### ISSUE TITLE
azurerm_application_gateway cannot use lifecycle ignore backend_address_pool

### ISSUE THREAD

**Issue by caiconkhicon** [hashicorp/terraform-provider-azurerm#10009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.14.0
AzureRM: 2.41.0

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

I want to create an `azurerm_application_gateway`, which is later on managed by an Application Gateway Ingress Controller (https://docs.microsoft.com/en-us/azure/application-gateway/ingress-controller-overview). Thus, I don't want/need to create any `backend_address_pool`, but I still have to add one of it, since it is required by the resource. To prevent TF from managing the gateway, I use `ignore_changes`

```hcl
resource "azurerm_application_gateway" "main" {
  name                = "aks"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 1
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.public.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Enabled"
    path                  = "/"
    port                  = 8080
    protocol              = "Http"
    request_timeout       = 60
  }

 lifecycle {
   ignore_changes = [backend_address_pool, http_listener, backend_http_settings, request_routing_rule, probe, tags]
 }
<OMITTED OUTPUT>
}
```

### Expected Behaviour

I created the application gateway some time ago using TF 0.12. Now, I update to 0.14 and rerun. I expect it to not show any change when running `terraform apply` (note that at this time, the Application Gateway already has many configurations created by the Ingress Controller). 

### Actual Behaviour

However, it fails with the error:

```
Error: backend_address_pool.0.fqdns: attribute supports 1 item as a minimum, config has 0 declared

  on ../../modules/shared-resources/main.tf line 53, in resource "azurerm_application_gateway" "main":
  53: resource "azurerm_application_gateway" "main" {

Error: "backend_address_pool.0.id": this field cannot be set

  on ../../modules/shared-resources/main.tf line 53, in resource "azurerm_application_gateway" "main":
  53: resource "azurerm_application_gateway" "main" {
```

### Steps to Reproduce

1.  Create an `azurerm_application_gateway` with minimal configuration (see the code above)
2. Setup an `Application Gateway Ingress Controller` to manage the gateway above
3. Rerun `terraform apply`

**Comment by neilfromit** [comment]
I'm attempting the same thing as @caiconkhicon . Use TF to provision a _base_ AGW and then hand over control of provisioning to the MS AGIC service. I'm seeing similar idempotency issues using `ignore_changes = all`:

```
Error: "gateway_ip_configuration.0.id": this field cannot be set
  on main.tf line 63, in resource "azurerm_application_gateway" "agw":
  63: resource "azurerm_application_gateway" "agw" {
##[error]Error: expected "request_routing_rule.0.redirect_configuration_name" to not be an empty string, got 
##[error]  on main.tf line 63, in resource "azurerm_application_gateway" "agw":
##[error]  63: resource "azurerm_application_gateway" "agw" {
##[error]
##[error]Error: expected "request_routing_rule.0.rewrite_rule_set_name" to not be an empty string, got 
##[error]  on main.tf line 63, in resource "azurerm_application_gateway" "agw":
##[error]  63: resource "azurerm_application_gateway" "agw" {
##[error]
##[error]
Error: "request_routing_rule.0.http_listener_id": this field cannot be set
  on main.tf line 63, in resource "azurerm_application_gateway" "agw":
  63: resource "azurerm_application_gateway" "agw" {
##[error]
##[error]Error: : invalid or unknown key: id
##[error]  on main.tf line 63, in resource "azurerm_application_gateway" "agw":
##[error]  63: resource "azurerm_application_gateway" "agw" {
```

In this instance I've reset and used the same version for both initial provisioning (which works fine) and further runs that produce the above:

Terraform: 0.14.0
AzureRM: 2.44.0

**Comment by mkprizzle** [comment]
Found this through internet search for a how-to for a similar AGIC use case, the latest TF or AzureRM provider this is not an issue and the lifecycle ignore is appropriately ignoring the listed attributes

**Comment by mbfrahry** [comment]
Thanks @mkprizzle for checking this works! I'm closing this down but feel free to reopen this if you're still seeing this issue @caiconkhicon
