### ISSUE TITLE
azurerm_network_security_rule source_application_security_group_ids documentation

### ISSUE THREAD

**Issue by JohnDelisle** [hashicorp/terraform-provider-azurerm#10016]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
2020-12-29T20:44:40.5444570Z [command]C:\hostedtoolcache\windows\terraform\0.14.3\x64\terraform.exe version
2020-12-29T20:44:40.7119016Z Terraform v0.14.3
2020-12-29T20:44:40.7121965Z + provider registry.terraform.io/hashicorp/azurerm v2.41.0
2020-12-29T20:44:40.7123454Z + provider registry.terraform.io/hashicorp/random v3.0.0

### Affected Resource(s)

* `azurerm_network_security_rule`

### Terraform Configuration Files

NA - see related issues for an example

### Debug Output

NA

### Panic Output

NA

### Expected Behaviour

Expected it to accept a list of more than one ID, as per the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule#source_application_security_group_ids), it should accept a list of multiple (implied by virtue of being a list...) Application Security Group IDs.

`source_application_security_group_ids - (Optional) A List of source Application Security Group ID's`

### Actual Behaviour
`Error: source_application_security_group_ids: attribute supports 1 item maximum, config has 2 declared`

### Steps to Reproduce

Create an NSG and some ASGs, and attempt to create an NSG rule with a list containing n>1 ASG IDs for the `source_application_security_group_ids` value.

### Important Factoids
I'm submitting this issue specifically for the documentation.  

There's an existing issue to correct the actual problem, but it's been open for more than a year and if I understand correctly the root-cause may be related to an Azure API issue preventing Terraform/ AzureRM Provider from specifying a list of more than 1 ID.  

My suggestion is to correct the documentation to align with the actual current capability, and once the issue has been resolved, update the documentation accordingly.  Or, at least make some reference in the documentation to this issue so as to prevent user confusion and frustration.

Suggestion (something like this would be helpful to users): 

```
source_application_security_group_ids - (Optional) A List of source Application Security Group IDs. NOTE - Current limitation/issue requires specifying a list of one and only one ID. See issue #5126.
```

### References
* #5126

**Comment by tombuildsstuff** [comment]
👋 

As mentioned [in this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/5126#issuecomment-2025084322) and [checking the documentation for the latest version of the Provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule#source_application_security_group_ids) this appears to be resolved - and as such I'm going to close this issue for the moment.

Thanks!
