### ISSUE TITLE
Resource "lock" in state "Destruction complete", but dependent resource failed to be deleted with error: "ScopeLocked"

### ISSUE THREAD

**Issue by terezbw** [hashicorp/terraform-provider-azurerm#10013]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.28
+ provider.azurerm v2.19.0

### Affected Resource(s)
azurerm_mysql_server
azurerm_mysql_firewall_rule
azurerm_mysql_configuration

azurerm_postgresql_server
azurerm_postgresql_firewall_rule

azurerm_management_lock

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12"
  required_providers {
    azurerm = ">= 2.19.0"
  }
}
resource "azurerm_mysql_server" "main" {
  name                = var.server_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku_name    = var.server_sku_name
  create_mode = var.server_create_mode
  storage_mb            = var.server_storage_mb
  backup_retention_days = var.server_backup_retention_days
  geo_redundant_backup_enabled = var.server_geo_redundant_backup_enabled
  auto_grow_enabled            = var.server_auto_grow_enabled
  ssl_enforcement_enabled      = var.server_ssl_enforcement_enabled
  administrator_login          = var.server_administrator_login
  administrator_login_password = var.server_administrator_login_password
  version                      = var.server_version
}

resource "azurerm_mysql_firewall_rule" "main" {
  count = length(var.firewall_rule_map)
  name                = keys(var.firewall_rule_map)[count.index]
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_server.main.name
  start_ip_address    = values(var.firewall_rule_map)[count.index][0]
  end_ip_address      = values(var.firewall_rule_map)[count.index][1]
}
resource "azurerm_mysql_configuration" "main" {
  count = length(var.configuration_map)
  name                = keys(var.configuration_map)[count.index]
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_server.main.name
  value               = values(var.configuration_map)[count.index]
}
resource "azurerm_management_lock" "lock_delete" {
  name       = "lock_on_delete"
  scope      = azurerm_mysql_server.main.id
  lock_level = "CanNotDelete"
  notes      = "Locked on deleting"

  depends_on = [
    azurerm_mysql_firewall_rule.main,
    azurerm_mysql_configuration.main,
  ]
}
```

```hcl
module "mysql_server_test1_service" {
  source = "git::ssh://LOCAL_GIT_REPO/swft/terraform-modules.git/azure_mysql"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  server_name = "test1-service-server-v1"
  server_administrator_login          = data.vault_generic_secret.env.data["test1_service_mysql_admin_login"]
  server_administrator_login_password = data.vault_generic_secret.env.data["test1_service_mysql_admin_password"]
  firewall_rule_map = {
    "reports_${var.env}_access_rule_v1" = ["X.X.X.X", "Y.Y.Y.Y"]
  }
}

```
### Expected Behaviour
All resources deleting in correct order, according depend_on:
1) azurerm_management_lock.lock_delete
2) azurerm_mysql_firewall_rule.main OR azurerm_mysql_configuration.main
3) azurerm_mysql_server.main

### Actual Behaviour

Probably it's azure bug. According logs first task finished:
04:01:18 module.mysql_server_test1_service.azurerm_management_lock.lock_delete: Destruction complete after 2s

But after ~12min, CI get errors:
04:13:17 Error: mysql.FirewallRulesClient#Delete: Failure sending request:
StatusCode=0 -- Original Error: autorest/azure: Service returned an error. 
Status=<nil> Code="ScopeLocked" Message="The scope
'/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/XXXXXXXX/providers/Microsoft.DBforMySQL/servers/test1-service-server-v1/firewallRules/test1_access_rule_v1'
cannot perform delete operation because following scope(s) are locked:
'/subscriptions/XXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/XXXXXXXX/providers/Microsoft.DBforMySQL/servers/test1-service-server-v1'.  Please remove the lock and try again."

We perform periodic task and drop all ours mysql and postgres servers and recreate it again. Sometimes all work smoothly, sometimes - not. In fact, each run can be different. We can failed with error described above with one or with 5 servers.
Look like azure API report " Destruction complete" too early, or has some kind of cache in resource state.
Interesting, but if we run 
```
terraform destroy -auto-approve || sleep 120 || terraform destroy  -auto-approve
```
 or 
```
terraform destroy -auto-approve -target=sql1 -targte=sql2.... ||  terraform destroy  -auto-approve
```
then all work.
We reported error in azure support too.

### Steps to Reproduce

1. `terraform destroy`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
