### ISSUE TITLE
azurerm_servicebus_subscription lock duration documentation incorrect

### ISSUE THREAD

**Issue by RyanObray** [hashicorp/terraform-provider-azurerm#10043]
### Terraform (and AzureRM Provider) Version

Terraform v0.14.3

### Affected Resource(s)

* `azurerm_servicebus_subscription`

### Documentation Location
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_subscription

### Problem Summary
This is a documentation issue more than a bug. The documentation states that the default value for the "lock duration" is "1 minute or P1M" which is not correct per the referenced ISO 8601 standard. The maximum value allowed by Azure is 5 minutes which if following the documentation would lead you to believe that "P5M" would be the correct way to set this value. However, running "terraform apply" will result in the following error:
```shell
Error: creating/updating Subscription: ... servicebus.SubscriptionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The string 'P5M' is not a valid TimeSpan value. ..."
```
What I found particularly vexing about this error is that even specifying the value as just "T5M" didn't work. The Azure Portal interface (even though 5 minutes is the max value) still provides fields for Days, Hours, Minutes and Seconds and it wasn't until I specified all of the values as "P0DT0H5M0S" that terraform apply actually worked. Here's a snippet of my working HCL:

```terraform
#Topic - Subscription
resource "azurerm_servicebus_subscription" "subName" {
  name                                  = "SubName"
  resource_group_name                   = azurerm_resource_group.topicId.name
  namespace_name                        = azurerm_servicebus_namespace.topicId.name
  topic_name                            = azurerm_servicebus_topic.topicId.name
  max_delivery_count                    = 10
  requires_session                      = true
  dead_lettering_on_message_expiration  = true
  default_message_ttl                   = "P30D" #Allow messages to live for 30 days
  lock_duration                         = "P0DT0H5M0S" #Set lock duration to max value of 5 minutes
  auto_delete_on_idle                   = "P10675198DT2H48M5.48S" #Want to never auto-delete after idle in this case
}
```
Again this is more of a documentation suggestion than it is a bug but this clarification would have saved me a lot of time spinning my wheels so I wanted to pass it on.

**Comment by devesh-badal** [comment]
Hi, I would like to contribute on this issue, Can I pick up this one?

**Comment by jpmicrosoft** [comment]
> Hi, I would like to contribute on this issue, Can I pick up this one?

@devesh-badal I started picking issues up and referencing them in the pull request. I am not aware of any formal request to work on issue process. I could be wrong but, this far this is how I have handled it. If I notice someone is working on it, I let it along. 

Happy Coding!

**Comment by devesh-badal** [comment]
Thanks @jpmicrosoft for guiding me :)

**Comment by devesh-badal** [comment]
Thanks @jpmicrosoft for guiding me :)
