### ISSUE TITLE
azurerm_mssql_virtual_machine should not require LUN for SQLTempDbSettings

### ISSUE THREAD

**Issue by spreegabe** [hashicorp/terraform-provider-azurerm#10054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* `azurerm_mssql_virtual_machine `

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_virtual_machine" "sqlvm" {
  virtual_machine_id               = azurerm_windows_virtual_machine.VM.id
  sql_license_type                 = local.mergedSqlServerConfig.sqlServerLicenseType
  r_services_enabled               = local.mergedSqlServerConfig.rServicesEnabled
  sql_connectivity_port            = 1433
  sql_connectivity_type            = "PRIVATE"
  sql_connectivity_update_password = local.mergedSqlServerConfig.adminpass
  sql_connectivity_update_username = local.mergedSqlServerConfig.adminuser
  dynamic "auto_patching" {
    for_each = local.mergedSqlServerConfig.sqlpatchingConfig.patchingEnabled == false ? [] : list(local.mergedSqlServerConfig.sqlpatchingConfig)
    content {
      day_of_week                             = auto_patching.value.dayOfWeek
      maintenance_window_duration_in_minutes  = auto_patching.value.maintenanceWindowDuration
      maintenance_window_starting_hour        =auto_patching.value.maintenanceWindowStartingHour
    }
  }
  storage_configuration {
    disk_type = "NEW"
    storage_workload_type = "OLTP"
    data_settings  {
      default_file_path  = "H:\\SQLData"
      luns  = [0,1]
    }
    log_settings   {
      default_file_path  = "G:\\SQLData"
      luns  = [2,3]
    }
    temp_db_settings {
      default_file_path  = "D:\\SQLTemp"
    }
  }

```
### Expected Behaviour

The underlying arm templates support not specifying a LUN for the tempdb only - not specifying a LUN tells ARM to use the locally attached temporary ssd device. 

### Actual Behaviour

```
Error: Missing required argument

  on ../../modules/azure/windows_vm_v2/option-25-sqlextension.tf line 43, in resource "azurerm_mssql_virtual_machine" "sqlvm":
  43:     temp_db_settings {

The argument "luns" is required, but no definition was found.
```
### Steps to Reproduce

1. `terraform validate`

### Important Factoids

The following ARM snippet of  is valid, but unable to be generated by terraform - 

```json
            "type": "Microsoft.SqlVirtualMachine/SqlVirtualMachines",
            "apiVersion": "2017-03-01-preview",
            "name": "[parameters('sqlVirtualMachineName')]",
            "location": "[parameters('sqlVirtualMachineLocation')]",
            "dependsOn": [
                "[resourceId('Microsoft.Compute/virtualMachines', parameters('sqlVirtualMachineName'))]"
            ],
            "properties": {
                "....snip....":"snipped exterranous arm",
                "StorageConfigurationSettings": {
                    "DiskConfigurationType": "NEW",
                    "StorageWorkloadType": "OLTP",
                    "SQLDataSettings": {
                        "LUNs": "[0,1]",
                        "DefaultFilePath": "F:\\data"
                    },
                    "SQLLogSettings": {
                        "LUNs": "[2,3]",
                        "DefaultFilePath": "G:\\log"
                    },
                    "SQLTempDbSettings": {
                        "DefaultFilePath": "D:\\tempDb"
                    }
                }
           }
```
### References

* #7341

**Comment by diego7marques** [comment]
Hi @spreegabe,

I had the same problem here and I found out a solution:

`temp_db_settings {
        default_file_path           = "D:\\temp"
        luns                               = []
}`

If you use an empty list ([]), it will pass through the validation and the tempdb will be created inside the temporary disk.

**Comment by diego7marques** [comment]
Hi @spreegabe,

I had the same problem here and I found out a solution:

```
temp_db_settings { 
    default_file_path = "D:\\temp"
    luns = [] 
}
```

If you use an empty list ([]), it will pass through the validation and the tempdb will be created inside the temporary disk as desired.

**Comment by spreegabe** [comment]
oh gosh I could swear I tried that but lemme give it a go and report back

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
