### ISSUE TITLE
Support for Azure Monitor Private Link Scope

### ISSUE THREAD

**Issue by ross-p-smith** [hashicorp/terraform-provider-azurerm#10059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow azurerm provider to create/update Azure Monitor Private Link Scope resources: [az cli reference](https://docs.microsoft.com/en-us/cli/azure/monitor/private-link-scope?view=azure-cli-latest). This is supported in the 2019-10-17 preview schema [here](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/monitor/resource-manager/Microsoft.Insights/preview/2019-10-17-preview/privateLinkScopes_API.json). But I don't believe it is in the Azure Go SDK.
 
Implementing this will enable use of Azure Monitor behind Private Endpoints.

### New or Affected Resource(s)

* azurerm_monitor

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_private_link_scope" "example" {
  name = "example"
  log_analytics_workspace_id = "law_id"
}
```

**Comment by tj-corrigan** [comment]
Depends on https://github.com/Azure/azure-sdk-for-go/issues/14090

**Comment by robertdias** [comment]
Deploying this for a large customer now and until this resource is added, we will have to attempt to use azurerm_template with an ARM for AMPLS.

**Comment by geekzter** [comment]
The resource has been [implemented](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_private_link_scope) in provider 2.85. However, it has no meaningful properties next to `name` and `resource_group_name`. I'm confused.

**Comment by geekzter** [comment]
I think we have to wait for [this PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14119) for the `azurerm_monitor_private_link_scoped_service` resource to get merged and released

**Comment by nick4fake** [comment]
@geekzter it has been merged

**Comment by LaurentLesle** [comment]
According to the AMPLS design document you can attach up to 300 log analytics workspaces or application insigight. Looks like the PR above only support 1 attachment. Is it a limitation of the SDK or shall I open a new issue https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-design

**Comment by davidsampson-hv** [comment]
> Right after clicking refresh, the second AMPL service resource provisions ok. Does anyone know what may be causing this? I am not seeing any options for location on this resource, but it shows global in the portal. Private Endpoint does not allow location to be global. Any thoughts?

Hi Laurent,

Long time no speak, I hope you're well! We are also experiencing this issue with the second workspace link, as you said the documentation is clear that up to 300 workspaces are supported so I think an issue should be opened for this. In the meantime does anyone know if it's possible to hit that refresh button programatically?

Regards,
David

**Comment by scott1138** [comment]
We are looking at deploying AMPLS and I am confused by the azurerm_monitor_private_link_scope having no access mode property.  Does it default to open?

**Comment by dawsonar802** [comment]
From what I have seen when deploying AMPLS it defaults ```Ingestion access mode``` to private and ```Query access mode``` to open.  For the actual resources like LA or App Insights, when using the ```azurerm_monitor_private_link_scoped_service``` resource it sets both the "Accept data ingestion from public networks not connected through a Private Link Scope" and "Accept queries from public networks not connected through a Private Link Scope" to No.

**Comment by kaovd** [comment]
Jumping on this thread as noticed its still open, ideally support for DCE's which are currently not meeting the rules validation would be nice. Elsewise doing the patchwork with azapi for now

**Comment by swati-delphix** [comment]
Is there any further update, as "Accept queries from public networks not connected through a Private Link Scope" is still setting default open ?

**Comment by rodmhgl** [comment]
Wow, 2021. Any update on this issue?
