### ISSUE TITLE
Importing an azurerm_virtual_network_peering leaves most properties null/empty in the Terraform state file

### ISSUE THREAD

**Issue by alexvy86** [hashicorp/terraform-provider-azurerm#10071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
```

### Affected Resource(s)

* `azurerm_virtual_network_peering`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~> 2.41.0"
    }
  }
  required_version = ">= 0.14"
}

provider "azurerm" {
  subscription_id = "<redacted>"
  features {}
}

resource "azurerm_virtual_network_peering" "my-peering" {
  name                         = "northcentralus-lab-vnet-to-southcentralus-lab-vnet"
  resource_group_name          = "network-lab-rg"
  virtual_network_name         = "northcentral-lab-vnet"
  remote_virtual_network_id    = "/subscriptions/<redacted>/resourceGroups/network-lab-rg/providers/Microsoft.Network/virtualNetworks/southcentralus-lab-vnet"
  allow_virtual_network_access = true
  allow_forwarded_traffic      = true
  allow_gateway_transit        = false
  use_remote_gateways          = true
}
```

### Expected Behaviour

After running `terraform import` to bring an existing resource into the state, the state file should show all the correct values for the peering.

### Actual Behaviour

The state is full of `null` and empty values (everything except the "source" VNet name + id and the resource group name), so `terraform plan` and `terraform apply` say they're going to make changes, when none should be required.

This is how `terraform.tfstate` looks right after the import (`terraform import azurerm_virtual_network_peering.my-peering /subscriptions/<redacted>/resourceGroups/network-lab-rg/providers/Microsoft.Network/virtualNetworks/northcentralus-lab-vnet/peerings/northcentralus-lab-vnet-to-southcentralus-lab-vnet`):

```
{
  "version": 4,
  "terraform_version": "0.14.3",
  "serial": 1,
  "lineage": "d1f7938a-aa48-f271-dde3-dbd7e47c4857",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "azurerm_virtual_network_peering",
      "name": "my-peering",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "allow_forwarded_traffic": null,
            "allow_gateway_transit": null,
            "allow_virtual_network_access": null,
            "id": "/subscriptions/<redacted>/resourceGroups/network-lab-rg/providers/Microsoft.Network/virtualNetworks/northcentralus-lab-vnet/peerings/northcentralus-lab-vnet-to-southcentralus-lab-vnet",
            "name": "",
            "remote_virtual_network_id": null,
            "resource_group_name": "network-lab-rg",
            "timeouts": {
              "create": null,
              "delete": null,
              "read": null,
              "update": null
            },
            "use_remote_gateways": null,
            "virtual_network_name": "northcentralus-lab-vnet"
          },
          "sensitive_attributes": [],
          "private": "<redacted>"
        }
      ]
    }
  ]
}
```

### Steps to Reproduce

1. Define an `azurerm_virtual_network_peering` resource that corresponds to an existing VNet peering.
2. Run `terraform import` to import the resource into the state.
3. State is wrong.

### Important Factoids

N/A

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
