### ISSUE TITLE
azurerm_virtual_machine_extension state incorrectly lost on "provisioning failure"

### ISSUE THREAD

**Issue by lawrencegripper** [hashicorp/terraform-provider-azurerm#10121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2

```
required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.41"
    }
    archive = {
      source  = "hashicorp/archive"
      version = "~> 2.0.0"
    }
  }
```

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
// Using this https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/dsc-windows
// to run a DSC configuration with will make sure the VM is running the container and
// periodically check for any issue and correct them. 
// See: https://docs.microsoft.com/en-us/powershell/scripting/dsc/overview/overview?view=powershell-7.1
resource "azurerm_virtual_machine_extension" "dscconfig" {
  name                       = "dscconfig${local.script_hash}"
  virtual_machine_id         = azurerm_windows_virtual_machine.vm.id
  publisher                  = "Microsoft.Powershell"
  type                       = "DSC"
  type_handler_version       = "2.77"
  auto_upgrade_minor_version = true

  depends_on = [azurerm_storage_blob.dscps1]

  settings = jsonencode(jsondecode(<<SETTINGS
    {
      "configuration": {
        "url": "https://${var.releases_storage_account_name}.blob.core.windows.net/${var.releases_container_name}/${local.script_zip}",
        "script": "dsc_config.ps1",
        "function": "DockerImageStart"
      }
    }
SETTINGS
  ))

  protected_settings = jsonencode(jsondecode(<<JSON
    {
      "configurationArguments": {
          "ScriptHash": "${local.script_hash}",
          "Image": "${var.image}",
          "Command": "${var.command}",
          "RegistryUrl": "${var.docker_registry_url}",
          "RegistryUsername": "${var.docker_registry_username}",
          "RegistryPassword": "${var.docker_registry_password}",
          "EnvironmentVariables": "${local.env_file}"
      },
      "configurationUrlSasToken": "${var.releases_storage_sas}"
    }
JSON
  ))

  lifecycle {
    ignore_changes = all
  }
}
```

### Expected Behaviour

I expect to be able to repeatedly perform `terraform apply`.

### Actual Behaviour

When the VM Extension creation is successful but the run is not successful terraform returns the following error (for other extension types the error may differ):

> Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'dscconfigf31a30215b006a348a6f4276e732e0ee'. Error message: \"The DSC Extension received an incorrect input: A parameter cannot be found that matches parameter name 'ScriptHash'.\r\n\r\nAnother common error is to specify parameters of type PSCredential without an explicit type. Please be sure to use a typed parameter in DSC Configuration, for example:\r\n\r\n    configuration Example {\r\n        param([PSCredential] $UserAccount)\r\n        ...\r\n    }.\r\nPlease correct the input and retry executing the extension.\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionDSCWindowsTroubleshoot "

The extension has been created in Azure at the point as exists with a provisioning state of `failed`.

![image](https://user-images.githubusercontent.com/1939288/104133226-1a762d00-537a-11eb-9fa6-31d7c7cdcce1.png)

However, Terraform has not tracked it's existence so when you next attempt a `terraform apply` the following error is presented:

> Error: A resource with the ID "/subscriptions/xxxxxxxxxxxx/resourceGroups/testenv21/providers/Microsoft.Compute/virtualMachines/xxxxxxxxxxxxxxxx-vm/extensions/dscconfigf31a30215b006a348a6f4276e732e0ee" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_machine_extension" for more information.

I think this error checking is to blame, it's treating deployment with an error on execution as a deployment error and assumes the extension wasn't created so no state is tracked.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/46da0a743a4dba74dd8514b580a6b79f0147d1d9/azurerm/internal/services/compute/virtual_machine_extension_resource.go#L165-L177

Is it possible to first track the creation by calling `d.SetId(*read.ID)` then return the provisioning error? If so I'm happy to update the code and submit a PR.

### Steps to Reproduce

1. `terraform apply` with the DSC extension (likely repos with other extensions) which containers a "runtime" error that will lead to the extension being created but `provisioning failed`
2. `terraform apply` and observe error

**Comment by jmeadowcroft** [comment]
@katbyte do you have any more information on this, or when it can be fixed?

**Comment by tombuildsstuff** [comment]
hi @lawrencegripper 

Thanks for opening this issue.

Terraform intentionally only tracks resources once the platform (this applies to all providers AWS, Azure etc) has both Successfully deployed the resource and it's also ready for use (for example the DNS Name is replicated etc). Within the Azure Platform that means a `ProvisioningState` of `Succeeded` - since a `ProvisioningState` of `Failed` can mean multiple things - including both "this resource will never recover" and "this resource may become available later".

Due to the fact that the Azure API can be ambiguous in the meaning of "Failed" that varies on a per-Resource Provider basis, unfortunately Terraform has no means of knowing whether a particular resource will become available at a given point in time - as such it's unfortunate but we require the user to determine if this resource will recover or not (since redeploying this resource, or deleting + reprovisioning could cause a further outage for example).

As such whilst I'd like to thank you for opening this issue, since this is an intentional behaviour at this time I'm going to close this issue for the moment.

Thanks!
