### ISSUE TITLE
False drift resulting from blank retention_policy for azurerm_monitor_diagnostic_setting

### ISSUE THREAD

**Issue by futureviperowner** [hashicorp/terraform-provider-azurerm#10135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform v0.13.2
* AzureRM v2.33.0 

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "kv_monitor" {
  name                       = "kv-monitor-diagnostics"
  target_resource_id         = azurerm_key_vault.key_vault.id
  log_analytics_workspace_id = var.log_analytics_workspace_id

  log {
    category = "AuditEvent"
    enabled  = true
  }

  metric {
    category = "AllMetrics"
  }
}
```

### Expected Behaviour

After successfully applying these changes, re-running `terraform plan` should not show any changes.

### Actual Behaviour

Re-running `terraform plan` results in a diff as terraform believes it needs to remove the default `retention_policy` that is stored off in the state.

### Steps to Reproduce

1. Create an azurerm_monitor_diagnostic_setting that sends diagnostics to a key vault.
2. `terraform apply`
3. Run `terraform apply` again.

### Important Factoids

The documentation Azure Monitor diagnostics settings says that the retention policy only applies when sending the data to a Storage Account: https://docs.microsoft.com/en-us/azure/azure-monitor/platform/diagnostic-settings

The Terraform documentation for the provider says the `retention_policy` is optional: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
