### ISSUE TITLE
Support for Custom Azure APIPA BGP IP address

### ISSUE THREAD

**Issue by ElliottLW** [hashicorp/terraform-provider-azurerm#10149]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, there does not appear to be an option within the BGP block to configure "Custom Azure APIPA BGP IP address" as a result additional work is required during each deployment/update.

Would be great to have this option available. 

### New or Affected Resource(s)

azurerm_virtual_network_gateway
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway 
### Potential Terraform Configuration

```hcl
  bgp_settings {

    peering_address   = var.vpn_bgppeerip
    asn               = var.vpn_bgpasn
    peer_weight       = 1
    apipa_bgp_ip      = var.vpn_bgpapipa

  }  

```

### References

* #0000

**Comment by dmichel1** [comment]
You can set the APIPA address via a new field called [peering_addresses](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway#apipa_addresses).

**Comment by ElliottLW** [comment]
> You can set the APIPA address via a new field called [peering_addresses](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway#apipa_addresses).

Thanks dmichel1!
