### ISSUE TITLE
App Service service_tag in ip_restriction is optional in documentation

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform-provider-azurerm#10168]
Hi,

On the documentation we have

A ip_restriction block supports the following:
*    ip_address - (Optional) The IP Address used for this IP Restriction in CIDR notation.
*    service_tag - (Optional) The Service Tag used for this IP Restriction.
*    virtual_network_subnet_id - (Optional) The Virtual Network Subnet ID used for this IP Restriction.

But if don't define service_tag we have an error (I've define ip_address)
```
Inappropriate value for attribute "ip_restriction": element 0: attribute
"service_tag" is required.
```

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0
+ provider registry.terraform.io/hashicorp/external v2.0.0
+ provider registry.terraform.io/hashicorp/vault v2.16.0
```

### Affected Resource(s)

* `azurerm_app_service`

**Comment by sharebear** [comment]
Can you provide your config? I didn't change any of the existing acceptance tests, which should have caught this.

**Comment by sharebear** [comment]
Wait a second, there's something else strange, support for service_tag was added in v2.42.0 but you write that you are using v2.40.0

**Comment by kinwolfqc** [comment]
I have the same problem.  Updated the code to use v2.4x of azurerm(we previously used 2.20) and now terraform complains that the attributes service_tag and subnet"id are required
```
Inappropriate value for attribute "ip_restriction": element 0: attributes
"service_tag" and "subnet_id" are required.
```

**Comment by kinwolfqc** [comment]
Upon further investigation, the problem started to happen with 2.23 with this PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/7945

**Comment by sharebear** [comment]
Interesting error message and perhaps the documentation needs updating but I write ip_restriction as a block, not as a list... I quickly pulled this from the acceptance tests

```
  site_config {
    ip_restriction {
      ip_address = "10.10.10.10/32"
      name       = "test-restriction"
      priority   = 123
      action     = "Allow"
    }
  }
```

That's a very unhelpful error message though...

**Comment by sharebear** [comment]
This document seems to explain the issue you're experiencing https://www.terraform.io/docs/configuration/attr-as-blocks.html?_ga=2.165843772.309788729.1611063859-1978276004.1597053240#arbitrary-expressions-with-argument-syntax

> Because of the rule that argument declarations like this fully override any default value, when creating a list-of-objects expression directly the usual handling of optional arguments does not apply, so all of the arguments must be assigned a value, even if it's an explicit null

**Comment by sharebear** [comment]
Based on the last documentation then if you want to keep your current syntax you need to write

```hcl
    ip_restriction = [
      {
        ip_address                = "xxx.xxx.xxx.xxx/xx" 
        virtual_network_subnet_id = null #ne devrait pas être requis, mais terraform se plaint
        subnet_id                 = null
        service_tag               = null
        name                      = "Utilisateurs "
        priority                  = 300
        action                    = "Allow"
      },
    ]
```

or change to the recommended syntax

```hcl
    ip_restriction {
        ip_address                = "xxx.xxx.xxx.xxx/xx" 
        name                      = "Utilisateurs "
        priority                  = 300
        action                    = "Allow"
    }
```

**Comment by kinwolfqc** [comment]
Dunno if that was the OP problem, but for me, the block syntax worked, thanks!  

Strange though, as I clearly remember when I wrote that code months ago that a block didn't work, I had to write it as an argument.  Stuff change so fast...!

**Comment by roanp** [comment]
`ip_restriction = [ {

     action = "Allow"
     ip_address = "8.8.8.8/32"
     name = "Allow Roan Paes network"
     priority = 1
     service_tag = null
     subnet_id = null
     virtual_network_subnet_id = null
  } ]
`

  The above worked for me. I'm now figuring a way of restricting multiple networks, if anyone has a clue I would very much appreciate it.

**Comment by Jay-Funk** [comment]
I was seeing the same issue with App Service v1.2.2. **Upgrading the App Service to 1.2.4** fixed it for me so that I could just use the list style, i.e.:
```
ip_restrictions = [
     "192.168.0.1/24",
     "193.168.0.1/24",
     ...
]
```

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
