### ISSUE TITLE
Azure RM Windows VM Documentation has a dead link

### ISSUE THREAD

**Issue by lazarillo** [hashicorp/terraform-provider-azurerm#10172]
The standard template seemed inappropriate for this small issue.

Upon clicking on the "using the features setting within the Provider block" text at the top of [`azurerm_windows_virtual_machine`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine) documentation, it goes to a dead link.

I *suspect* it is meant to go to this link:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#virtual_machine

**Comment by Sheetalsingh23** [comment]
@katbyte Is this issue still unresolved? If yes, can I work on it?

**Comment by Sheetalsingh23** [comment]
@lazarillo

**Comment by psawant29** [comment]
working on this issue

**Comment by jpmicrosoft** [comment]
It seems this has been resolved. @Sheetalsingh23  @psawant29  @katbyte
