### ISSUE TITLE
count - resource "azurerm_lb"  not single threaded

### ISSUE THREAD

**Issue by 802856294** [hashicorp/terraform-provider-azurerm#10178]
Count was used to deploy an Azure Load Balancer 2.42.0. Code works deploying a load balancer with a single front end IP configuration. But, errors when creating an LB with multiple front end. seems as those the looping contructs do not complete an iteration before going on to the next.

[1m[31mError: [0m[0m[1mcreating/Updating Load Balancer "lb_azureew_01_name" (Resource Group "BT-CAF-uksouth-1-bt-loadbalancer-rg"): 
Code="Canceled" Message="Operation was canceled." Details=[{"code":"CanceledAndSupersededDueToAnotherOperation","message":"Operation 
PutLoadBalancerOperation (2bb6331f-bae3-4f6b-8476-ad6006324aff) was canceled and superseded by operation PutLoadBalancerOperation 
(86315f97-9aec-4c08-9dd4-46305328899e)."}][0m
[0m  on ..\core_modules\resources\loadbalancers\new_loadbalancer\new_loadbalancer_with_probes_rules_backend_pools\new_loadbalancer_with_probes_rules_backend_pools.tf line 82, in resource "azurerm_lb" "resource_new_load_balancer":
  82: resource "azurerm_lb" "resource_new_load_balancer"
Code

don't believe dynamic code blocks and for_each would solve this.
resource "azurerm_lb" "resource_new_load_balancer" {

  name       = var.name
  location   = var.location
  resource_group_name = module.get_resource_group_name_deploy.result
  sku = var.sku

  count = length(var.frontend_ip_configurations)
  frontend_ip_configuration {
           name = lookup(var.frontend_ip_configurations,element(keys(var.frontend_ip_configurations), count.index)).frontend_ip_configuration_name

           subnet_id =  module.get_public_ip_id_from_public_ip_ids[count.index].result == null ? module.get_subnet_id_deploy.result : null

           private_ip_address_allocation = lookup(var.frontend_ip_configurations,element(keys(var.frontend_ip_configurations), count.index)).frontend_ip_configuration_private_ip_address_allocation 

           private_ip_address = lookup(var.frontend_ip_configurations,element(keys(var.frontend_ip_configurations), count.index)).frontend_ip_configuration_private_ip_address

           private_ip_address_version = lookup(var.frontend_ip_configurations,element(keys(var.frontend_ip_configurations), count.index)).frontend_ip_configuration_private_ip_address_version 
           public_ip_address_id       = module.get_public_ip_id_from_public_ip_ids[count.index].result
  }
}

Data
         loadbalancer_1 ={
          name               = var.loadBalancerName,
          location           = var.location,
          resource_group_key = "loadbalancer",
          subnet_id_key = {
            subnet_id_key_1 = {
              network_key = "transit-vnet",
              subnet_key  = "snet-transit-trust"
            }
          },
          sku = "Standard",
          frontend_ip_configurations = {
            frontend_ip_configuration_1 = {
              frontend_ip_configuration_name                          = "${var.loadBalancerName}-fe-1",
              frontend_ip_configuration_private_ip_address_allocation = "Static",
              frontend_ip_configuration_private_ip_address            = cidrhost(cidrsubnet(var.address_space, 3, 3), 7),
              frontend_ip_configuration_private_ip_address_version    = "IPv4",
              public_ip_address_id_key                                = null,
              backend_pools = {
                backend_pool_1 = {
                  backend_pool_name  = "${var.loadBalancerName}-bep-1",
                  network_interfaces = [{ "vm_key" = "firewall1", "nic_key" = "firewall1-eth-2" }, { "vm_key" = "firewall2", "nic_key" = "firewall2-eth-2" }]

                }
              },
              probes = {
                probe_1 = {
                  probe_name                = "http-running-probe-1",
                  probe_protocol            = "Tcp",
                  probe_port                = 80,
                  probe_interval_in_seconds = 5,
                  probe_number_of_probes    = 2
                }

              },
              load_balancer_rules = {
                load_balancer_rules_2 = {
                  load_balancer_rule_name          = "${var.loadBalancerName}-rle-1",
                  load_balancer_rule_protocol      = "All",
                  load_balancer_rule_frontend_port = 0,
                  load_balancer_rule_backend_port  = 0,

                  load_balancer_rule_backend_pool_key = "backend_pool_1",

                  load_balancer_rule_probe_key                     = "probe_1",
                  load_balancer_rule_frontend_ip_configuration_key = "frontend_ip_configuration_1"

                  load_balancer_rule_enable_tcp_reset        = false,
                  load_balancer_rule_enable_floating_ip      = false,
                  load_balancer_rule_idle_timeout_in_minutes = 4,
                  load_balancer_rule_load_distribution       = "Default"

                }

              }
            },

            frontend_ip_configuration_2 = {
              frontend_ip_configuration_name                          = "${var.loadBalancerName}-fe-2",
              frontend_ip_configuration_private_ip_address_allocation = "Static",
              frontend_ip_configuration_private_ip_address            = cidrhost(cidrsubnet(var.address_space, 3, 3), 4),
              frontend_ip_configuration_private_ip_address_version    = "IPv4",
              public_ip_address_id_key                                = null,
              backend_pools = {
                backend_pool_1 = {
                  backend_pool_name  = "${var.loadBalancerName}-bep-2",
                  network_interfaces = [{ "vm_key" = "firewall1", "nic_key" = "firewall1-eth-2" }, { "vm_key" = "firewall2", "nic_key" = "firewall2-eth-2" }]

                }
              },
              probes = {
                probe_1 = {
                  probe_name                = "http-running-probe-2",
                  probe_protocol            = "Tcp",
                  probe_port                = 80,
                  probe_interval_in_seconds = 5,
                  probe_number_of_probes    = 2
                }
              },
              load_balancer_rules = {
                load_balancer_rules_2 = {
                  load_balancer_rule_name          = "${var.loadBalancerName}-rle-2",
                  load_balancer_rule_protocol      = "All",
                  load_balancer_rule_frontend_port = 0,
                  load_balancer_rule_backend_port  = 0,

                  load_balancer_rule_backend_pool_key = "backend_pool_1",

                  load_balancer_rule_probe_key                     = "probe_1",
                  load_balancer_rule_frontend_ip_configuration_key = "frontend_ip_configuration_2"

                  load_balancer_rule_enable_tcp_reset        = false,
                  load_balancer_rule_enable_floating_ip      = false,
                  load_balancer_rule_idle_timeout_in_minutes = 4,
                  load_balancer_rule_load_distribution       = "Default"

                }

              }
            }

          }
        }

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
