### ISSUE TITLE
Azure DPS linked hub is failing with "iot hub not found error" and status code is 401001

### ISSUE THREAD

**Issue by vin4git** [hashicorp/terraform-provider-azurerm#10224]
**Issue:** I had created the iothub and dps services with terraform. During integration tests, we are registering the device in the DPS service. However, these tests are working well with the manually created resources both IoTHub and DPS services. But, the same resources (IoTHub & DPS) which were created with terraform is having issues with the linked hub and the error message is "iothub not found" with status code as 401001. The tests will only work with terraform created resources upon manually linking the iothub with the DPS service. 

**Terraform version: _0.14.0_
Azure RM: _2.42.0_**

Below is the terraform code that is used to create the DPS:

resource "azurerm_iothub_dps" "my1dps" {
  name                = "my1dps"
  resource_group_name = azurerm_resource_group.my1.name
  location            = azurerm_resource_group.my1.location

  sku {
    name     = "S1"
    capacity = 1
  }

  linked_hub {
    connection_string = data.azurerm_iothub_shared_access_policy.my1iothub_iothubowner.primary_connection_string
    location          = azurerm_iothub.my1iothub.location
  }

  depends_on = [azurerm_iothub.my1iothub]
}

data "azurerm_iothub_shared_access_policy" "my1iothub_iothubowner" {
  name                = "iothubowner"
  resource_group_name = azurerm_resource_group.my1.name
  iothub_name         = azurerm_iothub.my1iothub.name
}

Let me know if need any further details. Thanks!

**Comment by oliverchristen** [comment]
I've got the same problem. Works with manual linking but not through Terraform.

**Comment by ssatheeshkumar** [comment]
Yes, got the same issue too. Manual linking works great but having linked IoT Hub in terraform template as part of dps results in "Iot Hub not found" and status code 401001.

**Comment by jphines57** [comment]
I'm having the same issue when my device attempts to connect to the IoT Hub. I use Terraform 0.14.10 to create the DPS. Error Msg: IoTHub not found even though it was able to connect to the DPS, just not the IoT Hub.

**Comment by gabrielSoudry** [comment]
Same problem here :'(

**Comment by yothoon** [comment]
I have exactly the same problem. TF 0.15.3 azure_rm 2.61.0
