### ISSUE TITLE
Support for setting Network Security Group for AKS cluster/nodepool

### ISSUE THREAD

**Issue by josephbmanley** [hashicorp/terraform-provider-azurerm#10233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently you cannot configure the network security group attached to your AKS cluster with the `azurerm` provider. Certain services need public node access, such as game servers, as well as allowing additional security.

With public node ips currently supported, it makes sense to be able to configure what on those nodes can be accessed.

### New or Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`
* `azurerm_kubernetes_cluster`

### Potential Terraform Configuration

```hcl

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
    network_security_group {
        name                = "exampleAksSecurityGroup"
        location            = azurerm_resource_group.example.location
        resource_group_name = azurerm_resource_group.example.name
      
        security_rule {
          name                       = "allowAllTcp"
          priority                   = 100
          direction                  = "Inbound"
          access                     = "Allow"
          protocol                   = "Tcp"
          source_port_range          = "*"
          destination_port_range     = "*"
          source_address_prefix      = "*"
          destination_address_prefix = "*"
        }
      
        tags = {
          environment = "Production"
        }
    }
  }
```

### References

* AKS docs on NSGs: https://docs.microsoft.com/en-us/azure/aks/concepts-network#network-security-groups
* Workaround discussion: https://stackoverflow.com/questions/53601223/terraform-specify-network-security-group-rules-when-creating-an-aks-cluster-usi

**Comment by aristosvo** [comment]
👋🏽  @josephbmanley I want to help you, can you give me more requirements if below solution doesn't work out?

I think it is pretty clear that the configuration as desired is not something supported by Azure in the way you want it: 

> A network security group filters traffic for VMs, such as the AKS nodes. As you create Services, such as a LoadBalancer, the Azure platform automatically configures any network security group rules that are needed. Don't manually configure network security group rules to filter traffic for pods in an AKS cluster. Define any required ports and forwarding as part of your Kubernetes Service manifests, and let the Azure platform create or update the appropriate rules. You can also use network policies, as discussed in the next section, to automatically apply traffic filter rules to pods.

However, it should be possible within the current setup by simple creating a Kubernetes Service to those ports you want to disclose.

For instance, when I deploy a ingress controller, the creation of the Kubernetes Service triggers the creation of an IP address/Loadbalancer with its NSG. By creating a Kubernetes Service (type LoadBalancer) which maps to the wanted pod port and with `loadBalancerSourceRanges` specified, a similar setup for your custom destination can be specified.

**Comment by josephbmanley** [comment]
Hi @aristosvo, that does not fit my needs unfortunately. Think game severs, where the match maker allocates a server and provides the client with an IP and Port to connect to.

So, rather than having a LoadBalancer, I have something similar to dynamically allocated NodePorts using [Agones](https://github.com/googleforgames/agones/). I've enabled public node IPs (preview feature) and now I should be able to update the NSG in Terraform to support the Agones port range.

**Comment by josephbmanley** [comment]
As a note, I was able to get this to work using an an external data resource to lookup the NSG name, but it would be preferable if that could all stay in `azurerm`

**Comment by aristosvo** [comment]
Ah, check! The problem is then in this case the Azure API, which doesn't have the possibility to enable your proposed way of working. I suspect that even then the NSG will be configured from inside out, but I'm not sure how. When configuring NodePorts, does it not change the NSG for your public node IPs?

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: MyApp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80
      targetPort: 80
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
```

To be honest, your current setup is a bit dangerous, as periodically the NSG will be reset to the initial configuration, leaving your clients disconnected.

**Comment by josephbmanley** [comment]
> Ah, check! The problem is then in this case the Azure API, which doesn't have the possibility to enable your proposed way of working. I suspect that even then the NSG will be configured from inside out, but I'm not sure how. When configuring NodePorts, does it not change the NSG for your public node IPs?

So, none of the resources I am deploying make changes to the NSG.

> To be honest, your current setup is a bit dangerous, as periodically the NSG will be reset to the initial configuration, leaving your clients disconnected.

What would cause that?

**Comment by aristosvo** [comment]
Can you give me the complete configuration of AKS? I'm quite sure this is not a Terraform question, but an AKS question.

To first answer your question what would cause that: reconciliation of AKS. I believe this is in general only done with updates, but not limited to. If you configure an ingress controller with access to your pods and access rules configured on it, it will touch this AKS managed NSG.

The solution for your problem might be to bring your own VNet and subnet, instead of using the default AKS configuration. In a default setup the AKS managed NSG is associated with both the default provided subnet and all network interfaces of the AKS Loadbalancers. By bringing your own VNet and a subnet within that VNET, the AKS managed NSG (which is by default provided) is not associated with your subnet (but only with the network interfaces you are not using), and you can configure a different NSG on your own provided subnet.

I'm not 100% sure this will work, as I haven't tried it out (yet), but this is a beter solution than changing the AKS managed NSG _if_ it works 😃 

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-aks-resources"
  location = var.location
}

resource "azurerm_virtual_network" "example" {
  name                = "${var.prefix}-vnet"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["192.168.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "${var.prefix}-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  address_prefixes     = ["192.168.1.0/24"]
  virtual_network_name = azurerm_virtual_network.example.name
}

resource "azurerm_network_security_group" "example" {
  name                = "${var.prefix}-aks-nsg"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  security_rule {
    name                       = "Web-Traffic-Allowed"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_ranges    = ["80", "443"]
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_subnet_network_security_group_association" "example" {
  subnet_id                 = azurerm_subnet.example.id
  network_security_group_id = azurerm_network_security_group.example.id
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-aks"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "example-dns-prefix"

  default_node_pool {
    name           = "examplepool"
    node_count     = 2
    vm_size        = "Standard_B2s"
    vnet_subnet_id = azurerm_subnet.example.id
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "Standard"
  }
}
```

**Comment by josephbmanley** [comment]
> Can you give me the complete configuration of AKS? I'm quite sure this is not a Terraform question, but an AKS question.

> The solution for your problem might be to bring your own VNet and subnet, instead of using the default AKS configuration. In a default setup the AKS managed NSG is associated with both the default provided subnet and all network interfaces of the AKS Loadbalancers. By bringing your own VNet and a subnet within that VNET, the AKS managed NSG (which is by default provided) is not associated with your subnet (but only with the network interfaces you are not using), and you can configure a different NSG on your own provided subnet.

So, I am currently using my own custom network that is setup to allow traffic, the current NSG I am having issues with is attached to the node pool's network interfaces. So, I'd like to be able to modify that using Terraform in someway natively.

It make make since to wait for better support from Azure, but it does mean that currently that certain architectures are not compatible with Terraform.

**Comment by aristosvo** [comment]
Can you please elaborate a bit more what your problem still is? It's not really clear what your current test setup is and which problems you are facing.

**Comment by josephbmanley** [comment]
So here is the visual:

![Diagram](https://lucid.app/publicSegments/view/d97baa2a-b96f-4b67-ab65-defc367541eb/image.png)

- I need to be able to directly access the nodes (which have public IPs)
- My subnet security group allows *
- AKS, generates NSGs attached to the network interfaces of VMs that blocks traffic

My desired solution is to be able to modify or set the NSG attached to the VMs, so that my users can access the nodes.

**Comment by aristosvo** [comment]
Ouch, I expected the VMSS interfaces not to be bound to the AKS generated NSG 😔. Thus far it seems the only option to add rules to the AKS generated NSG, which is not something I would do lightly. But, if I would do it, I'd suggest to do it by doing a lookup of the NSGs in your node pool resource group:

```hcl
data "azurerm_resources" "example" {
  resource_group_name = azurerm_kubernetes_cluster.example.node_resource_group

  type = "Microsoft.Network/networkSecurityGroups"
}

output name_nsg {
    value = data.azurerm_resources.example.resources.0.name
}

resource "azurerm_network_security_rule" "example" {
  name                        = "example"
  priority                    = 100
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_kubernetes_cluster.example.node_resource_group
  network_security_group_name = data.azurerm_resources.example.resources.0.name
}
```

I think this is the best Azure (and Azure TF provider) can offer you at this moment.

**Comment by josephbmanley** [comment]
> I think this is the best Azure (and Azure TF provider) can offer you at this moment.

Thanks @aristosvo, I appreciate all of your help and activity on this issue. Hopefully there will be an official solution here soon.

**Comment by WeetA34** [comment]
This solution could be perfect if azurerm_resources was reliable.
But it’s not the case. Sometimes you have to wait multiple minutes before having the security group returned in data source result :(

**Comment by dzmitry-lahoda** [comment]
I have to wait more then 15 minutes on westeu before automatically created rg groups starts to be visible. It really hampers automatic cluster provisioning.

**Comment by dzmitry-lahoda** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/issues/10233

**Comment by tombuildsstuff** [comment]
👋 

Unfortunately this functionality currently isn't supported by the AKS API - as such to be able to add this to Terraform we'd need this field to be exposed in the AKS API, as such [would you mind opening an issue on the AKS Repository](https://github.com/Azure/AKS) where someone from that team should be able to take a look?

Since this requires changed in the upstream AKS API, for the moment I'm going to close this issue - but once this functionality is available in the upstream AKS API then we can reopen this and take another look.

Thanks!
