### ISSUE TITLE
azurerm_app_service "source_control": conflicts with site_config.0.scm_type

### ISSUE THREAD

**Issue by SylvainMartel** [hashicorp/terraform-provider-azurerm#10237]
I have looked everywhere, there are no example on how to set the source_control in azurerm_app_service and so far, all my tries have resulted in a failure to configure the source_control when scm_type is set to ExternalGit .  Reading different issues, it's not even clear it is really supported even though the setting is in the doc? 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.13.5
AzureRm: 2.43

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "app_service" {
  name                    = "app-${local.namespace}"
  location                = azurerm_resource_group.default.location
  resource_group_name     = azurerm_resource_group.default.name
  app_service_plan_id     = azurerm_app_service_plan.service_plan.id
  client_affinity_enabled = false

  site_config {
    java_version           = "11"
    java_container         = "TOMCAT"
    java_container_version = "9.0"
    always_on              = true
    scm_type               = "ExternalGit"
  }

  source_control  {
      repo_url = "https://${var.Token}@editedUrltoRepo"
      branch   = "master"
    }
 
```

### Debug Output

https://gist.github.com/kinwolfqc/cb45dfaaddb337ac1163680ac31f82e7
### Actual Behaviour
Being able to configure the git repo for the app service code deployment

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by kinwolfqc** [comment]
I found the problem while debugging this with hashicorp support.
When configuring the source_control block, you cannot set the scm_type in the site_config.  In my case, simply setting the source_control like this would set the scm type to ExternGit by itself.
```
  source_control {
    repo_url           = "https://<edited>"
    branch             = "master"
    manual_integration = true
  }
```
notice that in site_config, `scm_type` is commented out.  If I remove the comment, I get the error described in the 1st post.
```
site_config {
    java_version           = "11"
    java_container         = "TOMCAT"
    java_container_version = "9.0"
    always_on              = true
    #scm_type               = "ExternalGit"
  }
```
Totally counter-intuitive if you ask me!  The doc should be clarified, or the resource behavior should be changed to allow us to set scm_type.  The later is the best solution IMHO as I do not trust the code to always select the right scm type by itself.

**Comment by thomaskennedy1066** [comment]
Thanks - just ran into this problem

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
