### ISSUE TITLE
Support for Zone-Redundancy on Azure Container Registry (ACR)

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#10279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ACR (azurerm_container_registry) should allow to configure the new availability zone redundancy.

### New or Affected Resource(s)

* azurerm_container_registry

### References

https://docs.microsoft.com/en-us/azure/container-registry/zone-redundancy

**Comment by ruandersMSFT** [comment]
Needs a newer Container Registry API to be published + support of newer version added to Azure SDK for Go to add Zone Redundant property.  Published API is still version [2019-05-01](https://docs.microsoft.com/en-us/rest/api/containerregistry/registries/create).

**Comment by GinSiuCheng** [comment]
This support is available in the latest azure provider: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry#zone_redundancy_enabled
