### ISSUE TITLE
azurerm_data_factory drops Git integration on apply when there aren't changes

### ISSUE THREAD

**Issue by davejhahn** [hashicorp/terraform-provider-azurerm#10288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
+ provider.azuread v0.11.0
+ provider.azurerm v2.30.0

### Affected Resource(s)

* `azurerm_data_factory`

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory" "ingest" {
  name                = var.azure_data_factory_ingest_name
  location                    = azurerm_resource_group.ingest_rg.location
  resource_group_name         = azurerm_resource_group.ingest_rg.name

  # ONLY USE FOR DEVELOPMENT
  dynamic "vsts_configuration" {
    for_each = var.azure_data_factory_ingest_vsts_config
    content {
      account_name = var.azure_data_factory_ingest_vsts_account_name
      branch_name = var.azure_data_factory_ingest_vsts_branch_name
      project_name = var.azure_data_factory_ingest_vsts_project_name
      repository_name = var.azure_data_factory_ingest_vsts_repository_name
      root_folder = var.azure_data_factory_ingest_vsts_root_folder
      tenant_id = var.azure_tenant_id
    }
  }
}


```

### Actual Behaviour

Git is configured, verified, in Azure Data Factory.   A terraform plan is run, creating an plan output file, which determines there are NO changes (nothing at all).  When the plan is applied (as part of a pipeline), Git is no longer connected.   Looking at the Activity Log in Azure, it indicates that AZDO pipeline credentials modified AZDF yet the only thing run is the terraform plan file that has no changes.

### Steps to Reproduce

1. Create a repo for AZDF
2 Create a AZDF instance with terraform using azurerm_data_factory and adding vsts_configuration with the necessary paramters to connect to the repo created above, using plan and creating a file, then applying.
3. Verify the repo is connected afterwards
4. Run terraform plan again, creating a plan file, and verify that there are NO CHANGES
5. Apply the new plan file
6. Look at the Git connection in AZDF, it is no longer connected.

Note: Exit out of AZDF authoring after verifying in #3 and go back in for #6

### References

* #0000

**Comment by dvansteenburg** [comment]
@davidjhahn, I added...

```
  lifecycle {
    ignore_changes = [
      vsts_configuration
    ]
  }
```
to prevent terraform from changing/removing the GIT integration setting once the Data Factory account was created.

**Comment by jarnawer** [comment]
@dvansteenburg unfortunately that doesn't fix the issue. I tried it, because I have the same problem that @davejhahn and in my case adding tags in azurerm_data_factory resource, applies those tags, and drops git integration. And there are no changes in the generated plan for the vsts_configuration, but terraform drops it anyway

**Comment by jarnawer** [comment]
@dvansteenburg unfortunately that doesn't fix the issue. I tried it, with no luck. I also forced changes adding tags in the azurerm_data_factory, they get listed on the plan, but then tags are applied and terraform also drops git integration anyway.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
