### ISSUE TITLE
Azurerm_storage_share , argument 'access tier' is not available

### ISSUE THREAD

**Issue by svsunil** [hashicorp/terraform-provider-azurerm#10297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* ` azurerm_storage_share `

### Terraform Configuration Files

resource "azurerm_storage_account" "fs_storage_account" {
  name                     = "sttempdata"
  resource_group_name      = "rg-temp-dev"
  location                 = "westeurope"
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
  min_tls_version          = "TLS1_2"
  access_tier              = "Hot"
}

resource "azurerm_storage_share" "datashare" {
  name                 = "fs-datashare"
  storage_account_name = azurerm_storage_account.fs_storage_account.name
  quota                = 2048
}

### Expected Behaviour

I need file share to be created with access tier’ Hot’.

### Actual Behaviour

Resource type ’ azurerm_storage_share’ is creating a file share in storage account with default tier ‘Transaction optimized’. 
Resource type ’ azurerm_storage_share’ is not supporting ‘access tier’ argument currently.

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_share#argument-reference

**Comment by davmhelm** [comment]
Appears related to Issue #8716 as well.

**Comment by Kiwi-dave** [comment]
Can this feature please be added, we have a need for it.

**Comment by mbfrahry** [comment]
It looks like this was added in v3.6.0 of the provider with #16462! I'm going to go ahead and close this down but feel free to reopen it if you're still seeing issues
