### ISSUE TITLE
azurerm_postgresql_server - public_network_access_enabled = false not applied when creating replica

### ISSUE THREAD

**Issue by jgreat** [hashicorp/terraform-provider-azurerm#10293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
```

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.43.0"
    }
  }
  required_version = "~> 0.14"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "pg" {
  name     = "my-pg-resources"
  location = "canadacentral"
}

resource "azurerm_postgresql_server" "writer" {
  name                = "${azurerm_resource_group.pg.name}-writer"
  location            = azurerm_resource_group.pg.location
  resource_group_name = azurerm_resource_group.pg.name

  sku_name = "GP_Gen5_4"

  storage_mb                   = 51200
  backup_retention_days        = 7
  geo_redundant_backup_enabled = true
  auto_grow_enabled            = true

  administrator_login          = var.db_admin_username
  administrator_login_password = var.db_admin_password
  version                      = "11"

  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"
  public_network_access_enabled    = false
}

resource "azurerm_postgresql_server" "reader" {
  name                = "${azurerm_resource_group.pg.name}-reader"
  location            = azurerm_resource_group.pg.location
  resource_group_name = azurerm_resource_group.pg.name

  create_mode               = "Replica"
  creation_source_server_id = azurerm_postgresql_server.writer.id
  sku_name                  = "GP_Gen5_4"

  storage_mb                   = 51200
  backup_retention_days        = 7
  geo_redundant_backup_enabled = true
  auto_grow_enabled            = true

  administrator_login          = var.db_admin_username
  administrator_login_password = var.db_admin_password
  version                      = "11"

  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"
  public_network_access_enabled    = false
}
```

### Expected Behaviour

When reader is create the `Deny public network access` toggle should be set to `Yes`

### Actual Behaviour

Reader is created with public network access :frowning_face: 
![image](https://user-images.githubusercontent.com/5324639/105617774-a179cb00-5da6-11eb-84a3-c13c6ca766fb.png)

Note: Running the apply a second time shows that the reader has changes and properly sets the `public_network_access_enabled` to `false`

### Steps to Reproduce

1. `terraform apply`

**Comment by jgreat** [comment]
Might be an upstream bug?   Looks like TF is submitting the `"publicNetworkAccess": "Disabled"` option with the payload. 

```json
    {
        "location": "canadacentral",
        "properties": {
            "createMode": "Replica",
            "infrastructureEncryption": "Disabled",
            "minimalTlsVersion": "TLS1_2",
            "publicNetworkAccess": "Disabled",
            "sourceServerId": "/subscriptions/<uuid>/resourceGroups/my-pg-resources/providers/Microsoft.DBforPostgreSQL/servers/my-pg-resources-writer",
            "sslEnforcement": "Enabled",
            "version": "11"
        },
        "sku": {
            "name": "GP_Gen5_4",
            "tier": "GeneralPurpose",
            "capacity": 4,
            "family": "Gen5"
        },
        "tags": {}
    }
```

**Comment by dkuzmenok** [comment]
@katbyte I guess this one should be closed. There is a following Update action after creation to set this field:
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/postgres/postgresql_server_resource.go#L522

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
