### ISSUE TITLE
Key Vault restore does not detect sub-resources are also restored.

### ISSUE THREAD

**Issue by michaelelleby** [hashicorp/terraform-provider-azurerm#10302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
[test-keyvault.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5866545/test-keyvault.zip)

### Expected Behaviour

Terraform should have imported existing access policies and diagnostic settings into Terraform state.

### Actual Behaviour

```
Error: A resource with the ID "/subscriptions/<subscription id>/resourcegroups/<resource group>/providers/microsoft.keyvault/vaults/<vault name>/providers/microsoft.insights/diagnosticSettings/keyvault_logs" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.

  on main.tf line 37, in resource "azurerm_monitor_diagnostic_setting" "keyvault":
  37: resource "azurerm_monitor_diagnostic_setting" "keyvault" {

Error: A resource with the ID "/subscriptions/<subscription id>/resourceGroups/<resource group>/providers/Microsoft.KeyVault/vaults/<vault name>/objectId/<principal id>" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.

  on main.tf line 79, in resource "azurerm_key_vault_access_policy" "principal":
  79: resource "azurerm_key_vault_access_policy" "principal" {
```

### Steps to Reproduce

I have attached a zip file with a Terraform template and a shell script demonstrating the issue. Run `sh scripts/test.sh` to reproduce the issue. This script will create a resource group, key vault and storage account in your current Azure subscription.

**Comment by girishsuri15** [comment]
@katbyte can u give the reference file in go where this problem exist.

**Comment by tombuildsstuff** [comment]
hi @michaelelleby 

Taking a look through there's an existing resource in Azure which needs to be imported into the State here:

> A resource with the ID "/subscriptions/<subscription id>/resourceGroups/<resource group>/providers/Microsoft.KeyVault/vaults/<vault name>/objectId/<principal id>" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_access_policy" for more information.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
