### ISSUE TITLE
azurerm_resources doesn't work for SQL database resources

### ISSUE THREAD

**Issue by DannyArr** [hashicorp/terraform-provider-azurerm#10314]
When capturing from the azurerm_resources data source while targeting an Azure SQL Database, no resource IDs are returned. This works fine on CosmosDB, for example, but SQL Database doesn't return it.

Using the same resource group and resource name when getting the details via PowerShell returns the required information, but this doesn't work for the azurerm_resources data source in Terraform when targeting a SQL database.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0

### Affected Resource(s)

* `azurerm_resources`

### Terraform Configuration Files

```hcl
provider "azurerm" {
    features {}
}

data "azurerm_resources" "get_resource" {
    resource_group_name = "myresourcegroup"
    name = "sqldatabase"
}

output resource_details {
    value = data.azurerm_resources.get_resource
}
```

### Debug Output
https://gist.github.com/DannyArr/5dac03a870e29e24285dcae7cffdb267

### Expected Behaviour
The returned resource_details collection should have a populated resources list when retrieving resource details for a SQL database resource.

### Actual Behaviour
The resources list is empty.

```hcl
Outputs:

resource_details = {
  "id" = "resource-0d784769-dd21-45d2-b79b-5aa7019093a6"
  "name" = "sqldatabase"
  "required_tags" = tomap(null) /* of string */
  "resource_group_name" = "myresourcegroup"
  "resources" = tolist([])
  "timeouts" = null /* object */
  "type" = tostring(null)
}
```

### Steps to Reproduce

1. `terraform apply`

**Comment by DannyArr** [comment]
My first assumption is that maybe it#s something to do with the resource type. This is also showing as null for SQL server. Could it be related to parsing the resource type value? The SQL Database resource type is different to most in that is has an additional forward slash; "Microsoft.Sql**/**servers**/**databases" whereas most others have one, e.g. "Microsoft.Storage/storageAccounts"

**Comment by jbinko** [comment]
@DannyArr : Can you double check with latest version please?
For me it works.

Outputs:

resource_details = {
  "id" = "resource-b961140c-ffff-4e78-ffff-cb5b3cfaaefd"
  "name" = "mydb"
  "required_tags" = tomap(null) /* of string */
  "resource_group_name" = "mydb"
  "resources" = tolist([
    {
      "id" = "/subscriptions/00000.../resourceGroups/mydb/providers/Microsoft.Sql/servers/mydb"
      "location" = "westeurope"
      "name" = "mydb"
      "tags" = tomap({})
      "type" = "Microsoft.Sql/servers"
    },
  ])
  "timeouts" = null /* object */
  "type" = tostring(null)
}

**Comment by dzmitry-lahoda** [comment]
i have it not working on NSG. Not sure why yet https://github.com/googleforgames/agones/pull/2124#issuecomment-858627000. May be there some random bug?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
