### ISSUE TITLE
azurerm_mysql_server if autogrowth happened a redeploy triggers unsupported shrink

### ISSUE THREAD

**Issue by CDann3r** [hashicorp/terraform-provider-azurerm#10360]
Hi Community,

we are using azurerm_mysql_server to create MySQL managed instances in Azure.
We configured them with a starting size of 250GB and the nice feature "auto_grow_enabled = true".
When our PROD environment exceeded this size and Azure increased the max available storage, then every following plan will say that this property will be changed and the following applies fails.

While we could change our parameters for this database higher or equal to the current size, we would need to change settings we hoped to not care about. Also we don't want to increase the storage up-front because it is cheaper and also that's why auto_grow feature should be used for.

I propose the following:
If "auto_grow_enabled = true" and "storage_mb" set in code is smaller than existing instance, then ignore "storage_mb" or just set "storage_mb" to size of instance. Therefore no change will be applied when auto_grow happened on the instance.

`Error: waiting for MySQL Server "servername" (Resource Group "resourcegroupname") to finish updating: Code="UnsupportedUpdate" Message="Cannot update StorageMB Downscaling for server"`

**Comment by phatcher** [comment]
@CDann3r Can't you just do a lifecycle ignore on the relevant properties, to me some of these sorts of parameters are the split between IaC and DevOps.  

I know it's not perfect, but it would give you a workaround for now.

**Comment by CDann3r** [comment]
Thanks @phatcher, thanks for the advice. This is exactly what we ended up with.
Our workaround is to copy our previous module we had for mysql and defined both modules with fixed "auto growth" either enabled and set the lifecycle ignore or we disabled it.

Therefore we have the logic we need but also more code to maintain.
Still would be happy to see that terraform modules are not executing what is not supported on the cloud provider side anyway and have a good documentation of the expected behaviour.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
