### ISSUE TITLE
Unable to send Azure SQL server Vulnerability assessment logs to storage account which is behind firewa

### ISSUE THREAD

**Issue by jayanthrajanna** [hashicorp/terraform-provider-azurerm#10394]
I have enabled azure sql defender for azure sql server snd trying to configure to send VA logs to a storage account account which is behind firewall(allows access only from a specific view).

I have assigned managed identity of "storage blob data contributor" role for the sql server on the storage account. Even then i am getting insufficient access to perform read write operation on the storage account.

Can any one help on this.. Thanks in advance

**Comment by hazzik** [comment]
Leave `storage_account_access_key` empty.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
