### ISSUE TITLE
Support for adding object_id to azurerm_user_assigned_identity output

### ISSUE THREAD

**Issue by mark-russell-bossanova** [hashicorp/terraform-provider-azurerm#10391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add object_id to [azurerm_user_assigned_identity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/user_assigned_identity) output.
I am trying to add a user assigned identity to a active directory group. To do that you need to have access to the object_id of the user assigned identity and that is not available.

### New or Affected Resource(s)

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.45.1

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  version         = "~> 2"
  tenant_id       = "tenant ID"
  subscription_id = "Subscription ID"

  features {}
}
resource "azurerm_resource_group" "example" {
  name     = "acceptanceTestResourceGroup1"
  location = "eastus"
}
resource "azurerm_user_assigned_identity" "linux_virtual_machine_main_identity" {
  resource_group_name = azurerm_resource_group.example.name
  location            = "eastus"

  name = "linux_machine_identity"
}
resource "azuread_group" "managed_identity_bug_test_ops" {
  display_name = "bug_test_ops"
  description  = "CoCreate Operations team"
}
resource "azuread_group_member" "linux_virtual_machine_main_identity_add_group" {
  group_object_id  = azuread_group.managed_identity_bug_test_ops.object_id
  member_object_id = azurerm_user_assigned_identity.linux_virtual_machine_main_identity.object_id
}
```
However the object_id is missing from the output of [azurerm_user_assigned_identity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/user_assigned_identity)

**Comment by ceciliasharp** [comment]
also missing this option, but I'm using the data source of "azurerm_user_assigned_identity" to be able to add an "azurerm_key_vault_access_policy" for that.

**Comment by ceciliasharp** [comment]
have you tried to use principal_id instead of object_id? that seemed to be working for us in another case

**Comment by katbyte** [comment]
@mark-russell-bossanova - could you give @ceciliasharp's suggestion a try?

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
