### ISSUE TITLE
azurerm_shared_image_versions - examples please

### ISSUE THREAD

**Issue by eodonoghue** [hashicorp/terraform-provider-azurerm#10414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to use this resource azurerm_shared_image_version**s** to retrieve an image from a shared image gallery in azure with certain tags. There are no examples on using this data source anywhere from what I can see. I am having issues using this to create a linux virtual machine and I think examples of this on the https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/shared_image_versions page or on the github page that references it would be useful: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4369. 

Also, why is it either or with azurerm_shared_image_version and azurerm_shared_image_version**s**? Why can't there be one resource to import an image version with the options to use the name or a tag? I want to be able to use the same code base for dev and prod. Eg in dev we may always want to take the "latest" image so I would like to be able to set this as a configuration variable on the dev workspace. But in prod we may want a specific image based on tags and I would ideally like to set these as configuration variables on the prod workspace. The code should be able to read the vars on the workspace and deploy the appropriate image, whether by name or by tag.

### New or Affected Resource(s)

azurerm_shared_image_versions

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/shared_image_versions page 

https://github.com/terraform-providers/terraform-provider-azurerm/issues/4369. 

* #0000

**Comment by rcskosir** [comment]
Thank you for opening this issue. I am going to mark it resolved with the example given by @gek0.
In the future if you have questions, I suggest one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
