### ISSUE TITLE
azurerm_virtual_network_gateway ActiveActiveP2SGatewayMustHaveExactlyThreeIpConfigurations Error in A/A with P2S deployment

### ISSUE THREAD

**Issue by domel138** [hashicorp/terraform-provider-azurerm#10425]
### General Description
During creation/updating Virtual Network Gateway in Active/Active mode with P2S client vpn configuration azurerm_virtual_network_gateway provider cannot create/update resource succesfully - either it complaint that ip configuration block supports maximum of two statements or that Active/Active mode with P2S requires 3 ip configuration blocks. 

### Terraform (and AzureRM Provider) Version
Terraform CLI v. 0.13.3
Azure Provider v. 2.38.0

### Affected Resource(s)
azurerm_virtual_network_gateway

### Terraform Configuration Files

**With two ip configuration blocks provided:**
```
resource "azurerm_virtual_network_gateway" "azure_vgw" {
  name                = var.virtual_network_gateway_name
  location            = var.location
  resource_group_name = var.resource_group_name

  type     = var.type
  vpn_type = var.vpn_type

  sku        = var.sku
  generation = var.generation

  active_active = var.active_active
  enable_bgp    = var.enable_bgp

  ip_configuration {
    name                          = "vnetGatewayConfigPrimary"
    public_ip_address_id          = azurerm_public_ip.primary_public_ip.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.vng_subnet.id
  }

  dynamic "ip_configuration" {
    for_each = var.active_active ? [true] : []
    content {
      name                          = "vnetGatewayConfigSecondary"
      public_ip_address_id          = azurerm_public_ip.secondary_public_ip[0].id
      private_ip_address_allocation = "Dynamic"
      subnet_id                     = azurerm_subnet.vng_subnet.id
    }
  }

  /*dynamic "ip_configuration" {
    for_each = var.enable_client_vpn ? [true] : []
    content {
      name                          = "vnetGatewayConfigVpn"
      public_ip_address_id          = azurerm_public_ip.client_vpn_public_ip[0].id
      private_ip_address_allocation = "Dynamic"
      subnet_id                     = azurerm_subnet.vng_subnet.id
    }
  }*/

  dynamic "bgp_settings" {
    for_each = var.enable_bgp ? [true] : []
    content {
      asn = var.bgp_asn_number
    }
  }

  dynamic "vpn_client_configuration" {
    for_each = var.vpn_client_configuration != null ? [var.vpn_client_configuration] : []
    iterator = vpn
    content {
      address_space = vpn.value.address_space
      aad_tenant    = vpn.value.aad_tenant
      aad_audience  = vpn.value.aad_audience
      aad_issuer    = vpn.value.aad_issuer
      vpn_client_protocols = vpn.value.vpn_client_protocols
    }
  }
  
  tags = var.tags
}
```

**With three IP configuration blocks:**
```
resource "azurerm_virtual_network_gateway" "az_vng" {
  name                = var.virtual_network_gateway_name
  location            = var.location
  resource_group_name = var.resource_group_name

  type     = var.type
  vpn_type = var.vpn_type

  sku        = var.sku
  generation = var.generation

  active_active = var.active_active
  enable_bgp    = var.enable_bgp

  ip_configuration {
    name                          = "vnetGatewayConfigPrimary"
    public_ip_address_id          = azurerm_public_ip.primary_public_ip.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.vng_subnet.id
  }

  dynamic "ip_configuration" {
    for_each = var.active_active ? [true] : []
    content {
      name                          = "vnetGatewayConfigSecondary"
      public_ip_address_id          = azurerm_public_ip.secondary_public_ip[0].id
      private_ip_address_allocation = "Dynamic"
      subnet_id                     = azurerm_subnet.vng_subnet.id
    }
  }

  dynamic "ip_configuration" {
    for_each = var.enable_client_vpn ? [true] : []
    content {
      name                          = "vnetGatewayConfigVpn"
      public_ip_address_id          = azurerm_public_ip.client_vpn_public_ip[0].id
      private_ip_address_allocation = "Dynamic"
      subnet_id                     = azurerm_subnet.vng_subnet.id
    }
  }

  dynamic "bgp_settings" {
    for_each = var.enable_bgp ? [true] : []
    content {
      asn = var.bgp_asn_number
    }
  }

  dynamic "vpn_client_configuration" {
    for_each = var.vpn_client_configuration != null ? [var.vpn_client_configuration] : []
    iterator = vpn
    content {
      address_space = vpn.value.address_space
      aad_tenant    = vpn.value.aad_tenant
      aad_audience  = vpn.value.aad_audience
      aad_issuer    = vpn.value.aad_issuer
      vpn_client_protocols = vpn.value.vpn_client_protocols
    }
  }
  
  tags = var.tags
}
```

### Expected Behavior
Virtual Network Gateway should be created in Active/Active mode with P2S enabled with three public ip configurations:
   - one primary ip configuration
   - one secondary ip configuration
   - one client vpn config ip configuration 

### Actual Behavior
**In Active/Active with P2S enabled  with two ip configuration blocks the provider throws this error:**
Error Creating/Updating AzureRM Virtual Network Gateway "vng-central-hub-dev-001" (Resource Group "rg-central-hub-dev-001"): network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ActiveActiveP2SGatewayMustHaveExactlyThreeIpConfigurations" Message="Gateway 2 has /subscriptions/omitted/resourceGroups/rg-central-hub-dev-001/providers/Microsoft.Network/virtualNetworkGateways/vng-central-hub-dev-001 IP configurations specified for gateway. ActiveActive Gateway with Vpn client configuration must be created with three IP configurations."

**In Active/Active deployment with P2S enabled with three ip configuration blocks the provider throws this error:**
Error: ip_configuration: attribute supports 2 item maximum, config has 3 declared

**Steps to Reproduce**
```
terraform apply
```

**Comment by piotr-penar-dhsc** [comment]
HI @domel138, have you managed to find a way around it? We are facing the same problem.

**Comment by jckeme-rs** [comment]
bump.

**Comment by jckeme-rs** [comment]
Issue appears to either have been fixed or this could be a common confusion from the Azure FAQs. 

https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-vpn-faq#can-i-connect-to-a-vpn-gateway-via-point-to-site-when-located-at-a-site-that-has-an-active-site-to-site-connection

The confusion here is the assumption that if you need a P2S tunnel as well, you will need an additional public IP, however, this did not seem to apply to a S2S **active-passive** vnet gateway which has only 1 S2S endpoint. Errors were always encountered while attempting to create the resource with an additional public IP, however, the P2S configuration works with no additional public IP. 

Deployed the vnet gateway with options for either active-active, active-passive with only 1 active endpoint, or both with or without the P2S deployment. 

Terraform provider version = "2.96.0"

With conditionals as your switch/case, you can toggle your count of public IPs allocated to your vnet gateway

e.g. 

```
resource "azurerm_public_ip" "example" {

 count = var.s2s_tunnel_count == 1 && var.enable_p2s == true ? 1 : (var.s2s_tunnel_count == 1 && var.enable_p2s == false ? 1 : (var.s2s_tunnel_count == 2 && var.enable_p2s == false ? 2 : (var.s2s_tunnel_count == 2 && var.enable_p2s == true ? 3 : null)))

.
.
.
```
 

And in your gateway resource, 

```
resource "azurerm_virtual_network_gateway" "example" {
.
.
.

  active_active = var.s2s_tunnel_count == 1 && var.enable_p2s == true ? false : (var.s2s_tunnel_count == 1 && var.enable_p2s == false ? false : true)
 
public_ip_address_id          = azurerm_public_ip.example[*].id
```

The key here is to have only 1 public IP when using 1 endpoint and P2S enabled, 2 public IPs when using active-active S2S with P2S disabled and 3 public IPs when using 2 endpoints (active-active) and P2S enabled.

And on a side note, had to make the P2S configuration dynamic with **all p2s variables having null defaults** incase p2s was not desired

```
dynamic "vpn_client_configuration" {
    for_each = var.enable_p2s ? [{}] : []

    content {
      address_space = var.vpn_address_space

      root_certificate {
        name             = var.root_ca_name
        public_cert_data = var.ca_root_certificate
      }

      vpn_client_protocols = var.vpn_client_protocols
    }
  }
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!

**Comment by sjackson0109** [comment]
For future reference.

Having a single VNG appliance, with S2S VPNs, you need only 1x PIP.
Making that an Active/Passive appliance - you don't need any more PIPs.
Moving to an Active/Active appliance - you need 2x PIPs, one each
And finally if you use SSL VPN configuration, that requires a dedicated PIP.
