### ISSUE TITLE
azurerm_subnet should be recreated when modifying delegation

### ISSUE THREAD

**Issue by KuSh** [hashicorp/terraform-provider-azurerm#10477]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azurerm v2.44.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

I can't upgrade to azurerm 2.45.1 due to #10371

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "main" {
  name = var.resource_group_name
}

data "azurerm_virtual_network" "main" {
  name                = var.virtual_network_name
  resource_group_name = data.azurerm_resource_group.main.name
}

resource "azurerm_subnet" "main" {
  name                 = "subnet"
  resource_group_name  = data.azurerm_resource_group.main.name
  virtual_network_name = data.azurerm_virtual_network.main.name
  address_prefixes     = [var.address_prefix]

  enforce_private_link_endpoint_network_policies = true

  delegation {
    name = "delegation"

    service_delegation {
      name = "Microsoft.Web/serverFarms"
    }
  }  
}
```

### Expected Behaviour

Plan is applied correctly

### Actual Behaviour

Applying plan result in an error :

```
Error: Error updating Subnet "subnet" (Virtual Network " vnet" / Resource Group "resourcegroup"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SubnetDelegationsCannotChangeWhenSubnetUsedByResource" Message="Delegations of subnet /subscriptions/593cfa7e-d3b2-4aab-9653-b1ddd2f5a7db/resourceGroups/resourcegroup/providers/Microsoft.Network/virtualNetworks/vnet/subnets/subnet cannot be changed from [] to [Microsoft.Web/serverFarms] because it is being used by the resource /subscriptions/593cfa7e-d3b2-4aab-9653-b1ddd2f5a7db/resourceGroups/resourcegroup/providers/Microsoft.Network/networkInterfaces/privateendpoint.nic.aa70ab99-e8a7-4bc7-bd8a-29177edd608b/ipConfigurations/postgresqlServer-postgresqlServer.privateEndpoint." Details=[]
```

### Steps to Reproduce

1. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
