### ISSUE TITLE
Storage Account Network Rules Virtual Network Subnet Ids not detecting changes when using distinct() and compact()

### ISSUE THREAD

**Issue by mikebranstein** [hashicorp/terraform-provider-azurerm#10485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.45.1

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

Code example is large and complex, please download from link: https://www.dropbox.com/s/2yd3d8d642cotc0/example.zip?dl=0

### Debug Output

https://gist.github.com/mikebranstein/883200f810b38c5e287dc8e12ebb09a5

### Expected Behaviour

The expected behavior is for Terraform to recognize a change in the number of subnets, and update the `virtual_network_subnet_ids` for the Storage Account and Key Vault resources.

### Actual Behaviour

When adding a subnet, Terraform only recognizes a change in the number of subnets for the Key Vault `virtual_network_subnet_ids`. The Storage Account is not updated.

### Steps to Reproduce

See https://gist.github.com/mikebranstein/9f295c6d880291de56a4206699e143c4.

1. Unzip example.zip from https://www.dropbox.com/s/2yd3d8d642cotc0/example.zip?dl=0
2. Update main.tf file to include `tenant_id` and `subscription_id` values for an Azure subscription
3. `az login --tenant <tenant_id>`
4. `terraform init`
5. `terraform apply`, which creates the base of the example resources:
  - `example-rg` resource group
  - `example-vnet` virtual network
  - `subnet1` subnet (with Storage and Key Vault service endpoints)
  - `exampleXXXXXXXXX` storage account
  - `exampleXXXXXXXXX` key vault

#### Test 1: Adding a subnet, using concat()

The purpose of this test is to show that when adding a subnet and using `concat()`, both Storage Account and Key Vault virtual network subnet ids are updated with the new subnet.

Before beginning review the `main.tf` in the `region` module folder. Note the `virtual_network_subnet_ids` property of the storage account and key vault resources is using a `concat()` function to combine a `for value in` and `list(string)` object.

1. Uncomment `subnet2` definition in `config.auto.tfvars` file
2. `terraform plan`

##### Test 1 Result

Note 1 resource will be added (`subnet2`), and 2 resources will be updated (storage account and key vault virtual network subnet ids). This is expected behavior.

#### Test 2: Adding a subnet, using concat() and distinct()

The purpose of this test is to show that when adding a subnet and using `concat()` and `distinct()`, only the Key Vault virtual network subnet ids are updated with the new subnet. The Storage Account virtual network subnet ids do not detect a change.

1. Open the `main.tf` file in the `region` module folder. 
2. Uncomment the `Test 2` scenario `virtual_network_subnet_ids` property for the Storage Account and Key Vault
3. `terraform plan`

##### Test 2 Result

Note 1 resource will be added (`subnet2`), and only 1 resource will be updated (the key vault). This behavior is unexpected. The expected behavior it to see 2 resources updated (the storage account and the key vault).

#### Test 3, 4, & 5

The purpose of these tests is to show that when `distinct()` and `compact()` are used, only the Key Vault virtual network subnet ids are updated with the new subnet. The Storage Account virtual network subnet ids do not detect a change.

Follow the same process as test 2 to see the same results.

### Important Factoids

None.

### References

None.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
