### ISSUE TITLE
Support for azurerm_virtual_network.subnet service_endpoints

### ISSUE THREAD

**Issue by nspyke** [hashicorp/terraform-provider-azurerm#10508]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Due to NSG policy requirements, I'm creating subnets inline so that I can set the required NSG.
But the inline subnet definition does not allow me to define service endpoints, and I'm unable to use `azurerm_subnet` due to the removal of the NSG setting at creation.

### New or Affected Resource(s)

* `azurerm_virtual_network`

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network" "vnet" {
  ...

  subnet {
    address_prefix = "172.x.0.0/26"
    name           = "example"
    security_group = azurerm_network_security_group.example.id
    service_endpoints = ["Microsoft.Sql", "Microsoft.Web"]
  }
}
```

### References

* #8261
* #9022

**Comment by dylan-asos** [comment]
@nspyke interested if you have any workaround for this.

**Comment by nspyke** [comment]
In the end I had to add a NSG policy exception to the management groups, as it was more important for me to have the service endpoints in place than the policy

**Comment by KristapsT** [comment]
Encountered same exact issue.

We have several AKS clusters defined and deployed with Terraform that, there are multiple `azurerm_virtual_network` resources defined. It was originally created with `subnet` block in `azurerm_virtual_network` and now we can't define `service_endpoints` for those subnets.

There also doesn't appear to be a clear migration path how we can move to using `azurerm_subnet` resource instead without deleting and recreating the subnets. They could be imported to state file for `azurerm_subnet` resource, but that still leaves the `subnet` block defined in `azurerm_virtual_network` resource - afaik there is no way to remove that definition without Terraform then deleting my subnet on apply.

The only workaround I can think of is to add a `null_resource` with local provisioner that runs az cli command on each subnet to add service endpoints. Here is how that would look in an example:

```
resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.1.0/24"
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.2.0/24"
  }
}

resource "null_resource" "service_endpoints" {
  triggers = {
    subnet_count = length(azurerm_virtual_network.example.subnet)
  }

  provisioner "local-exec" {
    command = <<-EOT
      %{for subnet in azurerm_virtual_network.example.subnet}
      az network vnet subnet update \
        --resource-group ${azurerm_resource_group.example.name} \
        --vnet-name ${azurerm_virtual_network.example.name} \
        --name ${subnet.name} \
        --service-endpoints Microsoft.Storage
      %{endfor}
      EOT
  }

}
```

Hopefully we get either a way to non destructively migrate to using `azurerm_subnet` or better functionality in `azurerm_virtual_network` subnet block.

**Comment by tombuildsstuff** [comment]
Consolidating this into #3917, as other properties also need to be added at the same time.
