### ISSUE TITLE
Changing vm identity does not recreate azurerm_key_vault_access_policy using its principal_id

### ISSUE THREAD

**Issue by ilons** [hashicorp/terraform-provider-azurerm#10540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.21
azurerm v2.44.0

### Affected Resource(s)

* `azurerm_key_vault_access_policy`
* `azurerm_linux_virtual_machine`

### Terraform Configuration Files

```hcl
```

### Expected Behaviour
The `azurerm_key_vault_access_policy` are replaced

### Actual Behaviour
The `azurerm_key_vault_access_policy` was left unchanged

### Steps to Reproduce
1. Create a `azurerm_linux_virtual_machine` and set the `identity` attribute to `SystemAssigned`
2. Create a `azurerm_key_vault_access_policy` referencing the vm`.identity.0.principal_id` as `object_id`
3. Run terraform and apply changes
4. Change the `identity` on `azurerm_linux_virtual_machine` to `UserManaged`, supplying an identity using `identity_ids`
5. Run terraform and apply changes

**Comment by ausfestivus** [comment]
I had something similar tonight trying to add a Managed Identity to an existing VM and then use the `azurerm_role_assignment` resource to map the VM resource `identity[0].principal_id` to the principal_id in the `azurerm_role_assignment`.

**azurerm_linux_virtual_machine resource**
```hcl
resource "azurerm_linux_virtual_machine" "tfeAppVM" {
  count = var.vm_count

  admin_username                  = var.ssh_user
  computer_name                   = "${local.vm_conf_name}${count.index}"
  custom_data                     = element(module.configs.primary_cloud_init_list, count.index)
  location                        = var.LOCATION
  name                            = "${local.vm_conf_name}${count.index}"
  network_interface_ids           = [azurerm_network_interface.tfeAppVM[count.index].id]
  resource_group_name             = azurerm_resource_group.new.name
  size                            = var.vm_size
  disable_password_authentication = true

  identity {
    type = "SystemAssigned"
  }

  admin_ssh_key {
    public_key = file("./ssh/id_rsa_user1.pub")
    username   = var.ssh_user
  }

  admin_ssh_key {
    public_key = file("./ssh/id_rsa_user2.pub")
    username   = var.ssh_user
  }

  os_disk {
    caching              = "ReadWrite"
    disk_size_gb         = var.os_disk_size
    name                 = "${local.osdisk_conf_name}-vm${count.index}"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = var.storage_image["publisher"]
    offer     = var.storage_image["offer"]
    sku       = var.storage_image["sku"]
    version   = var.storage_image["version"]
  }

  tags = var.TAGS

  lifecycle {
    ignore_changes = [
      # ignore tag changes because we inherit some tags from the Subscription
      tags,
    ]
  }
}
```

**azurerm_role_assignment resource**
```
resource "azurerm_role_assignment" "tfeAppVM" {
  depends_on = [azurerm_linux_virtual_machine.tfeAppVM]

  count = var.vm_count

  scope              = data.azurerm_subscription.current.id
  role_definition_id = "${data.azurerm_subscription.current.id}${data.azurerm_role_definition.contributor.id}"
  principal_id       = azurerm_linux_virtual_machine.tfeAppVM[count.index].identity[0].principal_id
}
```

I added the `identity {}` block to the VM resource and added the whole `azurerm_role_assignment` resource per the above examples. I ran the plan. Plan errored with:

```
Error: Unsupported attribute

  on tfeAppVMs.tf line 126, in resource "azurerm_role_assignment" "tfeAppVM":
 126:   principal_id       = element(azurerm_linux_virtual_machine.tfeAppVM.*.identity[0].principal_id, count.index)
    |----------------
    | azurerm_linux_virtual_machine.tfeAppVM is tuple with 2 elements

This value does not have any attributes.


Error: Unsupported attribute

  on tfeAppVMs.tf line 126, in resource "azurerm_role_assignment" "tfeAppVM":
 126:   principal_id       = element(azurerm_linux_virtual_machine.tfeAppVM.*.identity[0].principal_id, count.index)
    |----------------
    | azurerm_linux_virtual_machine.tfeAppVM is tuple with 2 elements

This value does not have any attributes.
```

I commented out the `azure_role_assignment` resource, re-ran the plan and the plan worked and showed the `identity {}` block to be added to the VM resource.

I then uncommented the `azure_role_assignment` resource, re-ran the plan and it was able to plan successfully.

Even with the `depends_on` meta-attribute on the role assignment resource, I couldn't get terraform to understand that the `identity {}` block needed to be added.

Im sure i've seen similar behaviour in other resources elsewhere. Was a while ago though.
