### ISSUE TITLE
r/application_insights: Terraform should remove the automatically created nested items post-creation

### ISSUE THREAD

**Issue by jeromewaibel** [hashicorp/terraform-provider-azurerm#10563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This issue is a direct followup to https://github.com/terraform-providers/terraform-provider-azurerm/issues/8812 as I think you completly missed the point of that issue.

Whenever a new insights resource is created via `azurerm_application_insights` azure automatically creates an alert rule called "Failure Anomalies" with the condition "Whenever the Failure Anomalies criteria is met" and an action group "Application Insights Smart Detection" which is also automatically created. (NB: It takes several minutes for this rule to show up in the portal after insights is created)

As Roshan B pointed out this creates a high volume of undesired alert messages sent to the wrong people.

What Roshan B wanted in his issue was the ability to turn off the creation of that alert rule

> So it would be great if we could get a way to disable these alerts in azurerm_application_insights resource.

What you instead delivered in your fix was the option to create more of them. 😮 

To make things worse, that "Failure Anomalies" rule and "Application Insights Smart Detection" alert group are completly outside of terraforms control. They are not accessible as a resource and thus cannot easily be altered (like changing the action group). You have to fiddle with az CLI call and/or ARM templates to get a grip on that alert rule. This is far from the stable automation process I'd like to achieve with terraform.

### New or Affected Resource(s)

* azurerm_application_insights
* azurerm_application_insights_smart_detection_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_application_insights" "shared" {
  name                = "randd-fakeapp-ai"
  location            = var.location
  resource_group_name = var.resource_group_name
  application_type    = "other" # 'other' means that a general instance is to be created
  tags                = var.tags

  auto_create_failure_anomalies_rule = false   <<<< some option like this would be nice
}
```

### References

https://docs.microsoft.com/en-us/azure/azure-monitor/app/proactive-failure-diagnostics#how-it-works

**Comment by tombuildsstuff** [comment]
Rather than exposing a flag for this, Terraform should remove the ones being created by default here - since we've got a means of creating these via the new resource (this is an issue across other resources too, for example placeholder data which shouldn't be provisioned by default, but Azure tries to be helpful)

**Comment by Simonzhaohui** [comment]
Any workaround to remove the failure anomalies rule ?

**Comment by ppanyukov** [comment]
This has been bugging me for while. We have tons of these "Smart detection" things scattered around in our subscriptions and nobody knows what they are and what to do with them. 

One problem I see is that terraform provider is only a thin wrapper on top of Azure RM API, and the API for App Insights has no mention of anything "Smart detection". So I'm not sure if the provider team will be able to implement this feature. I'm sad. See here: https://docs.microsoft.com/en-us/rest/api/application-insights/components/create-or-update
