### ISSUE TITLE
Azure - azurerm_app_service - Changed health_check_path in site_config is not picked up

### ISSUE THREAD

**Issue by oottka** [hashicorp/terraform-provider-azurerm#10568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0
+ provider registry.terraform.io/hashicorp/random v3.0.1

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

1. Initial app service configuration
```hcl
resource "azurerm_app_service" "XXX" {
  name                = "name-here"
 ...

  site_config {
    linux_fx_version  = format("DOCKER|%s/image-name:latest", var.container_registry_login_server)
    health_check_path = format("/health?X-API-KEY=%s", var.api_key)
  }
```

2. App service configuration after health check change
```hcl
resource "azurerm_app_service" "XXX" {
  name                = "name-here"
 ...

  site_config {
    linux_fx_version  = format("DOCKER|%s/image-name:latest", var.container_registry_login_server)
    health_check_path = format("/new-path-here?X-API-KEY=%s", var.api_key)
  }
```

### Expected Behaviour

1. run `terraform apply` with the initial configuration (1)
2. run `terraform apply` with the configuration that has a new health_check_path (2)
3. The health check path of the app service application is updated

### Actual Behaviour

In step 3, the new health check path was not picked up. No change was detected, and the health check path was not updated.

### Steps to Reproduce

See above.

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/8522

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
