### ISSUE TITLE
Error during terraform apply on existing LA workspace in Free tier

### ISSUE THREAD

**Issue by kamil-makowski** [hashicorp/terraform-provider-azurerm#10573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

azurerm Provider 2.46.1
Terraform 0.14.6

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "shared_hub_loganalytics_we" {
  name                = "${var.prefix}-shr-${var.region_code[var.location_lookup]}-${local.environment}-la"
  location            = var.location[var.location_lookup]
  resource_group_name = data.azurerm_resource_group.internal_hub_rg_we.name
  sku                 = "Free"
  retention_in_days   = 7
  daily_quota_gb      = 0.5
  tags                = var.old_tags
}
```

### Debug Output

```hcl
Error: `Free` tier SKU quota is not configurable and is hard set to 0.5GB
on main.tf line 41, in resource "azurerm_log_analytics_workspace" "shared_hub_loganalytics_we"
```

### Expected Behaviour

Terraform apply step shouldn't try to change anything on this resource. It already exist in Azure in this configuration but it has been created on older provider version.

### Actual Behaviour

During terraform apply step, above error is showing. I have tried to remove **daily_quota_gb** to stay with default value but behaviour is the same.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by masbrey-wellcome** [comment]
any luck with this? having the same issue

**Comment by chrsundermann** [comment]
Any update on this? Error hasn't fixed yet and no workaround seems to exist.

**Comment by soccerjoshj07** [comment]
I had this issue occur too after I merely went to go and update the tags on this resource.

Since it didn't house anything yet I just tainted and re-applied, but less than ideal to have to do that for just a tag update.

**Comment by katbyte** [comment]
@kamil-makowski @chrsundermann @joshjohanning - in that last release we included a change that _might_ fix this, we sadly can't test as we don't have any historical workspaces to test on. Let us know if this fixes it!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
