### ISSUE TITLE
Set access control lists (ACLs) recursively for Azure Data Lake Storage Gen2

### ISSUE THREAD

**Issue by lshade** [hashicorp/terraform-provider-azurerm#10576]
This is an enhancement/feature request to update the `azurerm_storage_data_lake_gen2_path` resource to "add, update, and remove ACLs recursively for existing child items of a parent directory without having to make these changes individually" now that the feature is available in PowerShell (https://docs.microsoft.com/en-us/azure/storage/blobs/recursive-access-control-lists?tabs=azure-powershell).

**Comment by kharkevich** [comment]
Will be great to add some parameter like a **propogate_ace** to _data_lake_gen2_filesystem_ and _data_lake_gen2_path_ resources
It can be looks like:
```
resource "azurerm_storage_data_lake_gen2_path" "example" {

  path                           = "some/directory"
  filesystem_name      = "storage"
  storage_account_id = var.storage_id
  resource                    = "directory"
  propogate_ace        = true
  ace {
    id          = var.some_object_id[var.env]
    permissions = "r-x"
    scope       = "access"
    type        = "user"
  }
```

Also, az cli and Azure Storage Explore already have similar functionality:
https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-acl-cli#set-acls-recursively
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/storage/blobs/data-lake-storage-explorer-acl.md#apply-acls-recursively

**Comment by m4r74** [comment]
Is there a chance to have this reviewed please? 
It would help us greatly in managing ACLs

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems the feature request has been supported by TF. The TF property name is [`ace`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem#ace).

**Comment by mkprizzle** [comment]
I believe what the request here is looking for a way to flag recursive - equivalent functionality to [az storage fs access set-recursive](https://learn.microsoft.com/en-us/cli/azure/storage/fs/access?view=azure-cli-latest#az-storage-fs-access-set-recursive) and [az storage fs access update-recursive](https://learn.microsoft.com/en-us/cli/azure/storage/fs/access?view=azure-cli-latest#az-storage-fs-access-update-recursive)
An argument enabling this could be as @kharkevich described

**Comment by neil-yechenwei** [comment]
@lshade, if above suggestion could resolve your question, does it make sense to close this issue? Thanks.
