### ISSUE TITLE
Shared_image_version datasource cannot find latest

### ISSUE THREAD

**Issue by claque2000** [hashicorp/terraform-provider-azurerm#10581]
As issue #10374 has been closed following PR merge #10519, when looking PR code, only shared_image_versions datasource has been fixed to return all images versions following pagination. And when looking at shared_image_version datasource code, the call done in obtainImage function is still the same that was raising error when searching for "latest" or "recent" image when there is more than 50 versions of an image, so not following pagination. 
Can a fix similar to what has been done for shared_image_versions datasource be applied to shared_image_version datasource in order to correct the bug indicated in #10374 ?

**Comment by claque2000** [comment]
I confirm that using 2.48.0, the issue is still valid. The image id returned by the datasource is not correct.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
