### ISSUE TITLE
Unable to create azurerm_role_assignment for global scope

### ISSUE THREAD

**Issue by sdebruyn** [hashicorp/terraform-provider-azurerm#10587]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.14.6

```
- Installing hashicorp/azuread v1.3.0...
- Installed hashicorp/azuread v1.3.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v2.47.0...
- Installed hashicorp/azurerm v2.47.0 (signed by HashiCorp)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/time v0.6.0...
- Installed hashicorp/time v0.6.0 (signed by HashiCorp)
- Installing hashicorp/random v3.0.1...
- Installed hashicorp/random v3.0.1 (signed by HashiCorp)
- Installing databrickslabs/databricks v0.3.0...
- Installed databrickslabs/databricks v0.3.0 (signed by a HashiCorp partner, key ID 905AA25F2E92C2D5)
```

### Affected Resource(s)
* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "redacted" {
  principal_id         = some.principal_id
  role_definition_name = "Directory Readers"
  scope                = "/"
}
```

### Output
```
Error: Can not parse "scope" as a management group id: Unable to parse Management Group ID "/"

  on redacted.tf line 61, in resource "azurerm_role_assignment" "redacted":
  61: resource "azurerm_role_assignment" "redacted" {



Error: "scope" expected to be valid subscription ID, got "/"

  on redacted.tf line 61, in resource "azurerm_role_assignment" "redacted":
  61: resource "azurerm_role_assignment" "redacted" {



Error: The number of path segments is not divisible by 2 in ""

  on redacted.tf line 61, in resource "azurerm_role_assignment" "redacted":
  61: resource "azurerm_role_assignment" "redacted" {



Error: Can not parse "scope" as a resource id: The number of path segments is not divisible by 2 in ""

  on redacted.tf line 61, in resource "azurerm_role_assignment" "redacted":
  61: resource "azurerm_role_assignment" "redacted" {

```

### Expected Behaviour
Scopes for the global scope should be allowed and created.

### Actual Behaviour
Errors I got above.

### Steps to Reproduce
1. `terraform validate`

### References

I think this error was introduced in https://github.com/terraform-providers/terraform-provider-azurerm/pull/10438/files ( cc @tombuildsstuff  )

**Comment by sdebruyn** [comment]
When I try to apply this using an older version, I get Error: Error loading Role Definition List: could not find role 'Directory Readers'

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
