### ISSUE TITLE
unable to create multiple azurerm_virtual_network_gateway_connection resources

### ISSUE THREAD

**Issue by tradosh** [hashicorp/terraform-provider-azurerm#10582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version - 

Terraform 0,14.5
AzureRM - v2.46.1

### Affected Resource(s)

* 'azurerm_virtual_network_gateway_connection'

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
```hcl
resource "azurerm_virtual_network_gateway_connection" "expressroute_to_core" {
  count                      = length(var.gateway_core_snet)
  name                       = "${var.name}-${format(1 + count.index)}"
  resource_group_name        = var.resource_group_name
  location                   = var.az_region
  type                       = "ExpressRoute"
  express_route_circuit_id   = var.ecr_circuit
  virtual_network_gateway_id = var.gateway_core_snet[count.index]
}
```

### Debug Output

the first connection created fine, however, the next connections get the bellow error

```
Error: Error waiting for completion of Virtual Network Gateway Connection "conenction-2" (Resource Group "rg"): Code="ConflictError" Message="The current operation could not be executed because it is already in progress." Details=[]
```

### Expected Behaviour

The connection should be created one after another, without error

### Actual Behaviour

first connection in the count gets created fine, the next ones get above error and show as failed in the Azure portal. They are not imported in the state either. the only way to fix it is to manually remove the network connection from the Azure Portal and re-run the terraform again

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

this is running multiple connections one after another to the same ECR 

### References

* #0000

**Comment by hougaardj** [comment]
Any updates this? It is quite painful to discover, manage and cleanup.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
