### ISSUE TITLE
removing policy_definition_reference instance from azurerm_policy_set_definition not working.  

### ISSUE THREAD

**Issue by russelljftw** [hashicorp/terraform-provider-azurerm#10621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version 0.14.4
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.46.1"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=1.3.0"
    }
  }
}
```

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
resource "azurerm_policy_set_definition" "policy_initiative_1" {
  name                   = "Initiative - Apply set of tag policies"
  policy_type            = "Custom"
  display_name           = "Initiative - Apply set of tag policies"

  management_group_name  = "MGMT-GRP1"

  policy_definition_reference {
    policy_definition_id = azurerm_policy_definition.custompolicydef.id
    reference_id         = "policyinstance1"
    parameter_values     = <<VALUE
    {
      "policyparam": {"value": "Value1"}
    }
    VALUE
  }

  policy_definition_reference {
    policy_definition_id = azurerm_policy_definition.custompolicydef.id
    reference_id         = "policyinstance2"
    parameter_values     = <<VALUE
    {
      "policyparam": {"value": "Value2"}
    }
    VALUE
  }

  policy_definition_reference {
    policy_definition_id = azurerm_policy_definition.noparampolicy.id
    reference_id         = "noparampolicy1"
  }
}
```

### Expected Behaviour

when removing policy_definition_reference block that contains policyinstance2, that policy definition in the policy set is removed from the initiative. 

### Actual Behaviour

Terraform apply fails. 

### Steps to Reproduce

1. `terraform apply` to create the policy set with 3 policy_definition_reference
2. remove the second policy_definition_reference
3. `terraform plan` shows the policy_definition_reference changes
4. run `terraform apply` to see failure:

```hcl
~ policy_definition_reference {
    ~ policy_definition_id = "/providers/Microsoft.Management/managementgroups/MGMT-GRP1/providers/Microsoft.Authorization/policyDefinitions/custompolicydef" -> "/providers/Microsoft.Management/managementgroups/MGMT-GRP1/providers/Microsoft.Authorization/policyDefinitions/noparampolicy"
    ~ reference_id         = "policyinstance2" -> "noparampolicy1"
      # (3 unchanged attributes hidden)
   }
- policy_definition_reference {
  - parameters           = {} -> null
  - policy_definition_id = "/providers/Microsoft.Management/managementgroups/MGMT-GRP1/providers/Microsoft.Authorization/policyDefinitions/noparampolicy" -> null
  - policy_group_names   = [] -> null
    - reference_id         = "noparampolicy1" -> null
  }
```

### Important Factoids

To reproduce, it's important that the final policy_definition_reference has no parameters and the other two policy_definition_reference has at least 1 parameter.  

It appears in the plan output, that the policy_definition_references are being remapped, but the parameter value from the 2 definition reference is not being updated.  

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
