### ISSUE TITLE
Azure no longer allows taints on default nodepool of AKS?

### ISSUE THREAD

**Issue by douernesto** [hashicorp/terraform-provider-azurerm#10639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: v0.13.6
hashicorp/azurerm: v2.47.0

### Affected Resource(s)

* `hashicorp/azurerm`
*  `azurerm_kubernetes_cluster`

### Terraform Configuration Files

For reference the value of local.default_np_taints is: ["CriticalAddonsOnly=true:NoSchedule"]

```hcl
resource "azurerm_kubernetes_cluster" "cluster" {
  name                = "${var.standard_tags["application-name"]}-${var.standard_tags["environment"]}-aks"
  location            = var.location
  resource_group_name = var.resource_group_name
  kubernetes_version  = local.kubernetes_version
  dns_prefix          = "${var.standard_tags["application-name"]}-${var.standard_tags["environment"]}"

  default_node_pool {
    name                 = local.default_np_name
    type                 = "VirtualMachineScaleSets"
    min_count            = local.default_np_min_count
    max_count            = local.default_np_max_count
    vm_size              = local.default_np_vm_size
    vnet_subnet_id       = local.subnet_id
    enable_auto_scaling  = local.default_np_enable_auto_scaling
    availability_zones   = local.default_np_availability_zones
    orchestrator_version = local.kubernetes_version
    tags                 = var.standard_tags
    node_labels          = local.default_np_node_labels
    node_taints          = local.default_np_taints
  }

... yada yada yada ..
```

### Debug Output

```
module.aks_creation.azurerm_kubernetes_cluster.cluster: Creating...

Error: expanding `default_node_pool`: The AKS API has removed support for tainting all nodes in the default node pool and it is no longer possible to configure this. To taint a node pool, create a separate one.

  on .terraform/modules/aks_creation/main.tf line 24, in resource "azurerm_kubernetes_cluster" "cluster":
  24: resource "azurerm_kubernetes_cluster" "cluster" {
```

### Expected Behaviour

Running terraform code I am creating a new cluster with a default nodepool, until yesterday Feb/17 I was able to taint the default nodepool with: ["CriticalAddonsOnly=true:NoSchedule"], however since yesterday I am getting the error I posted above.
I have a separate non-system nodepool with no taints, that I create with a separate resource.

1. Create AKS Cluster
2. Create a default nodepool with taints

### Actual Behaviour

No cluster created.

### Steps to Reproduce

1. `terraform apply`
 
Terraform plan doesn't detect any errors.

**Comment by douernesto** [comment]
I was able to resolve my specific case of this taints as they are "system taints" by replacing 

``hcl
node_taints          = ["CriticalAddonsOnly=true:NoSchedule"]
``

to

``hcl
only_critical_addons_enabled = true
``

You require azurerm 2.47.0 at least to do this. 

Altought this doesnt solve the issue that you cant add any other taints.

**Comment by stephybun** [comment]
Hi @douernesto

Thanks for opening this issue.

As you correctly pointed out the `["CriticalAddonsOnly=true:NoSchedule"]` taint can be applied by setting `only_critical_addons_enabled` to true. Unfortunately the fact that other taints cannot be applied to the system node pool is a limitation from [AKS](https://docs.microsoft.com/en-us/azure/aks/use-system-pools#system-and-user-node-pools). Since there is little we can do at the moment from a provider perspective I am going to close this issue for the moment.

Thanks!
