### ISSUE TITLE
azurerm_policy_definition throws error policy.DefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed"

### ISSUE THREAD

**Issue by jagadt80** [hashicorp/terraform-provider-azurerm#10645]
### Issue Description:

Failing to create a new custom Azure Policy definition despite my Azure AD Service principle account has "resource policy contributor" rights at the Tenant Root group level and it is inherited while using module named "azurerm_policy_definition"

### Terraform (and AzureRM Provider) Version

C:\Users\>terraform -v
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0

### Affected Resource(s)

azurerm_policy_definition

* `azurerm v2.48.0

### Terraform Configuration Files

```hcl
resource "azurerm_policy_definition" "addTagToRG" {
  count = length(var.mandatory_tag_keys)

  name                  = "addTagToRG_${var.mandatory_tag_keys[count.index]}"
  policy_type           = "Custom"
  mode                  = "All"
  management_group_name = var.childmg_id
  display_name          = "Add tag ${var.mandatory_tag_keys[count.index]} to resource group"
  description           = "Adds the mandatory tag key ${var.mandatory_tag_keys[count.index]} when any resource group missing this tag is created or updated. \nExisting resource groups can be remediated by triggering a remediation task.\nIf the tag exists with a different value it will not be changed."

  metadata = <<METADATA
    {
    "category": "${var.policy_definition_category}",
    "version" : "1.0.0"
    }

METADATA

  policy_rule = <<POLICY_RULE
    {
        "if": {
          "allOf": [
            {
              "field": "type",
              "equals": "Microsoft.Resources/subscriptions/resourceGroups"
            },
            {
              "field": "[concat('tags[', parameters('tagName'), ']')]",
              "exists": "false"
            }
          ]
        },
        "then": {
          "effect": "modify",
          "details": {
            "roleDefinitionIds": [
              "/providers/microsoft.authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
            ],
            "operations": [
              {
                "operation": "add",
                "field": "[concat('tags[', parameters('tagName'), ']')]",
                "value": "[parameters('tagValue')]"
              }
            ]
          }
        }
  }
POLICY_RULE


  parameters = <<PARAMETERS
    {
        "tagName": {
          "type": "String",
          "metadata": {
            "displayName": "Mandatory Tag ${var.mandatory_tag_keys[count.index]}",
            "description": "Name of the tag, such as ${var.mandatory_tag_keys[count.index]}"
          },
         "defaultValue": "${var.mandatory_tag_keys[count.index]}"
        },
        "tagValue": {
          "type": "String",
          "metadata": {
            "displayName": "Tag Value '${var.mandatory_tag_value[count.index]}'",
            "description": "Value of the tag, such as '${var.mandatory_tag_value[count.index]}'"
          },
          "defaultValue": "'${var.mandatory_tag_value[count.index]}'"
        }
  }
PARAMETERS

}
```

### Expected Behaviour

While using azurerm_policy_definition module based on using source "hashicorp/azurerm" and version "2.48.0", a new custom Azure policy definition should get created in Azure management group.

### Actual Behaviour

Failing to create a new custom Azure Policy definition despite my Azure AD Service principle account has "resource policy contributor" rights at the Tenant Root group level. 

**Note: I verified that by using the above service principle account that I can create a new custom Azure policy definition through Azure PowerShell, so permission is not an issue**

The below is the error message from Terraform run 
---------------------------------------------------------------------------------------
checking for presence of existing Policy Definition "addTagToRG_environment": policy.DefinitionsClient#GetAtManagementGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'XXX-XX-XX-XX' with object id 'XX-XX-XX-XX' does not have authorization to perform action 'Microsoft.Management/managementgroups/Microsoft.Management/MyManagement/Microsoft.Authorization/addTagToRG_environment/read' over scope '/providers/Microsoft.Management/managementgroups/providers/Microsoft.Management/managementGroups/MyManagement/providers/Microsoft.Authorization/policyDefinitions' or the scope is invalid. If access was recently granted, please refresh your credentials."
------------------------------------------------------------------------------------------
### Steps to Reproduce

Use azurerm_policy_definition module (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_definition) to create a new custom Azure policy definition in a new/existing management group and you will get the error message as mentioned above.

**Comment by milesjh** [comment]
I am running into the same issue with Owner permissions on the service principal at the Tenant Root Group level. I was also able to create said policy definition manually via the Portal and via PowerShell.

**Comment by milesjh** [comment]
>Microsoft.Management/managementgroups/Microsoft.Management/MyManagement/Microsoft.Authorization/addTagToRG_environment/read
>/providers/Microsoft.Management/managementgroups/providers/Microsoft.Management/managementGroups/MyManagement/providers/Microsoft.Authorization/policyDefinitions

It looks like the resource IDs are not assembled correctly. Shouldn't the second one be /providers/Microsoft.Management/managementgroups/MyManagement/providers/Microsoft.Authorization/policyDefinitions?

**Comment by KennethMLdk** [comment]
I had this issue for a couple of weeks after updating AzureRM provider. Management_group_name argument was deprecated in favor of management_group_id. My problem was the management_group_id argument value should be data.azurerm_management_group.policy_scope.group_id (mg-guid) and not .id (Microsoft.Management/managementGroups/Microsoft.Management/mg-guid) as it used to be. That fixed my issue. Hopefully it will help you or someone else coming across this thread in the future.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
