### ISSUE TITLE
azurerm_monitor_metric_alert: multiple issues

### ISSUE THREAD

**Issue by ppanyukov** [hashicorp/terraform-provider-azurerm#10657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.4
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0
```

### Affected Resource(s)

* `azurerm_monitor_metric_alert / application_insights_web_test_location_availability_criteria`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "example" {
  name                = local.alert_name

  # We *MUST* create this in the same resource group as the AI
  # and the webtest. Failing to do so leads to all sorts of weird
  # thigs, like the webtest in Portal thigns there are no alerts etc.
  resource_group_name = local.ai_rg_name

  # This *MUST* be in this order, however the provider reorders items
  # alphabetically which leads to incorrect results.
  # Also, why do we need to repleat these here? We already
  # specify these in application_insights_web_test_location_availability_criteria
  # block, the prider should populate these in correct order.
  scopes = [
    local.ai_webtest_id,
    local.ai_id,
  ]

  ## What goes here? These are not actually required, the docs are lying.
  ## Availability alerts work just fine without these.
  # target_resource_type = "microsoft.insights/webtests"
  # target_resource_location = local.ai_webtest_location

  description = "Test terraformed Availability alert."

  application_insights_web_test_location_availability_criteria {
    web_test_id           = local.ai_webtest_id
    component_id          = local.ai_id
    failed_location_count = 3
  }

  enabled       = true
  auto_mitigate = null
  severity      = 3
  frequency     = "PT1M"
  window_size   = "PT5M"

  # Are these required? When we create thing manually in Portal,
  # this get added. But there is no clarity on this.
  tags = {
    "hidden-link:${local.ai_id}"         = "Resource"
    "hidden-link:${local.ai_webtest_id}" = "Resource"
  }
}
```

### Expected Behaviour

There are multiple issue here, all to do with `application_insights_web_test_location_availability_criteria`.

* **Alert incorrectly created**. The provider reorders the values in `scopes` to be in alphabetical order. In my case this make AI to be first, and Web Test to be second. But for availability alert Web Test ID **must** be first (it took me several days to figure this out several months ago). With AI being first when going into Portal it shows App Insights as the target of the alert, and clicking on "Manage web test" takes us to AI, not Web Test. This is incorrect. The target should be Web Test.

  Expected behaviour:
  * Provider does not reorder the scopes.
  * Docs are clear what needs to go here for availability alerts (see further).
  * Availability alert is correctly created and operational in Portal as if created manually.

* **Documentation.** The documentation is extremely unhelpful. See comments in HCL example. 

    Expected behaviour:

   * Requirement of the availability alert being in the same RG as App Insights and Web Test. I wasted 4 hours trying to figure this out.
   * Requirement that scopes must have: Web Test ID, then App Insights ID. And **exactly** in this order. Failing to do so will lead to incorrect behaviour.
   * The `target_resource_type` and `target_resource_location` properties. The docs are incorrect saying that these are required when `scopes` has more than one resource like in this case. The docs for `target_resource_location` doesn't say what location is expected here: resource group name? actual location like `westeurope`. Neither the docs say why these are required. I personally am puzzled why these are needed.

* **Redundant `scopes` attribute**.  We already specify AI ID and Web Test ID in `application_insights_web_test_location_availability_criteria`. 

    Expected behaviour:

   * Scopes should not be required when `application_insights_web_test_location_availability_criteria` is used.
   * Provider should populate them from values supplied in `application_insights_web_test_location_availability_criteria` block.
   * The `scopes` populated by the provider should be in correct order (see above).

* **Slow**. This takes about 2 minutes to create the availability alert. My equivalent program written in Go to do the same (which I did a while back) runs in less than 10 seconds to create both Web Test and Availability Alert by using Azure RM SDK for Go. This provider uses the same SDK so I am puzzled why it's so much slower. This resource seems to be even slower than running ARM template. 

    Expected behaviour:

   * It should take only few seconds to run to create / update the resource. On par with my Go program.
   * It should be faster than ARM template. It isn't right now.

* **Low value**.   The value of this resource is rather low with availability alerts. This is all due to above issues: incorrect behaviour, users having to figure out all the values by themselves which takes quite a while. 

    Expected behaviour:

    * Using this resource makes our lives easier, not harder like in this case.
    * Using this resource should be easier than using raw ARM templates, which isn't in this case.

### Actual Behaviour

Not as expected.

### Workaround

It is easier and simpler to just use ARM template resource. This produces correct result and doesn't even look much different from terraform using this resource.

Of course the downside here is the ARM template does not detect the drift in the actual configuration. But here we are as a temporary measure until the real resource gets bushed up (hopefully).

```hcl
resource "azurerm_resource_group_template_deployment" "availability_alert" {
  name                = "availability-alert-${local.alert_name}"
  resource_group_name = local.ai_rg_name
  # TODO: This must NEVER EVER be set to Complete as it will zap everything in the resource group!
  deployment_mode  = "Incremental"
  template_content = <<EOT
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": { },
    "variables": {  },
    "resources": [
        {
            "name": "${local.alert_name}",
            "type": "Microsoft.Insights/metricAlerts",
            "location": "global",
            "apiVersion": "2018-03-01",
            "tags": {},
            "properties": {
                "description": "Test terraformed Availability alert.",
                "severity": "3",
                "enabled": "true",
                "scopes": [
                  "${local.ai_webtest_id}",
                  "${local.ai_id}"
                ],
                "evaluationFrequency": "PT1M",
                "windowSize": "PT5M",
                "criteria": {
                    "odata.type": "Microsoft.Azure.Monitor.WebtestLocationAvailabilityCriteria",
                    "componentId": "${local.ai_id}",
                    "webTestId": "${local.ai_webtest_id}",
                    "failedLocationCount": 3
                },
                "actions": [
                ]
            }
        }
    ]
}
EOT
}
```

----

### EDIT 1

Actually using ARM template is also problematic as it fails to destroy the deployment with this message:

```
Error: removing items provisioned by this Template Deployment: determining API Versions for Resource Providers: unable to determine API version for Resource Type "metricAlerts" (Resource Provider "Microsoft.Insights")
```

It is somehow related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/9003.

The error happens with `v2.47.0` version of the porvider, upgrading to `v2.48.0` resolves the ARM template destruction.

All other issues are still present in `v2.48.0`.

----
### EDIT 2

_(this oine is a generic Azure problem, not exactly a terraform provider issue but posting here for full details)_

Well, turns out this "reordering of scopes" is a deep-rooted issue indeed. Turns out, if you create an availability test (i.e. Web Test), lots of things in Monitor show App Insights as the target failed resource. This includes SMS alerts, emails alerts using unified schema, and the alert itself in portal.

The problem is, the "availability alertt" targets two resources, and these get sorted in alphabetical order somwhere deep in the guts in Azure. This means App Insights will **always** be first, and web test last. This is because resource IDs are like so:

```
resourceGroups/philip-test-appi-rg/providers/Microsoft.Insights/components/philip-test-appi/overview
resourceGroups/philip-test-appi-rg/providers/Microsoft.Insights/webtests/philip-test-webtest/availability
```

Since `components` are always before `webtests`, the order is always going to be like this.

Examples:

**SMS Alert:**

```
P1Alert:Fired:Sev3 Azure Monitor Alert philip-test-alert on philip-test-appi
```

Here `philip-test-appi` is App Insights, it should have been `philip-test-webtest`.

**Email alert**

<img width="630" alt="image" src="https://user-images.githubusercontent.com/300031/108760613-cac47d00-7545-11eb-9810-d4965d78a1d1.png">

**Alert in portal:**

Here it shows affected resource App Insights, not Web Test like it should.

<img width="910" alt="image" src="https://user-images.githubusercontent.com/300031/108760714-e596f180-7545-11eb-9ab8-4a5973e4ddbc.png">

**Alert list in portal:**

Here again it shows App Insights.

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/300031/108760936-33135e80-7546-11eb-975b-e5c9cd7fa779.png">

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
