### ISSUE TITLE
Creation of azurerm_backup_protected_vm times out every time

### ISSUE THREAD

**Issue by BenWyattMilliman** [hashicorp/terraform-provider-azurerm#10675]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azuread v1.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/random v2.2.1
```

### Affected Resource(s)

* `azurerm_backup_protected_vm`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

Big file, so here's a gist instead: https://gist.github.com/BenWyattMilliman/0daf93eb5fd0387cd6b57b6d3b79e2f6 

Redacted internal information to the best of my ability, but the state should still validate.

### Expected Behaviour

Backups should be enabled for the three VMs.

### Actual Behaviour

The `apply` operation times out (2 hours) every time we run it. After several attempts, it has never enabled backups for even one of the VMs.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by AndreasFrangopoulos** [comment]
I think I had a similar problem. I was told to increase the custom timeout value sufficiently to allow the inital backup to be created. Miine needed 3 hours

**Comment by mleziva** [comment]
I had the same problem and our issue was due to installing extensions on the VM while the backup was taking place. 

We were using _azurerm_virtual_machine_extension_ to install extensions and _azurerm_backup_protected_vm_ did not have a dependency on the extensions. Adding a dependency fixed the issue. 

Generally, it seems like if there are certain configurations being performed on the VM, the backup operation will not return successful and just time out. So you may need to investigate if there are any cloud init or configurations happening on the VM while the backup is taking place and maybe add a sleep between VM creation and backup.

**Comment by mpjtaylor** [comment]
Trying to backup VMs in Azure with 2 TB drives this takes for ever but In Azure it just configured, seems that azurerm_backup_protected_vm  is waiting for the backup to complete not configure it.

**Comment by ravensorb** [comment]
I am curious as to why terraform is waiting for a backup -- i would think that should be an additional step or at the very least a flag to indicate if an initial backup should be created or not?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
