### ISSUE TITLE
azurerm_linux_virtual_machine_set - Instances not updated when upgrade_mode = "Rolling"

### ISSUE THREAD

**Issue by jgreat** [hashicorp/terraform-provider-azurerm#10673]
If I understand correctly, when provider `feature.virtual_machine_scale_set.roll_instances_when_required=true` (Default) changes to things like instance `custom_data` should trigger instance updates/refreshes.  If `upgrade_mode` is `Manual` or `Automatic` this does seem to be the case. When `upgrade_mode` is `Rolling` looks like instance updates are ignored.

I think updates are being ignored because this block is missing a case for `Rolling`

https://github.com/terraform-providers/terraform-provider-azurerm/blob/56aee54ace989dd2a4ab6dbc5d4eaff90c044fc6/azurerm/internal/services/compute/virtual_machine_scale_set_update.go#L45

I know Azure has some wacky opinions on how things should work, but it seems to me that Provider logic for this is backwards.  

Currently

* `upgrade_mode = "Manual"` Updates 
* `upgrade_mode = "Automatic"` Updates
* `upgrade_mode = "Rolling"` Ignores

I would propose this logic for when to push an instance updates.

* `upgrade_mode = "Manual"` No, should never trigger an update (Manual means you go push the buttons/cli to "roll" your changes)
* `upgrade_mode = "Rolling"`  Yes, we have the rolling_update_policy and a health check. 
* `upgrade_mode = "Automatic"` Maybe? - follow provider feature flag

I could be missing something from the Azure side of things, but If this logic seems appropriate, I'd be happy to submit a PR.  At very least I'd be happy to submit a PR to allow updates to "Rolling".

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
➜ terraform version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
```

### Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set`
* (And probably) `azurerm_windows_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "this" {
  name                = "k3s-control"
  resource_group_name = data.azurerm_resource_group.this.name
  location            = data.azurerm_resource_group.this.location

  sku            = var.instance_sku
  instances      = var.instance_count
  admin_username = var.admin_username
  custom_data    = base64encode(local.cloud_init)

  ### TF will not update instances if upgrade_mode = "Rolling"

  # health_probe_id = azurerm_lb_probe.private_kube_api.id
  # upgrade_mode    = "Rolling"

  # rolling_upgrade_policy {
  #   max_batch_instance_percent              = 33
  #   max_unhealthy_instance_percent          = 33
  #   max_unhealthy_upgraded_instance_percent = 33
  #   pause_time_between_batches              = "PT1M"
  # }

  dynamic "admin_ssh_key" {
    for_each = var.ssh_public_keys

    content {
      username   = var.admin_username
      public_key = admin_ssh_key.value
    }
  }

  source_image_reference {
    publisher = var.image_publisher
    offer     = var.image_offer
    sku       = var.image_sku
    version   = var.image_version
  }

  os_disk {
    storage_account_type = var.disk_storage_account_type
    caching              = "ReadWrite"
    disk_size_gb         = var.disk_size_gb
  }

  identity {
    type = "SystemAssigned"
  }

  network_interface {
    name = "control"

    primary                       = true
    enable_accelerated_networking = false # Recommended by TAM

    ip_configuration {
      name = "internal"

      primary   = true
      subnet_id = var.subnet_id
      load_balancer_backend_address_pool_ids = [
        azurerm_lb_backend_address_pool.private_kube_api.id,
        azurerm_lb_backend_address_pool.public_kube_api.id
      ]

      dynamic "public_ip_address" {
        for_each = local.public_ip

        content {
          name = "public"
        }
      }
    }
  }


  tags = var.tags

  depends_on = [
    azurerm_lb_rule.private_kube_api,
    azurerm_lb_rule.public_kube_api
  ]
}

```

**Comment by rem-aj** [comment]
Hi @katbyte. we are seeing evidence of this behavior specifically with respect to azurerm_windows_virtual_machine_scale_set, where we set the upgrade_mode = "Manual". However when terraform runs and applies a change due to an update in extensions, it actually does "upgrade" the scaleset automatically. Can that be looked as as part of this bug also?
We are running 0.14.9 and azurerm provider 2.80
