### ISSUE TITLE
Allow AKS cluster creation with computing add-on on AKS

### ISSUE THREAD

**Issue by agowdamsft** [hashicorp/terraform-provider-azurerm#10689]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS has a new addon that will run Intel SGX device plugin on supported confidential computing nodes. This requires developer to add  anew addon name that TF should support. https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-overview#confidential-computing-add-on-for-aks . Requires support on Terraform

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

Not sure if this is entirely correct. Please modify if necessary.

```hcl
resource "azurerm_kubernetes_cluster" "aks" {

      confidential_computing {
      enabled = true
     

}
```

### References

https://docs.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-get-started

* #0000

**Comment by shebang89** [comment]
Example in Azure CLI:
`az aks create -g myResourceGroup --name myAKSCluster --generate-ssh-keys **--enable-addon confcom**`

**Comment by mbassett** [comment]
Yes how do you do this, I'm doing it right now via a null resource

```
resource "null_resource" "example_enable_ccomp" {
  provisioner "local-exec"{
     command = "az aks enable-addons --addons confcom --name ${azurerm_kubernetes_cluster.example.name} --resource-group ${azurerm_kubernetes_cluster.example.resource_group_name}"
  }
  depends_on = [azurerm_kubernetes_cluster.example]
}```

**Comment by agowdamsft** [comment]
@scav for the question above

**Comment by Syphon83** [comment]
any news about this feature? thank you

**Comment by agowdamsft** [comment]
@Syphon83 will update you shortly with an ETA when we can send this contribution.

**Comment by agowdamsft** [comment]
Thanks for the contribution @stephybun

**Comment by jon-signal** [comment]
Thank you, @stephybun!

I'm really excited to have the confidential computing in the Azure provider now, but it loooooks like #20111 does not include support for the [`--enable-sgxquotehelper` option available via the CLI](https://learn.microsoft.com/en-us/cli/azure/aks/addon?view=azure-cli-latest). Am I misunderstanding the situation, or is that option something that should be covered in the scope of a separate issue?

Again, thank you!

**Comment by agowdamsft** [comment]
It does here are the instructions https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-enclave-nodes-aks-get-started#create-an-aks-cluster-with-a-system-node-pool

**Comment by jon-signal** [comment]
@agowdamsft I'm really sorry, but I think I'm misunderstanding your point. I'm already familiar with (and just reread!) the document you just linked. The instructions (specifically the ["Create an AKS cluster with a system node pool" section](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-enclave-nodes-aks-get-started#create-an-aks-cluster-with-a-system-node-pool)) call out creating a cluster with the following CLI command:

```
az aks create -g myResourceGroup --name myAKSCluster --generate-ssh-keys --enable-addons confcom
```

…and that seems to be exactly what the changes in #20111 allow us to do via the Azure provider, which is great! At the same time, the [docs for `az aks create`](https://learn.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create) call out that `--enable-sgxquotehelper` is a separate option and that it does, in fact, default to `false`. I think that means that the cluster created by following the instructions you linked _and_ the new feature in #20111 will both create a new AKS cluster without the SGX quote helper enabled.

Incidentally, the sidebar in the instructions you mentioned includes a link to ["Confidential computing plugin for Confidential VMs"](https://learn.microsoft.com/en-us/azure/confidential-computing/confidential-nodes-aks-addon), which _does_ explicitly point out the need to use the `--enable-sgxquotehelper` option.

Pausing for a moment: is my understanding correct up to this point?

If I _am_ understanding the situation correctly, I understand how to add the SGX quote helper via the CLI, but it seems like that feature is still absent from the Terraform provider. Do you agree, or am I still misunderstanding the situation?

Thanks!

**Comment by agowdamsft** [comment]
@jon-signal terraform provider support for deploying the aks addon "confcom" was added here https://github.com/hashicorp/terraform-provider-azurerm/pull/20111/files. Azure CLI support existed but TF needed this capability which was recently added. 

Let me know if this answers your question.

**Comment by jon-signal** [comment]
> Let me know if this answers your question.

This does not answer my question.

Let me try explaining it another way. What I want to do is, essentially:

```terraform
resource "azurerm_kubernetes_cluster" "sgx_cluster"
{
  confidential_computing_enabled= true
  sgx_quote_helper_enabled = true
}
```

The changes in #20111 allow us to do `confidential_computing_enabled= true`, but I don't think they let us do `sgx_quote_helper_enabled = true`. Does that make sense?

**Comment by stephybun** [comment]
@jon-signal apologies, the documentation was a little unclear and this option was seemingly hidden away, thanks for pointing it out! I have another AKS PR in progress and I'll look into adding this to it.

**Comment by agowdamsft** [comment]
@jon-signal following you now. The sgxaddon/plugin is not triggered. I see @stephybun ack the same. Will review the ms docs and make necessary updates too.

**Comment by jon-signal** [comment]
Cheers, and thanks for your work on this!

> the documentation was a little unclear and this option was seemingly hidden away

We certainly got tripped up by this when setting up our first confidential computing cluster, too! Not to get too ambitious, but I wonder if it would be helpful to frame it as a sub-option of the confidential computing add-on to make it more discoverable and more clearly linked:

```terraform
resource "azurerm_kubernetes_cluster" "sgx_cluster"
{
  confidential_computing {
    enabled                  = true
    sgx_quote_helper_enabled = true
  }
}
```

Either way, though, I think it'll be a big help and big improvement. Thanks again!

**Comment by jon-signal** [comment]
> Will review the ms docs and make necessary updates too.

@agowdamsft Thanks!

**Comment by jon-signal** [comment]
Thanks so much!

**Comment by agowdamsft** [comment]
Thanks again for this contribution @stephybun
