### ISSUE TITLE
false positive config change with Azure VNet Subnet service endpoints config

### ISSUE THREAD

**Issue by benswu** [hashicorp/terraform-provider-azurerm#10710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue Description

Terraform reports false positive config change report if we update the same list of Subnet service endpoints but in different order. This is false positive config change report is impacting the infrastructure as a code design.

### Terraform (and AzureRM Provider) Version

0.13.4

### Affected Resource(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "Subnet001" {
  name                 = "Subnet001"
  resource_group_name  = azurerm_resource_group.rgterraform.name
  virtual_network_name = azurerm_virtual_network.eastasiavnet01.name
  address_prefixes       = ["192.168.12.0/26"]
  service_endpoints    = ["Microsoft.ServiceBus", "Microsoft.Sql", "Microsoft.Storage", "Microsoft.Web"]
}
```

### Debug Output

**Current Service Endpoint Config:**
 "serviceEndpoints": [
        {
          "locations": [
            "*"
          ],
          "provisioningState": "Succeeded",
          "service": "Microsoft.Web"
        },
        {
          "locations": [
            "eastasia",
            "southeastasia"
          ],
          "provisioningState": "Succeeded",
          "service": "Microsoft.Storage"
        },
        {
          "locations": [
            "eastasia"
          ],
          "provisioningState": "Succeeded",
          "service": "Microsoft.Sql"
        },

Apply terraform with the same service endpoints but in different order. 

resource "azurerm_subnet" "Subnet001" {
  name                 = "Subnet001"
  resource_group_name  = azurerm_resource_group.rgterraform.name
  virtual_network_name = azurerm_virtual_network.eastasiavnet01.name
  address_prefixes       = ["192.168.12.0/26"]
  service_endpoints    = ["Microsoft.ServiceBus", "Microsoft.Sql", "Microsoft.Storage", "Microsoft.Web"]
}

### Expected Behaviour

there should be no change on the service endpoints.

### Actual Behaviour

  # azurerm_subnet.Subnet001 will be updated in-place
  ~ resource "azurerm_subnet" "Subnet001" {
        address_prefix                                 = "192.168.12.0/26"
        address_prefixes                               = [
            "192.168.12.0/26",
        ]
        enforce_private_link_endpoint_network_policies = false
        enforce_private_link_service_network_policies  = false
        id                                             = "/subscriptions/7718cc33-171b-4e89-93b7-8edfe4ee2c6f/resourceGroups/RG_19831029/providers/Microsoft.Network/virtualNetworks/19831029-vnet01/subnets/Subnet001"
        name                                           = "Subnet001"
        resource_group_name                            = "RG_19831029"
      ~ service_endpoints                              = [
          **- "Microsoft.Web",
          - "Microsoft.Storage",
          - "Microsoft.Sql",
            "Microsoft.ServiceBus",
          + "Microsoft.Sql",
          + "Microsoft.Storage",
          + "Microsoft.Web",**
        ]
        virtual_network_name                           = "19831029-vnet01"
    }

Plan: 0 to add, **2 to change**, 0 to destroy.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

terraform apply out.plan
Acquiring state lock. This may take a few moments...
azurerm_subnet.Subnet001: Modifying... [id=/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/yyyyyyyyyyy/providers/Microsoft.Network/virtualNetworks/19831029-vnet01/subnets/Subnet001]
azurerm_network_security_group.main: Modifying... [id=/subscriptions/xxxxxxxxxx/resourceGroups/yyyyyyyyyyyyyy/providers/Microsoft.Network/networkSecurityGroups/19831029-nsg]
azurerm_subnet.Subnet001: Modifications complete after 2s [id=/subscriptions/xxxxxxxxxxxxx/resourceGroups/yyyyyyyyyyyyy/providers/Microsoft.Network/virtualNetworks/19831029-vnet01/subnets/Subnet001]
azurerm_network_security_group.main: Modifications complete after 5s [id=/subscriptions/xxxxxxxxxxxxx/resourceGroups/yyyyyyyyyyyyy/providers/Microsoft.Network/networkSecurityGroups/19831029-nsg]

Apply complete! Resources: 0 added**, 2 changed,** 0 destroyed.

### References

* #0000

**Comment by kenorb** [comment]
Same here.

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
```

**Comment by kenorb** [comment]
Same here.

```
  # module.....azurerm_subnet.nodes will be updated in-place
  ~ resource "azurerm_subnet" "nodes" {
        id                                             = "..."
        name                                           = "..."
      ~ service_endpoints                              = [
            "Microsoft.AzureActiveDirectory",
          + "Microsoft.AzureCosmosDB",
            "Microsoft.ContainerRegistry",
            "Microsoft.KeyVault",
          - "Microsoft.Storage",
          + "Microsoft.ServiceBus",
            "Microsoft.Sql",
          - "Microsoft.AzureCosmosDB",
          + "Microsoft.Storage",
        ]
        # (7 unchanged attributes hidden)
    }
```

```
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
```

**Comment by kenorb** [comment]
> ```
> Terraform v1.0.0
> on darwin_amd64
> + provider registry.terraform.io/hashicorp/azurerm v2.66.0
> ```

Actually my bad, after applied changes, it seems to work fine, no changes.

**Comment by AlexanderRijnbeek** [comment]
Issue is still there, 

 ~ service_endpoints                              = [
          - "Microsoft.Storage",
            "Microsoft.Sql",
            "Microsoft.KeyVault",
          + "Microsoft.Storage",
        ]

The returned list order of the service endpoints should not matter in the validation.

Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.79.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
