### ISSUE TITLE
Support for CDN Web Application Firewall policies

### ISSUE THREAD

**Issue by fwiedmann** [hashicorp/terraform-provider-azurerm#10716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello everyone! 

Azure provides the ability to create WAF policies for CDN Endpoints. This feature is currently in preview status. (https://docs.microsoft.com/de-de/azure/web-application-firewall/cdn/cdn-overview).

Currently, I have to create the policies via the [`az cdn waf policy`](https://docs.microsoft.com/en-us/cli/azure/cdn/waf/policy?view=azure-cli-latest) command afterwards I created the CDN profile + endpoint via terraform. 
I would love to manage this resource type with terraform too!

### New or Affected Resource(s)
This resource type could be a completely new resource type or it can be added to the azurerm_web_application_firewall_policy by adding type for  different types`Azure Front Door` `Azure Appliaction Gateway` & `Azure CDN Endpoints`

new:
* azurerm_cdn_web_application_firewall_policy

 or to the existing:
* azurerm_web_application_firewall_policy

### Potential Terraform Configuration

Extend the existing `azurerm_web_application_firewall_policy` resource with the type of resource the policy is for:
```hcl

resource "azurerm_web_application_firewall_policy" "example" {
...
policy_resource_type: "CDN" // CDN; FrontDoor; ApplicationGateway
...
}
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy
* https://docs.microsoft.com/en-us/cli/azure/cdn/waf/policy?view=azure-cli-latest
* https://docs.microsoft.com/de-de/azure/web-application-firewall/cdn/cdn-overview

**Comment by IanMoroney** [comment]
Seeing as how the Azure Portal lets you select the "policy for" type when creating a new waf policy, should mean to say this would be an improvement to the existing `azurerm_web_application_firewall_policy` resource.

![image](https://user-images.githubusercontent.com/10791260/109145347-4a2a9a00-775a-11eb-930d-823a8112c5e8.png)

**Comment by fwiedmann** [comment]
yes, definitely :)
