### ISSUE TITLE
Error: A role definition cannot be updated with a name that already exists

### ISSUE THREAD

**Issue by mattvella07** [hashicorp/terraform-provider-azurerm#10728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0
```

### Affected Resource(s)

* `azurerm_role_definition`

### Terraform Configuration Files

```hcl
resource "azurerm_role_definition" "cluster_autoscaler" {
  name        = format("%s-%s", var.cluster, "autoscaler")
  scope       = data.azurerm_subscription.primary.id
  description = "This is a custom role created via Terraform"

  permissions {
    actions = [
      "Microsoft.Compute/virtualMachineScaleSets/networkInterfaces/read",
      "Microsoft.Compute/virtualMachineScaleSets/publicIPAddresses/read",
      "Microsoft.Compute/virtualMachineScaleSets/read",
      "Microsoft.Compute/virtualMachineScaleSets/write",
      "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/instanceView/read",
      "Microsoft.Compute/virtualMachineScaleSets/virtualMachines/read",
      "Microsoft.Compute/virtualMachines/read",
      "Microsoft.Compute/virtualMachines/instanceView/read",
      "Microsoft.Network/dnsoperationresults/read",
      "Microsoft.Network/dnsoperationstatuses/read",
      "Microsoft.Network/dnszones/A/delete",
      "Microsoft.Network/dnszones/A/read",
      "Microsoft.Network/dnszones/A/write",
      "Microsoft.Network/networkInterfaces/read",
      "Microsoft.ServiceBus/operations/read",
      "Microsoft.ServiceBus/namespaces/read",
      "Microsoft.ServiceBus/namespaces/write",
      "Microsoft.ServiceBus/namespaces/topics/read",
      "Microsoft.ServiceBus/namespaces/topics/write",
      "Microsoft.ServiceBus/namespaces/topics/subscriptions/read",
      "Microsoft.ServiceBus/namespaces/topics/subscriptions/write",
    ]

    not_actions = []
  }

  assignable_scopes = [
    data.azurerm_resource_group.cluster.id
  ]
}
```

### Panic Output

none

### Expected Behaviour

Creates role

### Actual Behaviour

Returns the following error:
```
time="2021-02-22T21:13:36Z" level=error msg="terraform command apply failed with 
error: exit status 1\nstderr: \nError: authorization.RoleDefinitionsClient#CreateOrUpdate: 
Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: 
Service returned an error. Status=409 Code=\"RoleDefinitionWithSameNameExists\" 
Message=\"A role definition cannot be updated with a name that already exists.\"\n\n
 on autoscaler.tf line 23, in resource \"azurerm_role_definition\" 
\"cluster_autoscaler\":\n 23: resource \"azurerm_role_definition\" 
\"cluster_autoscaler\" {​​​​​​​​\n\n\n\nError: authorization.RoleDefinitionsClient#CreateOrUpdate: 
Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: 
Service returned an error. Status=409 Code=\"RoleDefinitionWithSameNameExists\" 
Message=\"A role definition cannot be updated with a name that already exists.\"\n\n 
on ingress-controller.tf line 86, in resource \"azurerm_role_definition\" 
\"azure_ingress_controller\":\n 86: resource \"azurerm_role_definition\" 
\"azure_ingress_controller\" {​​​​​​​​\n\n\n" source="terraform/terraform.go:318"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This happens when creating resources in a brand new resource group, so the role name does not already exist.  It happens consistently every time trying to create the resources.  Looking through the Activity Log for the resource group, it shows this error: `The role definition ID 'b5b1b1fd-38b2-4b3f-d6e1-83e3584bf39c|' is not valid`.  From my understanding that role definition ID is generated by terraform as it is only an output for azurerm_role_definition.

### References

* #0000

**Comment by derekwilliamsliquidx** [comment]
Experiencing a similar issue when creating a NEW role definition. Role Def created, but then says
```
Error: authorization.RoleDefinitionsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="RoleDefinitionDoesNotExist" Message="The specified role definition with ID '9666788d-ea0e-c4c2-29a5-a23b1bf2cdc9' does not exist."
```

When using the AZ commandline I can find the role def I create by name and the GUID DOES exist.

**Comment by mattvella07** [comment]
Any updates on this issue?  I'm still seeing the same behavior with the latest arzuerm version (v2.52.0)

**Comment by codenamekt** [comment]
Same with @mattvella07. I'm seeing this issue arzuerm version (v2.52.0)

**Comment by nitmatgeo** [comment]
@favoretti @aristosvo  Please help to have a check on this. Even in (v2.63.0) this issue is there... Pretty difficult to manage automation with these issues. Requesting some favour, please 😄

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
