### ISSUE TITLE
azurerm_sql_database / azurerm_mssql_database threat_detection_policy not optional

### ISSUE THREAD

**Issue by papymaj5** [hashicorp/terraform-provider-azurerm#10742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform 0.14.7
* azurerm v2.48.0

### Affected Resource(s)

* azurerm_sql_database
* azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_sql_database" "site_db" {
  name                = "vcd-sqldb-cloud-siem-${var.webapp_name}"
  resource_group_name = azurerm_resource_group.webapp_rg.name
  server_name         = "vcd-mssql-cloud-siem-${var.webapp_name}"
  location            = var.location
  edition             = "Basic"
  tags                = local.tags
  depends_on = [module.sqlserver]
}

resource "azurerm_mssql_database" "site_db" {
  name              = "vcd-sqldb-cloud-siem-${var.webapp_name}"
  server_id         = module.sqlserver.sqlserver_id
  collation         = "SQL_Latin1_General_CP1_CI_AS"
  max_size_gb       = 2
  sku_name          = "Basic"
  tags              = local.tags
}
```

### Expected Behavior

Not declaring a threat_detection_policy block should not create a threat_detection_policy in the plan and apply stages

### Actual Behavior

Creating a threat detection policy

### Steps to Reproduce

Create one of these resources without a threat_detection_policy block:
* azurerm_sql_database
* azurerm_mssql_database

### References

* #0000
![image](https://user-images.githubusercontent.com/7863607/109188822-5108db00-7761-11eb-81a4-3f5ba9e9dcab.png)

**Comment by fgarcia-cnb** [comment]
im having the same issue. the threat detection policy is supposed to be optional. If its not defined, subsequent runs keep trying to apply a disabled threat detection policy. Using azurerm v2.90.0

**Comment by fgarcia-cnb** [comment]
turns out we had an MS azure defender policy that enabled MS defender on open source relational DBs. this was forcing the threat detection policy to enabled, which conflicted with what was in code. @papymaj5 you might want to check and make sure you're not having the same issue

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
