### ISSUE TITLE
adding 1 policy_definition to for_each causes all policy_assignments to rebuild. works fine with count

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#10745]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_policy_assignment`

Using TF v0.12.24
azurerm v2.49.0

### Terraform Configuration Files

```hcl
data "azurerm_policy_definition" "existing_policies" {
  for_each = { for policy in var.existing_policies : policy.display_name => policy }

  display_name          = each.value.display_name
  management_group_name = try(each.value.management_group_name, null)
}

resource "azurerm_policy_definition" "custom_policies" {
  for_each = { for policy in var.custom_policies : policy.name => policy }

  name                  = each.value.name
  policy_type           = each.value.policy_type
  mode                  = each.value.mode
  display_name          = each.value.display_name
  description           = try(each.value.description, null)
  management_group_name = try(each.value.management_group_name, null)
  metadata              = try(each.value.metadata, null)
  policy_rule           = try(each.value.policy_rule, null)
  parameters            = try(each.value.parameters, null)
}

all_policy_ids = merge(azurerm_policy_definition.custom_policies, data.azurerm_policy_definition.existing_policies)

resource "azurerm_policy_assignment" "policy-assignments" {
  for_each =...
...
  policy_definition_id = local.all_policy_ids[try(each.value.name, each.value.display_name)].id
...
}

```

### Expected Behaviour

If I use count instead of for_each in ```azurerm_policy_definition.custom_policies```, and I add a resource (ie. increase count by 1), it only creates the additional policy assignment related to the new policy, and leaves old policies alone, as expected.

However, if i use for_each in  ```azurerm_policy_definition.custom_policies```, the new resource is added in random order to the output map. The changes to the output map of ```azurerm_policy_definition.custom_policies``` is forcing all policy assignments to recalculate their value for policy_definition_id (i.e. known after apply)

I think this is more of an issue with accessing the map output generated by creating resources with for_each rather than count. not necessarily an issue with the resource. but the whole point of using for_each is to avoid unnecessary changes when modifying items within a list of resources. Unless i'm doing something wrong?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
