### ISSUE TITLE
azurerm_key_vault_secret issue Request is missing a Bearer or PoP token

### ISSUE THREAD

**Issue by jwendl** [hashicorp/terraform-provider-azurerm#10798]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform: 0.14.7
terraform-provider-azurerm: 2.49.0

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "Test"
  location = "westus"
}

resource "azurerm_key_vault" "example" {
  name                       = "jwexamplekv"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "premium"
  soft_delete_retention_days = 7

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "create",
      "get",
    ]

    secret_permissions = [
      "set",
      "get",
      "delete",
      "purge",
      "recover"
    ]
  }
}

resource "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.example.id
}
```

### Debug Output

https://gist.github.com/jwendl/123021e4bbc8450bb0cce425bce4a16e

### Expected Behaviour

Secret is created and state file is updated.

### Actual Behaviour

Error: A resource with the ID "https://jwexamplekv.vault.azure.net/secrets/secret-sauce/50e09208fb164ee2b2b232b0eb52554e" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_secret" for more information.

  on main.tf line 35, in resource "azurerm_key_vault_secret" "example":
  35: resource "azurerm_key_vault_secret" "example" {

### Steps to Reproduce

1. `terraform apply`

### References

Importing it and running again shows that everything deployed properly.
```
❯ t plan -out tf.plan
2021/03/02 20:36:03 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
azurerm_resource_group.example: Refreshing state... [id=/subscriptions/959965bb-d9df-4c6f-825e-37e1090d817d/resourceGroups/Test]
azurerm_key_vault.example: Refreshing state... [id=/subscriptions/959965bb-d9df-4c6f-825e-37e1090d817d/resourceGroups/Test/providers/Microsoft.KeyVault/vaults/jwexamplekv]
azurerm_key_vault_secret.example: Refreshing state... [id=https://jwexamplekv.vault.azure.net/secrets/secret-sauce/50e09208fb164ee2b2b232b0eb52554e]

No changes. Infrastructure is up-to-date.

This means that Terraform did not detect any differences between your
configuration and real physical resources that exist. As a result, no
actions need to be performed.
❯ t apply tf.plan
2021/03/02 20:36:13 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

* #0000

**Comment by slyons** [comment]
Seconding this for version 2.2.1

**Comment by tombuildsstuff** [comment]
hi @jwendl @slyons 

Thanks for opening this issue.

As per the error that Terraform is raising here, this resource already exists in Azure and needs to be imported into Terraform:

> Error: A resource with the ID "https://jwexamplekv.vault.azure.net/secrets/secret-sauce/50e09208fb164ee2b2b232b0eb52554e" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_secret" for more information.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
