### ISSUE TITLE
Sql Virtual Machine : Ext_AutomatedBackupError

### ISSUE THREAD

**Issue by artyq** [hashicorp/terraform-provider-azurerm#10791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Initializing provider plugins...
Checking for available provider plugins...
- Downloading plugin for provider "azurerm" (hashicorp/azurerm) 2.49.0...

### Affected Resource(s)

* `azurerm_mssql_virtual_machine`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_mssql_virtual_machine" "sqlvm" {
  virtual_machine_id               = module.host_server.id
  sql_license_type                 = local.sql_license
  r_services_enabled               = var.rservices
  sql_connectivity_port            = 1433
  sql_connectivity_type            = "PRIVATE"

  auto_patching {
    day_of_week                            = "Sunday"
    maintenance_window_duration_in_minutes = 60
    maintenance_window_starting_hour       = 2
  }

  key_vault_credential {
    name                      = "AKVCred"
    key_vault_url             = "${data.azurerm_key_vault.hostingsqlkv.vault_uri}" 
    service_principal_name    = "${data.azurerm_key_vault_secret.readerid.value}"
    service_principal_secret  = "${data.azurerm_key_vault_secret.spreadersecret.value}"
  }

 storage_configuration {
    disk_type                               = var.sqldisktype
    storage_workload_type                   = var.workloadtype
    data_settings {
     default_file_path = "M:\\data"
     luns = (local.datadisk_count == "1") ? [1] : range(1, local.datadisk_count+1)
    }
    log_settings {
     default_file_path = "L:\\logs"
     luns = (local.logdisk_count == "1") ? [10] : range(10, (local.logdisk_count+10))
    }
 }

 depends_on = [
     module.logdisk, 
     module.datadisk,
     azurerm_virtual_machine_extension.customconfigurations
  ]
}

### Expected Behaviour

SQL Virtual Machine is created without Automated Backup.  Last working version for us is 2.46.1

### Actual Behaviour

SQL Virtual Machine fails the creation.  It appears to think we have the auto_backup block.

Error: waiting for creation of Sql Virtual Machine (Sql Virtual Machine Name "stdcsql-aqsb33" / Resource Group "hosting-sql-sandbox-aq-dev-rg"): Code="Ext_AutomatedBackupError" Message="Error: 'Time out has expired and the operation has not been completed.'"
  on .terraform/modules/sql-server-host-aqsb32/main.tf line 21, in resource "azurerm_mssql_virtual_machine" "sqlvm":
  21: resource "azurerm_mssql_virtual_machine" "sqlvm" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
sql2019-ws2019 latest.
We execute a custom script extension prior to azurerm_mssql_virtual_machine that switches to another collation if the client chooses, as well as setting gMSA as the service owner.

### References

* #0000

**Comment by artyq** [comment]
Is there any update on this issue?  We are still stuck using 2.46.1

**Comment by tombuildsstuff** [comment]
hi @artyq 

Thanks for opening this issue.

Taking a look through this appears to be a usage question rather than a bug/feature request in the Provider - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by artyq** [comment]
@tombuildsstuff This is a bug.

Nowhere in our code do we provide the backup block.  Yet AzureRM providers above 2.46.1 is enforcing it on us.  

We don't want it.  We are using Recovery Services Vaults and registering our instances as protected.  No one should use the automated backup solution in my opinion for production instances.

TF is failing as we don't provide any details for the backup block so it fails. If we were to provide details and have it configured, it would cause issues with our actual backup system.  It would cause the backup chain to be all over the place and cause major headaches in restoring DBs.

**Comment by artyq** [comment]
I should add that the TF documentation states that the auto_backup block should be optional.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_virtual_machine
