### ISSUE TITLE
TF doesn't detach disks from a VM when resizing the disk beyond 4095 GiB causing an Azure Error

### ISSUE THREAD

**Issue by kazikfriedrich** [hashicorp/terraform-provider-azurerm#10792]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.30
terraform-provider-azurerm_v2.48.0
```
### Affected Resource(s)

* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "data_disk" {
  name                 = "data_disk"
  location             = "West US 2"
  resource_group_name  = azurerm_resource_group.resource_group.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "9000" ### Going up from 4000

  tags = {
    environment = "dev"
  }
}
```

### Debug Output

https://gist.github.com/kazikfriedrich/fc455894d5561463016a30ad106ad977

### Expected Behaviour

TF should perform the following actions when resizing the disk over 4095 GiB:

1. Stop the VM
2. Detach the disk
3. Resize disk
4. Attach disk back
5. Start the VM

### Actual Behaviour

1. TF stops the VM
2. TF attempts to resize disk
3. Azure returns the `Disks cannot be resized beyond 4095 GiB when attached to a VM` error:
```
Error: Error updating Managed Disk "some_disk_name" (Resource Group "name-of-resource-group"): compute.DisksClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Disks cannot be resized beyond 4095 GiB when attached to a VM. Detach disk some_disk_name from VM /subscriptions/some_uuid/resourceGroups/name-of-resource-group/providers/Microsoft.Compute/virtualMachines/some-hostname and try again. If caching is enabled for this disk, it will not be supported for disks greater than 4095 GiB."
```

### Steps to Reproduce

Create a VM, attach a disk of any size below 4095GiB, attempt to resize the attached disk to anything over 4095GiB

**Comment by RawPatty** [comment]
I am also having a simliar issue with running terraform 1.3.7

<html><body>
<p dir="auto"><span>Terraform behaviour
is as below when resizing data disks on running VMs:</span></p>
<p dir="auto"><span> </span></p>


Action | Result | Notes
-- | -- | --
4GiB ->   4095GiB     (case 1) | Hot extend with   no issue | no outage is   required
Below 4095GiB to   4096GiB or above   (case 2) | Error with outage | To successfully   resize, I had to manually detach the disk and  reapply the plan. The plan   would create a new attachment object and  make a data disk  change to the   size   This use case   causes an  expected outage to the virtual machine, but also fails.   Please see    attached screenshot
4096GiB to   8192GiB +   (case 3) | Error with no   outage | To successfully   resize from here with Terraform, the VM needed to  be manually shut down   before applying the plan. This would require an  outage to successfully apply   Please see   attached screenshot
8192GiB + | Hot extend with   no issues | No outage is   required


<p dir="auto"><span> </span></p>
</body>
</html>
