### ISSUE TITLE
Host Header should not be required for Azure FrontDoor

### ISSUE THREAD

**Issue by kevinmatthews-kpmg** [hashicorp/terraform-provider-azurerm#10806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
latest

### Affected Resource(s)

azurerm_frontdoor

### Terraform Configuration Files

```hcl
backend_pool {
    name = "exampleBackendBing"
    backend {
      host_header = "www.bing.com"
      address     = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "exampleLoadBalancingSettings1"
    health_probe_name   = "exampleHealthProbeSetting1"
  }
```

### Expected Behaviour

Host Header is an optional field which if not set will use the frontend that has come through

### Actual Behaviour

Host Header in terraform is put down as a required field.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by WodansSon** [comment]
The legacy Frontdoor API is being retired so there will be no further development of these resources, moving forward only the CDN Frontdoor will be supported.
