### ISSUE TITLE
Unable to set azurerm_api_management_product subscriptions_limit to unlimited when it has been previously restricted to a specific number of subscriptions

### ISSUE THREAD

**Issue by Tiberriver256** [hashicorp/terraform-provider-azurerm#10812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.18.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
```

### Affected Resource(s)

* `azurerm_api_management_product`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_product" "product" {
  product_id            = var.product_id
  api_management_name   = var.api_management_name
  resource_group_name   = var.resource_group_name
  display_name          = var.display_name
  subscription_required = var.is_subscription_required
  approval_required     = var.is_approval_required
  published             = var.is_published
  subscriptions_limit   = null
}
```

### Expected Behaviour

When I set the subscriptions_limit to null
   or omit the subscriptions_limit option
Then I should have the subscriptions_limit set to null (i.e. unlimited)

### Actual Behaviour

The subscriptions_limit option was previously set to `0` and now I have no way to move it from being `0` back to being unlimited. It's detected as no change necessary and leaves it at 0 or whatever number I had set previously.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
