### ISSUE TITLE
Support for role-based access control for data plane operations in Azure Cosmos DB

### ISSUE THREAD

**Issue by mrichards3** [hashicorp/terraform-provider-azurerm#10817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Cosmos DB role-based access control is currently in preview.
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac

I would like to be able to use this feature from Terraform in order to:
* Define custom database roles that can access my Cosmos DB databases
* Assign custom database roles to Azure AD identities 

### New or Affected Resource(s)

* azurerm_cosmosdb_role_definition
* azurerm_cosmosdb_role_assignment

### Potential Terraform Configuration

```hcl
# Conceptually, I think that the new resources would work similarly to the existing
# azurerm_role_definition and azurerm_role_assignment resources, except that they
# will operate against the Cosmos DB management APIs.
```

### References

* https://devblogs.microsoft.com/cosmosdb/role-based-access-control-preview/
* https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac

**Comment by mikemowgli** [comment]
Another approach would be to reuse enhance the existing `azurerm_role_definition` resource with `provider` flag. For CosmosDB, its value would be `Microsoft.DocumentDB`. That way, if the Azure team would implement another data plane RBAC model for another service (e.g. Synapse, SQL Server, Analysis Service, ...), the same resource would be kept, only the `provider` flag would change.

**Comment by jarrodd07** [comment]
I tried adding these resources myself, but was blocked by this issue in the Go SDK
https://github.com/Azure/azure-sdk-for-go/issues/15295

**Comment by dr-dolittle** [comment]
Do you plan to support RBAC on Data Plane soon? I need it urgently.

See also [Configure role-based access control with Azure Active Directory for your Azure Cosmos DB account](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac)

**Comment by adamyager** [comment]
@tombuildsstuff  this has now been unblocked.

**Comment by heiniilmarinen** [comment]
Is this a duplicate and has been closed with this [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/13907)?
