### ISSUE TITLE
azurerm_api_management_api_diagnostic documentation 

### ISSUE THREAD

**Issue by rnmakino** [hashicorp/terraform-provider-azurerm#10822]
Hi, found two Errors on azurerm_api_management_api_diagnostic documentation example:

1 - Capital "V" on verbosity level:   verbosity                 = "Verbose"
2 - Missing required argument identifier

Best Regards,
Ricardo Makino

**Comment by jayendranarumugam** [comment]
@rnmakino can you explain 
>the missing required argument identifier ? 

verbose is actually an optional one which property you are referring here ?

**Comment by rnmakino** [comment]
> @rnmakino can you explain
> 
> > the missing required argument identifier ?
> 
> verbose is actually an optional one which property you are referring here ?

Hi @jayendranarumugam, verbosity is optional, but on the example usage it was writtten with capital "V", it should be with lowercase "v".

![Screen Shot 2021-10-04 at 11 09 15](https://user-images.githubusercontent.com/28014404/135866745-5d528f1b-abb8-4c55-87e1-b10ab36e49a1.png)

The argument identifier is required and is not included on the example usage.

Best Regards,
Ricardo Makino

**Comment by jayendranarumugam** [comment]
Understood on case issue, Infact I already drafted my PR with the lower case v from the doc 
> The argument identifier is required and is not included on the example usage.

Which argument identifier is not included on the example usage ?

**Comment by rnmakino** [comment]
> Understood on case issue, Infact I already drafted my PR with the lower case v for the doc
> 
> > The argument identifier is required and is not included on the example usage.
> 
> Which argument identifier is not included on the example usage ?

This one: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_diagnostic#identifier
