### ISSUE TITLE
Stack Settings for Python running under Windows Os not functional

### ISSUE THREAD

**Issue by kay07949** [hashicorp/terraform-provider-azurerm#10836]
i am trying to set the stack settings for python running in windows os via terraform:
![image](https://user-images.githubusercontent.com/41331053/109973583-7d3bd300-7cf0-11eb-8709-85da3e2bcc1c.png)

![image](https://user-images.githubusercontent.com/41331053/109968436-9c376680-7cea-11eb-8591-d668035bd23a.png)

below is the terraform code:

 
![image](https://user-images.githubusercontent.com/41331053/109969144-75c5fb00-7ceb-11eb-8920-9ae951d60228.png)

However this does not configure the stack settings. instead it resets to .net stack : 

![image](https://user-images.githubusercontent.com/41331053/109979183-862fa300-7cf6-11eb-8f9b-0c7c1440ba1a.png)

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
