### ISSUE TITLE
Allow Kubernetes Additional Nodes to autoscale down to 0

### ISSUE THREAD

**Issue by morsik** [hashicorp/terraform-provider-azurerm#10837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.46.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "win" {
  name                  = "win"  # max 6 chars, so "windows" is too long ;-)
  kubernetes_cluster_id = azurerm_kubernetes_cluster.cicd.id
  vm_size               = "Standard_B2s"

  vnet_subnet_id = azurerm_subnet.cicd.id

  os_type = "Windows"

  enable_auto_scaling = true
  min_count = 0
  max_count = 2
}

```

### Expected Behaviour

Since Azure web page allows additional node pools to scale down to 0, it should be possible to set also via terraform.

### Actual Behaviour

Azure API fails on what Terraform does, because Terraform doesn't care about `min_count = 0` - it just doesn't pass `min_count` to API at all when value is `0`.

See plan - `min_count` is missing when it's set to `0`:

```
  # azurerm_kubernetes_cluster_node_pool.win will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "win" {
      ~ enable_auto_scaling    = false -> true
        id                     = "**CENSORED**"
      ~ max_count              = 0 -> 2
        name                   = "win"
        tags                   = {}
        # (18 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

Because of that, I've got this error from Azure API:

```
azurerm_kubernetes_cluster_node_pool.win: Modifying... [id=/subscriptions/**CENSORED**/agentPools/win]

Error: updating Node Pool "win" (Kubernetes Cluster "cicd" / Resource Group "CICD"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Required parameter agentPoolProfile.minCount is missing (null)." Target="agentPoolProfile.minCount"
```

### Steps to Reproduce

See above.

**Comment by favoretti** [comment]
Hi @morsik, thank you for reporting this.
Looking at the source code, you should pass `null` instead of `0`:
```
"min_count": {
				Type:     schema.TypeInt,
				Optional: true,
				// NOTE: rather than setting `0` users should instead pass `null` here
				ValidateFunc: validation.IntBetween(0, 1000),
			},
```

Could you please try it and let me know if it work? In the meantime I'll look into either making `0` work or adjusting docs to include that comment :)

**Comment by morsik** [comment]
@favoretti I can confirm it works properly with `null`.

But let's be honest - this is totally counterintuitive :)

**Comment by favoretti** [comment]
@morsik I completely agree with you :) I'll assign this to myself and will try to make it work with a 0 if at all possible :)

**Comment by cailyoung** [comment]
I think this just happened for us, and I think it's because the plan includes:

```
~ enable_auto_scaling    = false -> true
```

We've had changes of `min_count` from 1 -> 0 work in the past when `enable_auto_scaling` was already `true`, but today we had a node pool which had been manually set to not autoscale before our `apply` and this failure was observed. So, my theory is that when the current object is `enable_auto_scaling = false` then there is no `min_count` at all, so it isn't pulled in from the `.tf ` file? This then causes the AKS API to complain that we aren't supplying `min_count`.

**Comment by stephybun** [comment]
Related to #11056. Closing since this is possible now.
