### ISSUE TITLE
IoT Central application provisioning fails because of Azure CLI version 2.20.0 update

### ISSUE THREAD

**Issue by hovtoros** [hashicorp/terraform-provider-azurerm#10861]
The usage of _azurerm_iotcentral_application_ resource has recently started failing with any type of execution scenario.

At first, _terraform init_ command runs successfully.

Then during execution of _terraform plan_ the following error is produced:

##############################################
Error: ID was missing the `IoTApps` element
##############################################

That's all from the error side.

After some investigation, I was able to find out that **Azure CLI** tool was updated to version **2.20.0** on March 02, 2021. This update brought the change of _resourceType_ abbreviation for IoT Central applications ID, please see the release notes [here](https://docs.microsoft.com/en-us/cli/azure/release-notes-azure-cli?tabs=azure-cli#iot-central).

It seems, that for now Azure CLI requires camel-cased _resourceType_ abbreviation, i.e. `IotApps`, but _azurerm_iotcentral_application_  consumes `IoTApps` version.

System configuration:
- Terraform v0.14.5
- azurerm v2.49.0

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
