### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_log is not recognized as a valid resource type

### ISSUE THREAD

**Issue by sean-t-shen** [hashicorp/terraform-provider-azurerm#10865]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.6
provider registry.terraform.io/hashicorp/azurerm v2.44.0

### Affected Resource(s)

azurerm_monitor_scheduled_query_rules_log

### Expected Behaviour

According to this reference below:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_log
"azurerm_monitor_scheduled_query_rules_log" should have been a valid resource type that can be imported.

The linked article above even contains instruction on how to import it
terraform import azurerm_monitor_scheduled_query_rules_log.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.Insights/scheduledQueryRules/myrulename

But it is not working for me.

### Actual Behaviour

when running terraform import, 
Error: unknown resource type: azurerm_scheduled_query_rules_log

### Steps to Reproduce

1. HCL code:
  resource "azurerm_scheduled_query_rules_log" "jira_servicedesk_insightserver_mem_mon" {
      name                = "insight-server-mem-usage-percent"
      blah bluah

2. Terraform import
    terraform import azurerm_monitor_scheduled_query_rules_log.jira_servicedesk_insightserver_mem_mon /subscriptions/1234567-abcdefg-7654321-00000000/resourceGroups/inf-jira-et/providers/microsoft.insights/scheduledqueryrules/insight-server-mem-usage-percent

3. Got the error as stated above.

4. Also, I tried to create a new resource of type "azurerm_scheduled_query_rules_log" and the planning simply failed with the following error:
     The provider provider.azurerm does not support resource type
     "azurerm_scheduled_query_rules_log".

### References

* #0000

**Comment by jackofallops** [comment]
Hi @sean-t-shen 
Looking at the issue text, you have a typo in your config, and missing the `monitor` portion of the resource type:

> resource "azurerm_scheduled_query_rules_log" "jira_servicedesk_insightserver_mem_mon"

the resource type should be `azurerm_monitor_scheduled_query_rules_log`
To import your existing resource as you have in step 2, you would use:
```
terraform import azurerm_monitor_scheduled_query_rules_log.jira_servicedesk_insightserver_mem_mon /subscriptions/1234567-abcdefg-7654321-00000000/resourceGroups/inf-jira-et/providers/Microsoft.Insights/scheduledQueryRules/insight-server-mem-usage-percent
```

Hope this helps.

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed and 2.x version of the provider is no longer actively maintained, I am going to close this issue.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
