### ISSUE TITLE
Error Creating Private Endpoint against ACR

### ISSUE THREAD

**Issue by jabba2324** [hashicorp/terraform-provider-azurerm#10880]
The given error is thrown when creating 8 private endpoints against a ACR being refrenced as a data entity.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.50.0

### Affected Resource(s)

* `azurerm_private_endpoint` and `azurerm_container_registry`

### Terraform Configuration Files

```hcl
data "azurerm_container_registry" "acr" {
  name                = var.container-registry-name
  resource_group_name = data.azurerm_resource_group.acr-group.name
}

resource "azurerm_private_endpoint" "acr-private-endpoint" {
  for_each             = {for v in azurerm_virtual_network.vnet : v.name => v}

  name                = "acr-endpoint"
  location            = each.value.location
  resource_group_name = each.value.resource_group_name
  subnet_id           = lookup({ for s in azurerm_subnet.acr-subnet : s.name => s.id }, "acr- 
  subnet", "Could not map subnet to region!")

  private_service_connection {
    name                           = "acr-privateserviceconnection"
    private_connection_resource_id = data.azurerm_container_registry.acr.id
    subresource_names              = ["registry"]
    is_manual_connection           = false
  }
}

```

### Debug Output

```

Error: waiting for creation of Private Endpoint "acr-endpoint" (Resource Group "rg"): Code="1:The property value exceeds the maximum allowed size (64KB). If the property value is a string, it is UTF-16 encoded and the maximum number of characters should be 32K or less." Message="Call to Microsoft.ContainerRegistry/registries failed. Error message: Element 1 in the batch returned an unexpected response code." Details=[]

```

### Expected Behaviour

The Private endpoints are created

### Actual Behaviour

This above error is thrown

### Steps to Reproduce

1. `terraform apply`

**Comment by jabba2324** [comment]
Update: the private link resource is created but never approved/configured and left in a failed state. This error could be related to the failed approval.

**Comment by EppO** [comment]
> Update: the private link resource is created but never approved/configured and left in a failed state. This error could be related to the failed approval.

I ran into the same issue but resource is approved and left in failed provisioning state. Looks like NIC gets assigned 9!!! IP addresses (instead of the usual 2). Only happened for me in West US so far, other regions I've tried doesn't have the issue

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
