### ISSUE TITLE
r/log_analytics_workspace: updating the default feature-flag in 3.0

### ISSUE THREAD

**Issue by tombuildsstuff** [hashicorp/terraform-provider-azurerm#10885]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Description

The [Feature Flag `permanently_delete_on_destroy` within the `log_analytics_workspace` block](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/features/defaults.go#L11) should be defaulted to `true` rather than `false` since the Delete should clean this up automatically, rather than soft-deleting by default - unfortunately this has already shipped, so we'll need to make this breaking change in 3.0.

**Comment by katbyte** [comment]
closing as on main:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/1638467/159583997-8846fce6-6b65-4740-84e5-a5ad8d637e79.png">
