### ISSUE TITLE
Optional log_monitoring_enabled in Azure SQL Database resource defaults to true 

### ISSUE THREAD

**Issue by petenorth** [hashicorp/terraform-provider-azurerm#10915]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.29 of Terraform
2.50.0 of the AzureRM provider

### Affected Resource(s)

* `azurerm_sql_database`
* `mssql_database_extended_auditing_policy resource`

### Expected behaviour

No changes applied to an existing resource as the log_monitoring_enabled is an optional property .

I would expect the default value of the optional property to be false.

### Actual Behaviour

```
     ~ extended_auditing_policy         = [
       ~ {
         ~ log_monitoring_enabled                  = false -> true
           retention_in_days                       = 1
           storage_account_access_key              = "xxxxxxxx"
           storage_account_access_key_is_secondary = false
           storage_endpoint                        = "xxxxxxxx"
         },
     ]
```

In the plan the `log_monitoring_enabled` property going to changed from false to true even though it has not been set.

### Steps to Reproduce

`terraform plan`

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database#log_monitoring_enabled

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
