### ISSUE TITLE
"azurerm_databricks_workspace" with custom_parameters forces unnecessary replacement

### ISSUE THREAD

**Issue by jeromewaibel** [hashicorp/terraform-provider-azurerm#10932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.13.6
azurerm 2.50.0
databrickslabs/databricks v0.3.1

### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "this" {
  name                        = "brickandmorty"
  resource_group_name         = azurerm_resource_group.this.name
  location                    = azurerm_resource_group.this.location
  sku                         = "premium"
  managed_resource_group_name = "rgmanaged"

  custom_parameters {
    no_public_ip = false
    public_subnet_name = "brickandmorty-public"
    private_subnet_name = "brickandmorty-private"
    virtual_network_id = ".../vnet/id"
  }
}
```

### Debug Output

```
  # azurerm_databricks_workspace.this must be replaced
-/+ resource "azurerm_databricks_workspace" "this" {
      ~ id                          = "/subscriptions/.../providers/Microsoft.Databricks/workspaces/brickandmorty" -> (known after apply)
        location                    = "westeurope"
      ~ managed_resource_group_id   = "/subscriptions/..." -> (known after apply)
        managed_resource_group_name = "rgmanaged"
        name                        = "brickandmorty"
        resource_group_name         = "rgtest"
        sku                         = "premium"
      + workspace_id                = (known after apply)
      + workspace_url               = (known after apply)

      + custom_parameters {
          + no_public_ip        = false # forces replacement
          + private_subnet_name = "brickandmorty-private" # forces replacement
          + public_subnet_name  = "brickandmorty-public" # forces replacement
          + virtual_network_id  = ".../vnet/id" # forces replacement
        }
    }
```

### Expected Behaviour
The resource "azurerm_databricks_workspace" should only be created once.

### Actual Behaviour

The resource is destroyed and rebuilt every time even though no changes have been made.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by base-mhen** [comment]
I am experiencing the same issue with any combination of below versions:

terraform 0.14.5, 0.14.8, and 0.15.0-beta1
azurerm 2.46, and 2.50.0
databrickslabs/databricks v0.3.1

**Comment by jeromewaibel** [comment]
After some more investigation on this issue I came across the main cause for my problem. It may be that this is not a bug in the provider and this issue can be closed.

The documentation for azurerm_databricks_workspace says:

> Databricks requires that a network security group is associated with public and private subnets when virtual_network_id is set.

What I did in my code was that I created the private and public subnets and the NSG in the same terraform code as the databricks workspace. But the databricks workspace only has a dependency on the subnet ids. Thus the module started creating the workspace right after the subnets were created and did not wait for the NSG association to finish.
As the workspace resource itself is adding rules the NSG, which may not yet associated to the subnets, the whole process derailed somewhere.

Workaround/Solution: Explicitly define the dependency from the workspace to the NSG association so it is finished before the workspace is created:

```
resource "azurerm_databricks_workspace" "this" {
  name                        = "brickandmorty"

  [...]

  # wait for network_security_group_association to finish
  depends_on = [azurerm_subnet_network_security_group_association.private, azurerm_subnet_network_security_group_association.public]
}
```

**Comment by bitsofinfo** [comment]
@jeromewaibel wonder if this is cause of my issue? https://github.com/terraform-providers/terraform-provider-azurerm/issues/11158

**Comment by jwshive** [comment]
I have just run into this today mocking up some databricks additions to an environment.

In my case, the networking was done well in advance, but I am getting the exact same issue with databricks being recreated each time an apply is run on the workspace code. I feel like this is an actual issue.

**Comment by WodansSon** [comment]
This is currently "by design" per the RP's service team. Unfortunately, many of the fields are definable during the initial creation of the resource only. So to satisfy this requirement of the RP almost all fields in the Terraform resource are force new.

**Comment by calannap** [comment]
I had the same problem, even without populating the custom_parameters block. I added foce disabled any changes made to the resource by adding

```
  lifecycle {
    ignore_changes = all
  }
```

to the resource. This leads to a correct terraform plan/apply with no scheduled changes or workspace replacement.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
