### ISSUE TITLE
azurerm_kubernetes_cluster Changing property 'agentPoolProfile.enableNodePublicIP' is not allowed when changing node

### ISSUE THREAD

**Issue by flmmartins** [hashicorp/terraform-provider-azurerm#10951]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4

Provider Version: 

2.44.0
2.50.0
2.51.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "this" {
  name                = "${var.cluster_name}-aks"
  location            = var.resource_group["location"]
  resource_group_name = var.resource_group["name"]
  dns_prefix          = "${var.cluster_name}-aks"

  default_node_pool {
    name                = var.default_node_spec.name
    vm_size             = var.default_node_spec.vm_size
    os_disk_size_gb     = var.default_node_spec.os_disk_size_gb
    node_count          = var.default_node_spec.node_count
    type                = "VirtualMachineScaleSets"
    availability_zones  = var.default_node_spec.az
    enable_auto_scaling = var.default_node_spec.enable_auto_scaling
    min_count           = var.default_node_spec.min_count
    max_count           = var.default_node_spec.max_count

    tags        = merge(var.tags, local.module_tags)
    node_labels = merge(var.tags, local.module_tags) 

    # Required for advanced networking
    vnet_subnet_id = azurerm_subnet.this.id
  }

  lifecycle {
    ignore_changes = [ default_node_pool.0.node_labels, default_node_pool.0.tags ]
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    azure_active_directory {
      managed = true
      admin_group_object_ids = var.cluster_admins_object_id
    }
    enabled = true
  }

  api_server_authorized_ip_ranges = var.api_server_whitelisted_ips

  addon_profile {
    kube_dashboard {
      enabled = true
    }

    http_application_routing {
      enabled = false
    }
    azure_policy {
      enabled = true
    }

  }

  network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "standard"
    network_policy    = "calico"
  }
  
  tags = merge(var.tags, local.module_tags)
}

```

### Debug Output

Terraform change output:

```bash
 # module.dev_cluster.azurerm_kubernetes_cluster.this will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "this" {
        id                              = "/subscriptions/xxxxx/dev-rg/providers/Microsoft.ContainerService/managedClusters/dev-aks"
        name                            = "dev-aks"
        tags                            = {
            "createdBy"                = "terraform"
            "environment"              = "dev"
            "part_of"                  = "dev_cluster"
            "terraform-module_name"    = "azure_kubernetes_svc"
            "terraform-module_version" = "2.1.0"
        }
        # (18 unchanged attributes hidden)



      ~ default_node_pool {
          ~ max_count             = 3 -> 4
            name                  = "defone"
            tags                  = {
                "createdBy"                = "terraform"
                "environment"              = "dev"
                "part_of"                  = "dev_cluster"
                "terraform-module_name"    = "azure_kubernetes_svc"
                "terraform-module_version" = "2.0.3"
            }
            # (14 unchanged attributes hidden)
        }

        # (6 unchanged blocks hidden)
    }

```
### Error

updating Default Node Pool "dev-aks" (Resource Group "dev-rg"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing property 'agentPoolProfile.enableNodePublicIP' is not allowed." Target="agentPoolProfile.enableNodePublicIP"

  on ../../tfmodules/azure_kubernetes_svc/main.tf line 20, in resource "azurerm_kubernetes_cluster" "this":
  20: resource "azurerm_kubernetes_cluster" "this" {

### Expected Behaviour

I wanted to change max_count in my node pool but for some reason I got the error above

### Actual Behaviour

I tried to change the max_count to 4 and the output above happened

When debugging this error I saw that although I changed something in the max_count of the node the error mentions somethings about the public ip.

I took a look in the terraform state and the default value of enable_node_public_ip is set to false which is what I want.

If I do:

```bash
az aks show -n dev-aks -g dev-rg
```

I can see that somehow my nodes have the following:

```bash
    "enableNodePublicIp": null,
```

I am suspecting that happened when we need to make a change in the nodepool and that was done manually. Maybe somehow it set the value to null.

Fact is that I think the provider is trying to set this null value to false and therefore the Azure API is giving this error above. 

### Steps to Reproduce

1. Making some manual changes and run terraform import on the nodes
2. `terraform apply` when something inside the node specification changes

You will see the error

### References

* #0000

**Comment by Karadiavinay** [comment]
Unfortunately, my code still using azurerm version 1.36.1, in which also "enable_node_public_ip" set to **null** as shown below: 
![image](https://user-images.githubusercontent.com/13751440/111740294-80b38a80-88aa-11eb-8688-d39efb637ecc.png)

I have a task to upgrade azurerm version without **rebuild** . I upgrade the version to 1.37.0, since its the version where azure provide introduced default_node_pool to tfstate the first time and then only one can move to upstream versions.

Version 1.37.0 had started support for the variable but as type **Boolean**. Since it's an optional argument, I haven't used it in code. During Terraform Plan, I found that the new version is setting this variable to "**false**", which is expected behavior as per the change. BUT not accepted as its earlier value was **"null"**
![image](https://user-images.githubusercontent.com/13751440/111740108-2d413c80-88aa-11eb-8322-b9f513b0860a.png)

**Comment by stephybun** [comment]
Hi @flmmartins 

Thanks for raising this issue and apologies for the delay in response. I attempted reproducing the error described using the provider version 2.50.0, unfortunately without luck. I created a cluster using the config that was provided then increased the `max_count` and was able to apply this successfully. In addition I had a poke around in the portal to see whether there were any manual changes that I could make to the node pool relating to `enabledNodePublicIP` but this property does not seem configurable after the creation of the cluster through the portal.

Would you be able to reproduce this with the latest version of the provider?

**Comment by stephybun** [comment]
Closing since we haven't heard back, if this is still an issue and you can provide some additional info do let us know and we can reopen this!
