### ISSUE TITLE
Multiple frontend ip configuration block using dynamic block

### ISSUE THREAD

**Issue by r2rajan** [hashicorp/terraform-provider-azurerm#10984]
I am trying to create a azure external load balancer with multiple frontend ip configuration. Terraform produced an inconsistent plan and tries to create only 1 frontend_ip_configuration block instead of matching the count. Terraform throws out an error

Error: Provider produced inconsistent final plan

When expanding the plan for module.fwlb.azurerm_lb.externallb to include new values learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.frontend_ip_configuration: block count changed from 1 to 2.
This is a bug in the provider, which should be reported in the provider's own issue tracker.
##[error]Terraform command 'apply' failed with exit code '1'.:  Provider produced inconsistent final plan ##[error]
This is a bug in the provider, which should be reported in the provider's own issue tracker.

Here is my code

variable name {
  type = string
  default = mypip
}

resource "azurerm_public_ip" "untrustpip" {
  count                = 2
  name                = "pip-${count.index}"
  location            = "westus2"
  resource_group_name = "myRG"
  allocation_method   = "Static"
  sku                 = Standard
}
# Compose a Map variable from the list created by public ip

locals {
  pip = { for entry in concat(azurerm_public_ip.untrustpip.*.id) :  "${var.name}${index(concat(azurerm_public_ip.untrustpip.*.id), entry)}" => entry }
}

# Create Load Balancer
resource "azurerm_lb" "externallb" {
  name                             = "externalLB"
  location                         = "westus2"
  resource_group_name = "myRG"
  sku                                = Standard

  dynamic  "frontend_ip_configuration" {
  for_each = local.pip
    content { 
            name                                      = frontend_ip_configuration.key
            public_ip_address_id            = frontend_ip_configuration.value
    }
  }
}

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
