### ISSUE TITLE
azurerm_log_analytics_saved_search string function_parameters not correct format accepted

### ISSUE THREAD

**Issue by pedrinimm** [hashicorp/terraform-provider-azurerm#10989]
### Terraform (and AzureRM Provider) Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.46.0

Your version of Terraform is out of date! The latest version
is 0.14.8. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_log_analytics_saved_search`

### Terraform Configuration Files

```terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.46.0"
    }
  }
}

provider "azurerm" {
  tenant_id       = "xxx"
  subscription_id = "xxxx"
  features {}
}

resource "azurerm_log_analytics_saved_search" "entity_function" {
    name = "getEntityList"
    log_analytics_workspace_id = "/subscriptions/xxxxx/resourceGroups/xxxx/providers/Microsoft.OperationalInsights/workspaces/team-test-workspace"
    category     = "Function"
    display_name = "getEntityList"
    query        = <<EOT
              print typeArg
                EOT
    function_alias = "getEntityList"
    function_parameters = ["typeArg:string=mail","tagsArg:string=dc"]
}
```

### Debug Output

Error: invalid value for function_parameters.1 (Log Analytics Saved Search Function Parameters must be in the following format: param-name1:type1=default_value1)

  on config.tf line 16, in resource "azurerm_log_analytics_saved_search" "entity_function":
  16: resource "azurerm_log_analytics_saved_search" "entity_function" {

### Expected Behaviour

Terraform should accept variables of the following kind when string
    function_parameters = ["typeArg:string=\"mail\"","tagsArg:string=\"dc\""]
or 
    function_parameters = ["typeArg:string='mail'","tagsArg:string='dc'"]

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_log_analytics_saved_search.entity_function: Creating...
azurerm_log_analytics_saved_search.entity_function: Creation complete after 2s [id=subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/team-test-workspace/savedSearches/getentitylist]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behaviour

Error: invalid value for function_parameters.1 (Log Analytics Saved Search Function Parameters must be in the following format: param-name1:type1=default_value1)

  on config.tf line 16, in resource "azurerm_log_analytics_saved_search" "entity_function":
  16: resource "azurerm_log_analytics_saved_search" "entity_function" {

### Steps to Reproduce

1. `terraform apply`

**Comment by nickjacobsen** [comment]
If you want to have the format "typeArg:string="mail""

You'll need to escape the double quote (") around "mail" so like this
"typeArg:string=\"mail\""

Single quotes: "typeArg:string='mail'" also work

**Comment by pedrinimm** [comment]
That's the first thing I tried and it was not working then I looked at the validation function which enforces this regex:
`^[a-zA-Z0-9!-_]*:[a-zA-Z0-9!_-]+=[a-zA-Z0-9!_-]+`
and there if no way this regex allows single or double quotes

**Comment by nickjacobsen** [comment]
Apologies; I tried it the other day and it worked, now it's not.  I was probably using my build, where I am modifying that regex to accept different parameters definitions to more accurately show what is possibly.

The problem is including tabular definitions and then validating them.

To validate it correctly is convoluted and it needs a lot of work to do it properly.

But you're right it doesn't work and it should.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
