### ISSUE TITLE
Azure CDN Endpoint geo_filters can no longer be removed

### ISSUE THREAD

**Issue by glennsarti** [hashicorp/terraform-provider-azurerm#10988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
azure_rm_provider v2.51.0

### Affected Resource(s)

* `azurerm_cdn_endpoint`

### Terraform Configuration Files
Only partial content provided

Initially deploy with:
```
resource "azurerm_cdn_endpoint" "example" {
  ...
geo_filter  {
  action = "Allow"
  relative_path = "/"
  country_codes = ["AU"]
 }
...
 }
```

This succesfully deploys a CDN with geo-blocking.  Modifying the terraform file to remove the geo_filter

```
resource "azurerm_cdn_endpoint" "example" {
  ...
 }
```

### Expected Behaviour

The  geo_filter should be removed

### Actual Behaviour

Terrform apply completes with success but the filter is not modified in Azure

### Steps to Reproduce

1. `terraform apply` with a `geo_filter` block defined
2. `terraform apply` without a `geo_filter` block defined

*Note* using version 2.41.0 of the provider does NOT have this problem and behaves as expected.

I suspect https://github.com/terraform-providers/terraform-provider-azurerm/pull/9902 has broken the deletion due to the statement

> Assigning the parameters EndpointProperties.ContentTypesToCompress, EndpointProperties.GeoFilters only when values are set for content_types_to_compress, geo_filter.

### References

https://github.com/terraform-providers/terraform-provider-azurerm/pull/9902

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
