### ISSUE TITLE
There is no reason for "azurerm_storage_share" "quota" to default to 5120

### ISSUE THREAD

**Issue by thomasbeauvais** [hashicorp/terraform-provider-azurerm#10998]
### Terraform (and AzureRM Provider) Version

Terraform v0.13.3

### Affected Resource(s)

* `azurerm_storage_account`
* `azurerm_storage_share `

### Terraform Configuration Files

Really, this isn't a bug though it is important!

For Azure, the Storage Account, "azurerm_storage_account" has different "tiers" such as Standard and Premium. The default is Standard which is "pay as you go" and generally usable for most solutions. 

The problem comes when you need the "Premium" tier for specific reasons. 

The pricing scheme DRASTICALLY changes from Standard to Premium. With Premium the "quota" no longer becomes a nearly arbitrary upper limit but rather a contract/reservation! Simple changing from Standard to Premium for the additional features will result in MASSIVE overcharges with the default if you don't read the Azure documentation!

This will cause about $100 per share per day! Rising from just pennies if you aren't using much in the Standard. We racked up nearly $20,000 in one month since we had 3x environments and 10x shares per environment yet had NEXT TO NO USAGE (less than 100mb). Azure SHOULD have a limit in here as well, we are working with support to address this from the operational side.

There is almost no reason that the quota needs to be 5 TB. If a cloud application needs a 5 TB (or more) share, then they can figure out what they need a manually set it as needed.  

### Possible Solution
Set the default to 100 GB (which is the minimum of the Premium package) to have people avoid this mistake in the future. If they need more than 100 GB, then they should really figure that out and map their scale their application up. Default users should not have to worry about SCALING DOWN for a simple change to the pricing tier.

Add a note to the documentation that Premium FileStorage is really experience, link to the Azure pricing calculation, and recommend that they choose the smallest they need such as a minimum of 100 GB. 

Remove the default completely forcing people to look into the documentation.

Create a new resource "azurerm_premium_storage_share" which sane default values.

### Conclusion
I know this sounds like an arbitrary change, though I know that this has might unforeseen consequences. I just believe that the default case should balance between the ease of scale and the pocketbook. 

I am eager to start a conversation on this topic as it has caused a lot of headaches and back-and-forth with Azure Support.

Thanks for your help, insights and interest.

**Comment by katbyte** [comment]
Hey @thomasbeauvais,

thank you for opening this issue, after some internal discussion we've decided to remove the default and make the `quota` property as you suggested and make it required to encourage users to think about, and determine what their storage needs are rather then rely on defaults. this will be closed by 15982 and released tomorrow in 3.0!
