### ISSUE TITLE
can't use log analytics workspace in a different subscription for azure policy also can't assign managed identity as contributor

### ISSUE THREAD

**Issue by rogerm-chen** [hashicorp/terraform-provider-azurerm#11031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.7
azurerm v2.51.0

### Affected Resource(s)

azurerm_policy_assignment
azurerm_role_assignment

### Terraform Configuration Files

```
resource "azurerm_policy_assignment" "Enable_Azure_Monitor_for_VMs" {
  
  name                 = "Enable Azure Monitor for VMs"
  scope                = data.azurerm_subscription.current.id
  policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/55f3eceb-5573-4f18-9695-226972c6d74a"
  description          = "Enable Azure Monitor for the virtual machines (VMs) in the specified scope (management group, subscription or resource group). Takes Log Analytics workspace as parameter."
  display_name         = "Enable Azure Monitor for VMs"
  location             = var.location
  metadata = jsonencode(
    {
      "category" : "General"
  })

  parameters = jsonencode({
    "logAnalytics_1" : {
      "value" : var.log_analytics_workspace_ID
    }
  })

  identity {
    type = "SystemAssigned"
  }

}

resource "azurerm_role_assignment" "vm_policy_msi_assignment" {
  scope                = azurerm_policy_assignment.Enable_Azure_Monitor_for_VMs.scope
  role_definition_name = "Contributor"
  principal_id         = azurerm_policy_assignment.Enable_Azure_Monitor_for_VMs.identity[0].principal_id
}
```

### Debug Output
https://gist.github.com/theasphaltworld/fea7bf141de85e367ff21f4172ebdf46

### Expected Behaviour

log analytics workspace in a different subscription should be able to use
policy managed identity should be set as contributor

### Actual Behaviour
log analytics workspace in a different subscription can not be set, no error output, but field is blank. However the workspace in the same subscription is fine.

Policy managed identity has not been set to contributor

### Steps to Reproduce
terraform plan, terraform apply where variable log_analytics_workspace_ID has been set to workspace ID in a different subscription

i have set my permission with user access management role

1. `terraform apply`

### References

* #0000

**Comment by vg22** [comment]
@katbyte I am also facing the issue. Is there a plan to address this in the near future?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
