### ISSUE TITLE
Add support for assigning a WAF policy in azurerm_application_gateway

### ISSUE THREAD

**Issue by janegilring** [hashicorp/terraform-provider-azurerm#11039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }

  waf_configuration {
    waf_policy_id = azurerm_web_application_firewall_policy.example.id  // <--- Suggestion
  }

}
```

We started out by defining a WAF policy inside the azurerm_application_gateway resource block. Then we moved to using WAF policies. After doing so, even after removing the waf_configuration block, we get this error when trying to run terraform apply:
```
Error: creating/updating Application Gateway: (Name "dsp-external-agw" / Resource Group "dsp-rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ApplicationGatewayFirewallPolicyCannotBeRemoved" Message="Firewall policy /subscriptions/12342f07-37de-408e-9bfc-cb2b9a923e81/resourceGroups/dsp-rg/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/dsp-wafpolicy cannot be removed from Application Gateway, changing from one firewall policy to another is permitted." Details=[]
```
Hence, if support for associating the App Gateway to a WAF policy resource ID is added, it would likely solve this problem as well.

**Comment by w3bward** [comment]
Assigning an independent WAF policy resource is possible using the [firewall_policy_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#firewall_policy_id) argument.

Perhaps setting that and removing the waf_configuration block in the same apply will allow you to proceed since it seems to indicate that you can't remove the WAF policy unless you provide a new one?

**Comment by janegilring** [comment]
We ended up re-creating the App Gateway as a workaround, so we're unable to test now unfortunately.

Since the original issue seems to be resolved I will go ahead and close this one

>Assigning an independent WAF policy resource is possible using the firewall_policy_id argument.
