### ISSUE TITLE
support permanent deletion of workspaces with the permanently_delete_on_destroy feature flag (#10235)

### ISSUE THREAD

**Issue by stevensoave** [hashicorp/terraform-provider-azurerm#11052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version = 0.13.5
AzureRM Provider Version = 2.50.0 (March 05, 2021) - Also tested 2.52.0

### Affected Resource(s)

* `azurerm_log_analytics_workspace`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/loganalytics/log_analytics_workspace_resource.go

Missing attribute scheme on top section of the file for "permanently_delete_on_destroy"

This is supported from the below function in that go file:
func resourceLogAnalyticsWorkspaceDelete

Not able to use in TF:

### Steps to Reproduce

```hcl
resource "azurerm_log_analytics_workspace" "la_workspace" {
  name                    = format(
                            "la-%s-%s-%s",
                            var.naming_convention["prj"],
                            var.naming_convention["reg"],
                            var.naming_convention["env"],
                          )
  location                = lookup(var.log_analytics, "workspace_location", var.location)
  resource_group_name     = var.resource_group_name
  sku                     = lookup(var.log_analytics, "sku", "PerNode")
  retention_in_days       = var.retention
  tags                    = var.tags
  permanently_delete_on_destroy = false
```

Error: Unsupported argument

  on .terraform/modules/log_analytics/main.tf line 13, in resource "azurerm_log_analytics_workspace" "la_workspace":
  13:   permanent_delete = false

An argument named "permanent_delete" is not expected here.

1. `terraform apply`

### References

* #10235
* https://github.com/terraform-providers/terraform-provider-azurerm/pull/10235

**Comment by tombuildsstuff** [comment]
This should be the default behaviour and disableable via the Features block

**Comment by tombuildsstuff** [comment]
This feature's controlable via the `features` block within the `provider` block: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#permanently_delete_on_destroy
