### ISSUE TITLE
when adding key_vault_credential and importing

### ISSUE THREAD

**Issue by knighteagle789** [hashicorp/terraform-provider-azurerm#11053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform v0.14.8
  * provider registry.terraform.io/hashicorp/azuread v1.4.0
  * provider registry.terraform.io/hashicorp/azurerm v2.51.0

### Affected Resource(s)

* `azurerm_mssql_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_virtual_machine" "sqlvm" {
  for_each                         = var.dbservers
  virtual_machine_id               = azurerm_windows_virtual_machine.vm[each.key].id
  sql_license_type                 = "AHUB"
  sql_connectivity_port            = 1433
  sql_connectivity_type            = "PRIVATE"
  sql_connectivity_update_password = var.admin_password
  sql_connectivity_update_username = var.admin_username
  r_services_enabled               = false

  key_vault_credential {
    key_vault_url            = "https://kv-ssbshared-production.vault.azure.net/"
    service_principal_name   = data.azuread_service_principal.kvSP.application_id
    service_principal_secret = var.kvuserSecret
    name                     = "kv-ssbshared-production:${azurerm_windows_virtual_machine.vm[each.key].name}kvCred"
  }

  tags = {
    "ci-client"      = var.client
    "ci-environment" = var.environment
    "ci-product"     = "Data Management"
  }
  timeouts {
    create = "240m"
  }

  depends_on = [
    azurerm_virtual_machine_data_disk_attachment.ddattach,
    azurerm_virtual_machine_data_disk_attachment.ldattach,
    azurerm_virtual_machine_data_disk_attachment.fdattach,
    azurerm_virtual_machine_data_disk_attachment.tdattach
  ]
}

```

### Debug Output

https://gist.github.com/knighteagle789/587b31da47209f2ec17bf2e4b8481a6a

### Expected Behaviour

When you run the plan/apply with a key vault in place, it should not force a destroy and build of the SQL VM.  This does not happen when you try this in the portal.

### Actual Behaviour

A full destroy and add occurs

### Steps to Reproduce

1. `terraform apply`

**Comment by knighteagle789** [comment]
Has this been looked at yet?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
