### ISSUE TITLE
Support for Purging Soft-Deleted API Management

### ISSUE THREAD

**Issue by opticyclic** [hashicorp/terraform-provider-azurerm#11061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The API Management is now soft-deleted by default. 
https://docs.microsoft.com/en-us/azure/api-management/soft-delete

If you do `terraform destroy` it will use this soft delete and you will be unable to create it again for 90 days, which is obviously a problem when you need to recreate infrastructure during development.

`Error: creating/updating API Management Service "dev-apim" (Resource Group "dev_rg"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceAlreadyExistsInSoftDeletedState" Message="Api service dev-apim was soft-deleted. In order to create the new service with the same name, you have to either undelete the service or purge it"`

It is possible to purge these soft-deleted items with the rest api:
https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/deletedservices/purge

It would be good if there was a way to call this delete API as part of `terraform destroy`

* #0000

**Comment by nexxai** [comment]
The purge action is supported in version 2020-12-01 of the Azure SDK for Go: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v54.2.0+incompatible/services/apimanagement/mgmt/2020-12-01/apimanagement#DeletedServicesClient.Purge

**Comment by yupwei68** [comment]
I'm working on this. But currently there is some upstream service problems in api mgmt purging are in fixing and releasing.
I'll raise PR for this once the fix is released.

**Comment by wasfree** [comment]
@yupwei68 is there a public github issue for this upstream problem? Missing purge soft-deleted option is blocking us from upgrade terraform azurerm version.
