### ISSUE TITLE
Support for setting scale_in_policy for underlying scaleset in AKS clusters

### ISSUE THREAD

**Issue by stigok** [hashicorp/terraform-provider-azurerm#11068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We want to be able to control the `azurerm_linux_virtual_machine_scale_set.scale_in_policy` for both `azurerm_kubernetes_cluster.default_node_pool` and `azurerm_kubernetes_cluster_node_pool`.

When using `upgrade_settings.max_surge` now, new nodes spawn to offload the upgrading node(s), but they are deprovisioned again when the old node is updated. This gives us an additional node outage when only one is strictly needed.

In our case, it makes more sense to use `OldestVM` for the `azurerm_linux_virtual_machine_scale_set.scale_in_policy`. I imagine exposing this variable with the existing defaults set will still maintain backwards compatability.

### New or Affected Resource(s)

- `azurerm_kubernetes_cluster.default_node_pool`
- `azurerm_kubernetes_cluster_node_pool`

**Comment by stephybun** [comment]
Hi @stigok,

Thanks for raising this issue. The AKS API currently doesn't support control of the `scale_in_policy` of the underlying VM Scale Set that's used for the node pool and as such we won't be able to support this currently. What I would suggest is opening a feature request over on [Azure/AKS](https://github.com/Azure/AKS). Once that functionality is exposed by the AKS API and added to the Swagger spec we can take another look at supporting this!

**Comment by stigok** [comment]
Thanks for the response. Let's see if this is possible :)

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
