### ISSUE TITLE
Cannot terraform destroy without first removing storage firewall

### ISSUE THREAD

**Issue by lazarillo** [hashicorp/terraform-provider-azurerm#11071]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Azure Storage Gen 2, associated with Azure Machine Learning Workspace, with a firewall enabled.

* `azurerm_machine_learning_workspace`

I do not know that it only affects storage on AML workspaces, but we do have other storage accounts and they do not have any trouble.

### Terraform Configuration Files

We have a large set of configurations, but below is the code relevant to this issue.

```hcl
resource "azurerm_machine_learning_workspace" "amlws" {
  name                    = var.resource_name
  resource_group_name     = data.azurerm_resource_group.rg.name
  location                = data.azurerm_resource_group.rg.location
  application_insights_id = var.application_insights_id
  key_vault_id            = var.key_vault_id
  storage_account_id      = var.storage_account_id

  identity {
    type = var.identity_type
  }

  container_registry_id = var.container_registry_id
  description           = var.description
  sku_name = var.sku_name
  tags     = var.tags
}
```

### Debug Output

Error: Error retrieving Container "defaultdatacontainer" (Account "<redacted>" / Resource Group "<redacted>"): containers.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation."

### Expected Behaviour

Terraform destroy should work, even with a firewall established.  At least, that it what I understood from resolution of issue[3925](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3925).

### Actual Behaviour

Before turning off the firewall, I receive the error above.  After turning it off, I am able to destroy.

### Steps to Reproduce

1. `terraform destroy`

### References

issue[3925](https://github.com/terraform-providers/terraform-provider-azurerm/issues/3925).

**Comment by favoretti** [comment]
Hi, thank you for reporting this. I think the 403 in this case is more related to where and with which credentials you're running terraform alongside permissions terraform SPN has on that storage account/container. It's not uncommon to create a resource with terraform and then lock it down to an extent that SPN that terraform uses can not do anything with it anymore. Provider can not go around access constrains you put on created objects, so you gotta take those into account. :)

**Comment by nadworny** [comment]
I'm getting the same error. This happens as soon as I enable firewall rules. I can create the storage without a problem, but destroying doesn't work unless I whitelist my IP. This behaviour is different for example for CosmosDB or PostgreSQL resources, there after enabling the firewall, I'm still able to destroy, even without whitelisting my IP. 

Not sure if I should open a ticket in azure portal for that? In case it's a Microsoft issue, what would be the best way to progress? Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. Time has passed and there have been many changes to the storage service, so for now I am going to close this issue. If this is still an issue with the 4.x version of the provider please do let us know by opening a new issue, thanks!
