### ISSUE TITLE
Plan doesn't fail when specifying a nonexistent VM source image

### ISSUE THREAD

**Issue by omkensey** [hashicorp/terraform-provider-azurerm#11078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
```

### Affected Resource(s)

* `azurerm_linux_virtual_machine`

### Expected Behaviour

A plan that specifies a non-existent VM image should fail.

### Actual Behaviour

When I create a VM spec with a non-existent image such as the following:

```
      source_image_reference {
          offer     = "flatcar_container_linux"
          publisher = "kinvolk"
          sku       = "stable"
          version   = "this_version_does_not_exist"
      }
```
...the plan succeeds.  However, if I then apply, the apply fails because the specified image does not exist.  The plan instead should have failed because the image is checked and is not available.

### Steps to Reproduce

1. Create TF code that will create a VM with a nonexistent Azure VM image.  (Sample code that should work for this attached
[tf-sample-code.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/6184827/tf-sample-code.zip) -- set the variable azure_offer_version to something obviously bogus)
2. `terraform plan`
3. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
