### ISSUE TITLE
azurerm_kubernetes_cluster_node_pool wants to be recreated because kubernetes_cluster_id changes from resourcegroups -> resourceGroups

### ISSUE THREAD

**Issue by mauriciodou** [hashicorp/terraform-provider-azurerm#11075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.6
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "application" {
  count                 = var.multi_np_flag ? 1 : 0
  name                  = "application"
  mode                  = "User"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.cluster.id # This id is forcing the recreation
  node_count            = local.node_count
  min_count             = local.min_count
  max_count             = var.max_count
  vm_size               = var.vm_size
  os_disk_size_gb       = var.os_disk_size_gb
  vnet_subnet_id        = local.subnet_id
  enable_auto_scaling   = var.enable_auto_scaling
  availability_zones    = var.availability_zones
  orchestrator_version  = local.kubernetes_version
  tags                  = var.standard_tags
  node_labels           = { "kroger/node-type" : "application" }
  lifecycle {
    ignore_changes = [
      node_count
    ]
  }
}
```

### Expected Behaviour

Terraform should not be recreating the node pool or provide a migration for the changed id. 

### Actual Behaviour

The state has:
kubernetes_cluster_id = "/subscriptions/xxx/resourcegroups/rg6744galactusk8dev/providers/Microsoft.ContainerService/managedClusters/galactus-cluster-dev-aks"

But has changed to:
kubernetes_cluster_id = "/subscriptions/xxx/resourceGroups/rg6744galactusk8dev/providers/Microsoft.ContainerService/managedClusters/galactus-cluster-dev-aks"

Note the resourcegroups -> resourceGroups change. Perhaps this was updated in a version?

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by stephybun** [comment]
Hi @mauriciodou, thanks for raising this issue. Since this was re-raised in #13919 where there is an ongoing discussion I am going to close this issue. Please subscribe to #13919 for updates.

Thanks!
