### ISSUE TITLE
As of 2.47 some data sources are lowercasing causing forced replacement

### ISSUE THREAD

**Issue by williamayerst** [hashicorp/terraform-provider-azurerm#11072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Working as expected:

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.47.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

Terraform force-replacing resources:

Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

Various - specifically in this case:

* `azurerm_subnet`

However I have noticed this also with location i.e. NorthEurope > northeurope for `azurerm_servicebus_namespace` and anecdotal reports of it on other resources.

### Terraform Configuration Files

Data Resource:
```hcl
data "azurerm_virtual_network" "k8s" {
  name                = var.browse_zone_core_aks_vnet_name
  resource_group_name = var.browse_zone_core_aks_vnet_rg
}

data "azurerm_subnet" "k8s" {
  name                 = var.browse_zone_core_aks_subnet_name
  virtual_network_name = var.browse_zone_core_aks_vnet_name
  resource_group_name  = var.browse_zone_core_aks_vnet_rg
}
```

Consuming Resource:
```hcl
module "aks_cluster" {
  ...
  aks_k8s_subnet_id           = data.azurerm_subnet.k8s.id
  ...
}
```

### Expected Behaviour

No change

### Actual Behaviour

Subnet name is capitalised 'Account00-AKS' in both Azure and the State file. When using provider version >2.47 the data resource is converting the subnet name to lowercase, resulting in a forced replacement:

```hcl
          ~ vnet_subnet_id               = "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/virtualNetworks/zzz/subnets/Account00-AKS" -> "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/virtualNetworks/zzz/subnets/account00-AKS" # forces replacement
```

To confirm the object output from AZCLI is as follows:

```json
{
"id": "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/virtualNetworks/zzz/subnets/Account00-AKS"
}
```

And in the TF State file:

```json
"default_node_pool": [
              {
                "vnet_subnet_id": "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/virtualNetworks/zzz/subnets/Account00-AKS"
              }
```

### Steps to Reproduce

* Set a subnet up with capitalised naming.
* Reference it with a data resource.
* Consume that data resource in a module.
* Forced replacement occurs due to the lowercasing of the data resource output for the subnet.

### References

* #0000

**Comment by lonegunmanb** [comment]
Hello @williamayerst , I've tried to reproduce this issue by the following code:

```hcl
resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = "zjhe-f11072"
}

resource "azurerm_virtual_network" "vnet" {
  address_space       = ["10.0.0.0/16"]
  location            = "eastus"
  name                = "zjhe-f11072"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "zjhe-f11072"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes = ["10.0.0.0/24"]
}

variable "subnet_name" {}

data "azurerm_subnet" "subnet" {
  depends_on = [azurerm_subnet.subnet]
  name                 = var.subnet_name
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
}

output "id" {
  value = data.azurerm_subnet.subnet.id
}
```

After creation of a subnet with lower case name, I query a subnet by a datasource which name is from input variable.

If I provide a lower case name:

```powershell
> terraform apply -auto-approve -var subnet_name=zjhe-f11072
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

id = "/subscriptions/85b3dbca-5974-4067-9669-67a141095a76/resourceGroups/zjhe-f11072/providers/Microsoft.Network/virtualNetworks/zjhe-f11072/subnets/zjhe-f11072"
```
The subnet id would be lower case, but If I provide an upper case name as variable:

```powershell
> terraform apply -auto-approve -var subnet_name=Zjhe-f11072
...
Outputs:

id = "/subscriptions/85b3dbca-5974-4067-9669-67a141095a76/resourceGroups/zjhe-f11072/providers/Microsoft.Network/virtualNetworks/zjhe-f11072/subnets/Zjhe-f11072"
```

The subnet id would be upper case.

Would you please check the variable you've used? Thanks!

**Comment by williamayerst** [comment]
Thank you @lonegunmanb - I'll check that!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
