### ISSUE TITLE
azurerm api_management_version_set fails with message "ID was missing the `apiVersionSets` element"

### ISSUE THREAD

**Issue by cranarma** [hashicorp/terraform-provider-azurerm#11093]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform v0.13.6
azurerm v2.52.0

### Affected Resource(s)

* `azurerm_api_management_api_version_set`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "api_management" {
  name                = "xxxx-api-${var.environment_tag}"
  location            = var.location
  resource_group_name = var.rg_name
  publisher_name      = "xxxx"
  publisher_email     = "support@xxxx.com"

  sku_name = var.sku_name

  sign_in {
    enabled = true
  }

  hostname_configuration {
    proxy {
      host_name = var.custom_domain.api_hostname
      certificate = var.custom_domain.certificate
    }
    portal {
      host_name = var.custom_domain.portal_hostname
      certificate = var.custom_domain.certificate
    }
  }

  policy {
    xml_content = <<XML
<policies>
    <inbound />
    <backend>
        <forward-request />
    </backend>
    <outbound />
    <on-error />
</policies>
XML
  }

  tags = {
    environment = var.environment_tag
    product     = var.product_name
  }
}

resource "azurerm_api_management_api" "api_v1" {
  name                = "auth-api-v1-0"
  resource_group_name = var.rg_name
  api_management_name = var.api_management_name
  version             = "v1.0"
  version_set_id      = azurerm_api_management_api_version_set.version_set.id
  revision            = "1"
  display_name        = "Authentication"
  path                = "api/auth"
  protocols           = ["https"]
  service_url         = "https://xxxxxxxx.b2clogin.com" //internal uri
}

resource "azurerm_api_management_api_version_set" "version_set" {
  name                = "authentication-api"
  resource_group_name = var.rg_name
  api_management_name = var.api_management_name
  display_name        = "Authentication"
  versioning_scheme   = "Query"
  version_query_name  = "version"
}

resource "azurerm_api_management_api_policy" "api_v1_policy" {
  api_name            = azurerm_api_management_api.api_v1.name
  api_management_name = var.api_management_name
  resource_group_name = var.rg_name

  xml_content = <<XML
<policies>
    <inbound>
        <base />
    </inbound>
    <backend>
        <base />
    </backend>
    <outbound>
        <base />
    </outbound>
    <on-error>
        <base />
    </on-error>
</policies>
XML
}
```

### Expected Behaviour
running `terraform plan` executes correctly.

### Actual Behaviour
running `terraform plan` fails with error message:
**Error: ID was missing the `apiVersionSets` element**

I get 5 of these error messages, and I have defined 5 `azurerm_api_management_api_version_set` resources in my Terraform config, each one referencing a different `azurerm_api_management_api`, so I suspect the error is linked to those blocks.

I started getting these errors when upgrading `azurerm` from v1.42.0 to v2.52.0. 
It happens on Terraform versions 0.12.x and 0.13.x.

### Steps to Reproduce

1. `terraform init -reconfigure`
1. `terraform plan`

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api_version_set

* #0000

**Comment by chrisbloe** [comment]
Maybe https://github.com/hashicorp/terraform-provider-azurerm/issues/6609#issuecomment-629551582 is the answer...

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
