### ISSUE TITLE
azurerm_automation_module - module_link uri in Azure Storage blob - StatusCode=400 error doesn't create module

### ISSUE THREAD

**Issue by ekUSA** [hashicorp/terraform-provider-azurerm#11096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0

### Affected Resource(s)

azurerm_automation_module

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
in terragrunt.hcl file
remote_state {
  backend = "azurerm"
  generate = {
    path      = "backend.tf"
    if_exists = "overwrite_terragrunt"
  }
  config = {
    resource_group_name   = "myRG"
    storage_account_name  = "myStorage"
    container_name        = "terraform"
    key = "${path_relative_to_include()}/terraform.tfstate"
  }
}

  automation_acct_module_name = "myToolsDSC"
  automation_acct_module_url = "https://mystorage.blob.core.windows.net/dsc/myToolsDSC.zip"

main.tf
variable location {}
variable resource_nonprod_group_name {}
variable automation_acct_name {}
variable automation_acct_sku {}

variable automation_acct_module_name {}
variable automation_acct_module_url {}

module "automationAccount1" {
  source = "../../../infrastructure-modules/AutomationAccount"
  name                = var.automation_acct_name
  location            = var.location
  resource_group_name = var.resource_nonprod_group_name

  sku_name = var.automation_acct_sku

}

resource "azurerm_automation_module" "myToolsModule" {
  name                    = var.automation_acct_module_name
  resource_group_name     = var.resource_nonprod_group_name
  automation_account_name = var.automation_acct_name

  module_link {
    uri = var.automation_acct_module_url
  }
}

### Expected Behaviour

in Automation Account > Modules, see my custom module added from Azure Storage's zip file, automation_acct_module_url

### Actual Behaviour

Error: automation.ModuleClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\"Message\":\"Module is not accessible. Exception: This request is not authorized to perform this operation.\"}"

### Steps to Reproduce

1. `terraform apply` 
Running as Subscription Contributor Service Principal user with remote state in Azure Storage - remote state in same storage account but different container where the Automation Account's zip file is. 

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
