### ISSUE TITLE
AzureRM: Creating a local network gateway using a public ip created in the same process does not work

### ISSUE THREAD

**Issue by thomash0815** [hashicorp/terraform-provider-azurerm#11115]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

TF: 0.13.5
AzRM: 2.48.0

### Affected Resource(s)

* `azurerm_local_network_gateway`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

<script src="https://gist.github.com/thomash0815/6f61fed13e65b695d1b7003bc493b470.js"></script>

### Expected Behaviour

creating resource "azurerm_local_network_gateway" referencing resource (to create) "azurerm_public_ip" works

### Actual Behaviour

using resource "azurerm_public_ip" and trying to reference it in the resource "azurerm_local_network_gateway" - module leads to the error. depends_on doesn't work.

### Steps to Reproduce

1. `terraform apply` -> error occurs
2. `terraform apply` -> all works fine (because the provisioned piublic ip is available

**Comment by aristosvo** [comment]
@thomash0815 Can you provide the .tf configuration as well?

**Comment by thomash0815** [comment]
> @thomash0815 Can you provide the .tf configuration as well?

I guess you mean the .terraformrc file? Can't find it on my hard disk )-:

**Comment by aristosvo** [comment]
No, your terraform configuration, like:
```hcl
resource "azurerm_public_ip" "example {
  // some content
}

resource "azurerm_local_network_gateway" "example {
  // some content
}
```

**Comment by thomash0815** [comment]
terraform {
  required_providers {
    azurerm = {
      source  = "registry.terraform.io/hashicorp/azurerm"      
    }
  }
}

#############################################################################
# PROVIDERS
#############################################################################

provider "azurerm" {
  features {}
}

#############################################################################
# prerequisite resources
#############################################################################

resource "azurerm_resource_group" "rg_vpn_sim" {
    name     = "rgvpngateway"
    location = "northeurope"
}

#vnet azure
resource "azurerm_virtual_network" "vnet_az" {
  name                = "Azure-VNet-1"
  location            = azurerm_resource_group.rg_vpn_sim.location
  resource_group_name = azurerm_resource_group.rg_vpn_sim.name
  address_space       = ["10.0.0.0/16"]
}

#gateway sub azure
resource "azurerm_subnet" "sub_gateway_az" {
  name                 = "GatewaySubnet"
  resource_group_name  = azurerm_resource_group.rg_vpn_sim.name
  virtual_network_name = azurerm_virtual_network.vnet_az.name
  address_prefixes     = ["10.0.255.0/27"]
}

#vnet on-prem
resource "azurerm_virtual_network" "vnet_hq" {
  name                = "HQ-Network"
  location            = azurerm_resource_group.rg_vpn_sim.location
  resource_group_name = azurerm_resource_group.rg_vpn_sim.name
  address_space       = ["172.16.0.0/16"]
}

#gateway sub hq
resource "azurerm_subnet" "sub_gateway_hq" {
  name                 = "GatewaySubnet"
  resource_group_name  = azurerm_resource_group.rg_vpn_sim.name
  virtual_network_name = azurerm_virtual_network.vnet_hq.name
  address_prefixes     = ["172.16.255.0/27"]
}

#pip az
resource "azurerm_public_ip" "ip_az" {
  name                = "ip_az"
  location            = azurerm_resource_group.rg_vpn_sim.location
  resource_group_name = azurerm_resource_group.rg_vpn_sim.name
  allocation_method   = "Dynamic"
}

#pip hq
resource "azurerm_public_ip" "ip_hq" {
  name                = "ip_hq"
  location            = azurerm_resource_group.rg_vpn_sim.location
  resource_group_name = azurerm_resource_group.rg_vpn_sim.name
  allocation_method   = "Dynamic"
}

#vpn gateway on-prem
resource "azurerm_virtual_network_gateway" "vpn_gateway_hq" {
  name                = "vpn_gateway_hq"
  location            = var.location
  resource_group_name = var.rg_name

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false
  sku           = "Basic"

  ip_configuration {
    public_ip_address_id          = azurerm_public_ip.ip_hq.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.sub_gateway_hq.id
  }
}

#lng representing az
resource "azurerm_local_network_gateway" "lng_az" {
  depends_on = [azurerm_public_ip.ip_az]
  name                = "lng_az"
  location            = var.location
  resource_group_name = var.rg_name
  gateway_address     = azurerm_public_ip.ip_az.ip_address
  address_space       = ["10.0.0.0/16"]
}

**Comment by aristosvo** [comment]
The solution here is probably that the actual IP address of `azurerm_public_ip.ip_az` is only known after `azurerm_public_ip.ip_az` is used by a resource, as it is an `Dynamic` IP address.  Thus `azurerm_public_ip.ip_az.ip_address` is `nil` until the IP is used by a resource.

The `azurerm_local_network_gateway.lng_az` should have a `depends_on` that resource instead of `azurerm_public_ip.ip_az`. Based on your setup this is probably the VPN Gateway simulating Azure, something like `azurerm_virtual_network_gateway.vpn_gateway_az`:

```hcl
resource "azurerm_local_network_gateway" "lng_az" {
  depends_on = [azurerm_virtual_network_gateway.vpn_gateway_az]
  name = "lng_az"
  location = var.location
  resource_group_name = var.rg_name
  gateway_address = azurerm_public_ip.ip_az.ip_address
  address_space = ["10.0.0.0/16"]
}
```

**Comment by thomash0815** [comment]
Hi, thanks for your answer, unfortunately, that doesn't work. 

I included a depends_on for resource "azurerm_virtual_network_gateway" and I get the same errors, as well as following in addition:

Error: Error Creating/Updating AzureRM Virtual Network Gateway "vpn_gateway_az" (Resource Group "rgvpngateway"): network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/1833961c-cb9b-4ec5-9fdb-438914562757/providers/Microsoft.Network/locations/northeurope/operations/03eafef9-8882-4aa6-83b5-a93ccccd6bd6?api-version=2020-05-01." Details=[]

**Comment by aristosvo** [comment]
Can you post your new terraform configuration?

**Comment by thomash0815** [comment]
<script src="https://gist.github.com/thomash0815/3f4f97a289c7e68f7e8cb8f5df0473e3.js"></script>

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained. If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
