### ISSUE TITLE
azurerm_analysis_services_server admin_users property is always updated in apply 

### ISSUE THREAD

**Issue by brnn8r** [hashicorp/terraform-provider-azurerm#11118]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform.exe -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
```

### Affected Resource(s)

* `azurerm_analysis_services_server`

### Terraform Configuration Files

**NOTE: A and B are placeholders for admin users**

```hcl
resource "azurerm_analysis_services_server" "server" {
  name                    = "${var.name}"
  location                = azurerm_resource_group.dss.location
  resource_group_name     = azurerm_resource_group.dss.name
  sku                     = local.env == "prod" ? "S0" : "B1"
  admin_users             = [
    "A",
    "B"
    ]
  enable_power_bi_service = true
  tags = local.tags
}

```

### Expected Behaviour

After deploying the `azurerm_analysis_services_server` terraform configuration above subsequent plans or applies should not require any modification to the server resource. 

Running `terraform plan` or `terraform apply` should require no changes.

### Actual Behaviour

After deploying the `azurerm_analysis_services_server` terraform configuration all subsequent plans or applies display

```
 ~ resource "azurerm_analysis_services_server" "server" {
      ~ admin_users               = [
          + "A",
          + "B",
        ]
        enable_power_bi_service   = true

```

### Steps to Reproduce

1. `terraform apply` original configuration
2. `terraform plan` original configuration

### Important Factoids

This issue does not occur if the analysis services server is running at the time of the plan or apply.

Perhaps this is related to the fact you cannot observe the admin_users in Azure Portal when the server is offline?

In any event I'm unsure why the plan wants to modify the admin_users section of the resource when there has been no change to the configuration and the configuration values match the Terraform state file.

### References

The getdetails API is here https://docs.microsoft.com/en-us/rest/api/analysisservices/servers/getdetails#analysisservicesserver.

I can confirm that the response body includes the following when the server is online and does not include the following section when the server is offline.

```
"asAdministrators": {
      "members": [
        "A",
        "B"
      ]
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
