### ISSUE TITLE
Cannot create a Sentinel alert using the template or even the sample code.

### ISSUE THREAD

**Issue by theonemule** [hashicorp/terraform-provider-azurerm#11128]
This error happens every time an apply is performed on the template. Even the sample code resulted in this error.

 creating Sentinel Alert Rule Scheduled "Alert Rule: (Name \"Heartbeat\" / Workspace Name \"workspace1-01\" / Resource Group \"tfdev\")": securityinsight.AlertRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="{\"error\":{\"code\":\"NotFound\",\"message\":\"Couldn't find workspaceMetadata of workspace id xxxxxxxxxxxxxxxxxxx\"}}"

  on config.tf line 27, in resource "azurerm_sentinel_alert_rule_scheduled" "Heartbeat":
  27: resource "azurerm_sentinel_alert_rule_scheduled" "Heartbeat" {
  
Any help appreciated.

**Comment by 1DudeOnTheInternet** [comment]
Same thing happening to me as well :/  

Terraform version: v0.14.5
Azurerm version: v2.53.0

**Comment by theonemule** [comment]
There's a missing step in the docs. You need this part:

resource "azurerm_log_analytics_solution" "la-opf-solution-sentinel"

See the sample below.

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~>2.0"
    }
  }
}

provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "rg" {
  name = "tfdev"
  location = "East US"
}

resource "azurerm_log_analytics_workspace" "laworkspace" {
  name                = "workspace1-01"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}


resource "azurerm_log_analytics_solution" "la-opf-solution-sentinel" {
  solution_name         = "SecurityInsights"
  location              = azurerm_resource_group.rg.location
  resource_group_name   = azurerm_resource_group.rg.name
  workspace_resource_id = azurerm_log_analytics_workspace.laworkspace.id
  workspace_name        = azurerm_log_analytics_workspace.laworkspace.name
  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/SecurityInsights"
  }
}

resource "azurerm_sentinel_alert_rule_scheduled" "Heartbeat" {
  name                       = "Heartbeat"
  log_analytics_workspace_id = azurerm_log_analytics_solution.la-opf-solution-sentinel.workspace_resource_id
  display_name               = "Heartbeat"
  severity                   = "High"
  query                      = <<QUERY
Heartbeat | summarize count() by Computer
QUERY
}

```

**Comment by Simonzhaohui** [comment]
@theonemule The log analytics solution should be required for sentinel resource. The sample codes are great. Thanks.
