### ISSUE TITLE
custom_data & data lookups on azurerm_virtual_machine & azurerm_windows_virtual_machine are not showing values in the JSON plan

### ISSUE THREAD

**Issue by MMollyy** [hashicorp/terraform-provider-azurerm#11129]
Hi all,

Scenario:
We have a stage running on gitlab that performs tests on deployed resources so we can validate mandatory settings. To be able to validate those tests we use the terraform plan json output.
These tests are being run on terraform resources migrated from tf11 to tf14.4, but also on resources that have only been deployed with tf14.4.

I'd like to report a case where the custom_data property inside the os_profile block for an [azurerm_virtual_machine ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine) is giving us trouble when performing a terraform plan. The same applies to data lookups, for example the vault_generic_secret backend provider.
For the custom_data we are using the deprecated template_file still, however we have also placed the same into a locals {} block using the file() function.

The trouble we are experiencing is that terraform plan is not generating the hash for the custom_data and it also seems to not be generating values for data resource lookups like [vault_generic_secret](https://registry.terraform.io/providers/hashicorp/vault/latest/docs/resources/generic_secret).
The weird thing about it is that when we run the plan, do the show, and the apply, there are no issues with the apply. 
Also when we call the template_file data resource or the local and output the value to the screen there are also no issues. the values we expect are being written to the terminal.

I will place two gists with an example tf code containing the lookups that have the issues as well as the json output for that particular resource, followed by a table of test that have been performed over the past day.

tf code belonging with it: https://gist.github.com/MMollyy/7d326c57baaa2c699d12cc608cb3b4b4
Example JSON output: https://gist.github.com/MMollyy/a5dac5d8040494696d62295744fd6427

Tests performed:
| TF version | migrated from/to | Did it already exist? | Resource | Tested property with issues in JSON plan | Issues showing up when using output? |
| ----------- | ------------------- | ------- | ---------- | --------------------- |  ----------------------- |
| tf14.4 | tf11 -> tf 14.4 | yes | azurerm_virtual_machine | data.template_file.winrm_config.rendered | no |
| tf14.4 | tf11 -> tf 14.4 | yes | azurerm_virtual_machine | local.winrm_config | no |
| tf14.4 | tf11 -> tf 14.4 | yes | azurerm_virtual_machine | data.vault_generic_secret.asecret | no |
| tf14.8 | tf11 -> tf 14.8 | yes | azurerm_virtual_machine | data.template_file.winrm_config.rendered | no |
| tf14.8 | tf11 -> tf 14.8 | yes | azurerm_virtual_machine | local.winrm_config | no |
| tf14.8 | tf11 -> tf 14.8 | yes | azurerm_virtual_machine | data.vault_generic_secret.asecret | no |

So in order to test faster I stopped testing with tf14.8 because there were no differences. So I tested deploying the two types of virtual machine resources, and I tested both of those with the deprecated data resource, as well as the local function, and ofcourse I tested the data resource for vault as well.

| TF version | Did it already exist? | Resource | Tested property with issues in JSON plan | Does the property show up in the plan |
| ----------- | ------------------- | ------- | ---------- | --------------------- |
| tf14.4 | no | azurerm_virtual_machine | data.template_file.winrm_config.rendered | no |
| tf14.4 | no | azurerm_virtual_machine | local.winrm_config | no |
| tf14.4 | no | azurerm_virtual_machine | data.vault_generic_secret.asecret | no |
| tf14.4 | no | azurerm_windows_virtual_machine | data.template_file.winrm_config.rendered | yes |
| tf14.4 | no | azurerm_windows_virtual_machine | local.winrm_config | yes |
| tf14.4 | no | azurerm_windows_virtual_machine | data.vault_generic_secret.asecret | yes |
| tf14.4 | yes | azurerm_windows_virtual_machine | data.template_file.winrm_config.rendered | yes |
| tf14.4 | yes | azurerm_windows_virtual_machine | local.winrm_config | yes |
| tf14.4 | yes | azurerm_windows_virtual_machine | data.vault_generic_secret.asecret | yes |

From all the testing I can conclude that the old vm resources only show this behaviour when the resource already exists. And it shows this behaviour across the board with lookups, but only within the azurerm provider so far. The data lookups we do within the aws provider are not showing this behaviour, hence why I am posting this here and not on the terraform github.
the new vm resources do not show this behaviour when the resource already exists and works as expected.

### Expected Behavior
I would expect the hashes and the lookups to be calculated and shown in the JSON for azurerm_virtual_machine just like for azurerm_windows_virtual_machine, for both resources that already exist as well as new deployments.

### Actual Behavior
The hashes for template_file, file() function and content for data lookups are not being shown for azurerm_virtual_machine resource inside the JSON output for a terraform plan, when the resource already exists.

### Steps to Reproduce
1. `Codify a few azurerm_virtual_machine resources with tf14.4`
2. `init, plan (dont forget to put it to a file), apply to deploy `
3. Check the JSON with terraform show, you will see the hash on custom_data or the content for data lookups
4. `terraform plan`
5. `terraform show`
You will find that the existing resources do not show the data lookups or the template_file or local with file() function in the JSON plan. And the new resources are showing.

Required tf code:
https://gist.github.com/MMollyy/474cf21c7b98713be5947abe4d2edc54

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
