### ISSUE TITLE
Conditional Public IP prefix data source using count not working

### ISSUE THREAD

**Issue by tommydejong** [hashicorp/terraform-provider-azurerm#11122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

> + Terraform v0.14.8
> + provider registry.terraform.io/hashicorp/azurerm v2.50.0

### Affected Resource(s)

* `azurerm_public_ip_prefix`

### Terraform Configuration Files

```hcl
data "azurerm_public_ip_prefix" "example" {
  count = var.localvar== "Test" && local.software == true ? 1 : 0 
# I've verified with `terraform console` that this is working correctly. Setting this is to count = 1 produces the same result.

  name                = "pip-prefix-name"
  resource_group_name = "pip-prefix-rg"
}

resource "azurerm_public_ip" "test-pip" {
  name                = "test-pip"
  location            = "westeurope"
  resource_group_name = "test-rg"
  allocation_method   = "Static"
  public_ip_prefix_id = data.azurerm_public_ip_prefix.example[count.index].id
}
```

### Debug Output

can provide at a later date if important

### Panic Output

can provide at a later date if important

### Expected Behaviour

I should be able to access the data source conditionally using [count.index], but I can't.

### Actual Behaviour

The following is produced **with the count** property set, and **without** [count.index]. This gives the expected error message:
```hcl
resource "azurerm_public_ip" "test-pip" {
  name                = "test-pip"
  location            = "westeurope"
  resource_group_name = "test-rg"
  allocation_method   = "Static"
  public_ip_prefix_id = data.azurerm_public_ip_prefix.example.id
}
```

```hcl>> terraform plan
Error: Missing resource instance key

  on ../../terraform-module-vm/main.tf line 231, in output "public_ip_prefix":
 231:   value = data.azurerm_public_ip_prefix.example.ip_prefix

Because data.azurerm_public_ip_prefix.example has "count" set, its attributes
must be accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    data.azurerm_public_ip_prefix.example[count.index]
```

If I follow these instructions and set the following:
```hcl
resource "azurerm_public_ip" "test-pip" {
  name                = "test-pip"
  location            = "westeurope"
  resource_group_name = "test-rg"
  allocation_method   = "Static"
  public_ip_prefix_id = data.azurerm_public_ip_prefix.example[count.index].id
}
```

The following error is produced:
```hcl
Error: Reference to "count" in non-counted context

  on ../../terraform-module-vm/main.tf line 231, in output "public_ip_prefix":
 231:   value = data.azurerm_public_ip_prefix.example[count.index].ip_prefix

The "count" object can only be used in "module", "resource", and "data"
blocks, and only when the "count" argument is set.
```

The error message seems to be going in circles, with me unable to set the count property on a data source, while the error states this should be possible:  
> The "count" object can only be used in "module", "resource", and "data"
> blocks, and only when the "count" argument is set.

### Steps to Reproduce

Copy the snippet below. Try setting/removing the count property on the data source and following the error instructions by setting [count.index] on the data source.

1. 
```hcl
provider "azurerm" {
    features {}
}

terraform {
  required_version = ">= 0.14.5"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.50.0"
    }
  }
}

data "azurerm_public_ip_prefix" "example" {
  count = 1

  name                = "pip-prefix-name"
  resource_group_name = "pip-prefix-rg"
}

resource "azurerm_public_ip" "test-pip" {
  name                = "test-pip"
  location            = "westeurope"
  resource_group_name = "test-rg"
  allocation_method   = "Static"
  public_ip_prefix_id = data.azurerm_public_ip_prefix.example[count.index].id
}
```
2. `terraform plan`
3. This will produce the following error message, stating that the count property is not set while it clearly is set:
```hcl
Error: Reference to "count" in non-counted context

  on main.tf line 23, in output "public_ip_prefix":
  23:   value = data.azurerm_public_ip_prefix.example[count.index].ip_prefix

The "count" object can only be used in "module", "resource", and "data"
blocks, and only when the "count" argument is set.
```

### Important Factoids

Nothing important, just a public Enterprise Agreement subscription. I want to access this public IP prefix only conditionally when a certain condition resolves to true, for licensing server reasons. I would assume this is possible, since data source generally support a count property. This is also mentioned in the error message. However, it cannot be accessed in an output without the count.index set. Please advise :)

### References

* #0000

**Comment by favoretti** [comment]
Hi and thank you for reporting this. Your `azurerm_public_ip` resource must also be created using count, otherwise there's no loop when interpolating it and it won't be indexing anything.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @favoretti‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
