### ISSUE TITLE
azurerm_data_factory_integration_runtime_managed Creates azure-ssis integration runtime instead

### ISSUE THREAD

**Issue by kanishkadubey0688** [hashicorp/terraform-provider-azurerm#11138]
Hi, 

I am using the terraform code for  azurerm_data_factory_integration_runtime_managed for creating azure managed integration runtime, but instead it creates an azure-ssis integration runtime which is not an expected output.

Thanks,
Kanishka

**Comment by favoretti** [comment]
Hi and thank you for reporting this. To be able to help you better, can you share your terraform code used to create the resources and potentially any screenshots indicating what went wrong? Thanks!

**Comment by njuCZ** [comment]
@kanishkadubey0688 `azurerm_data_factory_integration_runtime_managed` is deprecated and `azurerm_data_factory_integration_runtime_azure_ssis` is prefered. They are the same.

**Comment by rcskosir** [comment]
Thank you @kanishkadubey0688 for taking the time to open this issue. I am going to mark this as closed with the response by @njuCZ. If you have questions in the future, I suggest one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
