### ISSUE TITLE
`role_based_access_control` should default to `enabled` for new AKS clusters

### ISSUE THREAD

**Issue by seanhamlin** [hashicorp/terraform-provider-azurerm#11140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if new AKS cluster installation could default to having RBAC (through `role_based_access_control`) set to `enabled`.

Seeing as this needs to be set at cluster creation time (and cannot be changed afterwards without cluster recreation) it would make sense to make this opt-out, rather than opt-in. This is more secure by default.

### Potential Terraform Configuration

Alter the section https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#role_based_access_control to have `role_based_access_control` default to `enabled` for new clusters.

### References

At the moment, Azure CLI has this behaviour ([docs link](https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az_aks_create)) where RBAC is enabled by default:

```
  --enable-rbac -r
    Enable Kubernetes Role-Based Access Control. Default: enabled.
```

and other cloud providers do as well in Terraform (e.g. AWS EKS).

**Comment by favoretti** [comment]
Hi and thank you for reporting this. Unfortunately this would be a breaking change, since it would force cluster recreation for people who have not specified this property. @tombuildsstuff something to consider for 3.0?
