### ISSUE TITLE
[preview] Support for mutual TLS and shared ssl policy in application_gateway

### ISSUE THREAD

**Issue by timja** [hashicorp/terraform-provider-azurerm#11141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

See https://github.com/Azure/azure-cli/issues/16144, https://github.com/Azure/azure-cli/pull/16762

Available from `Microsoft.Network/stable/2020-06-01` api version

~Currently [2020-05-01](https://github.com/terraform-providers/terraform-provider-azurerm/blob/ae0448bede101561b8bb0b1be7cf831e6c5c31bc/azurerm/internal/services/network/application_gateway_resource.go#L9) is used so an API version update is required~ - updated in https://github.com/terraform-providers/terraform-provider-azurerm/pull/11627

https://github.com/Azure/azure-rest-api-specs/blob/08f526c7011f9d34fbe7e912c9b2994e75179a80/specification/network/resource-manager/Microsoft.Network/stable/2020-06-01/applicationGateway.json#L1364

### New or Affected Resource(s)

* azurerm_application_gateway_ssl_policy
* azurerm_application_gateway_client_certificate
* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azurerm_application_gateway_client_certificate" "cert" {
  name = "clientcert"
  data = "..."
}

resource "azurerm_application_gateway_ssl_policy" "policy" {
  name                   = "sslProfile1"
  type                   = "custom" # or predefined
  min_protocol_version   = "TLSv1_2"
  disabled_ssl_protocols = ["TLSv1"]
  cipher_suites          = ["TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"]
  client_auth_configuration {
    verify_client_cert_issuer_DN = true
  }
  trusted_client_certificates = [azurerm_application_gateway_client_certificate.cert.id]
}

resource "azurerm_application_gateway" "gateway" {
  ...
  
  http_listener {
    # not 100% sure on this the API has the ID under a nested field under ssl_policy but seems a bit simpler to flatten it
    # and I think this belongs at the http_listener level but not clear again
    ssl_policy_id = azurerm_application_gateway_ssl_policy.policy.id
  }
}
```

### References

* #0000

**Comment by captainbrown** [comment]
I'm happy to see that this is getting priority.  What's a good workaround to keep terraform from wiping any Mutual TLS we put on a terraform-managed App Gateway?  The best I have gotten so far is:

  lifecycle {
    ignore_changes = [
      http_listener
    ]
  }
  
Any more specific and it wants to update all of my listeners and wipe my mutual-TLS.  Unfortunately, that means that any http_listener blocks are pretty much useless after the first build.
