### ISSUE TITLE
Updating from <2.42.0 to >2.42.0 can cause a mismatch between state and resource with updated keyvault defaults

### ISSUE THREAD

**Issue by LP0101** [hashicorp/terraform-provider-azurerm#11144]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue description:

When updating from a version of azurerm_keyvault prior to 2.42.0 to a one after 2.42.0, the default value of `soft_delete_enabled` changes. If the defaults were used previous, the value will change in the state, but it will not change on the resource itself, resulting in a mismatch between state and resource.

### Terraform (and AzureRM Provider) Version

Terraform 13.4, Terraform 0.14.9, Azurerm 2.53.0

### Affected Resource(s)

* `azurerm_keyvault`

### Debug Output

`terraform plan` run before the provider was updated:

https://gist.github.com/LP0101/648aed37385854bcd5da76c6059ef266

`terraform plan` run after the provider was updated:

https://gist.github.com/LP0101/23cf7a60165232a68905f77ff6b6225b

Notice the values on `soft_delete_enabled` and `soft_delete_retention_days` have changed, without it registering as an actual change.

### Expected Behaviour

The value of the state should match the value of the resource

### Actual Behaviour

The value of the state gets updated with the new defaults, but the resource itself keeps the old defaults (`soft_delete_enabled` remains false on the keyvault itself)

### Steps to Reproduce

1. Deploy an azure-keyvault resource using an azurerm version < 2.42.0, without the `soft_delete_enabled` variable being set (thus, using the default, which is `false`)
2. Update the version to > 2.42.0
3. `terraform apply`
4. The log will show the value of `soft_delete_enabled` being set to true, but not registered as a change. This will update it in the state, but not on the actual resource.

**Comment by favoretti** [comment]
Hi and thank you for reporting this. As you can see from the [CHANGELOG entry](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG-v2.md#2420-january-08-2021) this has been announced as a breaking change in 2.42.0.

**Comment by tombuildsstuff** [comment]
👋 

Unfortunately the Azure API force-enabled Soft Delete for all Key Vault resources - however newer versions of the Provider support this implementation. I'm going to close this out since I believe this has been fixed in newer versions of the Azure Provider, but if your still seeing this issue when using the latest version of the Azure Provider please feel free to open a new issue and we'll take another look.

Thanks!
