### ISSUE TITLE
azurerm_network_connection_monitor (API v2 based) doesn't support adding MMAWorkspaceMachine type endpoints 

### ISSUE THREAD

**Issue by vholubek** [hashicorp/terraform-provider-azurerm#11153]
It's not possible to add Log Analytics Workspace-based non-Azure endpoints to the connection monitor. Per following documentation https://docs.microsoft.com/en-us/rest/api/network-watcher/connectionmonitors/createorupdate non-Azure endpoints are created as follows using API v2:

```json
      {
        "name": "CanaryWorkspaceVamshi",
        "resourceId": "/subscriptions/96e68903-0a56-4819-9987-8d08ad6a1f99/resourceGroups/vasamudrRG/providers/Microsoft.OperationalInsights/workspaces/vasamudrWorkspace",
        "filter": {
          "type": "Include",
          "items": [
            {
              "type": "AgentAddress",
              "address": "npmuser"
            }
          ]
        }
      },
```

The ARM JSON representation of a non-Azure endpoint is:

```
endpoint {
   type        = "MMAWorkspaceMachine"
   name        = "OnPrem-SERVERNAME"
   address     = "SERVERNAME.ad-domain.com"
   resource_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.OperationalInsights/workspaces/xxxxxxxxxx"
}
```

Writing a corresponding terraform code:
```hcl
endpoint {
    name               = "OnPrem-SERVERNAME"
    resource_id        = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.OperationalInsights/workspaces/xxxxxxxxxx"

    filter {
      item {
        address = "SERVERNAME.ad-domain.com"
        type    = "AgentAddress"
      }

      type = "Include"
    }
}
```
Terraform fails with `...an argument named "resource_id" is not expected here.`

When using `virtual_machine_id` instead of `resource_id`:
`Error: Can not parse "endpoint.0.filter.0.item.0.address" as a resource id: Cannot parse Azure ID: parse "SERVERNAME.ad-domain.com": invalid URI for request`
`Error: ID was missing the 'virtualMachines' element`

**Comment by SteveBurkettNZ** [comment]
Think this could be closed?  

The current parameters as per the [network connection monitor endpoint docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_connection_monitor#endpoint) are **target_resource_type** and **target_resource_id**

Can confirm those work ok.

**Comment by vholubek** [comment]
Steve, yes this is good to close. Those parameters work. Thank you.


Viktor Holubek


________________________________
From: Steve Burkett ***@***.***>
Sent: Wednesday, November 23, 2022 11:24 PM
To: hashicorp/terraform-provider-azurerm ***@***.***>
Cc: Viktor Holubek ***@***.***>; Author ***@***.***>
Subject: EXTERNAL: Re: [hashicorp/terraform-provider-azurerm] azurerm_network_connection_monitor (API v2 based) doesn't support adding MMAWorkspaceMachine type endpoints (#11153)


[Use caution with links & attachments]



Think this could be closed?

The current parameters as per the network connection monitor endpoint docs<https://urldefense.com/v3/__https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_connection_monitor*endpoint__;Iw!!JhrIYaSK6lFZ!t_E_XsRohw3J8d70X5wq9EkNJXyCIFpsDUqO8Jns39CJm3XZYTuECQk_v-cU5aoAUVDKHzZ2EQQ8lT0mkH4buTSg3Zso$> are target_resource_type and target_resource_id

Can confirm those work ok.

**Comment by rcskosir** [comment]
Closing as noted above by author.
