### ISSUE TITLE
"Azurerm_private_dns_zone" is missing subscription argument

### ISSUE THREAD

**Issue by chakri-nelluri** [hashicorp/terraform-provider-azurerm#11159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Provider version - v2.53.0

### Affected Resource(s)

* `Azurerm_private_dns_zone`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "azurerm" {
  features {}
}

# Existing Azure Private DNS zone
data "azurerm_private_dns_zone" "example" {
  name                = "test.com"
  resource_group_name = "private_dns_zone_resource_group"
}
```

### Expected Behaviour
Private DNS zones can span across subscriptions. Please add subscription as an argument in addition to resource group name.

### Actual Behaviour
Unable to specify subscription. Only resource group name is allowed. When the private DNS Zone resource group is in a separate subscription

### Steps to Reproduce

Create a Private DNS zone in one subscription and you cannot link it to private endpoints created in another subscription. It is allowed from Console.

1. `terraform plan`
~/work/tmp/private_dns_zone$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

data.azurerm_private_dns_zone.example: Refreshing state...

Error: Private DNS Zone "test.com" (Resource Group "private_dns_zone_resource_group") was not found

  on main.tf line 6, in data "azurerm_private_dns_zone" "example":
   6: data "azurerm_private_dns_zone" "example" {

### References
https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns

* #0000

**Comment by beniclouds** [comment]
hi @chakri-nelluri 
had the same problem, hope this resolves it for you. 
```terraform
resource "azurerm_private_endpoint" "private_endpoint" {
    name                = "${var.name}-pe"
    location            = var.location
    resource_group_name = var.resource_group_name
    subnet_id           = var.subnet_id
    tags                = var.tags
    
    private_service_connection {
        name                           = "${var.name}-psc"
        private_connection_resource_id = var.storage_account_id
        subresource_names              = var.subresource_names
        is_manual_connection           = false
    }

    private_dns_zone_group {
          name                 = "${var.name}-dns-zone-group"
          private_dns_zone_ids = [
            "/subscriptions/${var.subscription_id_dns}/resourceGroups/${var.resource_group_name_dns}/providers/Microsoft.Network/privateDnsZones/${var.private_dns_zone_name}",
          ]
    }
}
```

**Comment by nihaldivyam** [comment]
> hi @chakri-nelluri had the same problem, hope this resolves it for you.
> 
> ```terraform
> resource "azurerm_private_endpoint" "private_endpoint" {
>     name                = "${var.name}-pe"
>     location            = var.location
>     resource_group_name = var.resource_group_name
>     subnet_id           = var.subnet_id
>     tags                = var.tags
>     
>     private_service_connection {
>         name                           = "${var.name}-psc"
>         private_connection_resource_id = var.storage_account_id
>         subresource_names              = var.subresource_names
>         is_manual_connection           = false
>     }
> 
>     private_dns_zone_group {
>           name                 = "${var.name}-dns-zone-group"
>           private_dns_zone_ids = [
>             "/subscriptions/${var.subscription_id_dns}/resourceGroups/${var.resource_group_name_dns}/providers/Microsoft.Network/privateDnsZones/${var.private_dns_zone_name}",
>           ]
>     }
> }
> ```

This doesn't create the private-dns-zone virtual-network link

**Comment by nihaldivyam** [comment]
@chakri-nelluri did you found the fix ?

**Comment by nihaldivyam** [comment]
@chakri-nelluri I got around the issue using providers

```
provider "azurerm" {
  subscription_id = var.external_subscription_of_dns_zone
  features {}
  alias = "externalsubs"
  skip_provider_registration = true
}

resource "azurerm_private_dns_zone_virtual_network_link" "link_private_dns" {

  name                  = "private-endpoint-link"
  resource_group_name   = "external-subs-resource-group"
  private_dns_zone_name = "privatelink.blob.core.windows.net"
  virtual_network_id    = azurerm_virtual_network.aksvnet[0].id
  registration_enabled = true
  provider = azurerm.externalsubs
}
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
