### ISSUE TITLE
ip_restriction block in App_service says ip_address is required when documentation says it is optional

### ISSUE THREAD

**Issue by dalejmarshall** [hashicorp/terraform-provider-azurerm#11151]
I'm attempting to add an ip_restriction block to the site_config. The [documentation ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#ip_restriction) states ip_address, service_tag  and virtual_network_subnet_id are all optional but one of them must be specified. I have specified service_tag yet I am still receiving the error "Inappropriate value for attribute "ip_restriction": element 0: attributes
"ip_address", "subnet_id", and "virtual_network_subnet_id" are required."

`ip_restriction = [  {
      service_tag     = "AzureFrontDoor.Backend"
      priority        = "300"
      name            = "FrontDoorAccess"
      action          = "Allow"
    } ]`

**Comment by Tzalo** [comment]
I had the same issue today and I have seen that setting to null the other values it works.

```
ip_address = null
virtual_network_subnet_id = null
headers = []
```

**Comment by Quixotical** [comment]
I'm getting this issue as well now in CDKTF, but setting to null doesn't appear to fix the issue

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
