### ISSUE TITLE
Cannot create an express route connection from an express route gateway in virtual hub - ID was missing the virtualNetworkGateways element

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#11162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `virtual_network_gateway_connections`

I create an ER GW attached to a virtual hub.

```hcl
resource "azurerm_express_route_gateway" "er_gateway" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  virtual_hub_id      = azurerm_virtual_hub.vwan_hub.id

  scale_units = var.virtual_hub_config.er_config.scale_units
}
```

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Actual Behaviour

```
 # module.solution.module.virtual_network_gateway_connections["er-1"].azurerm_virtual_network_gateway_connection.vngw_connection will be created
  + resource "azurerm_virtual_network_gateway_connection" "vngw_connection" {
      + authorization_key                  = (sensitive value)
      + connection_protocol                = (known after apply)
      + enable_bgp                         = (known after apply)
      + express_route_circuit_id           = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/expressRouteCircuits/er-1"
      + express_route_gateway_bypass       = (known after apply)
      + id                                 = (known after apply)
      + location                           = "southeastasia"
      + name                               = (known after apply)
      + resource_group_name                = "xxx"
      + routing_weight                     = (known after apply)
      + tags                               = {
          + "module" = "virtual_network_gateway_connections"
        }
      + type                               = "ExpressRoute"
      + use_policy_based_traffic_selectors = false
      + virtual_network_gateway_id         = "/subscriptions/xxx/resourceGroups/cccc/providers/Microsoft.Network/expressRouteGateways/yyyyyy"

      + timeouts {
          + create = "60m"
          + delete = "60m"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

This plan was saved to: /home/vscode/.terraform.cache/tfstates/level2/tfstate/caf_networking_vwan.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "/home/vscode/.terraform.cache/tfstates/level2/tfstate/caf_networking_vwan.tfplan"

Terraform plan return code: 0
@calling apply
running terraform apply
module.solution.module.virtual_network_gateway_connections["er-1"].azurecaf_name.vngw_connection: Creating...
module.solution.module.virtual_network_gateway_connections["er-1"].azurecaf_name.vngw_connection: Creation complete after 0s [id=kjwrxwmjlkywwyar]
module.solution.module.virtual_network_gateway_connections["er-1"].azurerm_virtual_network_gateway_connection.vngw_connection: Creating...
Terraform apply return code: 0
Terraform returned errors:

Error: ID was missing the `virtualNetworkGateways` element

  on /home/vscode/.terraform.cache/modules/solution/modules/networking/virtual_network_gateway_connections/module.tf line 11, in resource "azurerm_virtual_network_gateway_connection" "vngw_connection":
  11: resource "azurerm_virtual_network_gateway_connection" "vngw_connection" {
```

the ER connection is not created. 

### Steps to Reproduce

1. `terraform apply`

### References

https://docs.microsoft.com/en-us/azure/templates/microsoft.network/expressroutegateways/expressrouteconnections?tabs=json

* #0000

**Comment by ArielRam99** [comment]
Could this help? : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/express_route_connection

**Comment by lukebailey** [comment]
Did anyone get to the bottom of this, we are seeing the same issue with `azurerm_virtual_network_gateway_connection`

**Comment by twhite-coles** [comment]
@lukebailey We ended up getting it working by using the azurerm_express_route_connection provider.
Below assumes 1 vWAN, 2 vHUBs and 2 ER connections (one to each Hub). Only manual thing we needed to do was generate Auth Keys on the ER Circuits and pass through a Library Group (as our ER is in another Subscription and it was failing as our pipeline had no service connection into that Sub):

resource "azurerm_virtual_wan" "VWAN" {
  name                = var.virtual_wan_name
  resource_group_name = var.resource_group_primary_name
  location            = var.location_name_primary
  allow_branch_to_branch_traffic = var.allow_branch_to_branch

}

resource "azurerm_virtual_hub" "VHUBP" {
  name                = var.virtual_hub_primary_name
  resource_group_name = var.resource_group_primary_name
  location            = var.location_name_primary
  virtual_wan_id      = azurerm_virtual_wan.VWAN.id
  address_prefix      = var.subnet_primary_range
}

resource "azurerm_virtual_hub" "VHUBS" {
  name                = var.virtual_hub_secondary_name
  resource_group_name = var.resource_group_primary_name
  location            = var.location_name_secondary
  virtual_wan_id      = azurerm_virtual_wan.VWAN.id
  address_prefix      = var.subnet_secondary_range
}

resource "azurerm_express_route_gateway" "ERGP" {
  name                = var.er_gateway_primary_name
  resource_group_name = var.resource_group_primary_name
  location            = var.location_name_primary
  virtual_hub_id      = azurerm_virtual_hub.VHUBP.id
  scale_units         = var.er_gateway_scale_units
}

resource "azurerm_express_route_gateway" "ERGS" {
  name                = var.er_gateway_secondary_name
  resource_group_name = var.resource_group_primary_name
  location            = var.location_name_secondary
  virtual_hub_id      = azurerm_virtual_hub.VHUBS.id
  scale_units         = var.er_gateway_scale_units
}

resource "azurerm_express_route_connection" "conn_primary" {
  name                = var.vngc_hub_primary_name
  express_route_gateway_id  = azurerm_express_route_gateway.ERGP.id
  express_route_circuit_peering_id = var.er_circuit_aue_id
  authorization_key = var.er_authorization_key_aue
  routing_weight    = 0
}

resource "azurerm_express_route_connection" "conn_secondary" {
  name                = var.vngc_hub_secondary_name
  express_route_gateway_id  = azurerm_express_route_gateway.ERGS.id
  express_route_circuit_peering_id = var.er_circuit_aus_id
  authorization_key = var.er_authorization_key_aus
  routing_weight    = 0
}
