### ISSUE TITLE
azurerm_mariadb_server create from a geo redundant backup

### ISSUE THREAD

**Issue by daseth** [hashicorp/terraform-provider-azurerm#11168]
It is not clear from the documentation if we can create a new MariaDB server from a geo redundant backup. The create_mode block might indicate that it is possible but unclear how it would be used.

So is it possible to create a server from a backup with terraform?
If Yes, can anyone provide an example?

**Comment by jaydrue** [comment]
We are trying to deploy complete infrastructure deployments for development purposes with many different pieces of infrastructure. The only piece that is missing is currently the content of the database in the mariadb server. Based on the documentation it's not exactly clear how to do it and there are limitations that are not obvious from reading the docs. 

For example:

We have setup and are managing mariadb servers in separate production and staging subscriptions. These are currently being updated in a semi-automatic way (outside of the terraform space). For the development subscription (where we test and deploy new infrastructure modules) we want to have a working database with a structure and most recent data content on it. I tried to reference the staging database as a base/seed and replicate it to create a new database resource. 

However, and here is the catch: Azure does not allow to reference a database that is in a different subscription or resource group other than the base database you want to create from. I can see that this is most likely a provider issue and not directly terraform related. However, manually one could replicate the database in the subscription where the original database resides and move it to the desired location afterwards.

Is there a suitable solution/workaround that I am not seeing or a solution planned for this? Is there any more documentation on database seeding planned?

Thanks for any updates.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
