### ISSUE TITLE
AKS cluster creation reports failure but actually succeeds in Azure

### ISSUE THREAD

**Issue by zak-forsyth** [hashicorp/terraform-provider-azurerm#11179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5

provider registry.terraform.io/hashicorp/azurerm v2.53.0

### Affected Resource(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

https://gist.github.com/zak-forsyth/de9d3882be93fbbdb2451c163819cb70

### Expected Behaviour

The creation of the Kubernetes cluster should complete successfully.
If Terraform encountered an internal error Terraform should retry the requested operation until successful or a retry timeout is hit.

### Actual Behaviour

Terraform reports failure. But Azure actually goes on to create the cluster successfully. Now the terraform state is out of sync.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. These situations can happen unfortunately, from what I see from debug output - AKS cluster creation was successful, however NodePool wasn't created. Did you check whether NodePool creation was successful as well?

**Comment by zak-forsyth** [comment]
> Hi there and thank you for reporting this. These situations can happen unfortunately, from what I see from debug output - AKS cluster creation was successful, however NodePool wasn't created. Did you check whether NodePool creation was successful as well?

The node pool initially failed with an agent communication error. AKS retries the node pool through their remediation process and does eventually succeed and the cluster is healthy. 

This is a repeatable failure and due to whatever environmental reasons the node pool initially failed it causes terraform to fail as well.

**Comment by stephybun** [comment]
Hi @zak-forsyth,

Thanks for raising this issue. At the core this looks to be caused by the same behaviour that's described in #9342 for which there is already an upstream issue https://github.com/Azure/AKS/issues/1972. If you don't mind I will consolidate this into #9342, please subscribe to that issue for updates. Thanks!
