### ISSUE TITLE
Cannot create Azure Site Recovery Fabric using Terraform. Error code=404:"FabricArmEntityMissing"

### ISSUE THREAD

**Issue by MayurP-DI** [hashicorp/terraform-provider-azurerm#11180]
Cannot enable A2A VM replication via Terraform. The Fabric creation is failing with the below error.
The Fabric doesn't exist and Azure API is responding with 404 code, which is the expected response, however, it looks like the terraform is not handling the response in a proper way.

Error checking for presence of existing site recovery fabric primary-fabric-payroll (vault-recovery-vault): siterecovery.ReplicationFabricsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Fabric with name primary-fabric could not be located." Details=[{"activityId":"***","clientRequestId":"***","code":"FabricArmEntityMissing","message":"Fabric with name primary-fabric could not be located.","possibleCauses":"The fabric might have been unregistered from the Microsoft Azure Site Recovery vault.","recommendedAction":"Retry the operation with a valid site."}] 2021-03-25T19:44:10.7260906Z 2021-03-25T19:44:10.7261879Z   on asr.tf line 10, in resource "azurerm_site_recovery_fabric" "primary": 2021-03-25T19:44:10.7264393Z   10: resource "azurerm_site_recovery_fabric" "primary" {

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
