### ISSUE TITLE
azurerm_api_management_custom_domain does not set Azure AD System Assigned Identity Reply URL to Developer Portal, causes Azure AD Logins to Docs site to fail

### ISSUE THREAD

**Issue by kensykora** [hashicorp/terraform-provider-azurerm#11185]
When you assign a custom domain the Azure API Management Developer Portal, the System Assigned Identity does not get its reply URLs updated with the custom domain name. It's not really clear to me if this is a bug in Azure, a bug in the TF provider, or a manual step you are expected to do.

It seems that the system assigned identity gets the reply URLs added automatically:

![image](https://user-images.githubusercontent.com/64756/113237971-7b245000-926d-11eb-9060-cdfe41858263.png)

![image](https://user-images.githubusercontent.com/64756/113237406-609da700-926c-11eb-9ff7-8bc468978c3e.png)

![image](https://user-images.githubusercontent.com/64756/113237300-321fcc00-926c-11eb-8e50-37c5ff1e5197.png)

Note that the Azure AD app does not contain the custom domain name with the updated developer portal URL, but still has the old one.

Workarounds I'm considering:

- Manual Step (not ideal, but acceptable)
- Using a User assigned identity (In Preview, ~acceptable-ish)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.53.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
```

### Affected Resource(s)

* `azurerm_api_management`
* `azurerm_api_management_custom_domain `

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_certificate" "star_contoso_eu" {
  name         = "star-contoso-eu"
  key_vault_id = var.global.key-vault.id
}
resource "azurerm_api_management" "api-management" {
  location            = var.global.main-rg.location
  name                = "${var.global.main-rg.name}-apimgmt"
  publisher_email     = "api-publisher@contoso.com"
  publisher_name      = "Contoso Solutions"
  resource_group_name = var.global.main-rg.name

  identity {
    type = "SystemAssigned"
  }

  sku_name = var.sku_name

  tags = local.common_tags

  policy {
    xml_content = <<XML
  <policies>
    <inbound>
        <cors>
            <allowed-origins>
              %{for origin in var.cors_origins~}
                <origin>${origin}</origin>
              %{endfor~}
            </allowed-origins>
            <allowed-methods>
                <method>GET</method>
                <method>POST</method>
                <method>PUT</method>
                <method>DELETE</method>
                <method>OPTIONS</method>
                <method>PATCH</method>
            </allowed-methods>
            <allowed-headers>
                <header>*</header>
            </allowed-headers>
        </cors>
    </inbound>
    <backend>
        <forward-request />
    </backend>
    <outbound />
    <on-error />
  </policies>
  XML
  }
}

resource "azurerm_api_management_custom_domain" "apim-hostnames" {
  api_management_id = azurerm_api_management.api-management.id

  depends_on = [
    azurerm_key_vault_access_policy.apim
  ]

  developer_portal {
    host_name = "api-docs${lower(var.global.environment) != "prod" ? "-${lower(var.global.environment)}" : ""}.contoso.eu"

    # Example: https://contoso-kv.vault.azure.net/secrets/star-contoso-eu/c0e15d4a2665409d9ff7686732721461
    #                                                                     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    #                                                                     ^
    #                                                                     Get rid of this stuff
    # Split on /'s, cut the last one off, re-join on / again.
    # KMS 31 MAR 2021
    key_vault_id = join("/", slice(split("/", data.azurerm_key_vault_certificate.star_contoso_eu.secret_id), 0, length(split("/", data.azurerm_key_vault_certificate.star_contoso_eu.secret_id)) - 1))
  }

  proxy {
    default_ssl_binding = true
    host_name           = "api${lower(var.global.environment) != "prod" ? "-${lower(var.global.environment)}" : ""}.contoso.eu"

    # same as above KMS 31 MAR 2021
    key_vault_id = join("/", slice(split("/", data.azurerm_key_vault_certificate.star_contoso_eu.secret_id), 0, length(split("/", data.azurerm_key_vault_certificate.star_contoso_eu.secret_id)) - 1))
  }
}
```

### Steps to Reproduce

1. `terraform apply`
2. Log into API Docs site with Azure AD

Login Fails

### Expected Behaviour

Provisioning a custom domain name adds the reply URL with the custom domain to Azure AD (again, this might be an expectation since Azure manages the reply urls... I presume...)

### Actual Behaviour

Reply URL is not updated and Login breaks

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
