### ISSUE TITLE
Azure fileshare backup resource failing with message - storage account not registered with vault , but its already registered 

### ISSUE THREAD

**Issue by KannappanSomu** [hashicorp/terraform-provider-azurerm#11184]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.14.7
tried with both azure provider 2.53 and 2.46.1

### Affected Resource(s)

* `azurerm_backup_protected_file_share`

### Terraform Configuration Files

```hcl
resource "azurerm_recovery_services_vault" "recovery-vault-prod" {
  count = var.environment == "dev" ? 0 : 1 
  name                = "kap-recovery-vault-prod"
  location            = "westeurope"
  resource_group_name = var.resource_group_name
  sku                 = "Standard"
}

resource "azurerm_backup_container_storage_account" "kap-protection-prod" {
  count = var.environment == "dev" ? 0 : 1 
  resource_group_name = var.resource_group_name
  recovery_vault_name = azurerm_recovery_services_vault.recovery-vault-prod[count.index].name
  storage_account_id  = module.storage-account-kapacitors.storage_account_id
}
resource "azurerm_backup_container_storage_account" "etcd-protection-prod" {
  count = var.environment == "dev" ? 0 : 1 
  resource_group_name = var.resource_group_name
  recovery_vault_name = azurerm_recovery_services_vault.recovery-vault-prod[count.index].name
  storage_account_id  = module.storage-account-etcd-chronograf.storage_account_id
}
resource "azurerm_backup_policy_file_share" "kap-recovery-prod" {
  count = var.environment == "dev" ? 0 : 1 
  name                = "kap-recovery-prod-vault-policy"
  resource_group_name = var.resource_group_name
  recovery_vault_name = azurerm_recovery_services_vault.recovery-vault-prod[count.index].name

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }
}



--------------------

resource "azurerm_backup_protected_file_share" "share1" {
  resource_group_name       = var.resource_group_name
  recovery_vault_name       = var.recovery_vault_name
  source_storage_account_id = var.source_storage_account_id
  source_file_share_name    = azurerm_storage_share.file_share.name
  backup_policy_id          = var.backup_policy_id
}


----------------------
```

### Panic Output

2021-04-01T00:09:55.1007600Z Error: [ERROR] fileshare XXXXXXXX  not found in protectable or protected fileshares, make sure Storage Account "kapdatadev" is registered with Recovery Service Vault "kap-recovery-vault" (Resource Group "XXXXXXX")
2021-04-01T00:09:55.1008458Z 
2021-04-01T00:09:55.1008991Z   on modules\azure-storage-share\main.tf line 13, in resource "azurerm_backup_protected_file_share" "share1":
2021-04-01T00:09:55.1009601Z   13: resource "azurerm_backup_protected_file_share" "share1" {
2021-04-01T00:09:55.1009823Z 

### Expected Behaviour

the storage account is already registerd with recovery vault & so it should create backup of fileshare

### Actual Behaviour

2021-04-01T00:09:55.1007600Z Error: [ERROR] fileshare XXXXX not found in protectable or protected fileshares, make sure Storage Account "kapdatadev" is registered with Recovery Service Vault "kap-recovery-vault" (Resource Group "XXXXXXXX")
2021-04-01T00:09:55.1008458Z 
2021-04-01T00:09:55.1008991Z   on modules\azure-storage-share\main.tf line 13, in resource "azurerm_backup_protected_file_share" "share1":
2021-04-01T00:09:55.1009601Z   13: resource "azurerm_backup_protected_file_share" "share1" {
2021-04-01T00:09:55.1009823Z 

### Steps to Reproduce

1. `terraform apply`

### Comments:

I believe this is a bug in terraform after some recent changes in flishare API. Its working with following workaround

### workaround : 

Enable back up manually for fileshare & 
then stop the backup again 
and rerun terraform apply step

**Comment by KannappanSomu** [comment]
using terraform provider 2.53

**Comment by KannappanSomu** [comment]
any update on this

**Comment by otabut** [comment]
👍

**Comment by geekzter** [comment]
The same HCL fails under certain conditions only:

- Creating 1 protected item: SUCCESS
- Creating 2 protected items: SUCCESS
- Adding a protected item to a pre-existing one: ERROR (same as above)

```hcl
resource azurerm_backup_protected_file_share minecraft_data {
  resource_group_name          = azurerm_resource_group.minecraft.name
  recovery_vault_name          = azurerm_recovery_services_vault.backup.0.name
  source_storage_account_id    = azurerm_storage_account.minecraft.id
  source_file_share_name       = module.minecraft[each.key].container_data_share_name
  backup_policy_id             = azurerm_backup_policy_file_share.nightly.0.id

  depends_on                   = [azurerm_backup_container_storage_account.minecraft]

  for_each                     = var.enable_backup ? toset(keys(var.minecraft_config)) : []
}
```

**Comment by arock76** [comment]
Any update on this one?

I am experiencing the same error.
Error: [ERROR] fileshare 'XXXXXXXX' not found in protectable or protected fileshares, make sure Storage Account "XXXXXXX" is registered with Recovery Service Vault "XXXXXXXX" (Resource Group "XXXXXXXXXX")

terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.67.0

I found another workaround is to go into the recovery services vault and go through the steps to add the file share manually. Once the select file shares screen refreshes with the new share you can cancel out and run successfully in Terraform.

**Comment by sinbai** [comment]
@KannappanSomu  I can reproduce this issue based on your TF config, and verified it can be fixed after adding `depends_on`. Could you help verify that this issue is resolved on your side when you add `depends_on` in tf config?

**Comment by KannappanSomu** [comment]
sure ,  will update you soon .
