### ISSUE TITLE
azurerm_subnet - service_endpoint_policy_ids updated after apply

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azurerm#11207]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.54.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.0"
    }
  }
  required_version = "~> 0.13"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "network" {
  name     = "hbtest"
  location = "uksouth"
}

resource "azurerm_virtual_network" "network" {
  name                = "hbtest"
  address_space       = ["10.0.0.0/16"]
  dns_servers         = []
  location            = azurerm_resource_group.network.location
  resource_group_name = azurerm_resource_group.network.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "test"
  resource_group_name  = azurerm_resource_group.network.name
  virtual_network_name = azurerm_virtual_network.network.name
  address_prefixes     = ["10.0.0.0/27"]
  service_endpoints    = []
}

output "subnet" {
  value = azurerm_subnet.subnet
}

```

### Expected Behaviour

Run terraform apply, then run terraform plan, there should be no changes

### Actual Behaviour

Terraform plan shows `Changes to Outputs`

```
terraform apply

Apply complete! Resources: 3 added, 0 changed, 0 destroyed.

Outputs:

subnet = {
  "address_prefix" = "10.0.0.0/27"
  "address_prefixes" = tolist([
    "10.0.0.0/27",
  ])
  "delegation" = tolist([])
  "enforce_private_link_endpoint_network_policies" = false
  "enforce_private_link_service_network_policies" = false
  "id" = "/subscriptions/xxx/resourceGroups/hbtest/providers/Microsoft.Network/virtualNetworks/hbtest/subnets/test"
  "name" = "test"
  "resource_group_name" = "hbtest"
  "service_endpoint_policy_ids" = toset(null) /* of string */
  "service_endpoints" = tolist([])
  "timeouts" = null /* object */
  "virtual_network_name" = "hbtest"
}

terraform plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:

Terraform will perform the following actions:

Plan: 0 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  ~ subnet = {
      ~ service_endpoint_policy_ids                    = null -> []
        # (11 unchanged elements hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by mariodavid** [comment]
@hbuckle I had the same problem. Switching to the latest provider version:

``` 
terraform {
  required_version = ">=1.0.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.65.0"
    }
  }
}
```

the error disappeared. Perhaps this helps you as well.

**Comment by manzurshaikh** [comment]
@mariodavid same error with latest provider

`Error: Cycle: azurerm_subnet.backend, module.storage_bsai.var.vnet_subnet_id (expand), module.storage_bsai.azurerm_storage_account.storageaccount_name, module.storage_bsai.output.id (expand), azurerm_subnet_service_endpoint_storage_policy.stg`

**Comment by tombuildsstuff** [comment]
@manzurshaikh that's a config error - unrelated to this issue where you have/had a circular reference between resources.

@hbuckle since there's a suggestion that this is fixed in the latest provider version - can you confirm if this is now fixed for you?

Thanks!

**Comment by hbuckle** [comment]
I think I just ended up changing the output to only output the properties we needed, so all good so far as I'm concerned.
