### ISSUE TITLE
"for_each" argument value is unsuitable

### ISSUE THREAD

**Issue by Marwen-TAALLAH** [hashicorp/terraform-provider-azurerm#11204]
I have a module in a branch, I can't change in this module, this module has a foreach as follows:
for_each                =  var.m_kv_access_policy

The variable m_kv_access_policy is as follows:
variable "m_kv_access_policy" {
  type = map(object({
    index                   = number
    key_permissions         = list(string)
    secret_permissions      = list(string)
    certificate_permissions = list(string)
  }))
  description = "The map object to configure one or several KeyVault access policy"
  default     = null
}

I'm calling this module from the main.tf of an other project as follows:

module "az-keyvault" {
  source                        = "git::https://<module_in_git>"
  m_environment                 = var.environment
  m_instance                    = var.instance
  .
  .
  .
}

But I'm getting this error:
for_each                = var.m_kv_access_policy
 The given "for_each" argument value is unsuitable: the given "for_each"
argument value is null. A map, or set of strings is allowed.

Any ideas?

**Comment by favoretti** [comment]
You should default your map to an empty map, rather than `null`, that should do the trick.

**Comment by binaryPUNCH** [comment]
I had a similar issue and this fixed it. I guess this issue can be closed.

> You should default your map to an empty map, rather than `null`, that should do the trick.

**Comment by tombuildsstuff** [comment]
Closing per above.
