### ISSUE TITLE
Undefined optional config blocks are ignored -> lost DSC

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform-provider-azurerm#11215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.9
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.54.0
```

### Affected Resource(s)

* `azurerm_app_service`
* potentially all `azurerm_`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "example" {
  name                = var.name
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  # non-relevant settings hidden

  logs {}
}
```

### Expected Behaviour

Terraform detects change in `logs {application_logs {}}` and will plan removal of the configuration, so that the resource state is returned to what is specified in the code (`logs {}` mean logging is desired to be disabled).

### Actual Behaviour

Terraform ignores both `application_logs` and `http_logs` blocks, leaving them configured despite `logs {}`, so the resource is no longer in sync with my code hence no longed in desired state.

If I remove the `logs {}` block from the resource entirely, the plan will ignore also `detailed_error_messages_enabled` and `failed_request_tracing_enabled`.

`terraform state show azurerm_app_service.example` # after resource update via Portal

```hcl
# non-relevant settings hidden
logs {
        detailed_error_messages_enabled = true
        failed_request_tracing_enabled  = true

        application_logs {
            file_system_level = "Error"

            azure_blob_storage {
                level             = "Error"
                retention_in_days = 10
                sas_url           = (sensitive value)
            }
        }

        http_logs {
            azure_blob_storage {
                retention_in_days = 5
                sas_url           = (sensitive value)
            }
        }
    }
```

Plan output:

```hcl
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_app_service.example will be updated in-place
  ~ resource "azurerm_app_service" "example" {
        id                                = "/subscriptions/ssss/resourcegroups/rrrr/providers/Microsoft.Web/sites/app1"
        name                              = "app1"
        # (15 unchanged attributes hidden)
      ~ logs {
          ~ detailed_error_messages_enabled = true -> false
          ~ failed_request_tracing_enabled  = true -> false
            # (2 unchanged blocks hidden)
        }
        # (4 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. Create a simple WebApp (via Terraform or via Portal and import) with all set to default
2. Manually configure App Service logs via Portal.
3. `terraform apply` -> App Service logs remain configured despite not being in your Terraform code

### Important Factoids

There may be a lot more resources impacted than we think there are.

This really now leaves me worried big portions of the DSC we all thought we were doing was actually not DSC!

### References

* #0000

**Comment by Tbohunek** [comment]
I wonder if I'm the only one having the issue, or nobody else noticed it yet.

**Comment by qbikez** [comment]
I noticed same symptomps. This log line might give some clue:

```
2021-09-26T07:22:47.588+0200 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_app_service.example, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .enabled: planned value cty.True for a non-computed attribute
      - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
      - .client_affinity_enabled: planned value cty.False for a non-computed attribute
      - .https_only: planned value cty.False for a non-computed attribute
      - .client_cert_enabled: planned value cty.False for a non-computed attribute
      - .identity: block count in plan (1) disagrees with count in config (0)
      - .logs: block count in plan (1) disagrees with count in config (0)
      - .site_config: block count in plan (1) disagrees with count in config (0)
      - .source_control: block count in plan (1) disagrees with count in config (0)
      - .timeouts: planned for existence but config wants absense
      - .auth_settings: block count in plan (1) disagrees with count in config (0)
```

**Comment by Tbohunek** [comment]
@tombuildsstuff thanks for your comment from the other thread. 
> @Tbohunek `azurerm_app_service` is resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources instead.

This original report is pretty old, so I can't remember which other resources I've seen this with.
I wasn't able to reproduce the issue anymore with `azurerm_linux_web_app`, so I'm closing this. I'll reopen if I come across the same issue again.
