### ISSUE TITLE
kubernetes_cluster: addon_profile.oms_agent.log_analytics_workspace_id - validate casing

### ISSUE THREAD

**Issue by asubmani** [hashicorp/terraform-provider-azurerm#11223]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

*  Terraform v0.14.9
*  provider registry.terraform.io/hashicorp/azuread v1.4.0
*  provider registry.terraform.io/hashicorp/azurerm v2.54.0
*  provider registry.terraform.io/hashicorp/kubernetes v2.0.3
*  provider registry.terraform.io/hashicorp/random v3.1.0
### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
AKSLAWId =  lower(data.azurerm_log_analytics_workspace.AKSLAWS.id)
##tried without `lower`
addon_profile {

    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = var.AKSLAWId
    }


```

### Debug Output
 ```hcl
(16 unchanged attributes hidden)
 ~ addon_profile {
          ~ oms_agent {
              ~ log_analytics_workspace_id = "/subscriptions/c1c3**redacted**96c6/resourceGroups/core-rg/providers/Microsoft.OperationalInsights/workspaces/jb-loga-eus-core-20" -> "/subscriptions/c1c3**redacted**96c6/resourcegroups/core-rg/providers/microsoft.operationalinsights/workspaces/jb-loga-eus-core-20"
                # (2 unchanged attributes hidden)
            }
            # (1 unchanged block hidden)
        }
Plan: 0 to add, 1 to change, 0 to destroy.

```

### Expected Behaviour

Terraform should not count this as a change.

### Actual Behaviour

Regression of #9151 and #10517

### Steps to Reproduce

1. `terraform plan`

### References

* #9151
* #10517

**Comment by stephybun** [comment]
Hi @asubmani, thanks for raising this issue.

It seems the problem is indeed the `lower` function that's applied to the log analytics workspace ID. I was able to reproduce the error with the configuration supplied above, but the issue resolves itself when `lower` is removed. Is there a particular reason why the log analytics workspace ID is being lower cased? And could you please confirm whether you're still facing this issue?

Thanks!

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.

**Comment by asubmani** [comment]
The Log Analytics resource id returned is not consistent. I lower case it to ensure that it is consistent.

Closing.
