### ISSUE TITLE
recover_soft_deleted_key_vaults default value differs from documentation

### ISSUE THREAD

**Issue by kemmemha** [hashicorp/terraform-provider-azurerm#11233]
> recover_soft_deleted_key_vaults - (Optional) Should the azurerm_key_vault, azurerm_key_vault_certificate, azurerm_key_vault_key and azurerm_key_vault_secret resources recover a Soft-Deleted Key Vault/Item? **Defaults to true**

**hashicorp/azurerm v2.52.0**

The documentation states that `recover_soft_deleted_key_vaults ` defaults to true. We tested it with the following provider. The key vault has soft delete and purge protection enabled.

```
provider "azurerm" {
  subscription_id = "XXX"
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}
```

We create a Key Vault with `terraform apply`, add a secret to it and destroy it per `terraform destroy`. Then we do another `terraform apply`. The following exception is thrown: 

> Error: An existing soft-deleted Key Vault exists with the Name "xxx" in the location "westeurope", however automatically recovering this KeyVault has been disabled via the "features" block.

Now we tried the exact same test setup with a different provider setup:

```
provider "azurerm" {
  subscription_id = "XXX"
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
      recover_soft_deleted_key_vaults = true
    }
  }
}
```

We create a new Key Vault per `terraform apply`, add a secret, destroy it per `terraform destroy` and do another `terraform apply` to recover the vault.
Result: Key Vault is recovered and contains the secret.

The code itself states that the default value is true?

```
				Schema: map[string]*schema.Schema{
					"recover_soft_deleted_key_vaults": {
						Type:     schema.TypeBool,
						Optional: true,
					},
```

**Conclusion:**

`recover_soft_deleted_key_vaults ` default value seems to be `false `and not `true `as stated in the documentation

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. The schema you've pasted shows that parameter is optional, but not that it's set to any default value?

**Comment by kemmemha** [comment]
@favoretti oh sorry. This should be the correct code snippet:

```
func expandFeatures(input []interface{}) features.UserFeatures {
	// these are the defaults if omitted from the config <-----
	features := features.Default()

	if len(input) == 0 || input[0] == nil {
		return features
	}

	val := input[0].(map[string]interface{})

	if raw, ok := val["key_vault"]; ok {
		items := raw.([]interface{})
		if len(items) > 0 {
			keyVaultRaw := items[0].(map[string]interface{})
			if v, ok := keyVaultRaw["purge_soft_delete_on_destroy"]; ok {
				features.KeyVault.PurgeSoftDeleteOnDestroy = v.(bool)
			}
			if v, ok := keyVaultRaw["recover_soft_deleted_key_vaults"]; ok {
				features.KeyVault.RecoverSoftDeletedKeyVaults = v.(bool) // <-------
			}
		}
	}
```

**Comment by favoretti** [comment]
@kemmemha Hmm, still not sure I follow, look at [this line](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/features/defaults.go#L8)?

**Comment by myhau** [comment]
I have similar conclusions, I assumed `recover_soft_deleted_key_vaults` is true by default, but it started working only after I set it explicitly.

**Comment by favoretti** [comment]
Hmm, interesting. I'll try to run some tests next week to reproduce.

**Comment by patst** [comment]
I can confirm that we had to set `recover_soft_deleted_key_vaults = true` explicitly as well in order to have secrets recovered.

**Comment by manicminer** [comment]
Thanks for reporting. The default value for this will now be `true` in v3.0, in line with the documentation.
