### ISSUE TITLE
azurerm_web_application_firewall_policy rule_group_override is required despite being documented as optional

### ISSUE THREAD

**Issue by w3bward** [hashicorp/terraform-provider-azurerm#11242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform: 0.14.5
AzureRM Provider: 2.54.0

### Affected Resource(s)

* `azurerm_web_application_firewall_policy`

### Terraform Configuration Files

```hcl
resource "azurerm_web_application_firewall_policy" "external_applications" {
  name                = "${var.environment}ExternalApplications"
  resource_group_name = var.resource_group_name
  location            = var.location

  policy_settings {
    enabled                     = true
    mode                        = "Prevention"
    file_upload_limit_in_mb     = 100
    request_body_check          = true
    max_request_body_size_in_kb = 128
  }

  managed_rules {
    managed_rule_set {
      type    = "OWASP"
      version = "3.0"
      
      rule_group_override {
        rule_group_name = "General"
      }
    }
  }
}
```

### Expected Behaviour

Terraform should have created an WAF policy, and overriden the "General" rule group. According to the documentation, this should be fine.

### Actual Behaviour

Terraform threw an error that the rule_group_override was missing a required argument despite the fact that the ["disabled_rules"](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy#disabled_rules) argument is documented as being an optional argument, and should be optional according to the [ARM documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.network/applicationgatewaywebapplicationfirewallpolicies?tabs=json#managedrulegroupoverride-object) which states that if no rules are specified, then all rules in the group will be disabled.

If I add the disabled_rules argument, then it works, but this is cumbersome when the intention is to disable all rules within a group that contains a large number of rules.

```
Acquiring state lock. This may take a few moments...

Error: Missing required argument

  on policy_externalapplications.tf line 189, in resource "azurerm_web_application_firewall_policy" "external_applications":
 189:       rule_group_override {

The argument "disabled_rules" is required, but no definition was found.

```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
