### ISSUE TITLE
azurerm_application_insights cannot be created

### ISSUE THREAD

**Issue by ksmigiel** [hashicorp/terraform-provider-azurerm#11251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.54.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_application_insights`

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights" "ins" {
  name                            = "ins-${var.deployment_name}  "
  location                        = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  application_type          = "web"
}
```

### Expected Behaviour

Resource should be created without error and subsequent `terraform apply` should not report error either.

### Actual Behaviour

> Error: Error read Application Insights Billing Features "(hidden)  " (Resource Group "(hidden)"): insights.ComponentCurrentBillingFeaturesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Insights/components/(hidden)  ' under resource group '(hidden)' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

What is weird, resource is created after that error, but running again `terraform apply` results in another error:

> Error: A resource with the ID "/subscriptions/(hidden)/resourceGroups/(hidden)/providers/microsoft.insights/components/(hidden) " already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_application_insights" for more information.

### Steps to Reproduce

1. Make main.tf file with azurerm_application_insights resource
2. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
