### ISSUE TITLE
Creating an Azure Function App with a runtime version of ~3 does not create host keys

### ISSUE THREAD

**Issue by Jay-Madden** [hashicorp/terraform-provider-azurerm#11266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.14.8
+ provider registry.terraform.io/hashicorp/azurerm v2.54.0
 ```

### Affected Resource(s)

* `azurerm_function_app`
* `azurerm_data_factory_linked_service_azure_function`
* `azurerm_function_app_host_keys`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "afaxot" {
  name                       = var.xotfunctionappname
  location                   = var.region
  resource_group_name        = var.resgroupname
  app_service_plan_id        = azurerm_app_service_plan.aasxot.id
  storage_account_name       = var.storageaccountname
  storage_account_access_key = data.azurerm_storage_account.sg.primary_access_key
  version                    = "~3"
  depends_on                 = [azurerm_app_service_plan.aasxot]

  # app_settings = {
  #   AzureWebJobsDashboard          = data.azurerm_storage_account.sg.primary_connection_string
  #   AzureWebJobsStorage            = data.azurerm_storage_account.sg.primary_connection_string
  #   BLOB_STORAGE_CONNECTION_STRING = data.azurerm_storage_account.sg.primary_connection_string
  #   CONTAINER_NAME = "afaxot"
  #   FUNCTIONS_EXTENSION_VERSION = "~3"
  #   WEBSITE_HTTPLOGGING_RETENTION_DAYS = "3"
  # }
  
  tags = {
    aa-app-id           = data.azurerm_key_vault_secret.aaappid.value
    aa-application      = var.aaapplication
    aa-costcenter       = data.azurerm_key_vault_secret.aacostcenter.value
    aa-sdlc-environment = var.environment
    aa-security         = var.aasecurity
    aa-vertical         = var.aavertical
  }
}

# Reference host keys of xOvertime XML Function App
data "azurerm_function_app_host_keys" "afaxotkeys" {
  name                = var.xotfunctionappname
  resource_group_name = var.resgroupname
  depends_on          = [azurerm_function_app.afaxot]
}

# Linked Service for xOvertime XML Function App
resource "azurerm_data_factory_linked_service_azure_function" "lsxotfa" {
  name                = var.xotfunctionapplinkedservice
  resource_group_name = var.resgroupname
  data_factory_name   = var.datafactoryname
  url                 = var.xotfunctionappurl
  key                 = data.azurerm_storage_account.sg.primary_access_key
  depends_on          = [azurerm_data_factory.df, azurerm_function_app.afaxot]
}

```

### Debug Output

https://gist.github.com/Jay-Madden/77c0e55fe8bda6ef247ac3c06e75b825

### Expected Behaviour

A function app with runtime version of ~3 was created with appropriate app keys

referenced here https://stackoverflow.com/questions/64713697/azure-function-host-keys-not-created-with-terraform

**Comment by Jay-Madden** [comment]
Update for anyone else that is having this bug: The app keys are being created in blob storage but the generated Function App cant find them. We had to delete the old blob containing the encrypted keys and add this to the function app App Settings 
`CONTAINER_NAME = "azure-webjobs-secrets" `

The entire app_settings are as follows 
```
   app_settings = {
     AzureWebJobsDashboard          = data.azurerm_storage_account.sg.primary_connection_string
     AzureWebJobsStorage            = data.azurerm_storage_account.sg.primary_connection_string
     CONTAINER_NAME = "azure-webjobs-secrets"
     FUNCTIONS_EXTENSION_VERSION = "~3"
     WEBSITE_HTTPLOGGING_RETENTION_DAYS = "3"
   }
``` This fixed it for us

**Comment by brianharwell** [comment]
Yes, this worked for me as well. Can the documentation be updated to reflect this?

**Comment by StefanSchoof** [comment]
this sounds similar to #16599

**Comment by mzaatar** [comment]
Thanks everyone for the useful thread. 

I'm having the same issue with my Bicep templates. My Function WebApp doesn't create default keys and cannot create dynamic one. 

@Saj1234 could you elaborate more on what did you do to make your templates create the Function keys for you?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
