### ISSUE TITLE
azurerm_app_service_slot: missing config arguments

### ISSUE THREAD

**Issue by ppanyukov** [hashicorp/terraform-provider-azurerm#11262]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.0
+ provider registry.terraform.io/hashicorp/azurerm v2.54.0
```

### Affected Resource(s)

* `azurerm_app_service_slot`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_slot" "example" {
  app_service_name    = "example"
  name                = "myslot"
  location            = "westeurope"
  resource_group_name = "example"
  app_service_plan_id = data.azurerm_app_service_plan.example.id

  # Slots don't have client_cert_enabled attribute but they should.
  client_cert_enabled = false

  # Slots don't have separate source_control block but they should.
  source_control {
    repo_url           = "https://example.com"
    branch             = "master"
    manual_integration = true
    rollback_enabled   = false
  }
}
```

### Expected Behaviour

Looks like slots should have both `client_cert_enabled` and `source_control`, at least in Portal I see both separate client cert config and source control config for slots, and they are separate from the "main app". 

We should be able to configure these in terraform too, is this an omission?

### Actual Behaviour

```
$ tf validate

Error: Unsupported argument

  on REDACTED.tf line 127, in resource "azurerm_app_service_slot" "REDACTED":
 127:   client_cert_enabled = false

An argument named "client_cert_enabled" is not expected here.


Error: Unsupported block type

  on REDACTED.tf line 179, in resource "azurerm_app_service_slot" "REDACTED":
 179:   source_control {

Blocks of type "source_control" are not expected here.
```

**Comment by wirdatrd** [comment]
I am getting that error on the azurerm_app_service block as well.  Is there a bug in the documentation specifying which block client_cert_enabled = <bool> is supposed to be in?

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
