### ISSUE TITLE
azurerm_iothub_dps always forced to be recreated 

### ISSUE THREAD

**Issue by dharanidhar-m** [hashicorp/terraform-provider-azurerm#11272]
`**Terraform` (and AzureRM Provider) Version**
Using Terraform v0.12.29
Using provider v2.53.0

**Affected Resource(s)**
azurerm_iothub_dps

**Terraform Configuration Files**

Here is the terraform content

# Iot hub shared access policy
data "azurerm_iothub_shared_access_policy" "aih-sap-owner" {
    name                = "iothubowner"
    resource_group_name = azurerm_resource_group.rg.name
    iothub_name         = azurerm_iothub.iah.name
}

#  Device provisioning service
resource "azurerm_iothub_dps" "dps" {
  name                = "${var.subscription-prefix}-conm-${var.environment}-${var.location-shortcut}-deviceprovision-dps"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku {
    name     = var.dpssku
    capacity = "1"
  }
  linked_hub {
        connection_string = data.azurerm_iothub_shared_access_policy.aih-sap-owner.primary_connection_string
        location = azurerm_iothub.iah.location
        apply_allocation_policy = true        
  }
  lifecycle {
      ignore_changes = [
        tags
      ]
    }
  
  tags = {
      environment = var.environment
  }
}

**Expected Behavior**

- If no changes are made to the azurerm_iothub_dps resource, Terraform should not detect changes between two terraform apply.

- whenver we apply the terraform the dps should not be re-created and it should be the same

**Actual Behavior**

Whenver we apply terraform the dps resource has been destroying and re-creating again even though there are no changes to the dps resource, as this is the case we are loosing all the changes and individual enrollments created in the dps whenever we apply terraform during deployment.

Steps to Reproduce
terraform apply
you should see the unnecessary destroying and re-create of dps resource.

**Comment by jthin** [comment]
I have the same problem with Terraform 0.15.x and ARM provider 2.61.
Re-creation seems to be triggered by `connection_string` in `linked_hub`.

**Comment by yothoon** [comment]
Same problem here, changing linked IoT hub forced whole DPS re-creation. From Azure portal it can be changed without need to re-create DPS.

**Comment by svenna** [comment]
yeah i found that the code clearly states that changing the above should force recreate. https://github.com/hashicorp/terraform-provider-azurerm/issues/6720#issuecomment-931308795
i think it is wrong as it is only references those values and they should be possible change, and of course adding/removing iothubs without replacing the dps.

i have never done a patch to terraform but i think this should be an easy fix :)
