### ISSUE TITLE
Panic when upgrading from 2.41.0 to 2.42.0

### ISSUE THREAD

**Issue by bm77525-kr** [hashicorp/terraform-provider-azurerm#11283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.13.0
AzureRM: 2.42.0

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

# Create the Azure Key Vault
resource "azurerm_key_vault" "key-vault" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name

  enabled_for_deployment          = var.enabled_for_deployment
  enabled_for_disk_encryption     = var.enabled_for_disk_encryption
  enabled_for_template_deployment = var.enabled_for_template_deployment
  soft_delete_enabled             = true
  purge_protection_enabled        = true
  soft_delete_retention_days      = 90

  tenant_id = data.azurerm_client_config.current.tenant_id
  sku_name  = var.sku_name
  tags      = var.tags

  network_acls {
    default_action = "Allow"
    bypass         = "AzureServices"
  }
}
```

### Debug Output

https://gist.github.com/bm77525-kr/d4160488ddb07a8093d7c561b9991387

### Expected Behaviour

There should be no state change, given that soft delete is already enabled with retention days set, and there should be no crash.

### Actual Behaviour

Terraform crashes

### Steps to Reproduce

1. Upgrade provider to 2.41.0 to 2.42.0
2. `terraform apply`

### Important Factoids

I realize there were breaking changes for keyvault in this release, but this keyvault already had soft delete enabled with retention days set, so I was under the impression that there should be no issue upgrading.

**Comment by tombuildsstuff** [comment]
👋 

Unfortunately the Azure API force-enabled Soft Delete for all Key Vault resources - however newer versions of the Provider support this implementation. I'm going to close this out since I believe this has been fixed in newer versions of the Azure Provider, but if your still seeing this issue when using the latest version of the Azure Provider please feel free to open a new issue and we'll take another look.

Thanks!
