### ISSUE TITLE
`storage_authentication_type` in `azure_media_services_account` does not work in combination with Managed Identity

### ISSUE THREAD

**Issue by FreyMo** [hashicorp/terraform-provider-azurerm#11296]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.9
azurerm v2.55.0

### Affected Resource(s)

* `azurerm_media_services_account`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "2.55.0"
    }
    azuread = {
      version = "1.3.0"
    }
  }
}

provider "azurerm" {
  features { }
}

locals {
  location = "westeurope"
  name     = "reproduce"
}

resource "azurerm_resource_group" "this" {
  name     = "rg-${local.name}"
  location = local.location
}

resource "azurerm_storage_account" "this" {
  name                = "sa${local.name}"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_role_assignment" "storage_blob_data_contributor" {
  scope                = azurerm_storage_account.this.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_media_services_account.this.identity[0].principal_id
}

resource "azurerm_media_services_account" "this" {
  name                = "ams${local.name}"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  storage_account {
    id         = azurerm_storage_account.this.id
    is_primary = true
  }

  identity {
    type = "SystemAssigned"
  }

  storage_authentication_type = "ManagedIdentity"
}
```

### Error Output

```
Error: creating Media Service: (Name "amsreproduce" / Resource Group "rg-reproduce"): media.MediaservicesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The storage authentication property cannot be set to ManagedIdentity before the Managed Identity has been created for the media account." Details=[{"code":"StorageManagedIdentityAuthenticationRequiresManagedIdentity","message":"The storage authentication property cannot be set to ManagedIdentity before the Managed Identity has been created for the media account."}]

  on main.tf line 41, in resource "azurerm_media_services_account" "this":
  41: resource "azurerm_media_services_account" "this" {
```

### Expected Behaviour

An Azure Media Services Account with Managed Identity access to its primary storage account should be created.

### Actual Behaviour

See [Error Output](#error-output). No Media Services Account gets created.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Applying this without the `storage_authentication_type` and adding it in a second `apply` works as expected. This is however not a practical solution. The order of creating the Managed Identity and settings the `storage_authentication_type` needs to be switched.

### References

* #11213 fixed the wrong strings for `storage_authentication_type` but does not address this follow up problem

**Comment by jcanizalez** [comment]
Hello,
At this time, the process to enable managed identity in multimedia services is:

1. Create a media service account with identity type ** SystemAssigned **
2. Map "Storage Blob Data Contributor" to the managed identity created in step 1 to the Storage account
3. Change the Storage Authentication Type property for the created media service account to ** ManagedIdentity **

I think I can fix this, so if you set identity.type = "SystemAssigned" and storage_authentication_type = "ManagedIdentity"

I could include in the code the logic to automatically create the role assignment (step 2) but I'm not sure if this is good practice, because basically the role assignment would not be explicitly declared in the Terraform code. 

@tombuildsstuff do you think is a valid solution? Or if someone has a better idea

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
