### ISSUE TITLE
azurerm_kubernetes_cluster crashes with index error

### ISSUE THREAD

**Issue by apeschel** [hashicorp/terraform-provider-azurerm#11299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.0.3
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

https://gist.github.com/apeschel/e9c3a95028eb91846c402abda85a0378

Encrypted using the Hashicorp GPG key.

### Debug Output

https://gist.github.com/apeschel/a7808ea798f79d57057933cc215a2aad

### Panic Output

Can't seem to find this file, if it was created.

### Expected Behaviour

Apply runs

### Actual Behaviour

Apply crashes

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I tried importing some existing Azure resources cluster, and I get this error when running apply. I've managed to narrow it down to the AKS cluster resource.

### References

* #0000

**Comment by apeschel** [comment]
Taking a look at the trace logs and cross referencing the code, it seems like this line is the most likely culprit:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L937

**Comment by apeschel** [comment]
This is definitely an issue with the line I pointed at -- I added a `service_principal` block with valid credentials to the resource definition, and the apply worked on the AKS cluster. So I think the scenario to trigger this bug is as follows:

* Define an AKS resource that does not have the service principal field set.
* Import an existing AKS cluster, which has a service principal set.
* Run terraform apply -- the plan will show removing the service principal.
* Approve the plan and a crash ensues.

**Comment by apeschel** [comment]
I suspect this may be because the terraform import command can't actually import the full service principal information from the Azure API, for security reasons.

**Comment by lonegunmanb** [comment]
Hi @apeschel ,

I've tried to reproduce this panic but I failed, here's my procedures:

1. Create an aks with `service_principal`, then apply:

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "f11299"
  location = "West Europe"
}
resource "azurerm_kubernetes_cluster" "example" {
  name                = "f11299"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

#  identity {
#    type = "SystemAssigned"
#  }
  service_principal {
    client_id     = data.azurerm_client_config.current.client_id
    client_secret = "############################"
  }

  tags = {
    Environment = "Test"
  }
}

output aks_id{
  value = azurerm_kubernetes_cluster.example.id
}
output "rg_id" {
  value = azurerm_resource_group.example.id
}
```

The `terraform apply` was a success.

2. Copy and paste code to a new folder, with tiny modification:

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "f11299"
  location = "West Europe"
}
resource "azurerm_kubernetes_cluster" "example" {
  name                = "f11299"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
 # service_principal {
#    client_id     = data.azurerm_client_config.current.client_id
#    client_secret = "############################"
  }

  tags = {
    Environment = "Test"
  }
}
```

This time I used `identity` rather than `service_principal`.

3. Import terraform resources in the second folder

The import was a success.

4. Run `terraform apply`

It worked fine.

Would you please give a procedure that can reproduce this panic, with latest plugin version? Thanks!

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
