### ISSUE TITLE
Support for custom hostname binding for slots in web apps

### ISSUE THREAD

**Issue by andyadamides** [hashicorp/terraform-provider-azurerm#11295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description 
It would be great to enable custom hostname binding for slots within web apps. Currently this is only possible for the default production slot and there isn't a `slot` option, unlike the `az cli` [counterpart](https://docs.microsoft.com/en-us/cli/azure/webapp/config/hostname?view=azure-cli-latest#az_webapp_config_hostname_add-examples) .

### New or Affected Resource(s)

* azurerm_app_service_custom_hostname_binding

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_custom_hostname_binding" "example" {
  hostname            = "www.mywebsite.com"
  app_service_name    = azurerm_app_service.example.name
  app_service_slot    = "test-slot"
  resource_group_name = azurerm_resource_group.example.name
}
```

### References

* https://docs.microsoft.com/en-us/cli/azure/webapp/config/hostname?view=azure-cli-latest#az_webapp_config_hostname_add-examples
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_custom_hostname_binding

**Comment by haraldatbmw** [comment]
@katbyte Do you think its better to create a new resource named `azurerm_app_service_slot_custom_hostname_binding` or extend the exising resource `azurerm_app_service_custom_hostname_binding` to support both app-service and slots?

**Comment by tombuildsstuff** [comment]
@haraldatbmw apologies just seen your question - in general we'd tend to prefer a separate resource for a slot binding here, since it's possible that the requirements for that could be different (for example that it could be copied from the original app service, or to multiple slots) over time.

**Comment by haraldatbmw** [comment]
@tombuildsstuff I created a PR with a separate resource for the slot binding.
