### ISSUE TITLE
Error: Error creating/updating Automation Runbook "AzureVMStartStop" (Account "test-autoacc" / Resource Group "app-labtest"): automation.RunbookClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Unable to read content link."

### ISSUE THREAD

**Issue by sahityamalepati** [hashicorp/terraform-provider-azurerm#11293]
I have tried creating Automation Account in Azure but while creating Runbook i am experiencing below error.

data "azurerm_client_config" "example" {}

data "azurerm_resource_group" "resource_group_name" {
  name = var.resource_group_name
}

data "azurerm_storage_container" "blobstorage" {
  name                 = "vmstartstop"
  storage_account_name = var.storage_account
}

resource "azurerm_storage_blob" "script" {
  name                   = "run-vmStartStopParent.ps1"
  storage_account_name   = var.storage_account
  storage_container_name = data.azurerm_storage_container.blobstorage.name
  type                   = "Block"
  source                 = "../TerraformModules/ScriptUpload/run-vmStartStopParent.ps1"
}
resource "azurerm_automation_account" "AppAutomation" {
  name                = "${var.appPrefix}-autoacc"
  location            = var.location
  resource_group_name = var.resource_group_name
  sku_name            = "Basic"
  tags = {
    "uai" = "$(var.uai)"
    "env" = "$(var.env)"
  }
}

resource "azurerm_automation_connection" "example" {
  name                    = "${var.appPrefix}-connection"
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.AppAutomation.name
  type                    = "AzureServicePrincipal"
  depends_on              = [azurerm_automation_account.AppAutomation]

  values = {
    "ApplicationId" : var.Applicationid,
    "TenantId" : data.azurerm_client_config.example.tenant_id,
    "SubscriptionId" : data.azurerm_client_config.example.subscription_id,
    "CertificateThumbprint" : "B05CCBDE46799D6FEED5BFE9C4C3276869566830"
  }
}

resource "azurerm_automation_runbook" "AppAutomation" {
  name                    = "AzureVMStartStop"
  location                = var.location
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.AppAutomation.name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "This is an example runbook"
  runbook_type            = "PowerShellWorkflow"
  depends_on              = [azurerm_automation_account.AppAutomation]
  publish_content_link {
    uri = "https://labstgtest.blob.core.windows.net/vmstartstop/run-vmStartStopParent.ps1"
  }
}

resource "azurerm_automation_schedule" "one-time" {
  name                    = "${var.appPrefix}-one-time"
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.AppAutomation.name
  frequency               = "OneTime"
  depends_on              = [azurerm_automation_account.AppAutomation, azurerm_automation_runbook.AppAutomation]

  // The start_time defaults to now + 7 min
}

resource "azurerm_automation_schedule" "hour" {
  name                    = "${var.appPrefix}-hour"
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.AppAutomation.name
  frequency               = "Hour"
  interval                = 2
  depends_on              = [azurerm_automation_account.AppAutomation, azurerm_automation_runbook.AppAutomation]

}

// Schedules the example runbook to run on the hour schedule
resource "azurerm_automation_job_schedule" "AppAutomation" {
  resource_group_name     = var.resource_group_name
  automation_account_name = azurerm_automation_account.AppAutomation.name
  runbook_name            = azurerm_automation_runbook.AppAutomation.name
  schedule_name           = azurerm_automation_schedule.hour.name
  depends_on              = [azurerm_automation_account.AppAutomation, azurerm_automation_runbook.AppAutomation]
}

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
