### ISSUE TITLE
r/api_management(_custom_domain): support for key_vault_certificate_id

### ISSUE THREAD

**Issue by NeuroticStar** [hashicorp/terraform-provider-azurerm#11309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_api_management, azurerm_api_management_custom_domain

### Potential Terraform Configuration

First and foremost, while mapping a custom domain to api managemetn developer and portal, I noticed few glitches with the implementation.

1. key_vault_id under the management, developer, scm blocks should be renamed to key_vault_certificate_id
2. As Microsoft is planning to deprecate the usage of importing certificates in key vault secrets, I would like if we provide an ability to import the certificate from azurerm_key_vault_certificate module.

**Comment by oWretch** [comment]
Might be worth looking at for provider v3? #14193

**Comment by tombuildsstuff** [comment]
Released [in v3.4.0](https://github.com/hashicorp/terraform-provider-azurerm/issues/11309#issuecomment-1105896447)
