### ISSUE TITLE
azurerm_policy_set_definition -> policy_definition_reference -> parameter_values are nulled with TF >=14.0

### ISSUE THREAD

**Issue by gettek** [hashicorp/terraform-provider-azurerm#11327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.9
AzureRM 2.50.0

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
  policy_definition_reference {
    parameter_values = jsonencode({
      approvedExtensions = { value = "[parameters('listOfApprovedVMExtensions')]" }
    })
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/c0e996f8-39cf-4af9-9f45-83fbde810432"
    reference_id         = "CISv110x7x4"
  }

  policy_definition_reference {
    parameter_values = jsonencode({
      listOfLocations   = { value = "[parameters('listOfRegionsWhereNetworkWatcherShouldBeEnabled')]" },
      resourceGroupName = { value = "[parameters('NetworkWatcherResourceGroupName')]" }
    })
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/b6e2945c-0b7b-40f5-9233-7a5323b5cdc6"
    reference_id         = "CISv110x6x5"
  }
```

### Expected Behaviour

On Plan/Apply terraform should only execute changes reflected in code

### Actual Behaviour

Not sure if this is definitely provider related but since `Terraform >=14.0` all `parameter_values` within the `policy_definition_reference` blocks are nulled out, as in the below `plan` output:

```hcl
  # azurerm_policy_set_definition.cis_benchmark will be updated in-place
  ~ resource "azurerm_policy_set_definition" "cis_benchmark" {
        id                    = "/providers/Microsoft.Management/managementgroups/***/providers/Microsoft.Authorization/policySetDefinitions/cis_benchmark"
        name                  = "cis_custom_benchmark"
        # (8 unchanged attributes hidden)

      ~ policy_definition_reference {
          ~ parameters           = {
              - "approvedExtensions" = "[parameters('listOfApprovedVMExtensions')]" -> null
            }
            # (4 unchanged attributes hidden)
        }
      ~ policy_definition_reference {
          ~ parameters           = {
              - "listOfLocations"   = "[parameters('listOfRegionsWhereNetworkWatcherShouldBeEnabled')]" -> null
              - "resourceGroupName" = "[parameters('NetworkWatcherResourceGroupName')]" -> null
            }
            # (4 unchanged attributes hidden)
        }
        # (68 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform plan`

**Comment by paveldokov** [comment]
I can confirm this is still an issue with:
* azurerm provider 2.62.1
* Terraform 1.0.0
Are there plans to address this?

**Comment by sraddhananda** [comment]
"V" should be capital in "defaultValue" within your parameters. 
I literally walked the same path.

**Comment by Satak** [comment]
We have the same issue. Any plans of fixing this?

**Comment by wplj** [comment]
In my case I explicitly specify an empty list as a parameter (`[]`), but Terraform converts it to `null` and writes to the state file. After the first `apply` I run `plan` again, and provider call returns an empty list type for a particular attribute, Terraform compares it to the type it stored and finds the difference (`~ null -> []`), obviously, so it falsely detects a change when no changes are made. You have to run `apply` two times. 100% reproducible with `Terraform 1.0.4` and `azurerm` provider `2.73.0`.

**Comment by magodo** [comment]
@gettek

I've used following cfg trying to reproduce this issue, but a `plan` following a `apply` prints out no diff:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_policy_definition" "test" {
  name         = "acctestpol-mgd-test"
  policy_type  = "Custom"
  mode         = "All"
  display_name = "acctestpol-mgd-test"

  policy_rule = <<POLICY_RULE
	{
    "if": {
      "not": {
        "field": "location",
        "in": "[parameters('allowedLocations')]"
      }
    },
    "then": {
      "effect": "audit"
    }
  }
POLICY_RULE

  parameters = <<PARAMETERS
  {
    "allowedLocations": {
      "type": "Array",
      "metadata": {
        "description": "The list of allowed locations for resources.",
        "displayName": "Allowed locations",
        "strongType": "location"
      }
    }
  }
PARAMETERS
}
resource "azurerm_policy_set_definition" "test" {
  name         = "acctestPolSet-mgd-test"
  policy_type  = "Custom"
  display_name = "acctestPolSet-display-mgd-test"

  parameters = <<PARAMETERS
    {
        "allowedLocations": {
            "type": "Array",
            "metadata": {
                "description": "The list of allowed locations for resources.",
                "displayName": "Allowed locations",
                "strongType": "location"
            }
        }
    }
PARAMETERS

  policy_definition_reference {
    policy_definition_id = azurerm_policy_definition.test.id
    parameter_values = jsonencode({
      allowedLocations = { value: "[parameters('allowedLocations')]"}
    })
  }
}
```

I've run the test either:

1. Using the latest terraform version v1.0 to do both `apply` and `plan`
2. Using the terraform v0.13.0 to do `apply`, then use the v1.0 to do `plan`

The provider version under used is the latest v2.84.0. Note that there is no big change in this policy set definition since v2.50.0.

Also noted that the description of this issue has shown, the diff is complaining that the `parameters` (rather than the `parameter_values`) inside the `policy_definition_reference` is going to change from some value ot `null`. This shouldn't happen unless you have specified something to the `parameters` (e.g. explicitly setting it to `null`).

That said, would you please kindly provide a full terraform configuration together with the  detailed steps (e.g. which TF version is used to run `apply`/`plan`) so that I can go on investigating this issue?

**Comment by matthorgan** [comment]
We've been battling with the same issue on our definition sets but have just realised what's causing it. We had some legacy lifecycle code in our azurerm_policy_set_definition resource because many moons ago the definition set always used to say it had changed:

```
  lifecycle {
    ignore_changes = [metadata] // hacky hack hack, always says it has changed!
  }
  ```

@magodo using your example with the lifecycle block, I can consistently reproduce the error. I'm not sure how this lifecycle block correlates with the empty parameters that we've been seeing but we can now get rid of that old lifecycle block and our code works 👍

**Comment by magodo** [comment]
@matthorgan Thanks to provide me the repro steps. With some digging in, it appears to be a core issue (hashicorp/terraform#29921). I've also provide a naive fix for that.

**Comment by magodo** [comment]
hashicorp/terraform#29921 has been closed and I've confirmed with that the issue as described in https://github.com/hashicorp/terraform-provider-azurerm/issues/11327#issuecomment-965574092 is addressed.

I'm gonna close issue for now. If the issue still exists, feel free to reopen this issue.
