### ISSUE TITLE
role_definition_id usage appears incorrectly stated in Terraform Doc

### ISSUE THREAD

**Issue by paultath-parsable** [hashicorp/terraform-provider-azurerm#11331]
Reviewing the argument [reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment) for using role_definition_id 
 in role_assignment, it states the argument is "optional" same as in [code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/36b13c7dc9e78d10d3cda3d63eee69e3b14f2f0b/azurerm/internal/services/authorization/role_assignment_resource.go#L67)

When not using this argument reference in terraform the following error occurs "Error: either role_definition_id or role_definition_name needs to be set" 

Viewing the source code from [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/36b13c7dc9e78d10d3cda3d63eee69e3b14f2f0b/azurerm/internal/services/authorization/role_assignment_resource.go#L130-L153) seems that this is required? Please correct if this is the case.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in an older version of the provider which are no longer actively maintained.
If this is still an issue with the 4.x version of the provider please do let us know by opening a new issue, thanks!
