### ISSUE TITLE
Support for EnableLiveTrace feature in azurerm_signalr_service

### ISSUE THREAD

**Issue by bm77525-kr** [hashicorp/terraform-provider-azurerm#11353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, manually enabling the "Enable Live Trace" feature for a terraform managed signalR resource outside of terraform (via the Azure portal) causes it to try and revert the change on the next plan/apply:

```
resource "azurerm_signalr_service" "signalr" {

        # (10 unchanged attributes hidden)


      - features {
          - flag  = "EnableLiveTrace" -> null
          - value = "False" -> null
        }

        # (5 unchanged blocks hidden)
    }
```

Reverting the change is expected, but it attempts to revert it to `null`, so no matter if it's enabled or disabled in the portal (value `True` or `False`), it always tries to set the feature to `null`. It doesn't appear to cause any issue in the `apply`, but is a minor annoyance in that there will always be a diff and attempted resource change Adding the `EnableLiveTrace` to the resource doesn't appear to be supported:

```
Error: expected features.1.flag to be one of [EnableMessagingLogs EnableConnectivityLogs ServiceMode], got EnableLiveTrace
│
│   on resources-functions.tf line 113, in resource "azurerm_signalr_service" "signalr":
│  113: resource "azurerm_signalr_service" "signalr" {
```

### New or Affected Resource(s)

* azurerm_signalr_service

### Potential Terraform Configuration

```hcl
resource "azurerm_signalr_service" "signalr" {

...

      features {
          flag  = "EnableLiveTrace"
          value = "True"
      }

...

}
```

**Comment by trennepohl** [comment]
Basically it's missing an enum in the features validations and the azure-go-sdk for the api `2020-05-01` 
I've made a simple fix locally and got it to work as expected.
https://github.com/trennepohl/terraform-provider-azurerm/commit/86dcda4394ba5b1553ce6b5f8c28ac0ebe0c62d1

Problem is, it's a bit confusing where I should submit a PR to get this updated, there are 3 other repos mentioned in the this Readme https://github.com/Azure/azure-sdk-for-go/blob/master/CONTRIBUTING.md

**Comment by Tiduster** [comment]
Hi !
This issue is a bit annoying because on our instance, each time we apply, terraform detect some changes in the feature flags:

```
  # azurerm_signalr_service.this will be updated in-place
  ~ resource "azurerm_signalr_service" "this" {
        id                          = "/subscriptions/***
        name                        = "sigr-dev-cnto-indigo"
        tags                        = {}
        # (10 unchanged attributes hidden)


      - features {
          - flag  = "EnableLiveTrace" -> null
          - value = "False" -> null
        }

        # (5 unchanged blocks hidden)
    }

```

@trennepohl: As you said, to fix the issue you change `azurerm/internal/services/signalr/signalr_service_resource.go `

```
These generated packages depend on the HTTP client implemented at Azure/go-autorest. Therefore when contributing, please make sure you do not change anything under the services directory.
```

Can someone point us in the right direction?

Much appreciated.

**Comment by trennepohl** [comment]
Sure, I even asked in the #azure-sdk-for-go channel in Slack.

looks like the right place to submit a fix would be https://github.com/Azure/azure-rest-api-specs/blob/master/specification/signalr/resource-manager/Microsoft.SignalRService/stable/2020-05-01/signalr.json

But as you can see  Joel recommended opening an issue.

![image](https://user-images.githubusercontent.com/12124856/125069459-0efc8800-e0b7-11eb-8609-2f44e81a9b2b.png)

**Comment by daojah** [comment]
@trennepohl  hello! 

Your link above not working anymore - https://github.com/trennepohl/terraform-provider-azurerm/commit/86dcda4394ba5b1553ce6b5f8c28ac0ebe0c62d1

Could you please share how you fixed it?

**Comment by trennepohl** [comment]
@daojah sorry I deleted the fork as the real fix involves a bunch..

Please keep in mind that the solution below is not the best way to go, the best way to go would be a new version of the azure-go-sdk and a new provider version, but as mentioned in the comments above it depends from [this file](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/signalr/resource-manager/Microsoft.SignalRService/stable/2020-05-01/signalr.json) being updated.

However, if you want to have your own custom version of azure-sdk-for-go and terraform you can just add [one more constant here](https://github.com/Azure/azure-sdk-for-go/blob/e95f324add5acb64cf2e15eb7f657e9472731de5/services/signalr/mgmt/2020-05-01/signalr/enums.go#L27-L34)

and then add the newly created constant to this function [return here](https://github.com/Azure/azure-sdk-for-go/blob/e95f324add5acb64cf2e15eb7f657e9472731de5/services/signalr/mgmt/2020-05-01/signalr/enums.go#L38)

**Comment by drdamour** [comment]
@thiagocaiubi did u open an issue for signalr.json?

**Comment by thiagocaiubi** [comment]
> @thiagocaiubi did u open an issue for signalr.json?

Hey @drdamour, I think you meant @trennepohl. 👍

**Comment by joshjohanning** [comment]
> Hi ! This issue is a bit annoying because on our instance, each time we apply, terraform detect some changes in the feature flags:
> 
> ```
>   # azurerm_signalr_service.this will be updated in-place
>   ~ resource "azurerm_signalr_service" "this" {
>         id                          = "/subscriptions/***
>         name                        = "sigr-dev-cnto-indigo"
>         tags                        = {}
>         # (10 unchanged attributes hidden)
> 
> 
>       - features {
>           - flag  = "EnableLiveTrace" -> null
>           - value = "False" -> null
>         }
> 
>         # (5 unchanged blocks hidden)
>     }
> ```
> 
> @trennepohl: As you said, to fix the issue you change `azurerm/internal/services/signalr/signalr_service_resource.go ` But the documentation you linked says:
> 
> ```
> These generated packages depend on the HTTP client implemented at Azure/go-autorest. Therefore when contributing, please make sure you do not change anything under the services directory.
> ```
> 
> Can someone point us in the right direction?
> 
> Much appreciated.

@For the instance Azure SignalR service I created through the portal and imported into my Terraform state, I had the same issue as you, every time I ran a plan it tried to drop the `EnableLiveTrace` feature.

```
>       - features {
>           - flag  = "EnableLiveTrace" -> null
>           - value = "False" -> null
>         }
```

For the Azure SignalR resource I created via Terraform natively, it was not part of my subsequent plans.

My solution was to taint and re-create the resource that was originally created in the portal. 

My terraform:

```terraform
resource "azurerm_signalr_service" "example" {
  name                                 = "example"
  location                             = var.location
  resource_group_name                  = azurerm_resource_group.app.name

  sku = {
    name     = "Standard_S1"
    capacity = 1
  }

  cors = {
    allowed_origins = ["*"]
  }

  features = {
      flag  = "EnableConnectivityLogs"
      value = "True"
    },
    {
      flag  = "EnableMessagingLogs"
      value = "False"
    },
    {
      flag  = "ServiceMode"
      value = "Default"
    },

  tags = var.tags
}
```

**Comment by drdamour** [comment]
yeah there's some secondary bug here where it defaults those to null, but the current state if ever touched (like you enabled then disabled something) will make it false..and terraform tries to go from false to null, but the azure rm api seems to just ignore the null and leave it as false.  rather annoying
