### ISSUE TITLE
Terraform Crash importing Azure Data Factory Linked Service (File Storage)

### ISSUE THREAD

**Issue by Robinson308** [hashicorp/terraform-provider-azurerm#11354]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.14.9
AzureRM Provider version v2.54.0

### Affected Resource(s)

azurerm_data_factory_linked_service_azure_file_storage

### Terraform Configuration Files

```
resource "azurerm_data_factory" "myDataFactory" {
  name                   = "myDataFactory"
  resource_group_name    = azurerm_resource_group.myResourceGroup.name
  location               = azurerm_resource_group.myResourceGroup.location
  public_network_enabled = false
  tags = {
    environment = "sample"
  }
}

resource "azurerm_data_factory_linked_service_azure_file_storage" "myDataFactory_AzureFileStorage" {
  name                = "AzureFileStorage"
  resource_group_name    = azurerm_resource_group.myResourceGroup.name
  data_factory_name   = azurerm_data_factory.myDataFactory.name
  connection_string   = azurerm_storage_account.myStorageAccount.primary_connection_string
}
```

### Panic Output

[crash.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/6326417/crash.log)

### Expected Behaviour

Should have imported Linked Service into state file

### Actual Behaviour

Error: The terraform-provider-azurerm_v2.54.0_x5.exe plugin crashed!

### Steps to Reproduce

```
terraform import azurerm_data_factory_linked_service_azure_file_storage.myDataFactory_AzureFileStorage /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MyResourceGroup/providers/Microsoft.DataFactory/factories/myDataFactory/linkedServices/AzureFileStorage
```

**Comment by pguitard** [comment]
Hi @Robinson308, the import command works with a similar configuration with azure_rm v2.68. The issue I have is when I apply the linked service, the `connection_string` isn't mapped properly and end up into the `userId` property of the linked service (accordingly to the code I see in [data_factory_linked_service_azure_file_storage_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/internal/services/datafactory/data_factory_linked_service_azure_file_storage_resource.go), line 176. Have you experienced this?

**Comment by Robinson308** [comment]
I'm just revisiting this with azure_rm v2.73. I no longer get the crash.
I'm still experimenting with combinations of connection string & key vault secrets.

**Comment by pguitard** [comment]
Thanks for the update @Robinson308, I've submitted a bug report regarding the connection string issue (don't hesitate to up-vote! ;o) ): https://github.com/hashicorp/terraform-provider-azurerm/issues/13063

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
