### ISSUE TITLE
Unable to create Private endpoints for several resources

### ISSUE THREAD

**Issue by vishnu-anil** [hashicorp/terraform-provider-azurerm#11377]
Based on the documentation from Azure it says to use the sub resource name "_namespace_" FOR "**Eventhub**", "**Notification hub**", "**Service bus**"
https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview

I followed https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint

However eventhough i have provided the subresourcename in Terraform as "namespace" I still get the below error saying " _invalid resource type_"

`Failure sending request: StatusCode=400 -- Original Error: Code="InvalidPrivateLinkServiceIdType" Message="Private link service Id /subscriptions/asdlkfjxscvklndfad878swd7643we4231a/resourceGroups/Mynew-Test-RG/providers/Microsoft.NotificationHubs/namespaces/notification-test/notificationHubs/notification-test has an invalid resource type. 
Permitted type(s): Microsoft.DocumentDB/databaseAccounts, Microsoft.Sql/servers, Microsoft.Network/privateLinkServices, Microsoft.Web/sites, Microsoft.Web/hostingEnvironments, Microsoft.Storage/storageAccounts, Microsoft.DBforPostgreSQL/servers, Microsoft.DBforMySQL/servers, Microsoft.DBforMariaDB/servers, Microsoft.KeyVault/vaults, Microsoft.Synapse/workspaces, Microsoft.AppConfiguration/configurationStores, Microsoft.Search/searchServices, Microsoft.ContainerService/managedClusters, Microsoft.Devices/IotHubs, Microsoft.Cache/Redis, Microsoft.SignalRService/SignalR, Microsoft.MachineLearningServices/workspaces, Microsoft.Batch/batchAccounts, Microsoft.ContainerRegistry/registries, Microsoft.RecoveryServices/vaults, Microsoft.EventGrid/topics, Microsoft.EventGrid/domains, Microsoft.EventHub/namespaces, Microsoft.ServiceBus/namespaces, Microsoft.Relay/namespaces, Microsoft.StorageSync/storageSyncServices, Microsoft.HealthcareApis/services, Microsoft.Automation/automationAccounts, Microsoft.Insights/privateLinkScopes, Microsoft.CognitiveServices/accounts, Microsoft.Compute/diskAccesses, Microsoft.Network/applicationgateways, Microsoft.Migrate/assessmentProjects, Microsoft.Migrate/migrateProjects, Microsoft.DataFactory/factories, Microsoft.Devices/ProvisioningServices, Microsoft.Synapse/privateLinkHubs, Microsoft.PowerBI/privateLinkServicesForPowerBI, Microsoft.Cache/redisEnterprise, Microsoft.OffAzure/mastersites, Microsoft.DigitalTwins/digitalTwinsInstances, Microsoft.Purview/accounts." Details=[]`

Terraform version : Latest 0.15.0

**Comment by aristosvo** [comment]
@vishnu-anil Can you share your configuration?

**Comment by vishnu-anil** [comment]
@aristosvo Please find my code. I am using the private endpoint module from Terraform. 
http://registry.terraform.io/modules/andrewCluey/private-endpoint/azurerm/latest

Please note that It gave me initially issues using the module with respnect to the DNS nams and hence I have commented out the DNS portion in the module itself. I can create endpoints for the rest of the resources with this and it accepts the sub resource names based on Azure documentation but just have issue with this "namespace"

`module "private_endpoint-servicebus" {
  source  = "../../modules/terraform-azurerm-private-endpoint-2.0.4"
  pe_resource_group_name =  "My-Test_RG-EastUS"
  pe_resource_name = "servicebus"
  location = "eastus"
  endpoint_resource_id = module.service_bus.servicebus-id
  subresource_names              = [ "namespace" ]
  pe_network = {
    resource_group_name = "My-Test_RG-EastUS"
    vnet_name           = module.vnet.vnet_name
    subnet_name         =  "APP"
  }

  #dns = {
  #  zone_ids   = module.dns-zone.servicebus-resource-id
  #  zone_name = module.dns-zone.servicebus-resource-name
  #}
}`

**Comment by aristosvo** [comment]
Have you tried `namespaces` instead of `namespace`?

**Comment by vishnu-anil** [comment]
@aristosvo I dont recall doing that but will definitely try. Thanks for the quick response

**Comment by smitp11** [comment]
Have you registered the Resource Providers in the Azure subscription designated for Azure Purview Account: 

- Microsoft.Storage
- Microsoft.EventHub
- Microsoft.Purview

https://docs.microsoft.com/en-us/answers/questions/44443/add-resource-providers-to-azure-subscription.html
