### ISSUE TITLE
azurerm_subscription enrollment_account argument

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#11392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
azurerm v2.55.0

### Affected Resource(s)

* `azurerm_subscription`

### Terraform Configuration Files

```hcl
resource "azurerm_subscription" "subvend" {
    subscription_name  = "Example-Subscription"
    enrollment_account = "12345"
}
```

### Expected Behaviour

Terraform should accept the argument for "enrollment_account" (based of the documentation, is this out of date?)

### Actual Behaviour

Error: Unsupported argument

  on main.tf line 4, in resource "azurerm_subscription" "subvend":
   4:     enrollment_account = "123456"

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription

* #0000

**Comment by milesjh** [comment]
The parameter should be enrollment_account_name, per the docs, but I am also having trouble getting this working. Seems to be more of a service principal role assignment issue, though.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
