### ISSUE TITLE
azurerm_subscription workload only deploying as DevTest

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#11391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
AzureRM 2.55

### Affected Resource(s)

* `azurerm_subscription`

### Terraform Configuration Files

```hcl
resource "azurerm_subscription" "subvend" {
    billing_scope_id  = data.azurerm_billing_enrollment_account_scope.ea_account.id
    subscription_name = "Example-Subscription"
    workload          = "Production"
}
```

### Expected Behaviour

Subscription was created as a "Production"

### Actual Behaviour

Subscription was created as a "DevTest"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Deploying using a Service Principal that has RBAC permissions to create Subscriptions within the EA Account

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
