### ISSUE TITLE
azurerm_management_group_subscription_association cannot move to another management group

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#11393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.4
azurerm v2.55.0

### Affected Resource(s)

* `azurerm_management_group_subscription_association`

### Terraform Configuration Files

```hcl
resource "azurerm_management_group_subscription_association" "subvend" {
  management_group_id = data.azurerm_management_group.subvend.id
  subscription_id     = data.azurerm_subscriptions.subvend.subscriptions[0].id
}
```

### Expected Behaviour

When I change the management group in the data lookup, the plan notices the management group has changed and will move the subscription on apply.

### Actual Behaviour

terraform plan notices the different management group, apply completes without any errors, but the subscription is not moved to another management group.

### Steps to Reproduce

1. `terraform apply`
2. Change Management group in data lookup
3. 'terraform apply'
4. Apply completes, subscription is not moved.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_subscription_association

* #0000

**Comment by aecom-billhammond** [comment]
I can confirm also that on v.2.74.0 if you complete the example on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_subscription_association
that the end result is also that the subscription is created and the terraform apply is successful yet the subscription is not moved to be under that management group.

**Comment by aecom-billhammond** [comment]
OK I'm going to take back what I said there, turns out to have been a temporary issue in Azure itself that happened to coincide with my TF test. Currently the example URL I cited above seems to work for me on the latest version

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
