### ISSUE TITLE
azurerm_shared_image_version - build image version from managed image "regionalReplicaCount" error

### ISSUE THREAD

**Issue by valtos** [hashicorp/terraform-provider-azurerm#11411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0

### Affected Resource(s)

* `azurerm_shared_image_version`

### Terraform Configuration Files

File "shared_image_version.tf"
```hcl
data "azurerm_resource_group" "gallery_resource_group" {
  name = var.gallery_resource_group_name
}

resource "azurerm_shared_image_version" "shared_image_version" {
  name                = var.gallery_image_version
  gallery_name        = var.gallery_name
  image_name  = var.gallery_image_name
  resource_group_name = var.gallery_resource_group_name
  location            = data.azurerm_resource_group.gallery_resource_group.location
  managed_image_id    = azurerm_image.vm-image.id

  target_region {
    name                   = var.gallery_image_location
#    regional_replica_count = var.regional_replica_count
    regional_replica_count = 1
    #    storage_account_type   = var.storage_account_type
  }
}
```

### Debug Output

I am sorry, too much sensitive informations, i can't sent complete debug output.
Here the error at apply, hope you this helps

[Gist link to error output at apply](https://gist.github.com/valtos/96e6b0e5befa8a95145236d4e2dd2aaf)

### Expected Behaviour

Image version should have been created in the image defintion of the shared gallery.

### Actual Behaviour

Generating an error during the terraform apply

### Steps to Reproduce

1. Create a VM
2. Create a "managed image" from this  VM ( [Create a managed image of a generalized VM in Azure](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/capture-image-resource) )
3. Create a "shared image gallery"
4. Create an "image definition" in this shared gallery for the image
5. Finally build the "shared_image_version" resource from the managed image created in step 2

### References

* #0000

**Comment by roy-work** [comment]
I also seem to be hitting this.

I think the error is the same,

```
The value 0 of parameter 'galleryArtifactVersion.properties.publishingProfile.targetRegions.regionalReplicaCount' is out of range. The value must be between '1' and '50', inclusive.
```

The Terraform code,

```terraform
resource "azurerm_shared_image_version" "base_0_0_1" {
  name = "0.0.1"
  gallery_name = azurerm_shared_image.base.gallery_name
  image_name = azurerm_shared_image.base.name
  resource_group_name = azurerm_shared_image.base.resource_group_name
  location = azurerm_shared_image.base.location
  managed_image_id = data.azurerm_image.base_20210308_1.id

  target_region {
    name = "East US"
    regional_replica_count = 1
    storage_account_type = "Standard_LRS"
  }
}
```

During the `apply`, if you do a `TF_LOG=DEBUG` you can see the request that gets made:

```
2021-05-14T11:28:59.750-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.52.0_x5: {"location":"eastus","properties":{"publishingProfile":{"excludeFromLatest":false,"targetRegions":[{"name":"East US","regionalReplicaCount":0},{"name":"eastus","regionalReplicaCount":1,"storageAccountType":"Standard_LRS"}]},"storageProfile":{"source":{"id":"/subscriptions/[redacted]/resourceGroups/[redacted]/providers/Microsoft.Compute/images/[redacted]"}}},"tags":{}}
```
Which is clearly wrong, and starts to explain the error.

That API call's `targetRegions` seems to get generated here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.52.0/azurerm/internal/services/compute/shared_image_version_resource.go#L312-L332

But that code looks fine to me. And yet, the API call is clearly wrong.

And it's definitely taking the single `target_region` from the TF source & like… splitting it into two? I changed by input to,

```
  target_region {
    name = "East USaaa"
    regional_replica_count = 1
    storage_account_type = "Standard_ZRS"
  }
```

And got:
```json
"targetRegions":[{"name":"East USaaa","regionalReplicaCount":0},{"name":"eastusaaa","regionalReplicaCount":1,"storageAccountType":"Standard_ZRS"}]}
```
… which is even weirder.

**Comment by kubasiatkowski** [comment]
The issue can be worked around by providing short region names. For example:

```
  target_region {
    name                   = "westeurope"
    regional_replica_count = 2
    storage_account_type   = "Standard_LRS"
  }
```
