### ISSUE TITLE
Error: Incorrect UUID Validation on WorkspaceID for itsm_reciever

### ISSUE THREAD

**Issue by Lachlan-White** [hashicorp/terraform-provider-azurerm#11423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform Version `14.5`
* AzureRM Provider Version `2.57.0`

### Affected Resource(s)

* `azurerm_monitor_action_group`

### Terraform Configuration Files

```hcl
module "example_mag" {
  source = "../.."

  name                = "mag-${random_id.unique.hex}"
  resource_group_name = module.example_rg.name
  short_name          = "mag-${random_id.short.hex}"

  itsm_receivers = [
    {
      name                 = "createorupdateticket"
      workspace_id         = "6asdfe3a18-aac3-40e4-b98e-1f309f329816"
      connection_id        = "5dde3956-42v4-42ba-ba3c-b123cdf18b19"
      ticket_configuration = "{}"
      region               = "australiasoutheast"
    },
  ]
}

```

### Expected Behaviour
The required `workspace_id` input for the ITSM_Reciever block is a combination of the Subscription ID and the Workspace ID separated by a `|` not a UUID. 

The string configuration of `sub_id | workspace_id` is required to be valid, but is block by the UUID helper function. Something like the below should be required:
`workspace_id = format("%s|%s", data.azurerm_subscription.current.subscription_id, azurerm_log_analytics_workspace.this.workspace_id)`

ITSM_Reciever configuration should successfully apply, to the `azurerm_monitor_action_group` resource.

### Actual Behaviour
![image](https://user-images.githubusercontent.com/41881046/115639456-f69e8c00-a357-11eb-81e3-096d8aeaac7c.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

When manually configuring this in the Azure Portal the properties are the below:
```json
{
      "connectionId": "e921ceff-cc4f-5ab6-b53d-b4a1de2a22a8",
      "name": "ITSMAction",
      "region": "australiasoutheast",
      "ticketConfiguration": "{\"PayloadRevision\":null,\"WorkItemType\":\"Event\",\"WorkItemData\":\"{\\\"severity\\\":\\\"1\\\"}\",\"CreateOneWIPerCI\":true,\"CreateOneWIPerLog\":false}",
      "workspaceId": "erccf22a-b008-45ee-ee22-215ee047af699|6asdfe3a18-aac3-40e4-b98e-1f309f329816"
    }
```

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/validate/uuid.go
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/monitor/monitor_action_group_resource.go#L96
* https://github.com/Azure/azure-rest-api-specs/blob/1b0ed8edd58bb7c9ade9a27430759527bd4eec8e/specification/monitor/resource-manager/Microsoft.Insights/stable/2017-04-01/examples/createOrUpdateActionGroup.json#L44

**Comment by leriksen** [comment]
I have been looking at this, and I think there are two possible fixes

1. change the validation from isUUID to a regex that matches roughly "uuid_regex|uuid_regex"
2. write a new validator, something like "is_oms_la_instance_identifier" that splits the string on the "|", checks there are only two parts, and that each part is a UUID. That's a pretty specific validator, but I don't know anywhere else in Azure that uses this format.

Of course there are certainly possible fixes I haven't considered, these seem the low hanging fruit.

Thoughts @tombuildsstuff ?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
