### ISSUE TITLE
azurerm_storage_account is recreated when using data.azurerm_resource_group as an implicit dependency

### ISSUE THREAD

**Issue by fl-max** [hashicorp/terraform-provider-azurerm#11437]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_storage_account`
* `data.azurerm_resource_group`

### Terraform Configuration Files

**main.tf**:
```hcl
variable "tenant_id" {
  type        = string
  description = "Azure Tenant ID"
}

variable "subscription_id" {
  type        = string
  description = "The Azure Subscription in which Resources should be deployed in."
}

locals {
  tags = {
    Version = random_string.version.result
  }
}

resource "random_string" "version" {
  length           = 4
  special          = false
  keepers         = {
      uuid = uuid()
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  tenant_id           = var.tenant_id
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "Example-Test"
  location = "eastus2"
  tags       = local.tags
}

module "example" {
    source     = "./module"
    depends_on = [
      azurerm_resource_group.test
    ]
    rg_name = azurerm_resource_group.test.name
    tags    = local.tags
}
```

**modules/storage.tf**:
```hcl
variable "tags" {
  type = map
}

variable "rg_name" {
  type        = string
  description = "Name of the resource group"
}

data "azurerm_resource_group" "test" {
  name = var.rg_name
}

resource "random_string" "sa-name" {
  length           = 24
  special          = false
  lower            = true
  upper            = false
  number           = true
}

resource "azurerm_storage_account" "test" {
  name = random_string.sa-name.result

  resource_group_name       = data.azurerm_resource_group.test.name
  location                  = data.azurerm_resource_group.test.location
  account_tier              = "Standard"
  account_kind              = "BlobStorage"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
  allow_blob_public_access  = false
  network_rules {
    default_action = "Deny"
  }
  tags = var.tags
}

```

### Expected Behaviour

Upon **second** `terraform apply`, I would expect there to only be an update to the Version tag and to not force a resource replacement.

### Actual Behaviour

`module.example.azurerm_storage_account.test` is recreated.

```log
  # module.example.azurerm_storage_account.test must be replaced
-/+ resource "azurerm_storage_account" "test" {
      ~ access_tier                      = "Hot" -> (known after apply)
      ~ id                               = "/subscriptions/<your_sub>/resourceGroups/Example-Test/providers/Microsoft.Storage/storageAccounts/<your_sa_name>" -> (known after apply)
      + large_file_share_enabled         = (known after apply)
      ~ location                         = "eastus2" -> (known after apply) # forces replacement
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `terraform apply`
4. The second apply (Step 3) will cause the `Version` tag to change and subsequently force the resource replacement.

**Comment by j2017771** [comment]
This is not binding only to Azure resource group. Anytime you are trying to reference something via Data Source. The problem is without any changes terraform-provider-azurerm are always asking the data source to be read during apply.

And all data sources are reference via the `id`. This cause this behavior:

```hcl
  # module.kv.data.azurerm_client_config.current will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_client_config" "current"  {
      ~ client_id       = "xxx" -> (known after apply)
      ~ id              = "xxx" -> (known after apply)
      ~ object_id       = "xxx" -> (known after apply)
      ~ subscription_id = "xxx" -> (known after apply)
      ~ tenant_id       = "xxx" -> (known after apply)

      + timeouts {
          + read = (known after apply)
        }
    }
```

This cause anything that are referencing the data source to be re-created because Terraform can't ensure that the ID is the same. This is a very poor behavior of the terraform-provide-azurerm. And it should not behave like that ever. However, this is not a bug, it is expected based on Terraform specs of Data Source.

**Comment by tombuildsstuff** [comment]
Consolidating into #13015
