### ISSUE TITLE
azurerm_container_group resource fails to create shared volume between containers in multi container group

### ISSUE THREAD

**Issue by greifelt** [hashicorp/terraform-provider-azurerm#11444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.0 on linux_amd64
provider registry.terraform.io/hashicorp/azurerm v2.56.0

### Affected Resource(s)

* `azurerm_container_group`

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "sidecar" {
  ip_address_type     = "Public"
  location            = "eastus"
  name                = "sidecar-test"
  os_type             = "Linux"
  resource_group_name = "rgdev"
  restart_policy      = "Always"

  container {
    name   = "nginx1"
    image  = "nginx"
    cpu    = 1
    memory = 1.5

    ports {
      port = 80
    }

    volume {
      empty_dir  = true
      mount_path = "/mnt/empty"
      name       = "emptydir1"
    }
  }

  container {
    name   = "sidecar"
    image  = "alpine"
    cpu    = 1
    memory = 1.5

    commands = [
      "sleep",
      "99999",
    ]

    volume {
      empty_dir  = true
      mount_path = "/var/cache"
      name       = "emptydir1"
    }
  }
}
```

### Actual Behaviour

```hcl
azurerm_container_group.sidecar: Creating...

Error: Error creating/updating container group "sidecar-test" (Resource Group "rgdev"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="DuplicateVolumes" Message="Duplicate volumes 'emptydir1' are found."

  on a.tf line 10, in resource "azurerm_container_group" "sidecar":
 10: resource "azurerm_container_group" "sidecar" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If You need share mount in multi container Azure Container Instance group between containers, need to pass the same mount name in separate container definitions blocks as described there: https://docs.microsoft.com/en-us/azure/container-instances/container-instances-volume-emptydir, but this doesn't likes for azurerm provider due to identified duplicate volume name

**Comment by janegilring** [comment]
We also ran into the same issue recently:

`│ Error: creating/updating container group "contoso-aci-01-ne" (Resource Group "contoso-infrastructure-rg"): containerinstance.ContainerGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="DuplicateVolumes" Message="Duplicate volumes 'dbt-emptydir' are found."`

As a workaround we failed back to using an ARM template instead.
