### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment resource adds and removes disk to VM continuously

### ISSUE THREAD

**Issue by snair01** [hashicorp/terraform-provider-azurerm#11443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform --version
Terraform v0.12.24
+ provider.azuread v1.1.0
+ provider.azurerm v2.3.0

### Affected Resource(s)

* `azurerm_virtual_machine_data_disk_attachment`

### Terraform Configuration Files

resource "azurerm_virtual_machine_data_disk_attachment" "attach-<myvm>_datadisk-01" {
  depends_on         = [azurerm_managed_disk.<myvm>_datadisk-01, azurerm_virtual_machine.vm-<myvm>]
  managed_disk_id    = azurerm_managed_disk.<myvm>_datadisk-01.id
  virtual_machine_id = azurerm_virtual_machine.vm-<myvm>.id
  create_option      = "Attach"
  lun                = 0
  caching            = "None"
}

### Debug Output

First run plan output (state for VM does not change)

# azurerm_virtual_machine_data_disk_attachment.attach-<myvm>_datadisk-01 will be created
  + resource "azurerm_virtual_machine_data_disk_attachment" "attach-<myvm>_datadisk-01" {
      + caching                   = "None"
      + create_option             = "Attach"
      + id                        = (known after apply)
      + lun                       = 0
      + managed_disk_id           = "/subscriptions/<sub-id>/resourceGroups/<resource-group-id>/providers/Microsoft.Compute/disks/<myvm>_datadisk-01"
      + virtual_machine_id        = "/subscriptions/<sub-id>/resourceGroups/<resource-group-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Compute/virtualMachines/<myvm>"
      + write_accelerator_enabled = false
    }

Next run plan output removes the storage_data_disk property from the VM

# azurerm_virtual_machine.vm-<myvm> will be updated in-place

~resource "azurerm_virtual_machine" "vm-<myvm>" {
        delete_data_disks_on_termination = false
        delete_os_disk_on_termination    = false
        id                               = "/subscriptions/<sub-id>/resourceGroups/<res-grp-name>/providers/Microsoft.Compute/virtualMachines/<myvm>"
        location                         = "westus2"
        name                             = "<myvm>"
        network_interface_ids            = [
            "/subscriptions/<sub-id>/resourceGroups/<res-grp-name>/providers/Microsoft.Network/networkInterfaces/<myvm>-nic1",
        ]
        resource_group_name              = "<res-grp-name>"
        vm_size                          = "Standard_D4ds_v4"
        zones                            = []

        os_profile {
            admin_username = "<admin-name>"
            computer_name  = "<myvm>"
        }

        os_profile_windows_config {
            enable_automatic_upgrades = false
            provision_vm_agent        = true
            timezone                  = "<mytimezone>"
        }

      - storage_data_disk {
          - caching                   = "None" -> null
          - create_option             = "Attach" -> null
          - disk_size_gb              = 50 -> null
          - lun                       = 0 -> null
          - managed_disk_id           = "/subscriptions/<sub-id>/resourceGroups/<res-grp-name>/providers/Microsoft.Compute/disks/<myvm>_datadisk-01" -> null
          - managed_disk_type         = "StandardSSD_LRS" -> null
          - name                      = "<myvm>_datadisk-01" -> null
          - write_accelerator_enabled = false -> null
        }

Requeuing the workspace without any changes gives the same result as the first plan result above 

### Expected Behaviour

the disk attachment resource is expected to update the state of the VM the disk is being attached to so the storage_data_disk {} construct on the VM state reflects the disk attachment.

### Actual Behaviour

Terraform requeue adds and removes disk from VM every other run.

**Comment by tombuildsstuff** [comment]
hi @snair01 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!
