### ISSUE TITLE
custom_subdomain_name  in Azure Coginitve is not working as expected 

### ISSUE THREAD

**Issue by afsalva1** [hashicorp/terraform-provider-azurerm#11450]
on main.tf line 37, in resource "azurerm_cognitive_account" "cognitive_services":
  37:   custom_subdomain_name = "Test"

An argument named "custom_subdomain_name" is not expected here.

Why this argument is not taking , is there any way to get this done ?

**Comment by katbyte** [comment]
@afsalva1 - that is part of the `azurerm_cognitive_account` resource - can you share a tf config that causes this error?

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
