### ISSUE TITLE
Support for `AllowSharedKeyAccess` in `azurerm_storage_account`

### ISSUE THREAD

**Issue by yupwei68** [hashicorp/terraform-provider-azurerm#11460]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for `AllowSharedKeyAccess` in `azurerm_storage_account`
![image](https://user-images.githubusercontent.com/56525716/115979035-2945c000-a5b6-11eb-8885-33c79be8ecc5.png)

This feature could not be enhanced because we authenticate the storage account via shared key access. 
Once we disable the `AllowSharedKeyAccess` in `azurerm_storage_account`, we'll get error in getting queue service and other services.
Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account"
### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "test" {
  name                = "unlikely23exst2acct%s"
  resource_group_name = azurerm_resource_group.test.name

  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  allow_shared_key_access  = false

  tags = {
    environment = "production"
  }
}
```

### References

* #0000

**Comment by hayden-corney** [comment]
> This feature could not be enhanced because we authenticate the storage account via shared key access.
Once we disable the AllowSharedKeyAccess in azurerm_storage_account, we'll get error in getting queue service and other services.
Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account"

If you set the [`storage_use_azuread`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread) argument on the provider configuration it won't use the shared key to access the storage account. We are using this and a `local-exec` provisioner to workaround this option not yet being available in the provider, but it would make things cleaner once this is supported.

```tf
provider "azurerm" {
  storage_use_azuread = true
  features {}
}

resource "azurerm_storage_account" "example" {
  ...
}

resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "az storage account update --ids ${azurerm_storage_account.example.id} --allow-shared-key-access false"
  }
}
```

**Comment by hayden-corney** [comment]
It looks like the underlying API now supports this property. Is there anything else that needs to be done before the option can be added to the terraform provider?

https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v55.0.0+incompatible/services/storage/mgmt/2021-04-01/storage#AccountProperties

```go
// AllowSharedKeyAccess - Indicates whether the storage account permits requests to be authorized with the account access key via Shared Key. If false, then all requests, including shared access signatures, must be authorized with Azure Active Directory (Azure AD). The default value is null, which is equivalent to true.
AllowSharedKeyAccess *bool `json:"allowSharedKeyAccess,omitempty"`
```

**Comment by yupwei68** [comment]
Hi @hayden-corney Thanks for your reply. 
On fact, we could not use AAD to authenticate storage data plane. Because it requires an additional rabc role `Blob Data Contributor` besides `Contributor`. We always use Shared Key to authenticate to the storage account. 
It might be implemented in the future when we have transited our apis from storage data plane to storage mgmt. plan.
But currently, we could not implement this field.

**Comment by OliverRC** [comment]
I agree, would be great to have support for Enabling/Disabling "Allow Shared Access Keys" as part of Terraform.
