### ISSUE TITLE
module.virtual_machine_extension.azurerm_virtual_machine_extension.extension["XXX"] will be updated in-place -> virtual_machine_id change

### ISSUE THREAD

**Issue by rpili1313** [hashicorp/terraform-provider-azurerm#11476]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
0.14.X

### Affected Resource(s)
azurerm_virtual_machine_extension

### Terraform Configuration Files
resource "azurerm_virtual_machine_extension" "extension" {
  for_each = try(var.virtual_machine_extensions_data, {})

  name                       = each.value.name
  virtual_machine_id         = try(var.windows_virtual_machines_data[each.value.windows_virtual_machine_key].id, var.linux_virtual_machines_data[each.value.linux_virtual_machine_key].id)
  publisher                  = each.value.publisher
  type                       = each.value.type
  type_handler_version       = each.value.type_handler_version
  auto_upgrade_minor_version = each.value.auto_upgrade_minor_version

  settings                   = jsonencode(each.value.settings)
  protected_settings         = jsonencode(each.value.protected_settings)

  lifecycle {
    ignore_changes = [
      virtual_machine_id,
      settings 
    ]
  }

  tags  = merge(try(each.value.tags, null), {DeploymentType = "Terraform"})
}

### Debug Output

module.virtual_machine_extension.azurerm_virtual_machine_extension.extension["extension03"] will be updated in-place
   ~ resource "azurerm_virtual_machine_extension" "extension" {
       id = "/subscriptions/xxxxx/resourceGroups/biology-visiopharm-rg/providers/Microsoft.Compute/virtualMachines/xxxx/extensions/JoinDomain"
      name  = "JoinDomain"
tags = {
"DeploymentType" = "Terraform"
} # Warning: this attribute value will be marked as sensitive and will

~ virtual_machine_id         = (sensitive)
 }

### Expected Behaviour
Even with the ignore part it doesn't ignore the virtual machine ID

### Actual Behaviour
Work even without ignore changes in the code

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x or 1.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
