### ISSUE TITLE
Unable to set retention policy on azurerm_network_watcher_flow_log

### ISSUE THREAD

**Issue by gmichels** [hashicorp/terraform-provider-azurerm#11479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.9
AzureRM 2.56.0

### Affected Resource(s)

* `azurerm_network_watcher_flow_log`

### Terraform Configuration Files

```hcl
resource "azurerm_network_watcher_flow_log" "nw_flow" {
  for_each = module.vnet.nsg_obj

  network_watcher_name = azurerm_network_watcher.netwatcher.name
  resource_group_name  = azurerm_resource_group.dte-lz.name

  network_security_group_id = each.value.id
  storage_account_id        = local.flow_logs_config.storage_account_id
  enabled                   = local.flow_logs_config.nsg_flow_logs_enable
  version                   = 2

  retention_policy {
    enabled = local.flow_logs_config.nsg_flow_logs_enable && local.flow_logs_config.nsg_flow_logs_retention > 0 ? true : false
    days    = local.flow_logs_config.nsg_flow_logs_retention
  }

  traffic_analytics {
    enabled               = local.flow_logs_config.traffic_analytics_enable
    interval_in_minutes   = local.flow_logs_config.traffic_analytics_interval
    workspace_id          = var.nh-shared-lz_log_analytics_workspace.workspace_id
    workspace_region      = var.nh-shared-lz_log_analytics_workspace.location
    workspace_resource_id = var.nh-shared-lz_log_analytics_workspace.id
  }
}
```

### Debug Output

https://gist.github.com/gmichels/3745c1e7dea84e3cdeed95c11534def0

### Expected Behaviour

Applying the resource with traffic a retention policy should create the management policy on the storage account

### Actual Behaviour

The apply operation fails with:

```
Error: Error waiting for completion of setting Flow Log Configuration for target "/subscriptions/ce8e7d8f-10bb-4290-9e18-a21b7d6f9462/resourceGroups/ev-perf-rg/providers/Microsoft.Network/networkSecurityGroups/ev-perf-k8s-subnet-nsg" (Network Watcher "NetworkWatcher_eastus" / Resource Group "ev-perf-rg"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="FeatureUnsupportedForApiVersion" Message="Invalid Management policy operation, appendBlob support for blobType property requires June19 or higher api version" Details=[]
```

The apply operation works fine when `retention_policy.enabled` is set to `false`

### Steps to Reproduce

1. `terraform apply` with `retention_policy.enabled` set to `true`

### Important Factoids

None

### References

None that I could find

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
