### ISSUE TITLE
[FEATURE REQUEST] Support for Ingress Controller add-on for a new AKS cluster with Application Gateway instance

### ISSUE THREAD

**Issue by Shaybs** [hashicorp/terraform-provider-azurerm#11489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

So in the following tutorial:

https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new

A user can set up a cluster with an AGIC that is managed by Azure using the following command:

az aks create -n myCluster -g myResourceGroup --network-plugin azure --enable-managed-identity -a ingress-appgw --appgw-name myApplicationGateway --appgw-subnet-cidr "10.2.0.0/16" --generate-ssh-keys

However, I have been searching for a similar feature on Terraform where this feature is replicated for AKS but I have not found any. I have found ways to configure the AGIC & also ensure that the AGIC is connected to the same VNET effectively allowing ingress to the AKS cluster. However, the AGIC feature itself as shown in the image:

![Screenshot 2021-04-27 094840](https://user-images.githubusercontent.com/41239922/116213577-d139c580-a73d-11eb-8bc8-036c2a7eb476.png)

Cannot be set to on/true on startup. 

### Potential Terraform Configuration

```
resource "azurerm_kubernetes_cluster" "cluster" {
 ...

  addon_profile {
    enable_application_gateway_ingress_controller {
      enabled                     = true
      application_gateway = [NAME OF APPLICATION GATEWAY]
    }
  }
}

```

**Comment by TadeoCloud** [comment]
It seems that since version 2.57.0 of azurerm provider "ingress_application_gateway" block is supported on aks resource, 
but if I use this terraform example it does not create any app-gw in my subscription.

```
resource "azurerm_kubernetes_cluster" "k8s" {
...

  addon_profile {
    ingress_application_gateway {
      enabled = true
      subnet_id = data.azurerm_subnet.aks.id
    }
  }
}
```

**Comment by Shaybs** [comment]
Hi,

Thanks a ton! I'll be updating our Terraform script.

Shuaib

**Comment by tmiroslav** [comment]
Hi,

Any update on this? 
I am also experiencing issue when creating AKS with app gw add-on enabled. Only if service principal is selected for identity, app gw is being created - and in that case ingress with is running inside AKS cluster is not getting IP. So, I need to change then identity to "SystemAssigned", in order ingress to get IP. 
When I set "SystemAssigned" as identity in the time of AKS cluster creation, app gw is not being created at all. 

Any progress in app gw  add-on  feature functionality?

Thank you!

**Comment by tombuildsstuff** [comment]
Closing this out since this is now supported in the `ingress_application_gateway` block

**Comment by tmiroslav** [comment]
@tombuildsstuff Could you please tell  me what is supported in `ingress_application_gateway`? When I used this block to create app gw, while  setting service principal as identity for AKS clusters, app gw is being created, but ingress then is not getting an IP in AKS cluster. This is a problem and not working as expected. What should be set as identity for AKS cluster while using `ingress_application_gateway` add-on for app gw creation.
