### ISSUE TITLE
can not change edition for azurerm_sql_database when using with azurerm_sql_failover_group

### ISSUE THREAD

**Issue by SamWhitby** [hashicorp/terraform-provider-azurerm#11482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

hashicorp/azurerm v2.29.0

### Affected Resource(s)

azurerm_sql_database and azurerm_sql_failover_group

### Terraform Configuration Files

Initial configuration with an edition of "Basic" - works as expected.

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_sql_server" "primary" {
  name                         = "sql-primary"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = "sqladmin"
  administrator_login_password = "pa$$w0rd"
}

resource "azurerm_sql_server" "secondary" {
  name                         = "sql-secondary"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = "northeurope"
  version                      = "12.0"
  administrator_login          = "sqladmin"
  administrator_login_password = "pa$$w0rd"
}

resource "azurerm_sql_database" "db1" {
  name                = "db1"
  resource_group_name = azurerm_sql_server.primary.resource_group_name
  location            = azurerm_sql_server.primary.location
  server_name         = azurerm_sql_server.primary.name

  edition                          = "Basic"
  requested_service_objective_name = "Basic"
}

resource "azurerm_sql_failover_group" "example" {
  name                = "example-failover-group"
  resource_group_name = azurerm_sql_server.primary.resource_group_name
  server_name         = azurerm_sql_server.primary.name
  databases           = [azurerm_sql_database.db1.id]
  partner_servers {
    id = azurerm_sql_server.secondary.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 60
  }
}
```

Then change the edition to "Standard" and apply fails

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_sql_server" "primary" {
  name                         = "sql-primary"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  version                      = "12.0"
  administrator_login          = "sqladmin"
  administrator_login_password = "pa$$w0rd"
}

resource "azurerm_sql_server" "secondary" {
  name                         = "sql-secondary"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = "northeurope"
  version                      = "12.0"
  administrator_login          = "sqladmin"
  administrator_login_password = "pa$$w0rd"
}

resource "azurerm_sql_database" "db1" {
  name                = "db1"
  resource_group_name = azurerm_sql_server.primary.resource_group_name
  location            = azurerm_sql_server.primary.location
  server_name         = azurerm_sql_server.primary.name

  edition                          = "Standard"
  requested_service_objective_name = "S0"
}

resource "azurerm_sql_failover_group" "example" {
  name                = "example-failover-group"
  resource_group_name = azurerm_sql_server.primary.resource_group_name
  server_name         = azurerm_sql_server.primary.name
  databases           = [azurerm_sql_database.db1.id]
  partner_servers {
    id = azurerm_sql_server.secondary.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 60
  }
}
```

### Expected Behaviour

Both the primary and the geo replica dbs should have been updated to the new edition.

### Actual Behaviour
When applying the error message below is returned 
"The source database 'x' cannot have higher edition than the target database 'y'. Upgrade the edition on the target before upgrading source."

### Steps to Reproduce
Create a geo replicated sql db with the edition of "Basic", then change the edition to something higher e.g. "Standard".

It seems because of the dependency order (the replica db is dependent of the primary db) changes are made to the primary first. However it looks like azure enforces that replica need to be changed first then the primary.

1. `terraform apply` (initial configuration)
2. change edition to "Standard"
3. `terraform apply`

**Comment by aristosvo** [comment]
`azurerm_mssql_database` resource is the new version of `azurerm_sql_database`.

I'm sure upgrading within a certain edition (`GP_Gen5_2` -> `GP_Gen5_8` -> `GP_Gen5_2`) works there, will test if upgrading between editions works as well (`S2` -> `GP_Gen5_8` -> `S2`) and report back.

**Comment by aristosvo** [comment]
Before-mentioned test indeed fails. According to the [docs](https://docs.microsoft.com/en-us/azure/azure-sql/database/auto-failover-group-overview?tabs=azure-powershell#upgrading-or-downgrading-a-primary-database) you cannot upgrade between service tiers:

> You can upgrade or downgrade a primary database to a different compute size (within the same service tier, not between General Purpose and Business Critical) without disconnecting any secondary databases.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
