### ISSUE TITLE
azurerm_monitor_metric_alert defined with dynamic_criteria failed with Runtime Error

### ISSUE THREAD

**Issue by PeterUherek** [hashicorp/terraform-provider-azurerm#11491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

*  `Terraform version: 0.14.2`

### Affected Resource(s)

* `azurerm_2.49.0`

### Terraform Configuration Files

```
resource "azurerm_monitor_metric_alert" "eventhub_alert" {
  name                = "Number of incoming messages are unusual"
  resource_group_name = var.resource_group_name
  scopes              = [azurerm_eventhub_namespace.test.id]
  description    = "Alert if eventhub has more or less incoming messages than usual"
  enabled        = true

  severity = 2
  frequency = "PT5M"
  window_size = "PT5M"

 dynamic_criteria {
    metric_namespace         = "Microsoft.EventHub/namespaces"
    metric_name              = "IncomingMessages"
    aggregation              = "Total"
    operator                 = "GreaterOrLessThan"
    alert_sensitivity        = "Medium"
    evaluation_total_count   = 4
    evaluation_failure_count = 4
 }

  action {
    action_group_id  = var.action_group_id
  }
}
```

### Expected Behaviour
It should pass. 

### Actual Behaviour
Actually I get error:

```
Error: Error creating or updating metric alert "Number of incoming messages are unusual" (resource group "test_beta"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: "<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Runtime Error</title>\r\n        <meta name=\"viewport\" content=\"width=device-width\" />\r\n        <style>\r\n         body {font-family:\"Verdana\";font-weight:normal;font-size: .7em;color:black;} \r\n         p {font-family:\"Verdana\";font-weight:normal;color:black;margin-top: -5px}\r\n         b {font-family:\"Verdana\";font-weight:bold;color:black;margin-top: -5px}\r\n         H1 { font-family:\"Verdana\";font-weight:normal;font-size:18pt;color:red }\r\n         H2 { font-f" error: invalid character '<' looking for beginning of value

  on ../../modules/replication/modules/alerts/main.tf line 102, in resource "azurerm_monitor_metric_alert" "eventhub_alert":
 102: resource "azurerm_monitor_metric_alert" "eventhub_alert" {
```

It is not clear from error message what is wrong about azurerm_monitor_metric_alert definition. I check debug output but it was not helpful. I configured it by exported template from azure and It looks like all values fit correctly. So right now I dont know what can be wrong. 

### Steps to Reproduce

Define azurerm_monitor_metric_alert with dynamic criteria

1. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
