### ISSUE TITLE
Support for Azure ServiceBus AutoScaling

### ISSUE THREAD

**Issue by matthawley** [hashicorp/terraform-provider-azurerm#11498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In March 2021, Azure GA'd autoscaling support for premium service bus skus based on metrics. We would like to start utilizing this autoscaling functionality, but need it supported in Terraform.

### New or Affected Resource(s)

* azurerm_servicebus_namespace

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "terraform-servicebus"
  location = "West Europe"
}

resource "azurerm_servicebus_autoscaler" "example" {
  name     = "tfex-servicebus-autoscale"
  resource_group_name = azurerm_resource_group.example.name

  condition {
    name = "Scale out at 75% CPU and Scale in at 25% CPU"
    mode = "Metric"
    limits = {
      min = 1
      max = 16
      default = 1
    }

    rule {
      metric_name = "CPU"
      operator = "GreaterThan"
      threshold = 75
      duration = 10
      statistic = "Avg"
      operation = "Increase"
      cool_down_duration = 5
    }

   rule {
      metric_name = "CPU"
      operator = "LessThan"
      threshold = 25
      duration = 10
      statistic = "Avg"
      operation = "Decrease"
      cool_down_duration = 5
    }
  }
}

resource "azurerm_servicebus_namespace" "example" {
  name                = "tfex-servicebus-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium"

  auto_scaler_id = azurerm_servicebus_autoscaler.example.id

  tags = {
    source = "terraform"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/service-bus-messaging/automate-update-messaging-units

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I've had a look and this should already be supported.
You define a `azurerm_monitor_autoscale_settings` resource, with `target_resource_id` parameter being set to your servicebus resource id. This isn't something that's configured in the servicebus resource itself.

**Comment by catriona-m** [comment]
Thanks @matthawley - based on the above comment it seems this is now supported, so I will close this issue. Feel free to reopen this if this is not the case!
