### ISSUE TITLE
azurerm_virtual_hub_connection across subscriptions

### ISSUE THREAD

**Issue by jleonelion** [hashicorp/terraform-provider-azurerm#11497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.5
+ provider registry.terraform.io/aztfmod/azurecaf v1.2.2
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.55.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Affected Resource(s)
* `azurerm_virtual_hub_connection`

### Terraform Configuration Files
```hcl
resource "azurerm_virtual_hub_connection" "vhub_connection" {
  name                      = "connection1"
  virtual_hub_id            = "/subscriptions/<subscription A>/resourceGroups/<resource group A>/providers/Microsoft.Network/virtualHubs/<virtual hub>"
  remote_virtual_network_id = "/subscriptions/<subscription B>/resourceGroups/<resource group B>/providers/Microsoft.Network/virtualNetworks/<vnet>"
  internet_security_enabled = true
}
```
### Expected Behaviour

Virtual hub connection is establish between the specified virtual hub and the specified vnet, as long as:
1. both subscriptions are backed by the same tenant 
2. the "active" az session is against that tenant

Since the fully id is provided for both ends of the connection, it shouldn't not matter which subscription you are in.

### Actual Behaviour

If your session is set to "subscription A", this works.  But if your session is set to "subscription B" (or any other subscription) the below error:
```
Error: creating Connection "connection1" (Virtual Hub "<virtual hub>" / Resource Group "<resource group A>"): network.HubVirtualNetworkConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group '<resource group A>' could not be found."

  on main.tf line 76, in resource "azurerm_virtual_hub_connection" "vhub_connection":
  76: resource "azurerm_virtual_hub_connection" "vhub_connection" {
```

### Steps to Reproduce
Create a simple Terraform file like that above.  Hard code the id's to existing virtual hub and vnets, which exist in separate subscriptions.

1. `terraform apply`

**Note: this works fine if both vnet and vhub are in the same subscription**

**Comment by henryxuteck** [comment]
Cross subscription azurerm_virtual_hub_connection did work for me up to azurerm 2.76.0. With latest azurerm provider, azurerm_virtual_hub_connection creation did "succeed", however, at the very end of the creation, there was a GET call against a resource ID with vnet name and resource group,  **but vhub subscription id**.

[DEBUG] provider.terraform-provider-azurerm_v2.78.0_x5: AzureRM Response for https://management.azure.com/subscriptions/**<vhub_subscription_id>**/resourceGroups/**<vnet_resource_group>**/providers/Microsoft.Network/virtualNetworks/**<vnet_name>**?api-version=2021-02-01: 
HTTP/2.0 404 Not Found

I guess [#13294](https://github.com/hashicorp/terraform-provider-azurerm/pull/13294) somehow breaks the logic.

**Comment by owenfarrell** [comment]
@jleonelion - thanks for the detailed writeup. One of the challenges here is that the API operation for connecting a virtual network with a virtual hub is at the _**subscription**_ level, not the tenant level. So your summary of what you're observing makes complete sense in that the current Azure account (`az account show`) has to be the subscription that contains the virtual hub when your configuration uses the default `azurerm` provider.

One alternative would be to explicitly configure the subscription ID of the default provider. Or if you have accounts across multiple subscriptions, using aliased providers for one or both of the subscriptions (see example below).

```hcl
################################################################################
# VWAN Subscription
################################################################################

provider "azurerm" {
  alias           = "vwan"
  tenant_id       = "<your tenant ID>"
  subscription_id = "<your virtual hub subscription ID>"
  features {}
}

resource "azurerm_resource_group" "vwan" {
  provider = azurerm.vwan

  name     = "vwan-resources"
  location = "eastus"
}

resource "azurerm_virtual_wan" "example" {
  provider = azurerm.vwan

  name                = "example-vwan"
  resource_group_name = azurerm_resource_group.vwan.name
  location            = azurerm_resource_group.vwan.location
}

resource "azurerm_virtual_hub" "example" {
  provider = azurerm.vwan

  name                = "example-vhub"
  resource_group_name = azurerm_resource_group.vwan.name
  location            = azurerm_resource_group.vwan.location
  virtual_wan_id      = azurerm_virtual_wan.example.id
  address_prefix      = "10.0.1.0/24"
}

resource "azurerm_virtual_hub_connection" "example" {
  provider = azurerm.vwan

  name                      = "example-vhub-connection"
  virtual_hub_id            = azurerm_virtual_hub.example.id
  remote_virtual_network_id = azurerm_virtual_network.example.id
}

################################################################################
# VNET Subscription Resources
################################################################################

provider "azurerm" {
  alias           = "vnet"
  tenant_id       = "<your tenant ID>"
  subscription_id = "<your virtual network subscription ID>"
  features {}
}

resource "azurerm_resource_group" "vnet" {
  provider = azurerm.vnet

  name     = "vnet-resources"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  provider = azurerm.vnet

  name                = "example-vnet"
  address_space       = ["172.0.0.0/16"]
  location            = azurerm_resource_group.vnet.location
  resource_group_name = azurerm_resource_group.vnet.name
}
```

**Comment by owenfarrell** [comment]
@henryxuteck - On a related note, I 100% agree that my changes cause cross-subscription provisioning to fail and needs to be changed.

I'm going to do some experimenting here, but I think the best case would be to change #13294 to poll for the virtual hub connection's provisioning state instead of the virtual network's provisioning state. My hope there is that the VHUB connection doesn't reach `Succeeded` until everything is 100% complete.

That would at least keeps everything within a single subscription. Unfortunately for me, it may reintroduce the issue I originally reported in #13105.

The above configuration is adapted from the example in the documentation - could you give it a review and let me know if it's a good representative sample for your situation or if there any changes I should make?
