### ISSUE TITLE
Unable to assign RBAC Roles directly to Key Vault Secret/Key/Certificate

### ISSUE THREAD

**Issue by danielbarber2** [hashicorp/terraform-provider-azurerm#11529]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform = v0.14.7
Testing performed on AzureRM versions: 2.50.0, 2.51.0, 2.52.0, 2.53.0, 2.54.0, 2.55.0, 2.56.0

### Affected Resource(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl

resource azurerm_key_vault keyvault {
  name                            = "DBKeyVaultTest123"
  location                        = "UK South"
  resource_group_name             = "DB_Test"
  sku_name                        = "standard"
  tenant_id                       = var.tenant_id
  enable_rbac_authorization       = true
}

resource azurerm_key_vault_secret secret_test {
  name         = "Secret-Test"
  value        = "thisisastest1"
  key_vault_id = azurerm_key_vault.KeyVault.id
}

data azuread_group group {
  display_name = "DB Azure Secret Group 6"
}

resource azurerm_role_assignment rbac_assignment {
  scope                 = azurerm_key_vault_secret.secret_test.id
  role_definition_name  = "Key Vault Secrets User"
  principal_id          = data.azuread_group.group.id
}
```

### Debug Output

Error: The number of path segments is not divisible by 2 in "secrets/Secret-Test/667eed1474ca420c80a59774a0bca465"
on main.tf line 192, in resource "azurerm_role_assignment" "rbac_assignment":
 192: resource azurerm_role_assignment rbac_assignment {

Error: Can not parse "scope" as a management group id: Unable to parse Management Group ID "https://dbkeyvaulttest123.vault.azure.net/secrets/Secret-Test/667eed1474ca420c80a59774a0bca465"
on main.tf line 192, in resource "azurerm_role_assignment" "rbac_assignment":
 192: resource azurerm_role_assignment rbac_assignment {

Error: "scope" expected to be valid subscription ID, got "https://dbkeyvaulttest123.vault.azure.net/secrets/Secret-Test/667eed1474ca420c80a59774a0bca465"
on main.tf line 192, in resource "azurerm_role_assignment" "rbac_assignment":
 192: resource azurerm_role_assignment rbac_assignment {

Error: The number of path segments is not divisible by 2 in "secrets/Secret-Test/667eed1474ca420c80a59774a0bca465"
on main.tf line 192, in resource "azurerm_role_assignment" "rbac_assignment":
 192: resource azurerm_role_assignment rbac_assignment {

Error: Can not parse "scope" as a resource id: The number of path segments is not divisible by 2 in "secrets/Secret-Test/667eed1474ca420c80a59774a0bca465"
on main.tf line 192, in resource "azurerm_role_assignment" "rbac_assignment":
 192: resource azurerm_role_assignment rbac_assignment {

### Steps to Reproduce

Try to assign RBAC permissions using azurerm_role_assignment with a scope value of the ID of a secret, key or certificate within Azure Key Vault.

### Notes

Functionality was added to the azurerm provider under 2.30 to allow the ability to enable rbac authorization on azurerm_key_vault by using the argument "enable_rbac_authorization".
The main benefit of this being that you can now set the scope of a role directly to the secret, key or certificate instead of the entire vault.
However when attempting this in terraform using azurerm_role_assignment I receive the above mentioned errors. 
I believe this is due to the ID attribute that is exported from azurerm_key_vault_secret is in the form of a URI (id" = "https://db-kv-test.vault.azure.net/secrets/Secret-Test/3e822cbf73dd47c49d3d504bc6267986") which azurerm_role_assignment cannot handle. But there is no other suitable attribute exported from the secret resource that I can use.
I have managed to workaround this issue by using interpolation to create an ID value as follows:

```hcl
resource azurerm_role_assignment rbac_assignment {
  scope                 = "${azurerm_key_vault_secret.secret_test.key_vault_id}/secrets/${azurerm_key_vault_secret.secret_test.name}"
  role_definition_name  = "Key Vault Secrets User"
  principal_id          = data.azuread_group.group.id
}
```

However this feels quite unintuitive given that azurerm_role_assignment requires a scope in the form of an ID and an ID is exported from azurerm_key_vault_secret. Note this same behavior is seen when using secrets, keys or certificates within key vault.

* #0000

**Comment by SPeacock1978** [comment]
I am getting exactly the same issue but when trying to apply the RBAC assignment to a storage account container.  

I've attached the full terraform code (minus the variable values) but the code that is failing is as follows...

`resource "azurerm_role_assignment" "storage_blob_writer_raw" {
  scope                = azurerm_storage_data_lake_gen2_filesystem.data_lake_test.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = var.sp_object_id
}`

The scope value is https://simonterraformtest.dfs.core.windows.net/test and I'm getting this error...

Error: The number of path segments is not divisible by 2 in "test"

  on terraform.tf line 59, in resource "azurerm_role_assignment" "storage_blob_writer_raw":
  59: resource "azurerm_role_assignment" "storage_blob_writer_raw" {



Error: Can not parse "scope" as a management group id: Unable to parse Management Group ID "https://simonterraformtest.dfs.core.windows.net/test"

  on terraform.tf line 59, in resource "azurerm_role_assignment" "storage_blob_writer_raw":
  59: resource "azurerm_role_assignment" "storage_blob_writer_raw" {



Error: "scope" expected to be valid subscription ID, got "https://simonterraformtest.dfs.core.windows.net/test"

  on terraform.tf line 59, in resource "azurerm_role_assignment" "storage_blob_writer_raw":
  59: resource "azurerm_role_assignment" "storage_blob_writer_raw" {



Error: The number of path segments is not divisible by 2 in "test"

  on terraform.tf line 59, in resource "azurerm_role_assignment" "storage_blob_writer_raw":
  59: resource "azurerm_role_assignment" "storage_blob_writer_raw" {



Error: Can not parse "scope" as a resource id: The number of path segments is not divisible by 2 in "test"

  on terraform.tf line 59, in resource "azurerm_role_assignment" "storage_blob_writer_raw":
  59: resource "azurerm_role_assignment" "storage_blob_writer_raw" {

**Comment by TimHarmon** [comment]
Any movement on this bug, I am having the exact issue as @danielbarber2, trying to create a Disk Encryption Set and assign RBAC roles to the Key but getting the same error above.

Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.4.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
