### ISSUE TITLE
terraform import of azurerm_lb  - "frontend_ip_configuration"   info. is missing

### ISSUE THREAD

**Issue by andyt530** [hashicorp/terraform-provider-azurerm#1153]
$ terraform -v
Terraform v0.11.7

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "azurerm" (1.3.3)...

Resource impacted:   azurerm_lb

terraform import of the azurerm_lb resource does not pick up the frontend_ip_configuration information:

hcl:

```
resource "azurerm_lb" "rg-dwp-prd-ss-core-fw-core__ilb-vm-prdssfwcore" {
         name = "ilb-vm-prdssfwcore"
         location = "uksouth"
         resource_group_name = "rg-dwp-prd-ss-core-fw-core"
         sku = "Basic"
         frontend_ip_configuration {
                 name = "loadBalancerFrontEnd1" 
                 subnet_id = "${azurerm_subnet.rg-dwp-prd-ss-core-fw__sub-dwp-prd-ss-core-fw-core-out.id}"
                 private_ip_address = "10.86.146.84" 
                 private_ip_address_allocation  = "Static" 
         }
         frontend_ip_configuration {
                 name = "loadBalancerFrontEnd2" 
                 subnet_id = "${azurerm_subnet.rg-dwp-prd-ss-core-fw__sub-dwp-prd-ss-core-fw-core-in.id}"
                 private_ip_address = "10.86.146.68" 
                 private_ip_address_allocation  = "Static" 
         }
}
```

$ terraform import  - ok

```
$ terraform state show azurerm_lb.rg-dwp-prd-ss-core-fw-core__ilb-vm-prdssfwcore
id                         = /subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore
location                   = uksouth
name                       = ilb-vm-prdssfwcore
private_ip_address         = 10.86.146.84
private_ip_addresses.#     = 2
private_ip_addresses.0     = 10.86.146.84
private_ip_addresses.1     = 10.86.146.68
resource_group_name        = rg-dwp-prd-ss-core-fw-core
sku                        = Basic
tags.%                     = 12
tags.billingIdentifier     = NOTSET
tags.commissionedDate      = NOTSET
tags.dataProfile           = NOTSET
tags.department            = NOTSET
tags.displayName           = iNGFLB
tags.environmentIdentifier = NOTSET
tags.environmentVersion    = NOTSET
tags.expirationDate        = NOTSET
tags.projectIdentifier     = NOTSET
tags.serviceName           = NOTSET
tags.serviceOwner          = NOTSET
tags.serviceWindow         = NOTSET
```

 **Note frontend_ip_configuration settings are not listed** 

Terraform plan - also confirms this:

terraform plan .

```
  ~ azurerm_lb.rg-dwp-prd-ss-core-fw-core__ilb-vm-prdssfwcore
      frontend_ip_configuration.#:                               "0" => "2"
      frontend_ip_configuration.0.inbound_nat_rules.#:           "" => <computed>
      frontend_ip_configuration.0.load_balancer_rules.#:         "" => <computed>
      frontend_ip_configuration.0.name:                          "" => "loadBalancerFrontEnd1"
      frontend_ip_configuration.0.private_ip_address:            "" => "10.86.146.84"
      frontend_ip_configuration.0.private_ip_address_allocation: "" => "static"
      frontend_ip_configuration.0.subnet_id:                     "" => "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw/providers/Microsoft.Network/virtualNetworks/vnet-dwp-prd-ss-core-fw/subnets/sub-dwp-prd-ss-core-fw-core-out"
      frontend_ip_configuration.1.inbound_nat_rules.#:           "" => <computed>
      frontend_ip_configuration.1.load_balancer_rules.#:         "" => <computed>
      frontend_ip_configuration.1.name:                          "" => "loadBalancerFrontEnd2"
      frontend_ip_configuration.1.private_ip_address:            "" => "10.86.146.68"
      frontend_ip_configuration.1.private_ip_address_allocation: "" => "static"
      frontend_ip_configuration.1.subnet_id:                     "" => "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw/providers/Microsoft.Network/virtualNetworks/vnet-dwp-prd-ss-core-fw/subnets/sub-dwp-prd-ss-core-fw-core-in"
```

**Comment by tombuildsstuff** [comment]
hi @andyt530 

Thanks for opening this issue :)

So that we can dig into this further - would it be possible to confirm(roughly) when and through what means this resource was created? I ask as Azure returns the state of a resource at the time it was last modified, as such if it was created a long time ago it can be required to make some change to this resource to force-update it (e.g. adding and removing a tag) for Azure to update how it represents the resource in the API.

Thanks!

**Comment by andyt530** [comment]
This lb was created a few weeks back (by the portal)

But -  I think the representation is Azure is good:

You can see the Azure CLI2 is able to see the frontend ip configuration ok:

$ azr=`az network lb list -g rg-dwp-prd-ss-core-fw-core`
$ echo $azr | jq .[0].frontendIpConfigurations
[
  {
    "additionalProperties": {},
    "etag": "W/\"4cc46455-1116-4d69-9f8e-089fa33a2a77\"",
    "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/frontendIPConfigurations/loadBalancerFrontEnd1",
    "inboundNatPools": null,
    "inboundNatRules": null,
    "loadBalancingRules": [
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/IPSEC-IKE1",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      },
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/IPSEC-NATT1",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      },
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/TINA-UDP",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      },
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/TINA-TCP1",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      }
    ],
    "name": "loadBalancerFrontEnd1",
    "outboundNatRules": null,
    "privateIpAddress": "10.86.146.84",
    "privateIpAllocationMethod": "Static",
    "provisioningState": "Succeeded",
    "publicIpAddress": null,
    "resourceGroup": "rg-dwp-prd-ss-core-fw-core",
    "subnet": {
      "additionalProperties": {},
      "addressPrefix": null,
      "etag": null,
      "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw/providers/Microsoft.Network/virtualNetworks/vnet-dwp-prd-ss-core-fw/subnets/sub-dwp-prd-ss-core-fw-core-out",
      "ipConfigurations": null,
      "name": null,
      "networkSecurityGroup": null,
      "provisioningState": null,
      "resourceGroup": "rg-dwp-prd-ss-core-fw",
      "resourceNavigationLinks": null,
      "routeTable": null,
      "serviceEndpoints": null
    },
    "zones": null
  },
  {
    "additionalProperties": {},
    "etag": "W/\"4cc46455-1116-4d69-9f8e-089fa33a2a77\"",
    "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/frontendIPConfigurations/loadBalancerFrontEnd2",
    "inboundNatPools": null,
    "inboundNatRules": null,
    "loadBalancingRules": [
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/IPSEC-IKE2",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      },
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/IPSEC-NATT2",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      },
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/TINA-UDP2",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      },
      {
        "additionalProperties": {},
        "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw-core/providers/Microsoft.Network/loadBalancers/ilb-vm-prdssfwcore/loadBalancingRules/TINA-TCP",
        "resourceGroup": "rg-dwp-prd-ss-core-fw-core"
      }
    ],
    "name": "loadBalancerFrontEnd2",
    "outboundNatRules": null,
    "privateIpAddress": "10.86.146.68",
    "privateIpAllocationMethod": "Static",
    "provisioningState": "Succeeded",
    "publicIpAddress": null,
    "resourceGroup": "rg-dwp-prd-ss-core-fw-core",
    "subnet": {
      "additionalProperties": {},
      "addressPrefix": null,
      "etag": null,
      "id": "/subscriptions/7e97df51-9a8e-457a-ab7a-7502a771bb36/resourceGroups/rg-dwp-prd-ss-core-fw/providers/Microsoft.Network/virtualNetworks/vnet-dwp-prd-ss-core-fw/subnets/sub-dwp-prd-ss-core-fw-core-in",
      "ipConfigurations": null,
      "name": null,
      "networkSecurityGroup": null,
      "provisioningState": null,
      "resourceGroup": "rg-dwp-prd-ss-core-fw",
      "resourceNavigationLinks": null,
      "routeTable": null,
      "serviceEndpoints": null
    },
    "zones": null
  }
]

**Comment by tombuildsstuff** [comment]
@andyt530 

> This lb was created a few weeks back (by the portal)
> But - I think the representation is Azure is good:

Interesting. Would you mind going to `https://resources.azure.com` and navigating down the chain (Subscriptions -> [Name] -> Resource Groups -> [Name] -> Providers -> Microsoft.Network -> Load Balancers -> [Name]) - on that page you should see something similar to this:

<img width="1388" alt="screen shot 2018-04-24 at 12 55 15" src="https://user-images.githubusercontent.com/666005/39183014-e48a749a-47be-11e8-8742-535e0d9a339d.png">

Would you mind confirming the API version which exists at the end of the Resource ID, as shown here:

<img width="851" alt="screen shot 2018-04-24 at 12 55 27" src="https://user-images.githubusercontent.com/666005/39183015-e7bb03e6-47be-11e8-94db-6048a7bf24e2.png">


Thanks!

**Comment by andyt530** [comment]
Hi - do you need anything else ?

**Comment by tombuildsstuff** [comment]
@andyt530 thanks for the info, not at this time - we'll take a look into this in the near future. Thanks!

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems the issue has gone since I can get "frontend_ip_configuration" data after imported. Could you have a try below tfconfig to check whether the issue still exists?
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-lb-test01"
  location = "eastus2"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctvn-test01"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "acctsub-test01"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_lb" "test" {
  name                = "acctestlb-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Basic"

  frontend_ip_configuration {
    name                          = "Internal"
    private_ip_address_allocation = "Static"
    private_ip_address_version    = "IPv4"
    private_ip_address            = "10.0.2.7"
    subnet_id                     = azurerm_subnet.test.id
  }
}
```

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider. I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
