### ISSUE TITLE
azurerm_mssql_server_security_alert_policy introduces inconsistent behaviour in Azure Portal

### ISSUE THREAD

**Issue by jonmartin136** [hashicorp/terraform-provider-azurerm#11555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0

### Affected Resource(s)

* `azurerm_mssql_server_security_alert_policy`

### Terraform Configuration Files

```hcl
resource azurerm_resource_group rg {
  name     = local.resource_group_name
  location = local.location
}
resource azurerm_storage_account sa {
  name                = local.storage_account_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  min_tls_version          = "TLS1_2"
  identity {
    type = "SystemAssigned"
  }
  network_rules {
    bypass                     = [ "AzureServices", "Logging", "Metrics" ]
    default_action             = "Deny"
    ip_rules                   = [ "10.0.0.0" ]
    virtual_network_subnet_ids = null
  }
}
data azuread_group sql_aad_login_name {
  display_name     = "sql admin"
  security_enabled = true
}
resource azurerm_mssql_server sql {
  name                = local.sql_server_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  version             = "12.0"
  minimum_tls_version = "1.2"
  administrator_login = "sqladmin"
  administrator_login_password = "ThisIsAPassw0rd!"
  azuread_administrator {
    login_username = data.azuread_group.sql_aad_login_name.display_name
    object_id      = data.azuread_group.sql_aad_login_name.id
  }
  identity {
    type = "SystemAssigned"
  }
}
resource azurerm_role_assignment sql {
  scope                  =  azurerm_storage_account.sa.id
  role_definition_name   = "Storage Blob Data Contributor"
  principal_id           = azurerm_mssql_server.sql.identity.0.principal_id
}
resource azurerm_mssql_server_security_alert_policy sql {
  server_name            = azurerm_mssql_server.sql.name
  resource_group_name    = azurerm_mssql_server.sql.resource_group_name
  state                  = "Enabled"
  disabled_alerts        = []
  email_account_admins   = false
  email_addresses        = []
}
resource azurerm_mssql_server_vulnerability_assessment sql {
  depends_on                      = [ azurerm_role_assignment.sql ]
  server_security_alert_policy_id = azurerm_mssql_server_security_alert_policy.sql.id
  storage_container_path          = "${azurerm_storage_account.sa.primary_blob_endpoint}vulnerability-assessment"
  recurring_scans {
    enabled                   = true
    email_subscription_admins = false
    emails                    = []
  }
}
```

### Expected Behaviour

Under "Advanced Threat Protection type" title on the blade the "Configure Threat detection types" link is shown.

![image](https://user-images.githubusercontent.com/30291236/116821851-81129700-ab73-11eb-8ae4-00b78b6c06e4.png)

### Actual Behaviour

**When:** email_account_admins = false AND email_addresses = []
![image](https://user-images.githubusercontent.com/30291236/116821476-e82f4c00-ab71-11eb-84ef-17a0664caaa1.png)
Any portal based GUI changes to either the email field or checkbox has no impact on the "Configure Threat detection types" link from showing again. Updating the field/checkbox values via terraform script will bring back the link.

**When:** email_account_admins = true AND email_addresses = []
![image](https://user-images.githubusercontent.com/30291236/116821702-d1d5c000-ab72-11eb-8fde-aa14378a8338.png)
 

**When:** email_account_admins = false AND email_addresses = [ "jon@email.com" ]
![image](https://user-images.githubusercontent.com/30291236/116821495-f8472b80-ab71-11eb-88fe-9e6dddb79156.png)

After running tests using both PowerShell Cmdlets and ARM Templates I believe that this is a MS REST API issue but it might be worth adding a comment to the documentation - both settings are optional but if not defined [and defaults used] then it is not possible to see whether any alerts are disabled via the portal. 

I have noticed that the Az cmdlet (Update-AzSqlServerAdvancedThreatProtectionSettings) enforces that either the email field [-NotificationRecipientsEmails] is not empty or the admins checkbox [-EmailAdmins] is set to true before it executes; this is contrary to the documentation for both ARM and the REST API.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
