### ISSUE TITLE
Panic/crash on azurerm_app_service

### ISSUE THREAD

**Issue by vfab-insight** [hashicorp/terraform-provider-azurerm#11584]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.1, v0.15.0, v0.14.11, v0.14.10
AzureRM v2.43.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
# Resource that the error is complaining about
locals {
   default_documents = "Default.htm,Default.html,Default.asp,index.htm,index.html,iisstart.htm,default.aspx,index.php,hostingstart.html"
}

resource "azurerm_app_service" "main" {
  for_each = var.webappservices

  dynamic "site_config" {
    for_each = [{ key = "value" }]

    content {
      . . .
      # This line is what caused the crash.  Comment this out and it works fine.
      default_documents = split(",", lookup(each.value, "default_documents", local.default_documents))
      . . .
   }
   . . .
}

# The variable
variable "webappservices" {
  description = "List of WebApp services need to be created."
  type        = any
}

# The variable as populated in the .tfvars file
webappservices = {
  "application"    = {
    always_on                   = "true"
    https_only                  = "false"
    http2_enabled               = "true"
    client_affinity_enabled     = "true"
    default_documents  = ""
    .
    .
    .
  },
  "emailsubscriber" = {
    always_on                    = "false"
    https_only                   = "false"
    http2_enabled                = "false"
    default_documents  = ""Default.htm,Default.html"
    client_affinity_enabled      = "true"
    affinity_cookie_name         = null
  },
   .
   .
   .
```

### Debug Output

https://gist.github.com/vfab-insight/cb01777e2b7e57cff6abd1a0fdacad0d

### Panic Output

https://gist.github.com/vfab-insight/cb01777e2b7e57cff6abd1a0fdacad0d

### Expected Behaviour

Should have deployed the web apps with the specified default_documents property.

### Actual Behaviour

Panic / Crash 

### Steps to Reproduce

1. Execute `terraform apply` with the `.tfvars` file

**Comment by rcskosir** [comment]
Thanks for reporting this issue! The azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources, if you have not already.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
