### ISSUE TITLE
azurerm_monitor_action_group doesn't link to ITSM connector properly.

### ISSUE THREAD

**Issue by jbla9028** [hashicorp/terraform-provider-azurerm#11596]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v14.5 
AzureRM 2.48.0

### Affected Resource(s)

azurerm_monitor_action_group

### Terraform Configuration Files

resource "azurerm_monitor_action_group" "action_group" {
name = "ag-sn-dev-systems"
resource_group_name = data.azurerm_resource_group.lga_rg.name
short_name = "SNOWdev-so"

itsm_receiver {
name = "SNOWDev"
workspace_id = "%Log Analytics WorkspaceID"
connection_id = "%SNOW ITSM connectionID%"
ticket_configuration = jsonencode({"CreateOneWIPerCI"=true,
"PayloadRevision" = null,
"CreateOneWIPerLog"=false,
"WorkItemData" = {
"resource" = "assignment_group:[Systems]",
"severity" = 2
}
"WorkItemType" = "Event"
})
region = var.location
}
}

### Debug Output
![image](https://user-images.githubusercontent.com/44985530/117210034-296b6a00-adc5-11eb-83f6-032fc6df5f63.png)

### Expected Behaviour
After building the monitor group, the ITSM connector should be properly linked and retain the ticket details.

### Actual Behaviour
The apply was successful but when reviewing the deployment within the portal I get this error.
"The ITSM action %SNOW ITSM connectionID% points to an ITSM connection that has been deleted or moved. Please delete or modify this ITSM action."

I then go through the portal and go to set the action group settings to what we need them to match what's expected in the terraform code. When I then run a terraform plan, I am noticing that the connection_id field wants to be updated with a piped value. one is the connection_Id of the ITSM connector and I think the other is the workspace_id.

### Steps to Reproduce

1. `terraform apply`
2. Review output in the portal.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
