### ISSUE TITLE
azurerm_app_service_certificate_order missing required KeyVault integration

### ISSUE THREAD

**Issue by ricohomewood** [hashicorp/terraform-provider-azurerm#11657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0

### Affected Resource(s)

azurerm_app_service_certificate_order

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_app_service_certificate_order" "certificate" {
  name                = "my-cert"
  resource_group_name = azurerm_resource_group.example.name
  location            = "global"
  distinguished_name  = "CN=my.example.com"
  product_type        = "Standard"
}
```

### Expected Behaviour

An App Service Certificate Order should be created and configure with a required Key Vault Store as per the resource. 

### Actual Behaviour

An App Service Certificate order creates the certificate with missing Key Vault Store implementation and updates the terraform state file with an empty `certificate` list of object as it completes the resource create in a pending state.

### Steps to Reproduce

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_app_service_certificate_order" "certificate" {
  name                = "my-cert"
  resource_group_name = azurerm_resource_group.example.name
  location            = "global"
  distinguished_name  = "CN=my.example.com"
  product_type        = "Standard"
}
```
1. `terraform apply`
2. Note that this makes a certificate request to GoDaddy so cost associated
3. Observe the certificate order warning in the portal `Configure Required Key Vault store`.
4. Also inspect the state file to see that the `certificates` list of objects property is empty even after successfully ordering that certificate. Run `terraform state show  azurerm_app_service_certificate_order.certificate` and `status` will be set to `"Pendingissuance"` 

### References

This was initially created in ticket https://github.com/terraform-providers/terraform-provider-azurerm/issues/2038

The Azure documentation shows this KV association should be implemented as per below and is specified in the Azure SDK for GO
https://github.com/Azure/azure-sdk-for-go/blob/master/services/web/mgmt/2020-12-01/web/appservicecertificateorders.go

https://docs.microsoft.com/en-us/rest/api/appservice/appservicecertificateorders/createorupdatecertificate

* #0000

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
