### ISSUE TITLE
Management group scope in role definition fails

### ISSUE THREAD

**Issue by undergroundwires** [hashicorp/terraform-provider-azurerm#11656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```txt
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.58.0
```

### Affected Resource(s)

- `azurerm_role_definition`

### Terraform Configuration Files

```hcl
resource azurerm_role_definition custom {
  name = "custom"
  scope = "/providers/microsoft.management/managementGroups/${var.management_group_id}"
  permissions {
    actions = [
      "Microsoft.Authorization/roleDefinitions/*",
      "Microsoft.Authorization/roleAssignments/*",
    ]
  }
  assignable_scopes = ["/providers/microsoft.management/managementGroups/${var.management_group_id}"]
}
```

### Expected Behaviour

No error. Role definition can be found by the provider.

### Actual Behaviour

```txt
failed to parse scope from Role Definition ID "/providers/Microsoft.Authorization/roleDefinitions/xxxxxx-xxxxxx-xxx-xxx-xxxxxx|/providers/microsoft.management/managementGroups/xxxxxx"
```

Fails at the line where role definition is created `resource "azurerm_role_definition" "custom"`

### Steps to reproduce

1. `terraform init`
2. `terraform apply`

### References

- Has same ID construction as #8426
- Similar problem but on `destroy`:  • #6695 • #5125

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
