### ISSUE TITLE
SecurityInsights - Sentinel Scheduled Rules: support for entityMappings 

### ISSUE THREAD

**Issue by kaovd** [hashicorp/terraform-provider-azurerm#11667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm putting an issue here as a Todo and currently as blocked. See https://github.com/Azure/azure-rest-api-specs/issues/14078 as this has not yet been implemeneted within swagger. 
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview

Recently a new preview feature has come into the creation of Azure Sentinel Scheduled rules, whereby entities are now being defined in the alert Properties rather than in the query, whereby the traditional style was to include something in the query such as | extend AccountCustomEntity = AccountName is is now defined as:

```
entityMappings: [ {entityType: "Type", fieldMappings: [ {identifer: "Identifer", columnName: "columnName"} ] } 
]
```
in properties

The 2021-03-01-preview seems to currently be in heavy dev and does not have a single SecurityInsights.json full spec yet.

We may need a dedicated issue for the eventual 2021-03-01-preview migration if this is not backported. to 2019-01-01-preview, which is what current sentinel implementation is using. 
### New or Affected Resource(s)

- azurerm_sentinel_alert_rule_scheduled
- azurerm_sentinel_alert_rule_template_data_source (needs upgrade as a result for new property)

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  name                       = "example"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
  display_name               = "example"
  severity                   = "High"
  query                      = <<QUERY
AzureActivity |
  where OperationName == "Create or Update Virtual Machine" or OperationName =="Create Deployment" |
  where ActivityStatus == "Succeeded" |
  make-series dcount(ResourceId) default=0 on EventSubmissionTimestamp in range(ago(7d), now(), 1d) by Caller
QUERY

  entity_mapping {
    entity_type = "AzureResource" //Create a mapping for a resource id
    field_mappings {
      identifier="ResourceId" //Static options
      column_name="ResourceId" //This is the field from within the query
    }
  }

  entity_mapping {
    entity_type = "Account" //Create a mapping for an Account
    field_mappings {
      identifier="UPNSuffix" //Static options
      column_name="Caller" //This is the field from within the query
    }
    field_mappings {
      identifier="SID" //Static options
      column_name="userSID" //This is the field from within the query (Not applicable in AzureActivity but just an example)
    }
  }

}
```

### References
https://github.com/Azure/azure-rest-api-specs/issues/14078
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview

**Comment by kaovd** [comment]
It appears this change is now in, https://github.com/Azure/azure-rest-api-specs/blob/master/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview/AlertRules.json

See PR https://github.com/Azure/azure-rest-api-specs/commit/61e7148e9592c5efc95e5c16a5bb4f2dc26d6de0

Pending coming down into Go SDK, Will test a bump to Scheduled rules to this new API Version which will enable entityMappings, customDetails.  Also think some of the enums / terms in grouping changed.

**Comment by kaovd** [comment]
Service request now up https://github.com/Azure/azure-sdk-for-go/issues/14800

**Comment by kevinkle** [comment]
Not exactly what you're looking for, but been doing this in the Kusto query in azurerm_sentinel_alert_rule_scheduled resources. Such as:

```kusto
| extend AccountCustomEntity = UserPrincipalName, IPCustomEntity = IPAddress
```

As in the rule templates `Failed host logons but success logon to AzureAD`

```kusto
//Adjust this threshold to fit environment
let signin_threshold = 5; 
//Make a list of IPs with failed Windows host logins above threshold
let win_fails = 
SecurityEvent
| where EventID == 4625
| where LogonType in (10, 7, 3)
| where IpAddress != "-"
| summarize count() by IpAddress
| where count_ > signin_threshold
| summarize make_list(IpAddress);
//Make a list of IPs with failed *nix host logins above threshold
let nix_fails = 
Syslog
| where Facility contains 'auth' and ProcessName != 'sudo'
| extend SourceIP = extract("(([0-9]{1,3})\\.([0-9]{1,3})\\.([0-9]{1,3})\\.(([0-9]{1,3})))",1,SyslogMessage)
| where SourceIP != "" and SourceIP != "127.0.0.1"
| summarize count() by SourceIP
| where count_ > signin_threshold
| summarize make_list(SourceIP);
//See if any of the IPs with failed host logins hve had a sucessful Azure AD login
let aadFunc = (tableName:string){
table(tableName)
| where ResultType !in ("0", "50125", "50140")
| where IPAddress in (win_fails) or IPAddress in (nix_fails)
| extend Reason=  "Multiple failed host logins from IP address with successful Azure AD login"
| extend timstamp = TimeGenerated, AccountCustomEntity = UserPrincipalName, IPCustomEntity = IPAddress, Type = Type
};
let aadSignin = aadFunc("SigninLogs");
let aadNonInt = aadFunc("AADNonInteractiveUserSignInLogs");
union isfuzzy=true aadSignin, aadNonInt
```
