### ISSUE TITLE
azurerm_storage_management_policy having issue while refreshing the terraform state

### ISSUE THREAD

**Issue by VijayaAlbu** [hashicorp/terraform-provider-azurerm#11680]
Terraform (and AzureRM Provider) Version
Provider azurerm 2.56.0 
Terraform version:
Terraform v0.13.5

Affected Resource(s)
azurerm_storage_management_policy
azurerm_storage_account

Terraform Configuration Files
terraform
resource "azurerm_storage_account" "this" {
  name                = local.main_resource_name
  resource_group_name = azurerm_resource_group.this.name

  location                  = var.location
  account_tier              = "Standard"
  account_replication_type  = var.account_replication_type
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
  is_hns_enabled            = true
  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = var.subnet_ids
    bypass                     = ["Logging", "Metrics", "AzureServices"]
  }

azurerm_storage_management_policy
resource "azurerm_storage_management_policy" "example" {
  storage_account_id = var.storage_account_id

  rule {
    name    = var.name
    enabled = true
    filters {
      prefix_match = [var.prefix_match]
      blob_types   = [var.blob_types]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than = var.tier_to_cool_after_days_since_modification_greater_than
        # tier_to_archive_after_days_since_modification_greater_than = var.tier_to_archive_after_days_since_modification_greater_than
        delete_after_days_since_modification_greater_than       = var.delete_after_days_since_modification_greater_than
      }
      snapshot {
        delete_after_days_since_creation_greater_than = var.delete_after_days_since_creation_greater_than
      }
    }
  }
}
Expected Behaviour
azurerm_storage_account should be recreated if it is not available in real state

Actual Behaviour
azurerm_storage_account is deleted manually then terraform plan is not able to identify the missing resources,

Steps to Reproduce
1. terraform apply
2.delete the storage account or comment out the storage account code
3.terraform plan

**Comment by tombuildsstuff** [comment]
Consolidating into #12933
