### ISSUE TITLE
Support or tooling for Azure Resource Move

### ISSUE THREAD

**Issue by aristosvo** [hashicorp/terraform-provider-azurerm#11747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It takes up a lot of time to simply move Azure Resources (in Terraform) to a different subscription.

1. Move resource in Azure Portal or via `az cli`
2. Remove resource in `terraform`, `terraform state rm module.storage.azurerm_mysql_server`
3. Import resource in `terraform`, `terraform import module.storage.azurerm_mysql_server <new_id>`
4. Change `azurerm` provider in terraform config

It would be awesome to simply type:
```
aztfmove -tfresource module.storage.azurerm_mysql_server -target-resource-group test-move-rg [-target-subscription test-subscription]
```
or:
```
aztfmove -tfresource module.storage -target-resource-group test-move-rg [-target-subscription test-subscription]
```

### New or Affected Resource(s)

* `azurerm_*` (resources which support a move in Azure)

#### Example before:

```hcl
# main.tf:
provider "azurerm" {
  features {}
}

module "storage" {
  source = ./modules/storage
  ...
}

# module.storage:
resource "azurerm_mysql_server" "mysql" {
  version                      = "5.7"
  administrator_login          = "example-admin"
  administrator_login_password = data.azurerm_key_vault_secret.mysql-server-password.value
  resource_group_name          = var.context.resource_group_name
  location                     = var.location
  name                         = "${var.context.prefix}-mysql"
  ssl_enforcement_enabled      = "true"

  sku_name = var.mysql_sku

  tags = var.context.tags

  auto_grow_enabled            = "true"
  storage_mb                   = var.mysql_size_mb
  backup_retention_days        = 7
  geo_redundant_backup_enabled = "false"
}
```

#### Example after:

```hcl
# main.tf:
provider "azurerm" {
  features {}
}

provider "azurerm" {
  alias           = "move"
  subscription_id = "<target-subscription>"
  features {}
}

module "storage" {
  source = ./modules/storage
  provider {
    azurerm.move = azurerm.move
  }
  ...
}

# module.storage:
provider "azurerm" {
  alias = "move"
}

resource "azurerm_mysql_server" "mysql" {
  provider = azurerm.move

  version                      = "5.7"
  administrator_login          = "example-admin"
  administrator_login_password = data.azurerm_key_vault_secret.mysql-server-password.value
  resource_group_name          = var.context.resource_group_name
  location                     = var.location
  name                         = "${var.context.prefix}-mysql"
  ssl_enforcement_enabled      = "true"

  sku_name = var.mysql_sku

  tags = var.context.tags

  auto_grow_enabled            = "true"
  storage_mb                   = var.mysql_size_mb
  backup_retention_days        = 7
  geo_redundant_backup_enabled = "false"
}
```

### References

- https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription

### Notes
I'm absolutely in to create a tool like this myself, it's just that I'm not sure if this is functionality more users need and want, or which usecases it should support!

**Comment by magodo** [comment]
@aristosvo This seems to be duplicated as #1733?

**Comment by aristosvo** [comment]
@magodo I agree it is kind of a duplicate, but the direction of the solution makes it viable and interesting for users of the Azure Terraform provider.

I'm halfway with a MVP to prove my point 😇

**Comment by aristosvo** [comment]
First version available here: https://github.com/aristosvo/aztfmove
