### ISSUE TITLE
Upgrade an AKS cluster with managed identity and aad-pod-identity enabled

### ISSUE THREAD

**Issue by alxy** [hashicorp/terraform-provider-azurerm#11764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.3
hashicorp/azurerm v2.59.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# define a variable here to easily upgrade kubernetes
variable "kubernetes_version" {
  type        = string
  description = "The version of kubernetes for the AKS cluster and nodes."
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                = "aks-${var.app_name}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group.name
  dns_prefix          = "aks-${var.app_name}-${var.environment}"
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    type                 = "VirtualMachineScaleSets"
    name                 = "default"
    node_count           = 3
    vm_size              = "Standard_D2s_v3"
    os_disk_size_gb      = 30
    vnet_subnet_id       = azurerm_subnet.aks.id
    enable_auto_scaling  = true
    max_count            = 5
    min_count            = 3
    orchestrator_version = var.kubernetes_version
    upgrade_settings {
      max_surge = 1
    }
  }

  network_profile {
    network_plugin = "azure"
  }

  role_based_access_control {
    enabled = true
  }

  identity {
    type = "SystemAssigned" # we are using a system assigned managed identity here
  }
}

# assign kubelet identity (system assigned managed identity) the required roles
resource "azurerm_role_assignment" "all_mi_operator" {
  scope                = data.azurerm_resource_group.aks_node_rg.id
  principal_id         = azurerm_kubernetes_cluster.aks.kubelet_identity.0.object_id
  role_definition_name = "Managed Identity Operator"
}
```

This is a simplified extract from out code. We basically use an AKS cluster where we enabled the system managed identity and we also use user assigned identities bound to our pods to authenticate against other Azure services. In our case we load secrets from key vault using the [Secret store CSI driver](https://github.com/Azure/secrets-store-csi-driver-provider-azure) in combination with [AAD pod identity](https://github.com/Azure/aad-pod-identity). If my understanding is correct the `Managed Identity Operator` role is needed for kubernetes to do exactly these bindnings between pods (applications running in the cluster) and the user assigned managed identities (distinct Azure resource).

This is all working fine, however, there is an issue when we upgrade the cluster. In this case, we have created a variable for `kubernetes_version` and increase that whenever there is a new release and populate it through our environments. When we plan the upgrade we get the following output:

### Example Plan Output

```
# azurerm_kubernetes_cluster.aks will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "aks" {
        id                              = "/subscriptions/xxxx/resourcegroups/xxxx/providers/Microsoft.ContainerService/managedClusters/aks-xxx-dev"
      ~ kubernetes_version              = "1.20.2" -> "1.20.5"

        }
        # (14 unchanged attributes hidden)



      ~ default_node_pool {
            name                         = "default"
          ~ orchestrator_version         = "1.20.2" -> "1.20.5"
            tags                         = {}
            # (16 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }




        # (6 unchanged blocks hidden)
    }

  # azurerm_role_assignment.all_mi_operator must be replaced
-/+ resource "azurerm_role_assignment" "all_mi_operator" {
      ~ id                               = "/subscriptions/xxxxx/resourceGroups/MC_rg-xxxxx/providers/Microsoft.Authorization/roleAssignments/xxxxx" -> (known after apply)
      ~ name                             = "84d87da0-6ce4-4caf-b42e-6107df383040" -> (known after apply)
      ~ principal_type                   = "ServicePrincipal" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/xxxx/providers/Microsoft.Authorization/roleDefinitions/xxxxx" -> (known after apply)
      ~ scope                            = "/subscriptions/xxxx/resourceGroups/MC_rg-xxxx" -> (known after apply) # forces replacement
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    }


```

### Example Apply output

```
azurerm_role_assignment.all_mi_operator: Destroying...
azurerm_kubernetes_cluster.aks: Modifying... 
azurerm_role_assignment.all_mi_operator: Destruction complete after 1s
....
azurerm_kubernetes_cluster.aks: Still modifying... 
azurerm_kubernetes_cluster.aks: Modifications complete after 18m15s
azurerm_role_assignment.all_mi_operator: Creating...
azurerm_role_assignment.all_mi_operator: Creation complete after 22s
```

So, as you can see, even though we didn't change anything except the `kubernetes_version`, it also needs to re-create the role assignment. The problem with that process is that during the time of the upgrade (~20 mins) the applications running on the cluster are not available. Kubernetes quite correctly tries to upgrade one node after the other and also tries to migrate the pods to a new node before killing the old node. However, the pods cannot start correctly on the new (upgraded) nodes as they don't have access to key vault, and the kubelet identity cannot bind the user assigned MIs to the pods, as it doesn't have the `Managed Identity Operator` role (yet). Result is that we have a lot of pods failing to start; the good news is that the cluster and pods recover automatically once the role assignment is back.

### Expected Behaviour

I am not sure what I should expect or if this is an issue with AKS/kubernetes itself or the provider, but I would assume that there should be a way to do zero-downtime upgrades of the cluster. Ideally, upgrading the cluster should not trigger a re-creation of the role assignments.

**Comment by aristosvo** [comment]
Hi @alxy! 👋 

I struggle with these things a few times a year as well when upgrading AKS. There are multiple routes towards a solution here, but the one solution I'd use myself probably is by BYO kubelet managed identity. By creating the managed identity separate and assigning it to the cluster, all assignments can be done without a direct dependency on computed outputs of AKS.

Other options are:
- using a targeted apply in case of upgrades
- upgrade manually/outside and ignore versions of AKS within TF
- use the mentioned aad-pod-identity as add-on. I've no experience with this one
- Enable auto-upgrade for AKS, ignore versions of AKS within TF

Does one of these solutions solve your problem? To be honest I don't think better solutions are available, good luck going forward!

**Comment by alxy** [comment]
Thanks for your suggestion @aristosvo 

What we have done is split the role assignments and the AKS resource creation in two different modules, as we were also facing other issues with the setup. Reason was that we were also deploying the Helm chart for `aad-pod-identity` within the same module, which is a very bad idea. Now that we have split it into `infra` and `kubernetes` (incl role assignments) modules, it works much better :)

**Comment by aristosvo** [comment]
@alxy Ouch, forgot that option 😄 Just curious, did you split it in a different modules under the same root module (which are planned at the same time) or did you split it in two different root modules (`infra` and `kubernetes`) with it's own `plan` and `apply` cycle?

I think you can close this issue, as the problems with AKS as a Terraform resource and subsequent resources are well-known, but thus far impossible to fix on resource level. I'd recommend in general a strong split between those, which is mentioned and backed up elsewhere as well, and again to be proven successful 🎉

**Comment by alxy** [comment]
In two different root modules. We orchestrate the [dependencies between them using Terragrunt](https://terragrunt.gruntwork.io/docs/features/execute-terraform-commands-on-multiple-modules-at-once/#passing-outputs-between-modules), which is working really nice.
