### ISSUE TITLE
app_service_certificate not deploying properly and app_service_certificate_binding 404 error

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#11771]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.46.0

### Affected Resource(s)

* `azurerm_app_service_certificate`
* `azurerm_app_service_certificate_binding`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate" "app_cert" {
  name                                            = data.azurerm_key_vault_certificate.key_vault_certificate.name
  resource_group_name                 = var.resource_group_name
  location                                        = var.location
  hosting_environment_profile_id  = var.ase_id
  key_vault_secret_id                      = data.azurerm_key_vault_certificate.key_vault_certificate.id
}

resource "azurerm_app_service_certificate_binding" "cert_binding" {
  hostname_binding_id     = azurerm_app_service_custom_hostname_binding.hostname_binding.id
  certificate_id                   = azurerm_app_service_certificate.app_cert.id
  ssl_state                          = "SniEnabled"
}
```

### Debug Output

Error: Error creating/updating Custom Hostname Binding "testdomain.net" (App Service "TESTAPPSERVICE" / Resource Group "TESTRSG"): web.AppsClient#CreateOrUpdateHostNameBinding: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Certificate 82D...ADC was not found." Details=[{"Message":"Certificate 82D...ADC was not found."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"04031","Message":"Certificate 82D...ADC was not found.","MessageTemplate":"Certificate {0} was not found.","Parameters":["82D...ADC"]}}]

### Expected Behaviour

Certificate should have been deployed to app_service and binding should have been successful

### Actual Behaviour

Certificate deploys, but `app_service_certificate_binding` is unable to see it.  Certificate also does not show up in the app_service.

### Steps to Reproduce

1. Deploy a valid app_service with ASE
2. Have a valid certificate and custom domain
2. `terraform apply`

### Important Factoids

If certificate is manually imported to the app_service and the thumbprint copied to terraform, the binding is successful.

### References

* #0000

**Comment by zpbonjour** [comment]
hosting_environment_profile_id is optional.  I am not using it and I am not seeing this issue.

**Comment by calebak404** [comment]
`hosting_environment_profile_id` is required when you are deploying inside of an App Service Environment.

**Comment by haraldatbmw** [comment]
If I look at the created certificate via az-command `az webapp config ssl list --resource-group my-group` the `hostingEnvironmentProfile` stays `null`.  If I create one via Azure web-portal the `hostingEnvironmentProfile` is filled correct.

```
resource "azurerm_app_service_certificate" "my-cert" {
  name                           = "my-cert"
  resource_group_name            = "my-group"
  location                       = "westeurope"
  hosting_environment_profile_id = "/subscriptions/xxx/resourceGroups/my-ase/providers/Microsoft.Web/hostingEnvironments/my-ase"
  pfx_blob                       = filebase64("my-cert.pfx")
  password                       = "xxx"
}
```
