### ISSUE TITLE
Azure ARM template requires array data input, Terraform only allows string parameters.

### ISSUE THREAD

**Issue by zpbonjour** [hashicorp/terraform-provider-azurerm#11788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Latest versions are being used.

### Affected Resource(s)

azurerm_template_deployment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Inappropriate value for attribute "parameters": element "keyValueValues": string required.

### Expected Behaviour

The KeyValueName and KeyValueValue parameters are required to be an array in the ARM template.  I need to pass an Array data type, not a string.

### Actual Behaviour

Terraform does not allow an array type in the ARM parameter inputs.

### Steps to Reproduce

Attempt to deploy the linked ARM template with Terraform.

### Important Factoids

Using Terraform Cloud

### References
https://docs.microsoft.com/en-us/azure/azure-app-configuration/quickstart-resource-manager

* #0000

**Comment by magodo** [comment]
@zpbonjour Thank you for submitting this issue!

In case of [azurerm_resource_group_template_deployment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment), the `parameters_content` takes a json representation of the input parameters. If you want some input to be an array, you can do something like:

```hcl
  parameters_content = jsonencode({
    "keyValueNames" = {
      value = ["myKey", "myKey$myLabel"]
    }
  })
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
