### ISSUE TITLE
cdn_endpoint - Documentation about value of [order] attribute in block [delivery_rule] is wrong

### ISSUE THREAD

**Issue by jhauray** [hashicorp/terraform-provider-azurerm#11806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.2.2
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0

### Affected Resource(s)

* `cdn_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_profile" "profil_cnd_ms" {
  name                = "cdn-profile-ms"
  location            = "westeurope"
  resource_group_name = "myrg"
  sku                 = "Standard_Microsoft"
}

resource "azurerm_cdn_endpoint" "endpoint_cdn_ms" {
  name                          = "edp-01-profile-ms"
  profile_name                  = azurerm_cdn_profile.profil_cnd_ms.name
  location                      = "westeurope"
  resource_group_name           = "myrg"

  delivery_rule {
    name  = "EnforceHTTPS"
    order = 2

    request_scheme_condition {
      operator     = "Equal"
      match_values = ["HTTP"]
    }

    url_redirect_action {
      redirect_type = "Found"
      protocol      = "Https"
    }

  }
}
```

### Debug Output

```bash
Error: Error updating CDN Endpoint "edp-01-profile-ms" (Profile "cdn-profile-ms" / Resource Group "rg-xxxxxxxxxxxxxxxxxx"): cdn.EndpointsClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="The delivery rules order values must be sequential."
```

### Expected Behaviour

Documentation (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint#order) should indicate correct allowed values for attribute `order` : Greater than 0.

As describe in Azure REST Api documentation : https://docs.microsoft.com/en-us/rest/api/cdn/cdn/endpoints/create#deliveryrule

> The order in which the rules are applied for the endpoint. Possible values {0,1,2,3,………}. A rule with a lesser order will be applied before a rule with a greater order. Rule with order 0 is a special rule. It does not require any condition and actions listed in it will always be applied.

I've deduced that order 0 is for `global_delivery_rule`. So `delivery_rule` must accept order with values greater than 0.

And finally, CDN profile and CDN Endpoint, who contain only one rule must be created successfully.

### Actual Behaviour

Documentation (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint#order) indicate that "The order used for this rule, which must be larger than 1."

I define `order` with a value compliant with documentation : "2".
Provisionning stop with the error shown in debug log.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
closing as this was fixed by #14050
