### ISSUE TITLE
azurerm_policy_set_definition accesses incorrect scope with management_group_name set

### ISSUE THREAD

**Issue by ToxicGLaDOS** [hashicorp/terraform-provider-azurerm#11811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.59.0
```

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

`main.tf`
```hcl
terraform {
  # Intentionally empty. Will be filled by Terragrunt.
  backend "azurerm" {}
}

provider "azurerm" {
  version = ">= 2.0, <3.0"
  features {}
}

resource "azurerm_policy_set_definition" "initiative" {
  name         = "Apply Diagnostics Settings Initiative"
  policy_type  = "Custom"
  display_name = "My Initiative"

  management_group_name   = var.management_group_name
  //management_group_id   = var.management_group_id
  //management_group_name = var.management_group_id

  metadata     = <<METADATA
    {
    "category": "Monitoring",
    "description": "Batch of Azure Policies to deploy diagnostics settings to all azure resources"
    }
  METADATA

  policy_definition_reference {
    policy_definition_id = var.policy_id
  }
}
```
`variables.tf`
```hcl
variable "management_group_name" {
}

variable "management_group_id" {
}

variable "policy_id" {
  description = "Policy id"
  type = string
}

```

`management_group_name` contains the name of the management group (`ev-org-mg` for instance)
`management_group_id` contains the id of the management group (`db83946a-4e44-4352-802f-e82d395a2238` for instance)

### Expected Behaviour

Terraform creates a policy initiative under the given management group

### Actual Behaviour

Terraform succeeds to plan, but errors with this message on apply

```
Error: creating Policy Set Definition "Apply Diagnostics Settings Initiative": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'me@me.com' with object id '<my-object-id>' does not have authorization to perform action 'Microsoft.Authorization/policySetDefinitions/write' over scope '/providers/Microsoft.Management/managementgroups/ev-org-mg/providers/Microsoft.Authorization/policySetDefinitions/Apply Diagnostics Settings Initiative' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

However, if I swap the `management_group_name    = var.management_group_name` line out for either of the two commented out lines it works.

The bug appears to be in the construction of the scope ID for the Initiative. The error message tells us the scope is
```
/providers/Microsoft.Management/managementgroups/ev-org-mg/providers/Microsoft.Authorization/policySetDefinitions/Apply Diagnostics Settings Initiative
``` 
when we should get
```
/providers/Microsoft.Management/managementgroups/db83946a-4e44-4352-802f-e82d395a2238/providers/Microsoft.Authorization/policySetDefinitions/Apply Diagnostics Settings Initiative
```

It seems like the `management_group_name` field is being treated the same as the `management_group_id` field is, when it should be converted into an id before using it to construct the scope.

### Steps to Reproduce

1. Define a `azurerm_policy_set_definition` resource with the `management_group_name` field set to the name of the management group
2. `terraform apply`

### Important Factoids

I'm using [terragrunt](https://terragrunt.gruntwork.io/).

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
