### ISSUE TITLE
azurerm_app_service_managed_certificate tags not being stored in Azure

### ISSUE THREAD

**Issue by NestorRV** [hashicorp/terraform-provider-azurerm#11816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.15.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.60.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```
### Affected Resource(s)

* `azurerm_app_service_managed_certificate`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_managed_certificate" "cert" {
  ...
  tags = { ... }
}
```

### Debug Output
```
resource "azurerm_app_service_managed_certificate" "cert" {
  id = "..."
  ~ tags                       = {
      + "..." = "..."
    }
    # (8 unchanged attributes hidden)
}
```
### Expected Behaviour

Tags should be storage in Azure

### Actual Behaviour

Every time I run a `terraform plan`, the change in the tag is displayed because they are not being saved in azure.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by AliAllomani** [comment]
Looks an Azure API/SDK Issue

Created:

* https://github.com/Azure/azure-rest-api-specs/issues/14529
* https://github.com/Azure/azure-sdk-for-go/issues/14700

**Comment by NestorRV** [comment]
Perfect, thanks @AliAllomani! What is the process for getting this fixed? Wait for Microsoft and then a new version of the provider will be released?

**Comment by AliAllomani** [comment]
@NestorRV We need to wait for Microsoft’s response and from there we can see how to go further, a fix on terraform side may or may not be required

**Comment by NestorRV** [comment]
Perfect, thanks for the explanation @AliAllomani !

**Comment by alexs77** [comment]
@AliAllomani any progress here? I'm still seeing that tags don't seem to get applied, with hashicorp/azurerm v2.98.0.

**Comment by drdamour** [comment]
we opened a support ticket on the upstream...first MS told us that tags werent' supported....after proving that they were, they directed us to use the https://docs.microsoft.com/en-us/rest/api/appservice/certificates/update?tabs=HTTP#code-try-0 method instead of https://docs.microsoft.com/en-us/rest/api/appservice/certificates/create-or-update?tabs=HTTP#code-try-0  even though tags are NOT documented there from what i can tell..

@AliAllomani @katbyte  is this a viable option for tf?

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!

**Comment by drdamour** [comment]
this is still an issue
