### ISSUE TITLE
Add `user_data` option to VM resources

### ISSUE THREAD

**Issue by schnerring** [hashicorp/terraform-provider-azurerm#11846]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> [User data through Azure Instance Metadata Service now generally available](https://azure.microsoft.com/en-us/updates/user-data-through-azure-instance-metadata-service-now-generally-available/):
> 
> Today, we are announcing the general availability of user data, enabling you to insert your own metadata into a Microsoft Azure virtual machine at **provisioning time**, with the ability to retrieve it using the Azure Instance Metadata Service (IMDS).

Azure Portal already supports that feature (Azure CLI and PWSH not yet):

![image](https://user-images.githubusercontent.com/3743342/119405744-482c9480-bcd1-11eb-8a64-d42af27dd7db.png)

### New or Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_windows_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_windows_virtual_machine_scale_set`

### Potential Terraform Configuration

It is used exactly like the existing `custom_data` field.

### References

* [Create user data for Azure VM/VMSS (MSFT docs)](https://docs.microsoft.com/en-us/azure/virtual-machines/user-data#create-user-data-for-azure-vmvmss)

**Comment by et304383** [comment]
User Data has been available for 8 months.  I never saw this kind of feature lag with the AWS provider.  No Azure love?
