### ISSUE TITLE
Add support for Enterprise Agreement customers to create Azure Subscriptions using azurerm_subscription Terraform Provider.

### ISSUE THREAD

**Issue by njpatel54** [hashicorp/terraform-provider-azurerm#11872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As per my testing for "Azure US Government", below listed Terraform Provider (azurerm_subscription) only allow Azure Subscription creation for customers with "Microsoft Customer Agreement". Please add support for "Enterprise Agreement" customers to create Azure Subscriptions using this Terraform Provider.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription

### New or Affected Resource(s)

azurerm_subscription

**Comment by jackofallops** [comment]
Hi @njpatel54 - I cannot test for Gov Cloud specifically, but I can can confirm that EA accounts are supported and I have confirmed locally using the Public cloud that they are still working.  Are you able to provide any details for the failure on Gov Cloud that I may be able to use to diagnose the issue there? If not, can you check that the account with which you are running terraform has appropriate permissions on your EA to create Subscriptions.  In public cloud this requires one of the following Role Definitions to be assigned:

* `Enrollment account owner` - Definition ID: `c15c22c0-9faf-424c-9b7e-bd91c06a240b`
* `Enrollment account subscription creator` - Definition ID: `a0bcee42-bf30-4d1b-926a-48d21664ef71`

I cannot conform if these IDs are the same in the Gov cloud, but they should be discoverable via the cli using:
```
az billing role-definition list --account-name `{AZURE_ACCOUNT_NAME}`
```
Additionally, we provide a [data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/billing_enrollment_account_scope) to help with the `billing_scope_id` field property: `azurerm_billing_enrollment_account_scope`, are you using this? 

I hope this helps, but I'm happy to try to assist further if you are able to supply additional information on what the failure is.

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
