### ISSUE TITLE
virtual_machine_extension intermittent timeouts when deploying with linux vm's

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#11940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `Terraform v0.13.5`
* `hashicorp/azurerm v2.60.0`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "NetworkWatcher-lnx_vm" {
  for_each                   = azurerm_linux_virtual_machine.lnx_vm
  name                       = "NetworkWatcher"
  virtual_machine_id         = each.value.id
  publisher                  = "Microsoft.Azure.NetworkWatcher"
  type                       = "NetworkWatcherAgentLinux"
  type_handler_version       = "1.4"
  auto_upgrade_minor_version = true
  depends_on                 = [azurerm_virtual_machine_data_disk_attachment.lnx_vm]
  tags                       = module.data.tags
}
```

### Expected Behaviour

VM and extensions should deploy with no issues.

### Actual Behaviour
Intermittently we receive this error

```
Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
        	            	
        	            	  on ../../main.tf line 137, in resource "azurerm_virtual_machine_extension" "NetworkWatcher-lnx_vm":
        	            	 137: resource "azurerm_virtual_machine_extension" "NetworkWatcher-lnx_vm" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

* This is an intermittent issue, affecting approximately 1 in 5 vm deployments.  If the extension deployment is successful it completes in 3-5 minutes.  If it is going to fail it will eventually time out and the VM will need to be manually removed before attempting to deploy again.
* This issue appears to only affect linux VMs deployed with `azurerm_linux_virtual_machine` and `azurerm_linux_virtual_machine_scale_set`  Windows VM's deploy consistently with no issues with the equivalent extensions.
* We are also experiencing the issues described in #9342 and suspect there may be a related underlying cause.

### References

* #9342

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. The error message from this scenario should be better with the new base layer. If you are still struggling with this output, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34), to get help for questions.
