### ISSUE TITLE
Error importing azurerm_virtual_machine_data_disk_attachment

### ISSUE THREAD

**Issue by colutti** [hashicorp/terraform-provider-azurerm#11966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.50.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* `azurerm_virtual_machine_data_disk_attachment `

### Panic Output

https://gist.github.com/colutti/78a34281bc49324ebc1f0c36267baddb

### Steps to Reproduce

This error occurs when importing the resource using the command bellow:

terraform import azurerm_virtual_machine_data_disk_attachment.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/microsoft.compute/virtualMachines/machine1/dataDisks/disk1

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
