### ISSUE TITLE
Update for virtual_machine_extension documentation

### ISSUE THREAD

**Issue by Jvekka** [hashicorp/terraform-provider-azurerm#11962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.60.0

### Affected Resource(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

Current examples are not working with Windows devices and it would be good to add also Windows example to [azurerm_virtual_machine_extension](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension)

Working example for Windows devices

```hcl
resource "azurerm_virtual_machine_extension" "hello_world" {
  name                 = "ansible_windows_winrm"
  virtual_machine_id   = azurerm_windows_virtual_machine.example.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.9"
  tags = {
    environment = "Production"
  }

  settings = <<SETTINGS
    {
        "fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],
        "commandToExecute": "powershell -ExecutionPolicy Unrestricted -file ConfigureRemotingForAnsible.ps1 -EnableCredSSP -DisableBasicAuth"
    }
SETTINGS
}
```

* #0000

**Comment by Sheetalsingh23** [comment]
@Jvekka, I want to work on this issue. Can I pick it up?

**Comment by Jvekka** [comment]
Yeah, of course :)
