### ISSUE TITLE
Support for dotnet_framework_version in azurerm_function_app

### ISSUE THREAD

**Issue by brettsam** [hashicorp/terraform-provider-azurerm#11988]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Function apps need the ability to specify the version of .NET they are using. For example, the new [dotnet-isolated worker](https://docs.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide) requires the aps's config value `netFrameworkVersion` to be set to `v5.0` (and `v6.0` in the near future). This functionality exists in app service already by setting the `dotnet_framework_version` in `site_config`, but currently throws an error when doing so for a Function app.

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "test" {
  name                = var.scenarioName
  resource_group_name = azurerm_resource_group.test.name
  location            = var.locationName
  app_service_plan_id       = azurerm_app_service_plan.test.id
  storage_connection_string = azurerm_storage_account.test.primary_connection_string
  version                   = "~3"
  enable_builtin_logging    = false

  site_config {
    always_on = "true"
    dotnet_framework_version = "v5.0"
  }

  app_settings = {
    APPINSIGHTS_INSTRUMENTATIONKEY = azurerm_application_insights.test.instrumentation_key
    FUNCTIONS_WORKER_RUNTIME = "dotnet"
    WEBSITE_RUN_FROM_PACKAGE = "1"
  }
  
  lifecycle {
    ignore_changes = [
      app_settings
    ]
  }
}
```

### References

* #10229 (similar functionality added for `java_version`)

**Comment by Elip-tdlr** [comment]
We need this ASAP. [This ](https://github.com/Azure/azure-functions-core-tools/issues/2304) issue with Function Apps makes it even more important as we are required to transition to .Net 5 due to a bug in the framework. 

This needs a priority boost!
