### ISSUE TITLE
Support for Azure Front Door Standard/Premium

### ISSUE THREAD

**Issue by AONunan** [hashicorp/terraform-provider-azurerm#11983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to add support for [Azure Front Door Standard/Premium](https://docs.microsoft.com/en-us/azure/frontdoor/standard-premium/)?

I manually deployed this resource in the Azure Portal to see what the underlying components are. Unlike the original Front Door resource which is deployed as type "Microsoft.Network/frontdoors", the following resource types are deployed for Front Door Premium:

- Microsoft.Cdn/Profiles
- Microsoft.Cdn/Profiles/AfdEndpoints
- Microsoft.Cdn/Profiles/AfdEndpoints/Routes
- Microsoft.Cdn/Profiles/OriginGroups
- Microsoft.Cdn/Profiles/OriginGroups/Origins

Terraform already supports [azurerm_cdn_profile](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_profile). However, this Front Door Premium resource is deployed with a SKU of `Premium_AzureFrontDoor`, which is not allowed currently in the "azurerm_cdn_profile" resource:

`Error: expected sku to be one of [Standard_Akamai Standard_ChinaCdn Standard_Verizon Standard_Microsoft Premium_Verizon], got Premium_AzureFrontDoor`

### New or Affected Resource(s)

* azurerm_cdn_profile

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_profile" "example" {
  name                = "exampleFrontDoorPremium"
  location            = "West US"
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium_AzureFrontDoor"

  origin_group {
    # Origin group config here
  }

  afd_endpoint {
    # Azure Front Door Endpoint config here
  }
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/cdn/cdn/profiles/create

**Comment by WodansSon** [comment]
@AONunan, thank you for opening this issue. This resource has not yet been implemented for Terraform as of yet and is not backward compatible with the existing front door resource. Frontdoor X will be implemented in the near future. 🚀

**Comment by nboaldin** [comment]
A microsoft rep said frontdoor premium should be generally available beginning of july and the terraform provider should follow shortly after. Does anyone here have a pulse on when the tf provider for the premium sku could possibly be available?

**Comment by dschniepp** [comment]
@WodansSon are there any plans around the structure? I would like to see that the sub resources are not nested inside the root resource or at least to have two options like we have for ‘azurerm_virtual_network‘. This would enable us to create more advanced setups where we are able to split the definition across modules so multiple teams can utilize the same frontdoor so they can add the routing as they need. Thanks

**Comment by BenWaller** [comment]
Are there any plans to continue with this now that the new Front Door is GA? https://azure.microsoft.com/en-us/blog/introducing-the-new-azure-front-door-reimagined-for-modern-apps-and-content/

**Comment by sebader** [comment]
@BenWaller the PR that's linked above is still in active WIP

**Comment by kaganmersin** [comment]
Hello @BenWaller. Is there any expected/planned go-live date for this feature?

**Comment by sebader** [comment]
well, to be honest, with only the profile and endpoint resources, you don't really get anywhere in deploying an AFD Standard/Premium. So hopefully the remaining resources will follow soon :)

**Comment by tombuildsstuff** [comment]
@sebader indeed, although this issue is _technically_ tracking support for the new SKU's, there's another issue tracking Firewall Policies etc - so I've left that one open as that's still pending. The other resources are being split out/refactored as we speak :)
