### ISSUE TITLE
Initialization of azurerm for Management Groups

### ISSUE THREAD

**Issue by schwarzzz** [hashicorp/terraform-provider-azurerm#11989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azurerm` provider requires a `subscription_id` argument (or a respective environment variable). However, not all resources provided by `azurerm` are actually scoped within a subscription (e.g. `azurerm_management_group`).

I have a Terraform configuration that is bootstrapping the initial management group structure of an organization. This configuration creates Management Group structure's only. However, I cannot initialize the `azurerm` provider without providing a subscription Id - which I don't have (, yet).

### New or Affected Resource(s)

* azurerm

### Potential Terraform Configuration

Add a new argument `management_group_name` and make either `management_group_name` or `subscription_id` mandatory.
If `subscription_id` is not set, the creation of resources scoped within a subscription should fail.

```
provider "azurerm" {
  tenant_id = "..."
  management_group_name = "..."
  ...
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I'll share my view on the topic here and let people with more clue on this either confirm or deny, but this is a bit of a chicken and egg thing. Unfortunately subscription ID is a config parameter provider can not work without. It's being used all over the place to construct resource IDs for virtually everything.

My best bet here - you'll have to create your first sub by hand and import it into the state.

I don't think we'll be able to initialize provider without subscription ID.

// cc @jackofallops

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions and discussions like this are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
