### ISSUE TITLE
Data source azurerm_storage_account returns URL value for ID attribute

### ISSUE THREAD

**Issue by carct** [hashicorp/terraform-provider-azurerm#11982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version: 
* **TF: 0.12.31**
* **AzureRM Provider: 2.59.0**

### Affected Resource(s)

* `azurerm_storage_account` -> encountered this for the data-source

### Terraform Configuration Files

```hcl
data "azurerm_storage_blob" "my_blob" {
  name                   = local.full_vhd_blob_name
  storage_account_name   = var.storage_account_name
  storage_container_name = "system"
}

locals {
  full_blob_id = "${data.azurerm_storage_blob.my_blob.id}"
}

output "blob_id" {
    value = local.full_blob_id 
}
```

### Debug Output

```
Outputs:
blob_id = https://YYYY.blob.core.windows.net/TTT/path/to/blob
```

### Expected Behaviour

* would expect that ${data.azurerm_storage_blob.my_blob.id} returns an Azure resource ID
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/storage_blob

### Actual Behaviour

* ID attribute of data-source azurerm_storage_blob returns an URL
* there is a separate "URL" attribute for the URL

### Steps to Reproduce

* output the ID of a blob data-source, as in the code sample 
* ${data.azurerm_storage_blob.my_blob.id}

1. `terraform apply`

### Important Factoids

* **Azure Public Cloud**

### References

* #0000

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I just looked into a state file of an infra that has blobs - ID that's returned by blobsclient is identical to the URI.

```
        {
          "index_key": "xxxxx",
          "schema_version": 1,
          "attributes": {
            "access_tier": "Hot",
            "content_md5": "",
            "content_type": "application/octet-stream",
            "id": "https://xxxxx.blob.core.windows.net/metadata/xxxx",
            "metadata": {},
            "name": "FDXREV.ImplementPricingEvent.xsd",
            "parallelism": 8,
            "size": 0,
            "source": "../metadata/xxxx",
            "source_content": null,
            "source_uri": null,
            "storage_account_name": "xxxx",
            "storage_container_name": "metadata",
            "timeouts": null,
            "type": "Block",
            "url": "https://xxxx.blob.core.windows.net/metadata/xxxxx"
          },
```

I'm also not aware of the fact that blobs are a RM-level resource, so the fact that they do not have an ARM-like (/subscriptions/....) ID does seem logical.

**Comment by tombuildsstuff** [comment]
hi @carct 

As @favoretti has mentioned, there both isn't a Resource Manager API to manage blobs (and likely won't given the max payload size to the ARM API) or a Resource Manager specific ID for a Blob - and as such the Data Plane ID that's being used is correct here.

As such, whilst I'd like to thank you for opening this issue, since this isn't something we can action (and isn't likely to be, given the payload/size constraints on the ARM API) - I'm going to go ahead and close this issue for the moment.

Thanks!
