### ISSUE TITLE
Autoscaling setting for vmss is throwing conflict error

### ISSUE THREAD

**Issue by sschoebinger** [hashicorp/terraform-provider-azurerm#12035]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- terraform v0.14.8
- azurerm v2.61.0

### Affected Resource(s)

* `azurerm_monitor_autoscale_setting`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_autoscale_setting" "autoscale_default" {
  name                = "<thename>"
  resource_group_name = "<rgname>"
  location            = "<location>"
  target_resource_id  = azurerm_linux_virtual_machine_scale_set.<thevmss>.id

  profile {
    name = "<profilename>"

    capacity {
      default = 2
      minimum = 2
      maximum = 2
    }

    recurrence {
      timezone = "UTC"
      days     = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
      hours    = [3]
      minutes  = [0]
    }
  }

  profile {
    name = "<profilename2>"

    capacity {
      default = 4
      minimum = 4
      maximum = 4
    }

    recurrence {
      timezone = "UTC"
      days     = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
      hours    = [2]
      minutes  = [0]
    }
  }

  notification {
    email {
      send_to_subscription_administrator    = false
      send_to_subscription_co_administrator = false
      custom_emails                         = ["the@email"]
    }
  }
}
```

### Debug Output

```
Error: Error creating AutoScale Setting "rulename" (Resource Group "rg-name"): insights.AutoscaleSettingsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
```

### Expected Behaviour

Create or update/modify the autoscale setting for the vmss

### Actual Behaviour

The autoscale setting which I want to create via terraform conflicts with the automatically created autoscale setting from vmss. I have to manually delete the already existing autoscale setting like described [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2929#issuecomment-508161687) and afterwards I can create the autoscale setting via terraform.

### Steps to Reproduce

1. create vmss
1. create autoscale setting for that vmss

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/2929#issuecomment-508161687

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
