### ISSUE TITLE
azurerm_automation_module import fails because it does not wait for previous import to complete

### ISSUE THREAD

**Issue by SylvainMartel** [hashicorp/terraform-provider-azurerm#12045]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform = 0.15.4
azurerm = 2.61
```

### Affected Resource(s)

* `azurerm_automation_module`

### Terraform Configuration Files

```hcl

resource "azurerm_automation_module" "azAccounts" {
  name                    = "Az.Accounts"
  resource_group_name     = azurerm_resource_group.main.name
  automation_account_name = azurerm_automation_account.main.name

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/az.accounts/2.3.0"
  }
}
resource "azurerm_automation_module" "AzContainerInstance" {
  name                    = "Az.ContainerInstance"
  resource_group_name     = azurerm_resource_group.main.name
  automation_account_name = azurerm_automation_account.main.name

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/Az.ContainerInstance/2.0.0"
  }
  depends_on = [azurerm_automation_module.azAccounts]
}

```

### Debug Output

https://gist.github.com/kinwolfqc/04726d53dab3006403b4b637a6675d7c

### Expected Behaviour

The 2 modules are installed properly, in sequence since Az.ContainerInstance  requires Az.Accounts

### Actual Behaviour

The installation of Az.ContainerInstance fails since Az.Accounts hasn't completed it's import yet.  Adding a 120 secs delay, to allow the installation of Az.Accounts to finish properly, solve the problem, so the problem is really one of dependencies.

### Steps to Reproduce

1. `terraform apply`

### References
#3109 and #2600 describe this problem, and it was supposedly solved in 1.39, but the problem seems to still exist in 2.xx ?

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
