### ISSUE TITLE
Reference azurerm_ssh_public_key in azurerm_linux_virtual_machine

### ISSUE THREAD

**Issue by patuzov** [hashicorp/terraform-provider-azurerm#12054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform: 0.14.0
azurerm: 2.61.0

### Affected Resource(s)
* `azurerm_linux_virtual_machine`
* `azurerm_ssh_public_key `

### Terraform Configuration Files

```hcl
data "azurerm_ssh_public_key" "example" {
  name                = "xxx"
  resource_group_name = "xxx"
}

resource "azurerm_linux_virtual_machine" "example" {
  ...

  admin_ssh_key {
    username   = "xxx"
    public_key = data.azurerm_ssh_public_key.example.public_key
  }
}

```

### Debug Output

2021/06/03 22:35:33 [WARN] Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for azurerm_linux_virtual_machine.example during refresh.
      - .tags: was null, but now cty.MapValEmpty(cty.String)

Error: Error parsing "admin_ssh_key.0.public_key" as a public key object

  on main.tf line 42, in resource "azurerm_linux_virtual_machine" "example":
  42: resource "azurerm_linux_virtual_machine" "example" {

### Expected Behaviour

azurerm_linux_virtual_machine should accept public key in heredoc format

### Actual Behaviour

azurerm_linux_virtual_machine doesn't accept the public key format returned by azurerm_ssh_public_key data source, with the error: _Error parsing "admin_ssh_key.0.public_key" as a public key object_

### Steps to Reproduce

* create ssh key in Azure Portal
* create terraform script with [azurerm_ssh_public_key data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/ssh_public_key) referencing the create ssh key
* add azurerm_linux_virtual_machine example from [terraform doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine)
* reference the public key in admin_ssh_key: `public_key = data.azurerm_ssh_public_key.example.public_key`
* `terraform apply`

### Important Factoids
Value returned by azurerm_ssh_public_key data source:
```
public_key = <<-EOT
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHJ/ykSPnuOUiPZYeF9Y/7tufp
        q8D0krNCyNzrn7aj0adRKjYXXJdLRkcupKVOaM/44IRX5Yv7IEzb9LK5VK3A62K9
        aXf3GxSZW7gGRYKTbymuj72//Gjb0iZue/wJK3W+cy7rIrr6dRs8pUsUJJ0uEpIS
        ZCmGO80TzbL6jK7AorkkCBw7jF3VwrSeNBjWxyVMMsfo57Vqg83fjFSHQgE5jdVJ
        TkqQ0/OeiRMid+4iW5+3ZYwMYk1VHgx8Hh3kj/Vs2ehQTJVeqwa6GCWem3heEzoY
        P6Uyw/5ltxZysVQU1z9uNJYiXjpHfVR9IBqh5ZMAggx1YyRjl/D01zJxGhuKNMwl
        rHqfQeFEPFzeOQu4CRAmoffUzNqO4++gtKXxucL9P/UnnQWu9inqwZrnYBpgvm40
        9iPn1L+UIQICPn3y8pJ3WWstN7MPcW+TUc9r+ADXeVIp4gETzdQbVWHgPCroeiix
        AdisVhi6i1ZbZZQtkiTz2HqMN4SDC3+pXw+d6zE= generated-by-azure
    EOT
```

### References

* #9238

**Comment by LaurentLesle** [comment]
try that

```
  admin_ssh_key {
    username   = "xxx"
    public_key = replace(data.azurerm_ssh_public_key.example.public_key, "\r\n", "")
  }
```

**Comment by henworth** [comment]
I recently ran into a similar issue. However, in my case I was using an uploaded key that had the SSH2 format, not the OpenSSH format that the provider expects on the `azurerm_linux_virtual_machine` resource. The portal will not accept an OpenSSH formatted key, only SSH2.

My solution was to do some string manipulation to roughly translate from one format to the other: 
```hcl
locals {
  ssh_key_hash = regex("^-{4}[A-Z0-9 ]*-{4}(.*)-{4}[A-Z0-9 ]*-{4}$", data.azurerm_ssh_public_key.this.public_key)
  ssh_key_rsa  = "ssh-rsa ${local.ssh_key_hash[0]} ${data.azurerm_ssh_public_key.this.name}"
}

data "azurerm_ssh_public_key" "this" {
  name                = "this_rsa_key"
  resource_group_name = "this_resource_group"
}
```

I know this is different from the original issue, but this might be useful for anyone who finds this issue while troubleshooting like I did.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
