### ISSUE TITLE
Trying to create resources in Azure with service principal and pulling that SPs key from keyvault

### ISSUE THREAD

**Issue by rb-cloud-guru** [hashicorp/terraform-provider-azurerm#12059]
Hi,
I am trying to pull SPN i am using for TFE auth from Azure Key Vault and i am getting a cycle dependency error:
Error: Cycle: data.azurerm_key_vault_secret.sub-id, data.azurerm_key_vault_secret.tenant-id, data.azurerm_key_vault_secret.cl-sec, data.azurerm_key_vault.kv, data.azurerm_key_vault_secret.cl-id, provider["registry.terraform.io/hashicorp/azurerm"]
This is an expected behavior\bug?
Here is my code: pull SPN secrets and use them to provision resources 
# Azure Vault Data 
data "azurerm_key_vault" "kv" {
  name                = "akv-terraform"
  resource_group_name = "terraform"
}

#from azure vault
data "azurerm_key_vault_secret" "cl-id" {
  name      = "CLIENT-ID"
  key_vault_id = "${data.azurerm_key_vault.kv.id}"

}

# from azure vault
data "azurerm_key_vault_secret" "cl-sec" {
  name      = "CLIENT-SECRET"
  key_vault_id = "${data.azurerm_key_vault.kv.id}"
  
}
# from azure vault
data "azurerm_key_vault_secret" "sub-id" {
  name      = "SUBSCRIPTION-ID"
  key_vault_id = "${data.azurerm_key_vault.kv.id}"
 
}
# Fetch secret  from azure vault
data "azurerm_key_vault_secret" "tenant-id" {
  name      = "TENANT-ID"
  key_vault_id = "${data.azurerm_key_vault.kv.id}"
  
}

# Azure Provider new creds used
provider "azurerm" {
  features {}
  subscription_id = "${data.azurerm_key_vault_secret.sub-id.value}"
  client_id       = "${data.azurerm_key_vault_secret.cl-id.value}"
  client_secret   = "${data.azurerm_key_vault_secret.cl-sec.value}"
  tenant_id       = "${data.azurerm_key_vault_secret.tenant-id.value}"
}

**Comment by nnellans-acts** [comment]
https://www.terraform.io/docs/language/providers/configuration.html

"You can use expressions in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources (with an exception for resource arguments that are specified directly in the configuration)."

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @nnellans-acts's response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
