### ISSUE TITLE
"StorageAccountNotFound" while creating Storage Account

### ISSUE THREAD

**Issue by roy-work** [hashicorp/terraform-provider-azurerm#12052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
» terraform -v
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0

Your version of Terraform is out of date! The latest version
is 0.15.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

We're trying to instantiate a module that contains this,

```hcl
resource "azurerm_storage_account" "storage_account" {
  account_replication_type = "RAGRS"
  account_tier = "Standard"
  location = var.location
  name = var.storage_account
  resource_group_name = var.group

  access_tier = "Cool"
  account_kind = "BlobStorage"
  allow_blob_public_access = false
  enable_https_traffic_only = true
  is_hns_enabled = false
  large_file_share_enabled = false
  min_tls_version = "TLS1_2"

  network_rules {
    bypass = ["None"]
    default_action = "Deny"
    ip_rules = [for ip in var.ip_addresses : ip.ip]
    virtual_network_subnet_ids = [for sn in data.azurerm_subnet.subnets : sn.id]
  }
}
```
The key part, for the purposes of this bug report, is that we set the `virtual_network_subnet_ids` attribute.

Additionally, the subnet ID that gets used for that `virtual_network_subnet_ids` *must* be a subnet that does *not* have the Storage Account Endpoint configured on it. (And this *is* an error, one that I naïvely made while running into this.)

### Debug Output

First, see the "Actual Behavior". Without debug logs on, the diagnostic that gets emitted by `terraform apply` makes no sense at all. (It complains that we cannot create the Storage Account because the Storage Account doesn't exist.)

With debug logs *on*, it makes more "sense". We see TF check the status of the creation of the SA:

```
module.example.azurerm_storage_account.storage_account: Still creating... [10s elapsed]
2021-06-03T12:38:37.089-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: [DEBUG] AzureRM Request:
2021-06-03T12:38:37.089-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: GET /subscriptions/[snip]/providers/Microsoft.Storage/locations/eastus/asyncoperations/[snip]?monitor=true&api-version=2021-01-01 HTTP/1.1
[snip]

2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/[snip]/providers/Microsoft.Storage/locations/eastus/asyncoperations/[snip]?monitor=true&api-version=2021-01-01:
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: HTTP/2.0 200 OK
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: Cache-Control: no-cache
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: Content-Type: application/json
[snip]
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: {"error":{"code":"NetworkAclsValidationFailure","message":"Validation of network acls failure: SubnetsHaveNoServiceEndpointsConfigured:Subnets cluster of virtual network /subscriptions/[snip]/resourceGroups/[snip]/providers/Microsoft.Network/virtualNetworks/[snip]-vnet do not have ServiceEndpoints for Microsoft.Storage resources configured. Add Microsoft.Storage to subnet's ServiceEndpoints collection before trying to ACL Microsoft.Storage resources to these subnets.."}}
```

And here is where I think the `azurerm` provider very rightly gets confused. It's been given a `200 OK` — success! — … but which of course contains an error.

I believe it interprets this `200 OK` (again, reasonably) as success, and then it goes on to `GET` the storage account, presumably to fill in the state file entry for it:

```
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: [DEBUG] AzureRM Request:
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: GET /subscriptions/[snip]/resourceGroups/[snip]/providers/Microsoft.Storage/storageAccounts/[snip]?api-version=2021-01-01 HTTP/1.1
2021-06-03T12:38:37.263-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: Host: management.azure.com
[snip]
2021-06-03T12:38:37.460-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: [DEBUG] AzureRM Response for https://management.azure.com/subscriptions/[snip]/resourceGroups/[snip]/providers/Microsoft.Storage/storageAccounts/[snip]?api-version=2021-01-01:
2021-06-03T12:38:37.460-0400 [DEBUG] plugin.terraform-provider-azurerm_v2.59.0_x5: HTTP/2.0 404 Not Found
```
But that, of course, fails with `404 Not Found`, which makes sense, because the storage account creation actually failed. But that error, then, becomes our diagnostic, which leaves the user really, really confused.

I guess some sniffing of the JSON on the `asyncoperations` call, to see if it looks like an error, and then, if it does, consider the request failed? (And promote the error from that call as the diagnostic that the user would see.)

### Expected Behaviour

A usable diagnostic gets emitted.

### Actual Behaviour

```
module.example.azurerm_storage_account.storage_account: Creating...
module.example.azurerm_storage_account.storage_account: Still creating... [10s elapsed]

Error: Error retrieving Azure Storage Account "examplestorageaccount": storage.AccountsClient#GetProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account examplestorageaccount was not found."

  on ../modules/foo-storage/main.tf line 9, in resource "azurerm_storage_account" "storage_account":
   9: resource "azurerm_storage_account" "storage_account" {
```

### Steps to Reproduce

1. Have a vnet with some subnet in it, but forget to set any endpoints on the subnet. (Crucially, forget to set the Storage Account endpoint on the subnet, which is what matters here.)
1. `terraform apply` something like the above that creates a Storage Account with subnets permitted to access it.

### References

See #10872. I **don't** think #10872 is a duplicate — it involves static websites, and does not involve vnet subnets & endpoints — however, I think some of the comments on that bug are by people who *are* affected by *this* bug.

**Comment by fcatacut** [comment]
I ran into this issue when I specified multiple subnets as well. However, when I only specified just one subnet, `terraform apply` successfully completed. _After the Storage Account was created_, I was able to add the remaining subnets with a subsequent ` terraform apply`. Not a great workaround but might shed additional insight to assist with troubleshooting this issue.

```hcl
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1
```

**Comment by slyons** [comment]
This problem is still occurring as of 2.71.0 with terraform 0.15.4

**Comment by graudeejs** [comment]
With azurerm `2.73.0` and terraform `0.15.4` and `1.0.5`
I have only one subnet, so @fcatacut workaround doesn't work for me.

**Comment by Divyabd** [comment]
I also had same issue before in my case it got resolved by choosing the same location of vnet where storage account creating 
and I am using  azurerm version     = "2.99.0"  and terraform version ="Terraform v1.0.7"

after plan its look like this ,I am attaching 2 subnets you can see 


  # module.storage_account.azurerm_storage_account.BootDiagonastics will be created
  + resource "azurerm_storage_account" "BootDiagonastics" {
      + access_tier                       = "Hot"
      + account_kind                      = "StorageV2"
      + account_replication_type          = "LRS"
      + account_tier                      = "Standard"
      + allow_blob_public_access          = false
      + enable_https_traffic_only         = true
      + id                                = (known after apply)
      + infrastructure_encryption_enabled = false
      + is_hns_enabled                    = true
      + large_file_share_enabled          = (known after apply)
      + location                          = "centralus"
      + min_tls_version                   = "TLS1_2"
      + name                              = "nameofthestorage123"
      + nfsv3_enabled                     = false
      + primary_access_key                = (sensitive value)
      + primary_blob_connection_string    = (sensitive value)
      + primary_blob_endpoint             = (known after apply)
      + primary_blob_host                 = (known after apply)
      + primary_connection_string         = (sensitive value)
      + primary_dfs_endpoint              = (known after apply)
      + primary_dfs_host                  = (known after apply)
      + primary_file_endpoint             = (known after apply)
      + primary_file_host                 = (known after apply)
      + primary_location                  = (known after apply)
      + primary_queue_endpoint            = (known after apply)
      + primary_queue_host                = (known after apply)
      + primary_table_endpoint            = (known after apply)
      + primary_table_host                = (known after apply)
      + primary_web_endpoint              = (known after apply)
      + primary_web_host                  = (known after apply)
      + queue_encryption_key_type         = "Service"
      + resource_group_name               = "RG-BTS-ENC-eastus2"
      + secondary_access_key              = (sensitive value)
      + secondary_blob_connection_string  = (sensitive value)
      + secondary_blob_endpoint           = (known after apply)
      + secondary_blob_host               = (known after apply)
      + secondary_connection_string       = (sensitive value)
      + secondary_dfs_endpoint            = (known after apply)
      + secondary_dfs_host                = (known after apply)
      + secondary_file_endpoint           = (known after apply)
      + secondary_file_host               = (known after apply)
      + secondary_location                = (known after apply)
      + secondary_queue_endpoint          = (known after apply)
      + secondary_queue_host              = (known after apply)
      + secondary_table_endpoint          = (known after apply)
      + secondary_table_host              = (known after apply)
      + secondary_web_endpoint            = (known after apply)
      + secondary_web_host                = (known after apply)
      + shared_access_key_enabled         = true
      + table_encryption_key_type         = "Service"
      + tags                              = {
          
        }

      + blob_properties {
          + change_feed_enabled      = (known after apply)
          + default_service_version  = (known after apply)
          + last_access_time_enabled = (known after apply)
          + versioning_enabled       = (known after apply)

          + container_delete_retention_policy {
              + days = (known after apply)
            }

          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known after apply)
              + max_age_in_seconds = (known after apply)
            }

          + delete_retention_policy {
              + days = (known after apply)
            }
        }

      + customer_managed_key {
          + key_vault_key_id          = (known after apply)
          + user_assigned_identity_id = (known after apply)
        }

      + network_rules {
          + bypass                     = (known after apply)
          + default_action             = "Deny"
          + ip_rules                   = [
              + "10.0.0.0/20",
              + "10.1.1.1/16",

            ]
          + virtual_network_subnet_ids = [
              + "/subscriptions/subscriptionid/resourceGroups/RG-D-EC-AR/providers/Microsoft.Network/virtualNetworks/dns_centralus_vnet/subnets/dns_centralus_subnet",
              + "/subscriptions/subscriptionid/resourceGroups/RG-DC-AWAMER/providers/Microsoft.Network/virtualNetworks/dns_centralus_vnet/subnets/dns_centralus_subnet1",
            ]
        }

      + queue_properties {
          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known after apply)
              + max_age_in_seconds = (known after apply)
            }

          + hour_metrics {
              + enabled               = (known after apply)
              + include_apis          = (known after apply)
              + retention_policy_days = (known after apply)
              + version               = (known after apply)
            }

          + logging {
              + delete                = (known after apply)
              + read                  = (known after apply)
              + retention_policy_days = (known after apply)
              + version               = (known after apply)
              + write                 = (known after apply)
            }

          + minute_metrics {
              + enabled               = (known after apply)
              + include_apis          = (known after apply)
              + retention_policy_days = (known after apply)
              + version               = (known after apply)
            }
        }

      + routing {
          + choice                      = (known after apply)
          + publish_internet_endpoints  = (known after apply)
          + publish_microsoft_endpoints = (known after apply)
        }

      + share_properties {
          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known after apply)
              + max_age_in_seconds = (known after apply)
            }

          + retention_policy {
              + days = (known after apply)
            }

          + smb {
              + authentication_types            = (known after apply)
              + channel_encryption_type         = (known after apply)
              + kerberos_ticket_encryption_type = (known after apply)
              + versions                        = (known after apply)
            }
        }
    }

**Comment by magodo** [comment]
Duplicates to #16547
