### ISSUE TITLE
Support for setting a azurerm_storage_encryption_scope when creating a azurerm_storage_container resource

### ISSUE THREAD

**Issue by duckfez** [hashicorp/terraform-provider-azurerm#12055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for specifying a `azurerm_storage_encryption_scope` when creating a `azurerm_storage_container`.  It looks like the base resources for defining an encryption scope were added in #8893.  One mode of using an encryption scope is to choose a scope when [defining a blob storage container](https://docs.microsoft.com/en-us/azure/storage/blobs/encryption-scope-manage?tabs=portal).  To do this, the `azurerm_storage_container` resource needs to support adding an encryption scope.  

It appears (from my cursory reading of code) that there's already support for this in the underlying Azure Go SDK in the [ContainerProperties](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v55.0.0+incompatible/services/storage/mgmt/2021-02-01/storage#ContainerProperties) object.

### New or Affected Resource(s)

* azurerm_storage_container

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_encryption_scope" "scope" {
  name                               = myscope
  storage_account_id                 = azurerm_storage_account.my_account.id
  source                             = "Microsoft.KeyVault"
  infrastructure_encryption_required = true
  key_vault_key_id                   = azurerm_key_vault_key.my_vault.id
}

resource "azurerm_storage_container" "container" {
  name                     = "blobs"
  storage_account_name     = azurerm_storage_account.my_account.name
  container_access_type    = "private"
  default_encryption_scope = azurerm_storage_encryption_scope.scope.name
}


```

### References

* #8893

**Comment by LaurentLesle** [comment]
@katbyte do you think this feature can be prioritised? There is support on encryption scopes on the storage account but we cannot attach the default encryption scope to the container.

Also I would propose a variation:

```
resource "azurerm_storage_container" "container" {
  name                     = "blobs"
  storage_account_name     = azurerm_storage_account.my_account.name
  container_access_type    = "private"
  default_encryption_scope_id = azurerm_storage_encryption_scope.scope.id
  deny_encryption_scope_override = true
}
```

some ref - https://docs.microsoft.com/en-us/rest/api/storagerp/blob-containers/create

**Comment by LaurentLesle** [comment]
Added also https://github.com/hashicorp/terraform-provider-azurerm/issues/17272

**Comment by jbasement** [comment]
@katbyte Can we have an update on this issue? The official Go Azure SDK is supporting this feature already. Also @magodo opened a [PR](https://github.com/tombuildsstuff/giovanni/pull/61) at the unofficial repo to add encryption scope support as well.
Could we go forward with either implementing the official go SDK for the container resource in the terraform provider or going forward with the existing PR on the giovanni Azure SDK repo?
