### ISSUE TITLE
Support of parquet data format for azurerm_kusto_eventgrid_data_connection

### ISSUE THREAD

**Issue by DaSenf** [hashicorp/terraform-provider-azurerm#12064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, i´m working on ingesting data to Azure Data Explorer (formerly Kusto) and i use the eventgrid data connection to ingest the data. 
The imported data comes in **parquet** format. This works fine when i set up the data connection via the portal.
However the parquet data format is not supported in the terraform module.
![image](https://user-images.githubusercontent.com/15066410/120798147-394da980-c53d-11eb-97a0-2ac5591f5e0a.png)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_eventgrid_data_connection

As parquet is the most or at leaste one of the most common data formats it would be great if it can be used as an option also in the terraform module

### New or Affected Resource(s)

Resource:
azurerm_kusto_eventgrid_data_connection

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-event-grid
![image](https://user-images.githubusercontent.com/15066410/120797763-bfb5bb80-c53c-11eb-98c4-dc65a16a8812.png)

**Comment by xiaxyi** [comment]
Hi @DaSenf, I tested the event grid connection using the HCL but seems the PARQUET data format is supported and below is my test result:
HCL:
```
resource "azurerm_kusto_eventgrid_data_connection" "example" {
  name                         = "test-kusto-eventgrid-data-connection"
  resource_group_name          = data.azurerm_resource_group.example.name
  location                     = data.azurerm_resource_group.example.location
  cluster_name                 = "testkustocluster"
  database_name                = "test-kusto-database"
  storage_account_id           = data.azurerm_storage_account.example.id
  eventhub_id                  = data.azurerm_eventhub.test.id
  eventhub_consumer_group_name = data.azurerm_eventhub_consumer_group.example.name

  table_name        = "testTable"         #(Optional)
  mapping_rule_name = "testMapping" #(Optional)
  data_format       = "PARQUET"             #(Optional)

  depends_on = [azurerm_eventgrid_event_subscription.example]
} 
```
results:
```
azurerm_kusto_eventgrid_data_connection.example will be created
  + resource "azurerm_kusto_eventgrid_data_connection" "example" {
      + blob_storage_event_type      = "Microsoft.Storage.BlobCreated"
      + cluster_name                 = "testkustocluster"
      **+ data_format                  = "PARQUET"**
      + database_name                = "test-kusto-database"
      + eventhub_consumer_group_name = "test-consumergroup"
      + eventhub_id                  = "/subscriptions/<subs>/resourceGroups/testrg-kusto/providers/Microsoft.EventHub/namespaces/test-eventhubnamespace/eventhubs/test-eventhub"
      + id                           = (known after apply)
      + location                     = "westeurope"
      + mapping_rule_name            = "testMapping"
      + name                         = "test-kusto-eventgrid-data-connection"
      + resource_group_name          = "testrg-kusto"
      + skip_first_record            = false
      + storage_account_id           = "/subscriptions/<subs>/resourceGroups/testrg-kusto/providers/Microsoft.Storage/storageAccounts/teststorageaccount"
      + table_name                   = "testTable"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_kusto_eventgrid_data_connection.example: Creation complete after 1m39s [id=/subscriptions/<subs>/resourceGroups/testrg-kusto/providers/Microsoft.Kusto/Clusters/kustocluster/Databases/test-kusto-database/DataConnections/test-kusto-eventgrid-data-connection]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
```
can you share more details about your usage?

**Comment by mybayern1974** [comment]
@DaSenf  I'm closing this issue since per comment above this feature should have already been supported in latest AzureRM provider versions. While fee free to suggest to reopen this issue if you believe your question has not been resolved.
