### ISSUE TITLE
azurerm_virtual_network_gateway : policybased vpn type fails

### ISSUE THREAD

**Issue by iamsoorya** [hashicorp/terraform-provider-azurerm#12065]
I have the following code and when I pass PolicyBased vpn type parameter, the code fails. FOr the amy given sku it fails. Tried with Basic, VpnGw1, HighPerformance etc..  Can you spot the error?

resource "azurerm_virtual_network_gateway" "lgra_vng_vpn" {
  name                = var.vng_vpn_lgra_name 
  location            = var.location
  resource_group_name = var.rg_name

  type                = "Vpn"
  vpn_type            = "PolicyBased"
  active_active       = false
  enable_bgp          = false
  sku                 = var.vpn_sku 

  #generation          = "None" #"Generation1"

  private_ip_address_enabled = false  

  dynamic "ip_configuration" {
    for_each = local.ip_config_1
      content {        
        name                 = ip_configuration.value["name"]
        public_ip_address_id = ip_configuration.value["public_ip_address_id"]
        subnet_id            = var.gateway_subnet_id          
    }
  }

  tags                = local.tags_vpn
}

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
