### ISSUE TITLE
`georeplications` argument should be conditional when choosing SKU, not required for `Premium` and removed for other values

### ISSUE THREAD

**Issue by thpang** [hashicorp/terraform-provider-azurerm#12070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.62.0
+ provider registry.terraform.io/hashicorp/cloudinit v2.2.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Affected Resource(s)

* `azurerm_container_regsitry`

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "acr" {
  count                    = var.create_container_registry ? 1 : 0
  name                     = join("", regexall("[a-zA-Z0-9]+", "${var.prefix}acr")) # alpha numeric characters only are allowed
  resource_group_name      = module.resource_group.name
  location                 = var.location
  sku                      = var.container_registry_sku
  admin_enabled            = var.container_registry_admin_enabled
  # georeplication_locations = var.container_registry_sku == "Premium" ? var.container_registry_geo_replica_locs : null

  # georeplications = var.container_registry_sku == "Premium" ? [
  #   for location_item in var.container_registry_geo_replica_locs:
  #     {
  #       location = location_item
  #       tags     = var.tags
  #     }
  # ] : null

  dynamic "georeplications" {
    for_each = var.container_registry_sku == "Premium" ? var.container_registry_geo_replica_locs : []
    iterator = each
    content {
      location = each.value
      tags     = var.tags
    }
  }

  tags                     = module.resource_group.tags
  depends_on               = [module.resource_group]
}
```

### Expected Behaviour

As you can see by the code snippet, I am migrating from the deprecated `gereplication_locations` argument to the new `georeplications` argument. 

In most resources it is acceptable to simply apply a conditional item to the argument and pass in `null` if that argument is not needed, however, with this module I need to either specify `georeplications` if I am using a SKU of `Premium` or I need to completely remove that argument if my SKU is anything else.

If had coded it this way:

```hcl
  georeplications = var.container_registry_sku == "Premium" ? [
    for location_item in var.container_registry_geo_replica_locs:
      {
        location = location_item
        tags     = var.tags
      }
  ] : null
```
things should work regardless of the SKU type selected.

### Steps to Reproduce

If my SKU is set to `Premium` I can include the `georeplications` argument. If my SKU is not set to `Premium` I must remove the `georeplications` argument completely.

Code snippet location: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/container_registry_resource.go#L326-L328

1. `terraform apply`

### References

* #0000

**Comment by luckeyca** [comment]
This georeplications property change, introduced in azurerm provider 2.82.0, not only caused the issue reported here, which supposed to be an optional parameter, but becomes mandatory, but also move up a breaking change scheduled for 3.x to version 2.82.0. The correct schedule was mentioned here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#resource-azurerm_container_registry

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
