### ISSUE TITLE
azurerm_firewall does not allow you to enable firewall with default DNS servers

### ISSUE THREAD

**Issue by vsabella** [hashicorp/terraform-provider-azurerm#12084]
https://github.com/terraform-providers/terraform-provider-azurerm/blob/8fc7613206855de21b1771a209510890f701a24b/azurerm/internal/services/firewall/firewall_resource.go#L624

AuzreRM Firewall does not allow you to enable the firewall DNS proxy unless you use Firewall Policy. This looks like a bug in the design of the module.

I want to enable the firewall DNS, without using a Firewall Policy object.

**Comment by darren-johnson** [comment]
This is an issue for us too.  The newer 'Objects have been changed' message doesn't pick this up either.

**Comment by cpressland** [comment]
We've just bumped into this while planning a migration to AKS. I don't really see what operational benefits Firewall Policies provide us when using Terraform, so would rather continue using "Rules (Classic)" along with DNS Proxy if possible.
