### ISSUE TITLE
Error: Error making Read request on Azure Backup Protected VM backup.ProtectedItemsClient#Get: Failuresending request: StatusCode=429 -- Original Error: context deadline exceede

### ISSUE THREAD

**Issue by GanapathiGS** [hashicorp/terraform-provider-azurerm#12095]
Every time I run the terraform plan/apply I get below error .  I tried to comment out the backup option for few VM's but still get error for different VM .  
Can you please engage someone from Terraform team to check this ? 

Error: Error making Read request on Azure Backup Protected VM "VM;iaasvmcontainerv2;rg-nonprod-dev-extportal;dvextptlord01" (Resource Group "rg-nonprod-apps"): backup.ProtectedItemsClient#Get: Failuresending request: StatusCode=429 -- Original Error: context deadline exceeded
│
│   with module.compute_rg-nonprod-dev-extportal-epservers.azurerm_backup_protected_vm.linux_vm_resources_to_backup["dvextptlord01"],
│   on azuremodules/compute/main.tf line 435, in resource "azurerm_backup_protected_vm" "linux_vm_resources_to_backup":
│  435: resource "azurerm_backup_protected_vm" "linux_vm_resources_to_backup" {

I have excluded below VM's from backup schedule to check if it helps .  But the error shows up different system names in next Terrform run  . 

[Terraform error messages- June 7 2021.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/6610041/Terraform.error.messages-.June.7.2021.txt)

**Comment by GanapathiGS** [comment]
Getting below error with AzureRM version : 

 -bash: [clt-ggounder@npibmatools01: command not found
[clt-ggounder@npibmatools01 NONPROD]$ source init.sh
Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
╷
│ Warning: Empty provider configuration blocks are not required
│
│   on azuremodules/compute/main.tf line 13:
│   13: provider "azurerm" {
│
│ Remove the azurerm.kv provider block from module.compute_rg-nonprod-ssvc-automationtools. Add azurerm.kv to the
│ list of configuration_aliases for azurerm in required_providers to define the provider configuration name.
│
│ (and 101 more similar warnings elsewhere)
╵

╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/azurerm: locked provider
│ registry.terraform.io/hashicorp/azurerm 2.45.1 does not match configured version constraint 2.45.1, 2.62.0; must
│ use terraform init -upgrade to allow selection of new versions
╵

[clt-ggounder@npibmatools01 NONPROD]$ terraform version
Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.45.1
[clt-ggounder@npibmatools01 NONPROD]

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
