### ISSUE TITLE
AuthorizationPermissionMismatch with Storage Account and storage_use_azuread=true

### ISSUE THREAD

**Issue by jhyot** [hashicorp/terraform-provider-azurerm#12138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.61.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 0.15.3"

  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~> 2.61.0"
    }
  }
}
provider "azurerm" {
  features {}
  storage_use_azuread = true
}


resource "azurerm_resource_group" "rg" {
  name = "rg-jhyot-storage-test"
  location = "westeurope"
}
resource "azurerm_storage_account" "blob-storage" {
  name = "storageadblobtest"
  resource_group_name = azurerm_resource_group.rg.name
  location = "westeurope"

  account_tier = "Standard"
  account_replication_type = "LRS"
  enable_https_traffic_only = "true"
  min_tls_version = "TLS1_2"
  allow_blob_public_access = false
}
```

### Expected Behaviour

Terraform creates the Storage Account and can access it afterwards.

### Actual Behaviour

Terraform creates the Storage Account, but cannot access it anymore, due to this error:
```
azurerm_resource_group.rg: Creating...
azurerm_resource_group.rg: Creation complete after 1s [id=xxxxxxxxxxxxxxx]
azurerm_storage_account.blob-storage: Creating...
╷
│ Error: Error reading queue properties for AzureRM Storage Account "storageadblobtest": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationPermissionMismatch" Message="This request is not authorized to perform this operation using this permission.\nRequestId:7a7dc5b4-b003-0074-2711-5d75e9000000\nTime:2021-06-09T09:28:55.6944380Z"
│
│   with azurerm_storage_account.blob-storage,
│   on main.tf line 23, in resource "azurerm_storage_account" "blob-storage":
│   23: resource "azurerm_storage_account" "blob-storage" {
│
╵
```

Any subsequent `terraform apply`, `terraform destroy` etc. command fails because of the error. The resource was created correctly.

### Steps to Reproduce

Use above config.
1. `terraform apply`

### Notes

If I set `storage_use_azuread = false`, everything works.

I don't think that this is a permission issue on my side, because I have the subscription-scoped roles:
* Storage Account Contributor 
* Storage Blob Data Owner
* Storage Queue Data Contributor

And the access to Queues works in Azure Portal, also when using "Authentication method: Azure AD User Account" in Portal.

**Comment by jhyot** [comment]
Debugging a bit what kind of HTTP calls get made, I see the following difference between GetBlobServices (which 
succeeds) and GetQueueServices (which fails with 403). Don't know if that's significant though.

GetBlobServices (returns 200):
```
INFO: REQUEST: GET https://management.azure.com/subscriptions/xxxxxxxxxxxxxx/resourceGroups/rg-jhyot-storage-test/providers/Microsoft.Storage/storageAccounts/storageadblobtest/blobServices/default?api-version=2021-01-01
```

GetQueueServices (returns 403):
```
INFO: REQUEST: GET https://storageadblobtest.queue.core.windows.net/?comp=properties&restype=service
```

**Comment by jhyot** [comment]
Anything that can be done to advance this ticket? We would like to disable access keys for our Azure Storage, and access only via Azure AD, but we are blocked by this because it doesn't work with Azure AD.

**Comment by piyush94** [comment]
I am also facing this issue when trying to update Azure File Share behind a private subnet. I added `storage_use_azuread = true` in the provider config but still facing issue of 403 Forbidden.

**Comment by Bluffkin** [comment]
All of a sudden I am getting 403 too.
Terraform v1.1.4
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
