### ISSUE TITLE
Azurerm plugin upgrade from 0.1.44 to 2.20.0 causing import failure for deprecated feilds

### ISSUE THREAD

**Issue by reddeppas** [hashicorp/terraform-provider-azurerm#12149]
### Description 
After upgrading terrafrom from 0.11.14 to 0.12 and Azure ARM plugin from 1.44 to 2.20 we are observing terraform resource creation for deprecated fields and terraform import also failing

route_table_id  ->  replaced with resource: azurerm_subnet_route_table_association
network_security_group_id ->  replaced with resource: azurerm_subnet_network_security_group_association
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.0

Your version of Terraform is out of date! The latest version
is 1.0.0. You can update by downloading from www.terraform.io/downloads.html

### Affected Resource(s)

route_table_id  ->  replaced with resource: azurerm_subnet_route_table_association
network_security_group_id ->  replaced with resource: azurerm_subnet_network_security_group_association
* 

### Terraform Configuration Files

```
resource "azurerm_resource_group" "redacted" {
        name = "redacted"
        location = "redacted"
    }

    resource "azurerm_route_table" "redacted" {
        name                = "routes_redacted"
        location            = "${azurerm_resource_group.redacted.location}"
        resource_group_name = "${azurerm_resource_group.redacted.name}"


        route {
            name                    = "REDACTED"
            address_prefix          = "REDACTED"
            next_hop_type           = "VirtualAppliance"
            next_hop_in_ip_address  = "REDACTED"
        }


    }

    resource "azurerm_virtual_network" "redacted" {

        name                = "redacted_ARM"
        resource_group_name = "${azurerm_resource_group.redacted.name}"

        address_space       = [ "REDACTED" ]
        location            = "${azurerm_resource_group.redacted.location}"
        dns_servers         = [ "REDACTED", "REDACTED" ]
    }


    resource "azurerm_subnet" "redacted_K8S" {
        name                    = "redacted_K8S"
        address_prefixes          = ["REDACTED"]
        virtual_network_name    = "${azurerm_virtual_network.redacted.name}"

        resource_group_name     = "${azurerm_resource_group.redacted.name}"

    }
    resource "azurerm_subnet_route_table_association" "redacted_K8S" {
       subnet_id      = "${azurerm_subnet.redacted_K8S.id}"
       route_table_id = "${azurerm_route_table.redacted.id}"
    }



```

### Debug Output

Terraform Apply Error
Error: A resource with the ID "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Network/virtualNetworks/redacted_ARM/subnets/redacted" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_subnet_route_table_association" for more information.

  on ../tf-work-mr-play-A/sdn.tf line 145, in resource "azurerm_subnet_route_table_association" "redacted":
 145:     resource "azurerm_subnet_route_table_association" "redacted" {

Terraform Import Error:
Error: Cannot import non-existent remote object

While attempting to import an existing object to
azurerm_subnet_route_table_association.redacted_Default, the provider
detected that no object exists with the given id. Only pre-existing objects
can be imported; check that the id is correct and that it is associated with
the provider's configured region or endpoint, or use "terraform apply" to
create a new remote object for this resource.

### Panic Output

None

### Expected Behaviour
Either terraform Apply or the terraform import should work

### Actual Behaviour

Terraform is not creating the resource and import is failing as well

### Steps to Reproduce

1. update terraform from 0.11.14 to 0.12
2. updated azure arm plugin from 1.44 to 2.20.0
3. migrate deprecated feild to resources 

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
