### ISSUE TITLE
Express route circuit private peering attempts to create Microsoft peering item

### ISSUE THREAD

**Issue by jonhadfield** [hashicorp/terraform-provider-azurerm#12148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
After importing an Express route circuit private peering, subsequent plans show a change will be made to introduce an empty 'route_filter_id' which is a property of Microsoft peerings only. This is reproduceable, so please let me know if more detail is required.
I've encountered another issue like this, with the same resource type, where the plan attempts to create an empty Microsoft peering (one has never been defined in Azure nor in our tf file for this peering) and, by applying it, it actually resulted in the BGP key being deleted. This removal was not reflected in the Azure activity log, but a Microsoft engineer was able to see it in their backend logs. My concern is that, by applying this plan, it may have the same effect. 

```
Terraform v0.15.5
on darwin_amd64
provider registry.terraform.io/hashicorp/azurerm v2.62.0
```

Component:`azurerm_express_route_circuit_peering`

Resource defined in tf file
```
resource "azurerm_express_route_circuit_peering" "redacted" {
  lifecycle {
    ignore_changes = [shared_key, microsoft_peering_config, route_filter_id]
  }
  peering_type                  = "AzurePrivatePeering"
  resource_group_name = redacted
  peer_asn = 65013
  express_route_circuit_name = redacted
  primary_peer_address_prefix = "10.41.255.252/30"
  secondary_peer_address_prefix = "10.41.254.252/30"
  vlan_id = 100
  shared_key = redacted
}
```

After importing my state is:
```
   {
      "mode": "managed",
      "type": "azurerm_express_route_circuit_peering",
      "name": "redacted",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "azure_asn": 12076,
            "express_route_circuit_name": "redacted",
            "id": "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Network/expressRouteCircuits/redacted/peerings/AzurePrivatePeering",
            "ipv6": [],
            "microsoft_peering_config": [],
            "peer_asn": 65013,
            "peering_type": "AzurePrivatePeering",
            "primary_azure_port": "EQIX-LON31-09XGMR-CIS-1-PRI-A",
            "primary_peer_address_prefix": "10.41.255.252/30",
            "resource_group_name": "redacted,
            "route_filter_id": "",
            "secondary_azure_port": "EQIX-LON31-09XGMR-CIS-2-SEC-A",
            "secondary_peer_address_prefix": "10.41.254.252/30",
            "shared_key": null,
            "timeouts": {
              "create": null,
              "delete": null,
              "read": null,
              "update": null
            },
            "vlan_id": 100
          },
          "sensitive_attributes": [],
          "private": "redacted"
        }
      ]
    },
```

A plan (after import, using the above tf file extract) shows
```
Terraform will perform the following actions:

  # azurerm_express_route_circuit_peering.redacted will be updated in-place
  ~ resource "azurerm_express_route_circuit_peering" "redacted" {
        id                            = "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.Network/expressRouteCircuits/redacted/peerings/AzurePrivatePeering"
      + route_filter_id               = ""
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

**Comment by HariprasadM-TomTom** [comment]
We have the same issue as well. Terraform is attempting to apply "route_filter_id" attribute which is intended for Microsoft peering as per the documentation [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/express_route_circuit_peering#route_filter_id)

Terraform version:
```
Terraform v0.15.5
on linux_amd64
```

Provider:
```
azurerm = {
  source  = "hashicorp/azurerm"
  version = "2.66.0"
}
```

Terraform plan:
```
Terraform will perform the following actions:

  # azurerm_express_route_circuit_peering.er_circuit_peering_azure_private will be updated in-place
  ~ resource "azurerm_express_route_circuit_peering" "azure_private_peering" {
        id                            = "/subscriptions/xxxxxx/resourceGroups/xxxxxxx/providers/Microsoft.Network/expressRouteCircuits/xxxxxx/peerings/AzurePrivatePeering"
      + route_filter_id               = ""
        # (10 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
