### ISSUE TITLE
Support for Azure Event Hubs Namespace Premium tier

### ISSUE THREAD

**Issue by joshuahancox** [hashicorp/terraform-provider-azurerm#12141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Event Hubs Namespace has recently added a new tier named Premium

(https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quotas)

Currently the provider only allows for sku's `Basic` and `Standard`. Could the premium tier be added? @favoretti 

### New or Affected Resource(s)

* azurerm_eventhub_namespace

### Potential Terraform Configuration

```hcl
resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Premium"
  capacity            = 2
}
```

**Comment by favoretti** [comment]
Will look into it in a bit.

**Comment by favoretti** [comment]
As discussed offline, this requires a newer API version. As soon as we're able to upgrade this can be added.

**Comment by sehgalnamit** [comment]
There is a problem in the terraform documentation 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub_namespace_customer_managed_key

resource "azurerm_eventhub_namespace" "example" {
  name                 = "example-namespace"
  location             = azurerm_resource_group.example.location
  resource_group_name  = azurerm_resource_group.example.name
  sku                  = "Standard"
  dedicated_cluster_id = azurerm_eventhub_cluster.example.id

  identity {
    type = "SystemAssigned"
  }
}


It doe snot work with Standard

2021-06-29 16:49:51  Error: creating/updating Namespace: (Name "ehn-sgrtss-dev-az1-mwrgy7" / Resource Group "rsg-sgrtss-dev-az1-mwrgy7"): performing CreateOrUpdate: namespaces.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Customer-managed key encryption at rest is only available for namespaces of premium SKU or namespaces created in a Dedicated Cluster. CorrelationId: 30c70fb5-4826-fbd6-6089-3523dac06562"
2021-06-29 16:49:51

So documentation must be fixed and feature should only be included if this is being tested.

**Comment by mybayern1974** [comment]
I'm closing this issue by noticing [PR 12695](https://github.com/hashicorp/terraform-provider-azurerm/pull/12695) trying to address this has been merged and released. Please suggest to reopen this issue if there are any other stories.
