### ISSUE TITLE
azurerm_firewall_application_rule_collection Error: expanding Firewall Application Rules: `fqdn_tags` cannot be used with `target_fqdns` or `protocol`

### ISSUE THREAD

**Issue by thedevopscat** [hashicorp/terraform-provider-azurerm#12157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1
+ provider registry.terraform.io/hashicorp/http v2.1.0

### Affected Resource(s)

azurerm_firewall_application_rule_collection

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_application_rule_collection" "aksfwar" {
  name                = "aksfwar"
  azure_firewall_name = azurerm_firewall.firewall_msdn.name
  resource_group_name = azurerm_firewall.firewall_msdn.resource_group_name
  priority            = 101
  action              = "Allow"
  rule {
    name = "allow fqdn"
    source_addresses = [
      "*",
    ]
    fqdn_tags = [
      "AzureKubernetesService",
    ]
    protocol {
      port = "80"
      type = "Http"
    }
    protocol {
      port = "443"
      type = "Https"
    }
  }
}
```
### Expected Behaviour

When using the portal or AZ Cli the protocol blocks are added (indeed AZ Cli won't run without them).

### Actual Behaviour

When using the Terraform configuration above we receive the following error.

 Error: expanding Firewall Application Rules: `fqdn_tags` cannot be used with `target_fqdns` or `protocol`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
