### ISSUE TITLE
Support for azurerm_function_app using Managed Identity base access for its AzureWebJobsStorage connection

### ISSUE THREAD

**Issue by Roshick** [hashicorp/terraform-provider-azurerm#12155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the new public preview of Function Apps, it is now possible for the App to use a Managed Identity to access its Storage Account. Currently, the storage_account_access_key variable is required to deploy a Function App, making it impossible to avoid secret handling. As we strive to use Managed Identities everywhere, it would be nice to have this feature supported.

### New or Affected Resource(s)

* azurerm_function_app

### References

https://azure.microsoft.com/en-us/updates/public-preview-identitybased-connections-in-azure-functions-with-latest-azure-sdk-triggers-and-bindings/

* #0000

**Comment by lonegunmanb** [comment]
Actually `storage_account_access_key` is optional now, the document need to be updated. You can ignore it and use `identity` as Managed Identity directly now.

**Comment by Roshick** [comment]
Awesome, thanks a lot for the info. :)

**Comment by lonegunmanb** [comment]
You're welcome!

**Comment by mybayern1974** [comment]
Close this issue with assuming the question has been answered. Feel free to suggest to reopen if not.

**Comment by ZachTB123** [comment]
@lonegunmanb I tried this with version 2.77.0 of the provider and I'm still getting an error:

```
Error: one of `storage_connection_string` or `storage_account_name` and `storage_account_access_key` must be specified
```

When adding back name I get:

```
Error: both `storage_account_name` and `storage_account_access_key` must be specified
```

Am I missing something?

**Comment by lonegunmanb** [comment]
@ZachTB123 you're right, there's still outdated constraint guard remain in function_app.go file. The #13410 is insufficient. I'll resubmit a new pr.
