### ISSUE TITLE
Support for Authentication Type for IotHub Endpoints, IoTHub Routes and IoTHub Enrichment

### ISSUE THREAD

**Issue by eranjbarSuncor** [hashicorp/terraform-provider-azurerm#12170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The IoTHub supports the Managed Service Identity Feature to use the MSI for Authorization against endpoints.

Currently it is not possible to create an IoT Hub with system assigned or user assigned identity

When a user-assigned or system assigned identity is created using manually, it is not possible to use the Identity for Authorization when creating IoT Hub Endpoints

When creating the endpoint authentication type manually, it breaks several azurerm modules from being able to utilize those endpoints:
- `azurerm_iothub_route`
- `azurerm_iothub_enrichment`
- 
with an error stating that the managed identity is not associated with the IoTHub even though it is. **I am able to manually create the routes with the same settings using ARM template, az cli or portal**
### New or Affected Resource(s)

* azurerm_iothub_route
* azurerm_iothub_enrichment
* azurerm_iothub
* azurerm_iothub_endpoint_*

### Potential Terraform Configuration

`azurerm_iothub_endpoint_*` and `azurerm_iothub`:
```hcl
use_managed_identity = true
user_assigned_identity = azurerm_user_assigned_identity.test.id # (optional value, defaults to system assigned identity)
```

`azurerm_iothub_route` and `azurerm_iothub_enrichment` would work as expected, regardless of if there's an assigned identity or not on the endpoint

### References

* #9139

**Comment by luckeyca** [comment]
and one more use case is when connecting to event hub as custom endpoint, it can only use managed identity as MS document here: https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support#egress-connectivity-from-iot-hub-to-other-azure-resources

**Comment by myc2h6o** [comment]
Hi @eranjbarSuncor identity-based endpoints are being added in #9139, it shall be able to resolve this issue. Rather than having multiple issues open to track the same thing, would you mind subscribing to it for update? Feel free to reopen this issue if it cannot be fully resolved.

**Comment by mybayern1974** [comment]
Hi @eranjbarSuncor , I'm closing this issue for it being dup with #9139 that's been resolved now. Please suggest to reopen if you believe it's not the case.
