### ISSUE TITLE
azurerm_linux_virtual_machine_scale_set data disk size to be optional when create_option = FromImage

### ISSUE THREAD

**Issue by shurikk** [hashicorp/terraform-provider-azurerm#12204]
`azurerm_linux_virtual_machine_scale_set` data disk size should be optional when `create_option` is `FromImage` similar to `virtual_machine_scale_set`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

latest

### Affected Resource(s)

* `azurerm_linux_virtual_machine_scale_set`

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#disk_size_gb
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_scale_set#disk_size_gb

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. From the [latest documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#disk_size_gb), data_disk appears to be optional. As such I am going to close this issue, if that is not the case on the latest version of the provider (4.x), please feel free to open a new issue!
