### ISSUE TITLE
Azure Firewall policy can't be replaced because it's in use

### ISSUE THREAD

**Issue by edoboker** [hashicorp/terraform-provider-azurerm#12212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `Terraform 0.15.5`
* `azurerm_2.62.0`

### Affected Resource(s)

* `azurerm_firewall_policy`
* `azurerm_firewall`

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "policy_rg" {
  name = var.policy_rg_name
}

resource "azurerm_firewall_policy" "policy" {
  name                = var.policy_name_override == null? local.policy_name : var.policy_name_override
  resource_group_name = data.azurerm_resource_group.policy_rg.name
  location            = data.azurerm_resource_group.policy_rg.location
  
  tags = merge(data.azurerm_resource_group.policy_rg.tags, var.tags)
  
  dynamic "dns" {
    for_each = var.dns_settings
    content {
      servers       = lookup(dns.value, "servers", [])
      proxy_enabled = dns.value["proxy_enabled"]
    }
  }
}
```

### Expected Behaviour

Terraform should dissociate the firewall policy, then replace (delete and re-create) it

### Actual Behaviour

Terraform fails to replace the firewall policy since it is in use by an Azure Firewall:

>  Error: deleting Firewall Policy "fw-policy" (Resource Group "cp-dmz-intranet-rg"): network.FirewallPoliciesClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code="FirewallPolicyHasAzureFirewallRefer
ences" Message="Firewall Policy '/....../rg/providers/Microsoft.Network/firewallPolicies/fw-policy' can not be deleted since there are Azure Firewalls using this policy."

### Steps to Reproduce

1. `terraform apply`
2. Change the name of the policy
3. `terraform apply` again

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
