### ISSUE TITLE
Azure Function: Setting client_cert_mode to Required does not change clientCertEnabled to true.

### ISSUE THREAD

**Issue by jwshive** [hashicorp/terraform-provider-azurerm#12216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `Terraform v0.14.11`
* `provider registry.terraform.io/hashicorp/azurerm v2.63.0`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "function-app-1" {
  name                       = "${local.resource-name-prefix}-fn1"
  location                   = var.resource-location
  resource_group_name        = local.resource-group-name
  app_service_plan_id        = azurerm_app_service_plan.function-app-sp.id
  storage_account_name       = azurerm_storage_account.working-storage_account.name
  storage_account_access_key = azurerm_storage_account.working-storage_account.primary_access_key
  os_type                    = "linux"
  https_only                 = true
  client_cert_mode           = "Required"
  tags                       = merge(local.common_tags, tomap({ "type" = "function-app" }))
}
```

### Expected Behaviour

Azure Recommendation: Function apps should have Client Certificates (Incoming client certificates) enabled resolves.
clientCertEnabled is set to true
```
    "clientCertEnabled": false, -> true
    "clientCertExclusionPaths": null,
    "clientCertMode": "Required",
```

### Actual Behaviour

ClientCertEnabled still remains false.
```    
    "clientCertEnabled": false,
    "clientCertExclusionPaths": null,
    "clientCertMode": "Required",
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This work is being done in azure government cloud.
Pull Request https://github.com/terraform-providers/terraform-provider-azurerm/pull/11161 seems to be meant to set client cert to enabled but doesn't appear to actually affect clientCertEnabled field.

### References

* #11161

**Comment by jwshive** [comment]
Manually setting clientCertEnabled using azure cli flipped this check to passing.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
