### ISSUE TITLE
Unable to create Windows VM from SIG Image Version with Replication to target region

### ISSUE THREAD

**Issue by ryan-rockwell** [hashicorp/terraform-provider-azurerm#12217]
I am using shared image gallery images to create VMs. The image used in this example is a custom, generalized image hosted in a SIG in the Central US region. The image is also replicated to the North Central US region.

I can successfully create VMs in the Central US region with this image using the following methods:
+ Terraform `azurerm_windows_virtual_machine` with a `source_image_id`
+ Azure ARM template
+ Manually through the portal

The problem occurs when creating VMs using this image in the North Central US region. It works using these methods:
+ Azure ARM template
+ Manually through the portal

However it does not when using this method:
+ Terraform `azurerm_windows_virtual_machine` with a `source_image_id`

### Terraform (and AzureRM Provider) Version

+ `Terraform v0.14.5`
+ `provider registry.terraform.io/hashicorp/azurerm v2.58.0`

### Affected Resource(s)

+ `azurerm_windows_virtual_machine`
+ `azurerm_shared_image_version`

### Terraform Configuration Files

```hcl
# Shared Image Version referencing an image originally created in Central US, and replicated to North Central US
data "azurerm_shared_image_version" "sig_image" {
  name                = var.image_version
  image_name          = var.image_name
  gallery_name        = var.shared_image_gallery_name
  resource_group_name = var.shared_image_gallery_resource_group
}

# Windows VM to be created in North Central US region
resource "azurerm_windows_virtual_machine" "windows-machine" {
  # other fields left out for brevity 
  location        = "northcentralus"
  source_image_id = data.azurerm_shared_image_version.sig_image.managed_image_id
}
```

### Expected Behaviour

A VM is created in the North Central US region from the source image that was originally created in a Central US Shared Image Gallery and replicated to North Central US. 

### Actual Behaviour

`terraform apply` fails with the error:
```
Error: creating Windows Virtual Machine "<vm-name>" (Resource Group "<north-central-rg>"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="NotFound" Message="The Image '/subscriptions/<sub-id>/resourceGroups/<central-us-sig-rg>/providers/Microsoft.Compute/images/<image-name>.<image-version>' cannot be found in 'northcentralus' region."
```

### Steps to Reproduce

1. Create a Shared Image Gallery in Central US
2. Create a Shared Image within the gallery that is replicated to both Central US and North Central US
3. Attempt to create an `azurerm_windows_virtual_machine` with the `source_image_id` set to the `managed_image_id` from a shared image gallery version resource
4. `terraform apply`

### Important Factoids

Standard Azure commercial

The terraform state for the `azurerm_shared_image_version` resouurce has the correct target_regions listed. So it seems the Azure API is returning the correct information, but either Azure or Terraform can't recognize this VM should be able to be created. See snippet below:
```
"target_region": [
              {
                "name": "centralus",
                "regional_replica_count": 1,
                "storage_account_type": "Standard_LRS"
              },
              {
                "name": "northcentralus",
                "regional_replica_count": 1,
                "storage_account_type": "Standard_LRS"
              }
            ]
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
