### ISSUE TITLE
Failure to update between Basic and Standard tiers on mssql failover group

### ISSUE THREAD

**Issue by pivotal-marcela-campo** [hashicorp/terraform-provider-azurerm#12235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.31
terraform-provider-azurerm v2.59.0

### Affected Resource(s)

* azurerm_mssql_database
* azurerm_sql_failover_group

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

variable instance_name {
    type = string
    default = "fog-force-3"
}
variable resource_group {
    type = string
    default = "test-mssql-db-rg2"
}
variable db_name {
    type = string
    default = "test-db3"
}
variable location {
    type = string
    default = "eastus2"
}
variable labels {
    type = map
    default = {}
}
variable sku_name {
    type = string
    default = "Basic"
}
variable max_storage_gb {
    type = number
    default = 2
}

provider "azurerm" {
  version = "~> 2.59.0"
  features {}
}

resource "azurerm_resource_group" "azure-sql-fog" {
  name     = var.resource_group
  location = var.location
  tags     = var.labels
}

resource "random_string" "username" {
  length = 16
  special = false
  number = false
}

resource "random_password" "password" {
  length = 64
  override_special = "~_-."
  min_upper = 2
  min_lower = 2
  min_special = 2
}

resource "azurerm_sql_server" "primary_azure_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-primary-2", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = var.location
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags = var.labels
}

resource "azurerm_sql_server" "secondary_azure_sql_db_server" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                         = format("%s-secondary-2", var.instance_name)
  resource_group_name          = var.resource_group
  location                     = "centralus"
  version                      = "12.0"
  administrator_login          = random_string.username.result
  administrator_login_password = random_password.password.result
  tags                         = var.labels
}

resource "azurerm_mssql_database" "primary_db" {
  name                = var.db_name
  server_id           = azurerm_sql_server.primary_azure_sql_db_server.id
  sku_name            = var.sku_name
  max_size_gb         = var.max_storage_gb
  tags                = var.labels
}

# azurerm_mssql_database.secondary_db:
resource "azurerm_mssql_database" "secondary_db" {
    create_mode                 = "Secondary"
    creation_source_database_id = azurerm_mssql_database.primary_db.id
    sku_name            = var.sku_name
    name                        = var.db_name
    server_id                   = azurerm_sql_server.secondary_azure_sql_db_server.id
    tags                        = {}
}

resource "azurerm_sql_failover_group" "failover_group" {
  depends_on = [ azurerm_resource_group.azure-sql-fog ]
  name                = var.instance_name
  resource_group_name = var.resource_group
  server_name         = azurerm_sql_server.primary_azure_sql_db_server.name
  databases           = [azurerm_mssql_database.primary_db.id]
  partner_servers {
    id = azurerm_sql_server.secondary_azure_sql_db_server.id
  }

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 5
  }
}

output primary_server_name { value = azurerm_sql_server.primary_azure_sql_db_server.name }
output secondary_server_name { value = azurerm_sql_server.secondary_azure_sql_db_server.name }
output failover_group_name { value = azurerm_sql_failover_group.failover_group.name }
output resource_group { value = var.resource_group }
output primary_db_name { value = azurerm_mssql_database.primary_db.name }
output secondary_db_name { value = azurerm_mssql_database.secondary_db.name }



```

### Expected Behaviour

Primary and Secondary database sku should have been successfully updated

### Actual Behaviour

Consistently fails with:
```
Error: waiting for creation of MsSql Database "test-db3" (MsSql Server Name "fog-force-3-primary-2" / Resource Group "test-mssql-db-rg2"): Code="SourceDatabaseEditionCouldNotBeUpgraded" Message="The source database 'fog-force-3-primary-2.test-db3' cannot have higher edition than the target database 'fog-force-3-secondary-2.test-db3'. Upgrade the edition on the target before upgrading source."

  on provision-mssql-failover.tf line 77, in resource "azurerm_mssql_database" "primary_db":
  77: resource "azurerm_mssql_database" "primary_db" {
```

### Steps to Reproduce

1. `terraform apply`
2. Change `Basic` for `S0` as default value for variable `sku_name`
3. `terraform apply`

### References

Opened based on **[cloudfoundry-incubator/csb-brokerpak-azure#47](https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/47)**

**Comment by blgm** [comment]
@aristosvo, you [mentioned](https://github.com/cloudfoundry-incubator/csb-brokerpak-azure/issues/20#issuecomment-850209145) that you might have a fix for this, but unfortunately it got deleted. Do you remember enough about it to point someone in the right direction?

**Comment by aristosvo** [comment]
@blgm Sure! What would be the best way to pass this information on? I'm on the Slack channel and available for direct communication, just limited in time :)

It boils basically down to the following:
- find the Failover databases for the primary
- upgrade the tier of these
- upgrade the primary

I believe I've implemented this pattern already for Postgres I believe, but the API is a bit different for MsSql.

**Comment by manicminer** [comment]
Looking into this a bit further, unfortunately I'm doubtful that we can resolve this dependency issue within the provider. By nature, database A that replicates from database B requires A to be created first, however this order is imposed by Terraform core and I don't believe it's possible for a provider to reverse it.

In such cases, as a workaround I'd suggest using `terraform plan -target azurerm_mssql_database.secondary_db` which is provided for such circumstances as these.

**Comment by pivotal-marcela-campo** [comment]
Hi @manicminer ,  Thank you for your comment. @aristosvo had mentioned [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/12235#issuecomment-869833739) exactly that pattern of updating secondary first and then primary within the provider itself and that that similar pattern has been implemented previously for Postgres. 
Is it impossible to apply that thinking here?

**Comment by manicminer** [comment]
@pivotal-marcela-campo We've discussed internally and given there's little other option, we'll try to implement this as part of the database resource (similarly to how it has been achieved in the postgres resource). It looks like it should be doable in theory.

**Comment by pivotal-marcela-campo** [comment]
Thank you @manicminer for reviewing it!

**Comment by kirederik** [comment]
Thanks @manicminer and team!
