### ISSUE TITLE
Changes that require replacement of the azurerm_app_service_plan do not trigger replacement of the azurerm_function_app

### ISSUE THREAD

**Issue by alex-goncharov** [hashicorp/terraform-provider-azurerm#12232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -v
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.56.0

### Affected Resource(s)

* `azurerm_app_service_plan`
* `azurerm_function_app`

### Debug Output

Error: Error deleting App Service Plan "this" (Resource Group "this"): web.AppServicePlansClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

```
{
  "Code": "Conflict",
  "Message": "Server farm 'this-apsp' cannot be deleted because it has web app(s) this-func assigned to it.",
  "Target": null,
  "Details": [
    {
      "Message": "Server farm 'this-apsp' cannot be deleted because it has web app(s) this-func assigned to it."
    },
    {
      "Code": "Conflict"
    },
    {
      "ErrorEntity": {
        "ExtendedCode": "11003",
        "MessageTemplate": "Server farm '{0}' cannot be deleted because it has web app(s) {1} assigned to it.",
        "Parameters": [
          "this-apsp",
          "this-func"
        ],
        "Code": "Conflict",
        "Message": "Server farm 'this-apsp' cannot be deleted because it has web app(s) this-func assigned to it."
      }
    }
  ],
  "Innererror": null
}

```

### Expected Behaviour

The azurerm_function_app is also replaced (or the error message is changed to be informative during the plan stage).

### Actual Behaviour

Terraform apply fails with 

rror: Error deleting App Service Plan "this" (Resource Group "this"): web.AppServicePlansClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

### Steps to Reproduce

build
azurerm_app_service_environment #1 and #2
azurerm_app_service_plan and azurerm_function_app on azurerm_app_service_environment #1

move azurerm_app_service_plan to azurerm_app_service_environment #2

**Comment by mmcelreath** [comment]
I'm seeing this same behavior when changing the App Service Plan for azurerm_app_service resources as well.

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service_plan` has been superseded by the `azurerm_service_plan` resource.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
