### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert cannot set multiple aggregate on while creating alert rules

### ISSUE THREAD

**Issue by Rakshithkakathkar** [hashicorp/terraform-provider-azurerm#12244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.0
provider registry.terraform.io/hashicorp/azurerm v2.63.0

### Affected Resource(s)

* `azurerm_monitor_scheduled_query_rules_alert`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert" "ContainerCpuAlert" {
  name                = "AKS-Container CPU Alert"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    action_group = [data.azurerm_monitor_action_group.actiongroup.id]
  }

  data_source_id = azurerm_log_analytics_workspace.example.id
  description    = "Query results grouped into AggregatedValue; alert when results cross threshold"
  enabled        = true
  query          = <<-QUERY
   .....
  QUERY
  severity       = 2
  frequency      = 15
  time_window    = 15
  trigger {
    operator  = "GreaterThan"
    threshold = 90
    metric_trigger {
      operator            = "GreaterThan"
      threshold           = 1
      metric_trigger_type = "Consecutive"
      metric_column       = "ControllerName, ContainerName"
    }
  }
}
```

### Expected Behaviour

As seen in the above code, I am using 2 values which is against the documentation provided in a hope that it will add multiple dimensions. which in fact it added.
metric_column       = "ControllerName, ContainerName" 

On going to Azure portal and checking the export template option, I see the following added as dimensions
```
"dimensions": [
                          {
                             "name": "ControllerName",
                              "operator": "Include",
                              "values": [
                                  "*"
                               ]
                          },
                          {
                             "name": " ContainerName",
                             "operator": "Include",
                             "values": [
                                 "*"
                              ]
                          }
                      ]
```

which is what I wanted and hoping that 
 would also have both Controller name and container name
### Actual Behaviour
![image](https://user-images.githubusercontent.com/16958379/122330985-bd4a5d00-cf51-11eb-8c8d-b358da5cebea.png)

Can see only ControllerName column to aggregate on

### Steps to Reproduce

Create an azurerm_monitor_scheduled_query_rules_alert by passing multiple values into metric_column which are comma seperated

1. `terraform apply`

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
