### ISSUE TITLE
System assigned identity still enabled when using identity type UserAssigned (azurerm_linux_virtual_machine)

### ISSUE THREAD

**Issue by alexisbonnin** [hashicorp/terraform-provider-azurerm#12247]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
- azurerm provider : 2.63.0
- terraform : 0.13.5
### Affected Resource(s)

* `azurerm_linux_virtual_machine `

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "main" {
  identity {
    type = "UserAssigned"
    identity_ids = [<managed identities id list>]
  }
}
```

### Expected Behaviour

According to [azurerm_linux_virtual_machine documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#identity), if identity type if set to `UserAssigned`, system assigned identity should be disabled.

### Actual Behaviour

Even if azurerm_linux_virtual_machine identity type is set to `UserAssigned`, system assigned identity is still enabled.

### Steps to Reproduce

1. `terraform plan`
```hcl
+ resource "azurerm_linux_virtual_machine" "main" {
      + identity {
          + identity_ids = [<managed identities id list>]
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "UserAssigned"
        }
  }
```

2. `terraform apply` (azure virtual machine json definition)
```json
{
  "type": "Microsoft.Compute/virtualMachines",
  "identity": {
      "type": "SystemAssigned",
      "principalId": "aaaaaaa-aaaa-aaaa-aaaaaaaaaa",
      "tenantId": "aaaaaaa-aaaa-aaaa-aaaaaaaaaa"
  }
}
```

**Comment by EvilSmiff** [comment]
We generate our managed id using the code 

resource "azurerm_user_assigned_identity" "managedid" {
  name = var.managedidentity
  resource_group_name = var.rsg
  location            = var.resource_location
}

and then assign it with azurerm_linux_virtual_machine
Seems to work ok.

**Comment by alexisbonnin** [comment]
Can you check if the Virtual Machine `system assigned identity` is still enabled ?
![image](https://user-images.githubusercontent.com/14919537/122386830-8df61900-cf6e-11eb-8e48-d1b857fdd3a3.png)

According to the documentation, if you want both system & user assigned identity, `SystemAssigned, UserAssigned` need to be specified.
If only `UserAssigned` is specificied, system assigned identity should be disabled.

**Comment by EvilSmiff** [comment]
SystemAssigned is set to off.

Provider azurerm 2.61.  The issue may be introduced in the later provider.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
