### ISSUE TITLE
The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."

### ISSUE THREAD

**Issue by dannystaple** [hashicorp/terraform-provider-azurerm#12255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
(.venv) $ terraform version
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.63.0
+ provider registry.terraform.io/hashicorp/external v1.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2
+ provider registry.terraform.io/meilleursagents/ansiblevault v2.2.0
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_user_assigned_identity" "aks_identity" {
  resource_group_name = var.rg_name
  location            = var.rg_location
  name                = "${var.infrastructure_environment}_${var.application_environment}_aks"
  tags = {
    Environment = upper(var.infrastructure_environment)
    managed_by  = module.constants.managed_by
  }
}

resource "azurerm_kubernetes_cluster" "k8s_cluster" {
  name                            = "${var.infrastructure_environment}-${var.application_environment}"
  location                        = var.location
  resource_group_name             = var.rg_name
  dns_prefix                      = "k8s-${var.infrastructure_environment}-${var.application_environment}"
  private_cluster_enabled         = false
  api_server_authorized_ip_ranges = var.authorised_ip_ranges
  kubernetes_version              = var.k8s_version

  default_node_pool {
    name                 = "default"
    node_count           = var.k8s_node_pool.node_count
    vm_size              = var.k8s_node_pool.vm_size
    vnet_subnet_id       = var.node_subnet_id
    enable_auto_scaling  = var.k8s_node_pool.enable_auto_scaling
    min_count            = var.k8s_node_pool.node_min_count
    max_count            = var.k8s_node_pool.node_max_count
    orchestrator_version = var.k8s_version
  }

  identity {
    type                      = "UserAssigned"
    user_assigned_identity_id = azurerm_user_assigned_identity.aks_identity.id
  }

  network_profile {
    network_plugin = "kubenet"

    load_balancer_profile {
      outbound_ip_address_ids = [azurerm_public_ip.aks_public_ip.id]
    }
  }

  tags = {
    Environment = upper(var.infrastructure_environment)
    managed_by  = module.constants.managed_by
  }

  ## Needed for proper resource destroy order - see resource doc.
  depends_on = [
    azurerm_user_assigned_identity.aks_identity,
    azurerm_role_assignment.aks_role_assignment
  ]
}
```

### Debug Output

When I attempt to apply a change for an AKS node pool. I receive a message like the following:

```hcl
│ Error: updating Managed Kubernetes Cluster "cluster" (Resource Group "grp"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidIdentityValues" Message="Invalid value for the identities '/subscriptions/nnn/resourcegroups/grp/providers/Microsoft.ManagedIdentity/userAssignedIdentities/cluster_identity'. The 'UserAssignedIdentities' property keys should only be empty json objects, null or the resource exisiting property."
│ 
│   with module.k8s_wrapper["cluster"].azurerm_kubernetes_cluster.k8s_cluster,
│   on common/azure_k8s/k8s.tf line 34, in resource "azurerm_kubernetes_cluster" "k8s_cluster":
│   34: resource "azurerm_kubernetes_cluster" "k8s_cluster" {
```

It seems that if I modify a cluster (ie pools size, version) it happens once, but goes away on a rerun. 

### Expected Behaviour

It should have applied the changes (cluster version update, node pool version update).

### Actual Behaviour

It failed with the above error. On a rerun it worked. This reproduced on 6 clusters.

### Steps to Reproduce

1.  Configure an AKS cluster in terraform.
2. Specify a version update to the cluster.
3. Apply the terraform.

### Important Factoids

This seems related to #10406, however as the versions show I'm on a later azurerm provider.
It may be important to note that these clusters would have been originally provisioned (and potentially last touched) by an earlier version of the provider.

### References

* #10406

**Comment by kevinharing** [comment]
I'm having the same issue. A retry does not solve the issue though. So currently I'm stuck with a broken pipeline and thus it's blocking.

**Comment by tombuildsstuff** [comment]
Closing since this has been fixed in a newer version of Terraform (at least v2.64.0) - however if your still seeing this issue in the latest version of Terraform then please let us know and we'll take another look.

Thanks!
