### ISSUE TITLE
Support for internal_load_balancing_mode on azurerm_app_service_environment_v3

### ISSUE THREAD

**Issue by haraldatbmw** [hashicorp/terraform-provider-azurerm#12251]
### Terraform (and AzureRM Provider) Version

- Terraform 1.0.0
- AzureRM Provider 2.63.0

### Affected Resource(s)

azurerm_app_service_environment_v3

### Terraform Configuration Files

```hcl
data "azurerm_virtual_network" "vnet" {
  name                = "MyVNET"
  resource_group_name = "Group-VNET"
}

resource "azurerm_subnet" "inbound" {
  name                                           = "ase-in"
  resource_group_name                            = data.azurerm_virtual_network.vnet.resource_group_name
  virtual_network_name                           = data.azurerm_virtual_network.vnet.name
  address_prefixes                               = ["10.9.88.192/27"]
  enforce_private_link_endpoint_network_policies = false
}

resource "azurerm_subnet" "outbound" {
  name                 = "ase-out"
  resource_group_name  = data.azurerm_virtual_network.vnet.resource_group_name
  virtual_network_name = data.azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.9.88.224/27"]

  delegation {
    name = "delegation"
    service_delegation {
      name    = "Microsoft.Web/hostingEnvironments"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "ase-tf"
  location = "westeurope"
}

resource "azurerm_app_service_environment_v3" "ase" {
  name                = "myase"
  resource_group_name = azurerm_resource_group.rg.name
  subnet_id           = azurerm_subnet.outbound.id

  tags = {
    terraformed = "true"
  }
}
```

### Expected Behaviour

When creating an "App Service Environment (preview)" via the Azure Portal the ASE inbound IP is bound into a subnet of my vnet via a private endpoint. Same behaviour is expected when creating via Terraform provider.

### Actual Behaviour

The ASE created via Terraform provider created inbound connection to an external public IP address.

### Steps to Reproduce

1. `terraform apply`

**Comment by haraldatbmw** [comment]
I think the terraform resource `azurerm_app_service_environment_v3` is missing the property `internal_load_balancing_mode` which was available in the predecessor.

**Comment by adamyager** [comment]
This service goes GA next week so any ability to add this to the next release would be apprecated.  Today it cannot be deployed for most use cases.

**Comment by haraldatbmw** [comment]
ASEv3 is now GA - see https://azure.microsoft.com/en-us/updates/app-service-environment-v3-now-generally-available/

**Comment by orenzi-tr** [comment]
The next version 2.68.0 doesn't seem to address this issue also. **Sad Face Emoji**

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md

**Comment by scuderig** [comment]
I'm struggling with the same issue

Not sure I understand what is the point to create an isolated environment and then configure the VIP to be publicly accessible

**Comment by jackofallops** [comment]
Hi all - by way of update, I have the GA update to this resource waiting on a branch, however, we're blocked on a couple SDK/API fixes that are part of this upstream PR: https://github.com/Azure/azure-rest-api-specs/pull/15188. (Notably the dedicated hosts property incorrectly marked as Read Only, and support for configuring zonal resources). As soon as that's merged and made available in an SDK release, we'll get this moving.

**Comment by mcalik77** [comment]
Any news on this issue? Anybody used Arm template to create asev3?
