### ISSUE TITLE
azurerm_private_link_service - Only supports one frontend ip configruation

### ISSUE THREAD

**Issue by jhisc** [hashicorp/terraform-provider-azurerm#12272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.15.1

### Affected Resource(s)

* `azurerm_private_link_service`

### Terraform Configuration Files

```hcl
resource "azurerm_private_link_service" "example" {
  name                = "example-privatelink"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  auto_approval_subscription_ids              = ["00000000-0000-0000-0000-000000000000"]
  visibility_subscription_ids                 = ["00000000-0000-0000-0000-000000000000"]
  load_balancer_frontend_ip_configuration_ids = [azurerm_lb.example1.frontend_ip_configuration.0.id, azurerm_lb.example2.frontend_ip_configuration.0.id]

  nat_ip_configuration {
    name                       = "primary"
    private_ip_address         = "10.5.1.17"
    private_ip_address_version = "IPv4"
    subnet_id                  = azurerm_subnet.example.id
    primary                    = true
  }

  nat_ip_configuration {
    name                       = "secondary"
    private_ip_address         = "10.5.1.18"
    private_ip_address_version = "IPv4"
    subnet_id                  = azurerm_subnet.example.id
    primary                    = false
  }

```

### Expected Behaviour

Multiple load balancers to be added to the Private link service.
Documentation states "A list of Frontend IP Configuration ID's"

### Actual Behaviour

Azure API returns an error due to multiple frontends being specified.

```
│ Error: Error creating Private Link Service "example-privatelink" (Resource Group "example-resources"): network.PrivateLinkServicesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidNumberOfPrivateLinkServiceLoadBalancerFrontendIpConfigurationsSpecified" Message="Cannot have more than one load balancer frontend IP configuration on the private link service. Private link service example-privatelink has 2 load balancer frontend IP configurations specified." Details=[]
```

### Steps to Reproduce

1. Create a azurerm_private_link_service with multiple frontend specified.

### Important Factoids

This appears to be expected behaviour per the Azure documentation.
The description of the "loadBalancerFrontIpConfigruations" is "An array of references to the load balancer IP configurations."

### References

* https://docs.microsoft.com/en-gb/rest/api/virtualnetwork/private-link-services/create-or-update#frontendipconfiguration

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
