### ISSUE TITLE
Azure Data Factory Linked Service not being deployed

### ISSUE THREAD

**Issue by NickBishop2112** [hashicorp/terraform-provider-azurerm#12282]
Terraform not creating an Azure SQLDatabase linked service from ADF.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

hashicorp/azurerm = "=2.63.0"

### Affected Resource(s)

azurerm_data_factory_linked_service_azure_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory_linked_service_azure_sql_database" "foobar_sql_database" {
  name                = "foobar-linked-service"    
  resource_group_name = data.azurerm_resource_group.foobar.name
  data_factory_name   = azurerm_data_factory.foobar.name

  key_vault_connection_string {
      linked_service_name = azurerm_data_factory_linked_service_key_vault.key_vault.name
      secret_name = "ConnectionStrings--AdfConnection"
  }
}.
```

### Debug Output

Nonw

### Expected Behaviour

Azure SQL Linked service should be created in ADF.

### Actual Behaviour

Azure SQL Linked service was not created in ADF.

### Steps to Reproduce

Delete the linked service from within ADF and run the Terraform deploy (init, validate, generate plan and build) to re-create the linked service. The generate plan did not pick up the change. The linked service was not re-created.

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
