### ISSUE TITLE
Optional Variable called "availability_zone" under "frontend_ip_configuration" for the resource "azurerm_lb" is actually a Required variable now

### ISSUE THREAD

**Issue by binoyjt** [hashicorp/terraform-provider-azurerm#12286]
Under the resource "azurerm_lb" the "frontend_ip_configuration" has an optional setting. This setting is the Availability Zone. Terraform Fails if this Setting is not passed. For a LB with no AV Zone we need to pass a value called as "No-Zone" so that the apply is successful.

**Comment by WodansSon** [comment]
@binoyjt Thanks for opening this issue. I believe this issue has been fixed in #12208

**Comment by binoyjt** [comment]
Can the document be updated as this is a required variable and needs to be set at "No Zone" for regions with no AV Zones. Otherwise it fails.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
