### ISSUE TITLE
Support for output of network interface id or name created by private endpoint

### ISSUE THREAD

**Issue by Roshick** [hashicorp/terraform-provider-azurerm#12283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Creating a Private Endpoint will implicitly create a Network Interface, which is mostly managed by the Private Endpoint and shares its Lifecycle. Network Interfaces allow configuration of Diagnostic Settings to fetch metrics, which can be configured within the Portal, but there seems to be currently no way to access the Network Interface that is created by the Private Endpoint in order to configure its Diagnostic Settings, making it impossible to get any metrics. Outputting the id or name of this Network Interface should alleviate the problem, making it possible to use it as input for the azurerm_monitor_diagnostic_setting resource.

### New or Affected Resource(s)

azurerm_private_endpoint

**Comment by Pwd9000-ML** [comment]
Yes, please do add this so we can configure the NIC as an output!
I am facing the same dilemma where I need to set the diagnostics up on the NICs, but there is of course no way for determine what the NIC id will be as there is no related attribute exported by the resource!

**Comment by owenfarrell** [comment]
@Roshick - I took a crack at addressing this issue as part of #13421. The implementation specifically exports the ID and the name of the network interface.

* Exporting the ID would address the use case you identified above, and enable you to create a `azurerm_monitor_diagnostic_setting` resource.
* Exporting the name (in conjunction with the `resource_group` attribute of the endpoint), would enable you to get more details on the network interface itself by feeding it in to a [`azurerm_network_interface`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/network_interface) data source. This way, we avoid duplicating the implementation of API calls associated with pulling NIC details.

Thoughts welcome.

**Comment by Roshick** [comment]
That's awesome! Funnily enough I was looking into the code just a few hours ago and wanted to give it a try when I'm back from holidays. Your solution looks way better than the one I was thinking about (just adding the network_interface_id instead of a block to the resourcedata). Imho this should work just fine! :)

**Comment by owenfarrell** [comment]
> the one I was thinking about (just adding the network_interface_id instead of a block to the resourcedata)

Honestly, I thought through that. And I was internally conflicted on how to handle.

- The status quo is to use blocks for these kinds of scenarios. And technically speaking, when you look up a private endpoint via the API, you get a _**collection**_ of network interfaces back. So pushing the ID and name of the network interface in to a block seems right on face value.
- But the current implementation assumes the first element is the only one that matters. And I do wonder about the impacts of making this a block on how you would actually code this up (i.e., is it _**too**_ dynamic to make it useful?). So maybe a `network_interface_id` and `network_interface_name` attribute at the top-level of the schema would make more sense.

**Comment by Roshick** [comment]
Iirc I came across multiple instances where a block is exported while only a single subresource is to be expected within the provider (especially concerning network resources). I don't think a private endpoint will be backed by multiple NICs in the future (if that even makes sense?), but if it would, there would be no breaking change to this solution. The drawback is as far as I can see only a bit more bloat when accessing the values.

**Comment by owenfarrell** [comment]
I tested a local build of this yesterday and everything worked as expected. Like you, I've also come across "single subresource" scenarios, specifically when it comes to managed identities.

So, to your point, the one-to-many scenario doesn't make a lot of sense and there is a little bloat (I always feel a bit dirty when I hard-code magic numbers... even `0`). But based on my local tests, I think this will work pretty well.
