### ISSUE TITLE
Add support for Customer Managed Keys for notebooks in the Azure Databricks resource

### ISSUE THREAD

**Issue by alexott** [hashicorp/terraform-provider-azurerm#12302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently, Databricks has added support for [customer managed keys (CMK) for managed services](https://docs.microsoft.com/en-us/azure/databricks/security/keys/customer-managed-key-managed-services-azure) (notebooks, etc.).  This functionality complements the CMK for DBFS Root for which there is already another issue: #9785

The ability to encrypt data with customer's keys is a requirement for many big customers of Azure Databricks.

### New or Affected Resource(s)

* `azurerm_databricks_workspace`

### Potential Terraform Configuration

```hcl
custom_parameters {
  cmk_managed_services {
    key_vault_id = azurerm_key_vault.example.id
    key_id = azurerm_key_vault_key.example.id
    key_version = azurerm_key_vault_key.example.version
  }
}
```

### References
* https://docs.microsoft.com/en-us/azure/databricks/security/keys/customer-managed-key-managed-services-azure
* https://docs.microsoft.com/en-us/azure/databricks/security/keys/customer-managed-keys-dbfs/
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/9785

**Comment by WodansSon** [comment]
This was fixed in #12331

**Comment by alexott** [comment]
Thank you!

**Comment by alexott** [comment]
@WodansSon I've looked onto changes, but as I see it doesn't cover this specific issue. CMK for notebooks is a separate piece from DBFS root encryption, and exists only in pre-release version of API, not in the 2018-04-01.  It allows to specify a separate key for notebooks & another for DBFS root.

Can you please re-open this issue.

thank you

**Comment by favoretti** [comment]
Re-opening as requested. @WodansSon can you please have a look? Thank you!

**Comment by alexott** [comment]
it's supported now
