### ISSUE TITLE
Intermittent AzureRm crash on tf apply with keyvault policy

### ISSUE THREAD

**Issue by drummer425** [hashicorp/terraform-provider-azurerm#12304]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.14.3
AzureRM: 2.63.0

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
https://www.dropbox.com/s/1d7kxkej3uu0xlr/terraform.zip?dl=0
```

### Debug Output

https://gist.github.com/drummer425/8f13afeb55ce20edbfa871320fdcd012

### Expected Behaviour

Should have successfully applied changes, upgrading one scale set to a new image, and made no changes to the access policies for the keyvault. 

### Actual Behaviour

It crashed while reading or attempting to change the access policy on the keyvault's certificates. I don't know why. Those policies didn't change. Nothing for the keyvault changed. This error seems to happen intermittently and I'm not sure what differences cause it to crash or not. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Typical setup.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
