### ISSUE TITLE
azurerm_storage_table_entity can't handle 404s from when an entity is deleted

### ISSUE THREAD

**Issue by jaxidian** [hashicorp/terraform-provider-azurerm#12326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
azurerm v2.63.0

### Affected Resource(s)

* `azurerm_storage_table_entity`

### Terraform Configuration Files

This is reproducible using the sample code at: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_table_entity

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azureexample"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "azureexamplestorage1"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_table" "example" {
  name                 = "myexampletable"
  storage_account_name = azurerm_storage_account.example.name
}

resource "azurerm_storage_table_entity" "example" {
  storage_account_name = azurerm_storage_account.example.name
  table_name           = azurerm_storage_table.example.name

  partition_key = "examplepartition"
  row_key       = "examplerow"

  entity = {
    example = "example"
  }
}
```

### Expected Behaviour

It should detect that the Entity does not exist when running `terraform plan` or `terraform apply` and offer to create the missing resource. This expected behavior would be consistent with most resources being manually deleted. The underlying HTTP status codes of 404 are returned specifically to communicate that the resource does not exist.

### Actual Behaviour

The 404s cause the `terraform plan` to fail. The only way to get rid of the error is to do a `terraform state rm module.SharedState.azurerm_storage_table_entity.example` from the CLI.

### Steps to Reproduce

1. `terraform apply`
2. Using the Azure Storage Explorer (or anything else), delete the record from the table
3. `terraform apply` <--- note the error here

### Important Factoids

There is nothing special about the HCL attached. Any table with a record in it will serve for your repro case.

### References

I could find no information referencing this problem.

**Comment by jaxidian** [comment]
I have confirmed that azurerm v2.64.0 also fails.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
