### ISSUE TITLE
Support for allow_vnet_to_vnet_traffic property on azurerm_virtual_wan

### ISSUE THREAD

**Issue by laughtonsm** [hashicorp/terraform-provider-azurerm#12322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support the use of the `allowVnetToVnetTraffic` property for `azurerm_virtual_wan` resource

### New or Affected Resource(s)

* azurerm_virtual_wan

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_wan" "main" {
  name                              = "my-virtual-wan"
  resource_group_name               = "my-resource-group"
  location                          = "uksouth"
  disable_vpn_encryption            = false
  allow_branch_to_branch_traffic    = false
  allow_vnet_to_vnet_traffic        = true
  office365_local_breakout_category = "None"
  tags                              =  {
    "myTag" = "myValue"
}
```

**Comment by atombrella** [comment]
It's there, although not documented, and it's in ongoing deprecation phase. You can't actively set it, as it's overridden in the read-function (always sets it to `false`). 

```
			// TODO 3.0: remove this property
			"allow_vnet_to_vnet_traffic": {
				Type:       pluginsdk.TypeBool,
				Optional:   true,
				Default:    false,
				Deprecated: "this property has been removed from the API and will be removed in version 3.0 of the provider",
			},
```

**Comment by tombuildsstuff** [comment]
Closing this out since as @atombrella has mentioned this property is deprecated and no longer supported by the Azure API - so will be removed in v3.0 of the Azure Provider.
