### ISSUE TITLE
Support for specifying data types on entity properties for azurerm_storage_table_entity

### ISSUE THREAD

**Issue by jaxidian** [hashicorp/terraform-provider-azurerm#12337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, `azurerm_storage_table_entity` does not allow you to specify the types on entity properties (columns). As such, everything goes in as a string, even if the property on the map is coded as a number.

Going down the path of assuming the number type (which doesn't exist today) would be insufficient because it would be difficult/impossible to determine if the number should be an `Int32` or an `Int64` type. Additionally, HCL primitive types are insufficient to translate to the various types supported by Azure Storage Tables.

So I believe this feature request would require a pretty fundamental change to how this module currently functions, moving away from the simple and convenient KVP map implementation for the `entity` attribute and move to a more explicit (and verbose ☹️) implementation. However, I think this can be done in a way that preserves today's convenient format, as well.

### New or Affected Resource(s)

* `azurerm_storage_table_entity`

### Potential Terraform Configuration

This HCL (the entity has been tweaked from the samples in the official docs) shows the problem where the two numbers go in as strings:

```hcl
resource "azurerm_storage_table_entity" "example" {
  storage_account_name = azurerm_storage_account.example.name
  table_name           = azurerm_storage_table.example.name

  partition_key = "examplepartition"
  row_key       = "examplerow"

  entity = {
    exampleString = "example"
    exampleInt32 = 42
    exampleInt64 = 21474836470 # Int32.MaxValue = 2,147,483,647. I just added a zero to the end of this. Nothing special here.
  }
}
```

Below is the configuration format that I propose for the new implementation. I'm sure somebody smart could suggest something better, and that's fine. but this format would accomplish 3 things:

1. It would allow the module to easily have backwards-compatibility with all existing code, since the abbreviated format would continue to always assume string data types (it should, under the hood, map to the same code as the verbose string type)
2. It would support scenarios where I need to be explicit about the data types, even if I'm inserting 42 into an Int64.
3. It could scale to pretty much any/all data types that are currently supported or could later be supported in Azure Storage Tables. (Sure, some parsing rules would have to be used to manage certain things, but since we're starting from a clean slate here, make some good decisions and document them well!)

```hcl
resource "azurerm_storage_table_entity" "example" {
  storage_account_name = azurerm_storage_account.example.name
  table_name           = azurerm_storage_table.example.name

  partition_key = "examplepartition"
  row_key       = "examplerow"

  entity = {
    exampleString = "example" # To maintain compatibility, keep string syntax the same as a shortcut (perhaps support the verbose version, too)
    exampleInt32 = {
      value = 42
      type = "Int32"
    }
    exampleInt64 = {
      value = 21474836470
      type = "Int64"
    }
  }
}
```

### References

There's been very little discussion on this topic. A couple StackOverflow questions and this one Issue, which was deflected to the community support forum (where it went unanswered). As such, I'm only linking the one issue, since the others provide almost no additional value for this request.

* #8194

**Comment by jaxidian** [comment]
Just as some additional information: I actually do have the ability to do some nasty things in order to manipulate this a bit. While this **does** get the data type to be set on the first run, it seems to break the ability to run the script again in the future. **This is not a valid work-around.** I'm just adding this as additional information describing the current behavior, in case this is useful information for a developer to implement this feature request.

The following configuration:

```hcl
resource "azurerm_storage_table_entity" "example" {
  storage_account_name = azurerm_storage_account.example.name
  table_name           = azurerm_storage_table.example.name

  partition_key = "examplepartition"
  row_key       = "examplerow"

  entity = {
    exampleString = "example"
    exampleInt32 = 42
    "exampleInt32@odata.type" = "Edm.Int32"
    exampleInt64 = 21474836470 # Int32.MaxValue = 2,147,483,647. I just added a zero to the end of this. Nothing special here.
  }
}
```

Results in the following plan:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_storage_table_entity.example will be updated in-place
  ~ resource "azurerm_storage_table_entity" "example" {
      ~ entity               = {
          + "exampleInt32@odata.type" = "Edm.Int32"
            # (3 unchanged elements hidden)
        }
        id                   = "https://xyz.table.core.windows.net/myexampletable(PartitionKey='examplepartition',RowKey='examplerow')"
        # (4 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

When you run `terraform apply`, it fails with the following error:

```
azurerm_storage_table_entity.example: Modifying... [id=https://xyz.table.core.windows.net/myexampletable(PartitionKey='examplepartition',RowKey='examplerow')]
╷
│ Error: Error setting `entity` for Entity (Partition Key "examplepartition" / Row Key "examplerow") (Table "myexampletable" / Storage Account "xyz" / Resource Group "rg-tfrepro-entitydatatypes"): entity.exampleInt32: '' expected type 'string', got unconvertible type 'float64'
│
│   with azurerm_storage_table_entity.example,
│   on main.tf line 26, in resource "azurerm_storage_table_entity" "example":
│   26: resource "azurerm_storage_table_entity" "example" {
│
```

But when viewing the data now in Azure Storage Explorer, you can tell that the data type was successfully set:

![image](https://user-images.githubusercontent.com/260128/123147216-c6916900-d42c-11eb-8491-df637d406bdf.png)

And of course, forever on, the HCL will fail any `terraform plan` or `terraform apply` commands until I go do a `terraform state rm xxx` to remove that entity from the state.

**Comment by Amier3** [comment]
This should be fixed with the addition of https://github.com/hashicorp/terraform-provider-azurerm/pull/15782 , big thanks to the community on getting this fixed 😄
