### ISSUE TITLE
ip_restriction not working for Azure function app 

### ISSUE THREAD

**Issue by arunprasathv** [hashicorp/terraform-provider-azurerm#12339]
azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.61.0"
    }

Terraform  v1.0.0

site_config {
   ip_restriction {
  action="Allow"
  priority=1
  name= "allowonlyapim"
  virtual_network_subnet_id="vnetgateway/subnet"
}
}
# Error
│ Inappropriate value for attribute "ip_restriction": element 0: attributes "headers", "ip_address", and "service_tag" are required.

then if  I give the values as requested , I get error when I do apply

error expanding `site_config` for Function App "funcnam" (Resource Group "RG"): only one of `ip_address`, `service_tag` or `virtual_network_subnet_id` can be set for an IP restriction

Expected Behavior
without these optional params it should work

**Comment by kohei3110** [comment]
I'd like to pick this one.

**Comment by DanielSSilva** [comment]
This is happening to any combination of ip_address, service_tag, and virtual_network_subnet_id.
The documentation states that all of them are optional, but it also has a note saying that 

> One of either ip_address, service_tag or virtual_network_subnet_id must be specified

But the terraform actually expects everything to be populated, and without the defaults/empty.

I have 2 restrictions, one by ip_address and one by service tag. In both cases, it says that all the parameters are required. Even if I set them to defaults (as they are represented on the terraform plan output), it says that it wasn't expected to be empty

Here's the code 

``` terraform
ip_restriction = [
      {
        name        = "APIM"
        action      = "Allow"
        ip_address  = "xx.xx.xxx.xx/32"
        priority    = 1
        headers     = []
        service_tag               = ""
        virtual_network_subnet_id = ""
      },
      {
        name        = "ai-availability"
        action      = "Allow"
        priority    = 2
        service_tag = "ApplicationInsightsAvailability"
        headers     = []
        ip_address  = ""
        virtual_network_subnet_id = ""
      }
    ]
```
and here's the output

``` bash
Error: expected "site_config.0.ip_restriction.0.service_tag" to not be an 
empty string, got
│
│   with azurerm_function_app.linux,
│   on main.tf line 132, in resource "azurerm_function_app" "linux":        
│  132: resource "azurerm_function_app" "linux" {
│
╵
╷
│ Error: expected "site_config.0.ip_restriction.0.virtual_network_subnet_id" to not be an empty string, got
│
│   with azurerm_function_app.linux,
│   on main.tf line 132, in resource "azurerm_function_app" "linux":        
│  132: resource "azurerm_function_app" "linux" {
│
╵
╷
│ Error: expected "site_config.0.ip_restriction.1.ip_address" to not be an empty string, got
│
│   with azurerm_function_app.linux,
│   on main.tf line 132, in resource "azurerm_function_app" "linux":        
│  132: resource "azurerm_function_app" "linux" {
│
╵
╷
│ Error: expected "site_config.0.ip_restriction.1.virtual_network_subnet_id" to not be an empty string, got
│
│   with azurerm_function_app.linux,
│   on main.tf line 132, in resource "azurerm_function_app" "linux":        
│  132: resource "azurerm_function_app" "linux" {
 ```

And here's the output of the terraform plan (when it detects that I've changed things outside the terraform)
``` bash
 ~ site_config {
          ~ ip_restriction              = [
              - {
                  - action                    = "Allow"
                  - headers                   = []
                  - ip_address                = "xx.xx.xxx.xx/32"
                  - name                      = "APIM"
                  - priority                  = 1
                  - service_tag               = ""
                  - virtual_network_subnet_id = ""
                },
              - {
                  - action                    = "Allow"
                  - headers                   = []
                  - ip_address                = ""
                  - name                      = "ai-availability"
                  - priority                  = 2
                  - service_tag               = "ApplicationInsightsAvailability"
                  - virtual_network_subnet_id = ""
                },
            ]
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
