### ISSUE TITLE
Synapse Workspace "sql_administrator_login" Name Validation Issue

### ISSUE THREAD

**Issue by olivergaudreault** [hashicorp/terraform-provider-azurerm#12355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For Synapse "sql_administrator_login" rules should be the following but Terraform isn't validating on that. Through the Azure Portal I can put a login with dashes but not through Terraform.

- must not start with numbers or symbols
- between 1 and 128 characters long
- must not include non-alphanumeric characters
- must not contain a sql identifier or typical system name....

I am getting the following error
Error: sql_administrator_login can contain only letters or numbers, must start with a letter, The value must be between 1 and 128 characters long

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0

### Affected Resource(s)

* azurerm_synapse_workspace

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behaviour

I should have been able to Terraform Synapse with a dash in the login name.

### Actual Behaviour

Error that it isn't possible due to validation rules

### Steps to Reproduce

1. Create a Synapse workspace with a sql admin login that has a dash in the name

### Important Factoids

N/A

### References

N/A

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
