### ISSUE TITLE
Can't delete static site via terraform

### ISSUE THREAD

**Issue by timja** [hashicorp/terraform-provider-azurerm#12352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.58.0 (I'm actually running a custom build...)
+ provider registry.terraform.io/hashicorp/template v2.2.0

```

### Affected Resource(s)

* `azurerm_static_site`

### Terraform Configuration Files

```hcl
resource "azurerm_static_site" "static_webapp" {
  for_each = {
    // TODO add jui and fact redirect in prod to ignore list, not done now to avoid conflicts
    for frontend in var.shutter_apps : frontend.name => frontend
  }

  name                = each.value.name
  resource_group_name = data.azurerm_resource_group.shutter.name
  location            = "westeurope"
  tags                = var.common_tags // be wary of changes to tags: https://github.com/terraform-providers/terraform-provider-azurerm/issues/11986
}
```

### Expected Behaviour

Static site is deleted

### Actual Behaviour

Static site is not deleted but it's removed from the state file

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

I think the API says succeeded before it's deleted. I was able to delete one of static sites out of 6, in the activity log it still says deleting, but it's been ~30 minutes.

The portal is able to delete it quickly, it appears to use an ARM call though:

```
{"requests":[{"httpMethod":"DELETE","name":"024cc82e-bf2e-4964-abce-153385dd002f","requestHeaderDetails":{"commandName":"WebsitesExtension.DeleteStaticSite"},"url":"https://management.azure.com/subscriptions/sub-id/resourceGroups/shutter-app-sbox-rg/providers/Microsoft.Web/staticSites/site?api-version=2019-12-01-preview"}]}
```

API call made by SDK
```
az rest --verbose --method DELETE --uri "/subscriptions/sub-id/resourceGroups/shutter-app-sbox-rg/providers/Microsoft.Web/staticSites/webapp?api-version=2020-12-01"
```

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
