### ISSUE TITLE
Sql-server failover resource created in v2.32.0 fails in planning with "Error: ID contained more segments than required" on v2.39.0 and above

### ISSUE THREAD

**Issue by CarlosQualisflow** [hashicorp/terraform-provider-azurerm#12351]
Community Note

    Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
    Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
    If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform (and AzureRM Provider) Version

Terraform v0.14.0
on windows_amd64
  + AzureRM Provider Version: 2.32.0 - 2.39.0+

Affected Resource(s)

    "azurerm_sql_server" "sql-server-failover"

Terraform Configuration Files

    locals {  
    failover_server_name = "${var.server_name}-failover"
    }

    
    resource "azurerm_sql_server" "sql-server-failover" {  
    count                        = var.has_failover ? 1 : 0  
    name                         = local.failover_server_name  
    resource_group_name          = var.resource_group_name  
    location                     = var.failover_location  
    version                      = "12.0"
  
    lifecycle {    
    ignore_changes = [administrator_login_password, identity]  
    }

  
    tags = {    
    Environment = var.env  
    }
    }

Debug Output

Error: ID contained more segments than required: "/subscriptions/xxxxxxxxxxx/resourceGroups/rg-sql-prod/providers/Microsoft.Sql/servers/xxxxxxxx/databases/\<databasename\>", map[databases:\<databasename\>]
Expected Behaviour

No issues on plan or apply operation  

Actual Behaviour  
Error in Debug Output stops planning and application
Highest tested provider which still worked was v2.38.0
The issue persisted while using both powershell and cmd to execute

Steps to Reproduce

    terraform apply creating the failover using v2.32.0
    terraform plan using v2.39.0 or above

**Comment by Nick-Lucas** [comment]
@katbyte @tombuildsstuff (apologies if I tag the wrong people, I'm going off activity)

I'm from the same organisation as @CarlosQualisflow and we're still struggling with this while trying to upgrade above 2.38.0. Today trying with azurerm 2.77.0 and terraform 1.0.7 and still facing the problem with our failover databases.

Is there anything we can do to provide more information and work toward a resolution?

The issue also occurs when running `terraform refresh` which implies it's a problem reading the state in production, but the best I can understand from reading azurerm code is the final segment `databases/{db-name}` is not expected by the parsing, although it's seemingly correctly there.

**Comment by aristosvo** [comment]
Hi @Nick-Lucas! This issue is around the ID which contains to many elements. It is hard to debug this from a distance, especially as it is unknown what happened here between creation and now. Can you reproduce this in a simple reproduction scenario?

I'd `terraform state rm` and `terraform import` this resource based on a valid id (`/subscriptions/x-x-x/resourceGroups/rg-sql-prod/providers/Microsoft.Sql/servers/org-prod-tags-failover`) without the last segment or adjust your state.

If you are able to replay this problem from creation of a new resource I'd be happy to help, until then I'll close this issue.

**Comment by CarlosQualisflow** [comment]
Thank you for this.
The issue was resolved by re-importing the resource.
We are unclear on what caused it since other sql failover resources worked fine.
