### ISSUE TITLE
azurerm_media_services Does not set the system up correctly Requires the account to be created before setting it as MI

### ISSUE THREAD

**Issue by mxrss2** [hashicorp/terraform-provider-azurerm#12358]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.31

```
├── provider.azuread ~> 0.11
├── provider.azuredevops ~> 0.0.1
├── provider.azurerm ~> 2.64.0
├── provider.azurerm.hub
├── provider.azurerm.sb
├── provider.helm ~> 1.3.2
```

Your version of Terraform is out of date! The latest version
is 1.0.1. You can update by downloading from https://www.terraform.io/downloads.html`
### Affected Resource(s)

* `azurerm_media_services_account`

### Terraform Configuration Files

```hcl
resource "azurerm_media_services_account" "media" {
  name                = local.name
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name

  storage_account {
    id         = module.pr_storage.id
    is_primary = true
  }

   storage_account {
    id         = module.sec_storage.id
    is_primary = false
  }

  storage_authentication_type = "ManagedIdentity"

  identity {
   type = "SystemAssigned" 
  }
  
  tags = local.tags
}
```

### Expected Behaviour

Should create storage account and set the managed ideneity to authenticate to the secondary and primary accounts. 

### Actual Behaviour

azurerm_media_services_account.media: Creating...
azurerm_media_services_account.media: Still creating... [10s elapsed]

Error: creating Media Service: (Name "mediadamsbx829c" / Resource Group "rg-dam-sbx-002"): media.MediaservicesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The storage authentication property cannot be set to ManagedIdentity before the Managed Identity has been created for the media account." Details=[{"code":"StorageManagedIdentityAuthenticationRequiresManagedIdentity","message":"The storage authentication property cannot be set to ManagedIdentity before the Managed Identity has been created for the media account."}]

  on main.tf line 84, in resource "azurerm_media_services_account" "media":
  84: resource "azurerm_media_services_account" "media" {

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jcanizalez** [comment]
hey  I think this issue is duplicated with #11296

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
