### ISSUE TITLE
Azure cosmosdb continuous backup issue

### ISSUE THREAD

**Issue by giridharaprasadh** [hashicorp/terraform-provider-azurerm#12371]
Hi Team,

I am trying to deploy Azure cosmosdb(mongo) with continuous backup and when i deploy getting below error,

"Blocks of type "backup" are not expected here."
ref: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#backup
![image](https://user-images.githubusercontent.com/86479995/123436328-241fe400-d5ec-11eb-8473-cda912709b68.png)

please provide the sample Terraform file for cosmos db with continuous backup or please correct me.

Terraform file:

# CosmosDB
resource "azurerm_cosmosdb_account" "database" {
  name = "demo-${azurerm_resource_group.rg.location}-${var.env}"
  location = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type = "Standard"
  kind = "MongoDB"

  lifecycle {
    ignore_changes = [capabilities]
    prevent_destroy = true
  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level = "Session"
  }

  geo_location {
    failover_priority = 0
    location = var.cosmos_replication_location != "" ? var.cosmos_replication_location : azurerm_resource_group.rg.location
  }  
  
   backup {
    type = "Continuous"
  }
}

resource "azurerm_cosmosdb_mongo_database" "methodology" {
  account_name = azurerm_cosmosdb_account.database.name
  name = "demo-methodology-${azurerm_resource_group.rg.location}-${var.env}"
  resource_group_name = azurerm_resource_group.rg.name

  autoscale_settings {
    max_throughput = var.cosmos_autoscaling_max_throughput
  }
}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by jrstreng** [comment]
Verify the version of provider you are using.
the backup property was introduced in azurerm 2.59.0

**Comment by catriona-m** [comment]
Thanks for opening this issue @giridharaprasadh. I have tested this on the latest version of AzureRM Provider and this now appears to be working as expected, so I will now close this issue. However, please feel free to reopen this if you are still experience this issue again. Thanks!
