### ISSUE TITLE
backend_address_pool dont have options to add VMs

### ISSUE THREAD

**Issue by Ajith0888** [hashicorp/terraform-provider-azurerm#12380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

After create Azure App Gw no options to add to Virtual Machines when we do manually its present but in TF its not there. 

### Terraform (and AzureRM Provider) Version

$ terraform.exe -v
Terraform v1.0.0
on windows_amd64

Your version of Terraform is out of date! The latest version
is 1.0.1. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_XXXXX`

azurerm_application_gateway 

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by w3bward** [comment]
You can create a relationship between a backend address pool and a VM (more specifically a NIC on a VM) using the [azurerm_network_interface_application_gateway_backend_address_pool_association](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_interface_application_gateway_backend_address_pool_association) resource.

**Comment by Ajith0888** [comment]
Thank you for point it out.
