### ISSUE TITLE
import of ressource azurerm_web_application_firewall_policy incomplete

### ISSUE THREAD

**Issue by marcusfriede** [hashicorp/terraform-provider-azurerm#12390]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform version 1.0.0
azurerm version 2.64.0

### Affected Resource(s)

* azurerm_web_application_firewall_policy

### Expected Behaviour
When importing that ressource i want to import all settings like the below values:

    {
      "module": "module.applicationGW",
      "mode": "managed",
      "type": "azurerm_web_application_firewall_policy",
      "name": "policy",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "custom_rules": [
              {
                "action": "Block",
                "match_conditions": [
                  {
                    "match_values": [
                      "DE",
                      "BE",
                      "NL",
                      "CH",
                      "LU",
                      "FR",
                      "IT",
                      "FI",
                      "DK",
                      "AT",
                      "GB",
                      "ES",
                      "PT",
                      "SE",
                      "NO",
                      "PL",
                      "CZ",
                      "HU",
                      "SI",
                      "GR",
                      "BG",
                      "EE",
                      "HR",
                      "IE",
                      "LV",
                      "LT",
                      "MT",
                      "RO",
                      "SK",
                      "CY"
                    ],
                    "match_variables": [
                      {
                        "selector": "",
                        "variable_name": "RemoteAddr"
                      }
                    ],
                    "negation_condition": true,
                    "operator": "GeoMatch",
                    "transforms": []
                  }
                ],
                "name": "ForbiddenCountries",
                "priority": 90,
                "rule_type": "MatchRule"
              }
            ],
            "http_listener_ids": [
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-prod-http",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-test-http",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-prod-https",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-test-https",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-www-shop-prod-http",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-www-shop-prod-https",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-group-prod-http",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-group-test-http",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-www-shop-group-prod-http",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-group-prod-https",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-shop-group-test-https",
              "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGateways/appgw-central/httpListeners/appgwlisten-www-shop-group-prod-https"
            ],
            "id": "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/appgwfwpol-central",
            "location": "westeurope",
            "managed_rules": [
              {
                "exclusion": [],
                "managed_rule_set": [
                  {
                    "rule_group_override": [
                      {
                        "disabled_rules": [
                          "942180",
                          "942260",
                          "942340",
                          "942200",
                          "942430",
                          "942370",
                          "942130"
                        ],
                        "rule_group_name": "REQUEST-942-APPLICATION-ATTACK-SQLI"
                      },
                      {
                        "disabled_rules": [
                          "920230",
                          "920300",
                          "920320"
                        ],
                        "rule_group_name": "REQUEST-920-PROTOCOL-ENFORCEMENT"
                      }
                    ],
                    "type": "OWASP",
                    "version": "3.1"
                  }
                ]
              }
            ],
            "name": "appgwfwpol-central",
            "path_based_rule_ids": [],
            "policy_settings": [
              {
                "enabled": true,
                "file_upload_limit_in_mb": 100,
                "max_request_body_size_in_kb": 128,
                "mode": "Prevention",
                "request_body_check": false
              }
            ],
            "resource_group_name": "rg-appgw",
            "tags": {},
            "timeouts": null
          },
          "sensitive_attributes": [],
          "dependencies": [
            "azurerm_resource_group.rgAppGw"
          ]
        }
      ]
    },

### Actual Behaviour

Actually i am missing many values like the above of azurerm_web_application_firewall_policy.
I only get this ones:

{
  "module": "module.applicationGW",
  "mode": "managed",
  "type": "azurerm_web_application_firewall_policy",
  "name": "policy",
  "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
  "instances": [
	{
	  "index_key": "central",
	  "schema_version": 0,
	  "attributes": {
		"custom_rules": [],
		"http_listener_ids": null,
		"id": "/subscriptions/xxx/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/appgwfwpol-central",
		"location": "westeurope",
		"managed_rules": [],
		"name": "appgwfwpol-central",
		"path_based_rule_ids": null,
		"policy_settings": [],
		"resource_group_name": "rg-appgw",
		"tags": {},
		"timeouts": {
		  "create": null,
		  "delete": null,
		  "read": null,
		  "update": null
		}
	  },
	  "sensitive_attributes": [],
	  "private": "xyz"
	}
  ]    
},

### Steps to Reproduce

1. `terraform import -var-file=xyz.tfvars "module.applicationGW.azurerm_web_application_firewall_policy.policy[\"central\"]" "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/applicationGatewayWebApplicationFirewallPolicies/appgwfwpol-central"`

### References

* #0000

**Comment by alexandergood** [comment]
Hi @marcusfriede, I came across this issue today as well and I managed to work out the solution.

I am guessing that you, like I did, fetched the id from the url to the resource which has `applicationGatewayWebApplicationFirewallPolicies`, the code and [the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy#import) expect `ApplicationGatewayWebApplicationFirewallPolicies`, note the lowercase `a` at the beginning. 

So your import should be as below.

```
terraform import -var-file=xyz.tfvars "module.applicationGW.azurerm_web_application_firewall_policy.policy[\"central\"]" "/subscriptions/xyz/resourceGroups/rg-appgw/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/appgwfwpol-central"
```

The main issue is that there appears to be no validation on the id of the `azurerm_web_application_firewall_policy` resource when it is imported, see the link below.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/bfa0c53e7888e1e466f79c9f5837b177be459b9c/azurerm/internal/services/network/web_application_firewall_policy_resource.go#L28

Either the validation needs to be completed or (I am guessing, I haven't gone too deep) in the line linked below, `ApplicationGatewayWebApplicationFirewallPolicies` should be changed to `applicationGatewayWebApplicationFirewallPolicies` to make it consistent with the url, this seems to be the case for most resources.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/ef610f2ca81698680349ee75ea95c4637c25f7e4/azurerm/internal/services/network/parse/application_gateway_web_application_firewall_policy.go#L36

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
