### ISSUE TITLE
azurerm_lb always shows addition of private_ip_address_version = Ip_v4 whenever running a plan

### ISSUE THREAD

**Issue by Alex-W1** [hashicorp/terraform-provider-azurerm#12396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When running a terraform plan for my environment, a new value for private_ip_address_version = "IPv4" is added to all instances of azurerm_lb resources frontend_ip_configuration.

While troubleshooting the issue, discovered that running a plan using the 2.63.0 version of the azurerm provider, there are 22 instances of the '+ private_ip_address_version = "IPv4"' addition, but with the 2.64.0 version there are 17.

Comparing the two plans, any azure_lb resources that have multiple frontend_ip_configuration blocks defined are appearing in 2.63.0 but NOT 2.64.0,

Any azure_lb resources that have a single frontend_ip_configuration block defined still show up with the addition.

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.5 (also occurring in 1.0.0)
AzureRM provider: 2.65.0
```

### Affected Resource(s)

* `azurerm_lb`

### Terraform Configuration Files
(Below addition always appears including in 2.63.0, 2.64.0 and 2.65.0)

```
resource "azurerm_lb" "x1" {
        id                   = "/subscriptions/xxxxxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Network/loadBalancers/zzzzzzzz"
        name                 = "zzzzzzzz"
        tags                 = {}
        # (4 unchanged attributes hidden)

      ~ frontend_ip_configuration {
            id                            = "/subscriptions/xxxxxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Network/loadBalancers/zzzzzzzz/frontendIPConfigurations/LoadBalancerFrontEnd"
            name                          = "LoadBalancerFrontEnd"
          + private_ip_address_version    = "IPv4"
            # (7 unchanged attributes hidden)
}
```
(Below will appear in 2.63.0 but not 2.64.0 NOR 2.65.0)
```
resource "azurerm_lb" "x" {
        id                   = "/subscriptions/xxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Network/loadBalancers/zzzzzzz"
        name                 = "zzzzzzz"
        tags                 = {}
        # (4 unchanged attributes hidden)

      ~ frontend_ip_configuration {
            id                            = "/subscriptions/xxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Network/loadBalancers/zzzzzzz/frontendIPConfigurations/LoadBalancerFrontEnd"
            name                          = "LoadBalancerFrontEnd"
          + private_ip_address_version    = "IPv4"
            # (6 unchanged attributes hidden)
        }
      ~ frontend_ip_configuration {
            id                            = "/subscriptions/xxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Network/loadBalancers/zzzzzzz/frontendIPConfigurations/LoadBalancerFrontEnd-Server"
            name                          = "LoadBalancerFrontEnd-Server"
          + private_ip_address_version    = "IPv4"
            # (6 unchanged attributes hidden)
        }
      ~ frontend_ip_configuration {
            id                            = "/subscriptions/xxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Network/loadBalancers/zzzzzzz/frontendIPConfigurations/LoadBalancerFrontEnd-KpiServer"
            name                          = "LoadBalancerFrontEnd-KpiServer"
          + private_ip_address_version    = "IPv4"
            # (6 unchanged attributes hidden)
        }
    }
````

### Expected Behaviour

After applying changes, the value should no longer appear as a change.

### Actual Behaviour

Every instance of an azurerm_lb resource will have the following value added to its frontend_ip_configuration block if the block is **only defined once** in the azurerm_lb resource. Resources with multiple frontend_ip_configuration blocks **do not** get the addition. 

```
 + private_ip_address_version    = "IPv4"
```

### Steps to Reproduce

1. `terraform apply`

### References

Original issue reported here, seems to have been partially fixed in 2.64.

* #12166

**Comment by Alex-W1** [comment]
Checked with version 2.80 of the provider, it's still an issue made more complicated by the fact that if a dynamic block is used for the frontend_ip_configuration, the workaround mentioned in #12166 can't be used because the lifecycle meta-argument cannot accept dynamic values.

```
lifecycle { 
    ignore_changes = [ 
      frontend_ip_configuration[0].private_ip_address_version,
      frontend_ip_configuration[1].private_ip_address_version,     <---- This will fail if the front end is not defined for certain LBs
    ] 
  }
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
