### ISSUE TITLE
azurerm_monitor_activity_log_alert  fails with no supported API version

### ISSUE THREAD

**Issue by RussTech** [hashicorp/terraform-provider-azurerm#12407]
Terraform (and AzureRM Provider) Version
Terraform v1.0.0
azurerm provider version  2.55.0, 2.63.0, 2.65.0 

Affected Resource(s)
azurerm_monitor_activity_log_alert

Terraform Configuration Files
```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.65.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rsg" {
  name     = "test-rsg"
  location = "usgovvirginia"
}

resource "azurerm_monitor_action_group" "action_grp" {
  name                = "test-action-group"
  resource_group_name = azurerm_resource_group.rsg.name
  short_name          = "test-ag"

  email_receiver {
    name          = "supportcontact"
    email_address = "test@domain.com"
  }
}

resource "azurerm_monitor_activity_log_alert" "rsg_alert" {
  name                = "test-failed"
  resource_group_name = azurerm_resource_group.rsg.name
  scopes              = [ azurerm_resource_group.rsg.id ]
  description         = "This alert will monitor Failed Administrative events."

  criteria {
    status         = "Failed"
    category       = "Administrative"
  }

  action {
    action_group_id = azurerm_monitor_action_group.action_grp.id
  }
}
```

Debug Output

Expected Behavior

A new alert should be created (or an existing alert modified).  

Actual Behavior

Error: Error creating or updating activity log alert "test-failed" (resource group "test-rsg"): insights.ActivityLogAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'global' and API version '2020-10-01' for type 'activityLogAlerts'. The supported api-versions are '2017-03-01-preview, 2017-04-01'. The supported locations are 'global'."

Steps to Reproduce

Try to create a new Azure Monitor Activity Alert using Azure US Government (copy code above)

terraform apply

Important Factoids
Azure US Gov only has two supported API versions for this endpoint: 
2017-04-01
2017-03-01-preview

Azure has three supported APIs: 
2020-10-01
2017-04-01
2017-03-01-preview

I'm not sure, but it looks like monitor_activity_log_alert_resource.go is hardcoded to use 2020-10-01 ?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
