### ISSUE TITLE
azurerm_linux_virtual_machine - license_type cannot be unset

### ISSUE THREAD

**Issue by centiqchris** [hashicorp/terraform-provider-azurerm#12424]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
```
### Affected Resource(s)

* `azurerm_linux_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "egvm" {
  name                            = "name"
  computer_name                   = "hostname"
  resource_group_name             = "rg-name"
  location                        = "uksouth"
  size                            = "Standard_M32ls"
  admin_username                  = "azureuser"
  disable_password_authentication = true
  #license_type                    = "SUSE_BYOS" 
}
```

### Expected Behaviour

License type can be set to SUSE_BYOS, or left out entirely for PAYG subscription basis.  However, if setting is changed in portal or by other means, there is no means to return to PAYG subscriptions with the terraform config.

With no license type set in the code, but with SLES_BYOS set through the portal, terraform should revert back to PAYG terms

License_type needs validation altering to accept "None" as an option.

### Actual Behaviour

Terraform attempts to set it to null

```
  ~ resource "azurerm_linux_virtual_machine" "egvm" {
        id                              = "/subscriptions/xxx"
      - license_type                    = "SLES_BYOS" -> null
        name                            = "xxx"
    
```

This has no effect.  Repeated runs of apply give the same output.

If setting is reverted in portal, following occurs on apply

```
  ~ resource "azurerm_linux_virtual_machine" "egvm" {
        id                              = "/subscriptions/xxx"
      - license_type                    = "None" -> null
        name                            = "xxx"
```

It is not possible to set license_type to "None" in terraform - not an allowed value.  Terraform will attempt to make a change after every run from this point on.

### Steps to Reproduce

1. Create a SUSE Linux VM using `azurerm_linux_virtual_machine` resource
1. Change "Licensing" in "Configuration" in Azure Portal to "Would you like to use an existing SUSE subscription?" - Yes
2. Rerun `terraform apply` - it will attempt to set it back.
3. Rerun `terraform apply` - it will try again to set it back.

### References

* #0000

**Comment by Nitin052** [comment]
Hi @katbyte  I have done with some changes with  code ,but not works ,it is giving same output as previous.
My changes in codes is-
```var licenseType string
	if props.LicenseType != nil {
		licenseType = *props.LicenseType
		if licenseType == "None" {
			licenseType = ""
		}
	}
	d.Set("license_type", licenseType)
So Please give me a some suggestion .

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
