### ISSUE TITLE
API Management versioned APIs are not modified when version is removed

### ISSUE THREAD

**Issue by Berbe** [hashicorp/terraform-provider-azurerm#12430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```console
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)

* `azurerm_api_management_api`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_version_set" "example" {
  name = "example"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name = "example"
  versioning_scheme = "Segment"
}

resource "azurerm_api_management_api" "example" {
  name = "example"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  display_name = "example"
  path = "example"
  revision = "1"
  protocols = [
    "https",
  ]
  service_url = "http://example.org"
  version_set_id = azurerm_api_management_api_version_set.example.id
  version = "1"

  import {
    content_format = "openapi+json"
    content_value = file("${path.module}/example.json")
  }
}
```

### Expected Behaviour

On removal of:
* `azurerm_api_management_api_version_set.example` object
* `version_set_id` directive from `azurerm_api_management_api.example`
* `version` directive from `azurerm_api_management_api.example`
all other things being equal.
`azurerm_api_management_api.example` shall have a change being detected from the state and be modified before `azurerm_api_management_api_version_set.example` is attemtped to be deleted.

### Actual Behaviour
On removal of:
* `azurerm_api_management_api_version_set.example` object
* `version_set_id` directive from `azurerm_api_management_api.example`
* `version` directive from `azurerm_api_management_api.example`
all other things being equal.
No change is detected on `azurerm_api_management_api.example` and `azurerm_api_management_api_version_set.example` is tryong to be deleted:
```console
Terraform will perform the following actions:

  # azurerm_api_management_api_version_set.example will be destroyed
  - resource "azurerm_api_management_api_version_set" "example" {
      - api_management_name = "example" -> null
      - display_name        = "example" -> null
      - id                  = "/subscriptions/***/resourceGroups/example/providers/Microsoft.ApiManagement/service/example/apiVersionSets/test" -> null
      - name                = "example" -> null
      - resource_group_name = "example" -> null
      - versioning_scheme   = "Segment" -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. Create a versioned `azurerm_api_management_api` object (`version_set_id` & `version` set) along with a `azurerm_api_management_api_version_set` object
Apply the changes so their state are recorded
2. Keep `azurerm_api_management_api` in Terraform configuration, but strip it from the `version_set_id` & `version` directives
Also remove `azurerm_api_management_api_version_set`
3. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
