### ISSUE TITLE
azurerm_storage_share refresh state fails 'with context deadline exceeded'

### ISSUE THREAD

**Issue by doherty100** [hashicorp/terraform-provider-azurerm#12447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_storage_share`
* `azurerm_private_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_share" "storage_share_01" {
  name                 = "fs-${random_id.random_id_storage_share_01_name.hex}-001"
  storage_account_name = azurerm_storage_account.storage_account_01.name
  quota                = var.storage_share_quota_gb
}

resource "azurerm_private_endpoint" "storage_account_01_private_endpoint_file" {
  name                = "pend-${random_id.random_id_storage_account_01_private_endpoint_file_name.hex}-001"
  resource_group_name = azurerm_resource_group.resource_group_01.name
  location            = azurerm_resource_group.resource_group_01.location
  subnet_id           = azurerm_subnet.vnet_shared_01_subnets["PrivateLink"].id
  tags                = var.tags

  private_service_connection {
    name                           = "azure_files"
    private_connection_resource_id = azurerm_storage_account.storage_account_01.id
    is_manual_connection           = false
    subresource_names              = ["file"]
  }
}
```

### Debug Output

https://gist.github.com/doherty100/a0efbf227f6bc93a488b8136a3ff6f93 

### Expected Behaviour

Terraform refresh should succeed.

### Actual Behaviour

│ Error: shares.Client#GetProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│
│   with azurerm_storage_share.storage_share_01,
│   on 40-storage.tf line 87, in resource "azurerm_storage_share" "storage_share_01":
│   87: resource "azurerm_storage_share" "storage_share_01" {
│
### Steps to Reproduce

1. `terraform apply`
2. `terraform refresh`

### Important Factoids

* Private endpoints are configured for Azure Files endpoints associated with this share. 
* This is new behavior, this same configuration worked with previous releases of azurerm provider.

### References

* [#10015](https://github.com/terraform-providers/terraform-provider-azurerm/issues/10015)

**Comment by tombuildsstuff** [comment]
This'll be fixed by #2977 - please subscribe to that issue for updates
