### ISSUE TITLE
Unable to Add Frontend to Front Door with Existing Frontends Due to Incorrect Ordering

### ISSUE THREAD

**Issue by timothymathison** [hashicorp/terraform-provider-azurerm#12445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.11
+ provider azurerm v2.65
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

**Module:**

```hcl
resource "azurerm_frontdoor" "fd" {
  name                                         = var.name
  resource_group_name                          = var.resource_group_name
  backend_pools_send_receive_timeout_seconds   = var.backend_pools_send_receive_timeout_seconds
  enforce_backend_pools_certificate_name_check = var.enforce_backend_pools_certificate_name_check

  frontend_endpoint {
    name                                    = var.default_frontend_endpoint.name
    host_name                               = format("%s.azurefd.net", var.name)
    web_application_firewall_policy_link_id = var.default_frontend_endpoint.web_application_firewall_policy_link_id
  }

  dynamic "frontend_endpoint" {
    for_each = var.frontend_endpoints

    content {
      name                                    = frontend_endpoint.value.name
      host_name                               = frontend_endpoint.value.host_name
      session_affinity_enabled                = frontend_endpoint.value.session_affinity_enabled
      web_application_firewall_policy_link_id = frontend_endpoint.value.web_application_firewall_policy_link_id
    }
  }
}
```

### Plan Partial Output

```
          ~ frontend_endpoint           = [
                {
                    host_name                               = "foo.azurefd.net"
                    id                                      = "<redacted>"
                    name                                    = "default"
                    session_affinity_enabled                = false
                    session_affinity_ttl_seconds            = 0
                    web_application_firewall_policy_link_id = "<redacted>"
                },
              ~ {
                  ~ host_name                               = "delta.a.domain.com" -> "beta.a.domain.com"
                  ~ name                                    = "delta-a" -> "beta-a"
                    # (4 unchanged elements hidden)
                },
              ~ {
                  ~ host_name                               = "delta.b.domain.com" -> "beta.b.domain.com"
                  ~ name                                    = "delta-b" -> "beta-b"
                    # (4 unchanged elements hidden)
                },
              + {
                  + host_name                               = "delta.a.domain.com"
                  + id                                      = null
                  + name                                    = "delta-a"
                  + session_affinity_enabled                = true
                  + session_affinity_ttl_seconds            = 0
                  + web_application_firewall_policy_link_id = "<redacted>"
                },
              + {
                  + host_name                               = "delta.b.domain.com"
                  + id                                      = null
                  + name                                    = "delta-b"
                  + session_affinity_enabled                = true
                  + session_affinity_ttl_seconds            = 0
                  + web_application_firewall_policy_link_id = "<redacted>"
                },
            ]
```

### Error Output

```
Error: creating Front Door "foo" (Resource Group "foundation-eastus2-foo"): frontdoor.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="Conflict" Message="We couldn't create your custom domain. Another custom domain with the same host name already exists."

  on .terraform/modules/fd/_modules/frontdoor/main.tf line 14, in resource "azurerm_frontdoor" "fd":
  14: resource "azurerm_frontdoor" "fd" {
```

### Expected Behaviour

Terraform should leave existing `frontend_endpoint`s un-changed and create the new endpoints.

### Actual Behaviour

Frontends `delta-a` and `delta-b` were previously created when the FrontDoor instance was originally created.

When adding `frontend_endpoint`s `beta-a` and `beta-b` Terraform attempts to update the existing `frontend_endpoint`s to `beta-a` and `beta-b` and then create `delta-a` and `delta-b` as new `frontend_endpoint`s.

My hypothesis is that it attempts to create the new `frontend_endpoint`s first and fails because the existing `frontend_endpoint`s already use the same domain(s).

It also re-orders the associated `routing_rule`s.

### Steps to Reproduce

1. Create/apply `azurerm_frontdoor` with two `frontend_endpoint`s to begin with.
2. Add 2 more `frontend_endpoint`s and attempt to run `plan` and `apply`.

### Important Factoids

None.

### References

I thought all the ordering issues were fixed after #11456. But it seems like there may still be un-resolved issues when adding new frontends.

**Comment by timothymathison** [comment]
It turns out that the re-ordering in the plan -- while annoying -- was not the cause of the error. The frontend domains I was trying to add were already associated with another Font Door instance, and Azure Front Door does not allow that.

**Comment by PrestonR** [comment]
I'm experiencing this same issue, and my new frontend endpoints do not exist anywhere else. I think the reordering is trying to reapply existing custom domains. But I'm unsure how to confirm this specifically.

**Comment by WodansSon** [comment]
The legacy Frontdoor resources are being retired and are no longer being developed.
