### ISSUE TITLE
azurerm_resource_group_template_deployment outputs evaluating before resource created

### ISSUE THREAD

**Issue by SamStenton** [hashicorp/terraform-provider-azurerm#12451]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v1.0.1
v2.66.0

### Affected Resource(s)

* `azurerm_resource_group_template_deployment`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "main" {
  name     = "some-rg"
  location = "uksouth"
}

resource "azurerm_resource_group_template_deployment" "main" {
  name                = "deployment-name"
  resource_group_name = azurerm_resource_group.main.name
  deployment_mode     = "Incremental"
  parameters_content  = jsonencode({
    "logic-app-name"  = {
      value = "logic-app-name"
    }
  })
  template_content = file("logicapp.json")
}
```

#### logicapp.json
```json
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "logic-app-name": {
            "type": "string"
        }
    },
    "variables": {},
    "resources": [
        {
            "type": "Microsoft.Logic/workflows",
            "apiVersion": "2017-07-01",
            "name": "[parameters('logic-app-name')]",
            "location": "uksouth",
            "identity": {
                "type": "SystemAssigned"
            },
            "properties": {
                "state": "Enabled",
                "definition": {
                    "$schema": "https://pluginsdk.management.azure.com/providers/Microsoft.Logic/schemas/2016-06-01/workflowdefinition.json#",
                    "contentVersion": "1.0.0.0",
                    "triggers": {},
                    "actions": {}
                },
                "parameters": {}
            }
        }
    ],
    "outputs": {
        "principalId": {
            "type": "string",
            "value": "[reference(concat(resourceId('Microsoft.Logic/workflows', parameters('logic-app-name')), '/providers/Microsoft.ManagedIdentity/Identities/default'), '2018-11-30').principalId]"
        }
    }
}
```

### Debug Output

https://gist.github.com/SamStenton/abb5a3707fd1f20fe9a44245ace0d74b

### Expected Behaviour

ARM template for logic app to deploy and output the SystemAssigned identity ID back to Terraform. 

_I'm having to use an ARM template for the logic app deployment as there is currently no way to create with an MSI (#2924)_ 

### Actual Behaviour

Running apply, the logic app is created in Azure however the TF output fails with a 'Not Found' from ARM ([line 301](https://gist.github.com/SamStenton/abb5a3707fd1f20fe9a44245ace0d74b#file-tf_log_azurerm_resource_group_template_deployment-L301)). This appears to be the reference to the Microsoft.Logic/workflows/logic-app-name in the outputs of the ARM template. Removing the output variable causes the deployment to succeed. 

Normally I would be opening this with Microsoft but interestingly running the ARM template directly using the AZ CLI works fine. It would appear that when using `azurerm_resource_group_template_deployment` the output attempts to evaluate before the resource is created. 

### Steps to Reproduce

1. `terraform apply`

Manual ARM deploy:

1. `az deployment group create --resource-group deployment1 --mode Incremental --parameters logic-app-name='logic-app-name' --template-file logicapp.json`

**Comment by sdebruyn** [comment]
@SamStenton Did you find a workaround on how to get the identity object ID back into Terraform?

**Comment by SamStenton** [comment]
@sdebruyn Not yet I'm afraid. Planned to get back to this in the next couple of weeks. Super frustrating!

**Comment by sdebruyn** [comment]
I found it, seems like it was just incorrect ARM syntax or something. This worked now:

```json
    "outputs": {
        "identityObjectId": {
            "type": "string",
            "value": "[reference(resourceId('Microsoft.Logic/workflows', parameters('laName')), '2016-06-01', 'Full').identity.principalId]"
        }
    }
```

**Comment by tombuildsstuff** [comment]
Closing this out since this was an ARM Template configuration issue, however support for Identities within Logic Apps are being tracked in #2924 (as mentioned above).
