### ISSUE TITLE
azurerm_mysql_server: Provider produced inconsistent result after apply (read-after-write eventual consistency?)

### ISSUE THREAD

**Issue by drjwelch** [hashicorp/terraform-provider-azurerm#12464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform v0.14.7
azurerm v2.66.0

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files

```
resource "azurerm_mysql_server" "myServer" {
  name                              = "myName"
  location                          = var.location
  resource_group_name               = azurerm_resource_group.myRG.name
  administrator_login               = var.username
  administrator_login_password      = var.password
  sku_name                          = "GP_Gen5_2"
  storage_mb                        = 5120
  version                           = "5.7"
  backup_retention_days             = 7
  ssl_enforcement_enabled           = true
  tags                              = var.tags
}
```

then, after successful apply, re-apply with changes that cause a destroy/create:

```
  storage_mb                        = 51200
  version                           = "8.0"
```

### Debug Output

```
Error: Provider produced inconsistent result after apply

When applying changes to azurerm_mysql_server.myServer, provider
"registry.terraform.io/hashicorp/azurerm" produced an unexpected new value:
Root resource was present, but now absent.
```

### Expected Behaviour

Existing server destroyed and new server created

### Actual Behaviour

Existing server destroyed and error output shown above
However new server _was_ in fact created

### Steps to Reproduce

1. `terraform apply` the resource above
2. Change to tier as above
3. `terraform apply` the changes

### Important Factoids

This error message appears in several linked issues and seems to be due to the situation described [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/9379#issuecomment-738959820)

In the above scenario running in ADO pipeline, the reason could be that the attempt to get the resource id after creation 404s resulting in the error seen (but I haven't been able to test this).

Re-running the pipeline fails because the resource now exists but is not present in the state.

Workaround:  we deleted the newly-created resource and re-ran the pipeline; this time it succeeded (but according to the linked issues that might be more luck than judgment)

If the assumption is correct then changes similar to [this](https://github.com/terraform-providers/terraform-provider-azurerm/pull/9698/files) should resolve the issue

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
