### ISSUE TITLE
Support for Azure Netapp Files - AD Site Name

### ISSUE THREAD

**Issue by schlbra** [hashicorp/terraform-provider-azurerm#12462]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the netapp files account resource does not have a `site` or `AD Site Name` attribute. This is the site name that the domain controller discover will be limited to.  Since netapp files does not currently support route tables, this attribute is required for large organizations that multiple domain controllers in datacenters across the world.

This `Site` parameter already exists in the Azure SDK for Go so hopefully adding it to the terraform resource is quick and easy [(LINK HERE)](https://github.com/Azure/azure-sdk-for-go/blob/a8003cfb0fc890f0619b0f11d71947c5bb559e0d/services/netapp/mgmt/2020-05-01/netapp/models.go#L425).

![image](https://user-images.githubusercontent.com/12618487/124333688-977ca500-db5a-11eb-8e4e-d565caa36383.png)

### New or Affected Resource(s)

* azurerm_netapp_account

### Potential Terraform Configuration

```hcl
resource "azurerm_netapp_account" "example" {
  name                = "example-netapp"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  active_directory {
    username            = "aduser"
    password            = "aduserpwd"
    smb_server_name     = "SMBSERVER"
    dns_servers         = ["1.2.3.4"]
    domain              = "westcentralus.com"
    organizational_unit = "OU=FirstLevel"
    site_name           = "WestCentral"
  }
}
```

### References

* [Link to where this is found in the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go/blob/a8003cfb0fc890f0619b0f11d71947c5bb559e0d/services/netapp/mgmt/2020-05-01/netapp/models.go#L425)
* [Link to Terraform Resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/netapp_account)

**Comment by KenCowley1967** [comment]
Has there been any movement on this request as it is urgently required by a project I am working on. Without this I cannot fully automate the deployment using terraform as the AD join with correct site is fundamental to creating the SMB volumes as part of the deployment. if there is a work around please share

**Comment by thplex48178** [comment]
Same question as bye others, is there any movement? or plan ? I would also need the AES configuration check box. Otherwise the Terraform automation is very limited in it's usefulness. Probably all of the gui options would need to be implemented. Thanks

**Comment by aleblanc70** [comment]
The AES configuration and Site Name seem to be available with pulumi Azure Native provider 
https://www.pulumi.com/registry/packages/azure-native/api-docs/netapp/account/

Please please Hashicorp :)
