### ISSUE TITLE
Error retrieving Azure Storage Account - 404

### ISSUE THREAD

**Issue by oryon-dominik** [hashicorp/terraform-provider-azurerm#12470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

1.0.1  
2.66.0  

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "filestorage" {
  name                     = var.storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = var.account_tier
  account_replication_type = var.account_replication_type
  allow_blob_public_access = var.allow_blob_public_access
  tags                     = var.tags

  dynamic "network_rules" {
    for_each = var.networkrules
    content {
      default_action             = network_rules.value
      ip_rules                   = var.devops_agent_ip
      virtual_network_subnet_ids = var.private_endpoint_subnet_id
    }
  }
}
```

### Pipeline Output
╷
│ Error: Error retrieving Azure Storage Account "filestorage": storage.AccountsClient#GetProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account storageaccountname was not found."
│ 
│   with module.modulename.azurerm_storage_account.filestorage,
│   on modules/modulename/main.tf line 2, in resource "azurerm_storage_account" "storageaccountname":
│    2: resource "azurerm_storage_account" "filestorage" {
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.

### Expected Behaviour

The pipeline should have passed without errors.

### Actual Behaviour

The pipeline fails.

### Steps to Reproduce

This is a non-deterministic behaviour. The pipeline runs ~ 60% correctly and in 40% of the runs it fails with the above error-message.

1. `terraform apply`

**Comment by oryon-dominik** [comment]
may be related: https://github.com/terraform-providers/terraform-provider-azurerm/issues/12470

**Comment by phgogo** [comment]
Got the same error in `2.65.0`

**Comment by tyconsulting** [comment]
i had the same error, turned out i'm trying to connect the stroage account to a subnet that didn't have storage service endpoint enabled. once i enabled the service endpoint, the error went away

**Comment by oryon-dominik** [comment]
> i had the same error, turned out i'm trying to connect the stroage account to a subnet that didn't have storage service endpoint enabled. once i enabled the service endpoint, the error went away

We also have the storage service endpoint enabled.
But the error still occurs occassionally.

**Comment by tombuildsstuff** [comment]
hi @oryon-dominik 

Thanks for opening this issue.

Taking a look through this appears to be a configuration issue, as there's no dependency between the resources - since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
