### ISSUE TITLE
Error refreshing State on previously created Storage Account

### ISSUE THREAD

**Issue by andydkelly-ig** [hashicorp/terraform-provider-azurerm#12485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.13.7
Azure Provider 2.65.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "redacted" {
  name                     = "redacted"
  resource_group_name      = azurerm_resource_group.data.name
  location                 = "Australia East"
  account_tier             = "Standard"
  account_replication_type = "GRS"
  account_kind             = "Storage"
  enable_https_traffic_only = false
  tags = {
    owner       = var.tagOwner
    description = "The storage account used for App Service Backups and SQL Logs for Australia"    
    usage       = var.tagUsage
    config      = var.tagConfig
  }
}
```

### Expected Behaviour

This storage account was created >12 months ago using Terraform. The last successful run of this workspace was using provider 2.18.0 When refreshing the workspace resources in order to make an unrelated change to a different component, Terraform should not return an error.  

### Actual Behaviour

When refreshing the state Terraform returns the error:

```
Error: reading share properties for AzureRM Storage Account "redacted": storage.FileServicesClient#GetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="File is not supported for the account."
```

Speaking with Vladimir Lazarenko on Slack, the error comes from the following code:

```
	if resp.Kind == storage.FileStorage || resp.Kind != storage.BlobStorage && resp.Kind != storage.BlockBlobStorage && resp.Sku != nil && resp.Sku.Tier != storage.Premium {
		shareProps, err := fileServiceClient.GetServiceProperties(ctx, resGroup, name)
		if err != nil {
			if !utils.ResponseWasNotFound(shareProps.Response) {
				return fmt.Errorf("reading share properties for AzureRM Storage Account %q: %+v", name, err)
			}
		}
		if err := d.Set("share_properties", flattenShareProperties(shareProps)); err != nil {
			return fmt.Errorf("setting `share_properties `for AzureRM Storage Account %q: %+v", name, err)
		}
	}
```

### Steps to Reproduce

1. Make a change to a resource in a workspace that also has a Storage Account with the settings in above config.
2. Use recent Azure Provider
3. Reverting provider to 2.18.0 causes this not to be an issue. I have tried latest 5 releases of Provider and the issue is present, 2.18.0 was the version when we had our last successful run. Reverting back to this version resolves the issue.

**Comment by aristosvo** [comment]
The solution is probably to disable this functionality for `account_kind = Storage`.

A solution for your problems could be to upgrade to `account_kind = StorageV2`.

**Comment by andydkelly-ig** [comment]
As i understand from https://docs.microsoft.com/en-us/azure/storage/common/storage-account-upgrade?tabs=azure-portal Microsoft have not deprecated `storage` and has no plan to do so. what would the reason behind forcing Terraform users to upgrade storage to storagev2?

**Comment by aristosvo** [comment]
Sorry for the misunderstanding, I'm not trying to say the Terraform provider should not support this scenario. I'll figure out if it is possible to fix it, and let you know the outcome.

Depending on your own timeframe and other influences you should do what suits best for you. Just trying to give the options.

**Comment by andydkelly-ig** [comment]
No worries at all - for now i pinned the workspace to use 2.18.0 as it's a small workspace and there isn't anything in there that relies on newer code so at least we have a workaround in place. Cheers

**Comment by aristosvo** [comment]
@andydkelly-ig I tried to test it via a new acceptance test, but I'm unable to reproduce it with a newly created StorageAccount with `account_kind = Storage`. Do you know of any network settings you've configured or AD configuration?

I'm afraid `account_kind = Storage` may lack some features in storage accounts which are created longer ago.., and thus very hard to support in a maintainable way.

**Comment by f0o** [comment]
@aristosvo I can repro it straight out of the box with nothing fancy:

```hcl
resource "azurerm_storage_account" "IAmBorken" {
  name                     = "somerandomnameagjfsrgfduhkjesd"
  resource_group_name      = local.resource_group.name
  location                 = local.resource_group.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"
  account_kind             = "Storage" 
}
```

Using version 2.67.0

**Comment by f0o** [comment]
Seems easy enough to add another check into `https://github.com/terraform-providers/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L1699 to filter out `account_kind=Storage`... That might need to be added in a few other places too perhaps

**Comment by f0o** [comment]
@aristosvo had any chance to look at this again?
