### ISSUE TITLE
azurerm_security_center_automation doesn't create Log Analytics Continuous Export settings

### ISSUE THREAD

**Issue by cmptscpeacock** [hashicorp/terraform-provider-azurerm#12491]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.14.11
* azurerm 2.62.0

### Affected Resource(s)

* azurerm_security_center_automation

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_automation" "securityCenter1Automation1" {
  name                = "SecurityCenter1Automation1"
  resource_group_name = var.resourceGroup1Name
  location            = var.location

  action {
    type        = "LogAnalytics"
    resource_id = var.logAnalytics1Id
  }

  source {
    event_source = "Alerts"
  }

source {
    event_source = "Alerts"
    rule_set {
      rule {
        property_path  = "properties.metadata.severity"
        operator       = "Equals"
        expected_value = "High"
        property_type  = "String"
      }
    }
  }
  
  source {
    event_source = "Assessments"
    rule_set {
      rule {
        property_path  = "type"
        operator       = "Contains"
        expected_value = "Microsoft.Security/assessments"
        property_type  = "string"
      }
    }
  }

  scopes = ["/subscriptions/${data.azurerm_client_config.current.subscription_id}"]
}
```

### Expected Behaviour

Continuous export should be visible on the Azure Portal post deployment.

### Actual Behaviour

![image](https://user-images.githubusercontent.com/40865231/124602473-cc417280-de60-11eb-99dd-eaa4a7756552.png)

The security center continuous export settings are not set. No errors from the TF apply, and we do get a Apply complete.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

As per the example, I've tried a few variations to create Alerts or Assessments with the "source" field, on their own and also together as per the example. 

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_automation

**Comment by vijay1yadav** [comment]
Hi All, This issue is open since long. Any update or solution around it.

**Comment by rezarms** [comment]
I have the same issue. It doesn't update settings for LogAnalytics

**Comment by rezarms** [comment]
I came up with a solution that uses Azure policy at scale.
You can use policy assignment in terraform.
Policy:
**Deploy export to Log Analytics workspace for Azure Security Center data**

**Comment by markusbecker** [comment]
You would need to set the name of the export automation either to "ExportToWorkspace" or "ExportToEventhub" to make it recognized by the portal. See https://github.com/hashicorp/terraform-provider-azurerm/issues/9975

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
