### ISSUE TITLE
Front door WAF policy association *always* re-deploys front end even when there are no changes

### ISSUE THREAD

**Issue by royjacob** [hashicorp/terraform-provider-azurerm#12494]
With the following WAF policy:
resource "azurerm_frontdoor_firewall_policy" "wafpolapppprd" {
  name                              = "MOHHUBFDWAFPOLAPPPPRD"
  resource_group_name               = azurerm_resource_group.fdresourcegroup.name
  enabled                           = true
  mode                              = "Prevention"
  redirect_url                      = "https://....../"
  custom_block_response_status_code = 403

  managed_rule {
    type    = "DefaultRuleSet"
    version = "1.0"
  }
}

And the folllowing Front Door front end block:
....
    frontend_endpoint {
        name                              = "....."
        host_name                         = "....."
        web_application_firewall_policy_link_id     = azurerm_frontdoor_firewall_policy.wafpolapppprd.id
    }
....

I would expect that no changes to the policy link ID would mean no changes to the end point.

However it comes up every time as an inplace update:
      ~ frontend_endpoint {
            id                                      = "/subscriptions/.../resourceGroups/MOH-HUB-FRONTDOOR01/providers/Microsoft.Network/frontDoors/MOH-GLB-PRD-FrontDoor/frontendEndpoints/....."
            name                                    = "...."
          ~ web_application_firewall_policy_link_id = "/subscriptions/.../resourceGroups/MOH-HUB-FRONTDOOR01/providers/Microsoft.Network/frontDoorWebApplicationFirewallPolicies/MOHHUBFDWAFPOLICY01" -> "/subscriptions/..../resourceGroups/MOH-HUB-FRONTDOOR01/providers/Microsoft.Network/frontdoorWebApplicationFirewallPolicies/MOHHUBFDWAFPOLICY01"
            # (3 unchanged attributes hidden)
        }

Notice the ID strings are identical.

While I'm hoping this is benign, my concern is that even a small change will result in a re-deploy of the front end, this is problematic for a resource which is designed to be always available. While I can work around this by breaking up he terraform it would be nice to to have to.

Kindest regards.
Roy,

Also, how do I get involved?

**Comment by eliog** [comment]
We noticed the same issue as well.  The difference seems to be the case "frontDoor" vs "frontdoor" 

```
"/subscriptions/.../providers/Microsoft.Network/frontDoorWebApplicationFirewallPolicies/glbwafpolicy" 
"/subscriptions/.../providers/Microsoft.Network/frontdoorWebApplicationFirewallPolicies/glbwafpolicy"
```

**Comment by WodansSon** [comment]
The legacy resource is no longer supported and is no longer being developed. Moving forward only the CDN Frontdoor resources are being supported.
