### ISSUE TITLE
Incorrect documentation of upgrade_description block in azurerm_service_fabric_cluster resource

### ISSUE THREAD

**Issue by Va55ago** [hashicorp/terraform-provider-azurerm#12505]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1

### Affected Resource(s)

* `azurerm_service_fabric_cluster`

### Terraform Configuration Files
According to the [official documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_fabric_cluster#upgrade_description), we should define the upgrade policy of a service fabric cluster in an upgrade_description block as shown:
```hcl
resource "azurerm_service_fabric_cluster" "cluster" {
  ...
  upgrade_description {
    force_restart                     = false
    health_check_retry_timeout        = "00:45:00"
    health_check_stable_duration      = "00:01:00"
    health_check_wait_duration        = "00:00:30"
    upgrade_replica_set_check_timeout = "10675199.02:48:05.4775807"
    upgrade_domain_timeout            = "02:00:00"
    upgrade_timeout                   = "12:00:00"
    health_policy {
      max_percent_unhealthy_applications = 0
      max_percent_unhealthy_nodes        = 0
    }
    delta_health_policy {
      max_percent_unhealthy_applications               = 0
      max_percent_unhealthy_nodes                      = 0
      max_percent_upgrade_domain_delta_unhealthy_nodes = 0
    }
  }
  ...
}
```

### Panic Output
```
Error: Unsupported block type

   on ..\terraform-modules\Azure\rdt_service_fabric_cluster\main.tf line 194, in resource "azurerm_service_fabric_cluster" "cluster":
  194:   upgrade_description {

 Blocks of type "upgrade_description" are not expected here.
```

### Expected Behaviour
Creating a resource that matches the official documentation should produce a valid plan.

It appears that the documentation of the upgrade_description block is at odds with the implementation. The documentation changes that seem to be needed are:
```hcl
resource "azurerm_service_fabric_cluster" "cluster" {
  upgrade_description { # ==> upgrade_policy
    force_restart = false # ==> force_restart_enabled
    health_policy {
      max_percent_unhealthy_applications = 0 # ==> max_unhealthy_nodes_percent
      max_percent_unhealthy_nodes        = 0 # ==> max_unhealthy_applications_percent
    }
    delta_health_policy {
      max_percent_unhealthy_applications               = 0 # ==> max_delta_unhealthy_nodes_percent
      max_percent_unhealthy_nodes                      = 0 # ==> max_delta_unhealthy_applications_percent
      max_percent_upgrade_domain_delta_unhealthy_nodes = 0 # ==> max_upgrade_domain_delta_unhealthy_nodes_percent
    }
  }
}
```

### Steps to Reproduce
1. Define an azurerm_service_fabric_cluster resource that includes an upgrade_description block as described by the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_fabric_cluster#upgrade_description).
2. Run `terraform plan`

**Comment by dhmoto17** [comment]
I had the same issue, it appears the attributes have been named differently in the provider to the documentation, as I found from this pull request https://github.com/terraform-providers/terraform-provider-azurerm/pull/10713 

For example the upgrade block appears to be called upgrade_policy.

**Comment by Va55ago** [comment]
@katbyte, I don't think that this issue is completely closed by 13027. As I pointed out in the "Expected Behaviour" section, there are many more incorrectly documented properties within the upgrade_policy block.

```hcl
resource "azurerm_service_fabric_cluster" "cluster" {
  upgrade_policy {
    force_restart = false                                  # ==> force_restart_enabled
    health_policy {
      max_percent_unhealthy_applications = 0               # ==> max_unhealthy_nodes_percent
      max_percent_unhealthy_nodes        = 0               # ==> max_unhealthy_applications_percent
    }
    delta_health_policy {
      max_percent_unhealthy_applications               = 0 # ==> max_delta_unhealthy_nodes_percent
      max_percent_unhealthy_nodes                      = 0 # ==> max_delta_unhealthy_applications_percent
      max_percent_upgrade_domain_delta_unhealthy_nodes = 0 # ==> max_upgrade_domain_delta_unhealthy_nodes_percent
    }
  }
}
```
