### ISSUE TITLE
VMSS and ADX clusters get replaced when zones change order

### ISSUE THREAD

**Issue by aml11** [hashicorp/terraform-provider-azurerm#12504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
`Terraform v1.0.1`
`terraform-provider-azurerm v2.66.0`

### Affected Resource(s)

* `azurerm_virtual_machine_scale_set`
* `azurerm_kusto_cluster`

### Terraform Configuration Files

```
provider "azurerm" {
  features {}
  skip_provider_registration = true
}


resource "azurerm_resource_group" "rg" {
  name     = "test-tf-rg"
  location = "West US 2"
}

resource "azurerm_kusto_cluster" "example" {
  name                = "testtfcluster"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  zones               = [1,3,2]
  sku {
    name     = "Standard_D13_v2"
    capacity = 2
  }

  tags = {
    Environment = "Production"
  }
}

```
Another example with VMSS
```

provider "azurerm" {
  features {}
  skip_provider_registration = true
}


locals {
  frontend_ip_configuration_name = "internal"
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = "${var.location}"
}

resource "azurerm_virtual_network" "example" {
  name                = "${var.prefix}-network"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  virtual_network_name = "${azurerm_virtual_network.example.name}"
  resource_group_name  = "${azurerm_resource_group.example.name}"
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_public_ip" "example" {
  name                = "${var.prefix}-publicip"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  allocation_method   = "Static"
    sku                 = "Standard"
}

resource "azurerm_lb" "example" {
  name                = "${var.prefix}lb"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  sku                 = "Standard"
  frontend_ip_configuration {
    name                 = "${local.frontend_ip_configuration_name}"
    public_ip_address_id = "${azurerm_public_ip.example.id}"
  }
}

resource "azurerm_lb_backend_address_pool" "example" {
  name                = "backend"
  resource_group_name = "${azurerm_resource_group.example.name}"
  loadbalancer_id     = "${azurerm_lb.example.id}"
}

resource "azurerm_lb_probe" "example" {
  name                = "ssh-running-probe"
  resource_group_name = "${azurerm_resource_group.example.name}"
  loadbalancer_id     = "${azurerm_lb.example.id}"
  port                = 22
  protocol            = "Tcp"
}

resource "azurerm_lb_rule" "example" {
  resource_group_name            = "${azurerm_resource_group.example.name}"
  loadbalancer_id                = "${azurerm_lb.example.id}"
  probe_id                       = "${azurerm_lb_probe.example.id}"
  backend_address_pool_id        = "${azurerm_lb_backend_address_pool.example.id}"
  frontend_ip_configuration_name = "${local.frontend_ip_configuration_name}"
  name                           = "LBRule"
  protocol                       = "Tcp"
  frontend_port                  = 22
  backend_port                   = 22
}

resource "azurerm_virtual_machine_scale_set" "example" {
  name                 = "${var.prefix}-vmss"
  location             = "${azurerm_resource_group.example.location}"
  resource_group_name  = "${azurerm_resource_group.example.name}"
  overprovision        = true
  upgrade_policy_mode  = "Rolling"
  automatic_os_upgrade = true
  health_probe_id      = "${azurerm_lb_probe.example.id}"
  zones                = [1,2,3]

  rolling_upgrade_policy {
    max_batch_instance_percent              = 20
    max_unhealthy_instance_percent          = 20
    max_unhealthy_upgraded_instance_percent = 20
    pause_time_between_batches              = "PT0S"
  }

  sku {
    name     = "Standard_D1_v2"
    tier     = "Standard"
    capacity = 3
  }

  os_profile {
    computer_name_prefix = "${var.prefix}-vm"
    admin_username       = "myadmin"
    admin_password       = "Passwword1234"
  }

    os_profile_linux_config {
    disable_password_authentication = true

    ssh_keys {
      path     = "/home/myadmin/.ssh/authorized_keys"
      key_data = file("~/.ssh/id_rsa.pub")
    }
    }

  network_profile {
    name    = "internal"
    primary = true

    ip_configuration {
      name                                   = "internal"
      subnet_id                              = "${azurerm_subnet.example.id}"
      load_balancer_backend_address_pool_ids = ["${azurerm_lb_backend_address_pool.example.id}"]
      primary                                = true
    }
  }

  storage_profile_os_disk {
    name              = ""
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  storage_profile_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}
```

### Expected Behaviour

AZs are not ordered, it shouldn't matter if I use 1,2,3 or 3,2,1, it should be regarded like a set.... see https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_elasticache_replication_group.go#L343 for how `terraform-provider-aws` does it.

### Actual Behaviour

If I change it to `1,2,3` from `3,2,1` TF will try to rebuild the resource. 

### Steps to Reproduce

Use one of the 2 example tf

1. `terraform apply` (will deploy theinitial stack)
2. Change the zones to be something else... say 1,2,3 instead of 2,1,3
3. `terraform apply` (will now ask to replace the resource) 

* #0000

**Comment by aml11** [comment]
@katbyte you should probably add service/kusto label

**Comment by lulujrush** [comment]
Came across this almost year old issue after seeing VERY similar things. 

Issue I am seeing now is that when we set the zones to [1,2] the cluster will still decide what zones it wants to use but maybe not on first `tf apply` but subsequent ones. This morning I deployed a stack that had the [1,3] zones set... Deployed made a new DB and went to deploy that and here is what TF tells me it is going to do. So it seems the first deployment never even made it to [1,3] but rather [2,3] 

<img width="540" alt="Screen Shot 2022-06-30 at 08 26 52" src="https://user-images.githubusercontent.com/101839303/176716308-fd8ba7b4-4cda-4825-8c46-ffbe7008fd6e.png">

@katbyte any updates on this issue getting some attention? I would love to go over it more with you all if needed. Would it be easier if I reach out to Mark Gray from MSFT about what we are seeing? (We have been working with them on other MSFT TF issues/missing things we are encountering)

**Comment by lulujrush** [comment]
Thought I would try a new deployment with [1,2] in my code, `tf apply` shows that it will be going to [1,2] 

<img width="540" alt="Screen Shot 2022-06-30 at 08 32 31" src="https://user-images.githubusercontent.com/101839303/176717921-2bd784e6-28d2-42d4-a25d-e7c8eeb4af3f.png">

but in reality when deployed it goes to [1,3] 
![Screen Shot 2022-06-30 at 08 36 10](https://user-images.githubusercontent.com/101839303/176718296-3a7cc45c-7baf-4489-96c8-d54b79be4d48.png)

json view of console

![Screen Shot 2022-06-30 at 08 36 47](https://user-images.githubusercontent.com/101839303/176718412-4f6abb14-e7ef-4994-9332-d68519b8a092.png)

then if I do another `tf apply` we see that it also sees the deployed item is NOT what it thought was going to be and will destroy/replace. 
<img width="640" alt="Screen Shot 2022-06-30 at 08 43 41" src="https://user-images.githubusercontent.com/101839303/176720034-2fafacc0-2452-4f17-b2c6-f530fc2beaa7.png">

so I let that run and then in Azure it STILL shows [1,3] after deployments complete.
![Screen Shot 2022-06-30 at 09 10 45](https://user-images.githubusercontent.com/101839303/176726411-5800ad75-f960-4939-8a5a-b866afc90609.png)

**Comment by myc2h6o** [comment]
Issue with `azurerm_kusto_cluster` looks to be a service bug and has been resolved. Details could be found at #17461.
For `azurerm_virtual_machine_scale_set`, this resource had been in feature freezing state so could not be changed. The behavior is because the `zones` is a `TypeList` https://github.com/hashicorp/terraform-provider-azurerm/blob/d32e718dc092f2e70c422f894c62bf0c370245cb/internal/services/legacy/virtual_machine_scale_set_resource.go#L72-L74.
For others meeting this issue, the three new resources `azurerm_linux_virtual_machine_scale_set`, `azurerm_windows_virtual_machine_scale_set` and `azurerm_orchestrated_virtual_machine_scale_set` could be used, where `zones` is a `TypeSet`
https://github.com/hashicorp/go-azure-helpers/blob/768f9b56cb76e977dceb971772beb2cf0e09cf6e/resourcemanager/commonschema/zones.go#L51-L53

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
