### ISSUE TITLE
Getting data of `azurerm_batch_pool` fails if no `public_ips` in `network_configuration` are set

### ISSUE THREAD

**Issue by sgutwein** [hashicorp/terraform-provider-azurerm#12506]
Hello,

the `network_configuration` in my `azurerm_batch_pool` resource is configured like this:

```
resource "azurerm_batch_pool" "ba" {
...
  network_configuration {
    subnet_id = azurerm_subnet.ba.id
  }
...
}
```

By getting the data source it fails, as no `public_ips` in `network_configuration` are set:
```
Error: error setting `network_configuration`: Invalid address to set: []string{"network_configuration", "0", "public_ips"}

  on main.tf line 39, in data "azurerm_batch_pool" "ba":
  39: data "azurerm_batch_pool" "ba" {
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* resource azurerm_batch_pool
* data azurerm_batch_pool

https://github.com/terraform-providers/terraform-provider-azurerm/blob/eb528252c9ed1c1e7916b669ce5fc775b75ceb5b/azurerm/internal/services/batch/batch_pool_data_source.go#L297

**Comment by donbee** [comment]
I get a similar error when attempting to access an existing resource via data source.

> Error: error setting `network_configuration`: Invalid address to set: []string{"network_configuration", "0", "public_address_provisioning_type"}

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
