### ISSUE TITLE
 Error Code="ReplicationIsDisabled" Message="The operation could not be completed. Replication is not enabled for the server. Set server parameter azure.replication_support to REPLICA on the master server and restart it.

### ISSUE THREAD

**Issue by rodjanasaksit** [hashicorp/terraform-provider-azurerm#12514]
### Terraform (and AzureRM Provider) Version
0.14.7

### Affected Resource(s)
* `azurerm v.2.61.0`

### Terraform Configuration Files
```hcl
# Create PostgreSQL Server
resource "azurerm_postgresql_server" "psql" {
  name                = module.naming.postgresql
  location            = var.location
  resource_group_name = var.resource_group


  administrator_login          = var.administrator_login
  administrator_login_password = var.administrator_login_password

  sku_name   = var.sku_name
  version    = var.pgversion
  storage_mb = var.storage_mb

  backup_retention_days        = var.backup_retention_days
  auto_grow_enabled            = var.auto_grow
  geo_redundant_backup_enabled = var.geo_redundant_backup

  public_network_access_enabled    = false
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"

  create_mode = var.create_mode
  creation_source_server_id = var.postgresql_master_id

  tags = var.tags

  depends_on = [
    azurerm_resource_group_template_deployment.disable_private_endpoint_policy
  ]
}
```

### Debug Output

2021-07-08T03:37:35.005Z  Error: waiting for creation of PostgreSQL Server "psql-dr-cu1-vuaz871-fw" (Resource Group "rgp-we1-hcpsql"): Code="ReplicationIsDisabled" Message="The operation could not be completed. Replication is not enabled for the server. Set server parameter azure.replication_support to REPLICA on the master server and restart it."

### Expected Behaviour

replica server should be created

### Actual Behaviour

it return Replication is not enabled for the server

### Important Factoids

Master Region:  France Central
Replication Region:  Central US

***Only France is master failed

** Successful case
Master Region:  West Europe 
Replication Region:  Central US

**Comment by aristosvo** [comment]
@rodjanasaksit Can you tell me what you expect here? Should we enable replication on the primary server or do you want a flag to configure replication of the primary on a secondary/replica `azurerm_postgresql_server`? I'd say the first one, what do you think?

**Comment by rodjanasaksit** [comment]
@aristosvo I don't need to do any flag, I just wander in any azure region was successfully created with terraform but only France Region is Master it's make that error happen. ** again only France Region failed for other region working fine.

**Comment by aristosvo** [comment]
When is this France region master created? Just now? Is there a chance the replication is manually disabled or because it is created with an older version of `azurerm`

**Comment by rodjanasaksit** [comment]
@aristosvo We deploy the PostgreSQL DB on different regions such as West Europe, France Central, Australia Central, Central US etc. We provision the primary DB and some will require DR instance at the other region, When we provision with any other region as primary it works fine and when we select France Central as primary, it fails with the error above. THe same is working when we provision from the Azure portal. We were using azurerm version "2.56.0" The same failing with the version "2.61.0"

**Comment by manicminer** [comment]
Hi @rodjanasaksit, could you provide [debug logs ](https://www.terraform.io/docs/internals/debugging.html) to aid us in tracking down the cause of this error?  If it works in some region combinations but not others, this does sound more like an upstream service issue that perhaps the portal works around or is not subject to, but a debug log may offer enough information that we can reproduce this. Thanks!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
