### ISSUE TITLE
Feature request: Add resource for managing Event Hubs Geo-Recovery Pairing

### ISSUE THREAD

**Issue by ducas** [hashicorp/terraform-provider-azurerm#1251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer, I want to be able to manage Event Hubs Geo-Recovery Pairings using terraform so that I don't have to automate it using PowerShell/cli.

APIs available here - https://docs.microsoft.com/en-us/rest/api/eventhub/disasterrecoveryconfigs

### New or Affected Resource(s)

* azurerm_eventhub_geopairing

### Potential Terraform Configuration

```hcl
resource "azurerm_eventhub_namespace" "primary_namespace" {
  name                     = "my-hub-namespace-primary"
  resource_group_name      = "my-eventhubs-group-east"
  location                 = "australia east"
  sku                      = "Standard"
}

resource "azurerm_eventhub_namespace" "secondary_namespace" {
  name                     = "my-hub-namespace-secondary"
  resource_group_name      = "my-eventhubs-group-southeast"
  location                 = "australia southeast"
  sku                      = "Standard"
}

resource "azurerm_eventhub_geopairing" "geopairing" {
  alias                    = "my-hub-alias"
  resource_group_name      = "my-eventhubs-group-east"
  primary_namespace        = "${azurerm_eventhub_namespace.primary_namespace.name}"
  secondary_namespace      = "${azurerm_eventhub_namespace.secondary_namespace.id}" # this needs to be an ID if in a different resource group
}
```

### References

* N/A

**Comment by adventuresinazure** [comment]
This is important so I don’t have to use CLI or other tools

**Comment by rudolphjacksonm** [comment]
We're using ARM templates to accomplish this currently and it's not the best experience. It would be great if we could manage these using Terraform. We use Event Hubs as the backbone of our logging infra so making changes via ARM is definitely not preferred.

**Comment by rudolphjacksonm** [comment]
Any updates on this issue?

**Comment by tomoiti** [comment]
Isn't this already covered by azurerm_eventhub_namespace_disaster_recovery_config ?
https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace_disaster_recovery_config.html

**Comment by favoretti** [comment]
As @tomoiti mentioned, the disaster recovery config should cover this, therefore I'm going to close this. Please open a new updated bug report if this is still relevant. Thank you.
