### ISSUE TITLE
Support for new Azure Bot Service

### ISSUE THREAD

**Issue by Dan-Bai** [hashicorp/terraform-provider-azurerm#12522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Bot Channel Registration will be deprecated in the coming months and replaced by Azure Bot. It would be nice to have that available in terraform. 

### New or Affected Resource(s)

* azurerm_bot_channels_registration
* azurerm_bot_channel_directline?

### Potential Terraform Configuration

From the exported template, the underlying structure looks identical except for "kind" property. As such, the configuration should remain the same of azurerm_bot_channels_registration

### References

* [Deprecation Note](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-quickstart-registration?view=azure-bot-service-4.0&tabs=csharp%2Ccshap)

**Comment by wang415** [comment]
I have the same question.

**Comment by TPPWC** [comment]
Any update on this?

**Comment by AiGhostMod** [comment]
Any updates?

**Comment by drdamour** [comment]
@howlowck what about the channel stuff part of this ticket?
