### ISSUE TITLE
Subscription ID cannot be set as resource_id in azurerm_resource_policy_assignment

### ISSUE THREAD

**Issue by romanshiryaev** [hashicorp/terraform-provider-azurerm#12521]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.66.0
```

### Affected Resource(s)

* `azurerm_resource_policy_assignment`

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "current" {
}

data "azurerm_policy_definition" "kv-secrets-expiration-set" {
  display_name = "[Preview]: Key Vault secrets should have an expiration date"
}

resource "azurerm_resource_policy_assignment" "kv-secrets-expiration-set" {
  name                 = "kv-secrets-expiration-set"
  resource_id          = data.azurerm_subscription.current.id
  policy_definition_id = data.azurerm_policy_definition.kv-secrets-expiration-set.id
}

```
### Debug Output

```
╷
│ Error: ID cannot be a Subscription ID
│ 
│   with module.sharedres.azurerm_resource_policy_assignment.kv-secrets-expiration-set,
│   on .terraform/modules/sharedres/policy.tf line 10, in resource "azurerm_resource_policy_assignment" "kv-secrets-expiration-set":
│   10:   resource_id          = data.azurerm_subscription.current.id
│ 
╵

```
### Expected Behaviour

The azure policy assignment should have been created as scoped to the whole current Azure Subscription (I'm able to create the same via Azure Portal and also see a valid resource_id when I try to import the existing Azure Policy Assignment into the current terraform state). The API doc also states that `Be sure to replace {scope} with one of the following patterns:
Subscription: /subscriptions/{subscriptionId}`
```
resource "azurerm_resource_policy_assignment" "kv-secrets-expiration-set" {
    ...
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/98728c90-32c7-4049-8429-847dc0f4fe37"
    resource_id          = "/subscriptions/0cf03d4a-be67-42d2-bfc6-18e57807abc8"
}
```

### Steps to Reproduce

1. `terraform plan -out plan.out`

### References

* https://docs.microsoft.com/en-us/azure/governance/policy/assign-policy-rest-api

**Comment by bmargula** [comment]
I'm facing the same issue 15 months later - is this still not solved?

**Comment by tombuildsstuff** [comment]
👋 

Support for this is [available in the `azurerm_subscription_policy_assignment` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment) - the `azurerm_resource_policy_assignment` is scoped to a given Resource Manager resource.

Since support for this is available in the `azurerm_subscription_policy_assignment ` resource I'm going to close this issue for the moment, but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
