### ISSUE TITLE
ADF Linked Service for Data Lake Gen 2 - Incorrect Required Inputs

### ISSUE THREAD

**Issue by Lachlan-White** [hashicorp/terraform-provider-azurerm#12546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.67.0
+ provider registry.terraform.io/hashicorp/random v2.3.1
+ provider registry.terraform.io/hashicorp/time v0.7.2
+ provider registry.terraform.io/microsoft/azuredevops v0.1.5

### Affected Resource(s)

* `azurerm_data_factory_linked_service_data_lake_storage_gen2`
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_data_lake_storage_gen2

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory_linked_service_data_lake_storage_gen2" "this" {
  count = var.adls_linked_service_enable ? 1 : 0

  name                     = "adlslink"
  resource_group_name      = var.resource_group_name
  data_factory_name        = azurerm_data_factory.this.name
  integration_runtime_name = azurerm_data_factory_integration_runtime_azure_ssis.this[0].name
  url                      = var.adls_endpoint
  use_managed_identity     = true
  tenant                   = var.tenant_id
}
```

### Expected Behaviour

As per the documentation for the resource, if the `use_managed_identity` argument is set to true it is incompatible with `service_principal_id` and `service_princpal_key`. 

It is expected that the use of `managed_identity` removes the need for the `service_prinicpal` arguments

### Actual Behaviour

However, since the change linked below the error is failing due to a required argument missing:

```
Error: Missing required argument

  on .terraform/modules/modern_data_platform.data_factory/main.tf line 66, in resource "azurerm_data_factory_linked_service_data_lake_storage_gen2" "this":
  66:   tenant                   = var.tenant_id

"tenant": all of `service_principal_id,tenant` must be specified
```
This previously has worked, where the use of a managed identity removes the need for the `service_principal_id` and `service_principal_key` fields.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It seems like this has occurred as a result of the PR https://github.com/terraform-providers/terraform-provider-azurerm/pull/12136

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_data_lake_storage_gen2#use_managed_identity

**Comment by MoAhuja** [comment]
I haven't played with this at all, but just looking at the code, it appears that tenant is optional (I realize the documentation has it marked as required).

```
"tenant": {
      Type:          pluginsdk.TypeString,
      Optional:      true,
      ValidateFunc:  validation.StringIsNotEmpty,
      RequiredWith:  []string{"service_principal_id"},
      ConflictsWith: []string{"storage_account_key", "use_managed_identity"},
},
```

Looks like it's needed when you have a 'service_principal_id' set, which you obviously don't because you're running managed identity. Can you try deploying without the tenant field?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
