### ISSUE TITLE
Failure to import azurerm_role_assignment

### ISSUE THREAD

**Issue by pintope** [hashicorp/terraform-provider-azurerm#12552]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.62.0

### Affected Resource(s)

azurerm_role_assignment

### Terraform Configuration Files

terraform import azurerm_role_assignment.TerraformNetwork "/subscriptions/REMOVED/resourceGroups/azwe-services-bastion-rg01/providers/Microsoft.ContainerRegistry/registries/betvictor/providers/Microsoft.Authorization/roleAssignments/REMOVED"

### Debug Output

https://gist.github.com/pintope/117acc699dec81ebe6a9742ca3b1b05a

### Expected Behaviour

Resource imported

### Actual Behaviour

Failure

### Steps to Reproduce

Import a resource of the type above

# Notes
Unique identifier removed.

**Comment by pintope** [comment]
Issue seems to be TF is adding an extra "/" to the ID.

**Comment by aristosvo** [comment]
There has been a hotfix release, I'd try v2.62.1!

You may need to reimport your role or delete manually and regenerate.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
