### ISSUE TITLE
Support for azurerm_netapp_volume "Continuous Availability" flag

### ISSUE THREAD

**Issue by MariuszG7** [hashicorp/terraform-provider-azurerm#12572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Netapp Files now supports "Continuous Availability" feature and can only be set when Volume is created.

### New or Affected Resource(s)

azurerm_netapp_volume

### Potential Terraform Configuration

Default:
    continuous_availability = false

can be changed to:
    continuous_availability = true

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by MariuszG7** [comment]
FYI: 
Thru GUI interface the [ ] Continuous Availability checkbox is available when Protocol Type [SMB] is selected. 
The feature is in PUBLIC PREVIEW now and available to customers who requested the feature to be available and got approved.

**Comment by adhodgson1** [comment]
This feature is now in GA state as per this [Microsoft article.](https://learn.microsoft.com/en-us/azure/azure-netapp-files/whats-new)
