### ISSUE TITLE
Enable Zonal capability for App Service Enviroment V3

### ISSUE THREAD

**Issue by adamyager** [hashicorp/terraform-provider-azurerm#12577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Today the App Service Enviroment V3 povider does no support the ability to run this in a Zonal config. This service is now in GA.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3
I am told by the product team that the swagger is being updated but is avaiable(but not documented) in the current API spec..
https://docs.microsoft.com/en-us/rest/api/appservice/app-service-environments

"zoneRedundant": true/false

### New or Affected Resource(s)

Existing resource that is impacted.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3

azurerm_app_service_environment

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3
and
https://docs.microsoft.com/en-us/rest/api/appservice/app-service-environments

* #0000

**Comment by miwebst** [comment]
Dependent on https://github.com/Azure/azure-rest-api-specs/pull/15188
