### ISSUE TITLE
Changing os azure storage acount 'account_replication_type' forces re-creation of the account

### ISSUE THREAD

**Issue by vijayrajah** [hashicorp/terraform-provider-azurerm#12589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_account`

on version `2.51.0` of provider, the changes are made in-place ( i.e without replacement)
```
  ~ resource "azurerm_storage_account" "adls" {
        access_tier                    = "Hot"
        account_kind                   = "StorageV2"
      ~ account_replication_type       = "GRS" -> "LRS"
        account_tier                   = "Standard"
        allow_blob_public_access       = false
        enable_https_traffic_only      = true
        id                             = "<ID>"
        is_hns_enabled                 = true
.
.
.

```

in version `2.67.0` of provider, the account is re-created
```
-/+ resource "azurerm_storage_account" "adls" {
      ~ access_tier                      = "Hot" -> (known after apply)
        account_kind                     = "StorageV2"
      ~ account_replication_type         = "GRS" -> "LRS" # forces replacement
        account_tier                     = "Standard"
        allow_blob_public_access         = false
        enable_https_traffic_only        = true
      ~ id                               = "<ID>" -> (known after apply)
        is_hns_enabled                   = true
      + large_file_share_enabled         = (known after apply)
        location                         = "eastus2"
        min_tls_version                  = "TLS1_0"
        name                             = "<ACCNT_NAME>"
        nfsv3_enabled                    = false
      ~ primary_access_key               = (sensitive value)
      ~ primary_blob_connection_string   = (sensitive value)
      ~ primary_blob_endpoint            = "https://<ACCNT_NAME>.blob.core.windows.net/" -> (known after apply)
      ~ primary_blob_host                = "<ACCNT_NAME>.blob.core.windows.net" -> (known after apply)
      ~ primary_connection_string        = (sensitive value)
      ~ primary_dfs_endpoint             = "https://<ACCNT_NAME>.dfs.core.windows.net/" -> (known after apply)
      ~ primary_dfs_host                 = "<ACCNT_NAME>.dfs.core.windows.net" -> (known after app
.
.
.
```
### Expected Behaviour

The resource should be updated in-place

### References

Azure supports change of replication without re-creating the resources (delete & create). FYI -- [doc](https://docs.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal)

**Comment by wasfree** [comment]
Hi @vijayrajah 

see https://github.com/terraform-providers/terraform-provider-azurerm/pull/12479, seems some replication types support in-place updates while others do not. There was a change made so all changes to account_replication_type force a new resource. Haven't looked into it in detail if we could reflect the matrix in [docs](https://docs.microsoft.com/en-us/azure/storage/common/redundancy-migration?tabs=portal) to terraform.

**Comment by tombuildsstuff** [comment]
This appears to be fixed in `main` - as such I'm going to close this issue for the moment, but if you're still seeing this issue when using the latest version of the Provider then please let us know and we'll take another look.

Thanks!
