### ISSUE TITLE
Changing the size of default_node_pool in azurerm_kubernetes_cluster errors

### ISSUE THREAD

**Issue by anna-yn** [hashicorp/terraform-provider-azurerm#12582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.1
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.65.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2

Your version of Terraform is out of date! The latest version
is 1.0.2. You can update by downloading from https://www.terraform.io/downloads.html
```
### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.environment}-${var.cluster_group}-${var.cluster_type}"
  location            = var.location
  resource_group_name = var.resource_group_name
  dns_prefix          = "${var.environment}-${var.cluster_group}-${var.cluster_type}"
  linux_profile {
    admin_username = "ubuntu"

    ssh_key {
      key_data = data.azurerm_key_vault_secret.ssh_key.value
    }
  }

  default_node_pool {
    name           = "agentpool"
    node_count     = var.node_count
    vm_size        = "Standard_D2_v2"
    type           = "AvailabilitySet"
    vnet_subnet_id = lookup(var.subnet_ids, var.cluster_type)
  }
...
}
```

### Expected Behaviour
I have an aks cluster managed by tf that was created with 3 nodes in the default node pool. It's not using VMSS. 

I updated `var.node_count` from 3 to 5 and `terraform plan`, got this output: 
```
  # module.cluster_retool_main.azurerm_kubernetes_cluster.k8s will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "k8s" {
        id                              = "/subscriptions/b8fdf600-459c-417b-9a3d-8851420c520b/resourcegroups/staging/providers/Microsoft.ContainerService/managedClusters/staging-tf-main"
        name                            = "staging-tf-main"
        tags                            = {}
        # (20 unchanged attributes hidden)


      ~ default_node_pool {
            name                         = "agentpool"
          ~ node_count                   = 3 -> 5
            tags                         = {}
            # (16 unchanged attributes hidden)
        }




        # (5 unchanged blocks hidden)
    }
```
So I think the cluster should've added 2 nodes to the default node pool

### Actual Behaviour

Got this error:
```
│ Error: updating Default Node Pool "staging-tf-main" (Resource Group "staging"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="AgentPoolAPIsNotSupported" Message="AgentPool APIs supported only for clusters with VMSS agentpools. For more information, please check https://aka.ms/multiagentpoollimitations"
│
│   with module.cluster_retool_main.azurerm_kubernetes_cluster.k8s,
│   on ../modules/cluster/cluster.tf line 6, in resource "azurerm_kubernetes_cluster" "k8s":
│    6: resource "azurerm_kubernetes_cluster" "k8s" {
│
╵
```

### Steps to Reproduce

1. create a cluster with `azurerm_kubernetes_cluster` with just a default node pool with 3 nodes, no VMSS
2. Change the `node_count` from 3 to 5
3. `terraform plan` and `terraform apply`

### References

* #0000

**Comment by stephybun** [comment]
Hi @anna-yn, 

Thanks for raising this issue! Node pools based on availability sets have limited functionality when it comes to managing them and the azure docs are fairly explicit in discouraging their use ([REST API docs](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update#agentpooltype) and [limitations](https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#limitations)). Adding a note on this limitation in the provider docs is probably the way to go here.
