### ISSUE TITLE
Support for IoT Hub device creation

### ISSUE THREAD

**Issue by EliiseS** [hashicorp/terraform-provider-azurerm#12604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for creating a IoT Hub device like in the Azure CLI:
```sh
az iot hub device-identity create --device-id myDeviceId --hub-name {Your IoT Hub name}
```

### New or Affected Resource(s)

* azurerm_iothub_device

### Potential Terraform Configuration

```hcl
resource "azurerm_iothub_device" "example" {
  name            = "device_name"
  iothub_name     = azurerm_iothub.example.name
}
```

### References

* IoT Hub device create/update API link: <https://docs.microsoft.com/en-us/rest/api/iothub/service/devices/create-or-update-identity#devicecapabilities>
* Azure CLI using above API: https://github.com/Azure/azure-iot-cli-extension/blob/e10bed483371b44eba6912447642b3739ad7f4be/azext_iot/sdk/iothub/service/operations/devices_operations.py#L160
* #9416

##### **`main.tf`**

```hcl
terraform {
  required_providers {
    shell = {
      source  = "scottwinkler/shell"
      version = "1.7.7"
    }
  }
}

provider "shell" {}

resource "shell_script" "register_iot_edge_device" {
  lifecycle_commands {
    create = "$script create"
    read   = "$script read"
    delete = "$script delete"
  }

  environment = {
    iot_hub_name         = var.iot_hub_name
    iot_edge_device_name = "${var.resource_prefix}-edge-device"
    script               = "../../scripts/terraform/register_iot_edge_device.sh"
  }
}
```

##### **`register_iot_edge_device.sh`**
```bash
#!/bin/bash

set -e

create() {
    az iot hub device-identity create --device-id "$IOT_EDGE_DEVICE_NAME" --edge-enabled --hub-name "$IOT_HUB_NAME" --output none
    # shellcheck disable=SC2162
    read
}

read() {
    az iot hub device-identity connection-string show --device-id "$IOT_EDGE_DEVICE_NAME" --hub-name "$IOT_HUB_NAME"
}

delete() {
    az iot hub device-identity delete --device-id "$IOT_EDGE_DEVICE_NAME" --hub-name "$IOT_HUB_NAME"
}

# Check if the function exists (bash specific)
if declare -f "$1" >/dev/null; then
    # call arguments verbatim
    "$@"
else
    # Show a helpful error
    echo "'$1' is not a known function name" >&2
    exit 1
fi
```

**Comment by EliiseS** [comment]
This issue is blocked by the https://github.com/Azure/azure-sdk-for-go/issues/8399. The Azure SDK for go does not support iot devices at this moment.

**Comment by psmgeelen** [comment]
Any news on this?

**Comment by MirnaAlaisami** [comment]
Any updates here?

**Comment by EliiseS** [comment]
@MirnaAlaisami it's still blocked by the https://github.com/Azure/azure-sdk-for-go/issues/8399 issue. So any updates need to come on that ticket before hand.

**Comment by CornerstoneII** [comment]
It appears it is the same for terraform

**Comment by sjaatos** [comment]
Any news?

**Comment by EliiseS** [comment]
Unfortunately as the the other issue has been closed, we're also unable to implement this.
