### ISSUE TITLE
Resource azurerm_api_management tries to update hostname_configuration block created by azurerm_api_management_custom_domain on apply changes to API Management Service.

### ISSUE THREAD

**Issue by amkctc** [hashicorp/terraform-provider-azurerm#12607]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.4
hashicorp/azurerm v2.61.0

### Affected Resource(s)

* `azurerm_api_management`
* `azurerm_api_management_custom_domain`

### Debug Output
```
Error: creating/updating API Management Service "apim" (Resource Group "apim-rg"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameters" Message="Invalid parameter: Either encodedCertificate or keyVaultId should be provided to retrieve the custom SSL certificate for type: Management and hostname : management.apim.local."

  on .terraform/modules/main.apim/main.tf line 25, in resource "azurerm_api_management" "main":

  25: resource "azurerm_api_management" "main" {
```

### Expected Behaviour

Resource azurerm_api_management applies changes to API Management Service only.

### Actual Behaviour

Resource azurerm_api_management tries to update hostname_configuration block created by azurerm_api_management_custom_domain on apply changes to API Management Service and gets an error about "Invalid parameter".

### Steps to Reproduce

1. Create `azurerm_api_management` resource  without `hostname_configuration` block.
2. `terraform apply`
3. Add custom domains via `azurerm_api_management_custom_domain` resource.
4. `terraform apply`
5. Make any changes to `azurerm_api_management` resource (ex. publisher email)
6. `terraform apply`

You will see `hostname_configuration` block in the plan,  without any signs of changes. But deployment will fail with the error.

### References

* #0000

**Comment by thomast1906** [comment]
+1 to this, we have similar - it does finish successfully but it shouldn't be attempting an update each time when not required.

Takes 15mins or so extra per Terraform run for this

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
