### ISSUE TITLE
issue with "azurerm_firewall" resource

### ISSUE THREAD

**Issue by marckean** [hashicorp/terraform-provider-azurerm#12623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

azurerm_firewall

### Terraform Configuration Files

```hcl
resource "azurerm_firewall" "AzFW1" { # Standard
  for_each            = var.virtual_wan
  name                = "${var.environment_code}-${each.value.region_code}-afw-${each.value.environment}-${each.value.name_suffix}"
  location            = each.value.region
  resource_group_name = azurerm_resource_group.Virtual_Network.name
  firewall_policy_id  = azurerm_firewall_policy.AzFWPolicy[each.key].id
  tags                = var.tags
  sku_name            = "AZFW_Hub"
  sku_tier            = "Standard"
  #threat_intel_mode   = "Off"
  # does not accept ThreatIntelMode in current sku AZFW_Hub
  # Original Error: Code="AzureFirewallInvalidRequest" Message="Request parameter VirtualHub can not be specified in current SKU AZFW_VNet for the Azure Firewall
  # https://github.com/terraform-providers/terraform-provider-azurerm/issues/7368
  virtual_hub {
    virtual_hub_id = azurerm_virtual_hub.vwan_hubs[each.key].id
    public_ip_count = 1
  }
}
```

### Expected Behaviour

It should deploy just fine

### Actual Behaviour

Fails with - Original Error: Code="AzureFirewallDoesNotAcceptThreatIntelModeInSku" Message="Azure Firewall /subscriptions/6bb00255-5486-4db1-96ca-5baefc18b0b2/resourceGroups/con-aue-rg-core_network/providers/Microsoft.Network/azureFirewalls/con-aue-afw-non_prod-002 does not accept ThreatIntelMode in current sku AZFW_Hub." Details=[]

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Basically: The Azure Firewall does not accept **ThreatIntelMode** with SKU **AZFW_Hub**. But removing **threat_intel_mode**  from the azurerm_firewall Terraform resource block makes no difference at all and it thinks it's still there and causes an error. 

When running this same command using Azure CLI:

az network firewall create --name "con-aue-afw-ss-003" --resource-group "con-aue-rg-core_network" --firewall-policy "/subscriptions/6bb00255-5486-4db1-96ca-5baefc18b0b2/resourceGroups/con-aue-rg-core_network/providers/Microsoft.Network/firewallPolicies/con-aue-afwp-ss-003" --count "1" --location "australiaeast" --sku "AZFW_Hub" --threat-intel-mode "Off" --tier "Standard" --vhub "/subscriptions/6bb00255-5486-4db1-96ca-5baefc18b0b2/resourceGroups/con-aue-rg-core_network/providers/Microsoft.Network/virtualHubs/con-aue-vwanhub-ss-003"

I get this error:

(AzureFirewallDoesNotAcceptThreatIntelModeInSku) Azure Firewall /subscriptions/6bb00255-5486-4db1-96ca-5baefc18b0b2/resourceGroups/con-aue-rg-core_network/providers/Microsoft.Network/azureFirewalls/con-aue-afw-ss-003 **does not accept ThreatIntelMode in current sku AZFW_Hub**.

In Azure CLI, if I take this out **--threat-intel-mode "Off"** it deploys successfully. 

However, this line "**threat_intel_mode   = "Off**" either in or out in the Terraform azurerm_firewall resource block, makes no difference, and seems to remain in there even if not included which causes the error. 

### References

* #0000

**Comment by aaronboock** [comment]
Preventing use of Terraform to deploy secured virtual hubs

**Comment by dimilider** [comment]
hey all, any updates on this? we have to deploy AZFW in vHub in Prod

**Comment by dimilider** [comment]
Hey @marckean i've played a bit and went trough the provide go file and figured out that if you provide the threat_intel_mode just with an "" as value, then it deploys - crazy. here is my full code I were able to deploy with:

`resource "azurerm_firewall" "example" {
  name                = "azfw"
  location            = "westeurope"
  resource_group_name = data.azurerm_resource_group.example.name
  sku_name            = "AZFW_Hub"
  sku_tier            = "Premium"
  threat_intel_mode   = ""
  firewall_policy_id  = data.azurerm_firewall_policy.example.id
  virtual_hub {
      virtual_hub_id  = data.azurerm_virtual_hub.example.id
      public_ip_count = 1
  }
  zones               = [1,2,3]
}`

**Comment by ahilmathew** [comment]
This doesn't work for me - 
```
resource "azurerm_firewall" "hub-firewall" {
  name                = "${var.environment_class}-${var.location_short}-${var.product_domain}-hub-firewall"
  location            = azurerm_resource_group.hub-infra-rg.location
  resource_group_name = azurerm_resource_group.hub-infra-rg.name
  sku_name            = "AZFW_Hub"
  sku_tier            = "Premium"
  threat_intel_mode   = ""

  virtual_hub {
    virtual_hub_id = azurerm_virtual_hub.hub.id
  }

  firewall_policy_id = azurerm_firewall_policy.default-allow-all.id
  tags               = local.tags
}
```

Errors out:
```
│Error: expected threat_intel_mode to be one of [Off Alert Deny], got 
│  with azurerm_firewall.hub-firewall,
│  on main.tf line 54, in resource "azurerm_firewall" "hub-firewall":
│  54:   threat_intel_mode   = ""
time=2022-07-05T05:24:17Z level=error msg=1 error occurred:
	* exit status 1
```

Any fix for this?

**Comment by eroadrdrdog** [comment]
Just a follow up, to @ahilmathew, it works if you omit the threat_intel_mode parameter:

```
resource "azurerm_firewall" "hub-firewall" {
  name                = "${var.environment_class}-${var.location_short}-hub-firewall"
  location            = azurerm_resource_group.hub-infra-rg.location
  resource_group_name = azurerm_resource_group.hub-infra-rg.name
  sku_name            = "AZFW_Hub"
  sku_tier            = "Premium"

  virtual_hub {
    virtual_hub_id = azurerm_virtual_hub.hub.id
  }

  firewall_policy_id = azurerm_firewall_policy.default-allow-all.id
  tags               = local.tags
}
```

**Comment by rdrdog** [comment]
Just a follow up, to @ahilmathew, it works if you omit the threat_intel_mode parameter:

```
resource "azurerm_firewall" "hub-firewall" {
  name                = "${var.environment_class}-${var.location_short}-hub-firewall"
  location            = azurerm_resource_group.hub-infra-rg.location
  resource_group_name = azurerm_resource_group.hub-infra-rg.name
  sku_name            = "AZFW_Hub"
  sku_tier            = "Premium"

  virtual_hub {
    virtual_hub_id = azurerm_virtual_hub.hub.id
  }

  firewall_policy_id = azurerm_firewall_policy.default-allow-all.id
  tags               = local.tags
}
```

**Comment by kourosh-forti-hands** [comment]
> Just a follow up, to @ahilmathew, it works if you omit the threat_intel_mode parameter:
> 
> ```
> resource "azurerm_firewall" "hub-firewall" {
>   name                = "${var.environment_class}-${var.location_short}-hub-firewall"
>   location            = azurerm_resource_group.hub-infra-rg.location
>   resource_group_name = azurerm_resource_group.hub-infra-rg.name
>   sku_name            = "AZFW_Hub"
>   sku_tier            = "Premium"
> 
>   virtual_hub {
>     virtual_hub_id = azurerm_virtual_hub.hub.id
>   }
> 
>   firewall_policy_id = azurerm_firewall_policy.default-allow-all.id
>   tags               = local.tags
> }
> ```

Did you deploy work when omitting `threat_intel_mode`? My firewall came up in a failed state and wanted to be sure it wasn't due to `threat_intel_mode`

**Comment by ahilmathew** [comment]
> to

Yeah. Get rid of that parameter and that works.

**Comment by ahilmathew** [comment]
> > Just a follow up, to @ahilmathew, it works if you omit the threat_intel_mode parameter:
> 
> > 
> 
> > ```
> 
> > resource "azurerm_firewall" "hub-firewall" {
> 
> >   name                = "${var.environment_class}-${var.location_short}-hub-firewall"
> 
> >   location            = azurerm_resource_group.hub-infra-rg.location
> 
> >   resource_group_name = azurerm_resource_group.hub-infra-rg.name
> 
> >   sku_name            = "AZFW_Hub"
> 
> >   sku_tier            = "Premium"
> 
> > 
> 
> >   virtual_hub {
> 
> >     virtual_hub_id = azurerm_virtual_hub.hub.id
> 
> >   }
> 
> > 
> 
> >   firewall_policy_id = azurerm_firewall_policy.default-allow-all.id
> 
> >   tags               = local.tags
> 
> > }
> 
> > ```
> 
> 
> 
> Did your deploy work when omitting `threat_intel_mode`? My firewall came up in a failed state and wanted to be sure it wasn't due to  `threat_intel_mode`


Yeah. Get rid of `threat_intel_mode`

**Comment by erwinkramer** [comment]
@ahilmathew Shouldn't the docs reflect that then? See https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall#threat_intel_mode 

`If virtual_hub_settting is specified, the threat_intel_mode has to be explicitly set as "".`

This should just say that it has to be omitted, i think setting it as empty string was the case in an older version, as we have used the empty string before upgrading to some newer terraform provider versions.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
