### ISSUE TITLE
azurerm_storage_account with network_rules doesn't give the error if missing serviceEndpoint but a 404 not found

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform-provider-azurerm#12627]
### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.2
on linux_amd64
+ provider registry.terraform.io/aztfmod/azurecaf v1.2.5
+ provider registry.terraform.io/hashicorp/azurerm v2.68.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/vault v2.21.0
+ provider registry.terraform.io/terraform-providers/mysql v1.9.0
+ provider registry.terraform.io/winebarrel/mysql v1.10.4
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "assets" {
  account_replication_type = "GRS"
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  location                 = module.azure-region.location
  name                     = local.storage_account_name
  resource_group_name      = module.rg.resource_group_name

  network_rules {
    default_action = "Deny"
    bypass         = ["Logging", "Metrics", "AzureServices"]
    ip_rules       = [for value in concat(local.admin_cidrs_list, local.customer_cidrs_list) : replace(value, "/(.*)\\/32/", "$1")]

    virtual_network_subnet_ids = [
      data.terraform_remote_state.xxx.outputs.fo_subnet_id
      data.terraform_remote_state.xxx.outputs.bo_subnet_id
    ]
  }
}
```

### Expected Behaviour
If a subnet doesn't have a serviceendpoint should have this error
̀```
│ Error: updating Azure Storage Account network_rules "zhstdeepr4qeuw1": storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NetworkAclsValidationFailure" Message="Validation of network acls failure: SubnetsHaveNoServiceEndpointsConfigured:Subnets zhsnetdeepadmpeuw1 of virtual network /subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxxx do not have ServiceEndpoints for Microsoft.Storage resources configured. Add Microsoft.Storage to subnet's ServiceEndpoints collection before trying to ACL Microsoft.Storage resources to these subnets.."
̀```

### Actual Behaviour

An error that doesn't help to debug
```
Error: Error retrieving Azure Storage Account "zhstdeepr4qeuw1": storage.AccountsClient#GetProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account zhstdeepr4qeuw1 was not found."
```

### Steps to Reproduce

1. `terraform apply`

Best regards,

**Comment by manicminer** [comment]
Hi @Poil, thanks for reporting this. Are you running Terraform from within the aforementioned subnet? If so, the error is expected as the provider is not in a position to determine the correct path to reach a storage account, and can only know whether or not it can be found/reached. If this is not the case, can you give a bit more context to help us reproduce this? Thanks!

**Comment by daviddob** [comment]
Can confirm we have encountered the same behavior if we try to create a storage account with a `virtual_network_subnet_ids` config that is invalid. For instance, trying to create a storage account in `eastus2` that references a subnet id from `eastus` results in a 404 configuring blob_properties instead of a failure message regarding the creation of the storage account itself. This leads to confusion as to the nature of the error message. The storage account is not created and thus the 404 presents itself. I'd be happy to provide additional debugging info if it proves helpful to RCA.

**Comment by anhdle14** [comment]
Also experienced the same issue, and here is the code

```hcl
  network_rules = {
    bypass = ["AzureServices"]
    default_action = "Allow"
    ip_rules = []
    virtual_network_subnet_ids = [
      "some_vnet_ids_that_in_a_different_region_than_what_specified_in_storage_account_region"
    ]
  }
```

Received a confusing 404 for storage account not found when using resource {}. Fixed it by just removing the vnet_subnet_ids argument.

**Comment by maciej-skorupka** [comment]
I confirm the same problem. It would be nice to just see a better error log.

**Comment by infa-svikyath** [comment]
Have encountered same issue recently
