### ISSUE TITLE
outbound_network_access_restrited setting for azurerm_cognitive_account

### ISSUE THREAD

**Issue by mikemowgli** [hashicorp/terraform-provider-azurerm#12624]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_cognitive_account`

### Terraform Configuration Files

the setting `outbound_network_access_restrited` should be renamed `outbound_network_access_restricted` both in the code and the doc.

**Comment by katbyte** [comment]
rename has been toggled on in 3.0
