### ISSUE TITLE
"Resource has changed outside of Terraform"

### ISSUE THREAD

**Issue by roy-work** [hashicorp/terraform-provider-azurerm#12631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
» terraform -v
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.4.0
+ provider registry.terraform.io/hashicorp/azurerm v2.52.0
```
But note this is running on TFE:
```
Terraform v0.15.5
```

### Affected Resource(s)

* `azurerm_resource_group`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name = "example"
  location = "East US"
}
```

### Expected Behaviour

No output; the resource hasn't changed.

### Actual Behaviour

```
Note: Objects have changed outside of Terraform

  # azurerm_resource_group.example has been changed
  ~ resource "azurerm_resource_group" "example" {
        id       = "/subscriptions/uuid/resourceGroups/example"
        name     = "example"
      + tags     = {}
        # (1 unchanged attribute hidden)
    }
    
No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

1. `terraform plan`

Not entirely sure how I accomplished this, however.

### Important Factoids

We are running on TFE.

There are no tags on the actual resource file. There are no tags listed in the `.tf` code, and even if I add `tags = {}`, it doesn't go away.

We have other RGs, using basically the same TF (no `tags` in the TF code, and no tags in the actual infra), but they are not effected by this.

I think this boils down to the state file: for a "normal" RG that does not get flagged with this, we have,
```
    {
      "mode": "managed",
      "type": "azurerm_resource_group",
      "name": "not_example",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "/subscriptions/uuid/resourceGroups/not-example",
            "location": "eastus",
            "name": "not-example",
            "tags": {},
            "timeouts": null
          },
          …
        ]
      …
    }
```

But for our effected RG:
```
    {
      "mode": "managed",
      "type": "azurerm_resource_group",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "/subscriptions/uuid/resourceGroups/example",
            "location": "eastus",
            "name": "example",
            "tags": null,
            "timeouts": null
          },
```

Here we can see that `tags` are null, which seems to explain the diff. But since TF doesn't plan any actions during the `terraform plan`, I'm sort of at a loss as to how to fix this, aside from seeing if I can manually edit the state file, but that seems both unwise, and I'm not even sure if that's possible w/ TFE.

**Comment by aristosvo** [comment]
I'd expect that `terraform apply -refresh-only` should "fix" this

**Comment by manicminer** [comment]
@roy-work Could you confirm whether @aristosvo's suggestion corrects the attribute in your statefile? Thanks!

**Comment by roy-work** [comment]
So, that flag (`-refresh-only`) [appears to be completely undocumented?](https://www.terraform.io/docs/cli/commands/apply.html) It'd just be nice to understand the consequences of running it.

I ran it, it emitted a bunch of "Refreshing state" lines, and then failed with:
```
╷
│ Error: Invalid refresh-only plan
│
│ Terraform generated planned resource changes in a refresh-only plan. This is a bug in Terraform.
╵
```

However, yes, it does look like subsequent plans no long include `tags` in their difference.

**Comment by aristosvo** [comment]
It is documented [here](https://www.terraform.io/docs/cli/commands/refresh.html) and replaced `terraform refresh`.

Glad it helped, not sure about the errors thrown..

**Comment by tombuildsstuff** [comment]
@roy-work I think there's two separate issues here, one in Terraform Core and one in the Provider where we flatten tags. I've got a theory on the Provider issue, but would it be possible to confirm something that for me:

For the affected Resource Group could you:

1. Navigate to: https://resources.azure.com
2. Select the correct tenant at the top of the screen
3. Navigate (on the left) to Subscriptions -> [Name] -> resourceGroups -> [Name]
4. Copy/Paste the JSON output (sanitising the UUID/name if necessary) here.

My guess is that `tags` is being returned as `null` in the API response here, which is why [when these get flattened in Terraform](https://github.com/terraform-providers/terraform-provider-azurerm/blob/82bddc610fbb606be34203f4c16a00dd25b1f56f/azurerm/internal/tags/flatten.go#L11) the Tags are null and not `{}` - which should be possible to fix in the Flatten function (defaulting the size of the map to `0` rather than the length of the tags) - but it'd be good to confirm this first.

Thanks!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
