### ISSUE TITLE
App Service dotnet_framework_version doesn't seem to get applied when deployed to ASE v2

### ISSUE THREAD

**Issue by CaptainStealthy** [hashicorp/terraform-provider-azurerm#12671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/azurerm v2.63.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.1
```

### Affected Resource(s)

* `azurerm_app_service`
* `azurerm_app_service_environment`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "app" {
  name                = "isolated-web-app"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  app_service_plan_id = azurerm_app_service_plan.asp.id
  tags                = var.tags
  https_only          = true

  site_config {
    dotnet_framework_version = "v5.0"
    min_tls_version          = "1.2"
  }
}

resource "azurerm_app_service_plan" "asp" {
  name                       = "isolated-asp"
  location                   = azurerm_resource_group.rg.location
  resource_group_name        = azurerm_resource_group.rg.name
  kind                       = "Linux"
  reserved                   = true
  app_service_environment_id = azurerm_app_service_environment.ase.id

  sku {
    tier = "Isolated"
    size = "I1"
    capacity = 1
  }
}

resource "azurerm_app_service_environment" "ase" {
  name                         = "isolated-ase"
  subnet_id                    = azurerm_subnet.subnet.id
  pricing_tier                 = "I1"
  front_end_scale_factor       = 5
  internal_load_balancing_mode = "Web, Publishing"

  cluster_setting {
    name  = "DisableTls1.0"
    value = "1"
  }
}

resource "azurerm_subnet" "subnet" {
  name                 = "app-subnet"
  resource_group_name  =   azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = "10.0.0.0/24"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "app-vnet"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  address_space = [
    "10.0.0.0/24"
  ]
}
```

### Debug Output

The resources were created a while ago, and everything deployed successfully, so I can't get a debug output very easily now - not without destroying the resource group, anyway.

### Expected Behaviour

App Service should have the Stack settings set to .NET 5

### Actual Behaviour

Stack settings were completely empty - using the "export template" function of the Azure Portal also generated an ARM template that was missing the `siteConfig.linuxFxVersion` property.

This actually prevented the .NET 5 Web API from starting up - browsing to the site would return a generic Apache 403 Forbidden page, and any other URL would return 404.

After setting the Stack to .NET 5 once using the Azure Portal, the app works fine, and Terraform doesn't report any changes to the infrastructure. The Stack settings only need to be adjusted manually once (effectively the first time you deploy the App Service, you need to manually set the Stack to .NET 5), and subsequent deployments don't require/make any changes.

![image](https://user-images.githubusercontent.com/48744965/126389642-27e19bc1-7960-403e-b7fd-60236de572bf.png)

![image](https://user-images.githubusercontent.com/48744965/126390443-41f8df06-b588-4b15-a9d1-0d32eb04c3d6.png)

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A - Running in Azure public cloud, in the `CanadaCentral` region.

We've deployed many app services with Terraform, and setting the `dotnet_framework_version` to `v5.0` has always worked fine - this is the first instance where we've ever used App Service in an Isolated ASP/ASE.

Let me know if you need any more information.

Thanks!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
