### ISSUE TITLE
azurerm_data_factory_dataset_binary parameters definition

### ISSUE THREAD

**Issue by arnozeelmaekers** [hashicorp/terraform-provider-azurerm#12674]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.2
provider registry.terraform.io/hashicorp/azurerm v2.68.0

### Affected Resource(s)

* `azurerm_data_factory_dataset_binary`

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory_dataset_binary" "madison_dataset_source" {
    name = join("", [var.config.name, "_storageacount_dataset_source"])
    resource_group_name = var.common.resource_group_name
    linked_service_name = azurerm_data_factory_linked_service_data_lake_storage_gen2.madison_storageacount_linkedservice_source.name
    data_factory_name =  var.config.datafactory_name

    parameters = <<PARAMETERS
    {
        "fileSystem": {
            "type": "string"
        },
        "directory":{
            "type": "string"
        }
    }
    PARAMETERS

    azure_blob_storage_location {
        container = "@dataset().fileSystem"
        path = "@dataset().directory"
        filename = "/"
    }
}
```

### Debug Output
```
│ Error: Incorrect attribute value type
│
│   on datafactory.tf line 69, in resource "azurerm_data_factory_dataset_binary" "madison_dataset_source":
│   69:     parameters = <<PARAMETERS
│   70:     {
│   71:         "fileSystem": {
│   72:             "type": "string"
│   73:         },
│   74:         "directory":{
│   75:             "type": "string"
│   76:         }
│   77:     }
│   78:     PARAMETERS
│
│ Inappropriate value for attribute "parameters": map of string required.
```

### Expected Behaviour

The dataset has parameters available for dynamic content entry.

### Actual Behaviour

I'm trying to pass in parameters into an dataset. According to the documentation this should be possible but it's unclear as how this formatting should be. I've tried several thing but all of the return an error. I've seen other people talk about using parameters_values but then I get that this option is not available

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

No.

**Comment by dkutetsky** [comment]
Probably, that's should be some sort of this:
```
  parameters = {
    "fileSystem" :"string"
  }

```

**Comment by arnozeelmaekers** [comment]
Hey @dkutetsky,

Sorry for the late response but yes this was the correct way of doing it. Thanks!
