### ISSUE TITLE
Support for using managed identity in azurerm_stream_analytics_output_blob

### ISSUE THREAD

**Issue by alk-sramond** [hashicorp/terraform-provider-azurerm#12718]
Add authentication by managed identity @ stream_analytics_output_blob
![image](https://user-images.githubusercontent.com/50571972/126800683-a5e203d0-d959-40b5-b380-0ddb5a55246b.png)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently in the azurerm_stream_analytics_output_blob https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/stream_analytics_output_blob it does not seems possible to use identity "Managed identity" as authentication method. (the only authentication available is using storage_account_name + storage_account_key)
cf on azure: 
![image](https://user-images.githubusercontent.com/50571972/126800791-2aa230d7-3945-439e-ab3a-b1b7abc5ab69.png)

Note: Identity was made available for creation in azurerm_stream_analytics_output_blob https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/stream_analytics_job#identity
cf: https://github.com/terraform-providers/terraform-provider-azurerm/pull/12171

An issue was previously open on the topic but only solved adding identity for stream_analytics_job https://github.com/terraform-providers/terraform-provider-azurerm/issues/12096

### New or Affected Resource(s)

azurerm_stream_analytics_output_blob

### Potential Terraform Configuration

-

### References

https://github.com/terraform-providers/terraform-provider-azurerm/pull/12171
https://github.com/terraform-providers/terraform-provider-azurerm/issues/12096
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/stream_analytics_output_blob

**Comment by sikkiv** [comment]
the same is true for `azurerm_stream_analytics_stream_input_eventhub` so would be a good idea to implement that for every input and output possible

**Comment by sikkiv** [comment]
just a follow-up I am getting the following error when changing a Stream Analytics Eventhub Output manually in the portal to "Managed Identity" and then try to run a `terraform apply`:

```bash
Error: converting Output Data Source to a EventHub Output: <nil>
```

**Comment by stephybun** [comment]
Hi @alk-sramond

Thanks for raising this issue. Unfortunately the latest stable version of the SDK that we're using to create stream analytics resources doesn't support managed identities for outputs. I also don't see it in the swagger spec either, so an issue will need to be opened in [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) asking the relevant service team to add it.
