### ISSUE TITLE
azurerm_api_management_named_value doesn't support system managed identity

### ISSUE THREAD

**Issue by allenhumphreys** [hashicorp/terraform-provider-azurerm#12722]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management_named_value`
* provider v2.69.0

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_named_value" "my_key" {
  name                = "my-key"
  display_name        = "my-key"

  resource_group_name = module.apim_service.resource_group_name
  api_management_name = module.apim_service.name

  value_from_key_vault  {
    secret_id = data.azurerm_key_vault_secret.auth0_signing_secret.id
  }

  secret = true

  tags = ["terraform"]
}
```

### Expected Behaviour

The `value_from_key_vault` block should not require `identity_client_id` or it should accept some other indicator of using the system managed identity.

### Actual Behaviour

You must provide the system managed identity's `client_id` (aka Application id), which is not exported from `azurerm_api_management`'s identity block. 

### Important Factoids

Examining the API for a named value created via the portal shows that a null `identityClientId` tells APIM that it should use the system managed ID.

```json
{
  "id": "/subscriptions/<sub>/resourceGroups/<rg>/providers/Microsoft.ApiManagement/service/<apim-service>/namedValues/<named-value-name>",
  "type": "Microsoft.ApiManagement/service/namedValues",
  "name": "named-value-name",
  "properties": {
    "displayName": "blah",
    "keyVault": {
      "secretIdentifier": "https://<my-kv>.vault.azure.net/secrets/<my-secret-name>",
      "identityClientId": null,
      "lastStatus": {
        "code": "Success",
        "timeStampUtc": "2021-07-23T18:49:03.1550771Z"
      }
    },
    "tags": [],
    "secret": true
  }
}
```

### References

* #10416

**Comment by nnnvvvcv** [comment]
@allenhumphreys, did you find any workarounds for this? I'm seeing it too.

**Comment by allenhumphreys** [comment]
@nnnvvvcv I worked around it by looking up the system assigned client IDs and providing them as inputs. This will cause a chicken and egg cycle for new environments. Perhaps @yupwei68 could help out since they implemented the original feature.
