### ISSUE TITLE
HTTP client errors should fail early (and not be retried?)

### ISSUE THREAD

**Issue by Berbe** [hashicorp/terraform-provider-azurerm#12723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```console
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Expected Behaviour
When requests to providers end up in HTTP 4xx (client error), it usually means the error won't solve by itself.

### Actual Behaviour
However, the current client still retries requests until hitting the max attempts:
```
[...]
Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="ValidationError"
[...]
```

### References
* [hashicorp/terraform#29231](https://github.com/hashicorp/terraform/issues/29231)

**Comment by tombuildsstuff** [comment]
hi @Berbe 

Thanks for opening this issue.

Taking a look through here this appears to be a bug in the Azure SDK for Go (or specifically, it's base layer `Azure/go-autorest`) - as such this'll need to be patched there.

Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained. Since we’ve determined that the described behavior is a bug in the Azure SDK for Go, and there is nothing to be done on our side, I am going to close this issue.
