### ISSUE TITLE
Support for --allow-cross-tenant-replication on azurerm_storage_account

### ISSUE THREAD

**Issue by kevinharing** [hashicorp/terraform-provider-azurerm#12749]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support --allow-cross-tenant-replication on azurerm_storage_account (https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az_storage_account_create)

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "example" {
  name                           = "storageaccountname"
  resource_group_name            = azurerm_resource_group.example.name
  location                       = azurerm_resource_group.example.location
  account_tier                   = "Standard"
  account_replication_type       = "GRS"
  allow_cross_tenant_replication = false

  tags = {
    environment = "staging"
  }
}
```

### References

* https://docs.microsoft.com/en-us/cli/azure/storage/account?view=azure-cli-latest#az_storage_account_create

**Comment by pathob** [comment]
Can be closed: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#cross_tenant_replication_enabled

**Comment by tombuildsstuff** [comment]
Closing per above - this is available as `cross_tenant_replication_enabled` - thanks @pathob
