### ISSUE TITLE
Updating new version of openapi spec does not update azurerm_api_management_api resource

### ISSUE THREAD

**Issue by chdalski** [hashicorp/terraform-provider-azurerm#12757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management_api`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "some_api" {
  name                  = "some_api_name"
  resource_group_name   = var.resource_group_name
  api_management_name   = azurerm_api_management.my_apim.name
  revision              = "1"
  display_name          = "Some API"
  path                  = data.azurerm_function_app.some_function.name
  protocols             = ["https"]
  subscription_required = true

  # sample openapi import
  import {
    content_format = "openapi-link"
    content_value  = "https://${data.azurerm_storage_account.openapispecs.primary_web_host}/some_function/openapi_spec.yaml"
    # Workaround to update openapi_spec
    # content_value  = "https://${data.azurerm_storage_account.openapispecs.primary_web_host}/some_function/openapi_spec.yaml${timestamp()}"
  }
}
```

### Expected Behaviour

I would have assumed the resource would be updated if the import file (https://${data.azurerm_storage_account.openapispecs.primary_web_host}/some_function/openapi_spec.yaml) changes.

### Actual Behaviour
The resource is not updated even if the import file changes.

### Steps to Reproduce
1. `Create a azurerm_api_management_api resource with openapi-link import`
2. `terraform apply`
3. `Update the import file`
4. `terraform apply`

**Comment by bizintelligence** [comment]
Hi, 

Thanks for reporting this issue. We have been facing the same issue. Just wondering, if you had heard from them or found any resolution since your reported. 

Cheers

**Comment by chdalski** [comment]
Hi @bizintelligence,

there is no update/solution so far.

**Comment by AyeJayAA** [comment]
We also ran across this issue and used a similar workaround to OP.  We added "?${timestamp()}" to the end of our OpenAPI URL to force the openAPI import on every run to pick up any changes.  Not ideal but without deeper tracking within the state file of the contents of the openAPI doc, not sure how else TF would be aware of changes to the document.

**Comment by AyeJayAA** [comment]
Potentially a lifecycle attibute to "always import" or another boolean in the Azurerm_api_management_api import block to "always import" could be a solution.

**Comment by jtmackoy** [comment]
TF run validation from @AyeJayAA's comments above:
![image](https://user-images.githubusercontent.com/7025779/146421643-da3c09ad-3600-465c-89a0-980c0ebad9ff.png)

**Comment by ssunkari** [comment]
Think you need to bump the revision attribute for APIM to reload the definition.

**Comment by AyeJayAA** [comment]
> Think you need to bump the revision attribute for APIM to reload the definition. `revision = "2"`

Yes, this was the solution we used.  It was just easier for us to use the current date/time as our revision number to make sure the number would be unique for each run and wouldnt need to be tracked.  Not to mention we had tracking in our logs of the last time the API was imported.

**Comment by chdalski** [comment]
> Think you need to bump the revision attribute for APIM to reload the definition. `revision = "2"`

**Comment by ssunkari** [comment]
@AyeJayAA I recently bumped into this scenario. You have to be careful updating the revision as it will destroy and recreate the api definition which will result in api downtime during terraform apply. I instead went with wildcard routing solution. Below is how it looks. Below code passes the endpoint calls and shouldnt ever need to worry about new additions or deletions. Only downside is you cannot apply any transformations at the APIM level to the operations.

resource "azurerm_api_management_api_operation" "apim_operations_wildcard" {
  for_each            = toset(["POST", "GET", "PUT", "DELETE", "HEAD", "OPTIONS", "PATCH", "TRACE"]) 
  method              = each.value
  url_template        = "/*"
  operation_id        = "${each.value}-Wildcard"
  display_name        = "${each.value} User Operation"
  description         = "This can only be done by the logged in user."
  api_management_name = data.azurerm_api_management.apim.name
  api_name            = azurerm_api_management_api.apim_api.name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name
}

**Comment by ssunkari** [comment]
You can also have multiple configurations. I switched off the open_api spec definitions using below code
```  #Adding openAPI import feature will result in outages during deployments when docs needs updating #Refer Revision field
  dynamic "import" {
    for_each = local.apim_import_openapi_definition ? [var.apim_api_config] : []
    content {
      content_format = "openapi-link"
      content_value  = "https://${azurerm_function_app.function_app.default_hostname}/${var.apim_api_config.path}/swagger.json?format=json"
    }
  }```
