### ISSUE TITLE
CosmosDB Periodic backup validation on terraform plan / valid default values

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#12750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform v1.0.3
azurerm v2.69.0

### Affected Resource(s)

cosmosdb_account

### Expected Behaviour

Validating the `backup` block as part of terraform plan command, or at least providing a valid default values. 

### Actual Behaviour

When the `backup` block of `cosmosdb_account` is defined and the `type` is set to `Periodic`, while `interval_in_minutes` is missing, the terraform plan command finishes successfully, but terraform apply fails with:
`Error creating/updating CosmosDB Account "<account_name>" (Resource Group "<RG_name>"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Requested BackupIntervalInMinutes 0 should be a value between 60 and 1440
ActivityId: <...>, Microsoft.Azure.Documents.Common/2.14.0"`

### Steps to reproduce:

`  backup {
    type = "Periodic"
    retention_in_hours = 16
  }`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
