### ISSUE TITLE
Azure Service bus "azurerm_servicebus_queue_authorization_rule" : Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by dilipdesingaon** [hashicorp/terraform-provider-azurerm#12768]
###  Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

###  Description

Whenever I run the terrafrom apply on the resource "azurerm_servicebus_queue_authorization_rule" , I'm getting the Error saying "Provider produced inconsistent result after apply". The full error as follows. This eventually stops the deployment fo the service bus. 

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.service-bus.azurerm_servicebus_queue_authorization_rule.reader["auth_rule_sender_1"],
│ provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### New or Affected Resource(s)

azurerm_servicebus_queue_authorization_rule 

### Terraform (and AzureRM Provider) Version
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0

### Terraform Configuration Files

resource "azurerm_servicebus_queue_authorization_rule" "reader" {
  name                = "testreader"  
  resource_group_name = var.resource_group
  namespace_name      = azurerm_servicebus_namespace.servicebus_namespace.name
  queue_name          = "sbqueue2"  
  listen = true 
  send   = false   
  manage = false 
}

### Debug Output

X-Ms-Request-Server-Encrypted: true
X-Ms-Version: 2018-11-09
2021-07-28T14:34:46.989+0100 [DEBUG] Azure Backend Request: 
PUT /tfstate/pipeline-azure-service-bus-module-dev.terraform.tfstateenv%AZP253Adev?comp=lease HTTP/1.1
Host: sasitpeu2di1azgdevops01.blob.core.windows.net
User-Agent: Terraform/1.0.3 VSTS_b6d1e9ae-2152-491f-8c1b-60b0bc39cbfc_build_2462_0
Content-Length: 0
X-Ms-Date: Wed, 28 Jul 2021 13:34:46 GMT
X-Ms-Lease-Action: release
X-Ms-Lease-Id: 59eed5da-150f-bd99-6f26-3a580f25720e
X-Ms-Version: 2018-11-09
Accept-Encoding: gzip

2021-07-28T14:34:47.002+0100 [DEBUG] Azure Backend Response for https://sasitpeu2di1azgdevops01.blob.core.windows.net/tfstate/pipeline-azure-service-bus-module-dev.terraform.tfstateenv%AZP253Adev?comp=lease: 
HTTP/1.1 200 OK
Content-Length: 0
Date: Wed, 28 Jul 2021 13:35:25 GMT
Etag: "0x8D951CC8F01E594"
Last-Modified: Wed, 28 Jul 2021 13:35:26 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
X-Ms-Request-Id: 7e8e7336-901e-0050-32b5-83cd9a000000
X-Ms-Version: 2018-11-09
2021-07-28T14:34:47.003+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2021-07-28T14:34:47.016+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.69.0/linux_amd64/terraform-provider-azurerm_v2.69.0_x5 pid=14265
2021-07-28T14:34:47.016+0100 [DEBUG] provider: plugin exited

##[warning]%AZP25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
##[warning]%AZP25 detected in ##vso command. In March 2021, the agent command parser will be updated to unescape this to %. To opt out of this behavior, set a job level variable DECODE_PERCENTS to false. Setting to true will force this behavior immediately. More information can be found at https://github.com/microsoft/azure-pipelines-agent/blob/master/docs/design/percentEncoding.md
Finishing: Terraform apply

### Expected Behaviour
 
Terraform apply should create  azurerm_servicebus_queue_authorization_rule and it should not give any errors. 

### Actual Behaviour

│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.service-bus.azurerm_servicebus_queue_authorization_rule.reader["auth_rule_sender_1"],
│ provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced
│ an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to Reproduce

1. Create a Service bus and Service bus  authorization_rule resources from terrafrm. (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_queue_authorization_rule)
2. Run Terraform Apply 

### important Factoids:

I have tried all the latest provider and the latest terraform versions but the issue is still the same.

Some of the provider and the terraform vesions i have tried as below.

v0.14.5 and v2.57.0
v0.15.0 and v2.57.0
v0.15.0 and 2.58.0
Also i have tried few other combinations but it didn't seems to be working.
Any suggestions will be really helpful.

**Comment by dilipdesingaon** [comment]
Hi Everyone, 
Is there anyone got any idea about this issue.? thanks in advance.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
