### ISSUE TITLE
azurerm_log_analytics_linked_service tags not supported

### ISSUE THREAD

**Issue by krowlandson** [hashicorp/terraform-provider-azurerm#12777]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.3
AzureRM provider v2.69.0
```
### Affected Resource(s)

* `azurerm_log_analytics_linked_service`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.69.0"
    }
  }
}

provider "azurerm" {
  features {}
}

locals {
  tags = {
    environment = "testing tags"
  }
}

resource "azurerm_resource_group" "management" {
  name     = "la-test"
  location = "uksouth"
  tags     = local.tags
}

resource "azurerm_log_analytics_workspace" "management" {
  name                = "${azurerm_resource_group.management.name}-workspace"
  location            = azurerm_resource_group.management.location
  resource_group_name = azurerm_resource_group.management.name
  tags                = local.tags
}

resource "azurerm_automation_account" "management" {
  name                = "automation-01"
  location            = azurerm_resource_group.management.location
  resource_group_name = azurerm_resource_group.management.name
  sku_name            = "Basic"
  tags                = local.tags
}

resource "azurerm_log_analytics_linked_service" "management" {
  resource_group_name = azurerm_resource_group.management.name
  workspace_id        = azurerm_log_analytics_workspace.management.id
  read_access_id      = azurerm_automation_account.management.id
  tags                = local.tags
}

```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behaviour

As this resource type doesn't support tags, as per the [Tag support for Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftoperationalinsights) documentation, running `terraform apply` should result in an error.

### Actual Behaviour

Running `terraform apply` multiple times will always complete without errors, but the `azurerm_log_analytics_linked_service` never has the tags applied. As such, subsequent attempt to run `terraform plan` or `terraform apply` will always identify that the tags need to be updated:

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_log_analytics_linked_service.management will be updated in-place
  ~ resource "azurerm_log_analytics_linked_service" "management" {
        id                  = "/subscriptions/<redacted>/resourceGroups/la-test/providers/Microsoft.OperationalInsights/workspaces/la-test-workspace/linkedServices/Automation"
        name                = "la-test-workspace/Automation"
      ~ tags                = {
          + "environment" = "testing tags"
        }
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. Run `terraform apply` multiple times using the sample code from above

### Important Factoids

I've also noticed that if you don't specify the tags argument on this resource at all (this must be omitted when creating the resource for the very first time), I have also witnessed terraform continually outputting the following when subsequently running `terraform apply`:

```shell
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_log_analytics_linked_service.management has been changed
  ~ resource "azurerm_log_analytics_linked_service" "management" {
        id                  = "/subscriptions/<redacted>/resourceGroups/la-test/providers/Microsoft.OperationalInsights/workspaces/la-test-workspace/linkedServices/Automation"
        name                = "Automation"
      + tags                = {}
        # (6 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to these changes.

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

Contrary to the comments from #2670, I believe both of these scenarios are actually due to the fact that this resource type does not support tags, as per the [Tag support for Azure resources](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftoperationalinsights) documentation.

To work-around this issue, you can specify `tags = {}` within the resource block.

I believe that this particular argument should be removed from this resource.

### References

* #2670

**Comment by jtracey93** [comment]
I can also confirm and replicate this: 
![image](https://user-images.githubusercontent.com/41163455/127520976-894a0ce6-76e7-441f-9cb5-3f2733b1ee94.png)

**Comment by krowlandson** [comment]
@jackofallops - just bumping this as I believe this may have been fixed in version 3.x of the provider but not closed.

Using the same code as above but with the latest provider you now get the following error:

```shell
╷
│ Error: Unsupported argument
│
│   on main.tf line 45, in resource "azurerm_log_analytics_linked_service" "management":
│   45:   tags                = local.tags
│
│ An argument named "tags" is not expected here.
╵
```

Removing the offending argument results in a successful apply.

Running `terraform apply` multiple times correctly reports `No changes. Your infrastructure matches the configuration.`

I'll leave this open for now in case there's anything else you want to do / check before closing.
