### ISSUE TITLE
Support for AKS addon azure-keyvault-secrets-provider

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#12783]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support the AKS addon azure-keyvault-secrets-provider

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
azurerm_kubernetes_cluster {
  addon_profile {
    keyvault_secrets {
      enabled = true
      secret_rotation = true
    }
  }  
}
```

### References

https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

**Comment by nerddtvg** [comment]
Even if the provider doesn't support enabling/configuring the Key Vault CSI driver, perhaps only exporting the values would be okay? Referencing the data exported from the `addon_profile` block for that addon is critical for referencing the user assigned managed identity it enables and setting the Key Vault ACLs appropriately.

```json
    "addonProfiles": {
      "azureKeyvaultSecretsProvider": {
        "enabled": true,
        "config": {
          "enableSecretRotation": "true"
        },
        "identity": {
          "resourceId": "/subscriptions/aaaaaaaa-bbbb-cccc-dddd-ffffffffffff/resourcegroups/MC_resource_group/providers/Microsoft.ManagedIdentity/userAssignedIdentities/azurekeyvaultsecretsprovider-name",
          "clientId": "aaaaaaaa-bbbb-cccc-dddd-ffffffffffff",
          "objectId": "aaaaaaaa-bbbb-cccc-dddd-ffffffffffff"
        }
      }
```

Last week, the driver had a pre-release for version v1.0.0 with rc0. The structure and function is probably not going to change much before go-live.

https://github.com/Azure/secrets-store-csi-driver-provider-azure/releases/tag/v1.0.0-rc.0

**Comment by deepak-malhotra** [comment]
The pre-req for Secret store driver is CSI being enabled. CSI is default storage driver from AKS 1.21 and the Secret store driver is also GA since November 2021.
