### ISSUE TITLE
[azurerm_web_application_firewall_policy] Fix max_request_body_size_in_kb, file_upload_limit_in_mb for CRS 3.2

### ISSUE THREAD

**Issue by obolobova** [hashicorp/terraform-provider-azurerm#12817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.7
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0

### Affected Resource(s)

* `azurerm_web_application_firewall_policy`

### Expected Behaviour

https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-waf-configuration#waf-request-size-limits

For CRS 3.2 (on the WAF_v2 SKU) and newer, these limits are as follows:
- 2MB request body size limit
- 4GB file upload limit

### Actual Behaviour

Looks like Terraform still sticks to the old limits.
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.70.0/azurerm/internal/services/network/web_application_firewall_policy_resource.go#L268
```
"file_upload_limit_in_mb": {
	Type:         pluginsdk.TypeInt,
	Optional:     true,
	ValidateFunc: validation.IntBetween(1, 750),
	Default:      100,
},
"max_request_body_size_in_kb": {
	Type:         pluginsdk.TypeInt,
	Optional:     true,
	ValidateFunc: validation.IntBetween(8, 128),
	Default:      128,
},
```

Error returned when trying to exceed the old limit, regardless of CRS 3.2 has been set.
```
Error: expected policy_settings.0.max_request_body_size_in_kb to be in the range (8 - 128), got 248

  on .terraform\modules\waf_policy\waf-policy-module\waf_policy.tf line 62, in resource "azurerm_web_application_firewall_policy" "this":
  62:     max_request_body_size_in_kb = var.policy_settings.max_request_body_size_in_kb
```

**Comment by favoretti** [comment]
@tombuildsstuff Shall we just raise the limits and let people figure out version dependency or turn validation into a version-specific function?

**Comment by rafabu** [comment]
bumped into the same issue - meanwhile on provider `azurerm v2.83.0`.
Unfortunate as the possibility to increase the sizes were one of the main reasons that made usmove to WAF policies from `azurerm_application_gateway: waf_configuration` and OWASP Rule Set 3.2.

**Comment by varnav** [comment]
max_request_body_size_in_kb is fixed while file_upload_limit_in_mb is not.

https://github.com/hashicorp/terraform-provider-azurerm/pull/14369

**Comment by lonegunmanb** [comment]
Hi @varnav , solid copy!
