### ISSUE TITLE
azurerm_bot_connection: tags could not be converged

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#12819]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```
### Affected Resource(s)

* `azurerm_bot_connection`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "random_pet" "example" {}

resource "azurerm_resource_group" "example" {
  name     = format("%s-rg", random_pet.example.id)
  location = "West Europe"
}

resource "azurerm_bot_channels_registration" "example" {
  name                = format("%s-bot", random_pet.example.id)
  location            = "global"
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "F0"
  microsoft_app_id    = data.azurerm_client_config.current.client_id
}

resource "azurerm_bot_connection" "example" {
  name                  = format("%s-bot-connection", random_pet.example.id)
  bot_name              = azurerm_bot_channels_registration.example.name
  location              = azurerm_bot_channels_registration.example.location
  resource_group_name   = azurerm_resource_group.example.name
  service_provider_name = "box"
  client_id             = "exampleId"
  client_secret         = "exampleSecret"

  tags = { "test" = "true" }
}

```

### Expected Behaviour

After terraform apply, plan should not produce any diffs.

### Actual Behaviour
```hcl
Terraform will perform the following actions:

  # azurerm_bot_connection.example will be updated in-place
  ~ resource "azurerm_bot_connection" "example" {
        id                    = "/subscriptions/3c35ede8-4cb5-405d-9e87-ad8f429bb600/resourceGroups/keen-sawfly-rg/providers/Microsoft.BotService/botServices/keen-sawfly-bot/connections/keen-sawfly-bot-connection"
        name                  = "keen-sawfly-bot-connection"
      ~ tags                  = {
          + "test" = "true"
        }
        # (7 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform apply -auto-approve`
3. `terraform plan`

**Comment by jackofallops** [comment]
Hi @t3mi - Could you try that with the tags block as:
```hcl
resource "azurerm_bot_connection" "example" {
  name                  = format("%s-bot-connection", random_pet.example.id)
  bot_name              = azurerm_bot_channels_registration.example.name
  location              = azurerm_bot_channels_registration.example.location
  resource_group_name   = azurerm_resource_group.example.name
  service_provider_name = "box"
  client_id             = "exampleId"
  client_secret         = "exampleSecret"

  tags = { 
    test = "true" 
  }
}
```

**Comment by jackofallops** [comment]
Hi @t3mi - Please disregard my last response, I just checked the API and whilst tags are exposed they're not actually configurable on the resource (they're silently ignored), so shouldn't be used.

**Comment by lonegunmanb** [comment]
It seems like an service side issue.

I've record http requests and responses via fiddler, here's my PUT request:

PUT https://management.azure.com/subscriptions/###########/resourceGroups/<botconnectionname>/providers/Microsoft.BotService/botServices/<rg>/connections/<botconnection>?api-version=2021-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.16.6 (amd64-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.6.0 botservice/2021-03-01 HashiCorp Terraform/1.0.11 (+https://www.terraform.io) Terraform Plugin SDK/2.7.0 terraform-provider-azurerm/2.70.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 197
Authorization: Bearer 
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: 0895e68c-239e-95a5-1a74-08d8c3cdcefd
Accept-Encoding: gzip

{"kind":"bot","location":"global","properties":{"clientId":"exampleId","clientSecret":"exampleSecret","scopes":"","serviceProviderId":"#############"},"tags":{"test":"true"}}

The response is here:

HTTP/1.1 201 Created
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 763
Content-Type: application/json; charset=utf-8
Expires: -1
ETag: W/"c1f53469eb14f140820d0b46147b2fc111/22/2021 5:55:51 AM"
x-ms-request-id: 9b267ccf-5d3d-4772-953a-25b7c06e0a06
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-correlation-request-id: 0895e68c-239e-95a5-1a74-08d8c3cdcefd
x-ms-routing-request-id: SOUTHEASTASIA:20211122T055551Z:f5e4efd4-e782-428a-bbfe-9bc11498277e
X-Content-Type-Options: nosniff
Date: Mon, 22 Nov 2021 05:55:50 GMT

{"id":"/subscriptions/###########/resourceGroups/<botconnectionname>/providers/Microsoft.BotService/botServices/<rg>/connections/<botconnection>","name":"<rg>/<botconnection>","type":"Microsoft.BotService/botServices/connections","etag":"W/\"c1f53469eb14f140820d0b46147b2fc111/22/2021 5:55:51 AM\"","location":"global","properties":{"settingId":"7a08e553-fcf6-7641-a101-04d716afde1d_b6f2f4f3-4df3-aac4-2882","clientId":"exampleId","clientSecret":"exampleSecret","scopes":null,"serviceProviderId":"###########","serviceProviderDisplayName":null,"parameters":[{"key":"clientId","value":"exampleId"},{"key":"clientSecret","value":"exampleSecret"},{"key":"scopes","value":""}],"provisioningState":"Succeeded"},"zones":[]}

Then if I read this connection by a HTTP GET:

GET https://management.azure.com/subscriptions/###########/resourceGroups/<botconnectionname>/providers/Microsoft.BotService/botServices/<rg>/connections/<botconnection>?api-version=2021-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.16.6 (amd64-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/v55.6.0 botservice/2021-03-01 HashiCorp Terraform/1.0.11 (+https://www.terraform.io) Terraform Plugin SDK/2.7.0 terraform-provider-azurerm/2.70.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Authorization: Bearer 
X-Ms-Correlation-Request-Id: e6a353c4-d85d-5089-1e95-ef04ab6891e5
Accept-Encoding: gzip


The response is:

HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
ETag: W/"1ba881a855f227693537dc2135b5ec6711/22/2021 6:03:14 AM"
Vary: Accept-Encoding,Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 11997
x-ms-request-id: cb1f361f-421d-4dfc-8193-dfcdb31f5dcd
Strict-Transport-Security: max-age=31536000; includeSubDomains
x-ms-correlation-request-id: e6a353c4-d85d-5089-1e95-ef04ab6891e5
x-ms-routing-request-id: SOUTHEASTASIA:20211122T060314Z:38740ae3-0d1c-4f82-bd95-e79f34983dc8
X-Content-Type-Options: nosniff
Date: Mon, 22 Nov 2021 06:03:14 GMT
Content-Length: 741

{"id":"/subscriptions/###########/resourceGroups/<botconnectionname>/providers/Microsoft.BotService/botServices/<rg>/connections/<botconnection>","name":"<rg>/<botconnection>","type":"Microsoft.BotService/botServices/connections","etag":"W/\"1ba881a855f227693537dc2135b5ec6711/22/2021 6:03:14 AM\"","location":"global","properties":{"settingId":"7a08e553-fcf6-7641-a101-04d716afde1d_b6f2f4f3-4df3-aac4-2882","clientId":"exampleId","clientSecret":null,"scopes":null,"serviceProviderId":"###########","serviceProviderDisplayName":null,"parameters":[{"key":"clientId","value":"exampleId"},{"key":"clientSecret","value":null},{"key":"scopes","value":""}],"provisioningState":"Succeeded"},"zones":[]}

There's no tags in GET response, which tags was defined in [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json#L1170). I've asked the service team about that, hope we can get an answer.

**Comment by yeze322** [comment]
Confirmed the logic in Azure Bot Service source code. It should be a service-side issue.

In detail, the [`Resource`](https://github.com/Azure/azure-rest-api-specs/blob/be8b6e1fc69e7c2700847d6a9c344c0e204294ce/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json#L1147) entity referenced in "allOf" of [`ConnectionSetting`](https://github.com/Azure/azure-rest-api-specs/blob/be8b6e1fc69e7c2700847d6a9c344c0e204294ce/specification/botservice/resource-manager/Microsoft.BotService/stable/2021-03-01/botservice.json#L2404) was not fully constructed as a part of the response value in this controller `"/providers/Microsoft.BotService/botServices/{resourceName}/connections"`. It resulted in the response of this GET api contains a subset of Swagger defined properties, some properties might be missing including the `tags` property.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
