### ISSUE TITLE
azurerm_kubernetes_cluster / add argument "enable public fqdn"

### ISSUE THREAD

**Issue by flbla** [hashicorp/terraform-provider-azurerm#12856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add this parameter : --enable-public-fqdn 
https://docs.microsoft.com/en-us/azure/aks/private-clusters#create-a-private-aks-cluster-with-a-public-dns-address
to be able to create private cluster with public fqdn

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
private_cluster_enable_public_fqdn
```
This parameter, is only useful with Private AKS cluster

### References

**Comment by tombuildsstuff** [comment]
Support for this is being tracked in #12780
