### ISSUE TITLE
azurerm_network_watcher_flow_log can generate an invalid name

### ISSUE THREAD

**Issue by w0ut0** [hashicorp/terraform-provider-azurerm#12861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `hashicorp/azurerm v2.70.0`
* Terraform v0.15.5

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "my-super-loong-long-long-rg-with-hyphens"
  location = "West Europe"
}

resource "azurerm_network_security_group" "test" {
  name                = "my-super-long-nsg-with-hyphens"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_network_watcher" "test" {
  name                = "acctestnw"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_storage_account" "test" {
  name                = "acctestsa"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  account_tier              = "Standard"
  account_kind              = "StorageV2"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
}

resource "azurerm_network_watcher_flow_log" "test" {
  network_watcher_name = azurerm_network_watcher.test.name
  resource_group_name  = azurerm_resource_group.test.name

  network_security_group_id = azurerm_network_security_group.test.id
  storage_account_id        = azurerm_storage_account.test.id
  enabled                   = true

  retention_policy {
    enabled = true
    days    = 7
  }

}
```

### Expected Behaviour

azurerm_network_watcher_flow_log should have been created, with a generated name, but not ending in a hyphen

### Actual Behaviour

```
│ Error: Error creating "Flow Log: (Name \"Microsoft.Networkmy-super-loong-long-long-rg-with-hyphensmy-super-long-nsg-with-\" / Network Watcher Name \"NetworkWatcher_westeurope\" / Resource Group \"NetworkWatcherRG\")": network.FlowLogsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidResourceName" Message="Resource name Microsoft.Networkmy-super-loong-long-long-rg-with-hyphensmy-super-long-nsg-with- is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]

```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

My NSG is attached to a Databricks-managed subnet, so it's a pain to recreate the NSG to have a shorter name (without hyphens).

### References

* #11670
* #11587

There doesn't seem to be a check for hyphens [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11670/files#diff-0464f9e7990cb2f9d920399ca4ab5c7f5edf67d079aeb57d0d6c260cce45b284R39)

**Comment by lonegunmanb** [comment]
Hello @w0ut0 , I've tried your code, with a little modification, I changed `location` to `eastasia` and `azurerm_storage_account.test.name` to `zjheacctestsa` and left other parts untouched. The code ran successful on my machine:

```shell
azurerm_network_watcher_flow_log.test: Creation complete after 14s [id=/subscriptions/##########/resourceGroups/my-super-loong
-long-long-rg-with-hyphens/providers/Microsoft.Network/networkWatchers/acctestnw/networkSecurityGroupId/subscriptions/############
76/resourceGroups/my-super-loong-long-long-rg-with-hyphens/providers/Microsoft.Network/networkSecurityGroups/my-super-long-nsg-with-hyphens]

Apply complete! Resources: 5 added, 0 changed, 0 destroyed.
```

Would you please check again whether this code can work under provider version 2.87.0 ? Thanks!

**Comment by magodo** [comment]
@w0ut0 With #15016 being merged, that users are now allowed/required to set the `name` directly. I'm gonna resolve this issue.
