### ISSUE TITLE
Request to have route all option in azurerm_app_service vnet integration

### ISSUE THREAD

**Issue by Pwd9000-ML** [hashicorp/terraform-provider-azurerm#12860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is now a setting to enable or disable "route all" on vnet integration when setting up app services - vnet integration.
The app setting has been made legacy and now has to be set via the vnet integration configuration setting.

warning: The legacy app setting 'WEBSITE_VNET_ROUTE_ALL' is being overridden by the vnetRouteAllEnabled configuration setting.

Is it possible to have this option as part of [site_config](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#site_config) block in the terraform resource?

### New or Affected Resource(s)

* [azurerm_app_service](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service)

### Potential Terraform Configuration

add feature (var type bool) in `site_config` -> `vnet_route_all_enabled`

```hcl

variable "vnetRouteAllEnabled" {
  type = bool
}

resource "azurerm_app_service" "azure_appservice" {
  name                = var.appservice_app_name
  location            = var.location
  resource_group_name = var.resource_group_name
  app_service_plan_id = data.azurerm_app_service_plan.app_service_plan.id

  site_config {
    dotnet_framework_version = var.frameworkVersion
    ftps_state               = var.ftps_state
    always_on                = var.always_on
    websockets_enabled       = var.websockets_enabled
    health_check_path        = var.health_check_path
    vnet_route_all_enabled   = var.vnetRouteAllEnabled
  }
```

**Comment by L-P** [comment]
As `vnetRouteAllEnabled` is set by to `false` by default and overrides
`WEBSITE_VNET_ROUTE_ALL`, there is no way to set this parameter to `true`.

Until this issue is resolved, the workaround is to use the `local-exec` provisioner with the Azure CLI:
```hcl
resource "azurerm_app_service_virtual_network_swift_connection" "example" {
  app_service_id = var.app_service_id
  subnet_id      = var.subnet_id

  provisioner "local-exec" {
    command = "az webapp config set --resource-group ${var.resource_group_name} --name ${var.app_service_name} --vnet-route-all-enabled true"
  }
}
```

**Comment by Pwd9000-ML** [comment]
@L-P 
Yes, that is correct.
This is how we are currently working around the issue for the time moment. Thanks for also sharing here 😃

**Comment by zpbonjour** [comment]
+1

I avoid local provioners at all costs so I put together a quick ARM template for use with azurerm_resource_group_template_deployment that will apply this setting until it can be added to the azurerm_app_service module.

`{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
		"AppServiceName": {
        "type": "String"
        }
	},
    "resources": [
	{
		"name": "[parameters('AppServiceName')]",
		"type": "Microsoft.Web/sites",
		"apiVersion": "2020-12-01",
		"kind": "app,linux,container",
		"location": "Central US",
		"properties": {
			"siteConfig": {
			"vnetRouteAllEnabled": "true"
			}
		}
     }
  ]
}`

(assuming a linux container)
"kind": "app,linux" for a linux app, and "kind": "app" for a windows app.

**Comment by binte** [comment]
Thank you for this @L-P ! 

However, the command exactly as you have, did not work for me! What did the trick was the following command:

 ```
provisioner "local-exec" {
    command = "az webapp config set --resource-group ${var.resource_group_name} --name ${var.app_service_name}  --generic-configurations '{\"vnetRouteAllEnabled\": true}'"
  }
```
