### ISSUE TITLE
when another resource depends on a azurerm_storage_blob, the blob changes from destroy first to create first

### ISSUE THREAD

**Issue by jtesolin** [hashicorp/terraform-provider-azurerm#12862]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version 0.15.5
AzureRM Provider Version 2.68.0

### Affected Resource(s)

* `azurerm_storage_blob`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_blob" "example_blob" {
  name                   = local.example_blob_file_name
  storage_account_name   = data.azurerm_storage_account.example_blob_account.name
  storage_container_name = azurerm_storage_container.example_blob_container.name
  type                   = "Block"
  access_tier            = "Hot"
  source                 = local.local_zip_path
  content_md5            = filemd5(local.local_zip_path)
}

resource "azurerm_app_service" "example_app_service" {
  name                = "example-app-svc"
  location            = data.azurerm_resource_group.example_rg.location
  resource_group_name = data.azurerm_resource_group.example_rg.name
  app_service_plan_id = azurerm_app_service_plan.example_app_service_plan.id

  site_config {
    linux_fx_version         = "NODE|12-lts"
    ftps_state               = "Disabled"
    remote_debugging_enabled = true
  }

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = azurerm_storage_blob.example_blob.url

    # the md5 entry is to force service restart upon deployment
    # adding the version to the url would make this unnecessary 
    "content_md5" = filemd5(local.local_zip_path)
  }
}
```

### Error Message

Error: A resource with the ID "https://exampledevaccount.blob.core.windows.net/example-blob-container/example.zip" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_storage_blob" for more information.

with azurerm_storage_blob.example_blob,
  on azure-blob-storage.tf line 12, in resource "azurerm_storage_blob" "example_blob":
  12: resource "azurerm_storage_blob" "example_blob"

### Expected Behaviour

Ideally, an in-place update, uploading a new version of the blob file ought to happen.  There is an upload option to allow overwriting in the portal without having to delete the existing blob.

If an in-place update isn't possible, then being able to control the creation/deletion order with the lifecycle meta-argument create_before_destroy = false would suffice.  

Then basic use case here is to use a blob as the package for an app service, and to have the deployment of the blob contents done when the contents have changed.

### Actual Behaviour

Setting the blob to update when the contents change using the content_md5 property and referencing a property of the blob from another resource causes the blob to switch to a create before destroy mode, which then will conflict with itself when the contents change.

### Steps to Reproduce

1. `terraform apply`

### References

* n/a

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
