### ISSUE TITLE
azurerm_databricks_workspace forcing replacement for new encryption properties

### ISSUE THREAD

**Issue by crpietschmann** [hashicorp/terraform-provider-azurerm#12882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

  Terraform v0.13.7
  + provider registry.terraform.io/hashicorp/azuread v0.11.0
  + provider registry.terraform.io/hashicorp/azurerm v2.71.0
  + provider registry.terraform.io/hashicorp/local v2.1.0
  + provider registry.terraform.io/hashicorp/null v2.1.2
  + provider registry.terraform.io/hashicorp/random v2.3.1

### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "default" {
  name                = "${local.databricks_workspace.name_prefix}databricks"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = local.resource_location
  sku                 = "premium"

  managed_resource_group_name = local.databricks_workspace.managed_resource_group_name

  custom_parameters {
    no_public_ip        = false
    virtual_network_id  = data.azurerm_virtual_network.vnet.id
    public_subnet_name  = local.azure_primary_vnet_subnet_databricks_public
    private_subnet_name = local.azure_primary_vnet_subnet_databricks_private
  }
}
```

### Panic Output

```
 # module.central_region.azurerm_databricks_workspace.default must be replaced
-/+ resource "azurerm_databricks_workspace" "default" {
      + customer_managed_key_enabled      = false # forces replacement
      ~ id                                = "/subscriptions/***/resourceGroups/dbk-rg/providers/Microsoft.Databricks/workspaces/databricks" -> (known after apply)
      + infrastructure_encryption_enabled = false # forces replacement
        location                          = "eastus2"
      ~ managed_resource_group_id         = "/subscriptions/***/resourceGroups/databricks-rg-dbk-rg" -> (known after apply)
        managed_resource_group_name       = "databricks-rg-dbk-rg"
        name                              = "databricks"
        resource_group_name               = "dbk-rg"
        sku                               = "premium"
      + storage_account_identity          = (known after apply)
      - tags                              = {} -> null
      ~ workspace_id                      = "0000000000000000" -> (known after apply)
      ~ workspace_url                     = "adb-0000000000000000.00.azuredatabricks.net" -> (known after apply)

        custom_parameters {
            no_public_ip        = false
            private_subnet_name = "dbk_private"
            public_subnet_name  = "dbk_public"
            virtual_network_id  = "/subscriptions/***/resourceGroups/NET-rg/providers/Microsoft.Network/virtualNetworks/vnet"
        }
    }

```

### Expected Behaviour

Since we never set the `customer_managed_key_enabled` and `infrastructure_encryption_enabled` properties they should remain defaulted to `false` and not require a forced replacement of the Azure Databricks resource. These properties are already set to `false` by default, and we never changed their values.

The `azurerm_databricks_workspace` provider should just gracefully handle this and update the `.tfstate` accordingly, so that no replacement is necessary. After all, it these properties are defaulting to `false` and they are already set to `false` on the resource in Azure. Updating to use the latest `azurerm` provider version shouldn't require a replacement of the Azure Databricks resource.

### Actual Behaviour

Terraform is requiring the resource be replaced.

It's worth noting that I have multiple environments with the same Terraform code and only 1 of them is requiring the Databricks resource to be replaced. There's a bug that for some reason this one is requiring it, but the others are working as expected.

**Comment by alexott** [comment]
This is really a problem for one of big enterprise customers - customer managed keys for managed services could be enabled on an existing workspace ([doc](https://docs.microsoft.com/en-us/azure/databricks/security/keys/customer-managed-key-managed-services-azure#--step-3-deploy-or-update-workspace-with-your-key)) without recreation of workspace.  The only limitation is that the key will be applied only to newly created notebooks, not to the existing one

**Comment by galaticoso** [comment]
It's also prompting to replace the workspace resource when I execute the plan after upgrade to azurerm v2.99, pointing at `public_network_access_enabled` argument though I left everything as default value.

My workaround is to put it in the `ignore_changes` and it seems to do the trick.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!

**Comment by alexott** [comment]
Update for network settings and CMK is supported since 3.41.0
