### ISSUE TITLE
terraform destroy failed

### ISSUE THREAD

**Issue by fmuntean** [hashicorp/terraform-provider-azurerm#12889]
module.vnet-main.azurerm_subnet_network_security_group_association.vnet["DATA"]: Destroying... [id=/subscriptions/.../resourceGroups/net-rg/providers/Microsoft.Network/virtualNetworks/devVNET/subnets/DATA]
module.vnet-main.azurerm_subnet_network_security_group_association.vnet["APP"]: Destroying... [id=/subscriptions/.../resourceGroups/net-rg/providers/Microsoft.Network/virtualNetworks/devVNET/subnets/APP]
azurerm_shared_image_gallery.sig: Destroying... [id=/subscriptions/.../resourceGroups/net-rg/providers/Microsoft.Compute/galleries/BaseImages]
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.70.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x48a92f7]

goroutine 97 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.resourceSharedImageGalleryDelete(0xc001c7c800, 0x57787e0, 0xc0001cb880, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/shared_image_gallery_resource.go:173 +0x237
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc0002efc00, 0x670a628, 0xc001476580, 0xc001c7c800, 0x57787e0, 0xc0001cb880, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002efc00, 0x670a628, 0xc001476580, 0xc0017e6460, 0xc0015105c0, 0x57787e0, 0xc0001cb880, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0010d0348, 0x670a628, 0xc001476580, 0xc0017d6eb0, 0xc001476580, 0x5c595a0, 0xc000cdff00)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001d38a80, 0x670a6d0, 0xc001476580, 0xc0017e6380, 0xc001d38a80, 0xc000cdffb0, 0xc0012a3ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5c595a0, 0xc001d38a80, 0x670a6d0, 0xc000cdffb0, 0xc00147c540,0x0, 0x670a6d0, 0xc000cdffb0, 0xc00162c780, 0x1dc)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005d01c0, 0x67565b8, 0xc001d54d80, 0xc0010d6d80, 0xc001183a40, 0x9cccf80, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0005d01c0, 0x67565b8, 0xc001d54d80, 0xc0010d6d80, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000c3ef70, 0xc0005d01c0, 0x67565b8, 0xc001d54d80, 0xc0010d6d80)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.70.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

terraform -v
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0

**Comment by WodansSon** [comment]
@fmuntean, thank you for opening this issue. This is a known issue with the new version of auto-rest and the SDK has been made aware of this issue. They have added a fix to the new auto-rest code base, so this should go away once we upgrade the auto-rest version within the azure provider. I am sorry for the inconvenience this may have caused...  

```
if response.WasNotFound(future.Response()) {
```
(related #12852)

**Comment by fmuntean** [comment]
Any ETA on the fix for this issue?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
