### ISSUE TITLE
Updating PostgreSQL Flexible Server HA "standby availability zone" causes recreate

### ISSUE THREAD

**Issue by fcatacut** [hashicorp/terraform-provider-azurerm#12890]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azurerm v2.71.0
```

### Affected Resource(s)

* `azurerm_postgresql_flexible_server `

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "example-rg"
  location = "eastus2"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "example-vnet"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "subnet" {
  name                 = "postgres"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
  delegation {
    name = "postgres"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_private_dns_zone" "private_dns_zone" {
  name                = "example.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "private_dns_zone_vnet_link" {
  name                  = "exampleVnetZone.com"
  private_dns_zone_name = azurerm_private_dns_zone.private_dns_zone.name
  virtual_network_id    = azurerm_virtual_network.vnet.id
  resource_group_name   = azurerm_resource_group.rg.name
}

resource "azurerm_postgresql_flexible_server" "psql" {
  depends_on = [
    azurerm_private_dns_zone_virtual_network_link.private_dns_zone_vnet_link
  ]

  name                = "example-psql"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"
  delegated_subnet_id    = azurerm_subnet.subnet.id
  private_dns_zone_id    = azurerm_private_dns_zone.private_dns_zone.id
  sku_name               = "GP_Standard_D4s_v3"
  storage_mb             = 32768
  version                = 12
  zone                   = 3

  high_availability {
    mode                      = "ZoneRedundant"
    standby_availability_zone = 2
  }

  timeouts {
    create = "10m" # Just so you don't get stuck waiting an hour for this to timeout.
  }
}
```

### Expected Behaviour

I wouldn't expect the existing PostgreSQL Flexible Server to be recreated since the standby (and not the primary) zone is what's getting updated. Similarly, when the PostgreSQL Flexible Server is initially provisioned with HA disabled, enabling HA with `standby_availability_zone` set to a non-null value is also causing a recreate.

### Actual Behaviour

Updating `standby_availability_zone` results in a plan where the PostgreSQL Flexible Server is recreated.

```hcl
Terraform will perform the following actions:

  # azurerm_postgresql_flexible_server.psql must be replaced
-/+ resource "azurerm_postgresql_flexible_server" "psql" {
      ~ backup_retention_days         = 7 -> (known after apply)
      + cmk_enabled                   = (known after apply)
      ~ fqdn                          = "example-psql.postgres.database.azure.com" -> (known after apply)
      ~ id                            = "/subscriptions/****/resourceGroups/example-rg/providers/Microsoft.DBforPostgreSQL/flexibleServers/example-psql" -> (known after apply)
        name                          = "example-psql"
      ~ public_network_access_enabled = false -> (known after apply)
      - tags                          = {} -> null
        # (10 unchanged attributes hidden)

      ~ high_availability {
          ~ standby_availability_zone = "2" -> "1" # forces replacement
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

```

### Steps to Reproduce

1. `terraform apply`.
2. Update the `standby_availability_zone` value from `2` to `1`.
3. `terraform plan`

**Comment by yupwei68** [comment]
Hi @fcatacut , thanks for opening this issue.
`standby_availability_zone` is not updatable currently from service side.
If you want to enable HA without recreating the server, you need not to assign the `standby_availability_zone`, and the system will assign one default value for it.

```
  high_availability {
    mode                      = "ZoneRedundant"
  }
```

**Comment by fcatacut** [comment]
@ yupwei68 thank you for the clarification. Would it be worthwhile for me to submit a PR to update the documentation to reflect this, or do you anticipate update support in the near future?

**Comment by nkm269** [comment]
Initally i enabled HA and ran terraform apply.
Later i want to disable HA .When i run terraform apply.getting below error



 Error: `zone` and `high_availability.0.standby_availability_zone` should only be either exchanged with each other or unchanged
│
│   with azurerm_postgresql_flexible_server.iopostgresdemo,
│   on main.tf line 53, in resource "azurerm_postgresql_flexible_server" "iopostgresdemo":
│   53: resource "azurerm_postgresql_flexible_server" "iopostgresdemo" {
│
Here is my code


variable "postgres-resourcegroup" {
type = string
description = "Resource group name"
}

variable "postgres-location" {
type = string
description = "Location of the resource"
}

variable "postgres-location" {
type = string
description = "Location of the resource"
}

resource "azurerm_resource_group" "tf-postgres" {
name = var.postgres-resourcegroup
location = var.postgres-location
}

resource "random_password" "postgresadminpassword" {
length = 16
special = true
override_special = "_%@"

}

resource "azurerm_postgresql_flexible_server" "iopostgresdemo" {
  name                   = "iopostgresdemo"
  resource_group_name    = azurerm_resource_group.tf-postgres.name
  location               = azurerm_resource_group.tf-postgres.location
  version                = "13"
  administrator_login    = "postgres_admin"
  administrator_password = random_password.postgresadminpassword.result
  storage_mb = 65536
  sku_name   = "GP_Standard_D2s_v3"
  zone = "1" 
dynamic high_availability {

for_each = var.ha_var == yes ? [1] : []
content {
    mode                      = "ZoneRedundant"
    standby_availability_zone = "2"
  }
}
 }

**Comment by hungryengineer** [comment]
I am also getting the blow when I change from high availability Error: `zone` and `high_availability.0.standby_availability_zone` should only be either exchanged with each other or unchanged
any explanations?

**Comment by fcatacut** [comment]
Once HA is enabled, I don't believe that it can be disabled. The only allowed update is to "swap" the `zone` and `high_availability.0.standby_availability_zone` value.

**Comment by PedroEss** [comment]
I had this issue and it was gone when I added below lifecycle:
    lifecycle {
    ignore_changes = [
        zone
        ]
    }

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
