### ISSUE TITLE
Iot Hub Routes Sources not working as expected

### ISSUE THREAD

**Issue by mgardi85** [hashicorp/terraform-provider-azurerm#12892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are using IOT HUB and the below is the way we are creating it
We are facing issue in the creating routes from terraform script

Terraform version 1.0.2
Azure Provider: 2.69.0. 
`
resource "azurerm_resource_group" "example" {
name = "example-resources-3213"
location = "West Europe"
}

resource "azurerm_iothub" "iot-hub" {
name = "myHub"
resource_group_name = azurerm_resource_group.example.name
location = azurerm_resource_group.example.location

sku {
name = "S1"
capacity = "1"
}
fallback_route {
source = "DeviceMessages"
endpoint_names = ["events"]
enabled = true
}

route {
name = "DeviceUpdate.DigitalTwinChanges"
source = "DigitalTwinChangeEvents"
condition = "true"
endpoint_names = ["events"]
enabled = true
}
dependson =[
azurerm_resource_group.example
]
}
`

The validate command fails with message that the route source value is invalid and needs be to one of 4-5 given values.

_Error: expected route.0.source to be one of [DeviceConnectionStateEvents DeviceJobLifecycleEvents DeviceLifecycleEvents DeviceMessages Invalid TwinChangeEvents], got DigitalTwinChangeEvents._

I am able to create the same route when done from Azure Portal / Az Powershell module.
The possible values available in Azure Portal are as below
- Device Telemetry Messages
- Device Lifecycle Events
- Device Connection State Events
- Device Twin Change Events
- Digital Twin Change Events

Referring to the documentation at [Azure RM documentation] https://registry.terraform.io/providers/hashicorp/azurerm/2.69.0/docs/resources/iothub) the possible values are listed as below

- RoutingSourceInvalid
- RoutingSourceDeviceMessages
- RoutingSourceTwinChangeEvents
- RoutingSourceDeviceLifecycleEvents
- RoutingSourceDeviceJobLifecycleEvents
- DeviceMessages

From the first look it seems there is a mismatch in sources. 
Is there any additional information available for mapping of route source values from tf azure provider to the ones used in azure.

**Comment by catriona-m** [comment]
Hi @mgardi85 thanks for opening this. I tried to add this source as an option but unfortunately it seems it is not currently supported in the api. See: https://docs.microsoft.com/en-us/rest/api/iothub/iot-hub-resource/create-or-update#routingsource

**Comment by catriona-m** [comment]
Sounds like this issue has been resolved and this can be closed now. Thanks!
