### ISSUE TITLE
Support for alias connection strings on [servicebus] resources 

### ISSUE THREAD

**Issue by dylanmorley** [hashicorp/terraform-provider-azurerm#12913]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using azurerm_servicebus_namespace_disaster_recovery_config to build a pairing between two service bus namespaces, namespace, topic and queue service bus resources support an Alias connection string property that represents the CNAME alias over the paired resources. 

If any SAS polices have been created on those resources, those polices will support an alias connection string.

### New or Affected Resource(s)

servicebus_namespace_authorization_rule_data_source
servicebus_namespace_authorization_rule_resource

servicebus_queue_authorization_rule_data_source
servicebus_queue_authorization_rule_resource

servicebus_topic_authorization_rule_data_source
servicebus_topic_authorization_rule_resource_test

### Potential Terraform Configuration

Another two properties on the resources mentioned - 

alias_primary_connection_string
alias_secondary_connection_string

These are available on the AccessKeys response object, like so 

![image](https://user-images.githubusercontent.com/5038454/128759359-ccd98c07-8008-45e2-9339-f215fa6b716a.png)

**Comment by dylanmorley** [comment]
Q- would you always return this property, even when the resources aren't paired? i.e. just return the property with empty string? Or omit properties when not paired?

Happy to pick this up myself

**Comment by tombuildsstuff** [comment]
@dylanmorley

> Q- would you always return this property, even when the resources aren't paired? i.e. just return the property with empty string? Or omit properties when not paired?

Omitting these properties would mean they can't be interpolated, so setting these to an empty string should be fine - but the screenshot above looks good if you get time to send a PR 👍

**Comment by dylanmorley** [comment]
Thanks @tombuildsstuff  - shall do, will get a PR together over the next few days

**Comment by dylanmorley** [comment]
Closed by #12997 and released in [v2.74.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.74.0/CHANGELOG.md)
