### ISSUE TITLE
azurerm_storage_share_file: upload 2.5GB file crashed the plugin 

### ISSUE THREAD

**Issue by morks** [hashicorp/terraform-provider-azurerm#12925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.71.0

### Affected Resource(s)

* `azurerm_storage_share_file`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "doddeployment" {
    name                        = "doddeployment"
    resource_group_name         = var.resource_group
    location                    = var.location 
    account_tier                = "Standard"
    account_replication_type    = "LRS"
}

resource "azurerm_storage_share" "dodcode" {
    name                 = "dodcode"
    storage_account_name = azurerm_storage_account.doddeployment.name
}

resource "azurerm_storage_share_file" "dodplaybooks" {
  name             = "playbooks.tar.gz"
  storage_share_id = azurerm_storage_share.dodcode.id
  source           = "../../ansible/playbooks.tar.gz"
  timeouts {
    create = "45m"
  }
}
```
### Panic Output

```hcl
azurerm_storage_share_file.dodplaybooks: Still creating... [8m30s elapsed]
╷
│ Error: Plugin did not respond
│ 
│   with azurerm_storage_share_file.dodplaybooks,
│   on filestore.tf line 22, in resource "azurerm_storage_share_file" "dodplaybooks":
│   22: resource "azurerm_storage_share_file" "dodplaybooks" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.71.0_x5 plugin:
panic: sync: negative WaitGroup counter

goroutine 588 [running]:
sync.(*WaitGroup).Add(0xc0016615a0, 0xffffffffffffffff)
        /opt/goenv/versions/1.16.6/src/sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(...)
        /opt/goenv/versions/1.16.6/src/sync/waitgroup.go:99
github.com/tombuildsstuff/giovanni/storage/2019-12-12/file/files.Client.PutFile.func1(0x226, 0xc001661598, 0x89659cf7, 0xc001a066e0, 0x73865f8, 0xc000898660, 0xc000976108, 0xd, 0xc00097612c, 0x7, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/tombuildsstuff/giovanni/storage/2019-12-12/file/files/range_put_file.go:52 +0x285
created by github.com/tombuildsstuff/giovanni/storage/2019-12-12/file/files.Client.PutFile
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/tombuildsstuff/giovanni/storage/2019-12-12/file/files/range_put_file.go:40 +0x2f7

Error: The terraform-provider-azurerm_v2.71.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Upload the file to the fileshare

### Actual Behaviour

file upload crashed after 8 minutes 

### Steps to Reproduce

Use the code above to upload a file with 2.5GB

1. `terraform apply`

### Important Factoids

- The size of the file is 2.5GB 
- "location": "West Europe"

**Comment by malcolmtylerfil** [comment]
I too am experiencing the same issue on terraform-provider-azurerm_v2.89.0_x5.exe is this bug going to be worked upon any time soon please?

**Comment by steven-visagie** [comment]
Same problem on azurerm 2.99.0 and tf 1.1.8 when uploading a ~225MB file. Reduced the file size to ~155MB and worked.

**Comment by tombuildsstuff** [comment]
@magodo since you were making related changes to blob uploads recently, any chance you could take a look into this one?

**Comment by magodo** [comment]
@tombuildsstuff This is the same issue as #15895, which is fixed in https://github.com/tombuildsstuff/giovanni/pull/56. Once a new release is made for the giovanni, we can upgrade the dependency and get the issue fixed.

**Comment by tombuildsstuff** [comment]
👍 oh cool, I think that got released yesterday fwiw, let me check

**Comment by tombuildsstuff** [comment]
PR to update the dependencies: https://github.com/hashicorp/terraform-provider-azurerm/pull/16460
