### ISSUE TITLE
Support for enable_infrastructure_encryption attribute in azurerm_storage_account resource

### ISSUE THREAD

**Issue by Kumar1325** [hashicorp/terraform-provider-azurerm#12934]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have a Azure Policy that it only allows Storage Account creation only if it has the "Enable Infrastructure Encryption" ticked. I tried to do the similar thing using terraform but unfortunately the related attribute is not present in azurerm_storage_account resource.
### New or Affected Resource(s)

* azurerm_2.68.0
* terraform_1.0.2

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "example" {
  name                = "storageaccountname"
  resource_group_name = azurerm_resource_group.example.name

  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  enable_infrastructure_encryption = true

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["100.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.example.id]
  }

  tags = {
    environment = "staging"
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
This is available via [the `infrastructure_encryption_enabled` attribute](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#infrastructure_encryption_enabled) in the latest version of the Provider - so closing this out as available
