### ISSUE TITLE
Documentation bug in azurerm_function_app causing Error deleting App Service Plan 409 error

### ISSUE THREAD

**Issue by AnitaErnszt** [hashicorp/terraform-provider-azurerm#12937]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version 1.0.4
AzureRM Version 2.71.0

### Affected Resource(s)
* `azurerm_app_service_plan`
* `azurerm_function_app`

### Terraform Configuration Files
Code is the same as the sample code on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#example-usage-linux

```hcl
resource "azurerm_resource_group" "example" {
  name     = "azure-functions-cptest-rg"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "fupptestsfgfgdffda"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "example" {
  name                = "azure-functions-test-service-plan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "Linux"
  reserved            = true

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "example" {
  name                       = "test-azure-functionsfdd"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  os_type                    = "linux"
}
```

### Expected Behaviour
Terraform apply runs without any issue on consecutive calls as well

### Actual Behaviour
Any consecutive run (for function update, no change or terraform destroy) fails

### Steps to Reproduce
1. copy the code from the documentation
2. `terraform apply`
2. `terraform apply` with no changes - FAILS

### FIX
remove the following bit fixes the problem:
`os_type  = "linux"`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
