### ISSUE TITLE
Support for Verifying IoT hub DPS Certificates (or Auto-Verify)

### ISSUE THREAD

**Issue by kensykora** [hashicorp/terraform-provider-azurerm#12963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There currently is not a method in Terraform to validate the certificate once it's uploaded to DPS. This leaves us with a couple of options to validate it:

 1. Manually through portal (yuck)
 2. Automate the signing / verification part (non-trivial)

In the Azure portal, there is also a checkbox to automatically verify on upload, which such a boolean flag is missing from the `azurerm_iothub_dps_certificate` resource type. It would nice if this resource type supported that boolean flag since it is available on the portal.

![image](https://user-images.githubusercontent.com/64756/129121803-3ebfb6f7-8b9d-419e-b304-63d374ef7d05.png)

Alternately it would be great if it's possible to pass in a key vault reference to the certificate and have that verification step be automatic. Below is a local-exec workaround that does it

This method would have to go through the signing steps as outlined in <https://docs.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates>

### New or Affected Resource(s)

* azurerm_iothub_dps_certificate

### Potential Terraform Configuration

Potential Solution:

(1) Auto Verify on Upload

```hcl
resource "azurerm_iothub_dps_certificate" "intermediate_ca" {
  name                = "mycert"
  resource_group_name = "rg"
  iot_dps_name        = "mydps"

  certificate_content = var.certificate_content_base64

  auto_verify = true
}

```

(2) Actual Verification

```hcl
resource "azurerm_iothub_dps_certificate" "intermediate_ca" {
  name                = "mycert"
  resource_group_name = "rg"
  iot_dps_name        = "mydps"

  certificate_content = var.certificate_content_base64

  key_vault_certificate_secret_id = data.azurerm_key_vault_certificate.intermediate_ca.secret_id
}
```

This Help document has some openssl steps that can be performed: <https://docs.microsoft.com/en-us/answers/questions/163763/how-do-i-generate-a-validation-certificate-from-a.html>, but implementing this directly in Go would be preferred

## Workaround

I was able to write a script that adapts the above steps and introduces it in a `local-exec` provider as a workaround. It requires both openssl and the Java JDK (see comments as to why both)

```hcl
resource "azurerm_iothub_dps_certificate" "intermediate_ca" {
  name                = "mycert"
  resource_group_name = "rg"
  iot_dps_name        = "mydps"

  certificate_content = var.certificate_content_base64

    provisioner "local-exec" {
    environment = {
      KEY_VAULT_CERTIFICATE_SECRET_ID = var.key_vault_certificate_secret_id
      CERT_NAME                       = azurerm_iothub_dps_certificate.intermediate_ca.name
      DPS_NAME                        = var.iot_dps_name
      RESOURCE_GROUP_NAME             = var.resource_group_name # key vault resource group
    }
    command = file("${path.module}/verify-certificate.sh")
  }
}
```

```bash
#!/bin/bash
# Check to see if it's already verified
set -e # Exit on failure
echo "Getting Status..."
STATUS=$(az iot dps certificate show -o json --query properties.isVerified -n $CERT_NAME --dps-name $DPS_NAME -g $RESOURCE_GROUP_NAME)
if [ "$STATUS" = "true" ]; then
echo "Already Verified";
exit 0;
fi 
# Get the certificate
echo "Downloading Cert..."
az keyvault secret download --file cert.pfx --id $KEY_VAULT_CERTIFICATE_SECRET_ID -e base64

# Convert the certificate to a PFX file with a password (openssl cannot deal with PFX files that have a blank passphrase)
# This uses the java SDK `keytool` toolset to add the passphrase to it
echo adding passphrase to PFX
keytool -importkeystore -srckeystore cert.pfx -srcstoretype PKCS12 -srcstorepass '' -deststoretype PKCS12 -deststorepass asdfasdf -destkeystore cert-protected.pfx
rm cert.pfx

# Extract separate files for cert data and private key
echo extracting key
openssl pkcs12 -in cert-protected.pfx -out cert.pem -nodes -passin pass:asdfasdf
openssl pkcs12 -in cert-protected.pfx -nocerts -out key.pem -passin pass:asdfasdf -passout pass:asdfasdf
rm cert-protected.pfx

# Get Verification Code
echo Getting Verification Code
ETAG=$(az iot dps certificate show -o json --query etag -n $CERT_NAME --dps-name $DPS_NAME -g $RESOURCE_GROUP_NAME)
VERIFICATION_CODE=$(az iot dps certificate generate-verification-code -o tsv --query properties.verificationCode -n $CERT_NAME --dps-name $DPS_NAME -g $RESOURCE_GROUP_NAME -e $ETAG)

# Create the CSR to sign the verification code
echo Generating CSR
openssl genrsa -out verification.key 2048
openssl req -new -key verification.key -out verification.csr -subj "/C=US/ST=Virginia/O=MyOrg/CN=$VERIFICATION_CODE"

# Create the cert, sign with the CA
echo Signing Cert
openssl x509 -req -in verification.csr -CA cert.pem -CAkey key.pem -CAcreateserial -out verificationCert.pem -days 1095 -sha256 -passin pass:asdfasdf
echo Waiting 10s to account for clock drift...
sleep 10 # give a few seconds to account for any clock drift
rm cert.pem
rm cert.srl
rm key.pem
rm verification.csr
rm verification.key

# Verify with IoT Hub
echo Verifying with IoT hub
ETAG=$(az iot dps certificate show -o json --query etag -n $CERT_NAME --dps-name $DPS_NAME -g $RESOURCE_GROUP_NAME)
az iot dps certificate verify --path verificationCert.pem --etag $ETAG -n $CERT_NAME --dps-name $DPS_NAME -g $RESOURCE_GROUP_NAME
rm verificationCert.pem
```

### References

* https://docs.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates

**Comment by catriona-m** [comment]
Hi @kensykora thanks for creating this. I had a look at implementing this but it seems it's not currently possible to send CertificateProperties in the request at this time - https://docs.microsoft.com/en-us/rest/api/iot-dps/dps-certificate/create-or-update#request-body

**Comment by kensykora** [comment]
@catriona-m thanks for replying -- yeah you would have to call the verify endpoint after uploading it. 

https://docs.microsoft.com/en-us/rest/api/iot-dps/dps-certificate/verify-certificate

You might consider doing this as a separate resource instead. something like:

```hcl
resource "azurerm_iothub_dps_certificate" "intermediate_ca" {
  name                = "mycert"
  resource_group_name = "rg"
  iot_dps_name        = "mydps"

  certificate_content = var.certificate_content_base64
}

resource "azurerm_iothub_dps_certificate_verification" "intermediate_ca" {
  certificate_id = azurerm_iothub_dps_certificate.intermediate_ca.id

  auto_verify = true
}
```

**Comment by kensykora** [comment]
I know the "auto verify" can be done via the portal, so maybe there is an undocumented API flag. I might reverse engineer the portal call to look at how it's doing it.

**Comment by myc2h6o** [comment]
This seems to be added in the newer api (though the REST API doc is not updated, the [API spec](https://github.com/Azure/azure-rest-api-specs/blob/c5c5e1d0c31a0ceccda42505d6e872ff303d1c80/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2021-10-15/iotdps.json#L1661) has it). I'll test if it can be added.
