### ISSUE TITLE
Public IP Docs

### ISSUE THREAD

**Issue by grtn316** [hashicorp/terraform-provider-azurerm#12979]
The Public IP Docs:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip#ip_version

Have a note saying "Only dynamic IP address allocation is supported for IPv6." for the ip_version property. This should actually be "static" as "dynamic" is not supported.

**Comment by aishwarya128** [comment]
Hi @katbyte ,
I will be working on this issue, if already not worked upon
Thanks

**Comment by stephybun** [comment]
Closed by #14416
