### ISSUE TITLE
can't enable all logs for AAD monitoring

### ISSUE THREAD

**Issue by fmuntean** [hashicorp/terraform-provider-azurerm#12978]
I get the following errors trying to setup the AAD monitoring setup with TerraForm

│ Error: expected log.5.category to be one of [AuditLogs SignInLogs ADFSSignInLogs ManagedIdentitySignInLogs NonInteractiveUserSignInLogs ProvisioningLogs ServicePrincipalSignInLogs], got RiskyUsers
│
│   with azurerm_monitor_aad_diagnostic_setting.aad,
│   on CreateServices.tf line 137, in resource "azurerm_monitor_aad_diagnostic_setting" "aad":
│  137: resource "azurerm_monitor_aad_diagnostic_setting" "aad" {
│
╵
╷
│ Error: expected log.8.category to be one of [AuditLogs SignInLogs ADFSSignInLogs ManagedIdentitySignInLogs NonInteractiveUserSignInLogs ProvisioningLogs ServicePrincipalSignInLogs], got UserRiskEvents

**Comment by tombuildsstuff** [comment]
Fixed via #16534
