### ISSUE TITLE
App Servie Plan creation getting timout

### ISSUE THREAD

**Issue by kfirlevin** [hashicorp/terraform-provider-azurerm#12975]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `Terraform v1.0.4`
* `azurerm v2.71.0`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  location = var.location
  name     = local.rg_name

}

data "azurerm_subnet" "subnet" {
  name                 = var.subnet.subnet_name
  virtual_network_name = var.subnet.vnet_name
  resource_group_name  = var.subnet.resource_group_name
}

variable "ase_list" {
  type = list(string)
}

variable "asp_list" {
  type = list(object({
    name     = string
    ase_name = string
  }))
}

resource "azurerm_app_service_environment" "ase" {


  for_each = toset(local.ase_list)

  name                         = each.key
  subnet_id                    = data.azurerm_subnet.subnet.id
  internal_load_balancing_mode = "Web, Publishing"
  pricing_tier                 = "I1"
  front_end_scale_factor       = 15
  resource_group_name          = azurerm_resource_group.rg.name


  depends_on = [
    azurerm_resource_group.rg
  ]
}

resource "azurerm_app_service_plan" "asp" {


  for_each = { for asp in local.asp_list : asp.name => asp }

  name                         = each.key
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  kind                         = "linux"
  maximum_elastic_worker_count = 0
  sku {
    capacity = 4
    size     = "I1"
    tier     = "Isolated"
  }

  app_service_environment_id = azurerm_app_service_environment.ase[each.value.ase_name].id
  reserved                   = true 
  per_site_scaling           = false

  timeouts {
    create = "5h"
  }

  depends_on = [
    azurerm_app_service_environment.ase
  ]
}
```

### Expected Behaviour

When I create App Service Plan I assign in to App Service Environment I expect that the resource will be created and continue with the terrafrom creation,
### Actual Behaviour

Got timeout although the resource were created. The timeout happens when I set it for 1h or for 5h.
Error message: `Future#WaitForCompletion: context has been cancelled: StatusCode=202 -- Original Error: context deadline exceeded `
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Greven145** [comment]
Can confirm this is still happening. Very disruptive to a CI pipeline that needs to have the resource manually imported into the state file, then a new plan and apply executed.

**Comment by kfirlevin** [comment]
After we checked the issue with Microsoft support it seems that there was an issue with our ASE and therefore everything got stuck.
