### ISSUE TITLE
Issue with fix for #12533 with network watcher flow log name truncation to 80 char

### ISSUE THREAD

**Issue by dean-vanderwath-lab3** [hashicorp/terraform-provider-azurerm#12981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.72.0

### Affected Resource(s)

* `azurerm_network_watcher_flow_log`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "storage_account_name" {
  type    = string
}

variable "location" {
  type    = string
}
resource "azurerm_resource_group" "example" {
  name     = "nrg-test-thiswillendup31char-01"
  location = var.location
}

resource "azurerm_network_security_group" "example" {
  name                = "nsg-test-thiswillendup31char-01-nsgdesc"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_network_watcher" "example" {
  name                = "nwa-test-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_storage_account" "example" {
  name                      = var.storage_account_name
  resource_group_name       = azurerm_resource_group.example.name
  location                  = azurerm_resource_group.example.location
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "law-test-thiswillendup31char-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
}

resource "azurerm_network_watcher_flow_log" "example" {
  network_watcher_name = azurerm_network_watcher.example.name
  resource_group_name  = azurerm_resource_group.example.name

  network_security_group_id = azurerm_network_security_group.example.id
  storage_account_id        = azurerm_storage_account.example.id
  enabled                   = true

  retention_policy {
    enabled = true
    days    = 7
  }

  traffic_analytics {
    enabled               = true
    workspace_id          = azurerm_log_analytics_workspace.example.workspace_id
    workspace_region      = azurerm_log_analytics_workspace.example.location
    workspace_resource_id = azurerm_log_analytics_workspace.example.id
    interval_in_minutes   = 10
  }
}
```

### Debug Output
```
Error: creating "Flow Log: (Name \"Microsoft.Networknrg-test-thiswillendup31char-01nsg-test-thiswillendup31char-01-\" / Network Watcher Name \"nwa-test-01\" / 
Resource Group \"nrg-test-thiswillendup31char-01\")": network.FlowLogsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidResourceName" Message="Resource name Microsoft.Networknrg-test-thiswillendup31char-01nsg-test-thiswillendup31char-01- is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]
```
### Expected Behaviour

terraform apply to succeed as it has been, until 2.68 introduced [PR12533](https://github.com/hashicorp/terraform-provider-azurerm/pull/12533), with current naming convention. This introduction of truncation is what stopped our configuration from working even though it was 80+ characters.

### Actual Behaviour

We have a standardized naming convention module which a majority of our customers use and are now affected by this. Due to the truncation, we now get an error when deploying as the truncation always causes the string to end with a '-', which results in the error 
```
It must begin with a word character, and it must end with a word character or with '_'
```

### Steps to Reproduce

1. `terraform apply`

### References

#12460 
#12533

**Comment by nitmatgeo** [comment]
Can this be pushed on priority as 2.72.1? Breaking my release 😞

**Comment by larslind** [comment]
We had hoped that [#12533](https://github.com/hashicorp/terraform-provider-azurerm/pull/12533) would fix our issue with long RG + NSG names but now we have occasional failures when the 80th character is a "-", so this is still a blocking issue for us.
@magodo, is there any chance of prioritising the pull request from @josh-barker for fixing this? It would really be helpful to get this fixed ASAP.

**Comment by dean-vanderwath-lab3** [comment]
> We had hoped that [#12533](https://github.com/hashicorp/terraform-provider-azurerm/pull/12533) would fix our issue with long RG + NSG names but now we have occasional failures when the 80th character is a "-", so this is still a blocking issue for us.
> @magodo, is there any chance of prioritising the pull request from @josh-barker for fixing this? It would really be helpful to get this fixed ASAP.

One thing to keep in mind if you do have more than 80 characters and it gets truncated, you may end up with several resources with the same name. In this case terraform applies all the config correctly but the last flow to apply wins. You then only end up with 1 flow.
