### ISSUE TITLE
resource azurerm_linux_virtual_machine_scale_set crashes on apply  v2.70.0

### ISSUE THREAD

**Issue by waylew-lexis** [hashicorp/terraform-provider-azurerm#12992]
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.70.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4910b4d]

goroutine 122 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.virtualMachineScaleSetUpdateMetaData.performUpdate(0x10100, 0xc0001ea480, 0xc001639290, 0xc002752258, 0x0, 0xc0006d4200, 0xc0029d82a0, 0x0,
0x0, 0xc0029e6380, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/virtual_machine_scale_set_update.go:52 +0x14d
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute.resourceLinuxVirtualMachineScaleSetUpdate(0xc001b71200, 0x57787e0, 0xc0012dc700, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/compute/linux_virtual_machine_scale_set_resource.go:842 +0xc30
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc00088b880, 0x670a628, 0xc001a20640, 0xc001b71200, 0x57787e0, 0xc0012dc700, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:352 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00088b880, 0x670a628, 0xc001a20640, 0xc0019e62a0, 0xc001605420, 0x57787e0, 0xc0012dc700, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:464 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000cb28, 0x670a628, 0xc001a20640, 0xc001a48960, 0xc001a20640, 0x5c595a0, 0xc001f6c100)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001a17800, 0x670a6d0, 0xc001a20640, 0xc001004c40, 0xc001a17800, 0xc001f6c1e0, 0xc00110bba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x5c595a0, 0xc001a17800, 0x670a6d0, 0xc001f6c1e0, 0xc00197f9e0, 0x0, 0x670a6d0, 0xc001f6c1e0, 0xc00195c800, 0x46a9)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a6c40, 0x67565b8, 0xc000001980, 0xc001cf6c60, 0xc0010b8ab0, 0x9cccf80, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0002a6c40, 0x67565b8, 0xc000001980, 0xc001cf6c60, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000174b10, 0xc0002a6c40, 0x67565b8, 0xc000001980, 0xc001cf6c60)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. Some of these crashes were fixed in v 2.71 of the provider, can you please try upgrading?

**Comment by waylew-lexis** [comment]
Hello,
Getting this new error with that resource in v2.72.2 

Error: waiting for update of instances for Linux Virtual Machine Scale Set "git-runner-basic" (Resource Group "app-gitrunner-sandbox-eastus2"): Code="MaxUnhealthyInstancePercentExceededBeforeRollingUpgrade" Message="Rolling Upgrad
e failed due to exceeding the MaxUnhealthyInstancePercent value (defined in the RollingUpgradePolicy) before any batch was attempted. 100% of instances are in an unhealthy state, more than the threshold of 20% configured in the Roll
ingUpgradePolicy. The most impactful error is:  Instance found to be unhealthy or unreachable. For details on rolling upgrades, use http://aka.ms/AzureVMSSRollingUpgrade"
│
│   with module.git-runner-basic[0].azurerm_linux_virtual_machine_scale_set.runner,
│   on ../../vm.tf line 22, in resource "azurerm_linux_virtual_machine_scale_set" "runner":
│   22: resource "azurerm_linux_virtual_machine_scale_set" "runner" {

**Comment by favoretti** [comment]
@waylew-lexis well, this one is legit :) your rolling upgrade policy needs to have at least 20% of the VMSS instances in healthy state before performing upgrade actions and according to the error message - none of the instances in that set are healthy.

**Comment by waylew-lexis** [comment]
Yes, sorry I had forgotten I had modified the resource.

Thanks
Wayne Lewalski
SRE Team
LexisNexis Risk Solutions Group
***@***.******@***.***>

**Comment by mbfrahry** [comment]
Hey @waylew-lexis, are you still seeing this issue listed in the comments? If so, please open a new issue so we can track that bug instead of the currently listed fixed crash.
