### ISSUE TITLE
azurerm_storage_account has wrong allow_blob_public_access default value

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#13037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that the Azure has changed a default value for "allowBlobPublicAccess" to "true". The azurerm provider considers default value to be "false", hence leaves it unset (value is missing in resource exports and `az storage account show` command shows a value of "null"). 

I have a support ticket open with them, but they don't seem to bulge and since it is already written in their documentation (see link below). I don't think there is much chance for the default value to change back, hence please change it on your end.

### References

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.storageaccount.allowblobpublicaccess?view=azure-dotnet

**Comment by aglees** [comment]
In addition it seems like this parameter doesn't therefore work in AzureRm.... it can be set to `true` or `false` and Terraform is unable to make any changes.

**Comment by doanminhtu** [comment]
I am not sure why 2 previous comments said that the setting not worked.
This settings actually works, see the image below. I have made change on terraform and the output is in azure activity logs:
![image](https://user-images.githubusercontent.com/42829510/146306924-39befacb-99b5-4f65-b196-2700a887ce5a.png)

If they do not fix this default value, I don't know what will be happened in future since terraform-azurerm and ARM conflicts.

**Comment by jcoqueret** [comment]
Changing the setting `allow_blob_public_access` in terraform works for me.
However when I import a new resource in my terraform state, that value will always be `false` whatever I have configured on Azure.

**Comment by magodo** [comment]
@JiriKovar The default value used in Terraform is not necessarily to be the same as what is used in Azure, though typically we will follow the Azure convention. As you said, the default value for the allow_blob_public_access is changed in the Azure, while we can't afford to make the same change at the provider side in v2.0, as it is a breaking change.

Note that in v3.0, there are two changes:

1. The property name will be changed to `allow_nested_items_to_be_public` to make it more explicit
2. The default value is changed to `true`

https://github.com/hashicorp/terraform-provider-azurerm/blob/baf55926fe813011003ee4fb0e8e6134fcfcca87/internal/services/storage/storage_account_resource.go#L3027-L3038

**Comment by katbyte** [comment]
this has been fixed as of 3.0.0 which was released last week! as such i'm going to close this out
