### ISSUE TITLE
Support for full SecurityProfile for azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by amccullough84** [hashicorp/terraform-provider-azurerm#13039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can you please add support for adding a Security Profile block when deploying a Windows Virtual Machine. One of the Security Profile properties has already been implemented outside of a Security Profile block, however Azure has now added other attributes as part of the security profile to support Trusted Launch of Virtual Machines.  

### New or Affected Resource(s)

* azurerm_windows_virtual_machine
* azurerm_windows_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  security_profile {
    encryptionAtHost  = true
      securityType = 'TrustedLaunch'
      uefiSettings {
        secureBootEnabled = true
        vTpmEnabled = true
      }
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update#securityprofile

**Comment by tombuildsstuff** [comment]
hi @amccullough84 

Thanks for opening this issue.

Taking a look through here it appears that we already support Encryption at Host via [this top level field](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#encryption_at_host_enabled) - since the value for `SecurityType` can be inferred from the presence of the `uefi` block, I'm thinking this would probably make sense to be a top-level object:

```hcl
resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  encryption_at_host_enabled = true #available today
  secure_boot_enabled = true
  vtpm_enabled = true
  # the (only valid) value for SecurityType of 'TrustedLaunch' can be assumed if either of those is set to true?
}
```

WDYT?

Thanks!

**Comment by amccullough84** [comment]
Hi @tombuildsstuff that looks great to me - if either SecureBoot or vTPM are present then TrustedLaunch can be inferred so that would work fine.

**Comment by ellr** [comment]
Hi,
I like this suggestion a lot and would like to add this would be helpful for `azurerm_linux_virtual_machine` too.
