### ISSUE TITLE
Support for auto-mitigate for Azure scheduled_query

### ISSUE THREAD

**Issue by Xnnguyen** [hashicorp/terraform-provider-azurerm#13036]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add the auto-mitigate property to the azurerm_monitor_scheduled_query_rules_alert module

### New or Affected Resource(s)

azurerm_monitor_scheduled_query_rules_alert

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert

### Potential Terraform Configuration

```hcl

# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Klaas-** [comment]
I think this is a duplicate of #12691

**Comment by Xnnguyen** [comment]
I'm still getting "An argument named "auto_mitigate" is not expected here" error. Is "auto_mitigate"?

**Comment by Klaas-** [comment]
@Xnnguyen read https://github.com/hashicorp/terraform-provider-azurerm/pull/13213#issuecomment-921401566

**Comment by Xnnguyen** [comment]
doc has auto_mitigation_enabled, still getting an error, not a valid argument.

 28:   auto_mitigation_enabled = false
│
│ An argument named "auto_mitigation_enabled" is not expected here.

**Comment by stephybun** [comment]
Hi @Xnnguyen, thanks for raising this. Could you please provide me with some info, e.g. provider version and the terraform config that causes this error?

**Comment by Xnnguyen** [comment]
Hi Stephybun,

I included the main.tf, variable and vars-dv file.


Error: Unsupported argument
│
│   on main.tf line 28, in resource "azurerm_monitor_scheduled_query_rules_alert" "azure_alertv2_arel":
│   28:   auto_mitigation_enabled = false
│
│ An argument named "auto_mitigation_enabled" is not expected here.
╵
PS C:\Users\nnguyen\tf\ArelTest> terraform version
Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.76.0


***@***.***

**Comment by Klaas-** [comment]
@Xnnguyen read https://github.com/hashicorp/terraform-provider-azurerm/pull/13213#issuecomment-921401566 as I have previously suggested .... the version that includes automatic mitigation is 2.77

**Comment by Xnnguyen** [comment]
Got it working thanks…
I changed version = > 2.76 (I thought it would just take the latest version with greater value) to version = >= 2.77
