### ISSUE TITLE
azurerm_mssql_database long_term_retention_policy requires week_of_year and never re-applys clean (reopen #9067)

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azurerm#13035]
reopening parts of #9067  the docs say each part is optional, but if i only supply `weekly_retention` i get an error on apply:
```
 Error: issuing create/update request for Sql Server "usos1sql01-inmp-test" (Database "usos1dbo01-inmp-test") Long Term Retention Policies (Resource Group "usos1rgp01-inmp-test"): sql.BackupLongTermRetentionPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LongTermRetentionMissingWeekOfYear" Message="WeekOfYear is required to be set between 1 and 52 in order to set yearly retention."  
```

again since the docs say optional, i expect not to have to set it, but to work around i put  `week_of_year = 1`  and it applies, but then the very next apply the diff shows:

```
      ~ long_term_retention_policy {
          ~ week_of_year      = 0 -> 1
            # (3 unchanged attributes hidden)
        }
```

trying to set week_of_year = 0 leads to this error

```
Error: expected long_term_retention_policy.0.week_of_year to be in the range (1 - 52), got 0
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

❯ tf -v
Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.72.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.6

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "example" {
  name            = "example"
  server_id       = azurerm_mssql_server.mgmt.id
  elastic_pool_id = azurerm_mssql_elasticpool.mgmt.id
  max_size_gb     = 100

  threat_detection_policy {
    state                      = "Enabled"
    email_account_admins       = "Enabled"
    use_server_default         = "Enabled"
    storage_endpoint           = var.storage_account_blob_endpoint
    storage_account_access_key = var.storage_account_access_key
  }

  short_term_retention_policy {
    retention_days = 35
  }

  long_term_retention_policy {
    weekly_retention = "P45D"
    # this shouldn't be needed, but get's you past the first error
    # week_of_year = 1
  }
}
```

### Expected Behaviour

* Can set weekly retention WITHOUT setting week_in_year
* Setting week_in_year to 1 is reflected in state and subsequent runs don't affect

### Actual Behaviour

* week_in_year is required
* rerunning with week_in_year = 1 always shows a difference in plan

### Steps to Reproduce

1. `terraform apply`

### References

* #9067

**Comment by rellis-of-rhindleton** [comment]
To elaborate a bit: 

`week_of_year` only applies to yearly backups. If yearly backups are disabled (set to zero), Azure automatically sets this setting to zero, no matter what the configuration says (config can be 1, the value will be read next time as 0). The azurerm validation for this setting requires 1-52 so the config has to have a nonzero value. Every time Terraform runs it sees a change and an endless cycle of "updates" occurs.

Related: if yearly_backups are set to zero Azure sets `yearly_retention` to `PT0S`. This happens even if the value in the configuration is equivalent but different, e.g. `PY0` will result in endless updates from PT0S to PY0. There's no validation rule against PT0S though so it's easy to avoid this.

This is not an urgent problem, but it is annoying.  Hopefully the fix isn't any more difficult than changing the validation to allow week_of_year to be 0-52. It would be more accurate to require 1-52 _unless_ yearly_retention is set to "PT0S", but that relies on Azure not changing their default value, which might not be entirely safe.

**Comment by orgads** [comment]
When week_of_year is *not* set, I have this in the log:
```
2022-02-22T14:24:14.290Z [DEBUG] provider.terraform-provider-azurerm_v2.97.0_x5: AzureRM Request: 
PUT /subscriptions/.../resourceGroups/rg/providers/Microsoft.Sql/servers/sql-server/databases/test-db/backupLongTermRetentionPolicies/default?api-version=2020-11-01-preview HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.17.5 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v61.4.0 sql/v5.0 HashiCorp Terraform/1.1.6 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/2.97.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 106
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: ...
Accept-Encoding: gzip

{"properties":{"weeklyRetention":"P2W","monthlyRetention":"PT0S","yearlyRetention":"PT0S","weekOfYear":0}}: timestamp=2022-02-22T14:24:14.290Z
2022-02-22T14:24:15.083Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for azurerm_mssql_database.db
2022-02-22T14:24:15.083Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for azurerm_mssql_database.db
2022-02-22T14:24:15.083Z [TRACE] evalApplyProvisioners: azurerm_mssql_database.db is not freshly-created, so no provisioning is required
2022-02-22T14:24:15.083Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState to workingState for azurerm_mssql_database.db
2022-02-22T14:24:15.083Z [TRACE] NodeAbstractResouceInstance.writeResourceInstanceState: writing state object for azurerm_mssql_database.db
2022-02-22T14:24:15.084Z [TRACE] statemgr.Filesystem: creating backup snapshot at terraform.tfstate.backup
2022-02-22T14:24:15.084Z [DEBUG] provider.terraform-provider-azurerm_v2.97.0_x5: AzureRM Response for https://management.azure.com/subscriptions/.../resourceGroups/byoc-rolling/providers/Microsoft.Sql/servers/sql-server/databases/test-db/backupLongTermRetentionPolicies/default?api-version=2020-11-01-preview: 
HTTP/2.0 400 Bad Request
Content-Length: 151
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8

{"error":{"code":"LongTermRetentionMissingWeekOfYear","message":"WeekOfYear is required to be set between 1 and 52 in order to set yearly retention."}}: 
```

Notice that weekOfYear is still passed as 0.
{"properties":{"weeklyRetention":"P2W","monthlyRetention":"PT0S","yearlyRetention":"PT0S","weekOfYear":0}}

Looks like `weekOfYear` should be omitted when it is `null`.

**Comment by orgads** [comment]
Any chance of getting this fixed? This is a real pain.

**Comment by pierrejeandev** [comment]
Same issue here. This is really annoying.
I tried adding a lifecycle ignore_changes on the "week_of_year" property, but it even worse :
`Error: setting Long Term Retention Policies for Database: (Name "<db name>" / Server Name "<servername>" / Resource Group "<rg name>"): sql.LongTermRetentionPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LongTermRetentionMissingWeekOfYear" Message="WeekOfYear is required to be set between 1 and 52 in order to set yearly retention."`

**Comment by ilya-git** [comment]
This seems not to be a problem anymore in the latest terraform / azurerm provider. At least my plan did not show any differences

**Comment by orgads** [comment]
With 3.5.0 I can assign `null` to `week_of_year`, and it no longer tries to re-apply every time 👍 

The issue can be closed.

**Comment by orgads** [comment]
It's also fixed in 2.99.

**Comment by OliverKrukowPwC** [comment]
This issue is not fixed with version 3.8.0 or earlier.

`week_of_year` is a required parameter, so not setting it or setting it to `null` results in an error during creation.

Setting `week_of_year` to any value in the required range (1 - 52) results in proper creation, but it being detected as `0` during subsequent runs, which then on re-apply leads to the database being updated in place.

After a successful creation with `week_of_year` being set, one can then adapt the code and set it to `null`. That actually results in no change being detected during subsequent runs. But this is an ugly workaround and not a fix.

**Comment by orgads** [comment]
Oh, ok. I didn't try creating a new resource. Thanks for this info.

**Comment by frugecn** [comment]
I've tried to do a little digging on this one.  Running the Azure Rest API for Long Term Retention Policies - Create or Update [https://learn.microsoft.com/en-us/rest/api/sql/2022-05-01-preview/long-term-retention-policies/create-or-update?tabs=HTTP](url)

If I run where weekofyear = 0, it throws the weekofyear must be between 1 and 52.  
If I remove the weekofyear and yearlyretiontion as properties in the body going to the API, it will process the request.

So, I'm wondering if instead of the provider sending the entire list of parameters, the provider only sends the parameters defined in the long_term_retention_policy block if that would solve the problem.

It looks like the response adds the fields, though.

**Comment by drdamour** [comment]
this also causes problems during updates to fix things that may have been changed in portal or other places.   i have plans like

```
     ~ long_term_retention_policy {
          ~ weekly_retention  = "PT0S" -> "P45D"
            # (3 unchanged attributes hidden)
        }

      ~ short_term_retention_policy {
          ~ retention_days           = 7 -> 14
            # (1 unchanged attribute hidden)
        }
```

that can't apply because 

Error: setting Long Term Retention Policies for Database: (Name "usos1dbo01-advisor-test" / Server Name "usos1sql01-advisor-test" / Resource Group "usos1rgp01-advisor-test"): sql.LongTermRetentionPoliciesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LongTermRetentionMissingWeekOfYear" Message="WeekOfYear is required to be set between 1 and 52 in order to set yearly retention."

the fix here certainly seems to be to omit the weekofyear if yearlyretention is not specified in the call to azure.  that seems pretty straightforward change to make, wish someone who understood go well enough could PR this.

**Comment by drdamour** [comment]
what sucs]ks is if you send the azure service P0Y for yearly retention and 1 for week of year, but then read that value azure comes back with 0.   this is still true with 2022-05-01-preview

so really it's not just yearlyretention being null, but if it's any of the 0 values like P0Y PTOS etc..

maybe it's better to have an additional attribute that's like yearly_disabled = true or week_of_year_0 = 1 or something weird like that.

**Comment by orgads** [comment]
Thank you @beandrad!
