### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by roy-work** [hashicorp/terraform-provider-azurerm#13056]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Important Factoids

I am chasing a bug between the `databricks` provider & the `azurerm` provider: when I upgrade the AzureRM provider, after that, the Databricks provider is no longer able to authenticate. See [this issue](https://github.com/databrickslabs/terraform-provider-databricks/issues/783). It seems like something that was introduced in `azurerm` 2.71.0 is causing it, so I went looking for what changed there, but the changelog has not been updated since 2.69.0. Can there be a changelog published?

### References

* https://github.com/databrickslabs/terraform-provider-databricks/issues/783

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. My guess is would be you mis-clicked, here's the [latest changelog](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md). That said, I can see how CHANGELOG-v2.md may be misguiding.

**Comment by tombuildsstuff** [comment]
hi @roy-work 

Taking a look through this appears to be related to [this change in the databricks provider](https://github.com/databrickslabs/terraform-provider-databricks/issues/781#issuecomment-901306747) - as such I'm going to close this in favour of that issue.

With regards to the Azure Provider, we upgraded the Databricks API Version in that release - https://github.com/hashicorp/terraform-provider-azurerm/pull/12543 - as such I believe the Databricks Provider may need updating to account for that?

Thanks!

**Comment by roy-work** [comment]
> That said, I can see how CHANGELOG-v2.md may be misguiding.

Yeah, I only saw the -v1 and the -v2 CHANGELOGs. Why are there two, with one out of date…?

**Comment by favoretti** [comment]
Since we're on a weekly release schedule, they become very long. -v1 is for 1.x, -v2 is for everything 2x that's old enough.

**Comment by nfx** [comment]
@tombuildsstuff @favoretti I'm not  convinced that moving to AAD auth by default is the cause of the issue.

The ID field from the workspace resource is empty and provider cannot reach to resource manager to get workspace URL, therefore the error 
https://github.com/databrickslabs/terraform-provider-databricks/issues/783#issuecomment-901995849

Other issues report that azurerm provider below 2.70 work as expected. I'm going to be looking into this today.

**Comment by tombuildsstuff** [comment]
@nfx if the ID field is empty then the resource would be untracked within Terraform - so unfortunately this isn't a bug in the Azure Provider, else the Databricks Workspace resource wouldn't be tracked.

As mentioned above this is likely an issue within the Databricks Provider, so for now [I'd suggest tracking this in the bug you've opened on the Databricks side](https://github.com/databrickslabs/terraform-provider-databricks/issues/781) where this'll need to be fixed.

However since this isn't an issue with the Azure Provider I'm going to lock this issue for the moment to avoid any further confusion.

Thanks!
