### ISSUE TITLE
Support for the vnetRouteAllEnabled setting in azurerm

### ISSUE THREAD

**Issue by binte** [hashicorp/terraform-provider-azurerm#13053]
Currently, it doesn't seem possible to set the `Route All` setting in the VNet integration with an App Service. Traditionally, we would do that by setting the app `WEBSITE_VNET_ROUTE_ALL` setting to `1`. This doesn't seem to work anymore, as per the screenshot below. Instead, we are told to set the `vnetRouteAllEnabled` configuration setting. But how can we do that via Terraform?

![image](https://user-images.githubusercontent.com/5520287/129920659-92c25b7b-7e0e-44b6-81e4-9dad6203da29.png)

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. I'd say the same way as with `WEBSITE_VNET_ROUTE_ALL`, just set it. Did MSFT also tell you which value they accept for that setting? Optionally, flip it to `Enabled` in the portal, use az cli to fetch the app and check the value?

**Comment by tombuildsstuff** [comment]
The feature request for this is being tracked in #12860 - closing in favour of that issue
