### ISSUE TITLE
Additional Example needed in azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by zpbonjour** [hashicorp/terraform-provider-azurerm#13052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The module azurerm_resource_group_template_deployment has additional options surrounding the deletion of resources.  The note at the header reads:

"This resource will automatically attempt to delete resources deployed by the ARM Template when it is deleted. You can opt-out of this by setting the delete_nested_items_during_deletion field within the template_deployment block of the features block to false."

I would like to see an example of this.  It is confusing written out like that and I am not sure where to actually place the thing.

### New or Affected Resource(s)

azurerm_resource_group_template_deployment

### Potential Terraform Configuration

```hcl

```

### References

* #0000

**Comment by joshRooz** [comment]
@zpbonjour  the `delete_nested_items_during_deletion` argument is set in the azurerm providers block. Here's an example to disable the deletion of the underlying resources -

```hcl
provider "azurerm" {
  features {
    template_deployment {
      delete_nested_items_during_deletion = false
    }
  }
}
```

**Comment by rcskosir** [comment]
Thank you @joshRooz for the example and the PR #13313, with that I am going to close this issue.
