### ISSUE TITLE
Support for AKS node pool cordonDrainTimeoutInMinutes parameter

### ISSUE THREAD

**Issue by SteveLeach-Keytree** [hashicorp/terraform-provider-azurerm#13066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS feature aks-engine#1276 made the cordon drain timeout configurable, but this attribute does not yet appear to be exposed through the azurerm provider. 

We have some pods in a deployment that take a long time to start up as they load all the data they need. We generally have 4 pods in the ReplicaSet and a minimum of 2 (defined in a pod disruption budget). During an AKS upgrade we need to allow time for 2 new pods to start up on new nodes before terminating the last 2 on the old nodes, but the cordon & drain times-out before they are ready.

### New or Affected Resource(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "blue_node_pool" {
  name                  = "bluepool"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.k8s.id
  vm_size               = var.vm_size
  node_count            = var.node_pool_count
  os_disk_size_gb       = var.os_disk_size
  vnet_subnet_id        = azurerm_subnet.k8s_subnet.id
  orchestrator_version  = var.k8s_version

  enable_auto_scaling   = false
  enable_node_public_ip = false
  max_pods              = 110

  timeouts {
      drain = 40
  }

  lifecycle {
    ignore_changes = [
      node_count
    ]
  }
}
```

### References

* https://github.com/Azure/aks-engine/pull/1276

**Comment by aristosvo** [comment]
@SteveLeach-Keytree Do you know if this feature has made it into AKS already? I can't find it.

If not, I recommend to first file this issue upstream for the [AKS team](https://github.com/Azure/AKS) to expose it in the API.

**Comment by SteveLeach-Keytree** [comment]
> @SteveLeach-Keytree Do you know if this feature has made it into AKS the AKS API already? I can't find it.
> 
> If not, I recommend to first file this issue upstream for the [AKS team](https://github.com/Azure/AKS) to expose it in the API.

Is that not what the issue I linked in the reference was? I'm not entirely sure I fully understand what all the different projects are.

**Comment by aristosvo** [comment]
@SteveLeach-Keytree Don't worry, there is a lot indeed 😃 aks-engine stuff might end up in AKS, but in general a feature in aks-engine is not by default exposed in AKS.


If there is no documentation or API feature we can use, you should ask it to the [AKS team](https://github.com/Azure/AKS) first.

**Comment by SteveLeach-Keytree** [comment]
> @SteveLeach-Keytree Don't worry, there is a lot indeed 😃 aks-engine stuff might end up in AKS, but in general a feature in aks-engine is not by default exposed in AKS.
> 
> If there is no documentation or API feature we can use, you should ask it to the [AKS team](https://github.com/Azure/AKS) first.

That's what I'm saying - I linked the AKS team's change that makes this possible.

**Comment by aristosvo** [comment]
I understand what you are saying, but you are pointing towards the change in AKS _engine_. The Terraform provider for Azure interacts with Azure AKS API's which are a wrapper around the service which uses probably some version of your mentioned AKS engine.

We have to work with that API, as does the Azure CLI. The functionality you are interested in is AFAIK not exposed via the Azure AKS API. I cannot find it in the Azure CLI docs either. 

To get more technical detailed, [this link](
https://github.com/Azure/azure-sdk-for-go/blob/dc2d9f4b14d50a080644c66de1807c2d5fed663b/services/containerservice/mgmt/2021-07-01/containerservice/models.go#L1480) points towards the Go models which we can use to configure the AKS node pool for Terraform, I cannot find it over there as well. To get the feature exposed or more information how it possibly can be done you could best file an issue [here](https://github.com/Azure/AKS).

**Comment by SteveLeach-Keytree** [comment]
Ah, got you now. I'd assumed that the AKS _team_ were the people maintaining the AKS _engine_ and was getting very confused.
I'll see if I can get that raised and link it.

**Comment by SteveLeach-Keytree** [comment]
https://github.com/Azure/AKS/issues/2508

**Comment by BenjaminHerbert** [comment]
Just FYI: the issue was closed on the [AKS side due to inactivity](https://github.com/Azure/AKS/issues/2508#issuecomment-989830635) :shrug:

**Comment by cailyoung** [comment]
Regardless of the AKS issue, it appears that at some point this arrived in the REST API: https://learn.microsoft.com/en-us/rest/api/aks/agent-pools/get?view=rest-aks-2023-08-01&tabs=HTTP#agentpoolupgradesettings

**Comment by norm-dole-dbtlabs** [comment]
This value will also need to be respected when setting a temp-pool-name for upgrade. Meaning currently if you change VM size of AKS cluster in TF you give it a temp-node_pool-name and it creates one and moves your workload over and then re-creates the default-node-pool. the drain_timeout should be the same for the temp-pool and the re-created default-pool as the original custom setting rather than just set to the default 30min

**Comment by aristosvo** [comment]
I'll take a quick look on how hard this will be to implement, will let you know ASAP

**Comment by akrock** [comment]
@aristosvo It looks like the dependencies listed in the PR have been potentially resolved now. Is there anything that is blocking the attached PR from moving forward?

**Comment by dkirrane** [comment]
Could you add support for soak setting also?

So all `upgrade_settings` as per [API](https://learn.microsoft.com/en-us/rest/api/aks/agent-pools/get?view=rest-aks-2023-11-01&tabs=HTTP#agentpoolupgradesettings)?

`maxSurge`
`drainTimeoutInMinutes`
`nodeSoakDurationInMinutes`

**Comment by zioproto** [comment]
This is today possible on AKS and the features are all GA:
https://learn.microsoft.com/en-US/azure/aks/upgrade-aks-cluster?tabs=azure-cli#customize-node-surge-upgrade

Generally Available: AKS support for node soak duration for upgrades
https://azure.microsoft.com/en-gb/updates/generally-available-node-soak-duration-for-upgrades/

@stephybun @ms-henglu we need to have this in the provider. We already have a issue for the AKS module https://github.com/Azure/terraform-azurerm-aks/issues/530

**Comment by itay-grudev** [comment]
Without the:

* `--drainTimeoutInMinutes`
* `--node-soak-duration`

[parameters](https://learn.microsoft.com/en-us/azure/aks/upgrade-aks-cluster?tabs=azure-cli#set-node-soak-time-value), we are currently experiencing downtime during automatic node upgrades. Nodes are upgraded in a very rapid succession before services inside had a chance to recover.

I would call this a really **high priority** problem as it genuinely leaves services offline for a while. Could you please focus some effors on this?

**Comment by norm-dole-dbtlabs** [comment]
Hahah yeah...come on IBM let's get this done

**Comment by aristosvo** [comment]
I'll take a quick look. Last time it was blocked on Microsoft's API behavior, which was reported [here](https://github.com/Azure/azure-rest-api-specs/issues/27373) but which triggered no response thus far.

@norm-dole-dbtlabs Not cool, I'm an independent contributor, nobody at the Terraform nor HashiCorp side can be blamed for anything in this regard.

**Comment by stephybun** [comment]
@zioproto is this something you could help with by bringing it to the attention of the AKS team?

**Comment by aristosvo** [comment]
I've brought the PR up to date and completed stuff like docs.

The issue is still there, resetting the upgrade settings to the defaults implicitly is therefore not included in the current implementation. Whether that is an issue is up to the reviewers.

**Comment by norm-dole-dbtlabs** [comment]
@aristosvo that IBM shot wasn't at you; I think it's noble that your doing this work but it's also the responsibility of Hashicorp/Microsoft through whatever partnership they have to keep this up to date in real time and not hope community members shore up their enterprise support best effort
