### ISSUE TITLE
azurerm_app_service: Unchanged app_settings ending with \n are always updated

### ISSUE THREAD

**Issue by meidlinga** [hashicorp/terraform-provider-azurerm#13087]
If an app setting ends with a linefeed character, it is always updated. Even if it was not changed.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

I have had this issue also for older versions. Currently:
```
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
+ provider registry.terraform.io/hashicorp/dns v3.2.1
+ provider registry.terraform.io/hashicorp/github v4.13.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.9.4
```

### Affected Resource(s)

* `azurerm_app_service`
* `azurerm_app_service_slot`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "testservice" {

[...]

app_settings = {
       "TEST_HEREDOC"=<<EOF
A
A
EOF

       "TEST_HEREDOC2"=<<EOF
A
EOF

       "TEST_STR"="A\nA"
       "TEST_STR2"="A\nA\n"
       "TEST_STR3"="A\n"
}
}
```

### Expected Behaviour

The app settings TEST_HEREDOC, TEST_HEREDOC2, TEST_STR2, TEST_STR3 should not be applied when not changed.
This does not imply a first apply, when the settings are not existing, but subsequent updates.

### Actual Behaviour

The app settings TEST_HEREDOC, TEST_HEREDOC2, TEST_STR2, TEST_STR3 are always applied.

```
  ~ resource "azurerm_app_service" "testservice" {
      ~ app_settings                      = {
          ~ "TEST_HEREDOC"                                = <<-EOT
                A
                A
            EOT
          ~ "TEST_HEREDOC2"                               = <<-EOT
                A
            EOT
          ~ "TEST_STR2"                                   = <<-EOT
                A
                A
            EOT
          ~ "TEST_STR3"                                   = <<-EOT
                A
            EOT
            # (54 unchanged elements hidden)
        }
```

### Steps to Reproduce

1. Make an azurerm_app_service having app_settings ending with \n.
2. `terraform apply` (a first time)
3. do not change anything
4. `terraform apply` (again)

### References

* #0000

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
