### ISSUE TITLE
azurerm databricks workspace not supporting aml_workspace_id

### ISSUE THREAD

**Issue by gaddaak** [hashicorp/terraform-provider-azurerm#13086]
<img width="1792" alt="Screen Shot 2021-08-20 at 2 24 47 PM" src="https://user-images.githubusercontent.com/77636094/130294823-2ab8ab59-683d-4d0d-b230-cdc8f35997bd.png">

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by davkohli** [comment]
we are also experiencing same problem, already voted on the issue. thanks.

**Comment by brunoscota** [comment]
and its mentioned on oficial documentation.
