### ISSUE TITLE
Set default value of `enable_free_tier` to be `TRUE` to avoid extra charge

### ISSUE THREAD

**Issue by southwolf** [hashicorp/terraform-provider-azurerm#13091]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_cosmos_db_account

### Potential Terraform Configuration

```hcl
"enable_free_tier": {
  Type:     schema.TypeBool,
  Optional: true,
  Default:  true,       # changed from false
  ForceNew: true,
},
```

### References

The default behavior of creating a CosmosDB storage account in Azure is to Apply Free Tier Discount when you have it.

Terraform should also follow the same convention to avoid extra charge (like me, I created 2 instances without noticing the Optional `enable_free_tier` and cost me more than $100, and I had to submit support ticket asking for refund.

This change should not have any side effects - even for users not eligible for Free Tier, the option still exists in Azure Portal (Verified with enterprise agreement subscription).

![image](https://user-images.githubusercontent.com/150648/130377968-53b33d7c-f299-4bad-9396-eeaef829d7fc.png)

Related issues

* #7814
* #6030

**Comment by tombuildsstuff** [comment]
We should verify if it's possible to create multiple with this flag set - afaik the portal doesn't let you configure this for multiple CosmosDB Accounts (it's grey'd out when one account has this set?)?

**Comment by markjbrown** [comment]
You can only create one free account per subscription so would not be possible as any resource provisioning would be scoped to a single resource group which itself is scoped to a single Azure subscription.

Also, this does not default to true in the Cosmos resource provider. It's only enabled by default in the portal.

**Comment by tombuildsstuff** [comment]
Thanks for the heads up @markjbrown - will leave this set to `false` since this can only be set once per-subscription - but this functionality can be controlled via the field `enable_free_tier`.

Thanks!
