### ISSUE TITLE
automatic_channel_upgrade does not accept "node-image" 

### ISSUE THREAD

**Issue by T1loc** [hashicorp/terraform-provider-azurerm#13095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Update list of acceptable values (node-image is missing)

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "foo"
  vm_size               = "Standard_DS2_v2"
  node_count            = 3
  
  auto_upgrade_channel = "node-image"
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/upgrade-cluster#set-auto-upgrade-channel

**Comment by tombuildsstuff** [comment]
hi @T1loc 

This is available as of [the `v2.71.0` release](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#2710-august-06-2021) - as such upgrading to that release should let you configure this.

Thanks!
