### ISSUE TITLE
Support for "hybrid-benefit" for windows-"azurerm_kubernetes_cluster_node_pool"

### ISSUE THREAD

**Issue by matthiasritter** [hashicorp/terraform-provider-azurerm#13104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to enable the "hybrid-benefit"-feature on Windows-Worker-Nodepools.
This is possible via CLI with "--enable-ahub" 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "windows_nodepool" {
  name                  = "windows"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  os_type               = "Windows"
  vm_size               = var.windows_user_nodepool_node_size
  orchestrator_version  = data.azurerm_kubernetes_service_versions.current.latest_version
  max_pods              = var.user_nodepool_max_pods
  enable_auto_scaling   = true
  min_count             = var.windows_user_nodepool_node_count_min
  max_count             = var.windows_user_nodepool_node_count_max
  availability_zones    = ["1", "2", "3"]
  vnet_subnet_id        = azurerm_subnet.aks.id

 enable_hybrid_benefit = true # default: false

  tags = {
    dm-product = var.dm_product
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/aks/windows-faq#can-i-use-azure-hybrid-benefit-with-windows-nodes

**Comment by heoelri** [comment]
Do you want to enabled AHUB on a per-node pool level? 

It is already possible per-cluster (not per node pool) using the `license` parameter in `windows_profile`:

```hcl
  windows_profile {
    admin_username = ""
    admin_password = ""

    license = "Windows_Server" 
  }
```

Based on the azure-sdk-for go (see [models.go #L2719](https://github.com/Azure/azure-sdk-for-go/blob/main/services/containerservice/mgmt/2021-07-01/containerservice/models.go#L2719)) can it be set to 'LicenseTypeNone' or 'LicenseTypeWindowsServer'. This translates to 'Windows_Server' (ahub) or 'None' (payg) as mentioned in [Azure Hybrid Benefit for Windows Server](https://docs.microsoft.com/en-gb/azure/virtual-machines/windows/hybrid-use-benefit-licensing#convert-an-existing-vm-using-azure-hybrid-benefit-for-windows-server). 

You can use the CLI to search for AHUB-enabled node pools:

```azurecli
az vmss list --query "[?virtualMachineProfile.licenseType=='Windows_Server']" -o table
```

**Comment by matthiasritter** [comment]
@heoelri thank you very much, unfortunately I overlooked that.
Since this should be available on nodepool-level too (sometimes it could be cheaper to enable Hybrid-Benefit not on every nodepool but only on one nodepool, because of the vm-sizes), I would like to let this issue open.

**Comment by matthiasritter** [comment]
After some research I found out, that this is only available on cluster-level. So I'll close this issue.
