### ISSUE TITLE
Support for consumption_budget_management_group

### ISSUE THREAD

**Issue by josh-barker** [hashicorp/terraform-provider-azurerm#13112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I'd like to be able to configure a budget on a management group.

### New or Affected Resource(s)

* azurerm_consumption_budget_management_group

### Potential Terraform Configuration

```hcl
resource "azurerm_consumption_budget_management_group" "test" {
  name            = "some-budget"
  management_group_id = "some-management-group-id"

  amount     = 3000
  time_grain = "Monthly"

  time_period {
    start_date = "01-01-2020"
    end_date   = "01-01-2031"
  }

  notification {
    enabled   = true
    threshold = 95.0
    operator  = "GreaterThan"
    contact_emails = [
      "foo@example.com",
      "bar@example.com",
    ]
  }
}
```

### References

* #2677

**Comment by stephybun** [comment]
Closed by #14411
