### ISSUE TITLE
Please update documentation for azurerm_sql_server

### ISSUE THREAD

**Issue by BradLeeHines-ST** [hashicorp/terraform-provider-azurerm#13128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

Please update the code at [Link](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_server)

The sample code block asks us to use 
`extended_auditing_policy`
but the 
`terraform validate `
command asks users to use 
`azurerm_mssql_server_extended_auditing_policy` instead. 

Please update the documentation to encourage best practices.

**Comment by favoretti** [comment]
Hi there and thank you for reporting this issue. As the error message states, the inline block has been deprecated and will be removed in version 3.0 of the provider. Whenever 3.0 is released - the documentation will be updated accordingly.
