### ISSUE TITLE
Support for "Start trigger on creation" for azurerm_data_factory_trigger_schedule

### ISSUE THREAD

**Issue by NestorRV** [hashicorp/terraform-provider-azurerm#13133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a Azure Datafactory trigger within the portal, a check for starting the trigger on creation is displayed, see the following image:

![portal](https://user-images.githubusercontent.com/14926343/130748130-f0f30cd4-a158-45cf-9d1a-c4901b15b1aa.png)

Triggers created with the `azurerm_data_factory_trigger_schedule` resource are disabled on creation, making them to never run.

### New or Affected Resource(s)

* azurerm_data_factory_trigger_schedule

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_data_factory_pipeline" "example" {
  name                = "acctest%d"
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name   = azurerm_data_factory.example.name
}

resource "azurerm_data_factory_trigger_schedule" "example" {
  name                = "example"
  data_factory_name   = azurerm_data_factory.example.name
  resource_group_name = azurerm_resource_group.example.name
  pipeline_name       = azurerm_data_factory_pipeline.example.name

  start_on_cretion = true # <------------------------- This fields
}
```

**Comment by aristosvo** [comment]
Hi @NestorRV! Thanks for your issue, but it triggered (🤣 ) a question from my side: are you looking for activation of `azurerm_data_factory_trigger_schedule`, or do you want the flow to run once on creation?

Issue #9018 and PR #13090 is about activating `azurerm_data_factory_trigger_schedule `, but if you are looking for a one time run on creation time this is not a duplicate.

**Comment by NestorRV** [comment]
Hi @aristosvo! I expect the same behaviour as the flag within the portal. If that `start_on_cretion` field (or the `active` one in your linked issue) is set to true, the trigger should be activated after/during the creation. Without that functionality, we need to create the trigger and then, somehow, activate it. I would say this is a duplicate of the one you have linked (sorry in that case, my fault!) but I'll leave the final decision to you!

Thanks!

**Comment by aristosvo** [comment]
Thanks! This issue can be closed than as duplicate👍
