### ISSUE TITLE
User Identity for Azure Machine learning workspace

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform-provider-azurerm#13137]
Hi Team,

When can we expect feature to enable "User Managed Identity" for Azure Machine Learning workspace when deploying using terraform 
 
currently we have "system identity" using terraform

resource "azurerm_machine_learning_workspace" "aml_ws" {
  name                    = "${var.prefix}-ws-${random_string.postfix.result}"
  friendly_name           = var.workspace_display_name
  location                = azurerm_resource_group.aml_rg.location
  resource_group_name     = azurerm_resource_group.aml_rg.name
  application_insights_id = azurerm_application_insights.aml_ai.id
  key_vault_id            = azurerm_key_vault.aml_kv.id
  storage_account_id      = azurerm_storage_account.aml_sa.id
  container_registry_id   = azurerm_container_registry.aml_acr.id

  identity {
    type = "SystemAssigned"
  }
}

**Comment by stephybun** [comment]
Closed by #14181
