### ISSUE TITLE
Support for "Execute at this time" in azurerm_data_factory_trigger_schedule

### ISSUE THREAD

**Issue by NestorRV** [hashicorp/terraform-provider-azurerm#13132]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating a new trigger, if the recurrence is "bigger" than hourly (see daily, weekly or monthly), there are extra options for the recurrence, see the following picture:

![portal](https://user-images.githubusercontent.com/14926343/130747581-028a2c8b-e2ab-484d-aba0-5f219effc791.png)

### New or Affected Resource(s)

* azurerm_data_factory_trigger_schedule

### Potential Terraform Configuration

```hcl
# Not sure how I would suggest implementing this, so I leave this to you guys!
```

**Comment by NestorRV** [comment]
Just seen PR #13243 @stephybun. If all the options available in Azure have been considered in the PR, this one can be closed. What are your thoughts?

**Comment by stephybun** [comment]
Hi @NestorRV, thanks for bringing that to my attention! #13243 implements all scheduling options for a data factory trigger so I completely agree and will close this issue.
