### ISSUE TITLE
Import Your azurerm_frontdoor_custom_https_configuration Settings Into Your State File - Not working

### ISSUE THREAD

**Issue by thanga91** [hashicorp/terraform-provider-azurerm#13148]
Unable to import the azurerm_frontdoor_custom_https_configuration resource using below id format as mentioned in the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/2.58.0-frontdoor-upgrade-guide#import-your-azurerm_frontdoor_custom_https_configuration-settings-into-your-state-file) 

**/subscriptions/{subscription}/resourceGroups/{resorceGroup}/providers/Microsoft.Network/frontDoors/{frontDoor}/customHttpsConfiguration/default**

Error: 

```
2021-08-25T13:14:03.1156503Z ##[error]Terraform command 'import' failed with exit code '1'.:  parsing Resource ID "/subscriptions/{subscription}/resourceGroups/{resorceGroup}/providers/Microsoft.Network/frontDoors/{frontDoor}/customHttpsConfiguration/default": ID was missing the `frontendEndpoints` element |  Reference to undeclared input variable
2021-08-25T13:14:03.1177337Z ##[error][31m
```

trying to import it to a an empty resource stub as per the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/2.58.0-frontdoor-upgrade-guide#import-your-azurerm_frontdoor_custom_https_configuration-settings-into-your-state-file) 

`resource "azurerm_frontdoor_custom_https_configuration" "default" {
}`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
