### ISSUE TITLE
Error to retrieve ip_address from azurerm_public_ip resource.

### ISSUE THREAD

**Issue by rmends** [hashicorp/terraform-provider-azurerm#13141]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

data.azurerm_public_ip.example.ip_address

### Terraform Configuration Files

```hcl

data "azurerm_public_ip" "dynamic_pip" {
  for_each = toset(var.name)
  name                = azurerm_public_ip.pip[each.key].name
  resource_group_name = var.rg_name

output "public_ip" {
    value = data.azurerm_public_ip.dynamic_pip[*].ip_address
}
```

### Debug Output

rmends/gist:efc522ce1c94435760d85e242f45e44a

### Expected Behaviour

The public IP address should be passed in module outputs

### Actual Behaviour

An error: Unsupported attribute is happening, but is possible to confirm that the attribute exists and had filled.

### Steps to Reproduce

To declare a azurerm_public_ip resource and a data source .

try to retrieve the IP address information using a output block pointing to a data source block.

run terraform plan
run terraform apply

### References

* #0000

**Comment by kinwolfqc** [comment]
same problem, the output returns empty.

**Comment by rmends** [comment]
> same problem, the output returns empty.

Hi @kinwolfqc, I could workaround this problem using a for expression on the output instead that flat expression.

my code worked like that:

output "public_ip" {
    value = {for name in var.name : lower(name) => data.azurerm_public_ip.dynamic_pip[name].ip_address}
}

then the output was:

Ips = {
  + myserver   = "x.x.x.x"
  + myserver2 = "x,x,x,x"
}
