### ISSUE TITLE
Error: expected key_vault_key_id to not have a version in azurerm versions above 2.38.0

### ISSUE THREAD

**Issue by strakh-alex** [hashicorp/terraform-provider-azurerm#13147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.13.5
* azurerm_2.39.0+
* 

### Affected Resource(s)

`azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
...
key_vault_key_id = azurerm_key_vault_key.key_vault_key.id
```

### Expected Behaviour

The Cosmos DB account should have been created with my custom CMK key used for encryption.

### Actual Behaviour

Resource creation failed

### Steps to Reproduce

Create Terrafrom configuration with CosmosDB consuming KeyVault key (CMK)

1. `terraform apply`

### Additional information

I tested with newer versions (2.47, 2.63 and 2.73) and it works only with the provider version 2.38 and below.

**Comment by ctvanzandt42** [comment]
I know that we don't want to post "me too" comments, but I want to point out, this makes me completely unable to take advantage of the enhanced encryption features that are enabled by using a CMK. We make sure to keep our provider versions up-to-date, and using outdated versions affects our ability to use organizational modules and other great features. Would really love to have this resolved soon.

**Comment by rschurchill** [comment]
Provision for getting a versionless key id was added in 2.47.0.  This is working for me with a Cosmos CMK.

`key_vault_key_id = azurerm_key_vault_key.cosmos-db-name.versionless_id`

Although, given that a versionless key is necessary in this circumstance, it may help if the error message was tweaked to provide the solution rather than simply state the error.

**Comment by ctvanzandt42** [comment]
Just created https://github.com/hashicorp/terraform-provider-azurerm/pull/14768 to enhance this error message. Makes sense, but I wasn't able to figure it out on my own.
