### ISSUE TITLE
Support for --enable-addons azure-keyvault-secrets-provider

### ISSUE THREAD

**Issue by smileythf** [hashicorp/terraform-provider-azurerm#13150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft have recently updated their process for integrating aks with akv (https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver). It appears that they've added a new addon option, is it possible to allow access to this option through Terraform. --enable-addons azure-keyvault-secrets-provider.

Sample az code - az aks create -n myAKSCluster -g myResourceGroup --enable-addons azure-keyvault-secrets-provider --enable-managed-identity

### New or Affected Resource(s)

azurerm_kubernetes_cluster.

* azurerm_2.73.0

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
(...)
  addon_profile {
    azure-keyvault-secrets-provider {
        enabled                       = true
    azure_policy {
      enabled                         = true
    }
  }
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by dhirschfeld** [comment]
I'd like to see this too, but it appears this is a dup of #12783?

**Comment by tombuildsstuff** [comment]
thanks for the heads up @dhirschfeld - this is indeed a duplicate - consolidating this into #12783
