### ISSUE TITLE
Incorrect argument description on storage account documentation

### ISSUE THREAD

**Issue by randvir** [hashicorp/terraform-provider-azurerm#13167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On the [allowed_methods](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#allowed_methods) description, it says _A list of http headers that are allowed_ instead of _A list of http methods that are allowed_.

**Comment by AbihaFatima** [comment]
Hi @stephybun @randvir !
I am new to open source. can I be assigned to fix this?

**Comment by stephybun** [comment]
@AbihaFatima certainly 🙂

**Comment by AbihaFatima** [comment]
here is my pull request #13208
