### ISSUE TITLE
Ingress is not getting IP after deploying AKS cluster with ingress_application_gateway add-on enabled

### ISSUE THREAD

**Issue by tmiroslav** [hashicorp/terraform-provider-azurerm#13169]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform version: 0.13.6`

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "nutanix-cluster" {
  name     = "${var.aks_cluster_name}-rg"
  location = var.azure_region
}

resource "azurerm_virtual_network" "nutanix-cluster-network" {
  name                = "nutanix-cluster-network"
  address_space       = ["10.10.16.0/20"]
  location            = var.azure_region
  resource_group_name = azurerm_resource_group.nutanix-cluster.name
}

resource "azurerm_subnet" "nutanix-cluster-subnet" {
  name                 = "nutanix-cluster-subnet"
  resource_group_name  = azurerm_resource_group.nutanix-cluster.name
  virtual_network_name = azurerm_virtual_network.nutanix-cluster-network.name
  address_prefixes     = ["10.10.17.0/24"]
}

resource "azurerm_kubernetes_cluster" "nutanix-cluster" {
  name                = "${var.aks_cluster_name}-aks"
  location            = azurerm_resource_group.nutanix-cluster.location
  resource_group_name = azurerm_resource_group.nutanix-cluster.name
  dns_prefix          = "${var.aks_cluster_name}-k8s"
  kubernetes_version  = var.aks_kubernetes_version

  default_node_pool {
    name = "systempool"
    vm_size             = "Standard_D2_v2"
    availability_zones  = [1, 2, 3]
    vnet_subnet_id      = azurerm_subnet.nutanix-cluster-subnet.id
    enable_auto_scaling = true
    max_count           = 3
    min_count           = 1
    os_disk_size_gb     = 30
    type                = "VirtualMachineScaleSets"
  }

  service_principal {
    client_id     = var.azure_client_id
    client_secret = var.azure_client_secret
  }

  network_profile {
    network_plugin = "azure"
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed                = true
      admin_group_object_ids = [var.ad_admin_group_id]
    }
  }

  addon_profile {
    ingress_application_gateway {
      enabled = true
      gateway_name = "appgw-clusters"
      subnet_cidr  = "10.10.18.0/24"
    }
  }
}

```

### Expected Behaviour

AKS cluster, together with appgw is deployed successfully. But, after deploying first app in kubernetes cluster (Using aspnetapp like in example [here](https://docs.microsoft.com/en-us/azure/application-gateway/tutorial-ingress-controller-add-on-new)), ingress AKS resource is not getting IP, and then do not update app gw. 

### Actual Behaviour

This is what I have after deploying first app in AKS cluster (As sad before, using aspnetapp example)
```
kubectl get ingress --all-namespaces=true
NAMESPACE     NAME        CLASS    HOSTS   ADDRESS   PORTS   AGE
kube-system   aspnetapp   <none>   *                 80      23s
```
So, no IP allocated here.

### Steps to Reproduce

Run code I pasted above.

**Comment by aristosvo** [comment]
@tmiroslav Have you verified the events during and after the deployment of the example in all namespaces (`kubectl get events -A --sort-by=lastTimestamp`)? I suspect the problem is permissions based.

I suspect that giving the service principal `Contributor` (or similar, in any way permissions to modify the APIG) permissions on the gateway might resolve this issue.

**Comment by tmiroslav** [comment]
Hi @aristosvo 

Thanx for your answer.

Seems I messed things up with namespaces. I would regularly deploy AKS cluster, using principal ID like in example above, and then would deploy test aspnetapp in kube-system namespace. When I deploy app in default namespace, ingress resource was managed to get an IP.

**Comment by aristosvo** [comment]
Perfect, looks like this issue can be closed.

Good luck!👍
