### ISSUE TITLE
Support for creating azurerm_kubernetes_cluster without kube configs in state file

### ISSUE THREAD

**Issue by carlos4ndre** [hashicorp/terraform-provider-azurerm#13168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an AKS cluster the kube configs get stored in the terraform state file, so I would like to know if it would be possible to prevent that?

I know it is assumed by design that the information stored in the state file is considered secure, this however
can become a serious threat in the event of it getting compromised as the attacker will be able to get the admin kube config, giving full control over the cluster and for instance access all user's pod secrets. So it would make sense to keep those secrets on the Cloud provider's side, if possible.

As unlikely as this scenario might be, it has a high impact so it could make sense to have some sort of feature flag to include/exclude the sensitive kube configs in the state file. The admin credentials of the kube cluster could be retrieved using the [Azure API](https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/list-cluster-admin-credentials) avoiding the need to store them in the state file.

This issue has already been mentioned in https://github.com/hashicorp/terraform-provider-azurerm/pull/10390 but given the severity, I think it would be worthwhile to revisit this as it would be giving more options to further securing the cluster.

As a reference, both EKS and GKE cluster resources do not store any sensitive data in their state file, so it would be great if the `azurerm_kubernetes_cluster` resource could allow the same pattern.

Let me know your thoughts on this.

Thanks!

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### References

* https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/list-cluster-admin-credentials

**Comment by aristosvo** [comment]
Hi @carlos4ndre! I think the feature you are requesting might be basically around the corner.

[When the feature to disable local accounts](https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts-preview) would be implemented, you are unable to get a working kubeconfig without AAD login.

I'm curious, would that work within your organization or would this be a solution which is too restricted?

**Comment by carlos4ndre** [comment]
Hi @aristosvo!

I've tried out the [disable local accounts](https://docs.microsoft.com/en-us/azure/aks/managed-aad#disable-local-accounts-preview) feature and it worked well,  I'm no longer seeing any sensitive information of the kube configs getting stored in the Terraform state file.

Thanks for your help, this seems to solve the issue :+1:

One last question, do you have any suggestions on how to generate an access token within Terraform?

I'm using the [kubectl](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs) Terraform provider to provision kube resources, and will need to pass in a valid access token for it to work. Prior to this solution, was using the kube clients certs and now need to switch to an access token, which so far I think it can be achieved by using [exec](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#exec) and then invoke [kubelogin](https://github.com/Azure/kubelogin).

This will require some extra dependencies, like Azure CLI and kubelogin itself. I haven't tested this yet but it should work. It would be great to know if there is another simpler alternative (e.g., eks has a command line [option](https://docs.aws.amazon.com/cli/latest/reference/eks/get-token.html) to generate a token).

**Comment by aristosvo** [comment]
@carlos4ndre I think it should be possible, but the latest information I have is based on [this issue](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1176).

**Comment by aristosvo** [comment]
@carlos4ndre Great! If you have found the solution, could you please share it?

**Comment by carlos4ndre** [comment]
Hi @aristosvo,

I was able to get an AAD token using the version [v0.0.10](https://github.com/Azure/kubelogin/releases/tag/v0.0.10) of kubelogin.

I'm using the `get-token` command directly from within the [exec](https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs#exec) attribute of the kubectl provider, avoiding any dependency on the kube config, Azure CLI and going through a series of steps in order to get that token.

This is how it would look from the CLI:
```
export AAD_SERVICE_PRINCIPAL_CLIENT_ID=<spn client id>
export AAD_SERVICE_PRINCIPAL_CLIENT_SECRET=<spn secret>

kubelogin get-token \
  --login spn \
  --environment AzurePublicCloud \
  --tenant-id <aad tenant id> \
  --server-id 6dae42f8-4368-4678-94ff-3960e28e3630 \
  | jq .status.token
```

and Terraform:
```
provider "kubectl" {
  host                   = data.azurerm_kubernetes_cluster.default.kube_config.0.host
  cluster_ca_certificate = base64decode(data.azurerm_kubernetes_cluster.default.kube_config.0.cluster_ca_certificate)
  load_config_file       = false

  exec {
    api_version = "client.authentication.k8s.io/v1beta1"
    command     = "kubelogin"
    args = [
      "get-token",
      "--login",
      "spn",
      "--environment",
      "AzurePublicCloud",
      "--tenant-id",
      var.tenant_id,
      "--server-id",
      var.server_id,
      "|",
      "jq",
      ".status.token"
    ]
  }
}
```

**Note:** I'm assuming the `server-id` is always `6dae42f8-4368-4678-94ff-3960e28e3630` as mentioned in the documentation over [here](https://github.com/Azure/kubelogin#exec-plugin-format). This makes getting the token much easier, but If this turns out to be inaccurate and that Id does change, then this approach needs to be revisited, perhaps calling a script to dynamically fetch the kube config with that Id correctly populated in the `.user.auth-provider.config.apiserver-id` section, and then perform the necessary commands with `az aks` and `kubelogin` in order to get the token.

It would be nice though to have this logic embedded in the Azure CLI, same as [EKS](https://docs.aws.amazon.com/cli/latest/reference/eks/get-token.html).

**Comment by carlos4ndre** [comment]
Actually, the `server-id` information can be retrieved from [kubernetes_cluster](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_cluster#server_app_id) data source.

**Comment by aristosvo** [comment]
Thanks a lot! I created an issue for the flag to disable local accounts for AKS to put it on the radar, I might have time to implement it even in the coming few days.
