### ISSUE TITLE
The plugin returned an unexpected error from plugin.(*GRPCProvider).ConfigureProvider

### ISSUE THREAD

**Issue by som-nitjsr** [hashicorp/terraform-provider-azurerm#13182]
On My windows 10 Machine I was running terraform for azure and was able to create my resources and from yesterday I am started getting this error. Even I am getting the same issue in my sample apps.
The code in my sample app is from here.
https://learn.hashicorp.com/tutorials/terraform/azure-build?in=terraform/azure-get-started

PS C:\sns\tf> terraform init

Initializing the backend...

Initializing provider plugins...

Finding hashicorp/azurerm versions matching "~> 2.65"...
Installing hashicorp/azurerm v2.74.0...
Installed hashicorp/azurerm v2.74.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

PS C:\sns\tf> terraform plan
╷
│ Error: Plugin error
│
│ with provider["registry.terraform.io/hashicorp/azurerm"],
│ on main.tf line 13, in provider "azurerm":
│ 13: provider "azurerm" {
│
│ The plugin returned an unexpected error from plugin.(*GRPCProvider).ConfigureProvider: rpc error: code = Internal
│ desc = grpc: error while marshaling: string field contains invalid UTF-8

**Comment by saurabh1611** [comment]
Facing similar issue for the version 2.70.0

**Comment by som-nitjsr** [comment]
I tried on different machine it works for one day then again same issue.

**Comment by jok0** [comment]
Same issue on version 2.79.0

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
