### ISSUE TITLE
Support for enable-managed-identity on azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by smark88** [hashicorp/terraform-provider-azurerm#13180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow preview feature enable-managed-identity to be enabled on aks clusters

### New or Affected Resource(s)

azurerm_kubernetes_cluster

### References

https://docs.microsoft.com/en-us/azure/aks/use-managed-identity#update-an-aks-cluster-to-managed-identities-preview

**Comment by aristosvo** [comment]
Hi @smark88 👋!

I believe this is completely supported, and can be found in the docs.

This part is responsible for configuring the Managed Identity:

```hcl
...
  identity {
    type = "SystemAssigned"
  }
...
```

A migration scenario from service_principal to identity is supported. When upgrading service_principal to identity, your cluster's control plane and addon pods will switch to use managed identity, but the kubelets will keep using your configured service_principal until you upgrade your Node Pool.

**Comment by stephybun** [comment]
Hi @smark88 

Thanks for opening this issue. As pointed out by @aristosvo this feature is already supported. As such i'm going to close this issue, If you have any questions regarding the usage then I would encourage you to raise that in one of the [community resources](https://www.terraform.io/community) or in our [community slack channel](https://terraform-azure.slack.com/).

Thanks!
