### ISSUE TITLE
Support for `local_authentication_disabled` in `azurerm_cosmosdb_account`

### ISSUE THREAD

**Issue by shibayan** [hashicorp/terraform-provider-azurerm#13184]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Disable local authentication using the four access keys provided with Cosmos DB and add an option to force Azure AD authentication.

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  local_authentication_disabled = true
}
```

### References

* https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#disable-local-auth
* https://msrc-blog.microsoft.com/2021/08/27/update-on-vulnerability-in-the-azure-cosmos-db-jupyter-notebook-feature/

**Comment by ajmal744** [comment]
As we like to move to RBAC auth model for cosmosdb and want to reduce attack vector of keys - it would be really nice to have this feature merged as soon as possible please
