### ISSUE TITLE
Error when creating azurerm_data_protection_backup_vault

### ISSUE THREAD

**Issue by wary-hermit** [hashicorp/terraform-provider-azurerm#13198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.73.0

Upgraded to v2.74.0 - issue persists. 

### Affected Resource(s)

* `azurerm_data_protection_backup_vault`

### Terraform Configuration Files

```hcl
resource "azurerm_data_protection_backup_vault" "backupvault" {
  name                = "good-name-for-backup-vault"
  resource_group_name = azurerm_resource_group.transport.name
  location            = azurerm_resource_group.transport.location
  datastore_type      = "VaultStore"
  redundancy          = "LocallyRedundant"
  
  identity {
    type = "SystemAssigned"
  }
}
```

### Panic Output

```
│ Error: waiting for creation of the DataProtection BackupVault ("Backup Vault: (Name \"good-name-for-backup-vault\" /  
Resource Group \"transport-resources\")"): Future#WaitForCompletion: the number of retries has been exceeded:   
StatusCode=404 -- Original Error: Code="InvalidResourceType" Message="The resource type could not be found in the  
namespace 'Microsoft.DataProtection' for api version '2021-01-01'."
│
│   with azurerm_data_protection_backup_vault.backupvault,
│   on backup.tf line 1, in resource "azurerm_data_protection_backup_vault" "backupvault":
│    1: resource "azurerm_data_protection_backup_vault" "backupvault" {
```

### Expected Behaviour

Create BackUp Vault and continue.

### Actual Behaviour

Backup vault is created (if viewed from portal), but terraform shows error and stops.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The thing is that this worked 7 days ago just fine. But at least for last 3 days it started showing this error. Checked out my code from then it was passing without problems - it does not work any longer and shows this error.

**Comment by IvanStanul** [comment]
Maybe it was some problem on Azure's end? Because after few days - it now started working again, no crashes, without changing anything. Not sure why it was failing before.

**Comment by katbyte** [comment]
Closing as it seems like the issue has been resolved!
