### ISSUE TITLE
unable to Integrate Keyvault certificate to azurerm_api_management_custom_domain proxy settings

### ISSUE THREAD

**Issue by ghariin** [hashicorp/terraform-provider-azurerm#13193]
I was trying to import keyvault certificate to API Gateway to enable the Custom domain and autonegotiate the certificate., 

Steps followed: Enabled system identity is true at keyvault. added access policy mapping with apigateway.  which is successful.  

in the azurerm_api_management_custom_domain proxy settings, when we refer key_vault_id for custom domain mapping, mapping was  successful.  However it is mapping to https://myvault.vault.azure.net/secrets/certificate/version instead of mapping to certificate.  in Azure side i see the following error.
**Hostname keyvault certificate version, this prevents certificate from being refreshed when its update in keyvault.  Update hostname certificate to ensure its successful rotation**

**My Configuration**
data "azurerm_client_config" "current" {
}

#Key Vault Data
data "azurerm_key_vault" "Keyvault_nonprod" {
  name                = "Kvcertone"
  resource_group_name = "RGGroup"
}

# Access Policy Mapping to Keyvault
resource "azurerm_key_vault_access_policy" "access_poliy" {
  key_vault_id = data.azurerm_key_vault.Keyvault_nonprod.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id     = "${azurerm_api_management.API-Gateway.identity.0.principal_id}"
   
    key_permissions = [
     "Get","List",
   ]

  secret_permissions = [
    "Get","List",
  ]
}

# Keyvault Secret data reference
data "azurerm_key_vault_secret" "Keyvault_nonprod_secret" {
  name            = "secret"
  key_vault_id    = data.azurerm_key_vault.Keyvault_nonprod.id
}

# Key vault certificate
data "azurerm_key_vault_certificate" "testdotsurpakimcom" {
  name         = "certificate"
  key_vault_id = data.azurerm_key_vault.Keyvault_nonprod.id
}

# Custom Domain Configuration
resource "azurerm_api_management_custom_domain" "custom-domain" {
  api_management_id = azurerm_api_management.API-Gateway.id

  proxy {
    host_name    = var.gateway-custom-domain
    key_vault_id = data.azurerm_key_vault_certificate.certificate.secret_id
    negotiate_client_certificate  = true
  }

When i modified manually custom domain keyvault settings in azure to https://keyvault.vault.azure.net/secrets/certificate/  the warning was disappeared.  

* [Configuration Language](https://www.terraform.io/docs/configuration/index.html) or resource ordering issues
* [State](https://www.terraform.io/docs/state/index.html) and [State Backend](https://www.terraform.io/docs/backends/index.html) issues
* [Provisioner](https://www.terraform.io/docs/provisioners/index.html) issues
* [Registry](https://registry.terraform.io/) issues
* Spans resources across multiple providers

If you are running into one of these scenarios, we recommend opening an issue in the [Terraform core repository](https://github.com/hashicorp/terraform/) instead.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Please run `terraform -v` to show the Terraform core version and provider version(s). If you are not running the latest version of Terraform or the provider, please upgrade because your issue may have already been fixed. [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions).
Terraform v1.0.1
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.5. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)

* `azurerm_v2.74.0`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Custom domain should apply the latest certificate instead of referring to Thumbprint, when keyvault certificate got expired, there is no chances of auto renew this certificate in API Gateway
https://myvault.vault.azure.net/secrets/certificate/

### Actual Behaviour

https://myvault.vault.azure.net/secrets/certificate/thumbprint

### Steps to Reproduce

1. `terraform apply`

### References
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Such as vendor documentation?

* #0000

**Comment by oWretch** [comment]
Above PR adds a `versionless_secret_id` property to the Key Vault which can be used in place of the versions ID to solve this issue.
