### ISSUE TITLE
Imported an existing KeyVault key.  TF apply -- the key must be replaced.

### ISSUE THREAD

**Issue by zpbonjour** [hashicorp/terraform-provider-azurerm#13201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

azurerm_key_vault_key

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "identity" {
  name                       = var.KeyVaultName
  location                   = azurerm_resource_group.ResourceGroup.location
  resource_group_name        = azurerm_resource_group.ResourceGroup.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7
  depends_on = [azurerm_app_service.WebAppPlatform, azurerm_app_service_slot.ApiStaging]
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Create",
      "Get",
      "Purge",
      "Recover",
      "Delete"
    ]

    secret_permissions = [
      "Set",
    ]
  }
}

resource "azurerm_key_vault_key" "GeneratedKey" {
  name         = "MyKey"
  key_vault_id = azurerm_key_vault.identity.id
  key_type     = "RSA"
  key_size     = 4096

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behaviour

Apply should not affect the key as no changes were made after import

### Actual Behaviour

Terraform attempts to replace the KeyVault key 

### Steps to Reproduce

1.  Create a key in KeyVault via Portal or CLI/API
2.  Import the key with "terraform import azurerm_key_vault_key...."
3.  Run "terraform apply"
4. "+key_vault_id {my keyvault ID string} forces replacement"

### Important Factoids

Using Terraform Cloud exclusively

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @zpbonjour 

Thanks for opening this issue.

Taking a look through this appears to be a usage question - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by mikemonteith** [comment]
I think this is the same issue as: https://github.com/hashicorp/terraform-provider-azurerm/issues/12357
