### ISSUE TITLE
azurerm_app_service identity.identity_ids auto set empty, but can't manually set to match

### ISSUE THREAD

**Issue by collinsbenjw** [hashicorp/terraform-provider-azurerm#13212]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.0
AzureRM v2.72

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "example" {
# ...
  identity {
    type = "SystemAssigned"
    identity_ids = []
  }
```

### Expected Behaviour

When running without identity_ids set, Azure will set it to = []. This is shown under "things changed outside of tf" on next tf plan.
Setting this manually should allow it to match the actual configuration and cause no errors

### Actual Behaviour

The following error is given when running a new terraform plan:
```hcl
│ Error: Not enough list items
│
│   with module.example.azurerm_app_service.example,
│   on main.tf line 431, in resource "azurerm_app_service" "example":
│  431:     identity_ids = []
│
│ Attribute requires 1 item minimum, but config has only 0 declared.
```

### Steps to Reproduce

1. `terraform apply` on app service config without identity_ids set
2. `terraform plan` with above configuration to match "changed outside of terraform"

**Comment by rcskosir** [comment]
Thanks for opening this issue. azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
