### ISSUE TITLE
azurerm_monitor_diagnostic_setting failing when using eventhub rule id as a destination

### ISSUE THREAD

**Issue by nourriba** [hashicorp/terraform-provider-azurerm#13220]
When creating a monitor diagnostic setting and want to use event hub as a destination 

- if I provide eventhub_authorization_rule_id with a value referencing an policy rule on a eventhub namespace 
     Ex : "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{My_eventhub_namespace}/authorizationRules/{MyAaccessPolicyName}"
   everything is working fine 

- if I provide "eventhub_authorization_rule_id with a value referencing an policy rule on a eventhub ( not an eventhub namespace ) 
   | Ex : |"/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"
     it is failing to parse the id 

      This is the Error Displayed 

      
      │ Error: ID contained more segments than required: "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}", map[eventhubs:{My_eventHub_name}]
      │
      │   with azurerm_monitor_diagnostic_setting.monitor_diagnostic_settings,
      │   on t.tf line 10, in resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings":
      │   10: eventhub_authorization_rule_id  = "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"

Example :   
      
resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings" {

  eventhub_authorization_rule_id  = /subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}
  name                           = "monitor_diagnostic_setting"
  target_resource_id             = "/subscriptions/........."

  log {
     category = "ContainerRegistryRepositoryEvents"
     enabled  = true
     retention_policy {
        days    = 0
        enabled = true
    }
  }
  metric {
    category = "AllMetrics"
    enabled  = false
    retention_policy {
       days    = 0
       enabled = false
    }
  }
}

### Terraform and azurerm Version
```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
```

 
 

### Crash Output

      │ Error: ID contained more segments than required: "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"  map[eventhubs:{My_eventHub_name}]
      │
      │   with azurerm_monitor_diagnostic_setting.monitor_diagnostic_settings,
      │   on t.tf line 10, in resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings":
      │   10: eventhub_authorization_rule_id  = "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}" 

 
### Steps to Reproduce
    replace {..}  with real values 
resource "azurerm_monitor_diagnostic_setting" "monitor_diagnostic_settings" {
  eventhub_authorization_rule_id  = "/subscriptions/{My_subsID}/resourceGroups/{MyGroup}/providers/Microsoft.EventHub/namespaces/{eventHub-namespaceName}/eventhubs/{My_eventHub_name}/authorizationRules/{MyPolicy}"
  name                           = "monitor_diagnostic_setting"
  target_resource_id             = "/subscriptions/........."

  log {
     category = "ContainerRegistryRepositoryEvents"
     enabled  = true
     retention_policy {
        days    = 0
        enabled = true
    }
  }
  metric {
    category = "AllMetrics"
    enabled  = false
    retention_policy {
       days    = 0
       enabled = false
    }
  }
}

**Comment by nourriba** [comment]
Any news in this

**Comment by okanmenevseoglu** [comment]
I am also having the same issue on version 2.84 when I try to pass it as a variable from the actual rule:
`eventhub_authorization_rule_id = azurerm_eventhub_authorization_rule.eventhub_producer_rule.id`

**Comment by okanmenevseoglu** [comment]
After a bit of research, I've found that apparently the naming is unclear and it actually requires a eventhub_namespace_authorization_rule_id not eventhub_authorization_rule_id which is actually described in the document: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting

So this is not really a bug but a non-supported feature:
`eventhub_authorization_rule_id - (Optional) Specifies the ID of an Event Hub Namespace Authorization Rule used to send Diagnostics Data. Changing this forces a new resource to be created.`

**Comment by nourriba** [comment]
How can i send diagnostics logs/metrics to a specific event hub with the event hub namespace ( in case i have multiple event hubs grouped in the same namespace )  ?
