### ISSUE TITLE
Unable to create new azurerm_app_configuration_key

### ISSUE THREAD

**Issue by Socolin** [hashicorp/terraform-provider-azurerm#13229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Version: 2.75.0

```
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
```

### Affected Resource(s)

* `azurerm_app_configuration_key`

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration" "config-use" {
  name                = "some-config"
  resource_group_name = azurerm_resource_group.some-rg.name
  location            = azurerm_resource_group.some-rg.location
  sku                 = "free"

  tags = {
    "Environment" = local.environment,
  }
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.config-use.id

  key  = "test"
  value = "1"
}
```

### Debug Output

Debug output contains sensible data... and it's too big to be sure I'm not leaking any secret, so here only the classic logs

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_app_configuration_key.test will be created
  + resource "azurerm_app_configuration_key" "test" {
      + configuration_store_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/some-rg/providers/Microsoft.AppConfiguration/configurationStores/some-config"
      + content_type           = (known after apply)
      + etag                   = (known after apply)
      + id                     = (known after apply)
      + key                    = "test"
      + locked                 = false
      + type                   = "kv"
      + value                  = "1"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_app_configuration_key.test: Creating...
╷
│ Error: while checking for key's "test" existence: appconfiguration.BaseClient#GetKeyValues: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
│ 
│   with azurerm_app_configuration_key.test,
│   on app_config.tf line 153, in resource "azurerm_app_configuration_key" "test":
│  153: resource "azurerm_app_configuration_key" "test" {
│ 
│ while checking for key's "test" existence: appconfiguration.BaseClient#GetKeyValues: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
╵
```

### Expected Behaviour

It create a new error

### Actual Behaviour

It crash

### Steps to Reproduce

`terraform apply`

### Important Factoids

- The command `az appconfig kv set -n some-config --key test --value abc` is working so I have the correct access. Terraform is displaying a 403 error.

- Azure US East

**Comment by Socolin** [comment]
Maybe it would be the same problem as I got when trying to import (I dont have time to try it now, I'll check next week but maybe it can help)

See: https://github.com/hashicorp/terraform-provider-azurerm/issues/13230#issuecomment-918111632 
There is a special permission to add to be able to manage configuration kv with terraform

**Comment by wozorio** [comment]
I am facing the same issue with `azurerm_app_configuration_feature`. Adding the service principal to the `App Configuration Data Owner` role and changing the authentication method from Access keys to Azure AD do not help.

**Comment by martin-weber** [comment]
I have the same with azurerm_app_configuration_feature.

**Comment by vanmash** [comment]
The configuration below worked for me. Defining `azurerm_role_assignment.appconf_dataowner` and adding `depends_on` are crucial.

```hcl
resource "azurerm_app_configuration" "appconfiguration" {
...
}

resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_app_configuration.appconfiguration.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = var.SP_OBJECT_ID
}

resource "azurerm_app_configuration_key" "settings" {
  configuration_store_id = azurerm_app_configuration.appconfiguration.id
  key                    = "Compensation:Settings"

  depends_on = [
    azurerm_role_assignment.appconf_dataowner
  ]
}
```

reference:
[app_configuration_key docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration_key#example-usage-of-vault-type)

**Comment by xocolatl-aficionado** [comment]
Thanks @vanmash . Noteworthy is the note on the terraform doc:

> App Configuration Keys are provisioned using a Data Plane API which requires the role App Configuration Data Owner on either the App Configuration or a parent scope (such as the Resource Group/Subscription).

So if the OP has this role assigned to their resource group/subscription, then an explicit azurerm_role_assignment resource would be unnecessary. But definitely confirm this exists at the parent level.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
