### ISSUE TITLE
Terraform for AKS  idempotency not working

### ISSUE THREAD

**Issue by vidyasagarreddyc** [hashicorp/terraform-provider-azurerm#13232]
**What happened**:

terraform idempotency not work for AKS, first time it will deploy successfuly, if i rerun same code without changin anything, it recreate cluster/components. Raised support request they ask to report here. 

**What you expected to happen**:

terraform should not recreate any comopents, if no changes in terraform code

**How to reproduce it (as minimally and precisely as possible)**:
1. Clone repo https://github.com/vidyasagarreddyc/aks_terraform.git
2. Go to project directory
 cd aks_terraform/projects/project
3. init, plan and apply
terraform init
terraform plan --var-file=./env/dev.tfvars.json
terraform apply -auto-approve --var-file=./env/dev.tfvars.json
4. Once successfully deployed run again terraform plan without changing any code
terraform plan --var-file=./env/dev.tfvars.json

It will show,
Plan: 1 to add, 1 to change, 1 to destroy.

expected behaviour: 0 add and 0 to destroy

**Anything else we need to know?**: NA

**Environment**:
- Kubernetes version (use `kubectl version`): 1.20.7
- Terraform version: Terraform v0.13.5
- Size of cluster (how many worker nodes are in the cluster?): autoscaler
- General description of workloads in the cluster (e.g. HTTP microservices, Java app, Ruby on Rails, machine learning, etc.): no workload is started and its intial deployment
- Others: NA

**Comment by aristosvo** [comment]
Hey @vidyasagarreddyc 👋 

I wanted to reproduce this to check what the problem is, however this module refers to data sources which I don't have. Is it possible to make your reconstruction scenario simpler or specify which fields trigger above mentioned behavior?

**Comment by vidyasagarreddyc** [comment]
Let me change the code and update, I will opt below example https://github.com/Azure/terraform-azurerm-aks

**Comment by stephybun** [comment]
Thanks for opening this issue @vidyasagarreddyc. Seeing as we haven't heard anything back from you I'm hoping the suggestion from @aristosvo helped solve your issue and will go ahead and close this. If not I would direct you to the [Community Discuss forum](https://discuss.hashicorp.com/) where you can ask questions specific to configuration which this appears to be.

Thanks!
