### ISSUE TITLE
Error after apply an azurerm_app_configuration_key without `label` variable

### ISSUE THREAD

**Issue by brunoscota** [hashicorp/terraform-provider-azurerm#13236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.6
on darwin_amd64
provider registry.terraform.io/hashicorp/azurerm v2.75.0

### Affected Resource(s)

* `azurerm_app_configuration_key`

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration_key" "launchDarkley_key" {
  configuration_store_id = module.appconfiguration.id
  key                    = "launchDarkley.key"
  value                  = "aaaa"
}
```

### Debug Output

```
Terraform will perform the following actions:

  # azurerm_app_configuration_key.launchDarkley_key will be created
  + resource "azurerm_app_configuration_key" "launchDarkley_key" {
      + configuration_store_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/shared_configuration/providers/Microsoft.AppConfiguration/configurationStores/appcs-dev-ngconf-01"
      + content_type           = (known after apply)
      + etag                   = (known after apply)
      + id                     = (known after apply)
      + key                    = "launchDarkley.key"
      + locked                 = false
      + type                   = "kv"
      + value                  = "aaaa"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_app_configuration_key.launchDarkley_key: Creating...
╷
│ Error: while parsing resource ID: while parsing resource ID: The number of path segments is not divisible by 2 in "subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/shared_configuration/providers/Microsoft.AppConfiguration/configurationStores/appcs-dev-ngconf-01/AppConfigurationKey/launchDarkley.key/Label"
│ 
│   with azurerm_app_configuration_key.launchDarkley_key,
│   on main.tf line 36, in resource "azurerm_app_configuration_key" "launchDarkley_key":
│   36: resource "azurerm_app_configuration_key" "launchDarkley_key" {
│ 
│ while parsing resource ID: while parsing resource ID: The number of path segments is not divisible by 2 in
│ "subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/shared_configuration/providers/Microsoft.AppConfiguration/configurationStores/appcs-dev-ngconf-01/AppConfigurationKey/launchDarkley.key/Label"
╵
Releasing state lock. This may take a few moments...
```
### Expected Behaviour

Returns the key confirmation even without assigning lable variable

### Actual Behaviour

When I try to add a key type `kv` just assigning the name and value the object is created in my app configuration and also is written into my tfstate but instead of `Apply Complete` output, i'm receiving the error above. But the error doesn't happens when the `label` is provided

### Steps to Reproduce

Its easy, just try to apply without specify a label property

### Important Factoids

The object key is created and apears in appconfiguration and my tfstate. And it works fine if I assign `label` variable. 

Taking a look at the merged the tests were made with `label` variable. But in the read me it says that its optional.

**Comment by martin-jaeger-maersk** [comment]
Getting same behaviour. `label` is optional in the Azure API, so of course it should be in terraform as well.

**Comment by MPapst** [comment]
Adding a label does not resolve the issue for me. Getting exact the same error when a label is added (tried both: empty string and with value).

**Comment by martin-jaeger-maersk** [comment]
> Adding a label does not resolve the issue for me. Getting exact the same error when a label is added (tried both: empty string and with value).
If you add the label before running the first apply, so that the resource is created with it, it will work.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
