### ISSUE TITLE
Azure VM Workload Backup Extension always times out

### ISSUE THREAD

**Issue by faisaleem-na** [hashicorp/terraform-provider-azurerm#13241]
am trying to deploy the azurebackupwindowsworkload extension to server 2019 virtual machines deployed in Azure public cloud

### Terraform (and AzureRM Provider) Version

terraform version 0.14.10

azreurm version 2.61.0

### Affected Resource(s)

azurerm_virtual_machine_extension

```hcl
resource "azurerm_virtual_machine_extension" "SQLBackupExtension" {
  for_each = {
    for k, r in var.vms : k => r
    if contains(keys(r), "SQLBackupExtension")
  }
  name                 = "SQLBackupExtension"
  virtual_machine_id   = azurerm_windows_virtual_machine.vm[each.key].id
  publisher            = "Microsoft.Azure.RecoveryServices.WorkloadBackup"
  type                 = "AzureBackupWindowsWorkload"
  type_handler_version = "1.1"
  depends_on           = [azurerm_windows_virtual_machine.vm]
}
```

### Debug Output
```
Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

  on .terraform/modules/vms-win/module/main.tf line 219, in resource "azurerm_virtual_machine_extension" "SQLBackupExtension":
 219: resource "azurerm_virtual_machine_extension" "SQLBackupExtension" {
```

### Expected Behaviour

terraform should provision the extension successfully, in to a 'provisioning succeeded' state

### Actual Behaviour

terraform times out and extension is left in a 'transitioning' state 

### Steps to Reproduce

apply configuration

1. `terraform apply`

**Comment by mpjtaylor** [comment]
experiencing this issue more and more with Microsoft.Azure.Monitor and AzureMonitorLinuxAgent / AzureMonitorWindowsAgent

is there any resolution for it:

```go
resource "azurerm_virtual_machine_extension" "virtualmachine_linux" {
  count = var.os_type == "Linux" ? 1 : 0

  name                       = "AzureMonitorLinuxAgent"
  virtual_machine_id         = local.virtual_machine_id
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorLinuxAgent"
  type_handler_version       = "1.9"
  auto_upgrade_minor_version = true
  settings                   = <<SETTINGS
    {
    }
SETTINGS
}
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
