### ISSUE TITLE
Azurerm provide fails to getting authenticated over Azure DevOps pipeline Terraform Plan

### ISSUE THREAD

**Issue by Srimrao02** [hashicorp/terraform-provider-azurerm#13242]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.5
Tried with both Provider versions 2.72.0 and 2.75.0 

### Affected Resource(s)
AzureRM Authentication

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.75.0"
    }
  }
}

provider "azurerm" {
  features {}
}

terraform {
  backend "azurerm" {}
}
```

### Expected Behaviour

Plan should work and refresh the state.

### Actual Behaviour

Basically it refreshes the random providers but later it gets stuck for almost 7min and throws error. I have not seen any issues on `StatusCode:0, Message:"Failure sending request"`

![image](https://user-images.githubusercontent.com/49248571/132217847-38c42664-95c0-4a03-9647-2bd1ad5dd490.png)

```
Error: building account: getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*url.Error)(0xc0011ba390), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:0, Message:"Failure sending request", ServiceError:[]uint8(nil), Response:(*http.Response)(nil)}

  with provider["registry.terraform.io/hashicorp/azurerm"],
  on main.tf line 10, in provider "azurerm":
  10: provider "azurerm" {
```

We have done similar setup for another region, there we do not have any issues via same pipeline and same procedure. Below is plan output of working region.

![image](https://user-images.githubusercontent.com/49248571/132218050-e6aa6ecd-65fb-4bc3-8b9e-fc6a64040466.png)

### Steps to Reproduce

1. Initialize terraform with all config

```
./terraform -chdir=prod-americas init \
  -backend-config "resource_group_name=$TF_VAR_tf_state_rgname" \
  -backend-config "storage_account_name=$TF_VAR_tf_state_saname" \
  -backend-config "container_name=$TF_VAR_tf_container_name" \
  -backend-config "key=$TF_VAR_key" \
  -backend-config "subscription_id=$ARM_SUBSCRIPTION_ID" \
  -backend-config "client_id=$ARM_CLIENT_ID" \
  -backend-config "client_certificate_path=$ARM_CLIENT_CERTIFICATE_PATH" \
  -backend-config "client_certificate_password=$ARM_CLIENT_CERTIFICATE_PASSWORD" \
  -backend-config "tenant_id=$ARM_TENANT_ID"
 ```

2. `terraform plan`

### References

Any help or reference would be appreciated. As I have wasted my 3 days trying to re-spin the agent instance, reconfigure agents and many other options. Nothing is working.

**Comment by manicminer** [comment]
Hi @Srimrao02, thanks for opening this issue. This looks most likely to be a network issue between the agent where Terraform is running, and the API at graph.windows.net. I would suggest manual testing via your agent to ensure the provider can reach all necessary APIs.

As this is more of a usage question pertaining to your execution environment, I'm going to close this issue for now. We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). I believe you should be able to get an answer on the community discussion portal.
