### ISSUE TITLE
disabling retention_policy when share_properties is a nested block always outputs changes on tf plan

### ISSUE THREAD

**Issue by cyprienruelle** [hashicorp/terraform-provider-azurerm#13254]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.1.0
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
+ provider registry.terraform.io/hashicorp/null v3.1.0

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

terraform {
  required_version = ">= 0.15"
  required_providers {
    azurerm = {
      version = "~> 2.0"
      source  = "hashicorp/azurerm"
    }
  }
}

locals {
  kind = "StorageV2"
  activate_retention_policy = false
}

resource "azurerm_storage_account" "storage_account" {
  name = "testshareproperties"
  resource_group_name = "test_rg"
  account_replication_type = "LRS"
  location = "west europe"
  account_tier = "Standard"
  account_kind = local.kind

  dynamic "share_properties" {
    for_each = local.kind != "BlobStorage" && local.kind != "BlockBlobStorage" ? [true] : []
    content {
      dynamic "retention_policy" {
        for_each = local.activate_retention_policy ? [true] : []
        content {
          days = 30
        }
      }
    }
  }
}
```

### Expected Behaviour

After tf apply, the next tf plan should not output pending changes.

### Actual Behaviour

```
terraform plan
azurerm_storage_account.storage_account: Refreshing state... [id=/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/test_rg/providers/Microsoft.Storage/storageAccounts/testshareproperties]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_storage_account.storage_account has been changed
  ~ resource "azurerm_storage_account" "storage_account" {
        id                             = "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/test_rg/providers/Microsoft.Storage/storageAccounts/testshareproperties"
        name                           = "testshareproperties"
      + tags                           = {}
        # (30 unchanged attributes hidden)



        # (3 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond   
to these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_storage_account.storage_account will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
        id                             = "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/test_rg/providers/Microsoft.Storage/storageAccounts/testshareproperties"
        name                           = "testshareproperties"
        tags                           = {}
        # (30 unchanged attributes hidden)




      + share_properties {
        }
        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run "terraform apply" now.
```

### Steps to Reproduce

1. `terraform apply`
1. `terraform plan`

### Additionnal Context

We have a home-made module which encapsulate azurerm_storage_account to have minimum settings to determine when creating a storage account. The same resource is used whatever the kind of the storage account.

So we need a dynamic share_properties block to disable the block when storage account does not have shares.
On top of that, we may need deactivate retention_policy depending on storage account usage.

The code above is a simpler way to reach this configuration.

A solution could be to have `0` as an authorized value for `days` and disable retention in that case.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
