### ISSUE TITLE
Support for 'sku' property of 'public_ip_address' in 'azurerm_linux_virtual_machine_scale_set'

### ISSUE THREAD

**Issue by JanneMattila** [hashicorp/terraform-provider-azurerm#13250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Virtual Machine scale set can be configured with Public IP addresses. Those Public IP addresses can be configured to support [Routing preferences](https://docs.microsoft.com/en-us/azure/virtual-network/routing-preference-overview).
However, this requires that you use `Standard` SKU of the Public IP. By default, it will create `Basic` Public IP and if you try to enable routing preferences for that you'll get error message: 

````
Code="BasicSkuPublicIPAddressDoesNotSupportRoutingPreference" Message="A PublicIPAddress sku of Standard 
is required for routing preference feature
````

### New or Affected Resource(s)

* azurerm_linux_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "front-vmss" {
  name                            = "front-vmss"
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = azurerm_resource_group.rg.location
  sku                             = "Standard_D4d_v4"
  instances                       = 3
  admin_username                  = var.vm_username
  admin_password                  = var.vm_password
  disable_password_authentication = false
  zones                           = [1, 2, 3]
  zone_balance                    = true
  overprovision                   = true

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }

  network_interface {
    name                          = "nic"
    primary                       = true
    enable_accelerated_networking = true

    ip_configuration {
      name      = "public1"
      primary   = true
      subnet_id = azurerm_subnet.front-subnet.id

      public_ip_address {
        name = "pip"

        sku = "Standard" # NEW property for setting the sku

        ip_tag {
          type = "RoutingPreference"
          tag  = "Internet"
        }
      }
    }
  }

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadOnly"

    diff_disk_settings {
      option = "Local"
    }
  }
}
```

Notice that new `sku` property under `public_ip_address`.

### References

Newer ARM APIs e.g., [2021-04-01](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2021-04-01/virtualmachinescalesets?tabs=bicep) do support setting the `sku`. See details under [VirtualMachineScaleSetPublicIPAddressConfiguration](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2021-04-01/virtualmachinescalesets?tabs=bicep#virtualmachinescalesetpublicipaddressconfiguration).

[What is routing preference?](https://docs.microsoft.com/en-us/azure/virtual-network/routing-preference-overview)

* #11212

**Comment by JanneMattila** [comment]
Actually, I think better would be to use similar structure as in [ARM template](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2021-04-01/virtualmachinescalesets?tabs=bicep):

```hcl
sku {
  name = "Standard"
  tier = "Regional"
}
```

And *not* that direct string:

```hcl
sku = "Standard"
```

**Comment by WodansSon** [comment]
AFAIK This is already exposed in the [azurerm_public_ip](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip) resource directly. I think exposing the same attribute in multiple places would add confusion and potential conflicts between the resources and Azure. I would suggest setting the `sku` in the public ip resource directly.

**Comment by tombuildsstuff** [comment]
@WodansSon that makes sense for a VM but not for a VMSS where the NIC's are created/updated dynamically by the VMSS Management API/Platform?

**Comment by WodansSon** [comment]
@tombuildsstuff I dug into this issue a bit deeper and these fields are exposed in the SDK they just have not been exposed via Terraform as of yet. I am working with the service team to figure out if we are supposed to expose these or not... I am leaning toward yes, but I will wait to hear from the service team. 🙂
