### ISSUE TITLE
Cannot import the state of a monitor diagnostic settings if the setting is defined at subscription level

### ISSUE THREAD

**Issue by AFAde** [hashicorp/terraform-provider-azurerm#13272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Cannot import the state of a monitor diagnostic settings if the setting is defined at subscription level

For example, the command

terraform import azurerm_monitor_diagnostic_setting.resource_health_alert "subscriptions/**************************/providers/microsoft.insights/diagnosticSettings/Resource health diagnostics develop"

produces the following output

```
2021-09-08T09:50:34.362+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/hashicorp/azurerm\"]" changed the config value, but that value is unused
azurerm_monitor_diagnostic_setting.resource_health_alert: Importing from ID "subscriptions/************************/providers/microsoft.insights/diagnosticSettings/Resource health diagnostics develop"...
azurerm_monitor_diagnostic_setting.resource_health_alert: Import prepared!
  Prepared azurerm_monitor_diagnostic_setting for import
azurerm_monitor_diagnostic_setting.resource_health_alert: Refreshing state... [id=subscriptions/************************/providers/microsoft.insights/diagnosticSettings/Resource health diagnostics develop]
╷
│ Error: Expected the Monitor Diagnostics ID to be in the format `{resourceId}|{name}` but got 1 segments
```

I experience a similar issue when trying to create diagnostic setting when using the subscription as target_resource_id
For example, the following script

```
resource "azurerm_monitor_diagnostic_setting" "resource_health_alert" {
  name               = "resource_health_alert-test"
  target_resource_id = "/subscriptions/*********************"
  log_analytics_workspace_id = "/subscriptions/***************/resourcegroups/monitoring_core-develop-rg/providers/microsoft.operationalinsights/workspaces/test-loganalytics-develop"

  metric {
    category = "ResourceHealth"

    retention_policy {
      enabled = false
    }
  }
}

```
Produces the following output

```
2021-09-08T10:29:11.553+0200 [WARN]  provider.terraform-provider-azurerm_v2.75.0_x5.exe: Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-09-08T10:29:11.553+0200
2021-09-08T10:29:13.012+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/hashicorp/azurerm\"]" changed the config value, but that value is unused
2021-09-08T10:29:19.066+0200 [WARN]  provider.terraform-provider-azurerm_v2.75.0_x5.exe: Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-09-08T10:29:19.065+0200

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_monitor_diagnostic_setting.resource_health_alert will be created
  + resource "azurerm_monitor_diagnostic_setting" "resource_health_alert" {
      + id                         = (known after apply)
      + log_analytics_workspace_id = "/subscriptions/****************/resourcegroups/monitoring_core-develop-rg/providers/microsoft.operationalinsights/workspaces/test-loganalytics-develop"
      + name                       = "resource_health_alert-production"
      + target_resource_id         = "/subscriptions/*******************"

      + metric {
          + category = "ResourceHealth"
          + enabled  = true

          + retention_policy {
              + enabled = false
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

2021-09-08T10:29:23.053+0200 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/hashicorp/azurerm\"]" changed the config value, but that value is unused
2021-09-08T10:29:28.852+0200 [WARN]  provider.terraform-provider-azurerm_v2.75.0_x5.exe: Truncating attribute path of 0 diagnostics for TypeSet: timestamp=2021-09-08T10:29:28.852+0200
azurerm_monitor_diagnostic_setting.resource_health_alert: Creating...
╷
│ Error: insights.DiagnosticSettingsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The diagnostic setting 'resource_health_alert-production' doesn't exist."
│
│   with azurerm_monitor_diagnostic_setting.resource_health_alert,
│   on main.tf line 24, in resource "azurerm_monitor_diagnostic_setting" "resource_health_alert":
│   24: resource "azurerm_monitor_diagnostic_setting" "resource_health_alert" {
```

### Terraform Version
Terraform v1.0.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/random v2.3.1

### Expected Behavior
The state should be imported

### Actual Behavior
Import Fails

### Steps to Reproduce

1. terraform import azurerm_monitor_diagnostic_setting.resource_health_alert "subscriptions/**************************/providers/microsoft.insights/diagnosticSettings/Resource health diagnostics develop"

**Comment by emeadows** [comment]
Is this due to be resolved, I am experiancing the same issue and to my knoweldge there is not work around.

**Comment by tombuildsstuff** [comment]
This is an issue with the ID bring provided at import time, it's missing both a forward slash and the diagnostic setting name e.g.

> terraform import azurerm_monitor_diagnostic_setting.resource_health_alert "subscriptions/**************************/providers/microsoft.insights/diagnosticSettings/Resource health diagnostics develop"

Rather than what we're expecting ([per the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#import):

> terraform import azurerm_monitor_diagnostic_setting.example "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/group1/providers/Microsoft.KeyVault/vaults/vault1|logMonitoring1"

Closing this out since this'll be fixed by specifying the correct Resource ID at import time here.
