### ISSUE TITLE
azure logic app workflow access control through terraform is not possible

### ISSUE THREAD

**Issue by Maheshsuthari** [hashicorp/terraform-provider-azurerm#13285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
Hey @Maheshsuthari - thanks for opening this issue, could you please add some details here? its hard to know what the request is from the title alone. THanks!

**Comment by mybayern1974** [comment]
I assume [PR 13265](https://github.com/hashicorp/terraform-provider-azurerm/pull/13265) can address this ask.

**Comment by wiktorn** [comment]
I think that this can be closed now.

**Comment by mybayern1974** [comment]
Per assume there is already #13265 fixing this, close this issue.
