### ISSUE TITLE
Bug in "azurerm_key_vault_secret" implementation 

### ISSUE THREAD

**Issue by kumehta** [hashicorp/terraform-provider-azurerm#13288]
Hi Team,

I have one Key vault with Purge Protection enabled for 14 Days. I am creating a secret using "azurerm_key_vault_secret" "sql_server_username" and when I delete secret manually through Portal and after that re-run "terraform apply" 

Expected Behavior :   It should give me an error by saying that key is in deleted state with purge protection
Actual Behavior: It recreates the secret with new version Id.

**Comment by tombuildsstuff** [comment]
@kumehta Terraform will auto-recover soft-deleted secrets during deletion if a soft-deleted secret is found with that name - the new version is likely coming from the update of other fields post-restore such as additional tags.
