### ISSUE TITLE
azurerm_mssql_virtual_machine resource using custom image times out

### ISSUE THREAD

**Issue by waylew-lexis** [hashicorp/terraform-provider-azurerm#13298]
Not sure if this is a feature request or a bug, but when using this resource against a windows vm that is using a secured custom version of the mssql server image, the resource will time out on the apply. The custom image we are using does work on the vm without using this resource, which makes me believe this an issue with the resource and not the image.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* azurerm_mssql_virtual_machine

### Terraform Configuration Files

```hcl
  data "azurerm_shared_image" "sql" {
    name                = "windows2019SQLDeveloper"
    gallery_name        = "windows2019SQLDeveloper"
    resource_group_name = "myrg"
  }
  
  resource "azurerm_windows_virtual_machine" "example" {
    name                = "example-machine"
    resource_group_name = "myrg"
    location            = azurerm_resource_group.example.location
    size                = "Standard_F2"
    source_image_id  = data.azurerm_shared_image.sql.id
  }
  
  resource "azurerm_mssql_virtual_machine" "example" {
    virtual_machine_id               = resource.azurerm_windows_virtual_machine.example.id
    sql_license_type                 = "PAYG"
    r_services_enabled               = true
    sql_connectivity_port            = 1433
    sql_connectivity_type            = "PRIVATE"
  }
```

### Debug Output

https://gist.github.com/waylew-lexis/6ed62f4b869ee7190ca07f0954eae81c

### Expected Behaviour

apply completes successfully using a custom sql server image

### Actual Behaviour

terraform apply times out on resource

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
