### ISSUE TITLE
azurerm_managed_disk storage_account_type does not support Standard_ZRS

### ISSUE THREAD

**Issue by vmninja** [hashicorp/terraform-provider-azurerm#13317]
Using ```Standard_ZRS``` as ```storage_account_type``` results in error:
```
Error: expected storage_account_type to be one of [Standard_LRS Premium_LRS StandardSSD_LRS UltraSSD_LRS], got Standard_ZRS.
```
While Standard_ZRS should be a valid option according to [Azure Docs:](https://docs.microsoft.com/en-us/rest/api/storagerp/srp_sku_types)

Name | Supported Account Kinds | Description
-- | -- | --
Standard_LRS | Storage, BlobStorage, StorageV2 | Standard Locally Redundant Storage
Standard_GRS | Storage, BlobStorage, StorageV2 | Standard Geo Replicated Storage
Standard_RAGRS | Storage, BlobStorage, StorageV2 | Standard Read-Access Geo Replicated Storage
Standard_ZRS | Storage, StorageV2 | Standard Zone Redundant Storage
Premium_LRS | Storage, StorageV2, FileStorage, BlockBlobStorage | Provisioned IO Locally Redundant Storage
Premium_ZRS | Storage, StorageV2 | Provisioned IO Locally Redundant Storage
Standard_GZRS | Storage, StorageV2 | Provisioned IO Locally Redundant Storage
Standard_RAGZRS | Storage, StorageV2 | Provisioned IO Locally Redundant Storage

Snipplet that generates the error:
```
resource "azurerm_managed_disk" "azure_disk_zrs_test" {
  name                 = "azure-disk-zrs-test"
  location             = data.azurerm_resource_group.storage.location
  resource_group_name  = data.azurerm_resource_group.storage.name
  storage_account_type = "Standard_ZRS"
  create_option        = "Empty"
  disk_size_gb         = "10"
  tags = {
    environment = data.azurerm_resource_group.storage.name
  }
}
```

**Comment by aristosvo** [comment]
Hi @vmninja! I believe this is[ just recently GA](https://azure.microsoft.com/en-us/updates/zone-redundant-storage-zrs-for-azure-disk-storage-now-generally-available/) and probably the reason for not being available.

Probably a nice first issue to implement! 👍🏽

**Comment by vmninja** [comment]
FYI,

Equivalent AZ CLI:
```
az disk create --name "azure-disk-zrs-test" -g myresourcegroup --size-gb 10 --location westeurope --sku StandardSSD_ZRS
```

However for ```az disk create```, the sku is ```StandardSSD_ZRS```, not ```Standard_ZRS```:
```
az disk create: 'Standard_ZRS' is not a valid value for '--sku'. Allowed values: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS, Premium_ZRS, StandardSSD_ZRS.
Did you mean 'Standard_LRS' ?
```

StandardSSD_ZRS is also not accepted by the module.
