### ISSUE TITLE
azurerm_kubernetes_cluster, node count increased manually terraform forcing replacement

### ISSUE THREAD

**Issue by prateekmanasvi01** [hashicorp/terraform-provider-azurerm#13316]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

resource "azurerm_kubernetes_cluster" "aks-fca" {
  name                = "aks-${local.name-prefix}-${var.env}"
  location            = var.region
  kubernetes_version  = "1.19.7"
  resource_group_name = "rg-${local.name-prefix}-${var.env}"
  dns_prefix          = "aks-${local.name-prefix}-${var.env}"
  node_resource_group = "rg-aks-${local.name-prefix}-${var.env}"
  sku_tier            = var.aks-sku_tier[var.env]
  api_server_authorized_ip_ranges     = []
  enable_pod_security_policy          = false
  local_account_disabled              = false

  linux_profile {
    admin_username = var.aks-user[var.env]

    ssh_key {
      key_data = var.aks-psk[var.env]
    }
  }

  network_profile  {
    network_plugin     = "azure"
    network_policy     = "azure"
    service_cidr       = var.aks-cidr[var.env]
    dns_service_ip     = var.aks-dns[var.env]
    docker_bridge_cidr = "172.17.0.1/24"
    load_balancer_sku  = "Standard"
  }

  default_node_pool {
    name                = "agentpool"
    enable_auto_scaling = false
    node_count          = 5
    enable_host_encryption       = false
    enable_node_public_ip        = false
    fips_enabled                 = false
    node_taints                  = []
    only_critical_addons_enabled = false
    availability_zones  = [1, 2, 3]
    vm_size             = var.aks-vm_size[var.env]
    max_pods            = 50
    vnet_subnet_id      = azurerm_subnet.subnet-fca.id
    tags                         = {}

  }

  lifecycle {
    ignore_changes = [
      kube_admin_config,
      kube_config
    ]
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
        managed                = true
        admin_group_object_ids = var.aks-groups[var.env] 
    }
  }  
 
  addon_profile {

      oms_agent {
          enabled                    = true
          log_analytics_workspace_id = azurerm_log_analytics_workspace.law-fca.id
      }

      http_application_routing {
              enabled                = false
            }

      ingress_application_gateway {
              enabled                = false
            } 
  }

  tags = local.tags

}
node count was earlier 3, manually changed to 5 from UI, added the same to terraform config getting a cluster replacement.

### Debug Output

-/+ resource "azurerm_kubernetes_cluster" "aks-fca" {
      - api_server_authorized_ip_ranges     = [] -> null
      ~ fqdn                                = "aks-fca-we-dev-2c149ef1.hcp.westeurope.azmk8s.io" -> (known after apply) 
      ~ id                                  = "/subscriptions/8a656f13-ae6c-4832-9b25-281f59301a4e/resourcegroups/rg-fca-we-dev/providers/Microsoft.ContainerService/managedClusters/aks-fca-we-dev" -> (known after apply)
      ~ kube_admin_config                   = [
          - {
              - client_certificate     = "***************"
              - client_key             = "R********"
              - cluster_ca_certificate = "******"
              - password               = "******"
              - username               = "******"
            },
        ] -> (known after apply)
      ~ kube_admin_config_raw               = (sensitive value)
      ~ kube_config                         = [
          - {
              - client_certificate     = ""
              - client_key             = ""
              - cluster_ca_certificate = "********"
              - password               = ""
              - username               = "******"
            },
        ] -> (known after apply)
      ~ kube_config_raw                     = (sensitive value)
        name                                = "******"
      ~ private_cluster_enabled             = false -> (known after apply)
      + private_dns_zone_id                 = (known after apply)
      + private_fqdn                        = (known after apply)
      ~ private_link_enabled                = false -> (known after apply)
        tags                                = {
            "applicationName" = "fca"
            "env"             = "dev"
        }
        # (9 unchanged attributes hidden)

      ~ addon_profile {

          ~ http_application_routing {
              + http_application_routing_zone_name = (known after apply)
                # (1 unchanged attribute hidden)
            }

          ~ ingress_application_gateway {
              + effective_gateway_id                 = (known after apply)
              ~ ingress_application_gateway_identity = [] -> (known after apply)
                # (1 unchanged attribute hidden)
            }

          ~ oms_agent {
              ~ oms_agent_identity         = [
                  - {
                      - client_id                 = "ce47d7a7-56c7-47d6-9fcc-3d929c33e2e4"
                      - object_id                 = "a22565eb-32b0-4e51-97c5-599bb8aa327e"
                      - user_assigned_identity_id = "/subscriptions/8a656f13-ae6c-4832-9b25-281f59301a4e/resourcegroups/rg-aks-fca-we-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/omsagent-aks-fca-we-dev"
                    },
                ] -> (known after apply)
                # (2 unchanged attributes hidden)
            }
        }

      + auto_scaler_profile {
          + balance_similar_node_groups      = (known after apply)
          + empty_bulk_delete_max            = (known after apply)
          + expander                         = (known after apply)
          + max_graceful_termination_sec     = (known after apply)
          + max_node_provisioning_time       = (known after apply)
          + max_unready_nodes                = (known after apply)
          + max_unready_percentage           = (known after apply)
          + new_pod_scale_up_delay           = (known after apply)
          + scale_down_delay_after_add       = (known after apply)
          + scale_down_delay_after_delete    = (known after apply)
          + scale_down_delay_after_failure   = (known after apply)
          + scale_down_unneeded              = (known after apply)
          + scale_down_unready               = (known after apply)
          + scale_down_utilization_threshold = (known after apply)
          + scan_interval                    = (known after apply)
          + skip_nodes_with_local_storage    = (known after apply)
          + skip_nodes_with_system_pods      = (known after apply)
        }

      ~ default_node_pool {
          ~ kubelet_disk_type            = "OS" -> (known after apply)
          - max_count                    = 0 -> null
          - min_count                    = 0 -> null
            name                         = "agentpool"
          ~ node_labels                  = {} -> (known after apply)
          ~ orchestrator_version         = "1.19.7" -> (known after apply)
          ~ os_disk_size_gb              = 128 -> (known after apply)
          + os_sku                       = "Ubuntu" # forces replacement
          - tags                         = {} -> null
            # (14 unchanged attributes hidden)
        }

      ~ identity {
          ~ principal_id = "c686b0af-5399-4599-a0d9-c538ae641cd5" -> (known after apply)
          ~ tenant_id    = "9690ff2d-0d52-402e-8160-137e6dfd3f64" -> (known after apply)
            # (1 unchanged attribute hidden)
        }

      ~ kubelet_identity {
          ~ client_id                 = "a19a442e-8ccf-4663-a8a6-5f087abe7118" -> (known after apply)
          ~ object_id                 = "7ebbec74-c2d5-4cab-a37b-71bf4734f5fe" -> (known after apply)
          ~ user_assigned_identity_id = "/subscriptions/8a656f13-ae6c-4832-9b25-281f59301a4e/resourceGroups/rg-aks-fca-we-dev/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-fca-we-dev-agentpool" -> (known after apply)       
        }

      ~ network_profile {
          + network_mode       = (known after apply)
          + pod_cidr           = (known after apply)
            # (7 unchanged attributes hidden)

          ~ load_balancer_profile {
              ~ effective_outbound_ips    = [
                  - "/subscriptions/8a656f13-ae6c-4832-9b25-281f59301a4e/resourceGroups/rg-aks-fca-we-dev/providers/Microsoft.Network/publicIPAddresses/eadb83f4-2de2-400c-b4bc-11c43a382bd5",
                ] -> (known after apply)
              ~ idle_timeout_in_minutes   = 0 -> (known after apply)
              ~ managed_outbound_ip_count = 1 -> (known after apply)
              ~ outbound_ip_address_ids   = [] -> (known after apply)
              ~ outbound_ip_prefix_ids    = [] -> (known after apply)
              ~ outbound_ports_allocated  = 0 -> (known after apply)
            }
        }

      ~ role_based_access_control {
            # (1 unchanged attribute hidden)

          ~ azure_active_directory {
              - azure_rbac_enabled     = false -> null
              ~ tenant_id              = "9690ff2d-0d52-402e-8160-137e6dfd3f64" -> (known after apply)
                # (2 unchanged attributes hidden)
            }
        }

      - timeouts {}

      ~ windows_profile {
          + admin_password = (sensitive value)
          ~ admin_username = "azureuser" -> (known after apply)
          + license        = (known after apply)
        }
        # (1 unchanged block hidden)
    }

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aristosvo** [comment]
Hi @prateekmanasvi01!

In the output it is given that `os_sku`, a new feature, is triggering the replacement (`+ os_sku = "Ubuntu" # forces replacement`). Changing `node_count` without changing provider versions would've caused no problems.

The issue around `os_sku` might have already been reported in #13306, making this a duplicate.

**Comment by tombuildsstuff** [comment]
Consolidating into #13312
