### ISSUE TITLE
Updating Key Vault Certificate tags incorrectly forces resource replacement 

### ISSUE THREAD

**Issue by troyready** [hashicorp/terraform-provider-azurerm#13315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.74.0
```

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_certificate" "cert" {
  ...
  tags = { environment = "test" }
}
```

### Expected Behaviour

Changing the resource `tags` property [updates the resource without replacement](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/keyvault/v7.0/keyvault#BaseClient.UpdateCertificate).

### Actual Behaviour

Changing the resource `tags` property [causes the resource to be replaced](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.75.0/internal/services/keyvault/key_vault_certificate_resource.go#L390).

### Steps to Reproduce

1. Deploy the resource
2. Change the value of the `tags` property

**Comment by troyready** [comment]
> ... there's no update method for key vault certificate in rest api

I don't believe this is correct - the relevant api [is here](https://github.com/Azure/azure-rest-api-specs/blob/1e2c9f3ec93078da8078389941531359e274f32a/specification/keyvault/data-plane/Microsoft.KeyVault/stable/7.2/certificates.json#L705-L760).

I'm pretty sure this wasn't originally supported in the API, so it makes sense that Terraform didn't support it previously. But now that the API has been fixed, it'd be nice to do the same for Terraform.

**Comment by lonegunmanb** [comment]
Hello @troyready ,

I think you are right, I hope this pr would solve this issue.
