### ISSUE TITLE
Application Gateway does not support "Standard" SKUs

### ISSUE THREAD

**Issue by mitchellkingsley** [hashicorp/terraform-provider-azurerm#13329]
### Terraform (and AzureRM Provider) Version
```
Terraform v1.0.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
```
### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files
```hcl
resource "azurerm_application_gateway" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 1
  }
...
```

### Expected Behaviour

When modifying an existing application gateway with the following changes:
```
~ sku {
    ~ capacity = 2 -> 1
    ~ name     = "Standard_v2" -> "Standard_Small"
    ~ tier     = "Standard_v2" -> "Standard"
}
```

The changes are made without error.

### Actual Behaviour

The listed changes above cause the following errors after confirming a `terraform apply` command:
```
│ Error: creating/updating Application Gateway: (Name "ecample" / Resource Group "example"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ApplicationGatewayFeatureCannotBeEnabledForSelectedSku" Message="Application Gateway /subscriptions/XXXXXXXXXXXXXXXXX/resourceGroups/example/providers/Microsoft.Network/applicationGateways/unit_gateway does not support Identity for the selected SKU tier Standard. Supported SKU tiers are Standard_v2,WAF_v2." Details=[]
```
### Important Factoids

- The existing application gateway has path based routing and `HTTP -> HTTPS` redirection
- The current [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway) includes the `Standard` tier as a valid option.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiaxyi** [comment]
@mitchellkingsley , I tested the user case, seemed the SKU is not able to be modified directly if the action is change the SKU tier. we can verify the same behavior from the azure portal, the option provided is the same tier,  for example, from standard_v2 to WAF_v2:
![image](https://user-images.githubusercontent.com/92154856/140016616-5d15f729-b7fc-4ff6-8a7f-aac7fa2ceb8b.png)

**Comment by xiaxyi** [comment]
@mitchellkingsley, after further confirmation. the SKU cannot be switched between families, for example, be moved from standard_v2 to standard. hope it helps!

**Comment by mybayern1974** [comment]
@mitchellkingsley given seems this infeasibility is by Azure service design (assume there is no way to do that, not only in using Terraform), so would you be okey if we close this issue?

**Comment by mybayern1974** [comment]
Closing or feel free to suggest to reopen if there are different opinions.
