### ISSUE TITLE
azurerm_api_management_api Terraform saves Open API contract in its state when import fails, leading to unexpected behavior

### ISSUE THREAD

**Issue by robinkb** [hashicorp/terraform-provider-azurerm#13325]
I am not completely sure if this bug is caused by this provider, or by the Terraform core.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.76.0

### Affected Resource(s)

* `azurerm_api_management_api`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "microservices" {
  for_each = local.microservices

  name                  = "API-${each.key}"
  resource_group_name   = "rg-${var.env}"
  api_management_name   = "apim-${var.customer}-${var.env}"
  revision              = "1"
  display_name          = "API-${each.key}"
  path                  = each.key
  protocols             = ["http", "https"]
  subscription_required = false

  import {
    content_format = "openapi"
    content_value  = file("docs/${each.value.docs_file}")
  }
}
```

### Expected Behaviour

1. Terraform reads the OpenAPI contract from disk.
2. Terraform checks the YAML against its state.
3. Terraform detects a change and attempts to import the new contract into API Management.
4. Because import fails, so Terraform does not persist the new contract into its own state.
5. Running Terraform again shows a diff for the API that was not successfully imported, and the import is attempted again.

### Actual Behaviour

1. Terraform reads the OpenAPI contract from disk.
2. Terraform checks the YAML against its state.
3. Terraform detects a change and attempts to import the new contract into API Management.
4. Even though the import fails, Terraform persists the new contract into its own state.
5. Running Terraform again no longer shows a diff and the import is not attempted again until the contract changes.

### Steps to Reproduce

1. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
