### ISSUE TITLE
azurerm_app_service ip restriction blocks not working

### ISSUE THREAD

**Issue by TPPWC** [hashicorp/terraform-provider-azurerm#13327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v2.76.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
dynamic "ip_restriction" {
         for_each = length(var.ip_restrictions) > 0 ? var.ip_restrictions : null
         content {
           ip_address  = ip_restriction.value
         }
       }

    dynamic "ip_restriction" {
         for_each = length(var.ip_restriction_subnet) > 0 ? var.ip_restriction_subnet : null
         content {
           virtual_network_subnet_id  = ip_restriction.value
         }
       }
```

### Expected Behaviour

Should add an ip address and a subnet to the firewall setting

### Actual Behaviour

Getting this error:

> Original Error: Code="BadRequest" Message="IpSecurityRestriction is invalid.  Only IpAddress or VnetSubnetResourceId property must be specified." Details=[{"Message":"IpSecurityRestriction is invalid.  Only IpAddress or VnetSubnetResourceId property must be specified."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51021","Message":"IpSecurityRestriction is invalid.  Only IpAddress or VnetSubnetResourceId property must be specified.","MessageTemplate":"{0} is invalid.  {1}","Parameters":["IpSecurityRestriction","Only IpAddress or VnetSubnetResourceId property must be specified."]}}]

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
