### ISSUE TITLE
Api Management external redis cache association not working

### ISSUE THREAD

**Issue by uolter** [hashicorp/terraform-provider-azurerm#13323]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.70.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

* `azurerm_api_management_redis_cache`

### Terraform Configuration Files

```hcl

resource "azurerm_api_management_redis_cache" "this" {
  name              = format("%s-redis", var.name)
  api_management_id = azurerm_api_management.this.id
  connection_string = var.redis_connection_string
  redis_cache_id    = var.redis_cache_id
  cache_location    = var.location
}

```
Since this piece of code is included a module we published publicly I also provide here the link to the github repository:

[pagopa/azurerm](https://github.com/pagopa/azurerm/blob/main/api_management/main.tf)

### Expected Behaviour

I am expecting to see my redis instance associated as external cache in the api management.  
### Actual Behaviour

Apparently from the portal it looks like associated, but I don't see any cache hits and when I try to expand the External cache row in the portal no cache instance is associated: only the location and  the connection string are filled.

### Steps to Reproduce

1. `terraform apply`
2. Go to the api management in the portal and click in the Overview: external cache 
3. Expand the row presenting your redis cache. Something like:
West Europe |   /subscriptions/4d177xxxxxxxxxxxxxxxxxxxx/resourceGroups/cstar-d-api-rg/providers/Microsoft.ApiManagement/service/cstar-d-apim/caches/cstar-d-apim-redis | {{613fxxxxxxx}} | https://management.azure.com//subscriptions/4d177xxxxxxxxxxxxxx/resourceGroups/cstar-d-db-rg/providers/Microsoft.Cache/Redis/cstar-d-redis |  
 4. Check the list box at the top of the window: Cache Instance

<br class="Apple-interchange-newline">

### References

* #0000

**Comment by mybayern1974** [comment]
Closing this issue given the [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/14208)fixing it has been released in v2.86.0. Please let us know if this issue needs to be reactivated for issue not being resolved with the new AzureRM provider version.
