### ISSUE TITLE
Error: Application Insights "blah-appi" (Resource Group "blah-rg") was not found 

### ISSUE THREAD

**Issue by jeremypope-valpak** [hashicorp/terraform-provider-azurerm#13326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform version: 0.14.11 
AzureRM Provider version 2.70.0

### Affected Resource(s)

azurerm_application_insights

### Terraform Configuration Files

data "azurerm_application_insights" "legacy-calculatepackaginggroupweights" {
  name                = "${local.prefix}-epic-legacy-calculatepackaginggroupweights-appi"
  resource_group_name = azurerm_resource_group.legacy-backgroundservicehost.name
}

### Debug Output

Error: Application Insights "blah-dev-epic-legacy-calculatepackaginggroupweights-appi" (Resource Group "blah-dev-epic-legacy-backgroundservicehost-rg") was not found

  on 4_insights.tf line 401, in data "azurerm_application_insights" "legacy-calculatepackaginggroupweights":
 401: data "azurerm_application_insights" "legacy-calculatepackaginggroupweights" {

2021-09-13T10:29:32.858Z [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/2.70.0/linux_amd64/terraform-provider-azurerm_v2.70.0_x5 pid=1490

### Expected Behaviour

New application insight to be created in existing resource group

### Actual Behaviour

Resource group wasn't found.

Azure Activity logs show no changes have been made to the Resource Group since the last successful run resources listed in the state file apparently exist.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

This was run in Terraform Cloud

**Comment by tombuildsstuff** [comment]
hi @jeremypope-valpak 

Thanks for opening this issue.

Taking a look through this appears to be a configuration/usage question - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by jeremypope-valpak** [comment]
I'll do as you ask, but I don't see this as a question asking for help.  Rather, this is a report of a behavioural change from something that worked two months ago and which now fails to add new resources to existing Terraform managed resource groups that apparently now can't be found, although they clearly exist as far as the Azure Portal is concerned.
