### ISSUE TITLE
Cosmos SQL Container Excluded Path not Updating with new path

### ISSUE THREAD

**Issue by Zman94** [hashicorp/terraform-provider-azurerm#13330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_cosmosdb_sql_container`

### Terraform Configuration Files

```hcl
### Containers ###
resource "azurerm_cosmosdb_sql_container" "server_containers" {
  for_each = var.server_db_containers

  name                = each.value.name
  resource_group_name = module.rg.name
  account_name        = azurerm_cosmosdb_account.griffin_account.name
  database_name       = azurerm_cosmosdb_sql_database.server.name

  partition_key_path = each.value.partition_key_path
  dynamic "unique_key" {
    for_each = each.value.unique_keys
    content {
      paths = unique_key.value.paths
    }
  }

  indexing_policy {
    indexing_mode = each.value.indexing_policy.indexing_mode
    dynamic "included_path" {
      for_each = each.value.indexing_policy.included_paths
      content {
        path = included_path.value.path
      }
    }
    dynamic "excluded_path" {
      for_each = each.value.indexing_policy.excluded_paths
      content {
        path = excluded_path.value.path
      }
    }
  }

  analytical_storage_ttl = each.value.analytical_storage_ttl
  conflict_resolution_policy {
    mode                     = each.value.conflict_resolution_policy.mode
    conflict_resolution_path = each.value.conflict_resolution_policy.conflict_resolution_path
  }
}
```
And the container that is having the issue
```
sql_containers = {
    metrics = {
      name               = "metrics"
      partition_key_path = "/id"
      unique_keys        = {}
      indexing_policy = {
        indexing_mode  = "Consistent"
        included_paths = {}
        excluded_paths = { path1 = { path = "/*" }, path2 = { path = "/\"_etag\"/?" } }
      }
      analytical_storage_ttl = -1
      conflict_resolution_policy = {
        mode                     = "LastWriterWins"
        conflict_resolution_path = "/_ts"
      }
    }
}
```

### Debug Output

https://gist.github.com/Zman94/30e405759df06bb55e050220dc158bad

### Expected Behaviour

Container should have the added `excluded_path`

### Actual Behaviour

Container has the `excluded_path` in the Azure portal, but every apply attempts to create the `excluded_path` again.

### Steps to Reproduce

Use the container listed. I believe the issue is with the path `"/\"_etag\"/?"`. This path adds successfully for `included_path`.

1. `terraform apply`

### Important Factoids

We are using Terragrunt to orchestrate variables and HCL files across environments.

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
