### ISSUE TITLE
azurerm_application_insights asks for workspace_id but requires id of the azurerm_log_analytics_workspace in lower case

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform-provider-azurerm#13348]
### Terraform Version

```
Terraform v1.0.6
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.75.0
```

### Expected Behavior
```
resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  workspace_id        = azurerm_log_analytics_workspace.example.workspace_id
  application_type    = "web"
}
```

### Actual Behavior
```
resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  workspace_id        = azurerm_log_analytics_workspace.example.id
  application_type    = "web"
}
```

### Additional Context
On the resource "azurerm_log_analytics_workspace" : 
- The **id** is The Log Analytics Workspace ID.
- The **workspace_id** is The Workspace (or Customer) ID for the Log Analytics Workspace.

And it requires it in lower case, when using a data source on azurerm_log_analytics_workspace we are asked to update the resource --> 
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_application_insights.ains["xxx"] will be updated in-place
  ~ resource "azurerm_application_insights" "ains" {
        id                                    = "/subscriptions/xxx/resourceGroups/xxx/providers/microsoft.insights/components/xxx"
        name                                  = "xxx"
      ~ workspace_id                          = "/subscriptions/xxx/resourcegroups/xxx/providers/microsoft.operationalinsights/workspaces/xxx" -> "/subscriptions/xxxxxx/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/xxx"
        # (12 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

**Comment by dhtek** [comment]
Same issue for me with a new clean deployment.

workspace_id = azurerm_log_analytics_workspace.default.id -> no error when executing the Terraform apply but the change is not applied in the Azure portal and App Insights is still the using the old way.

workspace_id = azurerm_log_analytics_workspace.default.workspace_id -> error when executing terraform plan with the following error: Can not parse "workspace_id" as a resource id: Cannot parse Azure ID: parse "a_guid": invalid URI for request

**Comment by DaleyKD** [comment]
Any update on this? Can someone from TF submit a ticket to MSFT?

**Comment by matbest1** [comment]
Same problem here:

```
resource "azurerm_log_analytics_workspace" "this" {
  name                = "${local.stack_name}-la"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  sku                 = "PerGB2018"
  retention_in_days   = 90
}

resource "azurerm_application_insights" "this" {
  name                = "${local.stack_name}-ai"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  workspace_id        = azurerm_log_analytics_workspace.this.id
  application_type    = "web"
}
```

```
 ~ workspace_id  = "/subscriptions/xxx/resourcegroups/demo-group/providers/microsoft.operationalinsights/workspaces/xxx-demo-la" -> "/subscriptions/xxx/resourceGroups/demo-group/providers/Microsoft.OperationalInsights/workspaces/xxx-demo-la" # forces replacement
```

```
Terraform v1.2.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.19.1
```

@ms-henglu Could you please have a look at this? Noticed that you commented a similar issue #18030

**Comment by AshutoshNirkhe** [comment]
Seems like this same issue is coming even after using v3.21.1,
`parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"`

**Comment by mgattei** [comment]
The issue is still present.

I have tried:
Deleting Log Analytics Workspace resource from state
Deleting Application Insights resource from state
Imported them back, but the provider still asks for recreation.

Can anyone please have a look? Or has anyone any suggestion? I can't update my infrastructure since I have some important data on AI and they will be lost if I recreate the resource...
