### ISSUE TITLE
azurerm_sql_failover_group Always Creates a new Secondary Database

### ISSUE THREAD

**Issue by Coombszy** [hashicorp/terraform-provider-azurerm#13351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v1.0.1
* AzureRM Provider version: v2.76.0

### Affected Resource(s)

* `azurerm_sql_failover_group`

### Terraform Configuration Files

I am using the sample provided in this repository, [examples/sql-azure/failover_group](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/sql-azure/failover_group).  

### Expected Behaviour

When creating an azurerm_sql_failover_group you should be able to point to an existing secondary database resource so that it can be managed by Terraform (as explained in the docs linked below).

> ...If the secondary databases need to be managed through Terraform, they should be defined as resources and a dependency added to the failover group to ensure the secondary databases are created first. Please refer to the detailed example which can be found in the ./examples/sql-azure/failover_group directory within the Github Repository...

### Actual Behaviour

No matter what you do, the creation of the azurerm_sql_failover_group will result in an additional database being created. Using the example provided in the repo, this results in 3 databases. 1 Primary, 1 Secondary and 1 Duplicate Secondary.

This additional Duplicate Secondary is not, and cannot be, managed by Terraform.

### Steps to Reproduce

1. Pull this repo and use [example config](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/sql-azure/failover_group). 
2. `terraform apply`

### Important Factoids

* Running in UK Azure.
* Logging in to Azure via `az login`

### References

* [Terraform Documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_failover_group#mode)

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
