### ISSUE TITLE
Segfault in `terraform plan` possibly related to azurerm_app_service_managed_certificate

### ISSUE THREAD

**Issue by pkgw** [hashicorp/terraform-provider-azurerm#13353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
```

### Affected Resource(s)

* `azurerm_app_service_managed_certificate`

### Terraform Configuration Files

See: https://github.com/WorldWideTelescope/wwt-terraform-infra/tree/master/website

### Debug Output

**edit:** log deleted since I'm worried it might contain secrets and AFAICT it is not at all necessary to solving this issue

### Panic Output

No crash.log since the plugin panicked, not terraform itself:

```
Stack trace from the terraform-provider-azurerm_v2.41.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4602981]

goroutine 1345 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web.resourceArmAppServiceManagedCertificateRead(0xc0024839d0, 0x49ab0c0, 0xc000346600, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/web/app_service_managed_certificate_resource.go:223 +0x681
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc001049a70, 0xc00163cff0, 0x49ab0c0, 0xc000346600, 0xc00182aa20, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:460 +0x129
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000296de8, 0x56fdcc0, 0xc0012cadb0, 0xc0022e7800, 0xc000296de8, 0xc0012cadb0, 0xc00216fb78)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x4dfb920, 0xc000296de8, 0x56fdcc0, 0xc0012cadb0, 0xc0022e77a0, 0x0, 0x56fdcc0, 0xc0012cadb0, 0xc00124a000, 0x37d)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00028bc80, 0x5742540, 0xc000001e00, 0xc0016cb400, 0xc000923500, 0x84cddf0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc00028bc80, 0x5742540, 0xc000001e00, 0xc0016cb400, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1313 +0xd34
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc000c84160, 0xc00028bc80, 0x5742540, 0xc000001e00, 0xc0016cb400)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:722 +0xa5
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:720 +0xa5

Error: The terraform-provider-azurerm_v2.41.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Not crash.

### Actual Behaviour

Crash.

### Steps to Reproduce

1. `terraform plan -var-file=prod.tfvars`

### Important Factoids

I haven't used this project's Terraform tooling for a while, so the definition files may be quite out of date.

**Comment by pkgw** [comment]
See also #13352 which was file just a few minutes apart from this one!

**Comment by Marcus-James-Adams** [comment]
@pkgw I feel your pain today.

**Comment by pkgw** [comment]
@Marcus-James-Adams The funny thing is that this is literally the first time I've used Terraform in like 9 months, but apparently I picked just the wrong day to try to change something ...

**Comment by dmueller-tetra** [comment]
Also experiencing this.

**Comment by sravansagi** [comment]
We are also experiencing it ... Everything is working fine till last week ..

**Comment by vpetersen** [comment]
I have a ticket open with Microsoft about this, there is something going on with their API.

**Comment by mpanasiuk-apptio** [comment]
We started experiencing this withing last couple of days.
It affects other azurerm resource types, not just `azurerm_app_service_managed_certificate` as indicated in this ticket title. Some of our resources affected:

* azurerm_application_insights
* azurerm_app_service_certificate
* azurerm_key_vault
* azurerm_log_analytics_workspace
* azurerm_monitor_autoscale_setting
* azurerm_monitor_metric_alert
* azurerm_storage_queue

@vpetersen do you mind sharing your Microsoft ticket so we can upvote and/or escalate it?

**Comment by vpetersen** [comment]
> @vpetersen do you mind sharing your Microsoft ticket so we can upvote and/or escalate it?

2109130040008895

**Comment by vpetersen** [comment]
They just updated me and stated that the following values will be null/empty going forward via API:

Thumbprint
Issuer
IssueDate
ExpirationDate

**Comment by vietanhtran16** [comment]
we are also experiencing the same issue with `azurerm_app_service_managed_certificate` and `azurerm_app_service_slot`

**Comment by aristosvo** [comment]
> They just updated me and stated that the following values will be null/empty going forward via API:
> 
> Thumbprint
> Issuer
> IssueDate
> ExpirationDate

Is there a reason to break this? It's not that hard to fix `azurerm_app_service_managed_certificate` to make these values conditional, but I prefer to have a proper explanation with it.

**Comment by AdamCoulterOz** [comment]
This has just caused a major disruption to us, we are in the middle of a very large scale go-live. Does anyone have a contact who's looking after this at Microsoft?

**Comment by aristosvo** [comment]
I've created a PR which targets the error shown in the trace, I'll need to run some tests to make sure this is the actual fix

**Comment by AdamCoulterOz** [comment]
> I've created a PR which targets the error shown in the trace, I'll need to run some tests to make sure this is the actual fix.
> 
> @AdamCoulterOz Is it possible to do the release based on a build of my PR branch?

I’m reluctant to push in a change here based on a breaking API change microsoft has made… I’m in the process of escalating this at microsoft to get it rolled back.

**Comment by aristosvo** [comment]
> > I've created a PR which targets the error shown in the trace, I'll need to run some tests to make sure this is the actual fix.
> > @AdamCoulterOz Is it possible to do the release based on a build of my PR branch?
> 
> I’m reluctant to push in a change here based on a breaking API change microsoft has made… I’m in the process of escalating this at microsoft to get it rolled back. There could be other things broken too.

Sure thing! Just offering the option, the `plan` should at least show whether this issue is still facing or not

**Comment by tombuildsstuff** [comment]
@JeffreyRichter heads up this is a breaking behavioural change to the App Service API

**Comment by vietanhtran16** [comment]
hey guys, when would this fix be released because without it, we are unable to deploy? Is there a workaround that we can use in the meantime? Also, did Microsoft get back on why the breaking changes was introduce? Thanks 👍

**Comment by JeffreyRichter** [comment]
FYI: I have reached out to an App Service PM to discuss this. I have not heard back from them yet.

**Comment by vpetersen** [comment]
> hey guys, when would this fix be released because without it, we are unable to deploy? Is there a workaround that we can use in the meantime? Also, did Microsoft get back on why the breaking changes was introduce? Thanks 👍

They wanted the certificates to be fully managed, there was a blog article about it in May apparently. https://azure.github.io/AppService/2021/05/25/App-Service-Managed-Certificate-GA.html

_There is an upcoming plan to remove thumbprint information from both portal and API to provide our customers a more managed experience for certificates without having to worry about all the details. Also, App Service Managed Certificate is not meant to be used as a client certificate._

I am also wondering when the release is scheduled, I saw on the 2.77 milestone that it's flagged for tomorrow, I'm hoping that means it's available tomorrow? 

In the meantime, I've had to remove the code, remove the certificate from my state file and then configure it manually using the canary site. https://aka.ms/canary

**Comment by aristosvo** [comment]
> hey guys, when would this fix be released because without it, we are unable to deploy? Is there a workaround that we can use in the meantime? Also, did Microsoft get back on why the breaking changes was introduce? Thanks 👍 

tomorrow @ around 1600 pst 🙂

**Comment by skerr4311** [comment]
The cert issue has had me in debug mode for a while now. Thanks for the update

**Comment by AdamCoulterOz** [comment]
Hey guys, this also has an impact on `azurerm_app_service_custom_hostname_binding` as it is the resource used to bind all types of certificates to the actual web app endpoints. @aristosvo has this been accounted for?

**Comment by aristosvo** [comment]
@AdamCoulterOz No, it's not! I'll check it and make a new PR if necessary.

**Comment by jackofallops** [comment]
> FYI: I have reached out to an App Service PM to discuss this. I have not heard back from them yet.

@JeffreyRichter - For additional context, this change renders users unable to bind certificates to hostnames as `thumbprint` is a required property in that flow and there now does not seem to be a way to retrieve that information?

**Comment by andycoderapptio** [comment]
I'm still having the issue with the 2.77 version, was there a flag or setting we need to change to use the fix? I also noticed we are using an older version (1.1) of azuread would this fix depend on a newer version? Tried moving to 2.3.0 but seems there are some breaking changes.

**Comment by aristosvo** [comment]
@andycoderapptio Can you post your stack trace?

**Comment by andycoderapptio** [comment]
I can give a few examples of errors  I'm seeing: 

Error: Request cancelled

resource "azurerm_monitor_action_group"
 The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

Error: Plugin did not respond
resource "azurerm_monitor_action_group"
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

And seeing "Error: Plugin did not respond" on many modules such as
"azurerm_application_insights"
"azurerm_storage_queue"
"azurerm_app_service_plan"
"azurerm_key_vault"
I can list more if helpful but it's basically on all our resource types 

Stack trace from the terraform-provider-azurerm_v2.77.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x632479c]

goroutine 499 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceCertificateRead(0xc001d4ad00, 0x67678e0, 0xc000166700, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/web/app_service_certificate_resource.go:257 +0x77c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0012e9420, 0x77fe048, 0xc0017678c0, 0xc001d4ad00, 0x67678e0, 0xc000166700, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0012e9420, 0x77fe048, 0xc0017678c0, 0xc0003f8460, 0x67678e0, 0xc000166700, 0xc001bc7108, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000058c0, 0x77fe048, 0xc0017678c0, 0xc001767900, 0xc0017678c0, 0xd9beca, 0x6aab180)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x45b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001897b20, 0x77fe0f0, 0xc0017678c0, 0xc0023fc600, 0xc001897b20, 0xc000d82090, 0xc0007e7ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6c7d560, 0xc001897b20, 0x77fe0f0, 0xc000d82090, 0xc0023fc4e0, 0x0, 0x77fe0f0, 0xc000d82090, 0xc0025de380, 0x341)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b6540, 0x784f6d8, 0xc00007fc80, 0xc000cc9680, 0xc001628ae0, 0xb47c550, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0001b6540, 0x784f6d8, 0xc00007fc80, 0xc000cc9680, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0005f0170, 0xc0001b6540, 0x784f6d8, 0xc00007fc80, 0xc000cc9680)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.77.0_x5.exe plugin crashed!

**Comment by aristosvo** [comment]
@andycoderapptio I've located the problem, but this is weird from my point of view. I would've thought only managed certificates would be affected, can you share how the failing `app_service_certificate` is fitting in your configuration?

**Comment by mpanasiuk-apptio** [comment]
@aristosvo - it fails for us like this:
```
Stack trace from the terraform-provider-azurerm_v2.77.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x58a2b1c]

goroutine 698 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceCertificateRead(0xc003318e00, 0x5ce4b60, 0xc000fae000, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/web/app_service_certificate_resource.go:257 +0x75c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc0012ec1c0, 0x6d78a28, 0xc0017f48c0, 0xc003318e00, 0x5ce4b60, 0xc000fae000, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0012ec1c0, 0x6d78a28, 0xc0017f48c0, 0xc00033f810, 0x5ce4b60, 0xc000fae000, 0xc0006e83d0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000820918, 0x6d78a28, 0xc0017f48c0, 0xc0017f4900, 0xc0017f48c0, 0x40b965, 0x6028e40)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001d047c0, 0x6d78ad0, 0xc0017f48c0, 0xc0006e5140, 0xc001d047c0, 0xc000831620, 0xc00228dba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x61fac80, 0xc001d047c0, 0x6d78ad0, 0xc000831620, 0xc0006e50e0, 0x0, 0x6d78ad0, 0xc000831620, 0xc00158e380, 0x341)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000a0e700, 0x6dc9858, 0xc000602600, 0xc00160c6c0, 0xc000830ab0, 0xa9e6610, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000a0e700, 0x6dc9858, 0xc000602600, 0xc00160c6c0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0008fafa0, 0xc000a0e700, 0x6dc9858, 0xc000602600, 0xc00160c6c0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.77.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

Do we need to make a similar change you've done to `app_service_managed_certificate_resource.go` but to `app_service_certificate_resource.go`?

```
diff --git a/internal/services/web/app_service_certificate_resource.go b/internal/services/web/app_service_certificate_resource.go
index 917338bc2..2e2da1640 100644
--- a/internal/services/web/app_service_certificate_resource.go
+++ b/internal/services/web/app_service_certificate_resource.go
@@ -254,7 +254,11 @@ func resourceAppServiceCertificateRead(d *pluginsdk.ResourceData, meta interface
                d.Set("subject_name", props.SubjectName)
                d.Set("host_names", props.HostNames)
                d.Set("issuer", props.Issuer)
-               d.Set("issue_date", props.IssueDate.Format(time.RFC3339))
+               issueDate := ""
+               if props.IssueDate != nil {
+                       issueDate = props.IssueDate.Format(time.RFC3339)
+               }
+               d.Set("issue_date", issueDate)
                d.Set("expiration_date", props.ExpirationDate.Format(time.RFC3339))
                d.Set("thumbprint", props.Thumbprint)
```

**Comment by aristosvo** [comment]
@mpanasiuk-apptio Check this [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/13401), this should solve it

**Comment by mpanasiuk-apptio** [comment]
The resources were initially created manually, and then "terraformed" via `terraform import`. So yeah, it is possible that something got imported incorrectly, e.g. managed cert was imported as unmanaged. I will take a closer look.
