### ISSUE TITLE
Replacing azurerm_app_service_plan of azurerm_function_app isn't synchronized

### ISSUE THREAD

**Issue by sschmeck** [hashicorp/terraform-provider-azurerm#13377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.10
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* `azurerm_app_service_plan`
* `azurerm_function_app`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "0.14.10"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.69.0"
    }
    time = {
      source  = "hashicorp/time"
      version = "0.7.2"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "issue" {
  name     = "app-service-plan-issue"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "shared" {
  name                = "app-service-plan-shared"
  location            = azurerm_resource_group.issue.location
  resource_group_name = azurerm_resource_group.issue.name
  kind                = "elastic"
  sku {
    tier = "ElasticPremium"
    size = "EP1"
  }
}

# REMOVED after first apply
#resource "azurerm_app_service_plan" "dedicated" {
#  name                = "app-service-plan-dedicated"
#  location            = azurerm_resource_group.issue.location
#  resource_group_name = azurerm_resource_group.issue.name
#  kind                = "elastic"
#  sku {
#    tier = "ElasticPremium"
#    size = "EP2"
#  }
#}

locals {
  # REPLACED after first apply
  #app_service_plan_id = azurerm_app_service_plan.dedicated.id
  app_service_plan_id = azurerm_app_service_plan.shared.id
}

# Enforce syncronisation
resource "time_sleep" "delay_function_app_change" {
  create_duration  = "30s"
  destroy_duration = "30s"

  triggers = {
    plan_id = local.app_service_plan_id
  }
}

resource "azurerm_storage_account" "issue" {
  name                     = "appserviceplanissuesa"
  resource_group_name      = azurerm_resource_group.issue.name
  location                 = azurerm_resource_group.issue.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_function_app" "issue" {
  name                       = "app-service-plan-issue-app"
  location                   = azurerm_resource_group.issue.location
  resource_group_name        = azurerm_resource_group.issue.name
  storage_account_name       = azurerm_storage_account.issue.name
  storage_account_access_key = azurerm_storage_account.issue.primary_access_key

  app_service_plan_id = time_sleep.delay_function_app_change.triggers["plan_id"]
}
```

### Debug Output

```
{
  "Code":"Conflict",
  "Message":"Server farm 'app-service-plan-dedicated' cannot be deleted because it has web app(s) app-service-plan-issue-app assigned to it.",
  "Target":null,
  "Details":[{"Message":"Server farm 'app-service-plan-dedicated' cannot be deleted because it has web app(s) app-service-plan-issue-app assigned to it."},{"Code":"Conflict"},{"ErrorEntity":{"ExtendedCode":"11003","MessageTemplate":"Server farm '{0}' cannot be deleted because it has web app(s) {1} assigned to it.","Parameters":["app-service-plan-dedicated","app-service-plan-issue-app"],"Code":"Conflict","Message":"Server farm 'app-service-plan-dedicated' cannot be deleted because it has web app(s) app-service-plan-issue-app assigned to it."}}],
  "Innererror":null
}: timestamp=2021-09-17T07:56:20.744+0200

2021/09/17 07:56:20 [DEBUG] azurerm_app_service_plan.dedicated: apply errored, but we're indicating that via the Error pointer rather than returning it: 
  Error deleting App Service Plan "app-service-plan-dedicated" (Resource Group "app-service-plan-issue"): 
    web.AppServicePlansClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
```

### Expected Behaviour

It should be possible to replace an existing `azurerm_app_service_plan` of a `azurerm_function_app` by another one. The `apply` command should run successfully. It should update the `azurerm_function_app` before deleting the obsolete `azurerm_app_service_plan`. 

### Actual Behaviour

The `apply` command fails sporadically while deleting the `azurerm_app_service_plan` because of the still assigned `azurerm_function_app`.

### Steps to Reproduce

```
# 1. Create resource group 2 Plans and assign the `dedicated` Plan to the Function App.
# (You need to change the provided configuration above)
$ terraform apply

# 2. Remove the `dedicated` Plan and assign the `shared` Plan to the Function App.
# (Provided configuration above)
$ terraform apply
```

### References

* #5990
* #3036

**Comment by sschmeck** [comment]
As workaround you could delay the `destroy` by using `time_sleep`. You need to add and `apply` the `time_sleep` resource before you remove the obsolete `azurerm_app_service_plan`.

1. Add `time_sleep` and run `apply`
   ```hcl
   resource "time_sleep" "delay_service_plan_destroy" {
     destroy_duration = "90s"
     depends_on = [azurerm_app_service_plan.dedicated]
   }
   ```
2. Remove the obsolete `azurerm_app_service_plan` and run `apply`

**Comment by AmudaPalani** [comment]
Error: deleting App Service Plan "hsidmi-dev-dc1-appsvc-plan" (Resource Group "hsidmi-dev-dc1-rg"): web.AppServicePlansClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Server farm 'hsidmi-dev-dc1-appsvc-plan' cannot be deleted because it has web app(s) hsidmi-dev-dc1-appsvc assigned to it." Details=[{"Message":"Server farm 'hsidmi-dev-dc1-appsvc-plan' cannot be deleted because it has web app(s) hsidmi-dev-dc1-appsvc assigned to it."},{"Code":"Conflict"},{"ErrorEntity":{"Code":"Conflict","ExtendedCode":"11003","Message":"Server farm 'hsidmi-dev-dc1-appsvc-plan' cannot be deleted because it has web app(s) hsidmi-dev-dc1-appsvc assigned to it.","MessageTemplate":"Server farm '{0}' cannot be deleted because it has web app(s) {1} assigned to it.","Parameters":["hsidmi-dev-dc1-appsvc-plan","hsidmi-dev-dc1-appsvc"]}}]

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
