### ISSUE TITLE
Support for Synapse Integration runtime

### ISSUE THREAD

**Issue by Satyala** [hashicorp/terraform-provider-azurerm#13381]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To manage an integration runtime in Azure Synapse Studio similar to the Azure Data factory. 

### New or Affected Resource(s)

* azurerm_synapse_integration_runtime_managed
* azurerm_synapse_integration_runtime_self_hosted

### Potential Terraform Configuration

```
## Managed Integration runtime

resource "azurerm_synapse_integration_runtime_managed" "example" {
  name                                   = "example"
  synapse_workspace_name    = azurerm_synapse_workspace.example.name
  resource_group_name          = azurerm_resource_group.example.name
  location                                = azurerm_resource_group.example.location

  compute-type                      = "General"
  core-count                           = 8
}

## SelfHosted Integration runtime

resource "azurerm_synapse_integration_runtime_self_hosted" "example" {
  name                                   = "example"
  synapse_workspace_name    = azurerm_synapse_workspace.example.name
  resource_group_name          = azurerm_resource_group.example.name
  location                                = azurerm_resource_group.example.location  
}

```

### References

https://docs.microsoft.com/en-us/cli/azure/synapse/integration-runtime?view=azure-cli-latest

https://docs.microsoft.com/en-us/powershell/module/az.synapse/set-azsynapseintegrationruntime?view=azps-6.4.0

**Comment by mybayern1974** [comment]
@Satyala , assume what you expect has already been supported?
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_integration_runtime_azure
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_integration_runtime_self_hosted
If so, would you agree if I close this issue?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @mybayern1974‘s response with links as completed. If that is not the case, please provide additional information regarding your feature request, thanks!
