### ISSUE TITLE
Support for Kafka enabled Azure Eventhub namespace

### ISSUE THREAD

**Issue by Farzad-Jalali** [hashicorp/terraform-provider-azurerm#13385]
How can I create an azure event hub namespace that has Kafka enabled?
Currently, I'm doing as below to spin up an azure event hub namespace, but I can't see how can I enable Kafka API for it (Azure has introduced it for 2-3 years now)

```
resource "azurerm_eventhub_namespace" "eventhubNS" {

  name                = "${var.mainPrefix}-eventhub-ns"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "standard"
  capacity            = 7
  auto_inflate_enabled = true
  maximum_throughput_units = 12
  
  tags = {
    environment = var.environment
    owner       = var.owner
  }
}
```

**Comment by arodriguezdlc** [comment]
The Kafka API is always enabled in Eventhubs, so you don't have to enable or disable it. Just use it! :)

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @arodriguezdlc's response as an answer. If you have further questions, we have [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34) that are a great place to ask.
