### ISSUE TITLE
Support for AzureServiceTags UDR Routes

### ISSUE THREAD

**Issue by chris87-concat** [hashicorp/terraform-provider-azurerm#13395]
Microsoft Announced by PublicPreview from march 2021 the functionality to use Azure ServiceTags in the user defined routes. I have a problem otherwise that the limit from 400 routes per route table reached. 

https://azure.microsoft.com/de-de/updates/public-preview-service-tags-for-user-defined-routing/

Please vote the features request for the next azurerm_provider version. 

Thanks a lot of.

**Comment by georgy-varghese** [comment]
Looks like `address_prefix` accepts string. I tried using it and seems to work.

```
  + resource "azurerm_route" "routes" {
      + address_prefix       = "ApiManagement"
      + id                   = (known after apply)
      + name                 = "ControlPlane"
      + next_hop_type        = "Internet"
      + resource_group_name  = "resourcegroup"
      + route_table_name     = "routetbl"
    }
```

**Comment by bubbletroubles** [comment]
This PR is to update the doco - https://github.com/hashicorp/terraform-provider-azurerm/pull/16466
