### ISSUE TITLE
[azurerm_virtual_machine_extension] How to pass --set-access-to-individual-resources switch to azurerm_virtual_machine_extension

### ISSUE THREAD

**Issue by jpbuecken** [hashicorp/terraform-provider-azurerm#13417]
Hello there.

SAP workloads on SLES15 require a new extension. [1] 
SLES15 will drop python2 completely with SLES15 SP4, so the old extension will not work. [3]
~~~
`This module is disabled by default and will be removed entirely starting with SLE 15 SP4.`
~~~

Via cli you get the extension via [2]
```
az vm aem set -g asy-osoc-prod-rg-lvm -n exunxlvp07998 --install-new-extension --set-access-to-individual-resources
```
Installation of this new extension will create an identity in azure.
If --set-access-to-individual-resources is not set, it will create a identity with read permissions on resource group level.

From [2]
--set-access-to-individual-resources
Set the access of the VM identity to the individual resources, e.g. data disks instead of the complete resource group.

We want to pass this option to restrict this identity to VM level.

The question is, is it possible to pass this option to azurerm_virtual_machine_extension.

**Example HCL:**
```hcl
resource "azurerm_virtual_machine_extension" "aem" {
  name                       = "aem"
  virtual_machine_id         = azurerm_linux_virtual_machine.instance.id
  publisher                  = "Microsoft.AzureCAT.AzureEnhancedMonitoring"
  type                       = "MonitorX64Linux"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true
}

```

**Affected Resource:**
- azurerm_virtual_machine_extension

**Documentation:**
[1] https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/deployment-guide#d98edcd3-f2a1-49f7-b26a-07448ceb60ca
[2] https://docs.microsoft.com/en-us/cli/azure/vm/aem?view=azure-cli-latest
[3] https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP3/index.html#jsc-SLE-16746

**Comment by tombuildsstuff** [comment]
hi @jpbuecken 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by jpbuecken** [comment]
Oh sorry. I assumed this issue will end up in a feature enhancements issue since I'm pretty sure it is not possible and I thought only a developer of the provider can proof me wrong. 

Anyway, I will give the Community Resource a try.
