### ISSUE TITLE
Unable to create the synapse service using terraform

### ISSUE THREAD

**Issue by animsri** [hashicorp/terraform-provider-azurerm#13412]
Earlier Synapse uses the data lake gen2 file system, which is deprecated by Azure this year. Now it uses the container for the same. But while creating the synapse using terraform getting below error.

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "datadevstorage"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
  depends_on = [
    azurerm_resource_group.example,
  ]
}

resource "azurerm_storage_container" "example" {
  name                  = "data-dev-container"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
  depends_on = [
    azurerm_storage_account.example,
  ]
}

resource "azurerm_synapse_workspace" "example" {
  name                                 = "synwork123"
  resource_group_name                  = azurerm_resource_group.example.name
  location                             = azurerm_resource_group.example.location
  storage_data_lake_gen2_filesystem_id = azurerm_storage_container.example.id
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = 

  tags = {
    Env = "production"
  }
}

resource "azurerm_synapse_sql_pool" "synapsesqlp" {
  name                 = "alpha12"
  synapse_workspace_id = azurerm_synapse_workspace.example.id
  sku_name             = "DW100c"
  create_mode          = "Default"
}

Error:
creating Synapse Workspace "synwork123" (Resource Group "example-resources"): synapse.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ValidationFailed" Message="Workspace request validation failed, check error details for more information" Details=[{"code":"DefaultDataLakeStorageAccountUrlNotInUriFormat","message":"The default data lake storage account url property should be in the format: https://accountname.dfs.core.windows.net"}]

**Comment by tombuildsstuff** [comment]
hi @animsri 

Thanks for opening this issue.

Taking a look through this appears to be a configuration question, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by animsri** [comment]
Hi tombuildsstuff,

the issue is with terraform scripts.
Azure has decommissioned its datalake storage gen1 services. Blob Container are the new datalake gen2 storage, but while creating the synapse it is asking for datalake gen2 url which is something like this .dfs.core.windows.net but while creating the blob storage we are getting the url of type .blob.core.windows.net/ . which means while validating terraform is getting 403 as this url (.dfs.core.windows.net) doesn’t exist in Azure. 

When I have used the replace command to replace the blob with dfs while creating synapse, it worked for me. I guess somewhere terraform is looking for dfs url if simply pass the container id, and it fails.

Please let me know if you need more information on this issue.

Thanks!!

**Comment by tombuildsstuff** [comment]
@animsri in the configuration above your specifying the Storage Container ID which isn't valid, since that's scoped to the Storage Account:

> storage_data_lake_gen2_filesystem_id = azurerm_storage_container.example.id

Instead you need to specify the DataLake Gen2 File System ID to fix this configuration issue.

**Comment by animsri** [comment]
@tombuildsstuff  That is the issue, We cannot create the Datalake Gen2 File System ID using terraform.

https://azure.microsoft.com/en-gb/updates/azure-data-lake-storage-gen1-account-creation-will-be-blocked-for-new-customers-from-july-1-2021-2/

https://discuss.hashicorp.com/t/failure-responding-to-request-statuscode-403/28261

storage_data_lake_gen2_filesystem_id = replace(azurerm_storage_container.example.id,"blob","dfs")


It worked for me

**Comment by tombuildsstuff** [comment]
@animsri see [this resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem#import) and [this resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_path)

**Comment by animsri** [comment]
Thanks seems it worked for me now :-)
