### ISSUE TITLE
azurerm_cosmosdb_sql_container cannot be created/updated when indexing_mode is "None"

### ISSUE THREAD

**Issue by joachimhalvorsen** [hashicorp/terraform-provider-azurerm#13416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/3lvia/elvid v1.4.1
+ provider registry.terraform.io/hashicorp/azurerm v2.77.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.5.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/vault v2.24.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

Note that the apply was run in terraform enterprise with Terraform v1.0.7 on linux_amd64 

### Affected Resource(s)

* `azurerm_v2.77.0`

### Debug Output

https://gist.github.com/joachimhalvorsen/f430b9ef553b2438a583d86f4368aab2

### Expected Behaviour

azurerm_cosmosdb_sql_container was created/updated

### Actual Behaviour

Error during terraform apply: included_path must not be set if indexing_mode is "None

### Steps to Reproduce
Create resources azurerm_cosmosdb_account, azurerm_cosmosdb_sql_database and azurerm_cosmosdb_sql_container with terraform.

Set indexing_mode to "None" and do not specify included_path in  azurerm_cosmosdb_sql_container.

Note that in my case I have an existing azurerm_cosmosdb_sql_container that we wanted to turn off indexing for.
```
resource "azurerm_cosmosdb_sql_container" "some-name" {
  name                = "some-name"
  resource_group_name = "some resource_group_name"
  account_name        = "some account_name"
  database_name       =  "some database_name "
  partition_key_path  = "/pk"
  autoscale_settings {
    max_throughput = 4000
  }
  indexing_policy {
    indexing_mode = "None"
  }
}
```

1. `terraform apply`

### Important Factoids
 No. This run was done in terraform enterprise

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
