### ISSUE TITLE
azurerm_servicebus_topic_authorization_rule uniqueness

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/terraform-provider-azurerm#13415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
2.66.0

### Affected Resource(s)

* `azurerm_servicebus_topic_authorization_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_topic_authorization_rule" "event_listener_1" {
  name                           = "event-listener"
  namespace_name      = data.azurerm_servicebus_namespace.events.name
  topic_name                 = data.azurerm_servicebus_topic.topic1.name
  resource_group_name = data.azurerm_servicebus_namespace.events.resource_group_name
}

resource "azurerm_servicebus_topic_authorization_rule" "event_listener_2" {
  name                           = "event-listener"
  namespace_name      = data.azurerm_servicebus_namespace.events.name
  topic_name                 = data.azurerm_servicebus_topic.topic2.name
  resource_group_name = data.azurerm_servicebus_namespace.events.resource_group_name
}
```

### Panic Output

Apply does not error.

### Expected Behaviour

Two authorization rules are created

### Actual Behaviour

It appears that authorization rules are not unique to the topic, but are actually unique to the namespace.

Terraform currently lets you create two authorization rules in the same namespace with the same name so long as the topic_name is different, however it shouldn't.

It should take the namespace_name into consideration in the validation of the name.

The resultant behaviour is the rules keep overwriting each other.

**Comment by IanMoroney** [comment]
@favoretti , this isn't actually a question but rather a bug.
Can you re-label it?
Thanks

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
