### ISSUE TITLE
incorrect documentation

### ISSUE THREAD

**Issue by tradosh** [hashicorp/terraform-provider-azurerm#13418]
the example presented here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_instance_blob_storage
is incorrect, attempt to run it as is generate multiple errors

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. This appears to be a duplicate of #13403, therefore I'm going to close this one to keep the discussion concise.
