### ISSUE TITLE
Azure API returns data in different order, so Terraform Sees a change?

### ISSUE THREAD

**Issue by chadcarlton** [hashicorp/terraform-provider-azurerm#13437]
I am seeing terraform want to change resources for meaningless changes (often related to the ordering of list type things). For example below, This resource has not changed, just the ordering returned this particular run from the APIs.

I did not change anything in the below WAF policy plan snippet. As you can see from this Plan, it's going to update the WAF, but not really change anything. We have alerts setup to modifications to the WAF policy, so applying the other items in this larger TF project trigger those alarms.. 

**Can I change anything to prevent these sort of meaningless changes from showing up in plans and applys?** Application Gateway and it's many blocks are another example where I see this occurring.

This is from terraform 1.02/azurerm 2.67 (thought I have also seen this on 2.7)

    # azurerm_web_application_firewall_policy.owasp_only will be updated in-place
      ~ resource "azurerm_web_application_firewall_policy" "owasp_only" {
            id                  = "/subscriptions/ReallingInterestingGUID/resourceGroups/rg-apim/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/ccr-owasp-only"
            name                = "ccr-owasp-only"
            tags                = {
                "created-by"      = bob.jones@jones.com
                "terraform-stack" = "api-gateway"
            }
            # (4 unchanged attributes hidden)
    
          ~ managed_rules {
    
              ~ managed_rule_set {
                  ~ type    = "Microsoft_BotManagerRuleSet" -> "OWASP"
                  ~ version = "0.1" -> "2.2.9"
                }
              ~ managed_rule_set {
                  ~ type    = "OWASP" -> "Microsoft_BotManagerRuleSet"
                  ~ version = "2.2.9" -> "0.1"
                }
           }
    
            # (1 unchanged block hidden)
        }

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
