### ISSUE TITLE
Add CosmosDB read region resource

### ISSUE THREAD

**Issue by idangmic** [hashicorp/terraform-provider-azurerm#1343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add  the ability to  add CosmosDB read region externally to the cosmos_db_account resource as an independent resource 

### New or Affected Resource(s)

* azurerm_cosmos_db_account
* azurerm_cosmosdb_read_region

### Potential Terraform Configuration

```hcl

resource "azurerm_cosmosdb_read_region" "db_r" {

}
```

**Comment by kjhosein** [comment]
I was just about to make what I believe is the same request, i.e. making the `geo_location` sub-block of the `azurerm_cosmosdb_account` resource an (optionally) separate resource. This is very useful when you have a unknown/dynamic # of  failover regions to specify.

**Comment by lrxtom2** [comment]
Hi @idgazit , thanks for opening the issue! This resource `azurerm_cosmosdb_account`  and the field `geo_location` was supported in latest Provider version. Please have check.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider. I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
