### ISSUE TITLE
Terraform considers nodepool is successfully created but it is in failed state

### ISSUE THREAD

**Issue by arodriguezdlc** [hashicorp/terraform-provider-azurerm#13436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.31
AzureRM provider 2.72.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

If the nodepool is in failed state, Terraform should try to reconcile the cluster before consider it as successfully created, if state is not "Success". 

### Actual Behaviour

Terraform is considering that a nodepool is successfully created although it is in failed state. 

### Steps to Reproduce

You need a nodepool in failed state. In my case, I have the nodepool on this state during an AKS upgrade due to timeout when it is moving pods. Executing terraform apply results inmediately in a creation completed, although the nodepool is in failed state.

**Comment by arodriguezdlc** [comment]
This is not the same issue. The issue you mentioned is produced when terraform fails creating the nodepool but AKS retries internally and appears finally as succeded. In my case, the nodepool is already in failed state but, after refresh the state, Terraform considers that this resource in failed state is correctly created. I consider that this is provider bug, because the provider can know that the nodepool is in failed state.

**Comment by tombuildsstuff** [comment]
@arodriguezdlc it's fundamentally the same issue unfortunately - AKS currently exposes no means of knowing whether it's _temporarily_ failed (and will recover) or _permanently_ failed (and won't), both are exposed in the same manner. Once the upstream issue is resolved we'll have the information to be able to differentiate those, but for now we're blocked on the AKS Team providing that information.

**Comment by arodriguezdlc** [comment]
okk @tombuildsstuff, I will subscribe to the other issue. Thank you!
