### ISSUE TITLE
Support for user-assigned managed identities for `azurerm_policy_assignment`

### ISSUE THREAD

**Issue by dhirschfeld** [hashicorp/terraform-provider-azurerm#13433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure policy now supports user-assigned managed identities:
* https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-policy-introduces-user-assigned-msi-support-faster-dine/ba-p/2661073

It would be great if this were supported by `terraform`.

### New or Affected Resource(s)
[`azurerm_policy_assignment`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_assignment)

### References
* https://docs.microsoft.com/en-us/rest/api/policy/policy-assignments/create#userassignedidentities

**Comment by nimmyarjith** [comment]
Yes, this will be really helpful

**Comment by nimmyarjith** [comment]
Any recent plan for this enhancement

**Comment by runemy** [comment]
Also wanted in azurerm_management_group_policy_assignment

**Comment by koikonom** [comment]
This has been addressed in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#resource-azurerm_policy_assignment.

`azurerm_policy_assignment` has been removed, and the resources that replaced it support user-assigned managed identities.
