### ISSUE TITLE
r/api_management - support for publicIpAddressId for multi-zone deployments

### ISSUE THREAD

**Issue by uracharla** [hashicorp/terraform-provider-azurerm#13445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.4

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html
```

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.76.0"
    }
  }
}
```
### Affected Resource(s)

* `azurerm_api_management `

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "main" {
  name                = var.api_management_name
  resource_group_name = var.resource_group_name
  location            = var.api_management_location

  sku_name        = "Premium_3"
  publisher_name  = var.api_management_publisher_name
  publisher_email = var.api_management_publisher_email

  zones = [1,2,3]
  virtual_network_type = var.virtual_network_type

  dynamic "virtual_network_configuration" {
    for_each = var.apim_locations != null ? slice(var.apim_locations, 0, 1) : []
    content {
      subnet_id = data.azurerm_subnet.main[0].id

    }
  }
  dynamic "additional_location" {
    for_each = var.apim_locations != null && var.api_management_sku_name == "Premium_1" ? slice(var.apim_locations, 1, length(var.apim_locations)) : []
    content {
      location = lookup(additional_location.value, "location", null)
      dynamic "virtual_network_configuration" {
        for_each = lookup(additional_location.value, "subnet_name", null) == null ? [] : [1]
        content {
          subnet_id = data.azurerm_subnet.main[index(var.apim_locations, additional_location.value)].id
        }
      }
    }
  }
  tags = var.api_management_tags
}
```

### Actual Behaviour

From the terraform documentation, I was specifying the availiablity zone 1,2,3 and terraform through me the error,
```
{\"error\":{\"code\":\"NotSupported\",\"message\":\"Deploying Microsoft.ApiManagement/service into      
Virtual Network in location `Australia East` and configuring Availability Zones (1,2,3) is only supported  
 in api-version 2021-01-01-preview,2021-04-01-preview,2021-08-01 and setting property   
`publicIpAddressId` is a must. Refer to aka.ms/azurestandardpublicip on how to create a   
Standard SKU Public IP Address resource.\",\"details\":null,\"innerError\":null}}"
```
there is no option to specify the public IP address ID in the terraform resource `azurerm_api_management`

### Steps to Reproduce

1. `terraform apply`

**Comment by lrsvendsen** [comment]
Any updates on the issue?

Being able to set a Public IP address (properties.publicIpAddressId)(1) is also required in order to provision APIM using the stv2(2) Compute Platform.

(1) (https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet?tabs=stv2#prerequisites)

(2) (https://docs.microsoft.com/en-us/rest/api/apimanagement/2021-04-01-preview/api-management-service/create-or-update#code-try-0)

**Comment by asifkd012020** [comment]
Though the API was updated to 2021-08-01 but the support for public IP address is still missing from the input, without which the deployment of multi az apim will still fail.

**Comment by lrsvendsen** [comment]
That PublicIPAddressID has not been implemented from the Azure Go SDK is also blocking issue #12021

**Comment by oWretch** [comment]
I am actively working on this code as we need it for a project. I hope to have a PR early next week to support zones and public ips
