### ISSUE TITLE
Different output on subsequent terraform apply (without configuration changes)

### ISSUE THREAD

**Issue by morariu** [hashicorp/terraform-provider-azurerm#13441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v2.77.0

### Affected Resource(s)

* `azurerm_virtual_network`
*  `azurerm_subnet`

### Terraform Configuration Files

```hcl
---modules---

data "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
}

resource "azurerm_virtual_network" "vnet" {
  name                = var.vnet_name
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  address_space       = var.vnet_address_space
  dns_servers         = var.dns_servers
  subnet              = []
}

resource "azurerm_subnet" "subnet" {
  name                 = var.subnet_name
  resource_group_name  = var.resource_group_name
  virtual_network_name = var.vnet_name
  address_prefixes     = var.subnet_address_space
  enforce_private_link_endpoint_network_policies = var.enforce_private_link_endpoint_network_policies
}

---

module "vnet_gateway_dev" {
    source = "./../../az_modules/vnet"
    
    vnet_name                           = var.vnet_name
    resource_group_name                 = data.azurerm_resource_group.rg.name
    vnet_address_space                  = var.vnet_address_space
    dns_servers                         = var.dns_servers
    depends_on                          = [data.azurerm_resource_group.rg]    
}

module "subnet" {
  source = "./../../az_modules/subnet"
  for_each = {for subnet in var.subnet_config: subnet.subnet_name => subnet}

  resource_group_name  = data.azurerm_resource_group.rg.name
  vnet_name            = each.value.vnet_name
  subnet_name          = each.value.subnet_name
  subnet_address_space = each.value.subnet_adress_space
  enforce_private_link_endpoint_network_policies = each.value.enforce_private_link_endpoint_network_policies
  depends_on = [module.vnet_gateway_dev]
}

---input-file---

resource_group_name="RG-01"
vnet_name = "VNET-DEV-01"
vnet_address_space = ["10.104.0.0/22"]
nsg_location="germanywestcentral"
dns_servers = []
subnet_config = [
  {
    vnet_name = "VNET-DEV-01"
    subnet_name = "snet-01"
    subnet_adress_space = ["10.104.0.0/28"]
    enforce_private_link_endpoint_network_policies = null
    nsg_rules = []
  }
```

### Expected Behaviour

There should not be a different output on subsequent "apply"

### Actual Behaviour

1. On first "apply" the behavior is as expected.
2. On 2nd "apply" I get the "Objects have changed outside of Terraform" even though there have been no manual changes of resources.
3. Also, on 2nd "apply" the subnet gets deleted.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by vivek1295** [comment]
We had experienced the same kind of behavior with azurerm_private_endpoint where we had run **terraform apply** two more times.
I had done an analysis. Mostly based on module call.
**Folder structure**
|--Module Root Folder
|    |__---main.tf (root)
|--Singlr (main.tf)
|--Private EndPoint (main.tf)

### Problem
> Problem with subdirectory call

### Solution but not idle
>The only solution I was able to find and work for me is that not to call modules. keep resource block in same main.tf.
This will not be an idle solution.

This behavior is strange and required to fix

I will add more details with logs

**Comment by tombuildsstuff** [comment]
hi @morariu 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
