### ISSUE TITLE
Error when adding azurerm_app_service.identity and azurerm_role_assignment to existing infrastructure

### ISSUE THREAD

**Issue by jason-swissre** [hashicorp/terraform-provider-azurerm#13458]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 1.0.7
azurerm 2.77.0

### Affected Resource(s)

- azurerm_app_service
- azurerm_role_assignment

### Terraform Configuration Files / Debug out / Actual Behavior / Steps to reproduce

See [previous bug report](https://github.com/hashicorp/terraform-provider-azurerm/issues/4532).

This issue was already reported but closed to point at some more generic issue with terraform.  Apparently the more generic issue has been fixed but this issue still remains.  The other issue is only open to the original contributors so I am opening another version of it here.  Most of the information stated in that issue is still correct.  I have confirmed that I still have the problem with the latest terraform and azurerm.

### References

#[4532](https://github.com/hashicorp/terraform-provider-azurerm/issues/4532)

**Comment by jason-swissre** [comment]
Any update on this issue?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained. azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
