### ISSUE TITLE
Fully Scripted Deployment of Azure APIM with KEyVault Integration

### ISSUE THREAD

**Issue by jannickk** [hashicorp/terraform-provider-azurerm#13457]
The following code works if a "minimal " API Management Instance is present and fails already in the plan phase when no APIM instance is present. The problem is that during the Plan phase, Terraform tries to access the identity of the APIM instance during creation of the Azure KeyVault access policy creation and will find an empty string (because there is no APIM yet) and complain that it was expecting an GUID. Only when APIM is there, will it run through. The problem we are facing is that we would need to create an APIM instance first manually, and then code the configuation of custom domain names for which we need KeyVault access.

resource azurerm_api_management "apim" {
  name = "${var.environment.alias}-apim-${local.az_location_alias}"
  location = azurerm_resource_group.rg["rg_apim"].location
  resource_group_name = azurerm_resource_group.rg["rg_apim"].name
  publisher_name = "<my company"
  publisher_email = "data@<my domain>"
  sku_name = var.apim_sku_name
  virtual_network_type = "Internal"

  virtual_network_configuration {
    subnet_id = azurerm_subnet.snet["snet_apim"].id
  }

  identity {

    type = "SystemAssigned"
  }
}

resource "azurerm_api_management_custom_domain" "apim_domain" {

    api_management_id= azurerm_api_management.apim.id

   api {
      host_name = "api.<my domain>"

      key_vault_id = data.azurerm_key_vault_certificate.appgw_certs["management_cert"].secret_id
  }

}

resource "azurerm_role_assignment" "apim_role_assignment" {
  scope                = data.azurerm_key_vault.kv.id
  role_definition_name = "Reader"
  principal_id         = azurerm_api_management.apim.identity[0].principal_id
}

resource "azurerm_key_vault_access_policy" "apim_kv_access" {

  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_api_management.apim.identity[0].principal_id
  key_vault_id = data.azurerm_key_vault.kv.id
  certificate_permissions = [
    "Get",
    "List",
  ]

  secret_permissions = [
    "Get",
    "List",
  ]
}

data "azurerm_key_vault_certificate" "appgw_certs" {
  for_each = var.appgw_certs
  name=each.value
  //The id of the keyvault to use.
  key_vault_id = data.azurerm_key_vault.kv.id
}

resource "azurerm_private_dns_a_record" "api_dns_apim" {
   name                = "api"
   zone_name           = "<mydomain>"
   resource_group_name = azurerm_resource_group.rg["rg_hubnetwork"].name
   ttl                 = 1800
   records = ["${azurerm_api_management.apim.private_ip_addresses[0]}"]
}

**Comment by tombuildsstuff** [comment]
hi @jannickk 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
