### ISSUE TITLE
azurerm_cosmosdb_account does not create database accounts with backup type "continuous", but uses the default "periodic" instead.

### ISSUE THREAD

**Issue by RomanKreisel** [hashicorp/terraform-provider-azurerm#13467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.7
AzureRM Provider 2.77.0

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "dbprod" {
   // ...
   backup {
    type              = "Continuous"
   }
   // ...
}
```

### Expected Behaviour

The database was created with "**Continuous**" Backup Mode

### Actual Behaviour

The database was created with "**Periodic**" Backup Mode (the default)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by RomanKreisel** [comment]
Just one more thing:

I checked the code - and the test `TestAccCosmosDBAccount_backup()` in "internal/services/cosmos/cosmosdb_account_resource_test.go" check's for "Periodic" of the created database.

Unfortunately the test `TestAccCosmosDBAccount_backupContinuous()` only checks for the existence of the database - not wether it has been created with "Continuous" backup type.

**Comment by lonegunmanb** [comment]
Hi @RomanKreisel , I've tested the following code with azurerm provider 2.94.0:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "zjhe-f13467"
  location = "eastus"
}

resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_cosmosdb_account" "db" {
  name                = "zjhe-f13467-${random_integer.ri.result}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = true

  backup {
    type = "Continuous"
  }

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = "westus"
    failover_priority = 1
  }

  geo_location {
    location          = azurerm_resource_group.rg.location
    failover_priority = 0
  }
}
```

The cosmosdb account was created with "Continuous" backup type:

![](https://raw.githubusercontent.com/lonegunmanb/pic/master/20220129141529.png)

Would you please try again with the latest version of the plugin? Thanks!

**Comment by RomanKreisel** [comment]
Hi @lonegunmanb,
I just upgraded from 1.0.7 (also with some older version of Azure Provider) to 1.1.4 with latest azure provider and now it works as expected.


Thank you! :)
