### ISSUE TITLE
Support for passing Key Vault secret internally using parameter-references (value never touching host)

### ISSUE THREAD

**Issue by hterik** [hashicorp/terraform-provider-azurerm#13472]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using azurerm_key_vault_secret value-attribute, the full secret is transferred to the host running Terraform and stored into tfstate if i understand correctly.

Azure has a feature to pass Key Vault secrets internally via ID only, so that the secret value never leaves Azure. This is done using parameter-references in the ARM template, see https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/key-vault-parameter?tabs=azure-cli
Using this method, the secret is never exposed, which should be a neat security improvement. It would be good if Terraform somehow could use this method under the hood when referencing Key Vault secrets.

### New or Affected Resource(s)

* azurerm_key_vault_secret

**Comment by rcskosir** [comment]
Thanks for opening this issue. Time has passed and I believe this has been solved by Azure through the key vault references, as such I am going to mark this closed. If you are able to provide more information based on the latest version of the provider that this is not possible we may re-open this issue or open a new issue, thanks!

**Comment by hterik** [comment]
I'm not sure this is completed. 
Azure may provide key vault references, my question was how to use such references when deploying a resource _with Terraform._
@rcskosir can you please show or link to any documentation of how to use such key vault references with Terraform?

For example, how can I set the  [`administrator_password`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#administrator_password) of a  `azurerm_postgresql_flexible_server` using a key vault reference?
