### ISSUE TITLE
Kubernetes taints on default node pool (created outside terraform) not synced to state

### ISSUE THREAD

**Issue by audunsol** [hashicorp/terraform-provider-azurerm#13475]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Overview

I needed to change some important things on our (system) default node pool (as we had severe issues with the IOPS on the vm-types used, among other things). Also added some taints on the nodes in the same go. Did this in a 4 step fashion, to prevent downtime:
1. Created a new temporary system node pool. 
2. Deleted the old system/default node pool. Pods drained and restarted on the new temporary node pool
3. Created a new default node pool with the new desired properties (including taints)
4. Deleted the temporary node pool from step 2, and saw pods getting drained and restarted on the new node pool, without downtime (k8s deployments not shutting down old pods before new pods are up)

I am sorry if I am "breaking the rules" by doing this outside Terraform. But it was a very stressed situation, with a lot of hard-to-explain IOPS-related issues (network and disk write trouble on some important nodes/workloads etc.). And my impression was that I could get the state synced into terraform when the dust had settled.

This does not work, however, because terraform does not see the new taints in the node pool in its state, is unable to update it, and insists on replacing my AKS cluster.

### Terraform (and AzureRM Provider) Version

```bash
terraform -v
```
Outputs:
```
Terraform v0.15.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.3.0
+ provider registry.terraform.io/hashicorp/azurerm v2.46.0

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_kubernetes_cluster" "aks_mycompany" {
  name                            = "${var.aks_cluster_name_prefix}-${var.env}"
  location                        = azurerm_resource_group.rg_k8s.location
  resource_group_name             = azurerm_resource_group.rg_k8s.name
  dns_prefix                      = "${var.aks_cluster_name_prefix}-${var.env}"
  kubernetes_version              = var.kubernetes_version
  api_server_authorized_ip_ranges = []
  enable_pod_security_policy      = false

  default_node_pool {
    name                 = "default"
    node_count           = 2
    vm_size              = "Standard_B4MS"
    os_disk_size_gb      = 30
    vnet_subnet_id       = azurerm_subnet.subnet_default.id
    max_pods             = 30
    enable_auto_scaling  = false
    orchestrator_version = var.kubernetes_version # Value is currently "1.19.7"
    node_labels          = { "dedicated" : "main" }
    node_taints          = [ "dedicated=main:NoSchedule" ]  # <----THIS IS THE IMPORTANT THING!
  }

  addon_profile {
    aci_connector_linux {
      enabled     = true
      subnet_name = azurerm_subnet.subnet_aci.name
    }

    http_application_routing {
      enabled = false
    }

    kube_dashboard {
      enabled = true
    }
  }

  service_principal {
    client_id     = azuread_application.aks_ad_app.application_id
    client_secret = azuread_service_principal_password.aks_sp_pw.value
  }

  role_based_access_control {
    enabled = true
  }

   # + auto_scaler_profile, network_profile not shown here...

  tags = {
    source      = "terraform"
    environment = var.env
  }
}
```

### Debug Output

```
  # azurerm_kubernetes_cluster.aks_mycompany must be replaced
-/+ resource "azurerm_kubernetes_cluster" "aks_mycompany" {
      - api_server_authorized_ip_ranges = [] -> null
      
      ...
      
      ~ default_node_pool {
          - availability_zones     = [] -> null
          - enable_host_encryption = false -> null
          - enable_node_public_ip  = false -> null
          - max_count              = 0 -> null
          - min_count              = 0 -> null
            name                   = "default"
          ~ node_taints            = [ # forces replacement
              + "dedicated=main:NoSchedule",
            ]
          - tags                   = {} -> null
            # (10 unchanged attributes hidden)
        }
        ...
```        

### Expected Behaviour

Node taints should reflect what is actually seen in the Azure portal for this node pool:

![image](https://user-images.githubusercontent.com/4691439/134504533-1c061d6b-a03f-4cb8-9dad-2a16b464f063.png)

### Actual Behaviour

Terraform cannot sync the actual state of default node pool taints from Azure into the state. It insists on deleting and re-creating the AKS cluster if I add this line in my terraform:

```
node_taints          = [ "dedicated=main:NoSchedule" ]
```

### Steps to Reproduce

1. Add taint on default node pool outside Terraform, e.g. via Azure CLI
```
az aks nodepool add \
  --cluster-name MyCompanyAKS-test \
  --resource-group mycompany-k8s-test \
  --name default \
  --mode "System" \
  --node-vm-size Standard_B4MS \
  --labels dedicated=main \
  --node-taints dedicated=main:NoSchedule \
  --node-osdisk-size 30 \
  --node-count 2
```
2. Update terraform config to reflect the node pool as per the `az aks` CLI command above, including `node_taints`
3. `terraform plan --var-file=env.tfvars`

Also tried
```
terraform state rm azurerm_kubernetes_cluster.aks_mycompany
terraform import --var-file=env.tfvars azurerm_kubernetes_cluster.aks_mycompany /subscriptions/<guid>/resourcegroups/mycompany-k8s-<env>/providers/Microsoft.ContainerService/managedClusters/MyCompanyAKS-<env>
terraform state show azurerm_kubernetes_cluster.aks_mycompany
```

...but the Terraform state _still_ thinks that there are no taints on my default node pool. Which is wrong.

~~This is a showstopper, as I cannot really get my terraform config into sync without a destructive action on my AKS cluster.~~
For now, I have to keep this line commented out in my terraform definition. Then it does not suggest any cluster replacement upon `terraform plan` nor `terraform apply`, and the taint seems to still be present in Azure after apply. I would like my terraform to become "the source of truth" again.

### References

Suggestion/inspiration followed for the `az cli` approach: https://pumpingco.de/blog/modify-aks-default-node-pool-in-terraform-without-redeploying-the-cluster/

Might be relevant (but not sure):

* #10639

**Comment by stephybun** [comment]
Hi @audunsol,

Apologies for the very late response. I can understand that there are circumstances where one needs to intervene on running systems manually with tools outside of Terraform, especially when there are deadlines and/or time critical processes at play. It's certainly unfortunate that it was not possible to reconcile the Terraform state with what was deployed in Azure without having to recreate the cluster.

At the time this was a limitation in the AKS API, and I believe it still is. The API won't allow changes to the `node_taints`. Since then we have introduced functionality into the resource that essentially mimics what's outlined in the blog post that's linked in the issue and since v3.59.0 of the provider it's possible to update the value of `node_taints` without recreating the cluster by cycling the node pools in the background. You will need to specify `temporary_name_for_rotation` in order to take advantage of this feature.

Since it's now possible to update `node_taints` I'm going to go ahead and close this issue. Apologies again for not providing an answer sooner.
