### ISSUE TITLE
azurerm_data_factory doesn't support `SystemAssigned, UserAssigned` for identity type (validation issue)

### ISSUE THREAD

**Issue by jmcee1** [hashicorp/terraform-provider-azurerm#13471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.5
+ provider registry.terraform.io/hashicorp/azurerm v2.77.0

### Affected Resource(s)

* `azurerm_data_factory`

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory" "this" {
  name                = var.name
  location            = var.location
  resource_group_name = var.target_resource_group_name

  identity {
    type         = "SystemAssigned, UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.this.id]
  }
  customer_managed_key_id = var.encryption_key_id
}
```

### Debug Output

 ```
Error: expected identity.0.type to be one of [SystemAssigned UserAssigned], got SystemAssigned, UserAssigned
```

### Expected Behaviour

Validation should pass for value `SystemAssigned, UserAsssigned`

### Actual Behaviour

Validation fails for `SystemAssigned, UserAsssigned` 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

From models.go since v54.0.0:
```
Type - The identity type. Possible values include: 'FactoryIdentityTypeSystemAssigned', 'FactoryIdentityTypeUserAssigned', 'FactoryIdentityTypeSystemAssignedUserAssigned'
```
Looks like value missed while migrating to v54.0.0
### References

+ https://github.com/Azure/azure-sdk-for-go/blob/main/services/datafactory/mgmt/2018-06-01/datafactory/models.go#L10299-L10307
+ https://github.com/hashicorp/terraform-provider-azurerm/blob/317dd622ccb43ef9c458fc4137806fa1fc082c9c/internal/services/datafactory/data_factory_resource.go#L73-L76

**Comment by aristosvo** [comment]
Let's give it a try to fix this 👍🏽

**Comment by aristosvo** [comment]
@jmcee1 I have never seen an issue resolve and being released as quickly as this one, enjoy! 😂🎉🎉
