### ISSUE TITLE
azurerm_batch_pool is erroring out for setting only public_address_provisioning_type in network_configuration

### ISSUE THREAD

**Issue by sushilkm** [hashicorp/terraform-provider-azurerm#13481]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.7
on darwin_amd64

Azure RM version 2.77.0

### Affected Resource(s)

* `azurerm_batch_pool`

### Terraform Configuration Files

```resource "azurerm_batch_pool" "test" {
  name                = "testaccpool"
  resource_group_name = "${azurerm_resource_group.test.name}"
  account_name        = "${azurerm_batch_account.test.name}"
  display_name        = "Test Acc Pool Auto"
  vm_size             = "standard_f8s_v2"
  node_agent_sku_id   = "batch.node.ubuntu 20.04"

  storage_image_reference {
    publisher = "microsoft-azure-batch"
    offer     = "ubuntu-server-container"
    sku       = "20-04-lts"
    version   = "latest"
  }
  network_configuration {
    public_address_provision_type = "BatchManaged" # Possible values BatchManaged, UserManaged, NoPublicIPAddresses
  }
}
```

### Expected Behaviour

It should work for setting the `public_address_provisioning_type`

### Actual Behaviour

Getting error for missing subnet_id, even though subnet_id is listed as optional argument
```
$ terraform validate
╷
│ Error: Missing required argument
│
│   on ../../../modules/azure/batch-pool/main.tf line 175, in resource "azurerm_batch_pool" "batch_pool":
│  175:   network_configuration {
│
│ The argument "subnet_id" is required, but no definition was found.
```

**Comment by tombuildsstuff** [comment]
fixed via #13675
