### ISSUE TITLE
The terraform-provider-azurerm_v2.77.0_x5.exe plugin crashed

### ISSUE THREAD

**Issue by robduncan-novia** [hashicorp/terraform-provider-azurerm#13482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v3.0.0
+ provider registry.terraform.io/hashicorp/azuread v2.3.0    
+ provider registry.terraform.io/hashicorp/azurerm v2.77.0   
+ provider registry.terraform.io/hashicorp/random v3.1.0     
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

### Affected Resource(s)

* The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
* The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.* 

### Panic Output

```panic: runtime error: index out of range [0] with length 0

goroutine 184 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/appconfiguration.KeyResource.Read.func1(0x6f6e0b8, 0xc0017177a0, 0xc0012e3c00, 0x6f6f708, 0xc000118cd8, 0xc0015fbe00, 0x0, 0x6f711b8, 0xac42da0, 0x10a97e83638, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/appconfiguration/app_configuration_key_resource.go:215 +0xc05
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func3(0x6f6e0b8, 0xc0017177a0, 0xc0015fbe00, 0x5ed78e0, 0xc0012e3c00, 0x2030005, 0x10a000000cb)
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001c7e2c0, 0x6f6e0f0, 0xc001606a00, 0xc0017173e0, 0xc001c7e2c0, 0xc000731a70, 0xc0018ebba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x108
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x63ed560, 0xc001c7e2c0, 0x6f6e0f0, 0xc000731a70, 0xc001717380, 0x0, 0x6f6e0f0, 0xc000731a70, 0xc00166e900, 0x40d)        
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x222   
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000238a80, 0x6fbf6d8, 0xc000297e00, 0xc0018a2a20, 0xc00160cae0, 0xabec550, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000238a80, 0x6fbf6d8, 0xc000297e00, 0xc0018a2a20, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000f28810, 0xc000238a80, 0x6fbf6d8, 0xc000297e00, 0xc0018a2a20)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.77.0_x5.exe plugin crashed!
```

### Expected Behaviour

Run Terraform plan

### Actual Behaviour
Error above

**Comment by aristosvo** [comment]
@robduncan-novia I have created a PR which can potentially fix this issue, but do you know how this situation actually was created? Was the key removed manually or something like that?

If you have a reproduction scenario it would be appreciated, as I've no idea how this actually is possible.

**Comment by aristosvo** [comment]
I'm able to reproduce this scenario by adding a different label for the same key and remove the original label.

With the fix in place, the resource is marked as gone and recreated on the next apply.

**Comment by robduncan-novia** [comment]
@aristosvo , thank you so much.  Just checking the changes I was trying to apply, and I was changing the variable in the value of a azurerm_key_vault_secret, and also changing the key of a azurerm_app_configuration_key.

**Comment by robduncan-novia** [comment]
I confirm that following Terraform init -upgrade this is now working.  Thank you very much @aristosvo .
