### ISSUE TITLE
Support for azurerm_signalr_service Disabling Access Keys

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azurerm#13501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure signalr service offers the ability to disable access keys
![image](https://user-images.githubusercontent.com/1514496/134723167-b7cc680a-00fc-48cf-94a6-484c62bc8b7d.png)

in the export template this appears to correspond to `disableLocalAuth` prop

### New or Affected Resource(s)

* azurerm_signalr_service

### Potential Terraform Configuration

```hcl
resource "azurerm_signalr_service" "example" {
  name                = "tfex-signalr"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  disable_access_keys = true

  sku {
    name     = "Free_F1"
    capacity = 1
  }

  cors {
    allowed_origins = ["http://www.example.com"]
  }

  features {
    flag  = "ServiceMode"
    value = "Default"
  }

  upstream_endpoint {
    category_pattern = ["connections", "messages"]
    event_pattern    = ["*"]
    hub_pattern      = ["hub1"]
    url_template     = "http://foo.com"
  }
}
```

**Comment by jbhuguenin** [comment]
azure api support this attribute => https://learn.microsoft.com/en-us/rest/api/signalr/signalr/create-or-update?tabs=HTTP#request-body

**Comment by tombuildsstuff** [comment]
Taking a look through here this is available in the `local_auth_enabled` field: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/signalr_service#local_auth_enabled
