### ISSUE TITLE
Errors while applying azurerm_app_configuration_key

### ISSUE THREAD

**Issue by ssevella** [hashicorp/terraform-provider-azurerm#13502]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_app_configuration_key`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_app_configuration" "appconf" {
  name                = "appConf1"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.appconf.id
  key                    = "appConfKey1"
  label                  = "somelabel"
  value                  = "a test"
}
```

### Debug Output

│ Error: while checking for key's "appConfKey1" existence: appconfiguration.BaseClient#GetKeyValues: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF
│
│   with azurerm_app_configuration_key.test,
│   on test.tf line 24, in resource "azurerm_app_configuration_key" "test":
│   24: resource "azurerm_app_configuration_key" "test" {
│
│ while checking for key's "appConfKey1" existence: appconfiguration.BaseClient#GetKeyValues: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error:   
│ EOF

### Expected Behaviour

New resource group, new app configuration store and key-value pair to be created.

### Actual Behaviour

Resource group and app configuration store are created but error creating key-value pair.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aristosvo** [comment]
Hi @ssevella! I had the same problem yesterday, and I believe I got the solution.

To get data access, you can both use a connection string or AD to authenticate, and it seems AD authentication is used within this resource. This also means you need AD authorization, check the [docs for more info](https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration).

After providing the `App Configuration Data Owner` role to the service principal I was using on the App Configuration resource (or higher level, i.e. Resource Group), it worked!

**Comment by ssevella** [comment]
Hi @aristosvo, thank you so much for the answer. Granting 'App Configuration Data Owner' fixed the issue.

**Comment by aristosvo** [comment]
@ssevella Great! I'll check the documentation if this needs clarification
