### ISSUE TITLE
cassandra is requiring minimum 8000 RU

### ISSUE THREAD

**Issue by katlimruiz** [hashicorp/terraform-provider-azurerm#13504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.5
on windows_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v2.21.0
+ provider registry.terraform.io/hashicorp/azuread v1.5.1     
+ provider registry.terraform.io/hashicorp/azurerm v2.62.1    
+ provider registry.terraform.io/hashicorp/helm v2.2.0        
+ provider registry.terraform.io/hashicorp/kubernetes v2.3.2  
+ provider registry.terraform.io/hashicorp/local v2.1.0       
+ provider registry.terraform.io/terraform-providers/azuredevops v0.1.5

### Affected Resource(s)

* `azurerm_cosmosdb_cassandra_keyspace`

### Terraform Configuration Files
```hcl
resource "azurerm_cosmosdb_cassandra_keyspace" "cassdbs" {
  for_each = {
    "a" : 4000,
    "b" : 4000,
    "c" : 4000
  }

  name                = each.key
  resource_group_name = azurerm_cosmosdb_account.cdbcass.resource_group_name
  account_name        = azurerm_cosmosdb_account.cdbcass.name
  autoscale_settings {
    max_throughput = each.value
  }
}
```
### Expected Behaviour
The minimum should be 4000. In the Azure Portal UI I can set 4000.

### Actual Behaviour

Error: Error waiting on ThroughputUpdate future for Cosmos Cassandra Keyspace "a" (Account: "acc"): Code="BadRequest" Message="Message: {\"code\":\"BadRequest\",\"message\":\"Message: {\\\"Errors\\\":[\\\"The offer should have valid throughput values between 8000 and 1000000 inclusive in increments of 1000.\\\"]}

### Steps to Reproduce

1. `terraform apply`

* #0000

**Comment by katlimruiz** [comment]
@PedroDLC1210

**Comment by aristosvo** [comment]
@katlimruiz The Acceptance Tests for `azurerm` are using `4000`, `5000` and `6000` as values in one of the tests, and they succeeded the last time I ran them.

The setup
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-cosmos-123"
  location = "West Europe"
}

resource "azurerm_cosmosdb_account" "test" {
  name                = "acctest-ca-123"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  consistency_policy {
    consistency_level = "Strong"
  }

  capabilities {
    name = "EnableCassandra"
  }

  geo_location {
    location          = azurerm_resource_group.test.location
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_cassandra_keyspace" "test" {
  name                = "acctest-123"
  resource_group_name = azurerm_cosmosdb_account.test.resource_group_name
  account_name        = azurerm_cosmosdb_account.test.name
  autoscale_settings {
    max_throughput = 4000
  }
}
```

If your setup is similar to above, I'd contact Microsoft Support to ask them how this is the case in your particular situation, as the validation/error message is not coming from Terraform provider `azurerm` but from the Azure API instead.

**Comment by katlimruiz** [comment]
yes, it is very similar to that, ok I will try going to Azure support.

**Comment by jackofallops** [comment]
As this appears to be an upstream problem, rather than an issue with the provider I'm going to close this issue for now.
