### ISSUE TITLE
[azurerm_cosmosdb_account] Support for Online Update of MongoDB Version of CosmosDB 

### ISSUE THREAD

**Issue by mrmatimba** [hashicorp/terraform-provider-azurerm#13515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to the official Azure documentation, the MongoDB version can be updated without service interruption (see [here](https://docs.microsoft.com/en-gb/azure/cosmos-db/mongodb/upgrade-mongodb-version)). In contrast to this, changing the mongo_server_version setting of azurerm_cosmosdb_account forces a new resource to be created. Is it possible to change the MongoDB version via terraform without recreating the Azure resource?

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### References

* https://docs.microsoft.com/en-gb/azure/cosmos-db/mongodb/upgrade-mongodb-version
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account

**Comment by aristosvo** [comment]
Let's see if that can be fixed!
