### ISSUE TITLE
Support for storage_account blocks in azurerm_function_app

### ISSUE THREAD

**Issue by jwefers** [hashicorp/terraform-provider-azurerm#13513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

`azurerm_app_service` supports mounting azure file shares via `storage_account` blocks. Azure-wise, the same is possible for functions, but the azurerm provider is lacking support for this in function resources. Please add this to `azurerm_function_app`

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  ...
  storage_account {
    name = ...
    ...
    mountPath = ...
  }
}
```

**Comment by rgammans** [comment]
Isn't this a duplicate of #6790 ?

**Comment by jwefers** [comment]
whoops, yes it is - apparently i didnt search thoroughly when i filed this
