### ISSUE TITLE
Function App deploys with "Deployment Credentials" blade option

### ISSUE THREAD

**Issue by Zman94** [hashicorp/terraform-provider-azurerm#13537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Alias tip: tf -v
Terraform v0.15.3
on darwin_amd64

Your version of Terraform is out of date! The latest version
is 1.0.7. You can update by downloading from https://www.terraform.io/downloads.html
```
```
AzureRM version = 2.76.0
```

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "fa" {
  name                = "${local.fa_name}-${var.short_name}-${var.rank}-${var.feature_name}"
  resource_group_name = module.rg.name
  location            = var.location

  app_service_plan_id        = azurerm_app_service_plan.asp_fa.id
  storage_account_name       = azurerm_storage_account.sa_fa.name
  storage_account_access_key = azurerm_storage_account.sa_fa.primary_access_key

  app_settings = var.app_settings
  os_type      = var.os_type

  tags = var.tags
}
```

### Debug Output

No issue during deployment

### Expected Behaviour

Function App should have been deployed without the Deployment credentials blade option

![image](https://user-images.githubusercontent.com/8743777/135164592-c1846222-b570-461e-ab2f-58971ed7044a.png)

### Actual Behaviour

Function App has the Deployment credentials option

![image](https://user-images.githubusercontent.com/8743777/135164540-c802c4e7-ee63-4b94-9330-9510c8f8f155.png)

### Steps to Reproduce

1. `terraform apply`
2. Look at Function App in Portal

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. The azurerm_function_app resource is deprecated in version 3. 0 and will be removed in version 4.0 - so I'd suggest moving to the azurerm_linux_function_app and azurerm_windows_function_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_function_app and azurerm_windows_function_app resources please do let us know by opening a new issue, thanks!
