### ISSUE TITLE
eventgrid_extension exists on function but displays null value for event_grid_extension_config_key

### ISSUE THREAD

**Issue by srjennings** [hashicorp/terraform-provider-azurerm#13568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

TF Version: `0.15.5`
AzureRM Version: `2.76.0`

### Affected Resource(s)

**Data Source:**
* `azurerm_function_app_host_keys`

### Terraform Configuration Files

```hcl
data "azurerm_function_app_host_keys" "func_apphostkeys" {
  name                = "functionname"
  resource_group_name = "resourcegroupname"
}
```

### Debug Output

Debug output wasn't helpful. Issue was found in state file.

STATE EXCERPT:

```json
    {
      "mode": "data",
      "type": "azurerm_function_app_host_keys",
      "name": "func_apphostkeys",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "default_function_key": "SANITIZED==",
            **"event_grid_extension_config_key": "",** <~~~~~ NULL VALUE IS INCORRECT
            "id": "/subscriptions/SANITIZED/resourceGroups/SANITIZED/providers/Microsoft.Web/sites/functionname",
            "master_key": "SANITIZED==",
            "name": "functionname",
            "primary_key": "SANITIZED==",
            "resource_group_name": "resourcegroupname,
            "timeouts": null
          },
          "sensitive_attributes": []
        }
      ]
    }
```

### Panic Output

N/A

### Expected Behaviour

Grab the eventgrid_extension key.

### Actual Behaviour

`event_grid_extension_config_key` is `""` in the state file.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

N/A

### References

* PR #10823

**Comment by srjennings** [comment]
I am not a Go developer but I see the following piece of code: https://github.com/hashicorp/terraform-provider-azurerm/blob/b44ea51c13981790f575c04d0d79eff94639f71f/internal/services/web/function_app_host_keys_data_source.go#:~:text=eventgridextensionconfig_extension

I think the reference is simply incorrect. I'd make a PR but may not have time right away to do so.

Running the following command in the AZ CLI returns a different key:

```bash
az rest \
--method post \
--uri /subscriptions/SANITIZED/resourceGroups/SANITIZED/providers/Microsoft.Web/sites/functionname/host/default/listkeys?api-version=2019-08-01 \
--query systemKeys
```

**Comment by srjennings** [comment]
Looks like this is dependent on which runtime is set. If the runtime is 1.x, eventgridextensionconfig_extension is used. Whereas version 2.x+ is ventgrid_extension:
https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-trigger?tabs=python%2Cbash#get-the-system-key

**Comment by abilous-ti** [comment]
@jackofallops I am facing same issue. 
event_grid_extension_config_key is empty

I am using Function ~4
Is it a bug?

**Comment by markrzasa** [comment]
Hi Everyone, I submitted a PR to fix this problem.

In the meantime, in case it helps, one way to work around this problem is using azapi:
```
data "azapi_resource_action" "event_router_keys" {
  count = var.subscribe ? 1 : 0

  type                   = "Microsoft.Web/sites@2022-03-01"
  resource_id            = azurerm_linux_function_app.event_router.id
  action                 = "host/default/listkeys"
  method                 = "POST"
  response_export_values = ["*"]
}
```
The key can then be accessed with `jsondecode(data.azapi_resource_action.event_router_keys.0.output)["systemKeys"]["eventgrid_extension"]`.
