### ISSUE TITLE
Race condition when updating multiple subnet service endpoints

### ISSUE THREAD

**Issue by subesokun** [hashicorp/terraform-provider-azurerm#13564]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- `azurerm v2.78.0`
- `Terraform v1.0.7`

### Affected Resource(s)

* `azurerm_subnet `

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "example_1" {
  name                 = "example-subnet-1"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
  service_endpoints = [
    "Microsoft.EventHub",
    "Microsoft.Storage",
    "Microsoft.ServiceBus"
  ]
}

resource "azurerm_subnet" "example_2" {
  name                 = "example-subnet-2"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints = [
    "Microsoft.EventHub",
    "Microsoft.Storage",
    "Microsoft.ServiceBus"
  ]
}
```

### Expected Behaviour

TF can correctly update multiple service endpoints at once.

### Actual Behaviour

TF starts updating the service endpoints on the first subnet and second subnet in parallel. This causes the error below on the second subnet as the Azure VNet seems to be able to handle only one update request at a time.

```
│ Error: updating Subnet: (Name "example" / Virtual Network Name "example" / Resource Group "example"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="AnotherOperationInProgress" Message="Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: <snip>." Details=[]
│ 
│   with azurerm_subnet.example_2,
│   on network.tf line 1, in resource "azurerm_subnet" "example_2":
│    1: resource "azurerm_subnet" "example_2" {
```

### Steps to Reproduce

1.  Create initial subnet 1 and 2
2. `terraform apply`
3. Add service endpoints to both subnets 
4. `terraform apply -> error`

**Comment by andy-mcgrath** [comment]
You can simply add the `depends_on` option to ensure the second subnet is not created/updated until the first is complete. e.g.
```
resource "azurerm_subnet" "example_1" {
  name                 = "example-subnet-1"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
  service_endpoints = [
    "Microsoft.EventHub",
    "Microsoft.Storage",
    "Microsoft.ServiceBus"
  ]
}

resource "azurerm_subnet" "example_2" {
  depends_on = [
    azurerm_subnet.example_1
  ]
  name                 = "example-subnet-2"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints = [
    "Microsoft.EventHub",
    "Microsoft.Storage",
    "Microsoft.ServiceBus"
  ]
}
```

[depends_on documentation](https://www.terraform.io/docs/language/meta-arguments/depends_on.html)

**Comment by subesokun** [comment]
@andy-mcgrath Yes, I'm using that already as a hacky workaround until a fix lands in the TF provider

**Comment by subesokun** [comment]
@katbyte Awesome, thanks :)
