### ISSUE TITLE
Unable to use azurerm_subscription.resource.subscription_id as input to azurerm provider's subscription_id parameter when using Service Principal

### ISSUE THREAD

**Issue by bleemus** [hashicorp/terraform-provider-azurerm#13572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

```
### Terraform (and AzureRM Provider) Version
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.78.0
```

### Affected Resource(s)

* `azurerm_subscription`

### Terraform Configuration Files

```hcl
data "azurerm_billing_enrollment_account_scope" "billacct" {
  billing_account_name    = "xxxxxxx"
  enrollment_account_name = "xxxxxxx"
}
 
resource "azurerm_subscription" "test" {
  subscription_name = "testsubscription"
  billing_scope_id  = data.azurerm_billing_enrollment_account_scope.billacct.id
}
 
provider "azurerm" {
    features {}
}
 
provider "azurerm" {
  features {}
  alias = "test"
  subscription_id = azurerm_subscription.test.subscription_id
  tenant_id       = "xxxxxxx"
  client_id       = "xxxxxxx"
  client_secret   = "xxxxxxx"
}
 
resource "azurerm_resourcegroup" "test" {
  provider = azurerm.test
  name = "testingrg"
  location = "eastus"
}
```

### Debug Output

[gist](https://gist.github.com/bleemus/d597a0032164c13eeeae9468faf3db24)

### Expected Behaviour

Second provider (alias "test") definition should get the subscription_id from the newly created azurerm_subscription object.  This same code works for other new resources that don't yet exist at plan time (like a key vault secret).

### Actual Behaviour

```
Error: building AzureRM Client: 1 error occurred:
	* A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
with provider["registry.terraform.io/hashicorp/azurerm"].test,
on main.tf line 15, in provider "azurerm":
15: provider "azurerm"
```
### Steps to Reproduce

1. `terraform init`
1. `terraform plan`

**Comment by jackofallops** [comment]
Hi @bleemus - Provider configuration blocks, including aliased ones, are processed before any resource data, so it's not possible to use references to exported properties in those blocks to other configuration items.
From the docs [here](https://www.terraform.io/docs/language/providers/configuration.html)

> You can use expressions in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources.

As this is not supported by Terraform, and is not a limitation of the provider, I'm going to close this issue.
