### ISSUE TITLE
Managed disk fails to create after v2.79.0 update

### ISSUE THREAD

**Issue by hammerhead** [hashicorp/terraform-provider-azurerm#13574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.79.0
```

### Affected Resource(s)

* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1"

  required_providers {
    azurerm = {
      source  = "azurerm"
      version = "2.79.0"
    }
  }
}

provider "azurerm" {
  features {}

  subscription_id = "xxx-yyy-zzz"
}

resource "azurerm_managed_disk" "data_disk" {
  name                = "DebugDataDisk"
  location            = "westeurope"
  resource_group_name = "RG-example-project-test"

  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = 512
}
```

### Debug Output
https://gist.github.com/hammerhead/846c08133155cd385369aed8825de050

### Expected Behaviour
On azurerm 2.78.0, the above configuration executes successfully. After upgrading to azurerm 2.79.0, it should pass as well.

### Actual Behaviour

The creation fails related to `max_shares`, although `max_shares` is optional and not specified:
```
azurerm_managed_disk.data_disk: Creating...
╷
│ Error: creating/updating Managed Disk "DebugDataDisk" (Resource Group "RG-example-project-test"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="MaxShares '0' for disk 'DebugDataDisk' of size '512' GB is invalid. Please refer to https://docs.microsoft.com/azure/virtual-machines/windows/disks-shared-enable#disk-sizes"
│ 
│   with azurerm_managed_disk.data_disk,
│   on main.tf line 18, in resource "azurerm_managed_disk" "data_disk":
│   18: resource "azurerm_managed_disk" "data_disk" {
```

### Steps to Reproduce

1. `terraform apply`

### References

* #13571

**Comment by mbfrahry** [comment]
Hey @hammerhead! Apologies for this getting mixed into the last release. We just pushed out another release that should hopefully take care of this.
