### ISSUE TITLE
Provider version 2.79.0; Managed disk failing for max shares

### ISSUE THREAD

**Issue by nikeshp84** [hashicorp/terraform-provider-azurerm#13584]
Using "azurerm_managed_disk" resource without max_shares option is failing with below error.
This is happening with the 2.79.0 version of the provider.
We do not intend to share disks and it used to work till 2.78 where this option itself was not available.

Error: creating/updating Managed Disk "disk_name" (Resource Group "rg_name"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="MaxShares '0' for disk 'disk_name' of size '50' GB is invalid. Please refer to https://docs.microsoft.com/azure/virtual-machines/windows/disks-shared-enable#disk-sizes"

**Comment by mbfrahry** [comment]
Hey @nikeshp84. Looks like this bug slipped into the latest release of the provider. We just shipped a fix with release 2.79.1. Please let me know if that fixes the issue you're seeing.

**Comment by nikeshp84** [comment]
Thanks @mbfrahry for the quick fix. Works as expected now.
