### ISSUE TITLE
Support for getting the external ip of an azure webapp (app_service)

### ISSUE THREAD

**Issue by jonsamwell** [hashicorp/terraform-provider-azurerm#13589]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

At the moment there is no way to get the external ip of a web app as an exported attribute to any resource or app_service data block.  In az cli there is the `az webapp config hostname get-external-ip` command (see https://docs.microsoft.com/en-us/cli/azure/webapp/config/hostname?view=azure-cli-latest#az_webapp_config_hostname_get_external_ip).

This make it impossible to bind a web app to a DNS A record during terraform and represents a big whole in our terraformed infrastructure.

### Potential Terraform Configuration

It would be great if this was exported from a app_service block https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#attributes-reference

**Comment by aristosvo** [comment]
Hi @jonsamwell! Would it be a problem to use the a CNAME record here? This seems like the easier solution, but correct me if I'm wrong.

With regard to the external IP, this is not incorporated in the Azure REST API definitions at this moment in time, making it an upstream issue. I'll check if it might help to file an issue upstream.

**Comment by jonsamwell** [comment]
Hi @aristosvo thank you for your reply.

In my case I need to bind to the domain apex using an A record so need the external IP.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
https://github.com/Azure/azure-rest-api-specs/issues/12974
