### ISSUE TITLE
IOT Hub endpoints result in a "change game" with every plan suggesting to change, even right after apply

### ISSUE THREAD

**Issue by ilya-git** [hashicorp/terraform-provider-azurerm#13604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 1.0.7
AzureRM: 2.78.0

### Affected Resource(s)

* `azurerm_iothub`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "iot_hub" {

  endpoint {
      type = "AzureIotHub.StorageContainer"
  }
  
  # There are 6 endpoints of event hub type in total in this group
  endpoint {
      type = "AzureIotHub.EventHub"
  }
  
  endpoint {
      type = "AzureIotHub.ServiceBusTopic"
  }
  
  endpoint {
      type = "AzureIotHub.EventHub"
  }
}
```

I have removed everything that seems to not matter for the case to make the example easier to understand.

### Expected Behaviour

No changes in plan after running apply.

### Actual Behaviour

Plan always comes with a change to "re-shuffle" endpoints in the iothub.

### Steps to Reproduce

1. Create a terraform with endpoints like from an example
2. `terraform plan`
3.`terraform apply`
4.`terraform plan`

### Important Factoids

I have "fixed" the error by moving `ServiceBusTopic` endpoint after `StorageContainer` endpoint. My guess is that if the `ServiceBusTopic` was "among" `EventHub` endpoints, it caused the provider to not match the order properly resulting in an eternal desire to change it.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
