### ISSUE TITLE
no schema available for azurerm_autoscale_setting.xxxxxxx_xxxx while reading state

### ISSUE THREAD

**Issue by ssrb89** [hashicorp/terraform-provider-azurerm#13620]
Facing below issue while executing terraform plan or apply:

**Error: no schema available for azurerm_autoscale_setting.clarosapi_auto_scaling while reading state; this is a bug in Terraform and should be reported**

`resource "azurerm_monitor_autoscale_setting" "xxxxxx" {
  count               = "1"
  name                = "xxxxx"
  target_resource_id  = "xxxx"
  location            = "xxx"
  resource_group_name = "xxx"

  profile {
    name = "${terraform.workspace}-${replace(var.location, " ", "")}-appserviceplan-auto-scaling"

    capacity {
      default = "var.auto_scaling_default_instance"
      minimum = "var.auto_scaling_min_instance"
      maximum = "var.auto_scaling_max_instance"
    }
    rule {
      metric_trigger {
        metric_name        = "CpuPercentage"
        metric_resource_id = "${azurerm_app_service_plan.xxxxx.id}"
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT10M"
        time_aggregation   = "Average"
        operator           = "GreaterThan"
        threshold          = 80
      }

      scale_action {
        direction = "Increase"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT15M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "MemoryPercentage"
        metric_resource_id = "${azurerm_app_service_plan.xxxxxxx.id}"
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT10M"
        time_aggregation   = "Average"
        operator           = "GreaterThan"
        threshold          = 80
      }

      scale_action {
        direction = "Increase"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT15M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "CpuPercentage"
        metric_resource_id = "${azurerm_app_service_plan.xxxxxx.id}"
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT10M"
        time_aggregation   = "Average"
        operator           = "LessThan"
        threshold          = 60
      }

      scale_action {
        direction = "Decrease"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT5M"
      }
    }

    rule {
      metric_trigger {
        metric_name        = "MemoryPercentage"
        metric_resource_id = "${azurerm_app_service_plan.xxxxxx.id}"
        time_grain         = "PT1M"
        statistic          = "Average"
        time_window        = "PT10M"
        time_aggregation   = "Average"
        operator           = "LessThan"
        threshold          = 60
      }

      scale_action {
        direction = "Decrease"
        type      = "ChangeCount"
        value     = "1"
        cooldown  = "PT5M"
      }
    }
  }

  notification {
    email {
      send_to_subscription_administrator    = false
      send_to_subscription_co_administrator = false
    }
  }
}`

Terraform v0.12.31
+ provider.azurerm v2.72.0
+ provider.external v2.1.0
+ provider.random v3.1.0
+ provider.template v2.2.0
+ provider.tls v3.1.0

**Comment by tombuildsstuff** [comment]
hi @ssrb89 

The `azurerm_autoscale_setting` resource has been removed in version 2.0 of the Azure Provider - as such you'll need to [follow the upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/2.0-upgrade-guide) to switch over to using the replacement `azurerm_monitor_autoscale_setting` resource mentioned above (namely you'll need to remove the older resource from your state and reimport it using the new resource name). Since this is a configuration question rather than a bug in Terraform, I'm going to close this issue for the moment but should you have further questions I'd point you in the direction of [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
