### ISSUE TITLE
App Service Certificate Binding |  Binding certificate on existing resource fails with "StatusCode=409" error.

### ISSUE THREAD

**Issue by kiran20211** [hashicorp/terraform-provider-azurerm#13651]
![image (8)](https://user-images.githubusercontent.com/77786659/136368490-17f5cccb-d51c-47c0-b914-ef61f294cf65.png)

**Description**

It's working on fresh deployment when there is change in app service, running the terraform apply will failed with following error 

_`web.AppsClient#CreateOrUpdateHostNameBinding: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error.`_

**Issue:** 

Running terraform apply fails to bind the certificate with above error.

**Workaround:** 

Rerunning the terraform apply will solve the issue.

**Comment by rcskosir** [comment]
Thanks for opening this issue. azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
