### ISSUE TITLE
Support for creating keys in a managed HSM

### ISSUE THREAD

**Issue by Roshick** [hashicorp/terraform-provider-azurerm#13654]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, there is no way to create a key within a managed HSM with the provider. Analogous to the existing azurerm_key_vault_key it would be great to have a managed_hsm_key resource.

### New or Affected Resource(s)

* azurerm_managed_hsm_key

### Potential Terraform Configuration

Analogous to the existing azurerm_key_vault_key

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/13606

**Comment by mbfrahry** [comment]
This has been added with #25935!
