### ISSUE TITLE
Content of the Azure Runbook not getting updated when the content link referred to by the Terraform script is updated

### ISSUE THREAD

**Issue by udhanMti** [hashicorp/terraform-provider-azurerm#13660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.14.10
Azurerm: 2.73.0

### Affected Resource(s)

* `azurerm_automation_runbook`

### Terraform Configuration Files

```hcl
resource "azurerm_automation_runbook" "automation_runbook" {
  name                    = var.automation_runbook_name
  location                = var.location
  resource_group_name     = var.resource_group_name
  automation_account_name = var.automation_account_name
  runbook_type            = "PowerShell"
  log_verbose             = "true"
  log_progress            = "true"

  publish_content_link {
    uri = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/c4935ffb69246a6058eb24f54640f53f69d3ac9f/101-automation-runbook-getvms/Runbooks/Get-AzureVMTutorial.ps1"
  }
}
```

### Expected Behaviour

I was able to create a Runbook using the above code successfully. Then I changed the `uri` within the `publish_content_link` block to https://raw.githubusercontent.com/azureautomation/automation-packs/master/200-connect-azure-vm/Runbooks/Connect-AzureVM.ps1 and applied. 
```
resource "azurerm_automation_runbook" "automation_runbook" {
  name                    = var.automation_runbook_name
  location                = var.location
  resource_group_name     = var.resource_group_name
  automation_account_name = var.automation_account_name
  runbook_type            = "PowerShell"
  log_verbose             = "true"
  log_progress            = "true"

  publish_content_link {
    uri = "https://raw.githubusercontent.com/azureautomation/automation-packs/master/200-connect-azure-vm/Runbooks/Connect-AzureVM.ps1"
  }
}
```
During the `terraform apply` it identified the change as expected and the modification was completed successfully.  Then I was expecting to see the Powershell script of Azure Runbook shown in the Azure Portal updated as well.

### Actual Behaviour

But the new PowerShell script was not getting reflected in the Azure Automation Runbook in the Azure Portal and it still showed the old PowerShell script.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
