### ISSUE TITLE
Error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by smakadicy** [hashicorp/terraform-provider-azurerm#13667]
**Community Note**
---
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Description**
---
When applying a change to the `azurerm_monitor_action_group` and creating a new instance of `azurerm_monitor_scheduled_query_rules_alert`, the below issue appears when running a terraform apply:

```
When expanding the plan for
│ azurerm_monitor_scheduled_query_rules_alert.app_error to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
│ .action[0].action_group: planned set element
│ cty.StringVal("/subscriptions/<REDACTED>/resourceGroups/<REDACTED>/providers/Microsoft.Insights/actionGroups/<REDACTED>")
│ does not correlate with any element in actual.

This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Context**
---
- Terraform version: v1.0.0 
- azurerm provider version: v2.80.0
- A dependency was enforced for `azurerm_monitor_action_group` to complete any planned changes before proceeding with the creation of any alerts. 

**Mitigation**
---
The workaround I found during apply is to let terraform apply the changes to  `azurerm_monitor_action_group` first. Then do another run to create/modify any of the alert rules.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
