### ISSUE TITLE
Cannot pull docker image from private ACR into azurerm_appservice

### ISSUE THREAD

**Issue by skylaro** [hashicorp/terraform-provider-azurerm#13685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

1.0.8

### Affected Resource(s)

* `azurerm_XXXXX`
* azurerm_app_service

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

On app service startup, image from private ACR should pull successfully.

### Actual Behaviour

Image does not pull successfully for an unknown reason.

### Steps to Reproduce
1. Manually create an azure vnet, private endpoint, private link service, PE subnet, and azure container registry.
2. Set azure container registry to 'Private' to disable public network access, and enable admin access.
3. Apply terraform template which references the above resources within an app service definition.
Confirm in app service logs that it says, "pulling image ... over VNET failed"

1. `terraform apply`

### Important Factoids

I can get it working by embedding az CLI commands into the template, but this is hacky and not ideal.

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
