### ISSUE TITLE
Unable to create Octet key (azurerm_key_vault_key) 

### ISSUE THREAD

**Issue by mibollma** [hashicorp/terraform-provider-azurerm#13706]
### Terraform (and AzureRM Provider) Version
2.80.0

### Affected Resource(s)
azurerm_key_vault_key

### Terraform Configuration Files
```hcl
resource "azurerm_key_vault" "key_vault" {
  name                        = "somevaultname"
  location                    = azurerm_resource_group.group.location
  resource_group_name         = azurerm_resource_group.group.name
  enable_rbac_authorization = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false
  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Get",
    ]
  }
}

resource "azurerm_key_vault_key" "generated" {
  name         = "somekeyname"
  key_vault_id = azurerm_key_vault.key_vault.id
  key_type     = "Oct"
  key_size     = 768

  key_opts = [
    "decrypt",
    "encrypt",
  ]
}
```

### Expected Behaviour
A key of type Octet is created

### Actual Behaviour
```
Error: expected key_type to be one of [EC EC-HSM RSA RSA-HSM], got Oct
  with azurerm_key_vault_key.generated,
  on main.tf line 524, in resource "azurerm_key_vault_key" "generated":
  524:   key_type     = "Oct"
```

### Important Factoids
The documentation states:
```
#key_type - (Required) Specifies the Key Type to use for this Key Vault Key. Possible values are EC (Elliptic Curve), EC-HSM, Oct (Octet), RSA and RSA-HSM. Changing this forces a new resource to be created.
```
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key#key_type

**Comment by mibollma** [comment]
Thanks for looking into it.
I've found a different solution for my use-case.
Instead of a key I now use a secret thats generated using the random_password resource which is good enough for now.

**Comment by aristosvo** [comment]
It seems Octet is not supported in Azure KeyVault at the moment. Although present in recent APIs, it doesn't work and doesn't show up in the docs anywhere.

I'll close this issue therefore for now and file a PR to remove it completely from `azurerm` docs and code.
