### ISSUE TITLE
azurerm_api_management_api service_url attribute can't be removed from resource

### ISSUE THREAD

**Issue by SKhachko** [hashicorp/terraform-provider-azurerm#13729]
Provider version: 2.80.0
Current config:
```
resource "azurerm_api_management_api" "main" {
  name                  = "gw-api"
  resource_group_name   = var.resource_group_name
  api_management_name   = azurerm_api_management.main.name
  revision              = "1"
  display_name          = "gw-api"
  protocols             = ["https"]
  subscription_required = false
  service_url           = null

  import {
    content_format = "openapi"
    content_value  = data.local_file.scheme.content
  }
}
```

When applying, the `service_url` is still present in "gw-api" with its recent value (even if I set it to null or remove completely from terraform spec). The diff doesn't show anything which means that old value of `service_url` will not be removed

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
