### ISSUE TITLE
App Service - Auth Settings Config Version missing

### ISSUE THREAD

**Issue by StiviiK** [hashicorp/terraform-provider-azurerm#13750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version
```
Terraform v1.0.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.80.0
```

### Affected Resource(s)

- azurerm_app_service

### Description / Feedback

Property `auth_settings.configVersion` of `azurerm_app_service` is missing, and defaults to `v1` which has been deprecated within the Azure Portal.
![image](https://user-images.githubusercontent.com/8115642/137465434-47483e97-f673-4f26-aa1f-c95b993b038e.png)
![image](https://user-images.githubusercontent.com/8115642/137466986-f7335aeb-f2bd-4213-b366-70b0f821df02.png)

### References
https://docs.microsoft.com/en-us/rest/api/appservice/web-apps/get-auth-settings#siteauthsettings
https://github.com/hashicorp/terraform-provider-azurerm/issues/13591

**Comment by markphillipsbjss** [comment]
It appears that MS are moving to remove the classic experience from the portal next month.
![image](https://user-images.githubusercontent.com/75017466/140040041-8f31c116-f2c9-4e99-a280-3c25bd1de367.png)

**Comment by WithHolm** [comment]
this is also applicable to all resources using authentication, not just app_service

**Comment by drdamour** [comment]
this is being discussed most relevantly in https://github.com/hashicorp/terraform-provider-azurerm/issues/12928

**Comment by tombuildsstuff** [comment]
Consolidating this into #12928 - please subscribe to that issue for updates
