### ISSUE TITLE
Doc issues for azurerm_mssql_database_extended_auditing_policy and azurerm_mssql_server_extended_auditing_policy

### ISSUE THREAD

**Issue by rberlind** [hashicorp/terraform-provider-azurerm#13775]
The page https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database_extended_auditing_policy has a note that makes no sense.  It talks about two ways of setting audit policy for azurerm_mssql_database resources, but it points back to itself.  What it needs to be saying is that the audit policy can be set in this resource or with the `extended_auditing_policy` block of the azurerm_mssql_database resource.  And there should probably be a note with the language of this note in that block under https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database

The same problem occurs with https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server_extended_auditing_policy

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

This is a documentation issue.

### Affected Resource(s)

* `azurerm_mssql_database_extended_auditing_policy`
* `azurerm_mssql_server_extended_auditing_policy`

**Comment by Sheetalsingh23** [comment]
Hello @rberlind, I want to work on this issue. Can I pick up this issue?

**Comment by rberlind** [comment]
absolutely, @Sheetalsingh23 .  Thanks.
