### ISSUE TITLE
azurerm_static_site: sku_size and sku_tier descriptions are duplicates

### ISSUE THREAD

**Issue by TobiTh** [hashicorp/terraform-provider-azurerm#13794]
The description of sku_size and sku_tier parameters are exactly the same:

From https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/static_site

`sku_tier` - (Optional) Specifies the sku tier of the Static Web App. Possible values are "Free" or "Standard". Defaults to "Free".

`sku_size` - (Optional) Specifies the sku tier of the Static Web App. Possible values are "Free" or "Standard". Defaults to "Free".

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

latest

### Affected Resource(s)

azurerm_static_site

### Expected Behaviour

The description for `sku_size` should be: (Changes marked as **bold**)
`sku_size` - (Optional) Specifies the sku **size** of the Static Web App. Possible values are "Free" or "Standard". Defaults to "Free".

### Actual Behaviour

The descriptions are duplicates

**Comment by stephybun** [comment]
Closed by #13861
