### ISSUE TITLE
can't get datasource azurerm_kubernetes_cluster with role Azure Kubernetes Service Cluster User Role

### ISSUE THREAD

**Issue by flbla** [hashicorp/terraform-provider-azurerm#13802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

azurerm 2.81.0 

### Affected Resource(s)

* data `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
data "azurerm_kubernetes_cluster" "example" {
  name                = "cluster_name"
  resource_group_name = "rg-name"
}
```

### Debug Output

The client 'XXXX' with object id 'XXXX' does not have authorization to perform action 'Microsoft.ContainerService/managedClusters/accessProfiles/listCredential/action' over scope '/subscriptions/XXX/resourceGroups/rg-name/providers/Microsoft.ContainerService/managedClusters/cluster_name/accessProfiles/clusterUser' or the scope is invalid. If access was recently granted, please refresh your credentials

### Expected Behaviour

My service principal has this default built in Azure role : _Azure Kubernetes Service Cluster User Role_ 
which has those permissions :
  "Microsoft.ContainerService/managedClusters/listClusterUserCredential/action",
  "Microsoft.ContainerService/managedClusters/read"

So it should be able to get the AKS cluster credentials, as I'm able to do a "az aks get-credentials" with it.
Furthermore, the listCredential API will be deprecated : https://docs.microsoft.com/en-us/rest/api/aks/managed-clusters/get-access-profile 

### Actual Behaviour

It crash with the previous debug output

### Steps to Reproduce

1. Create a SP with a role _Azure Kubernetes Service Cluster User Role_ on a cluster
2. Try to apply the previous TF code

**Comment by stephybun** [comment]
Hi @flbla

Thanks for raising this issue. The permission `Microsoft.ContainerService/managedClusters/listClusterUserCredential/action` will allow you to list the User Credential for the cluster but not the Access Profile which is the Kube Config. Whilst it would be possible to change the behaviour of the data source such that it functions with read-only credentials, accessing the Kube Config from the data source is one of the primary use cases. As such the end user will need to ensure that the service principal has all the necessary permissions for using the kubernetes data source.

Thanks!
