### ISSUE TITLE
Incorrect string formatting for API Management API Operation sample requests (quotes)

### ISSUE THREAD

**Issue by Dwight-D** [hashicorp/terraform-provider-azurerm#13804]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.9
on linux_amd64

- Installed hashicorp/azurerm v2.81.0 (signed by HashiCorp)
```

### Affected Resource(s)

* azurerm_api_management_api_operation

Specifically `request.representation.sample` property.

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_operation" "string-format-example" {
  operation_id = "string-format-example"
  api_name = azurerm_api_management_api.myapi.name
  api_management_name = azurerm_api_management.myapim.name
  resource_group_name = azurerm_resource_group.myrg.name
  display_name = "string-format-example"
  method = "POST"
  url_template = "/myendpoint"
  description = "Demonstrate a bug"

  request {
    description = "JSON-encoded request body"
    representation {
      content_type = "application/json"
      sample = "a string literal"      //                        <------- The offender
    }
  }
}
```

### Debug Output

Not relevant, relevant plan output:

```
      ~ request {
            # (1 unchanged attribute hidden)

          ~ representation {
              + sample       = "A string literal"
                # (1 unchanged attribute hidden)
            }
        }
    }
```

### Expected Behaviour

I expect to see a string containing only `A string literal` in the Azure GUI under API > Operation > string-format-example > Request > Representation :

![image](https://user-images.githubusercontent.com/25592807/138092263-d8684a64-c828-43e3-82f4-1c24f3144733.png)

### Actual Behaviour

I see my string wrapped in quotes: `"A string literal"`.
![image](https://user-images.githubusercontent.com/25592807/138094678-008520a9-aa32-491d-b04e-5b8982dddbdb.png)

The intended purpose of this field in this case is to contain JSON, so real life examples would result in a string-encoded JSON object (and this is indeed what happens, but I used simpler test data for demonstration purposes), which breaks the functionality of this property.

I.e. if I submit a value of the expected format, like this: `sample = file("sample.json")`, with sample.json having this:
```
{
  "foo": "bar"
}
```

I will have a string looking like this: `"{ \"foo\": \"bar\" }"`, which is of course not valid JSON and not what I submitted. This is string-encoded JSON which breaks the parsing, because of some kind of re-formatting done by either Terraform itself or the Azurerm provider in combination with this resource, I'm not sure which. I suspect it's the provider/resource because I have not encountered this same phenomenon anywhere else.

### Steps to Reproduce

Create Terraform project with the following resources:

* API Management instance: `azurerm_api_management`
* API: `azurerm_api_management_api` referencing the APIM resource
* API Operation: `azurerm_api_management_api_operation` referencing the API resource
* Add `request` block containing `representation` block containing `sample` property with any string as the value. Could be a basic string literal, `jsonencode(obj)` or a more complicated JSON object structure using `file(mysample.json)`, same result.
* Run `terraform apply`

Look at the actual value in the Azure portal GUI: `API Management > MyAPI > MyOperation > Request > Representation`

### Important Factoids

None.

### References

None.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
