### ISSUE TITLE
Support for forwardProxy in azurerm_app_service 

### ISSUE THREAD

**Issue by infogulch** [hashicorp/terraform-provider-azurerm#13833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The official Azure App Service team published a blog post in March 2021, [Deploying a secure, resilient site with a custom domain](https://azure.github.io/AppService/2021/03/26/Secure-resilient-site-with-custom-domain.html) [1], where they configure an example app service with AAD authentication ("Easy Auth") and a forward / reverse proxy in the form of Azure Front Door / Application Gateway. In the past, this required some very ugly workarounds [2] because prior to this post Easy Auth did not support serving behind a proxy.

The three settings they use to [configure the app service to allow forward proxies](https://azure.github.io/AppService/2021/03/26/Secure-resilient-site-with-custom-domain.html#alter-authentication-settings) [3] are:

* allowedExternalRedirectUrls - ✅ [Available today as auth_settings.allowed_external_redirect_urls](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#allowed_external_redirect_urls) [4]
* allowedAudiences - ✅ [Available today as auth_settings.active_directory.allowed_audiences](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#allowed_audiences) [5]
* forwardProxy - ❌ Not available

**I propose to add a new argument (or argument block) to the azurerm_app_service that allows configuring the forwardProxy auth setting.**

Note that there are several configurations for this property mentioned in the blog post, which are available to support various forward/reverse proxies with different/weird conventions (looking at you, application gateway):

```json
"forwardProxy": {
    "convention": "Standard"
}
```

```json
"forwardProxy": {
    "convention": "Custom",
    "customHostHeaderName": "X-Original-Host"
}
```

Just to acknowledge a detail in the article, the configuration with this setting was applied by executing an `az rest` command to post an auth.json configuration file to a new (?) `/authsettingsV2` endpoint. I don't know exactly what this would mean for the provider implementation, or if this detail changed since publishing in March 2021, but it may be relevant to the discussion.

> az rest --uri /subscriptions/REPLACE-ME-SUBSCRIPTIONID/resourceGroups/REPLACE-ME-RESOURCEGROUP/providers/Microsoft.Web/sites/REPLACE-ME-APPNAME/config/authsettingsV2?api-version=2020-09-01 --method put --body @auth.json 

### New or Affected Resource(s)

* `azurerm_app_service`

### Potential Terraform Configuration

Option 1, separate fields in both configurations:

```hcl
resource "azurerm_app_service" "example" {
  # ... snip ...
  
  auth_settings {
    # ... snip ...

    # Add:
    forward_proxy_convention = "Standard"
  }
}
```

```hcl
resource "azurerm_app_service" "example" {
  # ... snip ...
  
  auth_settings {
    # ... snip ...

    # Add:
    forward_proxy_convention = "Custom"
    forward_proxy_host_header = "X-Original-Host"
  }
}
```

Option 2, a block, in just the custom configuration (please infer the standard convention configuration):

```hcl
resource "azurerm_app_service" "example" {
  # ... snip ...
  
  auth_settings {
    # ... snip ...

    # Add:
    forward_proxy {
      convention = "Custom"
      host_header = "X-Original-Host"
    }
  }
}
```

### References

* [1] https://azure.github.io/AppService/2021/03/26/Secure-resilient-site-with-custom-domain.html 
* [2] https://stackoverflow.com/questions/64298867/asp-net-core-app-with-azure-ad-authentication-behind-a-reverse-proxy-is-setting
* [3] https://azure.github.io/AppService/2021/03/26/Secure-resilient-site-with-custom-domain.html#alter-authentication-settings
* [4] https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#allowed_external_redirect_urls
* [5] https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#allowed_audiences

Other references:
* [6] Difference between forward/reverse proxy https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/

**Comment by ezequielan** [comment]
Hi,
any ETA to support this configuration?, thanks!

**Comment by mgopez** [comment]
Any ETA? This would be very helpful.

**Comment by tizzir** [comment]
This feature would be very useful for me as well.

**Comment by epa095** [comment]
@infogulch : Looking at the specifications for [Microsoft.Web sites/config 'authsettings'](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-authsettings?pivots=deployment-language-arm-template) I dont see any forwardProxy anywhere. It is present in V2 though: [Microsoft.Web sites/config 'authsettingsV2'](https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/config-authsettingsv2?pivots=deployment-language-arm-template). So for me it seems like this depends on https://github.com/hashicorp/terraform-provider-azurerm/issues/12928, and is maybe even subsumed by it (so this could be closed?). Anyway it definitely does *not* seem like a good first issue ;-)

**Comment by epa095** [comment]
@infogulch : My message was **not** meant as a critisism of your background work, but I still don't understand how it can be a good first issue. It is my impression that it is not possible to combine V1 and V2 auth in the same webapp. If thats true, does this task actually entail starting the process towards authV2, but not fully supporting it (because that would be the full #12928)? Does it even make sence to support only this one feature of authv2, or would it only make sense if one also supported several other V2 features? 
Maybe @jackofallops has some input?
