### ISSUE TITLE
Support for enabling "Allow public access from any Azure service..." in azurerm_postgresql_flexible_server resource

### ISSUE THREAD

**Issue by aaronswainonset** [hashicorp/terraform-provider-azurerm#13873]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to request support for the firewall option "Allow public access from any Azure service within Azure to this server" in Azure Database for PostgreSQL flexible server.

### New or Affected Resource(s)

* azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "example-psqlflexibleserver"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  version                = "13"
  administrator_login    = "psqladminun"
  administrator_password = "H@Sh1CoR3!"
  storage_mb = 32768
  sku_name   = "GP_Standard_D4s_v3"
  public_azure_access_enabled = true
}
```

### References

* https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-firewall-rules#connect-from-azure

**Comment by aaronswainonset** [comment]
Any thoughts on this request?

**Comment by avandras** [comment]
Based on how the [Azure API works](https://docs.microsoft.com/en-us/rest/api/sql/2021-02-01-preview/firewall-rules/create-or-update), this feature can be enabled by setting both `start_ip_address` and `end_ip_address` to `0.0.0.0`

**Comment by aaronswainonset** [comment]
@avandras 
Thanks, that works as needed.
