### ISSUE TITLE
azurerm_bot_connection not applying client_id

### ISSUE THREAD

**Issue by brnwn4** [hashicorp/terraform-provider-azurerm#13892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 2.188.1
AzureRM Provider: 2.69.0

### Affected Resource(s)

azurerm_bot_connection 

### Expected Behaviour

The bot connection will be applied with the client id.

### Actual Behaviour

Bot connection is created with the Client Secret, Scope, TenantID, Name. However, the client id is not getting added. It shows in the deploy output that it will be created with the correct client ID, but when validating the resource through the portal everything BUT the client id is being added on the bot connection creation. The Client ID remains blank, regardless of the Correct ID showing in the deploy output.

### Steps to Reproduce

Create a azurerm_bot_connection via terraform.

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_connection

**Comment by lonegunmanb** [comment]
Hi @brnwn4 , I've tried the following code:

```hcl
resource "azurerm_resource_group" "example" {
  name     = "zjhe-13892"
  location = "West Europe"
}

resource "azurerm_bot_channels_registration" "example" {
  name                = "zjhe-13892"
  location            = "global"
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "F0"
  microsoft_app_id    = "#############"
}

resource "azurerm_bot_connection" "example" {
  name                  = "zjhe-13892"
  bot_name              = azurerm_bot_channels_registration.example.name
  location              = azurerm_bot_channels_registration.example.location
  resource_group_name   = azurerm_resource_group.example.name
  service_provider_name = "box"
  client_id             = "exampleId"
  client_secret         = "exampleSecret"
}
```

After provision, I can see `client_id` as "exampleId" on the portal(I believe it's in Bot Channels Registration configuration tab). Would you please check it again, or provide a minimum sample code that can reproduce this issue? Thanks!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
