### ISSUE TITLE
Support for setting multiple expanders for AKS autoscaler

### ISSUE THREAD

**Issue by yaraskm** [hashicorp/terraform-provider-azurerm#13900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Cluster Autoscaler allows multiple expander profiles to be used at once, so that if the first expander matches more than one Node Pool, the next expander is used to narrow down the selection. Currently however, the provider requires that only one expander can be set:

```
expander - Expander to use. Possible values are least-waste, priority, most-pods and random. Defaults to random.
```

```bash
$ terraform plan -out out.plan
╷
│ Error: expected auto_scaler_profile.0.expander to be one of [least-waste most-pods priority random], got priority,random
│
│   with module.oss_dev.azurerm_kubernetes_cluster.aks,
│   on ../modules/aks/main.tf line 123, in resource "azurerm_kubernetes_cluster" "aks":
│  123:     expander                         = "priority,random"
│
╵
```

Support should be added for multiple expanders.

### New or Affected Resource(s)
* azurerm_kubernetes_cluster

### Potential Terraform Configuration
```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  ...
  auto_scaler_profile {
    expander                         = "priority,random"
  }
}
```

### References

* https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-are-expanders
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#expander

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying AKS API so I am going to close it for now. When it gets added, we can reopen this request or you can create a new one.
https://github.com/Azure/AKS/issues/2610
