### ISSUE TITLE
terraform plan forcing AKS cluster node pool replacement due to change in AKS id

### ISSUE THREAD

**Issue by everspader** [hashicorp/terraform-provider-azurerm#13919]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0
```
### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.13.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.79.0"
    }
  }
}

provider "azurerm" {
  features {}

  subscription_id = var.SUBSCRIPTION_ID
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                = "myCluster"
  resource_group_name = "myResourceGroup"
  ...
}

resource "azurerm_kubernetes_cluster_node_pool" "nodepool" {
  ...
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  ...
  depends_on = [azurerm_kubernetes_cluster.aks,]
}
```

### Expected Behaviour

When running `terraform plan` after everything is created, no changes should be detected and the plan should be empty.

### Actual Behaviour

The plan detects that the `azurerm_kubernetes_cluster_node_pool.kubernetes_cluster_id` changed and requires replacement but what actually changed is the capital `G` in `resourcegroups` in the `id` string as so:
```hcl
# module.aks.azurerm_kubernetes_cluster_node_pool.nodepool must be replaced
-/+ resource "azurerm_kubernetes_cluster_node_pool" "nodepool" {
      - availability_zones     = [] -> null
      - enable_auto_scaling    = false -> null
      - enable_host_encryption = false -> null
      - enable_node_public_ip  = false -> null
      - fips_enabled           = false -> null
      ~ id                     = "/subscriptions/subscriptionId/resourcegroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCl  -> (known after apply)
      ~ kubelet_disk_type      = "OS" -> (known after apply)
      ~ kubernetes_cluster_id  = "/subscriptions/subscriptionId/resourcegroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCl -> "/subscriptions/subscriptionId/resourceGroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCluster" # forces replacement
```

```hcl
"/subscriptions/subscriptionId/resourcegroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCluster"
"/subscriptions/subscriptionId/resourceGroups/myResourceGroup/providers/Microsoft.ContainerService/managedClusters/myCluster"
```
### Steps to Reproduce

1. Create a simple `azurerm_kubernetes_cluster` and a `azurerm_kubernetes_cluster_node_pool` associated with it.
2. `terraform plan`
3.  `terraform apply`
4. After the cluster is created, try to run `terraform plan` without making any changes to the configurations.

**Comment by to266** [comment]
Just FYI, this is still an issue with 
```
❯ terraform version
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.88.1
```
