### ISSUE TITLE
v2.82.0 broke data source azurerm_network_interface

### ISSUE THREAD

**Issue by nebed** [hashicorp/terraform-provider-azurerm#13918]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0

### Affected Resource(s)

* data `azurerm_network_interface`

### Terraform Configuration Files

```hcl
data "azurerm_network_interface" "config" {
  name                = "nic_name"
  resource_group_name = "rg"
}
```

### Expected Behaviour

 should load data source 

### Actual Behaviour

 Error: setting `ip_configuration`: Invalid address to set: []string{"ip_configuration", "0", "gateway_load_balancer_frontend_ip_configuration_id"}

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
Fixed via #13865
