### ISSUE TITLE
Support for geo-replication of a SQL Managed Instance

### ISSUE THREAD

**Issue by fcatacut** [hashicorp/terraform-provider-azurerm#13932]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using Azure Portal, you can create a failover/secondary instance. In addition to using `azurerm_virtual_network_gateway` to create the requisite VPN Gateway described in the info box below, I believe that this requires a `dns_zone_partner` argument to be added to `azurerm_sql_managed_instance`, which takes the resource ID of the primary instance.

![image](https://user-images.githubusercontent.com/20847572/139160369-2ff05633-a83d-4694-bd29-0d5c244a68bf.png)

### New or Affected Resource(s)

* azurerm_sql_managed_instance

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_managed_instance" "primary" {
  name                         = "managedsqlinstance01"
  ...
  sku_name                     = "GP_Gen5"
  vcores                       = 4
  storage_size_in_gb           = 32
  ...
}

resource "azurerm_sql_managed_instance" "failover" {
  name                         = "managedsqlinstance02"
  ...
  sku_name                     = "GP_Gen5"
  vcores                       = 4
  storage_size_in_gb           = 32
  dns_zone_partner             = azurerm_sql_managed_instance.primary.id # new rgument
  ...
}
```

### References

It looks like `DnsZonePartner` is an argument that is available in AZ PowerShell: <https://docs.microsoft.com/en-us/powershell/module/az.sql/new-azsqlinstance>.

However, I don't see it in Azure CLI: <https://docs.microsoft.com/en-us/cli/azure/sql/mi?view=azure-cli-latest#az_sql_mi_create>.

**Comment by fcatacut** [comment]
Please re-open. PR #13951 is part 1 of a 2-part implementation.

**Comment by aristosvo** [comment]
@fcatacut My mistake, can't fix it unfortunately. To give a small update, tests are almost looking good, the complaint (hopefully the last one) I'm facing is the networking setup.

The biggest issue with regard to the speed of development is the test duration time, which takes up to 8 hours 🙃

**Comment by aristosvo** [comment]
@fcatacut The failover group and documentation are ready to merge, if you'd like you could take a look at the [docs](https://github.com/hashicorp/terraform-provider-azurerm/blob/4c83c8a11590c93aa1ae00ffa3d30d642b5725d5/website/docs/r/sql_managed_instance_failover_group.html.markdown) and [example setup](https://github.com/hashicorp/terraform-provider-azurerm/blob/4c83c8a11590c93aa1ae00ffa3d30d642b5725d5/examples/sql-azure/managed_instance_failover_group/main.tf).
