### ISSUE TITLE
CosmosDB resource trying to change VNets with virtual_network_rule

### ISSUE THREAD

**Issue by jmswick** [hashicorp/terraform-provider-azurerm#13947]
## Terraform version
```
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.7.0
+ provider registry.terraform.io/hashicorp/azurerm v2.76.0

```

## Terraform Configuration
```
resource "azurerm_cosmosdb_account" "cosmos_mongo" {
  name                = "${local.def_resource_prefix}-cdb"
  resource_group_name = azurerm_resource_group.resource_group_shared.name
  location            = azurerm_resource_group.resource_group_shared.location
  offer_type          = "Standard"

  kind                 = "MongoDB"
  mongo_server_version = var.cosmosdb_mongo_version

  ip_range_filter                   = local.cosmosdb_ip_filter
  is_virtual_network_filter_enabled = true

  dynamic "virtual_network_rule" {
    for_each = local.aks_subnets
    content {
      id                                   = virtual_network_rule.value
      ignore_missing_vnet_service_endpoint = false
    }
  }

  capabilities {
    name = "EnableMongo"
  }

  capabilities {
    name = "EnableServerless"
  }

  consistency_policy {
    consistency_level = "Session"
  }

  # Doesn't matter for serverless
  geo_location {
    location          = azurerm_resource_group.resource_group_shared.location
    failover_priority = 0
  }

  tags = local.common_tags
}
```

## Crash Output
Sanitized output
```
╷
│ Error: creating CosmosDB Account "cosmos-db-account" (Resource Group "cosmos-db-account-rg"): creating/updating CosmosDB Account "cosmos-db-account" (Resource Group "cosmos-db-account-rg"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client 'terraform-user-uid' with object id 'terraform-user-uid' has permission to perform action 'Microsoft.DocumentDB/databaseAccounts/write' on scope '/subscriptions/subscription-a-uid/resourceGroups/cosmos-db-account-rg/providers/Microsoft.DocumentDB/databaseAccounts/cosmos-db-account'; however, it does not have permission to perform action 'joinViaServiceEndpoint/action' on the linked scope(s) '/subscriptions/subscription-b-uid/resourceGroups/cluster-vnet-rg/providers/Microsoft.Network/virtualNetworks/cluster-vnet/subnets/cluster-pvtc-snet,/subscriptions/subscription-b-uid/resourceGroups/cluster-vnet-rg/providers/Microsoft.Network/virtualNetworks/cluster-vnet/subnets/cluster-pvtb-snet,/subscriptions/subscription-b-uid/resourceGroups/cluster-vnet-rg/providers/Microsoft.Network/virtualNetworks/cluster-vnet/subnets/cluster-puba-snet,/subscriptions/subscription-b-uid/resourceGroups/cluster-vnet-rg/providers/Microsoft.Network/virtualNetworks/cluster-vnet/subnets/cluster-pvta-snet' or the linked scope(s) are invalid."
│ 
│   with azurerm_cosmosdb_account.cosmos_mongo,
│   on cosmosdb.tf line 3, in resource "azurerm_cosmosdb_account" "cosmos_mongo":
│    3: resource "azurerm_cosmosdb_account" "cosmos_mongo" {
│ 
╵
```

## Expected Behavior

Create CosmosDB account with access restricted to the selected internal subnets.

## Actual Behavior

Apply run tries to modify the subnets, but the Service Principal it is running under does not have permission to modify the subnets.  However, the subnets already have the Microsoft CosmosDB service endpoint connected with them

## Steps to reproduce

1. Create two Azure subscriptions
2. Create a vnet with subnets in one subscription and add the CosmosDB service endpoint to them
3. Attempt to create a cosmosdb instance with Terraform in the second subscription with an account/service principal that does not have permission to modify resources in the first subscription.

## Additional Context

For accounting purposes we create Azure resources for different applications in separate subscriptions, but the application will be running on a shared kubernetes cluster, so the resources get configured with network ACLs that only allow the subnets of the cluster to access them.

Our terraform configurations are applied via service connectors (service principals) via Azure devops pipelines, and are configured such  that they only have permissions to specific subscriptions.

**Comment by jmswick** [comment]
Hmm,
Guess we can file this into the inconsistencies of Azure then, as doing this for Storage Accounts doesn't require that permission, and can do the subnet ACL without it.  Just that permission allows to add the service endpoint to the subnet if it doesn't already exist.

**Comment by aristosvo** [comment]
@jmswick Indeed, it is a bit different compared to other resources, also the reason why I didn't catch it at first.

I think we can close this issue, as based on the docs this is a Microsoft design decision.
