### ISSUE TITLE
azurerm_app_service - support load balancer eviction timer for unhealthy nodes

### ISSUE THREAD

**Issue by MartyMcFlaye** [hashicorp/terraform-provider-azurerm#13941]
### Community note

Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version
Terraform Core version: v1.0.9
AzureRM Provider version: v2.82.0

### Description

it seems that the "load balancing" (defining the time where an unhealthy instance remains in the load balancer before eviction) property is not available in terraform.

It could be very handy to add it

![appservice](https://user-images.githubusercontent.com/25328378/139214259-0ffbf6a8-d23e-4161-98e2-a87a6215f2ce.png)

**Comment by adamyager** [comment]
I do think the proper description should be "support Health Check for Linux function app, Windows function app, Linux app service and Windows App service" as the case may be.  
This is the official an proper name and will help end users understand what is being added. Oh and a most welcome addition for all these service in the azurerm 3.0.0

https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check

**Comment by jackofallops** [comment]
> I do think the proper description should be "support Health Check for Linux function app, Windows function app, Linux app service and Windows App service" as the case may be. This is the official an proper name and will help end users understand what is being added. Oh and a most welcome addition for all these service in the azurerm 3.0.0
> 
> [docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check](https://docs.microsoft.com/en-us/azure/app-service/monitor-instances-health-check)

Hi @adamyager - Thanks for the suggestion, I'll keep it in mind as we progress with adding/updating the beta items in preparation for 3.0.  I updated the title to reflect the request for configuring the unhealthy timer, rather than heath-check in general, to assist in my own tracking of features / properties for what is a very complex collection of resources. (since I had already added `health_check_path`).

**Comment by adamyager** [comment]
I do see the distinction as a sub capability. Thanks!

**Comment by jackofallops** [comment]
This feature is now supported by the 3.0 resources (for [example](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#health_check_eviction_time_in_min)), and `azurerm_app_service` has been deprecated, so I'm going to close out this issue. 

Thanks!
