### ISSUE TITLE
Support for Active Directory admin  of a SQL Managed Instance

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/terraform-provider-azurerm#13957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using Azure Portal, you can create a system managed identity/Service Principle and then set an Active Directory Admin for the instance.  You can optionally set if you want to Support only Azure Active Directory authentication for this managed instance
![image](https://user-images.githubusercontent.com/33451031/139416079-9eee15b0-5012-4cd0-9c38-6ca4795e193b.png)

this could be enabled in the same way as azurerm_sql_active_directory_administrator

### New or Affected Resource(s)

* azurerm_sql_managed_instance_administrator

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_managed_instance_administrator" "example" {
  server_name            = azurerm_sql_managed_instance.example.name
  resource_group_name    = azurerm_resource_group.example.name
  tenant_id              = data.azurerm_client_config.current.tenant_id
  object_id              = data.azuread_group.example_AD_Admin.object_id
  AD_auth_only           = false 
}

```

**Comment by aristosvo** [comment]
Hi @Marcus-James-Adams! This is a nice one, and definitely something I would like to see merged.

At this moment in time I've created a PR for #14049, as I expect this to be a prerequisite.
