### ISSUE TITLE
Change to azurerm_eventhub_namespace.network_rulesets and Customer Managed Keys leads to: Encryption properties are missing

### ISSUE THREAD

**Issue by schmidp** [hashicorp/terraform-provider-azurerm#13953]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Show Terraform Version and Providers
Terraform v1.0.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.7.0
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.10. You can update by downloading from https://www.terraform.io/downloads.html

Providers required by configuration:
.
├── provider[registry.terraform.io/hashicorp/azurerm] ~> 2.82.0
├── provider[registry.terraform.io/hashicorp/azuread] ~> 2.7.0
└── provider[registry.terraform.io/hashicorp/random]

Providers required by state:

    provider[registry.terraform.io/hashicorp/random]

    provider[registry.terraform.io/hashicorp/azuread]

    provider[registry.terraform.io/hashicorp/azurerm]

```

### Affected Resource(s)

* `azurerm_eventhub_namespace `
* `azurerm_eventhub_namespace_customer_managed_key`

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "main" {
  name                = "ehn-main"
  location            = data.azurerm_resource_group.rg01.location
  resource_group_name = data.azurerm_resource_group.rg01.name

  sku                 = "Premium"
  capacity            = 1
  zone_redundant      = true

  identity {
    type = "SystemAssigned"
  }

  network_rulesets {
    default_action = "Deny"
    trusted_service_access_enabled = false
  }
}

resource "azurerm_eventhub_namespace_customer_managed_key" "main" {
  eventhub_namespace_id = azurerm_eventhub_namespace.main.id
  key_vault_key_ids     = [azurerm_key_vault_key.infra_rg01_eventhub_namespace_main.id]
}

```

### Debug Output

https://gist.github.com/schmidp/e2ad307337dd86dbc9936f6ddf0d3128

### Expected Behaviour

If I change something in the `network_rulesets` block, I expect that change to be applied.

For example:

trusted_service_access_enabled from false to true.

### Actual Behaviour

I receive an error that the encryption properties are missing:

`
│ Error: creating Namespace: (Name "XXXXXX" / Resource Group "XXXXX"): performing CreateOrUpdate: namespaces.NamespacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Encryption properties are missing. Note: Once encryption has been enabled on a namespace, it cannot be disabled. CorrelationId: XXXX"
`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The event_hub_namespace and keyvault are both located in azure west europe.

### References

@schmirchi in the comments of https://github.com/hashicorp/terraform-provider-azurerm/issues/12677 has the same issue.

* #0000

**Comment by gchagan36** [comment]
Any update on this?

**Comment by abij** [comment]
Running into the same issue.

- AzureRM: 2.90.0
- Terraform 1.0.11

Action: **update Tag** on existing Eventhub Namespace with custom key.
Issue occors at Apply-stage.

```
2022-03-11T14:53:53.686+0100 [DEBUG] provider.terraform-provider-azurerm_v2.90.0_x5.exe: AzureRM Request: 
PUT /subscriptions/***/resourceGroups/eventhub-acc-rg/providers/Microsoft.EventHub/namespaces/***-dl-evh-acc?api-version=2021-01-01-preview HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.17.3 (amd64-windows) go-autorest/v14.2.1 pandora/namespaces/2021-01-01-preview HashiCorp Terraform/1.0.11 (+https://www.terraform.io) Terraform Plugin SDK/2.10.0 terraform-provider-azurerm/2.90.0 pid-222c6c49-1b0a-5959-a213-6608f9eb
8820
Content-Length: 419
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: cc8c3852-71d8-4326-7bd9-45cc4b55253b
Accept-Encoding: gzip

{"identity":{"type":"SystemAssigned","tenantId":"","principalId":"","userAssignedIdentities":null},
"location":"westeurope",
"properties":{"isAutoInflateEnabled":false,"zoneRedundant":true},
"sku":{"capacity":1,"name":"Premium","tier":"Premium"},
"tags":{"ADO-Project":"****","Automation":"Terraform","Build":"manual-deployment","department":"**** - DataLake Platform team","git-repo":"de-infra-eventhub"}}

: timestamp=2022-03-11T14:53:53.686+0100
2022-03-11T14:53:54.918+0100 [DEBUG] provider.terraform-provider-azurerm_v2.90.0_x5.exe: AzureRM Response for https://management.azure.com/subscriptions/***/resourceGroups/eventhub-acc-rg/providers/Microsoft.EventHub/n
amespaces/***-dl-evh-acc?api-version=2021-01-01-preview:
HTTP/2.0 400 Bad Request


{"error":{"message":"Encryption properties are missing. Note: Once encryption has been enabled on a namespace, it cannot be disabled. CorrelationId: cc8c3852-71d8-4326-7bd9-45cc4b55253b","code":"BadRequest"}}: timestamp=2022-03-11T14:53:54.918+0100   
```
> Encryption properties are missing. Note: Once encryption has been enabled on a namespace, it cannot be disabled
