### ISSUE TITLE
Front Door Custom HTTPS Configuration Docs Wrong

### ISSUE THREAD

**Issue by matt-lethargic** [hashicorp/terraform-provider-azurerm#13952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.9
AzureRM 2.81.0

### Affected Resource(s)

* `azurerm_frontdoor_custom_https_configuration`
* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "app" {
  name                                         = local.frontdoor_name
  resource_group_name                          = azurerm_resource_group.app.name
  enforce_backend_pools_certificate_name_check = false

  tags = local.common_tags

  frontend_endpoint {
    name                     = local.frontdoor_name
    host_name                = local.frontdoor_hostname
    session_affinity_enabled = false
  }

  frontend_endpoint {
    name                     = "app"
    host_name                = local.frontdoor_app_host
    session_affinity_enabled = false
  }

  ...

  backend_pool {
    name = "propt-app-backend"
    ...
  }
}

resource "azurerm_frontdoor_custom_https_configuration" "app" {
  frontend_endpoint_id              = azurerm_frontdoor.app.frontend_endpoint[1].id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

### Debug Output

N/A

### Expected Behaviour

See docs page https://registry.terraform.io/providers/hashicorp/azurerm/2.81.0/docs/resources/frontdoor_custom_https_configuration

The example for `azurerm_frontdoor_custom_https_configuration` is

```
frontend_endpoint_id = azurerm_frontdoor.example.frontend_endpoints["exampleFrontendEndpoint2"]
```
I expect this to work, I get errors

### Steps to Reproduce

1. Follow example
2. `terraform apply`
3. Observe errors

### Important Factoids

Only thing I can get to work is using an integer and then I have no real way of knowing if I'm referencing the correct endpoint other than guessing
frontend_endpoint_id = azurerm_frontdoor.example.frontend_endpoints[1]

### References

* #0000

**Comment by heoelri** [comment]
You can be more specific by addressing them via their name. Here's an example how I'm addressing them:

```hcl
resource "azurerm_frontdoor" "main" {
  name                                         = local.frontdoor_name
  resource_group_name                          = azurerm_resource_group.global.name
  ...

  frontend_endpoint {
    name                     = local.frontdoor_default_frontend_name
    host_name                = local.frontdoor_default_dns_name
    session_affinity_enabled = false

    web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.main.id
  }

  dynamic "frontend_endpoint" {
    for_each = azurerm_dns_cname_record.app_subdomain # there is either 1 or 0 resources, depending on whether a custom domain name was supplied
    content {
      name                                    = local.frontdoor_custom_frontend_name
      host_name                               = trimsuffix(frontend_endpoint.value.fqdn, ".") # remove trailing dot (.) from the end of the FQDN
      session_affinity_enabled                = false
      web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.main.id
    }
  }
}
```

```hcl
resource "azurerm_frontdoor_custom_https_configuration" "custom_domain_https" {
  count                             = var.custom_fqdn != "" ? 1 : 0
  frontend_endpoint_id              = "${azurerm_frontdoor.main.id}/frontendEndpoints/${local.frontdoor_custom_frontend_name}"
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

In my example `azurerm_frontdoor_custom_https_configuration` is applied when `var.custom_fqdn != ""` and `frontend_endpoint_id` points to a combination of `azurerm_frontdoor.main.id` + `/frontendEndpoints/` + `local.frontdoor_custom_frontend_name` (which is the name of my custom frontend.

**Comment by WodansSon** [comment]
The legacy Frontdoor resources are being retired and are no longer in development.
