### ISSUE TITLE
Support for  setting  maintenance  windows on azurerm_sql_managed_instance

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/terraform-provider-azurerm#13959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azure portal allows you to change the system maintenance window of azurerm_sql_managed_instance, it would be good if we could set this from the start via terraform

### New or Affected Resource(s)

* azurerm_sql_managed_instance

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_managed_instance" "example" {
  name                         = "example"
  resource_group_name          = azurerm_resource_group.main.name
  location                     = "UK South"
  administrator_login          = "admin"
  administrator_login_password = random_password.example.result
  license_type                 = "BasePrice"
  subnet_id                    = data.terraform_remote_state.tf_core.outputs.managed_sql_subnet_id
  sku_name                     = var.sku_name
  vcores                       = var.vcores
  storage_size_in_gb           = var.storage_size_in_gb
  collation                    = var.collation
  maintenance                  = ("System Default" ,"Monday-to-Thursday", or "Friday-to-Saturday")
}
```

**Comment by aristosvo** [comment]
Hi @Marcus-James-Adams! Thanks for this issue, great functionality.

I've taken a quick look to check what it takes to support this functionality. It has location dependent maintenance options, which makes configuration a bit harder. It might even make sense to expose the possibilities as a data source themselves, not completely sure yet how I'd implement it.

It doesn't seem extremely difficult, but it's not a walk in the park either. With currently 3 PRs in flight for `azurerm_sql_managed_instance` (which has tests which can take up to 8+ hours) I'll pass this one for now until there is some room on my work-in-progress list.

**Comment by Marcus-James-Adams** [comment]
Would it simplify things if they were extracted to s separate resource, similar to what we are now doing for #13957 and #13932?

**Comment by macro-labs** [comment]
We already have azurerm_maintenance_configuration. The only issue is that we have no way to assign it to a managed instance. We can assign it to a dedicated host, vm, or scaleset and that is it - despite the fact that the maintenance configuration resource itself supports sql database and sql managed instance as a scope - rendering those scope values kind of pointless.
