### ISSUE TITLE
azurerm_cosmosdb_account gets destroyed/replaced when changing backup type

### ISSUE THREAD

**Issue by pollyapostolova** [hashicorp/terraform-provider-azurerm#13963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 1.0.9
azurerm 2.83.0

### Affected Resource(s)

cosmosdb_account

### Terraform Configuration Files

```
resource "azurerm_cosmosdb_account" "db" {
  name                = "${var.environment}-cosmos-db"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = false
  enable_free_tier          = true

  backup {
    type = "Continuous"
  }

  consistency_policy {
    consistency_level = "Eventual"
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }
}
```

### Expected Behaviour

After adding the backup block the backup type should change to Continuous without affecting anything else in the resource.

### Actual Behaviour

Terraform tries to replace the entire cosmosdb_account resource:

# azurerm_cosmosdb_account.db must be replaced
-/+ resource "azurerm_cosmosdb_account" "db" {
      ~ backup {
          ~ interval_in_minutes = 240 -> (known after apply)
          ~ retention_in_hours  = 8 -> (known after apply)
          ~ type                = "Periodic" -> "Continuous" # forces replacement
        }

### Steps to Reproduce

1. `terraform apply`

### References

Looking at the provider, it looks like the backup property is configured to force a resource replacement - [link](https://github.com/hashicorp/terraform-provider-azurerm/blob/cc3a286a6438a7d8c97a0260fc1d0fb4172e7087/internal/services/cosmos/cosmosdb_account_resource.go#L346)

**Comment by aristosvo** [comment]
Hi @pollyapostolova, thanks for filing this issue!

#13967 allows a one-way change of backup type from `Periodic` to `Continuous`. This should fix this issue 🎉
