### ISSUE TITLE
Subsequent Terraform runs wants to remove Azure Key Vault access policies that were created by Terraform

### ISSUE THREAD

**Issue by aaronswainonset** [hashicorp/terraform-provider-azurerm#13977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Cloud - v1.0.9
AzureRM Provider: >=2.71.0

### Affected Resource(s)

* `azurerm_key_vault`
* `azurerm_key_vault_access_policy`

### Terraform Configuration Files

In main.tf:
```hcl
module "kv" {
  source   = "./modules/key-vault"
  kv_name  = "my-kv"
  location = azurerm_resource_group.rg.location
  rg_name  = azurerm_resource_group.rg.name
  tags     = azurerm_resource_group.rg.tags
}

resource "azurerm_key_vault_access_policy" "app_service" {
  key_vault_id       = module.kv.kv_id
  object_id          = azurerm_app_service.my_app.identity[0].principal_id
  tenant_id          = data.azurerm_client_config.current.tenant_id

  key_permissions = [
    "Get",
    "List"
  ]
  secret_permissions = [
    "Get",
    "List",
    "Set"
  ]
  storage_permissions = [
    "Get",
    "List"
  ]
}
```

In /modules/key-vault.tf:
```hcl
resource "azurerm_key_vault" "kv" {
  name                        = var.kv_name
  resource_group_name         = var.rg_name
  location                    = var.location
  enabled_for_disk_encryption = var.enabled_for_disk_encryption
  purge_protection_enabled    = var.purge_protection
  sku_name                    = var.sku_name
  soft_delete_retention_days  = var.soft_delete_retention_days
  tenant_id                   = data.azurerm_client_config.current.tenant_id

  access_policy {
    # Grant access to Terraform
    object_id               = data.azurerm_client_config.current.object_id
    tenant_id               = data.azurerm_client_config.current.tenant_id
    certificate_permissions = [
      "Delete",
      "Get",
      "Import",
      "List",
      "Purge",
      "Update"
    ]
    key_permissions         = [
      "Get",
      "List",
      "Purge"
    ]
    secret_permissions      = [
      "Delete",
      "Get",
      "List",
      "Purge",
      "Recover",
      "Set"
    ]
    storage_permissions     = [
      "Get",
      "List"
    ]
  }

  tags = var.tags
}

output "kv_id" {
  description = "Key vault ID"
  value       = azurerm_key_vault.kv.id
}
```

### Expected Behaviour

The above key vault and access policies are created correctly the first time Terraform Cloud runs. Every subsequent Terraform plan/apply should have no change on the resources in Azure (key vault and its access policies) when nothing has changed in Azure or Terraform.

### Actual Behaviour

The above key vault and access policies are created correctly the first time Terraform Cloud runs. When changing nothing in Azure or the Terraform script, every subsequent Terraform Cloud plan will show Terraform wants to remove the App Service's access policy (created by the azurerm_key_vault_access_policy.app_service resource) from the key vault:

```hcl
# module.kv.azurerm_key_vault.kv will be updated in-place
~ resource "azurerm_key_vault" "kv" {
  ~ access_policy                   = [
      - {
          - application_id          = ""
          - certificate_permissions = []
          - key_permissions         = []
          - object_id               = "object-id-redacted" ## This is the App Service
          - secret_permissions      = [
              - "Get",
              - "List",
            ]
          - storage_permissions     = []
          - tenant_id               = "redacted"
        },
        {
            application_id          = ""
            certificate_permissions = [
                "Delete",
                "Get",
                "Import",
                "List",
                "Purge",
                "Update",
            ]
            key_permissions         = [
                "Get",
                "List",
                "Purge",
            ]
            object_id               = "object-id-redacted" ## This is the Terraform SP
            secret_permissions      = [
                "Delete",
                "Get",
                "List",
                "Purge",
                "Recover",
                "Set",
            ]
            storage_permissions     = [
                "Get",
                "List",
            ]
            tenant_id               = "redacted"
        },
    ]
    id                              = "/subscriptions/redacted/resourceGroups/redacted/providers/Microsoft.KeyVault/vaults/my_kv"
    name                            = "my_kv"
    tags                            = {
        "environment" = "Staging"
    }
    # (12 unchanged attributes hidden)

    # (1 unchanged block hidden)
}
```

### Steps to Reproduce

1. Create a key vault and assign access policies as shown in the code above.
2. Apply the resource.
3. Without changing anything, immediately re-run the plan in Terraform Cloud and it will report it wants to remove the access policy.

### References

* #0000

**Comment by aristosvo** [comment]
Hi @aaronswainonset! This is expected behaviour and well documented in the [`azurerm_ key_vault_access_policy ` resource documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy):
> It's possible to define Key Vault Access Policies both within the `azurerm_key_vault resource` via the `access_policy` block and by using the `azurerm_key_vault_access_policy` resource. However it's not possible to use both methods to manage Access Policies within a KeyVault, since there'll be conflicts.

I'd recommend to use `azurerm_key_vault_access_policy` in the `key-vault` module instead of the inline `access_policy` to prevent this behaviour.

**Comment by aaronswainonset** [comment]
Hi @aristosvo , the meaning of that warning never made sense until now. Thanks for the clarification.
