### ISSUE TITLE
azurerm_firewall_policy_rule_collection_group missing mssql for application_rule_collection protocol options and applies wrong character restrictions for rule names

### ISSUE THREAD

**Issue by lysacor** [hashicorp/terraform-provider-azurerm#13980]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.10
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.83.0

### Affected Resource(s)

* `azurerm_firewall_policy_rule_collection_group`

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy_rule_collection_group" "Sample-Col-Group" {
  name               = "Sample-Firewall"
  firewall_policy_id = azurerm_firewall_policy.Firewall-policy-obj.id
  priority           = 200
  application_rule_collection {
    name     = "Sample Rule"
    priority = 300
    action   = "Allow"
    rule {
      name              = "Allow Azure Portal"
      source_addresses  = ["10.1.2.3", "10.1.2.3"]
      destination_fqdns = ["*.azure.com"]
      protocols {
        type = "Http"
        port = 80
      }
      protocols {
        type = "Https"
        port = 443
      }
      protocols {
	type = "Mssql"
	port = 1433
    }
  }
```

### Expected Behaviour

Change commits without issue, and new application rule collection is provisioned
### Actual Behaviour

In Azure, the name of a rule within a rule collection can contain spaces, underscores, hyphens, letters and numbers. The terraform azurerm provider arbitrarily removes the ability to use spaces in names. The error I get when using rule names with spaces is:

│ Error: invalid value for application_rule_collection.23.rule.0.name (The name must begin with a letter or number, end with a letter, number or underscore, and may contain only letters, numbers, underscores, periods, or hyphens.)       
│
│   with azurerm_firewall_policy_rule_collection_group.Sample-Col-Group,
│   on main.tf line 1433, in resource "azurerm_firewall_policy_rule_collection_group" "Sample-Col-Group":
│ 1433: resource "azurerm_firewall_policy_rule_collection_group" "Sample-Col-Group"

The character requirements for the name do not conform with the permitted character set by AzureRM per Microsoft's documentation.

Attached is a screenshot of the allowed characters in a rule
![image](https://user-images.githubusercontent.com/29993795/139726763-47d8b19a-fd7e-4bb1-9428-33401837af77.png)

Additionally, when I attempt to have a protocol block of type "Mssql", a valid protocol according to Microsoft documentation. I get an error when I run terraform plan or apply with the above code (once the name is corrected):
│ Error: expected application_rule_collection.27.rule.1.protocols.0.type to be one of [Http Https], got Mssql
│
│   with azurerm_firewall_policy_rule_collection_group.AZUVFW1-Rules,
│   on main.tf line 1433, in resource "azurerm_firewall_policy_rule_collection_group" "Sample-Col-Group":
│ 1433: resource "azurerm_firewall_policy_rule_collection_group" "Sample-Col-Group"

According to Microsoft's documentation for Azure Firewall, the Azure Firewall application rules can process HTTP, HTTPS, AND MSSQL traffic. All three protocol types are supported in Azure firewall. We make extensive use of those datatypes in our firewall policies.

Attached is a screenshot of the allowed protocols in a rule.
![image](https://user-images.githubusercontent.com/29993795/139727272-134466c3-64eb-46ac-8d03-a7039505d026.png)

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### Important Factoids

This is a deployed in South Central US, and is not running in a special Azure government environment.
### References

* https://docs.microsoft.com/en-us/azure/firewall/rule-processing#network-rules-and-applications-rules

**Comment by dogfastly** [comment]
Although I can create an **Mssql** application rule in the UI, the following page does not show that as an option when using an ARM template. I fall back to ARM templates when terraform has a gap, but it may not be possible to do so using IaC, which is certainly non-optimal. I will test using an ARM template later today to confirm.

Reference: https://docs.microsoft.com/en-us/azure/templates/microsoft.network/firewallpolicies/rulecollectiongroups?tabs=json#firewallpolicyruleapplicationprotocol

**FirewallPolicyRuleApplicationProtocol**
- protocolType
- The application protocol type of a Rule.
- 'Http' 'Https'

**Comment by dogfastly** [comment]
I was able to create the **Mssql** application rule in a policy using an ARM template. It would be very nice if this can be incorporated into the terraform resource instead of having to use ARM.

`
resource "azurerm_resource_group_template_deployment" "example_rcg" {
  name                = "example-deploy"
  resource_group_name = azurerm_resource_group.example.name
  deployment_mode     = "Incremental"
  template_content    = <<TEMPLATE
  {
    "$schema": "https://schema.management.azure.com/schemas/2019-08-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "ruleCollectionGroupName": {
        "type": "String",
        "minLength": 5,
        "metadata": {
          "description": "Name of the rule collection group."
        }
      },
      "location": {
        "type": "String",
        "metadata": {
          "description": "Location of the rule collection group."
        }
      },
      "ruleCollectionGroupPriority": {
        "type": "Int",
        "defaultValue": 1000,
        "metadata": {
          "description": "Priority of the rule collection group."
        }
      },
      "sourceAddresses": {
        "type": "Array",
        "metadata": {
          "description": "Source IP addresses allowed to access the target FQDNs."
        }
      },
      "targetFqdns": {
        "type": "Array",
        "metadata": {
          "description": "FQDNs of the target resources."
        }
      }
    },
    "resources": [
      {
        "apiVersion": "2020-05-01",
        "type": "Microsoft.Network/firewallPolicies/ruleCollectionGroups",
        "name": "[parameters('ruleCollectionGroupName')]",
        "location": "[parameters('location')]",
        "properties": {
          "priority": "[parameters('ruleCollectionGroupPriority')]",
          "ruleCollections": [
            {
              "ruleCollectionType": "FirewallPolicyFilterRuleCollection",
              "name": "sql-private-endpoints",
              "priority": 1000,
              "action": {
                "type": "Allow"
              },
              "rules": [
                {
                  "ruleType": "ApplicationRule",
                  "name": "allow-inbound-1433-to-sql-private-endpoints",
                  "protocols": [
                    {
                      "protocolType": "Mssql",
                      "port": 1433
                    }
                  ],
                  "terminateTLS": false,
                  "sourceAddresses": "[parameters('sourceAddresses')]",
                  "targetFqdns": "[parameters('targetFqdns')]"
                }
              ]
            }
          ]
        }
      }
    ]
  }
TEMPLATE

  parameters_content = <<PARAMETERS
  {
    "ruleCollectionGroupName": {
      "value": "${azurerm_firewall_policy.example.name}/example-sql-pol-rcg"
    },
    "location": {
      "value": "${azurerm_resource_group.example.location}"
    },
    "ruleCollectionGroupPriority": {
      "value": 1400
    },
    "sourceAddresses": {
      "value": ${jsonencode(var.source_addresses)}
    },
    "targetFqdns": {
      "value": ${jsonencode(var.target_fqdns)}
    }
  }
PARAMETERS

  depends_on = [
    azurerm_firewall_policy.example
  ]
}
`

**Comment by brakelee** [comment]
Is there some news about this feature request, because we need this feature in our Premium firewall for Mssql.

**Comment by torivara** [comment]
We are also in need of this feature right now. Would be nice to know when we can start using this via Terraform. ARM is not a viable option for the long run.

**Comment by torivara** [comment]
For anyone looking, I created this with the AzApi provider:

```terraform
locals {
  policy_array         = split("/", var.firewall_policy_id)
  firewall_policy_name = local.policy_array[8]
  resource_group_name  = local.policy_array[4]
}

variable "firewall_policy_id" {
  type        = string
  description = "Firewall policy id"
}

variable "api_version" {
  type        = string
  description = "API Version of rule collection group"
  default     = "2021-08-01"
}

data "azurerm_firewall_policy" "fwpolicy" {
  name                = local.firewall_policy_name
  resource_group_name = local.resource_group_name
}

resource "azapi_resource" "rule_collection_group" {
  type      = "Microsoft.Network/firewallPolicies/ruleCollectionGroups@${var.api_version}"
  name      = "Rule-Collection-Name"
  parent_id = var.firewall_policy_id

  body = jsonencode({
    name = var.firewall_rule_collection_group_name
    properties = {
      priority = 1000
      ruleCollections = [
        {
          ruleCollectionType = "FirewallPolicyFilterRuleCollection"
          name               = "ruleCollectionProd"
          priority           = 1000
          action = {
            type = "Allow"
          }
          rules = [
            {
              ruleType = "ApplicationRule"
              name     = "allow-inbound-to-prod-databases-from-somewhere"
              protocols = [
                {
                  protocolType = "Mssql"
                  port         = 1433
                }
              ]
              terminateTLS = false
              sourceAddresses = [
                "10.1.0.4/32",
                "10.1.0.5/32"
              ]
              targetFqdns = [
                "proddb01.database.windows.net",
                "proddb02.database.windows.net"
              ]
            }
          ]
        },
        {
          ruleCollectionType = "FirewallPolicyFilterRuleCollection"
          name               = "ruleCollectionTest"
          priority           = 1000
          action = {
            type = "Allow"
          }
          rules = [
            {
              ruleType = "ApplicationRule"
              name     = "allow-inbound-to-test-databases-from-somewhere"
              protocols = [
                {
                  protocolType = "Mssql"
                  port         = 1433
                }
              ]
              terminateTLS = false
              sourceAddresses = [
                "10.0.0.4/32",
                "10.0.0.5/32"
              ]
              targetFqdns = [
                "testdb01.database.windows.net",
                "testdb02.database.windows.net"
              ]
            }
          ]
        }
      ]
    }
  })
}
```
