### ISSUE TITLE
Intermittent error with azurerm_function_app_host_keys Error: making Read request on AzureRM Function App Hostkeys "

### ISSUE THREAD

**Issue by saroup** [hashicorp/terraform-provider-azurerm#13982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version 1.0.9
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.78.0"
    }
  }

### Affected Resource(s)

data "azurerm_function_app_host_keys" 

### Terraform Configuration Files

data "azurerm_function_app_host_keys" "function_app" {
  name                = azurerm_function_app.function_app.name
  resource_group_name = var.resource_group.name
}
resource "azurerm_function_app" "function_app" {
  name                                     = local.function_name
  resource_group_name          = var.resource_group.name
  location                                 = var.resource_group.location
  app_service_plan_id              = var.app_service_plan_id
  storage_account_name         = azurerm_storage_account.function_storage.name
  storage_account_access_key = azurerm_storage_account.function_storage.primary_access_key
  version                                   = "~3"
  os_type                                  = "linux"

  site_config {
    vnet_route_all_enabled = true
    always_on                      = true
    linux_fx_version             = "python|3.8"
  }

  app_settings = merge(var.settings, local.common_settings)

  identity {
    type            = "UserAssigned"
    identity_ids = [var.managed_identity.id]

  }
}

### Debug Output

Error: making Read request on AzureRM Function App Hostkeys "functionapp_name": web.AppsClient#ListHostKeys: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxx-xxxx-xxxx-bxxxx44c-xxxxx' with object id 'xxx-xxxx-xxxx-xxx' does not have authorization to perform action 'Microsoft.Web/sites/host/listkeys/action' over scope '/subscriptions/xxxxxxxxxx/resourceGroups/resourcegroupe-rg/providers/Microsoft.Web/sites/functionapp_name/host/default' or the scope is invalid. If access was recently granted, please refresh your credentials."
with module.azure-functions["functionapp_name"].data.azurerm_function_app_host_keys.function_app
on .terraform/modules/azure-functions/data_sources.tf line 6, in data "azurerm_function_app_host_keys" "function_app":

This fails sometimes and sometimes passes even though the infrastructure and permissions haven't changed.
### Steps to Reproduce

 Running workspace from TFC

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
