### ISSUE TITLE
`azurerm_mssql_database` property `storage_account_type` not working as expected

### ISSUE THREAD

**Issue by merca** [hashicorp/terraform-provider-azurerm#13989]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.8.0
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

Your version of Terraform is out of date! The latest version
is 1.0.10. You can update by downloading from https://www.terraform.io/downloads.html     

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "sql_database" {
  name                        = format("%s-%s-%s-sqldb", var.company, local.environment_letter, var.short_name)
  server_id                   = azurerm_mssql_server.this.id
  sku_name                    = "GP_S_Gen5_1"
  min_capacity                = 1
  collation                   = "Danish_Norwegian_CI_AS"
  storage_account_type        = "LRS"
  auto_pause_delay_in_minutes = var.auto_pause_in_minutes

  tags = var.tags
  lifecycle {
    ignore_changes = [
      tags["Created"],
    ]
  }
}
```

### Expected Behaviour

Database is created with `Locally-redundant backup storage`

### Actual Behaviour

Database is created with `Geo-redundant backup storage`

### Steps to Reproduce

1. `terraform apply`with version >= 2.82.0
    (tested and works with version <=2.81.0)

**Comment by aristosvo** [comment]
Hi @merca! I'm sorry, this is caused by an update of mine which overlooked one aspect of the change in the Azure APIs. 

PR is filed here (#13990). I'll need to test if this really fixes your troubles, but I expect so 👍🏽
