### ISSUE TITLE
Changing AzureRM policy definition parameters fails

### ISSUE THREAD

**Issue by kaovd** [hashicorp/terraform-provider-azurerm#13991]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.0
AzureRM 2.82.0

### Affected Resource(s)

azurerm_policy_definition

### Terraform Configuration Files

```hcl
...
  parameters = jsonencode(each.value.parameter)
...
```

### Debug Output

```
policy.DefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyParameterUpdate" Message="The existing policy has '3' parameter(s) which is greater than the count of parameter(s) '1' in the policy being added. Policy parameters cannot be removed during policy update."

```

### Expected Behaviour

Terraform should force new resource

### Actual Behaviour

Terraform attempts to patch and error is returned

### Steps to Reproduce

Create a azure policy definition with a number of parameters, then reduce parameters on next apply

### References

Exact same issue previously reported but was workarounded via force new on the name

#2422

**Comment by AshutoshNirkhe** [comment]
I am facing quite a similar issue, wherein I am unable to change any of the policy or initiative parameters,

`
Error: updating Policy Set Definition "CoreTech-Kubernetes-Policies": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicySetParameterUpdate" Message="The existing policy set parameter(s) 'block_host_namespace_excluded_workloads,host_network_ports_excluded_workloads' were not found in the policy set being updated. The parameter names can not be changed."
`

As a result, we can't delete/update any parameters for policies/initiatives.

**Comment by NovemberZulu** [comment]
We are still encountering this error with AzureRM `3.89.0` (Terraform `1.4.6`)
