### ISSUE TITLE
CosmosDB Recreated due to Capability removal which was not declared

### ISSUE THREAD

**Issue by andessi** [hashicorp/terraform-provider-azurerm#14002]
All of our CosmosDb instances want to be re-created due to a Capability changing (EnableSql) which isn't defined in our resources file. Could someone help explain why TF wants to recreate this resource suddenly?

Change being applied:

```

- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v2.74.0

  # ... must be replaced
-/+ resource "azurerm_cosmosdb_account" "my-cdb" {
      // ... 

      - capabilities { # forces replacement
          - name = "EnableSql" -> null
        }
    }
```

Sample definition: 
```
resource "azurerm_cosmosdb_account" "my-cdb" {
    name                = local.safename
    location            = local.location
    resource_group_name = local.rgname
    offer_type          = "Standard"
    kind                = "GlobalDocumentDB"
    tags                = {
        real_name = local.realname
    }

    consistency_policy {
        consistency_level = "Strong"
    }

    geo_location {
        location = local.location
        failover_priority = 0
    }
}
```

**Comment by andessi** [comment]
cc @sinbai and @katbyte as it looks related to a bug fix in a different version. Have I run into this somehow?

**Comment by sinbai** [comment]
@andessi CosmosDB Account got recreated due to change in capabilities value. It is a TF behavior which is by current TF design. The reason of the change of the capabilities value is as follows (from Azure service team), though there was no change performed on the TF client side.

> _Our resource, “Cosmos DB Database Account”, expose a property called “capabilities” which is an array of objects. It is by design that this capabilities array may contain capability objects that are injected by the system, even if user does not directly request for it._

**Comment by sebader** [comment]
We ran into the same issue. This is a real no-no and I would assume this might lead to very nasty situations for quite some people

**Comment by hatfarm** [comment]
What's the best practice recommended then @sinbai ?  It seems risky that a param that's not even set can so extremely affect our resources.

**Comment by sinbai** [comment]
@hatfarm The v2.83.0 of the Terraform Provider contains the #13936. It ignores the change of capabilities when there is no change performed on TF side. Please upgrade the version of Azurerm to avoid the risks brought by this case.
