### ISSUE TITLE
Split provider between different Azure Clouds

### ISSUE THREAD

**Issue by dtns2** [hashicorp/terraform-provider-azurerm#14017]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.83.0
```

### Affected Resource(s)

* affects the [azurerm provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest) directly, not any specific resources/data sources.

### Terraform Configuration Files

```hcl
provider "azurerm" {
  alias           = "public"
  environment     = "public"
  subscription_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  features {}
}
data "azurerm_subscription" "public" { provider = azurerm.public }

provider "azurerm" {
  alias           = "usgovernment"
  environment     = "usgovernment"
  subscription_id = "yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy"
  features {}
}
data "azurerm_subscription" "usgovernment" { provider = azurerm.usgovernment }

output "subscription_ids" { value = {
  public       = data.azurerm_subscription.public.id
  usgovernment = data.azurerm_subscription.usgovernment.id
} }
```

### Debug Output

* Terraform Apply debug output when `az cloud set --name AzureCloud`:
  * https://gist.github.com/dtns2/d0a3c02efe95ace08fe09f1a1911ac6e 
* Terraform Apply debug output when `az cloud set --name AzureUSGovernment`:
  * https://gist.github.com/dtns2/b46d9755da50b1ab14a64e76ecc52981

### Expected Behaviour

* Having multiple `azurerm` providers in a single Terraform root module should allow one to manage resource in multiple different Azure subscriptions, tenants, or even clouds at the same time.
  * Managing resources in multiple subscriptions or tenants is already supported with multiple azurerm Terraform providers
  * **Point of Concern:** This issue aims focus on the use case of managing resources in two different subscriptions that preside in two different Azure clouds at the same time (in this example `AzureCloud` and `AzureUSGovernment`)

### Actual Behaviour

* Having multiple `azurerm` providers setup in a single Terraform root module where the `environment` field is set to different values (e.g. `public` and `usgovernment` in this example) will cause a failure due to the fact that Azure CLI requires one to set the Azure Cloud to a single value at a time with the `az cloud set --name <NAME>` [command](https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest).

### Steps to Reproduce

1. `az cloud set --name AzureCloud`
2. `terraform apply`

**or**

1. `az cloud set --name AzureUSGovernment`
2. `terraform apply`

### Important Factoids

* To reiterate, the above issue can be observed when running the included Terraform Configuration code snippet when one has their Azure Cloud set to either `AzureCloud` or `AzureUSGovernment` and presumed would also be an issue if combining any other clouds such as `AzureGermanCloud` or `AzureChinaCloud`.

### References

* Azurerm Terraform Provider documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs
* Azure CLI `az cloud` command documentation: https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest

**Comment by tombuildsstuff** [comment]
hi @dtns2 

Thanks for opening this issue.

As you've mentioned the Azure CLI only allows for authenticating against a single cloud at a time - as it's possible for Terraform (and any other products using the Azure CLI, such as the Azure Backend) to make requests against the Azure CLI in parallel, as such even if we were to dynamically change the cloud we're talking too, unfortunately that'd potentially cause unexpected issues for other products, meaning that this isn't really something we can fix unfortunately.

Instead in this scenario we'd recommend using a Service Principal for authentication against either a single or both clouds - potentially using the Azure CLI against the other - you can [find more information on how to authenticate using a Service Principal here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret).

Thanks!

**Comment by archoversight** [comment]
@tombuildsstuff You can't use Service Principals across AzureCloud/AzureUSGovernment since just like AWS partitions (commercial/govCloud) nothing is shared.
