### ISSUE TITLE
There is no subnet SQL service endpoint resource

### ISSUE THREAD

**Issue by abaymar** [hashicorp/terraform-provider-azurerm#14016]
I would like to be able to allow a newly created AKS cluster to access my Azure SQL Server.

For that I need to create an Azure SQL Firewall rule and enable the Mircrosoft.Sql server endpoint for the AKS VNet subnet.

Because this subnet is created and managed by Azure, it's not supposed to be a Terraform resource and I should not be importing it.

How do I enable the service point, which requires changing a property of a resource not managed by Terraform?

**Comment by abaymar** [comment]
Current workaround: 

```
resource "null_resource" "my_subnet_endpoint" {
  depends_on = [
    data.azurerm_subnet.my_subnet
  ]
  provisioner "local-exec" {
    command = "az network vnet subnet update -n aks-subnet --vnet-name ${data.azurerm_resources.my_vnet.resources[0].name} -g ${azurerm_kubernetes_cluster.my_vnet.node_resource_group} --service-endpoints Microsoft.Sql"
  }
}

**Comment by aristosvo** [comment]
Hi @abaymar! This is something which is hard to support with Terraform without a small modification.

The solution I applied in similar situations is a BYO VNet/Subnet:
```hcl
resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  address_space       = ["10.0.0.0/16"]
  resource_group_name = azurerm_resource_group.aks.name
  location            = azurerm_resource_group.aks.location
}

resource "azurerm_subnet" "subnet_aks" {
  name                 = "aks-subnet"
  resource_group_name  = azurerm_resource_group.aks.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.0.0/22"]

  service_endpoints = ["Microsoft.Sql"]
}


resource "azurerm_kubernetes_cluster" "aks" {
  ...

  default_node_pool {
    ...
    vnet_subnet_id = azurerm_subnet.subnet_aks.id
  }
  ...
}
```

Does this solve your problems? It would require a recreation of AKS unfortunately.

**Comment by abaymar** [comment]
I think I might lose Azure SLA if I modify anything under MC_* resource group, as opposed to having AKS modify it.

**Comment by aristosvo** [comment]
Indeed, this solution circumvents that by using a VNet and Subnet from outside of the MC_* resource group.

This is backed up by Microsoft docs [here](https://docs.microsoft.com/en-us/azure/aks/configure-kubenet#create-a-virtual-network-and-subnet) how to configure it via `az cli`.

**Comment by abaymar** [comment]
Oh I see - yes, BYO VNet might be a solution - albeit it seems more invasive than running the CLI command.

**Comment by aristosvo** [comment]
@abaymar Although it is a setup which is a bit more advanced, this is the solution Terraform offers for your problem within the boundaries of the Azure SLA rules.

As this is also the solution suggested and advised when using other tools, I hereby close this issue.

If there are any remarks or other reasons to reopen this issue, let me know!
