### ISSUE TITLE
Virtual_Network - however the linked subscription '00000000-0000-0000-0000-000000000000' was not found. "

### ISSUE THREAD

**Issue by javabrad** [hashicorp/terraform-provider-azurerm#14021]
The configuration below is returning :
Error: creating/updating Virtual Network: (Name "mvwc-eastus-corp-nonprd-vnet" / Resource Group "mvwc-eastus-corp-nonprd-rg"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Network/ddosProtectionPlans/join/action' on scope '/subscriptions/{real subscription_id}/resourceGroups/mvwc-eastus-corp-nonprd-rg/providers/Microsoft.Network/virtualNetworks/mvwc-eastus-corp-nonprd-vnet', however the linked subscription '00000000-0000-0000-0000-000000000000' was not found. "

only on the vnet resource ,  with or without ddos configuration

SP created all the components so it is the owner of all the resources including the subscription

Terrafrom 15.5
azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.77.0"  (2.83.0)
    }

resource "azurerm_subscription" "this" {
  provider = azurerm
  alias             = lower(local.base_name)           
  subscription_name = lower(local.subscription_name)
  billing_scope_id  = data.azurerm_billing_enrollment_account_scope.this.id
  workload          = var.subscription_workload
}

resource "azurerm_management_group_subscription_association" "this" {
  provider = azurerm
  management_group_id = data.azurerm_management_group.this.id
  subscription_id     = format("/subscriptions/%s",azurerm_subscription.this.subscription_id)
}

 provider "azurerm" {
  alias = "applz"
  features {}
  client_id       = local.client_id
  client_secret   = local.client_secret
  tenant_id       = local.tenant_id
  subscription_id = azurerm_subscription.this.subscription_id  
}

resource "azurerm_network_ddos_protection_plan" "vnet" {
  provider = azurerm.applz
  name                = format("%s-ddos",local.base_name)
  location            = azurerm_resource_group.vnet.location
  resource_group_name = azurerm_resource_group.vnet.name
}

resource "azurerm_virtual_network" "vnet" {
  provider = azurerm.applz
  name                = local.vnet_name
  resource_group_name = azurerm_resource_group.vnet.name
  location            = azurerm_resource_group.vnet.location
  tags                = azurerm_resource_group.vnet.tags
  address_space       = var.address_space
  dns_servers         = var.dns_servers

ddos_protection_plan {
    id     = azurerm_network_ddos_protection_plan.vnet.id
    enable = false
  }
  
  lifecycle {
    ignore_changes = [tags]
  }
}

**Comment by tombuildsstuff** [comment]
hi @javabrad 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
