### ISSUE TITLE
Using Terraform to deploy Azure Cloud Shell accounts and storage for users

### ISSUE THREAD

**Issue by tplive** [hashicorp/terraform-provider-azurerm#14029]
Hi!
If this issue has been discussed earlier, I apologize for not finding it, but I've been looking all over the Internetz for a way to use either az cli commands or (preferably) Terraform to deploy Azure Cloud Shell accounts for our (Azure admin/operator) users. All I can find is guidance on how to use Azure Cloud Shell to run terraform and az cli! :)

So I want to provision Azure Cloud Shell in a particular region and subscription, with particular settings (as exposed under "Advanced settings" when you set it up through the portal) but I'm unable to find such guidance.

Has it been done before? Can you help me out?

All the best,
Thomas

**Comment by aristosvo** [comment]
Hi @tplive! Are you looking to implement it for them beforehand, or to ease up the setup for the users doing it themselves?

This is an important question, as the [Cloud Shell APIs as exposed](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cloudshell/resource-manager/Microsoft.Portal/stable/2018-10-01) are a bit limited and implemented to run by the user who needs the Cloud Shell, as it is seen as a personal setting in the portal. It would require impersonation, which might make it a bit harder to implement than any other random resource. It is also not available in the Go SDK, making it an upstream issue at the same time.

I'm not saying I don't want to give it a try, but it would take a bit of time before we could even start, and it might not even serve your purposes that well. Providing the storage accounts beforehand and ~~certain `az cli` based scripts might be the better route~~ a manual how to set it up the preferred way would be a faster route.. For a head start on some personal automation, check [here](https://docs.microsoft.com/en-us/azure/cloud-shell/troubleshooting#personal-data-in-cloud-shell).

**Edit:** I just realised it is not even implemented in `az cli`, which might be a sign better not go this path.

**Comment by tplive** [comment]
@aristosvo, thank you for your excellent reply!
I was thinking about setting it up for a number of platform operators, as we have requirements to keep storage in a particular region, in a specific subscription and so forth. A set of `az cli` commands would suffice, so each operator would be able to set up her own environment following a "template", but ideally we would want to control it through TF and/or Access Packages. Looking into the link you added, thanks! :)

**Comment by aristosvo** [comment]
Great, you're welcome!

I'll close this issue for now, as I don't see a potential path to a Terraform solution without changes on the Azure Cloud Shell resource itself.

Have a nice day!
