### ISSUE TITLE
azurerm_cosmosdb_account change in validation

### ISSUE THREAD

**Issue by ernesto1596** [hashicorp/terraform-provider-azurerm#14039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version: 1.09 on linuxamd64
AzureRm Provider Version: 2.83.0

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "<redacted>" {
  name                = <redacted>
  location            = <redacted>
  resource_group_name = <redacted>
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = <redacted>
    failover_priority = 0
  }
}
```

### Expected Behaviour

No changes required

### Actual Behaviour

Fails terraform validation with
`capability EnableMongo must be enabled if MongoDBv3.4 is also enabled`

### Steps to Reproduce

1. Create CosmosDb Account with AzureRm Version < 2.82
2. `terraform apply`
3. Update to AzureRm >= 2.82
4. `terraform apply`

### Important Factoids

I understand that the change was added so this situation would not occur but for accounts previously created before the check has put our terraform state in a deadlock when upgrading as re-creating the account is not an option.

### References

* Added in #13757

**Comment by katbyte** [comment]
related to #14301
