### ISSUE TITLE
Uploaded certificate from ACME provider to Key Vault crashes

### ISSUE THREAD

**Issue by alexgagnon** [hashicorp/terraform-provider-azurerm#14040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 1.0.10
AzureRM: 2.83.0

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    acme = {
      source  = "vancluever/acme"
      version = "~> 2.0"
    }

    azurerm = {
      source = "hashicorp/azurerm"
      version = "2.83.0"
    }
  }
}

provider "acme" {
  server_url = "https://acme-staging-v02.api.letsencrypt.org/directory"
}

provider "azurerm" {
  features {}
}

locals {
  algorithm = "RSA"
  bits = 2048
}

resource "tls_private_key" "reg_private_key" {
  algorithm = local.algorithm
  rsa_bits = local.bits
}

resource "acme_registration" "reg" {
  account_key_pem = "${tls_private_key.reg_private_key.private_key_pem}"
  email_address   = "***"
}

resource "tls_private_key" "cert_private_key" {
  algorithm = "RSA"
}

resource "tls_cert_request" "req" {
  key_algorithm   = "RSA"
  private_key_pem = "${tls_private_key.cert_private_key.private_key_pem}"
  dns_names = ["*.ssl-test.***"]

  subject {
    common_name = "ssl-test.***"
  }
}

resource "acme_certificate" "certificate" {
  account_key_pem         = "${acme_registration.reg.account_key_pem}"
  certificate_request_pem = "${tls_cert_request.req.cert_request_pem}"

  dns_challenge {
    provider = "azure"

    config = {
      AZURE_RESOURCE_GROUP = "***"
      AZURE_ZONE_NAME = "***"
    }
  }
}

resource "azurerm_key_vault_certificate" "kv_cert" {
  name = "test-cert"
  key_vault_id = "***"

  certificate {
    contents = acme_certificate.certificate.certificate_p12
    password = ""
  }

  certificate_policy {
    issuer_parameters {
      name = "Unknown"
    }

    key_properties {
      key_size = local.bits
      key_type = local.algorithm
      exportable = true
      reuse_key = true
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }
  }
}
```

### Debug Output

https://gist.github.com/alexgagnon/753c42bef4819a3074d360481fac206e

### Expected Behaviour

Certificate should be uploaded to Key Vault

### Actual Behaviour

Crashed

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Running in Azure DevOps, using a Service Principal with Owner access to the Key Vault

**Comment by aristosvo** [comment]
Hi @alexgagnon! I dove into this one for a bit, but it's hard to tackle without a last bit of information. It would be great if you could help me here.

Is it possible that `acme_certificate.certificate.certificate_p12` is empty or nil at the moment of creating the `azurerm_key_vault_certificate`?

**Comment by alexgagnon** [comment]
Thanks! I managed to get it working just by removing the CSR!

**Comment by jaydrue** [comment]
I am experiencing the same issue. How did you actually resolve it @alexgagnon? 

The error should really be thrown before runtime, ideally when validation takes place and should be more descriptive.

**Comment by aristosvo** [comment]
Hi @jaydrue, #14061 does exactly that and will be released in the next release 🥳 

https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate shows an example without an external CSR (first), implementation of that flow with KV should solve this problem functionality wise.

**Comment by jaydrue** [comment]
Thanks for the reply! I am not using an external CSR. I am making a request to Let‘s Encrypt. Is that in itself a using an external CSR? All our domain names and hosting is on azure.

Can you point out the part you changed in your issue on github. That would be very helpful.

On 9 Nov 2021, at 16:39, aristosvo ***@***.***> wrote:

﻿
Hi @jaydrue, #14061 does exactly that and will be released in the next release 🥳

https://registry.terraform.io/providers/vancluever/acme/latest/docs/resources/certificate shows an example without an external CSR (first), implementation of that flow with KV should solve this problem functionality wise.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
