### ISSUE TITLE
azurerm_virtual_network_gateway resource expects 3 IP configuration blocks, however only 2 are allowed.

### ISSUE THREAD

**Issue by crawfs** [hashicorp/terraform-provider-azurerm#14044]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.14.3
AzureRM version: Tested on both 2.63 and 2.83

### Affected Resource(s)

* `azurerm_virtual_network_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "gateway_zone_redundant" {
  name                = "redeploymentgateway-pip-az"
  location            = azurerm_virtual_network.redeploymentgateway.location
  resource_group_name = azurerm_virtual_network.redeploymentgateway.resource_group_name
  domain_name_label   = "redeploymentgateway-az"

  allocation_method   = "Static"
  sku                 = "Standard"
  availability_zone   = "Zone-Redundant"
}

resource "azurerm_public_ip" "gateway_zone_redundant2" {
  name                = "redeploymentgateway-pip-az2"
  location            = azurerm_virtual_network.redeploymentgateway.location
  resource_group_name = azurerm_virtual_network.redeploymentgateway.resource_group_name
  domain_name_label   = "redeploymentgateway-az2"

  allocation_method   = "Static"
  sku                 = "Standard"
  availability_zone   = "Zone-Redundant"
}

resource "azurerm_public_ip" "gateway_zone_redundant3" {
  name                = "redeploymentgateway-pip-az3"
  location            = azurerm_virtual_network.redeploymentgateway.location
  resource_group_name = azurerm_virtual_network.redeploymentgateway.resource_group_name
  domain_name_label   = "redeploymentgateway-az3"

  allocation_method   = "Static"
  sku                 = "Standard"
  availability_zone   = "Zone-Redundant"
}

resource "azurerm_virtual_network_gateway" "gateway" {
  name                = "redeploymentgateway"
  location            = azurerm_virtual_network.redeploymentgateway.location
  resource_group_name = azurerm_virtual_network.redeploymentgateway.resource_group_name

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = true
  enable_bgp    = true
  sku           = "VpnGw1AZ"

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = azurerm_public_ip.gateway_zone_redundant.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.redeploymentgateway["GatewaySubnet"].id
  }
  ip_configuration {
    name                          = "vnetGatewayConfig2"
    public_ip_address_id          = azurerm_public_ip.gateway_zone_redundant2.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.redeploymentgateway["GatewaySubnet"].id
  }
  ip_configuration {
    name                          = "vnetGatewayConfig3"
    public_ip_address_id          = azurerm_public_ip.gateway_zone_redundant3.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.redeploymentgateway["GatewaySubnet"].id
  }
  vpn_client_configuration {
    address_space = ["172.21.0.0/24"]
    aad_tenant = "https://login.microsoftonline.com/***/"
    aad_audience = "***"
    aad_issuer = "https://sts.windows.net/***/"
  }
}
```

### Debug Output

This is the error in the API that is returned with only two IP configurations present:
```
Error: Creating/Updating AzureRM Virtual Network Gateway "Virtual Network Gateway: (Name \"redeploymentgateway\" / Resource Group \"network-deploy\")": network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ActiveActiveP2SGatewayMustHaveExactlyThreeIpConfigurations" Message="Gateway 2 has /subscriptions/***/resourceGroups/network-deploy/providers/Microsoft.Network/virtualNetworkGateways/redeploymentgateway IP configurations specified for gateway. ActiveActive Gateway with Vpn client configuration must be created with three IP configurations." Details=[]
```

Output for azurerm 2.63 if run with 3 IP configurations:

```
Error: ip_configuration: attribute supports 2 item maximum, config has 3 declared

  on vpn.tf line 80, in resource "azurerm_virtual_network_gateway" "gateway":
  80: resource "azurerm_virtual_network_gateway" "gateway" {
```

Output for azurerm 2.83 if run with 3 IP configuration blocks:
```
Error: Too many list items

  on vpn.tf line 80, in resource "azurerm_virtual_network_gateway" "gateway":
  80: resource "azurerm_virtual_network_gateway" "gateway" {
```

### Expected Behaviour

The VPN gateway should be updated with 3 IP configurations to allow for the Point to site VPN as specified by the returned error in the API

### Actual Behaviour

The terraform provider validation only expects 2 IP configuration blocks total, making the configuration impossible

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

As far as I can tell having an active-active gateway with a point to site VPN in Azure is an undocumented scenario in microsoft docs, however as shown the API does appear to have useful errors for troubleshooting the issue.

This only only occurs when deploying an active-active gateway with a point-to-site configuration

### References

* #0000

**Comment by aristosvo** [comment]
Hi @crawfs! I'm currently exploring the options here, but I'm facing a lot of errors here.

Have you created such a setup before in a different way (`az` or ARM templates) or is this a first? In case of this being a first, I'd say to first ask Azure Support how this could be created and if there are any SKU requirements for Gateway or IP besides the stated setup. 

At this moment in time I'm ending up with failed VPN Gateways without any insights what is going wrong: `Code="VmssGatewayDeploymentFailed" Message="The gateway deployment operation failed due to an intermittent error. Please try again."`
