### ISSUE TITLE
Support for optional public IP in Azure Firewall

### ISSUE THREAD

**Issue by hariprabu2010** [hashicorp/terraform-provider-azurerm#14055]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

As of September 9, Microsoft have announced that Public IP is not required when Azure Firewall is setup in forced tunneling mode. When deploying through portal, Public IP could be set as none when the forced tunneling is enabled. Need this feature enabled in terraform to secure the firewalls by not exposing the public IP.

### New or Affected Resource(s)

Azure Firewall

* azurerm_firewall

### Potential Terraform Configuration

resource "azurerm_firewall" "azure_firewall" {

  name                  = var.azure_firewallname
  location              = var.azure_firewallregion
  resource_group_name   = var.resource_group
  ip_configuration {
    name                 = "IpConf"
    subnet_id            = data.azurerm_subnet.subnets[count.index].id
    public_ip_address_id = "none"
  }

### References

https://azure.microsoft.com/en-us/blog/boost-your-network-security-with-new-updates-to-azure-firewall

Deploy Azure Firewall without public IP in Forced Tunnel mode
Azure Firewall service requires public IP for its operational purposes. While secure, some deployments don’t prefer exposing public IP directly to the internet. In such cases, customers can deploy Azure Firewall in Forced Tunnel mode. This configuration creates a management NIC which is used by Azure Firewall for its operations. The Tenant Datapath network can be configured without a public IP, and internet traffic can be forced tunneled to another Firewall or completely blocked.

* #0000

**Comment by hariprabu2010** [comment]
Hi, any updates on this? We want to secure our firewall by removing public ip but unable to do so.

**Comment by devildog-tech** [comment]
Evening,

Is there any plans to resolve this issue. We are building a whole Enterprise Hub and Spoke design in Azure to support 1000's of applications. Until this issue is fixed Terraform is not even an option for us. I'm forced to use Bicep. Any information would be helpful. Thank you..

**Comment by pcbl** [comment]
Hey. Stumbled on this issue as well. Are there any trick to skip this issue?
I deployed the firewall manually and imported it to check how the terraform state is... Here you can see it:
**note the "" on the "public_ip_address_id" attribute for the "ip_configuration" section...**
```
"ip_configuration": [
  {
    "name": "tst-firewall_IPConf",
    "private_ip_address": "10.1.2.4",
    "public_ip_address_id": "",
    "subnet_id": "/subscriptions/XXXXXXX/resourceGroups/p2s-vpn-dev/providers/Microsoft.Network/virtualNetworks/main-vnet/subnets/AzureFirewallSubnet"
  }
],
"location": "westeurope",
"management_ip_configuration": [
  {
    "name": "firewall-mgmt-ip",
    "private_ip_address": "",
    "public_ip_address_id": "/subscriptions/XXXXXXX/resourceGroups/p2s-vpn-dev/providers/Microsoft.Network/publicIPAddresses/firewall-mgmt-ip",
    "subnet_id": "/subscriptions/XXXXXXX/resourceGroups/p2s-vpn-dev/providers/Microsoft.Network/virtualNetworks/main-vnet/subnets/AzureFirewallManagementSubnet"
  }
],
```
