### ISSUE TITLE
Error: updating Azure Storage Account `blob_properties` "storage_account_name"

### ISSUE THREAD

**Issue by iugastefan922** [hashicorp/terraform-provider-azurerm#14053]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version:  0.15.3, azurerm provider version: "2.83.0"

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```
resource "azurerm_storage_account" "example_name" {
  name = examplestorageaccountname
  resource_group_name = example-rg-name
  location = "switzerlandnorth"
  account_tier = "Standard"
  account_replication_type = var.account_replication_type 
  is_hns_enabled = true
  min_tls_version = "TLS1_2"
  allow_blob_public_access = false
  enable_https_traffic_only = true
  blob_properties {
    container_delete_retention_policy {
      days = 7
    }
  }
    network_rules {
    default_action = "Deny"
    bypass         = ["None"]
    ip_rules       = var.ip_rules
    private_link_access {
      endpoint_resource_id = var.endpoint_resource_id 
      endpoint_tenant_id   = data.azurerm_client_config.current.tenant_id
      }
    }

    routing {
      publish_internet_endpoints  = false
      publish_microsoft_endpoints = true
      choice                      = "MicrosoftRouting"
    }
    
  tags = local.tags
}
```

### Debug Output

Error: updating Azure Storage Account `blob_properties` "storage_account_name": storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account storage_account_namewas not found."

### Expected Behaviour

Storage account created in the new region.

### Actual Behaviour

Failing with:
Error: updating Azure Storage Account `blob_properties` "storage_account_name": storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account storage_account_namewas not found."

Tried to remove the blob_properties block (as per the documentation it is optional), and I'm getting this error:
 Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to azurerm_storage_account.adls_ns, provider
│ "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

### Steps to Reproduce

Deployed a storage account via Terraform in North Europe Region

Change the region in the code from North Europe to North Switzerland

Pipeline failing with the issue mentioned above. If I remove the blob_properties block (optional as per the documentation) , it fails with a different error stated above.

**Comment by aristosvo** [comment]
Hi @iugastefan922! That sounds like a networking issue, based on your configuration. 

The blocking issue might be the network rules configured, as `blob_properties` in general are configured using data plane APIs, which require data plan access from your Terraform runner.

Does this also show up without `network_rules` configured? You might need to include data plan access in your configuration of the `azurerm_storage_account` from your Terraform runner (locally, pipeline, cloud) to make `blob_properties` work.

**Comment by iugastefan922** [comment]
> Hi @iugastefan922! That sounds like a networking issue, based on your configuration.
> 
> The blocking issue might be the `network_rules` configured, as `blob_properties` in general are configured using data plane APIs, which require data plan access from your Terraform runner.
> 
> Does this also show up without `network_rules` configured? You might need to include data plan access in your configuration of the `azurerm_storage_account` from your Terraform runner (locally, pipeline, cloud) to make `blob_properties` work.

Thanks for the clarification. In the meantime I also found out that the issue was that I was trying to whitelist a vnet from another region in the North Switzerland account, which is not possible.

BR,

Stefan
