### ISSUE TITLE
vnet peering gets disconnected when adding a new ressource

### ISSUE THREAD

**Issue by manfred0191** [hashicorp/terraform-provider-azurerm#14051]
Hi, I have exactly the same problem like it has been described in issue

https://github.com/hashicorp/terraform/issues/18091

Unfortunately nowhere was a solution to this published.

My terraform deployment runs OK when I do an initial deployment. When adding a new ressource, for instance another VM or a SQL database, I get his error message:

```
Error: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="RemotePeeringIsDisconnected" Message="Cannot create or update peering /subscriptions/… because remote peering /subscriptions/… referencing parent virtual network /subscriptions/… is in Disconnected state. Update or re-create the remote peering to get it back to Initiated state. Peering gets Disconnected when remote vnet or remote peering is deleted and re-created." Details=[]
68│ 
69│ with azurerm_virtual_network_peering.hub-spoke1-peer[0],
70│ on main.tf line 100, in resource "azurerm_virtual_network_peering" "hub-spoke1-peer":
71│ 100: resource "azurerm_virtual_network_peering" "hub-spoke1-peer" {


```

**Comment by aristosvo** [comment]
Hi @manfred0191! This issue has been tried to fix [here in a combination issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/1576#issuecomment-493500708), but it could not be reproduced.

Do you have a reproducible minimal setup to make fixing this more easy?

**Comment by manfred0191** [comment]
Hi, fortunately the error did no longer occur after I was using gitlab-terraform instead of terraform in the version 1.0.3.
Therefore I would agree to close this issue.

**Comment by mybayern1974** [comment]
Close this issue with getting agreement from the issue author.
