### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.84.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by emmaeyo** [hashicorp/terraform-provider-azurerm#14068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`
* `azurerm_app_service_virtual_network_swift_connection`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_monitor_diagnostic_setting" "logs" {
  count = var.enable_audit_logging == true ? 1 : 0 

  name               = "diag-audit-storage"
  target_resource_id = local.consumable.id

  storage_account_id = var.audit_storage_account_id

  dynamic "log" {
    for_each = sort(data.azurerm_monitor_diagnostic_categories.default.logs)
    content {
      category = log.value
      enabled  = true

      retention_policy {
        enabled = true
        days    = 0 
      }
    }
  }
}

resource "azurerm_app_service_virtual_network_swift_connection" "this" {
  app_service_id = azurerm_function_app.datadog_logs_sender.id
  subnet_id      = data.azurerm_subnet.this.id
}

```

### Panic Output

╷
│ Error: Plugin did not respond
│ 
│   with azurerm_monitor_diagnostic_setting.logs[0],
│   on common_includes_diag_retention.tf line 24, in resource "azurerm_monitor_diagnostic_setting" "logs":
│   24: resource "azurerm_monitor_diagnostic_setting" "logs" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with azurerm_app_service_virtual_network_swift_connection.this,
│   on main.tf line 523, in resource "azurerm_app_service_virtual_network_swift_connection" "this":
│  523: resource "azurerm_app_service_virtual_network_swift_connection" "this" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵

Stack trace from the terraform-provider-azurerm_v2.84.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5aa88ce]

goroutine 153 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/web.resourceAppServiceVirtualNetworkSwiftConnectionCreateUpdate(0xc001d2d200, 0x5ec8c60, 0xc0010d8000, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/web/app_service_virtual_network_swift_connection_resource.go:83 +0x17ae
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0013b5880, 0x6fadbc8, 0xc001943740, 0xc001d2d200, 0x5ec8c60, 0xc0010d8000, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:318 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0013b5880, 0x6fadbc8, 0xc001943740, 0xc001384230, 0xc001ee42c0, 0x5ec8c60, 0xc0010d8000, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:456 +0x67b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000dc50, 0x6fadbc8, 0xc001943740, 0xc0000c2d70, 0xc001943740, 0x6401580, 0xc0019b6300)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc001c1b240, 0x6fadc70, 0xc001943740, 0xc0013840e0, 0xc001c1b240, 0xc0019b63f0, 0xc0008ffba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6401580, 0xc001c1b240, 0x6fadc70, 0xc0019b63f0, 0xc00191b260, 0x0, 0x6fadc70, 0xc0019b63f0, 0xc00162a480, 0x40b)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022aa80, 0x7002138, 0xc00029bc80, 0xc0019b4360, 0xc001166ae0, 0xad40ac0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022aa80, 0x7002138, 0xc00029bc80, 0xc0019b4360, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000fc49c0, 0xc00022aa80, 0x7002138, 0xc00029bc80, 0xc0019b4360)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.84.0_x5 plugin crashed!

### Expected Behaviour

The resources should be created

### Actual Behaviour

Resources are not created. Error: The terraform-provider-azurerm_v2.84.0_x5 plugin crashed! . This is a blocker. 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aristosvo** [comment]
Hi @emmaeyo! Thanks for reporting, it seems there is a nil check missing, `existing.SwiftVirtualNetworkProperties != nil`:
https://github.com/hashicorp/terraform-provider-azurerm/blob/61dc4ef8966d10dd6dbe69be039a63c183431987/internal/services/web/app_service_virtual_network_swift_connection_resource.go#L83

I'll file the PR to fix it.

**Comment by emmaeyo** [comment]
Thank you @aristosvo
