### ISSUE TITLE
Support for TriggerCallbackUrl in Azure Logic App

### ISSUE THREAD

**Issue by weldpua2008** [hashicorp/terraform-provider-azurerm#14078]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am using `azurerm_monitor_action_group` with `azurerm_logic_app_workflow` unfortunately` `data.azurerm_logic_app_workflow.logicapp_data.access_endpoint` is not  enough for triggering the Logic App from the action group.

 Standart PowerShell module has [Get-AzLogicAppTriggerCallbackUrl](https://docs.microsoft.com/en-us/powershell/module/az.logicapp/get-azlogicapptriggercallbackurl?view=azps-6.6.0)

### New or Affected Resource(s)

* azurerm_logic_app_workflow

### Potential Terraform Configuration

```hcl
data "azurerm_logic_app_workflow" "logicapp" {
  name                =  var.logicapp_name
  resource_group_name = var.resource_group_name
 }

resource "azurerm_monitor_action_group" "notify" {
  logic_app_receiver {
        callback_url            = data.azurerm_logic_app_workflow.logicapp.trigger_callback_url
    }
}

```

* #0000

**Comment by neil-yechenwei** [comment]
@weldpua2008, thanks for raising this issue. Per my understanding, you're asking you cannot find the `callback_url` for Logic App Trigger. If yes, I think you can find it from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_trigger_http_request#callback_url. 

Below is an example. If you need, you can try it.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-mag-test01"
  location = "eastus"
}

resource "azurerm_logic_app_workflow" "test" {
  name                = "acctestLAW-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_logic_app_trigger_http_request" "test" {
  name         = "some-http-trigger"
  logic_app_id = azurerm_logic_app_workflow.test.id

  schema = <<SCHEMA
{
	"type": "object",
	"properties": {
		"hello": {
			"type": "string"
		}
	}
}
SCHEMA
}

resource "azurerm_monitor_action_group" "test" {
  name                = "acctestActionGroup-test01"
  resource_group_name = azurerm_resource_group.test.name
  short_name          = "acctestag"

  logic_app_receiver {
    name                    = "logicappaction"
    resource_id             = azurerm_logic_app_workflow.test.id
    callback_url            = azurerm_logic_app_trigger_http_request.test.callback_url
    use_common_alert_schema = true
  }
}
```

**Comment by mybayern1974** [comment]
@weldpua2008 , would you agree this issue could be closed if you think the suggestion provided by Neil could resolve your issue?

**Comment by weldpua2008** [comment]
The callback_url doesn't includes the token. So logicapp can't be triggered.

**Comment by neil-yechenwei** [comment]
@weldpua2008 , can you have a try above tf config? `azurerm_logic_app_trigger_http_request.test.callback_url` includes the token.

**Comment by weldpua2008** [comment]
@neil-yechenwei  looks like it wasn't there yet in Azurerm 2.70.0 https://registry.terraform.io/providers/hashicorp/azurerm/2.70.0/docs/resources/logic_app_trigger_http_request

**Comment by neil-yechenwei** [comment]
Terraform always recommends to use the latest azurerm provider. Currently, the latest version is v2.90.0 and it includes [`callback_url`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_trigger_http_request#callback_url) what you want.

**Comment by weldpua2008** [comment]
> Terraform always recommends to use the latest azurerm provider. Currently, the latest version is v2.90.0 and it includes [`callback_url`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_trigger_http_request#callback_url) what you want.

Yep, you are right. Just it's more obvious when there is a note that the field is exported since 2.73.0.

**Comment by mybayern1974** [comment]
@weldpua2008 per communication here I'd like to close this issue now. Feel free to suggest reopen it if there are further concerns.
