### ISSUE TITLE
azurerm_api_management_product subscription_required field should not be required

### ISSUE THREAD

**Issue by Victorp99** [hashicorp/terraform-provider-azurerm#14077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.10
AzureRM v2.84.0

### Affected Resource(s)

* `azurerm_api_management_product`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_api_management_product" "product" {
  product_id            = var.product_id
  resource_group_name   = var.resource_group_name
  api_management_name   = azurerm_api_management.apim.name
  display_name          = var.display_name
  subscription_required = true
  approval_required     = false
  published             = true
  subscriptions_limit   = 100
}
```

### Expected Behaviour

Based on the [Azure REST API](https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-12-01/product/create-or-update#request-body) and [ARM](https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/service/products?tabs=json) documentation, the `subscription_required` is not a required field for the `ApiManagement/service/products` resource. If a value is not provided, the default value should be `true`.

### Actual Behaviour

Terraform requires the user to provide a value for the `subscription_required` field when provisioning an `azurerm_api_management_product` resource.

### Steps to Reproduce

1. Add an `azurerm_api_management_product` resource to your Terraform configuration without the `subscription_required` field.
1. `terraform apply`

**Comment by katbyte** [comment]
closing as this will be fixed in the upcoming 3.0 release
