### ISSUE TITLE
azurerm_mssql_database - Error when trying to replace resource

### ISSUE THREAD

**Issue by ksmigiel** [hashicorp/terraform-provider-azurerm#14086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.10
on windows_amd64
\+ provider registry.terraform.io/hashicorp/azurerm v2.83.0
\+ provider registry.terraform.io/hashicorp/null v3.1.0
\+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_mssql_database`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "db" {
  for_each = { for t in var.tenants : t.name => t }

  name      = each.value.name
  server_id = azurerm_mssql_server.sql.id
  sku_name  = each.value.database_sku

  dynamic "long_term_retention_policy" {
    for_each = local.is_production ? [1] : []

    content {
      weekly_retention = "P1W"
      # Some weird setting for making it work...
      week_of_year = 1
    }
  }

  dynamic "short_term_retention_policy" {
    for_each = local.is_production ? [1] : []

    content {
      retention_days = 35
    }
  }
}
```

### Expected Behaviour

Database resource should be replaced without error.

### Actual Behaviour

```
Error: setting database threat detection policy for Database: (Name "name" / Server Name "serverName" / Resource Group "resourceGroup"):
sql.DatabaseSecurityAlertPoliciesClient#CreateOrUpdate:
Failure responding to request: StatusCode=404
 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'serverName/dbName' not found."
```

### Steps to Reproduce

1. `terraform apply -auto-approve -replace 'module.deployment["dev-eu"].azurerm_mssql_database.db["dbName"]'`

### Important Factoids

~~After adding empty block:~~

``` hcl
threat_detection_policy {}
```

~~it works as expected. But I do not specify threat_detection_policy at all and do not want to. In previous resource `azurerm_sql_database` it was not a problem.~~

Update: It seems that it doesn't work and looks like some racing/timing issue with requests being made to Azure Resource Manager API.

**Comment by Fresa** [comment]
I'm also experiencing this problem randomly. I think it relates to the ARM API being eventual consistent. I believe the issue is located here: https://github.com/hashicorp/terraform-provider-azurerm/blob/d515aca0ce9c7d3ee4a959a80a693e7c4ced8452/internal/services/mssql/mssql_database_resource.go#L387-L389

If getting 404 when creating the security alert policy as part of creating the database, the request should probably be retried as the database is being propagated to the ARM API instances and will appear any moment.
