### ISSUE TITLE
IoT-Hub downgrade tier doesn't work

### ISSUE THREAD

**Issue by Geens** [hashicorp/terraform-provider-azurerm#14088]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.10
hashicorp/azurerm v2.84.0

### Affected Resource(s)

* `azurerm_iothub`

### Terraform Configuration Files
```
resource "azurerm_iothub" "iothub" {
    name                        = var.name
    resource_group_name         = var.resource_group_name
    location                    = var.location
    # Define the Pricing Tier (SKU & Capacity)
    sku {
        name                    = "B1"
        capacity                = 6
    }
}
```
### Output
```
2021-11-08T13:28:46.8895722Z Error: creating/updating Iot Hub: (Name "iothub-d-01" / Resource Group "rg-d-01"): devices.IotHubResourceClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="Failed" Message="The async operation failed." InnerError={"unmarshalError":"json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string"} AdditionalInfo=[{"code":400013,"httpStatusCode":"BadRequest","message":"Cannot change sku from S1 to B1. If you contact a support representative please include this correlation identifier: <redacted>, timestamp: 2021-11-08 13:28:46Z, errorcode: IH400013."}]
2021-11-08T13:28:46.8897301Z 
2021-11-08T13:28:46.8898047Z   on iot-hub/main.tf line 4, in resource "azurerm_iothub" "iothub":
2021-11-08T13:28:46.8898471Z    4: resource "azurerm_iothub" "iothub" {
2021-11-08T13:28:46.8898643Z 
2021-11-08T13:28:46.8898769Z 
```
### Expected Behaviour

I tried to downgrade our IoT-Hub from the Standard S1 tier to the Basic B1 tier. Since this is not directly supported in Azure, I expected Terraform to remove the IoT-Hub resource and recreate it.

### Actual Behaviour

The resource was not modified. Terraform exited indicating the error.

### Steps to Reproduce

1. create azurerm_iothub resource with sku.name = "S1"
2. terraform apply
3. modify the resource changing sku.name to "B1"
4. terraform apply

**Comment by xiaxyi** [comment]
@Geens thanks for the comments, unfortunately, we do not support the downgrade of SKU and you may refer to the[ official doc](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-upgrade):
```
If you want to downgrade your IoT hub, you can remove units and reduce the size of the IoT hub but you cannot downgrade to a lower tier
```

I understand that you would like terraform to do the destruction and recreation of the resource based on the SKU downgrade, however, we may not be able to make the property as force-new since the upgrade of SKU from B1 to S1 is supported.

let me know if you have more questions

**Comment by mybayern1974** [comment]
@Geens , would you agree this issue could be closed if you think the suggestion provided by xiaxyi could answer your question?

**Comment by Geens** [comment]
Hi,

I asked because there are other services on Azure that do get recreated by Terraform when a parameter is changed in a way that can't be changed by Azure. If I understand correctly this would require different behavior between upgrading and downgrading the tier.

I have been able to manually remove the resource and have Terraform recreate it. So I guess the problem is manageable.

Thanks for looking into this. The issue can be closed. Apologies for the late reply.
