### ISSUE TITLE
Support for authenticating via Service Principal and Client Certificate Passing the encoded certificate bundle directly

### ISSUE THREAD

**Issue by kmpha** [hashicorp/terraform-provider-azurerm#14107]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to autenticate to Azure Passing the encoded certificate bundle directly

```
sh
$ export ARM_CLIENT_CERTIFICATE="$(base64 /path/to/my/client/certificate.pfx)"
```

### Potential Terraform Configuration

```
# sh
$ export ARM_CLIENT_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_CLIENT_CERTIFICATE="$(base64 /path/to/my/client/certificate.pfx)"
$ export ARM_CLIENT_CERTIFICATE_PASSWORD="Pa55w0rd123"
$ export ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000"
$ export ARM_TENANT_ID="10000000-2000-3000-4000-500000000000"
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @kmpha 

Thanks for opening this issue.

So that we can better understand this feature request, would you mind adding a little more context on the use-case/problem your looking to solve by passing the certificate inline, rather than by specifying the path to the certificate?

Thanks!

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.

**Comment by kmpha** [comment]
Hello,

@tombuildsstuff I have been requested to use certificate based identification. I am using Terraform Could for deployments and at the moment I don't know how to continue to use Terraform Cloud with current requirements. While investigating I found that  with azuread you can use certificates directly, and this would be good way to pass certificate to pipeline.

[Azuread certificate authentication.](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_client_certificate#environment-variables)
