### ISSUE TITLE
azurerm_cosmosdb_account forcing EnableMongo on DocumentDB

### ISSUE THREAD

**Issue by prateekmanasvi01** [hashicorp/terraform-provider-azurerm#14116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.83.0

### Affected Resource(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

resource "azurerm_cosmosdb_account" "dba-fca" {
  name                = "cosmosdba-test-dg-tbd"
  location            = "westeurope"
  resource_group_name = "rg-fca-we-dev"
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"
  enable_free_tier    = false
  enable_multiple_write_locations = false
  is_virtual_network_filter_enabled = true
  analytical_storage_enabled = false
  consistency_policy {
    consistency_level       = "Session"
  }

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"
  }

  /*capabilities {
    name = "EnableMongo"
  } */ 

  geo_location {
    location          = "westeurope"
    failover_priority = 0
  }

}

### Debug Output

azurerm_cosmosdb_account.dba-fca: Refreshing state... [id=/subscriptions/*****/resou╷
│ Error: capability EnableMongo must be enabled if MongoDBv3.4 is also enabled
│
│   with azurerm_cosmosdb_account.dba-fca,
│   on main.tf line 35, in resource "azurerm_cosmosdb_account" "dba-fca":
│   35: resource "azurerm_cosmosdb_account" "dba-fca" {

### Expected Behaviour

This was running fine but suddenly started giving this issue.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

If I add the capability EnableMongo on terraform it says it will destroy cosmoDB account which we cant.
If I try to update capability via azure cli  we get below

>az cosmosdb update --capabilities EnableMongo --name cosmosdba-test-dg-tbd --resource-group rg-fca-we-dev
BadRequestError: Operation failed with status: 'BadRequest'. Details: "EnableMongo capability is not allowed with kind=GlobalDocumentDB"

### References

* #0000

**Comment by xiaxyi** [comment]
@prateekmanasvi01, the property value `enableMongo` can't be set for the SQL API(kind: GlobalDocumentDB). The API was defined during the creation and cannot be modified.

As for the capability `MongoDBv3.4`,  Azure also set `enableMongo` if it's enabled. Considering the property is forceNew, to prevent the database from being destroyed, we need to throw an error, you can refer to the [PR#13757](https://github.com/hashicorp/terraform-provider-azurerm/pull/13757)
hope it helps!

**Comment by katbyte** [comment]
related to #14301
