### ISSUE TITLE
Error loading Role definition list

### ISSUE THREAD

**Issue by Kishanbhatk** [hashicorp/terraform-provider-azurerm#14117]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
   Terraform version - 0.13.3
   Azure provider version - 2.84.0

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "azurerm_subscription" "primary" {
}resource "azurerm_role_definition" "test_role" {
name = "test_role_1"
scope = data.azurerm_subscription.primary.id
permissions {
actions = []
not_actions = []
}
assignable_scopes = [
data.azurerm_subscription.primary.id,
]
}
data "azurerm_role_definition" "select_test_role" {
name = "test_role_1"
scope = data.azurerm_subscription.primary.id
depends_on = [
azurerm_role_definition.test_role,
]
}

```

### Debug Output

Error loading Role definition list

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
[](url)

**Comment by aristosvo** [comment]
Hi @Kishanbhatk! Thanks for raising this issue. 

Could you please elaborate a bit more on the issue at hand and show the complete error or debug log? I'm unable to reproduce it based on the configuration in this issue.

**Comment by Kishanbhatk** [comment]
Hi @aristosvo 

Error: Error loading Role Definition List: could not find role 'test_role_1'

  on ../module/main.tf line 20, in data "azurerm_role_definition" "select_test_role":
  20: data "azurerm_role_definition" "select_test_role" {

This is the error that I am getting while trying to run ,

I am using the resource as well as data source.
resource to create the roles and data source to retrieve the role information which I have created .
But I am unable to retrieve the information which I have created 

data "azurerm_subscription" "primary" {
}
resource "azurerm_role_definition" "test_role" {
name = "test_role_1"
scope = data.azurerm_subscription.primary.id
permissions {
actions = [
      "Microsoft.Compute/virtualMachines/*/read",
      "Microsoft.Network/networkInterfaces/*/read",
      "Microsoft.Network/publicIPAddresses/*/read",
      "Microsoft.Network/virtualNetworks/subnets/*/read"
    ]

not_actions = []
}
assignable_scopes = [
data.azurerm_subscription.primary.id,
]
}
data "azurerm_role_definition" "select_test_role" {
name = "test_role_1"
scope = data.azurerm_subscription.primary.id
depends_on = [
azurerm_role_definition.test_role,
]
}

**Comment by Kishanbhatk** [comment]
Hi @aristosvo  

It was previously working fine , now it is throwing this error . I think the creation of role is not getting reflected in tfstate file

**Comment by Kishanbhatk** [comment]
I had cross verified the role creation using the az role definition list -n test_role_1 , It is showing that the role has been created .
Even I am using the same assignable scope to retrieve the role which I have created . still it shows could not find role error.

**Comment by aristosvo** [comment]
I used your example, except that I changes your permissions slightly (removed `|`), and it worked perfect, see also the output:

```hcl
resource "azurerm_role_definition" "test_role" {
...
    actions = [
      "Microsoft.Compute/virtualMachines/read",
      "Microsoft.Network/networkInterfaces/read",
      "Microsoft.Network/publicIPAddresses/read",
      "Microsoft.Network/virtualNetworks/subnets/read"
    ]
...
}

output "permission" {
    value = data.azurerm_role_definition.select_test_role.permissions[0].actions
}
```

When running `terraform apply`:
```bash
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

permission = tolist([
  "Microsoft.Compute/virtualMachines/read",
  "Microsoft.Network/networkInterfaces/read",
  "Microsoft.Network/publicIPAddresses/read",
  "Microsoft.Network/virtualNetworks/subnets/read",
])
```

**Comment by Kishanbhatk** [comment]
Are you able to retrieve the role "test_role_1" which you have created using the data source ?

**Comment by Kishanbhatk** [comment]
module.role.azurerm_role_definition.test_role[0]: Creation complete after 3s [id=/subscriptions/572e564f-87ea-4269-aadb-XXXXX/providers/Microsoft.Authorization/roleDefinitions/ff1dcc60-0086-7f41-7038-366ce4cd4027|/subscriptions/572e564-XXXXXXXX]
module.role.data.azurerm_role_definition.select_test_role[0]: Reading...

Error: Error loading Role Definition List: could not find role 'test_role_123'

  on ../module/main.tf line 20, in data "azurerm_role_definition" "select_test_role":
  20: data "azurerm_role_definition" "select_test_role" {

Same error persists

**Comment by Kishanbhatk** [comment]
@aristosvo 

[Debug](https://gist.github.com/Kishanbhatk/818332c1aa4f147422733bebbbbe445a)
Uploaded the gist file can you please help or suggest a work around , not able to create

**Comment by Kishanbhatk** [comment]
Yeah Roles are visible in the portal ,

az role definition list -n test_role_302
[
{
"assignableScopes": [
"/subscriptions/572e564f-87ea-4269-aadb-a14739637a31"
],
"description": "",
"id": "/subscriptions/572e564f-87ea-4269-aadb-a14739637a31/providers/Microsoft.Authorization/roleDefinitions/0caeaac8-0fc1-edce-01a5-698d42fb8469",
"name": "0caeaac8-0fc1-edce-01a5-698d42fb8469",
"permissions": [
{
"actions": [
"Microsoft.Compute/virtualMachines/read",
"Microsoft.Network/networkInterfaces/read",
"Microsoft.Network/publicIPAddresses/read",
"Microsoft.Network/virtualNetworks/subnets/read"
],
"dataActions": [],
"notActions": [],
"notDataActions": []
}
],
"roleName": "test_role_302",
"roleType": "CustomRole",
"type": "Microsoft.Authorization/roleDefinitions"
}
]

**Comment by Kishanbhatk** [comment]
This behaviour is uncertain, sometimes it just executes and most of the time it throws this error previously it was working very fine , I dont know is it associated with Azure API ? 
We are currently using this to build infrastructure for our product dont know what exactly can we do for the issue .

**Comment by aristosvo** [comment]
Is there a reason why you use data source next to the resource itself? The resource exposes the same or more data.

**Comment by Kishanbhatk** [comment]
> Is there a reason why you use data source next to the resource itself? The resource exposes the same or more data.

Yeah actually we designed to create the roles based on some management variable , if it is true we are creating the roles and retrieving the data based on role name, if it is false we are only retrieving the data based on role name, here I have not shared the code but that is the basic idea behind why we are following up that practice.

**Comment by Kishanbhatk** [comment]
We are retrieving the role ids as outputs

**Comment by aristosvo** [comment]
I would advise to retrieve the role data only in case you didn't create it just before. The outputs you need can be filled based on the same logic as the decision whether to create it or not with data/resource data.

GitHub issues in this repository are only intended for bug reports and feature requests. Other issues will be closed. Please ask and answer questions through the [Terraform Azure Provider Community Forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure).

**Comment by Kishanbhatk** [comment]
@aristosvo Thank you !
