### ISSUE TITLE
Support for new Resource - Azure Container Apps

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#14122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide new resource for Azure Container Apps

### New or Affected Resource(s)

New resources
* azurerm_container_app_env
* azurerm_container_app

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app_env" "example" {
  name                   = "containerappenv"
  location               = "location"
  resource_group_name    = "resourcegroupname"
  logs_workspace_id      = "logsworkspaceclientid"
  logs-workspace-key     = "logsworkspaceclientsecret"
}

resource "azurerm_container_app" "example" {
  name                   = "containerapp"
  resource_group_name    = "resourcegroupname"
  environment            = "azurerm_container_app_env.example.environment"
  image                  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
  target_port            = 80
  ingress                = "external"
  query                  = "configuration.ingress.fqdn"
}
```

### References

* https://docs.microsoft.com/en-us/azure/container-apps/?ocid=AID3042118

**Comment by piizei** [comment]
The label service/app-service label is misplaced, as this is not an app-service based service (rather serverless AKS).

**Comment by tombuildsstuff** [comment]
@piizei it's part of the AppService Go SDK, which is why it has this label

**Comment by chaliy** [comment]
Hello team, could you please provide some light why this one is blocked? Is it azure-go-sdk missing something?

**Comment by piizei** [comment]
Container apps client was added to Go SDK recently: https://github.com/Azure/azure-sdk-for-go/commit/263cc58a4d93faa75e0c989e60813ee6951a2006#diff-cbe946f802c0fc4c71b389bba160000a987995c3d459da2a41cd834a828e3020

**Comment by kensykora** [comment]
If you're looking for some inspiration, I recently put together a bicep example of this. One thing to keep in mind is that the parameters are non-specific in the case of the scale rules, i think the documentation on this is still developing and was a gap when I was playing with it. I had to reverse engineer a bit.

https://github.com/kensykora/azure-container-apps-examples/blob/main/hello-azure-queue/infra.bicep#L63

**Comment by timoknapp** [comment]
Whats actually blocking this to be implemented? Is there already an open PR for this?

**Comment by piizei** [comment]
FYI its changing namespace, I assume this means changes to the Go SDK https://github.com/microsoft/azure-container-apps/issues/109 and might cause delay?

**Comment by KoenR3** [comment]
Is there a timeline on this?  We would like to make use of container apps in our architecture and are hitting a roadblock in using Terraform, unfortunately.

**Comment by error0327** [comment]
9 months later ... any update on this ?!

**Comment by sharebear** [comment]
Anyone really stuck on this should perhaps look into the AzAPI provider that was released last week https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azure-terrafy-and-azapi-terraform-provider-previews/ba-p/3270937

I've been meaning to play with it myself for exactly this use-case but other hobby projects got in the way over the easter holiday.

**Comment by piizei** [comment]
> Anyone really stuck on this should perhaps look into the AzAPI provider that was released last week https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azure-terrafy-and-azapi-terraform-provider-previews/ba-p/3270937
> 

Here is example how to do it with AzApi provider https://github.com/piizei/terraform-container-apps

**Comment by kkadiyam** [comment]
Hello, When i am trying to use this azapi provider it doesn't work, getting below error, Anything you can help here ?

Initializing Terraform Cloud...

Initializing provider plugins...

Finding hashicorp/azurerm versions matching ">= 2.0.0, ~> 2.0, >= 2.70.0"...
Finding latest version of hashicorp/namep...
Finding latest version of hashicorp/null...
Finding latest version of hashicorp/local...
Finding latest version of azure/azapi...
Installing hashicorp/azurerm v2.99.0...
Installed hashicorp/azurerm v2.99.0 (signed by HashiCorp)
Installing hashicorp/null v3.1.1...
Installed hashicorp/null v3.1.1 (signed by HashiCorp)
Installing hashicorp/local v2.2.2...
Installed hashicorp/local v2.2.2 (signed by HashiCorp)
Installing azure/azapi v0.1.1...
Installed azure/azapi v0.1.1 (signed by a HashiCorp partner, key ID
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/namep: provider registry registry.terraform.io does not have a
│ provider named registry.terraform.io/hashicorp/namep
│
│ All modules should specify their required_providers so that external
│ consumers will get the correct providers when using a module. To see which
│ modules are currently depending on hashicorp/namep, run the following
│ command:
│ terraform provider

**Comment by kkadiyam** [comment]
> > Anyone really stuck on this should perhaps look into the AzAPI provider that was released last week https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azure-terrafy-and-azapi-terraform-provider-previews/ba-p/3270937
> 
> Here is example how to do it with AzApi provider https://github.com/piizei/terraform-container-apps

I passed parent_id as module.resource_group.resource_group.id, but getting below error, Can we not use modules here ?

Error: `parent_id` is invalid, expect id of resource whose scope is [ResourceGroup], but got scope Unknown
with azapi_resource.container_app_environment
on main.tf line 85, in resource "azapi_resource" "container_app_environment":
resource "azapi_resource" "container_app_environment" {

**Comment by ctvanzandt42** [comment]
Is there any update on this? As container apps gets closer and closer to GA, it'd be great to have this support soon.

**Comment by waylew-lexis** [comment]
it is now GA, where is the Terraform? https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-general-availability/ba-p/3416885

**Comment by UsmanMohammad** [comment]
> it is now GA, where is the Terraform? https://techcommunity.microsoft.com/t5/apps-on-azure-blog/azure-container-apps-general-availability/ba-p/3416885

I don't see why it is marked as off-topic? This service is now GA and some insight into terraform's support for deploying would be appreciated.

**Comment by waylew-lexis** [comment]
Just because the resource can be Terraformed using AzApi provider, shouldn't delay its development in AzureRM.  if this is the new path then please let us know, as we have teams waiting to use this service.

**Comment by jackofallops** [comment]
By way of update, support for this is being actively worked on. The service has undergone significant change and improvement during the preview, as well as there having been some blocking issues in the API. There's a lot to cover to provide the resources required working as users would expect under Terraform, but rest assured we're working with the service team at Azure to get support added as soon as possible.

**Comment by nikuljain** [comment]
May we know an update , we are waiting to use it officially

**Comment by penfold** [comment]
Are you looking to support dapr in the initial version?

Thanks,
Paul

**Comment by danlambethskyport** [comment]
Any update on this?

**Comment by nikuljain** [comment]
Any Update ? , this is really important for us to get this going

**Comment by jackofallops** [comment]
Hi Folks - Just an update that there's still an outstanding issue with updates on the service side that is blocking us progressing support for this resource. We're working with the Service Team at Azure to get this resolved, but there's no ETA yet. As soon as we're unblocked we'll be picking this back up and getting support available as quickly as we can. Apologies for the delays and any frustration caused in the meantime, we know this is important to a lot of users and we want support as soon as we can too.

While I'm here:
@penfold - Dapr support is on my branch, but I'm not in a position to test it currently, if testing is successful, it should ship with the rest of this service.

**Comment by SonOfBytes** [comment]
> there's still an outstanding issue with updates on the service side that is blocking us progressing support for this resource. We're working with the Service Team at Azure to get this resolved

Hi @jackofallops - could you provide a brief explanation of the issue as I would like to present it back through our MS account management to help get this prioritised.

Thank you!

**Comment by simongottschlag** [comment]
@jackofallops I've been playing around with Container Apps and building a GitOps engine for it. In this work, I've used azapi terraform provider which has worked quite well - but there has been one issue that maybe can be solved with the "real" resources you are building for the azurerm provider.

The issue: If you are creating the vnet, subnet and managed environment in the same state, everything works as expected when applying. But when running destroy, the managed environment will be marked as removed before the separate reaource group is completely removed and it will be connected to the subnet, which will cause terraform to error. You have to wait a while (couple of minutes?) and then run destroy again for the vnet to be removed.

It would be amazing if the azurerm provider would keep track of the separate reaource group and not mark the destroy as completed until it's actually removed.

You can see my terraform code here (using azapi): https://github.com/XenitAB/azcagit/blob/main/terraform-module/platform.tf

**Comment by anrub** [comment]
are there any updates around this?  Is there a time range for this?

**Comment by simongottschlag** [comment]
> @simongottschlag - the managed environment deletion API was fixed recently to not mark the environment as removed until all resources used by it have been released/removed. With that fix the issue you have described should not be happening anymore.

Ah, that's awesome news! 👍

**Comment by ilmax** [comment]
@ruslany does this mean the issue that was holding back the terraform provider is also fixed?

**Comment by epomatti** [comment]
Label for this issue is not the correct one: `service/app-service`

**Comment by danlambethskyport** [comment]
Any idea when this will make its way into a release?

**Comment by jackofallops** [comment]
> Any idea when this will make its way into a release?

as soon as we possibly can - we're actively working with the service team over at Azure to get this supported! We appreciate your patience, please bear with us.

**Comment by camilosantana** [comment]
> please bear with us

what can we do as enterprise customers to upvote this on Azure's side?

**Comment by SandraAhlgrimm** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/pull/18008#issuecomment-1338287668 isn't it linked? can it be merged?

**Comment by jimmyville** [comment]
Curious if there's been an update?

**Comment by wgkesler** [comment]
This is a piece of great news we were all waiting for.

However, there is no support for the "zoneRedundant" property of managed environment in the new azurerm_container_app_environment resource.
When it will be possible to manage this property via Terraform Azure RM provider?

**Comment by Zizico2** [comment]
There's also no way to set scale rules. And azapi doesn't seem to be able to set them either. A quick `azapi_update_resource` doesn't do anything either.

**Comment by camilosantana** [comment]
> there is no support for the "zoneRedundant" property of managed environment in the new azurerm_container_app_environment resource.

> There's no way to set scale rules.

I think it best to file an issue for each of these and link them back here to make progress. This feature request is 🔐

**Comment by zioproto** [comment]
@wgkesler for `zone_redundant` please check #20538

**Comment by wetrocks** [comment]
> There's also no way to set scale rules. And azapi doesn't seem to be able to set them either. A quick `azapi_update_resource` doesn't do anything either.

You can set scale rules with azapi with a "scale" property in the template, like: 
`scale = {
          maxReplicas = 1
          minReplicas = 0
          rules = [
            {
              name = "alert-queue-msg"
              custom = {
                type = "azure-servicebus"
                metadata = {
                  queueName = azurerm_servicebus_queue.alert.name
                }
                auth = [
                  {
                    secretRef        = "sb-conn-str"
                    triggerParameter = "connection"
                  }
                ]
              }
            }
          ]
        }`
