### ISSUE TITLE
Unable to turn on MSI and create an azurerm_role_assignment to existing infrastructure

### ISSUE THREAD

**Issue by ilmax** [hashicorp/terraform-provider-azurerm#14139]
I'm seeing the same issue as #4532 I'm using an `azurerm_app_service` resource, current state is that the app exists but DOESN'T have MSI enabled, so my change is to add `  identity { type = "SystemAssigned" }` to the pre-existing app service and at the same time use the app service identity to create a role assignment

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/betr-io/mssql v0.2.2
+ provider registry.terraform.io/hashicorp/azuread v2.8.0
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/mongodb/mongodbatlas v1.0.2
```

### Affected Resource(s)

* `azurerm_app_service`
* `azurerm_app_service_slot`

### Terraform Configuration Files

# Before
```hcl
resource "azurerm_app_service" "web" {
  name                = "${var.prefix}-web-backend-${var.env}"
  location            = azurerm_resource_group.backend.location
  resource_group_name = azurerm_resource_group.backend.name
  app_service_plan_id = azurerm_app_service_plan.backend.id
  https_only          = true
}
```

# After
```hcl
resource "azurerm_app_service" "web" {
  name                = "${var.prefix}-web-backend-${var.env}"
  location            = azurerm_resource_group.backend.location
  resource_group_name = azurerm_resource_group.backend.name
  app_service_plan_id = azurerm_app_service_plan.backend.id
  https_only          = true
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "web_storage_table_contributor" {
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${azurerm_storage_account.storage.resource_group_name}/providers/Microsoft.Storage/storageAccounts/${azurerm_storage_account.storage.name}"
  role_definition_name = "Storage Table Data Contributor"
  principal_id         = azurerm_app_service.web.identity[0].principal_id
}
```

### Expected Behaviour

Enabling managed service identity on the app service and then creating the role assignment

### Actual Behaviour

terraform apply fails

### Steps to Reproduce

1. `terraform apply`

### References

* #4532 that has been marked as closed but I run into what apparently looks like exactly the same issue

**Comment by aristosvo** [comment]
Hi @ilmax! Thanks for raising this issue.

Previous issue as referenced appeared to be a [bug in Terraform Core](https://github.com/hashicorp/terraform/issues/25578) - and as this issue is of similar nature I would ask you to raise it over there in it's current form.

The ability to solve it from a provider perspective is limited and would require changes with bigger impact on the user than the current problem, although I'm aware of the hassle it gives.

As such I'm going to close this here.

Thanks!

**Comment by ilmax** [comment]
Hi @aristosvo, I saw that but found that the linked bug in terraform core appear to be solved, shall I open another one there?

**Comment by aristosvo** [comment]
Yes, I would do that with a reference to the old one and your current setup.

That should work 👍

**Comment by ilmax** [comment]
@aristosvo so I reported there and, from what I got, it looks like it's a provider issue, can you help me understand how to move forward? Thanks

**Comment by aristosvo** [comment]
Hi @ilmax!

I saw the issue response, but I don't get it completely as well how to fix it in the provider.

I'll take a quick look tomorrow if we can in some way prevent this value to evaluate to `Null` (but to `Unknown` instead) if the identity has changed for the plan. Worth the try, and likely a challenge: challenge accepted 👍🏽

**Comment by aristosvo** [comment]
Hi @ilmax!

I have discussed it with @tombuildsstuff as well, this is indeed unfortunately _not_ that easy to solve from our side. For now the best solution might be to do it the hacky way, but it is definitely not something that's ignored long term:
```hcl
resource "azurerm_app_service" "example" {
  name                = "example-app-service"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id
  https_only          = true

  // possibly enabled some time after creation
  identity {
    type = "SystemAssigned"
  }
}

// Solution 1: Requires double `apply`
resource "azurerm_role_assignment" "solution1" {
  count = try(azurerm_app_service.example.identity.0.principal_id, null) == null ? 0 : 1
  scope                = azurerm_resource_group.example.id
  role_definition_name = "Storage Table Data Contributor"
  principal_id         = azurerm_app_service.example.identity.0.principal_id
}

// Solution 2: Requires read permissions on AD
data "azuread_service_principal" "solution2" {
  display_name = azurerm_app_service.example.name
  depends_on   = [azurerm_app_service.example]
}

resource "azurerm_role_assignment" "solution2" {
  scope                = azurerm_resource_group.example.id
  role_definition_name = "Storage Table Data Contributor"
  principal_id         = data.azuread_service_principal.solution2.id
}
```

Hope this helps, would've really liked to solve it for you 💯

**Comment by ilmax** [comment]
Hey @aristosvo  Thank you so much for the suggestions , I was wondering if there's a way to track this and try to improve it
