### ISSUE TITLE
azurerm_frontdoor_rules_engine match_condition doesn't set correct operators and values and issue with variables

### ISSUE THREAD

**Issue by aimarjs** [hashicorp/terraform-provider-azurerm#14130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/aztfmod/azurecaf v1.2.6
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_frontdoor_rules_engine`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor_rules_engine" "geo_rule" {
  name                = "Georewrites"
  frontdoor_name      = azurerm_frontdoor.frontdoor.name
  resource_group_name = azurerm_frontdoor.frontdoor.resource_group_name

  rule {
    name     = "benlux"
    priority = 1

    match_condition {
      variable = "RemoteAddr"
      operator = "GeoMatch"
      value    = ["NL", "BE"]
    }

    match_condition {
      variable = "RequestURI"
      operator = "Equal"
      value    = ["https://frontdoorurl.azurefd.net"]
    }

    action {
      response_header {
        header_action_type = "Overwrite"
        header_name        = "location"
        value              = "/nl"
      }
    }
  }
}

```

### Expected Behaviour

On Azure, I expected to see that the Remote Address is set as GeoMatch on the rule and the request URL is set as https://frontdoorurl.azurefd.net

### Actual Behaviour

For some reason, it sets remote address as Geo Not Match, and it doesn't even change request path to remote URL
![image](https://user-images.githubusercontent.com/25065245/141147270-fe6b1d07-a3f4-4251-994e-61d5cb4fda26.png)

Also, if I'm trying to set request URL then sometimes variable should be RequestURL and sometimes RequestUri

![image](https://user-images.githubusercontent.com/25065245/141149194-64ebde17-b789-40c5-9d48-94f8116e0d31.png)

On Mac and Linux it breaks the thing since everything is case sensitive

Second attempt

![image](https://user-images.githubusercontent.com/25065245/141149564-df6b4581-2159-4e55-a342-049e454073e6.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ernout** [comment]
It seems that the operator 'GeoNotMatch' is not mentioned in the list of parameters in the rules sourcecode in terraform. Maybe this was a feature that was added later? 

https://github.com/hashicorp/terraform-provider-azurerm/blob/0a65b78cb3619fc7d1708e130f06c3f5d5e146d4/internal/services/frontdoor/frontdoor_rules_engine_rule.go

**Comment by aimarjs** [comment]
Any comment on this issue? Am I doing something wrong or there's is actually quite a nasty bug in the code?

**Comment by bubbletroubles** [comment]
It seems that `RequestURI` and `RequestUri` are specified inconsistently.

**Comment by rcskosir** [comment]
Thanks for opening this issue. There have been large changes to the azurerm_frontdoor resources as noted here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor. As such I am going to mark this issue closed. If this is still an issue with the 4.x version of the provider for the azurerm_cdn_frontdor_custom_domain resource please do let us know by opening a new issue, thanks!
