### ISSUE TITLE
Support for new AKS outbound settings: managedNATGateway and userAssignedNATGateway

### ISSUE THREAD

**Issue by MasterKolka** [hashicorp/terraform-provider-azurerm#14138]
Support for new AKS outbound settings: managedNATGateway and userAssignedNATGateway

https://docs.microsoft.com/en-us/azure/aks/nat-gateway

Looks like validation is broken for those types. kubernetes_cluster_resource.go line 496.
There're missing 
```
string(containerservice.OutboundTypeManagedNATGateway),
string(containerservice.OutboundTypeUserAssignedNATGateway),
```

**Comment by aristosvo** [comment]
Hi @MasterKolka! I'll take a quick look if we can fix this easily with our current API version, thanks!

I'll let you know how it goes :+1:

**Comment by MasterKolka** [comment]
@aristosvo Thanks! I've seen that constants for this new options were already added. They're just unused.

**Comment by MasterKolka** [comment]
@aristosvo  Will this fix be available in the next release?

**Comment by aristosvo** [comment]
@MasterKolka I've no idea. Tests are passing, but I'm not sure how quick it can be reviewed.

It's a bigger change than just 2 extra types and it is a preview feature, which may affect review times.
