### ISSUE TITLE
Existing mounted file share on Azure web app is not deleted

### ISSUE THREAD

**Issue by xaviermignot** [hashicorp/terraform-provider-azurerm#14162]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
$> tf version
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

https://gist.github.com/xaviermignot/bd304de5b7b62dbc60cb2ad50e4c9843

### Debug Output

I have created a gist with the second apply only, as the first one works as expected:
https://gist.github.com/xaviermignot/bfdbaaeda3aeed09742ac215d6d0fed5

### Panic Output

N/A

### Expected Behaviour

The mounted file share on the web app should have been deleted.

### Actual Behaviour

A change is detected by the plan, but after the apply the mounted file share is still here.  
It is still visible in the portal and returned by the `az webapp config storage-account list -n <WEB-APP-NAME> -g <RESOURCE-GROUP-NAME>` command.  
I tried to change the block like this: `storage_account = []` (as suggested [here](https://www.terraform.io/docs/language/attr-as-blocks.html)) but the syntax is not valid. I'm wondering if this requires some adaptation in the provider in order to work.

### Steps to Reproduce

1. Run `terraform apply` with the configuration "as is"
2. Comment the `storage_account` block in the `azurerm_app_service` resource
3. Run `terraform apply` again

### Important Factoids

Nothing fancy here, it's my first issue so don't hesitate to comment if you need further details or anything :)

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
