### ISSUE TITLE
azurerm_log_analytics_linked_storage_account following example usage results in error

### ISSUE THREAD

**Issue by keke8273** [hashicorp/terraform-provider-azurerm#14166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v1.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.78.0

### Affected Resource(s)

* `azurerm_log_analytics_linked_storage_account`

### Terraform Configuration Files

```hcl
resource azurerm_storage_account audit_log_storage {
   name                        = local.audit_log_storage_acct_name
   resource_group_name         = local.resource_group_name     
   location                    = var.location                  
   account_tier                = "Standard"
   account_replication_type    = "GRS"
}

resource "azurerm_log_analytics_workspace" audit_log_analytics_workspace { 
   name                      = local.audit_log_workspace_name
   resource_group_name       = local.resource_group_name
   location                  = var.location
   sku                       = "PerGB2018"
}
 
resource "azurerm_log_analytics_linked_storage_account" customlogs_linked_storage_account {
  data_source_type      = "customlogs"
  resource_group_name   = local.resource_group_name
  workspace_resource_id = azurerm_log_analytics_workspace.audit_log_analytics_workspace.id
   storage_account_ids   = [azurerm_storage_account.audit_log_storage.id]
 }
```

### Expected Behaviour

Azure logic analytic workspace linked to storage account

### Actual Behaviour

Error: ID was missing the `linkedStorageAccounts` element

### Steps to Reproduce

1. `terraform apply`

### References
Following the example usage in the follow document results in above error.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_linked_storage_account

**Comment by simoneightch** [comment]
This is affecting the configuration of a production enviroment, is there any sugested work arounds?

**Comment by IBera** [comment]
Hi all. The same issue here:

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/anschoewe/curl v0.1.4
+ provider registry.terraform.io/hashicorp/azurerm v2.88.0

Thanks and regards

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
