### ISSUE TITLE
WEBSITE_CONTENTSHARE being added to azurerm_function_app_slot on dedicated app service premium plan

### ISSUE THREAD

**Issue by michaelstephensonuk** [hashicorp/terraform-provider-azurerm#14167]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform = 0.15.5
azurerm v2.84.0  

### Affected Resource(s)

- azurerm_function_app_slot

### Terraform Configuration Files

```hcl

resource "azurerm_function_app_slot" "my_app" {
    function_app_name               = azurerm_function_app.my_app.name
    name                            = "staging"
    location                        = data.azurerm_resource_group.eai_resource_group.location
    resource_group_name             = data.azurerm_resource_group.eai_resource_group.name
    app_service_plan_id             = azurerm_app_service_plan.platform_appservice_plan.id
    storage_account_name            = azurerm_storage_account.platform_appservice_plan_functions.name
    storage_account_access_key      = azurerm_storage_account.platform_appservice_plan_functions.primary_access_key
    https_only		                = true
    version                         = "~3"

    site_config {    
        scm_type                 = "VSTSRM"
        ftps_state = "Disabled"
        ip_restriction = [
        ]
    }

    identity {
        type = "SystemAssigned"
    }

    app_settings = {
        "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.platform_appservice_plan_application_insights.instrumentation_key    
        "AzureWebJobsStorage" = azurerm_storage_account.platform_appservice_plan_functions.primary_connection_string
        "AzureWebJobs.Ping.Disabled" = "false"
        "WEBSITE_RUN_FROM_PACKAGE" = 1
        "FUNCTIONS_WORKER_RUNTIME" = "dotnet"
        "FUNCTIONS_EXTENSION_VERSION" = "~3"
        "AzureWebJobsSecretStorageType" = "files"
        "Test" = "Test"
        
    }

    lifecycle {
        ignore_changes = [
            app_settings["WEBSITE_RUN_FROM_PACKAGE"],
            app_settings["MSDEPLOY_RENAME_LOCKED_FILES"],         
            id
        ]
    }
}

resource "azurerm_function_app" "my_app" {
    name                            = "fa-${lower(var.general_prefix_lowercase)}-myapp-${lower(var.environment_name)}"
    location                        = data.azurerm_resource_group.eai_resource_group.location
    resource_group_name             = data.azurerm_resource_group.eai_resource_group.name
    app_service_plan_id             = azurerm_app_service_plan.platform_appservice_plan.id
    storage_account_name            = azurerm_storage_account.platform_appservice_plan_functions.name
    storage_account_access_key      = azurerm_storage_account.platform_appservice_plan_functions.primary_access_key
    https_only		                = true
    version                         = "~3"

    site_config {    
        scm_type                 = "VSTSRM"
        ftps_state = "Disabled"
        ip_restriction = [
        ]
    }

    identity {
        type = "SystemAssigned"
    }

    app_settings = {
        "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.platform_appservice_plan_application_insights.instrumentation_key    
        "AzureWebJobsStorage" = azurerm_storage_account.platform_appservice_plan_functions.primary_connection_string
        "AzureWebJobs.Ping.Disabled" = "false"
        "WEBSITE_RUN_FROM_PACKAGE" = 1
        "FUNCTIONS_WORKER_RUNTIME" = "dotnet"
        "FUNCTIONS_EXTENSION_VERSION" = "~3"
        "AzureWebJobsSecretStorageType" = "files"
        "Test" = "Test"
        
    }
 

    lifecycle {
        ignore_changes = [
            app_settings["WEBSITE_RUN_FROM_PACKAGE"],
            app_settings["MSDEPLOY_RENAME_LOCKED_FILES"],        
            id
        ]
    }
}

resource "azurerm_app_service_plan" "platform_appservice_plan" {
    name                = "asp-${lower(var.general_prefix_lowercase)}-apps-${lower(var.environment_name)}"
    location            = data.azurerm_resource_group.eai_resource_group.location
    resource_group_name = data.azurerm_resource_group.eai_resource_group.name
    kind                = "Windows"

    //If we use this sku we get the issue
    sku {
        tier = "PremiumV3"
        size = "P1v3"
    }

    //If we use this sku we dont get the issue
    //sku {
    //    tier = "Standard"
    //    size = "S1"
    //}

}


```

### Expected Behaviour

We want to deploy a Function App and a Function App Slot on a dedicated App Service Plan on the Premium SKU (see below sku) but not have the WEBSITE_CONTENTAZUREFILECONNECTIONSTRING or WEBSITE_CONTENTSHARE settings added to the slot because we are not using them and they are causing some problems for our private vnet integration in our solution.

sku {
        tier = "PremiumV3"
        size = "P1v3"
    }

### Actual Behaviour

We are deploying a function app which also has a function slot which lives on an Azure App Service Plan.  If we deploy run the deploy with terraform the function slot always ends up with the following settings being added to the slot app settings:

- WEBSITE_CONTENTAZUREFILECONNECTIONSTRING
- WEBSITE_CONTENTSHARE

Note that they are only added to the slot and are not added to the main function app

If we change the app service plan SKU to be a standard plan rather than premium plan then the 2 app settings are not added to the slot.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

We suspect the problem could be in code for the slot on the below link on line 683

https://github.com/hashicorp/terraform-provider-azurerm/blob/272bc09552972cbfd2eab613fc3610a78bdfe468/internal/services/web/function_app_slot_resource.go

I think it is implementing a workaround for consumption and elastic premium plans to manage those settings but the logic might catch the dedicated plan if its on a premium tier because its checking for the word "premium" and add the settings to that slot but they are not required if its a dedicated app service plan.

**Comment by traeddle** [comment]
This is causing issues for my team as well

**Comment by traeddle** [comment]
this started happening azurerm v2.68.0

**Comment by traeddle** [comment]
My workaround for this is to use v2.67 of the azure provider for function_app_slot

```
 azurerm_version="2.67.0"
  azurerm_type="linux_amd64" #"darwin_amd64" may need darwin if running on mac
  azurerm_file="terraform-provider-azurerm267_v${azurerm_version}"
  tf_file_mirror_dir="${HOME}/.terraform.d/plugins" 
  azurerm_path="${tf_file_mirror_dir}/registry.terraform.io/hashicorp/azurerm267/${azurerm_version}/${azurerm_type}"
  
  
  mkdir -p $azurerm_path
  curl -sLo_ "https://releases.hashicorp.com/terraform-provider-azurerm/${azurerm_version}/terraform-provider-azurerm_${azurerm_version}_${azurerm_type}.zip"
  unzip -p _ "terraform-provider-azurerm*" > "${azurerm_path}/${azurerm_file}"
  rm _
  chmod 755 "${azurerm_path}/${azurerm_file}"
```

```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "~> 2.81.0"
    }

    azurerm267 = {
      source = "hashicorp/azurerm267"
    }
    
  }
  required_version = "~> 1.0"
}

provider "azurerm" {
  subscription_id             = var.subscription_id
  tenant_id                   = var.tenant_id
  use_msi                     = true
  skip_provider_registration  = true
  features {
  }
}

provider "azurerm267" {
  subscription_id             = var.subscription_id
  tenant_id                   = var.tenant_id
  use_msi                     = true
  skip_provider_registration  = true
  features {
  }
}

resource "azurerm_function_app_slot" "deployment_slot" {
  provider = azurerm267
  ...
```

**Comment by cmendible** [comment]
Can confirm that with provider v2.93.1 it's not possible to set a custom value for WEBSITE_CONTENTSHARE which is a must in order to deploy Azure Functions with a Private Endpoint protected Storage Account.

**Comment by arpitcpanchal** [comment]
> Can confirm that with provider v2.93.1 it's not possible to set a custom value for WEBSITE_CONTENTSHARE which is a must in order to deploy Azure Functions with a Private Endpoint protected Storage Account.

@cmendible ,
I was trying to deploy function app with storage account backed by Private endpoint both file/blob and vnet integration (Elastic premium windows ASP) with the app settings as below
    WEBSITE_VNET_ROUTE_ALL         = "1"
    WEBSITE_CONTENTOVERVNET        = "1"

my understanding is that both WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE values are automatically parsed by the provider behind the scene (Based on the storage account name and access key, and content share as random 4 char appended to function app name). 

After the function app deployed, I looked at the run time and "Azure Functions runtime is unreachable". From further look at the storage account, it seems that it hasn't got any file share and containers created, during the function app deployment.

Do you know if the provider creates the file share and container during the function app deployment? As unless they are in place the runtime will not be available for function app. 

I checked the https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.web/function-app-storage-private-endpoints, and ARM deployment does that.

**Comment by cmendible** [comment]
@arpitcpanchal 

Issue is that in the private endpoint use case, the content share must exists before the function is deployed or you get the "unreachable" runtime error. That is why `WEBSITE_CONTENTSHARE` if present **must** be respected by the provider.

This problem is also present in the beta resources: `azurerm_windows_function_app` and `azurerm_linux_function_app`

**Comment by arpitcpanchal** [comment]
@cmendible thanks, that explains it. That means it needs a fix for it in provider.

@michaelstephensonuk, it's been while waiting for this fix on this issue. Can you please assist prioritising this one? 
Without this feature it is impossible to deploy function app with storage account backed by private endpoint.

**Comment by danielrobinson95** [comment]
@arpitcpanchal @cmendible any update?

**Comment by arpitcpanchal** [comment]
@cmendible, 
Tested this today, with azurerm 3.0.1 with new function app resource `azurerm_windows_function_app`.
The `WEBSITE_CONTENTSHARE` value is honoured, if defined in APP_SETTINGS. However the deployment is not successful, still has the "Azure Functions runtime is unreachable".
Further, check implies that the containers for the `azure-webjobs-hosts` and `azure-webjobs-secrets` are not created part of the function app deployment, which could be the reason for the runtime error.

@koikonom - can this be prioritised please?

**Comment by fgarcia-cnb** [comment]
we definitely need the option to not use the WEBSITE_CONTENTSHARE related app config settings. In v2.68 of the provider, the slot would connect to storage via the standard AzureWebJobsStorage endpoint and create a blob folder. In later proviers, it uses the file share endpoint and created a file share instead, which doesnt work with private endpoint. When i deploy, ive had to manually/temporarily "allow all networks" on the storage for it to work. I have to do the same for swapping slots

**Comment by arpitcpanchal** [comment]
Tested new function app resource released in v3.0.1 and it seemed to work fine with host storage account behind private endpoint. 
As @cmendible mentioned, I had pre-stage file share and provided share name in app settings.

**Comment by fgarcia-cnb** [comment]
@arpitcpanchal are you doing an app service or app service slot? i noticed the new provider allows passing a shanre name in to the app service not but the slot.

terraform auto generates the WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING on fnapp slot. you cant specify the share name. We had to do something similar for logic app standard where we precreated the share, but that accepts a storage file share name parameter. function app slots do not

that said, it looks like the new slot resource does have `content_share_force_disabled`, which could possibly work around these issues. too bad its a major version upgrade

**Comment by arpitcpanchal** [comment]
@favoretti 
I am using azurerm_windows_function_app resource, which now respects WEBSITE_CONTENTSHARE specified in app settings.
But true, major upgrade for just this is fair bit of work.

**Comment by fgarcia-cnb** [comment]
yea and youre using the app resource, not the slot resource. the slot is the problem

**Comment by xiaxyi** [comment]
Hey guys, the `WEBSITE_CONTENTSHARE` must be specified to a predefined file share according to the [docs](There are scenarios where you must set the WEBSITE_CONTENTSHARE value to a predefined share, such as when you [use a secured storage account in a virtual network](https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network). In this case, you must set a unique share name for the main function app and the app for each deployment slot.):
_There are scenarios where you must set the WEBSITE_CONTENTSHARE value to a predefined share, such as when you [use a secured storage account in a virtual network](https://docs.microsoft.com/en-us/azure/azure-functions/configure-networking-how-to#restrict-your-storage-account-to-a-virtual-network). In this case, you must set a unique share name for the main function app and the app for each deployment slot._

I made some changes to the provider to not generate a value for this key when `WEBSITE_CONTENTOVERVNET` presents. For those function app created before this pr, you may need to create the file share using the name which generated by Terraform manually. 

Hope it makes sense to you, feel free to let me know if you have any more concerns or questions

**Comment by Mouflok** [comment]
Hi

I test and it"s OK for Function App. But how to handle this issue with slot ?
