### ISSUE TITLE
Support for route propagation across virtual WAN with labels

### ISSUE THREAD

**Issue by osten33** [hashicorp/terraform-provider-azurerm#14180]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using the default route table of a virtual hub for branches and you have multiple virtual hubs across virtual WAN it is possible to propagate the routes of branches across all virtual hubs based of labels. This is enabled in portal when you edit the default route table after it has been created with the option "Propagate routes from all branch connections to these labels across virtual WAN". Without this the global connectivity does not work properly. 

Currently it does not look like terraform can modify the default route table, so not sure where this config should be placed, but in virtual hub potentially. If it is not possible to modify default route table then this option should be made available for custom route tables so the feature is achievable in some way as it is important. 

### New or Affected Resource(s)

* azurerm_virtual_hub
* azurerm_virtual_hub_route_table

### Potential Terraform Configuration

```hcl

resource "azurerm_virtual_hub" "example" {
  name                = "virtual-hub-example"
  resource_group_name = var.resource_group_name
  location            = var.hub_location
  virtual_wan_id      = var.vwan_id
  address_prefix      = var.hub_address_prefix
  branch_route_propagation_labels = ["label1","label2"]
```

### References
https://docs.microsoft.com/en-us/azure/virtual-wan/about-virtual-hub-routing

* #0000

**Comment by oWretch** [comment]
You can modify the default route table in Terraform - but you have to import it into state manually. Not sure if there is appetite to allow an auto-import of the default route table, or if extension of the `azurerm_virtual_hub` resource is the best way to go for doing this.

**Comment by osten33** [comment]
This configuration option is crucial if you have virtual WAN as the propagation simply doesn't work without it. If it won't be possible to have in default route table then it should be possible to set on a custom route table that you create.

**Comment by steve-down** [comment]
All of this makes sense with respect to the Default route table - how does one configure a virtual hub connection to propagate to the "None" route table? The hub doesn't surface a route table ID for id, and all connections are propagating to Default - do I just choose a _label_ of "None" and an empty `route_table_ids` list in my `propagated_route_table` block?

**Comment by traittinen** [comment]
> All of this makes sense with respect to the Default route table - how does one configure a virtual hub connection to propagate to the "None" route table? The hub doesn't surface a route table ID for id, and all connections are propagating to Default - do I just choose a _label_ of "None" and an empty `route_table_ids` list in my `propagated_route_table` block?

This seems to work as route table ID ends with the route table name:
`  
routing {
    propagated_route_table {
      labels = ["none"]
      route_table_ids = [replace(azurerm_virtual_hub.example.default_route_table_id, "defaultRouteTable", "noneRouteTable")]
    }    
  }
`

**Comment by WaitingForGuacamole** [comment]
> This seems to work as route table ID ends with the route table name:
> 
> ```terraform
>  routing {
>     propagated_route_table {
>       labels = ["none"]
>       route_table_ids = [replace(azurerm_virtual_hub.example.default_route_table_id, "defaultRouteTable", "noneRouteTable")]
>     }    
>   }
> ```

This was extremely useful (replacing default with none to force propagation to the None route table). Just specifying a "none" label and nothing else didn't associate it. Since we're hosting multiple environments within the hub, and we have stringent security requirements for them, I don't want anything propagating on its own to any other route table (because those propagations are often direct). Rather, I want each spoke to add its own entries to the route tables for the environments it needs to support. This should give me more control over that.

I'm hoping (will need to validate after a hub reset) that this fix will prevent the strage behavior where, when I didn't specifically advertise my spoke to other route tables, that spoke would appear in the Default route table with an invalid next hop of an ExpressRouteGateway.

**Comment by catriona-m** [comment]
Hi @osten33, I've had a look into this issue and currently it doesn't appear possible to add the propagation labels due to a limitation in the Azure API. I have now raised an issue and hopefully we can revisit this when it is addressed: https://github.com/Azure/azure-rest-api-specs/issues/21136. Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
Below is a follow up issue from the one linked above by @catriona-m, in which it is clarified that there is no API support. 
https://github.com/Azure/azure-rest-api-specs/issues/22200
