### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by PierreDony** [hashicorp/terraform-provider-azurerm#14194]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000
Can this function be enabled in terraform when deploying an azure Cosmos DB?

 resource "azurerm_cosmosdb_account" "cosmos_account" {
     azure_portal_access = true / false
}

**Comment by aristosvo** [comment]
Hi @PierreDony! This is already possible, but it is a bit hidden, and can be based on the [docs](https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-configure-firewall#allow-requests-from-the-azure-portal):

> <h3 id="allow-requests-from-the-azure-portal" class="heading-anchor" style="font-style: normal; font-variant-caps: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: inherit; margin: 30px 0px 18px -1.875rem; padding: 0px 0px 0px 1.875rem; font-size: clamp(1.3125rem, 15.4736842105px + 1.1513157895vw, 1.75rem); font-weight: 600; outline-color: inherit; line-height: 1.3; position: relative; caret-color: rgb(230, 230, 230); color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;">Allow requests from the Azure portal</h3><p style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: inherit; margin: 1rem 0px 0px; padding: 0px; outline-color: inherit; word-wrap: break-word; caret-color: rgb(230, 230, 230); color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;">When you enable an IP access control policy programmatically, you need to add the IP address for the Azure portal to the<span class="Apple-converted-space"> </span><strong style="box-sizing: inherit; font-weight: 600; outline-color: inherit;">ipRangeFilter</strong><span class="Apple-converted-space"> </span>property to maintain access. The portal IP addresses are:</p><div class="table-scroll-wrapper has-inner-focus" tabindex="0" role="group" aria-label="Horizontally scrollable data" style="font-size: 16px; font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; box-sizing: inherit; outline-color: inherit; overflow: auto hidden; caret-color: rgb(230, 230, 230); color: rgb(230, 230, 230); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif;">

Region | IP address
-- | --
Germany | 51.4.229.218
China | 139.217.8.252
US Gov | 52.244.48.71
All other regions | 104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26

</div>

An example configuration can be found [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/examples/cosmos-db/failover/main.tf), this is what you are looking for:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = var.location
}

resource "azurerm_cosmosdb_account" "example" {
  name                      = "${var.prefix}-cosmosdb"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  offer_type                = "Standard"
  kind                      = "GlobalDocumentDB"
  enable_automatic_failover = true

  // set ip_range_filter to allow Azure Services (0.0.0.0) and Azure Portal (104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26).
  ip_range_filter = "0.0.0.0,104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26"
}
```
