### ISSUE TITLE
Adding Fsv2 family to azurerm_mssql_elasticpool sku

### ISSUE THREAD

**Issue by geremy42** [hashicorp/terraform-provider-azurerm#14203]
### Terraform (and AzureRM Provider) Version
    azurerm 2.85.0
### Affected Resource(s)
    azurerm_mssql_elasticpool

### Terraform Configuration Files

```
sku {
   name    = "GP_FSv2"
   tier        = "GeneralPurpose"
   capacity = 8
}
```

### Debug Output
![image](https://user-images.githubusercontent.com/39192567/141976925-2552c076-7d73-47c7-83fa-8721ed20d488.png)

### Expected Behaviour

SQL Elastic Pool can be provisioned on General Purpose FSv2 series with sku family value equals to "Fsv2"
### Steps to Reproduce

1.     Configure the sku for azurerm_mssql_elasticpool as per the code above.
2.     Run terraform plan

**Comment by aristosvo** [comment]
Hi @geremy42! Thanks for this issue.

I believe the `family` option is already available in this resource according to the docs [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_elasticpool#family), which can contain `Gen4` and `Gen5`. We cannot fill this in for you, as this differs per SKU whether this is necessary or not iirc.

Could you retry it with the needed `family` attribute specified?

**Comment by geremy42** [comment]
Already tried to specify 'Gen4' as family value without any success
![image](https://user-images.githubusercontent.com/39192567/142373953-2ce63d32-edda-4f29-a28f-d6b7ab2b2510.png)

**Comment by aristosvo** [comment]
@geremy42 Sorry, I think I misunderstood you. The PR is filed (#14250), tests are passing!
