### ISSUE TITLE
azurerm_security_center_workspace scope error

### ISSUE THREAD

**Issue by Jared-Wolff23** [hashicorp/terraform-provider-azurerm#14216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0

### Affected Resource(s)

azurerm_security_center_workspace

### Terraform Configuration Files

resource "azurerm_security_center_workspace" "example" {
  scope        = "/subscriptions/<subscription_id>"
  workspace_id = <log analytics workspace id>
}
### Expected Behaviour

It should create a security center workspace for the subscription.

### Actual Behaviour

It gives this error:

azurerm_security_center_workspace.ppeob: Creating...
╷
│ Error: Creating Security Center Workspace: security.WorkspaceSettingsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidInput" Message="Invalid scope was provided - scope '/subscriptions/<subscription id>'. Please provide the following scope: '/subscriptions/{subscriptionId}'"
│
│   with azurerm_security_center_workspace.ppeob,
│   on main.tf line 55, in resource "azurerm_security_center_workspace" "example":
│   55: resource "azurerm_security_center_workspace" "example" {

### Steps to Reproduce

terraform plan
terraform apply

**Comment by ms-henglu** [comment]
Hi @Jared-Wolff23 ,

I've taken a look, it seems that the scope value is invalid. Would you please try the following configuration? It will fetch subscription id by `data.azurerm_client_config.current.subscription_id`.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "henglu-rg2"
  location = "west europe"
}


resource "azurerm_log_analytics_workspace" "test" {
  name                = "acctesthhenglu-1"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
}

data "azurerm_client_config" "current" {}

resource "azurerm_security_center_workspace" "test" {
  scope        = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  workspace_id = azurerm_log_analytics_workspace.test.id
}
```

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
