### ISSUE TITLE
Kusto Cluster does not apply empty trusted external tenants list.

### ISSUE THREAD

**Issue by jmswick** [hashicorp/terraform-provider-azurerm#14234]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```text
Terraform v1.0.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.8.0
+ provider registry.terraform.io/hashicorp/azurerm v2.76.0
```

### Affected Resource(s)

* `azurerm_kusto_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kusto_cluster" "adx" {
  name                = "${local.region_abbreviation}${local.business_unit}${local.product}${local.environment}adx"
  resource_group_name = azurerm_resource_group.resource_group_adx.name
  location            = azurerm_resource_group.resource_group_adx.location

  optimized_auto_scale {
    maximum_instances = var.adx_maximum_instances
    minimum_instances = var.adx_minimum_instances
  }
  sku {
    name     = var.adx_sku_name
    capacity = var.adx_sku_capacity
  }

  trusted_external_tenants = []
  virtual_network_configuration {
    subnet_id                    = azurerm_subnet.adx_snet.id
    engine_public_ip_id          = azurerm_public_ip.adx_engine.id
    data_management_public_ip_id = azurerm_public_ip.adx_ingestion.id
  }

  tags = local.common_tags
}
```

### Expected Behaviour

When creating the Azure Data Explorer cluster (Kusto Cluster), we expect the cluster settings for tenant permissions to be "My tenant only" when passing an empty list for `trusted_external_tenants`.

### Actual Behaviour

The cluster is created with a `trusted_external_tenants` list of `"*"` (All Tenants) instead of an empty list (My Tenant Only).  Additional terraform plan runs show that the `"*"` entry will be removed, but the change does not get applied in Azure.

### Steps to Reproduce

1. Create a Kusto Cluster (Data Explorer) resource definition with `trusted_external_tenants = []` as an attribute
2. Apply the change
3. Observe in the Azure portal that the Data Explorer Cluster tenant permissions is set to "All Tenants"
4. Run `terraform plan`, observe that the `trusted_external_tenants` attribute will be updated.
5. Run `terraform apply`, and observe that while it says the resource is updated, the change does not occur on the cluster.

**Comment by aristosvo** [comment]
Hi @jmswick, thanks for reporting this issue!

I'm not that familiar with this resource, but based on a quick look at the API I'd expect that you'd need to add your own tenant explicitly if you'd want 'My Tenant Only' set. An empty array is not accepted, default setting is `*`.

It would be interesting to see what happens if you'd add your tenant id to the list like this:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG"
  location = "westeurope"
}

data "azurerm_client_config" "current" {
}

resource "azurerm_kusto_cluster" "test" {
  name                = "acctestkc"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }

  trusted_external_tenants = [data.azurerm_client_config.current.tenant_id]
}
```

Happy to hear your experiences, I'm currently testing it myself as well. If this is the way to go, I'll add a testcase and docs to explain the details of this setting.

**Comment by jmswick** [comment]
Thank you for looking into this.  I forgot to add that when I changed the created Data Explorer Cluster to "My Tenant Only" in the Azure portal, the updated state for trusted external tenants was an empty list.
