### ISSUE TITLE
Issue with latest changes to container_registry.go file

### ISSUE THREAD

**Issue by Makovec** [hashicorp/terraform-provider-azurerm#14245]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0
```

### Affected Resource(s)

* `azurerm_container_registry`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "some-RG"
  location = "West Europe"
}

resource "azurerm_container_registry" "acr" {
  name                = "acrdm1"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "Premium"
  admin_enabled       = false
  georeplications = [
    {
      location                  = "East US"
      zone_redundancy_enabled   = true
      tags = {
        Description = "Replica registry"
      }
    },
    {
      location                  = "West US"
      zone_redundancy_enabled   = true
      tags = {
        Description = "Replica registry"
      }
  }]
}

```

### Debug Output
Just short important part:

```
Error: Incorrect attribute value type

  on acr.tf line 23, in resource "azurerm_container_registry" "acr":
  23:   georeplications = [
  24:     {
  25:       location                  = "East US"
  26:       zone_redundancy_enabled   = true
  27:       tags = {
  29:         Description = "Replica registry"
  30:       }
  31:     },
  32:     {
  33:       location                  = "West US"
  34:       zone_redundancy_enabled   = true
  35:       tags = {
  37:         Description = "Replica registry"
  38:       }
  39:     }
  40:   ]

Inappropriate value for attribute "georeplications": element 0: attribute
"regional_endpoint_enabled" is required.
2021-11-18T12:14:23.220+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

### Expected Behaviour

Provider should create ACR with two georeplicas.

### Actual Behaviour

Error is raised - see above

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

When running with just one georeplica, it works. But when added two or more, error is raised.
When I add `regional_endpoint_enabled = false` manually to both replicat, it creates it correctly.

### References

I think it is related to missing default value here: https://github.com/hashicorp/terraform-provider-azurerm/blob/d12b89339743503b80d4fcf2b0988ff1b0ab709c/internal/services/containers/container_registry_resource.go#L119

**Comment by magodo** [comment]
@Makovec The expected syntax of the configuration is as below:

```hcl
  georeplications {
    location                  = "East US"
    zone_redundancy_enabled   = true
    tags = {
      Description = "Replica registry"
    }
  }

  georeplications {
    location                  = "West US"
    zone_redundancy_enabled   = true
    tags = {
      Description = "Replica registry"
    }
  }
```

The attribute-like assignment is only used when you want to zero the `georeplications` block, i.e. `georeplications = []`.

As this is an unexpected syntax used in the HCL rather than a provider bug. I'm gonna close this issue now. Please feel free to reopen it if it didn't solve your problem.

**Comment by slime-uk** [comment]
I’m experiencing the same error. Following the document with latest provider results in the same error. 

From the above replies, it suggests the documentation is wrong and you only need [] around georeplications regions when zero out. To confirm please, if I have one replica only, or multiples I actually repeat the definition with {} and no [] and I should not need to include the regional_endpoint_enabled at all within the georeplications block(s) at all? Do I need to include regional_endpoint_enabled higher up at all too? As I say, I find the documentation on these options confusing resulting in the same error and lots of head scratching. 

Thank you.

**Comment by slime-uk** [comment]
![Uploading F00E0706-C64F-4C0A-B390-DC20D2D5797E.jpeg…]()

**Comment by slime-uk** [comment]
![49734D5A-0F5D-471D-B434-1D2EAA551A8E](https://user-images.githubusercontent.com/15941907/144492687-1c4da6fd-387a-49a9-a939-2e216d8bc326.jpeg)

**Comment by magodo** [comment]
@Makovec Yes, you should repeat the block if have multiple regions for replication. The `regional_endpoint_enabled` is only needed to be specified once at the root level. I've submit a PR to fix the incorrect example in the doc. Thanks!

**Comment by salatamartin** [comment]
We actually need a parametrized number of georeplications. We have a variable which describes these replications. We then need to construct the georeplication blocks from this variable. Hence the explicit use of []:
```
variable "georeplications" {
  type = set(object({
    location                = string
    zone_redundancy_enabled = bool
  }))
  default     = [{
    location                = "Australia East"
    zone_redundancy_enabled = false
  }]
  description = "A set of geo-replication zones used for this ACR"
}

resource "azurerm_container_registry" "acr" {
  ...

  georeplications = [
    for zone in var.georeplications : {
      location                = zone.location
      zone_redundancy_enabled = zone.zone_redundancy_enable
    }
  ]
  ...
}
```

Is this really unexpected syntax? Is there a different way how this can be set up?

**Comment by slime-uk** [comment]
Update: I've now changed my `georeplications {}` block as described to use `{ }` and removed `[ ]` and added `regional_endpoint_enabled = true` to the root.  It now errors saying this `regional_endpoint_enabled is not expected here`.  Provider version 2.87 and terraform v1.0.10 (just FYI).

Error:
```
regional_endpoint_enabled 		= true
An argument named "regional_endpoint_enabled" is not expected here.
```

**Comment by magodo** [comment]
@slime-uk Sorry for the wrong information, the `regional_endpoint_enabled` goes inside the `georeplications`.

@salatamartin For your case, you might want to use [dynamic block](https://www.terraform.io/docs/language/expressions/dynamic-blocks.html) instead, in which case you can use the block syntax. The assignment syntax is only needed when you want to explicitly zero the `georeplications`.

**Comment by slime-uk** [comment]
@magodo - thanks - another PR against the docs then maybe is needed?

Thanks!
