### ISSUE TITLE
Support for alert_rule_template_version in the azurerm_sentinel_alert_rule_scheduled resource

### ISSUE THREAD

**Issue by Korving-F** [hashicorp/terraform-provider-azurerm#14244]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is a missing field which can help indicate updates to template-based rules. Adding an `alert_rule_template_version` field would solve that. This relates to the existing `alert_rule_template_guid` field.

### New or Affected Resource(s)

* azurerm_sentinel_alert_rule_scheduled

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  name                       = "example"
  log_analytics_workspace_id = azurerm_log_analytics_solution.example.workspace_resource_id
  display_name               = "example"
  severity                   = "High"
  alert_rule_template_guid = aaaa-bbbb-cccc-dddd
  alert_rule_template_version = 1.0.0
  query                      = <<QUERY
AzureActivity |
  take 10
QUERY
}
```

### References

* #9712

**Comment by magodo** [comment]
@Korving-F After looking through the [Swagger spec](https://github.com/magodo/azure-rest-api-specs/blob/953c26995780b043102a8941a07e8175ffad4428/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-03-01-preview/AlertRules.json#L1322) of the sentinel alert rule, there seems no such property for template version, would you please confirm?

**Comment by Korving-F** [comment]
@magodo One can see it defined in [2021-09-01-preview](https://github.com/magodo/azure-rest-api-specs/blob/953c26995780b043102a8941a07e8175ffad4428/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-09-01-preview/AlertRules.json) as **templateVersion** under **QueryBasedAlertRuleProperties.**
Thanks for the follow up! ^_^
