### ISSUE TITLE
Relay SDK Upgrade causes failure parsing EventHub AuthorizationRules

### ISSUE THREAD

**Issue by vsabella** [hashicorp/terraform-provider-azurerm#14269]
#14153

https://github.com/hashicorp/terraform-provider-azurerm/pull/14153 

When moving to 2.86.0 we now get the following error when attempting to use Microsoft Diagnostics Accounts with EventHub

```
Error: parsing "/subscriptions/<sub>/resourceGroups/<rg>/Microsoft.EventHub/namespaces/<mynamespace>/authorizationRules/telemetry-send": parsing segment "microsoftRelay": expected the segment "Microsoft.EventHub" to be "Microsoft.Relay"
```

This occurred recently with 2.86.0 and looks to be related to the above pull request.

This is breaking on Azure Commercial and Azure Us Government

**Comment by fcatacut** [comment]
Duplicate of #14267

**Comment by tombuildsstuff** [comment]
Duplicate of #14267 - thanks @fcatacut
