### ISSUE TITLE
r/eventhub_namespace_authorization_rule: missing state migration

### ISSUE THREAD

**Issue by boris-tarasov-maersk** [hashicorp/terraform-provider-azurerm#14266]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
azurerm version 2.86.0
tested with terraform version 1.0 and 0.15

### Affected Resource(s)

* `azurerm_eventhub_namespace_authorization_rule`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error 1 (@tombuildsstuff: this is tracked in #14267)
` Error: parsing "/subscriptions/..../resourceGroups/..../Microsoft.EventHub/namespaces/.../AuthorizationRules/DataWriter": parsing segment "microsoftRelay": expected the segment "Microsoft.EventHub" to be "Microsoft.Relay"`

Error 2
`Error: parsing "/subscriptions/.../resourceGroups/.../providers/Microsoft.EventHub/namespaces/.../eventhubs/.../consumergroups/dashboard": parsing segment "staticConsumerGroups": expected the segment "consumergroups" to be "consumerGroups"`

### Steps to Reproduce

Rerun a pipline with existing eventhub or azurerm_eventhub_namespace_authorization_rule after upgdate from 2.85 to 2.86

1. `terraform apply`

### References

* #0000

**Comment by anderius** [comment]
Probably the same as https://github.com/hashicorp/terraform-provider-azurerm/issues/14267.

**Comment by tombuildsstuff** [comment]
This is missing a state migration

**Comment by no-weller** [comment]
Hello everyone,

first of all, thank you for providing a fix in the upcoming release for the second issue. I've just one short question: has anyone a workaround he can share till we wait for the next release? We'd downgraded the azurerm version to 2.85 as a quick fix.

Kind regards
