### ISSUE TITLE
azurerm_monitor_diagnostic_setting with eventhub destination fails on 2.86.0

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#14267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.31
+ provider.azurerm v2.86.0

### Affected Resource(s)

* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "eastus2"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "testnsn"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Basic"
  capacity            = 1
}

resource "azurerm_eventhub" "test" {
  name                = "test"
  namespace_name      = azurerm_eventhub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name
  partition_count     = 2
  message_retention   = 1
}

resource "azurerm_eventhub_namespace_authorization_rule" "test" {
  name                = "test"
  namespace_name      = azurerm_eventhub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name
  listen              = true
  send                = true
  manage              = true
}

resource "azurerm_monitor_diagnostic_setting" "test" {
  name                           = "Metrics"
  target_resource_id             = azurerm_eventhub_namespace.test.id
  eventhub_authorization_rule_id = azurerm_eventhub_namespace_authorization_rule.test.id
  eventhub_name                  = azurerm_eventhub.test.name

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }
}
```

### Expected Behaviour

No errors 
### Actual Behaviour

```hcl
...
Error: parsing "/subscriptions/<subscription>/resourceGroups/test/providers/Microsoft.EventHub/namespaces/testnsn/authorizationRules/test": parsing segment "microsoftRelay": expected the segment "Microsoft.EventHub" to be "Microsoft.Relay"

  on main.tf line 37, in resource "azurerm_monitor_diagnostic_setting" "test":
  37:   eventhub_authorization_rule_id = azurerm_eventhub_namespace_authorization_rule.test.id
...
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by anderius** [comment]
I would guess this is related to https://github.com/hashicorp/terraform-provider-azurerm/pull/14153.

**Comment by tombuildsstuff** [comment]
hi @t3mi 

Thanks for opening this issue.

I've tagged this as both an enhancement (since we should support accepting a Relay Authorisation Rule ID here) and a regression (since we were unaware users could specify this value for this field) - however the Azure Provider's recently been updated to validate that the ID provided is what we're expecting here (which is why this is an enhancement, albeit we should also support this value too).

From our side we'll take a look at supporting this behaviour for the next release - so apologies for this regression - however as mentioned above we were unaware that it was possible to use the Relay ID here in addition to the EventHub ID (so we'd need to support that here too).

Thanks!

**Comment by desertfoxmb** [comment]
Same here. This was working in our pipeline yesterday (11/18/21) and with the update to 2.86 it is now failing.
