### ISSUE TITLE
VM creation : keep os disk

### ISSUE THREAD

**Issue by ranjeetgarodia** [hashicorp/terraform-provider-azurerm#14283]
As per terraform documentation, below feature is given, but when running terraform validate, it is giving error that it is not supported.
so can you please let me know where need to define below:

ref:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#argument-reference

   on demo_vm.tf line 66, in resource "azurerm_linux_virtual_machine" "main":
│   66:   delete_os_disk_on_termination   = true
│
│ An argument named "delete_os_disk_on_termination" is not expected here.

thanks
Ranjeet Garodia

**Comment by aristosvo** [comment]
Hi @ranjeetgarodia, the documentation you're referring to is for the `azurerm_virtual_machine` resource, you are using the `azurerm_linux_virtual_machine` resource.

Documentation for this resource can be found [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine). It does not contain the functionality you are referring to unfortunately.
