### ISSUE TITLE
azurerm_sentinel_automation_rule Conditions

### ISSUE THREAD

**Issue by Coffee-007** [hashicorp/terraform-provider-azurerm#14286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_sentinel_automation_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_automation_rule" "example" {
  name = uuid()
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id
  display_name = "Example Automation Rule"
  action_playbook{
    logic_app_id = azurerm_logic_app_workflow.example.id
    order = 1
  }
  order = 100
  enabled = true
}
```

### Expected Behaviour

I expect I should be able to provide "Rule Name" as a property for a condition so that I can limit the automation rule to run when an Analytics Rule contains "XXX", but the property is not supported and therefore the rule gets applied to all analytic rules.

### Actual Behaviour

Automation rule is applied to all analytic rules

### Steps to Reproduce

Place a condition in place that tries to filter by Rule Name, run the Terraform Apply, error received because the Property checks don't allow for the default condition of "Analytic rule name"

**Comment by aristosvo** [comment]
Hi @Coffee-007!

The Terraform Provider for Azure is limited by the possibilities provided by the Azure API, a list of possible values can be found [here](https://github.com/Azure/azure-sdk-for-go/blob/v59.0.0/services/preview/securityinsight/mgmt/2019-01-01-preview/securityinsight/enums.go#L181). Would example below work for you? 
```hcl
resource "azurerm_sentinel_automation_rule" "example" {
  name = uuid()
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id
  display_name = "Example Automation Rule"
  action_playbook{
    logic_app_id = azurerm_logic_app_workflow.example.id
    order = 1
  }
  condition {
    property = "IncidentTitle"
    operator = "Contains"
    values = ["XXX"]
  }
  order = 100
  enabled = true
}
```

**Comment by Coffee-007** [comment]
Hi @aristosvo, thanks for the follow-up and yes I totally understand that it is limited to what the Azure API supplies, just unfortunate that the API doesnt mirror the interface.

The work around that you have supplied will work for the moment and hopefully the Azure API starts to expose the same as the interface.

I will raise a question in the Azure Repo as well and see what they suggest.
