### ISSUE TITLE
VGW shouldn't force update on authorization key change even no change

### ISSUE THREAD

**Issue by AshishDadhich4h2** [hashicorp/terraform-provider-azurerm#14280]
```hcl
resource "azurerm_virtual_network_gateway_connection" "connection" {
  name                = "ExpressRoute${var.region}"
  location            = "${var.region}"
  resource_group_name = "core-network"

  type                               = "ExpressRoute"
  virtual_network_gateway_id         = "${azurerm_virtual_network_gateway.expressroute.id}"
  express_route_circuit_id           = "${var.express_route_circuit_id}"
  authorization_key                  = "${azurerm_express_route_circuit_authorization.key.authorization_key}"
  routing_weight                     = 10
  enable_bgp                         = false
  use_policy_based_traffic_selectors = false
  express_route_gateway_bypass       = false
}
```

### Expected Behaviour

Resource azurerm_virtual_network_gateway_connection should not update  authorization_key when there is no change in key value during terraform plan.

### Actual Behaviour
 # azurerm_virtual_network_gateway_connection.connection will be updated in-place

 ~  ~ resource "azurerm_virtual_network_gateway_connection" "connection" {
      authorization_key:            <sensitive> => <sensitive> (attribute changed)

### Steps to Reproduce

1. `terraform  plan`

### References

* #0000

**Comment by lintaonz** [comment]
In my case:

* TF: v0.13.6
* azurerm: v2.65.0

The actual authorization_key has been replaced with `*****************` even both `azurerm_express_route_circuit_authorization` and `azurerm_virtual_network_gateway_connection`  have no change at all.

```
    {
      "module": "module.connectivity",
      "mode": "managed",
      "type": "azurerm_virtual_network_gateway_connection",
      "name": "er_vngc",
      "provider": "module.connectivity.provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "index_key": 0,
          "schema_version": 0,
          "attributes": {
            "authorization_key": "*****************",
           ...
```

Is this a bug?
