### ISSUE TITLE
`azurerm_frontdoor` has no argument to associate `azurerm_frontdoor_rules_engine` configuration

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azurerm#14293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_frontdoor`
* `azurerm_frontdoor_rules_engine`

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "example" {
  name                                         = "example-FrontDoor"
  resource_group_name                          = azurerm_resource_group.example.name
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "exampleRoutingRule1"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["exampleFrontendEndpoint1"]
    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "exampleBackendBing"
    }
  }

  backend_pool_load_balancing {
    name = "exampleLoadBalancingSettings1"
  }

  backend_pool_health_probe {
    name = "exampleHealthProbeSetting1"
  }

  backend_pool {
    name = "exampleBackendBing"
    backend {
      host_header = "www.bing.com"
      address     = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "exampleLoadBalancingSettings1"
    health_probe_name   = "exampleHealthProbeSetting1"
  }

  frontend_endpoint {
    name      = "exampleFrontendEndpoint1"
    host_name = "example-FrontDoor.azurefd.net"
  }
}
```

### Expected Behaviour

There should be a documented way to link a `azurerm_frontdoor_rules_engine` created object to an Azure FrontDoor routing rule.

### Actual Behaviour

There is no documented way to link the two objects.

### Steps to Reproduce

Open a web browser
Visit https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor
Validate there is no reference to assoicate a rules engine to a routing rule. 

* #0000

**Comment by heoelri** [comment]
ARM does currently support that. The next gen Azure Front Door service will change that. There's a documented workaround available using azurecli via the null_resource provider. See https://github.com/hashicorp/terraform-provider-azurerm/issues/7455#issuecomment-882769364 for more.

**Comment by heoelri** [comment]
PR #13911 (@joaomoreno) and PR #14093 (@mbfrahry) should solve that. TF should not remove the routing rule association anymore.

**Comment by joaomoreno** [comment]
Yup. Make sure you update to at least v2.85.0 and you won't get any downtime any more.

**Comment by bubbletroubles** [comment]
Thanks all. As advised this is fixed in later versions of the provider. Closing the ticket.
