### ISSUE TITLE
Validate storage account name parameter for databricks workspace

### ISSUE THREAD

**Issue by atombravo** [hashicorp/terraform-provider-azurerm#14309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Validate the optional custom parameter "storage_account_name" in a "azurerm_databricks_workspace" resource meets requirements for storage account names (no invalid characters).

Currently, no validation is done by the provider to check whether the value passed for "storage_account_name" meets requirements.  Invalid names (such as including hyphens or uppercase characters) are accepted by the provider.  When Azure attempts to provision the storage account for the databricks workspace with an invalid name, it leaves the databricks workspace in a "failed" state which requires it to be deleted and re-created.  No error bubbles up to the user indicating the cause of the failure.

### New or Affected Resource(s)

azurerm_databricks_workspace

### Potential Terraform Configuration
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_databricks_workspace" "example" {
  name                = "databricks-test"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "standard"

  custom_parameters= {
    storage_account_name = "alllowercaseandnumbersonly"
  }
}

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by guruprasad-afk** [comment]
Hi, I would like to work on this issue
