### ISSUE TITLE
Support for OpenID Connect to authenticate to Azure from GitHub Actions

### ISSUE THREAD

**Issue by hknutsen** [hashicorp/terraform-provider-azurerm#14326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is now possible to configure OpenID Connect to authenticate to Azure from GitHub Actions without using a secret.
It would be nice if Terraform supported this feature.

### References

* [Secure deployments with OpenID Connect & GitHub Actions now generally available](https://github.blog/2021-11-23-secure-deployments-openid-connect-github-actions-generally-available/)

**Comment by aristosvo** [comment]
@tombuildsstuff To get the expectations clear, is this only waiting on the release of Terraform v1.1 or are there other dependencies like https://github.com/hashicorp/terraform/pull/29814 before it can be considered supported?

**Comment by sigurdfalk** [comment]
@tombuildsstuff @aristosvo Any updates on this? I guess Terraform v1.1 is released now

**Comment by tombuildsstuff** [comment]
👋 

This is being tracked in https://github.com/hashicorp/go-azure-helpers/issues/91 - please subscribe to that issue for updates.

Thanks!
