### ISSUE TITLE
Linux/Windows App Service doesn't appear to support vnet_route_all site config

### ISSUE THREAD

**Issue by gabrielmccoll** [hashicorp/terraform-provider-azurerm#14331]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version   

* Terraform Core version: 1.0.11
* AzureRM Provider version: 2.86

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Description / Feedback

Hi there, the new Linux/windows WebApp resources don't appear to have anything in the site config to force private routing (or is it just undocumented?)

vnet_route_all_enabled - (Optional) Should all outbound traffic to have Virtual Network Security Groups and User Defined Routes applied? Defaults to false.

Our azure Policy forces this and doesn't recognise it just added the old way to APP Settings. 

The reason I say old way is that the existing azurerm_app_service documentation says

"This setting supersedes the previous mechanism of setting the app_settings value of WEBSITE_VNET_ROUTE_ALL. However, to prevent older configurations breaking Terraform will update this value if it not explicitly set to the value in app_settings.WEBSITE_VNET_ROUTE_ALL." 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service

**Comment by aristosvo** [comment]
Hi @gabrielmccoll!

https://github.com/hashicorp/terraform-provider-azurerm/pull/14202 should've solved that, it seems only the documentation is lacking. Have you tried configuring it?

**Comment by gabrielmccoll** [comment]
We did yes, the reason I found the bug so to speak is that our Azure policy seems to not like it still.  Let me see if there's been something silly and a version has slipped

**Comment by gabrielmccoll** [comment]
Hmm , weird.   It's deployed okay apart from a couple times where it gave the VNet error, with no changes in .tf files   
This might be an azure policy bug instead.

**Comment by jackofallops** [comment]
This will be fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/14247, unfortunately I only got part of the solution in 14202, sorry!

**Comment by gabrielmccoll** [comment]
@jackofallops ahh excellent glad it helped to flag it up. Thanks !
