### ISSUE TITLE
Index Error when Azure Virtual Desktop Registration Token time has exceeded

### ISSUE THREAD

**Issue by Theragus** [hashicorp/terraform-provider-azurerm#14330]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 1.0.11
AzureRm Provider Version: 2.86.0

### Affected Resource(s)

* `azurerm_virtual_desktop_host_pool`

### Terraform Configuration Files

```hcl

locals {
  expiration_date_for_Host_Pool = timeadd(timestamp(), "6h") // adding 6 hour timeframe to register the VM to the Host Pool
}


resource "azurerm_virtual_desktop_host_pool" "HostPool" {
  name                  = "HostPool"
  location              = "West Europe"
  resource_group_name   = "ResourceGroupName"
  type                  = "Pooled"
  load_balancer_type    = "DepthFirst"
  start_vm_on_connect   = true
  maximum_sessions_allowed = var.NumberofUsers
  custom_rdp_properties = "audiocapturemode:i:1;audiomode:i:0;targetisaadjoined:i:1;"

  registration_info {
    expiration_date = local.expiration_date_for_Host_Pool
  }

  lifecycle {
    ignore_changes = [registration_info]
  }
}

...

resource "azurerm_virtual_machine_extension" "HostPoolJoin" {
  name                       = "HostPoolJoin"
  virtual_machine_id         = azurerm_windows_virtual_machine.HSVM.id
  publisher                  = "Microsoft.Powershell"
  type                       = "DSC"
  type_handler_version       = "2.73"
  auto_upgrade_minor_version = true

  settings           = <<SETTINGS
  {
    "modulesUrl": "https://wvdportalstorageblob.blob.core.windows.net/galleryartifacts/Configuration_10-6-2021.zip",
    "configurationFunction": "Configuration.ps1\\AddSessionHost",
    "properties": {
      "hostPoolName": "${azurerm_virtual_desktop_host_pool.HostPool.name}",
      "aadJoin": true
    }
  }
    SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
  {
    "properties": {
      "registrationInfoToken": "${azurerm_virtual_desktop_host_pool.HostPool.registration_info[0].token}"
    }
  }
PROTECTED_SETTINGS
  lifecycle {
    ignore_changes = [settings, protected_settings]
  }
}
```

### Expected Behaviour

Terraform should do a plan successfully.

### Actual Behaviour

If you run terraform plan after the registration token has exceeded Terraform throws an error message:
```
Error: Invalid index

on .terraform/modules/HSonAzureV2/VM.tf line 138, in resource "azurerm_virtual_machine_extension" "HostPoolJoin":
      "registrationInfoToken": "${azurerm_virtual_desktop_host_pool.HostPool.registration_info[0].token}"

The given key does not identify an element in this collection value: the collection has no elements.
```
### Steps to Reproduce

1. add azurerm_virtual_desktop_host_pool to config. Set Registration token to a shorter time (e.g. 6 hours or so
2. reference Host Pool Registration Token in a VM extension to onboard the machine to the Host pool.
3. run terraform plan or terraform apply after registration token has exceeded. Note that the extension ignores changes to the registration token in the lifecycle policy and terraform still errors.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Theragus 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider - since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
