### ISSUE TITLE
Support for Virtual Network and Subnet when using Azure CNI in AKS

### ISSUE THREAD

**Issue by Socolin** [hashicorp/terraform-provider-azurerm#14336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was not able to find a way to configure the virtual network and subnet when using Azure CNI for AKS.
I would like to see this config available in kubernetes

![image](https://user-images.githubusercontent.com/539620/143295548-6ea95009-4d7e-4858-b79a-b080a587c4fe.png)

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

**Comment by christianrondeau** [comment]
This is very useful to avoid [virtual network peering costs](https://azure.microsoft.com/en-ca/pricing/details/virtual-network/) between Azure App Gateway and AKS.

**Comment by aristosvo** [comment]
Hi @Socolin! Can you elaborate a bit what this does and where I can find more documentation about it?

I have multiple options which might all be wrong:
- Is this already existing functionality which can be configured per node pool, [`default_node_pool.0.vnet_subnet_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#vnet_subnet_id)
- Is this the PodSubnet vs NodeSubnet ([Dynamic allocation of IPs and enhanced subnet support (preview)](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview))
- Is this new functionality which is not exported completely but seems partly present about defining a VNet for the masters (https://github.com/Azure/azure-rest-api-specs/blob/b6b834584cb58a3c2cbe887570fa0942b397dfc7/specification/containerservice/resource-manager/Microsoft.ContainerService/stable/2021-10-01/managedClusters.json#L2572-L2601)

**Comment by Socolin** [comment]
Hello,

I have no idea if this is a new feature, it's the first time I'm using AKS (still learning how it works).

When I look at the JSON on the portal the only location where I can find a reference to this is `properties.agentPoolProfiles[0].vnetSubnetID` so it seems to be option 1.

I was searching for "virtual network" in the documentation and since it's only referenced as subnet I did not find it, and with the portal UI I was not looking for it to be in the node pool (i though it would have been a more global settings).

Thanks for the quick answer.
