### ISSUE TITLE
Unable to deploy with Azure Lighthouse terraform module

### ISSUE THREAD

**Issue by lanicolas** [hashicorp/terraform-provider-azurerm#14334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Using Azure Cloud Shell: 

Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.9.0
+ provider registry.terraform.io/hashicorp/local v1.4.0

### Affected Resource(s)

[azurerm_lighthouse_definition]

### Terraform Configuration Files

```hcl
data "azurerm_role_definition" "contributor" {
  role_definition_id = "b24988ac-6180-42a0-ab88-20f7382dd24c"
}

resource "azurerm_lighthouse_definition" "mspoffer" {
  name               = var.mspoffername
  description        = var.mspofferdescription
  managing_tenant_id = var.managedbytenantid
  scope              = var.scope

  authorization {
    principal_id           = var.provider
    role_definition_id     = data.role_definition_id
    principal_display_name = var.principal_display_name
  }
}
```

### Debug Output

No output as no changes are made

### Expected Behaviour

Azure Lighthouse should be configured on the customers tenant providing access to another management tenant

### Actual Behaviour

No resource is deploy as terraform does not modify any resource: 
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

### Steps to Reproduce

Run the plan using 2 different Azure tenants, the msp offer name, description and managed tenant should correspond to the managed tenant whereas the plan should be run on the customer side.

1. `terraform apply`

### Important Factoids

Azure commercial Cloud

### References

A discussion:
https://discuss.hashicorp.com/t/unable-to-deploy-azure-lighthouse-using-terraform/16404

* #0000

**Comment by Lddeiva** [comment]
@lanicolas , I tested this and it seems to be working fine.

**Comment by lanicolas** [comment]
I seem to have an issue with previous role assigments we c
