### ISSUE TITLE
Failure: azurerm_mssql_server tries to update administrator_login_password while azuread_authentication_only is enabled

### ISSUE THREAD

**Issue by kevinharing** [hashicorp/terraform-provider-azurerm#14348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 1.0.11
AzureRM: 2.86.0

### Affected Resource(s)

* `azurerm_mssql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "sql_server" {
  name                         = local.sql_server_name
  resource_group_name          = azurerm_resource_group.rg.name
  location                     = azurerm_resource_group.rg.location
  version                      = "12.0"
  administrator_login          = local.sql_admin_username
  administrator_login_password = local.sql_admin_password // contains a new value on every apply
  minimum_tls_version          = "1.2"
  connection_policy            = "Proxy"

  identity {
    type = "SystemAssigned"
  }

  azuread_administrator {
    login_username              = data.azuread_group.sql_admin_ad_group.display_name
    object_id                   = data.azuread_group.sql_admin_ad_group.id
    azuread_authentication_only = true
  }
}
```

### Debug Output

Error: waiting for creation/update of Server: (Name "xxx" / Resource Group "xxx"): Code="AadOnlyAuthenticationIsEnabled" Message="Azure Active Directory Only Authentication is enabled. Please contact your system administrator."

### Expected Behaviour

1. Terraform should throw an error during plan that this is not allowed.
2. The fields `administrator_login` and `administrator_login_password` should be made optional.

### Actual Behaviour

1. Terraform throws an error during apply.
2. The fields `administrator_login` and `administrator_login_password` are required.

### Steps to Reproduce

1. `terraform apply`

**Note that the first time you enable azuread_authentication_only the apply goes through, the second apply (while updating the administrator_login_password) it fails.**

### Important Factoids

Updating the administrator_login_password is not allowed when azuread_authentication_only is enabled:

`To reset the server administrator password, Azure AD-only authentication must be disabled.`

[Source](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-only-authentication-create-server?tabs=azure-portal#limitations).

**Comment by kevinharing** [comment]
Workaround:

```hcl
lifecycle {
  ignore_changes = [
    administrator_login_password // Not allowed to change when azuread_authentication_only = true
  ]
}
```

**Comment by aristosvo** [comment]
Hi @kevinharing! Thanks for raising this issue.

I've raised a PR and changed the code to throw an error. Changing the fields `administrator_login` and `administrator_login_password` to optional is a posibility, but would make the code a lot more complex in the case of changing from Azure AD Only to administrator and other edge cases like that.

I hope you can agree with this solution for now.
