### ISSUE TITLE
Support for Bastion SKU settings

### ISSUE THREAD

**Issue by pszypowicz** [hashicorp/terraform-provider-azurerm#14347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Bastion is missing 'sku' configuration. 

### New or Affected Resource(s)

* azurerm_bastion_host

### References

https://docs.microsoft.com/en-us/azure/bastion/bastion-overview?WT.mc_id=Portal-Microsoft_Azure_HybridNetworking#sku

**Comment by pszypowicz** [comment]
Also it's worth to implement 'native client" capability. 

https://docs.microsoft.com/pl-pl/azure/bastion/connect-native-client-windows

**Comment by aristosvo** [comment]
Hi @pszypowicz! Thanks for filing this issue, a PR is on the way.

With regard to the `native client` capability, I'd prefer to have that as a separate issue/feature request to keep things separated and clean. Is that okay with you?
