### ISSUE TITLE
Add Metadata as optional field to gen2_filesystem and gen2_path

### ISSUE THREAD

**Issue by Locutus66** [hashicorp/terraform-provider-azurerm#14352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When trying to assign a metadata value to either azurerm_storage_data_lake_gen2_filesystem or azurerm_storage_data_lake_gen2_path, an error is thrown: "Unsupported argument"

### New or Affected Resource(s)

* azurerm_storage_data_lake_gen2_filesystem
* azurerm_storage_data_lake_gen2_path

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_data_lake_gen2_path" "folder" {
  count = length(local.container_folder_pairs)

  path               = local.container_folder_pairs[count.index].folder
  filesystem_name    = local.container_folder_pairs[count.index].container
  storage_account_id = data.azurerm_storage_account.storageAccountADL.id
  resource           = "directory"
  metadata           = var.ucid # this will fail, even with a static string

  depends_on = [
    azurerm_storage_data_lake_gen2_filesystem.saadlv2
  ]
}


resource "azurerm_storage_data_lake_gen2_filesystem" "saadlv2" {
  for_each = var.file_system

  name               = each.key 
  storage_account_id = data.azurerm_storage_account.storageAccountADL.id
  metadata           = var.ucid # this will fail, even with a static string

  #admingroup permission
  dynamic "ace" {
    for_each = concat(local.adminsIds, var.aad_admin_object_ids)

    content {
      id          =  ace.value
      permissions = "rwx"
      scope       = "access"
      type        = "group"
    }
  }

  #admingroup permission
  dynamic "ace" {
    for_each = concat(local.adminsIds, var.aad_admin_object_ids) 
    content {
      id          = ace.value 
      permissions = "rwx"
      scope       = "default"
      type        = "group"
    }
  }
}
```

### References

* #0000

**Comment by Locutus66** [comment]
So upon further investigation, it seems setting the Metadata in gen2 is done through properties.

https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/internal/services/storage/storage_data_lake_gen2_filesystem_resource.go#L76
https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/internal/services/storage/metadata.go#L8

This works as an example:
```
resource "azurerm_storage_data_lake_gen2_filesystem" "saadlv2" {
  for_each = var.file_system

  name               = each.key 
  storage_account_id = data.azurerm_storage_account.storageAccountADL.id
  properties = { # right here
    ucid = base64encode(var.ucid)
  }

  #admingroup permission
  dynamic "ace" {
    for_each = concat(local.adminsIds, var.aad_admin_object_ids)

    content {
      id          =  ace.value
      permissions = "rwx"
      scope       = "access"
      type        = "group"
    }
  }

  #admingroup permission
  dynamic "ace" {
    for_each = concat(local.adminsIds, var.aad_admin_object_ids) 
    content {
      id          = ace.value 
      permissions = "rwx"
      scope       = "default"
      type        = "group"
    }
  }
}
```
If the intention was to make properties the entry field for Metadata, feel free to close this ticket.

**Comment by rcskosir** [comment]
Closing as noted above by author.
