### ISSUE TITLE
Disable Automatic VM Guest Patching not supported

### ISSUE THREAD

**Issue by doherty100** [hashicorp/terraform-provider-azurerm#14383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The latest version of the Azure REST API supports modifications to the `enable_automatic_updates` and `patch_mode` properties. Disabling Automatic VM Guest Patching should no longer force replacement of the VM.

### New or Affected Resource(s)

* azurerm_windows_virtual_machine

### Potential Terraform Configuration

For the initial deployment, `enable_automatic_updates` was set to `true` and `patch_mode` was set to "AutomaticByOS".

```hcl
resource "azurerm_windows_virtual_machine" "vm_mssql" {
  name                     = var.vm_mssql_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  size                     = var.vm_mssql_size
  admin_username           = data.azurerm_key_vault_secret.adminuser.value
  admin_password           = data.azurerm_key_vault_secret.adminpassword.value
  network_interface_ids    = [azurerm_network_interface.vm_mssql_nic_01.id]
  enable_automatic_updates = true
  patch_mode               = "AutomaticByOS"
  license_type             = "Windows_Server"
  tags                     = var.tags

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = var.vm_mssql_storage_account_type
  }

  source_image_reference {
    publisher = var.vm_mssql_image_publisher
    offer     = var.vm_mssql_image_offer
    sku       = var.vm_mssql_image_sku
    version   = var.vm_mssql_image_version
  }
}
```

If you try to disable Automatic VM Guest Patching by setting `enable_automatic_updates` to `false` and `patch_mode` to `Manual`, azurerm provider still forces replacement even though these properties are now updatable:

```hcl
resource "azurerm_windows_virtual_machine" "vm_mssql" {
  name                     = var.vm_mssql_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  size                     = var.vm_mssql_size
  admin_username           = data.azurerm_key_vault_secret.adminuser.value
  admin_password           = data.azurerm_key_vault_secret.adminpassword.value
  network_interface_ids    = [azurerm_network_interface.vm_mssql_nic_01.id]
  enable_automatic_updates = false
  patch_mode               = "Manual"
  license_type             = "Windows_Server"
  tags                     = var.tags

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = var.vm_mssql_storage_account_type
  }

  source_image_reference {
    publisher = var.vm_mssql_image_publisher
    offer     = var.vm_mssql_image_offer
    sku       = var.vm_mssql_image_sku
    version   = var.vm_mssql_image_version
  }
}
```

### References

* [Disable Automatic VM Guest Patching](https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#disable-automatic-vm-guest-patching)

**Comment by myc2h6o** [comment]
Hi @doherty100 Though API allows update to `enable_automatic_updates`, it can only be updated in Windows VMSS currently, it cannot be updated in Windows VM.
https://docs.microsoft.com/en-us/azure/virtual-machines/automatic-vm-guest-patching#patch-orchestration-modes
> For Windows VMs, the property osProfile.windowsConfiguration.enableAutomaticUpdates can only be set when the VM is first created.
