### ISSUE TITLE
Terraform Azure Data Factory Trigger Schedule - Error When Using Activated With Schedule Block

### ISSUE THREAD

**Issue by mysterygrocer** [hashicorp/terraform-provider-azurerm#14384]
I've created a new datafactory pipeline trigger meant to invoke every 5th of the month at 13:00 UTC using Terraform. This was achieved using **_azurerm_data_factory_trigger_schedule_** resource key.

However, as the trigger Status doesn't automatically get set to Started on deploy, I used the **_activated_** property in an attempt to set it. This is following the updates made on this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/13390

However, adding _activated_ causes an error on deployment.

The Terraform script I'm using is as follows:

```
resource "azurerm_data_factory_trigger_schedule" "pipeline_trigger" {
  name                = "Pipeline_MonthlyTrigger"
  data_factory_name   = "dataFactoryName"
  resource_group_name = "resourceGroupName"
  pipeline_name       = "pipelineName"

  frequency           = "Month"
  interval            = 1

  activated           = true

  schedule  {
    days_of_month     = [4]
    hours             = [13]
    minutes           = [0]
  }
}
```

The error that comes up on deployment:

> The recurrence schedule of trigger could not have 'WeekDays' for recurrence frequency 'Month'." Target="Pipeline_MonthlyTrigger"

I raised [a similar question on Stackoverflow](https://stackoverflow.com/questions/70148972/terraform-azure-data-factory-trigger-schedule-error-when-using-activated-with) and was told that this is most likely a bug on the newly added support for _activated_ clashing with _schedule_ block.

**Comment by aristosvo** [comment]
Hi @mysterygrocer! Thanks for raising this issue!

I expect it to be a configuration confusion mistake, this is how I expect it to work:
```hcl
resource "azurerm_data_factory_trigger_schedule" "example" {
  name                = "example"
  data_factory_name   = azurerm_data_factory.example.name
  resource_group_name = azurerm_resource_group.example.name
  pipeline_name       = azurerm_data_factory_pipeline.example.name

  annotations = ["test1", "test2", "test3"]
  frequency   = "Month"
  interval    = 1
  activated   = true

  schedule {
    monthly {
      weekday = "Monday"
      week    = 1
    }
  }
}
```

**Comment by Grigoriy0** [comment]
I was faced with the similar issue today. How can I specify the hourly time for the trigger?
```terraform
resource "azurerm_data_factory_trigger_schedule" "daily" {
  data_factory_name   = var.data_factory_name
  name                = var.name
  pipeline_name       = var.pipeline_name
  resource_group_name = var.resource_group_name
  activated           = true
  interval            = 1
  frequency           = "Hour"

  schedule {
      days_of_month = []
      days_of_week  = []
      hours         = range(1, 25)
      minutes       = [0]
  }
}
```
With activated = true an API returns some errors, from `"The recurrence schedule of trigger has an invalid recurrence frequency 'Hour'"` to `"The recurrence of trigger has an invalid start time '2021-11-30T09:49:23.6373031+00:00' zone designator for time zone 'UTC'"`

An interesting thing: the trigger is created inactive, but terraform tries to create it again. Azure API returns "400" errors, but creates the disabled trigger. 
Only if I delete schedule block it will be successfully created in activated state.

**Comment by aristosvo** [comment]
@Grigoriy0 Working on it!

I'm adding some tests to validate the behaviour and interaction with the Azure API in the Terraform Provider in more detail, as current tests were not validated completely as schedules weren't activated. Almost there!

**Comment by mysterygrocer** [comment]
Thanks for the quick fix on this @aristosvo ! Will catch the fix you made when it gets included on the next Release.
