### ISSUE TITLE
Old Policy Assignments and Definitions metadata keys now replaced by native systemData

### ISSUE THREAD

**Issue by gettek** [hashicorp/terraform-provider-azurerm#14380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.84.0
```

### Affected Resource(s)

* `azurerm_policy_definition`
* `azurerm_policy_set_definition`
* `azurerm_management_group_policy_assignment`
* `azurerm_subscription_policy_assignment`
* `azurerm_resource_group_policy_assignment`
* `azurerm_resource_policy_assignment`
* `azurerm_policy_assignment`
* [Keys are located in metadata.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/policy/metadata.go#L26)

### Terraform Configuration Files

```hcl
+ resource "azurerm_management_group_policy_assignment" "def" {
      + display_name         = "Resources should inherit Resource Group Tags and Values with Modify Remediation"
      + enforce              = true
      + id                   = (known after apply)
      + location             = "uksouth"
      + management_group_id  = "/providers/Microsoft.Management/managementGroups/team_a"
      + metadata             = jsonencode(
            {
              + category  = "Tags"
              + createdBy = "6e89b073-9963-4ee8-99ce-7260c80124e7"
              + createdOn = "2021-11-21T20:48:39.143189Z"
              + updatedBy = null
              + updatedOn = null
              + version   = "1.0.0"
            }
        )

```

### Debug Output

Trying to create our own metadata block conflicts with the [provider keys](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/policy/metadata.go#L26) at policy assignment

```
│ Error: Provider produced inconsistent final plan
│
│ When expanding the plan for module.customer_mg_add_replace_resource_group_tag_key_modify.azurerm_management_group_policy_assignment.def[0] to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for .metadata: was cty.StringVal("{\"category\":\"Tags\",\"version\":\"1.0.0\"}"), but now
│ cty.StringVal("{\"category\":\"Tags\",\"createdBy\":\"6e89b073-9963-4ee8-99ce-7260c80124e7\",\"createdOn\":\"2021-11-21T20:50:10.433817Z\",\"updatedBy\":null,\"updatedOn\":null,\"version\":\"1.0.0\"}").
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

Even ignoring the debug output above, Terraform should no longer need to generate metadata keys `["assignedBy", "createdBy", "createdOn", "updatedBy", "updatedOn"]` as these are now nativley generated by the Azure Policy engine attribute named as `systemData` which gets automatically added to all definitions and assignments such as below:

```json
 "systemData": {
    "createdBy": "user.name@tenant.onmicrosoft.com",
    "createdByType": "User",
    "createdAt": "2021-11-25T23:30:26.8233824Z",
    "lastModifiedBy": "user.name@tenant.onmicrosoft.com",
    "lastModifiedByType": "User",
    "lastModifiedAt": "2021-11-25T23:30:26.8233824Z"
  }
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @gettek 

Thanks for opening this issue.

The code that you've linked is removing these keys from the diff, rather than setting these into the state - these are instead actually being returned from the Azure Policy API itself.

With regards to SystemData, this is set in the Azure API itself and (as far as I know) isn't intended to be user-configured, as such this isn't something we plan to expose in Terraform at this time.

Coming back to the specific issue your seeing here, unfortunately `Provider produced inconsistent final plan` is a bug in Terraform Core, as such I'd encourage you to open an issue on the Terraform Core repository where someone from that team should be able to take a look, however I'm going to close this issue for the moment.

Thanks!

**Comment by gettek** [comment]
Hi @tombuildsstuff 

Appreciate the quick response but unfortunately I may have misrepresented the issue, it does in fact appear those keys are being added to the state file, I tested this today with only 2 key/value pairs in the definition metadata:

### Config
```hcl
locals {
  # create metadata if var.policy_metadata is omitted
  metadata = var.policy_metadata == null ? jsonencode(merge(
    { category = var.policy_category },
    { version = var.policy_version },
  )) : var.policy_metadata
}

resource azurerm_policy_definition def {
  name         = var.policy_name
  display_name = local.display_name
  description  = local.description
  policy_type  = "Custom"
  mode         = var.policy_mode

  management_group_name = var.management_group_name

  policy_rule = jsonencode(local.policy_rule)
  parameters  = jsonencode(local.parameters)
  metadata    = local.metadata

  lifecycle {
    create_before_destroy = true
  }

  timeouts {
    read = "10m"
  }
}

```
### Statefile
```json
"metadata": "{\"category\":\"Tags\",\"createdBy\":\"ee59fcd1-be05-4635-9892-eedbc14ae9d8\",\"createdOn\":\"2021-11-30T12:44:54.0265553Z\",\"updatedBy\":null,\"updatedOn\":null,\"version\":\"1.0.0\"}",
```

So since these are now auto-generate within systemData by the Azure API, we no longer need the provider to create/manage them. Hope this is a little clearer. Thanks!

**Comment by tombuildsstuff** [comment]
@gettek these are added to the state file (since they're coming from the Azure API, but ignored in the diff - as mentioned above unfortunately that's an Azure API question/enhancement, rather than specific to the Azure Provider.

**Comment by gettek** [comment]
Thanks @tombuildsstuff,

Strange though as this doesn't happen with Bicep or ARM templates. Perhaps it not a major issue but worth a mention

**Comment by tombuildsstuff** [comment]
Good to know @gettek - out of interest which API version are you using for ARM Templates/Bicep where this isn't present?

My guess is that older versions of the API/resources provisioned using older API versions may have this preset - but that newer ones won't, which is a common pattern across Azure - but I've not tested that to confirm in this specific case.

**Comment by gettek** [comment]
Hey @tombuildsstuff, these are the API versions, fairly new, tbh I've not tested with older ones...

- `policyDefinitions@2021-06-01`
- `policySetDefinitions@2021-06-01`
- `policyAssignments@2021-06-01`

**Comment by tombuildsstuff** [comment]
Thanks - we're currently using `2019-09-01`, so I guess that's the behaviour of the newer API
