### ISSUE TITLE
no value for inbound_ip_address, virtual_ip in app_service

### ISSUE THREAD

**Issue by hoivikaj** [hashicorp/terraform-provider-azurerm#14385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.87.0

### Affected Resource(s)

* `azurerm_app_service`
* `azurerm_app_service_custom_hostname_binding`

### Problem Description

Previous issue #5333 was closed citing an issue that it was impossible to create DNS A records for app_service resources as there was no way to return the `inbound_ip_address` for said app_service.

The proposal was for the app_service to add support for `inbound_ip_address` as properties. However the issue was closed citing the need to use the `virtual_ip` property from `azurerm_app_service_custom_hostname_binding`. 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_custom_hostname_binding#virtual_ip

### Actual Behaviour

In its current state:
- The inbound ip address is still not accessible in state. There does not appear to be a property for inbound_ip_address for the app_service resource
- The `virtual_ip` property of `azurerm_app_service_custom_hostname_binding` exists but appears to be empty in state. 
![image](https://user-images.githubusercontent.com/38190936/143972975-e7126d0c-ed1f-46eb-85e6-3484847de32d.png)

The IP address is discoverable using the Azure GUI.
![image](https://user-images.githubusercontent.com/38190936/143972244-4dfa15fa-8eaf-434c-9abb-47b95df5af61.png)

In various tests the IP address can also be found in state always listed as the last IP address in the `outbound_ip_address_list` and. `possible_outbound_ip_address_list` set.
![image](https://user-images.githubusercontent.com/38190936/143972585-83bddaf4-2339-43ba-805c-1e9c8e018fe1.png)

### Steps to Reproduce

Create an app service with custom hostname and certificate
Attempt via terraform to return the inbound IP of your SNI app service.

### References

* #5333

**Comment by favoretti** [comment]
Hi there and thank you for reporting this!
So apparently portal fetches the `inboundIpAddress` property as 
```
curl 'https://management.azure.com/batch?api-version=2020-06-01' \
  -H 'x-ms-client-session-id: 7423c24ef76648ca83de8d87580ff1eb' \
  -H 'x-ms-command-name: { HubsExtension.Batch:0,Unknown:1}' \
  -H 'Accept-Language: en' \
  -H 'Authorization: Bearer xxx' \
  -H 'x-ms-effective-locale: en.en-us' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Referer: ' \
  -H 'x-ms-client-request-id: xxx' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36' \
  --data-raw '{"requests":[{"httpMethod":"GET","name":"a5fc5dbd-1716-4372-8091-1f3b8d55e00b","requestHeaderDetails":{"commandName":"HubsExtension."},"url":"/subscriptions/953f18a0-9b3d-4a43-9fe8-f41039606a03/resourceGroups/eastus2-fxs-oscar-np-rg/providers/Microsoft.Web/sites/xxx-dev-appsvc?api-version=2015-08-01"}]}' \
  --compressed
```

The response to this call actually contains populated property:

![image](https://user-images.githubusercontent.com/805046/144039830-434f3afb-2c64-4847-bac1-d0239f1f017d.png)

Now the question would be how to actually fetch it without creating all too much spaghetti around it...

**Comment by hoivikaj** [comment]
For what its worth, in limited testing the `inbound_ip_address` seems to be the same for all app's using the same `app_service_plan`. Currently proceeding by manually specifying the IP after getting the IP outside of terraform after first app creation, which is obviously a bad idea :).

Another workaround for some people may be to instead point their custom DNS record as a CNAME to the `<appservice>.azurewebsites.net` hostname which is accessible in state as `default_site_hostname`, but for organizations that use DNS filtering services like OpenDNS - newly created azurewebsites.net hostnames may be blocked, breaking the lookup chain. (Which is why we are using direct A records).

**Comment by hoivikaj** [comment]
A great workaround for this issue came up in another thread, and wanted to repost it here in case someone come across this issue vs the feature request #14642

Courtesy @mateusz-opoka  

Hi! I've just found a workaround.

You can use [hashicorp/dns](https://registry.terraform.io/providers/hashicorp/dns/latest) provider to get this IP address by default hostname.

For example:

```
resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}
}

data "dns_a_record_set" "app_ip_address" {
  host = azurerm_linux_web_app.example.default_hostname
}

resource "azurerm_dns_a_record" "dns_a" {
  # ...
  target_resource_id  = data.dns_a_record_set.app_ip_address.addrs[0]
}
```

**Comment by EamonHetherton** [comment]
this is still an issue with azurerm_windows_web_app and azurerm_linux_web_app BTW.
