### ISSUE TITLE
Support for streaming ingest on azurerm_kusto_database

### ISSUE THREAD

**Issue by kiranpradeep** [hashicorp/terraform-provider-azurerm#14396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We can enable/disable streaming ingest, at a kusto database level also as in this [Microsoft doc](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-database-streaming-ingestion-policy-command). Currently terraform offers support for streaming ingestion at a cluster level only.

More importantly, if we enable streaming ingest at cluster level (at a later point in project) after the database have been created, then already existing database will not have the policy enabled.

### New or Affected Resource(s)

* azurerm_kusto_database

### Potential Terraform Configuration

```hcl
resource "azurerm_kusto_database" "database" {
  name                = "my-kusto-database"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  cluster_name        = azurerm_kusto_cluster.cluster.name

  enable_streaming_ingest = true
}
```

### References

The same applies to kusto tables, but that is not in scope of this project.
* [adx_table](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/alter-table-streaming-ingestion-policy-command)

**Comment by aristosvo** [comment]
Hi @kiranpradeep! Thanks for filing this issue, but unfortunately this is outside the scope of this provider.

It is not possible to enable streaming within the Azure REST API, which is basically the scope of this provider. It might be possible using [`azurerm_kusto_script`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_script) and the commands provided [here](https://docs.microsoft.com/en-us/azure/data-explorer/ingest-data-streaming?tabs=azure-portal%2Ccsharp#create-a-target-table-and-define-the-policy):
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_kusto_cluster" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }
}

resource "azurerm_kusto_database" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cluster_name        = azurerm_kusto_cluster.example.name
}

resource "azurerm_storage_account" "example" {
  name                     = "example"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "setup-files"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "example" {
  name                   = "script.txt"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source_content         = ".alter database example policy streamingingestion enable"
}

data "azurerm_storage_account_blob_container_sas" "example" {
  connection_string = azurerm_storage_account.example.primary_connection_string
  container_name    = azurerm_storage_container.example.name
  https_only        = true

  start  = "2017-03-21"
  expiry = "2022-03-21"

  permissions {
    read   = true
    add    = false
    create = false
    write  = true
    delete = false
    list   = true
  }
}

resource "azurerm_kusto_script" "example" {
  name                               = "example"
  database_id                        = azurerm_kusto_database.example.id
  url                                = azurerm_storage_blob.example.id
  sas_token                          = data.azurerm_storage_account_blob_container_sas.example.sas
  continue_on_errors_enabled         = true
  force_an_update_when_value_changed = "first"
}
```

I'll close this issue for now, I hope you got the functionality you need!
