### ISSUE TITLE
Add support for all possible values of Client certificate mode in Azure App Service

### ISSUE THREAD

**Issue by l-derossis** [hashicorp/terraform-provider-azurerm#14393]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for all possible values of `Client certificate mode` setting in `azurerm_app_service`. Currently, the argument `client_cert_enabled` is a boolean, altough it can takes 3 values in Azure : `Require`, `Allow` or `Ignore`. Maybe add a `client_cert_mode`, like what has been done for the `azurerm_function_app` in this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/11161

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service" "example" {
  name                = "example-app-service"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  client_cert_mode = "Allow"
}
```

**Comment by favoretti** [comment]
Here's what SDK has to say about this:
```
ClientCertEnabled *bool `json:"clientCertEnabled,omitempty"`
	// ClientCertMode - This composes with ClientCertEnabled setting.
	// - ClientCertEnabled: false means ClientCert is ignored.
	// - ClientCertEnabled: true and ClientCertMode: Required means ClientCert is required.
	// - ClientCertEnabled: true and ClientCertMode: Optional means ClientCert is optional or accepted. Possible values include: 'ClientCertModeRequired', 'ClientCertModeOptional', 'ClientCertModeOptionalInteractiveUser'
	ClientCertMode ClientCertMode `json:"clientCertMode,omitempty"`
```
