### ISSUE TITLE
r/postgresql_flexble_server: docs enhancement

### ISSUE THREAD

**Issue by cpressland** [hashicorp/terraform-provider-azurerm#14397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v1.0.11
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.87.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/terraform-providers/chef v0.2.0
+ provider registry.terraform.io/terrycain/chef v0.3.2
+ provider registry.terraform.io/terrycain/commandpersistence v1.1.0
```

### Affected Resource(s)

* `azurerm_postgresql_flexible_server`

### Terraform Configuration Files

Example code works just fine from [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server) minus the `zone` field, our example:

```hcl
resource "azurerm_postgresql_flexible_server" "pgfs" {
    for_each = var.postgres_flexible_config

    name = each.value.name
    resource_group_name = azurerm_resource_group.rg.name
    location = azurerm_resource_group.rg.location
    version = each.value.version
    delegated_subnet_id = azurerm_subnet.postgres.id
    private_dns_zone_id = azurerm_private_dns_zone.pgfs.id
    administrator_login = random_pet.pgfs[each.key].id
    administrator_password = random_password.pgfs[each.key].result

    storage_mb = each.value.storage_mb

    dynamic "high_availability" {
        for_each = each.value.high_availability ? [1] : []
        content {
            mode = "ZoneRedundant"
        }
    }

    sku_name   = each.value.sku_name
    depends_on = [azurerm_private_dns_zone_virtual_network_link.pgfs]
}
```
### Expected Behaviour

In upgrading from Provider version 2.85.0 to 2.87.0, no change should be observed.

### Actual Behaviour

Terraform wants to "update" all Postgres instances, removing default zone, example:

```
  # module.uksouth_sandbox_environment.azurerm_postgresql_flexible_server.pgfs["common"] will be updated in-place
  ~ resource "azurerm_postgresql_flexible_server" "pgfs" {
        id                            = "/subscriptions/<snipped>/resourceGroups/uksouth-sandbox/providers/Microsoft.DBforPostgreSQL/flexibleServers/<snipped>-sandbox"
        name                          = "<snipped>-sandbox"
        tags                          = {}
      - zone                          = "1" -> null
        # (13 unchanged attributes hidden)
    }
```

Trying to apply this results in an error:

```
│ Error: `zone` and `standby_availability_zone` should only be either exchanged with each other or unchanged
│ 
│   with module.uksouth_dev_environment.azurerm_postgresql_flexible_server.pgfs["common"],
│   on .terraform/modules/uksouth_dev_environment/postgres_flex.tf line 46, in resource "azurerm_postgresql_flexible_server" "pgfs":
│   46: resource "azurerm_postgresql_flexible_server" "pgfs" {
│ 
```

### Steps to Reproduce

1. Deploy a flexible server with provider version 2.85.0
2. Upgrade to provider version 2.87.0
3. Attempt an apply

Documentation suggests to add `zone` and `standby_availability_zone` to ignore_changes lifecycle, this mitigates the issue, however documentation should state `high_availability.0.standby_availability_zone` instead of simply `standby_availability_zone`.

### References

* Caused by changes in PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/13843

**Comment by tombuildsstuff** [comment]
hi @cpressland 

The documentation here is referring to the field `standby_availability_zone` rather than it's full address since it's located in place within the documentation for the `high_availability` block, as such this is _technically correct_ in what it's saying today. That said, I'd agree with you that it'd be helpful for this to have the full address too - so I'm going to tag this as a documentation enhancement 👍

Thanks!

**Comment by fcatacut** [comment]
@tombuildsstuff I believe that this is an actual bug, which I also encountered in 2.88.1. By _not_ setting `zone`, its value should is implicitly `null`. It appears that Azure is arbitrarily picking one of the zones. In @cpressland's description, it picked `1`. On subsequent `terraform plan` runs. Terraform is picking up this difference and is trying to set the value to `null` resulting in the error.

**Comment by chaoqi** [comment]
@tombuildsstuff i can also confirm this bug is still actual by using 2.88.1.
