### ISSUE TITLE
Feature Request: Sticky AppSetting and ConectionStrings - azurerm_app_service, azurerm_app_service_slot

### ISSUE THREAD

**Issue by kevinneufeld** [hashicorp/terraform-provider-azurerm#1440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add ability to set an AppSetting and ConnectionString as Sticky:

Currently, we are adding sticky AppSetting and ConnectionStrings via `azurerm_template_deployment` resource.

```hcl
resource "azurerm_template_deployment" "sticky_test" {
  name                = "sticky_test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  deployment_mode     = "Incremental"

  template_body = <<DEPLOY
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
      "stickyConnectionStringsNames": {
        "type": "String"
      },
      "stickyAppSettingNames": {
        "type": "String"
      }
      "webAppName": {
          "type": "String"
      }
  },
  "variables": {
    "connectionStringNames": "[split(parameters('stickyConnectionStringsNames'),',')]",
    "appSettingNames": "[split(parameters('stickyAppSettingNames'),',')]"
  },
  "resources": [
      {
        "type": "Microsoft.Web/sites/config",
        "name": "[concat(parameters('webAppName'), '/slotconfignames')]",
        "apiVersion": "2015-08-01",
        "properties": {
          "connectionStringNames": "[variables('connectionStringNames')]",
          "appSettingNames": "[variables('appSettingNames')]"
        }
      }
  ]
}
DEPLOY

  parameters {
    "webAppName"                   = "${azurerm_app_service.msbx_api.name}"
    "webAppCustomHostname"         = "${cloudflare_record.api-cname.hostname}"
    "stickyConnectionStringsNames" = "DBContext"                                #"${join(",",distinct(list(azurerm_app_service.test.connection_string.0.name,azurerm_app_service_slot.test.connection_string.0.name)))}"
    "stickyAppSettingNames"        = "APPSETTING1,APPSETTING2,APPSETTING3"      #"${join(",",distinct(concat(keys(azurerm_app_service.test.app_settings),keys(azurerm_app_service_slot.test.app_settings))))}"
  }

  depends_on = [
    "azurerm_app_service.test",
    "azurerm_app_service_slot.test",
  ]
}
```
### New or Affected Resource(s)

* azurerm_app_service
* azurerm_app_service_slot

### Potential Terraform Configuration

Since the arm type targets `Microsoft.Web/sites/config` it initial makes sense for another argument on `azurerm_app_service` like `sticky_settings` or `slot_config_names`.

```hcl
resource "azurerm_app_service" "test" {
  name                = "${random_id.server.hex}"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  app_service_plan_id = "${azurerm_app_service_plan.test.id}"

  site_config {
    dotnet_framework_version = "v4.0"
    scm_type                 = "LocalGit"
  }

  app_settings {
    "SOME_KEY1" = "some-value"
    "SOME_KEY2" = "some-value"
  }
 
  connection_string {
    name  = "Database"
    type  = "SQLServer"
    value = "Server=some-server.mydomain.com;Integrated Security=SSPI"
  }

   slot_config_names {
      app_settings = [
          "SOME_KEY1",
          "SOME_KEY2",
      ]
      connection_string = ["Database"]
  }
}
```

**Comment by perbergland** [comment]
I would prefer a syntax where the value and stickyness are set in one go instead of having it in two places.
This could be achieved by creating new sections that impose the stickyness and still allow you to set the values by precalculated hashes (for appsettings - no such luck for connection strings)
`
app_settings_sticky {
"SOME_KEY1" = "some-value"
}
...
app_settings_sticky = "${local.my_hash}"
`

**Comment by Stolpe** [comment]
It took me a while to find this feature request. Another term for this (which would have helped me finding this) is _slot setting_.

**Comment by gabrieljoelc** [comment]
We need this to be able to fully automate our production deployment. We don't currently use slots for non-production environments (it's more affordable and we don't need zero-downtime in non-prod environments). Since I [cannot](https://github.com/hashicorp/terraform/issues/15281) conditionally create/update a resource, I would have to create a slot resource for all non-production environments or exclude the target for all non-production environments (this is annoying since there is no `--target-excluded` switch).

If app setting slot flag setting was supported, I could set the flag to true every time for every environment regardless of if that environment had a slot setting.

I agree with @perbergland that it'd be nice to configure settings and slot flags together, but it'd be nice if it would be an optional value + flag format:
```
app_settings {
  Key1 = "value1"
  Key2 = ["value2", true]
}
```

I also agree with @Stolpe that the title of this issue should be updated to include "slot setting".

**Comment by gabrieljoelc** [comment]
A co-worker pointed out that I mis-read  https://github.com/hashicorp/terraform/issues/15281#issuecomment-308275154. I assumed it was specific to that AWS resource when I couldn't find the `count` in the Azure App Service documentation, but it is in the general `resource` docs. This allowed me to have a conditional slot config which solved my problem and I don't need this feature. 😬

**Comment by Andreas-Lehmann** [comment]
is there any update on this?
Would love to see a native implementation of sticky slot settings in the azure terraform provider.

could loo like
```tf
  connection_string {
    name  = "Database"
    type  = "SQLServer"
    value = "Server=some-server.mydomain.com;Integrated Security=SSPI"
    deployment_slot_setting = "true" # optional with default "false"
  }
```

**Comment by judgewest2000** [comment]
I'm guessing there's not been a massive amount of movement on this one?

**Comment by simondevolutions** [comment]
I would also like to see something like this implemented. We are looking to keep a short-lived pre-prod slot in order to be able to swap our new version without downtime, to prevent having to reprovision the same app settings on the slots, we would like to be able to enable sticky app settings on the production slot and swap with preview and then destroy the slot after the completed swap.

**Comment by vsawanny** [comment]
I am trying to enable specific app settings for stage and prod slots via terraform for App service . 
Please let me know if this feature is enabled or not or please suggest if there is any alternative for the same 
Thanks!

**Comment by shivanigoyaluk** [comment]
function_app_slot is available but it's of not much use as it doesn't have sticky app setting support. Is it going to available anytime soon?

https://www.terraform.io/docs/providers/azurerm/r/function_app_slot.html

**Comment by peter-dolkens** [comment]
@neil-yechenwei I saw you were active on some of the other azure provider support - any chance you know what's going on with this one?

**Comment by elliotchaim** [comment]
Any news on this? I think others would agree that this is fundamental functionality when leverage deployment slots and auto-swapping. By no means advanced usage, this is the type of limitation which prohibits some organisations from using terraform altogether.

**Comment by Jrc356** [comment]
If I could make a suggestion on this, I think it would be the most helpful if we could set sticky settings using the same api as defined now but with the option to provide a map of maps for the settings instead of just a map of strings. For example, if I just wanted to set app settings normally (without slot setting checked off), then it could be:
```hcl
app_settings = {
  "some_setting" = "some value"
}
```
and if I wanted to make that sticky then I could change it to:
```hcl
app settings = {
  {
    "name" = "some_setting"
    "value" = "some value"
    "slot_setting" = true
  }
}
```
I believe this lines up with how arm handles it as well so it's consistent across that and I would think this prevents breaking the original usage.

**Comment by Lucretius** [comment]
I took a look in the codebase and found that the Azure SDK representation looks most like the "slot_config_names" suggestion in the original issue.

I can work on a PR for this feature.

**Comment by akshaychopra5207** [comment]
@Lucretius  and all When is this feature coming? any expected date?

**Comment by prashdevops2020** [comment]
@Lucretius Is this on the road map for this year or next quarter? Any update is appreciated. Thanks!

**Comment by scuderig** [comment]
Really surprised this is still open
This is a mandatory feature for the terraform component to be usable on real-world scenario, as of now we are forced to handle this setup manually, which is not really what should happens when using IaC in your project.


Please review and prioritize accordingly

**Comment by verlindb** [comment]
I agree with scuderig that this is a general feature that we would like to achieve with standard iac conf from terraform
now : we are looking at the combination of arm and terraform to achieve this issue which is non confient.
P

**Comment by andreasasujacgi** [comment]
While waiting for this, I temporarily use AzDO pipeline task AzureAppServiceSettings@1 to set the slot variables. But I'm definitely waiting for this feature.

**Comment by ryangopuff** [comment]
> If I could make a suggestion on this, I think it would be the most helpful if we could set sticky settings using the same api as defined now but with the option to provide a map of maps for the settings instead of just a map of strings. For example, if I just wanted to set app settings normally (without slot setting checked off), then it could be:
> 
> ```terraform
> app_settings = {
>   "some_setting" = "some value"
> }
> ```
> 
> and if I wanted to make that sticky then I could change it to:
> 
> ```terraform
> app settings = {
>   {
>     "name" = "some_setting"
>     "value" = "some value"
>     "slot_setting" = true
>   }
> }
> ```
> 
> I believe this lines up with how arm handles it as well so it's consistent across that and I would think this prevents breaking the original usage.

The force is strong with this one ;)

**Comment by phekmat** [comment]
I initially liked the "map" suggestion, but having just implemented this via ARM, it might become unwieldy for more complex deployments.

The REST API only has a single `SlotConfigNames` that's attached to the app service. As proposed, it would be impossible to have different sets of configuration settings as deployment slot settings (e.g. some settings may exist on the staging slot, but not the production slot).

With the improvements in recent versions of terraform (for/for_each, specifically), it's straightforward to have your app settings definition be a map (e.g. in a `locals` block) that's transformed for use in the resource's `app_settings` block and a future `slot_settings` block.

**Comment by ngocketit** [comment]
Has anyone come up with a workaround while waiting for this, for example, using Arm template?

**Comment by phekmat** [comment]
> 
> 
> Has anyone come up with a workaround while waiting for this, for example, using Arm template?

The issue description has an ARM template that looks basically the same as what I came up with. You could also use the newer https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment if you don't want to have to join/split the names

**Comment by ngocketit** [comment]
> > Has anyone come up with a workaround while waiting for this, for example, using Arm template?
> 
> The issue description has an ARM template that looks basically the same as what I came up with. You could also use the newer https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment if you don't want to have to join/split the names

My bad. I didn't pay enough attention to the description. Thanks @phekmat

**Comment by SadokLadhari** [comment]
@tombuildsstuff any news please ?

**Comment by sayandaw** [comment]
Any Update?
Still cant define a variable as "Slot setting"

**Comment by lukepfeiffer10** [comment]
Looking at the linked PR it looks like this feature is almost ready to go. Any updates on getting this merged in to a release?

@zhcli

**Comment by npyzza** [comment]
When can we expect this getting merged into a release?

**Comment by fgbaezp** [comment]
Is this happening anytime soon?

**Comment by ventil8** [comment]
Is this available yet?

**Comment by lukaskolafa** [comment]
this feature is very much needed :-) pls pls pls, put prio on this.. thx

**Comment by josh-samuel** [comment]
Any news on this?
