### ISSUE TITLE
Support for enabling Azure Defender for resources via terraform

### ISSUE THREAD

**Issue by rdelgado-incomm** [hashicorp/terraform-provider-azurerm#14409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I don't believe it is possible to enable Microsoft Defender for cloud via terraform. 
https://docs.microsoft.com/en-au/azure/defender-for-cloud/defender-for-cloud-introduction

Can we add some terraform to do this?

### New or Affected Resource(s)

* azurerm_azure_defender (new)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @rdelgado-incomm 

As mentioned in the linked documentation, these have recently been renamed from Azure Security Center, which is supported in the `azurerm_security_center_*` resources - as such I believe support for this is already available in the Azure provider? If there's specific functionality that's missing feel free to open a feature request for that specially and we can take a look - but since I believe this is already available I'm going to close this issue for the moment.

Thanks!

**Comment by rdelgado-incomm** [comment]
Will there be some refactoring that occurs @tombuildsstuff in the terraform provider?  I can open a separate issue if required.  It was not immediately clear to me and after scouring the internet for some time I was not able to come up with a solution for the above.

**Comment by tombuildsstuff** [comment]
@rdelgado-incomm unfortunately the products been renamed multiple times, whilst we could rename them in Terraform each time, tbh that's a lot of churn for users so we tend to do so only when there's value in it (e.g. the old name is misleading, in the case of App Service -> Web App).

Feel free to open an issue specifically if there's functionality missing, or I think more to your point of that we should also call out that this is also named "Azure Defender" now (at least in the documentation, something along the lines of `Azure Defender, formally Azure Security Center ..`) - if that answer your question? :)

**Comment by rdelgado-incomm** [comment]
Could you guys at least update the documentation such that we know that the referenced terraform applies to azure defender?  That would be sufficient for now at least.

**Comment by rdelgado-incomm** [comment]
I have another question on this @tombuildsstuff - I found a blade today in azure that allows you to turn on azure defender for an entire resource group.  https://portal.azure.com/#blade/Microsoft_Azure_Security/EnvironmentSettingsBlade

Any chance there is terraform for this?  I was looking at the resource configuration docs: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group  

Is there a place to configure turning on Azure Defender for an entire resource group?
