### ISSUE TITLE
BUG: subscription_id provider property is not enforcing the subscription of the provider.

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-azurerm#14422]
When I set the `subscription_id` parameter to the `azurerm` provider, it is not followed if I set another subscription in the az cli.

This is a bug, not a configuration issue.

Followup to closed https://github.com/hashicorp/terraform-provider-azurerm/issues/13830 and https://github.com/hashicorp/terraform-provider-azurerm/issues/14415

**Comment by tombuildsstuff** [comment]
Closing in favour of #14415
