### ISSUE TITLE
Azure Guest OS Patching Documenation Update

### ISSUE THREAD

**Issue by amarkulis** [hashicorp/terraform-provider-azurerm#14421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

![image](https://user-images.githubusercontent.com/26640711/144262336-130d04f6-d691-499e-b2cf-a71c0109d845.png)

In Azure Guest OS Automatic patching is officially released.  Can the documentation and API be updated to reflect that?

**Comment by programmerdeeksha** [comment]
Hey @amarkulis !
I would like to work on this issue. Can I ?

**Comment by amarkulis** [comment]
@programmerdeeksha go for it!

**Comment by atombrella** [comment]
@mbfrahry Could you please close this issue?

**Comment by rcskosir** [comment]
Closing issue with #14589
