### ISSUE TITLE
`azurerm_subnet_network_security_group_association` should wait for all `azurerm_network_security_rule` objects to be created first

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azurerm#14434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_subnet_network_security_group_association`
* `azurerm_network_security_rule`
* `azurerm_network_security_group`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "nsg" {
  name                = "testnsg" 
  location            = azurerm_resource_group.nsg.location
  resource_group_name = azurerm_resource_group.nsg.name
}

resource "azurerm_subnet_network_security_group_association" "nsg-association" {
  subnet_id                 = azurerm_subnet.subnet.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

resource "azurerm_network_security_rule" "nsg_inbound_100" {
  name                        = "Rule_1"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_address_prefix       = "ApiManagement"
  source_port_range           = "*"
  destination_address_prefix  = "VirtualNetwork"
  destination_port_range      = "3443"
  resource_group_name         = azurerm_resource_group.rg.name
  network_security_group_name = azurerm_network_security_group.nsg.name
}
```

### Expected Behaviour

The NSG is created
The rules in the NSG are created
The NSG is associated with the subnet

### Actual Behaviour

The NSG is created
The rules in the NSG are created at the same time as the subnet association. 

This leads to errors such as 

- NSG linked to AppGateway subnet failes (e.g. the API checks that the NSG has certain rules before it can be linked - however these rules are still been added)
- Services behaving in unexpected ways as the NSG rules are not "complete" at the time its linked to the subnet.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by aristosvo** [comment]
Hi @bubbletroubles! Thanks for your question.

This seems like a good use case for `depends_on`:

```hcl

resource "azurerm_network_security_group" "nsg" {
  name                = "testnsg" 
  location            = azurerm_resource_group.nsg.location
  resource_group_name = azurerm_resource_group.nsg.name
}

resource "azurerm_subnet_network_security_group_association" "nsg-association" {
  subnet_id                 = azurerm_subnet.subnet.id
  network_security_group_id = azurerm_network_security_group.nsg.id

  depends_on = [azurerm_network_security_rule.nsg_inbound_100]
}

resource "azurerm_network_security_rule" "nsg_inbound_100" {
  name                        = "Rule_1"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_address_prefix       = "ApiManagement"
  source_port_range           = "*"
  destination_address_prefix  = "VirtualNetwork"
  destination_port_range      = "3443"
  resource_group_name         = azurerm_resource_group.rg.name
  network_security_group_name = azurerm_network_security_group.nsg.name
}
```

Would that work for you?

**Comment by bubbletroubles** [comment]
The depends_on does work, but if the NSG has many rules, the depends_on block gets very large.

**Comment by aristosvo** [comment]
As this is very specific for your use case, it is not something the `azurerm` provider can easily support for the construction you're currently using.

Another solution might be to define the rules inside the `azurerm_network_security_group`. Would that work in your situation?

```hcl
resource "azurerm_network_security_group" "example" {
  name                = "example-nsg"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}
```

**Comment by CorrenSoft** [comment]
Another idea: Put the NSG and its rules inside of a module, and use that module in depends_on.

**Comment by bubbletroubles** [comment]
Thanks all. The suggestions will work around the issue. Closing the ticket
