### ISSUE TITLE
Azure synapse {managed_virtual_network_enabled = true} does not correctly set up virtual network

### ISSUE THREAD

**Issue by uceimmp** [hashicorp/terraform-provider-azurerm#14444]
### Terraform Version

```
1.1.0
```

### Terraform Configuration Files

```terraform
resource "azurerm_synapse_workspace" "example" {
  name                                                      = "example"
  resource_group_name                                       = azurerm_resource_group.example.name
  location                                                  = var.location
  storage_data_lake_gen2_filesystem_id                      = azurerm_storage_data_lake_gen2_filesystem.example_filesystem.id
  sql_administrator_login                                   = "sqladminuser"
  sql_administrator_login_password                          = random_password.synapse-sql-password.result
  managed_virtual_network_enabled                           = true

  aad_admin {
    login     = "AD Admin"
    object_id = "var.object_id"
    tenant_id = var.tenant_id
  }

  azure_devops_repo {
    account_name    = "example"
    branch_name     = var.git_config["branch_name"]
    project_name    = "Example"
    repository_name = "example"
    root_folder     = "/"
  }
}
```

### Expected Behavior

Virtual network should have been successfully created in portal

### Actual Behavior

Applies successfully and Managed Network is enabled on Portal  however, virtual network is disabled inside Synapse workspace (as shown in screenshot attached)

### References
<img width="332" alt="Screenshot 2021-12-02 at 13 56 09" src="https://user-images.githubusercontent.com/32641643/144440878-bdfb3001-7eb5-4528-a661-6e87c0cf112b.png">

**Comment by ms-henglu** [comment]
@uceimmp Hello, I took a look at this, but couldn't find the `Virtual network configuration` which is in the attached screenshot. Would you please share me more details about how to find this property? Thanks!

**Comment by jkososki** [comment]
@ms-henglu I am experiencing the same behavior.  The property is from the default integration runtime that is deployed with the workspace (AutoResolveIntegrationRuntime).  Hovering over the Information icon provides a note that the workspace is not enabled for virtual network.  The Virtual network config is disabled for all new integration runtimes as well.  Also - the "Managed Private Endpoints" are disabled.

Thank you for your help!

![image](https://user-images.githubusercontent.com/23581784/152095734-d0bf59be-4975-4237-80d9-714f5135fac8.png)
![image](https://user-images.githubusercontent.com/23581784/152096198-026c879a-c807-4d6b-a082-a82142e2ff3e.png)
![image](https://user-images.githubusercontent.com/23581784/152095953-8319b107-cdf5-4c13-a703-b2cf5043eec7.png)

**Comment by jkososki** [comment]
from the log output

```2022-02-02T10:31:59.976-0600 [DEBUG] provider.terraform-provider-azurerm_v2.94.0_x5: AzureRM Request: 
PUT /subscriptions/########-####-#########-############/resourceGroups/rg-###-#######/providers/Microsoft.Synapse/workspaces/##########?api-version=2021-03-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.17.5 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v61.3.0 synapse/2021-03-01 HashiCorp Terraform/1.1.4 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/2.94.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 412
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: ########-####-#########-############
Accept-Encoding: gzip

{"identity":{"type":"SystemAssigned"},"location":"centralus","properties":{"defaultDataLakeStorage":{"accountUrl":"https://synws#########.dfs.core.windows.net","filesystem":"default"},"managedResourceGroupName":"rg-###-#######_synmg","managedVirtualNetwork":"default","publicNetworkAccess":"Enabled","sqlAdministratorLogin":"admin######","sqlAdministratorLoginPassword":"###################"},"tags":{}}: timestamp=2022-02-02T10:31:59.976-0600
2022-02-02T10:32:02.133-0600 [TRACE] dag/walk: vertex "module.workspace (close)" is waiting for "module.workspace.azurerm_synapse_workspace.syn_workspace"
2022-02-02T10:32:02.133-0600 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" is waiting for "module.workspace.azurerm_synapse_workspace.syn_workspace"
2022-02-02T10:32:02.742-0600 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)"
2022-02-02T10:32:05.342-0600 [DEBUG] provider.terraform-provider-azurerm_v2.94.0_x5: AzureRM Response for https://management.azure.com/subscriptions/########-####-#########-############/resourceGroups/rg-###-#######/providers/Microsoft.Synapse/workspaces/##########?api-version=2021-03-01: 
HTTP/2.0 201 Created     

```

**Comment by jkososki** [comment]
I don't think the issue is a Terraform issue.  After some research and testing I've found that this behavior occurs when deploying a workspace with the repository configuration.  I was able to duplicate the behavior by deploying a workspace using the Azure REST API and a Bicep equivalents to the terraform in the original report.

I was able to resolve issue with the following steps:
- create an empty repository and initialize it with a readme
- deploy the workspace (tf/rest/bicep)
- open the workspace and navigate to the management section, then the git configuration. 
  - edit the settings 
  - check "import existing resources to the repository"  (i was importing into the 'main' branch)

Once this was complete everything behaved normally.  Additionally - this step pushes all the default objects to your repository.  This doesn't happen with the portal deployment because the problem is also resolved when manually linking and choosing the option to import.

**Comment by ms-henglu** [comment]
Hi @jkososki , thanks for the investigation, it helps a lot!

Hi @uceimmp, would you please try above steps `import existing resources to the repository`, see if it could solve the problem?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
