### ISSUE TITLE
key_vault { purge_soft_delete_on_destroy = false } breaks soft-deleted key recovery

### ISSUE THREAD

**Issue by db0** [hashicorp/terraform-provider-azurerm#14442]
When trying to create a VM disk encryption sets in azure using terraform, I'm running into a situation where no matter my approach, terraform will fail in some instances.

Specifically, if I delete an encryption key from an azure keyvault and then later on try to recreate one with the same name, if the following is set

```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}
```
then terraform will always fail with the following:

```
azurerm_key_vault_key.disk_encryption[5]: Creating...
╷
│ Error: Creating Key: keyvault.BaseClient#CreateKey: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Key vmname-custom-disk-encryption is currently in a deleted but recoverable state, and its name cannot be reused; in this state, the key can only be recovered or purged." InnerError={"code":"ObjectIsDeletedButRecoverable"}
│ 
│   with azurerm_key_vault_key.disk_encryption[5],
│   on encryption.tf line 12, in resource "azurerm_key_vault_key" "disk_encryption":
│   12: resource "azurerm_key_vault_key" "disk_encryption" {
```

If However, I have the following provider

```
provider "azurerm" {
  features {}
}
```

Then the key will be recovered and reused automatically.

Unfortunately, if I do not put `purge_soft_delete_on_destroy = false`, then terraform will instead fail during `azurerm_key_vault_key` resource destroy with this error

```
│ Error: purging of Key "vmname-custom-disk-encryption" (Key Vault "https://keyvaultname.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedKey: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after 
the retention period has passed.\r\nVault: keyvaultname;location=westeurope"
```

which is expected. However this set of behaviours, ensures that a terraform destroy/create operation will fail no matter what.

### Terraform Version

```
Terraform 1.0.11
azurerm 2.86.0
```

### Expected Behavior

Azure keyvault soft-deleted key should be automatically recovered when discovered, while `purge_soft_delete_on_destroy = false`

### Actual Behavior

Terraform fails when it tries to create a key with the same name as a soft-deleted key when `purge_soft_delete_on_destroy = false`, but succeeds when `purge_soft_delete_on_destroy = true`

**Comment by tombuildsstuff** [comment]
hi @db0 

Thanks for opening this issue.

Support for more granular purge/recovery options is being tracked in #10273, as such rather than having multiple issues open tracking the same thing - I'm going to close this issue in favour of #10273 for the moment - would you mind subscribing to that issue for updates?

Thanks!

**Comment by db0** [comment]
It does not look like the issue you linked is covering the bug I posted. 

purge_on_delete = false, should not make terraform incapable of recovering keys. It doesn't matter if it's a less granular setting. At moment, terraform usage with keys is broken, regardless of that setting.

**Comment by tombuildsstuff** [comment]
@db0 more granular purge/recovery options will fix this by allowing users to opt-into recovering keys if needs be, so that'll fix this issue. For the moment you can opt into this across all Key Vault resources - or purge items within the Key Vault when they're deleted - that's unfortunately the design of the Key Vault service as it exists today (that you can't recreate a soft-deleted key without recovering it).

**Comment by db0** [comment]
But it works if this setting is true! Azure doesn't allow purges anyway, so if this setting is true Terraform is acting as it should and recovers the key

**Comment by tombuildsstuff** [comment]
@db0 Azure does allow purging of both the Key Vault and it's contents, depending on the scenario used/permissions available - unfortunately Disk Encryption Sets require purge protection on the Key Vault however the items nested within that can be purged/recovered iirc.

**Comment by db0** [comment]
It's impossible to purge keys when deleting them. Azure has blocked this functionality. This is exactly why Terraform fails whatever I do at the moment. This is clearly a bug on azurerm provider that is unrelated to the other issue.

Test it yourself. Make an encryption key and soft delete it. Then try to create the same key with Terraform with the purge on delete set to off. It will fail,even though that setting has nothing to do with *recovering* keys.
