### ISSUE TITLE
Error parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

### ISSUE THREAD

**Issue by samuelhornby** [hashicorp/terraform-provider-azurerm#14456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 Terraform version 1.0.5, AzureRM version 2.0

### Affected Resource(s)

* `azurerm_user_assigned_identity`

### Terraform Configuration Files

```
resource "azurerm_user_assigned_identity" "agw_id" {
  location            = var.location
  resource_group_name = azurerm_resource_group.core_rg.name
  name = "agw-dcmp-${var.env}-${var.region_code}"
}


resource "azurerm_public_ip" "pip_agw" {
  name                = "pip-agw-dcmp-${var.env}-${var.region_code}"
  location            = var.location
  resource_group_name = azurerm_resource_group.core_rg.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

locals {
  frontend_port_name             = "feport-https"
  frontend_port_name_http        = "feport-http"
  frontend_ip_configuration_name = "feip-agw-dcmp-${var.env}-${var.region_code}"
}


resource "azurerm_application_gateway" "core_agw" {
  name                = "agw-dcmp-${var.env}-${var.region_code}"
  location            = var.location
  resource_group_name = azurerm_resource_group.core_rg.name

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 1
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.agw_id.id]
  }

  gateway_ip_configuration {
    name      = "gateway-ip-config"
    subnet_id = azurerm_subnet.agw.id
  }
  ....

  depends_on = [
    azurerm_key_vault_access_policy.agw_cert_access
  ]
}
```

AKS with managed identity
```
resource "azurerm_kubernetes_cluster" "core_aks" {
  name                    = "aks-private-dcmp-${var.env}-${var.region_code}"
  resource_group_name     = azurerm_resource_group.core_rg.name
  location                = var.location
  kubernetes_version      = "1.20.7"
  dns_prefix              = "dns-private-dcmp-${var.env}-${var.region_code}"
  private_cluster_enabled = true
  private_dns_zone_id     = "System"

  default_node_pool {
    name                = "pool1"
    vm_size             = "Standard_B2ms"
    enable_auto_scaling = false
    node_count          = 1
    type                = "VirtualMachineScaleSets"
    vnet_subnet_id      = "${azurerm_virtual_network.core_vnet.id}/subnets/snet-aks-dcmp-${var.env}-${var.region_code}"
  }

  network_profile {
    network_plugin     = "azure"
    network_policy     = "calico"
    docker_bridge_cidr = "172.17.0.1/16"
    service_cidr       = "10.28.0.0/16"
    dns_service_ip     = "10.28.0.10" 
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control {
    enabled = true
    azure_active_directory {
      managed            = true
      azure_rbac_enabled = true
    }
  }
  depends_on = [
    azurerm_subnet.aks
  ]
}

```

### Debug Output
 Error: parsing "/subscriptions/REMOVED/resourcegroups/REMOVED/providers/Microsoft.ManagedIdentity/userAssignedIdentities/agw-dcmp-dev-sa": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

Error: parsing "/subscriptions/REMOVED/resourcegroups/MC_REMOVED/providers/Microsoft.ManagedIdentity/userAssignedIdentities/aks-private-dcmp-dev-sa-agentpool": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

### Expected Behaviour
This was running with no error messages earlier today, no changes to these sections of terraform were made before the error started occurring. 

### Steps to Reproduce
try to deploy a user assigned identity with app gateway. (This is also failing with my AKS cluster system assigned identity which is in terraform.  The error message is the same with a different Microsoft.ManagedIdentity path.)

**Comment by jiege3324** [comment]
The same problem, when will it be solved? An error will be reported on version 2.88, and the old version is normal

**Comment by satheeshpayoda** [comment]
Same issue for me. We are getting this error even when we try to import the AKS resource into TF state.

I'm on 2.88.0 version.

Output from Import Command:
```
module.aks.azurerm_kubernetes_cluster.project_aks: Importing from ID "/subscriptions/xxx-x-x-x--x-x-x-x-x/resourcegroups/project-dev/providers/Microsoft.ContainerService/managedClusters/project-aks-dev"...
module.aks.azurerm_kubernetes_cluster.project_aks: Import prepared!
  Prepared azurerm_kubernetes_cluster for import
module.aks.azurerm_kubernetes_cluster.project_aks: Refreshing state... [id=/subscriptions/xxx-x-x-x--x-x-x-x-x/resourcegroups/project-dev/providers/Microsoft.ContainerService/managedClusters/project-aks-dev]
╷
│ Error: parsing "/subscriptions/xxx-x-x-x--x-x-x-x-x/resourcegroups/MC_project-dev_project-aks-dev_centralindia/providers/Microsoft.ManagedIdentity/userAssignedIdentities/project-aks-dev-agentpool": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"
│ 
│ 
╵
```

**Comment by santhoshmaidam** [comment]
Same issue for me as well. We are using v2.88.0.

parsing "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxx/resourcegroups/Testproject-sampletestservice-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/Testproject-sampletestservice-rg-uami": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

**Comment by themonaminor** [comment]
╷
│ Error: parsing "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourcegroups/MC_xxxxxxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxxxxxxxxxxxxxxxxxxxx": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"
│
│   with azurerm_kubernetes_cluster.aks,
│   on main.tf line 164, in resource "azurerm_kubernetes_cluster" "aks":
│  164: resource "azurerm_kubernetes_cluster" "aks" {



getting this error in terraform azurerm provider version 2.88.0

kindly look

**Comment by mivica** [comment]
Same here as of this morning. AzureRM provider version 2.88.0.

Error: parsing "/subscriptions/xxxxxxxxxxxxxxx/resourcegroups/xxxxxxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxxxxxxxx": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

**Comment by RajputDeepak** [comment]
facing the similar error for managed identity.Azure rm version 2.46.0

**Comment by MarekStrejczek-TomTom** [comment]
Cannot use remote AKS state created pre-2.88 in a module that is on 2.88.0 azurerm module.

**Comment by lupass93** [comment]
Same Problem with AKS, AAG and AGIC integration. The problem is on kubelet identity. It is a bug of new azureRM provider version?

**Comment by jpmadureira** [comment]
Downgrading temporarily to `2.87.0` seems to work.

**Comment by besha100** [comment]
We just faced the same issue :(

**Comment by himeshbhojwani** [comment]
2.86 is working

**Comment by deen-nitj** [comment]
i am also having the same issue, getting the error as mentioned below.

Error: parsing "/subscriptions/XXXXXX/resourcegroups/YYYY/providers/Microsoft.ManagedIdentity/userAssignedIdentities/ZZZZ": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

when its going to resolve?

**Comment by robin-wayve** [comment]
I am still getting the issue after 2.88.1 on `azurerm_user_assigned_identity` resources.
