### ISSUE TITLE
Support for Azure Keyvault key rotation and rotation policy

### ISSUE THREAD

**Issue by knutejoh** [hashicorp/terraform-provider-azurerm#14471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure KeyVault has released a feature for key rotation using policies, and a new set of access policies to set, get and rotate keys. 

### New or Affected Resource(s)

* azurerm_key_vault_access_policy

![image](https://user-images.githubusercontent.com/5584917/144621953-8a8c363c-e287-4591-ad1a-313e43f29197.png)

* azurerm_key_vault
* azurerm_key_vault_key

Probable new resource
* azurerm_key_vault_key_rotation_policy

![image](https://user-images.githubusercontent.com/5584917/144620766-1b947d76-4cff-4a9e-81b3-c7f1ebf739f0.png)

### Potential Terraform Configuration
```

### References



* #0000

**Comment by x509cert** [comment]
Hey Folks, I want to add a little context. I work at Microsoft doing Azure security, we're going to push this feature heavily from a compliance perspective. If there's anything I can do to expedite this, or provide info, please let me know.

**Comment by Gill-Bates** [comment]
This feature is still Preview and Subject of Chance. I can imagine, that Terraform will support it after this feature is GA.

**Comment by lkurzyniec** [comment]
The feature is GA.
https://azure.microsoft.com/en-us/updates/automated-key-rotation-in-azure-key-vault-is-now-available/

**Comment by cpc-dossaa** [comment]
This feature is no longer in preview. When can we expect a release that will support this?

Reference:
https://docs.microsoft.com/en-us/azure/key-vault/keys/how-to-configure-key-rotation

**Comment by lkurzyniec** [comment]
Hi @tombuildsstuff, any ETA for that feature?

**Comment by DaleyKD** [comment]
I need to be able to add these permissions to an `azurerm_key_vault_access_policy` ASAP. Any update?

**Comment by lkurzyniec** [comment]
@DaleyKD as a workaround, we are using `null_resource` with `az keyvault set-policy`. Maybe that helps you in ASAP situation.

**Comment by mclacore** [comment]
I need to be able to set the `azurerm_key_vault_key` to auto-rotate upon expiry so we:
* Meet compliance standards
* Don't break infra with expiring keys that don't auto-rotate

**Comment by aristosvo** [comment]
@tombuildsstuff Could we generate an SDK for one of the [key vault specs which support this](https://github.com/Azure/azure-rest-api-specs/search?q=rotationPolicy)?

I can pick this up if the SDK is available.

**Comment by aristosvo** [comment]
Seems blocked on Azure SDK Track 1 (which is not generated/updated anymore) and no support for data plane specs yet in https://github.com/hashicorp/go-azure-sdk/issues/118

**Comment by highvibes95** [comment]
> @DaleyKD as a workaround, we are using `null_resource` with `az keyvault set-policy`. Maybe that helps you in ASAP situation.

Can you please suggest how you are implementing az keyvault key rotation using null resource. I am not able to get it.

**Comment by lkurzyniec** [comment]
Sure, but still it would be better to push forward blocker ;)

```hcl
resource "azurerm_key_vault_key" "key_vault_key" {
  name         = var.name
  key_vault_id = var.key_vault_id

  key_type = var.key_type
  key_size = var.key_size
  key_opts = var.key_opts

  tags = var.tags
}

resource "null_resource" "rotation_policy" {
  triggers = {
    key_name        = azurerm_key_vault_key.key_vault_key.name
    key_vault_name  = basename(var.key_vault_id)
    subscription_id = split("/", var.key_vault_id)[2]
  }

  provisioner "local-exec" {
    command = "json=$(cat \"${path.module}/rotation-policy-enabled.json\") && az keyvault key rotation-policy update -n \"${self.triggers.key_name}\" --vault-name \"${self.triggers.key_vault_name}\" --subscription '${self.triggers.subscription_id}' --value \"$json\""
  }

  provisioner "local-exec" {
    when    = destroy
    command = "json=$(cat \"${path.module}/rotation-policy-disabled.json\") && az keyvault key rotation-policy update -n \"${self.triggers.key_name}\" --vault-name \"${self.triggers.key_vault_name}\" --subscription '${self.triggers.subscription_id}' --value \"$json\""
  }
}
```

**Comment by aristosvo** [comment]
@lkurzyniec I'll try to circumvent the blocker by using a self generated version of Track 1, let's see how far that brings us!

**Comment by a-z-i-z** [comment]
@aristosvo I am continuously monitoring #19113 though but still wanted to check when should we expect this feature to get release ?

**Comment by aristosvo** [comment]
Hi @a-z-i-z ! I am working on the latest changes based on conversations I had with HC maintainers, just a bit limited in time.

**Comment by a-z-i-z** [comment]
@aristosvo Thank you for the heads up. 👍🏼

**Comment by mukundbajaj** [comment]
@aristosvo any updates on this feature being available? We would need this to configure the key rotation from the Terraform side.

**Comment by aristosvo** [comment]
@mukundbajaj This ultimately waits on a proper answer to https://github.com/Azure/azure-rest-api-specs/pull/21137#discussion_r1045555687 in PR https://github.com/Azure/azure-rest-api-specs/pull/21137

**Comment by scott1138** [comment]
I'm facing this problem myself, and I think our solution is going to be to create a wrapper module around the [azapi call for creating a key](https://learn.microsoft.com/en-us/azure/templates/microsoft.keyvault/2022-07-01/vaults/keys?pivots=deployment-language-terraform).  We don't want the user to have to figure out embedded JSON and what not, so we will simplify the inputs and interpolate the values.

**Comment by MattoHopkins** [comment]
Seems as tho there's been an update here: https://github.com/Azure/azure-rest-api-specs/pull/21137#issuecomment-1442608069

**Comment by aristosvo** [comment]
@MattoHopkins indeed, PR is updated with the latest API version, tests are passing.

🤞 Fingers crossed, but it could be merged soonish.
