### ISSUE TITLE
azurerm_web_application_firewall_policy - update `mode` argument documentation 

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azurerm#14482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Documentation for azurerm_web_application_firewall_policy doesn't say the valid values for the "mode" argument. 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_application_firewall_policy
### New or Affected Resource(s)

* azurerm_web_application_firewall_policy

### References

Valid values are "Prevention" or "Detection". I'm happy to update if this issue can be assigned to me. 

* #0000

**Comment by aristosvo** [comment]
Hi @bubbletroubles! I can assign you for sure!

Good luck!

**Comment by bubbletroubles** [comment]
Fixed by #15022
