### ISSUE TITLE
"Invalid URI for request" error when specifing azurerm_app_service.identity.identity_ids

### ISSUE THREAD

**Issue by rumatavz** [hashicorp/terraform-provider-azurerm#14485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/adamcoulteroz/azurehelpers v0.1.0
+ provider registry.terraform.io/bwoznicki/assert v0.0.1
+ provider registry.terraform.io/hashicorp/azuread v2.9.0
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.6.1
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

azurerm_app_service

### Terraform Configuration Files
```

terraform {
    required_providers {
        azurerm = {
            source = "hashicorp/azurerm"
            version = ">=2.76.0"
        }

        kubernetes = {
            source = "hashicorp/kubernetes"
            version = ">=2.5.0"
        }
    }
}

provider "azurerm" {
    subscription_id = ####

    tenant_id =###
	
	features {}
}

provider "azuread" {
    tenant_id = ###
}

resource "azuread_application" "app_registration" {
  display_name           = "tf_report"
  prevent_duplicate_names = true
}

data "azuread_client_config" "current" {}

resource "azurerm_resource_group" "tf-managed-resources" {
    name = "tf-report-rg"
    location = "North Europe"
}

resource "azuread_service_principal" "service_principal" {

  application_id               = azuread_application.app_registration.application_id
  app_role_assignment_required = false
  owners                       = [data.azuread_client_config.current.object_id]

  feature_tags {
    enterprise = true
  }
}

resource "azurerm_app_service_plan" "serviceplan" {
    name                = azurerm_resource_group.tf-managed-resources.name
    location            = "North Europe"
    resource_group_name = "tf-report-rg"
    kind                = "Linux"
    reserved            = true

    sku {
        tier = "Basic"
        size = "B1"
		}
}


resource "azurerm_app_service" "appservice" {
    name                = "tf-report"
    location            = "North Europe"
    resource_group_name = azurerm_resource_group.tf-managed-resources.name
    app_service_plan_id = azurerm_app_service_plan.serviceplan.id

    identity {
      type = "UserAssigned"
      identity_ids = [ azuread_service_principal.service_principal.object_id ] 
    }
}
```

### Debug Output

https://gist.githubusercontent.com/rumatavz/491c7cbe21a0164a0b47647749e796b8/raw/442bb6ca7906fe6fbc28253b4dd713897eba500f/gistfile1.txt

### Expected Behaviour

TF should apply without erorr

### Actual Behaviour

│ Error: parsing "01cadd59-2c2d-4ffa-921f-2626ecd56779": expected 8 segments within the Resource ID but got 1 for "01cadd59-2c2d-4ffa-921f-2626ecd56779"
│
│   with azurerm_app_service.appservice,
│   on report.tf line 75, in resource "azurerm_app_service" "appservice":
│   75:       identity_ids = [ azuread_service_principal.service_principal.object_id ]

or

parsing Azure ID: parse "790b825a-f63b-4b83-918a-8d7169c0b491": invalid URI for request

### Steps to Reproduce

1. `terraform apply`

**Comment by rumatavz** [comment]
I've found the solution. I should use azurerm_user_assigned_identity instead of azuread_service_principal.
But I think the docs should be improved to make this fact more clear.

**Comment by izvictor** [comment]
Hello @rumatavz ,
Can you please show me the final terraform sample to create a azurerm_user_assigned_identity with azuread_service_principal.service_principal in order to use it  identity_ids = for app service ?
I have a service principal that i try to add it to user managed identity for my web app.
Thank you very much for your help.
Best regards.
