### ISSUE TITLE
Re-creating a topic deletes the subscription, which is then not re-created despite having a dependancy

### ISSUE THREAD

**Issue by sonic1981** [hashicorp/terraform-provider-azurerm#14497]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.8
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.81.0
```

### Affected Resource(s)

* azurerm_servicebus_subscription
* azurerm_servicebus_topic

### Terraform Configuration Files

```hcl

resource "azurerm_servicebus_topic" "sendemails" {
  name                          = "identity.ssoexpiry.sendemails"
  resource_group_name           = var.rg.name
  namespace_name                = data.azurerm_servicebus_namespace.sb.name
  enable_express                = false
  enable_batched_operations     = true
  enable_partitioning           = true
  requires_duplicate_detection  = false
  support_ordering              = false
  max_size_in_megabytes         = 5120
}

resource "azurerm_servicebus_topic" "checkexpiry" {
  name                  = "identity.ssoexpiry.checkexpiry"
  resource_group_name   = var.rg.name
  namespace_name        = data.azurerm_servicebus_namespace.sb.name

  enable_partitioning   = false
  max_size_in_megabytes = 5120
  
}

resource "azurerm_servicebus_subscription" "ShouldShowBanner" {
  name                      = "Azure.Identity.SSOExpiry.Func.ShouldShowBanner"
  resource_group_name       = var.rg.name
  namespace_name            = data.azurerm_servicebus_namespace.sb.name
  topic_name                = azurerm_servicebus_topic.checkexpiry.name
  max_delivery_count        = 1
  enable_batched_operations = true
}
```

### Expected Behaviour

making a change to a topic that forces re-creation should re-create the subscription as well.

### Actual Behaviour

Should create the subscription along with the topic

### Steps to Reproduce

Upon changing `enable_partitioning ` from false to true. Terraform shows:
```
 ~ enable_partitioning                     = true -> false # forces replacement
```

Which is correct. The problem being when this topic is re-created the associated subscription (`ShouldShowBanner`) is not re-created forcing me to run `terraform apply` twice

**Comment by catriona-m** [comment]
Thanks for opening this @sonic1981. I tested this with the latest version of azurerm and it looks like this is now working as expected after the recent changes to `azurerm_servicebus_subscription` in 3.0. As such, I will now close this issue, however feel free to reopen this if you have this issue again. Thanks!
