### ISSUE TITLE
`azurerm_subnet_route_table_association` complain "InvalidResourceReference" due to incorrect upper case

### ISSUE THREAD

**Issue by lonegunmanb** [hashicorp/terraform-provider-azurerm#14510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_subnet_route_table_association`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  location = "westus"
  name     = "zjhe-vnet"
}

resource "azurerm_virtual_network" "vnet" {
  address_space       = ["10.0.0.0/16"]
  location            = "eastus"
  name                = "zjhe-vnet"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "private" {
  name                 = "private"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes = ["10.0.0.0/24"]
}

resource "azurerm_subnet" "public" {
  name                 = "public"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes = ["10.0.1.0/24"]
}

resource "azurerm_route_table" "rt" {
  location            = "westus"
  name                = "rt"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet_route_table_association" "private_association" {
  route_table_id = azurerm_route_table.rt.id
  subnet_id      = azurerm_subnet.private.id
}

resource "azurerm_subnet_route_table_association" "public_association" {
  route_table_id = azurerm_route_table.rt.id
  subnet_id      = azurerm_subnet.public.id
}
```

### Expected Behaviour

The route table been associated with subnet successfully.

### Actual Behaviour

╷
│ Error: updating Route Table Association for Subnet "public" (Virtual Network "zjhe-vnet" / Resource Group "zjhe-vnet"): network.SubnetsClient#CreateOr
Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /subscriptions/###########/resourceGroups/ZJHE-VNET/providers/Microsoft.Network/routeTables/RT referenced by resource /subscriptions/###########/resourceGroups/zjhe-vnet/providers/Microsoft.Network/virtualNetworks/zjhe-vnet/subnets/public was not found. Please make sure that the reference
d resource exists, and that both resources are in the same region." Details=[{"code":"NotFound","message":"Resource /subscriptions/###########/resourceGroups/ZJHE-VNET/providers/Microsoft.Network/routeTables/RT not found."}]
│
│   with azurerm_subnet_route_table_association.public_association,
│   on main.tf line 42, in resource "azurerm_subnet_route_table_association" "public_association":
│   42: resource "azurerm_subnet_route_table_association" "public_association" {
│
╵

### Steps to Reproduce

1. `terraform apply --auto-approve`

### Important Factoids

It seems like a service side bug which use incorrect upper case for route table id. Debugging with fiddler I captured the http request and response:

```shell
PUT https://management.azure.com/subscriptions/###########/resourceGroups/zjhe-vnet/providers/Microsoft.Network/virtualNetworks/zjhe-vnet/subnets/public?api-version=2021-02-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.17.4 (amd64-windows) go-autorest/v14.2.1 Azure-SDK-For-Go/v59.2.0 network/2021-02-01 HashiCorp Terraform/1.0.11 (+https://www.terraform.io) Terraform Plugin SDK/2.8.0 terraform-provider-azurerm/dev pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 536
Authorization: Bearer 
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: 9a90252a-df79-cd1f-634e-e7012f598f40
Accept-Encoding: gzip

{"id":"/subscriptions/###########/resourceGroups/zjhe-vnet/providers/Microsoft.Network/virtualNetworks/zjhe-vnet/subnets/public","name":"public","properties":{"addressPrefix":"10.0.1.0/24","delegations":[],"privateEndpointNetworkPolicies":"Enabled","privateLinkServiceNetworkPolicies":"Enabled","routeTable":{"id":"/subscriptions/###########/resourceGroups/zjhe-vnet/providers/Microsoft.Network/routeTables/rt"},"serviceEndpoints":[]},"type":"Microsoft.Network/virtualNetworks/subnets"}
```

As packet showed, the route table id in request is correct, but somehow, the response packet was:

```shell
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 732
Content-Type: application/json; charset=utf-8
Expires: -1
x-ms-request-id: c71fdc80-f1ff-4db9-a963-2d5fa0291090
x-ms-correlation-request-id: 9a90252a-df79-cd1f-634e-e7012f598f40
x-ms-arm-service-request-id: 2e5a507c-cccb-4a88-b8d4-333a324f63a9
Strict-Transport-Security: max-age=31536000; includeSubDomains
Server: Microsoft-HTTPAPI/2.0
Server: Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: 1199
x-ms-routing-request-id: SOUTHEASTASIA:20211207T095306Z:8f74a7a7-f878-4a6d-af32-9ae0e3e0f1f2
X-Content-Type-Options: nosniff
Date: Tue, 07 Dec 2021 09:53:06 GMT

{
  "error": {
    "code": "InvalidResourceReference",
    "message": "Resource /subscriptions/###########/resourceGroups/ZJHE-VNET/providers/Microsoft.Network/routeTables/RT referenced by resource /subscriptions/###########/resourceGroups/zjhe-vnet/providers/Microsoft.Network/virtualNetworks/zjhe-vnet/subnets/public was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.",
    "details": [
      {
        "code": "NotFound",
        "message": "Resource /subscriptions/###########/resourceGroups/ZJHE-VNET/providers/Microsoft.Network/routeTables/RT not found."
      }
    ]
  }
}
```

So the service side complained cannot find the route table, but in the id it returned the resource group name and route table name are both upper case. As `azurerm_route_table`'s [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/route_table) didn't mentioned that the table name must be upper case, I doubt it's a service side bug. I'll query the service for this issue.

### References

* #0000

**Comment by Igor-Golivets-cdw-ca** [comment]
Hi @lonegunmanb I have a very similar issue with `azurerm_subnet_route_table_association` but I'm doing a bit different actions to get those.
I'm trying to import the existing resources to the Terraform (subnets and RTs) and after successful import I get that "subnet associations must be recreated due to the difference in attribute" `route_table_id`:
`      ~ route_table_id = "/subscriptions/###########/resourceGroups/###########-rg/providers/Microsoft.Network/routeTables/###########-rt" -> "/subscriptions/###########/resourceGroups###########-RG/providers/Microsoft.Network/routeTables/###########-RT" # forces replacement`
So the problem is again the difference in the case, otherwise, the `route_table_id` is exactly the same.
The only workaround I found so far is to add ignore config to my `azurerm_subnet_route_table_association` resource, but that cannot be used as a permanent solution:
```
  lifecycle {
     ignore_changes = ["route_table_id"]
  }
```

**Comment by lonegunmanb** [comment]
Hi @Igor-Golivets-cdw-ca , I've asked the service but no response so far. I'll keep you updated when I got any progress, thanks for your sharing!

**Comment by lonegunmanb** [comment]
Hi @Igor-Golivets-cdw-ca , I've figured out my problem. It's due to incorrect location, my route table location is different with vnet's location and caused this error. After correct the location, everything was fine on my side. But still, the error message contains incorrect upper case for route table's name and resource group name. I'm closing this issue.

As for your case, would you please submit a new issue with a minimum code that could reproduce your problem and ping me there? I would like to try a fix for you.
