### ISSUE TITLE
Error: expanding `default_node_pool`: cannot change `node_count` when `enable_auto_scaling` is set to `true`

### ISSUE THREAD

**Issue by robertdeheer** [hashicorp/terraform-provider-azurerm#14522]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.82.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "test_vnet" {
  name                = "test_vnet"
  location            = "East US"
  resource_group_name = "myrg"
  address_space       = ["10.0.0.0/8"]
}

resource "azurerm_subnet" "test-subnet" {
  name                 = "test-subnet"
  address_prefixes     = ["10.240.0.0/16"]
  resource_group_name  = "myrg"
  virtual_network_name = azurerm_virtual_network.qa_vnet_dflorez_01.name
}

resource "azurerm_kubernetes_cluster" "test" {
  name                       = "test"
  location                   = "East US"
  dns_prefix                 = "test"
  enable_pod_security_policy = false
  kubernetes_version         = "1.21.2"
  resource_group_name        = "myrg"

  # Default pool with autoscaling to support upgrades
  default_node_pool {
    name                 = "nodepool01"
    orchestrator_version = "1.21.2"
    vm_size              = "Standard_DS2_v2"
    enable_auto_scaling = true
    node_count          = 3
    min_count           = 3
    max_count           = 4
    type                = "VirtualMachineScaleSets"

    upgrade_settings {
      max_surge = "33%"
    }

    vnet_subnet_id = azurerm_subnet.test-subnet.id
  }

  auto_scaler_profile {
    max_unready_nodes             = 1
    scale_down_unready            = "3m"
    scale_down_unneeded           = "20m"
    skip_nodes_with_system_pods   = false
    skip_nodes_with_local_storage = false
  }

  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }

  role_based_access_control {
    enabled = true
  }

  network_profile {
    load_balancer_sku = "Standard"
    network_plugin    = "azure"
  }
}
```

### Panic Output

│ Error: expanding `default_node_pool`: cannot change `node_count` when `enable_auto_scaling` is set to `true`
│ 
│   with azurerm_kubernetes_cluster.qa-htad-aks-01,
│   on azure_aks_vnet_htad.tf line 44, in resource "azurerm_kubernetes_cluster" "qa-htad-aks-01":
│   44: resource "azurerm_kubernetes_cluster" "qa-htad-aks-01" {

### Expected Behaviour

Apply should have run successfully and not made any changes since no changed were made to the terraform inputs and the cluster had not changed. 

### Actual Behaviour

Apply failed with the error above on several clusters. No change

### Steps to Reproduce

The issue is intermittent, so run apply several times if it succeeds. 
1. `terraform apply`

### Important Factoids

No

### References

* #0000

**Comment by orgads** [comment]
We also noticed the same issue. The cluster was auto-scaled from 1 to 3 nodes, but the tf file still has 1, so it tries to change `node_count` to 1 and fails with this error.

**Comment by DesislavaNPetrova** [comment]
Still the same behaviour. 
Could you please share any updates about it. Is there any plans to be fixed the issue?

**Comment by nla-gooddalton** [comment]
If you're using auto-scaling, which you are, then why do you need to specify the no. of nodes? Just remove `node_count` you're specifying `min_count` to achieve the same thing, unless i'm missing something?

If you want want to set the "node count" to 1 set `min_count` and `max_count` both to 1.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
