### ISSUE TITLE
Synapse setting role assignment and private endpoint on synapse analytics automatically removes disables VNET config 

### ISSUE THREAD

**Issue by uceimmp** [hashicorp/terraform-provider-azurerm#14539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 1.0.0
AzureRM: 2.84.0

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

resource "azurerm_synapse_managed_private_endpoint" "example_pvt_endpoint" {
  depends_on = [
    azurerm_synapse_workspace.example_synapse
  ]
  name                 = "example-storage-endpoint"
  synapse_workspace_id = azurerm_synapse_workspace.example_synapse.id
  target_resource_id   = module.example.id
  subresource_name     = "blob"
}

resource "azurerm_synapse_role_assignment" "example_sql_admin_role_assignment" {
  depends_on = [
    azurerm_synapse_workspace.example_synapse
  ]
  synapse_workspace_id = azurerm_synapse_workspace.example_synapse.id
  role_name            = "Synapse SQL Administrator"
  principal_id         = data.azuread_group.example.object_id
}

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14444

**Comment by ms-henglu** [comment]
@uceimmp , Hello, would you please share me more details about `removes disables VNET config`?
Are some properties got changed unexpectedly? If so, please share me the property names.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
