### ISSUE TITLE
Cannot enable NFS v3 in Azure storage account

### ISSUE THREAD

**Issue by AtwoodTM** [hashicorp/terraform-provider-azurerm#14540]
**Versions**
terraform: 1.0.11
azurerm provider: 2.88.1

**Error during apply:**
storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestPropertyValue" Message="The value 'True' is not allowed for property isNfsv3Enabled."

**Comment**
It looks like the bool value is being converted to a string before being sent to the Azure API.

**Resource code:**

```
resource "azurerm_storage_account" "sa" {
  access_tier               = "Hot"
  account_kind              = "StorageV2"
  account_replication_type  = "LRS"
  account_tier              = "Standard"
  allow_blob_public_access  = false
  enable_https_traffic_only = true
  is_hns_enabled            = true
  location                  = "eastus2"
  min_tls_version           = "TLS1_2"
  name                      = "mytest123456"
  nfsv3_enabled             = true
  resource_group_name       = "test"

  blob_properties {
    cors_rule {
      allowed_headers    = ["*"]
      allowed_origins    = ["*"]
      exposed_headers    = ["*"]
      allowed_methods    = ["DELETE", "GET", "HEAD", "MERGE", "POST", "OPTIONS", "PUT", "PATCH"]
      max_age_in_seconds = 300
    }

    delete_retention_policy {
      days = 365
    }
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    environment          = "test"
    firewall             = false
    managed-by-terraform = true
    product-group        = "test"
    region               = "eastus2"
  }
}
```

**Comment by jpmicrosoft** [comment]
@stephybun I am unable to recreate the issue. While running:
terraform versions 1.09, 1.1.1, 1.0.11
azurerm providers 2.88.1 and 2.90

The error I received was related to ACLs not the same. Once I added the network block with the deny it deploys.

![image](https://user-images.githubusercontent.com/48604544/147116565-578e8fe5-77cb-408c-ad9e-edcdf575a20a.png)

**Comment by marc-pensa** [comment]
This is related to https://github.com/hashicorp/terraform-provider-azurerm/issues/2977 - I was able to create the resource as @jpmicrosoft suggests with network rules in place, but subsequent terraform runs fail without an explicit IP added to the firewall rules. This has the added effect of breaking my Azure Pipelines that apply the terraform, and the workaround for trusted services doesn't work in this case (checking the box still shows No in the overview). The fix in the above link with private endpoints isn't possible here because in order to get NFS enabled, network rules must be included in the resource definition.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!

**Comment by rmacian** [comment]
I also tried with:
```
resource "azurerm_storage_account" "bloblogger" {
  name = local.storage_acc
  resource_group_name = local.resourcegroup
  location            = local.region
  nfsv3_enabled = true
  is_hns_enabled = true
  account_replication_type = "LRS"
  account_tier = "Standard"
  account_kind = "StorageV2"
  network_rules  {
    default_action = "Deny"
    virtual_network_subnet_ids = [data.azurerm_virtual_network.aks_vnet.id,azurerm_subnet.private.id,azurerm_subnet.public.id]
    ip_rules = ["195.235.92.0/23"]
  }
}
```
and this happened:
```
╷
│ Error: creating Storage Account (Subscription: "XXXX"
│ Resource Group Name: "nt-dev-rg"
│ Storage Account Name: "ntdevnfs"): storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: networkAcls.virtualNetworkRules[*].id. For more information, see - https://aka.ms/storagenetworkruleset"
```

**Comment by webstean** [comment]
This isn't a bug, you need to have the default action on a storage account with NFS set to "deny" by default as per below.
network_rules {
    ## Must be deny for NFS
    default_action = "Deny"
    bypass         = ["Logging", "Metrics", "AzureServices"]
    ip_rules       = ["0.0.0.0/0"]
}

**Comment by tombuildsstuff** [comment]
Closing since per @webstean's comment (and the API response `NetworkAcls default action must be set to Deny for NFS enabled account.`) - this is a configuration issue (where this has to be set to `default_action = "Deny"` for NFS) rather than a bug in the Provider.
