### ISSUE TITLE
terraform detects change in sql_filter of azurerm_servicebus_subscription_rule on every run

### ISSUE THREAD

**Issue by vanmash** [hashicorp/terraform-provider-azurerm#14559]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_servicebus_subscription_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_subscription_rule" "sbsr11" {
  name                = "rulename"
  resource_group_name = azurerm_resource_group.rg.name
  namespace_name      = azurerm_servicebus_namespace.sb.name
  topic_name          = azurerm_servicebus_topic.sbt.name
  subscription_name   = azurerm_servicebus_subscription.sbs.name
  filter_type         = "SqlFilter"
  sql_filter          = <<-EOT
    [NServiceBus.EnclosedMessageTypes] IN (
      'Events.Something.Updated'
    )
  EOT
}
```

### Expected Behaviour

Correctly detect no change in `sql_filter`.

### Actual Behaviour

Terraform detects a change to `sql_filter` whereas there is none.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by intellectualhonesty** [comment]
Hi @vanmash , I'd like to reproduce this issue with 3.0 provider on my side with the following code:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "zjhe-f14559"
  location = "West Europe"
}

resource "azurerm_servicebus_namespace" "example" {
  name                = "zjhe-f14559"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"

  tags = {
    source = "terraform"
  }
}

resource "azurerm_servicebus_topic" "example" {
  name         = "zjhe-f14559"
  namespace_id = azurerm_servicebus_namespace.example.id

  enable_partitioning = true
}

resource "azurerm_servicebus_subscription" "example" {
  name               = "zjhe-f14559"
  topic_id           = azurerm_servicebus_topic.example.id
  max_delivery_count = 1
}

resource "azurerm_servicebus_subscription_rule" "example" {
  name            = "zjhe-f14559"
  #  resource_group_name = azurerm_resource_group.example.name
  #  namespace_name      = azurerm_servicebus_namespace.example.name
  #  topic_name          = azurerm_servicebus_topic.example.name
  #  subscription_name   = azurerm_servicebus_subscription.example.name
  subscription_id = azurerm_servicebus_subscription.example.id
  filter_type     = "SqlFilter"
  sql_filter      = <<-EOT
    [NServiceBus.EnclosedMessageTypes] IN (
      'Events.Something.Updated'
    )
  EOT
}
````

It seems like 3.0 has deprecated the old arguments and using `subscription_id` as instead. I was unable to reproduce this issue by run plan after apply. Would you please try again with the latest provider? Thanks!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
