### ISSUE TITLE
Migrate resource from azurerm_virtual_machine to azurerm_windows_virtual_machine using winrm listener

### ISSUE THREAD

**Issue by cyprienruelle** [hashicorp/terraform-provider-azurerm#14562]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v1.0.7
* AzureRM Provider version: v2.88.1

### Description

Following documentation, we are changing the usage of azurerm_virtual_machine for azurerm_windows_virtual_machine.
We need to use the winrm listener.
According to [azurerm_virtual_machine resource documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#protocol), protocol of winrm listener can be HTTP or HTTPS in uppercase.
According to [azurerm_windows_virtual_machine resource documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#Protocol), protocol of winrm listener can be Http or Https in camelcase.

In order to have our infrastructure matching up-to-date code, we want to migrate from azurerm_virtual_machine to azurerm_windows_virtual_machine.

Code is updated accordingly:
```hcl
resource "azurerm_virtual_machine" "vm" {
# other mandatory config is done
  os_profile_windows_config {
    winrm {
      protocol = "HTTP"
    }
  }
}
```
Becomes:
```hcl
resource "azurerm_windows_virtual_machine" "vm" {
# other mandatory config is done
  winrm_listener {
    protocol = "Http"
  }
}
```

then we run terraform commands:
```bash
terraform state show azurerm_windows_virtual_machine.vm
# azurerm_windows_virtual_machine.vm:
resource "azurerm_windows_virtual_machine" "vm" {
...
    id                         = "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/MigrateWinVM"
...
}
terraform state rm azurerm_virtual_machine.vm
...
terraform import azurerm_windows_virtual_machine.vm "/subscriptions/XXXX/resourceGroups/XXXX/providers/Microsoft.Compute/virtualMachines/MigrateWinVM"
...
Import successful!
...
```

But next tf plan runs tells:
```bash
  # azurerm_windows_virtual_machine.vm must be replaced
-/+ resource "azurerm_windows_virtual_machine" "vm" {
...
      - winrm_listener { # forces replacement
          - protocol = "HTTP" -> null
        }
      + winrm_listener { # forces replacement
          + protocol = "Http"
        }
}
```

Next configuration is not valid (tf plan outputs an error):
```hcl
resource "azurerm_windows_virtual_machine" "vm" {
# other mandatory config is done
  winrm_listener {
    protocol = "HTTP"
  }
}
```

### Description / Feedback

case change should not be detected as # forces replacement.
OR
azurerm_windows_virtual_machine.winrm_listener.protocol should accept UPPERCASE configuration.

But you may have a better procedure to migrate from azurerm_virtual_machine to azurerm_windows_virtual_machine.
Can terraform 1.1.0 handle this ?

A quick action though is to update [azurerm_virtual_machine resource documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#protocol) : `(Required) Specifies the protocol of listener. Possible values are Http or Https.` which is a valid configuration.
That documentation fix will allow people to not have the same issue than me.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine

**Comment by tombuildsstuff** [comment]
In this case the resource should be normalising the protocol to `Http` (which is provided in the Azure SDK) here

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
