### ISSUE TITLE
Terraform adds defaulted included_path when no included_path is present

### ISSUE THREAD

**Issue by acence** [hashicorp/terraform-provider-azurerm#14561]
### Terraform (and AzureRM Provider) Version

* `terraform_version: 0.13.5`
* `azurerm_2.80.0`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_sql_container" "frontendfeeds-failed" {
  name                = "frontendfeeds-failed"
  resource_group_name = var.rsg_name
  account_name        = azurerm_cosmosdb_account.sqlcosmosdbacc.name
  database_name       = azurerm_cosmosdb_sql_database.notifications_cosmosdb.name
  partition_key_path  = "/id"
  indexing_policy {
    indexing_mode = "Consistent"
    excluded_path {
      path = "/*"
    }
  }
}
```

### Expected Behaviour

Should create a container where everything is excluded from indexing

### Actual Behaviour

Failed with error:
Error: updating Cosmos SQL Container "frontendfeeds-failed" (Account: "***", Database: "***"): only one of included_path or excluded_path may include the path "/*"

### Steps to Reproduce

Run terraform apply

**Comment by markjbrown** [comment]
This is normal behavior for the service. You have to define you index policy with the includedPaths and excludedPaths arrays. If you omit either, the service will inject them because it relies on these being present and for excludedPaths it will also inject the _etag path as these should always be excluded anyway.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
