### ISSUE TITLE
 Error: ID was missing the `securityContacts` element, since v2.88.0

### ISSUE THREAD

**Issue by martenvd** [hashicorp/terraform-provider-azurerm#14569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.0
provider registry.terraform.io/hashicorp/azurerm v2.89.0

But the same issue was found with azurerm 2.88.0 and 2.88.1.

### Affected Resource(s)

* `azurerm_security_center_contact `

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_contact" "contact" {
  count = (var.production && (length(local.team_email)) > 0) ? 1 : 0

  email = local.team_email

  alert_notifications = true
  alerts_to_admins    = true

  provider = azurerm.target-subscription
}
```

### Debug Output

https://gist.github.com/martenvd/332a0af454c1bcde192d926391bbb5df 

### Actual Behaviour

plan fails with `Error: ID was missing the ``securityContacts`` element.` 
In previous versions (up until 2.88.0), this error did not come up. Also when pinning the provider on version 2.87.0, it doesn't fail.

### Steps to Reproduce

`terraform plan`

**Comment by tombuildsstuff** [comment]
hey @martenvd

Thanks for opening this issue.

Out of interest were these resources created with an older version of Terraform/the Azure Provider, or imported into Terraform?

Thanks!

**Comment by martenvd** [comment]
Hi @tombuildsstuff 

Yes, these resources were created with an older version of the Azure Provider, although they were not created with an older version of Terraform itself.

**Comment by tombuildsstuff** [comment]
@martenvd got it, in which case this is a missing state migration, apologies for the bug here.

**Comment by fredflev** [comment]
Hi, just checking if this is supposed to be fixed in `2.91.0` since I am still getting after upgrading `hashicorp/azurerm requirement from ~> 2.87.0 to ~> 2.91.0`

![image](https://user-images.githubusercontent.com/42792052/148721147-75bea687-2547-40f0-a594-0639f800aa5b.png)

Or do I need to wait for `v2.92.0`? 

Thanks!

**Comment by koikonom** [comment]
Hey @martenvd ! I was looking at the debug information you provided and noticed that the ID of the resource is 
```            "id": "/subscriptions/******/providers/Microsoft.Security/securityContact/default1",```

I looked at the azure rest api specs and they never used `securityContact` as part of the resource ID, only `securityContacts`. I'm curious as to how this ended up in your state. Can you confirm if this was created by an older version of the azure provider of if it was imported into the terraform state?

**Comment by martenvd** [comment]
Hello @koikonom, the resource was indeed created with an older version of the azurerm provider.

**Comment by koikonom** [comment]
Hey @martenvd, 

Would it be possible to send us debug logs of running a terraform plan?

If not then please share the output of `az rest --debug -u https://management.azure.com/subscriptions/<yoursubscriptionid>/providers/Microsoft.Security/securityContact/default1`

**Comment by martenvd** [comment]
Hi @koikonom, when running your command I get the following output:
```
cli.azure.cli.core.azclierror: Bad Request({"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}})
az_command_data_logger: Bad Request({"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}})
```

When running the following command:
```
az rest --debug -u https://management.azure.com/subscriptions/****************/providers/Microsoft.Security/securityContact/default1?api-version=2020-01-01-preview
```
I get the following output:
https://gist.github.com/martenvd/e801e0c02c1d9f01155a0ae1566cd870

**Comment by tombuildsstuff** [comment]
@martenvd out of interest what happens when you run:

> az rest --debug -u https://management.azure.com/subscriptions/****************/providers/Microsoft.Security/securityContacts/default1?api-version=2020-01-01-preview

in particular, I'm wondering what `ID` field is being returned in the Azure API response here

**Comment by martenvd** [comment]
@tombuildsstuff the logs for that command are here:
https://gist.github.com/martenvd/2ec666ad2be408e9c1ace6be67e35da8

**Comment by fredflev** [comment]
On my side, since this is just a "contact" and not really a live resource we care about,  I solved this issue by removing the existing state and recreating it using the latest version of the provider. 

```console
terraform init (with azurerm-tw-2.92.0  and tf 1.1.3) 
terraform state rm azurerm_security_center_contact.main 
terraform apply -target='azurerm_security_center_contact.main'
```

I can confirm that the new state uses `securityContacts` in the ID field and not the misspelled `securityContact` we had in the old state.

**Comment by martenvd** [comment]
I have resolved my issue as well by refactoring the statefile with `securityContacts` instead of `securityContact` like @fredflev said.
