### ISSUE TITLE
azurerm_app_service_environment_v3 - page title typo

### ISSUE THREAD

**Issue by mikeclayton** [hashicorp/terraform-provider-azurerm#14570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

# Documentation Typo

The documentation for ```azurerm_app_service_environment_v3``` has the wrong title - it currently says ```azurerm_app_service_environment```.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/website/docs/r/app_service_environment_v3.html.markdown

**Comment by tombuildsstuff** [comment]
Fixed via #14571
