### ISSUE TITLE
r/managed_disk: support for platform encryption

### ISSUE THREAD

**Issue by jhabikal21** [hashicorp/terraform-provider-azurerm#14574]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would want to enable encryption for azurerm_managed_disk resources on Azure which uses Default Encryption using platform managed keys. However, terraform resource doesn't provide the feature, with just enabling encryption_settings, it throws below error:
`Error: creating/updating Managed Disk "acctestmd2" (Resource Group "TerraformTesting"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="DiskEncryptionKey is required for  if encryption is enabled."`

### New or Affected Resource(s)

* azurerm_managed_disk

### Potential Terraform Configuration

![Disk-encryption-Azure](https://user-images.githubusercontent.com/35531767/145587255-eaff6754-8b9b-447e-b213-7ea9207f2c14.png)

```
resource "azurerm_managed_disk" "copy" {
  name                 = "acctestmd2"
  location             = "West US 2"
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  # source_resource_id   = azurerm_managed_disk.source.id
  disk_size_gb         = "1"
  encryption_settings {
    enabled = true
  }
}
```

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#encryption_settings

* #0000

**Comment by myc2h6o** [comment]
Hi @jhabikal21 The property `encryption_settings` is used for [Azure Disk Encryption](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-overview).
The screenshot of Portal is Server-side disk encryption, which by default uses [Platform-managed key](https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption#platform-managed-keys). It is configured by [`disk_encryption_set_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#disk_encryption_set_id), When this property is not specified, platform-managed key will used. When specified, it will use the id of [disk_encryption_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/disk_encryption_set) as the custom-managed key.

By removing the `encryption_settings`, the disk should be able to set Encryption Type to "Encryption at-rest with a platform-managed key"
```
encryption_settings {
    enabled = true
}
```

**Comment by tombuildsstuff** [comment]
@myc2h6o we should remove the `enabled` field from that block since there's only one possible value fwiw

**Comment by myc2h6o** [comment]
Yeah make sense, I'll work on it.

**Comment by jhabikal21** [comment]
Is there any update on this @myc2h6o

**Comment by myc2h6o** [comment]
Hi @jhabikal21 I've opened a pr to deprecate the `enabled` property, which will be fully removed in 3.0 release. It's been changed from `Required` to `Optional` to keep backward compatibility. `disk_encryption_key` will be `Required` in 3.0 release (It is still `Optional` for backward compatibility). And to disable the ADE feature, one will remove `encryption_settings` block instead of setting `enabled` to false .

**Comment by aledeniz** [comment]
@myc2h6o any chance you could add in the documentation a sample to show how ADE encryption via encryption_settings is supposed to work? Both for 2.xx and 3.0 please?

**Comment by myc2h6o** [comment]
Hi @aledeniz I've added an example in the above pr https://github.com/hashicorp/terraform-provider-azurerm/pull/15317/commits/3f1eff474f7aeda20868bce2fff409f2b8cef3b7, the example will work with the new release only (`enabled` is not specified and take the default value of `true`). For older release, you just need to add `enabled = true` in `encryption_settings` block. Hope this will make it easier to use.

Also besides configuring the ADE on the managed disk, it can be configured on the Virtual Machine using the ADE VM Extension, which is more straightforward. It can also make the life easier when Key Encryption Key is used, as the extension will  set some tags which is required by the VM on the Disk Encryption Key. I've made another pr #15356 to add the examples as well.
![image](https://user-images.githubusercontent.com/10579712/153369204-7aff2e28-c38d-4626-b632-4915cf1d0d1b.png)

**Comment by myc2h6o** [comment]
I found a discussion around Azure Disk Encryption which recommended using the VM Extension instead. Although the properties can be specified on the Managed Disk itself, the encryption is finally done by the VM Extension instead. So the better way would be using the extension directly https://github.com/Azure/azure-sdk-for-go/issues/566#issuecomment-301205205

**Comment by tombuildsstuff** [comment]
@myc2h6o encryption using the VM Extension is deprecated in favour of using Disk Encryption

**Comment by myc2h6o** [comment]
I've checked some previous issues and found that we have moved to [Server-side Encryption](https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption) from Azure Disk Encryption (https://github.com/hashicorp/terraform-provider-azurerm/issues/486#issuecomment-580351484) starting from 2.0. For the platform encryption asked originally in this issue, `disk_encryption_set_id` in the below resources can be used: [azurerm_managed_disk](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#disk_encryption_set_id), [azurerm_linux_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#disk_encryption_set_id), [azurerm_windows_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#disk_encryption_set_id)

For the old Azure Disk Encryption, there is an [old example](https://github.com/hashicorp/terraform-provider-azurerm/tree/437e0e006da24a65fd85d1f5e9e4ad7cf926d513/examples/virtual-machines/virtual_machine/encrypt-running-linux-vm) triggering ARM template deployment to deploy the VM extension. Using `azurerm_virtual_machine_extension` #15356 can do the same thing. ([Linux extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/azure-disk-enc-linux), [Windows extension](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/azure-disk-enc-windows)). However, the extension creates unmanaged Secret in the Key Vault with various tags, and doesn't remove the Secret when deleting, which makes the it hard to manage within Terraform, I think using the new Server-side Encryption mentioned above would be a better way if possible.
