### ISSUE TITLE
azurerm_container_registry_scope_map should allow "_" in the name

### ISSUE THREAD

**Issue by saulobejo** [hashicorp/terraform-provider-azurerm#14573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
  Terraform v1.1.0
  on linux_amd64
  + provider registry.terraform.io/hashicorp/azurerm v2.89.0
```

### Affected Resource(s)

* `azurerm_container_registry_scope_map `

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry_scope_map" "acr_scope_map" {
  name                    = "_repositories_pull"
  container_registry_name = azurerm_container_registry.acr.name
  resource_group_name     = azurerm_container_registry.acr.resource_group_name
  actions = [
    "repositories/*/content/read"
  ]
}
```

### Debug Output

```
│
│ Error: alpha numeric characters and hyphens only are allowed in "name": "_repositories_pull"
│ 
│   with azurerm_container_registry_scope_map.acr_scope_map,
│   on acr.tf line 22, in resource "azurerm_container_registry_scope_map" "acr_scope_map":
│   22:   name                    = var.acr_scope_map_name
│ 
│
```

### Expected Behaviour

It should be able to create a scope map with a "_" (underscore) in the name. `_repositories_pull`, `_repositories_admin` and `_repositories_push` are created by default in ACR.

### Actual Behaviour

Terraform plan fails.

`Error: alpha numeric characters and hyphens only are allowed in "name": "_repositories_pull"`

### Steps to Reproduce

1. `terraform plan`

### References

* #11545

**Comment by Nitin052** [comment]
Hi @saulobejo @tombuildsstuff  When I am trying to create scope map manually  with name underscore in azure platform  i am getting this - 
![Screenshot from 2021-12-20 11-15-30](https://user-images.githubusercontent.com/42588508/146756009-30d5ab6d-fdf4-47bb-8417-33784c1a7e1d.png)
So could you please elaborate more.
Thank you.

**Comment by saulobejo** [comment]
@Nitin052 
You are correct. You are not able to CREATE a new scope map with underscore. But with the rules as they are, you are also not able to USE the 3 default system scopes in the left side of your print screen.

My workaround was to refer to the existing scope using its ID instead of declaring them as a block. Maybe this is the correct way to do it anyway.

Regards and thanks for looking into this

**Comment by Nitin052** [comment]
Hi @saulobejo  I am able to use default system scopes map. 
`resource "azurerm_resource_group" "test" {
  name     = "xyz"
  location = "eastus"
}

resource "azurerm_container_registry" "test" {
  name                     = "xyzregistry"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  sku                      = "Premium"

}

data "azurerm_container_registry_scope_map" "test" {
  name                  = "_repositories_admin"
  container_registry_name = azurerm_container_registry.test.name
  resource_group_name      = azurerm_resource_group.test.name
 
}


resource "azurerm_container_registry_token" "test" {
  name                  = "pull-image"
  container_registry_name = azurerm_container_registry.test.name
  resource_group_name      = azurerm_resource_group.test.name
  scope_map_id          = data.azurerm_container_registry_scope_map.test.id
}
`
![Screenshot from 2021-12-21 13-57-56](https://user-images.githubusercontent.com/42588508/146897190-6f030781-726b-4092-957b-c78148e93494.png)

**Comment by saulobejo** [comment]
@Nitin052 
I see that you set the resource_map as `data` instead of `resource`
As `data` it works. As `resource` it doesn't.
Does that automatically imports from azure or do I need to import manually?

**Comment by Nitin052** [comment]
@saulobejo 
When I create container registry by default  system scope map  created .
For using default system scope map  . I have used data source to fetch default scope map id .  
After that i have used scope map id to create tokens.

> @Nitin052 I see that you set the resource_map as `data` instead of `resource` As `data` it works. As `resource` it doesn't. Does that automatically imports from azure or do I need to import manually?

**Comment by saulobejo** [comment]
@Nitin052 
This "workaround" works great. I didn't know you could use data blocks like this.
This also means this is not a bug but the correct behavior when creating a `new` scope.
Thanks for the help!
