### ISSUE TITLE
Support for Azure Web PubSub

### ISSUE THREAD

**Issue by polys** [hashicorp/terraform-provider-azurerm#14579]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://azure.microsoft.com/services/web-pubsub/

**Comment by xiaxyi** [comment]
@polys , I'm working on the TF integration now, the feature should be available soon. I'll let you know if there is any update

**Comment by polys** [comment]
@xiaxyi Many thanks!  It's great to see the new resource for Web PubSub released.

Just gave it a try and one thing that doesn't line up is `managed_identity_id` on `azurerm_web_pubsub_hub` `auth`.

The Azure Portal lets you choose and existing Azure AD Application ID and you can see that's just a GUID in the ARM template. 

Here though, `managed_identity_id` doesn't like that — I get the error:
`Error: parsing "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx": expected 8 segments within the Resource ID but got 1 for "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

**Comment by xiaxyi** [comment]
@polys , thanks for pointing it out, let me check and update you.

**Comment by xiaxyi** [comment]
@polys I checked the code and below are some updates:
The validation logic of the auth id that I used is the user assigned identity resource ID, this cannot validate the GUID of an application.

Since portal supports the GUID, I will make terraform to have the same behavior. Please also note that we will check if the value that's being passed matches with the format of Azure UUID as well

**Comment by polys** [comment]
Many thanks @xiaxyi !

`managed_identity_id` works great in the latest release.

Sorry to keep bothering you with this but there's another thing that seems to be missing.
Comparing the ARM templates for a Web PubSub created with terraform vs one I created by hand, this block is missing:
```json
"identity": {
   "type": "SystemAssigned"
}
```

The `azurerm_web_pubsub` resource doesn't seem to support an `identity` block like [`azurerm_kubernetes_cluster`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster) and other resources:
```
identity {
  type = "SystemAssigned"
}
```

### Created using Terraform:

   ![image](https://user-images.githubusercontent.com/4301432/152582180-1ae831c0-b13b-4f8d-8c00-826fb22ca53b.png)

### Created through the Azure Portal (leaving all the defaults):

   ![image](https://user-images.githubusercontent.com/4301432/152582854-52e0463f-6e5f-4de0-aafd-7a41d0057497.png)

**Comment by xiaxyi** [comment]
@polys no worries, let me check

**Comment by polys** [comment]
> @polys The identity should be supported now, feel free to test and let me know if you have any other questions. :)

Thank you!
Just gave it a try and everything seems to work perfectly. Many thanks again!

**Comment by tombuildsstuff** [comment]
Fixed via https://github.com/hashicorp/terraform-provider-azurerm/pull/14731
