### ISSUE TITLE
Azure AD Domain Services - filtered_sync_enabled does not enable Scoped Synchronization

### ISSUE THREAD

**Issue by chittyren** [hashicorp/terraform-provider-azurerm#14599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM: 2.89.0
Terraform: 1.0.6

### Affected Resource(s)

* `azurerm_active_directory_domain_service`

### Terraform Configuration Files

Note, the block below is just for the azurerm_active_directory_domain_service, the rest of the terraform config can be pulled from the example section of the [resource's documentation page](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service#example-usage).
```hcl
resource "azurerm_active_directory_domain_service" "example" {
  name                = "example-aadds"
  location            = azurerm_resource_group.aadds.location
  resource_group_name = azurerm_resource_group.aadds.name

  domain_name           = "widgetslogin.net"
  sku                   = "Standard"
  filtered_sync_enabled = true

  initial_replica_set {
    subnet_id = azurerm_subnet.deploy.id
  }

  notifications {
    notify_dc_admins      = true
    notify_global_admins  = true
  }

  security {
    sync_kerberos_passwords = true
    sync_ntlm_passwords     = true
    sync_on_prem_passwords  = true
  }

  depends_on = [
    azuread_service_principal.example,
    azurerm_subnet_network_security_group_association.deploy,
  ]
}
```

### Expected Behaviour

Setting `filtered_sync_enabled` to true results in Azure AD Domain Service's "Scoped Synchronization" to be enabled.
(Feature Request) - Specify ad groups to include in scope to be sync'd. 

### Actual Behaviour

Setting `filtered_sync_enabled` to true does not enable "Scoped Synchronization" on the Azure AD Domain Services.

### Steps to Reproduce

1. copy entire example from the azurerm_active_directory_domain_service resource documentation  
2. under azurerm_active_directory_domain_service resource:  
  a. change `filtered_sync_enabled` to true  
  b. change `sku` to standard  
3. run `terraform apply`  

### References

* [azurerm_active_directory_domain_service](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/active_directory_domain_service#example-usage)
* [Azure AD DS Scoped Synchronization](https://docs.microsoft.com/en-us/azure/active-directory-domain-services/scoped-synchronization)

Please let me know if there is any further information I can provide!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
