### ISSUE TITLE
azurerm_app_service_certificate - Unable to determine the Resource ID for the Key Vault at URL

### ISSUE THREAD

**Issue by utr1903** [hashicorp/terraform-provider-azurerm#14611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: v1.1.0
Azurerm: v2.89.0

### Affected Resource(s)
* azurerm_app_service_certificate

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

provider "azurerm" {
  alias           = "subscription1"
  subscription_id = var.subscription_id_1
  features {}
}

# Resource Group (Subscription 1)
data "azurerm_resource_group" "subscription1" {
  name     = "rg-subscription1"
  provider = azurerm.subscription1
}

# Resource Group (Subscription 2)
data "azurerm_resource_group" "subscription2" {
  name     = "rg-subscription2"
}

# Key Vault (Subscription 1)
data "azurerm_key_vault" "subscription1" {
  name                = "kv_subscription1"
  resource_group_name = data.azurerm_resource_group.subscription1.name
  provider            = azurerm.subscription1
}

# SSL Certificate (Subscription 1)
data "azurerm_key_vault_certificate" "subscription1" {
  name         = "cert"
  key_vault_id = data.azurerm_key_vault.subscription1.id
  provider     = azurerm.subscription1
}

# Access Policy to App Service in subscription 2 on Key Vault in subscription 1
resource "azurerm_key_vault_access_policy" "app_service_in_subscription_2" {
  key_vault_id = data.azurerm_key_vault.subscription1.id
  tenant_id    = data.azurerm_client_config.this.tenant_id
  object_id    = azurerm_app_service.subscription2.identity[0].principal_id

  key_permissions         = []
  certificate_permissions = ["Get"]
  secret_permissions      = ["Get"]
  storage_permissions     = []

  provider = azurerm.subscription1
}

# SSL Certificate for App Service (Subscription 2)
resource "azurerm_app_service_certificate" "subscription2" {
  name                = "cert"
  resource_group_name = data.azurerm_resource_group.subscription2.name
  location            = data.azurerm_resource_group.subscription2.location

  key_vault_secret_id = data.azurerm_key_vault_certificate.subscription1.secret_id

  depends_on = [azurerm_key_vault_access_policy.app_service_in_subscription_2]

  # provider = azurerm.subscription1 -> Tested both commented and uncommented
}

# SSL Certificate Binding to Custom Domain (Subscription 2)
resource "azurerm_app_service_certificate_binding" "subscription2" {
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.subscription2.id
  certificate_id      = azurerm_app_service_certificate.subscription2.id
  ssl_state           = "SniEnabled"
}
```

### Debug Output

The issue is due to `azurerm_app_service_certificate`. Since the corresponding key vault and the certificate in that key vault are in "Subscription 1" and the app service is in the "Subscription 2", two providers are required to detect the resources.

When the provider for the "Subscription 2" is used (which for me seems to be right one), the Terraform cannot find the key vault "Subscription 1" and the following error is prompted:
-> Unable to determine the Resource ID for the Key Vault at URL <url_of_the_key_vault>

When the provider for the "Subscription 1" is used, the Terraform cannot find the resource group in the "Subscription 2" and the following error is prompted:
-> StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'rg-subscription2' could not be found."

### Expected Behaviour

The secret ID of the certificate in the "Subscription 1" should have been retrieved and assigned to the app service certificate in the "Subscription 2" successfully.

When I have tried to create the `azurerm_app_service_certificate` with a certificate in a key vault which is in the same subscription, everything worked perfectly.

### Actual Behaviour

Terraform can access the certificate in a key vault in "Subscription 1" and can grab its secret ID. However it cannot assign it to the app service in "Subscription 2".

**Comment by mrnone** [comment]
Hello,

This is a pretty standard configuration when a company has many subscriptions with different app services (different projects with separate billing) and an "internal" subscription with one keyvault where all certificates are located.

**Comment by pavelpikatamcs** [comment]
This seems to be working fine with ARM template and `Microsoft.Web/certificates` resource, but doesn't work with Terraform :(

**Comment by ArkadiuszSpiewak** [comment]
Im facing same issue. I have app service and key vault in production subscription, and spoke resource group in non prod subsciprion. Im unable to create `azurerm_app_service_certificate` in non-prod using secret form key vault in prod subsciption.

**Comment by ioxFR** [comment]
Hello,

Got same issue on my side.
Wildcard certificate is stored on shared keyvault used by prod & non prod environment.
This keyvault is in different subscription from the one which i create my appservices

**Comment by CoreyCaldwell** [comment]
+1 for me while migrating from blueprint to terraform trying to add azurerm_app_service_certificate. This works fine in azure (and blueprint) without a version in the url.
> terraform version      
>> Terraform v1.2.0
>> on windows_amd64
>> + provider registry.terraform.io/hashicorp/azurerm v3.7.0

**Comment by CoreyCaldwell** [comment]
Potential fix from master branch, 
internal\services\web\app_service_certificate_resource.go line 101
keyVaultParse.ParseNestedItemID -> keyVaultParse.ParseOptionallyVersionedNestedItemID

**Comment by pjolsen** [comment]
Not sure why the other comments have been marked off topic? 

@CoreyCaldwell - is that working code or code that would need to be fixed?

**Comment by pjolsen** [comment]
As an incomplete workaround, you can use the azapi provider:

`terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
    }
  }
}

provider "azapi" {
}

resource "azapi_resource" "example" {
  type = "Microsoft.Web/certificates@2021-02-01"
  name = "<myVault>-<myCert>"
  parent_id = "/subscriptions/<subID>/resourceGroups/<resourceGroupID>"
  body = jsonencode({
    "location": "West Europe",
    "properties": {
      "serverFarmId": "<appServicePlanID>",
      "keyVaultId": "<keyVaultID>",
      "keyVaultSecretName": "<myCert>"
    }
  })
}
`

**Comment by dylan-asos** [comment]
Thanks @pjolsen, workaround unblocked me.

**Comment by alexeyauslender** [comment]
Implemented as an ARM template, thank you @CoreyCaldwell for the comments.

**Comment by alexey-aouslender-sp** [comment]
Still an issue, I wander if anybody is going to fix that.

**Comment by dornfeder** [comment]
Any news on this one? It's still happening with azurerm v3.72.0...
