### ISSUE TITLE
Support for Automation Hybrid Runbook Worker Group

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#14622]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a request for a new resource in automation category for [Hybrid Runbook Worker Group](https://docs.microsoft.com/en-us/azure/automation/extension-based-hybrid-runbook-worker-install#create-hybrid-worker-group).

### New or Affected Resource(s)

* azurerm_automation_hybrid_runbook_worker_group

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/Azure/azure-sdk-for-go/blob/main/services/automation/mgmt/2019-06-01/automation/hybridrunbookworkergroup.go

**Comment by chnusti** [comment]
without the ability of having hybrid worker available and the ability to assign a web hook to that worker is pretty much useless.
 moreover, the ability to choose worker for azurerm_automation_schedule and azurerm_automation_webhook are missing either

**Comment by freola** [comment]
This would be very helpful!

**Comment by WaitingForGuacamole** [comment]
Agreed - I can create the automation account, create the runbook, create the schedule, and even create a job schedule pointing at an existing hybrid worker group, but without this resource, I'd always have to break this into two deployments to allow manual provisioning, put a local-exec block in, or run an ARM template before I can close the loop.

**Comment by t-l-k** [comment]
@WaitingForGuacamole perhaps consider use of the `azapi_resource` that can handle bicep compatible templates - I've managed to deploy a hybrid worker group using it, example below:

```
resource "azapi_resource" "hybrids_group_1" {
  type      = "Microsoft.Automation/automationAccounts/hybridRunbookWorkerGroups@2022-02-22"
  name      = "hwg-${azurerm_automation_account.hybrids.name}-001"
  parent_id = azurerm_automation_account.hybrids.id

  body = jsonencode({
    properties = {
      credential = {
        name = azurerm_automation_credential.domain_service_account.name
      }
    }
  })
}
```

There are [Terraform examples in the documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.automation/automationaccounts/hybridrunbookworkergroups?pivots=deployment-language-terraform). Its quite useful for stuff on the fringes, like this.
