### ISSUE TITLE
Add GraphQL to API Manager

### ISSUE THREAD

**Issue by adamyager** [hashicorp/terraform-provider-azurerm#14634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

GraphQL is a powerful new feature in API manager. We would love to see this added 

https://docs.microsoft.com/en-us/azure/api-management/graphql-api

Mostly be impacting this resource I believe. 
(https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api)
azurerm_api_management_api

the supporting SDK is in the current release so its now supported to enable
https://github.com/Azure/azure-sdk-for-go/blob/main/services/apimanagement/mgmt/2021-08-01/apimanagement/models.go#L990

### Potential Terraform Configuration

graphql_passthrough = boolean 
likely would default to false

### References
Info on the service
https://docs.microsoft.com/en-us/azure/api-management/graphql-api
Supported in the current API
https://github.com/Azure/azure-sdk-for-go/blob/main/services/apimanagement/mgmt/2021-08-01/apimanagement/models.go#L990

* #0000

**Comment by Gaardsholt** [comment]
Is anyone working on this?
If not, I might have a look at it :)

**Comment by christianfosli** [comment]
Microsoft just announced that this feature is now generally available, during the Microsoft Build conference.
Really looking forward to being able to use this feature in terraform :smile:

**Comment by cashman04** [comment]
Is there a status on this?  GraphQL just went GA in May and we still can't create this resource though TF, which is affecting all of our other API's.

**Comment by owenfarrell** [comment]
@adamyager - I took a crack at this one. I see the existing pattern for SOAP passthrough, but I took an approach to _**not**_ emulate that as I think it would be more challenging to maintain if/as more backend API types are supported.

Thoughts welcome.
