### ISSUE TITLE
azurerm_logic_app_trigger_recurrence: time_zone does not affect start_time

### ISSUE THREAD

**Issue by geekzter** [hashicorp/terraform-provider-azurerm#14657]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_logic_app_trigger_recurrence`

### Terraform Configuration Files

```hcl
resource azurerm_resource_group repro {
  name                         = "startdate-timezone-issue"
  location                     = "westeurope"
}

resource azurerm_logic_app_workflow stop {
  name                         = "stop-workflow"
  resource_group_name          = azurerm_resource_group.repro.name
  location                     = "westeurope"
}  

resource azurerm_logic_app_trigger_recurrence workweek_stop_trigger {
  name                         = "workweek_stop"
  logic_app_id                 = azurerm_logic_app_workflow.stop
  frequency                    = "Week"
  interval                     = 1
  schedule {
    at_these_hours             = [21]
    at_these_minutes           = [00]
    on_these_days              = [
      "Monday",
      "Tuesday", 
      "Wednesday", 
      "Thursday", 
      "Friday",
    ]
  }
  # Valid RFC 3339 Date is not accepted
  # start_time requires a 'Z' at the end, meaning UTC time. 
  start_time                   = "2021-12-19T21:00:00" 
  # Time zone will not affect start_time as start_time is always UTC
  time_zone                    = "W. Europe Standard Time"
}
```

### Expected Behaviour

Similar behavior as logic app UI/ARM: start_time to accept `2021-12-19T21:00:00` as a valid RFC 3339 date.

### Actual Behaviour

start_time requires a `Z` to be appended. This turns the date into a UTC time, so `time_zone` can't effect `start_date`.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

[RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) refers to the `Z` as an optional element.

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
