### ISSUE TITLE
azurerm_consumption_budget_subscription error introduced in v2.90.0

### ISSUE THREAD

**Issue by croeck** [hashicorp/terraform-provider-azurerm#14653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0

### Affected Resource(s)

* `azurerm_consumption_budget_subscription`

### Expected Behaviour

- Resource should work as it did in v2.89.0

### Actual Behaviour

Error is reported:
 
```
╷
│ Error: string is required
│
│   with azurerm_consumption_budget_subscription.budget,
│   on budget-alert.tf line 3, in resource "azurerm_consumption_budget_subscription" "budget":
│    3:   subscription_id = var.subscription_id
```

### Important Factoids

Reverting back to v2.89.0 worked for me, this potential bug seems to have been introduced by a code refactoring.

### References

I assume in this commit which ended up in v2.90.0: https://github.com/hashicorp/terraform-provider-azurerm/commit/19844818b19b0cc3e1474b9a773335464d024a22#diff-967148bd73e3aa7e8de6715956d8d2e07891b79697e481fe48acffab7a9c7076

**Comment by skelso01** [comment]
Additional information:
I had the same issue.
In the version specification of my template I had for azurerm: ">=2.73.0". Here I got this error message. After I changed that once to "=2.89.0" I could make a plan and an apply. Now I changed it back to ">=2.73.0" and it works as expected.
There seems to be something in an existing statefile that is causing the behavior described in this issue.
