### ISSUE TITLE
zone-zone disaster recovery support for VM using `azurerm_site_recovery_replicated_vm`  should have a "target_availability_zone" argument..

### ISSUE THREAD

**Issue by AnsumanBal-MT** [hashicorp/terraform-provider-azurerm#14652]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a zone to zone disaster recovery for vm but terraform only provides _single instance_ and _target availablity set_ argument in the `azurerm_site_recovery_replicated_vm`. There should be a **_target_availability zone_** argument in the resource block.

### New or Affected Resource(s)

* `azurerm_site_recovery_replicated_vm`

### Potential Terraform Configuration

```hcl
resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
  name                                      = "vm-replication"
  resource_group_name                       = azurerm_resource_group.secondary.name
  recovery_vault_name                       = azurerm_recovery_services_vault.vault.name
  source_recovery_fabric_name               = azurerm_site_recovery_fabric.primary.name
  source_vm_id                              = azurerm_windows_virtual_machine.vm.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  source_recovery_protection_container_name = azurerm_site_recovery_protection_container.primary.name

  target_resource_group_id                = azurerm_resource_group.secondary.id
  target_recovery_fabric_id               = azurerm_site_recovery_fabric.secondary.id
  target_recovery_protection_container_id = azurerm_site_recovery_protection_container.secondary.id
  **target_availablity_zone                 = "3"** 
```

### References

*  https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-how-to-enable-zone-to-zone-disaster-recovery
* https://docs.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/2021-08-01/vaults/replicationfabrics/replicationprotectioncontainers/replicationprotecteditems?tabs=bicep#enableprotectionproviderspecificinput-objects

**Comment by cheng514** [comment]
@katbyte Please review PR https://github.com/hashicorp/terraform-provider-azurerm/pull/15617/files and link to this issue. Thanks.
