### ISSUE TITLE
Cannot get built-in endpoints of an IoT Hub created by Terraform

### ISSUE THREAD

**Issue by gary918** [hashicorp/terraform-provider-azurerm#14670]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.5
on darwin_amd64
- provider registry.terraform.io/hashicorp/azurerm v2.89.0

### Expected Behaviour

Once an Azure IoT Hub resource's created, we should be able to get its built-in endpoints such as the 'Event Hub compatible endpoint'. For example, how can I get the connection string of the 'Event Hub compatible endpoint' of the IoT Hub?

### Actual Behaviour

There's no way I can get the IoT Hub's built-in endpoints such as the 'Event Hub compatible endpoint'.

### Steps to Reproduce

1. Create the iot_hub resource as the following:
```resource "azurerm_iothub" "iot_hub" {
  name                          = "my_iot_hub"
  resource_group_name           = "my_rg"
  location                      = "eastasia"
  public_network_access_enabled = true

  sku {
    name     = "S1"
    capacity = "1"
  }

  route {
    name           = "defaultroute"
    source         = "DeviceMessages"
    condition      = "true"
    endpoint_names = ["events"]
    enabled        = true
  }

  tags = {
    purpose = "testing"
  }
}
```

2. Through Azure Portal, you'll be able to get the information of the 'Event Hub compatible endpoint' of IoT Hub created by Terraform.
![azureportal](https://user-images.githubusercontent.com/23734158/146768054-316fdb4a-4143-4086-a07c-5af2f07ff251.png)

* #0000

**Comment by tombuildsstuff** [comment]
hi @gary918 

Thanks for opening this issue.

This is available [in the `shared_access_policy` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub#shared_access_policy) - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by gary918** [comment]
@tombuildsstuff Thanks for your prompt reply. However, [shared_access_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub#shared_access_policy) cannot solve my problem. Please note that I'm expecting to get the 'built-in **event hub endpoint connection string**', not the IoT Hub connection string. I don't think the current azurerm provider is able to solve this. Do you agree?

**Comment by tombuildsstuff** [comment]
@gary918 I maybe wrong but I believe the connection string is applicable for both? We can look to add this if it's not, but IIRC EventHub and IoTHub are fairly intertwined - would you mind confirming and we can take another look?

Thanks!

**Comment by gary918** [comment]
@tombuildsstuff Here's an example of connection strings of 'sample_iothub':

- **IoT Hub connection string**: HostName=sample_iothub.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxx
- **sample_iothub's built-in event hub endpoint connection string**: 
Endpoint=sb://**random_created_namespace**.servicebus.windows.net/;SharedAccessKeyName=iothubowner;SharedAccessKey=xxxx;EntityPath=sample_iothub

Therefore, I don't think they are interwined.

**Comment by PylypLebediev** [comment]
Are there any resolution to this issue? Why was it closed?
