### ISSUE TITLE
Support for azure account page blob

### ISSUE THREAD

**Issue by ekersale** [hashicorp/terraform-provider-azurerm#14699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "notification" {
  [...]
  account_tier             = "Premium"
  account_replication_type = "LRS"


  access_tier                    = "Hot"
  account_kind                = "PageBlobStorage"
  [...]
}
```

### References

* https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview#types-of-storage-accounts

**Comment by jpmicrosoft** [comment]
@ekersale This kind "PageBlobStorage" is not supported. The Premium Page Blobs are deployed using the StorageV2 account kind. I am going to submit a pull request that adds a note to the documentation for storage_account. 

![image](https://user-images.githubusercontent.com/48604544/146998386-ba2f6f2a-47ff-42ec-b5a4-fd8d973feb30.png)

https://docs.microsoft.com/en-us/azure/storage/common/storage-account-create?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json&tabs=azure-powershell#create-a-storage-account-1

**Comment by mybayern1974** [comment]
@ekersale , would you feel ok if we close this issue?

**Comment by ekersale** [comment]
Yes thanks a lot!
