### ISSUE TITLE
Problem with importing resource of type "azurerm_stream_analytics_output_table"

### ISSUE THREAD

**Issue by SimonGasparKentico** [hashicorp/terraform-provider-azurerm#14709]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.2
Azurerm v2.90.0

### Affected Resource(s)

* `azurerm_stream_analytics_output_table`

### Panic Output
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

Stack trace from the terraform-provider-azurerm_v2.90.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x59ef25c]

goroutine 92 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/streamanalytics.OutputTableResource.Read.func1({0x6e65ce8, 0xc001c047e0}, {0xc000e53500, {0x6e67338, 0xc00009b4e8}, 0xc0019dae80, 0x0, {0x6e68f00, 0xb423a40}})        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/streamanalytics/stream_analytics_output_table_resource.go:195 +0x57c
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.(*ResourceWrapper).Resource.func3({0x6e65ce8, 0xc001c047e0}, 0x45d964b800, {0x5e946c0, 0xc000e53500})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:65 +0x16e
github.com/hashicorp/terraform-provider-azurerm/internal/sdk.diagnosticsWrapper.func1({0x6e65ce8, 0xc001c047e0}, 0x1f648dd0a28, {0x5e946c0, 0xc000e53500})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/sdk/wrapper_resource.go:168 +0xbe
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000497b20, {0x6e65c78, 0xc0009f4340}, 0x24, {0x5e946c0, 0xc000e53500})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:358 +0x12e
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000497b20, {0x6e65c78, 0xc0009f4340}, 0xc001d205b0, {0x5e946c0, 0xc000e53500})
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0011b22b8, {0x6e65c78, 0xc0009f4340}, 0xc0009f43c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0000a9380, {0x6e65d20, 0xc0002d8360}, 0xc001c040c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x63c9000, 0xc0000a9380}, {0x6e65d20, 0xc0002d8360}, 0xc001c04060, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170     
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000216fc0, {0x6eb4388, 0xc000181200}, 0xc001b0a000, 0xc00127d860, 0xb3be290, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000216fc0, {0x6eb4388, 0xc000181200}, 0xc001b0a000, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.90.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Steps to Reproduce

1. `terraform import azurerm_stream_analytics_output_table.example _resource_id_`

### References

* #6710

**Comment by lonegunmanb** [comment]
Hi @SimonGasparKentico , it looks like the code caused panic at stream_analytics_output_table_resource.go:195 is reading batch size from service side:

```go
state := OutputTableResourceModel{
					Name:               id.Name,
					ResourceGroup:      id.ResourceGroup,
					StreamAnalyticsJob: id.StreamingjobName,
					StorageAccount:     *v.AccountName,
					StorageAccountKey:  metadata.ResourceData.Get("storage_account_key").(string),
					Table:              *v.Table,
					PartitionKey:       *v.PartitionKey,
					RowKey:             *v.RowKey,
					BatchSize:          *v.BatchSize,
				}
```

It looks like v.BatchSize is nil, but `batch_size` in schema definition is `Required`, so what's actual batch size value on the resource you'd like to import?

**Comment by tombuildsstuff** [comment]
@lonegunmanb any property in the Azure API response can be nil - so anything defined as nil in the SDK needs to be nil-checked / handled - so this needs to be fixed in the Provider too fwiw

**Comment by lonegunmanb** [comment]
@tombuildsstuff I'd like to contribute a fix but I'm not familiar with how our provider should deal with this kind of issue so I need your guidance, in this case should we return an error that indicating a malformat response? Thanks!
