### ISSUE TITLE
new resource "azurerm_key_vault_network_acl_rule"

### ISSUE THREAD

**Issue by akshaiu** [hashicorp/terraform-provider-azurerm#14706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We would like to have a new resource dedicated to the management of key vault network ACL rules. This is similar to the `azurerm_storage_account_network_rules` that will manage network rules inside of a Azure Keyvault as a separate resource.

### New or Affected Resource(s)

* `azurerm_keyvault`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @akshaiu 

Thanks for opening this issue.

This resource has been requested previously and after looking into this and digging into the use-cases at this time unfortunately we're not planning to introduce this resource into the provider at this time - more information can be found [in this comment](https://github.com/hashicorp/terraform-provider-azurerm/pull/8560#issuecomment-773267957) and so whilst I'd like to thank you for opening this issue, I'm going to close this issue for the moment.

Thanks!
