### ISSUE TITLE
Support for Azure Machine Learning datastores

### ISSUE THREAD

**Issue by Telemaco019** [hashicorp/terraform-provider-azurerm#14701]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to have Terraform resources for managing Azure Machine Learning Workspace internal assets, especially datastores, since they are often linked to other Azure resources already managed by Terraform (e.g. Service Principals for authentication, Storage Accounts, databases etc.).

I've started developing a dedicated provider for configuring AML Workspaces (you can find it in my GitHub repos) which at the moment only supports datastore resources/datasources as shown below. If this feature is of interest, I would like to implement it in azurerm provider by adapting what I've developed so far for my custom provider.

### New or Affected Resource(s)

* azurerm_machine_learning_datastore

### Potential Terraform Configuration

Datastore resource
```hcl
resource "azurerm_machine_learning_datastore" "example" {
  resource_group_name = "example"
  workspace_name      = "example"
  name                = "example"
  description         = "example"
  storage_type        = "AzureBlob"

  storage_account_name   = "example"
  storage_container_name = "example"

  auth  {
    credentials_type = "AzureDataLakeGen2"
    client_id        = "client-id"
    client_secret    = "client-secret"
    tenant_id        = "tenant-id"
  }
}
```

Datastore data sources
```hcl
data "azurerm_machine_learning_datastores" "all_datastores" {
  resource_group_name = "example"
  workspace_name      = "example"
}
data "azurerm_machine_learning_datastore" "datastore_by_name" {
  resource_group_name = "example"
  workspace_name      = "example"
  name                = "example"
}
```

### References

* [Azure Machine Learning documentation](https://docs.microsoft.com/en-us/azure/machine-learning/)
* [REST APIs for managing datastores](https://docs.microsoft.com/en-us/rest/api/azureml/datastores)
* [Azure Machine Learning Go SDK](https://github.com/Telemaco019/azureml-go-sdk)

**Comment by stephybun** [comment]
Closed by #20045, #19934, #19909

**Comment by tete17** [comment]
Hey @stephybun I may be getting this wrong but all the databases as datastores are missing

**Comment by stephybun** [comment]
@tete17 that may well be likely. As far as I know/can remember we're unable to support a generic `azurerm_machine_learning_datastore` resource, so the exact ask of this issue is a little vague. If there is a particular datastore missing that you'd like to have added I'd suggest opening another issue including the specific datastores that you'd like to have added.
