### ISSUE TITLE
Support for Azure autoheal - revive old thread

### ISSUE THREAD

**Issue by kwaksaewon** [hashicorp/terraform-provider-azurerm#14714]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi everyone. I want to revive this post https://github.com/hashicorp/terraform-provider-azurerm/issues/8093 and request feature for Azure Autoheal. 

### New or Affected Resource(s)

https://docs.microsoft.com/en-us/azure/app-service/overview-diagnostics

https://azure.github.io/AppService/2018/09/10/Announcing-the-New-Auto-Healing-Experience-in-App-Service-Diagnostics.html

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.autohealrules?view=azure-dotnet
### Potential Terraform Configuration

It's in https://github.com/hashicorp/terraform-provider-azurerm/issues/8093 under 'Potential Terraform Configuration'. I wasn't sure if I could copy it over here because I didn't come up with the terraform file myself. 

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:

* https://github.com/hashicorp/terraform-provider-azurerm/issues/8093

**Comment by tombuildsstuff** [comment]
hi @kwaksaewon 

Thanks for opening this issue.

Since #8093 is still open, rather than having multiple issues tracking the same thing I'm going to close this issue in favour of #8093 - please subscribe to that issue for updates.

Thanks!
