### ISSUE TITLE
azurerm_databricks_workspace private workspace produces different result when deploying via provider vs portal

### ISSUE THREAD

**Issue by faisaleem-na** [hashicorp/terraform-provider-azurerm#14713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
azurerm: 2.90.0
terraform: 0.14.10

### Affected Resource(s)

* `azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "databricks" {
  for_each                   = var.databricks 
  name                       = each.value.databricks_name
  resource_group_name        = each.value.rg_name == null ? lookup(var.resource_group_output, each.value.resource_group_name, "ERROR") : data.azurerm_resource_group.resource_group[each.key].name
  location                   = each.value.rg_name == null ? each.value.location : data.azurerm_resource_group.resource_group[each.key].location
  sku                        = "premium"
  tags                       = each.value.tags
  
  custom_parameters {
  virtual_network_id         = data.azurerm_virtual_network.vnet[each.key].id
  private_subnet_name        = each.value.private_subnet_name
  public_subnet_name         = each.value.public_subnet_name
  no_public_ip               = true
  private_subnet_network_security_group_association_id = data.azurerm_subnet.snet[each.value["private_subnet_key"]].network_security_group_id
  public_subnet_network_security_group_association_id  = data.azurerm_subnet.snet[each.value["public_subnet_key"]].network_security_group_id
  }
  public_network_access_enabled = false
  network_security_group_rules_required = each.value.network_security_group_rules_required
  
}
```

### Expected Behaviour
databricks private workspace to be provisioned

### Actual Behaviour
i get the below error stating that the private workspace needs to be registered in order to be used in the subscription. however if i deploy manually via the portal it deploys successfully without any issues. i am wondering whether this is a generic issue but actually the issue is something else?

Error: creating/updating Workspace (Subscription: "***"
Resource Group Name: "test_rg"
Workspace Name: "test_ws"): performing CreateOrUpdate: workspaces.WorkspacesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidPrivateWorkspaceForSubscription" Message="The subscription *** is not registered to create private workspace."

  on .terraform/modules/databricks/module/main.tf line 1, in resource "azurerm_databricks_workspace" "databricks":
   1: resource "azurerm_databricks_workspace" "databricks" {

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @faisaleem-na 

Thanks for opening this issue.

Taking a look through here it's likely the Azure Portal is using a different version of the DataBricks API to deploy this resource than the Provider is (`2021-04-01-preview`) - you should be able to confirm that in the Azure Portal checking the parent Resource Group (to see the ARM Template that the Portal has deployed behind the scenes) or by checking the network traffic that the Portal is sending (in Developer Tools) where the API version is in the QueryString on any requests to `management.azure.com`).

At this time we're using [the latest API Version available to us](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/databricks/resource-manager/Microsoft.Databricks) - so unfortunately I believe that's the most likely answer here (insofar as the Portal is using a new, undocumented API version).

Thanks!

**Comment by faisaleem-na** [comment]
thanks tom,

I thought as much and hence already raised it with MS and checking the template it is using (2021-04-01-preview) but just wanted to be sure there wasnt anything else that i was missing as it takes a while for it to get to the right person in MS

thanks again

**Comment by faisaleem-na** [comment]
out of interest how can I see what version is being used by the provider?

**Comment by faisaleem-na** [comment]
apologies for the multiple questions on this but just trying to better understand the situation.
The api version that the provider uses, is that based on the version of azurecli available or some other method?
how does it know what api versions are available and which is the latest etc?
thanks

**Comment by tombuildsstuff** [comment]
@faisaleem-na 

> out of interest how can I see what version is being used by the provider?

The Client in each Service Package imports those API versions, for example: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/databricks/client/client.go#L5

> The api version that the provider uses, is that based on the version of azurecli available or some other method? how does it know what api versions are available and which is the latest etc?

We pick the latest API version that's available and supports the features we need based on what's available in [the Azure Swagger repository](https://github.com/Azure/azure-rest-api-specs) which ultimately gets used in the Provider.

---

Since this appears to be an issue on Microsoft's side (since the same API version is being used in both cases) - I'm going to close this issue for the moment - but if the Service Team confirm there's something else needed here then please let us know and we can look into supporting this.

Thanks!
