### ISSUE TITLE
azurerm_key_vault_certificate: Error: Invalid function argument

### ISSUE THREAD

**Issue by ValeruS** [hashicorp/terraform-provider-azurerm#14719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v1.1.2
- AzureRM v2.90.0

### Affected Resource(s)

* `azurerm_key_vault_certificate`

### Terraform Configuration Files

```hcl
resource "random_password" "p12_password" {
  length = 32
  min_upper = 5
  min_numeric = 7
  special = false
}

resource "acme_certificate" "certificate" {
  account_key_pem           = var.account_key_pem
  common_name               = var.common_name
  subject_alternative_names = var.subject_alternative_names
  certificate_p12_password  = random_password.p12_password.result
  revoke_certificate_on_destroy = true
  min_days_remaining = "15"

  dns_challenge {
    provider = var.dns_provider

    config = tomap("${var.dns_provider_config}")
  }
}
resource "local_file" "certificate_pfx" {
  content_base64 = acme_certificate.certificate.certificate_p12
  file_permission      = "0644"
  directory_permission = "0755"
  filename       = "certs/${var.cert_name}.pfx"
}

resource "azurerm_key_vault_certificate" "pfx" {
  name         = var.cert_name
  key_vault_id = var.key_vault_id

  certificate {
    contents = filebase64(local_file.certificate_pfx.filename)
    password = random_password.p12_password.result
  }
}
```

### Expected Behaviour

to be possible to apply `azurerm_key_vault_certificate` resource after the file is created(the file is created while applying resource `local_file`)

### Actual Behaviour
```
Error: Invalid function argument
  on main.tf line 63, in resource "azurerm_key_vault_certificate" "pfx":
     contents = filebase64(local_file.certificate_pfx.filename)
     local_file.certificate_pfx.filename is "certs/somedomain-com.pfx"
Invalid value for "path" parameter: no file exists at certs/somedomain-com.pfx; this function works only with files that are distributed as part of the configuration source code, so if this file will be created by a resource in this configuration you must instead obtain this result from an attribute of that resource.
```
also tried with `depends_on` but still get the same error

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by MattiasAng** [comment]
Try changing filename to:

`filename       = "${path.module}/certs/${var.cert_name}.pfx"`

**Comment by ValeruS** [comment]
I made the change but I get the same error

The resource `azurerm_key_vault_certificate` is looking for the file(physical file) to already be in the indicated location
but the file is creating after is applied `"local_file certificate_pfx"`

**Comment by a30004053** [comment]
Do we have an update on this? 

We can't possibly expect teams to commit certificates and the private key into code

**Comment by tombuildsstuff** [comment]
hi @ValeruS 

Thanks for opening this issue - apologies for the delayed reply to this one.

Taking a look through here this appears to be a usage question regarding Terraform Core, since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - we ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
