### ISSUE TITLE
Implement Cost management Exports for Billing Account Scope

### ISSUE THREAD

**Issue by CalvinRodo** [hashicorp/terraform-provider-azurerm#14726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to create a cost management export with the scope being the billing account. We use enterprise enrolment for Azure and this would be super useful for us, at the moment we can do exports for Resource Groups and Subscriptions. 

### References

* https://github.com/hashicorp/terraform-provider-azurerm/issues/11598 was not fully satisifed as https://github.com/hashicorp/terraform-provider-azurerm/pull/14140 only partially closed it by adding subscription scope for cost management.

**Comment by twhite-coles** [comment]
I've attempted to use the new azapi for the time being whilst we wait for this functionality. Whilst it works (creates the Exports at a Billing Account Scope) it won't complete in TF and then write to the state:

azapi_resource.costexports-actualcost: Creating...
azapi_resource.costexports-actualcost: Still creating... [10s elapsed]
azapi_resource.costexports-actualcost: Still creating... [20s elapsed]
azapi_resource.costexports-actualcost: Still creating... [30s elapsed]
azapi_resource.costexports-actualcost: Still creating... [40s elapsed]
azapi_resource.costexports-actualcost: Still creating... [50s elapsed]
azapi_resource.costexports-actualcost: Still creating... [1m0s elapsed]
╷
│ Error: creating/updating "Resource: (ResourceId \"/providers/Microsoft.Billing/billingAccounts/<BILLING_ACCT_#>/providers/Microsoft.CostManagement/exports/TW-ColesActualCostTEST\" / Api Version \"2021-10-01\")": Get "[https://costmanagement.trafficmanager.net/providers/Microsoft.Billing/billingAccounts/<BILLING_ACCT_#>/providers/Microsoft.CostManagement/exports/TW-ColesActualCostTEST?api-version=2021-10-01"](https://costmanagement.trafficmanager.net/providers/Microsoft.Billing/billingAccounts/<BILLING_ACCT_#>/providers/Microsoft.CostManagement/exports/TW-ColesActualCostTEST?api-version=2021-10-01%22): **local error: tls: no renegotiation**
│ 
│   with azapi_resource.costexports-actualcost,
│   on main.tf line 58, in resource "azapi_resource" "costexports-actualcost":
│   58: resource "azapi_resource" "costexports-actualcost" {
│ 
╵

**Comment by haimdagan8** [comment]
UP

**Comment by ms-henglu** [comment]
Thanks @twhite-coles !

Yes, there's an issue in azapi repo tracking this: https://github.com/Azure/terraform-provider-azapi/issues/184
And the root cause is : https://github.com/Azure/azure-sdk-for-go/issues/19469
