### ISSUE TITLE
Support for creating child DNS-zone

### ISSUE THREAD

**Issue by AlekseyKalinin** [hashicorp/terraform-provider-azurerm#14733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kindly ask you to support creating a child DNS-zone for existing parent Azure DNS-zone.

### New or Affected Resource(s)

* azurerm_dns_zone

### Potential Terraform Configuration

```hcl
resource "azurerm_dns_zone" "parent_zone" {
  name                = "parent.com"
  resource_group_name = azurerm_resource_group.resource_group.name
}

resource "azurerm_dns_zone" "child_zone" {
  name                = "child.parent.com"
  resource_group_name = azurerm_resource_group.resource_group.name
  parent_zone_name = azure_dns_zone.parent_zone.name
}
```

### References

* [Tutorial: Creating a new Child DNS zone](https://docs.microsoft.com/en-us/azure/dns/tutorial-public-dns-zones-child)

**Comment by favoretti** [comment]
Hi there and thank you for reporting this issue. Unfortunately when I look at the SDK or rest-api-specs - this functionality is not supported anywhere yet. Feel free to log an issue for rest-api-specs MSFT repo requesting this functionality though, as soon as they release support for it - we can implement it in the provider.

**Comment by AlekseyKalinin** [comment]
Hi @favoretti 
Thank you for reply.
It's strange, but azure cli could create child zones - [az network dns zone](https://docs.microsoft.com/en-us/cli/azure/network/dns/zone?view=azure-cli-latest#az_network_dns_zone_create)
I have downloaded a template from the Azure Portal and I see the parameter parentDnsZoneName inside parameters section. Here is the generated template:
```json
{
    "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
        "dnsZonesName": {
            "type": "string"
        }
    },
    "resources": [
        {
            "apiVersion": "2016-04-01",
            "type": "Microsoft.Network/dnsZones",
            "name": "[parameters('dnsZonesName')]",
            "location": "global",
            "dependsOn": [],
            "tags": {},
            "properties": {}
        },
        {
            "apiVersion": "2018-05-01",
            "name": "NameServerDelegation-0ae1c23d80ba4c2c8516195ab60ce020",
            "type": "Microsoft.Resources/deployments",
            "resourceGroup": "ss-stage",
            "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "properties": {
                "mode": "Incremental",
                "templateLink": {
                    "uri": "https://dns.hosting.portal.azure.net/dns/Content/4.12.0.1739/Dns/Templates/NSDelegationLinkedTemplate.json",
                    "contentVersion": "1.0.0.0"
                },
                "parameters": {
                    "nsServers": {
                        "value": "[reference(parameters('dnsZonesName')).nameServers]"
                    },
                    "parentDnsZoneName": {
                        "value": "parent.com"
                    },
                    "dnsZoneName": {
                        "value": "[parameters('dnsZonesName')]"
                    }
                }
            },
            "dependsOn": [
                "[parameters('dnsZonesName')]"
            ]
        }
    ]
}
```
Could you try to add this parameter and test it?

**Comment by favoretti** [comment]
@AlekseyKalinin As you can see it's a generic ARM deployment that it generates. DNS API itself has no support for delegation. https://github.com/Azure/azure-sdk-for-go/blob/9c90938df1e8a1dc239d21679acc32a7d00f4635/services/dns/mgmt/2018-05-01/dns/models.go#L880

I can add a TF parameter, but if there's nothing on the API side to assign it to.. ;)

**Comment by favoretti** [comment]
As a workaround you can use `azurerm_resource_group_template_deployment` and wrap that generated RM template in it.

**Comment by heoelri** [comment]
You can achieve the same by creating the required NS record in the parent dns zone. 

Here's an example how this can be done using a `data` resource to load the details of the parent zone, create a "sub" dns zone via `azurerm_dns_zone` and create a NS record in the parent zone (pointing to the sub-zone) via `azurerm_dns_ns_record`. Hope that helps.

```hcl
## load parent (existing) dns zone
data "azurerm_dns_zone" "parent" {
  name                = "my-dns-zone.tld"
  resource_group_name = "parent-dns-rg"
}

# create sub-dns resource group
resource "azurerm_resource_group" "example" {
  name     = "sub-dns-rg"
  location = "North Europe"
}

# create sub-dns zone
resource "azurerm_dns_zone" "example" {
  name                = "sub.${data.azurerm_dns_zone.parent.name}"
  resource_group_name = azurerm_resource_group.example.name
}

# create ns record for sub-zone in parent zone
resource "azurerm_dns_ns_record" "example" {
  name                = "sub" # only the flat name not the fqdn
  zone_name           = data.azurerm_dns_zone.parent.name
  resource_group_name = data.azurerm_dns_zone.parent.resource_group_name
  ttl                 = 60

  records = azurerm_dns_zone.example.name_servers
}
```

**Comment by AlekseyKalinin** [comment]
@heoelri , thank you for the great workaround. I've successfully created sub DNS-zone using your solution.
