### ISSUE TITLE
[Azure][FileShare][Terraform version = "=2.90.0"] HTTP headers is not in the correct format

### ISSUE THREAD

**Issue by AdimUser** [hashicorp/terraform-provider-azurerm#14737]
│ Error: creating Share "fileshare" (Account "stxsoarconfigslab" / Resource Group "rg-XXXXX-lab"): shares.Client#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:61b909b9-501a-0055-3d40-fb496d000000\nTime:2021-12-27T16:39:41.3366258Z"
│ 

![image](https://user-images.githubusercontent.com/15202718/147491094-ddc50c32-4442-4cce-9849-71eb99e7f6ac.png)

```
resource "azurerm_storage_account" "storageAccount" {
  name                     = "${var.storage_account_name}"
  resource_group_name      = "${var.resource_group_name}"
  location                 = "${var.location}"
  allow_blob_public_access = true
  account_tier             = "Premium"
  account_kind             = "FileStorage"
  account_replication_type = "LRS"
  tags                     = var.tags
}

resource "azurerm_storage_share" "fileShare" {
  name                 = "${var.file_share_name}"
  storage_account_name = azurerm_storage_account.storageAccount.name
  quota                = "${var.file_share_size}"
  enabled_protocol     = "NFS"

  acl {
    id = "MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTI"

    access_policy {
      permissions = "${var.file_share_permissoins}"
    }
  }
}
```

**Comment by dsab123** [comment]
Bump. I have azurerm v2.91.0 and terraform v1.0.11

**Comment by owenfarrell** [comment]
@AdimUser - I stumbled across this same issue when trying to run some acceptance tests for #16574. I think the bug here is specifically related to how the provider is validating the `quota` attribute.

- For premium accounts, the quota must be in the range of 100 to 102400.
- For standard accounts, the quota must be in the range of 1 to 5120

I see you're injecting quota as a variable. Out of curiosity, what value are you providing there?

@dsab123 - I wasn't able to replicate an error with your configuration. In version 2 of the provider, the default quota is 5120, which is valid for both standard and premium tier storage accounts. And I don't see replication type influencing that attribute.

**Comment by digitalkram** [comment]
@owenfarrell your comment made my day. :+1: 

I had the same issue that @AdimUser encountered and using a quota of 100 instead of 50 for a share in a premium storage account "fixed" it. So it seems the `quota` attribute is indeed not validated correctly.

**Comment by eking-go** [comment]
> @AdimUser - I stumbled across this same issue when trying to run some acceptance tests for #16574. I think the bug here is specifically related to how the provider is validating the `quota` attribute.
> 
> * For premium accounts, the quota must be in the range of 100 to 102400.
> * For standard accounts, the quota must be in the range of 1 to 5120
> 
> I see you're injecting quota as a variable. Out of curiosity, what value are you providing there?
> 
> @dsab123 - I wasn't able to replicate an error with your configuration. In version 2 of the provider, the default quota is 5120, which is valid for both standard and premium tier storage accounts. And I don't see replication type influencing that attribute.

I tried to create share with the same quota for premium and standard tier - 128 (so, it is correct for both ranges)

All ok for the Premium storage account and error for the Standard

╷
│ Error: creating Share "share1" (Account "****" / Resource Group "*****"): shares.Client#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:*****\nTime:2023-05-04T11:30:15.5115880Z"

hashicorp/azurerm v3.54.0

**Comment by henkepa** [comment]
A generic solution that applies the max value considering the tier:

`data  "azurerm_storage_account" "default" {
  name                     = var.StorageAccountDefaultName
  resource_group_name      = data.azurerm_resource_group.shared.name
}


resource "azurerm_storage_share" "default" {
  name                 = "default"
  storage_account_name = data.azurerm_storage_account.default.name
  quota                = data.azurerm_storage_account.default.account_tier == "Standard" ? 5120 : 102400
}`

**Comment by eking-go** [comment]
Hello.

Any updates about it?

**Comment by webstean** [comment]
Any update - getting this error as well?

resource "azurerm_storage_share" "nfs1" {
  for_each = azurerm_storage_account.nfs

  storage_account_name = each.value.name

  name             = "default"
  enabled_protocol = "NFS"
  // 100GB is the minimum
  quota = 1000

  depends_on = [
    azurerm_role_assignment.nfs
  ]
}

Results in

Error: creating Share "default" (Account "lscpnfssydstorage01" / Resource Group "shared-syd-nfs-rg"): shares.Client#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:55bacddd-e01a-0063-4946-ed77df000000\nTime:2023-09-22T11:18:24.5952043Z"
│ 
│   with azurerm_storage_share.nfs1["sydney"],
│   on storage-nfs.tf line 138, in resource "azurerm_storage_share" "nfs1":
│  138: resource "azurerm_storage_share" "nfs1" {
│ 
╵
╷
│ Error: creating Share "default" (Account "lscpnfsmelstorage01" / Resource Group "shared-mel-nfs-rg"): shares.Client#Create: Failure responding to request: StatusCode=[40](https://github.com/lscph1929/lscph-azterraform/actions/runs/6273578234/job/17037339591#step:6:41)0 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.\nRequestId:19b2c79f-f01a-0070-2146-ed4a4d000000\nTime:2023-09-22T11:18:25.0062929Z"
│ 
│   with azurerm_storage_share.nfs1["melbourne"],
│   on storage-nfs.tf line 138, in resource "azurerm_storage_share" "nfs1":
│  138: resource "azurerm_storage_share" "nfs1" {
│

**Comment by webstean** [comment]
I still think this is an issue, because of the confusing error message (HTTP header not in correct format). If logic could be incorporated to check the account_tier must be Premium when account_kind  = "FileStorage" that would be fix.

**Comment by clowa** [comment]
This error can also occur in case the quota is set to an inappropriate value (eg. `< min` or `> max`). Premium NFS shares must have a quota > 100 GB.
