### ISSUE TITLE
Invalid WEBSITE_RUN_FROM_PACKAGE corrupts Function App 

### ISSUE THREAD

**Issue by alex-zyl** [hashicorp/terraform-provider-azurerm#14747]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform 1.1.2
- hashicorp/azurerm v2.90.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "restrict_access" {
  name                       = local.function_name
  resource_group_name        = azurerm_resource_group.function.name
  location                   = var.region
  app_service_plan_id        = azurerm_app_service_plan.restrict_access.id
  storage_account_name       = var.storage_name
  storage_account_access_key = var.storage_access_key
  os_type                    = "linux"
  version                    = "~3"

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = "INVALID_FUNCTION_ZIP_URL",
    "FUNCTIONS_WORKER_RUNTIME" = "dotnet",
  }
}

data "azurerm_function_app_host_keys" "restrict_access" {
  name                = azurerm_function_app.restrict_access.name
  resource_group_name = azurerm_resource_group.function.name
}
```

### Debug Output

None available

### Panic Output

None available

### Expected Behaviour

`azurerm_function_app` resource creation failed
Function App is created and properly configured.
Function zip is not deployed.

### Actual Behaviour

Function App creation succeeds. 
`azurerm_function_app_host_keys` reading fails with 
```
 Error: making Read request on AzureRM Function App Hostkeys "func_name": web.AppsClient#ListHostKeys: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Encountered an error (ServiceUnavailable) from host runtime." Details=[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}]
```
Function App is corrupted: Azure Functions runtime is unreachable

Subsequent `terraform apply` with corrected function zip url also fails during refresh phase:
```
azurerm_function_app.restrict_access: Refreshing state... [id=/subscriptions/000/resourceGroups/my_rg/providers/Microsoft.Web/sites/aztf32arasplm]
╷
│ Error: making Read request on AzureRM Function App Hostkeys "func_name": web.AppsClient#ListHostKeys: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Encountered an error (ServiceUnavailable) from host runtime." Details=[{"Message":"Encountered an error (ServiceUnavailable) from host runtime."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"Encountered an error (ServiceUnavailable) from host runtime."}}]
```

### Steps to Reproduce

1. Set WEBSITE_RUN_FROM_PACKAGE  to random invalid url
2. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. The azurerm_function_app resource is deprecated in version 3. 0 and will be removed in version 4.0 - so I'd suggest moving to the azurerm_linux_function_app and azurerm_windows_function_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_function_app and azurerm_windows_function_app resources please do let us know by opening a new issue, thanks!
