### ISSUE TITLE
Consistent InternalServerError Issue creating nsg flow logs

### ISSUE THREAD

**Issue by panasonixme** [hashicorp/terraform-provider-azurerm#14745]
Same issue as #13703

Community Note
Please vote on this issue by adding a +1 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment
Terraform (and AzureRM Provider) Version
Terraform 1.1.2

Affected Resource(s)
azurerm_network_watcher_flow_log

Terraform Configuration Files
resource "azurerm_network_watcher_flow_log" "nw_flow_log" {
  for_each = local.subnets_with_nsgs_and_flow_logs

  network_watcher_name      = data.azurerm_network_watcher.network_watcher.name
  resource_group_name       = data.azurerm_network_watcher.network_watcher.resource_group_name
  network_security_group_id = azurerm_network_security_group.nsg[each.key].id
  storage_account_id        = var.create_nsg_flow_logs_storage_account ? azurerm_storage_account.nsg_flow_logs_sa[0].id : var.nsg_flow_logs_storage_account_id
  enabled                   = true
  version                   = 2
  retention_policy {
    enabled = var.nsg_flow_logs_retention_enabled
    days    = var.nsg_flow_logs_retention_enabled ? var.nsg_flow_logs_retention_days : null
  }

  traffic_analytics {
    enabled               = true
    workspace_id          = var.create_log_analytics_workspace == false ? var.log_analytics_workspace_workspace_id : azurerm_log_analytics_workspace.log_analytics_workspace[0].workspace_id
    workspace_region      = var.location
    workspace_resource_id = var.create_log_analytics_workspace == false ? var.log_analytics_workspace_id : azurerm_log_analytics_workspace.log_analytics_workspace[0].id
    interval_in_minutes   = 10
  }

  tags = merge(local.default_tags, var.tags)

  lifecycle {
    ignore_changes = [
      tags["CreationDate"]
    ]
  }
}

Debug Output
Error: waiting for completion of creating "Flow Log: (Name \"Microsoft.Networkrg-vnet-itaag94-beta-weu-001nsg-snet-vm-beta-weu\" / Network Watcher Name \"NetworkWatcher_westeurope\" / Resource Group \"NetworkWatcherRG\")": Code="InternalServerError" Message="An error occurred." Details=[]
with module.network.azurerm_network_watcher_flow_log.nw_flow_log["snet-vm-beta-weu"]
on .terraform/modules/network/logging.tf line 135, in resource "azurerm_network_watcher_flow_log" "nw_flow_log":

Panic Output
Expected Behaviour
Able to create flow logs

Actual Behaviour
Unable to create NSG flow logs.

Steps to Reproduce
Add code to create flow logs with workspace and storage account destination
Terraform Apply

**Comment by neil-yechenwei** [comment]
Per the description of issue 13703, seems it's a Service API issue not Terraform issue. So filed an issue on Azure/azure-rest-api-specs/issues/17240.

**Comment by panasonixme** [comment]
This has been resolved suddenly...Not able to reproduce it any longer. We can close the ticket

**Comment by neil-yechenwei** [comment]
Thanks @panasonixme for double confirm. Suggest to close this ticket by yourself. Thanks.
