### ISSUE TITLE
Support for azurerm_security_center_subscription_pricing to accept "subscription" argument

### ISSUE THREAD

**Issue by gcolten** [hashicorp/terraform-provider-azurerm#14755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_security_center_subscription_pricing` manages the pricing tier settings for the _current_ subscription only. Having multiple subscriptions, and only one default subscription, it would be preferable to expose an argument to manually specify the subscription for this resource.

### New or Affected Resource(s)

* `azurerm_security_center_subscription_pricing`

### Potential Terraform Configuration

Current example options:
```hcl
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  resource_type = "VirtualMachines"
}
```

Proposed example options:
```hcl
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  subscription  = "XXXXX-..."
  resource_type = "VirtualMachines"
}
```

### References

* [`az security pricing create`](https://docs.microsoft.com/en-us/cli/azure/security/pricing?view=azure-cli-latest#az_security_pricing_create): Example of the Azure cli offering this feature with subscription context exposed.
* [`azure-sdk-for-go`](https://github.com/Azure/azure-sdk-for-go/blob/main/services/preview/security/mgmt/v3.0/security/pricings.go#L24): The Azure Go SDK exposes the option to specify appropriate subscription

**Comment by tombuildsstuff** [comment]
hi @gcolten 

Thanks for opening this issue.

Within the Azure Provider the Subscription ID argument can be configured against the Provider block, and intentionally isn't available against individual Resources, as Resources can be configured to use a different Provider (which uses a different Subscription) as shown below:

```hcl
provider "azurerm" {
  subscription_id = "..."
  alias = "first"
}

provider "azurerm" {
  subscription_id = "..."
  alias = "second"
}

resource "azurerm_resource_group" "first" {
  name = "first-resource-group"
  location = "West Europe"
  provider = azurerm.first
}

resource "azurerm_resource_group" "second" {
  name = "second-resource-group"
  location = "West Europe"
  provider = azurerm.second
}
```

As this functionality is already available in Terraform unfortunately we're not planning on adding a `subscription_id` argument to individual resources - and as such whilst I'd like to thank you for opening this issue I'm going to close this for the moment.

Thanks!
