### ISSUE TITLE
Support for scheduling runbooks 'azurerm_automation_runbook'

### ISSUE THREAD

**Issue by jbla9028** [hashicorp/terraform-provider-azurerm#14751]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As part of maintaining runbooks, we need to not only create and modify runbooks, but we need to be able to apply a schedule to a runbook. We can successfully create a runbook (azurerm_automation_runbook) and a schedule (azurerm_automation_schedule) but it doesn't appear when we create the azurerm_automation_runbook we have the ability to link it to one or more azurerm_automation_schedule resources.

### New or Affected Resource(s)

azurerm_automation_schedule
azurerm_automation_runbook

* azurerm_2.90

### Potential Terraform Configuration

```hcl
resource "azurerm_automation_schedule" "example1" {
  name                    = "tfex-automation-schedule1"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  frequency               = "Week"
  interval                = 1
  timezone                = "Australia/Perth"
  start_time              = "2014-04-15T18:00:15+02:00"
  description             = "This is an example schedule"
  week_days               = ["Friday"]
}

resource "azurerm_automation_schedule" "example2" {
  name                    = "tfex-automation-schedule2"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  frequency               = "Week"
  interval                = 1
  timezone                = "Australia/Perth"
  start_time              = "2014-04-15T18:00:15+02:00"
  description             = "This is an example schedule"
  week_days               = ["Friday"]
}

resource "azurerm_automation_runbook" "example" {
  name                    = "Get-AzureVMTutorial"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  log_verbose             = "true"
  log_progress            = "true"
  description             = "This is an example runbook"
  runbook_type            = "PowerShellWorkflow"

  publish_content_link {
    uri = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/c4935ffb69246a6058eb24f54640f53f69d3ac9f/101-automation-runbook-getvms/Runbooks/Get-AzureVMTutorial.ps1"
  }
  schedules = [azurerm_automation_schedule.example1.id, azurerm_automation_schedule.example2.id]
}

```

### References

* #0000

**Comment by TCPIPStack** [comment]
You need to use azurerm_automation_job_schedule:
`resource "azurerm_automation_job_schedule" "example" {
  resource_group_name     = "tf-rgr-automation"
  automation_account_name = "tf-automation-account"
  schedule_name           = "hour"
  runbook_name            = "Get-VirtualMachine"

  parameters = {
    resourcegroup = "tf-rgr-vm"
    vmname        = "TF-VM-01"
  }
}`

Source: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_job_schedule

**Comment by tombuildsstuff** [comment]
hey @jbla9028 

Thanks for opening this issue.

[As @TCPIPStack has mentioned](https://github.com/hashicorp/terraform-provider-azurerm/issues/14751#issuecomment-1014369917), support for this is available in the `azurerm_automation_job_schedule` resource, can you take a look and see if that works for you?

Since it appears that support for this functionality is already available I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
