### ISSUE TITLE
Error to be prompted for Read replicas on azure database for mysql server when using basic price tier

### ISSUE THREAD

**Issue by Gokul-Rams** [hashicorp/terraform-provider-azurerm#14769]
Read replicas is only supported in General and Memory optimized price tier of azure database for mysql service, but usage of terraform code with create_mode as replica on basic price tier does not prompt for any error when primary and read replicas are created seperately on seperate consecutive terraform apply 
In another scenario where both created on single terraform apply throws contact support the response from Azure API instead of prompts specifing read replicas not supported for basic tier

**Comment by neil-yechenwei** [comment]
@Gokul-Rams , thanks for raising this issue. If my understanding is correct, you mean creating mysql server with create_mode="replica" and sku_name="B_xxx" should fail and throw error message but it doesn't, right? But after tested with below tf config, seems this scenario would fail and throw error message. If my understanding is wrong, could you share your tf config and error message and the symptom and the expectation? Thanks in advance.

my tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-mysqldb-test01"
  location = "eastus"
}

resource "azurerm_mysql_server" "test" {
  name                             = "acctestmysqlsvr-test01"
  location                         = azurerm_resource_group.test.location
  resource_group_name              = azurerm_resource_group.test.name
  sku_name                         = "B_Gen5_2"
  administrator_login              = "acctestun"
  administrator_login_password     = "A@Sh1BoR3!"
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_1"
  storage_mb                       = 51200
  version                          = "8.0"
}

resource "azurerm_mysql_server" "replica" {
  name                = "acctestmysqlsvr-test01-replica"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku_name            = "B_Gen5_2"
  version             = "8.0"
  storage_mb          = 51200

  create_mode                      = "Replica"
  creation_source_server_id        = azurerm_mysql_server.test.id
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_1"
}
```

Error message:
```
azurerm_mysql_server.replica: Still creating... [30s elapsed]
╷
│ Error: waiting for creation of Server: (Name "xxxxxx" / Resource Group "xxxxxx"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'xx-xx-xx-xx'"
│
│   with azurerm_mysql_server.replica,
│   on main.tf line 23, in resource "azurerm_mysql_server" "replica":
│   23: resource "azurerm_mysql_server" "replica" {
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed without a response, I am going to close this issue. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!
