### ISSUE TITLE
Redis AOL - sensitive data update in place 

### ISSUE THREAD

**Issue by rmtier** [hashicorp/terraform-provider-azurerm#14772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.1.2
on linux_amd64
provider registry.terraform.io/hashicorp/azurerm v2.90.0
```

### Affected Resource(s)

* `azurerm_redis_cache`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage_account" {
  count = 1
  name                      = "withoutmodule"
  resource_group_name       = "XXX"
  location                  = "West Europe"
  account_tier              = "Standard"
  account_replication_type  = "GRS"
  account_kind              = "StorageV2"
  enable_https_traffic_only = true
  is_hns_enabled            = false
  min_tls_version           = "TLS1_2"
  allow_blob_public_access  = false
}


resource "azurerm_redis_cache" "replication" {
  name                = "redis-testing"
  location            = "West Europe"
  resource_group_name = "XXX"
  capacity            = 1
  family              = "P"
  sku_name            = "Premium"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  subnet_id           = null
  private_static_ip_address = null

  dynamic redis_configuration {
    for_each = azurerm_storage_account.storage_account
    content {
      maxmemory_policy = "allkeys-lru"
      aof_backup_enabled = true
      aof_storage_connection_string_0 = redis_configuration.value.primary_connection_string
      aof_storage_connection_string_1 = redis_configuration.value.secondary_connection_string
    }
  }
}
```

### Expected Behaviour

Do not detect change on aof_storage_connection_string_0 and aof_storage_connection_string_1.

Or at least do warning (#28738)

Note: this sensitive attribute value will be marked as
sensitive, but its value is unchanged

### Actual Behaviour
Detect change without warning on every apply.

```
~ redis_configuration {
        ~ aof_storage_connection_string_0 = (sensitive value)
        ~ aof_storage_connection_string_1 = (sensitive value)
           # (12 unchanged attributes hidden)
     }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### References

* Same issue I was reporting on terraform core repo https://github.com/hashicorp/terraform/issues/30240

**Comment by xuzhang3** [comment]
@rmtier  Redis service will  reformat and mask the `aof` connection strings,  workaround is to add `ignore_changes` for those two properties:

```hcl
lifecycle {
    ignore_changes =[
      redis_configuration.0.aof_storage_connection_string_0,
      redis_configuration.0.aof_storage_connection_string_1
    ]
  }
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained. As noted by the contributor @xuzhang3, this issue appears to be caused by the Redis service upstream. If you are still experiencing this issue in the latest provider, you can open an upstream issue with Microsoft: https://github.com/Azure/azure-rest-api-specs, thanks!
