### ISSUE TITLE
HDInsight Network block missing for HBase

### ISSUE THREAD

**Issue by spotakash** [hashicorp/terraform-provider-azurerm#14777]
HDInsight now support deployment with Private Link. We have noticed post recent update of HDInsight API, Terraform provider started showing network block in azurerm_hdinsight_spark_cluster . https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_spark_cluster
![image](https://user-images.githubusercontent.com/7689697/148001590-33c3dbe4-0194-44f8-99be-7d1f017462aa.png)

But, I can’t find it in hbase azurerm_hdinsight_hbase_cluster. I request if you can provide some insight when it is estimated to be updated. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_hbase_cluster

Absence of Network hamper HDInsight Hbase deployment via Terraform. 
From Portal experience or CLI or PWSH, it seems possible even for HBbase cluster.

**Comment by brucema-cloud** [comment]
Thank you for your support @katbyte @spotakash
