### ISSUE TITLE
azurerm_key_vault - adding virtual_network_subnet_ids only works on 2nd 'apply'

### ISSUE THREAD

**Issue by asaf-upstream** [hashicorp/terraform-provider-azurerm#14783]
### Affected Resource(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.0.3"
required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.90.0"
    }
}

resource "azurerm_key_vault" "kv" {
  location            = local.location
  name                = local.kv_name
  resource_group_name = var.rg_name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "premium"

  purge_protection_enabled = true

  network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"
    virtual_network_subnet_ids = [var.vnet_subnet_id]
    ip_rules                   = ["5.5.5.5/32"]
  }

  tags = module.outputs.calc_tags
}

```

### Expected Behaviour

TF should add an exception rule for the virtual_network_subnet_ids (ip rule is created)

### Actual Behaviour

Seems that TF adds the rule only in the state file, but not in the actual infra env.
I even tried to pass a vnet as a hard-coded string, and not a var, but getting the same result.

### Steps to Reproduce

1. `terraform apply`
2. Verify that vent rule was not created.
3. `terraform apply` again will mark the resource as if it was changed, and the vnet rule was removed. The 2nd apply will add the rule for the 1st time.

**Comment by sinbai** [comment]
I can't reproduce the issue. When I run `terraform apply` for the first time in my test, the `virtual_network_subnet_ids` can be added to the key vault. Could you share the complete tf config file and the screenshot of the failure results?  Below are my repro steps:

1. terraform apply runs the following tf config file.

> ```
> provider "azurerm" {
>   features {}
> }
> 
> terraform {
>   required_providers {
>     azurerm = {
>       source = "hashicorp/azurerm"
> 	  version = "2.90.0"
>     }
>   }
> }
> 
> data "azurerm_client_config" "current" {
> }
> 
> resource "azurerm_resource_group" "test" {
>   name     = "elena_test_rg1"
>   location = "eastus"
> }
> 
> resource "azurerm_virtual_network" "test" {
>   name                = "elena_test_vnet"
>   address_space       = ["10.0.0.0/16"]
>   location            = azurerm_resource_group.test.location
>   resource_group_name = azurerm_resource_group.test.name
> }
> 
> resource "azurerm_subnet" "test" {
>   name                 = "elena_test_subnet"
>   resource_group_name  = azurerm_resource_group.test.name
>   virtual_network_name = azurerm_virtual_network.test.name
>   address_prefixes       = ["10.0.2.0/24"]
>   service_endpoints    = ["Microsoft.KeyVault"]
> }
> 
> resource "azurerm_key_vault" "kv" {
>   location            = "eastus"
>   name                = "elenatestkv1"
>   resource_group_name = azurerm_resource_group.test.name
>   tenant_id           = data.azurerm_client_config.current.tenant_id
> 
>   sku_name = "premium"
> 
>   purge_protection_enabled = true
> 
>   network_acls {
>     default_action             = "Deny"
>     bypass                     = "AzureServices"
>     virtual_network_subnet_ids = [azurerm_subnet.test.id]
>     ip_rules                   = ["5.5.5.5/32"]
>   }
> 
>  tags = {
>     environment = "test"
>   }
> }
> ```

2. Verify the results on the portal, both`virtual_network_subnet_ids ` and `ip_rules ` are successfully added to the key vault, details:
    <img width="887" alt="kv" src="https://user-images.githubusercontent.com/39109137/148190890-928acb23-6767-41a0-91c0-3465faf719b9.png">

**Comment by asaf-upstream** [comment]
Hi @sinbai , thx for your help!
Not sure, seems like a really strange one..
1. Run apply the 1st time:
![Screen Shot 2022-01-05 at 13 31 49](https://user-images.githubusercontent.com/85824196/148217850-93cee4bd-992c-4645-af0d-85f8eb5960bf.png)

2. Vnet would not appear in the vault's networking:
![Screen Shot 2022-01-05 at 14 21 05](https://user-images.githubusercontent.com/85824196/148218009-fb88bc43-0950-48ae-b0c2-b0fb45d2d76f.png)

3. On 2nd apply, TF thinks the rule was removed, and wants to add it "again":
![Screen Shot 2022-01-05 at 14 23 15](https://user-images.githubusercontent.com/85824196/148218107-c75c6e18-4441-4684-9bba-07874cbafa5d.png)
![Screen Shot 2022-01-05 at 14 23 27](https://user-images.githubusercontent.com/85824196/148218136-01caff3f-2bc1-497d-a475-dd53232064c2.png)


Attaching full tf code:
`data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "kv" {
  location            = local.location
  name                = local.kv_name
  resource_group_name = var.rg_name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  sku_name = "premium"

  network_acls {
    default_action             = "Deny"
    bypass                     = "AzureServices"
    virtual_network_subnet_ids = [var.vnet_subnet_id]
    ip_rules                   = ["5.5.5.5/32"]
  }

  tags = module.outputs.calc_tags
}

resource "azurerm_key_vault_access_policy" "kv_access_policy" {
  for_each     = toset(var.additional_admins_object_id)
  key_vault_id = azurerm_key_vault.kv.id
  object_id    = each.value
  tenant_id    = data.azurerm_client_config.current.tenant_id

  key_permissions = [
    "backup",
    "create",
    "decrypt",
    "delete",
    "encrypt",
    "get",
    "import",
    "list",
    "purge",
    "recover",
    "restore",
    "sign",
    "unwrapKey",
    "wrapKey",
    "update",
    "verify"
  ]

  secret_permissions = [
    "backup",
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set"
  ]

  certificate_permissions = [
    "backup",
    "create",
    "delete",
    "deleteissuers",
    "get",
    "getissuers",
    "import",
    "list",
    "listissuers",
    "managecontacts",
    "manageissuers",
    "purge",
    "recover",
    "restore",
    "setissuers",
    "update"
  ]

  depends_on = [
    azurerm_key_vault.kv
  ]
}

`
Not sure what I am doing wrong, and if this issue happens only to me..

**Comment by sinbai** [comment]
I still can't repro. Two requirements:

1. Could you try to repro this issue with tf config file in my repro steps?
2. Per the info provided in "1. Run apply the 1st time" , I found "virtual_network_subnet_ids = know after apply". The virtual_network_subnet_ids should exist before creating the KV. Could you provide the complete tf config file (includes the virtual_network_subnet) and the complete repro steps? The detailed information would help me to repro this issue, thank you.
