### ISSUE TITLE
Define and output the TOKEN EXPIRY INSTANT for azurerm_eventhub_authorization_rule

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform-provider-azurerm#14788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When [calling an Event Hub Namespace we need to use a SAS token](https://docs.microsoft.com/en-us/rest/api/eventhub/event-hubs-runtime-rest?WT.mc_id=AZ-MVP-5003548#common-headers) that is composed like that `Authorization: SharedAccessSignature sr=<NAMESPACE NAME>.servicebus.windows.net&sig=<SHARED ACCESS KEY>&se=<TOKEN EXPIRY INSTANT>&skn=<SHARED KEY NAME>`.

The Terraform azurerm_eventhub_authorization_rule permits to gather the Namespace, the Shared Access Key, the Shared Key Name but not the TOKEN EXPIRY INSTANT.

See the following documentation that shows how to [generate a SAS token](https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token?WT.mc_id=AZ-MVP-5003548) with it's TOKEN EXPIRY INSTANT.

### New or Affected Resource(s)

* azurerm_eventhub_authorization_rule

### References

* [Event Hubs service REST - Common parameters and headers](https://docs.microsoft.com/en-us/rest/api/eventhub/event-hubs-runtime-rest?WT.mc_id=AZ-MVP-5003548#common-headers)
* [Event Hubs - Generate SAS token](https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token?WT.mc_id=AZ-MVP-5003548)

**Comment by neil-yechenwei** [comment]
@JamesDLD , thanks for raising this issue. After take a look. seems this issue is duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/7160. So is it ok to close this issue and subscribe issue 7160 since issue 7160 is already tracking this issue?

**Comment by JamesDLD** [comment]
Sure
