### ISSUE TITLE
Error creating azurerm_hdinsight_spark_cluster for HDInsight on Azure with Terraform

### ISSUE THREAD

**Issue by brucema-cloud** [hashicorp/terraform-provider-azurerm#14780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform {
  required_version = "= 0.14.11"
}

provider "azurerm" {
  version = "~> 2.0"
}

### Affected Resource(s)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_spark_cluster

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Error Output
```
Error: creating HDInsight Spark Cluster "spark02-stg-stream" (Resource Group "rg-stg-stream"): hdinsight.ClustersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Storage account 'name' in storage profile cannot be null or empty"

  on ../../../modules/azure/hdinsight-spark/main.tf line 1, in resource "azurerm_hdinsight_spark_cluster" "hid_spark_cluster":
   1: resource "azurerm_hdinsight_spark_cluster" "hid_spark_cluster" {
```

### Plan Output
```
module.hdi-stg-spark-stream.azurerm_hdinsight_spark_cluster.hid_spark_cluster will be created
  + resource "azurerm_hdinsight_spark_cluster" "hid_spark_cluster" {
      + cluster_version               = "4.0"
      + encryption_in_transit_enabled = (known after apply)
      + https_endpoint                = (known after apply)
      + id                            = (known after apply)
      + location                      = "southeastasia"
      + name                          = "spark02-stg-stream"
      + resource_group_name           = "xxxx"
      + ssh_endpoint                  = (known after apply)
      
      + tier                          = "Standard"

      + component_version {
          + spark = "2.4"
        }

      + gateway {
          + enabled  = true
          + password = (sensitive value)
          + username = "admin"
        }

      + network {
          + connection_direction = "Outbound"
          + private_link_enabled = false
        }

     ........................

      + storage_account {
          + is_default           = true
          + storage_account_key  = (sensitive value)
          + storage_container_id = "/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxxx/blobServices/default/containers/spark-test02"
        }
    }
```

### References

* #0000

**Comment by brucema-cloud** [comment]
I have specified the storage_account block, but it shows "Storage account 'name' in storage profile cannot be null or empty" when I apply.

**Comment by brucema-cloud** [comment]
Even though I set the azurerm version to 2.90,  it still reports the same error.

**Comment by sinbai** [comment]
Hi @brucema-cloud  

The storage_container_id  should be "https://{storage_account_name}.blob.core.windows.net/{azurerm_storage_container_name}". Could you try to replace "/subscriptions/xxxxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxxx/blobServices/default/containers/spark-test02" with the correct storage container id and try again? 

If this issue persists, could you provide the full terraform configuration file?

**Comment by brucema-cloud** [comment]
Thank you. Please let me try out the storage_container_id that you provided, then update you.

**Comment by brucema-cloud** [comment]
Hi @sinbai 
It shows another error when I try out the correct storage container id format you provided.
### Error output
`Error: creating HDInsight Spark Cluster "spark2-stg-stream" (Resource Group "rg-stg-stream"): hdinsight.ClustersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Resource ID is missing or invalid but required for storage account ststgstreamspark when NetworkProperties has ResourceProviderConnection set to Outbound. The ID takes format like /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$ACCOUNT_NAME and can be found in Storage Account Properties from Azure Portal"`
 
### Plan output
```
# module.hdi-stg-spark-stream.azurerm_hdinsight_spark_cluster.hid_spark_cluster will be created
  + resource "azurerm_hdinsight_spark_cluster" "hid_spark_cluster" {
      + cluster_version               = "4.0"
      + encryption_in_transit_enabled = (known after apply)
      + https_endpoint                = (known after apply)
      + id                            = (known after apply)
      + location                      = "southeastasia"
      + name                          = "xxxx"
      + resource_group_name           = "xxxx"
      + ssh_endpoint                  = (known after apply)
     

      + component_version {
          + spark = "2.4"
        }

      + gateway {
          + enabled  = true
          + password = (sensitive value)
          + username = "xxxx"
        }

      + network {
          + connection_direction = "Outbound"
          + private_link_enabled = false
        }

      ......
      + storage_account {
          + is_default           = true
          + storage_account_key  = (sensitive value)
          + storage_container_id = "https://ststgstreamspark.blob.core.windows.net/spark-test02"
        }
    }
```

**Comment by brucema-cloud** [comment]
```
resource "azurerm_hdinsight_spark_cluster" "hid_spark_cluster" {
  name                = var.cluster_name
  resource_group_name = var.resource_group_name
  location            = var.location
  cluster_version     = var.cluster_version
  tier                = var.tier
  tags                = var.tags

  component_version {
    spark = var.spark_component_version
  }

  gateway {
    username = var.ambari_name
    password = var.ambari_pwd
  }

  storage_account {
    storage_container_id = var.storage_container_id
    storage_account_key  = var.storage_account_key
    is_default           = true
  }

  network {
    connection_direction = "Outbound"
  }

  roles {
    head_node {
      vm_size            = var.head_vm_size
      username           = var.username
      ssh_keys           = var.ssh_keys
      virtual_network_id = var.virtual_network_id
      subnet_id          = var.subnet_id
    }

    worker_node {
      vm_size               = var.worker_vm_size
      username              = var.username
      ssh_keys              = var.ssh_keys
      target_instance_count = var.target_instance_count
      virtual_network_id    = var.virtual_network_id
      subnet_id             = var.subnet_id

      autoscale {
        capacity {
          max_instance_count = var.max_instance_count
          min_instance_count = var.min_instance_count
        }
      }
    }

    zookeeper_node {
      vm_size            = var.zk_vm_size
      username           = var.username
      ssh_keys           = var.ssh_keys
      virtual_network_id = var.virtual_network_id
      subnet_id          = var.subnet_id
    }
  }
}
```

```
module "hdi-stg-spark-stream" {
  source                = "../../../modules/azure/hdinsight-spark"
  resource_group_name   = local.resource_group_name
  location              = local.location
  tags                  = local.common_tags
  ambari_name           = local.ambari_name
  ambari_pwd            = local.ambari_pwd
  cluster_name          = local.cluster_name
  head_vm_size          = local.head_vm_size
  ssh_keys              = local.ssh_keys
  storage_account_key   = local.storage_account_key
  storage_container_id  = "https://ststgstreamspark.blob.core.windows.net/spark-test02"
  subnet_id             = local.hdi_subnet_id
  username              = local.username
  virtual_network_id    = local.virtual_network_id
  worker_vm_size        = local.worker_vm_size
  zk_vm_size            = local.zk_vm_size
  target_instance_count = local.target_instance_count
  max_instance_count    = local.max_instance_count
  min_instance_count    = local.min_instance_count
}

**Comment by sinbai** [comment]
Hi @brucema-cloud

There is an [sample ](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/hdinsight/private-link/hadoop-interactive-spark-hbase-cluster) using network block on azurerm_hdinsight_spark_cluster. Maybe it could help you?

**Comment by brucema-cloud** [comment]
Hi @sinbai  the sample is not work for me. I used the `storage_account` block in `azurerm_hdinsight_spark_cluster`.  there is a argument `storage_container_id` in it.  I set the `connection_direction = "Outbound"` in network block.  When I use the `storage_container_id` takes format like `/subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$ACCOUNT_NAME`
it shows:
`Storage account 'name' in storage profile cannot be null or empty`
and When I use the `storage_container_id` takes format like  `https://{storage_account_name}.blob.core.windows.net/{azurerm_storage_container_name}`
it shows:
`Resource ID is missing or invalid `

I don't know where the problem is.

**Comment by brucema-cloud** [comment]
Hi @sinbai any update please?

**Comment by sinbai** [comment]
@brucema-cloud Sorry for the delay and thanks for reporting this issue. The "storage_container_id" should be formatted like https://{storage_account_name}.blob.core.windows.net/{azurerm_storage_container_name}. The error returned because the API requires the storage account id when NetworkProperties has ResourceProviderConnection set to Outbound. There is an incorrect description in the [API](https://github.com/Azure/azure-rest-api-specs/blob/d29e6eb4894005c52e67cb4b5ac3faf031113e7d/specification/hdinsight/resource-manager/Microsoft.HDInsight/stable/2021-06-01/cluster.json#L1176). I has submitted a PR to fix it in terraform.

**Comment by brucema-cloud** [comment]
Hi, @sinbai many thanks for your support. I want to confirm again when NetworkProperties has ResourceProviderConnection set to Outbound, the storage_container_id should be formatted like HTTPS://{storage_account_name}.blob.core.windows.net/{azurerm_storage_container_name}. Am I right?

**Comment by sinbai** [comment]
@brucema-cloud Yes. And you also need to add `storage_resource_id  ` in terraform config when NetworkProperties has ResourceProviderConnection set to Outbound, after the PR is merged and released. It should be format like /subscriptions/$SUBSCRIPTION_ID/resourceGroups/$RESOURCE_GROUP/providers/Microsoft.Storage/storageAccounts/$ACCOUNT_NAME.

**Comment by brucema-cloud** [comment]
Thank you so much @sinbai
