### ISSUE TITLE
AKS Spot Nodepool k8s version update not handled

### ISSUE THREAD

**Issue by george-zubrienko** [hashicorp/terraform-provider-azurerm#14786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- TF: 1.0.4
- AzureRM provider: ~> 2.86.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

Snippet below is valid for any node pool. Let me know if I need to provide more than that. So, having a *spot* node pool in AKS cluster:

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "any_node_pool" {
  name                 = "test"
  orchestrator_version = "1.21.2"

  kubernetes_cluster_id = azurerm_kubernetes_cluster.my_cluster.id
  
  ...
}
```

we update `orchestrator_version`:

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "any_node_pool" {
  name                 = "test"
  orchestrator_version = "1.21.7"

  kubernetes_cluster_id = azurerm_kubernetes_cluster.my_cluster.id
  
  ...
}
```

This is not allowed by AKS and Terraform proxies and error (see debug output). Expected behaviour is resource re-creation.

### Expected Behaviour

Nodepool is re-created with a new orchestrator version.

### Actual Behaviour

Apply fails with

```
Error: the Orchestrator Version cannot be updated when using a Spot Node Pool

  with azurerm_kubernetes_cluster_node_pool.my_worker_pool ...
```

### Steps to Reproduce

1. Create a spot nodepool in AKS cluster using examples from the repo.
2. Update orchestrator version
3. `terraform plan` - all good
4. `terraform apply` - failure.

### Important Factoids

N/A

**Comment by ms-henglu** [comment]
Hi @george-zubrienko , how about using replace option: https://www.terraform.io/cli/commands/plan#replace-address

**Comment by george-zubrienko** [comment]
> Hi @george-zubrienko , how about using replace option: https://www.terraform.io/cli/commands/plan#replace-address

Hi @ms-henglu 
This will definitely work as a **workaround**, but this doesn't solve the problem itself. Problem is, that `terraform plan` on this specific case tell us that in-place update is possible, but then `terraform apply` fails.

**Comment by polys** [comment]
While `-replace` works (and that's what we've been doing so far), it's not very practical and not automation-friendly.

You don't really want to always run apply with the replace option for every random change you make to your infrastructure. Having to add it when needed though, doesn't lend itself nicely to automated workflows.

Since, by their very nature, spot nodes are expected to disappear at any time, I don't think it's unreasonable for terraform to destroy the node pool before a K8s upgrade and then recreate it.

**Comment by ms-henglu** [comment]
Hi @george-zubrienko, @polys, 

Yes, I agree. I've submitted a PR to make this property `ForceNew=true`

**Comment by ms-henglu** [comment]
Hi @george-zubrienko , @polys,

Unfortunately this PR would break a large number of users, so it got closed, please check the details below.
https://github.com/hashicorp/terraform-provider-azurerm/pull/15285#issuecomment-1031168664

**Comment by george-zubrienko** [comment]
Hmm but why make it ForceNew globally? Couldn't you only ForceNew when it's `Priority` is `spot`?

**Comment by polys** [comment]
Exactly, you only need to force new only for spot pools and only if the k8s version is changing. I can't imagine how's that breaking given the very nature of spot instances. That's what people have to do by hand anyway.

**Comment by ms-henglu** [comment]
Hi all, here's another workaround, in the latest terraform release, https://github.com/hashicorp/terraform/releases/tag/v1.2.0-beta1, a new feature called `replace_triggered_by` can help with this issue, it allows `one to configure the replacement of a resource based on changes in a dependency.`

**Comment by zerodayyy** [comment]
Hi! It's now possible to update Spot node pools in place: https://github.com/Azure/AKS/issues/2134

It would be great if this functionality was implemented in the Terraform provider
