### ISSUE TITLE
Error: "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.

### ISSUE THREAD

**Issue by prabirkrsarkar** [hashicorp/terraform-provider-azurerm#14798]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform -version
Terraform v1.1.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0

### Affected Resource(s)

`azurerm_storage_account`

### Terraform Configuration Files

https://github.com/prabirkrsarkar/bug-30262

### Debug Output

https://gist.github.com/prabirkrsarkar/d307066e982e95d1ae20ae766ff53f09

### Expected Behaviour

Expect to create the DataLake Storage.

### Actual Behaviour

Creating an Azure Data Lake Storage (among other resources) by calling a child module 
from root module. Got the following error: -

(Note: - After creating DataLake Storage (in modules/analyze) we are whitelisting virtual_network_subnet_ids 
from subnets created in modules/predict.)
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.analyze.azurerm_storage_account.optra, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: 
   Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

### Steps to Reproduce

1. $ git clone https://github.com/prabirkrsarkar/bug-30262.git
2. Update values of parameters in main.tf, terraform.tfvars in root module
3. $ cd prerequisites and update values of params in terraform.tfvars
4. While still in prerequisites directory, run: $ terraform init && terraform apply
5. cd .. (to the root module level)
6. $ terraform init && terraform apply

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
