### ISSUE TITLE
No package for darwin_arm64

### ISSUE THREAD

**Issue by sa-** [hashicorp/terraform-provider-azurerm#14806]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
> terraform -v                   
Terraform v1.1.2
on darwin_arm64
```

`azurerm` version `2.46.0`

### Expected Behaviour

`terraform init` should work

### Actual Behavior & Steps to Reproduce

```
> terraform init          

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.46.0"...
╷
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/azurerm v2.46.0 does not have a package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all providers are available for all platforms. Other versions of
│ this provider may have different platforms supported.
╵
```

**Comment by tombuildsstuff** [comment]
hi @sa- 

Thanks for opening this issue.

Support for Apple Silicon is available in `v2.49.0` and later of the Azure Provider - as such you'd either need to upgrade the version of the Provider being used (FWIW the latest release is `v2.90.0`) - or run Terraform in x86 mode to use an an older Provider version.

Thanks!
