### ISSUE TITLE
azurerm_mysql_database default 'latin1' character_set applied no matter what you set in terraform config

### ISSUE THREAD

**Issue by AlexeyDP** [hashicorp/terraform-provider-azurerm#14807]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
2.90.0

Terraform v1.0.11
### Affected Resource(s)

* `azurerm_mysql_database`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_mysql_server" "example" {
  name                = "example-mysqlserver"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "mysqladminun"
  administrator_login_password = "H@Sh1CoR3!"

  sku_name   = "GP_Gen5_2"
  storage_mb = 5120
  version    = "8.0"

  auto_grow_enabled                 = true
  backup_retention_days             = 7
  geo_redundant_backup_enabled      = true
  infrastructure_encryption_enabled = true
  public_network_access_enabled     = false
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
}

resource "azurerm_mysql_database" "example" {
  name                = "exampledb"
  resource_group_name = azurerm_resource_group.example.name
  server_name         = azurerm_mysql_server.example.name
  charset             = "utf8mb4"
  collation           = "utf8mb4_general_ci"
}
```

1. Connect to the server 
2. Run `SELECT @@character_set_database, @@collation_database;`. Result: character_set database is "latin1"
3. Go to azure portal >> Open the db >> Settings >> Server parameters: Result: character_set_server is "latin1" 

### Expected Behaviour
Character_set and collation applied as described in Terraform files

### Actual Behaviour
Default Character_set and collation applied
Forces resource replacement during next run

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment]
@AlexeyDP, thanks for raising this issue. After tested with above tf config and latest azurerm provider, seems `charset` and `collation` can be set to `utf8mb4` and `utf8mb4_general_ci` successfully. And I also checked Azure portal and it shows the value what I set in tf config. Could you try above tf config with latest azurerm provider to see if the issue still exists? Thanks in advance.

**Comment by AlexeyDP** [comment]
not reproduced anymore, closing the issue
