### ISSUE TITLE
Support for Storage Account > Network ACLs > Resource Access Rules

### ISSUE THREAD

**Issue by trentmillar** [hashicorp/terraform-provider-azurerm#14816]
Is this feature on the roadmap and if so when is it planned?

*Grant access from Azure resource instances (preview)*
https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-cli#grant-access-from-azure-resource-instances-preview

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adding this via the portal,
![image](https://user-images.githubusercontent.com/1146672/148265765-0ff6eeb5-104a-45a0-ace8-da62728e27c1.png)

Azure CLI,

```
az storage account network-rule add \
    --resource-id /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myResourceGroup/providers/Microsoft.Synapse/workspaces/testworkspace \
    --tenant-id xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx \
    -g myResourceGroup \
    --account-name mystorageaccount
```

ARM Template example,

```
              "networkAcls": {
                    "resourceAccessRules": [
                        {
                            "tenantId": "c310a750-e829-44c0-ace2-f6f64605aa3c",
                            "resourceId": "[parameters('workspaces___externalid')]"
                        }
                    ],
                    "bypass": "AzureServices",
                    "virtualNetworkRules": [],
                    "ipRules": [],
                    "defaultAction": "Deny"
                },
```

### New or Affected Resource(s)

* azurerm_storage_account
* azurerm_storage_account_network_rules

### References

* https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-cli#grant-access-from-azure-resource-instances-preview

**Comment by magodo** [comment]
@trentmillar This feature is already supported by the `private_link_access` for both [azurerm_storage_account_network_rules](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_network_rules#endpoint_resource_id) and [azurerm_storage_account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#endpoint_resource_id).

Please check whether that meets your requirements.

**Comment by LaurentLesle** [comment]
hi @magodo this is different. The feature described in this issue is to grant (storage account in this example) permission access access to a remote service (ie: AML notebook to access storage content) based on its managed identity.

"Specify resource instances that will have access to your storage account based on their system-assigned managed identity."

[Details ](https://azure.microsoft.com/en-gb/updates/storage-resource-instance-rules-preview/#:~:text=You%20can%20now%20configure%20your%20storage%20accounts%20to,any%20resource%20group%20or%20subscription%20in%20the%20tenant.)

Looks like #10965 already mention it

**Comment by magodo** [comment]
Thank you @LaurentLesle for the clarification. I'm gonna close this issue in favor of the #10965.
