### ISSUE TITLE
azurerm_mysql_server storage is limited to 4TB but the resource itself can scale up to 16TB

### ISSUE THREAD

**Issue by jamie-sweeney** [hashicorp/terraform-provider-azurerm#14823]
Using provider 2.90.0 

If I try to create an instance  of sku  GP_Gen5_32 

with storage > 4 tb I get an error of:
Error: expected storage_mb to be in the range (5120 - 4194304), got 8454144 

Azure mysql supports 16TB -> [Azure Database for MySQL](https://docs.microsoft.com/en-us/azure/mysql/concepts-pricing-tiers)

Perhaps the provider uses General purpose Backend v1 and does not support V2 ?  [Storage](https://docs.microsoft.com/en-us/azure/mysql/concepts-pricing-tiers#storage)

I am able to terraform import an instance set as above.

```
...
            "location": "eastus",
            "name": "aws-migration-az-replica",
            "public_network_access_enabled": true,
            "resource_group_name": "aws-migration-test",
            "restore_point_in_time": null,
            "sku_name": "GP_Gen5_32",
            "ssl_enforcement": "Disabled",
            "ssl_enforcement_enabled": false,
            "ssl_minimal_tls_version_enforced": "TLSEnforcementDisabled",
            "storage_mb": 8454144,
            "storage_profile": [
              {
                "auto_grow": "Disabled",
                "backup_retention_days": 7,
                "geo_redundant_backup": "Disabled",
                "storage_mb": 8454144
              }
            ],
....
```

**Comment by aristosvo** [comment]
Hi @jamie-sweeney! Thanks for reporting this issue, I'll take a quick look what the problem is.

I'll keep you posted.

**Comment by jamie-sweeney** [comment]
rockstar !
