### ISSUE TITLE
azurerm_postgresql_flexible_server isn't recognising valid SKUs when the variable value changes

### ISSUE THREAD

**Issue by aaronswainonset** [hashicorp/terraform-provider-azurerm#14833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform (Cloud) 1.0.10

### Affected Resource(s)

* `azurerm_postgresql_flexible_server`

### Terraform Configuration Files

```hcl
variable "location" {
  type        = string
}

variable "rg_name" {
  type        = string
}

variable "tags" {
  type        = map(string)
}

variable "db_admin_password" {
  sensitive   = true
  type        = string
}

variable "db_admin_username" {
  sensitive   = true
  type        = string
}

variable "db_server_name" {
  type        = string
}

variable "db_server_sku_name" {
  type        = string
  default     = "B_Standard_B2s"
}

variable "db_server_version" {
  type        = string
  default     = "13"
}

resource "azurerm_postgresql_flexible_server" "db" {
  name                   = var.db_server_name
  resource_group_name    = var.rg_name
  location               = var.location
  administrator_login    = var.db_admin_username
  administrator_password = var.db_admin_password
  backup_retention_days  = 7
  storage_mb             = 131072
  sku_name               = var.db_server_sku_name
  version                = var.db_server_version
  zone                   = "1"
  tags                   = var.tags
}
```

### Debug Output

There is no output.

### Expected Behaviour

The `db_server_sku_name` variable's default value was "B_Standard_B1ms", and a PostgreSQL flex db was created, but then the `db_server_sku_name` variable's default value was changed to "B_Standard_B2s". Terraform should recognise the value changed and update the db accordingly.

I have also tried with "GP_Standard_D2s_v3" and "MO_Standard_E4s_v3".

As a test, I hardcoded the SKU and Terraform still doesn't recognise the change:

```hcl
resource "azurerm_postgresql_flexible_server" "db" {
  name                   = var.db_server_name
  resource_group_name    = var.rg_name
 ...
  sku_name               = "B_Standard_B2s"
}
```

As a further test, I manually changed the db SKU to "B_Standard_B2s" and set `db_server_sku_name` variable's default value to "B_Standard_B2s", and Terraform `plan` reported that it was going to change the SKU back to "B_Standard_B1ms".

### Actual Behaviour

Terraform `plan` doesn't seem to recognise the default value was changed and reports that there is nothing to apply. The db remains on the "B_Standard_B1ms" SKU.

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
@aaronswainonset, thanks for raising this issue. After tested with below tf config that is similar with yours and latest azurerm provider, `azurerm_postgresql_flexible_server.sku_name` can be updated successfully from `B_Standard_B1ms` to `B_Standard_B2s`. Could you try below tf config with latest azurerm provider to see if the issue still exists? Thanks in advance.

tf config:
```
variable "db_server_sku_name" {
  type        = string
  default     = "B_Standard_B1ms"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-postgresql-test01"
  location = "eastus"
}

resource "azurerm_postgresql_flexible_server" "test" {
  name                   = "acctest-postgresqlfs-test01"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  administrator_login    = "adminTerraform"
  administrator_password = "CFDwsx123"
  backup_retention_days  = 7
  storage_mb             = 131072
  sku_name               = var.db_server_sku_name
  version                = "13"
  zone                   = "1"
}

resource "azurerm_postgresql_flexible_server_database" "test" {
  name      = "acctest-postgresqlfsdb-test01"
  server_id = azurerm_postgresql_flexible_server.test.id
  collation = "en_US.UTF8"
  charset   = "UTF8"
}
```

**Comment by aaronswainonset** [comment]
@neil-yechenwei 

Thanks for your reply, your TF worked as expected.

So I went back through my modules and eventually found the problem - another TF script had its own db SKU variable with a default value, and this was eventually passed up to the PostgreSQL module; hence, the module was ignoring the default value I was updating.
