### ISSUE TITLE
New-Feature-Request SQL Threat Detection Policy

### ISSUE THREAD

**Issue by whytoe** [hashicorp/terraform-provider-azurerm#1484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enable the SQL Threat Detection feature when deploying SQL Servers in Platform as a Service

### New or Affected Resource(s)

* azurerm_sql_server

### Potential Terraform Configuration

sql_threat_detection : "true"

### References

The Azure API documentation
https://docs.microsoft.com/en-us/rest/api/sql/databasethreatdetectionpolicies/createorupdate

Go SDK does not appear to support it ( i couldnt find it)

* #0000

**Comment by tombuildsstuff** [comment]
hey @whytoe 

Thanks for opening this issue :)

Taking a quick look at this / some notes for whoever picks this up: this appears to be available in the Go SDK here: https://github.com/Azure/azure-sdk-for-go/blob/v17.4.0/services/sql/mgmt/2014-04-01/sql/databasethreatdetectionpolicies.go#L52 - and this would probably make sense nested under the `azurerm_sql_server` resource rather than as an independent resource.

Thanks!

**Comment by Lucretius** [comment]
@tombuildsstuff just going through the issue backlog, looks like this one got resolved a while back and can be closed.

**Comment by andreas-schilling** [comment]
It's available on DB-Level, but not on server-level (which is recommended by Microsoft)

**Comment by SirWayne** [comment]
Is there a time plan for this feature?

**Comment by techjacker** [comment]
Is there any plan to add this for Azure storage?

The go SDK doesn't seem to support it currently.

**Comment by tombuildsstuff** [comment]
@techjacker I may be wrong, but that appears to be a separate (unrelated) service to the one in this issue? If so, would you mind opening a separate feature request for that? Thanks!

**Comment by techjacker** [comment]
@tombuildsstuff Sure I'll do this and add the link back to this thread when I'm done.

**Comment by techjacker** [comment]
> @tombuildsstuff Sure I'll do this and add the link back to this thread when I'm done.

Created feature request here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/3670

**Comment by jonhoare** [comment]
Is there any plans for this to be added?
