### ISSUE TITLE
Support for Credentials in Azure Data Factory (and Synapse Workspace)

### ISSUE THREAD

**Issue by si-te** [hashicorp/terraform-provider-azurerm#14856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Data Factory allows to configure credentials such as (user-) managed identities and service principals to be used in linked services. These credentials are required in order to enable linked services with user managed identities. It should be possible to manage these via terraform. This is a prerequisite for #14761.

This would likely also affect Synapse Workspace.

### New or Affected Resource(s)

* azurerm_data_factory_credential (would be a new resource type)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.microsoft.com/en-us/azure/data-factory/credentials?tabs=data-factory

**Comment by ms-henglu** [comment]
Hi @si-te , I took a look at it, does this property solve the problem?
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory#identity

**Comment by si-te** [comment]
Hi @ms-henglu thanks for the reply. I can setup a user managed identity with the above property (which is also a requirement for customer managed keys for the data factory encryption). But i cannot use this identity to add linked services such as storage accounts to data factory via terraform because as per my understanding that requires the credentials feature which are currently not supported in terraform.

**Comment by ms-henglu** [comment]
@si-te , I just checked the [data factory restapi spec](https://github.com/Azure/azure-rest-api-specs/tree/master/specification/datafactory/resource-manager/Microsoft.DataFactory/stable/2018-06-01), credential resource can't be managed by restapi. 

And I checked with synapse team as well, currently synapse resource can't be managed by restapi either.

Because azurerm provider is based on restapi,  we can't support this future now.

**Comment by si-te** [comment]
Thanks for checking!

**Comment by ms-henglu** [comment]
Hi @k8ekat , 

Thank you for taking time to check this, I think this resource may help with it: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_custom_service

This is a generic data factory linked service resource. Would you please have a try with it?

**Comment by Nayels** [comment]
Running in to the same problem. 

@ms-henglu The proposed linked custom service won't help. As it creates a linked service and not a credential. Tried multiple ways but couldn't get it to work.

I'd like to have a go at adding this functionality. But I'm hesitant as @ms-henglu indicates that rest api is not supported; but @k8ekat points to the rest api which does allow it.

**Comment by tommydejong** [comment]
Hi @Nayels @si-te did you make any progress or find any workaround for this issue? I'm looking for a way to deploy these credential objects so I can use them in my linked services. Or did you have to resort to `local-exec` type stuff?

**Comment by tomasvanpottelbergh** [comment]
Credentials have been added to the REST API recently (https://github.com/Azure/azure-rest-api-specs/commit/a7ae2063f33b983fee7f54a6ad0412b18842ce45). Could you therefore remove the "upstream" label @ms-henglu to indicate this can now be implemented?

**Comment by solita-burri** [comment]
This would also enable other linked service resources like `data_factory_linked_service_azure_sql_database` or `azurerm_data_factory_linked_service_azure_databricks` to use user-assigned managed identities which currently are restricted only to system-assigned managed identities.

**Comment by istairbn** [comment]
@tombuildsstuff - this is still tagged as "upstream/Microsoft" - but that's no longer the case (see thread). 
Can we please get this correctly tagged so it can be correctly triaged?

**Comment by lordy101** [comment]
@mybayern1974 @ms-henglu  - as above this is still tagged as "upstream/Microsoft" when this is not the case as per @tomasvanpottelbergh . Could this please be removed

**Comment by ms-henglu** [comment]
Hi all, sorry for late update. This feature is in my todo list, a roughly estimated timeline will be end of September .

**Comment by mustufa03021998** [comment]
hello! is there an updated roadmap for this?

**Comment by m33km** [comment]
> Hi all, sorry for late update. This feature is in my todo list, a roughly estimated timeline will be end of September .

@ms-henglu  any chance for an update on this?

**Comment by ms-henglu** [comment]
Hi @m33km , there's a bug in the swagger definition, I'm asking the service team to fix it.

**Comment by tommydejong** [comment]
> Interested in this one too, have others found a workaround for now? Credentials and user assigned mids need this functionality to be useful.

Hi @jonasthehobbit, I found a workaround using the azapi provider that works fine for now. Code snippet below.

```hcl
resource "azapi_resource" "adf-uami-cred-deloy" {
  type      = "Microsoft.DataFactory/factories/credentials@2018-06-01"
  name      = "${var.uami_principal_name}-cred-deploy"
  parent_id = azurerm_data_factory.adf.id
  body = jsonencode({
    properties = {
      description = "Shared UAMI for ${var.env} environment"
      type        = "ManagedIdentity"
      typeProperties = {
        resourceId = "${var.uami_principal_res_id}"
      }
    }
  })
}
```
