### ISSUE TITLE
Support for alias definitions in service endpoint policies 

### ISSUE THREAD

**Issue by m4r74** [hashicorp/terraform-provider-azurerm#14852]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for aliases on service endpoint policies to allow whitelisting of resources required for certain P/SaaS offerings.  
Currently the `azurerm_subnet_service_endpoint_storage_policy` supports only a list of resources. 

### New or Affected Resource(s)

* azurerm_subnet_service_endpoint_storage_policy

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azurerm_subnet_service_endpoint_storage_policy" "example" {
  name                = "example-policy"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  definition {
    name        = "name1"
    description = "definition1"
    service_resources = [
      azurerm_resource_group.example.id,
      azurerm_storage_account.example.id
    ]
    service_aliases = [
      "/services/Azure",
      "/services/Azure/Batch",
      "/services/Azure/DataFactory",
      "/services/Azure/MachineLearning",
      "/services/Azure/ManagedInstance",
      "/services/Azure/WebPI"
    ]
  }
}

```

### References

* https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/service-endpoint-policies-configure
* https://github.com/jhirono/azureml-dlp

**Comment by m4r74** [comment]
If the service alias is created outside of TF state, TF is aware of it as it become one of the resource definitions, it does not differentiate it as an alias and it is not ignored.

```
- definition {
   - name = "aml_Global" -> null
   - service_resources = [
     - "/services/Azure/MachineLearning",
   ] -> null
 }
```

When attempting to add it to the `service_resources` list as that's what it reports would be removed on next run, it fails due to a check that is ran against the resource IDs. 

`Error: Can not parse "definition.0.service_resources.0" as a resource id: The number of path segments is not divisible by 2 in "services/Azue/MachineLearning"`

`Error: Can not parse "definition.0.service_resources.0" as a management group id: Unable to parse Management Group ID "/services/Azure/MachieLearning/"`

(tried with a trailing slash too)

Therefore it would appear that `service_aliases` attribute is not needed, but a change to the validation of `service_resources` field does to allow for other values than resource IDs.

**Comment by marrobi** [comment]
Hit the exact same issue today when trying to configure Azure ML data exfiltration prevention as per https://learn.microsoft.com/en-us/azure/machine-learning/how-to-prevent-data-loss-exfiltration

**Comment by bubbletroubles** [comment]
I'll look to add support for Aliases in the provider - I'll have a PR for review shortly.
