### ISSUE TITLE
Cannot import existing `azurerm_aadb2c_directory`

### ISSUE THREAD

**Issue by tesharp** [hashicorp/terraform-provider-azurerm#14855]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
Terraform v1.1.2
on windows_amd64
+ provider registry.terraform.io/aztfmod/azurecaf v1.2.10
+ provider registry.terraform.io/cloudflare/cloudflare v3.4.0
+ provider registry.terraform.io/hashicorp/azuread v2.14.0
+ provider registry.terraform.io/hashicorp/azurerm v2.91.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.17.0
```

### Affected Resource(s)

* `azurerm_aadb2c_directory`

### Terraform Configuration Files

```hcl
resource "azurerm_aadb2c_directory" "this" {
  country_code            = "NO"
  data_residency_location = "Europe"
  display_name            = var.tenant_name
  domain_name             = "${var.tenant_name}.onmicrosoft.com"
  resource_group_name     = azurerm_resource_group.this.name
  sku_name                = "PremiumP1"
}
```

### Expected Behaviour

Created an B2C directory in portal 2 months ago since there was no resource for it at that time. Expected to be able to import that now since there is a resource, without it needing to recreate the resource. However, since `display_name` and `country_code` are not set when creating in portal, and they are required and force recreation it is not possible to import it without it recreating the B2C directory.

### Actual Behaviour

Forces recreation after import. Cannot recreate entire B2C directory. Looking at rest api and json in portal it doesn't seem like those properties are part of the resource either? So if they are only used during creation how to import this resource

### Steps to Reproduce

1. `terraform import azurerm_aadb2c_directory.this /sub....`
2. `terraform plan`

### References

* https://docs.microsoft.com/en-us/rest/api/activedirectory/b2c-tenants/create

**Comment by neil-yechenwei** [comment]
@tesharp , thanks for raising this issue. So you mean you can successfully import this resource by command  `terraform import azurerm_aadb2c_directory.test /subscriptions/xxxx/resourceGroups/xxxxx/providers/Microsoft.AzureActiveDirectory/b2cDirectories/xxxx`, right? But terraform shows difference after `tf plan`, right?

**Comment by tesharp** [comment]
Yes. Maybe completely accurate title.. it imports successfully, but will always show a difference. It does not seem to be possible to import and not make terraform recreate it. (unless I edit state file and set those properties manually maybe...)

**Comment by tombuildsstuff** [comment]
@tesharp so that we can take a look into this - can you show the plan/diff being proposed here?

**Comment by tesharp** [comment]
Sure:

```terraform
  # azurerm_aadb2c_directory.this must be replaced
-/+ resource "azurerm_aadb2c_directory" "this" {
      ~ billing_type            = "MAU" -> (known after apply)
      + country_code            = "NO" # forces replacement
      + display_name            = "b2ctenant" # forces replacement
      ~ effective_start_date    = "1/1/0001 12:00:00 AM" -> (known after apply)
      ~ id                      = "/subscriptions/***********/resourceGroups/rg-b2c-tenant/providers/Microsoft.AzureActiveDirectory/b2cDirectories/b2ctenant.onmicrosoft.com" -> (known after apply)
      - tags                    = {} -> null
      ~ tenant_id               = "*************" -> (known after apply)
        # (4 unchanged attributes hidden)

      - timeouts {}
    }
```

**Comment by tombuildsstuff** [comment]
Looks like these two fields aren't returned from the API after the initial creation unfortunately ([so we read them from the state, where they'll be nil for an imported resource](https://github.com/hashicorp/terraform-provider-azurerm/blob/4dd6699ec63ec21e31a7d516f3777f0c0aaa2123/internal/services/aadb2c/aadb2c_directory_resource.go#L262-L263)) - so we'll need a custom importer to account for that - @manicminer would you mind taking a look into that since you've got the most context on this one?
