### ISSUE TITLE
Error: failed to read schema for azurerm_resource_group.my_demo_rg1 in registry.terraform.io/hashicorp/azurerm

### ISSUE THREAD

**Issue by nawaahme** [hashicorp/terraform-provider-azurerm#14861]
Error: failed to read schema for azurerm_resource_group.my_demo_rg1 in registry.terraform.io/hashicorp/azurerm: failed to retrieve schema from provider "registry.terraform.io/hashicorp/azurerm": Plugin did not respond: The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).GetProviderSchema call. The plugin logs may contain more details.
│

$ terraform -v
Terraform v1.1.3
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0

**Comment by mybayern1974** [comment]
@nawaahme Thank you for opening this issue. By assuming Terraform AzureRM provider has been working, this issue apparently looks more like user side environment settings / configs. Could you provide your terraform config files as well as repro steps which could help troubleshooting?

**Comment by tombuildsstuff** [comment]
Closing this out since we haven't heard back here, if this is still an issue in the latest version of the Provider please let us know and we'll take another look.

Thanks!
