### ISSUE TITLE
ZoneRedundant storage_mode_type not available in azurerm_recovery_services_vault

### ISSUE THREAD

**Issue by mjnewborn** [hashicorp/terraform-provider-azurerm#14860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 1.1.3
azurerm v2.91.0

### Affected Resource(s)

* `azurerm_recovery_services_vault`

### Terraform Configuration Files

```hcl

resource "azurerm_recovery_services_vault" "vault" {

    name                                  = "testvault"
    location                              = "uksouth"
    resource_group_name       = "rg-rsv-vault
    sku                                     = "standard"
    storage_mode_type           = "ZoneRedundant"
}
```

### Expected Behaviour

The Recovery Services Vault is created with Zone-Redundant Storage replication type

### Actual Behaviour

Error: expected storage_mode_type to be one of [GeoRedundant LocallyRedundant], got ZoneRedundant
│ 
│   with azurerm_recovery_services_vault.vault,
│   on generic-vm-alerts.tf line 20, in resource "azurerm_recovery_services_vault" "vault":
│   20:     storage_mode_type   = "ZoneRedundant"
│ 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The updated documents state:  Possible values are GeoRedundant and LocallyRedundant. Defaults to GeoRedundant.

In the portal you can also select ZoneRedundant.

We have some Recovery Services Vaults using Zone-Redundant Storage replication type so are getting failed deployments now

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/recovery_services_vault

* #0000

**Comment by krelf75** [comment]
As I noted here [https://github.com/hashicorp/terraform-provider-azurerm/issues/8709](url), the Azure portal notes that, while you can change the RSV storage account type, it can't be changed after items are protected.  So if a vault previously created via Terraform was set to ZRS and protecting items, this would represent a breaking change

**Comment by sinbai** [comment]
@mjnewborn the [v2.95.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.95.0/CHANGELOG.md) already supports the `ZoneRedundant` of storage_mode_type, thanks for opening this issue.

**Comment by sinbai** [comment]
@mjnewborn would you mind we close this issue as the `ZoneRedundant ` has been supported?

**Comment by mybayern1974** [comment]
Per sinbai's suggest I'm closing this issue with regarding it as having been resolved. Feel free to suggest to reactivate this issue if people believe there is still feature missing.
