### ISSUE TITLE
Support for action overriding routing configuration in azurerm_frontdoor_rules_engine

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform-provider-azurerm#14884]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource azurerm_frontdoor_rules_engine supports both action "Response header" and "Request header" but not "Routing configuration".
In the ARM Template the block called "routeConfigurationOverride" contains forwarding or redirecting rules. 

### New or Affected Resource(s)

* azurerm_frontdoor_rules_engine

### Potential Terraform Configuration

```hcl
resource "azurerm_frontdoor_rules_engine" "example_rules_engine" {
  name                = "exampleRulesEngineConfig1"
  frontdoor_name      = azurerm_frontdoor.example.name
  resource_group_name = azurerm_frontdoor.example.resource_group_name

  rule {
    name     = "overwriteorigin"
    priority = 2

    match_condition {
      negate_condition = true
      operator         = "Contains"
      selector         = "Authorization"
      value            = ["myhub001"]
      variable         = "RequestHeader"
    }

    action {
      routing_rule_override {
        redirect_configuration {
          custom_host       = "www.bing.com"
          redirect_protocol = "MatchRequest"
          redirect_type     = "PermanentRedirect"
        }
      }
    }
  }
}
```

**Comment by cvallesi-kainos** [comment]
So, apparently the pull request have not gone through and the branch has been deleted just three days ago.
https://github.com/hashicorp/terraform-provider-azurerm/pull/14951

I'm running into this issue just today in which I need to replicate a production environment that has this rule and there is no way of doing that via terraform config.

Any suggestion? Have I misread the chain of events here?

**Comment by WodansSon** [comment]
The legacy Frontdoor resources are being retired and are no longer in development.
