### ISSUE TITLE
Dynamic policy_definition_reference block fails creation in new azurerm_policy_set_definition resource

### ISSUE THREAD

**Issue by jchancellor-ms** [hashicorp/terraform-provider-azurerm#14881]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform - v1.0.9
Azurerm - v2.90.0
### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
locals {
  policies = {
    "policy1" = "testpolicy1",
    "policy2" = "testpolicy2"
  }
}

resource "azurerm_policy_set_definition" "this" {
  name         = var.initiative_name
  policy_type  = var.initiative_policy_type
  display_name = var.initiative_display_name

  dynamic "policy_definition_reference" {
    for_each = local.policies
    content {
      parameter_values = <<VALUE
        {
            "tagName" : "sampleTag"
        }
      VALUE
      policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/b27a0cbd-a167-4dfa-ae64-4337be671140"
    }
  }
}
```

### Expected Behaviour

I'm trying to create a policy initiative with multiple policies that I create dynamically using input variables.  For testing the code, I've simplified this to static values in the dynamic block and am still getting an error that json cannot unmarshal a string into an object type. It isn't clear to me whether the issue is a bug in the azurerm provider code or if there is a specific format required for the parameter values JSON that I'm not properly following.

### Actual Behaviour

When running terraform apply, the following error occurs:
Error: expanding `policy_definition_reference`: unmarshalling `parameter_values`: json: cannot unmarshal string into Go value of type policy.ParameterValuesValue

### Steps to Reproduce

Provide initiative variable values - (can be just about anything)
1. `terraform apply`

### Important Factoids

Azure Government, Creating an initiative from some basic built-in tag policies.  Trying to keep everything simple prior to creating a more complex initiative and it is failing.
### References

* #0000

**Comment by jchancellor-ms** [comment]
In the factoids I erroneously said Government and meant commercial.

**Comment by sinbai** [comment]
Hi @jchancellor-ms thank you for opening this issue.

Could you please replace the `"tagName" : "sampleTag" `with  `"tagName" : {"value": "sampleTag"} `and try again?

**Comment by jchancellor-ms** [comment]
Elena,

That corrected the issue.  I wasn't aware that the policy JSON had the extra value element.

Thanks for the clarification, and we may close this issue.

Thanks,
Jon

**Comment by mybayern1974** [comment]
Close this issue with getting confirmation from the issue opener.
