### ISSUE TITLE
azurerm_log_analytics_solution keeps adding tags that are already present on the resource

### ISSUE THREAD

**Issue by mvalenzisi** [hashicorp/terraform-provider-azurerm#14903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.91.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

* `azurerm_log_analytics_solution`

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "logAnalyticsWorkspace" {
  name = "${local.cluster-short-name}-${random_id.log_analytics_workspace_name_suffix.dec}"
  location = var.azure-region
  resource_group_name = var.environment
  sku = "PerGB2018"

  tags = {
    akelius_environment = var.environment
    akelius_team = var.team-code
    akelius_project = var.project-code
    akelius_cluster = var.cluster-name
  }
}

```

### Expected Behaviour

Since the tags on the resource are already present, I expect `terraform apply` to not notify any changes in the tags.

### Actual Behaviour

`terraform apply` notifies about the following changes:
```
  # azurerm_log_analytics_solution.logAnalyticsSolution will be updated in-place
  ~ resource "azurerm_log_analytics_solution" "logAnalyticsSolution" {
        id                    = "[REDACTED]"
      ~ tags                  = {
          ~ "akelius_cluster"     = "" -> "devops.azure.akelius.com"
          + "akelius_environment" = "devops"
          + "akelius_project"     = "k8s"
          + "akelius_team"        = "ops"
        }
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/8751

* #0000

### EDIT:

Full configuration files: 
[config.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/7852712/config.zip)

Full steps to reproduce:
1. Create the resources with `terraform apply`
2. Run `terraform apply` again without changing the tags of the resource `azurerm_log_analytics_solution`

**Comment by sinbai** [comment]
@mvalenzisi thank you for opening this issue. Could you please provide your full terraform config and repro steps that could help repro and troubleshooting?

**Comment by mvalenzisi** [comment]
@sinbai issue updated, thank you!

**Comment by sinbai** [comment]
@mvalenzisi  thank you for the details. Unfortunately, I still can not repro this problem. Per the information  `~ "akelius_cluster"     = "" -> "devops.azure.akelius.com"`, I think that the tag value of "akelius_cluster" shoud be "" before running terraform apply for the second time. Could you double check the actual tag value of "akelius_cluster" on Azure Portal before running terraform apply for the second time? 

Below is my repros:

1. Run `terraform apply` with the following tf config:
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
     version = "2.91.0"
    }
  }

   backend "azurerm" {
    storage_account_name = "elenaccount"
    container_name       = "elelablobcontainer"
    key                  = "prod.terraform.tfstate1"

    sas_token = "xxxxxx"
  }
}

provider "azurerm" {
  features {}
}


resource "azurerm_log_analytics_workspace" "logAnalyticsWorkspace" {
  name = "testworkspace01"
  location = "eastus"
  resource_group_name = "elenatest"
  sku = "PerGB2018"

  tags = {
    akelius_environment = "test environment"
    akelius_team = "team"
    akelius_project = "project"
    akelius_cluster = "cluster"
  }
}

resource "azurerm_log_analytics_solution" "logAnalyticsSolution" {
  solution_name = "ContainerInsights"
  location = azurerm_log_analytics_workspace.logAnalyticsWorkspace.location
  resource_group_name = "elenatest"
  workspace_resource_id = azurerm_log_analytics_workspace.logAnalyticsWorkspace.id
  workspace_name = azurerm_log_analytics_workspace.logAnalyticsWorkspace.name

  plan {
    publisher = "Microsoft"
    product = "OMSGallery/ContainerInsights"
  }

  tags = {
    akelius_environment = "test environment"
    akelius_team = "team"
    akelius_project = "project"
    akelius_cluster = "cluster"
  }
}

```
2. Do not modify anything run `terraform apply` again => Everything goes smoothly.

If you are also unable to repro this issue with the steps above, I think step-by-step-repro-this-issue is the key to investigate this issue. Appreciate it if if you could provide it.

In addition, it would be helpful if below info can be provided:

- Does this issue only repro when using remote state (use backend "azurerm") rather than local state?

- Does this issue stable repro or happen intermittently?

- Do you use TF to manage all things rather than using any other client tools (portal, CLI, etc) to co-manage resources?

**Comment by mvalenzisi** [comment]
I am able to reproduce the issue always.
In the Azure portal I see all the tags correctly:
![Screenshot from 2022-01-20 10-18-31](https://user-images.githubusercontent.com/36044907/150309679-0100bd53-88a3-44a5-9087-132985952c2a.png)
then I run `terraform plan` and I see the changes:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_log_analytics_solution.logAnalyticsSolution will be updated in-place
  ~ resource "azurerm_log_analytics_solution" "logAnalyticsSolution" {
        id                    = "/subscriptions/b71f870a-6d7f-4fe9-b2aa-92bce2ad8a9e/resourceGroups/devops/providers/Microsoft.OperationsManagement/solutions/ContainerInsights(devops-azure-2396477646771175592)"
      ~ tags                  = {
          ~ "akelius_cluster"     = "" -> "devops.azure.akelius.com"
          + "akelius_environment" = "devops"
          + "akelius_project"     = "k8s"
          + "akelius_team"        = "ops"
        }
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
and this happens also if I use a local tfstate, I changes my configuration like this:
```
terraform {
  required_version = "= 1.0.3"

#  backend "azurerm" {}
  backend "local" {
    path = "devops-azure-akelius-com.tfstate"
  }

  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=2.91.0"
    }
  }
}
```
And yes, I only use terraform to manage the resources.

**Comment by sinbai** [comment]
> I am able to reproduce the issue always. In the Azure portal I see all the tags correctly: ![Screenshot from 2022-01-20 10-18-31](https://user-images.githubusercontent.com/36044907/150309679-0100bd53-88a3-44a5-9087-132985952c2a.png) then I run `terraform plan` and I see the changes:
> 
> ```
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   ~ update in-place
> 
> Terraform will perform the following actions:
> 
>   # azurerm_log_analytics_solution.logAnalyticsSolution will be updated in-place
>   ~ resource "azurerm_log_analytics_solution" "logAnalyticsSolution" {
>         id                    = "/subscriptions/b71f870a-6d7f-4fe9-b2aa-92bce2ad8a9e/resourceGroups/devops/providers/Microsoft.OperationsManagement/solutions/ContainerInsights(devops-azure-2396477646771175592)"
>       ~ tags                  = {
>           ~ "akelius_cluster"     = "" -> "devops.azure.akelius.com"
>           + "akelius_environment" = "devops"
>           + "akelius_project"     = "k8s"
>           + "akelius_team"        = "ops"
>         }
>         # (5 unchanged attributes hidden)
> 
>         # (1 unchanged block hidden)
>     }
> 
> Plan: 0 to add, 1 to change, 0 to destroy.
> ```
> 
> and this happens also if I use a local tfstate, I changes my configuration like this:
> 
> ```
> terraform {
>   required_version = "= 1.0.3"
> 
> #  backend "azurerm" {}
>   backend "local" {
>     path = "devops-azure-akelius-com.tfstate"
>   }
> 
>   required_providers {
>     azurerm = {
>       source = "hashicorp/azurerm"
>       version = "=2.91.0"
>     }
>   }
> }
> ```
> 
> And yes, I only use terraform to manage the resources.

@mvalenzisi since the above screenshot is azurerm_log_analytics_workspace resource and the output of `terraform plan ` is azurerm_log_analytics_solution resource. Could you double check that the `akelius_cluster` of azurerm_log_analytics_solution resource is empty?

**Comment by mvalenzisi** [comment]
@sinbai you are perfectly right, my mistake. Apologies for that.
The tags are missing in the azurerm_log_analytics_solution, but after a bit of research, I found out that the problem is related to some background policies.

The provider works fine.

**Comment by mybayern1974** [comment]
Closing for the issue author believed this issue is addressed.
