### ISSUE TITLE
Support for identity block in resource azurerm_iotcentral_application

### ISSUE THREAD

**Issue by alfredo222** [hashicorp/terraform-provider-azurerm#14914]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently **azurerm_iotcentral_application** resource does not include the **identity block argument**. There is no way to specify SystemAssigned, for instance, through Terraform deployment.

It would also be great to have the **Data Source** for the resource, in order to retrive the id associated with the Managed Service Identity.

### New or Affected Resource(s)

* azurerm_iotcentral_application

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resource"
  location = "West Europe"
}

resource "azurerm_iotcentral_application" "example" {
  name                = "example-iotcentral-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sub_domain          = "example-iotcentral-app-subdomain"

  display_name = "example-iotcentral-app-display-name"
  sku          = "S1"
  template     = "iotc-default@1.0.0"
  
  identity = {
    type = "SystemAssigned"
  }

  tags = {
    Foo = "Bar"
  }
}
```

### References

* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iotcentral_application

**Comment by myc2h6o** [comment]
Hi @alfredo222 thanks for opening the issue! This is supported v3.25.0 by #18564

**Comment by mybayern1974** [comment]
Closing this issue per myc2h6o's suggestion.
