### ISSUE TITLE
Importing a Storage Account ignores the allow_blob_public_access property and fallback to a wrong default value

### ISSUE THREAD

**Issue by jcoqueret** [hashicorp/terraform-provider-azurerm#14925]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
terraform: v1.1.0
provider: v2.90.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Expected Behaviour

When we import a storage account resource into the state using terraform import command, the `allow_blob_public_access` should be set to the value configured on Azure portal.

### Actual Behaviour

`allow_blob_public_access` is always set to `false`. Moreover, `false` is not the default value when creating a new storage account on the portal.

### Steps to Reproduce

1. `terraform import` azurerm_storage_account.myaccount /subscriptions/......
2. `terraform state show` azurerm_storage_account.myaccount

### References
* https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal
* #13037

**Comment by magodo** [comment]
@jcoqueret `terraform import` imports whatever state of the resource as it is, into terraform state (as you are seeing via `terraform state show`). From the description above, it appears that the actual value of the `allow_blob_public_access` of the storage account under discussion is `false`, would you please verify? If you want to make it to be `true`, please explicitly set the `allow_blob_public_access = true` in the config, and run `terraform apply`.

**Comment by jcoqueret** [comment]
I am not able to reproduce the problem when I start from scratch with a new Storage Account.
I guess my previous imports have been done with a `allow_blob_public_access = false` in the Azure configuration and that setting was changed on Azure after the import. That would explain the difference between the terraform state and Azure.

Cause I can not reproduce and I think it was my mistake, this issue can be closed.
Thank you for your help.
