### ISSUE TITLE
Support for On-demand Capacity Reservation

### ISSUE THREAD

**Issue by horvatal** [hashicorp/terraform-provider-azurerm#14923]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new enterprise feature (On-demand Capacity Reservation) in preview which is relevant for disaster recovery (DR) cases in regions and availability zones. When a zonal outage occurs everybody wants to use resources in the remaining zones. To be able to guarantee resources in such a case, capacity reservations have to be defined.

### New or Affected Resource(s)

* azurerm_capacity_reservation_group (new)
* azurerm_capacity_reservation (new)
* azurerm_windows_virtual_machine
* azurerm_linux_virtual_machine

### References

* https://docs.microsoft.com/en-us/azure/virtual-machines/capacity-reservation-overview

**Comment by aristosvo** [comment]
Has a dependency on #14828, as it requires the latest `compute` API version

**Comment by horvatal** [comment]
The new compute SDK version has been merged and released with https://github.com/hashicorp/terraform-provider-azurerm/pull/14828. Is this feature now ready for implementation?

**Comment by jemag** [comment]
I believe the "sdk/requires-upgrade" label might not be relevant anymore (given the merged PR)

**Comment by jemag** [comment]
In regards to affected resources, might be good to also include "kubernetes_cluster_node_pool", given that it can now be associated to a Capacity Reservation Group, see https://docs.microsoft.com/en-us/azure/aks/use-multiple-node-pools#associate-capacity-reservation-groups-to-node-pools-preview

**Comment by horvatal** [comment]
This Azure feature is now GA: https://azure.microsoft.com/en-us/updates/general-availability-ondemand-capacity-reservations/ You might carry on implementation.

**Comment by horvatal** [comment]
The feature has been implemented in following PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/16464

**Comment by horvatal** [comment]
The feature has been implemented in following PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/16464
