### ISSUE TITLE
Terraform diff on linked hub location for azurerm_iothub_dps

### ISSUE THREAD

**Issue by BzSpi** [hashicorp/terraform-provider-azurerm#14938]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.6 on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.91.0

### Affected Resource(s)

* `azurerm_iothub_dps`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "iothub" {
  name                = "myiothub"
  resource_group_name = var.resource_group_name
  location            = "West Europe"

  sku {
    name     = "S1"
    capacity = 1
  }
}

resource "azurerm_iothub_shared_access_policy" "dps_policy" {
  name                = "iothubdps"
  resource_group_name = var.resource_group_name

  iothub_name = azurerm_iothub.iothub.name

  registry_read  = true
  registry_write = true
  service_connect = true
  device_connect = true
}

resource "azurerm_iothub_dps" "iothub_dps" {
  name                = "myiothubdps"
  resource_group_name = var.resource_group_name
  location            = "West Europe"

  sku {
    name     = "S1"
    capacity = 1
  }

  linked_hub {
    connection_string = azurerm_iothub_shared_access_policy.dps_policy.primary_connection_string
    location          = "West Europe"
  }
}

```

### Expected Behaviour

On second `terraform apply`, Terraform should not have any change to perform.

### Actual Behaviour

Currently, the linked hub location attribute has a change to be performed on each apply
```
  # azurerm_iothub_dps.iothub_dps will be updated in-place
  ~ resource "azurerm_iothub_dps" "iothub_dps" {
        id                            = "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Devices/provisioningServices/myiothubdps"
        name                          = "myiothubdps"
        tags                          = {}
        # (6 unchanged attributes hidden)

      ~ linked_hub {
          ~ location                = "West Europe" -> "westeurope"
            # (4 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by myc2h6o** [comment]
Hi @BzSpi There seems to be a missing Normalization of the locations, I've raised a change to fix it.
I tested the fix with the same configuration. After running `terraform apply` again, you should see the locations being updated to `westeurope` in the state file automatically.
