### ISSUE TITLE
azurerm_virtual_desktop_scaling_plan documentation use wrong block name in example

### ISSUE THREAD

**Issue by pedroivotavares** [hashicorp/terraform-provider-azurerm#14955]
In the documentation for azurerm_virtual_desktop_scaling_plan at https://registry.terraform.io/providers/hashicorp/azurerm/2.91.0/docs/resources/virtual_desktop_scaling_plan, the example code snippet uses a "hostpool_reference" block, but the expected syntax is "host_pool".

Instead of:

```
  host_pool{
    hostpool_id          = azurerm_virtual_desktop_host_pool.example.id
    scaling_plan_enabled = true
  }
```
It should be:

```
  host_pool {
    hostpool_id          = azurerm_virtual_desktop_host_pool.example.id
    scaling_plan_enabled = true
  }
```

**Comment by sinbai** [comment]
@pedroivotavares  thank you for raising this issue. The [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14960) has been submitted.

**Comment by catriona-m** [comment]
Looks like this has now been fixed by the linked PR so this can be closed. Thanks!
