### ISSUE TITLE
Support for gallery_image_reference_lun on managed_disk_resource

### ISSUE THREAD

**Issue by myc2h6o** [hashicorp/terraform-provider-azurerm#14959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`gallery_image_reference_id` has been added to `managed_disk` resource through #14121 without supporting `gallery_image_reference_lun`. From user feedback, it seems reasonable to support `lun` for a gallery image because it can potentially have data disks depending on the implementation.
Different from [virtual_machine_data_disk_attachment.lun](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_data_disk_attachment#lun) which specifies the lun to put on the target virtual machine, `gallery_image_reference_lun` means the lun from the gallery image, and it will be kept in the creationData of the disk and not affect the disk attachment when attaching it to a virtual machine.

### New or Affected Resource(s)

* azurerm_managed_disk

### Potential Terraform Configuration

Azure API accepts data disk lun starting from `0`. And when given nil, API creates from OS disk. This actually breaks the convention in Terraform where `0` is the default/empty value for int. I thought two possible options below.

```hcl
// Option 1
resource "azurerm_managed_disk" "test" {
  name                 = "test"
  location             = "eastus"
  resource_group_name  = "test"
  os_type              = "Linux"
  create_option        = "FromImage"
  storage_account_type = "Standard_LRS"

  // gallery_image_reference_lun defaults to -1
  gallery_image_reference_lun = 0
  gallery_image_reference_id  = azurerm_shared_image_version.test.id
}

// Option 2
resource "azurerm_managed_disk" "test" {
  name                 = "test"
  location             = "eastus"
  resource_group_name  = "test"
  os_type              = "Linux"
  create_option        = "FromImage"
  storage_account_type = "Standard_LRS"

  // gallery_image_reference_lun defaults to 0, use gallery_image_reference_from_data_disk to control whether to create from data disk or os disk
  gallery_image_reference_from_data_disk = true
  gallery_image_reference_lun            = 0
  gallery_image_reference_id             = azurerm_shared_image_version.test.id
}
```

### References

* [ImageDiskReference](https://docs.microsoft.com/en-us/rest/api/compute/disks/create-or-update#imagediskreference)

**Comment by myc2h6o** [comment]
@tombuildsstuff What do you think about the second option mentioned above? to use a separate bool property `gallery_image_reference_from_data_disk` to decide creating from an image data disk/os disk, so that we can keep the default value of `gallery_image_reference_lun` to `0` instead of `-1` in the previous pr.

**Comment by BzSpi** [comment]
May I suggest another option ?

```
// Option 3
resource "azurerm_managed_disk" "test" {
  name                 = "test"
  location             = "eastus"
  resource_group_name  = "test"
  os_type              = "Linux"
  create_option        = "FromImage"
  storage_account_type = "Standard_LRS"

  gallery_image_reference_data_disk_lun = 0
  gallery_image_reference_id  = azurerm_shared_image_version.test.id
}
```

By specifying explicitly that lun is only used for data disk, user may not be confused.

**Comment by tombuildsstuff** [comment]
@myc2h6o what's the use-case we're looking to solve here?

Creating a Data Disk from a Gallery Image on it's own isn't useful - it'd only be provisioned as a part of a Virtual Machine (or VM Scale Set) - where this is already available - so I'm not sure of the use-case we're trying to solve here?

**Comment by tombuildsstuff** [comment]
@BzSpi got it, thanks.

Support for that is being tracked in #6117 - so I'm going to close this in favour of that issue.
