### ISSUE TITLE
Quota limit results in state not being written (azurerm_kubernetes_cluster_node_pool)

### ISSUE THREAD

**Issue by asmithdt** [hashicorp/terraform-provider-azurerm#14969]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.92.0

### Affected Resource(s)

* azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "general_1" {
  for_each = toset(local.availability_zones)

  name                  = "az${each.key}g1"
  kubernetes_cluster_id = module.aks.aks_id
  vm_size               = "Standard_D8s_v4"

  availability_zones = [each.key]

  enable_auto_scaling = true
  max_count           = 6
  min_count           = 3
  node_count          = 3

  node_labels = {
    "role" = "general"
  }

  enable_host_encryption = true
}

```

### Expected Behaviour

When erroring based on Quota limits, created resources should be added to state if those creation was successful but the "wait for" instances failed.

### Actual Behaviour

Items were not added to state

```
Error: waiting for completion of Managed Kubernetes Cluster Node Pool "az2g1" (Resource Group "<redacted>"): Code="ReconcileVMSSAgentPoolFailed" Message="Code=\"OperationNotAllowed\" Message=\"Operation could not be completed as it results in e
xceeding approved standardDSv4Family Cores quota. Additional details - Deployment Model: Resource Manager, Location: northeurope, Current Limit: 30, Current Usage: 30, Additional Required: 24, (Minimum) New Limit Required: 54.
```

```
Error: A resource with the ID "/subscriptions/<redacted>/resourcegroups/<redacted>/providers/Microsoft.ContainerService/managedClusters/<redacted>/agentPools/az3g1" already exists - to be managed via Terraform
 this resource needs to be imported into the State. Please see the resource documentation for "azurerm_kubernetes_cluster_node_pool" for more information.
```

### Steps to Reproduce

Ensure Quota limit will be breached before applying Terraform apply.

**Comment by tombuildsstuff** [comment]
hi @asmithdt 

Thanks for opening this issue.

Taking a look through here it appears this will be fixed by more information being returned from the Azure API which is being tracked upstream on the AKS repository: https://github.com/Azure/AKS/issues/1972 - would you mind subscribing to this issue for updates?

Thanks!
