### ISSUE TITLE
Cannot destroy Azure Firewall

### ISSUE THREAD

**Issue by TamasSzerb** [hashicorp/terraform-provider-azurerm#14966]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.1
on linux_amd64

### Affected Resource(s)

* `azurerm_firewall`

### Terraform Configuration Files

```hcl
resource "azurerm_firewall" "azfw" {
  name = format("%s-%s-%s-%s", var.name_prefix, var.environment, var.location_[redacted]_name, "fw")
  location = var.location
  resource_group_name = var.resource_group_name
  tags = var.tags
  ip_configuration {
    name = "IpConf"
    subnet_id = azurerm_subnet.azfw-subnet.id
    public_ip_address_id = azurerm_public_ip.azfw-public-ip.id
  }
}
```
### Debug Output

- Reusing previous version of hashicorp/kubernetes from the dependency lock file
- Reusing previous version of hashicorp/helm from the dependency lock file
- Reusing previous version of hashicorp/null from the dependency lock file
- Reusing previous version of hashicorp/external from the dependency lock file
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Reusing previous version of hashicorp/tls from the dependency lock file
- Installing hashicorp/kubernetes v1.13.3...
- Installed hashicorp/kubernetes v1.13.3 (signed by HashiCorp)
- Installing hashicorp/helm v1.3.2...
- Installed hashicorp/helm v1.3.2 (signed by HashiCorp)
- Installing hashicorp/null v3.0.0...
- Installed hashicorp/null v3.0.0 (signed by HashiCorp)
- Installing hashicorp/external v2.0.0...
- Installed hashicorp/external v2.0.0 (signed by HashiCorp)
- Installing hashicorp/azurerm v2.92.0...
- Installed hashicorp/azurerm v2.92.0 (signed by HashiCorp)
- Installing hashicorp/tls v3.0.0...
- Installed hashicorp/tls v3.0.0 (signed by HashiCorp)
- Installing hashicorp/http v2.0.0...
- Installed hashicorp/http v2.0.0 (signed by HashiCorp)

Terraform has been successfully initialized!

Error: deleting Azure Firewall Firewall: (Azure Firewall Name "[redacted]" / Resource Group "[redacted]") : network.AzureFirewallsClient#Delete: Failure sending request: StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '' is not supported. Only 'application/json' is supported."

### Expected Behaviour

Azure Firewall resource should be successfully destroyed.

### Actual Behaviour

Terraform destroy failed.

### Steps to Reproduce

* `terraform destroy`

### References

* #14866

**Comment by tombuildsstuff** [comment]
hey @TamasSzerb 

Thanks for opening this issue - apologies for the confusion on our part here, looking into #14866 I read that as FrontDoor and not Firewall 🤦 

Taking a look into this one this appears to be a similar issue in the Azure SDK for Go where the Content-Type field isn't being sent during the deletion of this resource - https://github.com/Azure/azure-sdk-for-go/blob/ff3a653623e72d5d9a54bdb89cbd1b5646623974/services/network/mgmt/2021-05-01/network/azurefirewalls.go#L154-L173

Comparing [the current Swagger version that that's generated from](https://github.com/Azure/azure-rest-api-specs/blob/16a50699c70e8e86765dd46b84a9185067debfa7/specification/network/resource-manager/Microsoft.Network/stable/2021-05-01/azureFirewall.json#L12-L66) and [an older version](https://github.com/Azure/azure-rest-api-specs/blob/16a50699c70e8e86765dd46b84a9185067debfa7/specification/network/resource-manager/Microsoft.Network/stable/2020-07-01/azureFirewall.json#L12-L54) these appear comparable - so my guess is this is actually a breaking change to the API behaviour that's rolling out, where the Content-Type was previously implied, but now isn't.

@jhendrixMSFT @jeffreyRichter heads up I think there's a breaking API change here which'll affects other SDK clients - although it's strange this isn't outputting a Json Content Type in the Go SDK here too, since the Swagger looks fine?

Thanks!

**Comment by jhendrixMSFT** [comment]
Sorry for the delay.

The SDK doesn't set a content type as there is no body being sent as part of the request.  Did this used to work in the past?

**Comment by Xophmeister** [comment]
I can replicate this in `azurerm` 2.86.0, 2.92.0 and 2.94.0. MWE:

```terraform
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.92.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "location" {
  type    = string
  default = "westeurope"
}

variable "address_space" {
  type    = string
  default = "10.1.0.0/24"
}

resource "azurerm_resource_group" "this" {
  name     = "TEST-RG"
  location = var.location
}

resource "azurerm_virtual_network" "this" {
  name                = "TEST-NETWORK"
  resource_group_name = azurerm_resource_group.this.name
  location            = var.location
  address_space       = [var.address_space]
}

resource "azurerm_subnet" "fw" {
  name                 = "AzureFirewallSubnet"
  resource_group_name  = azurerm_resource_group.this.name
  virtual_network_name = azurerm_virtual_network.this.name
  address_prefixes     = [var.address_space]
}

resource "azurerm_public_ip" "fw" {
  name                = "TEST-IP"
  location            = var.location
  resource_group_name = azurerm_resource_group.this.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_firewall" "this" {
  name                = "TEST-FIREWALL"
  resource_group_name = azurerm_resource_group.this.name
  location            = var.location

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.fw.id
    public_ip_address_id = azurerm_public_ip.fw.id
  }
}
```

**Comment by ole-bkk** [comment]
I`m still seeing this error as well.  
azurerm: 2.94.0. 
Terraform: 1.1.4. 

```
│ Error: deleting Azure Firewall Firewall: (Azure Firewall Name "REDACTED" / Resource Group "REDACTED") : network.AzureFirewallsClient#Delete: Failure sending request: StatusCode=415 -- Original Error: Code="UnsupportedMediaType" Message="The content media type '<null>' is not supported. Only 'application/json' is supported."
```

**Comment by earthquakesan** [comment]
The firewall client is using [azure go sdk 2021-05-01](https://github.com/hashicorp/terraform-provider-azurerm/blob/dfdb9a43092b507a011d301a02c92379b11f74b3/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-05-01/network/azurefirewalls.go#L167-L172). There is a DeletePreparer function, which configures request using autorest, but does not include `autorest.AsContentType("application/json; charset=utf-8")` line as in [this PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14927/commits/02d8425c7d81c0e49c90e55e33f739f201317031).

What's weird for me: in the same azurefirewalls.go, the [content type is set for request when creating Azure Firewall](https://github.com/hashicorp/terraform-provider-azurerm/blob/dfdb9a43092b507a011d301a02c92379b11f74b3/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-05-01/network/azurefirewalls.go#L86-L93).

For me it looks like the azure-go-sdk library needs a fix - it is a one-line fix, not sure about release process here - and how to bump versions in this terraform provider afterwards.

**Comment by jhendrixMSFT** [comment]
Can anybody comment if this used to work though?  We've never added the Content-Type header in the past for APIs that don't send a body in the request.  If the service team changed the behavior here it would be great to know so I can follow up on that too.

**Comment by earthquakesan** [comment]
@jhendrixMSFT I was developing/deploying Firewall using terraform in January this year and did not have this problem. I can not say exactly when it happened, but it looks like a recent problem (i.e. last week~).

**Comment by rowco** [comment]
Likewise, I've been adding/removing Azure firewalls with Terraform without incident over the last few months. Not tried in the last week or so though.

**Comment by athiththan11** [comment]
@jhendrixMSFT I have been deploying and destroying Azure Firewall resources using Terraform (with `azurerm`: 2.79) since December 2021, and I was able to destroy and deploy the resources successfully without any issue until mid of January. For the last two weeks, I was not able to destroy the Azure Firewall resources due to the mentioned error (and have also tried bumping the `azurerm` to 2.92 as well)

**Comment by geekzter** [comment]
Same here, it worked ever since the resource `azurerm_firewall` existed, until recently/

**Comment by j-chao** [comment]
I can also confirm that this was recent, and I opened #14866 when I had first encountered this.

**Comment by byteknacker** [comment]
I also have the same issue and got stuck here. Is there any update on this? Is that more of a problem that Microsoft or Go has to fix or something to do with azurerm?

**Comment by awterra** [comment]
> Can anybody comment if this used to work though? We've never added the Content-Type header in the past for APIs that don't send a body in the request. If the service team changed the behavior here it would be great to know so I can follow up on that too.

@jhendrixMSFT We developed a module middle of last year that includes a firewall. The module updates the Azurerm Version automatically every week and runs tests. This issue just appeared this week when the test pipeline failed but we had the issue in another module 2 weeks ago. I'm trying to locate right now what resource caused it.

**Comment by arnaudlh** [comment]
Same on our end for CAF TF module we can more and more consisently repro in regions: https://github.com/aztfmod/terraform-azurerm-caf/runs/5051813780?check_suite_focus=true

**Comment by danailedms** [comment]
Bump... just experienced this consistently in terraform 1.1.5.

**Comment by llgjermeni** [comment]
Same problem here. Does anyone solved the issue?

**Comment by earthquakesan** [comment]
As a workaround you can invoke [`az network firewall delete`](https://docs.microsoft.com/en-us/cli/azure/network/firewall?view=azure-cli-latest#az-network-firewall-delete) with AZ cli before `terraform destroy`. Not the best solution, but it worked in our case.

**Comment by ramsateesh** [comment]
This is happening to us as well, our terraform modules were working just fine and this started to happen very recently.

**Comment by magodo** [comment]
@jhendrixMSFT As @earthquakesan has indicated that the `az network firewall delete` works, I inspected the request and noticed that it contains the `Accept: application/json` header (while no `Content-Type` header), though the response actually still has no payload.

**Comment by tombuildsstuff** [comment]
@magodo whilst this is being fixed within the Azure SDK/API's, would you mind updating the Delete call to manually set this header for the moment? We've done this in a few other places by lifting the Azure SDK method into an `azuresdkhacks` package and customizing it as necessary fwiw e.g.: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/securitycenter/azuresdkhacks/security_center_contact.go
