### ISSUE TITLE
Support for Chaos Studio

### ISSUE THREAD

**Issue by BenH-Puregym** [hashicorp/terraform-provider-azurerm#14965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please support Azure Chaos Studio
https://azure.microsoft.com/en-us/services/chaos-studio/

**Comment by aristosvo** [comment]
Hi @BenH-Puregym! I'd like to help you out here, at the moment there is no SDK available.

I asked for it based on the REST API specs, as soon as it is available I'll give it a try!

**Comment by aristosvo** [comment]
I gave it a try, but am blocked for now on the specification which seems incomplete

**Comment by sebader** [comment]
any chance there are news on this?

**Comment by tombuildsstuff** [comment]
FWIW there's been several breaking changes to the Chaos Studio swagger specs recently, including the addition/removal of fields and changing of data types, so we may need to wait for that to settle down/get input from the Service Team to be able to determine if this is ready to use yet

**Comment by tombuildsstuff** [comment]
The SDK for the updated API version can be found here: https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/chaosstudio/2022-07-01-preview

**Comment by jbpaux** [comment]
Any news on that support ? :)

**Comment by 4865783a5d** [comment]
Azure Chaos Studio is now GA.

https://azure.microsoft.com/en-us/updates/azure-chaos-studio-is-now-generally-available/
