### ISSUE TITLE
Support for Azure log search alert V2

### ISSUE THREAD

**Issue by LQQ677** [hashicorp/terraform-provider-azurerm#14999]
Hi, 

I have a question relate to azure log alert V2.
https://docs.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-common-schema-definitions#monitoringservice--log-alerts-v2
https://cloudadministrator.net/2021/11/04/azure-monitor-log-alert-v2/

**Any plan to release a module for azure alert v2?** the module we found in the following doc
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert is for v1.

Thanks for any help in advance.

**Comment by AdimUser** [comment]
we are blocked with creating alert due to this issue. Please give your kind help/fix
      source  = "hashicorp/azurerm"
      version = "2.93.1"
