### ISSUE TITLE
Unable to update resource group that has `managedBy` set to something besides `null`

### ISSUE THREAD

**Issue by matthewaerose** [hashicorp/terraform-provider-azurerm#15015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v2.80.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.7.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tfe v0.24.0
```
### Affected Resource(s)

* `azurerm_resource_group`

### Terraform Configuration Files

```hcl
locals {
  groups = yamldecode(file("resource-groups.yml"))
}

resource "azurerm_resource_group" "this" {
  for_each = local.groups
  name     = each.key
  location = each.value.location
  tags = merge({
    "terraform" = "true",
    },
    each.value.tags
  )
}
```

```yaml
AzureBackupRG_eastus_1:
  location: eastus
  tags:

```

### Expected Behaviour
* terraform updates resource with the tag `terraform = true`

### Actual Behaviour
* terraform errors with
```
Error: creating Resource Group "AzureBackupRG_eastus_1": resources.GroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ResourceGroupManagedByMismatch" Message="The managed by property of the resource group cannot be changed from its current value 'subscriptions/<SUBSCRIPTION>/providers/Microsoft.RecoveryServices/'."
```

### Steps to Reproduce

1. import old azure state
2. add changes that would update specific resource group
3. `terraform plan -out=plan.tfplan`
2. `terraform apply plan.tfplan`

### Important Factoids

here is the `az group list` output for the specific resource.

```json
{
  "id": "/subscriptions/<SUBSCRIPTION>/resourceGroups/AzureBackupRG_eastus_1",
  "location": "eastus",
  "managedBy": "subscriptions/<SUBSCRIPTION>/providers/Microsoft.RecoveryServices/",
  "name": "AzureBackupRG_eastus_1",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": {
    "terraform": "false"
  },
  "type": "Microsoft.Resources/resourceGroups"
}
```
### References

* #0000

**Comment by matthewaerose** [comment]
I'd imagine this stems from `azurerm_resource_group` not having a "managedBy" attribute. But it seems to set the attribute to `null` nonetheless.
Are there plans to add a "managedBy" attribute?

**Comment by neil-yechenwei** [comment]
@matthewaerose , thanks for raising this issue. I think you shouldn't import this managed resource group to Terraform because it's automatically managed by application resource like "subscriptions/<SUBSCRIPTION>/providers/Microsoft.RecoveryServices/". If my understanding is correct, actually you intend to import the resource group where the resource "subscriptions/<SUBSCRIPTION>/providers/Microsoft.RecoveryServices/" exists, right? If yes, I think this managed resource group is not what you want. You have to retrieve the data of the application resource via Azure Portal/GET API to find out where is the resource group and then import it to Terraform.
