### ISSUE TITLE
azurerm_dev_test_lab.testing-lab.key_vault_id causes replacement on every run due to capitalization 

### ISSUE THREAD

**Issue by jwshive** [hashicorp/terraform-provider-azurerm#15013]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_access_policy`
* `azurerm_dev_test_lab`

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_access_policy" "shive-kv-access" {
  key_vault_id       = azurerm_dev_test_lab.testing-lab.key_vault_id
  object_id          = "<my_object_id>"
  tenant_id          = data.azurerm_client_config.current_client_config.tenant_id
  key_permissions    = ["Get", "List", "Create", "Delete"]
  secret_permissions = ["Get", "List", "Set", "Delete", "Purge"]
  depends_on         = [azurerm_dev_test_lab.testing-lab]
}
```

### Expected Behaviour

I expect future runs of the above code to produce no changes unless the resource block has been changed.

### Actual Behaviour

When the above block is run, azurerm_dev_test_lab.testing-lab.key_vault_id gets set as 
`/subscriptions/my_subscription/resourceGroups/gl-devtstdemo-dev-v1-rg/providers/Microsoft.KeyVault/vaults/gldevtstdemodevtstla963`

The expected and official syntax coming out of azure is
`/subscriptions/my_subscription/resourcegroups/gl-devtstdemo-dev-v1-rg/providers/microsoft.keyvault/vaults/gldevtstdemodevtstla963`

The only difference is the uppercase G in resourceGroups. If I hardcode the actual id with the uppercase G, the block does not try to recreate itself.

This is the actual replacement that terraform wants to do every time.
```hcl
  # azurerm_key_vault_access_policy.shive-kv-access must be replaced
-/+ resource "azurerm_key_vault_access_policy" "shive-kv-access" {
      - certificate_permissions = [] -> null
      ...
      ~ key_vault_id            = "/subscriptions/my_subscription/resourceGroups/gl-devtstdemo-dev-v1-rg/providers/Microsoft.KeyVault/vaults/gldevtstdemodevtstla963" -> "/subscriptions/my_subscription/resourcegroups/gl-devtstdemo-dev-v1-rg/providers/microsoft.keyvault/vaults/gldevtstdemodevtstla963" # forces replacement
      ...
    }
```

### Steps to Reproduce

Run above code using a dev test labs key vault id

1. `terraform apply`

### References

* #0000

**Comment by sinbai** [comment]
@jwshive thank you for reporting this issue. This is an azure API issue. I have submitted a PR as a workaround in Azurerm provider. You could use the 'ignore_changes' property in terraform to avoid the resource to be re-created until the PR is approved, like this: 
```
 resource "azurerm_key_vault_access_policy" "shive-kv-access" {
 lifecycle {
    ignore_changes = [
        key_vault_id,
	]
  }
  key_vault_id       = azurerm_dev_test_lab.testing-lab.key_vault_id
  object_id          = "<my_object_id>"
  tenant_id          = data.azurerm_client_config.current_client_config.tenant_id
  key_permissions    = ["Get", "List", "Create", "Delete"]
  secret_permissions = ["Get", "List", "Set", "Delete", "Purge"]
  depends_on         = [azurerm_dev_test_lab.testing-lab]
}
```
