### ISSUE TITLE
Unable to update azurerm_resource_group_cost_management_export resource

### ISSUE THREAD

**Issue by jamesbwilkinson** [hashicorp/terraform-provider-azurerm#15010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When updating an azurerm_subscription_cost_management_export the update fails as an etag reference is missing.  Reference documents for the API suggest this is [required](https://docs.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update).

### Affected Resource(s)

* `azurerm_subscription_cost_management_export`

### Terraform Configuration Files

resource "azurerm_subscription_cost_management_export" "example" {
  name                         = "example-name"
  subscription_id              = data.azurerm_subscription.current.id
  recurrence_type              = "Weekly"
  recurrence_period_start_date = timestamp()
  recurrence_period_end_date   = "2025-12-31T00:00:00Z"

  export_data_storage_location {
    container_id     = azurerm_storage_container.export.resource_manager_id
    root_folder_path = "/"
  }

  export_data_options {
    type       = "Usage"
    time_frame = "MonthToDate"
  }
}

### Expected Behaviour

The resource is updated.

### Actual Behaviour

Update fails with error message:
Service returned an error. Status=400 Code="400" Message="Etag value required for update operation of report: XXX .Please get the latest to avoid overwrite.

### Steps to Reproduce

Create a cost management export and trigger an update.

* #0000

**Comment by sinbai** [comment]
@jamesbwilkinson thanks for reporting this issue. I have submitted a PR to fix it.

**Comment by jamesbwilkinson** [comment]
@sinbai, thank you

**Comment by stephybun** [comment]
Closed by #15017
