### ISSUE TITLE
Support for partition key on event hub stream analytics input.

### ISSUE THREAD

**Issue by darren-clark** [hashicorp/terraform-provider-azurerm#15018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Stream analytics jobs allow for indicating what the partition key of an input is, allowing the job to know what is already partitioned and accomplish it's task more efficiently. This is currently unsupported by the terraform provider.

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
resource "azurerm_stream_analytics_stream_input_eventhub" "example" {
  name                         = "eventhub-stream-input"
  stream_analytics_job_name    = data.azurerm_stream_analytics_job.example.name
  resource_group_name          = data.azurerm_stream_analytics_job.example.resource_group_name
  eventhub_consumer_group_name = azurerm_eventhub_consumer_group.example.name
  eventhub_name                = azurerm_eventhub.example.name
  servicebus_namespace         = azurerm_eventhub_namespace.example.name
  shared_access_policy_key     = azurerm_eventhub_namespace.example.default_primary_key
  shared_access_policy_name    = "RootManageSharedAccessKey"
  partition_key = "partitionKey"
  serialization {
    type     = "Json"
    encoding = "UTF8"
  }
}
```

### References

* #0000

**Comment by stephybun** [comment]
Closed by #15019
