### ISSUE TITLE
azurerm_mysql_flexible_server database resource inconsistently does not remove serviceAssociationLinks from delegated subnet

### ISSUE THREAD

**Issue by jamie-sweeney** [hashicorp/terraform-provider-azurerm#15032]
Hello All!

If required I can provide/mock up an example in tf but it is somewhat easy to reproduce, and occurs nearly always when also adding a 'replica' resource, and sometimes without. TF does seem to create and destroy in the correct order and changing the parallelism to 1 [ a test to see if replica and mainDB were racing or removing in tandem ? ] had no effect.

**How to Reproduce:**
create as below and run 
`terraform apply`
then
`terraform destroy`

result: 
Error:
`Failed to delete resource group flextest: Deletion of resource group 'flextest' did not finish within the allowed time as resources with identifiers 'Microsoft.Network/virtualNetworks/flextest-network' could not be deleted. The provisioning state of the resource group will be rolled back. The tracking Id is '<generated-id>'. Please check audit logs for more details. (Code: ResourceGroupDeletionTimeout) Subnet flex-app-db is in use by /subscriptions/<az-subscription>7/resourceGroups/flextest/providers/Microsoft.Network/virtualNetworks/flextest-network/subnets/flex-app-db/serviceAssociationLinks/flex-app-db-service-association-link and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet. (Code: InUseSubnetCannotBeDeleted, Target: /subscriptions/<az-subscription>7/resourceGroups/flextest/providers/Microsoft.Network/virtualNetworks/flextest-network)`

To resolve the issue I must create a Flex server via az portal or az cli, with the same vnet/subnet/name which reassociates it with the subnet, and then delete the flex server, which then results in the subnet having a null link:

`"serviceAssociationLinks": null,
`
at which time I can then terraform destroy or  delete the subnet in the portal or cli.

I had not experienced this issue as of yet with the CLI, and have written a bash cli script to 'auto-create-and-delete' the flex server and rerun destroy to work around this so we can validate a shift to flex server from single-server, so I think its provider specific.

Additional finding:  I did put a "delete" lock on the vnet in testing at one point and got an error on delete in those cases which was:
`Message="The virtual network named 'flextest-network' has a lock on it. Please release the lock so that we can remove the service association link that we have created, otherwise this may prevent you from deleting the virtual network in the future."`
which validated [ with a few tests ] that it always attempted and reached out to remove the SA, but somehow it is left behind. This issue is not related to locks on vnets or RG. providing only to support that the resource always 'attempts' to remove.

There are similar issues noted online with AppServices and LoadBalancers as well, though not specific to TF providers afaik.

Let me know if I can test or if I am missing a step/process. 

Cheers

General TF module example
----

Create a subnet [ in an existing vnet ]

```
resource "azurerm_subnet" "this" {
  name                 = "${var.name}-db"
  resource_group_name  = var.vnet_rg
  virtual_network_name = data.azurerm_virtual_network.this.name
  address_prefixes     = [var.address_prefixes]
  service_endpoints    = ["Microsoft.Storage"]
  delegation {
    name = "${var.name}-sndel"
    service_delegation {
      name = "Microsoft.DBforMySQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
```

Create a private zone 
```
resource "azurerm_private_dns_zone" "this" {
  name                = "${var.name}.mysql.database.azure.com"
  resource_group_name = azurerm_resource_group.this.name
}
```

Link zone with Vnet
```
resource "azurerm_private_dns_zone_virtual_network_link" "this" {
  name                  = var.name
  resource_group_name   = azurerm_resource_group.this.name
  private_dns_zone_name = azurerm_private_dns_zone.this.name
  virtual_network_id    = data.azurerm_virtual_network.this.id
}
```

Create a Flex Server
```
resource "azurerm_mysql_flexible_server" "this" {
  name                         = "${var.name}-db"
  location                     = azurerm_resource_group.this.location
  resource_group_name          = azurerm_resource_group.this.name
  backup_retention_days        = var.backup_retention_days
  geo_redundant_backup_enabled = var.geo_redundant_backup_enabled
  sku_name                     = var.sku_name
  version                      = var.db_version
  administrator_login          = var.admin_db_user
  administrator_password       = var.admin_db_pass
  storage {
    auto_grow_enabled = var.auto_grow_enabled
    size_gb           = var.size_gb
  }
  delegated_subnet_id = azurerm_subnet.this.id
  private_dns_zone_id = azurerm_private_dns_zone.this.id
  depends_on = [azurerm_private_dns_zone_virtual_network_link.this]
}
```
Create a Replica 
```
resource "azurerm_mysql_flexible_server" "replica" {
  name                = "${var.name}-rdb"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  create_mode         = "Replica"
  source_server_id    = azurerm_mysql_flexible_server.this.id
  sku_name            = var.sku_name
  version             = var.db_version
  storage {
    auto_grow_enabled = var.auto_grow_enabled
    size_gb           = var.size_gb
  }
  backup_retention_days        = var.backup_retention_days
  geo_redundant_backup_enabled = var.geo_redundant_backup_enabled
  delegated_subnet_id          = azurerm_subnet.this.id
  private_dns_zone_id          = azurerm_private_dns_zone.this.id
  depends_on = [azurerm_mysql_flexible_server.this]
}
```

**Comment by neil-yechenwei** [comment]
@jamie-sweeney , thanks for raising this issue. As the service association link is created by Service API at backend, so I assume there is some API problem while deleting. So I filed an issue on Azure/azure-rest-api-specs/issues/17443 for tracking.
