### ISSUE TITLE
Support for Recovery Vault Backups of SQL in Azure VM

### ISSUE THREAD

**Issue by andyr8939** [hashicorp/terraform-provider-azurerm#15031]
Terraform allows you to add a Azure VM or Azure File Share to be protected by a Recovery Service Vault wit the **azurerm_backup_protected_vm** and **azurerm_backup_protected_file_share** resources, however there is no way to also backup SQL in an Azure VM.

[https://docs.microsoft.com/en-us/azure/backup/tutorial-sql-backup](url)

Could this be added as a feature please?

**Comment by joshfria** [comment]
We really need this functionality as well.

**Comment by Flappje** [comment]
I think this is the same request as: #3910

**Comment by ArjunMR89** [comment]
I am trying to backup SQL in Azure VM and used the policy **azurerm_backup_policy_vm_workload** with azurerm provider version **3.23.0**. The policy is successfully deployed in Azure but I couldn't find any resource to backup SQL in Azure VM. I tried using **azurerm_backup_protected_vm** by passing virtualMachines ID and SqlVirtualMachines ID but both resulted in errors. Am I missing something? Is only backup policy available at the moment? Is the backup of SQL in Azure VM still not supported using Terraform?
![Vm_ID_Error](https://user-images.githubusercontent.com/75679143/190996037-90a222f9-76dc-4632-9c53-094f6a3396c9.png)
![SqlVm_ID_Error](https://user-images.githubusercontent.com/75679143/190996063-2d1e6d3b-d546-4ea2-8094-3e1f013335a8.png)

**Comment by mpjtaylor** [comment]
Any updated on this, we have the policy but no way of configuring protection.

**Comment by khaman-pet** [comment]
Need update on this. 

This is what we expect:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/118238939/e148e505-313d-49ca-b044-09846aa95367)

**Comment by jbeeden-lumen** [comment]
...any updates?

**Comment by valentinahermann** [comment]
we need this feature as well!

**Comment by rio-hashicorp** [comment]
Hello, we have an important customer which is asking on this. Do we know the status/upadates for this?

**Comment by andyr8939** [comment]
As far as I know, this can now be done with the [azurerm_backup_policy_vm_workload](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_policy_vm_workload) Resource Type, however I haven't tried it as I no longer have a need to do this.

**Comment by andyr8939** [comment]
As far as I know, this can now be done with the [azurerm_backup_policy_vm_workload](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_policy_vm_workload) Resource Type, however I haven't tried it as I no longer have a need to do this.

**Comment by katbyte** [comment]
I am going to close this in favour of #3910
