### ISSUE TITLE
azurerm_mssql_database_vulnerability_assessment_rule_baseline unexpectedly replaced

### ISSUE THREAD

**Issue by dhmoto17** [hashicorp/terraform-provider-azurerm#15047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v0.14.11
+ provider registry.terraform.io/hashicorp/azuread v2.14.0
+ provider registry.terraform.io/hashicorp/azurerm v2.89.0 (also tried v2.90.0, v2.91.0 with same unexpected results)
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.7.2

### Affected Resource(s)

* `azurerm_mssql_database_vulnerability_assessment_rule_baseline`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database_vulnerability_assessment_rule_baseline" "db_baseline_va1258" {
  for_each = try(data.terraform_remote_state.sql.outputs.services_databases, {})

  server_vulnerability_assessment_id = azurerm_mssql_server_vulnerability_assessment.default.id
  database_name                      = data.terraform_remote_state.sql.outputs.services_databases[each.key].resource_suffix == "SSISDB" ? data.terraform_remote_state.sql.outputs.services_databases[each.key].resource_suffix : format("%s_%s", data.terraform_remote_state.config.outputs.naming.storage_prefix, data.terraform_remote_state.sql.outputs.services_databases[each.key].resource_suffix)
  rule_id                            = "VA1258"
  #  baseline_name                      = "master"
  baseline_result {
    result = [
      format("%s_user", data.terraform_remote_state.sql.outputs.services_databases[each.key].resource_suffix)
    ]
  }
}

```

### Debug Output

```shell
  # azurerm_mssql_database_vulnerability_assessment_rule_baseline.db_baseline_va1258["function_apps_oneillpatient"] must be replaced
-/+ resource "azurerm_mssql_database_vulnerability_assessment_rule_baseline" "db_baseline_va1258" {
      ~ id                                 = "/subscriptions/12345678-dc49-4afe-8839-abcdefghijkl/resourceGroups/sql-rg/providers/Microsoft.Sql/servers/sql-server-name/databases/sql-database-name/vulnerabilityAssessments/Default/rules/VA1258/baselines/default" -> (known after apply)
      ~ server_vulnerability_assessment_id = "/subscriptions/12345678-dc49-4afe-8839-abcdefghijkl/resourceGroups/sql-rg/providers/Microsoft.Sql/servers/sql-server-name/vulnerabilityAssessments/default" -> "/subscriptions/12345678-dc49-4afe-8839-abcdefghijkl/resourceGroups/sql-rg/providers/Microsoft.Sql/servers/sql-server-name/vulnerabilityAssessments/Default" # forces replacement
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```
### Expected Behaviour

no changes expected

### Actual Behaviour

Terraform plan indicated a force replacement as the case of Default <> default in the resource ID

### Steps to Reproduce

Plan and apply an azurerm_mssql_database_vulnerability_assessment_rule_baseline resource after and including AzureRM v2.89 onwards

1. `terraform apply`

### References

* #0000

edit: added markdown for readability

**Comment by AurimasNav** [comment]
same as #14695, it already has a PR #14759

**Comment by dhmoto17** [comment]
Thanks, that related issue didn't come up in search results when I searched originally.

**Comment by mybayern1974** [comment]
@dhmoto17 , would you mind if we close this issue and you can subscribe [#14695](https://github.com/hashicorp/terraform-provider-azurerm/issues/14695)?

**Comment by dhmoto17** [comment]
Sure, yes, you can close this, I'm tracking the other.  Thank you.
