### ISSUE TITLE
azurerm v2.93.0 is crashing for unknown reasons in existing setup

### ISSUE THREAD

**Issue by pranavkevadiya** [hashicorp/terraform-provider-azurerm#15058]
The newly released version v2.93.0 on 21st January 2022 is crashing with native errors without any apparent reasons, with an existing working setup.

Stack trace from the terraform-provider-azurerm_v2.93.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45a1c7d]
`goroutine 234 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceBastionHostRead(0xc00019f680, {0x559a880, 0xc001ae3180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/network/bastion_host_resource.go:255 +0x5dd
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x5e760e3, {0x657f318, 0xc0012533c0}, 0x24, {0x559a880, 0xc001ae3180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000669420, {0x657f318, 0xc0012533c0}, 0xc001bdf450, {0x559a880, 0xc001ae3180})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x35b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0011d05d0, {0x657f318, 0xc0012533c0}, 0xc001253440)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x534
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000293180, {0x657f3c0, 0xc0023791a0}, 0xc0020247e0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3b0
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x5adac20, 0xc000293180}, {0x657f3c0, 0xc0023791a0}, 0xc002024780, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000140fc0, {0x65cdac8, 0xc0000f2d80}, 0xc001bc07e0, 0xc0012d7620, 0xab3d910, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc000140fc0, {0x65cdac8, 0xc0000f2d80}, 0xc001bc07e0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294`

**Comment by tombuildsstuff** [comment]
@neil-yechenwei can you take a look into this, since this was introduced in https://github.com/hashicorp/terraform-provider-azurerm/pull/14987? Thanks.

**Comment by chriswhite72** [comment]
I have the same issue with the new plugin.  Hopefully the following stack trace will help.


Stack trace from the terraform-provider-azurerm_v2.93.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x105ffa484]

goroutine 7218 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/network.resourceBastionHostRead(0x14001c38180, {0x1076a3b60, 0x140002a0e00})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/network/bastion_host_resource.go:255 +0x574
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x14000c05420, {0x108068038, 0x140031a97c0}, 0x14001c38180, {0x1076a3b60, 0x140002a0e00})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:346 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x14000c05420, {0x108068038, 0x140031a97c0}, 0x140023f5ba0, {0x1076a3b60, 0x140002a0e00})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:635 +0x388
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x14000788ed0, {0x108068038, 0x140031a97c0}, 0x140031a9840)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:576 +0x5f4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x140000b5400, {0x1080680e0, 0x14002ec8d50}, 0x14001858de0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:553 +0x3ac
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x107bdf700, 0x140000b5400}, {0x1080680e0, 0x14002ec8d50}, 0x14001858d20, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140001ff340, {0x1080cb528, 0x140002fe000}, 0x140033ce360, 0x140014e16b0, 0x10c54c8d0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc04
google.golang.org/grpc.(*Server).handleStream(0x140001ff340, {0x1080cb528, 0x140002fe000}, 0x140033ce360, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa34
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x14000942520, 0x140001ff340, {0x1080cb528, 0x140002fe000}, 0x140033ce360)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1f0

Error: The terraform-provider-azurerm_v2.93.0_x5 plugin crashed!

**Comment by tikicoder** [comment]
2.93.0 also crashes on me. so I guess I will wait till 2.94
