### ISSUE TITLE
for_each is not supported on data.azurerm_key_vault_secrets.secrets.names is list of string

### ISSUE THREAD

**Issue by hsalluri259** [hashicorp/terraform-provider-azurerm#15052]
The example shown here (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secrets) has a for_each on the data source. I used it for one of my use cases, but it throws the below error. 

data "azurerm_key_vault" "cpe_akv" {
  name                = "cpe"
  resource_group_name = "cpe-secrets"
}

data "azurerm_key_vault_secrets" "secrets" {
  key_vault_id = data.azurerm_key_vault.cpe_akv.id
}
data "azurerm_key_vault_secret" "cpe_akv" {
  name         = each.key
  key_vault_id = data.azurerm_key_vault.cpe_akv.id
  for_each = data.azurerm_key_vault_secrets.secrets.names
}

on app-service/app-service.tf line 34, in data "azurerm_key_vault_secret" "cpe_akv":
│   34:   for_each = data.azurerm_key_vault_secrets.secrets.names
│     ├────────────────
│     │ data.azurerm_key_vault_secrets.secrets.names is list of string with 79 elements
│
│ The given "for_each" argument value is unsuitable: the "for_each" argument must be a map, or set of strings, and you have provided a value of type list of string.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by fwiedmann** [comment]
Hey Hey,

why do you want to create two data instances of `azurerm_key_vault_secret` of the same keyvault?
If you plan to use the secret names in your resource definitions you can use the `for_each` function there. Checkout this example: https://www.terraform.io/language/meta-arguments/for_each#chaining-for_each-between-resources

Or you could use `locals` variables to create your own custom `object`/`list`/`map` combination.

https://www.terraform.io/language/values/locals

**Comment by jackofallops** [comment]
Hi @hsalluri259 - Thanks for this issue, looks like the example needs to be update to use [toset](https://www.terraform.io/language/functions/toset) on the output.
