### ISSUE TITLE
azurerm 2.93.0 throws error while deploying new app services

### ISSUE THREAD

**Issue by theepansubramani** [hashicorp/terraform-provider-azurerm#15064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.3 (I have also tried with v1.1.4 as well)
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.93.0

### Affected Resource(s)

azurerm_app_service

### Terraform Configuration Files

I am creating a very basic app service mapped to a service plan. 
```
resource "azurerm_app_service_plan" "sample_plan" {
  name                = "sample_plan"
  location            = var.location
  resource_group_name = var.resource_group_name

  sku {
    tier = var.pi_asp_sku_tier
    size = var.pi_asp_sku_size
  }
}

resource "azurerm_app_service" "sample_app_service" {
  name                = "sample_app_service"
  location            = var.location
  resource_group_name = var.resource_group_name
  app_service_plan_id = azurerm_app_service_plan.sample_plan.id

}
```

### Debug Output

Your version of Terraform is out of date! The latest version
is 1.1.4. You can update by downloading from https://www.terraform.io/downloads.html
/usr/local/bin/terraform apply -auto-approve $(TerraformPlanFile)
module.azure-app-primary.azurerm_app_service_plan.sample_plan: Creating...
module.azure-app-primary.azurerm_app_service_plan.sample_plan: Creation complete after 5s [id=/subscriptions/2f0e9fda-d7cb-476d-b953-7e39206f2a9d/resourceGroups/Sandbox/providers/Microsoft.Web/serverfarms/sample_plan]
module.azure-app-primary.azurerm_app_service.sample_app_service: Creating...
╷
│ Error: The name "sample_app_service" used for the App Service needs to be globally unique and isn't available: Site names only allow alphanumeric characters and hyphens, cannot start or end in a hyphen, and must be less than 64 chars.
│ 
│   with module.azure-app-primary.azurerm_app_service.sample_app_service,
│   on AppService/webapp.tf line 12, in resource "azurerm_app_service" "sample_app_service":
│   12: resource "azurerm_app_service" "sample_app_service" {
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: The name "sample_app_service" used for the App Service needs to be globally unique and isn't available: Site names only allow alphanumeric characters and hyphens, cannot start or end in a hyphen, and must be less than 64 chars.
│ 
│   with module.azure-app-primary.azurerm_app_service.pi_orchard_app_service,
│   on AppService/webapp.tf line 12, in resource "azurerm_app_service" "sample_app_service":
│   12: resource "azurerm_app_service" "sample_app_service" {

### Expected Behaviour

App service should have been created as expected

### Actual Behaviour

App service creation gets failed in the pipeline

### Steps to Reproduce

1. Create a tf script to create an app service
2. Deploy it using the above versions of TF & azurerm provider

**Comment by marcindulak** [comment]
The PR aiming at fixing the problem already exists https://github.com/hashicorp/terraform-provider-azurerm/pull/15062
