### ISSUE TITLE
azurerm_key_vault data source authentication error using a Service Principal in provider

### ISSUE THREAD

**Issue by MostefaKamalLala** [hashicorp/terraform-provider-azurerm#15113]
### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
provider registry.terraform.io/hashicorp/azurerm v2.93.1
terraform version 1.1.4
```
### Affected Resource(s)

* `azurerm_key_vault`
* `azurerm_key_vault_secret`

### Terraform Configuration Files

```
terraform {
  cloud {
    organization = "some-org"
    workspaces {
      tags = ["some-app"]
    }
  }

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.93.1"
    }
  }
}

provider "azurerm" {
  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id

  features {}
}

data "azurerm_key_vault" "key-vault" {
  name                = "keyvault-name"
  resource_group_name = "keyvault-rg"
}

data "azurerm_key_vault_secret" "secret-test" {
  name         = "secret-test"
  key_vault_id = data.azurerm_key_vault.key-vault.id
}

output "secret_value" {
  value = "${data.azurerm_key_vault_secret.secret-test.value}"
}

```

### Debug Output

```
│ Error: making read request Vault: (Name "keyvault-name" / Resource Group "keyvault-rg"): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '**<AZURE-SUBSCRIPTION-ID>**' with object id '**<AZURE-SUBSCRIPTION-ID>**'' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/**<AZURE-SUBSCRIPTION-ID>**'/resourceGroups/cactusoft-constuction/providers/Microsoft.KeyVault/vaults/keyvault-name' or the scope is invalid. If access was recently granted, please refresh your credentials."
│
│   with data.azurerm_key_vault.key-vault,
│   on main.tf line 88, in data "azurerm_key_vault" "key-vault":
│   88: data "azurerm_key_vault" "key-vault" {
```

### Expected Behaviour

The azurerm_key_vault data source should be using the Service Principal credential defined in the provider configuration.

### Actual Behaviour

The error shows that the azurerm_key_vault data source is using the SubscriptionId as ClientId and ObjectId!

### Steps to Reproduce

1. Create a KeyVault and assign the read permissions on it using the Service Principal used to authenticate in azurerm provider.
2. Create a secret and try to output it using the terraform configuration above.
3.  `terraform plan`

### Important Factoids

The Service Principal works since I am already managing a couple of Azure Resources using the same terraform configuration.
The Service Principal has been granted read access to the concerned Azure Key Vault resource.
The error shows the Azure Subscription id as Client Id and Object Id which is suspicious.

I tried using a second provider (same Service Principal) but with an alias and referenced it with the alias  in the azurerm_key_vault provider argument but it didn't work.

### References
no related issues found.

**Comment by tombuildsstuff** [comment]
hi @MostefaKamalLala 

Thanks for opening this issue.

Taking a look into this, this appears to be an authentication issue with the values provided - I'd suggest checking the value of the `subscription_id` and `client_id` fields and confirming those match as expected.

As your using the Terraform Backend, note that these variables may be being sourced from Terraform Cloud too - as such I'd recommend checking the variables used there as the values can be defined both locally (within the Terraform Configuration/variables files) and within Terraform Cloud.

Since this is an issue with the values being provided rather than a bug in the Azure Provider, I'm going to close this issue for the moment, but otherwise as your making use of Terraform Cloud you should be able to reach out to Terraform Cloud support for further assistance.

Thanks!

**Comment by MostefaKamalLala** [comment]
Hi @tombuildsstuff 

Thank for your quick answer. 

As I said, the terraform configuration works properly with any other azure resource. However just to make sure I'm not forgetting anything, I created a simple terraform configuration with the code provided above without the Cloud block.

I also hardcoded the credentials for the service principal in the azurerm provider block to make sure it is not an issue with the values provided.  I even created another client secret to test with it. And I still get the same error.

Here is the configuration I used: 

```
terraform {
   required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.93.1"
    }
  }
}

provider "azurerm" {
  subscription_id = "***************************************"
  client_id       = "***************************************"
  client_secret   = "***************************************"
  tenant_id       = "***************************************"

  features {}
}

data "azurerm_key_vault" "key-vault" {
  name                = "keyvault-name"
  resource_group_name = "keyvault-rg"
}

data "azurerm_key_vault_secret" "secret-test" {
  name         = "secret-test"
  key_vault_id = data.azurerm_key_vault.key-vault.id
}

output "secret_value" {
  value = "${data.azurerm_key_vault_secret.secret-test.value}"
}
```

**Comment by MostefaKamalLala** [comment]
I don't know if it is my understanding of the data source that is wrong but  I got it working by replacing ```data "azurerm_key_vault"```  by the resource. I don't create the secrets with terraform and don't change the key vault resource itself.  By doing so the authentication error disappeared.
