### ISSUE TITLE
azurerm_static_site error with message: "SkuCode 'SKU' is invalid" for Free option. For Standard works OK.

### ISSUE THREAD

**Issue by azieh** [hashicorp/terraform-provider-azurerm#15125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4 on windows_amd64

### Affected Resource(s)

* `azurerm_static_site`

### Terraform Configuration Files

resource "azurerm_resource_group" "main_rg" {
  name     = "RES_DEV_FOR_TEST"
  location = "westeurope"

  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_static_site" "common-static-web" {
  name                = "SWA-FOR-TEST"
  resource_group_name = azurerm_resource_group.main_rg.name
  location            = azurerm_resource_group.main_rg.location
}

### Debug Output

https://gist.github.com/azieh/19b3124a632cdc7aa7b140a687e5fdfe

### Expected Behaviour

Resource should be created

### Actual Behaviour

Above error do not allow deploy service

### Steps to Reproduce

Just try to create simple resource. Nothing more.

### Important Factoids

When SKU is set to "Standard", Azure resource is create without any error. After that in Azure Portal is possible to change SKU to Free.

### References

* #0000

**Comment by jackofallops** [comment]
Hi @azieh - Thanks for opening this issue.  We saw this in our overnight tests also.  However, I've just successfully built a couple Free tier resources (in West Europe and West US 2) with the provider, so I believe this may have been a transient service side problem. Could you check again and update here with the result?

**Comment by azieh** [comment]
Hi @jackofallops.
That error occurred on my client azure subscription. 

I try once again on my private azure subscription with same result. 

`resource "azurerm_static_site" "common-static-web" {
  name                = "mgos-commonui-swa"
  resource_group_name = "Common"
  location            = "westeurope"
}`

with result

`PS D:\Coding\tftest> terraform apply "tfplan"
azurerm_static_site.common-static-web: Creating...
╷
│ Error: failed creating Static Site: (Name "mgos-commonui-swa" / Resource Group "Common"): web.StaticSitesClient#CreateOrUpdateStaticSite: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="SkuCode 'SKU' is invalid." Details=[{"Message":"SkuCode 'SKU' is invalid."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"55925","Message":"SkuCode 'SKU' is invalid.","MessageTemplate":"SkuCode '{0}' is invalid.","Parameters":["SKU","Free"]}}]
│
│   with azurerm_static_site.common-static-web,
│   on main.tf line 1, in resource "azurerm_static_site" "common-static-web":
│    1: resource "azurerm_static_site" "common-static-web" {
│
╵`

I did test on locations:  westeurope and westus2.

**Comment by magodo** [comment]
From my experiments, it turns out that if the request is as below, the API will raise the error:

```json
{
    "identity": {
        "type": "None"
    },
    "location": "West Europe",
    "tags": {},
    "properties": {
    },
    "sku": {
        "name": "Free",
        "tier": "Free"
    }
}
```

While, it works if remove the `identity` blocks above. While it always works for "Standard" sku. Presumably the service team removed the identity supports for "Free" sku?

**Comment by azieh** [comment]
@magodo you have right. Identity is not supported on "Free" SKU.

**Comment by magodo** [comment]
@azieh I didn't find any document mentioning this, do you know where it is announced?

**Comment by azieh** [comment]
@magodo I did a simple check on Azure Portal. Please take a look at the attachment. You can notice which features are disabled on the "Free" SKU. Identity is one of those that are disabled.
![image](https://user-images.githubusercontent.com/10528511/151330224-a191fc41-e94a-4e6d-8672-b3b79721e988.png)

![image](https://user-images.githubusercontent.com/10528511/151330361-f2e4c2fb-f7d5-4d95-9b54-6cafee49b47c.png)

**Comment by magodo** [comment]
@azieh Thanks! While which one in above list corresponds to the `identit`?
