### ISSUE TITLE
Mysql Flexible server administrator_login name is not supporting special characters

### ISSUE THREAD

**Issue by sadikalp01** [hashicorp/terraform-provider-azurerm#15128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
 
terraform = 1.0.8
azurerm = 2.93.1

### Affected Resource(s)

* `azurerm_mysql_flexible_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_flexible_server" "example" {
  name                   = "example-fs"
  resource_group_name    = azurerm_resource_group.mysql-flexible.location
  location               = azurerm_resource_group.mysql-flexible.location
  administrator_login    = "psqladmin_dev"
  administrator_password = "H@Sh1CoR3!"
  backup_retention_days  = 7
  delegated_subnet_id    = azurerm_subnet.subnet.id
  private_dns_zone_id    = azurerm_private_dns_zone.mysql-private-dzone.id
  sku_name               = "GP_Standard_D2ds_v4"

  depends_on = [azurerm_private_dns_zone_virtual_network_link.mysql-vnet-link]
}
```

### Panic Output

 Error: "administrator_login" must only contains characters and numbers, got psqladmin_dev
│
│   with azurerm_mysql_flexible_server.example,
│   on main.tf line 121, in resource "azurerm_mysql_flexible_server" "example":
│  121:   administrator_login    = "psqladmin_dev"

### Expected Behaviour

administrator_login is not accepting special characters, where as when creating directly in portal it is accepting special characters like _, -, @ etc... pls allow user to pass in special characters with user name creation.  

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by anandsaidba12** [comment]
Is there any update on this issue?

**Comment by aristosvo** [comment]
Hi @anandsaidba12! I created a PR [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/15280)

To validate your issue, can you provide a screenshot with characters other than _ being used in the `administrator_login`? In my experience only `_` is allowed as a special character.

**Comment by wescst01** [comment]
![image](https://user-images.githubusercontent.com/75334708/152820854-74c641d8-1d69-4cac-8211-846627647200.png)

**Comment by aristosvo** [comment]
> ![image](https://user-images.githubusercontent.com/75334708/152820854-74c641d8-1d69-4cac-8211-846627647200.png)
> 
> 

Hi @wescst01 👋 

This feature as requested is not released yet, is there anything special about your setup which requires attention?

**Comment by wescst01** [comment]
We also implement Azure single servers.
Our infrastructure needs to be able to use the same admin login across single and flexible servers.
The flex server admin login criteria should match that of single server.

**Comment by jamie-sweeney** [comment]
+1
we have this issue as well and had to change to remove the underscore ... it did not rise to the level of opening an issue for us but we would also rather be constant across servers, clouds and types as referenced.
