### ISSUE TITLE
azurerm_key_vault has "ConflictError" when building, recommended fix from Azure is to serialize actions

### ISSUE THREAD

**Issue by jblackwood12** [hashicorp/terraform-provider-azurerm#15127]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
2.93.1

### Affected Resource(s)

* azurerm_key_vault

### Terraform Configuration Files

```hcl
I can't add the configuration files yet, because I need to be sure no sensitive data is shared.
```

### Debug Output

`Error: creating Vault: (Name "samplekvname" / Resource Group "samplergname"): keyvault.VaultsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ConflictError" Message="A conflict occurred that prevented the operation from completing. The operation failed because the Key Vault 'samplekvname' changed from the point the operation began. This can happen if parallel operations are being performed on the Key Vault. To prevent this error, serialize the operations so that only one operation is performed on the Key Vault at a time. Follow this link for more information: https://go.microsoft.com/fwlink/?linkid=2147741`

### Expected Behaviour

Should have built the "azurerm_key_vault"

### Actual Behaviour

Fails to build the "azurerm_key_vault"

### Steps to Reproduce

1. `terraform apply`

### References

* Seems similar to this older resolved issue (for a different resource): https://github.com/hashicorp/terraform-provider-azurerm/issues/10582

**Comment by jblackwood12** [comment]
I've just tried using `parallelism=1` and got the same error. I'll look at the terraform configuration next.

**Comment by jblackwood12** [comment]
Looks like this could be due to the soft deleted key conflicting with the new key being created which has the same name. I'm testing this out by adding this to the azurerm features block:
```
key_vault { purge_soft_delete_on_destroy = true }
```

**Comment by sinbai** [comment]
> Looks like this could be due to the soft deleted key conflicting with the new key being created which has the same name. I'm testing this out by adding this to the azurerm features block:
> 
> ```
> key_vault { purge_soft_delete_on_destroy = true }
> ```

@jblackwood12 thanks for opening this issue. If this issue persists after testing, could you please provide your terraform config that could help repro and troubleshooting?

**Comment by jblackwood12** [comment]
@sinbai I've resolved the issue.

As of 1/19/2022, Azure started ensuring "soft-delete" was used when deleting a "Key Vault". The application we were using to communicate to Azure (via Terraform) did not have permissions to purge soft-deleted Key Vaults.

So, I delegated an Azure Key Vault role which had the "purge" soft-delete permission. And, also I've used the block I mentioned above.
