### ISSUE TITLE
azurerm_log_analytics_datasource_windows_event error with ID was missing the `dataSources` element

### ISSUE THREAD

**Issue by floryut** [hashicorp/terraform-provider-azurerm#15122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.4
* AzureRM Provider version: 2.93.0

### Description / Feedback

Since provider version v2.89.0 we have the following error
```
╷
│ Error: ID was missing the `dataSources` element
│
│   with module.xxxx-log-analytics-0001-datasources.azurerm_log_analytics_datasource_windows_event.windows_event_system,
│   on .terraform/modules/xxxx-log-analytics-0001-datasources/azure/loganalytics/loganalytics_datasources/main.tf line 41, in resource "azurerm_log_analytics_datasource_windows_event" "windows_event_system":
│   41: resource "azurerm_log_analytics_datasource_windows_event" "windows_event_system" {
│
╵
```
We also had the error with `ID was missing the 'dataSources' element -"azurerm_log_analytics_datasource_windows_performance_counter"` so I guess this was fixed with #14916 but missed for `azurerm_log_analytics_datasource_windows_event` ?

### References
n/a

**Comment by Blankf** [comment]
i`m having the same problem 👍

**Comment by mickare** [comment]
We have the same issue. And we suspect that the Terraform state contains an invalid / old ID, that ends with the following example `.../datasources/logagent-windows-events-system`.

What should we do to solve this problem?

**Comment by surlypants** [comment]
│ Error: ID was missing the `dataSources` element
│
│   with module.la_workspaces.azurerm_log_analytics_datasource_windows_event.eventlog[0],

```
terragrunt state show module.la_workspaces.azurerm_log_analytics_datasource_windows_event.eventlog[0] 2>/dev/null
# module.la_workspaces.azurerm_log_analytics_datasource_windows_event.eventlog[0]:
resource "azurerm_log_analytics_datasource_windows_event" "eventlog" {
    event_log_name      = "System"
    event_types         = [
        "error",
        "warning",
    ]
    id                  = "/subscriptions/XXX/resourceGroups/YYY/providers/Microsoft.OperationalInsights/workspaces/ZZZ/datasources/System"
    name                = "System"
    resource_group_name = "YYY"
    workspace_name      = "ZZZ"
}
```

yep. looks like state has "datasources" while the provider is anticipating "dataSources"

**Comment by koikonom** [comment]
@surlypants can you please provide the full debug log from that plan ?
