### ISSUE TITLE
Support for adding Windows Server node pool with containerd in azurerm_kubernetes_cluster_node_pool

### ISSUE THREAD

**Issue by sossickd** [hashicorp/terraform-provider-azurerm#15137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Beginning in Kubernetes version 1.20 and greater, you can specify containerd as the container runtime for Windows Server 2019 node pools. From [Kubernetes 1.23](https://github.com/Azure/AKS/pull/2751/files), containerd will be the default container runtime for Windows. Docker support will be deprecated in Kubernetes 1.24.

This can be enabled by adding the following parameter `--aks-custom-headers WindowsContainerRuntime=containerd` when creating a Windows node pool.

```console
az aks nodepool add \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --os-type Windows \
    --name npwcd \
    --node-vm-size Standard_D4s_v3 \
    --kubernetes-version 1.20.5 \
    --aks-custom-headers WindowsContainerRuntime=containerd \
    --node-count 1
```

For more information visit [here](https://docs.microsoft.com/en-us/azure/aks/windows-container-cli#optional-using-containerd-with-windows-server-node-pools)

This feature will give AKS cluster operators the ability to start testing Windows workloads on a node pool running the containerd runtime ahead of Docker being removed in Kubernetes 1.24.

### New or Affected Resource(s)

*  azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "windows_node_pool" {
  name                 = "test"
  orchestrator_version = "1.20.13"
  os_type = "Windows"
  windows_container_runtime = "Containerd"

  kubernetes_cluster_id = azurerm_kubernetes_cluster.my_cluster.id
  
  ...
}
```

There would need to be some validation to ensure `os_type` is set to `Windows` and that the Kubernetes version is between `1.20.x and 1.23.x`. 

If `Null` flag would be omitted.

### References

* #0000

**Comment by mybayern1974** [comment]
@sossickd , thank you for opening this issue. Do you think this issue could be duplicate with [issue 6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793)? If so, would you mind if we close this issue and instead you could subscribe to [issue 6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793)?

**Comment by sossickd** [comment]
Thanks for the quick reply @mybayern1974 having read through issue 6793 this would enable this feature. I will close this issue and subscribe.

**Comment by sossickd** [comment]
Anyone who comes across this this issue and subsequently subscribes to issue [6793](https://github.com/hashicorp/terraform-provider-azurerm/issues/6793) this has a closed [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14178) with a status or `wontfix` which isn't too promising.
