### ISSUE TITLE
Support for ssh keypair creation and one-time retrieval of private key

### ISSUE THREAD

**Issue by tspearconquest** [hashicorp/terraform-provider-azurerm#15135]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We have a requirement to generate an SSH keypair in Azure using terraform which can be used to access VMs after the keypair is created.

The azure cli can create this resource and dumps the private key into the user's `~/.ssh` directory.
In addition, the portal also provides a way to generate an SSH keypair and gives the user an option to download the private key to their machine. Upon downloading the key, it is in PEM format, from which the public key can easily be extracted (at least on my Mac) with `ssh-keygen -y -f downloaded_file.pem` to the correct format for using in an ssh public key file on the a VM.

The goal is to create a resource for this in terraform and then use the public key output from that to populate the `azurerm_linux_virtual_machine` resource's `ssh_key` block's `public_key` field.

Then upon the VM being created, we can go to the portal and download the private key from a one-time download link (similar to what the portal has now) so that we can login, or the private key could be output in some way that it can be read by some other automation to leverage the private key for making connections to the VM (such as using Ansible for post-build configuration).

The current workaround for this is to manually create the keypair before running terraform, and then using the `file()` function to read the public keyfile into the above mentioned field. This is prone to error because the private key is unique to the machine where it was generated unless it is shared, and updates to the shared key can lead to errors or possible compromise if someone didn't get the update and runs terraform, or uses a wrong key during a replacement, etc.

Therefore, it is desirable to have Azure handle this and provide the user a way to download the key once.

### New or Affected Resource(s)

* azurerm_ssh_keypair - PROPOSED

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_ssh_keypair" "default" {
  name = var.name
  resource_group = var.rg_name

  ... (typical ssh key configuration options such as the type of key (RSA/ECDSA), key size or curve parameters, etc.
}
```

**Comment by tspearconquest** [comment]
Other options have been investigated as well. We looked at resources that already exist such as `azurerm_ssh_public_key` and `azurerm_key_vault_key`.

The former doesn't handle private keys at all, so it has no access to output them.
The latter can create a private keypair, but offers no option to export or retrieve the private key under any circumstances via any method, and also offers no option via terraform to import an existing private key from a file. It is possible to import a private key from a file via the azure cli as well as the portal (both the keyvault and the the ssh keys ui offer this option), but we are hoping to do it with terraform.

**Comment by tombuildsstuff** [comment]
hi @tspearconquest 

Thanks for opening this issue.

From memory the Azure Portal is generating these client-side and then uploading the public key to the Azure API, as such there's no API for generating a Public/Private Key-Pair within Azure at this time (but it is possible to upload a public key pair via `azurerm_ssh_public_key`).

It should be possible to mirror this behaviour by using [the `tls_private_key` resource](https://registry.terraform.io/providers/hashicorp/tls/latest/docs/resources/private_key) to generate a private key (and then obtain it's public key for use with the `azurerm_ssh_public_key` resource), as this is available within the TLS Provider, we have no plans to add support for generating Private Keys within the AzureRM Provider.

Since this is a configuration question which should be resolved by using the TLS Provider here, I'm going to close this issue for the moment - but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by tombuildsstuff** [comment]
@tspearconquest a Key Vault Key is a Key-Value pair, not an SSH Key, a certificate pair can be generated using the `azurerm_key_vault_certificate` resource (which in itself backed by a Key Vault Key) which can be used for other things (such as signing) - but this isn't an SSH Key.

**Comment by tspearconquest** [comment]
Really? Wow, that is a completely different answer than I was expecting. I really missed the mark on that one if a Key vault Key is a Key-Value pair... I thought I had done my research too because https://stackoverflow.com/questions/61940541/how-to-add-a-key-value-in-a-azure-key-vault says that its for encryption keys and that key value pairs go in the Secrets section (which is an `azurerm_key_vault_secret` resource)

So, I have a follow up question then which is: is an `azurerm_key_vault_secret` resource is the recommended place for storing a private key centrally for consumption by automation?
