### ISSUE TITLE
Support for azurerm_kusto_database data source.

### ISSUE THREAD

**Issue by jakucera** [hashicorp/terraform-provider-azurerm#15133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Feature request to add support for importing existing Kusto databases as a data source in terraform.

### New or Affected Resource(s)

* azurerm_kusto_database

### Potential Terraform Configuration

data "azurerm_resource_group" "kusto_cluster_rg" {
  name = "kustoclusters"
}

data "azurerm_kusto_cluster" "kusto_cluster" {
  name                = "kustocluster01"
  resource_group_name = data.azurerm_resource_group.kusto_cluster_rg.name
}

**data "azurerm_kusto_database" "kusto_db" {
  name                = "kustodatabase"
  resource_group_name = data.azurerm_resource_group.kusto_cluster_rg.name
  cluster_name        = data.azurerm_kusto_cluster.kusto_cluster.name
}**

### References

* #0000

**Comment by catriona-m** [comment]
Closing as this has been fixed by #16180
