### ISSUE TITLE
`azurerm_network_security_group` `azurerm_network_security_rule` Try recreate When nothing changed

### ISSUE THREAD

**Issue by Uanid** [hashicorp/terraform-provider-azurerm#15146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
v2.39.1

### Affected Resource(s)

* `azurerm_network_security_group`
* `azurerm_network_security_rule`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_rule" "myrule" {
  name                         = "my-udp-rule"
  priority                       = 1000
  direction                    = "Inbound"
  access                       = "Allow"
  protocol                     = "Udp"
  source_port_range            = "*"
  source_address_prefix        = "*"
  destination_port_range       = "1024-65535"
  network_security_group_name  = data.azurerm_resources.data_plane_nsg.resources.0.name
  destination_address_prefixes = data.terraform_remote_state.vnet.outputs.game_session_subnet_cidrs


  # This Line has Problem
  resource_group_name          = "MC_myrg"
}
```

### Plan Output

```
# azurerm_network_security_rule.udpallow must be replaced
-/+ resource "azurerm_network_security_rule" "udpallow" {
      - destination_application_security_group_ids = [] -> null
      - destination_port_ranges                    = [] -> null
      ~ id                                         = "/subscriptions/***/resourceGroups/mc_myrg/providers/Microsoft.Network/networkSecurityGroups/my-nsg/securityRules/udp-dedicated" -> (known after apply)
        name                                       = "udp-dedicated"
      ~ resource_group_name                        = "mc_myrg" -> "MC_myrg" # forces replacement
      - source_address_prefixes                    = [] -> null
      - source_application_security_group_ids      = [] -> null
      - source_port_ranges                         = [] -> null
        # (9 unchanged attributes hidden)
    }
```

### Expected Behaviour

Plan skip.

### Actual Behaviour

Destroy and Then Create Resource.

### Steps to Reproduce

1. Create Network Security Rule with uppercase contains ResourceGroup (ex: MC_blah_blah)
2. Re plan Terraform code with `terraform plan`

### Important Factoids

AzureRM API server always return lowsercase ResourceGroup name.

**Comment by sinbai** [comment]
@Uanid thanks for opening this issue.  This issue has been fixed and released in v2.93.0 of the Terraform Provider. Could you please upgrade version and try again?

**Comment by LaurentLesle** [comment]
using 2.98 we had to set explicitly the optionals plural attributes to [] and the other optional text to '' to overcome that issue.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
