### ISSUE TITLE
Misspelling of variable to opt-in to beta

### ISSUE THREAD

**Issue by briangseagen** [hashicorp/terraform-provider-azurerm#15155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.4
* AzureRM Provider version: 2.85.0

### Terraform Configuration Files

This is a documentation issue on the following page: https://registry.terraform.io/providers/hashicorp/azurerm/2.78.0/docs/guides/3.0-beta

### Description / Feedback

This is a documentation issue on the following page: https://registry.terraform.io/providers/hashicorp/azurerm/2.78.0/docs/guides/3.0-beta

In the documentation it states to set the following flag to enable the Beta resources for azurerm 3.0
ARM_PROVIDER_THREEPOINTZERO_RESOURCES
But this did not work, the correct key should be:
ARM_THREEPOINTZERO_BETA_RESOURCES

### References

Correct value was found here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-app-service-beta

**Comment by ms-henglu** [comment]
Hi @briangseagen , thanks for reporting this issue.

It has been updated in the latest doc: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-app-service-beta

**Comment by mybayern1974** [comment]
@briangseagen , with ms-heng's update, are you ok if we close this issue?

**Comment by manicminer** [comment]
Looks like this error has been fixed/removed from the docs. Thanks for reporting!
