### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by matkosoric** [hashicorp/terraform-provider-azurerm#15161]
Documentation page for **azurerm_postgresql_server** contains broken link:

[Terraform documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_server)

[Broken link](https://docs.microsoft.com/en-us/rest/api/postgresql/servers/create#StorageProfile)

**Comment by Fazer87** [comment]
Fixed in PR #15242 - but no idea how to close issues - can someone please tidy up after me? (sorry, still learning git/github)

**Comment by stephybun** [comment]
Closed by #15714
