### ISSUE TITLE
local-network-gateway fails to update address_space

### ISSUE THREAD

**Issue by JoakimBG** [hashicorp/terraform-provider-azurerm#15163]
**Terraform (and AzureRM Provider) Version**

Terraform version 1.1.4
Azurerm version 2.93.1

**Affected Resource(s)**

azurerm_local_network_gateway

**Error description**

When changing addresses in the list in address_space there is an error like this:

Error: removing Local Network Gateway: (Name "core-vpn-lgw" / Resource Group "core-network-rg"): network.LocalNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LocalNetworkGatewayCannotHaveEmptyAddressPrefixAndBgpSettings" Message="The local network gateway /subscriptions/[SUBS_ID]/resourceGroups/core-network-rg/providers/Microsoft.Network/localNetworkGateways/core-vpn-lgw cannot have both empty address prefix and empty BGP Settings." Details=[]

What I try to do is to remove one IP range from the list and add another to the list. The same happens if only adding IP range also.

**Comment by mybayern1974** [comment]
@JoakimBG Thank you for opening this issue. With assuming this issue might be duplicate with #15109 , would you mind if we close this issue and you can subscribe #15109 ?

**Comment by JoakimBG** [comment]
Closing this as it is duplicate to  #15109
