### ISSUE TITLE
Plan fails when trying to provision Front Door with 2.94

### ISSUE THREAD

**Issue by fcatacut** [hashicorp/terraform-provider-azurerm#15170]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
```

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "2.94.0"
  features {}
}

resource "azurerm_resource_group" "this" {
  name     = "FrontDoorExampleResourceGroup"
  location = "eastus2"
}

resource "azurerm_frontdoor" "this" {
  name                                         = "example-FrontDoor"
  resource_group_name                          = azurerm_resource_group.this.name
  enforce_backend_pools_certificate_name_check = false

  routing_rule {
    name               = "exampleRoutingRule1"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["exampleFrontendEndpoint1"]
    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "exampleBackendBing"
    }
  }

  backend_pool_load_balancing {
    name = "exampleLoadBalancingSettings1"
  }

  backend_pool_health_probe {
    name = "exampleHealthProbeSetting1"
  }

  backend_pool {
    name = "exampleBackendBing"
    backend {
      host_header = "www.bing.com"
      address     = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "exampleLoadBalancingSettings1"
    health_probe_name   = "exampleHealthProbeSetting1"
  }

  frontend_endpoint {
    name      = "exampleFrontendEndpoint1"
    host_name = "example-FrontDoor.azurefd.net"
  }
}
```

### Debug Output

<https://gist.github.com/fcatacut/5852d1198afa86d7aa29939f59a95f47>

### Expected Behaviour

`terraform plan` should have successfully completed.

### Actual Behaviour

>  Error: "frontdoorexampleresourcegroup" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,southindia,westindia,centralindia,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast,westus3,swedencentral,swedensouth"
> 
>   with azurerm_frontdoor.this,
>   on main.tf line 13, in resource "azurerm_frontdoor" "this":
>   13:   resource_group_name                          = azurerm_resource_group.this.name

### Steps to Reproduce

1. Run `terraform plan`.

### Important Factoids

`terraform plan` succeeds with AzureRM 2.93.1.

### References

* #0000

**Comment by aliscott** [comment]
Looks related to this change: https://github.com/hashicorp/terraform-provider-azurerm/commit/a997dedf69763fa2ab8a8089a998ef20e79948e0#diff-864be0b144742356cdb059a53e70984970619c664e9d2be10afe8b439ec0f05dR104
