### ISSUE TITLE
no versions returned when using data azurerm_blueprint_definition

### ISSUE THREAD

**Issue by tikicoder** [hashicorp/terraform-provider-azurerm#15177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform -v
Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

data azurerm_blueprint_definition

### Expected Behaviour

When I pull in the blueprint definition I would expect the version to populate

### Actual Behaviour

the versions are returned as list(null)

"description" = <<-EOT
description returned
EOT
"display_name" = "blueprint test"
"id" = "/providers/Microsoft.Management/managementGroups/groupTest/providers/Microsoft.Blueprint/blueprints/bp-test"
"last_modified" = "2022-01-27T03:46:03.2656857Z"
"name" = "bp-test"
"scope_id" = "/providers/Microsoft.Management/managementGroups/groupTest"
"target_scope" = "subscription"
"time_created" = "2022-01-27T01:58:31Z"
"timeouts" = null /* object */
"versions" = tolist(null) /* of string */

### Steps to Reproduce

Create a management group 
Create a blueprint on that group 
then try to pull the info in terraform using the data object

* #0000

**Comment by xiaxyi** [comment]
@tikicoder  may i know if you published the blueprint?

**Comment by tikicoder** [comment]
@xiaxyi yes I have the blueprints published.
It would be nice if the version returned a list like you suggested. This way I could do some automagic around running the publish terraform only if there is a new version. It not as much of an issue at the moment it looks like the ARM deployment has gotten smarter so it only pushes when an update iis ready.

**Comment by xiaxyi** [comment]
@tikicoder  Let me see if there is any way to get the version list

**Comment by tikicoder** [comment]
@xiaxyi  thanks
