### ISSUE TITLE
Support for dynamic private ip allocation on AKS cluster

### ISSUE THREAD

**Issue by essale** [hashicorp/terraform-provider-azurerm#15186]
Dear community 

There is an amazing azure feature witch is on public preview and needs to get community support in order to be implemented.
On large-scale clusters, you might encounter with the suffocation of private Ip.

Useful Links
https://azure.microsoft.com/en-us/updates/public-preview-dynamic-ip-allocation-enhanced-subnet-support-in-aks
https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#dynamic-allocation-of-ips-and-enhanced-subnet-support-preview

**Comment by aristosvo** [comment]
Hi @essale! Thanks for raising this issue.

Fortunately it is probably already implemented. To specify your podSubnet for the default nodepool, you can use `azurerm_kubernetes_cluster.default_node_pool.pod_subnet_id`, for other nodepools use `azurerm_kubernetes_cluster_node_pool.pod_subnet_id`.

This requires that the Preview Feature Microsoft.ContainerService/PodSubnetPreview is enabled and the Resource Provider is re-registered, see the [d ocumentation](https://docs.microsoft.com/en-us/azure/aks/configure-azure-cni#register-the-podsubnetpreview-preview-feature) for more information.

I'll close this issue for now. If there is anything missing, let me know!
