### ISSUE TITLE
Cannot attach role to service principal

### ISSUE THREAD

**Issue by Danpiel** [hashicorp/terraform-provider-azurerm#15197]
### Terraform (and AzureRM Provider) Version

Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/aztfmod/azurecaf v1.2.11
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Expected outcome

Existing role Contributor is applied to the k8s_prod service principal at subscription scope

### Actual outcome

Loops to 30 minutes and dies

### Affected Resource(s)

azurerm_role_assignment
azuread_service_principal

### Terraform Configuration Files

```hcl
resource "azuread_application" "k8s_prod" {
  display_name = "k8s_prod"
  owners       = [data.azuread_client_config.current.object_id]
}

resource "azuread_service_principal" "k8s_prod" {
  application_id               = azuread_application.k8s_prod.application_id
  app_role_assignment_required = false
  owners                       = [data.azuread_client_config.current.object_id]
  feature_tags {
    hide = true
  }
}

resource "azuread_service_principal_password" "k8s_sp_secret" {
  service_principal_id = azuread_service_principal.k8s_prod.id
}

resource "azurerm_role_assignment" "subscription" {
  scope                = data.azurerm_subscription.current.id
  role_definition_name = "Contributor"
  principal_id         = azuread_service_principal.k8s_prod.application_id
}
```

### Debug Output
In the loop 

azurerm_role_assignment.subscription: Still creating... [2m10s elapsed]
2022-01-31T20:07:55.342+0200 [DEBUG] provider.terraform-provider-azurerm_v2.93.1_x5: AzureRM Request:
PUT //subscriptions/.../providers/Microsoft.Authorization/roleAssignments/...?api-version=2020-04-01-preview HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.17.5 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v61.1.0 authorization/2020-04-01-preview HashiCorp Terraform/1.1.3 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/2.93.1 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 246
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: ...
Accept-Encoding: gzip

{"properties":{"roleDefinitionId":"/subscriptions/.../providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c","principalId":"...","description":""}}: timestamp=2022-01-31T20:07:55.342+0200
2022-01-31T20:07:55.748+0200 [DEBUG] provider.terraform-provider-azurerm_v2.93.1_x5: AzureRM Response for https://management.azure.com//subscriptions/.../providers/Microsoft.Authorization/roleAssignments/...?api-version=2020-04-01-preview:
HTTP/2.0 400 Bad Request
Content-Length: 163
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 31 Jan 2022 18:07:55 GMT
Expires: -1
Pragma: no-cache
Set-Cookie: x-ms-gateway-slice=Production; path=/; secure; samesite=none; httponly
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: ...
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1150
X-Ms-Request-Id: ...
X-Ms-Routing-Request-Id: SWEDENCENTRAL:...

{"error":{"code":"PrincipalNotFound","message":"```Principal id without dashes``` does not exist in the directory ...."}}: timestamp=2022-01-31T20:07:55.748+0200
azurerm_role_assignment.subscription: Still creating... [2m20s elapsed]

### Panic Output

None

### Important Factoids

None

### References

* #4642

**Comment by favoretti** [comment]
Hi there and thank you for reporting this issue. I might be wrong, but don't you need to use `.object_id` in assignment?

**Comment by Danpiel** [comment]
Seems working, thank you.
