### ISSUE TITLE
AKS VMCacheSizeTooSmall

### ISSUE THREAD

**Issue by k7faq** [hashicorp/terraform-provider-azurerm#15200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.31
+ provider.azurerm v2.72.0
```

### Affected Resource(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "node_pools" {
  for_each = {
    for node_pool in var.node_pools : node_pool["name"] => node_pool
    if ! lookup(node_pool.tags, "aks_preview", false)
  }

  enable_host_encryption = false
  fips_enabled           = false
  name                   = each.value["name"]
  kubernetes_cluster_id  = azurerm_kubernetes_cluster.this.id
  vm_size                = each.value["vm_size"]
  min_count              = each.value["min_count"]
  max_count              = each.value["max_count"]
  max_pods               = each.value["max_pods"]
  node_labels            = each.value["labels"]
  node_taints            = each.value["taints"]
  enable_node_public_ip  = each.value["public"]
  enable_auto_scaling    = each.value["auto_scale"]
  vnet_subnet_id         = var.subnet_id
  os_disk_size_gb        = each.value["os_disk_size_gb"]
  os_disk_type           = each.value["os_disk_type"]
  availability_zones     = each.value["availability_zones"]
  orchestrator_version   = azurerm_kubernetes_cluster.this.kubernetes_version
  tags                   = each.value["tags"]
}
```

Where

```hcl
variable "node_pools" {
  description = <<EOD
The configuration of the aks node pools. Please see the following terraform documentation for field details:
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html
EOD
  type = list(object({
    name               = string
    auto_scale         = bool
    min_count          = number
    max_count          = number
    max_pods           = number
    public             = bool
    vm_size            = string
    labels             = map(string)
    tags               = map(string)
    taints             = list(string)
    max_pods           = number
    os_disk_size_gb    = number
    os_disk_type       = string
    availability_zones = list(number)
  }))
  default = []
}

node_pools = [
  {
    name               = "10gencpu"
    min_count          = 2 # Prod = 2
    max_count          = 8 # == Maximum number of CPUs in Quota / Number of CPUs per node
    node_count         = 2
    max_pods           = 154                 # = 3.5 times number of cores
    vm_size            = "Standard_D48ds_v5" 
    labels             = {}
    taints             = ["hostingClass=10gencpu:NoSchedule"]
    auto_scale         = true
    public             = false
    os_disk_size_gb    = 256
    os_disk_type       = "Managed"
    tags               = {}
    availability_zones = [1, 2, 3]
  },
]
```

### Debug Output

```bash
Error: creating/updating Managed Kubernetes Cluster Node Pool "10gencpu" (Resource Group "my-resource-group"): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="VMCacheSizeTooSmall" Message="The virtual machine size Standard_D48ds_v5 has a cache size of 0 bytes, but the OS disk requires 274877906944 bytes. Use a VM size with larger cache or disable ephemeral OS."
```

### Expected Behaviour

A node pool was expected to be provisioned with the new SKU.

### Actual Behaviour

Received above error

### Steps to Reproduce

1. `terraform apply`

Note the error reporting insufficient cache and no ability to define cache limits.

### Important Factoids

Running in EastUS Region. Not government.

### References

* #0000

**Comment by stephybun** [comment]
Hi @k7faq,

Thanks for opening this issue! At this point in time AKS only supports VMs that have a cache disk which `Standard_D48ds_v5` unfortunately does not. [This comment over on the AKS repo](https://github.com/Azure/AKS/issues/2699#issuecomment-995936013) should help explain which VMs are supported.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
