### ISSUE TITLE
azurerm_storage_account keeps trying to add access_tier 'Hot' for Premium BlockBlobStorage

### ISSUE THREAD

**Issue by Gerrit-K** [hashicorp/terraform-provider-azurerm#15210]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = "~> 2.0"
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_storage_account" "storage_account" {
  access_tier              = "Hot"  // doesn't matter if this is set, the current provider always defaults it to "Hot"
  account_kind             = "BlockBlobStorage"
  account_replication_type = "ZRS"
  account_tier             = "Premium"
  location                 = "westeurope"
  min_tls_version          = "TLS1_2"
  name                     = "testingstorage"
  resource_group_name      = "testingstorage"
}
```

### Debug Output

(after the ***second*** `terraform apply`)
```
Terraform will perform the following actions:

  # azurerm_storage_account.storage_account will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
      + access_tier                       = "Hot"
        id                                = "/subscriptions/<subscriptionid>/resourceGroups/testingstorage/providers/Microsoft.Storage/storageAccounts/testingstorage"
        name                              = "testingstorage"
        # (26 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

For `account_tier = "Premium"` and `account_kind = "BlockBlobStorage"` the field `access_tier` should not have any effect (since only `Hot` is allowed and the provider defaults to this value). Successive calls to `terraform apply` with the same configuration should not show any changes.

### Actual Behaviour

When (re-)applying this configuration on an existing storage account, the provider keeps reporting that it will add `access_tier = "Hot"` to the resource state. However, this is never done and the next call will yield the same message.

### Steps to Reproduce

1. `terraform apply` on the file posted above
2. A second `terraform apply` on the exact same file without changing anything

### Workaround

As a simple workaround you can add
```hcl
  lifecycle {
    ignore_changes = [
      access_tier
    ]
  }
```

### Additional information

We observed this behavior since some point between the 17th and 18th of January (without having changed anything in our infrastructure). This might perhaps be related to an upstream change in the Azure API, but I didn't find any official changelogs. I just noticed that `az storage account show` doesn't show this field either, so perhaps they have silently removed this field (which only applies to kinds `BlobStorage`, `FileStorage` and `StorageV2` after all).

**Comment by G0PINATH-WW** [comment]
I have the same issue, same code worked till 2.87.0 without this issue. I am  facing this issue while deploying Premium Blob storage accounts ONLY. General Storage, File Storage Premium and Blob Standard seems to be fine.

**Comment by Gerrit-K** [comment]
I don't believe it has something to do with the provider version, since we suddenly observed this issue without changing it (and we were running `2.85.0`). 

To add another observation that seems to support my assumption, I've found the first pipeline run where this happened and it included the following logs:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # azurerm_storage_account.storage_account has changed
  ~ resource "azurerm_storage_account" "storage_account" {
      - access_tier                    = "Hot" -> null
        id                             = "<redacted>"
        name                           = "<redacted>"
        # (23 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

────────────────────

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_storage_account.storage_account will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
      + access_tier                    = "Hot"
        id                             = "<redacted>"
        name                           = "<redacted>"
        # (23 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

This shows that something changed externally from terraform's point of view, but since we didn't touch this resource, I assume it's the underlying API that changed its response slightly.

**Comment by G0PINATH-WW** [comment]
Sorry it may have been before 2.85.0 then, I just pulled that version on top of my head - not very sure of which version exactly broke this.

**Comment by Gerrit-K** [comment]
Just as a semi-related side node (and to bump this once more): same thing seems to be happening for `customer_managed_key.key_vault_key_id`, if a managed key is deployed as a standalone resource, referencing the storage account (instead of deploying it directly in the storage account resource).
```
  # azurerm_storage_account.storage_account will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
        id                                = "<redacted>"
        name                              = "<redacted>"
        tags                              = {}
        # (27 unchanged attributes hidden)


      - customer_managed_key {
          - key_vault_key_id = "<redacted>" -> null
        }


        # (3 unchanged blocks hidden)
    }
```
I can raise this as a separate issue, if desired. The workaround is the same (add it to `ignore_changes`) and it doesn't hurt much, but it would still be nice to have it fixed eventually.

**Comment by Poil** [comment]
Hi,

I still have the error on azurerm 3.93.0 provider.
Is this has been released ?

Regards
