### ISSUE TITLE
Azure Storage Account network rule: storage_account_name is a required argument

### ISSUE THREAD

**Issue by fvdnabee** [hashicorp/terraform-provider-azurerm#15225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v1.1.4
- azurerm v2.94.0

### Affected Resource(s)

* azurerm_storage_account_network_rules

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}

  # https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration
  skip_provider_registration = true
}

variable "resource_group_name" {
  type     = string
  nullable = false
}

# resource group already exists and is referenced via a data source
data "azurerm_resource_group" "rg" {
  name = var.resource_group_name
}

resource "azurerm_storage_account" "storage" {
  name = "mystorageaccount"

  resource_group_name       = data.azurerm_resource_group.rg.name
  location                  = data.azurerm_resource_group.rg.location
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  min_tls_version           = "TLS1_2"
  enable_https_traffic_only = true
}

resource "azurerm_storage_account_network_rules" "storage" {
  resource_group_name = data.azurerm_resource_group.rg.name
  storage_account_id  = azurerm_storage_account.storage.id

  default_action = "Deny"
  ip_rules       = ["192.168.0.0/16"]
  bypass         = ["AzureServices", "Logging", "Metrics"]
}

```

### Debug Output

```bash
❯ terraform plan -var 'resource_group_name=my-rgp'
╷
│ Error: Missing required argument
│ 
│   with azurerm_storage_account_network_rules.storage,
│   on main.tf line 30, in resource "azurerm_storage_account_network_rules" "storage":
│   30:   resource_group_name  = data.azurerm_resource_group.rg.name
│ 
│ "resource_group_name": all of `resource_group_name,storage_account_name` must be specified
```

### Expected Behaviour

azurerm_storage_account_network_rules should accept the `storage_account_id` as per [its documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_network_rules) which states that `storage_account_name` is deprecated in favor of `storage_account_id`. 

Additionally, the docs state that both arguments are optional which is not true.

### Actual Behaviour

Terraform failed stating that storage_account_name is a non-optional argument (while the docs state it is optional). 

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
Appears to be due to these RequiredWith since the field is Computed: https://github.com/hashicorp/terraform-provider-azurerm/blob/ef11feb07db2b5fa96d79384cbcdc4e6309922fb/internal/services/storage/storage_account_network_rules_resource.go#L65-L67

**Comment by fvdnabee** [comment]
I proposed a clarification to the docs in #15226
