### ISSUE TITLE
azurerm_kubernetes_cluster  allows only 1 "maintenance_window" blocks.

### ISSUE THREAD

**Issue by sossickd** [hashicorp/terraform-provider-azurerm#15230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_kubernetes_cluster  allows only 1 "maintenance_window" blocks.

Microsoft documentation describes how you can have multiple [maintenance configuration](https://docs.microsoft.com/en-us/azure/aks/planned-maintenance#list-all-maintenance-windows-in-an-existing-cluster)

### New or Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Potential Terraform Configuration

Add named parameter to the maintenance_window block with the default being set to `default`

### References

* https://docs.microsoft.com/en-us/azure/aks/planned-maintenance#list-all-maintenance-windows-in-an-existing-cluster

**Comment by stephybun** [comment]
Thanks for raising this issue @sossickd.

I believe #21760 added support for specifying the other maintenance window types. As such I'm going to go ahead and close this issue. 

Thanks!
