### ISSUE TITLE
Error: expanding `template_content`: invalid character '}' after top-level value

### ISSUE THREAD

**Issue by ddeharo** [hashicorp/terraform-provider-azurerm#15249]
On trying to use an azurerm_resource_group_template_deployment Instead of an azurerm_template_deployment (that did work) I get the issue title error Error: expanding `template_content`: invalid character '}' after top-level value

The deployment template is for a Microsoft.Storage/storageAccounts/fileServices/shares inside a fw protected nfsv3_enabled storage account.

As I mention the equivalent code works for a azurerm_template_deployment but can not be destroyed by terraform.

In case it matters , I am using
#Version
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=2.53.0"
    }
  }
}

This is the  resources code portion in my storage account creation module:

```
#----------------------------------------------------------------
#  STGACCOUNT for NFSv3 purposes: storage_account_nfs	
#----------------------------------------------------------------

# azurerm_storage_account.storage_account_nfs:
resource "azurerm_storage_account" "storage_account_nfs" {
  name                     = var.stgacct_nfs_name
  resource_group_name      = data.azurerm_resource_group.rg_general.name
  location                 = var.location
  account_tier             = var.storage_tier
  account_replication_type = var.storage_replication_type
  min_tls_version          = var.tls_version

  # Values required for NFS3, also account tier = Standard
  account_kind              = var.account_kind
  is_hns_enabled            = var.is_hns_enabled
  enable_https_traffic_only = var.enable_https_traffic_only
  nfsv3_enabled             = var.nfsv3_enabled

  network_rules {
    default_action             = "Deny"
    bypass                     = ["Metrics", "AzureServices"] #to use AzureServices a   service_endpoints = ["Microsoft.Storage"] had to be included in Subnet. See vnet.tf (Note1)
    virtual_network_subnet_ids = ["${data.azurerm_subnet.subnet_batch.id}", "${data.azurerm_subnet.subnet_Mgmt.id}"]
  }

  tags = var.tags
}

# Share creation by means of an ARM Deployment Template. This Kind of template does not need to be externaly destroyed. Tf Should be able
# azurerm_resource_group_template_deployment.stgacct-share
resource "azurerm_resource_group_template_deployment" "stgacct-share" {
  name                = var.stgacct_share_dpl_name
  resource_group_name = data.azurerm_resource_group.rg_general.name
  deployment_mode     = "Complete"

  #depends_on = [azurerm_storage_account.storage_account_nfs]

  parameters_content = jsonencode({
		"storageAccountName" = {
		value = azurerm_storage_account.storage_account_nfs.name
		},
		"fileShareName"      = {
		value = var.nfs_fileShareName
		}
  })
  template_content = <<TEMPLATE
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
	"contentVersion": "1.0.0.0",
	"parameters": {
    "storageAccountName": {
      "type": "string"
		},
	"fileShareName": {
	  "type": "string",
	  "maxLength": 63,
	  "minLength": 3
	}
	},
	"functions": [],
	"resources": [
    {
      "type": "Microsoft.Storage/storageAccounts/fileServices/shares",
      "apiVersion": "2021-04-01",
      "name": "[format('{0}/default/{1}', parameters('storageAccountName'), parameters('fileShareName'))]"
      "dependsOn": [
        "[resourceId('Microsoft.Storage/storageAccounts', parameters('storageAccountName'))]"
      ]
    }
	]
	}

}	
TEMPLATE

}
```

Is there anythin wrong or is a bug? I have read about other like this with other invalid characters nstead of "}"

**Comment by tombuildsstuff** [comment]
hi @ddeharo 

Thanks for opening this issue.

Taking a look through here JSON provided isn't valid - namely this line is missing a comma at the end:

>		"name": "[format('{0}/default/{1}', parameters('storageAccountName'), parameters('fileShareName'))]"

and there's an extra `}` at the end which needs to be removed - fixing these should ensure this validates.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
