### ISSUE TITLE
azurerm_cosmosdb_cassandra_table fails with API error when trying to change between throughput modes

### ISSUE THREAD

**Issue by daniel-anova** [hashicorp/terraform-provider-azurerm#15252]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0

### Affected Resource(s)

* `azurerm_cosmosdb_cassandra_table `

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "bugexample2"
  location = "West Europe"
}


resource "azurerm_cosmosdb_account" "example" {
  name                = "tfex-cosmosdb-table-bug"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  offer_type          = "Standard"

  capabilities {
    name = "EnableCassandra"
  }

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = "West US"
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_cassandra_keyspace" "example" {
  name                = "tfex-cosmos-cassandra-keyspace"
  resource_group_name = azurerm_cosmosdb_account.example.resource_group_name
  account_name        = azurerm_cosmosdb_account.example.name
  throughput          = 400
}

resource "azurerm_cosmosdb_cassandra_table" "example" {
  name                  = "testtable"
  cassandra_keyspace_id = azurerm_cosmosdb_cassandra_keyspace.example.id

  throughput = 4000

  # autoscale_settings {
  #   max_throughput = 4000
  # }

  schema {
    column {
      name = "timestamp"
      type = lower("timestamp") // If not lower it's seen as difference during plan after applied
    }
    partition_key {
      name = "timestamp"
    }
  }
}

```

### Debug Output

https://gist.github.com/daniel-anova/192c997afe151641477af89a1418cb65

### Expected Behaviour

Change to be applied.

### Actual Behaviour

Terraform will give out different errors depending on the transition.

When going from manual to autoscale:
```
Error: updating Throughput for Cassandra Table: (Table Name "testtable" / Cassandra Keyspace Name "tfex-cosmos-cassandra-keyspace" / Database Account Name "tfex-cosmosdb-table-bug" / Resource Group "bugexample2"): Code="BadRequest" Message="Existing offer needs to be autoscale to be able to update autoscale settings\r\nActivityId: 4c288ac4-02f6-4cbb-aa46-aebd1737be11, Microsoft.Azure.Documents.Common/2.14.0"
│ 
│   with azurerm_cosmosdb_cassandra_table.example,
│   on main.tf line 38, in resource "azurerm_cosmosdb_cassandra_table" "example":
│   38: resource "azurerm_cosmosdb_cassandra_table" "example" {
 ```

When going from autoscale to manual:
```
│ Error: updating Cassandra Table: (Table Name "testtable" / Cassandra Keyspace Name "tfex-cosmos-cassandra-keyspace" / Database Account Name "tfex-cosmosdb-table-bug" / Resource Group "bugexample2"): switching between autoscale and manually provisioned throughput via Terraform is not supported at this time
│ 
│   with azurerm_cosmosdb_cassandra_table.example,
│   on main.tf line 38, in resource "azurerm_cosmosdb_cassandra_table" "example":
│   38: resource "azurerm_cosmosdb_cassandra_table" "example" {
│ 
╵
```

### Steps to Reproduce

1. `terraform apply`
2. uncomment `autoscale_settings` and comment `throughput`
3. `terraform apply`
4. change the table in the azure portal (next terraform apply will show no changes)
5. `terraform apply`
6. revert changes to example done in 2. to get the second error
7. `terraform apply`

**Comment by stephybun** [comment]
Hi @daniel-anova,

Thanks for raising this Issue. 
As stated in the [docs for azurerm_cosmosdb_cassandra_table](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_cassandra_table#autoscale_settings):

_Switching between autoscale and manual throughput is not supported via Terraform and must be completed via the Azure Portal and refreshed._

Since this appears to be a limitation in the Azure API that is documented and this forum is intended for feature requests and bugs I am going to close this issue.

Thanks!

**Comment by daniel-anova** [comment]
> Hi @daniel-anova,
> 
> Thanks for raising this Issue. As stated in the [docs for azurerm_cosmosdb_cassandra_table](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_cassandra_table#autoscale_settings):
> 
> _Switching between autoscale and manual throughput is not supported via Terraform and must be completed via the Azure Portal and refreshed._
> 
> Since this appears to be a limitation in the Azure API that is documented and this forum is intended for feature requests and bugs I am going to close this issue.
> 
> Thanks!

Only autoscale to manual gives that error, the reverse operation still gives a "BadRequest" error.

That said, wouldn't it be possible to get the error during plan instead if it's a known limitation?
