### ISSUE TITLE
Support for app service slots in azurerm_app_service_virtual_network_swift_connection

### ISSUE THREAD

**Issue by richardfric** [hashicorp/terraform-provider-azurerm#15259]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.5
* AzureRM Provider version: 2.95

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "my_service_plan" {
  name = "example-plan"
  resource_group_name = "example"
  location = "West Europe"
  os_type = "Windows"
  sku_name = "P1v3"
}

resource "azurerm_windows_web_app" "my_app_service" {
  name = "example-app"
  resource_group_name = "example"
  location = "West Europe"
  service_plan_id = azurerm_service_plan.my_service_plan.id
  site_config {}
}

resource "azurerm_app_service_virtual_network_swift_connection" "my_app_service_vnet_integration" {
  app_service_id = azurerm_windows_web_app.my_app_service.id
  subnet_id = azurerm_subnet.my_subnet.id
}

resource "azurerm_windows_web_app_slot" "my_app_service_slot" {
  name = "example"
  app_service_id = azurerm_windows_web_app.my_app_service.id
  site_config {}
}

resource "azurerm_app_service_virtual_network_swift_connection" "my_app_service_slot_vnet_integration" {
  app_service_id = azurerm_windows_web_app_slot.my_app_service_slot.id
  subnet_id = azurerm_subnet.my_subnet.id
}
```

### Description / Feedback

VNet integration for app service works fine but for slot it ends with error:

**Error**: parsing App Service Resource ID <nil>

**Comment by thomasfrederikhoeck** [comment]
@richardfric I have solved something similar by using `azurerm_app_service_slot_virtual_network_swift_connection` for the slots instead.
