### ISSUE TITLE
azurerm_linux_web_app throws "inconsistent values for sensitive attribute" when passing a password

### ISSUE THREAD

**Issue by pjelar** [hashicorp/terraform-provider-azurerm#15263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.5
* AzureRM Provider version: 2.76.0

### Terraform Configuration Files

```hcl

resource "azurerm_container_registry" "acr" {
  name                = "cpsinfra"
  resource_group_name = azurerm_resource_group.cpsrg.name
  location            = azurerm_resource_group.cpsrg.location
  sku                 = "Premium"
  admin_enabled       = true

  identity {
    type = "SystemAssigned"
  }    
}

resource "azurerm_linux_web_app" "myapi" {
  name                = "myapi"
  resource_group_name = azurerm_resource_group.cpsrg.name
  location            = azurerm_resource_group.cpsrg.location
  service_plan_id     = azurerm_app_service_plan.cpssp.id

  app_settings = {
    "DOCKER_REGISTRY_SERVER_PASSWORD" = azurerm_container_registry.acr.admin_password
    "DOCKER_REGISTRY_SERVER_URL" = azurerm_container_registry.acr.login_server
    "DOCKER_REGISTRY_SERVER_USERNAME" = azurerm_container_registry.acr.admin_username
  }

  site_config {
    container_registry_use_managed_identity = true
    # container_registry_managed_identity_client_id = azurerm_container_registry.acr.identity[0].principal_id
    container_registry_managed_identity_client_id = "1212120-12312-foo"


    application_stack {
      docker_image = "${azurerm_container_registry.acr.login_server}/myapp"
      docker_image_tag = "latest"
    }
  }
  identity {
    type = "SystemAssigned"
  }  

  logs {
    application_logs {
      file_system_level = "Verbose"
    }
    http_logs {
      file_system {
        retention_in_days = 30
        retention_in_mb = 100
      }
    }
    
  }
}
```

### Description / Feedback

Running terraform should set the DOCKER_REGISTRY_SERVER_PASSWORD using the output from the acr resource.

Instead this fails with this error
```bash
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for azurerm_linux_web_app.cpsapi to include new
│ values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
│ .app_settings: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Comment by ecdemomaniaKay** [comment]
Experiencing same issue
- Terraform 1.1.7
- hashicorp/azurerm 3.8.0

**Comment by marcin-dudek** [comment]
I got same issue using  (Terraform Core version: 1.2.2 and AzureRM Provider version: 3.9.0).

**Comment by xiaxyi** [comment]
@pjelar @marcin-dudek may I know if there is any changes to the azure container registry?

**Comment by marcin-dudek** [comment]
I did some more investigation and in the end removing two app settings solved the issue: 
- "AzureWebJobsStorage" = azurerm_storage_account.sa.primary_connection_string
- "APPINSIGHTS_INSTRUMENTATIONKEY" = "@Microsoft.KeyVault(...)"

There was no changes in container registry. I would more lean towards issue happening when you have 'secret' in app settings.

**Comment by xiaxyi** [comment]
@marcin-dudek it's weird as I don't see such error even if I change the password in the app settings. Everything works just fine. are you using the latest provider?

**Comment by marcin-dudek** [comment]
I ended up using provider 3.10.0. I will try to test it with newer version. Maybe will do some small app and try to reproduce this one.

**Comment by marcin-dudek** [comment]
I was trying to reproduce it with no luck. Everything seems to work fine with latest version of provider.

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed I was not able to reproduce this issue with the latest provider, I am going to mark this issue as closed. If this is still an issue with the 3.x latest version of the provider please do let us know by opening a new issue, thanks!
