### ISSUE TITLE
`azurerm_frontdoor` misses correct dependency on its resource group

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#15269]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_frontdoor`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "global" {
  name     = "${local.prefix}-global-rg"
  location ="westeurope"
}

resource "azurerm_frontdoor" "main" {
  name                              = local.frontdoor_name
  resource_group_name    = azurerm_resource_group.global.name
}
```

### Expected Behaviour

Any changes that force a recreate of the resource group, should also force-recreate of Front Door.

### Actual Behaviour

When you change the location of the RG, it obviously recreates the RG but Front Door does not recognize that as a signal to force-recreate, too. Hence, AFD gets deleted as part of the RG recreation but does not get recreated until you run terraform apply again

### Steps to Reproduce

1. Deploy a Resource Group and Front Door as shown above
2. Change the location of the resource group and run apply again

**Comment by sebader** [comment]
@tombuildsstuff I even tried to work around this by adding an explicit dependency on the resource group, but even that didn't make TF to recreate Front Door if the resource group gets re-created. Shouldn't that be the case?

```
resource "azurerm_frontdoor" "main" {
  name                                         = "testfd"
  resource_group_name                          = azurerm_resource_group.global.name

  depends_on = [
    azurerm_resource_group.global
  ]
```

**Comment by WodansSon** [comment]
The legacy Frontdoor is being retired and is no longer being developed.
