### ISSUE TITLE
private_ip_address not optional when private_ip_address_allocation = static

### ISSUE THREAD

**Issue by Klaas-** [hashicorp/terraform-provider-azurerm#15265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0

### Affected Resource(s)

* `azurerm_network_interface`

### Panic Output

` Error: creating Network Interface: (Name "test" / Resource Group "test"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateIPAddressMissing" Message="Private IP address is required when privateIPAllocationMethod is Static in IP configuration /subscriptions/[...]/ipconfig0." Details=[]`

### Expected Behaviour

Failure because static IP needs to be set if using static

### Actual Behaviour

Error from Azure API about missing IP

### Steps to Reproduce

Minimal Resource:
```
resource "azurerm_network_interface" "network_interface" {
  name                = "eth0"
  location            = var.location
  resource_group_name = azurerm_resource_group.resource_group.name

  ip_configuration {
    name                          = "ipconfig0"
    subnet_id                     = var.subnet_id
    private_ip_address_allocation = "Static"
  }
}
```

1. `terraform apply`

### References

* References #15264 I did a docs PR already because I was fixing a different issue in same document

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
