### ISSUE TITLE
Support for SQL Managed Instance - User Assigned Managed Identity

### ISSUE THREAD

**Issue by mdrakiburrahman** [hashicorp/terraform-provider-azurerm#15277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

SQL Managed Instance now supports [User Assigned Managed Identity](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity). This feature is especially great because for Azure AD login, Customers can provide the UAMI [minimum reqd permissions](https://docs.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity#permissions) one-time, and manage the lifecycle of the UAMI outside the MI lifecycle (allowing for synchronous onboarding to Azure AD rather than waiting for SAMI onboarding).

I believe this should be a fairly trivial change since the Go SDK already supports it:
* See `*ResourceIdentity`: 
  * https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v55.5.0+incompatible/services/preview/sql/mgmt/v5.0/sql#ManagedInstance
  * https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v55.5.0+incompatible/services/preview/sql/mgmt/v5.0/sql#ResourceIdentity
 
Change in TF module would be needed here to support UAMI: https://github.com/hashicorp/terraform-provider-azurerm/blob/01f7155cb668bcee1434cb63708ace2bbb1fde05/internal/services/sql/sql_managed_instance_resource.go#L229

### New or Affected Resource(s)

* `azurerm_sql_managed_instance`

**Comment by mdrakiburrahman** [comment]
@aristosvo - you're right, thanks for the thoughtful response. I'm going to get this on the Go SDK team's radar - please keep this issue open.

By the way, could you point me to any docs on how I can get a PR properly merged here (by going through your TF test cycles etc.).

**Comment by mdrakiburrahman** [comment]
Reference: https://github.com/Azure/azure-sdk-for-go/issues/16998

**Comment by bulentozkir** [comment]
Is there any ETA for this registry feature?
