### ISSUE TITLE
what's a "new beat resource"?

### ISSUE THREAD

**Issue by dimbleby** [hashicorp/terraform-provider-azurerm#15273]
The changelog is full of "new beat resource".  Is this a typo for beta?

**Comment by tombuildsstuff** [comment]
hi @dimbleby 

Thanks for letting us know, this was indeed a typo which I've fixed in https://github.com/hashicorp/terraform-provider-azurerm/commit/d98893dc1b7a9d0be432e7125779ef2e252d0d66

Thanks!
