### ISSUE TITLE
required dependency versions incompatible

### ISSUE THREAD

**Issue by SnowmanCharles** [hashicorp/terraform-provider-azurerm#15275]
I'm trying to configure the latest terraform-provider-azurerm package. It is suggested in https://github.com/hashicorp/terraform-provider-azurerm/blob/main/go.mod the following versions of dependencies are required

github.com/hashicorp/go-azure-helpers v0.22.0
github.com/tombuildsstuff/giovanni v0.17.0

However, these two packages are incompatible at those versions. At lease the following lines:
https://github.com/tombuildsstuff/giovanni/blob/v0.17.0/testhelpers/client.go#L156
https://github.com/hashicorp/go-azure-helpers/blob/v0.22.0/authentication/config.go#L147-L155

the go-azure-helpers packages removed the GetAuthorizationToken() function but introduced GetADALToken() and GetMSALToken(). 

I'm curious, what's the correct version combination to use?

**Comment by tombuildsstuff** [comment]
hi @SnowmanCharles 

So that we can answer this correctly, would it be possible to explain what you're trying to do here? The repository itself contains all of the necessary dependencies so in most cases you should only need to [follow the instructions here](https://github.com/hashicorp/terraform-provider-azurerm#developing-the-provider) to build the provider from source, although we'd recommend pulling this from the Terraform Registry instead.

Thanks!

**Comment by SnowmanCharles** [comment]
Hi Tom,

Are you saying that this [instruction](https://github.com/hashicorp/terraform-provider-azurerm#developing-the-provider) will already automatically the dependencies down and build them?

I'm trying to pull this repo and all it's dependencies down to my code base and build them. Thus, I need to figure out a feasible version combination. I followed the versions in the go.mod file in this repo, and it looks like infeasible.

**Comment by tombuildsstuff** [comment]
hi @SnowmanCharles 

With regards to building the Provider locally, the instructions linked above describe how to build the source-code for this provider, as the dependencies are contained within the project - as such `make build` should be sufficient here.

However we don't support vendoring this Provider in other codebases - and as such unfortunately we're unable to assist in that regard, and so I'm going to close this issue for the moment.

Thanks!
