### ISSUE TITLE
`azurerm_backup_policy_file_share.tags` still has changes after apply

### ISSUE THREAD

**Issue by heiazuo** [hashicorp/terraform-provider-azurerm#15283]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v1.1.2 on windows_amd64`
* `azurerm v2.90.0`

### Affected Resource(s)

* `azurerm_backup_policy_file_share.tags`

### Terraform Configuration Files

```hcl

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-backup-20220207"
  location = "West Europe"
}

resource "azurerm_recovery_services_vault" "test" {
  name                = "acctest-20220207"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"

  soft_delete_enabled = false
}

resource "azurerm_backup_policy_file_share" "test" {
  name                = "acctest-20220207"
  resource_group_name = azurerm_resource_group.test.name
  recovery_vault_name = azurerm_recovery_services_vault.test.name

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }

  retention_weekly {
    count    = 7
    weekdays = ["Sunday", "Wednesday"]
  }

  retention_monthly {
    count    = 7
    weekdays = ["Sunday", "Wednesday"]
    weeks    = ["First", "Last"]
  }

  retention_yearly {
    count    = 7
    weekdays = ["Sunday", "Wednesday"]
    weeks    = ["First", "Last"]
    months   = ["January", "July"]
  }
    tags = {
    ENV = "Test"
  }
}
```

### Debug Output
![image](https://user-images.githubusercontent.com/46072066/152739592-493cbdf1-31a5-4132-a506-465cd4f177cf.png)

### Expected Behaviour
do plan after apply dones have no changes

### Actual Behaviour
do plan after apply done still have changes

### Steps to Reproduce

1.`terraform init`
2.`terraform plan`
3.`terraform apply`
4.`terraform paln`

### References

* #0000

**Comment by myc2h6o** [comment]
Tag is not supported for this resource per below document
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/tag-support#microsoftrecoveryservices
