### ISSUE TITLE
`azurerm_stream_analytics_cluster.tags` still has changes after apply

### ISSUE THREAD

**Issue by heiazuo** [hashicorp/terraform-provider-azurerm#15282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v1.1.2 on windows_amd64`
* `azurerm v2.90.0`

### Affected Resource(s)

* `azurerm_stream_analytics_cluster.tags`

### Terraform Configuration Files

```hcl

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-20220207"
  location = "West Europe"
}


resource "azurerm_stream_analytics_cluster" "test" {
  name                = "acctestcluster-32322323"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  streaming_capacity  = 36

  tags = {
    ENV = "Test"
  }
}
```

### Debug Output
![image](https://user-images.githubusercontent.com/46072066/152732344-aae0d161-745e-4762-8ac0-786e1662f41f.png)

### Expected Behaviour

do plan after apply dones have no changes

### Actual Behaviour

do plan after apply done still have changes

### Steps to Reproduce

1.`terraform init`
2.`terraform plan`
3.`terraform apply`
4.`terraform paln`

### References

* #0000

**Comment by myc2h6o** [comment]
Hi @heiazuo looks like there is a bug in the provider which doesn't assign value to `tags`, I've made a pr to fix it

**Comment by myc2h6o** [comment]
@stephybun sorry I didn't realize you self-assigned this issue before making the change. Since it's a small fix, would you mind taking a look?
