### ISSUE TITLE
Unclear which Virtual Machine Scale Set (VMSS) resource to use depending on desired orchestration mode

### ISSUE THREAD

**Issue by mlcooper** [hashicorp/terraform-provider-azurerm#15298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
```

### Affected Resource(s)

* `azurerm_orchestrated_virtual_machine_scale_set`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_windows_virtual_machine_scale_set`

### Expected Behaviour

Per this [article](https://docs.microsoft.com/en-us/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-orchestration-modes) from Microsoft, there are two orchestration modes for Virtual Machine Scale Sets; `uniform orchestration` and `flexible orchestration`. It is not readily clear which Terraform `scale_set` resources creates a scale set in `uniform orchestration` or `flexible orchestration` mode.

Additionally, in `azurerm_orchestrated_virtual_machine_scale_set`, it incorrectly states this:
![image](https://user-images.githubusercontent.com/9505606/152812197-5b308481-fe50-477a-b908-0b833d724108.png)

The Public Preview is now over and both of these orchestration modes are Generally Available.

### Actual Behaviour

The documentation for the three `scale_set` resources mentioned above will clearly state which orchestration mode they create.

### References

* #0000

**Comment by WodansSon** [comment]
@mlcooper Thank you for opening this issue, and I totally agree with you... it is very confusing. Up until **v2.86.0** of the provider, all three of these resources would create both *uniform* and *flex* versions of the VMSS depending on how you defined your VMSS. Which type was created was determined by the Azure RP based on a series of check it would perform during the initial creation of the resource. In **v2.86.0** this has changed as follows:

* azurerm_orchestrated_virtual_machine_scale_set - **Flexible orchestration mode only**
* azurerm_linux_virtual_machine_scale_set - **Uniform orchestration mode only**
* azurerm_windows_virtual_machine_scale_set - **Uniform orchestration mode only**

To clear up the confusion I will add a note to the top of the documentation for each of these resources clearly stating what orchestration mode the VMSS will be created as. 🚀
