### ISSUE TITLE
azurerm plugin crash on azurerm_orchestrated_virtual_machine_scale_set

### ISSUE THREAD

**Issue by mlcooper** [hashicorp/terraform-provider-azurerm#15299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
```

### Affected Resource(s)

* `azurerm_orchestrated_virtual_machine_scale_set`

### Terraform Configuration Files

```hcl
resource "azurerm_orchestrated_virtual_machine_scale_set" "dns_forwarding" {
  name                        = var.vmss_name
  resource_group_name         = azurerm_resource_group.dns_forwarding.name
  location                    = var.vnet_location
  platform_fault_domain_count = 2
  sku_name                    = var.vm_sku
  instances                   = var.quantity_of_instances
  source_image_id             = data.azurerm_shared_image_version.dmi_from_gallery.id

  network_interface {
    name                          = local.nic_name
    enable_accelerated_networking = true
    primary                       = true

    ip_configuration {
      name                                   = local.ip_config_name
      load_balancer_backend_address_pool_ids = [azurerm_lb_backend_address_pool.dns_forwarding.id]
      subnet_id                              = var.vmss_subnet_id
      primary                                = true
      application_security_group_ids         = [azurerm_application_security_group.dns_forwarding.id]
    }
  }

  dynamic "source_image_reference" {
    for_each = var.custom_source_image == true ? [1] : []
    content {
      publisher = var.vmss_image_publisher
      offer     = var.vmss_image_offer
      sku       = var.vmss_image_sku
      version   = var.vmss_image_version
    }
  }

  os_disk {
    caching              = var.os_disk_caching
    storage_account_type = var.os_disk_storage_account_type
    disk_size_gb         = var.os_disk_size_gb
  }

  os_profile {
    linux_configuration {
      admin_username                  = var.admin_username
      admin_password                  = var.public_key != null ? null : var.admin_password
      disable_password_authentication = var.admin_password != null ? false : true

      dynamic "admin_ssh_key" {
        for_each = var.public_key != null ? [1] : []
        content {
          public_key = var.public_key
          username   = var.public_key_username
        }
      }
    }

    custom_data = base64encode(templatefile(
      "${path.module}/templates/cloud-init.tmpl",
      {
        vnet_cidr_block = var.vnet_cidr,
        dns_zones       = var.dns_zones,
        querylog        = var.querylog
      }
      )
    )
  }

  automatic_instance_repair {
    enabled      = var.automatic_instance_repair
    grace_period = var.grace_period_instance_repair
  }

  depends_on = [azurerm_lb_rule.dns_forwarding_tcp, azurerm_lb_rule.dns_forwarding_udp]

  tags = local.tags
}

```
### Panic Output

Please see crash output [here](https://gist.github.com/mlcooper/41e93ba3c4d1b4e6f590e01ec87ac4fa).

### Expected Behaviour
The azurerm plugin would not have crashed and it would have successfully applied the `azurerm_orchestrated_virtual_machine_scale_set` resource

### Actual Behaviour

plugin [crash](https://gist.github.com/mlcooper/41e93ba3c4d1b4e6f590e01ec87ac4fa)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by WodansSon** [comment]
@mlcooper thank you for opening this issue, you are hitting this because the code (for a Linux `os_profile`) is not checking if the `ComputerNamePrefix` field is `nil` or not before attempting to access that fields value. I will add a check for that and that will fix this bug. If you don't want to wait for the bug fix to unblock you, just add a value for the  `computer_name_prefix` field in your `os_profile` and you should be good to go. Thanks again! 🚀
