### ISSUE TITLE
error "unexpected state 'UpgradingRedisServerVersion', wanted target 'Succeeded'", when upgrading azurerm_redis_cache from redis_version 4 to 6

### ISSUE THREAD

**Issue by Dmitrii034** [hashicorp/terraform-provider-azurerm#15295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform fails when upgrading Redis 4 cache to Redis 6 due to unexpected state. On Azure side resource is upgraded.

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4
on linux_amd64
azurerm 2.94.0

### Affected Resource(s)

`azurerm_redis_cache`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~>1.1.4"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.94.0"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  use_msi         = tobool(lower(var.useMSI))
  subscription_id = var.subscriptionId
  tenant_id       = var.tenantId
  features {}
}

resource "azurerm_redis_cache" "example" {
  name                = var.name
  location            = "West Europe"
  resource_group_name = var.resourceGroup
  capacity            = 1
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  redis_version       = var.redisVersion

  public_network_access_enabled = false

  redis_configuration {
  }
}
```

### Debug Output

[Gist](https://gist.github.com/Dmitrii034/365e5faa2f25c71d30380359a0cc7134)

### Expected Behaviour

Terraform successfully upgrades Redis 4 cache to Redis 6.

### Actual Behaviour

Terraform fails with an error:
```hcl
azurerm_redis_cache.example: Modifying... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aaaaaaa/providers/Microsoft.Cache/Redis/da-da-da]

Error: waiting for Redis Cache "da-da-da" (Resource Group "aaaaaaa") to become available: unexpected state 'UpgradingRedisServerVersion', wanted target 'Succeeded'. last error: %!s(<nil>)

  with azurerm_redis_cache.example,
  on main.tf line 19, in resource "azurerm_redis_cache" "example":
  19: resource "azurerm_redis_cache" "example" {
```

### Steps to Reproduce

1. Set "redis_version" argument to "4"
2. `terraform apply`
3. Set "redis_version" argument to "6"
4. `terraform apply`
### Important Factoids

The result of second 'terraform apply' seems to be inconsistent. Half the time terraform mistakenly succeeds too fast, as described in #15294.

### References

* #15294

**Comment by xuzhang3** [comment]
Version upgrade state `UpgradingRedisServerVersion` is not handled, this should be the pending state until succeed.
