### ISSUE TITLE
Terraform mistakenly reports modification as complete when upgrading azurerm_redis_cache from redis_version 4 to 6

### ISSUE THREAD

**Issue by Dmitrii034** [hashicorp/terraform-provider-azurerm#15294]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform reports that resource modification is done after ~5s when upgrading Redis 4 cache to Redis 6, while in reality, resource is still being upgraded for ~10min.

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4
on linux_amd64
azurerm 2.94.0

### Affected Resource(s)

`azurerm_redis_cache`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~>1.1.4"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.94.0"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  use_msi         = tobool(lower(var.useMSI))
  subscription_id = var.subscriptionId
  tenant_id       = var.tenantId
  features {}
}

resource "azurerm_redis_cache" "example" {
  name                = var.name
  location            = "West Europe"
  resource_group_name = var.resourceGroup
  capacity            = 1
  family              = "C"
  sku_name            = "Standard"
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"

  redis_version       = var.redisVersion

  public_network_access_enabled = false

  redis_configuration {
  }
}
```

### Debug Output

[Gist](https://gist.github.com/Dmitrii034/fb8315253588b2ef9e0baac013a46ce4)

### Expected Behaviour

Terraform tracks resource provisioningState until it becomes "Succeeded".

### Actual Behaviour

Terraform reports modification as complete while resource provisioningState is still "UpgradingRedisServerVersion".
```hcl
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_redis_cache.example will be updated in-place
  ~ resource "azurerm_redis_cache" "example" {
        id                            = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aaaaaaa/providers/Microsoft.Cache/Redis/da-da-da"
        name                          = "da-da-da"
      ~ redis_version                 = "4.1.14" -> "6"
      ~ tags                          = { }

        # (19 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_redis_cache.example: Modifying... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aaaaaaa/providers/Microsoft.Cache/Redis/da-da-da]
azurerm_redis_cache.example: Modifications complete after 5s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/aaaaaaa/providers/Microsoft.Cache/Redis/da-da-da]
Releasing state lock. This may take a few moments...

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

Activity log after resource provisioningState becomes "Succeeded":
![Screenshot 2022-02-07 122943](https://user-images.githubusercontent.com/81961527/152761937-ef8e906a-b529-41a6-9eaf-564c27eda32c.png)

### Steps to Reproduce

1. Set "redis_version" argument to "4"
2. `terraform apply`
3. Set "redis_version" argument to "6"
4. `terraform apply`

### Important Factoids
The result of second 'terraform apply' seems to be inconsistent. Half the time terraform fails with "Unexpected state" error as described in #15295.

### References
*#15295

**Comment by xuzhang3** [comment]
dup with #15295

**Comment by Dmitrii034** [comment]
> dup with #15295

I am not sure if this can be considered a dupe. I created this issue because the cause of the problem is different from #15295. If you look at the debug log, you can see that after terraform had started checking for the `provisioningState` it immediately got `Succeeded` and decided that the modification had been completed, even though the version was still `4.1.14` and the resource obviously hadn't finished upgrading.

**Comment by xuzhang3** [comment]
@Dmitrii034  #15372 will fix this bug
