### ISSUE TITLE
"Error: ID was missing the `notificationHubs` element" when azurerm_notification_hub resource changes

### ISSUE THREAD

**Issue by blanser-cc** [hashicorp/terraform-provider-azurerm#15302]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
AzureRM v2.35.0
### Affected Resource(s)

* `azurerm_notification_hub`

### Terraform Configuration Files

```hcl
resource "azurerm_notification_hub" "hub_test" {
  name                = "test-${var.env_name}"
  namespace_name      = azurerm_notification_hub_namespace.hub_namespace_test.name
  resource_group_name = azurerm_resource_group.notification_service.name
  location            = azurerm_resource_group.notification_service.location
  gcm_credential {
    api_key = azurerm_key_vault_secret.gcm_api_key_test.value
  }
}
```

### Expected Behaviour

After the resource has been created, on subsequent runs of `terraform apply` changes to the resource should be applied without error.

### Actual Behaviour

While it is possible to create the resource, when the value of azurerm_key_vault_secret.gcm_api_key_test is changed afterwards, running `terraform apply` again fails with the error `Error: ID was missing the `notificationHubs` element`.

### Steps to Reproduce

1. `terraform apply`
2. change value of `azurerm_key_vault_secret.gcm_api_key_test`
3. `terraform apply`

**Comment by neil-yechenwei** [comment]
@blanser-cc , thanks for raising this issue. After tested with below tf config, seems I can't repro this issue. Could you try below tf config with latest azurerm provider to see if the issue still exists? Thanks.

tf config:
```
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "acctestRGpol-test01"
  location = "West Europe"
}

resource "azurerm_key_vault" "test" {
  name                       = "acctestkvnh-test01"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "standard"
  soft_delete_retention_days = 7

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Get",
    ]

    secret_permissions = [
      "Get",
      "Delete",
      "List",
      "Purge",
      "Recover",
      "Set",
    ]
  }

  tags = {
    environment = "Test"
  }
}

resource "azurerm_key_vault_secret" "test" {
  name         = "acctestsecret-test01"
#   value        = "<api key 1>" // Set it at first apply
  value        = "<api key 2>" // Change it at second apply
  key_vault_id = azurerm_key_vault.test.id
}

resource "azurerm_notification_hub_namespace" "test" {
  name                = "acctestnhn-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  namespace_type      = "NotificationHub"
  sku_name            = "Free"
}

resource "azurerm_notification_hub" "test" {
  name                = "acctestnh-test01"
  namespace_name      = azurerm_notification_hub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  gcm_credential {
    api_key = azurerm_key_vault_secret.test.value
  }

  tags = {
    env = "Test2"
  }
}
```

**Comment by blanser-cc** [comment]
This problem could indeed be solved by updating azurerm to the most recent version (2.95.0). Sorry I did not try that out before raising an issue!
