### ISSUE TITLE
During Destroy azurerm_key_vault_access_policy removed before dependencies

### ISSUE THREAD

**Issue by tcpipuk** [hashicorp/terraform-provider-azurerm#15304]
When carrying out a `terraform destroy` on my project, I can see the following:

```
azurerm_key_vault_access_policy.mgmt: Destroying... [xxxxx]
<...>
azurerm_key_vault_certificate.mgmt: Destroying... [xxxxx]
<...>
│ Error: deleting Certificate "xxxxx" (Key Vault "xxxxx"): keyvault.BaseClient#DeleteCertificate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=xxxxx;oid=xxxxx;iss=xxxxx' does not have certificates delete permission on key vault 'xxxxx'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
```

The Service Principal is granted access to act on certificates during the Key Vault creation, but during the destruction phase it removes its own ability to delete them.

I am going to override this in my own project using `depends_on` but couldn't see another issue raised for this behaviour, so raised to avoid other people hitting the same problem!

**Comment by mybayern1974** [comment]
@tcpipuk , thank you for opening this issue. Could you please provide your .tf config to help repro/troubleshooting?

**Comment by KCAndersen** [comment]
Same symptom, example tf below. Observing the Azure state versus Terraform state, Terraform seems to believe it's a 403 issue, but the keyvault in question was gone. My assumption was that the keyvault was deleted but the individual secrets were not categorized as deleted, so it's continuing to attempt to delete the child entities that no longer exist. Similarly, my tfstate file shows the keyvault is still present as well, despite it being gone in Azure.

Relevant variables.tf:
variable "key_vault" {
  type = object({
    sku                        = string
    soft_delete_retention_days = number
  })
  default = {
    sku                        = "standard"
    soft_delete_retention_days = 7
  }
}

Relevant main.tf:

resource "azurerm_key_vault" "teleHostedPages" {
  name                        = "${var.default_name}-kv"
  location                    = module.appservice-shared.location
  resource_group_name         = module.appservice-shared.resource_group
  enabled_for_disk_encryption = true
  tenant_id                   = data.azuread_client_config.current.tenant_id
  soft_delete_retention_days  = var.key_vault.soft_delete_retention_days
  purge_protection_enabled    = false
  sku_name                    = var.key_vault.sku
}

resource "azurerm_key_vault_access_policy" "user" {
  key_vault_id = azurerm_key_vault.teleHostedPages.id
  tenant_id    = data.azuread_client_config.current.tenant_id
  object_id    = data.azuread_client_config.current.object_id

  key_permissions = [
    "Get",
  ]

  secret_permissions = [
    "Get", "Set", "Delete", "List"
  ]
}

resource "azurerm_key_vault_access_policy" "app" {
  key_vault_id = azurerm_key_vault.teleHostedPages.id
  tenant_id    = data.azuread_client_config.current.tenant_id
  object_id    = module.appservice-shared.managed_id

  key_permissions = [
    "Get",
  ]

  secret_permissions = [
    "Get", "List"
  ]
}

resource "azurerm_key_vault_secret" "teleHostedPagesClientSecret" {
  name         = "teleHostedPagesClientSecret"
  value        = azuread_application_password.secret.value
  key_vault_id = azurerm_key_vault.teleHostedPages.id
}

**Comment by byteknacker** [comment]
I have a related problem. After a manual deletion of all the resources on Azure, the key vault access policies seem to be retained. When I applied terraform again, it says that the key vault access policies already exists and errors out. Maybe when I manually deleting all resources, Azure just does not delete the associated Access Policies even though the Key Vault itself is deleted.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
