### ISSUE TITLE
"Provider produced inconsistent result after apply" creating azurerm_traffic_manager_profile resources

### ISSUE THREAD

**Issue by graemerobertson** [hashicorp/terraform-provider-azurerm#15300]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.92.0
```

Also seen with Terraform v1.1.3, azurerm v2.86.0

### Affected Resource(s)

* `azurerm_traffic_manager_profile`

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.74"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_traffic_manager_profile" "gdr-test" {
  count                  = 8
  name                   = "gdr-test-${count.index}"
  resource_group_name    = "gdr-test-rg"
  traffic_routing_method = "Weighted"

  dns_config {
    relative_name = "gdrtest12345${count.index}"
    ttl           = 60
  }

  monitor_config {
    protocol                     = "http"
    port                         = 80
    path                         = "/"
    interval_in_seconds          = 30
    timeout_in_seconds           = 10
    tolerated_number_of_failures = 3
  }

  tags = {
    Owner="Penguin"
    Region="Deployment"
  }
}
```

### Debug Output

https://gist.github.com/graemerobertson/8e2cbdb2218886eaed1353d3b000578c

### Panic Output

N/A

### Expected Behaviour

`terraform apply` should always succeed

### Actual Behaviour

`terraform apply` sometimes fails like so:

```
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_traffic_manager_profile.gdr-test[4], provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource
│ was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Steps to Reproduce

1. Run `terraform apply` on the Terraform file supplied above

### Important Factoids

With the Terraform file supplied above this issue appears to be reproducible, but very rare. However, on the far more complex Terraform project that I originally hit this issue, it seems far more common.

### References

* #0000

**Comment by graemerobertson** [comment]
The Azure traffic manager profile appears to be created successfully

**Comment by magodo** [comment]
@graemerobertson From the description above, it seems to be an intermittent issue of Azure, that right after the creation succeeded, a `GET` on the traffic manager profile just created returned a 404, which results into Terraform resetting the resource in the state. Therefore you see the *Provider produced inconsistent result after apply* error above. This kind of problem might be due to eventual consistency of ARM.

**Comment by graemerobertson** [comment]
@magodo  thanks for the feedback, in that case I will also try and raise with Azure next time I see this issue
