### ISSUE TITLE
Support for managed identity retrieval with data azurerm_disk_encryption_set

### ISSUE THREAD

**Issue by piotrgwiazda** [hashicorp/terraform-provider-azurerm#15319]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please provide managed identity principal id and other information from `data "azurerm_disk_encryption_set"` as available via `az disk-encryption-set show`

### New or Affected Resource(s)

azurerm_disk_encryption_set data source

### Potential Terraform Configuration

N/A

### References

https://docs.microsoft.com/en-us/cli/azure/disk-encryption-set?view=azure-cli-latest#az-disk-encryption-set-show

**Comment by modbase** [comment]
Eventhough it is not mentioned in the documentation of the data resource, I was still able to fetch the principal ID of the managed identity using `identity[0].principal_id`. Example:

```
resource "azurerm_disk_encryption_set" "example" {
  name                      = "test"
  resource_group_name       = "test"
  location                  = var.location
  key_vault_key_id          = azurerm_key_vault_key.example.id

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_key_vault_access_policy" "example" {
  key_vault_id    = azurerm_key_vault.example.id
  tenant_id       = azurerm_disk_encryption_set.example.identity[0].tenant_id
  object_id       = azurerm_disk_encryption_set.example.identity[0].principal_id
  key_permissions = ["Get", "WrapKey", "UnwrapKey"]
}
```
