### ISSUE TITLE
Not able to deploy azurerm_vpn_site

### ISSUE THREAD

**Issue by awterra** [hashicorp/terraform-provider-azurerm#15324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
```

### Affected Resource(s)

* `azurerm_vpn_site`

### Terraform Configuration Files

Same as the example in the terraform registry.
```hcl

provider "azurerm" {
  features {}
}


resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "West Europe"
}

resource "azurerm_virtual_wan" "example" {
  name                = "example-vwan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}

resource "azurerm_vpn_site" "example" {
  name                = "site1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  virtual_wan_id      = azurerm_virtual_wan.example.id

  link {
    name       = "link1"
    ip_address = "10.0.0.1"
  }
}

```

### Expected Behaviour

```terraform-apply``` should run without errors

### Actual Behaviour

````
 Error: creating  "site1" (Resource Group "example-rg"): network.VpnSitesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VpnSiteAddressPrefixesAndVpnSiteLinkBgpSettingsCannotBeNull" Message="VpnSiteLinks can not have empty bgpSetting as vpnSite /subscriptions/ad19b602-438c-4e09-90a3-8b7a269ff7d9/resourceGroups/example-rg/providers/Microsoft.Network/vpnSites/site1 contains empty address prefixes." Details=[]
│ 
│   with azurerm_vpn_site.example,
│   on main.tf line 18, in resource "azurerm_vpn_site" "example":
│   18: resource "azurerm_vpn_site" "example" {
````

### Steps to Reproduce

1. `terraform apply`

### Additional Info
Our Module that includes the ```azurerm_vpn_site```failed during this weeks pipeline run so we tested it with the example code from the registry under different terraform Versions and different AzureRm versions. Same Issue. 
Is this possibly another Issue with the Azure SDK like in the following issue?
https://github.com/hashicorp/terraform-provider-azurerm/issues/14966

**Comment by neil-yechenwei** [comment]
@awterra , thanks for raising this issue. I assume one of `address_cidrs` and `link.bgp` has to be set. I will update example in doc.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-vpnsite-test01"
  location = "West Europe"
}

resource "azurerm_virtual_wan" "test" {
  name                = "acctest-vwan-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_vpn_site" "test" {
  name                = "acctestvpnsite01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  virtual_wan_id      = azurerm_virtual_wan.test.id
  address_cidrs       = ["10.0.0.0/24"]

  link {
    name       = "link1"
    ip_address = "10.0.0.1"
  }
}
```
