### ISSUE TITLE
Add optional subscription_id in data sources.

### ISSUE THREAD

**Issue by hsalluri259** [hashicorp/terraform-provider-azurerm#15351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have the following use case. I need to read Azure Log Analytics workspace keys and create a kubernetes secret. My problem here is, I have like 100 log analytics workspaces with all of them in different subscriptions. I have access to read log analytics keys only.

### New or Affected Resource(s)

* provider registry.terraform.io/hashicorp/azurerm v2.84.0

### Potential Terraform Configuration

```data "azurerm_log_analytics_workspace" "ala_keys" {
  subscription_id = "00000-000-000"
  name = "amap-intcusa-hdmaps-laworkspace"
  resource_group_name = "amap-intcusa-hdmaps-laworkspace-rg"
}
```
### Attempted solutions
```
provider "azurerm" {
  features {}
  alias = "cpe"
  subscription_id = "0000-0000-0000"
}
data "azurerm_log_analytics_workspace" "ala_keys" {
  provider = azurerm.cpe
  name = "cpe-laworkspace"
  resource_group_name = "cpe-laworkspace-rg"
}

Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '9ca0af5b-3c67-4757-96ed-6bd941483a00' with object id '9ca0af5b-3c67-4757-96ed-6bd941483a00' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/04898e0e-c649-47de-bd3e-a747870a60ac' or the scope is invalid. If access was recently granted, please refresh your credentials."
│
│   with module.provision_ala_logging.provider["registry.terraform.io/hashicorp/azurerm"].devcom,
│   on ala_logging/main.tf line 42, in provider "azurerm":
│   42: provider "azurerm" {
```
This error is expected because I don't have read access over /subscriptions/04898e0e-c649-47de-bd3e-a747870a60ac. I only have read access on log analytics workspace resource created inside the subscription.
### References

* #0000

**Comment by magodo** [comment]
@hsalluri259 The API that failed due to lack of permission is the 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/04898e0e-c649-47de-bd3e-a747870a60ac', which is not related to the data source, but is made by the provider. That operation is to ensure you have registered all RPs (resource providers) that are used by the Terraform provider. Normally, they are registered. So you can skip this step by exporting following two environment variables before you run `terraform`:

- export ARM_PROVIDER_ENHANCED_VALIDATION=false
- export ARM_SKIP_PROVIDER_REGISTRATION=true

Since the data source itself didn't do a list, only a `GET` against the target resource, which you should have access to. I'm gonna close this issue for now. Feel free to reopen it if you still have issues.

**Comment by hsalluri259** [comment]
Th

> @hsalluri259 The API that failed due to lack of permission is the 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/04898e0e-c649-47de-bd3e-a747870a60ac', which is not related to the data source, but is made by the provider. That operation is to ensure you have registered all RPs (resource providers) that are used by the Terraform provider. Normally, they are registered. So you can skip this step by exporting following two environment variables before you run `terraform`:
> 
>     * export ARM_PROVIDER_ENHANCED_VALIDATION=false
> 
>     * export ARM_SKIP_PROVIDER_REGISTRATION=true
> 
> 
> Since the data source itself didn't do a list, only a `GET` against the target resource, which you should have access to. I'm gonna close this issue for now. Feel free to reopen it if you still have issues.

Thank you, it worked. But my use case is different. I want to read 100 ALA workspaces dynamically. I can't write provider for each one of them. So I am okay  if I can  do a for_each  at provider level or pass subscription_id as an argument to azurerm_log_analytics_workspace data source.

**Comment by hsalluri259** [comment]
Can you please reopen the issue. My use case is different.

Regards,
Harish Salluri,
+1 4259843720

**Comment by magodo** [comment]
@hsalluri259 All the resources in the AzureRM provider is designed to work for one subscription only. As you already know you can work on multiple subscriptions with multiple provider aliases. It turns out that terraform currently doesn't support `for_each` at the provider block:

```
Error: Reserved argument name in provider block

  on main.tf line 5, in provider "azurerm":
   5:   for_each = var.aliases

The provider argument name "for_each" is reserved for use by Terraform in a future version.
```

You can submit a feature request to the hashicorp/terraform repo.

**Comment by hsalluri259** [comment]
Earlier I submitted a feature request then they told me to submit an issue here.

**Comment by tombuildsstuff** [comment]
@hsalluri259 unfortunately this isn't something we'll be adding to each Data Source/Resource in the Azure Provider - instead [there's a feature request for this on Terraform Core that you can subscribe to which'll add `for_each` to the Provider block](https://github.com/hashicorp/terraform/issues/19932), which'll enable supporting this scenario.
