### ISSUE TITLE
Inconsistent state for `azurerm_public_ip` resource after creation

### ISSUE THREAD

**Issue by krowlandson** [hashicorp/terraform-provider-azurerm#15388]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0
```

### Affected Resource(s)

* `azurerm_public_ip`

### Terraform Configuration Files

This is being observed as part of a test deployment located within the `caf-enterprise-scale` module, but can be reproduced outside the module.

See the following lines of code where we configure a deployment of the module where we observe this issue:
https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/blob/89d31d4dddeb5d4bd5c9f948871111b66c9e3aeb/tests/modules/test_003_add_mgmt_conn/main.tf#L117-L146

### Expected Behaviour

When creating an `azurerm_public_ip` resource using Terraform, the correct state should be stored upon resource creation.

### Actual Behaviour

When running `terraform plan` or `terraform apply` after initial creation of an `azurerm_public_ip` resource, Terraform reports that `Objects have changed outside of Terraform`:

```shell
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.test_connectivity.azurerm_public_ip.connectivity["/subscriptions/<redacted>/resourceGroups/12345-connectivity-northeurope/providers/Microsoft.Network/publicIPAddresses/12345-fw-northeurope-pip"] has changed
  ~ resource "azurerm_public_ip" "connectivity" {
        id                      = "/subscriptions/<redacted>/resourceGroups/12345-connectivity-northeurope/providers/Microsoft.Network/publicIPAddresses/12345-fw-northeurope-pip"
      + ip_tags                 = {}
        name                    = "12345-fw-northeurope-pip"
        tags                    = {}
        # (10 unchanged attributes hidden)
    }

```

As can be seen from the above, the following attributes appear to be affected:

* `ip_tags`

### Steps to Reproduce

1. Download a copy of the caf-enterprise-scale module from this pre-release branch: https://github.com/krowlandson/terraform-azurerm-caf-enterprise-scale/tree/refactor-tests
2. Change directory to the `./tests/modules/test_003_add_mgmt_conn` sub folder
3. Optionally update to the latest provider version in `terraform.tf`
4. Run `terraform init`
5. Run `terraform apply` and confirm deployment
6. Upon completion of deployment, run `terraform apply` a second time and observe the changes

### References

_none found_

**Comment by tombuildsstuff** [comment]
I believe I've fixed this in a local branch whilst passing through fwiw, will confirm next week.
