### ISSUE TITLE
azurerm_backup_protected_file_share - Azure Gov SubscriptionNotFound

### ISSUE THREAD

**Issue by bsuchorowski** [hashicorp/terraform-provider-azurerm#15408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/azuread v2.15.0
+ provider registry.terraform.io/hashicorp/azurerm v2.90.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0

### Affected Resource(s)

azurerm_backup_protected_file_share

### Terraform Configuration Files

resource "azurerm_backup_protected_file_share" "backup_protected_configs" {
  resource_group_name       = var.resource_group.name
  recovery_vault_name       = azurerm_recovery_services_vault.vault.name
  source_storage_account_id = azurerm_backup_container_storage_account.protection-container.storage_account_id
  source_file_share_name    = "fs-configs"
  backup_policy_id          = azurerm_backup_policy_file_share.policy.id
}

### Debug Output

2022-02-14T14:00:34.318+0100 [DEBUG] provider.terraform-provider-azurerm_v2.90.0_x5: AzureRM Response for https://management.azure.com/Subscriptions/X-Y-Z-X-Y/resourceGroups/rg-name/providers/Microsoft.RecoveryServices/vaults/vault-name/backupFabrics/Azure/protectionContainers/StorageContainer%3Bstorage%3Brrg-name%3Bsaname/operationResults/c3a1a815-2a96-4b88-a923-6fa535544ade?api-version=2016-12-01: 
HTTP/2.0 404 Not Found

### Expected Behaviour

azurerm_backup_protected_file_share  resoruce created without any issues.

### Steps to Reproduce

1. Azure Gov Subscription
2. azurerm_backup_protected_file_share

### Important Factoids

1. It seems that this request from DEBUG output should be sent to management.usgovcloudapi.net instead of management.azure.com. 
2. The rest of our azurerm resources were created without any issues.

**Comment by tombuildsstuff** [comment]
Fixed in #15316 which shipped in v2.96.0

**Comment by bsuchorowski** [comment]
I checked v2.95 and it did not help. However, I've just noticed v2.96 release and it solved the issue. Case closed.
