### ISSUE TITLE
azurerm_application_gateway - Since 2.96.0 azurerm keeps trying to add identity block

### ISSUE THREAD

**Issue by mjnewborn** [hashicorp/terraform-provider-azurerm#15411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.2
azurerm 2.96.0

### Affected Resource(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "app-gateway" {
  name                = "app-gateway"
  resource_group_name = "rg-app-gateway"
  location            = "uksouth"

  # Base Config

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
  }

  gateway_ip_configuration {
    name      = "application-gateway-gwip"
    subnet_id = module.application-gateway-snet-privateip.subnet-id
  }

  # Managed Identity

  identity {
    type                      = "UserAssigned"
    identity_ids              = [azurerm_user_assigned_identity.appgateway-identity.id]
  }
```

### Expected Behaviour

This Application Gateway already exists and the UserAssigned Identity is connected (and exists in the Azure Portal json). So there should be no changes.

### Actual Behaviour

Terraform states the Identity has been removed and it needs to be added again.
Once added, on the next plan it wants to add the Identity block again

```hcl
Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # azurerm_application_gateway.app-gateway has been changed
  ~ resource "azurerm_application_gateway" "app-gateway" {
        id                                = "/subscriptions/##########/resourceGroups/rg-app-gateway/providers/Microsoft.Network/applicationGateways/app-gateway"
        name                              = "app-gateway"
        tags                              = {}
        # (7 unchanged attributes hidden)

      - identity {
          - identity_ids = [
              - "/subscriptions/xxxxxxxxxxxxxx/resourceGroups/rg-hub-network/providers/Microsoft.ManagedIdentity/userAssignedIdentities/appgateway-identity-westberks",
            ] -> null
          - type         = "UserAssigned" -> null
        }
```
v
v
v
v
```hcl
Terraform will perform the following actions:

  # azurerm_application_gateway.app-gateway will be updated in-place
  ~ resource "azurerm_application_gateway" "app-gateway" {
        id                                = "/subscriptions/xxxxxxxxxxxx/resourceGroups/rg-app-gateway/providers/Microsoft.Network/applicationGateways/app-gateway"
        name                              = "app-gateway"
        tags                              = {}
        # (7 unchanged attributes hidden)

      + identity {
          + identity_ids = [
              + "/subscriptions/xxxxxxxxxxxx/resourceGroups/rg-app-gateway/providers/Microsoft.ManagedIdentity/userAssignedIdentities/app-gateway",
            ]
          + type         = "UserAssigned"
        }

```

This keep repeating

### Steps to Reproduce

Run a plan on an Application Gateway with an Identity Block since azurerm 2.96.0 was released

### Important Factoids

Started since azurerm v2.96.0 - https://github.com/hashicorp/terraform-provider-azurerm/pull/15337 
azurerm v2.95.0 works fine

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/15337

* #0000

**Comment by tombuildsstuff** [comment]
hey @mjnewborn 

Thanks for reporting this - this was a regression introduced in some upcoming work for 3.0, I've opened https://github.com/hashicorp/terraform-provider-azurerm/pull/15412 which'll fix this.

Thanks!

**Comment by Noel-Jones** [comment]
Thanks for quick resolution, hit by this one too.
