### ISSUE TITLE
Support for Azure Database for MySQL Flexible Server parameters whose type is list of strings

### ISSUE THREAD

**Issue by radirobi** [hashicorp/terraform-provider-azurerm#15410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
This issue is related to the `azurerm_mysql_flexible_server_configuration` object which makes possible to configure the server parameters of an Azure Database for MySQL Flexible server. The type of some of the server parameters are list of strings (e.g.: audit_log_events). At the moment these parameters could not be set. 

### New or Affected Resource(s)

* azurerm_mysql_flexible_server_configuration

### Potential Terraform Configuration

```hcl
resource "azurerm_mysql_flexible_server_configuration" "parameters" {
  name                = "audit_log_events"
  resource_group_name = "myrg"
  server_name         = "myserver"
  value               = ["DDL", "DML"] # Gives the error: Inappropriate value for attribute "value": string required.
}
```

### References

* [Source code of the module](https://github.com/hashicorp/terraform-provider-azurerm/blob/87cc5c3a885789db68d860357b612b33acb6fd08/internal/services/mysql/mysql_flexible_server_configuration_resource.go#L52)

**Comment by neil-yechenwei** [comment]
@radirobi , thanks for raising this issue. The API only supports string for the value type of server parameters. Please refer below example.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-mysqlfs-test02"
  location = "West Europe"
}

resource "azurerm_mysql_flexible_server" "test" {
  name                   = "acctest-mysqlfs-test02"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  administrator_login    = "adminTerraform"
  administrator_password = "QAZwsx123"
  sku_name               = "B_Standard_B1s"
}

resource "azurerm_mysql_flexible_server_configuration" "test" {
  name                = "audit_log_events"
  resource_group_name = azurerm_resource_group.test.name
  server_name         = azurerm_mysql_flexible_server.test.name
  value               = "DDL,DML"
}
```

**Comment by radirobi** [comment]
@neil-yechenwei 
Thank you for letting me know. You are absolutely right, with that being said, I am closing this issue.
