### ISSUE TITLE
`azurerm_api_management_api_operation_policy`.`operation_id` validation too restrictive

### ISSUE THREAD

**Issue by knutwannheden** [hashicorp/terraform-provider-azurerm#15417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v2.96.0

### Affected Resource(s)

* `azurerm_api_management_api_operation_policy`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_operation_policy" "openid-configuration" {
  api_name            = var.mobiyaml.tk_id
  api_management_name = var.apim_name
  resource_group_name = var.apim_rg
  operation_id        = "OpenIdRestResource_readOpenIdProviderMetadataOhneStage_get"
  xml_content         = file("resources/one-minute-caching-policy.xml")
}
```

Not listed here is the corresponding `azurerm_api_management_api` resource, which defines the API operation referenced above. That operation is defined inside a `swagger.json` OpenAPI definition and has an Operation ID corresponding to the value above:

```json
{
  "swagger" : "2.0",
  "basePath" : "/bps/openid/rest/",
  "paths" : {
    "/openid/.well-known/openid-configuration" : {
      "get" : {
        "tags" : [ "BPS - OpenID Connect public interfaces" ],
        "summary" : "Liefert die OpenID-Provider-Metadata ohne Stage (deprecated)",
        "description" : "",
        "operationId" : "OpenIdRestResource_readOpenIdProviderMetadataOhneStage_get",
        "produces" : [ "application/json" ],
        "responses" : {
          "200" : {
            "description" : "OpenID Provider Metadata"
          }
        }
      }
    }
  }
}
```

### Expected Behaviour

The `azurerm_api_management_api_operation_policy` as given should get accepted just like the `azurerm_api_management_api` based on the OpenAPI definition is accepted.

### Actual Behaviour

When running `terraform plan` the following error is logged and the operation fails:

```
╷
│ Error: "operation_id" may only contain alphanumeric characters and dashes up to 80 characters in length
│ 
│   with azurerm_api_management_api_operation_policy.openid-configuration,
│   on caching-policy.tf line 6, in resource "azurerm_api_management_api_operation_policy" "openid-configuration":
│    6:   operation_id        = "OpenIdRestResource_readOpenIdProviderMetadataOhneStage_get"
│ 
╵
```

I have read the documentation https://docs.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions#add-new-api-via-openapi-import and seen that the `operationId` value apparently gets normalized, even though this isn't explained in detail. The section https://docs.microsoft.com/en-us/azure/api-management/api-management-api-import-restrictions#export-api-as-openapi however explains what normalization rules get applied when exporting to OpenAPI.

I have tried to export an API which I previously imported from OpenAPI (via Terraform) and can confirm that `operationId` values containing `_` characters are left intact. From this I conclude that Azure API Management supports `_` (underscore) characters and that the validation applied by `azurerm_api_management_api_operation_policy` is too restrictive.

### Steps to Reproduce

1. Create resources as outlined above.
2. `terraform plan`

**Comment by xuzhang3** [comment]
I guess the the validation works for previous API versions, after the API version upgraded,  the validation was not updated with the version upgrade
