### ISSUE TITLE
Updating firewall policy rule collection group fails

### ISSUE THREAD

**Issue by dan-dimitrov** [hashicorp/terraform-provider-azurerm#15440]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v2.96.0

### Affected Resource(s)

azurerm_firewall_policy
azurerm_firewall_policy_rule_collection_group

### Terraform Configuration Files

```
# Firewall policies
resource "azurerm_firewall_policy" "firewallpolicy" {
  name                = "test-firewall-uksouth-policy"
  resource_group_name = var.resource_group
  location            = var.location
}

# Policy rule collection groups
resource "azurerm_firewall_policy_rule_collection_group" "policycollectiongroup" {
  name               = "test-firewall-uksouth-policy-rcg"
  firewall_policy_id = azurerm_firewall_policy.firewallpolicy.id
  priority           = 500
  application_rule_collection {
    name     = "app_rule_collection1"
    priority = 500
    action   = "Deny"
    rule {
      name = "app_rule_collection1_rule1"
      protocols {
        type = "Http"
        port = 80
      }
      protocols {
        type = "Https"
        port = 443
      }
      source_addresses  = ["10.0.0.2"]
      destination_fqdns = ["*.microsoft.com"]
    }
  }

  network_rule_collection {
    name     = "network_rule_collection1"
    priority = 400
    action   = "Deny"
    rule {
      name                  = "network_rule_collection1_rule1"
      protocols             = ["TCP", "UDP"]
      source_addresses      = ["10.0.0.1"]
      destination_addresses = ["192.168.1.1", "192.168.1.2"]
      destination_ports     = ["80", "1000-2000"]
    }
  }

  nat_rule_collection {
    name     = "nat_rule_collection1"
    priority = 300
    action   = "Dnat"
    rule {
      name                = "nat_rule_collection1_rule1"
      protocols           = ["TCP", "UDP"]
      source_addresses    = ["10.0.0.1", "10.0.0.2"]
      destination_address = azurerm_public_ip.firewallpip.ip_address
      destination_ports   = ["80"]
      translated_address  = "192.168.0.1"
      translated_port     = "8080"
    }
  }

  depends_on = [azurerm_firewall_policy.firewallpolicy]
}
```

### Debug Output

2022-02-15T15:22:01.3778543Z [31m│[0m [0m[1m[31mError: [0m[0m[1mcreating Firewall Policy Rule Collection Group "test-firewall-uksouth-policy-rcg" (Resource Group "test-connectivity-uksouth" / Policy: "test-firewall-uksouth-policy"): network.FirewallPolicyRuleCollectionGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyRuleCollectionGroupUpdateNotAllowed" Message="Rule Collection Group test-firewall-uksouth-policy-rcg can not be updated because Parent Firewall Policy test-firewall-uksouth-policy is in Updating state from previous operation ID : 5a0c64f8-0a5d-413e-a2d8-ed373c425506."[0m
2022-02-15T15:22:01.3780559Z [31m│[0m [0m
2022-02-15T15:22:01.3782035Z [31m│[0m [0m[0m  with module.azure-firewall.azurerm_firewall_policy_rule_collection_group.policycollectiongroup,
2022-02-15T15:22:01.3783025Z [31m│[0m [0m  on azure-firewall/main.tf line 48, in resource "azurerm_firewall_policy_rule_collection_group" "policycollectiongroup":
2022-02-15T15:22:01.3784004Z [31m│[0m [0m  48: resource "azurerm_firewall_policy_rule_collection_group" "policycollectiongroup" [4m{[0m[0m
2022-02-15T15:22:01.3784664Z [31m│[0m [0m

### Panic Output

N/A

### Expected Behaviour

When the rules inside a policy rule collection group are updated, these should apply. We cannot seem to achieve this without tearing everything down again and redeploying it.

### Actual Behaviour

When changes are made to the rules in the policy rule collection group the terraform apply fails stating that the policy it is tied in with is stuck in an updating state. This is because the apply triggers the policy into an updating state even when no changes are made to it.

### Steps to Reproduce

1. Deploy an Azure Firewall with a firewall policy with a policy rule collection group.
2. Update a rule in the policy rule collection group and redeploy.

### Important Factoids

N/A

### References

None that I could find.

**Comment by magodo** [comment]
@danailedms I've tested this locally, while failed to reproduce it. Would you please confirm whether this is a systematic issue or intermittent. Also, would you please to tell what *rule update* you have made?

**Comment by danailedms** [comment]
@magodo this is a systematic issue. After I deploy the firewall, policy and rule collection the first time, any time I re-apply the same state, it puts the policy into update mode even if the policy is not being updated, it then tries to make any rule collection rule updates at the same time if I have made any changes and fails due to the policy being temporarily in update mode.
An example rule change I have tested with is changing the application rule source address from 10.0.0.2 to 10.0.0.1.

**Comment by magodo** [comment]
@danailedms I've just tried again with above change, using the following cfg: https://gist.github.com/magodo/c45fbf9a097c2a695d10151741c654a6. But the update is still successful. Do you get this error even with a fresh new provision? Have you checked whether the policy is stuck in the update state all the time?

**Comment by danailedms** [comment]
@magodo I have tested this in 3 separate provisions.
I have figured out what the problem was!
We have a policy in place that adds a tag on to resources if the tag is not already set. We are not setting tags through terraform on Azure Firewall policies due to there being an issue present (where all tags need to be lower case alphabetical characters only). Terraform was removing the tag with every deployment and the policy was re-applying it automatically, so there was no visible indicators in the Azure portal. We have put an exclusion in the policy for resource types Microsoft.Network/firewallPolicies and Microsoft.Network/firewallPolicies/ruleCollectionGroups, and the policy no longer enters an update state when no updates are made, so the rule collection group updates successfully.
Thank you very much for all your assistance.

**Comment by robk9e** [comment]
I am facing the same issue:

Error: creating Firewall Policy Rule Collection Group "DefaultDnatRuleCollectionGroup" (Resource Group "ROBSON-TEST-RG" / Policy: "DefaultFirewallPolicy"): network.FirewallPolicyRuleCollectionGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyRuleCollectionGroupUpdateNotAllowed" Message="Rule Collection Group DefaultDnatRuleCollectionGroup can not be updated because Parent Firewall Policy DefaultFirewallPolicy is in Updating state from previous operation ID : 5483aa79-09e5-4194-a47e-23b403fe4a41."
│ 
│   with azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup,
│   on 08-FIREWALL-RULES.tf line 19, in resource "azurerm_firewall_policy_rule_collection_group" "DefaultDnatRuleCollectionGroup":
│   19: resource "azurerm_firewall_policy_rule_collection_group" "DefaultDnatRuleCollectionGroup" {

``
# Firewall Policy Rules

#Firewall Policy
resource "azurerm_firewall_policy" "DefaultFirewallPolicy" {
  name                = "DefaultFirewallPolicy"
  resource_group_name = var.resource_group_name
  location            = var.resource_group_location
  sku                 = "Premium"
  tags                = var.tags

  depends_on = [
    azurerm_resource_group.robson
    

  ]
}

# DNAT Rule
resource "azurerm_firewall_policy_rule_collection_group" "DefaultDnatRuleCollectionGroup" {
  name               = "DefaultDnatRuleCollectionGroup"
  firewall_policy_id = azurerm_firewall_policy.DefaultFirewallPolicy.id
  priority           = 100

  nat_rule_collection {
    name     = "AccessServersNAT"
    priority = 1001
    action   = "Dnat"
    rule {
      name                = "AllowHomeToSRV1"
      protocols           = ["TCP"]
      source_addresses    = ["109.255.96.61"]
      destination_address = "109.255.96.61" //module.firewall_publicip.public_ip[0].ip_address
      destination_ports   = ["22"]
      translated_address  = "10.71.134.4"
      translated_port     = "22"
    }
  }

  depends_on = [
    azurerm_firewall_policy.DefaultFirewallPolicy,
   // azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup
    
  ]

}

resource "azurerm_firewall_policy_rule_collection_group" "DefaultNetworkRuleCollectionGroup" {
  name               = "DefaultNetworkRuleCollectionGroup"
  firewall_policy_id = azurerm_firewall_policy.DefaultFirewallPolicy.id
  priority           = 200

  network_rule_collection {
    name     = "AllowPingToPrivateNetworks"
    priority = 1001
    action   = "Allow"
    rule {
      name                  = "AllowPing"
      protocols             = ["ICMP"]
      source_addresses      = ["*"]
      destination_addresses = ["*"]
      destination_ports     = ["1-65535"]
    }
  }

  depends_on = [
    azurerm_firewall_policy.DefaultFirewallPolicy,
   //  azurerm_firewall_policy.DefaultFirewallPolicy.tags
  ]
}

resource "azurerm_firewall_policy_rule_collection_group" "DefaultApplicationRuleCollectionGroup" {
  name               = "DefaultApplicationRuleCollectionGroup"
  firewall_policy_id = azurerm_firewall_policy.DefaultFirewallPolicy.id
  priority           = 300

  application_rule_collection {
    name     = "AccessUbuntu"
    priority = 1001
    action   = "Allow"
    rule {
      name = "AllowUbuntuRepository"
      protocols {
        type = "Http"
        port = 80
      }
      protocols {
        type = "Https"
        port = 443
      }
      source_addresses  = ["*"]
      destination_fqdns = ["azure.archive.ubuntu.com","security.ubuntu.com"]
    }
  }

  depends_on = [
    azurerm_firewall_policy.DefaultFirewallPolicy,
   // azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup,
   // azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup
  ]
}

``

**Comment by magodo** [comment]
@robk9e Do you mean the first creation of the above config will raise error? I've tried above config and even made an update, everything works fine. May I know which location did you specified?

**Comment by robk9e** [comment]
@magodo yes.. you are correct. I tried many times with no luck

**Comment by magodo** [comment]
@robk9e Which place are you running `terraform` from?

**Comment by robk9e** [comment]
@robk9e from my ubuntu server

**Comment by magodo** [comment]
@robk9e I mean which region does your ubuntu server runs. The region matters because it decides which Azure mgmt endpoint your request will finally be routed to, where the service software might has drift with nodes in other regions.

**Comment by robk9e** [comment]
I running from Ireland - Dublin

**Comment by robk9e** [comment]
Tried now and worked:

`Plan: 4 to add, 0 to change, 0 to destroy.
azurerm_firewall_policy.DefaultFirewallPolicy: Creating...
azurerm_firewall_policy.DefaultFirewallPolicy: Creation complete after 3s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy]
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Creating...
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Creating...
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Creating...
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Still creating... [10s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Still creating... [10s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Still creating... [10s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Creation complete after 14s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultNetworkRuleCollectionGroup]
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Still creating... [20s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Still creating... [20s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Creation complete after 28s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultDnatRuleCollectionGroup]
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Still creating... [30s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Still creating... [40s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Creation complete after 43s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultApplicationRuleCollectionGroup]

Apply complete! Resources: 4 added, 0 changed, 0 destroyed.`

**Comment by robk9e** [comment]
Failed again

```
Plan: 8 to add, 0 to change, 0 to destroy.
module.firewall_publicip.azurerm_public_ip.publicip[0]: Creating...
azurerm_firewall_policy.DefaultFirewallPolicy: Creating...
azurerm_log_analytics_workspace.firewall: Creating...
azurerm_log_analytics_workspace.firewall: Creation complete after 2s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.OperationalInsights/workspaces/firewall-01]
azurerm_firewall_policy.DefaultFirewallPolicy: Creation complete after 3s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy]
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Creating...
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Creating...
azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup: Creating...
module.firewall_publicip.azurerm_public_ip.publicip[0]: Creation complete after 4s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/publicIPAddresses/FIREWALL-public-ip]
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Still creating... [10s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Still creating... [10s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultDnatRuleCollectionGroup: Creation complete after 13s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultDnatRuleCollectionGroup]
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Still creating... [20s elapsed]
azurerm_firewall_policy_rule_collection_group.DefaultNetworkRuleCollectionGroup: Creation complete after 28s [id=/subscriptions/0789a83b-93dc-4964-a9b5-6390a2d5e83e/resourceGroups/ROBSON-TEST-RG/providers/Microsoft.Network/firewallPolicies/DefaultFirewallPolicy/ruleCollectionGroups/DefaultNetworkRuleCollectionGroup]
╷
│ Error: creating Firewall Policy Rule Collection Group "DefaultApplicationRuleCollectionGroup" (Resource Group "ROBSON-TEST-RG" / Policy: "DefaultFirewallPolicy"): network.FirewallPolicyRuleCollectionGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyRuleCollectionGroupUpdateNotAllowed" Message="Rule Collection Group DefaultApplicationRuleCollectionGroup can not be updated because Parent Firewall Policy DefaultFirewallPolicy is in Updating state from previous operation ID : 047571d0-4751-4627-96d6-d9d8e4fc3c59."
│ 
│   with azurerm_firewall_policy_rule_collection_group.DefaultApplicationRuleCollectionGroup,
│   on 08-FIREWALL-RULES.tf line 71, in resource "azurerm_firewall_policy_rule_collection_group" "DefaultApplicationRuleCollectionGroup":
│   71: resource "azurerm_firewall_policy_rule_collection_group" "DefaultApplicationRuleCollectionGroup" {
```

**Comment by magodo** [comment]
@robk9e I've been testing for your above config (by replacing the rg with a new rg in `northeurope`) with the endpoint set to `https://northeurope.management.azure.com` for multiple times, but the issue didn't occur. Is there by any chance your organization has some policy that will update your fw policy on creation, as @danailedms has stated?

**Comment by robk9e** [comment]
@magodo, unfortunately, we don't have such a policy in our environment. We use this subscription as a test environment and everything is created by terraform.

I have found a similar issue on the link below and this explanation:
```
Only one Rule Collection Group can be updated at a time with Azure Firewall Policy. Since the update refreshes all of the connected Azure Firewall instances, the amount of time it takes to update is non-deterministic. Therefore you will need to serialize the deployment using the batchSize decorator.
```
https://github.com/Azure/bicep/issues/1013#issuecomment-932126524

Does it make sense? If so, how to do that with terraform?

**Comment by p4ranoidandro1d** [comment]
I'm running into the same problem, same terraform provider version. 2.96.

I'm trying to create 3 empty groups for now. 
Azure Firewall Standard Tier.

None of the 3 groups is created due to firewall policy in Updating status because of this operation .. 

```
╷
│ Error: creating Firewall Policy Rule Collection Group "networkRuleCollectionGroup" (Resource Group "rg-firewall" / Policy: "fwpol"): network.FirewallPolicyRuleCollectionGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyRuleCollectionGroupUpdateNotAllowed" Message="Rule Collection Group networkRuleCollectionGroup can not be updated because Parent Firewall Policy fwpol is in Updating state from previous operation ID : ab231b47-5c71-43f4-b09b-2b365d7b4165."
│ 
│   with module.firewall.azurerm_firewall_policy_rule_collection_group.fwrcg["networkRuleCollectionGroup"],
│   on /builds/cloudplatform/azure/networking/firewall/modules/modules/azure_firewall/rules.tf line 1, in resource "azurerm_firewall_policy_rule_collection_group" "fwrcg":
│    1: resource "azurerm_firewall_policy_rule_collection_group" "fwrcg" {
│ 
╵
```

```{
    "authorization": {
        "action": "Microsoft.Network/firewallPolicies/write",
        "scope": "/subscriptions/xx/resourceGroups/rg-firewall/providers/Microsoft.Network/firewallPolicies/fwpol"
    },
    "caller": "33413657-cc76-4610-aae0-a8df3392ac58",
    "channels": "Operation",
    "claims": {
        "aud": "https://management.azure.com/",
        "iss": "https://sts.windows.net/yy/",
        ....
},
    "correlationId": "906c428f-3a44-80c8-2eea-a905c708cd86",
    "description": "",
    "eventDataId": "b83f36fb-5be2-43ed-a5d7-9d234de4ced7",
    "eventName": {
        "value": "EndRequest",
        "localizedValue": "End request"
    },
    "category": {
        "value": "Administrative",
        "localizedValue": "Administrative"
    },
    "eventTimestamp": "2022-02-21T22:38:38.9473485Z",
    "id": "/subscriptions/xx/resourceGroups/rg-firewall/providers/Microsoft.Network/firewallPolicies/fwpol/events/b83f36fb-5be2-43ed-a5d7-9d234de4ced7/ticks/637810799189473485",
    "level": "Informational",
    "operationId": "f9cd1cae-0b8d-4122-8c8e-32740f40310d",
    "operationName": {
        "value": "Microsoft.Network/firewallPolicies/write",
        "localizedValue": "Create or Update Firewall Policy"
    },
    "resourceGroupName": "rg-firewall",
    "resourceProviderName": {
        "value": "Microsoft.Network",
        "localizedValue": "Microsoft.Network"
    },
    "resourceType": {
        "value": "Microsoft.Network/firewallPolicies",
        "localizedValue": "Microsoft.Network/firewallPolicies"
    },
    "resourceId": "/subscriptions/xx/resourceGroups/rg-firewall/providers/Microsoft.Network/firewallPolicies/fwpol",
    "status": {
        "value": "Accepted",
        "localizedValue": "Accepted"
    },
    "subStatus": {
        "value": "OK",
        "localizedValue": "OK (HTTP Status Code: 200)"
    },
    "submissionTimestamp": "2022-02-21T22:39:51.1339355Z",
    "subscriptionId": "xx",
    "tenantId": "yy",
    "properties": {
        "statusCode": "OK",
        "serviceRequestId": "ab231b47-5c71-43f4-b09b-2b365d7b4165",   <====
        "eventCategory": "Administrative",
        "entity": "/subscriptions/xx/resourceGroups/rg-firewall/providers/Microsoft.Network/firewallPolicies/fwpol",
        "message": "Microsoft.Network/firewallPolicies/write",
        "hierarchy": "yy/aa/bb/xx/xx"
    },
    "relatedEvents": []
}```

**Comment by magodo** [comment]
@robk9e To avoid the parallel operations, we've already added the lock against the fw policy to serialize the rule collection  group operations (for create/update/delete):

https://github.com/hashicorp/terraform-provider-azurerm/blob/a22742cf74baa2cd932e72caebbb3382f57870dd/internal/services/firewall/firewall_policy_rule_collection_group_resource.go#L444-L445

I still can't reproduce it locally, would you mind reproduce the issue with debug log enabled, and provide the log so that I can further investigate?

**Comment by p4ranoidandro1d** [comment]
Hi guys,

i have a debug run below.

the apply itself generates an operation which then blocks the resources to be created.

ligne : 26 of below file (Azure-Asyncoperation: https://management.azure.com/subscriptions/[MASKED]/providers/Microsoft.Network/locations/switzerlandnorth/nfvOperations/bbe08af7-e17d-4249-a8bd-757ce1044612?api-version=2021-05-01)

https://gist.github.com/p4ranoidandro1d/fe5142955a604912fe92d0a422155f12

**Comment by robk9e** [comment]
Yep,
https://gist.github.com/robk9e/e549dcb5a297fff2d7c5e6651653fe54

**Comment by robk9e** [comment]
quick update:
I reran terraform apply the command to create and add the missing Firewall Policy Rule Collection Group to the parent policy, everything went well until attaching the policy to the firewall:

Terraform command:
Error: creating/updating Firewall: (Azure Firewall Name "FIREWALL" / Resource Group "ROBSON-TEST-RG"): network.AzureFirewallsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InternalServerError" Message="An error occurred." Details=[]
│ 
│   with azurerm_firewall.firewall,
│   on 08-FIREWALL.tf line 17, in resource "azurerm_firewall" "firewall":
│   17: resource "azurerm_firewall" "firewall" {

Via Portal:
Failed to update association(s)
Failed to update the association for the resource 'FIREWALL'. Error: An error occurred.

Checking the activity logs for the DefaultFirewallPolicy, I can see many validation tests made by Azure Traffic Manager and DNS with errors :

![error with DefaultFirewallPolicy](https://user-images.githubusercontent.com/26840035/155132655-09250f67-c2c3-4312-a519-4a507005966a.png)

Summary:
If we retry the action to add the missing rules to the policy, something internally breaks and makes the policy unusable.

**Comment by robk9e** [comment]
> @robk9e (danailedms here). I found that I was getting exactly the same error when trying to create the firewall after the policy already existed. If I removed everything (firewall, pip, policy and rule collection group) then recreated everything in one go with the following depends on statements, it worked for me (without these depends on statements, it does not appear to work and I get the same error)....
> 
> * Policy rule collection group depends on firewall policy.
> * Firewall depends on policy rule collection group.
> 
> It is a terrible error message as it gives us no indication of what the route cause was. Try this and see if this resolves the error for you.

Indeed solves the InternalError but throws us back to the initial problem :/
