### ISSUE TITLE
Updates to `parameters` cause Policy Assignment resources to be `replaced` instead of updated in-place

### ISSUE THREAD

**Issue by krowlandson** [hashicorp/terraform-provider-azurerm#15444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
Terraform v1.1.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0
```

### Affected Resource(s)

* `azurerm_policy_assignment` (_deprecated_)
* `azurerm_management_group_policy_assignment`
* `azurerm_subscription_policy_assignment`
* `azurerm_resource_group_policy_assignment`
* `azurerm_resource_policy_assignment `

### Terraform Configuration Files

> The following example shows this in the context of the `azurerm_management_group_policy_assignment` resource, but is repeatable for Policy Assignments at each supported scope.

```hcl
variable "toggle_allowed_locations" {
  type        = bool
  description = "Toggle the list of allowed locations for resources. Changing this will force the Policy Assignment to be recreated."
  default     = false
}

locals {
  allowed_locations_one = ["westeurope"]
  allowed_locations_two = ["westeurope", "northeurope"]
  allowed_locations     = var.toggle_allowed_locations ? local.allowed_locations_two : local.allowed_locations_one
}

resource "azurerm_management_group" "example" {
  display_name = "Some Management Group"
}

resource "azurerm_policy_definition" "example" {
  name                = "my-policy-definition"
  policy_type         = "Custom"
  mode                = "All"
  display_name        = "my-policy-definition"
  management_group_id = azurerm_management_group.example.group_id

  policy_rule = <<POLICY_RULE
    {
    "if": {
      "not": {
        "field": "location",
        "in": "[parameters('allowedLocations')]"
      }
    },
    "then": {
      "effect": "audit"
    }
  }
POLICY_RULE


  parameters = <<PARAMETERS
    {
    "allowedLocations": {
      "type": "Array",
      "metadata": {
        "description": "The list of allowed locations for resources.",
        "displayName": "Allowed locations",
        "strongType": "location"
      }
    }
  }
PARAMETERS

}

resource "azurerm_management_group_policy_assignment" "example" {
  name                 = "my-policy-assignment"
  display_name         = "My Example Policy Assignment"
  management_group_id  = azurerm_management_group.example.id
  policy_definition_id = azurerm_policy_definition.example.id

  parameters = jsonencode({
    allowedLocations = {
      value = local.allowed_locations
    }
  })

}

```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behaviour

Toggling the input variable value for `toggle_allowed_locations` between `true` and `false` should update the Policy Assignment to reflect the two different lists of allowed locations without resulting in the Policy Assignment being `replaced`.

### Actual Behaviour

Toggling the input variable value for `toggle_allowed_locations` between `true` and `false` results in Terraform reporting that the Policy Assignment will be `replaced` as per the following example output from `terraform plan`:

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_management_group_policy_assignment.example must be replaced
-/+ resource "azurerm_management_group_policy_assignment" "example" {
      ~ id                   = "/providers/Microsoft.Management/managementGroups/ae4d5e6d-4950-4482-8f4a-d1d20cd905ce/providers/Microsoft.Authorization/policyAssignments/my-policy-assignment" -> (known after apply)
      ~ metadata             = jsonencode(
            {
              - createdBy = "89685837-e8e5-4be4-933a-7dc867b2955d"
              - createdOn = "2022-02-15T20:59:26.1160894Z"
              - updatedBy = null
              - updatedOn = null
            }
        ) -> (known after apply)
        name                 = "my-policy-assignment"
      - not_scopes           = [] -> null
      ~ parameters           = jsonencode(
          ~ {
              ~ allowedLocations = {
                  ~ value = [
                        "westeurope",
                      + "northeurope",
                    ]
                }
            } # forces replacement
        )
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

I recognise that this is the documented behaviour, but I believe this is something which can and should be updated.
I've provided additional information to back this up below in the Important Factoids section.

### Steps to Reproduce

1. Create a new root module using the example code above.
2. Run `terraform init`.
3. Run `terraform apply` and confirm the changes.
4. Once all resources are successfully created, run `terraform apply` again to confirm no changes are needed.
Note at this point that Terraform actually reports changes made outside of Terraform as below which we believe is another bug but not directly related to the issue being reported here:
```shell
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_management_group_policy_assignment.example has changed
  ~ resource "azurerm_management_group_policy_assignment" "example" {
        id                   = "/providers/Microsoft.Management/managementGroups/ae4d5e6d-4950-4482-8f4a-d1d20cd905ce/providers/Microsoft.Authorization/policyAssignments/my-policy-assignment"
        name                 = "my-policy-assignment"
      + not_scopes           = []
        # (6 unchanged attributes hidden)
    }


Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to     
these changes.
```
5. Run `terraform plan -var='toggle_allowed_locations=true'` and not that Terraform is reporting that the Policy Assignment resource must be `replaced`:
```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_management_group_policy_assignment.example must be replaced
-/+ resource "azurerm_management_group_policy_assignment" "example" {
      ~ id                   = "/providers/Microsoft.Management/managementGroups/ae4d5e6d-4950-4482-8f4a-d1d20cd905ce/providers/Microsoft.Authorization/policyAssignments/my-policy-assignment" -> (known after apply)
      ~ metadata             = jsonencode(
            {
              - createdBy = "89685837-e8e5-4be4-933a-7dc867b2955d"
              - createdOn = "2022-02-15T20:59:26.1160894Z"
              - updatedBy = null
              - updatedOn = null
            }
        ) -> (known after apply)
        name                 = "my-policy-assignment"
      - not_scopes           = [] -> null
      ~ parameters           = jsonencode(
          ~ {
              ~ allowedLocations = {
                  ~ value = [
                        "westeurope",
                      + "northeurope",
                    ]
                }
            } # forces replacement
        )
        # (4 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Important Factoids

Replacement of a Policy Assignment results in the loss of all compliance and remediation data which can cause issues for some organizations where this data must be retained for auditing.

It's also worth noting that the replacement of a Policy Assignment where a Managed Identity is required for `DeployIfNotExists` or `Modify` effects results in a new Managed Identity being created, and therefore Role Assignments for this also need to be refreshed unnecessarily.

When the Policy Assignment resources were last updated in the provider, they were using an old version of the Azure SDK for Go ([github.com/Azure/azure-sdk-for-go/services/resources/mgmt/2019-09-01/policy](https://github.com/Azure/azure-sdk-for-go/tree/main/services/resources/mgmt/2019-09-01/policy)) which didn't include the latest `update` method. As such, the only option was for Terraform to `replace` the resource as observed.

This is reflected by the presence of `ForceNew:         true,` in the code, as per the following:

https://github.com/hashicorp/terraform-provider-azurerm/blob/770158de3e23639080e30ec54daf7c485fd20610/internal/services/policy/assignment_base_resource.go#L358-L364

In the `2021-06-01-preview` version of the API (which was added in PR #14518 and released in [v2.90.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v2.90.0/CHANGELOG.md)), there is now an `Update()` function: 

https://github.com/Azure/azure-sdk-for-go/blob/17d28e1b40b95be9a5a121e4f1c4d85da0042d1f/services/preview/resources/mgmt/2021-06-01-preview/policy/assignments.go#L1153-L1184

My belief is that it should now be possible to update the Terraform provider to support in-place updates for Policy Assignments.

### References

_none found_

**Comment by krowlandson** [comment]
cc: @LaurentLesle, @jtracey93, @matt-FFFFFF

**Comment by lonegunmanb** [comment]
Hi @krowlandson , since the `parameters` are updateable now, would you please try again? Thanks.

**Comment by krowlandson** [comment]
Hi @lonegunmanb ... yes, I can confirm this issue is now resolved. Thank you
