### ISSUE TITLE
r/shared_image: support for advanced_networking_enabled

### ISSUE THREAD

**Issue by scott1138** [hashicorp/terraform-provider-azurerm#15441]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In December 2021 Microsoft added support for specifying features for image definitions.  Documentation for what can be supplied is in the documentation for the [az cli](https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-definition.yml).

The issue is that when adding a new image version, if the source image has a feature configured, like IsAcceleratedNetworkSupported=true, and the definition does not have this feature, image creation fails.

### New or Affected Resource(s)

* azurerm_shared_image

### Potential Terraform Configuration

```hcl
resource "azurerm_shared_image" "image" {
  name                = "myImage"
  gallery_name        = "myGallery"
  resource_group_name = "myResourceGroup"
  location            = "centralus"
  os_type             = "linux"
  
  features {
    IsAcceleratedNetworkSupported = true
  }

  identifier {
    publisher = "myPublisher"
    offer     = "myOffer"
    sku       = "mysku"
  }

  purchase_plan {
    publisher = "myPublisher"
    product   = "myOffer"
    publisher = "mysku"
  }

}
```

### References

https://github.com/MicrosoftDocs/azure-docs-cli/blob/main/latest/docs-ref-autogen/sig/image-definition.yml
https://github.com/Azure/azure-powershell/pull/16621/files
https://docs.microsoft.com/en-us/powershell/module/az.compute/new-azgalleryimagedefinition?view=azps-7.2.0#examples -Example 4
https://docs.microsoft.com/en-us/rest/api/compute/gallery-images/update

**Comment by myc2h6o** [comment]
`SecurityType=TrustedLaunch` was added earlier as part of the `features`. I'll see if I'm able to add support for the general `feature` and include the already existing SecurityType
https://github.com/hashicorp/terraform-provider-azurerm/blob/15076cec31362037c89f6dfef9374c4108da8b3c/internal/services/compute/shared_image_resource.go#L190-L196

**Comment by tombuildsstuff** [comment]
@myc2h6o we're moving away from exposing the `features` blocks in favour of specific properties (as above) due to inconsistencies in the API's - so that's not something we'd expose here directly.

In this instance I'm going to update this issue title to add a new field for `advanced_networking_enabled` which should cover this use-case.
