### ISSUE TITLE
Global Parameters being deleted in azurerm_data_factory when using azurerm providers 2.62 and greater

### ISSUE THREAD

**Issue by gsmartvoda** [hashicorp/terraform-provider-azurerm#15447]
Global Parameters are being deleted in azurerm_data_factory when using azurerm providers 2.62 and greater.

We currently manage global parameters outside of TF in there own repo & CI/CD pipeline. I understand this is an added function from 2.62 however global parameters are labelled as optional. When we are using ver 2.62 and onwards it will delete the global parameters unless added into the file.

We plan to continue using global parameters outside of TF. Is there anyway to prevent Terraform from deleting the parameters other than adding them into the code?

**Comment by ms-henglu** [comment]
Hi @gsmartvoda , how about using `ignore_changes` on `global_paramter`, then the changes will be ignored.

```
resource "azurerm_data_factory" "test" {
  name                = "henglu217"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  public_network_enabled = false
  identity {
    type = "SystemAssigned"
  }

  global_parameter {
    name  = "key1"
    type  = "String"
    value = "value1"
  }

  lifecycle {
    ignore_changes = [global_parameter]
  }
}
```

**Comment by manicminer** [comment]
Hi @gsmartvoda, thanks for opening this issue. Support for configuring the `global_parameter` property was added in v2.64.0 of the provider. As per Terraform's declarative design, when adding support for properties for existing resources, this means Terraform will seek to manage the newly supported property. As per @ms-henglu's comment, the correct way to mitigate this is to instruct Terraform to ignore these changes via the `ignore_changes` lifecycle parameter.

I believe this should resolve the conflict you are facing when partly managing this resource outside of Terraform, and accordingly I'm going to close this issue for now. Thanks again for raising this.
