### ISSUE TITLE
terraform import required when creating custom hostname binding with traffic manager.

### ISSUE THREAD

**Issue by maritechsgooddalton** [hashicorp/terraform-provider-azurerm#15456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform version 0.12.31
AzureRm version 2.96

### Affected Resource(s)

* `azurerm_app_service_custom_hostname_binding`

### Terraform Configuration Files

```hcl
terraform-certificates.zip added.
[terraform-certificates.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/8081326/terraform-certificates.zip)

```

### Debug Output

Please see Gist https://gist.github.com/maritechsgooddalton/ed7407430f268f19288840329415a473

### Expected Behaviour

Terraform should create all the resources and not require an import of the custom hostname binding. This resource needs to be created within terraform as the dependent resources need the id of the binding.

### Actual Behaviour

Terraform requires an import.

### Steps to Reproduce

1. `terraform0.12.31 apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
