### ISSUE TITLE
r/cosmosdb: support for User Assigned Identities

### ISSUE THREAD

**Issue by RanjithTom** [hashicorp/terraform-provider-azurerm#15454]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.3

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_user_assigned_identity" "cosmos_identity" {
  resource_group_name = var.resource_group_name
  location            = var.location
  name                = "${var.customer_name}-${var.environment}-db-identity"
  tags                = local.default_tags
}

data "azurerm_client_config" "current" {}

#Grant Azure provided cosmosDB Identity to access db encryption key in keyvault
resource "azurerm_key_vault_access_policy" "access_policy_db" {
  key_vault_id = var.keyvault_id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_user_assigned_identity.cosmos_identity.id

  key_permissions = [
    "get",
    "unwrapKey",
    "wrapKey",
  ]
}
resource "azurerm_cosmosdb_account" "db_account" {
  name                = "test-cosmos-dbaccount"
  location            = var.location
  resource_group_name ="sample resource"
  offer_type          = "Standard"
  kind                = "MongoDB"
  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }
  capabilities {
    name = "MongoDBv3.4"
  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = var.failover_location
    failover_priority = 1
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }

  #User Assigned identity created and have access to azure keyvault to read key id for CMK
  default_identity_type = "UserAssignedIdentity=${azurerm_user_assigned_identity.cosmos_identity.id}"
  key_vault_key_id = var.db_encryption_key_id

  tags = local.default_tags

  #Keyvault policy needs to be updated before cosmos db account creation
  depends_on = [
    azurerm_key_vault_access_policy.access_policy_db,
  ]
}
```

### Expected Behaviour

As per the implementation Cosmos Account should use the UserAssignedIdentity created when accessing your encryption keys in Azure Key Vault. Then It is possible to create keyvault key for CMK encryption in cosmosdb accoutn and creation of cosmos db account  everything in a single go with using an UserAssignedIdentity

### Actual Behaviour

But in terraform apply getting this error -> Error : Updating default identity not allowed. Cannot set default identity to UserAssigned because the account doesn't have any UserAssigned identities.

### Steps to Reproduce

1. `terraform apply`

### References

In Terraform documentation for cosmos db account it is documented that ->
default_identity_type - (Optional) The default identity for accessing Key Vault. Possible values are FirstPartyIdentity, SystemAssignedIdentity or start with UserAssignedIdentity. Defaults to FirstPartyIdentity.

But in Identity Block only allowed type is SystemAssigned

Link -> https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#identity

So How we can use the UserAssignedIdentity as default_identity_type via terraform

* #0000

**Comment by mnazir23** [comment]
Hi,

is there any update on when this will become available?

**Comment by Insighter2k** [comment]
> Hi,
> 
> is there any update on when this will become available?

I can sign this. I have to mix powershell with terraform scripts. At which point can we await a solution which incorporates a "UserAssignedIdentity" in terraform?

**Comment by mnazir23** [comment]
@Insighter2k 

can you please elaborate? thank you
