### ISSUE TITLE
Application gateway certificate replaced by old certificate from terraform state

### ISSUE THREAD

**Issue by eager** [hashicorp/terraform-provider-azurerm#15463]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.0.4
Provider 2.55.0

(I have confirmed that the bug would still be present in the latest provider version.)

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
azurerm_application_gateway {
  ssl_certificate {
    name = "my_cert"
  }

  http_listener {
    certificate_name = "my_cert"
  }

  lifecycle {
    ignore_changes = [ssl_certificate]
  }
}
```

### Expected Behaviour

Existing SSL certificate should not replaced by prior version of a certificate that happened to be lingering in state

### Actual Behaviour

Existing SSL certificate was replaced by prior version of a certificate

### Steps to Reproduce

1. We had an application gateway with an `ssl_certificate` that was created with Terraform using a local certificate file & password. The gateway definition also had `lifecycle { ignore_changes = [ ssl_certificate ] }`.

2. Later, we updated the certificate data via the Azure console (the name remained the same). 

3. Lastly, we used Terraform to make an in-place change to request routing rules for the application gateway. As a side effect, the original, now invalid, certificate was restored.

I believe that the issue is this logic in `flattenApplicationGatewaySslCertificates` : https://github.com/hashicorp/terraform-provider-azurerm/blob/7d92759ef8ce072e787af569feb60d7474367bb2/internal/services/network/application_gateway_resource.go#L3755-L3773.

I definitely recognize that this  is a bit of an odd case, and maybe not recommended usage, but it definitely surprised us. 

Before we figured out exactly what was happening, we noticed that the SSL certificate’s etag value was changing after the `terraform apply`. I’m not able to submit a PR at this time, but updating `flattenApplicationGatewaySslCertificates` to check that the name _and_ etag both match seems like one possible solution.

**Comment by neil-yechenwei** [comment]
@eager , thanks for raising this issue. As Service API doesn't return the value of the `data` property, so terraform has to always set it using the value in local tf config. Generally, the resource should be maintained by Terraform in whole life cycle. For this case, if you changed `data` outside of the terraform, you have to update the `data` in tf config accordingly to avoid restoring.

**Comment by eager** [comment]
@neil-yechenwei thank you for the response! I definitely understand the constraints of the API, and we have updated our tf configuration to avoid this issue. One thought:

> As Service API doesn't return the value of the `data` property, so terraform has to always set it using the value in local tf config

The `etag` property could be useful, given the API constraints. Setting the particulars of this case aside, it seems like tf config that does maintain the certificate lifecycle might not be alerted to changes made outside of terraform, since `data` is not returned, while comparing `etag` values would allow the provider to detect out-of-band changes.

**Comment by neil-yechenwei** [comment]
Per my understanding, though TF can use etag + name to be able to distinguish the difference between tf config and Azure, but TF still cannot avoid this issue since service api doesn't return the value of the data property.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. I am going to close this issue based on the conversation above:

> Per my understanding, though TF can use etag + name to be able to distinguish the difference between tf config and Azure, but TF still cannot avoid this issue since service api doesn't return the value of the data property.

Whilst I'd like to thank you for opening this issue as we have no plans to support this functionality I'm going to close this issue for the moment.
