### ISSUE TITLE
azurerm_consumption_budget_subscription start_date incorrect for billing time grains

### ISSUE THREAD

**Issue by maldridgerp** [hashicorp/terraform-provider-azurerm#15467]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.5
azurerm v2.96.0

### Affected Resource(s)

* azurerm_consumption_budget_subscription.budget

### Terraform Configuration Files

```hcl
resource "azurerm_consumption_budget_subscription" "budget" {
  name            = "Test_Budget"
  subscription_id = data.azurerm_subscription.current.subscription_id

  amount     = 210 
  time_grain = "BillingMonth"

  time_period {
    start_date = "2022-01-18T00:00:00Z" 
    end_date   = "2030-01-01T00:00:00Z"
  }
}
```

### Debug Output

Error: "time_period.0.start_date" must be first of the month, got day 18

### Expected Behaviour

The start_date for budgets with billing time grains (BillingMonth, BillingQuarter, BillingYear) should have the day of the month set the same as the billing period, not the first day of the month. When creating a budget in the Azure portal it sets this and cannot be changed (unlike the calendar time grains which set it to the first day of the month).

### Actual Behaviour

Can only set the start_date to the start of the month and the budget is calculated for the calendar month instead of the billing month.

### Steps to Reproduce

1. Setup a subscription with a monthly billing period that begins in the middle of the month
2. Create a BillingMonth budget and try to set the day of month for the start date to align with the billing period.
3. `terraform apply`

**Comment by Matthew0x** [comment]
It's been over a year and the issue persists (as officially documented in Terraform's pages and MS's).
Currently it seems quite broken, as nobody can efficiently use it, what are engineers deploying on e.g. 5th of February supposed to do? It's not functional regarding the action groups and custom alerts.

Some API messages are not explanatory.
"Start date for quarterly time grain should not be prior to three months." 
Suggestion: "Start date must begin the time grain period" (it was the start_date error)

"A future start date shouldn't be more than three months in the future."
Is this also the current restriction?

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
