### ISSUE TITLE
azurerm_data_factory_linked_service_sql_server Windows Authentication / userName Property

### ISSUE THREAD

**Issue by andrewtatham-shell** [hashicorp/terraform-provider-azurerm#15475]
I see this issue has previously been discussed as #12274, which is closed, but the resolution be better.

It is true that including a User ID component in the connection string yields a linked service that does work with windows authentication.

However when the linked service is viewed in the ADF UI, it appears as "SQL Authentication" which is incorrect.

![image](https://user-images.githubusercontent.com/75247210/154459530-3ecad03b-ea3e-4968-be40-991d12cc4db5.png)

This is a problem as anyone viewing it could be misled.

Adding the userName property in the json as per below fixes the UI display completely. Please can this property be explicitly added to the provider?

```json
{
    "name": "my_connnector",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "type": "SqlServer",
        "typeProperties": {
            "userName": "MYDOMAIN\\MyUserName",
        },
    },
}
```

Please can [the doc page](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_sql_server) be updated with a note/example to make using windows authentication more obvious?

Thanks

Andrew

**Comment by ms-henglu** [comment]
Hi @andrewtatham-shell , thank you for taking time to report this issue.

I have a workaround for this, how about using https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_custom_service? This is a generic resource that supports all different Linked Service Types.
