### ISSUE TITLE
Support for Azure Spring Cloud Enterprise

### ISSUE THREAD

**Issue by rtrompier** [hashicorp/terraform-provider-azurerm#15484]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the new Azure Spring Cloud Enterprise offer

### New or Affected Resource(s)

* azurerm_spring_cloud_service

### References

https://azure.microsoft.com/en-us/blog/azure-spring-cloud-enterprise-is-now-available-in-preview/

**Comment by gradinDotCom** [comment]
This has been resolved as of the release of Azure Spring Apps Enterprise General Availability.

**Comment by ms-henglu** [comment]
Hi @rtrompier ,

Spring Cloud Enterprise tier has been supported, would you please check and close this issue? Thanks!

**Comment by tombuildsstuff** [comment]
Closing since this is available within the `azurerm_spring_cloud_service` resource as mentioned above.
