### ISSUE TITLE
VMSS creation fails with Code="RetryableError" Message="A retryable error occurred."

### ISSUE THREAD

**Issue by aslafy-z** [hashicorp/terraform-provider-azurerm#15509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v1.1.2
* AzureRM Provider version: v2.90.0

### Affected Resource(s)

`azurerm_linux_virtual_machine_scale_set`

#### Expected Behavior
The VMSS is created successfully.

#### Actual Behavior
Terraform fails with given error

```
│ Error: waiting for creation of Linux Virtual Machine Scale Set "worker_scale_set" (Resource Group "test-rg"): Code="RetryableError" Message="A retryable error occurred."
│ 
│   with azurerm_linux_virtual_machine_scale_set.worker_scale_set,
│   on workers.tf line 21, in resource "azurerm_linux_virtual_machine_scale_set" "worker_scale_set":
│   21: resource "azurerm_linux_virtual_machine_scale_set" "worker_scale_set" {
```

#### Steps to Reproduce
Create a stack with several VMSSs, loadbalancer, and vnet resources.
Run terraform apply
It randomly fails with this 

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/8052

**Comment by tombuildsstuff** [comment]
This'll be fixed as a part of #10858 - closing in favour of that issue
