### ISSUE TITLE
Perpetual change on `public_network_access_enabled` for `azurerm_iothub_dps`

### ISSUE THREAD

**Issue by BzSpi** [hashicorp/terraform-provider-azurerm#15503]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v1.0.6
* Azurerm v2.97.0

### Affected Resource(s)

* `azurerm_iothub_dps`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub_dps" "iothub_dps" {
  name                = "my_name"
  resource_group_name = var.resource_group_name
  location            = "West Europe"

  public_network_access_enabled = length(var.allowed_cidrs) > 0
  dynamic "ip_filter_rule" {
    for_each = var.allowed_cidrs
    content {
      name    = replace(ip_filter_rule.value, "/[\\W]/", "-")
      action  = "Accept"
      ip_mask = ip_filter_rule.value
    }
  }

  sku {
    name     = lookup(coalesce(var.dps_sku, var.sku), "name")
    capacity = lookup(coalesce(var.dps_sku, var.sku), "capacity")
  }

  linked_hub {
    connection_string = azurerm_iothub_shared_access_policy.dps_policy.primary_connection_string
    location          = "West Europe"
  }

  tags = local.tags
}
```

### Expected Behaviour

Having empty `allowed_cidrs` variable should disable public network access.

I have the following change perpetually

```
  # module.iothub.azurerm_iothub_dps.iothub_dps will be updated in-place
  ~ resource "azurerm_iothub_dps" "iothub_dps" {
        id                            = "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Devices/provisioningServices/<redacted>"
        name                          = "<redacted>"
      ~ public_network_access_enabled = true -> false
        tags                          = {
            "environment" = "sbx"
        }
        # (6 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }
```

1. `terraform apply`

### Important Factoids

During my tests, I have added IPs in the firewall then removed them. It may be that scenario that breaks.

### References

* #12909

**Comment by tombuildsstuff** [comment]
hi @BzSpi 

To look into this we need the version of Terraform Core and the AzureRM provider being used, would you mind populating this under `Terraform (and AzureRM Provider) Version` above?

Thanks!

**Comment by BzSpi** [comment]
woops, sorry @tombuildsstuff I made the issue too quickly. I've edited

Terraform (and AzureRM Provider) Version

    Terraform v1.0.6
    Azurerm v2.97.0

**Comment by tombuildsstuff** [comment]
@catriona-m could you look into this one?

**Comment by BzSpi** [comment]
This issue is not in the v2.98.0 CHANGELOG, is it expected ?
