### ISSUE TITLE
azurerm_kubernetes_cluster/oms_agent/enabled prematurely removed?

### ISSUE THREAD

**Issue by dimbleby** [hashicorp/terraform-provider-azurerm#15514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.3
registry.terraform.io/hashicorp/azurerm v2.97.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.97"
    }
  }
}

resource "azurerm_kubernetes_cluster" "main" {
  name                = "foo"
  resource_group_name = "foo"
  location            = "foo"

  default_node_pool {
    name    = "foo"
    vm_size = "foo"
  }

  oms_agent {
    enabled                    = true
    log_analytics_workspace_id = "foo"
  }
}
```

### Expected Behaviour

According to [the docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#enabled) the `enabled` field is both deprecated and required, which certainly is confusing - presumably I must include this field, but should expect to be told off for doing so.

> (Required) Is the OMS Agent Enabled? This field is deprecated and will be removed in version 3.0 of the AzureRM Provider.

Anyway, the docs do not say that it is an error for the field to be present.

### Actual Behaviour

```
$ terraform validate
╷
│ Error: Unsupported argument
│
│   on main.tf line 21, in resource "azurerm_kubernetes_cluster" "main":
│   21:     enabled                    = true
│
│ An argument named "enabled" is not expected here.
╵
```

### Steps to Reproduce

`terraform validate`

**Comment by stephybun** [comment]
Hi @dimbleby,

Thanks for raising this issue. We made some larger changes to the way add-ons can be configured for AKS, namely all of the properties in the `addon_profile` block are now available as top level properties but without the `enabled` field. This means add-ons that only had an `enabled` field have been turned into and renamed to booleans e.g. `azure_policy_enabled` and add-ons that accept a configuration are now switched on and off by the presence/absence of that block. I completely agree with you that the documentation is not effectively conveying that change, we will go back and re-work that to make it more clear.
