### ISSUE TITLE
'Unable to locate Storage Account' sporadically

### ISSUE THREAD

**Issue by techy321** [hashicorp/terraform-provider-azurerm#15515]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.88.1

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "primary" {
  name                      = lower("sg${var.company_name}")
  resource_group_name       = var.rgname
  location                  = var.region
  account_tier              = "Standard"
  account_kind              = "StorageV2"
  account_replication_type  = "GRS"
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"

  lifecycle {
    ignore_changes = [tags]
  }
}
```

### Steps to Reproduce

1. `terraform apply`
2. When running terraform plan afterwards, storage account cannot be found for various amounts of time

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/5299

* #0000

**Comment by magodo** [comment]
This bug is being tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/15048 which I'm going to close this in favour of - would you mind subscribing to that issue for updates?

Thanks!
