### ISSUE TITLE
Storage Account - queue properties arguments

### ISSUE THREAD

**Issue by KISMIDEV** [hashicorp/terraform-provider-azurerm#15525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v1.0.5
* AzureRM Provider version: v2.9.5

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  for_each                  = var.storage_account
  name                      = each.key
  resource_group_name       = azurerm_resource_group.example.name
  location                  = azurerm_resource_group.example.location
  account_kind              = each.value.account_kind
  account_tier              = each.value.account_tier
  account_replication_type  = each.value.account_replication_type
  access_tier               = each.value.access_tier
  min_tls_version           = each.value.min_tls_version
  enable_https_traffic_only = each.value.enable_https_traffic_only
  allow_blob_public_access  = each.value.allow_blob_public_access

  queue_properties {
    logging {
      delete = true
      read = true
      write = true
      version = "1.0"
      retention_policy_days = 10
    }
  }
}
```

### Description / Feedback

Hi!

I'm testing adding queue properties to my Storage Account tf code.
When the property was updated and `terraform apply`, the following error occurred due to the arguments
The error message is shown in the image below

![image](https://user-images.githubusercontent.com/70998863/154918458-e1722233-6a3e-496f-9a05-99e9c7d47047.png)

Is the problem caused by the Terraform version? 
I'd appreciate it if you could write a solution.

Thank you!

**Comment by magodo** [comment]
@KISMIDEV Do you mind to provide the exact config with concrete value for each property, so that I can try to reproduce it locally?

**Comment by joeywashburn** [comment]
I am having the same problem.  As for code you could use 

```
resource "azurerm_storage_account" "example" {
  name                                  = "teststoragaccount"
  resource_group_name       = "testrg"
  location                              = "centralus"
  account_tier                       = "Standard"
  account_replication_type  = "LRS"
  min_tls_version           = "TLS1_2"


  queue_properties {
    logging {
      delete = true
      read = true
      write = true
      version = "1.0"
      retention_policy_days = 10
    }
  }
}
```

I have noticed you will get one of two errors.  Either the error mentioned by the OP.  Or if your storage account already exists, you will get a 404 saying it cant find the resource.

Almost like its looking for the queue to be there and it cant find it.
