### ISSUE TITLE
Documentation: Dead link to "Features" on latest docs

### ISSUE THREAD

**Issue by EnjoyTheNoise** [hashicorp/terraform-provider-azurerm#15524]
Hello,  
since it's not a problem with provider itself, I decided not to use issue template, hope you don't mind :)

On newest [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) **Features** section mentions dedicated page for this block. Sadly the link is dead:  
https://registry.terraform.io/providers/hashicorp/azurerm/latest/features-block

Going back to 2.96 solves the issue, as **Features** is still embedded in main page:  
https://registry.terraform.io/providers/hashicorp/azurerm/2.96.0/docs#features

**Comment by myc2h6o** [comment]
Hi @EnjoyTheNoise Thanks for opening the issue. There seems to be a missing `guides/` in the url, I've created a pr try fixing it.
