### ISSUE TITLE
MySQL flexible server does not accept sku name Standard_B1s

### ISSUE THREAD

**Issue by Ramblurr** [hashicorp/terraform-provider-azurerm#15538]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.18.0
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.20.0
+ provider registry.terraform.io/mrolla/circleci v0.6.1

### Affected Resource(s)

* `azurerm_mysql_flexible_server`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vn"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = "example-sn"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
  delegation {
    name = "fs"
    service_delegation {
      name = "Microsoft.DBforMySQL/flexibleServers"
      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_private_dns_zone" "example" {
  name                = "example.mysql.database.azure.com"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "example" {
  name                  = "exampleVnetZone.com"
  private_dns_zone_name = azurerm_private_dns_zone.example.name
  virtual_network_id    = azurerm_virtual_network.example.id
  resource_group_name   = azurerm_resource_group.example.name
}

resource "azurerm_mysql_flexible_server" "example" {
  name                   = "example-fs"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  administrator_login    = "psqladmin"
  administrator_password = "H@Sh1CoR3!"
  backup_retention_days  = 7
  delegated_subnet_id    = azurerm_subnet.example.id
  private_dns_zone_id    = azurerm_private_dns_zone.example.id
  sku_name               = "Standard_B1s"

  depends_on = [azurerm_private_dns_zone_virtual_network_link.example]
}

```

### Debug Output

https://gist.github.com/Ramblurr/d328244e8ca17480a60bf0a3e6ed2eab

### Expected Behaviour

The module should have accepted the SKU Name `Standard_B1s`.

### Actual Behaviour

It did not accept the sku name
`│ Error: "sku_name" is not a valid sku name, got Standard_B1s`

### Steps to Reproduce

1. List the valid SKUs for mysql flexible server in west europe: `az mysql flexible-server list-skus --location westeurope
`
2. Verify that the SKU `Standard_B1s` exists in the output and matches the `sku_name` in the terraform
3. `terraform apply`

### Important Factoids

The same applies for `Standard_B1ms` and `Standard_B2s`.

### References

n/a

**Comment by johnkoukgit** [comment]
Hi, try prefixing the SKU with the Compute Tier i.e B (Burstable), GP (General Purpose), MO (Memory Optimised).

So in your case, "Standard_B1s" falls within the Burstable Tier, so replace "Standard_B1s" with "B_Standard_B1s".

**Comment by Ramblurr** [comment]
Thanks @stephybun  and @johnkoukgit that was exactly the problem.
