### ISSUE TITLE
Support for setting owner and group property on azurerm_storage_data_lake_gen2_filesystem

### ISSUE THREAD

**Issue by LoW0lf** [hashicorp/terraform-provider-azurerm#15547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In order to properly configure the owning user and owner group (ACL) on a datalake root folder we should have the possibility to configure an AAD object ID for `owner` and `group` on the `azurerm_storage_data_lake_gen2_filesystem` resource analogue to the `azurerm_storage_data_lake_gen2_path` resource. 

### New or Affected Resource(s)

* azurerm_storage_data_lake_gen2_filesystem

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_data_lake_gen2_filesystem" "example" {
  name               = "example"
  storage_account_id = azurerm_storage_account.example.id
  owner = "00000000-0000-0000-0000-000000000000"
  group = "00000000-0000-0000-0000-000000000000"
  ace {
  ....
  }
}
```

**Comment by magodo** [comment]
@LoW0lf Thank you for submitting this! By looking through the [API reference of the data lake gen2 fs](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/filesystem), there seems no mention about the `owner`/`group`. On the other hand, the [API reference of the data lake gen2 path's UPDATE method](https://docs.microsoft.com/en-us/rest/api/storageservices/datalakestoragegen2/path/update#request-headers) has them defined.

Do you know how to do that via the rest API?

**Comment by LoW0lf** [comment]
@magodo as far I understand it, this properties don't have to be set on the filesystem itself but on the "/" root directory that comes along with creation of the filesystem. In the current implementation of the filesystem resource, the ace's defined on the filesystem are deployed in the same way, see https://github.com/hashicorp/terraform-provider-azurerm/blob/d50e6dd1b228363519b9357de8ada98dd3e22a87/internal/services/storage/storage_data_lake_gen2_filesystem_resource.go#L181 

In code mentioned, the owner and group property is set to nil but from my point of view this should be possible to set them analogue to the path resource.
