### ISSUE TITLE
azurerm_eventgrid_system_topic_event_subscription - support delivery_identity

### ISSUE THREAD

**Issue by TobiStr** [hashicorp/terraform-provider-azurerm#15540]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**azurerm_eventgrid_system_topic_event_subscription** does not support **delivery_property** yet.

### New or Affected Resource(s)

* azurerm_eventgrid_system_topic_event_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_eventgrid_system_topic_event_subscription" "example" {
  name                = "example"
  system_topic        = azurerm_eventgrid_system_topic.topic.name
  resource_group_name = azurerm_resource_group.rg.name

  service_bus_topic_endpoint_id = azurerm_servicebus_topic.blobevent.id

  delivery_property {
    header_name  = "url"
    type         = "Dynamic"
    source_field = "data.url"
  }
}
```

### References

* [#12145](https://github.com/hashicorp/terraform-provider-azurerm/issues/12145)
* [#12945](https://github.com/hashicorp/terraform-provider-azurerm/pull/12945)
* [#13595](https://github.com/hashicorp/terraform-provider-azurerm/pull/13595)

**Comment by stephybun** [comment]
Closed by #15559
