### ISSUE TITLE
Support for async azurerm_virtual_machine_extension (skip waiting)

### ISSUE THREAD

**Issue by alisson276** [hashicorp/terraform-provider-azurerm#15555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to have a flag to do NOT wait for the azurerm_virtual_machine_extension runs. 

The only change needed is on https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/virtual_machine_extension_resource.go#L174-L176 and https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/virtual_machine_scale_set_extension_resource.go#L182-L184 (there are other lines we have this, but in creation is the problem right now)

The thing we need is do not wait (and we don't care about the output of the extension, if was successful or not), because it takes a lot of time and doesn't make sense wait for this.

### New or Affected Resource(s)

* azurerm_virtual_machine_extension
* virtual_machine_scale_set_extension

### Potential Terraform Configuration

```go
if not utils.Bool(d.Get("no_wait").(bool)) {
    if err := future.WaitForCompletionRef(ctx, client.Client); err != nil {
	    return fmt.Errorf("waiting for creation of %s: %+v", id, err)
    }
}
```

Something similar to this I think should solve.

**Comment by tombuildsstuff** [comment]
hi @alisson276

Thanks for opening this issue.

One of the core principals of Terraform is to wait for a resource to be fully provisioned before returning that it's completed and so should be tracked in the state, as such unfortunately this isn't something we're planning to add a feature-flag for.

Whilst I can't comment on your particular setup, one approach to speed up the provisioning time of VM's is to install any dependent software (which can also be provisioned using VM Extensions) using a tool like Packer to create an image which allows longer-running tasks to be done once. This means that VM's and VM Scale Sets can be provisioned from this image (and customized using UserData or similar) - which (depending on what you're doing) can both dramatically reduce the provisioning time.

Whilst that approach does involve maintaining VM Images which may be outside of the scope of your current setup, there's other approaches available here too - but unfortunately as this is a core tenant of Terraform this flag isn't something we plan to add to the Provider at the moment and so whilst I'd like to thank you for opening this issue I'm going to close this for the moment.

Thanks!
