### ISSUE TITLE
Docs for `features` blockgives 404

### ISSUE THREAD

**Issue by giraffesyo** [hashicorp/terraform-provider-azurerm#15564]
The link to learn more about the features block at the bottom of the [docs page](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#features) is returning a 404. 

This is the link: https://registry.terraform.io/providers/hashicorp/azurerm/latest/features-block

![image](https://user-images.githubusercontent.com/10459772/155264269-e3e770c0-4139-475e-9c67-78022636fe51.png)

**Comment by mybayern1974** [comment]
@giraffesyo , thanks for opening this issue. Assume there is a duplicate one #15524 that has been addressed. So expect you would see a normal doc link in the upcoming provider release that's expected to include the fix. With that, I'm closing this issue or feel free to suggest if you have different opinions.
