### ISSUE TITLE
Support for desktopvirtualization.sessionHosts - resource `virtual_desktop_session_host `

### ISSUE THREAD

**Issue by hayorov** [hashicorp/terraform-provider-azurerm#15563]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support functionality `desktopvirtualization.sessionHosts` https://docs.microsoft.com/en-us/rest/api/desktopvirtualization/session-hosts/

### New or Affected Resource(s)

* virtual_desktop_host_pool
* virtual_desktop_session_host (new)

### Potential Terraform Configuration
N/a

### References
* https://docs.microsoft.com/en-us/rest/api/desktopvirtualization/session-hosts

**Comment by sinbai** [comment]
@hayorov  thank you for opening this issue. First, I would like to clarify that a valid Terraform candidate should have API to support the resource CRUD: any of the Create/Read/Delete could not be missed. After checking, there is no  create API available for [session host](https://docs.microsoft.com/en-us/rest/api/desktopvirtualization/session-hosts). Hence, sorry to say that terraform could not support the `virtual_desktop_session_host` resource.

**Comment by sinbai** [comment]
@hayorov As far as I know, data resources in terraform are only used to read objects. so the [Session Hosts - Update]( https://docs.microsoft.com/en-us/rest/api/desktopvirtualization/session-hosts/update) could not be supported as a data resource. See the description below for details, ref to https://www.terraform.io/language/data-sources#using-data-sources

> _When distinguishing from data resources, the primary kind of resource (as declared by a resource block) is known as a managed resource. Both kinds of resources take arguments and export attributes for use in configuration, but while managed resources cause Terraform to create, update, and delete infrastructure objects, **data resources cause Terraform only to read objects**. For brevity, managed resources are often referred to just as "resources" when the meaning is clear from context._

**Comment by sinbai** [comment]
@hayorov based on the above context, are you okey if we close this issue?

**Comment by hayorov** [comment]
@sinbai  I mean expose `sesson_host` as a data source resource and some operations from `session_host` like user assignment  (it's possible to simulate CRUD-like operations).

Anyways, it's ok to close the issue.

**Comment by rcskosir** [comment]
Closing per the author above.
