### ISSUE TITLE
azurerm_key_vault_secret support for Enabled/Disabled state

### ISSUE THREAD

**Issue by SenorRagequit** [hashicorp/terraform-provider-azurerm#15578]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description  
Azure offers the ability to enable / disable secrets. It would be great if Terraform could use that as an optional argument too.  
![grafik](https://user-images.githubusercontent.com/50502395/155412835-689349d7-1fbb-4931-af79-cf634a53d213.png)

### New or Affected Resource(s)  
Affected resources: Azure Key Vault (Secrets)

* azurerm_key_vault_secret

### Potential Terraform Configuration
  
```
resource "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.example.id
  enabled  = true / false
}  
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by sinbai** [comment]
@SenorRagequit thank you for opening this issue. A valid terraform candidate should have API to support the resource CRUD: any of the the Create/Read/Delete could not be missed. However, the [Get Secret API (Read)](https://docs.microsoft.com/en-us/rest/api/keyvault/secrets/get-secret/get-secret) is not allowed on a disabled secret. When using it to get a disabled secret, the error  is as follows. Hence, the `enabled` property could not be supported in terraform.

```
{
    "error": {
        "code": "Forbidden",
        "message": "Operation get is not allowed on a disabled secret.",
        "innererror": {
            "code": "SecretDisabled"
        }
    }
}
```

**Comment by sinbai** [comment]
@SenorRagequit for the above context, are you okey if we close this issue?

**Comment by SenorRagequit** [comment]
Yes, please do so.
