### ISSUE TITLE
azurerm_mssql_managed_instance_active_directory_administrator resource forces replacement after every apply

### ISSUE THREAD

**Issue by enorlando** [hashicorp/terraform-provider-azurerm#15619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.5
+ provider registry.terraform.io/hashicorp/azurerm v2.97.0
```

### Affected Resource(s)

* `azurerm_mssql_managed_instance_active_directory_administrator`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_managed_instance_active_directory_administrator" "stg" {
  managed_instance_id = azurerm_mssql_managed_instance.stg.id
  login_username      = "stg"
  object_id           = azuread_group.stg.object_id
  tenant_id           = data.azurerm_client_config.current.tenant_id
} 
```

### Panic Output

N/A

### Expected Behaviour

Azure Active Directory admin should be assigned successfully to the managed instance 

### Actual Behaviour

 ``` # azurerm_mssql_managed_instance_active_directory_administrator.stg must be replaced
-/+ resource "azurerm_mssql_managed_instance_active_directory_administrator" "stg" {
      - azuread_authentication_only = false -> null
      ~ id                          = "/subscriptions/xx/resourceGroups/xx/providers/Microsoft.Sql/managedInstances/stg/administrators/ActiveDirectory" -> (known after apply)
      ~ managed_instance_id         = "/subscriptions/xx/resourceGroups/xx/providers/Microsoft.Sql/managedInstances/stg/administrators/ActiveDirectory" -> "/subscriptions/xx/resourceGroups/xx/providers/Microsoft.Sql/managedInstances/stg" # forces replacement
      ~ object_id                   = <<-EOT
          - �;�b
          - �EW��`�?�
          + xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        EOT
      ~ tenant_id                   = "<ranndom string>" -> "xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. `terraform apply`
3. `terraform plan` 
It wants to perform the actions again to replace the resource. This is true when creating a new resource or importing

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/15203

**Comment by manicminer** [comment]
Hi @enorlando, thanks for reporting this. It looks like there are a couple bugs in the read function for that resource which I believe are causing this. I've opened a PR to address this which should be included in the next release. Thanks!

**Comment by enorlando** [comment]
Thank you for the update @manicminer
