### ISSUE TITLE
Custom DPS policy (with Azure Functions) not supported

### ISSUE THREAD

**Issue by mikebaz** [hashicorp/terraform-provider-azurerm#15616]
Looking at https://github.com/hashicorp/terraform-provider-azurerm/blob/807f0fd916fa81e0cdb3a5c411010c5e5842d59c/internal/services/iothub/iothub_dps_resource.go#L174 and some of the other provider code, it looks like the `allocation_policy` value is the same as passed in the REST call, which presumably is the word "custom".

The provider should support referencing a function as a custom allocator for DPS.

**Comment by manicminer** [comment]
Hi @mikebaz, thanks for requesting this. Unfortunately I'm not sure there is enough context here to work with - would you be able to re-open this using our feature request template and add any relevant docs links for a potential contributor? Thanks!

**Comment by myc2h6o** [comment]
Hi @mikebaz I happened to check this earlier. I guess you are looking at [Create the custom allocation function](https://docs.microsoft.com/en-us/azure/iot-dps/how-to-use-custom-allocation-policies?tabs=windows#create-the-custom-allocation-function). This property is from [enrollmentGroup](https://github.com/Azure/azure-rest-api-specs/blob/d2774322bc5be6fa35945e9c6004b8d34c451732/specification/deviceprovisioningservices/data-plane/Microsoft.Devices/stable/2021-10-01/service.json#L957-L964). The `allocation_policy` you mentioned is from [dps](https://github.com/Azure/azure-rest-api-specs/blob/d2774322bc5be6fa35945e9c6004b8d34c451732/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2020-03-01/iotdps.json#L1860) itself (in the below picture). If the one from enrollmentGroup is what you are looking for, maybe you can mention the above doc link in the feature request. It is using a separate data-plane API for enrollmentGroup so probably we will need a new resource type to support this.
![image](https://user-images.githubusercontent.com/10579712/156283665-7c7f6b9f-2201-4b90-a270-3c75d72fe1c5.png)
