### ISSUE TITLE
azurerm_api_management_api_operation validation is wrong

### ISSUE THREAD

**Issue by davejhahn** [hashicorp/terraform-provider-azurerm#15620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_api_management_api_operation`

### Expected Behaviour

Operation with "_" in the operation_id is created.

### Actual Behaviour

```
Error: "operation_id" may only contain alphanumeric characters and dashes up to 80 characters in length

```

### Steps to Reproduce

Create an operation with the operation_id having "_" in it.   This is a permitted character and can be used when creating operations in the portal.

**Comment by xuzhang3** [comment]
similar issue #15417
