### ISSUE TITLE
Support for endpoint-resource-manager in provider

### ISSUE THREAD

**Issue by MichalKoziorowski-TomTom** [hashicorp/terraform-provider-azurerm#15632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to have feature similar to one from az cli:
```
az cloud update --endpoint-resource-manager https://${params.REGION}.management.azure.com
```

Sometimes, especially when searching for freshly created resources using:
```
data "azurerm_resources" "cluster_security_groups" {
  depends_on = [
    helm_release.ingress
  ]
  resource_group_name = local.mc_res_grp_name
  type = "Microsoft.Network/networkSecurityGroups"
}
```

there is a possibility that if resource was just created in region, e.g. westeurope, querying using `azurerm_resources` and standard endpoint will return no responses, but querying using ${region}.management.azure.com, e.g. westeurope.management.azure.com will return resource correctly. 

I thought that `metadata_host` variable in azurerm provider section will fix that, but it doesn't seem to change endpoint.

Suggestion to use ${region}.management.azure.com to search newly created resources, I've received some time ago from Azure Support.

### New or Affected Resource(s)

* azurerm provider section

### Potential Terraform Configuration

```
provider "azurerm" {
  subscription_id = var.subscription_id
...
...
  endpoint_resource_manager_url = "https://westeurope.management.azure.com" or endpoint_resource_manager_hostname = "westeurope.management.azure.com" or resource_manager_host = "westeurope.management.azure.com" // probably most similar to already existing metadata_host
}
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. Time has passed and this has since been added to the provider. Please upgrade to the latest, thanks!

**Comment by magodo** [comment]
@MichalKoziorowski-TomTom As a workaround, you can try https://github.com/magodo/azure-metadata-proxy
