### ISSUE TITLE
Case difference between Azure RM and terraform state results in continuous destruction/creation

### ISSUE THREAD

**Issue by bandarr** [hashicorp/terraform-provider-azurerm#15635]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* `azurerm_backup_protected_vm`

### Terraform Configuration Files

```hcl
resource "azurerm_backup_protected_vm" "trainer-daily" {
  resource_group_name = azurerm_resource_group.backup.name
  recovery_vault_name = azurerm_recovery_services_vault.training-compute.name
  source_vm_id        = azurerm_windows_virtual_machine.trainer.id
  backup_policy_id    = azurerm_backup_policy_vm.trainer-daily.id
}
```
### Expected Behaviour

Terraform ignores resource group case for the VM associated with the azurerm_backup_protected_vm

### Actual Behaviour

Terraform sees resource group case differences as a reason to create and destroy the azurerm_backup_protected_vm.

"#azurerm_backup_protected_vm.trainer-daily must be replaced
~ source_vm_id        = "/subscriptions/#########-####-####-####-############/resourceGroups/rg-**trainingcompute**/providers/Microsoft.Compute/virtualMachines/vm-Trainer" -> "/subscriptions/#########-####-####-####-############/resourceGroups/rg-TrainingCompute/providers/Microsoft.Compute/virtualMachines/vm-Trainer"   # forces replacement"

### Steps to Reproduce

1. single-case resource group name for VM (in this case, all upper appears to get translated to all lower)
2. `terraform plan`

### Important Factoids

No important factoids. 

### References
None

**Comment by myc2h6o** [comment]
Hi @bandarr There is a known bug on the API side, where the `source_vm_id` is not same with the input but the name of resource_group/virtual_machine in their own case: https://github.com/Azure/azure-rest-api-specs/issues/10357.
Since that issue has been there for a long time, I've created a pr to make it case-insensitive while waiting for the issue on API side to be addressed
