### ISSUE TITLE
Support for Azure Dedicated Host (ADH) based nodepools in AKS resource (azurerm_kubernetes_cluster)

### ISSUE THREAD

**Issue by ronaknnathani** [hashicorp/terraform-provider-azurerm#15658]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AKS team recently released a [public preview for ADH backed nodepools on AKS](https://docs.microsoft.com/en-us/azure/aks/use-azure-dedicated-hosts). Many teams, including ours, rely on Terraform to bootstrap AKS and we'd like to leverage ADH backed nodepools on AKS while continuing to use Terraform. 

This issue requests adding support for ADH backed nodepools in `azurerm_kubernetes_cluster` and `azurerm_kubernetes_cluster_node_pool` resources.

### New or Affected Resource(s)
* azurerm_kubernetes_cluster
* azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration
```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
    host_group_id = <ADH host group ID>
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1
  host_group_id = <ADH host group ID>

  tags = {
    Environment = "Production"
  }
}
```

### References
https://docs.microsoft.com/en-us/azure/aks/use-azure-dedicated-hosts

**Comment by ronaknnathani** [comment]
cc: @grayzu

**Comment by tombuildsstuff** [comment]
This isn't in the current API version we're using, whilst I haven't dig into #15648 - presumably this is dependent on #15648

**Comment by Swaroo** [comment]
Hi, Is there any update on this feature request?

Thank you

**Comment by swgriffith** [comment]
Any update on this one? Looks like #15648 was merged.
