### ISSUE TITLE
Cannot attach the Virtual Network for azurerm_hdinsight_kafka_cluster and azurerm_hdinsight_spark_cluster

### ISSUE THREAD

**Issue by sekasara** [hashicorp/terraform-provider-azurerm#15669]
### Description

I cannot attach the **Virtual Network** into **azurerm_hdinsight_kafka_cluster** and **azurerm_hdinsight_spark_cluster** via terraform.
But I can achieve this using Azure Portal. Can anyone help on this ?

![image](https://user-images.githubusercontent.com/63733959/156375234-cd9482cd-e88b-444e-a462-458b664ddfc7.png)

**Comment by neil-yechenwei** [comment]
@sekasara , thanks for raising this issue. Actually, this feature has already been implemented by TF. In TF, you can use [`virtual_network_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_spark_cluster#virtual_network_id) for this feature. If it meets your requirement, is it ok to close this issue?

**Comment by rcskosir** [comment]
Thank you for opening this issue. Since the feature [virtual_network_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_spark_cluster#virtual_network_id) exists, I am going to mark this issue as complete.
