### ISSUE TITLE
Data source azurerm_active_directory_domain_service does not export initial_replica_set

### ISSUE THREAD

**Issue by djryanj** [hashicorp/terraform-provider-azurerm#15680]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```sh
Terraform v1.1.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.93.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* data `azurerm_active_directory_domain_service`
* Unknown if this applies to the resource as well or just the data source.

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "rg1"
  location = "East US"
}

data "azurerm_active_directory_domain_service" "this" {
  name                = "aadds.internal"
  resource_group_name = azurerm_resource_group.this.name
}

resource "azurerm_virtual_network" "this" {
  name                = "vnet1"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  address_space       = ["10.0.0.0/16"]
  dns_servers         = data.azurerm_active_directory_domain_service.this.initial_replica_set.domain_controller_ip_addresses
}
```

### Panic Output

None

### Expected Behaviour

Successful `plan` or `apply`.

### Actual Behaviour

During `terraform plan` or `apply`:

```hcl
Error: Unsupported attribute
│
│    6:   dns_servers         = data.azurerm_active_directory_domain_service.this.initial_replica_set.domain_controller_ip_addresses
│
│ This object has no argument, nested block, or exported attribute named "initial_replica_set".
```

1. Create required `.tf` files, vars, etc.
2. Create AADDS resource in Azure.
3. `terraform plan` or `terraform apply`

### Important Factoids

If I switch to using `data.azurerm_active_directory_domain_service.this.replica_sets[0].domain_controller_ip_addresses` it works.

This might just be a documentation problem.

**Comment by manicminer** [comment]
Hi @djryanj, thanks for reporting this. You are correct that this is a documentation issue - for the data source we intentionally don't differentiate between the initial replica set and any additional ones, since it's not possible to infer the intent with the topology from the API responses in the same way we can when using the resource.
