### ISSUE TITLE
The following policy definition reference Is used in non-compliance messages do not exist in the assigned policy set definition

### ISSUE THREAD

**Issue by masonhuemmer** [hashicorp/terraform-provider-azurerm#15685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.5
* AzureRM Provider version: 2.98.0

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Description / Feedback

When referencing the `azurerm_policy_definition.example.id` in the non-compliance block of `azurerm_management_group_policy_assignment.example`, terraform should be provisioning the policy assignment resource.

Instead, it is throwing the following error: 

Error: creating Policy Assignment ID: (Assignment Name "assignment_name" / Scope "`/providers/Microsoft.Management/managementGroups/my_management_group`"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidCreatePolicyAssignmentRequest" Message="The policy assignment request is invalid. The following policy definition reference IDs used in non-compliance messages do not exist in the assigned policy set definition: `/providers/Microsoft.Management/managementGroups/my_management_group/providers/Microsoft.Authorization/policyDefinitions/Policy A`"

**Comment by masonhuemmer** [comment]
In the state file, I see there is a reference Id in the `azurerm_policy_set_definition` resource.
First, is this the reference ID that is required? 
Second, Is there any easier way of fetching the ID?

**Comment by lonegunmanb** [comment]
Hi @masonhuemmer , thanks for opening this issue, I'd like to help you, would you please give a minimum code snippet that can reproduce this issue? Thanks a lot!

**Comment by lonegunmanb** [comment]
Hello @masonhuemmer , any chance to provide a minimum sample code that can reproduce will be appreciated!

**Comment by lonegunmanb** [comment]
Hello @masonhuemmer , would you please provide a sample code so we can reproduce this issue? Thanks.

**Comment by masonhuemmer** [comment]
We can close this case.

**Comment by lonegunmanb** [comment]
@masonhuemmer thanks for your reply, glad to hear that. Would you please close this issue? Thanks!
