### ISSUE TITLE
The terraform-provider-azurerm_v2.95.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by aledeniz** [hashicorp/terraform-provider-azurerm#15712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.6 on windows_amd64
terraform-provider-azurerm_v2.95.0_x5.exe
backend: azurerm

### Affected Resource(s)

Not relevant.

### Terraform Configuration Files

Not relevant.

### Debug Output

https://gist.github.com/aledeniz/6e5ac1682375c249aa69ae12200665b8

### Panic Output

N/A

### Expected Behaviour

Please note I am reporting this only because the output stated _This is always indicative of a bug within the plugin. It would be immensely helpful if you could report the crash with the plugin's maintainers_.

The scenario is a build server with 5 build agents (Azure Pipeline) being hit by 10 builds. The builds are for 10 different environments (each on its own resource group), only Azure resources.
In total, across the 10 builds: 14 VMs, 14 virtual network interfaces, ~100 managed disks and their attachments, 14x3 extensions (encryption with ADE, SQL VM and Domjoin), 3 virtual networks, 3 key vaults, across 3 subscriptions). 
The 10 builds are quite similar (2 stages each, the first init and validate, the second init and plan).

### Actual Behaviour

One of the 10 builds return error code 1 and printed the output reported in the gist. The issue materialised during a terraform plan.
I looked at the build server metrics, during the peak of the 10 builds the cpu utilization was between 55% and 95%, the memory usage between 70% and 80%. A bit of pressure, but not stressed.
Similar behaviour when I replicated the scenario a few minutes later.
In an ideal world, that build should have been successful.
I did run the single failing build on its own a few minutes later, and it worked successfully.
I did replicate the same scenario (10 builds hitting that build server at the same time) a few minutes later, and all the build completed successfully.

### Steps to Reproduce

N/A

### Important Factoids

N/A

### References

N/A

**Comment by manicminer** [comment]
Hi @aledeniz, thanks for taking the time to report this crash. Looking at the stack trace, and based on your description of your runtime environments, it seems like Terraform ran out of memory during this plan. We don't officially support running Terraform in memory constrained environments, notably this can cause problems during a crash and might leave your statefile and infrastructure in an unpredictable state. In this case, although you may have only recorded an average 80% utilization, a spike beyond this could feasibly be absorbed by averaging, even over a short sample period, and so I would recommend scaling up your agent VM(s).

Thanks again for reporting, we appreciate every crash report as it helps us better understand behavior in different environments and identify potential bugs in the provider. As this seems to be largely an environment issue, I don't think there's any further action for us and accordingly I'm going to close this one for now.

**Comment by manicminer** [comment]
@aledeniz This appears to be the same issue, i.e. running out of memory
