### ISSUE TITLE
Support for Log Analytics Query Packs ETA

### ISSUE THREAD

**Issue by andyjballgit** [hashicorp/terraform-provider-azurerm#15710]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://docs.microsoft.com/en-us/azure/azure-monitor/logs/query-packs
### New or Affected Resource(s)

ETA For support of Log Analytics Query Packs (I know its preview)
https://docs.microsoft.com/en-us/azure/azure-monitor/logs/query-packs

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by Lachlan-White** [comment]
Believe this is now available in v3.16.0:
https://github.com/hashicorp/terraform-provider-azurerm/pull/17685
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_query_pack

And additional capability in v3.21.0:
https://github.com/hashicorp/terraform-provider-azurerm/issues/17929
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_query_pack_query
