### ISSUE TITLE
azurerm_postgresql_flexible_server_database does not complete destroy before subnet

### ISSUE THREAD

**Issue by anniehedgpeth** [hashicorp/terraform-provider-azurerm#15728]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```
### Affected Resource(s)

* `azurerm_postgresql_flexible_server_database`

### Terraform Configuration Files

This change [here](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/156/files) was necessary in order to add the necessary database extensions. 
```hcl
resource "azurerm_postgresql_flexible_server_database" "tfe" {
  name      = var.database_name
  server_id = azurerm_postgresql_flexible_server.tfe.id
  collation = "en_US.utf8"
  charset   = "utf8"
}
```

### Expected Behaviour

When [this change](https://github.com/hashicorp/terraform-azurerm-terraform-enterprise/pull/156/files#diff-573953a4f9e14abea2d1ace2029942ca8404db6e9dcfd76c5540a3361d75c905R23-R34) was introduced, which adds a database explicitly as opposed to relying upon the default database created, we expected no change in the destroy order as nothing really changed. We even used the default values for the `azurerm_postgresql_flexible_server_database`.

### Actual Behaviour

What actually happened is that, about half the time, the database never destroyed in time, and the tests would fail with:

```
│ Error: deleting Subnet: (Name "gmiu-database-subnet" / Virtual Network Name "gmiu-network" / Resource Group "gmiu-rg"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet gmiu-database-subnet is in use by /subscriptions/************************************/resourceGroups/gmiu-rg/providers/Microsoft.Network/virtualNetworks/gmiu-network/subnets/gmiu-database-subnet/serviceAssociationLinks/gmiu-database-subnet-service-association-link and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
```

### Steps to Reproduce

Create a module with a VNET, Subnet, azurerm_postgresql_flexible_server, and azurerm_postgresql_flexible_server_database. Apply and destroy several times and watch how many times the race condition allows for the destroy of the azurerm_postgresql_flexible_server_database to not complete before TF tries to destroy the subnet.

**Comment by neil-yechenwei** [comment]
@anniehedgpeth , thanks for raising this issue. This is a known issue at Service Backend. I assume this issue has been fixed. So new resource created wouldn't encounter this issue again. So I didn't encounter this issue with below tf config that is similar with yours. For existing resource hiting this issue, you have to submit Azure Ticket (Help+Support) to delete them.

![image](https://user-images.githubusercontent.com/19754191/157384667-0aab2017-4c3f-42e5-84b4-6a3e1f66d54d.png)

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-postgresqlfs-test10"
  location = "West Europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctest-vn-test10"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "acctest-sn-test10"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]

  delegation {
    name = "fs"

    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"

      actions = [
        "Microsoft.Network/virtualNetworks/subnets/join/action",
      ]
    }
  }
}

resource "azurerm_private_dns_zone" "test" {
  name                = "acctest10.postgres.database.azure.com"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_private_dns_zone_virtual_network_link" "test" {
  name                  = "acctestVnetZonetest10.com"
  private_dns_zone_name = azurerm_private_dns_zone.test.name
  virtual_network_id    = azurerm_virtual_network.test.id
  resource_group_name   = azurerm_resource_group.test.name
}

resource "azurerm_postgresql_flexible_server" "test" {
  name                   = "acctest-postgresqlfs-test10"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  administrator_login    = "bdminTerraform"
  administrator_password = "JAZwsx123"
  version                = "13"
  backup_retention_days  = 7
  storage_mb             = 32768
  sku_name               = "GP_Standard_D2s_v3"
  zone                   = "1"
  delegated_subnet_id    = azurerm_subnet.test.id
  private_dns_zone_id    = azurerm_private_dns_zone.test.id

  depends_on = [azurerm_private_dns_zone_virtual_network_link.test]
}

resource "azurerm_postgresql_flexible_server_configuration" "test" {
  name      = "backslash_quote"
  server_id = azurerm_postgresql_flexible_server.test.id
  value     = "on"
}

resource "azurerm_postgresql_flexible_server_database" "tfe" {
  name      = "acctest-postgresqlfsdb-test10"
  server_id = azurerm_postgresql_flexible_server.test.id
  collation = "en_US.utf8"
  charset   = "utf8"
}
```

**Comment by anniehedgpeth** [comment]
Yeah, you're right, @neil-yechenwei - looks like an Azure API issue. But I created the issue because not being able to consistently destroy the resource really does render it unusable.

**Comment by tombuildsstuff** [comment]
@neil-yechenwei we should look to fix this by adding a custom poller, since this should work reliably

**Comment by anniehedgpeth** [comment]
We were looking into the subnet destroy failures a little more and just noticed that every time the subnet destroys failed, it was because the apply failed to completely create the `azurerm_postgresql_flexible_server`:
```
│ Error: waiting for creation of the Postgresql Flexible Server "mwiu-pg" (Resource Group "mwiu-rg"): Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
```

When Terraform successfully creates the server, the destroy succeeds. So @sudomateo suggested that perhaps since Terraform timed out after 60 minutes creating the database server, it doesn't track it in state and then during destroy, doesn't even try to destroy it (because from its perspective it never was successfully created).

**Comment by neil-yechenwei** [comment]
Service team confirmed that the root cause is service backend failed to delete the SAL so that the custom poller cannot resolve this issue and it has to be resolved from service backend for existing server hiting this issue.

**Comment by anniehedgpeth** [comment]
@neil-yechenwei and/or @tombuildsstuff , do you have a suggestion of who to talk to or where else to submit a ticket so that I can try and get this escalated? (Feel free to Slack or email me to continue the conversation.)

**Comment by neil-yechenwei** [comment]
Hopes this [doc](https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request) is helpful.

**Comment by anniehedgpeth** [comment]
Thanks, @neil-yechenwei , I've already done that, so good to know I was on the right track.

**Comment by rcskosir** [comment]
@anniehedgpeth Thanks for taking the time to open this issue. As @neil-yechenwei said:

> Service team confirmed that the root cause is service backend failed to delete the SAL so that the custom poller cannot resolve this issue and it has to be resolved from service backend for existing server hiting this issue.

Since creating a support ticket with Azure is the way to handle this for existing resources and it is no longer a problem for new resources. I am going to mark this issue as closed, since there is no work to be done on our side.
Thanks again and I hope your Azure support ticket was able to get this resolved for you!
