### ISSUE TITLE
Diagnostic Settings not destroyed correctly and not added to tfstate.

### ISSUE THREAD

**Issue by Antuuu** [hashicorp/terraform-provider-azurerm#15734]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `azurerm_2.98.0`
* `Terraform 1.1.7`

### Affected Resource(s)
* `azurerm_monitor_diagnostic_setting`

### Terraform Configuration Files

```hcl
resource "random_integer" "id" {
  keepers = {
    # Generate a new id each time we switch to a new AMI id
    ami_id = "${var.ami_id}"
  }

  min = 4000
  max = 5000
}

resource "azurerm_monitor_diagnostic_setting" "diag_settings" {
  name                       = "${var.diagnostic_setting_name}-${random_integer.id.result}"
  target_resource_id         = var.target_resource_id
  log_analytics_workspace_id = var.log_analytics_workspace_id

  dynamic "log" {
    for_each = [for category, enabled in var.diagnostic_settings_logs : {
      category = category
      enabled  = enabled
      }
    ]

    content {
      category = log.value.category
      enabled  = log.value.enabled

      retention_policy {
        enabled = log.value.enabled
        days    = log.value.enabled ? var.days_in_log_analytics : 0
      }
    }
  }

  dynamic "metric" {
    for_each = [for category, enabled in var.diagnostic_settings_metrics : {
      category = category
      enabled  = enabled
      }
    ]

    content {
      category = metric.value.category
      enabled  = metric.value.enabled

      retention_policy {
        enabled = metric.value.enabled
        days    = metric.value.enabled ? var.days_in_log_analytics : 0
      }
    }
  }
}

resource "azurerm_monitor_diagnostic_setting" "diag_settings_archive" {
  name               = "${var.diagnostic_setting_name}_archive-${random_integer.id.result}"
  target_resource_id = var.target_resource_id
  storage_account_id = var.storage_account_id

  dynamic "log" {
    for_each = [for category, enabled in var.diagnostic_settings_logs : {
      category = category
      enabled  = enabled
      }
    ]

    content {
      category = log.value.category
      enabled  = log.value.enabled

      retention_policy {
        enabled = log.value.enabled
        days    = log.value.enabled ? var.days_in_archive : 0
      }
    }
  }

  dynamic "metric" {
    for_each = [for category, enabled in var.diagnostic_settings_metrics : {
      category = category
      enabled  = enabled
      }
    ]

    content {
      category = metric.value.category
      enabled  = metric.value.enabled

      retention_policy {
        enabled = metric.value.enabled
        days    = metric.value.enabled ? var.days_in_archive : 0
      }
    }
  }
}

```

### Debug Output

│ Error: creating Monitor Diagnostics Setting "primary_diagnostic_settings-4642" for Resource "/subscriptions//providers/Microsoft.Sql/servers": insights.DiagnosticSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="Conflict" Message="Data sink '//providers/Microsoft.OperationalInsights/workspaces/log-analitycs-workspace' is already used in diagnostic setting 'primary_diagnostic_settings-4028' for category 'InstanceAndAppAdvanced'. Data sinks can't be reused in different settings on the same category for the same resource."

 Error: A resource with the ID "database/providers/microsoft.insights/diagnosticSettings/primary_diagnostic_settings_archive" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
│ 
│   with module.databases.module.questionnaire_service_db_monitor_diagnostic_setting.azurerm_monitor_diagnostic_setting.diag_settings_archive,
│   on ../../modules/azure/monitor-diagnostic-setting/main.tf line 43, in resource "azurerm_monitor_diagnostic_setting" "diag_settings_archive":
│   43: resource "azurerm_monitor_diagnostic_setting" "diag_settings_archive" {

### Actual Behaviou
1. `terraform apply`

1.) Create environment- 10 databases with diagnostic settings with terraform apply.
2.) Run tests
3.) Destroy environment with terrafrom destroy.
4.) Repeat the process next day.

### Actual Behaviour

I am creating and destroying environment once a day. It looks like there is some issue in database diagnostic settings- even when I add specific ID to the name diag settings cannot be created. Without adding this ID there was issue with destroying- it looks like diagnostic settings was not removed correctly and I needed to add it to .tfstate manually.

1.) Create environment- 10 databases with diagnostic settins with terraform apply.
2.) Run tests
3.) Destroy environment with terrafrom destroy.
4.) New environment cannot be created because of describe issue.

### Steps to Reproduce

1. `terraform apply`
2.  `terraform destroy`
3.  `terraform apply`

**Comment by myc2h6o** [comment]
Hi @Antuuu I've tried this by myself with `target_resource_id` set to `/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myrg/providers/Microsoft.Sql/servers/sqlservername/databases/master` (I found the ID from Azure Portal https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/diagnosticsLogs) and it works fine, I verified that the diagnostic settings has been removed from the Portal after I run `terraform destroy` and I'm able to run `terraform apply` after that.

From the description, I think there is some issue with the `terraform destroy`, could you check if there is any error when running it and if the diagnostic settings is removed after you run `terraform destroy`?

**Comment by Antuuu** [comment]
> Hi @Antuuu I've tried this by myself with `target_resource_id` set to `/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/myrg/providers/Microsoft.Sql/servers/sqlservername/databases/master` (I found the ID from Azure Portal https://ms.portal.azure.com/#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/diagnosticsLogs) and it works fine, I verified that the diagnostic settings has been removed from the Portal after I run `terraform destroy` and I'm able to run `terraform apply` after that.
> 
> From the description, I think there is some issue with the `terraform destroy`, could you check if there is any error when running it and if the diagnostic settings is removed after you run `terraform destroy`?

There is no issue in terraform destroy on my side. Even If destroy is succesfull I can see this diagnostic settings in Azure Monitor, if I open one of them I can see 404 resource doesn't exist.

**Comment by tombuildsstuff** [comment]
@Antuuu that's a caching bug in the Azure Portal rather than a bug in Terraform unfortunately.

Since this is a bug in the Azure Portal rather than a bug in Terraform I'm going to close this issue for the moment, but I'd recommend reaching out to Azure Support here since this is a bug they'd need to fix in the Portal (and can be worked around by force-refreshing the browser a number of times)

Thanks!
