### ISSUE TITLE
Unable to use MSI authentication with Azure CLI on App Service Linux

### ISSUE THREAD

**Issue by RyDoug** [hashicorp/terraform-provider-azurerm#15746]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.94.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Affected Resource(s)

App Services Linux
MSI Authentication using Azure CLI

# Terraform Configuration Files

[terraform.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/8207877/terraform.zip)

### Debug Output
https://gist.github.com/RyDoug/f5a070432242abb02a51dec3165f5165

### Expected Behaviour

According to the documentation we should be able to specify the MSI endpoint using ARM_MSI_ENDPOINT to use MSI authentication with Azure CLI and this resource provider.  Since app services MSI endpoint is different than with other resources.

- Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity#configuring-with-environment-variables

- The example I am testing with just creates a new resource group:
-- Reference: https://docs.microsoft.com/en-us/azure/developer/terraform/create-resource-group?tabs=azure-cli
-- This example works in Container Instances without issue.  Presumably because Container Instances is using a well-known MSI endpoint.

### Actual Behaviour

Azure rm thinks that I am using a Service Principal and exits with the error as seen in the gist shared above.

### Steps to Reproduce

I have created a custom container with Azure CLI and Terraform preinstalled.  It has the example project in /app/terraform.

- rydoug/terraform-test:latest

- Create a new App Service Linux using the above custom container
-- You can use any container, but ensure it has Azure CLI and Terraform preinstalled, and SSH enabled.
-- You can also use a blessed image from App Service Linux and install these manually, but you will lose progress if you need to restart.
- Enable MSI on the App Service.
-- I have tried both User and System assigned.
- Browse to <sitename>.scm.azurewebsites.net/webssh/host
- az login --identity
- cd /app/terraform
- export ARM_MSI_ENDPOINT=$MSI_ENDPOINT
- export ARM_USE_MSI=true
-- in my use case when testing this on container instances, I also need to specify ARM_SUBSCRIPTION_ID.  However, we never get to that point to need it on App Services.
- terraform plan -out main.tfplan

### Important Factoids

When setting the ARM_MSI_ENDPOINT I am just specifying MSI_ENDPOINT as this is the environment var for the MSI endpoint according to the docs.
- Reference: https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=portal%2Cdotnet#rest-endpoint-reference

### References
#5558

**Comment by tombuildsstuff** [comment]
hi @RyDoug 

Thanks for opening this issue.

Unfortunately MSI Authentication in App Service and Function Apps isn't supported at this time, as you've mentioned https://github.com/hashicorp/terraform-provider-azurerm/issues/5558 is tracking support for this - as such rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one, would you mind subscribing to that issue for updates?

Thanks!
