### ISSUE TITLE
Support for CosmosDb Mongo v4.2

### ISSUE THREAD

**Issue by MrImpossibru** [hashicorp/terraform-provider-azurerm#15765]
Microsoft released MongoDb v4.2 for CosmosDb. But it isn't supported yet by azurerm.

`expected mongo_server_version to be one of [3.2 3.6 4.0], got 4.2`

https://devblogs.microsoft.com/cosmosdb/azure-cosmos-db-api-for-mongodb-v4-2-is-here-three-reasons-to-upgrade-now/

Could you, please, add a new version to the list? Thanks.

**Comment by polys** [comment]
Please, could you look into this now that v3 is out?
Is it simply a matter of adding the version to an allow-list or it's more involved?

**Comment by Noel-Jones** [comment]
Having come across the same issue I could look at updating the version list that is checked. However, I think we should look into what checking is done by the Microsoft Rest API and whether the (assumed) hard coded list can be removed from Terraform so that we do not need to make similar changes in the future.

**Comment by tombuildsstuff** [comment]
@Noel-Jones we wouldn't remove the hard-coded list here, since the API returns 500's when it's unset - in this case a new API version is required which hasn't got an Azure SDK release, which is being tracked here: https://github.com/Azure/azure-sdk-for-go/issues/17390#issuecomment-1081613378

**Comment by Noel-Jones** [comment]
Thanks @tombuildsstuff fair enough with the hard coded list. I checked though the links and the one you give says that the swagger has been released. and refers to 2021-10-15 which I believe is the rest API in use. Bearing this in mind I added v4.2 to the enum and tested it on our dev subscription. I was able to upgrade our 3.6 to 4.2. I think I could therefore raise a PR?

**Comment by rcskosir** [comment]
@MrImpossibru Thank you for taking the time to open this issue. Based on [the current documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account) it looks like 4.2 is supported. As such, I am going to mark this issue as resolved. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
