### ISSUE TITLE
Documentation on output attributes of backend_address_pool (and other) blocks is incomplete in azurerm_application_gateway

### ISSUE THREAD

**Issue by djryanj** [hashicorp/terraform-provider-azurerm#15770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0

### Affected Resource(s)

* `azurerm_application_gateway` -> `backend_address_pool`
* Possibly other blocks in `azurerm_application_gateway`

### Terraform Configuration Files

N/A

### Debug Output

None

### Panic Output

None

### Expected Behaviour

The documents should identify that the `name` attribute of a `backend_address_pool` is available.

### Actual Behaviour

The documents DO NOT identify that the `name` attribute of a `backend_address_pool` is available. Reading the code, I presume that many of the blocks also export `name` but it's not mentioned in the docs.

### Steps to Reproduce

1. Read the docs
2. Cry
3. Read the code
4. Hmm, it seems to be there
5. Try to access the `name` attribute
6. OMG it IS there!
7. oldmanyellsatcloud.jpg

### Important Factoids

I still love you guys.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#backend_address_pool

**Comment by tombuildsstuff** [comment]
hey @djryanj 

Thanks for opening this issue.

Within the documentation all fields which can be configured as arguments are also available as attributes - as such whilst this is listed on this page it's not particularly clear:

![Screenshot 2022-03-09 at 18 18 42](https://user-images.githubusercontent.com/666005/157495603-708cfe98-4a1c-49fa-a4c0-b203f4d5c310.png)

![Screenshot 2022-03-09 at 18 19 18](https://user-images.githubusercontent.com/666005/157495696-bc2245cd-a197-4adf-bb07-7948b3c1e739.png)

Within some other resources we've started moving towards using the phrasing `In addition to the arguments above, the following attributes are exported:` - but we've not managed to roll this out across all resources yet, but I believe that'd probably help with this.

Thanks!

**Comment by djryanj** [comment]
@tombuildsstuff - yeah, that could be clearer for sure.

I would still rather see a full list, as verbose as it nay be, rather than an (implied) reference, because bouncing around in documents is not my preferred way of reading them, though I can certainly see why you would choose one over the other.

I look forward to seeing the updates.
