### ISSUE TITLE
Azure Flexible Server for MySQL 5.7 

### ISSUE THREAD

**Issue by jamie-sweeney** [hashicorp/terraform-provider-azurerm#15776]
There are two issues observed which should be very easy to reproduce using the published example code which I link and reference below.

### Main Issue:  
Creating a 'ZoneRedundant' HA server-set does not succeed in the 'East US 2' region. 
the same  [ minus region delta ]  TF code run in 'East US' results in a running HA instance of type **ZoneRedundant**. 
When run in eastus2 the resulting server appears as "**SameZone**" 

Using the standard TF example code -> [mysql_flexible_server#example-usage](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#example-usage)

change rg  from "location = "West Europe"  to location = "East US 2"
and add the block
```
  high_availability {
    mode = "ZoneRedundant"
  }
```
to the "azurerm_mysql_flexible_server" "example" resource, and run terraform plan & terraform apply. The resulting resource  appears as SameZone, despite  the fact that TF plan shows it planning/configuring as ZoneRedundant. 

Again the correct result was achieved in useast and uswest2 but not useast2. 

Confirmed that US East 2 is available for Zone redundant HA
https://docs.microsoft.com/en-us/azure/mysql/flexible-server/overview#azure-regions

### 2nd Issue:
In debugging above we attempted to specifically specify the [standby_availability_zone](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#standby_availability_zone) option for HA without change.

BUT when we also add/added the optional [zone](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#zone)  option we always get a 

`Error: waiting for creation of Flexible Server: (Name "example-fs" / Resource Group "example-resources"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: xxxxx`

and can not create a Flex server.  Tested with zone = 1 and = "1"  [ & 2 etc.. just string vs int delta meant here ] 

all above was tested with TF 14.2 and 1.0 and using latest provider 2.98.0 and 2.91.0

**Comment by neil-yechenwei** [comment]
@jamie-sweeney , thanks for raising this issue. Could you share your error message for your above Main Issue? If the error message is like below this, I assume it's caused by Azure Capacity Limitation and the 2nd Issue is also caused by Azure Capacity Limitation.

Error message:
```
│ Error: waiting for creation of Flexible Server: (Name "xxxx" / Resource Group "xxxx"): Code="SubscriptionHasNoAvailabilityZone" Message="The subscription {0} does not have any availability zone in region {1}."
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed and based on @neil-yechenwei's comment, I am going to mark this issue closed. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!
