### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by charles-hay** [hashicorp/terraform-provider-azurerm#15772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* Documentaion

### Expected Behaviour

The sentence at [line 44](https://github.com/hashicorp/terraform-provider-azurerm/blob/b0c897055329438be6a3a159f6ffac4e1ce958f2/website/docs/r/role_definition.html.markdown#L44) states `The scope at which the Role Definition applies too, such as...` the `too` should be `to`.

**Comment by stephybun** [comment]
Closed by #15773
