### ISSUE TITLE
No provider "azurerm" plugins meet the constraint "= 2.60.0" on terraform 0.12.20

### ISSUE THREAD

**Issue by aviksamanta1986** [hashicorp/terraform-provider-azurerm#15778]
I am trying to use a newer azure provider version, but while using 2.60.0, I get get this error message. When I use 2.50.0, I don't get the error message and the provider plugin downloads. From what I understand, 2.X provider versions are supported on 0.12. Why do I get this error on a newer provider version then?

**Comment by tombuildsstuff** [comment]
hi @aviksamanta1986 

At this point in time we'd recommend upgrading to the latest version of Terraform (1.1) which contains many bug fixes, new features and enhancements - and also supports versions of the AzureRM well into the future.

Thanks!
