### ISSUE TITLE
Documentation app_service_plan does not define valid sku tier and size or where to find them.

### ISSUE THREAD

**Issue by samrueby** [hashicorp/terraform-provider-azurerm#15808]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On the [documentation page for app_service_plan](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_plan), the valid choices for sku's tier and size are not defined. Additionally, it does not describe where to find them. Because of this, it is difficult for beginners to know what the valid values are.

**Comment by jackofallops** [comment]
Hi @samrueby - This resource is going to be deprecated in the next release of the provider, I can recommend taking a look at the resource that is superseding it which takes a simpler approach to the SKU specification, and has all the currently supported SKU's detailed on the documentation page [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan#sku_name). This resource will be promoted out of Beta to GA with the release of 3.0 later this week.

Hope this helps.
