### ISSUE TITLE
Unable to create App Service with Docker image

### ISSUE THREAD

**Issue by H4D53** [hashicorp/terraform-provider-azurerm#15805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7 on linux_amd64

### Affected Resource(s)

App_Service
AzureRM v2.99.0

### Terraform Configuration Files

https://gist.github.com/H4D53/69e38dfeba27c534fe37cb075321c6fd

### Debug Output

https://gist.github.com/H4D53/07c649e803e8875ff63803141f892298

### Panic Output

null
### Expected Behaviour

define the app service created with docker from Azure Container Registry
accept the input value from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#site_config has shown

### Actual Behaviour

poped out this error https://gist.github.com/H4D53/07c649e803e8875ff63803141f892298

### Steps to Reproduce
create an app service with docker

please run the code I provide, you may ignore line 3, line 8 of reading local file container_registry.ts and modify line 43 - 45  the docker registry server URL , username and password

**Comment by jackofallops** [comment]
Hi @H4D53 - It appears that block of config should be enclosed in `[]`, and uses camelCase names e.g.

```typescript
siteConfig: [{
                linuxFxVersion: "DOCKER|mydemotestapp.azurecr.io/app:latest",
                alwaysOn: true,
                healthCheckPath: "/health",
            }]
```

However, if you are able to update to the latest CDKTF I think your config should work as is. (Reference: https://www.terraform.io/cdktf/release/upgrade-guide-v0-7#simplify-provider-api-surface)

Hope that helps.
