### ISSUE TITLE
azurerm_kubernetest_cluster: key_vault_secrets_provider has landed in Azure China, however doc mentions it's not supported

### ISSUE THREAD

**Issue by riiikawang** [hashicorp/terraform-provider-azurerm#15818]
I tested with Azure CLI about the add-on "key_vault_secrets_provider" following doc https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver, both new-cluster creation and existing-cluster upgrading could work in Azure China:

Upgrade an existing cluster in Azure China:

![image](https://user-images.githubusercontent.com/77219080/158090693-71e5887f-75bd-46ea-9583-ffe083b74d00.png)
![image](https://user-images.githubusercontent.com/77219080/158090657-d127e6bb-eeec-4aa2-87e6-ac3b3bef1136.png)

Create a new cluster in Azure China:
![image](https://user-images.githubusercontent.com/77219080/158090737-71e0b484-01da-4ea7-8b59-cf786b8f0dbf.png)
![image](https://user-images.githubusercontent.com/77219080/158090756-165f3efc-94d9-4883-8c97-653203e7578d.png)

However it's said the add-on is not supported in Azure China at this time:
![image](https://user-images.githubusercontent.com/77219080/158090846-82fac632-ad21-427f-b3ea-fb898c90d93d.png)

Could you please verify it? Thanks.

**Comment by riiikawang** [comment]
May I know if any plan recently to make this enhancement released in Terraform?

**Comment by namewee** [comment]
I noted the Azure KeyVault Secrets Provider will be moved to the top level from AzureRM 3.0 version, this will solved the current problem to support China cloud?
		_Deprecated: "`addon_profile` block has been deprecated and will be removed in version 3.0 of the AzureRM Provider. All properties within the block will move to the top level.",_
