### ISSUE TITLE
azurerm_kubernetes_cluster docs page missing http_application_routing block definition

### ISSUE THREAD

**Issue by 2good4hisowngood** [hashicorp/terraform-provider-azurerm#15813]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
The [azurerm_kubernetes_cluster docs page ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#http_application_routing) is missing the detailed http_application_routing block definition. The docs reference an additional block to be defined below. 

### New or Affected Resource(s)

azurerm_kubernetes_cluster 

* #0000

**Comment by stephybun** [comment]
Hi @2good4hisowngood, thanks for raising this issue. The `http_application_routing` block is deprecated and all references to it should have been removed from the docs entirely. To enable HTTP application routing and to access the zone name you can use the `http_application_routing_enabled` and `http_application_routing_zone_name` properties. 

Thanks again for spotting this!
