### ISSUE TITLE
Support for azurerm_monitor_action_rule_action_group to have schedule

### ISSUE THREAD

**Issue by ingokuba** [hashicorp/terraform-provider-azurerm#15819]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azurerm_monitor_action_rule_action_group` resource is not supporting a schedule, while the `azurerm_monitor_action_rule_suppression` is. This makes it impossible to configure a Alert processing rule of type Action group with scheduling.

### New or Affected Resource(s)

* azurerm_monitor_action_rule_action_group

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_action_rule_action_group" "workdays" {
  name                = "workdays"
  resource_group_name = azurerm_resource_group.example.name
  action_group_id     = azurerm_monitor_action_group.example.id

  schedule {
    start_date_utc    = "2022-01-01T12:00:00Z"
    end_date_utc      = "2032-01-01T12:00:00Z"
    recurrence_weekly = ["Saturday", "Sunday"]
  }
}
```

### References

* #6563 shows, that alert rule of type suppression supports a `schedule` block, but type action group doesn't

**Comment by neil-yechenwei** [comment]
@ingokuba , thanks for raising this issue. After checked [api spec](https://github.com/Azure/azure-rest-api-specs/blob/2abe647120f14bb145968a5543ead8ed51394498/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/preview/2019-05-05-preview/ActionRules.json#L863), seems ActionGroup doesn't support schedule so that TF cannot support it for now. May I ask is there any document talking about this feature? If yes, could you share the doc link here? Thanks.

**Comment by ingokuba** [comment]
I see - that seems to be missing on the Rest API on Azure side. After all it's a preview feature still.

This can only be configured in the UI or with Azure's native IaC language [Bicep](https://docs.microsoft.com/en-us/azure/azure-resource-manager/bicep/overview?tabs=bicep), in case this is helping someone:

```bicep
@description('ID of the action group for contacting')
param exampleActionGroup string

resource exampleAlert 'Microsoft.AlertsManagement/actionRules@2021-08-08' = {
  name: 'example'
  location: 'global'

  properties: {
    actions: [
      {
        actionType: 'AddActionGroups'
        actionGroupIds: [
          exampleActionGroup
        ]
      }
    ]
    scopes: [
      subscription().id
    ]
    schedule: {
      timeZone: 'W. Europe Standard Time'
      recurrences: [
        {
          recurrenceType: 'Weekly'
          startTime: '07:00:00'
          endTime: '19:00:00'
          daysOfWeek: [
            'Monday'
            'Tuesday'
            'Wednesday'
            'Thursday'
            'Friday'
          ]
        }
      ]
    }
    description: 'Send alerts during the work days'
  }
}
```
To sum up: I'm too early for this requirement. The issue can be closed.

Thank you @neil-yechenwei for the quick and helpful response.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
