### ISSUE TITLE
Machine learning vm_size doesn't change when updated

### ISSUE THREAD

**Issue by girvine86** [hashicorp/terraform-provider-azurerm#15825]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 1.1.6 & azurerm 2.89.0

### Affected Resource(s)

* azurerm_machine_learning_compute_cluster
* azurerm_machine_learning_workspace

### Terraform Configuration Files

main
```hcl
resource "azurerm_machine_learning_workspace" "main" {
  provider                = azurerm.app
  application_insights_id = var.application_insights_id
  container_registry_id   = var.container_registry_id[var.environment]
  description             = local.description
  friendly_name           = local.friendly_name
  high_business_impact    = var.high_business_impact
  key_vault_id            = module.keyvault.id
  location                = var.location
  name                    = local.name
  resource_group_name     = var.resource_group_name
  sku_name                = var.sku_name
  storage_account_id      = module.storage.id
  tags                    = local.tags

  identity {
    type = "SystemAssigned"
  }

  dynamic "timeouts" {
    for_each = var.timeouts
    content {
      create = timeouts.value["create"]
      delete = timeouts.value["delete"]
      read   = timeouts.value["read"]
      update = timeouts.value["update"]
    }
  }

}

resource "azurerm_machine_learning_compute_cluster" "main" {
  provider                      = azurerm.app
  name                          = local.ml_compute_name
  location                      = var.location
  vm_priority                   = var.vm_priority
  vm_size                       = var.vm_size[var.environment]
  machine_learning_workspace_id = azurerm_machine_learning_workspace.main.id
  subnet_resource_id            = data.azurerm_subnet.main.id

  scale_settings {
    min_node_count                       = 0
    max_node_count                       = var.max_nodes[var.environment]
    scale_down_nodes_after_idle_duration = var.idle_node_timeout[var.environment]
  }

  identity {
    type = "SystemAssigned"
  }
}
```
var
```hcl
variable "vm_size" {
  description = "The SKU of the compute instance."
  type        = map(any)
  default = {
    sandpit = ""
    dev     = "Standard_D2_v3"
    prod    = "Standard_D8S_V3"
  }
}
```

### Expected Behaviour

The plan indicates the ml cluster will be replaced and the VM size will change as below. 

  # module.main.azurerm_machine_learning_compute_cluster.main must be replaced
-/+ resource "azurerm_machine_learning_compute_cluster" "main" {
      ~ id                            = "/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/rg-d-moduletest/providers/Microsoft.MachineLearningServices/workspaces/ml-d-moduletest/computes/ml-compute" -> (known after apply)
        name                          = "ml-compute"
      ~ ssh_public_access_enabled     = false -> (known after apply)
      - tags                          = {} -> null
      ~ vm_size                       = "STANDARD_D1_V2" -> "Standard_D2_v3" # forces replacement

### Actual Behaviour

However, the VM size does not change, even though the apply destroys the ml cluster and creates again with the VM size as before. 

### Steps to Reproduce

Update VM size in variables to test and run terraform apply again.

### References

* #0000

**Comment by stephybun** [comment]
Thanks for raising this issue @girvine86. 

This seems to be an issue with the Azure API, the PUT request with the updated `vm_size` value is accepted and acknowledged by the API, but the subsequent GET after successful provisioning returns the former value for `vm_size`. I've raised this issue https://github.com/Azure/azure-rest-api-specs/issues/18889 in the hopes that the ML Service Team will take a look into this.
