### ISSUE TITLE
missing import documentation for azurerm_app_service_active_slot

### ISSUE THREAD

**Issue by shubha-rajan** [hashicorp/terraform-provider-azurerm#15827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.1.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)

* `azurerm_app_service_active_slot`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_active_slot" "active_slot" {
  resource_group_name   = data.azurerm_resource_group.rg.name
  app_service_name      = azurerm_app_service.app.name
  app_service_slot_name = azurerm_app_service_slot.canary.name
}
```

### Expected Behaviour

Terraform should have swapped the active slot.

### Actual Behaviour

```
╷
│ Error: ID contained more segments than required: "/subscriptions/ec814e56-5241-4d0b-9cd2-02d608c99732/resourceGroups/shubharajan/providers/Microsoft.Web/sites/shubharajan-champion-perch/slots/canary", map[slots:canary]
│
│   with module.app.azurerm_app_service_active_slot.active_slot,
│   on ../../azure/modules/app/main.tf line 177, in resource "azurerm_app_service_active_slot" "active_slot":
│  177: resource "azurerm_app_service_active_slot" "active_slot" {
│
╵
```
### Steps to Reproduce

1. `terraform apply`

### References

* #12809 will probably fix this? Edit: it looks like it's already been fixed in the source code, but there hasn't been a patch released

**Comment by tombuildsstuff** [comment]
hi @shubha-rajan 

Thanks for opening this issue.

Taking a look through here this is a case of missing documentation, as such I've marked this as a documentation issue - but in this case you can specify the App Service ID rather than the specific Slot as the Resource ID here, as it's the App Service which is being managed (and updated).

Thanks!
