### ISSUE TITLE
Support for instance settings on azurerm_mssql_virtual_machine

### ISSUE THREAD

**Issue by tbo-246** [hashicorp/terraform-provider-azurerm#15824]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Option to supply SQL Instance_settings config block when using the azurerm_mssql_virtual_machine resource. When deploying a SQL Server VM in the portal, we have the option to set storage configuration which is supported in the resource. However, we can also set Instance settings which is not supported in the resource. These are the missing settings:

- Server Collation (string)
- MAXDOP (number)
- Minimum server memory (MB) (number)
- Maximum server memory (MB) (number)
- Optimize for ad-hoc workload (bool)

### New or Affected Resource(s)

* azurerm_mssql_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_virtual_machine" "example" {
  virtual_machine_id               = data.azurerm_virtual_machine.example.id
  sql_license_type                 = "PAYG"
  r_services_enabled               = true
  sql_connectivity_port            = 1433
  sql_connectivity_type            = "PRIVATE"
  sql_connectivity_update_password = "Password1234!"
  sql_connectivity_update_username = "sqllogin"

  auto_patching {
    day_of_week                            = "Sunday"
    maintenance_window_duration_in_minutes = 60
    maintenance_window_starting_hour       = 2
  }

  instance_settings {
    collation         = "SQL_Latin1_General_CP1_CI_AS"
    maxdop            = 0
    min_server_memory = 0
    max_server_memory = 2147483647
    adhoc_workload    = false
  }
}
```

**Comment by myc2h6o** [comment]
`collation` is not returned in response after an update of the resource, and we are not able to compare the current collation with the new one. I've opened an issue under https://github.com/Azure/azure-rest-api-specs/issues/19387

**Comment by dsiperek-vendavo** [comment]
This provider needs to have Instance settings!

**Comment by myc2h6o** [comment]
@dsiperek-vendavo sorry for the delay. I've created #19123 to add the support for this.

**Comment by dsiperek-vendavo** [comment]
THANKS
