### ISSUE TITLE
azurerm_windows_function_app cannot be created with appsetting option FUNCTIONS_WORKER_RUNTIME set to value dotnet-isolated

### ISSUE THREAD

**Issue by klajn** [hashicorp/terraform-provider-azurerm#15823]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: 1.1.4
* AzureRM Provider version: 2.99.0

### Terraform Configuration Files

```hcl
...
resource "azurerm_windows_function_app" "example" {
  name                = "example-windows-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name = azurerm_storage_account.example.name
  service_plan_id      = azurerm_service_plan.example.id

  site_config {}

app_settings = {
    WEBSITE_RUN_FROM_PACKAGE                          = "1"
    SCM_DO_BUILD_DURING_DEPLOYMENT                    = "false"
    WEBSITE_CONTENTSHARE                              = "example_content_share"
    WEBSITE_CONTENTAZUREFILECONNECTIONSTRING          = azurerm_storage_account.klajn_storage.primary_connection_string
    FUNCTIONS_WORKER_RUNTIME                          = "dotnet-isolated"
    APPINSIGHTS_INSTRUMENTATIONKEY                    = azurerm_application_insights.example_insight.instrumentation_key
  }
}
...
```

### Description / Feedback
I cannot apply terraform for the first time with FUNCTIONS_WORKER_RUNTIME property set to "dotnet-isolated" value. This caused an error and the function is not created.

Error:
│ Error: creating Windows Function App: (Site Name "klajnexample" / Resource Group "KlajnRG"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=\<nil\> \<nil\>
│
│   with azurerm_windows_function_app.example,
│   on main.tf line 54, in resource "azurerm_windows_function_app" "example":
│   54: resource "azurerm_windows_function_app" "example" {
│
│ creating Windows Function App: (Site Name "klajnexample" / Resource Group "KlajnRG"): web.AppsClient#CreateOrUpdate: Failure
│ sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=\<nil\> \<nil\>

Workaround
1. Delete this property and apply the terraform. After that you can add back the property and apply terraform again without the problem.
2. You can create function manually and after that apply the terraform without problem.

The function should be created.

**Comment by tombuildsstuff** [comment]
x-ref: https://github.com/hashicorp/terraform-provider-azurerm/issues/10858
