### ISSUE TITLE
delete_data_disks_on_termination not supported on "azurerm_linux_virtual_machine"

### ISSUE THREAD

**Issue by Loki1711** [hashicorp/terraform-provider-azurerm#15850]
For older version of azure VM's "azurerm_virtual_machine" there is an option to skip deleting data disk when terminating the VM's with this argument "delete_data_disks_on_termination"

But in the newer version "azurerm_linux_virtual_machine" there is no way that you can skip deleting data disk.

Please bring the feature under **provider feature block** similar to this 
provider "azurerm" {
  features {
virtual_machine {
      delete_os_disk_on_deletion     = true
}
}
}

**Comment by tombuildsstuff** [comment]
hi @Loki1711 

Thanks for opening this issue.

At this time the `azurerm_linux_virtual_machine` resource doesn't support attaching data disks inline within the resource (due to some upstream changes) - which is being tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/6117. Instead Data Disk Attachments are handled via a separate resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_data_disk_attachment which allows for adding/removing data disks from Virtual Machines as required.

By using the Managed Disk resource in conjunction with the attachment resource it's possible to achieve this without the feature-flag (as shown below) and as such unfortunately we aren't planning to introduce a feature-flag for this at this time - however we may opt to do this in the future as a part of #6117. However in the interim it should be possible to achieve this via:

```hcl
variable "prefix" {
  default = "example"
}

locals {
  vm_name = "${var.prefix}-vm"
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "${var.prefix}-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "internal" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "${var.prefix}-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.internal.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = local.vm_name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}

resource "azurerm_managed_disk" "example" {
  name                 = "${local.vm_name}-disk1"
  location             = azurerm_resource_group.example.location
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "example" {
  managed_disk_id    = azurerm_managed_disk.example.id
  virtual_machine_id = azurerm_virtual_machine.example.id
  lun                = "10"
  caching            = "ReadWrite"
}
```

Thanks!

**Comment by Loki1711** [comment]
Hi @tombuildsstuff I'm already aware that `"azurerm_linux_virtual_machine"` doesn't support attaching data disks inline within the resource. 

My requirement here is - If I hit `terraform destroy` it should delete all the resource except the disk (both OS disk & data disk)
To retain OS disk there is a option to include in the provider's feature block `delete_os_disk_on_deletion = false`

But to retain data disk, there is no way to retain as of now. So I request to add this argument in the provider's feature block `delete_data_disk_on_deletion = false`

**Comment by tombuildsstuff** [comment]
@Loki1711 as above, unfortunately there are no plans to add a feature-flag for this - both the automatic removal of data disks - and not removing data disks can be achieved as outlined in my previous comment.
