### ISSUE TITLE
Support for azure app configuration custom filter.  

### ISSUE THREAD

**Issue by ravi-karur** [hashicorp/terraform-provider-azurerm#15857]
### Description

on azure app configuration service, Terraform only supports the default filters ( Time, Percertage, targer) , I do not see any reference configuring customer filter via terraform. 

Would you be able to include this feature and advise when will it be available?

### New or Affected Resource(s)

* azurerm_app_configuration_feature

**Comment by alexanderbikk** [comment]
I guess it's not supported. Didn't find any related information except this issue.
It will be good to have it. Or maybe someone could help with configuration for it(custom filter) in terraform.

**Comment by peruzzof** [comment]
Hi, any update on this request? I believe that is mislabeled as question but it should be "new feature request".

**Comment by rcskosir** [comment]
@peruzzof Thank you for taking the time to open this issue. I also see issue #23497 as a feature request. I am going to close this older issue as a duplicate to keep conversations consolidated.
