### ISSUE TITLE
`azurerm_api_management` does not work with soft-delete. Re-create fails

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#15865]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.99

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

Terraform should be able to cope with soft-deleted APIM instances.

### Actual Behaviour

APIM does now default to [soft-delete](https://docs.microsoft.com/en-us/azure/api-management/soft-delete) when deleted. Terraform should have an option to either un-delete a soft-deleted APIM or to purge and recreate. If `terraform apply` runs against a soft-deleted APIM, it fails:

```
│ Error: creating/updating Api Management: (Service Name "ace2e8284-westeurop-apim" / Resource Group "ace2e8284-stamp-westeurope-rg"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="ServiceAlreadyExistsInSoftDeletedState" Message="Api service ace2e8284-westeurop-apim was soft-deleted. In order to create the new service with the same name, you have to either undelete the service or purge it. See [https://aka.ms/apimsoftdelete."](https://aka.ms/apimsoftdelete.%22)
```

### Steps to Reproduce

Delete an APIM instance and let terraform create it again.

Note: I had manually deleted my APIM instance above. ~~I'm not sure if Terraform destroy would properly delete it (with purge). Does anybody know this?~~
When running deleting APIM with `terraform destroy` you end up in the same state. APIM is only soft-deleted.

### References

* #0000

**Comment by sebader** [comment]
> Note: I had manually deleted my APIM instance above. I'm not sure if Terraform destroy would properly delete it (with purge). Does anybody know this?

I just tried this: When running deleting APIM with `terraform destroy` you end up in the same state. APIM is only soft-deleted.

**Comment by manicminer** [comment]
@sebader Thanks for the feature request. The provider does currently support purging on deletion for API Management resources, although this is currently an opt-in behaviour via the provider features block. For example:

```hcl
provider "azurerm" {
  features {
    api_management {
      purge_soft_delete_on_destroy = true
    }
  }
}
```

Note that in v3.0 of the provider this setting will be enabled by default.

I'm looking at adding support for restoring/recovering soft-deleted API Management resources, similarly to how we do the same for KeyVault resources.

**Comment by sebader** [comment]
thanks @manicminer just found that features block, too :)

> I'm looking at adding support for restoring/recovering soft-deleted API Management resources, similarly to how we do the same for KeyVault resources.
+1 :)
