### ISSUE TITLE
azurerm_cognitive_account typo in outbound_network_access_restricted argument

### ISSUE THREAD

**Issue by samoomoo** [hashicorp/terraform-provider-azurerm#15891]
There seems to be a typo in the argument outbound_network_access_restricted in the documentation for azurerm_cognitive_account. When using terraform apply, it suggests outbound_network_access_restrited instead. See attached picture. Thanks !

![image](https://user-images.githubusercontent.com/94574788/159066355-525e9440-a3da-4beb-825e-022536783d95.png)

**Comment by sinbai** [comment]
@samoomoo  thank you for opening this issue. This issue has been fixed and would be released in the incoming release 3.0. Could you please check whether you would be unblocked in the 3.0 release?

**Comment by tombuildsstuff** [comment]
Fixed via #15800 which will ship in v3.0 of the AzureRM Provider
