### ISSUE TITLE
Azure automation Account With System Assigned Managed Identity

### ISSUE THREAD

**Issue by Tofan-Jena** [hashicorp/terraform-provider-azurerm#15919]
resource "azurerm_automation_account" "automationaccount" {
      name                = var.automationaccountname
      location                    = var.location
      resource_group_name         = var.resourceGroupName
      sku_name            = "Basic"
      tags = var.tags
      identity = {
        type = "SystemAssigned"
      }
    }
    
    
    
   Error: Unsupported argument
│
│   on Modules\AutomationAccount\main.tf line 7, in resource "azurerm_automation_account" "automationaccount":
│    7:   identity = {
│
│ An argument named "identity" is not expected here.

Kindly help to solve this issues, i have followed the Docs (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account)
but its not working.

**Comment by aristosvo** [comment]
Hi @Tofan-Jena! Could you check if this setup fixes the problem? 

```hcl
resource "azurerm_automation_account" "automationaccount" {
  ...
  identity {
    type = "SystemAssigned"
  }
}
```

**Comment by Tofan-Jena** [comment]
Hello , i tried above also , bust its giving same error.

![image](https://user-images.githubusercontent.com/47977011/159442495-fcd95534-675c-4678-a259-2ce9b7ed8287.png)

**Comment by sinbai** [comment]
@Tofan-Jena The tf configuration below worked for me, could you try it?
```
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	  version = "2.99.0"
    }
  }
}


resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_automation_account" "automationaccount" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
  tags = {
    "hello" = "world"
  }
  identity  {
    type = "SystemAssigned"
  }
}	
```

**Comment by tombuildsstuff** [comment]
Closing this out since as @sinbai has mentioned this is supported - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account - you may need to upgrade your provider version (v2.99.0 is the latest at the time of writing).

**Comment by Tofan-Jena** [comment]
its solved my problem
