### ISSUE TITLE
Support for azurerm_virtual_network_gateway_connection traffic_selector_policy

### ISSUE THREAD

**Issue by dbaur** [hashicorp/terraform-provider-azurerm#15917]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azurerm_virtual_network_gateway_connection currently only allows one "traffic_selector_policy" according to the documentation. Multiple blocks also throw an exception.
However, the corresponding Azure API documentation allows the specification of multiple policies which is required in our use case.
Probably the easiest solution would be to allow multiple blocks of a "traffic_selector_policy" to exist.

I am not sure why the initial implementation (see link below) sets the max items for the traffic selector block to 1.

### New or Affected Resource(s)

* azurerm_virtual_network_gateway_connection

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network_gateway_connection" "conn" {

    use_policy_based_traffic_selectors = true

    traffic_selector_policy {
        local_address_cidrs = [ "10.0.0.0/25" ]
        remote_address_cidrs = [ "40.40.40.0/25" ]
    }

    traffic_selector_policy {
        local_address_cidrs = [ "10.0.0.128/25" ]
        remote_address_cidrs = [ "40.40.40.128/25" ]
    }

}
```

### References

Azure Documentation: https://docs.microsoft.com/en-us/rest/api/network-gateway/virtual-network-gateway-connections/create-or-update
Provider Documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway_connection
Initial PullRequest: https://github.com/hashicorp/terraform-provider-azurerm/pull/6586

* #0000

**Comment by mybayern1974** [comment]
@dbaur would you be okey if we close this issue by noticing your contributed PR #15938 has been merged?

**Comment by dbaur** [comment]
yes, issue was fixed in the mentioned PR.
