### ISSUE TITLE
define a cosmos DB connection string into an Azure function app_settings 

### ISSUE THREAD

**Issue by pchevallier** [hashicorp/terraform-provider-azurerm#15947]
I feel the need to document the use case where you need to link an azure function to the cosmos DB database using the connection string.  

Assume you have declared a cosmosdb resource in your TF script like this
```
resource "azurerm_cosmosdb_account" "db" {
..
}
```

and now you want to define the connection string in you your azure function:

```
resource "azurerm_function_app" "function_name" {
  ..
  app_settings = {
     ....
     "cosmosdb_readwrite_primary_key"       = azurerm_cosmosdb_account.db.connection_strings[0],
     "cosmosdb_readwrite_secondary_key"  = azurerm_cosmosdb_account.db.connection_strings[1],
    }
``` 

So, obviously this is assuming the array respects the current following description by MSFT:
az cosmosdb keys list --type connection-strings
```
{
  "connectionStrings": [
    {
      "connectionString": "AccountEndpoint=https://<redacted>.documents.azure.com:443/;AccountKey=<redacted>",
      "description": "Primary SQL Connection String"
    },
    {
      "connectionString": "AccountEndpoint=https://<redacted>.documents.azure.com:443/;AccountKey=<redacted>",
      "description": "Secondary SQL Connection String"
    },
    {
      "connectionString": "AccountEndpoint=https://<redacted>.documents.azure.com:443/;AccountKey=<redacted>",
      "description": "Primary Read-Only SQL Connection String"
    },
    {
      "connectionString": "AccountEndpoint=https://<redacted>.documents.azure.com:443/;AccountKey=<redacted>",
      "description": "Secondary Read-Only SQL Connection String"
    }
  ]
}
```

**Comment by sinbai** [comment]
@pchevallier thank you for opeing this issue. Per the description "A map of key-value pairs for [App Settings](https://docs.microsoft.com/en-us/azure/azure-functions/functions-app-settings) and custom values." of `app_settings`  in the terraform [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app#argument-reference), I assume that your use case would like to define a map of key-value pairs for custom values about cosmos db connection string in `app_settings` property, right? If so, I don't think it is necessary to document a sample in terraform doc, as the key-value pairs could be any strings you would like to define. what do you think?

**Comment by pchevallier** [comment]
@sinbai thank you for the follow up. 
A generic solution could perhaps consists of referencing the type of connection string we want to use directly in the TF cosmosdb model. 
Example:
```
app_settings = {
     ....
     "ex_cosmosdb_primary_key"     =  azurerm_cosmosdb_account.db.connection_strings.primary_key,
     "ex_cosmosdb_secondary_key"   = azurerm_cosmosdb_account.db.connection_strings.secondary_key

```
That would avoid any future inconsistency if the structure of the array were to be changed by MSFT.
