### ISSUE TITLE
regional_endpoint_enabled seems to be missing from module

### ISSUE THREAD

**Issue by mukundbajaj** [hashicorp/terraform-provider-azurerm#15956]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.98.0

### Affected Resource(s)

* `azurerm_container_registry`

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "container_registry" {
  for_each            = var.container_registry_variables
  name                = each.value.name
  location            = each.value.location
  resource_group_name = each.value.resource_group_name
  sku                 = each.value.sku
  admin_enabled       = each.value.admin_enabled
  regional_endpoint_enabled = each.value.regional_endpoint_enabled ## Bug in current resource, does not seem to work
  public_network_access_enabled = each.value.public_network_access_enabled
  quarantine_policy_enabled     = each.value.quarantine_policy_enabled
  zone_redundancy_enabled       = each.value.zone_redundancy_enabled
  data_endpoint_enabled         = each.value.data_endpoint_enabled
  anonymous_pull_enabled        = each.value.anonymous_pull_enabled
  network_rule_bypass_option    = each.value.network_rule_bypass_option
  retention_policy {
    enabled = each.value.retention_policy_enabled
    days    = each.value.retention_policy_days
  }
  trust_policy {
    enabled = each.value.trust_policy_enabled
  }
  dynamic "georeplications" {
    for_each = { for k, v in var.container_registry_variables : k => v if lookup(v, "georeplication_enabled", true) == true }
    content {
      location                  = each.value.georeplication_location
      zone_redundancy_enabled   = each.value.georeplication_zone_redundancy_enabled
      regional_endpoint_enabled = each.value.georeplication_regional_endpoint_enabled
      tags                      = each.value.georeplication_zone_tags
    }
  }
  tags = merge(each.value.container_registry_tags, tomap({ Created_Time = formatdate("DD-MM-YYYY hh:mm:ss ZZZ", timestamp()) }))
  lifecycle { ignore_changes = [tags["Created_Time"]] }
}
```

### Expected Behaviour

regional_endpoint_enabled should be accepted as a variable.

### Actual Behaviour

Error: Unsupported argument
│
│ on ..\main.tf line 9, in resource "azurerm_container_registry" "container_registry":
│ 9: regional_endpoint_enabled = each.value.regional_endpoint_enabled
│
│ An argument named "regional_endpoint_enabled" is not expected here.

### Steps to Reproduce

1. `terraform plan`

**Comment by sinc59** [comment]
Hello,
based on the [resource documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry), the "regional_endpoint_enabled" is only present in the [georeplications block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry#georeplications).

Did you have tried this ?

Sébastien

**Comment by sinc59** [comment]
I'm not an azure expert but, why you would use georeplication in the same region ?

The georeplication mechanism is used in case of the region have trouble so georeplication in same region seems to be not have interrest (but maybe i don't have correctly undrestand your need).

**Comment by mukundbajaj** [comment]
@sinc59 thanks for actually raising that. I just checked the documentation for the version 3.0.1 (which was release 2 hours ago), and it only has the regional_endpoint_enabled in the georeplications block. For version 2.98.0, the regional_endpoint_enabled is separtely mentioned outside the georeplications block too.

Closing this for now, thank you!
