### ISSUE TITLE
enable NFSV3 for azure storage 

### ISSUE THREAD

**Issue by cuntoulishifu** [hashicorp/terraform-provider-azurerm#15968]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "xxx" {
  name                     = "xxx"
  location                 = "chinaeast2"
  resource_group_name      = azurerm_resource_group.xxx.name
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "LRS"
  enable_https_traffic_only = false
  allow_blob_public_access = true
  is_hns_enabled = true
  nfsv3_enabled = true
}
```

### Debug Output

havn't tried to debug, if need I will add it here
### Expected Behaviour

created SA with "nfsv3_enabled = true"

### Actual Behaviour

run into error with "StatusCode=400 -- Original Error: Code="NetworkAclsDefaultActionMisconfigured" Message="NetworkAcls default action must be set to Deny for NFS enabled account.""

### Steps to Reproduce

terraform init -- good
terraofrm plan -- good
terraform apply -- above error happended 

1. `terraform apply`

### Important Factoids

I am using terraform in AzureChina

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @cuntoulishifu 

As per the error message coming from the Azure API here you need to configure the `network_rules` block as outlined above: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#example-usage-with-network-rules to ensure these are disabled using using NFS.

Thanks!

**Comment by cuntoulishifu** [comment]
@tombuildsstuff  Thank you much, the error has been resolved. so my understanding is that if I want to enable the NFS then I mush set the `network_rules`, is that right ?
