### ISSUE TITLE
Support for identity parameter in azurerm_digital_twins_instance

### ISSUE THREAD

**Issue by mateuszlopusinski** [hashicorp/terraform-provider-azurerm#15970]
### Description
There is no option to specify _identity_ for the **azurerm_digital_twins_instance**

### New or Affected Resource(s)
* azurerm_digital_twins_instance

### Potential Terraform Configuration

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example_resources"
  location = "West Europe"
}

resource "azurerm_digital_twins_instance" "example" {
  name                = "example-DT"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  tags = {
    foo = "bar"
  }

 identity {
    type = "SystemAssigned"
  }
}
````

### References
* https://docs.microsoft.com/en-us/azure/digital-twins/concepts-security
* https://docs.microsoft.com/en-us/azure/digital-twins/how-to-route-with-managed-identity?tabs=portal#add-a-system-managed-identity-during-instance-creation
* https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/digital_twins_instance

**Comment by myc2h6o** [comment]
Hi @mateuszlopusinski I'll try work on this

**Comment by gkarecki** [comment]
Hi @myc2h6o Do you still work on this, or it has been resolved?

**Comment by myc2h6o** [comment]
Hi @mateuszlopusinski @gkarecki I've created #17076 to add the support

**Comment by gkarecki** [comment]
Hi @myc2h6o Sorry for bothering you again, I saw that PR is approved. Is there any chance to see that fix in next release? :)

**Comment by myc2h6o** [comment]
@tombuildsstuff I've resolved the comments in the change, could you take another look?

**Comment by gkarecki** [comment]
@tombuildsstuff Could you please look again at this PR to resolve this issue as soon as it's possible?
