### ISSUE TITLE
Support for "Azure Active Directory authentication only" on Synapse Workspace

### ISSUE THREAD

**Issue by Nisden** [hashicorp/terraform-provider-azurerm#16002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Synapse Workspace have just added support for only allowing Azure AD Authentication, similar to regular SQL Servers in Azure.

![image](https://user-images.githubusercontent.com/1127727/159876807-02cc7d61-5d97-4db2-bf3d-bd1b34f21c3f.png)

### New or Affected Resource(s)

* azurerm_synapse_workspace
* azurerm_synapse_workspace_aad_admin

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://github.com/MicrosoftDocs/azure-docs/commit/336fc490a3b8d931d1c78f2b6706ff7b66cdd03b

**Comment by DesaCh01** [comment]
Can we have some information on this feature...as to when will this be available in Terraform resource?

**Comment by eugene-cp** [comment]
> I tried using this policy but even with a successful policy remediation execution, it was not taking effect.  I opened a ticket with MS and they said that the policy needs to be revised.  

What worked for me was using azapi provider instead and creating this resource:

[https://learn.microsoft.com/en-us/azure/templates/microsoft.synapse/workspaces/azureadonlyauthentications?pivots=deployment-language-terraform](https://learn.microsoft.com/en-us/azure/templates/microsoft.synapse/workspaces/azureadonlyauthentications?pivots=deployment-language-terraform)

**Comment by mahalel** [comment]
> What worked for me was using azapi provider instead and creating this resource:
> 
> https://learn.microsoft.com/en-us/azure/templates/microsoft.synapse/workspaces/azureadonlyauthentications?pivots=deployment-language-terraform

Thank you @eugene-cp , I can confirm that works. 
There one thing I have encountered, worth mentioning here in case someone else runs into it.

If you have never in the past toggled the button via the portal, then you can simply apply the above and it will be fine.
However, this was toggled in the past, even if you have it on false, and you add the AzAPI block, it will say there is already an existing resource which needs to be imported in the state.

Something like this will do the trick ( `import` only being a feature for terraform 1.51 onwards ):

```hcl
 import {
   # ID of the cloud resource
   id = "/subscriptions/YOUR_SUB_ID/resourceGroups/SYNAPSE_RG/providers/Microsoft.Synapse/workspaces/SYNAPSE_NAME/azureADOnlyAuthentications/default"

   # Resource address
   to = azapi_resource.aad_auth_only
 }

resource "azapi_resource" "aad_auth_only" {
  type      = "Microsoft.Synapse/workspaces/azureADOnlyAuthentications@2021-06-01"
  name      = "default"
  parent_id = module.synapse_workspace.id
  body = jsonencode({
    properties = {
      azureADOnlyAuthentication = true
    }
  })
}
```

**Comment by marvinbuss** [comment]
I noticed that the resource gets automatically created for every workspace. Hence, I would recommend using the `azapi_update_resource` instead of `azapi_resource`. With `azapi_resource` you will continuously run into the import problem. The new import statement that terraform introduced is helpful but not great as it does not allow using variables or data objects for the id. Hence, it is not very convenient, if you need to rollout 30+ environments across different environments and subscriptions. Therefore, I suggest using the following resource (adjust the reference in resource ID to reference your Synapse workspace resource):

```terraform
resource "azapi_update_resource" "synapse_azuread_only_authentication" {
  type        = "Microsoft.Synapse/workspaces/azureADOnlyAuthentications@2021-06-01-preview"
  resource_id = "${azurerm_synapse_workspace.synapse.id}/azureADOnlyAuthentications/default"

  body = jsonencode({
    properties = {
      azureADOnlyAuthentication = true
    }
  })
}
```

**Comment by qzhou-hmcts** [comment]
Is there any plan to integrate the flag in the same way that is available in SQL servers? azapi workaround is valid to enable the flag however in the successive updates fails with the following error

> │ Error: updating Synapse Workspace "*******" (Resource Group "***"): synapse.WorkspacesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="ValidationFailed" Message="Workspace request validation failed, check error details for more information" Details=[{"code":"AadOnlyAuthenticationIsEnabled","message":"Azure Active Directory Only Authentication is enabled. Please contact workspace administrator."}]

**Comment by joakimlemb** [comment]
Still missing this functionality with azurerm 3.75...

**Comment by sharccc** [comment]
HashiCorp internal reference IPL-4932, IPL-4779 
(Terraform Support)
