### ISSUE TITLE
Unable to deploy a resource group via terraform

### ISSUE THREAD

**Issue by ashadeepparida1988** [hashicorp/terraform-provider-azurerm#16026]
Script
=============================

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.0.0"
    }
  }
}

provider "azurerm" {
  features {}

  subscription_id = "********"
  client_id       = "********"
  client_secret   = "********"
  tenant_id       = "********"
}

#create resource group
resource "azurerm_resource_group" "Dev" {
  name     = "Dev"
  location = "eastus"
}

======================================================================================
****Error Message*****

PS C:\Users\ashad\Desktop\Terraform\Demo3> terraform plan
╷
│ Error: building account: getting authenticated object ID: listing Service Principals: ServicePrincipalsClient.BaseClient.Get(): clientCredentialsToken: received HTTP status 401 with response: {"error":"invalid_client","error_description":"AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app 'bbadfd0d-2c2f-48a2-be59-473794852fef'.\r\nTrace ID: 2bd3c1ad-f57f-46d9-9a0c-69540b609a00\r\nCorrelation ID: a89ec582-85f8-47e3-8415-56e3fa16b729\r\nTimestamp: 2022-03-24 18:32:04Z","error_codes":[7000215],"timestamp":"2022-03-24 18:32:04Z","trace_id":"2bd3c1ad-f57f-46d9-9a0c-69540b609a00","correlation_id":"a89ec582-85f8-47e3-8415-56e3fa16b729","error_uri":"https://login.microsoftonline.com/error?code=7000215"}
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on Main.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
│
╵
PS C:\Users\ashad\Desktop\Terraform\Demo3>

**Comment by kgopi1** [comment]
Hi,  in your azure authentication you have provided an invalid client secret causing this issue.  

Can you try login in using az login with your client id and secret? 

This may be an issue with Terraform and it is a local issue.

**Comment by ashadeepparida1988** [comment]
@kgopi1  No I'm using the correct client secret (Client Vaule). I think it could be an issue with terraform

**Comment by manicminer** [comment]
Hi @ashadeepparida1988, thanks for reporting this. In the config you pasted, it looks like you're using single tenant auth and specifying the client credentials inline in the provider block. Can you confirm if these are both the case in your full config? Thanks!

**Comment by ashadeepparida1988** [comment]
now its worked
======================
terraform {
   required_version = ">= 1.1.7"
   required_providers {
     azurerm = {
       source = "hashicorp/azurerm"
       version = ">= 2.0.0, < 2.60.0"
       #version = ">= 2.0"
     }
   }
}
provider "azurerm" {
  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.client_secret
  tenant_id       = var.tenant_id 
  features {}
  
}

#create resource group
resource "azurerm_resource_group" "Dev" {
  name     = "Dev1"
  location = "eastus"
}

**Comment by katbyte** [comment]
Thanks for the update @ashadeepparida1988 ! glad to hear its working now 🙂  going to close this out as its been resolved
