### ISSUE TITLE
panic: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by aviisingh** [hashicorp/terraform-provider-azurerm#16048]
### Community Note

Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform Azure Provider Version
Terraform version : hashicorp/null v3.1.1
Terraform Azure Provider version: hashicorp/azurerm v2.99.0

### Affected Resource(s)
azurerm_cdn_endpoint
Terraform Configuration Files
resource "azurerm_cdn_endpoint" "ce" {
  name                = var.storage_account_name
  profile_name        = var.cdn_profile_name
  location            = "global"
  resource_group_name = var.resource_group_name
  origin_host_header  = data.azurerm_storage_account.sa.primary_web_host
  optimization_type   = "GeneralWebDelivery"
  querystring_caching_behaviour = var.querystring_caching_behaviour
  origin {
    name      = replace(data.azurerm_storage_account.sa.primary_web_host, ".", "-")
    host_name = data.azurerm_storage_account.sa.primary_web_host
  }
  geo_filter  {     
  action = "Block"
  relative_path = "/"
  country_codes = var.blocked_country_codes
  }
}

variable:
variable "blocked_country_codes" {
  default     = [""]
  type        = list
}

### Error
**Error: Plugin did not respond**
│ 
│   with module.default.module.cdn_endpoint_frontend_india.azurerm_cdn_endpoint.ce,
│   on ../../../../modules/azure/cdn-endpoint-spa/main.tf line 8, in resource "azurerm_cdn_endpoint" "ce":
│    8: resource "azurerm_cdn_endpoint" "ce" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Plugin did not respond
│ 
│   with module.default.module.cdn_endpoint_frontend_eu.azurerm_cdn_endpoint.ce,
│   on ../../../../modules/azure/cdn-endpoint-spa/main.tf line 8, in resource "azurerm_cdn_endpoint" "ce":
│    8: resource "azurerm_cdn_endpoint" "ce" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with module.default.module.cdn_endpoint_frontend_panda.azurerm_cdn_endpoint.ce,
│   on ../../../../modules/azure/cdn-endpoint-spa/main.tf line 8, in resource "azurerm_cdn_endpoint" "ce":
│    8: resource "azurerm_cdn_endpoint" "ce" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

**Stack trace from the terraform-provider-azurerm_v2.99.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string**

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behavior
Empty string being passed in as a document should be gracefully handled.

### Actual Behavior
Panic.

### Steps to Reproduce
Use azurerm_cdn_endpoint with geo_filter:country_codes
**Pass empty string array "[""]" as country_codes**
Run terraform init
Run terraform plan - **Succeeds**
Run terraform apply - **Fails**

**Comment by katbyte** [comment]
Thanks for opening this issue @aviisingh,

Would it be possible to share with us the panic output including the stack trace so we can track this down? thanks!

**Comment by aviisingh** [comment]
### Stack Trace

Error: Request cancelled
│ 
│   with module.default.module.cdn_endpoint_frontend_panda.azurerm_cdn_endpoint.ce,
│   on ../../../../modules/azure/cdn-endpoint-spa/main.tf line 8, in resource "azurerm_cdn_endpoint" "ce":
│    8: resource "azurerm_cdn_endpoint" "ce" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵


Stack trace from the terraform-provider-azurerm_v2.99.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 117 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.expandCdnEndpointGeoFilters(0xc002c39020)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/cdn/cdn_endpoint_resource.go:517 +0x47d
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceCdnEndpointUpdate(0xc002b72780, {0x5770660, 0xc0007a0380})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/cdn/cdn_endpoint_resource.go:358 +0x571
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0030e3bc0, {0x67b1cf8, 0xc002acd640}, 0x24, {0x5770660, 0xc0007a0380})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:363 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00068b420, {0x67b1cf8, 0xc002acd640}, 0xc002b2d790, 0xc002b72480, {0x5770660, 0xc0007a0380})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:475 +0x6ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001144fa8, {0x67b1cf8, 0xc002acd640}, 0xc002a7def0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000abc00, {0x67b1da0, 0xc002b1c150}, 0xc0012c1d50)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5cc9280, 0xc0000abc00}, {0x67b1da0, 0xc002b1c150}, 0xc002b16fc0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c4fc0, {0x6802630, 0xc000191380}, 0xc002af7560, 0xc0012bd830, 0xaf0b8a0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0000c4fc0, {0x6802630, 0xc000191380}, 0xc002af7560, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.99.0_x5 plugin crashed!
