### ISSUE TITLE
azurerm provider 3.0 - how and proper way to migrate renamed resource types?

### ISSUE THREAD

**Issue by RobertDubinski-Hologic** [hashicorp/terraform-provider-azurerm#16055]
Hello,

Noticed the 3.0 provider has released, and wanted to start updating an existing set of 2.0-era code to use it.   

This code has one of the now deprecated resource types 'azurerm_app_service_plan', that has a replacement type 'azurerm_service_plan' to migrate to.   But I'm not finding any documentation suggesting how this migration should be handled.

If I simply change the name in the code, 'terraform plan' wants to destroy the existing resource and build a new one.

If I try to modify state file and move it to adjusted name, like

terraform_1.1.7 state mv azurerm_app_service_plan.asp1 azurerm_service_plan.asp1

Then I get an error:

Error: Invalid state move request
│
│ Cannot move azurerm_app_service_plan.asp1 to azurerm_service_plan.asp1: resource types don't match.
╵

Doing a search for that error msg pulls up issue 5561, which then points to url 

https://www.terraform.io/docs/providers/azurerm/guides/migrating-between-renamed-resources.html

which sounded promising, but clicking that today now leads nowhere.

"Page Not Found
This documentation page doesn't exist for version 3.0.1 of the azurerm provider."

Have located a version of that doc at an older provider version:

https://registry.terraform.io/providers/hashicorp/azurerm/2.69.0/docs/guides/migrating-between-renamed-resources

and that mentions removing then importing the renamed resource.  Is that still the thing to do here?   

If so, that type of documentation should still be made available somewhere with the new versions, as well as get pointed at from the upgrade guide that mentions all the changed resource types.   It will be very useful for others like myself who don't regularly perform such maintenance procedures.

If what's in the old doc is not something to do, what is the new recommendation for these renamed types in 3.0?

Thanks.

**Comment by katbyte** [comment]
Hey @RobertDubinski-Hologic - thanks for pointing this out! looks like that was removed in the 3.0 shuffle instead of updated. I've opened #16060 that will restore it using the new app service resources as the example. Hopefully this makes it more clear and it should go out later today in 3.0.2 🙂
