### ISSUE TITLE
azurerm_managed_disk 3.0.1: cannot update zone

### ISSUE THREAD

**Issue by achevalet** [hashicorp/terraform-provider-azurerm#16059]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v1.1.7
azurerm v3.0.1

### Affected Resource(s)

* `azurerm_managed_disk`

### Expected Behaviour

Change zones forces replacement:

```
  # azurerm_managed_disk.main must be replaced
  ~ resource "azurerm_managed_disk" "main" {
      ~ zones                         = [ # forces replacement
          - "2",
          + "1",
        ]
    }
```

### Actual Behaviour

Change zone is updated in place but fail:

```
  # azurerm_managed_disk.main will be updated in-place
  ~ resource "azurerm_managed_disk" "main" {
      ~ zone                          = "1" -> "2"
    }
...
```

Note: API does not allow zone update:

```
$ az disk update --name testvm-disk1 --resource-group testvm --set zones=["2"]
(BadRequest) Availability zone must not be changed on existing resource 'testvm-disk1'. Existing zone '1', new zone '2'..
Code: BadRequest
```

**Comment by katbyte** [comment]
Thanks for letting us know about this @achevalet! looks like we used the wrong zone function here as such i've opened #16059 to resolve this in 3.0.2 which should go out later today 🙂
