### ISSUE TITLE
r/azurerm_windows_function_app - import not working

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#16068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.31
+ provider.azurerm v3.0.1
+ provider.random v3.1.2

### Affected Resource(s)

* `azurerm_windows_function_app`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "random_pet" "example" {
  length = 1
}

resource "azurerm_resource_group" "example" {
  name     = "azure-functions-test-rg"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = format("%stestsa", random_pet.example.id)
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "example" {
  name                = "azure-functions-test-service-plan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_function_app" "example" {
  name                       = format("%stest-azure-functions", random_pet.example.id)
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
}

output "id" {
  value = azurerm_function_app.example.id
}
```

### Expected Behaviour

Import succeeded.
### Actual Behaviour

```hcl
Error: specified Service Plan is not a Windows Functionapp plan
```
### Steps to Reproduce

1. `terraform apply -auto-approve`
2. `terraform state rm azurerm_function_app.example`
3. `rename azurerm_function_app => azurerm_windows_function_app`
4. `terraform import azurerm_windows_function_app.example <id from the output>`

### References

* #0000

**Comment by brennfoster** [comment]
Change azurerm_app_service_plan to azurerm_service_plan and set the os_type = "windows"

**Comment by RobertDubinski-Hologic** [comment]
I am also having the same issue when trying to update azurerm_function_app to azurerm_windows_function_app 

"Error: specified Service Plan is not a Windows Functionapp plan"

I have already done the update of azurerm_app_service_plan to azurerm_app_service_plan.   The properties on the plan were changed to mention the os_type is Windows.:


resource "azurerm_service_plan" "asp1" {
  
  name = var.app_service_plan1_name
  resource_group_name = data.azurerm_resource_group.rg1.name
  location = data.azurerm_resource_group.rg1.location
    
  os_type = "Windows"
  sku_name = var.app_service_plan1_options["sku_size"]
  
    tags = merge(
    var.common_tags, 
    var.app_service_plan1_extra_tags
  )
  provider = azurerm.DeploySub1
}
#

The modification of the state file to rm/import the old/new definitions of service plan as in the 'migrating-from-deprecated-resources' guide.  

I originally didn't do a plan/apply after the state file modification for service plan, so upon first receiving the "Error: specified Service Plan is not a Windows Functionapp plan", I put the function app back as it was and did so.   Figuring maybe there's some extra something that needed be written regarding that new 'os_type'parameter in the plan.     Did not help, unfortunately.

I am attempting procedure this using Terraform 1.1.7 and AzureRM 3.0.2

**Comment by RobertDubinski-Hologic** [comment]
I set TF_LOG to debug and to troubleshoot this.  Just before the error is received, a GET is made to get info on the Service Plan.  

In my case, this said:

```
{"id":"/subscriptions/xxxxxxxx-54a4-40bd-a55b-95de04807789/resourceGroups/holx-devopssbx-iot-dev/providers/Microsoft.Web/serverfarms/holx-devopssbx-iot-slinkreg-ASP-dev","name":"holx-devopssbx-iot-slinkreg-ASP-dev","type":"Microsoft.Web/serverfarms","kind":"Windows","location":"East US","properties":{"serverFarmId":43937,"name":"holx-devopssbx-iot-slinkreg-ASP-dev","workerSize":"Default","workerSizeId":0,"workerTierName":null,"numberOfWorkers":1,"currentWorkerSize":"Default","currentWorkerSizeId":0,"currentNumberOfWorkers":1,"status":"Ready","webSpace":"holx-devopssbx-iot-dev-EastUSwebspace","subscription":"xxxxxxxx-54a4-40bd-a55b-95de04807789","adminSiteName":null,"hostingEnvironment":null,"hostingEnvironmentProfile":null,"maximumNumberOfWorkers":10,"planName":"VirtualDedicatedPlan","adminRuntimeSiteName":null,"computeMode":"Dedicated","siteMode":null,"geoRegion":"East US","perSiteScaling":false,"elasticScaleEnabled":false,"maximumElasticWorkerCount":1,"numberOfSites":5,"hostingEnvironmentId":null,"isSpot":false,"spotExpirationTime":null,"freeOfferExpirationTime":null,"kind":"Windows","resourceGroup":"holx-devopssbx-iot-dev","reserved":false,"isXenon":false,"hyperV":false,"mdmId":"waws-prod-blu-083_43937","targetWorkerCount":0,"targetWorkerSizeId":0,"provisioningState":"Succeeded","webSiteId":null,"existingServerFarmIds":null,"kubeEnvironmentProfile":null,"zoneRedundant":false},"sku":{"name":"S1","tier":"Standard","size":"S1","family":"S","capacity":1}}: timestamp=2022-03-27T08:00:16.171-0700
2022-03-27T08:00:16.211-0700 [ERROR] vertex "azurerm_windows_function_app.funcapp1 (import id \"/subscriptions/xxxxxxxx-54a4-40bd-a55b-95de04807789/resourceGroups/holx-devopssbx-iot-dev/providers/Microsoft.Web/sites/holx-devopssbx-iot-slinkreg-FunctApp-dev\")" error: specified Service Plan is not a Windows Functionapp plan
[31m[31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mspecified Service Plan is not a Windows Functionapp plan[0m

```

In there one of the attributes was `"kind":"Windows"`


I then looked at source for the provider. 

In file https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/windows_function_app_resource.go

is this:

```
if strings.Contains(strings.ToLower(*sp.Kind), "linux") || !(strings.Contains(strings.ToLower(*sp.Kind), "elastic") || strings.Contains(strings.ToLower(*sp.Kind), "functionapp") || strings.Contains(strings.ToLower(*sp.Kind), "app")) {
			return fmt.Errorf("specified Service Plan is not a Windows Functionapp plan")
		}

```


I'm not a Go programmer, but this looks like a bunch of "or" conditions.   The second expression looks to be saying if "Kind is not elastic".  So as my kind of "Windows" evaluates true here and incorrectly errors out.
