### ISSUE TITLE
AzureRM Continually Planning Changes to API Management with Proxy Configuration for Default Endpoint to Switch on Negotiate Client Certificate

### ISSUE THREAD

**Issue by nnnvvvcv** [hashicorp/terraform-provider-azurerm#16065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.99

### Affected Resource(s)

* `azurerm_api_management`

### Terraform Configuration Files

```hcl
...
resource "azurerm_api_management" "apim" {
  name                = "the-apim"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

...

  hostname_configuration {
    proxy {
      host_name = "the-apim.azure-api.net"
      negotiate_client_certificate = true
    }
  }
}
...
```

### Expected Behaviour

AzureRM should configure the default gateway for APIM to use Negotiate Client Certificate just once and then not attempt again.

### Actual Behaviour

Whilst the setting does get set correctly:

![image](https://user-images.githubusercontent.com/3199833/160144646-f4b4df56-9ef2-4dea-a564-d869c9085cf6.png)

Subsequent times `terraform plan` & `terraform apply` is run it attempts to configure the setting again:

```
      + hostname_configuration {

          + proxy {
              + host_name                    = "the-apim.azure-api.net"
              + negotiate_client_certificate = true
            }
        }
```

### Steps to Reproduce

1. `terraform plan`
1. `terraform apply`
2. `terraform plan` <- this should show no change required.

### Important Factoids

We're trying to configure the default gateway domain on the APIM instance rather than a custom domain.

**Comment by jackofallops** [comment]
I believe this should have been closed by #16524. If this is not the case, we can re-open as needed.
