### ISSUE TITLE
v3.0 of AzureRM Provider Bitten By Case Difference Bug

### ISSUE THREAD

**Issue by treyhendon** [hashicorp/terraform-provider-azurerm#16076]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.1.7
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.19.1
+ provider registry.terraform.io/hashicorp/azurerm v3.0.1
+ provider registry.terraform.io/hashicorp/external v2.2.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Affected Resource(s)

All string compares

### Debug Output

```
Error: expected http_listener.0.protocol to be one of [Http Https], got HTTP

  with module.redsail_agw["eastus"].azurerm_application_gateway.app_gateway,
  on modules/agw/agw.tf line 58, in resource "azurerm_application_gateway" "app_gateway":
  58: resource "azurerm_application_gateway" "app_gateway" {


Error: expected http_listener.1.protocol to be one of [Http Https], got HTTPS

  with module.redsail_agw["eastus"].azurerm_application_gateway.app_gateway,
  on modules/agw/agw.tf line 58, in resource "azurerm_application_gateway" "app_gateway":
  58: resource "azurerm_application_gateway" "app_gateway" {


Error: expected probe.0.protocol to be one of [Http Https], got http

  with module.redsail_agw["eastus"].azurerm_application_gateway.app_gateway,
  on modules/agw/agw.tf line 58, in resource "azurerm_application_gateway" "app_gateway":
  58: resource "azurerm_application_gateway" "app_gateway" {


Error: expected probe.1.protocol to be one of [Http Https], got https

  with module.redsail_agw["eastus"].azurerm_application_gateway.app_gateway,
  on modules/agw/agw.tf line 58, in resource "azurerm_application_gateway" "app_gateway":
  58: resource "azurerm_application_gateway" "app_gateway" {


Error: expected network_profile.0.load_balancer_sku to be one of [basic standard], got Standard

  with module.redsail_aks["eastus"].azurerm_kubernetes_cluster.aks_us,
  on modules/aks/aks.tf line 106, in resource "azurerm_kubernetes_cluster" "aks_us":
 106:     load_balancer_sku = var.aks_lb_sku
```

### Expected Behaviour

HTTP == Http == http
TCP == Tcp == tcp

### Actual Behaviour

HTTP != Http != http
TCP != tcp != tcp

### Steps to Reproduce

1. Attempt to modify any App Gateway Asset created by 2.x.

### Important Factoids

Seems that the same [patch applied in 2.99](https://github.com/hashicorp/terraform-provider-azurerm/issues/15635) should be added to 3.x.  

In checking the tfstate, the case-syntax of the failing asset matches one of the expected values.  I believe the "got" value to be returned from the API.

### References

* #15635

**Comment by katbyte** [comment]
Hi @treyhendon , thanks for opening this issue.

The casing the provider is expecting is what is specified by both the REST API specs (swagger) and SDK. The provider should be transparently translating the API responses to the correct casing expected by the SDK (and often other services). 

What happens when you use the casing the validation is suggesting there in your config?

**Comment by treyhendon** [comment]
Wow!  I didn't even inspect my module's values (only the tfstate).  I'm surprised `validate` didn't catch these.  Thanks, that seems to have been my issue.

I guess because 2.x had that patch applied, it was always able to work?

**Comment by katbyte** [comment]
@treyhendon glad to hear that fixed it for you! and the one you linked was specific to another specific resource but some of the work we did for 3.0 was starting to insert the case normalization code for enums into the provider. It was flagged off behind the beta however until we flipped everything on for 3.0.
