### ISSUE TITLE
azurerm_app_service_source_control & azurerm_app_service_source_control_slot container_configuration does not exists

### ISSUE THREAD

**Issue by Dilergore** [hashicorp/terraform-provider-azurerm#16081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 1.1.7
azurerm 3.0.2

### Affected Resource(s)

* `azurerm_app_service_source_control`
* `azurerm_app_service_source_control_slot`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_source_control" "wapp" {
  app_id = azurerm_linux_web_app.wapp.id

  container_configuration {
    registry_url = azurerm_container_registry.registry.login_server
    image_name   = local.image_name
  }
}

resource "azurerm_app_service_source_control_slot" "wapp-slot" {
  slot_id = azurerm_linux_web_app_slot.wapp_slot.id

  container_configuration {
    registry_url = azurerm_container_registry.registry.login_server
    image_name   = local.image_name
  }
}
```

### Expected Behaviour

As per the documentation I can create this resource.

### Actual Behaviour

```bash
Error: Unsupported block type
│
│   on appService.tf line 115, in resource "azurerm_app_service_source_control" "wapp":
│  219:   container_configuration {
│
│ Blocks of type "container_configuration" are not expected here.

│ Error: Unsupported block type
│
│   on appService.tf line 219, in resource "azurerm_app_service_source_control_slot" "wapp_slot_warmup":
│  219:   container_configuration {
│
│ Blocks of type "container_configuration" are not expected here.
```

### Steps to Reproduce
1. `terraform init`
2. `terraform plan`

### Description
By checking the code it seems the struct [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/source_control_resource.go#L20) & [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/source_control_slot_resource.go#L21) does not even contain `container_configuration`.

Based on the documentation this should be a configurable block.

**Comment by jackofallops** [comment]
Hi @Dilergore - You can use the [application stack block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#application_stack) to specify the image settings for docker, for example on a linux app:
```hcl
  site_config {
    application_stack {
      docker {
        registry_url = "https://mcr.microsoft.com"
        image_name   = "azure-app-service/samples/aspnethelloworld"
        image_tag    = "latest"
      }
    }
  }
```

The schema is slightly different on Windows Apps, but that's covered in the `application_stack` docs for that resource also.

Hope that helps!

**Comment by Dilergore** [comment]
@jackofallops - OMG I missed this. I also should get more ☕. Thanks, I am closing this.
