### ISSUE TITLE
Cosmosdb indexing policy capitalization

### ISSUE THREAD

**Issue by noiano** [hashicorp/terraform-provider-azurerm#16086]
After upgrading to version `v3.0.2` due to the fix of #16068 I noticed a strage behaviour, this time affecting cosmodb resources. Even after a successful apply, just by running `terraform` apply again, I see terraform trying to capitalize the `indexing_policy` over and over again.

```
 ~ indexing_policy {
        ~ indexing_mode = "consistent" -> "Consistent"

          # (1 unchanged block hidden)
      }
```

I mean it's no biggie given that it doesn't seem to do much ... It's just an annoyance 😄 

### Terraform (and AzureRM Provider) Version

```bash
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.19.1
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2
+ provider registry.terraform.io/hashicorp/helm v2.4.1
+ provider registry.terraform.io/hashicorp/kubernetes v2.9.0
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/tls v3.1.0
```

### Affected Resource(s)

* `azurerm_cosmosdb_sql_container`

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by katbyte** [comment]
Hi @noiano, sorry that your having this issue

As part of the 3.0 upgrade we are starting to move towards using the casing specified by the rest API specs and SDK. The provider should be validing the config is using that casing and transparently translating the API responses to casing used in the SDK. It looks like the SDK is using `consistent` for this property.

What casing are you using in your config? and what happens when you use `consistent` in your config?

**Comment by noiano** [comment]
Hello,
thank you for you answer. Switching to `consistent` 

```
indexing_policy {
    indexing_mode = "consistent"

    included_path {
      path = "/*"
    }
  }
```

Solved the "problem" ... now terraform doesn't try capitalize the indexing policy any more. Are there any more of these changes? If so where can I find them?

Thank you for your time :)

**Comment by sinbai** [comment]
@noiano thank you for opening this issue. I submitted a PR to fix this issue, setting case-sensitive for `indexing_mode` property of 3.0. The resources involved are azurerm_cosmosdb_sql_container and azurerm_cosmosdb_gremlin_graph. It is expected to release in the upcoming v3.1.0 release. Could you track it and let me know whether you are unblocked?

**Comment by sinbai** [comment]
@noiano For the above context, are you okey if we close this issue?

**Comment by noiano** [comment]
Absolutely, thank you for checking in
