### ISSUE TITLE
Reopen #14567 Support for SQL Managed Instance - It has not been implemented by the fix listed

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/terraform-provider-azurerm#16096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#14567 Support for SQL Managed Instance Has been closed as listed as fixed under #13748 mssql_db: add support for transparent data encryption.

This request was NOT to support it at the database level but to allow us to enable it at the server level, specifiying the key vault / key it will use.

**Comment by katbyte** [comment]
Sorry about that @Marcus-James-Adams, I'll open that issue now!
