### ISSUE TITLE
Documentation errors for Service Plan and Linux/Windows Web App resources

### ISSUE THREAD

**Issue by bothzoli** [hashicorp/terraform-provider-azurerm#16090]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM Provider: v3.0.1

### Affected Resource(s)

* `azurerm_service_plan`
* `azurerm_linux_web_app`
* `azurerm_windows_web_app`

### Expected Behaviour

There are the following errors in the documentation for the aforementioned resources:

* `azurerm_service_plan`
  * `os_type` argument is required, but the example usage does not contain it, which is a bit misleading
* `azurerm_linux_web_app` and `azurerm_windows_web_app`
  * a `name` argument in the `connection_string` block is required (this is missing in the documentation)
  * in the `site_config` block there is an argument `websockets` which should really be `websockets_enabled` (see [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/c627ee20db6cec2c6544e6d14d4c2629501c2a5a/internal/services/appservice/helpers/web_app_schema.go#L41))

**Comment by OliDow** [comment]
Thanks @bothzoli 

This got me for an hour, needs updating!
