### ISSUE TITLE
azurerm_data_factory_linked_service_data_lake_storage_gen2 validation too strong. 

### ISSUE THREAD

**Issue by skoya** [hashicorp/terraform-provider-azurerm#16093]
[azurerm_data_factory_linked_service_data_lake_storage_gen2](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_data_lake_storage_gen2)

I would like to be able to set url and other fields to use ADF parameters but terraform mandates url starts with https: .  It is possible to set this in the ADF interface then perform terraform import, but we cannot then do terraform apply as the validation rule stops us.  

Ideally we want to be able to set url = "@Dataset().ST_URL".  I cannot see a way of disabling the terraform validation on this one field?

**Comment by katbyte** [comment]
Hi @skoya - we can certainly relax the validation for this property. will all ADF params be in the format of `@dataset().SOETHING` ?

**Comment by skoya** [comment]
I think this is the one liner stopping it from working:  https://github.com/hashicorp/terraform-provider-azurerm/blob/3bb83a994d9c8f8f430de4d14db5a6c1e537de95/internal/services/datafactory/data_factory_linked_service_data_lake_storage_gen2_resource.go#L55

Azure data factory can parameterise most fields so standard validation can't work.  (basically should be free fields)  We have had to drop out to JSON and az rest cli to get what we need.
