### ISSUE TITLE
Azure Front Door is not populating address or host_header in plan

### ISSUE THREAD

**Issue by brennfoster** [hashicorp/terraform-provider-azurerm#16111]
Getting the below error when trying to create a Front Door resource. This resource is dependent on a function app 'default_host_name' output that is used to set the 'address' and 'host_header' fields on the backend block.

│ Error: creating Front Door
│ Front Door performing CreateOrUpdate: frontdoors.FrontDoorsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="Backend \"\" has an invalid address. The address field must be an IPv4 address, IPv6 address, or fully-qualified domain name.; \nHostName cannot be null or empty."
│ 
│   with module.front_door.azurerm_frontdoor.default,
│   on Modules/FrontDoor/main.tf line 1, in resource "azurerm_frontdoor" "default":
│    1: resource "azurerm_frontdoor" "default" {

When I inspect the outputted plan, I don't see the 'address' or 'host_header' fields being populated. I don't see how this passed validation without those fields being populated since they are required fields.
![image](https://user-images.githubusercontent.com/419283/160461005-05b90a4f-d566-46bd-ad4b-f8d95d3faab9.png)

That all said, I'm comparing the most recent terraform plan to a previous plan using the same configuration and I can actually see the 'address' and 'host_header' fields getting set on the second backend block here:
![image](https://user-images.githubusercontent.com/419283/160461304-f51c39d3-3bb0-4aa4-af78-2790a081f652.png)

This started occurring when I upgraded the azurerm provider to v3. Specifically: hashicorp/azurerm v3.0.2.

**UPDATE:**
Setting the 'address' and 'host_header' fields to static values is showing correctly in the plan but I'm still getting a Bad Request response from the azure api stating that it isn't valid.

**Comment by brennfoster** [comment]
It looks like the problem might be that the Function App output is not working correctly but I am having a hard time figuring out where the problem actually lies.

**Comment by Romiko** [comment]
I have the same issue after upgrading to azurerm provider v3.

**Comment by Romiko** [comment]
There seems to be a bug with:
      host_header = azurerm_windows_function_app.function.default_hostname
      address     = azurerm_windows_function_app.function.default_hostname

So I agree with @brennfoster  the Function App output is not working correctly.

Can we get this resolved?

**Comment by brennfoster** [comment]
Closing this issue in favor of this one: https://github.com/hashicorp/terraform-provider-azurerm/issues/16263
