### ISSUE TITLE
azurerm_mssql_database does not have DTU setting

### ISSUE THREAD

**Issue by hugo-zhang-uipath** [hashicorp/terraform-provider-azurerm#16114]
Hi, I am trying to change my terraform code use azurerm_mssql_database  from the old one azurerm_sql_database. However my currently DB's are using DTU price tiers. But I don't see azurerm_mssql_database support DTU setting.

**Comment by sinbai** [comment]
@hugo-zhang-uipath thank you for openning this issue. Does the above reply solve your problem? If not, could you please provide information about tf config and location of azurerm_sql_database?

**Comment by Lddeiva** [comment]
Hi @hugo-zhang-uipath , Can you please confirm if the solution provided worked or not? Thanks.
