### ISSUE TITLE
azurerm_recovery_services_vault could not be updated after encryption using customer-managed keys

### ISSUE THREAD

**Issue by sinbai** [hashicorp/terraform-provider-azurerm#16116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.1.7
Provider registry.terraform.io/hashicorp/azurerm v3.0.2

### Affected Resource(s)

* `azurerm_recovery_services_vault`

### Terraform Configuration Files

```
provider "azurerm" {
  features {
   key_vault {
      purge_soft_delete_on_destroy = true
    }
	}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	  version = "3.0.2"
    }
  }
}

resource "azurerm_resource_group" "test" {
  name     = "recovery-sample"
  location = "eastus"
}

resource "azurerm_recovery_services_vault" "test" {
  name                = "recovery-services-vault-sample"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"

  identity {
    type = "SystemAssigned"
  }

  soft_delete_enabled = true

  encryption {
    key_id                            = azurerm_key_vault_key.test.id
    use_system_assigned_identity      = true
    infrastructure_encryption_enabled = false
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "test" {
  name                        = "key-vault-sample-329"
  location                    = azurerm_resource_group.test.location
  resource_group_name         = azurerm_resource_group.test.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Create",
      "Decrypt",
      "Encrypt",
      "Delete",
      "Get",
      "List",
      "Purge",
      "UnwrapKey",
      "WrapKey",
      "Verify",
    ]
    secret_permissions = [
      "Set",
    ]
  }
}

resource "azurerm_key_vault_key" "test" {
  name         = "acctest-key-vault-key-0325"
  key_vault_id = azurerm_key_vault.test.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
     "wrapKey",
  ]
}
```
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour
The `azurerm_recovery_services_vault` should be updated sucessfully.

### Actual Behaviour

 Error: creating/updating Recovery Service Vault: (Name "recovery-services-vault-sample" / Resource Group "recovery-sample"): recoveryservices.VaultsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="EncryptionDetailsAbsent" Message="Encryption\u202fdetails\u202fmissing in the\u202fsubsequent\u202fPUT\u202fcall. Please\u202fensure valid encryption\u202fdetails\u202fare sent as\u202fa\u202fpart\u202fof\u202fthe subsequent\u202fPUT\u202fcall"
│
│   with azurerm_recovery_services_vault.test,
│   on 15675.tf line 23, in resource "azurerm_recovery_services_vault" "test":
│   23: resource "azurerm_recovery_services_vault" "test" {

### Steps to Reproduce

1. `terraform apply` the tf config above.
2. Add tags for `azurerm_recovery_services_vault` by adding the config below and then  `terraform apply` .
```
  tags = {
    ENV = "test"
  }
```

### Important Factoids
Any changes of `azurerm_recovery_services_vault` will result in the above error.

### References
https://docs.microsoft.com/en-us/azure/backup/encryption-at-rest-with-cmk?tabs=portal#enable-encryption-using-customer-managed-keys-at-vault-creation-in-preview

* #0000

**Comment by myc2h6o** [comment]
This resource users `CreateUpdate` function for both create and update, in this function it creates the resource with empty CMK first, then update it to the expected value. Which causes the API to throw error on calling the Create API. (It worked earlier but started to break later after the feature was introduced) Probably this function needs to be separated into two.
https://github.com/hashicorp/terraform-provider-azurerm/blob/b0f6b7f8d87b6a0486afaabce5e9f87d8a60e41f/internal/services/recoveryservices/recovery_services_vault_resource.go#L289-L290

I'm considering looking into this, please let me know if someone has already started the work
