### ISSUE TITLE
Support for avoiding rolling nodes in a VMSS

### ISSUE THREAD

**Issue by whites11** [hashicorp/terraform-provider-azurerm#16120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am using `linux_virtual_machine_scale_set` to deploy a VMSS backing up a kubernetes cluster.
It is critical for my use case that I control when and how instances in a VMSS are rebooted.

If I set `upgrade_mode` to `Rolling` and change the os image during a routine upgrade, azure reimages all my instances without respecting any termination handler and thus causing an outage.

If I set `upgrade_mode` to `Manual`, terraform-provider-azurerm rolls issues an `UpdateInstance` to all instances and that causes Azure to reboot my nodes (because the OS image is changed).

In any case there is no way to apply the new settings to the VMSS and leaving the burden of updating instances to the user.

I noticed in the code there seems to be a flag to allow users to opt out from this behavior: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/virtual_machine_scale_set_update.go#L50

But I don't see a way to set a value to that flag and the default (feature enabled) is always used.

Am I missing something?

### New or Affected Resource(s)

* azurerm_linux_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "vmss1" {
   ...
  upgrade_mode    = "Manual"
  ...
```

### References

N/A

**Comment by t3mi** [comment]
@whites11 assuming the latest 3.0 provider is used, following provider [feature ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#virtual_machine_scale_set) could be leveraged:
```hcl
provider "azurerm" {
  features {
    virtual_machine_scale_set {
      roll_instances_when_required = false
    }
  }
}
```

**Comment by whites11** [comment]
> @whites11 assuming the latest 3.0 provider is used, following provider [feature ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#virtual_machine_scale_set) could be leveraged:
> 
> ```terraform
> provider "azurerm" {
>   features {
>     virtual_machine_scale_set {
>       roll_instances_when_required = false
>     }
>   }
> }
> ```

Oh nice! I couldn't find how to do so in the docs (probably didn't search hard enough).
Thanks a lot @t3mi
