### ISSUE TITLE
Not able to add Customer managed key with Terraform in Azure data factory

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform-provider-azurerm#16148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

/*
* # Azure DataFactory
* This module creates an Azure Data Factory
*/

locals {
  common_name = join("-", compact([var.uai, var.appName, var.environment]))
  tags = {
    env     = var.environment
    uai     = var.uai
    appname = var.appName
    role    = var.role
  }
}

# Get Existing Keyvault 

data "azurerm_client_config" "current" {}

data "azurerm_key_vault" "services_vault" {
  name                = var.keyvault_name
  resource_group_name = var.keyvault_rg_name
}

# Create an User Managed Identity

resource "azurerm_user_assigned_identity" "adf_identity" {
  name                = "${local.common_name}-adfidentity"
  location            = var.location
  resource_group_name = "${var.uai}-${var.appName}-${var.environment}-rg"
  tags                = local.tags
}

# Assign keyvault access policies to user managed identity

resource "azurerm_key_vault_access_policy" "key_access" {
  key_vault_id       = data.azurerm_key_vault.services_vault.id
  tenant_id          = data.azurerm_client_config.current.tenant_id
  object_id          = azurerm_user_assigned_identity.adf_identity.principal_id
  key_permissions    = ["get", "list", "unwrapkey", "wrapkey", "encrypt", "decrypt", "sign", "verify"]
  secret_permissions = ["Get", "List"]
  depends_on = [azurerm_user_assigned_identity.adf_identity]
}

# Generate Keyvault key

resource "azurerm_key_vault_key" "generated" {
  name         = "${var.uai}-${var.appName}-${var.environment}-adfkey"
  key_vault_id = "/subscriptions/${var.sub_id}/resourceGroups/${var.keyvault_rg_name}/providers/Microsoft.KeyVault/vaults/${var.keyvault_name}"
  key_type     = "RSA"
  key_size     = 2048
  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

# Create an Azure Data Factory (ADF)

resource "azurerm_data_factory" "data-factory" {
  depends_on = [azurerm_key_vault_key.generated]
  name                    = "${var.uai}-${var.appName}-${var.environment}-adf"
  location                = var.location
  resource_group_name     = "${var.uai}-${var.appName}-${var.environment}-rg"
  tags                    = local.tags
  public_network_enabled  = false
  customer_managed_key_id = azurerm_key_vault_key.generated.id

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.adf_identity.id]
  }

  # enable ADO intergration with ADF if needed

  /* vsts_configuration {
    account_name    = var.account_name
    branch_name     = var.branch_name
    project_name    = var.project_name
    repository_name = var.repo_name
    root_folder     = var.root_folder
    tenant_id       = var.tenant_id
  } */

  lifecycle {
    ignore_changes = [tags]
  }
}

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Error: creating/updating Data Factory: (Factory Name "uai3030275-lm-bi-2-0-shopfloor-prod-adf" / Resource Group "uai3030275-lm-bi-2-0-shopfloor-prod-rg"): datafactory.FactoriesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="CMKUserManagedIdentityNotFound" Message="Operation failed. Managed identity used in CMK not found."
│

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sahitya12** [comment]
can anyone help me to get this resolved

**Comment by aristosvo** [comment]
Add a [customer_managed_key_identity_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory#customer_managed_key_identity_id) to your ADF configuration: it specifies the ID of the user assigned identity associated with the Customer Managed Key. Must be supplied if `customer_managed_key_id` is set.
