### ISSUE TITLE
Change address space on vNet

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azurerm#16146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.99

### Affected Resource(s)

* `azurerm_virtual_network`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16", "10.1.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]
```

### Expected Behaviour

As per https://github.com/hashicorp/terraform-provider-azurerm/issues/812 and https://azure.microsoft.com/en-in/blog/how-to-resize-azure-virtual-networks-that-are-peered-now-in-preview/ Azure now supports adding IP address spaces without having to de-peer and re-peer a vNet.

### Actual Behaviour

When trying to add an address space to an existing vNet, I get the error 

```
│ Error: creating/updating Virtual Network: (Name "vnet-name" / Resource Group "resource-group-name"): network.VirtualNetworksClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="VnetAddressSpaceCannotChangeDueToPeerings" Message="Address space of the virtual network /subscriptions/sub-id/resourceGroups/rg-name/providers/Microsoft.Network/virtualNetworks/vnet-name cannot change when virtual network has peerings." Details=[]

```

### Steps to Reproduce

- Deploy a vNet with 1 IP address space
- Peer the vNet with another vNet
- Add a IP address space to the first vNet
- Error above appears

### References

* #0000

**Comment by bubbletroubles** [comment]
I just realised we haven't registered the provider Microsoft.Network/AllowUpdateAddressSpaceInPeeredVnets  on the subscription. Will try that first.

**Comment by WilliamDahlen** [comment]
> I just realised we haven't registered the provider Microsoft.Network/AllowUpdateAddressSpaceInPeeredVnets on the subscription. Will try that first.

This worked for me. Just remember that you have to have the correct rbac role in the target subscriptions where the peered vnet's are originating from. I believe contributer should suffice.

**Comment by shadow100000** [comment]
Wrong

**Comment by neil-yechenwei** [comment]
@bubbletroubles , thanks for raising this issue. Per API error message returned by API, seems it's expected as the address space of the virtual network cannot be changed when virtual network has peering.

**Comment by bubbletroubles** [comment]
The question has been answered - solution is to register the preview feature Microsoft.Network/AllowUpdateAddressSpaceInPeeredVnets and then perform the config via Terraform
