### ISSUE TITLE
azurerm_application_gateway : backend_address_pool : Error: Invalid index

### ISSUE THREAD

**Issue by RoyC7** [hashicorp/terraform-provider-azurerm#16142]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2
+ provider registry.terraform.io/hashicorp/random v3.1.2
+ provider registry.terraform.io/hashicorp/time v0.7.2
```

### Affected Resource(s)

* azurerm_application_gateway `

### Terraform Configuration Files

```hcl

resource "azurerm_application_gateway" "apwfront" {
  name                = "apw-${lower(var.prefix)}-${lower(var.ending)}-frontend"
  resource_group_name = var.rgname
  location            = var.location
  zones               = [1, 2]

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 0
  }

  autoscale_configuration {
    max_capacity = 10
    min_capacity = 0
  }
  
  ssl_policy {
    policy_type          = "Custom"
    min_protocol_version = "TLSv1_2"
    cipher_suites        = ["TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256", "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"]
  }
  
  gateway_ip_configuration {
    name      = "appGatewayIpConfig"
    subnet_id = var.appgatewayid
  }

  frontend_ip_configuration {
    name                 = "appGwPublicFrontendIp"
    public_ip_address_id = var.pipapgwfrontid
  }

  backend_address_pool {
    name = "UIBackendPool"
  }

  frontend_port {
    name = "port_80"
    port = 80
  }

  frontend_ip_configuration {
    name                          = "appGwPrivateFrontendIp"
    subnet_id                     = var.appgatewayid
    #private_ip_address            = replace(var.appsubnet, "0/24", "11")
    private_ip_address =  split("-", var.prefix)[1] == "PREPROD" ? replace(var.appsubnet, "0/24", "13") : replace(var.appsubnet, "0/24", "11")
    private_ip_address_allocation = "Static"
  }


  http_listener {
    name = "UIRoutingRule"
    #frontend_ip_configuration_name = "appGwPrivateFrontendIp"
    frontend_ip_configuration_name = "appGwPublicFrontendIp"
    frontend_port_name             = "port_80"
    protocol                       = "Http"
  }

  request_routing_rule {
    name                       = "UIRoutingRule"
    rule_type                  = "Basic"
    http_listener_name         = "UIRoutingRule"
    backend_address_pool_name  = "UIBackendPool"
    backend_http_settings_name = "UIHttpSetting"
  }

  backend_http_settings {
    name                  = "UIHttpSetting"
    cookie_based_affinity = "Disabled"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 300
  }

}
```

### Panic Output
╷
│ Error: Invalid index
│
│   on main.tf line 142, in module "Vmssui":
│  142:   apgwpool      = module.ApplicationGatewayFend.apgwfront.backend_address_pool.0.id
│     ├────────────────
│     │ module.ApplicationGatewayFend.apgwfront.backend_address_pool is set of object with 1 element
│
│ Elements of a set are identified only by their value and don't have any separate index or key to select with, so it's only possible to perform operations across all elements of the set.
╵

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by katbyte** [comment]
Hey @RoyC7 ,

Thanks for opening this issue.

As 3.0 is a major release there have been a number of behaviour changes made, a complete list can be found [in the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - which is [linked from the changelog since this is a major version](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#300-march-24-2022).

In this case this `backend_address_pool ` was changed to be a set instead of a list to prevent reordering by the API (and allow users to change the order without having to update the resource). to fix this you should beable to use the `tolist` terraform function like so:

```
apgwpool = tolist(module.ApplicationGatewayFend.apgwfront.backend_address_pool)[0].id
```

Additionally there may be other changes you need to make to your Terraform Configuration to be compatible with v3.0 - we recommend consulting the upgrade guide.

**Comment by RoyC7** [comment]
Hello @katbyte,
Thanks for those info,

Was very helpful 

++

**Comment by akolupay** [comment]
Thanks @katbyte !

I beleive it will be good practice to add type of referenced attributes

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#attributes-reference
