### ISSUE TITLE
Name of azurerm_mssql_server_vulnerability_assessment is "Default" but read back as "default"

### ISSUE THREAD

**Issue by flobeier** [hashicorp/terraform-provider-azurerm#16140]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* Terraform v1.1.3
* azurerm 2.99.0

### Affected Resource(s)

* `azurerm_mssql_server_vulnerability_assessment`
* `azurerm_mssql_server_vulnerability_assessment_rule_baseline`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server_vulnerability_assessment" "example" {
  server_security_alert_policy_id = azurerm_mssql_server_security_alert_policy.example.id
  storage_container_path          = "${azurerm_storage_account.example.primary_blob_endpoint}${azurerm_storage_container.example.name}/"
  storage_account_access_key      = azurerm_storage_account.example.primary_access_key
}

resource "azurerm_mssql_database_vulnerability_assessment_rule_baseline" "legitimate_users" {
  # For some reason the vulnerability assessment is created with the name "Default" but read back from the API as "default",
  # which makes the following replacement necessary until this is fixed. Otherwise Terraform wants to recreate the resource on every run.
  server_vulnerability_assessment_id = replace(azurerm_mssql_server_vulnerability_assessment.example.id, "Default", "default")
  database_name                      = "master"
  rule_id                            = "VA2130"
  baseline_name                      = "master"
  baseline_result {
    result = [
      "${azurerm_mssql_server.example.administrator_login}",
      "${local.sql_server_admin_sid[local.environment]}"
    ]
  }
}
```

### Expected Behaviour

I should be able to use the exported attribute `azurerm_mssql_server_vulnerability_assessment.example.id` directly as value for `server_vulnerability_assessment_id`.

### Actual Behaviour
I have to replace "Default" in `azurerm_mssql_server_vulnerability_assessment.example.id` with "default", otherwise Terraform will try to redeploy the `azurerm_mssql_database_vulnerability_assessment_rule_baseline` resource on every run.

### Steps to Reproduce

1. `terraform apply`

**Comment by katbyte** [comment]
closing as duplicate of #16139

**Comment by flobeier** [comment]
@katbyte thanks, somehow I didn't make the connection.
