### ISSUE TITLE
zone-zone azurerm_site_recovery_replicated_vm Target network settings were either removed or are not configured.

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#16158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

azurerm 3.02
Terraform 1.1.5

### Affected Resource(s)

azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replicated_vm" "protected_vm_tf" {
  count                                     = var.dr_serviceclass == "Gold" ? 1 : 0
  name                                      = format("%s-%s", local.recovery_vault, local.vm_name)
  resource_group_name                       = var.support_resource_group
  recovery_vault_name                       = local.recovery_vault
  recovery_replication_policy_id            = data.azurerm_site_recovery_replication_policy.policy.id
  source_vm_id                              = local.virtual_machine_id
  source_recovery_fabric_name               = data.azurerm_site_recovery_fabric.fabric.name
  source_recovery_protection_container_name = data.azurerm_site_recovery_protection_container.primary.name
  target_zone                               = local.secondary_zone ? tonumber(local.secondary_zone) : "3"
  target_resource_group_id                  = data.azurerm_resource_group.virtualmachine_asr[0].id
  target_recovery_fabric_id                 = data.azurerm_site_recovery_fabric.fabric.id
  target_recovery_protection_container_id   = data.azurerm_site_recovery_protection_container.secondary.id
  target_network_id                         = data.azurerm_resources.vnet.resources[0].id 

  managed_disk {
    disk_id                    = lower(data.azurerm_managed_disk.os_disk.id)
    staging_storage_account_id = data.azurerm_storage_account.primary.id
    target_resource_group_id   = data.azurerm_resource_group.virtualmachine_asr[0].id
    target_disk_type           = var.disk_storage_account_type
    target_replica_disk_type   = var.disk_storage_account_type
  }

  depends_on = [
    azurerm_windows_virtual_machine.virtualmachine_windows, azurerm_virtual_machine.virtualmachine_migrated,
    azurerm_linux_virtual_machine.virtualmachine_linux, azurerm_virtual_machine_extension.virtualmachine_linux, azurerm_virtual_machine_extension.virtualmachine_windows
  ]
}
```

### Expected Behaviour

Disaster recovery replication configured, tried this with network configuration and without.. cannot find an example of how to do this correctly.

### Actual Behaviour

Target network settings are not configured for virtual machine
Target network settings were either removed or are not configured.

1. `terraform apply`

**Comment by myc2h6o** [comment]
Hi @mpjtaylor I've created a pr #16205 to add the example for this, it uses `target_zone` and sets `target_network_id` to the same network as the original VM

**Comment by mpjtaylor** [comment]
Thanks for this , i thought i had tried exactly your example but looks like it works :-)
