### ISSUE TITLE
Renaming existing GZRS Storage Account breaks the Config

### ISSUE THREAD

**Issue by Gill-Bates** [hashicorp/terraform-provider-azurerm#16151]
I made now twice the experience, that - once created - a GZRS storage account is put into a broken state when I try to rename it in Terraform and apply the Config. This can then only be solved by deleting the storage account through Ms via a support ticket.

`We have an update from PG team that stuck jobs were cancelled. Could you please retry the deletion now and let us know the status.`

The error message is caused, because the Storage Account is locked due to undergoing background tasks.

Are there any similar experiences?

`Module-Version: 2.9.9`

**Comment by magodo** [comment]
@Gill-Bates Thanks for submitting this! May I understand the issue you are hitting is that everytime you rename a `azurerm_storage_account` with GZRS, the deletion (as renaming name causes TF to replace it) will always fail into a state that can only be cleaned up via a support ticket? I just locally tested and verified renaming a GZRS storage account via TF can successfully be replaced.

**Comment by tombuildsstuff** [comment]
Closing since out since we've not heard back here - if this is still reproducible then please let us know and we can take another look.
