### ISSUE TITLE
azurerm_servicebus_subscription_rule keeps being replaced

### ISSUE THREAD

**Issue by IanMoroney** [hashicorp/terraform-provider-azurerm#16166]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2

### Affected Resource(s)

* `azurerm_servicebus_subscription_rule`

### Terraform Configuration Files

```hcl

resource "azurerm_servicebus_subscription" "b2c_product_event_listener" {
  count                                = var.enable_in_subscription ? 1 : 0
  name                                 = "b2c-product-event-listener"
  topic_id                             = azurerm_servicebus_topic.product_details[0].id
  max_delivery_count                   = 5
  default_message_ttl                  = var.default_message_ttl
  dead_lettering_on_message_expiration = var.dead_lettering_on_message_expiration
}

resource "azurerm_servicebus_subscription_rule" "b2c_product_event_listener" {
  count           = var.enable_in_subscription ? 1 : 0
  name            = "messageType"
  subscription_id = azurerm_servicebus_subscription.b2c_product_event_listener[0].id
  filter_type     = "SqlFilter"
  sql_filter      = "messageType IN ('feedProductCreated','feedProductUpdated','feedProductDeleted','productAttributesChanged','productImagesChanged','syncProduct')"
}

```

### Debug Output
(The full debug output is over 100,000 lines long, but this is the bit that pertains to the problem)
https://gist.github.com/IanMoroney/9a62b40e2cb0936413409730badba971

### Expected Behaviour

The plan should result in no changes
### Actual Behaviour

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # azurerm_servicebus_subscription_rule.b2c_product_event_listener[0] must be replaced
2022/03/30 16:47:01 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2022/03/30 16:47:01 [DEBUG] Azure Backend Request: 
HEAD /terraform-state/main.terraform.tfstateenv%3Adev HTTP/1.1
-/+ resource "azurerm_servicebus_subscription_rule" "b2c_product_event_listener" {
Host: ufurnishterraformstorage.blob.core.windows.net
User-Agent: Terraform/0.14.6
X-Ms-Date: Wed, 30 Mar 2022 15:47:01 GMT
X-Ms-Lease-Id: 0c7cec14-7c36-860e-2ec1-97989c524a4c
X-Ms-Version: 2018-11-09


      ~ id              = "/subscriptions/7ad715a6-3343-4c91-9393-bc09ac611c53/resourceGroups/dev-servicebus/providers/Microsoft.ServiceBus/namespaces/dev-ufurnish-events/topics/products/subscriptions/b2c-product-event-listener/rules/messageType" -> (known after apply)
        name            = "messageType"
      ~ subscription_id = "/subscriptions/7ad715a6-3343-4c91-9393-bc09ac611c53/resourceGroups/dev-servicebus/providers/Microsoft.ServiceBus/namespaces/dev-ufurnish-events/topics/products/subscriptions/b2c-product-event-listener" -> "/subscriptions/7ad715a6-3343-4c91-9393-bc09ac611c53/resourceGroups/dev-servicebus/providers/Microsoft.Servicebus/namespaces/dev-ufurnish-events/topics/products/subscriptions/b2c-product-event-listener" # forces replacement
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

The issue appears to be a casing problem, where it wants to replace:
`providers/Microsoft.ServiceBus/namespaces`
with
`providers/Microsoft.Servicebus/namespaces`

**Comment by xiaxyi** [comment]
@IanMoroney I tried to reproduct the issue, unfortunately, unable to get the same result. My test result shows the no change in second plan:
```
$ terraform plan
azurerm_resource_group.test: Refreshing state... [id=/subscriptions/xxx/resourceGroups/xiaxintest-servicebus]
azurerm_servicebus_namespace.test: Refreshing state... [id=/subscriptions/xxx/resourceGroups/xiaxintest-servicebus/providers/Microsoft.ServiceBus/namespaces/xiaxintestservicebusnamespace]
azurerm_servicebus_topic.forward_to: Refreshing state... [id=/subscriptions/xxx/resourceGroups/xiaxintest-servicebus/providers/Microsoft.ServiceBus/namespaces/xiaxintestservicebusnamespace/topics/xiaxintestservicebustopic-forward_to]
azurerm_servicebus_subscription.b2c_product_event_listener[0]: Refreshing state... [id=/subscriptions/xxx/resourceGroups/xiaxintest-servicebus/providers/Microsoft.ServiceBus/namespaces/xiaxintestservicebusnamespace/topics/xiaxintestservicebustopic-forward_to/subscriptions/b2c-product-event-listener]
azurerm_servicebus_subscription_rule.b2c_product_event_listener[0]: Refreshing state... [id=/subscriptions/xxx/resourceGroups/xiaxintest-servicebus/providers/Microsoft.ServiceBus/namespaces/xiaxintestservicebusnamespace/topics/xiaxintestservicebustopic-forward_to/subscriptions/b2c-product-event-listener/rules/messageType]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_resource_group.test has been changed
  ~ resource "azurerm_resource_group" "test" {
        id       = "/subscriptions/xxx/resourceGroups/xiaxintest-servicebus"
        name     = "xiaxintest-servicebus"
      + tags     = {}
        # (1 unchanged attribute hidden)
    }
  # azurerm_servicebus_namespace.test has been changed
  ~ resource "azurerm_servicebus_namespace" "test" {
        id                                  = "/subscriptions/xxx/resourceGroups/xiaxintest-servicebus/providers/Microsoft.ServiceBus/namespaces/xiaxintestservicebusnamespace"
        name                                = "xiaxintestservicebusnamespace"
      + tags                                = {}
        # (9 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to undo or respond to    
these changes.

─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

```

Is it possible to share the full script including "servicebus namespace" part?

Thanks~

**Comment by IanMoroney** [comment]
Will do.

Interestingly, I destroyed this resource using a targeted `terraform destroy`, re-applied it which re-created it, re-applied it again and it still said it needed replacing.

Still citing a difference between `Microsoft.ServiceBus` and `Microsoft.Servicebus`

**Comment by tombuildsstuff** [comment]
@IanMoroney can you confirm the casing on `azurerm_servicebus_subscription.b2c_product_event_listener[0].id`? My guess is this would be `ServiceBus` which would indicate we may need to normalize this in the Read function

**Comment by IanMoroney** [comment]
Thanks @tombuildsstuff, 
The `azurerm_servicebus_subscription.b2c_product_event_listener[0].id` field 
shows:
`/subscriptions/subscriptionid/resourceGroups/dev-servicebus/providers/Microsoft.Servicebus/namespaces/dev-ufurnish-events/topics/products/subscriptions/b2c-product-event-listener`

whereas `azurerm_servicebus_subscription_rule.b2c_product_event_listener[0].subscription_id`
has it as:
`/subscriptions/subscriptionid/resourceGroups/dev-servicebus/providers/Microsoft.ServiceBus/namespaces/dev-ufurnish-events/topics/products/subscriptions/b2c-product-event-listener`

**Comment by IanMoroney** [comment]
Our upgrade path went from 2.31 to 2.99, which included the servicebus `_id` changes in [2.91.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v2.91.0)
It then wanted to replace it on every apply since then.

My assumption is that at one point, `azurerm_servicebus_subscription.b2c_product_event_listener[0].id` contained an incorrectly cased `Microsoft.Servicebus` and no piece of terraform noticed it was the incorrect casing in the ID and tried to fix it.

If `azurerm_servicebus_subscription` enforced `Microsoft.ServiceBus` and forced a recreation, everything else downstream would be fixed.

**Comment by tombuildsstuff** [comment]
Thanks for confirming - we should look to normalize the casing of that within the ServiceBus package which should solve that 👍

**Comment by tombuildsstuff** [comment]
@xiaxyi can you take a look into that? ^

**Comment by xiaxyi** [comment]
> @xiaxyi can you take a look into that? ^

Sure @tombuildsstuff , I'll take care of it

**Comment by xiaxyi** [comment]
@IanMoroney Can you help to look at the value of the subscription_id in the state file since I suspect the value of the property remained unchanged even after the resource being recreated

**Comment by IanMoroney** [comment]
As a workaround, i had to manually modify the state file to change the casing of Servicebus, but ideally we shouldn't have to do that.
I feel like `azurerm_servicebus_subscription` should normalise to `Microsoft.ServiceBus` and that would solve this problem.

**Comment by xiaxyi** [comment]
@IanMoroney As I mentioned above, we do normalize the `azurerm_servicebus_subscription` in our latest version:
```
if subscriptionIdLit := d.Get("subscription_id").(string); subscriptionIdLit != "" {
		subscriptionId, _ := parse.SubscriptionID(subscriptionIdLit)
		resourceId = parse.NewSubscriptionRuleID(subscriptionId.SubscriptionId,
			subscriptionId.ResourceGroup,
			subscriptionId.NamespaceName,
			subscriptionId.TopicName,
			subscriptionId.Name,
			d.Get("name").(string),
		)
	} else if !features.ThreePointOhBeta() {
		resourceId = parse.NewSubscriptionRuleID(subscriptionId,
			d.Get("resource_group_name").(string),
			d.Get("namespace_name").(string),
			d.Get("topic_name").(string),
			d.Get("subscription_name").(string),
			d.Get("name").(string))
	}

```
We are not using the ID that's returned by the api directly. The reason I'm checking with you about the state is I'm deciding whether to deal with the previous state that you had used.

Anyway, as you workaround the issue, may  I know if the behavior is stabilized now? Are you getting any diff?

**Comment by IanMoroney** [comment]
The scenario is still there, it's just masked because i manually updated the state.

You could replicate the issue by manually modifying your state and change the ID of `azurerm_servicebus_subscription` to set `Microsoft.Servicebus`

You'll find that the `azurerm_servicebus_subscription` doesn't ask to get recreated (it should), but any rule hanging off that subscription will constantly ask to get recreated.

My argument is the `azurerm_servicebus_subscription` itself should be recreated if it doesn't detect `Microsoft.ServiceBus`

**Comment by tombuildsstuff** [comment]
@xiaxyi as mentioned above we'll need to ensure all usages of this are consistent (which includes adding a state migration), which'll fix the issue @IanMoroney is describing

**Comment by xiaxyi** [comment]
@tombuildsstuff , will try the state migration.

**Comment by IanMoroney** [comment]
@xiaxyi , i saw the PR and that some changes were requested, but then the PR was closed?
