### ISSUE TITLE
Management Group Data Source does not Recursively Resolve Child Subscriptions

### ISSUE THREAD

**Issue by droessmj** [hashicorp/terraform-provider-azurerm#16168]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Provider versions 2.97.0, 2.99.0. Believe the code matches the current latest but have not tested with 3.x due to module compatibility issues. 

### Affected Resource(s)

* azurerm_management_group

### Terraform Configuration Files

```hcl
data "azurerm_management_group" "mgmt_group" {
  name = var.mgmt_group_id
}

output "subscriptions" {
  value = data.azurerm_management_group.mgmt_group.subscription_ids
}
```

### Expected Behaviour

In a situation with nested management groups, all recursive subscription Ids should be resolved and presented. 

### Actual Behaviour

No recursive lookup occurs. Only top-level subscription Ids are returned in a nested management group situation. 

### Steps to Reproduce

1. Ensure you have a management group nested within a management group. 
2. Ensure subscriptions are within the child management group. 
3. Use the parent management group as the data source. 
4. Validate an empty response as there is no recursive lookup.

**Comment by tombuildsstuff** [comment]
@droessmj could you expand a little on the use-case you're looking to achieve here? I'm assuming this is ultimately related to Azure Security related items, which are assigned at the Subscription level?

**Comment by droessmj** [comment]
@tombuildsstuff sure. FWiw, I *think* that the PR linked above will resolve this issue. 

I'm looking to work from one parent management group reference and have a list of ALL subscriptions contained within the parent, with recursive lookups on any nested management groups. I don't have a current case for the Ids of any nested management groups, but I can see value in returning that information as well (as evidenced in the linked PR) simply as this info needs to be collected along the way to get the subscriptions. 

Hope that helps, happy to continue elaborating as necessary.

**Comment by droessmj** [comment]
The current use case is primarily for Activity Log integrations. You could easily argue that the best scenario would be to provision the Activity Log integration(s) as part of the subscription setup, but the real world is messy and I frequently work with security teams who layer on their own controls outside of the de facto subscription setup processes. I totally understand the desire to avoid brittle configurations, but, pragmatically, I'd lean towards giving the downstream consumers this capability as the "architecturally correct" approach is likely blocked by layers for organizational structure and process...and this is the next best option.

**Comment by JustinGrote** [comment]
Thank you for implementing! My use case was implementing remediation tasks for policy assigned at a management group level. Policy remediation has to be done on a per-subscription basis and I had to resort to making a custom script data source to get all the subscriptions prior, this will let me discontinue that portion and do it all in HCL. Thanks again!
