### ISSUE TITLE
public_network_access_enabled does not really work for resource azurerm_machine_learning_workspace

### ISSUE THREAD

**Issue by mingweihe** [hashicorp/terraform-provider-azurerm#16177]
public_network_access_enabled = false
public_network_access_enabled = true
both the above setup are not working for the azure machine learning workspace 
I tried azurerm 2.76.0, 2.78.0, 3.0.2, all same
![image](https://user-images.githubusercontent.com/40443935/160963514-27798899-dd09-47c0-844f-021ce0cbfe88.png)
The expected behavior should be:
false -> Disabled
true -> All networks

Please take a look, thanks!

**Comment by stephybun** [comment]
Hi @mingweihe,

Thanks for raising this issue.

There seem to be two problems here:

1. The property `public_network_access_enabled` doesn't actually control whether public network access is disabled or enabled, it actually sets whether public access is allowed when behind a virtual network. So this property should be renamed to something that reflects that behaviour better.

2. I attempted to add a new property that does control the public network access behaviour of the workspace but unfortunately it appears to be broken in the API. Changing the value doesn't seem to have any effect and it isn't returned by the API.

I will open a PR to address 1. and i've also raised this issue https://github.com/Azure/azure-rest-api-specs/issues/18601 to address 2.

Thanks again for bringing this to our attention and let's hope Azure can fix this in the API soon!
