### ISSUE TITLE
Support for Standard SKU as the default for LB and IP

### ISSUE THREAD

**Issue by anavinahar** [hashicorp/terraform-provider-azurerm#16172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We'd like to make Standard the default SKU in alignment with other clients for scenarios such as create LB, create IP, and create VM where these resources need to be deployed

### New or Affected Resource(s)

Load Balancer
Public IP address

**Comment by anavinahar** [comment]
Standard SKU

**Comment by anavinahar** [comment]
@magodo  when will this be live?

**Comment by magodo** [comment]
@anavinahar Since this is a breaking change, we will involve this when upgrading to v4.

**Comment by cburuzie** [comment]
@magodo Are the changes here live?

**Comment by stemaMSFT** [comment]
@cburuzie as @magodo previously mentioned, these changes are being prioritized for when AzureRM v4 is being released.

**Comment by cburuzie** [comment]
@stemaMSFT I am not familiar with AzureRM v4 release schedule. What is the target ETA for this?

**Comment by cburuzie** [comment]
@stemaMSFT @magodo Do we have an ETA for when these changes will go live?

**Comment by magodo** [comment]
@cburuzie Unfortunately I don't have the date.
