### ISSUE TITLE
azurerm_public_ip_prefix shows error when availability_zone is provided

### ISSUE THREAD

**Issue by thllxb** [hashicorp/terraform-provider-azurerm#16179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v1.0.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.0.2

### Affected Resource(s)

* `azurerm_public_ip_prefix`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = "test"
}
resource "azurerm_public_ip_prefix" "ip_prefixes" {
  name                = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  prefix_length       = 28
  availability_zone   = "No-Zone"
}
```

### Debug Output
https://gist.github.com/thllxb/a18bb0aaef979799b90c19a3ab99bf5c

### Panic Output
╷
│ Error: Unsupported argument
│
│   on main.tf line 11, in resource "azurerm_public_ip_prefix" "ip_prefixes":
│   11:   availability_zone   = "No-Zone"
│
│ An argument named "availability_zone" is not expected here.
╵

### Expected Behaviour
terraform plan should not output an error about `availability_zone`

### Actual Behaviour
terraform plan shows an error complaining  `availability_zone` is not expected here.

### Steps to Reproduce

1. `terraform plan`

**Comment by xiaxyi** [comment]
@thllxb are you going to make this public ip address as a no-zones one? if this is the case, you can just omit the property zone.

we've made changes to the zone/zones property in terraform provider 3.0:
_For the upcoming version 3.0 of the Provider we're making the identity and zones blocks behaviourally consistent across the Provider:

- To provision a resource with no-zones the zones field should be omitted

- To provision a resource in a single zone (that can only be provisioned in a single zone), the field zone should be set (e.g. zone = "1")

- To provision a resource in a single zone (that could be provisioned in multiple), the zones field should be set to a single value (e.g. zones = ["1"])

- To provision a resource in/across multiple zones, the field zones should be set to all available zones (e.g. zones = ["1", "2", "3"])_

refer to this pr #15405 

below are some samples:
1. No Zone
```
resource "azurerm_public_ip_prefix" "ip_prefixes" {
  name                = "nonzone"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  prefix_length       = 28
}
```
2. Zone-redundant 
```
resource "azurerm_public_ip_prefix" "ip_prefixes1" {
  name                = "zone-redun"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  prefix_length       = 28
  zones = ["1", "2", "3"]
}
```
3. Zonal
```
resource "azurerm_public_ip_prefix" "ip_prefixes2" {
  name                = "zonal"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  prefix_length       = 28
  zones = ["1"]
}
```

**Comment by thllxb** [comment]
@xiaxyi 
Thanks for your reply. The `no-zone` was just for an example. The error happens regardless what the value is.
Your reply confuses me, because 

1. from your reply, it seems `zones` is the new variable to replace `availability_zone`, but in https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/public_ip_prefix_resource.go#L123 `zones` is clearly marked as Deprecated, while in https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/public_ip_prefix_resource.go#L98 `availability_zone` is not.
2. in https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/public_ip_prefix_resource.go#L98 `availability_zone` is clearly still an acceptable argument, but the error tells me it is not expected.

**Comment by xiaxyi** [comment]
@thllxb 

As the code suggests, we're making the identity and zones blocks to be consistently using the commonSchema. 
```

			if features.ThreePointOhBeta() {
				s["zones"] = commonschema.ZonesMultipleOptionalForceNew()
			} else {
				s["availability_zone"] = &pluginsdk.Schema{
				...
					},
```
The property `availability_zone` will be replaced by the common property `Zones` in terraform 3.0. Can you try the code sample that I provided to see if the desired public ip prefix can be provisioned? feel free to let me know if you have any question or concern about the code sample.

**Comment by thllxb** [comment]
@xiaxyi I tried with `zones` and it worked. I guess it wasn't clear to me that `ThreePointOhBeta` actually is true in v3 release.
We can close this issue. Thank you for the help.

**Comment by xiaxyi** [comment]
@thllxb No Worries, glad to see it helps!
