### ISSUE TITLE
Terraform wants to remove customer_managed_key block of azurerm_storage_account on every run when using azurerm_storage_account_customer_managed_key resource

### ISSUE THREAD

**Issue by flobeier** [hashicorp/terraform-provider-azurerm#16188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v1.1.3
* azurerm 3.0.2

### Affected Resource(s)

* `azurerm_storage_account`
* `azurerm_storage_account_customer_managed_key`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "examplestor"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_storage_account_customer_managed_key" "example" {
  storage_account_id = azurerm_storage_account.example.id
  key_vault_id       = azurerm_key_vault.example.id
  key_name           = azurerm_key_vault_key.example.name
}
```

### Expected Behaviour

Terraform shouldn't try to remove the customer_managed_key block on every run.

### Actual Behaviour

Terraform tries to remove the customer_managed_key block on every run. This looks like a regression, it was working correctly before with azurerm 2.99.0

### Steps to Reproduce

1. `terraform apply`

**Comment by stephybun** [comment]
Thanks for taking the time to raise this issue @flobeier!

There is an existing issue detailing the same behaviour over in #16085. In short you need to add the following block to your `azurerm_storage_account`.
```
  lifecycle {
    ignore_changes = [customer_managed_key]
  }
```
This is unfortunately missing from the docs but will be updated in the next release to reflect that.

In order to avoid parallel discussions on the same issue I am going to close this one in favour of #16085.

Thanks!
