### ISSUE TITLE
Support for SKU option for azurerm_log_analytics_solution

### ISSUE THREAD

**Issue by vaclaond** [hashicorp/terraform-provider-azurerm#16189]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For some Log Analytics solutions, it is important to have option to define SKU. For example Azure Sentinel (SecurityInsights solution) costs savings are significant with Capacity reservation SKU.

### New or Affected Resource(s)

* azurerm_log_analytics_solution

### Potential Terraform Configuration

```hcl
resource "azurerm_log_analytics_solution" "example" {
  solution_name         = "SecurityInsights"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  workspace_resource_id = azurerm_log_analytics_workspace.example.id
  workspace_name        = azurerm_log_analytics_workspace.example.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/SecurityInsights"
  }

  sku {
    name = "CapacityReservation"
    capacityReservationLevel = 100
  }
}
```

### References

* #0000

**Comment by neil-yechenwei** [comment]
@vaclaond , thanks for raising this issue. Seems Log Analytics Solution API doesn't support this property.

**Comment by KennethMLdk** [comment]
A potential configuration should be like this:

```
resource "azurerm_log_analytics_solution" "example" {
  solution_name         = "SecurityInsights"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  workspace_resource_id = azurerm_log_analytics_workspace.example.id
  workspace_name        = azurerm_log_analytics_workspace.example.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/SecurityInsights"
  }

  sku = "CapacityReservation"
  reservation_capacity_in_gb_per_day = 100
}
```
Then the syntax matches azurerm_log_analytics_workspace capacity reservation arguments.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
