### ISSUE TITLE
`azurerm_cosmosdb_sql_container` removing `analytical_storage_ttl` needs to force replacement

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#16183]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

3.0.2

### Affected Resource(s)

* `azurerm_cosmosdb_sql_container`

### Expected Behaviour

Removing `analytical_storage_ttl` (or setting it to null) on `azurerm_cosmosdb_sql_container` should force a replacement of the container. The setting cannot be changed back once enabled on an existing container.

### Actual Behaviour

Terraform plan output:

```
 # azurerm_cosmosdb_sql_container.payments will be updated in-place
  ~ resource "azurerm_cosmosdb_sql_container" "payments" {
      - analytical_storage_ttl = -1 -> null

```

Terraform apply actually works fine - but the setting is just the same as before

```
azurerm_cosmosdb_sql_container.payments: Still modifying... 
azurerm_cosmosdb_sql_container.payments: Still modifying... 
azurerm_cosmosdb_sql_container.payments: Still modifying... 
azurerm_cosmosdb_sql_container.payments: Modifications complete after 32s 
```

### Steps to Reproduce

1. deploy a container with `analytical_storage_tt = -1`
2. Remove `analytical_storage_ttl ` and run terraform apply again 

### References

Feature was added in
* https://github.com/hashicorp/terraform-provider-azurerm/pull/11655
@favoretti

**Comment by sinbai** [comment]
@sebader For the above context, are you okey if we close this issue?

**Comment by sebader** [comment]
I didnt get to test this again but I would just trust it works now :)

**Comment by sinbai** [comment]
@sebader  thank you very much!
