### ISSUE TITLE
Support for user accounts in azurerm_batch_pool

### ISSUE THREAD

**Issue by fblampe** [hashicorp/terraform-provider-azurerm#16194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Batch Pools created through the Azure Portal can define an optional list of user accounts that should be used to run tasks (not to be confused with the Batch account the pool should be created in, or Managed Identities). The Azure API supports this too according to the docs: https://docs.microsoft.com/en-us/rest/api/batchmanagement/pool/create#useraccount

The Terraform resource azurerm_batch_pool doesn't support user accounts however, according to its docs: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool

Support for user accounts is necessary e.g. to run tasks using containers that expect to be run as a certain user (e.g. defined with `USER` in a Dockerfile). As Azure does not respect the default user of a container, it has to be set during task creation, and the user that is being set has to exist in the pool. That is currently not possible with Terraform (as far as I can tell).

### New or Affected Resource(s)/Data Source(s)

azurerm_batch_pool 

### Potential Terraform Configuration

```hcl
resource "azurerm_batch_pool" "pool" {
  name                = var.batch.pool.name
  account_name        = azurerm_batch_account.batch.name
  resource_group_name = azurerm_resource_group.rg.name
  [...]

  container_configuration {
    container_image_names = []
    container_registries = [{
      registry_server = "someRegistry.azurecr.io"
    }]
    type = "DockerCompatible"
  }

  user_accounts = [
    {
      name = "myUser"
      password = "very_secret123"
      elevation_level = "NonAdmin"
    }
  ]
}
```

### References

https://docs.microsoft.com/en-us/rest/api/batchmanagement/pool/create#useraccount
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool

**Comment by fblampe** [comment]
After days of trial and error and trying to make sense of the Azure Batch docs, I figured out how to make my containers run with the user predefined in the Dockerfile.

It's not exactly intuitive, but adding this part to the task configuration helps:
```json
"userIdentity": {
    "autoUser": {
        "scope": "pool",
        "elevationLevel": "admin"
    }
}
```

This way there's no need for a user to be defined in the pool itself, and the task will get its user from the Dockerfile as one would expect to be the default.

This means that I personally have no need for pool user accounts after all.
Feel free to close this issue, unless you want to keep it around as a reminder and for other people to find and vote for.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue, I am going to close this as mentioned above.
