### ISSUE TITLE
Support for additional Defender for Cloud autoprovisioning.

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#16216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, there is the resource "azurerm_security_center_auto_provisioning" this only handles VM security agent auto provisioning.

Defender for Cloud has more options for auto provisioning now:
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/69148538/161265009-505b1f01-1994-4ff4-a2cc-2e972f244eb4.png">

Could we update this resource to support all the new types of auto-provisioning? Or create a new resource with the new name "azurerm_defender_for_cloud_auto_provisioning"

### New or Affected Resource(s)/Data Source(s)

azurerm_security_center_auto_provisioning
azurerm_defender_for_cloud_auto_provisioning

### Potential Terraform Configuration

```hcl
resource "azurerm_defender_for_cloud_auto_provisioning" "example" {
  log_analytics_agent = "On"
  vulnerability_assessment = "On"
  guest_configuration_agent = "Off"
  defender_for_containers_components = "Off"
}
```

**Comment by neil-yechenwei** [comment]
@MattGarner-N , thanks for raising this issue. Seems it's API limitation. Seems the rest api doesn't support it.

**Comment by vireshdoshi-wpp** [comment]
Good find @MattGarner-N !  I was just looking for the same

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
