### ISSUE TITLE
Support for Defender for Cloud Pricing Advanced Configuration

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#16217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using Terraform to enable Defender for Cloud "containers" plan, it does not give any options to change the advanced configuration options and they are all turned off:
<img width="1456" alt="image" src="https://user-images.githubusercontent.com/69148538/161272286-964bfd87-e6cd-4045-abff-0a8b7b9e884a.png">

<img width="578" alt="image" src="https://user-images.githubusercontent.com/69148538/161272527-c4411a3b-33e9-46b1-98eb-9256dc901548.png">

### New or Affected Resource(s)/Data Source(s)

azurerm_security_center_subscription_pricing

### Potential Terraform Configuration

```hcl
resource "azurerm_security_center_subscription_pricing" "example" {
  tier          = "Standard"
  resource_type = "Containers"
  advanced_configuration = {
   deploy_security_profile = false
   azure_policy_for_kubernetes = true
  }
}
```

**Comment by neil-yechenwei** [comment]
@MattGarner-N , thanks for raising this issue. Seems I didn't find any rest api to support this feature. If it's possible, could you share the rest api link for this feature? Thanks in advance.

**Comment by p1johnson** [comment]
@MattGarner-N those settings are configured using Azure Policy. If you assign the following four policies to the subscription it will turn on the settings:

Deploy Azure Policy Add-on to Azure Kubernetes Service clusters
[Preview]: Configure Azure Kubernetes Service clusters to enable Defender profile
[Preview]: Configure Azure Arc enabled Kubernetes clusters to install the Azure Policy extension
[Preview]: Configure Azure Kubernetes Service clusters to enable Defender profile

**Comment by hansmbakker** [comment]
What about the `extensions` property in the rest call when enabling the `Standard` Cloud Posture plan?

When setting it to `On`
![image](https://user-images.githubusercontent.com/3463496/229120831-eed742e6-8298-479b-b1f6-e3ecc45c2e76.png)

this is the resulting batch call payload:
![image](https://user-images.githubusercontent.com/3463496/229120704-c1c0a39a-9fbe-47c9-9ff9-90543227bd49.png)

**Comment by tiwood** [comment]
@hansmbakker is right. If we could set extensions this would work. Something like:

```hcl
resource "azurerm_security_center_subscription_pricing" "foo" {
  resource_type = "StorageAccounts"
  tier          = "Standard"
  subplan       = "PerStorageAccount"

  extension {
    name    = "SensitiveDataDiscovery"
    enabled = true
  }

  extension {
    name    = "OnUploadMalwareScanning"
    enabled = true
    additional_properties = {
      capGBPerMonthPerStorageAccount = 10
    }
  }
}

```
