### ISSUE TITLE
Creation of Azure VM extension fails with ResourceGroupNotFound error

### ISSUE THREAD

**Issue by swatilekhapaul** [hashicorp/terraform-provider-azurerm#16220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.5

### AzureRM Provider Version

2.77.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl
Content of module:

resource "azurerm_virtual_machine_extension" "join-domain" {
  name                       = var.domain_join_resource_name
  virtual_machine_id         = var.virtual_machine_id
  publisher                  = "Microsoft.Compute"
  type                       = "JsonADDomainExtension"
  type_handler_version       = "1.3"
  auto_upgrade_minor_version = true

#         "OUPath": "${var.ou_path}",
  settings = <<SETTINGS
    {
        "Name": "${var.active_directory_domain}",
        "User": "${var.domainjoin-user-id}",
        "Restart": "true",
        "Options": "3"
    }
SETTINGS

  protected_settings = <<SETTINGS
    {
        "Password": "${var.domainjoin-user-password}"
    }
SETTINGS
}

Calling the module:
module "domain-join" {
  source                    = "./domain_join"
  domain_join_resource_name = "domain-test"
  virtual_machine_id        = element(concat(module.win_vm03.windows_virtual_machine_ids, [""]), 0)
  active_directory_domain   = "xx"
  ou_path                   = "OU=xx,DC=xx,DC=xx"
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.domain-join.azurerm_virtual_machine_extension.join-domain will be created
  + resource "azurerm_virtual_machine_extension" "join-domain" {
      + auto_upgrade_minor_version = true
      + id                         = (known after apply)
      + name                       = "domain-test"
      + protected_settings         = (sensitive value)
      + publisher                  = "Microsoft.Compute"
      + settings                   = jsonencode(
            {
              + Name    = "xx"
              + Options = "3"
              + Restart = "true"
              + User    = "xx"

  Enter a value: yes

module.domain-join.azurerm_virtual_machine_extension.join-domain: Creating...
╷│ Error: getting Virtual Machine "domain-test" (Resource Group "xx"): compute.VirtualMachinesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'xx' could not be found."
```

### Expected Behaviour

It should create the virtual machine extension

### Actual Behaviour

Receiving error provided in output

**Comment by myc2h6o** [comment]
Hi @swatilekhapaul thanks for opening the issue!
From the error message, looks like when getting the virtual machine detail, resource group doesn't exist. From the config `virtual_machine_id         = var.virtual_machine_id` the virtual machine id is passed from outside variable, maybe you want to double check if the variable is passed in correctly, and the virtual machine does exist when Terraform tries creating the extension. I also noticed you are using module, maybe there is a module deployment sequence or dependency which is not correctly set?

**Comment by swatilekhapaul** [comment]
@myc2h6o I was able to provision a VM using the same code and moreover its complaining about the resource group not existing but its in place. Also the VM was created successfully.

**Comment by swatilekhapaul** [comment]
Issue is resolved. Problem was with pointing the right subscription
