### ISSUE TITLE
Long Term Retention is not supported : Not supported for database with Free edition.

### ISSUE THREAD

**Issue by AlexPaskhin** [hashicorp/terraform-provider-azurerm#16231]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "mps_mssqldb" {
  name                 = "mps_db"
  server_id            = azurerm_mssql_server.mps_mssql.id
  collation            = "SQL_Latin1_General_CP1_CI_AS"
  sku_name             = var.sql_sku_name
  read_scale           = "false"
  zone_redundant       = "Local"
  storage_account_type = "Free"
}
```

### Debug Output/Panic Output

```shell
│ Error: retrieving Long Term Retention Policies for Database: (Name "mps_db" / Server Name "dev-mps-mssql" / Resource Group "dev-rg-mps-spa-studio-wallsmedia"): sql.LongTermRetentionPoliciesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LongTermRetentionPolicyNotSupported" Message="Long Term Retention is not supported : Not supported for database with Free edition."
│
│   with azurerm_mssql_database.mps_mssqldb,
│   on mssql.tf line 47, in resource "azurerm_mssql_database" "mps_mssqldb":
│   47: resource "azurerm_mssql_database" "mps_mssqldb" {
```

### Expected Behaviour

Pass

### Actual Behaviour

Error: retrieving Long Term Retention Policies for Database: 

### Steps to Reproduce

terraform apply or plan 

### Important Factoids

No

### References

None

**Comment by 1mamute** [comment]
Also getting this error using 3.5.0. Can't create a free tier Azure SQL database because of it.

**Comment by RockyMM** [comment]
I observe the same behaviour. 

Anyways, the 32 Megabytes database is not very useful. I am hoping more for support of the Free offer on the Serverless.
