### ISSUE TITLE
Error "Error: reading queue properties for AzureRM Storage Account" during deployment when build agent is behind firewall, with no access to data-plane.

### ISSUE THREAD

**Issue by mvervoort** [hashicorp/terraform-provider-azurerm#16240]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "this" {
  name = "myproject-rg"
}

resource "azurerm_storage_account" "this" {
  name                            = "marcovtest1ctfissuesa"
  resource_group_name             = data.azurerm_resource_group.this.name
  location                        = data.azurerm_resource_group.this.location
  account_kind                    = "StorageV2"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  access_tier                     = "Hot"
  min_tls_version                 = "TLS1_2"
  lifecycle {
    ignore_changes = [tags]
  }
}

output "sa_id" {
  value = azurerm_storage_account.this.id
}
```

### Debug Output/Panic Output

```shell
azurerm_storage_account.this: Still creating... [4m50s elapsed]
azurerm_storage_account.this: Still creating... [5m0s elapsed]
azurerm_storage_account.this: Still creating... [5m10s elapsed]
azurerm_storage_account.this: Still creating... [5m20s elapsed]
╷
│ Error: reading queue properties for AzureRM Storage Account "marcovtest1ctfissuesa": queues.Client#GetServiceProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with azurerm_storage_account.this,
│   on main.tf line 9, in resource "azurerm_storage_account" "this":
│    9: resource "azurerm_storage_account" "this" {
│ 
╵
```

### Expected Behaviour

```
azurerm_storage_account.this: Creating...
azurerm_storage_account.this: Still creating... [10s elapsed]
azurerm_storage_account.this: Still creating... [20s elapsed]
azurerm_storage_account.this: Creation complete after 22s [id=/subscriptions/xxxxxxxxxx/resourceGroups/myproject-rg/providers/Microsoft.Storage/storageAccounts/marcovtest1ctfissuesa]
```

### Actual Behaviour

```
azurerm_storage_account.this: Still creating... [4m50s elapsed]
azurerm_storage_account.this: Still creating... [5m0s elapsed]
azurerm_storage_account.this: Still creating... [5m10s elapsed]
azurerm_storage_account.this: Still creating... [5m20s elapsed]
╷
│ Error: reading queue properties for AzureRM Storage Account "marcovtest1ctfissuesa": queues.Client#GetServiceProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with azurerm_storage_account.this,
│   on main.tf line 9, in resource "azurerm_storage_account" "this":
│    9: resource "azurerm_storage_account" "this" {
│ 
╵
```

### Steps to Reproduce

1. Create an Azure Virtual Network
2. Create an Azure Firewall to filter for outbound traffic, not allowing access to `*.blob.core.windows.net` or `*.queue.core.windows.net`
3. Create a Azure DevOps self-hosted agent (or just a VM on which you run the Terraform) inside this Virtual Network
4. Run the Terraform template to create a Storage Account. The VM should have access to the Azure control-plane to create the Storage Account, but not have access to the data-plane (`*.blob.core.windows.net` or `*.queue.core.windows.net`)

### Important Factoids

Terraform is running behind a firewall, blocking access to `*.blob.core.windows.net` and `*.queue.core.windows.net`

### References

I noticed in [terraform-provider-azurerm/storage_account_resource.go line 1930 at main · hashicorp/terraform-provider-azurerm](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L1930) the error message `Error: reading queue properties for AzureRM Storage Account` shows up.
I think this is part of checking if the storage account is fully deployed and the data-plane is ready to receive requests. But as our self-hosted agent is behind a firewall which blocks access to the `*.blob.core.windows.net` and `*.queue.core.windows.net` (to limit data-exfiltration), it gives this error.

Running a CURL command on the same agent gives an SSL issue:
`curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to marcovtest1ctfissuesa.blob.core.windows.net:443`
Most likely as the Azure Firewall does not have the proper SSL certificate.

**Comment by mvervoort** [comment]
During initial `terraform apply` (and also during subsequent `terraform plan`) these lines are logged in the Azure Firewall which sits between the self-hosted agent (VM) and the storage account (on public internet):
| TimeGenerated | Message | FQDN | Action |
| ----------------- | ----- | ------ | ------ |
| 4-4-2022 08:39:45.693 | HTTPS request from 10.246.56.133:49072 to marcovtest1ctfissuesa.queue.core.windows.net:443. Action: Deny. No rule matched. Proceeding with default action | marcovtest1ctfissuesa.queue.core.windows.net | Deny |
| 4-4-2022 08:40:15.613 | HTTPS request from 10.246.56.133:49072 to marcovtest1ctfissuesa.queue.core.windows.net:443. Action: Deny. No rule matched. Proceeding with default action | marcovtest1ctfissuesa.queue.core.windows.net | Deny |
| 4-4-2022 08:41:15.639 | HTTPS request from 10.246.56.133:49072 to marcovtest1ctfissuesa.queue.core.windows.net:443. Action: Deny. No rule matched. Proceeding with default action | marcovtest1ctfissuesa.queue.core.windows.net | Deny |
| 4-4-2022 08:43:15.700 | HTTPS request from 10.246.56.133:49072 to marcovtest1ctfissuesa.queue.core.windows.net:443. Action: Deny. No rule matched. Proceeding with default action | marcovtest1ctfissuesa.queue.core.windows.net | Deny |

**Comment by mvervoort** [comment]
Thanks @tombuildsstuff for your feedback. Although this might seems to be related to #2977, I'm pretty sure it's a different issue. 
#2977 is about a public agent hitting the firewall of the storage account when creating a container. But this issue is about deploying the storage account (without container) and hitting the corporate Azure Firewall, which allows control-plane access, but not data-plane access.
It can also be replicated with:
```
resource "azurerm_storage_account" "this" {
  ...
  network_rules {
    default_action             = "Allow"
  }
}
```
Perhaps #9314 could help out, but I cannot find how to use/apply this.

**Comment by tombuildsstuff** [comment]
@mvervoort as per #9314 unfortunately this is blocked on Microsoft - the Data Plane and Resource Manager API's aren't feature-compatible and thus aren't interchangeable at this time. Once the API's contain the same fields, this'll unblock #9314 which'll ultimately fix this issue - where the Data Plane API has to be used (both for Containers etc, and the Storage Account itself).
