### ISSUE TITLE
Support for Azure NetApp Files backup policy

### ISSUE THREAD

**Issue by anthonymashford** [hashicorp/terraform-provider-azurerm#16242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, we do not see an option to configure Azure NetApp Files backup policy in Terraform.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/backup-configure-policy-based

### New or Affected Resource(s)/Data Source(s)

azurerm_netapp_volume

**Comment by lucgalasso** [comment]
Hello, 

Azure NetApp Files backup is GA since May 2024:
https://learn.microsoft.com/en-us/azure/azure-netapp-files/whats-new#may-2024

When will we see new Terraform resources for NetApp Files backup policy and backup vault?

Thank you!

**Comment by CarlRMorris101** [comment]
@paulomarquesc do you know when this will be available?
