### ISSUE TITLE
AKS oms agent cannot be disabled anymore

### ISSUE THREAD

**Issue by Meandron** [hashicorp/terraform-provider-azurerm#16259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.2

### AzureRM Provider Version

2.97.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
 # Relevant part only...
 oms_agent {
    log_analytics_workspace_id = azurerm_log_analytics_workspace.aks_monitoring.id
  }
}

# Trying to disable container insights by:
resource "azurerm_kubernetes_cluster" "aks" {
    # oms_agent block is deleted
}
```

### Debug Output/Panic Output

```shell
Terraform plan shows "No changes"
```

### Expected Behaviour

The Terraform plan shows expected change, i.e. oms agent will be removed

### Actual Behaviour

No planned changes shown after having performed "terraform plan"

### Steps to Reproduce

1. Created azurerm_kubernetes_cluster with AzureRM provider version < 2.97.0
2. Enabled oms_agent block
3. Updated to AzureRM version 2.97.0
3.1 Applied changes, like removing "addon_profile"
4. Removed oms_agent block  
5. Terraform plan

**Comment by ms-henglu** [comment]
Hi @Meandron ,

Thank you for taking time to report this issue!

It seems oms can be disabled if using azurerm v3.x, would you please give it a try?

**Comment by Meandron** [comment]
Just tried, however, ran into [this issue](https://github.com/hashicorp/terraform/issues/30746) which prevents me from further testing currently.

**Comment by stephybun** [comment]
@Meandron are you able to try disabling `oms_agent` after upgrading to Terraform v1.3?

**Comment by stephybun** [comment]
Closing since we haven't heard back. Hopefully this issue is resolved, if not please let us know and we can reopen this.

Thanks!
