### ISSUE TITLE
Support for Network Security Group association within Subnet resource

### ISSUE THREAD

**Issue by jpovey** [hashicorp/terraform-provider-azurerm#16256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Many organisations configure security policies within Azure to prevent subnet creation without an associated network security group. Please provide the option to associate a `azurerm_network_security_group` within the `azurerm_subnet` resource on creation. 

Terraform already provides a resource to link subnets and nsg post creation using `azurerm_subnet_network_security_group_association`. 

The `azurerm_virtual_network` resource also allows for nsg and subnet association but this resource is not as feature rich as `azurerm_subnet` and misses important attributes such as network polices, service endpoints etc

A property within the `azurerm_subnet` such as `network_security_group_id` would allow for direct association on creation and remove the need for a separate resource to link with the nsg

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
resource "azurerm_subnet" "example" {
  name                 = "frontend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]

  network_security_group_id = azurerm_network_security_group.example.id
}
```

**Comment by tombuildsstuff** [comment]
hi @jpovey 

This field has been intentionally removed from the `azurerm_subnet` resource to workaround issues within the Azure Platform during the deletion of resources, as this field has been intentionally removed unfortunately this isn't something we plan to reintroduce.

Instead #9022 is tracking adding an example of how to use Azure Policy with the separate resources, which'll fix this Azure Policy issue - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by jpovey** [comment]
Ahh ok that is a shame :(. Thanks Tom for your swift reply, I will track the others
