### ISSUE TITLE
 Error: "jioindiawest" was not found in the list of supported Azure Locations

### ISSUE THREAD

**Issue by motokotoboom** [hashicorp/terraform-provider-azurerm#16260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_public_ip, azurerm_storage_account, azurerm_network_interface

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "outbound_ip_address" {
  name                = "outbound_ip_address"
  resource_group_name = "your-rg"
  location            = "jioindiawest"
  allocation_method   = "Static"
  domain_name_label = "jioindiawestip"
  sku = "Standard"
}
```

### Debug Output/Panic Output

```shell
│ Error: "jioindiawest" was not found in the list of supported Azure Locations: "westus,westus2,eastus,centralus,centraluseuap,southcentralus,northcentralus,westcentralus,eastus2,eastus2euap,brazilsouth,brazilus,northeurope,westeurope,eastasia,southeastasia,japanwest,japaneast,koreacentral,koreasouth,southindia,westindia,centralindia,australiaeast,australiasoutheast,canadacentral,canadaeast,uksouth,ukwest,francecentral,francesouth,australiacentral,australiacentral2,uaecentral,uaenorth,southafricanorth,southafricawest,switzerlandnorth,switzerlandwest,germanynorth,germanywestcentral,norwayeast,norwaywest,brazilsoutheast,westus3,swedencentral,swedensouth"

#while az cli with the same sp shows:
az account list-locations -o table | grep jio
Jio India West            jioindiawest         (Asia Pacific) Jio India West
Jio India Central         jioindiacentral      (Asia Pacific) Jio India Central
```

### Expected Behaviour

azurerm_public_ip should be created

### Actual Behaviour

resources:
azurerm_public_ip
azurerm_storage_account
azurerm_network_interface
are not created with jioindiawest location with the same error

**Comment by sebader** [comment]
Have you successfully created the PIP with CLI (outside of terraform)? If this also does not work, this is not a TF bug

**Comment by motokotoboom** [comment]
yes, I have.
az network public-ip list -o table
Name                 ResourceGroup    Location      Zones    Address         AddressVersion    AllocationMethod    IdleTimeoutInMinutes    ProvisioningState
-------------------  ---------------  ------------  -------  --------------  ----------------  ------------------  ----------------------  -------------------
outbound_ip_address  xxxxxxx   jioindiawest           xxxxxxxx  IPv4              Static              4                       Succeeded

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this appears to be an issue in the Azure API where this information isn't being returned in the MetaData Endpoint: https://management.azure.com/metadata/endpoints?api-version=2018-01-01 - as such we'd need this information returned for it to be usable in Terraform.

In this instance I'd recommend reaching out to Azure Support about this, as this MetaData endpoint should be being populated for all new regions, but in the interim you should be able to workaround this by disabling Enhanced Validation by setting the Environment Variable `ARM_PROVIDER_ENHANCED_VALIDATION` to `false`.

Thanks!

**Comment by tombuildsstuff** [comment]
@motokotoboom unfortunately there isn't a newer API version returning that information, there's a number of different API versions for the metadata endpoint which return totally different schemas/information, rather than being additive.

**Comment by spawn08** [comment]
Any update on the above issue??

**Comment by tombuildsstuff** [comment]
`jioindiawest` is now returned from the endpoint, so this'll be fixed automatically: https://management.azure.com/metadata/endpoints?api-version=2018-01-01
