### ISSUE TITLE
azurerm_linux_function_app returns empty string from default_hostname

### ISSUE THREAD

**Issue by alex-zyl** [hashicorp/terraform-provider-azurerm#16263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {  }
}

data "azurerm_client_config" "current" {}

locals {
  function_name = "azfuncbugtest"
  rg_name       = "azfuncbugrg"
  location      = "eastus"
}

resource "azurerm_resource_group" "function" {
  name     = "azfuncbugrg"
  location = "eastus"
}

resource "azurerm_service_plan" "function" {
  name                = "${local.function_name}-plan"
  resource_group_name = azurerm_resource_group.function.name
  location            = azurerm_resource_group.function.location
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_storage_account" "function" {
  name                     = "${local.function_name}stor"
  resource_group_name      = azurerm_resource_group.function.name
  location                 = azurerm_resource_group.function.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_linux_function_app" "function" {
  name                        = "${local.function_name}-function"
  resource_group_name         = azurerm_resource_group.function.name
  location                    = azurerm_resource_group.function.location
  service_plan_id             = azurerm_service_plan.function.id
  storage_account_name        = azurerm_storage_account.function.name
  storage_account_access_key  = azurerm_storage_account.function.primary_access_key
  functions_extension_version = "~3"

  app_settings = {
    "FUNCTIONS_WORKER_RUNTIME"                 = "dotnet"
  }

  site_config {}
}

output "Function" {
  # showing only selected properties to skip sensitive data
  value = {
    function_url = azurerm_linux_function_app.function.default_hostname
  }
}
```

### Debug Output/Panic Output

```shell
No panic
```

### Expected Behaviour

The Linux azure function app should have ```default_hostname``` property set.

### Actual Behaviour

```default_hostname``` property value is empty

### Steps to Reproduce

1. terraform init
2. terraform apply

### References

Original report: https://github.com/hashicorp/terraform-provider-azurerm/issues/16176

**Comment by jshield** [comment]
just an addendum it's not just DefaultHostname quite a number of properties are missing.

**Comment by jdegiglio** [comment]
I've noticed the same behavior on the azurerm_windows_function_app resource and data objects, as well. I've just updated to version 1.1.8 and it's still a problem there.

As a workaround, I'm using the azurerm_function_app data object and retrieving the default_hostname for my function app from that.

**Comment by elthanor** [comment]
Have the same issue on azurerm v3.3.0, terraform v1.19.0

**Comment by ZinkNotTheMetal** [comment]
> I've noticed the same behavior on the azurerm_windows_function_app resource and data objects, as well. I've just updated to version 1.1.8 and it's still a problem there.
> 
> As a workaround, I'm using the azurerm_function_app data object and retrieving the default_hostname for my function app from that.

Can you share code on how you got the default_host name?

**Comment by erorubrz** [comment]
> I've noticed the same behavior on the azurerm_windows_function_app resource and data objects, as well. I've just updated to version 1.1.8 and it's still a problem there.
> 
> As a workaround, I'm using the azurerm_function_app data object and retrieving the default_hostname for my function app from that.

I just tried this and it works. That is confusing, but it's the best we got at the moment. Thanks for the tip! 👍

**Comment by jdegiglio** [comment]
> > I've noticed the same behavior on the azurerm_windows_function_app resource and data objects, as well. I've just updated to version 1.1.8 and it's still a problem there.
> > As a workaround, I'm using the azurerm_function_app data object and retrieving the default_hostname for my function app from that.
> 
> Can you share code on how you got the default_host name?

Here's a quick sample of how I'm using the azurerm_function_app data object to retrieve default_hostname:
```
resource "azurerm_windows_function_app" "your_windows_function_app" {
    all_your_properties_here = "values"
}

data "azurerm_function_app" "reference_to_your_windows_function_app" {
    name = azurerm_windows_function_app.your_windows_function_app.name
    resource_group_name = "your_resource_group_name_here"
}

# This will correctly return default_hostname, but Terraform will throw deprecation warnings (which is ok for now)
output "fa_url_deprecated" {
    value = data.azurerm_function_app.reference_to_your_windows_function_app.default_hostname
}

# This is the way we want to retrieve default_hostname when the new resources objects get fixed
output "fa_url" {
    value = azurerm_windows_function_app.your_windows_function_app.default_hostname
}
```

**Comment by ericfaure007** [comment]
I Have the same issue on azurerm v3.6.0.

**Comment by andrew-flatters-bliss** [comment]
> I Have the same issue on azurerm v3.6.0.

@ericfaure007  Think they prefer us to 👍 the original rather than putting comments in if we've reproduced it.

**Comment by Romiko** [comment]
I can confirm we have the same issue. Cannot wire up FrontDoor.

It is missing
frontdoor
    backend {
      host_header = azurerm_windows_function_app.function.default_hostname
      address     = azurerm_windows_function_app.function.default_hostname
      http_port   = 80
      https_port  = 443
    }

output missing address and host_header


+ backend {
              + enabled    = true
              + http_port  = 80
              + https_port = 443
              + priority   = 1
              + weight     = 50
            }

**Comment by pacorreia** [comment]
Any updates on this issue? would be really nice to get rid of deprecated resources warning.... we still need to rely on the old one

**Comment by eprokofev** [comment]
I Have the same issue on azurerm v3.9.0.

**Comment by SteveKurutz** [comment]
And 3.10.0

**Comment by pacorreia** [comment]
> And 3.10.0

Really? another version as this one is still missing?

So much for abandoning deprecated stuff

**Comment by jeramec** [comment]
I'm also having the same issue. AzureRM 3.10.0 and Terraform 1.2.3

**Comment by xiaxyi** [comment]
Thanks guys for pointing out this issue, please track the fix in the mentioned pr
