### ISSUE TITLE
The 'remote_debugging' not supported on azurerm_windows_web_app

### ISSUE THREAD

**Issue by KenticoMartinS** [hashicorp/terraform-provider-azurerm#16287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app, azurerm_windows_web_app_slot

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "group" {
  location = "West Europe"
  name     = "test-rg"
}

resource "azurerm_service_plan" "example" {
  name                = "test-rg-example1"
  resource_group_name = azurerm_resource_group.group.name
  location            = azurerm_resource_group.group.location
  sku_name            = "B1"

  os_type = "Windows"
}

resource "azurerm_windows_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.group.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    remote_debugging = true
  }
}
```

### Debug Output/Panic Output

```shell
terraform validate/plan/apply
╷
│ Error: Unsupported argument
│
│   on file.tf line 26, in resource "azurerm_windows_web_app" "example":
│   26:     remote_debugging = true
│
│ An argument named "remote_debugging" is not expected here.
```

### Expected Behaviour

The `remote_debugging` property in the `site_config` block is supported. 

### Actual Behaviour

An argument named `"remote_debugging"` is not expected here.

**Comment by ashutoshrathore** [comment]
I also encountered same issue while using "remote_debugging" argument in azurerm_windows_web_app, is there any update on fix?

**Comment by pierluca** [comment]
Reproduced with AzureRM Provider 3.9.0 and Terraform 1.1.9

**Comment by katbyte** [comment]
Closing as it appears this is supported via `remote_debugging_enabled` property
