### ISSUE TITLE
SAS token generated by azurerm_storage_account_blob_container_sas is invalid for app service backups

### ISSUE THREAD

**Issue by lotaezhao** [hashicorp/terraform-provider-azurerm#16295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_blob_container_sas, azurerm_storage_account_sas

### Terraform Configuration Files

```hcl
data "azurerm_storage_account_blob_container_sas" "backup_sas" {
  connection_string = var.storage_primary_connection_string
  container_name    = var.container_name
  https_only        = true

  start  = "2022-03-28T15:00:00+12:00"
  expiry = "2027-03-28T15:00:00+12:00"

  permissions {
    read   = true
    add    = false
    create = false
    write  = true
    delete = true
    list   = true
  }
}

#Note: azurerm_storage_account_blob_container_sas output does not prefix the token with '?' as azurerm_storage_account_sas 
#does so this is part of the url construction.
locals {
 backup_sas_url = "https://${var.storage_account_name}.blob.core.windows.net/${var.container_name}?${data.azurerm_storage_account_blob_container_sas.backup_sas.sas}"
}

resource "azurerm_app_service" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}

  backup {
    name                = "example-backup"
    enabled             = true
    storage_account_url = local.backup_sas_url

    schedule {
      frequency_interval       = 1
      frequency_unit           = "Day"
      retention_period_in_days = 30
      start_time               = "2022-03-28T16:00:00+12:00"
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A - the configuration works and terraform apply succeeds. However, when the app service backup runs it fails with error message as described in behavior below.
```

### Expected Behaviour

The SAS token should be in a format that works and and app_service backups should succeed.

### Actual Behaviour

The SAS token is in an invalid format and results in failed backups with the following error: **"Storage access failed. The remote server returned an error: (403) Forbidden.. Please delete and recreate backup schedule to mitigate."**

**azurerm_storage_account_blob_container_sas generated SAS token:**
```sv=2018-11-09&sr=c&st=2022-03-27T15%3A00%3A00%2B12%3A00&se=2027-03-27T15%3A00%3A00%2B12%3A00&sp=rwdl&spr=https&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D```

**az storage container generate-sas generated SAS token:**
```se=2022-04-29&sp=rwdl&sv=2018-11-09&sr=c&sig=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx%3D```

Above you can clearly see the differences in the sas token that is generated between using terraform and az cli. The AZ CLI generated sas works when enabling the backups in azurerm_app_service but the azurerm_storage_account_blob_container_sas does not. As per referenced previous issue below this has been known about since April 2020 but not resolved.

### Steps to Reproduce

1. Generate a SAS url for a storage container as per the above configuration.
2. Use the SAS url to enable backups for azurerm_app_service as per the above configuration.

### References

A previous issue has been raised for this in April 2020 but was closed without being resolved:
https://github.com/hashicorp/terraform-provider-azurerm/issues/6672

**Comment by magodo** [comment]
@lotaezhao Thanks for submitting this!

The config above seems have several issues:

1. The construction of `backup_sas_url` contains an extra `?`, as the `data.azurerm_storage_account_blob_container_sas.backup_sas.sas` already has the `?` prefix.
2. The format of `start` is incorrect, the decimal part of the second are not supported. Also, my local test shows that the timezone offset is not correctly recognized by the service (though the [document](https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-values) claimed it supports that). Would you mind try something like: `start  = "2022-03-28T15:00:00"`?

**Comment by lotaezhao** [comment]
@magodo Thanks for replying.

I have constructed the SAS url (which btw there is no documentation on) by checking the final output value. My tests showed that ```azurerm_storage_account_sas``` output includes the '?' but ```azurerm_storage_account_blob_container_sas``` does not.

I also validated the behavior by manually enabling the backups using Az CLI ```az webapp config backup create``` with both the  token generated via ```azurerm_storage_account_blob_container_sas``` and ```az storage container generate-sas```. I used just the sas token portion and constructed the sas url as per the MS example: https://docs.microsoft.com/en-us/azure/app-service/scripts/cli-backup-onetime

 The testing showed that the ```az storage container generate-sas``` version works but the terraform generated does not. I think this confirms that the sas url formatting is not the issue.
 
 I will try the timestamp suggestion and report back. In general there a lack of documentation around the timestamps that is very frustrating.

**Comment by lotaezhao** [comment]
@magodo

I just tested using a modified timestamp without the decimal part for seconds. Still the same error when the backup runs; ***"Storage access failed. The remote server returned an error: (403) Forbidden.. Please delete and recreate backup schedule to mitigate."***

```
resource "azurerm_app_service" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}

  backup {
    name                = "example-backup"
    enabled             = true
    storage_account_url = local.backup_sas_url

    schedule {
      frequency_interval       = 1
      frequency_unit           = "Day"
      retention_period_in_days = 30
      start_time               = "2022-04-11T11:00:00+12:00"
    }
  }
}
```

Here you can see that formatting of actual backup_sas_url that was used and that there is only one '?':
```https://xxxxxxxxxx.blob.core.windows.net/xxxx?sv=2018-11-09&sr=c&st=2022-04-11T10%3A00%3A00%2B12%3A00&se=2027-04-10T11%3A00%3A00%2B12%3A00&sp=rwdl&spr=https&sig=M9hk%2BZoX9yt97WKesWfpWcJEtBZu6ow7ryUX7y9Fcmg%3D```

I think this confirms there are no issues with the sas url or the timestamp and something else with the token generation is at fault.

**Comment by magodo** [comment]
@lotaezhao Would you try to remove the time zone offset in your `start` and `expiry` properties as *my local test shows that the timezone offset is not correctly recognized by the service (though the [document](https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-values) claimed it supports that)*?

**Comment by lotaezhao** [comment]
@magodo OK I'll try, using that to generate local NZST timezone.

**Comment by magodo** [comment]
@lotaezhao If the timezone is not the cause, then the only suspicion is the `sv`, which you can set in `azurerm_storage_account_sas`, but not in `azurerm_storage_account_blob_container_sas`. BTW, do you wan to redact the signature in this thread for secutiy purpose?

**Comment by lotaezhao** [comment]
@magodo OK I have a successful backup now after specifying the start/expiry date in ISO 8601 format without a time offset, nice spotting!

```"2022-04-11T02:20:00Z"```

This is quite a subtle issue as according to the documentation for ```azurerm_storage_account_sas``` the start and expiry dates should be in ISO 8601 format.  ISO 8601 does allow time offsets (https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC) in the same way as Terraform's preferred RFC 3389 format.

This being the case the documentation should be updated to reflect that we're dealing with a strict subset of ISO 8601. It's not helpful that app service accepts the sas url even though it is invalid either, you'd think there would be checks involved.

**Comment by magodo** [comment]
@lotaezhao Good news :+1: [That said](https://github.com/hashicorp/terraform-provider-azurerm/issues/16295#issuecomment-1093648453), the issue is the storage service behavior doesn't align with the [official document about SAS](https://docs.microsoft.com/en-us/rest/api/storageservices/formatting-datetime-values). I'll raise an issue about that. Meanwhile, I'll update the document of the provider (not sure whether add some additional validation to restrict the format is suitable, as it is regarded as a breaking change).

**Comment by magodo** [comment]
https://github.com/Azure/azure-rest-api-specs/issues/18631 submitted for this.

**Comment by lotaezhao** [comment]
@magodo Great thanks!
