### ISSUE TITLE
azurerm_windows_function_app_slot now requires a globally unique name for the slot itself

### ISSUE THREAD

**Issue by bdorplatt** [hashicorp/terraform-provider-azurerm#16305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.4

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app_slot

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "function_app" {
  service_plan_id             = var.asp_id
  location                    = var.region
  name                        = testapp-azf"
  resource_group_name         = var.resource_group_name
  storage_account_access_key  = var.sa_primary_access_key
  storage_account_name        = var.sa_name
  functions_extension_version = var.fa_extensions_version
  builtin_logging_enabled     = var.fa_builtin_logging_enabled

resource "azurerm_windows_function_app_slot" "function_app_slot" {
  name                        = "dev"
  function_app_id             = var.fa_id
  storage_account_access_key  = var.sa_primary_access_key
  storage_account_name        = var.sa_name
  functions_extension_version = var.fa_extensions_version
  builtin_logging_enabled     = var.fa_builtin_logging_enabled
```

### Debug Output/Panic Output

```shell
│ Error: the Site Name "testapp-azf" failed the availability check: Hostname 'dev' already exists. Please select a different name.
│ 
│   with module.fa_slot.azurerm_windows_function_app_slot.function_app_slot,
│   on .terraform/modules/fa_slot/main.tf line 1, in resource "azurerm_windows_function_app_slot" "function_app_slot":
│    1: resource "azurerm_windows_function_app_slot" "function_app_slot" {
│ 
│ the Site Name "testapp-azf" failed the availability check:
│ Hostname 'dev' already exists. Please select a different name.
```

### Expected Behaviour

The slot would be created with the Function app name and the slot name appended with a forward slash and would be globally  unique.
Example:
testapp-azf/dev

### Actual Behaviour

Error is thrown: Hostname 'dev' already exists.
The slot will only deploy if it is given its own globally unique name.

### Steps to Reproduce

Run a plan with the slot named something common that wouldn't be globally unique on its own.

### Important Factoids

This works as expected with the new resource: azurerm_windows_web_app_slot and previously worked correctly with  the azurerm_function_app_slot resource

**Comment by bdorplatt** [comment]
Hello @AaldertVanWijk-TomTom, We have only tested this as net new as we hadn't previously used this resource to deploy a slot. All previous deployments used the now-deprecated azurerm_function_app_slot resource.

I'd be curious if running the Terraform code again against the imported resource would try to destroy and re-create the slot. Have you tested that scenario with the workaround?

**Comment by AaldertVanWijk-TomTom** [comment]
@bdorplatt In my case after the import there are a lot of changes to the slot but there is no delete/create cycle

**Comment by aasier** [comment]
Hello all,

We are having the same issue when we are creating the "staging" slot with the latest provider version,

```
module.sfo_azure_function_node.azurerm_windows_function_app_slot.sfo_function_app_slot_staging,
│ on .terraform\modules\sfo_azure_function_node\azure\function\app_func.tf line 144, in resource "azurerm_windows_function_app_slot" "sfo_function_app_slot_staging":
│ 144: resource "azurerm_windows_function_app_slot" "sfo_function_app_slot_staging" { # SLOT STAGING
│
│ the Site Name "xxx-xxx" failed the availability check: Hostname 'staging' already exists. Please select a different name.
```

```
$ terraform version
Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.3.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.1.0

```

Could someone help here?

Thanks!! in advance,

**Comment by bdorplatt** [comment]
There is a PR for this now so hopefully it makes it into the next release: https://github.com/hashicorp/terraform-provider-azurerm/pull/16410

**Comment by AaldertVanWijk-TomTom** [comment]
@aasier 
I know of two work arounds,
1. manual creation and import as explained above
2. choose a more complex alt-slot name the issue only occurs with names that already happen to be used: "alt", "staging" "second", etc.

**Comment by aasier** [comment]
Thanks! @AaldertVanWijk-TomTom for your suggestions,
Finally, I did a null_resource running a shell script with some az-cli commands.
I´m interested about when is gonna be available the new release with this fix. https://github.com/hashicorp/terraform-provider-azurerm/pull/16410

**Comment by rgrace-puck** [comment]
I'm also seeing the same behavior in `azurerm_linux_function_app_slot` on version 3.7.0
