### ISSUE TITLE
`data_lake_store_file` support raw text contents

### ISSUE THREAD

**Issue by mbfrahry** [hashicorp/terraform-provider-azurerm#1630]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `data_lake_store_file` should support passing in raw text contents that will be stored in a data lake store in addition to the current capabilities of storing local files. 

### New or Affected Resource(s)

* azurerm_data_lake_store_file

### Potential Terraform Configuration

```hcl
resource "azurerm_data_lake_store_file" "example" {
  resource_group_name = "${azurerm_resource_group.example.name}"
  remote_file_path    = "/path/created/for/remote/file"
  raw_contents = ""Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.""
}
```

**Comment by catriona-m** [comment]
Closing this as this resource is no longer available. Thanks!
