### ISSUE TITLE
azurerm_app_configuration_key (type=vault) no mechanism to define the secret version (i.e latest)

### ISSUE THREAD

**Issue by mikegouldthorp** [hashicorp/terraform-provider-azurerm#16307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration" "appcfg" {
  name                = "test-tf-appconfig"
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
}

data "azurerm_key_vault_secret" "kvs" {
  name         = "key1"
  key_vault_id = data.azurerm_key_vault.kv.id
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.appcfg.id
  key                    = "key1"
  type                   = "vault"
  label                  = "label1"
  vault_key_reference    = data.azurerm_key_vault_secret.kvs.id
}
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

Im attempting to create an Azure App Config key (`type = vault`) that references an **existing** key vault secret. When the association is made it references the GUID of  **current** version of the secret.

See `vault_key_reference` secret GUID (cf32a6f....) below...

The challenge is that if the associated key vault secret value is updated or rotated the App Config continues to reference this specific secret version even if it its not current or even disabled.

```
  # azurerm_app_configuration_key.test will be created
  + resource "azurerm_app_configuration_key" "test" {
      + configuration_store_id = "/subscriptions/xxxxxx/resourceGroups/test-tf-rg/providers/Microsoft.AppConfiguration/configurationStores/test-tf-appconfig"
      + content_type           = (known after apply)
      + etag                   = (known after apply)
      + id                     = (known after apply)
      + key                    = "key1"
      + label                  = "label1"
      + locked                 = false
      + type                   = "vault"
      + value                  = (known after apply)
      + vault_key_reference    = "https://<redacted>.vault.azure.net/secrets/key1/cf32a6fxxxxxxxxxxxxx"
    }
```

When you manually edit a Key Vault App Config you are given the option to specify the "secret version" which can be set as "latest version'

I would think that there should be a similar argument for the `azurerm_app_configuration_key` resource.

<img width="701" alt="appcfg1" src="https://user-images.githubusercontent.com/56976171/162533514-defdc8fd-4848-46ef-83e5-4bf9004641cf.png">

<img width="713" alt="appcfg2" src="https://user-images.githubusercontent.com/56976171/162533196-56c721ad-45cb-4689-b108-595ca79dc4da.png">

As a test I tried specifying the secret WITHOUT the version GUID  for the `vault_key_reference` argument and it worked. Given that the `vault_key_reference` argument is not listed as a supported argument Im assuming that it not going to be a recommended approach to specific the "latest version" of the secret.

```
resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.appcfg.id
  key                    = "key1"
  type                   = "vault"
  label                  = "label1"
  vault_key_reference    = "https://test-tf-keyvault.vault.azure.net/secrets/key1"   <----- Referenced the specific secret WITHOUT the version GUID
}
```

### Actual Behaviour

App Config keys (type=vault) do not reference the latest version of the key vault secret.

**Comment by xiaxyi** [comment]
@mikegouldthorp can you try this property `versionless_id` instead of `id` in the `azurerm_app_configuration_key` resource?
```
resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.appcfg.id
  key                    = "key1"
  type                   = "vault"
  label                  = "label1"
  vault_key_reference    = azurerm_key_vault_secret.test.versionless_id
}
```

**Comment by mikegouldthorp** [comment]
Thank you @xiaxyi the 'versionless_id' property did the trick! It enabled us to reference the base \ latest version of the secret in the App Configuration.

**Comment by xiaxyi** [comment]
@mikegouldthorp No problems, happy to see the solution worked out!
