### ISSUE TITLE
verified parameter is missed in azurerm_iothub_dps_certificate 

### ISSUE THREAD

**Issue by xuwenjian1995** [hashicorp/terraform-provider-azurerm#16319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

1. We can use Az cli to create dps certificate with --verified parameter: https://docs.microsoft.com/en-us/cli/azure/iot/dps/certificate?view=azure-cli-latest#az-iot-dps-certificate-create

2. We failed to find such verified parameter in the Terraform:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub_dps_certificate

3. We would like to know if this is a design limit or can we add this verified parameter to the  AzureRM : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub_dps_certificate

### New or Affected Resource(s)/Data Source(s)

azurerm_iothub_dps_certificate

### Potential Terraform Configuration

```hcl
The azurerm_iothub_dps_certificate should be like follows:
resource "azurerm_iothub_dps_certificate" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  iot_dps_name        = azurerm_iothub_dps.example.name

  certificate_content = filebase64("example.cer")
  verified = False/True
}
```

**Comment by xuwenjian1995** [comment]
Hello, 

May I know if there is any update?

**Comment by myc2h6o** [comment]
Hi @xuwenjian1995 I've checked the issue and the doc, it seems to be duplicate with #12963 which was blocked due to API not available. I've checked the API spec again and the `isVerified` property is available in the latest API. I'll check if this can be supported.

**Comment by xuwenjian1995** [comment]
Hi @myc2h6o,

Thank you for your prompt response and I look forward to your update.
