### ISSUE TITLE
Support for mysql_flexible_server.backup_retention_days < 7

### ISSUE THREAD

**Issue by kratkyzobak** [hashicorp/terraform-provider-azurerm#16311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

 

### Description

In https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#backup_retention_days, there is 7 as minimum. According to Azure documentation (and according to setting enabled through portal), minimum is one day.

I hope, 7 were used as resource were copied from PosgtreSQL version of Flexible server, where 7 days is minimum.

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Potential Terraform Configuration

```hcl
azurerm_mysql_flexible_server {
  ...
  backup_retention_days = 1
  ...
}
```

### References

- https://docs.microsoft.com/en-us/azure/mysql/flexible-server/concepts-backup-restore#backup-retention
- https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-backup-restore#backup-retention

**Comment by mbfrahry** [comment]
Hey @kratkyzobak, it looks like this doc change went in a couple weeks ago. I'm going to close this issue down but feel free to reopen it if you're still seeing issues
