### ISSUE TITLE
Support for User Assigned Managed Identity in SQL Managed Instance

### ISSUE THREAD

**Issue by bulentozkir** [hashicorp/terraform-provider-azurerm#16320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_instance#type the identity must support User Assigned Maged Identity. Provider does not have this option.

### New or Affected Resource(s)/Data Source(s)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_instance

**Comment by mybayern1974** [comment]
@bulentozkir , thank you for filing this issue. With assuming this issue could be duplicate with #15277 , would you mind if I close this issue and instead you could subscribe to #15277? Or please correct me if I were wrong. As for your follow up feature request on maintenance window, if it's not related with user assigned identity we suggest to open an independent issue for that. Thanks.
