### ISSUE TITLE
Unable to provision custom domain for Standard Verizon CDN endpoint

### ISSUE THREAD

**Issue by larry-lau** [hashicorp/terraform-provider-azurerm#16332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.9

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_endpoint_custom_domain

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_endpoint_custom_domain" "cdn" {
  name            = "sdc"
  cdn_endpoint_id = azurerm_cdn_endpoint.sdc.id
  host_name       = "cdn.mycustomdomain.com"
  user_managed_https {
    key_vault_certificate_id = data.azurerm_key_vault_certificate.cdn_certificate.id
    tls_version = "TLS12"
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_cdn_endpoint_custom_domain.cdn_sdc: Creating...
azurerm_cdn_endpoint_custom_domain.cdn_sdc: Still creating... [10s elapsed]
╷
│ Error: sending enable request: cdn.CustomDomainsClient#EnableCustomHTTPS: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Cannot override minimum TLS version for Verizon using this parameter. Please contact snal Error: Code="BadRequest" Message="Cannot overridupport for help."
│
│   with azurerm_cdn_endpoint_custom_domain.cdn_sdc,
│   on cdn-domain.tf line 1, in resource "azurerm_cdn_endpoint_custom_domain" "cdn_sdc":
│    1: resource "azurerm_cdn_endpoint_custom_domain" "cdn_sdc" {
```

### Expected Behaviour

I expect the custom domain is updated in my azurerm_cdn_endpoint

### Actual Behaviour

terraform apply return the above error.

Note: I can configure the custom domain without error using the Azure Portal UI.  

### Steps to Reproduce

1. Provision Standard Verizon endpoint
2. Add CNAME pointing to the endpoint
3. Uploaded SSL certificate to KeyVault
4. Run terraform apply to create the azurerm_cdn_endpoint_custom_domain

**Comment by magodo** [comment]
@larry-lau Thank you for submitting this!

This bug is being tracked in #15705 which I'm going to close this in favour of - would you mind subscribing to that issue for updates?

**Comment by benjamin-crew** [comment]
Hi, just wondering if you managed to find a way around this problem? I'm having the same issue. The thread that @magodo referenced has a fix for cdn_managed_https, but not user_managed_https.

**Comment by magodo** [comment]
@benjamin-crew #15756 is fixing for both cases.
