### ISSUE TITLE
For expression "Invalid index" on azurerm_app_service_plan after upgrade to Azurerm 3.0.2

### ISSUE THREAD

**Issue by Nyxbiker** [hashicorp/terraform-provider-azurerm#16340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_app_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "CORE" {
  for_each                    = var.ase_plans
  name                        = "${var.ase_plan_prefix}-${each.key}"
  location                    = azurerm_resource_group.CORE.location
  resource_group_name         = azurerm_resource_group.CORE.name
  kind                        = "app"
  app_service_environment_id  = azurerm_app_service_environment.CORE.id
  per_site_scaling            = each.value.per_site_scaling   
  sku {
    tier = "Isolated"
    size = each.value.sku
    capacity = each.value.capacity
  }
  tags = var.tags
}

var.ase_plans:

ase_plans = {
  "API" = {
    "sku"               = "I2"
    "capacity"          = "5"
    "per_site_scaling"  = true
  },
  "FUNCTIONS" = {
    "sku"               = "I2"
    "capacity"          = "1"
    "per_site_scaling"  = true
  }
}

output (which is causing the error): 

output "host_plan_ids" {
  value = { for k in keys(var.ase_plans) : k => azurerm_app_service_plan.CORE[k].id }
}
```

### Debug Output/Panic Output

```shell
│ Error: Invalid index
│
│   on modules\CORE\outputs.tf line 10, in output "host_plan_ids":
│   10:   value = { for k in keys(var.ase_plans) : k => azurerm_app_service_plan.CORE[k].id }
│     ├────────────────
│     │ azurerm_app_service_plan.CORE is object with 2 attributes
│
│ The given key does not identify an element in this collection value.


In the output the "k" in CORE[k].id is underlined so it's referring to that.
```

### Expected Behaviour

The key "k" should be interpreted with the key in that var-file (which is the app service plan name)

### Actual Behaviour

It looks like the key "k" is not being interpreted and this causes the error

### Steps to Reproduce

1. code
2. terraform plan

**Comment by tombuildsstuff** [comment]
hi @Nyxbiker 

Thanks for opening this issue.

Taking a look through this appears to be a configuration issue rather than something specific to the Azure Provider, as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
