### ISSUE TITLE
Port allocation does not set to use the default number of outbound ports

### ISSUE THREAD

**Issue by tanvp112** [hashicorp/terraform-provider-azurerm#16343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_lb_outbound_rule

### Terraform Configuration Files

```hcl
// https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_outbound_rule#example-usage

resource "azurerm_lb_outbound_rule" "example" {
  loadbalancer_id         = azurerm_lb.example.id
  name                    = "OutboundRule"
  protocol                = "Tcp"
  backend_address_pool_id = azurerm_lb_backend_address_pool.example.id

  frontend_ip_configuration {
    name = "PublicIPAddress"
  }

  allocated_outbound_ports = 0
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

An outbound rules of port allocation set to zero with Port allocation set to "Use the default number of outbound ports" should be created.

![image](https://user-images.githubusercontent.com/57385114/162935202-79857df8-22ac-4282-ab8e-a70c5a621f76.png)

![image](https://user-images.githubusercontent.com/57385114/162935347-a0ae3830-0f4e-4d94-ad5e-bb3864aa9c2c.png)

### Actual Behaviour

An outbound rule of port allocation is set to 1024 despite `allocated_outbound_ports = 0` was specified in the code, and Port allocation required manual intervention to set it to "Use the default number of outbound ports".

![image](https://user-images.githubusercontent.com/57385114/162936365-000db5ab-1520-46fe-a261-daa817f39dca.png)

![image](https://user-images.githubusercontent.com/57385114/162936198-ab304974-676e-4424-aa8d-ce6bba24f7c3.png)

**Comment by myc2h6o** [comment]
Hi @tanvp112 this seems to be a bug in the provider that `0` is ignored. I've raised a pr #16369 to fix it. And for "Use the default number of outbound ports", unfortunately current Azure API doesn't allow us to do it, but I found an issue already tracking this #11862, would you mind subscribe to it for update

**Comment by tanvp112** [comment]
I look forward to the fix in the provider soon, thanks for the prompt replied.
