### ISSUE TITLE
Support for Advanced filtering azurerm_data_factory_trigger_custom_event

### ISSUE THREAD

**Issue by jmalaverri-kr** [hashicorp/terraform-provider-azurerm#16345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Data Factory allows to create custom event triggers to run a pipeline. This feature supports advanced filtering capabilities according to this document https://docs.microsoft.com/en-us/azure/data-factory/how-to-create-custom-event-trigger#advanced-filtering

Is it possible to have this feature added to azurerm_data_factory_trigger_custom_event?

Thanks

### New or Affected Resource(s)/Data Source(s)

azurerm_data_factory_trigger_custom_event

### Potential Terraform Configuration

```hcl
advanced_filters = [
   {
     key        = "foo"
     operator_type = "StringContains"
     values = ["dumy1", "dummy2"]
  }
]
```

**Comment by ms-henglu** [comment]
Hi @jmalaverri-kr ,

It seems this feature has not been added to data factory's swagger, so we can't support it now.
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/datafactory

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
