### ISSUE TITLE
Use auto-provisioning to deploy Vulnerability Assessment (VA) through the AzureRM provider to Microsoft Defender for Cloud (aka Azure Security Center)

### ISSUE THREAD

**Issue by LianaT** [hashicorp/terraform-provider-azurerm#16357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It’s now possible to use auto-provisioning in MIcrosoft Defender for Cloud (previously called Azure Security Center) to deploy Vulnerability Assessment (VA) solution to servers. Currently in AzureRM, we only see it possible to set up auto-provisioning for the Log Analytics agent, not also for vulnerability assessment.

Can you please make this vulnerability assessment auto-provisioning scenario possible through the AzureRM Terraform provider? 

![image](https://user-images.githubusercontent.com/6423037/163060332-3ce71e2b-203a-4486-8b7d-46fc241d9f12.png)

![image](https://user-images.githubusercontent.com/6423037/163060347-36d2f730-4004-4e3c-9d1e-34c3fd3356ee.png)

### New or Affected Resource(s)/Data Source(s)

azurerm/azurerm_security_center_auto_provisioning

### Potential Terraform Configuration

```hcl
resource "azurerm_security_center_VA_auto_provisioning" "example" {
  VA_auto_provision = "On"
}
```

### References

https://docs.microsoft.com/en-us/azure/defender-for-cloud/auto-deploy-vulnerability-assessment#:~:text=Automatically%20enable%20a%20vulnerability%20assessment%20solution%20From%20Defender,machines%20to%20On%20and%20select%20the%20relevant%20solution.

**Comment by sinbai** [comment]
@LianaT Thank you for opening this issue. Unfortunately, it's not possible to support  vulnerability assessment auto-provisioning  through the AzureRM Terraform provider because the [azure API](https://docs.microsoft.com/en-us/rest/api/securitycenter/auto-provisioning-settings/create) used by terraform provider does not support it. The 'default'(Log Analytics agent for Azure VMs) is the only valid name currently supported by the API. Could you try using [azurerm_security_center_server_vulnerability_assessment_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_server_vulnerability_assessment_virtual_machine) resource instead?

**Comment by helderpinto** [comment]
@sinbai Can you please help identify which REST API is used by the [azurerm_security_center_server_vulnerability_assessment_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_server_vulnerability_assessment_virtual_machine) resource?

**Comment by helderpinto** [comment]
@LianaT auto-provisioning for TVM is Policy-based. We can leverage the `azurerm_subscription_policy_assignment` resource for that. See the following built-in policy:

[[Preview]: Configure machines to receive a vulnerability assessment provider](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2F13ce0167-8ca6-4048-8e6b-f996402e3c1b)

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
