### ISSUE TITLE
key_vault permissions case sensitive

### ISSUE THREAD

**Issue by mrfreester** [hashicorp/terraform-provider-azurerm#16354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13

### AzureRM Provider Version

3.1

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_access_policy" "owner_policy" {
  # not relavent....

  secret_permissions = [
    "backup",  #<--- starting with version 3.0 this complains because it doesn't match case
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set"
  ]
```

### Debug Output/Panic Output

```shell
Error: expected secret_permissions.0 to be one of [Backup Delete Get List Purge Recover Restore Set], got backup

  on azure-keyvault.tf line 25, in resource "azurerm_key_vault_access_policy" "owner_policy":
  25:     "backup",
```

### Expected Behaviour

Values ingore case and are accepted

### Actual Behaviour

When first letter isn't capitalized, expected match fails

### Steps to Reproduce

Using the azurerm_key_vault_access_policy resource, use lowercase values for any of the permissions rather than uppercase. When terraform runs using a provider of 3.0 or higher the bug is reproduced.

### References

Issue also discussed here:
https://discuss.hashicorp.com/t/secret-permissions-of-azurerm-becomes-case-sensitive/37536

**Comment by tombuildsstuff** [comment]
hey @mrfreester 

Thanks for opening this issue.

These changes were made as a part of 3.0 (and are now correctly documented against the fields within [the `azurerm_key_vault`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault#certificate_permissions) and [`azurerm_key_vault_access_policy` resources](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_access_policy#certificate_permissions)) - as such you'd need to update your configuration to use the fixed casing here.

Double-checking the upgrade guide it appears that this is missing from the upgrade guide for the `azurerm_key_vault` resource, as such I'll send a PR for that shortly - but this is included for the `azurerm_key_vault_access_policy` resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#resource-azurerm_key_vault_access_policy.

Thanks!
