### ISSUE TITLE
Values for request parameters are invalid: properties.encryption.identity

### ISSUE THREAD

**Issue by georgeboot** [hashicorp/terraform-provider-azurerm#16374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {}

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.1.0"
    }
  }
}

resource "azurerm_key_vault" "keyvault" {
  name                            = "testkeyvault"
  location                        = "West Europe"
  resource_group_name             = "my-resource-group"
  sku_name                        = "standard"
  tenant_id                       = "uuid-of-my-tennant"
  soft_delete_retention_days      = 90
  purge_protection_enabled        = true
}

resource "azurerm_key_vault_key" "storage_account_key" {
  name         = "testaccount"
  key_vault_id = azurerm_key_vault.keyvault.id
  key_type     = "RSA"
  key_size     = 2048
  key_opts     = ["unwrapKey", "wrapKey"]
}

resource "azurerm_user_assigned_identity" "keyvault_reader" {
  resource_group_name = "my-resource-group"
  location            = "West Europe"
  name                = "testmanagedidentity"
}

resource "azurerm_key_vault_access_policy" "keyvault_reader_can_read_keys" {
  key_vault_id    = azurerm_key_vault.keyvault.id
  tenant_id       = "uuid-of-my-tennant"
  object_id       = azurerm_user_assigned_identity.keyvault_reader.principal_id
  key_permissions = ["Get", "UnwrapKey", "WrapKey"]
}

resource "azurerm_storage_account" "testaccount" {
  name                     = "testaccount"
  resource_group_name      = "my-resource-group"
  location                 = "West Europe"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Cool"
  
  customer_managed_key {
    key_vault_key_id          = azurerm_key_vault_key.storage_account_key.id
    user_assigned_identity_id = azurerm_user_assigned_identity.keyvault_reader.id
  }
}
```

### Debug Output/Panic Output

```shell
Error: updating Storage Account: (Name "testaccount" / Resource Group "my-resource-group") Customer Managed Key: storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: properties.encryption.identity."
```

### Expected Behaviour

The key should be added as the user-managed encryption key for the storage account

### Actual Behaviour

I get an error during the `terraform apply`:

```
Error: updating Storage Account: (Name "testaccount" / Resource Group "my-resource-group") Customer Managed Key: storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: properties.encryption.identity."
```

### Steps to Reproduce

terraform apply

**Comment by georgeboot** [comment]
I tried adding an `identity` block to the `azurerm_storage_account`, but it results in the same error.

```terraform
resource "azurerm_storage_account" "testaccount" {
  name                     = "testaccount"
  resource_group_name      = "my-resource-group"
  location                 = "West Europe"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Cool"

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.keyvault_reader.id]
  }
  
  customer_managed_key {
    key_vault_key_id          = azurerm_key_vault_key.storage_account_key.id
    user_assigned_identity_id = azurerm_user_assigned_identity.keyvault_reader.id
  }
}
```

**Comment by georgeboot** [comment]
I figured out a workaround. First add the `identity` block and apply. Then, add the `customer_managed_key` block and apply that again. Then it works.

Using Azure CLI one can do both at the same time, but it seems Terraform can not. It first tries to apply the customer_managed_key, but that fails because the account doesn't have an identity yet.

**Comment by magodo** [comment]
@georgeboot In this case, you might want to use [`azurerm_storage_account_customer_managed_key`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_customer_managed_key) instead?

**Comment by georgeboot** [comment]
I forgot to mention: I am not creating the storage account, but updating it.

It previously existed without identity and with Microsoft managed key.

I tried to update it to have an identity and to have a vault key, all in one apply.
