### ISSUE TITLE
Support for creating specific Public IP address from a Public IP Prefix

### ISSUE THREAD

**Issue by salindaliyanage** [hashicorp/terraform-provider-azurerm#16382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When requesting a Public IP address from a Public IP Prefix, the allocation is not deterministic or sequential. If a specific Public IP address from a Public IP Prefix is required, currently only the PowerShell or Azure CLI commands allow for this. (https://docs.microsoft.com/en-us/azure/virtual-network/ip-services/manage-public-ip-address-prefix#create-a-static-public-ip-address-from-a-prefix). Terraform azurerm_public_ip resource currently does not have support to do this. With Azure BYOIP is in GA, this is an important feature for customers to onboard the same IP addresses they were using into Azure.

### New or Affected Resource(s)/Data Source(s)

azurerm_public_ip

### Potential Terraform Configuration

Add optional ip_address argument to azurerm_public_ip resource

```hcl
resource "azurerm_public_ip" "example" {
  name                      = "acceptanceTestPublicIp1"
  resource_group_name = azurerm_resource_group.example.name
  location                   = azurerm_resource_group.example.location
  allocation_method  = "Static"
  ip_address              = var.ip_address

  tags = {
    environment = "Production"
  }
}
```

**Comment by mybayern1974** [comment]
@salindaliyanage , thank you for opening this issue. By assuming this might be a duplicate issue with #16310, would you mind to subscribe to #16310 and I close this? Or feel free to suggest reopen this issue if you believe they are two different ones.
