### ISSUE TITLE
Listing callbacks URL for logic app request triggers not working in non-public cloud

### ISSUE THREAD

**Issue by TimS95** [hashicorp/terraform-provider-azurerm#16390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_trigger_http_request

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_workflow" "logic_app" {
  name                = "TestLogicApp"
  location            = "chinaeast"
  resource_group_name = "TestResourceGroup"
}

resource "azurerm_logic_app_trigger_http_request" "logic_app" {
  name         = "HTTP Trigger"
  logic_app_id = azurerm_logic_app_workflow.logic_app.id

  schema = <<SCHEMA
{
    "properties": {
        "test": {
            "type": "string"
        }
    },
    "type": "object"
}
SCHEMA
}

output "logic_app" {
  value = {
    callback_url = azurerm_logic_app_trigger_http_request.logic_app.callback_url
  }
}
```

### Debug Output/Panic Output

```shell
Error getting trigger callback URL (logic.WorkflowTriggersClient#ListCallbackURL: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="SubscriptionNotFound" Message="The subscription '***' could not be found.")
```

### Expected Behaviour

The WorkflowTriggersClient should use the base URL for the specific non-public cloud and return the callback URL of the workflow trigger.

### Actual Behaviour

The WorkflowTriggersClient is using the base URL of the public Azure Cloud instead of the configured non-public environment (Like Azure China). In the public cloud it's failing because the subscription there is not existing.

The WorkflowTriggersClient should be initialized with `NewWorkflowTriggersClientWithBaseURI` instead of  `NewWorkflowTriggersClient` to support it. (https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/logic/client/client.go#L57)

**Comment by tombuildsstuff** [comment]
hey @TimS95 

Thanks for opening this issue - digging into this it appears there's 4 of these misregistered across the provider, as such I'll open a PR to fix this shortly.

Thanks!
