### ISSUE TITLE
`azurerm_linux_function_app` broken if running `terraform apply` a second time

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#16396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "regional" {
  name                        = "${var.prefix}-loadgen-${var.location}-func"
  location                    = var.location
  resource_group_name         = var.resource_group_name
  service_plan_id             = azurerm_service_plan.regional.id
  storage_account_name        = azurerm_storage_account.regional.name
  storage_account_access_key  = azurerm_storage_account.regional.primary_access_key
  functions_extension_version = "~4"
  https_only                  = true

  identity {
    type         = "UserAssigned"
    identity_ids = [var.function_user_managed_identity_resource_id]
  }

  key_vault_reference_identity_id = var.function_user_managed_identity_resource_id

  site_config {
    application_stack {
      node_version = "14"
    }
    application_insights_connection_string = var.application_insights_connection_string
  }

  app_settings = merge(
    var.additional_app_settings,
    {
      "PLAYWRIGHT_BROWSERS_PATH"       = "0"
      "ENABLE_ORYX_BUILD"              = "true"
      "SCM_DO_BUILD_DURING_DEPLOYMENT" = "true"
      "WEBSITE_MOUNT_ENABLED"          = "1"
  })
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Terraform should not break the function

### Actual Behaviour

After the first deployment of the Function app, plus the actual Function code, using the Function core tools are complete, it looks like this and all is good:
![image](https://user-images.githubusercontent.com/11445087/163398324-5663ab81-4ad3-4f06-b487-33b8c9783755.png)

From the ARM template export:
![image](https://user-images.githubusercontent.com/11445087/163398401-cdf50941-63e1-45ec-af34-4e5b8b227223.png)

Next time I run `terraform apply`, the plan wants to (and will) remove the RUN_FROM_PACAKGE app setting.

![image](https://user-images.githubusercontent.com/11445087/163399083-08d689e0-c5b3-4eb0-b295-303839d33bbe.png)

Afterwards, not only is the package setting gone, but also all the app settings regarding the runtime version. Result: Function is not working anymore.
![image](https://user-images.githubusercontent.com/11445087/163398963-228ad7f2-a395-4a82-9eec-159e081ba42b.png)

![image](https://user-images.githubusercontent.com/11445087/163399714-04638cce-8005-46d8-9cfa-449218f98807.png)

Even after running the Function core tools deployment again (which is successful), the Function is still broken beyond repair.

The sample shows a Node Function, but I have the same behavior on a dotnet6 function

### Steps to Reproduce

1) Create a new Function app using Terraform
2) deploy app to it using Function core tools. I'm using `func azure functionapp publish my-func --build local --javascript`
3) Run terraform apply again

**Comment by AaldertVanWijk-TomTom** [comment]
Hi @sebader can you share with us what the input into var.additional_app_settings is?

In general I have the experience with Java that you have to be careful not to set app_settings that conflict with or duplicate the application stack

**Comment by sebader** [comment]
Sure, the entire code is here, but the extra App setting is actually only just one more
Custom setting, nothing conflicting with the publish settings:

https://github.com/Azure/Mission-Critical-Online/blob/fix/load-gen-function-tf3/src/testing/userload-generator/infra/modules/regional_function/functionapp.tf
