### ISSUE TITLE
Unable to create App Service Plans for Logic Apps with azurerm_service_plan

### ISSUE THREAD

**Issue by JameySteinmann** [hashicorp/terraform-provider-azurerm#16401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan, azurerm_app_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name = "${terraform.workspace}-RG"
  location = "East US"
}

#Working via deprecated azurerm_app_service_plan
resource "azurerm_app_service_plan" "plan" {
  name = "ASP-${terraform.workspace}"
  location = "East US"
  resource_group_name = azurerm_resource_group.rg.name
  kind = "elastic"
  sku {
    tier = "WorkflowStandard"
    size = "WS1"
  }
}

#Non-working azurerm_service_plan
resource "azurerm_service_plan" "plan" {
  name = "SP-${terraform.workspace}"
  location = "East US"
  resource_group_name = azurerm_resource_group.rg.name
  sku_name = "WS1"
}
```

### Debug Output/Panic Output

```shell
#This is the data source via azurerm_service_plan for a working App Service Plan that allows logic apps to be attached to it. The data source also seems to be missing some components when compared to the data source of azurerm_app_service_plan of the same resource.

    {
      "mode": "data",
      "type": "azurerm_service_plan",
      "name": "manual",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "app_service_environment_id": "",
            "id": "/subscriptions/ac688153-f123-67b8-a19f-d1cecc0d2599/resourceGroups/la-plan-test-RG/providers/Microsoft.Web/serverfarms/ASP-la-plan-test",
            "kind": "",
            "location": "eastus",
            "maximum_elastic_worker_count": 20,
            "name": "ASP-la-plan-test",
            "os_type": "",
            "per_site_scaling_enabled": false,
            "reserved": false,
            "resource_group_name": "la-plan-test-RG",
            "sku_name": "WS1",
            "tags": {},
            "timeouts": null,
            "worker_count": 1,
            "zone_balancing_enabled": false
          },
          "sensitive_attributes": []
        }
      ]
    }


    {
      "mode": "data",
      "type": "azurerm_app_service_plan",
      "name": "manual",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "app_service_environment_id": null,
            "id": "/subscriptions/ac688153-f123-67b8-a19f-d1cecc0d2599/resourceGroups/la-plan-test-RG/providers/Microsoft.Web/serverfarms/ASP-la-plan-test",
            "is_xenon": false,
            "kind": "elastic",
            "location": "eastus",
            "maximum_elastic_worker_count": 20,
            "maximum_number_of_workers": 20,
            "name": "ASP-la-plan-test",
            "per_site_scaling": false,
            "reserved": false,
            "resource_group_name": "la-plan-test-RG",
            "sku": [
              {
                "capacity": 1,
                "size": "WS1",
                "tier": "WorkflowStandard"
              }
            ],
            "tags": {},
            "timeouts": null,
            "zone_redundant": false
          },
          "sensitive_attributes": []
        }
      ]
    }
```

### Expected Behaviour

When using the WS1, WS2, or WS3 sku name for an azurerm_service_plan it should create an app service plan in Azure that shows as an "Elastic App"

When using the data source the kind should show as elastic

### Actual Behaviour

When using the WS1, WS2, or WS3 sku names for an azurerm_service_plan it results in creating an App Service Plan and Logic Apps are not able to be deployed via azure to them. You can deploy them with Terraform, however they fail to run due to the wrong Service Plan being created in Azure. 

When using the data source the kind shows as ""

### Steps to Reproduce

1. Deploy an azurerm_service_plan using WS1, WS2, or WS3 skus

- Create an azurerm_logic_app_standard resource using this service plan and navigate to workflows in Azure to see a resulting hosting error message
- Manually create a logic app in the Azure Portal and note that you are unable to select the service plan to deploy the logic app

2. Deploy an azurerm_app_service_plan using WS1, WS2, or WS3 skus, set kind to "elastic" and tier to "WorkflowStandard"
- Create an azurerm_logic_app_standard resource using the service plan and see the when navigating to workflows in the Azure Portal that it will allow you to add workflows
- Manually create a logic app in the Azure Portal and note that you are able to use the service plan to deploy to

**Comment by sinbai** [comment]
@JameySteinmann thank you for posting this issue here. Unfortunately, I could not reproduce the above issue. After creating an App Service Plans for Logic Apps with azurerm_service_plan(tf configuration below),  there is no error message in workflows in Azure and the service plan(SP-01) is available when manually deploying the logic app in the Azure Portal. Could you compare the tf config with yours and try to reproduce with it?

```

provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	  version = "3.1.0"
    }
  }
}

resource "azurerm_resource_group" "test" {
  name     = "rg-sample"
  location = "eastus"
}

resource "azurerm_service_plan" "test" {
  name                = "SP-01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku_name            = "WS1"
  os_type             = "Windows"
}

resource "azurerm_storage_account" "test" {
  name                     = "functionapptest0415"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_logic_app_standard" "test" {
  name                       = "logic-sample"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  app_service_plan_id        = azurerm_service_plan.test.id
  storage_account_name       = azurerm_storage_account.test.name
  storage_account_access_key = azurerm_storage_account.test.primary_access_key
}
```

![image](https://user-images.githubusercontent.com/39109137/163546362-0409115a-9cd7-41e9-91b5-8c29e9f42ec5.png)

**Comment by JameySteinmann** [comment]
Thank you @sinbai. It appears that you have to set the os_type = "Windows" for this to work. I tested it in 3.1.0 and 3.2.0 and it works as you showed. This is a departure from how you would do it in azurerm_app_service_plan and isn't documented. Perhaps this request can just serve to update the docs with a note that when using WS1, WS2, and WS3 skus that they're only available in the os_type = "Windows". Is this the right spot for it, or should I close this and open a new report for just the documentation update?

**Comment by sinbai** [comment]
@JameySteinmann  thanks for your feedback. In fact, when using WS1, WS2, and WS3 skus, they're available both "Windows" and "Linux". In my sample, os_type is set to "Windows" simply because  `"is_xenon": false and  "reserved": false` in the information provided below. This means the os_type neither WindowsContainer nor Linux.
```
 {
      "mode": "data",
      "type": "azurerm_app_service_plan",
      "name": "manual",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "app_service_environment_id": null,
            "id": "/subscriptions/ac688153-f123-67b8-a19f-d1cecc0d2599/resourceGroups/la-plan-test-RG/providers/Microsoft.Web/serverfarms/ASP-la-plan-test",
            "is_xenon": false,
            "kind": "elastic",
            "location": "eastus",
            "maximum_elastic_worker_count": 20,
            "maximum_number_of_workers": 20,
            "name": "ASP-la-plan-test",
            "per_site_scaling": false,
            "reserved": false,
            "resource_group_name": "la-plan-test-RG",
            "sku": [
              {
                "capacity": 1,
                "size": "WS1",
                "tier": "WorkflowStandard"
              }
            ],
            "tags": {},
            "timeouts": null,
            "zone_redundant": false
          },
          "sensitive_attributes": []
        }
      ]
    }
```

For the data source issue, I have submitted a PR to fix it. Thanks again for posting this here.

**Comment by JameySteinmann** [comment]
You're welcome @sinbai. I have another bug as they relate to creating the logic apps do not work, but I'll file another bug for this.
