### ISSUE TITLE
azurerm_windows_function_app not working

### ISSUE THREAD

**Issue by taipignas** [hashicorp/terraform-provider-azurerm#16412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.5

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
azure cli version 2.33.1
I'm using az login with client secret
Default configuration in the documentation. I tried variations with or without: storage_account_name, storage_uses_managed_identity, identity. First 3 resources are created without issues, 4th resource - function app - fails.
Is the documentation wrong? Are those properties optional or required?
Because I either get error: Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.
Or error: The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value
```

### Debug Output/Panic Output

```shell
Error: creating Windows Function App: (Site Name "app-name" / Resource Group "group-name"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible." Details=[{"Message":"Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"99022","Message":"Creation of storage file share failed with: 'The remote server returned an error: (403) Forbidden.'. Please check if the storage account is accessible.","MessageTemplate":"Creation of storage file share failed with: '{0}'. Please check if the storage account is accessible.","Parameters":["The remote server returned an error: (403) Forbidden."]}}]
│ 
│   with azurerm_windows_function_app.function_app,
│   on terraform.tf line 46, in resource "azurerm_windows_function_app" "function_app":
│   46: resource "azurerm_windows_function_app" "function_app" {
```

**Comment by taipignas** [comment]
solution: add this property to function app section - storage_account_access_key = azurerm_storage_account.example.primary_access_key

i think the documentation is not 100% complete. this can be really frustrating for newcomers.

**Comment by remiX-** [comment]
Ah thanks!

Looking at the docs it does state this, but I glossed over and just saw they were `optional` :D 

![image](https://user-images.githubusercontent.com/2831747/165041637-b5beef6b-eff4-4181-9b37-b3a339ef4c82.png)

**Comment by scarter-brighthealth** [comment]
storage_account_name is also listed as optional and this needs to be updated to required as well. 

![image](https://user-images.githubusercontent.com/89096674/165186002-accebc70-95e1-41f8-9647-1ffd9fb1667b.png)

![image](https://user-images.githubusercontent.com/89096674/165186368-a3b2a070-7ecc-4f25-8520-20217b592bec.png)
