### ISSUE TITLE
Support for Databricks IP access lists

### ISSUE THREAD

**Issue by atombravo** [hashicorp/terraform-provider-azurerm#16435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for Azure Databricks IP Access lists would be very useful, since currently it can only be enabled and managed by directly accessing the Azure API (i.e., not from the portal).

https://docs.microsoft.com/en-us/azure/databricks/security/network/ip-access-list has the details of the feature, which is now in general release and available on premium subscriptions.  Given the complexity of locking down databricks from a network level, this is a really useful feature.

### New or Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace_ip_access_list

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

# Separate resource for each IP list
resource "azurerm_databricks_workspace" "example_1" {
  name                = "databricks-separate-list"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "premium"

  enableIpAccessLists = true  # New atribute to enable feature on workspace, only allowed on sku = "premium"
}

resource "azurerm_databricks_workspace_ip_access_list" "example_1_list" {  # New resource type
  workspace_url = azurerm_databricks_workspace.example.workspace_url
  label = "example_1"  # exports a calculated attribute, list_id which is different than the label
  list_type = "ALLOW"   # "ALLOW" or "BLOCK"
  ip_addresses =  [
        "1.1.1.1",
        "2.2.2.2/21",
      ]
   enabled = true
}

# Inline definition of ipaccess list
resource "azurerm_databricks_workspace" "example_2" {
  name                = "databricks-inline-list"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "premium"

  enableIpAccessLists = true  # New atribute to enable feature on workspace, only allowed on sku = "premium"

  ip_access_list  {     # Allow multiple
        label = "example_2"  # exports a calculated attribute, list_id which is different than the label
        list_type = "ALLOW"   # "ALLOW" or "BLOCK"
        ip_addresses =  [
            "1.2.3.5",
            "3.3.3.3/21",
        ]
        enabled = true
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/databricks/security/network/ip-access-list

**Comment by mlcooper** [comment]
Check out this resource in the Databricks Terraform https://undefined/providers/databrickslabs/databricks/latest/docs/resources/ip_access_list

**Comment by atombravo** [comment]
[mlcooper] thank you! I'm not sure how I missed that since I've spent the last several days on that same section of documentation working on user permissioning via TF.  That exactly is what I was looking for--except in the wrong provider.  Much appreciated, thank you!
