### ISSUE TITLE
azurerm_kubernetes_cluster_node_pool kubelet config no longer preview feature

### ISSUE THREAD

**Issue by NissesSenap** [hashicorp/terraform-provider-azurerm#16433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.1.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1

  kubelet_config {
    pod_max_pid = 5000
  }

  tags = {
    Environment = "Production"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Node Pool: (Agent Pool Name "example" / Managed Cluster Name "example" / Resource Group "example): containerservice.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PreviewFeatureNotRegistered" Message="Preview feature Microsoft.ContainerService/CustomNodeConfigPreview not registered."
│
```

### Expected Behaviour

Kubelet config has stopped being a preview feature and is now GA.

https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration
https://github.com/Azure/AKS/releases/tag/2022-04-03

Thus we should no longer need to register for a preview feature to use this config.

### Actual Behaviour

Azurerm complains about PreviewFeatureNotRegistered.

### Steps to Reproduce

Use provided config where `kubelet_config` is defined and run terraform apply.
You should see a similar error as shown in the debug output.

### References

https://docs.microsoft.com/en-us/azure/aks/custom-node-configuration
https://github.com/Azure/AKS/releases/tag/2022-04-03

**Comment by stephybun** [comment]
Hi @NissesSenap,

Thanks for raising this issue and apologies for not getting to this sooner. 

The provider itself doesn't check whether the relevant preview features are enabled or not on the subscription so it looks like this error comes from the AKS service itself. Seeing as this is from quite a while ago I imagine this might already be resolved though.

Could you confirm whether you still have this problem?

**Comment by NissesSenap** [comment]
Hey okay, i currently don't have time for a deeper look but if you say that this is only a API thing in Azure then i assume it should be okay. 

I will close the issue in the mean time and if it doesn't work when i get time to verify i guess i will reopen it then. 

Thanks for your explanation
