### ISSUE TITLE
404 error creating policy assignments at resource group level across subscriptions; can't use variable to reference provider alias

### ISSUE THREAD

**Issue by TeamDman** [hashicorp/terraform-provider-azurerm#16449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_policy_assignment

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}


variable "scopes" {
  type = list(object({
    subscriptionId    = optional(string),
    managementGroupId = optional(string),
    exemptions = optional(set(object({
      resourceGroupId  = string,
      allowedLocations = optional(set(string)),
      allowedVMSKUs    = optional(set(string)),
      allowedSASKUs    = optional(set(string)),
    }))),
  }))
  description = "Subscription ids to apply the policy to"
}

resource "azurerm_resource_group_policy_exemption" "main" {
  for_each = { for ex in local.exemptions: ex.id => ex }
  name = each.key
  resource_group_id = each.value.exemption.resourceGroupId # some RGs are outside of default provider's subscription, this works
  policy_assignment_id = each.value.assignment.id
  exemption_category = "Mitigated"
}


resource "azurerm_resource_group_policy_assignment" "ex" {
  for_each = {
    for ex in flatten([for scope in var.scopes : coalesce(scope.exemptions, [])]) :
    ex.resourceGroupId => ex
  }
  resource_group_id    = each.value.resourceGroupId # some RGs are outside of default provider's subscription, this is failing with a 404
  policy_definition_id = azurerm_policy_set_definition.initiative.id
  enforce              = true
  display_name         = each.value.resourceGroupId
  name                 = each.value.resourceGroupId
  parameters = jsonencode({
    allowedLocations = {
      value = setunion(var.allowedLocations, coalesce(each.value.allowedLocations, []))
    }
    allowedVMSKUs = {
      value = setunion(var.allowedVMSKUs, coalesce(each.value.allowedVMSKUs, []))
    }
    allowedSASKUs = {
      value = setunion(var.allowedSASKUs, coalesce(each.value.allowedSASKUs, []))
    }
  })
  identity {
    type = "SystemAssigned"
  }
  location = "canadacentral"
}
```

### Debug Output/Panic Output

```shell
azurerm_resource_group_policy_assignment.ex["/subscriptions/mySubscription/resourceGroups/myRG"]: Creating...
╷
│ Error: creating Policy Assignment ID: (Assignment Name "/subscriptions/mySubscription/resourceGroups/myRG" / Scope "/subscriptions/mySubscription/resourceGroups/myRG"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="InvalidRequestUri" Message="The request uri is invalid. The requested resource is not found."
│
│   with azurerm_resource_group_policy_assignment.ex["/subscriptions/mySubscription/resourceGroups/myRG"],
│   on policyExemption.tf line 24, in resource "azurerm_resource_group_policy_assignment" "ex":
│   24: resource "azurerm_resource_group_policy_assignment" "ex" {
│
│ creating Policy Assignment ID: (Assignment Name "/subscriptions/mySubscription/resourceGroups/myRG" / Scope
│ "/subscriptions/mySubscription/resourceGroups/myRG"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=404 --      
│ Original Error: autorest/azure: Service returned an error. Status=404 Code="InvalidRequestUri" Message="The request uri is invalid. The requested resource is not found."
╵
```

### Expected Behaviour

My goals:
- [x] Create policy definition
- [x] Create policy assignments to subscriptions and management groups
- [x] Create policy exemptions for some resource groups with known IDs
- [ ] _Create additional policy assignments to the resource groups that have exemptions (additional SKUs in the whitelist, etc)_

### Actual Behaviour

This last step, creation of policy assignments at the resource group level, is failing presumably because the resource groups are not within the subscription associated with the default provider being used. The resource group with the given ID definitely exists.

I tried looking into creating a provider for each subscription in the tenant, but [there's no way to reference provider aliases using variables](https://discuss.hashicorp.com/t/defining-provider-aliases-with-string-interpolation-not-working-in-terraform-0-12/1569/2) to reference them, so I'm not sure how to continue.

### Important Factoids

Tenant with multiple subscriptions

**Comment by magodo** [comment]
@TeamDman I've locally tested assigning policy to resource group within another subscription than the provider is using. As long as the service principal has appropriate permission, the assignment can be created successfully. Also, I've tested that in case the resource group doesn't exist, the error message is as below (which is different than what you have got):

```
Status=404 Code="ResourceGroupNotFound" Message="Resource group 'acctest7755' could not be found.
```

So, would you please check whether there is any other special in your setup so that I can further investigate the issue? Meanwhile, I'll reach out to the Azure team to see when will the API return `InvalidRequestUri` code.

**Comment by magodo** [comment]
@TeamDman The reason is that you are using `/subscriptions/mySubscription/resourceGroups/myRG` as the policy assignment name, which will then be interpolated into the API path, which ends up into a invalid url.

**Comment by TeamDman** [comment]
That makes sense, thanks for the info!
Will mark as resolved for now; if I still have issues with it when I get back then I will follow up here

**Comment by TeamDman** [comment]
Confirmed working <3
