### ISSUE TITLE
Support for azurerm_api_management_api websocket protocols "ws" and "wss"

### ISSUE THREAD

**Issue by kensykora** [hashicorp/terraform-provider-azurerm#16452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With API Management now supporting websockets, getting the APIs manageable in terraform is the next logical step! Currently the `azurerm_api_management_api` only supports protocols `http` or `https` and now `wss` is available.

Use case: routing requests through APIM to Azure SignalR Service

![ws-example](https://user-images.githubusercontent.com/64756/164079454-4e52c953-24d6-4515-a467-73e6d9e4c064.png)
![image](https://user-images.githubusercontent.com/64756/164079684-b102942e-73f8-43fe-98c6-39f1d126df21.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management_api" "ws" {
  name                  = "ws"
  description           = "Websocket"
  api_management_name   = data.azurerm_api_management.default.name
  resource_group_name   = data.azurerm_api_management.default.resource_group_name
  revision              = "v1"
  display_name          = "WS"
  path                  = "customer/v1/ws"
  protocols             = ["wss"]
  subscription_required = false
  service_url           = "wss://${azurerm_signalr_service.main.hostname}"
}
```

### References

 - https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2021-04-01-preview/service/apis?tabs=bicep

**Comment by tombuildsstuff** [comment]
Looks like there's 4 to expose here total:

```go
// Protocol enumerates the values for protocol.
type Protocol string

const (
	// ProtocolHTTP ...
	ProtocolHTTP Protocol = "http"
	// ProtocolHTTPS ...
	ProtocolHTTPS Protocol = "https"
	// ProtocolWs ...
	ProtocolWs Protocol = "ws"
	// ProtocolWss ...
	ProtocolWss Protocol = "wss"
)
```

**Comment by kensykora** [comment]
Another thing I noticed is that it also required me to set the property `serviceUrl` so that might be new as well. 

```
# Ref: https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/apis/create-or-update
resource "azapi_resource" "azurerm_api_management_api_websocket" {
  type      = "Microsoft.ApiManagement/service/apis@2021-04-01-preview"
  name      = "websocket"
  parent_id = data.azurerm_api_management.default.id

  body = jsonencode({
    properties = {
      description          = "Websocket"
      displayName          = "Websocket"
      path                 = "customer/v1/ws"
      protocols            = ["wss"]
      apiRevision          = "1"
      type                 = "websocket"
      serviceUrl           = "wss://${azurerm_signalr_service.main.hostname}"
      subscriptionRequired = false
    }
  })
}
```

**Comment by mityankin** [comment]
> Another thing I noticed is that it also required me to set the property `serviceUrl` so that might be new as well.
> 
> ```
> # Ref: https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/apis/create-or-update
> resource "azapi_resource" "azurerm_api_management_api_websocket" {
>   type      = "Microsoft.ApiManagement/service/apis@2021-04-01-preview"
>   name      = "websocket"
>   parent_id = data.azurerm_api_management.default.id
> 
>   body = jsonencode({
>     properties = {
>       description          = "Websocket"
>       displayName          = "Websocket"
>       path                 = "customer/v1/ws"
>       protocols            = ["wss"]
>       apiRevision          = "1"
>       type                 = "websocket"
>       serviceUrl           = "wss://${azurerm_signalr_service.main.hostname}"
>       subscriptionRequired = false
>     }
>   })
> }
> ```

Hi. 
Thanks for the example.

Also, can you write an example how you describe APIM endpoints (with Websocket)? 
Like in usual HTTP API azurerm_api_management_api_operation and azurerm_api_management_api_operation_policy

**Comment by kensykora** [comment]
> Also, can you write an example how you describe APIM endpoints (with Websocket)?

I haven't gotten that far yet, just experimenting with it right now. I believe it only creates a single endpoint for you and you can't create any others. The idea is that you'd use this with other REST APIs at different routes

**Comment by mityankin** [comment]
As I understand azapi and azurerm it is a different providers. 
And you try to mix it. It can be not a good idea. 
What do you think about it?

**Comment by kensykora** [comment]
Why not? That's one of the many beauties of terraform, you can mix providers to achieve multi provider configuration. Under the hood, it's using the same credential set and same APIs that the terraform provider uses, and the azapi provider is designed explicitly for this scenario (where there's a gap in terraform azurerm coverage)

Check out this blog post by the MS product team: https://techcommunity.microsoft.com/t5/azure-tools-blog/announcing-azure-terrafy-and-azapi-terraform-provider-previews/ba-p/3270937

**Comment by owenfarrell** [comment]
@kensykora - When I was digging in to #14634, this issue _**seemed**_ related. I think my approach to the linked PR solves both problems at once. And my acceptance test configuration (see [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/17812/files#diff-9e99153fb17f3a4e77378ef4277a0519e8f1d6ac0806272e2eef9323500e8e2aR173-R187)) seems to align with your expected configuration.

Any feedback you have would be appreciated.
