### ISSUE TITLE
azurerm_storage_account allow_nested_items_to_be_public doesn't set allowBlobPublicAccess to false

### ISSUE THREAD

**Issue by Dan-Bai** [hashicorp/terraform-provider-azurerm#16451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.11

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "rg-example"
  location = "centralus"

}

resource "azurerm_storage_account" "storage_account" {
  name                            = "stexample"
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = "centralus"
  account_kind                    = "StorageV2"
  account_tier                    = "Standard"
  account_replication_type        = "RAGRS"
  enable_https_traffic_only       = true
  allow_nested_items_to_be_public = false
}
```

### Debug Output/Panic Output

```shell
No output. JSON view of the storage account in Azure portal shows allowBlobPublicAccess as true.
```

### Expected Behaviour

allowBlobPublicAccess should be set as false

### Actual Behaviour

allowBlobPublicAccess is set as true

### Steps to Reproduce

View on Azure portal after apply

**Comment by LeighdePaor** [comment]
This happened previously and broke Gov Cloud - https://github.com/hashicorp/terraform-provider-azurerm/issues/7781
Public access to cloud resources should always default to false as a basic security principle, it should have to be explicitly overridden to enable public access.

**Comment by tombuildsstuff** [comment]
@LeighdePaor that's not what this field does - and is why this field has been renamed in 3.0 to avoid confusion - this field controls whether resources within this storage account _can opt-in_ to being public - it doesn't make items within it public. As such this Terraform default matches the Azure default here.

**Comment by tombuildsstuff** [comment]
@Dan-Bai which Azure Environment is this running in? Can you provide the debug logs here so that we can take a look into this?

**Comment by LeighdePaor** [comment]
> @LeighdePaor that's not what this field does - and is why this field has been renamed in 3.0 to avoid confusion - this field controls whether resources within this storage account _can opt-in_ to being public - it doesn't make items within it public. As such this Terraform default matches the Azure default here.

Thanks @tombuildsstuff 
It may indeed match the Azure default, but I have big problems with MS having public access enabled as being the default it's almost like a recipe for failure.
Anyway all storage accounts being created by TF which did not specify the "allow_blob_public_access = false" are now being created with public access enabled - I know this does not necessarily translate to the azurerm_storage_container being public but the danger of containers being created as public is much higher if the storage account has public enabled by default.

**Comment by Dan-Bai** [comment]
> @Dan-Bai which Azure Environment is this running in? Can you provide the debug logs here so that we can take a look into this?
This is running in Azure Public Cloud.
Currently trying to generate the logs. Is there a specific piece you are looking for? This is a small part of a larger terraform project so the logs is looking to be 50MB+.

**Comment by tombuildsstuff** [comment]
@LeighdePaor unfortunately that's Microsoft's recommendation for this setting - you can use Azure Policy to enforce it one way or another within your Azure Subscription(s), but as this is the recommended setting from MSFT unfortunately this isn't something we have plans to change at this time.

**Comment by tombuildsstuff** [comment]
@Dan-Bai you can scope a plan/apply using `-target=azurerm_storage_account.{name}`, which should output only the logs for that resource (e.g. `TF_LOG=1 terraform apply -target=azurerm_storage_account.XXX`)

**Comment by Dan-Bai** [comment]
> @Dan-Bai you can scope a plan/apply using `-target=azurerm_storage_account.{name}`, which should output only the logs for that resource (e.g. `TF_LOG=1 terraform apply -target=azurerm_storage_account.XXX`)

@tombuildsstuff 
I was able to do this. It's still a long output, is there a specific section?

**Comment by Dan-Bai** [comment]
I am no longer seeing the issue. Could have been transient and could have been user error.
Will close the issue .
