### ISSUE TITLE
Terraform azurerm_resource_group_policy_remediation not working as expected

### ISSUE THREAD

**Issue by rks040888** [hashicorp/terraform-provider-azurerm#16454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.1.7

### AzureRM Provider Version

v3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_policy_remediation and remediation tasks

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "rg_name" {
  name = var.rg_name
}

data "azurerm_subscription" "primary" {
}

resource "azurerm_resource_group_policy_assignment" "policy_assign" {
  name                 = join("_", ["policy_assignment_for", "${var.rg_name}"])
  resource_group_id    = data.azurerm_resource_group.rg_name.id
  policy_definition_id = azurerm_policy_set_definition.inherit_rg_tags.id
  enforce              = true
  identity {
    type = "SystemAssigned"
  }
  location = var.location_for_identity
}

resource "azurerm_role_assignment" "assignment" {
  scope                = join("/", [data.azurerm_subscription.primary.id, "resourceGroups", "${var.rg_name}"])
  #scope                = data.azurerm_subscription.primary.id
  role_definition_name = "Contributor"
  principal_id         = azurerm_resource_group_policy_assignment.policy_assign.identity[0].principal_id
}

output "policy_definition_id_forsnowgrp" {
  value = azurerm_policy_definition.policy["foo_tag"].id
}

resource "azurerm_resource_group_policy_remediation" "example" {
  name                 = "policy_remediation_for_tag_foo_tag_email"
  resource_group_id    = data.azurerm_resource_group.rg_name.id
  policy_assignment_id = azurerm_resource_group_policy_assignment.policy_assign.id
  policy_definition_id = azurerm_policy_definition.policy["foo_tag"].id
}
```

### Debug Output/Panic Output

```shell
Terraform is deeming that it has created the remediation task for "policy_remediation_for_tag_foo_tag_email" But I don't see it in Azure portal. Seems like the terraform module has a bug in remediation task creations.
```

### Expected Behaviour

Terraform should have created the policy_remediation_task for the existing resources of the group.

### Actual Behaviour

The remediation task not gets created in Azure portal

### Steps to Reproduce

Use above provided terraform code snippet and use appropriate variables and run "terraform apply"

**Comment by tombuildsstuff** [comment]
hi @rks040888

Thanks for opening this issue.

When creating the Policy Remediation Terraform's relying on the Azure API to tell us that it's completed, and since this is coming back as `Succeeded` it should be done - as such I have a feeling this is likely (another) caching issue in the Azure Portal. Would it be possible to confirm if the Policy Remediation is returned from the Azure API?

Thanks!

**Comment by rks040888** [comment]
Looks like Terraform is using "policy_definition_id" while remediating policies from a policy set. Where as Azure CLI is using "definition-reference-id" while remediating a policy from policy set.

If we directly call Azure CLI with the "definition-reference-id", The remediation task is getting created correctly in the portal. So to me it looks like an issue/bug in the terraform module. Below is the Azure CLI command I have used to create the remediation task by calling Azure API directly,

az policy remediation create -n myRemediation --policy-assignment eeb18edc813c42d0ad5a9eab --definition-reference-id auditVMPolicyReference

**Comment by gettek** [comment]
Related to #17096

**Comment by RackPhilO** [comment]
The same id mix up seems to be true for "azurerm_resource_policy_remediation" and "azurerm_subscription_policy_remediation" 

The tasks creates successfully via TF , but there are no remediation tasks viewable in the portal .

You can see the created TF task using cli or PowerShell but the field PolicyDefinitionReferenceId  is then populated with the DEFINITION ID not the REFERENCE ID . 

PolicyDefinitionReferenceId : /subscriptions/{subname}/providers/microsoft.authorization/policydefinitions/polname-001

vs the cli \ PowerShell

PolicyDefinitionReferenceId : polreference001
