### ISSUE TITLE
azurerm_private_endpoint creation

### ISSUE THREAD

**Issue by kantkrish** [hashicorp/terraform-provider-azurerm#16475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

.13.7

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoin

### Terraform Configuration Files

```hcl
My configs are applied based on the example/documentation from this link:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint
```

### Debug Output/Panic Output

```shell
None
```

### Expected Behaviour

Private endpoint should ask for Target resource and Sub-resource for attaching to a PaaS service:

        "privateEndpointName": {
            "value": "Portal-Private-Endpoint"
        },
        "privateLinkResource": {
            "value": "/subscriptions/<<subscription>>/resourceGroups/<<RSG>>/providers/Microsoft.Storage/storageAccounts/<<storage>>"
        },
        "targetSubResource": {
            "value": [
                "blob"
            ]
        }

Attaching ARM template for a Private endpoint deployment.
[template.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/8523274/template.zip)

### Actual Behaviour

Current azurerm_private_endpoint creates bindings only for Private Link service

### Steps to Reproduce

It deploys a private endpoint for a private link service along with ILB, NAT, which is not relevant for private endpoint attached to a PaaS service in this scenario.

### References

I am trying to create a private endpoint for Storage(to start with) and while following the example in the Azurerm Provider, it deploys PE in reference to a Private link, but it doesn't work for a scenario where a private link is not needed but just a private endpoint attached to a PaaS service. 
For a Private Endpoint for a PaaS it option should be to provide Target resource and sub-resource this private endpoint should be attached to. 

After looking at the ARM template for Private endpoint it has no references to ILB/NAT which is irrelevant in case of Private endpoint.

**Comment by tombuildsstuff** [comment]
hi @kantkrish 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider - as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
