### ISSUE TITLE
azurerm_database_migration_project : error in syntax

### ISSUE THREAD

**Issue by Ogbugoana** [hashicorp/terraform-provider-azurerm#16479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_database_migration_project

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_database_migration_service" "example" {
  name                = "example-dbms"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  virtual_subnet_id   = azurerm_subnet.example.id
  sku_name            = "Standard_1vCores"
}

resource "azurerm_database_migration_project" "example" {
  name                = "example-dbms-project"
  service_name        = azurerm_database_migration_service.example.name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  source_platform     = "SQL"
  target_platform     = "SQLDB"
}
```

### Debug Output/Panic Output

```shell
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_database_migration_service" "example" {
  name                = "example-dbms"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  subnet_id           = azurerm_subnet.example.id
  sku_name            = "Standard_1vCores"
}

resource "azurerm_database_migration_project" "example" {
  name                = "example-dbms-project"
  service_name        = azurerm_database_migration_service.example.name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  source_platform     = "SQL"
  target_platform     = "SQLDB"
}
```

### Expected Behaviour

database migration service connects to subnet id

### Actual Behaviour

database migration service cannot connect to subnet id due to error in syntax

**Comment by tombuildsstuff** [comment]
hi @Ogbugoana 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider - as this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
