### ISSUE TITLE
Keyvault errors after updating to azurerm_provider 3.2.0

### ISSUE THREAD

**Issue by michelefa1988** [hashicorp/terraform-provider-azurerm#16493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_keyvault

### Terraform Configuration Files

```hcl
keyvault.tf

#################################
### Variables
#################################

variable "name" {}
variable "location" {}

variable "resource_group" {}
variable "default_tags" {}
variable "purge_protection_enabled" {
    default= false
}
variable "enable_rbac_authorization" {
  default = "true"
}
variable "keyvault_name_char_limit" {
  default = 22
}


#################################
### Modules
#################################
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "key_vault" {
  name                        = substr(var.name, 0, var.keyvault_name_char_limit)
  location                    = var.location
  resource_group_name         = var.resource_group
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = var.purge_protection_enabled

  enable_rbac_authorization = var.enable_rbac_authorization

  sku_name = "standard"

  tags = merge(
    var.default_tags
  )
}

azurerm_key_vault_secret.tf

#################################
### Variables
#################################

variable "name" {}
variable "secret" {}
variable "key_vault_id" {}
variable "expiration_date" {
  default = null
}

#################################
### Modules
#################################
resource "azurerm_key_vault_secret" "secret" {
  name         = var.name
  value        = var.secret
  key_vault_id = var.key_vault_id

  expiration_date = var.expiration_date

  tags = {
    managed-by = "terraform"
  }
}

main.tf

module "store_secret" {
  source = "../../../terraform-providers/azure/modules/key_vault/azurerm_key_vault_secret"

  name   = var.key_vault_key_name
  secret = random_password.password.result

  key_vault_id = var.key_vault_id
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.env-definition.module.temp.module.store_secret.azurerm_key_vault_secret.secret, provider
│ "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Unable to determine the Resource ID for the Key Vault at URL "https://kv-xxxxxx.vault.azure.net/"
│ 
│   with module.env-definition.module.appi_store_key.azurerm_key_vault_secret.secret,
│   on ../../../terraform-providers/azure/modules/key_vault/azurerm_key_vault_secret/azurerm_key_vault_secret.tf line 12, in resource "azurerm_key_vault_secret" "secret":
│   12: resource "azurerm_key_vault_secret" "secret" {
│ 
╵
```

### Expected Behaviour

As seen below I expec 

- 1 key to be updated
- 1 key to be created

```  # module.env-definition.module.appi_store_key.azurerm_key_vault_secret.secret will be updated in-place
  ~ resource "azurerm_key_vault_secret" "secret" {
        id             = "https://kv-xxxxxxxxx.vault.azure.net/secrets/infrastructure-appi-aks-xxxxxx-weeu-instrumentationkey/myid"
        name           = "infrastructure-appi-aks-xxxxxxx-weeu-instrumentationkey"
        tags           = {
            "managed-by" = "terraform"
        }
      ~ value          = (sensitive value)
        # (4 unchanged attributes hidden)
    }

  # module.env-definition.module.temp.module.store_secret.azurerm_key_vault_secret.secret will be created
  + resource "azurerm_key_vault_secret" "secret" {
      + id             = (known after apply)
      + key_vault_id   = "/subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/rg-xxxxx-weeu/providers/Microsoft.KeyVault/vaults/kv-xxxxxx"
      + name           = "helm-temp-xxxxxxxxxxx-password-admin"
      + tags           = {
          + "managed-by" = "terraform"
        }
      + value          = (sensitive value)
      + version        = (known after apply)
      + versionless_id = (known after apply)
    }
```

### Actual Behaviour

-  key helm-temp-xxxxxxxxxxx-password-admin was created on azure keyault but it wasn't in the statefile
- 2nd key `infrastructure-appi-xxxxxx` was never updated

### Steps to Reproduce

- Use a azurerm number 2.9.0 to create a keyvault and a number of keys
- Update azurerm provider to 3.2.0
- `terraform apply`
- try and create new secrets / update existing (with terraform)
- terraform apply

### References

Not sure if https://github.com/hashicorp/terraform-provider-azurerm/issues/11059 is related.

**Comment by tombuildsstuff** [comment]
hi @michelefa1988 

Taking a look through at the error being returned here:

> Error: Unable to determine the Resource ID for the Key Vault at URL "https://kv-xxxxxx.vault.azure.net/"

It appears that Terraform is unable to find this Key Vault within the list of Key Vaults returned from the Resource Manager API for this Subscription, is this in a different subscription to what's currently being used (or set as default, using the Azure CLI)?

Thanks!

**Comment by michelefa1988** [comment]
Hi @tombuildsstuff 

I was successful at reproducing it this morning, however I then noticed I was connected to a VPN (which is running on the Azure but on a different subscription ). After disabling VPN all seemed to have stabilized.

Do you think that this could have caused the above (misleading error)?

Thanks in advance for your help anyway

**Comment by tombuildsstuff** [comment]
@michelefa1988 The VPN wouldn't make any difference here, we're connecting to `management.azure.com` (and then the KeyVault Domain - tbh my guess would be that your making use of Azure CLI auth and that the default subscription for the Azure CLI was changed?

At any rate, glad that's working for you now :)
