### ISSUE TITLE
Support for finding a resource id by tags and getting tags by resource id

### ISSUE THREAD

**Issue by djryanj** [hashicorp/terraform-provider-azurerm#16497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Metadata tags are a first-class way to help organize resources in Azure. 

Using tags to identify/find a thing (possibly uniquely, possibly not) without necessarily knowing its resource ID or other needed data using traditional azurerm resources makes leveraging this capability in Terraform configurations impossible.

For example, I have a VM image that changes regularly with naming that also changes regularly and unpredictably, making encoding this into variables an activity with high administrative overhead. However, finding the "latest" image is easy by using tags. To solve for this, I can use a pipeline or other method to grab the IDs and pass _those_ in as variables to use in my config, but this is not optimal.

Similarly, sometimes I want to grab the tags (or any other attribute) off of something that I know by resource ID but nothing else. 

Having a pair of data resources dedicated to this would be ideal.

### New or Affected Resource(s)/Data Source(s)

- data azurerm_get_resource_by_tags
- data azurerm_get_attributes_from_resource

### Potential Terraform Configuration

```hcl
data "azurerm_get_resource_by_tags" "this" {
    tags = {
      Image = "latest"
     }
}

data "azurerm_get_attributes_from_resource" "this" {
    resource_id = "/subscriptions/***/<etc>"
}

output "image_id" {
  value = data.azurerm_get_resource_by_tags.id
}

output "image_tags" {
  value = data.azurerm_get_resource_by_tags.tags
  # this might seem silly, but consider when you only know part of the tags
}

output "resource_name" {
   value = data.azurerm_get_attributes_from_resource.name
}
```

**Comment by tombuildsstuff** [comment]
hi @djryanj 

Thanks for opening this issue.

Support for filtering images based on the tags is available [in the `azurerm_images` data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/images) - and whilst (for a number of reasons) we don't plan to introduce a generic data source for this, this is something we can look to add more data sources.

If there's specific Data Sources where you'd like to see this supported, then please feel free to open Feature Requests for those specific Data Sources, but as we're not planning to introduce a generic data source for this I'm going to close this issue for the moment.

Thanks!

**Comment by djryanj** [comment]
Thanks @tombuildsstuff , I guess I should just RTFM! :)

**Comment by tombuildsstuff** [comment]
@djryanj np - as a rule the "plural" data sources (e.g. `azurerm_images`) allow filtering whereas the singular (e.g. `azurerm_image`) don't fwiw :)
