### ISSUE TITLE
Azurerm_storage_account allow_blob_public_access missing

### ISSUE THREAD

**Issue by ndrone-kr** [hashicorp/terraform-provider-azurerm#16507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  allow_blob_public_access  = false
}
```

### Debug Output/Panic Output

```shell
Error: Unsupported argument
│
│   on main.tf line 26, in resource "azurerm_storage_account" "example":
│   26:   allow_blob_public_access  = false
│
│ An argument named "allow_blob_public_access" is not expected here.
```

### Expected Behaviour

since enable blob public access is still able to be set via the portal. I would expect that provider still supports this as well. 

### Actual Behaviour

azurerm provider no longer supports argument allow_blob_public_access

### Steps to Reproduce

1. terraform plan

**Comment by tombuildsstuff** [comment]
hi @ndrone-kr 

This field got renamed in 3.0 - see [the upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) for more information.

Thanks!
