### ISSUE TITLE
Documentation: vnet_route_all_enabled missing from azurerm_linux_web_app site config

### ISSUE THREAD

**Issue by samskiter** [hashicorp/terraform-provider-azurerm#16513]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#site_config

Should contain documentation for vnet_route_all_enabled (which it supports and *is* documented in linux_function_app).

### Actual Behaviour

No docs for vnet_route_all_enabled

**Comment by sinbai** [comment]
@samskiter  thank you for posting this issue here. PR [#16513](https://github.com/hashicorp/terraform-provider-azurerm/pull/16531) has been submitted to fix this issue.

**Comment by catriona-m** [comment]
Closing this as this issue has now been addressed by the linked PR. Thanks!
