### ISSUE TITLE
"InvalidDataActionOrNotDataAction" 'Microsoft.ServiceBus/namespaces/messages/send/action' has not published any data operations.

### ISSUE THREAD

**Issue by GavBurke** [hashicorp/terraform-provider-azurerm#16535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.31

### AzureRM Provider Version

2.92.0

### Affected Resource(s)/Data Source(s)

azurerm_role_definition

### Terraform Configuration Files

```hcl
resource "azurerm_role_definition" "servicebus_support_role" {

  scope                = local.deployment_tenant_resource_group_id
  name = "${var.prefix}-sxdb-service-bus-support"
  description = "service bus support role, which provides read access to all resources, plus the send action"
  permissions {
    actions = ["Microsoft.ServiceBus/*/read"]
    data_actions = ["Microsoft.ServiceBus/namespaces/messages/send/action"]
  }
}
```

### Debug Output/Panic Output

```shell
Error: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidDataActionOrNotDataAction" Message="The resource provider referenced in the action 'Microsoft.ServiceBus/namespaces/messages/send/action' has not published any data operations."
```

### Expected Behaviour

The definition should have been created as https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftservicebus suggests Microsoft.ServiceBus/namespaces/messages/send/action is indeed a valid action.  And actually, it was our automated daily deployments which failed Saturday, Sunday and this (Monday) morning, when on Friday it worked.

### Actual Behaviour

TF outputs an error that the Data Action is invalid.

### Steps to Reproduce

Attempt to create role definition containing Microsoft.ServiceBus/namespaces/messages/send/action

**Comment by xiaxyi** [comment]
@GavBurke I can add the role definition successfully using Terraform config that's provided by you.

Can you confirm if you have required permission to add the role definition or you can try creating the custom role in Azure portal to see if the action can be performed:
![image](https://user-images.githubusercontent.com/92154856/165696988-261639ec-c634-4df6-b9da-faf7ca9236a5.png)

**Comment by GavBurke** [comment]
Hi Xiavin

As of yesterday I am able to add both via TF and via the console, all
Sunday, Monday and Tuesday it was missing

Regards

**Comment by xiaxyi** [comment]
@GavBurke Thanks for the update, are you suggesting the feature works fine for you now?

**Comment by GavBurke** [comment]
That’s correct, yesterday those DataActions just reappeared on the console,
and today now appear back in the docs too

**Comment by xiaxyi** [comment]
@GavBurke cool, maybe you would want to check the azure audit log for more insights about the failed actions.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved based on the comments above. As such, I am going to mark this issue as closed.
