### ISSUE TITLE
Support for Azure Virtual Desktop Scheduled Agent Updates

### ISSUE THREAD

**Issue by mattyfrank** [hashicorp/terraform-provider-azurerm#16542]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Summary: Requesting azurerm feature to be added. 

Description: AVD now offers (public preview) Agent Update Schedules. AzureRM does not yet support this feature. This AVD feature is only accessible from REST API or the web portal. It was designed to limit end-user impact of updating agents on session hosts. 

Resource(s): Azure VM that is a AVD Session Host. 

Environment: Terraform 1.1.* & azurerm 3.3.0

[Reference](https://docs.microsoft.com/en-us/azure/virtual-desktop/scheduled-agent-updates)

Potential Feature Example:
```
resource "azurerm_vm_extension" "example" {
  resource_group_name    = "resourcegroupname"
  virtual_machine_id     = "vm.id"
  use_local_host_time    = bool
  time_zone              = "Time_Zone"
  location               = "location"
  enabled                = bool

  primary_schedule = [
        day  = "DD"
        time = "HH"
  ]

  additional_schedule = [
        day  = "DD"
        time = "HH"
  ]
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_vm_extension" "example" {
  resource_group_name    = "resourcegroupname"
  virtual_machine_id     = "vm.id"
  use_local_host_time    = bool
  time_zone              = "Time_Zone"
  location               = "location"
  enabled                = bool

  primary_schedule = [
        day  = "DD"
        time = "HH"
  ]

  additional_schedule = [
        day  = "DD"
        time = "HH"
  ]
}
```

### References

https://docs.microsoft.com/en-us/azure/virtual-desktop/scheduled-agent-updates

**Comment by amccullough84** [comment]
Currently blocked by https://github.com/Azure/azure-sdk-for-go/issues/17783
