### ISSUE TITLE
Support for OIDC Authentication

### ISSUE THREAD

**Issue by SudoSpartanDan** [hashicorp/terraform-provider-azurerm#16554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With https://github.com/hashicorp/go-azure-helpers/issues/91 now finally resolved, I'm opening this feature since the other feature requests were locked.

We should get the library `go-azure-helpers` version `0.31.0` updated in the provider and then add options `id_token_request_url` and `id_token_request_token` to the provider configuration to use the new authentication option.

### New or Affected Resource(s)/Data Source(s)

* Provider Level

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  subscription_id        = "xxxxxxxxxxxxxxxx"
  tenant_id              = "xxxxxxxxxxxxxxxx"
  id_token_request_url   = "xxxxxxxxxxxxxxxx"
  id_token_request_token = "xxxxxxxxxxxxxxxx"
  features {}
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/16226
https://github.com/hashicorp/terraform-provider-azurerm/issues/14525

**Comment by waylew-lexis** [comment]
why is azure so behind on getting this implemented? aws already has gh oidc resources for this https://github.com/br3ndonland/terraform-examples/tree/main/terraform-aws-github-actions-oidc
