### ISSUE TITLE
SQL Manged Instance Failover group fails with Error: Code="InstanceFailoverGroupCreateOrUpdateRequestInvalidPrimary"

### ISSUE THREAD

**Issue by asishr** [hashicorp/terraform-provider-azurerm#16566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance_failover_group

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_managed_instance" "primary" {
  name                         = "example-primary"
  resource_group_name          = azurerm_resource_group.primary.name
  location                     = azurerm_resource_group.primary.location
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
  license_type                 = "BasePrice"
  subnet_id                    = azurerm_subnet.primary.id
  sku_name                     = "GP_Gen5"
  vcores                       = 4
  storage_size_in_gb           = 32

  depends_on = [
    azurerm_subnet_network_security_group_association.primary,
    azurerm_subnet_route_table_association.primary,
  ]

  tags = {
    environment = "prod"
  }
}

resource "azurerm_mssql_managed_instance" "secondary" {
  name                         = "example-secondary"
  resource_group_name          = azurerm_resource_group.secondary.name
  location                     = azurerm_resource_group.secondary.location
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
  license_type                 = "BasePrice"
  subnet_id                    = azurerm_subnet.secondary.id
  sku_name                     = "GP_Gen5"
  vcores                       = 4
  storage_size_in_gb           = 32

  depends_on = [
    azurerm_subnet_network_security_group_association.secondary,
    azurerm_subnet_route_table_association.secondary,
  ]

  tags = {
    environment = "prod"
  }
}

resource "azurerm_mssql_managed_instance_failover_group" "example" {
  name                        = "example-failover-group"
  resource_group_name         = azurerm_resource_group.primary.name
  location                    = azurerm_mssql_managed_instance.primary.location
  managed_instance_id         = azurerm_mssql_managed_instance.primary.id
  partner_managed_instance_id = azurerm_mssql_managed_instance.secondary.id

  read_write_endpoint_failover_policy {
    mode          = "Automatic"
    grace_minutes = 60
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Instance Failover Group: (Name "cetsqlmifailov4" / Location Name "Canada East" / Resource Group "my-sqlmi-rg4"): sql.InstanceFailoverGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InstanceFailoverGroupCreateOrUpdateRequestInvalidPrimary" Message="The given primary field in create or update instance failover group request body is empty or invalid."
│ 
│   with module.sql_mi.azurerm_mssql_managed_instance_failover_group.failover_group["cetmysqlmi-failov4"],
│   on ../../../databases/sql_mi_v2/sql_mi_main.tf line 119, in resource "azurerm_mssql_managed_instance_failover_group" "failover_group":
│  119: resource "azurerm_mssql_managed_instance_failover_group" "failover_group" {
│ 
│ creating Instance Failover Group: (Name "cetsqlmifailov4" / Location Name "Canada East" / Resource Group "my-sqlmi-rg4"): sql.InstanceFailoverGroupsClient#CreateOrUpdate:
│ Failure sending request: StatusCode=400 -- Original Error: Code="InstanceFailoverGroupCreateOrUpdateRequestInvalidPrimary" Message="The given primary field in create or update
│ instance failover group request body is empty or invalid."
```

### Steps to Reproduce

terraform apply

**Comment by sinbai** [comment]
@asishr thank you for opening this issue. Could you please provide the full terraform config to help repro/troubleshooting?

**Comment by asishr** [comment]
Its the config provided above, fails with the error on apply

**Comment by sinbai** [comment]
@asishr thanks for your reply. There are multiple possibilities for the above error. For example: The sql managed instances are in the same region, they have different dnszone etc. Hence, if a full terraform configuration could be provided, it would help with troubeshooting. The "full terraform config"means that it should contain the configuration of all relevant resources, it may include the following resources: azurerm_virtual_network, azurerm_subnet, azurerm_network_security_group, azurerm_network_security_rule, azurerm_route_table, azurerm_subnet_network_security_group_association, azurerm_subnet_route_table_association,azurerm_public_ip,azurerm_virtual_network_gateway,azurerm_virtual_network_gateway_connection, etc.

In addition, it could be found from the configuration file provided above that the `dns_zone_partner_id` property is not configured in the secondary sql managed instance. Per the [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_managed_instance#dns_zone_partner_id), the `dns_zone_partner_id` should be added to the secondary azurerm_mssql_managed_instance with the following details:

```
resource "azurerm_mssql_managed_instance" "secondary" {
  name                         = "example-secondary"
  resource_group_name          = azurerm_resource_group.secondary.name
  location                     = azurerm_resource_group.secondary.location
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
  license_type                 = "BasePrice"
  subnet_id                    = azurerm_subnet.secondary.id
  sku_name                     = "GP_Gen5"
  vcores                       = 4
  storage_size_in_gb           = 32

  # add `dns_zone_partner_id` below will share the DNS zone 
  dns_zone_partner_id = azurerm_mssql_managed_instance.test.id

  depends_on = [
    azurerm_subnet_network_security_group_association.secondary,
    azurerm_subnet_route_table_association.secondary,
  ]

  tags = {
    environment = "prod"
  }
}
```

Besides, The [doc ](https://docs.microsoft.com/en-us/azure/azure-sql/managed-instance/failover-group-add-instance-tutorial?view=azuresql&tabs=azure-portal) of "Add SQL Managed Instance to a failover group" could be used as a reference. Hope this helps you.
