### ISSUE TITLE
azurerm_mssql_server automatically sets minimum_tls_version even if not provided 

### ISSUE THREAD

**Issue by schauppm** [hashicorp/terraform-provider-azurerm#16565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.5

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "example" {
  name                         = "mssqlserver"
  resource_group_name          = "mssqlserver"
  location                     = "westeurope"
  version                      = "12.0"
  administrator_login          = "missadministrator"
  administrator_login_password = "thisIsKat11"
}
```

### Debug Output/Panic Output

```shell
# module.mssql-server.azurerm_mssql_server.primary will be created
  + resource "azurerm_mssql_server" "example" {
      + administrator_login                  = "missadministrator"
      + administrator_login_password         = (sensitive value)
      + connection_policy                    = "Default"
      + fully_qualified_domain_name          = (known after apply)
      + id                                   = (known after apply)
      + location                             = "westeurope"
      + minimum_tls_version                  = "1.2"
      + name                                 = "mssqlserver"
      + outbound_network_restriction_enabled = false
      + primary_user_assigned_identity_id    = (known after apply)
      + public_network_access_enabled        = true
      + resource_group_name                  = "mssqlserver"
```

### Expected Behaviour

My expectaion is that a MSSQL server is created without any minimum TLS setting applied.
According to the documentation, any settings that have a default value applied are listed as such.
minimum_tls_version does not have a default value according to the doc: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server

### Actual Behaviour

If I don't provide "minimum_tls_version", the minimum_tls_version 1.2 is applied per default. If I provide minimum_tls_version = "1.0" is is exactly applied as such.

I can create a MSSQL server without minimum TLS settings through Azure portal.

I can also create a MSSQL server without minumim TLS settings through terraform with azurerm provider 2.99, I have not checked any other provider versions yet

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_server

**Comment by sinbai** [comment]
@schauppm thank you for posting this issue here. I have submitted PR #16595 to resolve this issue. Please track it for updates.

**Comment by rcskosir** [comment]
@schauppm Thank you for opening this issue. @sinbai Thank you for your PR #16595 that resolves this issue. As such, I will mark this issue as closed.
