### ISSUE TITLE
Request for feedback: your experience using Logic Apps

### ISSUE THREAD

**Issue by opslivia** [hashicorp/terraform-provider-azurerm#16571]
👋

After speaking with many of you, we heard a lot of feedback around deploying Logic App resources with the provider.

We want to make this experience better for everyone. To do that, we'd like to dive deeper into your particular Logic Apps journey.

If you use Logic Apps and want your experience included in upcoming improvements, please sign up for a quick one-on-one session with us [here](https://calendly.com/hashicorp-oliviac/tf-azure-providers-experience)!

Thanks!

**Comment by opslivia** [comment]
Resources on the subject:
[azurerm_logic_app_action_custom](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_action_custom)
[azurerm_logic_app_action_http](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_action_http)
[azurerm_logic_app_integration_account](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account)
[azurerm_logic_app_integration_account_agreement](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_agreement)
[azurerm_logic_app_integration_account_assembly](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_assembly)
[azurerm_logic_app_integration_account_batch_configuration](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_batch_configuration)
[azurerm_logic_app_integration_account_certificate](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_certificate)
[azurerm_logic_app_integration_account_map](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_map)
[azurerm_logic_app_integration_account_partner](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_partner)
[azurerm_logic_app_integration_account_schema](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_schema)
[azurerm_logic_app_integration_account_session](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_integration_account_session)
[azurerm_logic_app_standard](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_standard)
[azurerm_logic_app_trigger_custom](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_trigger_custom)
[azurerm_logic_app_trigger_http_request](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_trigger_http_request)
[azurerm_logic_app_trigger_recurrence](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_trigger_recurrence)
[azurerm_logic_app_workflow](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/logic_app_workflow)

**Comment by mlcooper** [comment]
Are there plans to support an Event becoming available in an Event Hub as a trigger.  For example, perhaps something like `azurerm_logic_app_trigger_event_available_in_event_hub`. This is the trigger for my Logic Apps, but with the currently supported triggers I could not find a way to build my Logic Apps in Terraform. I built them in an ARM template and had TF deploy that.

**Comment by opslivia** [comment]
> Are there plans to support an Event becoming available in an Event Hub as a trigger. For example, perhaps something like `azurerm_logic_app_trigger_event_available_in_event_hub`. This is the trigger for my Logic Apps, but with the currently supported triggers I could not find a way to build my Logic Apps in Terraform. I built them in an ARM template and had TF deploy that.

@mlcooper hmm I'm not sure - maybe! Want to meet for 30min to show me your situation? My Calendly link is in the issue description.

**Comment by opslivia** [comment]
closing for now
