### ISSUE TITLE
Doc Link is missing https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret.html

### ISSUE THREAD

**Issue by infa-mseelam** [hashicorp/terraform-provider-azurerm#16584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The following link is missing https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret.html

### Terraform Version

latest

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

terraform

### Terraform Configuration Files

```hcl
The following link is missing https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret.html
```

### Debug Output/Panic Output

```shell
The following link is missing https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret.html
```

**Comment by jayendranarumugam** [comment]
You have to remove the `.html` in your URL. You don't need to provide that

**Comment by catriona-m** [comment]
Looks like this works by going to: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret

So this can be closed now. Thanks!
