### ISSUE TITLE
Documentation for azurerm_sql_database contains broken link

### ISSUE THREAD

**Issue by michael-staffa** [hashicorp/terraform-provider-azurerm#16582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

N/A

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_sql_data base

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Link to documentation for the [edition](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database#edition) field should open a tab to the proper documentation found [here](https://docs.microsoft.com/en-gb/azure/azure-sql/database/purchasing-models?view=azuresql).

### Actual Behaviour

Documentation link for the [edition](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database#edition) field is broken and brings users to a 404 - Not Found.

### Steps to Reproduce

1. Go to the [`azurerm_sql_database`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database#edition) page
2. Scroll to the "Edition" parameter
3. Click the link labelled "[Azure SQL Database Service Tiers](https://azure.microsoft.com/en-gb/documentation/articles/sql-database-service-tiers/)"

**Comment by rcskosir** [comment]
Thank you for opening this issue, the link appears to be working as expect now, therefore I will mark this issue as closed.
