### ISSUE TITLE
[azurerm_kusto_cluster] Prior to AzureRM 3.2.0, public_network_access_enabled argument isn't documented

### ISSUE THREAD

**Issue by jaredbrogan** [hashicorp/terraform-provider-azurerm#16607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Prior to AzureRM 3.2.0, the argument `public_network_access_enabled` is not documented for the `azurerm_kusto_cluster` resource, but is still available to use.

Not sure if you have a process for updating older documentation, but wanted to at least share this.

---

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13.7

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

**Comment by rcskosir** [comment]
@jaredbrogan Apologies for the delayed response. We do not update older documentation, with that I am going to close this issue. Thank you for reaching out!
