### ISSUE TITLE
Missing state migration for `availability_zones` on AKS (node pool)

### ISSUE THREAD

**Issue by pst** [hashicorp/terraform-provider-azurerm#16611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
https://github.com/kbst/terraform-kubestack/pull/276/files
```

### Debug Output/Panic Output

```shell
https://gist.github.com/pst/ab8d7292adad7439b6fed445ed475c3a
```

### Expected Behaviour

Succesful run

### Actual Behaviour

```
│ Error: Failed to decode resource from state
│ 
│ Error decoding
│ "module.aks_zero_node_pool.module.node_pool.azurerm_kubernetes_cluster_node_pool.current"
│ from previous state: unsupported attribute "availability_zones"
```

### Steps to Reproduce

Create an AKS cluster and node pool with azurerm < 3.0.0, then upgrade the provider and run terraform plan.

**Comment by OceaneLonneux-CAL** [comment]
We are having the same issue with `addon_profile.ingress_application_gateway` that becomes `ingress_application_gateway`. The state does not reconcile. 

Thank you for opening this issue.

**Comment by tombuildsstuff** [comment]
@pst there's no state migration needed for these removals - running `terraform refresh` should be sufficient, can you try that and see how you get on?

**Comment by pst** [comment]
@tombuildsstuff unfortunately `terraform refresh` results in the same error message.

```
│ Error: Failed to decode resource from state
│ 
│ Error decoding
│ "module.aks_zero_node_pool.module.node_pool.azurerm_kubernetes_cluster_node_pool.current"
│ from previous state: unsupported attribute "availability_zones"
╵
```

**Comment by waza-ari** [comment]
Seeing the same behaviour here. Error happens already during the refresh:

```
│ Error: Failed to decode resource from state
│ 
│ Error decoding "module.cluster.azurerm_kubernetes_cluster_node_pool.k8s_user_node_pool[0]" from previous state: unsupported attribute "availability_zones"
```

**Comment by pst** [comment]
I've retried now with Terraform 1.3.x and it was successful. I'm closing my issue.
