### ISSUE TITLE
Support for sticky_settings on windows_web_app_slot (and other kinds of resources for slots)

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#16613]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add the feature added in https://github.com/hashicorp/terraform-provider-azurerm/pull/16546 to the slots related resources. Without support in slots, the feature is incomplete.

### New or Affected Resource(s)/Data Source(s)

windows_web_app_slot (and other kinds of resources for slots)

**Comment by joshschmitter** [comment]
Seems like https://github.com/hashicorp/terraform-provider-azurerm/issues/1440 should not have been closed as slots were already part of the feature request.  https://github.com/hashicorp/terraform-provider-azurerm/pull/16546 only partially fulfilled it.

**Comment by JiriKovar** [comment]
Hi @joshschmitter 

Thank you for your answer, but the thing is that `azurerm_app_service_slot` mentioned in the #1440 is deprecated and replaced by the `azurerm_windows_web_app_slot` that didn't even exist back in 2018. Which means that it's OK that the #1440 was closed back then, but it's not OK that the `azurerm_windows_web_app_slot` was released as a replacement without a proper support for sticky slots.

**Comment by bigwheels490** [comment]
I agree with @joshschmitter.  PR [@16546](https://github.com/hashicorp/terraform-provider-azurerm/pull/16546) specifically states that the fix is being applied to `azurerm_linux_function_app`, `azurerm_linux_wep_app`, `azurerm_windows_function_app`, and `azurerm_windows_web_app` (both the resource and data types).  While you are correct that those types didn't exist in 2018 when the issue was created, they did exist when that PR was submitted in April 2022.  It should not have been marked complete as it completely ignored the slot variants of all of those.  I just discovered this oversight as I was relying on being able to set a sticky app setting on our non-production slots.

**Comment by toothpasteBeforeOj** [comment]
Is there any kind of ETA on a fix for this? For azurerm_windows_function_app especially. If there are function apps on a consumption plan, they share the storage account and a sticky setting must be set in order for the slot app to function.

**Comment by okogut** [comment]
Also curious to hear the ETA.

**Comment by toothpasteBeforeOj** [comment]
> Also curious to hear the ETA.

After some research, I saw the az cli works the same. You don't actually need to specify sticky setting names on the slot - just the parent resource and it will apply to any slots that have that setting. So wait no further ☺️

**Comment by okogut** [comment]
Thanks, but will that also work when the app service is created before the slot?

**Comment by toothpasteBeforeOj** [comment]
Yes, it does. I have this working in my scripts today. App service is created first, then slot is created with the dependency on the app service.

**Comment by okogut** [comment]
Cool, I’ll try that. Thanks again
