### ISSUE TITLE
azurerm_windows_web_app sticky_settings app_setting_names doesnt allow valid characters

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#16612]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app and possibly everything with sticky_settings property mentioned here: https://github.com/hashicorp/terraform-provider-azurerm/pull/16546

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "app_service" {
  name                = var.service_name
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name
  service_plan_id     = var.app_service_plan_id

  site_config {
    always_on         = local.site_config.always_on
    ...
  }

  app_settings = {
    "ConfigManager:Location" = var.config_manager.location
    ...
  }

  sticky_settings {
    app_setting_names = ["ConfigManager:Location"] //the colon is not allowed by the azurerm provider even though we have had this setting in Azure for years
    ...
  }
}
```

### Debug Output/Panic Output

```shell
Error: "sticky_settings.0.app_setting_names.0" may only contain alphanumeric characters, periods and underscores
```

### Expected Behaviour

The azurerm provider allows all characters allowed in the Azure App Settings. I.e. it allows to implement the suggested hierarchical namespaces via colons, or slashes as well as use other common practices described here: https://docs.microsoft.com/en-us/azure/azure-app-configuration/concept-key-value

### Actual Behaviour

The azurerm provider does not allow us to use the common key naming practices, which prevents us from upgrading from azurerm_app_service resource to the azurerm_windows_web_app

### Steps to Reproduce

Try to add any setting that is allowed in the Azure App Service -> Configuration -> Application Settings that contains characters other than the characters allowed by the current provider. Other than my example with colon, you can try adding a Key Vault Reference, which has a syntax: `@Microsoft.KeyVault({referenceString})`. More on that: https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

**Comment by enorlando** [comment]
We are also encountering this issue when using resource `azurerm_windows_function_app`
```Error: "sticky_settings.0.app_setting_names.1" may only contain alphanumeric characters, periods and underscores

with azurerm_windows_function_app.xxx,
on xxx.tf line 256, in resource "azurerm_windows_function_app" "xxx":
 256:       "APPINSIGHTS_INSTRUMENTATIONKEY", "APPLICATIONINSIGHTS_CONNECTION_STRING ",
```

**Comment by nu12** [comment]
After importing an existing azurerm_windows_web_app, the "APPLICATIONINSIGHTS_CONNECTION_STRING " came with an extra space at the end (just like in @enorlando example above), which is not valid. 

However, the error message was always pointing to the last value of the list so I was looking at the wrong place trying to debug this. Once the extra  space was removed it started working again.

**Comment by enorlando** [comment]
@nu12 Thank you for your input. Once I removed the extra space from the app setting name, it all worked and I as able to apply the change.
