### ISSUE TITLE
Support fora resource to configure vulnerability assessment for virtual machine scale sets

### ISSUE THREAD

**Issue by Miouge1** [hashicorp/terraform-provider-azurerm#16626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new resource to configure vulnerability assessment for virtual machine scale sets.

This is already available for virtual machines and arc virtual machines, but not for scale sets.

### New or Affected Resource(s)/Data Source(s)

security_center_server_vulnerability_assessment_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "security_center_server_vulnerability_assessment_virtual_machine_scale_set" "example" {
  virtual_machine_scale_set_id = azurerm_linux_virtual_machine_scale_set.example.id
}
```

### References

- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/security_center_server_vulnerability_assessment_virtual_machine

**Comment by myc2h6o** [comment]
Hi @Miouge1 It looks like server vulnerability assessment for virtual machine scale set or instances of a scale set is not supported yet. Maybe you can add a feature request to Azure to add the support.

It throws below error when I try enabling it with REST API:
```
PUT https://management.azure.com/subscriptions/<subscription_id>/resourceGroups/<rg_name>/providers/Microsoft.Compute/virtualMachineScaleSets/<vmss_name>/providers/Microsoft.Security/serverVulnerabilityAssessments/Default?api-version=2020-01-01
{
    "error": {
        "code": "BadRequest",
        "message": "Got an unsupported resource type for extension. The supported types are: Microsoft.HybridCompute/machines; Microsoft.Compute/virtualMachines"
    }
}
```

https://docs.microsoft.com/en-us/azure/defender-for-cloud/deploy-vulnerability-assessment-vm#why-does-my-machine-show-as-not-applicable-in-the-recommendation
> It's an image in an AKS cluster or part of a virtual machine scale set - This extension doesn't support VMs that are PaaS resources.

**Comment by Miouge1** [comment]
That's right, thank you.
