### ISSUE TITLE
Azure VMWare Solution Private Cloud -- The number of retries has been exceeded: StatusCode=200

### ISSUE THREAD

**Issue by jchancellor-ms** [hashicorp/terraform-provider-azurerm#16637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_vmware_private_cloud

### Terraform Configuration Files

```hcl
resource "azurerm_vmware_private_cloud" "privatecloud" {
  name                = var.sddc_name
  resource_group_name = var.rg_name
  location            = var.rg_location
  sku_name            = var.sddc_sku
  tags                = var.tags

  management_cluster {
    size = var.management_cluster_size
  }

  network_subnet_cidr         = var.avs_network_cidr
  internet_connection_enabled = false
  nsxt_password               = random_password.nsxt.result
  vcenter_password            = random_password.vcenter.result

  timeouts {
    create = "10h"
  }

  lifecycle {
    ignore_changes = [
      nsxt_password,
      vcenter_password
    ]
  }
}
```

### Debug Output/Panic Output

```shell
│ Resource Group Name: "tfSEA4-PrivateCloud-vbl1"
│ Private Cloud Name: "tfSEA4-SDDC-vbl1"): polling after CreateOrUpdate: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=200
```

### Expected Behaviour

Azure VMWare Solution (AVS) private cloud completes deployment without error and downstream resources continue deploying after the private cloud deployment.

### Actual Behaviour

Deployment errored with the timeout error listed, with a status code of 200. (this is different that the 4xx errors seen in other issues).  The actual private cloud deployment completed successfully even though the full terraform apply deployment errored out.  

Common AVS deployments can be 6-9 hours long, so we set the timeout value to 10 hours to account for this behavior.  It appears that there is also a polling retry limit that was exceeded in this case.  Hoping to understand if there is a way to modify the polling behaviors similar to the timeouts to ensure we don't exceed the retry limits.  The polling frequency for this resource can be less frequent as the expected deployment time frame is long.  If there is no polling configuration options available, would it be possible to link the retries to the timeout values instead?  (i.e. 10s retries on 10h would be 3600 total retries or something similar)

### Steps to Reproduce

Happens during a normal terraform apply.

I'm using an empty features block with the azurerm provider, and backend state authenticating using azuread auth.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. After tested with latest azurerm provider and below tf config that is similar with yours, seems I cannot repro this issue. If it's possbile, you could try below tf config and latest azurerm provider to see if the issue still exists.

tf config:
```
provider "azurerm" {
  features {}
  disable_correlation_request_id = true
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRGvmwaretest02"
  location = "Australia East"
}

resource "azurerm_vmware_private_cloud" "test" {
  name                = "acctestvpctest02"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku_name            = "av36"

  management_cluster {
    size = 3
  }

  network_subnet_cidr         = "192.168.48.0/22"
  internet_connection_enabled = false
  nsxt_password               = "RgvRjf13$Abc"
  vcenter_password            = "UpcWtc23$Qdf"

  tags = {
    ENV = "Test"
  }
}
```

![image](https://user-images.githubusercontent.com/19754191/167232466-b47e9683-22be-4842-92c3-0756151e4e2e.png)

**Comment by jchancellor-ms** [comment]
Neil,

I attempted a new deployment with the latest provider (3.5.0) and got the same error. (Although not with your code snippet.  I don't have quota in Australia East, so I'm testing in Southeast Asia.)  I re-attempted with your code yesterday afternoon and had the same issue, although removing the custom timeout of 10 hours caused the error to occur at 2.5 hours in instead of 4 hours.

I'll take a debug the next time I deploy to see if I can get any more details.
Jon

**Comment by jchancellor-ms** [comment]
Closing this issue as I have not seen a re-occurence.
