### ISSUE TITLE
terraform import does not import `resource_group_name` for `azurerm_iothub_endpoint_*` resources

### ISSUE THREAD

**Issue by ilya-git** [hashicorp/terraform-provider-azurerm#16636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.4

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_iothub_endpoint_*

### Terraform Configuration Files

```hcl
resource "azurerm_iothub_endpoint_eventhub" "example" {
  resource_group_name = var.resource_group
  iothub_id           = azurerm_iothub.iot_hub.id
  name                = "example"

  connection_string = var.connection_string
}
```

### Debug Output/Panic Output

```shell
After running `terraform import -var-file=/settings.tfvars module.iothub.azurerm_iothub_endpoint_eventhub.example /subscriptions/<guid>/resourceGroups/<rg-name>/providers/Microsoft.Devices/IotHubs/<iot-hub-name>/Endpoints/example` the terraform reports a success. The subsequent plan shows this:


  # module.iothub.azurerm_iothub_endpoint_eventhub.example must be replaced
-/+ resource "azurerm_iothub_endpoint_eventhub" "example" {
      # ...
      + resource_group_name = "<rg-name>" # forces replacement
      # ...
    }
```

### Expected Behaviour

`resource_group_name` should have been populated during import

### Actual Behaviour

`resource_group_name` was not populated during import

### Steps to Reproduce

1. Create the resource from example
2. Import this resource into the state
3. Run terraform plan

P.S. Any input on a workaround is welcome :). I tried to run refresh to no avail

**Comment by myc2h6o** [comment]
Hi @ilya-git I've tried the same thing and it works fine for newly created iot hub endpoints. Besides import, before plan/apply, Terraform runs a refresh which retrieves the `resource_group_name` as well, but looks like your iot hub endpoint doesn't have it. Would you mind check with REST API or Azure Resource Explorer https://resources.azure.com/ to see if the `resourceGroup` is present for the iot hub routing endpoint? Below is the detail of my iot hub from the Azure Resource Explorer
```
https://resources.azure.com/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/yicmaiot/providers/Microsoft.Devices/IotHubs/yicmaiothub
...
"routing": {
      "endpoints": {
        "serviceBusQueues": [],
        "serviceBusTopics": [],
        "eventHubs": [
          {
            "connectionString": "Endpoint=sb://yicmaeventsamerg.servicebus.windows.net:5671/;SharedAccessKeyName=iothubroutes_yicmaiothub;SharedAccessKey=****;EntityPath=hub1",
            "name": "samerg",
            "id": "8658f5fa-e47b-4c10-8139-0bb270fe3224",
            "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "resourceGroup": "yicmaiot"
          },
          {
            "connectionString": "Endpoint=sb://yicmadiffrg.servicebus.windows.net:5671/;SharedAccessKeyName=iothubroutes_yicmaiothub;SharedAccessKey=****;EntityPath=hub2",
            "name": "diffrg",
            "id": "30639924-4797-409f-b718-3a7b9df06882",
            "subscriptionId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
            "resourceGroup": "yicma2"
          }
        ]
      },
...
```

**Comment by ilya-git** [comment]
Hi! I have unfortunately already recreated the resources, so I would not be able to verify that :(
I can though confirm that the endpoints were relatively old, so it might be possible that this information was not available there before?

I tried to run refresh manually as well, that did not help.

**Comment by myc2h6o** [comment]
maybe you can try import on the newly created resource? did you run refresh manually on the old one or the new one?

**Comment by ilya-git** [comment]
I did run refresh on the old ones manually and it did not help.

I have checked that the new resources do have resourceGroup, I have found an old iot hub (another one) and checked that endpoints there have resources as well (not a guarantee that mine had them though, but possibly)

**Comment by myc2h6o** [comment]
Got it. For the deleted iothub, maybe contacting Azure support could help you identify whether or not the `recoureGroup` property is set. If you find any issue with importing the new endpoints, please share the output and we could take a further look.

**Comment by ilya-git** [comment]
The iot hub itselft was not deleted, just all of the endpoints were recreated, so unless Microsoft keeps some history of these versions it is probably not possible to get anymore...

But if you cannot reproduce it with the new endpoints (and I do not have the test case anymore as I had to quickly fix some things) it is probably best if we just close this issue?

**Comment by myc2h6o** [comment]
I see. Since we are not able to repro it with the new endpoints, let's close the issue. And feel free to reopen it if it happens again. Thanks!
