### ISSUE TITLE
azurerm_cdn_endpoint_custom_domain : certificate updated each time with user_managed_https

### ISSUE THREAD

**Issue by benj-ch** [hashicorp/terraform-provider-azurerm#16630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_endpoint_custom_domain

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "kv" {
   name                = var.key_vault_name
   resource_group_name = var.key_vault_rg_name
 }

data "azurerm_key_vault_certificate" "cert" {
  name         = var.cert_name
  key_vault_id = data.azurerm_key_vault.kv.id
}

resource "azurerm_cdn_profile" "profile" {
  name                = "example-profile"
  location            = "East US2"
  resource_group_name = "examplegroup"
  sku                 = "Standard_Microsoft"
}

resource "azurerm_cdn_endpoint" "endpoint" {
  name                = "example-endpoint"
  profile_name        = azurerm_cdn_profile.profile.name
  location            = azurerm_cdn_profile.profile.location
  resource_group_name = azurerm_cdn_profile.profile.resource_group_name

  origin {
    name      = "example-name"
    host_name = "cdn.example.com"
  }
}

resource "azurerm_cdn_endpoint_custom_domain" "endpoint" {
  name            = "example"
  cdn_endpoint_id = azurerm_cdn_endpoint.endpoint.id
  host_name       = "cdn.example.net"

  user_managed_https {
    key_vault_certificate_id = data.azurerm_key_vault_certificate.cert.id
    or
    key_vault_certificate_id = "https://<kv-name>.vault.azure.net/certificates/<cert-name>"
  }
}
```

### Debug Output/Panic Output

```shell
[WARN]  Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for azurerm_cdn_endpoint_custom_domain.endpoint, but we are tolerating it because it is using the legacy plugin SDK.
The following problems may be the cause of any confusing errors from downstream operations:
  - .user_managed_https[0].key_vault_certificate_id: was cty.StringVal("https://<kv-name>.vault.azure.net/secrets/<cert-name>/088dce7f3cba41a28a2926dad26690ef"), but now cty.StringVal("https://<kv-name>.vault.azure.net/certificates/<cert-name>/088dce7f3cba41a28a2926dad26690ef")
```

### Expected Behaviour

Once the certificate is set and don't change, terraform should not update the certificate
Selected sku for profile is "Standard_Microsoft"

### Actual Behaviour

```
# azurerm_cdn_endpoint_custom_domain.endpoint will be updated in-place
~ resource "azurerm_cdn_endpoint_custom_domain" "endpoint" {
        id              = "/subscriptions/<subscription-id>/resourceGroups/examplegroup/providers/Microsoft.Cdn/profiles/example-profile/endpoints/example-endpoint/customDomains/example"
        name            = "example"
        # (2 unchanged attributes hidden)
      ~ user_managed_https {
          ~ key_vault_certificate_id = "https://<kv-name>.vault.azure.net/certificates/<cert-name>/088dce7f3cba41a28a2926dad26690ef" -> "https://<kv-name>.vault.azure.net/secrets/<cert-name>/088dce7f3cba41a28a2926dad26690ef"
            # (1 unchanged attribute hidden)
        }
    }
```

**Comment by magodo** [comment]
@benj-ch Thank you for reporting this!

Would you please provide the [debug log](https://www.terraform.io/internals/debugging) with `TF_LOG = DEBUG`?

**Comment by benj-ch** [comment]
@magodo Sorry for the delay, we had a dns migration. I couldn't make any test.

[Here the file debug file](https://github.com/hashicorp/terraform-provider-azurerm/files/8662338/debug.txt)

**Comment by magodo** [comment]
@benj-ch I searched for the same line as below in the debug log, but didn't find a match:

```
- .user_managed_https[0].key_vault_certificate_id: was cty.StringVal
```

I also saw there is a GET call to the key vault secret. If the output of the CLI still shows that there is a change on the `key_vault_certificate_id` from the certificate id to the secret id, then could you double confirm you are referencing the certificate data source rather than the secret one?

**Comment by benj-ch** [comment]
@magodo I did a new debug log to provide the file. 

You're right, I used the secret data source and not the certificate data source (I done a copy/paste from a custom domain https on azure front door).
I thought it worked the same way.

Thank you @magodo
