### ISSUE TITLE
Geo-replication regions deleted/recreated when modified

### ISSUE THREAD

**Issue by eanveden** [hashicorp/terraform-provider-azurerm#16634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "acr" {
  # Whatever other settings, but has to be a premium registry
  georeplication_locations      = [
    "westus",
    "canadaeast",
    "canadacentral",
    "uksouth",
    "ukwest",
    "northeurope",
    "westeurope",
    "germanywestcentral",
    "australiaeast",
    "australiasoutheast"
  ]
}
```

### Debug Output/Panic Output

```shell
A plan after removing 'australiasoutheast' produces the following output:

# azurerm_container_registry.acr will be updated in-place
  ~ resource "azurerm_container_registry" "acr" {
      ~ georeplication_locations      = [
          - "australiasoutheast",
            # (9 unchanged elements hidden)
        ]

An Apply will remove/recreate all the geo-replications causing temporary downtime, in our case it was even worse because the apply failed halfway through (deleting some geo-replications we did not intend on touching at all)
```

### Expected Behaviour

When 'australiasoutheast' (or any other region) is removed from the list of Geo-replications, it should only delete the targeted replication, or at least indicate that ALL replications will be deleted/recreated (see https://github.com/hashicorp/terraform-provider-azurerm/blob/35a2aa81e342d142b5152f83511e8d36278099b7/internal/services/containers/container_registry_resource.go#L434)

### Actual Behaviour

When deleting one or more of the geo-replications, it deletes/recreates all of them, potentially causing downtime and other issues for big container registries. In our case the apply failed halfway through, causing unwanted deletion of some Geo-replications that we did not intend to touch.

### Steps to Reproduce

1. Terraform plan/apply with the above Geo-replication regions
2. Terraform plan/apply with one region commented out

### References

**Comment by LP0101** [comment]
Can confirm this is an issue. Additionally, if the ACR instance is configured with private endpoints, each georeplication will have its own PEP/IP. Given the current logic in the azurerm provider, deleting a single replication will cause them all to be recreated, also resulting in all of them getting a new PEP/IP, which can lead to additional downtime.
