### ISSUE TITLE
Documentation for azurerm_spring_cloud.required_network_traffic_rules is incorrect

### ISSUE THREAD

**Issue by justinp-kr** [hashicorp/terraform-provider-azurerm#16648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_spring_cloud

### Terraform Configuration Files

```hcl
destination_addresses = azurerm_spring_cloud_service.spring_cloud.required_network_traffic_rules[0].ips
```

### Debug Output/Panic Output

```shell
| destination_addresses = azurerm_spring_cloud_service.spring_cloud.required_network_traffic_rules[0].ips
│ 
│ This object does not have an attribute named "ips".
```

### Expected Behaviour

Documentation should reflect actual field, "ip_addresses".

### Actual Behaviour

Documentation mistakenly lists field as "ips".

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.4.0/docs/resources/spring_cloud_service#required_network_traffic_rules

**Comment by catriona-m** [comment]
Thanks @justinp-kr, this has now been fixed by #16675.
