### ISSUE TITLE
Support for SignalR custom domain

### ISSUE THREAD

**Issue by thanksnext** [hashicorp/terraform-provider-azurerm#16651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since SignalR on Azure starts supporting custom domains. We wonder to know when will Terraform support this feature.

### New or Affected Resource(s)/Data Source(s)

azurerm_signalr_service

**Comment by stephybun** [comment]
Closed by #21153
