### ISSUE TITLE
WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE settings are lost when using azurerm_linux_function_app_slot

### ISSUE THREAD

**Issue by sberube** [hashicorp/terraform-provider-azurerm#16650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app_slot

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "rg-linux-func"
  location = "Canada Central"
}

resource "azurerm_storage_account" "example" {
  name                     = "linuxfuncapp"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "example" {
  name                = "plan-ep1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "EP1"
}

resource "azurerm_linux_function_app" "example" {
  name                        = "linux-func-app"
  resource_group_name         = azurerm_resource_group.example.name
  location                    = azurerm_resource_group.example.location
  service_plan_id             = azurerm_service_plan.example.id
  storage_account_name        = azurerm_storage_account.example.name
  storage_account_access_key  = azurerm_storage_account.example.primary_access_key

  site_config {
    application_stack {
      dotnet_version = "6.0"
    }
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_linux_function_app_slot" "example" {
  name                        = "stage"
  function_app_id             = azurerm_linux_function_app.example.id
  storage_account_name        = azurerm_storage_account.example.name
  storage_account_access_key  = azurerm_storage_account.example.primary_access_key

  site_config {
    application_stack {
      dotnet_version = "6.0"
    }
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

N/A

### Expected Behaviour

WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE settings should not be removed because a storage is specified in the Terraform script file.

### Actual Behaviour

The second time we run the plan on the Function App Slot, WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE settings are lost.

### Steps to Reproduce

1. Generate the plan and apply it
2. Wait for the plan to apply
3. Generate the plan a second time and apply it
4. The plan is "correctly" applied
5. WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE settings are removed from the slot configuration in the Function App

**Comment by ramseytm** [comment]
We're experiencing this bug with TF 1.2.5 with azurerm 3.13.0 as well. Just wanted to see if there was timeline for when this fix would be in place? It's causing issues with our deployment as it causes our slot to stop functioning and we can no longer deploy to it unless we manually re-add these settings.
