### ISSUE TITLE
JAVASCRIPT SOURCE MAP BLOB STORAGE URL property for application insights in terraform missing

### ISSUE THREAD

**Issue by induyadavswissre** [hashicorp/terraform-provider-azurerm#16683]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Community Note

I am using the azurerm provider for creating all azure resources. 

In Application Insights need to configure 'JAVASCRIPT SOURCE MAP BLOB STORAGE URL' which contain the javascript source maps, so that via Application Insights see javascript information before it was minified. but, I cannot configure this setting via azurerm.

### Description

I am using the azurerm provider for creating all azure resources. 

In Application Insights need to configure 'JAVASCRIPT SOURCE MAP BLOB STORAGE URL' which contain the javascript source maps, so that via Application Insights see javascript information before it was minified. but, I cannot configure this setting via azurerm.

### New or Affected Resource(s)/Data Source(s)

azurerm_application_insights

### References

https://docs.microsoft.com/en-us/azure/azure-monitor/app/source-map-support#from-the-properties-page
https://github.com/microsoft/ApplicationInsights-JS

**Comment by ms-zhenhua** [comment]
Hi @induyadavswissre, this issue seems the same as [13255](https://github.com/hashicorp/terraform-provider-azurerm/issues/13255).  You could add a **"hidden-link:Insights.Sourcemap.Storage"** tag to set the 'JAVASCRIPT SOURCE MAP BLOB STORAGE URL'. The schema may look like below(Kindly replace the <storage_account_name> and <blob_container_name> with your own configuration).

```
tags = { 
    "hidden-link:Insights.Sourcemap.Storage" = jsonencode( { Uri = "https://<storage_account_name>.blob.core.windows.net/<blob_container_name>" } ) 
}
```

**Comment by mybayern1974** [comment]
@induyadavswissre with ms-zhenhua's suggestion, I'm closing this issue for duplicate with #13255 and please subscribe to #13255 if ms-zhenhua's suggestion is unable to unblock. Or feel free to suggest to reopen this issue if you between these two issues are talking about different stories.
