### ISSUE TITLE
Error: setting `network_configuration`: Invalid address to set: []string{"network_configuration", "0", "public_address_provisioning_type"}

### ISSUE THREAD

**Issue by Yaron-Hazan** [hashicorp/terraform-provider-azurerm#16702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

 1.1.9

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_batch_pool - data source

### Terraform Configuration Files

```hcl
data "azurerm_batch_pool" "example" {
  name                = "testbatchpool"
  account_name        = "testbatchaccount"
  resource_group_name = "test"
}

output "test" {
  value = data.azurerm_batch_pool.example
}
```

### Debug Output/Panic Output

```shell
Error: setting `network_configuration`: Invalid address to set: []string{"network_configuration", "0", "public_address_provisioning_type"}
│
│   with data.azurerm_batch_pool.example,
│   on main.tf line 18, in data "azurerm_batch_pool" "example":
│   18: data "azurerm_batch_pool" "example" {
```

### Expected Behaviour

Data source reads state of azurerm_batch_pool

### Actual Behaviour

│ Error: setting `network_configuration`: Invalid address to set: []string{"network_configuration", "0", "public_address_provisioning_type"}
│
│   with data.azurerm_batch_pool.example,
│   on main.tf line 18, in data "azurerm_batch_pool" "example":
│   18: data "azurerm_batch_pool" "example" {
│

### Steps to Reproduce

Run terraform plan  (should complete without error)
Run terraform apply (should complete without error)

### Important Factoids

We use IP address provisioning type NoPublicIPAddresses for node pools

**Comment by Yaron-Hazan** [comment]
@xiaxyi  Sure, this is the pool configuration I am using

resource "azurerm_batch_pool" "batch_pool" {
  for_each            = { for pool in var.pool_data : pool.name => pool }
  name                = "${each.value.name}-pool"
  resource_group_name = azurerm_resource_group.batch_rg.name
  account_name        = azurerm_batch_account.batch_account.name
  display_name        = lookup(each.value, "display_name", "")
  vm_size             = each.value.vm_size
  node_agent_sku_id   = lookup(each.value, "node_agent_sku_id", "batch.node.windows amd64")
  max_tasks_per_node  = lookup(each.value, "max_tasks_per_node", 1)

  auto_scale {
    evaluation_interval = lookup(each.value, "eval_interval", "PT5M")
    formula             = each.value.autoscale_formula
  }

  dynamic "storage_image_reference" {
    for_each = list(lookup(each.value, "node_image_id", local.default_pool_image_id))
    content {
      id = storage_image_reference.value
    }
  }
  network_configuration {
    subnet_id                        = azurerm_subnet.batch_subnet.id
    public_ips                       = []
    public_address_provisioning_type = "NoPublicIPAddresses"
  }

}

**Comment by xiaxyi** [comment]
@Yaron-Hazan Thanks, let me check
