### ISSUE TITLE
Connection of Subscription Activity Log to Log Analytics Workspace via Terraform

### ISSUE THREAD

**Issue by manfred0191** [hashicorp/terraform-provider-azurerm#16707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can anyone tell me if the connection of a subscription alert log to a log analytics workspace in Azure like described here

![image](https://user-images.githubusercontent.com/83340030/167373691-40ee2159-7058-4f1a-9482-29d40b7b99ef.png)

can be coded with Terraform?

https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/activity-log

### New or Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

**Comment by rcskosir** [comment]
Apologizes for the very delayed response. If you still have this question we ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
