### ISSUE TITLE
Terraform suggest to change `default_identity_type` for `azurerm_cosmosdb_account` indefinitely

### ISSUE THREAD

**Issue by ilya-git** [hashicorp/terraform-provider-azurerm#16706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.4.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "example" {
  name                = "example"
  location            = var.location
  resource_group_name = azurerm_resource_group.example.name
  tags                = var.tags.common

  offer_type = "Standard"
  kind       = "GlobalDocumentDB"

  enable_automatic_failover = false
  # default_identity_type     = "FirstPartyIdentity" # I tried to add this, but the change plan still wants to do this all the time

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }

  lifecycle {
    prevent_destroy = true
    ignore_changes = [
#      default_identity_type # I had to add this as a workaround
    ]
  }
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Empty change plan

### Actual Behaviour

      + default_identity_type                 = "FirstPartyIdentity"

### Steps to Reproduce

1. Create a cosmos db as in example above (I did import it from another configuration, but probably should not make a difference)
2. Make plan -> it will try to add `default_identity_type` as in the example above
3. Make apply
4. Make plan -> same as step 2 forever

### References

There is a similar issue closed, but this is happening in the latest 3.x provider still
https://github.com/hashicorp/terraform-provider-azurerm/issues/14630

_No response_

**Comment by JackSinclairT** [comment]
I also get this issue - the state is never updated despite the fact cosmos gets updated

**Comment by neil-yechenwei** [comment]
@ilya-git , thanks for raising this issue. Seems I cannot repro this issue with latest azurerm provider. Could you help double confirm whether the issue still exists?

Repro steps:
1. Create resource with below tfconfig or import the existing resource
2. tf plan
3. there is no difference

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-cosmos-test02"
  location = "eastus"
}

resource "azurerm_cosmosdb_account" "example" {
  name                = "acctest-ca-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  offer_type = "Standard"
  kind       = "GlobalDocumentDB"

  enable_automatic_failover = false

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = azurerm_resource_group.test.location
    failover_priority = 0
  }
}
```

**Comment by abergie** [comment]
I have also experienced this issue, seems that it may only happen when a cosmosdb account was created before `default_identity_type` was added via Azure REST APIs?

**Comment by ilya-git** [comment]
Our account is at least few years old, and I did not try to reproduce this with a new database. What I did is I imported the old cosmos db into terraform and then got this error. I will check if it is still there in the latest terraform/provider

**Comment by JackSinclairT** [comment]
> I have also experienced this issue, seems that it may only happen when a cosmosdb account was created before `default_identity_type` was added via Azure REST APIs?

Yep same here. Happens with our cosmos account we created a year ago.

**Comment by ilya-git** [comment]
I have now tested with latest 1.2.1 terraform and 3.7.0 azurerm, the issue is still here, so it seems likely it affects "older" accounts?

**Comment by neil-yechenwei** [comment]
@ilya-git , seems older account doesn't support default_identity_type and doesn't return it. Could you share the value in your state file (terraform.tfstate) for this property?

**Comment by ilya-git** [comment]
Sorry for the delay, not sure if it is relevant anymore, but the value does not seem to exist in the state
