### ISSUE TITLE
Update azurerm_synapse_spark_pool to support spark_version 3.2 ? 

### ISSUE THREAD

**Issue by TerryRomeu3SR** [hashicorp/terraform-provider-azurerm#16729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Our customers use spark version 3.2 into Azure Synapse, but when i imported it, Terraform do not support this version.

Error : 
![image](https://user-images.githubusercontent.com/70966216/167582685-ce037191-c5ca-4a7e-8f56-cd487033e3fe.png)

When I write 3.1 : 
![image](https://user-images.githubusercontent.com/70966216/167582927-9146fae5-374a-42df-a48f-fb97927f3616.png)

In your Doc : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_spark_pool

![image](https://user-images.githubusercontent.com/70966216/167581488-bf3cb805-5e04-4467-8a6c-bf34677e0e91.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_synapse_spark_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_synapse_spark_pool" "spark_pool_2" {
  name                           = Name
  synapse_workspace_id           = azurerm_synapse_workspace.synapse_workspace.id
  node_size_family               = var.spark_pool_2.node_size_family
  node_size                      = var.spark_pool_2.node_size
  node_count                     = var.spark_pool_2.node_count
  cache_size                     = var.spark_pool_2.cache_size
  spark_version                  = var.spark_pool_2.spark_version
  session_level_packages_enabled = true
.....Etc....
}

# Var
spark_pool_2 = {
  node_size_family = "MemoryOptimized"
  node_size        = "Small"
  cache_size       = 0
  node_count       = 3
  max_node_count   = 50
  min_node_count   = 3
  delay_in_minutes = 30
  spark_version    = "3.2"
}
```

**Comment by jackofallops** [comment]
Closed by #16906, released in v3.8.0 but incorrectly linked.
