### ISSUE TITLE
Can't create storage account - fails with "404 storage account not found" for the very storage account it's trying to create

### ISSUE THREAD

**Issue by tdevopsottawa** [hashicorp/terraform-provider-azurerm#16748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "ecommdna/nonprod/acr/terraform.tfstate"
    resource_group_name  = "ecomm-terraform"
    storage_account_name = "ecommterra672301"
  }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.5.0"
    }
  }
}

provider "azurerm" {
  skip_provider_registration = true
  features {}
}

resource "azurerm_storage_account" "storage_gen2_ecomm_dna" {
  name                     = "ecommdnaeus01"
  resource_group_name      = "ecommtesting-01-rg"
  location                 = "eastus"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = true
  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = ["/subscriptions/ae0c1e4e-d49e-4115-b3ba-888d77ea97a3/resourceGroups/azure-prod/providers/Microsoft.Network/virtualNetworks/azure-prod/subnets/xp","/subscriptions/ae0c1e4e-d49e-4115-b3ba-888d77ea97a3/resourceGroups/azure-prod/providers/Microsoft.Network/virtualNetworks/azure-prod/subnets/gs","/subscriptions/37265438-aa4f-49f6-adc4-46271ae19193/resourceGroups/deployment-infra-rg2/providers/Microsoft.Network/virtualNetworks/deployment-vnet2/subnets/xp","/subscriptions/37265438-aa4f-49f6-adc4-46271ae19193/resourceGroups/deployment-infra-rg2/providers/Microsoft.Network/virtualNetworks/deployment-vnet2/subnets/gs","/subscriptions/63c9e19b-5cf1-4dcf-ace5-bf0f416f2ff7/resourceGroups/deployment-infra-rg3/providers/Microsoft.Network/virtualNetworks/deployment-vnet3/subnets/xp","/subscriptions/63c9e19b-5cf1-4dcf-ace5-bf0f416f2ff7/resourceGroups/deployment-infra-rg3/providers/Microsoft.Network/virtualNetworks/deployment-vnet3/subnets/gs"]
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/tdevopsottawa/76435b6f0eb66adf8e116e208cbbaf4f
```

### Expected Behaviour

Storage account should have been created

### Actual Behaviour

Storage account failed to provision - while creating, it fails with a "404 not found error", saying that the very storage account it's trying to create is "not found", which makes no sense.

azurerm_storage_account.storage_gen2_ecomm_dna: Creating...
azurerm_storage_account.storage_gen2_ecomm_dna: Still creating... [10s elapsed]
azurerm_storage_account.storage_gen2_ecomm_dna: Still creating... [20s elapsed]
╷
│ Error: retrieving Storage Account: (Name "ecommdnaeus01" / Resource Group "ecommtesting-01-rg"): storage.AccountsClient#GetProperties: Failure responding to reques
t: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account ecommdnaeus01 was not
found."
│
│   with azurerm_storage_account.storage_gen2_ecomm_dna,
│   on main.tf line 21, in resource "azurerm_storage_account" "storage_gen2_ecomm_dna":
│   21: resource "azurerm_storage_account" "storage_gen2_ecomm_dna" {

### Steps to Reproduce

terraform apply -auto-approve

### Important Factoids

Behind storage firewall with whitelisting rules for Snowflake storage subnets

### References

https://docs.snowflake.com/en/user-guide/data-load-azure-allow.html

**Comment by bubbletroubles** [comment]
Is the machine you are running Terrform Apply on running one of the subnets in the virtual_network_subnet_ids parameter?

**Comment by tdevopsottawa** [comment]
Yep, that was it.

Shouldn't it have failed with a 403 instead, though?

**Comment by magodo** [comment]
@tdevopsottawa Would you please check that the [`service_endpoints`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#service_endpoints) include the `Microsoft.Storage`?

**Comment by cpressland** [comment]
@magodo - I was having the same issue as @tdevopsottawa and your suggestion for `service_endpoints` on the subnet fixed it. Thank you.
