### ISSUE TITLE
resource "azurerm_role_assignment" : Error while getting storage container id

### ISSUE THREAD

**Issue by aviisingh** [hashicorp/terraform-provider-azurerm#16753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

resource "azurerm_role_assignment"

### Terraform Configuration Files

```hcl
## Blob container for Data Archive
resource "azurerm_storage_container" "datasets" {
  name                  = "my-datasets-archive"
  storage_account_name  = module.storage_account_common.storage_account_object.name
  container_access_type = "private"
}

## role assignments for Azure AD Group ##
resource "azurerm_role_assignment" "rg__dev" {
  scope                = azurerm_storage_container.datasets.id
  role_definition_name = "Contributor"
  principal_id         = data.azuread_group.org_dev.object_id
}
```

### Debug Output/Panic Output

```shell
na
```

### Expected Behaviour

Should add rbac for container for specified AD group.

### Actual Behaviour

Terraform apply fails with below error

Error: The number of path segments is not divisible by 2 in "my-datasets-archive"
│ 
│   with azurerm_role_assignment.rg__dev,
│   on rbac.tf line 35, in resource "azurerm_role_assignment" "rg__dev":
│   35:   scope                = azurerm_storage_container.datasets.id
│ 
╵
╷
│ Error: parsing "[https://storagename.blob.core.windows.net/my-datasets-archive"](https://storagename.blob.core.windows.net/my-datasets-archive%22): parsing segment "providers": expected the segment "https:" to be "providers"
│ 
│   with azurerm_role_assignment.rg__dev,
│   on rbac.tf line 35, in resource "azurerm_role_assignment" "rg__dev":
│   35:   scope                = azurerm_storage_container.datasets.id
│ 
╵
╷
│ Error: parsing "[https://storagename.blob.core.windows.net/my-datasets-archive"](https://storagename.blob.core.windows.net/my-datasets-archive%22): parsing segment "subscriptions": expected the segment "https:" to be "subscriptions"
│ 
│   with azurerm_role_assignment.rg__dev,
│   on rbac.tf line 35, in resource "azurerm_role_assignment" "rg__dev":
│   35:   scope                = azurerm_storage_container.datasets.id
│ 
╵

### Steps to Reproduce

terraform apply

**Comment by magodo** [comment]
@aviisingh In this case, you shall set the `scope` to [`azurerm_storage_container.datasets.resource_manager_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_container#resource_manager_id) instead.

**Comment by aviisingh** [comment]
> @aviisingh In this case, you shall set the `scope` to [`azurerm_storage_container.datasets.resource_manager_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_container#resource_manager_id) instead.

This works. Thanks.
