### ISSUE TITLE
Terraform showing changes in second terraform apply in azurerm_cdn_profile

### ISSUE THREAD

**Issue by ccsandhanshive** [hashicorp/terraform-provider-azurerm#16759]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_profile

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_profile" "this" {
  location            = "global"
  resource_group_name = "Group"
  name                = "example01"
  sku                 = "Standard_Akamai"
}
```

### Debug Output/Panic Output

```shell
$ terragrunt apply
azurerm_cdn_profile.this["example01"]: Refreshing state... [id=/subscriptions/*****************/resourceGroups/Group/providers/Microsoft.Cdn/profiles/example01]
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply":

  # azurerm_cdn_profile.this["example01"] has been changed
  ~ resource "azurerm_cdn_profile" "this" {
        id                  = "/subscriptions/***************/resourceGroups/************/providers/Microsoft.Cdn/profiles/example01"
        name                = "example01"
      + tags                = {}
        # (3 unchanged attributes hidden)
    }
  
Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.

─────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like
to update the Terraform state to match, create and apply a refresh-only plan:
  terraform apply -refresh-only

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behaviour

If we do not specify tags. Terraform second apply should not show any changes if there is no changes in infrastructure 

### Actual Behaviour

If we do not specify tags. Terraform second apply shows changes in second terraform apply but it also shows that No changes. Your infrastructure matches the configuration.

### Steps to Reproduce

1. terraform apply
2. terraform apply

**Comment by magodo** [comment]
@ccsandhanshive This bug is being tracked in #15387 which I'm going to close this in favour of - would you mind subscribing to that issue for updates?

Thanks!
