### ISSUE TITLE
SecurityRuleInvalidAddressPrefix Invalid Address Prefix

### ISSUE THREAD

**Issue by iddqdiddqd** [hashicorp/terraform-provider-azurerm#16761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.1.9

### AzureRM Provider Version

v3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "ml" {
  name                                             = "ML-SA-acceptance-SG"
  location                                         = var.project["location"]
  resource_group_name                              = data.azurerm_resource_group.default.name
}

resource "azurerm_network_security_rule" "outbound_keyvault_region" {
  name                                             = "outbound-Keyvault.region"
  direction                                        = "Outbound"
  source_address_prefix                            = "*"
  source_port_range                                = "*"
  destination_address_prefix                       = "Keyvault.centralus"
  destination_port_range                           = "443"
  protocol                                         = "Tcp"
  access                                           = "Allow"

  priority                                         = 300

  resource_group_name                              = data.azurerm_resource_group.default.name
  network_security_group_name                      = azurerm_network_security_group.ml.name

  depends_on                                     = [
    azurerm_network_security_group.ml
  ]
}
```

### Debug Output/Panic Output

```shell
Error: creating/updating Security Rule: (Name "outbound-Keyvault.region" / Network Security Group Name "ML-SA-acceptance-SG" / Resource Group "Iqvia-ResourceGroup"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SecurityRuleInvalidAddressPrefix" Message="Security rule /subscriptions/03ff4509-6d9d-47e0-a8c2-13697cc2d62c/resourceGroups/Iqvia-ResourceGroup/providers/Microsoft.Network/networkSecurityGroups/ML-SA-acceptance-SG/securityRules/outbound-Keyvault.region has invalid Address prefix. Value provided: Keyvault.Centralus" Details=[]
│ 
│   with azurerm_network_security_rule.outbound_keyvault_region,
│   on virtual_network.tf line 337, in resource "azurerm_network_security_rule" "outbound_keyvault_region":
│  337: resource "azurerm_network_security_rule" "outbound_keyvault_region" {
```

### Expected Behaviour

The network security rule should have been created successfully for Key Vault in the Central US region.

### Actual Behaviour

Terraform fails with the 'SecurityRuleInvalidAddressPrefix' error.

### Steps to Reproduce

1. `terraform init`
1. `terraform apply -auto-approve`

### Important Factoids

Running Terraform locally with terraform.tfvars

**Comment by sinbai** [comment]
@iddqdiddqd thank you for opening this issue here. Could you use `AzureKeyVault.Centralus` instead of `Keyvault.centralus`?

**Comment by iddqdiddqd** [comment]
@sinbai thank you! The issue is resolved with your suggestion. We can consider this case as closed.
