### ISSUE TITLE
Service plan change fails

### ISSUE THREAD

**Issue by taipignas** [hashicorp/terraform-provider-azurerm#16785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "example" {
  name                = "service-plan"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  os_type             = "Linux"
  sku_name            = "Y1"

  tags = {}
}

resource "azurerm_windows_function_app" "example" {
  name                       = "function-app"
  resource_group_name        = azurerm_resource_group.resource_group.name
  location                   = azurerm_resource_group.resource_group.location
  service_plan_id            = azurerm_service_plan.service_plan.id

  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key
  site_config {}

  tags = {}
}
```

### Debug Output/Panic Output

```shell
Error: deleting Service Plan: (Serverfarm Name "service-plan" / Resource Group "resource-group"): web.AppServicePlansClient#Delete: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>


azurerm_service_plan.example must be replaced
azurerm_windows_function_app.examplewill be updated in-place
```

### Expected Behaviour

service plan should be deleted and then recreated

### Actual Behaviour

service plan cannot be deleted and recreated

### Steps to Reproduce

1. create service plan (Windows, Y1) with function app
2. change plan to (Linux, Y1)

I think the issue is that it tries to replace service plan without replacing function app

**Comment by jackofallops** [comment]
Hi @taipignas - The configuration change you're trying to make there cannot work I'm afraid. Changing the `azurerm_service_plan` to a Linux `os_type`, without updating your config to use a `azurerm_linux_function_app` in place of the `azurerm_windows_function_app` in your config is not supported as Terraform cannot redefine resources on your behalf.

The `Status=<nil> <nil>` error is an underlying Autorest problem, currently being tracked [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/10858), please follow there for updates on that issue.

Given the above, I'm going to close out this issue for now.
