### ISSUE TITLE
[azurerm_linux_function_app] Documentation: [force_disable_content_share] attribute should match windows attribute [content_share_force_disabled]

### ISSUE THREAD

**Issue by mkprizzle** [hashicorp/terraform-provider-azurerm#16789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.x

### AzureRM Provider Version

3.x

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
NA
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

Documentation suggests using [force_disable_content_share](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app#force_disable_content_share)

### Actual Behaviour

TF expects content_share_force_disable

**Comment by sinbai** [comment]
@mkprizzle thank you for opening this issue. The documentation has been fixed by PR #16796.

**Comment by jackofallops** [comment]
Closed by 16796.
