### ISSUE TITLE
Failure to add/change tags on imported `azurerm_shared_image` (Error: `Changing property 'galleryImage.properties.eula' is not allowed.`)

### ISSUE THREAD

**Issue by dduportal** [hashicorp/terraform-provider-azurerm#16792]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_shared_image

### Terraform Configuration Files

```hcl
https://github.com/jenkins-infra/azure/blob/7311f8f8674089cc5d52b03d0f97693d224bcdd5/packer-resources.tf#L25-L58
```

### Debug Output/Panic Output

```shell
https://gist.github.com/dduportal/6a5f20977e272f15c85e1ed75ce6c50f
```

### Expected Behaviour

Part of the described resource were pre-existing and had been imported through `terraform import` commands, while other are expected to be created (switch from manual management to terraform management).

We expect all the resource to be update or created without any error.

### Actual Behaviour

- All the created resources behave as expected
- All the imported resources fails when the `tags` are updated/created with an error related to the existing `eula` properties unable to be changed.
- We do NOT specify any [`eula`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/shared_image#eula) attributes: neither on the Azure side neither on the terraform management
- Removing the `tags` atrribute does not trigger the error (this is what we are doing: no tag applied and it's fine)

### Steps to Reproduce

- Create a shared image gallery in Azure WebUI and create an image 
- Import both on a terraform project
- Add a tag to the imported image: it fails.

### References

- https://github.com/jenkins-infra/azure/pull/189
- https://github.com/jenkins-infra/azure/pull/190

**Comment by serhiichernukha** [comment]
Faced the same issue. Is there any update on this?
