### ISSUE TITLE
Error setting Sign Up settings for Api Management: "Representation was empty."

### ISSUE THREAD

**Issue by alexwieseawe** [hashicorp/terraform-provider-azurerm#16797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.4

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"
}
```

### Debug Output/Panic Output

```shell
│ Error:  setting Sign Up settings for Api Management: (Service Name "12558544-01" / Resource Group "b51920e4-ec2a-4cd1-a0e8-04227876a28d"): apimanagement.SignUpSettingsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="Representation was empty."
│ 
│   with module.apim-ptn.module.apim.azurerm_api_management.apim,
│   on .terraform/modules/apim-ptn.apim/main.tf line 2, in resource "azurerm_api_management" "apim":
│    2: resource "azurerm_api_management" "apim" {
│ 
╵
```

### Expected Behaviour

Deployment succeeds without error

### Actual Behaviour

In v3.6.0 the Error Service returned an error. Status=400 Code="ValidationError" Message="Representation was empty." is returned

### Steps to Reproduce

1. terraform init
1. terraform apply

**Comment by alexwieseawe** [comment]
Issue disappeared after running terraform apply again. 
It appears to be a timing issue.

**Comment by mybayern1974** [comment]
@alexwieseawe thank you for opening this issue. Would you be ok if we close this issue by noticing you mentioned there are no more blockings?
