### ISSUE TITLE
`azurerm_application_gateway` documentation doesn't reflect mandatory arguments

### ISSUE THREAD

**Issue by bubbletroubles** [hashicorp/terraform-provider-azurerm#16793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.x

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

The documentation for `azurerm_application_gateway` states that the `priority` within the `request_routing_rule` block is optional.

It is now mandatory as of API 2021-08-01.

### Actual Behaviour

When no priority is set, the error below happens

`│ Error: creating Application Gateway: (Name "app-gw" / Resource Group "example"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty" Message="Priority for the request routing rule /subscriptions/xxxxx/resourceGroups/app-gw/providers/Microsoft.Network/applicationGateways/app-gw/requestRoutingRules/routing-rule cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01" Details=[]`

### Important Factoids

The Application Gateway API version was changed as below. This issue was introduced with the newer api version.

	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-05-01/network"  - AzureRM 3.5.0
	"github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-08-01/network"  - AzureRM 3.6.0

**Comment by adamfd** [comment]
Same issue.  Using a dynamic block of routing rules, applying fine in 3.5, but failing in 3.6 for the same error with the updated API version.
In 3.5, it seems all the rules have a priority, but looks to be assigned by Azure in the order they are created 10/20/30 etc.  That does not seem to be the case in 3.6, where it must be specified.

**Comment by bubbletroubles** [comment]
> I am trying to run terraform script for Application gateway. There are no changes in my code and pipelines. I am getting these error messages: ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty All request routing rules should have a priority defined starting from api-version 2021-08-01

You will need to pin to the provider to azurerm 3.5.0 or earlier. From 3.6.0 onwards the priority is needed.

**Comment by anishtechnet** [comment]
I added priority on request_routing_rule and resolved the issue. Thank you all.

**Comment by karishma-kohli** [comment]
Facing the same issue since yesterday, if they keep rolling out breaking changes like this, it's going to be hard to manage the modules. I fixed 5 modules in my org recently to make them 3.x.x compatible.

**Comment by SudhirG85** [comment]
> I added priority on request_routing_rule and resolved the issue. Thank you all.

Could you please share the entry/value you provided for "priority" in request_routing_rule, because we too have one app gateway created by terraform for multiple domains.

**Comment by Nicolas92300** [comment]
you need add priority in request_routing_rule, for exemple : 

  request_routing_rule {
    name                       = var.rule_name
    rule_type                  = "Basic"
    http_listener_name         = var.listener_name
    backend_address_pool_name  = var.bp_name
    backend_http_settings_name = var.http_setting_name
    **priority = 10**
  }
  request_routing_rule {
    name                       = var.rule_name2
    rule_type                  = "Basic"
    http_listener_name         = var.listener_name2
    backend_address_pool_name  = var.bp_name2
    backend_http_settings_name = var.http_setting_name2
    **priority = 20**
  }

**Comment by bubbletroubles** [comment]
> > I added priority on request_routing_rule and resolved the issue. Thank you all.
> 
> Could you please share the entry/value you provided for "priority" in request_routing_rule, because we too have one app gateway created by terraform for multiple domains.

I've submitted a pull request to include priority in the example code which should help clarify in future too - 
#17079
#16849
