### ISSUE TITLE
Kind should be allow for creation of webAPP/API

### ISSUE THREAD

**Issue by manikanta469** [hashicorp/terraform-provider-azurerm#16809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

the kind option should be allowed to be chosen whether it's a web app or API. when creating the web app.
getting below error when we use kind attribute
│  101: kind = "api"
│
│ Can't configure a value for "kind": its value will be decided automatically based on the result of applying this configuration.

### Description

the kind option should be allowed to be chosen whether it's a web app or API. when creating the web app.
getting below error when we use kind attribute
│  101: kind = "api"
│
│ Can't configure a value for "kind": its value will be decided automatically based on the result of applying this configuration.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_web_app" "identity" {
name = "identity"
resource_group_name = azurerm_resource_group.Enh-AppServices-High-RG.name
location = azurerm_resource_group.Enh-AppServices-High-RG.location
service_plan_id = azurerm_service_plan.Enh-ASP-High.id
https_only = true
kind = "api"
site_config {
  use_32_bit_worker = true
  always_on = true
  ftps_state = "FtpsOnly"
  application_stack {
    current_stack = "dotnet"
    dotnet_version = "v4.0"
  }
  cors {
    allowed_origins = [ "*" ]
  }
  }
  app_settings = {
    "Office365.clientID" = "123456"
    "Azure.set"= "12345"
    "APPINSIGHTS_INSTRUMENTATIONKEY"= azurerm_application_insights.identity.instrumentation_key
    "APPLICATIONINSIGHTS_CONNECTION_STRING"= azurerm_application_insights.identity.connection_string
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @manikanta469 

The new resources intentionally take a different approach to the older App Service resources - as such they're more opinionated to better match the API. When we've previously investigated this for the older resources [we've learnt that there's no difference between the two](https://github.com/hashicorp/terraform-provider-azurerm/issues/443#issuecomment-900981696) and the Service Team now recommend not specifying the `kind` field here - as such the new resources don't support this field.

As the Service Team are recommending not setting this field (and instead having the API determine the correct value for it) - unfortunately this isn't something we're planning to add at this time and as such whilst I'd like to thank you for opening this issue I'm going to close this feature request for the moment.

Thanks!
