### ISSUE TITLE
Support for postgresql_flexible_server create_mode GeoRestore

### ISSUE THREAD

**Issue by jeffmccollum** [hashicorp/terraform-provider-azurerm#16811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [postgresql_flexible_server resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server) does not support the `create_mode` of `GeoRestore`. 

Setting a postgresql_flexible_server to `geo_redundant_backup_enabled` is supported in the provider today, restoring a geo redundant backup is possible in the Azure portal, and the [mysql_flexible_server](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#create_mode) resource supports `GeoRestore` as well. 

### New or Affected Resource(s)/Data Source(s)

resource & data azurerm_postgresql_flexible_server

**Comment by sinbai** [comment]
@jeffmccollum  thank you for opening this issue here. Unfortunately, since the latest version of the [Azure API](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/postgresql.json#L1479) does not support the create_mode of  `GeoRestore`, the terraform provider could not currently supported it as it does by calling the Azure API.

**Comment by SebTardif** [comment]
Since this depend of an improvement on the Azure API, I created that issue on it -> https://github.com/Azure/azure-rest-api-specs/issues/21438

**Comment by SebTardif** [comment]
@sinbai What's the workaround? Is this mean it's also not possible to do this using the az cli?

**Comment by SebTardif** [comment]
Looks like the API now exist, see https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/preview/2022-03-08-preview/FlexibleServers.json

**Comment by sandy-wang** [comment]
Any update on this request? It will be really useful if we could use IaC to do geo-restore during a DR incident.

**Comment by tech7857** [comment]
Hi

Can this be prioritized? This is a very important feature needed for DR

Thank you

**Comment by aletournel** [comment]
Hello everybody, same here. This feature would be useful in our case to avoid bash scripting on top of terraform when starting the DR. But in any case. Thanks for all your good work :)

**Comment by prashantagavane** [comment]
me too

**Comment by prashantagavane** [comment]
i would be interested to find a workaround , since even today create_mode doesn't support "GeoResore" option in TF

**Comment by sinbai** [comment]
Hi @jeffmccollum [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/25664)has been submitted to support GeoRestore, could you please track it for more updates?
