### ISSUE TITLE
azurerm_network_watcher_flow_log recreated if location is not set

### ISSUE THREAD

**Issue by Wiston999** [hashicorp/terraform-provider-azurerm#16823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_network_watcher_flow_log

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "resourcegroup" {
  name     = "test-resource-group"
  location = "westeurope"
}

resource "azurerm_network_security_group" "nsg" {
  name                = "test-network-security-group"
  location            = "westeurope"
  resource_group_name = "test-resource-group"
}

resource "azurerm_storage_account" "nw_storage_account" {
  name                            = "testnwsa"
  location                        = "westeurope"
  resource_group_name             = "test-resource-group"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  min_tls_version                 = "TLS1_2"
  enable_https_traffic_only       = true
  allow_nested_items_to_be_public = false
}

resource "azurerm_network_watcher_flow_log" "nwfl" {
  network_watcher_name = "NetworkWatcher_westeurope"
  resource_group_name  = "NetworkWatcherRG"
  name                 = "test-network-watcher-flow-log"

  network_security_group_id = azurerm_network_security_group.nsg.id
  storage_account_id        = azurerm_storage_account.nw_storage_account.id
  enabled                   = true

  retention_policy {
    enabled = true
    days    = 91
  }
}
```

### Debug Output/Panic Output

```shell
Unavailable
```

### Expected Behaviour

The resource shouldn't be recreated on every iteration of `terraform apply` if the configuration of the resource doesn't change.

### Actual Behaviour

The resource is being recreated on every iteration of `terraform apply` with plan output:
```
# module.pdns.azurerm_network_watcher_flow_log.nwfl[0] must be replaced
-/+ resource "azurerm_network_watcher_flow_log" "nwfl" {
      ~ id                        = "[REDACTED]" -> (known after apply)
      - location                  = "westeurope" -> null # forces replacement
        name                      = "pdns-westeurope-network-watcher-flow-log"
      - tags                      = {} -> null
      ~ version                   = 1 -> (known after apply)
        # (5 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @Wiston999 

Thanks for opening this issue.

This can be fixed by specifying the `location` property since it's required for new Network Flow Log Watchers, but isn't for older resources. This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
