### ISSUE TITLE
`azurerm_linux_web_app`'s `site_config`'s `always_on` is set to True by default contradicting with the documentation

### ISSUE THREAD

**Issue by adamency** [hashicorp/terraform-provider-azurerm#16830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.3

### AzureRM Provider Version

3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
data "azurerm_service_plan" "<my_service_plan>" {
  name                = "<my_service_plan>"
  resource_group_name = data.azurerm_resource_group.<my_resource_group>.name
}

resource "azurerm_linux_web_app" "<my_appservice>" {
  name                = "<my_appservice>"
  resource_group_name = data.azurerm_resource_group.<my_resource_group>.name
  location            = data.azurerm_resource_group.<my_resource_group>.location
  service_plan_id     = data.azurerm_service_plan.<my_service_plan>.id

  site_config {
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/adamency/386e38a35ed09b8a22aa817fe3f13fa0
```

### Expected Behaviour

```
+ site_config {
          + always_on                               = false
```

According to the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#always_on)

### Actual Behaviour

```
+ site_config {
          + always_on                               = true
```

### Steps to Reproduce

`terraform plan`

**Comment by xiaxyi** [comment]
Hi @adamency, thanks for this, may I know if you are having any deployment issue or just simply point this diff out?

**Comment by adamency** [comment]
Yes I don't have any issue with deployment of the appservice. I was indeed just pointing out the discrepancy between the docs and the actual implementation.

By the way since I'm here, I've also noticed an issue in the `scm_ip_restriction` block where the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#virtual_network_subnet_id) states that:

```
One and only one of ip_address, service_tag or virtual_network_subnet_id must be specified.
```

but when you actually run a `plan` on a configuration with for instance `virtual_network_subnet_id`  specified, the plan fails and claims that all three of those attributes are "required" (it even says that `headers` is required to whereas it is marked as optional in the documentation)

**Comment by xiaxyi** [comment]
@adamency Thanks for the feedbacks, let me check the code.

**Comment by xiaxyi** [comment]
@adamency I didn't have this error by running below TF confirm:
```
 site_config {
    ip_restriction {
      ip_address = "10.10.10.10/32"
      name       = "test-restriction"
      priority   = 123
      action     = "Allow"
      headers {
        x_azure_fdid      = ["55ce4ed1-4b06-4bf1-b40e-4638452104da"]
        x_fd_health_probe = ["1"]
        x_forwarded_for   = ["9.9.9.9/32", "2002::1234:abcd:ffff:c0a8:101/64"]
        x_forwarded_host  = ["example.com"]
      }
    }
  }
```

can you share the full config and paste the error message as well?

**Comment by rcskosir** [comment]
@adamency Thank you for taking the time to open this issue. Thank you @xiaxyi and @geralexgr for the PRs to update the documentation. Since #16879 and #17051 are both merged I am going to mark this issue as closed.
