### ISSUE TITLE
azurerm_windows_virtual_machine and timezone

### ISSUE THREAD

**Issue by L-u-k-e-GIT** [hashicorp/terraform-provider-azurerm#16848]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.7

### AzureRM Provider Version

v3.3.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

### Terraform Configuration Files

```hcl
Hi I add timezone to an existing tf project.
During the plan terraform recognize the resource change but actually does not change the time zone inside a server.

Running following terraform plan it always try to reapply it.
```

### Debug Output/Panic Output

```shell
no specif error
```

### Expected Behaviour

The timezone of the vm is changed.

### Actual Behaviour

The time zone is not changed (if the vm already exits)

### Steps to Reproduce

Resource "azurerm_windows_virtual_machine" "vm" {
 
  for_each            = var.VM_DEF
  name                = "${var.VM_NAME_PREFIX}${var.PROJECT_NAME}-${each.value.name}-${var.VM_ENV}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = var.LOCATION
  license_type        = var.WINDOWS_LICENSE_TYPE
  size                = each.value.size
  admin_username      = var.ADMIN_USERNAME 
  admin_password      = var.ADMIN_PASSWORD
  **timezone            = "W. Europe Standard Time"**
  boot_diagnostics {
      storage_account_uri = module.vm_ext_storage.MD_OUT_ST_URI
      } 
  network_interface_ids = [
    azurerm_network_interface.vm_nic1[each.key].id,
  ]

  os_disk {
    name                 =  "${var.DISKOS_PREFIX}-${var.PROJECT_NAME}-${var.SUBSCRIPTION_PREFIX}-${var.REGION_PREFIX}-${each.value.name}"
    caching              = "ReadWrite"
    disk_size_gb         = each.value.diskosize
    storage_account_type = each.value.disk
    
  }

**Comment by myc2h6o** [comment]
Hi @L-u-k-e-GIT `timezone` cannot be changed, and there seems to be a bug in the provider where `ForceNew` flag is missed, I've created a pr to fix it
