### ISSUE TITLE
ingress_application_gateway_identity should be assigned to existing UserAssignedManagedIdentity within azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by bulentozkir** [hashicorp/terraform-provider-azurerm#16854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster 

**azurerm_kubernetes_cluster** AKS namespace allows AKS Cluster Identity and Kubelet Identity blocks to be assigned to existing UserAssignedManaged identity. However, **ingress_application_gateway_identity** is only exportable. Therefore, Ingress Controller managed identity is created dynamically. It would be good to improve ingress_application_gateway_identity block to use existing UserAssignedManagedIdentity so code will be leaner and there won't be dynamically created additional managed identity for ingress controller. 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "example-aks1"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix          = "exampleaks1"

  linux_profile {
    admin_username = "azureuser"

    ssh_key {
      key_data = tls_private_key.example_ssh.public_key_openssh
    }
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [data.azurerm_user_assigned_identity.example.id]
  }

  kubelet_identity {
    user_assigned_identity_id = data.azurerm_user_assigned_identity.example.id
    client_id                 = data.azurerm_user_assigned_identity.example.client_id
    object_id                 = data.azurerm_user_assigned_identity.example.principal_id
  }

.......
.......
.......
```

**Comment by stephybun** [comment]
Thanks for raising this issue @bulentozkir.

I believe we already have an issue open for this. So that we don't have multiple issues tracking the same request I'm going to close this one in favour of #11753. Please subscribe to #11753 for updates.

Thanks!
