### ISSUE TITLE
Eventhub Namespaces fails updating the maximum_throughput_units

### ISSUE THREAD

**Issue by blame19** [hashicorp/terraform-provider-azurerm#16850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### AzureRM Provider Version

Tested both with 

2.99.0

and 3.6.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_namespace

### Terraform Configuration Files

```hcl
"azurerm_eventhub_cluster" "eventhub" {
  count               = var.eventhub_cluster_name == null ? 0 : 1
  name                = var.eventhub_cluster_name
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name
  sku_name            = var.eventhub_cluster_sku_name
}

resource "azurerm_eventhub_namespace" "eventhub" {
  for_each            = var.eh_namespaces
  name                = each.key
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name

  sku                      = coalesce(each.value.sku, "Standard")
  capacity                 = coalesce(each.value.capacity, 1)
  auto_inflate_enabled     = coalesce(each.value.auto_inflate_enabled, false)
  maximum_throughput_units = coalesce(each.value.auto_inflate_enabled, false) == true ? coalesce(each.value.maximum_throughput_units, 1) : null
  zone_redundant           = coalesce(each.value.zone_redundant, false)
  dedicated_cluster_id     = join("", azurerm_eventhub_cluster.eventhub[*].id) != "" ? azurerm_eventhub_cluster.eventhub[0].id : null

  network_rulesets {
    default_action = coalesce(each.value.network_rule_default_action, "Deny")

    virtual_network_rule = [
      for rule in coalesce(each.value.virtual_network_rules, []) : {
        subnet_id                                       = rule.subnet_id
        ignore_missing_virtual_network_service_endpoint = rule.ignore_missing_virtual_network_service_endpoint
      }
    ]

    ip_rule = [
      for rule in coalesce(each.value.ip_rules, []) : {
        ip_mask = rule.ip_mask
        action  = "Allow"
      }
    ]
  }

  tags = {
    environment = each.value.environment
  }

  lifecycle {
    ignore_changes = [
      # Ignore hardcoded capacity, since auto_inflate_enabled could be enabled
      # NOTE: This cannot be dynamically added, as there is no support for interpolation yet
      # See https://github.com/hashicorp/terraform/issues/3116
      capacity,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
First plan when creating the namespace:

terraform plan -out=tfplan -input=false -var='eventhub_configs={}'  -var='eventhub_cluster_name=eh2'  -var='resource_group_name=testehrg2'  -var='eventhub_cluster_sku_name=Dedicated_1'  -var='eh_namespaces={ nstest301 = { sku = "Standard", capacity = 1,   auto_inflate_enabled = false, maximum_throughput_units = 1, zone_redundant = false }}'  -var='eh_namespace_auth_rules={}'  -var='create_resource_group=true'  -var='eventhub_authorization_rules={}'  -var='location=eastus'  -var='azure_service_principal=[azure_service_principal]'  
...
INFO   2022-05-11 13:03:27      # module.eh.azurerm_eventhub_namespace.eventhub["nstest301"] will be created
INFO   2022-05-11 13:03:27      + resource "azurerm_eventhub_namespace" "eventhub" {
INFO   2022-05-11 13:03:27          + auto_inflate_enabled                      = false
INFO   2022-05-11 13:03:27          + capacity                                  = 1
INFO   2022-05-11 13:03:27          + dedicated_cluster_id                      = (known after apply)
INFO   2022-05-11 13:03:27          + default_primary_connection_string         = (sensitive value)
INFO   2022-05-11 13:03:27          + default_primary_connection_string_alias   = (sensitive value)
INFO   2022-05-11 13:03:27          + default_primary_key                       = (sensitive value)
INFO   2022-05-11 13:03:27          + default_secondary_connection_string       = (sensitive value)
INFO   2022-05-11 13:03:27          + default_secondary_connection_string_alias = (sensitive value)
INFO   2022-05-11 13:03:27          + default_secondary_key                     = (sensitive value)
INFO   2022-05-11 13:03:27          + id                                        = (known after apply)
INFO   2022-05-11 13:03:27          + location                                  = "eastus"
INFO   2022-05-11 13:03:27          + maximum_throughput_units                  = (known after apply)
INFO   2022-05-11 13:03:27          + name                                      = "nstest301"
INFO   2022-05-11 13:03:27          + network_rulesets                          = [
INFO   2022-05-11 13:03:27              + {
INFO   2022-05-11 13:03:27                  + default_action                 = "Deny"
INFO   2022-05-11 13:03:27                  + ip_rule                        = []
INFO   2022-05-11 13:03:27                  + trusted_service_access_enabled = null
INFO   2022-05-11 13:03:27                  + virtual_network_rule           = []
INFO   2022-05-11 13:03:27                },
INFO   2022-05-11 13:03:27            ]
INFO   2022-05-11 13:03:27          + resource_group_name                       = "testehrg2"
INFO   2022-05-11 13:03:27          + sku                                       = "Standard"
INFO   2022-05-11 13:03:27          + zone_redundant                            = false
INFO   2022-05-11 13:03:27        }```

Subsequent plans show no changes even when we try to update capacity or thorughput_units:

```
terraform plan -out=tfplan -input=false  -var='eventhub_configs={}'  -var='eventhub_cluster_name=eh2'  -var='resource_group_name=testehrg2'  -var='eventhub_cluster_sku_name=Dedicated_1'  -var='eh_namespaces={ nstest301 = { sku = "Standard", capacity = 1,   auto_inflate_enabled = false, maximum_throughput_units = 40, zone_redundant = false }}'  -var='eh_namespace_auth_rules={}'  -var='create_resource_group=true'  -var='eventhub_authorization_rules={}'  -var='location=eastus'  -var='azure_service_principal=[azure_service_principal]'  
...
INFO   2022-05-11 15:03:37    
INFO   2022-05-11 15:03:37    No changes. Your infrastructure matches the configuration.
```
```

### Expected Behaviour

The namespace should have been updated with the new settings. We were able to change manually through Azure portal.

### Actual Behaviour

Nothing, terraform didn't detect the changes.

### Steps to Reproduce

1. Deploy an eventhub namespace with capacity = 1 and maximum_throughput_units = 1
2. wait for apply completion
3. Modifiy the resource (eg. capacity = 2, maximum_throughput_units = 20)
4. Terraform plan shows no changes

**Comment by xiaxyi** [comment]
@blame19 I can change the value for the property `maximum_throughput_units`
```
  # azurerm_eventhub_namespace.test will be updated in-place
  ~ resource "azurerm_eventhub_namespace" "test" {
        id                                  = "/subscriptions/xxx/resourceGroups/xiaxintestRG-eh/providers/Microsoft.EventHub/namespaces/xiaxintestehn"
      ~ maximum_throughput_units            = 25 -> 30
        name                                = "xiaxintestehn"
        tags                                = {}
        # (11 unchanged attributes hidden)
```

I noticed that you are using variable to set the property, can you try explicitly specifying a value and see if the change can be detected?

**Comment by blame19** [comment]
> @blame19 I can change the value for the property `maximum_throughput_units`
> 
> ```
>   # azurerm_eventhub_namespace.test will be updated in-place
>   ~ resource "azurerm_eventhub_namespace" "test" {
>         id                                  = "/subscriptions/xxx/resourceGroups/xiaxintestRG-eh/providers/Microsoft.EventHub/namespaces/xiaxintestehn"
>       ~ maximum_throughput_units            = 25 -> 30
>         name                                = "xiaxintestehn"
>         tags                                = {}
>         # (11 unchanged attributes hidden)
> ```
> 
> I noticed that you are using variable to set the property, can you try explicitly specifying a value and see if the change can be detected?

Thanks for the answer @xiaxyi 
I did check at our code and we're running an if condition I didn't recall:
```
resource "azurerm_eventhub_namespace" "eventhub" {
  for_each            = var.eh_namespaces
  name                = each.key
  location            = var.resource_group.location
  resource_group_name = var.resource_group.name

  sku                      = coalesce(each.value.sku, "Standard")
  capacity                 = coalesce(each.value.capacity, 1)
  auto_inflate_enabled     = coalesce(each.value.auto_inflate_enabled, false)
  maximum_throughput_units = coalesce(each.value.auto_inflate_enabled, false) == true ? coalesce(each.value.maximum_throughput_units, 1) : null
```

By setting auto_inflate_enabled=true, the change to maximum_throughput_units was propagated. So it was on our side

However, I have some questions:

- Do we need to have auto_inflate_enabled=true to set maximum_throughput_units ? The provider's doc seems to imply so.
- Could you check the same goes for capacity? That's the other issue we see on our side.
I will check the behaviour on the capacity parameter on my side as well.

**Comment by aristosvo** [comment]
@blame19 Hope this provided you a solution! Is your question completely answered?

I'll close this issue for now, and reopen it if there is anything left.
