### ISSUE TITLE
Connection string in azurerm_app_service always detected as changed when it has not

### ISSUE THREAD

**Issue by lotaezhao** [hashicorp/terraform-provider-azurerm#16857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_secret" "db_password" {
  name         = "db-password"
  key_vault_id = var.keyvault_id
}

data "azurerm_key_vault_secret" "connection_string" {
  name         = "db-connection-string"
  key_vault_id = var.keyvault_id
}

resource "azurerm_app_service_plan" "deathstar_asp" {
  name                = "deathstar-asp"
  location            = var.location
  resource_group_name = var.rgname
  tags                = var.tags
  kind                = var.app_service_plan.kind
  reserved            = var.app_service_plan.reserved

  sku {
    tier = var.sku.tier
    size = var.sku.size
  }
}

resource "azurerm_app_service" "deathstar_app" {
  name                = "deatstar-app-as"
  location            = var.location
  resource_group_name = var.rgname
  tags                = var.tags
  app_service_plan_id = azurerm_app_service_plan.deathstar_asp.id
  
  app_settings = {
    "DATABASE_HOST"     = var.database_host
    "DATABASE_NAME"     = var.database_name
    "DATABASE_USER"     = var.database_user
    "DATABASE_PASSWORD" = data.azurerm_key_vault_secret.db_password.value
  }

  connection_string {
    name  = "Database"
    type  = "MySQL"
    value = data.azurerm_key_vault_secret.connection_string.value
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

No change should be detected in the plan as the connection string has not changed.

### Actual Behaviour

Subsequent plans show that the connection string has changed (even though it hasn't) and is a sensitive value. The database password (app setting) value is being created in exactly the same way using the keyvault secret value and this is not detected as a change. I think this proves there is something odd about the way the connection string attribute for app service is treated that is causing terraform/azurerm provider to detect a change when none has occurred.

```
  # azurerm_app_service.deathstar_app will be updated in-place
  ~ resource "azurerm_app_service" "deathstar_app" {
        id                                = "/subscriptions/xxxxx/resourceGroups/rg-deathstar/providers/Microsoft.Web/sites/deathstar-app-as"
        name                              = "deathstar-app-as"
        tags                              = {
            "Business Owner" = "Emperor Palpatine"
            "Environment"    = "Galactic Empire"
        }
        # (17 unchanged attributes hidden)

      ~ connection_string {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }

        # (6 unchanged blocks hidden)
    }
```

### Steps to Reproduce

Deploy an azure_app_service configured with a connection_string block.

### Important Factoids

My actual configuration is deploying the app service within a module. As I've said though, I'm passing the database password in exactly the same way to an app setting value and this isn't being detected as a change. So I don't think using a module has anything to do with  it.

**Comment by xiaxyi** [comment]
@lotaezhao I didn't get any plan diff during my second plan, the api is returning MySQL, may I know if you are still seeing this issue by creating a new app service now? I suspect the issue may due to the old state file, maybe the service did return the value  MySql previously, but I need to double confrim.

**Comment by xiaxyi** [comment]
@lotaezhao Good day! May I know if you tried the latest azurerm provider and are you still facing this issue? feel free to let me know if you have any question. Thanks

**Comment by rcskosir** [comment]
Thank you for opening this issue. Since case suppression was aded in v3.0 of the provider and time has passed, I am going to close this issue. If you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose).
