### ISSUE TITLE
data_factory_trigger_schedule needs to support TimeZone

### ISSUE THREAD

**Issue by skoya** [hashicorp/terraform-provider-azurerm#16883]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

as per the title. Timezone isn't available in data_factory_trigger_schedule

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

so that a trigger can be configured with a timezone please can this be supported as a field?

### New or Affected Resource(s)/Data Source(s)

data_factory_trigger_schedule

**Comment by jackofallops** [comment]
Closed by #16918
