### ISSUE TITLE
azurerm_cosmosdb_sql_container throughput changes keep popping up in terraform plan/apply

### ISSUE THREAD

**Issue by vkamlesh** [hashicorp/terraform-provider-azurerm#16892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

2.98.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_sql_container

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_sql_container" "platform-api" {
  name                = "platform-api"
  resource_group_name = azurerm_cosmosdb_account.cosmos-sql-db.resource_group_name
  account_name        = azurerm_cosmosdb_account.cosmos-sql-db.name
  database_name       = azurerm_cosmosdb_sql_database.platform-api.name

  partition_key_path = "/PartitionKey"
  default_ttl = -1 
  autoscale_settings {
    max_throughput = 4000 
  }
}
```

### Debug Output/Panic Output

```shell
Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # module.middleware-environment.azurerm_cosmosdb_sql_container.platform-api has changed
  ~ resource "azurerm_cosmosdb_sql_container" "platform-api" {
        id                  = "/subscriptions/72d94415-0067-4c3e-a6cb-b4a2355a7a96/resourceGroups/middleware-dev/providers/Microsoft.DocumentDB/databaseAccounts/middleware-cosmosdb-sql-dev/sqlDatabases/platform-api/containers/platform-api"
        name                = "platform-api"
      ~ throughput          = 400 -> 700
        # (5 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  # module.middleware-environment.azurerm_cosmosdb_account.cosmos-sql-db will be updated in-place
  ~ resource "azurerm_cosmosdb_account" "cosmos-sql-db" {
      + default_identity_type                 = "FirstPartyIdentity"
        id                                    = "/subscriptions/72d94415-0067-4c3e-a6cb-b4a2355a7a96/resourceGroups/middleware-dev/providers/Microsoft.DocumentDB/databaseAccounts/middleware-cosmosdb-sql-dev"
        name                                  = "middleware-cosmosdb-sql-dev"
        tags                                  = {
            "Environment" = "dev"
            "Service"     = "Mo2C"
            "Team"        = "middleware"
        }
        # (27 unchanged attributes hidden)

         # (4 unchanged blocks hidden)
    }
```

### Expected Behaviour

When you terraform plan or apply, it should not show changes that are not part of a change request.  In the mentioned terraform plan output, throughput changes are not part CR and cosmosdb sql container use autoscaling but Its changes in manual throughput.

### Actual Behaviour

TF apply/Plan should not show any changes in manual throughput when autoscaling settings are enabled.

### Steps to Reproduce

1. Run terrafom plan
2. Check the section under Note: Objects have changed outside of Terraform.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_sql_container

**Comment by neil-yechenwei** [comment]
@vkamlesh , thanks for raising this issue. As `throughput` has default value `400`, so terraform detected it and warned that it's made outside of terraform but terraform wouldn't change this property. Actually, terraform wants to update `default_identity_type` so that the difference is outputted.

**Comment by neil-yechenwei** [comment]
@vkamlesh , as this issue is duplicate with https://github.com/hashicorp/terraform-provider-azurerm/issues/16706, so suggest close this issue and describe that issue. Thanks.
