### ISSUE TITLE
azurerm_management_group_policy_assignment : Not able to use "UserAssigned" as identity assignment

### ISSUE THREAD

**Issue by RKSelvi** [hashicorp/terraform-provider-azurerm#16898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_user_assigned_identity" "mg_id" {
  name                = "mgid"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
}

resource "azurerm_management_group_policy_assignment" "policy_assignment" {
  depends_on = [
    azurerm_policy_set_definition.policy_set,
    azurerm_user_assigned_identity.policy_id
  ]

  name                 = var.policy_set_name
  management_group_id  = data.azurerm_management_group.mg.id
  policy_definition_id = azurerm_policy_set_definition.policy_set.id
  description          = var.description
  display_name         = var.policy_set_name
  location             = var.location
  parameters           = <<-EOT
    {
      "param": {
        "value": "paramValue"
      }
    }
    EOT

    identity {
      type          = "UserAssigned"
      identity_ids  = [azurerm_user_assigned_identity.mg_id.id]
    }
}
```

### Debug Output/Panic Output

```shell
Error: updating Policy Assignment ID: (Assignment Name "RRR" / Scope "/providers/Microsoft.Management/managementGroups/MG"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="MissingIdentityIds" Message="The identity ids must not be null or empty for 'UserAssigned' identity type."
│ 
│   with azurerm_management_group_policy_assignment.policy_assignment,
│   on monitoring.tf line 87, in resource "azurerm_management_group_policy_assignment" "policy_assignment":
│   87: resource "azurerm_management_group_policy_assignment" "policy_assignment" ***
│ 
│ updating Policy Assignment ID: (Assignment Name "RRR" / Scope
│ "/providers/Microsoft.Management/managementGroups/MG"):
│ policy.AssignmentsClient#Create: Failure responding to request:
│ StatusCode=400 -- Original Error: autorest/azure: Service returned an
│ error. Status=400 Code="MissingIdentityIds" Message="The identity ids must
│ not be null or empty for 'UserAssigned' identity type."
```

### Expected Behaviour

User Managed Identity should have set for the Policy Initiative Assignment

### Actual Behaviour

Right now, I need to set SystemAssigned for the Policy set first time when the workflow runs. Then either I need to set it to User Managed Identity in the workflow using PowerShell or re-run the workflow with 'User Managed Identity' block.

    identity {
      type          = "SystemAssigned"
    }

### Steps to Reproduce

Create user managed identity TF resource and use that to set to policy initiative assignment with User Managed Identity. There will be a failure. 

resource "azurerm_management_group_policy_assignment" not able to set with 'User Managed Identity'

### Important Factoids

Azure Government

**Comment by lonegunmanb** [comment]
Hello @RKSelvi , thanks for opening this issue. I've tried to reproduce this issue with the following code in US Gov env but I cannot reproduce it:

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_management_group" "example" {
  display_name = "Some Management Group"
}

resource "azurerm_policy_definition" "example" {
  name                = "only-deploy-in-westeurope"
  display_name        = "only-deploy-in-westeurope"
  policy_type         = "Custom"
  mode                = "All"
  management_group_id = azurerm_management_group.example.id

  policy_rule = <<POLICY_RULE
    {
    "if": {
        "field": "location",
        "equals": "westeurope"
    },
    "then": {
      "effect": "Deny"
    }
  }
POLICY_RULE
}

resource "azurerm_resource_group" "rg" {
  location = "usgovarizona"
  name     = "zjhe-f16898"
}

resource "azurerm_user_assigned_identity" "mg_id" {
  name                = "zjhef16898"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
}

resource "azurerm_management_group_policy_assignment" "example" {
  name                 = "example-policy"
  policy_definition_id = azurerm_policy_definition.example.id
  management_group_id  = azurerm_management_group.example.id
  location             = azurerm_resource_group.rg.location
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.mg_id.id]
  }
}
```

The provision was success without error, and I've tried to switch the `identity` between `SystemAssigned` and `UserAssigned`. Would you please provide a minimum sample code that can reproduce the issue? Thanks!

**Comment by lonegunmanb** [comment]
@dansailer would you please give us a sample code that can reproduce this issue so we can try a fix? Thanks.

**Comment by RKSelvi** [comment]
> Hello @RKSelvi , thanks for opening this issue. I've tried to reproduce this issue with the following code in US Gov env but I cannot reproduce it:
> 
> ```terraform
> provider "azurerm" {
>   features {}
> }
> 
> resource "azurerm_management_group" "example" {
>   display_name = "Some Management Group"
> }
> 
> resource "azurerm_policy_definition" "example" {
>   name                = "only-deploy-in-westeurope"
>   display_name        = "only-deploy-in-westeurope"
>   policy_type         = "Custom"
>   mode                = "All"
>   management_group_id = azurerm_management_group.example.id
> 
>   policy_rule = <<POLICY_RULE
>     {
>     "if": {
>         "field": "location",
>         "equals": "westeurope"
>     },
>     "then": {
>       "effect": "Deny"
>     }
>   }
> POLICY_RULE
> }
> 
> resource "azurerm_resource_group" "rg" {
>   location = "usgovarizona"
>   name     = "zjhe-f16898"
> }
> 
> resource "azurerm_user_assigned_identity" "mg_id" {
>   name                = "zjhef16898"
>   resource_group_name = azurerm_resource_group.rg.name
>   location            = azurerm_resource_group.rg.location
> }
> 
> resource "azurerm_management_group_policy_assignment" "example" {
>   name                 = "example-policy"
>   policy_definition_id = azurerm_policy_definition.example.id
>   management_group_id  = azurerm_management_group.example.id
>   location             = azurerm_resource_group.rg.location
>   identity {
>     type         = "UserAssigned"
>     identity_ids = [azurerm_user_assigned_identity.mg_id.id]
>   }
> }
> ```
> 
> The provision was success without error, and I've tried to switch the `identity` between `SystemAssigned` and `UserAssigned`. Would you please try the latest provider (mine is v3.7.0) then provide a minimum sample code that can reproduce the issue? Thanks!

Hello @lonegunmanb 
Thank you for your response. But its the code I shared in this GH issue, no additional code. I am deploying to VA region as I see you are deploying to AZ. But not sure if that would make any difference.

**Comment by lonegunmanb** [comment]
@RKSelvi in the code snippet you posted we cannot see the declaration of `azurerm_resource_group.rg.name`/`data.azurerm_management_group.mg`/`azurerm_policy_set_definition.policy_set` . Would you please give me a sample that could reproduce this issue? I'll try VA region later. Thanks.

**Comment by lonegunmanb** [comment]
@RKSelvi I've tried VA region and still no luck to reproduce the issue. Would you please give me a minimum sample code that can reproduce this issue so I can try a fix? Thanks.
