### ISSUE TITLE
Upgrade to new provider produce a error on delete/replace public ip

### ISSUE THREAD

**Issue by MelleD** [hashicorp/terraform-provider-azurerm#16891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_public_ip

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "PublicIP" {
  name                = local.public_ip_name
  location            = var.location
  resource_group_name = azurerm_resource_group.ResourceGroup.name
  allocation_method   = "Static"
  sku                 = "Standard"
}
```

### Debug Output/Panic Output

```shell
deleting Public Ip Address: (Name \"xxx-public-ip\" / Resource Group \"xxx-rg\"):
       network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- 
       Original Error: Code=\"PublicIPAddressCannotBeDeleted\" Message=\"Public IP address /subscriptions/xxx/resourceGroups/xxx-rg/
       providers/Microsoft.Network/publicIPAddresses/xxx-public-ip can not be deleted since it is still
        allocated to resource /subscriptions/xxx/resourceGroups/xxx-rg/providers/Microsoft.Network/applicationGateways/
        xxx-gw/frontendIPConfigurations/xxx-vnet-feip. In order to delete the public IP disassociate/detach the Public IP address from the resource.         To learn how to do this, see aka.ms/deletepublicip.\"  



        "  # azurerm_public_ip.PublicIP must be replaced",
        "-/+ resource \"azurerm_public_ip\" \"PublicIP\" {",
        "      + fqdn                    = (known after apply)",
        "      ~ id                      = \"/subscriptions/xxx/resourceGroups/xxx-rg/providers/Microsoft.Network/publicIPAddresses/xxx-public-ip\" -> (known after apply)",
        "      ~ ip_address              = \"xxx\" -> (known after apply)",
        "      - ip_tags                 = {} -> null",
        "        name                    = \"xxx-public-ip\"",
        "      - tags                    = {} -> null",
        "      - zones                   = [",
        "          - \"1\",",
        "          - \"2\",",
        "          - \"3\",",
        "        ] -> null # forces replacement",
        "        # (7 unchanged attributes hidden)",
        "    }",
```

### Expected Behaviour

The PublicIP should no be deleted

### Actual Behaviour

The PublicIP is deleted

### Steps to Reproduce

Upgrade von terraform provider 2.99.0 to 3.7.0

**Comment by tombuildsstuff** [comment]
hi @MelleD 

This is a breaking change in 3.0 which is documented in [the 3.0 upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide) - as such you'll need to work through these changes when upgrading to v3.0.

Thanks!

**Comment by MelleD** [comment]
Hey @tombuildsstuff 

Of course I went through the document, but there is no documentation anywhere with the public ip.
Just see:
[Resource: azurerm_public_ip](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#resource-azurerm_public_ip)
The fields availability_zone and zones will be consolidated into zones.

Can you show me the spot and the migration step?
