### ISSUE TITLE
Documentation Issue for AzureRM 3.x regarding Windows App Services and Windows Function Apps

### ISSUE THREAD

**Issue by SteveKurutz** [hashicorp/terraform-provider-azurerm#16904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.x

### AzureRM Provider Version

3.x

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app azurerm_windows_function_app

### Terraform Configuration Files

This is a documentation issue.  https://registry.terraform.io/providers/hashicorp/azurerm/3.6.0/docs/resources/windows_function_app and https://registry.terraform.io/providers/hashicorp/azurerm/3.6.0/docs/resources/windows_web_app describe the use of the application_stack block as though it resides at the top level of the resource block, when in fact it appears that it's a child of the site_config block.  Or at least that's how it goes when I validate.  Code example:

```hcl
resource "azurerm_windows_function_app" "primary" {
  name                       = "azfun"
  location                   = "southcentralus"
  resource_group_name        = "rg"
  service_plan_id        = (doesn't matter)
  storage_account_name       = azurerm_storage_account.functions.name
  storage_account_access_key = azurerm_storage_account.functions.primary_access_key

  site_config {
    ftps_state                = "Disabled"
    http2_enabled             = "false"
    use_32_bit_worker = "true"
    websockets_enabled        = "false"
    minimum_tls_version           = "1.2"
  }

    application_stack {
  dotnet_version = "6"
}

  app_settings = (doesn't matter)

}
```

### Debug Output/Panic Output

```shell
terraform validate
╷
│ Error: Unsupported block type
│
│   on appservice.tf line 14, in resource "azurerm_windows_web_app" "api_primary":
│   14:   application_stack {
│
│ Blocks of type "application_stack" are not expected here.
```

### Expected Behaviour

It should have validated OK

### Actual Behaviour

It didn't validate

### Steps to Reproduce

Make web app or function app with the application_stack block at the root of the resource block, and try to validate it.

**Comment by xiaxyi** [comment]
@SteveKurutz can you try put application_stack block inside of the site_config block like below and see if it works?
```
  site_config {
    ftps_state          = "Disabled"
    http2_enabled       = "false"
    use_32_bit_worker   = "true"
    websockets_enabled  = "false"
    minimum_tls_version = "1.2"
    application_stack {
      dotnet_version = "6"
    }
  }
```

**Comment by xiaxyi** [comment]
@SteveKurutz Thanks for pointing this docs issue out, we will try our best to update the docs in time in the future.
