### ISSUE TITLE
azurerm_linux_function_app fails to create a function app for custom handlers because the azurerm_service_plan seems to not be getting properly created

### ISSUE THREAD

**Issue by msalazar97** [hashicorp/terraform-provider-azurerm#16936]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

2.2.0

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "platform-health-checker-tf"
  location = "East US"
}

resource "azurerm_storage_account" "sa" {
  name                     = "phchosttf"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "sp" {
  name                = "ASP-phc-host-tf"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "fa" {
  name                = "phc-host-tf"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  storage_account_name = azurerm_storage_account.sa.name
  service_plan_id      = azurerm_service_plan.sp.id

  site_config {
    application_stack {
      use_custom_runtime = true
    }
  }
}

resource "azurerm_function_app_function" "f1" {
  name            = "health"
  function_app_id = azurerm_linux_function_app.fa.id
  language        = "Custom"

  file {
    name    = "handler"
    content = filebase64sha256("path/to/handler/without/.go/extension/(compiled for linux)")
  }

  config_json = jsonencode({
    "bindings": [
        {
        "authLevel": "anonymous",
        "type": "httpTrigger",
        "direction": "in",
        "name": "req",
        "methods": [
            "get",
            "post"
        ]
        },
        {
        "type": "http",
        "direction": "out",
        "name": "res"
        }
    ]
  })
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Linux Function App: (Site Name "phc-host-tf" / Resource Group "platform-health-checker-tf"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter LinuxFxVersion has an invalid value." Details=[{"Message":"The parameter LinuxFxVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["LinuxFxVersion"]}}]
│
│   with azurerm_linux_function_app.fa,
│   on main.tf line 46, in resource "azurerm_linux_function_app" "fa":
│   46: resource "azurerm_linux_function_app" "fa" {
│
│ creating Linux Function App: (Site Name "phc-host-tf" / Resource Group "platform-health-checker-tf"):
│ web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The
│ parameter LinuxFxVersion has an invalid value." Details=[{"Message":"The parameter LinuxFxVersion has an invalid
│ value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter
│ LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an invalid
│ value.","Parameters":["LinuxFxVersion"]}}]
```

### Expected Behaviour

The function should have been created. A function needs an App Service Plan (ASP) to run. By creating an ASP with the new azurerm_service_plan resource type, you cannot set the following attributes:
`kind = "Linux"`
`reserved = true`
as their values will be "decided automatically" once the resource gets created. (Can't configure a value for "kind/reserved": its value will be decided automatically based on the result of applying this configuration. That is the error that throws when you try to set those values in the new azurerm_service_plan resource type version). It seems that those lines solved that same error for the previous azurerm_service_plan resource type version (which was called azurerm_app_service_plan, but it is now deprecated). When using the deprecated version of this resource type (azurerm_app_service_plan) you can set those values, and the function gets created, but, of course, it has errors out of the scope of this issue since it uses an outdated version of Azure Functions).

### Actual Behaviour

The function does not get created. When you check the JSON of the ASP directly in the Azure Portal, the "reserved" attribute is set to true, but that does not make any change, it still fails to create the function. Moreover, when creating a function manually from the portal with the same configurations, it works, JSONs are practically identical.

### Steps to Reproduce

`terraform apply`

### Important Factoids

No

### References

#6882

**Comment by xiaxyi** [comment]
@msalazar97 as the error message shows, the issue should be caused by the LinuxFxVersion value, let me have a further investigation
