### ISSUE TITLE
Support for setting domain_name for AADDS in azurerm_storage_account azure_files_authentication block

### ISSUE THREAD

**Issue by ravensorb** [hashicorp/terraform-provider-azurerm#16932]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It appears there is no way to set the domain name when using AADDS for authentication as the active_directory block currently requires information that is only valid for use when connecting to AD

Current setting the active_directory block with domain_name results in an error that other attributes are missing.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Potential Terraform Configuration

```hcl
azurerm_storage_account {
    azure_files_authentication {
       directory_type = "AADDS"
       azure_active_directory_domain_services {
          domain_name_fqdn = "somename.example.com"
       }
    }
}
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#azure_files_authentication

**Comment by magodo** [comment]
@ravensorb Thank you for submitting this! Would you mind share the error message about which attributes are missing (presumably `samAccountName` and `accountType`)?

**Comment by ravensorb** [comment]
That would be everything marked as required in the "active_directory" block.  


[storage_sid](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#storage_sid) - (Required) Specifies the security identifier (SID) for Azure Storage.

[domain_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#domain_name) - (Required) Specifies the primary domain that the AD DNS server is authoritative for.

[domain_sid](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#domain_sid) - (Required) Specifies the security identifier (SID).

[domain_guid](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#domain_guid) - (Required) Specifies the domain GUID.

[forest_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#forest_name) - (Required) Specifies the Active Directory forest.

[netbios_domain_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#netbios_domain_name) - (Required) Specifies the NetBIOS domain name.

**Comment by magodo** [comment]
@ravensorb So in this case only the `domain_name` is actually required, but the others should be absent?

**Comment by ravensorb** [comment]
That would be my understanding as well -- the other items would not make sense when connected to AADDS based on Microsoft's documentation.

**Comment by magodo** [comment]
@ravensorb I just realized that you can simply omit the `active_directory` when `directory_type = "AADDS"`

**Comment by ravensorb** [comment]
Very true -- and that allows the authentication type to be set, what it doesn't allow though is to set the domain name that is used for authentication.  What happens is a random domain name is set and you need to go into the web portal and finish the "configuration" by setting it to the correct fqdn for the AADDS instance.  Right now I am doing this step either via PowerShell or ARM -- ideally I'd like to be able to do the complete setup via terraform.

**Comment by magodo** [comment]
@ravensorb In my case, my AADDS is named to a non-builtin name like: `never.gonna.shut.you.down`, and when I simply set the `directory_type = "AADDS"`, the resulting `domain_name` is set to `never.gonna.shut.you.down`. So it appears I don't need to explicitly set the fqdn for that?

**Comment by ravensorb** [comment]
Interesting - so far every time I have run the terraform script (setup AADDS first, then a storage account and enable AADS) - I have needed to into the web portal and "finish" the setup.  Then if I run the terraform script, it recognizes a "change" in the state of the storage account (active_directory -> domain_name is set) and looks to remove it.

**Comment by ravensorb** [comment]
@magodo - interesting.  Ok let me run a few more tests.   If your curious here is the module I am working with

https://github.com/ravensorb/terraform-azurerm-azure-filesync/blob/main/main.tf

**Comment by ravensorb** [comment]
I seem to be running into an issue getting that to work. Note the "not configured" in the screenshot below.

![image](https://user-images.githubusercontent.com/2222472/172032501-eec5f8a2-4fcf-4567-9612-c67db92011f7.png)

I created a module that can be used to reproduce the issue:  
https://registry.terraform.io/modules/ravensorb/azure-filestorage/azurerm/1.0.0

and here is the code 
https://github.com/ravensorb/terraform-azurerm-azure-filestorage/blob/main/main.tf

**Comment by ravensorb** [comment]
I think I figured out what the issue was -- The issue I was running into was related to the actual setup of AADDS
