### ISSUE TITLE
[azurerm_linux_function_app] storage_uses_managed_identity failed deployments without contentshare connection string

### ISSUE THREAD

**Issue by mkprizzle** [hashicorp/terraform-provider-azurerm#16935]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "functionapprg"
  location = "East US 2"
}

resource "azurerm_storage_account" "example" {
  name                            = "give_me_a_unique_name"
  resource_group_name             = azurerm_resource_group.example.name
  location                        = azurerm_resource_group.example.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
}

resource "azurerm_service_plan" "example" {
  name                = "amazingfunctionplan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "EP2"
}

resource "azurerm_linux_function_app" "example" {
  name                = "give_me_a_unique_name"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  service_plan_id            = azurerm_service_plan.example.id
  storage_uses_managed_identity = true
  # Commented out for easy toggling in testing
  app_settings = {
    # "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" = azurerm_storage_account.example.primary_connection_string
  }

  site_config {
    application_stack {
      python_version = "3.9"
      use_dotnet_isolated_runtime = null
    }
  }

  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity.id]
  }
}

resource "azurerm_user_assigned_identity" "identity" {
  name = "funcidentity"
  resource_group_name = azurerm_resource_group.example.name
  location = azurerm_resource_group.example.location
}

resource "azurerm_role_assignment" "storage_role" {
  scope = azurerm_storage_account.example.id
  principal_id = azurerm_user_assigned_identity.identity.principal_id
  role_definition_name = "Storage Account Contributor"
}

resource "azurerm_role_assignment" "storage_role_2" {
  scope = azurerm_storage_account.example.id
  principal_id = azurerm_user_assigned_identity.identity.principal_id
  role_definition_name = "Storage Blob Data Contributor"
}

# Just in case
resource "azurerm_role_assignment" "storage_role_3" {
  scope = azurerm_storage_account.example.id
  principal_id = azurerm_user_assigned_identity.identity.principal_id
  role_definition_name = "Storage File Data SMB Share Contributor"
}
```

### Debug Output/Panic Output

```shell
{"Code":"BadRequest","Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value.","Target":null,"Details":[{"Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"ExtendedCode":"51008","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"],"Code":"BadRequest","Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value."}}],"Innererror":null}: timestamp=2022-05-24T18:31:00.583-0400
2022-05-24T18:31:00.584-0400 [ERROR] vertex "azurerm_linux_function_app.example" error: creating Linux Function App: (Site Name "newfunctionapp123454" / Resource Group "functionapprg"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value." Details=[{"Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51008","Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"]}}]
```

### Expected Behaviour

Function app creates successfully, using managed identity to handle storage. (Even with a connection string set, the function does not provision storage containers correctly in the account when using managed identity)

### Actual Behaviour

Error in above debug

### Steps to Reproduce

Terraform apply the above sample code. Uncomment the WEBSITE_CONTENTAZUREFILECONNECTIONSTRING to see app not fully provision in the storage account containers.

**Comment by lordhits** [comment]
I'm noticing this issue with azurerm_windows_function_app resource too. Even when i provision the resource with "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" set, I can't seem to delete this configuration via the portal even when i'm using managed identity. So maybe it's an issue with Azure and not azurerm provider?

Terraform version: 1.2.2 Azurerm version: 3.8.0

**Comment by xiaxyi** [comment]
@mkprizzle The property needs to be used together with `WEBSITE_CONTENTSHARE` and  the share name must follow the [guidance](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-shares--directories--files--and-metadata#share-names). can you confirm whether you are following the best practice?

**Comment by mkprizzle** [comment]
@xiaxyi Thank you for the reply. 
I have modified my code to add a manually created website_contentshare.

```
resource "azurerm_storage_share" "storage_share" {
  name = "contentshare"
  storage_account_name = azurerm_storage_account.example.name
  quota = 50
  access_tier = "TransactionOptimized"
}

resource "azurerm_linux_function_app" "example" {
  name                = "myfunction"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  key_vault_reference_identity_id = azurerm_user_assigned_identity.identity.id
  service_plan_id            = azurerm_service_plan.example.id
  #storage_key_vault_secret_id = azurerm_key_vault_secret.example.versionless_id
  storage_account_name       = azurerm_storage_account.example.name
  # storage_account_access_key = azurerm_storage_account.example.primary_access_key
  storage_uses_managed_identity = true
  app_settings = {
    "WEBSITE_CONTENTSHARE" = azurerm_storage_share.storage_share.name
    # "WEBSITE_CONTENTOVERVNET" = "1"
    # "WEBSITE_CONTENTAZUREFILECONNECTIONSTRING" = azurerm_storage_account.example.primary_connection_string
  }
...
```
Result is the same:
```
Error: creating Linux Function App: (Site Name "myfunctionapp" / Resource Group "functionapprg"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value." Details=[{"Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51008","Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"]}}] 
```

Furthermore, the TF documentation does not indicate that property `storage_uses_managed_identity` must be used with app setting `WEBSITE_CONTENTSHARE` and manually created contentshare.

Hunch is that we are trying to compute the CONTENTAZUREFILECONNECTIONSTRING but do not have an account key provided to compute it properly while it is requiring one.

https://registry.terraform.io/providers/hashicorp/azurerm/3.9.0/docs/resources/linux_function_app

**Comment by xiaxyi** [comment]
@mkprizzle I can create the function app using your TF config without any errors. The error was threw by the api, can you confirm the connected storage account is in health state and have a valid connection string?
![image](https://user-images.githubusercontent.com/92154856/174567986-c1f38fda-b06e-412f-81ea-1eef05708de4.png)

**Comment by xiaxyi** [comment]
@lordhits I can delete the configuration without any issue, can you be more specific about the delete action you took, was there any error message received?

**Comment by mkprizzle** [comment]
If this is the case, please have this note added to the `storage_uses_managed_identity` attribute as there is no way to know this from the azurerm provider side and it throws the original error if this is not set.

As an aside, it defeats part of the purpose of wanting to use managed identity for storage, if my app settings still require a storage account key in them, which might be a question to take upstream.

**Comment by xiaxyi** [comment]
@mkprizzle WEBSITE_CONTENTAZUREFILECONNECTIONSTRING is required for event-driven scaling plans,  I'll figure out the relationship between this property and storage_uses_managed_identity. if there is any update, I'll let you know.
