### ISSUE TITLE
EventHub change partition count ends with error

### ISSUE THREAD

**Issue by caioqueirozkr** [hashicorp/terraform-provider-azurerm#16931]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "resourceGroup1"
  location = "West US"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "acceptanceTestEventHubNamespace"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "Standard"
  capacity            = 1
}

resource "azurerm_eventhub" "test" {
  name                = "acceptanceTestEventHub"
  namespace_name      = "${azurerm_eventhub_namespace.test.name}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  partition_count     = 4
  message_retention   = 1
}
```

### Debug Output/Panic Output

```shell
│ Error: `partition_count` cannot be changed unless the namespace sku is `Premium`
│ 
│   with azurerm_eventhub.eventhub["evh-test"],
│   on evh.tf line 53, in resource "azurerm_eventhub" "eventhub":
│   53: resource "azurerm_eventhub" "eventhub" {
│ 
╵
Releasing state lock. This may take a few moments...
Error: Process completed with exit code 1.
```

### Expected Behaviour

From the partition_count argument, is expected the destroy/recreate the eventhub (Once the parition count change in the Standard SKU EventHub Namespace is not allowed)

From this previous issue, (https://github.com/hashicorp/terraform/issues/19029) it was fixed, in version 1.20.0 but i still see the problem when i tried to change the partition count for an existing eventhub. 

### Actual Behaviour

Error when changing the partition count in an existing eventhub, telling that it can't be changed unless the namespace sku is premium.

### References

https://github.com/hashicorp/terraform/issues/19029

**Comment by xiaxyi** [comment]
@caioqueirozkr According to the official article, the partition count can only be changed under premium sku:
 _[You can't change the partition count for an event hub after its creation except for the event hub in a dedicated cluster and premium tier.](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features)

The behavior also aligned with the Terraform [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub#partition_count)

**Comment by xiaxyi** [comment]
Hi @caioqueirozkr, just would like to follow up with you to see if you have any question or concern regarding my last comment? :)

**Comment by calleo** [comment]
> @caioqueirozkr According to the official article, the partition count can only be changed under premium sku:
>  _[You can't change the partition count for an event hub after its creation except for the event hub in a dedicated cluster and premium tier.](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-features)
> 
> The behavior also aligned with the Terraform [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub#partition_count)

It would be so much better if Terraform could handle this and recreate the event-hub.

**Comment by rcskosir** [comment]
@caioqueirozkr Thank you for opening this issue. Per @xiaxyi's links to documentation it is clear that this is the expected behavior, therefore I am going to close this issue.
