### ISSUE TITLE
Support for AKS Monitoring Addon

### ISSUE THREAD

**Issue by thy143** [hashicorp/terraform-provider-azurerm#16937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Kubernetes Cluster have a addon called “monitor” which can be enabled/disabled as required. This addon if enabled performs multiple actions which include

•	Creates a Log Analytics Workspace (if the AKS cluster has not already been configured to use an existing one)
•	Enabled AKS to publish metrics for container insights into Log Analytics Workspace

Without enabling the “monitoring” addon, we can link AKS to a log Analytics Workspace, however we need to manually enable metrics for container insights.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
esource "azurerm_kubernetes_cluster" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  monitoring_enabled = true

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  oms_agent {
    log_analytics_workspace_id = "...."
  }

}
```

### References

https://docs.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-cli#create-aks-cluster

https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-enable-existing-clusters#integrate-with-an-existing-workspace

**Comment by thy143** [comment]
I have attempted to take a stab at implementing the feature but very new to golang and terraform providers. I believe I added all required code to ` kubernetes_addons.go`, however when I run my changes I get the following error

```
Error: creating Cluster: (Managed Cluster Name "example " / Resource Group "example "): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AddonInvalid" Message="Addon monitoring is invalid." Target="AddonProfiles"
```

So to me it looks like the SDK/APi does not support it (however AZ cli does).  I looked at the Azure SDK for GO (as I believe the AzureRM provider uses this from what I can understand). The closet reference I can find to Addons is this block of code here : https://github.com/Azure/azure-sdk-for-go/blob/a9d9b56a8ee885da9f94ed5e35ff001ca325fe84/services/preview/containerservice/mgmt/2022-01-02-preview/containerservice/models.go#L1264

This just seems to be generic struct to form a JSON block that could be submitted to the Azure API? Is any one able to confirm if I understanding things correctly? 

Finally can someone guide me how to check the Azure API to see if it does or does not support certain addons?

Thanks

**Comment by thy143** [comment]
HI @stephybun 

I tried the role assignment and it does “sort of” work. Once the OSM agent identity has been granted the permission it then seems to work as expected, however there is one slight issues (form my limited testing) is that it seems to take a while to detect the change. 

This then caused a issue with creating Azure monitor alerts due to the metrics not been immediately available. I did not see this issue when using AZ CLI and using the “monitoring” addon, as it seem like the metrics were ready as soon as the cluster creation completed.

I might be able to workaround this delay somehow – maybe with time_sleep or the new preconditions.


Just so I can understand development of the provider is there really no way to check Azure if they support that feature ? (i really keen on trying to contribute on bug fixes etc, but it’s a bit hard to understand what to check etc as a newcomer)? Is it just a case see if the SDK mentions or trying it out? 

Thank you

**Comment by stephybun** [comment]
Hi @thy143,

Apologies for the delayed response. An issue was raised over here https://github.com/MicrosoftDocs/azure-docs/issues/11090 regarding the documentation of the add-ons supported by the AKS API but so far not much has come of it. This information as far as I am aware is not readily available, if you do happen to find something I'd be thrilled if you could share it here 🙂 .

It can be overwhelming trying to understand how to get involved in contributing towards the provider, but we recently released some [contributor documentation](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/DEVELOPER.md#contributor-guides) which should provide some guidance in extending resources or submitting bug fixes.

Regarding the delay in the monitoring alerts, there is #6996 which currently tracks this issue. As such I am going to close this issue and ask you to subscribe to #6996 for updates.

Thanks!
