### ISSUE TITLE
[azurerm_policy_set_definition] 

### ISSUE THREAD

**Issue by Spacebjorn** [hashicorp/terraform-provider-azurerm#16942]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_policy_set_definition

### Terraform Configuration Files

```hcl
name         = "testPolicySet"
  policy_type  = "Custom"
  display_name = "Test Policy Set"

  parameters = <<PARAMETERS
    {
        "allowedLocations": {
            "type": "Array",
            "metadata": {
                "description": "The list of allowed locations for resources.",
                "displayName": "Allowed locations",
                "strongType": "location"
            }
        }
    }
PARAMETERS

  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/e765b5de-1225-4ba3-bd56-1ac6695af988"
    parameter_values     = <<VALUE
    {
      "listOfAllowedLocations": {"value": "[parameters('allowedLocations')]"}
    }
    VALUE
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Unable to parse Management Group ID ""
```

### Expected Behaviour

Going by the way the azurerm_policy_definition module works, this module should've assigned the policy set on the current subscription.

### Actual Behaviour

instead the resource fails saying it could not parse with the optional management group id that was not used. 

Actually adding in the management_group_id will produce the exact same error.

**Comment by danbarber72** [comment]
Hi @Spacebjorn ,
Interestingly I just had this exact same issue whilst running 3.6.0 of the azurerm provider with azurerm_policy_set_definition. 
Error: Unable to parse Management Group ID ""
I went back to version 3.5.0 of azurerm and the errors stopped. Might be worth you trying to go back to 3.5.0 to see if this resolves it for you, if so then it confirms that this issue was introduced in version 3.6.0.

**Comment by Spacebjorn** [comment]
Hi @danbarber72 ,

I can confirm it works downgrading to 3.5.0 Thanks a lot for the suggestion. Seems like @wuxu92  found the code piece that was changed as well!
