### ISSUE TITLE
azurerm_container_registry_task unable to update after a successful creation.

### ISSUE THREAD

**Issue by tju-that1guy** [hashicorp/terraform-provider-azurerm#16959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.7

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_task

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry_task" "acr_task_build_push" {
  name                  = "${module.naming-conventions.prefix}-build-push-on-commit-pr-main-ecs"
  container_registry_id = azurerm_container_registry.acr.id
  platform {
    os = "Linux"
  }
  docker_step {
    dockerfile_path      = "ecs/ecs.Dockerfile"
    context_path         = "https://EnterpriseCloudSolutions@dev.azure.com/EnterpriseCloudSolutions/EcsAgents/_git/ecsAgents#main:container"
    context_access_token = var.ado_pat_ecs
    image_names          = ["enterprise-containerized-agents:latest"]
  }

  source_trigger {
    name           = "test_trigger"
    events         = ["commit", "pullrequest"]
    repository_url = "https://EnterpriseCloudSolutions@dev.azure.com/EnterpriseCloudSolutions/EcsAgents/_git/ecsAgents"
    source_type    = "VisualStudioTeamService"
    authentication {
      token      = var.ado_pat_ecs
      token_type = "PAT"
    }
    branch  = "main"
    enabled = true
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_container_registry_task.acr_task_build_push_eads: Modifying... [id=/subscriptions/***/resourceGroups/use-ecs-foundation-rg-ops/providers/Microsoft.ContainerRegistry/registries/***/tasks/use-ecs-build-push-on-commit-pr-main-eads]
╷
│ Error: updating Container Registry Task: (Task Name "use-ecs-build-push-on-commit-pr-main-ecs" / Registry Name "***" / Resource Group "use-ecs-foundation-rg-ops"): containerregistry.TasksClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidInputValue" Message="Some of the properties of 'taskCreateParameters' are invalid.. InnerErrors: SourceProperties:Missing required property 'SourceControlAuthProperties'." Target="request" Details=[{"code":"MissingRequiredProperty","message":"Missing required property 'SourceControlAuthProperties'.","target":"SourceProperties"}]
│ 
│   with azurerm_container_registry_task.acr_task_build_push_ecs,
│   on main.tf line 197, in resource "azurerm_container_registry_task" "acr_task_build_push_ecs":
│  197: resource "azurerm_container_registry_task" "acr_task_build_push_ecs" {
│ 
│ updating Container Registry Task: (Task Name
│ "use-ecs-build-push-on-commit-pr-main-ecs" / Registry Name
│ "***" / Resource Group "use-ecs-foundation-rg-ops"):
│ containerregistry.TasksClient#Create: Failure sending request:
│ StatusCode=400 -- Original Error: Code="InvalidInputValue" Message="Some of
│ the properties of 'taskCreateParameters' are invalid.. InnerErrors:
│ SourceProperties:Missing required property 'SourceControlAuthProperties'."
│ Target="request"
│ Details=[{"code":"MissingRequiredProperty","message":"Missing required
│ property 'SourceControlAuthProperties'.","target":"SourceProperties"}]
```

### Expected Behaviour

azurerm_container_registry_task.acr_task_build_push_eads: completed

### Actual Behaviour

[logs.txt](https://github.com/hashicorp/terraform-provider-azurerm/files/8774287/logs.txt)

### Steps to Reproduce

The first apply will be successful.

Then I simply rerun my pipeline without any changes.

1. terraform init
2. terraform plan -out=tffile
3. terraform fmt
4. terraform apply 'tffile'
5. │ Error: updating Container Registry Task: (Task Name "use-ecs-build-push-on-commit-pr-main-ecs" / Registry Name "***" / Resource Group "use-ecs-foundation-rg-ops"): containerregistry.TasksClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidInputValue" Message="Some of the properties of 'taskCreateParameters' are invalid.. InnerErrors: SourceProperties:Missing required property 'SourceControlAuthProperties'." Target="request" Details=[{"code":"MissingRequiredProperty","message":"Missing required property 'SourceControlAuthProperties'.","target":"SourceProperties"}]

### Important Factoids

Running the agent in an azure container instance

### References

N/A

**Comment by tju-that1guy** [comment]
Terraform is able to delete the tasks and recreate them but unable to update after successful creation. I also noticed that this only started happening after I included the **source_trigger** block

**Comment by magodo** [comment]
@tju-that1guy Thank you for submitting this!

Unfortunately, I can't reproduce it locally with following config (it works well for me):

```hcl
resource "azurerm_container_registry_task" "test" {
  name                  = "testacccrTask220527113417385149"
  container_registry_id = azurerm_container_registry.test.id
  platform {
    os = "Linux"
  }
  docker_step {
    dockerfile_path      = "Dockerfile"
    context_path         = "https://github.com/magodo/acr-build-helloworld-node#main"
    context_access_token = "REDACTED"
    image_names          = ["helloworld:{{.Run.ID}}"]
  }
  source_trigger {
    name           = "default"
    events         = ["commit"]
    source_type    = "Github"
    repository_url = "https://github.com/magodo/acr-build-helloworld-node#main"
    branch         = "main"
    enabled        = true
    authentication {
      token_type = "PAT"
      token      = "REDACTED"
    }
  }
}
```

From the error message, it seems due to something is absent in the `authentication` block. Probably you forgot passing in the `ado_pat_ecs` variable?

**Comment by tju-that1guy** [comment]
The `ado_pat_ecs` is sent via pipeline variables which would error out during the `terraform plan -out=tffile`. This errors out during the `terraform apply 'tffile'`. This could be an issue with the `source_type    = "VisualStudioTeamService"` in combination with the `authentication` block, as I see you are using `github` as your `source_type`. 

I did also take note that `SourceControlAuthProperties` [comes from the azure docs found here.](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.containerregistry.fluent.models.sourceproperties.sourcecontrolauthproperties?view=azure-dotnet)

**Comment by magodo** [comment]
@tju-that1guy Thank you for the detail! I've successfully reproduce it with `source_type = "VisualStudioTeamService"`. The reason why there is diff after an apply is the `docker_step.context_path` is changed at service side from form `https://<user>@dev.azure.com/<user>/...` (as in the request) to the form `https://dev.azure.com/<user>/...`. The second apply will try to change it back to the former form, which triggers a bug in the provider (see #17002), causing the mentioned properties missing.

In your specific case, you can simply change your config to using the form `https://dev.azure.com/<user>/...`, and then you'll not get a plan diff after provisioning, therefore won't trigger the provider bug.
