### ISSUE TITLE
Azure Batch Pool user_identity passes user_name=""

### ISSUE THREAD

**Issue by ross-ivanov-oritain** [hashicorp/terraform-provider-azurerm#16975]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_batch_pool

### Terraform Configuration Files

```hcl
esource "azurerm_batch_pool" "batch_docker" {
  name                = "pool-docker"
  resource_group_name = azurerm_resource_group.ost.name
  account_name        = azurerm_batch_account.ost.name
  display_name        = "pool docker"
  vm_size             = "Standard_D16as_v4"
  node_agent_sku_id   = "batch.node.ubuntu 20.04"

  auto_scale {
    evaluation_interval = "PT5M"

    formula = <<EOF
$samples = $PendingTasks.GetSample(TimeInterval_Minute * 5);
$TargetLowPriorityNodes = (sum($samples)  > 0 ? 1:0)
EOF
  }

  storage_image_reference {
    publisher = "microsoft-azure-batch"
    offer     = "ubuntu-server-container"
    sku       = "20-04-lts"
    version   = "latest"
  }

  container_configuration {
    type = "DockerCompatible"
    container_registries {
      registry_server = var.docker_registry["server"]
      user_name       = var.docker_registry["username"]
      password        = data.azurerm_key_vault_secret.docker_registry_password.value
    }
    
  }
  
  identity {
    type = "UserAssigned"
    identity_ids = [
      azurerm_user_assigned_identity.ost.id
    ]
  }
--container-name=ost-clhs-pipeline
  start_task {
    command_line = "sudo blobfuse /mnt/batch/tasks/fsmounts/data --tmp-path=/mnt/batch/tasks/fsmounts/data --container-name=data"
    task_retry_maximum = 3
    wait_for_success   = true
    common_environment_properties = {
      env="test"
    }
    user_identity {
      auto_user {
        elevation_level = "Admin"
        scope = "Pool"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Pool: (Name "pool-docker" / Batch Account Name "devaccount" / Resource Group "dev-gr"): auto_user and user_name cannot be specified in the user_identity at the same time

======
DEBUG:
          "identity": [
              {
--
                "resource_file": [],
                "task_retry_maximum": 3,
                "user_identity": [
                  {
                    "auto_user": [
                      {
                        "elevation_level": "Admin",
                        "scope": "Pool"
                      }
                    ],
                    "user_name": ""
                  }
                ],
                "wait_for_success": true
              }
            ],
```

### Expected Behaviour

"user_name": "" should not be created, when auto_user specified? 

### Actual Behaviour

Terraform fails to create pool because either auto_user or user_name must be specified.

        "user_identity": [
                  {
                    "auto_user": [
                      {
                        "elevation_level": "Admin",
                        "scope": "Pool"
                      }
                    ],
                    "user_name": ""

### Steps to Reproduce

create pool with start_task and specify user_identity as auto_user
...
    user_identity {
      auto_user {
        elevation_level = "Admin"
        scope = "Pool"
      }

...

### Important Factoids

no

**Comment by liuwuliuyun** [comment]
I did reproduce this issue on my side with follwing tf file using 3.7.0 and 3.8.0 azurerm provider and we will plan to fix this issue.
`terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.8.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "yunliu_test"
  location = "east us"
}

resource "azurerm_batch_account" "test" {
  name                = "testaccbatch"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_batch_pool" "test" {
  name                = "testaccpool"
  resource_group_name = azurerm_resource_group.test.name
  account_name        = azurerm_batch_account.test.name
  node_agent_sku_id   = "batch.node.ubuntu 18.04"
  vm_size             = "Standard_A1"

  fixed_scale {
    target_dedicated_nodes = 1
  }

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-lts"
    version   = "latest"
  }

  start_task {
    command_line       = "echo 'Hello World from $env'"
    wait_for_success   = true
    task_retry_maximum = 5
    common_environment_properties = {
      env = "TEST"
      bu  = "Research&Dev"
    }

    user_identity {
      auto_user {
        elevation_level = "NonAdmin"
        scope           = "Task"
      }
    }

    resource_file {
      http_url  = "https://raw.githubusercontent.com/hashicorp/terraform-provider-azurerm/main/README.md"
      file_path = "README.md"
    }
  }
}`

**Comment by liuwuliuyun** [comment]
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.8.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "yunliu_test"
  location = "east us"
}

resource "azurerm_batch_account" "test" {
  name                = "testaccbatch"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_batch_pool" "test" {
  name                = "testaccpool"
  resource_group_name = azurerm_resource_group.test.name
  account_name        = azurerm_batch_account.test.name
  node_agent_sku_id   = "batch.node.ubuntu 18.04"
  vm_size             = "Standard_A1"

  fixed_scale {
    target_dedicated_nodes = 1
  }

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-lts"
    version   = "latest"
  }

  start_task {
    command_line       = "echo 'Hello World from $env'"
    wait_for_success   = true
    task_retry_maximum = 5
    common_environment_properties = {
      env = "TEST"
      bu  = "Research&Dev"
    }
    user_identity {
      auto_user {
        elevation_level = "NonAdmin"
        scope           = "Task"
      }
    }
    resource_file {
      http_url  = "https://raw.githubusercontent.com/hashicorp/terraform-provider-azurerm/main/README.md"
      file_path = "README.md"
    }
  }
}

**Comment by liuwuliuyun** [comment]
` Error: creating Pool: (Name "testaccpool" / Batch Account Name "testaccbatch" / Resource Group "yunliu_test"): auto_user and user_name cannot be specified in the user_identity at the same time
│
│   with azurerm_batch_pool.test,
│   on test.tf line 25, in resource "azurerm_batch_pool" "test":
│   25: resource "azurerm_batch_pool" "test" {
│
╵`

**Comment by liuwuliuyun** [comment]
PR raised: https://github.com/hashicorp/terraform-provider-azurerm/pull/17004

**Comment by liuwuliuyun** [comment]
I just tested v3.9.0 and it works, if no more request from @ross-ivanov-oritain I will close this issue.
