### ISSUE TITLE
Support for setting docker registry for azure functions

### ISSUE THREAD

**Issue by jacob7395** [hashicorp/terraform-provider-azurerm#16991]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I might be missing something but I can't see a way to set the registry value when deploying an azure function with an azure container registry. See image bellow:

![Screenshot 2022-05-27 110641](https://user-images.githubusercontent.com/9060893/170679643-32a8f748-079e-440c-ae95-ab0a8e7b2750.png)

The block to generate this is as follows

```
resource "azurerm_service_plan" "function" {
  name                = "${var.project}-batch-api-service-plan"
  location            = azurerm_resource_group.batch.location
  resource_group_name = azurerm_resource_group.batch.name
  os_type             = "Linux"
  sku_name            = "B1"
}

resource "azurerm_linux_function_app" "function" {
  name                       = "${var.project}-batch-azure-functions"
  location                   = azurerm_resource_group.batch.location
  resource_group_name        = azurerm_resource_group.batch.name
  service_plan_id            = azurerm_service_plan.function.id
  storage_account_name       = azurerm_storage_account.function.name
  storage_account_access_key = azurerm_storage_account.function.primary_access_key

  app_settings = {
    # "VaultUri"                          = "${azurerm_key_vault.main.vault_uri}"
    "AzureWebJobsStorage"      = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.function-storage-connection-stirng.versionless_id})"
    DOCKER_ENABLE_CI           = true
    DOCKER_REGISTRY_SERVER_URL = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.acr-login-server.versionless_id})"
    # DOCKER_REGISTRY_SERVER_USERNAME = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.acr-admin-username.versionless_id})"
    # DOCKER_REGISTRY_SERVER_PASSWORD = "@Microsoft.KeyVault(SecretUri=${azurerm_key_vault_secret.acr-admin-password.versionless_id})"
    # WEBSITES_ENABLE_APP_SERVICE_STORAGE = false
  }

  site_config {
    always_on                                     = true
    container_registry_use_managed_identity       = true
    container_registry_managed_identity_client_id = azurerm_user_assigned_identity.identity.client_id
    app_scale_limit                               = 5
    application_stack {
      docker {
        registry_url = azurerm_key_vault_secret.acr-login-server.value
        image_name   = var.image_name
        image_tag    = var.tag
      }
    }
  }

  identity {
    type         = "UserAssigned"
    identity_ids = ["${azurerm_user_assigned_identity.identity.id}"]
  }

  tags = var.tags
}
```

The CI option isn't directly supported in terraform but this can be fixed by adding the "DOCKER_ENABLE_CI" app setting. Is there a similar work around for the registry option?

If not can we get an option with the site_config, something like "container_registry_name"?

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

**Comment by xiaxyi** [comment]
checking the feature

**Comment by xiaxyi** [comment]
@jacob7395 can you be more specific about "The CI option isn't directly supported" as adding the `DOCKER_ENABLE_CI` in the `app_setting` is a direct way?

**Comment by jacob7395** [comment]
Hi, sorry for the delay I have been away.

What I mean is there are no arguments within the transformer resource. This isn't the direct issue rather there is no way to set the "Registry" used. 

The docker block within site_config -> application_stack sets the image and tag to the correct value but not the register.
