### ISSUE TITLE
AppService Plan SKU errors out when set to "FREE"

### ISSUE THREAD

**Issue by rumenavramov** [hashicorp/terraform-provider-azurerm#17032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

The documentation on this page: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan, lists the acceptable values for the "sku_name" attribute. One of the values listed is "FREE". When you select that value, however, TF gets an error from Azure that the the SKU name is not valid.
If "F1" is used, everything works fine.

Please update the documentation (or fix the big if this is a bug)!

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "service_plan_name" {
  name                = "service_plan_name"
  resource_group_name = azurerm_resource_group.AllResources.name
  location            = azurerm_resource_group.AllResources.location
  os_type             = "Windows"
  sku_name            = "FREE"
}
```

### Debug Output/Panic Output

```shell
Terraform v1.2.1
on linux_amd64
Initializing plugins and modules...
azurerm_service_plan.service_plan_name: Creating...

Error: creating Service Plan: (Serverfarm Name "service_plan_name" / Resource Group "AllResources"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter SKU.Name has an invalid value." Details=[{"Message":"The parameter SKU.Name has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"The parameter SKU.Name has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["SKU.Name"]}}]
│ 
│   with azurerm_service_plan.service_plan_name,
│   on azure.appservices.tf line 1, in resource "azurerm_service_plan" "service_plan_name":
│    1: resource "azurerm_service_plan" "service_plan_name" {
│ 
│ creating Service Plan: (Serverfarm Name "service_plan_name" / Resource Group
│ "AllResources"): web.AppServicePlansClient#CreateOrUpdate: Failure sending
│ request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The
│ parameter SKU.Name has an invalid value." Details=[{"Message":"The
│ parameter SKU.Name has an invalid
│ value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","Message":"The
│ parameter SKU.Name has an invalid value.","MessageTemplate":"The parameter
│ {0} has an invalid value.","Parameters":["SKU.Name"]}}]

Operation failed: failed running terraform apply (exit 1)
```

### Expected Behaviour

The service plan should have been created.

### Actual Behaviour

Service plan creation failed

**Comment by kyohei-ts** [comment]
Had same error. Using `F1` instead of `FREE` solved the issue.

**Comment by eamreyes** [comment]
What is the best course of action for discovering which SKU values in TF map to which SKU values in Azure? The documentation mentions a  `SHARED` SKU but I can't find it in the Azure Portal or in Azure Previews.

I found FREE == F1 thanks to @kyohei-ts , and the Azure Portal confirms it when I try to make a plan manually. However, someone like me might assume S1 == SHARED. Luckily I double checked in the Portal.
