### ISSUE TITLE
data "azurerm_private_dns_zone" no longer looks up resource group starting in v3.8.0

### ISSUE THREAD

**Issue by jdaugherty** [hashicorp/terraform-provider-azurerm#17036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

data azurerm_private_dns_zone

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source                = "hashicorp/azurerm"
      version               = "=3.8.0"
      configuration_aliases = [azurerm, azurerm.ops]
    }
  }
}

data "azurerm_private_dns_zone" "aks-dns-zone-lookup" {
  name                = "privatelink.eastus.azmk8s.io"
  provider            = azurerm.ops
}

output "testing" {
  value = data.azurerm_private_dns_zone.aks-dns-zone-lookup.id
}
```

### Debug Output/Panic Output

```shell
testing = "/subscriptions/***/resourceGroups//providers/Microsoft.Network/privateDnsZones/privatelink.eastus.azmk8s.io"
```

### Expected Behaviour

testing = "/subscriptions/***/resourceGroups/my-resource-group-name-here/providers/Microsoft.Network/privateDnsZones/privatelink.eastus.azmk8s.io"

In v3.7.0, the resource group name was optional on the data lookup, but in v3.8.0 it returns an id without the resource group name in the path if a resource group name is not provided.  Adding the resource group name to the data lookup includes the resource name, indicating that it's now required in 3.8.0 or a regression was introduced in 3.8.0.

### Actual Behaviour

testing = "/subscriptions/***/resourceGroups//providers/Microsoft.Network/privateDnsZones/privatelink.eastus.azmk8s.io"

The resource group name is excluded in 3.8.0, while it was previously included in 3.7.0

### Steps to Reproduce

terraform apply

**Comment by owenfarrell** [comment]
@jdaugherty - looks like this was a byproduct of #16858. In prior versions, the resource ID was lazily generated (off of the Azure API response). But after the move to the embedded SDK, the ID was eagerly generated.

And while the resource group name attribute in the state was always being populated, the resource group name **_attribute on that ID_** wasn't updated if/when omitted in the configuration.
