### ISSUE TITLE
azurerm_subnet.address_prefixes docu should needs update

### ISSUE THREAD

**Issue by Haratsu** [hashicorp/terraform-provider-azurerm#17052]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24","10.0.2.0/24"]

}
```

### Debug Output/Panic Output

```shell
Error: Error Creating/Updating Subnet "example-subnet" (Virtual Network "example-vnet" / Resource Group "example-resources"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="SubscriptionNotRegisteredForFeature" Message="Subscription 60471ca2-f532-4ac9-8736-d89df5c2b54d is not registered for feature Microsoft.Network/AllowMultipleAddressPrefixesOnSubnet required to carry out the requested operation." Details=[]
```

### Expected Behaviour

After registering resource provider `Microsoft.Network/AllowMultipleAddressPrefixesOnSubnet` it should be possible to apply the terraform template above.

### Actual Behaviour

Resource provider `Microsoft.Network/AllowMultipleAddressPrefixesOnSubnet`is not available for public access (not even in 'pre' state) cmp. [Azure Cli #18194](https://github.com/Azure/azure-cli/issues/18194)
So non MS developers will never be able to use it right now.

I would highly recommend mentioning this in the documentation, otherwise it wastes time of both terraform users and MS support.

**Comment by catriona-m** [comment]
Looks like this has now been addressed by #17109 so this can be closed. Thanks!
