### ISSUE TITLE
`azurerm_linux_function_app` loses external `WEBSITE_RUN_FROM_PACKAGE` setting, causing the Function App to break

### ISSUE THREAD

**Issue by MHarutunian** [hashicorp/terraform-provider-azurerm#17081]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "this" {
  name                       = "func-example-dev"
  resource_group_name        = var.resource_group_name
  location                   = var.location
  service_plan_id            = var.service_plan_id
  storage_account_name       = var.storage_account_name
  storage_account_access_key = var.storage_account_access_key
  https_only                 = true
  builtin_logging_enabled    = false
  tags                       = var.tags

  identity {
    type = "SystemAssigned"
  }

  site_config {
    application_insights_connection_string = var.application_insights_connection_string
    http2_enabled                          = true

    application_stack {
      node_version = 16
    }
  }

  app_settings = merge(
    { "WEBSITE_MOUNT_ENABLED" : "1" },
    var.app_settings
  )

  lifecycle {
    ignore_changes = [
      # We tried with and without ignoring changes here, but in both cases adding/removing entries to/from app_settings
      # causes WEBSITE_RUN_FROM_PACKAGE to be removed entirely
      app_settings["WEBSITE_RUN_FROM_PACKAGE"],
    ]
  }
}
```

### Debug Output/Panic Output

```shell
n/a (please let me know if I can provide any helpful output)
```

### Expected Behaviour

Making changes to `azurerm_linux_function_app.app_settings` has no effect on any external `WEBSITE_RUN_FROM_PACKAGE` entry.

### Actual Behaviour

Whenever there are changes to `app_settings` within the terraform configuration, the `WEBSITE_RUN_FROM_PACKAGE` setting gets removed on the next `terraform apply`. This renders the Function App broken, because the deployment package cannot be retrieved.

In particular this happens when deploying with the Azure Function Core Tools using `func azure functionapp publish`, since this will publish the package to a storage account and set the `WEBSITE_RUN_FROM_PACKAGE` in the Function App's `app_settings`. Upon the next changes in terraform, this setting will be removed and require another explicit deployment using the Azure Function Core Tools to be repaired. In between the Function App is broken.

Unlike mentioned in issue https://github.com/hashicorp/terraform-provider-azurerm/issues/16396 the `WEBSITE_RUN_FROM_PACKAGE` setting does not appear in the terraform plan or state at all, but it will be removed whenever there are any other changes in `app_settings`.

### Steps to Reproduce

1. Create the Function App `func-example-dev` using `terraform apply`
2. Deploy a function using `func azure functionapp publish func-example-dev` (here the `WEBSITE_RUN_FROM_PACKAGE` will be set on the Function App's settings)
3. Add an entry to the `app_settings` of the `azurerm_linux_function_app` resource in terraform
4. Run `terraform apply` to apply the changes to the `app_settings` (note that the plan will show no changes to `WEBSITE_RUN_FROM_PACKAGE`)
5. The Function App loses its `WEBSITE_RUN_FROM_PACKAGE` setting and becomes unusable

### References

A similar issue has been reported here:
https://github.com/hashicorp/terraform-provider-azurerm/issues/16396

The issue was supposedly fixed in this pull request:
https://github.com/hashicorp/terraform-provider-azurerm/pull/16641

However, we are still running into the issue, although the behavior seems to have changed a bit (see `Actual Behavior`)

**Comment by xiaxyi** [comment]
@MHarutunian based on my understanding, the app setting `WEBSITE_RUN_FROM_PACKAGE ` was added via another tool instead of by terraform directly as below code:
```
  app_settings = {
    "WEBSITE_MOUNT_ENABLED" : "1",
    "WEBSITE_RUN_FROM_PACKAGE" : URL
  }
```

if the `WEBSITE_RUN_FROM_PACKAGE` is not explicitly specified in the tf config, then it will be removed when running TF apply?

**Comment by MHarutunian** [comment]
@xiaxyi yes, exactly. In our case the `WEBSITE_RUN_FROM_PACKAGE` setting is managed by [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local#publish), which we use to publish our projects to the Function App.

Running `terraform plan` will not show any outside `WEBSITE_RUN_FROM_PACKAGE` changes at all (e.g. to apply it with a `-refresh-only`), and it will also not show the setting to be removed. I believe this is due to the changes in PR #16641 , but I am not sure.

However, when there are any other changes to `app_settings` in terraform, the next `terraform apply` will remove the `WEBSITE_RUN_FROM_PACKAGE` setting, which is required to keep the Function App functional.

**Comment by maQus123** [comment]
We experience same behavior (Linux & Consumption). Functions-Code is deployed outside of Terraform via Azure DevOps Task `AzureFunctionApp@1`. When that task runs, it assignes `WEBSITE_RUN_FROM_PACKAGE` and `WEBSITE_ENABLE_SYNC_UPDATE_SITE` (whatever that is responsible for?!) accordingly and Functions work. When terraform runs, both app settings disappear and Functions are broken.

**Comment by xiaxyi** [comment]
@maQus123, @MHarutunian  do you have any changes besides the property `WEBSITE_RUN_FROM_PACKAGE ` in the TF config?

The cause is the property is not managed by TF using TF config file, if there is any changes to the original config, then TF will try to remove/ set the default value to those unmanaged properties. 

Can you try add the corresponding property in the config manually or by using data source to update any unmanaged properties?

example would be:
```
data "azurerm_linux_function_app" "current" {
  name                = "xiaxintest-funtionapp"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_linux_function_app" "this" {
  name                       = "xiaxintest-funtionapp"
  resource_group_name        = azurerm_resource_group.test.name
  location                   = azurerm_resource_group.test.location
  service_plan_id            = azurerm_service_plan.test.id
  storage_account_name       = azurerm_storage_account.test.name
  storage_account_access_key = azurerm_storage_account.test.primary_access_key
  https_only                 = true
  builtin_logging_enabled    = false

  identity {
    type = "SystemAssigned"
  }

  site_config {
    application_insights_connection_string = azurerm_application_insights.test.connection_string
    http2_enabled                          = true

    application_stack {
      node_version = 16
    }
  }

  app_settings = merge(
    {
      "WEBSITE_MOUNT_ENABLED" : "1",
    },
    data.azurerm_linux_function_app.current.app_settings
  )
}

```

**Comment by athisun** [comment]
One potential workaround would be to construct the `WEBSITE_RUN_FROM_PACKAGE` app setting manually. Here's an example of it being done in an Azure Cognitive Search example repo: https://github.com/rozele/azure-cognitive-search-skills-terraform/blob/main/deploy/terraform/functions.tf
```terraform
app_settings = {
  WEBSITE_RUN_FROM_PACKAGE = "https://${azurerm_storage_account.instance.name}.blob.core.windows.net/${azurerm_storage_container.deploy.name}/${azurerm_storage_blob.instance.name}${data.azurerm_storage_account_sas.instance.sas}"
}
```

**Comment by MHarutunian** [comment]
Thank you @athisun,
unfortunately I don't think it's possible to specify the name of the deployment package when publishing the Function App via the Functions Core Tools, see https://github.com/Azure/azure-functions-core-tools/blob/db2ff784941c3f6241aea996818ba370ea441bd2/src/Azure.Functions.Cli/Actions/AzureActions/PublishFunctionAppAction.cs#L614.

The DevOps task (which we are not using btw) also doesn't seem to have that option.

Even if it were possible, wouldn't that restrict us to use a static name for the deployment package? Not sure what the official recommendations are, but at least all Azure tools seem to generate new package names for each deployment, instead of overriding an existing deployment package.

**Comment by MHarutunian** [comment]
@xiaxyi
So I tried using a data source, and it somewhat works. It is possible to "import" the `WEBSITE_RUN_FROM_PACKAGE` setting this way, and running `terraform apply` will no longer break a running Function App. I needed to make a small adjustment to make it work, because otherwise it would not be possible to remove `app_settings` from the original Function App via terraform (they would be added back through the data source):

```
data "azurerm_linux_function_app" "existing" {
  name                = "func-${var.application_name}-${var.environment}"
  resource_group_name = var.resource_group_name
}

resource "azurerm_linux_function_app" "this" {
  name                       = "func-${var.application_name}-${var.environment}"
  resource_group_name        = var.resource_group_name
  ...

  # this null check is for covering the case when the Function App is created for the first time - I don't know why it works
  app_settings = data.azurerm_linux_function_app.existing.app_settings == null ? var.app_settings : merge(
      # we only set this one setting explicitly, because otherwise removing settings in var.app_settings would have no effect
    { "WEBSITE_RUN_FROM_PACKAGE" = data.azurerm_linux_function_app.existing.app_settings["WEBSITE_RUN_FROM_PACKAGE"] },
    var.app_settings,
  )
}
```

For some reason this also works when creating the Function App for the first time, i.e. when the data source cannot be retrieved. In this case `data.azurerm_linux_function_app.existing.app_settings` will be `null`, which surprised me to be honest, I thought that the lookup of the data source would fail with an error. This is usually the case with other data sources, so I'm not sure why it doesn't happen here, but it also makes me question the stability of this workaround, as I expect this to be subjective to change in future versions.

**Comment by xiaxyi** [comment]
@MHarutunian  if the resource does not exists, the state will set all its attributes to null.

**Comment by MHarutunian** [comment]
@xiaxyi is that behavior specific to `azurerm_linux_function_app`? My experience with data sources is different, usually an error will be thrown when a data source cannot be found. Minimal example:
```
provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "nonexisting" {
  name = "nonexisting"
}
```
will produce
```
data.azurerm_resource_group.nonexisting: Reading...
╷
│ Error: Error: Resource Group "nonexisting" was not found
│ 
│   with data.azurerm_resource_group.nonexisting,
│   on output.tf line 5, in data "azurerm_resource_group" "nonexisting":
│    5: data "azurerm_resource_group" "nonexisting" {
│ 
╵
```
I used resource group as an example, but I've seen this with a lot of other data sources as well. And the latest [(somewhat) official statement](https://github.com/hashicorp/terraform/issues/16380#issuecomment-517282340) I've read is that allowing empty data sources "runs counter to Terraform's design goals". That's why I am surprised to see that this does seems to work here.

**Comment by MHarutunian** [comment]
Regarding the workaround we have in place now: We had to adapt it even further, because in case of an existing Function App that has not been deployed yet, we would still run into error (because `WEBSITE_RUN_FROM_PACKAGE` was not set in the data source's `app_settings`). For anybody else facing this issue, this is what we currently use:
```
data "azurerm_linux_function_app" "existing" {
  name                = "func-example"
  resource_group_name = var.resource_group_name
}

locals {
  existing_app_settings = coalesce(data.azurerm_linux_function_app.existing.app_settings, {})
}

resource "azurerm_linux_function_app" "example" {
  name                       = "func-example"
  ...
  app_settings = merge(
    {
      "WEBSITE_MOUNT_ENABLED"    = lookup(local.existing_app_settings, "WEBSITE_MOUNT_ENABLED", null)
      "WEBSITE_RUN_FROM_PACKAGE" = lookup(local.existing_app_settings, "WEBSITE_RUN_FROM_PACKAGE", null)
    },
    var.app_settings,
  )
}
```
It somehow works, but it still makes me wonder if that is how it's supposed to be, because it seems quite tedious and error prone. In the terraform plan there still is no mention that any of the app settings would be removed, so without knowing about this issue it can and will break Function App deployments without any notice. We ran into several broken deployments ourselves before we figured out what was actually happening. And we are just using the regular approach of deployment via Azure Functions Core Tools as documented and officially recommended, nothing fancy either.

**Comment by xiaxyi** [comment]
@MHarutunian I will check the code and see if we can add the notification to the user.

**Comment by MHarutunian** [comment]
@xiaxyi thank you, just wanted to mention again that the plan-diff was working a few months back as mentioned in this issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/16396

There was a PR for this in https://github.com/hashicorp/terraform-provider-azurerm/pull/16641, but I think it just made the diff disappear without fixing the actual issue (or maybe another issue was fixed and I misunderstood).

I just want to avoid adding another band-aid to to this just to show a notification, when there is an explicit case in `unpackLinuxFunctionAppSettings()` to handle the `WEBSITE_RUN_FROM_PACKAGE` issue.

**Comment by xiaxyi** [comment]
@MHarutunian This actually is a by-design one as TF won't manage the changes that are made outside of TF. If you look at the code in the pr https://github.com/hashicorp/terraform-provider-azurerm/pull/16641, you'll find out that the property is written to state only if the user explicitly sets it in the TF config. I'm not sure if we can consider extracting this property and put it directly in app setting, but we'll see what we can do, just no guarantee.

**Comment by xiaxyi** [comment]
@MHarutunian No problems. Actually, we are not "filtering" the key out, we are just conditionally set it back. TF doesn't manage the key that's changed outside of it. The difference between this property and the others is this property (the key) is added by user themselves in the app_setting map, which means, TF has no idea about this property if the user adds it outside so it will revert the app_setting back to what was defined in the original config. Hope it makes sense to you. Considering this is a by-design behavior, what's left to us is very limited, but I'll see what can be done.

**Comment by chriswhitts** [comment]
I can confirm experiencing the same issue mentioned here.

We also tried the lifecycle ignore approach but it does not work as expected.

e.g.

```
app_settings = {
    WEBSITE_ENABLE_SYNC_UPDATE_SITE = "true"
    WEBSITE_RUN_FROM_PACKAGE        = "" # This value is irrelevant and will be populated correctly by subsequent Function app code deployments (github) which is why we need to init it here and ignore it below
  }

  lifecycle {
    ignore_changes = [
      app_settings["WEBSITE_RUN_FROM_PACKAGE"]
    ]
  }
```

When terraform initially creates the function app it correctly sets an empty string 
Subsequent github deploy sets the string value to a url
Next Terraform change containing an update to app_settings causes the setting to disappear

In other words it's not being tracked at all that point whereas it should be tracked and ignoring future changes. This is **definitely** a bug

**Comment by Dergons** [comment]
I can also confirm this issue, and I think it's understated how bad this is. Any changes to app_settings silently removes the `WEBSITE_RUN_FROM_PACKAGE` setting, unless it is explicitly stated (which for a lot of users it is not), subsequently breaking the function app. Further I can report that it is not only explicit changes to app_settings that results in the removal, implicit changes, like setting application_insights_connection_string in site_config produces the same behavior.

```
Terraform will perform the following actions:

  # azurerm_linux_function_app_slot.xxxxxxxxxxxxxxx will be updated in-place
  ~ resource "azurerm_linux_function_app_slot" "xxxxxxxxxxxxxx" {
        id                                 = "xxxxxxxxxxxxxxxxxxxxxxxxxxx"
        name                               = "staged"
        tags                               = {
            "environment" = "stage"
        }
        # (25 unchanged attributes hidden)



      ~ site_config {
          - application_insights_connection_string        = (sensitive value)
            # (33 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

![image](https://user-images.githubusercontent.com/10773178/199932963-f0e86ac7-8b50-45c7-ae14-181d581913e6.png)


This behavior is **not** present in the deprecated azurerm_function_app resource. 
 
Looking at the terraform states, I can see that `WEBSITE_RUN_FROM_PACKAGE` is not tracked, which I guess is why it doesn't show up in the diff, and also why adding the ignore_changes makes no difference.

**Comment by darren-kay** [comment]
Even if I use the lifecycle/ignore for the app settings it still clears them. Not sure why the 'ignore' does not work either.

We cannot use Terraform to deploy updates if there is a function in the resources as it breaks deployments.

**Comment by Dergons** [comment]
Also I don't understand the above discussion. How can it be "by-design" that azurerm removes a vital app setting without expressing that in the plan, nor giving us the ability to ignore changes on that setting?

And if that is "by-design" why does it do that only with the "WEBSITE_RUN_FROM_PACKAGE"? We have several app settings that are set by our code deployment that we can ignore and it works just fine.

**Comment by MHarutunian** [comment]
I agree, the issue is quite critical, maybe I was not stern enough in my communication.

We recently updated our `terraform` and `azurerm` versions to v1.3.4 and 3.30.0 respectively, and now the previous workaround also does not work reliably anymore, because setting up the Function App for the first time now produces the error that I expected previously:
```
│ Error: Linux Function App: (Site Name "func-foo" / Resource Group "rg-foo") not found
│
│   in data "azurerm_linux_function_app" "existing":
│   33: data "azurerm_linux_function_app" "existing" {
│
│ Linux Function App: (Site Name "func-foo" / Resource Group "rg-foo") not found
```
I mentioned in an earlier comment that I didn't understand how it was working in the first place, but @xiaxyi mentioned that it would work. This is no longer the case, so now there isn't even a workaround (which was not really a solution in the first place, to be honest).

**Comment by Dergons** [comment]
So our APIs broke the other day when updating the provider, there was a new default setting set for cors which triggered a change that in turn wiped the setting again.

@xiaxyi This cannot possibly be right.
@jackofallops I can see that you did the implementation of the PR @MHarutunian mentioned above. IDK if that is truly the culprit, but it seems plausible considering the subject matter.

**Comment by md-nable** [comment]
I am facing the same issue.
For me setting required settings explicitly in code also does not work as they disappear after apply.

    "WEBSITE_ENABLE_SYNC_UPDATE_SITE"     = "true"
    "WEBSITE_RUN_FROM_PACKAGE"            = "1"
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "true"

Is there any valid workaround?

**Comment by digital-raver1** [comment]
I am facing the same issue, there is an additional challenge:
If I am adding WEBSITE_RUN_FROM_PACKAGE = 1 or else adding WEBSITE_RUN_FROM_PACKAGE = "notempty" and
lifecycle->ignore_changes to Terraform. The CD pipeline fails to deploy the code with following error.
"2022-12-29T13:40:07.1629115Z ##[error]Error: Error: Failed to deploy web package to App Service. Error: Request timeout: /api/zipdeploy?isAsync=true&deployer=VSTS_ZIP_DEPLOY_FUNCTIONS_V1_"

**Comment by jack-ev** [comment]
For me using lifecycle.ignore_changes works if I remove "WEBSITE_RUN_FROM_PACKAGE" from app_settings and have it in ignore_changes. Deployed function from cicd and then terafform apply stopped override package uri in app_settings.

**Comment by BostjanBozic** [comment]
I can confirm this is still not working and I would agree this is a major bug. We are deploying function code using DevOps `AzureFunctionApp@1` action, yet Function App itself is deployed using Terraform. We are not specifying `WEBSITE_RUN_FROM_PACKAGE` parameter in there and we also include `app_settings` in `ignore_changes`.
```
  lifecycle {
    ignore_changes = [
      app_settings,
      sticky_settings,
      tags["hidden-link: /app-insights-conn-string"],
      tags["hidden-link: /app-insights-instrumentation-key"],
      tags["hidden-link: /app-insights-resource-id"]
    ]
  }
```
What I tried today is:
* deploy function code using DevOps action
* run `terraform apply`
* check changes to function - only reported change was following
```
~ site_config {
            # (34 unchanged attributes hidden)

          + cors {
              + support_credentials = false
            }

            # (1 unchanged block hidden)
        }
```
* check Function app activity log within Azure portal, where you can see that `properties.appSettings["WEBSITE_RUN_FROM_PACKAGE"]` has been deleted

When it comes to versions, I am using following:
* Terraform v1.3.7
* Azurerm Terraform provider v3.40.0

**Comment by fabianboerner** [comment]
This is still open, we currently implementing this provider would be sad if this still breaks the function app

**Comment by michaltalaga** [comment]
still broken as of today

**Comment by philippeckelintive** [comment]
We've been facing this issue for a while and thought of using the [azapi provider](https://registry.terraform.io/providers/Azure/azapi/latest/docs) just for the `app_settings` part.  

And we stumbled upon this [example](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_and_update_appsettings/main.tf) which is indeed fixing the issue. 

`app_settings` part is now covered by `azapi` provider and any change there does not break the existing function code.

Some remarks on the linked example code:

* The data source from [line 53](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_and_update_appsettings/main.tf#L53) - [line 58](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_and_update_appsettings/main.tf#L58) is not really required and therefore [line 67](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_and_update_appsettings/main.tf#L67) can be replaced by 
```hcl
resource_id = "${azurerm_linux_function_app.test.id}/config/appsettings"
```
* The [properties](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_and_update_appsettings/main.tf#L85) might contain secrets which would be disclosed on an `terraform plan`; so I would suggest using [sensitive function](https://developer.hashicorp.com/terraform/language/functions/sensitive) here.
* Similar issue is on the [response_export_values](https://github.com/Azure/terraform-provider-azapi/blob/main/examples/Microsoft.Web/list_and_update_appsettings/main.tf#L92) which is basically showing the whole `app_settings` including secrets; I would suggest to replace `["*"]` with `[]` here to not show any values at all.

Hope this helps ...

**Comment by obesser** [comment]
For some reason `WEBSITE_RUN_FROM_PACKAGE` is not saved to the state at all, while other custom app settings do, even when they are not defined in the terraform configuration file. This is the same issue as #17123 

The implication of this is that the setting is deleted on each apply that changes **something**, even a setting outside of the `app_settings` block, and even when the entire `app_settings` is in `ignore_changes`.

**Comment by Eagdra** [comment]
We also having this issue ...

**Comment by Dergons** [comment]
It would be great to get this fix released so we can get rid of the workaround we have currently that is causing circular dependencies in our configuration

**Comment by smokedlinq** [comment]
Any idea why an `ignore_changes` doesn't working `app_settings.WEBSITE_RUN_FROM_PACKAGE`?

**Comment by vivaladan** [comment]
I have dozens of functions and I just changed a variable used as an app setting in all of them. The TF run ***and I really need to emphasis the danger here*** because only showed the change to the intended setting and yet it took down *`every`* *`single`* *`function`* because it silently removed the WEBSITE_RUN_FROM_PACKAGE. As others here have said, it was explicitly in the ignore_changes.

- It should ABSOLUTELY show in the plan that it's wanting to remove it
- When ignore_changes is present it should ignore the setting

**Comment by Sefriol** [comment]
According to @jackofallops

Removal of lines https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.73.0/internal/services/appservice/linux_function_app_resource.go#L1291-L1295
(version tagged) should fix the issue.

I guess this works in the `azurerm_windows_function_app`. So that could be a possible intermediate alternative.

**Comment by marciobarbato** [comment]
Can we have this prioritized guys, please ?
We unfortunately hit that bugged yesterday and wiped function on prod environment

**Comment by darren-kay** [comment]
> Can we have this prioritized guys, please ? We unfortunately hit that bugged yesterday and wiped function on prod environment

Over a year later and multiple proposed and submitted solutions it is quite clear that Hashicorp are not interested in supporting us or Azure.

**Comment by Hrolgar** [comment]
I have this bug now, anyone know of a fix for it?

**Comment by marcia-schulman** [comment]
Pull request was closed but this is still a critical issue for many of us. Please fix!

**Comment by gioleppe** [comment]
I opened a new [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/24848), which should fix the issue. 
I tried the fix on my subscription and it worked perfectly: you can now safely ignore the WEBSITE_RUN_FROM_PACKAGE from lifecycle ignore_changes. 
Thanks @jackofallops for the analysis on the original PR 👍

**Comment by hilarudeens** [comment]
Tested below things in terraform == 1.5 and Azurerm == 3.92

Overall, the latest terraform is trying to be smart which is confusing developer. Terraform is only tracking settings which are mentioned in `app_settings { ... }` section and it doesn't care any other settings which are coming from out-site of terraform code.

The solution is, let terraform know about WEBSITE_RUN_FROM_PACKAGE by adding as follows,
```
  # Following configuration added to terraform tracking
  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE"       = 1
  }
```

and tell terraform, not to change settings by following ignore
```
  lifecycle {
    ignore_changes = [
      app_settings["WEBSITE_RUN_FROM_PACKAGE"]
    ]
  }
```
