### ISSUE TITLE
Support for Event Hubs Schema Registry

### ISSUE THREAD

**Issue by ivanobulo** [hashicorp/terraform-provider-azurerm#17095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for Azure Schema Registry ([link](https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview))

### New or Affected Resource(s)/Data Source(s)

azurerm_eventhub_schema_group

### Potential Terraform Configuration

```hcl
resource "azurerm_eventhub_schema_group" "mygroup" {
  name = "MyGroup"
  schema_type = "Avro"
  schema_compatibility = "Backward"
  eventhub_namespace = "foobar.servicebus.windows.net"
}
```

### References

https://docs.microsoft.com/en-us/azure/event-hubs/schema-registry-overview

**Comment by xiaxyi** [comment]
pr:https://github.com/hashicorp/terraform-provider-azurerm/pull/17635

**Comment by xiaxyi** [comment]
Hi @ivanobulo Good day, the feature is available in Terraform now, can you please check and see if it satisfies your requirements?

feel free to let me know if there is anything needed.

**Comment by ivanobulo** [comment]
It's great! Thanks

**Comment by xiaxyi** [comment]
Thanks @ivanobulo for the feedback, glad to see it works! Is it ok for us to close this issue or do you have any other question that I can help to address?

**Comment by ivanobulo** [comment]
You may close it, thanks 😊

**Comment by rcskosir** [comment]
Closing as noted above by author.
