### ISSUE TITLE
policy_definition_id in azurerm_management_group_policy_remediation Not Working

### ISSUE THREAD

**Issue by Eslam10** [hashicorp/terraform-provider-azurerm#17096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_remediation

### Terraform Configuration Files

```hcl
resource "azurerm_management_group_policy_remediation" "main" {
  name                 = "test"
  policy_assignment_id = "/providers/Microsoft.Management/managementGroups/xxx/providers/Microsoft.Authorization/policyAssignments/d70f6f72a0e64d11a63a96b2"
  management_group_id  = "/providers/Microsoft.Management/managementGroups/xxx"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/91cb9edd-cd92-4d2f-b2f2-bdd8d065a3d4"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

A new remediation task should be created for this policy definition from the policy set definitions. 

### Actual Behaviour

Terraform apply succeeded, a new TF resource created.
From Azure portal, I was not able to find the remediation task created, also the policy still shows as non-compliant.  
Also "policy_definition_id" argument accepts any string after "policyDefinitions/" which means that it is not actually checking the policy definition id !

### Steps to Reproduce

1. Assign policy set definition to one of Azure Management Groups.
2. Use azurerm_management_group_policy_remediation to create a remediation task for one of the policy definitions under the policy set-definition. 
3. Apply the changes. 
4. Check if a policy remediation task has been created.

**Comment by Eslam10** [comment]
As per the activity log request body comparison between a manual task and a task created by TF, the `policyDefinitionReferenceId` in the TF task takes the `policy_definition_id`, this should be the `policyDefinitionReferenceId`, same as the TF resource for azurerm provider versions < 3.0

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue.
The property validation only checks whether the format is correct. So it's the expected behaviour.
The `policyDefinitionReferenceId` is the name in rest api. The `policy_definition_id` is the name in TF and it mapps to `policyDefinitionReferenceId`. So it's expected.

**Comment by Eslam10** [comment]
@neil-yechenwei , thanks for the answer, indeed the `policy_definition_id` is a different value than the `policyDefinitionReferenceId` but based on my testing, it didn't map to the `policyDefinitionReferenceId` since the remediation task was not created.
You may be able to test it by assigning a policy set-definition and create a remediation task for one of the included policies.

**Comment by Eslam10** [comment]
Another point, it is also possible to include same policy definition multiple times in the same policy set definition, in this case the unique value will be the `policyDefinitionReferenceId`. If the resource is only taking `policy_definition_id`, how could we distinguish which policy we need to create a remediation task for ?

**Comment by FBraesemann** [comment]
Hi, we have this problem even with "azurerm_subscription_policy_remediation".
Terraform and Azure API doesn't report an issue and ran successfully.
When creating a remediation task with Powershell, then the Parameter "policyDefinitionReferenceId" is used. This requires the name of the Remediation task without the complete path.
Incorrect: "/providers/Microsoft.Management/managementGroups/<ManagementGroup>/providers/Microsoft.Authorization/policyDefinitions/<PolicyDefinitionName>"

Correct: <PolicyDefinitionName>

The TF Module doesn't accept only the <PolicyDefinitionName> as a value for parameter "policy_definition_id".
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/99398721/172841546-b8c085e2-9ca8-448c-85f7-98406c628335.png">


I think this issue is present on all terraform ressource modules for remediation.

**Comment by rdvansloten** [comment]
I am also having this issue.

+1

**Comment by jschwellnus92** [comment]
I am also having this issue. Terraform is reporting remediation created successfully yet there is no resulting remediation task in Azure.

**Comment by fabian-ro** [comment]
I can confirm the issue for `azurerm_management_group_policy_remediation` when assigning a policy set and trying to create remediation tasks for the contained policies.

**Comment by fabian-ro** [comment]
I think I found a workaround: In the `azurerm_policy_set_definition`, in the `policy_definition_reference` blocks, set the `reference_id` to the same value as `policy_definition_id` (e. g. `/providers/Microsoft.Authorization/policyDefinitions/1f725891-01c0-420a-9059-4fa46cb770b7`).

And then in the `azurerm_subscription_policy_remediation`, you can also use the `policy_definition_id`. Terraform doesn't throw any parsing errors and Azure can identify the respective policy correctly.

I don't see any drawback in setting the `policy_definition_id` as `reference_id` in the `azurerm_policy_set_definition`. Or do I miss anything?

**Comment by Eslam10** [comment]
@fabian-ro , in some cases, I used the same policy definition to create a set definition. 
For instance, I created a set-definition contains multiple (same) policy definition of inherit a tag, as the policy definition accepts only one tag input parameter. In this case, reference_id should be different and descriptive.

**Comment by JustinGrote** [comment]
Hopefully #18037  will get merged soon, looks to fix the issue for me, as I have an initiative for multiple tag inherits that has separate reference IDs for each tag but the same policy definition ID for each.
