### ISSUE TITLE
Not working proper as documented

### ISSUE THREAD

**Issue by eliyazsyed22** [hashicorp/terraform-provider-azurerm#17093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.9.0.

### AzureRM Provider Version

3.9.0.

### Affected Resource(s)/Data Source(s)

azurerm_kusto_script

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_kusto_cluster" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }
}

resource "azurerm_kusto_database" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cluster_name        = azurerm_kusto_cluster.example.name
}

resource "azurerm_storage_account" "example" {
  name                     = "example"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "setup-files"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "example" {
  name                   = "script.txt"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source_content         = ".create table MyTable (Level:string, Timestamp:datetime, UserId:string, TraceId:string, Message:string, ProcessId:int32)"
}

data "azurerm_storage_account_blob_container_sas" "example" {
  connection_string = azurerm_storage_account.example.primary_connection_string
  container_name    = azurerm_storage_container.example.name
  https_only        = true

  start  = "2017-03-21"
  expiry = "2022-03-21"

  permissions {
    read   = true
    add    = false
    create = false
    write  = true
    delete = false
    list   = true
  }
}

resource "azurerm_kusto_script" "example" {
  name                               = "example"
  database_id                        = azurerm_kusto_database.example.id
  url                                = azurerm_storage_blob.example.id
  sas_token                          = data.azurerm_storage_account_blob_container_sas.example.sas
  continue_on_errors_enabled         = true
  force_an_update_when_value_changed = "first"
}
```

### Debug Output/Panic Output

```shell
│ Error: waiting for creation of "Script: (Name \"jedivac\" / Database Name \"jeff\" / Cluster Name \"jeffbejo\" / Resource Group \"example\")": Code="BadRequest" Message="[BadRequest] Could not download database script '{0}'. Please make sure the provided SAS is valid, the blob exists, and access to the Storage Account is not limited."
│
│   with azurerm_kusto_script.example,
│   on main.tf line 68, in resource "azurerm_kusto_script" "example":
│   68: resource "azurerm_kusto_script" "example" {
│
```

### Expected Behaviour

it should create a script and should upload to database but giving error on creating script

### Actual Behaviour

│ Error: waiting for creation of "Script: (Name \"jedivac\" / Database Name \"jeff\" / Cluster Name \"jeffbejo\" / Resource Group \"example\")": Code="BadRequest" Message="[BadRequest] Could not download database script '{0}'. Please make sure the provided SAS is valid, the blob exists, and access to the Storage Account is not limited."
│
│   with azurerm_kusto_script.example,
│   on main.tf line 68, in resource "azurerm_kusto_script" "example":
│   68: resource "azurerm_kusto_script" "example" {
│

### Steps to Reproduce

terraform apply

**Comment by tombuildsstuff** [comment]
hi @eliyazsyed22 

Thanks for opening this issue.

Taking a look through this appears to be a question regard to the Terraform Configuration being used, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
