### ISSUE TITLE
`azurerm_automation_job_schedule` documentation Argument Reference missing required `schedule_name`

### ISSUE THREAD

**Issue by sudo-edwardwu** [hashicorp/terraform-provider-azurerm#17105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_job_schedule

### Terraform Configuration Files

```hcl
resource "azurerm_automation_job_schedule" "start_vm" {
  resource_group_name     = azurerm_resource_group.rg.name
  automation_account_name = azurerm_automation_account.account.name
  runbook_name            = azurerm_automation_runbook.start_vm.name
}
```

### Debug Output/Panic Output

```shell
│ Error: Missing required argument
│ 
│   on main.tf line 201, in resource "azurerm_automation_job_schedule" "start_vm":
│  201: resource "azurerm_automation_job_schedule" "start_vm" {
│ 
│ The argument "schedule_name" is required, but no definition was found.
```

### Expected Behaviour

Able to create an automation job schedule

### Actual Behaviour

`terraform validate` and `terraform plan` failed, `schedule_name` is actually a required argument. Once that is added, code can execute. This information is currently missing on [documentation page](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_job_schedule)

Below code would work:
```hcl
resource "azurerm_automation_job_schedule" "start_vm" {
  schedule_name           = azurerm_automation_schedule.start_vm.name
  resource_group_name     = azurerm_resource_group.rg.name
  automation_account_name = azurerm_automation_account.account.name
  runbook_name            = azurerm_automation_runbook.start_vm.name
}
```

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by catriona-m** [comment]
Thanks for this @sudo-edwardwu, looks like this has now been fixed in the linked PR so this can be closed. Thanks!
