### ISSUE TITLE
content_share_force_disabled and some key-value pairs in app_settings won't be saved in TF state

### ISSUE THREAD

**Issue by petliura** [hashicorp/terraform-provider-azurerm#17123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "example" {
    name                = "example-app-service-plan"
    resource_group_name = "my-rg"
    location            = "centralus"
    os_type             = "Windows"
    sku_name            = "P1v3"
}

resource "azurerm_windows_function_app" "example" {
    name                = "example-windows-function-app"
    resource_group_name = "my-rg"
    location            = "centralus"
    storage_account_name         = "mystorageaccountNNN"
    service_plan_id              = azurerm_service_plan.example.id
    content_share_force_disabled = true

    site_config {}

    app_settings = {"WEBSITE_HEALTHCHECK_MAXPINGFAILURES" = "4"}
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Settings 
content_share_force_disabled = true 
and
app_settings = {"WEBSITE_HEALTHCHECK_MAXPINGFAILURES" = "4"}
are set and preserved in the Terraform state

### Actual Behaviour

bash> terraform state show module.deployment.azurerm_windows_function_app.example
# module.deployment.azurerm_windows_function_app.example:
resource "azurerm_windows_function_app" "example" {
    **app_settings                      = {}**
    builtin_logging_enabled           = true
    client_certificate_enabled        = false
    client_certificate_mode           = "Optional"
    **content_share_force_disabled      = false**
...
}

### Steps to Reproduce

1. set content_share_force_disabled = true and app_settings = {"WEBSITE_HEALTHCHECK_MAXPINGFAILURES" = "4"} in the config file
2. execute terraform apply
3. check terraform state for the deployed resource (the state won't persist changes supplied in the configuration)

**Comment by xiaxyi** [comment]
@jackofallops I noticed the property is not set back to app setting in read function, instead, is referred by another property `health_check_eviction_time_in_min`, below is the code:"
```
case "WEBSITE_HEALTHCHECK_MAXPINGFAILURES":
			i, _ := strconv.Atoi(utils.NormalizeNilableString(v))
			m.SiteConfig[0].HealthCheckEvictionTime = utils.NormaliseNilableInt(&i)

```
any ideas about it, shall we set the property in the app_setting as user explicitly sets it.

**Comment by petliura** [comment]
Any comments/updates on the issue with the ****content_share_force_disabled**** parameter not being persisted in the state?

**Comment by xiaxyi** [comment]
Thanks @petliura for the comments, currently, I'm reviewing the whole `app_setting` block, it may takes some times. I will update you once I have any progress. Thanks for your understanding, feel free to let me know if there is anything needed.

**Comment by petliura** [comment]
@xiaxyi, just a quick follow up: Are you guys addressing the same issues with azurerm_linux_function_app and azurerm_windows_function_app resource blocks as a part of this effort? Or do you need a separate issue raised for the functions?
Thanks!
