### ISSUE TITLE
SQL Server Public Access defaulting to disabled. need it to set to "Selected Networks" to enable firewall rules

### ISSUE THREAD

**Issue by KezHalls** [hashicorp/terraform-provider-azurerm#17149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

0.14

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "this" {
  provider                     = azurerm.environment
  name                         = var.sql_server_name
  resource_group_name          = var.resource_group_name
  location                     = var.location
  version                      = var.sql_version
  administrator_login          = var.sql_admin
  administrator_login_password = var.sqladminpwd
  public_network_access_enabled = false
  tags                         = var.tags #merge(var.tags, var.tags_sql)
  
}
resource "azurerm_sql_active_directory_administrator" "this" {
  server_name         = azurerm_mssql_server.this.name
  resource_group_name = var.resource_group_name
  login               = data.azuread_group.databaseadmin.display_name
  tenant_id           = var.tenant_id
  object_id           = data.azuread_group.databaseadmin.object_id
}

resource "azurerm_private_endpoint" "this" {
  provider            = azurerm.environment
  name                = "pvt_endpoint_${var.sql_server_name}"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = data.azurerm_subnet.restricted.id

  private_service_connection {

    name                           = "privatesvc_conn_${var.sql_server_name}"
    is_manual_connection           = "false"
    private_connection_resource_id = azurerm_mssql_server.this.id
    subresource_names              = ["sqlServer"]
  }

  depends_on                       = [azurerm_mssql_server.this]
  
  lifecycle {
    ignore_changes = [subnet_id]
  }

}

resource "azurerm_private_dns_a_record" "private_dns_a_record" {
  provider            = azurerm.sharedservice
  name                = azurerm_mssql_server.this.name
  zone_name           = var.private_dns_zone_name
  resource_group_name = var.resource_group_dns_zone
  ttl                 = 300
  records             = [data.azurerm_private_endpoint_connection.connection.private_service_connection.0.private_ip_address]
}

resource "azurerm_mssql_firewall_rule" "this" {
 #for_each = var.netskope_ip_address_range
 for_each = { for x in var.netskope_ip_address_range: x.name => x }

 name             = each.value.name
 server_id        = azurerm_mssql_server.this.id
 start_ip_address = each.value.range_min
 end_ip_address   = each.value.range_max
}
```

### Debug Output/Panic Output

```shell
has business info... so not if I should provide this
```

### Expected Behaviour

SQL Server networking tab "Public Access" should be set to "Selected Networks" and Firewall rules populated.

### Actual Behaviour

SQL Server networking tab "Public Access" is set to "Disabled" and causing an error when trying to add firewall rules

**Comment by sinbai** [comment]
Hi @KezHalls thank you for opening this issue here.

Per the terraform configuration provided, the `public_network_access_enabled` is set to false in the terraform configuration below, seems it causes the SQL Server networking tab "Public Access" to be set to "Disabled". Could you please set it to true to see whether it works? It is worth mentioning that the `public_network_access_enabled` default to true in the latest version of terraform provider.

```
resource "azurerm_mssql_server" "this" {
  provider                     = azurerm.environment
  name                         = var.sql_server_name
  resource_group_name          = var.resource_group_name
  location                     = var.location
  version                      = var.sql_version
  administrator_login          = var.sql_admin
  administrator_login_password = var.sqladminpwd
  public_network_access_enabled = false
  tags                         = var.tags #merge(var.tags, var.tags_sql)
  
}
```

**Comment by sinbai** [comment]
I could not repro the issue with the following terraform configuration. Could you repro with it? Could you compare it to yours and let me know the detailed repro terraform configuration and repro steps to help repro/troubleshooting? 

```
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	   version = "3.8.0"
    }
  }
}

resource "azurerm_resource_group" "test" {
  name     = "rg-sqlserver-sample"
  location = "eastus"
}


resource "azurerm_mssql_server" "test" {
  name                         = "sqlserver-sample"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  public_network_access_enabled = true
  administrator_login          = "missadministrator"
  administrator_login_password = "thisIsKat11"
  
  tags = {
    ENV = "Test"
  }
}
```

After running terraform apply, the following result is expected in the Azure Portal:

![image](https://user-images.githubusercontent.com/39109137/172748829-44a081aa-8346-452d-888d-0cde1dcc4c63.png)

**Comment by KezHalls** [comment]
thanks for your help.  I realised by looking at your examples that I hadn't actually tried via the GUI.  This did not work either and I later found it was a policy setting.  
Thanks again.  Please close

**Comment by KezHalls** [comment]
This works.  it was policy setting stopping it.
