### ISSUE TITLE
azurerm_cognitive_account needs to support Cognitive Language Service

### ISSUE THREAD

**Issue by molson504x** [hashicorp/terraform-provider-azurerm#17169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure is sunsetting QnA Maker in 2025, and replacing it with Cognitive Language Service.  The azurerm_cofnitive_account module needs to have support added for this Language Service resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_account

### References

* https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/overview
* https://docs.microsoft.com/en-us/azure/cognitive-services/qnamaker/overview/overview
> The QnA Maker service is being retired on the 31st of March, 2025. A newer version of the question and answering capability is now available as part of [Azure Cognitive Service for Language](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/). For question answering capabilities within the Language Service, see [question answering](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/overview). Starting 1st October, 2022 you won’t be able to create new QnA Maker resources. For information on migrating existing QnA Maker knowledge bases to question answering, consult the [migration guide](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/how-to/migrate-qnamaker).

**Comment by ms-henglu** [comment]
Hi @molson504x ,

Thank you for opening this issue.

I think you can use `kind = "TextAnalytics"` to create a Language service.

**Comment by molson504x** [comment]
@ms-henglu Thanks, I'll give that a try.  Can that be documented somewhere on the module docs?  You can even just have it link to [the microsoft documentation](https://docs.microsoft.com/en-us/azure/cognitive-services/cognitive-services-apis-create-account-cli?tabs=windows#create-a-cognitive-services-resource) if that would be easier.  I'm assuming that what the terraform module is doing is similar to what the az cli is doing.

**Comment by stephybun** [comment]
Closed by #17535
