### ISSUE TITLE
Support for TLS version

### ISSUE THREAD

**Issue by kevinharing** [hashicorp/terraform-provider-azurerm#17165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support the minimum TLS version field in the `azurerm_servicebus_namespace` resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace

### Potential Terraform Configuration

```hcl
resource "azurerm_servicebus_namespace_network_rule_set" "example" {
  namespace_id = azurerm_servicebus_namespace.service_bus.id
  minimum_tls_version  = "1.2"
}
```

### References

https://docs.microsoft.com/en-us/azure/service-bus-messaging/transport-layer-security-configure-minimum-version

**Comment by juan-carlos-valderrama-duque** [comment]
I'm suffering the impact. azurerm_servicebus_namespace configures by default the TLS ver 1.0 so the automation is partiala creating an unnecesary lack in security compliance 👎 Why automate if you must do manual work :-(

**Comment by xiaxyi** [comment]
@kevinharing This is a preview feature, I'll add it to my backlog.

**Comment by truptisatardekar** [comment]
I'm also facing the same issue. Will be great if you could release it soon. Thanks.

**Comment by DaleyKD** [comment]
Definitely waiting on this. Thanks!

**Comment by xiaxyi** [comment]
Hey guys, you can track the status in https://github.com/hashicorp/terraform-provider-azurerm/pull/17805
