### ISSUE TITLE
azurerm_automation_account identity block not recognised

### ISSUE THREAD

**Issue by KezHalls** [hashicorp/terraform-provider-azurerm#17177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

0.14

### Affected Resource(s)/Data Source(s)

azurerm_automation_account

### Terraform Configuration Files

```hcl
resource "azurerm_automation_account" "automation_account" {
    name                        = var.automation_account_name
    location                    = var.location
    resource_group_name         = var.resource_group_name
    sku_name                    = "Basic"
    tags                        = var.tags

    identity {
         type         = "UserAssigned"
         identity_ids = [azurerm_user_assigned_identity.uai.id]
    }
}
```

### Debug Output/Panic Output

```shell
private info
```

### Expected Behaviour

add user to automation identity config

### Actual Behaviour

Throws Error: 
Blocks of type "identity" are not expected here.

### Steps to Reproduce

tried with "=" and without
identity {
and
identity  = {

### References

no

**Comment by wuxu92** [comment]
hi @KezHalls , is `AzureRM Provider Version  0.14` a typo? because the latest azurerm version is 3.9.0 from https://registry.terraform.io/providers/hashicorp/azurerm/latest

**Comment by KezHalls** [comment]
Hi wuxu92.  yes sorry I am using 3.8.0 currently

**Comment by KezHalls** [comment]
once again apologies.  I only recently upgraded to 3.8 so will need to retest.  I will repost once done.

**Comment by KezHalls** [comment]
this now works after upgrading everything.  thanks for your help
