### ISSUE TITLE
Using `terraform import` to import a `azurerm_frontdoor_rules_engine` resource always imports only the ID of the rules engine and fills the rest of the properties and attributes as null

### ISSUE THREAD

**Issue by nexocentric** [hashicorp/terraform-provider-azurerm#17179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_frontdoor_rules_engine

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {}
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.9.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
azurerm_frontdoor_rules_engine.example_rules_engine: Importing from ID "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/thing-thing-thing/providers/Microsoft.Network/frontdoors/thing-thing-thing/rulesengines/customRules"...
azurerm_frontdoor_rules_engine.example_rules_engine: Import prepared!
  Prepared azurerm_frontdoor_rules_engine for import
azurerm_frontdoor_rules_engine.example_rules_engine: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/thing-thing-thing/providers/Microsoft.Network/frontdoors/thing-thing-thing/rulesengines/customRules]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

### Expected Behaviour

Expecting the rules engine JSON in the Terraform state to be populated with the actual values of the rules engine. The following is abbreviated, but due to not knowing what an actual `azurerm_frontdoor_rules_engine` JSON object would look like in the Terraform state file. However, would expect something similar to the JSON object below.

```
{
  "mode": "managed",
  "type": "azurerm_frontdoor_rules_engine",
  "name": "example_rules_engine",
  "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
  "instances": [
    {
      "schema_version": 1,
      "attributes": {
        "enabled": true,
        "frontdoor_name": "Name-of-Frontdoor-Resource",
        "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/thing-thing-thing/providers/Microsoft.Network/frontdoors/thing-thing-thing/rulesengines/cacheRules",
        "location": "Completed-Location",
        "name": "Completed-Name",
        "resource_group_name": null,
        "rule": [
          "rule 1"...,
          "rule 3"...,
          "rule 4"...,
          "rule 5"...,
          "rule 6"...,
          ...,
        ],
        "timeouts": {
          "create": null,
          "delete": null,
          "read": null,
          "update": null
        }
      },
      "sensitive_attributes": [],
      "private": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000=="
    }
  ]
}
```

### Actual Behaviour

Even though a rules engine configuration exists for this resource
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/3537237/172736700-f639f958-30be-4892-8d60-78f85b809fab.png">
the following is recorded to the Terraform state file:

```
{
  "mode": "managed",
  "type": "azurerm_frontdoor_rules_engine",
  "name": "example_rules_engine",
  "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
  "instances": [
    {
      "schema_version": 1,
      "attributes": {
        "enabled": null,
        "frontdoor_name": null,
        "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/thing-thing-thing/providers/Microsoft.Network/frontdoors/thing-thing-thing/rulesengines/cacheRules",
        "location": null,
        "name": null,
        "resource_group_name": null,
        "rule": [],
        "timeouts": {
          "create": null,
          "delete": null,
          "read": null,
          "update": null
        }
      },
      "sensitive_attributes": [],
      "private": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000=="
    }
  ]
}
```

### Steps to Reproduce

1. Create a Front Door resource
2. In the Front Door resource create a Rules Engine resource
3. Create a Terraform configuration with an empty rules engine resource and then run `terraform import azurerm_frontdoor_rules_engine.my_engine /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/thing-thing-thing/providers/Microsoft.Network/frontdoors/thing-thing-thing/rulesengines/nameOfRulesEngine`

### Important Factoids

No

### References

No

**Comment by bubbletroubles** [comment]
Routing configuration isn't in the provider yet. That could be the cause. See issue #14884

**Comment by WodansSon** [comment]
The legacy Frontdoor is being retired and is no longer in development.
