### ISSUE TITLE
azurerm_windows_function_app appsetting WEBSITE_NODE_DEFAULT_VERSION is added in every apply even if the function app has the value set

### ISSUE THREAD

**Issue by Ikriva** [hashicorp/terraform-provider-azurerm#17198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.10"
    }
  }
  required_version = ">= 1.1.9"
}

provider "azurerm" {
  features {}
  tenant_id       = var.tenant_id
  subscription_id = var.subscription_id
}

resource "azurerm_resource_group" "default" {
  name     = "error-testing-rg"
  location = "westeurope"
  tags     = var.default_tags
}

resource "azurerm_storage_account" "function_app" {
  name                            = "errortesting"
  resource_group_name             = azurerm_resource_group.default.name
  location                        = azurerm_resource_group.default.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  min_tls_version                 = "TLS1_2"
  allow_nested_items_to_be_public = false
}

resource "azurerm_service_plan" "default" {
  name                         = "error-testing-plan"
  location                     = azurerm_resource_group.default.location
  resource_group_name          = azurerm_resource_group.default.name

  os_type                      = "Windows"
  sku_name                     = "Y1"
}

resource "azurerm_windows_function_app" "default" {
  name                        = "error-testing-func"
  location                    = azurerm_resource_group.default.location
  resource_group_name         = azurerm_resource_group.default.name
  service_plan_id             = azurerm_service_plan.default.id
  storage_account_name        = azurerm_storage_account.function_app.name
  storage_account_access_key  = azurerm_storage_account.function_app.primary_access_key
  functions_extension_version = "~4"
  https_only                  = true

  app_settings = {
    FUNCTIONS_WORKER_RUNTIME       = "node"
    WEBSITE_NODE_DEFAULT_VERSION   = "~16"
  }

  site_config {
    
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/Ikriva/7c2be9a25d4e0a81656fc55f2fe46145
```

### Expected Behaviour

On second `terraform apply`, there should be no changes to be applied.

### Actual Behaviour

![Capture](https://user-images.githubusercontent.com/2535237/173067865-e6d4cee6-5fec-4ae4-809c-f8769357e6dc.PNG)

### Steps to Reproduce

terraform apply x2

**Comment by xiaxyi** [comment]
@jackofallops I noticed the note in the code and suggesting the node version is being collected from the property `windowsFxVersion`, however, just would like to know why didn't we set the property back in app setting, is there any conflict with the windowsFxVersion?
