### ISSUE TITLE
azurerm_api_management fails to apply on 3.10.0 provider

### ISSUE THREAD

**Issue by scott-doyland-burrows** [hashicorp/terraform-provider-azurerm#17206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "hogarth_api_management" {
  depends_on = [azurerm_key_vault_access_policy.user_assigned_managed_identity_001]

  name                          = "${var.opp_grp}-${var.proj_code}-${var.locale}-${var.sn_env}-apim-001"
  location                      = var.location
  resource_group_name           = var.resource_group_name
  publisher_name                = "Hogarth"
  publisher_email               = "hogarth@hogarthww.com"
  public_network_access_enabled = true
  sku_name                      = var.sn_env == "p" ? "Premium_1" : "Developer_1"
  zones                         = var.sn_env == "p" ? [1, 2, 3] : null
  virtual_network_type          = "Internal"

  virtual_network_configuration {
    subnet_id = azurerm_subnet.pwapimgw_apimanagement_subnet.id
  }

  identity {
    type = "SystemAssigned"
  }

  certificate {
    encoded_certificate  = filebase64("../certificates/${var.automation_cert_name}.crt")
    certificate_password = ""
    store_name           = "Root"
  }

  tags = merge(local.tags, {
    hostname    = "${var.opp_grp}-${var.proj_code}-${var.locale}-${var.sn_env}-apim-001"
    serverrole  = "N/A"
    serveros    = "N/A"
    servicename = "api_management"
  })
}
```

### Debug Output/Panic Output

```shell
azurerm_api_management.hogarth_api_management: Still creating... [32m30s elapsed]
azurerm_api_management.hogarth_api_management: Still creating... [32m40s elapsed]
azurerm_api_management.hogarth_api_management: Still creating... [32m50s elapsed]
azurerm_api_management.hogarth_api_management: Still creating... [33m0s elapsed]

Error: waiting for recovery of "Api Management: (Service Name \"hgh-pwapimgw-weuro-d-apim-001\" / Resource Group \"pwapimgw-d-app-rg\")": pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0

  with azurerm_api_management.hogarth_api_management,
  on api_management.tf line 1, in resource "azurerm_api_management" "hogarth_api_management":
   1: resource "azurerm_api_management" "hogarth_api_management" {" {
```

### Expected Behaviour

The APIM resource should apply.

### Actual Behaviour

The apply runs for ~30mins and then fails, however the resource is seen in the Azure portal.

The ~30min runtime is expected.

This worked fine on provider 3.9.0.

It fails on 3.10.0 (which appears to have had changes to the azurerm_api_management resource in it.

### Steps to Reproduce

Setup the terraform code as per above and run an apply.

### Important Factoids

Worked fine on provider 3.9.0

**Comment by cT-m00cat** [comment]
Can confirm this is an issue. Have been trying ALL week to get APIM deployed with terraform and finally found this by googling the error message - it consistently fails on 3.10.0 - apim actually get's created but when the procedure fails my API's which are also part of the deployment (and depend on APIM) are not deployed

**Comment by meilz381** [comment]
I also had this issue. Azure introduces a [soft delete for Azure API Management](https://docs.microsoft.com/en-us/azure/api-management/soft-delete). When the service was not purged the API call to create or update the service will fail. So for future versions, we need an option to enable the purge when the APIM gets deleted or recover the soft-deleted instance.
This problem probably occurs when you deleted the APIM via the UI for some reason.

The workaround for me was to [purge the service manually](https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/deleted-services/purge?tabs=HTTP).

**Comment by cT-m00cat** [comment]
Thanks that is good to know

**Comment by parkerjgit** [comment]
> The workaround for me was to [purge the service manually](https://docs.microsoft.com/en-us/rest/api/apimanagement/current-ga/deleted-services/purge?tabs=HTTP).

can also use purge_soft_delete_on_destroy feature toggle (see https://github.com/hashicorp/terraform-provider-azurerm/pull/12850)

**Comment by parkerjgit** [comment]
Having similar issue with azurerm v3.21.1. APIM Resource gets created, but terraform apply never succeeds, gets stuck creating: `azurerm_api_management.apim: Still creating... [35m32s elapsed]` Let it run for over an hour before forcably terminating with ctrl + c. config is barebones and happend with azurerm v3.2.0 as well.

**Comment by parkerjgit** [comment]
well, creation complete after 1h15m46s. ¯\_(ツ)_/¯

**Comment by VRay27** [comment]
@parkerjgit  Which version did you use finally to deploy without any issue. I am looking for any version above 3.17.0.
The issue exist in 3.17.0

**Comment by abhishekjerry2000** [comment]
Even I am also getting same issue with version 3.25.0, can anyone please help.

**Comment by Joshua-Viewpointe** [comment]
Still experiencing this issue  with 3.30.0  released today. Fails to complete action after 1 hour and processing of other resource deployments is cancelled, yet apim resource appears in RG. I have been purging soft-delete between deployments. 

```
azurerm_api_management.apim: Still creating... [59m1s elapsed]
##[error]The operation was canceled.
```

**Comment by Ruineer** [comment]
Still experiencing this issue with 3.30.0 released today. Fails to complete action after 1 hour and processing of other resource deployments is cancelled, yet apim resource appears in RG. I have been purging soft-delete between deployments.

```
azurerm_api_management.apim: Still creating... [59m1s elapsed]
##[error]The operation was canceled.
```

**Comment by swatilekhapaul** [comment]
Facing the same issue for provider 3.25.0:
│ Error: waiting for recovery of "Api Management: (Service Name \"APIM-DEMO-001\" / Resource Group \"RG--DEV-DEMO01\")": pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0

Is there any workaround for this issue? Same code works in another subscription. Resource is created in azure.

**Comment by jeanpaulsmit** [comment]
> Still experiencing this issue with 3.29.1. Fails to complete action after 1 hour and processing of other resource deployments is cancelled, yet apim resource appears in RG. I have been purging soft-delete between deployments.
> 
> ```
> azurerm_api_management.apim: Still creating... [59m1s elapsed]
> ##[error]The operation was canceled.
> ```

Isn't this a different issue, as the agent running the operation cancels because the 1 hr time limit was hit? 
We've seen the same on the Azure DevOps public build agent, which also just terminates after 1 hr.
It was one of the reasons to move to self hosted agents, where we could customize this.

**Comment by venkatesh-ytp** [comment]
the response did not contain a body: StatusCode=0 for apim in 3.35.0 version can any one help

**Comment by dmicic** [comment]
Same here with v3.36.0. Deployment fails after ~1h4m  with the error  `pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0`

**Comment by godsonsibreyan-cb** [comment]
same with v3.37.0

**Comment by ncliarmnhs** [comment]
Same issue in v3.38.0. 

azurerm_api_management.api_management: Still creating... [35m26s elapsed]

Error: waiting for recovery of "Api Management: (Service Name \apim\" / Resource Group \"front-01\")": pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0

**Comment by prahlad141992** [comment]
same issue with me

**Comment by yossarian04** [comment]
I'm seeing the same issue using 3.31.0

**Comment by samiko-nd** [comment]
same issue here using v3.31.0 - 33m30s later -  waiting for recovery of "Api Management" pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0

**Comment by vishalmamidi** [comment]
Same issue with version = "3.44.1" 
`pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0`

**Comment by carvarr** [comment]
Same issue with version 3.49.0

`waiting for recovery of "Api Management: (Service Name "xxxx") pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0`

any workaround for this ?

**Comment by mjhoole** [comment]
Same issue with version 3.50.0

`waiting for recovery of "Api Management: (Service Name): pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0`

Workaround: Let it fail with this error message (The resource is actually created on failure) and then run a `terraform import [resource.name] [ResourceID]` rerun your apply and it should be happy

**Comment by oocx** [comment]
I also have this problem with 3.66.0.

Terraform still shows "module.api_management.azurerm_api_management.api: Still creating... [1h14m34s elapsed]", even though the api management resource was successfully created.

**Comment by scott-doyland-burrows** [comment]
> I also have this problem with 3.66.0.
> 
> Terraform still shows "module.api_management.azurerm_api_management.api: Still creating... [1h14m34s elapsed]", even though the api management resource was successfully created.

It can take a couple of hours for APIM to deploy (you may see it in the Portal, but it wont be fully deployed).  You need to wait longer - it'll either succeed or fail with the actual error.

3.66.0 is working fine for me

**Comment by oocx** [comment]
> > I also have this problem with 3.66.0.
> > Terraform still shows "module.api_management.azurerm_api_management.api: Still creating... [1h14m34s elapsed]", even though the api management resource was successfully created.
> 
> It can take a couple of hours for APIM to deploy (you may see it in the Portal, but it wont be fully deployed). You need to wait longer - it'll either succeed or fail with the actual error.
> 
> 3.66.0 is working fine for me

In the portal the status is "online", so I assume it was deployed. I was also able to import it with terraform import.

**Comment by fayssal-az** [comment]
hi ! I got this same kind of issue when deploying an api management service

```
Error: waiting for recovery of "Api Management: (Service Name \"hgh-pwapimgw-weuro-d-apim-001\" / Resource Group \"pwapimgw-d-app-rg\")": pollingTrackerPut#checkForErrors: the response did not contain a body: StatusCode=0

  with azurerm_api_management.hogarth_api_management,
  on api_management.tf line 1, in resource "azurerm_api_management" "hogarth_api_management":
   1: resource "azurerm_api_management" "hogarth_api_management" {" {
```

Can anyone help ?
