### ISSUE TITLE
azurerm_machine_learning_workspace not able to use a Data Lake Gen2 (HNS) storage account 

### ISSUE THREAD

**Issue by bdorplatt** [hashicorp/terraform-provider-azurerm#17210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.15.4

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage" {
  account_kind                    = var.sa_kind
  account_replication_type        = var.sa_replication_type
  account_tier                    = var.sa_tier
  allow_nested_items_to_be_public = var.sa_allow_blob_public_access
  is_hns_enabled                  = var.sa_is_hns_enabled #True
  large_file_share_enabled        = var.sa_large_file_share_enabled
  location                        = var.region
  min_tls_version                 = var.sa_min_tls_version
  name                            = "${var.tenant}${var.subscription}${var.sa_name_short}sta"
  resource_group_name             = var.resource_group_name

resource "azurerm_machine_learning_workspace" "aml_wks" {
  application_insights_id = var.ai_id
  key_vault_id            = var.kv_id
  location                = var.region
  name                    = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.aml_name_short}-aml"
  resource_group_name     = var.resource_group_name
  storage_account_id      = var.sa_id

resource "azurerm_storage_data_lake_gen2_filesystem" "datalake_storage_file" {
  name               = "${var.tenant}${var.subscription}${var.syn_name_short}dlsta"
  storage_account_id = var.syn_sa_create == true ? azurerm_storage_account.datalake_storage[0].id : var.sa_id
}

resource "azurerm_synapse_workspace" "synapse_workspace" {
  location                             = var.region
  managed_virtual_network_enabled      = true
  name                                 = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.syn_name_short}-synwks"
  resource_group_name                  = var.resource_group_name
  sql_administrator_login              = var.syn_sql_admin_username
  sql_administrator_login_password     = random_password.syn_sql_password.result
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.datalake_storage_file.id
```

### Debug Output/Panic Output

```shell
Error: waiting for the creation of Workspace: (Name "example-aml" / Resource Group "example-rg"): Code="BadRequest" Message="Cannot use storage with HNS enabled."
```

### Expected Behaviour

Our goal is to deploy Azure Synapse which requires a Data Lake Gen2 (HNS) storage account. The AML Workspace uses the same storage account and cannot be created if the storage account is Gen2. We should be able to create a storage account in advance and have both Azure Synapse and Azure Machine Learning Workspace deploy to it.

### Actual Behaviour

 Currently, it is required to create the storage account without HNS, deploy the AML Workspace and then manually upgrade the storage account in after the deployment.

### Steps to Reproduce

Deploy a Data Lake Gen2 (HNS) storage account in a deployment where AML and Synapse are deployed using that storage account.

**Comment by bdorplatt** [comment]
Some more relevant information. Trying to add a  Gen2 storage account to AML through the portal results in a similar error: **Hierarchical Namespace is not supported**

This doesn't seem right since AML is on the list of supported services for Data Lake Gen2 [https://docs.microsoft.com/en-us/azure/storage/blobs/data-lake-storage-supported-azure-services](url)

**Comment by jamescrowley** [comment]
@bdorplatt you can definitely *access* Gen2 storage from AML (we do) - but perhaps the limitation is using it as the primary storage container for AML?

**Comment by bdorplatt** [comment]
It seemed odd that you could upgrade the default storage account to Gen2 after initial setup and everything still worked. We opened a case with Microsoft and were told that the  recommendation is to have a separate non-HNS default storage account and then only to add HNS-enabled storage accounts additionally while leaving the default storage account in place. What we were doing is unsupported even though it worked so we will adjust our deployment and be using a separate storage account going forward.

[https://docs.microsoft.com/en-us/azure/machine-learning/concept-workspace#resources](url)

 **Neither premium storage nor hierarchical namespaces are supported with the default storage account of the workspace. You can use premium storage or hierarchical namespace with non-default storage accounts.**
