### ISSUE TITLE
azurerm_windows_web_app is unavailable (503) when I set application stack dotnetcore version = v3.0

### ISSUE THREAD

**Issue by JohnBoneJones** [hashicorp/terraform-provider-azurerm#17232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type = "Windows"
  sku_name            = "B1"
}

resource "azurerm_windows_web_app" "example1" {
  name                = "example1z"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    application_stack {
      current_stack  = "dotnetcore"
      dotnet_version = "v3.0"
    }
    ftps_state = "AllAllowed"
  }
  zip_deploy_file = "./deploy/LoginNCCDeploy.zip"
}
```

### Debug Output/Panic Output

```shell
This page isn’t working right nowexample1z.azurewebsites.net didn’t send any data.
ERR_EMPTY_RESPONSE
```

**Comment by xiaxyi** [comment]
@JohnBoneJones This issue is being tracked in https://github.com/hashicorp/terraform-provider-azurerm/issues/16867

**Comment by JohnBoneJones** [comment]
> @JohnBoneJones This issue is being tracked in #16867

And now it's still not fixed yet, right?

**Comment by xiaxyi** [comment]
@JohnBoneJones As I mentioned in that thread, the underlying IIS server have all the dotnet core runtime supported, the property doesn't have an impact on the dotnet core app. I'm still working on a solution from Terraform side, as a workaround, you can consider to set a valid runtime value for .netframeworkversion

**Comment by JohnBoneJones** [comment]
Thank  you for your support

**Comment by xiaxyi** [comment]
Hey @JohnBoneJones , good day! Can you do me a favor which is to confirm if the DotNet core deployment is functioning well for you now? Thanks!

**Comment by xiaxyi** [comment]
Hey @JohnBoneJones , good day! Any update? Thanks!
