### ISSUE TITLE
Editing azurerm_cognitive_account breaks relation with azurerm_search_service

### ISSUE THREAD

**Issue by geremy42** [hashicorp/terraform-provider-azurerm#17239]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_account;azurerm_search_service

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_account" "language" {

  name                  = local.qnamaker_language_name
  location              = azurerm_resource_group.rsg.location
  resource_group_name   = azurerm_resource_group.rsg.name
  kind                  = "TextAnalytics"
  sku_name              = "S"
  custom_question_answering_search_service_id = azurerm_search_service.search.id
  custom_subdomain_name = lower(local.qnamaker_language_name)

  public_network_access_enabled      = false
  
  identity {
    type = "SystemAssigned"
  }

  network_acls {
    default_action             = "Deny"
    ip_rules                   = [var.outbound_ip]
  }
}

resource "azurerm_role_assignment" "language" {
  scope                = "${azurerm_resource_group.rsg.id}/providers/Microsoft.Search/searchServices/${local.search}"
  role_definition_name = "Contributor"
  principal_id         = azurerm_cognitive_account.language.identity.0.principal_id
  depends_on           = [azurerm_cognitive_account.language, azurerm_search_service.search]
}

resource "azurerm_search_service" "search" {
  name                = local.search
  location            = azurerm_resource_group.rsg.location
  resource_group_name = azurerm_resource_group.rsg.name
  sku                 = "standard"

  public_network_access_enabled = false
  allowed_ips         = []
}
```

### Debug Output/Panic Output

```shell
When trying access to existing KB in Search service

Failed to load QnA pairs
QnaRuntimeError: Runtime error.
 - AzureSearchBadState: Unable to connect to Azure search service. Please verify that the Azure search resource in your QnAMaker service is up and running.
 - AzureSearchBadState: Unable to connect to Azure search service. Please verify that the Azure search resource in your QnAMaker service is up and running.
```

### Expected Behaviour

Editing azurerm_cognitive_account resource (IP filtering / SKU, etc) should not break relation with azurerm_search_service (can't browse anymore existing KB)

Doing same thing manually via Azure portal (add/remove IP from filtering) doesn't have any impact on accessing existing KBs

### Actual Behaviour

My goal is to implement "Custom Question Answering" API language in secure way as described here: 
[https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/how-to/network-isolation](url)

Deployment through TF with code above works well (we still have to "sync keys linked to the selected search service at first time).
The problem is : For any changes on Cognitive Account Language resource (like removing IP from Filtering), it breaks relation with Search Service and their existing KBs, which is big issue for a production environment ..

Doing same thing manually via Azure portal (add/remove IP from filtering) doesn't have any impact on accessing existing KBs

```
Failed to load QnA pairs
QnaRuntimeError: Runtime error.
 - AzureSearchBadState: Unable to connect to Azure search service. Please verify that the Azure search resource in your QnAMaker service is up and running.
 - AzureSearchBadState: Unable to connect to Azure search service. Please verify that the Azure search resource in your QnAMaker service is up and running.
```

### Steps to Reproduce

`terraform apply`

### References

[https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/question-answering/how-to/network-isolation](url)

**Comment by ms-henglu** [comment]
Linked to https://github.com/hashicorp/terraform-provider-azurerm/pull/17683

**Comment by ms-henglu** [comment]
Hi @geremy42 ,

This feature has been supported in https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.16.0, would you please give it a try? Thanks!

**Comment by geremy42** [comment]
Hi @ms-henglu ,

Thanks for this update.
Just tried to edit settings of azurerm_cognitive_account resource throuh and it seems working now.

Unfortunately, I got new error for azurerm_cognitive_account creation:
`╷
│ Error: waiting for creation of Account (Subscription: "00000000-1111-2222-3333-444444444444"
│ Resource Group Name: "RSGNAME"
│ Account Name: "ACCOUNTNAME"): unexpected state 'Failed', wanted target 'Succeeded'. last error: %!s(<nil>)
`

![image](https://user-images.githubusercontent.com/39192567/181720616-ce25a413-df7a-43ec-8daa-8936e2208130.png)
