### ISSUE TITLE
Adding a provider (alias) causes terraform apply to recreate every resource from scratch

### ISSUE THREAD

**Issue by ackris** [hashicorp/terraform-provider-azurerm#17242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.3.0

### Affected Resource(s)/Data Source(s)

linux & windows virtual machines, managed disk, NIC, NSG, NIC-NSG association, subnet, vnet, windows virtual machine extension, null resources, shared compute gallery data source

### Terraform Configuration Files

```hcl
terraform {
 required_providers {
  azurerm = {
   source = "hashicorp/azurerm"
   version = "=3.3.0"
  }
 }

 backend "azurerm" {
  storage_Account_definition_goes_here
  ///
 }
}

provider "azurerm" {
 features {}
 skip_provider_registration = true
}

provider "azurerm" {
 features {}
 skip_provider_registration = true
 alias = "aliasA"
 subscription_id = "dfefefdfdsfsdfdfdfdsfsdffdfd" 
}

provider "azurerm" {
 features {}
 skip_provider_registration = true
 alias = "aliasB"
 subscription_id = "skjjdnfdfldnfldnfkldfkldfkld"
}

data "azurerm_Shared_image_version" "shared_rhel78" {
 name = "1.0.0.0"
 image_name = "name of the image"
 gallery_name = "name of the gallery"
 resource_group_name = "name of resource group"
 provider = azurerm.aliasB
}

resource "azurerm_linux_virtual_machine" "linux_vm" {
 source_image_id = data.azurerm_Shared_image_version.shared_rhel78.id
 //rest of definition
}
```

### Debug Output/Panic Output

```shell
Plan: 23 to add, 0 to change and 1 to destroy
```

### Expected Behaviour

I have an ISO image in shared compute gallery of subscription defined in alias B. I have added this alias so that a data source can refer to this alias and inject ISO ID in `source_image_id` in `azurerm_linux_virtual_machine` resource in aliasA subscription.

Ideally, terraform plan should now create only 1 resource- a linux VM refering to aliasB.

### Actual Behaviour

Terraform plan now wants to destroy every resource created before and recreate them. This should not be happening. I don't understand why terraform wants to destroy everything and create from scratch!

### Steps to Reproduce

1) `az logout`
2) `az login` (to refresh the changes after subscription access has been granted)
3) add a new alias definition in provider block.
4) `terraform init`
5) `terraform plan `

### Important Factoids

Running in Azure Central India region.

**Comment by tombuildsstuff** [comment]
hi @ackris 

Thanks for opening this issue.

Taking a look through here this is a question related to Terraform Configuration, since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
