### ISSUE TITLE
AKS: node pools got unexpectedly reimaged to the latest version while terraform plan shown just update the tag

### ISSUE THREAD

**Issue by eissko** [hashicorp/terraform-provider-azurerm#17244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool
azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s" {
  name                = var.aks_name
  resource_group_name = var.resource_group_name
  location            = "West Europe"
  dns_prefix          = var.aks_dns_name
  kubernetes_version  = "1.23.5"
  sku_tier            = "Free"
  node_resource_group = var.aks_managed_rg_name
  api_server_authorized_ip_ranges = var.aks_api_allowed_ip
  linux_profile {
    admin_username = var.vm_user_name
    ssh_key {
      key_data = tls_private_key.aks_ssh.public_key_openssh
    }
  }

  # previous addon_profile block
  http_application_routing_enabled = false
  oms_agent {
    log_analytics_workspace_id = var.aks_log_analytics_workspace_id
  }
  ingress_application_gateway {
    gateway_id = var.application_gateway_id
  }

  default_node_pool {
    name                         = "aksnodepool"
    vm_size                      = "Standard_D2s_v4"
    enable_auto_scaling          = true
    vnet_subnet_id               = var.aks_vnet_subnet_id
    max_count                    = "6"
    min_count                    = "2"
    zones                        = ["1","2"]
    os_disk_type                 = "Managed"
    max_pods                     = "30"
    only_critical_addons_enabled = true
    orchestrator_version         = "1.23.5"
    os_disk_size_gb              = "128"
    enable_host_encryption       = false
  }

  identity {
    type = "SystemAssigned"
  }

  role_based_access_control_enabled = var.aks_enable_rbac

  network_profile {
    network_plugin      =  var.aks_network_plugin 
    dns_service_ip      =  var.aks_dns_service_ip 
    docker_bridge_cidr  =  var.aks_docker_bridge_cidr 
    service_cidr        =  var.aks_service_cidr
    outbound_type       =  "userDefinedRouting"
  }
  tags = local.tags
}

resource "azurerm_kubernetes_cluster_node_pool" "userpool" {
  name                  = var.node_pool_name
  kubernetes_cluster_id = azurerm_kubernetes_cluster.k8s.id
  vnet_subnet_id        = var.vnet_id
  vm_size               = "Standard_D16s_v4"
  mode                  = "User"
  max_pods              = "40"
  zones                 = ["1","2"]
  os_disk_type          = "Managed"
  enable_auto_scaling   = true
  max_count             = "12"
  min_count             = "1"
  node_count            = null
  os_type               = "Managed"
  os_disk_size_gb       = "128"
  orchestrator_version  = "1.23.5"
  enable_host_encryption = false

  tags = local.tags
  lifecycle {
      ignore_changes = [
      tags
    ]
  }
}
```

### Debug Output/Panic Output

```shell
No debug or panic output.
```

### Expected Behaviour
The terraform plan is axiom in deployment. When plan shows only update the tag. Apply should only apply the tag a not upgrade the node pools images to the latest version.

### Actual Behaviour
The terraform plan showed only update the tag but on apply did different things - upgraded the node pools to latest version. From AKSUbuntu-1804gen2containerd-2022.04.27 to AKSUbuntu-1804gen2containerd-2022.05.24.

### Important Factoids

Upgrade of AzureRM included from 2.99.0 to 3.8.0

**Comment by tombuildsstuff** [comment]
hi @eissko

Thanks for opening this issue.

Taking a look through here unfortunately the issue description above is missing the Terraform Plan/Debug Output above for us to be able to debug this, and the Terraform Resource defined above doesn't show the values used - so we'd need that to be able to look into this, however the Terraform Plan output should show the proposed changes here - would you be able to provide that so we can look into this?

Thanks!

**Comment by eissko** [comment]
@tombuildsstuff Hi Tom, thanks for your attention. I understand. I am going to add missing pieces. I've already updated resource "azurerm_kubernetes_cluster_node_pool" with required values. I am gonna add also "azurerm_kubernetes_cluster" resource. And I forgot to mention very important thing - this was upgrade from 2.99.0 to 3.8.0 AzureRM provider. I followed upgrade recommendation and went through change management - and based on this I adjusted the code to be support by new provider - afterwards, I was happy with new terraform plan which shown only the tag update.

**Comment by eissko** [comment]
This is still in progress. If got some new meaningful findings I will post them

**Comment by eissko** [comment]
@tombuildsstuff  news is that MSFT has withdrawn from their first statement there is a bug and they are rolling it out in all regions.  Anyway, the everything what I described is still relevant and I will summarize below:
1, upgrade from azurerm 2.99.0 to 3.8.0
2, terraform plan shown only update tag as depicted below:
```hcl
  # module.aks[0].azurerm_kubernetes_cluster.k8s will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "k8s" {
        id                                  = "<redacted id>"
        name                                = "<redacted name>"
      ~ tags                                = {
          ~ "terraformModule" = "aks_v2.0.0" -> "aks_v2.1.0"
            # (10 unchanged elements hidden)
        }
        # (23 unchanged attributes hidden)
```
3, from activity log I see this weird behavior where "orchestratorVersion" was firstly set from 1.23.5 to null and then back to 1.23.5 as depicted below:
![image](https://user-images.githubusercontent.com/18594305/174968216-55ad70ea-438e-4e07-b69f-ef872f3040b5.png)

**Comment by eissko** [comment]
hey, hey. new update. 

The support is weird. I like when things are exact but they are not. Just got confirmation it has been fixed. I didn't get exact reference to release notes where it is mentioned. just this - "fix is included in the version v20220626". 

Even though for me looks this release the most suspicious https://github.com/Azure/AKS/releases/tag/2022-07-10.1 where you can see in release notes stated: 

_Bug Fixes
The nodepools will not inherit node resource group tags in az aks create --tags and az aks update --tags scenarios. Because nodepools have az aks nodepool add --tags and az aks nodepool update --tags._
