### ISSUE TITLE
Error creating private endpoint 

### ISSUE THREAD

**Issue by swetharaot22** [hashicorp/terraform-provider-azurerm#17253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
# Web App Private Endpoint
resource "azurerm_private_endpoint" "webpep" {
  name                = local.webpepname
  location            = var.location
  resource_group_name = azurerm_resource_group.resource_group.name
  subnet_id           = azurerm_subnet.webpepsubnet.id

  private_service_connection {
    name                           = local.webpvtpname
    is_manual_connection           = false
    private_connection_resource_id = azurerm_linux_web_app.example.id
    subresource_names              = ["sites"]
  }

  tags = var.tags
}

##############################################
# Storage Account Private Endpoint
##############################################
resource "azurerm_private_endpoint" "stgpep" {
  name                = local.stgpepname
  location            = var.location
  resource_group_name = azurerm_resource_group.resource_group.name
  subnet_id           = azurerm_subnet.mainpepsubnet.id
  
  private_service_connection {
    name                           = local.stgpvtpname
    is_manual_connection           = false
    private_connection_resource_id = azurerm_storage_account.storage.id
    subresource_names              = ["file"]
  }
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Error: creating Private Endpoint "example-stg-endpoint" (Resource Group "example-rg"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidValuesForRequestParameters" Message="Call to Microsoft.Storage/storageAccounts failed. Error message: Values for request parameters are invalid: GroupId: File." Details=[]
with azurerm_private_endpoint.stgpep
on pvtendpoints.tf line 21, in resource "azurerm_private_endpoint" "stgpep":
resource "azurerm_private_endpoint" "stgpep" {
```

### Expected Behaviour

Should create the private end point when subresource is file 

### Actual Behaviour

Fails with invalid values for request parameter error , when subresource is file. Works if I change the subresource to "blob"

**Comment by vivuu1989** [comment]
The issue still persists

**Comment by riemers** [comment]
If your using a premium storage account, that doesn't mean you have a file share. Standard accounts have file shares by default and premium not always. Just adding a reply here for google. Think this can be closed too by now :)

**Comment by RSwarnkar** [comment]
I am facing same issue. Unable to create PE for OpenAI even though as per [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_account) the property `custom_subdomain_name` is optional.

**Comment by tombuildsstuff** [comment]
Closing per @riemers's comment above, since this is a configuration question rather than a bug in the provider
