### ISSUE TITLE
sku_name Y1 in azurerm_service_plan is missing?

### ISSUE THREAD

**Issue by kyohei-ts** [hashicorp/terraform-provider-azurerm#17257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.4

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "app_service_plan_1" {
  name                = "app_service_plan_1"
  resource_group_name = azurerm_resource_group.rg_1.name
  location            = "Japan East"
  os_type             = "Linux"
  sku_name            = "Y1"
}
```

### Debug Output/Panic Output

```shell
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:
```

### Expected Behaviour

> [azurerm\_service\_plan \| Resources \| hashicorp/azurerm \| Terraform Registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan#sku_name)

The documentation didn't mention `Y1` is available value in `sku_name` 

### Actual Behaviour

`Y1` is usable to create app service plan with Dynamic plan.
→ `Y1` should be listed on documentation?

**Comment by stephybun** [comment]
Closed by #17284
