### ISSUE TITLE
azurerm_function_app_function doesn't support multiple files

### ISSUE THREAD

**Issue by crablab** [hashicorp/terraform-provider-azurerm#17266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_function_app_function

### Terraform Configuration Files

```hcl
resource "azurerm_function_app_function" "function" {
  name            = ${var.name}
  function_app_id = azurerm_linux_function_app.function_app.id
  language        = "Python"
  
  // Only deploys a single file: use VSCode Function Deployment for code
  file {
    name    = "__init__.py"
    content = file("${var.function_location}/__init__.py")
  }

  config_json = jsonencode({
    "scriptFile": "__init__.py",
    "bindings": [
      {
        "type": "eventGridTrigger",
        "name": "event",
        "direction": "in"
      }
    ]
  })
  lifecycle {
    ignore_changes = [
      file
    ]
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

It should be possible to specify a zip file of function code, which will contain multiple files. This is particularly important for interpreted languages like Python where you don't provide a compiled artifact, instead a collection of .py and a requirements.txt. 

### Actual Behaviour

If you specify multiple `file` blocks (eg. for the `__init__.py` and `requirements.txt`), the contents of the last file will be used for both file names when uploaded to Azure. 

Alternatively, the function has to be deployed independently of Terraform (eg. with Azure CLI) and then imported back into the state, so the entire function folder can be uploaded as a zip.

**Comment by vg22** [comment]
Is there any plan to fix this?

**Comment by Harry93** [comment]
This issue occurs also in the recent provider version 3.32.0.

**Comment by zakpaw** [comment]
On top of that containers are locked behind premium plan...
Did anyone find a reasonable solution?

**Comment by keiranm** [comment]
Just experienced this issue too. Trying to load a Python function app, but can't do it. Essentially the azurem_function_app_function resource is not fit for purpose without this ability. I'm using provider 3.36.

**Comment by DevSecNinja** [comment]
Same for function apps with PowerShell!

**Comment by mgw6** [comment]
Hi, I am also having this issue. In my case I can deploy a Python function to an app fine, but when the function triggers it fails because the packages that need to be imported are not pip installed. Is there any plan to fix this feature?

When creating Azure functions in VS code, there is one requirements.txt file that is outside of the individual function directories. I think there needs to be some way in the azurerm_function_app to upload the requirements.txt, and tracked for changes.

**Comment by mgw6** [comment]
@Harry93 I agree with all of your comments. 

Currently, it looks the best way to deploy a function in a CI/CD process is with [.zip deployment](https://learn.microsoft.com/en-us/azure/azure-functions/functions-reference-python?tabs=asgi%2Capplication-level&pivots=python-mode-configuration#folder-structure). We followed [this video](https://www.youtube.com/watch?v=P-tZ28RhYE4) to deploy zip functions via Azure DevOps.

**Comment by FaresKi** [comment]
Hi! Sorry if I'm reopening this issue, I just have a question.
I have a project with 3 functions in it, and want to create a single `azurerm_linux_function_app` containing these 3 functions.
Is it interesting to use the file block and refer the entrypoint file, or should I still use the zip compression method? Thanks!
