### ISSUE TITLE
Support for datafactory pipeline `parameters` other than the `string` type

### ISSUE THREAD

**Issue by StealthBlack** [hashicorp/terraform-provider-azurerm#17260]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_pipeline

### Terraform Configuration Files

```hcl
# this is an example code
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_data_factory_pipeline" "example" {
  name            = "example"
  data_factory_id = azurerm_data_factory.example.id
  parameters      = {
      # this parameters expects a map of string to be passed
      "testArray" = {type="Array",defaultValue=[]}
  }
}
```

### Debug Output/Panic Output

```shell
Error: Incorrect attribute value type

   on main.tf line 24, in resource "azurerm_data_factory_pipeline" "example":
   24:   parameters      = {
   25:       # this parameters expects a map of string to be passed
   26:       "testArray" = {type="Array",defaultValue=[]}
   27:   }

 Inappropriate value for attribute "parameters": element "testArray": string required.
```

### Expected Behaviour

I couldn't find anything that could help me with making the parameter into `Array` type. Making the parameter into a `string` is straightforward. Ideally this should take the map and create pipeline parameters with their type and default values.

### Actual Behaviour

The parameters/variables is asking for a `map of string`(Hence the error) . We can make this into a map of string but at that time only string type parameters we can specify. Atleast that's what I could understand. Please correct me if I am wrong!.

#### Suggestion to rectify this
* Make the parameters and the variables in this resource as blocks with content parameter `name` , parameter `type` and default `value`
* We can have `dynamic` block to specify all the parameters.
* I believe similar issue may arise while creating the trigger.  

### Steps to Reproduce

Simply copy paste the code in `main.tf` and run :
```
terraform apply
```

**Comment by ms-henglu** [comment]
Hi @StealthBlack ,

Thank you for opening this issue! Is it duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/13131?

**Comment by StealthBlack** [comment]
> Hi @StealthBlack ,
> 
> Thank you for opening this issue! Is it duplicated with #13131?

I believe it is a duplicate issue. Thank you for bringing it to my notice. 
Since this is my first time creating an issue. I would like you to guide me whether I should keep this open or close it?

**Comment by ms-henglu** [comment]
Hi @StealthBlack - Please close this issue, and you can subscribe https://github.com/hashicorp/terraform-provider-azurerm/issues/13131 to get the latest updates.

**Comment by StealthBlack** [comment]
Thank you,I will do that
