### ISSUE TITLE
Resource ID format for already existing Diagnostic Setting resources is incorrect

### ISSUE THREAD

**Issue by WaitingForGuacamole** [hashicorp/terraform-provider-azurerm#17263]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting 

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "this" {
  name                           = "diag-${var.setting_name}"
  log_analytics_destination_type = var.log_analytics_destination_type
  target_resource_id             = var.target_resource_id
  storage_account_id             = var.storage_account_id
  log_analytics_workspace_id     = var.log_analytics_workspace_id

  dynamic "log" {
    for_each = var.categories
    content {
      category = log.key
      enabled  = log.value.enabled

      retention_policy {
        days    = log.value.retention_days
        enabled = log.value.retention_enabled
      }
    }
  }

  dynamic "metric" {
    for_each = var.metrics
    content {
      category = metric.key
      enabled  = metric.value.enabled

      retention_policy {
        days    = metric.value.retention_days
        enabled = metric.value.retention_enabled
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
If an azurerm_monitor_diagnostic_setting resource already exists on terraform apply, you get a message indicating that it already exists, and to import it, in the format:

Error: A resource with the ID "/subscriptions/<subscriptionid>/resourcegroups/<resourcegroupname>/providers/microsoft.network/virtualnetworks/<vnetname>/providers/microsoft.insights/diagnosticSettings/<diagname>" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.

  with module.prod_subscription_spokes["prod"].module.vnet_diagnostic_setting["spokeName"].azurerm_monitor_diagnostic_setting.this,
  on ../modules/diagnostic_setting/main.tf line 1, in resource "azurerm_monitor_diagnostic_setting" "this":
   1: resource "azurerm_monitor_diagnostic_setting" "this" {

If you use that resource ID, as provided, to terraform import, you receive the following error:

module.prod_subscription_spokes["prod"].module.vnet_diagnostic_setting["spokeName"].azurerm_monitor_diagnostic_setting.this: Importing from ID "/subscriptions/<subscriptionid>/resourcegroups/<resourcegroupname>/providers/microsoft.network/virtualnetworks/<vnetname>/providers/microsoft.insights/diagnosticSettings/<diagsettingname>"...
╷
│ Error: parsing Resource ID "/subscriptions/<subscriptionid>/resourcegroups/<resourcegroupname/providers/microsoft.network/virtualnetworks/<vnetname>/providers/microsoft.insights/diagnosticSettings/<diagsettingname>": Expected the Monitor Diagnostics ID to be in the format `{resourceId}|{name}` but got 1 segments

Note the last part of the resource ID - when a resource is created successfully, it's reported in the format ".../<vnetname>|<diagsettingname>". When the "already exists" message is displayed, it's in the format ".../<vnetname>/providers/microsoft.insights/diagnosticSettings/<diagsettingname>", and so if you use that ID to attempt your import, it will fail with the message above.
```

### Expected Behaviour

Correctly formatted resource ID returned in the original error message, so that the ID could be used directly in a subsequent terraform import command.

### Actual Behaviour

An error message indicating that the resource ID needs to be in the format '{resourceId}|name' is displayed.

### Steps to Reproduce

Create an `azurerm_monitor_diagnostic_setting` resource successfully, but in an overall terraform operation that times out on another resource. Replan/apply, and hope the duplicate resource message appears, Attempt to use the resource ID returned in a `terraform import` statement.

### Important Factoids

no

**Comment by WaitingForGuacamole** [comment]
Additionally, it seems that the resource ID format change causes the target_resource_id property to change in Azure, which means every time I apply, Terraform wants to replace the setting resource, because a resource id change forces replacement.  The only way around this would seem to do a ignore_changes block for target_resource_id?

**Comment by WaitingForGuacamole** [comment]
If I pipe my `terraform apply` output through the following:

``` 
#!/usr/bin/bash
perl -0777 -ne 'print "terraform import '"'"'$2'"'"' '"'"'$1'"'"' \n" while m/Error: A resource with the ID "(.+)" already exists.*\n.*\n.*with (.+)?,/g' | \
perl -ne '$_ =~ s/\/providers\/microsoft.insights\/diagnosticSettings\//|/g; print $_;' | \
tee $1
```

I can get a properly formatted set of `terraform import` statements. The first Perl script transforms the log output into the right sequence and format for an import. The second Perl script removes the offending part of the resource ID for `diagnosticSettings`.

**Comment by onenessboy** [comment]
I am facing same issue... dont know what is correct fix for this

**Comment by WaitingForGuacamole** [comment]
@onenessboy - The correct fix is for the provider to be altered to 1) properly create/destroy the settings resources in the first place (because let's face it, it doesn't, we have to do this a lot), and 2) correctly output the resource ID as Azure displays it, as Terraform needs it for resource imports.

The fix that works? Save the script in my previous post, `chmod +x` it. Call it something like `collect-imports`.

if you capture your `terraform apply` like 

```
terraform plan -no-color -out terraform.tfplan 2&>1 | tee terraform.plan.txt
terraform apply -no-color terraform.tfplan 2&>1 | tee terraform.apply.txt
```

That will save all output and write it to log files.

Then, if you see that your output contains resources that need importing, you run

```
cat terraform.apply.txt | collect-imports | bash
```

That will parse out the imports needed (including the resource ID fix for diagnostics), and run it. If you want to inspect the output first, take off the  `| bash`.

**Comment by teowa** [comment]
Hi @WaitingForGuacamole ,  thanks for opening this issue and provide a workaround💪. I have submited a PR https://github.com/hashicorp/terraform-provider-azurerm/pull/17963 to fix the error message when trying to create a exist resource.
