### ISSUE TITLE
Managed Disk Resource: regression in support of `network_access_policy`

### ISSUE THREAD

**Issue by pierluca** [hashicorp/terraform-provider-azurerm#17267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_disk

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_managed_disk" "example" {
  name                 = "acctestmd"
  location             = azurerm_resource_group.example.location
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"

  tags = {
    environment = "staging"
  }
}


data "azurerm_managed_disk" "this" {
  name                = azurerm_managed_disk.example.name
  resource_group_name = azurerm_managed_disk.example.resource_group_name
}

output "network_access_policy" {
  value = data.azurerm_managed_disk.this.network_access_policy
}

output "disk_access_id" {
  value = data.azurerm_managed_disk.this.disk_access_id
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported attribute
│ 
│  207:       data.azurerm_managed_disk.this.network_access_policy == "AllowPrivate",
│ 
│ This object has no argument, nested block, or exported attribute named "network_access_policy".
```

### Expected Behaviour

The managed disk data source should support both `network_access_policy` and `disk_access_id` readout, as per its documentation and the implementation in #9862

### Actual Behaviour

The attributes are unsupported, and the [code](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/managed_disk_data_source.go
) shows no trace of the additions of #9862

### Steps to Reproduce

- `terraform apply`

### References

This is a regression with respect to #9862

**Comment by myc2h6o** [comment]
Hi @pierluca thanks for opening the issue! These properties were missing in the data source, I've opened #17270 to add them
