### ISSUE TITLE
Add support for encryption scope on storage blobs

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#17272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Specify the encryption scope of the block blob. This feature is to support fined-grained configuration

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_encryption_scope" "blob" {
  name                               = "blobscope"
  storage_account_id                 = azurerm_storage_account.my_account.id
  source                             = "Microsoft.KeyVault"
  infrastructure_encryption_required = true
  key_vault_key_id                   = azurerm_key_vault_key.my_vault.id
}

resource "azurerm_storage_blob" "example" {
  name                   = "my-awesome-content.zip"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source                 = "some-local-file.zip"
  encryption_scope_id    = azurerm_storage_encryption_scope.blob.id
}
```
```


### References

https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#request-headers-customer-provided-encryption-keys

**Comment by magodo** [comment]
@LaurentLesle I've updated the https://github.com/tombuildsstuff/giovanni/pull/61 to resolve the conflicts, whilst still waiting for review..
