### ISSUE TITLE
Add support for WAF Microsoft_DefaultRuleSet 2.0 to azurerm_frontdoor_firewall_policy

### ISSUE THREAD

**Issue by dawsonpaul** [hashicorp/terraform-provider-azurerm#17276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

 Microsoft_DefaultRuleSet 2.0 is not currently supported within the azurerm_frontdoor_firewall_policy resource.  

Microsoft_DefaultRuleSet 2.0 is the new rulebase type with anomaly detection based on OWASP CRS version 3.x. This is not compatible in Azure with previous versions of WAF. When importing the resource I can see the new version 2.0 in  state. When trying to apply the new version an error message is returned which says the Managed Rule version is not supported. 

Azure Provider version:  3.10.0 (latest)
Terraform Version: v1.2.2 (latest)

Not supported:

`
  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = "2.0"
  }
`

Error Message:

`
╷
│ Error: creating Front Door Web Application Firewall Policies (Subscription: "xxx-xxx-xxx-xxx-xxx" 
│ Resource Group Name: "xxx-application-resources" 
│ Policy Name: "xxxAzWafFrontdoorjuiceshopVersion2"): performing PoliciesCreateOrUpdate: webapplicationfirewallpolicies.WebApplicationFirewallPoliciesClient#PoliciesCreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="WebApplicationFirewallPolicy validation failed. More information \"Managed rule set type and version is not supported\"."
`

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor_firewall_policy

### Potential Terraform Configuration

```hcl
managed_rule { 
type = "Microsoft_DefaultRuleSet" 
version = "2.0" }
```

**Comment by WodansSon** [comment]
@dawsonpaul, thank you for opening this issue. Unfortunately, this is by [design](https://docs.microsoft.com/azure/web-application-firewall/afds/waf-front-door-drs?tabs=drs20#drs-20) as the "DRS 2.0 is only available on Azure Front Door Premium".  PR #16671 exposes support for the new Default Rule Set 2.0 (DRS 2.0). I am sorry to be the bearer of bad news, but this is not supported and there is nothing we can do at this point so I am going to go ahead and close this issue.

**Comment by dawsonpaul** [comment]
@WodansSon Thanks for the update. It does not seem possible to set the pricing tier (SKU) to 'Premium' on Front Door within the Azure Terraform module.

 https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor

**Comment by WodansSon** [comment]
> @WodansSon Thanks for the update. It does not seem possible to set the pricing tier (SKU) to 'Premium' on Front Door within the Azure Terraform provider.

Yes, that is correct, this will only be possible once the CDN version of Frontdoor ships... sorry about the delay...
