### ISSUE TITLE
Support for Adding "Override Routing Configuration" in Front Door - Rules Engine

### ISSUE THREAD

**Issue by adamsba3** [hashicorp/terraform-provider-azurerm#17288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Looking to impalement a rule with an action of "Override Routing Configuration"  

This feature is in Front Door component. As part of the Rules Engines

In the UI when creating a rules engine there is an "Add An Action" option, with last being "Override Routing Configuration"

When looking at current source code looks to be missing after this block: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/frontdoor/frontdoor_rules_engine_rule.go#L171-L236

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor_rules_engine

### Potential Terraform Configuration

```hcl
rule {
    name     = "overrideRouteExample"
    priority = 1

    action {
      override_routing_configuration {
        route_type           = "Forward"         # Options "Forward" or "Redirect" -- Required
        backend_pool_name    = "my_backend_pool" # Required
        forwarding_protocol  = "HTTPS"           # Options "HTTPS", "HTTP", or "Match" --  Required
        rewrite_url          = true              # Boolean -- Default false
        caching              = true              # Boolean -- Default false
      }
    }
  }
```

**Comment by WodansSon** [comment]
The legacy Frontdoor resource is being retired and is no longer supported.
