### ISSUE TITLE
Terraform not removing IP restrictions from function app

### ISSUE THREAD

**Issue by cwilmottMNZ** [hashicorp/terraform-provider-azurerm#17281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
variable "allowed_customer_ips" {
  type        = list(string)
  default     = ["1.1.1.1"]
}

variable "secure" {
  type        = bool
  default     = true
}

locals {
  allowed_customer_ips = (
    var.secure == true ?
    (var.allowed_customer_ips) :
    ([])
  )
}

resource "azurerm_linux_function_app" "acc_function_app" {
  name                       = "function-app"
  location                   = azurerm_resource_group.resource_group.location
  resource_group_name        = azurerm_resource_group.resource_group.name
  service_plan_id            = azurerm_service_plan.service_plan.id
  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key

  site_config {
    ip_restriction = [
      for ip_range in local.allowed_customer_ips : {
        ip_address                = format("%s/%s", ip_range, "32")
        name                      = null
        priority                  = null
        action                    = "Allow"
        subnet_id                 = null
        virtual_network_subnet_id = null
        headers = null
        service_tag = null
      }
    ]
  }
```

### Debug Output/Panic Output

```shell
      ~ site_config {
          ~ ip_restriction                                = [
              - {
                  - action                    = "Allow"
                  - headers                   = []
                  - ip_address                = "1.1.1.1/32"
                  - name                      = ""
                  - priority                  = 65000
                  - service_tag               = ""
                  - virtual_network_subnet_id = ""
                },
              - {
                  - action                    = "Allow"
                  - headers                   = []
                  - ip_address                = "2.2.2.2/32"
                  - name                      = ""
                  - priority                  = 65000
                  - service_tag               = ""
                  - virtual_network_subnet_id = ""
                },
            ]
            # (32 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }

```

### Expected Behaviour

When IP Restrictions is passed an empty list it should remove the existing IP Restriction rules.

### Actual Behaviour

Terraform reports that it will remove the IP Restrictions, and reports that it successfully completes it's modifications, but the rules are never removed. Subsequent runs of terraform continue to report its intention to remove the IP rules

### Steps to Reproduce

terraform apply

### Important Factoids

Running arm64-darwin

**Comment by xiaxyi** [comment]
Hey @cwilmottMNZ, good day! The issue should be fixed now, can you confirm from your side and let me know if you have any question?

Thanks!
