### ISSUE TITLE
azurerm_kubernetes_cluster | microsoft_defender block

### ISSUE THREAD

**Issue by bertrandpons** [hashicorp/terraform-provider-azurerm#17306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
For the resource azurerm_kubernetes_cluster, it is proposed to specify a block for microsoft_defender in order to define the log analytics workspace used. 

However, as stated in Microsoft documentation, "the Defender profile/extension uses a default Log Analytics workspace" (https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-enable?tabs=aks-deploy-portal%2Ck8s-deploy-asc%2Ck8s-verify-asc%2Ck8s-remove-arc%2Caks-removeprofile-api&pivots=defender-for-container-aks#default-log-analytics-workspace).

Therefore, why is this block implemented this way?
```

### Debug Output/Panic Output

```shell
If I specify a custom log analytics workspace, terraform apply will ask for a change in order to switch to the default workspace.
```

**Comment by ms-henglu** [comment]
Hi @bertrandpons ,

I've confirmed with service team, in current phase, the LA workspace is required when create AKS with azure defender in terraform.

**Comment by stephybun** [comment]
Since the service team have confirmed that the LA workspace ID is required when enabling Microsoft Defender and we haven't heard back I'm going to close this. If this is still an issue please feel free to reach out and we'll be happy to reopen this. Thanks!
