### ISSUE TITLE
Ability to create azurerm_frontdoor as Premium tier.

### ISSUE THREAD

**Issue by dawsonpaul** [hashicorp/terraform-provider-azurerm#17304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is currently no way to define  a Premium tier (SKU) Front Door deployment within the Azure terraform provider. The default deployment is a standard tier Front Door deployment. 

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Potential Terraform Configuration

```hcl
sku {
    name     = "Premium"
    tier     = "Premium"
  }
```

**Comment by WodansSon** [comment]
Hi @dawsonpaul, thank you for opening this issue. The Front Door(Classic) API's does not allow setting the `sku` as this resource/API is going to be deprecated in the near future. I have opened PR  #16671 for the new CDN Front Door (Standard/Premium) which will support this ask.
