### ISSUE TITLE
`allowCrossTenantReplication` is not updated on existing `azurerm_storage_account`

### ISSUE THREAD

**Issue by kevinharing** [hashicorp/terraform-provider-azurerm#17302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "aks_storage" {
  name                             = var.name
  resource_group_name              = var.resource_group_name
  location                         = var.location
  account_tier                     = "Premium"
  account_kind                     = "FileStorage"
  account_replication_type         = "LRS"
  min_tls_version                  = "TLS1_2"
  allow_nested_items_to_be_public  = false
  shared_access_key_enabled        = true
  **cross_tenant_replication_enabled = false**
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

 `allowCrossTenantReplication` is set to false

### Actual Behaviour

 `allowCrossTenantReplication` is not set (true by default)

### Important Factoids

In the state file it is set to `null`:

```hcl
"cross_tenant_replication_enabled": null
```

**Comment by magodo** [comment]
@kevinharing I'm using the exact same config as shown above but can't reproduce the issue. Also I've checked the code, which looks fine. So would you please double confirm whether the issue exists in the latest provider?

**Comment by kevinharing** [comment]
@magodo I think it might be [the same case](https://github.com/hashicorp/terraform-provider-azurerm/blob/19793d61f5c430ece8b0831e6b02b3579e62de8e/internal/services/storage/storage_account_resource.go#L1726) as `allow_nested_items_to_be_public` or previously `allow_blob_public_access`.

Another possible cause: This storage account was created with version 2 of the azurerm provider and then upgraded to version 3, perhaps that has something to do with it as well?

**Comment by magodo** [comment]
@kevinharing, that is possible. In case the API doesn't return that attribute back, it doesn't matter what value is set in the state, as it doesn't correctly reflect the remote state, but only some hardcoded value (in most case the zero value, i.e. `false`) in the provider code.

**Comment by tareks** [comment]
Seeing this issue as well where despite the terraform resource having the property set to false, it's still enabled in Azure. The provider does not seem to be updating this value. 

Many of our storage accounts were created with v2 version of the provider.

**Comment by magodo** [comment]
@tareks Could you please provide the v2 version of the TF code that you used to deploy the resource?

**Comment by schwarzzz** [comment]
Looks like I was able to work around this issue:
I just toggled the value in my configuration from `false` (which did not work) back to `true`, applied the configuration, switched backed to `false` and applied again.

The storage account is now in the desired state.

**Comment by aaronswainonset** [comment]
I've encountered this problem today.

The storage account was initially created with AzureRM 2.99.0, then I updated to AzureRM 3.51.0 and set `cross_tenant_replication_enabled = false`.
TF Cloud said it would apply the change:

![image](https://user-images.githubusercontent.com/63683488/236383127-3a8e75d1-0c8c-474b-bc79-556fe826c2be.png)

But the storage account still shows the setting is enabled:

![image](https://user-images.githubusercontent.com/63683488/236383185-59051621-971f-496e-b477-ee119823364f.png)

**Comment by magodo** [comment]
@aaronswainonset Thank you for providing the steps above. I tried to deploy the following config (from the description of this issue) using provider v2.99.0:

```hcl
resource "azurerm_storage_account" "aks_storage" {
  name                     = "mgdokrtest2"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Premium"
  account_kind             = "FileStorage"
  account_replication_type = "LRS"
}
```

While in the created storage account JSON representation, it has no definition of the property `allowCrossTenantReplication`. In your description above, you has a screeshot that showing the "Allow cross tenant replication" is enabled. How do you achieve that? I mean isn't that a Portal inconsistency between the visualization and the resource model?

How terraform works is that if the `allowCrossTenantReplication` is not part of the response, it was set to be `null`/`false` (depending on the implementation), while in this case, it was `null`. Then if you explicitly set to `false` and introduce a plan diff (together with some other changed properties).  

The update logic for this particular property is implemented as below:

https://github.com/hashicorp/terraform-provider-azurerm/blob/715ec6ccc7a57600d7c2e900ef81c501159826ef/internal/services/storage/storage_account_resource.go#L1506-L1513

The first `if` is actually not entered, because of how the `d.HasChange` works:

https://github.com/hashicorp/terraform-provider-azurerm/blob/715ec6ccc7a57600d7c2e900ef81c501159826ef/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go#L158-L163

and

https://github.com/hashicorp/terraform-provider-azurerm/blob/715ec6ccc7a57600d7c2e900ef81c501159826ef/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource_data.go#L68-L77

The comment above tells the reason, that for a boolean property, `null` and `false` are regared as the same. This is a common issue that the SDKv2 doesn't differ the `null` and `false`, which makes API properties that has 3 states: `true`, `false` and `null` doesn't work well with SDKv2.

**Comment by magodo** [comment]
Interestingly, the Portal "Show JSON" is buggy:

After I set `allowCrossTenantReplication` to `true` via Terraform, and viewing the JSON from portal, it is still showing `false` with the default API version 2022-05-01, while using other versions, it is correctly showing `true`. Meanwhile, I try to call `GET` via 2022-05-01 via API, it also shows `true` correctly ¯\_(ツ)_/¯

**Comment by magodo** [comment]
@aaronswainonset Thank you for the quick response! Would you mind share the TF config that you used to create the storage account?

**Comment by aaronswainonset** [comment]
@magodo 

Sure -

AzureRM 2.99.0
```hcl
# main.tf
resource "azurerm_storage_account" "sa" {
  name                             = var.storage_account.name
  resource_group_name              = var.rg_name
  location                         = var.region
  access_tier                      = var.storage_account.access_tier
  account_kind                     = var.storage_account.account_kind
  account_replication_type         = var.storage_account.replication_type
  account_tier                     = var.storage_account.account_tier
  allow_blob_public_access         = var.storage_account.allow_blob_public_access
  enable_https_traffic_only        = true
  large_file_share_enabled         = var.storage_account.large_file_share_enabled
  min_tls_version                  = var.storage_account.min_tls_version
}

variables.tf
variable "storage_account" {
  description = "Storage account configuration"
  type        = object({
    # Storage access tier (Cool|Hot)
    access_tier                      = optional(string, "Hot")
    # Storage account kind
    account_kind                     = optional(string, "StorageV2")
    # Storage account tier
    account_tier                     = optional(string, "Standard")
    # Allow public/anonymous access to blob storage
    allow_blob_public_access         = optional(bool, false)
    # Enable cross-tenant replication policies
    cross_tenant_replication_enabled = optional(bool, false)
    # Enable large file share
    large_file_share_enabled         = optional(bool, false)
    # Minimum supported TLS version for the storage account
    min_tls_version                  = optional(string, "TLS1_2")
    # Name of storage account resource
    name                             = string
    # Replication to use for storage account (LRS|GRS|RAGRS|ZRS|GZRS|RAGZRS)
    replication_type                 = optional(string, "RAGRS")
  })
  nullable    = false
}
```

AzureRM 3.5x.0
```hcl
# main.tf
resource "azurerm_storage_account" "sa" {
  name                             = var.storage_account.name
  resource_group_name              = var.rg_name
  location                         = var.region
  access_tier                      = var.storage_account.access_tier
  account_kind                     = var.storage_account.account_kind
  account_replication_type         = var.storage_account.replication_type
  account_tier                     = var.storage_account.account_tier
  allow_nested_items_to_be_public  = var.storage_account.allow_nested_items_to_be_public
  allowed_copy_scope               = var.storage_account.allowed_copy_scope
  cross_tenant_replication_enabled = var.storage_account.cross_tenant_replication_enabled
  enable_https_traffic_only        = true
  large_file_share_enabled         = var.storage_account.large_file_share_enabled
  min_tls_version                  = var.storage_account.min_tls_version
}

# variables.tf
variable "storage_account" {
  description = "Storage account configuration"
  type        = object({
    # Storage access tier (Cool|Hot)
    access_tier                      = optional(string, "Hot")
    # Storage account kind
    account_kind                     = optional(string, "StorageV2")
    # Storage account tier
    account_tier                     = optional(string, "Standard")
    # Allow public/anonymous access to nested items in this storage account
    allow_nested_items_to_be_public  = optional(bool, false)
    # Restrict copy to and from Storage Accounts within a scope
    allowed_copy_scope               = optional(string, "AAD")
    # Enable cross-tenant replication policies
    cross_tenant_replication_enabled = optional(bool, false)
    # Enable large file share
    large_file_share_enabled         = optional(bool, false)
    # Minimum supported TLS version for the storage account
    min_tls_version                  = optional(string, "TLS1_2")
    # Name of storage account resource
    name                             = string
    # Replication to use for storage account (LRS|GRS|RAGRS|ZRS|GZRS|RAGZRS)
    replication_type                 = optional(string, "RAGRS")
  })
  nullable    = false
```
