### ISSUE TITLE
azurerm_shared_image_version ID not returning version

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/terraform-provider-azurerm#17307]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_shared_image_version

### Terraform Configuration Files

```hcl
data "azurerm_shared_image_version" "main" {
  gallery_name        = "SIG"
  image_name          = "Win10"
  name                = "latest"
  resource_group_name = "sig"
}

output "id" "main" {
  value = data.azurerm_shared_image_version.main.id
}
```

### Debug Output/Panic Output

```shell
id = /subscriptions/{subscription-id}/resourceGroups/sig/providers/Microsoft.Compute/galleries/Prod/images/Win10/versions/latest
```

### Expected Behaviour

Return Azure Resource ID with version (Was working - Seems more of an Azure API problem but worth asking here) i.e

/subscriptions/{subscription-id}/resourceGroups/sig/providers/Microsoft.Compute/galleries/Prod/images/Win10/versions/<ins>**1.0.0**</ins>

### Actual Behaviour

Returns

/subscriptions/{subscription-id}/resourceGroups/sig/providers/Microsoft.Compute/galleries/Prod/images/Win10/versions/<ins>**latest**</ins>

### Steps to Reproduce

terraform apply

**Comment by myc2h6o** [comment]
Hi @ASHR4 thanks for opening the issue! This seems to be a regression. I've opened #17332 to fix the issue.
