### ISSUE TITLE
azurerm_app_service_virtual_network_swift_connection created but apply fails due to polling for virtual network.

### ISSUE THREAD

**Issue by chgenzel** [hashicorp/terraform-provider-azurerm#17317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.6

### AzureRM Provider Version

3.7.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_virtual_network_swift_connection

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_virtual_network_swift_connection" "appsvc" {
  count          = local.out_app_subnet_access ? 1 : 0
  app_service_id = azurerm_function_app.app.id
  subnet_id      = data.azurerm_subnet.delegated.id
}
```

### Debug Output/Panic Output

```shell
[...]
Error: waiting for provisioning state of virtual network for App Service VNet association between "app" (Resource Group "RG-Something") and Virtual Network "VNET-DELEGATED-DEV": polling for Virtual Network: (Name "VNET-DELEGATED-DEV" / Resource Group "RG-Another-DEV"): network.VirtualNetworksClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'client-id' with object id 'object-id' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/read' over scope '/subscriptions/sub-id/resourceGroups/RG-Another-DEV/providers/Microsoft.Network/virtualNetworks/VNET-DELEGATED-DEV' or the scope is invalid. If access was recently granted, please refresh your credentials."
│ 
│   with module.app.azurerm_app_service_virtual_network_swift_connection.appsvc[0],
│   on modules/main/network.tf line 1, in resource "azurerm_app_service_virtual_network_swift_connection" "appsvc":
│    1: resource "azurerm_app_service_virtual_network_swift_connection" "appsvc" {
[...]
```

### Expected Behaviour

Since azurerm_app_service_virtual_network_swift_connection was in fact created an needed to be imported in a later run, it should not try to read from VNET but only as expected from Function App and/or subnet. Hence, it should not fail because of missing permissions to read from VNET. Reading from VNET should not be mandatory, should it?

### Actual Behaviour

azurerm_app_service_virtual_network_swift_connection was in fact created and a read request was executed on VNET which caused a failure after the already successful creation since read permissions on VNET are not given only read permissions on subnets are given.

### Steps to Reproduce

1. Create a terraform script to:
    * Create a Function App in an existing Resource Group
    * Create a VNET and a subnet in a different existing Resource Group
    * Create a azurerm_app_service_virtual_network_swift_connection for the Function App to the subnet
2. Apply the terraform script with a user/service principle that has the following permissions:
    * Network Contributor on the subnet
    * No other permissions on the VNET's Resource Group
    * Contributor on the Function App's Resource Group

### Important Factoids

It might be related to this statement, is this realy necessary?
```go
vnetId := networkParse.NewVirtualNetworkID(subnetID.SubscriptionId, subnetID.ResourceGroup, subnetID.VirtualNetworkName)
	vnetStateConf := &pluginsdk.StateChangeConf{
		Pending:    []string{string(azureNetwork.ProvisioningStateUpdating)},
		Target:     []string{string(azureNetwork.ProvisioningStateSucceeded)},
		Refresh:    network.VirtualNetworkProvisioningStateRefreshFunc(ctx, vnetClient, vnetId),
		MinTimeout: 1 * time.Minute,
		Timeout:    time.Until(timeout),
	}
	if _, err = vnetStateConf.WaitForStateContext(ctx); err != nil {
		return fmt.Errorf("waiting for provisioning state of virtual network for App Service VNet association between %q (Resource Group %q) and Virtual Network %q: %s", name, resourceGroup, virtualNetworkName, err)
	}
```

**Comment by chgenzel** [comment]
Current workaround:
After this fails, I do a manual import for the azurerm_app_service_virtual_network_swift_connection and then another plan and apply.

**Comment by xiaxyi** [comment]
@chgenzel  have you changed anything to the resource outside of the terraform after creation, specifically, is there any change that's not managed by TF?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without knowing more about the resource, like requested avoce. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please upgrade to the latest provider version and provide the answer to the question above.
