### ISSUE TITLE
data export template cannot translate Event Hub destination correctly

### ISSUE THREAD

**Issue by MSNina123456** [hashicorp/terraform-provider-azurerm#17333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_data_export_rule

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_data_export_rule" "example" {
  name = "Nina-DE2"
  resource_group_name = data.azurerm_resource_group.main.name
  workspace_resource_id = data.azurerm_log_analytics_workspace.example.id
  destination_resource_id = data.azurerm_eventhub.id
  table_names = ["Perf"]
  enabled = true
}
```

### Debug Output/Panic Output

```shell
No error
```

### Expected Behaviour

Once created, we should see Event hub name in data export rule:
ResourceId       : /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.EventHub/namespaces/xxxx
DataExportType   : EventHub
EventHubName     : test-nina

### Actual Behaviour

Once created, we cannot see Event hub name in data export rule:
ResourceId       : /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.EventHub/namespaces/xxxx
DataExportType   : EventHub
EventHubName     : 

### Steps to Reproduce

create data export and set destination id as Event hub resource id
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_data_export_rule

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_data_export_rule

**Comment by xiaxyi** [comment]
@MSNina123456 I can see eventhub id in the `destination_resource_id`, below is the value in state
```
            "destination_resource_id": "/subscriptions/xxx/resourceGroups/xiaxintestRG-eventhub-log/providers/Microsoft.EventHub/namespaces/xiaxintesteventhubnamespace/eventhubs/xiaxintesteventhub",
```

for the api call:
```
{
    "properties": {
        "dataExportId": "4ed5d1f6-7bae-4a65-19d0-08da57e7a8a2",
        "destination": {
            "resourceId": "/subscriptions/xxx/resourceGroups/xiaxintestRG-eventhub-log/providers/Microsoft.EventHub/namespaces/xiaxintesteventhubnamespace/eventhubs/xiaxintesteventhub",
            "type": "EventHub",
            "metaData": {}
        },
        "tableNames": [
            "Perf"
        ],
        "enable": true,
        "createdDate": "Mon, 27 Jun 2022 02:49:30 GMT",
        "lastModifiedDate": "Mon, 27 Jun 2022 02:49:30 GMT"
    },
    "id": "/subscriptions/xxx/resourcegroups/xiaxintestrg-eventhub-log/providers/microsoft.operationalinsights/workspaces/xiaxintestworkspace/dataexports/eh-test",
    "name": "eh-test",
    "type": "Microsoft.OperationalInsights/workspaces/dataexports"
}
```

**Comment by xiaxyi** [comment]
@MSNina123456 may I know which version of the terraform provider that you used?

**Comment by MSNina123456** [comment]
@xiaxyi  any version should have this issue and we can see Event hub name is empty after created, you can repro the issue as always.
we also find AzAPI resource can work with event hub destination, so please update current template to support event hub, thanks

**Comment by xiaxyi** [comment]
This is the TF config that I used and i can see eventhub is exists in the state file, can you try it?
```
resource "azurerm_resource_group" "test" {
  name     = "tftestRG-eventhub-log"
  location = "east us"
}

resource "azurerm_eventhub_namespace" "test" {
  name                = "tftesteventhubnamespace"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Basic"
}

resource "azurerm_eventhub" "test" {
  name                = "tftesteventhub"
  namespace_name      = azurerm_eventhub_namespace.test.name
  resource_group_name = azurerm_resource_group.test.name
  partition_count     = 1
  message_retention   = 1
}

resource "azurerm_log_analytics_workspace" "test" {
  name                = "tftestWorkspace"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_data_export_rule" "example" {
  name = "eh-test"
  resource_group_name = azurerm_resource_group.test.name
  workspace_resource_id = azurerm_log_analytics_workspace.test.id
  destination_resource_id = azurerm_eventhub.test.id
  table_names = ["Perf"]
  enabled = true
}
```

**Comment by MSNina123456** [comment]
@xiaxyi  same as mine:
resource "azurerm_log_analytics_data_export_rule" "example" {
  name = "Nina-DE2"
  resource_group_name = data.azurerm_resource_group.main.name
  workspace_resource_id = data.azurerm_log_analytics_workspace.example.id
  destination_resource_id = data.azurerm_eventhub.id
  table_names = ["Perf"]
  enabled = true
}

after created, you can use powershell command to check data export configuration Get-AzOperationalInsightsDataExport -ResourceGroupName resourceGroupName -WorkspaceName workspaceName -DataExportName 'ruleName', then you will find event hub name is empty which cause no logs appearing in event hub side:
Once created, we cannot see Event hub name in data export rule:
ResourceId : /subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.EventHub/namespaces/xxxx
DataExportType : EventHub
EventHubName :

**Comment by xiaxyi** [comment]
do you get anything from the api call? also can you confirm the eventhub_id is properly obtained from the data source?
```
GET https://management.azure.com/subscriptions/xxx/resourceGroups/xiaxintestRG-eventhub-log/providers/Microsoft.OperationalInsights/workspaces/xiaxintestWorkspace/dataexports/eh-test?api-version=2019-08-01-preview
```

**Comment by MSNina123456** [comment]
@xiaxyi  sure, I have output of above api call because data export rule is created successfully, but as I mentioned, event hub name is empty, in api call, you can see metaData is empty where it should contain event hub name:
{
  "properties": {
    "dataExportId": "xxx",
    "destination": {
      "resourceId": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.EventHub/namespaces/eventhub-diag1",
      "type": "EventHub",
      "metaData": {}
    },
    "tableNames": [
      "Perf"
    ],
    "enable": true,
    "createdDate": "2022-06-27T03:28:38.7428672Z",
    "lastModifiedDate": "2022-06-27T03:28:38.7428672Z"
  },
  "location": "australiasoutheast",
  "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.OperationalInsights/workspaces/xxx/dataexports/Nina-DE2",
  "name": "Nina-DE2",
  "type": "Microsoft.OperationalInsights/workspaces/dataexports"
}


As comparison, if I created it in Azure portal, I will have metaData where event hub name is there correctly as below:
 "metaData": {
        "eventHubName": "test-nina"
      }

**Comment by xiaxyi** [comment]
let me check the code.

**Comment by nlighten** [comment]
We are running into the same issue. Eventhub needs to be handled differently than a Storage Account. 

The `resourceId` for an eventhub typically has the following form:
`/subscriptions/<subscriptionId>/resourceGroups/<resourceGroupName>/providers/Microsoft.EventHub/namespaces/<namespace>/eventhubs/<eventhub>`

When this `resourceId` is passed to the `destination_resource_id` argument it should not be applied directly to `Destination.ResourceID` as is done here: 

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/loganalytics/log_analytics_data_export_resource.go#L113

Instead the last part (`/eventhubs/<eventhub>`) needs to be removed from the `resourceId` and an additional `metaData.EventHubName` needs to be added containing `<eventhub>` value. 

See also:
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/Azure/azure-sdk-for-go/services/operationalinsights/mgmt/2020-08-01/operationalinsights/models.go#L1000
