### ISSUE TITLE
Changed observed during second apply for second apply for azurerm_monitor_activity_log_alert.

### ISSUE THREAD

**Issue by rutujachaudhari124** [hashicorp/terraform-provider-azurerm#17343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_activity_log_alert

### Terraform Configuration Files

```hcl
mon-activity-log-alert-test05 = {
    name                = "mon-activity-log-alert-test05"
    resource_group_name = "************"
    scopes              = ["/subscriptions/**************/resourceGroups/**************"]
    criteria = {
      category       = "ResourceHealth"
      resource_group = "**********"
      level          = "Critical"
      resource_health = [
        {
          current  = ["Unavailable", "Unknown"]
          previous = ["Unavailable", "Unknown"]
          reason   = ["Unknown"]
        },
        {
          current  = ["Available", "Degraded", "Unavailable", "Unknown"]
          previous = ["Available", "Degraded"]
          reason   = ["PlatformInitiated", "UserInitiated"]
        }
      ]
    }
    action = [
      {
        DataSource = {
          action_group_id = {
            resource_group_name = "***********"
            name                = "ag-test01"
          }
        }
        webhook_properties = {
          name = "ResourceHealth alert"
        }
      },
      {
        DataSource = {
          action_group_id = {
            resource_group_name = "************"
            name                = "ag-test02"
          }
        }
        webhook_properties = {
          name = "ResourceHealth alert"
        }
      }
    ]
    enabled     = true
    description = "This alert is for resource-health category."
    tags = {
      Name          = "mon-activity-log-alert-test05"
      Owner         = "***********"
      *********** = "yes"
    }
  }
 mon-activity-log-alert-test07 = {
    name                = "mon-activity-log-alert-test07"
    resource_group_name = "************"
    scopes              = ["/subscriptions/*********/resourceGroups/********"]
    criteria = {
      category       = "ServiceHealth"
      resource_group = "*************"
      level          = "Error"
      service_health = [
        {
          events    = ["Incident", "Maintenance", "Informational"]
          locations = ["Japan East"]
          services  = ["Alerts"]
        },
        {
          events    = ["ActionRequired", "Security"]
          locations = ["East Asia"]
          services  = ["Action Groups"]
        }
      ]
    }
    action = [
      {
        DataSource = {
          action_group_id = {
            resource_group_name = "****************"
            name                = "ag-test01"
          }
        }
        webhook_properties = {
          name = "ServiceHealth alert"
        }
      },
      {
        DataSource = {
          action_group_id = {
            resource_group_name = "***************"
            name                = "ag-test02"
          }
        }
        webhook_properties = {
          name = "ServiceHealth alert"
        }
      }
    ]
    enabled     = false
    description = "This alert is for service-health category."
    tags = {
      Name          = "mon-activity-log-alert-test07"
      Owner         = "****************"
      ********** = "yes"
    }
  }
```

### Debug Output/Panic Output

```shell
first apply is successful without an error. But during the second apply we can see the change for resource and service health block.
```

### Expected Behaviour

Second apply should not show any change and both blocks should be added successfully.

### Actual Behaviour

     ~ criteria {
            # (3 unchanged attributes hidden)

          ~ resource_health {
              ~ current  = [
                  - "Available",
                  - "Degraded",
                    # (2 unchanged elements hidden)
                ]
              ~ previous = [
                  - "Available",
                  - "Degraded",
                  + "Unavailable",
                  + "Unknown",
                ]
              ~ reason   = [
                  - "PlatformInitiated",
                  + "Unknown",
                  - "UserInitiated",
                ]
            }
          + resource_health {
              + current  = [
                  + "Available",
                  + "Degraded",
                  + "Unavailable",
                  + "Unknown",
                ]
              + previous = [
                  + "Available",
                  + "Degraded",
                ]
              + reason   = [
                  + "PlatformInitiated",
                  + "UserInitiated",
                ]
            }
        }
        # (2 unchanged blocks hidden)
    }

      ~ criteria {
            # (3 unchanged attributes hidden)

          ~ service_health {
              ~ events    = [
                  - "ActionRequired",
                  + "Incident",
                  + "Informational",
                  + "Maintenance",
                  - "Security",
                ]
              ~ locations = [
                  - "East Asia",
                  + "Japan East",
                ]
              ~ services  = [
                  - "Action Groups",
                  + "Alerts",
                ]
            }
          + service_health {
              + events    = [
                  + "ActionRequired",
                  + "Security",
                ]
              + locations = [
                  + "East Asia",
                ]
              + services  = [
                  + "Action Groups",
                ]
            }
        }

### Steps to Reproduce

terraform apply

**Comment by rutujachaudhari124** [comment]
Any updates on this issue?

**Comment by teowa** [comment]
Hi @rutujachaudhari124 , thanks for submiting this!
I can successfully repro the same issue you meet. And I have checked the source code and find that the `resource_health` and `service_health` should add a constraint to limit the number of blocks to allow for only one blocks, for using one blocks already has the full access to these properties. I am going to submit PR to resolve this. And as a possible workaround, you can add two blocks into one like below, the function should stays the same.

change
```
      service_health = [
        {
          events    = ["Incident", "Maintenance", "Informational"]
          locations = ["Japan East"]
          services  = ["Alerts"]
        },
        {
          events    = ["ActionRequired", "Security"]
          locations = ["East Asia"]
          services  = ["Action Groups"]
        }
      ]    
```
to
```
      service_health = [
        {
          events    = ["Incident", "Maintenance", "Informational","ActionRequired", "Security"]
          locations = ["Japan East", "East Asia"]
          services  = ["Alerts", "Action Groups"]
        }
      ]
```
And the same for `resouce_health`.
Hope this may help, if you have any futher issues, feel free to reply here.

**Comment by rcskosir** [comment]
@teowa Thank you for contributing to this issue. Were you able to create a PR to resolve this? If so, can you please link it here?
