### ISSUE TITLE
azurerm_role_assignment for Azure Key Vault fails with PrincipalNotFound not found

### ISSUE THREAD

**Issue by randolf720** [hashicorp/terraform-provider-azurerm#17357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment, link: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_managed_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "example" {
  scope                = azurerm_storage_account.example.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id         = "727055f9-0386-4ccb-bcf1-9237237ee102"
}
```

### Debug Output/Panic Output

```shell
Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PrincipalNotFound" Message="Principal 727055f903864ccbbcf19237237ee102 does not exist in the directory <removeddirectoryid> Check that you have the correct principal ID. If you are creating this principal and then immediately assigning a role, this error might be related to a replication delay. In this case, set the role assignment principalType property to a value, such as ServicePrincipal, User, or Group.  See https://aka.ms/docs-principaltype"
```

### Expected Behaviour

Role assignment

### Actual Behaviour

Error, see Output/Panic Output

### Steps to Reproduce

Azure DevOps Pipeline, generated an error during the apply phase

**Comment by myc2h6o** [comment]
Hi @randolf720 thanks for opening the issue! The `principal_id` in document seems to be wrong, I've created #17367 to fix it.
You can get the correct principal id by using below config:
```hcl

data "azuread_service_principal" "test" {
  # display_name = "Azure Key Vault"
  application_id = "cfa8b339-82a2-471a-a3c9-0fc0be7a4093"
}

resource "azurerm_role_assignment" "example" {
  scope                = azurerm_storage_account.example.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id         = data.azuread_service_principal.test.id
}

```
 https://docs.microsoft.com/azure/key-vault/secrets/overview-storage-keys-powershell#service-principal-application-id
