### ISSUE TITLE
Add support for updating Key Vault Certificate content

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#17358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently changing the content of a Key Vault certificate re-creates the resource ([documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_certificate#contents)). This means it destroys the certifcate and creates it again with the new content. This can't be done if Purge Protection is enabled on the Key Vault, which is a best practice. 

Terraform fails its operation in this case:
![image](https://user-images.githubusercontent.com/46575727/175311948-3c1527fe-3c76-4893-aaf8-bc54462a4fdf.png)

Therefore there should exist an option to simply update the content. Azure Portal supports this by creating a new version of the certificate:
![image](https://user-images.githubusercontent.com/46575727/175312400-7d7f3d7a-f71b-4442-a440-cb091a4bde21.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificate

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_certificate" "example" {
  name         = "imported-cert"
  key_vault_id = azurerm_key_vault.example.id
  create_new_version = true // <- this could indicate to not re-create the tf resource

  certificate {
    contents = filebase64("certificate-to-import.pfx")
    password = ""
  }
}
```

**Comment by ssergio25** [comment]
We have the same issue , Terraform tries to destroy the existing certificate, when what we want to do is update a new version of the soon to be expired cert. 

![image](https://user-images.githubusercontent.com/115113600/194153863-931a577e-fda4-43cb-8fbe-d16f025b7eba.png)
