### ISSUE TITLE
azurerm_application_gateway bug in the documentation of the probe block

### ISSUE THREAD

**Issue by BeTheFlow95** [hashicorp/terraform-provider-azurerm#17353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
It's only a bug in this documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway
```

### Debug Output/Panic Output

```shell
unhealthy_threshold - (Required) The Unhealthy Threshold for this Probe, which indicates the amount of retries which should be attempted before a node is deemed unhealthy. Possible values are from 1 - 20 seconds.
```

### Expected Behaviour

In the documentation of azurerm_application_gateway Probe block, the unhealthy_threshold is declared as the AMOUNT OF RETRIES, but later its possible values are between 1 and 20 SECOONDS. 

Is only the word "seconds" wrong in this place or is the explanation of the unhealthy_threshold wrong?

**Comment by stephybun** [comment]
Closed by #17364
