### ISSUE TITLE
datasource azurerm_images: the output block for imageid show the timestamp of image created rather than resource id

### ISSUE THREAD

**Issue by SuryaTejaT-1201** [hashicorp/terraform-provider-azurerm#17379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13+

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_images

### Terraform Configuration Files

```hcl
data "azurerm_images" "lxImage" {
    resource_group_name = "resourcegroupname"
    tags_filter = {
      "tag" = "value"
      "OS" = "win/linux"
    }
  
}

output "image" {
    value = data.azurerm_images.lxImage
  
}
```

### Debug Output/Panic Output

```shell
Changes to Outputs:
  + image = {
      + id                  = "2022-06-24 18:54:39.9310182 +0000 UTC"
```

### Expected Behaviour

/subscriptions/*subcriptionId*/resourceGroups/*resourcegroupname*/providers/Microsoft.Compute/images/ubuntuimage-img"

**Comment by myc2h6o** [comment]
Hi @SuryaTejaT-1201 thanks for opening the issue! The id of this data source seems to be set to the UTC timestamp to avoid duplication, but it caused the id to be unstable. I'll check if we could use a more meaningful for this resource.

**Comment by SuryaTejaT-1201** [comment]
@myc2h6o thanks for your response. I just added the "Expected Behavior" how should be output for ID.

**Comment by SuryaTejaT-1201** [comment]
@myc2h6o a gentle follow up on this case.

**Comment by SuryaTejaT-1201** [comment]
@myc2h6o a gentle follow up here

**Comment by myc2h6o** [comment]
Hi @SuryaTejaT-1201 I've opened #17766 to change the id to be static, which should remove the additional output of changing timestamp
