### ISSUE TITLE
azurerm_mssql_database long_term_retention_policy does not get applied

### ISSUE THREAD

**Issue by KezHalls** [hashicorp/terraform-provider-azurerm#17393]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.0

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
long_term_retention_policy {
    weekly_retention  = "P35D"
    monthly_retention = "P14W"
    yearly_retention  = "P3Y"  
    week_of_year = 1      
  }
```

### Debug Output/Panic Output

```shell
~ long_term_retention_policy {
          ~ monthly_retention = "PT0S" -> "P14W"
          ~ week_of_year      = 0 -> 1
          ~ weekly_retention  = "P3M" -> "P35D"
          ~ yearly_retention  = "PT0S" -> "P3Y"
        }
```

### Expected Behaviour

retention policies should change from the default retention period

### Actual Behaviour

retention policies should change to the requested retention settings

### Steps to Reproduce

terraform apply

### References

#13035
#15803

**Comment by sinbai** [comment]
@KezHalls thank you for opening this issue here. I could not repro this issue with the following tf configuration. Could you reproduce with it? 

step 1: create azurerm_mssql_database with the following tf config :
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.8.0"
    }
  }
}

provider "azurerm" {
  features {
  }
}


resource "azurerm_resource_group" "test" {
  name     = "mssql-example"
  location = "eastus"
}

resource "azurerm_mssql_server" "test" {
  name                         = "sqlserver-example"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
}

resource "azurerm_mssql_database" "test" {
  name      = "acctest-db-example"
  server_id = azurerm_mssql_server.test.id
  long_term_retention_policy {
    weekly_retention  = "P3M"
    monthly_retention = "PT0S"
    yearly_retention  = "PT0S"
    week_of_year      = 1
  }
}
```

step2: update `azurerm_mssql_database` with the following tf configuration , then terraform apply => everything is going smooth .
```
resource "azurerm_mssql_database" "test" {
  name      = "acctest-db-example"
  server_id = azurerm_mssql_server.test.id
  long_term_retention_policy {
    weekly_retention  = "P35D"
    monthly_retention = "P14W"
    yearly_retention  = "P3Y"
    week_of_year      = 1
  }
}
```

**Actual**: call [api ](https://docs.microsoft.com/en-us/rest/api/sql/2021-05-01-preview/long-term-retention-policies/list-by-database#code-try-0), the response is as follows:
```
{
  "value": [
    {
      "properties": {
        "weeklyRetention": "P35D",
        "monthlyRetention": "P14W",
        "yearlyRetention": "P3Y",
        "weekOfYear": 1
      },
      "id": "/subscriptions/xxx/resourceGroups/mssql-example/providers/Microsoft.Sql/servers/sqlserver-example/databases/acctest-db-example/backupLongTermRetentionPolicies/default",
      "name": "default",
      "type": "Microsoft.Sql/servers/databases/backupLongTermRetentionPolicies"
    }
  ]
}
```
