### ISSUE TITLE
Support for Disabling Access Keys for app_configuration Resource

### ISSUE THREAD

**Issue by schultzwc18** [hashicorp/terraform-provider-azurerm#17408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure app configuration supports disabling access keys such that only AzureAD authentication can be used on the resource. Both the REST API and Azure CLI support configuring this parameter, for example, Azure CLI uses the ```--disable-local-auth```.

The solution for this would be a configurable parameter for the azurerm_app_configuration resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_app_configuration

### Potential Terraform Configuration

```hcl
resource "azurerm_app_configuration" "this" {
  name                = "appConfigBlue"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
  identity {
    type = "SystemAssigned"
  }
  disable_local_auth = true
}
```

**Comment by teowa** [comment]
Hi @schultzwc18 , thanks for opening this issue. The `local_auth_enabled` property is going to be supported in PR #17714 . You can try that in coming future after the PR is merged.
