### ISSUE TITLE
I would like to make sure that Azure SQL Server is accessible ONLY from desired IPs when terraform reports no changes on apply/plan

### ISSUE THREAD

**Issue by mllab-nl** [hashicorp/terraform-provider-azurerm#17404]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I would like to make sure that my Azure SQL db has ONLY rules I have defined using  azurerm_mssql_firewall_rule and no others

In multiple places (azurerm_storage_account_network_rules,  azurerm_kubernetes_cluster.api_server_authorized_ip_ranges ) you control the entire ruleset. 
This means you  know that no extra rules were created.
I would like to make sure this is the case for Azure SQL DB. 

Maybe there is a way to check the amount of rules ? In this case you can fail if it does not match expected set of rules after apply. 
Or any other way to achieve full visibility ? 

I did not find a way to achieve that. 

Could you please let me know if there is a way to achieve the desired behaviour and if not is there a plan to implement this so that Azure SQL DBs managed by terraform will be as secure as possible ! 

Thank you,
Alexander

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_firewall_rule

### Potential Terraform Configuration

```hcl
.
```

### References

.

**Comment by sinbai** [comment]
@mllab-nl thank you for opening this issue. Unfortunately, I didn't find any Azure API that supports this feature. Could you share the rest API link for this feature if possible?

**Comment by mllab-nl** [comment]
@sinbai I am not an expert on those API, but using the existing API IMO should be possible to return an attribute on azurerm_mssql with amount of firewall rules. That should do the trick

**Comment by vytux-com** [comment]
I am looking for same solution, would this help?

https://learn.microsoft.com/en-us/rest/api/sql/2021-02-01-preview/firewall-rules/list-by-server?tabs=HTTP

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.

**Comment by egorshulga** [comment]
Looks like a feature request 😉 Sorry for creating even more burden on the repo.
As far as I can see, the Go sdk already [supports the call](https://github.com/hashicorp/terraform-provider-azurerm/blob/06217d569ef36a9416f63b3528d7e648e4afbb2e/vendor/github.com/Azure/azure-sdk-for-go/services/preview/sql/mgmt/v5.0/sql/firewallrules.go#L279C35-L279C47) to list all rules. I believe to cover this drift mitigation issue, we'd need to implement a `azurerm_mssql_firewall_rules` resource to set all rules at once (as opposed to `azurerm_mssql_firewall_rule` which creates only one rule)
