### ISSUE TITLE
extended_auditing_policy block is not working in azurerm_mssql_database resource.

### ISSUE THREAD

**Issue by PriyanshuKatiyarSecurrency** [hashicorp/terraform-provider-azurerm#17439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "test" {
  name           = "acctest-db-d"
  server_id      = azurerm_mssql_server.example.id
  collation      = "SQL_Latin1_General_CP1_CI_AS"
  license_type   = "LicenseIncluded"
  max_size_gb    = 4
  read_scale     = true
  sku_name       = "S0"
  zone_redundant = true

  extended_auditing_policy {
    storage_endpoint                        = azurerm_storage_account.example.primary_blob_endpoint
    storage_account_access_key              = azurerm_storage_account.example.primary_access_key
    storage_account_access_key_is_secondary = true
    retention_in_days                       = 6
  }


  tags = {
    foo = "bar"
  }
```
```


### Debug Output/Panic Output

```shell
https://gist.github.com/PriyanshuKatiyarSecurrency/ad75988dae7fa6c5397626f7b63387e7
```

### Actual Behaviour

```
│ Error: Unsupported block type
│ 
│   on main.tf line 37, in resource "azurerm_mssql_database" "test":
│   37:   extended_auditing_policy {
│ 
| Blocks of type "extended_auditing_policy" are not expected here.
```

**Comment by sinbai** [comment]
@PriyanshuKatiyarSecurrency Thanks for opening this issue here. Since the `extended_auditing_policy` block has been moved to `azurerm_mssql_database_extended_auditing_policy`. This block has been removed in version 3.0 of the provider. We will update the terraform documentation later.
