### ISSUE TITLE
After Azure TF upgrade to 1.2.3 I get Error: retrieving `contact` for KeyVault

### ISSUE THREAD

**Issue by dimitrigeo** [hashicorp/terraform-provider-azurerm#17443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

2.9.9

### Affected Resource(s)/Data Source(s)

azurerm_key_vaul

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                     = var.kv_name
  location                 = var.location
  resource_group_name      = var.resource_group_name
  tenant_id                = var.tenant_id
  sku_name                 = "standard"
  purge_protection_enabled = true

  network_acls {
    default_action = "Deny"
    bypass = "AzureServices"
    ip_rules = var.kv_ip_allowed_from

  }
}


resource "azurerm_key_vault_access_policy" "object" {
  key_vault_id = azurerm_key_vault.main.id
  tenant_id    = azurerm_key_vault.main.tenant_id
  object_id    = data.azurerm_client_config.current.object_id

  key_permissions = [
    "Get",
    "List",
    "Update",
    "Create",
    "Import",
    "Delete",
    "Recover",
    "Backup",
    "Restore",
    "Decrypt",
    "Encrypt",
  ]

  secret_permissions = [
    "get",
    "list",
    "set",
    "delete",
    "recover",
    "backup",
    "restore",
  ]

  certificate_permissions = [
    "create",
    "delete",
    "deleteissuers",
    "get",
    "getissuers",
    "import",
    "list",
    "listissuers",
    "managecontacts",
    "manageissuers",
    "purge",
    "recover",
    "setissuers",
    "update",
    "backup",
    "restore"
  ]
}


 
resource "azurerm_role_assignment" "team_access" {
  scope                = azurerm_key_vault.main.id
  role_definition_name = var.team_acces_role
  principal_id         = var.team_object_id
}


resource "azurerm_private_endpoint" "kv-endpoint" {
  name                = "${var.kv_name}-endpoint"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.subnet_id

  private_service_connection {
    name                           = "${var.kv_name}-privateserviceconnection"
    private_connection_resource_id = azurerm_key_vault.main.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Warning: Argument is deprecated
│ 
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on ../modules/aks/aks.tf line 11, in resource "azurerm_kubernetes_cluster" "main":
│   11: resource "azurerm_kubernetes_cluster" "main" {
│ 
│ `role_based_access_control` is deprecated in favour of the properties
│ `role_based_access_control_enabled` and
│ `azure_active_directory_role_based_access_control` and will be removed in
│ version 3.0 of the AzureRM provider
│ 
│ (and 7 more similar warnings elsewhere)
╵
╷
│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with module.keyvault.azurerm_key_vault.main,
│   on ../modules/dev/keyvault.tf line 4, in resource "azurerm_key_vault" "main":
│    4: resource "azurerm_key_vault" "main" {
│ 
╵
```

### Expected Behaviour

this was working with terraform version 1.0.11

### Actual Behaviour

╷
│ Warning: Argument is deprecated
│ 
│   with module.aks.azurerm_kubernetes_cluster.main,
│   on ../modules/aks/aks.tf line 11, in resource "azurerm_kubernetes_cluster" "main":
│   11: resource "azurerm_kubernetes_cluster" "main" {
│ 
│ `role_based_access_control` is deprecated in favour of the properties
│ `role_based_access_control_enabled` and
│ `azure_active_directory_role_based_access_control` and will be removed in
│ version 3.0 of the AzureRM provider
│ 
│ (and 7 more similar warnings elsewhere)
╵
╷
│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with module.keyvault.azurerm_key_vault.main,
│   on ../modules/dev/keyvault.tf line 4, in resource "azurerm_key_vault" "main":
│    4: resource "azurerm_key_vault" "main" {
│ 
╵

### Steps to Reproduce

terraform plan

### Important Factoids

this was working with terraform version 1.0.11

**Comment by sinbai** [comment]
Hi @dimitrigeo,

Thanks for opening this issue here. It's worth mentioning that I was able to reproduce this issue even though the terraform version was not upgraded to 1.2.3 (using terraform v1.0.11 and AzureRM Provider v2.99.0) with the tf configuration provided above. Also, in my test, it is found that if removing the configuration of resource `azurerm_private_endpoint`, run `terraform apply` to create azurerm_key_vault, azurerm_key_vault_access_policy and then run `terraform plan`, everything works fine. 

Per [terraform doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#private_connection_resource_id), `private_connection_resource_id` should be the resource id of private link service (the id of resource azurerm_private_link_service) instead of the keyvault id in the following tf configuration. In the case where the `azurerm_key_vault.main.id` is set, the error (no such host for https://{kv-name}.vault.azure.net/certificates/contacts?api-version=7.1) returned by the Azure API could be found in terraform log, although it exists. So, could you please update the `private_connection_resource_id `  to the correct resource id to see if there is still error?

 ```
private_service_connection {
    name                           = "${var.kv_name}-privateserviceconnection"
    private_connection_resource_id = azurerm_key_vault.main.id
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider, and @sinbai's suggestions above weren't able to fix it please do let us know by opening a new issue, thanks!
