### ISSUE TITLE
Support `acr_use_managed_identity_credentials` site_config for azurerm_linux_web_app

### ISSUE THREAD

**Issue by adisaljusi** [hashicorp/terraform-provider-azurerm#17451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.2.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.11.0"
    }
  }
  backend "azurerm" {}
}


data "azurerm_resource_group" "example" {
  name = "example-rg"
}

resource "azurerm_app_service_plan" "example" {
  name                = "example-service-plan"
  location            = data.azurerm_resource_group.example.location
  resource_group_name = data.azurerm_resource_group.example.name
  kind                = "linux"
  reserved            = true

  sku {
    size = "B3"
    tier = "Basic"
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "azurerm_container_registry" "example" {
  name                = "example-acr"
  location            = data.azurerm_resource_group.example.location
  resource_group_name = data.azurerm_resource_group.example.name
  sku                 = "Basic"

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "azurerm_role_assignment" "pull_image" {
  role_definition_name = "AcrPull"
  scope                = azurerm_container_registry.example.id
  principal_id         = azurerm_app_service.example.identity[0].principal_id
}



resource "azurerm_linux_web_app" "example" {
  name                = "example-app-service"
  resource_group_name = data.azurerm_resource_group.example.name
  location            = data.azurerm_resource_group.example.location
  service_plan_id     = azurerm_app_service_plan.example.id
  https_only          = true

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on                            = "true"
    acr_use_managed_identity_credentials = "true"
  }

  app_settings = {
    DOCKER_REGISTRY_SERVER_URL = "https://${azurerm_container_registry.example.login_server}"
  }

  lifecycle {
    ignore_changes = [
      site_config.0.scm_type,
      app_settings,
      tags
    ]
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Unsupported argument
│ 
│   on appservice.tf line 14, in resource "azurerm_linux_web_app" "example":
│   14:     acr_use_managed_identity_credentials = "true"
│ 
│ An argument named "acr_use_managed_identity_credentials" is not expected here.
```

### Expected Behaviour

Terraform shouldn't throw an exception and respect the `acr_use_managed_identity_credentials` argument. Terraform then should configure the Azure App Service configuration to use managed identity for deployments. In the old `azurerm_app_service` resource, the argument was respected and no exceptions were thrown.

### Actual Behaviour

Terraform plan doesn't complete successfully

### Steps to Reproduce

1. terraform init -backend-config="configuration.tfvars"
2. terraform plan -var-file="variables.local.tfvars"

### References

[#12745 https://github.com/hashicorp/terraform-provider-azurerm/pull/12745](https://github.com/hashicorp/terraform-provider-azurerm/pull/12745)

**Comment by xiaxyi** [comment]
@adisaljusi Thanks for this, I'll check the feature and see if we can add it back

**Comment by buntagonalprism** [comment]
Seems like it was just renamed. We're using the following and it works for pulling images from ACR using managed identity for linux web apps

```
  site_config {
    container_registry_use_managed_identity = true
  }
```

**Comment by adisaljusi** [comment]
@buntagonalprism thanks for pointing this out. Doc reference: 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#container_registry_use_managed_identity
