### ISSUE TITLE
Want to know effective way of creating azure synapse workspace with Service Principal

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#17479]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

2.83

### Affected Resource(s)/Data Source(s)

synapse_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_workspace" "syn_ws" {
  name                                 = "syn-${var.prefix}-${var.postfix}"
  resource_group_name                  = var.rg_name
  location                             = var.location
  storage_data_lake_gen2_filesystem_id = var.adls_id

  sql_administrator_login          = var.synadmin_username
  sql_administrator_login_password = var.synadmin_password

  managed_virtual_network_enabled = true
  managed_resource_group_name     = "${var.rg_name}-syn-managed"

  aad_admin {
    login     = var.aad_login.name
    object_id = var.aad_login.object_id
    tenant_id = var.aad_login.tenant_id
  }
}
```

### Debug Output/Panic Output

```shell
I am able to create workspace with AD admin user, but I want to create it with service principal which already exist
```

### Expected Behaviour

I am able to create workspace with AD admin user, but I want to create it with service principal which already exist

### Actual Behaviour

I am able to create workspace with AD admin user, but I want to create it with service principal which already exist.

How to tell terraform to use my existing service principal to create workspace? Documentation example don't  have service principal example

### Important Factoids

.

### References

.

**Comment by ms-henglu** [comment]
Hi @onenessboy ,

I think you use `azuread_service_principal` data source to fetch the existing service principal and refer it in synapse workspace.

https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/data-sources/service_principal

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
