### ISSUE TITLE
Support for Application Gateway CustomV2 policy type / TLSv1.3

### ISSUE THREAD

**Issue by maxburke** [hashicorp/terraform-provider-azurerm#17484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It looks like Azure has an Application Gateway feature preview for a CustomV2 policy type which implements a minimum protocol version of TLSv1.3. This new minimum protocol version only has two supported cipher suites: TLS_AES_128_GCM_SHA256, and TLS_AES_256_GCM_SHA384. 

### New or Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "ag_centralca_prod_ulgate_v2" {
  ssl_policy {
    disabled_protocols   = []
    policy_type          = "CustomV2"
    min_protocol_version = "TLSv1_3"
    cipher_suites = [
      "TLS_AES_128_GCM_SHA256",
      "TLS_AES_256_GCM_SHA384",
    ]
  }
}
```

**Comment by rsun-thoughtworks** [comment]
Also found this issue, don't know how to handle it.
