### ISSUE TITLE
Visibility of Webhook properties on Azure Portal for azurerm_monitor_activity_log_alert.

### ISSUE THREAD

**Issue by rutujachaudhari124** [hashicorp/terraform-provider-azurerm#17486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.2.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_activity_log_alert

### Terraform Configuration Files

```hcl
mon-activity-log-alert-test01 = {
    resource_group_name = "**************"
    name                = "mon-activity-log-alert-test01"
    scopes              = ["/subscriptions/**************/resourcegroups/***************"]
    enabled             = true
    description         = "This alert is for Administrative category."
    criteria = {
      category          = "Administrative"
      operation_name    = "Microsoft.Compute/virtualMachines/write"
      resource_provider = "Microsoft.Compute"
      resource_type     = "Microsoft.Compute/virtualMachines"
      resource_group    = "************"
      resource_id       = "/subscriptions/****************/resourceGroups/*************/providers/Microsoft.Compute/virtualMachines/vm-test01"
      caller            = "**************"
      level             = "Verbose"
      status            = "Started"
      sub_status        = "OK"
    }
    action = [
      {
        DataSource = {
          action_group_id = {
            resource_group_name = "**************"
            name                = "ag-test01"
          }
        }
        webhook_properties = {
          name        = "callmyapi"
          service_uri = "http://example.com/alert"
        }
      },
      {
        DataSource = {
          action_group_id = {
            resource_group_name = "*************"
            name                = "ag-test02"
          }
        }
        webhook_properties = {
          name = "Administrative alert"
        }
      }
    ]
    tags = {
      Name          = "mon-activity-log-alert-test01"
      Owner         = "************"
      **************** = "yes"
    }
  }
```

### Debug Output/Panic Output

```shell
Alert created successfully with no errors.
```

### Expected Behaviour

Webhook properties for two action groups are provided separately so, webhook properties for both the action groups must be visible on the console.

### Actual Behaviour

Webhook properties of only second block of action group are visible on console. A note is mentioned which describes that if multiple webhook properties are provided, it will be overridden.

<img width="478" alt="Console_2" src="https://user-images.githubusercontent.com/107192994/177081168-81f47381-1181-4e08-b51c-2fa7a5b40a43.PNG">

### Steps to Reproduce

1.terraform apply

**Comment by teowa** [comment]
I think this is Portal display issue, you can retrieve the `webhook_properties` by clicking the `Properties` on the top and then click `JSON view` on the right side of the UI. You can see `webhook_properties` have been correctly set in the API.
