### ISSUE TITLE
azure_postgresql_flexible_server connectionstring in output

### ISSUE THREAD

**Issue by sdahlbac** [hashicorp/terraform-provider-azurerm#17503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would have expected to be able to get the connection_string as an output. Now it seems I have to go into the portal and pull it out manually.

if I run 
```
az postgres flexible-server create --resource-group ... --location ... --tier Burstable --sku-name Standard_B1ms
Checking the existence of the resource group '...'...
Resource group '...' exists ? : True
Detected current client IP : ...
Do you want to enable access to client ... (y/n) (y/n): y
Creating PostgreSQL Server '...' in group '...'...
Your server '...' is using sku 'Standard_B1ms' (Paid Tier). Please refer to https://aka.ms/postgres-pricing for pricing details
Configuring server firewall rule to accept connections from '...'...
Creating PostgreSQL database '...'...
Make a note of your password. If you forget, you would have to reset your password with "az postgres flexible-server update -n ... -g ... -p <new-password>".
Try using 'az postgres flexible-server connect' command to test out connection.
{
  "connectionString": "postgresql://....postgres.database.azure.com/postgres?sslmode=require",
...
}
```

What I would like to do.

Have a base terraform project creating the database
Have a second terraform pulling in the connection string from remote state. (alternatively from Key vault)

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
output "connection-string" {
  value = azurerm_postgresql_flexible_server.example.connection_string
  sensitive = true
}
```

**Comment by sinbai** [comment]
@sdahlbac thanks for opening this issue. Since terraform supports connectionstring in output, support from the Azure Rest API is required. There doesn't seem to be an [Azure API](https://github.com/Azure/azure-rest-api-specs/blob/898587c563d7b1941e1a10779ea7b122dce8ad6f/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2021-06-01/postgresql.json#L204) to expose the connectionString. I assume that terraform could not currently support the request.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.

**Comment by wuxu92** [comment]
hi @sdahlbac actually the connection string is just a simple string literally constructed from several parts, you can compute the value with terraform locally like:

```hcl
output connstr {
  value = "postgresql://${azurerm_postgresql_flexible_server.example.administrator_login}:${azurerm_postgresql_flexible_server.example.administrator_password}@${azurerm_postgresql_flexible_server.example.fqdn}:5432/postgres?sslmode=require"
  sensitive = true
}
```

then you can use `terraform output -raw connstr` to view the connection string
