### ISSUE TITLE
azurerm_data_factory_trigger_schedule can't trigger multiple pipelines

### ISSUE THREAD

**Issue by andrewtatham** [hashicorp/terraform-provider-azurerm#17504]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

An ADF trigger can trigger multiple pipelines. I would expect the azurerm_data_factory_trigger_schedule to accept multiple pipeline blocks, but it does not. 

### Terraform Version

1.1.4

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_trigger_schedule

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_data_factory_pipeline" "example1" {
  name            = "example1"
  data_factory_id = azurerm_data_factory.example.id
}

resource "azurerm_data_factory_pipeline" "example2" {
  name            = "example2"
  data_factory_id = azurerm_data_factory.example.id
}

resource "azurerm_data_factory_pipeline" "example3" {
  name            = "example3"
  data_factory_id = azurerm_data_factory.example.id
}


resource "azurerm_data_factory_trigger_schedule" "example" {
  name            = "example"
  data_factory_id = azurerm_data_factory.example.id
  interval  = 5
  frequency = "Day"

  pipeline {
    name = azurerm_data_factory_pipeline.example1.name
  }

  pipeline {
    name = azurerm_data_factory_pipeline.example2.name
  }

  pipeline {
    name = azurerm_data_factory_pipeline.example3.name
  }

}
```

### Debug Output/Panic Output

```shell
│ Error: Missing required argument
│ The argument "pipeline_name" is required, but no definition was found.

│ Error: Unsupported block type
│ Blocks of type "pipeline" are not expected here.
```

### Expected Behaviour

Multiple pipelines triggered

### Actual Behaviour

Errors as shown in output

### Steps to Reproduce

terraform apply

**Comment by ms-henglu** [comment]
Hi @andrewtatham ,

This feature has been supported in https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.9.0/CHANGELOG.md, would you please upgrade to the latest azurerm version?

**Comment by ms-henglu** [comment]
And it's duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/16884
