### ISSUE TITLE
NSG rule is removed only from the state file but not from the Azure portal.

### ISSUE THREAD

**Issue by thejanek** [hashicorp/terraform-provider-azurerm#17506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.5

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "network-security-group" {
  name                = "nsg-001"
  resource_group_name = "my-rg"
  location            = "eastus"

}

resource "azurerm_subnet_network_security_group_association" "nsg-association" {
  subnet_id                 = azurerm_subnet.dedicated-subnets-creation.id
  network_security_group_id = azurerm_network_security_group.network-security-group.id
}

resource "azurerm_network_security_rule" "rule01" {
  resource_group_name         = "my-rg"
  name                        = "rdp"
  network_security_group_name = "nsg-001"
  access                      = "Allow"
  direction                   = "Inbound"
  priority                    = 215
  protocol                    = "Tcp"
  source_port_range           = "*"
  source_address_prefix       = "*"
  destination_port_range      = "3389"
  destination_address_prefix  = "*"
}
```

### Debug Output/Panic Output

```shell
Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
```

### Expected Behaviour

NSG rule should be removed after deletion of below code:

resource "azurerm_network_security_rule" "rule01" {
  resource_group_name         = "my-rg"
  name                        = "rdp"
  network_security_group_name = "nsg-001"
  access                      = "Allow"
  direction                   = "Inbound"
  priority                    = 215
  protocol                    = "Tcp"
  source_port_range           = "*"
  source_address_prefix       = "*"
  destination_port_range      = "3389"
  destination_address_prefix  = "*"
}

### Actual Behaviour

Terraform shows success of deletion of NSG rule but (in state file terraform successfully removed mentioned rule) but in Azure portal rule still exist even after web browser restart or 1 hour of waiting...

### Steps to Reproduce

Please list the full steps required to reproduce the issue, for example:
1. `terraform init`
2. `terraform apply` # to deploy NSG rule.
3.  I am removing code or just mark it as a text 
resource "azurerm_network_security_rule" "rule01" {
resource_group_name         = "my-rg"
name                        = "rdp"
network_security_group_name = "nsg-001"
access                      = "Allow"
direction                   = "Inbound"
priority                    = 215
protocol                    = "Tcp"
source_port_range           = "*"
source_address_prefix       = "*"
destination_port_range      = "3389"
destination_address_prefix  = "*"
}

### Important Factoids

Removing or marking mentioned code as a text ending with potential success but ONLY in state file  - in Azure portal rule is still available and visible.  ONLY deletion process works properly if I am using below command: "terraform destroy -auto-approve -target="azurerm_network_security_rule.rule01"

**Comment by sinbai** [comment]
Hi @thejanek thanks for opening this issue. Unfortunately, I could not reproduce this issue with the following tf configuration and reproduce steps. Could you reproduce with it? Could you correct me if it is different from yours?

Terraform and AzureRM Provider Version:
![image](https://user-images.githubusercontent.com/39109137/177705407-62d19f22-06e4-4c23-b20e-4b2d123fe2a3.png)

Step1: Create azurerm_network_security_rule with the following tf configuration by running `terraform init`, `terraform apply -auto-approve`.
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.8.0"
    }
  }
}

provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "test" {
  name     = "RG-example"
  location = "eastus"
}


resource "azurerm_virtual_network" "test" {
  name                = "testvirtnet-example"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_network_security_group" "test" {
  name                = "testnsg-example"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}


resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_subnet_network_security_group_association" "test" {
  subnet_id                 = azurerm_subnet.test.id
  network_security_group_id = azurerm_network_security_group.test.id
}

resource "azurerm_network_security_rule" "rule01" {
  resource_group_name         = azurerm_resource_group.test.name
  name                        = "rdp"
  network_security_group_name = azurerm_network_security_group.test.name
  access                      = "Allow"
  direction                   = "Inbound"
  priority                    = 215
  protocol                    = "Tcp"
  source_port_range           = "*"
  source_address_prefix       = "*"
  destination_port_range      = "3389"
  destination_address_prefix  = "*"
}
```

- `rule01` was added in the Azure portal:

![image](https://user-images.githubusercontent.com/39109137/177709474-7fbc9c0a-47ca-4eaa-a9ff-d98eb326b0b4.png)


Step2: Remove the following tf configuration in the .tf file of Step1. Run `terraform apply -auto-approve`.
```
resource "azurerm_network_security_rule" "rule01" {
  resource_group_name         = azurerm_resource_group.test.name
  name                        = "rdp"
  network_security_group_name = azurerm_network_security_group.test.name
  access                      = "Allow"
  direction                   = "Inbound"
  priority                    = 215
  protocol                    = "Tcp"
  source_port_range           = "*"
  source_address_prefix       = "*"
  destination_port_range      = "3389"
  destination_address_prefix  = "*"
}
```

Actual: `rule01` was deleted in the Azure portal.

- ![image](https://user-images.githubusercontent.com/39109137/177709509-21c0ebd0-e401-4126-b667-a0d7c527d48d.png)

**Comment by thejanek** [comment]
Hi Elena,
I have found solution for my issue. Issue is happening only on on large and complex terraform deployments. It looks like terraform or something is not handling large code (I'm deploying near 250 resources at once). When I am using 'terraform apply -target="nsg_roles"' every thing works fine but after "terraform apply" not... 

I have found in Azure "Activity logs" that my service principal (when I want to remove e.g. one specific NSG role) actually remove that role but... just after that he is creating exactly the same!!! 

Solution for this issue is to add lifecycle {create_before_destroy = true } in "azurerm_network_security_rule" section. like:


resource "azurerm_network_security_rule" "unic_nsgs_for_dedicated_subnets" {
  for_each = local.map_of_all_nsgs_for_dedicated_subnets

  resource_group_name = azurerm_resource_group.platform-resource-group-creation.name

  name                        = each.value.name
  network_security_group_name = each.value.network_security_group_name
  access                      = each.value.access
  direction                   = each.value.direction
  priority                    = each.value.priority
  protocol                    = each.value.protocol
  description                 = each.value.description

  source_port_range                     = each.value.source_port_range
  source_port_ranges                    = each.value.source_port_ranges
  source_address_prefix                 = each.value.source_address_prefix
  source_address_prefixes               = each.value.source_address_prefixes
  source_application_security_group_ids = each.value.source_application_security_group_names

  destination_port_range                     = each.value.destination_port_range
  destination_port_ranges                    = each.value.destination_port_ranges
  destination_address_prefix                 = each.value.destination_address_prefix
  destination_address_prefixes               = each.value.destination_address_prefixes
  destination_application_security_group_ids = each.value.destination_application_security_group_names

  lifecycle {
    # Without that Terraform will not destroy any NSG rule 
    # (actually it did but just after that terraform will one more time create the same  rule which we want to remove...)
    # It is happening on large terraform deployments
    create_before_destroy = true 
  }  
}

**Comment by sinbai** [comment]
@thejanek thanks for the detailed explanation, I believe this solution could help more people with the same problem as you. Thank you for your feedback.
