### ISSUE TITLE
Support for NGINXPLUS RP

### ISSUE THREAD

**Issue by puneetsarna** [hashicorp/terraform-provider-azurerm#17516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

NGINX for Azure is a new service that was just launched on Azure. This service requires subnets to be delegated to it for it function. Terraform is one of the use-cases that is used to bring up customer vnets and being able to delegate the subnet via terraform will be really nice.

Please allow option for `NGINX.NGINXPLUS` as a service that can be delegated to an Azure subnet.

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/network/subnet_resource.go#L86

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
Need to be able to do the following:


resource "azurerm_subnet" "nalb_pub" {
  name                 = "foo"
  resource_group_name  = "foo"
  virtual_network_name = "foo"
  address_prefixes     = ["10.0.0.0/16"]
    delegation {
      name = "nginx"
      service_delegation {
        name = "NGINX.NGINXPLUS/nginxDeployments"
      }
    }
}
```

**Comment by katbyte** [comment]
fixed by #17796
