### ISSUE TITLE
Support for "Split by dimensions" azurerm_monitor_scheduled_query_rules_alert 

### ISSUE THREAD

**Issue by ovidiubuligan** [hashicorp/terraform-provider-azurerm#17510]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is no way to add "Split by dimension" functionality. 
![image](https://user-images.githubusercontent.com/4757459/177346447-c78c8b08-3f3e-4ec8-8cea-02aa0607cf87.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

**Comment by teowa** [comment]
Hi @ovidiubuligan , a new https://github.com/hashicorp/terraform-provider-azurerm/pull/17772 will support `split_by_demensions`.
