### ISSUE TITLE
Event Hub Authorization Rule is not working as expected.

### ISSUE THREAD

**Issue by sathishkumar3009** [hashicorp/terraform-provider-azurerm#17511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13.0

### AzureRM Provider Version

2.58.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_authorization_rule

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_authorization_rule" "jira_notifications_consumer" {
  name                = "consumer"
  namespace_name      = azurerm_eventhub_namespace.jiranotifications.name
  eventhub_name       = core-shs-eun1
  resource_group_name = azurerm_resource_group.eventhub.name
  listen              = true
  send                = false
  manage              = false
}
```

### Debug Output/Panic Output

```shell
Error making Read request on Azure EventHub Authorization Rule List Keys : eventhub.EventHubsClient#ListKeys: Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 Code="" Message="The requested resource does not support http method 'POST'."
```

### Expected Behaviour

Creation of authorization Rule

### Actual Behaviour

Gives an error:
Error: Error making Read request on Azure EventHub Authorization Rule List Keys : eventhub.EventHubsClient#ListKeys: Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 Code="" Message="The requested resource does not support http method 'POST'."

### Steps to Reproduce

terraform apply.

**Comment by tguski** [comment]
I have also seen this issue where:
`resource "azurerm_eventhub_authorization_rule" "eh" {
  resource_group_name      = "{{ azure_resource_group_environment_id }}"
  namespace_name      = azurerm_eventhub_namespace.eh.name
  eventhub_name       = azurerm_eventhub.eh.name
  name                = "acc01"
  send                = true
}`
which has been working fine - started timing out then failing on retry returning the following:
`azurerm_eventhub_namespace.eh: Creation complete after 1m3s [id=/subscriptions/b16ac3ab-b7db-4ee9-8a93-99b1dafb4761/resourceGroups/tgusk318-eastus/providers/Microsoft.EventHub/namespaces/tguskiothub0t08e7ns01]
azurerm_eventhub.eh: Creating...
azurerm_eventhub.eh: Creation complete after 3s [id=/subscriptions/b16ac3ab-b7db-4ee9-8a93-99b1dafb4761/resourceGroups/tgusk318-eastus/providers/Microsoft.EventHub/namespaces/tguskiothub0t08e7ns01/eventhubs/tguskiothub0t08e7eh01]
azurerm_eventhub_authorization_rule.eh: Creating...

2022-07-06 02:04:39,914 - 0109:tgusk318 - root:module_utils - run_terraform - DEBUG - sleeping: 30 seconds before retrying terraform apply.
2022-07-06 02:05:09,945 - 0109:tgusk318 - root:module_utils - run_terraform - DEBUG - TRY 2: terraform apply -auto-approve -no-color
2022-07-06 02:05:20,113 - 0109:tgusk318 - root:module_utils - run_terraform - ERROR - ERROR running: terraform apply -auto-approve -no-color  : 
Error: Error making Read request on Azure EventHub Authorization Rule List Keys : eventhub.EventHubsClient#ListKeys: Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 Code="" Message="The requested resource does not support http method 'POST'."

  with azurerm_eventhub_authorization_rule.eh,
  on iothub.tf line 60, in resource "azurerm_eventhub_authorization_rule" "eh":
  60: resource "azurerm_eventhub_authorization_rule" "eh" {`

**Comment by gopinathrsv** [comment]
I started experiencing it today, it was working fine and started throwing following error message 
"Error: Error making Read request on Azure EventHub Authorization Rule List Keys : eventhub.EventHubsClient#ListKeys: Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 Code="" Message="The requested resource does not support http method 'POST'." 
Steps to repro
terraform init
terraform apply

**Comment by sathishkumar3009** [comment]
Can someone assist us on this issue.

**Comment by xiaxyi** [comment]
Hey guys, the cause should be the case sensitive handling of the authrRule id in the 2.58 azurerm provider. I can confirm the issue is handled in later release. can you try the latest version or azurerm provider?

**Comment by sathishkumar3009** [comment]
Hi xixayi,

      I tried with azurerm_provider version 3.7.0, facing different error. It's not giving the plan.

Error: parsing "/subscriptions/***************/resourcegroups/eventhub/providers/Microsoft.EventHub/namespaces/eventhub/eventhubs/sbx-audit-sre/authorizationrules/consumer": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

**Comment by PramodBobade** [comment]
@sathishkumar3009 can you please provide the minimum version of provider which has this fix?

**Comment by sathishkumar3009** [comment]
@PramodBobade - I'm not sure about that minimum version of this fix. If you are aware kindly share. @xiaxyi - Please let me know the exact version should i use.

**Comment by xiaxyi** [comment]
@sathishkumar3009  I added some logic to deal with the ID in the state, you can refer to the mentioned pr for more details.

**Comment by xiaxyi** [comment]
@sathishkumar3009  can you try using the latest released provider to refresh the state?

**Comment by sathishkumar3009** [comment]
@xiaxyi Can I use 3.14.0 ? that is the latest version.

**Comment by weldpua2008** [comment]
> @xiaxyi Can I use 3.14.0 ? that is the latest version.

What's the minimum azurerm version? We are using 2.50.0 and it will be a major issue to jump to 3.x.x now

**Comment by weldpua2008** [comment]
**If you can't upgrade azurerm (as I).**
You can use the following script to fix the state on "old" azurerm.
Please notice that some modules could require providing the subscription directly. So uncomment all related to `subscriptionFixApplied` and using sed fix the relevant files.


```bash
subscriptionFixApplied=""
LOG_PREFIX="${HOME}/.$0"
STATE_LIST_PATH="${LOG_PREFIX}/azurerm_eventhub_authorization_rule_$(date "+%Y%m%d_%H%M").txt"
mkdir -p ${LOG_PREFIX}
for st in $(terraform state list|grep azurerm_eventhub_authorization_rule| tee ${STATE_LIST_PATH});do
    resourceName="$(echo $st| tr -d '\r')"
    [[ -z "${resourceName}" ]] && continue
    [[  "${resourceName}" = " " ]] && continue
    resourceLogPath="${LOG_PREFIX}/${resourceName}$(date "+%Y%m%d_%H%M").txt"
    resourceLogCMDPath="${LOG_PREFIX}/${resourceName}_cmd$(date "+%Y%m%d_%H%M").txt"
    resourceId=$(terraform state  show $resourceName| tee ${resourceLogPath}  |grep id| grep --color=never -Eo '".*"'|cut -d '"' -f2)
    [[ -z "${resourceId}" ]] && continue
    [[  "${resourceId}" = " " ]] && continue
    [[ "${resourceId}" != *authorizationrules* ]] && continue
    resourceIdFixed=$(echo $resourceId| sed 's,authorizationrules,authorizationRules,' )
    echo " => ${resourceId}"
    echo "terraform state rm ${resourceName}" | tee ${resourceLogCMDPath}
    echo "terraform import  \"${resourceName}\" \"${resourceIdFixed}\"" | tee -a ${resourceLogCMDPath}
    # subscriptionId=$(echo $resourceIdFixed| grep -Eo 'subscriptions/(.*)/resourcegroups'| grep -Eo '/(.*)/'| head -1 | tr -d '/')
    # Fixing
    # Error: Error building AzureRM Client: 1 error occurred:
    #    * A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
    # if [[ "${subscriptionFixApplied}" != "yes" ]];then
    #     if [ "$(uname)" == "Darwin" ]; then
    #         macOssedFlags=" ''"
    #     fi
    #     if [[ -e "${subscriptionIdFixPath}" ]];then
    #         cp "${subscriptionIdFixPath}" "${subscriptionIdFixPath}__"
    #         sed  -i ${macOssedFlags} 's/subscription_id.*$/subscription_id = "'${subscriptionId}'"/' "${subscriptionIdFixPath}"
    #     fi
    #     subscriptionFixApplied="yes"
    # fi   
    terraform state rm "${resourceName}"
    terraform import  "${resourceName}" "${resourceIdFixed}" || terraform import  "${resourceName}" "${resourceIdFixed}"
done
# if [[ -e "${subscriptionIdFixPath}__" ]];then
#     cp "${subscriptionIdFixPath}__" "${subscriptionIdFixPath}"
#     rm -f "${subscriptionIdFixPath}__"
# fi
```
