### ISSUE TITLE
“staticCommunicationServices”: expected the segment “CommunicationServices” to be “communicationServices”

### ISSUE THREAD

**Issue by Venkateshdodda-MSFT** [hashicorp/terraform-provider-azurerm#17537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.5

### AzureRM Provider Version

v3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_communication_service

### Terraform Configuration Files

```hcl
Link of the issue where the customer reported https://docs.microsoft.com/en-us/answers/questions/916004/index.html
```

### Debug Output/Panic Output

```shell
parsing “/subscriptions//resourceGroups//providers/Microsoft.Communication/CommunicationServices/*-communcation”: parsing segment “staticCommunicationServices”: expected the segment “CommunicationServices” to be “communicationServices”
```

### Expected Behaviour

expected the segment “CommunicationServices” to be “communicationServices”

### Actual Behaviour

expected the segment “CommunicationServices” to be “communicationServices”

### Steps to Reproduce

please check this reported issue for details

### Important Factoids

NA

### References

Customer reported the issue in Microsoft Q&A https://docs.microsoft.com/en-us/answers/questions/916004/index.html and redirecting the customer to here on behalf of them

**Comment by tombuildsstuff** [comment]
hey @Venkateshdodda-MSFT 

Thanks for opening this issue - taking a look through here it appears there's another issue open for this (#17532) - as such I hope you don't mind but I'm going to close this issue in favour of that one.

Thanks!
