### ISSUE TITLE
Azure App Service Health Check fails

### ISSUE THREAD

**Issue by rlachic** [hashicorp/terraform-provider-azurerm#17546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Using Terraform to Deploy Azure Linux Container App Service I found if we use health check option, the HealthCheck is always falling. This is because there is needed as well a variable in the site config called:

**WEBSITE_HEALTHCHECK_MAXPINGFAILURE**

If you disable and enable the health check in Azure, the variable is created.

This variable should be created alongside the option: health_check_eviction_time_in_min

### Terraform Version

1.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
site_config{
health_check_path = local.health_check_path_backend
health_check_eviction_time_in_min = 5
```

### Debug Output/Panic Output

```shell
None
```

### Steps to Reproduce

terraform apply

**Comment by xiaxyi** [comment]
@rlachic May I know the detailed symptom?

**Comment by rlachic** [comment]
The Azure App Service keeps always Unhealthy and restarting in a loop. This is because with Terraform the App Service Configuration Variable is not set.

**Comment by xiaxyi** [comment]
@rlachic Thanks for the information, let me check the provider code, will submit the pr once confirmed it's a bug

**Comment by xiaxyi** [comment]
should relates to this issue https://github.com/hashicorp/terraform-provider-azurerm/issues/17123

**Comment by xiaxyi** [comment]
Hey @rlachic, may I know if you are still seeing this issue, it should be fixed now. Feel free to let me know if you have any questions

**Comment by rlachic** [comment]
Thanks!!
