### ISSUE TITLE
Support for Resource Scope in monitor_scheduled_query_rules_alert

### ISSUE THREAD

**Issue by jamietaffurelliriskscreen** [hashicorp/terraform-provider-azurerm#17544]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Documentation for [monitor_scheduled_query_rules_alert](ttps://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert) does not list the scope property that is available in the [ARM/Bicep documentation](https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/scheduledqueryrules?tabs=bicep).

The scopes property allows you filter what resource IDs are returned from scheduled queries, rather than running over all the resources that are logging to the workspace.

You can currently work around this missing property by either using Alert Processing Rules (which may be overkill) or explicitly filtering in your KQL query (which makes your query look messy).

Is there a reason for this property omission?

Additionally, there is a missing targetResourceTypes property that allows you to filter based on resource type (e.g. virtual machines)

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Potential Terraform Configuration

```hcl
Taken from docs with added scopes property

resource "azurerm_monitor_scheduled_query_rules_alert" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    action_group           = []
    email_subject          = "Email Header"
    custom_webhook_payload = "{}"
  }
  data_source_id = azurerm_application_insights.example.id
  description    = "Alert when total results cross threshold"
  enabled        = true
  # Count all requests with server error result code grouped into 5-minute bins
  query       = <<-QUERY
  requests
    | where tolong(resultCode) >= 500
    | summarize count() by bin(timestamp, 5m)
  QUERY
  severity    = 1
  frequency   = 5
  time_window = 30
  trigger {
    operator  = "GreaterThan"
    threshold = 3
  }
  scope = [
    "/subscriptions/xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/resourceGroups/rg"
  ]
}
```

**Comment by teowa** [comment]
Hi @jamietaffurelliriskscreen , this is because of API versions difference: current `azurerm_monitor_scheduled_query_rules_alert` is based on REST API [`2018-04-16`](https://github.com/Azure/azure-rest-api-specs/blob/e94b0da0c7f80e2986af90c1dd7e9c8f4c336c61/specification/monitor/resource-manager/Microsoft.Insights/stable/2018-04-16/scheduledQueryRule_API.json). And a newer `azurerm_monitor_scheduled_query_rules_alert_v2` (temp name) is under PR review which supports `scopes` and `target_resource_types` , see PR https://github.com/hashicorp/terraform-provider-azurerm/pull/17772
