### ISSUE TITLE
Support for extensions

### ISSUE THREAD

**Issue by sdahlbac** [hashicorp/terraform-provider-azurerm#17540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

How do i specify extensions https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-extensions

I need to be able to whitelist pgcrypto, and I do not see such an option in either `azurerm_postgresql_flexible_server` nor `azurerm_postgresql_flexible_server_configuration` (unless "azure.extensions" is a "[to be a valid PostgreSQL configuration name](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIER)" in this context.)

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

**Comment by sdahlbac** [comment]
After testing, it turns out that azure.extensions is indeed a valid PostgreSQL configuration name. The fact that it linked to upstream postgres docs led me to believe it was not. Perhaps a doc clarification would be in order?

**Comment by sinbai** [comment]
@sdahlbac thanks for opening this issue. PR #17580 has been submitted to clarify the usage of extensions for `azurerm_postgresql_flexible_server`.

**Comment by sinbai** [comment]
@sdahlbac Since PR #17580 has been released in [v3.14.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.14.0/CHANGELOG.md). Would you mind if we close this issue?
