### ISSUE TITLE
Update from 3.11 to >=3.12 forces recreation of `azurerm_linux_web_app` because `virtual_network_subnet_id` is null

### ISSUE THREAD

**Issue by anrub** [hashicorp/terraform-provider-azurerm#17559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.13.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app, azurerm_app_service_virtual_network_swift_connection

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = "myrg"
  location = "westeurope"
}

resource "azurerm_service_plan" "asp" {
  location            = "westeurope"
  name                = "asp"
  os_type             = "Linux"
  resource_group_name = azurerm_resource_group.rg.name
  sku_name            = "P1v3"
}

resource "azurerm_linux_web_app" "this" {
  name                = "asdf"
  location            = "westeurope"
  resource_group_name = azurerm_resource_group.rg.name
  service_plan_id     = azurerm_service_plan.asp.id
  https_only          = true

  site_config {
    always_on = true

    application_stack {
      docker_image     = "index.docker.io/nginxdemos/hello/"
      docker_image_tag = "latest"
    }

    minimum_tls_version    = "1.2"
    use_32_bit_worker      = false
    vnet_route_all_enabled = true
  }
}

resource "azurerm_app_service_virtual_network_swift_connection" "vnet_integration" {
  app_service_id = azurerm_linux_web_app.this.id
  subnet_id      = "/subscriptions/xx/resourceGroups/rg-xx-spoke-test/providers/Microsoft.Network/virtualNetworks/vnet-xx-test/subnets/snet-xx-test-appservice_subnet"
}

provider "azurerm" {
  features {}
  version = "3.11"
  # version "3.12" # forces recreation of the linux_webapp
}
```

### Debug Output/Panic Output

```shell
# azurerm_linux_web_app.this must be replaced
...
      - virtual_network_subnet_id         = "/subscriptions/xx/resourceGroups/rg-xx-spoke-test/providers/Microsoft.Network/virtualNetworks/vnet-xx-test/subnets/snet-xx-test-appservice_subnet" -> null # forces replacement
....


 # azurerm_app_service_virtual_network_swift_connection.vnet_integration must be replaced
...
```

### Expected Behaviour

No change in the infrastructure is expected, as the resource `app_service_virtual_network_swift_connection` is used to configure vnet integration and not the field virtual_network_subnet_id

### Actual Behaviour

When updating from azurerm 3.11 to >= 3.12 terraform wants to recreate the linux webapp and wants to set `virtual_network_subnet_id` to null, as the vnet integration is set through  `app_service_virtual_network_swift_connection`. 

### Steps to Reproduce

1. terraform apply with provider version 3.11
2. terraform apply with provider vesion 3.13
3. see replacement

### References

PR https://github.com/hashicorp/terraform-provider-azurerm/pull/17354 seems to introduce this change in 3.12

**Comment by bubbletroubles** [comment]
I've got a PR open #17582 which will hopefully fix this.

**Comment by jackofallops** [comment]
Hi @anrub - That property should be able to be managed with `ignore_changes` to prevent the change behaviour you're seeing, as documented here: https://www.terraform.io/language/meta-arguments/lifecycle#ignore_changes. We'll get this added to the note in the docs to more clearly explain this new property is incompatible with `azurerm_app_service_virtual_network_swift_connection` and this action is needed.  

I'll work with @bubbletroubles to make some changes to the implementation of this new property, as I believe it doesn't need to be `ForceNew` so should be able to replace the `azurerm_app_service_virtual_network_swift_connection` in user configs in future to manage that aspect of configuration in line. 

Hope this helps!
