### ISSUE TITLE
Synapse Role Assignment in Azure Government is not supported.

### ISSUE THREAD

**Issue by stonenw** [hashicorp/terraform-provider-azurerm#17564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_role_assignment" "example" {
  synapse_workspace_id = azurerm_synapse_workspace.example.id
  role_name            = "Synapse SQL Administrator"
  principal_id         = data.azurerm_client_config.current.object_id
}
```

### Debug Output/Panic Output

```shell
unavailable
```

### Expected Behaviour

A Synapse Workspace Role Assignment(s) be created as specified in the code. 

### Actual Behaviour

│ Error: Synapse is not supported in this Azure Environment

### Steps to Reproduce

Using the code provided with the azurerm_synapse_workspace resource,  I ran terraform init, then terraform apply to get the errors.
I do not get any warning when running terraform plan. 

### Important Factoids

I am trying to run this in Azure Government.

### References

Azure Synapse Workspace Availability in US Government
https://azure.microsoft.com/en-us/global-infrastructure/services/?rar=true&regions=non-regional,usgov-non-regional,us-dod-central,us-dod-east,usgov-arizona,usgov-texas,usgov-virginia&products=synapse-analytics

**Comment by adrian-gonzalez** [comment]
Hello -

My team is directly impacted by this bug on Azure US Gov. Is there an idea on where this is in the roadmap priorities?

**Comment by kottofy** [comment]
Related: https://github.com/hashicorp/terraform-provider-azurerm/issues/15443

**Comment by kottofy** [comment]
Works for me now. Thanks all!

**Comment by stonenw** [comment]
Same for me. I was able to verify this is functional now. Thank you. 

Seems to have been fixed in https://github.com/manicminer/hamilton/pull/186

And related too: https://github.com/hashicorp/terraform-provider-azurerm/issues/17362
