### ISSUE TITLE
Service Bus queue is always recreated, because partitioning can't be enabled

### ISSUE THREAD

**Issue by grgkro** [hashicorp/terraform-provider-azurerm#17561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.1.2

### AzureRM Provider Version

2.71.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_queue

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_queue" "my_queue_consumer" {
  name                = "my-name"
  resource_group_name = "my-rg"
  namespace_name      = "my-namespace"

  enable_partitioning = true
}
```

### Debug Output/Panic Output

```shell
none, plan and apply job succeed
```

### Expected Behaviour

Throw an error when partitioning can't be enabled (It isn't available for the Premium messaging SKU)

### Actual Behaviour

Apply Job succeeds -> Service Bus Queue get's created without partitioning enabled, and you don't get notified in the apply job logs, only in the plan jobs (which you often don't read if everything succeeded...). 

This is bad because the next time you run your terraform script for whatever change you made (doesn't need to be in the Service Bus), terraform will destroy your queue and recreate it. The reason: Terraform sees that the existing queue has partitioning disabled, and in the terraform script it says that it should be enabled. Partitioning can't be enabled at an existing queue, so it destroys the existing queue and recreates this. But for Premium tier it's not possible at all to enable partitioning (https://docs.microsoft.com/en-us/azure/service-bus-messaging/enable-partitions), so it will create it again with partitioning disabled.

The result: Your customer calls you because they can't access the messages in the queue anymore, because a different access string (authorization rule) get's created with the recreation of the queue. Also there's a downtime, messages will get lost (read and send rule are recreated) and in our case terraform didn't even recreate the authorization rules at all, as when it runs the apply job, the authorization rules are still there. Then in the apply job, terraform deletes the queue with the authorization rule without understanding that it then also needs to recreate the authorization rule.

### References

The bug was already mentioned here: https://github.com/hashicorp/terraform-provider-azurerm/issues/5606

**Comment by xiaxyi** [comment]
@grgkro Thanks, I can reproduce the same issue. I will add code to check the property first as it seems to be supported in the past.

**Comment by xiaxyi** [comment]
@grgkro Can you try the latest released azurerm provider to see if issue is fixed from your side? Feel free to let us know if there is anything needed.

**Comment by grgkro** [comment]
Sorry, we updated now to the latest version, but it's too much work now to replicate the error again (if it's even possible) and as long as everything works, I don't want to play around with it. So thank you for taking some time for this, if it happens again, I will report again.
