### ISSUE TITLE
Lifecycle module "ignore_changes" issue on azurerm_sql_database

### ISSUE THREAD

**Issue by jaideepsra** [hashicorp/terraform-provider-azurerm#17579]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_sql_database" "messaging" {
  lifecycle {
    ignore_changes = [
      import
    ]
  }
  name                = "${var.environment}-messaging"
  resource_group_name = azurerm_resource_group.main.name
  location            = var.location
  tags = (merge(
    var.common_tags,
    {
      "Cost_Centre" = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    }
  ))
  server_name                      = azurerm_sql_server.main.name
  requested_service_objective_name = "ElasticPool"
  edition                          = var.db_elastic_authoring_database_edition
  elastic_pool_name                = azurerm_mssql_elasticpool.authoring.name

   import {
     storage_uri                  = var.db_storageaccount_messaging_uri
     storage_key                  = var.db_storageaccount_key
     storage_key_type             = var.db_storageaccount_key_type
     administrator_login          = azurerm_sql_server.main.administrator_login
     administrator_login_password = azurerm_sql_server.main.administrator_login_password
     authentication_type          = var.db_authentication_type
   }
}
```

### Debug Output/Panic Output

```shell
Terraform v1.1.8
on linux_amd64
Initializing plugins and modules...
module.databases.azurerm_sql_database.messaging: Modifying... [id=/subscriptions/resourceGroups/xxxxxxxxx-rg/providers/Microsoft.Sql/servers/xxxxxxxxx-sql01/databases/xxxxxxxxx-messaging]
module.databases.azurerm_sql_database.messaging: Still modifying... [id=/subscriptions/...-sql01/databases/xxxxxxxxx-messaging, 10s elapsed]
.
.
.
module.databases.azurerm_sql_database.messaging: Still modifying... [id=/subscriptions/...-sql01/databases/xxxxxxxxx-messaging/databases/xxxxxxxxx-messaging, 15m10s elapsed]
module.databases.azurerm_sql_database.messaging: Still modifying... [id=/subscriptions/...-sql01/databases/xxxxxxxxx-messaging/databases/xxxxxxxxx-messaging, 15m20s elapsed]
╷
│ Error: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=400 -- Original Error: Code="BadRequest" Message="The ImportExport operation with Request Id 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' failed due to 'Target database is not empty. The import operation can only be performed on an empty database.'." Details=[] InnerError={"multi":[]}
│ 
│   with module.databases.azurerm_sql_database.messaging,
│   on modules/sql-databases/main.tf line 633, in resource "azurerm_sql_database" "messaging":
│  633: resource "azurerm_sql_database" "messaging" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```

### Expected Behaviour

The tag update triggers the sql db import which should have been ignored under lifecylce module. I can find a similar issue but here I'm suspecting the issue with lifecycle module

https://github.com/hashicorp/terraform-provider-azurerm/issues/3991

### Actual Behaviour

The tag update is not done but db import starts and eventually fails as db is not empty

### Steps to Reproduce

terraform apply -> modify resource

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/3991

**Comment by sinbai** [comment]
@jaideepsra thank you for opening this issue here. The azurerm_sql_database resource is deprecated and will be removed in the next major version of the AzureRM Provider, as such this resource is feature-frozen. Could you use the azurerm_mssql_database resource instead of azurerm_sql_database?

**Comment by sinbai** [comment]
@jaideepsra Given the above context, are you okey if we close this issue?
