### ISSUE TITLE
Support for storage_account_customer_managed_key in the azurerm_storage_account resource

### ISSUE THREAD

**Issue by mkbruhaas** [hashicorp/terraform-provider-azurerm#17592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have run into scenarios at Enterprise Azure accounts where policies explicitly requiring customer managed keys (deployment deny if CMEK isn't present) on storage accounts is a required security control. This forces the use ARM templates for the deployment of all storage accounts. 
If this syntax is available via ARM, can't it be added so that for this scenario storage accounts can be deployed via arm?

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account, azurerm_storage_account_customer_managed_key

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "examplestor"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  identity {
    type = "SystemAssigned"
  }
  customer_managed_key{
    key_vault_id = azurerm_key_vault.example.id
    key_name     = azurerm_key_vault_key.example.name
  }

}
```

**Comment by magodo** [comment]
@mkbruhaas Are you looking for [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#customer_managed_key)?

**Comment by tombuildsstuff** [comment]
Closing since per @magodo's comment above, this functionality is available.
