### ISSUE TITLE
Impossible to set a subnet delegation with service "Microsoft.Orbital/orbitalGateways"

### ISSUE THREAD

**Issue by astraios** [hashicorp/terraform-provider-azurerm#17597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.13.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "orbital_delegated" {
  name                 = "snet-orbital-delegated"
  resource_group_name  = data.azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["172.20.0.0/24"]

  delegation {
    name = "orbital"
    service_delegation {
      name = "Microsoft.Orbital/orbitalGateways"
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected delegation.0.service_delegation.0.name to be one of [Microsoft.ApiManagement/service Microsoft.AzureCosmosDB/clusters Microsoft.BareMetal/AzureVMware Microsoft.BareMetal/CrayServers Microsoft.Batch/batchAccounts Microsoft.ContainerInstance/containerGroups Microsoft.ContainerService/managedClusters Microsoft.Databricks/workspaces Microsoft.DBforMySQL/flexibleServers Microsoft.DBforMySQL/serversv2 Microsoft.DBforPostgreSQL/flexibleServers Microsoft.DBforPostgreSQL/serversv2 Microsoft.DBforPostgreSQL/singleServers Microsoft.HardwareSecurityModules/dedicatedHSMs Microsoft.Kusto/clusters Microsoft.Logic/integrationServiceEnvironments Microsoft.MachineLearningServices/workspaces Microsoft.Netapp/volumes Microsoft.Network/managedResolvers Microsoft.PowerPlatform/vnetaccesslinks Microsoft.ServiceFabricMesh/networks Microsoft.Sql/managedInstances Microsoft.Sql/servers Microsoft.StoragePool/diskPools Microsoft.StreamAnalytics/streamingJobs Microsoft.Synapse/workspaces Microsoft.Web/hostingEnvironments Microsoft.Web/serverFarms], got Microsoft.Orbital/orbitalGateways
│
│   with azurerm_subnet.orbital_delegated,
│   on network.tf line 34, in resource "azurerm_subnet" "orbital_delegated":
│   34:       name = "Microsoft.Orbital/orbitalGateways"
│
╵
```

### Expected Behaviour

I'm expecting the service delegation to be configured.

### Actual Behaviour

I'm getting an error stoping the azurerm_subnet configuration.

### Steps to Reproduce

* Set a Resource Group
* Set a Virtual Network
* Create a TF so setup a subnet with a service delegation to "Microsoft.Orbital/orbitalGateways"
* terraform plan

**Comment by jiaweitao001** [comment]
Hi, this is a known issue. We are actively working on it to add `orbitalGateways` to service delegation list. Thanks.

**Comment by astraios** [comment]
While waiting for a fix, we deployed the subnet and configured the delegation manually. Now with this release, I decided to configure the subnet delegation via terraform. when running plan I get the following output:

```
~ delegation {
          ~ name = "Microsoft.Orbital.orbitalGateways" -> "orbital"

          ~ service_delegation {
              ~ actions = [
                  - "Microsoft.Network/publicIPAddresses/join/action",
                  - "Microsoft.Network/virtualNetworks/subnets/join/action",
                  - "Microsoft.Network/virtualNetworks/read",
                  - "Microsoft.Network/publicIPAddresses/read",
                ]
              ~ name    = "Microsoft.Orbital/orbitalGateways" -> "Microsoft.Orbital/orbitalGateway"
            }
        }
```

Moreover, when trying to use that value in the delegation service_delegation.name property, terraform apply returns with the following error:
```
The service name Microsoft.Orbital/orbitalGateway specified on delegation /subscriptions/<redacted>/resourceGroups/rg-redacted/providers/Microsoft.Network/virtualNetworks/vnet-redacted/subnets/snet-orbital-delegated/delegations/Microsoft.Orbital.orbitalGateways is not valid.
```
