### ISSUE TITLE
Terraform Delete on a NSG Association does not consider the NSG ID

### ISSUE THREAD

**Issue by M-Flexi** [hashicorp/terraform-provider-azurerm#17600]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet_network_security_group_association

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "oldnsg" {
  name                = "oldnsg"
  location            = var.azure_region
  resource_group_name = data.azurerm_resource_group.someresourcegroup.name

}

resource "azurerm_subnet_network_security_group_association" "oldasso" {
  subnet_id                 = data.azurerm_subnet.somesubnet.id
  network_security_group_id = azurerm_network_security_group.oldnsg.id
}
```

### Debug Output/Panic Output

```shell
.
```

### Expected Behaviour

When running Terraform destroy on a NSG association resource, Terraform should consider the provided NSG id to prevent deletion of a new association.

### Actual Behaviour

Terraform tries to destroy the new association, it doens't seem to consider the NSG id.
  
# azurerm_subnet_network_security_group_association.xxx will be destroyed
  - resource "azurerm_subnet_network_security_group_association" "oldasso" {
      - id                        = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx" -> null
      - network_security_group_id = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/networkSecurityGroups/**newnsg**" -> null
      - subnet_id                 = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx" -> null
    }

### Steps to Reproduce

- create an nsg and association on a subnet
- manually change the association to a new nsg
- terraform destroy the former nsg and association
- experience that the destroy output is trying to delete the new association

**Comment by tombuildsstuff** [comment]
@M-Flexi this is covered by the `terraform refresh` which happens automatically prior to an apply/destroy, where if these differ the association resource will be marked as gone - so this shouldn't be needed.

As such it sounds like that isn't happening here - can you provide the debug output for this?

Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the debug output. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
