### ISSUE TITLE
Provider error for keyvault

### ISSUE THREAD

**Issue by bamboi-andrei** [hashicorp/terraform-provider-azurerm#17638]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7 ( windows) 

### AzureRM Provider Version

3.13.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
.....
resource "azurerm_key_vault_secret" "acr-login-server" {
  name         = "${var.service_name}-acr-login-server"
  value        = azurerm_container_registry.acr.login_server
  key_vault_id = data.azurerm_key_vault.journal_tx_kv.id
}
resource "azurerm_key_vault_secret" "acr-admin-username" {
  name         = "${var.service_name}-acr-admin-username"
  value        = azurerm_container_registry.acr.admin_username
  key_vault_id = data.azurerm_key_vault.journal_tx_kv.id
}
  resource "azurerm_key_vault_secret" "acr-admin-password" {
  name         = "${var.service_name}-acr-admin-password"
  value        = azurerm_container_registry.acr.admin_password
  key_vault_id = data.azurerm_key_vault.journal_tx_kv.id
}
....
```

### Debug Output/Panic Output

```shell
azurerm_key_vault_secret.acr-login-server: Still creating... [2m0s elapsed]
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_key_vault_secret.acr-admin-username, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was  
│ present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```

### Expected Behaviour

Expect the resources be created and also imported in tfstate

### Actual Behaviour

The resources are actually created but not preserved in tfstate.

**Comment by magodo** [comment]
@bamboi-andrei This duplicates to #11059, would you please subscribe that issue for any update?
