### ISSUE TITLE
Assing ASG to a private Endpoint

### ISSUE THREAD

**Issue by L-u-k-e-GIT** [hashicorp/terraform-provider-azurerm#17665]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Use-cases

I search on different sites, but I do not find a way to associate an ASG (application security group) to a private endpoint.
Is there a way to do it with terraform as for the resource "azurerm_network_interface_application_security_group_association" is used to associate an ASG to a NIC?
Attempted Solutions

Tried "azurerm_network_interface_application_security_group_association", but does not work
Proposal

### New or Affected Resource(s)/Data Source(s)

azurerm_private_endpoint_application_security_group_association

### Potential Terraform Configuration

```hcl
Develop azurerm_private_endpoint_application_security_group_association

resource "zurerm_private_endpoint_application_security_group_association" "asg-nic" {

private_endpoint_id = var.pe_id #
application_security_group_id = var.asg.id

}
```

**Comment by liuwuliuyun** [comment]
This is because in currently, we dont implement 
/SUBSCRIPTIONS/{}/RESOURCEGROUPS/{}/PROVIDERS/MICROSOFT.NETWORK/PRIVATEENDPOINTS/{}
yet, it contains a property called applicationSecurityGroups which should implement your request.

**Comment by Yakuza-UA** [comment]
I have a similar request. It would be nice if Private Endpoint can be assigned to ASG post-creation. Currently Terraform reports an error:
```
Error: updating Application Security Group Association for Network Interface: (Name "[MASKED]" / Resource Group "[MASKED]"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CannotModifyNicAttachedToPrivateEndpoint" Message="Network interface /subscriptions/[MASKED]/resourceGroups/[MASKED]/providers/Microsoft.Network/networkInterfaces/[MASKED] is linked to a private endpoint /subscriptions/[MASKED]/resourceGroups/[MASKED]/providers/Microsoft.Network/privateEndpoints/[MASKED]. It can not be modified by user." Details=[]
```

This can be done via portal, however, even after PE was created. Thanks!

**Comment by tombuildsstuff** [comment]
@liuwuliuyun we intentionally don't implement this within the `azurerm_private_endpoint` resource - see the `zurerm_private_endpoint_application_security_group_association` resource above

**Comment by L-u-k-e-GIT** [comment]
> in currently, we dont implement
> /SUBSCRIPTIONS/{}/RESOURCEGROUPS/{}/PROVIDERS/MICROSOFT.NETWORK/PRIVATEENDPOINTS/{}
> yet, it contains a property called applicationSecurityGroups wh

Hi in the Documentation I don't see such a property
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint

**Comment by L-u-k-e-GIT** [comment]
any news? 
thought the portal is possible to assign an asg to private endpoint during creation? how can I perform this with tf?

**Comment by tombuildsstuff** [comment]
@L-u-k-e-GIT the comments a little vague (it's available in the API/SDK but not in TF) - which is why that's been marked off-topic fwiw. As mentioned in my other comment above, this'll need to be implemented as a new Virtual Resource - this isn't available at this point in time and this Feature Request is tracking adding support for it.

**Comment by L-u-k-e-GIT** [comment]
@tombuildsstuff thank for clarification.

**Comment by mpmatti** [comment]
The same issue applies to associating NSG to PE NIC.

`Error: updating Security Group Association for Network Interface: (Name "pe-xxxx.nic..." / Resource Group "RGtest"): network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CannotModifyNicAttachedToPrivateEndpoint" Message="Network interface 
/subscriptions/xxx/resourceGroups/RGtest/providers/Microsoft.Network/networkInterfaces/pe-xxxx.nic... is linked to a private endpoint 
/subscriptions/xxx/resourceGroups/RGtest/providers/Microsoft.Network/privateEndpoints/pe-xxxx. It can not be modified by user." Details=[]	`

**Comment by MohamedAnouar** [comment]
I tried using azurerm_network_interface_application_security_group_association and got the same error as [mpmatti]. Do we have any date when this feature will be integrated ?

**Comment by Yakuza-UA** [comment]
Any update on this? Private Endpoints and Network Policies for Private Endpoints are now GA, aren't they?

**Comment by MohamedAnouar** [comment]
+1, any updates ? 
 @hc-github-team-tf-azure

**Comment by liuwuliuyun** [comment]
Hi all, I took the liberty of adding a new resource called `azurerm_private_endpoint_application_security_group_association` to solve the issue. Welcome to comment on my PR.
