### ISSUE TITLE
`azurerm_monitor_action_rule_suppression` should have optional `end_date_utc`

### ISSUE THREAD

**Issue by philwelz** [hashicorp/terraform-provider-azurerm#17678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If you create a `azurerm_monitor_action_rule_suppression` resource via Terraform, `end_date_utc` is required as per Terraform [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_action_rule_suppression#end_date_utc).

If you create this rule via Portal, the End date is optional. Terraform should also support this value as optional.

IT would be also good to seperate the date from the time, like it is done with [bicep](https://docs.microsoft.com/en-us/azure/templates/microsoft.alertsmanagement/actionrules?tabs=bicep).

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_action_rule_suppression

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_action_rule_suppression" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.rg.name
  description         = "Example"

  scope {
    type         = "ResourceGroup"
    resource_ids = [azurerm_resource_group.rg.id]
  }

  suppression {
    recurrence_type = "Weekly"

    schedule {
      start_date = "2022-03-03"
      start_time_utc = "02:00:00Z"
      end_time_utc = "04:00:00Z"
      recurrence_weekly = ["Tuesday"]
    }
  }
}
```

**Comment by teowa** [comment]
@philwelz This is cause by REST API version differences, this `azurerm_monitor_action_rule_suppression` is based on an old API version [`2019-05-05-preview`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/preview/2019-05-05-preview/ActionRules.json#L731), which need `end_date` to be required. Action Rule in portal in based on a newer API version, maybe is [`2021-08-08`](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/alertsmanagement/resource-manager/Microsoft.AlertsManagement/stable/2021-08-08/AlertProcessingRules.json#L544), which can have a optional `end_date`. 
Besides, a newer version of Action Rule in TF based on newer API version is in [PR review](https://github.com/hashicorp/terraform-provider-azurerm/pull/17006), you can try it in near future.
