### ISSUE TITLE
Storage Object Replication does not support cross-tenant

### ISSUE THREAD

**Issue by fsschmitt** [hashicorp/terraform-provider-azurerm#17677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_object_replication

### Terraform Configuration Files

```hcl
resource "azurerm_storage_object_replication" "anonymize_replication" {
  source_storage_account_id      = var.source_storage_account_id
  destination_storage_account_id = var.destination_storage_account_id
  rules {
    source_container_name      = var.source_container_name
    destination_container_name = var.destination_container_name
    copy_blobs_created_after   = "OnlyNewObjects"
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/fsschmitt/1928fb7d2f26c49f15b7ff9ca93c3795
```

### Expected Behaviour

For the `Object Storage Replication` instance to be initialized as it is when done manually on the `Azure Portal` by specifying in the `JSON`:
```
/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Storage/storageAccounts/<storage-account-name>
```
for both source and destination.

### Actual Behaviour

```
module.blob_storage_backup_anonymize_replication["blob_storage_backup_anonymize_replication"].azurerm_storage_object_replication.anonymize_replication: Creating...
module.blob_storage_backup_anonymize_replication["blob_storage_backup_anonymize_replication"].azurerm_storage_object_replication.anonymize_replication: Still creating... [10s elapsed]
╷
│ Error: creating Storage Object Replication "<REDACTED>" for source storage account name "stprod": objectreplicationpolicies.ObjectReplicationPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="InvalidAuthenticationTokenTenant" Message="The access token is from the wrong issuer 'https://sts.windows.net/<AZURE-TENANT-SOURCE-ID-REDACTED>/'. It must match the tenant 'https://sts.windows.net/<AZURE-TENANT-DESTINATION-ID-REDACTED>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<AZURE-TENANT-DESTINATION-ID-REDACTED>' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later."
│ 
│   with module.blob_storage_backup_anonymize_replication["blob_storage_backup_anonymize_replication"].azurerm_storage_object_replication.anonymize_replication,
│   on ../modules/blob_storage_replication/replication.tf line 1, in resource "azurerm_storage_object_replication" "anonymize_replication":
│    1: resource "azurerm_storage_object_replication" "anonymize_replication" {
│ 
╵
```

### Steps to Reproduce

1. Have two subscriptions in two different AD Tenants
2. Add `azurerm_storage_object_replication` across two different subscriptions on two different AD Tenants
3. Apply the resource

### Important Factoids

Subscriptions are in different AD Tenants

### References

All these issue below target `cross subscription` and not `cross subscription & tenant`.

https://github.com/hashicorp/terraform-provider-azurerm/issues/15533
https://github.com/hashicorp/terraform-provider-azurerm/issues/14454
https://github.com/hashicorp/terraform-provider-azurerm/issues/8647
https://github.com/hashicorp/terraform-provider-azurerm/pull/15603

**Comment by magodo** [comment]
@fsschmitt For cross tenant scenario, did you specify the [`auxiliary_tenant_ids`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#auxiliary_tenant_ids)?

**Comment by fsschmitt** [comment]
To be honest, I did not know about this.

If it works, then we could add a note in the `azurerm_storage_object_replication` documentation a not about it.

Let me try it and I'll let you know as soon as I tested it.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Comment by simaotwx** [comment]
I had to add a second provider and explicitly specify it, otherwise it would time out on plan and fail with errors like `Error: retrieving Subscription (Subscription: "***"): authorizing request: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '***' was not found in the directory ...`

```hcl
provider "azurerm" {
  auxiliary_tenant_ids = [
    "..."
  ]
  alias = "azurerm2"
}
```
```hcl
resource "azurerm_storage_object_replication" "replication" {
  provider                       = azurerm.azurerm2
  // ...
}
```

But now I get following error:

```
│ Error: creating Storage Object Replication for destination storage account name "...": authorizing request: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier '***' was not found in the directory 'xxx'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant. ...
```

Is there some documentation that explains how this works? Does the service principal used for Terraform deployment need to be somehow added to the other tenant?
