### ISSUE TITLE
Support for count and/or for_each in ip_configuration

### ISSUE THREAD

**Issue by Otimun** [hashicorp/terraform-provider-azurerm#17681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating services on a F5 device in Azure, it is desirable to be able to create multiple public IP addresses as secondary addresses on the external interface of the VM. At this point the azurerm_network_interface supports count or for_each but only inside of the resource itself.

In order not to need to add on a new ip_configuration every time you need a new virtual server it would be benificial to be able to use for_each or count inside of the ip_configuration part of this resource.  This feature has been requested before in issue #1002 and was said to be fixed with terraform 0.11, but using Terraform v1.2.5 and azurerm v3.12.0 this still does not seem to work.  I either receive one of these errors:

An argument named "count" is not expected here.
An argument named "for_each" is not expected here.

### New or Affected Resource(s)/Data Source(s)

azurerm_network_interface ip_configuration

### Potential Terraform Configuration

```hcl
resource "azurerm_public_ip" "external_public_virtual" {
  count              = var.virtual_server_count
  name               = "public_virtual_${count.index + 1}"
  location            = data.azurerm_resource_group.tfresourcegroup.location
  resource_group_name = data.azurerm_resource_group.tfresourcegroup.name
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = local.tags
}

resource "azurerm_network_interface" "external_interface" {
  name                 = "nic_${lower(element(var.hostnames, count.index))}_external"
  location             = data.azurerm_resource_group.tfresourcegroup.location
  resource_group_name  = data.azurerm_resource_group.tfresourcegroup.name
  enable_ip_forwarding = true
  ip_configuration {
    for_each                      = azurerm_public_ip.external_public_virtual
    name                          = "virtual_server${count.index + 1}"
    subnet_id                     = data.azurerm_subnet.subnets["external"].id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.external_public_virtual[count.index].id
  }
  tags = local.tags
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/1002

**Comment by tombuildsstuff** [comment]
hi @Otimun 

Thanks for opening this issue.

You can use Terraform's `dynamic` blocks for this: https://www.terraform.io/language/expressions/dynamic-blocks

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader configuration questions are raised [on the Community Discuss forum](https://discuss.hashicorp.com) - as such I'm going to close this issue for the moment, but should you have further usage questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
