### ISSUE TITLE
azurerm_advanced_threat_protection: error response cannot be parsed

### ISSUE THREAD

**Issue by jamesbwilkinson** [hashicorp/terraform-provider-azurerm#17698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_advanced_threat_protection

### Terraform Configuration Files

```hcl
resource "azurerm_advanced_threat_protection" "example_synapse_sql_pool" {
  target_resource_id = azurerm_synapse_sql_pool.synapse_sql_pool.id
  enabled            = true
}
```

### Debug Output/Panic Output

```shell
Error: updating Advanced Threat protection for "/subscriptions/***/providers/Microsoft.Synapse/workspaces/***/sqlPools/***": security.AdvancedThreatProtectionClient#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
│ 
│   with azurerm_advanced_threat_protection.synapse_sql_pool,
│   on synapse.tf line 167, in resource "azurerm_advanced_threat_protection" "synapse_sql_pool":
│  167: resource "azurerm_advanced_threat_protection" "adt_synapse_sql_pool" {
│ 
╵
time=2022-07-20T15:23:07Z level=error msg=1 error occurred:
	* exit status 1
```

### Expected Behaviour

Advanced threat protection is enabled on Azure Synapse Sql Pool (or at least an understandable error message)

### Actual Behaviour

Deployment fails with error:
 Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF

### Steps to Reproduce

Try to enable advanced threat protection to Azure Synapse SQL Pool.

**Comment by myc2h6o** [comment]
Hi @jamesbwilkinson thanks for opening the issue! Synapse Workspace has its own resource to configure the Advanced Threat Protection due to the Azure API design. Could you try [azurerm_synapse_workspace_security_alert_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace_security_alert_policy)?

**Comment by jamesbwilkinson** [comment]
Thank you @myc2h6o , it was not obvious but you are correct, this seems to enable the setting.
