### ISSUE TITLE
Nat Gateway Association Hangs Intermittently 

### ISSUE THREAD

**Issue by AndrewHuddleston** [hashicorp/terraform-provider-azurerm#17690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.5

### AzureRM Provider Version

2.87.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet_nat_gateway_association

### Terraform Configuration Files

```hcl
resource "azurerm_subnet_nat_gateway_association" "k8s" {
  subnet_id = azurerm_subnet.k8s.id
  nat_gateway_id = azurerm_nat_gateway.k8s.id
}
```

### Debug Output/Panic Output

```shell
azurerm_subnet_nat_gateway_association.k8s: Still creating... [18m20s elapsed]
```

### Expected Behaviour

The association creates quickly on the times it works

### Actual Behaviour

Hangs intermittently, one run works quickly, then a few runs later it hangs 

### Steps to Reproduce

This is just on Terraform Apply

**Comment by magodo** [comment]
@AndrewHuddleston Thank you for submitting this! Could you please provide the provider debug log so that I can better look into this?

**Comment by AndrewHuddleston** [comment]
I figured out the issue, too many things were trying to associate to the same subnet at the same time, sometimes it worked, but now that I put on depends on so they create sequentially instead of parallel it works
