### ISSUE TITLE
support for Azure Frontdoor standard/premium

### ISSUE THREAD

**Issue by vermegi** [hashicorp/terraform-provider-azurerm#17721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the azurerm terraform provider has a azurerm_frontdoor resource. This resource however creates a Azure Frontdoor instance in the 'Classic' SKU. It is currently not possible to create an Azure Front Door in the new Standard/Premium sku.

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Potential Terraform Configuration

```hcl
Property and configuration-wise this should be close to the [bicep config](https://docs.microsoft.com/en-us/azure/frontdoor/create-front-door-bicep?tabs=CLI#review-the-bicep-file)
```

**Comment by bubbletroubles** [comment]
Take a look at the azurerm_cdn_frontdoor resources.... some of the resources are there, but not all.

![image](https://user-images.githubusercontent.com/42738824/180416490-6b90e914-afda-4cb3-a4ac-58276ac975d0.png)

**Comment by vermegi** [comment]
I am looking at the docs for version 3.14 (latest), and I see 

![image](https://user-images.githubusercontent.com/1042817/180417513-cfb396f2-20e7-40ba-9c73-824c4c5a5462.png)

I don't see origin nor origin_group. 

Are you seeing a version that I am not seeing?

**Comment by vermegi** [comment]
Ok, nvm the above comment. I need to be on version 3.15 ... refreshing a page can help ...

**Comment by vermegi** [comment]
Just support for routes through Microsoft.Cdn/profiles/afdEndpoints/routes@2021-06-01 is missing still.

**Comment by manojsgh** [comment]
are these features still in devlopment?
1 - Add domain
2 - Front Door Manager (Add a route)
3 - Routes association
4 - Add Security policies
5 - Rule set

any timeline please ?

**Comment by ag1316** [comment]
Just checking in to see if there are any updates on this

Thanks!

**Comment by WodansSon** [comment]
> Without support for route creation and route association, these other resources feel pretty useless. Any time line on when we can get these other resources?

Hi @donwlewis, once PR #18010 is merged I will be implementing the last of the remaining CDN Front Door resources, which are:

* `azurerm_cdn_frontdoor_route`
* `azurerm_cdn_frontdoor_custom_domain`
* `azurerm_cdn_frontdoor_custom_domain_txt_validator`
* `azurerm_cdn_frontdoor_custom_domain_secret_validator`

Unfortunately I am not able to comment on an ETA here as having the PR reviewed and merged is a process outside of my control. That said, these resources are a top priority for the AzureRM provider so I feel fairly confidant that they will get the level of attention they deserve. 🙂

**Comment by manojsgh** [comment]
Guys for now I am using null_resource with provisioners. Power shell script to do rest of the job using local_exec.

**Comment by randompixel** [comment]
I can't seem to find an option to get the `X-Azure-FDID` header with this version like we could with `azurerm_frontdoor`
<img width="658" alt="image" src="https://user-images.githubusercontent.com/2316601/188642138-2cdd78aa-b90d-47fb-b6b2-33c539b0e0ca.png">

Unless it is the same as `azurerm_cdn_frontdoor_profile.*.resource_guid` and the docs aren't very clear?
