### ISSUE TITLE
Support for env var ARM_CLIENT_CERTIFICATE

### ISSUE THREAD

**Issue by markushinz** [hashicorp/terraform-provider-azurerm#17741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to the [azuread provider docs](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/guides/service_principal_client_certificate#environment-variables), the **azuread** (!)  provider supports service principal authentication with the ARM_CLIENT_CERTIFICATE env var (base64 encoded .pfx file contents). It would be great if the **azurerm** (!) provider would support that, too. It is not mentioned in the [azurerm provider docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate) and I verified that it is not supported (using v3.15.0 provider version and v1.2.5 terraform version).

There is [a closed issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/14107) regarding the same feature request but no one seemed to work on it.

### New or Affected Resource(s)/Data Source(s)

none

### Potential Terraform Configuration

```hcl
export ARM_CLIENT_CERTIFICATE="$(base64 file.pfx)"
```

**Comment by manicminer** [comment]
Thanks for requesting @markushinz. We'd like to add this feature to the AzureRM provider, alas it depends on another body of work involving the underlying SDK, which we're currently working on. Once we reach a certain point with this work, we'll be able to include this feature relatively easily.

Whilst this addition was already planned, I'll keep this issue open to track it specifically.

**Comment by manicminer** [comment]
This was released in AzureRM provider version v3.44.1
