### ISSUE TITLE
`azurerm_resource_group_policy_assignment` returns status 500 InternalServerError

### ISSUE THREAD

**Issue by heoelri** [hashicorp/terraform-provider-azurerm#17761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_policy_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group_policy_assignment" "pod_security_baseline" {
  name                 = "pod-security-baseline"
  resource_group_id    = azurerm_resource_group.stamp.id
  policy_definition_id = "/providers/Microsoft.Authorization/policySetDefinitions/a8640138-9b0a-4a28-b8cb-1666c838647d"
  display_name         = "Kubernetes cluster pod security baseline standards for Linux-based workloads"
}
```

### Debug Output/Panic Output

```shell
module.stamp["uksouth"].azurerm_resource_group_policy_assignment.pod_security_baseline: Still creating... [7m30s elapsed]
╷
│ Error: creating Policy Assignment ID: (Assignment Name "pod-security-baseline" / Scope "/subscriptions/cb8d2bb0-****-****-****-cde33c0320a4/resourceGroups/afe2e493c-stamp-uksouth-rg"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalServerError" Message="Encountered an internal server error. The tracking id is '00000000-0000-0000-0000-000000000000'."
│ 
│   with module.stamp["uksouth"].azurerm_resource_group_policy_assignment.pod_security_baseline,
│   on modules/stamp/policy.tf line 5, in resource "azurerm_resource_group_policy_assignment" "pod_security_baseline":
│    5: resource "azurerm_resource_group_policy_assignment" "pod_security_baseline" {
│ 
│ creating Policy Assignment ID: (Assignment Name "pod-security-baseline" /
│ Scope
│ "/subscriptions/cb8d2bb0-****-****-****-cde33c0320a4/resourceGroups/afe2e493c-stamp-uksouth-rg"):
│ policy.AssignmentsClient#Create: Failure responding to request:
│ StatusCode=500 -- Original Error: autorest/azure: Service returned an
│ error. Status=500 Code="InternalServerError" Message="Encountered an
│ internal server error. The tracking id is
│ '00000000-0000-0000-0000-000000000000'."
```

### Expected Behaviour

It should (and was till today) successfully create the policy assignment.

### Actual Behaviour

It does not create the policy assignment.

**Comment by heoelri** [comment]
Seems like this was a transient issue which is gone now.

**Comment by wuxu92** [comment]
hi @heoelri  thanks for your feedback, it looks like a service unstable issue, good to see it's ok now. please append this thread if it comes back again in the future, I'll forward it to the service team to look at it.
