### ISSUE TITLE
Log analytics cluster supports minimum 1000 GB Size/day but Azure supports 500 GB minimum

### ISSUE THREAD

**Issue by niks-singh** [hashicorp/terraform-provider-azurerm#17787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2

### AzureRM Provider Version

3.1.15

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_cluster" "example" {
  name                = "example-cluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Errors out by saying 1000 GB is the minimum supported value. Azure API supports 500 GB minimum size_gb value.
```

### Expected Behaviour

- Allow  the minimum SKU GB per day to 500. https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-dedicated-clusters#create-a-dedicated-cluster refer the link 

### Actual Behaviour

Error when passing 500 GB as Size_GB parameter

### References

https://docs.microsoft.com/en-us/azure/azure-monitor/logs/logs-dedicated-clusters#create-a-dedicated-cluster refer the link

**Comment by bubbletroubles** [comment]
I've created PR #17794 to resolve this.

**Comment by mybayern1974** [comment]
@bubbletroubles thank you for opening this issue and further appreciate to submit a PR! Given there is an existing PR #17780 that not only tries to resolve this issue but includes some more info, would you mind subscribing that PR?
