### ISSUE TITLE
azurerm_virtual_machine_extension empty settings causes update in place

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#17788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.15.1

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "virtualmachine_linux" {
  count = local.virtual_machine_linux ? 1 : 0

  name                       = "AzureMonitorLinuxAgent"
  virtual_machine_id         = local.virtual_machine_id
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorLinuxAgent"
  type_handler_version       = "1.9"
  auto_upgrade_minor_version = true
  settings                   = <<SETTINGS
    {
    }
SETTINGS
}
```

### Debug Output/Panic Output

```shell
no-op
name :
"AzureMonitorLinuxAgent"
update
settings :
""
jsonencode({ })
no-op
tags :
{ }
```

### Expected Behaviour

no change should be required

### Actual Behaviour

update in place required

### Steps to Reproduce

terraform apply

**Comment by myc2h6o** [comment]
Hi @mpjtaylor thanks for opening the issue! The reason of the diff is because `settings` is set to a string value "{}". To avoid the diff, you could remove the `settings` from the config since it's an optional field.

**Comment by mpjtaylor** [comment]
ahh documentation says its required, i have removed it :)

Thanks

**Comment by myc2h6o** [comment]
oops, the doc is wrong. @mpjtaylor Thanks for finding it. I've opened #17820 to fix the doc.
