### ISSUE TITLE
azurerm_managed_disk create_option "Upload"

### ISSUE THREAD

**Issue by jmrav** [hashicorp/terraform-provider-azurerm#17792]
Hi all,

I'm facing an issue when I was able to import Azure Managed Disk that was created using "Upload". I'm aware that `create_option = "Upload"` doesn't exist, but the Resource JSON in Azure says the createOption is indeed "Upload" and any other argument forces the disk to be destroyed and recreated.

### Azure Resource JSON snippet
```json
    "properties": {
        "creationData": {
            "createOption": "Upload"
        },
        "diskSizeGB": 100,
        "timeCreated": "2022-07-13T12:55:26.3849858+00:00",
        "provisioningState": "Succeeded",
        "diskState": "Attached"
    }
```

### Terraform State snippet
```
 "resources": [
    {
      "mode": "managed",
      "type": "azurerm_managed_disk",
      "name": "vm01-disk",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "create_option": "Upload",
```

I'd like to know if I'm missing something here? Maybe the `terraform import` shouldn't have been successful?

Thanks,
J.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.2.5

### AzureRM Provider Version

3.15.1

### Affected Resource(s)/Data Source(s)

azurerm_managed_disk

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "vm01-disk" {
  create_option        = "Upload"
  location             = "eastus"
  name                 = "vm01-disk-87044a3a31a847b3a590d56c8046b675"
  resource_group_name  = "vm01-rg"
  storage_account_type = "Premium_LRS"
}
```

### Debug Output/Panic Output

```shell
$ terraform plan
╷
│ Error: expected create_option to be one of [Copy Empty FromImage Import Restore], got Upload
│
│   with azurerm_managed_disk.dev-pr-netbox-vm01-disk,
│   on dev-pr-netbox-vm.tf line 42, in resource "azurerm_managed_disk" "dev-pr-netbox-vm01-disk":
│   42:   create_option        = "Upload"
│
╵
```

### Expected Behaviour

It should continue with plan and in my case it should say, "No changes. Your infrastructure matches the configuration."
Now, I'm aware that `create_option = "Upload"` doesn't exist, but the Resource JSON in Azure says the createOption is indeed "Upload"

```json
    "properties": {
        "creationData": {
            "createOption": "Upload"
        },
        "diskSizeGB": 100,
        "timeCreated": "2022-07-13T12:55:26.3849858+00:00",
        "provisioningState": "Succeeded",
        "diskState": "Attached"
    }
```

### Actual Behaviour

$ terraform plan
╷
│ Error: expected create_option to be one of [Copy Empty FromImage Import Restore], got Upload
│
│   with azurerm_managed_disk.dev-pr-netbox-vm01-disk,
│   on dev-pr-netbox-vm.tf line 42, in resource "azurerm_managed_disk" "dev-pr-netbox-vm01-disk":
│   42:   create_option        = "Upload"
│
╵

### Steps to Reproduce

terraform plan

### References

https://azure.microsoft.com/en-ca/blog/introducing-the-preview-of-direct-upload-to-azure-managed-disks/#:~:text=If%20you%20choose%20to%20use%20Azure%20Compute%20Rest,size%20of%20the%20VHD%20being%20uploaded.%20Rest%20API

**Comment by myc2h6o** [comment]
Hi @jmrav thanks for opening the issue! The `import` succeeds as it doesn't do schema validation. Unfortunately, there is no current plan to support the `Upload` create option, but below is a workaround I could think of:
```hcl
  # Use another create_option
  create_option = "Empty"

  # ignore the change of the create_option
  lifecycle {
    ignore_changes = [
      create_option
    ]
  }
```
