### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert resource query_type parameter via import equals "Number"

### ISSUE THREAD

**Issue by m350** [hashicorp/terraform-provider-azurerm#17806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform version 1.2.6
azurerm provider 3.16.0
terraform state in storage account
Alert rule was created via "2021-08-01-ga" API version 

In one of the Alert Rules after import it to terraform state I see "Number" value in query_type parameter 
But if I try to plan or apply code with "Number" value for query_type parameter 
I will have error message  means that this parameter can have only "ResultCount" value.
<img width="529" alt="image" src="https://user-images.githubusercontent.com/14160267/181732551-7c58af79-26f1-41c2-8e37-80b005f133f0.png">

Also if I put "ResultCount" value, I will have pending changes for query_type parameter
from "Number" to "ResultCount"

### Terraform Version

1.2.6

### AzureRM Provider Version

3.16.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
can't provide
```

### Debug Output/Panic Output

```shell
can't provide
```

**Comment by teowa** [comment]
Hi @m350 This is a service Swagger bug, see https://github.com/Azure/azure-rest-api-specs/issues/20123. Once the Enum values are checked then I am going to fix it.
