### ISSUE TITLE
Creating private service connection for Azure Monitor Private Link Scope (AMPLS)

### ISSUE THREAD

**Issue by konstantin-prituko-rft** [hashicorp/terraform-provider-azurerm#17814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

2.2.3

### AzureRM Provider Version

3.14.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint, private_service_connection

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_private_link_scope" "amplsMain" {
  name                = local.amplsName
  resource_group_name = data.azurerm_resource_group.rg.name
}
resource "azurerm_private_endpoint" "amplsMainPrivateEndpoint" {
  name = "${local.amplsPrivateEndpointName}"
  location = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  subnet_id = data.azurerm_subnet.subnetMain.id
  private_service_connection {
    name = "${local.amplsPrivateServiceConnectionName}"
    private_connection_resource_id = azurerm_monitor_private_link_scope.amplsMain.id
    is_manual_connection = false
    subresource_names = ["azuremonitor"]
  }
  private_dns_zone_group {
    name = "common"
    private_dns_zone_ids = [
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.monitor.azure.com",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.oms.opinsights.azure.com",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.ods.opinsights.azure.com",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.agentsvc.azure-automation.net"
    ]
  }
  tags = local.commonTags
}
```

### Debug Output/Panic Output

```shell
Error: waiting for creation of Private Endpoint "PE_NAME" (Resource Group "RG_NAME"): Code="BadRequest" Message="Call to Microsoft.Insights/privateLinkScopes failed. Error message: Mismatching RequiredMembers in Request" Details=[]
```

### Expected Behaviour

Private Endpoint for AMPLS has been deployed. No errors appeared.

### Actual Behaviour

When "subresource_names = ["azuremonitor"]":
Actually Private Endpoint appears in Azure, but Terraform drop an error :
"Error: waiting for creation of Private Endpoint "PE_NAME" (Resource Group "RG_NAME"): Code="BadRequest" Message="Call to Microsoft.Insights/privateLinkScopes failed. Error message: Mismatching RequiredMembers in Request" Details=[]"
So, the build with Terraform not completed successfully.

When there is not "subresource_names" section:
Terraform error:
Error: creating Private Endpoint "PE_NAME" (Resource Group "RG_NAME"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingParameterOnPrivateLinkServiceConnection" Message="Private link service connection /subscriptions/((redacted))/resourceGroups/RG_NAME/providers/Microsoft.Network/privateEndpoints/PE_NAME/privateLinkServiceConnections/AMPLS_NAME is missing required parameter 'group Id'." Details=[]

### Steps to Reproduce

1. terraform apply

### References

https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-configure

**Comment by t3mi** [comment]
@konstantin-prituko-rft provided configuration for private endpoint is incomplete - that's why Azure API throws such error. Private endpoint for AMPLS requires [5 private DNS zones](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-configure#reviewing-your-endpoints-dns-settings).

```hcl
provider "azurerm" {
  features {}
}

locals {
  private_dns_zones_names = toset([
    "privatelink.agentsvc.azure-automation.net",
    "privatelink.blob.core.windows.net",
    "privatelink.monitor.azure.com",
    "privatelink.ods.opinsights.azure.com",
    "privatelink.oms.opinsights.azure.com",
  ])
}

resource "random_pet" "example" {
}

resource "azurerm_resource_group" "example" {
  name     = format("%s-rg", random_pet.example.id)
  location = "East US 2"
}

resource "azurerm_virtual_network" "example" {
  name                = format("%s-vnet", random_pet.example.id)
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "example" {
  name                 = format("%s-subnet", random_pet.example.id)
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.0.0/24"]
}

resource "azurerm_private_dns_zone" "example" {
  for_each = local.private_dns_zones_names

  name                = each.value
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_monitor_private_link_scope" "example" {
  name                = format("%s-ampls", random_pet.example.id)
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_private_endpoint" "this" {
  name                = format("%s-pe", random_pet.example.id)
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  subnet_id           = azurerm_subnet.example.id

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [for _, v in azurerm_private_dns_zone.example : v.id]
  }

  private_service_connection {
    name                           = format("%s-psc", random_pet.example.id)
    is_manual_connection           = false
    private_connection_resource_id = azurerm_monitor_private_link_scope.example.id
    subresource_names              = ["azuremonitor"]
  }
}

```

**Comment by ms-zhenhua** [comment]
Hi @konstantin-prituko-rft, I tried to repro the issue with your provided configuration, but it does not happen. I attached my fully runnable configuration below. Could you kindly also help provide a fully runnable configuration (you can hide the sensitive info) which you produced such issue with? Then we can do more investigation on it.
[main.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/9248335/main.zip)

**Comment by konstantin-prituko-rft** [comment]
> @konstantin-prituko-rft provided configuration for private endpoint is incomplete - that's why Azure API throws such error. Private endpoint for AMPLS requires [5 private DNS zones](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-configure#reviewing-your-endpoints-dns-settings).
> 
> ```terraform
> provider "azurerm" {
>   features {}
> }
> 
> locals {
>   private_dns_zones_names = toset([
>     "privatelink.agentsvc.azure-automation.net",
>     "privatelink.blob.core.windows.net",
>     "privatelink.monitor.azure.com",
>     "privatelink.ods.opinsights.azure.com",
>     "privatelink.oms.opinsights.azure.com",
>   ])
> }
> 
> resource "random_pet" "example" {
> }
> 
> resource "azurerm_resource_group" "example" {
>   name     = format("%s-rg", random_pet.example.id)
>   location = "East US 2"
> }
> 
> resource "azurerm_virtual_network" "example" {
>   name                = format("%s-vnet", random_pet.example.id)
>   location            = azurerm_resource_group.example.location
>   resource_group_name = azurerm_resource_group.example.name
>   address_space       = ["10.0.0.0/16"]
> }
> 
> resource "azurerm_subnet" "example" {
>   name                 = format("%s-subnet", random_pet.example.id)
>   resource_group_name  = azurerm_resource_group.example.name
>   virtual_network_name = azurerm_virtual_network.example.name
>   address_prefixes     = ["10.0.0.0/24"]
> }
> 
> resource "azurerm_private_dns_zone" "example" {
>   for_each = local.private_dns_zones_names
> 
>   name                = each.value
>   resource_group_name = azurerm_resource_group.example.name
> }
> 
> resource "azurerm_monitor_private_link_scope" "example" {
>   name                = format("%s-ampls", random_pet.example.id)
>   resource_group_name = azurerm_resource_group.example.name
> }
> 
> resource "azurerm_private_endpoint" "this" {
>   name                = format("%s-pe", random_pet.example.id)
>   location            = azurerm_resource_group.example.location
>   resource_group_name = azurerm_resource_group.example.name
>   subnet_id           = azurerm_subnet.example.id
> 
>   private_dns_zone_group {
>     name                 = "default"
>     private_dns_zone_ids = [for _, v in azurerm_private_dns_zone.example : v.id]
>   }
> 
>   private_service_connection {
>     name                           = format("%s-psc", random_pet.example.id)
>     is_manual_connection           = false
>     private_connection_resource_id = azurerm_monitor_private_link_scope.example.id
>     subresource_names              = ["azuremonitor"]
>   }
> }
> ```

Thank you!
Adding privatelink-blob-core-windows-net DNS zone solved this problem. Now Private Connection for AMPLS deployed normally without any errors.
And this is really interesting that here - https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-configure - I need only 4 DNS zones, but here - https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-configure#reviewing-your-endpoints-dns-settings - 5 zones.

**Comment by konstantin-prituko-rft** [comment]
> Hi @konstantin-prituko-rft, I tried to repro the issue with your provided configuration, but it does not happen. I attached my fully runnable configuration below. Could you kindly also help provide a fully runnable configuration (you can hide the sensitive info) which you produced such issue with? Then we can do more investigation on it. [main.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/9248335/main.zip)

You can see my comment above - this issue has been solved by adding one more DNS zone. 
I will add comment about this on Microsoft documentation.

**Comment by konstantin-prituko-rft** [comment]
Private endpoint for AMPLS requires [5 private DNS zones](https://docs.microsoft.com/en-us/azure/azure-monitor/logs/private-link-configure#reviewing-your-endpoints-dns-settings).

  private_dns_zone_group {
    name = "NAME"
    private_dns_zone_ids = [
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.monitor.azure.com",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.oms.opinsights.azure.com",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.ods.opinsights.azure.com",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.agentsvc.azure-automation.net",
      "${var.privateLinkDNSZoneResourceGroupId}/providers/Microsoft.Network/privateDnsZones/privatelink.blob.core.windows.net"
    ]
  }
