### ISSUE TITLE
Support for Server 2022 AKS NodePool SKU

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#17811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ability to select VM SKU for Preview Windows Server 2022 (sku name is "Windows2022")

### New or Affected Resource(s)/Data Source(s)

kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "windows" {
  name                  = "win1"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  vm_size               = var.agents_size
  node_count            = 1
  os_type               = "Windows"
  vnet_subnet_id        = var.subnet_id
  os_sku                = "Windows2022"
}
```

### References

https://docs.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli#register-the-akswindows2022preview-preview-feature

Done in the CLI by doing:

`az aks nodepool add \
    --resource-group myResourceGroup \
    --cluster-name myAKSCluster \
    --os-type Windows \
    --os-sku Windows2022 \ 
    --name npwin \
    --node-count 1`

**Comment by PatrickSpies** [comment]
Any updates on this? WS2022 for AKS is now GA, see https://github.com/Azure/AKS/issues/2115#issuecomment-1251872216

**Comment by matthiasritter** [comment]
we are also interessed in this. Is there any update?

**Comment by CJJ69** [comment]
Can we add more enums for "os_sku" i.e. Windows2022
and include it in the validation for "os_sku"

**Comment by CJJ69** [comment]
https://learn.microsoft.com/en-us/azure/aks/learn/quick-windows-container-deploy-cli#add-a-windows-server-2022-node-pool


# add a Windows node pool
az aks nodepool add `
    --resource-group $groupName `
    --cluster-name $clusterName `
    **--os-type Windows `
    --os-sku Windows2022 `**
    --name $nodePoolName `
...

**Comment by CJJ69** [comment]
Windows Server 2022 host support in AKS

https://azure.microsoft.com/en-us/updates/public-preview-windows-server-2022-host-support-in-aks/

**Comment by djsly** [comment]
anyone tried ? is there a Major blocker missing or it's just that no one tried to open the missing PR ? I'm asking before I start opening the PR (sounds like this is a simple addition of a new valid SKU to the Verification list)

**Comment by djsly** [comment]
blocked by the lack of proper containerservice SDK, it needs to be added to the go-azure-sdk first since the latest releases are in special branch/tag 

https://github.com/hashicorp/go-azure-sdk/issues/157
