### ISSUE TITLE
Terraform apply should not be failing when terraform is updating keyvault with soft delete enabled

### ISSUE THREAD

**Issue by bamb00** [hashicorp/terraform-provider-azurerm#17815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

0.14.0

### AzureRM Provider Version

0.14.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
Terraform apply should ignore kv with soft-delete enabled and not failed when the keyvault is getting update.
```

### Debug Output/Panic Output

```shell
Error: Error updating Key Vault "xxxxxxxxxx" (Resource Group "xxxxxxxx-xxxx-xxxxxx-xxxxxx-xx"): once Purge Protection has been Enabled it's not possible to disable it
```

### Expected Behaviour

Should skip the kv and not failed the run.

### Actual Behaviour

The terraform apply failed with detecting the kv is soft-delete/purge-protection is enabled.  The kv is not being purge but it is attempting to update the kv

### Steps to Reproduce

1. kv soft-delete/purge-protection is enabled
2. terraform apply updating the kv

**Comment by magodo** [comment]
@bamb00 Would you please provide a minimal TF config to describe the steps for reproducing the error?

From the description above, it seems in your update on the key vault, you are trying to change the `purge_protection_enabled` from `true` to `false` (note that its default value is `false`). As is mentioned in this [issue](https://github.com/Azure/azure-rest-api-specs/issues/8075), the `purge_protection_enabled` can't be revert from `true` to `false` in Azure. This is why the provider errored with above message.

**Comment by bamb00** [comment]
Thanks @magodo.  I made the change and the TF is running without the errors.  I've assume TF will ignore the purge_protection_enabled but had to override the setting.

Thanks for the help!
