### ISSUE TITLE
Azure Monitor agent (NOT OMSExtension) for Linux terraform

### ISSUE THREAD

**Issue by g-spencer** [hashicorp/terraform-provider-azurerm#17828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RedHat 9 and Ubuntu 22.04 LTS both report compatibility with the newer Microsoft Monitoring Agent, however I have searched (and have been searching for a couple of months) for the terraform code to deploy, but without luck.

MSREF: https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview?tabs=PowerShellWindows

The OMS Extension is being phased out and is not compatible (currently?) with the latest Linux releases, but I can't find any references wrt Terraform and the newer Microsoft Monitoring Agent for Linux?

### New or Affected Resource(s)/Data Source(s)

azurerm_XXXXX

### Potential Terraform Configuration

```hcl
https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-overview?tabs=PowerShellWindows - Azure Monitor agent overview

https://docs.microsoft.com/en-us/azure/azure-monitor/agents/agents-overview#linux - Overview of Azure Monitor agents
```

**Comment by teowa** [comment]
Hi @g-spencer , thanks for taking the time to open this issue. Maybe the Azure Monitor Agent extension can be provisioned using [`azurerm_virtual_machine_extension`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension) , below is a example config, and the `type_handler_version` can be found in this [doc](https://docs.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=ARMAgentCLI%2CPowerShellLinux%2CPowerShellWindowsArc%2CCLILinux%2CCLIWindowsArc#virtual-machine-extension-details) or with Azure CLI command `az vm extension image list --location eastus --output table | grep MonitorLinux` .

Hope this may help. And welcome to reply here if you have further issues.

<details>

<summary>TF config</summary>

```
provider "azurerm" {
}

resource "azurerm_resource_group" "example" {
  name     = "test-rg-vm-monitor"
  location = "east US"
}

resource "azurerm_virtual_network" "example" {
  name                = "test-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "test-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "test-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = "test-example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_B1ls"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  admin_password = "test-Password"

  disable_password_authentication = false
  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }
  lifecycle {
    ignore_changes = [tags]
  }
}

resource "azurerm_virtual_machine_extension" "example" {
  name                       = "AzureMonitorLinuxAgent"
  virtual_machine_id         = azurerm_linux_virtual_machine.example.id
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorLinuxAgent"
  type_handler_version       = "1.21"
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true
  tags = {
    environment = "Test"
  }
}

```
</details>

**Comment by tombuildsstuff** [comment]
Closing this out as above 👍
