### ISSUE TITLE
Authenticating a app running terraform via Managed Identities 

### ISSUE THREAD

**Issue by paparuco** [hashicorp/terraform-provider-azurerm#17829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.8.0

### Affected Resource(s)/Data Source(s)

azurerm_user_assigned_identity

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.2.4" 
  backend ""{}
 }
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.8.0"
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/2fb56fc4-f0d6-41ce-bfbf-4b61e39f03e8/providers?api-version=2016-02-01: StatusCode=404 -- Original Error: adal: Refresh request failed. Status Code = '404'. Response body: clientID in request: 8970##### REDACTED #####83e1, getting assigned identities for pod atlantis/atlantis-0 in CREATED state failed after 16 attempts, retry duration [5]s, error: <nil>. Check MIC pod logs for identity assignment errors
│  Endpoint http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&client_id=897000d1-c2bc-4e51-83ae-e652ea3283e1&resource=https%3A%2F%2Fmanagement.azure.com
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 27, in provider "azurerm":
│   27: provider "azurerm" {
│
```

### Expected Behaviour

Hello! 
At the moment I'm trying to create a pipeline with Atlantis (deployed on AKS). In order for Atlantis to run terraform it needs to authenticate to Azure. While Service Principal isn't the use case for us, we went for authenticating via Managed Identity.
We've created a user managed identity with the required permissions to do operations.
We configured the environment variables indicated in the documentation:
* `ARM_USE_MSI`
* `ARM_SUBSCRIPTION_ID`
* `ARM_TENANT_ID`
* `ARM_CLIENT_ID` 

Atlantis should authenticate to Azure and terraform should be able to do `plan/apply` commands

### Actual Behaviour

But when we try to run `terraform plan` inside the machine it gets stuck retrying to get the 

It's set as in the provider documentation, but not working can you provide any information on it? 
Thanks in advance and sorry for any inconvenience

**Comment by tombuildsstuff** [comment]
hey @paparuco 

Last I checked, AKS didn't provide (direct) access to the Instance MetaData Service from Pods, which is what this provider uses to authenticate using a Managed Identity - I believe there's some add-ons available within AKS to assign identities to Pods, but since this is a question related to the configuration of AKS rather than something specific to the Provider, you'd be best asking this on [the AKS repository](https://github.com/Azure/AKS/issues) instead where someone from that team should be able to assist further.

Thanks!
