### ISSUE TITLE
Support for data collection rule association

### ISSUE THREAD

**Issue by StephenCleary** [hashicorp/terraform-provider-azurerm#17831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_monitor_data_collection_rule` was added in 3.15 (I think), but the DCRs are not really useful without associating them with a resource/scope. I'd like to see support for `Microsoft.Insights/dataCollectionRuleAssociations@2021-04-01`.

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule_association

### Potential Terraform Configuration

```hcl
# (I think?)

resource "azurerm_monitor_data_collection_rule_association" "example" {
  name = ""
  description = ""
  scope = ""
  data_collection_rule_id = ""
}
```

**Comment by teowa** [comment]
Hi @StephenCleary , after this `azurerm_monitor_data_collection_endpoint` PR https://github.com/hashicorp/terraform-provider-azurerm/pull/17684 is merged, I am going to submit PR for `azurerm_monitor_data_collection_association`.

**Comment by teowa** [comment]
Hi @StephenCleary , the `azurerm_monitor_data_collection_association` PR has been submitted.
