### ISSUE TITLE
Lifecycle configuration ignored for aks k8s version

### ISSUE THREAD

**Issue by ThomasPelletier** [hashicorp/terraform-provider-azurerm#17847]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.5

### AzureRM Provider Version

2.45.1

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = local.stack_name
  location            = var.location
  resource_group_name = azurerm_resource_group.spoke.name
  dns_prefix          = local.stack_name
  kubernetes_version  = local.env_aks_version

  # identity {
  #   type = "SystemAssigned"
  # }

  linux_profile {
    admin_username = var.node_admin_username

    ssh_key {
      key_data = data.azurerm_key_vault_secret.pub.value
    }
  }

  default_node_pool {
    name                 = format("aks${local.environment}pool")
    node_count           = local.env_node_count
    max_count            = local.env_max_node_count
    min_count            = local.env_min_node_count
    max_pods             = "250"
    type                 = "VirtualMachineScaleSets"
    vm_size              = local.env_node_size
    os_disk_type         = "Ephemeral"
    vnet_subnet_id       = azurerm_subnet.aks.id
    orchestrator_version = local.env_aks_version
    availability_zones   = ["1", "2", "3"]
    tags                 = local.env_tags
    enable_auto_scaling  = true

  }

  service_principal {
    client_id     = azuread_service_principal.aks.application_id
    client_secret = azuread_service_principal_password.aks.value
  }

  lifecycle {
    ignore_changes = [
      default_node_pool[0].node_count,
      default_node_pool[0].orchestrator_version,
      kubernetes_version
    ]
  }

  # addon_profile {
  #     oms_agent {
  #     enabled                    = true
  #     log_analytics_workspace_id = azurerm_log_analytics_workspace.aks.id
  #     }
  # }

  network_profile {
    load_balancer_sku = "Standard"
    network_plugin    = "azure"
  }

  tags = local.env_tags
}
```

### Debug Output/Panic Output

```shell
Error: 
The Kubernetes/Orchestrator Version "1.21.1" is not available for Node Pool "akstestpool".

Please confirm that this version is supported by the Kubernetes Cluster spoke-aks-test"
(Resource Group "spoke-aks-test") - which may need to be upgraded first.

The Kubernetes Cluster is running version "1.21.1".

The supported Orchestrator Versions for this Node Pool/supported by this Kubernetes Cluster are:


Node Pools cannot use a version of Kubernetes that is not supported on the Control Plane. More
details can be found at https://aka.ms/version-skew-policy.


  on aks.tf line 45, in resource "azurerm_kubernetes_cluster" "aks":
  45: resource "azurerm_kubernetes_cluster" "aks" {
```

### Expected Behaviour

Update the configuration without checking for the k8s version or the orchestration version of the node pool.

### Actual Behaviour

Terraform doesn't apply the configuration since the k8s isn't supported anymore. I will update the k8s version of the cluster in the next few weeks but at the moment I can't.

### Steps to Reproduce

You need to have a cluster already up and running with a k8s version that is not supported by Azure anymore. Then just try a terraform apply

**Comment by stephybun** [comment]
Thanks for raising this issue @ThomasPelletier. 

Looks like #16551 should have resolved this, please let us know if that is not the case.
