### ISSUE TITLE
azurerum_windows_web_app data encoding "virtual_network_subnet_id"

### ISSUE THREAD

**Issue by jperry-smsc** [hashicorp/terraform-provider-azurerm#17850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.16.0

### Affected Resource(s)/Data Source(s)

azurerum_windows_web_app

### Terraform Configuration Files

```hcl
data "azurerm_windows_web_app" "app" {
  provider            = azurerm.apps
  name                = "app-use2-dev"
  resource_group_name = data.azurerm_resource_group.app_resource_group.name
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: encoding: setting "virtual_network_subnet_id": Invalid address to set: []string{"virtual_network_subnet_id"}
│
│   with data.azurerm_windows_web_app.app,
│   on main.tf line ###, in data "azurerm_windows_web_app" "app":
│  ###: data "azurerm_windows_web_app" "app" {
│
│ encoding: setting "virtual_network_subnet_id": Invalid address to set:
│ []string{"virtual_network_subnet_id"}
╵
```

### Expected Behaviour

Expected behavior is to return azurerm_windows_web_app information to data block for usage later on in main.tf

### Actual Behaviour

Error encoding virtual network subnet id value.  Values for linux apps working properly.  Only windows app failing.

**Comment by woowil** [comment]
I am getting the same error and adding `virtual_network_subnet_id = null` didn't help. Could it be that `virtual_network_subnet_id` is not configured to be optional?


```
resource "azurerm_windows_web_app" "wfa" {
   virtual_network_subnet_id   = null
}
resource "azurerm_windows_function_app" "wfa" {
   virtual_network_subnet_id   = null
}
```

│ Error: encoding: setting "virtual_network_subnet_id": Invalid address to set: []string{"virtual_network_subnet_id"}
│
│   with module.network_connection[0].data.azurerm_windows_web_app.win_wa[0],
│   on C:\azurerm_app_service_virtual_network_swift_connection\data.tf line 6, in data "azurerm_windows_web_app" "win_wa":  
│    6: data "azurerm_windows_web_app" "win_wa" {
│
│ encoding: setting "virtual_network_subnet_id": Invalid address to set: []string{"virtual_network_subnet_id"}

**Comment by BrianRichardson** [comment]
This issue is causing me some problems too.
azurerm version 3.16.0
terraform version 1.2.6.

**Comment by dannmichelson** [comment]
Same issue - this started using the same terraform code after going from azurerm 3.15.0 -> 3.16.0, so it seems like a breaking change was accidentally introduced?

Mine was specifically breaking when we tried to terraform plan on an azurerm_windows_web_app_slot

azurerm 3.16.0
terraform 1.1.8

**Comment by dtulltgna** [comment]
This is still an issue 5 days later.  I rolled back to AzureRM 3.15.1 and cleared the error.  Has anyone brought this up with Hashicorp or Microsoft?  Seems like it should be an easy fix.

azurerm 3.16.0
terraform 1.2.6

**Comment by dtulltgna** [comment]
Still seems to be an issue 5 days later.  Anyone brought this up with Hashicorp or Microsoft.  Seems like it ought to be an easy fix.
azurerm 3.16.0
terraform 1.2.6

**Comment by sahitya12** [comment]
i am also facing issue while deploying slot

**Comment by AurimasNav** [comment]
Trying to replace deprecated data source `azurerm_app_service` with `azurerm_windows_web_app` and facing same issue.
> Terraform v1.2.6
> on windows_amd64
> + provider registry.terraform.io/hashicorp/azurerm v3.18.0
