### ISSUE TITLE
Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

### ISSUE THREAD

**Issue by ChrisTav424** [hashicorp/terraform-provider-azurerm#17863]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.16.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_key_vault" "main" {
  name                        = var.kv_name
  location                    = azurerm_resource_group.main.location
  resource_group_name         = azurerm_resource_group.main.name
  enabled_for_disk_encryption = false
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = true #Cannot be disabled once enabled

  sku_name = "premium"

  #As this is only used for the encryption keys on these VMs, we are only allowing access from the v-subnet
  network_acls {
    bypass                     = "AzureServices"
    default_action             = "Deny"
    virtual_network_subnet_ids = [data.azurerm_subnet.v-subnet.id]
  }
}

# Uses the principal ID (system assigned identity) from these servers to add an access policy to create, wrap and unwrap keys

resource "azurerm_key_vault_access_policy" "server-1" {
  key_vault_id = azurerm_key_vault.main.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = module.windows-servers-image["Server-1"].principal_id

  key_permissions = [
    "Create", "WrapKey", "UnwrapKey"
  ]
  depends_on = [
    module.windows-servers-image
  ]
}

# Uses the principal ID (system assigned identity) from these servers to add an access policy to creat, wrap and unwrap keys

resource "azurerm_key_vault_access_policy" "server-2" {
  key_vault_id = azurerm_key_vault.main.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = module.windows-servers-image["Server-2"].principal_id

  key_permissions = [
    "Create", "WrapKey", "UnwrapKey"
  ]
  depends_on = [
    module.windows-servers-image
  ]
}

#Creates private endpoint for the keyvault
resource "azurerm_private_endpoint" "main" {
  name                = format("pep-%s", var.kv_name)
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  subnet_id           = data.azurerm_subnet.v-subnet.id

  private_service_connection {
    name                           = format("pep-connection-%s", var.kv_name)
    is_manual_connection           = false
    private_connection_resource_id = azurerm_key_vault.main.id
    # sub resource of 'file'
    subresource_names = ["vault"]
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_key_vault.main: Refreshing state... [id=/subscriptions/<_subscription_>/resourceGroups/rg-prod/providers/Microsoft.KeyVault/vaults/kv-prod]

╷
│ Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with azurerm_key_vault.main,
│   on kv.tf line 5, in resource "azurerm_key_vault" "main":
```

### Expected Behaviour

The keyvault can be successfully refreshed and the plan succeeds

### Actual Behaviour

Terraform fails with 'Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded'

### Steps to Reproduce

terraform plan

### Important Factoids

It runs fine on a Microsoft hosted agent but fails when running on a Self Hosted Agent

### References

I have found another report of this error but it doesn't look to be the same. This works successfully on an Azure hosted agent, only fails on a self hosted agent. 

To troubleshoot I have also allowed public network and also the access policy through the portal but this make no difference.

**Comment by magodo** [comment]
@ChrisTav424 This is due to you have specified the following in the key vault:

```
  #As this is only used for the encryption keys on these VMs, we are only allowing access from the v-subnet
  network_acls {
    bypass                     = "AzureServices"
    default_action             = "Deny"
    virtual_network_subnet_ids = [data.azurerm_subnet.v-subnet.id]
  }
```

This indicates that the access to the key vault is only allowed from within the subnet.

**Comment by AndreasMWalter** [comment]
Having the same issue in conjunction with Private Endpoint based deployments. 
We have a staged landing zone deployment, where the landing zone is deployed with a keyvault and then peerings are done.
The keyvault can be succesfully deployed, since it is just an resource managed api operation. However the contact is something on the dataplane. So if anything goes wrong with the peering deployment for some reason or another we always will have to cleanup the vault via portal/cli.
Although this is of course related to our special use case, I would recommend not having any data plane operations within the key vault resource. This may cause exactly these kinds of issues when something in the deployment fails, network isn't ready or IP rules mismatch.

**Comment by ChrisTav424** [comment]
Thanks for the replies @AndreasMWalter and @magodo, it was actually a restrictive NSG that was blocking access to the private endpoint of the keyvault. 

Even though Connection Troubleshooter showed it was successful from the Self-Hosted agent VM, it actually wasn't and adding an allow rule from our Self-Hosted agents to the private endpoint on port 443 was all it needed :)
