### ISSUE TITLE
Password argument for azurerm_storage_blob module

### ISSUE THREAD

**Issue by raptor-22** [hashicorp/terraform-provider-azurerm#17884]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are using terraform with a custom module "custom-acme-registration-route53" to handle requesting SSL certificates from Let's Encrypt using DNS Zones stored in AWS Route53. After getting the certificate the goal is adding it to an Azure Key Vault to be consumed by application gateway and be rotated automatically upon certificate renewal. Unfortunately, terraform can't create new versions of certificates in Azure key vaults and the vault in question has soft delete and purge protection enabled so Terraform fails trying to delete and purge the certificate entry to recreate it afterwards. In order to achieve the aim we plan to grab output of the custom module that contains the certificate contents in p12 format and store it in Azure blob storage using the "azurerm_storage_blob" terraform module. Currently this module does not have a password argument and without the password the certificate can't be imported to Key Vault as azure gives the following error message:     
```
    + CategoryInfo          : CloseError: (:) [Import-AzKeyVaultCertificate], CryptographicException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.ImportAzureKeyVaultCertificate
```
Please see details here: https://stackoverflow.com/questions/56028786/import-azkeyvaultcertificate-cmdlet-results-in-key-not-valid-for-user-in-specif

Please look into adding password argument to the contents of the blob being saved so that the resulting certificate file could be used for key vault import.

**In the meantime, is there a way I could work around the issue? I've tried adding the password as blob metadata but that had no impact on the import process.**

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Potential Terraform Configuration

```hcl
{
      "module_XXX_azurerm_storage_blob": {
        "name": "!environment!-YYY-certp12.pfx",
        "type": "Block",
        "resource_group_name": "my_certificate_store_rg",
        "storage_account_name": "certificatesp12",
        "storage_container_name": "application_name",
        "source_content": "${module.module_ZZZ_custom_acme_registration_route53.certificate_p12}",
        "content_type": "application/x-pkcs12",
        "password": "${module.module_ZZZ_custom_acme_registration_route53.password}",
        "source": "git::https://myorg.visualstudio.com/myproject/_git/azurerm-storage-blob"
      }
    },
```

**Comment by tombuildsstuff** [comment]
This is possible using [the `password` argument when importing a `azurerm_key_vault_certificate`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_certificate) - as such I'm going to close this issue for the moment, but should that not work for you using the latest version of the AzureRM Provider then please let us know and we'll take another look.

Thanks!
