### ISSUE TITLE
Support for tag on azurerm_monitor_scheduled_query_rules_alert

### ISSUE THREAD

**Issue by henryxuteck** [hashicorp/terraform-provider-azurerm#17891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_monitor_scheduled_query_rules_alert` can be tagged by policy and via portal.

 Since azurerm provider doesn't support tags for `azurerm_monitor_scheduled_query_rules_alert`, tags will be removed during the apply.

![image](https://user-images.githubusercontent.com/79539850/182958618-e2a4f22f-4c2b-4a9e-bbc2-d7b9f82878c3.png)

```
  ~ resource "azurerm_monitor_scheduled_query_rules_alert" "default" {
        id                          = "xxx"
        name                    = "xxx"
      ~ tags                     = {
          - "tag1" = "xxxx" -> null
        }

    }

```

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert" "default" {
        id                        = "xxx"
        name                  = "xxx"
       tags                     = {
          "tag1" = "xxxx"
        }

    }
```
```


### References

_No response_

**Comment by teowa** [comment]
@henryxuteck I have checked that the `azurerm_monitor_scheduled_query_rules_alert` has supported `tags` block, but it is omit in the doc, you can try:
```
tags = {
  foo = bar
}
```

**Comment by henryxuteck** [comment]
> @henryxuteck I have checked that the `azurerm_monitor_scheduled_query_rules_alert` has supported `tags` block, but it is omit in the doc, you can try this directly :)
> 
> ```
> tags = {
>   foo = bar
> }
> ```

aha, thanks :)
