### ISSUE TITLE
some windows_function_app app_settings are not written to tfstate

### ISSUE THREAD

**Issue by jb68** [hashicorp/terraform-provider-azurerm#17892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.14

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
When run terraform plan it shows:

# azurerm_windows_function_app.function_app[2] will be updated in-place
  ~ resource "azurerm_windows_function_app" "function_app" {
      ~ app_settings                      = {
          + "APPINSIGHTS_INSTRUMENTATIONKEY"                  = (sensitive)
          + "AzureWebJobsDashboard"                           = (sensitive)
          + "AzureWebJobsStorage"                             = (sensitive)
          + "FUNCTIONS_EXTENSION_VERSION"                     = "~4"
            # (26 unchanged elements hidden)
        }
```
After terraform apply which is a success FUNCTIONS_EXTENSION_VERSION appear on Azure GUI but is not present into tfstate so any new terraform plan will show the same thing. Same as with the other settings
If I do `tf state show azurerm_windows_function_app.function_app[0]` I can see about 26 settings but not this ones.
```


### Debug Output/Panic Output

```shell
No output
```

### Expected Behaviour

To see all settings in tfstate
To not show the same thing on evert tfplan

### Steps to Reproduce

terraform apply
terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/4321

**Comment by mikemadeja** [comment]
From the doc, you shouldn't handle this setting via app_settings. You should use version argument. 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app

**The values for AzureWebJobsStorage and FUNCTIONS_EXTENSION_VERSION will be filled by other input arguments and shouldn't be configured separately**. AzureWebJobsStorage is filled based on storage_account_name and storage_account_access_key. **FUNCTIONS_EXTENSION_VERSION is filled based on version**.

**Comment by jb68** [comment]
After more reading tests, I figure out that 
`"APPINSIGHTS_INSTRUMENTATIONKEY"` all big caps entry will be created by a magic wand when you set site_config block
```
   site_config {
    always_on = true
    http2_enabled = true
    ftps_state = "AllAllowed"
    application_insights_key = azurerm_application_insights.appinsights.instrumentation_key
 ```
 same with "FUNCTIONS_EXTENSION_VERSION" all caps 
 ```
 resource "azurerm_windows_function_app" "function_app" {
  name                       = "fappname"
  resource_group_name        = data.azurerm_resource_group.backend.name
  location                   = data.azurerm_resource_group.backend.location
  service_plan_id            = azurerm_service_plan.asplan.id
  storage_account_name       = "storageName"
  storage_account_access_key = azurerm_storage_account.fapp_storage_account.primary_access_key
  https_only                 = true
  client_certificate_mode    = "Required"
  functions_extension_version= "~4" # will create a similar FUNCTIONS_EXTENSION_VERSION entry on app_settings
```
`"AzureWebJobsDashboard"` and `"AzureWebJobsStorage"` are set by the storage. 


There is some info on the docs about `AzureWebJobsStorage` and `FUNCTIONS_EXTENSION_VERSION`  for the deprecated  "azurerm_function_app but they are also missing `APPINSIGHTS_INSTRUMENTATIONKEY` and `AzureWebJobsDashboard`
There is nothing on docs about this behavior on azurerm_windows_function_app

**Comment by jb68** [comment]
Hi Michael,
Thanks for reply, I was talking about windows_function_app and not about function_app. There is nothing on windows_function_app docs about this. Also the function_app docs are missing application_insights_key and dashboard. Please update the documentation to reflect behaviour.

Regards,
JB




________________________________

**Comment by xiaxyi** [comment]
Hi @jb68 , thanks for raising this issue, we added the usage tips in document [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app#app_settings). Let me know if you have any other questions that I can help to address or kindly consider closing this issue. :)

**Comment by xiaxyi** [comment]
Hey @jb68 , good day. May I know if you find the suggested usage and how does it go?

**Comment by jb68** [comment]
Hi @xiaxyi , 
Good job., sorry for delay, 
Thanks
