### ISSUE TITLE
State error while creating azurerm_eventhub_authorization_rule

### ISSUE THREAD

**Issue by bvenkatbm** [hashicorp/terraform-provider-azurerm#17899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.25

### AzureRM Provider Version

2.15.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_authorization_rule

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  version = "~> 2.15.0"
}

resource "azurerm_resource_group" "rg" {
  name     = "eventhub-${var.env}"
  location = "${var.location}"
}

resource "azurerm_eventhub_namespace" "hub" {
  name                = "device-metadata-${var.env}"
  location            = "${azurerm_resource_group.rg.location}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  sku                 = "Standard"
  capacity            = 1
  //kafka_enabled       = false

  tags = {
    environment = "${var.env}"
  }

}

resource "azurerm_eventhub" "entity" {
  name                = "device-meta-data"
  namespace_name      = "${azurerm_eventhub_namespace.hub.name}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  partition_count     = 32
  message_retention   = 1
}

resource "azurerm_eventhub_consumer_group" "group1" {
  name                = "dev"
  namespace_name      = "${azurerm_eventhub_namespace.hub.name}"
  eventhub_name       = "${azurerm_eventhub.entity.name}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
}

resource "azurerm_storage_account" "storage" {
  name                     = "${var.eventhubstoragename}${var.env}"
  resource_group_name      = "${azurerm_resource_group.rg.name}"
  location                 = "${azurerm_resource_group.rg.location}"
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
  account_kind             = "StorageV2"
}

resource "azurerm_storage_container" "container1" {
  name                  = "devicedata"
  storage_account_name  = "${azurerm_storage_account.storage.name}"
  container_access_type = "private"
}

resource "azurerm_eventhub_authorization_rule" "rule1" {
  name                = "iothubroutes_iothublucid-${var.env}"
  namespace_name      = "${azurerm_eventhub_namespace.hub.name}"
  eventhub_name       = "${azurerm_eventhub.entity.name}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  listen              = true
  send                = true
  manage              = true
}
```

### Debug Output/Panic Output

```shell
Error: Error making Read request on Azure EventHub Authorization Rule : eventhub.EventHubsClient#GetAuthorizationRule: Invalid input: autorest/validation: validation failed: parameter=authorizationRuleName constraint=MinLength value="" details: value length must be greater than or equal to 1

  on .terraform/modules/eventhub/main.tf line 50, in resource "azurerm_eventhub_authorization_rule" "rule1":

  50: resource "azurerm_eventhub_authorization_rule" "rule1" {
```

### Expected Behaviour

`terraform apply` should create RG, EventHub Namespace, EventHubs, CGs, Storage account and containers and set authorization rule in respective event hubs.

### Actual Behaviour

`terraform apply` is creating RG, EventHub Namespace, EventHubs, CGs, Storage account and containers and setting authorization rule in respective event hubs. But the apply is failing with a read error.

**Comment by tombuildsstuff** [comment]
hi @bvenkatbm 

Both the AzureRM Provider version and Terraform Core version being used here are very old and behave differently to newer versions of the Provider - as such we'd recommend upgrading to the latest versions since we believe this has been fixed in newer versions of the Provider.

If you're still encountering this issue on the latest version of the Provider then please feel free to open a new issue - but since this should be fixed by updating to the latest version of the AzureRM Provider I'm going to close this issue for the moment.

Thanks!
