### ISSUE TITLE
Terraform Import fail for azurerm_monitor_scheduled_query_rules_alert

### ISSUE THREAD

**Issue by vkamlesh** [hashicorp/terraform-provider-azurerm#17890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

2.98.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert" "KeyVault-resources-status-changed" {
  count               = var.create_alerts && var.enable_diagnostic_settings ? 1 : 0
  name                = "Key Vault resources status changed"
  data_source_id      = data.azurerm_log_analytics_workspace.log-analytics-workspace.id
  frequency           = 5
  location            = "northeurope"
  resource_group_name = azurerm_resource_group.resource-group.name
  query               = <<-EOT
  AzureDiagnostics
  | where ResourceProvider == "MICROSOFT.KEYVAULT"
  | where OperationName in ('VaultPut', 'VaultDelete', 'VaultPatch', 'VaultPurge', 'KeyCreate', 'KeyDelete', 'KeyPurge', 'SecretSet', 'SecretUpdate', 'SecretDelete', 'SecretPurge', 'CertificateCreate', 'CertificateUpdate', 'CertificateDelete', 'CertificatePurge')
  | where ResultType == "Success"
  | extend username=identity_claim_upn_s
  | extend resource_item=id_s
  | extend client_ip=CallerIPAddress
  | extend resource=Resource
  | summarize AggregatedValue=toint(count()) by bin(TimeGenerated, 5m), tostring(username), tostring(resource), tostring(resource_item), tostring(client_ip)
  EOT

  severity = 2
  tags = {
    "alphaTeam"        = "Product Engineering"
    "CreatedBy"         = "devosp@alpha.com"
  }
  time_window = 5
  action {
    action_group = [
      data.azurerm_monitor_action_group.middleware-alerts-action-group.id
    ]
    custom_webhook_payload = "{\"GrafanaTags\":\"keyvault\",\"SlackMentions\":\"@production-engineering-team\"}"
    #custom_webhook_payload = "{ "GrafanaTags" = "keyvault","SlackMentions" = "@production-engineering-team"}"
  }
  trigger {
    operator  = "GreaterThan"
    threshold = 0
    metric_trigger {
      metric_column       = "username,resource,resource_item,client_ip"
      metric_trigger_type = "Total"
      operator            = "GreaterThanOrEqual"
      threshold           = 1
    }
  }

}
```

### Debug Output/Panic Output

```shell
bash-3.2$ TF_LOG=DEBUG;terraform import module.middleware-environment-global.azurerm_monitor_scheduled_query_rules_alert.KeyVault-resources-status-changed[0] "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledqueryrules/Key Vault resources status changed"
Acquiring state lock. This may take a few moments...
module.middleware-environment-global.azurerm_monitor_scheduled_query_rules_alert.KeyVault-resources-status-changed[0]: Importing from ID "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledqueryrules/Key Vault resources status changed"...
╷
│ Error: parsing Resource ID "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledqueryrules/Key Vault resources status changed": ID was missing the `scheduledQueryRules` element
│ 
│ 
╵
```

### Expected Behaviour

bash-3.2$ TF_LOG=DEBUG;terraform import module.middleware-environment-global.azurerm_monitor_scheduled_query_rules_alert.KeyVault-resources-status-changed[0] "/subscriptions/xxxxxxxxxx-XXXX-XXXX-XXXX-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledQueryRules/Key Vault resources status changed"
Acquiring state lock. This may take a few moments...
module.middleware-environment-global.azurerm_monitor_scheduled_query_rules_alert.KeyVault-resources-status-changed[0]: Importing from ID "/subscriptions/xxxxxxxxxx-XXXX-XXXX-XXX-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledQueryRules/Key Vault resources status changed"...
module.middleware-environment-global.azurerm_monitor_scheduled_query_rules_alert.KeyVault-resources-status-changed[0]: Import prepared!
  Prepared azurerm_monitor_scheduled_query_rules_alert for import
module.middleware-environment-global.azurerm_monitor_scheduled_query_rules_alert.KeyVault-resources-status-changed[0]: Refreshing state... [id=/subscriptions/xxxxxxxxxx-XXXXX-XXXX-XXX-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledQueryRules/Key Vault resources status changed]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

### Steps to Reproduce

1. Create under monitor/log. (Type:microsoft.insights/scheduledqueryrules).
2. az monitor scheduled-query show --resource-group  $rg --name $name
3. Add terraform code in codebase(refer _Terraform Configuration Files_)
4. run terraform import 

### References

Actually resource ID contains  "**scheduledqueryrules**"  Not "scheduledQueryRules".  The solution is to either change the import command in the [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert) or make a change in the code-base.

bash-3.2$ az monitor scheduled-query show --resource-group middleware-prod-global --name "Key Vault resources status changed" | jq .id
"/subscriptions/xxxxxxxxxx-XXXXX-XXXX-XXX-xxxxxxxxxxxxxx/resourceGroups/middleware-prod-global/providers/microsoft.insights/scheduledqueryrules/Key Vault resources status changed"
bash-3.2$

**Comment by teowa** [comment]
Hi @vkamlesh , thanks for opening this issue and providing the detailed description. I have submitted a PR to fix the bug in the document.
