### ISSUE TITLE
Support for ZoneRudundant redundancy option for Backup Vault

### ISSUE THREAD

**Issue by elesandroo** [hashicorp/terraform-provider-azurerm#17906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, 

I'd like to create an Azure Backup Vault with it's redundancy set to ZRS (ZoneRedundant). This option is available in the Azure Portal for some regions. However, Terraform supports only LocallyRedundant or GeoRedundant options. 

![image](https://user-images.githubusercontent.com/110670291/183067763-73bb8395-52ca-4597-9f51-301c6d48ec8c.png)

Is it possible to fix this?

### New or Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_vault

### Potential Terraform Configuration

```hcl
resource "azurerm_data_protection_backup_vault" "example" {
  name                = "example-backup-vault"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  datastore_type      = "VaultStore"
  redundancy          = "ZoneRedundant"
}
```

**Comment by aparker-cityworks** [comment]
@elesandroo  I'm still getting
Error: expected redundancy to be one of ["GeoRedundant" "LocallyRedundant"], got ZoneRedundant

Am I missing something? Did you close this because it works now?
