### ISSUE TITLE
Missing Tactic value`ResourceDevelopment` in azurerm_sentinel_alert_rule_scheduled

### ISSUE THREAD

**Issue by deepanshumarwah** [hashicorp/terraform-provider-azurerm#17910]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.16.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_scheduled

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "rule" {
  name                       = var.name
  log_analytics_workspace_id = var.log_analytics_workspace_id
  display_name               = var.display_name
  severity                   = var.severity
  query                      = var.query
  tactics                    = var.tactics
  description                = var.description
  enabled                    = var.enabled
  query_frequency            = var.query_frequency
  query_period               = var.query_period
  suppression_duration       = var.suppression_duration
  suppression_enabled        = var.suppression_enabled
  trigger_operator           = var.trigger_operator
  trigger_threshold          = var.trigger_threshold
}

variable "tactics" {
  description = "A set of attack categories by which to classify the rule. Any of `Collection`, `CommandAndControl`, `CredentialAccess`, `DefenseEvasion`, `Discovery`, `Execution`, `Exfiltration`, `Impact`, `InitialAccess`, `LateralMovement`, `Persistence`, and `PrivilegeEscalation`."
  type        = set(string)
}
```

### Debug Output/Panic Output

```shell
Error: expected tactics.0 to be one of [Collection CommandAndControl CredentialAccess DefenseEvasion Discovery Execution Exfiltration Impact InitialAccess LateralMovement Persistence PrivilegeEscalation PreAttack], got ResourceDevelopment
```
```


### Expected Behaviour

Tactic field should also support additional Mitre tactic values that Azure api has. 
Here is the Azure sdk that contains the list 


https://github.com/Azure/azure-sdk-for-net/blob/ddd4380b913c86f71bdae3291d8108498b14c1b1/sdk/securityinsights/Microsoft.Azure.Management.SecurityInsights/src/Generated/Models/AttackTactic.cs#L19-L35

### Actual Behaviour

```
Error: expected tactics.0 to be one of [Collection CommandAndControl CredentialAccess DefenseEvasion Discovery Execution Exfiltration Impact InitialAccess LateralMovement Persistence PrivilegeEscalation PreAttack], got ResourceDevelopment
```

### Steps to Reproduce

terraform apply

### Important Factoids

_No response_

### References

_No response_

**Comment by arledesma** [comment]
API spec definition for `ResourceDevelopment`: https://github.com/Azure/azure-rest-api-specs/blob/1b301846a0e31a668c59b264c900be2128762fac/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2022-01-01-preview/common/AlertTypes.json#L56
