### ISSUE TITLE
Azure Defender for Data Services settings are not supported on resources of type managedClusters

### ISSUE THREAD

**Issue by shgopala1** [hashicorp/terraform-provider-azurerm#17918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.201.18

### AzureRM Provider Version

3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_advanced_threat_protection

### Terraform Configuration Files

```hcl
module "windowsdefender" {
  source         = "./modules/windowsdefender"
  aks_cluster_id = module.AKS.aks_id
}

resource "azurerm_advanced_threat_protection" "akswindowsdefender" {
  target_resource_id = var.aks_cluster_id
  enabled            = true
}
```

### Debug Output/Panic Output

```shell
module.windowsdefender.azurerm_advanced_threat_protection.akswindowsdefender: Creating...
╷
│ Error: checking for presence of existing Advanced Threat Protection for "/subscriptions/8773b64f-bf60-4ae9-b948-5e0f066624e7/resourceGroups/AzureDevops/providers/Microsoft.ContainerService/managedClusters/MSF-ADO-Pipelines-Agents": security.AdvancedThreatProtectionClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Not Supported" Message="Azure Defender for Data Services settings are not supported on resources of type managedClusters"
│ 
│   with module.windowsdefender.azurerm_advanced_threat_protection.akswindowsdefender,
│   on modules/windowsdefender/windowsdefender.tf line 1, in resource "azurerm_advanced_threat_protection" "akswindowsdefender":
│    1: resource "azurerm_advanced_threat_protection" "akswindowsdefender" {
│ 
╵
```

### Steps to Reproduce

terraform plan:
+ resource "azurerm_advanced_threat_protection" "akswindowsdefender" {
      + enabled            = true
      + id                 = (known after apply)
      + target_resource_id = "/subscriptions/{subid}/resourceGroups/AzureDevops/providers/Microsoft.ContainerService/managedClusters/MSF-ADO-Pipelines-Agents"
    }

_terraform apply fails_

**Comment by tombuildsstuff** [comment]
hi @shgopala1 

Thanks for opening this issue.

Taking a look through here this error message is coming from the Azure API rather than Terraform, as such it appears that Azure Defender for Data Services isn't supported for AKS Clusters at this time. As such I believe this is working as intended at this time since this isn't supported for this resource - if you're expecting this to work have you got a reference to some Azure Documentation highlighting that this should work (which may require bumping the API version)?

Thanks!

**Comment by shgopala1** [comment]
@tombuildsstuff This is from Azure portal where the containers are clearly supported now:
![image](https://user-images.githubusercontent.com/13006786/183460281-49d11050-e834-4cf5-b9c1-f01c08f42640.png)

**Comment by tombuildsstuff** [comment]
@shgopala1 Containers refers to ACI (Azure Container Image) - not AKS unfortunately

**Comment by shgopala1** [comment]
@tombuildsstuff Are you sure? These documentation clearly states that it is meant for Kubernetes clusters: https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-introduction
https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-kubernetes-introduction

**Comment by shgopala1** [comment]
Hey @tombuildsstuff I got confirmation from Microsoft that this was meant for Container scanning. Is there a way to add this to terraform?

**Comment by sonaliborikar** [comment]
![image](https://user-images.githubusercontent.com/43044851/193011544-c4bff082-1d27-4e95-b948-7c5b5c487b12.png)

![image](https://user-images.githubusercontent.com/43044851/193011850-6bd8516c-d1c0-48f0-b56e-170ede287fde.png)


Getting issue for Webapp & KeyVaults

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It appears as though this is now deprecated for Kubernetes as can be seen here: https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-kubernetes-introduction, as such I am going to mark this issue as closed.
