### ISSUE TITLE
Azure VM Data disk attachment LUN order is incorrect

### ISSUE THREAD

**Issue by 24Phani** [hashicorp/terraform-provider-azurerm#17916]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I have deployed around 20 VMs which consist approx 80 data disks, when I run the plan LUN ID, Disk Zone, and Caching all looked good but post-deployment found that the LUN order is random when disks are attached to VMs.

Due to this mismatch, my custom extension script formatted the drives with wrong labels and drive letters as well.

Can you please tell us how we can control the disk attachment order according to the LUN id, ideally it should be 0, 1, 2, 3, 4, 5

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.15.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_data_disk_attachment

### Terraform Configuration Files

```hcl
locals {
  vm_disks = flatten([
    for srv in local.vm_instances : [
      for i in range(1, srv.data_disks_count + 1) : {
        disk_name    = "${format("%s-DD%02d", srv.instance_name, i - 1)}"
        disk_gb      = "${element(srv.data_disks[*], i - 1)}"
        disk_zone    = srv.zone
        disk_caching = "${element(srv.host_caching[*], i - 1)}"
        disk_lun     = i - 1
      }
    ]
  ])
}



resource "azurerm_virtual_machine_data_disk_attachment" "data_disk-attach" {
  for_each           = { for server in local.vm_disks : server.disk_name => server }
  managed_disk_id    = azurerm_managed_disk.data_disk[each.value.disk_name].id
  virtual_machine_id = azurerm_windows_virtual_machine.win_vm[element(split("-", each.value.disk_name), 0)].id
  lun                = each.value.disk_lun
  caching            = each.value.disk_caching
  depends_on         = [azurerm_managed_disk.data_disk, azurerm_windows_virtual_machine.win_vm]
}
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

Based on the LUN number/id disks should have been attached to the VM.

### Actual Behaviour

It is assigning the LUN order randomly.

![image](https://user-images.githubusercontent.com/51828046/183247211-a1682cb9-c6a2-454f-aa0d-fc055384e575.png)

### References

https://discuss.hashicorp.com/t/azure-data-disk-lun-order/40227

**Comment by tombuildsstuff** [comment]
hi @24Phani 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader configuration related questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Since [this Terraform Configuration question has been asked on the HashiCorp Discuss forum](https://discuss.hashicorp.com/t/azure-data-disk-lun-order/40227), I'm going to close this issue in favour of that one where someone should be able to assist further.

Thanks!
