### ISSUE TITLE
configuring azurerm_disk_encryption_set with a key vault in different subscription does not work

### ISSUE THREAD

**Issue by nitgupta4** [hashicorp/terraform-provider-azurerm#17924]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_disk_encryption_set 

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.0.0"
    }
  }
  required_version = ">= 1.0.0"
}

provider "azurerm" {
  features {}

  alias           = "hub"
  subscription_id = "XXXXXXXXXXXXXXX"
}

# provider - spoke
provider "azurerm" {
  features {}

  alias           = "spoke"
  subscription_id = "XXXXXXXXXXXXXX"
}


locals {
  keyVaultName  = "KV Name created in hub subscription"
  keyvaultResourceGroupName = "rg-bankxcorpconuks101"
  secretKeyName = "keyname"
  desName = "des-instanceinspoke"
  desResourceGroupName  = "rg-instanceinspoke"


}
data "azurerm_key_vault" "hubkv" {
  provider            = azurerm.hub
  name                = local.keyVaultName
  resource_group_name = local.keyvaultResourceGroupName
}

data "azurerm_key_vault_key" "key" {
  provider = azurerm.hub
  name = local.secretKeyName
  key_vault_id = data.azurerm_key_vault.hubkv.id

}


#disk encryption set - spoke
resource "azurerm_disk_encryption_set" "main" {
  provider            = azurerm.spoke
  name                = local.desName
  resource_group_name = local.desResourceGroupName
  location            = data.azurerm_key_vault.hubkv.location
  key_vault_key_id    = data.azurerm_key_vault_key.key.id
  identity {
    type = "SystemAssigned" # Only supports SystemAssigned identity
  }
}
```

### Debug Output/Panic Output

```shell
Error: validating Key Vault Key "https://cccccccc.vault.azure.net/keys/ffffff/dfssssssssss" for Disk Encryption Set: Unable to determine the Resource ID for the Key Vault at URL "https://yyyyyyyyyyy.vault.azure.net/"
│
│   with azurerm_disk_encryption_set.main,
│   on main.tf line 80, in resource "azurerm_disk_encryption_set" "main":
│   80: resource "azurerm_disk_encryption_set" "main" {
│


Enabled detailed terraform Tracing and can see it is trying to make a request to fetch KV details from spoke subscription instead

DEBUG] provider.terraform-provider-azurerm_v3.17.0_x5.exe: AzureRM Request: 
GET /subscriptions/<spoke subscriptionid>>/resources?%24filter=resourceType+eq+%27Microsoft.KeyVault%2Fvaults%27+and+name+eq+%27xxx%27&%24top=5&api-version=2020-06-01 HTTP/1.1
Host: management.azure.com
Which results in 0 records {"value":[]} and rightly so as the relevant KV exists in different subscription
```

### Expected Behaviour

It should be able to create a Disk Encryption set which is referring to KV whoch is in different subscription but same region. Per Azure https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption#restrictions it is supported and should be working. Tried with Powershell Az module and it works for this setup as mentioned here https://docs.microsoft.com/en-us/azure/virtual-machines/windows/disks-enable-customer-managed-keys-powershell#use-a-key-vault-in-a-different-subscription

### Actual Behaviour

It fails while creating the encryption set with error

### Steps to Reproduce

1. Create a KV in 1 subscription (referring as Hub)
2. Add a secret key
3. Create a resource group (as mentioned in desResourceGroupName local) in another subscription (referring as Spoke) but in same location as KV
4. Set locals values
5. Run the template

**Comment by ms-zhenhua** [comment]
Hi @nitgupta4, thank you for reporting this issue. I have created this [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/17964)to fix this issue.
