### ISSUE TITLE
Support for [sqlvm] manual backup  backup schedule

### ISSUE THREAD

**Issue by ampm24g** [hashicorp/terraform-provider-azurerm#17931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is an option (Backup Schedule) I need to fill in when I configure sqlvm backup manual section through Azure Portal.

<img width="456" alt="sqlvm backup" src="https://user-images.githubusercontent.com/60175982/183596957-a2911a90-603f-47a8-8d26-d96d54be79c8.PNG">

But it seems Terraform doesn't support **backup schedule** in manual_schedule block.  Can somebody clarify how I can configure the backup schedule option in Terraform manual schedule block?

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_virtual_machine#log_backup_frequency_in_minutes

The manual_schedule block supports the following:
[full_backup_frequency]
[full_backup_start_hour]
[full_backup_window_in_hours]
[log_backup_frequency_in_minutes]

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_virtual_machine

**Comment by myc2h6o** [comment]
Hi @ampm24g thanks for opening the issue! I'll be working on this. From the [document](https://docs.microsoft.com/en-us/azure/azure-sql/virtual-machines/windows/automated-backup?view=azuresql#configure-new-vms) and my own testing, the days in Backup schedule seems to be configurable on Portal only for an existing VM. I'll see if we are able to configure it at create time by API.

**Comment by ampm24g** [comment]
@myc2h6o Thanks for picking this up.   I just found I am able to configure Backup schedule from Azure portal, but as my change will be overwritten by Terraform.  I have to do the same change through Terraform, hence asking this question.
