### ISSUE TITLE
ip_restriction does not support ranges

### ISSUE THREAD

**Issue by daseth** [hashicorp/terraform-provider-azurerm#17937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.1.7

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
locals {
    ip_restrictions = [
       {
        name = "Cloudflare-1"
        address_range = "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20"
        priority = "500"
      },

      {
        name = "Cloudflare-2"
        address_range = "197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22"
        priority = "510"
      }
]
}

resource "azurerm_linux_web_app" "front_end_app" {
  name = "${var.name}-front-end-app"

  location                  = var.resource_group.location
  resource_group_name       = var.resource_group.name
  service_plan_id           = azurerm_service_plan.app_service_plan.id
  virtual_network_subnet_id = azurerm_subnet.app_service_subnet_outbound.id

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on = false
    container_registry_use_managed_identity = true

    application_stack {
      docker_image     = "${var.acr.login_server}/${var.front_end_config.container_name}"
      docker_image_tag = "latest"
    }
    
    dynamic "ip_restriction" {
    for_each = local.ip_restrictions
    content {
      name        = ip_restriction.value["name"]
      ip_address  = ip_restriction.value["address_range"]
      priority    = ip_restriction.value["priority"]
      action      = "Allow"
    }
  }

  }
  
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
│ Error: expected "site_config.0.ip_restriction.1.ip_address" to be a valid IPv4 Value, got 197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22: invalid CIDR address: 197.234.240.0/22,198.41.128.0/17,162.158.0.0/15,104.16.0.0/13,104.24.0.0/14,172.64.0.0/13,131.0.72.0/22
```

### Expected Behaviour

Microsoft supports up to 8  ranges per single IP restrictions rule. We expect to be able to provide multiple sources in these rules:

https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions#multi-source-rules

### Actual Behaviour

Terraform is throwing an error  saying it is expecting a single IP address.

### References

https://docs.microsoft.com/en-us/azure/app-service/app-service-ip-restrictions#multi-source-rules

**Comment by michelefa1988** [comment]
I dont think Microsoft will tell you that its a bug, perhaps a feature, but you  need to split each ip/cidr then use a dyanmic block as you are doing

This is how I stored the variable for application insights ranges, then a use dyanamic blocks just like you did. For other resource you may need to use something [like this](https://stackoverflow.com/questions/69016536/terraform-flatten-tuple-to-string) 
```
locals {
  microsoft_appinsights_ip_addresses      =  [
    {
      name       = "appi"
      priority   = "2000"
      ip_address = "51.144.56.96/28"
    },
    {
      name       = "appi"
      priority   = "2000"
      ip_address = "51.144.56.112/28"
    },
    {
      name       = "appi"
      priority   = "2000"
      ip_address = "51.144.56.128/28"
    }
]
}
```

**Comment by daseth** [comment]
@michelefa1988  check out the Microsoft link above: having multiple  sources in one rule is possible if you create the rule with azure cli/powershell.
So this works for me: 
az webapp config access-restriction add -g "rg_name" -n "app_svc_name" --priority 101 --ip-address "173.245.48.0/20,103.21.244.0/22,103.22.200.0/22,103.31.4.0/22,141.101.64.0/18,108.162.192.0/18,190.93.240.0/20,188.114.96.0/20"  --action Allow

**Comment by DrikoldLun** [comment]
@daseth Thanks for pointing it out! I will follow this issue and make proper adjustment on `ip_address` validation.
