### ISSUE TITLE
Support for KMS etcd encryption to an Azure Kubernetes Service (AKS)

### ISSUE THREAD

**Issue by katbyte** [hashicorp/terraform-provider-azurerm#17957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support KMS as describe in https://docs.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by justinas-b** [comment]
I see this was recently introduced under https://github.com/Azure/AKS/issues/845

**Comment by Bananenbieger1234** [comment]
> I see this was recently introduced under [Azure/AKS#845](https://github.com/Azure/AKS/issues/845)

Which means it can be integrated into terrafrom !? :)

**Comment by justinas-b** [comment]
> 

I think so! 🤟

**Comment by BartvdBerkHU** [comment]
I can't find a reference for KMS, etcd/database encryption on the Terraform Azure docs for resource Kubernetes_cluster: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster

Will this feature become available? And in what timeframe if I may ask?

**Comment by flisbao** [comment]
Hello, is there any update regarding this matter?

**Comment by lahudeshmukh** [comment]
Hello, Any update on this request please . We are also waiting for this adoption in terraform .

**Comment by mkilchhofer** [comment]
Working on this over there: https://github.com/hashicorp/terraform-provider-azurerm/pull/19893
