### ISSUE TITLE
Support for redirect URL within custom_rule block for azurerm_frontdoor_firewall_policy

### ISSUE THREAD

**Issue by LWNetworks** [hashicorp/terraform-provider-azurerm#17951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Within Azure Front Door (Classic) WAF's, there is an option to redirect to a custom page at a top level for the WAF, but also on a per-rule basis. (Within the portal)

However within the documentation 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor_firewall_policy

It only mentions the redirect_url at the top level, not within the custom_rule block. Note - there is support for the below

custom_rule {
action = "Redirect"
}

But no apparent way of configuring the redirect URL

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_frontdoor_firewall_policy" "WAF" {
  name                = "waf-policy"
  resource_group_name = "example-rg"
  enabled             = true
  mode                = "Prevention"

  custom_block_response_status_code = 403

  ##OWASP Start##
  managed_rule {
    type    = "Microsoft_DefaultRuleSet"
    version = 1.1
  }

  custom_rule { 
    name                           = "Redirection"
    enabled                        = true
    priority                       = 3
    rate_limit_duration_in_minutes = 1
    rate_limit_threshold           = 10
    type                           = "MatchRule"
    action                         = "Redirect"
    redirect_url = "https://blocked-traffic-redirected-to-this.com"

    match_condition {
      match_variable     = "RemoteAddr"
      operator           = "GeoMatch"
      negation_condition = false
      match_values       = ["XX" ]
    }
  }
}
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor_firewall_policy

**Comment by WodansSon** [comment]
@LWNetworks the legacy Frontdoor resource is being retired and as such is no longer being developed in the provider. I am sorry if this causes you any inconvenience.
