### ISSUE TITLE
Support for data source `azurerm_monitor_data_collection_endpoint`

### ISSUE THREAD

**Issue by nbjohnson** [hashicorp/terraform-provider-azurerm#17956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new resource `azurerm_monitor_data_collection_endpoint` was just added and now `azurerm_monitor_data_collection_association` is in the works and under review. To properly be able to use the data collection association I need the id of the data collection endpoint. Can a data source be added for `azurerm_monitor_data_collection_endpoint` so its id  can easily be looked up?

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_endpoint

### Potential Terraform Configuration

```hcl
data "azurerm_monitor_data_collection_endpoint" "example" {
  resource_group_name = "terraform-example-rg"
  name                = "tf-dce"
}

output "data_collection_endpoint_id" {
  value = data.azurermr_monitor_data_collection_endpoint.example.id
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/17831

https://docs.microsoft.com/en-us/rest/api/monitor/data-collection-endpoints/get?tabs=HTTP

**Comment by teowa** [comment]
@nbjohnson thanks for submiting this issue. I am going to work on this.🙂

**Comment by nbjohnson** [comment]
@teowa Are you able to request a review for this PR and for your `azurerm_monitor_data_collection_rule_association` PR? I can't wait to see these merged in as they are exactly what is needed for me atm.

**Comment by teowa** [comment]
Thanks @nbjohnson for the comment. This pr is already in our review list, unfortunately, we may not be able to provide an ETA at the current moment. I'll keep a close eye on it and update you once there is a progress.
