### ISSUE TITLE
Storage account network rules never set to 'disabled'

### ISSUE THREAD

**Issue by ChrisTav424** [hashicorp/terraform-provider-azurerm#17976]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.201.18

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_network_rules, azurerm_storage_account

### Terraform Configuration Files

```hcl
Using either a network_rules block inside the azurerm_storage_account resource like this:

resource "azurerm_storage_account" "main" {
  name                            = var.storage_account_name
  resource_group_name             = var.storage_account_rg
  location                        = var.storage_account_location
  account_tier                    = var.storage_account_tier
  account_replication_type        = var.storage_account_replication_type
  account_kind                    = var.storage_account_kind
  min_tls_version                 = var.storage_account_tls
  large_file_share_enabled        = var.large_file_share_enabled
  enable_https_traffic_only       = var.enable_https_traffic_only
  allow_nested_items_to_be_public = var.allow_nested_items_to_be_public
  tags                            = var.storage_account_tags

network rules {
default_action             = "Deny"
}
}

or using the seperate azurerm_storage_account_network_rules resource

resource "azurerm_storage_account_network_rules" "main" {
  storage_account_id = azurerm_storage_account.main.id
  default_action             = "Deny"
}

It never sets it to disabled
```

### Debug Output/Panic Output

```shell
module.storage-accounts["christest"].azurerm_storage_account_network_rules.main: Modifying... [id=/subscriptions/<removed>/resourceGroups/rg-test/providers/Microsoft.Storage/storageAccounts/stchristest1]
module.storage-accounts["christest"].azurerm_storage_account_network_rules.main: Modifications complete after 2s [id=/subscriptions/<removed>/resourceGroups/rg-test/providers/Microsoft.Storage/storageAccounts/stchristest1]
```

### Expected Behaviour

It should set the storage account to 'disabled'

![image](https://user-images.githubusercontent.com/44398463/184308979-42de7f02-4901-4224-9449-e33e713c9371.png)

### Actual Behaviour

It only ever sets it to 'enabled from selected networks and IP addresses'

![image](https://user-images.githubusercontent.com/44398463/184308941-c937c391-f18f-45f0-bd26-f683560f12d1.png)

### Steps to Reproduce

terraform apply

### Important Factoids

Running from either a self hosted agent or Microsoft hosted agent

**Comment by ASHR4** [comment]
Hopefully #18005 can be completed ASAP I've got the same issue.
