### ISSUE TITLE
Error when creating a storage account in germanywestcentral

### ISSUE THREAD

**Issue by antonia-adler** [hashicorp/terraform-provider-azurerm#17974]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.16.0

### Affected Resource(s)/Data Source(s)

azuread v2.27.0, azurerm v3.16.0

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage_acc" {
  name                            = "storage_account_name"
  resource_group_name             = "resource_group_name"
  location                        = "germanywestcentral"
  account_tier                    = var.account_tier
  account_replication_type        = var.account_replication_type
  account_kind                    = var.account_kind
  allow_nested_items_to_be_public = false
  enable_https_traffic_only       = true
  min_tls_version                 = "TLS1_2"
  is_hns_enabled                  = true
}
```

### Debug Output/Panic Output

```shell
Error: creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="LocationNotValid" Message="Supplied location germanywestcentral is not valid."
```

### Expected Behaviour
Creating a new storage account in germanywestcentral

### Actual Behaviour
Error

### Steps to Reproduce
Execute terraform snippet

**Comment by magodo** [comment]
@antonia-adler I've tried following config with the latest provider:

```hcl
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-storage-220816112105435513"
  location = "germanywestcentral"
}
resource "azurerm_storage_account" "test" {
  name                          = "unlikely24exst2acctv9ipl"
  resource_group_name           = azurerm_resource_group.test.name
  location                      = azurerm_resource_group.test.location
  account_tier                  = "Standard"
  account_replication_type      = "LRS"
}
```

It works fine. May I know whether you are using the Azure public cloud as `germanywestcentral` is only supported for the public cloud.

**Comment by antonia-adler** [comment]
Thanks @magodo for your reply. Yes, should be the public cloud.

This is my terraform output:
`
  + resource "azurerm_storage_account" "storage_acc_resources" {
      + access_tier                       = (known after apply)
      + account_kind                      = "BlockBlobStorage"
      + account_replication_type          = "ZRS"
      + account_tier                      = "Premium"
      + allow_nested_items_to_be_public   = false
      + cross_tenant_replication_enabled  = true
      + enable_https_traffic_only         = true
      + id                                = (known after apply)
      + infrastructure_encryption_enabled = false
      + is_hns_enabled                    = true
      + large_file_share_enabled          = (known after apply)
      + location                          = "germanywestcentral"
      + min_tls_version                   = "TLS1_2"
      + name                              = "storage_account_name"
      + nfsv3_enabled                     = false
      + primary_access_key                = (sensitive value)
      + primary_blob_connection_string    = (sensitive value)
      + primary_blob_endpoint             = (known after apply)
      + primary_blob_host                 = (known after apply)
      + primary_connection_string         = (sensitive value)
      + primary_dfs_endpoint              = (known after apply)
      + primary_dfs_host                  = (known after apply)
      + primary_file_endpoint             = (known after apply)
      + primary_file_host                 = (known after apply)
      + primary_location                  = (known after apply)
      + primary_queue_endpoint            = (known after apply)
      + primary_queue_host                = (known after apply)
      + primary_table_endpoint            = (known after apply)
      + primary_table_host                = (known after apply)
      + primary_web_endpoint              = (known after apply)
      + primary_web_host                  = (known after apply)
      + queue_encryption_key_type         = "Service"
      + resource_group_name               = "resource-group"
      + secondary_access_key              = (sensitive value)
      + secondary_blob_connection_string  = (sensitive value)
      + secondary_blob_endpoint           = (known after apply)
      + secondary_blob_host               = (known after apply)
      + secondary_connection_string       = (sensitive value)
      + secondary_dfs_endpoint            = (known after apply)
      + secondary_dfs_host                = (known after apply)
      + secondary_file_endpoint           = (known after apply)
      + secondary_file_host               = (known after apply)
      + secondary_location                = (known after apply)
      + secondary_queue_endpoint          = (known after apply)
      + secondary_queue_host              = (known after apply)
      + secondary_table_endpoint          = (known after apply)
      + secondary_table_host              = (known after apply)
      + secondary_web_endpoint            = (known after apply)
      + secondary_web_host                = (known after apply)
      + shared_access_key_enabled         = true
      + table_encryption_key_type         = "Service"

      + blob_properties {
          + change_feed_enabled      = false
          + default_service_version  = (known after apply)
          + last_access_time_enabled = false
          + versioning_enabled       = false

          + container_delete_retention_policy {
              + days = 7
            }

          + delete_retention_policy {
              + days = 7
            }
        }

      + network_rules {
          + bypass                     = (known after apply)
          + default_action             = "Allow"
          + ip_rules                   = (known after apply)
          + virtual_network_subnet_ids = (known after apply)
        }

      + queue_properties {
          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known after apply)
              + max_age_in_seconds = (known after apply)
            }

          + hour_metrics {
              + enabled               = (known after apply)
              + include_apis          = (known after apply)
              + retention_policy_days = (known after apply)
              + version               = (known after apply)
            }

          + logging {
              + delete                = (known after apply)
              + read                  = (known after apply)
              + retention_policy_days = (known after apply)
              + version               = (known after apply)
              + write                 = (known after apply)
            }

          + minute_metrics {
              + enabled               = (known after apply)
              + include_apis          = (known after apply)
              + retention_policy_days = (known after apply)
              + version               = (known after apply)
            }
        }

      + routing {
          + choice                      = (known after apply)
          + publish_internet_endpoints  = (known after apply)
          + publish_microsoft_endpoints = (known after apply)
        }

      + share_properties {
          + cors_rule {
              + allowed_headers    = (known after apply)
              + allowed_methods    = (known after apply)
              + allowed_origins    = (known after apply)
              + exposed_headers    = (known after apply)
              + max_age_in_seconds = (known after apply)
            }

          + retention_policy {
              + days = (known after apply)
            }

          + smb {
              + authentication_types            = (known after apply)
              + channel_encryption_type         = (known after apply)
              + kerberos_ticket_encryption_type = (known after apply)
              + versions                        = (known after apply)
            }
        }
    }
`
Do you see a problem with that?
It fails with
`
│ Error: creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="LocationNotValid" Message="Supplied location germanywestcentral is not valid."
│ 
│   with module.storage_module.azurerm_storage_account.storage_acc_resources["germanywestcentral"],
│   on storage/main.tf line 1, in resource "azurerm_storage_account" "storage_acc_resources":
│    1: resource "azurerm_storage_account" "storage_acc_resources" {

`

**Comment by magodo** [comment]
@antonia-adler As you are using the `ZRS` replication type, which requires the location has multiple AZs, per the [Azure document](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview#azure-regions-with-availability-zones), `germanywestcentral` isn't one of them. You can also try it on Portal, where when you select the `germanywestcentral` location, you are only allowed to set `LRS`.
