### ISSUE TITLE
`azure_blob_storage_location` in `azurerm_data_factory_dataset_json` doesn't allow for empty filename and path

### ISSUE THREAD

**Issue by kashw2** [hashicorp/terraform-provider-azurerm#17972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I'm able to have this sort of functionality reciprocated in the portal however the current version of the provider doesn't allow for that to be reflected in terraform and currently I'm forced to ignore changes to `azure_blob_storage_location` `path` and `filename`, and make the changes in the portal.

The CLI also allows this via:

```
az datafactory dataset create --dataset-name "example" --factory-name "example" --resource-group "example" --properties "properties.json"
```

where `properties.json` contains:

```
{
        "linkedServiceName": {
            "referenceName": "Azure Blob Storage",
            "type": "LinkedServiceReference"
        },
        "annotations": [],
        "type": "Json",
        "typeProperties": {
            "location": {
                "type": "AzureBlobStorageLocation",
                "container": "example"
            },
            "encodingName": "UTF-8"
        },
        "schema": {}
}
```

### Terraform Version

1.2.6

### AzureRM Provider Version

3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_dataset_json

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_storage_account" "example" {
  name                     = "example"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "example"
  storage_account_name  = azurerm_storage_account.example.name
}

resource "azurerm_data_factory_linked_service_azure_blob_storage" "example" {
  data_factory_id      = azurerm_data_factory.example.id
  name                 = "Azure Blob Storage"
  connection_string    = azurerm_storage_account.example.connection_string
  use_managed_identity = true
}
resource "azurerm_data_factory_dataset_json" "example" {
  name                = "Json_Client_Destination"
  data_factory_id     = azurerm_data_factory.example.id
  linked_service_name = azurerm_data_factory_linked_service_web.example.name

  azure_blob_storage_location {
    container                = azurerm_storage_container.example.name
    filename                 = ""
    path                     = ""
    dynamic_filename_enabled = true
    dynamic_path_enabled     = true
  }

  encoding = "UTF-8"

}
```
```


### Debug Output/Panic Output

```shell
│ Error: expected "azure_blob_storage_location.0.filename" to not be an empty string, got 
│ 
│   with module.test.module.data_factory.module.dataset.azurerm_data_factory_dataset_json.client_json_destination,
│   on modules/test/dataFactory/dataset/dataset.tf line 44, in resource "azurerm_data_factory_dataset_json" "json_destination":
│   44:     filename = ""
│ 
╵
╷
│ Error: expected "azure_blob_storage_location.0.path" to not be an empty string, got 
│ 
│   with module.test.module.data_factory.module.dataset.azurerm_data_factory_dataset_json.client_json_destination,
│   on modules/test/dataFactory/dataset/dataset.tf line 45, in resource "azurerm_data_factory_dataset_json" "json_destination":
│   45:     path = ""
```

### Expected Behaviour

should pass and have the following working json code representation:

```
{
    "name": "Json_Client_Destination",
    "properties": {
        "linkedServiceName": {
            "referenceName": "Azure Blob Storage",
            "type": "LinkedServiceReference"
        },
        "annotations": [],
        "type": "Json",
        "typeProperties": {
            "location": {
                "type": "AzureBlobStorageLocation",
                "container": "example"
            },
            "encodingName": "UTF-8"
        },
        "schema": {}
    },
    "type": "Microsoft.DataFactory/factories/datasets"
}
```

### Actual Behaviour

with `dynamic_filename_enabled` and `dynamic_path_enabled`:

The argument "filename" is required, but no definition was found.
The argument "path is required, but no definition was found.

with `dynamic_filename_enabled`, `dynamic_path_enabled` and both `filename` and `path` set to empty strings: 

Error: expected "azure_blob_storage_location.0.filename" to not be an empty string, got
Error: expected "azure_blob_storage_location.0.path" to not be an empty string, got 

without:

The argument "filename" is required, but no definition was found.
The argument "path" is required, but no definition was found.

### Steps to Reproduce

1) terraform init
2) terraform apply

### References

Somewhat related https://github.com/hashicorp/terraform-provider-azurerm/issues/13787 however only mentions filepath and lacks the amount of information the issues templates requires.

https://docs.microsoft.com/en-us/cli/azure/datafactory/dataset?view=azure-cli-latest#az-datafactory-dataset-create

**Comment by tombuildsstuff** [comment]
Closing since this has been [fixed in v3.20.0](https://github.com/hashicorp/terraform-provider-azurerm/pull/18061#issuecomment-1227934968)
