### ISSUE TITLE
│ Error: encoding: setting "virtual_network_subnet_id": Invalid address to set: []string{"virtual_network_subnet_id"}

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform-provider-azurerm#17982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app_slot

### Terraform Configuration Files

```hcl
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# CREATE AN AZURE APP SERVICE PLAN
# This Terraform template configures an Azure App Service Plan
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
data "azurerm_client_config" "current" {
}

data "azurerm_windows_web_app" "webapp" {
  for_each            = var.app_services_win_slot
  name                = each.value["web_app_name"]
  resource_group_name = each.value["web_app_rg"]
}

data "azurerm_storage_account" "storageaccount" {
  name                = var.storage_account_name
  resource_group_name = var.storage_account_rg
}

#---------------------------------------------------
# CREATE NEW APP SERVICE
#---------------------------------------------------

resource "azurerm_windows_web_app_slot" "web_app_slot" {
  for_each                        = var.app_services_win_slot
  name                            = each.value["name"]
  app_service_id                  = data.azurerm_windows_web_app.webapp[each.key].id
  client_affinity_enabled         = each.value["client_affinity_enabled"]
  client_certificate_enabled      = each.value["client_certificate_enabled"]
  client_certificate_mode         = each.value["client_certificate_mode"]
  enabled                         = try(each.value["enabled"], true)
  https_only                      = try(each.value["https_only"], true)
  key_vault_reference_identity_id = try(data.azurerm_user_assigned_identity.ids[each.key].id, null)
  zip_deploy_file                 = try(each.value["zip_deploy_file"], null)
  tags                            = each.value["tags"]
  app_settings                    = try(each.value["app_settings"], null)

  site_config" {}
}
```

### Debug Output/Panic Output

```shell
│ Error: encoding: setting "virtual_network_subnet_id": Invalid address to set: []string{"virtual_network_subnet_id"}

│

│   with data.azurerm_windows_web_app.webapp["app1"],

│   on main.tf line 8, in data "azurerm_windows_web_app" "webapp":

│    8: data "azurerm_windows_web_app" "webapp" {

│

│ encoding: setting "virtual_network_subnet_id": Invalid address to set:

│ []string{"virtual_network_subnet_id"}
```

### Actual Behaviour

│ Error: encoding: setting "virtual_network_subnet_id": Invalid address to set: []string{"virtual_network_subnet_id"}

│

│   with data.azurerm_windows_web_app.webapp["app1"],

│   on main.tf line 8, in data "azurerm_windows_web_app" "webapp":

│    8: data "azurerm_windows_web_app" "webapp" {

│

│ encoding: setting "virtual_network_subnet_id": Invalid address to set:

│ []string{"virtual_network_subnet_id"}

### Steps to Reproduce

terraform apply

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app_slot

**Comment by sahitya12** [comment]
@tombuildsstuff could you please suggest for this issue ?

**Comment by kamruldevops** [comment]
I can confirm that it started from version 3.16.0. 
![image](https://user-images.githubusercontent.com/59657905/184733102-d090f33d-9ff8-48a9-b033-5700c7f0f9d1.png)

**Comment by sahitya12** [comment]
@kamruldevops you are right i am able to deploy after downgrading version tp 315.0 . we use one version for all the modules.

**Comment by Amier3** [comment]
Hey @sahitya12 

Thanks for the bug report, we'll look into this and see what's going on.
