### ISSUE TITLE
Policy assignments do not create role assignments for the managed identity; deployIfNotExist actions fail

### ISSUE THREAD

**Issue by schwarzzz** [hashicorp/terraform-provider-azurerm#17988]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_policy_assignment, azurerm_subscription_policy_assignment

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {
  }
}

data "azurerm_subscription" "current" {
}

# Deploy - Configure diagnostic settings for Azure Key Vault to Log Analytics workspace
data "azurerm_policy_definition" "kv" {
  name = "951af2fa-529b-416e-ab6e-066fd85ac459"
}

resource "azurerm_resource_group" "target" {
  name     = "rg-policy-assignment-test"
  location = "westeurope"
}

resource "azurerm_log_analytics_workspace" "instance" {
  name                = "log-testtfpolassignment"
  location            = azurerm_resource_group.target.location
  resource_group_name = azurerm_resource_group.target.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_resource_group_policy_assignment" "assignment" {
  name                 = "assignment"
  location = azurerm_resource_group.target.location

  resource_group_id    = azurerm_resource_group.target.id
  policy_definition_id = data.azurerm_policy_definition.kv.id

  identity {
    type = "SystemAssigned"
  }

  parameters = <<PARAMS
    {
      "logAnalytics": {
        "value": "${azurerm_log_analytics_workspace.instance.id}"
      }
    }
PARAMS
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

The policy assignment's managed identity should have the roles assigned, as specified in the policy definition.
A deployIfNotExists policy action on a matching resource should succeed.

### Actual Behaviour

The policy assignment's managed identity does not have any roles assigned.
A deployIfNotExists policy action fails with error message:
`Evaluation of DeployIfNotExists policy was unsuccessful. The policy assignment '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-policy-assignment-test/providers/Microsoft.Authorization/policyAssignments/assignment' resource identity does not have the necessary permissions to create deployment '/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-policy-assignment-test/providers/Microsoft.Resources/deployments/PolicyDeployment_9540692515924901671'. Please see https://aka.ms/arm-policy-identity for usage details.`

### Steps to Reproduce

1. terraform apply
2. (Manually) create a key-vault in the created resource group
3. Check the assignment in the portal (see details below)
4. Wait the usual 10 minutes and check the Activity Log of the assignment scope to see the failed deployIfNotExist action

Go to the portal and navigate to the created assignment (Policy -Assignments - assignment - Managed Identity). The list under "Permissions - Roles" shows "No results."

Assign the exact same policy using the same user account to the same scope via the portal (select the log analytics workspace, scope and location, leave all other settings on default) and check the created assignment in the portal: The list under "Permissions - Roles" will show the roles specified in the policy definition.

**Comment by wuxu92** [comment]
hi @schwarzzz thanks for your feedback, here is some information from my understanding.

1. Assigning the policy from the portal also created the "permission-Roles" automatically, that's because the portal chose the permission and does the role assignment in the background. 

![image](https://user-images.githubusercontent.com/2633022/184811068-bd56930e-375e-45d1-95db-09e3443b70b3.png)

**but** in terraform, we need to specify the role assignments as below, so we can manage all the roles assigned to the principal

```

data "azurerm_role_definition" "mc" {
  name = "Monitoring Contributor"
}

data "azurerm_role_definition" "lac" {
  name = "Log Analytics Contributor"
}

data "azurerm_subscription" "primary" {}

resource "azurerm_role_assignment" "test" {
  scope              = "${azurerm_resource_group.target.id}"
  role_definition_id = "${data.azurerm_subscription.primary.id}${data.azurerm_role_definition.mc.id}"
  principal_id       = "${azurerm_resource_group_policy_assignment.assignment.identity[0].principal_id}"
}

resource "azurerm_role_assignment" "rg-lac" {
  scope              = "${azurerm_resource_group.target.id}"
  role_definition_id = "${data.azurerm_subscription.primary.id}${data.azurerm_role_definition.lac.id}"
  principal_id       = "${azurerm_resource_group_policy_assignment.assignment.identity[0].principal_id}"
}

resource "azurerm_role_assignment" "log-mc" {
  scope              = "${azurerm_log_analytics_workspace.instance.id}"
  role_definition_id = "${data.azurerm_subscription.primary.id}${data.azurerm_role_definition.mc.id}"
  principal_id       = "${azurerm_resource_group_policy_assignment.assignment.identity[0].principal_id}"
}

resource "azurerm_role_assignment" "log-lac" {
  scope              = "${azurerm_log_analytics_workspace.instance.id}"
  role_definition_id = "${data.azurerm_subscription.primary.id}${data.azurerm_role_definition.lac.id}"
  principal_id       = "${azurerm_resource_group_policy_assignment.assignment.identity[0].principal_id}"
}
```

2. could you please give more information about `A deployIfNotExists policy action fails with the error message`, where does this message show up and how can I find it(i didn't see it in my azure portal ')

please ping me if there are any further questions.

**Comment by schwarzzz** [comment]
@wuxu92 , thank you for your response.

I got it - and now, that I did some more research, I also found the respective statement in the Azure documentation.

> When using the portal, Azure Policy automatically grants the managed identity the listed roles once assignment starts. When using an Azure software development kit (SDK), the roles must manually be granted to the managed identity. The location of the managed identity doesn't impact its operation with Azure Policy.
[Remediate non-compliant resources with Azure Policy](https://docs.microsoft.com/en-us/azure/governance/policy/how-to/remediate-resources?tabs=azure-portal#how-remediation-access-control-works)

So sorry for raising this issue in the first place.

However, I have one concern with the proposed solution: The required roles need to be specified twice: In the policy definition (`roleDefinitionIds`) and the terraform code. Lets assume I have a custom policy and modify it over time. I might need to add a role and then there is the chance that I forget to add it to the assignment code as well.

Do you think it be feasible/reasonable to add the role definition IDs to the `azurerm_policy_definition`'s arguments?

Then it would be possible to write something like:
```
resource "azurerm_role_assignment" "policy_msi" {
  for_each = data.azurerm_policy_definition.kv.role_definition_ids

  scope                = azurerm_resource_group.target.id
  role_definition_name = each.value
  principal_id         = azurerm_resource_group_policy_assignment.assignment.identity[0].principal_id
}
```
No need to manually specify the `data` elements for the role definition...

**Comment by wuxu92** [comment]
@schwarzzz that sounds reasonable but the azurerm_policy_definition resource does not expose the role_ids for now. could you please raise a issue to request this feature then we can discuss the possibility and schedule there, and then we can close this issue here?
