### ISSUE TITLE
Role Assignment for service principal

### ISSUE THREAD

**Issue by sudharsanpunniyakotti** [hashicorp/terraform-provider-azurerm#18003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.1.3

### AzureRM Provider Version

v3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
data "azurerm_role_definition" "role" {
  name = var.rolename
}  

resource "azurerm_role_assignment" "role-assign" {
  scope                = "/subscriptions/${var.scope}"
  role_definition_id   = "/subscriptions/${var.scope}${data.azurerm_role_definition.role.id}"
  principal_id         = azuread_application.vault_app.application_id
  skip_service_principal_aad_check = true
}
```

### Debug Output/Panic Output

```shell
azurerm_role_assignment.role-assign: Creating...
azurerm_role_assignment.role-assign: Still creating... [10s elapsed]
azurerm_role_assignment.role-assign: Still creating... [20s elapsed]
azurerm_role_assignment.role-assign: Still creating... [30s elapsed]
azurerm_role_assignment.role-assign: Creation complete after 30s [id=/subscriptions/XXXXXXXXXXXXXXX/providers/Microsoft.Authorization/roleAssignments/XXXXXXXXXXXXXX]
```

### Expected Behaviour

Service princiapal added to owner role . 

### Actual Behaviour

<img width="1101" alt="Screen Shot 2022-08-15 at 12 04 52 PM" src="https://user-images.githubusercontent.com/10153748/184700063-e263b9e8-d64c-4d80-adb9-297983790f12.png">

Although add to owner role . service principal doesn't appearas excepted  in UI . 

### Steps to Reproduce

Create a New service principal , and add the role (owner or contributor) to it .

**Comment by kashw2** [comment]
Hi @sudharsanpunniyakotti, You might find success using the following configuration.

```hcl

data "azurerm_subscription" "current" {}

resource "azuread_application" "application" {
  display_name = "Application"
}

resource "azuread_service_principal" "principal" {
  application_id = azuread_application.application.id
}

resource "azurerm_role_assignment" "assignment" {
  principal_id = azuread_service_principal.principal.id
  scope        = data.azurerm_subscription.current.id
  role_definition_name = var.rolename
  skip_service_principal_aad_check = true
}


```

Take the following with a grain of salt however my understanding is that an Application (azuread_application) is a Global representation of settings, brandings etc that can have AD Roles and Groups associated however not regular roles that would exist on a User as it is not a representation of a User. The Service Principal (azuread_service_principal) is the stand in for a User that inherits settings from the Application but allows for roles that would usually be attributed to a User.

**Comment by sudharsanpunniyakotti** [comment]
Hi Kashw , 

I have tried replacing role_definition_name instead of  role_definition_Id , but it doesn work as excepted . UI still shows as ```identity not found. 
Unable to find identity.```

**Comment by calebak404** [comment]
Hi, @sudharsanpunniyakotti,
Try using `azuread_service_principal.principal.object_id` instead of  `azuread_service_principal.principal.id`

**Comment by sudharsanpunniyakotti** [comment]
> Hi, @sudharsanpunniyakotti, Try using `azuread_service_principal.principal.object_id` instead of `azuread_service_principal.principal.id`

Yeah this one works . Thank you

**Comment by mloskot** [comment]
Since solution in https://github.com/hashicorp/terraform-provider-azurerm/issues/18003#issuecomment-1216042562 with correction in https://github.com/hashicorp/terraform-provider-azurerm/issues/18003#issuecomment-1226518619 works as expected, for me too, this issue can be closed, I think.

**Comment by rcskosir** [comment]
Closing as noted above. Thanks!
