### ISSUE TITLE
windows_web_app_slot zip_deploy_file Update does not update slot, but main web_app

### ISSUE THREAD

**Issue by douglasjohns86** [hashicorp/terraform-provider-azurerm#18001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app_slot

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
  required_version = ">= 1.0"
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "testing-rg"
  location = "North Central US"
}

resource "azurerm_service_plan" "asp" {
  name                = "tmp-plan"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku_name            = "S1"
  os_type             = "Windows"
}

resource "azurerm_windows_web_app" "windows-web-app" {
  name                = "tmp-webapp"
  location            = azurerm_service_plan.asp.location
  resource_group_name = azurerm_service_plan.asp.resource_group_name
  service_plan_id     = azurerm_service_plan.asp.id

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = 1
  }

  site_config {
    always_on         = true
    use_32_bit_worker = false
  }
}

resource "azurerm_windows_web_app_slot" "slot" {
  name            = "staging"
  app_service_id  = azurerm_windows_web_app.windows-web-app.id
  zip_deploy_file = var.zip_deploy_file_location

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = 1
  }

  site_config {
    always_on         = true
    use_32_bit_worker = false
  }
}

variable "zip_deploy_file_location" {}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/douglasjohns86/e1f2cb6fd264fd55524315a9a0bc1532
```

### Expected Behaviour

Running the `terraform apply` for an update to the slot's `zip_deploy_file` should update the specified slot's `zip_deploy_file`.

### Actual Behaviour

The main web app was updated with the slot's `zip_deploy_file`.

### Steps to Reproduce

1. Create 2 different zip files to deploy: 1.zip and 2.zip
2. `terraform apply` to create the windows web app and a slot (this also deploys the code for the slot's `zip_deploy_file`) -> using 1.zip
3. `terraform apply` to update the slot's `zip_deploy_file` -> using 2.zip

**Comment by jonathan-gregorsky-aw** [comment]
Hi @Amier3! Can you help me understand the process of getting this into the next release (3.21)?  It looks like the associated PR is approved.  Thanks!
