### ISSUE TITLE
Value InhibitResponseFunction missing for azurerm_sentinel_alert_rule_scheduled tactics

### ISSUE THREAD

**Issue by mariussm** [hashicorp/terraform-provider-azurerm#18013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.16.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_scheduled

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "ar" {
    name                       = "ar"
    display_name               = "Azure DDoS Protection Detected an attack"
    severity                   = "High"
    description                = "The Azure DDoS Protection Standard service has detected an active attack towards a public IP address."

    event_grouping {
        aggregation_method = "AlertPerResult"
    }

    incident_configuration {
        create_incident = true
        grouping {
            enabled                = true
            entity_matching_method = "AllEntities"
            lookback_duration      = "P1D"
        }
    }

    query_period      = "PT5M"
    query_frequency   = "PT5M"
    trigger_operator  = "GreaterThan"
    trigger_threshold = 0
    tactics           = [
        "InhibitResponseFunction",
    ]

    entity_mapping {
        entity_type = "IP"
        field_mapping {
            column_name = "PublicIPAddress"
            identifier  = "Address"
        }
    }
    entity_mapping {
        entity_type = "AzureResource"
        field_mapping {
            column_name = "_ResourceId"
            identifier  = "ResourceId"
        }
    }


    query = <<QUERY
AzureDiagnostics
| where Category == "DDoSProtectionNotifications"
    QUERY

    log_analytics_workspace_id = var.log_analytics_workspace_id
}
```

### Debug Output/Panic Output

```shell
Error: expected tactics.0 to be one of [Collection CommandAndControl CredentialAccess DefenseEvasion Discovery Execution Exfiltration Impact InitialAccess LateralMovement Persistence PrivilegeEscalation PreAttack], got InhibitResponseFunction
```

### Expected Behaviour

InhibitResponseFunction is an allowed value

### Actual Behaviour

InhibitResponseFunction fails

### Steps to Reproduce

Apply with tactics = ["InhibitResponseFunction"]

**Comment by Amier3** [comment]
Hey @mariussm 

Thanks for bringing this to our attention. Looks like `InhibitResponseFunction` and `ImpairProcessFunction` were added in the [October preview release](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2021-10-01-preview/common/AlertTypes.json) for the sentinel API , and the provider is currently on the [September release](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/sentinel/sentinel_alert_rule.go#L7). 

I'll inquire with the team about upgrading.

**Comment by Amier3** [comment]
@mariussm 

Following up on this: We do plan on updating the API spec to a newer version that'll include the new options, but I wouldn't be able to give you an accurate timeframe on when that'd be. In the meantime we'll keep this issue open and tracked. Let me know if you have any questions

**Comment by mariussm** [comment]
Thanks :)
