### ISSUE TITLE
azurerm_key_vault access_policies: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by extravio** [hashicorp/terraform-provider-azurerm#18038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

>= 3.14

### Affected Resource(s)/Data Source(s)

azurerm_key_vault 

### Terraform Configuration Files

```hcl
access_policies = [
    {
      azure_ad_user_principal_names = ["me@acc.co.nz"]
      key_permissions               = ["Get", "List"]
      secret_permissions            = ["Get", "List", "Delete"]
      certificate_permissions       = ["Get", "Import", "List", "Delete"]
      storage_permissions           = ["Backup", "Get", "List", "Recover"]
    }
]
```

### Debug Output/Panic Output

```shell
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.key-vault.azurerm_key_vault.main to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
│ .access_policy[1].storage_permissions[1]: was cty.StringVal("Delete"), but
│ now cty.StringVal("Get").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
[...]
x 100
```

### Expected Behaviour

No error should have been reported

### Actual Behaviour

Resources are created executing Terraform from an Azure Pipelines using a service principal.
A Key Vault is created and access_policies are automatically added for the service principal (therefore not in the plan).
On Terraform apply, multiple errors (see above) are triggered.

### Steps to Reproduce

Deploy KV though azure pipelines service connection linked to a service principal in Azure

**Comment by magodo** [comment]
@extravio Would you please kindly provide the full TF config of the key vault that causes this error, so that we can further take a look at it?

**Comment by extravio** [comment]
Found the problem. No a provider issue.
