### ISSUE TITLE
azurerm_eventhub_namespace public_network_access_enabled doesn't working properly when network_rulesets block exists

### ISSUE THREAD

**Issue by omerfeldman2** [hashicorp/terraform-provider-azurerm#18054]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.5

### AzureRM Provider Version

3.17.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_namespace

### Terraform Configuration Files

```hcl
resource "azurerm_eventhub_namespace" "namespace" {
  location            = var.location
  name                = var.name
  resource_group_name = var.resource_group_name
  sku                 = var.sku_tier

  zone_redundant = var.zone_redundant

  capacity                 = var.is_auto_inflate_enabled ? (var.force_override_throughput_units ? var.throughput_units : try(tonumber(data.azurerm_eventhub_namespace.namespace[0].capacity), var.throughput_units)) : var.throughput_units
  auto_inflate_enabled     = var.sku_tier != "Standard" ? false : var.is_auto_inflate_enabled
  maximum_throughput_units = (var.sku_tier != "Premium" && var.is_auto_inflate_enabled) ? var.maximum_throughput_units : 0

  local_authentication_enabled  = true
  public_network_access_enabled = false

  network_rulesets {
    default_action                 = "Allow"
    trusted_service_access_enabled = var.trusted_service_access_enabled
  }

  tags = var.tags

  depends_on = [data.azurerm_eventhub_namespace.namespace]
}
```

### Debug Output/Panic Output

```shell
unfortunately i cannot provide the full debug file because of sensitive information,
the related debug output as i believe:

{"sku":{"name":"Standard","tier":"Standard","capacity":5},"id":"/subscriptions/<subscription-id>/resourceGroups/event-hub-namespace-test-rg/providers/Microsoft.EventHub/namespaces/ehn-testing","name":"ehn-testing","type":"Microsoft.EventHub/Namespaces","location":"West Europe","tags":{"env":"test","owner":"me"},"properties":{"minimumTlsVersion":"1.2","publicNetworkAccess":"Disabled","disableLocalAuth":false,"zoneRedundant":true,"isAutoInflateEnabled":true,"maximumThroughputUnits":10,"kafkaEnabled":true,"provisioningState":"Succeeded","metricId":"<subscription-id>:ehn-testing","createdAt":"2022-08-21T06:07:49.063Z","updatedAt":"2022-08-21T06:08:39.16Z","serviceBusEndpoint":"https://ehn-testing.servicebus.windows.net:443/","status":"Active"}}: timestamp=2022-08-21T09:08:57.854+0300

{"properties":{"defaultAction":"Allow","trustedServiceAccessEnabled":true}}: timestamp=2022-08-21T09:08:57.854+0300

{"sku":{"name":"Standard","tier":"Standard","capacity":5},"id":"/subscriptions/<subscription-id>/resourceGroups/event-hub-namespace-test-rg/providers/Microsoft.EventHub/namespaces/ehn-testing","name":"ehn-testing","type":"Microsoft.EventHub/Namespaces","location":"West Europe","tags":{"env":"test","owner":"me"},"properties":{"minimumTlsVersion":"1.2","publicNetworkAccess":"Enabled","disableLocalAuth":false,"zoneRedundant":true,"isAutoInflateEnabled":true,"maximumThroughputUnits":10,"kafkaEnabled":true,"provisioningState":"Succeeded","metricId":"<subscription-id>:ehn-testing","createdAt":"2022-08-21T06:07:49.063Z","updatedAt":"2022-08-21T06:09:05.043Z","serviceBusEndpoint":"https://ehn-testing.servicebus.windows.net:443/","status":"Active"}}: timestamp=2022-08-21T09:09:10.531+0300

{"id":"/subscriptions/<subscription-id>/resourceGroups/event-hub-namespace-test-rg/providers/Microsoft.EventHub/namespaces/ehn-testing/networkRuleSets/default","name":"default","type":"Microsoft.EventHub/Namespaces/NetworkRuleSets","location":"West Europe","properties":{"publicNetworkAccess":"Enabled","defaultAction":"Allow","virtualNetworkRules":[],"ipRules":[],"trustedServiceAccessEnabled":true}}: timestamp=2022-08-21T09:09:11.280+0300

2022-08-21T09:09:12.770+0300 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for module.event_hub_namespace.azurerm_eventhub_namespace.namespace, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .public_network_access_enabled: was cty.False, but now cty.True
      - .dedicated_cluster_id: was null, but now cty.StringVal("")
```

### Expected Behaviour

eventhub namespace should be created with public access enabled  fals
<img width="601" alt="evh-creation" src="https://user-images.githubusercontent.com/26458596/185777667-98322f47-09b6-4623-9e64-4a8aca922fe4.png">
e

### Actual Behaviour

eventhub namespace created with public access enabled  tru
<img width="269" alt="evh-portal-public-access" src="https://user-images.githubusercontent.com/26458596/185777673-3073df98-8fc5-40c3-a18c-e35ef5f4ac5f.png">
<img width="252" alt="evh-portal-template-public-access" src="https://user-images.githubusercontent.com/26458596/185777675-1a187d2d-35b7-4b04-be9a-015caae02079.png">
e
and when i rerun terraform apply without code changes:
<img width="457" alt="evh-rerun" src="https://user-images.githubusercontent.com/26458596/185777700-28116253-b3c3-4507-b86a-345edcb8fa66.png">

### Steps to Reproduce

terraform apply

NOTE:
As i noticed the real problem is when you use the network_rulesets block, in the rulesets block there is also public_network_access_enabled attribute which is defaults to true.
therefore when you use the rulesets block the public_network_access_enabled attribute overrides the entered attribute.

**Comment by omerfeldman2** [comment]
Is there any progress regarding this bug?

**Comment by omerfeldman2** [comment]
Any help please

**Comment by omerfeldman2** [comment]
If you deploy it with arm template the network_rulesets public_network_access_enabled attribute override the the regular public_network_access_enabled, unfortunately terraform doesn’t support to modify the override attribute and it default to true. Which means every time network_rulesets block is defined the event hub namespace will be created with public access.

**Comment by xiaxyi** [comment]
Have you tried below config? I think we have the override property under the network_ruleset block:
```
resource "azurerm_eventhub_namespace" "test" {
  name                = "tftesteventhubtest"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"
  capacity            = "2"
  public_network_access_enabled = false

  network_rulesets {
    default_action = "Deny"

    virtual_network_rule {
      subnet_id = azurerm_subnet.test.id
    }

    virtual_network_rule {
      subnet_id = azurerm_subnet.test2.id
    }

    ip_rule {
      ip_mask = "10.0.1.0/24"
      action  = "Allow"
    }

    ip_rule {
      ip_mask = "10.1.1.0/24"
      action  = "Allow"
    }
  }
}
```

**Comment by xiaxyi** [comment]
If I set `default_action = "Deny"`, the `public_network_access` will be override. Is this the override option that you are talking about?

**Comment by omerfeldman2** [comment]
{
  "type": "Microsoft.EventHub/namespaces/networkRuleSets",
  "apiVersion": "2022-01-01-preview",
  "name": "default",
  "properties": {
    "defaultAction": "string",
    "ipRules": [
      {
        "action": "Allow",
        "ipMask": "string"
      }
    ],
    "publicNetworkAccess": "string",
    "trustedServiceAccessEnabled": "bool",
    "virtualNetworkRules": [
      {
        "ignoreMissingVnetServiceEndpoint": "bool",
        "subnet": {
          "id": "string"
        }
      }
    ]
  }
}

This is the arm template of network_rulesets block
As you can see there is here also public_network_access_enabled attribute, this is the override one

**Comment by xiaxyi** [comment]
Thanks @omerfeldman2 , let me check the api and source code, will update once confirmed.

**Comment by omerfeldman2** [comment]
Thanks, I really appreciate that.

**Comment by xiaxyi** [comment]
Hi @omerfeldman2 , I've added the override property in the mentioned pr. I have restricted the value setting, the public network access setting in two places has to be the same, otherwise, there will be an error. You can track the status in the pr. Feel free to let me know if there is anything needed.

**Comment by omerfeldman2** [comment]
Thanks a lot!!
