### ISSUE TITLE
Custom Policy Definition Modes are restricted to 'All' or 'Indexed' only

### ISSUE THREAD

**Issue by gettek** [hashicorp/terraform-provider-azurerm#18060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_policy_definition

### Terraform Configuration Files

```hcl
resource "azurerm_management_group" "example" {
  display_name = "Example Management Group"
}

resource azurerm_policy_definition def {
  name         = "keyvault_secret_expiration"
  display_name = "Key Vault secrets should have an expiration date"
  description  = "Secrets should have a defined expiration date and not be permanent."
  policy_type  = "Custom"
  mode         = "Microsoft.KeyVault.Data" # <----

  management_group_id = azurerm_management_group.example.id

  metadata    = jsonencode(local.metadata)
  parameters  = jsonencode(local.parameters)
  policy_rule = jsonencode(local.policy_rule)

  lifecycle {
    create_before_destroy = true
  }

  timeouts {
    read = "10m"
  }
}
```

### Debug Output/Panic Output

```shell
> Error: creating/updating Policy Definition "keyvault_secret_expiration": policy.DefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyDefinitionMode" Message="The creation of custom policy definition using mode 'Microsoft.KeyVault.Data' is not allowed. This mode is allowed only in built-in policy definitions."
```

### Expected Behaviour

This is the expected behaviour for custom definitions, the built-in versions will work as seen below:

![image](https://user-images.githubusercontent.com/14080406/185876568-b094aa1e-c058-4510-9334-fcda0607d646.png)

To Remove: 
`Microsoft.ContainerService.Data`, `Microsoft.CustomerLockbox.Data`, `Microsoft.DataCatalog.Data`, `Microsoft.KeyVault.Data`, `Microsoft.MachineLearningServices.Data`, `Microsoft.Network.Data` and `Microsoft.Synapse.Data`

To Keep:
`All`, `Indexed`, `Microsoft.Kubernetes.Data` (This mode supports custom definitions as a public preview)

### Steps to Reproduce

`terraform apply`

### References

https://github.com/gettek/terraform-azurerm-policy-as-code/issues/34
[Resource Provider Modes](https://docs.microsoft.com/en-us/azure/governance/policy/concepts/definition-structure#resource-provider-modes)

**Comment by wuxu92** [comment]
hi, @gettek thanks for raising this issue. just to make sure my understanding is correct, more details want to know:

for user-defined policy_definition resource, the `policy_type` should always be `Custom` so the `mode` property should limit to these `Custom` supported values. so we have to stricter the validation of the `mode` property to only the listed 3 values? which means `azurerm` should raise an error in the `terraform plan` stage if `mode` is assigned to `"Microsoft.KeyVault.Data"`.

**Comment by gettek** [comment]
Hi @wuxu92, yes that's pretty much correct. The current error message is pretty much enough but this may well just be a documentation update to ensure users aren't misinformed. I'll raise a PR soon to see what you think. Thanks

**Comment by wuxu92** [comment]
> Hi @wuxu92 Xu Wu FTE, yes that's pretty much correct. The current error message I guess is enough but this may well just be a [documentation update](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/policy_definition#mode) to ensure users aren't misinformed. I'll raise a PR soon to see what you think. Thanks

thanks for your great work could you please link this issue to your PR so we can track it directly.

**Comment by gettek** [comment]
@wuxu92 please see [changes here](https://github.com/hashicorp/terraform-provider-azurerm/compare/main...gettek:terraform-provider-azurerm:fix/policy_remediation#diff-ae44057e87abbd4a67ff8d4b3ca016372c6cf6c21ada7805ede46e0fee4f6ae9)
