### ISSUE TITLE
Support for Cost Anomaly Alert

### ISSUE THREAD

**Issue by bulentozkir** [hashicorp/terraform-provider-azurerm#18062]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create Cost Anomaly Alert in Azure

https://docs.microsoft.com/en-us/azure/cost-management-billing/understand/analyze-unexpected-charges#create-an-anomaly-alert 

How can we create Cost Anomaly Alert in Azure using Terraform? I could only find cost consumption budget alert creation. There seems no resource provider for Cost Anomaly Alert.

### New or Affected Resource(s)/Data Source(s)

azurerm_consumption_budget_resource_group

### Potential Terraform Configuration

```hcl
resource " azure_cost_anomaly_alert" "cost_anomaly_alert" {
  scope = ""
  view = ""
  emailsubject = ""
  recipients = ""
  message = ""
  allowcontributorschange = ""
}
```

### References

Create Cost Anomaly Alert in Azure

https://docs.microsoft.com/en-us/azure/cost-management-billing/understand/analyze-unexpected-charges#create-an-anomaly-alert

**Comment by aristosvo** [comment]
@tombuildsstuff Could you add [cost-management/scheduled-actions](https://learn.microsoft.com/en-us/rest/api/cost-management/scheduled-actions/create-or-update?tabs=HTTP) / [REST API spec](https://github.com/Azure/azure-rest-api-specs/blob/6690ec1649168a1b5b2aadf4aa656de99eefdb23/specification/cost-management/resource-manager/Microsoft.CostManagement/preview/2022-04-01-preview/scheduledActions.json) to the SDK?
