### ISSUE TITLE
default_backend in url_path_map in application_gateway is declared optional but throws error if you omit it

### ISSUE THREAD

**Issue by BeTheFlow95** [hashicorp/terraform-provider-azurerm#18064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

2.96.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "application_gateway" "agw"{
  ...
  url_path_map{
    # No default_backend_address_pool-name and default_backend_http_settings_name are provided
    ...
  }
  ...
}
```

### Debug Output/Panic Output

```shell
│ Error: creating/updating Application Gateway: (Name "agw" / Resource Group "rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayUrlPathMapMustSpecifyDefaultBackendHttpSettings" Message="UrlPathMap /subscriptions/xxx-xxx-xxx-xxx-xxx/resourceGroups/rg/providers/Microsoft.Network/applicationGateways/agw/urlPathMaps/urlpathmap must specify DefaultBackendHttpSettings." Details=[]
```

### Expected Behaviour

AGW is created with specified path_rules and without default_backend.

### Actual Behaviour

Error-message is shown and nothing is agw isn't created

**Comment by ziyeqf** [comment]
Hi @BeTheFlow95, sorry for late reply.

They are "pick one of two" properties, it should configured with `default_backend_address_pool_name` and `default_backend_http_settings_name` or `default_redirect_configuration_name`. And it can not be created with no these properties.

Thanks for your reporting!
