### ISSUE TITLE
azurerm_cdn_frontdoor_origin deploys as disabled.

### ISSUE THREAD

**Issue by RutgerAlbersCE** [hashicorp/terraform-provider-azurerm#18063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin_group

### Terraform Configuration Files

```hcl
data "azurerm_cdn_frontdoor_profile" "frontdoor" {
  name                = var.frontdoor_name
  resource_group_name = var.frontdoor_resource_group_name
}

resource "azurerm_cdn_frontdoor_origin_group" "origin-group" {
  name                     = var.endpoint_name
  cdn_frontdoor_profile_id = data.azurerm_cdn_frontdoor_profile.frontdoor.id
  load_balancing {
    additional_latency_in_milliseconds = 50
    sample_size                        = 4
    successful_samples_required        = 3
  }
}

resource "azurerm_cdn_frontdoor_origin" "origin" {
  name                           = "public-ip"
  cdn_frontdoor_origin_group_id  = azurerm_cdn_frontdoor_origin_group.origin-group.id
  certificate_name_check_enabled = false
  host_name                      = var.host_name
  health_probes_enabled          = false
  http_port                      = 80
  https_port                     = 443
  origin_host_header             = null
  priority                       = 1
  weight                         = 50
}
```

### Debug Output/Panic Output

```shell
Error: waiting for the update of Front Door Origin: {\"ErrorMessage\":\"Endpoint aks-platform-euw-test_public-ip cannot be disabled since that would make all Endpoints in Endpoint Pool aks-platform-euw-test be disabled\"}
```

### Expected Behaviour

The Origin Group should be created with the status "Enabled". 

### Actual Behaviour

The Origin Group gets created with the status "Disabled". When manually changing the status to "Enabled" and then deploying again terraform will try to set it to "Disabled" again. Resulting in the error message above.

### Steps to Reproduce

When deploying the azurerm_cdn_frontdoor_origin resource with the settings supplied above it will create an origin resource, but with the "Disabled" status. 

In the documentation I can't find a property to force this status to Enabled.
(Documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_origin)

### References

Pull request for the new Frontdoor implementation:
https://github.com/hashicorp/terraform-provider-azurerm/pull/16671

**Comment by WodansSon** [comment]
@RutgerAlbersCE thank you for opening this issue, but from my understanding this is by design. The Frontdoor Origin resource will be deployed as disabled if a route has not been associated with it.

**Comment by RutgerAlbersCE** [comment]
Thanks for your reply. I'm not really sure that it's checking to see if a route has been associated for it to enable or disable the resource. My guess is that it's using the "health_probes_enabled" property to also set the origin enabled state.
At least I think that's what happening. See the following line (disclaimer: I don't really know Go: so I could be wrong):
https://github.com/hashicorp/terraform-provider-azurerm/blob/df114ab23dbb45f118a624b928401a43941d2b54/internal/services/cdn/cdn_frontdoor_origin_resource.go#L192

In our use-case we want to disable the health probes, but enable the origin resource.
The "azurerm_cdn_frontdoor_route" resource doesn't seem to be implemented yet according to the PR.

I've currently managed to get around this by using a workaround with the azapi_resource provider for the origin group. Maybe that offers some extra insight. But I'd prefer to use the azurerm provider where possible.

``` terraform
resource "azapi_resource" "origin" {
  type      = "Microsoft.Cdn/profiles/originGroups/origins@2020-09-01"
  name      = "public-ip"
  parent_id = azurerm_cdn_frontdoor_origin_group.origin_group.id
  body      = jsonencode({
    properties : {
      hostName : var.host_name
      httpPort : 80
      httpsPort : 443
      originHostHeader : null
      enabledState : "Enabled"
      priority : 1
      weight : 50
    }
  })
}
```

**Comment by WodansSon** [comment]
@RutgerAlbersCE That is exactly what is going on, in my new PR #18231 I fix this issue and expose an new field in the origin resource called `enabled`. To disable the health probes you need to remove their definition from your configuration file. You can see the linked PR for more detail.

**Comment by RutgerAlbersCE** [comment]
That's great, I'll keep an eye out for the PR and test it when it's merged. Thanks!
