### ISSUE TITLE
azurerm_synapse_workspace - No Support of UserAssigned Managed Identity 

### ISSUE THREAD

**Issue by bhvkrishna90** [hashicorp/terraform-provider-azurerm#18080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.4

### AzureRM Provider Version

3.19.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_workspace" "example" {
  name                                 = "examplesynp"
  resource_group_name                  = "synaps-rg"
  location                             = "Central US"
  storage_data_lake_gen2_filesystem_id = "azurerm_storage_data_lake_gen2_filesystem.example.id"
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = "H@Sh1CoR3!"
  identity {
    type = "SystemAssigned, UserAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected identity.0.type to be one of [SystemAssigned], got SystemAssigned, UserAssigned
```

### Expected Behaviour

Should allow configuring UAMI to Synapsis workspace in identity block.

### Actual Behaviour

Identity Type is not allowed with UserAssigned,

### Steps to Reproduce

terraform apply

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace

**Comment by ms-henglu** [comment]
Hi @bhvkrishna90 ,

Thank you for taking time to report this issue, but I think it's duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/15687

**Comment by mybayern1974** [comment]
@bhvkrishna90 per ms-henglu's suggestion, would you mind if we close this issue and you can subscribe #15687 instead?

**Comment by tombuildsstuff** [comment]
Duplicate / closing in favour of #15687, please subscribe to that issue for updates.
