### ISSUE TITLE
TF Console does not show subscription IDs for new  all_subscription_ids attribute

### ISSUE THREAD

**Issue by JustinGrote** [hashicorp/terraform-provider-azurerm#18089]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

data.azurerm_management_group

### Terraform Configuration Files

```hcl
variable "targetManagementGroupName" {
  type = string
  default = "MyMG"
}

data "azurerm_management_group" "targetManagementGroup" {
  name = var.targetManagementGroupName
}

output "SubscriptionIds" {
  value = data.azurerm_management_group.targetManagementGroup.all_subscription_ids
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

`"data.azurerm_management_group.targetManagementGroup.all_subscription_ids" | tf console` outputs the subscription IDs.

### Actual Behaviour

Output: `tolist(null) /* of string */`

### Steps to Reproduce

`"data.azurerm_management_group.targetManagementGroup.all_subscription_ids" | tf console`

Setting it to an output and running `tf plan` outputs correctly.

### References

Introducing PR: #16208

**Comment by magodo** [comment]
@JustinGrote Did you check out the `terraform state show` on the data source? Another reason might be you didn't specify the dependency for the data source on the including subscriptions.

In my case, I have:

```
provider "azurerm" {
  features {}
}

locals {
  n = 2
}

resource "azurerm_management_group" "example_parent" {
  display_name = "ParentGroup"
}

resource "azurerm_management_group" "example_child" {
  count                      = local.n
  display_name               = "ChildGroup-${count.index}"
  parent_management_group_id = azurerm_management_group.example_parent.id
}

resource "azurerm_management_group" "grand_child" {
  count                      = local.n
  display_name               = "GrandChildGroup-${count.index}"
  parent_management_group_id = azurerm_management_group.example_child[count.index].id
}

data "azurerm_management_group" "test" {
  name       = azurerm_management_group.example_parent.name
  depends_on = [azurerm_management_group.grand_child] # Notice the dependency here
}
```

After `terraform apply`, I have:

```
azurerm/management_group/nest via 💠 default
💤  echo "data.azurerm_management_group.test.management_group_ids" | tf console
tolist([
  "/providers/Microsoft.Management/managementGroups/87d2ed83-*",
  "/providers/Microsoft.Management/managementGroups/75ed7f10-*",
])

azurerm/management_group/nest via 💠 default
💤  echo "data.azurerm_management_group.test.all_management_group_ids" | tf console
tolist([
  "/providers/Microsoft.Management/managementGroups/87d2ed83-*",
  "/providers/Microsoft.Management/managementGroups/c3068ba1-*",
  "/providers/Microsoft.Management/managementGroups/75ed7f10-*",
  "/providers/Microsoft.Management/managementGroups/69de31a1-*",
])
```

I assume the same should apply to the subscription ids.

**Comment by charlesb87** [comment]
> @JustinGrote Did you check out the `terraform state show` on the data source? Another reason might be you didn't specify the dependency for the data source on the including subscriptions.
> 
> In my case, I have:
> 
> ```
> provider "azurerm" {
>   features {}
> }
> 
> locals {
>   n = 2
> }
> 
> resource "azurerm_management_group" "example_parent" {
>   display_name = "ParentGroup"
> }
> 
> resource "azurerm_management_group" "example_child" {
>   count                      = local.n
>   display_name               = "ChildGroup-${count.index}"
>   parent_management_group_id = azurerm_management_group.example_parent.id
> }
> 
> resource "azurerm_management_group" "grand_child" {
>   count                      = local.n
>   display_name               = "GrandChildGroup-${count.index}"
>   parent_management_group_id = azurerm_management_group.example_child[count.index].id
> }
> 
> data "azurerm_management_group" "test" {
>   name       = azurerm_management_group.example_parent.name
>   depends_on = [azurerm_management_group.grand_child] # Notice the dependency here
> }
> ```
> 
> After `terraform apply`, I have:
> 
> ```
> azurerm/management_group/nest via 💠 default
> 💤  echo "data.azurerm_management_group.test.management_group_ids" | tf console
> tolist([
>   "/providers/Microsoft.Management/managementGroups/87d2ed83-*",
>   "/providers/Microsoft.Management/managementGroups/75ed7f10-*",
> ])
> 
> azurerm/management_group/nest via 💠 default
> 💤  echo "data.azurerm_management_group.test.all_management_group_ids" | tf console
> tolist([
>   "/providers/Microsoft.Management/managementGroups/87d2ed83-*",
>   "/providers/Microsoft.Management/managementGroups/c3068ba1-*",
>   "/providers/Microsoft.Management/managementGroups/75ed7f10-*",
>   "/providers/Microsoft.Management/managementGroups/69de31a1-*",
> ])
> ```
> 
> I assume the same should apply to the subscription ids.

You are mentioning  **all_management_group_ids** here and not **all_subscription_ids** (not same data returned; One is about management group, the other one is about the subscription) . I encounter the same "bug" on my subscription. Any news about this ?

**Comment by magodo** [comment]
@charlesb87 Yes, and it works:

```shell
azurerm/management_group/datasource via 💠 default took 18s
💤  cat main.tf
provider "azurerm" {
  features {}
}

data "azurerm_management_group" "test" {
  display_name = "<REDACTED>"
}

output "SubscriptionIds" {
  value = data.azurerm_management_group.test.all_subscription_ids
}

azurerm/management_group/datasource via 💠 default
💤  echo data.azurerm_management_group.test.all_subscription_ids | tf console
tolist([
  "<REDACTED>",
])
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
