### ISSUE TITLE
Specifying point_in_time_restore_time_in_utc  when trying to create azurerm_postgresql_flexible_server results in error

### ISSUE THREAD

**Issue by sergiupantiru** [hashicorp/terraform-provider-azurerm#18082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I am trying to create a new Flexible Postgres Server based on a Point In Time Restore.
When specifying the `point_in_time_restore_time_in_utc` the apply fails with error. 
```json
    "properties": {
      "message": "Microsoft.DBforPostgreSQL/flexibleServers/write",
      "serviceRequestId": null,
      "statusCode": "InternalServerError",
      "statusMessage": "{\"error\":{\"code\":\"InternalServerError\",\"message\":\"An unexpected error occured while processing the request. Tracking ID: 'xxxxx'\"}}"
    },
    "status": {
      "localizedValue": "Failed",
      "value": "Failed"
    },
    "subStatus": {
      "localizedValue": "Internal Server Error (HTTP Status Code: 500)",
      "value": "InternalServerError"
    }
```
Doing the same action via UI all works but the value of `pointInTimeUTC` is different (compared to the terraform one)

When doing the same action via UI the values are:
```
"pointInTimeUTC": "2022-08-23T07:14:24.000Z"
```
When doing it via terraform:
```
"pointInTimeUTC": "2022-08-23 07:14:24 +0000 UTC"
```

Already tested with proper format and it works via terraform as well.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "test_db" {
  name                   = "test-db"
  resource_group_name    = "test-resource-group"
  location               = "West Europe"
  version                = "13"
  delegated_subnet_id    = "xxxx"
  private_dns_zone_id    = "xxxx
  zone                   = "3"

  create_mode                       = "PointInTimeRestore"
  source_server_id                  = "/subscriptions/xxxxxx/resourceGroups/test-resource-group/providers/Microsoft.DBforPostgreSQL/flexibleServers/test-base-db"
  point_in_time_restore_time_in_utc = "2022-08-23T07:14:24.000Z"
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Flexible Server (Subscription: "xxxxxxxx"
│ Resource Group Name: "test-resource-group"
│ Server Name: "test-db"): performing Create: servers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: 'xxxxxxxxx'"
```

### Expected Behaviour

Flexible postgres server should be created

### Actual Behaviour

Failure

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Currently `time.Parse` would convert `point_in_time_restore_time_in_utc` to time type not `RFC3339` so that API call failed. Submitted PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/18106) to fix this issue.

**Comment by Amier3** [comment]
@sergiupantiru 

Neil's PR fixes a couple more issues with this resource, so I think it would make sense to close the one you opened in favor of his. Regardless, we appreciate the quick PR and hope to see another one in the near future ( hopefully not on a bug though! 😅 ).

**Comment by sergiupantiru** [comment]
Oki, closed my PR. Thanks
