### ISSUE TITLE
Support for Azure SQL Always Encrypted

### ISSUE THREAD

**Issue by rrottmann** [hashicorp/terraform-provider-azurerm#18086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

*Always Encrypted* is a feature that allows to specify columns in a SQL database that are additionally encrypted. Unencrypted columns provide metadata to find the correct data rows and the client application needs to provide a *Content Encrpytion Key* in oder to decrypt the values stored in the encrypted columns.

Right now, after setting up the SQL database with Terraform, one needs to break out to [Powershell](https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/configure-always-encrypted-using-powershell?view=sql-server-ver16) for configuration of the *Always Encrypted* settings of the database.

Moreover, the SQL server is usually shipped with an enabled Firewall. So usually you need a second breakout to a shell in order to determine your current IP address so that you can configure access from a provisioning pipeline/build agent.

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_database" "test" {
  name           = "acctest-db-d"
  server_id      = azurerm_mssql_server.example.id
  collation      = "SQL_Latin1_General_CP1_CI_AS"
  license_type   = "LicenseIncluded"
  max_size_gb    = 4
  read_scale     = true
  sku_name       = "S0"
  zone_redundant = true

  sql_column_master_key = {
    name = "somename"
    key_vault = azurerm_key_vault.test.id
  }
  sql_column_encryption_keys = [
    ("column_name_1", "encryption_key_1"),
    ("column_name_2", "encryption_key_2")
  ]

  tags = {
    foo = "bar"
  }
}
```

### References

https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine?view=sql-server-ver16

**Comment by sinbai** [comment]
@rrottmann thanks for raising this issue here. To support this feature should be an Azure rest API available. However, I didn't find any API [here](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01) to support it. So Terraform could not support it until the API is ready to use. Please correct me if I missed the rest API. If it is possible, could you share the rest API here? With that, I think terraform support for it would be on the agenda.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
