### ISSUE TITLE
"runtime_scale_monitoring_enabled" setting defaults back to "false" for azurerm_windows_function_app

### ISSUE THREAD

**Issue by mg-8** [hashicorp/terraform-provider-azurerm#18092]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "func_app_wdw" {
  for_each = var.func_app

  name                = each.key
  resource_group_name = var.rg_name
  location            = var.rg_location

  storage_account_name       = azurerm_storage_account.storage-account[each.key].name
  storage_account_access_key = sensitive(azurerm_storage_account.storage-account[each.key].primary_access_key)
  service_plan_id            = azurerm_service_plan.app-svc-plan.id
  virtual_network_subnet_id  = data.azurerm_subnet.vnet-int-subnet-qry.id
  https_only                 = true
  client_certificate_enabled = true
  client_certificate_mode    = "Required"

  identity {
    type         = "UserAssigned"
    identity_ids = var.identity
  }

  site_config {
    pre_warmed_instance_count              = "1"
    http2_enabled                          = true
    use_32_bit_worker                      = false
    runtime_scale_monitoring_enabled       = true
    application_insights_connection_string = sensitive(data.azurerm_application_insights.app-insight-qry.connection_string)
    application_insights_key               = sensitive(data.azurerm_application_insights.app-insight-qry.instrumentation_key)
  }

  app_settings = {
    vnet_route_all_enabled = "1"
  }  
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.function_app.azurerm_windows_function_app.func-app-wdw["func-app-01"] will be updated in-place
  ~ resource "azurerm_windows_function_app" "func-app-wdw" {
        id                                = "/subscriptions/xxxxxxxxxxxxxxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxxxxxxxxxxxxxxx/providers/Microsoft.Web/sites/func-app-01"
        name                              = "func-app-01"
        
        # (26 unchanged attributes hidden)


      ~ site_config {
          ~ runtime_scale_monitoring_enabled       = false -> true
            # (30 unchanged attributes hidden)
        }
        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

"runtime_scale_monitoring_enabled " value should be set to true in the function app settings

### Actual Behaviour

**"runtime_scale_monitoring_enabled"** value is not saved/set to **"true"** in the function app configuration and everytime with terraform plan/apply it tries to set the value from **"false"** --> **"true"**

### Steps to Reproduce

Run terraform plan or apply with above code

**Comment by tunglvNEV** [comment]
i got same issue with azurerm_linux_function_app, terraform v3.16.0. it's bug

**Comment by mg-8** [comment]
Thanks guys for sorting this out, much appreciated!
