### ISSUE TITLE
Terraform plan with azurerm_dns_a_record fails when parsing existing dns record with azurerm 3.19.1

### ISSUE THREAD

**Issue by stusklinar** [hashicorp/terraform-provider-azurerm#18104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_dns_cname_record

### Terraform Configuration Files

```hcl
resource "azurerm_dns_cname_record" "cname" {
  name                = "hostbinding.test.com"
  zone_name           = "testZone"
  resource_group_name = "rg"
  ttl                 = 60
  record              = "cname"
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/ce204445-xxxx-xxxx-xxxx-25677e054a2c/resourceGroups/dev-dns-zones/providers/Microsoft.Network/dnszones/dev.mkmapps.com/TXT/asuid.api-gateway.dev.xxxx.com": parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"
```

### Expected Behaviour

Terraform plan should finish successfully.
With azurerm 3.18.0 it works fine.
There where no changes to the dns config, aside from upgrading the provider version to 3.19.1

Works fine on some providers - but they were new deployments - this has existing 3.18.0 state

### Actual Behaviour

Fails to apply

### Steps to Reproduce

Run terraform plan or terraform apply with an **existing** dns_a_record after upgrading to azurerm 3.19.1

### Important Factoids

Seems to affect deployments that have upgraded

### References

[Run terraform plan or terraform apply with an existing dns_a_record after upgrading to azurerm 3.19.0

](https://github.com/hashicorp/terraform-provider-azurerm/issues/18039)

**Comment by mattduguid** [comment]
issue for us running pipeline with v3.19.x/v3.20.0 and existing state with CNAME record created using earlier version v3.13.0, pinned back to v3.18.0 and worked around for now

**Comment by gogonaft** [comment]
> issue for us running pipeline with v3.19.x/v3.20.0 and existing state with CNAME record created using earlier version v3.13.0, pinned back to v3.18.0 and worked around for now

for me this did not work. I went ahead and changed respected TFSTATE file where "dnszone" resources were and updated "id": "/subscriptions/XXX/resourceGroups/YYY/providers/Microsoft.Network/dnszones/..." to "id": "/subscriptions/XXX/resourceGroups/YYY/providers/Microsoft.Network/dnsZones/...". After that azurerm >=3.19.1 versions work for me.

**Comment by gogonaft** [comment]
Hashicorp, fix the bug it's ridiculous.

**Comment by twink0r** [comment]
We build a [small script](https://gist.github.com/twink0r/b83c94ff96714565ad6dbc26210aba58) to "fix" this. 
In this case, we only use child modules and nothing in root. If you created resources in the root module, you need a small adjustment in the Python Script in Line 17.

**Comment by doug2901** [comment]
I'm facing this problem too, I changed to v3.18.0, and it seems to be working fine.

**Comment by oleksii-goi** [comment]
Issue still exist in azurerm v.3.29.1 #https://github.com/hashicorp/terraform-provider-azurerm/issues/19119

**Comment by MarkTallentire** [comment]
I have this issue when using terraform import 

`terraform import "azurerm_dns_zone.example" "/subscriptions/${subId}/resourceGroups/${resourceGrpId}/providers/Microsoft.Network/dnszones/${dnsZone}`

`parsing segment "staticDnsZones": expected the segment "dnszones" to be "dnsZones"`

**Comment by tombuildsstuff** [comment]
Taking a look through here, since #18692 adds a state migration to fix the casing for any existing `azurerm_dns_zone` resources that Terraform is tracking, I believe the original issue is resolved for existing resources and as such I'm going to close this out.

However if you're still seeing issues here I'd recommend double-checking the value being provided here, as Terraform is now validating the Resource ID format matches what we're trying to parse, the error message should be highlighting which segment doesn't match (and how to fix that) - as such updating that segment to the expected casing (also shown in the `import` section of the documentation for the relevant resource) should fix this.

Thanks!
