### ISSUE TITLE
subresource_names on azurerm_private_endpoint is mandatory and not optional as documentation suggests

### ISSUE THREAD

**Issue by jeanpaulsmit** [hashicorp/terraform-provider-azurerm#18105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Missing `subresource_names` property should be caught on Terraform apply, as that is mandatory for correct execution.

### Actual Behaviour

Missing property is accepted, leading to this error:

`Error: creating Private Endpoint "egt-endpoint" (Resource Group "test-vnet"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="MissingParameterOnPrivateLinkServiceConnection" Message="Private link service connection /subscriptions/xxxxxx/resourceGroups/test-vnet/providers/Microsoft.Network/privateEndpoints/egt-endpoint/privateLinkServiceConnections/egt-privateserviceconnection is missing required parameter 'group Id'." Details=[]`

The confusing thing is the reference to 'group Id' in the error, which can only be found in the documentation when searching for it. 

### Steps to Reproduce

The resource below is lacking `subresource_names = ["topic"]` in the private_service_connection section, which leads to the error.

```
resource "azurerm_private_endpoint" "private_endpoint_egt" {
  name                = "egt-endpoint"
  location            = data.azurerm_resource_group.rg.location
  resource_group_name = data.azurerm_resource_group.rg.name
  subnet_id           = azurerm_subnet.subnet-eg.id

  private_service_connection {
    name                           = "egt-privateserviceconnection"
    private_connection_resource_id = azurerm_eventgrid_topic.egt.id
    is_manual_connection           = false
  }
}
```

### References

I found the cause of the error via this issue:
https://github.com/hashicorp/terraform-provider-azurerm/issues/9058

This could easily be solved by making the `subresource_names` mandatory, so it's checked before the apply.
Next to that, the documentation (although containing a link to the subresource name options) could be improved.

**Comment by jayendranarumugam** [comment]
Let me give a PR for this quick fix
