### ISSUE TITLE
AKS 1.24 missing kube_config

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#18127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.1.9

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

data.azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
data "azurerm_kubernetes_cluster" "aks" {
  name                = "cluster1"
  resource_group_name = "cluster1"
}

output "name" {
  value = data.azurerm_kubernetes_cluster.aks.kube_config[0].host
   sensitive = true
}
```

### Debug Output/Panic Output

```shell
│   on data.tf line 7, in output "name":
│    7:   value = data.azurerm_kubernetes_cluster.aks.kube_config[0].host
│     ├────────────────
│     │ data.azurerm_kubernetes_cluster.aks.kube_config has a sensitive value
│ 
│ The given key does not identify an element in this collection value.
```

### Expected Behaviour

kube_config should be found and can be used in the data call

### Actual Behaviour

Error as shown above

### Steps to Reproduce

1. terraform apply

### Important Factoids

This is the new GA release of AKS 1.24.3

**Comment by DaleyKD** [comment]
Is this a duplicate of #17182 ?

**Comment by MattGarner-N** [comment]
Oh yes, so it is. Closed thanks :)
