### ISSUE TITLE
https_only is not expected in azurerm_linux_web_app site_config 

### ISSUE THREAD

**Issue by paulturner-pg** [hashicorp/terraform-provider-azurerm#18121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "my_app" {
   name = "my-azure-app-group"
   location = "UK South"
}

resource "azurerm_service_plan" "my_app" {
  name                = "my-azure-app-plan"
  location            = "UK South"
  resource_group_name = "my-azure-app-group"
  sku_name            = "P1v2"
  os_type             = "Linux"
}

resource "azurerm_linux_web_app" "my_app" {
   name = "my-azure-app"
   location = "UK South"
   resource_group_name = "my-azure-app-group"
   service_plan_id = azurerm_service_plan.my_app.id

   site_config {
       https_only = true
   }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Unsupported argument
│
│   on main.tf line 34, in resource "azurerm_linux_web_app" "my_app":
│   34:        https_only = true
│
│ An argument named "https_only" is not expected here.
╵
```

### Expected Behaviour

The plan to create the resources, including the app-service, should have been presented.

### Actual Behaviour

An error is presented.

### Steps to Reproduce

1. `terraform plan`

### References

The provider documentation regarding `https_only`: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#https_only

**Comment by mikemadeja** [comment]
Hello @paulturner-pg, this should be outside the site_config block.

![image](https://user-images.githubusercontent.com/28938328/186748084-f07aaa80-d526-4f43-9045-8e607115b2b3.png)
```

resource "azurerm_resource_group" "my_app" {
   name = "my-azure-app-group"
   location = "UK South"
}

resource "azurerm_service_plan" "my_app" {
  name                = "xmy-azure-app-plan"
  location            = "UK South"
  resource_group_name = "my-azure-app-group"
  sku_name            = "P1v2"
  os_type             = "Linux"
}

resource "azurerm_linux_web_app" "my_app" {
   name = "xmy-azure-app"
   location = "UK South"
   resource_group_name = "my-azure-app-group"
   service_plan_id = azurerm_service_plan.my_app.id
   https_only = true

   site_config {}
}

```

**Comment by xiaxyi** [comment]
@paulturner-pg Have you tried to put the property outside of the site_config?

**Comment by xiaxyi** [comment]
@paulturner-pg Good day! May I know if you tried the solution mentioned in my last comment? Feel free to let me know if you have any question.

**Comment by xiaxyi** [comment]
@AlxCloudRl We have all the properties that are needed to be put under `site_config` defined in doc:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/92154856/a0fe604e-b460-4691-a5ee-1f83d7d9ae28)

Can you share your concerns with me so I can see what's unclear and may try make some improvements. Thanks

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @mikemadeja‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
