### ISSUE TITLE
Error: no schema available for azurerm_traffic_manager_endpoint.secondary_endpoint[0] while reading state;

### ISSUE THREAD

**Issue by GilesNewSkills** [hashicorp/terraform-provider-azurerm#18140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

traffic_manager_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_traffic_manager_azure_endpoint" "primary_endpoint" {
  count               = var.env == "prod" || var.env == "uat" ? 1 : 0
  name                = "Primary"
  profile_id        = azurerm_traffic_manager_profile.gsr_spoke_tm[0].id
  weight              = 1
  priority            = 1
  target_resource_id = data.azurerm_public_ip.gsr_primary_appgw_uksouth_ip[0].id
}

resource "azurerm_traffic_manager_azure_endpoint" "secondary_endpoint" {
  count               = var.env == "prod" ? 1 : 0
  name                = "Secondary"
  profile_id        = azurerm_traffic_manager_profile.gsr_spoke_tm[0].id
  weight              = 1
  priority            = 2
  target_resource_id = data.azurerm_public_ip.gsr_secondary_appgw_ukwest_ip[0].id
}
```

### Debug Output/Panic Output

```shell
Error: no schema available for azurerm_traffic_manager_endpoint.secondary_endpoint[0] while reading state; this is a bug in Terraform and should be reported
```

**Comment by magodo** [comment]
@GilesNewSkills Assuming this issue occurs after you upgrading the provider from v2 to v3. In the [upgrade guide](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide#resource-azurerm_traffic_manager_endpoint), it said:

> The resource `azurerm_traffic_manager_endpoint` will be removed in favour of the `azurerm_traffic_manager_azure_endpoint`, `azurerm_traffic_manager_external_endpoint` and `azurerm_traffic_manager_nested_endpoint` resources.

Would you please follow this guide and refactor your configuration to using one of the above resource instead?

**Comment by GilesNewSkills** [comment]
Thanks for the reply, the upgrade guide says change from azurerm_traffic_manager_endpoint will be removed in favour of the azurerm_traffic_manager_azure_endpoint which is what i have done, am i misisng something else?
![image](https://user-images.githubusercontent.com/99276962/187391761-a93d0136-fbf7-4c4c-ba8c-90984e1e4640.png)

**Comment by magodo** [comment]
@GilesNewSkills The `azurerm_traffic_manager_endpoint` exist in your state file, that is why terraform error during reading it from the state. To address this, you can first backup your state in case anything goes wrong. Then remove `azurerm_traffic_manager_endpoint` from the state file via `terraform state rm azurerm_traffic_manager_endpoint.primary_endpoint azurerm_traffic_manager_endpoint.secondary_endpoint`. Make the changes in your config. Import those two resources back to state via `terraform import azurerm_traffic_manager_endpoint.primary_endpoint <id>` (the same for the secondary_endpoint).
