### ISSUE TITLE
itsm_receiver 

### ISSUE THREAD

**Issue by farwind** [hashicorp/terraform-provider-azurerm#18144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_monitor_action_group

### Terraform Configuration Files

```hcl
monitor_action_group_itsm_receiver = {
     "itsm1" = {
       name                 = "itsm_receiver"
       workspace_id         = "00000000-0000-0000-0000-000000000000|00000000-0000-0000-0000-000000000000"
       connection_id        = "53de6956-42b4-41ba-be3c-xxxxxxxxxxx"
       ticket_configuration = "{}"
       region               = "ger-central"
     }
    }

dynamic "itsm_receiver" {
    for_each = var.monitor_action_group_itsm_receiver != null ? var.monitor_action_group_itsm_receiver : {}
    content {
      connection_id        = itsm_receiver.value.connection_id
      name                 = itsm_receiver.value.name
      region               = itsm_receiver.value.region
      ticket_configuration = itsm_receiver.value.ticket_configuration
      workspace_id         = itsm_receiver.value.workspace_id
    }
  }
```

### Debug Output/Panic Output

```shell
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [6m0s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [6m10s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [6m20s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [6m30s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [6m40s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [6m50s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [7m0s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [7m10s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [7m20s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [7m30s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [7m40s elapsed]
module.monitor.azurerm_monitor_action_group.this[0]: Still creating... [7m50s elapsed]
╷
│ Error: creating or updating Action Group: (Name "monitordefaultgwa" / Resource Group "rg-example-monitorgwa"): insights.ActionGroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="Unknown" Message="Unknown service error" Details=[{"code":"InternalError","message":null}]
│
│   with module.monitor.azurerm_monitor_action_group.this[0],
│   on ../../main.tf line 13, in resource "azurerm_monitor_action_group" "this":
│   13: resource "azurerm_monitor_action_group" "this" {
│
╵
```

### Expected Behaviour

finnish creating resources

### Actual Behaviour

error's out with error : 
 Error: creating or updating Action Group: (Name "monitordefaultgwa" / Resource Group "rg-example-monitorgwa"): insights.ActionGroupsClient#CreateOrUpdate: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="Unknown" Message="Unknown service error" Details=[{"code":"InternalError","message":null}]
│
│   with module.monitor.azurerm_monitor_action_group.this[0],
│   on ../../main.tf line 13, in resource "azurerm_monitor_action_group" "this":
│   13: resource "azurerm_monitor_action_group" "this" {

if itsm_receiver configuration is removed resources are created properly without any error.

**Comment by teowa** [comment]
@farwind , thanks for taking the time to submit this.

This 500 error should be caused by service API bug, I have submited a issue https://github.com/Azure/azure-rest-api-specs/issues/20488. As a workaround, I have tried set 
```
ticket_configuration =  "{\"PayloadRevision\":0,\"WorkItemType\":\"Incident\",\"UseTemplate\":false,\"WorkItemData\":\"{}\",\"CreateOneWIPerCI\":false}"
```
 like in this [example](https://github.com/Azure/azure-rest-api-specs/blob/3de536d7c66c85f88d84c258ecf9d839865e17c1/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-09-01/examples/createOrUpdateActionGroup.json#L58) can resolves this error. 

Hope this may help, and please reply if you have further issues.
