### ISSUE TITLE
Add ip-address as argument in azurerm_public_ip module

### ISSUE THREAD

**Issue by dzo366** [hashicorp/terraform-provider-azurerm#18165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

Good morning, thank you for your job.

I would like to request if it possible to add the "ip-address" argument to manually assign an IP address from an existing ip prefix in the azurerm_public_ip module (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip#argument-reference)

It can be done by az cli but not using the module. Example: 

`az network public-ip create --name test1 --resource-group <rg_name> --location <lcoation> --public-ip-prefix <name_ip_prefix> <ip_address_to_assign>/32`

It would be amazing to have the same result but using the terraform module.

Thank you in advance

### New or Affected Resource(s)/Data Source(s)

azurerm_public_ip

**Comment by mybayern1974** [comment]
@dzo366 , thank you for opening this feature request. May I suggest this might be duplicate with issue #16310, and if so would you mind if we close this issue and you can subscribe #16310 instead? Or please let me know if you believe this issue is different from #16310.

**Comment by dzo366** [comment]
You are right, it is the same and I have not found it when I oppened this issue. Sorry, I have already suscribed to https://github.com/hashicorp/terraform-provider-azurerm/issues/16310, you can close this issue.

Thank you very much.
