### ISSUE TITLE
couldnt create alerts for Event Hubs (Not for EventHub Name spaces)

### ISSUE THREAD

**Issue by nikhilbattula9** [hashicorp/terraform-provider-azurerm#18171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.19.1

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_eventhub

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "main" {
  for_each = var.alert_rules
  
  name                = each.value.alertname
  resource_group_name = var.resource_group_name
  description         = each.value.description
  scopes              = data.azurerm_eventhub.exampleEH.id
  severity            = each.value.severity
  frequency           = each.value.frequency
  window_size         = each.value.windowsize
  criteria {
    metric_namespace  = each.value.metric_namespace
    threshold         = each.value.threshold
    metric_name       = each.value.metric_name
    aggregation       = each.value.aggregation
    operator          = each.value.operator
    
   
        action {
         action_group_id = var.actiongroupid
       }
  }

variable.tf

variable "alert_rules" {
    type = map(object({  
     alertname = string 
     metric_namespace = string      
     severity = number
     metric_name = string
     frequency = any
     windowsize = any
     # window size must be gretar than Frequency values be PT1M, PT5M, PT15M, PT30M, PT1H, PT6H, PT12H and P1D. Defaults to PT5M
     aggregation = string
     description = string
     operator = string
     threshold = number        
    }))


     default = {

     
    Alert_1 = {
    alertname = "IncomingRqsts"
    severity = 2
    metric_namespace = "Microsoft.EventHub/Namespaces"
    metric_name = "IncomingRequests"
    frequency = "PT30M"
    windowsize = "PT1H"
    description = "Alert fires When Reqsts is Greaterthan 80"
    aggregation = "Total"
    operator = "GreaterThan"
    threshold = 80
    }
}
```

### Debug Output/Panic Output

```shell
insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ResourceNotFound" Message="{\"code\":\"BadRequest\",\"message\":\"Detect invalid value: Microsoft.EventHub/namespaces for query parameter: 'metricnamespace', the value must be: Microsoft.EventHub/namespaces/eventhubs if the query parameter is provided, you can also skip this optional query parameter.\"}
```

### Expected Behaviour

Looking to create the alerts for Individual Azure Event Hubs ( successfully created alerts to Name Spaces) using terraform.If anyone knows a solution to this pls guide me

### Actual Behaviour

I am able to create the Alerts for Event Hub namespace.But what i am looking for is to create the Alerts to Event Hubs ( which are present in event Hub Name space)

### Steps to Reproduce

terraform apply

ERROR: it is showing metric name is not valid value for Metric Name space

### References

metric alerts do not work for some namespaces #2470

**Comment by ms-zhenhua** [comment]
Hi @nikhilbattula9, thank you for reaching out.
**Microsoft.EventHub/namespaces/eventhubs** is not a supported platform metric namespace by Azure so that you cannot create a metric alert for it.
You can refer to this [document ](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported)for more details.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ms-zhenhua‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
