### ISSUE TITLE
Subnet creation doesn't support Route Table/NSG association

### ISSUE THREAD

**Issue by sioakim** [hashicorp/terraform-provider-azurerm#18173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

During creation of a subnet it is possible via the API to specify a NSG and/or a Route Table.
Unfortunately Terraform doesn't support this in the latest version (today - 3.20.0).
According to the API it is possible to declare them:
https://docs.microsoft.com/en-us/rest/api/virtualnetwork/subnets/create-or-update?tabs=HTTP
under:
properties.routeTable and properties.networkSecurityGroup

This is causing issues when you have an Azure policy that requires a NSG or UDR specified on creation.
We have tried this with 
Deny policy: The creation will fail
Append policy: The creation will fail because it will show that resources exist (we need to create currently the association via azurerm_subnet_route_table_association as a seperate step).

The request here is to have those two at least properties added to the provider (I see that the API supports other properties as well like natGateway)

Thank you

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.20.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
  route_table_id = azurerm_route_table.example.id <--- WE WOULD NEED SOMETHING LIKE THIS
  azurerm_network_security_group_id = azurerm_network_security_group.example.id <--- WE WOULD NEED SOMETHING LIKE THIS
  

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Actual Behaviour

Parameters are not part of the latest Terraform version

**Comment by tombuildsstuff** [comment]
hi @sioakim 

These fields have been intentionally removed from the `azurerm_subnet` resource to workaround issues within the Azure Platform during the deletion of resources, as this field has been intentionally removed unfortunately this isn't something we plan to reintroduce.

Instead #9022 is tracking adding an example of how to use Azure Policy with the separate resources, and #3917 is tracking adding additional fields within the `azurerm_virtual_network` resource - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!
