### ISSUE TITLE
Support for azurerm_app_service_public_certificate on App Services with Slot Configuration 

### ISSUE THREAD

**Issue by adamsba3** [hashicorp/terraform-provider-azurerm#18184]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Looking to get support to add azurerm_app_service_public_certificate  on App Services with slot configuration.

### Description

I'm trying to deploy public certs to an app_service with slog configuration.  I found putting in the path to the rest api location using azurerm_app_service_public_certificate resources, gets the cert added to azure (example code)

`
resource "azurerm_app_service_public_certificate" "example_slots" {

  resource_group_name  = var.resourceGroupName
  app_service_name     = format("%s/slots/primary", azurerm_app_service.example.name) 
  certificate_name     = "CERTCA"
  certificate_location = "CurrentUserMy"
  blob                 = filebase64("${path.module}/CA/cert.cer")
}
`

But terraform breaks reading the statefile id of the resource:
Error: ID contained more segments than required

"id": "/subscriptions/56b8d631-XXXXX/resourceGroups/rg-name/providers/Microsoft.Web/sites/app-name/slots/primary/publicCertificates/CERTCA",

### New or Affected Resource(s)/Data Source(s)

azurerm_app_service_public_certificate_slots

**Comment by xiaxyi** [comment]
in backlog

**Comment by adamsba3** [comment]
Its in back log so closing issue, thank you
