### ISSUE TITLE
`azurerm_load_test` fails when updating with status 400

### ISSUE THREAD

**Issue by heoelri** [hashicorp/terraform-provider-azurerm#18185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_load_test

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "deployment" {
  name     = "${local.prefix}-loadtest-rg"
  location = var.location
  tags     = merge(local.default_tags, { "LastDeployedAt" = timestamp() })
}

resource "azurerm_load_test" "deployment" {
  name                = "${local.prefix}-azloadtest"
  resource_group_name = azurerm_resource_group.deployment.name
  location            = azurerm_resource_group.deployment.location

  tags = local.default_tags
}
```

### Debug Output/Panic Output

```shell
azurerm_resource_group.deployment: Modifying... [id=/subscriptions/cb8d2bb0-****-****-****-cde33c03****/resourceGroups/afe2e67b5-loadtest-rg]
azurerm_resource_group.deployment: Modifications complete after 0s [id=/subscriptions/cb8d2bb0-****-****-****-cde33c03****/resourceGroups/afe2e67b5-loadtest-rg]
azurerm_load_test.deployment: Modifying... [id=/subscriptions/cb8d2bb0-****-****-****-cde33c03****/resourceGroups/afe2e67b5-loadtest-rg/providers/Microsoft.LoadTestService/loadTests/afe2e67b5-azloadtest]
╷
│ Error: updating Load Test Load Test (Subscription: "cb8d2bb0-****-****-****-cde33c03****"
│ Resource Group Name: "afe2e67b5-loadtest-rg"
│ Load Test Name: "afe2e67b5-azloadtest"): loadtests.LoadTestsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidResource" Message="The resource definition is invalid."
│ 
│   with azurerm_load_test.deployment,
│   on main.tf line 24, in resource "azurerm_load_test" "deployment":
│   24: resource "azurerm_load_test" "deployment" {
│ 
│ updating Load Test Load Test (Subscription:
│ "cb8d2bb0-****-****-****-cde33c03****"
│ Resource Group Name: "afe2e67b5-loadtest-rg"
│ Load Test Name: "afe2e67b5-azloadtest"):
│ loadtests.LoadTestsClient#CreateOrUpdate: Failure responding to request:
│ StatusCode=400 -- Original Error: autorest/azure: Service returned an
│ error. Status=400 Code="InvalidResource" Message="The resource definition
│ is invalid."
```

### Expected Behaviour

Load Test service should get updated (or deployed).

### Actual Behaviour

Load Test service is not getting updated. Terraform apply fails.

**Comment by liuwuliuyun** [comment]
On of our test case failed with the same reason. I will check this issue lately.

------- Stdout: -------
=== RUN   TestAccLoadTest_update
=== PAUSE TestAccLoadTest_update
=== CONT  TestAccLoadTest_update
testcase.go:110: Step 3/4 error: Error running apply: exit status 1
Error: updating Load Test Load Test (Subscription: "*******"
Resource Group Name: "acctestRG-220830001031693791"
Load Test Name: "acctestALT-220830001031693791"): loadtests.LoadTestsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidResource" Message="The resource definition is invalid."
with azurerm_load_test.test,
on terraform_plugin_test.tf line 15, in resource "azurerm_load_test" "test":
15: resource "azurerm_load_test" "test" {
updating Load Test Load Test (Subscription:
"*******"
Resource Group Name: "acctestRG-220830001031693791"
Load Test Name: "acctestALT-220830001031693791"):
loadtests.LoadTestsClient#CreateOrUpdate: Failure responding to request:
StatusCode=400 -- Original Error: autorest/azure: Service returned an error.
Status=400 Code="InvalidResource" Message="The resource definition is
invalid."
--- FAIL: TestAccLoadTest_update (165.45s)
FAIL

**Comment by liuwuliuyun** [comment]
I have tested the latest API version (2022-04-15) and succeeds without 400 error. Upgrading the api version could be the solution to this issue.

**Comment by heoelri** [comment]
Thanks @liuwuliuyun / @tombuildsstuff the previous versions will soon be deprecated. I was asked to move to `2022-06-01-preview` by Sep 30, 2022.

**Comment by liuwuliuyun** [comment]
Hi @heoelri I saw an update has been made. Could you try again? Leave comments if you still have this problem, Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved. Terraform apply for azurerm_load_test works in 3.62.1 As such, I am going to mark this issue as closed, but if you run into this again with the latest Terraform and Provider versions, please feel free to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose). 🙂
