### ISSUE TITLE
Support for data source `azurerm_monitor_data_collection_rule`

### ISSUE THREAD

**Issue by nbjohnson** [hashicorp/terraform-provider-azurerm#18187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the upcoming addition of the resource `azurerm_monitor_data_collection_rule_association`, it would be nice to be able to quickly lookup the id of a data collection rule to do the association. Can a data source lookup for `azurerm_monitor_data_collection_rule` be added?

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### Potential Terraform Configuration

```hcl
data "azurerm_monitor_data_collection_rule" "example" {
  resource_group_name = "terraform-example-rg"
  name                = "tf-dcr"
}

output "data_collection_rule_id" {
  value = data.azurerm_monitor_data_collection_rule.example.id
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/17831

https://docs.microsoft.com/en-us/rest/api/monitor/data-collection-rules/get?tabs=HTTP

**Comment by teowa** [comment]
Hi @nbjohnson , thanks for submiting this. The data source `azurerm_monitor_data_collection_rule` is now under development.

**Comment by wingersg** [comment]
> Hi @nbjohnson , thanks for submiting this. The data source `azurerm_monitor_data_collection_rule` is now under development.

i see terraform documentation already has it: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_data_collection_rule#example-usage

**Comment by nbjohnson** [comment]
> > Hi @nbjohnson , thanks for submiting this. The data source `azurerm_monitor_data_collection_rule` is now under development.
> 
> i see terraform documentation already has it: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_data_collection_rule#example-usage

What you have linked is the Resource for the data collection rule which I am aware of, my request was for a Data Source to be able to lookup an existing data collection rule so it can be referenced in terraform
