### ISSUE TITLE
azurerm_automation_module can't import newer versions of default modules

### ISSUE THREAD

**Issue by prubis** [hashicorp/terraform-provider-azurerm#18198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

2.95.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_module

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_automation_account" "example" {
  name                = "account1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_module" "computer_management_dsc" {
  name                    = "ComputerManagementDsc"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name

  module_link {
    uri = "https://devopsgallerystorage.blob.core.windows.net/packages/computermanagementdsc.8.5.0.nupkg"
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_automation_module.computer_management_dsc: Creating...
Error: A resource with the ID "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/example-resources/providers/Microsoft.Automation/automationAccounts/account1/modules/ComputerManagementDsc" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_automation_module" for more information.
│ 
│   with azurerm_automation_module.automation_modules["ComputerManagementDsc"], on automation_account-modules.tf line 25, in resource "azurerm_automation_module" "computer_management_dsc":
│   25: resource "azurerm_automation_module" "computer_management_dsc" {
│ 
╵
```

### Expected Behaviour

The module should be able to be imported with the newer version ([the default supplied with Automation Accounts is (currently) 5.0.0.0](https://docs.microsoft.com/en-us/azure/automation/shared-resources/modules#default-modules)).

### Actual Behaviour

The module can't be imported, and there's no way to force it to import with a newer version. I suppose you *could* try to import the existing module and then set it to use a newer version, but that's not a very elegant solution.

### Steps to Reproduce

1. `terraform apply`

### References

https://docs.microsoft.com/en-us/azure/automation/shared-resources/modules#default-modules

**Comment by wuxu92** [comment]
Hi, @prubis thanks for your feedback. the azurerm version you used seems a little bit old, could you please have a try with the newest version (3.20.0) to see if this issue still exists?

**Comment by wuxu92** [comment]
@prubis you can create it with a new name but not `ComputerManagementDsc`, because `ComputerManagementDsc` is a built-in module existing under the automation account. 

or you can import this model first, and then do a `terraform apply` to update the module link like:

```
terraform import azurerm_automation_module.computer_management_dsc /subscriptions/{xxxx-xxxx-xxxx-xxxxx-xxxxxxx}/resourceGroups/{example-resources}providers/Microsoft.Automation/automationAccounts/account1/modules/ComputerManagementDsc

terraform apply # <- this will do an update on this module
```
then the module version should fit your expectation.

![image](https://user-images.githubusercontent.com/2633022/189283879-9c8a3026-25be-486a-b70c-fa4df6d2eba5.png)

**Comment by wuxu92** [comment]
@prubis en yes, I think you are right. I'll create a PR to work around this.
