### ISSUE TITLE
Standard_L16as_v3 SKU is not supported by TF azurerm provider versions

### ISSUE THREAD

**Issue by Zauberberg1** [hashicorp/terraform-provider-azurerm#18220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Standard_L16as_v3 SKU is not supported by azurerm provider versions. 
This is the SKU block from version 3.20 (latest). Standard_L16as_v3 is not there.
![image](https://user-images.githubusercontent.com/112560131/187962840-f4a0b91a-1900-4c38-a4a4-b220f2ad53f8.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_cluster

**Comment by caol-ila** [comment]
PR is already created
https://github.com/hashicorp/terraform-provider-azurerm/pull/18157

**Comment by liuwuliuyun** [comment]
We could close this issue since it has been fixed by my PR above.

**Comment by catriona-m** [comment]
Closing this issue as it has been fixed by #18425 . Thanks!
