### ISSUE TITLE
Error Creating Function App in Elastic SKU

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform-provider-azurerm#18236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

">=1.0"

### AzureRM Provider Version

">=3.0.0"

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "example" {
  name                = "example-app-service-plan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {}
}
```

### Debug Output/Panic Output

```shell
╷

│ Error: creating Linux Function App: (Site Name "XXXXX-dev-fn-linux-XXXXXX-XXX" / Resource Group "xx-xxx-x--xx-xxxx-xxx"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

│

│   with azurerm_linux_function_app.linux_function["fa1"],

│   on main.tf line 62, in resource "azurerm_linux_function_app" "linux_function":

│   62: resource "azurerm_linux_function_app" "linux_function" {
│
│ creating Linux Function App: (Site Name "plte-dev-fn-linux-azp-use2-06" /
│ Resource Group "ssc-ccoe-platengg-sub-dev-01-rg-use2-fn-06"):
│ web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 --
│ Original Error: autorest/azure: Service returned an error. Status=<nil>

│ <nil>
```

### Expected Behaviour

╷

│ Error: creating Linux Function App: (Site Name "XXXXX-dev-fn-linux-XXXXXX-XXX" / Resource Group "xx-xxx-x--xx-xxxx-xxx"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

│

│   with azurerm_linux_function_app.linux_function["fa1"],

│   on main.tf line 62, in resource "azurerm_linux_function_app" "linux_function":

│   62: resource "azurerm_linux_function_app" "linux_function" {
│
│ creating Linux Function App: (Site Name "plte-dev-fn-linux-azp-use2-06" /
│ Resource Group "ssc-ccoe-platengg-sub-dev-01-rg-use2-fn-06"):
│ web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 --
│ Original Error: autorest/azure: Service returned an error. Status=<nil>

│ <nil>

### Steps to Reproduce

terraform apply

**Comment by pinaki-accenture** [comment]
Hello @sahitya12,
I tried with attach sample['azurerm_service_plan' sku 'Y1'] and it worked fine.
[main.zip](https://github.com/hashicorp/terraform-provider-azurerm/files/9482429/main.zip)

![image](https://user-images.githubusercontent.com/93645031/188267707-4ebd0459-0fa6-4000-a7f1-56c8dfca693a.png)

**Comment by xiaxyi** [comment]
@sahitya12  Thanks for raising this issue, the Y1 plan works for me as well. Can you try using Azure portal to see if the function app can be created as expected?

**Comment by sahitya12** [comment]
@xiaxyi  Y1 is free plan it works but i tried with elastic premium EP1 making use of container image

**Comment by xiaxyi** [comment]
Thanks @sahitya12 for the response, can you confirm the behavior in azure portal? are you able to create the Linux function app using the same service plan via Azure portal or another tool such as Azure cli?

**Comment by xiaxyi** [comment]
@sahitya12 Can you try put `always_on` to `true` in the `site_config` and try again?

**Comment by sahitya12** [comment]
@xiaxyi i am trying to create brand new one , if i try to deploy with Y1 plan using below mcr image i am able to browse function page. i tried creating one more function using EP1 and also tried using P1v2 plan i am getting function runtime unreachable error post deployment 

registry_url  = "mcr.microsoft.com"
image_name  = "azure-functions/python"
image_tag   =   "4"

**Comment by sahitya12** [comment]
> ervice

correct for elastic premium plan i have made always_on to false

**Comment by xiaxyi** [comment]
Thanks for the response, can you call below api:
`https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx/config/web?api-version=2021-02-01` and let me know the value of `linuxFxVersion`?

**Comment by sahitya12** [comment]
linuxFxVersion value is DOCKER|[https://mcr.microsoft.com/azure-functions/python:4"](https://mcr.microsoft.com/azure-functions/python:4%22)

**Comment by xiaxyi** [comment]
Thanks, can you please set the linuxFxVersion to `DOCKER|mcr.microsoft.com/azure-functions/python:4` via api and see if the function app can be functioned as expected?

**Comment by xiaxyi** [comment]
@sahitya12 Can you share with me about some updates as I'm trying to identify if this "function not reachable" issue is related to the mentioned pr or not. Thanks in advance!
