### ISSUE TITLE
azurerm_container_registry does not support virtual_network anymore

### ISSUE THREAD

**Issue by chaoqi** [hashicorp/terraform-provider-azurerm#18232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.0

### Affected Resource(s)/Data Source(s)

3.21.0

### Terraform Configuration Files

```hcl
virtual_network block seems being removed from the network_rule_set... is there any resources to use instead?
```

### Debug Output/Panic Output

```shell
Error: Unsupported argument

  on ../../../../products/container-registry/terraform/acr.tf line 31, in resource "azurerm_container_registry" "acr":
  31:     virtual_network = length(var.networkACLs.subnetIds) > 0 ? [

An argument named "virtual_network" is not expected here.
```

### Expected Behaviour

Terraform should not break---

### Actual Behaviour

terraform breaks

**Comment by chaoqi** [comment]
it looks like this part of code is getting deleted via this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/17926

**Comment by katbyte** [comment]
Hey @chaoqi, really sorry that i missed this in my review of #17926, i've opened #18239 that backs out those changes - this will be released as part of a patch release later today
