### ISSUE TITLE
Unable to destroy azurerm_resource_group_template_deployment with nested resource despite the dependsOn element

### ISSUE THREAD

**Issue by bandarlogen** [hashicorp/terraform-provider-azurerm#18243]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_template_deployment

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "myTFResourceGroup"
  location = "westus2"
}

resource "azurerm_resource_group_template_deployment" "dicomservice" {
  count               = 1
  name                = "mytfdicomservice"
  resource_group_name = azurerm_resource_group.rg.name
  deployment_mode     = "Incremental"
  parameters_content = jsonencode({
    "healthdicomservicename" = {
      value = "mydicomservicename"
    },
    "healthworkspacename" = {
      value = "myhealthworkspacename"
    }
  })

  template_content = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "healthdicomservicename": {
      "type": "String",
      "defaultValue": ""
    },
    "healthworkspacename": {
      "type": "String",
      "defaultValue": ""
    }
  },
  "resources": [
    {
      "type": "Microsoft.HealthcareApis/workspaces",
      "apiVersion": "2022-06-01",
      "name": "[parameters('healthworkspacename')]",
      "location": "westus2"
    },
    {
      "type": "Microsoft.HealthcareApis/workspaces/dicomservices",
      "apiVersion": "2022-06-01",
      "name": "[concat(parameters('healthworkspacename'), '/', parameters('healthdicomservicename'))]",
      "location": "westus2",
      "dependsOn": [
        "[resourceId('Microsoft.HealthcareApis/workspaces', parameters('healthworkspacename'))]"
      ]
    }
  ]
}
TEMPLATE
}
```

### Debug Output/Panic Output

```shell
Error: removing items provisioned by this Template Deployment: deleting Nested Resource "/subscriptions/.../resourceGroups/myTFResourceGroup/providers/Microsoft.HealthcareApis/workspaces/myhealthworkspacename": resources.Client#DeleteByID: Failure sending request: StatusCode=409 -- Original Error: Code="CannotDeleteResource" Message="Can not delete resource before nested resources are deleted."
```

### Expected Behaviour

`terraform destroy` should destroy resources.

It seems that terraform doesn't recognize  the nested resource `dependsOn` element.

### Actual Behaviour

`terraform destroy` cannot destroy resources

### Steps to Reproduce

1. terraform apply
2. terrsform destroy

**Comment by ms-zhenhua** [comment]
Hi @bandarlogen, thank you for reporting this issue. I have created a [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/18319) to fix it.
