### ISSUE TITLE
azurerm_cdn_frontdoor_rule doesn't allow an empty 'destination_hostname' field

### ISSUE THREAD

**Issue by LWNetworks** [hashicorp/terraform-provider-azurerm#18249]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule" "rs-rules" {
  depends_on = [data.azurerm_cdn_frontdoor_profile.fd, azurerm_cdn_frontdoor_rule_set.rs] 

  name                      = "HttpHTTPSredirect"
  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.rs.id
  order                     = 1
  behavior_on_match         = "Continue"

  conditions {
    request_scheme_condition {
        match_values = [
            "HTTP"
        ]
    negate_condition = false
    operator = "Equal"
    }
  }
  actions {
    url_redirect_action {
        redirect_type        = "PermanentRedirect"
        redirect_protocol = "Https"
        destination_hostname = ""
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: expected "actions.0.url_redirect_action.0.destination_hostname" to not be an empty string, got 
│ 
│   with module.FrontDoor-Origins.azurerm_cdn_frontdoor_rule.rs-rules,
│   on ../Module/FrontDoor/OriginGroup/ruleset.tf line 27, in resource "azurerm_cdn_frontdoor_rule" "rs-rules":
│   27:         destination_hostname = "" 
│
```

### Expected Behaviour

![image](https://user-images.githubusercontent.com/103250538/188415519-185dc13c-839c-472e-90c5-fa3b46fa196c.png)
Creation of a rule that looks like the attached image.

### Actual Behaviour

Errors out in terraform apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/18010

**Comment by WodansSon** [comment]
@LWNetworks, thank you for reporting this issue. I have made a code change that will fix this issue in PR #18231 

<img width="852" alt="image" src="https://user-images.githubusercontent.com/20408400/188977580-cffed3f6-0b8f-472e-b57f-d19c90f38f7e.png">
