### ISSUE TITLE
Mistake in AzureRM provider docs for ARM_STORAGE_USE_AZUREAD

### ISSUE THREAD

**Issue by srgva** [hashicorp/terraform-provider-azurerm#18255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

v3.7.0

### Affected Resource(s)/Data Source(s)

AzureRM Provider

### Terraform Configuration Files

```hcl
According to the docs (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread), I use ARM_STORAGE_USE_AZUREAD=true to access a remote Azure backend via Azure AD rather then Shared Access Key.
```

### Debug Output/Panic Output

```shell
Key based authentication is not permitted on this storage account
```

### Expected Behaviour

The Terraform performs a successful initialization. However, if I set ARM_USE_AZUREAD=true instead of ARM_STORAGE_USE_AZUREAD, it works as expected. It seems to be a mistake in the Azure Provider docs.

**Comment by magodo** [comment]
@srgva Thank you for submitting this! Looking into the source code, the env var name is the same as in the doc: https://github.com/hashicorp/terraform-provider-azurerm/blob/2d18c62fe702bfa9eeb890bcbb7c5951ae3fe49f/internal/provider/provider.go#L237-L242

If you set the (non-existing) `ARM_USE_AZUREAD`, it should take no effect, which means `ARM_STORAGE_USE_AZUREAD` falls back to its default value: `false`.

Would you please double confrim your setup?

**Comment by tombuildsstuff** [comment]
@magodo FWIW this appears to be related to the Azure Backend rather than the Provider: https://www.terraform.io/language/settings/backends/azurerm - there's a separate flag in the backend block (`use_azuread_auth`) and/or a separate Environment Variable for this (`ARM_USE_AZUREAD`)

**Comment by srgva** [comment]
@tombuildsstuff Exactly! This has fully clarified my question! Thanks!
