### ISSUE TITLE
azurerm_storage_share_file returns error : "Provider produced inconsistent result after apply"

### ISSUE THREAD

**Issue by tamoLo** [hashicorp/terraform-provider-azurerm#18252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### AzureRM Provider Version

 3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_share_file

### Terraform Configuration Files

```hcl
resource "azurerm_storage_share" "appname_fileshare" {
  access_tier          = "TransactionOptimized"
  name                 = "appname"
  storage_account_name = var.storage_account_name
  quota                = 50
}

resource "azurerm_storage_share_file" "upload-package" {
  for_each         = fileset(path.module, "postinstall/package/*")
  name             = replace("${each.key}","postinstall/package/","")
  storage_share_id = azurerm_storage_share.appname_fileshare.id
  source           = "${path.module}/${each.key}"
}

resource "azurerm_storage_share_directory" "appname_fileshare_plugin" {
  name                 = "plugin"
  share_name           = azurerm_storage_share.appname_fileshare.name
  storage_account_name = var.storage_account_name
}

resource "azurerm_storage_share_file" "upload-package-plugin" {
  for_each         = fileset(path.module, "postinstall/package/plugin/*")
  name             = replace("${each.key}","postinstall/package/","")
  storage_share_id = azurerm_storage_share.appname_fileshare.id
  source           = "${path.module}/${each.key}"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_storage_share_file.upload-package-plugin["postinstall/package/plugin/test.tar.gz"], provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new
│ value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_storage_share_file.upload-package-plugin["postinstall/package/plugin/test1.zip"], provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value:
│ Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to azurerm_storage_share_file.upload-package-plugin["postinstall/package/plugin/test2.tar.gz"], provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new
│ value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

... etc for all files in postinstall/package/plugin/*
```

### Expected Behaviour

Abilitie to manage those fileshare's files with terraform.

### Actual Behaviour

All resources are created in azure but I can't use Terraform to managed all the azurerm_storage_share_file created after terraform apply so I need to import each.

### Steps to Reproduce

1. Using backend-config with privatised storage-account. This storage-account is the same as the one used in the configuration file below
2. Terraform apply

**Comment by magodo** [comment]
@tamoLo Thank you for submitting this! Would you please provide the debug log when the issue occurs so that we can check whether it is due to the same reason as: https://github.com/hashicorp/terraform-provider-azurerm/issues/15048

**Comment by tamoLo** [comment]
@magodo can this extract give you enough info ?

2022-09-06T11:24:06.439+0200 [INFO]  provider.terraform-provider-azurerm_v3.21.1_x5.exe: Retrieving Storage File Share file "*******" (Directory "/plugin" / File Share "*******" / Account "*******" / Resource Group "*******" ): files.Client#GetProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF: timestamp=2022-09-06T11:24:06.438+0200

**Comment by magodo** [comment]
@tamoLo It seems not the same as #15048, could you please provide the full debug log?
