### ISSUE TITLE
Support for associating a Application Gateway WAF policy to an Application Gateway Listener and Route Path

### ISSUE THREAD

**Issue by nmiddleton** [hashicorp/terraform-provider-azurerm#18254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an application gateway WAF policy in Azure Portal, you can choose to associate one or more application gateways and/or HTTP listeners and route paths with the policy you are creating. 
Using terraform there IS a way to associate an Application Gateway WAF policy with the application gateway by using the `firewall_policy_id` on the App Gateway. 
However, there is no way to associate an Application Gateway WAF policy with a HTTP LISTENER nor the ROUTE PATH in the application gateway via terraform.

https://docs.microsoft.com/en-us/azure/web-application-firewall/ag/create-waf-policy-ag#create-a-policy

### New or Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy_application_gateway_listener_association, azurerm_web_application_firewall_policy_application_gateway_listener_routepath_association

### Potential Terraform Configuration

```hcl
resource "azurerm_web_application_firewall_policy_application_gateway_listener_association" "example" {
  association_type        = "ApplicationGatewayListener"
  waf_policy_id           = azurerm_web_application_firewall_policy.example.id
  application_gateway_id  = azurerm_application_gateway.example.id
  http_listener_name      = "http_listener_example"
}
resource "azurerm_web_application_firewall_policy_application_gateway_listener_routepath_association" "example" {
  association_type        = "ApplicationGatewayListenerRoutePath"
  waf_policy_id           = azurerm_web_application_firewall_policy.example.id
  application_gateway_id  = azurerm_application_gateway.example.id
  http_listener_name      = "http_listener_example"
  routing_rule            = "routing_rule_example"
}
```

**Comment by ms-zhenhua** [comment]
Hi @nmiddleton, thank you for reaching out.
`azurerm_application_gateway` has 3 firewall_policy_id(s). Could you kindly help confirm whether [firewall_policy_id in http_listener](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#ssl_certificate_name) and  [firewall_policy_id  in path_rule](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#rewrite_rule_set_name) are what you are looking for? Thanks.

**Comment by nmiddleton** [comment]
thank you, but it does not make it very easy to handle it from the listener property of App Gw when, in the portal, it is an association made from the policy blades.
Everything else on a listener (and a path_rule) is a name, not an ID. This is great because my listeners are numerous and delivered via dynamic. The listener is supplied in config e.g.
tfvars:
-----
```
appgw_listeners = [
  {
    name                 = "listener1"
    frontend_port_name   = "feipport_443"
    host_name            = "example.host.com"
    protocol             = "Https"
    require_sni          = true
    ssl_certificate_name = "example_cert_name"
  },  {
    name                 = "listener2" ...
]
```
------
within the app Gateway resource tf...
```
resource "azurerm_application_gateway" "product_appgw_v2" {
...
dynamic "http_listener" {
    for_each = var.appgw_listeners
    content {
      name                           = http_listener.value.name
      frontend_port_name             = http_listener.value.frontend_port_name
      host_name                      = http_listener.value.host_name
      frontend_ip_configuration_name = "feip"
      protocol                       = http_listener.value.protocol
      require_sni                    = http_listener.value.require_sni
      ssl_certificate_name           = http_listener.value.ssl_certificate_name
      firewall_policy_id             = ???
    }
```
For the firewall policy to work like the other variables on listener it would have to be firewall_policy_name? Or a separate association (which is what I was thinking). Unless you can suggest how I should be making this work?

**Comment by ms-zhenhua** [comment]
Hi @nmiddleton, 
all `firewall_policy_id`(s) should be a policy id. You could first define a `azurerm_web_application_firewall_policy` resource, then assign its ID to the `firewall_policy_id`. It may look like:
`firewall_policy_id  = azurerm_web_application_firewall_policy.xxx.id`
Hope it can help you.

**Comment by nmiddleton** [comment]
thankyou for responding @ms-zhenhua 
Sure, I understand how it is configured. I have 11x `azurerm_web_application_firewall_policy` defined and waiting for use. These 11 different policies need to be associated with many and various of the 78 listeners on the app Gateway. Across the for-each of the 78 listeners, what you suggest will mean that all of my listeners would only be configured with the same single policy. 
What it is forcing me to do is to have 11 dynamic http_listener stanzas on my AppGW, one for each WAF policy id. And then manage 11 different arrays of the listeners to apply to them. I hope you can see how ugly and fragile that gets at scale. 

One other side-effect of this implementation can be seen if you try to change the name of a previously associated policy. terraform is unable to destroy it in order to recreate it. An association\binding would also support this behaviour I feel.
