### ISSUE TITLE
Kusto property allowed_ip_ranges not applied

### ISSUE THREAD

**Issue by hitty5** [hashicorp/terraform-provider-azurerm#18250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kusto_cluster" "example" {
  name                = "dectest"
  location            = var.region.location.name
  resource_group_name = azurerm_resource_group.core.name

  sku {
    name     = "Standard_D13_v2"
    capacity = 2
  }

  public_network_access_enabled = false
  allowed_ip_ranges = [
    "194.96.47.80"
  ]
  tags = {
    Environment = "test"
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_kusto_cluster.example will be created
  + resource "azurerm_kusto_cluster" "example" {
      + allowed_ip_ranges                  = [
          + "194.96.47.80"
        ]
      + auto_stop_enabled                  = true
      + data_ingestion_uri                 = (known after apply)
      + disk_encryption_enabled            = false
      + engine                             = "V2"
      + id                                 = (known after apply)
      + location                           = "westeurope"
      + name                               = "dectest"
      + outbound_network_access_restricted = false
      + public_ip_type                     = "IPv4"
      + public_network_access_enabled      = false
      + purge_enabled                      = false
      + resource_group_name                = "rg-core-network-qa-weu"
      + streaming_ingestion_enabled        = false
      + tags                               = {
          + "Environment" = "test"
        }
      + trusted_external_tenants           = (known after apply)
      + uri                                = (known after apply)

      + sku {
          + capacity = 2
          + name     = "Standard_D13_v2"
        }
    }
```

### Expected Behaviour

The cluster created with "public_network_access_enabled" set to "false" and the provided "allowed_ip_ranges" list.

### Actual Behaviour

The cluster is set to "false" for "public_network_access_enabled", but no allowed IP entries set.

![Screenshot 2022-09-05 135155](https://user-images.githubusercontent.com/208332/188442621-e9559b8a-953b-4bcf-b99b-a679ac7d90d4.png)

### Steps to Reproduce

1. terraform apply with the provided kusto resource

**Comment by liuwuliuyun** [comment]
Hi @hitty5 , when you set public_network_access_enabled to false, only private endpoints could access this cluster.

**Comment by liuwuliuyun** [comment]
I have tested following config and it works.

terraform{
    required_providers {
      azurerm = {
        source  = "hashicorp/azurerm"
      }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "yunliutest2" {
  name      = "yunliutest111"
  location  = "eastus2"
}

resource "azurerm_kusto_cluster" "name" {
  name = "yunliukustocluster22"
  resource_group_name = azurerm_resource_group.yunliutest2.name
  location = azurerm_resource_group.yunliutest2.location
  sku {
    name = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }
  public_network_access_enabled = true
  allowed_ip_ranges = [
    "192.168.47.80"
  ]
}

**Comment by hitty5** [comment]
Yes right, the "publicNetworkAccess" property must set to "Enabled" and the restrict the access by listing the allowed IP addresses with "allowedIpRangeList". The misleading part here, you can disallow public network access, but allowed IP addresses can still be listed, see:

`{
  "acceptedAudiences": [],
  "allowedFqdnList": [],
  "allowedIpRangeList": [
    "192.168.47.80"
  ],
  "dataIngestionUri": "https://ingest-yunliukustocluster22.eastus2.kusto.windows.net",
  "enableAutoStop": true,
  "enableDiskEncryption": false,
  "enableDoubleEncryption": false,
  "enablePurge": false,
  "enableStreamingIngest": false,
  "engineType": "V2",
  "etag": "\"2022-09-06T06:20:43.6905856Z\"",
  "id": "/subscriptions/b66ed6d1-a1ed-4be1-8375-17313241c26c/resourceGroups/yunliutest111/providers/Microsoft.Kusto/Clusters/yunliukustocluster22",
  "identity": {
    "principalId": null,
    "tenantId": "0ae51e19-07c8-4e4b-bb6d-648ee58410f4",
    "type": "None",
    "userAssignedIdentities": null
  },
  "keyVaultProperties": null,
  "languageExtensions": {
    "value": []
  },
  "location": "East US 2",
  "name": "yunliukustocluster22",
  "optimizedAutoscale": null,
  "privateEndpointConnections": [],
  "provisioningState": "Succeeded",
  "publicIpType": "IPv4",
  "publicNetworkAccess": "Disabled",
  "resourceGroup": "yunliutest111",
  "restrictOutboundNetworkAccess": "Disabled",
  "sku": {
    "capacity": 1,
    "name": "Dev(No SLA)_Standard_D11_v2",
    "tier": "Basic"
  },
  "state": "Running",
  "stateReason": null,
  "systemData": null,
  "tags": {},
  "trustedExternalTenants": [],
  "type": "Microsoft.Kusto/Clusters",
  "uri": "https://yunliukustocluster22.eastus2.kusto.windows.net",
  "virtualClusterGraduationProperties": null,
  "virtualNetworkConfiguration": null,
  "zones": null
}`

However, the issue is solved.
