### ISSUE TITLE
Support for Node.js 18 in Azure Functions azurerm_linux_function_app

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#18259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Functions support for Node.js 18 is now available. This version of Node.js is supported by Functions runtime v4.x
Node.js 18 is currently in the initial release stage.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    application_stack {
      node_version = "18"
    }
}
```

### References

https://azure.microsoft.com/en-us/updates/public-preview-nodejs-18-in-azure-functions/

**Comment by kasattejaswi** [comment]
Raised a PR to implement this issue: https://github.com/hashicorp/terraform-provider-azurerm/pull/18283

**Comment by jbinko** [comment]
@katbyte I think this can be closed
