### ISSUE TITLE
Webhook not triggered when uri provided

### ISSUE THREAD

**Issue by YohanValette-DXC** [hashicorp/terraform-provider-azurerm#18269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_automation_webhook

### Terraform Configuration Files

```hcl
resource "azurerm_automation_webhook" "items" {
  for_each = var.webhooks

  name                    = each.value.name
  resource_group_name     = local.automation_account_rg_name
  automation_account_name = local.automation_account_name
  expiry_time             = each.value.expiry_time
  enabled                 = each.value.enabled
  runbook_name            = azurerm_automation_runbook.items[each.value.runbook_key].name
  uri                     = each.value.uri
  parameters              = each.value.parameters
}
```

### Debug Output/Panic Output

```shell
There is no error output
```

### Expected Behaviour

A POST request on the provided `uri` triggers the runbook

### Actual Behaviour

The runbook is not triggered. The POST request response is `404 Not found`.

### Steps to Reproduce

curl -X POST -H "Content-Type: application/json" --data-urlencode "body@webhook.json" ${webhook_uri} -v

* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 404 
< content-length: 0
< content-type: text/plain; charset=utf-8
< server: Microsoft-HTTPAPI/2.0
< date: Tue, 06 Sep 2022 13:48:57 GMT

### References

The code seems to store the provided uri in a variable, but do not actually use it in the resource parameters:

https://github.com/hashicorp/terraform-provider-azurerm/blob/0c087ce376811590a273478dd0892aac86d75f47/internal/services/automation/automation_webhook.go#L144

**Comment by wuxu92** [comment]
Hi @YohanValette-DXC thanks for your feedback, and if it's possible to share the URI provided to this webhook?

**Comment by YohanValette-DXC** [comment]
@wuxu92 as you know this is sensitive data and cannot be reproduced here.

The uri is generated through the API as recommended in the resource documentation: https://docs.microsoft.com/en-us/rest/api/automation/webhook/generate-uri?tabs=HTTP

**Comment by wuxu92** [comment]
reasonable.  as you have seen in the code, azurerm will generate the URI automatically if `uri` is not provided, so is it work as expected if do not provide the `uri` argument?

**Comment by YohanValette-DXC** [comment]
Yes, it works like a charm (I was able to write down the uri to a file with `local_file` to retrieve it) when the URI is not provided, but it does not when we provide the URI.
