### ISSUE TITLE
Support for publicNetworkAccess on Azure Sites i.e. Function App and App Service

### ISSUE THREAD

**Issue by rdbartram** [hashicorp/terraform-provider-azurerm#18272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support publicNetworkAccess property on all site types, this is app service and function for both linux and windows with the slots too. Could function similar to public_network_access_enabled property already present on other resource types.

### New or Affected Resource(s)/Data Source(s)

azurerm_(linux|windows)_(function|web)_app(_slot)?

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  public_network_access_enabled = false

  site_config {}
}
```

### References

https://docs.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-arm-template#siteproperties-1

**Comment by kantegajorgen** [comment]
In the mean time, this will solve the problem (by using the azapi-provider and a linux app in this example):

```
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
      version = "1.0.0"
    }
  }
}

provider "azapi" {
  # Configuration options
}

resource "azapi_update_resource" "example" {
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = azurerm_linux_function_app.example.name
  parent_id = azurerm_resource_group.example.id
  body = jsonencode({
    properties = {
      publicNetworkAccess = "Enabled"
    }
  })
  depends_on = [
    azurerm_linux_function_app.example
  ]
}
```

**Comment by Tafikay** [comment]
@kantegajorgen I have noticed that your given workaround no longer works once the ip_restriction/scm_ip_restriction within site_config changes after this code has been pushed, is that possible?

**Comment by farouqy** [comment]
> @kantegajorgen I have noticed that your given workaround no longer works once the ip_restriction/scm_ip_restriction within site_config changes after this code has been pushed, is that possible?

You can try this, it will force the update if any changes occur on the azurerm_linux_function_app.example :
`resource "azapi_update_resource" "example" {
  type      = "Microsoft.Web/sites@2022-03-01"
  name      = azurerm_linux_function_app.example.name
  parent_id = azurerm_resource_group.example.id
  body = jsonencode({
    properties = {
      publicNetworkAccess = "Enabled"
    }
  })
  lifecycle {
    replace_triggered_by = [
      azurerm_linux_function_app.example
    ]
  }
}`
