### ISSUE TITLE
Add the property 'hybrid_registration_url' property to 'azurerm_automation_account' resource and data

### ISSUE THREAD

**Issue by harcamSpark** [hashicorp/terraform-provider-azurerm#18277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Now that the resources for azurerm_automation_hybrid_runbook_worker and azurerm_automation_hybrid_runbook_worker_group have been added to azurerm provider, it would be handy to have the hybrid registration url as a property from the azurerm_automation_account to use to install the VM extension.

Currently I have a workaround of mangling the DSC endpoint URL with some replace()s, like so : 
```
locals {
  hybrid_url = replace("${azurerm_automation_account.example.dsc_server_endpoint}", ".agentsvc.", ".jrds.")
  hybrid_url2 = replace("${local.hybrid_url}", "/\\/accounts\\//", "/automationAccounts/")
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_automation_account

### Potential Terraform Configuration

```hcl
resource "azurerm_automation_account" "example-aa" {
  name                = "aa-example"
  location            = "australiaeast"
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_hybrid_runbook_worker_group" "example-hrwg" {...}
resource "azurerm_automation_hybrid_runbook_worker" "example-hrw" {...}

resource "azurerm_virtual_machine_extension" "hwge-registration" {
  name                 = "${azurerm_automation_account.example-aa.name}-hybridworkerextension"
  virtual_machine_id   = "${azurerm_windows_virtual_machine.example-vm.id}"
  publisher            = "Microsoft.Azure.Automation.HybridWorker"
  type                 = "HybridWorkerForWindows"
  type_handler_version = "0.1"

  settings = <<-EOF
    {
      "AutomationAccountURL" : "${azurerm_automation_account.example-aa.hybrid_registration_url}"
    }
  EOF
}
```

**Comment by wuxu92** [comment]
Hi, @harcamSpark thanks for your feedback. do you have any documents about this `hybrid_registration_url` property? so we can add this property then. I mean is there a document about this compute logic:


```tf
  hybrid_url = replace("${azurerm_automation_account.example.dsc_server_endpoint}", ".agentsvc.", ".jrds.")
  hybrid_url2 = replace("${local.hybrid_url}", "/\\/accounts\\//", "/automationAccounts/")
```

**Comment by harcamSpark** [comment]
That compute logic of the hybrid_url and hybrid_url2, there is no documentation for, that was my own custom workaround to get a hyrid registration url, cause it seems to always use the same uuid as the DSC endpoint, just with different bits in the URI around it.

As for documentation of the hybrid_registration_url itself, it seems to already be in the [go-azure-sdk](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/hashicorp/go-azure-sdk/resource-manager/automation/2021-06-22/automationaccount/model_automationaccountproperties.go#L13) I think?

**Comment by harcamSpark** [comment]
Or did you mean the REST API docs, in which case it's this [one here](https://docs.microsoft.com/en-us/rest/api/automation/automation-account/get?tabs=HTTP#automationaccount) - the "properties.automationHybridServiceURL"  property

**Comment by wuxu92** [comment]
it looks like not an officially supported property in the automation account. so it's a bit confusing for `azurerm` to support it by hardcoding this logic.

**Comment by harcamSpark** [comment]
sorry, I think you might be misunderstanding... the "hybrid_url" logic I mentioned as a workaround, is just that, not official. I use the "dsc_endpoint" property and do a couple of replace functions on it using locals in terraform code, as a stand-in until the hybrid_registration_url property is added to azurerm. I'm not saying we should add that code to azurerm.

The hybrid_registration_url property on the automation account looks to me like it's an official property though - it's in the response when I do a manual 'az rest' command and query the Azure Management API: 

`az rest -m GET -u 'https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Automation/automationAccounts/{automationAccountName}?api-version=2021-06-22'`

**Comment by wuxu92** [comment]
thanks for your explanation. now I got your point. this property comes in the version `2021-06-22` and I'll  raise a pull request to add this property.

**Comment by harcamSpark** [comment]
dang that was fast dude, nice work :-)
