### ISSUE TITLE
How to add Tunnel type while creating VPN Gateway, In documentation I dont find that argument

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#18289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_vpn_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway" "vpn-gw" {
  name = "test"
  location = azurerm_resource_group.rg[0].location
  resource_group_name = azurerm_resource_group.rg[0].name
  type = "Vpn"
  vpn_type = "RouteBased"
  active_active = true
  enable_bgp = false
  sku = "VpnGw1AZ"
  ip_configuration {
    name = "vnetGatewayConfig"
    public_ip_address_id = azurerm_public_ip.vpn-gateway-ip.id    
    private_ip_address_allocation = "Dynamic"
    subnet_id = data.azurerm_subnet.gatewaysubnetdata.id
  }
  ip_configuration {
    name = "vnetGatewayConfig1"
    public_ip_address_id = azurerm_public_ip.vpn-gateway-ip-secondary.id
    private_ip_address_allocation = "Dynamic"
    subnet_id = data.azurerm_subnet.gatewaysubnetdata.id
  }
  ip_configuration {
    name = "vnetGatewayConfig2"
    public_ip_address_id = azurerm_public_ip.vpn-gateway-ip-vpn.id
    private_ip_address_allocation = "Dynamic"
    subnet_id = data.azurerm_subnet.gatewaysubnetdata.id
  }
  vpn_client_configuration {
    address_space = ["xx.xxx.x.x/xx"]
    vpn_auth_types = ["AAD"]
    aad_tenant = "https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    #aad_audience = "41b23e61-6c1e-4545-b367-cd054e0ed4b4"
    aad_issuer = "https://sts.windows.net/xxxxxxxxxxxxxxxxxxxxxxxx/"
  }
}
```

### Debug Output/Panic Output

```shell
it created vpn but with tunnel type as IKE/OpenVPNssl, I want only Open VPN SSL
```

### Expected Behaviour

VPN gateway should be created with Open VPN SSL as tunnel type

### Actual Behaviour

VPN gateway created with tunnel type as IKE and Open VPN

### Steps to Reproduce

terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Hopes this [vpn_client_protocols](https://registry.terraform.io/providers/hashicorp/azurerm/2.55.0/docs/resources/virtual_network_gateway#vpn_client_protocols) property is helpful.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
