### ISSUE TITLE
Azure windows webapp + vnet : Provider produced an unexpected new value during refresh

### ISSUE THREAD

**Issue by homergsimpson** [hashicorp/terraform-provider-azurerm#18288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_virtual_network_swift_connection" "fa_vnet" {
  app_service_id = azurerm_windows_web_app.main_webapp[0].id
  subnet_id = var.subnet_id
}
```

### Debug Output/Panic Output

```shell
~ resource "azurerm_windows_web_app" "main_webapp" {
        id                                = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx"
        name                              = "staging-pbu-test-webapp-webapp"
        tags                              = {
            "xxx"  = "xxx"
        }
      - virtual_network_subnet_id         = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Network/virtualNetworks/xxx/subnets/xxx" -> null



"id":"/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Web/sites/xxxx/config/metadata","name":"metadata","type":"Microsoft.Web/sites/config","location":"West Europe","tags":{"xxxx":"xxxx"},"properties":{"xxxx":"xxxx"}}: timestamp=2022-09-07T11:33:53.983+0200
2022-09-07T11:33:53.989+0200 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an unexpected new value for xxxx during refresh.
- .virtual_network_subnet_id: was cty.StringVal(""), but now cty.StringVal("/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.Network/virtualNetworks/xxxx/subnets/xxxx")
```

### Expected Behaviour

Vnet integration configured for webapp

### Actual Behaviour

After creation, vnet integration is correctly configured, but, on each plan / apply vnet integration disappear or appear depending on the state

**Comment by xiaxyi** [comment]
Thanks @homergsimpson for raising this issue, I can reproduce it from my end as well. Let me check the functionality and the provider source code, will submit a pr for fix once confirmed the cause. Feel free to let me know if you would like to share more backgrounds with me.

**Comment by IronMania** [comment]
could it be, that this problem also occurs with `azurerm_windows_function_app` ?

**Comment by ondrejvaclavu** [comment]
same issue here - azurerm_windows_web_app

**Comment by xiaxyi** [comment]
Thanks guys for checking this issue, you may track the status in the mentioned pr.

**Comment by xiaxyi** [comment]
Hi Guys, a little update here. We may not be able to make the changes in the provider code as the property can be managed via two methods and it's difficult to get and check the status. 

it's better to use the ignore change for this property in web app resource if you are using `azurerm_app_service_virtual_network_swift_connection` to manage it.
```
lifecycle {
    ignore_changes = [virtual_network_subnet_id]
  }
```

**Comment by peterprumbach-telekom** [comment]
@xiaxyi Thank you for this solution. However, the documentation is not very clear. It is clear that both options cannot be used simultaneously. However, a reference to the workaround with the ignore_changes is missing.

**Comment by xiaxyi** [comment]
> @xiaxyi Thank you for this solution. However, the documentation is not very clear. It is clear that both options cannot be used simultaneously. However, a reference to the workaround with the ignore_changes is missing.

the notes are added in the pr https://github.com/hashicorp/terraform-provider-azurerm/pull/18738
