### ISSUE TITLE
azurerm_linux_web_app fails to create a web app because the azurerm_service_plan seems not getting properly created

### ISSUE THREAD

**Issue by Vinayak014** [hashicorp/terraform-provider-azurerm#18294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note
* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I have the exact same issue as the below issue except I am using Azure Web App. 

https://github.com/hashicorp/terraform-provider-azurerm/issues/16936

Is this fixed for Azure Web App? 

### Terraform Version

1.2.8

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      version = "3.21.1"
    }
  }
}
provider "azurerm" {
  features{}
}

resource "azurerm_resource_group" "example" {
  name     = "test"
  location = "westeurope"
}

resource "azurerm_service_plan" "appserviceplan" {
  name                = "${azurerm_resource_group.example.name}-plan"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  os_type             = "Linux"
  sku_name            = "S1"
	
}


resource "azurerm_linux_web_app" "dockerapp" {
  name                = "${azurerm_resource_group.example.name}-dockerapp"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  service_plan_id     = "${azurerm_service_plan.appserviceplan.id}"

   site_config {
    always_on      = "true"
    application_stack {
      docker_image = "DOCKER|prom/blackbox-exporter"
	  docker_image_tag = ""
    }
  }
}
```

### Debug Output/Panic Output

```shell
creating Linux Web App: (Site Name "test-dockerapp" / Resource Group "test"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter LinuxFxVersion has an invalid value." Details=[{"Message":"The parameter LinuxFxVersion has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["LinuxFxVersion"]}}]
│
│   with azurerm_linux_web_app.dockerapp,
│   on main.tf line 30, in resource "azurerm_linux_web_app" "dockerapp":
│   30: resource "azurerm_linux_web_app" "dockerapp" {
│
│ creating Linux Web App: (Site Name "test-dockerapp" / Resource Group "test"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error:
│ Code="BadRequest" Message="The parameter LinuxFxVersion has an invalid value." Details=[{"Message":"The parameter LinuxFxVersion has an invalid
│ value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an invalid
│ value.","Parameters":["LinuxFxVersion"]}}]
```

### Expected Behaviour

The Web App should have been created. A Web App needs an App Service Plan (ASP) to run. By creating an ASP with the new azurerm_service_plan resource type, you cannot set the following attributes:
kind = "Linux"
reserved = true
as their values will be "decided automatically" once the resource gets created. (Can't configure a value for "kind/reserved": its value will be decided automatically based on the result of applying this configuration. That is the error that throws when you try to set those values in the new azurerm_service_plan resource type version).

### Actual Behaviour

The Web App does not get created. When you check the JSON of the ASP directly in the Azure Portal, the "reserved" attribute is set to true, but that does not make any change, it still fails to create the Web App. Moreover, when creating a Web App manually from the portal with the same configurations, it works, JSONs are practically identical.

### References

#16936

**Comment by xiaxyi** [comment]
Thanks @Vinayak014 for raising this issue, can you let me know the value of linuxFxVersion? Are you using any docker regisrty?

**Comment by Vinayak014** [comment]
Hi Team, 

Is there any update?

Thank you,

**Comment by xiaxyi** [comment]
@Vinayak014 for docker image, please only fill the image name such as testimage. The DOCKER part is calculated by TF and will be put as the value if linuxFxVersion.

**Comment by Vinayak014** [comment]
Thank you @xiaxyi. It is working now.

**Comment by heoelri** [comment]
What is the correct syntax when pulling images from dockerhub? I'm using:

```hcl
  site_config {
    application_stack {
      docker_image     = "heoelri/simple-oidc-app"
      docker_image_tag = "v1"
    }
  }
```

But this is still generating an error message:

```console
creating Linux Web App: (Site Name "paean-oidc-webapp" / Resource Group "paean-oidc-rg"):     
│ web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error:     
│ Code="BadRequest" Message="The parameter LinuxFxVersion has an invalid value."
│ Details=[{"Message":"The parameter LinuxFxVersion has an invalid
│ value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The
│ parameter LinuxFxVersion has an invalid value.","MessageTemplate":"The parameter {0} has an   
│ invalid value.","Parameters":["LinuxFxVersion"]}}]
```
