### ISSUE TITLE
azurerm_backup_policy_vm_workload sql_compression_enabled isn't expected here

### ISSUE THREAD

**Issue by andrew-flatters-bliss** [hashicorp/terraform-provider-azurerm#18300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Attempting to setup `azurerm_backup_policy_vm_workload` following the example on the terraform documentation at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/backup_policy_vm_workload throws a error of 

> │   on main.tf line 453, in resource "azurerm_backup_policy_vm_workload" "backup_policy_vm_workload":
│  453:     sql_compression_enabled = false

This seems to be a feature that isn't within the module 

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_backup_policy_vm_workload 

### Terraform Configuration Files

```hcl
resource "azurerm_backup_policy_vm_workload" "backup_policy_vm_workload" {
  name                = "rsvpw-${var.client}-${var.appname}-${terraform.workspace}-${var.locationcode}-001"
  resource_group_name = azurerm_resource_group.rg.name
  recovery_vault_name = azurerm_recovery_services_vault.recovery_services_vault.name
  workload_type = "SQLDataBase"

  settings {
    time_zone               = "UTC"
    compression_enabled     = true
  }

  protection_policy {
    policy_type = "Full"

    backup {
      frequency = "Daily"
      time      = "15:00"
    }

    retention_daily {
      count = 8
    }
  }
}
```

### Debug Output/Panic Output

```shell
│   on main.tf line 453, in resource "azurerm_backup_policy_vm_workload" "backup_policy_vm_workload":
│  453:     sql_compression_enabled = false
```

**Comment by andrew-flatters-bliss** [comment]
Fixed in pull request https://github.com/hashicorp/terraform-provider-azurerm/pull/18301

**Comment by Amier3** [comment]
@andrew-flatters-bliss 

Thanks for the quick fix!

**Comment by andrew-flatters-bliss** [comment]
@Amier3 no problem spent a extra 5 mins scratching my head than it was worth so worth someone else saving them mins!
