### ISSUE TITLE
azurerm_monitor_private_link_scoped_service does not support linked_resource_id of data_collection_endpoint

### ISSUE THREAD

**Issue by sanderrhorst** [hashicorp/terraform-provider-azurerm#18307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.3

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_monitor_private_link_scoped_service

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_data_collection_endpoint" "dce_shared" {
  name                          = "dce-shared"
  resource_group_name           = azurerm_resource_group.rg-monitoring-shared.name
  location                      = azurerm_resource_group.rg-monitoring-shared.location
  public_network_access_enabled = false
  tags                          = local.global-tags
}

resource "azurerm_monitor_private_link_scope" "integratie" {
  name                = "integratie-ampls"
  resource_group_name = azurerm_resource_group.rg-monitoring-shared.name
  tags                = local.global-tags
}

resource "azurerm_monitor_private_link_scoped_service" "dce_shared" {
  name                = "dce-shared"
  resource_group_name = azurerm_resource_group.rg-monitoring-shared.name
  scope_name          = azurerm_monitor_private_link_scope.integratie.name
  # linked_resource_id  = azurerm_monitor_data_collection_endpoint.dce_shared.id
}
```

### Debug Output/Panic Output

```shell
│ Error: ID was missing the `components` element
│ Error: parsing "/subscriptions/***-***-***-***-***/resourceGroups/rg-monitoring-shared/providers/microsoft.insights/datacollectionendpoints/dce-shared": parsing segment "staticMicrosoftOperationalInsights": expected the segment "microsoft.insights" to be "Microsoft.OperationalInsights"
```

### Expected Behaviour

The data collection endpoint (DCE) should be added to the Azure Monitor Resources wihtin the Azure Monitor Private Link Scope

### Actual Behaviour

Terraform trows error that the linkedResourceId cannot be parsed. It is expecting the resourceId of Log Analytics Workspace or the Application Insights component as described on https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_private_link_scoped_service#arguments-reference in the linked_resource_id arguments reference

**Comment by ms-zhenhua** [comment]
Hi @sanderrhorst, thank you for reaching out. I created [this PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/18356) to support the DCE.
