### ISSUE TITLE
TDE key creation for the primary and secondary not working

### ISSUE THREAD

**Issue by HanamantSMalakagond** [hashicorp/terraform-provider-azurerm#18349]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server_transparent_data_encryption

### Terraform Configuration Files

```hcl
---------------main.tf file--------------------------------------
module "tde_key_primary" {

  source                    = "dir"
  keyvault_name             = var.app_root_key_vault_name
  resource_group            = RG-NAME
  tde_key_name              = var.tde_key_name
  server_id                 = SQLSERVERID
}
-----------------------tde.tf file ---------------------------------
data "azurerm_key_vault" "root_keyvault" {
  name                = var.keyvault_name
  resource_group_name = var.resource_group
}


data "azurerm_key_vault_key" "tde_key" {
  key_vault_id = data.azurerm_key_vault.root_keyvault.id
  name         = var.tde_key_name
}

resource "azurerm_mssql_server_transparent_data_encryption" "tde-key-new" {
  server_id        = var.server_id
  key_vault_key_id = data.azurerm_key_vault_key.tde_key.id
}
```

### Debug Output/Panic Output

```shell
module.tde_key_primary.data.azurerm_key_vault_key.tde_key: Read complete after 0s [value]
```

### Expected Behaviour

The TDE keys for both the primary and secondary should create without running multiple times for scenario adding dependency on primary and secondary. The TDE keys should be created for scenario when no dependency added in between the primary and secondary.

### Actual Behaviour

The TDE keys were not created.

### Steps to Reproduce

Steps to reproduce - >
1> Create Primary and secondary SQL servers
2> For SQL server managed identity provide the [Get, Wrap key, Unwrap key] permissions
3> While creating TDE key, The TDE key for secondary server is created and primary missing. The status is still showing (Service-managed key) - But if we see the logs the keyault key is read properly(module.tde_key_primary.data.azurerm_key_vault_key.tde_key: Read complete after 0s) but when I check the terraform state file the Keyvault key is empty for primary environment.
4> If I re-run the provisioning second time it will create the TDE key for primary also.

I tried above scenario by adding dependency from primary to secondary and vice versa. On first run the TDE keys were not created for both the servers. If we don't add dependency both the TDE keys were not generated.

### Important Factoids

Nothing

### References

Not sure

**Comment by aristosvo** [comment]
Hi @HanamantSMalakagond ! 

Based on the docs I would recommend to add the key to the secondary first, than on the primary. It may require a dependency of the primary TDE on the secondary TDE.

[Docs](https://learn.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-byok-overview?view=azuresql#geo-dr-and-customer-managed-tde):

> Both initial setup and rotation of the TDE protector must be done on the secondary first, and then on primary.

Does this explain your findings and help you solve this issue?

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed and @aristosvo has not gotten a response on if the suggestion helped with the issue. I am going to mark this as closed. If this is still an issue with the provider please do let us know by opening a new issue, thanks!
