### ISSUE TITLE
Support for bi-directional sync for Microsoft Defender for Cloud Sentinel data connector

### ISSUE THREAD

**Issue by mmsepyx** [hashicorp/terraform-provider-azurerm#18344]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is possible to create a Microsoft Sentinal Data Connector for Microsoft Defender for cloud using the `azurerm_sentinel_data_connector_azure_security_center` resource.

Unfortunatelly, the bidirectional sync is not supported, which forces us to use a provisioner to enabled it. Adding support for this feature would be welcome.

### New or Affected Resource(s)/Data Source(s)

azurerm_sentinel_data_connector_azure_security_center

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_data_connector_azure_security_center" "defender-cloud-connector" {
  name                       = "name"
  log_analytics_workspace_id = "xxx"
  subscription_id            = "yyy"
  bi_directional_sync        = true
}
```

**Comment by magodo** [comment]
@mmsepyx By inspecting the API request, it appears this operation indicates to enable the alert sync settings for all the sentinels under current subscription:

```
[
    {
        "content": {
            "kind": "AlertSyncSettings",
            "properties": {
                "enabled": true
            }
        },
        "httpMethod": "PUT",
        "name": "xxxx",
        "requestHeaderDetails": {
            "commandName": "Microsoft_Azure_Security_Insights."
        },
        "url": "https://management.azure.com/subscriptions/xxxx/providers/Microsoft.Security/settings/sentinel?api-version=2021-06-01"
    }
]
```

So this wants to be a new singleton resource something called `azurerm_sentinel_alert_sync_setting", rather than a property within a DC?

**Comment by mmsepyx** [comment]
@magodo The API calls are different, this is true, and having a separate resource would totally fit the requirement.

My suggestion to have it embeded in the "azurerm_sentinel_data_connector_azure_security_center" resource comes from the Azure portal, where it is linked:

![defender](https://user-images.githubusercontent.com/2276183/189818476-f33940ac-cf9d-4175-8ed2-8188f304ebd5.png)
