### ISSUE TITLE
The provider hashicorp/azurerm does not support resource type │ "azurerm_data_collection_rule_association".

### ISSUE THREAD

**Issue by msharma111** [hashicorp/terraform-provider-azurerm#18352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.17

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_data_collection_rule_association

### Terraform Configuration Files

```hcl
resource "azurerm_data_collection_rule_association" "vm" {
  name                    = "DCRA-VMs"
  target_resource_id      = var.target_resource_id 
  data_collection_rule_id = var.data_collection_rule_id
  description             = "Default Data Collection Rule"
}
```

### Debug Output/Panic Output

```shell
│ Error: Invalid resource type
│
│   on ../vm.tf line 291, in resource "azurerm_data_collection_rule_association" "vm":
│  291: resource "azurerm_data_collection_rule_association" "vm" {
│
│ The provider hashicorp/azurerm does not support resource type
│ "azurerm_data_collection_rule_association".
```

### Expected Behaviour

Should be able to deploy the association.

### Actual Behaviour

Unable to detect the resource
 │ Error: Invalid resource type
│
│   on ../vm.tf line 291, in resource "azurerm_data_collection_rule_association" "vm":
│  291: resource "azurerm_data_collection_rule_association" "vm" {
│
│ The provider hashicorp/azurerm does not support resource type
│ "azurerm_data_collection_rule_association".

### Steps to Reproduce

terraform plan

**Comment by Amier3** [comment]
Hey @msharma111 

Are you referring to the [data collection rules in Azure Monitor](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/data-collection-rule-overview)? If so we cover rule associations under the resource [azurerm_monitor_data_collection_rule_association](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_data_collection_rule_association)

**Comment by msharma111** [comment]
is it azurerm_monitor_data_collection_rule_association or azurerm_data_collection_rule_association?
![image](https://user-images.githubusercontent.com/63875951/190195298-0cc3b3e9-3bc8-4823-90a8-05d8598a34f9.png)

**Comment by Amier3** [comment]
@msharma111 

Just tested it out and it's `azurerm_monitor_data_collection_rule_association` , that example code block is wrong. I'll go ahead and fix the example before closing this issue. Thanks for bringing this to our attention!

**Comment by Amier3** [comment]
Looks like this was already fixed with https://github.com/hashicorp/terraform-provider-azurerm/pull/18327v , which will be reflected in the next release. Considering that, i'll close this out.
