### ISSUE TITLE
error creating/updating DNS Zone Virtual network link

### ISSUE THREAD

**Issue by barbacbd** [hashicorp/terraform-provider-azurerm#18350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.16.1

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_zone_virtual_network_link

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_zone" "private" {
  name                = var.cluster_domain
  resource_group_name = var.resource_group_name
  depends_on = [azurerm_dns_cname_record.api_external_v4, azurerm_dns_cname_record.api_external_v6]
}

resource "azurerm_private_dns_zone_virtual_network_link" "network" {
  name                  = "${var.cluster_id}-network-link"
  resource_group_name   = var.resource_group_name
  private_dns_zone_name = azurerm_private_dns_zone.private.name
  virtual_network_id    = var.virtual_network_id
}
```

### Debug Output/Panic Output

```shell
level=info msg=Consuming Openshift Manifests from target directory
level=info msg=Consuming Common Manifests from target directory
level=info msg=Credentials loaded from file "/var/run/secrets/ci.openshift.io/cluster-profile/osServicePrincipal.json"
level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: error creating/updating Private DNS Zone Virtual network link "ci-op-1w80vs6f-7f65d-t2zlz-network-link" (Resource Group "ci-op-1w80vs6f-7f65d-t2zlz-rg"): privatedns.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'ci-op-1w80vs6f-7f65d.ci2.azure.devcluster.openshift.com' not found."
level=error
level=error msg=  with module.dns.azureprivatedns_zone_virtual_network_link.network,
level=error msg=  on dns/dns.tf line 13, in resource "azureprivatedns_zone_virtual_network_link" "network":
level=error msg=  13: resource "azureprivatedns_zone_virtual_network_link" "network"
```

### Expected Behaviour

The private DNS Zone should have been created. `azurerm_private_dns_zone_virtual_network_link.network` requires `azurerm_private_dns_zone.private` to complete before it is parsed. It appears that adding a `depends_on = [azurerm_private_dns_zone.private]` alleviates the installation order issue, but this dependency should have been solved without an explicit `depends_on`. 

### Actual Behaviour

level=info msg=Consuming Openshift Manifests from target directory
level=info msg=Consuming Common Manifests from target directory
level=info msg=Credentials loaded from file "/var/run/secrets/ci.openshift.io/cluster-profile/osServicePrincipal.json"
level=info msg=Creating infrastructure resources...
level=error
level=error msg=Error: error creating/updating Private DNS Zone Virtual network link "ci-op-1w80vs6f-7f65d-t2zlz-network-link" (Resource Group "ci-op-1w80vs6f-7f65d-t2zlz-rg"): privatedns.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'ci-op-1w80vs6f-7f65d.ci2.azure.devcluster.openshift.com' not found."
level=error
level=error msg=  with module.dns.azureprivatedns_zone_virtual_network_link.network,
level=error msg=  on dns/dns.tf line 13, in resource "azureprivatedns_zone_virtual_network_link" "network":
level=error msg=  13: resource "azureprivatedns_zone_virtual_network_link" "network" 

### References

https://github.com/openshift/installer/pull/6311
https://issues.redhat.com/browse/OCPBUGS-927

**Comment by stbenjam** [comment]
I am not sure it's a problem with the terraform provider -- because even after seeing this depends we're experiencing this problem still.

Example:

```
time="2022-09-14T16:33:55Z" level=debug msg="module.dns.azurerm_private_dns_zone.private: Creating..."
time="2022-09-14T16:34:27Z" level=debug msg="module.dns.azurerm_private_dns_zone.private: Creation complete after 33s [id=/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/resourceGroups/ci-op-r0j51ij5-0e6bb-22jzf-rg/providers/Microsoft.Network/privateDnsZones/ci-op-r0j51ij5-0e6bb.ci.azure.devcluster.openshift.com]"
time="2022-09-14T16:34:27Z" level=debug msg="module.dns.azurerm_private_dns_zone_virtual_network_link.network: Creating..."
time="2022-09-14T16:54:51Z" level=error msg="Error: creating/updating Virtual Network Link (Subscription: \"d38f1e38-4bed-438e-b227-833f997adf6a\""
time="2022-09-14T16:54:51Z" level=error msg="Resource Group Name: \"ci-op-r0j51ij5-0e6bb-22jzf-rg\""
time="2022-09-14T16:54:51Z" level=error msg="Private Zone Name: \"ci-op-r0j51ij5-0e6bb.ci.azure.devcluster.openshift.com\""
time="2022-09-14T16:54:51Z" level=error msg="Virtual Network Link Name: \"ci-op-r0j51ij5-0e6bb-22jzf-network-link\"): performing CreateOrUpdate: virtualnetworklinks.VirtualNetworkLinksClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code=\"ParentResourceNotFound\" Message=\"Can not perform requested operation on nested resource. Parent resource 'ci-op-r0j51ij5-0e6bb.ci.azure.devcluster.openshift.com' not found.\""
```

From https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_windows-machine-config-operator/1237/pull-ci-openshift-windows-machine-config-operator-master-azure-e2e-operator/1570076519521325056/artifacts/azure-e2e-operator/ipi-install-install/artifacts/.openshift_install.log

**Comment by jiaweitao001** [comment]
Thanks for raising this issue. We're looking into it.

**Comment by jiaweitao001** [comment]
Hi @barbacbd , the provided code snippet seems insufficient for reproduce the problem. Could you please paste the whole block for further investigation? Thanks!

**Comment by stbenjam** [comment]
@jiaweitao001 The entire terraform config is in https://github.com/openshift/installer/tree/master/data/data/azure, which the dns config in https://github.com/openshift/installer/blob/master/data/data/azure/cluster/dns/dns.tf.

This is a ~10% problem for us, so it doesn't always happen.

**Comment by stbenjam** [comment]
@jiaweitao001  Any chance you've been able to look at this more?

This looks very similar to the behavior in https://github.com/hashicorp/terraform-provider-azurerm/issues/18287#issuecomment-1253444676, where we create a resource and it says not found.

We have a run with TF_LOG=debug set here: https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_installer/6304/pull-ci-openshift-installer-master-e2e-azure-ovn-shared-vpc/1574415977343356928/build-log.txt

**Comment by stbenjam** [comment]
@jiaweitao001 Any chance you've been able to look at this? This is not the only resource affected, https://github.com/hashicorp/terraform-provider-azurerm/issues/18311 reports an identical problem and ties it to the same start date.

We can also clearly show the behavior in our activity log.  The private DNS zone is created, 30 seconds later creating a link to a virtual network fails with DNS zone not found:

![image](https://user-images.githubusercontent.com/429763/193063670-9e9356d5-a0f7-487c-b722-81927e1a82fb.png)
