### ISSUE TITLE
Trying to read an existing resource group, while doing a terraform plan i'm getting "Error: Error: Resource Group "XXXXX" was not found

### ISSUE THREAD

**Issue by balurk** [hashicorp/terraform-provider-azurerm#18366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "existing-group"{
  name=var.resource_group_name
 }

resource "azurerm_storage_account" "sa" {
  name                            = var.storage_account_name
  location                        = data.azurerm_resource_group.data-rg.location
  resource_group_name             = data.azurerm_resource_group.data-rg.name
  account_tier                    = "Standard"
  account_kind                    = "Storage"
  account_replication_type        = "GRS"
  enable_https_traffic_only       = true
  
}
```

### Debug Output/Panic Output

```shell
Error: Error: Resource Group "cor-n-zweus-cargocf-messaging-rg" was not found
│
│   with data.azurerm_resource_group.data-rg,
│   on main.tf line 8, in data "azurerm_resource_group" "data-rg":
│    8: data "azurerm_resource_group" "data-rg"{
```

### Expected Behaviour

Expecting the existing resource group should be found for reading, which could be used to create function app and storage account

### Actual Behaviour

Getting the Error while running the terraform plan
 Error: Error: Resource Group "XXX" was not found
│
│   with data.azurerm_resource_group.data-rg,
│   on main.tf line 8, in data "azurerm_resource_group" "data-rg":
│    8: data "azurerm_resource_group" "data-rg"{

### Steps to Reproduce

1. terraform init
2. terraform plan

**Comment by onenessboy** [comment]
Are you sure that resource group exist ? you cant have `var.resource_group_name` in data block.

you need to mention name of actual resource which you created in that place..

see below example

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/resource_group

Hope this helps

**Comment by balurk** [comment]
@onenessboy - Yes that resource group exists. Let me make the changes you mentioned and try again. Thanks for your input

**Comment by balurk** [comment]
@onenessboy - I changed the var and directly passed the name in data block. But still getting the same error. Any idea if the terraform versions would make such difference?
My current version is 3.0.2

**Comment by ms-zhenhua** [comment]
Hi @balurk - seems **data-rg** referenced in the **azurerm_storage_account** is different from the name(**existing-group**) of the **azurerm_resource_group**. Kindly have a check. According to this [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate#configuring-the-service-principal-in-terraform), some environment variables(including the **subscription_id** and **tenant_id**) need to be set before using the AzureRM Provider. Kindly have a check. And please also help check the azurerm_resource_group really exists under the subscription_id.

Hope it could help you. 

data "azurerm_resource_group" "**existing-group"**{
  name=var.resource_group_name
 }

resource "azurerm_storage_account" "sa" {
  name                            = var.storage_account_name
  location                        = data.azurerm_resource_group.**data-rg**.location
  resource_group_name             = data.azurerm_resource_group.**data-rg**.name
  account_tier                    = "Standard"
  account_kind                    = "Storage"
  account_replication_type        = "GRS"
  enable_https_traffic_only       = true
  
}

**Comment by JonasFeierabend** [comment]
@balurk I had the same problem. For me the problem was not the ressource group but rather the provider. 
The error message should have been: "Unknown provider" instead of "cant find ressource group".
@ms-zhenhua yeah subscription_id, tenant_id are needed before you can access a data ressource_group. Then for that data source only the name is enough

**Comment by balurk** [comment]
Thank you @JonasFeierabend and @onenessboy - After defining the subscription and tenant id in Providers for Azure RM, i'm able to read the existing resource group
