### ISSUE TITLE
azurerm_shared_image architecture option forcing recreate of images with architecture defined

### ISSUE THREAD

**Issue by jordanfelle** [hashicorp/terraform-provider-azurerm#18363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_shared_image

### Terraform Configuration Files

```hcl
"azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_shared_image_gallery" "example" {
  name                = "example_image_gallery"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  description         = "Shared images and things."

  tags = {
    Hello = "There"
    World = "Example"
  }
}

resource "azurerm_shared_image" "example" {
  name                = "my-image"
  gallery_name        = azurerm_shared_image_gallery.example.name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"

  identifier {
    publisher = "PublisherName"
    offer     = "OfferName"
    sku       = "ExampleSku"
  }
```

### Debug Output/Panic Output

```shell
+ architecture                        = "x64" # forces replacement
```

### Expected Behaviour

Not setting an architecture shouldn't get the value.

### Actual Behaviour

When architecture is not specified a default of x64 is added. Not all images have this value set and this results in images being recreated.

### Steps to Reproduce

Create an image without an architecture using and older provider before this default and then attempt a terraform apply with the latest provider. 

### References

This looks to be introduced in https://github.com/hashicorp/terraform-provider-azurerm/pull/17250 and I would assume having a default value set https://github.com/hashicorp/terraform-provider-azurerm/pull/17250/files#diff-15034449be4075f058d1b178d8ab8872da97dc60b62bb78f2efa879a42ec512aR66

**Comment by epopisces** [comment]
We are also encountering this issue, and the workaround has been to pin the provider version to 3.18.0 (the architecture argument was introduced in 3.19.0).

**Comment by myc2h6o** [comment]
Hi @jordanfelle thanks for opening the issue! and thanks @epopisces for sharing the workaround. This is indeed a regression in the provider. I've opened #18400 to set the default value into state when architecture is missing in the resource.
