### ISSUE TITLE
Support for azurerm_mssql_virtual_machine to Set system databases location to newly create data storage

### ISSUE THREAD

**Issue by dsiperek-vendavo** [hashicorp/terraform-provider-azurerm#18377]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need the same option like you have in the Azure Portal to "Set system database (except tempDb) location to newly created data storage" 
See picture below
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/70541548/190005493-58b6063b-c437-470c-b921-10322fa8fadb.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_virtual_machine

**Comment by myc2h6o** [comment]
Hi @dsiperek-vendavo thanks for opening the issue! I'll be adding the support for this

**Comment by dsiperek-vendavo** [comment]
@myc2h6o Any idea when? We are going the route of getting off of this azure service now and doing everything sql ourselves because of this issue and the other settings issue thats already opened https://github.com/hashicorp/terraform-provider-azurerm/issues/15824

**Comment by myc2h6o** [comment]
@dsiperek-vendavo I've opened #19115 to add the support for this
