### ISSUE TITLE
cannot create cosmosdb sql database getting  Code="MethodNotAllowed" Message="Requests for API sql are not supported for this account.

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#18371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.21

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "cosmosaccount" {
  name                = "cosmosdb"
  location            = var.location
  resource_group_name = var.rg_name  
  offer_type          = var.cosmosdb_offer_type
  kind                = var.cosmosdb_kind
  is_virtual_network_filter_enabled = "true"
  ip_range_filter     = var.ip_range_filter

  capabilities {
    name = "EnableTable"
  }

  enable_automatic_failover = false

  consistency_policy {
    consistency_level       = var.cosmosdb_consistancy_level
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }

  virtual_network_rule  {
    id                = var.subnet_id
    ignore_missing_vnet_service_endpoint = true
  }
}


resource "azurerm_cosmosdb_sql_database" "comosdbsqldb" {
  name                = "driving"
  resource_group_name = azurerm_cosmosdb_account.cosmosaccount.resource_group_name
  account_name        = azurerm_cosmosdb_account.cosmosaccount.name
  throughput          = 500  
  depends_on = [azurerm_cosmosdb_account.cosmosaccount]  
}


resource "azurerm_cosmosdb_sql_container" "mdhistcontainer" {
  name                  = "metadata_history"
  resource_group_name   = azurerm_cosmosdb_account.cosmosaccount.resource_group_name
  account_name          = azurerm_cosmosdb_account.cosmosaccount.name
  database_name         = azurerm_cosmosdb_sql_database.comosdbsqldb.name
  partition_key_path    = "/definition/id"
  partition_key_version = 1
  throughput            = 500

  indexing_policy {
    indexing_mode = "consistent"

    included_path {
      path = "/*"
    }

    included_path {
      path = "/included/?"
    }

    excluded_path {
      path = "/excluded/?"
    }
  }

  unique_key {
    paths = ["/definition/idlong", "/definition/idshort"]
  }
  depends_on = [azurerm_cosmosdb_sql_database.comosdbsqldb]
}
```

### Debug Output/Panic Output

```shell
│ Error: checking for presence of Sql Database: (Name "xxxxxxxx" / Database Account Name
 "xxxxxxxxxxxxxxxx" / Resource Group "rxxxxxxxxxxxxxxxxx"): documentdb.SQLResourcesClient#GetSQLDatabase:
 Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 
 r\nActivityId:xxxxxxxxxxxxxxxxxx, 
 Microsoft.Azure.Documents.Common/2.14.0"
```

### Expected Behaviour

It has to created cosmosdb account and a sql db and containers in that db

### Actual Behaviour

│ Error: checking for presence of Sql Database: (Name "xxxxxxxx" / Database Account Name
 "xxxxxxxxxxxxxxxx" / Resource Group "rxxxxxxxxxxxxxxxxx"): documentdb.SQLResourcesClient#GetSQLDatabase:
 Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 
 r\nActivityId: xxxxxxxxxxxxxx
 Microsoft.Azure.Documents.Common/2.14.0"

### Steps to Reproduce

terraform apply

**Comment by sinbai** [comment]
@onenessboy thanks for opening this issue here. Could you provide the values of variables in the tf config to help reproduce and troubleshooting?

**Comment by onenessboy** [comment]
> @onenessboy thanks for opening this issue here. Could you provide the values of variables in the tf config to help reproduce and troubleshooting?

hi @sinbai  I am able to resolve issue,  the fix to omit capability all together in cosmosdb account definition.. I came to know we dont need to add any capability if we want to create default sqlapi db hence closing this issue
