### ISSUE TITLE
Front Door provider runs into inconsistent final plan with multiple backend_pools and routing_rules

### ISSUE THREAD

**Issue by ststrobel** [hashicorp/terraform-provider-azurerm#18389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.19.1

### Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor" "main" {
  name                                         = "${var.resource_group_name}-public"
  resource_group_name                          = var.resource_group_name

  dynamic "routing_rule" {
    for_each           = toset(var.backends)
    iterator           = backend
    content {
      name = "routing-rule-${backend.value["tenant"]}"
      accepted_protocols = ["Https"]
      patterns_to_match = ["/${backend.value["path"]}/*"]
      frontend_endpoints = ["${var.resource_group_name}-public"]
      forwarding_configuration {
        forwarding_protocol = "HttpsOnly"
        backend_pool_name = "${var.resource_group_name}-app-service-backend-pool-${backend.value["tenant"]}"
      }
    }
  }

  backend_pool_load_balancing {
    name = "${var.resource_group_name}-app-service-load-balancing"
  }

  backend_pool_health_probe {
    name    = "${var.resource_group_name}-app-service-health-probe"
    enabled = false
  }

  backend_pool_settings {
    enforce_backend_pools_certificate_name_check = true
  }

  dynamic "backend_pool" {
    for_each  = toset(var.backends)
    iterator  = backend
    content {
      name = "${var.resource_group_name}-app-service-backend-pool-${backend.value["tenant"]}"
      backend {
        host_header = backend.value["hostname"]
        address = backend.value["hostname"]
        http_port = 80
        https_port = 443
      }
      load_balancing_name = "${var.resource_group_name}-app-service-load-balancing"
      health_probe_name = "${var.resource_group_name}-app-service-health-probe"
    }
  }

  frontend_endpoint {
    name                                    = "${var.resource_group_name}-public"
    host_name                               = "${var.resource_group_name}-public.azurefd.net"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.frontdoor.azurerm_frontdoor.main to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
│ .routing_rule[1].forwarding_configuration[0].backend_pool_name: was
│ cty.StringVal("app-staging-app-service-backend-pool-1"), but now
│ cty.StringVal("app-staging-app-service-backend-pool-2").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for module.frontdoor.azurerm_frontdoor.main to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
│ .backend_pool[0].name: was
│ cty.StringVal("app-staging-app-service-backend-pool-1"), but now
│ cty.StringVal("app-staging-app-service-backend-pool-2").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Expected Behaviour

running terraform plan + apply should be consistent and always produce the same result.

### Actual Behaviour

when running plan everything is fine, but when applying it terraform complains that the there is an inconsistent final plan, mixing up the order of the subresources routing_rule and backend_pool.
Running plan and apply again then resolves the issue - but this is no viable option for production

### Steps to Reproduce

terraform plan && terraform apply
-> fail
terraform plan && terraform apply
-> success

**Comment by WodansSon** [comment]
@ststrobel, thank you for opening this issue. This is a known issue, but will not be fixed since these resources are going to be removed from the Terraform in the v4.0 of the provider. There is already a replacement for these resources [azurerm_cdn_frontdoor](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_custom_domain) here. Thanks again for opening this issue, but I am going to close it since these resources are no longer in active development.
