### ISSUE TITLE
Unable to create role assignment at resource provider scopeof /providers/Microsoft.Marketplace

### ISSUE THREAD

**Issue by ggomes-agc** [hashicorp/terraform-provider-azurerm#18387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "assignment-2" {
  scope              = "/providers/Microsoft.Marketplace"
  role_definition_id = "/providers/Microsoft.Authorization/roleDefinitions/dd920d6d-f481-47f1-b461-f338c46b2d9f"
  principal_id       = azuread_service_principal.spn.id
}
```

### Debug Output/Panic Output

```shell
Error: expected scope to be one of [/providers/Microsoft.Subscription], got /providers/Microsoft.Marketplace

  on main.tf line 73, in resource "azurerm_role_assignment" "assignment-2":
  73:   scope              = "/providers/Microsoft.Marketplace"



Error: ID was missing the `enrollmentAccounts` element

  on main.tf line 73, in resource "azurerm_role_assignment" "assignment-2":
  73:   scope              = "/providers/Microsoft.Marketplace"



Error: parsing "/providers/Microsoft.Marketplace": expected 4 segments within the Resource ID but got 2 for "/providers/Microsoft.Marketplace"

  on main.tf line 73, in resource "azurerm_role_assignment" "assignment-2":
  73:   scope              = "/providers/Microsoft.Marketplace"



Error: parsing "/providers/Microsoft.Marketplace": parsing segment "subscriptions": expected the segment "providers" to be "subscriptions"

  on main.tf line 73, in resource "azurerm_role_assignment" "assignment-2":
  73:   scope              = "/providers/Microsoft.Marketplace"



Error: parsing "/providers/Microsoft.Marketplace": expected 4 segments within the Resource ID but got 2 for "/providers/Microsoft.Marketplace"

  on main.tf line 73, in resource "azurerm_role_assignment" "assignment-2":
  73:   scope              = "/providers/Microsoft.Marketplace"



Error: Can not parse "scope" as a resource id: No subscription ID found in: "providers/Microsoft.Marketplace"

  on main.tf line 73, in resource "azurerm_role_assignment" "assignment-2":
  73:   scope              = "/providers/Microsoft.Marketplace"


ERRO[0005] 1 error occurred:
        * exit status 1
```

### Expected Behaviour

The role assignment should be created. The following Powershell code is able to deploy the role assignment. 

New-AzRoleAssignment -ObjectId $sp.Id -Scope /providers/Microsoft.Marketplace -RoleDefinitionName "Marketplace Admin"

Note: This issue is similar to the fix for https://github.com/hashicorp/terraform-provider-azurerm/issues/17397.  

### Actual Behaviour

Terraform's syntax checking seems to block this scope type.

### Steps to Reproduce

terraform plan

**Comment by ms-zhenhua** [comment]
Hi @ggomes-agc, thank you for reporting this issue. I will create a PR to support `/providers/Microsoft.Marketplace`

**Comment by rcskosir** [comment]
Hi @ms-zhenhua I followed the thread of #18439 and saw that it was closed and you referenced opening a new PR, but that one was not linked. I am following up to see if you know if this issue has been fixed/resolved. Thank you!

**Comment by ms-zhenhua** [comment]
Hi @rcskosir, not yet. I will reopen the PR when I finish updating it locally.
