### ISSUE TITLE
Creating a new AKS cluster in a new subscription requires AKS-AzureDefender feature registration

### ISSUE THREAD

**Issue by MrSimonC** [hashicorp/terraform-provider-azurerm#18395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

Creating a new AKS cluster in a new subscription requires AKS-AzureDefender

When I deploy a new AKS cluster, but also define `microsoft_defender` and `oms_agent` property, terraform fails to deploy with the following error:

 Error: updating Cluster: (Managed Cluster Name "myresourcename-cluster" / Resource Group "myresourcename-prod"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AzureDefenderFeatureFlagNotEnabled" Message="AzureDefender installation is not allowed since feature 'Microsoft.ContainerService/AKS-AzureDefender' is not enabled. Please see https://aka.ms/aks/previews for how to enable features."
│ 
│   with azurerm_kubernetes_cluster.cluster,
│   on main.tf line 95, in resource "azurerm_kubernetes_cluster" "cluster":
│   95: resource "azurerm_kubernetes_cluster" "cluster" {

Recreation steps:
1) create a new subscription
2) Follow [this guide](https://docs.microsoft.com/en-us/azure/defender-for-cloud/defender-for-containers-enable?tabs=aks-deploy-portal%2Ck8s-deploy-asc%2Ck8s-verify-asc%2Ck8s-remove-arc%2Caks-removeprofile-api&pivots=defender-for-container-aks) to enable Defender for Containers in the Azure Portal
3) either copy/paste new AKS terraform code, or use the below definition (updating as necessary)

```terraform
# Initialise
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3"
    }
  }
  backend "azurerm" {
    resource_group_name = "myazurestateresourcegroup"
    storage_account_name = "myaccountname"
    container_name = "mycontainername"
    key = "mystatefile.tfstate"
  }
}

provider "azurerm" {
  features {}
}

# AKS cluster
resource "azurerm_kubernetes_cluster" "cluster" {
  azure_policy_enabled   = true
  dns_prefix             = "myresourcegroup-cluster"
  local_account_disabled = true
  location               = azurerm_resource_group.main_resource_group.location
  name                   = "myresourcegroup-cluster"
  resource_group_name    = azurerm_resource_group.main_resource_group.name
  sku_tier               = "Paid"
  azure_active_directory_role_based_access_control {
    admin_group_object_ids = ["000AddYourOwnGuidForYourOwnAD000"]
    managed                = true
    tenant_id              = "000MyTenant000"
  }
  default_node_pool {
    enable_auto_scaling = true
    max_count           = 6
    min_count           = 2
    name                = "agentpool"
    vm_size             = "Standard_DS2_v2"
    zones               = ["1", "2", "3"]
  }
  identity {
    type = "SystemAssigned"
  }
  key_vault_secrets_provider {
    secret_rotation_enabled = true
    secret_rotation_interval = "15m"
  }
  microsoft_defender {
    log_analytics_workspace_id = azurerm_log_analytics_workspace.cluster_insights.id
  }
  oms_agent {
    log_analytics_workspace_id = azurerm_log_analytics_workspace.cluster_insights.id
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "cluster_node_pool" {
  enable_auto_scaling   = true
  kubernetes_cluster_id = azurerm_kubernetes_cluster.cluster.id
  max_count             = 6
  min_count             = 2
  mode                  = "System"
  name                  = "agentpool"
  vm_size               = "Standard_DS2_v2"
  zones                 = ["1", "2", "3"]
  depends_on = [
    azurerm_kubernetes_cluster.cluster,
  ]
}
```

Terraform v1.2.9 on windows_amd64:

4) Run terraform plan (which works fine)
5) Run terraform apply

EXPECTED:
Azure AKS cluster and node pool are created

ACTUAL:
Error is seen (see top of this isssue)

WORKAROUND:
We now *have* to manually run `az feature registration create --name AKS-AzureDefender --namespace Microsoft.ContainerService` against the subscription and use `az feature show --name AKS-AzureDefender --namespace Microsoft.ContainerService` to check it's finished registering (takes about 15 mins)
7) Re run `terraform apply` against the new subscription
8) Terraform apply finishes successfully and infrastruture is created

### Debug Output/Panic Output

```shell
Error: updating Cluster: (Managed Cluster Name "myresourcename-cluster" / Resource Group "myresourcename-prod"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="AzureDefenderFeatureFlagNotEnabled" Message="AzureDefender installation is not allowed since feature 'Microsoft.ContainerService/AKS-AzureDefender' is not enabled. Please see https://aka.ms/aks/previews for how to enable features."
│ 
│   with azurerm_kubernetes_cluster.cluster,
│   on main.tf line 95, in resource "azurerm_kubernetes_cluster" "cluster":
│   95: resource "azurerm_kubernetes_cluster" "cluster" {
```

### Expected Behaviour

(see above)

### Actual Behaviour

(see above)

### Steps to Reproduce

(see above)

**Comment by tombuildsstuff** [comment]
hi @MrSimonC 

Thanks for opening this issue.

Taking a look through here this appears to be required since you're defining the `microsoft_defender` block:

```
  microsoft_defender {
    log_analytics_workspace_id = azurerm_log_analytics_workspace.cluster_insights.id
  }
```

Is this still the case when provisioning this without this block defined?

Thanks!

**Comment by MrSimonC** [comment]
Hello again. I think it's fine. I _thought_ I checked the docs on this - but there are 2 parts to reading about the `microsoft_defender` part - and I only saw one of them. Checking the other, it already points to Microsoft docs - which again also have that CLI command in. My bad - I'll close the issue.

**Comment by ekrof** [comment]
Thanks @MrSimonC, your workaround helped us as well. I might be wrong, but it seems like the deprecated defender AKS SKUs are causing trouble if they are enabled. I went ahead and turned all three of them off, and then ran your `az feature registration create --name AKS-AzureDefender --namespace Microsoft.ContainerService` line. Terraform stopped giving us that error afterwards.

![image](https://user-images.githubusercontent.com/14015087/191905863-9f369600-ad7a-4ead-8840-636c85ec6d61.png)
