### ISSUE TITLE
Support for Multi-User-Authorization in Recovery Services Vault

### ISSUE THREAD

**Issue by leighmau** [hashicorp/terraform-provider-azurerm#18403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft has released Multi User-Authorization for Azure Recovery Services Vault as generally available support for back in June 2022. We have a requirement for enabling this capability to provide additional assurance around the ability to tamper with backup settings while still enabling subscription managers to own and manage their backups.

I noticed that the Terraform registry has the ability to deploy a resource guard resource which is great, but we can't assign it till the above is in place
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_resource_guard

### New or Affected Resource(s)/Data Source(s)

azurerm_latest

### References

https://techcommunity.microsoft.com/t5/azure-governance-and-management/azure-backup-multi-user-authorization-for-recovery-services/ba-p/3573316
https://docs.microsoft.com/en-gb/azure/backup/multi-user-authorization

**Comment by ziyeqf** [comment]
Hi @leighmau , thanks for opening the issue.

the `azurerm_role_assignment` resource might satisfy your demand. you can set the `scope` property of it to the id of recovery vaults like below.
```
data "azurerm_recovery_services_vault" "example" {
  name                = "example-recovery-vault"
  resource_group_name = "example-resource-group"
}

data "azuread_service_principal" "example" {
  display_name = "test-service-principal"
}

resource "azurerm_role_assignment" "example" {
  scope                = data.azurerm_recovery_services_vault.example.id
  role_definition_name = "Backup Reader"
  principal_id         = data.azuread_service_principal.example.id
}

```
For more details about `azurerm_role_assignment`, please refer to [the document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment)

If it helps or any further questions, please leave comments.

**Comment by ziyeqf** [comment]
I'm going to work on it.
blocked by https://github.com/Azure/azure-rest-api-specs/issues/20953

**Comment by ziyeqf** [comment]
Hi @leighmau, thanks again for opening this issue.

I have submitted a PR (#21712) to support this, you can subscribe it to keep track. Once it merged & released it will be available. For any further questions please leave comments.

Thanks!
