### ISSUE TITLE
Support for adding public certificates to Azure App Service Slots

### ISSUE THREAD

**Issue by philippeassani** [hashicorp/terraform-provider-azurerm#18413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform provide a way to add a public certificate an Azure App Service using "azurerm_app_service_public_certificate" resource.

However, this doesn't work for AppService Slots.
I tried to provide an "app_service_name" suce as myAppservice/slots/mySlotName.
In this case, certificate added successfully, by deployment fail at the end with error:
=> ID contained more segments than expected: ...

### New or Affected Resource(s)/Data Source(s)

azurerm_app_service_public_certificate

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_slot_public_certificate" "example" {
  resource_group_name  = azurerm_resource_group.example.name
  app_service_name     = azurerm_app_service.example.name
  slot_name            = azurerm_app_service_slot.example.name
  certificate_name     = "example-public-certificate"
  certificate_location = "Unknown"
  blob                 = filebase64("app_service_public_certificate.cer")
}
```

**Comment by xiaxyi** [comment]
Thanks @philippeassani for raising this issue, this should be enhancement, we'll evaluate it.
related:https://github.com/hashicorp/terraform-provider-azurerm/issues/18184

**Comment by mybayern1974** [comment]
@philippeassani , with xiaxyi's suggestion, would you mind if we close this issue as duplicate and you can subscribe to #18184?

**Comment by tombuildsstuff** [comment]
Closing in favour of #18184
