### ISSUE TITLE
LinuxVM(azurerm_linux_virtual_machine) and WindowsVM(azurerm_windows_virtual_machine) also need assessment_mode

### ISSUE THREAD

**Issue by grethinam** [hashicorp/terraform-provider-azurerm#18412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As per #17571 , **patch_assessment_mode** option is added only to Orchestrated VMSS, but Windows WindowsVM and LinuxVM also need this option. OR at least have to enabled at generic VM(azurerm_virtual_machine)

[Microsoft.Compute  change log ](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/change-log/virtualmachines#2021-03-01)

**linux_configuration:**

    patch_assessment_mode

**windows_configuration:**

    patch_assessment_mode 

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine 

azurerm_windows_virtual_machine

azurerm_virtual_machine

### References

[properties.osProfile.linuxConfiguration.patchSettings.assessmentMode](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2021-03-01/virtualmachines#linuxpatchsettings)
[properties.osProfile.windowsConfiguration.patchSettings.assessmentMode](https://docs.microsoft.com/en-us/azure/templates/microsoft.compute/2021-03-01/virtualmachines#patchsettings)

FYA: @WodansSon

**Comment by myc2h6o** [comment]
Hi @grethinam thanks for opening the issue! I'll be working on these properties in Virtual Machines resources

**Comment by myc2h6o** [comment]
I've opened #18437 to add the support for this
