### ISSUE TITLE
Support for deploying Azure Monitor Logs Dedicated Clusters

### ISSUE THREAD

**Issue by riteshmehta66** [hashicorp/terraform-provider-azurerm#18426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the Dedicated cluster creation DOC appears only CLI/Powershell or Rest API support. Kindly add support for deploying via Terraform. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_cluster

### New or Affected Resource(s)/Data Source(s)

azurerm_log_analytics_cluster

### Potential Terraform Configuration

```hcl
log_analytics_clusters = {
  name        = "test-law-cluster-001"                      # required
  resource_group_key  = "cacn_law_cluster_rg_01"            # required
  size_gb             = 1000                                # (Optional) The capacity of the Log Analytics Cluster is specified in GB/day. Allowed values depends on the version of azurerm provider
  # region              = "region1"                         # required. This defaults to location of resource group

  # identity = {                                              # required
  #   type      = "SystemAssigned"
  # }
  tags = {                                                  # optional
  }                                                 
}




module "log_analytics_clusters" {
  source   = "./modules/log_analytics_cluster"
  for_each = var.log_analytics_clusters

  global_settings     = local.global_settings
  client_config       = local.client_config
  settings            = each.value  
  location            = can(local.global_settings.regions[each.value.region]) ? local.global_settings.regions[each.value.region] : local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.resource_group.key, each.value.resource_group_key)].location
  resource_group_name = can(each.value.resource_group.name) || can(each.value.resource_group_name) ? try(each.value.resource_group.name, each.value.resource_group_name) : local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.resource_group_key, each.value.resource_group.key)].name
  base_tags           = try(local.global_settings.inherit_tags, false) ? try(local.combined_objects_resource_groups[try(each.value.resource_group.lz_key, local.client_config.landingzone_key)][try(each.value.resource_group.key, each.value.resource_group_key)].tags, {}) : {}
  
}


resource "azurerm_log_analytics_cluster" "analytics_cluster" {
  name                      = var.settings.name
  resource_group_name       = var.resource_group_name
  location                  = var.location
  size_gb                   = try(var.settings.size_gb, 1000)
  # abcdefg                   = var.settings.abcdefg

  identity {
    type = "SystemAssigned"
  }
  tags = merge(var.base_tags, try(var.settings.tags, null))
}
```

**Comment by ms-zhenhua** [comment]
Hi @riteshmehta66, thank you for reaching out.
According to this [Doc](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-dedicated-clusters#create-a-dedicated-cluster), Cluster creation triggers both resource allocation and provisioning. So the deployment should have already been supported by the Provider through creating `azurerm_log_analytics_cluster` resources?
If I do not understand it correctly, kindly give more explanations about this issue. Thanks.
![image](https://user-images.githubusercontent.com/76987228/190954652-988d7660-1d63-48cc-b3c0-3fdbfdfe9928.png)

**Comment by rcskosir** [comment]
@riteshmehta66 Thank you for taking the time to open this feature request. 
Based on @ms-zhenhua comment above, this should already be supported by the Provider, so I am going to mark this issue closed. If that is not the case and you can provider us with more information regarding your feature request, we can reopen this issue.
