### ISSUE TITLE
Azure Private Endpoint with ip_configuration for a Key Vault fails

### ISSUE THREAD

**Issue by sl3dg3hamm3r** [hashicorp/terraform-provider-azurerm#18443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "this" {
  name                = "pe-private-endpoint-test"
  location            = "northeurope"
  resource_group_name = "rg-test"
  subnet_id           = "<subnet-ID>"

  private_service_connection {
    name                           = "pe-private-endpoint-test-privateserviceconnection"
    private_connection_resource_id = "<key-vault-resource-id>"
    is_manual_connection           = false
    subresource_names              = ["vault"]
  }

  ip_configuration {
    name                = "pe-private-endpoint-test-ip-configuration"
    private_ip_address  = "xxx.xxx.xxx.xxx"
    subresource_name    = "vault"
  }
}
```

### Debug Output/Panic Output

```shell
Private Endpoint /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/<resource-group-name>/providers/Microsoft.Network/privateEndpoints/<key-vault-name> contains static ipconfigurations: [PrivateIPAddress: xxx.xxx.xxx.xxx, GroupId: vault, MemberName: vault] and its missing these membernames/groupids requested by Private Link service [GroupId: vault, MemberName: default]. Private Endpoint needs to be reconfigured with missing memberNames.
```

### Expected Behaviour

One should be able to define the member name of the IP configuration (which has to be `vault` for key vaults, I guess).

### Actual Behaviour

`subresource_name` is used for `group_id` AND `member_name` (I suppose this is the problem).

By the way: The problem does not apply for private endpoints connected to e.g. Storage Accounts, App Configurations and Azure Data Factories, with ip_configuration. There it works just fine.

### Steps to Reproduce

terraform init
terraform plan # will work
terraform apply # ARM returns error

**Comment by wuxu92** [comment]
Hi @sl3dg3hamm3r  thanks for your feedback. it looks like a bug and I'll try to fix it soon.
