### ISSUE TITLE
azurerm_resource_provider_registration with skip_provider_registration = true not working

### ISSUE THREAD

**Issue by rikribbers** [hashicorp/terraform-provider-azurerm#18458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0-beta1

### AzureRM Provider Version

v3.23.0 

### Affected Resource(s)/Data Source(s)

azurerm_resource_provider_registration 

### Terraform Configuration Files

```hcl
provider "azurerm" {
  skip_provider_registration = true

  features {}
}

locals {
  # List is compiled from here
  # https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers
  provider_list = [
    "Microsoft.Storage",
    "Microsoft.Web"
  ]

  provider_map = { for p in local.provider_list : p => p }
}
data "azurerm_subscription" "subscription" {
  subscription_id = "some guid"
}


resource "azurerm_resource_provider_registration" "provider" {
  for_each = local.provider_map
  name     = each.value
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: A resource with the ID "/subscriptions/<subscription-id>/providers/Microsoft.Storage" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_resource_provider_registration" for more information.
│ 
│   with azurerm_resource_provider_registration.provider["Microsoft.Storage"],
│   on main.tf line 74, in resource "azurerm_resource_provider_registration" "provider":
│   74: resource "azurerm_resource_provider_registration" "provider" {
│ 
│ A resource with the ID
│ "/subscriptions/<subscription-id>/providers/Microsoft.Storage"
│ already exists - to be managed via Terraform this resource needs to be
│ imported into the State. Please see the resource documentation for
│ "azurerm_resource_provider_registration" for more information.
╵
```

### Expected Behaviour

I expect the resource provider to be registered at the subscription and the terraform apply to finish success fully

### Actual Behaviour

Terraform apply failed and the providers are not registered on the subscription

### Steps to Reproduce

Create a brand new shiny EA subscription under your BillingAccount
run the terraform apply with the above code 

### Important Factoids

a brand new untouchednewly created subscription

**Comment by ms-zhenhua** [comment]
Hi @rikribbers, thank you for reaching out. 
I tried your configuration under a newly created subscription and I did not get any error. From the error you met, it seems like the `Microsoft.Storage` had already been registered before you apply your configuration. Have you checked the registration status from [Azure Portal](https://portal.azure.com/) before running your configuration ? 
![image](https://user-images.githubusercontent.com/76987228/192203460-65ef227c-b3f9-40ab-a8cb-ffcb1639b0e5.png)
![image](https://user-images.githubusercontent.com/76987228/192203490-69103d0e-2828-4d58-8da9-8a41fe6c4a77.png)

**Comment by ms-zhenhua** [comment]
Hi @rikribbers, it's really strange. Just to double confirm with you, is the **<subscription-id>** in your error message the same with the subscription you just checked ?

**Comment by rikribbers** [comment]
argh, my bad.. The configuration I presented uses the current client config subscription... But I want to register a different subscription and that is possible with a provider alias.... would look something like this, however in our use-case that doesn't work..... 

````
provider "azurerm" {
  alias="new_subscription"
  subscription_id = <some guid>
}

resource "azurerm_resource_provider_registration" "provider" {
  for_each = local.provider_map
  name     = each.value

  provider.new_subscription
}
````

**Comment by ms-zhenhua** [comment]
Hi @rikribbers, seems like you have 2 test subscriptions. Kindly help check the registration status of both of them before your testing.
And below is the runnable configuration which can work well under my own test subscription. Hope it can help you.

```
provider "azurerm" {
  features {}
}

provider "azurerm" {
  alias="new_subscription"
  skip_provider_registration = true
  features {}
# replace the subscription_id with your own
  subscription_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}

locals {
  # List is compiled from here
  # https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-services-resource-providers
  provider_list = [
    "Microsoft.Storage",
  ]

  provider_map = { for p in local.provider_list : p => p }
}

resource "azurerm_resource_provider_registration" "provider" {
  for_each = local.provider_map
  name     = each.value

  provider = azurerm.new_subscription
}
```

**Comment by rikribbers** [comment]
Sorry for my late response.. this did not get the proper attention. The solution presented above is working. thx
