### ISSUE TITLE
Creating multiple blob container with azurerm_resource_group_template_deployment and a tempalte. Terraform shows containers creation successful but only one container is actually created in Azure storage 

### ISSUE THREAD

**Issue by cacizi41** [hashicorp/terraform-provider-azurerm#18452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_template_deployment

### Terraform Configuration Files

```hcl
locals {
  failed_events_containers = toset(["container1", "container2", "container3"])
}

resource "azurerm_storage_account" "failed_events" {
  name                     = "failedevents${substr(lower(var.environment), 0, 4)}storage"
  resource_group_name      = azurerm_resource_group.aks_group.name
  location                 = azurerm_resource_group.aks_group.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices", "Logging", "Metrics"]
  }
}

resource "azurerm_resource_group_template_deployment" "failed_events_container" {
  name                = "failed-events-container-deploy-${random_id.arm_deployment_id.hex}"
  resource_group_name = azurerm_resource_group.aks_group.name
  deployment_mode     = "Incremental"
  for_each = local.failed_events_containers
  parameters_content = jsonencode({
    "storageAccountName" = {
      value = azurerm_storage_account.failed_events.name
    }
    "containerName" = {
      value = each.key
    }
  })
  template_content = file("${path.module}/arm/failed-events-container.json")
  depends_on       = [azurerm_storage_account.failed_events]
}

resource "azurerm_storage_management_policy" "events_eventbroker_blobs" {
  storage_account_id = azurerm_storage_account.failed_events_eventbroker.id

  rule {
    name    = "payloadAgingRule"
    enabled = true
    filters {
      prefix_match = local.failed_events_containers
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than = 30
        delete_after_days_since_modification_greater_than       = 180
      }
    }
  }
}

#Template
{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "storageAccountName": {
      "type": "String"
    },
    "containerName": {
      "type": "String"
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Storage/storageAccounts/blobServices/containers",
      "apiVersion": "2021-04-01",
      "name": "[concat(parameters('storageAccountName'), '/default/', parameters('containerName'))]",
      "properties": {}
    }
  ]
}
```

### Debug Output/Panic Output

```shell
No error in terraform plan and terraform apply
```

### Expected Behaviour

containers being created in the storage account.

### Actual Behaviour

only one(first one) got created in the storage account.

### Steps to Reproduce

![Screenshot 2022-09-19 172018](https://user-images.githubusercontent.com/14630538/191141208-468f267e-ad04-470d-b70d-5ff6b8cd365a.png)

### References

Referenced this post to create blob container using azurerm_resource_group_template_deployment as a walk around:https://github.com/hashicorp/terraform-provider-azurerm/issues/2977

**Comment by ms-zhenhua** [comment]
Hi @cacizi41, thank you for reaching out.
It seems that the reason is that you used the same `azurerm_resource_group_template_deployment.failed_events_container.name` for these containers which cause overwriting. Could you try to put the `name` under `for_each` and try it again ? Here is the sample:

```
resource "azurerm_resource_group_template_deployment" "failed_events_container" {
 ...
  for_each            = local.failed_events_containers
  name                = "failed-events-container-deploy-${each.key}"
  ...
```

**Comment by cacizi41** [comment]
> Hi @cacizi41, thank you for reaching out. It seems that the reason is that you used the same `azurerm_resource_group_template_deployment.failed_events_container.name` for these containers which cause overwriting. Could you try to put the `name` under `for_each` and try it again ? Here is the sample:
> 
> ```
> resource "azurerm_resource_group_template_deployment" "failed_events_container" {
>  ...
>   for_each            = local.failed_events_containers
>   name                = "failed-events-container-deploy-${each.key}"
>   ...
> ```

Thanks. It resolved the overwriting issue. I also encountered that 4 out of 9 deployments(same 4 containers across different environments) failed with no clear error from azure. Once I deleted those failed deployments from azure portal those can be re-deployed by terraform apply again. But I think it is another issue. Closing this one now.
