### ISSUE TITLE
azurerm_api_management_logger - resource_id loop 

### ISSUE THREAD

**Issue by ryanfnhs** [hashicorp/terraform-provider-azurerm#18466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_logger

### Terraform Configuration Files

```hcl
logger = { 
  1 = {
    name        = "appin-01"
    resource_id = "/subscriptions/000000-555-4444-8885-585454253/resourceGroups/rg-01/providers/Microsoft.ApiManagement/service/apim-01/loggers/appin-01",
    buffered    = true
    application_insights = {

    }
  }
}

resource "azurerm_api_management_logger" "app_ins" {
  for_each            = var.logger
  name                = each.value.name
  api_management_name = "apim-01"
  resource_group_name = "rg-01"
  resource_id         = each.value.resource_id
  buffered            = each.value.buffered

  dynamic "application_insights" {
    for_each = each.value.application_insights

    content {
      instrumentation_key = application_insights.value.instrumentation_key
    }
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_api_management_logger.app_ins["1"] will be updated in-place
  ~ resource "azurerm_api_management_logger" "app_ins" {
        id                  = "/subscriptions/000000-555-4444-8885-585454253/resourceGroups/rg-01/providers/Microsoft.ApiManagement/service/apim-01/loggers/appin-01",
        name                = "appin-01"
      - resource_id         = "appin-01" -> null
        # (3 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

after apply, resource ID should have changed as per plan. but what actually occurs is that on apply changes state they have been made but the resource ID remains "appin-01". Even manually removing the resourceID from the statefile producing the same results once apply is done and resource ID is "appin-01".

### Actual Behaviour

No changes were made on terraform apply

### Steps to Reproduce

terraform import resource
terraform apply

**Comment by xuzhang3** [comment]
@ryanfnhs  this property does not support updating,  you can only destroy and create a new one.
Ref: https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/logger/update?tabs=HTTP#request-body
