### ISSUE TITLE
azurerm_virtual_desktop_scaling_plan - Mixed/wrong argument description

### ISSUE THREAD

**Issue by teemukj** [hashicorp/terraform-provider-azurerm#18475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_scaling_plan

### Terraform Configuration Files

```hcl
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_scaling_plan
```

### Debug Output/Panic Output

```shell
In the documentation of "virtual_desktop_scaling_plan" resource, two argument descriptions are wrong, as they should be swapped in place.
```

### Expected Behaviour

[ramp_up_capacity_threshold_percent](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_scaling_plan#ramp_up_capacity_threshold_percent) attribute should be described as the threshold value for the autoscaling process during the ramp-up phase.

[ramp_up_minimum_hosts_percent](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_scaling_plan#ramp_up_minimum_hosts_percent) attribute should be described as the minimum percentage of session hosts to be available during ramp-up/peak.

### Actual Behaviour

Currently the descriptions of these attributes are mixed/swapped in the azurerm documentation. 

### References

https://learn.microsoft.com/en-us/azure/virtual-desktop/autoscale-scenarios

**Comment by sinbai** [comment]
Hi @teemukj thanks for bringing this to our attention. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/18490)has been submitted to fix it.
