### ISSUE TITLE
Support for Azure Cache for Redis `2022-05-01` API version

### ISSUE THREAD

**Issue by austintolani** [hashicorp/terraform-provider-azurerm#18484]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new API version (`2022-05-01`) for the Azure Cache for Redis Service. This new API version includes support for Managed Identity, changes to long running operations and changes to the default version for new cache creates. Request is to update Terraform with these new changes and to use the new API version. 

### New or Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### References

[REST API Specs PR](https://github.com/Azure/azure-rest-api-specs/pull/19506)

**Comment by austintolani** [comment]
Created #19053, which calls for support for an even newer `2022-06-01` API version.

**Comment by mybayern1974** [comment]
Thank austintolani's suggestion. Close this issue in favor of #19053.
