### ISSUE TITLE
Data azurerm_databricks_workspace location not working

### ISSUE THREAD

**Issue by waltonchiang** [hashicorp/terraform-provider-azurerm#18487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
data "azurerm_databricks_workspace" "this" {
  name = "workspace1"
  resource_group_name = "rg-workspace1"
}

output "databricks_workspace_location" {
  value = data.azurerm_databricks_workspace.this.location
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported attribute
│
│   on main.tf line 23, in output "databricks_workspace_location":
│   23:   value = data.azurerm_databricks_workspace.this.location
│
│ This object has no argument, nested block, or exported attribute named "location".
```

### Expected Behaviour

Returns the Databricks workspace locatoin

### Actual Behaviour

Does not recognize the location attributes reference

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/databricks_workspace#location

**Comment by Amier3** [comment]
Hey @waltonchiang 

Thanks for bringing this to our attention. Looks like `location` was never defined in the resource schema: 

https://github.com/hashicorp/terraform-provider-azurerm/blob/1a3195ad8d86f10bb3404da29eb861fcd2092700/internal/services/databricks/databricks_workspace_data_source.go#L24-L48

We'll get this fixed shortly!
