### ISSUE TITLE
azurerm_application_insights.connection_string keeps showing as changed when running plan

### ISSUE THREAD

**Issue by boyfonz** [hashicorp/terraform-provider-azurerm#18497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.6

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "sync-function-service-plan" {
  name                = "sync-function"
  resource_group_name = data.azurerm_resource_group.main_rg.name
  location            = data.azurerm_resource_group.main_rg.location
  os_type             = "Windows"
  sku_name            = "Y1"
}

resource "azurerm_windows_function_app" "sync-function-app" {
  name                       = "-function-app"
  resource_group_name        = data.azurerm_resource_group.main_rg.name
  location                   = data.azurerm_resource_group.main_rg.location
  storage_account_name       = data.azurerm_storage_account.blob-account.name
  storage_account_access_key = data.azurerm_storage_account.blob-account.primary_access_key
  service_plan_id            = azurerm_service_plan.sync-function-service-plan.id
  site_config {
    application_stack {
      dotnet_version = 6
    }
  }
  app_settings = {
# this value keeps getting changed
    "APPLICATIONINSIGHTS_CONNECTION_STRING" = azurerm_application_insights.function_application_insights.connection_string
  }
}

resource "azurerm_log_analytics_workspace" "function_log_analytics" {
  name                = "function-log-analytics-workspace"
  location            = data.azurerm_resource_group.main_rg.location
  resource_group_name = data.azurerm_resource_group.main_rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  daily_quota_gb      = 0.2
}

resource "azurerm_monitor_diagnostic_setting" "function_metrics" {
  name                       = "function_diagnostic_logs_and_metrics"
  target_resource_id         = azurerm_windows_function_app.sync-function-app.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.function_log_analytics.id
  log {
    category = "FunctionAppLogs"
    enabled  = true

    retention_policy {
      days    = 30
      enabled = true
    }
  }
  metric {
    category = "AllMetrics"
    enabled  = true

    retention_policy {
      days    = 30
      enabled = true
    }
  }
}

resource "azurerm_application_insights" "function_application_insights" {
  name                       = "function-appinsights"
  location                   = data.azurerm_resource_group.main_rg.location
  resource_group_name        = data.azurerm_resource_group.main_rg.name
  workspace_id               = azurerm_log_analytics_workspace.function_log_analytics.id
  application_type           = "web"
  internet_ingestion_enabled = false
  internet_query_enabled     = false
  retention_in_days          = 30
  daily_data_cap_in_gb       = 0.2
}
```

### Debug Output/Panic Output

```shell
I have a log file for this, but it contains sensitive information. I can share it privately.
```

### Expected Behaviour

Upon apply, and then plan, 

Plan: 0 to add, 0 to change, 0 to destroy.

### Actual Behaviour

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_windows_function_app.sync-function-app will be updated in-place
  ~ resource "azurerm_windows_function_app" "sync-function-app" {
      ~ app_settings                      = {
          + "APPLICATIONINSIGHTS_CONNECTION_STRING" = (sensitive)
            # (6 unchanged elements hidden)
        }
        # (25 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Steps to Reproduce

terraform apply
terraform plan

### Important Factoids

I have checked the azurerm_monitor_diagnostic_setting in the portal, and the connection string is not changing with each apply.

**Comment by ms-zhenhua** [comment]
Hi @boyfonz, thank you for reaching out.
According to this [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app#application_insights_connection_string), **APPLICATIONINSIGHTS_CONNECTION_STRING** is defined as a separate property of **application_insights_connection_string** in the provider. You could try to update your resource **azurerm_windows_function_app.sync-function-app** as below and run **terraform apply** for one time. Then the difference should disappear for future **plan**.

```
resource "azurerm_windows_function_app" "sync-function-app" {
  ...
  site_config {
    ...
    application_insights_connection_string = azurerm_application_insights.function_application_insights.connection_string
  }
}
```

**Comment by boyfonz** [comment]
Hi,

I changed my configuration as you suggested, and it DID stop terraform from repeatedly trying to change that new value.

However, I have a number of issues with the approach:

1) My application code expects there to be an app setting with this value
2) Replacing that value as you suggest led to an error in Azure that prevented the app function from starting:
System.Private.CoreLib: The network path as not found. : 'C:\home\site\wwwroot\host.json'.
3) What if I want to refer to that value elsewhere in my terraform setup?

I have a similar setting for a linux_web_app resource that does not exhibit the same problem when setting the APPLICATIONINSIGHTS_CONNECTION_STRING as an app setting.

This suggestion seems like a workaround rather than an explanation or a fix to me - I'd love some more detail or a different idea.

Thanks,

boyfonz

**Comment by boyfonz** [comment]
I've looked at this some more today and discovered that the System.Private.CoreLib: The network path as not found. : 'C:\home\site\wwwroot\host.json'. error was caused by sometbing unrelated. Deleting and recreating my function app solved it, and my code did indeed recognise the connection string using this method. I think this has solved my issue for now.

Thanks very much!
