### ISSUE TITLE
azurerm_firewall threat_intel_mode is missing "" option

### ISSUE THREAD

**Issue by rikunarhi-cloud2** [hashicorp/terraform-provider-azurerm#18505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall

### Terraform Configuration Files

```hcl
resource "azurerm_firewall" "vhub1-firewall" {
  name                = "xxxx"
  location            = azurerm_resource_group.rg_network.location
  resource_group_name = azurerm_resource_group.rg_network.name
  sku_name            = "AZFW_Hub"
  sku_tier            = "Standard"
  threat_intel_mode   = ""

  virtual_hub {
    virtual_hub_id  = azurerm_virtual_hub.vhub1.id
    public_ip_count = 1
  }

  firewall_policy_id = azurerm_firewall_policy.xxxxx.id

}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected threat_intel_mode to be one of [Off Alert Deny], got 
│ 
│   with azurerm_firewall.vhub1-firewall,
│   on fw-vhub.tf line 11, in resource "azurerm_firewall" "vhub1-firewall":
│   11:   threat_intel_mode   = ""
│ 
╵
```

### Expected Behaviour

Plan should successfully complete as the documentation has option for empty string. 

### Actual Behaviour

Gives error that the empty string isn't an option

### Steps to Reproduce

1. Terraform Plan

**Comment by wuxu92** [comment]
Hi, @rikunarhi-cloud2 thanks for your feedback! The Empty string value has been removed in azurerm 3.0. it's a document mistake and I have submitted a PR to fix the doc. Thanks again!
