### ISSUE TITLE
Inconsistent resource definition for azurerm_linux_web_app_slot

### ISSUE THREAD

**Issue by morufajibike** [hashicorp/terraform-provider-azurerm#18515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.23.0

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app_slot

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app_slot" "example" {
  name                = "example-linux-web-app-slot"
  app_service_name    = azurerm_linux_web_app.example.name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported argument
│ 
│   on ../../modules/webapp/main.tf line 79, in resource "azurerm_linux_web_app_slot" "this":
│   79:   resource_group_name     = local.resource_group_name
│ 
│ An argument named "resource_group_name" is not expected here.
╵
##[error]Error: The process '/opt/hostedtoolcache/terraform/1.2.3/x64/terraform' failed with exit code 1
```

### Expected Behaviour

Web app slot should be created in the provided resource group name.

### Actual Behaviour

An argument named "resource_group_name" is not expected here.

### Steps to Reproduce

The following page https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/web_app_active_slot#linux-web-app defines the resource `azurerm_linux_web_app_slot`

```
resource "azurerm_linux_web_app_slot" "example" {
  name                = "example-linux-web-app-slot"
  app_service_name    = azurerm_linux_web_app.example.name
  resource_group_name = azurerm_resource_group.example.name # Note this property
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}
}
```
and the following page https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app_slot defines the same resource with no `resource_group_name` property:

```
resource "azurerm_linux_web_app_slot" "example" {
  name           = "example-slot"
  app_service_id = azurerm_linux_web_app.example.id

  site_config {}
}
```

This first link indicates that the resource `azurerm_linux_web_app_slot` supports the property `resource_group_name` but that is not the case.

**Comment by xiaxyi** [comment]
Thanks @morufajibike for raising this issue.

You can track the fix in the mentioned pr.

**Comment by rcskosir** [comment]
@morufajibike Thank you for opening this issue. Thank you @xiaxyi for raising a PR to update the documentation to make the expected behavior of the provider clear. As such, I am going to close this issue. Please see PR #18524 to see the change.
