### ISSUE TITLE
Support for Databricks Access Connector

### ISSUE THREAD

**Issue by nkuln** [hashicorp/terraform-provider-azurerm#18518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Want to explore what is the work required to support Databricks Access Connector natively from `azurerm`

Currently, because the resource is not available from azurerm, we have to manage it through `azapi`.

```hcl
resource "azapi_resource" "ext_access_connector" {
  type      = "Microsoft.Databricks/accessConnectors@2022-04-01-preview"
  name      = "ext-databricks-mi"
  location  = data.azurerm_resource_group.this.location
  parent_id = data.azurerm_resource_group.this.id
  identity {
    type = "SystemAssigned"
  }
  body = jsonencode({
    properties = {}
  })
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_databricks_?

**Comment by favoretti** [comment]
@tombuildsstuff can we generate the SDK please? I can work on implementing this in provider.
