### ISSUE TITLE
azurerm_automation_software_update_configuration not accepting multiple update classifications

### ISSUE THREAD

**Issue by c-mckenzie** [hashicorp/terraform-provider-azurerm#18537]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.8

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automation_software_update_configuration" "example" {
  name                  = "example"
  automation_account_id = azurerm_automation_account.test.id
  operating_system      = "Windows"

  windows {
    classification_included = "Critical, Security"
    reboot                  = "IfRequired"
  }

  duration = "PT2H2M2S"
}
```

### Debug Output/Panic Output

```shell
│ Error: expected windows.0.classification_included to be one of [Critical Definition FeaturePack Security ServicePack Tools Unclassified UpdateRollup Updates], got Critical, Security
```

### Expected Behaviour

The plan should succeed with any combination of the possible classification values

### Actual Behaviour

The resource validation will only accept a single classification

### Steps to Reproduce

terraform plan

**Comment by wuxu92** [comment]
Hi @c-mckenzie thanks for your feedback, i think it's a by-design function that classification_included  only included only one classification as document described: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_software_update_configuration#classification_included

**Comment by c-mckenzie** [comment]
Hi @wuxu92 if the update configurations support multiple classifications why would the terraform resource limit it to only one by-design?
I can manually add more classifications after creating the configuration with terraform and then when running another plan it will correctly retrieve the current value with all the selected classifications

`      ~ windows {
          ~ classification_included         = "Critical, Security" -> "Critical"
            # (3 unchanged attributes hidden)
        }
`
It seems like the only thing stopping the terraform resource from working with more than one classification is its own validation logic

**Comment by wuxu92** [comment]
You are right I am missing a line in the service API definition. I'll try to submit a PR to fix this issue. Thanks for your feedback and your detailed information.
