### ISSUE TITLE
user_assigned_identity_id in azurerm_batch_pool.container_configuration.container_registries is optional according to the docs, but terraform requires it

### ISSUE THREAD

**Issue by fblampe** [hashicorp/terraform-provider-azurerm#18545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.19.0

### Affected Resource(s)/Data Source(s)

azurerm_batch_pool

### Terraform Configuration Files

```hcl
resource "azurerm_batch_pool" "pool" {
  name                = var.batch.pool.name
  account_name        = azurerm_batch_account.batch.name
  resource_group_name = azurerm_resource_group.rg.name
  node_agent_sku_id   = var.batch.pool.node_agent_sku_id
  vm_size             = var.batch.pool.vm_size
  max_tasks_per_node  = var.batch.pool.max_tasks_per_node

  storage_image_reference {
    offer     = var.batch.pool.storage_image_reference.offer
    publisher = var.batch.pool.storage_image_reference.publisher
    sku       = var.batch.pool.storage_image_reference.sku
    version   = var.batch.pool.storage_image_reference.version
  }

  fixed_scale {
    target_dedicated_nodes    = 0
    target_low_priority_nodes = var.batch.pool.target_node_count
  }

  network_configuration {
    public_address_provisioning_type = "BatchManaged"
    subnet_id                        = data.azurerm_subnet.subnet.id
  }

  container_configuration {
    container_image_names = []
    container_registries = [{
      registry_server = "${var.acr.name}.azurecr.io"
      user_name       = azurerm_container_registry.acr.admin_username
      password        = azurerm_container_registry.acr.admin_password
    }]
    type = "DockerCompatible"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Incorrect attribute value type
│
│   on main.tf line 45, in resource "azurerm_batch_pool" "pool":
│   45:     container_registries = [{
│   46:       registry_server = "${var.acr.name}.azurecr.io"
│   47:       user_name       = azurerm_container_registry.acr.admin_username
│   48:       password        = azurerm_container_registry.acr.admin_password
│   49:     }]
│     ├────────────────
│     │ var.acr.name is a string
│
│ Inappropriate value for attribute "container_registries": element 0: attribute "user_assigned_identity_id" is required.
```

### Expected Behaviour

`terraform plan/apply` should not throw any errors if a batch pool container registry has no user_assigned_identity_id configured.

With azurerm provider versions <3.19.0, this expected behavior was the case.

### Actual Behaviour

`terraform plan/apply` complains that `user_assigned_identity_id` is required, even though [the docs say otherwise](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool#password).

This happens with azurerm provider versions >=3.19.0.

Maybe the docs are just outdated, but since the resource can be created on Azure without the identity ID just fine with earlier versions of the provider, it looks to me that the requirement in newer versions is wrong.

### Steps to Reproduce

`terraform plan`

### References

Version 3.19.0 introduced `identity_reference` to `container_registries` via https://github.com/hashicorp/terraform-provider-azurerm/pull/17416, maybe that was the PR introducing the bug?

**Comment by liuwuliuyun** [comment]
Hi @fblampe I have tested similar config locally with latest version of provider, but when I do plan, no error is promoted. Here is my config.

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "testaccbatchyun"
  location = "yun"
}

resource "azurerm_container_registry" "test" {
  name                = "testregistryyun"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  sku                 = "Basic"
}

resource "azurerm_batch_account" "test" {
  name                = "testaccbatchyun"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
}

resource "azurerm_batch_pool" "test" {
  name                = "testaccpoolyun"
  resource_group_name = azurerm_resource_group.test.name
  account_name        = azurerm_batch_account.test.name
  node_agent_sku_id   = "batch.node.ubuntu 20.04"
  vm_size             = "Standard_A1"

  fixed_scale {
    target_dedicated_nodes = 1
  }

  storage_image_reference {
    publisher = "microsoft-azure-batch"
    offer     = "ubuntu-server-container"
    sku       = "20-04-lts"
    version   = "latest"
  }

  container_configuration {
    type                  = "DockerCompatible"
    container_image_names = ["centos7"]
    container_registries {
      registry_server = "myContainerRegistry.azurecr.io"
      user_name       = azurerm_container_registry.test.admin_username
      password        = azurerm_container_registry.test.admin_password
    }
  }
}

**Comment by liuwuliuyun** [comment]
I have checked code and as far as I can see `user_assigned_identity_id` is an optional property. It is only need to specified if no username and password is provided. So pretty weird error you have here.

**Comment by liuwuliuyun** [comment]
Could you try to remove [] `container_registries`? It is not needed here.

**Comment by dkuzmenok** [comment]
@liuwuliuyun And there is a test that is using a username `TestAccBatchPool_containerWithUser` and another one that tests UAMI `TestAccBatchPool_containerWithUAMI`.
