### ISSUE TITLE
azurerm_cdn_frontdoor_security_policy -> cdn_frontdoor_domain_id does not accept front door custom domain id

### ISSUE THREAD

**Issue by Tomasz-Kluczkowski** [hashicorp/terraform-provider-azurerm#18551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_security_policy

### Terraform Configuration Files

```hcl
I will see if I can construct a simple example.
```

### Debug Output/Panic Output

```shell
╷
│ Error: "domain" is invalid: the "security_policies.0.firewall.0.association.0.domain.0.cdn_frontdoor_domain_id" needs to be a valid Frontdoor Custom Domain ID or a Frontdoor Endpoint ID: [ID was missing the `afdEndpoints` element]
│ 
│   with azurerm_cdn_frontdoor_security_policy.webservices[0],
│   on fqdn.tf line 249, in resource "azurerm_cdn_frontdoor_security_policy" "webservices":
│  249:           cdn_frontdoor_domain_id = data.external.custom_domain_data.result.id
```

### Expected Behaviour

As per documentation (and as in the native az afd command) I am expecting this to be true:

> [cdn_frontdoor_domain_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_security_policy#cdn_frontdoor_domain_id) - (Required) The Resource Id of the Frontdoor Custom Domain or Frontdoor Endpoint that should be bound to this Frontdoor Security Policy. Changing this forces a new Frontdoor Security Policy to be created.

The Resource Id of the Frontdoor Custom Domain is usable as a cdn_frontdoor_domain_id.

### Actual Behaviour

The id of the azure front door custom domain is rejected and the provider mentions that `afdEndpoints` is missing in the ID - meaning it is expecting only ID for a front door profile endpoint. hence the `The Resource Id of the Frontdoor Custom Domain or Frontdoor Endpoint` is not true - the provider rejects custom domain id.

The format of the custom domain id I use is:

`/subscriptions/<our-subscription-id>/resourcegroups/<our-resource-group-name>/providers/Microsoft.Cdn/profiles/<azure-front-door-profile-name>/customdomains/<custom-domain-name>`

I have confirmed that this is the ID of the custom domain and that the association is working fine when using pure azure az afd commands to bind the firewall policy with front door profile and custom domain, unfortunately it does not work with terraform provider.

I fully understand that these are new resources and that work is being undertaken on introducing the missing front door resources but I think this problem will remain even if I create azure front door custom domain using terraform resource and not a azure cli command.

### Steps to Reproduce

Create azure front door custom domain for a azure front door profile using azure afd command (there is no terraform resource for that yet)
Read the id of the  custom domain using data source with a azure afd command showing details of created custom domain.
Use this custom domain id to create azurerm_cdn_frontdoor_security_policy -> domain -> cdn_frontdoor_domain_id
See that terraform provider reports error and demands afdEndpoints to be present in the domain id.

**Comment by WodansSon** [comment]
Hi @Tomasz-Kluczkowski, this is due to the casing of your custom domain ID:

**Expected Custom Domain Casing:**
/subscriptions/<our-subscription-id>/resourceGroups/<our-resource-group-name>/providers/Microsoft.Cdn/profiles/<azure-front-door-profile-name>/customDomains/<custom-domain-name>

**Your Custom Domain Casing:**
/subscriptions/<our-subscription-id>/resourcegroups/<our-resource-group-name>/providers/Microsoft.Cdn/profiles/<azure-front-door-profile-name>/customdomains/<custom-domain-name>

Notice that your `resource group` and `custom domain` segments casings differ from the expected Terraform casing. That said, since this is just a pass through value, I will go ahead and also and case insensitive resource ID logic to the validation function. That way it will work with any case that is passed in to the resource. Thanks for opening this issue! 🚀

**Comment by Tomasz-Kluczkowski** [comment]
Omg 😆 I swear to god, I stared at this thing for hours but never thought to diff ;)

Lesson learned - next time trust machine when comparing super long strings ;).

Thank you for actually checking this issue so fast!

Tom

On 28 Sep 2022, at 06:10, Wodans Son ***@***.***> wrote:

﻿

Hi @Tomasz-Kluczkowski<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTomasz-Kluczkowski&data=05%7C01%7C%7C0ba8fc1023b84cdce61408daa10fd162%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637999386546077855%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OVaGHisep53j8f6eRjp1g6Rri6GTXcjkmUbHXdQUX1k%3D&reserved=0>, this is due to the casing of your custom domain ID:

Expected Custom Domain Casing:
/subscriptions//resourceGroups//providers/Microsoft.Cdn/profiles//customDomains/

Your Custom Domain Casing:
/subscriptions//resourcegroups//providers/Microsoft.Cdn/profiles//customdomains/

Notice that your resource group and custom domain segments casings differ from the expected Terraform casing. That said, since this is just a pass through value, I will go ahead and also and case insensitive resource ID logic to the validation function. That way it will work with any case that is passed in to the resource. Thanks for opening this issue! 🚀

**Comment by WodansSon** [comment]
@Tomasz-Kluczkowski... no problem... been there, done that myself... Glad I could help. 🙂
