### ISSUE TITLE
Can't set postgresql_flexible_server pgbouncer.client_tls_sslmode parameter: StatusCode=500 -- Original Error: context deadline exceeded

### ISSUE THREAD

**Issue by holms** [hashicorp/terraform-provider-azurerm#18550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0 

### AzureRM Provider Version

3.2.4

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_configuration.pbs_config["pgbouncer.client_tls_sslmode"]

### Terraform Configuration Files

```hcl
variable "pbs_postgresql_config" {
  description = "PostgreSQL configurations to enable"
  type        = map(string)
  default = {
    "pg_qs.query_capture_mode" = "TOP"
    #"pg_qs.is_enabled_fs"                   = "on"
    "pg_qs.store_query_plans"               = "on"
    "pg_qs.max_plan_size"                   = "7500"
    "pg_qs.retention_period_in_days"        = "7"
    "pg_qs.track_utility"                   = "on"
    "pgms_wait_sampling.query_capture_mode" = "ALL"
    #"pg_qs.max_query_text_length"    = "6000"

    "pgbouncer.enabled"                   = "true"
    "pgbouncer.client_tls_sslmode"        = "ALLOW"
    "pgbouncer.ignore_startup_parameters" = "extra_float_digits"
    "pgbouncer.default_pool_size"         = "50"
    "pgBouncer.max_client_conn"           = "5000"
    "pgBouncer.pool_mode"                 = "TRANSACTION"
    "pgBouncer.min_pool_size"             = "1"
    "pgbouncer.query_wait_timeout"        = "120"

  }
}



resource "azurerm_postgresql_flexible_server_configuration" "pbs_config" {
  for_each  = var.pbs_postgresql_config
  name      = each.key
  server_id = azurerm_postgresql_flexible_server.pbs.id
  value     = each.value
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/holms/5dd9765a5da0928046887a516ad6efe3
```

### Expected Behaviour

This parameter is already created so it should've been just check for it's state. Worked a week ago with no problems.

I've also noticed that this param is gone on azure itself? So will the azure pgbouncer force to use ssl? Default param was to strict only to ssl connection. The opensource product that we're using doesn't support ssl in the pgsql golang driver itself. And pushing a pull request for such support will take ages.  
![screen](https://user-images.githubusercontent.com/280958/192647015-cb6ac8e2-06da-4023-ab39-c51018ee9f62.png)

### Actual Behaviour

Fails with error:

```
╷
│ Error: making Read request for Configuration (Subscription: "af30ce4f-65b9-4e38-b08b-cc960a9693c1"
│ Resource Group Name: "prebid"
│ Server Name: "pbs"
│ Configuration Name: "pgbouncer.client_tls_sslmode"): configurations.ConfigurationsClient#Get: Failure sending request: StatusCode=500 -- Original Error: context deadline exceeded
│ 
│   with azurerm_postgresql_flexible_server_configuration.pbs_config["pgbouncer.client_tls_sslmode"],
│   on azure-pgsql.tf line 90, in resource "azurerm_postgresql_flexible_server_configuration" "pbs_config":
│   90: resource "azurerm_postgresql_flexible_server_configuration" "pbs_config" {
```

### Steps to Reproduce

1. terraform plan

**Comment by aristosvo** [comment]
Hi @holms ! I would try two things:
- Ask Azure support, as this is a change in behavior of their resources
- Check how the resource behaves if you interact with it via `az` or Portal. Please don't do this on PRD:)

This doesn't seem Terraform related, although you are experiencing the results of the behavior of Azure via Terraform. As such I'll close this issue for now, if you've any reason to believe otherwise I'll be happy to reopen.
