### ISSUE TITLE
Azure FHIR Container Registry settings, cannot specify image

### ISSUE THREAD

**Issue by mclacore** [hashicorp/terraform-provider-azurerm#18552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_healthcare_fhir_service

### Terraform Configuration Files

```hcl
resource "azurerm_healthcare_fhir_service" "main" {
  name                          = "name"
  location                      = azurerm_resource_group.main.location
  resource_group_name           = azurerm_resource_group.main.name
  workspace_id                  = azurerm_healthcare_workspace.main.id
  kind                          = "fhir-R4"

  authentication {
    authority = "https://login.microsoftonline.com/tenant-id"
    audience  = "https://test.fhir.azurehealthcareapis.com"
  }

  identity {
    type = "SystemAssigned"
  }
  container_registry_login_server_url = "blahblah.azurecr.io"
}
```

### Debug Output/Panic Output

```shell
If I try to add the image to the end of the container registry URL, I get this:

│ Error: updating Fhir Service: (Name "fhir" / Workspace Name "fhir" / Resource Group "rg"): healthcareapis.FhirServicesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Login server 'blahblah.azurecr.io/test' is invalid. Login server must contain only letters or numbers in the head part with length 5 to 50 and tailed with '.azurecr.io', '.azurecr-test.io' or 'azurecr.us'."
```

### Expected Behaviour

Somehow I can specify the image(s) of ACR during configuration

### Actual Behaviour

I can't specify the image, just the URL. When I provision via the UI, I'm able to specify an image. When I deploy via Terraform, it doesn't select an image from ACR.

**Comment by aristosvo** [comment]
Hi @mclacore! The feature you are mentioning is something next to the `container_registry_login_server_url`. Within the portal it is shown as:
![Screenshot 2022-09-28 at 21 45 07](https://user-images.githubusercontent.com/8375124/192875205-efa18d8d-08ec-431c-8bed-0aa67844aa82.png)

To enable OCI artifacts functionality in `azurerm` it would require an extra input variable like i.e. `oci_artifact`:
```hcl
resource "azurerm_healthcare_fhir_service" "main" {
  name                          = "name"
  location                      = azurerm_resource_group.main.location
  resource_group_name           = azurerm_resource_group.main.name
  workspace_id                  = azurerm_healthcare_workspace.main.id
  kind                          = "fhir-R4"

  authentication {
    authority = "https://login.microsoftonline.com/tenant-id"
    audience  = "https://test.fhir.azurehealthcareapis.com"
  }

  identity {
    type = "SystemAssigned"
  }
  container_registry_login_server_url = "blahblah.azurecr.io"

  oci_artifact {
    container_registry =  "blahblah2.azurecr.io"
    image                      = "test"
    digest                      = "optionalDigest"
  }

  oci_artifact {
    container_registry =  "blahblah2.azurecr.io"
    image                      = "test2"
    digest                      = "optionalDigest"
  }
}
```

**Comment by aristosvo** [comment]
Working on it, btw ;)

**Comment by mclacore** [comment]
Ok. Will I need to wait on a new release to be able to use it?
