### ISSUE TITLE
azurerm_windows_web_app

### ISSUE THREAD

**Issue by adamcybersec** [hashicorp/terraform-provider-azurerm#18553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.24.0_x5

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app, azurerm_windows_function_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "this" {
  name = "my-rg01"
}

data "azurerm_service_plan" "linux_asp" {
  name                = "my-linux-asp01"
  resource_group_name = data.azurerm_resource_group.this.name
}

resource "azurerm_windows_web_app" "this" {
  location                = "australiaeast"
  name                    = "my-windows-web-app"
  resource_group_name     = data.azurerm_resource_group.this.name
  service_plan_id         = data.azurerm_service_plan.linux_asp.id

  site_config {}
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/adamcybersec/e9e7142718571e281c0b27c241361753
```

### Expected Behaviour

`azurerm_windows_web_app` and `azurerm_windows_function_app` providers should only deploy Windows based App Services and Function Apps.

If a Windows web app or function app is directed, based on the Terraform config, to deploy to an App Service Plan running Linux, the deployment should fail instead of deploying the apps as Linux apps and raising no flags or errors.

### Actual Behaviour

`azurerm_windows_web_app` and `azurerm_windows_function_app` providers both deploy 'successfully' to a **Linux based App Service Plan**, with kind: 'linux' which is not what is intended by using the azurerm_windows_xxx providers.

To be clear, attempting deployment of Windows Apps to a Linux based App Service Plan is a human error but Terraform happily deploys the `windows_web_app` and `windows_function_app` as Linux apps when the declarative intent and expectation is that a Windows app is what will be deployed.

`$ terraform state show azurerm_windows_web_app.this`

```
# azurerm_windows_web_app.this:
resource "**azurerm_windows_web_app**" "this" {
    ...
    kind                              = "app,**linux**"
    name                              = "my-windows-web-app"
    ...
```

### Steps to Reproduce

terraform apply

**Comment by xiaxyi** [comment]
Thanks @adamcybersec for raising this issue, the windows/ linux web/function app is using the same api client for app creation. We split the usage in terraform is just for better user experience. May I know the reason of using windows web app resource to create the linux app instance? Feel free to let me know your concerns. :)

**Comment by xiaxyi** [comment]
Hi @adamcybersec , good day, just would like to friendly follow up with you to see if you have any updates here?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is not something that we are able to add. The windows/ linux web/function app is using the same api client for app creation, as noted above.
Whilst I'd like to thank you for opening this issue as we have no plans to support this functionality I'm going to close this issue for the moment.
