### ISSUE TITLE
Azure Container Instance does not support Network Profile from 2021

### ISSUE THREAD

**Issue by epopa-ismg** [hashicorp/terraform-provider-azurerm#18574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.20.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
https://www.dropbox.com/s/adomznly8yph8ws/nodeapp.zip?dl=0
```

### Debug Output/Panic Output

```shell
https://gist.github.com/epopa-ismg/99b19caa5e1291c5b66f3930fadd4e5a
```

### Expected Behaviour

The process to finish and not to give Timeout for creation of Container Group resource.

### Actual Behaviour

The action to create Container group resource remains in loop because the resource will not successfully start. Based on our contact with Microsoft Azure Support they said the Network Profile was retired from 1st-July-2021 from their API and they are saying this is the cause of my issue.

I quote of what they said  "As we discussed over call, you mentioned that you are using the 'Network Profile' for deploying container groups to a virtual network. However, we would like to inform you that Network profiles have been retired as of the 2021-07-01 API version."

The MS support suggest to use VNET and SUBNET name or ID based on their documentation, but there is no option in the terraform provider resource to specify this. This is what they showed me as documentation related to Network profile: https://learn.microsoft.com/en-us/azure/container-instances/container-instances-virtual-network-concepts#network-profile

This is their suggestion from the email regarding on how to create the Container Instance:
```
Instead if you want to deploy to a new virtual network and have Azure create the network resources for you automatically, use the command:
 
az container create \
  --name appcontainer \
  --resource-group myResourceGroup \
  --image [mcr.microsoft.com/azuredocs/aci-helloworld](http://mcr.microsoft.com/azuredocs/aci-helloworld) \
  --vnet aci-vnet \
  --vnet-address-prefix 10.0.0.0/16 \
  --subnet aci-subnet \
  --subnet-address-prefix 10.0.0.0/24
 
 A link is shared for the reference
https://learn.microsoft.com/en-us/azure/container-instances/container-instances-vnet#deploy-to-new-virtual-network
```

### Steps to Reproduce

terraform init
terraform apply -auto-approve

**Comment by graememeyer** [comment]
It looks like this is in progress under https://github.com/hashicorp/terraform-provider-azurerm/pull/17785

**Comment by epopa-ismg** [comment]
Thank you, I didn't saw the Pull request with this change. I will wait for the documentation to update and then I will confirm to Azure Support as well that this was fixed as they are waiting for my answer as well.
