### ISSUE TITLE
Support for Java 17 in Azure Functions Linux and Windows

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#18575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Functions supports Java 17 in preview on dedicated, consumption, and premium plans for Windows and Linux.

https://azure.microsoft.com/en-us/updates/public-preview-java-17-support-in-azure-functions/

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_function_app, azurerm_linux_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    application_stack {
      java_version = "17"
    }
}

resource "azurerm_windows_function_app" "example" {
  name                = "example-windows-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    application_stack {
      java_version = "17"
    }
}
```

### References

https://azure.microsoft.com/en-us/updates/public-preview-java-17-support-in-azure-functions/

**Comment by abhishekjerry2000** [comment]
Can we have ETA on this?

**Comment by blueelvis** [comment]
Created a PR for this fix. Hoping for a quick merge!
