### ISSUE TITLE
Azure container registry task resource for scheduled purge does not recognize regex repository name filter

### ISSUE THREAD

**Issue by samjpv** [hashicorp/terraform-provider-azurerm#18584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.10.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_task

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "container_registry" {
  name                = var.container_registry_name
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "Standard"
  admin_enabled       = true

  lifecycle {
    ignore_changes = [tags]
  }
}

resource "azurerm_container_registry_task" "acr_weekly_purge_test" {
  name                  = "weeklyPurgeTest"
  container_registry_id = azurerm_container_registry.container_registry.id
  platform {
    os           = "Linux"
    architecture = "amd64"
  }
  encoded_step {
    task_content = <<EOF
      version: v1.1.0
      steps: 
        - cmd: mcr.microsoft.com/acr/acr-cli:0.4 purge --filter '.*:.*' --ago 30d --keep 20 --untagged
          disableWorkingDirectoryOverride: true
          timeout: 21600
    EOF
  }
  agent_setting {
    cpu = 2
  }
  base_image_trigger {
    name                        = "baseImageTrigger"
    type                        = "Runtime"
    enabled                     = true
    update_trigger_payload_type = "Default"
  }
  timer_trigger {
    name     = "noonSaturdayTrigger"
    schedule = "0 12 * * 6"
    enabled  = true
  }

  lifecycle {
    ignore_changes = [tags]
  }
}
```

### Debug Output/Panic Output

```shell
Debug logs didn't seem helpful for this particular issue after digging through them + I would need to omit a lot of private information. I can come up with some cleaned debug logs if someone deems it necessary.
```

### Expected Behaviour

An Azure Container Registry task should be created and should successfully purge all containers more than 20 or older than 30 days. **Note: Before I'm told this is an Azure issue and not a provider issue, it works locally using the Azure Container Registry CLI. This issue ONLY happens when creating the task via terraform.**

The configuration I'm using is referencing another github post that I've linked in references.

### Actual Behaviour

The purge task reads the registry name literally instead of as regex. This only happens for the registry name and not the image version, e.g.
```--filter 'repository:.*'```
 works, but
```--filter '.*:.*'```
and
```--filter 'prefix-.*:.*'```
do not. My initial assumption would be that there's something going on with the way the Azure API's are interacted with to create this task, but I'm not sure.

Task output after terraform creation:
6ac28caa25f2: Verifying Checksum
6ac28caa25f2: Download complete
6ac28caa25f2: Pull complete
527a2db38f69: Download complete
527a2db38f69: Pull complete
Digest: sha256:c61d4d91b72db340f0d0017f1d7de3dcfcdc127e7f5c03d379c0b428fa939154
Status: Downloaded newer image for mcr.microsoft.com/acr/acr-cli:0.4
**Deleting tags for repository: .***
**.* repository not found**
**Deleting manifests for repository: .***
**.* repository not found**

Number of deleted tags: 0
Number of deleted manifests: 0
2022/09/29 20:06:45 Successfully executed container: acb_step_0
2022/09/29 20:06:45 Step ID: acb_step_0 marked as successful (elapsed time in seconds: 1.670188)

Run ID: cfrs was successful after 5s

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14773

https://github.com/Azure/acr-cli/blob/main/cmd/acr/purge.go#:~:text=%2D%20Delete%20all%20tags%20that%20are%20older%20than%207,acr%20purge%20%2Dr%20example%20%2D%2Dfilter%20%22.*%3A.*%22%20%2D%2Dago%207d

https://learn.microsoft.com/en-us/azure/container-registry/container-registry-auto-purge#:~:text=%2D%2Dfilter%20%22.*/cache%3A.*%22

**Comment by Mitame** [comment]
@samjpv Could you try changing `mcr.microsoft.com/acr/acr-cli:0.4` to `mcr.microsoft.com/acr/acr-cli:0.5` (change the tag from 0.4 to 0.5)? I think there's still an issue with Terraform not sending _something_ correctly (based on some private output, it looks like the main irreconcilable difference is with the platform os being set to `Linux` instead of `linux`), but it might work around the issue in the short term?

**Comment by Mitame** [comment]
I've tested this on my setup now, and changing it to `0.5` works to solve the regex issue. 

Here's the resource I used

```terraform
resource "azurerm_container_registry_task" "daily_purge_prod_images" {
  name                  = "daily_purge_prod_images"
  container_registry_id = azurerm_container_registry.pacedocker.id

  agent_setting {
    cpu = 2
  }

  platform {
    architecture = "amd64"
    os           = "Linux"
    variant      = null
  }

  encoded_step {
    task_content = base64encode(yamlencode({
      version : "v1.1.0",
      steps : [
        {
          cmd : "mcr.microsoft.com/acr/acr-cli:0.5 purge --untagged --ago 7d --filter '*:[^0-9.]+$' --keep 3"
          disableWorkingDirectoryOverride : true,
          timeout : 3600
        }
      ]
    }))
    values = {}
  }

  timer_trigger {
    name     = "daily at 1AM"
    schedule = "0 1 * * *"
  }

  base_image_trigger {
    type                        = "Runtime"
    name                        = "defaultBaseimageTriggerName"
    update_trigger_payload_type = "Default"
  }
}
```
