### ISSUE TITLE
azurerm_firewall_policy.insights.log_analytics_workspace_id doesnt work

### ISSUE THREAD

**Issue by juicybaba** [hashicorp/terraform-provider-azurerm#18582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall_policy

### Terraform Configuration Files

```hcl
there is no speically code required, just feeding in log_analytics_workspace_id as per the document
```

### Debug Output/Panic Output

```shell
No error in Terraform but it doesn't work in Azure portal.
```

### Expected Behaviour

Policy Analytics is enabled.

### Actual Behaviour

Seeing below error in portal 

![Pasted Graphic 2](https://user-images.githubusercontent.com/79539850/193106542-45ba5397-95bb-4695-a2ff-22cfd3c377fa.png)

Seeing below error in Developer tool
```
{"error":{"code":"MissingSubscription","message":"The request did not have a subscription or a valid tenant level resource provider."}}
```

However, if I do an api call with postman and pass in resource id with all lower case, it works..... Below is the plan where terraform is attempting to revert the working config, and the only difference is the letter case, and there is a workspace id validation function in azurerm provider prevent me from using all lowcase resoruce id.

      ~ insights {
          ~ default_log_analytics_workspace_id = `"/subscriptions/<subscriptions_id>/resourcegroups/<rg_name>/providers/microsoft.operationalinsights/workspaces/<workspace_id>"` -> `"/subscriptions/subscriptions_id/resourceGroups/<rg_name>/providers/Microsoft.OperationalInsights/workspaces/<workspace_id>"`
            
        }

**Comment by juicybaba** [comment]
Any update for this issue?

**Comment by p4ranoidandro1d** [comment]
I think the problem is the way the "insights / log_analytics_workspace" is handled.

in my case, i dont want to set any additional workspaces per region. In that case the API is fine with an empty list.

from the terraform perspective, if we dont specify this parameter it sends null, which is allowed by the api but breaks the portal.
if we specify this parameter, it must ne one or multiple  blocks.

**Comment by juicybaba** [comment]
Any update for this issue?

**Comment by juicybaba** [comment]
issue has been resolved.
