### ISSUE TITLE
azurerm_cdn_frontdoor_profile_custom_domain - associated routes

### ISSUE THREAD

**Issue by evandeworp** [hashicorp/terraform-provider-azurerm#18598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.2.5

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_profile_custom_domain

### Terraform Configuration Files

```hcl
N/A since we're using azapi instead of azurerm to create these resources.
```

### Debug Output/Panic Output

```shell
Not possible to use azurerm_cdn_frontdoor_profile_custom_domain with our scenario of multiple routes sharing the same custom domain.
```

### Expected Behaviour

azurerm_cdn_frontdoor_profile_custom_domain has an optional attribute "associate_with_cdn_frontdoor_route_id" with description "The resource ID of the CDN FrontDoor Route this Custom Domain should be associated with." and "Once a CDN Front Door Custom Domain has been associated with a CDN Front Door Route changing this value will force a new CDN Front Door Custom Domain to be created."

The comments in [https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/cdn/cdn_frontdoor_custom_domain_resource.go](url)  regarding this attribute are:

			// NOTE: I need the reference to ensure the correct destroy order
			// this will also offload the task of maintaining the custom domain association
			// IDs in the route resource to the custom domains themselves...

The problem with the way azurerm_cdn_frontdoor_profile_custom_domain currently works is that it's possible to have multiple routes share the same custom domain like this:

![multiple_routes_sharing_same_custom_domain](https://user-images.githubusercontent.com/48076060/193327673-74128611-1003-41ac-9ad0-8cb35c7ca627.png)

Also, Azure let's you add and remove multiple routes to a custom domain without requiring the associated custom domain to ever be destroyed. Terraform shouldn't force us to destroy a custom domain if we want to add a new route.

I think it's necessary to do what the comments say you'd rather not do (maintain the custom domain association in the route resource). That's the logical place to maintain the domain association but i don't know how hard that is to do with Terraform/Go. Hopefully it can be done so we don't have to continue using azapi to create these routes.

**Comment by WodansSon** [comment]
@evandeworp thank you for opening this issue. I was not aware that you could associate a custom domain with more than one route so I originally implemented this incorrectly... my bad, sorry. 🙁 I will have a fix for this issue ready for the next release! 🚀
