### ISSUE TITLE
Join VM to Existing Domain  via extension throws error that "Extension with publisher 'Microsoft.Compute', type 'JsonADDomainExtension', and type handler version '1.3' for CPU Architecture 'x64' was not found in the extension repository

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform-provider-azurerm#18599]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

">=0.13"

### AzureRM Provider Version

">=3.0.0"

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl
#Extension: add server to domain
resource "azurerm_virtual_machine_extension" "vm3_ADD2AD" {
  for_each             = var.windows_vms
  name                 = "${var.vm3_name}-ADD2AD"
  virtual_machine_id   = azurerm_windows_virtual_machine.vm3.id
  publisher            = "Microsoft.Compute"
  type                 = "JsonADDomainExtension"
  type_handler_version = "1.3"
  tags                 = local.tags

  # NOTE: the `OUPath` field is intentionally blank, to put it in the Computers OU
  settings = <<SETTINGS
    {
        "Name": "${var.domainname}",
        "OUPath": "",
        "User": "${var.domainname}\\${var.domainusername}",
        "Restart": "true",
        "Options": "3"
    }
SETTINGS

  protected_settings = <<SETTINGS
    {
        "Password": "${var.domainpassword}"
    }
SETTINGS
  depends_on         = [azurerm_windows_virtual_machine.vm3]
}
```

### Debug Output/Panic Output

```shell
Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ExtensionNotFoundForCPUArchitecture" Message="Extension with publisher 'Microsoft.Compute', type 'JsonADDomainExtension', and type handler version '1.3' for CPU Architecture 'x64' was not found in the extension repository
```

### Steps to Reproduce

terraform apply

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension

**Comment by jodiecunningham** [comment]
I had a similar problem in the Az Powershell cmdlets.   In my case I had to set the extension name to "joindomain" . 

It looks like you're setting yours in your settings block as: "Name": "${var.domainname}"  

Can you retry just setting the name to "joindomain" ? 
You'll likely also have to add a line to your settings block to specify domainName.

**Comment by sahitya12** [comment]
@jodiecunningham  it worked thanks
