### ISSUE TITLE
Support for enable ms-support auditing

### ISSUE THREAD

**Issue by MichalSino** [hashicorp/terraform-provider-azurerm#18607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is not possibility to set "Enable Auditing of Microsoft support operations" and "Use different audit log destinations" through azurerm provider. Is it possible to add this feature to azurerm_mssql_server_extended_auditing_policy or create new resource like above? After creating resource we could set destination in diagnostic_settings (like with extended auditing policy).

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_server_mssupport_auditing_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_server_mssupport_auditing_policy" "example" {
  server_id                       = azurerm_mssql_server.example.id
  enabled                         = true
  log_monitoring_enabled          = true
  storage_endpoint                = azurerm_storage_account.example.primary_blob_endpoint
  storage_account_subscription_id = azurerm_subscription.primary.subscription_id
  retention_in_days               = 6
}

resource "azurerm_monitor_diagnostic_setting" "example" {
  name                       = "example"
  target_resource_id         = "${azurerm_mssql_server.example.id}/databases/master"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id

  log {
    category = "DevOpsAuditing"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }
}
```

**Comment by aristosvo** [comment]
I'll take a quick look!

**Comment by MichalSino** [comment]
Thanks. I forgot to write that it is relates to Azure mssql server :)

**Comment by aristosvo** [comment]
@MichalSino If you know how to build the provider yourselves locally, feel free to check out the PR and get a feel if this is working for you!

**Comment by MichalSino** [comment]
Thanks for quick reply. Unfortunately I've never written provider, so I don't know how to do it.

I've read this pull request and I think it is not full solution, because in cli we can use those 2 commands (and they do 2 different things, but similar):

This is what you mentioned:
az sql server audit-policy update -g ${data.azurerm_resource_group.rg.name} -n ${azurerm_mssql_server.server.name} --set isDevopsAuditEnabled=true --lats Enabled --lawr ${azurerm_log_analytics_workspace.law.id}

And this is what I found in docs:
az sql server ms-support audit-policy update --ids ${azurerm_mssql_server.server..id} --lats Enabled --lawri ${azurerm_log_analytics_workspace.law.id} --state Enabled

Someone from MS should write which one is correct. ;)

I don't know the difference, but second one works better in my case.

But thanks for reply. I will wait for this. :)

**Comment by aristosvo** [comment]
@MichalSino Thanks for your pointers! Enhanced the resource to a separate one, which indeed uses different APIs and works better.

I'll run some tests and add some docs, let's get it going!

**Comment by MichalSino** [comment]
@aristosvo great. I will wait for good news. :)

Thanks a lot.

**Comment by fcatacut** [comment]
> And this is what I found in docs: az sql server ms-support audit-policy update --ids azurermmssqlserver.server..id−−latsEnabled−−lawri{azurerm_log_analytics_workspace.law.id} --state Enabled

Regarding `az sql server ms-support audit-policy update`,

Auditing of Microsoft Support operations for your [logical server](https://learn.microsoft.com/en-us/azure/azure-sql/database/logical-servers?view=azuresql) allows you to audit Microsoft support engineers' operations when they need to access your server during a support request. The use of this capability, along with your auditing, enables more transparency into your workforce and allows for anomaly detection, trend visualization, and data loss prevention.

Source: [Auditing of Microsoft Support operations](https://learn.microsoft.com/en-us/azure/azure-sql/database/auditing-overview?view=azuresql#auditing-of-microsoft-support-operations) (September 2022)

**Comment by MichalSino** [comment]
I know what does it mean. :)

The question is which method is better to set up it and why. ;)

**Comment by fcatacut** [comment]
In the image below, `az sql server audit-policy update` configures the "Azure SQL Auditing" section while `az sql server ms-support audit-policy update` configures the "Auditing of Microsoft support operations" section, which is the one that you want based on your original description.

![image](https://user-images.githubusercontent.com/20847572/195516102-721eb710-fc9e-490c-abb2-24eb71d5c4d6.png)

**Comment by MichalSino** [comment]
As I said earlier I know it. :)

But we can also set it up using

az sql server audit-policy update -g ${data.azurerm_resource_group.rg.name} -n ${azurerm_mssql_server.server.name} --set isDevopsAuditEnabled=true --lats Enabled --lawr ${azurerm_log_analytics_workspace.law.id}

**Comment by fcatacut** [comment]
Looking at the [`az sql server audit-policy update`](https://learn.microsoft.com/en-us/cli/azure/sql/server/audit-policy?view=azure-cli-latest#az-sql-server-audit-policy-update) documentation and unless I'm missing something, none of its parameters will configure the destination for MS support operation _when "using different audit log destinations" is checked_. This is what you're asking for, right? If so, the only way to configure these would be with [`az sql server ms-support audit-policy update`](https://learn.microsoft.com/en-us/cli/azure/sql/server/ms-support/audit-policy?view=azure-cli-latest#az-sql-server-ms-support-audit-policy-update).

![image](https://user-images.githubusercontent.com/20847572/195539884-187fc58a-0756-49f8-8502-28e4ac289445.png)

**Comment by MichalSino** [comment]
So, you suggest to use first one if we want to enable Ms support auditing and second one if we want to change the destination of those logs, right?

**Comment by fcatacut** [comment]
To enable SQL auditing, you have to run `az sql server audit-policy update --state Enabled` specifying the audit logs destination.

If you want to enable the auditing of Microsoft support operations, I _think_ that you have to run the following: `az sql server ms-support audit-policy update -g mygroup -n myserver --state Enabled`. If you want to send the audit logs to a different destination, you'd have to specify additional parameters.

**Comment by MichalSino** [comment]
But what is isDevOpsauditEnabled=true for in
az sql server audit-policy update -g ${data.azurerm_resource_group.rg.name} -n ${azurerm_mssql_server.server.name} --set isDevopsAuditEnabled=true --lats Enabled --lawr

**Comment by fcatacut** [comment]
Azure CLI parameters are formatted in lower case characters and words are delimited by dashes whereas the code snippet that you provided is in camel case. What is the source of your snippet?

Note: There is a "Devops operations Audit Logs" log category for Azure SQL Databases.

![image](https://user-images.githubusercontent.com/20847572/195958167-cf57f592-c859-44cd-8181-62959bb26257.png)

**Comment by fcatacut** [comment]
There is a **_IsDevopsAuditEnabled_** property, but it's for the Azure SDK for .NET: <https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.sql.models.serverblobauditingpolicy.isdevopsauditenabled>.

**Comment by MichalSino** [comment]
> Azure CLI parameters are formatted in lower case characters and words are delimited by dashes whereas the code snippet that you provided is in camel case. What is the source of your snippet?
> 
> Note: There is a "Devops operations Audit Logs" log category for Azure SQL Databases.
> 
> ![image](https://user-images.githubusercontent.com/20847572/195958167-cf57f592-c859-44cd-8181-62959bb26257.png)

When you do "az sql server audit-policy update --ids sql-server-resource-id" there is property "isDevopsAuditEnabled": false and I changed it to true to set this
![image](https://user-images.githubusercontent.com/74066196/196166632-7ebd5dfe-0210-4da2-a9a1-447e61f0cc00.png)

But I understand that this should not be used to set ms-support auditing.
