### ISSUE TITLE
azure_container_group: Support Additional Volume types

### ISSUE THREAD

**Issue by lawrencegripper** [hashicorp/terraform-provider-azurerm#1860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

ACI support specifying different volume types. Currently only one of these is supported under the existing provider.  

Name | Type | Description | Supported in Provider
-- | -- | -- | --
azureFile | AzureFileVolume | The Azure File volume. | Yes
emptyDir | EmptyDirVolume | The empty directory volume. | No
gitRepo | GitRepoVolume | The git repo volume.| No
secret | object | The secret volume. | No

I want to add support (happy to submit as PR) for the secret volume type and am about to start looking at implementing it. Given the current code structure I'm not clear on the best approach, currently the provider has one `volume` type: 

``` golang 
"volume": {
	Type:     schema.TypeList,
	Optional: true,
	ForceNew: true,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"mount_path": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"read_only": {
				Type:     schema.TypeBool,
				Optional: true,
				ForceNew: true,
				Default:  false,
			},
			"share_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"storage_account_name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"storage_account_key": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
		},
	},          
```
One option is to add lots of option params to the existing volume structure. Adding fields for `secret_data`, `git_url` and a bool to enable empty dir but I think this would make the object quite confusing to use and be a tough one to validate. 

I think my preference would be to create a different, optional, item for each of the volume types, for example `secret_volume`. 

```golang 
"secret_volume": {
	Type:     schema.TypeList,
	Optional: true,
	ForceNew: true,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"mount_path": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"secret": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
		},
	},

"git_volume": {
	Type:     schema.TypeList,
	Optional: true,
	ForceNew: true,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"mount_path": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
			"git_url": {
				Type:     schema.TypeString,
				Required: true,
				ForceNew: true,
			},
		},
	},
					},
```

Does this seem like a sane plan?

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

Currently unclear. 

### References

* #853
* cc: @scottguymer 
* cc: @paulgrav

**Comment by lawrencegripper** [comment]
Have thought some more and have a third option which would be to more closely represent the API structure. This has one `volume` object with each type of volume being a child object. 

``` json
 "volumes": [
      {
        "name": "volume1",
        "azureFile": {
          "shareName": "shareName",
          "storageAccountName": "accountName"
        }
      },
      {
        "name": "volume2",
        "emptyDir": {}
      },
      {
        "name": "volume3",
        "secret": {}
      }
    ]
```

With this approach validation would be simple as if a volume has more than one child object it would be invalid

**Comment by lawrencegripper** [comment]
Going to look at getting an initial version of this PR done later this week, my current thinking it to go with my last suggestion, of a single `volume` object with sub-objects for each type. 

This keep things in line with the existing API and is hopefully nice and simple to use and validate without over complicating things. It should also making adding new volumes in the future trivial if/when new ones are release.

**Comment by lawrencegripper** [comment]
No problem, I've started playing with this approach but have hit a snag. In the existing provider the concepts of `volumes` and `volume_mounts` are condensed into one type `volume` and I believe this needs to be changed. 

In the API and ARM you define containers with named mounts, these define the path at which a volume will be mounted. Separately you define name volumes which are referenced by the mounts. 

The use case is that one azure share volume will be defined and used by multiple containers at different paths in the containers. 

The current TF provider doesn't provide this function and squishes both volume definitions and mounts into the container. 

I'm going to do some work to fix this with an aim of the following TF:

```terraform

resource "azurerm_container_group" "aci-example" {
  ....removed for example....

  volume {
    name       = "emptydir"
    mount_path = "/aci/emptydir"
    empty_dir {}
  }

  volume {
    name       = "gitrepo"
    mount_path = "/aci/gitrepo"
    git_repo {
      url = "https://github.com/Azure-Samples/aci-tutorial-sidecar"
    }
  }

  container {
    name     = "webserver"
    image    = "seanmckenna/aci-hellofiles"

    volume_mount {
      name       = "emptydir"
      mount_path = "/aci/empty"
      read_only  = false
    }

    volume_mount {
      name       = "gitrepo"
      mount_path = "/aci/gitrepo"
      read_only  = false
    }
  }

  container {
    name     = "sidecar"
    image    = "seanmckenna/aci-hellofiles"

    volume_mount {
      name       = "emptydir"
      mount_path = "/another_mount_point/empty"
      read_only  = false
    }

    volume_mount {
      name       = "gitrepo"
      mount_path = "/another_mount_point/gitrepo"
      read_only  = false
    }
  }

  tags {
    environment = "testing"
  }
}
```

**Comment by afdezl** [comment]
Implemented `emptyDir` volume type in #9836

**Comment by poz1** [comment]
@afdezl I think that #9836 is missing the creation of the volume in the group definition (to be shared among different containers), is it correct? (or am I missing something?)

**Comment by favoretti** [comment]
@poz1 Since this is somewhat related, but in essence is a separate issue, would you mind opening a fresh report for volume creation? This would allow us to address it sooner. I'm going to close this issue for now. Thank you!
