### ISSUE TITLE
azurerm_eventgrid_system_topic_event_subscription fails with eventhub

### ISSUE THREAD

**Issue by olivomarco** [hashicorp/terraform-provider-azurerm#18611]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

azurerm_eventgrid_system_topic_event_subscription; azurerm_eventhub

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-test"
  location = "westeurope"
}

resource "azurerm_storage_account" "sa" {
  name                     = "mystorageacc"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_eventgrid_system_topic" "eg" {
  name                   = "my-eventgrid"
  resource_group_name    = azurerm_resource_group.rg.name
  location               = "westeurope"
  source_arm_resource_id = azurerm_storage_account.sa.id
  topic_type             = "Microsoft.Storage.StorageAccounts"
}

resource "azurerm_eventhub_namespace" "eh" {
  name                = "myeventhub-ns"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"
}

resource "azurerm_eventhub" "eventhub" {
  name                = "myeventhub"
  namespace_name      = azurerm_eventhub_namespace.eh.name
  resource_group_name = azurerm_resource_group.rg.name
  partition_count     = 2
  message_retention   = 1
}

resource "azurerm_eventgrid_system_topic_event_subscription" "egs" {
    name                  = "eventgrid-subscription"
    system_topic          = azurerm_eventgrid_system_topic.eg.id
    resource_group_name   = azurerm_resource_group.rg.name
    event_delivery_schema = "EventGridSchema"
    eventhub_endpoint_id = azurerm_eventhub.eventhub.id
}
```

### Debug Output/Panic Output

```shell
│ Error: creating/updating System Topic Event Subscription: (Event Subscription Name "eventgrid-subscription" / System Topic Name "/subscriptions/REDACTED/resourceGroups/rg-test/providers/Microsoft.EventGrid/systemTopics/my-eventgrid" / Resource Group "rg-test"): eventgrid.SystemTopicEventSubscriptionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.EventGrid/systemTopics/subscriptions' under resource group 'rg-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
│
│   with azurerm_eventgrid_system_topic_event_subscription.egs,
│   on main.tf line 41, in resource "azurerm_eventgrid_system_topic_event_subscription" "egs":
│   41: resource "azurerm_eventgrid_system_topic_event_subscription" "egs" {
```

### Expected Behaviour

I am trying to create an EventGrid system topic event subscription to an eventhub endpoint. If done with the portal it works, when done with terraform it fails with the above error.
Expecting behavior of the portal.

### Actual Behaviour

Error message above

### Steps to Reproduce

terraform apply

**Comment by abuarbaz** [comment]
I think this might be related to the resources which you are creating using terraform and at the same time you are trying to create the subscription some how terraform is getting confused? Can you try to add. Also the second run should pass in this case if you are using the same state file.
 
resource "azurerm_eventgrid_system_topic_event_subscription" "egs" {
    name                  = "eventgrid-subscription"
    system_topic          = azurerm_eventgrid_system_topic.eg.id
    resource_group_name   = azurerm_resource_group.rg.name
    event_delivery_schema = "EventGridSchema"
    eventhub_endpoint_id = azurerm_eventhub.eventhub.id

depends_on = azurerm_eventhub.eventhub.id
}

**Comment by olivomarco** [comment]
Thank you, I checked and it's not that.
However, after further investigation, I found out that the line:

`system_topic          = azurerm_eventgrid_system_topic.eg.id`

was wrong. The right line should be:

`system_topic          = azurerm_eventgrid_system_topic.eg.name`

After fixing, it worked. Closing this issue, thank you.
