### ISSUE TITLE
maintenance_configuration_name conflicts with elastic_pool_id

### ISSUE THREAD

**Issue by peterprumbach-telekom** [hashicorp/terraform-provider-azurerm#18621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azure_mssql_database, azure_mssql_elasticpool

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "ep" {
  name                = var.resource_name
  resource_group_name = var.rg_name
  location            = var.location
  server_name         = var.sql_server_name
  max_size_gb         = var.elasticpool_max_size_gb

  maintenance_configuration_name = "SQL_GermanyWestCentral_DB_2"
  ...
}

resource "azurerm_mssql_database" "sqldb" {
  name            = var.resource_name
  server_id       = var.mssql_server_id
  elastic_pool_id = var.mssql_elastic_pool_id
  sku_name        = "ElasticPool"
  collation       = var.collation
  max_size_gb     = var.max_size_gb

  maintenance_configuration_name = "SQL_GermanyWestCentral_DB_2"
  ...
}
```

### Debug Output/Panic Output

```shell
Error: Conflicting configuration arguments
│
│   with module.XXX.azurerm_mssql_database.sqldb,
│   on ..\..\..\..\terraform_module\mssql-ep-database\main.tf line 9, in resource "azurerm_mssql_database" "sqldb":
│    9:   maintenance_configuration_name = "SQL_GermanyWestCentral_DB_2"
│
│ "maintenance_configuration_name": conflicts with elastic_pool_id
```

### Expected Behaviour

According to the Azure interface, the maintenance configuration window is inherited from the associated `azurerm_mssql_elasticpool` and the databases. In the elasitc pool, the `maintenance_configuration_name` could be set without any problems. Since Terraform recognises a change if the setting is not also set in the database, it is reset to the default value. Therefore, it should also be possible to set the `maintenance_configuration_name` in the `azurerm_mssql_database`.

### Actual Behaviour

`maintenance_configuration_name` cannot be set. There is a conflict with the `elastic_pool_id`. Therefore, the setting in the databases is always reset to the default value by terraform with terraform apply

### Important Factoids

Azure GermanyWestCentral

**Comment by rcskosir** [comment]
@peterprumbach-telekom Thank you for opening this issue, it appears that this issue should be resolved from v3.29.0 and newer which can be seen in the merged PR that @pierluca linked: #18321.
Thank you again for the collaboration. I am going to mark this issue as closed.
