### ISSUE TITLE
TF example for web_categories in application rules for azurerm_firewall_policy_rule_collection_group

### ISSUE THREAD

**Issue by jenka13all** [hashicorp/terraform-provider-azurerm#18623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I cannot get the "web_categories" of an application rule for a firewall policy rule collection group to work: I keep getting the error that the provided string is invalid. I am using the web categories provided by Microsoft under "liability":

https://learn.microsoft.com/en-us/azure/firewall/web-categories

The one-word entries work as is (e.g. "Gambling"), and I've been able to add some multiple-word entries by making them CamelCase without spaces. For instance, "Illegal Software" is accepted in TF as "IllegalSoftware". But there are entries that I haven't been able to map yet.

What is the mapping from Azure Firewall web categories to entries in "web_categories"? Could there be a table in the documentation, and/or an example as TF code?

### New or Affected Resource(s)/Data Source(s)

azurerm_firewall_policy_rule_collection_group.application_rule_collection.web_categories

### Potential Terraform Configuration

```hcl
# Application Rule Collection Group
resource "azurerm_firewall_policy_rule_collection_group" "firewall_policy_apprules" {
  provider           = azurerm.connectivity
  name               = "DefaultApplicationRuleCollectionGroup"
  firewall_policy_id = data.azurerm_firewall_policy.firewall_policy.id
  priority           = 300

  #Restrict web access by categories
  application_rule_collection {
    name     = "AVD-Deny-Inappropriate-Internet"
    priority = 199
    action   = "Deny"
    rule {
        name = "WebCategoriesRule"
        source_addresses = ["10.2.0.0/16"]
        web_categories = [
            "ChildAbuseImages",
            "Gambling",
            "HateAndIntolerance",
            "IllegalDrug",
            "IllegalSoftware",
            "Nudity",
            "PornographyOrSexuallyExplicit", # does not work
            "Violence",
            "Weapons"
        ]
        protocols {
          type = "Http"
          port = "80"
        }
        protocols {
          type = "Https"
          port = "443"
        }
    }
  }
}
```

**Comment by IgorOrmus** [comment]
Best way to figure out gaps in documentation I found is doing the changes on a resource manually and then running a plan against it to see the changes and referenced values in the plan output. For you question some of the examples came back as:

 ~ web_categories        = [
                  - "business",
                  - "alcoholandtobacco",
                  - "childinappropriate",
                  - "criminalactivity",
                  - "datingandpersonals",
                  - "politicsandlaw",
                  - "hateandintolerance",
                  - "lingerieandswimsuits",
                  - "pornographyandsexuallyexplicit",
                  - "schoolcheating",
                  - "sexeducation",
                  - "selfharm",
                  - "illegalsoftware",
                  - "illegaldrug",
                  - "peertopeer",
                  - "streamingmediaanddownloads",
                  - "downloadsites",
                  - "computersandtechnology",
                  - "forumsandnewsgroups",
                  - "healthandmedicine",
                  - "informationsecurity",
                  - "finance",
                  - "professionalnetworking",
                  - "privateipaddresses",
                  - "personalsites",
                  - "nonprofitsandngos",
                  - "searchenginesandportals",
                  - "webrepositoryandstorage",
                  - "webbasedemail",
                  - "instantmessaging",
                  - "socialnetworking",
                  - "leisureandrecreation",
                  - "natureandconservation",
                  - "greetingcards" ]

**Comment by jenka13all** [comment]
This is perfect - thank you!
