### ISSUE TITLE
Support for Automation rule incident `Updated` trigger in sentinel

### ISSUE THREAD

**Issue by deepanshumarwah** [hashicorp/terraform-provider-azurerm#18620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the automation rule has only 1 trigger `created` in terraform provider for  azure. In order to perform additional operations, we need to have `updated` workflow in the provider. 

https://github.com/hashicorp/terraform-provider-azurerm/blob/b1f893fdbf8757104d0bd89a98aabfb1a8c95491/internal/services/sentinel/sentinel_automation_rule_resource.go#L309-L310

Currently we dont have that option in provider, as it was pending on Microsoft to release go SDK with additional enum which is finally released by Microsoft recently.

https://github.com/Azure/azure-sdk-for-go/issues/18992#issuecomment-1264585290

### New or Affected Resource(s)/Data Source(s)

azurerm_sentinel_automation_rule

**Comment by deepanshumarwah** [comment]
Hi @tombuildsstuff , 

Can you please help me to put this into priority ? Thank you.

**Comment by deepanshumarwah** [comment]
@magodo : can you please help us out on this request ?

**Comment by magodo** [comment]
@deepanshumarwah Sure, I'll update the code to reflect the new enums shortly, as #19161 has been merged now.

**Comment by GerardSetho** [comment]
Hi @magodo ! Any idea when `TriggersWhenUpdated` will be used in the _sentinel_automation_rule_resource.go_?

This was added to the SDK recently:
https://github.com/hashicorp/go-azure-sdk/blob/a0184b4cba76bd45f95bfc65c3e565cc1114ad1a/resource-manager/securityinsights/2022-11-01/automationrules/constants.go#L645
