### ISSUE TITLE
Support for azurerm_firewall sku_tier=Basic

### ISSUE THREAD

**Issue by afdezl** [hashicorp/terraform-provider-azurerm#18648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow setting `sku_tier` as `Basic`. This is a new tier released in public preview as of 04/10/2022.
https://azure.microsoft.com/en-us/blog/azure-firewall-basic-now-in-preview/

### New or Affected Resource(s)/Data Source(s)

azurerm_firewall

### Potential Terraform Configuration

```hcl
resource "azurerm_firewall" "main" {
  name                = "example-firewall"
  location            = var.location
  resource_group_name = var.resource_group_name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Basic"

  tags = var.tags

  ip_configuration {
    name                 = "configuration"
    subnet_id            = data.azurerm_subnet.firewall.id
    public_ip_address_id = azurerm_public_ip.example.id
  }
}
```

### References

https://azure.microsoft.com/en-us/blog/azure-firewall-basic-now-in-preview/

**Comment by wuxu92** [comment]
Hi @afdezl, thanks for your feedback. This SKU Tire has been supported from PR https://github.com/hashicorp/terraform-provider-azurerm/pull/16989 but misses the document. I'll submit a PR to fix the document
