### ISSUE TITLE
API Management Delegation is not able to be configured in Terraform

### ISSUE THREAD

**Issue by byunru** [hashicorp/terraform-provider-azurerm#18644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

why this issue been closed ?
https://github.com/hashicorp/terraform-provider-azurerm/issues/4423

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management, ...

**Comment by aristosvo** [comment]
I'll give this a try
