### ISSUE TITLE
Issue with rewrites in the gateway

### ISSUE THREAD

**Issue by elvovsky** [hashicorp/terraform-provider-azurerm#18655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13

### AzureRM Provider Version

2.80

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
rewrite_rule_set {
    name = "edistribution"

    rewrite_rule {
      name          = "redirect-edistribution"
      rule_sequence = 100
      url  {
        path = "/exp/edistribution/v1/api/Invoices/pdf"
        reroute   = "false"
        query_string = ""
      
      }
    }
  }
```

### Debug Output/Panic Output

```shell
The output does not show any errors.
```

### Expected Behaviour

It does create a set and the rule. I expect it to have rewrite type "URL" with the component being URL path

### Actual Behaviour

when the tf runs it creates type url, but component is "Both URL path and URL query string"

**Comment by ms-zhenhua** [comment]
Hi @elvovsky, if you only want to use **path** in **url**, you could try to set the [components](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#components) as **path_only** , the configuration may look like below:
```
url  {
    path = "/exp/edistribution/v1/api/Invoices/pdf"
    reroute   = "false"
    components = "path_only"
}
```

**Comment by elvovsky** [comment]
Hello @ms-zhenhua . Thank you ! I will try it. Not sure how I missed that in the documentation. I will post the results as soon as I had a chance to try

**Comment by ms-zhenhua** [comment]
Hi @elvovsky, the `components` was imported in v3.19.0 by this [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/13899) which is used to resolve the similar issues which you met. And I am afraid I do not find any work around way in the older version.

**Comment by elvovsky** [comment]
Thanks @ms-zhenhua ! I will check if this works, I would need to make sure there is no issues with other elements, as it would be a big jump in version of azurerm. I will let you know .

**Comment by elvovsky** [comment]
Hello @ms-zhenhua ! I changed the script to use 3.19, then I got some other errors with protocol, whiche were also related to the version of the azurerm provider. Once I fixed that I got a different error , which was related to request routing rile having priority now as a required field, which was not required before. Now after I added priority, I get another error, which also only shows up in apply and not in plan. The error is 
**Error: expanding `request_routing_rule`: If you wish to use rule priority, you will have to specify rule-priority field values for all the existing request routing rules.** 
The line it is referencing is the definition of the app gateway resource.  Can you help guiding me in the right direction here, as unless I get passed all these other issues, I can't really test of the original problem is solved
