### ISSUE TITLE
Support for workload identity addon on AKS

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#18666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Following https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster, the workload identity addon in addition to the OIDC issuer is required on AKS to use it.

Quote from az cli
```
    --enable-workload-identity                    : Enable workload identity addon.  Allowed values:
                                                    false, true.
```

Currently, its not possible to enable this through terraform.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "jok" {
  workload_identity_enabled = true
}
```

### References

 https://learn.microsoft.com/en-us/azure/aks/workload-identity-deploy-cluster

**Comment by stephybun** [comment]
Thanks for raising this issue @jkroepke. AFAIK workload identity is synonymous with Pod Identity v2 which is being tracked in #9885. Please subscribe to #9885 for updates.

Thanks!
