### ISSUE TITLE
Unable to assign role to system managed identity -- KeyVault

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#18686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "syn_kv" {
  name                       = "kvtest"
  location                   = var.location
  resource_group_name        = var.rg_name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = var.kv_sku_name
  soft_delete_retention_days = 90
  enable_rbac_authorization  = true
  purge_protection_enabled    = true


  network_acls {
    default_action             = "Deny"
    ip_rules                   = []
    virtual_network_subnet_ids = []
    bypass                     = "None"
  }

  tags = var.tags
}


resource "azurerm_role_assignment" "rbac_assignment_reader" {
   scope                = azurerm_key_vault.syn_kv.id
   role_definition_name = "Key Vault Reader"
   principal_id         = azurerm_key_vault.syn_kv.identity[0].principal_id
}
```

### Debug Output/Panic Output

```shell
Error: Unsupported attribute
│ 
│   on ../modules/key-vault/main.tf line 41, in resource "azurerm_role_assignment" "rbac_assignment_reader":
│   41:   principal_id         = azurerm_key_vault.syn_kv.identity[0].principal_id
│ 
│ This object has no argument, nested block, or exported attribute named "identity"
```

### Expected Behaviour

It should create key vault and create role assingment

### Actual Behaviour

 Error: Unsupported attribute
│ 
│   on ../modules/key-vault/main.tf line 41, in resource "azurerm_role_assignment" "rbac_assignment_reader":
│   41:   principal_id         = azurerm_key_vault.syn_kv.identity[0].principal_id
│ 
│ This object has no argument, nested block, or exported attribute named "identity"

### Steps to Reproduce

terraform apply

**Comment by ziyeqf** [comment]
HI @onenessboy , thanks for opening the issue.

As the error message showed, `azurerm_key_vault` did not have an exported block or arguments named identity because the Key Vault resource is where the credentials storage.
the `principal_id` property of `azurerm_role_assignment` should be the id of a service-principal, it could come from the identity of the resource which need to read the Key Vault rather than the Key Vault itself. But according to the description , I'm not sure which principal you want to grant the permission.

If it helps or any further questions please leave comments.

**Comment by onenessboy** [comment]
> HI @onenessboy , thanks for opening the issue.
> 
> As the error message showed, `azurerm_key_vault` did not have an exported block or arguments named identity because the Key Vault resource is where the credentials storage. the `principal_id` property of `azurerm_role_assignment` should be the id of a service-principal, it could come from the identity of the resource which need to read the Key Vault rather than the Key Vault itself. But according to the description , I'm not sure which principal you want to grant the permission.
> 
> If it helps or any further questions please leave comments.

@ziyeqf Thanks for reply. Actually it is not for service principal. its needed --role assignment of Secrets Reader for the azure synapse workspace managed identity. How to grant it

**Comment by ziyeqf** [comment]
@onenessboy Please try the following config if it can meet the requirement.
```Terraform
resource "azurerm_key_vault" "syn_kv" {
...
  enable_rbac_authorization  = true
...
}

resource "azurerm_synapse_workspace" "example" {
...
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "rbac_assignment_reader" {
   scope                = azurerm_key_vault.syn_kv.id
   role_definition_name = "Key Vault Reader"
   principal_id         = azurerm_synapse_workspace.example.identity[0].principal_id
}
```

**Comment by onenessboy** [comment]
> 
@ziyeqf thanks again, but I am using differenct module for synapse workspace. in that case, how to refer to synapse modules principal id here.. is that principal_id = module.synapse_ws.azurerm_synapse_workspace.example.identity[0].principal_id ?

**Comment by ziyeqf** [comment]
@onenessboy you are welcome, the `principal_id` is not the id of `azurerm_synapse_workspace` and I may suggest to put the principal_id into an output item
```Terraform
#in the synapse module
output "principal_id" {
    value = azurerm_synapse_workspace.example.identity[0].principal_id
}
```
then it could be used like other output values
```Terraform
#in the Key Vault module
resource "azurerm_role_assignment" "rbac_assignment_reader" {
...
   principal_id         = module.<module name>.principal_id
}
```

**Comment by onenessboy** [comment]
@ziyeqf thank you its working now.. hence closing issue
