### ISSUE TITLE
azurerm_management_group_policy_assignment doesn't accept names over 24 characters long

### ISSUE THREAD

**Issue by dhep27** [hashicorp/terraform-provider-azurerm#18682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.26

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_assignment

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~>1.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.26.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_policy_definition" "policy_definition" {
    name                = "Enforce Azure Regions"
    policy_type         = "Custom"
    mode                = "All"
    display_name        = "Enforce Azure Regions"
    description         = "This policy enforces allowed Azure regions for resources"
    management_group_id = "/providers/Microsoft.Management/managementGroups/test"
    policy_rule         = <<POLICY_RULE
      { 
        "if": {
              "not": {
                  "field": "location",
                  "in": "[parameters('allowedLocations')]"
                }
              },
          "then": {
            "effect": "deny"
          }
      }
      POLICY_RULE
    metadata            = <<METADATA
        {
          "metadata" : "Sample metadata here"
        }
      METADATA
    parameters          = <<PARAMETERS
        {
          "allowedLocations": {
            "type": "Array",
            "metadata": {
              "description": "The list of allowed locations for resources.",
              "displayName": "Allowed locations",
              "strongType": "location"
            }
          }
        }
      PARAMETERS
}

resource "azurerm_management_group_policy_assignment" "management_group_assignment" {
  name = join("-",
    [
      "assign",
      azurerm_policy_definition.policy_definition.name
    ]
  )
  policy_definition_id = azurerm_policy_definition.policy_definition.id
  management_group_id  = "/providers/Microsoft.Management/managementGroups/test"
  parameters           = azurerm_policy_definition.policy_definition.parameters
}
```

### Debug Output/Panic Output

```shell
terraform plan
module.azure-policy.data.azurerm_subscription.current: Reading...
module.azure-policy.data.azurerm_subscription.current: Read complete after 0s [id=/subscriptions/<REDACTED>]
╷
│ Error: expected length of name to be in the range (3 - 24), got assign-Enforce Azure Regions
│
│   with module.azure-policy.azurerm_management_group_policy_assignment.management_group_assignment["Enforce Azure Regions"],
│   on tf-az-module-azure-policy\policyassignment.tf line 9, in resource "azurerm_management_group_policy_assignment" "management_group_assignment":
│    9:   name = join("-",
│   10:     [
│   11:       "assign",
│   12:       each.value.name
│   13:     ]
│   14:   )
│
```

### Expected Behaviour

The Assignment should have been created at Management Group level.  This behaviour does not occur for Subscription or Resource Group level Policy Assignments.

### Actual Behaviour

The Terraform Plan fails due to the name of the Management Policy Assignment exceeding 24 characters.

### Steps to Reproduce

terraform plan

### Important Factoids

Creating an Azure Policy Assignment at Management Group level with a name over 24 characters works in the Azure Portal

**Comment by jquinn99002** [comment]
Is there any update when this might be resolved as it makes it very hard to give clear names to policy assignments to management groups

**Comment by fll1119** [comment]
Is there any plans to get this one resolved? There is no such limit allocated in the portal - only arises when using Terraform

**Comment by marevers** [comment]
Also adding this: this limit is completely arbitrary in Terraform as the portal very well allows assignments that are much longer than 24 characters.
