### ISSUE TITLE
ADF to DB connectivity is not working when tenant_id is provided in LS configuration - azurerm_data_factory_linked_service_azure_sql_database

### ISSUE THREAD

**Issue by JaydeepUniverse** [hashicorp/terraform-provider-azurerm#18681]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.3

### AzureRM Provider Version

v3.13.0

### Affected Resource(s)/Data Source(s)

Azure data factory, SQL Database

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory_linked_service_azure_sql_database" "sqldatabase_linked_service_10102022" {
  count = (var.subResourcesInfo.sqlDatabaseName != "") ? 1 : 0
  depends_on = [azurerm_data_factory_integration_runtime_azure.autoresolve_integration_runtime,
  azurerm_data_factory_managed_private_endpoint.sqlserver_managed_endpoint]

  name            = "AzureSqlDatabase10102022"
  data_factory_id = azurerm_data_factory.datafactory.id

  integration_runtime_name = "AutoResolveIntegrationRuntime"
  use_managed_identity     = true
  connection_string = format("Integrated Security=False;Data Source=%s.database.windows.net;Initial Catalog=%s;",
    var.subResourcesInfo.sqlServerName,
  var.subResourcesInfo.sqlDatabaseName)
}
```

### Debug Output/Panic Output

```shell
Will get it soon
```

### Expected Behaviour

Issue is ADF to DB connectivity, error:

Operation on target DWH_DF_aaa failed: {'StatusCode':'DFExecutorUserError','Message':'Job failed due to reason: com.microsoft.dataflow.broker.InvalidOperationException: Only one valid authentication should be used for AzureSqlDatabase. ServicePrincipalAuthentication is invalid. One or two of servicePrincipalId/key/tenant is missing.','Details':''}
 
When we created this LS using TF, we get tenant="" in ADF LS Json file which we suspect that causing issue of above error. 

When we created the same LS directly on ADF UI, then there is no field of tenant="" in its json file, and if we use this LS in dataflow/pipeline then communication works from ADF to DB.

Expected behavior should be, if we don't provide tenant_id parameter in TF code then in json also should not show tenant="" which then works for connectivity.

**Comment by JaydeepUniverse** [comment]
Hello, is there anyone looking into this issue?

**Comment by JaydeepUniverse** [comment]
> I think this is the same as #14577

Yes it is. Thanks for linking. I see no answer on https://github.com/hashicorp/terraform-provider-azurerm/issues/14577 as well, it was reported 1 year back. Hopefully will get reply very soon.

**Comment by rcskosir** [comment]
@JaydeepUniverse Thank you for opening this issue, and thank you @fmms for finding the related issue #14577.
We try to keep only 1 issue open for a given topic/bug to consolidate effort and updates, so I ask for you to please subscribe to the older issue #14577 and use the 👍 to indicate you are also facing the same issue.
As such, I am going to close this issue as a duplicate.
