### ISSUE TITLE
Data Source: azurerm_shared_image_version outputs random version ID

### ISSUE THREAD

**Issue by AravindaHD** [hashicorp/terraform-provider-azurerm#18718]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.5

### AzureRM Provider Version

3.26.0

### Affected Resource(s)/Data Source(s)

resource "azurerm_linux_virtual_machine" "linux_vm"

### Terraform Configuration Files

```hcl
variable "shared_image" {
default = {
gallery_name = "XXXXXXXXX"
gallery_resource_group = "XXXXXXXXX"
image_name = "XXXXXXXXX"
"version" = "latest"
}
}

data "azurerm_shared_image_version" "shared_image" {
name = var.shared_image.version
resource_group_name = var.shared_image.gallery_resource_group
gallery_name = var.shared_image.gallery_name
image_name = var.shared_image.image_name
}

resource "azurerm_linux_virtual_machine" "linux_vm" {
...
source_image_id = data.azurerm_shared_image_version.shared_image.id
... (other parameters)
}
```

### Debug Output/Panic Output

```shell
Will obtain the debug info if necessary
```

### Expected Behaviour

ID of the latest version of the specified image should be used for creating the VM.

### Actual Behaviour

ID of the latest version of the specified image should be used, but some random version of the image is being used for creating the vm.

Below is the output of terraform plan

resource "azurerm_windows_virtual_machine" "windows_vm" {
...
source_image_id = "/subscriptions/XXXXXXXX/resourceGroups/XXXXXXXXXX/providers/Microsoft.Compute/galleries/XXXXXXXXXX/images/XXXXXXXXXX/versions/1.0.9"
...
}

### Steps to Reproduce

terraform init
terraform plan

**Comment by Amier3** [comment]
Hey @AravindaHD 

Is version 1.09 of the shared image the latest published image? using the "latest" name tag in the data source fetches the latest version of the shared image, not necessarily the version titled " latest".

**Comment by AravindaHD** [comment]
Hi @Amier3 1.0.9 is not the latest version. The Latest version is 1.0.14 I checked multiple times with different codes for creating different instances. It's just picking up the old versions of image.

FYI- The version titled "latest" is also 1.0.14

**Comment by myc2h6o** [comment]
Hi @AravindaHD I think you can try setting `sort_versions_by_semver = true` in `data.azurerm_shared_image_version` https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/shared_image_version#sort_versions_by_semver. The version list returned by Azure is sorted by string so `"9"` is larger than `"14"`. `sort_versions_by_semver` is introduced to sort the versions by version number.

**Comment by AravindaHD** [comment]
Hi all, Thank you for your quick response and providing the resolution. I tried the above method. Now It's picking up the latest image.
