### ISSUE TITLE
Azure Firewall Policy: Error when using tags with Uppercase letters

### ISSUE THREAD

**Issue by larsmaes-sogeti** [hashicorp/terraform-provider-azurerm#18719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.23.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall_policy

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy" "base_policy" {
  name                = "afwp-base-policy-${var.environment}-${local.short_location}-001"
  resource_group_name = var.virtual_network_resource_group_name
  location            = var.location

  tags = {
    UpperCase = "Tags with Cased Keys"
}
```

### Debug Output/Panic Output

```shell
None
```

### Expected Behaviour

Apply tags on policy

### Actual Behaviour

Error: a tag key "UpperCase" expected to be all in lowercase

### Steps to Reproduce

1. terraform apply

### References

This line seems to be the culprit:
https://github.com/hashicorp/terraform-provider-azurerm/blob/a6f0a06fa91e0412b8e3939e3778d43c3cd13cd4/internal/services/firewall/firewall_policy_resource.go#L929

**Comment by Amier3** [comment]
Hey @larsmaes-sogeti 

Thanks for the prompt PR, hopefully we'll be able to get that merged in shortly :)
