### ISSUE TITLE
azurerm_linux_web_app should allow python 3.10

### ISSUE THREAD

**Issue by dimbleby** [hashicorp/terraform-provider-azurerm#18726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.26.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "treasure" {
  ...
  site_config {
    application_stack {
      python_version = "3.10"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected site_config.0.application_stack.0.python_version to be one of [3.7 3.8 3.9], got 3.10
```

### Expected Behaviour

should have configured a web app with python 3.10 as the stack

### Actual Behaviour

failed with output as above

### Steps to Reproduce

`terraform apply`

### Important Factoids

evidence that azure supports this:
```
$ az webapp list-runtimes --os linux | grep PYTHON
  "PYTHON:3.10",
  "PYTHON:3.9",
  "PYTHON:3.8",
  "PYTHON:3.7",
```

**Comment by xiaxyi** [comment]
Thanks @dimbleby for raising this issue, let me check and will submit a pr once confirmed
