### ISSUE TITLE
Incorrect argument type for destination_ports on nat_rule_collection's

### ISSUE THREAD

**Issue by rwgnr** [hashicorp/terraform-provider-azurerm#18725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall_policy_rule_collection_group, azurerm_firewall_nat_rule_collection

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_firewall_policy" "example" {
  name                = "example-fwpolicy"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}

resource "azurerm_firewall_policy_rule_collection_group" "example" {
  name               = "example-fwpolicy-rcg"
  firewall_policy_id = azurerm_firewall_policy.example.id
  priority           = 100

  nat_rule_collection {
    name     = "nat_rule_collection1"
    priority = 300
    action   = "Dnat"
    rule {
      name                = "nat_rule_collection1_rule1"
      protocols           = ["TCP", "UDP"]
      source_addresses    = ["10.0.0.1", "10.0.0.2"]
      destination_address = "192.168.1.1"
      destination_ports   = ["80", "1000-2000"]
      translated_address  = "192.168.0.1"
      translated_port     = "8080"
    }
  }
}
```

### Debug Output/Panic Output

Attempting to provide a multi-value list
```shell
Error: creating Firewall Policy Rule Collection Group "example-fwpolicy-rcg" (Resource Group "example-resources" / Policy: "example-fwpolicy"): network.FirewallPolicyRuleCollectionGroupsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="FirewallPolicyNatRuleInvalidDnatMultipleDestinationPortsExists" Message="Firewall Policy Nat Rule Collection: nat_rule_collection1 Rule: nat_rule_collection1_rule1 has Multiple Destination Ports on a DNAT Rule. This is not supported, please set only 1 destination port on this rule."
```

Attempting to provide a string 
```
Inappropriate value for attribute "destination_ports": list of string
````

### Expected Behaviour

According to the current Terraform documentation, you should be able to provide a list of multiple destination ports for NAT rule's destination_ports argument

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group#destination_ports

### Actual Behaviour

In practice, you can _not_ have more than 1 value in the list otherwise it will error out as DNAT rules in Azure do not accept more than 1 destination port, additionally terraform will not validate a string argument even though this can only ever be 1 value (shouldn't be a list)

Good
`destination_ports = ["80"]`

Bad
`destination_ports   = ["80", "1000-2000"]`
`destination_ports = "80"`

### Steps to Reproduce

1. `terraform validate`
2. `terraform apply`

### Important Factoids

N/A

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group#destination_ports

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_nat_rule_collection#destination_ports

**Comment by wuxu92** [comment]
Hi, @rwgnr thanks for your feedback, it looks like a limitation from the server side, I'm not sure if it exists in the first place or from someday after azurerm releases this feature. anyway, I have submitted a PR to add a limit to this property to expose this error in the `terraform plan` stage.
