### ISSUE TITLE
Support for the addition of attributes primary_key and service_endpoint for azurerm_fluid_relay_server

### ISSUE THREAD

**Issue by samsym1** [hashicorp/terraform-provider-azurerm#18755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to be able to access the primary_key and service_endpoint as attributes for azurerm_fluid_relay_server resource.

Accessing primary key as an attribute for storage in a keyvault. 

As per Microsoft the GA version of @fluidframework/azure-client and fluid-framework makes use of service_endpoint. 
"In the latest package, you will need to update your serviceConfig object to the new Azure Fluid Relay service endpoint instead of the storage and orderer endpoints"

### New or Affected Resource(s)/Data Source(s)

azurerm_fluid_relay_server

### Potential Terraform Configuration

```hcl
azurerm_fluid_relay_server.this.service_endpoints
azurerm_fluid_relay_server.this.primary_key
```

**Comment by wuxu92** [comment]
Hi, @samsym1 thanks for your information. looks like we missed the `service_endpoint` and `keys` attributes, I am working on it now and will add it soon
