### ISSUE TITLE
azurerm_kubernetes_cluster: api_server_authorized_ip_ranges notation keeps being set

### ISSUE THREAD

**Issue by bitsofinfo** [hashicorp/terraform-provider-azurerm#18753]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

latet

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "this" {
  name                = "${var.cluster_name_prefix}-aks"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags

  dns_prefix = var.cluster_name_prefix
  #automatic_channel_upgrade = "stable"
  api_server_authorized_ip_ranges = ["10.10.10.10"]
...
...
```
```


### Debug Output/Panic Output

```shell
# azurerm_kubernetes_cluster.this will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "this" {
      ~ api_server_authorized_ip_ranges     = [
          + "10.10.10.10",
          - "10.10.10.10/32",
        ]
```
```


### Expected Behaviour

Once 10.10.10.10 is set, its should not keep removing 10.10.10.10/32 and re-adding 10.10.10.10, is like this goes into a loop each time it runs.

### Actual Behaviour

Once 10.10.10.10 is set, its should not keep removing 10.10.10.10/32 and re-adding 10.10.10.10, is like this goes into a loop each time it runs.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

**Comment by bitsofinfo** [comment]
every time this happens it takes forever as it requires a cluster update

**Comment by bitsofinfo** [comment]
is like the provider's var = 10.10.10.10 and adds the IP as 10.10.10.10/32, but in the state (or AKS reported value) it stores 10.10.10.10, then resets it to 10.10.10.10/32 and on and on in a cycle

**Comment by zanoni23** [comment]
You should be setting it with a /32:
api_server_authorized_ip_ranges = ["10.10.10.10/32"]

**Comment by bitsofinfo** [comment]
@zanoni23 I am, doesn't matter what I set with or without, it keeps happening
