### ISSUE TITLE
Support for data.azurerm_cdn_frontdoor_secret

### ISSUE THREAD

**Issue by LWNetworks** [hashicorp/terraform-provider-azurerm#18769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to have a data resource created for azurerm_cdn_frontdoor_secret

The reason for this is due to our code and passing between modules etc, when specifying cdn_frontdoor_secret_id - this needs to be an ID or the resource. But if the resource has been imported within another module, it is not possible to link this in. 

Having a data block for it would enable passing the certs through from a module that specifically handles just certificate import from KV to FD

resource "azurerm_cdn_frontdoor_custom_domain" "fqdn" {
  name                                  = "contoso-listener"
  cdn_frontdoor_profile_id              = var.cdn_frontdoor_profile_id
  host_name                             = "www.contoso.com"
  tls {
    certificate_type        = "CustomerCertificate"
    cdn_frontdoor_secret_id = data.azurerm_cdn_frontdoor_secret
  }
}

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_secret

**Comment by WodansSon** [comment]
@LWNetworks, thank you for opening this issue I have created a data source for the CDN FrontDoor Secret resource, in the linked PR, which should do exactly what you are looking for.

## Example Data Source Usage:

```hcl
data "azurerm_cdn_frontdoor_secret" "test" {
  name                = azurerm_cdn_frontdoor_secret.test.name
  profile_name        = azurerm_cdn_frontdoor_profile.test.name
  resource_group_name = azurerm_resource_group.test.name
}
``` 

To use it in your configuration:

```hcl
resource "azurerm_cdn_frontdoor_custom_domain" "fqdn" {
  name = "contoso-listener"
  cdn_frontdoor_profile_id = var.cdn_frontdoor_profile_id
  host_name = "www.contoso.com"

  tls {
    certificate_type        = "CustomerCertificate"
    cdn_frontdoor_secret_id = data.azurerm_cdn_frontdoor_secret.id
  }
}
```
