### ISSUE TITLE
azurerm_container_group container volume incorrect or inaccurate error message "only one of `empty_dir` volume, `git_repo` volume, `secret` volume or storage account volume"

### ISSUE THREAD

**Issue by graememeyer** [hashicorp/terraform-provider-azurerm#18778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.27.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "container_rg"
  location = "uksouth"
}

resource "random_id" "id" {
  byte_length = 6
}

resource "azurerm_storage_account" "example" {
  name                     = "storacc${random_id.id.hex}"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
}

resource "azurerm_storage_share" "example" {
  name                 = "sharename"
  storage_account_name = azurerm_storage_account.example.name
  quota                = 500
}

resource "azurerm_storage_share_directory" "example" {
    name = "esdata"
    storage_account_name = azurerm_storage_account.example.name
    share_name = azurerm_storage_share.example.name
}

resource "azurerm_container_group" "cont-group-opencti-elasticsearch" {
  name                = "continst-cont-group-opencti-elasticsearch"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  ip_address_type     = "Public"
  os_type             = "Linux"

  container {
    name   = "elasticsearch"
    image  = "docker.elastic.co/elasticsearch/elasticsearch:8.4.2"
    cpu    = 2
    memory = 16

    ports {
      port     = 9000
      protocol = "TCP"
    }

    volume {
        name = "data"
        mount_path = "/usr/share/elasticsearch/data"
    }
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/graememeyer/7fe89f5abe56b00995dd719f39cea719
```

### Expected Behaviour

It should create a container group, with a single elastic search container in it, with an azure file share mounted. 

### Actual Behaviour

Instead, you get this error: ```Error: only one of `empty_dir` volume, `git_repo` volume, `secret` volume or storage account volume (`share_name`, `storage_account_name`, and `storage_account_key`) can be specified```

You can see in the reproducible example I have provided, that I have not set any of the fields mentioned, let alone multiple as the error would suggest.

It seems likely that this behaviour originates from this switch statement: https://github.com/hashicorp/terraform-provider-azurerm/blob/b6db3e48da8d9538f5582ce225db22160d92369e/internal/services/containers/container_group_resource.go#L1356-L1385

### Steps to Reproduce

Initialise terraform:

```terraform init```

Apply the terraform template/code

```terraform apply -auto-approve```

**Comment by teowa** [comment]
Hi @graememeyer , thanks for submitting this.
By checking the code, the error message is confusing, accully it should be 
> Exactly one of `empty_dir` volume, `git_repo` volume, `secret` volume or storage account volume (`share_name`, `storage_account_name`, and `storage_account_key`) must be specified.

And I will submit PR to amend to error message as well as note in documents.

**Comment by graememeyer** [comment]
That makes sense and matches my own observations, thanks @teowa.
