### ISSUE TITLE
Support for [Identity="UserAssigned" in azurerm_stream_analytics_job]

### ISSUE THREAD

**Issue by baselsalam** [hashicorp/terraform-provider-azurerm#18787]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Please allow "UserAssigned" value for identity in azurerm_stream_analytics_job

Not having this makes it very difficult to have terraform deal with jobs using this setting.

### Description

Please allow "UserAssigned" value for identity in azurerm_stream_analytics_job

Not having this makes it very difficult to have terraform deal with jobs using this setting.

### New or Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_job

**Comment by jayendranarumugam** [comment]
@baselsalam  Currently [Azure GO SDK](https://github.com/Azure/azure-sdk-for-go) doesn't supported the [2021-10-01-preview](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/streamanalytics/resource-manager/Microsoft.StreamAnalytics/preview/2021-10-01-preview) , I'd suggest you can create the issue on [Azure GO SDK Repo](https://github.com/Azure/azure-sdk-for-go)

**Comment by alxy** [comment]
For reference this has been requested here: https://github.com/Azure/azure-sdk-for-go/issues/19407

**Comment by tombuildsstuff** [comment]
Support for this is available in `hashicorp/go-azure-sdk`- https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/streamanalytics/2021-10-01-preview - which this SDK is using, however the `identity` types want updating to be able to support this - in that vain I've opened [this PR on `hashicorp/pandora`](https://github.com/hashicorp/pandora/pull/3724) which'll ensure the `identity` blocks are detected correctly, and once that's supported it should be possible to support this functionality.

Thanks!
