### ISSUE TITLE
Documentation describes management_group_id in example and as Arguments Reference management_group_name

### ISSUE THREAD

**Issue by Juerg-Liechti** [hashicorp/terraform-provider-azurerm#18807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Documentation describes management_group_id in example and as Arguments Reference management_group_name

resource "azurerm_management_group_template_deployment" "example" {
  name                     = "example"
  location                 = "West Europe"
  management_group_id      = data.azurerm_management_group.example.id
  template_spec_version_id = data.azurerm_template_spec_version.example.id
}

[management_group_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_template_deployment#management_group_name) - (Required) The Name of the Management Group to apply the Deployment Template to.

### Terraform Version

1.2.7

### AzureRM Provider Version

3.26

### Affected Resource(s)/Data Source(s)

azurerm_management_group

### Terraform Configuration Files

```hcl
Is only a documentation case.
```

### Debug Output/Panic Output

```shell
No output
```

**Comment by sinbai** [comment]
@Juerg-Liechti thanks for reporting this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/18823)has been submitted to fix it.
