### ISSUE TITLE
The terraform-provider-azurerm_v3.27.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by ramanaakulage** [hashicorp/terraform-provider-azurerm#18810]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1

### AzureRM Provider Version

3.27

### Affected Resource(s)/Data Source(s)

azurerm_monitor_autoscale_setting" "service_plan

### Terraform Configuration Files

```hcl
│ Error: Plugin did not respond
│ 
│   with module.service-plan-autoscale.azurerm_monitor_autoscale_setting.service_plan,
│   on ../../modules/service-plan-autoscale/main.tf line 8, in resource "azurerm_monitor_autoscale_setting" "service_plan":
│    8: resource "azurerm_monitor_autoscale_setting" "service_plan" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
```

### Debug Output/Panic Output

```shell
│ Error: Plugin did not respond
│ 
│   with module.service-plan-autoscale.azurerm_monitor_autoscale_setting.service_plan,
│   on ../../modules/service-plan-autoscale/main.tf line 8, in resource "azurerm_monitor_autoscale_setting" "service_plan":
	github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor/monitor_autoscale_setting_resource.go:697 +0x5c5
github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor.resourceMonitorAutoScaleSettingCreateUpdate(0xc001dfb500, {0x590f740?, 0xc00009b400})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/monitor/monitor_autoscale_setting_resource.go:432 +0x5dc
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x6a838e8?, {0x6a838e8?, 0xc0012fad80?}, 0xd?, {0x590f740?, 0xc00009b400?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000ebbb20, {0x6a838e8, 0xc0012fad80}, 0xc001da2000, 0xc001d83980, {0x590f740, 0xc00009b400})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/resource.go:837 +0xa7a
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0005268d0, {0x6a838e8?, 0xc0012facc0?}, 0xc001a19090)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.18.0/helper/schema/grpc_provider.go:1021 +0xe3c
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000565540, {0x6a838e8?, 0xc0012d3710?}, 0xc0001c23f0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/tf5server/server.go:813 +0x4fc
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5f0d6c0?, 0xc000565540}, {0x6a838e8, 0xc0012d3710}, 0xc001c8dce0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002aca80, {0x6a95540, 0xc0004b2820}, 0xc001d7b680, 0xc0005cae10, 0xab7fa40, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1283 +0xcfd
google.golang.org/grpc.(*Server).handleStream(0xc0002aca80, {0x6a95540, 0xc0004b2820}, 0xc001d7b680, 0x0)
	google.golang.org/grpc@v1.47.0/server.go:1620 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.47.0/server.go:922 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.47.0/server.go:920 +0x28a

Error: The terraform-provider-azurerm_v3.27.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

### Expected Behaviour

Plugin should not be crashed

### Actual Behaviour

azurerm_monitor_autoscale_setting" "service_plan

### Steps to Reproduce

Apply the azurerm_monitor_autoscale_setting" "service_plan and we applied different version and error remains same in 3.0 too

### Important Factoids

_No response_

### References

None

**Comment by teowa** [comment]
Hi @ramanaakulage , thanks for submitting this!
Seems I cannot repro this issue. Could you have a try Terraform config in [link](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting#example-usage-repeating-on-weekends) to check whether the issue still exists? If still exists, could you provide your TF config that trigger this issue? Thanks.

**Comment by ramanaakulage** [comment]
#---------------------------------------------------
# USE EXISTING RESOURCE GROUP
#---------------------------------------------------
data "azurerm_resource_group" "existing" {
  name     = var.resource_group_name
}

resource "azurerm_monitor_autoscale_setting" "service_plan" {
  name                = "${var.service_plan_name}-autoscale-setting"
  location            = var.location
  resource_group_name = var.resource_group_name
  enabled             = var.enabled
  target_resource_id  = var.service_plan_id

  profile {
    name = "${var.service_plan_name}-autoscale-default-profile"

    capacity {
      default = var.capacity
      minimum = var.capacity
      maximum = var.maxcapacity
    }
        
    dynamic "rule" {
      for_each = var.rules
      iterator = each
      content {
        metric_trigger {
          metric_name        = each.value.metric_name
          metric_resource_id = var.service_plan_id
          time_grain         = each.value.time_grain
          statistic          = each.value.statistic
          time_window        = each.value.time_window
          time_aggregation   = each.value.time_aggregation
          operator           = each.value.direction == "Increase" ? "GreaterThan" : "LessThan"
          threshold          = each.value.threshold
        }

        scale_action {
          direction = each.value.direction
          type      = each.value.type
          value     = each.value.capacity_change
          cooldown  = each.value.cooldown
        }
      }
    }
  }
  notification {
      email {
        send_to_subscription_administrator    = false
        send_to_subscription_co_administrator = false
        custom_emails                         = var.email_address
      }
  }
}

**Comment by teowa** [comment]
Hi @ramanaakulage , thanks for your reply, now I can reproduce the error by using `var.email_address=[""]`, thus lead to an error: `panic: interface conversion: interface {} is nil, not string`. I will add a constraint to limit `email_address` value as non-empty to prevent the provider from crashing.
