### ISSUE TITLE
Resource azurerm_postgresql_server: Enable public_network_access_enabled when create_mode = "PointInTimeRestore"

### ISSUE THREAD

**Issue by jlodiba** [hashicorp/terraform-provider-azurerm#18812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

v3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_server" "postgresql_server" {
  name                             = "myservername"
  location                         = "westeurope"
  resource_group_name              = "muresourcegroupname"
  sku_name                         = "GP_Gen5_2"
  version                          = "11"
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"
  backup_retention_days            = 7
  auto_grow_enabled                = true
  public_network_access_enabled    = true
  administrator_login              = "asdfghjklñ"
  administrator_login_password     = "fghjk@3469"
  create_mode                      = "PointInTimeRestore"
  creation_source_server_id        = "/subscriptions/08decd9d-7e96-4af1-8ef6-6b5796b89dce/resourceGroups/myresourcegroupname/providers/Microsoft.DBforPostgreSQL/servers/mysourceservername"
  restore_point_in_time            = "2022-01-01T08:00:00.00Z"
  identity {
      type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: `public_network_access_enabled` doesn't support PointInTimeRestore mode
│ 
│   with azurerm_postgresql_server.postgresql_server,
│   on main.tf line 1, in resource "azurerm_postgresql_server" "postgresql_server":
│    1: resource "azurerm_postgresql_server" "postgresql_server" {
```

### Expected Behaviour

The PostgreSQL server should be created. If the source server has a CMK then the new server should be in an inaccessible state, so the user would need to revalidate the key, and if the source server doesn't have one then the new server server should create without issue.

### Actual Behaviour

As the Terraform Registry documentation says the property public_network_access_enabled cannot be established, neither with true or false value, when `create_mode = PointInTimeRestore`. The problem is that, when `public_network_access_enabled = null`, the provider asumes the default value, which is true, so in the end the execution creates the new with `public_network_access_enabled = true` all the same.

Right now we are able to change the public network access configuration when the server is already created, but would be great if the, for example, `public_network_access_enabled = false` configuration could be established when the server is going to be created, and not later.

### Steps to Reproduce

terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Per my understanding, the PITR server should align with the settings (including PublicNetworkAccess) of source service, which means if the publicNetworkAccess is false in source server, then the publicNetworkAccess in PITR is also false.
