### ISSUE TITLE
azurerm hybrid connection "namespace" auto changing the initials from lowercase to uppercase

### ISSUE THREAD

**Issue by mdaqshahab** [hashicorp/terraform-provider-azurerm#18829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

azurerm_function_app_hybrid_connection

### Terraform Configuration Files

```hcl
resource "azurerm_function_app_hybrid_connection" "example" {
  function_app_id = azurerm_windows_function_app.example.id
  relay_id        = "/subscriptions/xxxxx-xxxxx-xxxxxxxx/resourceGroups/xxx-xx- 
                  xxx/providers/Microsoft.Relay/namespaces/example-namespace/hybridConnections/hc-example"
  hostname        = "myhostname.example"
  port            = 8081
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/xxxxx-xxxxx-xxxxxx-x/resourceGroups/xxx-xxxx-xxxx/providers/Microsoft.Relay/Namespaces/xxxxxxxx/Hybridconnections/xxxxxxxxx": parsing segment "staticNamespaces": expected the segment "Namespaces" to be "namespaces"
 
   with module.function_app.azurerm_function_app_hybrid_connection.hybrid_connections["fa-test2-tf"],
   on ..\..\Modules\function_app\function_app.tf line 35, in resource "azurerm_function_app_hybrid_connection" "hybrid_connections":
   35: resource "azurerm_function_app_hybrid_connection" "hybrid_connections" {
```

### Expected Behaviour

It should have created the hybrid connection and link it to my function app as my relay id was correct and it was giving error Namespaces should be "namespaces" in the relay id

In my relay id I have written the correct case sensitive value of "namepaces"

### Actual Behaviour

At runtime terraform validate is successful and when we run apply it changes the "namespaces" to "Namespaces" (Capitalise the initials) and not letting that resource to be created

### Steps to Reproduce

terraform apply

### Important Factoids

No

### References

No

**Comment by xiaxyi** [comment]
Thanks @mdaqshahab for raising this issue, can you let me know if you are specifying the `relay_id` using the detailed value like mentioned in the config`/subscriptions/xxxxx-xxxxx-xxxxxxxx/resourceGroups/xxx-xx-xxx/providers/Microsoft.Relay/namespaces/example-namespace/hybridConnections/hc-example` or using the resource reference like `  relay_id        = azurerm_relay_hybrid_connection.test.id`? 

I can tell the its namespace not Namespace in your issue description, which conflicts with the error message. 

Can you share the value of `relay_id` in the state with me?

**Comment by xiaxyi** [comment]
Hi @mdaqshahab, good day, just would like to follow up with you to see if you can share updates with me? Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the the value of the `relay_id` in the state. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
