### ISSUE TITLE
azurerm_app_configuration v3.27.0 - Error: checking for presence of deleted Deleted Configuration Store

### ISSUE THREAD

**Issue by michael-wolfenden** [hashicorp/terraform-provider-azurerm#18827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration 

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.27.0"
    }
  }
}

provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "resource_group" {
  name     = "myresourcegroup"
  location = "Australia East"
}

resource "azurerm_app_configuration" "app_configuration" {
  name                = "myappconfiguration"
  resource_group_name = azurerm_resource_group.resource_group.name
  location            = azurerm_resource_group.resource_group.location
  sku                 = "standard"
}
```

### Debug Output/Panic Output

```shell
2022-10-18T13:20:51.976+0800 [DEBUG] provider.terraform-provider-azurerm_v3.27.0_x5.exe: AzureRM Response for https://management.azure.com/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.AppConfiguration/locations/australiaeast/deletedConfigurationStores/myappconfiguration?api-version=2022-05-01: 
HTTP/2.0 403 Forbidden
Content-Length: 535
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Tue, 18 Oct 2022 05:20:50 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 2fa8e576-4e41-c05d-54ed-8b15d03ce4b7
X-Ms-Failure-Cause: gateway
X-Ms-Request-Id: 26d9c13d-1263-478f-954b-c3166fcb6d5f
X-Ms-Routing-Request-Id: AUSTRALIASOUTHEAST:20221018T052051Z:26d9c13d-1263-478f-954b-c3166fcb6d5f

{"error":{"code":"AuthorizationFailed","message":"The client '<CLIENT_ID>' with object id '<CLIENT_ID>' does not have authorization to perform action 'Microsoft.AppConfiguration/locations/deletedConfigurationStores/read' over scope '/subscriptions/<SUBSCRIPTION_ID>/providers/Microsoft.AppConfiguration/locations/australiaeast/deletedConfigurationStores/myappconfiguration' or the scope is invalid. If access was recently granted, please refresh your credentials."}}
```

### Expected Behaviour

The Azure App Configuration resource should have been created

### Actual Behaviour

Received the following error

```
azurerm_app_configuration.app_configuration: Creating...
╷
│ Error: checking for presence of deleted Deleted Configuration Store (Subscription: "<SUBSCRIPTION_ID>"
│ Location: "australiaeast"
│ Config Store Name: "myappconfiguration"): myappconfiguration
│
│   with azurerm_app_configuration.app_configuration,
│   on main.tf line 25, in resource "azurerm_app_configuration" "app_configuration":
│   25: resource "azurerm_app_configuration" "app_configuration" {
│
╵
```

### Steps to Reproduce

terraform apply

### Important Factoids

So by going through the debug logs I was able to see that the issue was due to my service principle NOT having the following scopes:

**Permissions to read and purge deleted stores**
Read: `Microsoft.AppConfiguration/locations/deletedConfigurationStores/read`
Purge: `Microsoft.AppConfiguration/locations/deletedConfigurationStores/purge/action`

We resolved this by pinning the version to `3.26.0` as this was causing our new deployments to fail so it appears as though this is a breaking change. Also the error that was reporting gave no indication of the issue.

**Comment by teowa** [comment]
Hi @michael-wolfenden , thanks for submitting this !

Sorry for the trouble made by adding the soft-delete features into App Configuration. But since the feature has been released, revert this may introduce another breaking changes, Could you please add the required permission to the Service Principal? And here is more information about assigning [Azure custom roles](https://learn.microsoft.com/en-us/azure/role-based-access-control/custom-roles), [`azurerm_role_assignment`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment) also support assigning a custom role.

And I am going to add notes in the resource documents.

**Comment by michael-wolfenden** [comment]
Happy to add the required permissions @teowa  however I still believe there's an issue in that the underlying error is not being surfaced in the error message. This made it impossible to diagnose the underlying issue without enabling `DEBUG` logging.

It looks like perhaps `err` should have been passed instead of `name` which is in line with how other errors are surfaced.

https://github.com/hashicorp/terraform-provider-azurerm/blob/3823802de3018e03341354ca761de887fc9639ab/internal/services/appconfiguration/app_configuration_resource.go#L251-L255
