### ISSUE TITLE
Bug in the example of the documentation from azurerm_load_test

### ISSUE THREAD

**Issue by jonaskoeASYS** [hashicorp/terraform-provider-azurerm#18839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_load_test

### Terraform Configuration Files

```hcl
resource "azurerm_load_example" "example" {
  location            = azurerm_resource_group.example.location
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

The Section "Example Usage" should uses "azurerm_load_test" instead of "azurerm_load_example":

resource "azurerm_load_test" "example" {
  location            = azurerm_resource_group.example.location
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/load_test

### Actual Behaviour

The Section "Example Usage" uses "azurerm_load_example" which does not exist:

resource "azurerm_load_example" "example" {
  location            = azurerm_resource_group.example.location
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/load_test

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of this [PR.](https://github.com/hashicorp/pandora/issues/1720), and the documentation appears to have regenerated. As such, I am going to mark this issue as closed.
