### ISSUE TITLE
Support for Immutable vaults in Azure Recovery Services vault

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#18837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Backup provides an option to ensure that recovery points that are once created cannot be deleted before their intended expiry time. Azure Backup does this by preventing any operations which could lead to loss of backup data. Hence, this helps you protect backups against threats like ransomware attacks and malicious actors by disallowing operations such as deleting backups or reducing retention in backup policies.

### New or Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Potential Terraform Configuration

```hcl
resource "azurerm_recovery_services_vault" "vault" {
  name                = "example-recovery-vault"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"

  soft_delete_enabled = true

  immutable_vault {
    immutable_vault_enabled = true
    immutable_vault_lock = true
  }
}
```

### References

https://learn.microsoft.com/en-us/azure/backup/backup-azure-immutable-vault-how-to-manage?tabs=recovery-services-vault

**Comment by ziyeqf** [comment]
Hi @abilous-ti, sorry for late reply.

A PR(#19294) draft has been submitted to add this feature. Once it merged and released the feature will be available.
