### ISSUE TITLE
Support for Azure Active Directory for Azure Database for PostgreSQL – Flexible Server

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#18838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Active Directory authentication for Azure Database for PostgreSQL - Flexible Server allows to improve database security by delegating credential management and authentication to a centralized identity provider. Azure Active Directory supports advanced security features such as second factor authentication options, password lifecycle management, applications and managed identities and conditional access. Azure Active Directory for Azure Database for PostgreSQL – Flexible Server now provides full support for managed identities, improved group roles and support for invited users and Azure Active Directory-only authentication mode with ability to disable local user support.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_active_directory_administrator

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server_active_directory_administrator" "example" {
  server_name         = azurerm_postgresql_server.example.name
  resource_group_name = azurerm_resource_group.example.name
  login               = "sqladmin"
  tenant_id           = data.azurerm_client_config.current.tenant_id
  object_id           = data.azurerm_client_config.current.object_id
}
```

### References

https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-azure-ad-authentication

**Comment by ziyeqf** [comment]
Thanks for reporting! 

I'm going to add this feature. And it currently blocked by https://github.com/Azure/azure-rest-api-specs/issues/21304

**Comment by binnykmathew** [comment]
Any news on when this will be available for use ?

**Comment by ziyeqf** [comment]
Hi @binnykmathew, a pr draft has submitted to add this feature. It will be available when it merged and released.
