### ISSUE TITLE
azurerm_automation_software_update_configuration Error in scope when its at subscription level

### ISSUE THREAD

**Issue by RAWRitsCloud** [hashicorp/terraform-provider-azurerm#18835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.25.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automation_software_update_configuration" "windowsUpdateGroupManagement" {
  name                  = "wino24AM"
  automation_account_id = var.es_input["automation_account_id"]
  operating_system      = "Windows"
  duration              = "PT6H0M"

  windows {
    classifications_included        = ["Critical", "Security"]
    excluded_knowledge_base_numbers = var.windows_excluded_kbs
    reboot                          = "IfRequired"
  }

  schedule {
    is_enabled  = true
    frequency   = "Month"
    description = "wino24AM Schedule"
    interval    = 1
    start_time  = var.period == "AM" ? "${formatdate("YYYY-MM-DD", timeadd(timestamp(), "24h"))}T00:00:00Z" : "${formatdate("YYYY-MM-DD", timeadd(timestamp(), "24h"))}T18:00:00Z"
    time_zone   = "Europe/London"

    monthly_occurrence {
      day        = var.day
      occurrence = tonumber(keys(var.weekOccurance)[0])
    }
  }

  target {
    azure_query {
      locations = var.es_input["locations"]
      scope     = ["/subscription/GUIDSUBSCIRPTION"]
      tags {
        tag    = "updateManagementGroup"
        values = ["wino24AM"]
      }
      tags {
        tag    = "updateManagementMethod"
        values = ["Azure Automation"]
      }
      tag_filter = "All"
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: ID was missing the 'resourceGroups' element
│ 
│   with module.updateManagement[0].azurerm_automation_software_update_configuration.windowsUpdateGroupManagement["o24AM"],
│   on .terraform\modules\updateManagement\res-updategroup.tf line 34, in resource "azurerm_automation_software_update_configuration" "windowsUpdateGroupManagement":
│   34:       scope     = ["/subscription/GUIDSUBSCIRPTION"]
```

### Expected Behaviour

I would expect it to be able to have a scope of just the whole subscription, I was doing this via an API call and it worked fine and as an ARM Template

### Actual Behaviour

It seems to not validate that there is no Resource Group but it doesn't need one

**Comment by wuxu92** [comment]
Hi @RAWRitsCloud thanks for your feedback it is confirmed a bug of azurerm. I have submitted a PR to fix it. and another reminder that the format of the subscription id should be `/subscriptions/xxx-xxx`
