### ISSUE TITLE
Support for additional Azure CDN Frontdoor output

### ISSUE THREAD

**Issue by randompixel** [hashicorp/terraform-provider-azurerm#18849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I've just worked out how the `azurerm_cdn_frontdoor*` resource all glues together (thanks for the hard work @WodansSon !) and have got it to a place I need it. I've had a couple of observations

**Documentation tweaks:**
1) https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_custom_domain The page title on this page is `azurerm_cdn_frontdoor_profile_custom_domain` but the word `profile` isn't correct here.
2) On the same page, it took me a few attempts to work out the TXT record part, as to what went in place of `contoso` in the example; it is the sub-domain part of the address you are creating and the `host_name` in `azurerm_cdn_frontdoor_custom_domain` is the FQDN. (I think!) Could the documentation be improved to be more explicit as to what is required?
3) On the same page, if `dns_zone_id` is optional, can you expand on which scenarios you might need to include it? I _have_ for the moment, but it'd save a lookup if I didn't have to.

**Additional output please!**
1) Is there a way of getting `azurerm_cdn_frontdoor_custom_domain` to output all the FQDNs it creates? I can do that from `azurerm_cdn_frontdoor_endpoint.host_name` but I can't find a way of outputting the custom domain names that have been created (without manually deducing that from the inputs). I'd like to be able to loop over the custom_domain (or other) resource and get everything that isn't the default
2) I commented here https://github.com/hashicorp/terraform-provider-azurerm/issues/17721#issuecomment-1238122401 but haven't found a way yet. With the old frontdoor I could get the `X-Azure-FDID` value from Terraform which I then used to pass in to NGINX container as it was built. With this new version I don't think that's available yet? I can see the value in the Azure Portal on the overview screen but would like to be able to export it from `azurerm_cdn_frontdoor_profile`

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_custom_domain, azurerm_cdn_frontdoor_profile

**Comment by WodansSon** [comment]
@randompixel, thank you for opening this issue... I will attempt to answer your questions below:

## Documentation:
>1. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_custom_domain The page title on this page is azurerm_cdn_frontdoor_profile_custom_domain but the word profile isn't correct here.

This was fixed with [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/18804), thanks for pointing that out. That was going to be the original name of the resource but we ended up removing the profile part and that one got missed. 🙂 

>2. On the same page, it took me a few attempts to work out the TXT record part, as to what went in place of contoso in the example; it is the sub-domain part of the address you are creating and the `host_name` in `azurerm_cdn_frontdoor_custom_domain` is the FQDN. (I think!) Could the documentation be improved to be more explicit as to what is required?

In my most recent [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/18851) I have addressed these comments and added more clarification along with links to product documentation for additional information as well.

>3. On the same page, if dns_zone_id is optional, can you expand on which scenarios you might need to include it? I have for the moment, but it'd save a lookup if I didn't have to.

Same as above.

## Outputs:

>1. Is there a way of getting `azurerm_cdn_frontdoor_custom_domain` to output all the FQDNs it creates? I can do that from `azurerm_cdn_frontdoor_endpoint`.`host_name` but I can't find a way of outputting the custom domain names that have been created (without manually deducing that from the inputs). I'd like to be able to loop over the custom_domain (or other) resource and get everything that isn't the default.

`azurerm_cdn_frontdoor_custom_domain` also exposes the field `host_name` which should contain the FQDN for that custom domain, so I think you should be able to use that field for what you are looking for or am I missing some context here?

>2. I commented [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/17721#issuecomment-1238122401) but haven't found a way yet. With the old frontdoor I could get the `X-Azure-FDID` value from Terraform which I then used to pass in to NGINX container as it was built. With this new version I don't think that's available yet? I can see the value in the Azure Portal on the overview screen but would like to be able to export it from `azurerm_cdn_frontdoor_profile`.

Yes, that is actually currently exposed but under a different name, it is no longer called `header_frontdoor_id` as it was in the classic frontdoor resource it is now called `resource_guid` and is exposed on the `azurerm_cdn_frontdoor_profile` resource.

**Comment by randompixel** [comment]
Ah brilliant thanks. Many thanks for the updates @WodansSon .

For `azurerm_cdn_frontdoor_custom_domain` I was basing that comment on the documentation here which usually includes all the things you can reference in `output.tf` 
 https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_custom_domain#attributes-reference. It suggests you can only use `id`, `expiration_date` and `validation_token`
 
<img width="704" alt="image" src="https://user-images.githubusercontent.com/2316601/196635590-bf1f6d3e-a931-48fb-a574-a3503b48d3c6.png">

however, in VSCode I can see 
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2316601/196641938-b7357fe8-1b69-415b-9a32-cd0d4356faca.png">
so is that a documentation mismatch?

I've tested it now in the code and applied and it works; I think I was just going through all the "Attribute References" sections looking for things I will need without trying them (sorry!)

If that's not an improvement that needs making then no worries and thanks for all your hard work.

**Comment by WodansSon** [comment]
@randompixel, yeah the wording in the documentation is a little weird, that section of the document only shows "extra" attributes that are exported by the resource. The "In addition to the Arguments listed above..." part is supposed to mean that everything that you define for the resource + these "extra" ones are available for output. 🚀
