### ISSUE TITLE
Support for Security Policy on azurerm_cdn_frontdoor_custom_domain_association

### ISSUE THREAD

**Issue by networkdude17** [hashicorp/terraform-provider-azurerm#18840]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am looking for support to be added to the azurerm_cdn_frontdoor_custom_domain_association resource. It was recently added to allow associations with custom domains, but it was beneficial to have it also allow associations with security profiles. This would allow us to create one security profile and associate mutiple domains with one profile. 

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_custom_domain_association

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_frontdoor_custom_domain_association" "example" {
cdn_frontdoor_security_policy_id = azurerm_cdn_frontdoor_security_policy.example.id
}
```

**Comment by WodansSon** [comment]
@jyanez-smg, thank you for opening this issue. This is actually currently possible with the existing resource. To associate a security policy with multiple custom domains all you need to do is add more `domain` references within the existing `association` field in the `azurerm_cdn_frontdoor_security_policy` resource:

## Example:

```hcl
resource "azurerm_cdn_frontdoor_security_policy" "example" {
  name                     = "MySecurityPolicy"
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.test.id

  security_policies {
    firewall {
      cdn_frontdoor_firewall_policy_id = azurerm_cdn_frontdoor_firewall_policy.test.id

      association {
        domain {
          cdn_frontdoor_domain_id = azurerm_cdn_frontdoor_custom_domain.contosos.id
        }

        domain {
          cdn_frontdoor_domain_id = azurerm_cdn_frontdoor_custom_domain.fabrikam.id
        }

        domain {
          cdn_frontdoor_domain_id = azurerm_cdn_frontdoor_custom_domain.cronus.id
        }

        domain {
          cdn_frontdoor_domain_id = azurerm_cdn_frontdoor_custom_domain.coho.id
        }

        patterns_to_match = ["/*"]
      }
    }
  }
}
```

I fear that the name I picked for the `azurerm_cdn_frontdoor_custom_domain_association` resource was poorly chosen and is adding confusion around what its actual purpose is... it does not actually associate a `custom domain` to a `route`, it is actually quite the opposite. It removes the association of a `custom domain` with a `route` upon the deletion of the association resource. I jokingly said that the name was all wrong and we should call it `azurerm_cdn_frontdoor_custom_domain_disassociation`, maybe I wasn't wrong... lol... it seems the name of that resource is causing a lot of confusion around it's actual purpose. Please take a look at issue #18844 for a much deeper dive into what the  `azurerm_cdn_frontdoor_custom_domain_association` resource is actually used for. I hope this help and thank you again for opening this issue! 🚀

**Comment by networkdude17** [comment]
I figured out a way to do what I needed via Dynamic Blocks, so closing this ticket.
