### ISSUE TITLE
Support for CSI secret store driver

### ISSUE THREAD

**Issue by cberge908** [hashicorp/terraform-provider-azurerm#18852]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems to be possible to directly enable the CSI secret provider addon during the creation of an AKS cluster, see: https://learn.microsoft.com/en-us/azure/aks/csi-secrets-store-driver

Would be great if this option can be added as option to the azurerm provider as well.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
 ...
 addons {
  enable_secret_store_csi_driver = true
 }
 ...
}
```

**Comment by marc-schaer** [comment]
Hi,

It seems that what you're searching for is the block `key_vault_secrets_provider`. See https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#key_vault_secrets_provider

Have a nice day!

**Comment by cberge908** [comment]
Thanks for the hint @marc-schaer!

I just think it might make sense to update the documentations slightly. Right now it's getting enabled once the block `key_vault_secrets_provider` and argument `secret_rotation_enabled` is set to `true`. Would be great if this attribute description would contain some more details like: "This enabled the secret store CSI driver on the AKS cluster".

![image](https://user-images.githubusercontent.com/42270330/210229042-2441372b-f218-4500-ac39-bd637ee6b261.png)

Otherwise it's hard to make the connection between the enablement of the rotation and the general enablement of the CSI secret store driver.
