### ISSUE TITLE
Error while upgrading the azurerm provider version: parsing segment "staticMicrosoftCompute": expected the segment "microsoft.compute" to be "Microsoft.Compute"

### ISSUE THREAD

**Issue by abhinavkumar7** [hashicorp/terraform-provider-azurerm#18865]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_disk

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "disk_managed_disk" {
  name                 = "disk-01"
  location             = "norwayeast"
  resource_group_name  = azurerm_resource_group.rg.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = 50
  tags                 = local.default_tags
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/***/resourceGroups/rg/providers/microsoft.compute/disks/disk-01": parsing segment "staticMicrosoftCompute": expected the segment "microsoft.compute" to be "Microsoft.Compute"
```

### Expected Behaviour

This error shouldn't have been there since there are no changes in the configuration and we're just upgrading the provider version.

### Actual Behaviour

While upgrading the azurerm provider version for existing configuration / deployment with an existing state terraform apply or plan fails with the error: parsing segment "staticMicrosoftCompute": expected the segment "microsoft.compute" to be "Microsoft.Compute"

### References

Similar to: https://github.com/hashicorp/terraform-provider-azurerm/issues/18235

**Comment by abhinavkumar7** [comment]
upgrading from azurerm provider: 2.99.0 -> 3.27.0

**Comment by myc2h6o** [comment]
Hi @abhinavkumar7 thanks for opening the issue! This is indeed a regression when we were enhancing the ID validation. I've opened #18885 to fix the issue by adding a state upgrader to automatic upgrade the ID to a new one, and the error message shall disappear after the fix is released.
