### ISSUE TITLE
azurerm_monitor_metric_alert metric_name space cannot be specified and metric_name couldn't find Error 400

### ISSUE THREAD

**Issue by maxmanus96** [hashicorp/terraform-provider-azurerm#18869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.3

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert metric_name

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_event_subscription" "keyvault_secret_expiry" {
  name  = "azureeventgrid"
  scope = azurerm_key_vault.keyvault.id

  event_delivery_schema = "EventGridSchema"
  included_event_types  = ["Microsoft.KeyVault.SecretCloseToExpiry","Microsoft.KeyVault.KeyCloseToExpiry"]

  storage_queue_endpoint {
    storage_account_id = azurerm_storage_account.keyvault_alert.id
    queue_name         = azurerm_storage_queue.keyvault_alert.name
  }

  retry_policy {
    max_delivery_attempts = 10
    event_time_to_live    = 1440
  }
}

#create an alert rule for the published events metric name "Published Events",  metric namespace "Event Grid System Topics standard metrics"
resource "azurerm_monitor_metric_alert" "keyvault_secret_expiry" {
  name                = "keyvault_secret_expiry"
  resource_group_name = var.RESOURCE_GROUP
  scopes              = [azurerm_eventgrid_event_subscription.keyvault_secret_expiry.id]
  description         = "Alert if a Key Vault secret is close to expiry"
  severity            = 3

  criteria {
    metric_namespace = "Microsoft.EventGrid/eventSubscriptions"
    metric_name      = "MatchedEventCount"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 0
  }

  action {
    action_group_id = azurerm_monitor_action_group.keyvault_alert.id
  }
}

resource "azurerm_monitor_action_group" "keyvault_alert" {
  name                = "keyvault_alert"
  resource_group_name = var.RESOURCE_GROUP
  short_name          = "kv_alert"

  email_receiver {
    name          = "sendtoemail"
    email_address = "..."
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating or updating Monitor Metric Alert: (Name "keyvault_secret_expiry" / Resource Group ""): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The metric with the name MatchedEventCount does not exist. Activity ID: f41f0fa2-"
```

### Expected Behaviour

It supposed to create the metric alert successfully. 

### Actual Behaviour

I already checked the metric_namespace "Microsoft.EventGrid/systemTopics" and metric_name "PublishSuccessCount" from Microsoft's document. https://learn.microsoft.com/en-us/azure/event-grid/metrics#event-subscriptions However, terraform doesn't accept metric_name space  "Microsoft.EventGrid/systemTopics" and says must use "Microsoft.EventGrid/eventSubscriptions", then I checked what I can use for that metric_name space and used metric_name      = "MatchedEventCount", however as above terraform can't find the metric_name "MatchedEventCount".

### References

https://learn.microsoft.com/en-us/azure/event-grid/metrics#event-subscriptions

**Comment by teowa** [comment]
Hi @maxmanus96 , thanks for opening this issue!

By checking the [Supported resources for metric alerts in Azure Monitor](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-metric-near-real-time), seems `Microsoft.EventGrid/eventSubscriptions` is not supported by current metric alert. And `Microsoft.EventGrid/systemTopics` has been supported.

From [event grid doc](https://learn.microsoft.com/en-us/azure/event-grid/system-topics#lifecycle-of-system-topics),
>You can create a system topic in two ways:
>1. Create an [event subscription on an Azure resource as an extension resource](https://learn.microsoft.com/en-us/rest/api/eventgrid/controlplane-version2021-10-15-preview/event-subscriptions/create-or-update), which automatically creates a system topic with the name in the format: <Azure resource name>-<GUID>. The system topic created in this way is automatically deleted when the last event subscription for the topic is deleted.
>2. Create a system topic for an Azure resource, and then create an event subscription for that system topic. When you use this method, you can specify a name for the system topic. The system topic isn't deleted automatically when the last event subscription is deleted. You need to manually delete it.

So we can use method 2 to create a event grid  system topic first, and use metric alert base on it. I can successfully provision this using below Terraform config, hope this may help.

<details>
<summary> TF config</summary>

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "keyvault" {
  name                        = "examplekeyvault021"
  location                    = azurerm_resource_group.example.location
  resource_group_name         = azurerm_resource_group.example.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false

  sku_name = "standard"
}

resource "azurerm_storage_account" "keyvault_alert" {
  name                     = "examplestorageaccount021"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = "staging"
  }
}

resource "azurerm_storage_queue" "keyvault_alert" {
  name                 = "examplestoragequeue"
  storage_account_name = azurerm_storage_account.keyvault_alert.name
}

resource "azurerm_eventgrid_system_topic" "example" {
  name                   = "example-system-topic"
  location               = azurerm_key_vault.keyvault.location
  resource_group_name    = azurerm_resource_group.example.name
  source_arm_resource_id = azurerm_key_vault.keyvault.id
  topic_type             = "Microsoft.KeyVault.vaults"
}

resource "azurerm_eventgrid_system_topic_event_subscription" "example" {
  name                = "azureeventgrid"
  system_topic        = azurerm_eventgrid_system_topic.example.name
  resource_group_name = azurerm_resource_group.example.name

  event_delivery_schema = "EventGridSchema"
  included_event_types  = ["Microsoft.KeyVault.SecretCloseToExpiry", "Microsoft.KeyVault.KeyCloseToExpiry"]

  storage_queue_endpoint {
    storage_account_id = azurerm_storage_account.keyvault_alert.id
    queue_name         = azurerm_storage_queue.keyvault_alert.name
  }

  retry_policy {
    max_delivery_attempts = 10
    event_time_to_live    = 1440
  }
}

#create an alert rule for the published events metric name "Published Events",  metric namespace "Event Grid System Topics standard metrics"
resource "azurerm_monitor_metric_alert" "keyvault_secret_expiry" {
  name                = "keyvault_secret_expiry"
  resource_group_name = azurerm_resource_group.example.name
  scopes              = [azurerm_eventgrid_system_topic.example.id]
  description         = "Alert if a Key Vault secret is close to expiry"
  severity            = 3

  criteria {
    metric_namespace = "Microsoft.EventGrid/systemTopics"
    metric_name      = "PublishSuccessCount"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 0
  }

  action {
    action_group_id = azurerm_monitor_action_group.keyvault_alert.id
  }
}

resource "azurerm_monitor_action_group" "keyvault_alert" {
  name                = "keyvault_alert"
  resource_group_name = azurerm_resource_group.example.name
  short_name          = "kv_alert"

  email_receiver {
    name          = "sendtoemail"
    email_address = "1@1.com"
  }
}
```

</details>

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this issue. I am going to mark this issue as closed based on the documentation and example given by @teowa. If you have any further questions, I recommend asking them here: [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
