### ISSUE TITLE
Azurerm_firewall_policy_rule_collection_group documentation for protocol wrong case

### ISSUE THREAD

**Issue by ChrisTav424** [hashicorp/terraform-provider-azurerm#18868]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.209.19

### Affected Resource(s)/Data Source(s)

azurerm_firewall_policy_rule_collection_group

### Terraform Configuration Files

```hcl
resource "azurerm_firewall_policy_rule_collection_group" "fwpolicy" {
  name               = "firewall-policy"
  firewall_policy_id = azurerm_firewall_policy.fwpolicy.id
  priority           = 100

  network_rule_collection {
    name     = "Allow-any"
    priority = 120
    action   = "Allow"
    rule {
      name                  = "Allow-all-network-rule"
      protocols             = ["ANY"]
      source_addresses      = ["redacted"]
      destination_addresses = ["redacted"]
      destination_ports     = ["*"]
    }
  }

}
```

### Debug Output/Panic Output

```shell
See below
```

### Expected Behaviour

Plans successfully

### Actual Behaviour

Fails with the following

![image](https://user-images.githubusercontent.com/44398463/196637667-44a39b8f-a273-4e99-8769-7e15f51a72db.png)

Documentation says this expects uppercase ANY, but it expects title case / camel case for Any so think the documentation needs updating (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy#protocol)

### Steps to Reproduce

terraform apply

### References

Documentation is here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy#protocol

**Comment by wuxu92** [comment]
@ChrisTav424 thanks for your feedback. looks like you referenced to the document of another resource. please use the below link to see if it is right.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group#protocols:~:text=Possible%20values%20are%20Any%2C%20TCP%2C%20UDP%2C%20ICMP


![image](https://user-images.githubusercontent.com/2633022/196839575-db8842be-3af3-4cd0-860b-e61959b0f6ac.png)

**Comment by ChrisTav424** [comment]
@wuxu92 I'm a donut. I had completely missed that, thank you :)
