### ISSUE TITLE
Invalid legacy provider address: can't update it through Azure DevOps pipeline

### ISSUE THREAD

**Issue by gielVanDeVoorde** [hashicorp/terraform-provider-azurerm#18873]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

2.53

### Affected Resource(s)/Data Source(s)

State

### Terraform Configuration Files

```hcl
Not configuration related but state related, we can't upgrade to a qualified version of the provider "azurerm".
```

### Debug Output/Panic Output

```shell
[31m│[0m [0m[1m[31mError: [0m[0m[1mInvalid legacy provider address[0m

[31m│[0m [0m

[31m│[0m [0m[0mThis configuration or its associated state refers to the unqualified

[31m│[0m [0mprovider "azurerm".

[31m│[0m [0m

[31m│[0m [0mYou must complete the Terraform 0.13 upgrade process before upgrading to

[31m│[0m [0mlater versions.

[31m╵[0m[0m

[0m[0m
```

### Expected Behaviour

We want to use the Terraform 0.13upgrade command to refer to the qualified provider "azurerm", but there is no option to do this through Azure DevOps Terraform blocks

### Actual Behaviour

We can't upgrade and need assistance to get our code compiling again.

**Comment by magodo** [comment]
@gielVanDeVoorde Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).
