### ISSUE TITLE
Support for azurerm_kubernetes_cluster to set VirtualMachineScaleSets zoneBalance true if multiple zones selected

### ISSUE THREAD

**Issue by rgarcia89** [hashicorp/terraform-provider-azurerm#18879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently when deploying an over availability zones 1, 2, 3 spreaded aks kubernetes cluster, it can happen that your nodes will be started in only two of them. This is caused by the fact that Microsoft does per default set the `zoneBalance` variable of the `VirtualMachineScaleSets` to false. Even if multiple zones are selected. In my case I figured out that of my 3 nodes two are located in zone 2 and the third one in zone 3.

```
NAME                                  REGION               ZONE
.aks-workerpool1-39166192-vmss000000   germanywestcentral   germanywestcentral-2
aks-workerpool1-39166192-vmss000001   germanywestcentral   germanywestcentral-3
aks-workerpool1-39166192-vmss000003   germanywestcentral   germanywestcentral-2
```

This is of course not what I wanted it to have. Unfortunately I do not see a possibility to change this currently when deploying a cluster using terraform. Here are some further information:

Is there any way to get this into terraform or azure?

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster, azurerm_linux_virtual_machine_scale_set

### References

https://learn.microsoft.com/en-US/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-use-availability-zones#use-the-azure-portal
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#zone_balance

**Comment by alk-automize** [comment]
I have similar availability zones configuration, but now terraform only creates 2 of 3 nodes after a 30 min time out with a "CreateVMSSAgentPoolFailed" error message. Doing the same configuration in the portal works just fine.

**Comment by stephybun** [comment]
Thanks for raising this issue @rgarcia89.

Looking at the latest AKS API I currently do not see a property that will allow us to configure zone balancing on the VMSS deployed for the default node pool of the AKS cluster. It would be a big help if you could point me towards any documentation that demonstrates how this would be done, but I suspect that support for this would first need to be added in the AKS API, for that you would need to raise an issue over on the AKS repo https://github.com/Azure/AKS.

**Comment by rgarcia89** [comment]
Hi @stephybun thanks for coming back to me.
I have raised the API feature request in this ticket to the Devs behind AKS https://github.com/Azure/AKS/issues/3279#issuecomment-1430088094

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying AKS API so I am going to close it for now. When it gets added, we can reopen this request or you can create a new one.
https://github.com/Azure/AKS/issues/3279#issuecomment-1430088094
