### ISSUE TITLE
Support for admin protection in azurerm_databricks_workspace

### ISSUE THREAD

**Issue by dvasdekis** [hashicorp/terraform-provider-azurerm#18881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We wish to enable admin protection for "no-isolation shared" clusters ([see here for MS docs](https://learn.microsoft.com/en-gb/azure/databricks/administration-guide/account-settings/no-isolation-shared)).

Microsoft just added this parameter to their list of security advisory flags, so now our databricks instances are considered insecure by our internal IT department unless this flag is switched on.

Attempted Solutions
I haven't been able to determine a means to turn on this flag in the current Terraform Databricks workspace config.

We can't do it manually as we currently have 48 databricks instances, and growing.

Proposal
Add a parameter to the azurerm_databricks_workspace resource to control this, plus an entry in the docs.

### New or Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_databricks_workspace" "example" {
  name                = "databricks-test"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "standard"
  
  admin_protection_for_no_isolation_shared = true
}
```

### References

https://learn.microsoft.com/en-gb/azure/databricks/administration-guide/account-settings/no-isolation-shared

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. After checked the [rest api spec](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/databricks/resource-manager/Microsoft.Databricks), seems this feature isn't supported by the service api. So suggest file a feature request on https://github.com/Azure/azure-rest-api-specs/issues.

**Comment by dvasdekis** [comment]
> Thanks for raising this issue. After checked the [rest api spec](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/databricks/resource-manager/Microsoft.Databricks), seems this feature isn't supported by the service api. So suggest file a feature request on https://github.com/Azure/azure-rest-api-specs/issues.

Thank you, I have done so here: https://github.com/Azure/azure-rest-api-specs/issues/21198

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. Thank you for adding the link to be followed while waiting for this addition. When it gets added, we can reopen this request or you can create a new one.
