### ISSUE TITLE
Support for accurate granularities on in planning and docs for azurerm_monitor_scheduled_query_rules_alert_v2

### ISSUE THREAD

**Issue by fardarter** [hashicorp/terraform-provider-azurerm#18886]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Acceptable window granularities in minutes for azurerm_monitor_scheduled_query_rules_alert_v2 are 5, 10, 15, 30, 45, 60, 120, 180, 240, 300, 360, 1440, 2880. It would be useful if this could be added to planning and docs. 

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Potential Terraform Configuration

```hcl
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert_v2
```

**Comment by fardarter** [comment]
I got it from an error message in CI:

```hcl
│ Error: creating Scheduled Query Rule (Subscription: "redacted"
│ Resource Group Name: "redacted"
│ Rule Name: "disk-between-35-and-15-percent-free-space-redacted"): scheduledqueryrules.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'WindowSize of 720 minutes is not supported. Supported granularities are: 5, 10, 15, 30, 45, 60, 120, 180, 240, 300, 360, 1440, 2880'"
│ 
│   with module.alerting.azurerm_monitor_scheduled_query_rules_alert_v2.alert_on_disk_exhaustion_between_35_and_15_percent[0],
│   on ../shared/terraform/modules/alerting/main.tf line 40, in resource "azurerm_monitor_scheduled_query_rules_alert_v2" "alert_on_disk_exhaustion_between_35_and_15_percent":
│   40: resource "azurerm_monitor_scheduled_query_rules_alert_v2" "alert_on_disk_exhaustion_between_35_and_15_percent" {
│ 
│ creating Scheduled Query Rule (Subscription:
│ "redacted"
│ Resource Group Name: "redacted"
│ Rule Name:
│ "disk-between-35-and-15-percent-free-space-redacted"):
│ scheduledqueryrules.ScheduledQueryRulesClient#CreateOrUpdate: Failure
│ responding to request: StatusCode=400 -- Original Error: autorest/azure:
│ Service returned an error. Status=400 Code="InvalidRequestContent"
│ Message="The request content was invalid and could not be deserialized:
│ 'WindowSize of 720 minutes is not supported. Supported granularities are:
│ 5, 10, 15, 30, 45, 60, 120, 180, 240, 300, 360, 1440, 2880'"
```

**Comment by jayendranarumugam** [comment]
Alright, I can see those allowed values in the azure portal too.,
![image](https://user-images.githubusercontent.com/25414541/196972107-3cabf991-3bd3-4d72-81f6-cdaeff8d4fc1.png)

Let me give its quick fix on the doc

**Comment by fardarter** [comment]
Possible to add it for validation in the terraform plan stage?
