### ISSUE TITLE
Validation at planning stage for duration on azurerm_monitor_scheduled_query_rules_alert_v2

### ISSUE THREAD

**Issue by fardarter** [hashicorp/terraform-provider-azurerm#18895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please see: https://github.com/hashicorp/terraform-provider-azurerm/issues/18886

While the document update is appreciated, there is no validation of the value set at the planning phase. 

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

**Comment by teowa** [comment]
Hi @fardarter , thanks for opening this.
I have submitted PR to fix this.

**Comment by fardarter** [comment]
Thanks, amazing!
