### ISSUE TITLE
Azure Storage Account Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by beameup50** [hashicorp/terraform-provider-azurerm#18897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Greater than 0.13

### AzureRM Provider Version

2.86.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "main" {
  name                      = "${var.storageaccountname}"
  resource_group_name       = azurerm_resource_group.main.name
  location                  = azurerm_resource_group.main.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  enable_https_traffic_only = true
  is_hns_enabled            = true
  account_replication_type  = "LRS"
  access_tier               = "Hot"

  network_rules {
    default_action = "Deny"
    bypass         = ["AzureServices"]
    ip_rules       = var.optum_ip_addresses
  }

  min_tls_version = "TLS1_2"

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent result after apply

When applying changes to azurerm_storage_account.main, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource    
was present, but now absent.

This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Expected Behaviour

Storage account should be created

### Actual Behaviour

Error

### Steps to Reproduce

terraform apply

**Comment by magodo** [comment]
@beameup50 Could you please try out the latest provider as we are no longer maintaining the v2 provider?

**Comment by beameup50** [comment]
@magodo

After upgrading to latest provider 3.28.0 I get the following error:

azurerm_storage_account.example: Creating...
azurerm_storage_account.example: Still creating... [10s elapsed]
azurerm_storage_account.example: Still creating... [20s elapsed]

│ Error: retrieving Storage Account: (Name "[StorageAccountName]" / Resource Group "[RGName]"): storage.AccountsClient#GetProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="StorageAccountNotFound" Message="The storage account [StorageAccountName] was not found."

**Comment by beameup50** [comment]
UPDATE:  By manually removing the storage account from the TF state, manually creating a storage account, then importing it into the TF state, I was able to work around this problem.

**Comment by magodo** [comment]
@beameup50 Could you please kindly attach the DEBUG log when the issue occurs? This probably relates to #2977, but with a minor difference: In #2977, the storage account is able to create successfully, but the container will fail, after setting up the `network_rules`.

Though the `azurerm_storage_account` also has some data plane API calls after creation, whilst from the previous behavior, those API calls are not blocked by the network rules. I'm not sure whether the storage service changed the behavior recently.
