### ISSUE TITLE
azurerm_linux_function_app using ElasticPremium error

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-azurerm#18907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

2.2.0

### AzureRM Provider Version

3.16

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                            = "${var.names["storage-account"]}example"
  resource_group_name             = azurerm_resource_group.example.name
  location                        = azurerm_resource_group.example.location
  account_tier                    = "Standard"
  account_replication_type        = "GRS"
  allow_nested_items_to_be_public = false
  shared_access_key_enabled       = false
  enable_https_traffic_only       = true
  min_tls_version                 = "TLS1_2"
  tags                            = var.tags
}

resource "azurerm_user_assigned_identity" "example" {
  location            = azurerm_resource_group.example.location
  name                = "${var.names["managed-identity"]}example"
  resource_group_name = azurerm_resource_group.example.name
}

locals {
  function_app_role_assignments = [
    "Storage Blob Data Contributor",
    "Storage File Data SMB Share Contributor",
    "Storage Queue Data Contributor"
  ]
}

resource "azurerm_role_assignment" "example" {
  for_each             = toset(local.function_app_role_assignments)
  scope                = azurerm_storage_account.example.id
  role_definition_name = each.value
  principal_id         = azurerm_user_assigned_identity.example.principal_id
}

resource "azurerm_service_plan" "example" {
  name                         = "${var.names["app-service-plan"]}-example"
  location                     = azurerm_resource_group.example.location
  resource_group_name          = azurerm_resource_group.example.name
  maximum_elastic_worker_count = 20
  os_type                      = "Linux"
  tags                         = var.tags
  sku_name                     = "EP1"

  lifecycle {
    ignore_changes = [
      kind,
    ]
  }
}

resource "azurerm_linux_function_app" "example" {
  name                          = "${var.names["function-app"]}-example"
  location                      = azurerm_resource_group.example.location
  resource_group_name           = azurerm_resource_group.example.name
  service_plan_id               = azurerm_service_plan.example.id
  storage_account_name          = azurerm_storage_account.example.name
  storage_uses_managed_identity = true
  functions_extension_version   = "~4"
  https_only                    = true
  tags                          = var.tags

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.example.id]
  }
  depends_on = [
    azurerm_role_assignment.example
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Linux Function App: (Site Name "<<function-app-name>>" / Resource Group "<<rg-name>>"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value." Details=[{"Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"51008","Message":"The parameter WEBSITE_CONTENTAZUREFILECONNECTIONSTRING has an invalid value.","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"]}}]
```

### Expected Behaviour

Creates the function app using ElasticPremium EP1 plan with no issues.

**Works fine if I create using a Standard App Service Plan, e.g. S1**

### Actual Behaviour

Fails to create

### Steps to Reproduce

1. terraform apply

**Comment by xiaxyi** [comment]
Thanks @MattGarner-N for raising this issue, I see `shared_access_key_enabled` was set to `false`. Did you enable AD authentication as mentioned in this [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account):

_Terraform uses Shared Key Authorisation to provision Storage Containers, Blobs and other items - when Shared Key Access is disabled, you will need to enable [the storage_use_azuread flag in the Provider block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#storage_use_azuread) to use Azure AD for authentication, however not all Azure Storage services support Active Directory authentication._

**Comment by MattGarner-N** [comment]
Hello @xiaxyi,

Yes I did do that. Just to let you know the code works fine in Terraform if I use a Standard S1 app service plan. The problem is happening only with the ElasticPremium EP1 plan.

I have also added the role assignments code above I give to the Managed Identity for accessing the Storage Account

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved with @xiaxyi's information regarding WEBSITE_CONTENTAZUREFILECONNECTIONSTRING being needed for function elastic plan. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
