### ISSUE TITLE
azurerm_dns_zone not updating number_of_record_sets after dns records provisioning during apply

### ISSUE THREAD

**Issue by PowerSurj** [hashicorp/terraform-provider-azurerm#18917]
### ISSUE DESCRIPTION

We deploy azure dns zone using `azurerm_dns_zone` and then provision records into it using e.g. `azurerm_dns_a_record`, all in one play.

All being provisioned through pipeline, plan, evaluating impact and then apply.

Provider discovers changes in the `number_of_record_sets` attribute of the `azurerm_dns_zone` resource  on consecutive pipeline run. Even though there were no changes. This adds unnecessary noise to the output.

Resources` Lifecycle doesn't allow ignoring this property.

Use of terraform refresh is not recommended in general.
https://developer.hashicorp.com/terraform/cli/commands/refresh

Is there any other solution we could implement that would allow resource `azurerm_dns_zone` to refresh after the provisioning of any of the `azurerm_dns_..._record` into the zone during the same apply action.

Or is there any other way to suppress this specific warning?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_dns_zone

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.azure_dns.azurerm_dns_zone.zone["test.com"] has changed
  ~ resource "azurerm_dns_zone" "public_dns_zone" {
        id                        = "/subscriptions/............/test.com"
        name                      = "test.com"
      ~ number_of_record_sets     = 18 -> 19

        # (3 unchanged attributes hidden)
        # (2 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the
relevant attributes using ignore_changes, the following plan may include
actions to undo or respond to these changes.
```

### Expected Behaviour

be able to ignore changes in the `number_of_record_sets` attribute or make it auto-refresh when provisioning records into the zone

### Actual Behaviour

when records being provisioned through TF into the zone, zone resource doesn't update the `number_of_record_sets` attribute

### Steps to Reproduce

n/a

**Comment by ziyeqf** [comment]
Hi @PowerSurj, thanks for opening the issue.

Terraform shows the difference because the `number_of_record_sets` property did get changed. It's the number of records already in the zone. So even if there is no change in `azurerm_dns_zone`, adding dns records to it will cause changes, and there will be difference between local state file and remote state.

I think there is a tricky way to ignore the change of `number_of_record_sets `, you can separate `azurerm_dns_zone` and `azurerm_dns_..._record` into different terraform projects and then it won't show changes on `azurerm_dns_zone` till you run commands on its config.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ziyeqf‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
