### ISSUE TITLE
add offer type argument to azurerm_subscription

### ISSUE THREAD

**Issue by igorkarpel** [hashicorp/terraform-provider-azurerm#18925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, when I create a new Azure subscription using the official Terraform provider (using azurerm_subscription) there is no option to set the Offer type argument.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription

The only  option is to use an unofficial provider which is risky to use:
https://registry.terraform.io/providers/innovationnorway/azure-preview/latest/docs

Can you please update if you plan to add the offer type argument to the Azure official provider, if yes is there any estimation of when it will happen?

### New or Affected Resource(s)/Data Source(s)

azurerm_subscription

### Potential Terraform Configuration

```hcl
"azurepreview_subscription" "new_sub" { 
  name               = "subcription name"
  enrollment_account = "asdada-sadas-42eb-dsd-asdsaddasdsa"
  offer_type         = "MS-AZR-0148P" 
  provider           = azure-preview
}
```

**Comment by aristosvo** [comment]
Hi @igorkarpel!

Thanks for raising this! I'll probably include this in #18813 or a subsequent PR.

Do you prefer specific `offer_type` with an advanced offer type or is `DevTest` vs `Prod` also good enough?

**Comment by tombuildsstuff** [comment]
@aristosvo from memory @jackofallops had issues last time he looked into adding this field, I have a feeling that either the API didn't return the value, or that it behaved differently when it was configured - so it might be worth checking with him to see if there's any known potholes for this one?

**Comment by igorkarpel** [comment]
Hi @aristosvo 
Thanks for checking this, regarding your question, Dev/Test vs Prod will be enough.

Thanks,
Igor

**Comment by aristosvo** [comment]
@igorkarpel It seems [workload](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription#workload) is already a valid property of `azurerm_subscription`! 🎉 

I hope this satisfies your requirements for now, I'll close this issue until I hear otherwise. Have a nice day!!

**Comment by igorkarpel** [comment]
@aristosvo I can see that the workload property has appeared , Thank you very much for your assistance!
