### ISSUE TITLE
Module is not breaking as expected :)

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/terraform-provider-azurerm#18941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rt" {
  name     = format("rg-rt-%s-%s", var.location, var.name)
  name     = format("rg-rt-%s-%s", var.location, var.service)
  location = var.location
  tags     = var.tags
}

resource "azurerm_route_table" "rt" {
  name                          =  format("rt-%s-%s", var.location, var.name)
  location                      = azurerm_resource_group.rt.location
  resource_group_name           = azurerm_resource_group.rt.name
  disable_bgp_route_propagation = var.disable_bgp_route_propagation
  tags                          = var.tags

  dynamic "route" {
    for_each = var.routes
    content {
      name                   = route.value.name
      address_prefix         = route.value.address_prefix
      next_hop_type          = route.value.next_hop_type
      next_hop_in_ip_address = route.value.next_hop_type == "VirtualAppliance" ? route.value.next_hop_in_ip_address : null
    }
  }
}
```

### Debug Output/Panic Output

```shell
`
module.azure-route_tables["fw-uks"].azurerm_resource_group.rt: Refreshing state... [id=/subscriptions/********************/resourceGroups/rg-rt-uksouth-afw]

module.azure-route_tables["fw-uks-mgt"].azurerm_resource_group.rt: Refreshing state... [id=/subscriptions/********************/resourceGroups/rg-rt-uksouth-afw]
`
```

### Expected Behaviour

When this module is called multiple times and the resource group has the same name, it should break when trying to create it because a resource with that resource ID already exists. 

### Actual Behaviour

The module does not break despite the Terraform ID being different and the Azure Resource ID being the same.

Refreshing state shows:

`
module.azure-route_tables["fw-uks"].azurerm_resource_group.rt: Refreshing state... [id=/subscriptions/********************/resourceGroups/rg-rt-uksouth-afw]

module.azure-route_tables["fw-uks-mgt"].azurerm_resource_group.rt: Refreshing state... [id=/subscriptions/********************/resourceGroups/rg-rt-uksouth-afw]
`

Have recently updated terraform versions so this may be normal but not expecting this to work

**Comment by ziyeqf** [comment]
Hi @ASHR4, thanks for reporting!

I have digged into this, and I did reproduced it.But I think it should be an issue in Terraform and the it can't be handled by the provider, so I opened an issue on it.

**Comment by ziyeqf** [comment]
Hi @ASHR4, Sorry for late update.

As the TF core developer replied, it is not an issue with module but the provider. If we create two resources with the same name property and different resource name, it shows the same result as the issue described. We will try to fix it.

**Comment by manicminer** [comment]
Due to the [expected] way in which Terraform works, it's not possible to detect these naming conflicts when both resources are being created in parallel. The only way that the provider can detect this at apply time, is when resources are created serially, such that the import check for the second resource will detect the resource created earlier. When both resources are created in parallel, these checks will race past each other and both pass.
