### ISSUE TITLE
Unable to create Managed Disk from a snapshot if the source disk of the snapshot is deleted

### ISSUE THREAD

**Issue by Demokdawa** [hashicorp/terraform-provider-azurerm#18979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.20.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_disk

### Terraform Configuration Files

```hcl
## Static data for Almalinux Snapshot
data "azurerm_snapshot" "snapshot_alma" {
  name                = "snapshot_ALMALINUX_8_DO_NOT_DELETE"
  resource_group_name = data.azurerm_resource_group.rg_snap.name
}

## Create Managed Disk from the Snapshot
resource "azurerm_managed_disk" "snap_copy" {
  name                  = lower("disk_sys_${lower(replace(var.virtual_machine_name, "/[[:^alnum:]]/", ""))}")
  location              = data.azurerm_resource_group.rg.location
  resource_group_name   = data.azurerm_resource_group.rg.name
  storage_account_type  = var.os_disk_storage_account_type
  create_option         = "Copy"
  source_resource_id    = data.azurerm_snapshot.snapshot_alma.source_resource_id
  disk_size_gb          = "65"

  tags                  = {
    ENV = "TEST-DISK-TF"
  }
}
```

### Debug Output/Panic Output

```shell
module.vm_test-module-snapshot.azurerm_managed_disk.snap_copy: Creating...
╷
│ Error: creating/updating Managed Disk "disk_sys_testmodulesnapshot" (Resource Group "RG_POC_ANSIBLE"): compute.DisksClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="NotFound" Message="Resource disk-sys-zvf-lalm008 is not found."
│
│   with module.vm_test-module-snapshot.azurerm_managed_disk.snap_copy,
│   on modules/azure_create_vm_from_snapshot/main.tf line 28, in resource "azurerm_managed_disk" "snap_copy":
│   28: resource "azurerm_managed_disk" "snap_copy" {
```

### Expected Behaviour

I should be able to create a managed disk from a snapshot without it's source disk. It's possible in AZCLI and on the Portal.

### Actual Behaviour

Doesn't work

### Steps to Reproduce

1. terraform apply

**Comment by myc2h6o** [comment]
Hi @Demokdawa thanks for opening the issue! Taking a look at the config, id of the snapshot should be used as the disk is created from the snapshot instead of the source to create the snapshot

```hcl
source_resource_id    = data.azurerm_snapshot.snapshot_alma.id
```

**Comment by myc2h6o** [comment]
After taking another look, the document seems not clear, which could lead to a confusion. I've opened #18984 to add the Snapshot option to the `source_resource_id`

**Comment by Demokdawa** [comment]
Hi,

I can confirm i used the full id of the snapshot ("/subscription/etc...") instead of using a datasource to get the snapshot, and it worked !

Ty :)
