### ISSUE TITLE
Unable to use contact and license blocks in azurerm_api_management_api

### ISSUE THREAD

**Issue by mcarrgit** [hashicorp/terraform-provider-azurerm#18982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.26.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
Test config files can be found here: https://drive.google.com/file/d/1JTUF25XkHxr9NOur2ATUhD0wkm_UK0eN/view?usp=sharing
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported block type
│ 
│   on ../terraform-azurerm-apim/modules/api_ts/main.tf line 34, in resource "azurerm_api_management_api" "this":
│   34:   contact {
│ 
│ Blocks of type "contact" are not expected here.
╵
╷
│ Error: Unsupported block type
│ 
│   on ../terraform-azurerm-apim/modules/api_ts/main.tf line 41, in resource "azurerm_api_management_api" "this":
│   41:     license {
│ 
│ Blocks of type "license" are not expected here.
```

### Expected Behaviour

Expecting to get a successful plan with the contact and license blocks configured, as per the documentation at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api

### Actual Behaviour

An error occurs during the plan stage

### Steps to Reproduce

terraform plan

This can be tested with a module call set up as so:

`module "api_ts" {
source = "../api_ts"

#API
api_name = "api-test"
revision = 1
api_management_name = "test-apim"
display_name = "displayname"
resource_group_name = "test-rg"

#APIM
environment         = "dev"
service             = "devops"
region              = "aueast"
sku_name = "Developer_1"
publisher_name = "test"
publisher_email = "test@email.com"
}
`

**Comment by xuzhang3** [comment]
@mcarrgit this features start  support since [v3.27.0](https://github.com/hashicorp/terraform-provider-azurerm/milestone/204?closed=1)

**Comment by mcarrgit** [comment]
Ah… too easy. Thanks for pointing that out!

On 27 Oct 2022, at 1:53 pm, xuzhang3 ***@***.***> wrote:

﻿

@mcarrgit<https://github.com/mcarrgit> this features start support since v3.27.0<https://github.com/hashicorp/terraform-provider-azurerm/milestone/204?closed=1>

**Comment by manicminer** [comment]
Thanks for reporting, as mentioned by @xuzhang3 these fratures can be used by upgrading to a supported provider version.
