### ISSUE TITLE
azurerm_log_analytics_cluster size_gb default value generates unnecessary costs 

### ISSUE THREAD

**Issue by CKnoppas** [hashicorp/terraform-provider-azurerm#19001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_cluster

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_log_analytics_cluster" "example" {
  name                = "example-cluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
the resource is created using 1000GB/day pricing tier, which is almost double the cost compared to the 500GB/day tier. 

https://azure.microsoft.com/en-us/pricing/details/monitor/

The change was introduced through the linked pull request and in my opinion it should be changed to minimum, to avoid unnecessary costs.
```

### Expected Behaviour

- resource should  be created using the minimum 500GB /day pricing tier 
- in the documentation the default should be set to 500GB  

### Actual Behaviour

resource is created using the size_gb of 1000GB 

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/17780 
https://github.com/hashicorp/terraform-provider-azurerm/pull/17780/commits/b11ea497fc596a9ba8b344f92635b352208bcc2b

**Comment by wald-tq** [comment]
Maybe the default can be set even lower.
In the docs the specified minimum is 500 but in the Azure Portal you can go as low as 100 GB

**Comment by sebaspf** [comment]
There is also a pay-as-you-go option where you only pay for the real usage of the resource. IMHO, ALL defaults should be set to the minimum fix costs as possible (normally minimum amount of resources or quotas) as this prevents unexpected and possibly very high costs. The given setting of 1000GB/Day generates costs of 2k$/Day! this is too much for the first test deployment where you normally would use the defaults.

![image](https://user-images.githubusercontent.com/29202056/198035604-b6c76f5c-db4b-460f-a7c4-774614e09586.png)

The Recommended pricing Tire in Azur is Pay-as-you-go:
![image](https://user-images.githubusercontent.com/29202056/198036518-1517b05e-5cd7-4f2c-a9f7-351728743bff.png)

**Comment by CKnoppas** [comment]
Unfortunately there is no pay-as-you-go option for the dedicated cluster. 500GB/day is the minimum tier avaliable. But this should be the default when creating the ressource.
https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#dedicated-clusters 

I aggree that all defaults should be set to minimum, though ! Thanks for the comment

**Comment by Amier3** [comment]
Hey @CKnoppas 

We appreciate the input! I agree with this change, as a general rule if there's a minimum value for a resource we should stick to that minimum. I'll talk this over with the team and see if there's any reason we can't change this ASAP.

**Comment by CKnoppas** [comment]
okay thanks! please notify if opening a pull request would be of any help.

**Comment by WodansSon** [comment]
@Amier3 and @CKnoppas,

Looking at the code, it appears that the validation was updated while the `default` was not, this would be a super easy fix. 😸 

```go
"size_gb": {
	Type:         pluginsdk.TypeInt,
	Optional:     true,
	Default:      1000,
	ValidateFunc: validation.IntInSlice([]int{500, 1000, 2000, 5000}),
},
```

**Comment by wald-tq** [comment]
@WodansSon the smaller sizes are also missing:

`100, 200, 300, 400, 500, 1000, 2000, 5000`

See following screenshot from Azure Portal:

![image](https://user-images.githubusercontent.com/5268747/198247624-ccdf0272-27be-48a8-aa6c-1a2e414cdeb7.png)

**Comment by WodansSon** [comment]
@wald-tq, interesting... we haven't been told to implement anything below the 500 GB. Let me reach out to the service team and see what is going on here.

**Comment by WodansSon** [comment]
@wald-tq, I have heard back from the service team and it appears that the Portal UI maybe a bit confusing:

Log Analytics workspaces can have lower tiers, as you mentioned above, but clusters start at 500 GB:

* [Log Analytics Workspace Tiers](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/daily-cap)
* [Log Analytics Cluster Tiers](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-dedicated-clusters#cluster-pricing-model)

With that said, the fix here would be to lower the `clusters` minimum to 500 GB, but that would be a breaking change to the already existing resource since it was released with a default of 1000 GB. The minimum default value can be changed to 500 GB at the next major release of the provider in v4.0.
