### ISSUE TITLE
Terraform apply failing trying to update soft delete retention days to a Purge protection or Soft delete is already enabled.

### ISSUE THREAD

**Issue by bamb00** [hashicorp/terraform-provider-azurerm#19006]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.0

### AzureRM Provider Version

0.14.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
module "kv_permissiontest" {
  source   = "xxxxxxxxxxxxx"
  location = local.location
  rg_name  = module.rg_permissiontest.name
  tags     = module.tag.tags

  keyvault_name               = "xxxxx${local.environment}permissiontestkv"
  sku_name                    = "premium"
  purge_protection_enabled    = true
}
```

### Debug Output/Panic Output

```shell
Error: updating Key Vault "xxxxxuatpermissiontestkv" (Resource Group "xxxxxxxx-uat-xxxxx-permissiontest-rg"): once Soft Delete has been Enabled it's not possible to change `soft_delete_retention_days`
```

### Expected Behaviour

The retention period is already set when the purge protection and soft delete turn-on.  The TF is updating the retention days period.

retention days is optional TF should ignore.

### Actual Behaviour

Error: updating Key Vault "xxxxxuatpermissiontestkv" (Resource Group "xxxxxxxx-uat-xxxxx-permissiontest-rg"): once Soft Delete has been Enabled it's not possible to change `soft_delete_retention_days`

### Steps to Reproduce

n/a

### Important Factoids

no

### References

 n/a

**Comment by teowa** [comment]
Hi @bamb00 , thanks for opening this issue.
Seems the error is because the `soft_delete_retention_days` property is changed in Terraform config, but this is actually by design, from [official doc](https://learn.microsoft.com/en-us/azure/key-vault/general/soft-delete-overview#soft-delete-behavior):
> The default retention period is 90 days but, during key vault creation, it is possible to set the retention policy interval to a value from 7 to 90 days through the Azure portal. The purge protection retention policy uses the same interval. **Once set, the retention policy interval cannot be changed.**

The last sentence said the `soft_delete_retention_days` cannot be changed once set.

**Comment by bamb00** [comment]
Hi @teowa, What am I missing from the code block? Do I need to put in 'soft_delete_retention_days=90'? I didn't have it in the code block that would be updating the retention days.

Thanks.

**Comment by teowa** [comment]
Hi @bamb00 , after PR https://github.com/hashicorp/terraform-provider-azurerm/pull/10088 (v2.42.0), `soft_delete_retention_days` is default to 90 days, even it is not set it in TF config. But from the error message you provided, seems you are using a older version (pre v2.42.0) of the provider, which has no default value for `soft_delete_retention_days`. And here I think it is better to explicitly set a value (between 7 and 90) for `soft_delete_retention_days` in creation and keep it unchanged in later apply.
