### ISSUE TITLE
Support for Defender CSPM for Defender for cloud plans

### ISSUE THREAD

**Issue by websolut** [hashicorp/terraform-provider-azurerm#19004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft are actively developing the Defender for Cloud. 

Current TF code does not enable 'Defender CSPM' free plan at the moment. Before it was 'Cloud Security Posture management free' and it would be enabled by default as soon as any advanced plans are enabled.

This is request to add an additional plan to azurerm_security_center_subscription_pricing resource to control this basic plan.

### New or Affected Resource(s)/Data Source(s)

azurerm_azurerm_security_center_subscription_pricing

Cli implementation 
```
az security pricing list

az security pricing create -n CloudPosture --tier 'standard'
```
It seems that we just need to allow CloudPosture.

I also think CosmosDB plan is not available.

**Comment by fslef** [comment]
The new 'CloudPosture' parameter is missing from the documentation.
Would it be possible to add it ?
