### ISSUE TITLE
azurerm_postgresql_flexible_server_configuration should support blank or null values

### ISSUE THREAD

**Issue by jmorgannht** [hashicorp/terraform-provider-azurerm#19005]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server_configuration" "res-27" {
  name      = "azure.extensions"
  server_id = abc
  value     = ""
}
```

### Debug Output/Panic Output

```shell
Error: expected "value" to not be an empty string, got
with module.postgresql_flexible_server.azurerm_postgresql_flexible_server_configuration.postgres_fs_config["default_tablespace"],
on ..\..\module_groups\postgresql_flexible_server\postgres.tf line 52, in resource "azurerm_postgresql_flexible_server_configuration" "postgres_fs_config":52:   value = each.value
```

### Expected Behaviour

Should allow blank values for postgresql configurations.  There are several default configurations in azure that are blank by default and terraform should be able to handle that, i.e. "default_tablespace", "ssl_max_protocol_version", "pg_partman_bgw.role". "pg_partman_bgw.dbname", "application_name", "azure.extensions", "pgaudit.role"

### Actual Behaviour

Throws error expecting a non-empty string.  

Error: expected "value" to not be an empty string, got
with module.postgresql_flexible_server.azurerm_postgresql_flexible_server_configuration.postgres_fs_config["default_tablespace"],
on ..\..\module_groups\postgresql_flexible_server\postgres.tf line 52, in resource "azurerm_postgresql_flexible_server_configuration" "postgres_fs_config":52:   value = each.value

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it's by TF design. You can remove the part of "azurerm_postgresql_flexible_server_configuration" to set it as empty.

**Comment by jmorgannht** [comment]
That is counter to what we are trying to achieve by controlling the postgres configurations.  Those settings affect behavior and removing them from the configuration is a workaround, just not a good one as it leaves those values untracked.  There are many azurerm resources attributes where we can set null values.  Why is this set any different?

**Comment by jacobgaumond** [comment]
I've been able to pass blank values to the "azurerm_postgresql_flexible_server_configuration" resource by passing a string with only a blank space instead of an empty string.

```
resource "azurerm_postgresql_flexible_server_configuration" "this" {
  name      = "azure.extensions"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = " "
}
```

This successfully unselects all extensions listed under the "azure.extensions" parameter for the database server on the Azure portal. I've been able to verify this using Terraform v1.5.7, AzureRM v3.98.0, and PostgreSQL v15.6.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @jacobgaumond‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
