### ISSUE TITLE
Support `contentStoragePolicy` and `jobStorageAccount` in `azurerm_stream_analytics_job`

### ISSUE THREAD

**Issue by ThreeFive-O** [hashicorp/terraform-provider-azurerm#19018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Stream Analytics Job now allow to store private data assets in dedicated storage account. See [Data protection in Azure Stream Analytics](https://learn.microsoft.com/en-us/azure/stream-analytics/data-protection)

Assigning a dedicated storage account for private data assets can only be done on creation of a Stream Analytics job. Not modification/update afterwards.

### New or Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_job

### Potential Terraform Configuration

```hcl
resource "azurerm_stream_analytics_job" "example" {
  name                = "asa-job-example"
  location            = "westus"
  resource_group_name = "rg-asa"

  identity {
    type = "SystemAssigned"
  }

  content_storage_policy = "JobStorageAccount" # Requires "job_storage_account" block to be present; Default: "SystemAccount"

  job_storage_account {
    account_name = "saasajobaccount"
    authentication_mode = "Msi" # Alternatively "ConnectionString"
    # account_key = "" # Only required for authentication_mode = "ConnectionString"
  }
}
```

### References

REST API Documentation here: https://learn.microsoft.com/en-us/rest/api/streamanalytics/2020-03-01/streaming-jobs/create-or-replace?tabs=HTTP

SDK support here: https://github.com/hashicorp/go-azure-sdk/blob/0e8a0b3a8f7c2ad1ef138a40c13159ece58b3e44/resource-manager/streamanalytics/2020-03-01/streamingjobs/model_streamingjobproperties.go#L15
and here: https://github.com/hashicorp/go-azure-sdk/blob/0e8a0b3a8f7c2ad1ef138a40c13159ece58b3e44/resource-manager/streamanalytics/2020-03-01/streamingjobs/model_streamingjobproperties.go#L15

**Comment by jiaweitao001** [comment]
PR merged. https://github.com/hashicorp/terraform-provider-azurerm/pull/19120
