### ISSUE TITLE
azurerm_web_application_firewall_policy custom_rules does not support match_conditions > operator "Any"

### ISSUE THREAD

**Issue by sanderrhorst** [hashicorp/terraform-provider-azurerm#19013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.3.2

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Terraform Configuration Files

```hcl
resource "azurerm_web_application_firewall_policy" "agw_waf_policy_aks_tst" {
  name                = "tst-weu-001"
  resource_group_name = "test"
  location            = var.location

  custom_rules {
    name      = "restRuleUploadExclusion"
    priority  = 40
    rule_type = "MatchRule"
    
    match_conditions {
      match_variables {
        variable_name = "PostArgs"
        selector      = "Something"
      }
      operator           = "Any"
      negation_condition = false
      match_values       = []
    }
    action = "Log"
  }

  policy_settings {
    enabled            = true
    mode               = "Detection"
    request_body_check = true
  }

  managed_rules {

    managed_rule_set {
      type    = "OWASP"
      version = "3.2"
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected custom_rules.1.match_conditions.1.operator to be one of [IPMatch GeoMatch Equal Contains LessThan GreaterThan LessThanOrEqual GreaterThanOrEqual BeginsWith EndsWith Regex], got Any
│
│   with azurerm_web_application_firewall_policy.agw_waf_policy_aks_tst,
│   on application_gateway_waf_policy.tf line 48, in resource "azurerm_web_application_firewall_policy" "agw_waf_policy_aks_tst":
│   48:       operator           = "Any"
│
```

### Expected Behaviour

I expext azurerm provider to deploy the waf_policy with custom rules as I have configured them without errors. "Any" is a operator value that is supported when you configure the WAF_policy via the portal, so I want that in terraform as well.

### Actual Behaviour

Terraform trows an error when I validate my config.

### Steps to Reproduce

1. Create a waf_policy.tf file in an empty dir and setup a provider.tf
2. Terraform init
3. Terraform validate

**Comment by wuxu92** [comment]
Hi @sanderrhorst thanks for your feedback, The `Any` value was added in version[ `2022-01-01`](https://github.com/Azure/azure-rest-api-specs/blob/e82a24def11ffc98cc263884f9f1742c99f2df5e/specification/network/resource-manager/Microsoft.Network/stable/2022-01-01/webapplicationfirewall.json#L605) but azurerm was blocked by the Azure SDK, we have to wait for the new SDK then we can add this value to the validation.

**Comment by sanderrhorst** [comment]
> Hi @sanderrhorst thanks for your feedback, The `Any` value was added in version[ `2022-01-01`](https://github.com/Azure/azure-rest-api-specs/blob/e82a24def11ffc98cc263884f9f1742c99f2df5e/specification/network/resource-manager/Microsoft.Network/stable/2022-01-01/webapplicationfirewall.json#L605) but azurerm was blocked by the Azure SDK, we have to wait for the new SDK then we can add this value to the validation.

Thanks for your reply! Do you have an estimation on this? Or can I do something to speed up the process?

**Comment by rahulgurunule** [comment]
@wuxu92  I am getting below error for ANY operator and it is asking "Use at least api-version '2021-12-01'".
Is it possible to update code with api-version '2021-12-01' if it already have ANy value and not blocked by existing Azure SDK.

I can see API Version 2021-08-01 is hardcoded in (https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/Azure/azure-sdk-for-go/services/network/mgmt/2021-08-01/network/webapplicationfirewallpolicies.go)

│ Error: creating Application Gateway Web Application Firewall Policy: (Name "AGW-EUW-MYI-DEV-001-POLICY" / Resource Group "RSG-EUW-MYI-DEV"): network.WebApplicationFirewallPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ApplicationGatewayPropertyNotSupportedApiVersionTooOld" Message="Specified api-version '2021-08-01' does not support property 'Any' in context 'properties.customRules[0],properties.customRules[2]'. Use at least api-version '2021-12-01' or remove property 'Any' from the request body." Details=[] 
│  
│  with module.aks.azurerm_web_application_firewall_policy.waf_policy, 
│  on ..\..\modules\aks_appgw_dev\main.tf line 305, in resource "azurerm_web_application_firewall_policy" "waf_policy": 
│  305: resource "azurerm_web_application_firewall_policy" "waf_policy" {

**Comment by sanderrhorst** [comment]
@wuxu92, please check comment of @rahulgurunule and please fix this as the solution is already provided :)

**Comment by sanderrhorst** [comment]
Any updates on this? Solution can't be that hard as it is already provided. This is blocking our infra being fully code...

**Comment by wuxu92** [comment]
> Any updates on this? Solution can't be that hard as it is already provided. This is blocking our infra being fully code...

Very sorry for my delay repsonse. i have created a PR to add the `Any` value 🥪

**Comment by sanderrhorst** [comment]
@wuxu92  Please reopen this and fix it... The any operator is now allowed, but the match_values parameter is not supported when the operator is any. 
But the provider is validating if the match_values is provided. If not, it fails. But when I fill the match_values inside the match_conditions block, the api comes back with an error. 

Error when match_values is missing:
│ The argument "match_values" is required, but no definition was found.

Error when match_values is filled with ["*"]:
Message="Custom Rule 'restRuleUploadExclusion' must not have any match value(s) in its condition in context 'System.Collections.Generic.List`1[System.String]'." Details=[]

Please fix this in next version. I have waited for 6 months and now the solution is not working :(:(
