### ISSUE TITLE
Can't create Windows Virtual Machine with community shared image gallery

### ISSUE THREAD

**Issue by SirThomsalot** [hashicorp/terraform-provider-azurerm#19016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine" "domain_controller" {
  name                  = "vm-dc01-${var.kunden_kuerzel}"
  location              = azurerm_resource_group.rg.location
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [azurerm_network_interface.dc_nic.id]
  admin_username        = var.admin_username
  admin_password        = var.admin_password
  size                  = var.dc_vm_size
  source_image_id       = "/subscriptions/b1905f5e-e600-4878-a3f1-c04bfc78f323/resourceGroups/Community-Share/providers/Microsoft.Compute/galleries/ManagedVMsSMEAIT/images/SMEA_Server_2022_Datacenter_German/versions/latest"
```

### Debug Output/Panic Output

```shell
│ Error: creating Windows Virtual Machine: (Name "vm-dc01-wiass" / Resource Group "rg-datacenter-wiass"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/0df91ae0-9b93-4824-a1d2-7cd28383f98c/resourceGroups/rg-datacenter-wiass/providers/Microsoft.Compute/virtualMachines/vm-dc01-wiass', however the current tenant '31d747fe-66ec-4f79-9578-a9a138b6d1af' is not authorized to access linked subscription 'b1905f5e-e600-4878-a3f1-c04bfc78f323'."
│
```

### Expected Behaviour

VM should be created with image.

### Actual Behaviour

Error with unauthorized message. 
VM is now deployed.

Deploying the image via powershell or ARM is working.

**Comment by myc2h6o** [comment]
Hi @SirThomsalot community shared image version id should be in a format like `/CommunityGalleries/<community gallery name, like: ContosoImages-1a2b3c4d-1234-abcd-1234-1a2b3c4d5e6f>/Images/<image name>/Versions/latest` as described at https://learn.microsoft.com/azure/virtual-machines/vm-generalized-image-version?tabs=portal%2Ccli2#create-a-vm-from-a-community-gallery-image. Could you try with this id format?
