### ISSUE TITLE
Support for [Inline script for azurerm_kusto_script rather using a separate storage account]

### ISSUE THREAD

**Issue by sahanruwanga** [hashicorp/terraform-provider-azurerm#19015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to the latest azurerm provider version, we still need to have a separate storage account to host KQL queries as blobs to create Azure Kusto cluster resources. Is there any timeline or plan to provide the support to use local files which can be provided as inline files to create required Azure Kusto cluster resources from azurerm_kusto_script module? 

It would be better in certain angles such as cost and maintainability of the resource. 

### New or Affected Resource(s)/Data Source(s)

azurerm_3.28.0

### Potential Terraform Configuration

```hcl
resource "azurerm_kusto_script" "example" {
  name                               = "example"
  database_id                        = azurerm_kusto_database.example.id
  script_path                        = <local_path_to_script_for_resource_creation>
  continue_on_errors_enabled         = true
  force_an_update_when_value_changed = "first"
}
```

**Comment by liuwuliuyun** [comment]
We already have such support, for example

resource "azurerm_kusto_script" "test" {
  name                               = "acctest-ks-%d"
  database_id                        = azurerm_kusto_database.test.id
  continue_on_errors_enabled         = true
  force_an_update_when_value_changed = "first"
  script_content                     = ".create table MyTable (Level:string, Timestamp:datetime, UserId:string, TraceId:string, Message:string, ProcessId:int32)"
}

**Comment by liuwuliuyun** [comment]
If you prefer local files instead of inline script, there is another data source called [local_file](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) could be used. After you create local_file data source/resource you could export its content to script_content.

**Comment by liuwuliuyun** [comment]
Welcome to leave comment if you have problems using above resources.

**Comment by sahanruwanga** [comment]
> If you prefer local files instead of inline script, there is another data source/resource called [local_file](https://registry.terraform.io/providers/hashicorp/local/latest/docs/data-sources/file) could be used. After you create local_file data source/resource you could export its content to script_content.

I have a requirement of having 4 queries and to use a single `kusto_script` for that. As per you comment, I might achieve this using `local_file` and `script_content` as follows.

```
data "local_file" "adx_query" {
    filename = "my-path/adx-query.txt"
}
```

```
resource "azurerm_kusto_script" "my_kusto_script" {
  name = "my-kusto-script"
  database_id = azurerm_kusto_database.my_kusto_db.id
  continue_on_errors_enabled = true
  force_an_update_when_value_changed = "first"
  script_content = data.local_file.adx_query.content
}
```

Is this correct?

**Comment by liuwuliuyun** [comment]
In theory, this should work if your file is encoded with UTF-8. And I suggest to have a test run before going to production.

**Comment by sahanruwanga** [comment]
> In theory, this should work if your file is encoded with UTF-8. And I suggest to have a test run before going to production.

Thanks for the info @liuwuliuyun, I'll try it!

**Comment by stacda01** [comment]
Rather than making a new issue I will hop in on this. @liuwuliuyun 

I have tried two ways of calling it directly in the resource and I receive this error:
"Script: Code="BadInput" Message="Internal Server Error"

script resource
```
resource "azurerm_kusto_script" "script-a" {
  name = "script-a"
  database_id = var.databaseid
  script_content = data.local_file.script.content
  #script_content = ".create table MyLogs (Column1: string, Column2: datetime)"
  continue_on_errors_enabled = true
  force_an_update_when_value_changed = "first"
}
```
data block
```
data "local_file" "script" {
  filename = "path/adx-script.txt"
}
```
adx-script.txt
```
.create table MyLogs (Column1: string, Column2: datetime)
```

**Comment by liuwuliuyun** [comment]
Hi @stacda01, I have tried your script with following config and it works on my local.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "yunliughissue"
  location = "West Europe"
}

resource "azurerm_kusto_cluster" "example" {
  name                = "exampleyliu"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    name     = "Dev(No SLA)_Standard_D11_v2"
    capacity = 1
  }
}

resource "azurerm_kusto_database" "example" {
  name                = "exampleyliu"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cluster_name        = azurerm_kusto_cluster.example.name
}

resource "azurerm_kusto_script" "example" {
  name                               = "exampleyliu"
  database_id                        = azurerm_kusto_database.example.id
  continue_on_errors_enabled = true
  force_an_update_when_value_changed = "first"
  script_content = ".create table MyLogs (Column1: string, Column2: datetime)"
}
```

**Comment by chase-miller** [comment]
Thanks for posting this. I ended up with a slight variation that works great with `version = "~> 3.37.0"`

```tf
locals {
  kusto_combined_path = "../../../scripts/kusto/combined.kql"
}

data "local_file" "combinedscript" {
  filename = local.kusto_combined_path
}

resource "azurerm_kusto_script" "singlekustoscript" {
  name                               = "singlekustoscript"
  database_id                        = azurerm_kusto_database.spotlight.id
  script_content                     = data.local_file.combinedscript.content
  continue_on_errors_enabled         = false
  force_an_update_when_value_changed = md5(file(local.kusto_combined_path)) # execute this whenever the .kql file changes
}
```

Hope this helps someone.

**Comment by chase-miller** [comment]
Thanks for posting this. I ended up with a slight variation that works great with `version = "~> 3.37.0"`

```tf
locals {
  kusto_combined_path = "../../../scripts/kusto/combined.kql"
}

data "local_file" "combinedscript" {
  filename = local.kusto_combined_path
}

resource "azurerm_kusto_script" "singlekustoscript" {
  name                               = "singlekustoscript"
  database_id                        = azurerm_kusto_database.mydb.id
  script_content                     = data.local_file.combinedscript.content
  continue_on_errors_enabled         = false
  force_an_update_when_value_changed = md5(file(local.kusto_combined_path)) # execute this whenever the .kql file changes
}
```

Hope this helps someone.

**Comment by chase-miller** [comment]
Or this if you want to store multiple kusto script files in a directory and have them executed via tf whenever one is added/changed:

```tf
locals {
  kusto_scripts_path = "../../../scripts/kusto"
  kusto_script_files = fileset(local.kusto_scripts_path, "*.kql")
  kusto_scripts      = { for kusto_script in local.kusto_script_files : kusto_script => file("${local.kusto_scripts_path}/${kusto_script}") }
}

resource "azurerm_kusto_script" "spotlight_kusto_script" {
  for_each                           = local.kusto_scripts
  name                               = each.key
  database_id                        = azurerm_kusto_database.spotlight.id
  script_content                     = each.value
  continue_on_errors_enabled         = false
  force_an_update_when_value_changed = md5(each.value) # execute this whenever the .kql file changes
}
```

Although I'm a bit worried about order of execution with this approach.

**Comment by chase-miller** [comment]
Or this if you want to store multiple kusto script files in a directory and have them executed via tf whenever one is added/changed:

```tf
locals {
  kusto_scripts_path = "../../../scripts/kusto"
  kusto_script_files = fileset(local.kusto_scripts_path, "*.kql")
  kusto_scripts      = { for kusto_script in local.kusto_script_files : kusto_script => file("${local.kusto_scripts_path}/${kusto_script}") }
}

resource "azurerm_kusto_script" "spotlight_kusto_script" {
  for_each                           = local.kusto_scripts
  name                               = each.key
  database_id                        = azurerm_kusto_database.mydb.id
  script_content                     = each.value
  continue_on_errors_enabled         = false
  force_an_update_when_value_changed = md5(each.value) # execute this whenever the .kql file changes
}
```

Although I'm a bit worried about order of execution with this approach.

**Comment by holms** [comment]
Maybe these examples could go to documentation? I was pulling my hairs how can I provision ADX before making event hub data connection with mappings. If there's no table eventhub data connection is impossible to create.  So I believe this is crucial to have somehere in terraform docs so people would know how to create a db schema? So sad that PR for `azurerm_kusto_table` been closed this is must-have for this provider.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @liuwuliuyun‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
