### ISSUE TITLE
Assign More Than one User Managed Identity with azurerm_subscription_policy_assignment 

### ISSUE THREAD

**Issue by Eslam10** [hashicorp/terraform-provider-azurerm#19037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.2

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_subscription_policy_assignment

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "current" {}

resource "azurerm_subscription_policy_assignment" "main" {
  name                 = "test-policy-assignment"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/361c2074-3595-4e5d-8cab-4f21dffc835c"
  subscription_id      = data.azurerm_subscription.current.id
  identity {
    type         = "UserAssigned"
    identity_ids = ["/subscriptions/xxx/resourceGroups/rg1/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-user-assigned-managed-identity", "/subscriptions/xxx/resourceGroups/rg1/providers/Microsoft.ManagedIdentity/userAssignedIdentities/new-managed-identity"]
  }
  location = "west europe"
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Policy Assignment ID: (Assignment Name "test-policy-assignment" / Scope "/subscriptions/xxx"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidReso
urceIdentity" Message="The policy assignment 'test-policy-assignment' request is invalid. One and only one identity can be specified.  You cannot specify both user assigned and system assigned identities, nor can you specify more than one user assigned identity."
```

### Expected Behaviour

`identity_ids` Argument reference should be of type `string` since you can not assign more than one managed identity to the policy assignment. 
This works fine if you add only one value to `identity_ids` list.

### Actual Behaviour

Error when adding more than one user assigned managed identity. 

### Steps to Reproduce

1. Assign a policy definition that uses a managed identity using azurerm_subscription_policy_assignment resource.
2. Use UserAssigned managed identity type.
3. Add more than one value to `identity_ids` argument.

**Comment by wuxu92** [comment]
Hi @Eslam10 Thanks for your information though the server API did not accept more than one user assigned identity id in this test, but API swagger definition appears accept more than

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
