### ISSUE TITLE
azurerm_security_center_subscription_pricing

### ISSUE THREAD

**Issue by DevanshuSyk** [hashicorp/terraform-provider-azurerm#19046]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello I am trying to onboard security center  in Azure using defender plan but apparently there are no option for 
cosmos db and cloudposture ( this has been released recently) .Error: expected resource_type to be one of [AppServices ContainerRegistry KeyVaults KubernetesService SqlServers SqlServerVirtualMachines StorageAccounts VirtualMachines Arm Dns OpenSourceRelationalDatabases Containers], got cosmosdb
│ 
│   with azurerm_security_center_subscription_pricing.mdc_cosmosdb,
│   on main.tf line 57, in resource "azurerm_security_center_subscription_pricing" "mdc_cosmosdb":
│   57:   resource_type = "cosmosdb"
│ 
╵
╷
│ Error: expected resource_type to be one of [AppServices ContainerRegistry KeyVaults KubernetesService SqlServers SqlServerVirtualMachines StorageAccounts VirtualMachines Arm Dns OpenSourceRelationalDatabases Containers], got CloudPosture
│ 
│   with azurerm_security_center_subscription_pricing.mdc_cloudposture,
│   on main.tf line 62, in resource "azurerm_security_center_subscription_pricing" "mdc_cloudposture":
│   62:   resource_type = "CloudPosture"

### New or Affected Resource(s)/Data Source(s)

azurerm_security_center_subscription_pricing

### Potential Terraform Configuration

```hcl
resource "azurerm_security_center_subscription_pricing" "mdc_cosmosdb" {
  tier          = "Standard"
  resource_type = "cosmosdb"
}
```

### References

Hello I am trying to onboard security center  in Azure using defender plan but apparently there are no option for 
cosmos db and cloudposture ( this has been released recently) .Error: expected resource_type to be one of [AppServices ContainerRegistry KeyVaults KubernetesService SqlServers SqlServerVirtualMachines StorageAccounts VirtualMachines Arm Dns OpenSourceRelationalDatabases Containers], got cosmosdb
│ 
│   with azurerm_security_center_subscription_pricing.mdc_cosmosdb,
│   on main.tf line 57, in resource "azurerm_security_center_subscription_pricing" "mdc_cosmosdb":
│   57:   resource_type = "cosmosdb"
│ 
╵
╷
│ Error: expected resource_type to be one of [AppServices ContainerRegistry KeyVaults KubernetesService SqlServers SqlServerVirtualMachines StorageAccounts VirtualMachines Arm Dns OpenSourceRelationalDatabases Containers], got CloudPosture
│ 
│   with azurerm_security_center_subscription_pricing.mdc_cloudposture,
│   on main.tf line 62, in resource "azurerm_security_center_subscription_pricing" "mdc_cloudposture":
│   62:   resource_type = "CloudPosture"

**Comment by favoretti** [comment]
Fixed by #19273
