### ISSUE TITLE
azurerm_network_connection_monitor creates extra entries and no topology available

### ISSUE THREAD

**Issue by nigelbelanger** [hashicorp/terraform-provider-azurerm#19041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_network_connection_monitor

### Terraform Configuration Files

```hcl
resource "azurerm_network_connection_monitor" "ncme" {
  name               = "ICMP Test"
  network_watcher_id = data.azurerm_network_watcher.anwe.id
  location           = data.azurerm_network_watcher.anwe.location
  tags               = var.tags

  endpoint {
    name               = "${azurerm_windows_virtual_machine.vm.name}"
    target_resource_id = azurerm_windows_virtual_machine.vm.id

    filter {
      item {
        type = "AgentAddress"
      }
      type = "Include"
    }
  }

  endpoint {
    name    = "dest_host1"
    address = "10.0.0.10"
  }

  endpoint {
    name    = "dest_host2"
    address = "10.0.0.20"
  }  

  test_configuration {
    name                      = "ICMPConfig"
    protocol                  = "Icmp"
    test_frequency_in_seconds = 60

    icmp_configuration {
      trace_route_enabled     = true 
    }

    success_threshold {
      checks_failed_percent   = 1
      round_trip_time_ms      = 500
    }
  }

  test_group {
    name                     = "AzureToOnPremICMP"
    destination_endpoints    = ["dest_host1","dest_host2"]
    source_endpoints         = ["${azurerm_windows_virtual_machine.vm.name}"]
    test_configuration_names = ["ICMPConfig"]
  }

  notes = "ICMP Testing"

  output_workspace_resource_ids = [azurerm_log_analytics_workspace.shared.id]

  depends_on = [azurerm_virtual_machine_extension.nwa_ext]
}
```

### Debug Output/Panic Output

```shell
The plan and apply work but within Azure, there are two additional entries create above the correct entries and the correct entries do not show the topology.
```

### Expected Behaviour

Two entries should be created reflecting a test from the src_host1 and each dest_host.  Once expanded in Azure Connection Monitor, a topology map should be visible.  Was working in Terraform v0.13.3

### Actual Behaviour

Once the connection monitor was created within Azure, there were two additional entries create above the correct entries and the correct entries do not show the topology.  The topology map was being displayed in Terraform v0.13.3 however, the two incorrect entries were showing up there as well.  Another note is that the entries show that they are to be deleted (little info icon is displayed).  

### Steps to Reproduce

Manually create a monitor like the one used in terraform.  Then create the monitors with a different name via terraform.  You will notice that the manual entry shows ONLY the correct connection monitors and will display the topology map.  The Terraform code will not display the topology map and they include two tests.  

### Important Factoids

Standard Azure Public

### References

N/A

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems the two additional entries are created by adding the [`filter`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_connection_monitor#filter) property.

![image](https://user-images.githubusercontent.com/19754191/198970807-80840345-4ad0-45e0-af6d-b20a80f01e1d.png)

tf config:
```
resource "azurerm_network_connection_monitor" "ncme" {
  name               = "ICMPtest16"
  network_watcher_id = azurerm_network_watcher.test.id
  location           = azurerm_network_watcher.test.location

  endpoint {
    name               = azurerm_virtual_machine.src.name
    target_resource_id = azurerm_virtual_machine.src.id

    filter {
      item {
        address = azurerm_virtual_machine.src.id
        type = "AgentAddress"
      }
      type = "Include"
    }
  }

  endpoint {
    name    = "dest_host1"
    address = "10.0.0.10"
  }

  endpoint {
    name    = "dest_host2"
    address = "10.0.0.20"
  }  

  test_configuration {
    name                      = "ICMPConfig"
    protocol                  = "Icmp"
    test_frequency_in_seconds = 60

    icmp_configuration {
      trace_route_enabled     = true 
    }

    success_threshold {
      checks_failed_percent   = 1
      round_trip_time_ms      = 500
    }
  }

  test_group {
    name                     = "AzureToOnPremICMP"
    destination_endpoints    = ["dest_host1","dest_host2"]
    source_endpoints         = [azurerm_virtual_machine.src.name]
    test_configuration_names = ["ICMPConfig"]
  }

  notes = "ICMP Testing"

  depends_on = [azurerm_virtual_machine_extension.src]
}
```

**Comment by wjdavis5** [comment]
We're seeing the same behavior on Terraform 1.3.7 provider version 3.41.0. All our source entries are duplicated

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you are referring to is the service API behavior since the two additional entries are created by adding the [filter](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_connection_monitor#filter) property. 
If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs) to change the current behavior, feel free to add the link here. When it gets added, we can reopen this request or you can create a new one if additional work is needed on our side, in the meantime I am going to close this issue since it is the service API behavior.
