### ISSUE TITLE
Updating the container_access_type property of azurerm_storage_container returns 404

### ISSUE THREAD

**Issue by rhenningfnl** [hashicorp/terraform-provider-azurerm#19055]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_container

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                              = "samplest001"
  resource_group_name               = data.azurerm_resource_group.resource_group.name
  location                          = data.azurerm_resource_group.resource_group.location
  account_tier                      = "Standard"
  account_replication_type          = "LRS"
  access_tier                       = "Hot"
  enable_https_traffic_only         = true
  min_tls_version                   = "TLS1_2"
  shared_access_key_enabled         = false

  network_rules {
    default_action = "Allow"
    bypass         = ["None"]
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_storage_container" "this" {
  name                  = "container"
  storage_account_name  = azurerm_storage_account.this.name
  container_access_type = "container"
}
```

### Debug Output/Panic Output

```shell
Error: updating the Access Control for Container "container" (Storage Account "samplest001" / Resource Group "MigrationTest"): containers.Client#SetAccessControl: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:36589c2c-e01e-001a-5617-eb5a69000000\nTime:2022-10-28T21:48:39.2004013Z"
```

### Expected Behaviour

Updating the value of container_access_type should perform the same change on the resource in Azure.

### Actual Behaviour

Trying to change this value and running an apply returns a 404 resource not found error.

### Steps to Reproduce

1. terraform init -upgrade -reconfigure -backend-config="backend.cfg"
2. terraform plan -out plan.tfplan
3. terraform apply "plan.tfplan"

### Important Factoids

I was able to reproduce this issue with containers in public storage accounts and storage accounts with private endpoints.

**Comment by magodo** [comment]
Per my local experiment, it seems is due to you have disabled the shared access key at the storage account level (`shared_access_key_enabled = false`), and used AAD auth instead. I'm not sure whether it is a know limitation of Azure or a bug. I've created an issue against Azure anyway: https://github.com/Azure/azure-rest-api-specs/issues/21347.

**Comment by magodo** [comment]
@rhenningfnl See my comment: https://github.com/Azure/azure-rest-api-specs/issues/21347#issuecomment-1296834130

**Comment by tombuildsstuff** [comment]
@magodo any chance you could add that ^ to the ticket the Service Team has for making the Resource Manager / Data Plane API's consistent?
