### ISSUE TITLE
azure-vm-datadisk-lun issue for more than 10 disks

### ISSUE THREAD

**Issue by tejas-ts** [hashicorp/terraform-provider-azurerm#19067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

2.80.0

### Affected Resource(s)/Data Source(s)

storage_data_disk 

### Terraform Configuration Files

```hcl
dynamic "storage_data_disk" {
    # This is needed so that disks are in the same order that is generated by terraform import
    for_each = local.disks_order_by_lun

    content {
      create_option     = "Attach"
      caching           = storage_data_disk.value.caching
      lun               = storage_data_disk.key
      name              = storage_data_disk.value.name
      managed_disk_type = storage_data_disk.value.type
      disk_size_gb      = storage_data_disk.value.size
      managed_disk_id   = azurerm_managed_disk.data[storage_data_disk.value.name].id
    }
  }

  delete_data_disks_on_termination = true
  delete_os_disk_on_termination    = true

  boot_diagnostics {
    enabled     = true
    storage_uri = var.diagnostics_storage_account_uri
  }

  tags = var.tags

  lifecycle {
    ignore_changes = [
      tags["Infra-Redundancy"],
      tags["Infra-Role"],
    ]
  }
```

### Debug Output/Panic Output

```shell
~ storage_data_disk {
          ~ disk_size_gb              = 110 -> 200
          ~ lun                       = 2 -> 11
          ~ managed_disk_id           = "/subscriptions/b32b955d-1f7b-45c1-bb98-96cc12760598/resourceGroups/RG-001/providers/Microsoft.Compute/disks/TLV-D187-datadisk-00-7d68df8a-154d-4a74-9db5-89b2b1158f10" -> "/subscriptions/b32b955d-45c1-bb98-96cc12760598/resourceGroups/RG-001/providers/Microsoft.Compute/disks/TLV-D187-datadisk-00-02"
          ~ name                      = "TLV-D187-datadisk-00-7d68df8a-154d-4a74-9db5-89b2b1158f10" -> "TLV-D187-datadisk-00-02"
            # (4 unchanged attributes hidden)
        }
      ~ storage_data_disk {
          ~ disk_size_gb              = 45 -> 110
          ~ lun                       = 3 -> 2
          ~ managed_disk_id           = "/subscriptions/b32b955d-1f7b-45c1-bb98-96cc12760598/resourceGroups/RG-001/providers/Microsoft.Compute/disks/TLV-D187-datadisk-00-6ef7f5cb-52b5-4fef-a40e-8b8a62ba3e14" -> "/subscriptions/b32b955d-45c1-bb98-96cc12760598/resourceGroups/RG-001/providers/Microsoft.Compute/disks/TLV-D187-datadisk-00-7d68df8a-154d-4a74-9db5-89b2b1158f10"
          ~ name                      = "TLV-D187-datadisk-00-6ef7f5cb-52b5-4fef-a40e-8b8a62ba3e14" -> "TLV-D187-datadisk-00-7d68df8a-154d-4a74-9db5-89b2b1158f10"
}
```

### Expected Behaviour

The new data disk (lun 10/11) should not replace the existing disk lun 2 and create

### Actual Behaviour

The new data disk (lun 10/11) is replacing the existing disk lun 2 and create and viceversa

### Steps to Reproduce

terraform init
terraform plan

**Comment by tombuildsstuff** [comment]
hi @tejas-ts 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 3.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!
