### ISSUE TITLE
azurerm_windows_function_app always shows a planned change for CORs support_credentials when allowed_origins is empty array

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azurerm#19078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "insort_updater" {
  name                       = "some-name"
  resource_group_name        = azurerm_resource_group.rg.name
  location                   = azurerm_resource_group.rg.location
  tags                       = local.default_tags
  storage_account_name       = azurerm_storage_account.hubstorage.name
  storage_account_access_key = azurerm_storage_account.hubstorage.primary_access_key
  service_plan_id            = azurerm_service_plan.functionapp_service.id
  


  site_config {
    ftps_state                             = "AllAllowed"

    cors {
      allowed_origins     = []
      # doesn't matter true or false
      support_credentials = true
    }
  }
  
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

azurerm provider should see that cors values is already true or false, but seems to always see it as null.

i suspect this is because the site document has nulls for all site config.  meaning

https://management.azure.com/subscriptions/<sub>/resourceGroups/<rgp>/providers/Microsoft.Web/sites/<site>?api-version=2020-12-01 has 

```
"cors": null,
```

but https://management.azure.com/subscriptions/<sub>/resourceGroups/<rgp>/providers/Microsoft.Web/sites/<site>/config?api-version=2020-12-01 has

```
"cors": {
          "allowedOrigins": [],
          "supportCredentials": true
        }
```

or something equivalent to my config.

of NOTE is that ftpsState is the same, in the site's document it's null, but in the /config document it's got the actual value...though terraform seems not have the same issue. i suspect it's reading the current value from /config and this could be fixed by having cors do the same

or maybe it's about that allowedOrigins being [] , if i use [""] it all seems to work fine.

### Actual Behaviour

always finds cors config to be null and always plans a change

### Steps to Reproduce

terraform apply

**Comment by xiaxyi** [comment]
Thanks @drdamour for raising this issue, let me check the provider source code, will update once I can confirm.

**Comment by xiaxyi** [comment]
@drdamour You can track the status in the mentioned [pr](https://github.com/hashicorp/terraform-provider-azurerm/pull/19141)
