### ISSUE TITLE
Add support for partner solution on `azurerm_monitor_diagnostic_setting`

### ISSUE THREAD

**Issue by noahbirrer-8451** [hashicorp/terraform-provider-azurerm#19076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Diagnostic Settings for Azure Resources now support select partner solutions as [destinations](https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/diagnostic-settings?tabs=portal#destinations). The `azurerm_monitor_diagnostic_setting` resource should be updated to include this functionality.

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_diagnostic_setting" "example" {
  name                = "diag-setting"
  target_resource_id  = azurerm_kubernetes_cluster.kubernetes_cluster.id
  partner_solution_id = some_azurerm_partner_solution.id 
  
  ...

}
```

**Comment by teowa** [comment]
Hi @noahbirrer-8451 , thanks for submitting this! I will submit PR to support this feature soon.
