### ISSUE TITLE
Frontdoor rule not accepting multiple parameters for the query string

### ISSUE THREAD

**Issue by sudeep1607** [hashicorp/terraform-provider-azurerm#19097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.4

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule" "frontdoor_rule" {
...
...

"url_redirect_action" = {
              "redirect_type"        = "PermanentRedirect",
              "redirect_protocol"    = "Https",
              "query_string"         = "TE=,PFalse=,source=TE,medium=mai,campaign=y10",
              "destination_path"     = "/"
              "destination_hostname" = "xyz.com"
}

...
...
}

Values Tried:
"query_string"         = "TE=&PFalse=&source=TE&medium=mai&campaign=y10",
"query_string"         = "TE=,PFalse=,source=TE,medium=mai,campaign=y10",
"query_string"         = "TE= PFalse= source=TE medium=mai campaign=y10",
"query_string"         = ["TE=","PFalse=","source=TE","medium=mai","campaign=y10"],
```

### Debug Output/Panic Output

```shell
Errors:
Inappropriate value for attribute "query_string": string required.

"url_redirect_action" is invalid: "actions.0.url_redirect_action.0.query_string" must be in the <key>=<value> or <key>={action_server_variable} format, got "TE= PFalse= source=TE medium=mai campaign=y10"

"url_redirect_action" is invalid: "actions.0.url_redirect_action.0.query_string" must not include the "?" or the "&" characters in the "query_string" field. They will be automatically added by Frontdoor, got "TE=&PFalse=&source=TE&medium=mai&campaign=y10"
```

### Expected Behaviour

Should be possible to pass multiple parameters as part of the query string

### Actual Behaviour

Getting errors on all the scenarios mentioned above in the Values that were treid as part of testing

### Steps to Reproduce

Write terraform code for azurerm_cdn_frontdoor_rule with a request_uri_condition & url_redirect_action blocks and pass multiple parameters as value to query_string
Run terraform plan

**Comment by WodansSon** [comment]
@sudeep1607, thank you for opening this issue, however this is not something I can control as this is a requirement of the API. According to the [product documentation](https://learn.microsoft.com/en-us/azure/frontdoor/front-door-rules-engine-actions?tabs=json&pivots=front-door-standard-premium#UrlRedirect) the `query_string` must be in the `<key>=<value>` format, however you maybe able to use [server variables](https://learn.microsoft.com/azure/frontdoor/rule-set-server-variables) in combination with a [rule condition](https://learn.microsoft.com/azure/frontdoor/rules-match-conditions?pivots=front-door-classic&tabs=json) to achieve what you are attempting to do here.

**Comment by sudeep1607** [comment]
@WodansSon We are looking to achieve below. In condition we are just matching the URL. There won't be any query string

Redirect https://xyz.com/test to https://xyz.com/test/page?TE=&PFalse=&source=TE&medium=mai&campaign=y10

We used ARM templates previously and trying to migrate code to the new Terraform resources. Below is an example

            {
              name = "UrlRedirect",
              parameters = {
                "@odata.type" : "#Microsoft.Azure.Cdn.Models.DeliveryRuleUrlRedirectActionParameters",
                "redirectType" : "PermanentRedirect",
                "destinationProtocol" : "Https",
                "customQueryString" : "TE=&PFalse=&source=TE&medium=mai&campaign=y10",
                "customPath" : "/test/page"
              }
            }

**Comment by WodansSon** [comment]
@sudeep1607, thank you for the clarification of your issue. I am waiting on a reply from the service team as to what the correct behavior is here. It is a very real possibility that I misinterpreted the documentation and made my validation check for that field way more strict that it should have been.
