### ISSUE TITLE
Error waiting for the create/update of Application Gateway "AGW-EIP-PRD-APIM" (Resource Group "RG-EIP-PRD-APIM-AGW"): Code="InternalServerError" Message="An error occurred."

### ISSUE THREAD

**Issue by jeffchowdhury** [hashicorp/terraform-provider-azurerm#19102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.209.19

### AzureRM Provider Version

2.40.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
#####################################################################
## Creating Azure Application Gateway                               #
#####################################################################

resource "azurerm_resource_group" "AGW" {
  name     = "RG-${var.VNET_environment}-APIM-AGW"
  location = "${var.VNET_location}"
  tags = {
	Application		= "XX"
	CostCode		= "XXX"
	Department		= "XX"
	Environment		= "XX"
	BusinessUnit	        = "xx"
  }
}

resource "azurerm_public_ip" "AGW" {
  allocation_method   = "Static"
  sku                 = "Standard"
  location            = "${var.VNET_location}"
  name                = "PIP-AGW-EIP-PRD-APIM"
  resource_group_name = azurerm_resource_group.AGW.name
  tags                = azurerm_resource_group.AGW.tags
  
}

resource "azurerm_application_gateway" "AGW" {
  name                = "AGW-EIP-PRD-APIM"
  resource_group_name = azurerm_resource_group.AGW.name
  enable_http2        = true
  location            = azurerm_resource_group.AGW.location
  tags                = azurerm_resource_group.AGW.tags

  sku {
    name     = "WAF_v2"
    tier     = "WAF_v2"
	#capacity = 2
  }
  
    autoscale_configuration {
    min_capacity = 1
    max_capacity = 2
  }

  gateway_ip_configuration {
    name      = "GatewayIPConfig"
    subnet_id = azurerm_subnet.SNET2.id
  }

  frontend_port {
    name = "app_gw_frontend_port"
    port = 80
  }

  frontend_ip_configuration {
    name                 = "app_gw_frontend_config"
    public_ip_address_id = azurerm_public_ip.AGW.id
  }
  
  backend_address_pool {
    name  = "APIM-PRD-DEVELOPER-BACKENDPOOL-01"
    fqdns = ["apim-eip-dev-01.developer.azure-api.net"]
  }
  
  backend_http_settings {
    name                  = "APIM-PRD-DEVELOPER-BACKEND-SETTING"
    cookie_based_affinity = "Disabled"
    path                  = "/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 20
  }

  http_listener {
    name                           = "APIM-PRD-DEVELOPER-HTTPLSTR"
    frontend_ip_configuration_name = "app_gw_frontend_config"
    frontend_port_name             = "app_gw_frontend_port"
    protocol                       = "Http"
  }  
  
  request_routing_rule {
    name                       = "APIM-PRD-DEVELOPER-HTTP_ROUTEING-RULE"
    rule_type                  = "Basic"
    http_listener_name         = "APIM-PRD-DEVELOPER-HTTPLSTR"
    backend_address_pool_name  = "APIM-PRD-DEVELOPER-BACKENDPOOL-01"
    backend_http_settings_name = "APIM-PRD-DEVELOPER-BACKEND-SETTING"
  } 
  
}
```

### Debug Output/Panic Output

```shell
na
```

### Expected Behaviour

Application Gateway Deployed with HTTP backend pool in a healthy state

### Actual Behaviour

Application Gateway resource is deployed in Azure but the resources appear to be in a failed state. and state file doesn't have an awareness that the resource is deployed.

**Comment by jeffchowdhury** [comment]
![image](https://user-images.githubusercontent.com/64125050/199497191-6894d47a-f0e4-46ca-a0a5-f0d3bc96be11.png)

![image](https://user-images.githubusercontent.com/64125050/199497297-1a170aad-6edb-432d-88b1-911739ea6545.png)

**Comment by dwrusse** [comment]
I'm having the same error with a well-known module that was working fine last week.  Even tried a new vnet/subnet because we found some community posts that indicate a subnet misconfiguration could cause this error.

**Comment by jeffchowdhury** [comment]
@dwrusse I am using a /26 subnet, There was no minimum number of IP requirement for APP Gateway. 
can I please know if you are using a /24 or something else? 
I am also using a route table for this specific subnet that is pointing to internet out....

**Comment by dwrusse** [comment]
I've tried both /24 and /26, but the community issues I'm referring to were related to the route table or having other/conflicting resources mistakenly on the subnet.

Our deployment was working last week & nothing has changed, so I'm very suspicious that something is broken on the Azure side.

**Comment by dwrusse** [comment]
Our issue may be related to the key vault issue currently being reported on https://status.azure.com/en-us/status/ - although we aren't enrolling or renewing a certificate, our app gateway does read a certificate value from key vault...

**Comment by jeffchowdhury** [comment]
Yep I can see there are some issues in MS KeyVault. but I am deploying HTTP rules only and not uploading any SSL or not reading from any SSL so I have no Keyvault blocks in my tf file. but for yours, if you have a keyvault block, it makes sense where it could fail.. .

**Comment by jeffchowdhury** [comment]
Just got this from a MS update after raising a MS ticket 

![image](https://user-images.githubusercontent.com/64125050/199644108-627df5c5-57bc-457d-8f4b-5e1a58a52ccd.png)

**Comment by jeffchowdhury** [comment]
![image](https://user-images.githubusercontent.com/64125050/199652673-df7dd757-c0be-4651-be1d-3d366ef286b4.png)

**Comment by aristosvo** [comment]
@jeffchowdhury Does this still happen or is this issue resolved at the Microsoft side?

In the latter case we could close this issue.

**Comment by dwrusse** [comment]
My deployment is working again, assuming it was related to the key vault outage.
