### ISSUE TITLE
Provider attempts to purge AKV secrets, even with "purge_soft_delete_on_destroy = false"

### ISSUE THREAD

**Issue by karlschriek** [hashicorp/terraform-provider-azurerm#19104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.24.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}
// AKV
resource "random_string" "akv" {
  length  = 10
  numeric = true
  lower   = true
  upper   = false
  special = false
}

data "azurerm_client_config" "this" {}

resource "azurerm_resource_group" "this" {
  name     = "akvpurgetest"
  location = "Germany West Central"
}

resource "azurerm_key_vault" "this" {
  name                            = "test${random_string.akv.result}"
  location                        = "Germany West Central"
  resource_group_name             = azurerm_resource_group.this.name
  tenant_id                       = data.azurerm_client_config.this.tenant_id
  soft_delete_retention_days      = 7
  purge_protection_enabled        = true
  sku_name                        = "standard"
  enabled_for_deployment          = false
  enabled_for_disk_encryption     = true
  enabled_for_template_deployment = false
  enable_rbac_authorization       = true
}

resource "azurerm_role_assignment" "this" {
  scope                = azurerm_key_vault.this.id
  role_definition_name = "Key Vault Administrator"
  principal_id         = data.azurerm_client_config.this.object_id
}


resource "azurerm_key_vault_secret" "akv" {
  depends_on = [
    azurerm_role_assignment.this
  ]
  name         = "mysecret"
  value        = "foobar"
  key_vault_id = azurerm_key_vault.this.id
  tags         = {}
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: purging of Secret "mysecret" (Key Vault "https://testubdk2dbfi6.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: testubdk2dbfi6;location=germanywestcentral"
│ 
│ 
╵
```

### Expected Behaviour

If purge protection is on, and I've set "purge_soft_delete_on_destroy = true", then I would expect a "destroy" operation to delete the secret, but _not_ attempt to purge it as well.

### Actual Behaviour

Clearly the "destroy" operation is attempting to purge the secret, hence the error.

### Steps to Reproduce

Run `terraform apply` on the configuration files provided.

Once successful applied, comment out the last few lines where the secret is created and run `terraform apply` again (or alternatively run an appropriate CLI command to have that `azurerm_key_vault_secret.akv` destroyed).

### References

This issue is mentioned elsewhere, such as:
https://github.com/hashicorp/terraform-provider-azurerm/issues/14442
https://github.com/hashicorp/terraform-provider-azurerm/issues/9984

Both those issues have been marked as resolved, but the issue persists.

**Comment by teowa** [comment]
Hi @karlschriek , thanks for submitting this!
By checking the source code, I found there is a specific property [`purge_soft_deleted_secrets_on_destroy`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#purge_soft_deleted_secrets_on_destroy) in `features` block controls whether to delete the key vault secret.

You can set:
```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = true
      purge_soft_deleted_secrets_on_destroy= true
    }
  }
}
```

And I am going to add notes in docs.

**Comment by karlschriek** [comment]
That's great, thanks!

Although, I think in order to prevent purging it should be:

```
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy  = false
      purge_soft_deleted_secrets_on_destroy = false
    }
  }
}
```
