### ISSUE TITLE
Support for Azure Elastic SAN

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#19127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Elastic SAN is a unique cloud-native and fully managed storage area network (SAN) service. Combining SAN-like capabilities with the benefits of being a cloud-native service, Azure Elastic SAN offers a massively scalable, cost-effective, high-performance, and resilient storage solution. It can connect to a variety of Azure compute services, enabling you to seamlessly transition your SAN data estate to the cloud without having to refactor your application architectures.

With Elastic SAN, it is possible to deploy, manage, and host workloads on Azure with an end-to-end experience similar to on-premises SAN. The solution also enables bulk provisioning of block storage that can achieve massive scale, up to millions of IOPS, double-digit GB/s of throughput, and low single-digit millisecond latencies with built-in resiliency to minimize downtime. 

### New or Affected Resource(s)/Data Source(s)

azurerm_elastic_san

### Potential Terraform Configuration

```hcl
resource "azurerm_elastic_san" "example" {
  name                         = "my-sql-server"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = azurerm_resource_group.example.location
  base_size                    = "10"
  extended_capacity_size       = "20"
  replication_type             = "LRS"
}
```

### References

https://learn.microsoft.com/en-us/azure/storage/elastic-san/elastic-san-introduction

**Comment by stephybun** [comment]
Closed by #23619
