### ISSUE TITLE
Support for internet routing ip tag on node level public ip in AKS

### ISSUE THREAD

**Issue by sudheerbhat** [hashicorp/terraform-provider-azurerm#19128]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no option to specify the ip tag on the node level public ip's in AKS nodepool. This is needed to override the routing preference on the node level public ip to internet. 

### New or Affected Resource(s)/Data Source(s)

azurerm_3.29.1 and below

**Comment by aristosvo** [comment]
Hi @sudheerbhat! Thanks for raising this issue!

Do you have any documentation from Microsoft how to do this outside Terraform or your current workflow as an example? A bit more information would help a lot.

**Comment by phealy** [comment]
Good day @aristosvo - I'm the AKS PM for this feature. Public documentation will be available in a few days, and I'll link it in the issue when it posts. For now, I can link to the [ARM schema doc](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/preview/2022-08-03-preview/managedClusters.json#L3533-L3564).

Basically, this feature just provides a way to pass the [`ip_tag`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine_scale_set#ip_tag) block through to VMSS. The structure looks like this (cut down AKS object only showing the relevant properties):

```json
{
  "properties": {
    "agentPoolProfile": {
      "nodePublicIPTags": [
        {
          "name": "pool1",
          "networkProfile": {
            "nodePublicIPTags": [
              {
                "ipTagType": "RoutingPreference",
                "tag": "Internet"
              }
            ]
          }
        }
      ]
    }
  }
}
```
