### ISSUE TITLE
Support for default tags in the provider

### ISSUE THREAD

**Issue by sarg3nt** [hashicorp/terraform-provider-azurerm#19135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Our cloud team wants us to have four specific tags with the same data on every object we create in Azure.  Right now we are using a map and setting
`tags = var.tags` and where needed merging local with the tag variable.

The AWS provider supports adding default tags to the provider like this:

```
provider "aws" {
  # ... other configuration ...
  default_tags {
    tags = {
      Environment = "Production"
      Owner       = "Ops"
    }
  }
}
```
Then in a resource, if you need to add other tags
```
resource "aws_vpc" "example" {
  # ... other configuration ...

  # This configuration by default will internally combine tags defined
  # within the provider configuration block and those defined here
  tags = {
    Name = "MyVPC"
  }
}
```
Above code is from the bottom of this page: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/resource-tagging#propagating-tags-to-all-resources

It would reduce resource complexity, make changes easier and increase DRYness if this was added to the Azure provider as well.

### New or Affected Resource(s)/Data Source(s)

provider azurerm

### Potential Terraform Configuration

```hcl
Add default tags in the provider

provider "aws" {
  # ... other configuration ...
  default_tags {
    tags = {
      Environment = "Production"
      Owner       = "Ops"
    }
  }
}
```
Then in a resource, if you need to add other tags
```
resource "aws_vpc" "example" {
  # ... other configuration ...

  # This configuration by default will internally combine tags defined
  # within the provider configuration block and those defined here
  tags = {
    Name = "MyVPC"
  }
}
```
```


### References

_No response_

**Comment by tombuildsstuff** [comment]
hey @sarg3nt 

Thanks for opening this issue.

Taking a look through here this has previously been requested in #13776 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #13776, would you mind subscribing to that issue for updates?

Thanks!
