### ISSUE TITLE
documentation link is not working

### ISSUE THREAD

**Issue by fouadbayoucef** [hashicorp/terraform-provider-azurerm#19132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

all

### Terraform Configuration Files

```hcl
on the net
```

### Debug Output/Panic Output

```shell
on the link
```

### References

the link is not working : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights

**Comment by ksista-ahc** [comment]
It is same case with every other terraform resource. for example: subnet, virtual network including data resources

**Comment by Sergi-Badia** [comment]
Anything regarding documentation is working now. All providers affected.

**Comment by aristosvo** [comment]
It is all over the registry, also outside `azurerm`, see [`aws`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints) as well

**Comment by Nordle** [comment]
> https://github.com/hashicorp/terraform-provider-azurerm/tree/2daadb0f15ce7b64107c863ea76526b0b3c6f01a/website/docs/d as a workaround the docs can be found under website/docs/d folder
> 
> Press letter `t` to quickly filter out the files you want to find.

and the `/r` folder for the resources (d is just data)

**Comment by tombuildsstuff** [comment]
👋 hey folks

Thanks for opening this issue.

The Registry is handled by the Terraform Registry team, we've let them know this is happening - however in the interests of consolidating information I hope you don't mind but I'm going to close this issue in favour [of this issue on the `hashicorp/terraform` repository](https://github.com/hashicorp/terraform/issues/32156) - would you mind subscribing to that issue for updates?

Thanks!
