### ISSUE TITLE
azurerm_linux_function_app Storage options not working

### ISSUE THREAD

**Issue by rdvansloten** [hashicorp/terraform-provider-azurerm#19134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "function_apps" {
  name                          = "myapp"
  resource_group_name           = azurerm_resource_group.main.name
  location                      = var.location
  storage_account_name          = azurerm_storage_account.function_app_storage.name
  storage_account_access_key    = azurerm_storage_account.function_app_storage.primary_access_key
  service_plan_id               = azurerm_service_plan.asp.id
  https_only                    = true

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.function_apps.id]
  }

  site_config {
    application_insights_connection_string = azurerm_application_insights.function_app.connection_string
    application_insights_key               = azurerm_application_insights.function_app.instrumentation_key

    application_stack {
      python_version = "3.9"
    }

    cors {
      allowed_origins = [
        "mydomain.com"
      ]
      support_credentials = true
    }
  }

  app_settings = {
    APP_PARTITION_KEY            = var.app_partition_key
    ENVIRONMENT                  = var.environment
    HOME_URL                     = var.home_url
  }
}
```
```


### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

  storage_account_name and storage_account_access_key are set, and the promised vars should have been generated. They have not. 

From the docs:
"Note: For storage related settings, please use related properties that are available such as storage_account_access_key, terraform will assign the value to keys such as WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, AzureWebJobsStorage in app_setting."

AzureWebJobsStorage vars are set, but WEBSITE_CONTENTAZUREFILECONNECTIONSTRING and WEBSITE_CONTENTSHARE are not.

When creating through the Portal, this all works. The docs are either wrong or incomplete, or the module is not doing what it should.

### Actual Behaviour

The environment variables that were promised, are not generated. This causes deployments to fail, because there is no storage.
<img width="526" alt="Screen Shot 2022-11-03 at 19 41 16" src="https://user-images.githubusercontent.com/54894409/199807338-82d82bfc-4d09-4886-9f4d-515a17df0938.png">

**Comment by xiaxyi** [comment]
Thanks @rdvansloten for raising this issue, may I know the service plan? Is it standard plan or premium/ elastic?

**Comment by rdvansloten** [comment]
@xiaxyi I am using Consumption (Y) tier. Another thing is that if I deploy via Terraform and set these settings manually, I am unable to push Python code via VS Code. I have to create the Functions manually, then import. It seems that this env var needs to be set at create time, or the storage never gets linked.

**Comment by xiaxyi** [comment]
@rdvansloten I will raise a pr for the fix, the current provider didn't sets this property for consumption plan.

**Comment by xiaxyi** [comment]
@rdvansloten , you can track the status in the pr https://github.com/hashicorp/terraform-provider-azurerm/pull/18258
