### ISSUE TITLE
`azurerm_kubernetes_fleet_manager` InvalidResourceType

### ISSUE THREAD

**Issue by philwelz** [hashicorp/terraform-provider-azurerm#19143]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_fleet_manager

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_fleet_manager" "test" {

  hub_profile {
    dns_prefix = "fleet-test"
  }

  location            = "eastus"
  name                = "fleet-test"
  resource_group_name = "rg-eastus-fleet-test"
}
```

### Debug Output/Panic Output

```shell
Fleet Name: "fleet-test"): performing CreateOrUpdate:
│ fleets.FleetsClient#CreateOrUpdate: Failure sending request:
│ StatusCode=0 -- Original Error: Code="InvalidResourceType"
│ Message="The resource type could not be found in the namespace
│ 'Microsoft.ContainerService' for api version '2022-09-02-preview'."
```

### Expected Behaviour

Fleet is created

### Actual Behaviour

see debug outpout

### Steps to Reproduce

1. terraform apply

**Comment by tombuildsstuff** [comment]
hey @philwelz 

Thanks for opening this issue.

Taking a look into this one, since this is a Preview resource you may need to be opted into the Preview to make use of this, are you registered for the Fleet Manager Preview? If not you can do this by running:

> $ az feature register --namespace Microsoft.ContainerService --name FleetResourcePreview

and then once that's registered

> $ az provider register -n Microsoft.ContainerService

In retrospect we should be calling out that this is a Preview in the documentation here, so apologies for that - we'll look to get that fixed up.

Thanks!

**Comment by philwelz** [comment]
hey @tombuildsstuff thanks for your answer. I did that and with the Azure CLI creating the Fleet was already working. I just was happy to use the new Terraform Resource 😄  

It seems that I missed `az provider register -n Microsoft.ContainerService` bcs after doing that it works also with Terraform. So i will close this issue. Thanks and have a nice weekend!

**Comment by tombuildsstuff** [comment]
Glad to hear that's now working for you 👍

I've opened https://github.com/hashicorp/pandora/pull/1794 to add a description highlighting that this resource is in Preview, once that's merged the docs will get regenerated and this'll go out with the next release - thanks again for the report/letting us know :)
