### ISSUE TITLE
azurerm_monitor_data_collection_rule not connecting computers to Log Analytics Workspace

### ISSUE THREAD

**Issue by bdorplatt** [hashicorp/terraform-provider-azurerm#19156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### Terraform Configuration Files

```hcl
# LA Workspace
    resource "azurerm_log_analytics_workspace" "workspace" {
      name                = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.application}-la"
      location            = var.region
      resource_group_name = var.resource_group_name
      sku                 = "PerGB2018"
      retention_in_days   = 30
    }

    resource "azurerm_log_analytics_solution" "vminsights" {
      solution_name         = "vminsights"
      resource_group_name   = var.resource_group_name
      location              = var.region
      workspace_resource_id = azurerm_log_analytics_workspace.workspace.id
      workspace_name        = azurerm_log_analytics_workspace.workspace.name
      plan {
        publisher = "Microsoft"
        product   = "OMSGallery/VMInsights"
      }
}

      # Data Collection Rules
     resource "azurerm_monitor_data_collection_rule" "rule" {
      name                = "${var.tenant}-${var.region_abbr}-${var.subscription}-${var.application}-la-dcr"
      resource_group_name = var.resource_group_name
      location            = var.region
    
      destinations {
        log_analytics {
          workspace_resource_id = azurerm_log_analytics_workspace.workspace.id
          name                  = "destination-log"
        }
    
        azure_monitor_metrics {
          name = "destination-metrics"
        }
      } 
    
      data_flow {
        streams      = ["Microsoft-InsightsMetrics"]
        destinations = ["destination-metrics"]
      }

      data_flow {
         streams      = ["Microsoft-InsightsMetrics", "Microsoft-Syslog", "Microsoft-Perf", "Microsoft-WindowsEvent"]
         destinations = ["destination-log"]
      }
    
      data_sources { 
        performance_counter {
          streams                       = ["Microsoft-Perf", "Microsoft-InsightsMetrics"]
          sampling_frequency_in_seconds = 60
          counter_specifiers            = ["\\VmInsights\\DetailedMetrics"]
          name                          = "VMInsightsPerfCounters"
        }

  }
          depends_on = [
            azurerm_log_analytics_solution.vminsights
  ]
}

#VM

resource "azurerm_windows_virtual_machine" "server" {
  admin_password      = random_password.server_password.result
  admin_username      = var.server_local_admin
  license_type        = var.server_license_type
  location            = var.region
  name                = var.server_name
  resource_group_name = var.resource_group_name
  size                = var.server_size
  source_image_id     = var.server_source_image_id
  timezone            = var.server_timezone
  
# Azure Monitor Extension
resource "azurerm_virtual_machine_extension" "azuremonitorwindowsagent" {   
  depends_on = [  azurerm_virtual_machine_extension.da  ]  
  name                       = "AzureMonitorWindowsAgent"
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorWindowsAgent"
  type_handler_version       = 1.8
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = "true"
  virtual_machine_id         = azurerm_windows_virtual_machine.server.id

  settings = <<SETTINGS
    {
        "workspaceId": "${var.log_analytics_workspace_id}",
        "azureResourceId": "${azurerm_windows_virtual_machine.server.id}",
        "stopOnMultipleConnections": "false"
    }
  SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
    {
      "workspaceKey": "${var.log_analytics_primary_shared_key}"
    }
  PROTECTED_SETTINGS
 }

resource "azurerm_virtual_machine_extension" "da" {
  name                       = "DAExtension"
  virtual_machine_id         =  azurerm_windows_virtual_machine.server.id
  publisher                  = "Microsoft.Azure.Monitoring.DependencyAgent"
  type                       = "DependencyAgentWindows"
  type_handler_version       = "9.10"
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true
}
```

### Debug Output/Panic Output

```shell
VM's are added to the Data Collection Rule and appear under the DCR's "Resources."
The Data Collection Rules "Data Sources>Destination" shows the correct Log Analytics Workspace.

The VM shows does not show up under "Agents Management" in the Log Analytics Workspace.

If we go to "Windows Data Sources" in the Log Analytics Workspace, the VM shows as "Not Connected"
If the VM is selected and then chosen to "Connect" it connects to the LA workspace but the deprecated/ MMA extension is installed in addition to theexisting  "AzureMonitorWindowsAgent" extension.
```

### Expected Behaviour

The VM should be added to the Log Analytics Workspace via the Data Collection Rule and not need the MMA agent.

### Actual Behaviour

The VM appears to be in all of the right places but does not "Connect" to the Log Analytics workspace.

### Steps to Reproduce

Deploy a VM with the AzureMonitorWindowsAgent extension using a Data Collection Rule.

**Comment by teowa** [comment]
Hi @bdorplatt , thanks for submitting this issue!
The points to have the vm connected are:
 1. add a `extension` block in the `azurerm_monitor_data_collection_rule`
```hcl
    extension {
      streams        = ["Microsoft-WindowsEvent"]
      extension_name = "DAExtension"
      extension_json = jsonencode(
        {
          workspaceId               = azurerm_log_analytics_workspace.workspace.id
          azureResourceId           = azurerm_windows_virtual_machine.example.id
          stopOnMultipleConnections = "false"
      })
      name = "test-datasource-extension"
    }
```
 2. add a `azreurm_monitor_data_collection_rule_association` resource to associate the vm and the data collection rule.
```hcl
resource "azurerm_monitor_data_collection_rule_association" "example1" {
  name                    = "example1-dcra"
  target_resource_id      = azurerm_windows_virtual_machine.example.id
  data_collection_rule_id = azurerm_monitor_data_collection_rule.rule.id
  description             = "example"
}
```
Hope this may help.
<details>
<summary>below is a full example of the config: </summary>

```hcl
provider "azurerm" {
  features {}
}
resource "azurerm_resource_group" "example" {
  name     = "test-dcr"
  location = "eastus"
}
resource "azurerm_log_analytics_workspace" "workspace" {
  name                = "tesstlaw"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "vminsights" {
  solution_name         = "vminsights"
  resource_group_name   = azurerm_resource_group.example.name
  location              = azurerm_resource_group.example.location
  workspace_resource_id = azurerm_log_analytics_workspace.workspace.id
  workspace_name        = azurerm_log_analytics_workspace.workspace.name
  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/VMInsights"
  }
}

# Data Collection Rules
resource "azurerm_monitor_data_collection_rule" "rule" {
  name                = "test-dcr"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  destinations {
    log_analytics {
      workspace_resource_id = azurerm_log_analytics_workspace.workspace.id
      name                  = "destination-log"
    }

    azure_monitor_metrics {
      name = "destination-metrics"
    }
  }

  data_flow {
    streams      = ["Microsoft-InsightsMetrics"]
    destinations = ["destination-metrics"]
  }

  data_flow {
    streams      = ["Microsoft-InsightsMetrics", "Microsoft-Syslog", "Microsoft-Perf", "Microsoft-WindowsEvent"]
    destinations = ["destination-log"]
  }

  data_sources {
    performance_counter {
      streams                       = ["Microsoft-Perf", "Microsoft-InsightsMetrics"]
      sampling_frequency_in_seconds = 60
      counter_specifiers            = ["\\VmInsights\\DetailedMetrics"]
      name                          = "VMInsightsPerfCounters"
    }
    extension {
      streams        = ["Microsoft-WindowsEvent"]
      extension_name = "DAExtension"
      extension_json = jsonencode(
        {
          workspaceId               = azurerm_log_analytics_workspace.workspace.id
          azureResourceId           = azurerm_windows_virtual_machine.example.id
          stopOnMultipleConnections = "false"
      })
      name = "test-datasource-extension"
    }

  }
    depends_on = [
      azurerm_log_analytics_solution.vminsights
    ]
}
resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}
#VM
resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "P@$$w0rd1234!"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }
}
# Azure Monitor Extension
resource "azurerm_virtual_machine_extension" "azuremonitorwindowsagent" {
  depends_on                 = [azurerm_virtual_machine_extension.da]
  name                       = "AzureMonitorWindowsAgent"
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorWindowsAgent"
  type_handler_version       = 1.8
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = "true"
  virtual_machine_id         = azurerm_windows_virtual_machine.example.id

  settings           = <<SETTINGS
    {
        "workspaceId": "${azurerm_log_analytics_workspace.workspace.id}",
        "azureResourceId": "${azurerm_windows_virtual_machine.example.id}",
        "stopOnMultipleConnections": "false"
    }
  SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
    {
      "workspaceKey": "var.log_analytics_primary_shared_key"
    }
  PROTECTED_SETTINGS
}

resource "azurerm_virtual_machine_extension" "da" {
  name                       = "DAExtension"
  virtual_machine_id         = azurerm_windows_virtual_machine.example.id
  publisher                  = "Microsoft.Azure.Monitoring.DependencyAgent"
  type                       = "DependencyAgentWindows"
  type_handler_version       = "9.10"
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = true
}

resource "azurerm_monitor_data_collection_rule_association" "example1" {
  name                    = "example1-dcra"
  target_resource_id      = azurerm_windows_virtual_machine.example.id
  data_collection_rule_id = azurerm_monitor_data_collection_rule.rule.id
  description             = "example"
}
```

</details>

**Comment by bdorplatt** [comment]
We tested this with a hardcoded VM entry of an existing VM for **azureResourceId** and this still does not appear to connect the VM to Log Analytics.

In fact, adding Extension as a data source at all, caused all data sources to be cleared out in the portal:
![image](https://user-images.githubusercontent.com/78042220/200412968-e1408092-f2d7-40b2-85ab-7ee06dd56414.png)

But on the Overview, it still shows 2 data sources and they appear in the JSON as well.
![image](https://user-images.githubusercontent.com/78042220/200413812-09787d95-60e4-4c94-af68-ae162de1b042.png)

![image](https://user-images.githubusercontent.com/78042220/200414231-8d6e47e0-758e-4f25-96dd-90780dda6e50.png)

`      data_sources {
    
        performance_counter {
          streams                       = ["Microsoft-Perf", "Microsoft-InsightsMetrics"]
          sampling_frequency_in_seconds = 60
          counter_specifiers            = ["\\VmInsights\\DetailedMetrics"]
          name                          = "VMInsightsPerfCounters"
        }

        extension {
        streams        = ["Microsoft-WindowsEvent"]
        extension_name = "DAExtension"
        extension_json = jsonencode(
          {
            workspaceId               = azurerm_log_analytics_workspace.workspace.id
            azureResourceId           = "/subscriptions/11111111-1111-1111-1111-111111111111/resourceGroups/test-rg/providers/Microsoft.Compute/virtualMachines/testvm" #azurerm_windows_virtual_machine.example.id
            stopOnMultipleConnections = "false"
        })
        name = "datasource-extension"
    }`

**Comment by teowa** [comment]
@bdorplatt , you are right, there is no need for add `extension` data source in data collection rule.  I have editted my answer. And from my test, I can successfully connect the VM to log analytics workspace. Connecting the VM to log analytics workspace should be a API usage issue but not a Terraform provider bug, here a docs about [Troubleshooting guidance for the Azure Monitor agent on Windows virtual machines and scale sets](https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-troubleshoot-windows-vm). Below are some screenshots from Azure Portal:
![image](https://user-images.githubusercontent.com/104055472/200475910-b556428b-aa35-483f-85c8-21291fbcfe33.png)
see them in logs:
![image](https://user-images.githubusercontent.com/104055472/200476081-f8cffe03-93ab-4402-b61d-80ea96ba0432.png)

the dcr:
![image](https://user-images.githubusercontent.com/104055472/200476985-9973df7a-bdd2-4268-bc09-7ecec5b2dcb6.png)

the VM extensions (some of them are automatically added by my test subscription and may not matter):
![image](https://user-images.githubusercontent.com/104055472/200477479-46e649a8-6525-4338-8647-b1ec847ffa90.png)

**Comment by bdorplatt** [comment]
I think we have this figured out. After going through the troubleshooting guide, there was an item regarding needing a Managed Identity. After adding a System-Managed Identity and redeploying the extensions, the VM hooked up correctly to the Log Analytics workspace.

•	The virtual machine may not have Managed Identity enabled. [See here](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Factive-directory%2Fmanaged-identities-azure-resources%2Fqs-configure-portal-windows-vm%23enable-system-assigned-managed-identity-during-creation-of-a-vm&data=05%7C01%7Crplatt%40bdo.com%7C3b829929396f46778e5508dac269e355%7C6e57fc1a413e405091da7d2dc8543e3c%7C0%7C0%7C638036057329340233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9RDS4TS%2Bh2TJpcDLBYHbGv7IjyV8rNyH8IZDHmckCow%3D&reserved=0) on how to enable.
[https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-troubleshoot-windows-vm#basic-troubleshooting-steps-installation-agent-not-running-configuration-issues](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fagents%2Fazure-monitor-agent-troubleshoot-windows-vm%23basic-troubleshooting-steps-installation-agent-not-running-configuration-issues&data=05%7C01%7Crplatt%40bdo.com%7C3b829929396f46778e5508dac269e355%7C6e57fc1a413e405091da7d2dc8543e3c%7C0%7C0%7C638036057329340233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sla7NAN8efUuAf5GHF7yI5Jyi3uLYIrn9WdHBlp44C4%3D&reserved=0)


After further research, it appears the recommendation for large scale deployments is to use a user-assigned Managed Identity, additionally, there was some information about creating and assigning a built-in user-assigned managed identity, per subscription, per region.
[https://learn.microsoft.com/en-us/azure/azure-monitor/agents/azure-monitor-agent-manage?tabs=azure-portal#prerequisites](https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fazure-monitor%2Fagents%2Fazure-monitor-agent-manage%3Ftabs%3Dazure-portal%23prerequisites&data=05%7C01%7Crplatt%40bdo.com%7C3b829929396f46778e5508dac269e355%7C6e57fc1a413e405091da7d2dc8543e3c%7C0%7C0%7C638036057329340233%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DL%2BYAt0RIfzGhWzuP239j0D3VMBAsq54OZ3uQZGi%2F80%3D&reserved=0)

It goes on to say that to use a user-assigned MI, you must pass the managed identity details to Azure Monitor Agent via extension settings. We're trying to figure out how that fits in Terraform since it doesn't appear to be documented and the example gives the below JSON:

{
  "authentication": {
    "managedIdentity": {
      "identifier-name": "mi_res_id" or "object_id" or "client_id",
      "identifier-value": "<resource-id-of-uai>" or "<guid-object-or-client-id>"
    }
  }
}

I'm assuming we need to get that into a Settings block under the resource "azurerm_virtual_machine_extension" "azuremonitorwindowsagent"

Any guidance would be appreciated here!

**Comment by bdorplatt** [comment]
We have tried various combinations of adding/removing quotes and braces, resulting in either of the two error below. We aren't sure if our syntax is wrong or if this sort of nesting isn't possible. We don't believe there can be two settings blocks but may try that as well
Error: "settings" contains an invalid JSON: invalid character '}'
Error: "settings" contains an invalid JSON: invalid character '"'

`# Azure Monitor Extension
resource "azurerm_virtual_machine_extension" "azuremonitorwindowsagent" {   
  depends_on = [  azurerm_virtual_machine_extension.da  ]
  count                      = var.host_pool_add_avd ? 1 : 0     
  name                       = "AzureMonitorWindowsAgent"
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorWindowsAgent"
  type_handler_version       = 1.8
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = "true"
  virtual_machine_id         = azurerm_windows_virtual_machine.server.id

  settings = <<SETTINGS
    {
        "workspaceId": "${var.log_analytics_workspace_id}",
        "azureResourceId": "${azurerm_windows_virtual_machine.server.id}",
        "stopOnMultipleConnections": "false",
        "authentication": 
        {
        "managedIdentity": 
        {
        "identifier-name": "${var.log_analytics_mi_name}",
        "identifier-value": "${var.log_analytics_mi_object_id}",
       }
      }
     }
  SETTINGS

  protected_settings = <<PROTECTED_SETTINGS
    {
      "workspaceKey": "${var.log_analytics_primary_shared_key}"
    }
  PROTECTED_SETTINGS
 
}`

**Comment by teowa** [comment]
Hi @bdorplatt , you can try `jsonencode`, see https://developer.hashicorp.com/terraform/language/expressions/strings#generating-json-or-yaml
```
resource "azurerm_virtual_machine_extension" "azuremonitorwindowsagent" {
  depends_on                 = [azurerm_virtual_machine_extension.da]
  name                       = "AzureMonitorWindowsAgent"
  publisher                  = "Microsoft.Azure.Monitor"
  type                       = "AzureMonitorWindowsAgent"
  type_handler_version       = 1.8
  automatic_upgrade_enabled  = true
  auto_upgrade_minor_version = "true"
  virtual_machine_id         = azurerm_windows_virtual_machine.example.id

  settings = jsonencode({
    workspaceId               = "${azurerm_log_analytics_workspace.workspace.id}"
    azureResourceId           = "${azurerm_windows_virtual_machine.example.id}"
    stopOnMultipleConnections = false

    authentication = {
      managedIdentity = {
        identifier-name  = "mi_res_id"
        identifier-value = azurerm_user_assigned_identity.example.id
      }
    }

  })
  protected_settings = jsonencode({
    "workspaceKey" = azurerm_log_analytics_workspace.workspace.primary_shared_key
  })
}
```

**Comment by bdorplatt** [comment]
@teowa The jsonencode worked for us. Thank you for the assistance and for getting this added to the examples.
