### ISSUE TITLE
Update azurerm_communication_service data_location

### ISSUE THREAD

**Issue by sergiomcalzada** [hashicorp/terraform-provider-azurerm#19172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

data_location property can have more values now

[data_location](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/communication_service#data_location) - (Optional) The location where the Communication service stores its data at rest. Possible values are Asia Pacific, Australia, Europe, UK and United States. Defaults to United States.

https://learn.microsoft.com/en-us/azure/communication-services/concepts/privacy#data-residency

- Africa
- Asia Pacific
- Australia
- Brazil
- Canada
- Europe
- France
- Germany
- India
- Japan
- Korea
- Norway
- Switzerland
- United Arab Emirates
- United Kingdom
- United States

### New or Affected Resource(s)/Data Source(s)

azurerm_communication_service

### Potential Terraform Configuration

```hcl
Update the allowed list
```

### References

https://learn.microsoft.com/en-us/azure/communication-services/concepts/privacy#data-residency
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/communication_service

**Comment by sinbai** [comment]
@sergiomcalzada thanks for opening this issue. I have submitted [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/19186) to support more possible values for property `data_location`. Could you follow this PR for more updates?
