### ISSUE TITLE
`azurerm_cdn_frontdoor_profile` resource incorrectly replaced when changing value of `response_timeout_seconds`

### ISSUE THREAD

**Issue by jamesryanuk** [hashicorp/terraform-provider-azurerm#19174]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_profile

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_profile" "fd" {
  name                     = "fd-response-timeout-test"
  resource_group_name      = var.resource_group_name
  sku_name                 = "Standard_AzureFrontDoor"
  response_timeout_seconds = 90 #Changing this forces replacement
}
```

### Debug Output/Panic Output

```shell
# azurerm_cdn_frontdoor_profile.fd must be replaced
-/+ resource "azurerm_cdn_frontdoor_profile" "fd" {
      ~ id                       = "/subscriptions/<REDACTED>/Microsoft.Cdn/profiles/fd-response-timeout-test" -> (known after apply)
        name                     = "fd-response-timeout-test"
      ~ resource_guid            = "e612d01d-b40c-42c7-b192-14f6a3bb709c" -> (known after apply)
      ~ response_timeout_seconds = 100 -> 90 # forces replacement
      - tags                     = {} -> null
        # (2 unchanged attributes hidden)
    }
```

### Expected Behaviour

Changing the value of response_timeout_seconds should not force replacement

### Actual Behaviour

Changing the value of response_timeout_seconds forces replacement

### Steps to Reproduce

1. `terraform apply` with the sample supplied
2. Modify the value of `response_timeout_seconds`
3. `terraform apply`

**Comment by WodansSon** [comment]
@jamesryanuk, thank you for opening this issue. Good catch I totally missed this when I originally created this resource. 🚀
