### ISSUE TITLE
Azure Front Door Provider is trying to sort/ re-order rules/ pools, healthprobe, loadbalancing resource alphabetically 

### ISSUE THREAD

**Issue by koko-a** [hashicorp/terraform-provider-azurerm#19179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

v3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Terraform Configuration Files

```hcl
Module.

resource "azurerm_frontdoor" "fd" {
  name                = var.fd_name
  resource_group_name = var.rg_name
  tags                = var.tags

  backend_pool_settings {
    backend_pools_send_receive_timeout_seconds   = var.pool_timeout
    enforce_backend_pools_certificate_name_check = false
  }

  dynamic "routing_rule" {
    for_each = var.fd_routing
    content {
      name               = routing_rule.value.name == null ? "${routing_rule.key}-rule" : routing_rule.value.name
      accepted_protocols = routing_rule.value.accepted_protocols
      patterns_to_match  = routing_rule.value.patterns_to_match
      frontend_endpoints = routing_rule.value.frontend_endpoints

      forwarding_configuration {
        forwarding_protocol = routing_rule.value.forwarding_protocol
        backend_pool_name   = "${routing_rule.value.backendpool}-pool"
      }
    }
  }


  #review
  dynamic "routing_rule" { ### redirect
    for_each = var.fd_redirect
    content {
      name               = "${routing_rule.key}-redirect"
      accepted_protocols = routing_rule.value.accepted_protocols
      patterns_to_match  = routing_rule.value.patterns_to_match
      frontend_endpoints = routing_rule.value.frontend_endpoints != null ? routing_rule.value.frontend_endpoints : [routing_rule.key]
      redirect_configuration {
        redirect_type     = routing_rule.value.redirect_type
        redirect_protocol = routing_rule.value.redirect_protocol
      }
    }
  }

  dynamic "backend_pool_load_balancing" {
    for_each = var.pools
    content {
      name = "${backend_pool_load_balancing.key}-pool-loadbalancing"
    }
  }

  # backend_pool_load_balancing {
  #   name = "LoadBalancingSettings"
  # }

  dynamic "backend_pool_health_probe" {
      for_each = var.pools
    content {
      name                = "${backend_pool_health_probe.key}-healthprobe"
      path                = backend_pool_health_probe.value.health_probe_path
      probe_method        = backend_pool_health_probe.value.health_probe_method
      protocol            = backend_pool_health_probe.value.health_probe_protocol
      interval_in_seconds = backend_pool_health_probe.value.health_probe_interval
    }
  }

  dynamic "backend_pool" {
    for_each = var.pools
    content {
      name = "${backend_pool.key}-pool"
      load_balancing_name = "${backend_pool.key}-pool-loadbalancing"
      health_probe_name   = "${backend_pool.key}-healthprobe"
      dynamic "backend" {
        for_each = backend_pool.value.fqdn
        content {
          host_header = backend_pool.value.hostname == "" ? backend.value : backend_pool.value.hostname
          address     = backend.value
          http_port   = 80
          https_port  = backend_pool.value.https_port
        }
      }

    }
  }

  frontend_endpoint {
    name      = var.default_fd_frontend_name == null ? var.fd_name : var.default_fd_frontend_name
    host_name = "${var.fd_name}.azurefd.net"
  }

  dynamic "frontend_endpoint" {
    for_each = var.fd_frontend
    content {
      name                                    = frontend_endpoint.key
      host_name                               = frontend_endpoint.value.hostname
      session_affinity_enabled                = frontend_endpoint.value.session_affinity == "" ? false : frontend_endpoint.value.session_affinity
      session_affinity_ttl_seconds            = frontend_endpoint.value.sesstion_affinity_timeout == "" ? 0 : frontend_endpoint.value.sesstion_affinity_timeout
      web_application_firewall_policy_link_id = frontend_endpoint.value.waf_policy
    }
  }

}

resource "azurerm_frontdoor_custom_https_configuration" "https_config" {
  for_each                          = var.fd_frontend
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoints[each.key]
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
--------------------------------------------
variables.tf 
------------
variable "fd_name" {
  description = "The name of the Azure Front Door. Changing this forces a new resource to be created."
  type        = string
}

variable "pools" {
  description = "See object specific arguments in the README."
  type = map(object({
    hostname              = string
    fqdn                  = list(string)
    health_probe_path     = string
    health_probe_method   = optional(string, "GET")
    health_probe_protocol = optional(string, "Https")
    health_probe_interval = optional(string, "60")
    https_port            = number
  }))
}

variable "fd_frontend" {
  description = "See object specific arguments in the module README."
  type = map(object({
    hostname                  = string
    waf_policy                = string
    session_affinity          = bool
    sesstion_affinity_timeout = number
  }))
}

variable "fd_routing" {
  description = "See object specific arguments in the README."
  type = map(object({
    backendpool         = string
    patterns_to_match   = list(string)
    frontend_endpoints  = list(string)
    accepted_protocols  = optional(list(string), ["Https"])
    forwarding_protocol = optional(string, "HttpsOnly")
  }))
}

variable "fd_redirect" {
  description = "See object specific arguments in the README."
  type = map(object({
    frontend_endpoints = optional(list(string), null)
    accepted_protocols = optional(list(string), ["Http"])
    patterns_to_match  = optional(list(string), ["/*"])
    redirect_type      = optional(string, "Moved")
    redirect_protocol  = optional(string, "HttpsOnly")
  }))
  default = {}
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/koko-a/ac668cef2ba8eaef1fd403c268479b74
```

### Expected Behaviour

We should see only new resources when we add or delete one on terraform plan and apply

### Actual Behaviour

When we run apply , is trying to sort all resources name alphabetically , which does not match with Azure API . 
The plan shows that all existing resources will be renamed.  The apply does work and it looks to me that Azure API is rejecting the Terraform reordering and the code get successfully deployed.
The plan looks very messy when we add  new or delete existing  rule/pool resources.
------------------------------
pools = {
  dest = {
     health_probe_path = "/dest-test/"
     hostname          = "dest.azurewebsites.net"
     https_port        = 443
     fqdn              = ["dest.azurewebsites.net"]
   }
}

fd_routing = {
  dest = {
     backendpool        = "dest"
     patterns_to_match  = ["/dest", "/dest/*"]
     frontend_endpoints = ["koko-afd-test","koko-msdn-frontdoor"]
  }
}

--------------------------
The Output of the plan :

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.front_door.azurerm_frontdoor.fd will be updated in-place
  ~ resource "azurerm_frontdoor" "fd" {
        id                                   = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor"
        name                                 = "koko-msdn-frontdoor"
        tags                                 = {
            "Environment"     = "UAT-test"
            "Product"         = "AFD"
             "pipeline_name"   = "Manual-Deploy"
            "repository_name" = "Manual-Deploy"
        }
        # (10 unchanged attributes hidden)

      ~ backend_pool {
          ~ health_probe_name   = "mytest-healthprobe" -> "dest-healthprobe"
            id                  = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/backendPools/mytest-pool"
          ~ load_balancing_name = "mytest-pool-loadbalancing" -> "dest-pool-loadbalancing"
          ~ name                = "mytest-pool" -> "dest-pool"

          ~ backend {
              ~ address     = "mytest.azurestaticapps.net" -> "dest.azurewebsites.net"
              ~ host_header = "mytest.azurestaticapps.net" -> "dest.azurewebsites.net"
                # (5 unchanged attributes hidden)
            }
        }
      ~ backend_pool {
          ~ health_probe_name   = "remarketing-healthprobe" -> "mytest-healthprobe"
            id                  = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/backendPools/remarketing-pool"
          ~ load_balancing_name = "remarketing-pool-loadbalancing" -> "mytest-pool-loadbalancing"
          ~ name                = "remarketing-pool" -> "mytest-pool"

          ~ backend {
              ~ address     = "remarketing.azurestaticapps.net" -> "mytest.azurestaticapps.net"
              ~ host_header = "remarketing.azurestaticapps.net" -> "mytest.azurestaticapps.net"
                # (5 unchanged attributes hidden)
            }
        }
      + backend_pool {
          + health_probe_name   = "remarketing-healthprobe"
          + load_balancing_name = "remarketing-pool-loadbalancing"
          + name                = "remarketing-pool"

          + backend {
              + address     = "remarketing.azurestaticapps.net"
              + enabled     = true
              + host_header = "remarketing.azurestaticapps.net"
              + http_port   = 80
              + https_port  = 443
              + priority    = 1
              + weight      = 50
            }
        }

      ~ backend_pool_health_probe {
            id                  = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/healthProbeSettings/mytest-healthprobe"
          ~ name                = "mytest-healthprobe" -> "dest-healthprobe"
          ~ path                = "/mytest/" -> "/dest-test/"
            # (4 unchanged attributes hidden)
        }
      ~ backend_pool_health_probe {
            id                  = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/healthProbeSettings/remarketing-healthprobe"
          ~ name                = "remarketing-healthprobe" -> "mytest-healthprobe"
          ~ path                = "/locations" -> "/mytest/"
            # (4 unchanged attributes hidden)
        }
      + backend_pool_health_probe {
          + enabled             = true
          + interval_in_seconds = 60
          + name                = "remarketing-healthprobe"
          + path                = "/locations"
          + probe_method        = "GET"
          + protocol            = "Https"
        }

      ~ backend_pool_load_balancing {
            id                              = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/loadBalancingSettings/mytest-pool-loadbalancing"
          ~ name                            = "mytest-pool-loadbalancing" -> "dest-pool-loadbalancing"
            # (3 unchanged attributes hidden)
        }
      ~ backend_pool_load_balancing {
            id                              = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/loadBalancingSettings/remarketing-pool-loadbalancing"
          ~ name                            = "remarketing-pool-loadbalancing" -> "mytest-pool-loadbalancing"
            # (3 unchanged attributes hidden)
        }
      + backend_pool_load_balancing {
          + additional_latency_milliseconds = 0
          + name                            = "remarketing-pool-loadbalancing"
          + sample_size                     = 4
          + successful_samples_required     = 2
        }

      ~ routing_rule {
            id                 = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/routingRules/mytest-rule"
          ~ name               = "mytest-rule" -> "dest-rule"
          ~ patterns_to_match  = [
              - "/mytest",
              - "/mytest/*",
              + "/dest",
              + "/dest/*",
            ]
            # (3 unchanged attributes hidden)

          ~ forwarding_configuration {
              ~ backend_pool_name                     = "mytest-pool" -> "dest-pool"
                # (5 unchanged attributes hidden)
            }
        }
      ~ routing_rule {
            id                 = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/routingRules/remarketing-rule"
          ~ name               = "remarketing-rule" -> "mytest-rule"
          ~ patterns_to_match  = [
              - "/locations/",
              + "/mytest",
              + "/mytest/*",
            ]
            # (3 unchanged attributes hidden)

          ~ forwarding_configuration {
              ~ backend_pool_name                     = "remarketing-pool" -> "mytest-pool"
                # (5 unchanged attributes hidden)
            }
        }
      ~ routing_rule {
          ~ accepted_protocols = [
              - "Http",
              + "Https",
            ]
            id                 = "/subscriptions/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/routingRules/default-http-2-https-redirect"
          ~ name               = "default-http-2-https-redirect" -> "remarketing-rule"
          ~ patterns_to_match  = [
              - "/*",
              + "/locations/",
            ]
            # (2 unchanged attributes hidden)

          + forwarding_configuration {
              + backend_pool_name                     = "remarketing-pool"
              + cache_enabled                         = false
              + cache_query_parameter_strip_directive = "StripAll"
              + cache_use_dynamic_compression         = false
              + forwarding_protocol                   = "HttpsOnly"
            }

          - redirect_configuration {
              - redirect_protocol = "HttpsOnly" -> null
              - redirect_type     = "PermanentRedirect" -> null
            }
        }
      + routing_rule {
          + accepted_protocols = [
              + "Http",
            ]
          + enabled            = true
          + frontend_endpoints = [
              + "koko-afd-test",
              + "koko-msdn-frontdoor",
            ]
          + name               = "default-http-2-https-redirect"
          + patterns_to_match  = [
              + "/*",
            ]

          + redirect_configuration {
              + redirect_protocol = "HttpsOnly"
              + redirect_type     = "PermanentRedirect"
            }
        }

        # (15 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Steps to Reproduce

terraform plan -var-file="env_config/uat.tfvars"

### Important Factoids

n/a

**Comment by WodansSon** [comment]
@koko-a, thank you for opening this issue. This has a very long history, please see [PR 11456](https://github.com/hashicorp/terraform-provider-azurerm/pull/11456) for the full details, that said the `Front Door Classic` resources are currently in `sustained engineering mode` and will be deprecated in v4.0 of the AzureRM Provider.

Have you tried to onboard the new supported version of Front Door? You can find them here, [CDN Front Door Standard/Premium](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_custom_domain_association). I would highly recommend you migrate your current `Front Door Classic` instance(s) to the new `CDN Front Door Standard/Premium` resources.

**Comment by koko-a** [comment]
Thanks for getting back to me @WodansSon .
No we have not tried to onboard the new AFD yet. We have a blocker at the moment and we wont be able to move to until next year now. 
Yes we had the same http error in the past but we managed to fix it . However the re-ordering issues remained. I tried to re-import the resources into a new state file but that did not help and everytime  i need to add a new pool\ rule is trying to re-order them .  
Is there any temp work around or is there away to do any explicit_resource_order either in state file or in TF config ?
or any changes i can do to reflect this please ?
Thank you

**Comment by WodansSon** [comment]
@koko-a, if I remember correctly once you apply the changes the issue goes away. The crux of the issue is that the service sends back the JSON out of order and that confuses Terraform, which is why I mad the fix in the above PR to keep a local state list of the resources to help Terraform understand the correct ordering. Unfortunately, at this point in time, I do not believe there is any mitigation strategy to work around this issue.

**Comment by koko-a** [comment]
Thank you @WodansSon .
No the issue does not go away after apply for me. Where is that local state list kept, is that visible to us to clarify is in place  ? Will it matter that we have two tfvar files ( 1x uat and 1x prod)  and both state files are kept in Azure ?

**Comment by WodansSon** [comment]
@koko-a, the local state list is kept in the `terraform.tfstate` file under the field name `explicit_resource_order` in the `azurerm_frontdoor` resource block. I believe that since you have a UAT and a PROD tfvars file that target the same state file that could very well be what is causing this issue since the local `explicit_resource_order` field would contain the state of both the UAT and PROD tfvars files when you switch between those two tfvars files. That said after the first `apply` the `explicit_resource_order` field should be updated to reflect the resources in whichever tfvars file was last applied successfully.

**Comment by koko-a** [comment]
@WodansSon ,
We have separate state file for each "${env}.tfvar" files and they are kept into different subscriptions and blob storage. Dont think they conflict themselves. 
I noticed that "explicit_resource_order" in the state files has sort the resources alphabetically. Although the code and GUI are in differnet orders. No matter how i sort the order in the code, something is forcing it to do it alphabetically  and if I create a new rule/pool that start with letter  "a" then will take the first rule with letter b and rename it with the new rule with letter a and so on . Really odd.
I understand  the current resource are in "sustained engineering mode" but i would really appreciate if you can help on this please?

**Comment by WodansSon** [comment]
@koko-a, if your state and var files are separated in the way you described above, they would not conflict/overwrite each other which is good so we can rule that out.

The next bit is a bit more complicated, because this has to do with the underlaying API, the provider, and the core runtime dependency graph generation(e.g. how terraform detects changes in the resources) . The alphabetical listing of the resources is coming from the Terraform Core Runtime, which I have no control over in the provider code. While this does seem to be an odd behavior this is just the way the core runtime works. This is complicated further since the classic front door resource is monolithic and that the API decided to change the order the JSON is returned to Terraform in the `GET` call. Which is why I exposed the `explicit_resource_order` in the first place.

That said, it does appear to me, without knowing your typology, from the attached `plan` in this issue that there is some overlap in the `UAT` and `PROD` environments.

```terraform
  ~ backend_pool {
      ~ health_probe_name   = "mytest-healthprobe" -> "dest-healthprobe"
        id                  = "/subscriptions/XXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/backendPools/mytest-pool"
      ~ load_balancing_name = "mytest-pool-loadbalancing" -> "dest-pool-loadbalancing"
      ~ name                = "mytest-pool" -> "dest-pool"

      ~ backend {
          ~ address     = "mytest.azurestaticapps.net" -> "dest.azurewebsites.net"
          ~ host_header = "mytest.azurestaticapps.net" -> "dest.azurewebsites.net"
            # (5 unchanged attributes hidden)
        }
    }
  ~ backend_pool {
      ~ health_probe_name   = "remarketing-healthprobe" -> "mytest-healthprobe"
        id                  = "/subscriptions/XXX/resourceGroups/msdn-afd-uat-rg/providers/Microsoft.Network/frontDoors/koko-msdn-frontdoor/backendPools/remarketing-pool"
      ~ load_balancing_name = "remarketing-pool-loadbalancing" -> "mytest-pool-loadbalancing"
      ~ name                = "remarketing-pool" -> "mytest-pool"

      ~ backend {
          ~ address     = "remarketing.azurestaticapps.net" -> "mytest.azurestaticapps.net"
          ~ host_header = "remarketing.azurestaticapps.net" -> "mytest.azurestaticapps.net"
            # (5 unchanged attributes hidden)
        }
    }
```

There appears to be some overlap in the config where `dest-healthprobe` and the `remarketing-healthprobe` are both being renamed/remapped to `mytest-healthprobe`? This is super hard for me to grok since I do not know the exact repro case here. Can you double check your vars/config file to make sure that resources are not getting reused/remapped to the same resources?

**Comment by koko-a** [comment]
@WodansSon 
No There are not any overlap between UAT and PROD. 
They are on a separate tfvar and state files.

This plan is from a test instance that i have been testing and trying to get to the bottom of the re-order issue . Basically this test environment  has 2x rules with 2 x pools only (   "mytest" and "remarketing") .
Once i run the apply is sort the above 2 rules\pools in alphabetical order into the state file under the 
explicit_resource_order.

When i tried to add a 3rd one called "dest-rule" with "dest-pool", with "dest-healthprobe", and "dest-pool-loadbalancing", the plan show that , instead of creating a new rule\pool called  "dest" 
it will rename "mytest pool " to "dest pool"  (that apply for pools, healthprobe and the loadbalancing as well)   , and then take  the next below in alphabetical order which is the remarketing and renaming to "mytest" ( including  pool, healthprobe and the loadbalancing)  and then recreate "remarketing"  instead. 
I am using test env as its easy to understand when you have 2-3  rules and pools, then over 25 . I can confirm that we have the same issue  for our UAT and PROD env . 


See below my test.tfvar file 


rg_name            = "msdn-afd-uat-rg"
location           = "northeurope"
fd_name            = "koko-msdn-frontdoor"
log_analytics_name = ""

###### FD Front Ends

fd_frontend = {
  koko-afd-test = {
    hostname                  = ""
    session_affinity          = ""
    sesstion_affinity_timeout = ""
    waf_policy                = "" 
  }
}

fd_redirect = {
  default-http-2-https = {
    frontend_endpoints = ["koko-afd-test","koko-msdn-frontdoor"]
    redirect_type = "PermanentRedirect"
  }
}

##### Pools #####
pools = {



  mytest = {
     health_probe_path = "/mytest/"
     hostname          = "mytest.azurestaticapps.net"
     https_port        = 443
     fqdn              = ["mytest.azurestaticapps.net"]
  }

  remarketing = {
     health_probe_path = "/locations"
     hostname = "remarketing.azurestaticapps.net"
     https_port = 443
     fqdn = ["remarketing.azurestaticapps.net"]
  }

  dest = {
     health_probe_path = "/dest-test/"
     hostname          = "dest.azurewebsites.net"
     https_port        = 443
     fqdn              = ["dest.azurewebsites.net"]
   } 
}

##### Routing

fd_routing = {



  mytest = {
    backendpool        = "mytest"
    patterns_to_match  = ["/mytest", "/mytest/*"]
    frontend_endpoints = ["koko-afd-test","koko-msdn-frontdoor"]
  }
 
  remarketing = {
      backendpool         = "remarketing"
      patterns_to_match   = ["/locations/"]
      frontend_endpoints  = ["koko-afd-test","koko-msdn-frontdoor"]
  }

  dest = {
     backendpool        = "dest"
     patterns_to_match  = ["/dest", "/dest/*"]
     frontend_endpoints = ["koko-afd-test","koko-msdn-frontdoor"]
  }  
}

**Comment by WodansSon** [comment]
@koko-a, while I am on vacation for the Thanksgiving Holiday in the US I still wanted to see if I could help with your issue. It appears that the API has changed since the original implementation of this resource and the out of order JSON fix. I was able to repro your issue, but I believe that was due to a change in the API, it appears that the service team has introduced two new `required` blocks that must be passed to the API:

## Newly Required Code Blocks for Front Door Classic:

```hcl
  # You must now have a 'default' backend pool setting
  backend_pool_settings {
    backend_pools_send_receive_timeout_seconds   = 0
    enforce_backend_pools_certificate_name_check = false
  }

  # You must also have a 'defaultHostName' frontend endpoint
  frontend_endpoint {
    name                         = "defaultHostName"
    host_name                    = "<host-name>.azurefd.net"
    session_affinity_enabled     = true
    session_affinity_ttl_seconds = 0
  }
``` 
I did see the out of order issue you reported before I added the above blocks to my configuration file, exactly as you reported. However, once I added the above blocks and applied the changes the diff went away with the next `plan`. So I think this should fix the issue you are seeing if you add these two newly required `default` blocks to your configuration file. Let me know if this fixes your issue or not. 🚀

**Comment by koko-a** [comment]
Thanks @WodansSon ,
I appreciate you are trying to help out while you are on vacation. 

This block below already exist  in the module, you can see it just below the 
```
azurerm_frontdoor resource:  
  backend_pool_settings{
    backend_pools_send_receive_timeout_seconds   =0
   enforce_backend_pools_certificate_name_check =false
}
```
Are you saying i need to add it somewhere else as well ?

The below two attributes for frontend_endpoint block  are optional ( according to TF documentations) and they already exist under the Custom domain frontend_endpoint . They were missing on the default frontend_endpoint but 
I can confirm that event if i add them the issue is still there 
 
```
   session_affinity_enabled     = true
    session_affinity_ttl_seconds = 0
```
Just want to clarify again that once you run the apply , and if you run the plan next again will show no changes , which is great , however the issue re-appear again when you create a new rule or  pool with blackend_pool_health_probe and backend_pool_load_balancing

Please try to create a new rule and pool and you will see what i mean the issue also re-aapears when you delete an existing rule or pool
Thank you

**Comment by WodansSon** [comment]
Hi @koko-a, no what I am saying is that you need to add the following block into your configuration file.

```hcl
  frontend_endpoint {
    name                         = "defaultHostName"
    host_name                    = "<fontdoor-name>.azurefd.net"
    session_affinity_enabled     = true
    session_affinity_ttl_seconds = 0
  }
}
```

This appears to be a new block that is being returned by the API and since it is not in the internal list it is throwing the compare logic off within Terraform and in turn showing you the re-order issue.  This is something new that is being returned by the API since the re-order JSON fix what introduced. Since there is a new JSON object that is not in the state file that is why I believe you are seeing this drift in you plan after adding/removing your rule/pool.

That said, since this a monolithic API there isn't a whole lot we can do in the Terraform provider to change the API behavior, there are implied create/destroy orders that will give you unexpected errors. That is due to the design of the legacy(classic) API. 

Since this resource is slated to be removed from the provider in v4.0, I do not feel there is anything else which can be done to alleviate your current issue you are hitting. I am sorry, but these resources are as the will be until they are retired in v4.0. Hope this makes sense and I am sorry if I was not able to help you.
