### ISSUE TITLE
azurerm_windows_web_app java 17 support

### ISSUE THREAD

**Issue by peterprumbach-telekom** [hashicorp/terraform-provider-azurerm#19171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    java_version = "17"
  }
}
```

### Debug Output/Panic Output

```shell
16:08:37  ╷
16:08:37  │ Error: expected site_config.0.application_stack.0.java_version to be one of [1.8 11], got 17
16:08:37  │ 
16:08:37  │   with module.eps_env_ppo_app_001.azurerm_windows_web_app.webapp,
16:08:37  │   on .terraform/modules/eps_env_ppo_app_001/webapp-windows/main.tf line 23, in resource "azurerm_windows_web_app" "webapp":
16:08:37  │   23:       java_version           = var.java_version
16:08:37  │ 
16:08:37  ╵
```

**Comment by peterprumbach-telekom** [comment]
![grafik](https://user-images.githubusercontent.com/113669010/200524804-6581dfe1-e99c-49c5-be32-9e7b6d7f71d6.png)

**Comment by xiaxyi** [comment]
Thanks @peterprumbach-telekom for raising this issue, you can track the status in the mentioned pr.
