### ISSUE TITLE
private_dns_resolver_outbound_endpoint_ids documentation issue

### ISSUE THREAD

**Issue by JozefSmajda** [hashicorp/terraform-provider-azurerm#19194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_resolver_dns_forwarding_ruleset

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_resolver_dns_forwarding_ruleset" "example" {
  name                                       = "example-ruleset"
  resource_group_name                        = azurerm_resource_group.example.name
  location                                   = azurerm_resource_group.example.location
  dns_resolver_outbound_endpoints = [azurerm_private_dns_resolver_outbound_endpoint.example.id]
  tags = {
    key = "value"
  }
```

### Debug Output/Panic Output

```shell
The argument "private_dns_resolver_outbound_endpoint_ids" is required, but no definition was found.
```

### Expected Behaviour

[dns_resolver_outbound_endpoints] - (Required) The list of IDs of the Private DNS Resolver Outbound Endpoint that is linked to the Private DNS Resolver Dns Forwarding Ruleset .

[source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_resolver_dns_forwarding_ruleset)

### Actual Behaviour

[private_dns_resolver_outbound_endpoints_ids] - (Required) The list of IDs of the Private DNS Resolver Outbound Endpoint that is linked to the Private DNS Resolver Dns Forwarding Ruleset .

**Comment by CorrenSoft** [comment]
@JozefSmajda, just to confirm. The docs say that the property name is **_dns_resolver_outbound_endpoints_** but the expected name is **_private_dns_resolver_outbound_endpoints_ids_**, right?

**Comment by JozefSmajda** [comment]
Exactly.

**Comment by catriona-m** [comment]
Looks like this has been fixed now and this can be closed. Thanks @JozefSmajda !
