### ISSUE TITLE
Support for .NET 7 for windows/linux web app

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#19204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are new capabilities offered by .NET 7 and run web apps in Azure App Service. The early access feature of App Service provides immediate access to new language releases such as .NET 7. As new .NET 7 capabilities are released, you can integrate them into your web apps and use App Service to deploy and scale those apps, without waiting for an App Service platform update.

Azure App Service support for .NET 7.0 follows the .NET 7.0 lifecycle.

### New or Affected Resource(s)/Data Source(s)

* azurerm_windows_web_app 
* azurerm_linux_web_app

### Potential Terraform Configuration
```
resource "azurerm_linux_web_app" "example" {
  site_config {
    application_stack {
      dotnet_version = "7.0"
    }
  }
  ...
```

### References

https://azure.microsoft.com/en-us/updates/public-preivew-app-service-support-for-net-7/

**Comment by xiaxyi** [comment]
Thanks @abilous-ti for raising this issue, dotnet 7.0 is supported in current provider. Have you met any error when using 7.0?

This is my config:
```

resource "azurerm_linux_web_app" "test" {
  name                = "xiaxintestLWA"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  service_plan_id     = azurerm_service_plan.testLinux.id

  site_config {
    application_stack {
      dotnet_version = "7.0"
    }
  }
}

resource "azurerm_windows_web_app" "test" {
  name                = "xiaxintestWWA"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  service_plan_id     = azurerm_service_plan.testWindows.id

  site_config {
    application_stack {
      dotnet_version = "v7.0"
      current_stack  = "dotnet"
    }
  }
}
```

```
azurerm_linux_web_app.test: Creation complete after 51s [id=/subscriptions/xxx/resourceGroups/xiaxintestRG-lwa/providers/Microsoft.Web/sites/xiaxintestLWA]
azurerm_windows_web_app.test: Still creating... [50s elapsed]
azurerm_windows_web_app.test: Creation complete after 55s [id=/subscriptions/xxx/resourceGroups/xiaxintestRG-lwa/providers/Microsoft.Web/sites/xiaxintestWWA]
```

**Comment by abilous-ti** [comment]
@xiaxyi I tested yesterday and I was also able to create Azure Web App with .Net version 7.0.
I see that documentation was also updated.
Thank you

**Comment by tombuildsstuff** [comment]
Glad to hear this is now working for you @abilous-ti - closing this out 👍
