### ISSUE TITLE
Support for SQLInstanceSettings on azurerm_mssql_virtual_machine

### ISSUE THREAD

**Issue by forktrucka** [hashicorp/terraform-provider-azurerm#19207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm hoping that `azurerm_mssql_virtual_machine` can be extended to support `SQLInstanceSettings` (on the arm spec) to sort my use case where we are trying to automate infrastructure creation and deployments to a legacy app that requires a sql vm with a non-default collation (I believe it is `sql_latin1_general_cp1_ci_as`, I am hoping to use `Latin1_General_CI_AS`), and we also wish to set min/max memory configuration.

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_virtual_machine" "example" {
  SQLInstanceSettings {
    MaxDop = number
    IsOptimizeForAdHocWorkloadsEnabled = bool
    Collation = string
    MinServerMemoryMB = number
    MaxServerMemoryMB = number
    IsLPIMEnabled = bool
    IsIFIEnabled = bool
  }
}
```

### References

https://learn.microsoft.com/en-us/javascript/api/@azure/arm-sqlvirtualmachine/sqlinstancesettings?view=azure-node-preview

**Comment by msl0** [comment]
Hi @forktrucka, this feature already exists #19123

**Comment by forktrucka** [comment]
> Hi @forktrucka, this feature already exists #19123 

Need to double check but, I believe the settings I'm talking about are missing from the existing feature.

**Comment by forktrucka** [comment]
> Hi @forktrucka, this feature already exists #19123 

Wow. How unlucky. 2 days after..
