### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert documentation is incorrect

### ISSUE THREAD

**Issue by FinchHop** [hashicorp/terraform-provider-azurerm#19218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.18.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert" "unhandled_exceptions"{
    name = unhandled_exceptions
    resource_group_name =  azurerm_resource_group.my_resource_group.name
    data_source_id = azurerm_application_insights.my_service_appinsights.id
    frequency = 15
    time_window = 15
    enabled = "true"
    severity = 1

        query = <<-QUERY
    exceptions
    | where timestamp between (ago(5m)..now()) and ['type'] contains \"Unhandled\"
    QUERY

    trigger {
        operator = "GreaterThan"
        threshold = 1
    }

    action {
        action_group = [azurerm_monitor_action_group.pagerduty_alerter.id]
    }

}
```

### Debug Output/Panic Output

```shell
On terraform validate:
Error: Missing required argument
│
│   on main.tf line 120, in resource "azurerm_monitor_scheduled_query_rules_alert" "unhandled_exceptions":
│  120: resource "azurerm_monitor_scheduled_query_rules_alert" "unhandled_exceptions"{
│
│ The argument "location" is required, but no definition was found.


On terraform apply:

Error: creating or updating Monitor Scheduled Query Rules: (Scheduled Query Rule Name "unhandled_exceptions" / Resource Group "my_resource_group"): insights.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\r\n  \"error\": {\r\n    \"message\": \"The request had some invalid properties\",\r\n    \"code\": \"BadArgumentError\",\r\n    \"correlationId\": \"b0857cdf-c868-4d84-9ae6-82ec6ed3a59b\",\r\n    \"innererror\": {\r\n      \"code\": \"SyntaxError\",\r\n      \"message\": \"Request is invalid and cannot be processed: Syntax error: SYN0001: I could not parse that, sorry. [line:position=0:0]\"\r\n    }\r\n  }\r\n}" 
November 9th 2022 12:35:37Error
  with azurerm_monitor_scheduled_query_rules_alert.unhandled_exceptions, 
November 9th 2022 12:35:37Error
  on main.tf line 120, in resource "azurerm_monitor_scheduled_query_rules_alert"
```

### Expected Behaviour

Should have been validated, and plan applied, since it was structured according to the documentation

### Actual Behaviour

Validate failed, and later on after location was included, apply failed

### Steps to Reproduce

terrform init
terraform validate
terraform workplace select "myworkspace"
terraform apply -no-color -input=false -auto-approve -var-file="vars-dev.tfvars" 

### Important Factoids

This should be an easy fix. Documentation should reference need for location. Additionally, the "<<-QUERY ... QUERY" syntax is incorrect. I got mine to work by removing all references to the QUERY beginning and end bits. I also formatted it in a one line string, with \n line breaks as needed.

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert

**Comment by teowa** [comment]
Hi @FinchHop , thanks for submitting this issue!
the `<<-QUERY ... QUERY` is called Indented Heredocs string, from [doc](https://developer.hashicorp.com/terraform/language/expressions/strings#indented-heredocs):
> Backslash sequences are not interpreted as escapes in a heredoc string expression. Instead, the backslash character is interpreted literally.

below format with not backslash can work:
```
        query = <<-QUERY
    exceptions
    | where timestamp between (ago(5m)..now()) and ['type'] contains "Unhandled"
    QUERY
```

And I will add `location` property in document, thanks for the issue.
