### ISSUE TITLE
AzureRM linux_function_app doesnot accepts dotnet version 7.0

### ISSUE THREAD

**Issue by venkad-intc** [hashicorp/terraform-provider-azurerm#19257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.30.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
```

### Debug Output/Panic Output

```shell
2022-11-11T14:27:09.112Z [ERROR] provider.terraform-provider-azurerm_v3.30.0_x5: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.10.0/tfprotov5/internal/diag/diagnostics.go:56 diagnostic_detail= diagnostic_summary="expected site_config.0.application_stack.0.dotnet_version to be one of [3.1 6.0], got 7.0" diagnostic_severity=ERROR tf_proto_version=5.2 tf_rpc=ValidateResourceTypeConfig diagnostic_attribute=AttributeName("site_config").ElementKeyInt(0).AttributeName("application_stack").ElementKeyInt(0).AttributeName("dotnet_version") tf_provider_addr=provider tf_req_id=b0a93167-c54b-1249-91c6-806504437594 tf_resource_type=azurerm_linux_function_app @module=sdk.proto timestamp=2022-11-11T14:27:09.111Z
```

### Expected Behaviour

7.0 should be accepted together with use_dotnet_isolated_runtime enabled.

### Actual Behaviour

 Error: expected site_config.0.application_stack.0.dotnet_version to be one of [3.1 6.0], got 7.0

### Steps to Reproduce

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "linuxfunctionappsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "example" {
  name                = "example-app-service-plan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    application_stack {
      dotnet_version=7.0
      use_dotnet_isolated_runtime = true
     }
  }
}
```

### Important Factoids

Azure Public 

### References

Provider documentation: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app#:~:text=dotnet_version%20%2D%20(Optional)%20The%20version%20of%20.NET%20to%20use.%20Possible%20values%20include%203.1%2C%206.0%20and%207.0

**Comment by xiaxyi** [comment]
Thanks @venkad-intc for raising this issue, can you try using the double quote for `dotnet_version` like `dotnet_version="7.0"`?

The property `dotnet_version` is being defined as string.

**Comment by xiaxyi** [comment]
@manicminer Thanks for labeling this issue, this is not an enhancement, it's wrong usage.

**Comment by venkad-intc** [comment]
> Thanks @venkad-intc for raising this issue, can you try using the double quote for `dotnet_version` like `dotnet_version="7.0"`?
> 
> The property `dotnet_version` is being defined as string in provider code.
> 
> Feel free to let me know if it works for you. :)

No luck with `dotnet_version="7.0"`. As the error message explicitly says ` Error: expected site_config.0.application_stack.0.dotnet_version to be one of [3.1 6.0], got 7.0`, it doesn't look like a type conversion issue.

**Comment by xiaxyi** [comment]
@venkad-intc what provider version are you using?

**Comment by venkad-intc** [comment]
> ```terraform
> Terraform v1.2.5
> on linux_amd64
> + provider registry.terraform.io/hashicorp/azurerm v3.30.0
> + provider registry.terraform.io/hashicorp/null v3.1.0
> + provider registry.terraform.io/hashicorp/random v3.4.3
> ```

Terraform v1.2.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.30.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

**Comment by f1nzer** [comment]
> provider registry.terraform.io/hashicorp/azurerm v3.30.0

dotnet 7.0 support for linux_function_app was added in version 3.31.0

**Comment by manicminer** [comment]
Thanks @f1nzer, it was indeed just added.

@venkad-intc Please update to the latest version of the provider (v3.31.0 or later) for dotnet 7.0 support
