### ISSUE TITLE
Issues related to Postgres Flexible Server creation when resource group locks are in use

### ISSUE THREAD

**Issue by tspearconquest** [hashicorp/terraform-provider-azurerm#19262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.15.1 - I am aware this is behind by a number of releases

### Affected Resource(s)/Data Source(s)

azurerm_postgres_flexible_server

### Terraform Configuration Files

We have a private DNS zone module with the following code:

```hcl
resource "azurerm_private_dns_zone" "default" {
  name                = var.domainname # example: privatelink.blob.core.windows.net
  resource_group_name = var.rg_name
}

resource "azurerm_private_dns_zone_virtual_network_link" "default" {
  name                = var.private_dns_vnet_link_name
  resource_group_name = var.rg_name

  private_dns_zone_name = azurerm_private_dns_zone.default.name
  virtual_network_id    = var.remote_vnet_id
  registration_enabled  = false
}
```

We include this module in a virtual network module. The relevant parts of the virtual network module are below:

```hcl
resource "azurerm_resource_group" "default" {
  name     = var.rg_name
  location = var.region
}

# Resource locks to prevent accidental deletion
resource "azurerm_management_lock" "rg_level" {
  name       = "${var.rg_name}-lock"
  scope      = azurerm_resource_group.default.id
  lock_level = "CanNotDelete"
  notes      = "Delete protection"
}

resource "azurerm_virtual_network" "default" {
  name                = var.vnet_name
  address_space       = var.vnet_address_spaces
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
}

module "private_dns_zones" {
  source  = "/path/to/my/dns_module"

  for_each = var.private_dns_zones

  domainname = each.key
  rg_name    = var.rg_name

  private_dns_vnet_link_name = each.value
  remote_vnet_id             = azurerm_virtual_network.default.id
}

module "subnets" {
  source  = "/path/to/my/subnet/module"

  rg_name                    = var.rg_name
  vnet_name                  = each.key
  parent_vnet_address_spaces = each.value

  subnets = var.subnets
}
```

This virtual network module is then pulled into a bigger project with multiple pipeline jobs writing to separate state files. The part of the bigger project related to the virtual network module above is below (note the big comment, this is the issue):

```hcl
module "network" {
  source  = "/path/to/my/network_module"

  region = var.region

  rg_name = "${local.vnet_name_prefix}-${var.region}-${var.deployment_type}-${local.vnet_name_index}-rg"

  ## Azure requires the virtual network to be unlocked in order to use postgres flexible server
  ## This requirement is supposed to only affect automatic DNS changes during HA failovers between
  ## availability zones, but we ran into errors about the virtual network being locked even after
  ## disabling zone redundancy in the postgres config
  ## Fortunately, Azure doesn't allow you to delete a virtual network out from under a cluster
  ## So we are keeping the cluster and database server resource groups locked to prevent the
  ## virtual network from being deleted by terraform on accident

  create_rg_lock = true # we have been forced to set this to false because of the bug but I've marked it true in this GitHub issue to demonstrate the failure scenario

  vnet_name           = "${local.vnet_name_prefix}-${var.region}-${var.deployment_type}-${local.vnet_name_index}"
  vnet_address_spaces = var.vnet_address_spaces

  # Example:
  # "private.dns.domainname.tld"          = "private-dns-vnet-link-name"
  private_dns_zones = {
    "privatelink.${var.region}.azmk8s.io" = "private-aks-cluster-dns-to-cluster-vnet",
    "privatelink.blob.core.windows.net"   = "private-blob-storage-dns-to-cluster-vnet",
    "privatelink.servicebus.windows.net"  = "private-eventhub-dns-to-cluster-vnet",
    "privatelink.vaultcore.azure.net"     = "private-keyvault-dns-to-cluster-vnet"
  }

  create_postgres_private_dns_zone = true
  postgres_private_dns_rg_name     = "postgres-private-dns-zone-${var.region}-${var.deployment_type}-${local.vnet_name_index}-rg"

  subnets = [
    {
      delegated               = false,
      delegated_service_types = [],
      endpoint_config = {
        private_endpoints_enabled = var.private_endpoints_enabled,
        svc_endpoints             = var.svc_endpoints
      },
      name     = "node-and-pod-snet",
      new_bits = 2 # Adds 2 to the /15 assigned to the vnet to give the nodes and pods a /17 subnet
    }
  ]
}
```

The subnets block above is not relevant to this issue, but included for full context.
However, the next block is in the same terraform manifest and is relevant. As you can see, we create the postgres delegated subnet via its own subnet module and it is associated with the same resource group as the code above:

```hcl
module "postgres_delegated_subnet" {
  source  = "/path/to/my/subnet/module"

  rg_name   = "${local.vnet_name_prefix}-${var.region}-${var.deployment_type}-${local.vnet_name_index}-rg"
  vnet_name = module.network.vnet_name

  parent_vnet_address_spaces = local.db_subnet_address_spaces

  subnets = [
    {
      delegated               = true,
      delegated_service_types = ["postgres"],
      endpoint_config = {
        private_endpoints_enabled = true,                 ## Postgres delegated subnet must enforce private endpoint network policies
        svc_endpoints             = ["Microsoft.Storage"] ## Automatically applied by Azure
      },
      name     = "postgres-subnet",
      new_bits = 1 # Adds 1 to the /25 picked by local.db_subnet_address_spaces[0] to give us a /26 for postgres
    }
  ]
}
```

The postgres flexible server code is also a module in a different pipeline job and writing to a different state file:

```hcl
resource "azurerm_postgresql_flexible_server" "default" {
  name                = var.server_name
  resource_group_name = var.rg_name
  location            = var.region

  administrator_login    = var.admin_user
  administrator_password = var.admin_password

  backup_retention_days = var.backup_retention_days
  geo_redundant_backup_enabled = false

  depends_on = [azurerm_resource_group.default]

  delegated_subnet_id = var.dedicated_subnet_id # The delegated subnet ID 
  private_dns_zone_id = var.private_dns_zone_id # The private DNS zone ID from the code above

  sku_name   = var.sku_name # GP_Standard_D4ds_v4
  storage_mb = var.storage_mb # 32768
  version    = var.server_version # 14
  zone       = var.default_availability_zone # currently set to 1

  dynamic "high_availability" {
    for_each = var.high_availability == true ? ["ha"] : [] # in production we would set var.high_availability to true via TFVARS in order to include the high availability block, but in dev where we are currently testing, we have it set to false via TFVARS

    content {
      mode                      = "ZoneRedundant"
      standby_availability_zone = var.standby_availability_zone
    }
  }

  maintenance_window {
    day_of_week = var.maintenance_start_day
  }

  lifecycle {
    ignore_changes = [
      high_availability["ha"].standby_availability_zone,
      zone
    ]
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Flexible Server (Subscription: "[MASKED]"
│ Resource Group Name: "xxxxxxxxx"
│ Server Name: "xxxxxxxxx"): polling after Create: Code="OperationFailed" Message="Operation on resource xxxxxxxxx/subnets/postgres-subnet under resource type VirtualNetworks is blocking by customer lock, Please release the lock to unblock the operation. Lock details: [Lock Name: xxxxxxxxx, Lock Id: /subscriptions/[MASKED]/resourceGroups/xxxxxxxxx/providers/Microsoft.Authorization/locks/xxxxxxxx, Lock Level: CanNotDelete]"
│ 
│   with module.postgres["xxxxxxxx"].azurerm_postgresql_flexible_server.default,
│   on .terraform/modules/postgres/main.tf line 24, in resource "azurerm_postgresql_flexible_server" "default":
│   24: resource "azurerm_postgresql_flexible_server" "default" {
```

### Expected Behaviour

Postgres Flexible server is created without error

### Actual Behaviour

Received the error above

The documentation [here](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-networking#unsupported-virtual-network-scenarios) clearly indicates that using a resource group lock on a private DNS zone is the only limitation. By extension, we assume that to also include the resource group where the private DNS zone is located.

So what we've done is placed the private DNS zone for the postgres private endpoint into its own completely separate resource group, which we left unlocked because of the documentation above, and we've created a resource group containing a virtual network with 2 subnets (one of them is delegated to postgres flexible servers) and 5 other private DNS zones, and a resource group lock.

According to the documentation, since we have Zone Redundancy turned off, this should work properly. Additionally, even with Zone Redundancy turned on, it should work because we've placed the postgres private DNS zone into its own resource group with no lock in place.

To be clear, we did not lock the private DNS zone resource group, nor the zone itself, nor any of the records within the zone. Yet when we try to create the server, it fails because the delegated subnet is locked. The original intent was to have the virtual network and both subnets be locked, leaving the private DNS zone unlocked to allow terraform to create the flexible server itself and allow for failovers to occur properly by having the DNS zone able to be modified during those events.

The documentation doesn't mention anything about the delegated subnet needing to be unlocked.

### Steps to Reproduce

Run terraform plan and then run terraform apply

### Important Factoids

n/a

**Comment by tspearconquest** [comment]
Hi @aristosvo these are unrelated, please reopen.

**Comment by aristosvo** [comment]
@tspearconquest Can you in that case explain what the issue is for the Terraform Provider for Azure? In my regard the issue is documentation of a locking detail, which I would not expect to be documented here, but in the Azure Docs.

**Comment by tspearconquest** [comment]
Also, the issue you've linked which I created, relates to an action in the Terraform documentation which is missing from the Azure documentation and is not an action which was added to our subnet after I worked around this issue.

I simply was working on something unrelated to this issue and made the observation that it was listed in the Terraform documentation but not Azure documentation. :)

**Comment by aristosvo** [comment]
@tspearconquest The issues you are mentioning are things which should be documented in Azure, probably on the same place you are referring to in the issue. The errors you are getting when applying the terraform config are thrown by the Azure REST API, not by the provider, just given back to you.

Although global behaviour of a resource will usually be documented in the `azurerm` docs, this seems a bit too detailed and for really specific use cases. Please raise these as issues towards the Microsoft Azure docs if not covered there.

**Comment by tspearconquest** [comment]
Okay, understood. Will open separate issues. Thanks!
