### ISSUE TITLE
Error: Failed to get existing workspaces: containers.Client#ListBlobs:

### ISSUE THREAD

**Issue by nimblenitin** [hashicorp/terraform-provider-azurerm#19277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.19. 0

### Affected Resource(s)/Data Source(s)

all resource

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 3.16.0"
    }
  }
  backend "azurerm" {
    resource_group_name  = "XXX"
    storage_account_name = "XXX"
    container_name       = "XXX"
    key                  = "XXX"
    access_key           = "XXX"
  }
}
```

### Debug Output/Panic Output

```shell
Error: Failed to get existing workspaces: containers.Client#ListBlobs: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.\nRequestId:XXX"
```

### Expected Behaviour

I am using azure storage as Terraform backend. It was working fine. I removed a private endpoint for the storage from configuration and did terraform apply. It starts giving me this error. Is there need of Private endpoint for storing Terraform state in Azure storage? Also not sure why got above error. I am unable to do terraform init with this error.

**Comment by manicminer** [comment]
Hi @nimblenitin, thanks for opening this issue. I believe this is more of a usage question than a bug in the provider. Additionally, the error you are getting seems to be coming from the AzureRM backend, which is separate to the provider and for which issues can be raised on the [Terraform core repository](https://github.com/hashicorp/terraform/issues).

However, as mentioned I believe this is more or a usage question. We use GitHub issues for tracking feature requests and bugs in the provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly I'm going to close this issue, but I believe you should be able to get an answer on the community discussion portal.
