### ISSUE TITLE
Permission error when using Key Vaults from different subscriptions

### ISSUE THREAD

**Issue by dvanrijnberk** [hashicorp/terraform-provider-azurerm#19282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

data.azurerm_key_vault_secrets, data.azurerm_key_vault_secret,  azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
main.tf
----------------------
#
MORE AKS CREATION RESOURCES...
#
resource "azurerm_key_vault_access_policy" "custom" {
  for_each = local.kv_policies <-- List of Access Policies to be created

  key_vault_id = var.keyvault_id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = each.value.object_id

  certificate_permissions = try(each.value.certificate_permissions, [])

  key_permissions = try(each.value.key_permissions, [])

  secret_permissions = try(each.value.secret_permissions, [])

  storage_permissions = try(each.value.storage_permissions, [])
}

module "kub-init" {
  count  = var.enable_kub_init == true ? 1 : 0
  source = "./modules/kub-init"

  sshkey_kv_id = var.sshkey_kv_id
}
----------------------

./modules/kub-init/main.tf
----------------------
data "azurerm_key_vault_secrets" "sshkeys" {

  key_vault_id = var.sshkey_kv_id
}

data "azurerm_key_vault_secret" "sshkeys" {

  for_each     = toset(data.azurerm_key_vault_secrets.sshkeys.names)
  name         = each.key
  key_vault_id = var.sshkey_kv_id
}
----------------------
```

### Debug Output/Panic Output

```shell
╷
│ Error: retrieving parent Vault: (Name "${Correct Resource Name of var.sshkey_kv_id}" / Resource Group "${Correct Resource Group name of var.sshkey_kv_id}"): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '${SPN CLIENT ID OF TERRAFORM}' with object id '${SPN OBJECT ID OF TERRAFORM}' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/${Wrong SUBSCRIPTION_ID OF var.sshkey_kv_id}/resourceGroups/${Correct Resource Group name of var.keyvault_id}/providers/Microsoft.KeyVault/vaults/${Correct Resource Name of var.keyvault_id}' or the scope is invalid. If access was recently granted, please refresh your credentials."
│
│   with module.aks.azurerm_key_vault_access_policy.custom["policy1"],
│   on .terraform/modules/aks/main.tf line 155, in resource "azurerm_key_vault_access_policy" "custom":
│  155: resource "azurerm_key_vault_access_policy" "custom" {
│
╵
╷
│ Error: retrieving parent Vault: (Name "${Correct Resource Name of var.sshkey_kv_id}" / Resource Group "${Correct Resource Group name of var.sshkey_kv_id}"): keyvault.VaultsClient#Get: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '${SPN CLIENT ID OF TERRAFORM}' with object id '${SPN OBJECT ID OF TERRAFORM}' does not have authorization to perform action 'Microsoft.KeyVault/vaults/read' over scope '/subscriptions/${Wrong SUBSCRIPTION_ID OF var.sshkey_kv_id}/resourceGroups/${Correct Resource Group name of var.keyvault_id}/providers/Microsoft.KeyVault/vaults/${Correct Resource Name of var.keyvault_id}' or the scope is invalid. If access was recently granted, please refresh your credentials."
│
│   with module.aks.azurerm_key_vault_access_policy.custom["policy2"],
│   on .terraform/modules/aks/main.tf line 155, in resource "azurerm_key_vault_access_policy" "custom":
│  155: resource "azurerm_key_vault_access_policy" "custom" {
│
╵
```

### Expected Behaviour

The access policies should be created on the "var.keyvault_id" KeyVault while the datasource should retrieve the secrets from "var.sshkey_kv_id".

### Actual Behaviour

Terraform tries to get the secrets from the "var.keyvault_id" while using the subscription id of "var.sshkey_kv_id". 

### Steps to Reproduce

1. terraform apply

The workaround for this issue is declaring a depends_on for the AKS module above and the access policy it is creating. It seems that when the datasource tries to read the secrets while the access policies are being created the Subscriptions are getting mixed up.

Working situation:
module "kub-init" {
   depends_on = [
     azurerm_kubernetes_cluster.aks,
     azurerm_key_vault_access_policy.custom
   ]
  count  = var.enable_kub_init == true ? 1 : 0
  source = "./modules/kub-init"

  sshkey_kv_id = var.sshkey_kv_id
}

**Comment by dvanrijnberk** [comment]
It looks like this is an duplicate of #14516 after further research.

**Comment by rcskosir** [comment]
@dvanrijnberk Thank you for finding the duplicate issue #14516, and the forum: https://discuss.hashicorp.com/t/subscription-id-is-replaced-when-working-with-multiple-subscriptions/32940/2
I will be closing this issue as a duplicate. Kindly please follow the forum to see if there are future updates.
