### ISSUE TITLE
Support for Node.js 18 in web_app_schema and web_app_slot_schema

### ISSUE THREAD

**Issue by baronsunoko** [hashicorp/terraform-provider-azurerm#19289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Web Apps support for Node.js 18 is now available. Currently, linux/windows web apps and web app slots only go so far as version 16-lts. 

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app, azurerm_linux_web_app_slot, azurerm_windows_web_app, azurerm_windows_web_app_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example-linux-web-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    application_stack {
      node_version = "18-lts"
    }
}
```

**Comment by xiaxyi** [comment]
Thanks @baronsunoko for raising this issue, let me check the feature, will submit a pr to support it once confirmed. Feel free to let me know if there is anything needed.

**Comment by fa-bwilliams** [comment]
This is not fixed. azurerm_linux_web_app and azurerm_linux_web_app_slot currently will not accept '18-lts' for the node_version property in the application_stack block. It currently supports 12-lts (which should be removed), 14-lts and 16-lts but not 18-lts.

https://azure.microsoft.com/en-us/updates/node12/
