### ISSUE TITLE
Support for setting tls-min-version and tls-cipher-suites in kubelet_config

### ISSUE THREAD

**Issue by hobti01** [hashicorp/terraform-provider-azurerm#19280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`kubelet_config` in `azurerm_kubernetes_cluster.default_node_pool` and `azurerm_kubernetes_cluster_node_pool` does not allow setting kubelet arguments `tls-min-version` or `tls-cipher-suites`.  This prevents the configuration of the kubelet to for secure TLS versions, i.e. TLS 1.2 or higher.

These arguments and allowed values are described here https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster, azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"

    kubelet_config {
      tls_min_version = "VersionTLS12"
      tls_cipher_suites = [
        "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      ]
    }
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1

  kubelet_config {
    tls_min_version = "VersionTLS12"
    tls_cipher_suites = [
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
    ]
  }
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/11119 provided a limited set of kubelet arguments, but not these TLS related arguments.

**Comment by aristosvo** [comment]
@hobti01 Thanks for opening this issue.

Can you point me to the docs describing the functionality being available for AKS? Based on [this docs](https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration) it seems this is not supported (yet).

**Comment by hobti01** [comment]
Ah you are certainly right, it does not look to be supported yet.  I have opened https://github.com/Azure/AKS/issues/3334 to request this.

**Comment by thiagoescobar** [comment]
Any updates on this issue or roadmap for this to be implemented?

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. The upstream request can be tracked here: https://github.com/Azure/AKS/issues/3334
When it gets added, we can reopen this request or you can create a new one.
