### ISSUE TITLE
Terraform cannot delete keys in key vault with purge disabled in feature block

### ISSUE THREAD

**Issue by Joshua-Viewpointe** [hashicorp/terraform-provider-azurerm#19307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_key, azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.31.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 3.4"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
}

data "azurerm_client_config" "current" {}

resource "random_uuid" "cryptouser_uuid" { }

resource "azurerm_resource_group" "rg" {
    location                          = var.rg_location
    name                              = var.rg_name
}

resource "azurerm_key_vault" "kv-core" {
  name                        = "kv-core"
  location                    = var.primary_location
  resource_group_name         = azurerm_resource_group.rg.name
  enabled_for_disk_encryption = false
  enabled_for_deployment      = false
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = true
  enable_rbac_authorization   = true
  sku_name                    = "standard"
}

resource "azurerm_key_vault_key" "kv-key-core" {
  name         = "rsa-cmk-2048"
  key_vault_id = azurerm_key_vault.kv-core.id
  key_type     = "RSA"
  key_size     = 2048
  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
}

resource "tls_private_key" "ssh" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
resource "azurerm_key_vault_secret" "ssh-private-key" {
  name         = "ssh-private-key"
  value        = tls_private_key.ssh.private_key_pem
  key_vault_id = azurerm_key_vault.kv-core.id
}
resource "azurerm_key_vault_secret" "ssh-public-key-pem" {
  name         = "ssh-public-key-pem"
  value        = tls_private_key.ssh.public_key_pem
  key_vault_id = azurerm_key_vault.kv-core.id
}
resource "azurerm_key_vault_secret" "ssh-public-key-openssh" {
  name         = "ssh-public-key-openssh"
  value        = tls_private_key.ssh.public_key_openssh
  key_vault_id = azurerm_key_vault.kv-core.id
}
```

### Debug Output/Panic Output

```shell
Error: purging of Secret "ssh-public-key-openssh" (Key Vault "https://kv-core.vault.azure.net/") :
keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 --
Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message=
"Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault 
service will automatically purge it after the retention period has passed.\r\nVault: kv-core;location=southcentralus"
│
│
╵
╷
│ Error: cannot purge key "rsa-cmk-2048" because vault "Vault: (Name \"kv-core\" / Resource Group \"rg_name\")" has purge protection enabled
│
│
╵
╷
│ Error: purging of Secret "ssh-private-key" (Key Vault "https://kv-core.vault.azure.net/") :
keyvault.BaseClient#PurgeDeletedSecret: Failure responding to request: StatusCode=403 --
Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message=
"Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault 
service will automatically purge it after the retention period has passed.\r\nVault: kv-core;location=southcentralus"
│
│
╵
╷
│ Error: cannot purge key "rsa-cmk-2048" because vault "Vault: (Name \"kv-core\" / Resource Group \"rg_name\")" has purge protection enabled
```

### Expected Behaviour

 Terraform destroy should delete my resource group, key vaults, and key vault keys, specifically when configuring feature block to...
   
```
features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
```

### Actual Behaviour

I receive an error for each key stating...

'Error: cannot purge key "rsa-cmk-2048" because vault "Vault: (Name \"kv-core\" / Resource Group \"rg_name\")" has purge protection enabled.'

If I run terraform destroy a second time, the SSH private, public, and openssh public keys WILL actually be deleted, but the RSA key will not and I again receive the error...

'Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault.'

I am executing my Terraform commands via a Service Principal with appropriate roles and permissions as a key vault owner. It is important to note that RBAC is enforced on the key vault and must remain so.

### Steps to Reproduce

1. Create and run terraform commands with a service principal posseting appropriate RBAC Key vault owner permissions.

2. terraform apply

3. terraform destroy
    (note: no keys are deleted)
    
4. terraform destroy (again)
    (note: the RSA key remains but SSH keys are destroyed)
    
5. Subsequent terraform destroy commands produce the same result as step 4

### Important Factoids

Running terraform in powershell, with a service principal possessing appropriate role base permissions for key vault. NOTE, I am able to delete the keys with the same service principal in az cli using  the "az keyvault key delete" command.

**Comment by milkfinch** [comment]
Same problem here.

We set up :
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
      recover_soft_deleted_key_vaults = false
    }
  }
}

But we get Error: cannot purge key "hrktestforenc-encryption-key" because vault "Vault: (Name \"<redacted>\" / Resource Group \"<redacted>\")" has purge protection enabled

@Joshua-Viewpointe could you please share what was the solution?

**Comment by fgarcia-cnb** [comment]
why was this closed? im seeing the same behavior

**Comment by milkfinch** [comment]
> why was this closed? im seeing the same behavior

For me the option purge_soft_deleted_keys_on_detroy=false in features solved the problem

**Comment by fgarcia-cnb** [comment]
ah good catch... i didnt realize they had made the KV features more granular. i only had `purge_soft_delete_on_destroy`, not the key specific one. thanks
