### ISSUE TITLE
Support for getting SNAT Ports from Load Balancer/AKS (data "azurerm_lb_outbound_rule")

### ISSUE THREAD

**Issue by ElvenSpellmaker** [hashicorp/terraform-provider-azurerm#19301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Due to the low SNAT port defaults of 1024 (even when you have a few nodes) when using the default Load Balancer configuration in Kubernetes and ran into SNAT port exhaustion.
(Moving to NAT Gateway isn't an option at the present time but still.)

We've since done this in our K8s to up the amount of allocated ports, allowing us to have 10 nodes:
```tf
...
    load_balancer_profile {
      outbound_ports_allocated = "5816"
      idle_timeout_in_minutes  = "4"
    }
...
```

However there's no way for us to retrieve the number, which we'd love so we may alert on X% of SNAT ports used for example, as there's no data source for Outbound Rules.

It'd be nice to expose this from the outputs of `azurerm_kubernetes_cluster` as well seeing as we set this from this resource (but no way of retrieving it), but at least _some_ way of getting them (i.e. `data "azurerm_lb_outbound_rule`) would be great.

![image](https://user-images.githubusercontent.com/2286713/201972120-5758db8f-7753-4f0a-a84c-6b83b0023cc9.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_lb_outbound_rule (new data), azurerm_kubernetes_cluster (affected data)

### References

https://learn.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections

**Comment by aristosvo** [comment]
Hi @ElvenSpellmaker! Thanks for raising this.

Is there at this moment a way to get the number you are looking for? Via `az` or the portal maybe? An example might help get your issue resolved sooner.

If this is not the case, I would advise to raise this at Microsoft side first.

**Comment by ElvenSpellmaker** [comment]
> Hi @ElvenSpellmaker! Thanks for raising this.
> 
> Is there at this moment a way to get the number you are looking for? Via `az` or the portal maybe? An example might help get your issue resolved sooner.
> 
> If this is not the case, I would advise to raise this at Microsoft side first.

Hey, you can definitely see the number in the portal (from my screenshot above)
I'll check `az` when I can.

https://user-images.githubusercontent.com/2286713/201972120-5758db8f-7753-4f0a-a84c-6b83b0023cc9.png

**Comment by aristosvo** [comment]
So to understand what you're looking for, correct me if I'm wrong:

- You set a value for the AKS resource 
- You want to get that same value as an output from a data source

Can you explain what the difference is between the two or why this helps?

**Comment by ElvenSpellmaker** [comment]
* Yeah we set a value in the AKS resource
* Under the hood it creates an lb with an outbound rule (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/lb_outbound_rule)
* I'd like to get that value back either from a data resource from the lb rule, or from AKS (or both)


The use-case is so we can set an alert up on SNAT ports used as a % of the total allocated without having to hardcode it.

Its the same value, just it can't currently be retrieved in TF, but can be seen in the portal and set by both the AKS resource and by standalone outbound_rule resources.

**Comment by ElvenSpellmaker** [comment]
Also for completeness to your original question, yes this can be obtained by `az`:
```bash
$ az network lb outbound-rule list -g MC-foo-bar-baz --lb-name kubernetes --subscription <sub>
[
  {
    "allocatedOutboundPorts": 5816,
...
```
