### ISSUE TITLE
azurerm_storage_data_lake_gen2_filesystem - enabling storage account firewall breaks access to filesystem for Synapse

### ISSUE THREAD

**Issue by elmariachi2323** [hashicorp/terraform-provider-azurerm#19302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.8

### AzureRM Provider Version

2.97.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem

### Terraform Configuration Files

```hcl
resource "azurerm_storage_data_lake_gen2_filesystem" "storage_data_lake_gen2_filesystem" {
  name               = var.storage_data_lake_gen2_filesystem_resource_name
  storage_account_id = var.storage_account_id
}
```

### Debug Output/Panic Output

```shell
Error: retrieving File System "eundpproddlstore01" in Storage Account "eundpproddlstore01": datalakestore.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: 
"" error: EOF
```

### Expected Behaviour

Storage account firewall has an IP whitelisting for my deployment location, yet still throws that error.

When disabling the storage account firewall, it works fine.

I assume this means that the filesystem retrieval is coming from somewhere else which is _not_ whitelisted but I don't know what.

### Actual Behaviour

The error above is thrown.

### Steps to Reproduce

terraform plan

### References

NA

**Comment by lukecalderon** [comment]
I have the same issue with a data lake within a storage account, with a private endpoint attached.

If I lock-down the storage firewall, terraform receives a `403` when trying to do a state refresh before a plan/apply. The private agent I'm using is able to resolve both the blob and DFS private endpoints successfully.

**Comment by lukecalderon** [comment]
Any progress on this?

**Comment by lukecalderon** [comment]
@Amier3 Possible to get an update/chaser on this?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
