### ISSUE TITLE
azurerm_key_vault_access_policy doesnt recognize function app changes

### ISSUE THREAD

**Issue by taipignas** [hashicorp/terraform-provider-azurerm#19316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "function_app" {
  name                      = "function-app"
  resource_group_name       = azurerm_resource_group.resource_group.name
  location                  = azurerm_resource_group.resource_group.location
  service_plan_id           = azurerm_service_plan.service_plan.id
  virtual_network_subnet_id = azurerm_subnet.vnet_function_subnet.id

  storage_account_name       = azurerm_storage_account.storage_account.name
  storage_account_access_key = azurerm_storage_account.storage_account.primary_access_key

  app_settings = {
    SCM_DO_BUILD_DURING_DEPLOYMENT = false
  }

  site_config {
    application_insights_key = azurerm_application_insights.application_insights.instrumentation_key
    application_stack {
      dotnet_version              = "6.0"
      use_dotnet_isolated_runtime = true
    }
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {}
}

resource "azurerm_key_vault_access_policy" "function_access_policy" {
  key_vault_id = azurerm_key_vault.common_key_vault.id
  tenant_id    = azurerm_linux_function_app.function_app.identity.0.tenant_id
  object_id    = azurerm_linux_function_app.function_app.identity.0.principal_id

  key_permissions    = []
  secret_permissions = ["Get"]
}
```

### Debug Output/Panic Output

```shell
Error: Missing required argument
│
│   with azurerm_key_vault_access_policy.function_access_policy,
│   on resources.tf line 119, in resource "azurerm_key_vault_access_policy" "function_access_policy":
│  119:   tenant_id    = azurerm_linux_function_app.function_app.identity.0.tenant_id
│
│ The argument "tenant_id" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│
│   with azurerm_key_vault_access_policy.function_access_policy,
│   on resources.tf line 120, in resource "azurerm_key_vault_access_policy" "function_access_policy":
│  120:   object_id    = azurerm_linux_function_app.function_app.identity.0.principal_id
│
│ The argument "object_id" is required, but no definition was found.
```

### Expected Behaviour

function identity is added and after that azurerm_key_vault_access_policy is added

### Actual Behaviour

azurerm_key_vault_access_policy thinks that argument definition is missing when in fact it wasnt created yet.

### Steps to Reproduce

1. create function app without identity section
2. apply terraform
3. add identity section and add azurerm_key_vault_access_policy
4. try to apply terraform

**Comment by xiaxyi** [comment]
Thanks @taipignas for raising this issue. To better understand the issue, can you help me to clarify about the resource creation order?
1. creating the function app without enabling the system assigned identity.
2. add the system assigned identity for function app then creating the kv access policy?

**Comment by taipignas** [comment]
thanks for helping me out so quickly, @xiaxyi 

yes thats the correct order
and using data.azurerm_linux_function_app.test as a middle resource fixes the problem

**Comment by xiaxyi** [comment]
Thanks @taipignas for the update, glad to see it's working. 

I will take a look at the issue mentioned in the thread to see if we have any update there. To better track the progress, would you mind closing this one and let us share the update in that issue as there are some other resources are being affected. Thanks for your understanding.
