### ISSUE TITLE
Frontdoor rule not accepting cache_duration null value

### ISSUE THREAD

**Issue by sudeep1607** [hashicorp/terraform-provider-azurerm#19311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
+ resource "azurerm_cdn_frontdoor_rule" "frontdoor_rule" {
      + behavior_on_match           = "Continue"
      + cdn_frontdoor_rule_set_id   = "/subscriptions/..........."
      + cdn_frontdoor_rule_set_name = (known after apply)
      + id                          = (known after apply)
      + name                        = "ignoreString"
      + order                       = 0

      + actions {

          + route_configuration_override_action {
              + cache_behavior                = "HonorOrigin"
              + compression_enabled           = true
              + query_string_caching_behavior = "IgnoreQueryString"
            }
        }

      + conditions {

          + url_path_condition {
              + match_values     = [
                  + "data/",
                ]
              + negate_condition = false
              + operator         = "BeginsWith"
            }
          + url_path_condition {
              + match_values     = [
                  + ".html",
                ]
              + negate_condition = false
              + operator         = "EndsWith"
            }
        }
    }
```

### Debug Output/Panic Output

```shell
Error: creating Front Door Rule: (Rule Name "ignoreString" / Rule Set Name "cacheRequests" / Profile Name "xyzzy-profile" / Resource Group "xyzzy-rg"): cdn.RulesClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Cache duration must be null for honor origin behavior."
```

### Expected Behaviour

Should be able to create the rule when cache_duration value is set as null

### Actual Behaviour

Getting the mentioned error above

### Steps to Reproduce

1. Create a rule using auzrerm_cdn_frontdoor_rule with route_configuration_override_action configured with cache behaviour as HonorOrigin and cache duration as null
2. terraform plan
3. terraform apply

**Comment by WodansSon** [comment]
@sudeep1607, thank you for opening this issue, this appears to be a service issue where it interprets an empty string as an actual value being passed instead of ignoring it. So I am going to have to see if I can either hack the SDK, or figure out a way omit the value from being passed to the service if it is empty. 🚀
