### ISSUE TITLE
Support for "storage_account_identity" in Data Source for "azurerm_databricks_workspace"

### ISSUE THREAD

**Issue by imtarunsingh** [hashicorp/terraform-provider-azurerm#19329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am creating a module for "azurerm_databricks_workspace_customer_managed_key" using azurerm version 3.9.0. I am trying to use the existing module for "azurerm_databricks_workspace" to create this module. But the issue I am facing is that the data source for "azurerm_databricks_workspace" does not export "storage_account_identity" attribute due to which I am not able to create the "azurerm_key_vault_access_policy" for Databricks storage account.

Please see the following code:

resource "azurerm_key_vault_access_policy" "databricks" {
  depends_on = [azurerm_databricks_workspace.example]

  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = azurerm_databricks_workspace.example.storage_account_identity.0.tenant_id
  object_id    = azurerm_databricks_workspace.example.storage_account_identity.0.principal_id

  key_permissions = [
    "get",
    "unwrapKey",
    "wrapKey",
  ]
}

For tenant_id and object_id, I want to use the data source to fetch the tenant_id and object_id for existing databricks workspace's storage account.

### New or Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace_customer_managed_key

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_access_policy" "databricks" {
  depends_on = [azurerm_databricks_workspace.example]
  key_vault_id = azurerm_key_vault.example.id
  tenant_id    = data.azurerm_databricks_workspace.example.storage_account_identity.0.tenant_id
  object_id    = data.azurerm_databricks_workspace.example.storage_account_identity.0.principal_id

  key_permissions = [
    "get",
    "unwrapKey",
    "wrapKey",
  ]
}
```

**Comment by sinbai** [comment]
@imtarunsingh thanks for opening this issue. I have submitted [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/19336)to support `storage_account_identity` for `data.azurerm_databricks_workspace`. Could you follow it for more updates?

**Comment by imtarunsingh** [comment]
> 

Sure, I will follow it.
