### ISSUE TITLE
Fix max value on iops ValidateFunc

### ISSUE THREAD

**Issue by maronemoraes** [hashicorp/terraform-provider-azurerm#19324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.9.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```hcl
source                       = "../../../../modules/mysql-flexible"
  resource_group_name          = azurerm_resource_group.rg.name
  server_name                  = "mysql-order-prd-57"
  sku_name                     = "MO_Standard_E16ds_v4"
  server_version               = "5.7"
  administrator_login          = "adminlogin"
  administrator_password       = "*********"
  geo_redundant_backup_enabled = false
  #public_network_access_enabled = true
  storage_gb        = 16384
  iops              = 28000
  auto_grow_enabled = false
  zone_id           = "3"
  private_dns_id    = "*************"
  subnet_id         = "*************"
  tags = {
    suite       = "oms"
    product     = "order"
    env         = "prd"
    provisioner = "terraform"
  }
  depends_on = [
    azurerm_resource_group.rg
  ]
}
---
resource "azurerm_mysql_flexible_server" "server" {
  name                = var.server_name
  resource_group_name = data.azurerm_resource_group.server.name
  location            = var.location == null ? data.azurerm_resource_group.server.location : var.location

  sku_name                     = var.sku_name #GP_Standard_D2ds_v4"
  version                      = var.server_version
  zone                         = var.zone_id == "" ? null : var.zone_id
  administrator_login          = var.administrator_login
  administrator_password       = var.administrator_password
  delegated_subnet_id          = var.subnet_id
  private_dns_zone_id          = var.private_dns_id
  backup_retention_days        = var.backup_retention_days
  create_mode                  = var.create_mode
  geo_redundant_backup_enabled = var.geo_redundant_backup_enabled
  tags = var.tags
  storage {
    auto_grow_enabled = var.auto_grow_enabled
    iops              = var.iops
    size_gb           = var.storage_gb

  }
}
```

### Debug Output/Panic Output

```shell
│ Error: expected storage.0.iops to be in the range (360 - 20000), got 28000
│ 
│   with module.mysql-order-prd57.azurerm_mysql_flexible_server.server,
│   on ../../../../modules/mysql-flexible/main.tf line 35, in resource "azurerm_mysql_flexible_server" "server":
│   35:     iops              = var.iops
│
```

### Expected Behaviour

In the Azure documentation, the maximum value for IOPS should be 48000 and currently the value is set to 20000 on resource.

[https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mysql/mysql_flexible_server_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mysql/mysql_flexible_server_resource.go
)
> "iops": {
>             Type:         pluginsdk.TypeInt,
>             Optional:     true,
>             Computed:     true,
>             ValidateFunc: validation.IntBetween(360, 20000),

See: https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-service-tiers-storage

### Actual Behaviour

Setting the IOPS value to a value greater than 20000 is not allowed.

### Steps to Reproduce

terraform plan

### Important Factoids

N/A

**Comment by fxshelll** [comment]
I have the same problem IOPS  =(
