### ISSUE TITLE
Azure Batch pool creation missing taskSlotsPerNode

### ISSUE THREAD

**Issue by boris-ning-usds** [hashicorp/terraform-provider-azurerm#19330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Hi Azure,

I am creating a batch pool via [azurerm/azurerm_batch_pool](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool) and there's no configuration for me to change the **taskSlotPerNode** parameter which can be between 1-4.

Currently, without this parameter, it locks and defaults **taskSlotPerNode** to 1. Since this [configuration cannot be changed](https://learn.microsoft.com/en-us/azure/batch/batch-parallel-node-tasks#enable-parallel-task-execution) after the Batch pool has been created, it's necessary to delete and recreate the Batch pool to change that property.

### Terraform Version

1.2.8

### AzureRM Provider Version

3.30.0

### Affected Resource(s)/Data Source(s)

azurerm/azurerm_batch_pool

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "testaccbatch"
  location = "eastus"
}

resource "azurerm_storage_account" "example" {
  name                     = "testaccsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_batch_account" "example" {
  name                 = "testaccbatch"
  resource_group_name  = azurerm_resource_group.example.name
  location             = azurerm_resource_group.example.location
  pool_allocation_mode = "BatchService"
  storage_account_id   = azurerm_storage_account.example.id

  tags = {
    env = "test"
  }
}

resource "azurerm_batch_pool" "example" {
  name                = "testaccpool"
  resource_group_name = azurerm_resource_group.example.name
  account_name        = azurerm_batch_account.example.name
  display_name        = "Test Acc Pool Auto"
  vm_size             = "Standard_A1"
  node_agent_sku_id   = "batch.node.ubuntu 20.04"

  auto_scale {
    evaluation_interval = "PT15M"

    formula = <<EOF
      startingNumberOfVMs = 1;
      maxNumberofVMs = 25;
      pendingTaskSamplePercent = $PendingTasks.GetSamplePercent(180 * TimeInterval_Second);
      pendingTaskSamples = pendingTaskSamplePercent < 70 ? startingNumberOfVMs : avg($PendingTasks.GetSample(180 *   TimeInterval_Second));
      $TargetDedicatedNodes=min(maxNumberofVMs, pendingTaskSamples);
EOF

  }

  storage_image_reference {
    publisher = "microsoft-azure-batch"
    offer     = "ubuntu-server-container"
    sku       = "20-04-lts"
    version   = "latest"
  }

  container_configuration {
    type = "DockerCompatible"
    container_registries {
      registry_server = "docker.io"
      user_name       = "login"
      password        = "apassword"
    }
  }

  start_task {
    command_line       = "echo 'Hello World from $env'"
    task_retry_maximum = 1
    wait_for_success   = true

    common_environment_properties = {
      env = "TEST"
    }

    user_identity {
      auto_user {
        elevation_level = "NonAdmin"
        scope           = "Task"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Missing parameter to configure taskSlotPerNode properties; https://learn.microsoft.com/en-us/azure/batch/batch-parallel-node-tasks#enable-parallel-task-execution

Currently, the configuration forces the task slot to 1, when it can be 4.
```

### Expected Behaviour

Currently, the configuration forces the task slot per node to 1, when it can be 4.

### Actual Behaviour

Currently, the configuration forces the task slot per node to 1, when it can be 4 - and it cannot be changed after the Batch pool has been created.

### Steps to Reproduce

1. Run terraform to spin up a Batch account, and subsequently a batch pool.
2. There's no way to change the taskSlotPerNode parameter, so it's defaulted to 1. 
3. View the Batch pool properties to verify that it is 1.

### Important Factoids

No

**Comment by liuwuliuyun** [comment]
Hi @boris-ning-usds, thanks for the issue and we already have this property as  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool#max_tasks_per_node. You could try it out in test environment and send us the feedback.

**Comment by boris-ning-usds** [comment]
Got it, I just got a batch account with a batch pool functional - it's been an uphill battle.

Are there documentation on when I would ever delegate a subnet to a batch account?
It seems like I could just tell a batch pool to use a particular subnet instead.

**Comment by boris-ning-usds** [comment]
I also cannot find the [the node communication option](https://learn.microsoft.com/en-us/azure/batch/simplified-compute-node-communication) where node_communication_mode between **classic** and **simplified** should be available but it's not.

Default currently locks to **simplified** based on the documentation.
![image](https://user-images.githubusercontent.com/41026275/202585473-cfab173b-b7f8-4ba5-a13f-0d93a8562596.png)

**Comment by liuwuliuyun** [comment]
> Got it, I just got a batch account with a batch pool functional - it's been an uphill battle.
> 
> Are there documentation on when I would ever delegate a subnet to a batch account? It seems like I could just tell a batch pool to use a particular subnet instead.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool#subnet_id

**Comment by liuwuliuyun** [comment]
> I also cannot find the [the node communication option](https://learn.microsoft.com/en-us/azure/batch/simplified-compute-node-communication) where node_communication_mode should be either **classic** and **simplified** should be available but it's not.
> 
> Default currently locks to **simplified** based on the documentation. ![image](https://user-images.githubusercontent.com/41026275/202585473-cfab173b-b7f8-4ba5-a13f-0d93a8562596.png)

I am afrarid this property is not supported by now. but PR is welcome :).

**Comment by liuwuliuyun** [comment]
An alternative solution for using the latest property of azure is to use [azapi](https://registry.terraform.io/providers/azure/azapi/latest/docs) and you could refer to the [doc](https://learn.microsoft.com/en-us/azure/developer/terraform/overview-azapi-provider)

**Comment by boris-ning-usds** [comment]
Understood, thanks!

I'm closing this ticket since I saw that "classic" is being depreciated and it looks like the trend is heading towards "simplified" networking.
