### ISSUE TITLE
azurerm_databricks_access_connector has no object_id field and it cannot be used with azurerm_role_assignment

### ISSUE THREAD

**Issue by mattiazenidb** [hashicorp/terraform-provider-azurerm#19331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_access_connector

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
    databricks = {
      source = "databricks/databricks"
    }
  }
}

provider "azurerm" {
  subscription_id = local.subscription_id
  features {}
}

resource "azurerm_resource_group" "admin_resource_group" {
  name     = "rg"
  location = "West Europe"
}
resource "azurerm_databricks_access_connector" "metastore" {
  name                = "accessconnector"
  resource_group_name = azurerm_resource_group.admin_resource_group.name
  location            = azurerm_resource_group.admin_resource_group.location
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_storage_account" "admin_storage_account" {
  name                     = "storageaccount"
  resource_group_name      = azurerm_resource_group.admin_resource_group.name
  location                 = azurerm_resource_group.admin_resource_group.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
}

resource "azurerm_role_assignment" "this" {
  scope                = azurerm_storage_account.admin_storage_account.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_databricks_access_connector.metastore.object_id
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported attribute
│
│   on main.tf line 75, in resource "azurerm_role_assignment" "this":
│   75:   principal_id         = azurerm_databricks_access_connector.metastore.object_id
│
│ This object has no argument, nested block, or exported attribute named "object_id".
```

### Expected Behaviour

The expected behaviour is that azurerm_databricks_access_connector has a field object_id that can be used to assign permissions, e.g., to a storage account with azurerm_role_assignment.

**Comment by sinbai** [comment]
@mattiazenidb thank you for opening this issue. Could you try using `azurerm_databricks_access_connector.metastore.identity[0].principal_id` instead of 
 azurerm_databricks_access_connector.metastore.object_id` ? like this:

```
resource "azurerm_role_assignment" "this" {
  scope                = azurerm_storage_account.admin_storage_account.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_databricks_access_connector.metastore.identity[0].principal_id
}
```

**Comment by mattiazenidb** [comment]
Thanks, it works! Maybe we should document this.

**Comment by joshwright10** [comment]
I was trying to work this out yesterday, thanks for asking this question! I've opened a PR for the docs update.

**Comment by rcskosir** [comment]
Thank you @mattiazenidb, @sinbai and @joshwright10 for the collaboration. 
I am going to mark this issue as closed.
