### ISSUE TITLE
azurerm_orchestrated_virtual_machine_scale_set does not support computer_name_prefix argument

### ISSUE THREAD

**Issue by ben-east** [hashicorp/terraform-provider-azurerm#19364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
resource "azurerm_orchestrated_virtual_machine_scale_set" "test" {
  name                        = "vmss-name"
  computer_name_prefix        = "test"
  resource_group_name         = "my-resource-group"
  location                    = "West US 3"
}
```

### Debug Output/Panic Output

```shell
$ terraform validate
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 46, in resource "azurerm_orchestrated_virtual_machine_scale_set" "test":
│   46:   computer_name_prefix        = "test"
│ 
│ An argument named "computer_name_prefix" is not expected here.
```

### Expected Behaviour

`computer_name_prefix` should be supported as an argument, as suggested in the docs: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set#computer_name_prefix

### Actual Behaviour

Terraform validation failed saying the argument is unsupported

### Steps to Reproduce

- Define a minimal `azurerm_orchestrated_virtual_machine_scale_set`
- Set a `computer_name_prefix` argument aligning with the public docs
- Run `terraform validate` or `terraform plan`

### References

Public docs suggest this is a valid argument for the resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set#computer_name_prefix

**Comment by WodansSon** [comment]
@ben-east, thank you for opening this issue. It appears that this is a documentation issue which needs to be fixed. To use the `computer_name_prefix` field you must define it in the `os_profile` block for either the `linux_configuraton` or `windows_configuration` block. HTH. 🚀 

## Example usage of `computer_name_prefix`:

```hcl
  os_profile {
    linux_configuration {
      computer_name_prefix = "myPrefix"
      admin_username       = "myadmin"
      admin_password       = "Passwword1234"

      disable_password_authentication = false
    }
  }
```
