### ISSUE TITLE
Cannot create azurerm_app_service_source_control with service principal RBAC

### ISSUE THREAD

**Issue by vancodocton** [hashicorp/terraform-provider-azurerm#19367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_source_control

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources-2346-0"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example-2346-1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "B1"
}

resource "azurerm_linux_web_app" "example" {
  name                = "example-2346-2"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}
}

resource "azurerm_app_service_source_control" "example" {
  app_id   = azurerm_linux_web_app.example.id
  repo_url = "https://github.com/Azure-Samples/python-docs-hello-world"
  branch   = "master"
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/vancodocton/7e2a7ea7d1121bc32c022bc586744b77
```

### Expected Behaviour

`azurerm_app_service_source_control` should be created successfully

### Actual Behaviour

An exception throw:
```
Error: creating Source Control configuration for Web App: (Site Name "example-2346-2" / Resource Group "example-resources-2346-0"): web.AppsClient#UpdateSourceControl: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Cannot find User with name db76e690-3940-43f7-ba7c-977f6663be98." Details=[{"Message":"Cannot find User with name db76e690-3940-43f7-ba7c-977f6663be98."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"51004","Message":"Cannot find User with name db76e690-3940-43f7-ba7c-977f6663be98.","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["User","db76e690-3940-43f7-ba7c-977f6663be98"]}}]
│
│   with azurerm_app_service_source_control.example,
│   on main.tf line 32, in resource "azurerm_app_service_source_control" "example":
│   32: resource "azurerm_app_service_source_control" "example" {
│
│ creating Source Control configuration for Web App: (Site Name "example-2346-2" / Resource Group
│ "example-resources-2346-0"): web.AppsClient#UpdateSourceControl: Failure responding to request: StatusCode=404 --
│ Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Cannot find User with
│ name db76e690-3940-43f7-ba7c-977f6663be98." Details=[{"Message":"Cannot find User with name
│ db76e690-3940-43f7-ba7c-977f6663be98."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"51004","Message":"Cannot
│ find User with name db76e690-3940-43f7-ba7c-977f6663be98.","MessageTemplate":"Cannot find {0} with name
│ {1}.","Parameters":["User","db76e690-3940-43f7-ba7c-977f6663be98"]}}]
```

### Steps to Reproduce

Create a service principal RBAC with scope to a subscription:
```
az ad sp create-for-rbac --name "Contributor" --role contributor `
    --scopes "/subscriptions/e03039e3-9321-4445-bcd5-892e9b6c8bca" `
    --sdk-auth
```

Setup for `terraform` from the above result.
```
$env:ARM_SUBSCRIPTION_ID="***"
$env:ARM_CLIENT_ID="***"
$env:ARM_TENANT_ID="***"
$env:ARM_CLIENT_SECRET="***"
az login --service-principal -u $env:ARM_CLIENT_ID -p $env:ARM_CLIENT_SECRET --tenant $env:ARM_TENANT_ID
```

Execute plan
```
terraform init 
terraform plan --out create.tfplan
terraform apply "create.tfplan"
```

The error should throw.

**Comment by vancodocton** [comment]
Well, maybe it is a limit of RBAC, I tested with az CLI logged in by sp RBACand it doesn't work.
I will use my user account instead.

**Comment by xiaxyi** [comment]
Hi @vancodocton , Thanks for the update. May I know if there is any update that you can share with us? Are you able to get the expected result by using your user account or still not working due to service limitation?

**Comment by vancodocton** [comment]
Well, I created a separate project for creating azurerm_app_service_source_control. Swapping az login methods for the same project will cause unwanted changing of `data.azurerm_client_config.current.object_id`. 

Btw, I'm fine with this approach.

**Comment by erose96** [comment]
For anyone wondering, it also works if you assign the Contributor role directly for a management group scoped service principal

Not the first time I've had the Owner role be insufficient for an Azure operation, sort of inconvenient to troubleshoot when the error messages are misleading when the Owner role claims to give you full control over resources

**Comment by xiaxyi** [comment]
Thanks @vancodocton for the update, glad to see issue resolved. May I know if it's ok to close this issue or do you have any other follow up questions that I can help?

**Comment by vancodocton** [comment]
It's fine to close, @xiaxyi.

**Comment by rcskosir** [comment]
Thank you @vancodocton for opening this issue and @xiaxyi for assisting, I am going to mark this issue as closed.
