### ISSUE TITLE
Cosmos DB Account Creation - Issue with "identity_ids" parameter in "identity" block. 

### ISSUE THREAD

**Issue by ChadThomsen** [hashicorp/terraform-provider-azurerm#19361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

 "azurerm_cosmosdb_account"

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "db" {
  #name                = "tfex-cosmos-db-${random_integer.ri.result}"
  name                = "chads-mongo-db"
  location            = data.azurerm_resource_group.chads-rg.location
  resource_group_name = data.azurerm_resource_group.chads-rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"
  #Following lines added
  network_acl_bypass_for_azure_services = true
  mongo_server_version = 4.2
  #enable_free_tier = false
  #public_network_access_enabled = false
 
  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv3.4"

  }

  capabilities {
    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = "eastus"
    failover_priority = 1
  }

  geo_location {
    location          = "westus"
    failover_priority = 0
  }

#following blocks added
  backup {
    type = "Periodic"
    interval_in_minutes = 120
    retention_in_hours = 72
    storage_redundancy = "Local"
  }
  
  timeouts{
    create  = "60m"
    delete  = "60m"

  }
  
  identity {
    type = "UserAssigned"
    #identity_ids = d9b84fb8-4f2f-4130-8326-33047f3d4ca0
    identity_ids = [data.azurerm_user_assigned_identity.mongo_db.principal_id]
   
  }

   default_identity_type = "UserAssignedIdentity=d9b84fb8-4f2f-4130-8326-33047f3d4ca0"
   key_vault_key_id = "https://chads-keyvault.vault.azure.net/keys/cosmos-mongo-db/"  #<--Keyvault URI
}
```

### Debug Output/Panic Output

```shell
PS C:\Users\xxxxxx\Desktop\Admin\Learn-Terraform\Work Labs\Cosmos_DB> terraform plan -out plan.tfplan
random_integer.ri: Refreshing state... [id=42100]
data.azurerm_resource_group.chads-rg: Reading...
azurerm_resource_group.chads-rg: Refreshing state... [id=/subscriptions/8f7147fb-7424-4298-b18a-b85b1c817ad4/resourceGroups/chads-rg]
data.azurerm_resource_group.chads-rg: Read complete after 0s [id=/subscriptions/8f7147fb-7424-4298-b18a-b85b1c817ad4/resourceGroups/chads-rg]
data.azurerm_user_assigned_identity.mongo_db: Reading...
data.azurerm_user_assigned_identity.mongo_db: Read complete after 1s [id=/subscriptions/8f7147fb-7424-4298-b18a-b85b1c817ad4/resourceGroups/chads-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mongo_db]
╷
│ Error: parsing "d9b84fb8-4f2f-4130-8326-33047f3d4ca0": expected 8 segments within the Resource ID but got 1 for "d9b84fb8-4f2f-4130-8326-33047f3d4ca0"
│
│   with azurerm_cosmosdb_account.db,
│   on cosmos-mongo_account.tf line 92, in resource "azurerm_cosmosdb_account" "db":
│   92:     identity_ids = [ data.azurerm_user_assigned_identity.mongo_db.principal_id ]
│
╵
```

### Expected Behaviour

Terraform should add this account to the Azure Cosmos DB Identity ID fields. 

### Actual Behaviour

terraform apply crashes with the listed error.

### Steps to Reproduce

Plan and apply the code listed in this issue.

### Important Factoids

Running in Azure East US region.

**Comment by ChadThomsen** [comment]
Upgraded the Provider to "3.32.0" which is the latest, and that did not help.

**Comment by ChadThomsen** [comment]
But when I try to use the .id I get this error:

╷
│ Error: creating Database Account: (Name "chads-mongo-db" / Resource Group "chads-rg"): waiting for the CosmosDB Account "chads-mongo-db" (Resource Group "chads-rg") to finish creating/updating: Code="BadRequest" Message="Database account creation failed. Operation Id: 2555e898-fb00-405e-8c91-0917cc2b5259, Error : CustomerManagedKeyHelper-GetDefaultMsiProperties: global db account chads-mongo-db doesn't have UserAssigned identity which resourceId=d9b84fb8-4f2f-4130-8326-33047f3d4ca0.\r\nActivityId: 1e75791d-7e2d-459a-a770-4662a02c78db, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0"
│
│   with azurerm_cosmosdb_account.db,
│   on cosmos-mongo_account.tf line 27, in resource "azurerm_cosmosdb_account" "db":
│   27: resource "azurerm_cosmosdb_account" "db" {
│
╵

**Comment by tombuildsstuff** [comment]
@ChadThomsen in that case you'd also need to ensure the relevant Object/Principal ID is being used for the `default_identity_type` field, unfortunately the Azure API error isn't particularly descriptive there, but it's suggesting that the UUID being specified for `default_identity_type` isn't added as a User Assigned Identity for the resource, so it's likely the value being provided is incorrect?
