### ISSUE TITLE
azurerm_virtual_hub_connection : "Bypass Next Hop IP for workloads within this VNet"

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform-provider-azurerm#19372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_virtual_hub_connection does not support the checkbox  "Bypass Next Hop IP for workloads within this VNet"

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_hub_connection

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_hub_connection" "vwan" {
  provider                  = azurerm
  name                      = "xxx"
  remote_virtual_network_id = vnet.virtual_network_id
  virtual_hub_id            = vwan.virtual_hub_id
  internet_security_enabled = true

  routing {
    propagated_route_table {
      labels = ["none"]
      route_table_ids = [
        format("%s/hubRouteTables/noneRouteTable", vwan.virtual_hub_id)
      ]
    }
    bypass_next_hop_ip = true
  }
```

### References

https://learn.microsoft.com/en-us/azure/virtual-wan/how-to-virtual-hub-routing

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems this feature isn't in use for now since I tried to provision the vhub connection with/without this feature in Azure Portal but seems there is no difference between them after comparing the arm template. And I didn't find this new feature in azure rest api. So maybe this feature isn't ready for now.

**Comment by mlcooper** [comment]
Hi @neil-yechenwei I opened an issue with the Azure Rest API team and they said that this setting can be configure via API:

<html><body>
<p dir="auto">You can leverage this REST API:<br>
<a href="https://learn.microsoft.com/en-us/rest/api/virtualwan/hub-virtual-network-connections/create-or-update?tabs=HTTP" rel="nofollow">https://learn.microsoft.com/en-us/rest/api/virtualwan/hub-virtual-network-connections/create-or-update?tabs=HTTP</a></p>
<p dir="auto">You can use this parameter:</p>





VnetLocalRouteOverrideCriteria | Parameter determining whether NVA in spoke vnet is bypassed for traffic with destination in spoke vnet.
-- | --



</body>
</html>

**Comment by catriona-m** [comment]
Thanks for opening this @Poil. It looks like this property is currently available and can be enabled by setting `static_vnet_local_route_override_criteria = “Equals”`.  As such, I am going to close this now. Please feel free to re-open this if there is still an issue however. Thanks!
