### ISSUE TITLE
Support for Azure Cosmos for Postgres

### ISSUE THREAD

**Issue by alirezaachegini** [hashicorp/terraform-provider-azurerm#19375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Recently Microsoft added Postgres to supported databases in Azure Cosmos resources. I couldn't find the Terraform definition for this. Could you please implement this and tell us when we can expect that?

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_postgres_database" "example" {

}
```

**Comment by sinbai** [comment]
@alirezaachegini thanks for opening this issue. Terraform could not currently support it, as there doesn't seem to be an Azure API that Terraform could use [here](
https://github.com/Azure/azure-rest-api-specs/tree/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable). Could you please let us know once the Azure API is available if possible? At that time we will support it by priority.

**Comment by Hellevar** [comment]
Related issue - https://github.com/hashicorp/terraform-provider-azurerm/issues/5040
