### ISSUE TITLE
Support for multiple resource_id and resource_group values in azurerm_monitor_activity_log_alert resource.

### ISSUE THREAD

**Issue by Gheedit** [hashicorp/terraform-provider-azurerm#19373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

So currently, in the resource azurerm_monitor_activity_log_alert, for arguments "resource_id" and "resource_group" in the criteria{} block, datatype string is expected. Although, when you configure an alert in the Azure Portal, you can set multiple different resource groups or resources in the same parent scope (subscription). This makes it really tedious and very impractical to use, if you want to configure an alert as such, using terraform.

My suggestion is, either allow the arguments "resource_id" and "resource_group" to be used with datatype list or make the argument "scopes" usable as it is in the Azure Portal, where you can define absolute paths to all resources that should be monitored by the alert, also using datatype list.

Coming to the argument "scopes", you cannot define multiple scopes even though its given datatype is "list", as it cuts the Id at subscription and splits it up in resource group, resource type and child resource id. So defining more than one value in "scopes" is not necessary. This makes the datatype assigne to the argument effectively useless. As you can see in the JSON below, multiple scopes are possible.

Copy/Paste Snipped from generated JSON in Azure Portal:
```
"scopes": [
    "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx"
],
"condition": {
    "allOf": [
        {
            "field": "category",
            "equals": "ResourceHealth"
        },
        {
            "anyOf": [
                {
                    "field": "resourceType",
                    "equals": "Microsoft.Compute/virtualMachines"
                }
            ]
        },
        {
            "anyOf": [
                {
                    "field": "resourceGroup",
                    "equals": "example-rg1"
                },
                {
                    "field": "resourceGroup",
                    "equals": "example-rg2"
                }
            ]
        },
        {
            "anyOf": [
                {
                    "field": "resourceId",
                    "equals": "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/example-rg1/providers/Microsoft.Compute/virtualMachines/example-vm1"
                },
                {
                    "field": "resourceId",
                    "equals": "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/example-rg2/providers/Microsoft.Compute/virtualMachines/example-vm2"
                }
            ]
        }
    ]
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_activity_log_alert

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_activity_log_alert" "main" {
  name                = ""
  resource_group_name = ""
  scopes              = [""] 
  description         = ""

  criteria {
    resource_id    = [azurerm_virtual_machine.example-vm1.id, azurerm_virtual_machine.example-vm2.id]
    resource_group = [azurerm_resource_group.example-rg1.id, azurerm_resource_group.example-rg2.id]
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id
  }
}
```

**Comment by teowa** [comment]
Hi @Gheedit , thanks for submitting this issue!
Seems there is few doc about activity log alert multi-scope feature. I cannot choose more than one scope when create the activity log alert on Azure Portal.

By directly call the REST API, I can create activity log alert with more than one scopes, or condition with `anyOf` or `containsAny`, below is resource JSON from Azurer Portal:
![image](https://user-images.githubusercontent.com/104055472/203931412-683f9613-3851-4959-b744-5093046b595c.png)

Seems the three schemas are all about using two resource groups in single acitivity log alert:
```
        "scopes": [
            "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/wt-example-resources",
            "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/wt-resources"
        ],
```
```
                {
                    "anyOf": [
                        {
                            "field": "resourceGroup",
                            "equals": "wt-example-resources"
                        },
                        {
                            "field": "resourceGroup",
                            "equals": "wt-resources"
                        }
                    ]
                },
```
```
                {
                    "field": "resourceGroup",
                    "containsAny": [
                        "wt-example-resources",
                        "wt-resources"
                    ]
                }
```
Is there any difference between these 3 method? And is it a normal bussiness scenario to have multiple scopes for single activity log alert? If these questions can be clarified, it will help a lot to implement this in the Terraform provider. Thanks.

**Comment by Gheedit** [comment]
Hi @teowa, thanks for your feedback on this issue. 
Now, I compared the resource "azurerm_monitor_activity_log_alert" with its metric counterpart "azurerm_monitor_metric_alert". In "azurerm_monitor_metric_alert" you can define the argument "scopes" as a list of absolute resource IDs. This is what I imagine should be possible with "azurerm_monitor_activity_log_alert" as well. Therefore, I think the first one, from your example, should be the "correct" way. 
Regarding business scenario - let's say you have two VMs with essentialy the same purpose, but they are in different resource groups, this is where you'd need to define one alert for two scopes which are only different on resource group level.

**Comment by teowa** [comment]
Hi @Gheedit , as for the first method, I think the latest `azurerm_monitor_activity_log_alert` should support use a list of absolute resource IDs in [scopes](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_activity_log_alert#scopes).
below config should work:

```hcl
resource "azurerm_monitor_activity_log_alert" "main" {
  name                = "example-activitylogalert"
  resource_group_name = azurerm_resource_group.example.name
  scopes              = [azurerm_storage_account.to_monitor.id, azurerm_storage_account.to.id]
  description         = "This alert will monitor a specific storage account updates."

  criteria {
    operation_name = "Microsoft.Storage/storageAccounts/write"
    category       = "Recommendation"
  }

  action {
    action_group_id = azurerm_monitor_action_group.main.id

    webhook_properties = {
      from = "terraform"
    }
  }
}
```

**Comment by Gheedit** [comment]
Hi @teowa,
I tried using the argument "scopes" as a list. Though It did not work.
Variable definiton:
```
variable "deploymentScope" {
  description = "Resource ID of defined scope. Can be subscription, resource group, resource group set or resource."
  type        = list(string)
}
```

Error received:
```
│ Error: Incorrect attribute value type
│
│   on ..\..\modules\activity_log_alerts\resource_health\main.tf line 4, in resource "azurerm_monitor_activity_log_alert" "activitylog_resource_health_alert":
│    4:   scopes              = [var.deploymentScope]
│     ├────────────────
│     │ var.deploymentScope is a list of string, known only after apply
│
│ Inappropriate value for attribute "scopes": element 0: string required.
```

**Comment by Gheedit** [comment]
Hi @teowa,
Thanks for your input. I removed [] from scopes = var.deploymentScope and after that it worked. I was then able to define two resources from two different scopes. Therefore, I think this issue is resolved, since my original request was, to be able to define scopes as a list.
Cheers!
