### ISSUE TITLE
Attribute missing from azure monitor private link scope resource 

### ISSUE THREAD

**Issue by Uvindu96** [hashicorp/terraform-provider-azurerm#19370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.10

### AzureRM Provider Version

2.98.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_private_link_scope

### Terraform Configuration Files

```hcl
## source module
resource "azurerm_monitor_private_link_scope" "monitor_private_link_scope" {
  name                = join("-", ["ampls", var.project, var.workload, var.environment, var.location, var.padding]) 
  resource_group_name = var.resource_group_name
  tags                = var.default_tags
}

# Create Azure Monitor Private Link Scope resources
module "monitor-private-link-scope" {
  source              = ".....azurerm/Azure-Monitor-Private-Link-Scope"
  project             = var.project
  environment         = var.environment
  location            = var.location
  workload            = var.private_link_scope_workload_name
  padding             = var.padding
  resource_group_name = module.resource-group.resource_group_name
  default_tags        = local.default_tags
  depends_on = [
    module.resource-group
  ]
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

azurerm_monitor_private_link_scope should provide the user to select the AMPLS access modes. Access modes `Ingestion access mode` and `Query access mode` user should be able to set these values from TF module, but the required attributes were not provided. in the module https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_private_link_scope it only provides the AMPLS name and resource group only. Users should be able to changes these values via terraform.

### Actual Behaviour

in the `azurerm_monitor_private_link_scope` TF module AMPLS access mode configuration was not provided and it will initially set `Ingestion access mode` to private only and `Query access mode` to open, 

### Steps to Reproduce

1. create the TF module.
```
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_monitor_private_link_scope" "example" {
  name                = "example-ampls"
  resource_group_name = azurerm_resource_group.example.name
}
```
2. Run the terraform apply command.

**Comment by neilmca-inc** [comment]
Came to this recently and had to go a different route as I just wanted this out of the way - so chose the AZAPI provider to achieve this. I found I had to use the `depends_on` statements between each here, otherwise the Private Endpoint connection timed out but actually created the resource in Azure and then I was faced with importing it into the TF config - so deleted it all and put it back again like the code below. 

Hope it helps someone in the meantime

```
# Azure Monitor Private Link Scope for Applications Insights
#resource "azurerm_monitor_private_link_scope" "amplsai01" {
#  name                = "ampls-${local.azainame}"
#  resource_group_name = azurerm_resource_group.rg01.name
#}
resource "azapi_resource" "amplsai01" {
  type = "microsoft.insights/privateLinkScopes@2021-07-01-preview"
  name = "ampls-${local.azainame}"
  location = "global"
  parent_id = azurerm_resource_group.rg01.id
  body = jsonencode({
    properties = {
      accessModeSettings = {
        ingestionAccessMode = "PrivateOnly"
        queryAccessMode = "PrivateOnly"
      }
    }
  })
}
resource "azurerm_monitor_private_link_scoped_service" "amplssai01" {
  depends_on = [ azapi_resource.amplsai01 ]  
  name                = "amplss-${local.azainame}"
  resource_group_name = azurerm_resource_group.rg01.name
  #scope_name          = azurerm_monitor_private_link_scope.amplsai01.name
  scope_name          = azapi_resource.amplsai01.name  
  linked_resource_id  = azurerm_application_insights.appi01.id
}
resource "azurerm_private_endpoint" "pec-ai01" {
  depends_on = [ azurerm_monitor_private_link_scoped_service.amplssai01 ]
  name                = "pec-${local.azainame}"
  location            = azurerm_resource_group.rg01.location
  resource_group_name = azurerm_resource_group.rg01.name
  subnet_id           = azurerm_subnet.subnet-training.id

  private_service_connection {
    name                           = "psc-${local.azainame}"
    #private_connection_resource_id = azurerm_monitor_private_link_scope.amplsai01.id
    private_connection_resource_id = azapi_resource.amplsai01.id    
    subresource_names              = ["azuremonitor"]
    is_manual_connection           = false
  }
}
```

**Comment by MISO-mgriffin** [comment]
Any updates or roadmap on this being implemented in the AzureRM Provider?

**Comment by KiPIDesTAN** [comment]
I would really like to fix this item. However, it requires the hashcorp/pandora#3510 be merged. The fields referenced above require the latest API version for AMPLS in the hashicorp/go-azure-sdk.

As this is my first time making a request to get this API updated in the Pandora project, can someone confirm for me that I did this correctly and that the only hold-up is that it's the winter holiday season, when not many people are available to review?
