### ISSUE TITLE
azurerm_data_factory_linked_service_azure_file_storage userId should not be null or empty

### ISSUE THREAD

**Issue by guptaaayush8** [hashicorp/terraform-provider-azurerm#19409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_linked_service_azure_file_storage

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "name" {
  name = "myresourcegroup"
  location = "canadacentral"
}

resource "azurerm_storage_account" "my-storage-account" {
  name                     = "mystorageaccount"
  resource_group_name      = azurerm_resource_group.name.name
  location                 = "canadacentral"
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "my-file-share" {
  name                 = "myfileshare"
  storage_account_name = azurerm_storage_account.my-storage-account.name
  quota                = 5
}

resource "azurerm_data_factory" "my-data-factory" {
  name                = "mydatafactory"
  location            = "canadacentral"
  resource_group_name = azurerm_resource_group.name.name
}

resource "azurerm_data_factory_linked_service_azure_file_storage" "file-storage-linked-service" {
  name                     = "AzureFileStorage_LinkedService"
  data_factory_id          = azurerm_data_factory.my-data-factory.id
  connection_string        = azurerm_storage_account.my-storage-account.primary_connection_string
  file_share               = azurerm_storage_share.my-file-share.name
}
```

### Debug Output/Panic Output

```shell
The property 'userid' in the payload cannot be null or empty.
```

### Expected Behaviour

{
    "name": "AzureFileStorage_LinkedService",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "annotations": [],
        "type": "AzureFileStorage",
        "typeProperties": {
            "connectionString": "DefaultEndpointsProtocol=https;AccountName=xxx;EndpointSuffix=core.windows.net;",
            "fileShare": "myfileshare",
            "encryptedCredential": "xxx"
        }
    }
}

### Actual Behaviour

{
    "name": "AzureFileStorage_LinkedService",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "type": "AzureFileStorage",
        "typeProperties": {
            "host": "",
            "userId": "",
            "connectionString": {
                "type": "SecureString",
                "value": "**********"
            },
            "fileShare": "myfileshare"
        },
        "annotations": []
    }
}

### Steps to Reproduce

2. Test Connection on Linked Service

**Comment by ms-henglu** [comment]
Hi @guptaaayush8 ,

Thank you for taking time to report this issue!

It seems that I can create these resources by the configuration in my local. Would you please give it another try with the latest azurerm provider? And where do you see the following error?
```
The property 'userid' in the payload cannot be null or empty.
```

**Comment by guptaaayush8** [comment]
@ms-henglu - I am getting this error while doing a test connection from azure portal

**Comment by guptaaayush8** [comment]
> Hi @guptaaayush8 ,
> 
> Thank you for taking time to report this issue!
> 
> It seems that I can create these resources by the configuration in my local. Would you please give it another try with the latest azurerm provider? And where do you see the following error?
> ```
> The property 'userid' in the payload cannot be null or empty.
> ```

@ms-henglu - I am getting this error while doing a test connection from azure portal
