### ISSUE TITLE
Support for azurerm_recovery_services_vault Allow Site Recovery to manage Extension update

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#19407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Ability to associate an automation account to the ASR allowing the use of automatic extension updates.

### New or Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault 
azurerm_site_recovery_replicated_vm

### References

https://learn.microsoft.com/en-us/azure/site-recovery/azure-to-azure-autoupdate

**Comment by ziyeqf** [comment]
Hi @mpjtaylor, thanks for opening this issue. 

A PR (#19710) has been submitted to add this property. And the new property is in the `azurerm_site_recovery_protection_container_mapping` resource. You can subscribe the PR to get progress.

For any further questions, please leave comments.
