### ISSUE TITLE
Data Source: azurerm_api_management missing tenant_access information

### ISSUE THREAD

**Issue by schmallaria** [hashicorp/terraform-provider-azurerm#19406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2

### AzureRM Provider Version

3.32

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
data "azurerm_api_management" "apim" {
  name                = "swo-ip-apim-${var.environment}"
  resource_group_name = var.resource_group_name
}

resource "azurerm_key_vault_secret" "apim_management_key" {
  name         = "APIM-ManagementKey"
  value        = data.azurerm_api_management.apim.tenant_access[0].primary_key
  key_vault_id = var.keyvault_ressource_id
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Data source `azurerm_api_management` should export a `tenant_access` information block.

### Actual Behaviour

When accessing the data source `azurerm_api_management` the following error occurs: 

This object has no argument, nested block, or exported attribute named "tenant_access".

### References

The API Management Rest API has an valid endpoint to get those information:

https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/tenant-access/get?tabs=HTTP

**Comment by sinbai** [comment]
@schmallaria thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/19422)has been submitted to support `tenant_access ` for `data.azurerm_api_management`.

**Comment by schmallaria** [comment]
Great. Thanks alot. Very fast... :+1:
