### ISSUE TITLE
Upgrade Azure Management API to 2021-04-01

### ISSUE THREAD

**Issue by tschechniker** [hashicorp/terraform-provider-azurerm#19420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the Management API is used in Version 2020-06-01 which is outdated. Everytime i create a support request in Azure they point out to upgrade and i have an hard time explaining why i can't. 

Current latest API Version is 2021-04-01 see https://learn.microsoft.com/en-us/rest/api/resources/resources for details.

### New or Affected Resource(s)/Data Source(s)

azurerm_*

**Comment by aristosvo** [comment]
Hi @tschechniker! Thanks for filing this issue.

Can you explain in a bit more detail what are the specific issues you are facing? Personally I've had no problem with the resources thus far.

**Comment by tschechniker** [comment]
@aristosvo 

Everytime we create an issue for the Azure Support it advices us to upgrade to the latest API version first. That's why i created this ticket

**Comment by aristosvo** [comment]
@tschechniker Thanks for your reaction. So there are no underlying issues caused by it at the moment?

Usually upgrades like these will be done when new functionality is only available in the newer versions or older versions are deprecated. To manage expectations a bit, this might take a while.
