### ISSUE TITLE
Fail to apply AppInsight using a workspace in AureRM 3.33

### ISSUE THREAD

**Issue by Pumkko** [hashicorp/terraform-provider-azurerm#19443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.33

### Affected Resource(s)/Data Source(s)

azurerm_application_insights

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights" "kimAppInsight" {
  name                = "kim-${terraform.workspace}-ai"
  location            = var.SERVICE_PLAN_LOCATION
  resource_group_name = azurerm_resource_group.kimResourceGroup.name
  workspace_id        = var.ANALYTIC_WORKSPACE_ID
  application_type    = "web"
}
```

### Debug Output/Panic Output

```shell
parsing "/subscriptions/[SubscriptionId]/resourcegroups/monitoring-dev-rg/providers/microsoft.operationalinsights/workspaces/monitoring-dev-log": parsing segment "staticResourceGroups": expected the segment "resourcegroups" to be "resourceGroups"

with azurerm_application_insights.kimAppInsight,
 on appinsights.tf line 6, in resource "azurerm_application_insights" "kimAppInsight":
  workspace_id        = var.ANALYTIC_WORKSPACE_ID
```

### Expected Behaviour

The command `terraform apply` works well when using azurrm provider v3.32, the id given to workspace is correct i double checked it using azure CLI.

**Comment by ms-zhenhua** [comment]
Hi @Pumkko, seems there is [a change](https://github.com/hashicorp/terraform-provider-azurerm/pull/19325) in v3.33 and you could try to replace `resourcegroups` in `var.ANALYTIC_WORKSPACE_ID` with `resourceGroups` to resolve this issue.

**Comment by Pumkko** [comment]
> Hi @Pumkko, seems there is [a change](https://github.com/hashicorp/terraform-provider-azurerm/pull/19325) in v3.33 and you could try to replace `resourcegroups` in `var.ANALYTIC_WORKSPACE_ID` with `resourceGroups` to resolve this issue.

Thanks for your reply, i did try that but the problem persisted, right now we avoid the issue by using version 3.32
