### ISSUE TITLE
idle_timeout_in_minutes ignores current value. It always sets 0

### ISSUE THREAD

**Issue by AndriiPasternak1989** [hashicorp/terraform-provider-azurerm#19450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "standard"
    load_balancer_profile {
      idle_timeout_in_minutes = 120
    }
}
```

### Debug Output/Panic Output

```shell
~ network_profile {
            # (9 unchanged attributes hidden)

          ~ load_balancer_profile {
              ~ idle_timeout_in_minutes     = 0 -> 120
                # (6 unchanged attributes hidden)
            }
        }
```

### Expected Behaviour

Currently, idle_timeout_in_minutes is set to 30 minutes (terraform state file). Terraform should increase value up to 120 minutes, not to 0 as displayed in the "Debug Output/Panic Output"

### Actual Behaviour

Right now terraform plan shows that the value will be set to 0 instead of 120.

**Comment by ms-henglu** [comment]
Hi @AndriiPasternak1989 ,

Thank you for taking time to report this issue!

Would you please try to change the network plugin like the following?
`  network_plugin     = "kubenet"`

**Comment by AndriiPasternak1989** [comment]
@ms-henglu  It works the same way. No matter if it is kubenet or azure. Please keep in mind if we set "kubenet" it forces AKS to be re-created. 
![image](https://user-images.githubusercontent.com/113913788/204525983-f74c3598-315a-478a-83f6-ae0c96dae2dc.png)
![image](https://user-images.githubusercontent.com/113913788/204526029-981199c4-e050-41b1-a54b-e17860ac4bb3.png)

**Comment by AndriiPasternak1989** [comment]
@ms-henglu  I've just tested kubnet with existing AKS (another one that has been created manually using "kubenet" network and then imported into the terraform state). It worked well(idle_timeout_in_minutes  works fine in this scenario). So, it means we have the issue with "azure" network plugin only, right?

**Comment by AndriiPasternak1989** [comment]
@ms-henglu any updates?

**Comment by obobko** [comment]
same

**Comment by stephybun** [comment]
Closing since we haven't heard back. If this is still an issue feel free to reach out and we can reopen this. Thanks!
