### ISSUE TITLE
Can not create  azurerm_kusto_database with underscores (_) in the database name

### ISSUE THREAD

**Issue by BlackCoffeeAR** [hashicorp/terraform-provider-azurerm#19456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.14.0

### Affected Resource(s)/Data Source(s)

 azurerm_kusto_database

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.14.0"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
}

resource "azurerm_kusto_cluster" "example" {
  name                = "clusterexample"
  resource_group_name = "resource_group"
  location            = "location"
  auto_stop_enabled   = false

  sku {
    name     = "Dev(No SLA)_Standard_E2a_v4"
    capacity = 1
  }
}


# Azure Data Explorer Database
resource "azurerm_kusto_database" "adx_database_test" {
  name                = "adx_database_test"
  resource_group_name = "resource_group"
  location            = "location"
  cluster_name        = azurerm_kusto_cluster.example.name

  hot_cache_period   = "P7D"
  soft_delete_period = "P31D"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: "name" may only contain alphanumeric characters, whitespaces, dashes and dots: "adx_database_test"
│ 
│   with azurerm_kusto_database.adx_database_test,
│   on main.tf line 203, in resource "azurerm_kusto_database" "adx_database_test":
│  203:   name                = "adx_database_test"
│ 
╵
```

### Expected Behaviour

Database is created.

### Actual Behaviour

Database is not created.

Regarding to resource name rules (https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-name-rules) alphanumerics, hyphens, spaces, and periods are allowed for kusto database name. 
Regarding to entity names (https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/entity-names) letters, digits, underscores (_), spaces, dots (.), and dashes (-) are allowed.
Th REST Api (https://learn.microsoft.com/en-us/rest/api/azurerekusto/databases/create-or-update?tabs=HTTP) accepts also underscores.

**Comment by liuwuliuyun** [comment]
I have raised PR for this issue.

**Comment by BlackCoffeeAR** [comment]
@liuwuliuyun, thanks!
