### ISSUE TITLE
azurerm_automation_software_update_configuration needs tag's in Azure Query

### ISSUE THREAD

**Issue by marcvalk-git** [hashicorp/terraform-provider-azurerm#19454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

With azurerm_automation_software_update_configuration i need to provide tags in my azure_query field. If not provided (which is available through portal --> only a subscription scope), it will 

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automation_software_update_configuration" "definition_updates_config" {
  name                  = "updates"
  automation_account_id = var.automationaccount.id
  operating_system      = "Windows"
  duration              = "PT2H"
  windows {
    classifications_included = ["Definition"]
    reboot                   = "Never"
  }

  target {
    azure_query {
      scope = [ data.azurerm_subscription.current.id ]
    }
  }
  schedule {
    is_enabled  = true
    frequency   = "Hour"
    description = "Windows Definition Updates"
    interval    = 2
    time_zone   = "Etc/UTC"
    start_time  = "2022-11-28T13:00:00Z"
    expiry_time = "2025-11-28T13:00:00Z"
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Software Update Configuration: (Name "updates" / Automation Account Name "automation-001" / Resource Group "rg-automation"): automation.SoftwareUpdateConfigurationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\"Message\":\"The request is invalid.\",\"ModelState\":{\"softwareUpdateConfiguration.properties.updateConfiguration.targets.azureQueries[0].tagSettings.tags\":[\"The tags field is required.\"]}}"
│
│   with azurerm_automation_software_update_configuration.definition_updates_config,
│   on automation.tf line 46, in resource "azurerm_automation_software_update_configuration" "definition_updates_config":
│   46: resource "azurerm_automation_software_update_configuration" "definition_updates_config" {
│
│ creating Software Update Configuration: (Name "updates" / Automation Account Name "automation-001" /  
│ Resource Group "rg-automation"): automation.SoftwareUpdateConfigurationsClient#Create: Failure responding  
│ to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400
│ Code="BadRequest" Message="{\"Message\":\"The request is
│ invalid.\",\"ModelState\":{\"softwareUpdateConfiguration.properties.updateConfiguration.targets.azureQueries[0].tagSettings.tags\":[\"The
│ tags field is required.\"]}}"
```

### Expected Behaviour

I would expect that just having the scope to the subscription with nothing else, it would apply, as this can also be configured by the portal.

**Comment by wuxu92** [comment]
Hi @marcvalk-git thanks for your feedback! this looks like a server-side bug/incompatible. I'm creating a PR to work around this and also file an issue to track this.
