### ISSUE TITLE
Re-instate support for directly specifying service plan id in slot resources

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#19459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In AzureRM 2.x the slot resources azurerm_app_service_slot and azurerm_function_app_slot has the ability to directly specify the ASP id the slot ran in.

In AzureRM 3.x this option was removed from the new windows/linux equivalent slot resources.  This is a step backwards in functionality and affects the deployment workflow for some of our teams.

The ability to change the service plan on the slot is a supported pattern and documentation for it is linked below.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_function_app_slot, azurerm_windows_function_app_slot, azurerm_linux_web_app_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_function_app_slot" "example" {
  name                 = "example-slot"
  function_app_id      = azurerm_windows_function_app.example.id
  storage_account_name = azurerm_storage_account.example.name
  service_plan_id      = azurerm_service_plan.example.id
  site_config {}
}
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/function_app_slot

https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-slots#change-app-service-plan

**Comment by xiaxyi** [comment]
Hey @jackofallops , I see you've self-assigned this issue, are you going to submit a PR or any other plans?
