### ISSUE TITLE
azurerm_storage_object_replication cant create replication

### ISSUE THREAD

**Issue by tothger** [hashicorp/terraform-provider-azurerm#19457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.7

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_object_replication

### Terraform Configuration Files

```hcl
resource "azurerm_storage_object_replication" "replication" {
  count                          = var.replication ? 1 : 0
  source_storage_account_id      = azurerm_storage_account.storage_account.id
  destination_storage_account_id = var.destination_storage_account_id
  rules {
    source_container_name      = var.source_container_name
    destination_container_name = var.destination_container_name
  }
}

variable "replication" {
  type        = bool
  description = "Storage account replication ON/OFF"
  default     = true
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:
  # module.storage_account.azurerm_storage_object_replication.replication[0] will be created
  + resource "azurerm_storage_object_replication" "replication" {
      + destination_object_replication_id = (known after apply)
      + destination_storage_account_id    = "/subscriptions/[MASKED]/resourceGroups/storage-testing/providers/Microsoft.Storage/storageAccounts/gergelyteststorage"
      + id                                = (known after apply)
      + source_object_replication_id      = (known after apply)
      + source_storage_account_id         = "/subscriptions/[MASKED]/resourceGroups/storage-testing/providers/Microsoft.Storage/storageAccounts/gergelystorage"
      + rules {
          + copy_blobs_created_after     = "OnlyNewObjects"
          + destination_container_name   = "test-blob"
          + filter_out_blobs_with_prefix = []
          + name                         = (known after apply)
          + source_container_name        = "test-blob"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
module.storage_account.azurerm_storage_object_replication.replication[0]: Creating...
╷
│ Error: creating Storage Object Replication for destination storage account name "gergelyteststorage": objectreplicationpolicies.ObjectReplicationPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidObjectReplicationPolicy" Message="Object Replication Policy is not valid: sourceAccount and destinationAccount must be resource id."
│ 
│   with module.storage_account.azurerm_storage_object_replication.replication[0],
│   on .terraform/modules/storage_account/main.tf line 76, in resource "azurerm_storage_object_replication" "replication":
│   76: resource "azurerm_storage_object_replication" "replication" {
│ 
╵
time=2022-11-28T14:32:52Z level=error msg=1 error occurred:
	* exit status 1
```

### Expected Behaviour

Create the replication object

### Actual Behaviour

Can not create a replication. Fail with the error message what is no valid due the inputs are AzureId-s

**Comment by harshavmb** [comment]
I couldn't replicate this issue. My guess is that, one of the `source_storage_account_id` & `destination_storage_account_id` isn't the ARM resource id. 

By any chance you are using `azurerm_resources` data source to fetch the storage accounts? If that's the case, you might see some eventual consistency bothering every now & then.

**Comment by tothger** [comment]
Hello @harshavmb ,
You can see form the plan. They are ARM resource IDs.
`source_storage_account_id `  created by the block in the same file.

resource "azurerm_storage_account" "storage_account" {
  name                = var.name
  resource_group_name = var.resource_group_name

  location                         = var.resource_group_location
  account_tier                     = var.account_tier
  account_replication_type         = "GRS"
  cross_tenant_replication_enabled = false
  allow_nested_items_to_be_public  = false
  access_tier                      = var.access_tier
  shared_access_key_enabled        = true
  infrastructure_encryption_enabled = true
  min_tls_version                   = "TLS1_2"

  blob_properties {
    versioning_enabled = true
    change_feed_enabled = true
    change_feed_retention_in_days = 5

    delete_retention_policy {
      days = 3
    }

 
  tags = {
    "cost center" = var.cost_center
  }
}

**Comment by magodo** [comment]
This looks like some Azure bug, where the `sourceAccount` and `destinationAccount` should be storage account name as is defined in [API](https://github.com/Azure/azure-rest-api-specs/blob/8bcf420c12d61a1639dd470d511e6210869f44b6/specification/storage/resource-manager/Microsoft.Storage/stable/2022-05-01/examples/StorageAccountCreateObjectReplicationPolicyOnDestination.json#L35-L37), but somehow it requires it to be an Azure resource ID.

I've locally made a test for creating the `azurerm_storage_object_replication` and it works fine for me, the request is as below:

```
{
  "properties": {
    "destinationAccount": "stracctdst0n41x",
    "rules": [
      {
        "destinationContainer": "strcdst0n41x",
        "filters": {
          "minCreationTime": "",
          "prefixMatch": []
        },
        "sourceContainer": "strcsrc0n41x"
      }
    ],
    "sourceAccount": "stracctsrc0n41x"
  }
}
```


@tothger Would you please have a retry?

**Comment by tothger** [comment]
```
I tried to use the storage account name
│ Error: parsing Azure ID: parse "gergelystorage": invalid URI for request
│ 
│   with module.storage_account.azurerm_storage_object_replication.replication[0],
│   on .terraform/modules/storage_account/main.tf line 78, in resource "azurerm_storage_object_replication" "replication":
│   78:   source_storage_account_id      = azurerm_storage_account.storage_account.name
│ 
╵
╷
│ Error: parsing Azure ID: parse "gergelyteststorage": invalid URI for request
│ 
│   with module.storage_account.azurerm_storage_object_replication.replication[0],
│   on .terraform/modules/storage_account/main.tf line 79, in resource "azurerm_storage_object_replication" "replication":
│   79:   destination_storage_account_id = var.destination_storage_account_id
│ 
╵
```

this is in the module
```
resource "azurerm_storage_object_replication" "replication" {
  count                          = var.replication ? 1 : 0
  source_storage_account_id      = azurerm_storage_account.storage_account.name
  destination_storage_account_id = var.destination_storage_account_id
  rules {
    source_container_name      = var.source_container_name
    destination_container_name = var.destination_container_name
  }
}
```

**Comment by magodo** [comment]
I mean your previous config was right, bu the API raised an incorrect error.

**Comment by tothger** [comment]
@magodo I'm targeting to EU West

**Comment by magodo** [comment]
@tothger You might want to reach to Azure support for this unexpected behavior?

**Comment by aslatter** [comment]
Microsoft has updated their API documentation - it is now documented behavior that if "allowCrossTenantReplication" is set to false, the "sourceAccount" and "destAccount" properties of an object-replication-policy must be resource-ids, not account names - I think this issue should no longer be flagged as an "upstream issue", as it looks like it is now intended behavior.

See: https://learn.microsoft.com/en-us/azure/storage/blobs/object-replication-overview#specify-full-resource-ids-for-the-source-and-destination-accounts

>>>
The policy definition file previously required only the account name, instead of the full resource ID for the storage account. With the introduction of the AllowCrossTenantReplication security property in version 2021-02-01 of the Azure Storage resource provider REST API, you must now provide the full resource ID for any object replication policies that are created when cross-tenant replication is disallowed for a storage account that participates in the replication policy. Azure Storage uses the full resource ID to verify whether the source and destination accounts reside within the same tenant.
>>>

The ARM API-endpoint docs have also been updated: https://learn.microsoft.com/en-us/rest/api/storagerp/object-replication-policies/get?tabs=HTTP#objectreplicationpolicy

* *properties.destinationAccount* - *Required. Destination account name. It should be full resource id if allowCrossTenantReplication set to false.*
* *properties.sourceAccount* - *Required. Source account name. It should be full resource id if allowCrossTenantReplication set to false.*
