### ISSUE TITLE
Support for data.azurerm_key_vault_certificates

### ISSUE THREAD

**Issue by StefanSchoof** [hashicorp/terraform-provider-azurerm#19451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have where I want to assign all certificates of a key vault to Application Gateway. in this situation a data source that lists all key vault certificates would be useful. So very similar to `data.azurerm_key_vault_secrets`, but for certificates.

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificates

### Potential Terraform Configuration

```hcl
data "azurerm_key_vault_certificates" "example" {
  key_vault_id    = data.azurerm_key_vault.existing.id
  include_pending = true
}
```

### References

https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/get-certificates/get-certificates?tabs=HTTP

**Comment by jochenrichter** [comment]
it already [exists](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_certificate)
