### ISSUE TITLE
Support for Azure Digital Twins Time Series Database Connections

### ISSUE THREAD

**Issue by rquackenbush** [hashicorp/terraform-provider-azurerm#19463]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to support creating time series database connections for digital twins with terraform.

This can be accomplished with the `az dt data-history connection create` command line but is sub optimal.

### New or Affected Resource(s)/Data Source(s)

azurerm_digital_twins_tsdbconnection

### Potential Terraform Configuration

```hcl
resource "azurerm_digital_twins_tsdbconnection" "example" {
  name "example"
  digital_twins_id      = azurerm_digital_twins_instance.example.id
  resource_group_name   = azurerm_resource_group.example.name
  connection_type              = "AzureDataExplorer"
  adx_table_name               = "DataHistory"
  adx_resource_group_name      = azurerm_kusto_cluster.adx_cluster.resource_group
  adx_cluster_id               = azurerm_kusto_cluster.adx_cluster.id
  adx_subscription_id          = "23456" 
  eventhub_name                = azurerm_eventhub.eh.name
  eventhub_namespace_id        = azurerm_eventhub_namespace.ehns.id
  eventhub_consumer_group_name = "example"
  eventhub_resource_group_name = "my_resource_group"
  eventhub_subscription_id     = "12345"
}
```

### References

Command line reference:
- https://learn.microsoft.com/en-us/cli/azure/dt/data-history/connection/create?view=azure-cli-latest

**Comment by myc2h6o** [comment]
Hi @rquackenbush thanks for opening the issue! I've opened #19576 to add the support for this.
