### ISSUE TITLE
azurerm_linux_web_app claims CORS changed, when no change happened, keeps updating resource ([] -> null, false -> null)

### ISSUE THREAD

**Issue by derSchtefan** [hashicorp/terraform-provider-azurerm#19473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "web_app" {
  name                = var.name
  resource_group_name = var.common_app_config.resource_group_name
  location            = var.common_app_config.location
  service_plan_id     = var.common_app_config.linux_service_plan_id

  https_only = true
  site_config {
    always_on         = true
    health_check_path = "/"
    http2_enabled     = true
    api_definition_url = local.swagger_url
  }
  
  identity {
    type = "SystemAssigned"
  }

  app_settings = { x = 1, y = 2 }

  tags = var.common_app_config.tags
  lifecycle { ignore_changes = [
    tags,
    app_settings["DOCKER_CUSTOM_IMAGE_NAME"],
    app_settings["x"]
  ] }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # module.linux_web_apps["xxx-api"].azurerm_linux_web_app.web_app will be updated in-place
  ~ resource "azurerm_linux_web_app" "web_app" {
        id                                 = "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Web/sites/xxx-api"
        name                               = "xxx-api"
        tags                               = {
            "xxx" = "xxx"
        }
        # (21 unchanged attributes hidden)

      ~ site_config {
            # (25 unchanged attributes hidden)

          - cors {
              - allowed_origins     = [] -> null
              - support_credentials = false -> null
            }

            # (1 unchanged block hidden)
        }

        # (3 unchanged blocks hidden)
    }
```

### Expected Behaviour

```
   - cors {
              - allowed_origins     = [] -> null
              - support_credentials = false -> null
            }
```

This should not be detected as a change, but at least after applying it, it should be never detected as a change afterwards

### Actual Behaviour

Even after applying, a plan will show this as a change that needs to be executed and will execute it again.

### Steps to Reproduce

plan and apply, then plan again.

We are not certain why THIS resource in particular keeps being detected as changed, because we have 35 identical other resources with empty CORS created with the same resource block that are NOT detected as changed. The resource (like most others) was originally imported into terraform with terraform import.

In this case a [] should not be forced to null and a false (being the default) should neither be forced to null, resp. should not be detected as a changed that needs an action

**Comment by xiaxyi** [comment]
Thanks @derSchtefan for raising this issue, may I know if there was a config change or not? Specifically, changing the cors setting in site_config from:
```
site_config {
          cors {
              allowed_origins     = []
              support_credentials = false
            }
        }
```

to
```
site_config {}
```
?

**Comment by xiaxyi** [comment]
@derSchtefan , For web app, if there is no cors setting specified in TF config, the api will return:
```
 "cors": null,
```
and TF won't set a cors setting due to the null value.

The diff you are getting somehow suggests that there was a cors setting either made from TF or outside anywhere else (maybe the portal... ), Can you help me to confirm?

Thanks!

**Comment by derSchtefan** [comment]
Continuing in #19323, i think i have figured out how this happens. Writing it there.
