### ISSUE TITLE
Documentation for addon_profile

### ISSUE THREAD

**Issue by gwynforthewyn** [hashicorp/terraform-provider-azurerm#19478]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In [the terraform-azurm-kub](https://github.com/Azure-Terraform/terraform-azurerm-kubernetes/blob/99935422a30971e3b385a3a9de2d585c59553a06/main.tf) you can see that there's a pretty powerful addon_profile block that seems to allow for provisioning arbitrary plugins at cluster-creation time.

When I check https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster, though, this block is undocumented. It would be excellent to have this block's usage documented.

A compelling reasons to have this is that the security policy /providers/Microsoft.Authorization/policyDefinitions/0a15ec92-a229-4763-bb14-0ea34a568f8d recommends installing plugins as the _first_ remediation step for AKS clusters to come into compliance with recommended security policy, but it's unclear currently what this block accepts. 

### New or Affected Resource(s)/Data Source(s)

azurerm_aks

**Comment by ms-henglu** [comment]
Hi @gwynforthewyn ,

Thank you for taking time to report this issue!

In the terraform-azurm-kub repo, it uses an older version of azurerm provider, and the `addon_profile` is documented in that version's document: https://registry.terraform.io/providers/hashicorp/azurerm/2.57.0/docs/resources/kubernetes_cluster#addon_profile

But in the latest azurerm provider, these addon properties are moved to the top-level:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#aci_connector_linux
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#azure_policy_enabled
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#http_application_routing_enabled
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#http_application_routing_zone_name
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#oms_agent
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#ingress_application_gateway
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#open_service_mesh_enabled
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#key_vault_secrets_provider

**Comment by stephybun** [comment]
Thanks for raising this issue @gwynforthewyn.

As pointed out above the AKS add-ons can be found in the top level of the schema from **v2.97.0** of the provider onwards.

Since this is neither a feature request nor a bug I'm going to close this issue If you have any further questions regarding usage I'd direct you towards the [Community Discuss forum](https://discuss.hashicorp.com/).

Thanks!

**Comment by gwynforthewyn** [comment]
Thanks, @stephybun ! I'd missed @ms-henglu 's  response, so this message was super useful!
