### ISSUE TITLE
azurerm_eventgrid_topic - several arguments in "input_mapping_fields" object have no effect

### ISSUE THREAD

**Issue by kbargobdo** [hashicorp/terraform-provider-azurerm#19490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_eventgrid_topic

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_topic" "eventgrid_topic" {
  name                          = "test-egt"
  resource_group_name           = "test-rg"
  location                      = "northcentralus"
  input_schema                  = "CustomEventSchema"
  local_auth_enabled            = true
  public_network_access_enabled = true

  identity {
      type = "SystemAssigned"
  }

  input_mapping_fields {
      data_version = "data"
      event_time   = "time"
      event_type   = "event"
      id           = "id"
      subject      = "subject"
      topic        = "topic"
  }

  input_mapping_default_values {
      data_version = "testdata"
      event_type   = "testtype"
      subject      = "testsubject"
  }

  lifecycle {
    ignore_changes = [
      # Ignore changes to tags, e.g. because a management agent
      # updates these based on some ruleset managed elsewhere.
      tags
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + resource "azurerm_eventgrid_topic" "eventgrid_topic" {
      + endpoint                      = (known after apply)
      + id                            = (known after apply)
      + input_schema                  = "CustomEventSchema"
      + local_auth_enabled            = true
      + location                      = "northcentralus"
      + name                          = "test-egt"
      + primary_access_key            = (sensitive value)
      + public_network_access_enabled = true
      + resource_group_name           = "test-rg"
      + secondary_access_key          = (sensitive value)

      + identity {
          + principal_id = (known after apply)
          + tenant_id    = (known after apply)
          + type         = "SystemAssigned"
        }

      + input_mapping_default_values {
          + data_version = "testdata"
          + event_type   = "testtype"
          + subject      = "testsubject"
        }

      + input_mapping_fields {
          + data_version = "data"
          + event_time   = "time"
          + event_type   = "event"
          + id           = "id"
          + subject      = "subject"
          + topic        = "topic"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
azurerm_eventgrid_topic.eventgrid_topic: Creating...
azurerm_eventgrid_topic.eventgrid_topic: Still creating... [10s elapsed]
azurerm_eventgrid_topic.eventgrid_topic: Creation complete after 12s [id=/subscriptions/*******/resourceGroups/test-rg/providers/Microsoft.EventGrid/topics/test-egt]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

### Expected Behaviour

The Azure Event Grid Topic should be deployed and both the "input_mapping_fields" and "input_mapping_default_values" objects should be set to the values defined in the resource deployment. See below:

InputMappingField        : {[id, id], [topic, topic], [eventtime, time], **[eventtype, event], [subject, subject], [dataversion, data]**}
InputMappingDefaultValue : {[eventtype, testtype], [subject, testsubject], [dataversion, testdata]}

### Actual Behaviour

The Azure Event Grid Topic resource deploys, but the "event_type", "subject", and "data_version" values for "input_mapping_fields" are missing and not set. See below:

Using Az PowersShell cmdlet to pull the fields and default values from Azure.

InputMappingField        : {[id, id], [topic, topic], [eventtime, time]}
InputMappingDefaultValue : {[eventtype, testtype], [subject, testsubject], [dataversion, testdata]}

**Comment by sinbai** [comment]
@kbargobdo thanks for raising this issue here. I have submitted [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/19494) to fix it. Could you keep track of it for more updates?
