### ISSUE TITLE
azurerm_key_vault_certificate soft purge is Forbidden, purge_soft_delete_on_destroy does not work

### ISSUE THREAD

**Issue by Mykp3** [hashicorp/terraform-provider-azurerm#19502]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.16.0 - 3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificate

### Terraform Configuration Files

```hcl
# secret.tf

resource "azurerm_key_vault_certificate" "key_vault_certificate" {

  name         = "agwcertssssss"
  key_vault_id = "/subscriptions/**/kv-vault"

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }

    x509_certificate_properties {
      # Server Authentication = 1.3.6.1.5.5.7.3.1
      # Client Authentication = 1.3.6.1.5.5.7.3.2
      extended_key_usage = ["1.3.6.1.5.5.7.3.1"]

      key_usage = [
        "cRLSign",
        "dataEncipherment",
        "digitalSignature",
        "keyAgreement",
        "keyCertSign",
        "keyEncipherment",
      ]

      subject_alternative_names {
        dns_names = [
          "*.blah.com",
          "*.test.blah.com"
        ]
      }

      subject            = "CN=rblah"
      validity_in_months = 1
    }
  }

  lifecycle {
    create_before_destroy = true
    ignore_changes        = all
  }

}
```

# versions.tf
```
terraform {
  required_version = "1.3.4"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.16.0"
    }
    external = {
      source  = "hashicorp/external"
      version = "~> 2.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "3.4.0"
    }
  }
}
```

# provider.tf
```
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
    key_vault {
      purge_soft_delete_on_destroy    = false
    }
  }
}
```
```


### Debug Output/Panic Output

```shell
azurerm_key_vault_certificate.key_vault_certificate: Still destroying... [id=https://sssss/e9c58d82efdc48ecc, 10s elapsed]
╷
│ Error: purging of Certificate "agwcertssssss" (Key Vault "https://kv-vault.vault.azure.net/") : keyvault.BaseClient#PurgeDeletedCertificate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation \"purge\" is not allowed because purge protection is enabled for this vault. Key Vault service will automatically purge it after the retention period has passed.\r\nVault: kv-vault;location=northeurope"
```

### Expected Behaviour

Certificate being deleted without Terraform error

### Actual Behaviour

Terraform errored, pipeline failed, 
Further destroy attempts saying certificate is not exist and fails

### Steps to Reproduce

`terraform apply`

**Comment by teowa** [comment]
Hi @Mykp3 , thanks for submitting this issue!
The error is because the key vault has the purge protection enabled, and the provider is trying to purge the certificate. There is a feature toggle [`purge_soft_deleted_certificates_on_destroy`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/features-block#purge_soft_deleted_certificates_on_destroy), which controls whether the provider is to purge the certificate. You can disable this like below in the provider block:
```hcl
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
    key_vault {
      purge_soft_delete_on_destroy               = false
      purge_soft_deleted_certificates_on_destroy = false
    }
  }
}
```

**Comment by Mykp3** [comment]
Hey, thanks, it worked, any insight on when the added instruction was added to terraform docs? 

`purge_soft_deleted_certificates_on_destroy = false`
