### ISSUE TITLE
GP_Standard_D2ads_v5 for Azure MySQL Flexible server is not a valid sku name

### ISSUE THREAD

**Issue by thomeu** [hashicorp/terraform-provider-azurerm#19508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Debug Output/Panic Output**

```
│ Error: "sku_name" is not a valid sku name, got GP_Standard_D2ads_v5
│ 
│   with azurerm_mysql_flexible_server.mysql_flexible_server,
│   on mysql_flexible_server.tf line 9, in resource "azurerm_mysql_flexible_server" "mysql_flexible_server":
│    9:   sku_name                     = var.MYSQL_SERVER_SKU
```

**Expected Behaviour**

Change Compute size to General Purpose Standard_D2ads_v5

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server sku_name

### References

https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-service-tiers-storage#service-tiers-size-and-server-types
https://azure.microsoft.com/en-us/updates/general-availability-azure-database-for-mysql-flexible-server-with-amd-compute/

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Please try latest azurerm provider since it has been supported it.

**Comment by thomeu** [comment]
@neil-yechenwei Tried again with azurerm provider (3.36.0) and resource created. Thanks

**Comment by rcskosir** [comment]
Thank you @thomeu for raising issue. Based on your last comment it looks like the provider version 3.36.0 resolved this issue, so I am going to mark this issue as closed.
