### ISSUE TITLE
Azure Service Bus resource namespace change

### ISSUE THREAD

**Issue by andrewiankidd** [hashicorp/terraform-provider-azurerm#19501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.0

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace

### Terraform Configuration Files

```hcl
locals {
  base_name = "eu1-myapp"
}

resource "azurerm_resource_group" "myapp" {
  name     = "${local.base_name}-rg"
  location = var.PRIMARY_LOCATION
}

resource "azurerm_servicebus_namespace" "myapp" {
  name                = "${local.base_name}-sbn"
  location            = azurerm_resource_group.myapp.location
  resource_group_name = azurerm_resource_group.myapp.name
  sku                 = "Standard"
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/xxxxxxxx-yyyy-zzzz-aaaa-bbbbbbbbbbbb/resourceGroups/eu1-myapp-rg/providers/microsoft.servicebus/namespaces/eu1-myapp-sbn": parsing segment "staticMicrosoftServiceBus": expected the segment "microsoft.servicebus" to be "Microsoft.ServiceBus"
```

### Expected Behaviour

This worked as expected on previous versions, service bus is created, imported or checked without error.

### Actual Behaviour

Error is thrown, state file (Azure Blob) has to be manually manipulated in order to unblock and continue

### References

I have seen similar issues reported for other resource types

- #18210
- #18865

**Comment by xiaxyi** [comment]
Thanks @andrewiankidd for raising this issue, can you let me know the version of the state file? for example:
![image](https://user-images.githubusercontent.com/92154856/207248632-1e0d4ee3-2263-418a-a528-63eec7ce658e.png)

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to provide an update here then we'll be happy to take another look.

Thanks!
