### ISSUE TITLE
Support for custom logs options in azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by ssrahul96** [hashicorp/terraform-provider-azurerm#19503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need support for custom log options in Node Pools

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
    container_log_max_files = 5
    container_log_max_size_mb = 100
  }
```
```


### References

https://github.com/Azure/AKS/issues/1062

**Comment by ms-henglu** [comment]
Hi @ssrahul96 ,

Thank you for taking time to report this issue!

This feature has been supported in the latest azurerm provider, please check https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#container_log_max_line and https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#container_log_max_size_mb

**Comment by ssrahul96** [comment]
@ms-henglu , thanks for the update, ll take a look
