### ISSUE TITLE
azurerm_monitor_diagnostic_setting for logic app already exist

### ISSUE THREAD

**Issue by tomabg** [hashicorp/terraform-provider-azurerm#19500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5 

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "getconfigv2LogAnalytics" {
  name               = "getconfigv2LogAnalytics"
  target_resource_id = azurerm_logic_app_workflow.getconfigv2.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.LoganalyticsARXR.id

  log {
    category = "WorkflowRuntime"
    enabled  = true


    retention_policy {
      days    = 0
      enabled = false
    }
  }
    metric {
    category = "AllMetrics"
    enabled  = false

    retention_policy {
      days    = 0
      enabled = false
    }
  }
}
```

### Debug Output/Panic Output

```shell
2022-11-30T11:15:17.0240979Z [31m╵[0m[0m
2022-11-30T11:15:17.0625405Z ##[error]Terraform command 'apply' failed with exit code '1'.
2022-11-30T11:15:17.0832360Z ##[error][31m╷[0m[0m
[31m│[0m [0m[1m[31mError: [0m[0m[1mA resource with the ID "/subscriptions/XXX/resourcegroups/azdevops-tf-ref-rg/providers/microsoft.logic/workflows/getdevicesfromintune/providers/microsoft.insights/diagnosticSettings/getdevicesfromintuneLogAnalytics" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.[0m
[31m│[0m [0m
[31m│[0m [0m[0m  with azurerm_monitor_diagnostic_setting.getdevicesfromintuneLogAnalytics,
[31m│[0m [0m  on monitoring.tf line 170, in resource "azurerm_monitor_diagnostic_setting" "getdevicesfromintuneLogAnalytics":
[31m│[0m [0m 170: resource "azurerm_monitor_diagnostic_setting" "getdevicesfromintuneLogAnalytics" [4m{[0m[0m
[31m│[0m [0m
[31m╵[0m[0m
```

### Expected Behaviour

wenn we do terraform apply/destroy/apply/destroy..

We see that sporatically the diag settings for logic apps are not destroyed correctly
betwen this atempts we always did manuel cleanup then apply again-->good
Then destroy and apply all again-->again some azurerm_monitor_diagnostic_setting only forlogic apps were already existing
We have many logic apps and this apears always for different logic apps.
We see this issue in about 50 % of the azurerm_monitor_diagnostic_setting for logic apps

for any questions please come back

### Actual Behaviour

destroy not always deletes all azurerm_monitor_diagnostic_setting even they are managed by terraform

**Comment by ziyeqf** [comment]
Hi @tomabg, sorry for my late reply.

To diagnosis this issue could you please provide some log of `not destroy correctly`? You can use this command to save log to `tf-debug.log` file: `TF_LOG_PATH="./tf-debug.log" TF_LOG=DEBUG terraform destroy`.

Thank you.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant logs. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out additional information regarding the debug logs so that we can try to reproduce the problem.
