### ISSUE TITLE
azurerm_sentinel_data_connector_azure_security_center comes up with "ResourceGroupNotFound" when trying to enable azure_security_center connector on different subscription

### ISSUE THREAD

**Issue by bhupinder-azenix** [hashicorp/terraform-provider-azurerm#19520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_data_connector_azure_security_center

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_data_connector_azure_security_center" "adfc" {
  name                       = "adfc"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.this.id
  subscription_id = data.azurerm_subscription.uat.subscription_id
```

### Debug Output/Panic Output

```shell
TF plan shows below and works well:

+ resource "azurerm_sentinel_data_connector_azure_security_center" "adfc" {
      + id                         = (known after apply)
      + log_analytics_workspace_id = "/subscriptions/xxx-xxx-xxxx-xxxx/resourceGroups/testing-rg/providers/Microsoft.OperationalInsights/workspaces/test-workspace"
      + name                       = "ADFC"
      + subscription_id            = "xxx-xxx-xxxx-xxxx"
    }
```

### Expected Behaviour

Azure Security Center (AKA Defender for cloud) data connector should have been enabled on different subscription.

### Actual Behaviour

azurerm_sentinel_data_connector_azure_security_center.this: Creating...
╷
│ Error: creating Data Connector: (Name "ADFC" / Workspace Name "test-workspace" / Resource Group "testing-rg"): securityinsight.DataConnectorsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource group 'testing-rg' could not be found."

### Steps to Reproduce

1: Create a log analytics workspace in one subscription and enable "azurerm_security_center_subscription_pricing" within the same subscription.

2: Create "azurerm_log_analytics_solution" for SecurityInsights (Sentinel) with in same subscription.

3: Create "azurerm_sentinel_data_connector_azure_security_center" with in same subscription (Where log analytics workspace exist).

4: No issue for above 3 steps However when we want to enable sentinel data connector "azurerm_sentinel_data_connector_azure_security_center" on different subscription by using log analytics workspace from another subscription then we get the error "ResourceGroupNotFound". Looks like TF is trying to find the resource Group in the same Subscription rather than in another subscription.

### References

Similar issue even it's for different resource https://github.com/hashicorp/terraform-provider-azurerm/issues/13961

**Comment by magodo** [comment]
@bhupinder-azenix This is a common issue among the provider. The issue is because currently we are initializing the Azure SDK client with the subscription id bound the the provider when provider got initialized. Then every API call will bound to the that subscription.

In long term, we'll transfer to using the [Hashicorp Azure SDK](https://github.com/hashicorp/go-azure-sdk), which shall hopefully solve this limitation. In short term, you can use another provider block (with an alias), that is bound to the second subscription you want to use, for this data connector.

**Comment by bhupinder-azenix** [comment]
@magodo thanks for looking into this issue. I did try using another provider(with an alias) but similar issue. We have a central log analytics workspace which sits in another subscription and we have enabled the sentinel solution in that log analytics workspace. we are trying to enable the azure security centre (Aka defender for cloud) data connector for another subscription by pointing to central log analytics workspace.

**Comment by magodo** [comment]
The resource id of the data connector is like: `/SUBSCRIPTIONS/{}/RESOURCEGROUPS/{}/PROVIDERS/MICROSOFT.OPERATIONALINSIGHTS/WORKSPACES/{}/PROVIDERS/MICROSOFT.SECURITYINSIGHTS/DATACONNECTORS/{}`, which implies that the data connector is a child resource of a log analytics workspace. So in your case, the central log analytics workspace is in `subscriptionA`, whilst you still need a log analytics workspace in `subscriptionB` to create this data connector?

**Comment by bhupinder-azenix** [comment]
@magodo no we shouldn't need a log analytics workspace in subscriptionB as I was able to enable the data connector in subscriptionB without having a log analytics in subscriptionB using AzApi provider. code same below:

https://learn.microsoft.com/en-us/azure/templates/microsoft.securityinsights/dataconnectors?pivots=deployment-language-terraform

resource "azapi_resource" "adfc_data_connector" {

  type      = "Microsoft.SecurityInsights/dataConnectors@2022-10-01-preview"

  name      = "ADFC_dev"

  parent_id = data.azurerm_log_analytics_workspace.this.id

  body = jsonencode({

    name = "ADFC_dev"

    kind = "AzureSecurityCenter"

    properties = {

      subscriptionId = "${data.azurerm_client_config.this.subscription_id}"

      dataTypes = {

        alerts = {

          state = "enabled"

        }



      }

    }

  })

}

**Comment by magodo** [comment]
@bhupinder-azenix Can you use the provider alias of `subscriptionA` to create this resource and assign whatever you have in `${data.azurerm_client_config.this.subscription_id}` as `subscription_id`? That should be equivalent to above azapi config.

**Comment by bhupinder-azenix** [comment]
@magodo I have just tested with AzureRm version 3.34.0 and it worked as expected. I didn't have to mention provider as well. Not sure if it's fixed in 3.34.0 version? I want to test this in other environment and will let you know with outcome tomorrow.

resource "azurerm_sentinel_data_connector_azure_security_center" "uat" {
  name                       = "uatdefender"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.this.id
  subscription_id            = data.azurerm_subscription.uat.subscription_id
}

**Comment by bhupinder-azenix** [comment]
@magodo tested with version 3.33.0 and it worked with previous version as well so I am not sure what has changed overnight? I will provide you with further update tomorrow.

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed without an update and it is working based on the most recent comments, I am going to mark this issue closed. If you are able to provide more information we may re-open this issue or open a new issue, thanks!
