### ISSUE TITLE
Support for Capacity Reservation Settings in azurerm_site_recovery_replicated_vm

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#19535]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The ability to set the capacity reservation group on the configured azurerm_site_recovery_replicated_vm

Capacity Reservation Settings
Reserve a capacity at the destination location - northeurope for this Virtual machine size - Standard_DS4_v2
[Why to reserve capacity at the destination location?](https://go.microsoft.com/fwlink/?linkid=2184970)

### New or Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replicated_vm

### Potential Terraform Configuration

```hcl
resource "azurerm_site_recovery_replicated_vm" "protected_vm_tf" {
capacity_reservation_group_id = var.reserve_capacity
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/17900

**Comment by ziyeqf** [comment]
Hi @mpjtaylor, I noticed this property has been supported in https://github.com/hashicorp/terraform-provider-azurerm/pull/19939. Do you mind close this issue?

For any further questions please leave comments.
Thanks!

**Comment by mpjtaylor** [comment]
sure i am using this
