### ISSUE TITLE
enable azureADOnlyAuthentications on synapse workspace

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#19540]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

request to add ability to check `Support only Azure Active Directory authentication for this workspace`

parameter should be in one of these resoruces:

1. `azurerm_synapse_workspace_aad_admin`
2. `azurerm_synapse_workspace_sql_aad_admin`
3. `azurerm_synapse_workspace`

1 and 2 manage the same resource in the Azure API per issue #16853

API info: https://learn.microsoft.com/en-us/azure/templates/microsoft.synapse/workspaces/azureadonlyauthentications?pivots=deployment-language-bicep

the only thing to keep in mind - when the aad_admin or sql_aad_admin resource is destroyed, the azureadonlyauthentications needs to be unchecked to allow an empty aad_admin field. thats why i think the parameter makes the most sense in the aad_admin resources.

### New or Affected Resource(s)/Data Source(s)

`azurerm_synapse_workspace_aad_admin` 
`azurerm_synapse_workspace_sql_aad_admin` 
`azurerm_synapse_workspace`

**Comment by stephybun** [comment]
I'm going to close this issue since I believe this has been resolved by #23659
