### ISSUE TITLE
Changing TTL of an existing azurerm_traffic_manager_profile forces new resource

### ISSUE THREAD

**Issue by irmbrady** [hashicorp/terraform-provider-azurerm#1954]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v0.11.8
* provider.azurerm v1.15.0

### Affected Resource(s)

* azurerm_traffic_manager_profile

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 1.15.0"
}

resource "azurerm_traffic_manager_profile" "test" {
  name                = "test"
  resource_group_name = "my-resource-group"

  traffic_routing_method = "Weighted"

  dns_config {
    relative_name = "test"
    ttl           = 60
  }

  monitor_config {
    protocol = "https"
    port     = 443
    path     = "/system/api/canary"
  }
}
```

### Expected Behavior

We expected changing the `azurerm_traffic_manager_profile` `dns_config` `ttl` from `90` to `60` would update the setting without having to re-create the resource, as this is possible from the Azure Portal web console, and also the Azure CLI.

### Actual Behavior

Changing the `ttl` causes Terraform to force a new resource (destroy and re-create). This is not ideal for our production environment.

### Steps to Reproduce

1. Use the HCL above
1. `terraform plan`
1. Output shows `forces new resource`

### Important Factoids

European account.

### References

Not that I am aware of, but I can update here if I find any.

**Comment by Workshop2** [comment]
@tombuildsstuff We are also seeing the same behaviour when changing the `traffic_routing_method` - however, it isn't reported as a drop and create.

This takes down our traffic manager which for production traffic is unacceptable. This seems to be a bug rather than an "enhancement" as it shouldn't be destroying and creating under the hood to change a simple property (especially as it leaves the traffic manager without the endpoints).

This is the log we got which resulted in tearing down the traffic managers rather than updating values:
```Terraform will perform the following actions: 

  ~ module.primary-zone.azurerm_app_service.payments 
      https_only:             "false" => "true" 
  ~ module.primary-zone.azurerm_app_service_slot.payments 
      https_only:             "false" => "true" 
  ~ module.primary-zone.azurerm_traffic_manager_endpoint.api 
      priority:               "2" => "1" 
  ~ module.primary-zone.azurerm_traffic_manager_endpoint.identity 
      priority:               "2" => "1" 
  ~ module.primary-zone.azurerm_traffic_manager_endpoint.payments 
      priority:               "2" => "1" 
  ~ module.region.azurerm_traffic_manager_profile.region 
      traffic_routing_method: "Weighted" => "Priority" 
  ~ module.secondary-zone.azurerm_app_service.payments 
      https_only:             "false" => "true" 
  ~ module.secondary-zone.azurerm_traffic_manager_endpoint.api 
      priority:               "3" => "2" 
  ~ module.secondary-zone.azurerm_traffic_manager_endpoint.identity 
      priority:               "3" => "2" 
  ~ module.secondary-zone.azurerm_traffic_manager_endpoint.payments 
      priority:               "3" => "2" 
Plan: 0 to add, 10 to change, 0 to destroy.```

**Comment by Guidonet** [comment]
Just re-running an apply seems to force a recreate as well.  Only with the traffic manager profile.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
