### ISSUE TITLE
auto_scale attribute is required even after specifying node_count. By definition only one needs to be specified

### ISSUE THREAD

**Issue by Tarvinder91** [hashicorp/terraform-provider-azurerm#19541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

2.74.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_spark_pool

### Terraform Configuration Files

```hcl
spark_pools = {
  "pool1" = {
    name = "pool1"                         # The name which should be used for this Synapse Spark Pool.
    node_size_family = "MemoryOptimized"   # The kind of nodes that the Spark Pool provides. Possible values are MemoryOptimized and None
    node_size = "Small"                    # The level of node in the Spark Pool. Possible values are Small, Medium, Large, None, XLarge, XXLarge and XXXLarge.
    node_count = 1                        

    spark_log_folder=""       
    spark_events_folder=""     
    spark_version=""           
    auto_pause = {
      delay_in_minutes = 5
```

### Debug Output/Panic Output

```shell
Error: Invalid value for input variable
on npe.auto.tfvars line 41:
spark_pools = {
  "pool1" = {
    name = "pool1"                         # The name which should be used for this Synapse Spark Pool.
    node_size_family = "MemoryOptimized"   # The kind of nodes that the Spark Pool provides. Possible values are MemoryOptimized and None
    node_size = "Small"                    # The level of node in the Spark Pool. Possible values are Small, Medium, Large, None, XLarge, XXLarge and XXXLarge.
    node_count = 1                         # The number of nodes in the Spark Pool. Exactly one of node_count or auto_scale must be specified.
    #auto_scale = {                        # Exactly one of node_count or auto_scale must be specified.
    #  min_node_count = 0
    #  max_node_count = 0
    #}
    #library_requirement= {
    #  content = ""           
    #  filename = ""           
    #}
    spark_log_folder=""        
    spark_events_folder=""    
    spark_version=""           
    auto_pause = {
      delay_in_minutes = 5     
    }
  }
}
The given value is not suitable for var.spark_pools declared at variables.tf:100,1-23: element "pool1": attributes "auto_scale" and "library_requirement" are required.
```

### Expected Behaviour

it should not complain that **auto_scale** is required as only one of node_count and auto_scale can be specified

### Steps to Reproduce

terraform plan will throw the error mentioned

**Comment by Tarvinder91** [comment]
Reference:  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_spark_pool#node_count

**Comment by Tarvinder91** [comment]
Also, node_count need to be in the range 3-100. This info is missing

**Comment by ms-henglu** [comment]
Hi @Tarvinder91 ,

Thank you for taking time to report this issue!

It seems that `attributes "auto_scale" and "library_requirement" are required.` message is not from the `azurerm_synapse_spark_pool` resource itself, are you using some module to provision the synapse spark pool?

**Comment by Tarvinder91** [comment]
yes using a module.. That module declares the azurerm_synapse_spark_pool as a resource and only has resources declared. I just realized that is it required because its declared in that module as such. In that case, its my bad. I will report that to internal module and thank you for taking time to revert on this.

**Comment by rcskosir** [comment]
Thank you @Tarvinder91 for opening this issue. It appears as though @ms-henglu was able to help figure out what was causing your issue. Therefore, I am going to go ahead and mark this issue as closed.
