### ISSUE TITLE
Data Source azurerm_api_management fails when not having the required service level permission

### ISSUE THREAD

**Issue by arkiaconsulting** [hashicorp/terraform-provider-azurerm#19582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.34.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
data "azurerm_api_management" "apim" {
  provider            = azurerm.apim
  name                = local.specific.apim.name
  resource_group_name = local.specific.apim.resource_group_name
}
```

### Debug Output/Panic Output

```shell
Error: retrieving tenant access properties for Api Management: (Service Name "**redacted**" / Resource Group "**redacted**"): apimanagement.TenantAccessClient#ListSecrets: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '**redacted**' with object id '**redacted**' does not have authorization to perform action 'Microsoft.ApiManagement/service/tenant/listSecrets/action' over scope '/subscriptions/**redacted**/resourceGroups/**redacted**/providers/Microsoft.ApiManagement/service/**redacted**/tenant/access' or the scope is invalid. If access was recently granted, please refresh your credentials."
```

### Expected Behaviour

The Azure Api management resource is populated correctly (was the case in 3.33.0)

### Actual Behaviour

Unauthorized error when the data source is fetched.

### Steps to Reproduce

terraform plan

### Important Factoids

For organization reasons, the identity executing the plan has restricted access to the Azure APIM service level resources..

### References

#19422

**Comment by martin-fuhrer** [comment]
I have the same issue and I consider this a bug. The tenant information should only be read if the `tenant_access` block is specified.

**Comment by arkiaconsulting** [comment]
@martin-fuhrer the `tenant_access` block is an output block, thus it cannot be specified. As a result, the behaviour of this data dource may be either:
- don't fill the `tenant_access` block if not having the right permission (ie swallow the 403)
- provide an input parameter allowing the consumer to specify that he doesn't want the `tenant_access` block to be filled

**Comment by xuzhang3** [comment]
@martin-fuhrer what roles or permission your SPN have if use SPN to run the Terraform? Assume u use SPN to do the auth, can you try grant the `API Management Service Operator Role` role to your SPN and try again?

**Comment by arkiaconsulting** [comment]
> @martin-fuhrer what roles or permission your SPN have if use SPN to run the Terraform? Assume u use SPN to do the auth, can you try grant the `API Management Service Operator Role` role to your SPN and try again?

@xuzhang3 In the organization which I work for, it's not an option. The Api Management resource is managed organization wide by another Team. Each consumer team have permission for their own Api, but very few permissions at APIM level.

**Comment by xuzhang3** [comment]
@arkiaconsulting due to the permissions not allowed.  Two suggestions:
1) Contact the service team for additional permission
2) Downgrade the AzureRM provider version

**Comment by arkiaconsulting** [comment]
@xuzhang3 Downgrading the provider version means getting stuck to this version...

**Comment by tombuildsstuff** [comment]
hey @arkiaconsulting 

Thanks for opening this issue.

Please disregard the comments about downgrading the provider version from @xuzhang3 here, this is a bug in the Provider - whilst we do require new permissions from time-to-time in Resources (since we need to retrieve additional information to be able to manage it effectively) - Data Sources should handle the missing permissions gracefully by outputting this as an empty list instead.

I've tagged this as a `bug` - @sinbai since you introduced this change to the Data Source, would you mind sending a PR to fix this?

Thanks!

**Comment by sinbai** [comment]
Hi @arkiaconsulting, thanks for raising this issue. I have submitted [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/19626)to fix this issue. Could you track if for more updates?
