### ISSUE TITLE
azurerm_kusto_cluster_principal_assignment - Missing Role

### ISSUE THREAD

**Issue by 784651** [hashicorp/terraform-provider-azurerm#19584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.34.0

### AzureRM Provider Version

current

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster_principal_assignment

### Terraform Configuration Files

```hcl
Missing Role Type, AllDatabasesMonitor. You have AllDatabasesAdmin and AllDatabasesViewer, but missing the third.

resource "azurerm_kusto_cluster_principal_assignment" "blah_blah" {  
  name                = "blah-blah"
  resource_group_name = azurerm_resource_group.main.name
  cluster_name        = azurerm_kusto_cluster.main.name
  tenant_id           = data.azuread_client_config.current.tenant_id
  principal_id        = "GUID-HERE" #GUID
  principal_type      = "App"
  role                = "AllDatabasesMonitor"
}
```

### Debug Output/Panic Output

```shell
The role isn't defined..
```

### Expected Behaviour

Allow terraform to set the AllDatabasesMonitor permission

### Actual Behaviour

The type is not defined

### Steps to Reproduce

run it?

### Important Factoids

Nope

### References

https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/access-control/role-based-authorization
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_cluster_principal_assignment#role

**Comment by liuwuliuyun** [comment]
Hi @784651 , thanks for raising this issue. For current version of API we are using, only those two properties are supported. Link: https://github.com/Azure/azure-rest-api-specs/blob/1be09531e4c6edeafde41d6562371566d39669e8/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2022-02-01/kusto.json#L4867-L4873. The same in the latest API version https://github.com/Azure/azure-rest-api-specs/blob/1be09531e4c6edeafde41d6562371566d39669e8/specification/azure-kusto/resource-manager/Microsoft.Kusto/stable/2022-07-07/kusto.json#L4923-L4934. Would you mind to share where you got the information that AllDatabasesMonitor is allowed here?

**Comment by liuwuliuyun** [comment]
Let me help to raise a PR in swagger to help this case.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. Here is a link to the upstream request: https://github.com/Azure/azure-rest-api-specs/issues/21813. When it gets added, we can reopen this request or you can create a new one.
