### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.34.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by bpriyas92** [hashicorp/terraform-provider-azurerm#19598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.3

### AzureRM Provider Version

 version = ">=2.99"

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_compute_cluster

### Terraform Configuration Files

```hcl
module "compute_cluster" {
  for_each                             = var.clusters
  source                               = "../../../lib/compute_cluster"
  compute_cluster_name                 = each.value.compute_cluster_name
  location                             = each.value.location
  priority                             = each.value.vm_priority
  vm_size                              = each.value.vm_size
  workspace_id                         = each.value.workspace_id
  subnet_id                            = each.value.subnet_ids
  min_node_count                       = each.value.min_node_count
  max_node_count                       = each.value.max_node_count
  scale_down_nodes_after_idle_duration = each.value.scale_down_nodes_after_idle_duration
  identity                             = each.value.vm_identity
  username                             = each.value.username
  ssh_key                              = each.value.ssh_key
}
```

### Debug Output/Panic Output

```shell
Error: Request cancelled
│ 
│   with module.compute_cluster["test-cluster2"].azurerm_machine_learning_compute_cluster.compute_cluster,
│   on ../../../lib/compute_cluster/main.tf line 1, in resource "azurerm_machine_learning_compute_cluster" "compute_cluster":
│    1: resource "azurerm_machine_learning_compute_cluster" "compute_cluster" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
Releasing state lock. This may take a few moments...

Stack trace from the terraform-provider-azurerm_v3.34.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 95 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning.expandUserAccountCredentials(...)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go:345
github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning.resourceComputeClusterCreate(0x0?, {0x5a6c2a0?, 0xc000b52c00})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/machinelearning/machine_learning_compute_cluster_resource.go:182 +0x1954
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x6c65bc0?, {0x6c65bc0?, 0xc00198af30?}, 0xd?, {0x5a6c2a0?, 0xc000b52c00?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0009bf6c0, {0x6c65bc0, 0xc00198af30}, 0xc001c48820, 0xc001eede80, {0x5a6c2a0, 0xc000b52c00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0006032c0, {0x6c65bc0?, 0xc00198aae0?}, 0xc0000b7c20)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000bf8820, {0x6c65bc0?, 0xc0018713b0?}, 0xc00276ce00)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x60db9e0?, 0xc000bf8820}, {0x6c65bc0, 0xc0018713b0}, 0xc00276cd90, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00025c000, {0x6c77520, 0xc001348820}, 0xc001c38a20, 0xc00080fa10, 0xade10c0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00025c000, {0x6c77520, 0xc001348820}, 0xc001c38a20, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.34.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Terraform apply should have deployed cluster

### Actual Behaviour

terraform apply failed

### Steps to Reproduce

terraform apply

**Comment by JudedeDude** [comment]
Same happen with me on this today...any fixes ?

**Comment by danielkelly22** [comment]
Pretty similar error with regards to the plugin crashing

```
Stack trace from the terraform-provider-azurerm_v3.34.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 135 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.expandFrontdoorDeliveryRuleConditions({0xc00115c9a0, 0x1, 0x6c59fe0?})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:891 +0x909
github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn.resourceCdnFrontDoorRuleCreate(0x0?, {0x5a6c2a0?, 0xc000ad7800})
	github.com/hashicorp/terraform-provider-azurerm/internal/services/cdn/cdn_frontdoor_rule_resource.go:649 +0x65c
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x6c65bc0?, {0x6c65bc0?, 0xc00118d4a0?}, 0xd?, {0x5a6c2a0?, 0xc000ad7800?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00060b0a0, {0x6c65bc0, 0xc00118d4a0}, 0xc001cfd930, 0xc001867d00, {0x5a6c2a0, 0xc000ad7800})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001614b10, {0x6c65bc0?, 0xc00118d380?}, 0xc001cb14a0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001684b40, {0x6c65bc0?, 0xc00118c420?}, 0xc0002db880)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x60db9e0?, 0xc001684b40}, {0x6c65bc0, 0xc00118c420}, 0xc0002db7a0, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00014e1e0, {0x6c77520, 0xc0017601a0}, 0xc001cd4c60, 0xc001722d80, 0xade10c0, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc00014e1e0, {0x6c77520, 0xc0017601a0}, 0xc001cd4c60, 0x0)
	google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.34.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by myc2h6o** [comment]
Hi @bpriyas92 thanks for opening the issue! and thanks @danielkelly22 for sharing the other failure. I've opened #19613 to fix these two crashes. Similar to #19554 when an empty block is specified in the config file. @JudedeDude if the crash you haves seen is for a different resource/function, would you mind sharing the crash detail so that we could further check the issue?

@bpriyas92 while trying to repro the issue, I found `admin_username` is requred in the `ssh` block and I'm not able to create an empty block, would you mind also sharing the config block you used for `azurerm_machine_learning_compute_cluster.ssh` block?

**Comment by bpriyas92** [comment]
Below is the cluster config block you have asked for

resource "azurerm_machine_learning_compute_cluster" "compute_cluster" {
  name                          = var.compute_cluster_name
  location                      = var.location
  vm_priority                   = var.priority
  vm_size                       = var.vm_size
  machine_learning_workspace_id = var.workspace_id
  subnet_resource_id            = var.subnet_id

  scale_settings {
    min_node_count                       = var.min_node_count
    max_node_count                       = var.max_node_count
    scale_down_nodes_after_idle_duration = var.scale_down_nodes_after_idle_duration
  }

  identity {
    type = var.identity
  }

  ssh {
    admin_username = var.username
    key_value      = var.ssh_key
  }
}

**Comment by myc2h6o** [comment]
@bpriyas92 thanks for sharing the config. I have got a repro with below config. Looks like when all arguments in the nested block are set to their default value, the nested property itself will be nil.
```
  ssh {
    admin_username = ""
    key_value = ""
  }
```

**Comment by myc2h6o** [comment]
@bpriyas92 this looks to be a document error. There is a missing note to say at least one of `admin_password` and `key_vault` should be specified to match the code https://github.com/hashicorp/terraform-provider-azurerm/blob/4007e677a56f707dab3be0bf253c23dfa6de4ca2/internal/services/machinelearning/machine_learning_compute_cluster_resource.go#L114-L125

**Comment by JudedeDude** [comment]
> Hi @bpriyas92 thanks for opening the issue! and thanks @danielkelly22 for sharing the other failure. I've opened #19613 to fix these two crashes. Similar to #19554 when an empty block is specified in the config file. @JudedeDude if the crash you haves seen is for a different resource/function, would you mind sharing the crash detail so that we could further check the issue?
> 
> @bpriyas92 while trying to repro the issue, I found `admin_username` is requred in the `ssh` block and I'm not able to create an empty block, would you mind also sharing the config block you used for `azurerm_machine_learning_compute_cluster.ssh` block?

Here are my logs for the plugin

 Error: Plugin did not respond
│
│   with azurerm_lighthouse_assignment.beisprd_soc_contributor["beis-rg-assessment"],
│   on main.tf line 54, in resource "azurerm_lighthouse_assignment" "beisprd_soc_contributor":
│   54: resource "azurerm_lighthouse_assignment" "beisprd_soc_contributor" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.33.0_x5.exe plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 98 [running]:
github.com/Azure/go-autorest/autorest/azure.getProvider(...)
        github.com/Azure/go-autorest/autorest@v0.11.27/azure/rp.go:78
github.com/Azure/go-autorest/autorest/azure.register({{0x7299680, 0xc0014709f0}, {0x729dc00, 0xc0022b0390}, 0xc0022b03c0, 0x0, 0x6fc23ac00, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...}, ...)
        github.com/Azure/go-autorest/autorest@v0.11.27/azure/rp.go:88 +0xe87
github.com/Azure/go-autorest/autorest/azure.DoRetryWithRegistration.func1.1(0xc00027ec00)
        github.com/Azure/go-autorest/autorest@v0.11.27/azure/rp.go:65 +0x3e5
github.com/Azure/go-autorest/autorest.SenderFunc.Do(0x729db60?, 0xc0002f7320?)
        github.com/Azure/go-autorest/autorest@v0.11.27/sender.go:84 +0x1f
github.com/Azure/go-autorest/autorest.SendWithSender({0x729db60?, 0xc0002f7320?}, 0xb595908?, {0xc001b06ac0, 0x1, 0x90?})
        github.com/Azure/go-autorest/autorest@v0.11.27/sender.go:126 +0x6a
github.com/Azure/go-autorest/autorest.Client.Send({{0x7299680, 0xc0014709f0}, {0x729dc00, 0xc0022b0390}, 0xc0022b03c0, 0x0, 0x6fc23ac00, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...}, ...)
        github.com/Azure/go-autorest/autorest@v0.11.27/client.go:327 +0x133
github.com/hashicorp/go-azure-sdk/resource-manager/managedservices/2019-06-01/registrationassignments.RegistrationAssignmentsClient.Get({{{0x7299680, 0xc0014709f0}, {0x729dc00, 0xc0022b0390}, 
0xc0022b03c0, 0x0, 0x6fc23ac00, 0xd18c2e2800, 0x3, 0x6fc23ac00, ...}, ...}, ...)
        github.com/hashicorp/go-azure-sdk@v0.20221122.1115312/resource-manager/managedservices/2019-06-01/registrationassignments/method_get_autorest.go:51 +0x110
github.com/hashicorp/terraform-provider-azurerm/internal/services/lighthouse.resourceLighthouseAssignmentCreate(0x0?, {0x60ad080?, 0xc0020a2400})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/lighthouse/lighthouse_assignment_resource.go:83 +0x285
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x72a9fc0?, {0x72a9fc0?, 0xc0002d99b0?}, 0xd?, {0x60ad080?, 0xc0020a2400?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0012850a0, {0x72a9fc0, 0xc0002d99b0}, 0xc0002fb450, 0xc0020ad380, {0x60ad080, 0xc0020a2400})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000008258, {0x72a9fc0?, 0xc0002d9890?}, 0xc0014dcd70)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0015fa5a0, {0x72a9fc0?, 0xc0002d9260?}, 0xc001c0cd20)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x670d840?, 0xc0015fa5a0}, {0x72a9fc0, 0xc0002d9260}, 0xc001c0ccb0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001f61e0, {0x72bd800, 0xc0012f81a0}, 0xc001ab98c0, 0xc0016716e0, 0xb52f6c0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001f61e0, {0x72bd800, 0xc0012f81a0}, 0xc001ab98c0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.34.0_x5.exe plugin crashed!


The same plugin and same code base works on different tenants in Azure

**Comment by myc2h6o** [comment]
Hi @JudedeDude The crash from the log file you shared seems to be due to some different issue. Would you mind opening a separate issue? And for troubleshooting, would you mind sharing the config file and whether it is working fine or not in the previous version?
