### ISSUE TITLE
unable to create azurerm_monitor_metric_alert on azure monitor for sql  managed instance

### ISSUE THREAD

**Issue by MukulOberoi52** [hashicorp/terraform-provider-azurerm#19597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.2

### AzureRM Provider Version

3..34.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "example" {
  for_each = var.monitor_metric_alerts

  name                = lookup(each.value, "custom_name", null)
  description         = each.value.description
  resource_group_name = var.resource_group_name
  scopes              = each.value.scopes

  criteria {
    metric_namespace = lookup(each.value.criteria, "metric_namespace")
    metric_name      = lookup(each.value.criteria, "metric_name")
    aggregation      = lookup(each.value.criteria, "aggregation")
    operator         = lookup(each.value.criteria, "operator")
    threshold        = lookup(each.value.criteria, "threshold")

    # dimension {
    #   name     = "ApiName"
    #   operator = "Include"
    #   values   = ["*"]
    # }
  }

  action {
    action_group_id = azurerm_monitor_action_group.action_group_notification.id
  }

  tags = var.tags
}

and modules where values are passed

module "alerts" {
  source              = "../alerts"
  resource_group_name = data.azurerm_resource_group.rg.name
  action_group_name = "testactiongroup"
  action_group_short_name = "testag"
  action_group_emails = {
  "Mukul Oberoi" = "mukul.oberoi@techolution.com"
}        
  
  monitor_metric_alerts = {
    
    "sql-mi" = {
      custom_name         = "test-sqlmi"
      description         = "Average percentage of CPU utilization in selected time period."
      scopes              = [module.sqlmi.sql_mi_id]
      criteria = {
        metric_namespace = " Microsoft.Sql/managedInstances"
        metric_name      = "Average CPU percentage"
        aggregation      = "Average"
        operator         = "GreaterThan"
        threshold        = 50
      }
    }
  }
  tags                           = {
    Application = "SQL DB MI"
    Approver = "Akash"
    Brand = "Harper Collins"
    Business = "Azure"
    Business_Unit = "DB"
    Data_Classification = "random"
    Environment = "sandbox"
    Location = "eastus"
    Organization = "hc"
    Owner = "akash"
    Project = "migration"
    Team = "azure"
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating or updating Monitor Metric Alert: (Name "test-sqlmi" / Resource Group "RG_Playgroud"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Couldn't find a metric named Average CPU percentage. Make sure the name is correct. If this metric hasn't been reported yet, use the -skipMetricValidation flag. Learn more here: https://docs.microsoft.com/azure/azure-monitor/platform/alerts-troubleshoot-metric#define-an-alert-rule-on-a-custom-metric-that-isnt-emitted-yet  Activity ID: 41440a34-0d52-4641-9c8b-908f986cb42d."
│
│   with module.alerts.azurerm_monitor_metric_alert.example["sql-mi"],
│   on ..\alerts\main.tf line 20, in resource "azurerm_monitor_metric_alert" "example":
│   20: resource "azurerm_monitor_metric_alert" "example" {
│
```

### Expected Behaviour

It should create alert for cpu percentange for sql mi.

### Actual Behaviour

error
metric named Average CPU percentage. Make sure the name is correct. If this metric hasn't been reported yet, use the -skipMetricValidation flag. Learn more here: https://docs.microsoft.com/azure/azure-monitor/platform/alerts-troubleshoot-metric#define-an-alert-rule-on-a-custom-metric-that-isnt-emitted-yet  Activity ID: 41440a34-0d52-4641-9c8b-908f986cb42d."
│
│   with module.alerts.azurerm_monitor_metric_alert.example["sql-mi"],
│   on ..\alerts\main.tf line 20, in resource "azurerm_monitor_metric_alert" "example":
│   20: resource "azurerm_monitor_metric_alert" "example" {
│

### Steps to Reproduce

terraform apply

**Comment by teowa** [comment]
Hi @MukulOberoi52 , thanks for submitting this issue!
From the error message, maybe we can enable skipMetricValidation to suppress the error, and in terraform we currently support set [skip_metric_validation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert#skip_metric_validation) property like in below config:

```
  criteria {
    metric_namespace = lookup(each.value.criteria, "metric_namespace")
    metric_name      = lookup(each.value.criteria, "metric_name")
    aggregation      = lookup(each.value.criteria, "aggregation")
    operator         = lookup(each.value.criteria, "operator")
    threshold        = lookup(each.value.criteria, "threshold")

    skip_metric_validation = true
  }
```

**Comment by MukulOberoi52** [comment]
![image](https://user-images.githubusercontent.com/120018909/206504256-7a1dbbae-8a2f-47bd-88a0-c20279210edf.png)
Hi @teowa , thanks for the suggestion. but still issue persists. Please see the attachment.

**Comment by MukulOberoi52** [comment]
it works avg_cpu_percent with this value. Thanks for the help. I appreciate for giving your valuable time

**Comment by rcskosir** [comment]
Thank you @MukulOberoi52 for opening this issue and thank you @teowa for helping find a working solution. 
I am going to mark this issue as complete as a working solution has been reached.
