### ISSUE TITLE
Custom linked service type "DB2" gets sent as type "LinkedService" causing an error.

### ISSUE THREAD

**Issue by Thegsgs** [hashicorp/terraform-provider-azurerm#19596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0-dev

### AzureRM Provider Version

3.34.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_linked_custom_service

### Terraform Configuration Files

```hcl
resource "azurerm_data_factory_linked_custom_service" "AS400_DB2" {
  name                 = "LS_Source_AS400"
  data_factory_id      = module.data_factory.data_factory_id
  type                 = "DB2"
  description          = "test description"
  type_properties_json = <<JSON
{
  "connectionString":"*****"
}
JSON
}
```
```


### Debug Output/Panic Output

```shell
Not an error within terraform.
```

### Expected Behaviour

Custom liked service of type DB2 in Azure data factory.

### Actual Behaviour

Error from azure:
```
datafactory.LinkedServicesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Failed to encrypt sub-resource payload {\r\n  \"Id\": \"/subscriptions/***/resourceGroups/HRL-RG-Dev-DataCloud-001/providers/Microsoft.DataFactory/factories/hrl-hdc-adf-dev001/linkedservices/LS_Source_AS400\",\r\n  \"Name\": \"LS_Source_AS400\",\r\n  \"Properties\": {\r\n    \"description\": \"test description\",\r\n    \"type\": \"LinkedService\",\r\n    \"typeProperties\": {\r\n      \"connectionString\": \"********************\"\r\n    }\r\n  }\r\n} and error is: Invalid type 'LinkedService' is provided in 'linkedServices'. Please correct the type in payload and retry.." Target="/subscriptions/***/resourceGroups/HRL-RG-Dev-DataCloud-001/providers/Microsoft.DataFactory/factories/hrl-hdc-adf-dev001/linkedservices/LS_Source_AS400"
```

### Steps to Reproduce

terraform apply

**Comment by ms-henglu** [comment]
Hi @Thegsgs ,

Thank you for taking time to report this issue!

It seems that the `type` field is case sensitive, would you please change it to `type = "Db2"` and give it a try? Thanks!

**Comment by rcskosir** [comment]
@Thegsgs Thank you for opening this issue. Based on your emoji reactions to @ms-henglu's suggestion regarding `type = "Db2"`, I am going to assume this helped solve your issue, and thus I am going to mark this issue as closed.
