### ISSUE TITLE
Support for Go 1.18 and 1.19 in windows/linux web app

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#19615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Go language (v1.18 and v1.19) is natively supported on Azure App Service

### New or Affected Resource(s)/Data Source(s)

* azurerm_linux_web_app 
* azurerm_windows_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  site_config {
    application_stack {
      go_version = "1.18"
    }
  }
  ...
```

### References

https://azure.microsoft.com/en-us/updates/public-preview-go-language-support-on-azure-app-service/

**Comment by xiaxyi** [comment]
Thanks @abilous-ti for raising this issue, the feature enhancement is added in pr #19685 .

**Comment by xiaxyi** [comment]
@abilous-ti Terraform now supports go 1.18/ 1.19, can you confirm if its working as expected from you side? Thanks

**Comment by abilous-ti** [comment]
It works for me. Thank you very much

**Comment by abilous-ti** [comment]
@xiaxyi Please close the ticket
