### ISSUE TITLE
Support for Node.js 18 in Azure App Service azurerm_linux_web_app

### ISSUE THREAD

**Issue by YusukeSugiyamaTG** [hashicorp/terraform-provider-azurerm#19619]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure App Service support for Node.js 18 is now available. Currently, Node.js version 18 is the recommended version and LTS.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example-linux-web-app"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  service_plan_id     = azurerm_service_plan.example.id
  site_config {
    application_stack {
      node_version = "18-lts"
    }
  }
}
```

### References

https://azure.github.io/AppService/2022/10/12/New-Language-Stacks-available-on-AppService.html

**Comment by xiaxyi** [comment]
Thanks @YusukeSugiyamaTG for raising this issue, the windows version is included in the pr https://github.com/hashicorp/terraform-provider-azurerm/pull/19343. I will add the support for Linux version to my working list but unfortunately that I can't provide any ETA now.

**Comment by YusukeSugiyamaTG** [comment]
Thanks @xiaxyi for confirming this issue, I understand that it is supported in the windows version #19343. Thank you also for adding it to the working list, I am waiting for it to be supported.

**Comment by xiaxyi** [comment]
@YusukeSugiyamaTG Node 18 is supported now, can you try and see if it works for you?

**Comment by YusukeSugiyamaTG** [comment]
@xiaxyi I tried it and it works correctly. Thank you very much for your support.
