### ISSUE TITLE
azurerm_backup_protected_vm unable to change policy and ASR

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#19629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_backup_protected_vm 

### Terraform Configuration Files

```hcl
resource "azurerm_backup_protected_vm" "vm1" {
  count               = (local.backup || local.production) && !var.orchestration_dry_run && var.backupv2 ? 1 : 0
  resource_group_name = var.support_resource_group
  recovery_vault_name = data.azurerm_recovery_services_vault.vault[0].name
  source_vm_id        = local.virtual_machine_id
  backup_policy_id    = local.support_backup_policy_id
}
```

### Debug Output/Panic Output

```shell
Error: creating/updating Azure Backup Protected VM "VM;iaasvmcontainerv2;z-ago-driftdemo-dv05-en1-01;zagodriftdemodv05221" (Resource Group "z-ago-support-dv05-en1-01"): backup.ProtectedItemsClient#CreateOrUpdate: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="BMSUserErrorContainerIsAlreadyRegisteredWithAnotherVault" Message="Virtual machine is already registered\\registering with another recovery services vault. Please select a different virtual machine for registration."
with module.terraform-azure-linux-real["221"].azurerm_backup_protected_vm.vm1[0]
on .terraform/modules/terraform-azure-linux-real/backup.tf line 35, in resource "azurerm_backup_protected_vm" "vm1":
resource "azurerm_backup_protected_vm" "vm1" {
```

### Expected Behaviour

virtual machine container is dissociated and then the new asr is associated.

### Actual Behaviour

first run fails , a re run resolves this issue

### Steps to Reproduce

set a backup policy with AS1 try to change to ASR2 fail occurs. re run ASR2 is associated.

**Comment by mpjtaylor** [comment]
changing backup policy and ASR so originally ASR1 and policy1 switch to ASR2 policy2

**Comment by ziyeqf** [comment]
Hi @mpjtaylor, Could you please confirm if it's similar to the following change?  And does `ASR` means `Azure Site Recovery`? Please provide some more details, thanks.

original config
---
```
resource "azurerm_backup_protected_vm" "vm" {
# other properties
  backup_policy_id    =  azurerm_backup_policy_vm.original.id
}
```

changed config
---
```
resource "azurerm_backup_protected_vm" "vm" {
# other properties
  backup_policy_id    =  azurerm_backup_policy_vm.target.id
}
```

**Comment by mpjtaylor** [comment]
yes correct on both counts!
