### ISSUE TITLE
Support for Defender CSPM

### ISSUE THREAD

**Issue by MavSasha** [hashicorp/terraform-provider-azurerm#19646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new Defender Plan available in Azure Defender - Environment Settings, called: Defender CSPM
We would like to toggle manage the setting for all subscriptions via terraform - like the others already existing ones.

### New or Affected Resource(s)/Data Source(s)

azurerm_security_center_subscription_pricing

### Potential Terraform Configuration

```hcl
//Example for Containers, just use CSPM instead
resource "azurerm_security_center_subscription_pricing" "Containers" {
  resource_type = "Containers"
  tier          = "Standard"
  lifecycle {
    ignore_changes = [
      subplan
    ]
  }
}
```

**Comment by jmyers82** [comment]
Is this the same as Cloud Posture?  I believe that functionality is already in place?
resource "azurerm_security_center_subscription_pricing" "mdc_cloud_posture" {
  tier          = "Standard"
  resource_type = "CloudPosture"
}

**Comment by MavSasha** [comment]
Ye thanks, that wasn't in place when it came out. Can close the case.
