### ISSUE TITLE
How to turn on Application Insights for `azurerm_linux_web_app` resource with Terraform code?

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-provider-azurerm#19653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

How to turn on Application Insights for [azurerm_linux_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) resource with Terraform code?

---

- This issue is related to #1303.

- Tried `hidden-link` with `tags` workaround, but to no avail.

```hcl
resource "azurerm_application_insights" "application_insights" {
  # ...
  tags = merge(
    local.tags,
    { "hidden-link:/subscriptions/${data.azurerm_subscription.current.subscription_id}/resourceGroups/${local.linuxwebappname}" = "Resource" }
  )
  # ...
}

resource "azurerm_linux_web_app" "linux_web_app" {
  # ...
  app_settings = {
    APPINSIGHTS_INSTRUMENTATIONKEY =  azurerm_application_insights.application_insights.instrumentation_key
    APPLICATIONINSIGHTS_CONNECTION_STRING =  azurerm_application_insights.application_insights.connection_string
  }
  # ...
}
```

---

<img width="823" alt="Screenshot 2022-12-12 at 17 10 24" src="https://user-images.githubusercontent.com/305414/207096783-38968b77-1cee-480b-8954-b4ae2d272587.png">

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app, azurerm_windows_web_app

**Comment by xiaxyi** [comment]
Thanks @sheeeng for raising this issue, can you try adding the key `ApplicationInsightsAgent_EXTENSION_VERSION` to `app_setting`? for example `    ApplicationInsightsAgent_EXTENSION_VERSION = "~3"
`

**Comment by sheeeng** [comment]
> Thanks @sheeeng for raising this issue, can you try adding the key `ApplicationInsightsAgent_EXTENSION_VERSION` to `app_setting`? for example ` ApplicationInsightsAgent_EXTENSION_VERSION = "~3"`

Hi @xiaxyi, thank you for the workaround. It works.

![image](https://user-images.githubusercontent.com/305414/207270927-3f6bc2d9-68ea-40cb-9c4d-a0c5d186d127.png)


The `hidden-link` tag was removed at the same time as it is not helping in this issue.

The complete workaround is shown below.

```hcl
resource "azurerm_linux_web_app" "linux_web_app" {
  # ...
  app_settings = {
    APPINSIGHTS_INSTRUMENTATIONKEY =  azurerm_application_insights.application_insights.instrumentation_key
    APPLICATIONINSIGHTS_CONNECTION_STRING =  azurerm_application_insights.application_insights.connection_string
    ApplicationInsightsAgent_EXTENSION_VERSION = "~3"
  }
  # ...
}
```
