### ISSUE TITLE
Support image_cleaner block doesn't work as expected

### ISSUE THREAD

**Issue by yildizbilal** [hashicorp/terraform-provider-azurerm#19654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks-cluster" {
  name                = var.CLUSTER_NAME
  location            = var.LOCATION
  resource_group_name = var.RESOURCE_GROUP
  dns_prefix          = var.CLUSTER_NAME
  depends_on          = [azurerm_public_ip.aks-public-ip]
  kubernetes_version  = var.K8S_VERSION
  tags                = var.TAGS

  default_node_pool {
    name                = "ap${replace(lower(var.CLUSTER_NAME), "/[^a-z0-9]/", "")}"
    node_count          = var.NODE_COUNT
    vm_size             = var.NODE_SIZE
    enable_auto_scaling = false
    vnet_subnet_id = azurerm_subnet.subnet.id
    tags           = var.TAGS
  }

  azure_policy_enabled              = false
  http_application_routing_enabled  = false
  role_based_access_control_enabled = false

  linux_profile {
    admin_username = var.CLUSTER_ADMIN

    ssh_key {
      key_data = var.CLUSTER_PUBLIC_SSH
    }
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "standard"
    load_balancer_profile {
      outbound_ip_address_ids = [azurerm_public_ip.aks-public-ip.id]
    }
  }

  service_principal {
    client_id     = var.SERVICE_PRINCIPAL_CLIENT_ID
    client_secret = var.SERVICE_PRINCIPAL_SECRET
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output/Panic Output

```shell
# module.aks.azurerm_kubernetes_cluster.aks-cluster will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "aks-cluster" {
        id                                  = "/subscriptions/.."
      + image_cleaner_enabled               = false
      + image_cleaner_interval_hours        = 48
        name                                = "k8s"
        tags                                = {
            "Product" = ".."
        }
        # (23 unchanged attributes hidden)

      ~ service_principal {
          + client_secret = (sensitive value)
            # (1 unchanged attribute hidden)
        }

        # (4 unchanged blocks hidden)
    }
```

### Expected Behaviour

When i upgrade to azurerm version 3.35.0 no affected changes to `image_cleaner_enabled` and `image_cleaner_interval_hours` should be shown, when it isn't in use. 

### Actual Behaviour

Changes to our kubernetes cluster configuration is shown for the fields `image_cleaner_enabled = false` and `image_cleaner_interval_hours = 48`. I didn't understand why these fields got some default values. When i reimport the kubernetes resource with `terraform state rm ..` and `terraform import ...` then the values in the state file are `null`. So there is also an inconsistency between "plan" and "import" when fetching the values from azure. 

### Steps to Reproduce

Pre: Deployed cluster without enabled image cleaner.

1. Upgrade azurerm from `3.16.0` to `3.35.0`
2. tf init
3. tf plan

### References

#19368
#19241

**Comment by yildizbilal** [comment]
Probably i misunderstood how terraform works and this is not a bug. [This](https://discuss.hashicorp.com/t/optional-resource-fields-are-not-optional/10191) article helped me to better understand the "workflow". Until this moment what i thought was: Terraform checks through the provider the actual values configured at the using cloud provider (the "real-world" - how the CTO explained it) and fetches them. 

So theoretically what i was assuming was, that when i re-import the affected resource with the new provider version (in this example azurerm v3.35.0), the new added fields `image_cleaner_enabled ` and `image_cleaner_interval_hours` should get the correct values from them - but this is not the case, right? And also what i was assuming was that when i not use a field, especially optional fields, shouldn't be affected and doesn't need values. This is also not correct. They have optional values with they will be set even they aren't configured in the terraform configuration files.

But there is something that i didn't catch yet. I tried to find the current set values of those two new support fields and couldn't find them in the azure portal. I have to be careful with applying changes, so couldn't apply those fields with there default values because im not sure if that will trigger a change in the real-world configurations or if they just entries in the state file without changing real running system. Im a bit confused.

Can someone explain me how all that stuff works (links to explanations would also be enough)? And how to deal with such new supported fields? Can i apply them without system changes? When i import them i get "null" values for those fields, but when i do a plan i get default values which - how i understood how terraform works - will change the state file and make changes to the real-world system?..

**Comment by stephybun** [comment]
@leaiabrugena the default for enabling the image cleaner is set to `false`, so even though Terraform is throwing a diff and attempting to make a change to the resource, it shouldn't alter the behaviour of the cluster.

This will be fixed in the next major version of the provider by #25296.
