### ISSUE TITLE
Add example service principal configuration for azurerm_postgresql_flexible_server_active_directory_administrator

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#19658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to see the documentation updated for website/docs/r/postgresql_flexible_server_active_directory_administrator.html.markdown

Following the example provided I get this error...

`Error: updating Flexible Server
polling after Update: Code="AadAuthEnableFailedDueToMissingGraphApiAccessPrincipal" Message="Expected Microsoft Graph API client application with ClientId = 5657e26c-cc92-45d9-bc47-9da6cfdb4ed9 is not found in the TenantId = aacf2201--XXXX, or does not have required permissions."`

I'm tired and confused and I would like if the SP resource configuration could be added as well.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_active_directory_administrator

**Comment by ziyeqf** [comment]
Hi @DevopsMercenary, thanks for opening the issue.

A PR (#19673) has submitted to add documents, I'd like to share the steps needed here for you first.

1. you can add the needed service principal by Powershell per this [document](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/how-to-configure-sign-in-azure-ad-authentication?source=recommendations#install-the-azure-ad-powershell-module)

2. or you can deploy by the following Terraform config, it will use `azuread` provider and need some API permissions which could be found [here](https://registry.terraform.io/providers/hashicorp/azuread/latest/docs/resources/service_principal) 

---
```
provider "azuread" {
}

resource "azuread_service_principal" "postgresql" {
  application_id = "5657e26c-cc92-45d9-bc47-9da6cfdb4ed9"
  use_existing   = true
}
```
