### ISSUE TITLE
Function app scm.azurewebsites.net endpoint

### ISSUE THREAD

**Issue by arichiardi** [hashicorp/terraform-provider-azurerm#1965]
Hello folks,
I decided to write this question here, because I think it might bring about some code feature, but I am not sure so apologies in advance if not.

I am trying to get, give a function app, the hostname of Kudu/Logs, which looks like this:

```
<function-app>.scm.azurewebsites.net
```

It is of course different (I never notice the `scm` part) and at the moment not returned by the function app `azurerm_function_app`.

I was wondering whether I am missing a better way of doing.

Thank you in advance for the answers!

**Comment by kevinneufeld** [comment]
@arichiardi

I think what you are looking do is something like this: 
` "${format("%s.scm.azurewebsites.net" azurerm_function_app.test.name)}"` 
you then can use it within the resource or as an output like the example below:

```HCl
output "scm_hostname" {
  value = "${format("%s.scm.azurewebsites.net" azurerm_function_app.test.name)}"
}
```

**Comment by arichiardi** [comment]
Yep that is what I am basically doing now - that would still hardcode `scm.azurewebsites.net`. I was wondering whether there is a way to get that path from some Azure resource instead.

**Comment by kevinneufeld** [comment]
@arichiardi, 
Unfortunately no. Looking through Azure Resource on both web app and function there is no specific `scm/kudo` hostname property.  The closest is on a collection under `enabledHostNames`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
