### ISSUE TITLE
Wrong Casing in Import Example providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_firewall_policy

### ISSUE THREAD

**Issue by dligthart** [hashicorp/terraform-provider-azurerm#19678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Wrong casing in import documentation:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_firewall_policy

`terraform import azurerm_cdn_frontdoor_firewall_policy.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourceGroup1/providers/Microsoft.Network/frontdoorWebApplicationFirewallPolicies/firewallPolicy1
`
should be

`terraform import azurerm_cdn_frontdoor_firewall_policy.example /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourceGroup1/providers/Microsoft.Network/frontDoorWebApplicationFirewallPolicies/firewallPolicy1`

### Terraform Version

1.1.0

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_firewall_policy

### Terraform Configuration Files

```hcl
not applicable
```

### Debug Output/Panic Output

```shell
ID was missing the `frontDoorWebApplicationFirewallPolicies` element
```

### Expected Behaviour

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

### Actual Behaviour

ID was missing the `frontDoorWebApplicationFirewallPolicies` element

### Steps to Reproduce

Run terraform import according to documentation

### Important Factoids

no

**Comment by WodansSon** [comment]
I am going to close this issue since this was fixed in the linked PR.
