### ISSUE TITLE
Please fix Kerberos for  azure_files_authentication

### ISSUE THREAD

**Issue by MrSnaffe** [hashicorp/terraform-provider-azurerm#19683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

 azure_files_authentication {
    directory_type = ""

Only AD and AADS is supported, AADKERB is not.

### New or Affected Resource(s)/Data Source(s)

azure_files_authentication under storage account creation

### Potential Terraform Configuration
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
}
azure_files_authentication {
    directory_type = "AADKERB"

active_directory {
domain_guid = 
domain_name =
domain_sid =
forest_name =
netbios_domain_name =
storage_sid =
}
}

**Comment by mybayern1974** [comment]
@MrSnaffe , could you please confirm whether this issue belongs to [Terraform AzureRM provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) that this repository focuses? It does not look like so since resource names of AzureRM provider started with `azurerm_` while the reported resource is named as `azure_`.

**Comment by MrSnaffe** [comment]
This is a setting under azurerm_storage_accounts, so yes its right.

Hämta Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
