### ISSUE TITLE
`azurerm_virtual_desktop_application_group` should force new on `host_pool_id` change

### ISSUE THREAD

**Issue by jrwesolo** [hashicorp/terraform-provider-azurerm#19687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_application_group

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "rg-example-virtualdesktop"
  location = "West Europe"
}

resource "azurerm_virtual_desktop_host_pool" "pooledbreadthfirst" {
  name                = "pooledbreadthfirst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type               = "Pooled"
  load_balancer_type = "BreadthFirst"
}

resource "azurerm_virtual_desktop_host_pool" "pooleddepthfirst" {
  name                = "pooleddepthfirst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type                             = "Personal"
  load_balancer_type               = "DepthFirst"
}

# Initially point app group to pooledbreadthfirst host pool
resource "azurerm_virtual_desktop_application_group" "remoteapp" {
  name                = "acctag"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type          = "RemoteApp"
  host_pool_id  = azurerm_virtual_desktop_host_pool.pooledbreadthfirst.id
  friendly_name = "TestAppGroup"
  description   = "Acceptance Test: An application group"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

I would expect the application group to change the host pool it is pointing at.

### Actual Behaviour

Host pool id is not updated on app group. It appears that this property is not editable and should be set to ForceNew in the [resource code](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/desktopvirtualization/virtual_desktop_application_group_resource.go#L81-L85). The [azure API for application groups](https://learn.microsoft.com/en-us/rest/api/desktopvirtualization/application-groups/update?tabs=HTTP) also does not appear to have a field to update the host pool id.

### Steps to Reproduce

1. `terraform apply`
2. Notice app group is pointing at pooledbreadthfirst host pool
3. Change app group host_pool_id to point at pooleddepthfirst host pool
4. `terraform apply`, notice TF detects the diff and applies change
5. Check azure portal and notice app group is still pointing at pooledbreadthfirst
6. Rerun `terraform apply` and see same diff in step 4

### References

https://learn.microsoft.com/en-us/rest/api/desktopvirtualization/application-groups/update?tabs=HTTP
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/desktopvirtualization/virtual_desktop_application_group_resource.go#L81-L85

**Comment by sinbai** [comment]
@jrwesolo thanks for opening this issue. I have submitted [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/19689)to fix it. Could you keep track of it for more updates?

**Comment by jrwesolo** [comment]
@sinbai thank you! I appreciate the quick response. I'll keep an eye on the PR.
