### ISSUE TITLE
azurerm_app_configuration_key bad request after moving to 3.36.0

### ISSUE THREAD

**Issue by krukowskid** [hashicorp/terraform-provider-azurerm#19711]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
locals {
  app_configuration = flatten([
    for label_key, config in var.app_configuration : [
      for entry_key, entry in config.values : {
        key   = entry_key
        value = entry
        label = config.label
        type  = config.type
      }
    ]
  ])
}

resource "azurerm_app_configuration_key" "this" {
  for_each               = { for entry in local.app_configuration : entry.key => entry }
  configuration_store_id = var.app_configuration_id
  key                    = "${var.app_configuration_key_prefix}:${each.value.key}"
  type                   = each.value.type
  label                  = each.value.label
  value                  = each.value.type == "kv" ? each.value.value : null
  vault_key_reference    = each.value.type == "vault" ? "${var.key_vault_uri}secrets/${each.value.value}" : null
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/krukowskid/a3a88c83657a0ed36cce66c0e4c6c90c
```

### Expected Behaviour

Configuration should be retrieved during refresh in terraform plan/apply like in previous version of module

### Actual Behaviour

error: while checking for key's "" existence: appconfiguration.BaseClient#GetKey
Value: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF

### Steps to Reproduce

terraform init
terraform plan

### Important Factoids

federated credentials auth

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/19470

**Comment by arkiaconsulting** [comment]
Git the same error after moving from 3.33.0 to 3.36.0

**Comment by ziyeqf** [comment]
Hi @krukowskid and @arkiaconsulting , sorry for introduced this bug, a pr (#19722) has been submitted to fix it.
