### ISSUE TITLE
Getting parse error for azurerm_app_configuration_key

### ISSUE THREAD

**Issue by harshithre** [hashicorp/terraform-provider-azurerm#19729]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration_key" "event_hub_namespace_springboot" {
  depends_on = [
    azurerm_eventhub_namespace.ehns
  ]
  configuration_store_id = var.app_config_id
  key                    = "/application/${local.eventHubConfigKey}.namespace"
  value                  = azurerm_eventhub_namespace.ehns.name
  label                  = var.environment // scoped to this environment
  tags                   = var.global_tags
}
```

### Debug Output/Panic Output

```shell
Error: while checking for key's "harshithpeddi" existence: appconfiguration.BaseClient#GetKeyValue: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: error response cannot be parsed: {"" '\x00' '\x00'} error: EOF
│ 
│   with module.product_secrets["applicationproductclient-id"].azurerm_app_configuration_key.config_key,
│   on modules/AppConfigVault/main.tf line 8, in resource "azurerm_app_configuration_key" "config_key":
│    8: resource "azurerm_app_configuration_key" "config_key" {
│ 
│ while checking for key's "harshithpeddi" existence:
│ appconfiguration.BaseClient#GetKeyValue: Failure responding to request:
│ StatusCode=400 -- Original Error: autorest/azure: error response cannot be
│ parsed: {"" '\x00' '\x00'} error: EOF
╵
```

### Expected Behaviour

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
╷

### Actual Behaviour

I tried to upgrade terraform provider version from 2.99 to 3.32 first it has run successfully but when i am again upgarded to 3.36 getting the parse error. 

### Steps to Reproduce

1. Terraform plan

### Important Factoids

Running the changes in AzureDevOps Pipeline

**Comment by ziyeqf** [comment]
Hi @harshithre, thanks for opening this issue.

there is an existing issue(#19711) for it and fixed in #19722. the fix pr has been merged and will be released soon, you can subscribe it to get notification.

For any further questions please leave comments.Thanks!
