### ISSUE TITLE
azurerm_hdinsight_kafka_cluster: nodes tagging

### ISSUE THREAD

**Issue by cristian98149** [hashicorp/terraform-provider-azurerm#19726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_hdinsight_kafka_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_hdinsight_kafka_cluster" "example" {
  name                = "example-hdicluster"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cluster_version     = "4.0"
  tier                = "Standard"

  component_version {
    kafka = "2.1"
  }

  gateway {
    username = "acctestusrgw"
    password = "TerrAform123!"
  }

  storage_account {
    storage_container_id = azurerm_storage_container.example.id
    storage_account_key  = azurerm_storage_account.example.primary_access_key
    is_default           = true
  }

  roles {
    head_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }

    worker_node {
      vm_size                  = "Standard_D3_V2"
      username                 = "acctestusrvm"
      password                 = "AccTestvdSC4daf986!"
      number_of_disks_per_node = 3
      target_instance_count    = 3
    }

    zookeeper_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }
  }
  tags = {
    env = "test"
  }
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

I was expecting that tags set to azurerm_hdinsight_kafka_cluster resource was also set to cluster nodes (head-node, zookeeper-node and worker-node).

### Actual Behaviour

Tags set to azurerm_hdinsight_kafka_cluster are just set to the service but not to the cluster nodes.

**Comment by jiaweitao001** [comment]
Hi @cristian98149, thanks for opening this issue! So far, hdinsight cluster supports tagging the service itself only, we're currently unable to tag the nodes for now.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
