### ISSUE TITLE
Head node and work node support script_actions list

### ISSUE THREAD

**Issue by chdzhangqi** [hashicorp/terraform-provider-azurerm#19724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need to config multi script actions in spark cluster for azure so that we can init our env

### New or Affected Resource(s)/Data Source(s)

azurerm_spark_cluster

**Comment by chdzhangqi** [comment]
@jiaweitao001 Could you provide the usage for mutil-script-actions in worker and head node? Thanks!!

**Comment by jiaweitao001** [comment]
Hi @chdzhangqi, thanks for opening this issue. Here is an example of how to set `script_actions` for head node. It can also apply to worker node.
```
head_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
      script_actions {
        name       = "scriptactiontest1"
        uri        = "exmaple-url-for-testing-1"
        parameters = "headnode"
      }
      script_actions {
        name       = "scriptactiontest2"
        uri        = "exmaple-url-for-testing-2"
        parameters = "headnode"
     }
    }
```

**Comment by chdzhangqi** [comment]
@jiaweitao001 Thanks!!!

**Comment by chdzhangqi** [comment]
Hi @jiaweitao001, another question: does spark cluster not support edge node?

**Comment by jiaweitao001** [comment]
@chdzhangqi , edge node is not supported by spark cluster.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @jiaweitao001‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
