### ISSUE TITLE
azurerm_logic_app_action_http doesn't allow a textual body, to support a "@concat() function" 

### ISSUE THREAD

**Issue by lmalmeida** [hashicorp/terraform-provider-azurerm#19728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_action_http

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_action_http" "sendwebhook" {
  name         = "send-webhook"
  logic_app_id = azurerm_logic_app_workflow.wf.id
  method       = "POST"
  uri          = "https://example.com/redacted"
  headers = {
    Content-Type = "application/json"
  }
  body = "@concat('{\"summary\": \"Foo\", \"text\": ',triggerBody()?['data']?['essentials']?['description'],'}')"

}
```

### Debug Output/Panic Output

```shell
╷
│ Error: "body" contains an invalid JSON: invalid character '@' looking for beginning of value
│
│   with azurerm_logic_app_action_http.sendwebhook,
│   on main.tf line 49, in resource "azurerm_logic_app_action_http" "sendwebhook":
│   49:   body = "@concat('{\"summary\": \"Foo\", \"text\": ',triggerBody()?['data']?['essentials']?['description'],'}')"
│
```

### Expected Behaviour

The provider should have passed through the body definition provided.
I can have in my actions:

```
"actions": {
            "send-webhook": {
                "inputs": {
                    "body": "@concat('{\"summary\": \"Foo\", \"text\": \"',triggerBody()?['data']?['essentials']?['description'],'\"}')",
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "method": "POST",
                    "uri": "https://example.com/redacted"
                },
                "runAfter": {},
                "type": "Http"
            }
```

### Actual Behaviour

It rejected the body provided, by doing a check that content is valid json

### Steps to Reproduce

Create an logic app action based on the code

```
resource "azurerm_logic_app_action_http" "sendwebhook" {
  name         = "send-webhook"
  logic_app_id = azurerm_logic_app_workflow.wf.id
  method       = "POST"
  uri          = "redacted"
  headers = {
    Content-Type = "application/json"
  }
  body = "@concat('{\"summary\": \"Foo\", \"text\": \"',triggerBody()?['data']?['essentials']?['description'],'\"}')"

}
```

**Comment by ziyeqf** [comment]
Hi @lmalmeida, thansk for opening the issue.

A pr (#19754) has been submitted to support this, you can subscribe it to get notification of progress.

For any further questions, please leave comments.
