### ISSUE TITLE
azurerm_automation_software_update_configuration - tags in target block have unexpected behavior

### ISSUE THREAD

**Issue by steini44as** [hashicorp/terraform-provider-azurerm#19739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
locals {
  currentDate          = timestamp()
  currentFormattedTime = formatdate("YYYY-MM-DD", local.currentDate)
  currentHour          = formatdate("hh", local.currentDate)
  nextDay              = timeadd(local.currentDate, "24h")
  nextDayFormattedTime = formatdate("YYYY-MM-DD", local.nextDay)
  startTime            = var.StartingHour > local.currentHour ? "${local.nextDayFormattedTime}T${format("%02d", var.StartingHour)}:00:00Z" : "${local.nextDayFormattedTime}T${format("%02d", var.StartingHour)}:00:00Z"
}

resource "azurerm_automation_software_update_configuration" "automation_software_update_configuration" {
  name                  = var.ResourceName
  automation_account_id = var.AutomationAccountObjectId
  operating_system      = var.OperatingSystem
  duration              = var.Duration

  dynamic "linux" {
    for_each = var.OperatingSystem == "Linux" ? [1] : []
    content {
      classification_included = join("",var.UpdateClassificationList)
      reboot                  = var.RebootSetting
    }
  }

  dynamic windows {
    for_each = var.OperatingSystem == "Windows" ? [1] : []
    content {
      classifications_included = var.UpdateClassificationList
      reboot                  = var.RebootSetting
    }
  }

  target {
    azure_query {
      scope = var.UpdateScopeList
      tags {
        tag = "UpdateSchedule"
        values = [ "${var.ResourceName}" ]
      }
      tag_filter = "All"
    }
  }

  schedule {
    frequency = var.Frequency
    interval  = var.Interval
    time_zone = "UTC"
    monthly_occurrence {
      day        = var.Day
      occurrence = var.NumberOfWeekInMonth
    }
    start_time = local.startTime
    expiry_time = "2023-01-01T11:00:00Z"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

To have the tags applied in the query, but I have 2 errors

### Actual Behaviour

1: if there is no tags provided within the target block, I got the following error:
`creating Software Update Configuration: (Name "wus-2nd-tue-0900-pm-rir" / Automation Account Name "aa-prd-shared-001" / Resource Group "gensio-rg-management-automation-dev-001"): automation.SoftwareUpdateConfigurationsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{"Message":"The request is invalid.","ModelState":{"softwareUpdateConfiguration.properties.updateConfiguration.targets.azureQueries[0].tagSettings.tags":["The tags field is required."]}}"`

In the documentation it says that it's optional within an Azure_query block: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_software_update_configuration#azure_query

2: If I add tags, I got the following error:
`creating Software Update Configuration: (Name "wus-2nd-tue-0900-pm-rir" /
│ Automation Account Name "aa-prd-shared-001" / Resource Group
│ "gensio-rg-management-automation-dev-001"):
│ automation.SoftwareUpdateConfigurationsClient#Create: Failure responding to
│ request: StatusCode=201 -- Original Error: Error occurred unmarshalling
│ JSON - Error = 'json: cannot unmarshal number into Go struct field
│ TagSettingsProperties.updateConfiguration.targets.azureQueries.tagSettings.filterOperator
│ of type automation.TagOperators' JSON =
│ '{"id":"/subscriptions/***/resourceGroups/gensio-rg-management-automation-dev-001/providers/Microsoft.Automation/automationAccounts/aa-prd-shared-001/softwareUpdateConfigurations/wus-2nd-tue-0900-pm-rir","name":"wus-2nd-tue-0900-pm-rir","type":null,"properties":{"updateConfiguration":{"operatingSystem":"Windows","windows":{"includedUpdateClassifications":"Critical,
│ Security","excludedKbNumbers":[],"includedKbNumbers":[],"rebootSetting":"IfRequired"},"linux":null,"targets":{"azureQueries":[{"scope":["/subscriptions/***"],"tagSettings":{"tags":{"UpdateSchedule":["wus-2nd-tue-0900-pm-rir"]},"filterOperator":0},"locations":[]}],"nonAzureQueries":null},"duration":"PT2H","azureVirtualMachines":null,"nonAzureComputerNames":null},"scheduleInfo":{"description":"","startTime":"2022-12-21T21:00:00+00:00","startTimeOffsetMinutes":0.0,"expiryTime":"2023-01-01T11:00:00+00:00","expiryTimeOffsetMinutes":0.0,"isEnabled":true,"nextRun":null,"nextRunOffsetMinutes":0.0,"interval":1,"frequency":"Month","creationTime":"2022-12-20T06:57:02.29+00:00","lastModifiedTime":"2022-12-20T06:57:02.29+00:00","timeZone":"Etc/UTC","advancedSchedule":{"monthDays":null,"monthlyOccurrences":[{"day":"Tuesday","occurrence":2}],"weekDays":null}},"provisioningState":"Provisioning","createdBy":"{scrubbed}","error":null,"tasks":{"preTask":null,"postTask":null},"creationTime":"2022-12-20T06:57:02.3+00:00","lastModifiedBy":null,"lastModifiedTime":"2022-12-20T06:57:02.33+00:00"}}'`

When checking the above json, I think the issue is with "filteroperator: 0"? This should be "All" or "Any". So it seems that it's not taking the tag_filter property:https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_software_update_configuration#tag_filter

In ARM templates, the "filterOperator": "All" works, so I assume the issue is there? or is this a bug or am I doing something wrong?

**Comment by wuxu92** [comment]
Hi @steini44as thanks for your feedback it's really important to address these issues. 

as for the first one, I am dropping a PR to make it work with no tags provided.

and for the second one, there is [an issue](https://github.com/Azure/azure-rest-api-specs/issues/21719) with the server API response, it responds with an integer for a string field. 

but I have fixed this issue in https://github.com/hashicorp/terraform-provider-azurerm/pull/19516/files and it should work fine from version v3.35.0 of azurerm. could you please check on your azurerm version or update to the latest version to have a try?

**Comment by steini44as** [comment]
Works great, thanks!
