### ISSUE TITLE
azurerm_automation_software_update_configuration - expiryTime is before startTime

### ISSUE THREAD

**Issue by steini44as** [hashicorp/terraform-provider-azurerm#19738]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
locals {
  currentDate          = timestamp()
  currentFormattedTime = formatdate("YYYY-MM-DD", local.currentDate)
  currentHour          = formatdate("hh", local.currentDate)
  nextDay              = timeadd(local.currentDate, "24h")
  nextDayFormattedTime = formatdate("YYYY-MM-DD", local.nextDay)
  startTime            = var.StartingHour > local.currentHour ? "${local.nextDayFormattedTime}T${format("%02d", var.StartingHour)}:00:00Z" : "${local.nextDayFormattedTime}T${format("%02d", var.StartingHour)}:00:00Z"
  #classifications = replace(replace(var.UpdateClassificationList,"[",""),"]","")
}

resource "azurerm_automation_software_update_configuration" "automation_software_update_configuration" {
  name                  = var.ResourceName
  automation_account_id = var.AutomationAccountObjectId
  operating_system      = var.OperatingSystem
  duration              = var.Duration

  dynamic "linux" {
    for_each = var.OperatingSystem == "Linux" ? [1] : []
    content {
      classification_included = join("",var.UpdateClassificationList)
      reboot                  = var.RebootSetting
    }
  }

  dynamic windows {
    for_each = var.OperatingSystem == "Windows" ? [1] : []
    content {
      classifications_included = var.UpdateClassificationList
      reboot                  = var.RebootSetting
    }
  }

  target {
    azure_query {
      scope = var.UpdateScopeList
      tags {
        tag = "UpdateSchedule"
        values = [ "${var.ResourceName}" ]
      }
    }
  }

  schedule {
    frequency = var.Frequency
    interval  = var.Interval
    time_zone = "UTC"
    monthly_occurrence {
      day        = var.Day
      occurrence = var.NumberOfWeekInMonth
    }
    start_time = local.startTime
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

when no expiry time is provided, the end time of the schedule should be far in the future or even never ending.

### Actual Behaviour

Error: creating Software Update Configuration: (Name "wus-2nd-tue-0900-pm-rir" /
│ Automation Account Name "aa-prd-shared-001" / Resource Group
│ "gensio-rg-management-automation-dev-001"):
│ automation.SoftwareUpdateConfigurationsClient#Create: Failure responding to
│ request: StatusCode=400 -- Original Error: autorest/azure: Service returned
│ an error. Status=400 Code="BadRequest" Message="Argument scheduleAllData
│ with value Orchestrator.Schedules.DataAccess.Models.ScheduleAllData is not
│ valid. Error message: expiryTime is before startTime"

**Comment by wuxu92** [comment]
hi @steini44as, thanks for your feedback it makes sense to add this feature to the `expiry_time` property, and I have dropped a PR to fix this. as a workaround could you please try to provide an expiry_time of far future to meet your requirement before this PR got merged.
