### ISSUE TITLE
Support for multiple dimensions in azurerm_monitor_metric_alert

### ISSUE THREAD

**Issue by jhthedev** [hashicorp/terraform-provider-azurerm#19744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the azure portal, it is possible to create multiple dimensions for one alert. This is very helpful to filter out unwanted namespaces or fine tune the alert. Now, as far as I know, the resource `azurerm_monitor_metric_alert` only takes one dimension block.

![Bildschirm­foto 2022-12-20 um 16 32 12](https://user-images.githubusercontent.com/3295998/208704736-db805490-77fb-41bb-87a1-ebf0bd8931e5.png)

If multiple dimensions are already supported, it would be nice to update the documentation to give an instruction.

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

**Comment by teowa** [comment]
Hi @jhthedev , thanks for submitting this issue!
From [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert#dimension): 
> A criteria block supports the following:
&nbsp;&nbsp;&nbsp;&nbsp;... 
&nbsp;&nbsp;&nbsp;&nbsp;[dimension](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert#dimension) - (Optional) One or more dimension blocks as defined below.

So we can define multiple dimensions like:
```hcl
criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts"
    metric_name      = "Transactions"
    aggregation      = "Total"
    operator         = "GreaterThan"
    threshold        = 50

    dimension {
      name     = "dim1"
      operator = "Include"
      values   = ["*"]
    }
    dimension {
      name     = "dim2"
      operator = "Include"
      values   = ["*"]
    }
  }
```
Hope this may help.

**Comment by jhthedev** [comment]
Hi @teowa , thanks for the quick reply. I must have overlooked this line. I will close this issue now, thanks!
