### ISSUE TITLE
Could not apply azurerm_maintenance_assignment_virtual_machine when maintenance configuration contains maintenanceScope    = "InGuestPatch"

### ISSUE THREAD

**Issue by rob31231232** [hashicorp/terraform-provider-azurerm#19747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.36

### Affected Resource(s)/Data Source(s)

azurerm_maintenance_assignment_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_maintenance_assignment_virtual_machine" "example" {
  location                     = azurerm_resource_group.resource_group.location
  maintenance_configuration_id = data.azurerm_maintenance_configuration.patch_window.id
  virtual_machine_id           = azurerm_windows_virtual_machine.virtual_machine.id
}


Json value of the maintenance configuration which will be mounted by the code above:

{
    "location": "westeurope",
    "properties": {
        "namespace": "Microsoft.Maintenance",
        "extensionProperties": {
            "inGuestPatchMode": "User"
        },
        "maintenanceScope": "InGuestPatch",
        "maintenanceWindow": {
            "startDateTime": "2022-12-03 01:00",
            "duration": "03:00",
            "timeZone": "W. Europe Standard Time",
            "recurEvery": "3Hour"
        },
        "visibility": "Custom",
        "configurationType": "Regular"
    },
    "id": "/subscriptions/<subscription_id>/resourcegroups/<RG_Name>/providers/microsoft.maintenance/maintenanceconfigurations/definition_updates",
    "name": "Definition_Updates",
    "type": "Microsoft.Maintenance/maintenanceConfigurations"
}
```

### Debug Output/Panic Output

```shell
Error: issuing creating request for Maintenance Assignment (virtual machine ID "/subscriptions/<subscription_id>/resourceGroups/<RG_Name>/providers/Microsoft.Compute/virtualMachines/<VM_Name>"): configurationassignments.ConfigurationAssignmentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedResourceOperation" Message="Invalid Maintenance Scope. Resource: /subscriptions/<ID>/resourcegroups/<RG_Name>/providers/microsoft.compute/virtualmachines/<VM_Name>"
│ 
│   with module.virtualmachine["vm2"].azurerm_maintenance_assignment_virtual_machine.example,
│   on VM/maintenance_assignment.tf line 7, in resource "azurerm_maintenance_assignment_virtual_machine" "example":
│    7: resource "azurerm_maintenance_assignment_virtual_machine" "example" {
│
```

### Expected Behaviour

Maintenance configuration should be mounted to the VM. But this fails when the maintenance configuration has a Maintenance Scope with the value "InGuestPatch".

### Actual Behaviour

Applying of Terraform code fails with error:

Error: issuing creating request for Maintenance Assignment (virtual machine ID "/subscriptions/<subscription_id>/resourceGroups/<RG_Name>/providers/Microsoft.Compute/virtualMachines/<VM_Name>"): configurationassignments.ConfigurationAssignmentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedResourceOperation" Message="Invalid Maintenance Scope. Resource: /subscriptions/<ID>/resourcegroups/<RG_Name>/providers/microsoft.compute/virtualmachines/<VM_Name>"
│ 
│   with module.virtualmachine["vm2"].azurerm_maintenance_assignment_virtual_machine.example,
│   on VM/maintenance_assignment.tf line 7, in resource "azurerm_maintenance_assignment_virtual_machine" "example":
│    7: resource "azurerm_maintenance_assignment_virtual_machine" "example" {
│

### References

https://discuss.hashicorp.com/t/unable-to-configure-maintenance-configuration-for-patching/45304

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Per the error message returned by API, seems service API doesn't support the maintenanceScope you provided.

**Comment by rob31231232** [comment]
It's indeed an API error message. But it's working when you assign the (same) maintenance configuration with azapi_resource:

```
resource "azapi_resource" "vm_maintenance_assignment" {
  type      = "Microsoft.Maintenance/configurationAssignments@2021-09-01-preview"
  name      = "${azurerm_windows_virtual_machine.virtual_machine.name}-mca"
  parent_id = azurerm_windows_virtual_machine.virtual_machine.id
  location  = azurerm_resource_group.resource_group.location
  
  body = jsonencode({
    properties = {
      maintenanceConfigurationId = data.azurerm_maintenance_configuration.patch_window.id
    }
  })
}
```

So in my view it is possible. 

The creation of a maintanance configuration also failed, see issue https://github.com/hashicorp/terraform-provider-azurerm/issues/19790. But that issue is almost solved (waiting for the PR) https://github.com/hashicorp/terraform-provider-azurerm/pull/19865. 

@ziyeqf what is your view on this issue?

**Comment by ziyeqf** [comment]
Hi @rob31231232,  I assume it may need a API upgration on provider, let me give a try.
