### ISSUE TITLE
"Error: ID was missing the `certificates` element" , when referencing `data.azurerm_app_service_certificate_order` for `certificate_id`

### ISSUE THREAD

**Issue by samgovier** [hashicorp/terraform-provider-azurerm#19746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

`azurerm_app_service_certificate_binding` , `azurerm_app_service_certificate_order` 

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate_binding" "cert-binding-example" {
  certificate_id      = data.azurerm_app_service_certificate_order.example-cert.id
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.example-hostname-binding.id
  ssl_state           = "SniEnabled"
}

data "azurerm_app_service_certificate_order" "example-cert" {
  name                = "example"
  resource_group_name = "exampleRG"
}

# provided here to help reproduction
resource "azurerm_app_service_custom_hostname_binding" "example-hostname-binding" {
  hostname            = "example.test.com"
  app_service_name    = "test-app-service"
  resource_group_name = "exampleRG"
}
```

### Debug Output/Panic Output

```shell
Error on `terraform plan` run: "Error: ID was missing the `certificates` element"
---
Payload of the `management.azure.com` API request for `data.azurerm_app_service_certificate_order` (trimmed for security):

{
    "id": "/subscriptions/xxx/resourceGroups/exampleAppServiceCertificates/providers/Microsoft.CertificateRegistration/certificateOrders/wildcard",
    "name": "wildcard",
    "type": "Microsoft.CertificateRegistration/certificateOrders",
    "location": "global",
    "tags": {
        "Business Unit": "example",
        "Environment": "Production"
    },
    "properties": {
        "certificates": {
            "wildcard": {
                "keyVaultId": "/subscriptions/xxx/resourcegroups/support/providers/microsoft.keyvault/vaults/keyvault2",
                "keyVaultSecretName": "xxx",
                "provisioningState": "Succeeded"
            }
        }
    }
}

---
Let me know if more debug output is needed.
```

### Expected Behaviour

This should bind the pulled certificate to the custom hostname provided for the app service.

### Actual Behaviour

I got an error that the `certificates` element is missing. Taking a look at the payload of the data, I suspect this happened because the `certificates` element is buried under `properties`.

### References

I suspect [this PR](https://github.com/hashicorp/terraform-provider-azurerm/issues/11657) may be related.

**Comment by xiaxyi** [comment]
Thanks @samgovier for raising this issue, as the error mentions, you may need to use certificate id not the certificate order id. Can you try using certificate id for the binding?

**Comment by samgovier** [comment]
I did some more investigation into the environment I was creating; it seems like `certificate_order` objects are used to create `Microsoft.Web/certificates` objects that the App Service(s) use, and so Certificate Orders can't bind directly to a hostname. I had to create an `azurerm_app_service_certificate` object. The following code worked for me. Thank you @xiaxyi !

```hcl
resource "azurerm_app_service_certificate_binding" "cert-binding-example" {
  # certificate_id      = data.azurerm_app_service_certificate_order.example-cert.id
  certificate_id      = azurerm_app_service_certificate.example-app-cert.id
  hostname_binding_id = azurerm_app_service_custom_hostname_binding.example-hostname-binding.id
  ssl_state           = "SniEnabled"
}

## Not used for creating a certificate object
# data "azurerm_app_service_certificate_order" "example-cert" {
#   name                = "example"
#   resource_group_name = "exampleRG"
# }

resource "azurerm_app_service_custom_hostname_binding" "example-hostname-binding" {
  hostname            = "example.test.com"
  app_service_name    = "test-app-service"
  resource_group_name = "exampleRG"
}

###

resource "azurerm_app_service_certificate" "example-app-cert" {
  name                = "cert-exampleRG-webspace"
  resource_group_name = "exampleRG"
  location            = "eastus2"
  key_vault_secret_id = data.azurerm_key_vault_secret.example-cert-secret.id
}

data "azurerm_key_vault" "example-keyvault" {
  name                = "ExampleKeyVault"
  resource_group_name = "exampleRG"
}

data "azurerm_key_vault_secret" "example-cert-secret" {
  name         = "certificate_order_x-pkcs12_secret"
  key_vault_id = data.azurerm_key_vault.example-keyvault.id
}
```
