### ISSUE TITLE
Potential discrepancy between `container_log_max_line` config name and `ContainerLogMaxFiles` config value 

### ISSUE THREAD

**Issue by btiernay** [hashicorp/terraform-provider-azurerm#19745]
## Context

I was browsing through the code and just happened to notice this discrepancy:

https://github.com/hashicorp/terraform-provider-azurerm/blob/5c310f03a5f4dc7fc2a48c3248e227d02e45d528/internal/services/containers/kubernetes_cluster_node_pool_resource.go#L1031-L1032

From [the docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#container_log_max_line):

> [container_log_max_line](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#container_log_max_line) - (Optional) Specifies the maximum number of container log files that can be present for a container. must be at least 2. Changing this forces a new resource to be created.

It appears to be swapped. 

## Suggestion

Suggest fixing `container_log_max_line` and adding `container_log_max_files` configuration values, which today is unsupported.

**Comment by ms-henglu** [comment]
Hi @btiernay ,

Thank you for taking time to report this issue!

I've made a PR to add todo item to rename this field in v4.0.

**Comment by btiernay** [comment]
Thank you! Is there an item to update the docs as well? The concern is that they are speaking to a completely different property.
