### ISSUE TITLE
azurerm_sql_database.webdb: Error setting database threat detection policy

### ISSUE THREAD

**Issue by seitosan** [hashicorp/terraform-provider-azurerm#1974]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

Hello, 
When i try to apply threat_detection_policy on sql-azure database, i reach an issue.

### Terraform Version
```
terraform -v
Terraform v0.11.7
+ provider.azurerm v1.15.0
```

### Affected Resource(s)

* azurerm_sql_database

### Terraform Configuration Files

```hcl
resource "azurerm_sql_database" "webdb" {
  name                = "sql-${random_id.sqlnameId.hex}-web-db"
  resource_group_name = "${azurerm_resource_group.mainRG.name}"
  location            = "${azurerm_resource_group.mainRG.location}"
  server_name         = "${azurerm_sql_server.srv_sql.name}"
  edition             = "Standard"

  threat_detection_policy {
    state = "Enabled"
  }


}
```

### Debug Output

azurerm_sql_database.webdb: Error setting database threat detection policy: sql.DatabaseThreatDetectionPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {} 

### Steps to Reproduce

1. `terraform apply`

**Comment by jameswhinn** [comment]
I also have this issue on the following versions:
Terraform v0.11.10
+ provider.azurerm v1.19.0

**Comment by AresiusXP** [comment]
I have the same issue. 

Here's my code:
```
resource "azurerm_sql_database" "sqlDatamartDB" {
  name                             = "${var.nameenv == "D" ? "DEV" : var.nameenv == "Q" ? "QA" :var.nameenv == "E" ? "Demo" : upper(var.nameenv)}"
  resource_group_name              = "${var.resource_group_name}"
  location                         = "${var.resource_group_location}"
  server_name                      = "${var.sql_server_name}"
  edition                          = "Standard"
  requested_service_objective_name = "S3"

  threat_detection_policy {
    state = "New"
    retention_days = "10"
    storage_account_access_key = "${var.storage_account_primary_access_key}"
    storage_endpoint = "${var.storage_account_primary_blob_endpoint}"
  }
}```

Terraform v0.11.10
* provider.azurerm: version = "~> 1.19"

**Comment by AresiusXP** [comment]
Thanks for the info.

After some testing, I found that the field giving errors is `email_addresses`. Lack of this field throws an error. There's no way to implement Threat Detection Policy without this field being filled. However, [documentation](https://www.terraform.io/docs/providers/azurerm/r/sql_database.html#email_addresses) states that it's optional. 

Either documentation should be changed, or some fix is needed.


As a byproduct of this issue, there should also be a fix for error management for this setting. Main problem we had is that the error is not being thrown correctly. There's no descriptive error message because there's an unmarshal error with `sql.DatabaseThreatDetectionPoliciesClient#CreateOrUpdate`.

**Comment by seitosan** [comment]
hello @AresiusXP  

 
I can propose this modification in a PR so that others do not have this problem

best  regards

**Comment by AresiusXP** [comment]
Sure, if you think that'll help, I'm all for it. Thank you!

**Comment by jlucktay** [comment]
> After some testing, I found that the field giving errors is `email_addresses`. Lack of this field throws an error. There's no way to implement Threat Detection Policy without this field being filled.

Populating `email_addresses` worked for me and applied the plan successfully. Thanks!

**Comment by chfrodin** [comment]
Hello everyone.

While building a Azure SQL Module I stumbled upon the same erroras this issue details.
But for one thing, even when populating my email_addresses variable with a list, I still encounter the issue.

Config:
Terraform v0.12.2
+ provider.azurerm v1.30.1

variable "email_addresses" {
  description = "A list of email addresses which alerts should be sent to."
  type = list(any)
}

resource "azurerm_sql_database" "sql" {
 ....

    threat_detection_policy {
      state                      = var.state
      email_account_admins       = var.email_account_admins
      email_addresses            = var.email_addresses
      retention_days             = var.retention_days
      storage_account_access_key = var.storage_account_access_key
      storage_endpoint           = var.storage_endpoint
      use_server_default        = var.use_server_default

    }
}

system.auto.tfvars
email_addresses            = ["asdf@asdf.com",]


error:
Error: Error setting database threat detection policy: sql.DatabaseThreatDetectionPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}

**Comment by davidtom** [comment]
Like @chfrodin, I am also running into this same error still. Any updates on this??

**Comment by nezoic** [comment]
Just ran into this issue myself, any updates?

**Comment by mikemowgli** [comment]
Same here. I didn't get this issue as long as only one email address was in this list. As soon as I added another one, the error popped up. I'm using tf 0.14.3 and azurerm 2.41.0.

**Comment by mikemowgli** [comment]
@yupwei68 is this something you could kindly look into?

**Comment by seitosan** [comment]
Hello, 

In my case i have finally solved this issue by use the following code  : 

```
Hello dude,

I solved it, with this version and with this code :

Terraform v0.11.10
+ provider.azurerm v1.19.0
 threat_detection_policy = {
    state                      = "Enabled"
    email_addresses            = "${var.threat_email_notification}"
    storage_endpoint           = "${azurerm_storage_account.threat.primary_blob_endpoint}"
    storage_account_access_key = "${azurerm_storage_account.threat.secondary_access_key}"
    retention_days             = "${var.threat_retention_logs}"
  }
Tell me if it's works for you.

```

**Comment by favoretti** [comment]
I've just re-tested this on the latest version, seems to work just fine, ran an acceptance test:
```
$ TF_ACC=1 go test -v ./internal/services/sql -timeout=1000m -run='TestAccSqlDatabase_threatDetectionPolicy'
=== RUN   TestAccSqlDatabase_threatDetectionPolicy
=== PAUSE TestAccSqlDatabase_threatDetectionPolicy
=== CONT  TestAccSqlDatabase_threatDetectionPolicy
--- PASS: TestAccSqlDatabase_threatDetectionPolicy (379.94s)
PASS
ok  	github.com/hashicorp/terraform-provider-azurerm/internal/services/sql	381.213s
```

Used the following config:
```
resource "azurerm_sql_database" "test" {
  name                = "acctestdb%d"
  resource_group_name = azurerm_resource_group.test.name
  server_name         = azurerm_sql_server.test.name
  location            = azurerm_resource_group.test.location
  edition             = "Standard"
  collation           = "SQL_Latin1_General_CP1_CI_AS"
  max_size_bytes      = "1073741824"

  threat_detection_policy {
    retention_days             = 15
    state                      = "%s"
    disabled_alerts            = ["Sql_Injection"]
    email_account_admins       = "Enabled"
    email_addresses            = ["1@alerting.com", "2@alerting.com"]
    storage_account_access_key = azurerm_storage_account.test.primary_access_key
    storage_endpoint           = azurerm_storage_account.test.primary_blob_endpoint
  }
}
```

Closing this. Please reopen if still relevant.
