### ISSUE TITLE
Don't delete azurerm_cdn_frontdoor_security_policy when adding a new domain association

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform-provider-azurerm#19761]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A Front Door Security Policy could be associated to multiples domain, when adding a new domain to an existing security policy it would be great not to delete it.

![image](https://user-images.githubusercontent.com/18073917/208868469-40c97dad-b993-4874-bfa6-f988898b3564.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_security_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_frontdoor_security_policy" "fd_security_policy_dedicated" {
  for_each                 = { for x, y in var.fd_firewall_policy : x => y if lookup(y, "default", false) == true ? false : true }
  name                     = "${var.domain}${lookup(each.value, "env", var.env)}${each.value["role"]}fdsec${each.value["instance"]}"
  cdn_frontdoor_profile_id = local.fd[each.value.fd_key].id

  security_policies {
    firewall {
      cdn_frontdoor_firewall_policy_id = replace(azurerm_cdn_frontdoor_firewall_policy.fd_firewall_policy[each.key].id, "frontdoorWebApplicationFirewallPolicies", "frontDoorWebApplicationFirewallPolicies")

      association {
        dynamic "domain" {
          for_each = { for x, y in var.fd_managed_route : x => azurerm_cdn_frontdoor_custom_domain.fd_endpoint_custom_domain[x] if lookup(y, "fd_firewall_policy_key", null) == null ? false : true }
          content {
            cdn_frontdoor_domain_id = domain.value.id
          }
        }
        patterns_to_match = ["/*"] #(Required) The list of paths to match for this firewall policy. Possible value includes /*. Changing this forces a new Front Door Security Policy to be created.
      }
    }
  }
}
```

**Comment by WodansSon** [comment]
@JamesDLD, thank you for opening this issue, however this is not possible at this time as the API currently does not support the Update operation on the resource, so this is currently by design.
