### ISSUE TITLE
Remove first Note from azurerm_hpc_cache page

### ISSUE THREAD

**Issue by swpepin** [hashicorp/terraform-provider-azurerm#19766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now, there's a Note on the hpc_cache page talking about the first several months of GA for this service, which is far outdated. It also includes a broken link. The request is to take down this note. I don't know how to make this request so I'm trying this medium. If this isn't correct or there's another forum by which to make this request, please let me know. 

### New or Affected Resource(s)/Data Source(s)

azurerm_hpc_cache

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hpc_cache

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. For usage question, suggest to file the issue on https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34 if it's possible. Thanks.

![image](https://user-images.githubusercontent.com/19754191/209046954-404c5c20-a5e3-4f13-a1e8-074667ac7b37.png)

**Comment by tombuildsstuff** [comment]
hey @swpepin 

Thanks for reporting this, I've tagged this as a documentation bug so that we can get this fixed 👍 

Thanks!

**Comment by rcskosir** [comment]
@swpepin Thank you for raising this issue and @McGon-Fid thank you for creating the fix for this issue. Since #19974 has been merged, I am going to mark this issue as closed.
