### ISSUE TITLE
Terraform not able to create a resource referencing a new attribute on an existing resource that will be referenced.

### ISSUE THREAD

**Issue by b1ackhawk-uh60** [hashicorp/terraform-provider-azurerm#19764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_access_policy azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "webapp1" {
  name                = "app-web-myapp-test3"
  resource_group_name = azurerm_resource_group.secondary_rg.name
  location            = azurerm_resource_group.secondary_rg.location
  service_plan_id     = data.terraform_remote_state.shared_resources.outputs.primary_plan_id
  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on = false
  }
}


resource "azurerm_key_vault_access_policy" "secondary_policy" {
  key_vault_id = data.terraform_remote_state.shared_resources.outputs.primary_vault_id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id          = azurerm_linux_web_app.webapp1.identity.0.principal_id
  secret_permissions = ["Get", ]
     depends_on = [
      azurerm_linux_web_app.webapp1
     ]
}
```

### Debug Output/Panic Output

```shell
"The argument "object_id" is required, but no definition was found."
```

### Expected Behaviour

When running from scratch (no existing resources) it runs as expected, the web app is created along with the managed identity, that managed identity is used for the key vault access policy, which is created.
However, in my actual use case, I have an existing web app without a managed identity, so the identity must be created for the existing web app resource and then the policy can be created (Expected).

### Actual Behaviour

In the case of an existing web app that needs to have a managed identity created:
Plan/Apply fails with error "The argument "object_id" is required, but no definition was found."
Terraform apparently tries to obtain the principal_id but seems to find a null value (perhaps it should be a (known after apply) scenario).
Dependency I believe is implicit, but even explicitly stating it, it only looks to see if the resource exists (which it does in this case) and will not look at an attribute of the resource (in this case the principal_id). Attempting to append ".identity" or something of that sort will result in error.

### Steps to Reproduce

terraform apply
or 
terraform plan

### Important Factoids

I don't think so

**Comment by xiaxyi** [comment]
Thanks @b1ackhawk-uh60 for raising this issue. Based on my understanding, you have an existed app service instance which doesn't have system managed identity enabled. Now you would like to enable the system assigned identity and create a key vault access policy along with it, but failed with the "null object id" error, right?

**Comment by xiaxyi** [comment]
The current work around is to use data source as mentioned in this issue:https://github.com/hashicorp/terraform-provider-azurerm/issues/19316 

let me know if you have any questions.

**Comment by b1ackhawk-uh60** [comment]
Thank you @xiaxyi, I tested that work around on the webapp, it works. Not optimal, but it will do. I appreciate the assist.
