### ISSUE TITLE
terraform fails to execute(re-run) if azure_batch_pool is deleted outside of terraform

### ISSUE THREAD

**Issue by meghdivya** [hashicorp/terraform-provider-azurerm#19770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.36.0

### Affected Resource(s)/Data Source(s)

azurerm_batch_pool

### Terraform Configuration Files

```hcl
locals {
   rg_name = "test-rg"
   location = "CentralIndia"
}

data "azurerm_storage_account" "example" {
  name                = "example"
  resource_group_name = local.rg_name
}

resource "azurerm_batch_account" "example" {
  name                 = "testbatchaccount"
  resource_group_name  = local.rg_name
  location             = local.location
  pool_allocation_mode = "BatchService"
}

resource "azurerm_batch_pool" "example" {
  name                = "testaccpool"
  resource_group_name = local.rg_name
  account_name        = azurerm_batch_account.example.name
  display_name        = "Test Acc Pool Auto"
  vm_size             = "Standard_A1"
  node_agent_sku_id   = "batch.node.ubuntu 20.04"
  storage_image_reference {
    publisher = "microsoft-azure-batch"
    offer     = "ubuntu-server-container"
    sku       = "20-04-lts"
    version   = "latest"
  }
  fixed_scale {
   node_deallocation_method = "Terminate"
  }

}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Pool: (Name "testaccpool" / Batch Account Name "testbatchaccount" / Resource Group "test-adf") was not found
│
│   with azurerm_batch_pool.example,
│   on adf.tf line 33, in resource "azurerm_batch_pool" "example":
│   33: resource "azurerm_batch_pool" "example" {
│
╵
```

### Expected Behaviour

Terraform should create a new batch pool if it's not existing.

### Actual Behaviour

Terraform fails to execute in the creation of the azure batch pool again, if it was deleted externally and not from the terraform destroy.

### Steps to Reproduce

1. terraform apply
2. Delete the azure batch pool from the azure portal
3. terraform apply

**Comment by sinbai** [comment]
@meghdivya thanks for opening this issue. I have submitted [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/19780)to fix this issue. Could you track it for more updates?
