### ISSUE TITLE
azurerm_key_vault_secret documentation Arguments Reference correction

### ISSUE THREAD

**Issue by garyGoDev** [hashicorp/terraform-provider-azurerm#19785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13+

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

Data Source: azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### Steps to Reproduce

Browse to [Arguments Reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secret#arguments-reference)

### References

With regards to [Arguments Reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secret#arguments-reference)

# Current
key_vault_id - (Required) The ID of the TODO.
name - (Required) Specifies the ID of the Key Vault instance where the Secret resides, available on the azurerm_key_vault Data Source / Resource.

# Expected
key_vault_id - (Required) Specifies the ID of the Key Vault instance where the Secret resides, available on the azurerm_key_vault Data Source / Resource.
name - (Required) Specifies the name of the Key Vault Secret to be exported.

**Comment by sinbai** [comment]
@garyGoDev thanks for opening this issue. I have submitted [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/19787)to fix it.
