### ISSUE TITLE
'azurerm_policy_definition' data lookup not working as intended

### ISSUE THREAD

**Issue by jf781** [hashicorp/terraform-provider-azurerm#19783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.31.0

### Affected Resource(s)/Data Source(s)

azurerm_policy_definition

### Terraform Configuration Files

```hcl
data "azurerm_policy_definition" "example" {
  display_name = "Allowed resource types"
}

output "id" {
  value = data.azurerm_policy_definition.example.id
}
```

### Debug Output/Panic Output

```shell
[ERROR] vertex "data.azurerm_policy_definition.example (expand)" error: reading Policy Definition (Display Name "Allowed resource types"): loading Policy Definition List: policy.DefinitionsClient#listNextResults: Failure responding to next results request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field DefinitionListResult.value of type bool'
```

### Expected Behaviour

It would provide the built in policy definition ID

### Actual Behaviour

```bash
terraform plan
data.azurerm_policy_definition.example: Reading...
╷
```

### Steps to Reproduce

```hcl
terraform plan
```

### Important Factoids

I have tried using different using the latest AzureRM Provider (3.37.0) and Terraform (1.3.6) but the results are the same. 

If use `name` instead of `display_name` it will work providing you supply the built-in policy name instead of display name.

This also appears to be fairly new because I was able to use the same code previously to look up built-in policies but something changed within the month that is now causing this issue.

**Comment by wuxu92** [comment]
Hi @jf781 thanks for your feedback. i have tried with your configuration and it output the policy definition id correctly.

![image](https://user-images.githubusercontent.com/2633022/209263677-4737295d-03af-42ff-bf45-8662a8ee92da.png)


 i wonder if there are any other special configuration on your subscription? and could you please have a try with `name` property as below? it should retrieve the same policy definition for you.

```hcl
data "azurerm_policy_definition" "example" {
  name = "a08ec900-254a-4555-9bf5-e42af04b5c5c"
}

output "id" {
  value = data.azurerm_policy_definition.example.id
}
```

**Comment by jf781** [comment]
Hi @wuxu92  - Thanks for taking a look.     

When I utilize the `name` property it works as intended.   For some reason it's just the `display_name` property that is causing an issue.  I searched through the policies and ensured there are not any that have duplicate display names and have also tried to reference multiple policies to no avail. 

Is there anything else I can provide that would helpful to identify what is causing the lookup to fail.

**Comment by wuxu92** [comment]
could you please  run `terraform plan` again with environment TF_LOG=DEBUG to see more logs. reference here for more information https://developer.hashicorp.com/terraform/internals/debugging.

**Comment by jf781** [comment]
Hi @wuxu92  - This is the output from TF plan with debugging enabled. 

```bash
[ERROR] vertex "data.azurerm_policy_definition.example (expand)" error: reading Policy Definition (Display Name "Allowed resource types"): loading Policy Definition List: policy.DefinitionsClient#listNextResults: Failure responding to next results request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'json: cannot unmarshal string into Go struct field DefinitionListResult.value of type bool'
```

**Comment by jf781** [comment]
Hi @wuxu92  - I was reviewing the full error message and saw there were some policies defined that have a parameter type of `bool` instead of `boolean`.  However those were built in policies, not any custom policies.   

For example `"Configure diagnostic settings for Azure Machine Learning workspace to Log Analytics workspace"` has both `metricsEnabled` and `logsEnabled` parameter type value set to `bool`.  

Not sure if that helps or make sense.  

Please let me know if there is anything else I can provide that would be helpful.

**Comment by wuxu92** [comment]
Hi @jf781 it looks like not related to the parameter type. Are there particular custom policy definitions that cause this issue? I add a policy_type property support of policy definition data source in the branch https://github.com/wuxu92/terraform-provider-azurerm/tree/policyds/builtin . could you please build this branch and use it as azurerm provider to see if it works?


```
data "azurerm_policy_definition" "example" {
  display_name = "Allowed resource types"
  policy_type = "BuiltIn"
}

output "id" {
  value = data.azurerm_policy_definition.example.id
}
```
