### ISSUE TITLE
Support for specifying the notification email address when the daily data volume cap is met for `azurerm_application_insights`.

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-provider-azurerm#19788]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Under [application_insights](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights) module, we have the options to enable notification email when the daily data volume cap is met by setting [daily_data_cap_notifications_disabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights#daily_data_cap_notifications_disabled) argument to `false`.

How do we specify the notification email address (e.g. example@example.org) when the daily data volume cap is met?

### New or Affected Resource(s)/Data Source(s)

azurerm_application_insights

### Potential Terraform Configuration

```hcl
resource "azurerm_application_insights" "example" {
  daily_data_cap_in_gb = 0.2
  daily_data_cap_notifications_disabled = false
  daily_data_cap_notifications_email = "example@example.org"
}
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. After checked [Azure Rest API](https://github.com/Azure/azure-rest-api-specs/blob/89a9bf17524904e7670f0fd2d62ac882ca00d85c/specification/applicationinsights/resource-manager/Microsoft.Insights/stable/2015-05-01/componentFeaturesAndPricing_API.json#L228), seems service API doesn't support the feature you mentioned. So it's service API limitation.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
