### ISSUE TITLE
tf plan of azurerm_role_definition does not complain about bad actions

### ISSUE THREAD

**Issue by mpw96** [hashicorp/terraform-provider-azurerm#19784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_role_definition

### Terraform Configuration Files

```hcl
+ resource "azurerm_role_definition" "test" {
       + assignable_scopes           = [
           + "/subscriptions/23169dd7-f4ca-4962-b59f-62709b0c81e4",
         ]
       + id                          = (known after apply)
       + name                        = "test"
       + role_definition_id          = (known after apply)
       + role_definition_resource_id = (known after apply)
       + scope                       = "/subscriptions/23169dd7-f4ca-4962-b59f-62709b0c81e4"
 
       + permissions {
           + actions      = [
               + "Microsoft.ResourceHealth/events/read",
               + "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read",
               + "Microsoft.Storage/storageAccounts/blobServices/containers/read",
             ]
           + data_actions = [
               + "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/*",
             ]
           + not_actions  = []
         }
     }
```

### Debug Output/Panic Output

```shell
+ resource "azurerm_role_definition" "test" {
       + assignable_scopes           = [
           + "/subscriptions/23169dd7-f4ca-4962-b59f-62709b0c81e4",
         ]
       + id                          = (known after apply)
       + name                        = "test"
       + role_definition_id          = (known after apply)
       + role_definition_resource_id = (known after apply)
       + scope                       = "/subscriptions/23169dd7-f4ca-4962-b59f-62709b0c81e4"
 
       + permissions {
           + actions      = [
               + "Microsoft.ResourceHealth/events/read",
               + "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read",
               + "Microsoft.Storage/storageAccounts/blobServices/containers/read",
             ]
           + data_actions = [
               + "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/*",
             ]
           + not_actions  = []
         }
     }
```

### Expected Behaviour

The **terraform plan** call, of which you see the output above, should fail. Because the action `Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read` is actually a `data_action`, but we put it into the `actions`list.

Microsoft has [documented](https://learn.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations#microsoftstorage) which actions and which data_actions are possbile.

### Actual Behaviour

The **terraform plan** call succeeded, but the **terraform apply** call later failed (which is actually too late in my environment):
```
Error: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidActionOrNotAction" Message="'Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read' does not match any of the actions supported by the providers."
```

**Comment by wuxu92** [comment]
Hi @mpw96, thanks for your feedback. it is a good suggestion to add this validator, but it's not terraform-provider-azurerm's knowledge of this full list of action/data_action in the document. so azurerm may not add it eventually.

**Comment by manicminer** [comment]
Thanks for requesting this @mpw96. As we can only validate these by submitting them to the API, you will only get an error for these at apply time. As @wuxu92 mentioned, it's unfortunately not practical for Terraform to self-validate role permissions at plan time, as we would be just as likely to get it wrong, and it would be an undue maintenance burden to keep this up to date. Accordingly, I'm going to close this issue for now as I believe it's unlikely we will be able to validate these effectively.
