### ISSUE TITLE
PostgreSQL Firewall rule name not allowing string type value with space

### ISSUE THREAD

**Issue by a-z-i-z** [hashicorp/terraform-provider-azurerm#19796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_firewall_rule

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server_firewall_rule" "postgresql_server_firewall_rule" {
  name             = "Allow inbound access from Specific IP"
  server_id        = azurerm_postgresql_flexible_server.postgresql_server.id
  start_ip_address = "x.x.x.x"
  end_ip_address   = "x.x.x.x"
}
```

### Debug Output/Panic Output

```shell
│ Error: "name" must only contains numbers, characters and `-`, `_`, got Allow inbound access from Specific IP
│
│   with azurerm_postgresql_flexible_server_firewall_rule.postgresql_server_firewall_rule,
│   on postgresql_server.tf line 34, in resource "azurerm_postgresql_flexible_server_firewall_rule" "postgresql_server_firewall_rule":
│   34:   name             = "Allow inbound access from Specific IP"
```

### Expected Behaviour

Ideally parameter `name` should allow value such as "Allow inbound access from Specific IP" (Space between characters). Tried running "Allow-inbound-access-from-Specific-IP" (Removed spaces in between) and it worked.

There is no such description mentioned that it doesn't allows space in between a string type value.
Ref - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server_firewall_rule#name

### Actual Behaviour

Parameter `name` should allow spaces in a string type value similar to [MSSQL Firewall rule name resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_firewall_rule).

### Steps to Reproduce

Add a string type value with space in between under `name` parameter and run `terraform apply`
(For eg - "All Access")

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Service API doesn't allow space. So it's service API limitation.

**Comment by a-z-i-z** [comment]
Thank you @neil-yechenwei for the heads up. Moving forward to close this issue.
