### ISSUE TITLE
Support for dedicated host type LSv3-type1

### ISSUE THREAD

**Issue by denise89p** [hashicorp/terraform-provider-azurerm#19793]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure has new dedicated host of Lsv3-Type1. The latest version of azurerm does not support Lsv3-Type1 dedicated hosts. only Lsv2-Type1

### New or Affected Resource(s)/Data Source(s)

azurerm_dedicated_host

### Potential Terraform Configuration

```hcl
resource "azurerm_dedicated_host" "example" {
  name                    = "example-host"
  location                = azurerm_resource_group.example.location
  dedicated_host_group_id = azurerm_dedicated_host_group.example.id
  sku_name                = "LSv3-Type1"
  platform_fault_domain   = 1
}
```

### References

azure Lsv3-series:  https://learn.microsoft.com/en-us/azure/virtual-machines/lsv3-series

**Comment by harshavmb** [comment]
Hi @mybayern1974 / @rcskosir ,

Can this be closed? I do see this being available [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/6062d998807b32301b84e113072e3505f27aaa99/internal/services/compute/dedicated_host_resource.go#L103).

**Comment by rcskosir** [comment]
@harshavmb Thanks for linking where it is available, I will mark this closed.
