### ISSUE TITLE
Could not create azure maintenance configuration with scope InGuestPatch

### ISSUE THREAD

**Issue by rob31231232** [hashicorp/terraform-provider-azurerm#19790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.37

### Affected Resource(s)/Data Source(s)

azurerm_maintenance_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_maintenance_configuration" "example" {
  name                          = "example-mc"
  location                      = azurerm_resource_group.resource_group.location
  resource_group_name           = azurerm_resource_group.resource_group.name
  scope                         = "InGuestPatch"

}
```

### Debug Output/Panic Output

```shell
Error: creating/updating Maintenance Configuration (Subscription: "<subscription_id>"
│ Resource Group Name: "<rg_name>"
│ Resource Name: "example-mc"): maintenanceconfigurations.MaintenanceConfigurationsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="" Message="maintenance scope 'InGuestPatch' not supported in '2021-05-01' version.,Extension properties must contain Patch mode. e.g. InGuestPatchMode = 'User' or InGuestPatchMode = 'Platform',Empty or Default Maintenance window is not allowed for InGuestPatch scope."
│ 
│   with azurerm_maintenance_configuration.example,
│   on maintenance_configuration.tf line 4, in resource "azurerm_maintenance_configuration" "example":
│    4: resource "azurerm_maintenance_configuration" "example" {
```

### Expected Behaviour

Create a maintenance configuration with the name example-mc with scope InGuestPatch

### Actual Behaviour

Error: autorest/azure: Service returned an error. Status=400 Code="" Message="maintenance scope 'InGuestPatch' not supported in '2021-05-01' version.,Extension properties must contain Patch mode. e.g. InGuestPatchMode = 'User' or InGuestPatchMode = 'Platform',Empty or Default Maintenance window is not allowed for InGuestPatch scope."

### References

At https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maintenance_configuration InGuestPatch is an valid scope option

**Comment by ziyeqf** [comment]
Hi @rob31231232 ,sorry for my late reply and thanks for reporting.

It needs an update on provider to support some properties tu fully support `InGuestPatch`. I will work on that.

For any further questions, please leave comments.Thanks

**Comment by rob31231232** [comment]
> Hi @rob31231232 ,sorry for my late reply and thanks for reporting.
> 
> It needs an update on provider to support some properties to fully support `InGuestPatch`. I will work on that.
> 
> For any further questions, please leave comments.Thanks

Hi @ziyeqf 

Thank you for your reply! Wil this also solve issue https://github.com/hashicorp/terraform-provider-azurerm/issues/19747#issuecomment-1360876699? That issue is an error when you try to connect an existing maintenance configuration with the inguest scope to a VM

> Hi @rob31231232 ,sorry for my late reply and thanks for reporting.
> 
> It needs an update on provider to support some properties to fully support `InGuestPatch`. I will work on that.
> 
> For any further questions, please leave comments.Thanks

Hi @ziyeqf 

Thank you for your reply! Wil this also solve issue https://github.com/hashicorp/terraform-provider-azurerm/issues/19747#issuecomment-1360876699? That issue is an error when you try to connect an existing maintenance configuration with the inguest scope to a VM

**Comment by rob31231232** [comment]
Hi @ziyeqf 

Thank you for your reply! Wil this also solve issue https://github.com/hashicorp/terraform-provider-azurerm/issues/19747#issuecomment-1360876699? That issue is an error when you try to connect an existing maintenance configuration with the inguest scope to a VM

**Comment by ziyeqf** [comment]
Hi @rob31231232, 

A PR (#19865) has submitted to add the support, there are some new properties needed when `scope` is set to `InGuestPatch`, please follow the documents. 

For your mentioned issue, could you please give a try after the PR merged and released? I will give a try on my side too.

For any further questions, please leave comments. Thanks!

**Comment by IvanKirianov** [comment]
Hi there, 
Any news when it's come to merge? We have recently notice the same issue... We are appreciate if this PR will be merged fast as it can be. 
Thanks!
