### ISSUE TITLE
Unable to create azurerm_storage_management_policy for storage account redundancy set to zone redundant storage (ZRS)

### ISSUE THREAD

**Issue by ecdemomaniaKay** [hashicorp/terraform-provider-azurerm#19814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.9

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_management_policy, azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                = "xxxxx"
  resource_group_name = local.resource_group_name
  location            = var.location
  tags                = local.tags

  account_tier                     = "Standard"
  account_kind                     = "StorageV2"
  access_tier                      = "Hot"
  account_replication_type         = "ZRS"
  enable_https_traffic_only        = true
  min_tls_version                  = "TLS1_2"
  is_hns_enabled                   = false
  allow_nested_items_to_be_public  = false
  cross_tenant_replication_enabled = false
  public_network_access_enabled    = true
}

resource "azurerm_storage_container" "this" {
  storage_account_name  = azurerm_storage_account.this.name
  name                  = "processing"
  container_access_type = "private"
}

resource "azurerm_storage_management_policy" "mgt_storage" {
  storage_account_id = azurerm_storage_account.this.id
  rule {
    name    = "cleanuprule"
    enabled = true
    filters {
      prefix_match = [
        "processing"
      ]
      blob_types = ["blockBlob"]
    }
    actions {
      version {
        change_tier_to_archive_after_days_since_creation = 10
        change_tier_to_cool_after_days_since_creation    = 7
        delete_after_days_since_creation                 = 20
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Storage Account Management Policy: (Management Policy Name "default" / Storage Account Name "xxxxx" / Resource Group "xxxxx"): storage.ManagementPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="FeatureNotSupportedForAccount" Message="tierToArchive is not supported for the account."
```

### Expected Behaviour

Successfully create the lifecycle policy.

### Actual Behaviour

Got error message "tierToArchive is not supported for the account."

### Steps to Reproduce

1. terraform apply

### References

Same issue [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/6031) and reported as solved. Judging by the replies and timestamp it is likely that the issue was resolved for azurerm v2.19.0 or v2.20.0. However I am using `public_network_access_enabled` in my storage account and versions <= 3.20.0 throws error for that argument, therefore I cannot test v2.20.0. Azurerm v3.21.0 throws the same error "tierToArchive is not supported for the account."

**Comment by magodo** [comment]
This seems to be a limitation of Azure, see [here](https://learn.microsoft.com/en-us/azure/storage/blobs/access-tiers-overview#:~:text=Only%20storage%20accounts%20that%20are%20configured%20for%20LRS%2C%20GRS%2C%20or%20RA%2DGRS%20support%20moving%20blobs%20to%20the%20archive%20tier.%20The%20archive%20tier%20isn%27t%20supported%20for%20ZRS%2C%20GZRS%2C%20or%20RA%2DGZRS%20accounts.):

> Only storage accounts that are configured for LRS, GRS, or RA-GRS support moving blobs to the archive tier. The archive tier isn't supported for ZRS, GZRS, or RA-GZRS accounts.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is not something that we are able to add as noted above.
Whilst I'd like to thank you for opening this issue as we have no plans to support this functionality I'm going to close this issue for the moment.
