### ISSUE TITLE
Support for data source to obtain identities of function app

### ISSUE THREAD

**Issue by nexient-ajoshi** [hashicorp/terraform-provider-azurerm#19844]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a data source `[azurerm_windows_function_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/windows_function_app)` to obtain identities of the function app module. There is no data source(if there is I couldn't find documentation for it, so please help in the case) for obtaining identities of the function app slots. It would be helpful to have one.

Since there is none available right now, is there any other recommended way to get it via terraform(other than using provisioners)? 

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

**Comment by xiaxyi** [comment]
Thanks @nexient-ajoshi for raising this issue. The data source for app slot is not available, I need to check the feature and decide the next step. unfortunately, there is no ETA, I'll keep you updated. 

As for your question: "is there any other recommended way to get it via terraform(other than using provisioners"? May I know the user scenario so I can try to find a workaround?

**Comment by nexient-ajoshi** [comment]
@xiaxyi Thanks for your response!!

Scenario :- We need to retrieve system system identity of windows function app deployment slot, so that system identity can be given an azure role over a key vault, and also that system identity can be added in azure ad group.

We are using terragrunt to orchestrate the terraform modules and supply inputs to them. There is a [bug](https://github.com/gruntwork-io/terragrunt/issues/720#issuecomment-497888756) in terragrunt due to which we are not able to "plan, use plan output to apply when there are dependent modules". For example, we had below terraform modules
1. module that creates function app slot, key vault
2. module for rbac

In terragrunt code, module 2 is dependent on outputs of module 1. But due to bug in terragrunt, module 2 can not use use "mock outputs along with terragrunt plan" command. I am not sure if I am able to explain it well here, please let me know if I need to provide code examples.

Current workaround:- Create below terrraform modules
1. module that creates function app slot and key vault
2. module that uses ["external" data source](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) to call shell script. The shell script uses `az cli` commands to fetch the system identity of the deployment slot. The same terraform module has rbac which then uses the system identity as input.

In terragrunt we "plan with output file, apply the output" for module 1. Then  "plan with output file, apply the output" for module 2. This is done sequentially in CI/CD pipeline. We are not using terragrunt module dependencies in the workaround.

Since we do not have 'data source' available for deployment slots, we need to use "external" data source. Otherwise this would have been a cleaner code.

We thought of using "local-exec" provisioner, but that [does not output](https://www.reddit.com/r/Terraform/comments/xv39l0/output_of_localexec_to_variable/) the system identity, which we need since the system identity needs to be supplied to rbac module as input.

**Comment by xiaxyi** [comment]
@nexient-ajoshi Thanks for the background sharing, have you tried to import the slot into terraform and try azurerm_windows_function_app.test.identity[0]?

**Comment by nexient-ajoshi** [comment]
@xiaxyi  Haven't tried that, I could try the 'import' option.

I was also made aware of [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/resources) data source. Function app deployment slot resource could be obtained if proper tags were added to it.
We are looking to move forward with this solution as it looks much cleaner from code perspective.

This issue can be closed since the intent was just knowing if data source exists for function app deployment slot.
