### ISSUE TITLE
Support for CMK in Azure Database for MySQL - Flexible Server

### ISSUE THREAD

**Issue by marucha** [hashicorp/terraform-provider-azurerm#19842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Database for MySQL flexible servers now supports using a customer managed encryption key  for encryption of databases. The feature is currently GA. Please add support for this feature in the azurerm provider. The docs for this feature can be found here: https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-customer-managed-key

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

**Comment by bwilczynski** [comment]
Started working on it but it requires changing the client SDK first. Will send a PR once I have it done.
