### ISSUE TITLE
data azurerm_management_group should allow whitespace

### ISSUE THREAD

**Issue by Poil** [hashicorp/terraform-provider-azurerm#19841]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group

### Terraform Configuration Files

```hcl
data "azurerm_management_group" "mg_main" {
  name = "Shared Services - Core IT"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: name can only consist of ASCII letters, digits, -, _, (, ), . , and cannot exceed the maximum length of 90
│ 
│   with data.azurerm_management_group.mg_main,
│   on data-mg.tf line 2, in data "azurerm_management_group" "mg_main":
│    2:   name = "Shared Services - Core IT"
│ 
╵
```

### Expected Behaviour

Should work, it works on portal

### Steps to Reproduce

terraform plan

**Comment by sinbai** [comment]
@Poil thanks for opening this issue. I guess the "Shared Services - Core IT" should be the `display_name` instead of `name`, right? If yes, could you try to get the management group with the following config?
```

data "azurerm_management_group" "mg_main" {
  display_name = "Shared Services - Core IT"
}
```

**Comment by Poil** [comment]
Hi,

Sorry, you are right, I tried to debug the code of my colleague and I didn't saw that ...

best regards
