### ISSUE TITLE
azurerm_windows_web_app site config application stack is not in alignment with the supported versions

### ISSUE THREAD

**Issue by vj-msft** [hashicorp/terraform-provider-azurerm#19850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
application_stack {
      current_stack  = try(var.site_config.runtime_stack, "dotnet")
      dotnet_version = try(var.site_config.dotnet_version, "v4.8")
    }
```

### Debug Output/Panic Output

```shell
Error: expected site_config.0.application_stack.0.dotnet_version to be one of [v2.0 v3.0 core3.1 v4.0 v5.0 v6.0 v7.0], got v4.8
```

### Expected Behaviour

Based on the portal experience, the current supported dotnet version for windows web app is 
<img width="453" alt="image" src="https://user-images.githubusercontent.com/12212247/210466799-cd1a81d7-a31b-4f68-9185-1067f8b1415a.png">

So expected terraform module to accept the same dotnet versions.  

### Actual Behaviour

Based on the documentation the terraform module currently accepts the below versions but few are not supported or available in windows web app.
[dotnet_version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app#dotnet_version) - (Optional) The version of .NET to use when current_stack is set to dotnet. Possible values include v2.0,v3.0,core3.1, v4.0, v5.0, v6.0 and v7.0.

**Comment by jackofallops** [comment]
Hi @vj-msft - Thanks for opening this issue.
Unfortunately the values displayed in the portal and those actually used by the API do not align 1:1.  Currently the service maps the values as:

Portal Value | API value
-- | --
ASP.NET V3.5 | v2.0
ASP.NET V4.8 | v4.0
.NET 6 (LTS) | v6.0
.NET 7 (STS) | v7.0

These are reflected in #19685 and I'm adding the supporting documentation notes to this at the moment. 

Hope this helps!

**Comment by vj-msft** [comment]
Thank you @jackofallops. This helps.

**Comment by jackofallops** [comment]
Thanks @vj-msft - I'm going to close this one out for now since it will be addressed by the above PR 👍
