### ISSUE TITLE
azurerm_synapse_spark_pool should support spark_version 3.3

### ISSUE THREAD

**Issue by lestermarch** [hashicorp/terraform-provider-azurerm#19854]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.22.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_spark_pool

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "rg-test"
  location = "UK South"
}

resource "azurerm_storage_account" "test" {
  name                            = "test20230104"
  resource_group_name             = azurerm_resource_group.test.name
  location                        = azurerm_resource_group.test.location
  account_tier                    = "Standard"
  account_replication_type        = "ZRS"
  account_kind                    = "StorageV2"
  default_to_oauth_authentication = true
  enable_https_traffic_only       = true
  is_hns_enabled                  = true
  min_tls_version                 = "TLS1_2"
  public_network_access_enabled   = true
}

resource "azurerm_storage_data_lake_gen2_filesystem" "test" {
  name               = "synapse"
  storage_account_id = azurerm_storage_account.test.id
}

resource "azurerm_synapse_workspace" "test" {
  name                                 = "test-workspace"
  resource_group_name                  = azurerm_resource_group.test.name
  location                             = azurerm_resource_group.test.location
  managed_resource_group_name          = "${azurerm_resource_group.test.name}-synapse-managed"
  managed_virtual_network_enabled      = true
  sql_administrator_login              = "test"
  sql_administrator_login_password     = "test"
  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.test.id

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_synapse_spark_pool" "synapse" {
  name                 = "testpool"
  synapse_workspace_id = azurerm_synapse_workspace.synapse.id
  node_size_family     = "MemoryOptimized"
  node_size            = "Small"
  spark_version        = "3.3"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected spark_version to be one of [2.4 3.1 3.2], got 3.3
│ 
│   with module.synapse_workspace_private.azurerm_synapse_spark_pool.synapse[0],
│   on modules/synapse-workspace-private/synapse-spark-pool.tf line 8, in resource "azurerm_synapse_spark_pool" "synapse":
│    8:   spark_version        = var.spark_pool_version
│ 
╵
Releasing state lock. This may take a few moments...
##[error]Bash exited with code '1'.
```

### Expected Behaviour

The provider should accept "3.3" as a valid value for `spark_version`. 

### Actual Behaviour

The provider only accepts "2.4", "3.1", or "3.2" as valid values for `spark_version`.

### References

Previous provider update to support Spark 3.2:
https://github.com/hashicorp/terraform-provider-azurerm/pull/16906/files

Microsoft documentation on Spark 3.3 availability:
https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-33-runtime

**Comment by sinbai** [comment]
@lestermarch thanks for your feedback. [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/19866) has been submitted to support spark_version 3.3. Could you track it for more updates?
