### ISSUE TITLE
Azurerm_data_factory_linked_service_azure_blob_storage account name stored asterisks  

### ISSUE THREAD

**Issue by levgoronshteyn** [hashicorp/terraform-provider-azurerm#19862]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0

### AzureRM Provider Version

3.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_linked_service_azure_blob_storage

### Terraform Configuration Files

```hcl
provider "azurerm" {
  # Configuration options
  features {}
}

data "azurerm_resource_group" "test" {
  name     = "test-lg"
 # location = "East US"
}

data "azurerm_client_config" "current" {
}

data "azurerm_storage_account" "example" {
  name                = "levgoronshteynstorage"
  resource_group_name = data.azurerm_resource_group.test.name
}

resource "azurerm_data_factory" "test" {
  name                = "example-lev"
  location            = data.azurerm_resource_group.test.location
  resource_group_name = data.azurerm_resource_group.test.name
}

resource "azurerm_key_vault" "test" {
  name                = "example-lev"
  location            = data.azurerm_resource_group.test.location
  resource_group_name = data.azurerm_resource_group.test.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
}

resource "azurerm_data_factory_linked_service_key_vault" "test" {
  name            = "linkkv-lev"
  data_factory_id = azurerm_data_factory.test.id
  key_vault_id    = azurerm_key_vault.test.id
}

resource "azurerm_data_factory_linked_service_azure_blob_storage" "test" {
  name            = "example-lev"
  data_factory_id = azurerm_data_factory.test.id
 service_principal_id = "f38c0ec8-c8d0-4df8-b29b-69057f6236984239"
 service_principal_key = "6zc5e2d7-5f12-5669-9ea5-8108093a60ce"
 tenant_id = "0d4q3e88-8caf-41ca-b4da-e3b33b6c52ec"
 connection_string = "DefaultEndpointsProtocol=https;AccountName=levgoronshteynstorage;AccountKey=NJaByjNTH3HZcRyROBeDFPjKoPIUMViI0p7r+79tRLBVSQNmmspGBdwI4ns2qGyp1HtvrZC+6hYf+AStVaZ8eg==;EndpointSuffix=core.windows.net"

ALL sensitive information has been changed!
```

### Debug Output/Panic Output

```shell
No panic output but what occurs is when you login to Azure portal and navigate to Azure Data Factory to see what the blob storage account name is, you are not able to see anything but asterisks(********). If you perform the same steps manually via Azure Portal, you can see the blob storage account name.

Same issue accounts even if you use AZ CLI
```

### Expected Behaviour

When a user uses Azure Portal to add a linked service for blob storage, the portal breaks up the connection string into two properties below:
```
{
  "connectionString": "<value>",
  "encryptedCredential": "<value>"
}
```

### Actual Behaviour

When using AzureRM provider, the connection string is stored as secure string and the storage account name is hidden with asterisks.
```
"connectionString": {
      "type": "SecureString",
      "value": "**********"
    },
    "credential": null,
    "description": null,
    "encryptedCredential": "ew0KICAiVmVyc2lvbiI6ICIyMDE3LTExLTMwIiwNCiAgIlByb3RlY3Rpb25Nb2RlIjogIktleSIsDQogICJTZWNyZXRDb250ZW50VHlwZSI6ICJQbGFpbnRleHQiLA0KICAiQ3JlZGVudGlhbElkIjogIkRBVEFGQUNUT1JZQEREMjREMjZGLTFEQkYtNDVERi04NEM1LTIzRUI4MDIzMUU1QV9hZGU1YTkzYS00MWZlLTRjZGYtOTA1NS1lNzg5YzcwMzM2NDciDQp9",
```
### Steps to Reproduce

Use the Terraform Configuration File provided

change the resource group and storage account

apply the terraform file.

### References

The AZ CLI tool has the same behaviour as terraform:

```
az datafactory linked-service create --factory-name "example-lev" --properties "{\"type\":\"AzureBlobStorage\",\"typeProperties\":{\"connectionString\":

{\"type\":\"SecureString\",\"value\":\"DefaultEndpointsProtocol=https;AccountName=xxx;AccountKey=xxx+xxx+6hYf+AStVaZ8eg==;EndpointSuffix=core.windows.net\"}}}" --name "exampleLinkedService" --resource-group "test-lg"
{
  "etag": "4f008de4-0000-0100-0000-63b477df0000",
  "id": "/subscriptions/xxx/resourceGroups/test-lg/providers/Microsoft.DataFactory/factories/example-lev/linkedservices/exampleLinkedService",
  "name": "exampleLinkedService",
  "properties": {
    "accountKey": null,
    "accountKind": null,
    "additionalProperties": null,
    "annotations": null,
    "azureCloudType": null,
    "connectVia": null,
    "connectionString": {
      "type": "SecureString",
      "value": "**********"
    },
    "credential": null,
    "description": null,
    "encryptedCredential": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "parameters": null,
    "sasToken": null,
    "sasUri": null,
    "serviceEndpoint": null,
    "servicePrincipalId": null,
    "servicePrincipalKey": null,
    "tenant": null,
    "type": "AzureBlobStorage"
  },
  "resourceGroup": "test-lg",
  "type": "Microsoft.DataFactory/factories/linkedservices"

```

**Comment by ms-henglu** [comment]
Hi @levgoronshteyn ,

Thank you for taking time to open this issue.

Is it duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/14358?

**Comment by levgoronshteyn** [comment]
Hi @ms-henglu,

It is the same issue as https://github.com/hashicorp/terraform-provider-azurerm/issues/14358 but since 14358 was never solved i have opened a new issue.

If using Terraform or even AZ CLI you cannot see the storage account name.

**Comment by ms-henglu** [comment]
Hi @levgoronshteyn ,

Thanks for the clarification. I have a workaround for this, https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_custom_service is a generic data factory linked service resource, you can use it to pass any payload, I think it might solve the problem.

**Comment by levgoronshteyn** [comment]
@ms-henglu I have tested the work around provided and it worked as well. I sent the outcome and details to the client until the reported issue is resolved.

I also see that there has bee a PR created and tested to verify that the resource can be used as designed without encrypting non-sensitive data. Do you know when the fix will be in and i can let the client know that they can test?

**Comment by tombuildsstuff** [comment]
@ms-henglu this is an Azure Portal issue which needs to be fixed there, since Terraform is matching the behaviour of the Azure CLI etc?

**Comment by katbyte** [comment]
I opened an issue on the rest [API specs](https://github.com/Azure/azure-rest-api-specs/issues/22106) as this appears to be something that needs to be corrected in the portal as both providers + the CLI are sending the connection string in the same way.

**Comment by levgoronshteyn** [comment]
@ms-henglu the client also tested your recommended workaround but they cannot use it as the resource is not an approved one to be used in their org.
