### ISSUE TITLE
azurerm_sql_managed_instance custom timeouts do not work - 3.37

### ISSUE THREAD

**Issue by Official-James** [hashicorp/terraform-provider-azurerm#19870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.3

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_sql_managed_instance

### Terraform Configuration Files

```hcl
resource "azurerm_sql_managed_instance" "sql_server" {
  name                         = **
  resource_group_name          = **
  location                     = **
  sku_name                     = **
  vcores                       = **
  storage_size_in_gb           = **
  license_type                 = **
  administrator_login          = **
  administrator_login_password = **
  subnet_id                    = **
  collation                    = **
  public_data_endpoint_enabled = **
  minimum_tls_version          = **
  tags                         = **

  timeouts {
    create = "4h"
    delete = "1h"
  }
}
```

### Debug Output/Panic Output

```shell
Interrupt received.
Please wait for Terraform to exit or data loss may occur.
Gracefully shutting down...

Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context canceled
```

### Expected Behaviour

Continue the deployment even after the default 1-hour timeout, as the custom is set to 4 hours. 

### Actual Behaviour

Timeout of 1-hour happens which results in the deployment to be terminated.

### Steps to Reproduce

1. terraform apply

### References

3.37 states it now supports timeouts. Previous versions have not got this: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_instance

**Comment by sinbai** [comment]
Hi @Official-James , thanks for opening this issue. The azurerm_sql_managed_instance resource is deprecated  and will be removed in version 4.0, as such this resource is feature-frozen and [azurerm_mssql_managed_instance](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_managed_instance)  should be used instead of  azurerm_sql_managed_instance.
