### ISSUE TITLE
Support for priority setting in azurerm_web_pubsub_hub event_handler

### ISSUE THREAD

**Issue by bugoutfr** [hashicorp/terraform-provider-azurerm#19876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

I noticed that  event handlers in Azure Web PubSub are ordered by priority. It is important because incoming events might be caught by the wrong handler before reaching the expected one if the correct priority is not set.

I haven't found a way to set the priority in the current module. Adding it in the future would be a good thing to fully support Azure Web PubSub.

Best regards.

### New or Affected Resource(s)/Data Source(s)

azurerm_web_pubsub_hub

### Potential Terraform Configuration

```hcl
resource "azurerm_web_pubsub_hub" "mediaplayer" {
  name          = "mediaplayer"
  web_pubsub_id = azurerm_web_pubsub.webpubsub.id
  anonymous_connections_enabled = true

  event_handler {
    url_template       = var.connect_event_handler_url
    system_events      = ["connect"]
    priority           = 1

    auth {
      managed_identity_id = azurerm_web_pubsub.webpubsub.identity.0.principal_id
    }
  }

  event_handler {
    url_template       = var.disconnect_event_handler_url
    system_events      = ["disconnect"]
    priority           = 5

    auth {
      managed_identity_id = azurerm_web_pubsub.webpubsub.identity.0.principal_id
    }
  }
}
```

**Comment by xiaxyi** [comment]
Thanks @bugoutfr for raising this issue. API doesn't support setting priority directly, however, you can set the event handler priority by order, for example, moving the handler up/ down. 

I will modify the data type in terraform so it supports the order modification. I'll update you once the fix is ready.

**Comment by bugoutfr** [comment]
Thank you @xiaxyi for your quick and detailed answer. 

I raised this issue because I noticed that after applying my terraform file to create a new Web PubSub Hub, the order in the resulting Hub on the Azure Portal didn't match the order in my terraform file. So I guessed the creation process didn't necessarily take that order into account.

**Comment by xiaxyi** [comment]
Thanks @bugoutfr for the comment, the event handler is defined as TypeSet which only cares about the content instead of the order. I will change the data type so it can respect the order.

**Comment by bugoutfr** [comment]
That sounds great! thanks a lot ☺

**Comment by xiaxyi** [comment]
@bugoutfr no problems, you can refer to the mentioned pr for the progress of the fix.
