### ISSUE TITLE
Creating Azure application gateway request_routing_rule failed without flag: priority

### ISSUE THREAD

**Issue by epiHATR** [hashicorp/terraform-provider-azurerm#19874]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.37.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.http_listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.backend_http_settings_name
  }
```

### Debug Output/Panic Output

```shell
Error: creating Application Gateway: (Name "hatr-vnet-appgw" / Resource Group "hatr-vmss"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty" Message="Priority for the request routing rule /subscriptions/c3f3aa63-3fdc-402f-9b03-30fe0a3df3ef/resourceGroups/hatr-vmss/providers/Microsoft.Network/applicationGateways/hatr-vnet-appgw/requestRoutingRules/rule-5e78e22d53e2724784a3a4c4f13f2201 cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01" Details=[]
```

### Expected Behaviour

Based on documentation at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway, the ```priority``` flag should be ```mandatory``` (required)

**Comment by ms-zhenhua** [comment]
Hi @epiHATR, thank you for reaching out.
According to [this issue](https://github.com/hashicorp/terraform-provider-azurerm/pull/17380), `priority` is required for `v2 sku` only, but not for `v1 sku`.

**Comment by StefanSchoof** [comment]
The Docs say:
> Note: priority is required when sku.0.tier is set to *_v2.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#priority

**Comment by epiHATR** [comment]
Thank you everyone.
