### ISSUE TITLE
azurerm_site_recovery_replicated_vm does not support multiVmGroupName

### ISSUE THREAD

**Issue by richshadman** [hashicorp/terraform-provider-azurerm#19898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replicated_vm 

### Terraform Configuration Files

```hcl
N/A, the issue is there is no property for multivmgroup - we have been using ARM templates for 2 years due to this missing feature.
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The ARM template for replicated items has supported setting up a multi vm group name (and now id) for some time:

https://learn.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/2021-12-01/vaults/replicationfabrics/replicationprotectioncontainers/replicationprotecteditems?pivots=deployment-language-bicep 

![image](https://user-images.githubusercontent.com/59030423/211103834-7dfbb536-9df2-48da-9c6e-648010cda006.png)

![image](https://user-images.githubusercontent.com/59030423/211103899-727c0da0-d3f3-45e8-9ae1-d8a47bef4a15.png)

### Actual Behaviour

We must use ARM template deployment to support multi vm groups - this makes the resource unusable for scenarios like asr for windows failover clusters that must failover as a group.

**Comment by ziyeqf** [comment]
Hi @richshadman , thanks for opening the issue.

A PR (#19939) has been submit to add this property. Please wait for it to merge and release.

Thanks!

**Comment by richshadman** [comment]
Great news, thanks for the quick turnaround!

I have another similar issue that has been opened for 2 years, linked here: https://github.com/hashicorp/terraform-provider-azurerm/issues/8465

Any chance you can take a look at that as well @ziyeqf ?

**Comment by dsiperek-vendavo** [comment]
This would be great as we can't use ASR for some servers that use PPG because of this.

**Comment by ziyeqf** [comment]
@richshadman have taken a look at the property related to `test fail over` you mentioned. Have updated the PR to including these.

Thanks!

**Comment by richshadman** [comment]
> @richshadman have taken a look at the property related to `test fail over` you mentioned. Updated the PR to include these.
> 
> And don't worry about I have closed this PR, just close it to wait for some tests cost much time to finish.
> 
> Thanks!

Fantastic news, thanks @ziyeqf !

**Comment by richshadman** [comment]
@ziyeqf the one thing that I don't see in the PR is the tfo network id (assuming it would be a property called **test_network_id** since the equivalent for failover is **target_network_id**?). This property is not part of the network mapping but rather should be a root property for the resource.

Without this value, I don't think the network mappings would be valid.

Thank you very much for attending to these changes, it will make the resource much more usable - once complete we can finally move away from arm templates for this portion of our infrastructure as code.
