### ISSUE TITLE
azurerm_windows_function_app virtual network integration not released correctly

### ISSUE THREAD

**Issue by RodicaRadut** [hashicorp/terraform-provider-azurerm#19896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_function_app" "function" {
  name                       = "exx-dev-fa-auditroutingexport"
  location                   = data.azurerm_resource_group.fa_rg.location
  resource_group_name        = data.azurerm_resource_group.fa_rg.name
  service_plan_id            = data.azurerm_service_plan.service_plan.id
  storage_account_name       = azurerm_storage_account.fa_storage_account.name
  storage_account_access_key = azurerm_storage_account.fa_storage_account.primary_access_key

  virtual_network_subnet_id = data.azurerm_virtual_network.vnet.id

  tags = {
    Environment = var.environment
  }

    site_config {  
      application_stack {
        dotnet_version = "3.1"
      }
    }
......
}
```

### Debug Output/Panic Output

```shell
An argument named "virtual_network_subnet_id" is not expected here.
```

### Expected Behaviour

Terraform plan should run correctly and function app should have vnet integration

### Actual Behaviour

Terraform plan throws and error regarding the attribute

### Steps to Reproduce

I am trying to create a windows function app with vnet integration. 
It seems that the attribute "virtual_network_subnet_id" has not been released.

### Important Factoids

no

### References

no

**Comment by xiaxyi** [comment]
Thanks @RodicaRadut for raising this issue, may I know the provider version that you used? I see the version you post in this issue is 3.0.0, in this version, the property `virtual_network_subnet_id` is defined in block `ip_restriction`. Would you mind trying the latest version? Feel free to let me know if you have any concerns.

**Comment by davidobrien1985** [comment]
This same issue is also present on `azurerm_linux_web_app`.

TF version: `1.3.9`
AzureRm provider: 
```
azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0.2"
    }
```

**Comment by RodicaRadut** [comment]
> Thanks @RodicaRadut for raising this issue, may I know the provider version that you used? I see the version you post in this issue is 3.0.0, in this version, the property `virtual_network_subnet_id` is defined in block `[ip_restriction](https://registry.terraform.io/providers/hashicorp/azurerm/3.0.0/docs/resources/windows_function_app#virtual_network_subnet_id)`. Would you mind trying the latest version? Feel free to let me know if you have any concerns.

Hi, 
The version that I was using is 3.0.0. 

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
}

Will try with a newer version and let you know.

**Comment by xiaxyi** [comment]
@RodicaRadut Good day, may I know if you tried the solution that I mentioned in my last comment? let me know if you have any question.

**Comment by rcskosir** [comment]
Thanks for opening this issue. Since time has passed since @xiaxyi reached out with no additional information, I am going to mark this issue closed. If you are able to provide more information to help us reproduce this issue we may re-open this issue or open a new issue, thanks!
