### ISSUE TITLE
Error in azurerm_management_group_policy_exemption using policy_definition_reference_ids

### ISSUE THREAD

**Issue by pasqualedevita** [hashicorp/terraform-provider-azurerm#19904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_management_group_policy_exemption

### Terraform Configuration Files

```hcl
locals {
  intiative_ids = {
    iso_27001_2013 = "/providers/Microsoft.Authorization/policySetDefinitions/89c6cddc-1c73-4ac1-b19c-54d1a15a42f2",
  }
}

resource "azurerm_management_group_policy_assignment" "pagamenti_servizi_prod_iso_27001_2013" {
  name                 = "${local.pagamenti_servizi_prod_prefix}iso270012013"
  display_name         = "ISO 27001:2013"
  policy_definition_id = local.intiative_ids.iso_27001_2013
  management_group_id  = data.azurerm_management_group.pagamenti_servizi_prod.id

  location = var.location
  enforce  = false
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_management_group_policy_exemption" "pagamenti_servizi_prod_iso_27001_2013" {
  name                 = "${azurerm_management_group_policy_assignment.pagamenti_servizi_prod_iso_27001_2013.name}"
  management_group_id  = data.azurerm_management_group.pagamenti_servizi_prod.id
  policy_assignment_id = azurerm_management_group_policy_assignment.pagamenti_servizi_prod_iso_27001_2013.id
  exemption_category   = "Mitigated"
  description          = "Mitigated with Google MFA"
  policy_definition_reference_ids = [
    "/providers/Microsoft.Authorization/policyDefinitions/e3576e28-8b17-4677-84c3-db2990658d64", # MFA should be enabled on accounts with read permissions on your subscription
    "/providers/Microsoft.Authorization/policyDefinitions/9297c21d-2ed6-4474-b48f-163f75654ce3", # MFA should be enabled for accounts with write permissions on your subscription
    "/providers/Microsoft.Authorization/policyDefinitions/aa633080-8b72-40c4-a2d7-d00c03e80bed", # MFA should be enabled on accounts with owner permissions on your subscription
    "/providers/Microsoft.Authorization/policyDefinitions/4f11b553-d42e-4e3a-89be-32ca364cad4c", # A maximum of 3 owners should be designated for your subscription
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: creating/updating /providers/Microsoft.Management/managementGroups/pagamenti_servizi_prod/providers/Microsoft.Authorization/policyExemptions/pspiso270012013: policy.ExemptionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyDefinitionReference" Message="The policy exemption 'pspiso270012013' create request is invalid.  The specified policy definition reference id '/providers/Microsoft.Authorization/policyDefinitions/e3576e28-8b17-4677-84c3-db2990658d64,/providers/Microsoft.Authorization/policyDefinitions/9297c21d-2ed6-4474-b48f-163f75654ce3,/providers/Microsoft.Authorization/policyDefinitions/aa633080-8b72-40c4-a2d7-d00c03e80bed,/providers/Microsoft.Authorization/policyDefinitions/4f11b553-d42e-4e3a-89be-32ca364cad4c' is invalid."
│ 
│   with azurerm_management_group_policy_exemption.pagamenti_servizi_prod_iso_27001_2013,
│   on 03_pagamenti_servizi_prod.tf line 22, in resource "azurerm_management_group_policy_exemption" "pagamenti_servizi_prod_iso_27001_2013":
│   22: resource "azurerm_management_group_policy_exemption" "pagamenti_servizi_prod_iso_27001_2013" {
```

### Expected Behaviour

resource created

### Actual Behaviour

Error

### Steps to Reproduce

terraform apply

### References

Full code and pull request https://github.com/pagopa/azure-governance/pull/46

**Comment by wuxu92** [comment]
Hi @pasqualedevita, thanks for your feedback. according to the policy API definition, `policy_definition_reference_ids ` should be used when the associated policy assignment is an assignment of a **policy set definition**, and it should be the reference id of the policy set definition(not the policy definition id). it's not a policy set definition in your configuration, so you may not use this property in the exemption resource.

https://github.com/Azure/azure-rest-api-specs/blob/fce0b25dda01303f2c70de34031169b5d326998b/specification/resources/resource-manager/Microsoft.Authorization/preview/2020-07-01-preview/policyExemptions.json#L397-L402

**Comment by pasqualedevita** [comment]
> Hi @pasqualedevita, thanks for your feedback. according to the policy API definition, `policy_definition_reference_ids ` should be used when the associated policy assignment is an assignment of a **policy set definition**, and it should be the reference id of the policy set definition(not the policy definition id). it's not a policy set definition in your configuration, so you may not use this property in the exemption resource.
> 
> https://github.com/Azure/azure-rest-api-specs/blob/fce0b25dda01303f2c70de34031169b5d326998b/specification/resources/resource-manager/Microsoft.Authorization/preview/2020-07-01-preview/policyExemptions.json#L397-L402

Hi @wuxu92 thanks for your suggestion! I've updated to the policy set reference id and now it works!
In this picture where to find the policy set reference ids on Azure Portal

<img width="1594" alt="Screenshot 2023-01-09 at 11 50 07" src="https://user-images.githubusercontent.com/59291437/211291671-dd4560df-4c49-40b7-93b5-f1607a75645d.png">
