### ISSUE TITLE
Support for configure long term backup retention in azurerm_mssql_managed_database

### ISSUE THREAD

**Issue by StefanSchoof** [hashicorp/terraform-provider-azurerm#19917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Manage Azure SQL Managed Instance have an option to control the long-term backup retention. See https://learn.microsoft.com/en-us/azure/azure-sql/managed-instance/long-term-backup-retention-configure?view=azuresql&tabs=portal

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_managed_database" "example" {
  name                = "example"
  managed_instance_id = azurerm_mssql_managed_instance.example.id
  monthly_retention    = "P1Y"
  week_of_year         = 3
  weekly_retention     = "P1M"
  yearly_retention     = "P5Y"
}
```

### References

- https://learn.microsoft.com/en-us/rest/api/sql/2021-02-01-preview/long-term-retention-policies/create-or-update?tabs=HTTP

**Comment by JakeAdkisson** [comment]
Thank you for creating this issue!  Does anyone know how early this can be implemented?

**Comment by OLeonardoRodrigues** [comment]
Is this going to be implemented?

**Comment by StefanSchoof** [comment]
[azurerm_mssql_managed_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_managed_database) does have now a `long_term_retention_policy` block.
