### ISSUE TITLE
Support for "Alert product names" condition in azurerm_sentinel_automation_rule

### ISSUE THREAD

**Issue by kotlaluk** [hashicorp/terraform-provider-azurerm#19919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I expect to be able to use "Alert product names" property as a condition in an automation rule. Using this, one should be able to limit the automation rule to run on incidents containing alerts with only specific product names as in Sentinel GUI:

![image](https://user-images.githubusercontent.com/46661160/211342072-f871f0bb-47c0-4cd1-a709-546afe2d770a.png)

This seems to be currently not supported.

### New or Affected Resource(s)/Data Source(s)

azurerm_sentinel_automation_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_automation_rule" "example" {
  name = uuid()
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id
  display_name = "Example Automation Rule Using AlertProductNames"
  action_playbook{
    logic_app_id = azurerm_logic_app_workflow.example.id
    order = 1
  }
  condition {
    operator = "Contains"
    property = "AlertProductNames"
    values = [
      "Azure Active Directory Identity Protection", "Office 365 Advanced Threat Protection"
    ]
  }
  order = 1
  enabled = true
}
```

### References

Possible Azure SDK resource:
- https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/preview/securityinsight/mgmt/2021-09-01-preview/securityinsight#MicrosoftSecurityProductName

**Comment by ziyeqf** [comment]
Hi @kotlaluk, thanks for opening this issue.

I noticed the support of `AlertProductNames` has been supported by #20726.

And I may suggest to use `condition_json` as `condition` is deprecated in favor of `condition_json`.

For any further questions please leave comments.
Thanks!

**Comment by kotlaluk** [comment]
Hello @ziyeqf, 
thank you for your reply.

I have tested the functionality with the newest provider version (3.57.0) and below code using `condition_json`:
```terraform
condition_json = jsonencode([
    {
      conditionType = "Property"
      conditionProperties = {
        propertyName = "AlertProductNames"
        operator     = "Contains"
        propertyValues = [
          "Microsoft Defender for Cloud Apps"
        ]
      }
    }
])
```

This produces the following output in the Sentinel GUI (1):
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/46661160/67e9e732-cafa-4322-bd72-d33d7a49c7a7)

Instead of the expected (2):
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/46661160/d2271e1c-ac06-483d-86d2-738ecc3ebe75)

The automation rule using the condition (1) does not match the incidents properly whereas the (2) does.

**Comment by ziyeqf** [comment]
Hi @kotlaluk, to make the config match the #2, please use `"Microsoft Cloud App Security"` as `propertyValues`.

For any further questions please leave comments. Thanks!

**Comment by kotlaluk** [comment]
Hello @ziyeqf,
thanks again for your comment. It has indeed solved my issue and the automation rule now works as expected.

I could have anticipated that Microsoft still uses old tool names there...

I'm going to close this issue.
Thank you!
