### ISSUE TITLE
azurerm_key_vault_secret fails apply in first run succeeds in future apply runs without code change

### ISSUE THREAD

**Issue by jchancellor-ms** [hashicorp/terraform-provider-azurerm#19926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
#childmodule keyvault_with_access_policy
resource "azurerm_key_vault" "infra_vault" {
  name                            = var.keyvault_name
  location                        = var.rg_location
  resource_group_name             = var.rg_name
  enabled_for_disk_encryption     = true
  enabled_for_template_deployment = true
  enabled_for_deployment          = true
  tenant_id                       = var.azure_ad_tenant_id
  soft_delete_retention_days      = 7
  purge_protection_enabled        = true
  sku_name                        = "standard"
  tags                            = var.tags
}
#set a wait timer to handle creation lag issues
resource "time_sleep" "wait_30_seconds" {
  depends_on = [azurerm_key_vault.infra_vault]
  create_duration = "30s"
}
resource "azurerm_key_vault_access_policy" "deployment_user_access" {
  key_vault_id = azurerm_key_vault.infra_vault.id
  tenant_id    = var.azure_ad_tenant_id
  object_id    = var.deployment_user_object_id

  secret_permissions = [
    "Get", "List", "Set", "Delete", "Backup", "Recover", "Restore"
  ]

  depends_on = [
    time_sleep.wait_30_seconds,
    azurerm_key_vault.infra_vault
  ]
}

#root module
resource "random_password" "userpass" {
  length           = 20
  special          = true
  override_special = "_-!."
  min_lower        = 2
  min_numeric      = 2
  min_upper        = 2
  min_special      = 2
}

resource "azurerm_key_vault_secret" "gmsapassword" {
  name         = "testgmsaapp-password"
  value        = random_password.userpass.result
  key_vault_id = module.keyvault_with_access_policy.keyvault_id
  depends_on   = [module.keyvault_with_access_policy.keyvault_id]
}
```

### Debug Output/Panic Output

```shell
Error: checking for presence of existing Secret "testgmsaapp-password" (Key Vault "https://k8slab-kv-westus3-d4.vault.azure.net/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx;oid=xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx;numgroups=3;iss=https://sts.windows.net/xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/' does not have secrets get permission on key vault 'k8slab-kv-westus3-d4;location=westus3'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
```

### Expected Behaviour

Secret should create during the first module apply instead of failing.

### Actual Behaviour

I get these errors during the first run of a large configuration where I have a root module that calls several child modules.  If I immediately re-run the configuration without code changes then everything works successfully.  Interestingly, secrets created in the child modules work fine, but while secrets in the root fail in the first iteration.  

This may be the same issue as https://github.com/hashicorp/terraform-provider-azurerm/issues/18659, but I'm adding it as my error is slightly different.  Hoping this will help with any troubleshooting

### References

(https://github.com/hashicorp/terraform-provider-azurerm/issues/18659)

**Comment by wuxu92** [comment]
Hi @jchancellor-ms, if this issue persists in every run, and if creating the keyvault resource cross-region(means the keyvault in a different region than where terraform runs)?

**Comment by jchancellor-ms** [comment]
Xu,

Terraform runs on my laptop, deploying into Azure WestUS3.  What is unusual is that the error only seems to occur when the secret creation occurs in the root module.  I create secrets in child modules without issue as part of the same deployment in the same region to the same keyvault.

(you can see the full code here) - infrastructure-labs/labs/k8s_windows at main · jchancellor-ms/infrastructure-labs (github.com)<https://github.com/jchancellor-ms/infrastructure-labs/tree/main/labs/k8s_windows>.  Secrets in main.tf fail, but secrets in the modules (like module.lab_dc write passwords to the same keyvault as secrets and work successfully.

Please let me know if you'd like me to do additional testing from a different deployment machine or something else.

Jon
[https://opengraph.githubassets.com/a0ece00219adfa10f198e1a5b8fa1cd6215e858c7b52c9bc6eb895436077a95c/jchancellor-ms/infrastructure-labs]<https://github.com/jchancellor-ms/infrastructure-labs/tree/main/labs/k8s_windows>
infrastructure-labs/labs/k8s_windows at main · jchancellor-ms/infrastructure-labs<https://github.com/jchancellor-ms/infrastructure-labs/tree/main/labs/k8s_windows>
Azure Infrastructure test-labs. Restructuring layout - infrastructure-labs/labs/k8s_windows at main · jchancellor-ms/infrastructure-labs
github.com

________________________________

**Comment by lonegunmanb** [comment]
Hi @jchancellor-ms , according to your code:

```hcl
resource "azurerm_key_vault_secret" "gmsapassword" {
  name         = "testgmsaapp-password"
  value        = random_password.userpass.result
  key_vault_id = module.keyvault_with_access_policy.keyvault_id
  depends_on   = [module.keyvault_with_access_policy.keyvault_id]
}
```

The `azurerm_key_vault_secret` resource depends on `module.keyvault_with_access_policy.keyvault_id`, so once the KeyVault inside this child module was created, Terraform would try to create secret immediately, meanwhile the access policy is about to be created. Would you try the follow code?

```hcl
 resource "azurerm_key_vault_secret" "gmsapassword" {
  name         = "testgmsaapp-password"
  value        = random_password.userpass.result
  key_vault_id = module.keyvault_with_access_policy.keyvault_id
  depends_on   = [module.keyvault_with_access_policy]
}
```

According to the [document](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on#processing-and-planning-consequences):

>The depends_on meta-argument instructs Terraform to complete all actions on the dependency object (including Read actions) before performing actions on the object declaring the dependency. When the dependency object is an entire module, depends_on affects the order in which Terraform processes all of the resources and data sources associated with that module.

**Comment by jchancellor-ms** [comment]
That corrected the issue.  One I fixed the module dependency, it looks like it sequenced everything properly.  My apologies for inadequately troubleshooting my dependencies and thanks for the help.  We can close this issue.

Jon
________________________________

**Comment by wuxu92** [comment]
> That corrected the issue. One I fixed the module dependency, it looks like it sequenced everything properly. My apologies for inadequately troubleshooting my dependencies and thanks for the help. We can close this issue. Jon

@jchancellor-ms could you close this issue? I can not close it directly.

**Comment by lonegunmanb** [comment]
Wow @jchancellor-ms I'm glad to hear that your issue has been solved, would you please help us by closing this issue? And please feel free to reopen it once you've any further question on this issue!
