### ISSUE TITLE
azurerm_subnet can't create with "The async operation failed"

### ISSUE THREAD

**Issue by naruse666** [hashicorp/terraform-provider-azurerm#19930]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.35.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg"
  location = "East US"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  resource_group_name = azurerm_resource_group.rg.name
  location            = "East US"
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "app_sub" {
  name                 = "app_sub"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.100.0/24"]
}
```

### Debug Output/Panic Output

```shell
Error: creating Subnet: (Name "app_sub" / Virtual Network Name "vnet" / Resource Group "rg"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed."
```

### Expected Behaviour

I want to create subnet.

### Actual Behaviour

I can create same subnet by GUI portal.
But can't create with terraform.
What I can do?

### Steps to Reproduce

terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. After tested, seems it works fine with your tf config on my local. Could you retry to see if the issue still exists?

![image](https://user-images.githubusercontent.com/19754191/211491743-9acd3d61-a26e-49e6-a71b-ddd4129f0b0f.png)

**Comment by naruse666** [comment]
Sorry. Here is using "app_sub" on subnet above example.
But my local is using "app_data".

When I used "app_data", I can't created subnet.
I don't know why it happen. But I was solved with name "data" !

If you know this problem, please let me know.
And my English is good? sorry if I'm rude.

**Comment by epiHATR** [comment]
Linked related issues: https://github.com/hashicorp/terraform-provider-azurerm/issues/8129

**Comment by naruse666** [comment]
oh...thank you!
