### ISSUE TITLE
azurerm_virtual_desktop_workspace changes cause workspace to be removed for users

### ISSUE THREAD

**Issue by ChrisTav424** [hashicorp/terraform-provider-azurerm#19943]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_workspace" "main" {
  name                = lower(format("vdws-%s-%s-%s", var.environment, var.location, replace(var.name, " ", "-")))
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  friendly_name = var.friendly_name
  description   = var.description
  tags          = var.tags
}
```

### Debug Output/Panic Output

```shell
C:\hostedtoolcache\windows\terraform\1.3.7\x64\terraform.exe apply -auto-approve -input=false 7527-operations
module.hostpool["test"].azurerm_virtual_desktop_host_pool_registration_info.main: Creating...
module.workspace.azurerm_virtual_desktop_workspace.main: Modifying... [id=/subscriptions/<removed>/resourceGroups/rg-vdws-prod-uksouth-operations/providers/Microsoft.DesktopVirtualization/workspaces/vdws-prod-uksouth-operations]
module.hostpool["test"].azurerm_virtual_desktop_host_pool_registration_info.main: Creation complete after 1s [id=/subscriptions/<removed>/resourceGroups/rg-vdpool-prod-uksouth-br/providers/Microsoft.DesktopVirtualization/hostPools/vdpool-prod-uksouth-br/registrationInfo/default]
module.workspace.azurerm_virtual_desktop_workspace.main: Modifications complete after 3s [id=/subscriptions/<removed>/resourceGroups/rg-vdws-prod-uksouth-operations/providers/Microsoft.DesktopVirtualization/workspaces/vdws-prod-uksouth-operations]

Apply complete! Resources: 1 added, 1 changed, 0 destroyed.
Finishing: Terraform : apply
```

### Expected Behaviour

A simple change to remove one character from the description, should have only changed the description

### Actual Behaviour

Instead it removes access for the users, they see the following

<img width="676" alt="image" src="https://user-images.githubusercontent.com/44398463/211562393-1c2fe69b-73f1-4739-9a0f-596af5c010e8.png">

In the Desktop Application Group, the association is still there as is the user. The workaround we have found is to de-associate and re-associate the DAG but it means we can't make changes in production hours at the moment as it impacts our users

### Steps to Reproduce

terraform apply

### Important Factoids

None

### References

Also seen a similar symptom reported under https://github.com/hashicorp/terraform-provider-azurerm/issues/18677

**Comment by sinbai** [comment]
@ChrisTav424 thanks for opening this issue. Unfortunately, Terraform could not do anything about this case, because terraform only sends a request to call the Azure API when updating the `description` of the resource `azurerm_virtual_desktop_workspace`. And does nothing else.

**Comment by ChrisTav424** [comment]
Thank you @sinbai i raised a support ticket with MS and it's a known global issue that disconnects the app group from the workspace when any changes are made to the workspace, just waiting on an ETA

**Comment by sinbai** [comment]
Hi @ChrisTav424 thanks for the update above, are you okey if we close this issue?

**Comment by ChrisTav424** [comment]
Yes, hopefully this helps someone too.

**Comment by ChrisTav424** [comment]
Microsoft have confirmed that this is now resolved
