### ISSUE TITLE
Machine Learning Workspace public_access_behind_virtual_network_enabled warning

### ISSUE THREAD

**Issue by waltonchiang** [hashicorp/terraform-provider-azurerm#19952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.24.0

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 0.12.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.24.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_machine_learning_workspace" "example" {
  name                                         = "example-workspace"
  location                                     = var.location
  resource_group_name                          = var.resource_group_name
  application_insights_id                      = var.application_insights_id
  key_vault_id                                 = var.key_vault_id
  storage_account_id                           = var.storage_account_id
  public_access_behind_virtual_network_enabled = true

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
│ Warning: Argument is deprecated
│
│   with azurerm_machine_learning_workspace.example,
│   on main.tf line 22, in resource "azurerm_machine_learning_workspace" "example":
│   52:   public_access_behind_virtual_network_enabled = true
│
│ `public_access_behind_virtual_network_enabled` will be removed in favour of the property
│ `public_network_access_enabled` in version 4.0 of the AzureRM Provider.
```

### Expected Behaviour

According to [AzureRM Documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_workspace#public_access_behind_virtual_network_enabled) public_network_access_enabled should be the one being removed and replaced by public_access_behind_virtual_network_enabled

### Actual Behaviour

Either public_network_access_enabled or public_access_behind_virtual_network_enabled works in the example, but the Warning message and the reference page contradict each other.

### References

[public_access_behind_virtual_network_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/machine_learning_workspace#public_access_behind_virtual_network_enabled)

**Comment by xuzhang3** [comment]
@waltonchian `public_access_behind_virtual_network_enabled ` will eventually be removed in v4.x.

**Comment by waltonchiang** [comment]
I should have double checked, but the error message in the original post was not the one I saw... This is what I mean, and if @xuzhang3 is correct then this message is not. 
![pnae](https://user-images.githubusercontent.com/77019232/212094457-cb3bd94a-a276-4f78-b936-a27bbddd418b.png)

**Comment by waltonchiang** [comment]
Thank you, I was working in an isolated environment so I didn't realize that.
