### ISSUE TITLE
Support for optional `site_config` block for `azurerm_linux_web_app` resource since it already exist as a required empty block.

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-provider-azurerm#19966]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {} # Why is this empty block defined as required block?
}
```

The [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app) states the below line.

---

[site_config](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#site_config) - (Required) A site_config block as defined below.

---

As `site_config {}` empty block line is required inside `azurerm_linux_web_app` resource, why it cannot be defined as an optional block?

The `site_config` block could be optional for `azurerm_linux_web_app` resource since it already exist as a required empty block.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id
}
```

**Comment by xiaxyi** [comment]
Thanks @sheeeng for raising this issue, the site_config block is required even it allows the empty value. For some properties inside the site_config block, they are required from the Api side, and we assigned them the default value. For data type as list/set (site_config in this case), we don't support default value yet, so we need to make it required. Hope it makes sense to you, feel free to let me know if there is anything needed.
