### ISSUE TITLE
azurerm_postgresql_flexible_server_active_directory_administrator - parallel jobs fails deployment 

### ISSUE THREAD

**Issue by ovie91** [hashicorp/terraform-provider-azurerm#19962]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.38.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_active_directory_administrator

### Terraform Configuration Files

```hcl
variable "aadIntegration" {
    default = [
    {
      aadObjectId      = "<removed>"
      aadPrincipalName = "<removed>"
      aadPrincipalType = "Group"
    },
    {
      aadObjectId      = "<removed>"
      aadPrincipalName = "<removed>"
      aadPrincipalType = "ServicePrincipal"
    }
  ]

}


resource "azurerm_postgresql_flexible_server_active_directory_administrator" "example" {
  count               = length(var.aadIntegration)
  server_name         = azurerm_postgresql_flexible_server.example.name
  resource_group_name = "<removed>"
  tenant_id           = "<removed>"
  object_id           = var.aadIntegration[count.index].aadObjectId
  principal_name      = var.aadIntegration[count.index].aadPrincipalName
  principal_type      = var.aadIntegration[count.index].aadPrincipalType
}
```

### Debug Output/Panic Output

```shell
azurerm_postgresql_flexible_server_active_directory_administrator.example[1]: Still creating... [1m0s elapsed]
azurerm_postgresql_flexible_server_active_directory_administrator.example[0]: Still creating... [1m0s elapsed]
azurerm_postgresql_flexible_server_active_directory_administrator.example[0]: Creation complete after 1m2s [<removed>] 

Error: creating Administrator (Subscription: "<removed>"
│ Resource Group Name: "<removed>"
│ Server Name: "<removed>"
│ Object: "<removed>"): polling after Create: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '<removed>'"
│ 
│   with azurerm_postgresql_flexible_server_active_directory_administrator.example[1],
│   on postgres.tf line 49, in resource "azurerm_postgresql_flexible_server_active_directory_administrator" "example":
│   49: resource "azurerm_postgresql_flexible_server_active_directory_administrator" "example" {
│
```

### Expected Behaviour

Terraform in parallel is able to add administrators to postgresql flexible server

### Actual Behaviour

Terraform fails when jobs are done in parallel

**Comment by ziyeqf** [comment]
Hi @ovie91 ,

Considering it's a preview feature (https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-azure-ad-authentication), and there is an error message `InternalServerError`, I assume it's not because of the provider. 

Could you please give it another try and the error still exists, maybe you can open a support case where should be safe to provide the tracking ID?

For any further questions, please leave comments

**Comment by ovie91** [comment]
Hi @ziyeqf,

Yes I'm aware that this is preview feature, my understanding that its possible to tweak terraform provider to not do things in parallel for specific resource.

I have ticket with MS but so far received that this is expected behavior, it cannot be upgrade at the same time. ( I believe same approach is with other databases and AAD integration)

**Comment by ziyeqf** [comment]
Thanks @ovie91 , I get your point about `parallel`, while my thought is if there should be a limit on parallel running, it should not be inside Terraform Provider. ( provider could be run in different machines at the same time ).
Will reach out to see if there will be an up-stream fix on Postgresql flexible server.

Thanks!

**Comment by ovie91** [comment]
It make sens, I forgot about this part :)

**Comment by ovie91** [comment]
Issue has been resolved
