### ISSUE TITLE
Support for Azure RBAC to manage Bastion Service resource access

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#19995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have attribute to enable Azure RBAC for Bastion Service to manage access through role assignments.

enable_rbac_authorization = true

### New or Affected Resource(s)/Data Source(s)

azurerm_bastion_host

### Potential Terraform Configuration

```hcl
resource "azurerm_bastion_host" "example" {
  name                = "examplebastion"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
    enable_rbac_authorization = true
  }
}
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems service API doesn't support it for now since I didn't find this new feature from azure rest api spec. If you happen to know, could you share the api link for this new feature? Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
