### ISSUE TITLE
Support for NSG attribute in Bastion Host resource

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#19994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful we could mention the Network Security Group id for the Bastion Host.

### New or Affected Resource(s)/Data Source(s)

azurerm_bastion_host

### Potential Terraform Configuration

```hcl
resource "azurerm_bastion_host" "example" {
  name                = "examplebastion"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
     network_security_group_id = azurerm_network_security_group.example-nsg.id
  }
}
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems service API doesn't support it for now since I didn't find this new feature from azure rest api spec. If you happen to know, could you share the api link for this new feature? Thanks.
