### ISSUE TITLE
Diagnostic Setting fails to apply if `logAnalyticsDestinationType` is set

### ISSUE THREAD

**Issue by cpressland** [hashicorp/terraform-provider-azurerm#20019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "i" {
    name = "diags"
    target_resource_id = azurerm_key_vault.i.id
    log_analytics_workspace_id = var.loganalytics_id

    enabled_log {
        category = "AuditEvent"
        retention_policy {
            days = 0
            enabled = false
        }
    }
}
```

### Debug Output/Panic Output

```shell
During Plan:
  # module.uksouth_sandbox_environment.azurerm_monitor_diagnostic_setting.add_kv["bink-uksouth-retail"] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "add_kv" {
        id                             = "<snipped>"
      - log_analytics_destination_type = "AzureDiagnostics" -> null
        name                           = "diags"
        # (2 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }


During Apply:
│ Error: at least one type of Log or Metric must be enabled
│ 
│   with module.uksouth_sandbox_environment.azurerm_monitor_diagnostic_setting.add_kv["bink-uksouth-retail"],
│   on ../tf-azurerm_environment/keyvault_additional.tf line 78, in resource "azurerm_monitor_diagnostic_setting" "add_kv":
│   78: resource "azurerm_monitor_diagnostic_setting" "add_kv" {
│
```

### Expected Behaviour

No change should be applied as the default IS AzureDiagnostics according to Documentation [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#log_analytics_destination_type)

### Actual Behaviour

We have a single diagnostic setting which has `"logAnalyticsDestinationType": "AzureDiagnostics"` set, while all other Diagnostics Settings have `"logAnalyticsDestinationType": null`.

AzureRM Provider appears to be trying to set `"AzureDiagnostics"` to `null` during a plan/apply, but the Azure API appears to be rejecting this.

I have destroyed other diagnostics settings, upon recreating them they always get set with `"AzureDiagnostics"` instead of `null`, this suggests an API change within Azure that the provider needs to handle better.

### Steps to Reproduce

1) Create a Diagnostic Setting via Terraform
2) `terraform plan` on the same Diagnostic Setting

**Comment by MoeTopaji** [comment]
Not sure what caused this behaviour but deleting the diagnostic settings on the portal and re-running the pipeline fixed it for me. I re-ran the pipeline several times after that and no issues

**Comment by cpressland** [comment]
I’ll try deleting a few diagnostics settings this morning - I can confirm they create just fine, but then on a second run they all want to be updated.

**Comment by teowa** [comment]
Hi @cpressland , thanks for submitting issue!
About the `log_analytics_destination_type`, recently service has changed API behaviour, returns the `log_analytics_destination_type: AzureDiagnostics` even if we don't set it in API request. But this should not fail the apply process. I will try to amend the code to suppress the plan diff.

From the provided error message `Error: at least one type of Log or Metric must be enabled`, the apply failure should caused by lack of an enabled log or metrics. Please check the `add_kv` diagnostic setting.

**Comment by cpressland** [comment]
So this is fun, tainting and replacing Diagnostic Settings gives me a completely random chance of getting `"logAnalyticsDestinationType": "AzureDiagnostics"` or `"logAnalyticsDestinationType": null`. So the issue is a lot harder to replicate consistently.

**Comment by thrubovc** [comment]
I have the same problem. Removing the diagnostic setting manually worked for me as a workaround to fix my terraform apply!

**Comment by jackyou84** [comment]
terraform always report drift after upgrade to 3.40
```
# azurerm_monitor_diagnostic_setting.anthem_keyvault_oms_auditing will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "anthem_keyvault_oms_auditing" {
        id                             = ""
      + log_analytics_destination_type = "AzureDiagnostics"
        name                           = "anthemcustomsaudit"
        # (2 unchanged attributes hidden)

        # (4 unchanged blocks hidden)
    }
```

**Comment by 4c74356b41** [comment]
```
resource "azurerm_monitor_diagnostic_setting" "network_security_groups" {
  for_each = local.network_security_groups

  name                           = "${each.key}-diagnostic-setting"
  target_resource_id             = yyy
  log_analytics_workspace_id     =  xxx
  log_analytics_destination_type = "AzureDiagnostics"

  enabled_log {
    category_group = "allLogs"

    retention_policy {
      enabled = false
      days    = 0
    }
  }
}
```
constant updates

**Comment by 4c74356b41** [comment]
@teowa does it work for you?

**Comment by teowa** [comment]
Please see https://github.com/hashicorp/terraform-provider-azurerm/issues/20140

**Comment by Soufianux** [comment]
Same in 3.42.0 .  it's still reporting update of locanalytics_destination_type without taking any effect after apply: 

 resource "azurerm_monitor_diagnostic_setting" "logs" {
        id                             = "/subscriptions/xxxxxx-xxxxx-xxxxx-xxxx-xxxxxxxxresourceGroups/xxxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxxx|Diagnostic_logs"
      + log_analytics_destination_type = "AzureDiagnostics"
        name                           = "Diagnostic_logs"

**Comment by cpressland** [comment]
Yep, no change in behaviour on 3.42.0 for me.
