### ISSUE TITLE
Parsing error when importing azurerm_iothub

### ISSUE THREAD

**Issue by jvanbuel** [hashicorp/terraform-provider-azurerm#20020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_iothub

### Terraform Configuration Files

```hcl
resource "azurerm_iothub" "hub" {
}
```

### Debug Output/Panic Output

```shell
azurerm_iothub.hub: Importing from ID "/subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Devices/IotHubs/xxxxxxxxxx”…
╷
│ Error: parsing Resource ID "/subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Devices/IotHubs/xxxxxxxxxx”: ID was missing the `iotHubs` element
```

### Expected Behaviour

azurerm_iothub.hub: Importing from ID "/subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Devices/iotHubs/xxxxxxxxxx"...
azurerm_iothub.hub: Import prepared!
  Prepared azurerm_iothub for import
azurerm_iothub.hub: Refreshing state... [id=/subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Devices/iotHubs/xxxxxxxxxx]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

### Actual Behaviour

The import failed when using the ResourceID from the Azure Portal. When manually changing `IotHubs` to `iotHubs` in the ResourceID, the import succeeds.

### Steps to Reproduce

`terraform import /subscriptions/xxxxxxxxxxxx/resourceGroups/xxxxxxxxx/providers/Microsoft.Devices/IotHubs/xxxxxxxxxx`

**Comment by jvanbuel** [comment]
Possibly there was an upstream change in the API? 

When changing the resource IDs in `resourceids.go` so that they contain `IotHubs` instead of `iotHubs`, and  `go generate` the parsing and validation code, the import is succesful, and all other acceptance tests seem to run succesfully as well. 

Not sure if that is the way forward, but if so, I'd happily create a PR.

**Comment by myc2h6o** [comment]
Hi @jvanbuel thanks for opening the issue! Similar to #19100, AzureRM provider restrict the casing of some segments like provider name so that the ID could be consistent across the provider. Thus you would need to use `iotHubs` to import the resource

**Comment by jvanbuel** [comment]
Thanks for the clarification @myc2h6o! I should've looked a bit harder. :) Now also found this [relevant SO](https://stackoverflow.com/questions/62651102/the-terraform-cli-get-a-error-id-was-missing-the-slots-element).
