### ISSUE TITLE
Invalid SKU capacity provided, the SKU Standard_D11_V2 should be between 2 and 8

### ISSUE THREAD

**Issue by holms** [hashicorp/terraform-provider-azurerm#20024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kusto_cluster" "setupad" {
  name                = "setupad"
  location            = azurerm_resource_group.analytics.location
  resource_group_name = azurerm_resource_group.analytics.name
  auto_stop_enabled   = true
  language_extensions = ["PYTHON"]
  engine              = "V3"

  sku {
    name     = "Standard_D11_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  optimized_auto_scale {
    minimum_instances = 1
    maximum_instances = 6
  }

  tags = {
    Environment = "Kusto"
  }
}

```

### Debug Output/Panic Output

```shell
│ Error: creating/updating Cluster: (Name "setupad" / Resource Group "analytics"): kusto.ClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Invalid SKU capacity provided, the SKU Standard_D11_v2 should be between 2 and 8"
│ 
│   with azurerm_kusto_cluster.setupad,
│   on azure-kusto.tf line 6, in resource "azurerm_kusto_cluster" "setupad":
│    6: resource "azurerm_kusto_cluster" "setupad" {
│ 
╵
```

### Expected Behaviour

Should create a cluster with sku Standard_D11_V2.

### Actual Behaviour

As per documentation it's stated:

```
If no optimized_auto_scale block is defined, then the capacity is required. ~> NOTE: If an optimized_auto_scale block is defined and no capacity is set, then the capacity is initially set to the value of minimum_instances.
```

So there's no need to specify capacity because by default it will be value of minimum_instances, but as you can see it fails even when optimized_auto_scale block is defined

**Comment by holms** [comment]
Okay my bad, in documentation it nowhere says that capacity for some SKU's must be more than 1. Definitely would be nice to mention it somewhere. This issue can be closed if OP thinks that it shouldn't be in docs.

**Comment by liuwuliuyun** [comment]
Hi @holms, in doc of azure, they do list skus [here](https://learn.microsoft.com/en-us/rest/api/azurerekusto/clusters/create-or-update?tabs=HTTP#azuresku) but the skus you mentioned are newly supported so the doc could be outdated or incomplete like you said.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @liuwuliuyun‘s response as an answer.
