### ISSUE TITLE
azurerm_app_configuration_key - while parsing resource ID: the number of path segments is not divisible by 2

### ISSUE THREAD

**Issue by vishalpant** [hashicorp/terraform-provider-azurerm#20038]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.5

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration_key" "this" {
  for_each               = fileset("${path.cwd}/configurations/${terraform.workspace}", "*")
  configuration_store_id = var.app_config_id
  key                    = upper(split(".", each.key)[0])
  type                   = "kv"
  value                  = file("${path.cwd}/configurations/${terraform.workspace}/${each.value}")
}
```

### Debug Output/Panic Output

```shell
Error: while parsing resource ID: while parsing resource ID: the number of path segments is not divisible by 2 in "subscriptions/[MASKED]/resourceGroups/[MASKED]providers/Microsoft.AppConfiguration/configurationStores/[MASKED]AppConfigurationKey/SAMPLE%2FLabel%2F%00%2FAppConfigurationKey%2FSAMPLE/Label"
│ 
│   with azurerm_app_configuration_key.this["sample.json"],
│   on main.tf line 35, in resource "azurerm_app_configuration_key" "this":
│   35: resource "azurerm_app_configuration_key" "this" {
│ 
│ while parsing resource ID: while parsing resource ID: the number of path
│ segments is not divisible by 2 in
│ "subscriptions/[MASKED]/resourceGroups/[MASKED]providers/Microsoft.AppConfiguration/configurationStores/[MASKED]AppConfigurationKey/SAMPLE%2FLabel%2F%00%2FAppConfigurationKey%2FSAMPLE/Label"
```

### Expected Behaviour

The provider should be able to detect the changes in the sample.json file and update the key in App Configuration.

### Actual Behaviour

The terraform plan fails with the following error

`Error: while parsing resource ID: while parsing resource ID: the number of path segments is not divisible by 2`

**Comment by valakson** [comment]
I can confirm the same issue. Can someone please accept/adjust the PR so the issue would be fixed?

**Comment by lukerogers** [comment]
I set my azurerm provider version at 3.30.0 and it still works, so I'm stuck there until this is resolved.

**Comment by elialombardi** [comment]
I'm using version 3.46.0 and I'm having this error:

```
Error: while parsing resource ID: while parsing resource ID: the number of path segments is not divisible by 2 in "subscriptions/[xxx]/resourceGroups/x-y-z/providers/Microsoft.AppConfiguration/configurationStores/z-x-c/AppConfigurationKey/my%3Acustom%3Akey%2FLabel%2F%00%2FAppConfigurationKey%2Fmy%3Acustom%3Akey/Label"
```

If I switch to version 3.33.0 it works perfectly.

**Comment by Kiran-Ruby1402** [comment]
If I'm using Azurerm version from 3.39.0 to 3.48.0 getting below error:

`subscriptions/XXXXXXXXX/rg/dev-rg/providers/Microsoft.AppConfiguration/configurationStores/appcs001/AppConfigurationKey/%2Fapi%2Flogging.level.com.abcd%2FLabel%2F%00%2FAppConfigurationKey%2F%2Fapi%2Flogging.level.com.abcd/Label`

If I use 3.38.0 it's working fine, Can please help me to resolve this issue
