### ISSUE TITLE
`azurerm_kubernetes_cluster` always wants to modify `api_server_access_profile` when using `optional()`

### ISSUE THREAD

**Issue by cpressland** [hashicorp/terraform-provider-azurerm#20037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
variable "cluster" {
    type = object({
        api_ip_ranges = optional(list(string))
    })
}

resource "azurerm_kubernetes_cluster" "i" {
    api_server_access_profile {
        authorized_ip_ranges = var.cluster.api_ip_ranges
    }
}
```

### Debug Output/Panic Output

```shell
# module.uksouth_dev_environment.module.aks["dev"].azurerm_kubernetes_cluster.i will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "i" {
        id                                  = "<snipped>"
        name                                = "uksouth-dev"
        tags                                = {}
        # (28 unchanged attributes hidden)

      + api_server_access_profile {
          + authorized_ip_ranges     = (known after apply)
          + vnet_integration_enabled = false
        }

        # (9 unchanged blocks hidden)
    }

  # module.uksouth_sandbox_environment.module.aks["sandbox"].azurerm_kubernetes_cluster.i will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "i" {
        id                                  = "<snipped>"
        name                                = "uksouth-sandbox"
        tags                                = {}
        # (28 unchanged attributes hidden)

      + api_server_access_profile {
          + authorized_ip_ranges     = (known after apply)
          + vnet_integration_enabled = false
        }

        # (9 unchanged blocks hidden)
    }

  # module.uksouth_staging_environment.module.aks["staging"].azurerm_kubernetes_cluster.i will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "i" {
        id                                  = "<snipped>"
        name                                = "uksouth-staging"
        tags                                = {}
        # (28 unchanged attributes hidden)

      + api_server_access_profile {
          + authorized_ip_ranges     = (known after apply)
          + vnet_integration_enabled = false
        }

        # (9 unchanged blocks hidden)
    }
```

### Expected Behaviour

`terraform plan` should not detect any changes

### Actual Behaviour

`terraform plan` incorrectly requests changes

### Steps to Reproduce

1) Build an AKS Cluster with any basic config using the new `api_server_access_profile` block, where the `authorized_ip_ranges` field refers to an optional variable.
2) Run `terraform plan -out=out` and `terraform apply out`
3) Repeat Step 2, the same changes should be requested again, this is incorrect.

**Comment by ms-henglu** [comment]
Hi @cpressland ,

Thank you for taking time to report this issue!

I have a workaround for this, the following example uses dynamic blocks to achieve the conditional block

```hcl

locals {
  ips = []
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestakshenglu"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestakshenglu"

  default_node_pool {
    name           = "default"
    node_count     = 1
    vm_size        = "Standard_DS2_v2"
    vnet_subnet_id = azurerm_subnet.test.id
  }

  identity {
    type = "SystemAssigned"
  }

  network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "standard"
  }


  dynamic "api_server_access_profile" {
    for_each = toset(length(local.ips) != 0 ? ["dummy"] : [])
    content {
      authorized_ip_ranges     = local.ips
      vnet_integration_enabled = false
    }
  }
}
```

**Comment by joselcaguilar** [comment]
@ms-henglu The removal is not working as expected, at least in my case even removing completely the `api_server_access_profile` block from `main.tf`, the `authorized_ip_ranges` are not disabled.

**Comment by cpressland** [comment]
@joselcaguilar this sounds like it could be a separate issue with removing that block. @ms-henglu this workaround appears to work fine for me. Thanks!

**Comment by joselcaguilar** [comment]
> @joselcaguilar this sounds like it could be a separate issue with removing that block. @ms-henglu this workaround appears to work fine for me. Thanks!

Np, new issue #20085 opened.

**Comment by manicminer** [comment]
Since it looks like the original issue has a decent workaround, I'm going to close this issue for now. If you think this would better be resolved differently, please comment again and we'll be happy to take another look. Thanks!
