### ISSUE TITLE
azurerm_app_service site_config dotnet_version v7.0 is still missing

### ISSUE THREAD

**Issue by AndreasKummerAT** [hashicorp/terraform-provider-azurerm#20035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

azurerm_app_service site_config dotnet_version **v7.0** is still missing in 3.39.1!

BR Andreas

### New or Affected Resource(s)/Data Source(s)

azurerm_app_service

**Comment by xiaxyi** [comment]
Thanks @AndreasKummerAT for raising this issue.`azurerm_app_service` resource is about to be deprecated and we may not maintain it. Can you try using the new resource provider `azurerm_windows_web_app` and `azurerm_linux_web_app` instead?

dotnet 7 is supported:https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app#dotnet_version

**Comment by xiaxyi** [comment]
@AndreasKummerAT may I know if you have any follow up questions?

**Comment by wil-vse** [comment]
Hi Team, Any updates on when v7.0 will be added to Function Apps and WebApps?

**Comment by rcskosir** [comment]
Thanks for opening this issue. The azurerm_app_service resource is deprecated and will be removed in future versions of the provider as noted above by @xiaxyi, as such this is not an enhancement that we are going to make on the deprecated resource, so I am going to close this issue.
