### ISSUE TITLE
Support for kusto cosmosdb data connection

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#20059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello, 

could you please add the support for the CosmosDB type of data connection? The best current workaround I have found is with azapi provider, documented here: https://learn.microsoft.com/en-us/azure/templates/microsoft.kusto/clusters/databases/dataconnections?pivots=deployment-language-terraform

### New or Affected Resource(s)/Data Source(s)

azurerm_kusto_cosmosdb_data_connection

**Comment by liuwuliuyun** [comment]
Sounds like a reasonable request, I will look into the swagger and working on the coding part.

**Comment by liuwuliuyun** [comment]
Hi @JiriKovar, this resource is supported now. See https://github.com/hashicorp/terraform-provider-azurerm/pull/22295
