### ISSUE TITLE
Azure Defender for Data Services settings are not supported on resources of type managedInstances

### ISSUE THREAD

**Issue by wayne-orego-cap** [hashicorp/terraform-provider-azurerm#20067]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_advanced_threat_protection

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
See attached image
```

### Expected Behaviour

According to Microsofts documentation, Azure SQL Managed Instances should have support for Defender
https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-sql-introduction

### Actual Behaviour

<img width="719" alt="image" src="https://user-images.githubusercontent.com/115114525/212980577-f33d1aa3-aba3-4bea-b0c9-9f1cb6e5e54e.png">

### Steps to Reproduce

terraform init
terraform plan
terraform apply

**Comment by sinbai** [comment]
@wayne-orego-cap thanks for opening this issue. After checking Terraform code, the Azure API returned the above error instead of Terraform. So it seems that actually it's not supported yet and Terraform could do anything for it.

**Comment by wayne-orego-cap** [comment]
> @wayne-orego-cap thanks for opening this issue. After checking Terraform code, the Azure API returned the above error instead of Terraform. Per the error message, it seems that it's not supported yet and Terraform could not do anything for it. Could you reach out to MS to ask whether this feature is supported?

Where would I go to reach out to MS?

**Comment by sinbai** [comment]
@wayne-orego-cap [This API](https://github.com/Azure/azure-rest-api-specs/blob/8ba5121a93e44a6ab53e4bc12a56f96829e47a91/specification/security/resource-manager/Microsoft.Security/stable/2019-01-01/advancedThreatProtectionSettings.json#L48) returns the above error. You could contact MS by opening an issue [here](https://github.com/Azure/azure-rest-api-specs/issues).

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
