### ISSUE TITLE
azurerm_application_insights_standard_web_test resource with validation_rules block fails with Error code: PropertyMissingForKind

### ISSUE THREAD

**Issue by jussiheinonen** [hashicorp/terraform-provider-azurerm#20064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.2

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

azurerm_application_insights_standard_web_test

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.2.1"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.39.1"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = "change_this"
}

data "azurerm_application_insights" "this" {
  name                = "appinsight-app01"
  resource_group_name = "rg-appinsight"
}

# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_standard_web_test
resource "azurerm_application_insights_standard_web_test" "example" {
  name                    = "std-web-test"
  resource_group_name     = "rg-appinsight"
  location                = "UK South"
  application_insights_id = data.azurerm_application_insights.this.id
  geo_locations           = [ "emea-gb-db3-azr" ]
  
  request {
    url = "https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_standard_web_test"
  }

  validation_rules {
    ssl_check_enabled    = true
  }

}
```

### Debug Output/Panic Output

```shell
azurerm_application_insights_standard_web_test.example: Creating...
╷
│ Error: creating Web Test (Subscription: "change_this"
│ Resource Group Name: "rg-appinsight"
│ Web Test Name: "std-web-test"): webtestsapis.WebTestsAPIsClient#WebTestsCreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Specified argument was out of the range of valid values.\r\nParameter name: Error code: PropertyMissingForKind. Web test 'std-web-test' is invalid. 'ValidationRules.ContentValidation' property is provided, a required property 'ValidationRules.ContentValidation.ContentMatch' is missing or empty for 'standard' web test" InnerError={"trace":["System.ArgumentOutOfRangeException"]}
│ 
│   with azurerm_application_insights_standard_web_test.example,
│   on azurerm_application_insights_standard_web_test.tf line 24, in resource "azurerm_application_insights_standard_web_test" "example":
│   24: resource "azurerm_application_insights_standard_web_test" "example" {
```

### Expected Behaviour

Standard Web Test is created when `validation_rules` block in the resource definition is not present.

### Actual Behaviour

Adding a simple validation rule block into resource...

``` 
validation_rules {
    ssl_check_enabled    = true
  }
``` 
...results in error.

The error message implies that the property named `kind` or `web-test-kind` is missing and such property should carry a value `standard` 

Microsoft [documentation for Standard Web Test](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/2020-10-05-preview/webtests?pivots=deployment-language-bicep#webtestproperties) specifies Kind as a required property.

I've validated this by creating equivalent Standard Web Test using `az` command line tool. 
Creation only works when including a flag `--web-test-kind standard` in the command like `az monitor app-insights web-test create --web-test-kind standard  --location "UK South" ....`

Attempting to create a Standard Web Test without a flag `--web-test-kind standard` results in error similar to what Azurerm v.3.39.1 is reporting. 

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by aristosvo** [comment]
@jussiheinonen I'll take a look later this week!

**Comment by jussiheinonen** [comment]
Tested in v3.42.0 and creating azurerm_application_insights_standard_web_test with validation_rules block works as well.
Thanks for speedy response!
