### ISSUE TITLE
Related to issue 12288: I have updated to the 2.68.0 azurerm provider and still getting the "MissingRequiredParameter" error

### ISSUE THREAD

**Issue by mudman2k** [hashicorp/terraform-provider-azurerm#20066]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

2.68.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "cpro-prod-east" {
  name                   = "aaaotcproprodeastus-paasdb"
  resource_group_name    = data.azurerm_resource_group.cpro-east.name
  location               = data.azurerm_resource_group.cpro-east.location
  version                = "12"
  delegated_subnet_id    = data.azurerm_subnet.cpro-east.id
  zone                   = "1"

  storage_mb = 32768

  sku_name   = "GP_Standard_D4s_v3"
  depends_on = [azurerm_private_dns_zone_virtual_network_link.cpro-east]

}
```

### Debug Output/Panic Output

```shell
│ Error: creating Postgresql Flexible Server "aaaotcproprodeastus-paasdb" (Resource Group "aa-aot-cpro-prod-eastus-rg"): postgresqlflexibleservers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="MissingRequiredParameter" Message="Parameter 'PrivateDnsZoneArmResourceId' must be specified. This parameter cannot be NULL or empty."
│
│   with azurerm_postgresql_flexible_server.cpro-prod-east,
│   on postgres.tf line 21, in resource "azurerm_postgresql_flexible_server" "cpro-prod-east":
│   21: resource "azurerm_postgresql_flexible_server" "cpro-prod-east" {
```

### Expected Behaviour

Postgres Flexible Server should be created with Private Connection to Subnet. 

### Actual Behaviour

Resource doesn't create and error displayes

### Steps to Reproduce

terraform apply -target azurerm_postgresql_flexible_server.cpro-prod-east

### References

I researched https://github.com/hashicorp/terraform-provider-azurerm/issues/12053 and updated the Provider in my provider.tf file.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume you missed property `private_dns_zone_id`. See more details from [TF doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#private_dns_zone_id).

Sample:
```
resource "azurerm_postgresql_flexible_server" "test" {
  name                   = "acctest-fs-test01"
  resource_group_name    = azurerm_resource_group.test.name
  location               = azurerm_resource_group.test.location
  administrator_login    = "adminTerraform"
  administrator_password = "123wsxBDF"
  version                = "12"
  storage_mb             = 32768
  delegated_subnet_id    = azurerm_subnet.test.id
  sku_name               = "GP_Standard_D2s_v3"
  zone                   = "1"
  private_dns_zone_id    = azurerm_private_dns_zone.test.id

  depends_on = [azurerm_private_dns_zone_virtual_network_link.test]
}
```

**Comment by mudman2k** [comment]
Thanks @neil-yechenwei. It is working now. 

I am appreciative. I have that private_dns_zone_id parameter set but it apparently wanted to misbehave. I fixed a typo and it is processing. 

Thanks again
