### ISSUE TITLE
Support for disabling the Azure ML compute CLuster \ Instance  public IP Support for [thing]

### ISSUE THREAD

**Issue by sahitya12** [hashicorp/terraform-provider-azurerm#20078]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for disabling the Azure ML compute Cluster / instance  public IP

https://learn.microsoft.com/en-us/azure/machine-learning/how-to-secure-training-vnet?tabs=ipaddress

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_compute_cluster

**Comment by aristosvo** [comment]
This is at this moment in time opt-in preview, which makes it harder to develop this solution now.

> Using the no public IP configuration requires you to opt-in to this preview. Before opting in, you must have created a workspace and a compute instance on the subscription you plan to use. You can delete the compute instance and/or workspace after creating them.

**Comment by Lucasjuv** [comment]
The node_public_ip_enabled parameter for the compute cluster was merged. There is an API not returning the property for the compute instance that blocks the state refresh.

**Comment by Lucasjuv** [comment]
I have opened this issue on the auto rest repo https://github.com/Azure/azure-rest-api-specs/issues/24324. After some testing I believe this option can be implemented by reading the value for the public ip.

**Comment by Lucasjuv** [comment]
I believe this can be closed right now. The option is available in version 3.60.
