### ISSUE TITLE
Support for enabling private link for Azure Cognitive Service accounts

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if there could be an attribute that enables private link for restricting access to Cognitive Services. 

 private_link_enabled = “true”

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_account 

### Potential Terraform Configuration

```hcl
resource "azurerm_cognitive_account" "example" {
  name                = "example-account"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "Face"
  sku_name = "S0"
 
 private_link_enabled = “true”
  
}
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it has been supported by [azurerm_private_endpoint ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint)and [azurerm_private_link_service](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_link_service).

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If that is not the case, please provide additional information, thanks!
