### ISSUE TITLE
Support for Zone Type in DNS Zone

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if the attribute "zone_type" to mention the DNS zone type is included in the terraform resource "azurerm_dns_zone". The REST API has the attribute in it. Please find the link below.

https://learn.microsoft.com/en-us/rest/api/dns/zones/create-or-update?tabs=HTTP#zonetype

### New or Affected Resource(s)/Data Source(s)

azurerm_dns_zone

### Potential Terraform Configuration

```hcl
resource "azurerm_dns_zone" "example-public" {
  name                = "mydomain.com"
  resource_group_name = azurerm_resource_group.example.name
  zone_type = "Private"
}
```

**Comment by aristosvo** [comment]
Hi @ramyaradhakrishnan108!

Are you looking for [azurerm_private_dns_zone](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_dns_zone) or is there some other functionality you are looking for?
