### ISSUE TITLE
Support for IP addresses of forwarding zone targets

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if there is  attribute in the DNS resource "azurerm_dns_zone" to mention the IP addresses of forwarding zone targets.

### New or Affected Resource(s)/Data Source(s)

azurerm_dns_zone

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems service API doesn't support it for now since I didn't find this feature from azure rest api spec. If you happen to know, could you share the doc link or rest api link? Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
