### ISSUE TITLE
Support for azurerm_linux_web_app HTTP version http2_enabled 

### ISSUE THREAD

**Issue by javierlegidoatnestle** [hashicorp/terraform-provider-azurerm#20104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

First of all many thanks to everybody involved in this project for their time, I really appreciate it.

I would like to have [http2_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#http2_enabled) but for [linux_web_app](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app), thanks

### New or Affected Resource(s)/Data Source(s)

linux_web_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "example" {
  http2_enabled       = true
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}
}
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#http2_enabled
https://github.com/hashicorp/terraform-provider-azurerm/issues/9422

**Comment by jbinko** [comment]
You can do it Today via site_config + http2_enabled

resource "azurerm_linux_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
     http2_enabled = true
  }
}

@tombuildsstuff: I believe this can be closed as resolved

**Comment by javierlegidoatnestle** [comment]
Confirmed, it works, thanks
