### ISSUE TITLE
Support for RBAC and ACL for Storage account access

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20117]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to have attribute to allow ACL and RBAC for granting appropriate storage account access.

enable_rbac_authorization = true

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "examplestorageacc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
 enable_rbac_authorization = true
}
```

**Comment by aristosvo** [comment]
Hi @ramyaradhakrishnan108!

Can you explain which functionality you are looking for? RBAC Authorization is available by default, RBAC authentication is not enabled by default for all storage services.

**Comment by rcskosir** [comment]
@ramyaradhakrishnan108 Thank you for taking the time to open this issue. I am going to mark it as closed with the answer provided by @aristosvo. If that answer does not resolve this issue for you, please add a comment with the additional information requested regarding functionality, thanks again!
