### ISSUE TITLE
Support for disallowing external service integration with Defender

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to have terraform support to disallow the integration of Defender with any third party or external service.

**Comment by manicminer** [comment]
Thanks for raising this issue. Unfortunately you have not provided any information about your feature request other than the issue title, and this is not enough for us to work with. Please re-submit your feature request, providing a description of the feature you are looking for, and a potential Terraform configuration that you would like to see. This does not need to be perfect, but providing this really helps a maintainer working on your proposed feature. Thanks!
