### ISSUE TITLE
Support for Managed HSM role assignments

### ISSUE THREAD

**Issue by creste** [hashicorp/terraform-provider-azurerm#20112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for [creating](https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/role-management#assign-role-for-a-specific-key), [listing](https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/role-management#list-existing-role-assignments), and [deleting](https://learn.microsoft.com/en-us/azure/key-vault/managed-hsm/role-management#delete-a-role-assignment) Managed HSM role assignments for a specific key.

When I attempt to create a managed HSM role assignment with `azurerm_role_assignment`:

```hcl
resource "azurerm_role_assignment" "example" {
  scope = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourcegroup/providers/Microsoft.KeyVault/managedHSMs/hsmname"
  role_definition_name = "Managed HSM Crypto Service Release User"
  principal_id = azurerm_user_assigned_identity.example.principal_id
}
```

I see this error:

> Error: loading Role Definition List: could not find role 'Managed HSM Crypto Service Release User'

Using `role_definition_id` instead of `role_definition_name` fails with this error:

>The role definition ID 'Microsoft.KeyVault/providers/Microsoft.Authorization/roleDefinitions/21dbd100-6940-42c2-9190-5d6cb909625c' is not valid.

Also, it is not clear how to specify a key scope when using `azurerm_role_assignment`.

### New or Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_role_assignment" "example" {
  scope = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourcegroup/providers/Microsoft.KeyVault/managedHSMs/hsmname/keys/keyname"
  role_definition_name = "Managed HSM Crypto Service Release User"
  principal_id = azurerm_user_assigned_identity.example.principal_id
}
```

### References

This [StackOverflow post](https://stackoverflow.com/a/70508925) shows a workaround:
```hcl
resource "null_resource" "roleassignkv" {
  provisioner "local-exec" {
    command = <<EOT
    az keyvault role assignment create --hsm-name ${azurerm_key_vault_managed_hardware_security_module.example.name} --role "Managed HSM Crypto Service Encryption User" --assignee ${azurerm_storage_account.example.identity[0].principal_id} --scope /keys
    az keyvault role assignment create --hsm-name ${azurerm_key_vault_managed_hardware_security_module.example.name} --role "Managed HSM Crypto User" --assignee ${data.azurerm_client_config.current.object_id} --scope /
    az keyvault key create --hsm-name ${azurerm_key_vault_managed_hardware_security_module.example.name} --name storageencryptionkey --ops wrapKey unwrapKey --kty RSA-HSM --size 3072
    EOT
    interpreter = [
      "PowerShell","-Command"
    ]
  }
  depends_on = [
    null_resource.securityDomain,
    azurerm_storage_account.example
  ]
}
```

**Comment by tombuildsstuff** [comment]
This is now available via [`azurerm_key_vault_managed_hardware_security_module_role_assignment `](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_managed_hardware_security_module_role_assignment) as @wuxu92 has mentioned above
