### ISSUE TITLE
Support for namespace in Kubernetes Resources

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful if there there is attribute in Terraform resource - "azurerm_kubernetes_cluster" under azurerm provider to mention the namespace(default, kube-system or kube-public) of the Kubernetes resources. Kubernetes resources, such as pods and deployments, are logically grouped into a namespace to divide an AKS cluster and restrict create, view, or manage access to resources.

https://learn.microsoft.com/en-us/azure/aks/concepts-clusters-workloads#namespaces

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by aristosvo** [comment]
Hi @ramyaradhakrishnan108! I've seen a lot of feature request popping up the last few days from your side. In general we're welcoming these, and also this one has something to it I must say.

But we aren't the one-stop shop it seems like you're using it now for. It would be a bit more helpful if you'd investigate before making this request if this is existing functionality or that this is actually a feature request for Microsoft/Azure. There is no AKS API exposing the possibility to create an AKS namespace (AFAIK) thus far, it is possible however to create a Kubernetes namespace with the [Kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs).

As I think this answers your question, I'll close this issue for now. If there are any questions regarding that or reasons to reopen, let me know!
