### ISSUE TITLE
Support for Bastion Host to interact with AKS nodes

### ISSUE THREAD

**Issue by ramyaradhakrishnan108** [hashicorp/terraform-provider-azurerm#20126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to have Terraform support to have a bastion host configured to interact with AKS nodes.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster, azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  
  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }
}
resource "azurerm_bastion_host" "example" {
  name                = "examplebastion"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  bastion_host_id       = azurerm_bastion_host.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1

  tags = {
    Environment = "Production"
  }
}
```

**Comment by aristosvo** [comment]
Hi @ramyaradhakrishnan108! Like mentioned before, I've seen a lot of feature request popping up the last few days from your side. In general we're welcoming these, and also this one has something to it I must say.

But we aren't the one-stop shop it seems like you're using it now for. It would be a bit more helpful if you'd investigate before making this request if this is existing functionality we can expose via Terraform or that this is actually a feature request for Microsoft/Azure. There is no Azure API exposing the possibility to do this, so please report that to Azure/Microsoft and ask for exposure of that functionality via Terraform afterwards.

As I think this answers your question, I'll close this issue for now. If there are any questions regarding that or reasons to reopen, let me know!
