### ISSUE TITLE
Application Gateway CustomV2 and TLSv1_3 seems to not work properly

### ISSUE THREAD

**Issue by drs143** [hashicorp/terraform-provider-azurerm#20135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
ssl_profile {
    name = "default-ssl-profile"
    ssl_policy {
      policy_type = "CustomV2"
      min_protocol_version = "TLSv1_3"
      cipher_suites        = ["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"]
    }
  }
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

The policy of type CustomV2 is created along with cipher_suites defined in the list.

### Actual Behaviour

Even if terraform plan shows correct changes to be applied, predefined policy AppGwSslPolicy20150501 appears in the portal after terraform apply.

### Steps to Reproduce

Create an application_gateway service with ssl_profile containing this ssl_policy:

  ssl_profile {
    name = "default-ssl-profile"
    ssl_policy {
      policy_type = "CustomV2"
      min_protocol_version = "TLSv1_3"
      cipher_suites        = ["TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"]
    }
  }

**Comment by fabiomarinetti** [comment]
Same if I set 

`min_protocol_version = "TLSv1_2"`

**Comment by rajesh-shanmugasundaram8** [comment]
Hi Team , Any feedback on this reported issue.

**Comment by javiervelamindcurv** [comment]
Hello team!

Any update?

**Comment by rajesh-shanmugasundaram8** [comment]
Hello team!

Any update?

**Comment by maxburke** [comment]
Any updates on this issue?

**Comment by rebla** [comment]
Hello, any updates?

**Comment by rajesh-shanmugasundaram8** [comment]
HI Team,

Any feedback on this topic.

**Comment by maxburke** [comment]
@manicminer Any idea if work on this is planned? Or are there any known workarounds to managing TLSv1.3 settings on application gateways with Terraform with the current functionality as is?

**Comment by jakie1971** [comment]
@stephybun We also have the same issue and after some testing I would like to add the following information to this issue: 

After running the terraform apply to deploy the customv2 SSL policy we checked the Azure application gateway activity log details for this action. In the json output that is shown in the Azure activity log it shows the following for the ssl policy update done by Terraform:

\"sslPolicy\":{},

So Terraform provider seems to create an empty sslPolicy object which results in Azure for the SSL policy being reverted to the predefined one.

**Comment by javiervelamindcurv** [comment]
any update?

**Comment by palmerabollo** [comment]
This issue means it's not possible to automate the creation of an Azure Application Gateway supporting TLSv1_3

Is there a way we can debug or try help fix this issue? I'm happy to help but I'm not familiar with the code nor the internals of terraform providers.

I've tried to add a new test similar to an existing one
https://github.com/hashicorp/terraform-provider-azurerm/blob/454ba5b69447e65370fb572b697d2b19d0fcc4d0/internal/services/network/application_gateway_resource_test.go#L876 

and try to make it fail. No luck so far. But this is me when I write golang code:

![giphy](https://github.com/hashicorp/terraform-provider-azurerm/assets/673420/3e106b84-3f32-4958-bf6a-5fa8b093c063)

**Comment by stephybun** [comment]
@palmerabollo yup you've found the bug. A rather simple one to fix so apologies for it taking so long.

There's some strange behaviour with the ciphers - you can't actually supply the mandatory ones because the API will error saying they're not supported but I'm assuming they will be set by the API. Either way if that becomes problematic aswell please do raise another issue.
