### ISSUE TITLE
`azurerm_monitor_diagnostic_setting` allways want to change `log_analytics_destination_type` from empty to `AzureDiagnostics` starting with 3.40.0

### ISSUE THREAD

**Issue by StefanSchoof** [hashicorp/terraform-provider-azurerm#20140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "subscription" {
  name                       = "Subscription"
  target_resource_id         = data.azurerm_subscription.current.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.log_analytics.id

  enabled_log {
    category = "Administrative"
  }
  enabled_log {
    category = "Alert"
  }
  enabled_log {
    category = "Recommendation"
  }
  enabled_log {
    category = "ResourceHealth"
  }
  enabled_log {
    category = "Security"
  }
  enabled_log {
    category = "ServiceHealth"
  }
}
```

### Debug Output/Panic Output

```shell
{"@level":"info","@message":"azurerm_monitor_diagnostic_setting.subscription: Plan to update","@module":"terraform.ui","@timestamp":"2023-01-20T17:05:28.962335Z","change":{"resource":{"addr":"azurerm_monitor_diagnostic_setting.subscription","module":"","resource":"azurerm_monitor_diagnostic_setting.subscription","implied_provider":"azurerm","resource_type":"azurerm_monitor_diagnostic_setting","resource_name":"subscription","resource_key":null},"action":"update"},"type":"planned_change"}
```

### Expected Behaviour

No changes to the `azurerm_monitor_diagnostic_setting` is planed

### Actual Behaviour

In every plan `azurerm_monitor_diagnostic_setting` wants to set `log_analytics_destination_type`again to `AzureDiagnostics`.
![grafik](https://user-images.githubusercontent.com/4662023/213762997-58f7d982-96eb-450d-bf51-e55b38659ec6.png)

### Important Factoids

This starts with 3.40.0. Is working with 3.39.1

**Comment by tschechniker** [comment]
Hi there,

i face the same issue. This is super annoying because we have many resources with diagnostic settings. 

+1 for this!

**Comment by Dyhr** [comment]
I have my setting set to "Dedicated" and I'm getting the same issue. It seems that it's not reading that property from the resource at all.

**Comment by roviracarlos** [comment]
Same issue here, in terraform the setting is set (logAnalyticsDestinationType) but the Get in Microsoft API Rest return null in this setting for most of the resources, only some of them have this setting applied like API Management.

**Comment by teowa** [comment]
@roviracarlos is right, for some resource the `logAnalyticsDestinationType`property is no longer applicable for now, see https://github.com/Azure/azure-rest-api-specs/issues/22400 for detail. I am still contacting with the service team about the API issue to work out a solution. 

The diff caused by `logAnalyticsDestinationType` should not affect the functionality of diagnostic setting. So we can just ignore it. A temp workaround is using [`ignore_change`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to ignore the diff.

**Comment by asbjorn-wiik** [comment]
This is still an issue in 3.42.0
resource "azurerm_monitor_diagnostic_setting" "datadog" {
  for_each                       = var.enable_datadog_logs ? toset(keys(local.diagnostic_categories)) : toset([])
  name                           = "datadog"
  target_resource_id             = local.diagnostic_target_resource_ids[each.key]
  eventhub_name                  = local.datadog_eventhub_name
  eventhub_authorization_rule_id = local.datadog_eventhub_authorization_rule
  **log_analytics_destination_type = null**
............................
 
Will still in Terraform Plan or Apply produce a change
 # module.storage_account_my.azurerm_monitor_diagnostic_setting.datadog["queue"] will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "datadog" {
        id                             = "/subscriptions/11111111-2222-3333-4444-123456789012/resourceGroups/weu-stg-rg/providers/Microsoft.Storage/storageAccounts/weustgsa/queueServices/default|datadog"
      **+ log_analytics_destination_type = "AzureDiagnostics"**
        name                           = "datadog"
        # (3 unchanged attributes hidden)

        # (8 unchanged blocks hidden)
    }

**Comment by laurilarjo** [comment]
Still an issue with 3.44.1

**Comment by eyenx** [comment]
We also have this issue, any news on roadmap?

**Comment by indispeq** [comment]
Same issue happening for us, using latest, 3.44.1.
