### ISSUE TITLE
Support for action_group location

### ISSUE THREAD

**Issue by networksecadmin** [hashicorp/terraform-provider-azurerm#20151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Action groups support locations now - Sweden Central & Germany West Central
- Location Attribut is missing

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_action_group

### References

https://azure.microsoft.com/en-ca/updates/generally-available-action-groups-can-now-be-saved-and-processed-within-europe/

**Comment by stephybun** [comment]
Closed by #20603
