### ISSUE TITLE
Support for create more than one Name in private_dns_zone_group

### ISSUE THREAD

**Issue by fe-eccel** [hashicorp/terraform-provider-azurerm#20152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm tryng to create a private endpoint for AMPLS (Azure Monitor Private Link Scope), this resource need a config for some dns zones to work.

Through the Azure Portal we can create several private dns zone names, but with Terraform azurerm_private_endpoint, on the private_dns_zone_group block, just permit create only one dns zone name.

If you look in the portal, on Azure RM Template, this resource is created with different names.

Azure RM Template:

```json
{
            "type": "Microsoft.Network/privateEndpoints/privateDnsZoneGroups",
            "apiVersion": "2022-05-01",
            "name": "[concat(parameters('privateEndpoints_teste_chat_bot_ampls_name'), '/default')]",
            "dependsOn": [
                "[resourceId('Microsoft.Network/privateEndpoints', parameters('privateEndpoints_teste_chat_bot_ampls_name'))]"
            ],
            "properties": {
                "privateDnsZoneConfigs": [
                    {
                        "name": "privatelink-monitor-azure-com",
                        "properties": {
                            "privateDnsZoneId": "[parameters('privateDnsZones_privatelink_monitor_azure_com_externalid')]"
                        }
                    },
                    {
                        "name": "privatelink-oms-opinsights-azure-com",
                        "properties": {
                            "privateDnsZoneId": "[parameters('privateDnsZones_privatelink_oms_opinsights_azure_com_externalid')]"
                        }
                    },
                    {
                        "name": "privatelink-ods-opinsights-azure-com",
                        "properties": {
                            "privateDnsZoneId": "[parameters('privateDnsZones_privatelink_ods_opinsights_azure_com_externalid')]"
                        }
                    }
```

Ideally, it would be allowed to create a "list(object) for the "private_dns_zone_group" block.

### New or Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Potential Terraform Configuration

```hcl
variable "private_dns_zone_groups" {
  type = list(object({
    name                 = string
    private_dns_zone_ids = list(string)    
  }))
  description = "(Optional) A private_dns_zone_group block as defined below."  
}

resource "azurerm_private_endpoint" "main" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.location
  subnet_id           = var.subnet_id
  private_service_connection {
    name                              = var.private_service_connection.name
    is_manual_connection              = var.private_service_connection.is_manual_connection
    private_connection_resource_id    = var.private_service_connection.private_connection_resource_id
    private_connection_resource_alias = var.private_service_connection.private_connection_resource_alias
    subresource_names                 = var.private_service_connection.subresource_names
    request_message                   = var.private_service_connection.request_message
  }
  dynamic "private_dns_zone_group" {
    for_each            = var.private_dns_zone_groups
    content {
      name                 = private_dns_zone_group.value.name
      private_dns_zone_ids = private_dns_zone_group.value.private_dns_zone_ids
    }
   }
}
```

**Comment by aristosvo** [comment]
Hi @fe-eccel 👋 

Can you explain it a bit more? It is possible to use 1 endpoint with multiple dns zones, by adding multiple zone ids to `private_dns_zone_ids`

**Comment by fe-eccel** [comment]
Hi, Aristosvo,

Sorry, I think the explanation in the registry is a bit confusing. I had understood that the "name" (in private_dns_zone_group) was the "Configuration name", however the "name" is the "DNS zone group name", so inside the private_dns_zone_group:

- name - Is the DNS zone group name
- private_dns_zone_ids - IDs of the DNS zones that will be linked. Based on the ID, it adds a "Configuration name" with the same name as the zone. Still based on the IDs, it also adds within each configuration all the fqdns based on the records of these zones. 

Therefore, I need to add a single name (which will be the same for all configurations, and these configurations will be generated from the name of each zone).

I believe you can close this issue. Thank's for your time.
