### ISSUE TITLE
httpRequestTimeout not applying

### ISSUE THREAD

**Issue by stumueller** [hashicorp/terraform-provider-azurerm#20179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_pipeline

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.0.0"

  backend "local" {

  }

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0.0"
    }
  }
}

provider "azurerm" {
  features {}
}

locals {
  pbi_dp_folder = "folder"
}

resource "azurerm_resource_group" "rg" {
    name     = "bugreport-test-rg"
    location = "uksouth"
}

resource "azurerm_data_factory" "df" {
  name                = "bugreport-test-df"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_data_factory_pipeline" "republish_powerbi_reports" {
  name                = "republish_powerbi_reports"
  description = "Republish the power BI reports."
  folder              = local.pbi_dp_folder
  data_factory_id     = azurerm_data_factory.df.id
  activities_json = templatefile(
    "./activities.json",
    {
      resource_group_name = azurerm_resource_group.rg.name
    }
  )
}

activities.json file:
[
    {
        "name": "Web1",
        "type": "WebActivity",
        "dependsOn": [],
        "policy": {
            "timeout": "0.00:14:00",
            "retry": 3,
            "retryIntervalInSeconds": 30,
            "secureOutput": false,
            "secureInput": false
        },
        "userProperties": [],
        "typeProperties": {
            "url": "https://localhost",
            "method": "PUT",
            "body": "{\n\"key\": \"value\"",
            "httpRequestTimeout": "00:05:00",
            "authentication": {
                "type": "Basic",
                "username": "username",
                "password": {
                    "type": "SecureString",
                    "value": "**********"
                }
            }
        }
    }
]
```

### Debug Output/Panic Output

```shell
https://gist.github.com/stumueller/f3a746a760d5761aa7c99e011cf5f63b
```

### Expected Behaviour

When viewing the pipeline in ADF under settings\advanced the httpRequestTimeout should be set to 00:05:00

### Actual Behaviour

It appears that the setting is taking effect according to the output of terraform apply:
log snipett:
azurerm_data_factory_pipeline.republish_powerbi_reports will be updated in-place
  ~ resource "azurerm_data_factory_pipeline" "republish_powerbi_reports" {
      ~ activities_json = jsonencode(
          ~ [
              ~ {
                    name           = "Web1"
                  ~ typeProperties = {
                      **+ httpRequestTimeout = "00:05:00**"
                        # (4 unchanged elements hidden)
                    }
                    # (4 unchanged elements hidden)
                },
            ]
        )
        id              = "/subscriptions/64b57460-015e-4db0-860b-86c4d083a797/resourceGroups/bugreport-test-rg/providers/Microsoft.DataFactory/factories/bugreport-test-df/pipelines/republish_powerbi_reports"
        name            = "republish_powerbi_reports"
        # (7 unchanged attributes hidden)
    }

But it never does actually take effect.

### Steps to Reproduce

using the terraform code above with a separate activities.json (also specified above) file run terraform apply

**Comment by ms-henglu** [comment]
Hi @stumueller ,

Thank you for taking time to report this issue!

This field it not defined in the swagger, so the generated SDK couldn't deserialize it and send it to the service. I've created an issue to track it: https://github.com/Azure/azure-rest-api-specs/issues/22340
