### ISSUE TITLE
Problem with password change in `azurerm_mssql_managed_instance resource`

### ISSUE THREAD

**Issue by kinseii** [hashicorp/terraform-provider-azurerm#20181]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_managed_instance" "this" {
  name                = "mssql_managed_instance"
  resource_group_name = azurerm_resource_group.name
  location            = azurerm_resource_group.location

  license_type        = "BasePrice"
  sku_name            = "GP_Gen5"
  storage_size_in_gb  = 32
  subnet_id           = azurerm_subnet.mssql.id
  vcores              = 4

  administrator_login          = "admin"
  administrator_login_password = "insert-password-here"

  depends_on = [
    azurerm_subnet_network_security_group_association.mssql,
    azurerm_subnet_route_table_association.mssql
  ]
}
```

### Debug Output/Panic Output

```shell
...
~ administrator_login_password   = (sensitive value)
...
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behaviour

I previously created an MSSQL instance via terraform and am now trying to change the password. But when I make the change and apply the configuration, the password does not change.

The password should have changed.

### Actual Behaviour

The password hasn't changed. It won't connect with the new password. It connects with the old password.

### Steps to Reproduce

terraform apply

**Comment by sinbai** [comment]
@kinseii thanks for opening this issue. I would submit a PR to fix it as soon as possible.
