### ISSUE TITLE
Terraform support for Azure Secret Cloud

### ISSUE THREAD

**Issue by rohrerb** [hashicorp/terraform-provider-azurerm#20190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to add Azure Secret to the terraform provider supported environments?

### New or Affected Resource(s)/Data Source(s)

*all*

**Comment by manicminer** [comment]
Hi @rohrerb, thanks for requesting this! We do have an existing open issue for this - #15743 - although I appreciate it's not easy to find. This was blocked until recently but now that the necessary changes have been made by Microsoft to the ARM metadata service, we should be able to add support for private/secret/undocumented clouds. I'm going to close this issue however, in favor of the existing one. Please subscribe to #15743 for updates, thanks!
