### ISSUE TITLE
Improperly Forced Case Sensitivity on import of azurerm_service_plan on serverFarms ID

### ISSUE THREAD

**Issue by ImIOImI** [hashicorp/terraform-provider-azurerm#20201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "data_farm" {
  name                = "data-server-farm"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  os_type  = "Windows"
  sku_name = "EP1"
}

resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = "rg"
}
```

### Debug Output/Panic Output

```shell
Error: parsing Resource ID "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/serverFarms/data-server-farm": ID was missing the `serverfarms` element
```

### Expected Behaviour

When importing a resource with a resource id taken off the azure portal, the azure provider should accept that resource id and I shouldn't have to format the resource id. However, If you edit the resource ID taken from the Azure portal and change `serverFarms` to `serverfarms` it works.

### Actual Behaviour

azurerm_service_plan.data_farm: Importing from ID "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/serverFarms/data-server-farm"...
╷
│ Error: parsing Resource ID "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Web/serverFarms/data-server-farm": ID was missing the `serverfarms` element
│
│
╵

### Steps to Reproduce

1. navigate to an app service plan in the azure portal => properties => copy the resource id
![image](https://user-images.githubusercontent.com/1832271/215205279-23cab82a-8190-4615-b3a5-2ad12b231ee6.png)
2. `terraform import azurerm_service_plan.data_farm <insert resource id>`

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/19600

**Comment by myc2h6o** [comment]
Hi @ImIOImI thanks for opening the issue! Unfortunately according to https://github.com/hashicorp/terraform-provider-azurerm/issues/19600#issuecomment-1342675234, different from Azure Portal, the provider is designed to be case sensitive for resource ID, so the segment needs to be changed to `serverfarms`.

**Comment by ImIOImI** [comment]
> Hi @ImIOImI thanks for opening the issue! Unfortunately according to [#19600 (comment)](https://github.com/hashicorp/terraform-provider-azurerm/issues/19600#issuecomment-1342675234), different from Azure Portal, the provider is designed to be case sensitive for resource ID, so the segment needs to be changed to `serverfarms`.

Thanks for the response! I'm confused. In the referenced comment, it says the following:
>Unfortunately the casing used by the Azure Portal and Azure APIs differs (and changes over time) as such the Azure APIs are the canonical reference for Resource ID segments. Since Resource IDs are predictable within Azure, we now define these within Terraform based on a point-in-time reference of the Resource ID, unfortunately at the point-in-time when this Resource ID was created we were using the segment serverfarms (as the Azure API was doing so) - however at this point in time the ARM Team within Azure has required that segments move towards using camelCasing for segment names, as such this should ultimately become serverFarms.

The way I read this is that the casing requirements change over time and the Azure provider changes to reflect that. I upgraded to the newest version of the Azurerm to test, and it didn't work. Therefore (if I'm reading this correctly), when the next update to Azurerm comes out it should reflect the current values given by the azure API. 

But if you're saying that the provider is going to use camelcase in spite of what the Azure API returns (we can also see the same behavior when using a data source), then that is less than ideal. At the very least, Terraform should be compatible with itself.

**Comment by myc2h6o** [comment]
This resource was onboarded with the static segment `serverfarms` as in below code:
https://github.com/hashicorp/terraform-provider-azurerm/blob/8cdfd601e731251e4b07b9a7e08f7b1df7cb4d3e/internal/services/appservice/parse/service_plan.go#L60
and unfortunately, the Azure API spec still haven't change to camel case yet so for now to be consistent with the API, it remains like this.
https://github.com/Azure/azure-rest-api-specs/blob/78ec1b99699a4bf44869bd13f1b0ed7d92a99c27/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/AppServicePlans.json#L107

**Comment by ImIOImI** [comment]
> This resource was onboarded with the static segment `serverfarms` as in below code:
> 
> https://github.com/hashicorp/terraform-provider-azurerm/blob/8cdfd601e731251e4b07b9a7e08f7b1df7cb4d3e/internal/services/appservice/parse/service_plan.go#L60
> 
> 
> and unfortunately, the Azure API spec still haven't change to camel case yet so for now to be consistent with the API, it remains like this.
> https://github.com/Azure/azure-rest-api-specs/blob/78ec1b99699a4bf44869bd13f1b0ed7d92a99c27/specification/web/resource-manager/Microsoft.Web/stable/2022-03-01/AppServicePlans.json#L107

Thanks, I don't have to like the answer, but at least I understand why it is this way.
