### ISSUE TITLE
Support data module for import initiative (policy set) assignment 

### ISSUE THREAD

**Issue by fengcanliu** [hashicorp/terraform-provider-azurerm#20210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need to import build in policy set assignment (/subscriptions/xxxx/providers/Microsoft.Authorization/policyAssignments/SecurityCenterBuiltIn) to be able to create resource azurerm_subscription_policy_exemption. 

We have tried using Data Source: azurerm_policy_assignment to import it but we are getting null. 

### New or Affected Resource(s)/Data Source(s)

azurerm_3.40

### Potential Terraform Configuration

```hcl
data "azurerm_subscription" "current" {}

data "azurerm_policy_definition" "sql_enable_aad_policy" {
  display_name = "An Azure Active Directory administrator should be provisioned for SQL servers"
}


data "azurerm_policy_assignment" "sql_enable_aad_policy_assignment" {
  name                 = "ASC Default (subscription: ${data.azurerm_subscription.current.subscription_id})"
  scope_id             = data.azurerm_subscription.current.id
}

resource "azurerm_subscription_policy_exemption" "sql_enable_aad_policy_exemption" {
  name                            = "${var.environment}-sql-enable-aad-assigment-policy-exemption"
  subscription_id                 = data.azurerm_subscription.current.id
  policy_assignment_id            = data.azurerm_policy_assignment.sql_enable_aad_policy.id
  policy_definition_reference_ids = [data.azurerm_policy_definition.sql_enable_aad_policy.id]
  exemption_category   = "Mitigated"
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
