### ISSUE TITLE
InaccessibleImage error with azurerm_container_group and a public Docker Hub image

### ISSUE THREAD

**Issue by eugene-romero-capgemini** [hashicorp/terraform-provider-azurerm#20216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "unleash" {
  name                = "containerinstance-unleash-test"
  resource_group_name = "my_resource_group"
  location            = "westeurope"
  os_type             = "Linux"
  ip_address_type     = "Private"
  subnet_ids          = [data.azurerm_subnet.unleash.id]
  exposed_port = [
    {
      port     = 80
      protocol = "TCP"
    }
  ]

  container {
    name   = "proxy"
    image  = "nginx:alpine"
    cpu    = "0.5"
    memory = "1"

    ports {
      port     = 80
      protocol = "TCP"
    }
  }

  container {
    name   = "unleash"
    image  = "unleashorg/unleash-server:4.20.1"
    cpu    = "1"
    memory = "1.5"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Container Group (Subscription: "XXXXXXXXXX"
│ Resource Group Name: "my_resource_group"
│ Container Group Name: "containerinstance-unleash-test"): performing ContainerGroupsCreateOrUpdate: containerinstance.ContainerInstanceClient#ContainerGroupsCreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InaccessibleImage" Message="The image 'unleashorg/unleash-server:4.20.1' in container group 'containerinstance-unleash-test' is not accessible. Please check the image and registry credential."
│
│   with azurerm_container_group.unleash,
│   on containerGroup.tf line 1, in resource "azurerm_container_group" "unleash":
│    1: resource "azurerm_container_group" "unleash" {
```

### Expected Behaviour

Image should be pulled from Docker Hub and Container Group should be created.

### Actual Behaviour

Terraform fails with 
```
Original Error: Code="InaccessibleImage" Message="The image 'unleashorg/unleash-server:4.20.1' in container group 'containerinstance-unleash-test' is not accessible. Please check the image and registry credential."
```

This image is from the public Docker Hub, and can be `docker pull`ed locally. Interestingly, the image in the other container (nginx) is pulled without issue. I have also attempted removing the version tag completely, using `:latest`, using the full address to the docker hub (docker.io and registry.docker.com) and trying without the `owner` part of the image address.

To look for possible patterns, I replaced the line `unleashorg/unleash-server:4.20.1` with `alpinelinux/docker-cli:latest`. I wanted to test having an `owner` field and a `-`. This worked as expected, which means it is only some Docker Hub images it does not like.

### Steps to Reproduce

```
terraform plan
terraform apply
```

### References

This issue might be upstream with the Azure API itself: https://github.com/Azure/azure-cli/issues/18596

This is the image I am trying to pull: https://hub.docker.com/r/unleashorg/unleash-server

**Comment by manicminer** [comment]
@eugene-romero-capgemini Thanks for reporting this issue. Looking at the error you are getting, along with your report of having it work with some images but not others, indicates that this is more likely to be an Azure service issue than it is an issue with Terraform. The error you are getting is being reported from the API, and looking at the code the provider isn't doing anything to the image string provided, it is being passed along to the API unchanged.

Accordingly, since this is more likely to be an issue with the service than the provider, I'm going to close this for now and recommend that you open an Azure support ticket to troubleshoot further. Thanks!

**Comment by eugene-romero-capgemini** [comment]
@manicminer thank you for your reply! Indeed, testing out creation of a Container Instance on the Azure portal throws the same error, so this is definitely an issue with Azure itself. I will raise an issue over there.

Thanks again!
