### ISSUE TITLE
Documentation request - add note to "azurerm_dns_*_record" resources that private DNS are separate

### ISSUE THREAD

**Issue by tdevopsottawa** [hashicorp/terraform-provider-azurerm#20227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I recently got stuck for a while on trying to implement a DNS setup in Terraform because I created private DNS zones and was trying to use `azurerm_dns_a_record` to populate my zone instead of `azurerm_private_dns_a_record` as I was supposed to. But there was no text in the error suggesting this; Azure merely failed with "not found" errors. I had no idea that private DNS zones have whole separate azurerm resources for records.

It would be nice if there was a caution note in the documentation for azurerm_dns_*_record resources (ie. azurerm_dns_a_record, azurerm_dns_ns_record, etc.) pointing this out.

### New or Affected Resource(s)/Data Source(s)

azurerm_dns_a_record

**Comment by sinbai** [comment]
@tdevopsottawa thanks for opening this issue. [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/20244) has been submitted to enhance the description.
