### ISSUE TITLE
Can't switch data persistence in `azure_cache_redis`

### ISSUE THREAD

**Issue by mclacore** [hashicorp/terraform-provider-azurerm#20228]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_cache_redis

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "main" {
  name                          = var.name
  location                      = azurerm_resource_group.main.location
  resource_group_name           = azurerm_resource_group.main.name
  redis_version                 = var.redis.redis_version
  replicas_per_primary          = var.redis.replicas_per_primary
  family                        = "P"
  capacity                      = var.redis.capacity
  sku_name                      = "Premium"
  minimum_tls_version           = "1.2"
  subnet_id                     = var.default_subnet_id
  public_network_access_enabled = false
  shard_count                   = var.cluster.enable_cluster ? var.cluster.shard_count : 0
  tags                          = var.default_tags

  redis_configuration {
    rdb_backup_enabled              = false
    aof_backup_enabled              = true
    aof_storage_connection_string_0 = azurerm_storage_account.aof0.primary_connection_string
    aof_storage_connection_string_1 = azurerm_storage_account.aof1.primary_connection_string
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Redis Cache "local-dev-redis-0003" (Resource Group "local-dev-redis-0003"): redis.Client#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="AOF and RDB cannot both be enabled\r\nRequestID=4430166a-1f01-#########4"
│
│   with azurerm_redis_cache.main,
│   on main.tf line 7, in resource "azurerm_redis_cache" "main":
│    7: resource "azurerm_redis_cache" "main" {
```

### Expected Behaviour

`azure_cache_redis` can freely switch between data persistence types without any issues, just like in the Azure portal

### Actual Behaviour

I can't switch from `RDB` to `AOF` persistence or switch back. Also, I tried completely disabling data persistence before enabling `AOF` persistence, and I get the same error. Looks like remnants of data persistence gets left in the statefile somehow. 

Only way I can switch persistence is to completely destroy the cache and recreate it using another type. This is **not** how this behaves in the Azure portal.

### Steps to Reproduce

`terraform apply`

### References

https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-how-to-premium-persistence#can-i-enable-aof-and-rdb-persistence-at-the-same-time

**Comment by mclacore** [comment]
Just discovered another problem. If I deploy a Redis with this configuration:
```
resource "azurerm_redis_cache" "main" {
  name                          = var.name
  location                      = azurerm_resource_group.main.location
  resource_group_name           = azurerm_resource_group.main.name
  redis_version                 = var.redis.redis_version
  replicas_per_primary          = var.redis.replicas_per_primary
  family                        = "P"
  capacity                      = var.redis.capacity
  sku_name                      = "Premium"
  minimum_tls_version           = "1.2"
  subnet_id                     = var.default_subnet_id
  public_network_access_enabled = false
  shard_count                   = var.cluster.enable_cluster ? var.cluster.shard_count : 0
  tags                          = var.default_tags

  redis_configuration {
    rdb_backup_enabled              = false
    aof_backup_enabled              = true
    aof_storage_connection_string_0 = azurerm_storage_account.aof0.primary_connection_string
    aof_storage_connection_string_1 = azurerm_storage_account.aof1.primary_connection_string
  }

  identity {
    type = "SystemAssigned"
  }
}
```
And then update the terraform and redeploy using this configuration:
```
resource "azurerm_redis_cache" "main" {
  name                          = var.name
  location                      = azurerm_resource_group.main.location
  resource_group_name           = azurerm_resource_group.main.name
  redis_version                 = var.redis.redis_version
  replicas_per_primary          = var.redis.replicas_per_primary
  family                        = "P"
  capacity                      = var.redis.capacity
  sku_name                      = "Premium"
  minimum_tls_version           = "1.2"
  subnet_id                     = var.default_subnet_id
  public_network_access_enabled = false
  shard_count                   = var.cluster.enable_cluster ? var.cluster.shard_count : 0
  tags                          = var.default_tags

  identity {
    type = "SystemAssigned"
  }
}
```
The data persistence settings remain in the state. They are not removed. Therefore, the settings stay the same even though I've removed them from my .tf file and redeployed the changes.
```
No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences,
so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

**Comment by harshavmb** [comment]
I think it's because of [3037](https://github.com/Azure/azure-rest-api-specs/issues/3037). I tried the other way around from `AOF` to `RDB` but stuck with the same issue. 

When I used `AOF` in state files, connection strings were masked with trailing `AccountKey=[key hidden]`. On further runs, terraform tried to refresh the state as it experienced a different key. 

I did try with `ignore_changes` as recommended but that as well didn't help. I'm greeted with below error ::

> azurerm_redis_cache.main: Modifying... [id=/subscriptions/xxxxxxx/resourceGroups/yyyyyy/providers/Microsoft.Cache/Redis/zzzzzz]
╷
│ Error: updating Redis Cache "fops-redis" (Resource Group "yyyyyy"): redis.Client#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestBody" Message="The value of the parameter 'properties.redisConfiguration.aof-storage-connection-string-0' is invalid.\r\nRequestID=a036d0f7-ba9f-498d-90ac-60bff185d6f1"
│ 
│   with azurerm_redis_cache.main,
│   on test.tf line 1, in resource "azurerm_redis_cache" "main":
│    1: resource "azurerm_redis_cache" "main" {
│ 
╵

Have you tried with `ignore_changes`? It may work as I don't see `rdb` connection string being masked.

**Comment by sinbai** [comment]
@mclacore thanks for opening this issue. It seems that this is a terraform bug, I might try to fix it later.

**Comment by mclacore** [comment]
Does that mean that data persistence can't be disabled after it's enabled?

**Comment by sinbai** [comment]
After the PR https://github.com/hashicorp/terraform-provider-azurerm/pull/20286 is released, the data persistence could be disabled after it's enabled.

**Comment by michaelmccarver** [comment]
Is there a workaround or do we just delete and recreate the redis instance?

**Comment by mclacore** [comment]
> Is there a workaround or do we just delete and recreate the redis instance?

no workaround, currently only way to disable is to recreate the redis
