### ISSUE TITLE
Add managed identity support to `azurerm_redis_cache` persistence

### ISSUE THREAD

**Issue by mclacore** [hashicorp/terraform-provider-azurerm#20223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Cache for Redis supports using managed identity to connect the cache to a storage account using RBAC. Currently, the `azurerm` provider requires a `rdb_storage_connection_string` to be set. Same with `aof_storage_connection_string_0/1`. We can still configure RBAC, but the params require the connection string. Can you add an option to set a connection string **or** an Azure storage account resource ID? 

### New or Affected Resource(s)/Data Source(s)

azurerm_cache_redis

### Potential Terraform Configuration

```hcl
redis_configuration {
    rdb_backup_enabled            = true
    rdp_backup_max_snapshot_count = 15
    rdb_storage_account_id        = azurerm_storage_account.main.id
  }
```

### References

https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-managed-identity#use-managed-identity-with-storage-accounts

**Comment by MichalSino** [comment]
Do someone knows when it will come to provider?

**Comment by MichalSino** [comment]
@manicminer any new infos about this?

**Comment by MichalSino** [comment]
It is added in version 3.94, we can close the issue.

**Comment by dansailer** [comment]
Works with version `v3.103.1` and using `primary_blob_endpoint` as connection string

```
redis_configuration {
    ...
    data_persistence_authentication_method = "ManagedIdentity"
    rdb_storage_connection_string = azurerm_storage_account.example.primary_blob_endpoint
}
```

**Comment by tombuildsstuff** [comment]
Closing as resolved per @dansailer and @MichalSino's comments above
