### ISSUE TITLE
azurerm_billing_account_cost_management_export  Status=404 Code="MissingSubscription"

### ISSUE THREAD

**Issue by danabrash** [hashicorp/terraform-provider-azurerm#20242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_billing_account_cost_management_export

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storageaccount" {
  provider                        = azurerm.management
  name                            = "storageaccount"
  resource_group_name             = "CostManagement"
  location                        = "West US 2"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false

}

resource "azurerm_storage_container" "actual-billingaccount" {
  provider              = azurerm.management
  name                  = "actual-billingaccount"
  storage_account_name  = azurerm_storage_account.storageaccount.name
  container_access_type = "private"
}

resource "azurerm_billing_account_cost_management_export" "billing_account_export" {
  name                         = "actual-billingaccount"
  billing_account_id           = "<BillingAccountId>/billingProfiles/<BillingProfileId>"
  recurrence_type              = "Daily"
  recurrence_period_start_date = formatdate("YYYY-MM-DD'T'00:00:00Z", timestamp())
  recurrence_period_end_date   = "2050-01-01T00:00:00Z"

  export_data_storage_location {
    container_id     = azurerm_storage_container.actual-billingaccount.resource_manager_id
    root_folder_path = "/billingaccount-actual"
  }

  export_data_options {
    type       = "ActualCost"
    time_frame = "WeekToDate"
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/danabrash/56f702a06d6339ccc21aea277334f298
```

### Expected Behaviour

The export job should create.  There is no documented setting for context beyond the billing account ID.
Since we're MCA (not EA) I tried both just the billing account ID and the billing accountID/billingprofileID, same results

The prompt for subscription or Tenant is out of context

### Actual Behaviour

Status=404 Code="MissingSubscription" Message="The request did not have a subscription or a valid tenant level resource provider."

### Steps to Reproduce

run the sample code provided.  substitute actual values for account tokens

**Comment by ms-zhenhua** [comment]
Hi @danabrash, `billing_account_id` is mapped to [`scope` parameter](https://learn.microsoft.com/en-us/rest/api/cost-management/exports/create-or-update?tabs=HTTP#uri-parameters) of the Azure REST API. So, you could try to set `billing_account_id` like follows:

```
billing_account_id           = "providers/Microsoft.Billing/billingAccounts/<BillingAccountId>"
billing_account_id           = "providers/Microsoft.Billing/billingAccounts/<BillingAccountId>/billingProfiles/<BillingProfileId>"
```

**Comment by danabrash** [comment]
OK, thank you.  So basically we need the provider in front of the BillingAccountID to properly scope the call.  That makes sense.

It would be great if to make that clear with an update to the documentation.

  billing_account_id           = "example"

and even

   billing_account_id - (Required) The id of the billing account on which to create an export. Changing this forces a new resource to be created.

are insufficient in that they do not clarify that the provider portion of the ID must be provided as well.

Since the name of this provider is "*billing_account*" you'd think the provider portion might be included in the code.

The "ID" of the Billing Account in the portal is <guid>:<guid>_<date>
which is the name property in powershell unless you specify the request for the ID

So ultimately the information is there to be had.
Some better direction in the documentation to get to that info would be helpful.

in any case, thank you very much for the direction, I appreciate your assistance.  It's working well for me now that I understand.
