### ISSUE TITLE
parameter validation for azurerm_active_directory_domain_service

### ISSUE THREAD

**Issue by Blouni** [hashicorp/terraform-provider-azurerm#20259]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41

### Affected Resource(s)/Data Source(s)

azurerm_active_directory_domain_service

### Terraform Configuration Files

```hcl
resource "azurerm_active_directory_domain_service" "aadds" {
  name                = "aadds"
  location            = azurerm_resource_group.aadds.location
  resource_group_name = azurerm_resource_group.aadds.name
  domain_name           = var.address_space # Here is typo.... - the value is "az.domain.com"
  sku                   = var.sku 
  filtered_sync_enabled = false
  initial_replica_set {
    subnet_id = azurerm_subnet.sub.id
  }
  notifications {
    notify_dc_admins     = true
    notify_global_admins = true
  }
  security {
    sync_kerberos_passwords = true
    sync_ntlm_passwords     = true
  }
  depends_on = [
    azurerm_subnet_network_security_group_association.aadds-sub,
  ]
}
```

### Debug Output/Panic Output

```shell
Error: domain_name must be a valid FQDN and the first element must be 15 or fewer characters
```

### Expected Behaviour

No error

### Actual Behaviour

Error: domain_name must be a valid FQDN and the first element must be 15 or fewer characters

The issue was introduced in v3.36 of the provider here is the PR:
- https://github.com/hashicorp/terraform-provider-azurerm/pull/19599

The issue came from the REGEX which validates only sub domain with at least 2 chars

**Comment by magodo** [comment]
@Blouni I'm not sure whether I understand this correctly, the regexp `regexp.MustCompile("^[0-9a-zA-Z][0-9a-zA-Z-]{1,13}[0-9a-zA-Z](.[0-9a-zA-Z-]+)+$")` actually matches the input `"test.domain.com"`, which then won't raise the validation error, but you were expecting an error?

**Comment by Blouni** [comment]
Sorry i'v done a check it doesn't validate for a subdomain with only 2 char for example: az.domain.com
