### ISSUE TITLE
Issue with Azure Monitor Data Collection Rules

### ISSUE THREAD

**Issue by cRaZyT1807** [hashicorp/terraform-provider-azurerm#20258]
* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_data_collection_rule" "data_collection_rule" {
  name                = "${var.project}-${var.environment}-log-rules"
  resource_group_name = lower("devops-${var.environment}-log-rg")
  location            = var.location

  destinations {
    log_analytics {
      workspace_resource_id = var.workspace_id
      name                  = "${var.project}-${var.environment}-destination-log"
    }
  }

  data_flow {
    streams      = ["Microsoft-Perf","Microsoft-Syslog"]
    destinations = ["${var.project}-${var.environment}-destination-log"]
  }

  data_sources {
    syslog {
      facility_names = ["*"]
      log_levels     = ["*"]
      name           = "${var.project}-${var.environment}-sysLogs"
    }

    performance_counter {
      streams                       = ["Microsoft-Perf"]
      sampling_frequency_in_seconds = 10
      counter_specifiers            = ["*"]
      name                          = "${var.project}-${var.environment}-perfCounter"
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Create the rule with the provided "syslog" and "performance counter" settings.

### Actual Behaviour

The rule is created but nothing is selected in the “Performance Counters” and in “Syslog” all the “Facilities” are available but no “minimum log level”.

**Comment by teowa** [comment]
Hi @cRaZyT1807 , thanks for submitting this issue!

From Data Collection Rule [REST API sepcification ](https://github.com/Azure/azure-rest-api-specs/blob/d1eb4e42e24016044e150c0fb8f0dc6c1182b5f5/specification/monitor/resource-manager/Microsoft.Insights/stable/2021-04-01/dataCollectionRules_API.json#L339), the wildcard(*) means collect all. And azurerm has send the correct value to service API. Through reproduce, I can also see in Portal the no option is selected, So the issue should be in servicn side or Portal side.

**Comment by teowa** [comment]
As for the “Performance Counters”, in Portal it is selected at the last item of Custom blade, and still confirm if syslog is the Portal issue.
<img width="836" alt="image" src="https://user-images.githubusercontent.com/104055472/216557142-88a5146d-5b80-4f3f-aebe-8a4068972f1d.png">

**Comment by teowa** [comment]
After internal sync, the conclusion is: For `performance_counter`, the `*` should be used in format object(instance)\counter to collect all the instance.
And for `syslog`, the `*` can be used in `facility_names` and `log_levels`, it is the portal display issue (no log level is selected), and it will be reported.

Thanks.

**Comment by cRaZyT1807** [comment]
HI @teowa , thanks for the feedback and support!

The documentation for `performance_counter` was a bit confusing at this point, because `Use a wildcard * to collect counters for all instances` meant for me that I could get all possible counters with it, especially since the term instances is not explained further here.

Regards
