### ISSUE TITLE
AKS agent labels not set reliably

### ISSUE THREAD

**Issue by gganssauge** [hashicorp/terraform-provider-azurerm#20269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
Please see the repo at https://github.com/gganssauge/test-node-labels.

The README.me file in that repo more closely describes the issue and the tests we are doing.
```

### Debug Output/Panic Output

```shell
https://gist.github.com/gganssauge/1a520edb390b96864135c7b5008a7f64
```

### Expected Behaviour

The node labels in an agent pool should apply to all nodes in that pool.

We assign the label `stack=app` to the nodes in the default agent pool 
and the label `stack=monitoring` to the nodes in a second agent pool and
 use those labels to control the node affinity of affected deployments.

### Actual Behaviour

Since we deployed azurerm-3.39, at least one node in the monitoring pool is missing the label in about 30% of the cases.

### Steps to Reproduce

Please see the script "[test-node-labels.sh](https://github.com/gganssauge/test-node-labels/blob/main/test-node-labels.sh)"
 in repository [https://github.com/gganssauge/test-node-labels](https://github.com/gganssauge/test-node-labels).

I run that script as a Job on our CI-Server every 20 minutes.
It creates an AKS cluster with two agent-node-pools.
It then tries to get nodes with `kubectl get node -l stack=monitoring`, 
counts the number of retrieved nodes and compares it to the number of 
nodes in the pool.
Finally the cluster is destroyed.

Manual inspection with azure portal yields that the agent pool contains 
the requested number of nodes and that at least one of them is missing 
the requested label.

**Comment by manicminer** [comment]
Hi @gganssauge, thanks for reporting this. Whilst triaging, I had a quick look through your linked repo but this seems to be a large/complete configuration with several modules which we unfortunately will be able to dig into. In order for a maintainer to investigate this issue, please would you reply with a minimal configuration and/or instructions to reproduce your issue? Many thanks.

**Comment by gganssauge** [comment]
We can't reproduce it, anymore, in our test job, so this probably should be closed
