### ISSUE TITLE
azurerm_container_group fails to pull public image from dockerhub

### ISSUE THREAD

**Issue by pregress** [hashicorp/terraform-provider-azurerm#20270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
variable "region" {
  default = "West Europe"
}

variable "subscription_id" {
}

provider "azurerm" {
  subscription_id            = var.subscription_id
  skip_provider_registration = true
  features {
  }
}

# Shared state
terraform {
  required_version = "1.3.7"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.41.0"
    }
  }  
}


resource "azurerm_resource_group" "example" {
  name     = "example"
  location = var.region
}


resource "azurerm_container_group" "n8n" {
  name                = "example-n8n-aci"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  ip_address_type     = "Public"
  dns_name_label      = "example-n8n-aci"
  os_type             = "Linux"

  exposed_port {
    port     = 5678 
    protocol = "TCP"
  }

  container {
    name   = "n8n"
    image  = "n8nio/n8n"
    cpu    = "1.5"
    memory = "2"

    ports {
      port     = 5678 
      protocol = "TCP"
    }   
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/pregress/c14405a78c8da5015c83976e25e2666f
```

### Expected Behaviour

The container instance should be created when using a public image that contains a / eg: [n8nio/n8n](https://hub.docker.com/r/n8nio/n8n)

When using a different image (without /) in the image name this does work
eg: [caddy](https://hub.docker.com/_/caddy) 

This configuration worked in the past, so I'm thinking its a change at azure side that broke it.
With Terraform version 1.3.6 and AzureRm version 3.33.0.
I also tried with this setup but the same error surfaces.

### Actual Behaviour

The container instance is not created because:

> Container Group Name: "example-aci"): performing ContainerGroupsCreateOrUpdate: containerinstance.ContainerInstanceClient#ContainerGroupsCreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InaccessibleImage" Message="The image 'n8nio/n8n' in container group 'example-aci' is not accessible. Please check the image and registry credential.

### Steps to Reproduce

terraform apply

**Comment by magodo** [comment]
@pregress Thank you for submitting this! This seems a service side issue as it also faield via Portal:

![image](https://user-images.githubusercontent.com/7970698/216505959-8e7461af-c323-4dd5-b39a-a63366cf9aad.png)

But interestingly, using another image from dockerhub (even is not a official/verified image), it works both via Portal/Terraform. So it looks like this specific image causes the issue. Whilst, it has no problem to `docker pull` it locally. I'd suggest open a support ticket for this case. Or maybe follow this thread: https://learn.microsoft.com/en-us/answers/questions/204946/deploying-docker-container-instance-fails-to-acces

**Comment by pregress** [comment]
Created a support ticket at Azure for it, will update this ticket when this gets resolved.

**Comment by mschmieder** [comment]
same issue here. Any update?

**Comment by pregress** [comment]
@mschmieder If the docker image doesn't have a manifest file you get this behavior you can test this using:
```
docker manifest inspect yourimagename

# no manifest, doesn't work in ACI
docker manifest inspect n8nio/n8n:0.216.0 
# has manifest, does work in ACI
docker manifest inspect n8nio/n8n:0.201.0
```


The fix is to publish the manifest file.
But it's an ACI requirement so I'll close the terraform ticket.
