### ISSUE TITLE
Update azurerm_private_endpoint documentation for subresource `staticSites`

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#20284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

N/A

### AzureRM Provider Version

N/A

### Affected Resource(s)/Data Source(s)

N/A

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Azure has this new 'Static Web Apps' and to create a private endpoint the `subresource_name` needs to be `staticSite`

**Comment by sinbai** [comment]
@DevopsMercenary thanks for opening this issue. Do you mean the `Note` of [subresource_names](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#subresource_names) should be enhanced by adding `staticSites`?

**Comment by DevopsMercenary** [comment]
yes. the table.please
