### ISSUE TITLE
Setting DNS servers on vnets in multiple subscriptions using azurerm_virtual_network_dns_servers

### ISSUE THREAD

**Issue by adam-welch** [hashicorp/terraform-provider-azurerm#20280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_dns_servers

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "virtual_network_ids" {
  default = ["/subscriptions/726e80fd-...redacted.../resourceGroups/rg-test-net-1/providers/Microsoft.Network/virtualNetworks/vnet-1",
             "/subscriptions/158c1bca-...redacted.../resourceGroups/rg-test-net-2/providers/Microsoft.Network/virtualNetworks/vnet-2",
             "/subscriptions/7b8de3e8-...redacted.../resourceGroups/rg-test-net-3/providers/Microsoft.Network/virtualNetworks/vnet-3"]
}

resource "azurerm_virtual_network_dns_servers" "dns" {
  for_each = toset(var.virtual_network_ids)

  virtual_network_id = each.value
  dns_servers        = ["8.8.8.8","8.8.6.6"]
}
```

### Debug Output/Panic Output

```shell
Virtual Network: (Name "vnet-2" / Resource Group "rg-test-net-2") could not be found: network.VirtualNetworksCliding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceGroupNotFound"
```

### Expected Behaviour

I would expect all of the virtual networks supplied to have their DNS servers updated as we are supplying the full id the vnets, in this case to 8.8.8.8 and 8.8.6.6. 

### Actual Behaviour

This only works for the vnet(s) in the subscription of the context it is running as. In the example only vnet-1 will get updated and any vnets not in that subscription throw a virtual network and resource group not found error message. It appears to be ignoring the full ID and just uses the resource group and vnet name.

**Comment by jiaweitao001** [comment]
Hi @adam-welch , thanks for opening the issue. I've tried to reproduce your issue on my end, it looks all good. From the error message I think it might be your local environment variable is pointing to another subscription, thus the resource group cannot be found there.

**Comment by adam-welch** [comment]
@jiaweitao001 as I mentioned, this only works on the virtual networks in the subscription of the context we are running under, this is the same on a build system where we need to specify the subscriptionID in the provider. Using aliases for each sub isn't practical and as we are passing the full resource id of the network in this resource I would expect this to apply to all networks irrespective of the current subscription, as we are passing in the full id.

**Comment by jiaweitao001** [comment]
@adam-welch , that might be the only option I'm afraid.  Since each provider is designed to work for a single subscription by design, you have to specify the credentials separately like this. 

```hcl
provider "azurerm" {
  subscription_id = "<sub id 1>"
  features {}
  alias = "sub1"
}
provider "azurerm" {
  subscription_id = "<sub id 2>"
  features {}
  alias = "sub2"
}

data "azurerm_virtual_network" "vnet1" {
  provider            = azurerm.sub1
  name                = "foo"
  resource_group_name = "exampleRG1"
}

data "azurerm_virtual_network" "vnet2" {
  provider            = azurerm.sub2
  name                = "bar"
  resource_group_name = "exampleRG2"
}
```

**Comment by adam-welch** [comment]
@jiaweitao001 will close this off, was hoping to avoid aliases due to the number of subs so will look for an alternative solution.
