### ISSUE TITLE
azurerm_site_recovery_protection_container_mapping automatic_update Auto update settings is un-healthy

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#20304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_protection_container_mapping

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_protection_container_mapping" "container-mapping" {
  name                                      = "container-mapping"
  resource_group_name                       = azurerm_recovery_services_vault.recovery.resource_group_name
  recovery_vault_name                       = azurerm_recovery_services_vault.recovery.name
  recovery_fabric_name                      = azurerm_site_recovery_fabric.primary.name
  recovery_source_protection_container_name = azurerm_site_recovery_protection_container.primary.name
  recovery_target_protection_container_id   = azurerm_site_recovery_protection_container.secondary.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  automatic_update {
    enabled               = true
    automation_account_id = azurerm_automation_account.support.id
  }
}
```

### Debug Output/Panic Output

```shell
No terraform error
```

### Expected Behaviour

ASR should configure auto update

### Actual Behaviour

Auto update settings is un-healthy

### Steps to Reproduce

terraform apply
Check Site Recovery infrastructure | Extension update settings

**Comment by mpjtaylor** [comment]
Seems this is an issue with System . Managed Identity is not supported at this time only RunAsAccount

**Comment by ziyeqf** [comment]
Hi @mpjtaylor, thanks for reporting.

Could you please provide some details on you `azurerm_recovery_services_vault` and `azurerm_automation_account`? it will help to diagnosis.

> Seems this is an issue with System / Managed Identity is not supported at this time only RunAsAccount
Could you please add some more details on this? 

Thanks!

**Comment by mpjtaylor** [comment]
```
resource "azurerm_automation_account" "support" {
  name                          = local.support_automation_account
  location                      = var.location
  resource_group_name           = var.resource_group_name
  sku_name                      = "Basic"
  public_network_access_enabled = false
  identity {
    type = "SystemAssigned"
  }

  tags = merge(var.custom_tags, {
    "global-opco"          = var.global-opco # API opco
    "global-dcs"           = var.global-dcs
    "global-env"           = var.global-env       # API environment
    "global-dataclass"     = var.global-dataclass # API exposure and dataclass make dataclass
    "global-cbp"           = var.global-cbp
    "global-project"       = var.global-project
    "global-app"           = var.global-app
    "global-techserviceid" = local.global-techserviceid
    "global-appserviceid"  = "a09d9c3a1bec8994e3e66574604bcbbf"
    "local-purpose"        = "MPI"
  })
}

resource "azurerm_recovery_services_vault" "recovery" {
  name                         = local.support_recovery_vault
  location                     = var.location
  resource_group_name          = var.resource_group_name
  storage_mode_type            = var.replication_storage_mode_type
  sku                          = var.replication_vault_sku
  soft_delete_enabled          = var.replication_soft_delete_enabled
  cross_region_restore_enabled = var.replication_cross_region_restore_enabled
  tags = merge(var.custom_tags, {
    "global-opco"          = var.global-opco # API opco
    "global-dcs"           = var.global-dcs
    "global-env"           = var.global-env       # API environment
    "global-dataclass"     = var.global-dataclass # API exposure and dataclass make dataclass
    "global-cbp"           = var.global-cbp
    "global-project"       = var.global-project
    "global-app"           = var.global-app
    "global-techserviceid" = local.global-techserviceid
    "global-appserviceid"  = "a09d9c3a1bec8994e3e66574604bcbbf"
    "local-purpose"        = "MPI"
  })
}
```

Azure site recovery currently does not support managed identity for automation account, the automation account need to be created with run as account.
The support for managed identity will be released in the short coming period before the retirement of the run as accounts in Azure.

**Comment by ziyeqf** [comment]
@mpjtaylor Thanks for the information and config detail.

I have tried to create an `azurerm_automation_account` with `SystemAssigned` identity. And it works... I want to confirm how did you create an `azurerm_automation_account` without `run as account`?

And, if there is any error message on the "un-healthy" status?

Thanks.

**Comment by mpjtaylor** [comment]
the unhealthy state is on the ASR which is configured on the container mapping to use the automation account. I had to manually create the RunAsAccount and then click repair on the ASR Site Recovery infrastructure | Extension update settings

**Comment by ziyeqf** [comment]
@mpjtaylor Could you please check if the identity you used to run Terraform have the permission to create Service Principal(/ Run as Account) and grant `Contributor` permission?

**Comment by mpjtaylor** [comment]
Yes it does, its not a problem creating the identity its just not supported as per Microsoft reply

**Comment by ziyeqf** [comment]
> Yes it does, its not a problem creating the identity its just not supported as per Microsoft reply

I understand it's not supported to use Managed Identity to run auto update, but I'm not sure why the `RunAsAccount` was not created toghter with `azurerm_automation_account`, I'm a little worried if there is a bug inside the provider.

**Comment by ziyeqf** [comment]
Please let me explain my concern: with the following config, it works.  And in the following, I have also set `identity` to `SystemAssigned` for `azurerm_automation_account`, so I'm not sure why your account does not work.

---
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test1" {
  name     = "test-recovery-update"
  location = "eastus"
}

resource "azurerm_automation_account" "test" {
  name                = "test-acctestAutomation"
  location            = azurerm_resource_group.test1.location
  resource_group_name = azurerm_resource_group.test1.name

  sku_name = "Basic"
  identity {
    type = "SystemAssigned"
  }
  tags = {
    Environment = "Test"
  }
}

resource "azurerm_recovery_services_vault" "test" {
  name                = "test-vault"
  location            = azurerm_resource_group.test1.location
  resource_group_name = azurerm_resource_group.test1.name
  sku                 = "Standard"

  identity {
    type = "SystemAssigned"
  }

  soft_delete_enabled = false
}

resource "azurerm_site_recovery_fabric" "test1" {
  resource_group_name = azurerm_resource_group.test1.name
  recovery_vault_name = azurerm_recovery_services_vault.test.name
  name                = "test-fabric1"
  location            = azurerm_resource_group.test1.location
}

resource "azurerm_site_recovery_fabric" "test2" {
  resource_group_name = azurerm_resource_group.test1.name
  recovery_vault_name = azurerm_recovery_services_vault.test.name
  name                = "test-fabric2"
  location            = "eastus2"
  depends_on          = [azurerm_site_recovery_fabric.test1]
}

resource "azurerm_site_recovery_protection_container" "test1" {
  resource_group_name  = azurerm_resource_group.test1.name
  recovery_vault_name  = azurerm_recovery_services_vault.test.name
  recovery_fabric_name = azurerm_site_recovery_fabric.test1.name
  name                 = "test-container-1"
}

resource "azurerm_site_recovery_protection_container" "test2" {
  resource_group_name  = azurerm_resource_group.test1.name
  recovery_vault_name  = azurerm_recovery_services_vault.test.name
  recovery_fabric_name = azurerm_site_recovery_fabric.test2.name
  name                 = "test-container-2"
}

resource "azurerm_site_recovery_replication_policy" "test" {
  resource_group_name                                  = azurerm_resource_group.test1.name
  recovery_vault_name                                  = azurerm_recovery_services_vault.test.name
  name                                                 = "test-policy"
  recovery_point_retention_in_minutes                  = 24 * 60
  application_consistent_snapshot_frequency_in_minutes = 4 * 60
}

resource "azurerm_site_recovery_protection_container_mapping" "test" {
  resource_group_name                       = azurerm_resource_group.test1.name
  recovery_vault_name                       = azurerm_recovery_services_vault.test.name
  recovery_fabric_name                      = azurerm_site_recovery_fabric.test1.name
  recovery_source_protection_container_name = azurerm_site_recovery_protection_container.test1.name
  recovery_target_protection_container_id   = azurerm_site_recovery_protection_container.test2.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.test.id
  name                                      = "container-mapping"
  automatic_update {
    enabled               = true
    automation_account_id = azurerm_automation_account.test.id
  }
}
```

And, just to confirm, the "un-healthy" shows up after depolying `azurerm_site_recovery_protection_container_mapping`, or after depolying `azurerm_site_recovery_replicated_vm`?

**Comment by mpjtaylor** [comment]
yes the same as you , but when you go to the ASR its un-healthy deploying `azurerm_site_recovery_protection_container_mapping` nothing to do with the VM

**Comment by mpjtaylor** [comment]
Have deployed many of these now all show un-healthy

**Comment by hofmannma** [comment]
Same here.... it is un-healthy...
![image](https://user-images.githubusercontent.com/51420906/218101997-b07215be-8925-4759-ae1b-3bc548e8314d.png)

**Comment by hofmannma** [comment]
By the way - if you execute an ASR non of the existing extensions are on the VM recovered through ASR. So if you start to manage your ASR-failover VM through terraform it will redeploy all the extensions again.

**Comment by hofmannma** [comment]
Any updates?
Also the updates are not running because it still attempts a runas account vs. manaaged identity. But runas account are going away...
![image](https://user-images.githubusercontent.com/51420906/234981501-e0e32ab1-774c-40ad-84b6-fc6e9ecbbfae.png)
![image](https://user-images.githubusercontent.com/51420906/234981831-4e701302-2aa2-478d-97c2-8a39f0cfd68d.png)

**Comment by ziyeqf** [comment]
Hi @hofmannma and @mpjtaylor , thanks for the reporting and the details.

I have submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/21688) to support using `SystemAssginedIdentity` as authentication type for the Automation Account. You can keep track on it by subscripting the PR.

For any further questions please leave comments.
Thanks!
