### ISSUE TITLE
azurerm_data_factory_flowlet_data_flow requires sink and source

### ISSUE THREAD

**Issue by supereddie** [hashicorp/terraform-provider-azurerm#20301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_flowlet_data_flow azurerm_data_factory_data_flow

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_data_factory" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_data_factory_flowlet_data_flow" "flowlet1" {
  name            = "flowlet1"
  data_factory_id = azurerm_data_factory.example.id

  transformation {
    name = "output1"
  }

  transformation {
    name = "input1"
  }
  script = <<EOT
  input(order: 0,
	allowSchemaDrift: true) ~> input1
  input1 output() ~> output1
  EOT
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/supereddie/7a4dda547c13cf80b371f19174e392bd#file-log-1
```

### Expected Behaviour

The flowlet  (or dataflow) configuration should be correct, since manually creating a flowlet without sources or sinks in DataFactory is no issue.

### Actual Behaviour

The following errors appear:
```
╷   
│ Error: Insufficient sink blocks
│
│   on bug-reporting.tf line 26, in resource "azurerm_data_factory_flowlet_data_flow" "flowlet1":
│   26: resource "azurerm_data_factory_flowlet_data_flow" "flowlet1" {
│
│ At least 1 "sink" blocks are required.
╵
╷
│ Error: Insufficient source blocks
│
│   on bug-reporting.tf line 26, in resource "azurerm_data_factory_flowlet_data_flow" "flowlet1":
│   26: resource "azurerm_data_factory_flowlet_data_flow" "flowlet1" {
│
│ At least 1 "source" blocks are required.
╵
```

### Steps to Reproduce

1. `terraform validate`

**Comment by ms-henglu** [comment]
Hi @supereddie ,

Thank you for taking time to report this issue!

I tried to create the flow let data flow without source and since, but I saw this error from the Portal.

<img width="1458" alt="image" src="https://user-images.githubusercontent.com/79895375/217139545-ba3f3809-96de-4abe-a94e-31e81ad87c0e.png">

**Comment by supereddie** [comment]
Hi @ms-henglu ,

It appears my simplified example was a little too simplified.

I have delved a little deeper, and found the following:
- A flowlet does not seem to have a Sink option in the designer, only an 'output'. So in the designer it is not possible to add a Sink.
![image](https://user-images.githubusercontent.com/7723579/217485917-b483b85b-ebc5-4a16-92a3-bb605686e440.png)
- A flowlet either needs a Source or an 'input' (this determines where it can be used in a dataflow)
- In a dataflow, the Source and Sink requirement seem to depend on the contents of the flowlets. I think that in total (including pipeline), there needs to be a Source and a Sink somewhere, but not necessarily in the dataflow or flowlets.

These give no errors with the Validate-button in the designer, since there is one Source in the flowlet, and one Sink in the dataflow:
![image](https://user-images.githubusercontent.com/7723579/217490261-24835277-69cb-4a48-b564-98591f3ab208.png)
![image](https://user-images.githubusercontent.com/7723579/217490715-80213657-0c18-4864-900a-eb4663aac3ec.png)

Based on this, it is not valid for terraform to require both Source and Sink in the flowlet and dataflow resources.

**Comment by taniab** [comment]
I'm having the same problem, are there any updates regarding this issue?
