### ISSUE TITLE
Support for Network security group id in Subnet

### ISSUE THREAD

**Issue by decewei** [hashicorp/terraform-provider-azurerm#20322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From reading previous issue like https://github.com/hashicorp/terraform-provider-azurerm/issues/3054, it seems like network security id has been deprecated in azurerm_subnet. 

I want to apply organization-wide security policy, that no subnet can be deployed without a network security group associated with. This can't be done if we have to associate them in a separate creation API. It will always fail at the creation of the subnet.

Is there anyway we could do this with current azurerm? If not, can we support this?

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

**Comment by tombuildsstuff** [comment]
hi @decewei 

This field has been intentionally removed from the `azurerm_subnet` resource to workaround issues within the Azure Platform during the deletion of resources, as this field has been intentionally removed unfortunately this isn't something we plan to reintroduce.

Instead #9022 is tracking adding an example of how to use Azure Policy with the separate resources, and #3917 is tracking adding additional fields within the `azurerm_virtual_network` resource - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!
