### ISSUE TITLE
azurerm_disk_encryption_set unable to refer the correct vault ID

### ISSUE THREAD

**Issue by vikas027** [hashicorp/terraform-provider-azurerm#20323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_disk_encryption_set

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "kv" {
  name                            = local.vault_name
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = azurerm_resource_group.rg.location
  tenant_id                       = data.azurerm_client_config.current.tenant_id
  sku_name                        = "standard"
  purge_protection_enabled        = true
  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = true
  public_network_access_enabled   = true
}

resource "azurerm_disk_encryption_set" "des" {
  name                = "${local.resource_group}-des"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  # Fails with error `KeyVault Nested Item should contain 2 or 3 segments, got 8`
  key_vault_key_id    = azurerm_key_vault.kv.id
  
  # Works fine
  # key_vault_key_id = "https://<omiited>.vault.azure.net/keys/<omiited>-disk-encryption-key/<omiited>"

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/<omiited>/resourceGroups/<omiited>/providers/Microsoft.KeyVault/vaults/<omiited>": KeyVault Nested Item should contain 2 or 3 segments, got 8 from "subscriptions/<omiited>/resourceGroups/<omiited>/providers/Microsoft.KeyVault/vaults/<omiited>"
```

### Expected Behaviour

The provider should have found the correct vault resource ID and created the disk encryption set.

### Actual Behaviour

The provider failed to find the correct ID

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14401

**Comment by myc2h6o** [comment]
Hi @vikas027 `key_vault_key_id` is the ID of the key and not the vault. It is the id from [azurerm_key_vault_key](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_key)

**Comment by vikas027** [comment]
Ah, my bad. Sorry for the noise.
