### ISSUE TITLE
Support for different vnet_subnet_id for multiple nodepools

### ISSUE THREAD

**Issue by mracfa** [hashicorp/terraform-provider-azurerm#20330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support to have different subnets (inside same vnet) for different nodepools. We have this feature in AKS  for 1+ years (at least).

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### References

https://learn.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-node-pool-with-a-unique-subnet

**Comment by aristosvo** [comment]
Let me check how difficult this might be, will bring back an update when I know
