### ISSUE TITLE
Non empty plan when azurerm_route_table.route.*.next_hop_in_ip_address is omitted due to Azure insisting it is an empty string, while terraform setting null.

### ISSUE THREAD

**Issue by MarkKharitonov** [hashicorp/terraform-provider-azurerm#20340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_route_table

### Terraform Configuration Files

```hcl
locals {
  # Order route entries by address_prefix
  routes = {
    eastus2 = values({ for o in concat([for i, route_cidr in [
      "...",
      ] : {
      name           = "Akamai_${format("%02s", i + 1)}"
      address_prefix = route_cidr
      next_hop_type  = "Internet"
      }], [...]) : o.address_prefix => o })
  }
}
...
resource "azurerm_route_table" "route_table" {
  for_each                      = var.route_tables
  name                          = each.value.name
  location                      = var.location
  resource_group_name           = var.resource_group_name
  disable_bgp_route_propagation = each.value.disable_bgp_route_propagation
  tags                          = var.tags

  dynamic "route" {
    for_each = each.value.routes
    content {
      name                   = route.value.name
      address_prefix         = route.value.address_prefix
      next_hop_type          = route.value.next_hop_type
      next_hop_in_ip_address = route.value.next_hop_in_ip_address
    }
  }
}
```

### Debug Output/Panic Output

The plan looks like this:
```
# module.bootstrap.module.vnets["eastus2"].azurerm_route_table.route_table["eastus2"] will be updated in-place
# (moved from module.bootstrap.module.vnets["eastus2"].azurerm_route_table.route_table["rt0"])
~ resource "azurerm_route_table" "route_table" {
      id                            = "/subscriptions/4...d/resourceGroups/xyz/providers/Microsoft.Network/routeTables/abc"
      name                          = "abc"
    ~ route                         = [
        - {
            - address_prefix         = "104......../24"
            - name                   = "Akamai_32"
            - next_hop_in_ip_address = ""
            - next_hop_type          = "Internet"
          },
        + {
            + address_prefix         = "104......../24"
            + name                   = "Akamai_32"
            + next_hop_in_ip_address = null
            + next_hop_type          = "Internet"
          },
        - {
            - address_prefix         = "172......../24"
            - name                   = "Akamai_33"
            - next_hop_in_ip_address = ""
            - next_hop_type          = "Internet"
          },
        + {
            + address_prefix         = "172......../24"
            + name                   = "Akamai_33"
            + next_hop_in_ip_address = null
            + next_hop_type          = "Internet"
          },
...
```

### Expected Behaviour

Applying the configuration the second time produces an empty plan.

### Actual Behaviour

The same dirty plan is reported.

So the problem is this:
1. terraform sets `azurerm_route_table.route.*.next_hop_in_ip_address` to `null`.
1. Azure reports that the actual value is the empty string `""`.

Hence terraform plans to update. However, applying the plan does not change anything - the next plan is dirty still, because Azure continues to report absent `azurerm_route_table.route.*.next_hop_in_ip_address` as `""`. Ordinarily, this is fixed by us passing `""` - to match what Azure does. But `""` is an invalid value for this attribute.

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/2736

**Comment by karlparry** [comment]
We are also seeing this issue. First plan worked, not going forward all plans are failing with the error the same as yours:
```
##[error]PowerShell exited with code '1'.
##[error]PowerShell wrote one or more lines to the standard error stream.
##[error]╷
│ Error: expected "route.0.next_hop_in_ip_address" to not be an empty string, got 
│ 
│   with azurerm_route_table.app_gateway_to_test_route,
│   on application_gateway.tf line 494, in resource "azurerm_route_table" "app_gateway_to_test_route":
│  494: resource "azurerm_route_table" "app_gateway_to_test_route" {
│ 
```

**Comment by MarkKharitonov** [comment]
@katbyte - would you be able to explain how we can avoid the redundant plan now after this fix? The empty string for `next_hop_in_ip_address` is still rejected. Omitting the attribute generates the same redundant plan as described in the body of the issue.

It is unclear how the fix helps eliminate the redundant plan. Please, clarify. Thank you.
