### ISSUE TITLE
azurerm_app_service ignore source control changes

### ISSUE THREAD

**Issue by mirandavj** [hashicorp/terraform-provider-azurerm#20355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

2.96.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "app-service" {
  name                = "my-app-service"
  resource_group_name = "my-resource-group"
  app_service_plan_id = "my-app-service-plan"
  location            = "eastus2"

  site_config {
    dotnet_framework_version = "v4.0"
  }

  app_settings = {
    "MY_KEY" = "my-value"
  }

  lifecycle {
    ignore_changes = [
      tags,
      app_settings,
      source_control,
      site_config.0.scm_type
    ]
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: failed to update App Service Source Control for "my-app-service" (Resource Group "my-resource-group"): web.AppsClient#CreateOrUpdateSourceControl: Failure sending request: StatusCode=404 -- Original Error: Code="NotFound" Message="Cannot find User with name ****." Details=[{"Message":"Cannot find User with name ****."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"51004","Message":"Cannot find User with name ****.","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["User","****"]}}]

If the SCM config created through the portal somehow breaks, it results in the output shown above.
```

### Expected Behaviour

Changes to source control done through the portal should have been ignored.

### Actual Behaviour

I'm not configuring **scm_type** in the **site config** or **source_control** block for **azurerm_app_service**.

However if an user changes this in the deployment center through the portal, Terraform would detect those changes no matter how i configured the ignore changes to ignore either the **source_control** block or **scm_type** in the **site config**.

The idea is to ignore changes related to source control so that once the resource is deployed user can configure that in the Azure portal, and terraform apply moving forward wouldn't fail because of anything related to source control.

### Steps to Reproduce

terraform init
terraform apply
change source control in azure portal
terraform apply

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
