### ISSUE TITLE
azurerm_site_recovery_protection_container_mapping automatic_update true forces replacement

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#20357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

1.34.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_protection_container_mapping

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_protection_container_mapping" "container-mapping" {
  name                                      = "container-mapping"
  resource_group_name                       = azurerm_recovery_services_vault.recovery.resource_group_name
  recovery_vault_name                       = azurerm_recovery_services_vault.recovery.name
  recovery_fabric_name                      = azurerm_site_recovery_fabric.primary.name
  recovery_source_protection_container_name = azurerm_site_recovery_protection_container.primary.name
  recovery_target_protection_container_id   = azurerm_site_recovery_protection_container.secondary.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  automatic_update {
    enabled               = true
    automation_account_id = azurerm_automation_account.support.id
  }
}
```

### Debug Output/Panic Output

```shell
Error: deleting site recovery protection container mapping Replication Protection Container Mapping (Subscription: "xxxxx-xxxx-xxx-xxx-xxxxxx" Resource Group Name: "xxxxx" Vault Name: "xxxxx" Replication Fabric Name: "primary-fabric" Replication Protection Container Name: "primary-protection-container" Replication Protection Container Mapping Name: "container-mapping") : polling after Delete: Code="15008" Message="Configuration settings couldn't be removed."
```
```


### Expected Behaviour

Adding automation should not recreate `azurerm_site_recovery_protection_container_mapping`

### Actual Behaviour

Terraform wants to destory the container but it cannot as its in use by virtual machines

### Steps to Reproduce

terraform apply

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/20304

**Comment by ziyeqf** [comment]
Hi @mpjtaylor, thanks for report!

Have submitted a PR(#20383 ) to fix this, it will be fixed when this PR merged & released.

Thanks!

**Comment by mpjtaylor** [comment]
this wasn't released? tested this morning with version 3.43.0

**Comment by mpjtaylor** [comment]
thanks for confirming :)

**Comment by mpjtaylor** [comment]
this is not in 3.44.0 either? how can i get this fix waiting on it 

Thanks

**Comment by ziyeqf** [comment]
> this is not in 3.44.0 either? how can i get this fix waiting on it
> 
> Thanks

the code was invovled, changing `automatic_update` block should not force a replacement for now. Could you please check if there are any other changes in config?

**Comment by mpjtaylor** [comment]
yes this works still unhealthy but now not causing a replacement :)
