### ISSUE TITLE
network_security_group_association and route_table_association keep creating resources with multiple "terraform apply" on available NSG or RT

### ISSUE THREAD

**Issue by IchiruTake** [hashicorp/terraform-provider-azurerm#20363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3

### AzureRM Provider Version

3.37 or above

### Affected Resource(s)/Data Source(s)

subnet_route_table_association and subnet_network_security_group_association

### Terraform Configuration Files

```hcl
data "azurerm_subnet" "subnet" {
  resource_group_name  = var.resource_group_name
  name                 = var.subnet_name
  virtual_network_name = var.virtual_network_name
}

resource "azurerm_network_security_group" "nsg" {
    resource_group_name = var.resource_group_name
    name                = var.nsg_name
    location            = var.nsg_location
    tags                = var.nsg_tags
    depends_on = [
        data.azurerm_subnet.subnet
    ]
}

resource "azurerm_subnet_network_security_group_association" "nsg_association" {  
  network_security_group_id = azurerm_network_security_group.nsg.id
  subnet_id                 = data.azurerm_subnet.subnet.id
  
  depends_on = [
    azurerm_network_security_group.nsg
  ]
}

output "nsg_record" {
    value = {
        resource_group_name = azurerm_network_security_group.nsg.resource_group_name
        name                = azurerm_network_security_group.nsg.name
    }
    description = "The network security group record to reproduce the data sources."
}

resource "azurerm_route_table" "rt" {
  resource_group_name           = var.resource_group_name
  name                          = var.rt_name
  location                      = var.rt_location 
  disable_bgp_route_propagation = var.rt_disable_bgp_route_propagation
  tags                          = var.rt_tags
  depends_on = [
    data.azurerm_subnet.subnet
  ]
}

resource "azurerm_subnet_route_table_association" "rtAssociation" {
  subnet_id      = data.azurerm_subnet.subnet.id
  route_table_id = azurerm_route_table.rt.id
  depends_on = [
    azurerm_route_table.rt
  ]
}

output "rt_record" {
  value = {
    resource_group_name = azurerm_route_table.rt.resource_group_name
    name                = azurerm_route_table.rt.name
  }
}

resource "azurerm_mssql_managed_instance" "server" {
...
}

```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Both subnet_route_table_association and subnet_network_security_group_association should not be created when the TF (base) resource is already available.
-> HOWTO troubleshoot (from the provider side) -> Add these two resources into the tfstate or the Azure API so that the Terraform can decide if the associate is available.

### Actual Behaviour

New subnet_route_table_association and subnet_network_security_group_association are kept creating despite successful previous attempt.

### Steps to Reproduce

terraform apply

### Important Factoids

Public

### References

[#17565](https://github.com/hashicorp/terraform-provider-azurerm/issues/17565)

**Comment by IchiruTake** [comment]
I think the possible solution is to gather the data source of the azurerm_subnet and verifiy if route_table_id or nsg_id is available or not

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems I didn't encounter this issue and the resource isn't kept creating after tested with latest azurerm provider and below tf config.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-nscga-test01"
  location = "west europe"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvirtnettest01"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
}

data "azurerm_subnet" "subnet" {
  resource_group_name  = azurerm_subnet.test.resource_group_name
  name                 = azurerm_subnet.test.name
  virtual_network_name = azurerm_subnet.test.virtual_network_name
}

resource "azurerm_network_security_group" "nsg" {
  name                = "acctestnsgtest01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  depends_on = [
    data.azurerm_subnet.subnet
  ]
}

resource "azurerm_subnet_network_security_group_association" "nsg_association" {  
  network_security_group_id = azurerm_network_security_group.nsg.id
  subnet_id                 = data.azurerm_subnet.subnet.id
  
  depends_on = [
    azurerm_network_security_group.nsg
  ]
}

resource "azurerm_route_table" "rt" {
  name                          = "acctestrttest01"
  location                      = azurerm_resource_group.test.location
  resource_group_name           = azurerm_resource_group.test.name
  disable_bgp_route_propagation = true

  depends_on = [
    data.azurerm_subnet.subnet
  ]
}

resource "azurerm_subnet_route_table_association" "rtAssociation" {
  subnet_id      = data.azurerm_subnet.subnet.id
  route_table_id = azurerm_route_table.rt.id

  depends_on = [
    azurerm_route_table.rt
  ]
}
```

![image](https://user-images.githubusercontent.com/19754191/217697769-1b0c240f-3aba-4c59-aea9-583a90f834be.png)

![image](https://user-images.githubusercontent.com/19754191/217697741-99a3cfc1-94b1-42b3-8bf7-7f1aeb5f2f6a.png)

**Comment by IchiruTake** [comment]
Thank you, I have discovered the problem. In my code, I create two NSG and RT and associate them into one subnet whilst creating the Azure SQL Managed Instance (the NSG name is "nsg-${var.managed_instance_name}" and the RT name is "rt-${var.managed_instance_name}"). 
When I discover the document on Azure, it said that only one subnet can only handle at most one NSG and R, thus when the Terraform resource is disconnected, it caused me error when the tfstate is not updated the new disassociation. Thank you for your support. 

P/s: Can you double-check the Terraform code to help me verify this issue when two or more NSG/RT is associated to one subnet? At least I hope that it could give me the correct error


> Thanks for raising this issue. Seems I didn't encounter this issue and the resource isn't kept creating after tested with latest azurerm provider and below tf config. Could you try below tf config to see if the issue still exists with below tf config that is similar with yours?
> 
> tf config:
> 
> ```
> provider "azurerm" {
>   features {}
> }
> 
> resource "azurerm_resource_group" "test" {
>   name     = "acctestRG-nscga-test01"
>   location = "west europe"
> }
> 
> resource "azurerm_virtual_network" "test" {
>   name                = "acctestvirtnettest01"
>   address_space       = ["10.0.0.0/16"]
>   location            = azurerm_resource_group.test.location
>   resource_group_name = azurerm_resource_group.test.name
> }
> 
> resource "azurerm_subnet" "test" {
>   name                 = "internal"
>   resource_group_name  = azurerm_resource_group.test.name
>   virtual_network_name = azurerm_virtual_network.test.name
>   address_prefixes     = ["10.0.2.0/24"]
> }
> 
> data "azurerm_subnet" "subnet" {
>   resource_group_name  = azurerm_subnet.test.resource_group_name
>   name                 = azurerm_subnet.test.name
>   virtual_network_name = azurerm_subnet.test.virtual_network_name
> }
> 
> resource "azurerm_network_security_group" "nsg" {
>   name                = "acctestnsgtest01"
>   location            = azurerm_resource_group.test.location
>   resource_group_name = azurerm_resource_group.test.name
> 
>   depends_on = [
>     data.azurerm_subnet.subnet
>   ]
> }
> 
> resource "azurerm_subnet_network_security_group_association" "nsg_association" {  
>   network_security_group_id = azurerm_network_security_group.nsg.id
>   subnet_id                 = data.azurerm_subnet.subnet.id
>   
>   depends_on = [
>     azurerm_network_security_group.nsg
>   ]
> }
> 
> resource "azurerm_route_table" "rt" {
>   name                          = "acctestrttest01"
>   location                      = azurerm_resource_group.test.location
>   resource_group_name           = azurerm_resource_group.test.name
>   disable_bgp_route_propagation = true
> 
>   depends_on = [
>     data.azurerm_subnet.subnet
>   ]
> }
> 
> resource "azurerm_subnet_route_table_association" "rtAssociation" {
>   subnet_id      = data.azurerm_subnet.subnet.id
>   route_table_id = azurerm_route_table.rt.id
> 
>   depends_on = [
>     azurerm_route_table.rt
>   ]
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/19754191/217697769-1b0c240f-3aba-4c59-aea9-583a90f834be.png)
> 
> ![image](https://user-images.githubusercontent.com/19754191/217697741-99a3cfc1-94b1-42b3-8bf7-7f1aeb5f2f6a.png)

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
