### ISSUE TITLE
azurerm_recovery_services_vault cross_region_restore_enabled = true -> false not working

### ISSUE THREAD

**Issue by Klaas-** [hashicorp/terraform-provider-azurerm#20373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tfex-recovery_vault"
  location = "West Europe"
}

resource "azurerm_recovery_services_vault" "backup_vault" {
  name                         = "example-recovery-vault"
  location                     = azurerm_resource_group.example.location
  resource_group_name          = azurerm_resource_group.example.name
  sku                          = "Standard"
  cross_region_restore_enabled = true ## change to false on 2nd run

  soft_delete_enabled = false
}
```

### Debug Output/Panic Output

```shell
Creation works, update to cross_region_restore_enabled = false does not work
The update never finishes, so I am guessing the API does not respond properly :) In portal I can see "Cross Region Restore is currently non-reversible storage property." so I am guessing this means it's a property where true -> false means recreation, false -> true should work (haven't tested that though)
```

### Expected Behaviour
```

  # azurerm_recovery_services_vault.backup_vault will be recreated
  ~ resource "azurerm_recovery_services_vault" "backup_vault" {
      ~ cross_region_restore_enabled  = true -> false
```

### Actual Behaviour

```
  # azurerm_recovery_services_vault.backup_vault will be updated in-place
  ~ resource "azurerm_recovery_services_vault" "backup_vault" {
      ~ cross_region_restore_enabled  = true -> false
```

### Steps to Reproduce

* terraform apply
* change cross_region_restore_enabled  to false
* terraform apply [does not finish]

**Comment by ziyeqf** [comment]
Hi @Klaas- ,thanks for reporting.

You are right once `cross_region_restore_enabled` been set to true, it does not allowed to set it to `false` again. Have submitted a PR(#20406 ) to limit this. When this PR merged & released, it will be fixed.

And please note: in this fix, changing `cross_region_restore_enabled` from `true` to `false` will force a new `azurerm_recovery_services_vault` to be created.

For any furthur questions please leave comments.
Thanks!
