### ISSUE TITLE
azurerm_app_service_certificate cannot find my App Certificate

### ISSUE THREAD

**Issue by linak-lukasmendez** [hashicorp/terraform-provider-azurerm#20372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_certificate

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_custom_hostname_binding" "portal" {
  count               = var.app_service.portal.host_name == "" ? 0 : 1

  hostname            = local.portal_host_name
  app_service_name    = azurerm_windows_web_app.portal.name
  resource_group_name = azurerm_windows_web_app.portal.resource_group_name

  # Ignore ssl_state and thumbprint as they are managed using
  # azurerm_app_service_certificate_binding
  lifecycle {
    ignore_changes = [ssl_state, thumbprint]
  }
}

data "azurerm_app_service_certificate" "portal" {
  name                = "OneConnectCertificate"
  resource_group_name = "GlobalResources"
}

resource "azurerm_app_service_certificate_binding" "portal" {
  count               = var.app_service.portal.host_name == "" ? 0 : 1

  hostname_binding_id = azurerm_app_service_custom_hostname_binding.portal[0].id
  certificate_id      = data.azurerm_app_service_certificate.portal.id
  ssl_state           = "SniEnabled"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Certificate: (Name "OneConnectCertificate" / Resource Group "GlobalResources") does not exist
│
│   with data.azurerm_app_service_certificate.portal,
│   on app_service.tf line 95, in data "azurerm_app_service_certificate" "portal":
│   95: data "azurerm_app_service_certificate" "portal" {
│
╵
```

### Expected Behaviour

The app service certificate should be found and used for the certificate binding

### Actual Behaviour

Terraform claims that the certificate does not exist at all, which is not true:

![image](https://user-images.githubusercontent.com/115475014/217545925-e40c2c94-76d7-4681-93fa-fb9742b2a583.png)

I am also able to find it if I want to bind it manually: 

![image](https://user-images.githubusercontent.com/115475014/217546120-bc78de1c-15a4-412a-949b-f1bf522a806c.png)

So it's a question to me why Terraform cannot find it. 

### Important Factoids

No

**Comment by xiaxyi** [comment]
Thanks @linak-lukasmendez for raising this issue, can you try getting this cert using powershell or azure cli to see if the cert can be retrieved?

**Comment by linak-lukasmendez** [comment]
Actually that does not seem to be the case.

![image](https://user-images.githubusercontent.com/115475014/218045728-8eaa8d62-1319-4109-b301-3f25e7b56df0.png)

 Just very weird that I can see it from the portal.. 

![image](https://user-images.githubusercontent.com/115475014/218045897-ab38d6d9-e025-4ae2-aa0e-6c1c2533d418.png)

**Comment by MmAtBosch** [comment]
I have a similar issue when creating a new Web app, uploading a certificate into it and creating the hostname binding.
In 50% of the cases, this fails with
`web.AppsClient#CreateOrUpdateHostNameBinding: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="Cannot find Certificate with name 8438937506179AB62464D6E6B3D77E8A1F8B1EE4." Details=[{"Message":"Cannot find Certificate with name 8438937506179AB62464D6E6B3D77E8A1F8B1EE4."},{"Code":"NotFound"},{"ErrorEntity":{"Code":"NotFound","ExtendedCode":"51004","Message":"Cannot find Certificate with name 8438937506179AB62464D6E6B3D77E8A1F8B1EE4.","MessageTemplate":"Cannot find {0} with name {1}.","Parameters":["Certificate","8438937506179AB62464D6E6B3D77E8A1F8B1EE4"]}}]`

When i check the cert via CLI its there.
az webapp config ssl list -g myRg--query [].thumbprint -o tsv
8438937506179AB62464D6E6B3D77E8A1F8B1EE4

really annoying.

using Terraform v1.5.2 and azurerm version 3.58.0

**Comment by ryankelley** [comment]
@MmAtBosch Ever find a resolution to your error? I am experiencing the same issue and same error as you were seeing.

**Comment by ryankelley** [comment]
> @MmAtBosch Ever find a resolution to your error? I am experiencing the same issue and same error as you were seeing.

Actually, scratch that, solution I found was a note in the documentation, the app service certificate has to be created in the same resource group as the app service plan.

**Comment by MmAtBosch** [comment]
> @MmAtBosch Ever find a resolution to your error? I am experiencing the same issue and same error as you were seeing.

no, somewhen i stopped working on this...

**Comment by MmAtBosch** [comment]
> > @MmAtBosch Ever find a resolution to your error? I am experiencing the same issue and same error as you were seeing.
> 
> Actually, scratch that, solution I found was a note in the documentation, the app service certificate has to be created in the same resource group as the app service plan.

interesting! thank you

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ryankelley‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
