### ISSUE TITLE
`azurerm_storage_account`: does not track ip network-rules

### ISSUE THREAD

**Issue by yellowhat** [hashicorp/terraform-provider-azurerm#20388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

`azurerm_storage_account`,

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "zz_deleteme"
  location = "West Europe"
}

resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_storage_account" "this" {
  name                = "blobstorage${random_integer.ri.result}"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"

  public_network_access_enabled   = false
  allow_nested_items_to_be_public = false
  enable_https_traffic_only       = true
  min_tls_version                 = "TLS1_2"

  network_rules {
    default_action = "Deny"
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_service_plan" "this" {
  name                = "appserviceplanname"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name
  os_type             = "Linux"
  sku_name            = "P1v2"
  worker_count        = 1
}

resource "azurerm_linux_web_app" "this" {
  name                = "appservice${random_integer.ri.result}"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
  service_plan_id     = azurerm_service_plan.this.id
  https_only          = true

  site_config {
    always_on              = true
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_role_assignment" "app_blob" {
  scope                = azurerm_storage_account.this.id
  principal_id         = azurerm_linux_web_app.this.identity.0.principal_id
  role_definition_name = "Storage Blob Data Contributor"
}

resource "azurerm_app_service_connection" "blob" {
  name               = "blobStorage"
  app_service_id     = azurerm_linux_web_app.this.id
  target_resource_id = azurerm_storage_account.this.id
  client_type        = "java"
  authentication {
    type = "systemAssignedIdentity"
  }
}
```

### Debug Output/Panic Output

```shell
The `azurerm_app_service_connection` resource creates network-rule ips on the Storage Account to whitelist the App Service outbound public ip.
Ideally, I would like to have an option not to do that.

Anyway, the new `ip` rules are not part of the terraform state:


$ terraform apply -refresh -auto-approve
...
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
```

### Expected Behaviour

New network-rule ips are deleted

### Actual Behaviour

New network-rule ips are not part of the state

**Comment by magodo** [comment]
@yellowhat You'd be able to explicitly specify the `ip_rules` in the `azurerm_storage_account` resource like below:

```hcl
resource "azurerm_storage_account" "example" {
  ...
  network_rules {
    ...
    ip_rules                   = [] # setting this to an empty array to clean up ip rules
  }
  ...
}
```

The caveat is that due to the dependency order, the `azurerm_app_service_connection` is applied after `azurerm_storage_account`, which means the `ip_rules` will be overriden by the `azurerm_app_service_connection`. Whilst you can override it back with a second apply, though not ideal.

The reason why terraform doesn't tell you the diff during plan is that the `ip_rules` is marked as optional and computed in the provider: https://github.com/hashicorp/terraform-provider-azurerm/blob/72f0799cec36e848d997dfb8d0c0d60bb0931b39/internal/services/storage/storage_account_resource.go#L387-L396

This is set as is mainly to support configuring the network rules either inlined in the `azurerm_storage_account` or standalone by using the `azurerm_storage_account_network_rules` resource.
