### ISSUE TITLE
azurerm_linux_virtual_machine and azurerm_windows_virtual_machine 'adminUsername' and 'adminPassword' validation

### ISSUE THREAD

**Issue by juanjojulian** [hashicorp/terraform-provider-azurerm#20400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Description

In Azure API there are a number of restrictions related to Virtual Machine 'adminUsername' and 'adminPassword', it would be nice to include some validations at provider level to verify that those restrictions are met and make the user fail fast instead of waiting for an API error. 

https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#osprofile

![](https://user-images.githubusercontent.com/43988825/217765567-584b8efc-b85c-4194-8d29-68db296b6da2.png)

![](https://user-images.githubusercontent.com/43988825/217766166-d5a6e51d-cfcb-444b-b1f3-d25de46ec9f5.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine, azurerm_windows_virtual_machine

**Comment by stephybun** [comment]
Closed by #20558
