### ISSUE TITLE
azurerm_mysql_flexible_server internal server error with geo_redundant_backup and customer managed key

### ISSUE THREAD

**Issue by andreipantelimon** [hashicorp/terraform-provider-azurerm#20408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.9

### AzureRM Provider Version

3.41.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexbile_server

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_flexible_server" "server" {
  name                   = var.sqlserver_name
  resource_group_name    = var.rg_name
  location               = var.location
  version                = var.sqlserver_version
  administrator_login    = var.administrator_sql_login
  administrator_password = var.administrator_sql_password
  sku_name               = var.sku_name
  geo_redundant_backup_enabled = true
  backup_retention_days        = 7

  customer_managed_key {
    key_vault_key_id                  = var.key_vault_key_id
    primary_user_assigned_identity_id = var.primary_user_assigned_identity_id
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Flexible Server (Subscription: "$SUB_ID"
Resource Group Name: "$RG_NAME"
Flexible Server Name: "$SERVER_NAME"): polling after Create: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '$TRACKING_ID'"

  with module.mysql-flexible-server.azurerm_mysql_flexible_server.server,
  on ../../modules/mysql-flexible-server/main.tf line 39, in resource "azurerm_mysql_flexible_server" "server":
  39: resource "azurerm_mysql_flexible_server" "server" {
```

### Expected Behaviour

When provided a customer managed key for data encryption, terraform provider should put the same key or offer the option to select another key for the geo-redundant-backup server. Currently, the geo-redundant server does not get any CMK and a conflict appears, as from the Microsoft's official answer.

### Actual Behaviour

The same CMK should have been provided to the geo-redundant backup server as well.

### Steps to Reproduce

terraform apply with both options enabled (geo_redundant_backup_enabled and customer_managed_key block)

### Important Factoids

No

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. When `geoRedundantBackup` is enabled, `geoBackupKeyURI` and `geoBackupUserAssignedIdentityId` also need to be set. But unfortunately, these two properties haven't been supported by TF for now.
