### ISSUE TITLE
azurerm_container_app - Support pulling container images from ACR using managed identity

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-azurerm#20412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it does not seem possible to use a managed identity to pull images from an Azure Container Registry.

Using the azapi_resource for type `Microsoft.App/containerApps`, one could do the following

```hcl
        registries = [
          {
            identity = <resource id of managed identity>
            server   = "myregistry.azurecr.io"
          }
        ]
```

While the current config has both username and password_secret_name as required

```hcl
  registry {
    server               = "myregistry.azurecr.io"
    username             = <resource id of managed identity>
    password_secret_name = "clientsecretname"
  }
```

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

**Comment by faheemgani** [comment]
This is causing us an issue as well - we rely on managed identity against the container app instance to access services such as key vaults.

Currently there is no way of setting managed identity if you use the `azurerm_container_app` resource, perhaps it's possible to implement an identity block similar to some of the other azure terraform resources?

e.g. `  identity {
    type = "SystemAssigned"
  } `

**Comment by audunsolemdal** [comment]
> This is causing us an issue as well - we rely on managed identity against the container app instance to access services such as key vaults.
> 
> Currently there is no way of setting managed identity if you use the `azurerm_container_app` resource, perhaps it's possible to implement an identity block similar to some of the other azure terraform resources?
> 
> e.g. ` identity { type = "SystemAssigned" }`

Actually this is already possible, it just wasn't documented in azurerm version 3.43. I updated the documentation here https://github.com/hashicorp/terraform-provider-azurerm/pull/20411

**Comment by Ivan-L** [comment]
We're in the same boat.

It would be great to be able to do this as this option was available to us when we used `azapi`.
```terraform
registry {
  server   = "<private_registry>.azurecr.io"
  identity = data.azurerm_user_assigned_identity.container_app.id
}
```

It is great that @audunsolemdal updated the docs with respect to being able to set a managed identity on a container app.

The core issue however remains that we cannot use managed identity with container apps to pull images from a private registry with the current `azurerm` version (3.43.0).

**Comment by jsok** [comment]
I took a stab at adding support for this in https://github.com/hashicorp/terraform-provider-azurerm/pull/20466
