### ISSUE TITLE
Support for public network access setting in App Services

### ISSUE THREAD

**Issue by Ikriva** [hashicorp/terraform-provider-azurerm#20415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure function apps and app services have flag for public network access. The corresponding resources should support this flag. Now you can create access restrictions, but you have no control if the rules even get evaluated as the public network access flag can disable all connections.

The property is supported in web apps [rest api](https://learn.microsoft.com/en-us/rest/api/appservice/web-apps/create-or-update-configuration) `properties.publicNetworkAccess`

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app, azurerm_linux_web_app, azurerm_linux_function_app, azurerm_windows_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_windows_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id
  
  # New flag to set public network access
  public_network_access_enabled = true

  site_config {}
}
```

**Comment by xiaxyi** [comment]
Thanks @Ikriva for raising this issue. 

The enhancement is included in pr:https://github.com/hashicorp/terraform-provider-azurerm/pull/20350.
