### ISSUE TITLE
azurerm_container_app - Unable to create new containerapps using private registries

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-azurerm#20422]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.8

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_container_app" "aca" {
  name                         = "myapp"
  container_app_environment_id = azurerm_container_app_environment.aca_env.id
  resource_group_name          = azurerm_resource_group.k8s.name
  revision_mode                = "Single"

  registry {
    server               = "myregistry.azurecr.io"
    username             = "myclientid"
    password_secret_name = "clientsecret"
   }

  secret {
    name  = "clientsecret"
    value = "myclientsecret"
  }

  template {
    container {
      name  = "main"
      image = "myregistry.azurecr.io:latest"
   }
}
}
```

### Debug Output/Panic Output

```shell
Via terraform apply:

│ Container App Name: "myapp"): polling after
│ CreateOrUpdate: Code="ContainerAppOperationError" Message="Failed to
│ provision revision for container app 'myapp'.
│ Error details: Operation expired."


Trying to create revision in portal:

Failed to deploy new revision: PasswordSecretRef 'clientsecret' defined for registry server 'myregistry.azurecr.io' not found.
```

### Expected Behaviour

Reference secrets from the container registry should be in place before attempting to create a revision.

### Actual Behaviour

My secret is not provisioned through Terraform. I am not sure if this happens regardless of pulling a public container image or not. I get the impression that when creating a new containerapp, it tries pulling the container image from the private registry before the required secret `clientsecret` is added to the containerapp.

### Steps to Reproduce

`terraform apply`

**Comment by xiaxyi** [comment]
Thanks @audunsolemdal for raising this issue, it seems a service behavior. Was there any succesful attempts before?

**Comment by audunsolemdal** [comment]
No attempts were successful for me.

**Comment by franciscojf** [comment]
I am getting the same issue trying to to create a new container app using a private ACR (in a different subscription). When I run terraform apply I get the following error: 
![image](https://user-images.githubusercontent.com/6495073/219789272-86981398-63bf-4f93-824a-89d6c332cf9a.png)


This will create the app but it fails creating the revision. When I go to the portal an try to create the revision manually it gives me the same error. If I delete the app and create it from scratch via the CLI or portal it works perfectly.

**Comment by audunsolemdal** [comment]
> I am getting the same issue trying to to create a new container app using a private ACR (in a different subscription). When I run terraform apply I get the following error: ![image](https://user-images.githubusercontent.com/6495073/219789272-86981398-63bf-4f93-824a-89d6c332cf9a.png)
> 
> This will create the app but it fails creating the revision. When I go to the portal an try to create the revision manually it gives me the same error. If I delete the app and create it from scratch via the CLI or portal it works perfectly.

my registry is also in another subscription, perhaps this causes the issue

**Comment by mateusparente** [comment]
@audunsolemdal try to add `latest_revision = true`. It worked for me.
```
traffic_weight {
      latest_revision = true
      percentage = 100
}
```

**Comment by jdubois** [comment]
If this the same issue as @mateusparente then have a look at #20435

I have a fully working version available at:

https://github.com/jdubois/NubesGen-2/blob/container-apps-support/rest-server/src/test/resources/nubesgen/terraform/aca-spring/terraform/modules/container-apps/main.tf

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of the suggestion of `latest_revision = true `in the `ingress` block making it work. As such, I am going to mark this issue as closed.
