### ISSUE TITLE
azurerm_key_vault_secrets support for Enabled/Disabled state

### ISSUE THREAD

**Issue by mpalermo73** [hashicorp/terraform-provider-azurerm#20459]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There was a time that the Azure API did not allow for seeing the state of a secret.  This appears to no longer be the case.  I have a secret that I disabled in KV for example here

Note:
"enabled: false"

```
-> % az keyvault secret list --vault-name my-key-vault
[
  {
    "attributes": {
      "created": "2023-02-14T15:56:32+00:00",
      "enabled": false,
      "expires": null,
      "notBefore": null,
      "recoveryLevel": "CustomizedRecoverable+Purgeable",
      "updated": "2023-02-14T16:07:05+00:00"
    },
    "contentType": "true",
    "id": "https://my-key-vault.vault.azure.net/secrets/my-secret",
    "managed": null,
    "name": "my-secret",
    "tags": {}
  }
]
```

It clearly shows that this secret is disabled.  When I try and list KV secrets with the existing terraform data source [azurerm_key_vault_secrets](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secrets#example-usage), I get the (known) error:

> Error: making Read request on Azure KeyVault Secret my-secret: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Operation get is not allowed on a disabled secret." InnerError={"code":"SecretDisabled"}

this is the raw `output` from `azurerm_key_vault_secrets`:
```
{
  "address": "data.azurerm_key_vault_secrets.my_key_vault",
  "mode": "data",
  "type": "azurerm_key_vault_secrets",
  "name": "my_key_vault",
  "provider_name": "registry.terraform.io/hashicorp/azurerm",
  "schema_version": 0,
  "values": {
    "id": "/subscriptions/1a2b3c4d-1a2b-1a2b-9c2e-1a2b3c4d5e6f/resourceGroups/my-resource-group/providers/Microsoft.KeyVault/vaults/my-key-vault",
    "key_vault_id": "/subscriptions/1a2b3c4d-1a2b-1a2b-9c2e-1a2b3c4d5e6f/resourceGroups/my-resource-group/providers/Microsoft.KeyVault/vaults/my-key-vault",
    "names": [
      "my-secret"
    ],
    "timeouts": null
  }
},
```

which provides pretty much everything the azure-cli _except_ the state.

---

Why am I unable to simply read the `enabled` key when it is clearly being returned from the API without error?

### New or Affected Resource(s)/Data Source(s)

3.43.0

### References

- azurerm_key_vault_secrets
  - https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secrets#example-usage

**Comment by StefanSchoof** [comment]
Related https://github.com/hashicorp/terraform-provider-azurerm/issues/20136
