### ISSUE TITLE
Rename AKS sku_tier

### ISSUE THREAD

**Issue by sinacek** [hashicorp/terraform-provider-azurerm#20455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Rename SKU Tier `Paid` to `Standard`. More information on https://learn.microsoft.com/en-us/azure/aks/free-standard-pricing-tiers#uptime-sla

Reference to attribute: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#sku_tier

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by marcindulak** [comment]
Anybody trying to use this feature be aware of https://github.com/Azure/AKS/issues/3481
