### ISSUE TITLE
azurerm_security_center_auto_provisioning does not disable for ARC enabled computers

### ISSUE THREAD

**Issue by ChristianLloydGrannes** [hashicorp/terraform-provider-azurerm#20475]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.8

### AzureRM Provider Version

3.42.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_auto_provisioning

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_auto_provisioning" "security_center_auto_provisioning" {
  auto_provision = "Off"   #var.security_center_auto_provisioning # Off or On
}
```

### Debug Output/Panic Output

```shell
The code executes with no error but not all components are disabled
```

### Expected Behaviour

I expect all Log Analytics Autoprovisioning to be disabled. Not Just for Azure virtual Machines.
The Arc machines remains enabled
<img width="842" alt="image" src="https://user-images.githubusercontent.com/74256454/219027868-1523f4de-9207-4767-953e-359a397b5c78.png">

### Actual Behaviour

Ony Azure Vorual Machines are disabled

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. After checked, seems service API only supports VM for now. Once service API supports Arc VM or if you happen to know the related doc or rest api for this feature, please share us the link and we would take another look. Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
