### ISSUE TITLE
code_configuration block not recognised

### ISSUE THREAD

**Issue by T3ssTing** [hashicorp/terraform-provider-azurerm#20477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

2.203.0

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_source_control

### Terraform Configuration Files

```hcl
required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.43.0"
    }

resource "azurerm_app_service_source_control" "sourcecontrol" {
  app_id             = azurerm_linux_web_app.webapp.id
  repo_url           = "https://github.com/Azure-Samples/nodejs-docs-hello-world"
  branch             = "master"
  use_manual_integration = true
  use_mercurial      = false
    
code_configuration {}
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported block type
│ 
│   on AppService.tf line 48, in resource "azurerm_app_service_source_control" "sourcecontrol":
│   48:   code_configuration {}
│ 
│ Blocks of type "code_configuration" are not expected here.
╵
```

**Comment by xiaxyi** [comment]
Thanks @T3ssTing for raisng this issue, the `code_configuration`  block is supposed to be defined in `github_action_configuration` like:
```

 github_action_configuration {
    generate_workflow_file = true

    code_configuration {
      runtime_stack   = "dotnetcore"
      runtime_version = "5.0.x"
    }
  }
```

can you try it?

**Comment by xiaxyi** [comment]
Hi @T3ssTing , may I know if you tried the suggestion mentioned above?
