### ISSUE TITLE
Lack of documentation for event hub namespace network rule sets 

### ISSUE THREAD

**Issue by vamshisiram** [hashicorp/terraform-provider-azurerm#20470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.8

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

Azurerm_eventhub_namespace

### Terraform Configuration Files

```hcl
How to add the network rulesets block?

Is it a set of rules or single set?

We want to allow access to multiple vnets, and multiple IPs. How do we do this?

The lack of documentation and examples on this is confusing and unable to add network rulesets.
```

### Debug Output/Panic Output

```shell
How to add the network rulesets block?

Is it a set of rules or single set?

We want to allow access to multiple vnets, and multiple IPs. How do we do this?

The lack of documentation and examples on this is confusing and unable to add network rulesets.
```

### Expected Behaviour

How to add the network rulesets block?

Is it a set of rules or single set?

We want to allow access to multiple vnets, and multiple IPs. How do we do this?

The lack of documentation and examples on this is confusing and unable to add network rulesets.

### Actual Behaviour

How to add the network rulesets block?

Is it a set of rules or single set?

We want to allow access to multiple vnets, and multiple IPs. How do we do this?

The lack of documentation and examples on this is confusing and unable to add network rulesets.

### Steps to Reproduce

Create network rulesets to add multiples ips and virtual networks.

### References

Why can this not be made simple like storage account network rules section? It is simple in storage account, but it is complicated in event hub namespace, while the settings are same in azure portal for both.

resource "azurerm_storage_account" "example" {
  name                = "storageaccountname"
  resource_group_name = azurerm_resource_group.example.name

  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["100.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.example.id]
  }

  tags = {
    environment = "staging"
  }
}

**Comment by xiaxyi** [comment]
Thanks @vamshisiram for raising this issue, I'll check the code and take the corresponding actions, will update once confirmed.

**Comment by xiaxyi** [comment]
Hi @vamshisiram, the usage docs may not contain the detailed usage of every single property considering the length limits. We do provide the definition, for example, the `network_rulesets` has a maximum length of 1 block, if you want to add more `ip_rules` block, you can follow below example to define multiple `ip_rules`
```
resource "azurerm_eventhub_namespace" "test" {
  name                = "testeventhubnamespace"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"
  capacity            = "2"

  network_rulesets {
    default_action = "Deny"

    virtual_network_rule {
      subnet_id = azurerm_subnet.test.id
    }

    virtual_network_rule {
      subnet_id = azurerm_subnet.test2.id
    }

    ip_rule {
      ip_mask = "10.0.1.0/24"
    }

    ip_rule {
      ip_mask = "10.1.1.0/24"
    }
  }
}
```

**Comment by vamshisiram** [comment]
I understand that but this particular instance is confusing due the format. So, having example on such things would help consumers of this resource.

**Comment by xiaxyi** [comment]
@vamshisiram I'll add example under example folder but I may not consider change the eventhub namespace usage. hope you can understand.
