### ISSUE TITLE
azurerm_redis_cache  no patch schedules found for redis cache

### ISSUE THREAD

**Issue by jhernandez-vendavo** [hashicorp/terraform-provider-azurerm#20489]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

v3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
data "azurerm_redis_cache" "rediscache" {
  name                = "RedisTestInstance"
  resource_group_name = "OrgXXX"
}
```

### Debug Output/Panic Output

```shell
│ Error: obtaining patch schedules for Redi (Subscription: "6712b72e-9733-4fdf-958f-0a1dc2ee8149"
│ Resource Group Name: "OrgXXX"
│ Redis Name: "RedisTestInstance"): patchschedules.PatchSchedulesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="There are no patch schedules found for redis cache 'RedisTestInstance'.\r\nRequestID=6acd18d4-860X-4fXX-9378-XXXXXXX"
│
│   with module.main.data.azurerm_redis_cache.rediscache,
│   on ../../../module_cpq/datasources.tf line 26, in data "azurerm_redis_cache" "rediscache":
│   26: data "azurerm_redis_cache" "rediscache" {
```

### Expected Behaviour

Run Terraform Plan or Terraform Apply with no error warnings. 

### Actual Behaviour

 The error message indicates that there are no patch schedules found for the Redis cache 'RedisTestInstance', and the error code returned is "404-ResourceNotFound".

However, according to the provider documentation, the `patch_schedule` is optional. As a result, it's unclear why I am receiving this error, and it seems to contradict what the documentation suggests.

I'm able to resolve the issue by downgrading to azure provider version '3.42.0'

### Steps to Reproduce

terraform plan and terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/20313

**Comment by sinbai** [comment]
@jhernandez-vendavo thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/20516)has been submitted to fix it. Could you keep track of it for more updates?
