### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.94.0_x5 plugin crashed!

### ISSUE THREAD

**Issue by mvinit008** [hashicorp/terraform-provider-azurerm#20497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

>= 0.12

### AzureRM Provider Version

2.94.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_plan

### Terraform Configuration Files

```hcl
│    9: resource "azurerm_app_service_plan" "this" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
Error: The terraform-provider-azurerm_v2.94.0_x5 plugin crashed!
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

Terraform plan is returning expected output but while applying the changes it returned below error 

│    9: resource "azurerm_app_service_plan" "this" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
╷
Error: The terraform-provider-azurerm_v2.94.0_x5 plugin crashed!

### Actual Behaviour

Need your inputs to fix this error

**Comment by wuxu92** [comment]
Hi @mvinit008 could you please share the log of provider panic so we can dig out where the bug is? or could you please try with wth newest azurerm version like v3.42.0?

**Comment by mvinit008** [comment]
Hi @wuxu92 

please find the below logs of provider panic 


stack trace from the terraform-provider-azurerm_v2.94.0_x5 plugin:

panic: runtime error: index out of range [0] with length 0



github.com/hashicorp/terraform-provider-azurerm/internal/services/eventhub.resourceEventHubUpdate(0x0, {0x55cdca0, 0xc0001d6700})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/internal/services/eventhub/eventhub_resource.go:231 +0x645
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000955a40, {0x65bed98, 0xc001880580}, 0x24, {0x55cdca0, 0xc0001d6700})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:363 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000aba9a0, {0x65bed98, 0xc001880580}, 0xc0018885b0, 0xc001884600, {0x55cdca0, 0xc0001d6700})
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:475 +0x6ba
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001113248, {0x65bed98, 0xc001880580}, 0xc001fd4a00)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0000a9700, {0x65bee40, 0xc001fef020}, 0xc00104a1c0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0x5b125e0, 0xc0000a9700}, {0x65bee40, 0xc001fef020}, 0xc001831b00, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c4fc0, {0x660dac8, 0xc000339800}, 0xc0017acfc0, 0xc000fa30b0, 0xaba5b40, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0xc6f
google.golang.org/grpc.(*Server).handleStream(0xc0000c4fc0, {0x660dac8, 0xc000339800}, 0xc0017acfc0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x294

Error: The terraform-provider-azurerm_v2.94.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely

**Comment by wuxu92** [comment]
Hi @mvinit008 this issue looks like duplicated with #15898 and it has been fixed in  #15930 . could you please have a try with a new version of azurerm provider?

**Comment by mvinit008** [comment]
Hi @wuxu92 i tried with the latest version and used 3.42.0 but terraform validate itself got failed due to some dependencies 

and below is the configuration of provider.tf also with 2.94.0 terraform plan returns expected output and fail in terraform apply returning terraform plugin crash 




provider "azurerm" {
  features {}
  subscription_id            = ""
  tenant_id                  = ""
  skip_provider_registration = true
}

terraform {
  required_version = ">= 0.12"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.42.0"
    }
  }
  backend "azurerm" {

  }
}

**Comment by mvinit008** [comment]
Hi @wuxu92 
attached is the error i am getting when upgarded to latest version of azurerm provider 
[3.42.0_error.txt](https://github.com/hashicorp/terraform-provider-azurerm/files/10781574/3.42.0_error.txt)
