### ISSUE TITLE
data azurerm_linux_web_app is not handling virtual_network_subnet_id correctly

### ISSUE THREAD

**Issue by algompluecker** [hashicorp/terraform-provider-azurerm#20490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

data azurerm_linux_web_app, data azurerm_windows_web_app

### Terraform Configuration Files

```hcl
data "azurerm_linux_web_app" "example" {
  name                = "existing"
  resource_group_name = "existing"
}

output "id" {
  value = data.azurerm_linux_web_app.example.id
}
```

### Debug Output/Panic Output

```shell
Unable to provide a log, but I found the issue in the code (see Steps to Reproduce).
```

### Expected Behaviour

The property virtual_network_subnet_id should contain the subnet id.

### Actual Behaviour

The property virtual_network_subnet_id is an empty string.

### Steps to Reproduce

terraform plan

Looking at [linux_web_app_data_source.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/linux_web_app_data_source.go) and [windows_web_app_data_source.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/windows_web_app_data_source.go) the handling for VirtualNetworkSubnetID is missing.

It requires similar handling as in [linux_function_app_data_source.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appservice/linux_function_app_data_source.go)

			state.VirtualNetworkSubnetID = utils.NormalizeNilableString(functionApp.VirtualNetworkSubnetID)

**Comment by xiaxyi** [comment]
Thanks @algompluecker for raising this issue, i'll check the data source code and update later.

**Comment by algompluecker** [comment]
Thanks a lot @xiaxyi and @stephybun!
