### ISSUE TITLE
Upgrade to version 3.44.0 broke provider registration status

### ISSUE THREAD

**Issue by GBuchanon** [hashicorp/terraform-provider-azurerm#20514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.44.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.0"

  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidSubscriptionId" Message="The provided subscription identifier 'providers' is malformed or invalid."
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on 00_terraform.tf line 31, in provider "azurerm":
│   31: provider "azurerm" {
```

### Expected Behaviour

It should have worked

### Actual Behaviour

plan fails with error above

### Steps to Reproduce

terraform plan

**Comment by msnook** [comment]
I believe part of the issue might be with this line of code:
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/hashicorp/go-azure-sdk/sdk/environments/azure_gov.go#L15

Note the mis-spelling of `management` vs `manaagement`.

**Comment by tombuildsstuff** [comment]
hey @GBuchanon @msnook 

Thanks for opening this issue.

Apologies for these regressions, taking a look through here there appear to be two different issues here:

1. The Subscription ID isn't being pulled through in some cases - raised by @GBuchanon which @manicminer is looking into.
2. The Azure Government URI being incorrect - raised by @msnook, which I've opened https://github.com/hashicorp/go-azure-sdk/pull/316 to fix.

Once fixes are available for both of those, we'll look to ship those in a bug fix release (`v3.44.1`) later today / will post an update here when that's available - apologies again for the inconvenience here, in the interim you should be able to pin to last weeks release (`v3.43.0`).

Thanks!

**Comment by flmmartins** [comment]
We are seeing also something similar with the following error:

│ Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: auxiliary tokens are not supported with MSI authentication

**Comment by noushi** [comment]
Same here:
```
│ Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidSubscriptionId" Message="The provided subscription identifier 'providers' is malformed or invalid."
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 2, in provider "azurerm":
│    2: provider "azurerm" {
```

version pinning to `3.43.0` restores working behavior.

**Comment by benvbr** [comment]
Same issue here with using MSI authentication. Currently pinning to 3.43.0 fixes the issue.

**Comment by walkerk1980** [comment]
``` 
- Installing hashicorp/azurerm v3.44.1... [96](https://github.com/Oceaneering/it_infra_tf_enrg_informcore/actions/runs/4196319747/jobs/7297895125#step:12:97)- Installed hashicorp/azurerm v3.44.1 (signed by HashiCorp)
``` 
``` 
Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'Redacted' was not found in the directory 'Redacted'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: redacted\r\nCorrelation ID: redacted\r\nTimestamp: 2023-02-17 16:23:02Z","error_codes":[700016],"timestamp":"2023-02-17 

``` 

This is using OIDC trust from a github repo. The "Application Identifier" it shows in the error is our Tenant ID, not the ClientId/ApplicationId.

This does not happen when using older providers:

    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.41.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.32.0"
    }

**Comment by GBuchanon** [comment]
Thanks for the quick response and patch. Can confirm v3.44.1 works for me.
