### ISSUE TITLE
azurerm_frontdoor is being deprecated in 4.0, even though Azure Front Door (classic) isn't being deprecated.

### ISSUE THREAD

**Issue by GurliGebis** [hashicorp/terraform-provider-azurerm#20525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Taken directly from: https://azure.microsoft.com/en-us/blog/introducing-the-new-azure-front-door-reimagined-for-modern-apps-and-content/

> The existing Azure Front Door and Azure CDN from Microsoft will now be known as Azure Front Door (classic) and Azure CDN from Microsoft (classic) moving forward. **Azure Front Door (classic), as well as Azure CDN from Microsoft (classic), will continue to be fully supported and you can continue to use them**. However, we encourage you to take advantage of Azure Front Door Standard and Premium as the latest capabilities and future enhancements will not be available on Azure Front Door (classic).

So, can we please keep the classic resources, since there still are use cases where classic makes sense.

### New or Affected Resource(s)/Data Source(s)

azurerm_frontdoor

**Comment by GurliGebis** [comment]
Also, just because they have added a migration tool doesn't mean the old one is going away (Please correct me if I'm wrong, and point me to official documentation etc. mentioning it being deprecated)

**Comment by GurliGebis** [comment]
One of the use cases is wanting to use a WAF with managed rulesets, without having to pay $300+ each month.

**Comment by GurliGebis** [comment]
@katbyte where does Microsoft mention Azure Front Door Classic being deprecated?
I have been looking for a long time now, and I haven't been able to find anything mentioning it being deprecated, just that you now can migrate it.
If there is none, please reopen this and fix it, so it isn't being removed, since, like I mentioned above, there are still workloads where Classic is the SKU that makes the most sense.

**Comment by WodansSon** [comment]
> @katbyte where does Microsoft mention Azure Front Door Classic being deprecated? I have been looking for a long time now, and I haven't been able to find anything mentioning it being deprecated, just that you now can migrate it. If there is none, please reopen this and fix it, so it isn't being removed, since, like I mentioned above, there are still workloads where Classic is the SKU that makes the most sense.

Hi @GurliGebis, the Front Door Classic resources in the Terraform provider are deprecated at this point. By deprecated, that means that there will be no engineering effort to fix bugs outside of security and framework issues for these resources. @katbyte was correct in approving the message change to the documentation stating that they are deprecated, but are no longer going to be removed in the v4.0 of the provider.

**Comment by GurliGebis** [comment]
> Hi @GurliGebis, the Front Door Classic resources in the Terraform provider are deprecated at this point. By deprecated, that means that there will be no engineering effort to fix bugs outside of security and framework issues for these resources. @katbyte was correct in approving the message change to the documentation stating that they are deprecated, but are no longer going to be removed in the v4.0 of the provider.

Thanks for elaborating.
