### ISSUE TITLE
Application configuration was highlighted as not found even though it exists.

### ISSUE THREAD

**Issue by jvlingam** [hashicorp/terraform-provider-azurerm#20529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.44.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_app_configuration" "appconf" {
  name                = "appConf1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}
resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.appconf.id
  key                    = "appConfKey1"
  label                  = "somelabel"
  value                  = "a test"

  depends_on = [
    azurerm_role_assignment.appconf_dataowner
  ]
}
```

### Debug Output/Panic Output

```shell
Error: app configuration "/subscriptions/*************************/resourceGroups/example-resources/providers/Microsoft.AppConfiguration/configurationStores/appConf1" was not found

While creating the azurerm_app_configuration_key.
```

### Expected Behaviour

azurerm_app_configuration_key should be created without any issues.

### Actual Behaviour

Error: app configuration "/subscriptions/*************************/resourceGroups/example-resources/providers/Microsoft.AppConfiguration/configurationStores/appConf1" was not found

So, I had to revert to the previous provider 3.43.0 and it worked as expected.

**Comment by tombuildsstuff** [comment]
hey @jvlingam 

Thanks for opening this issue.

Taking a look through here unfortunately this appears to be a regression - I've opened #20533 (which has since been merged) which includes a fix for this - and will ship in a patch release (`v3.44.1`) - apologies for any inconvenience caused, but you should be able to pin to last weeks release (`v3.43.0`) in the interim.

Thanks!

**Comment by jvlingam** [comment]
Hi @tombuildsstuff 

Thanks for the immediate response and support. Appreciate it.
