### ISSUE TITLE
Support for route table name when creating aks with outbound network profile as loadbalancer

### ISSUE THREAD

**Issue by jozephp** [hashicorp/terraform-provider-azurerm#20528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If there is a need to add any additional routes in the route table used by an AKS which is created with _outbound_type_ as loadbalancer, its not currently possible since there is no reference to the route table name returned by the azurerm_kubernetes_cluster  module.

Ask here is to output the route table name from **azurerm_kubernetes_cluster** module, when we create aks with _network_profile_ of _outbound_type_ as loadbalancer 

Please let us know if more information is needed.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#network_policy

**Comment by sinbai** [comment]
@jozephp thanks for opening this issue. The implementation of terraform provider depends on the Azure rest API. [Here ](https://github.com/Azure/azure-rest-api-specs/blob/45b820410edf6ccd3f3f75cbe3b383b9adbb39d5/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-01-01/managedClusters.json#L3945)is the latest Azure rest API used by `azurerm_kubernetes_cluster`.  Unfortunately, it seems that  route table name is not supported by the API, so terraform could not do anything with the request. If you find an API that supports it, please feel free to let us know, thank you.

**Comment by jozephp** [comment]
Thanks @sinbai for the suggestion I have raised a feature request with Azure rest API https://github.com/Azure/azure-rest-api-specs/issues/22710

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
