### ISSUE TITLE
Add zone_redundant property to the azurerm_container_app_environment resource

### ISSUE THREAD

**Issue by paolosalvatori** [hashicorp/terraform-provider-azurerm#20538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `azurerm_container_app_environment` resource misses some essential properties like `runtime_subnet_id` and `zone_redundant`

- `runtime_subnet_id` : Resource ID of a subnet that Container App containers are injected into. This subnet must be in the same VNET as the subnet defined in infrastructureSubnetId. Must not overlap with any other provided IP ranges.
- `zone_redundant`: Whether or not this Managed Environment is zone-redundant.

For more information, see [Microsoft.App/managedEnvironment](https://learn.microsoft.com/en-us/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-terraform)

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app_environment 

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app_environment" "managed_environment" {
  name                                         = var.managed_environment_name
  location                                     = var.location
  resource_group_name               = var.resource_group_name
  log_analytics_workspace_id       = var.workspace_id
  infrastructure_subnet_id            = var.infrastructure_subnet_id
  runtime_subnet_id                     = var.runtime_subnet_id
  zone_redundant                         = true
  internal_load_balancer_enabled = var.internal_load_balancer_enabled
  tags                           = var.tags
  
  lifecycle {
    ignore_changes = [
        tags
    ]
  }
}
```

**Comment by darrencrossley** [comment]
It was suggested `runtime_subnet_id` is deprecated as per: https://github.com/microsoft/azure-container-apps/issues/374 Maybe worth checking what's going on there (not a Microsoft employee though!)

**Comment by paolosalvatori** [comment]
> It was suggested `runtime_subnet_id` is deprecated as per: https://github.com/microsoft/azure-container-apps/issues/374 Maybe worth checking what's going on there (not a Microsoft employee though!)

After filing this issue, I tried to deploy a Container App Environment with Bicep using the latest release of the resource provider and I get an error saying that runtimeSubnetId is not supported. I'll double-check with the product group.

**Comment by chriswangelin** [comment]
@paolosalvatori - Is it possible to raise visibility/priority on adding `zone_redundant` - perhaps by opening a separate issue or retitiling this one?  I'm a little concerned about `zone_redundant` getting lost in the chatter about the deprecated (?) `runtime_subnet_id` property.   Many thanks for opening this issue!

**Comment by paolosalvatori** [comment]
> @paolosalvatori - Is it possible to raise visibility/priority on adding `zone_redundant` - perhaps by opening a separate issue or retitiling this one? I'm a little concerned about `zone_redundant` getting lost in the chatter about the deprecated (?) `runtime_subnet_id` property. Many thanks for opening this issue!

Done, changed the title of this issue. I may also create a PR to implement this feature.

**Comment by pete-xlab** [comment]
Hey @paolosalvatori, any news on adding `zone_redundant`?

**Comment by paolosalvatori** [comment]
@pete-xlab I'll be OOF next week, can you please send me a reminder or ping me here on the 26th? Thanks!

**Comment by benj-ch** [comment]
Hi @paolosalvatori, have you had time to look at this issue?

**Comment by daniel-martinez-deltatre** [comment]
Hi! any updates on this topic?
