### ISSUE TITLE
Enable ability to apply azurerm_mssql_server TDE using a CMK at time of server deployment

### ISSUE THREAD

**Issue by win-admin-85** [hashicorp/terraform-provider-azurerm#20549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When trying to deploy a MSSQL Server via azurerm_mssql_server and you have Azure policies in place to require a customer-managed key for TDE Terraform currently fails to deploy.  It appears that Terraform will first deploy the SQL server resource in order to get the server_id as required by azurerm_mssql_server_transparent_data_encryption.  However, due to the policy in place, this is denied since the policy is looking for the KeyID on the SQL Server resource which does not exist yet.  It would be great to move this action within the azurerm_mssql_server resource.  If there is a way to do this now please let me know.  Thanks!

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_server" "demo" {
  name        = "demo"
  location    = "eastus"
  version     = "12.0"
  resource_group_name   = "rg-demo"
  azurerm_mssql_server_transparent_data_encryption {
    key_vault_key_id = azurerm_key_vault_key.tde_key.id
  }
  minimum_tls_version = "1.2"
  public_network_access_enabled = "false"
  outbound_network_restriction_enabled = "true"
  primary_user_assigned_identity_id = azurerm_user_assigned_identity.identity.id
  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.identity.id]
  }  
}
```

### References

https://github.com/Azure/azure-policy/blob/master/built-in-policies/policyDefinitions/SQL/SqlServer_EnsureServerTDEisEncryptedWithYourOwnKey_Deny.json

**Comment by sinbai** [comment]
@win-admin-85 thanks for opening this issue. Could you refer to the following example to see if it is what you need?
```

provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
	  version = "3.43.0"
    }
  }
}


data "azurerm_client_config" "current" {}


resource "azurerm_resource_group" "test" {
  name     = "mssql-0220"
  location = "eastus"
}

resource "azurerm_user_assigned_identity" "test" {
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  name                = "test_identity"
}


resource "azurerm_mssql_server" "test" {
  name                         = "acctestsqlserver0220"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "missadministrator"
  administrator_login_password = "thisIsKat11"
  minimum_tls_version          = "1.2"

  public_network_access_enabled = "false"
  outbound_network_restriction_enabled = "true"
  
  primary_user_assigned_identity_id = azurerm_user_assigned_identity.test.id

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.test.id]
  }
}


resource "azurerm_key_vault" "test" {
  name                        = "acctestsqlserver02202"
  location                    = azurerm_resource_group.test.location
  resource_group_name         = azurerm_resource_group.test.name
  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false

  sku_name = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Get", "List", "Create", "Delete", "Update", "Purge",
    ]
  }

  access_policy {
    tenant_id = azurerm_user_assigned_identity.test.tenant_id
    object_id = azurerm_user_assigned_identity.test.principal_id

    key_permissions = [
      "Get", "WrapKey", "UnwrapKey", "List", "Create",
    ]
  }
}

resource "azurerm_key_vault_key" "generated" {
  name         = "keyVault"
  key_vault_id = azurerm_key_vault.test.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]

  depends_on = [
    azurerm_key_vault.test,
  ]
}


resource "azurerm_mssql_server_transparent_data_encryption" "test" {
  server_id        = azurerm_mssql_server.test.id
  key_vault_key_id = azurerm_key_vault_key.generated.id
}
```

**Comment by sinbai** [comment]
@win-admin-85 since the example above works fine on my test subscription, I assume that it might have something to do with the permission of the subscription. Could you share the detailed error for me to try and see if I could find anything that might help you?

**Comment by sinbai** [comment]
@win-admin-85 After setting the "SQL servers should use customer-managed keys to encrypt data at rest" azure policy to `Deny`, I got `RequestDisallowedByPolicy` error. If changed the policy to `Disabled` or `Audit` , it works fine on my side. 

Set to Deny, causing creation of  SQL server using customer-managed keys to encrypt data to fail, which I understand is by design. The implementation of terraform depends on the Azure API, `azurerm_mssql_server_transparent_data_encryption` requires the id of `azurerm_mssql_server` depends on API not terraform. So Terraform could not do anything since the error is returned by API. 

To solve this case, is it possible to disable the policy before creation and then enable it?

**Comment by bxokywsfgqurhkat** [comment]
I can confirm that we have the same issue @win-admin-85.

**Comment by lonegunmanb** [comment]
Hi @win-admin-85, is that possible to create the resources by tools other than Terraform, like portal or azcli?

**Comment by WodansSon** [comment]
@win-admin-85, thanks for opening this issue. I have looked into this and it appears what needs to happen to pass the policy check you need to pass the `key_id`(_currently not exposed_) property at the time of server creation, the actual TDE part already exist behind the scenes and just needs to be told how to get the key to use from the server. In order to do that you must use a `user assigned identity` and grant the `key vault` permissions to the key with the `user assigned identity`. I am currently working on a PR that will enable this scenario. 🚀

**Comment by WodansSon** [comment]
@win-admin-85, It appears that my PR fixes the issue you are hitting, please feel free to build your own private of my linked PR and give it a go in one of your test environments...

```
=== RUN   TestAccMsSqlServer_dteByokAtServerDeployment
=== PAUSE TestAccMsSqlServer_dteByokAtServerDeployment
=== CONT  TestAccMsSqlServer_dteByokAtServerDeployment
--- PASS: TestAccMsSqlServer_dteByokAtServerDeployment (566.23s)
PASS
```

I have included and `example configuration` for your scenario in the new documentation... 🚀
