### ISSUE TITLE
Support for setting Node communication mode on azurerm_batch_pool

### ISSUE THREAD

**Issue by chris-holguin** [hashicorp/terraform-provider-azurerm#20553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

MS are removing support for Batch Pools configured using NoPublicIPAddresses, and as an alternative solution require users to migrate to Batch Pools configured with "Node Communication Mode" set to Simplified. 

Related Links
- https://learn.microsoft.com/en-us/azure/batch/simplified-node-communication-pool-no-public-ip
- https://learn.microsoft.com/en-us/azure/batch/batch-pools-without-public-ip-addresses-classic-retirement-migration-guide

At UBS we are looking to perform this migration, but the Node Communication Mode is not available to set on azurerm_batch_pool. 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/batch_pool

### New or Affected Resource(s)/Data Source(s)

azurerm_batch_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_batch_pool" "example" {
  name                = "rates_options"
  resource_group_name = azurerm_resource_group.example.name
  account_name        = azurerm_batch_account.example.name
  display_name        = "Rates Options EOD Risk"
  vm_size             = "Standard_A1"
  node_agent_sku_id   = "batch.node.ubuntu 20.04"

  target_node_communication_mode = "Simplified"
..
}
```

**Comment by liuwuliuyun** [comment]
Hi @chris-holguin, thanks for raising this issue. You could try https://registry.terraform.io/providers/Azure/azapi/latest with to get access to this property right away.

To anyone interested in contributing to this topic, this property is supported in the lastest API version. Need to switch to pandora sdk first, then upgrade sdk version and add this property.
