### ISSUE TITLE
allow_blob_public_access isn't documented on azurerm_storage_account

### ISSUE THREAD

**Issue by andrecp** [hashicorp/terraform-provider-azurerm#20551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

2.46.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account, it's a documentation issue, no `allow_blob_public_access` parameter
```

### Debug Output/Panic Output

```shell
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account, it's a documentation issue, no `allow_blob_public_access` parameter
```

### Expected Behaviour

have the property documented

### Steps to Reproduce

read the web page

**Comment by StefanSchoof** [comment]
You look at the docs of the latest version, but use a very old version. Try https://registry.terraform.io/providers/hashicorp/azurerm/2.46.0/docs/resources/storage_account

**Comment by mybayern1974** [comment]
Thank you @andrecp for opening this issue, per what StefanSchoof explained, given the [doc ](https://registry.terraform.io/providers/hashicorp/azurerm/2.46.0/docs/resources/storage_account#allow_blob_public_access)for `allow_blob_public_access` does exist in AzureRM v2.46.0 , and in the latest AzureRM v3.44.0 that property does not exist anymore (I wonder whether it's replaced by [public_network_access_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#public_network_access_enabled)? ), I'm closing this issue. Feel free to suggest to re-activate this issue if you believe this explanation does not address your ask.
