### ISSUE TITLE
Incorrect documentation for data app_service, should be app_service_plan!

### ISSUE THREAD

**Issue by thenecroscope** [hashicorp/terraform-provider-azurerm#20557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The documentation here is incorrect:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/app_service

the data source should be app_service_plan and NOT app_service!

Please update many thanks,

### Terraform Version

all

### AzureRM Provider Version

3+

### Affected Resource(s)/Data Source(s)

App_Service

### Terraform Configuration Files

```hcl
.
```

### Debug Output/Panic Output

```shell
.
```

**Comment by mybayern1974** [comment]
@thenecroscope thank you for opening this issue. Though I'm not expert in the app service domain, per pure resource naming, the data source `azurerm_app_service_plan` ([link](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/app_service_plan)) does exist. Is it possible this is what you were pointing at and `azurerm_app_service` is a separated data source that's on purpose different from `azurerm_app_service_plan`?

**Comment by thenecroscope** [comment]
Yes you're complete correct, I need glasses :)
Thanks very much for responding!
