### ISSUE TITLE
Support for setting azure data explorer cmk provider to auto key rotation (no key version)

### ISSUE THREAD

**Issue by christiansalathe-art** [hashicorp/terraform-provider-azurerm#20569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider **azurerm_kusto_cluster_customer_managed_key** doesn't support to set the key without a version. No version on the azure api side would mean to take always the latest version and with that you can set the key vault auto rotation for these keys. Azure Kusto Cluster is supporting auto key rotation.

### New or Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster_customer_managed_key

### Potential Terraform Configuration

```hcl
resource "azurerm_kusto_cluster_customer_managed_key" "cmk-key" {
  cluster_id         = azurerm_kusto_cluster.dataexplorer.id
  key_vault_id       = data.azurerm_resources.key_vault_dec.resources[0].id
  key_name           = "key-${azurerm_kusto_cluster.dataexplorer.name}"
  key_version        = null # if key version ist null, pass a empty strung to azure api
```

**Comment by liuwuliuyun** [comment]
Hi @christiansalathe-art, thanks for raising this issue. I think we could work this out by modifying the `azurerm_kusto_cluster_customer_managed_key` resource. And I will work on the code update.
