### ISSUE TITLE
Support for enabling AD authentication on postgresql_flexible_server_resource without password authentication

### ISSUE THREAD

**Issue by lunalite** [hashicorp/terraform-provider-azurerm#20561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From Azure Portal, it is possible to select Azure AD authentication only without having to specify any local administrator username and password. Instead, we are able to set an admin using Azure AD.

![image](https://user-images.githubusercontent.com/14029092/220015470-fc6081cd-2876-4346-a9e1-8092c505b858.png)

The current behavior from [https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/postgres/postgresql_flexible_server_resource.go#L435](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/postgres/postgresql_flexible_server_resource.go#L435) hides the possibility of creating a postgresql flexible server without having to go through the process of enabling password authentication before disabling it and that is currently causing some issues.

We are currently looking to enable AD authentication without ever having to enable password authentication.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

**Comment by ziyeqf** [comment]
Hi @lunalite, thanks for reporting.

opened a PR (#20578) for this to allow create without enabling password authentication.

For any further question please leave comments.
Thanks.
