### ISSUE TITLE
Support for setting Microsoft.Web/sites/basicPublishingCredentialsPolicies

### ISSUE THREAD

**Issue by guidojw** [hashicorp/terraform-provider-azurerm#20572]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to be able to disable ftp/scm authentication to my function app using azurerm, it doesn't look like this is supported currently.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app, azurerm_windows_web_app_slot, azurerm_linux_web_app, azurerm_linux_web_app_slot, azurerm_windows_function_app, azurerm_windows_function_app_slot, azurerm_linux_function_app, azurerm_linux_function_app_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "resource_name" {
  ...
  ftp_local_auth_disabled = true
  scm_local_auth_disabled = true
}
```

### References

* https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/basicpublishingcredentialspolicies-ftp
* https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites/basicpublishingcredentialspolicies-scm

**Comment by xiaxyi** [comment]
Thanks @guidojw for raising this issue, I added it to the enhancement list, will update once there is a progress.

**Comment by xiaxyi** [comment]
This is blocked by api issue:https://github.com/Azure/azure-rest-api-specs/issues/22714. Once the api issue is addressed, I will continue with Terraform support for this feature.

**Comment by guidojw** [comment]
Thanks for the quick response! I'm just starting with Terraform and azurerm so the example configuration I thought of may not actually be very logical 🙏🏻

**Comment by xiaxyi** [comment]
@guidojw no problems, let's keep monitor the fix from the api side.

**Comment by byteknacker** [comment]
Thank you for clarifying this issue. We also face the same problem. Right now, we can only use this documentation and the az cli command in a script to manipulate the FTP local auth setting. Also watching this issue closely.  https://azure.github.io/AppService/2020/08/10/securing-data-plane-access.html

**Comment by mharris4-eqr** [comment]
We are having the same issue

**Comment by danielguo72** [comment]
Is there any update on this issue? Has it been put onto the backlog or some sort? It's a missing feature definitely

**Comment by DucVanNgo** [comment]
Any update on this issue?

**Comment by guidojw** [comment]
Looks like this was added in https://github.com/hashicorp/terraform-provider-azurerm/pull/23900
