### ISSUE TITLE
Updating azurerm_iothub_dps fails

### ISSUE THREAD

**Issue by lukipro** [hashicorp/terraform-provider-azurerm#20587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_iothub_dps

### Terraform Configuration Files

```hcl
resource "azurerm_iothub_dps" "dps" {
  name                = "provs-${module.common.resource_suffix}"
  resource_group_name = module.common.resource_group_name
  location            = var.azure_region
  linked_hub {
    location                = azurerm_iothub.iothub.location
    connection_string       = data.azurerm_iothub_shared_access_policy.iothubowner.primary_connection_string
    apply_allocation_policy = true
  }

  sku {
    name     = var.dps_sku
    capacity = var.dps_capacity
  }

  tags = module.common.tags
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating/updating IoT Device Provisioning Service Provisioning Service (Subscription: "xxxxxxxxxxxxxxxxx"
│ Resource Group Name: "rg-platform-prd-westeurope"
│ Provisioning Service Name: "provs-platform-prd-westeurope"): performing CreateOrUpdate: iotdpsresource.IotDpsResourceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="Failed" Message="The async operation failed." InnerError={"unmarshalError":"json: cannot unmarshal number into Go struct field serviceErrorInternal.code of type string"} AdditionalInfo=[{"code":400303,"httpStatusCode":"BadRequest","message":"The EnableDataResidency property may not be updated after initial IotDps creation. If you contact a support representative please include this correlation identifier: 48380527-ece0-4efd-a7ff-6a91929543f7, timestamp: 2023-02-20 13:21:15Z, errorcode: IH400303."}]
│ 
│   with azurerm_iothub_dps.dps,
│   on iothub.tf line 113, in resource "azurerm_iothub_dps" "dps":
│  113: resource "azurerm_iothub_dps" "dps" {
│ 
╵
```

### Expected Behaviour

DPS gets updated.

### Actual Behaviour

Error is thrown.

### Steps to Reproduce

1. Create a DPS resource with Terraform.
2. Change a tag.
3. Try to run `terraform apply`.

**Comment by myc2h6o** [comment]
Hi @lukipro thanks for reporting this! It looks like a bug when adding the support for `data_residency_enabled` #18151, I'll add a fix soon.
