### ISSUE TITLE
Support for azurerm_subnet to be created with security group associated

### ISSUE THREAD

**Issue by rsun-thoughtworks** [hashicorp/terraform-provider-azurerm#20581]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Due to policy restriction in our Azure resource group, all subnets must have an security group associated to it.

When I try to create an azurerm_subnet and asssociate with azurerm_network_security_group, I always get rejected.

So, is it possible to associate a security group alone with the creation of an subnet?

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

**Comment by tombuildsstuff** [comment]
hi @rsun-thoughtworks 

Thanks for opening this issue.

At this point in time this can be achieved by defining subnets within the `azurerm_virtual_network` resource (using [the `security_group` field within the `subnet` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network#security_group)).

Whilst we've previously supported the `network_security_group_id` field within the `azurerm_subnet` resource, support for this has intentionally been removed in favour of the `azurerm_subnet_network_security_group_association` resource to workaround issues within the Azure API during the deletion of other resources (where the Azure Platform marks a resource as removed, however it's still kicking around in the backend, which causes cascading failures of other resources during deletion).

Should you need to define Subnets outside of the `azurerm_virtual_network` resource, then issue #9022 is tracking adding an example of how to use Azure Policy when using the `azurerm_subnet` and `azurerm_subnet_network_security_group_association` resources - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by rsun-thoughtworks** [comment]
Thanks.

For people who don't know how to resolve this issue:

1. Create subnet using dynamic block of terraform, this will help you build subnet.
2. Use azapi_resource to patch your other configuration that need to bind with subnet, refer to this stack-overflow answer: https://serverfault.com/a/1114275

**Comment by rsun-thoughtworks** [comment]
@tombuildsstuff Thanks again. For you details explanation, I could not be as patient as you were if I were at your position.
