### ISSUE TITLE
recurrence_period_start_date in azurerm_subscription_cost_management_export resource cannot be set to past

### ISSUE THREAD

**Issue by andredaube** [hashicorp/terraform-provider-azurerm#20597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_subscription_cost_management_export

### Terraform Configuration Files

```hcl
resource "azurerm_subscription_cost_management_export" "default" {
  name                         = "my-export"
  subscription_id              = "<sub_id>"
  recurrence_type              = "Daily"
  recurrence_period_start_date = "2023-02-01T00:00:00Z"
  recurrence_period_end_date   = "2050-02-01T00:00:00Z"

  export_data_storage_location {
    container_id     = "/subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.Storage/storageAccounts/<storage_account_name>/blobServices/default/containers/<container_name>"
    root_folder_path = "my-export-data"
  }

  export_data_options {
    type       = "AmortizedCost"
    time_frame = "MonthToDate"
  }
}
```

### Debug Output/Panic Output

```shell
$ terraform apply
azurerm_subscription_cost_management_export.default: Refreshing state... [id=/subscriptions/<sub_id>/providers/Microsoft.CostManagement/exports/my-export]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_subscription_cost_management_export.default will be updated in-place
  ~ resource "azurerm_subscription_cost_management_export" "default" {
        id                           = "/subscriptions/<sub_id>/providers/Microsoft.CostManagement/exports/my-export"
        name                         = "my-export"
      ~ recurrence_period_start_date = "2023-02-21T00:00:00Z" -> "2023-02-01T00:00:00Z"
        # (4 unchanged attributes hidden)


        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_subscription_cost_management_export.default: Modifying... [id=/subscriptions/<sub_id>/providers/Microsoft.CostManagement/exports/my-export]
╷
│ Error: updating Cost Management Export ID: (Cost Management Export Name "my-export" / Scope "/subscriptions/<sub_id>"): costmanagement.ExportsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Request properties validation failed: Invalid schedule recurrencePeriod; updated 'from' value cannot be in the past.\r\n (Request ID: <req_id>)"
│ 
│   with azurerm_subscription_cost_management_export.default,
│   on main.tf line 1, in resource "azurerm_subscription_cost_management_export" "default":
│   1: resource "azurerm_subscription_cost_management_export" "default" {
│ 
│ updating Cost Management Export ID: (Cost Management Export Name "my-export" / Scope "/subscriptions/<sub_id>"): costmanagement.ExportsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400
│ Code="400" Message="Request properties validation failed: Invalid schedule recurrencePeriod; updated 'from' value cannot be in the past.\r\n (Request ID: 448fdd8a-5145-4d61-a797-8979722bd4c1)"
╵
```

### Expected Behaviour

It should be possible to to set `recurrence_period_start_date` and `recurrence_period_end_date` to the past.

#### Why?

- To avoid having to bump the dates to the future each time a new apply has to be done.
- To avoid having to use a function like [timestamp](https://developer.hashicorp.com/terraform/language/functions/timestamp) which would result in a drift between code and infra on each apply

If Azure itself does not support this, the above fields should be optional and the provider should just take the value that's already set in Azure.

### Actual Behaviour

A `terraform apply` resulted in an error when setting `recurrence_period_start_date` to the past.

### Steps to Reproduce

`terraform apply` with above minimal TF configuration file.

### Important Factoids

We use the region "West Europe"

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_cost_management_export

**Comment by manicminer** [comment]
Thanks for reporting this issue @andredaube. Can you confirm whether you are trying to set the date in the past when creating the resource, or do you receive this error when updating an existing resource having the original start date?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant information asked for above. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill in all the requested information including whether you are trying to set the date in the past when creating the resource, or do you receive this error when updating an existing resource having the original start date so that we can try to reproduce the problem.
