### ISSUE TITLE
azure policy definitions stored in a subscription even if management group id is specified

### ISSUE THREAD

**Issue by secura-dschauland** [hashicorp/terraform-provider-azurerm#20615]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_policy_definition

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "apply_sub" {
  subscription_id = var.policy_subscription_id
}

data "azurerm_management_group" "mgmt_policy" {
  name = "mg-all-policy"
}

module "naming_resourceGroups" {
  source                     = "./naming_policy/resourceGroups"
  policy_name                = var.policy_name                                                  #"pol_rg_naming"
  policy_mode                = var.policy_mode                                                  #"all"
  policy_management_group_id = "/providers/Microsoft.Management/managementGroups/mg-all-policy" #anagement_group.mgmt_policy.parent_management_group_id
  policy_subscription_id     = data.azurerm_subscription.apply_sub.id                           #var.policy_subscription_id #"96d43cad-de7d-4a42-9939-119278764bf7"
}
```

### Debug Output/Panic Output

```shell
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Creating...
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [10s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [20s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [30s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [40s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [50s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m0s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m10s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m20s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m30s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m40s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m50s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [2m0s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Creation complete after 2m4s [id=/subscriptions/737#####-####-####-####-##########2c/providers/Microsoft.Authorization/policyDefinitions/rg-naming]
module.naming_resourceGroups.azurerm_subscription_policy_assignment.rg_naming_assign_sub: Creating...
```

### Expected Behaviour

The azure policy definition should be stored in the specified management group

### Actual Behaviour

The policy definition is being placed inside the currently selected subscription, even though the management group ID is specified from the data source used above. 

module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Creating...
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [10s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [20s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [30s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [40s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [50s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m0s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m10s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m20s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m30s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m40s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [1m50s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Still creating... [2m0s elapsed]
module.naming_resourceGroups.azurerm_policy_definition.naming_rg: Creation complete after 2m4s [id=/subscriptions/737#####-####-####-####-#########32c/providers/Microsoft.Authorization/policyDefinitions/rg-naming]
module.naming_resourceGroups.azurerm_subscription_policy_assignment.rg_naming_assign_sub: Creating...
╷
│ Error: creating Policy Assignment ID: (Assignment Name "pol-rg-naming" / Scope "/subscriptions/96d43cad-de7d-4a42-9939-119278764bf7"): policy.AssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidCreatePolicyAssignmentRequest" Message="The policy definition specified in policy assignment 'pol-rg-naming' is out of scope. Policy definitions should be specified only at or above the policy assignment scope."

### Steps to Reproduce

 terraform apply

### References

This issue https://github.com/hashicorp/terraform-provider-azurerm/issues/2195 appears to show that this is fixed, but when I supply the management group ID - it still gets defined in the current subscription and cannot be assigned.

**Comment by aristosvo** [comment]
Hi @secura-dschauland ! Can you provide the actual content of the module for reproducing the error? Thanks in advance!

**Comment by secura-dschauland** [comment]
Sure - the module content is below:
### varaiables
variable "policy_name" {
  default = ""
  type    = string
}

variable "policy_mode" {
  default = ""
  type    = string
}

variable "policy_management_group_id" {
  default = ""
  type    = string
}

variable "policy_subscription_id" {
  default = ""
  type    = string
}

variable "assignment" { #use snake case storage_account - checkmarx cares
  type = object({
    assignments = list(object({
      id   = string
      name = string
    }))
    scope = optional(string, "rg")
  })

  description = <<DESC
  (Required) assignment details for the policy.
  Properties:
  `assignments` (Required) - list of assignments
  `id` (Required) - resource ID
  `name` (Required) - friendly name/reference for the assignment
  `scope` (Optional) - resource scope for the assignment [Default: `rg`]

  DESC

  validation {
    condition = contains(["sub", "mg", "rg"],
      var.assignment.scope
    )
    error_message = "Err: Invalid assignment scope"
  }
}

variable "exemptions" { #use snake case storage_account - checkmarx cares
  type = list(object({
    id                   = string
    risk_id              = string
    scope                = string
    category             = string
    assignment_reference = string
  }))
  description = <<DESC
  (Optional) List of exemption objects
  Properties:
  `id` (Required) - the resource ID for the exemption
  `risk_id` (Required) - internal risk reference ID
  `scope` (Required) - the scope for the exemption (sub, mg, rg)
  `category` (Required) - exemption category
  `assignment_reference` (Required) - assignment-friendly name/reference
  DESC

  validation {
    condition = alltrue(
      [
        for exemption in var.exemptions :
        contains(
          ["sub", "mg", "rg"],
          exemption.scope
        )
      ]
    )
    error_message = "Err: Invalid exemption scope."
  }

  validation {
    condition = alltrue(
      [
        for exemption in var.exemptions :
        contains(
          ["Mitigated", "Waiver"],
          exemption.category
        )
      ]
    )
    error_message = "Err: invalid exemption category."
  }

  default = []
}


### Module Code:
resource "azurerm_policy_definition" "naming_rg" {
  name                = var.policy_name
  policy_type         = "Custom"
  mode                = var.policy_mode
  display_name        = "Naming Policy for Resource Groups"
  management_group_id = var.policy_management_group_id
  description         = "A policy for configuring Resource Groups to abide by a specified naming standard"


  metadata = <<METADATA
  {
        "category": "Governance"
  }

  METADATA

  policy_rule = <<POLICY_RULE
  {
    "if": {
        "allOf": [
            {
                "field": "name",
                "notMatch": "[concat(parameters('resourceType'), parameters('workload'), parameters('environment'), parameters('region'), parameters('instance'))]"
            },
            {
                "field": "type",
                "equals": "Microsoft.Resources/ResourceGroups"
            }
        ]
    },
    "then": {
        "effect": "deny"
    }
  }
POLICY_RULE

  parameters = <<PARAMETERS
{
    "ResourceType": {
        "type": "String",
        "metadata": {
            "description": "Use up to 5 characters to identify the resource type",
            "displayName": "Resource Type or abbreviation"
        }
    },
    "WorkLoad": {
        "type": "String",
        "metadata": {
            "description": "The name of the workload or application",
            "displayName": "Workload/Application or Abbreviation"
        }
    },
    "environment": {
        "type": "String",
        "metadata": {
            "description": "The name of the environment",
            "displayName": "Environment name or Abbreviation"
        },
        "allowedValues": [
            "dev",
            "qa",
            "stage",
            "prod"
        ]
    },
    "region": {
        "type": "String",
        "metadata": {
            "description": "The name of the Azure Region or abbreviation",
            "displayName": "Azure Region name or Abbreviation"
        },
        "allowedValues": [
            "northcentralus",
            "nocnus",
            "southcentralus",
            "socnus",
            "centralus",
            "cus",
            "eastus",
            "eus",
            "eastus2",
            "eus2",
            "eastus3",
            "eus3",
            "westus1",
            "wus1",
            "westus2",
            "wus2",
            "westus3",
            "wus3"
        ]
    },
    "instance": {
        "type": "Integer",
        "metadata": {
            "description": "The Instance number of the resouce ie 001, 002",
            "displayName": "Instance Number"
        }
    }
}
PARAMETERS

}



resource "azurerm_subscription_policy_assignment" "rg_naming_assign_sub" {
  name                 = "pol-${azurerm_policy_definition.naming_rg.name}"
  policy_definition_id = azurerm_policy_definition.naming_rg.id
  subscription_id      = var.policy_subscription_id
}

**Comment by secura-dschauland** [comment]
Any update/movement on this item?

**Comment by secura-dschauland** [comment]
Just checking in to see if this is moving

**Comment by secura-dschauland** [comment]
Is the plan to solve this in v 3.x of the provider? It seems 3.x is coming to an end soon being that the latest version is 3.95.0
