### ISSUE TITLE
Setting scale rules

### ISSUE THREAD

**Issue by Zizico2** [hashicorp/terraform-provider-azurerm#20629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is support for scale rules in Azure Container Apps planed?

It would also be beneficial if I could use AzApi to fill this gap. But using AzApi in conjunction with AzureRm for this seems broken. The scale rules defined in AzApi never seem to get set. It's happened that they do get set, but then disappear after a following deployment, or just after some time (?). I assume this is a bug. And, according to this comment (https://github.com/hashicorp/terraform-provider-azurerm/issues/20535#issuecomment-1441608202), weird stuff is happening with scale rules, even when not using AzApi. So I assume the bug is on AzureRm's side.

Created a bug report for this problem: https://github.com/hashicorp/terraform-provider-azurerm/issues/20631

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

**Comment by MartyWind** [comment]
@jsok Thanks for your effort to implement this feature 👌
Would it be possible to set the value for `cooldown` with this?
https://learn.microsoft.com/en-us/azure/azure-monitor/autoscale/autoscale-understanding-settings

I want unused container apps to scale to zero, but the default `cooldown` of 5 minutes is just too low.

**Comment by ab-revanthgss** [comment]
Any update on this?

**Comment by wouter-van-den-meulenhof** [comment]
We're also waiting for this; currently we need to configure the scalers and their settings by hand. Not a fun excercise.

**Comment by waynebrantley** [comment]
@jsok I see your PR was reviewed with a few 'larger than minor' changes.  Any plans to get this out - looks like a great start and would be a nice addition.
