### ISSUE TITLE
Support for "publicNetworkAccess" in azurerm_windows_web_app

### ISSUE THREAD

**Issue by AlexJPawlak** [hashicorp/terraform-provider-azurerm#20635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey - currently it seems the ARM API property "publicNetworkAccess" cannot be set within Terraform. It's useful for scenarios with webapps, where we restrict traffic with private endpoints, but otherwise want to allow traffic to "tool site" to enable code deployment via Kudu. Would it be possible to add this? 
![image](https://user-images.githubusercontent.com/10241620/220977470-ed40b958-2293-4fb2-babf-3d8ae0c9520e.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Potential Terraform Configuration

```hcl
Best suitable as property in "siteConfig" - as this is where it resides in ARM https://learn.microsoft.com/en-us/azure/templates/microsoft.web/sites?pivots=deployment-language-bicep
```

**Comment by xiaxyi** [comment]
Thanks @AlexJPawlak for raising this issue, you can track the status in the mentioned pr. Feel free to let me know if you have any follow up questions.

**Comment by AlexJPawlak** [comment]
Thanks @xiaxyi - I've not found this PR when looking for issues reported, will look forward to merge and release so we can use it for our deployemnts
