### ISSUE TITLE
Support for collecting text logs with Azure Monitor

### ISSUE THREAD

**Issue by tvsanthoshkumar** [hashicorp/terraform-provider-azurerm#20648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure provides the support to collect the custom text logs with the help of data collection rules defined in Azure Monitor.

Kindly provide the support for custom text logs in data collection rules

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### References

https://learn.microsoft.com/en-us/azure/azure-monitor/agents/data-collection-text-log?tabs=portal

**Comment by teowa** [comment]
Hi @tvsanthoshkumar , thanks for submitting this!
By checking the code, the feature is available in new API versions, we will support this after a new stable API version is released, thanks!

**Comment by kriswill** [comment]
I just ran dead into this problem also.  was attempting to add `log_files` to `data_sources`, like so:

```terraform
  resource "azurerm_monitor_data_collection_rule" "dcr" {
  //  ...
  data_sources {
    dynamic "log_file" {
      for_each = azapi_resource.tables
      content {
        file_paths = ["${local.logs_path}/${log_file.value.name}"]
        name       = "datasource-${log_file.value.name}"
      }
    }
  }
}
```
I suppose I'll have to resort to using azapi_resource for these...

**Comment by jckeme-rs** [comment]
bump
