### ISSUE TITLE
Support for a nodepool resource group id attribute on azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by etaham** [hashicorp/terraform-provider-azurerm#20651]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add a new generated field on the azurerm_kubernetes_cluster resource called node_resource_group_id. The value should be the azurerm id of the resource group created for node pools.

The id (vs the name) is required for some resources, such as the scope of an azurerm_role_assignment. Using a data  azurerm_resource_group causes instability in terraform plan - where it always needs to refresh the data during the apply and recreate the azurerm_role_assignments.

We can work around by forming the id manually in a local block - but that seems a bit hacky.

Thank you!

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# No new configuration on the azurerm_kubernetes_cluster resource
resource "azurerm_kubernetes_cluster" "aks" {
  ...
}

# See the scope - we need the resource group id to perform role assignments. 
resource "azurerm_role_assignment" "aad_identity_vmc" {
  role_definition_name  = "Virtual Machine Contributor"
  scope                         = azurerm_kubernetes_cluster.aks.node_resource_group_id
}
```

**Comment by lovelinuxalot** [comment]
I think this is a problem with Azure client itself. Because the ResourceID of the resource group is not returned. Its only the name is returned

**Comment by etaham** [comment]
Yeh - [only the name is returned](https://learn.microsoft.com/en-us/rest/api/aks/managed-clusters/create-or-update?source=recommendations&tabs=HTTP#managedcluster). Is the provider allowed to make an additional API call the retried the id (or build it in code)?

**Comment by tombuildsstuff** [comment]
@etaham the Resource Group is guaranteed to be in the same Subscription, so we can [use the `ResourceGroups` type in the Common IDs package](https://github.com/hashicorp/go-azure-helpers/blob/6f01d4105802b8338ba7e31be01814d82b2c8d99/resourcemanager/commonids/resource_group.go#L22) to generate that on our side
