### ISSUE TITLE
authentifcation failed by using OIDC authentification

### ISSUE THREAD

**Issue by leon-avanade** [hashicorp/terraform-provider-azurerm#20650]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0

### AzureRM Provider Version

3.44

### Affected Resource(s)/Data Source(s)

hashicorp/azurerm ; azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
https://www.dropbox.com/scl/fo/uekd89mv6ukb0q94ih4yt/h?dl=0&rlkey=acg3o1wjg6r91z416ux13du5m
```

### Debug Output/Panic Output

```shell
https://login.microsoftonline.com/error?code=700016
```

### Actual Behaviour

Error: building account: could not acquire access token to parse claims: clientCredentialsToken: received HTTP status 400 with response: {"error":"unauthorized_client","error_description":"AADSTS700016: Application with identifier 'd7b671d8-de19-4f7f-956a-6d47e45b42ac' was not found in the directory 'Avanade Gallia'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.\r\nTrace ID: 573a95fa-c0d9-4353-9359-545a04c42100\r\nCorrelation ID: 9658c0f2-5869-48fb-9f31-548075e07a3a\r\nTimestamp: 2023-02-23 14:24:24Z","error_codes":[700016],"timestamp":"2023-02-23 14:24:24Z","trace_id":"573a95fa-c0d9-4353-9359-545a04c42100","correlation_id":"9658c0f2-5869-48fb-9f31-548075e07a3a","error_uri":"https://login.microsoftonline.com/error?code=700016"}

**Comment by ms-zhenhua** [comment]
Hi @leon-avanade, thank you for reaching out. Seems it is duplicated with https://github.com/hashicorp/terraform-provider-azurerm/issues/20546. Could you upgrade your Provider to [v3.45.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.45.0) and have another try?

**Comment by SuHwak** [comment]
> Hi @leon-avanade, thank you for reaching out. Seems it is duplicated with #20546. Could you upgrade your Provider to [v3.45.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.45.0) and have another try?

We can't, because [this pipeline]([v3.45.0 · hashicorp/terraform-provider-azurerm@9d33232 · GitHub 1](https://github.com/hashicorp/terraform-provider-azurerm/actions/runs/4259122295/jobs/7411040613)) has failed.

**Comment by tombuildsstuff** [comment]
@SuHwak the Github Actions failure above isn't an issue/blocking the release - v3.45.0 is available both [in the registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) and by updating the Provider Version specified in your Terraform Configuration - however since this'll be fixed by updating the version of the Provider being used here I'm going to close this issue for the moment.

Thanks!
