### ISSUE TITLE
Add/remove on managed disks doesn't work if a vm extension exists

### ISSUE THREAD

**Issue by bfleming-ciena** [hashicorp/terraform-provider-azurerm#2065]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.azurerm v1.16.0

### Affected Resource(s)

* azurerm_virtual_machine_extension
* azurerm_managed_disk

### Terraform Configuration Files
https://github.com/stonefury/terraform-azure-vm

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
NA

### Panic Output
None

### Actual Behavior

If there is an extension on the VM, then future managed disk attachements fail.

### Steps to Reproduce

1. Deploy a simple VM with 1 managed disk.
2. Go manually add a VM extension (recommend datadog agent - doesn't matter)
3. Update TF to add a second managed disk
4. Will hang and timeout/fail while the VM extension exists - BUG
5. Remove the VM extension.
6. Run the TF apply - Now it works.

I supplied a tf example in github.  It creates a VM with many managed disks. What happens is, a few of the managed disks will get added, and concurrently the extension will be added during that process, and it stops adding managed disks in its tracks.

### Important Factoids
VM Extensions on an VM prevents terraform from adding/removing managed disks.

### References

* #0000

**Comment by stonefury** [comment]
Could someone confirm this bug? I'm finding it hard to believe that we're the only company that is using managed disks and VM extensions. Put plainly, this is totally hindering our use of Terraform in Azure. If we can make a modification to a managed disk once a server extension is applied, that is an enormous setback.

Thanks

**Comment by stonefury** [comment]
Thanks @tombuildsstuff. You're the best, as usual.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
