### ISSUE TITLE
azurerm_cdn_frontdoor_origin default `enabled` state

### ISSUE THREAD

**Issue by ssrahul96** [hashicorp/terraform-provider-azurerm#20657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v1.3.9

### AzureRM Provider Version

v3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_origin" "fd_o_eus" {
  name                          = "${var.pocfd}-o-eus"
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.fd_og.id

  host_name                      = "test1us.eastus.cloudapp.azure.com"
  http_port                      = 80
  https_port                     = 443
  priority                       = 1
  weight                         = 1
  certificate_name_check_enabled = false
}

resource "azurerm_cdn_frontdoor_origin" "fd_o_wus" {
  name                          = "${var.pocfd}-o-wus"
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.fd_og.id

  host_name                      = "test2us.eastus.cloudapp.azure.com"
  http_port                      = 80
  https_port                     = 443
  priority                       = 1
  weight                         = 1
  enabled                        = true
  certificate_name_check_enabled = false
}
```

### Debug Output/Panic Output

```shell
execution is successful, but the desired state is not correct as per doc
```

### Expected Behaviour

as per the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_origin#enabled), the enabled is `true`. but its `disabled` by default

### Actual Behaviour

<img width="573" alt="image" src="https://user-images.githubusercontent.com/15570570/221343712-c992b1d2-37a6-4086-a91a-ac6757ed3c1c.png">

**Comment by WodansSon** [comment]
@ssrahul96, thank you for opening this issue, this is currently by design and will correct itself once the v4.0 provider is released. I added a note in the documentation which calls out this discrepancy.

>The enabled field will need to be explicitly set until the 4.0 provider is released due to the deprecation of the health_probes_enabled property in version 3.x of the AzureRM Provider.

Sorry for the confusion, thanks again! 🚀
