### ISSUE TITLE
Support for Private Endpoint Network Policies, not just enabled/disabled

### ISSUE THREAD

**Issue by rvdouderaa** [hashicorp/terraform-provider-azurerm#20677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In `azurem_subnet` there is the option `private_endpoint_network_policies_enabled`, which accepts (obviously) only true or false. 

However, there are more options. Eg. when setting `PrivateEndpointNetworkPolicies` using powershell the options are:
- `disabled`
- `NetworkSecurityGroupEnabled`
- `RouteTableEnabled`
- `enabled`

When setting `NetworkingSecurityGroupEnabled` using powershell, Terraform wants to revert this on the next run

```
Terraform will perform the following actions:private_endpoint_network_policies_enabled      = false -> true
```

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]

  private_endpoint_network_policies = "NetworkSecurityGroupEnabled"
}
```
```


### References

https://learn.microsoft.com/en-us/azure/private-link/disable-private-endpoint-network-policy?tabs=network-policy-powershell

**Comment by pascalkrielen** [comment]
Having the same issue. Hope this can be adjusted.

**Comment by sinbai** [comment]
@rvdouderaa thanks for opening this issue. Since Terraform relies on the Azure rest  API for Azure resource management.  Per [the latest Azure API](https://github.com/Azure/azure-rest-api-specs/blob/09119c0cca116b1d8b69552bb63d697628f0e5f6/specification/network/resource-manager/Microsoft.Network/stable/2022-09-01/virtualNetwork.json#L1606),  `privateEndpointNetworkPolicies` only supports  `Enabled`  and `Disabled` . So Terraform could not support `NetworkSecurityGroupEnabled` and `RouteTableEnabled` until the Azure API includes them.

**Comment by sinbai** [comment]
@rvdouderaa I have filed an[ API issue](https://github.com/Azure/azure-rest-api-specs/issues/23256) to track this inconsistency. Let's wait for the response from the API team.

**Comment by Marcel1805** [comment]
@sinbai meanwhile the API is now capable for more options for PrivateEndpointNetworkPolicies, therefore the azurerm provider could be updated.
Thank you!

**Comment by PwshPally** [comment]
@sinbai It looks like the API side has been fixed.  https://github.com/Azure/azure-rest-api-specs/blob/main/specification/network/resource-manager/Microsoft.Network/stable/2023-09-01/virtualNetwork.json#L1602

**Comment by swati-delphix** [comment]
When this gets updated? Also as per documentation, if we just enabled it, it still work for network security group to restrict network for private endpoint , right ?

**Comment by man0s** [comment]
+1 on this one..

**Comment by pascalkrielen** [comment]
It seems the options are available now:
![image](https://github.com/user-attachments/assets/ce484760-72b8-48a4-8000-55304c524d7e)

**Comment by katbyte** [comment]
closing based on @pascalkrielen 's comment
