### ISSUE TITLE
Container App - Ingress parameters do not match Azure Portal options, need clarification

### ISSUE THREAD

**Issue by askaribragimov** [hashicorp/terraform-provider-azurerm#20693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.8

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
A typical Ingress block looks like

  ingress {
    external_enabled           = false
    allow_insecure_connections = true
    target_port                = 3000
    transport                  = "auto"
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
  }

However, in the Azure Portal ingress options are

"Limited to Container App Environment", "Limited to VNET", "Accepting traffic from anywhere".

It is unclear from the documentation how to switch between the three. When I set `  external_enabled           = false` I get `Limited to Container App Environment` while I do need VNET.
```

### Debug Output/Panic Output

```shell
---
```

### Expected Behaviour

Documentation should describe how to get "Limited to Container App Environment", "Limited to VNET", "Accepting traffic from anywhere" ingress setups using terraform.

**Comment by JeremyKeusters** [comment]
I agree that this is currently unclear in Terraform. I did however manage to use the `Limited to VNet` option through Terraform by following these steps:

1. Set the `internal_load_balancer_enabled` argument to `True` and assign a subnet to the `infrastructure_subnet_id` argument for the Container App Environment: 
```
resource "azurerm_container_app_environment" "cae" {
  ...
  internal_load_balancer_enabled = true
  infrastructure_subnet_id       = azurerm_subnet.snet.id
}
```
2. Create a new Container App with the following `ingress` code:
```
  ingress {
    external_enabled = true
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
```

Changing `external_enabled` to `false` modifies the container app to use `Limited to Container Apps Environment` for the ingress traffic option. This means that it is possible to achieve all of the three available settings, but it could be more clearly documented.

**Comment by askaribragimov** [comment]
Yes, I arrived at same conclusion and managed to understand that - but this information has to be in the docs in order to enable users of the provider to migrate from Portal to terraform code at minimum effort and save time.

**Comment by skykubashovo** [comment]
From Azure portal it's also possible to restrict Ingress per ip: 

> IP Restrictions
Access restrictions allow you to define lists of allow/deny rules to control traffic to your app. If there are no rules defined then your app will accept traffic from any address.

but it's not possible with terraform. It would be great to have this feature :)

**Comment by Yukititit** [comment]
I finally reach the same conclusion in version 3.75 the after days on reviewing docs. It is even more confusing that in the docs of [container_app_environment](https://registry.terraform.io/providers/hashicorp/azurerm/3.75.0/docs/resources/container_app_environment) stated that the argument `internal_load_balancer_enabled` `can only be set to true if infrastructure_subnet_id is specified.`

**Comment by Justrebl** [comment]
> Changing `external_enabled` to `false` modifies the container app to use `Limited to Container Apps Environment` for the ingress traffic option. This means that it is possible to achieve all of the three available settings, but it could be more clearly documented.

Almost a year old and still serving the community : thank you sire! 🫡

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @JeremyKeusters‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
