### ISSUE TITLE
 azurerm_virtual_desktop_application_group attribute default_desktop_display_name not working as expected

### ISSUE THREAD

**Issue by AdrianSaunders** [hashicorp/terraform-provider-azurerm#20716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_application_group

### Terraform Configuration Files

```hcl
# Create AVD DAG
resource "azurerm_virtual_desktop_application_group" "dag" {
  resource_group_name = azurerm_resource_group.vdi.name
  host_pool_id        = azurerm_virtual_desktop_host_pool.hostpool.id
  location            = azurerm_resource_group.vdi.location
  type                = "Desktop"
  name                = "${var.vdi-prefix}-dag"
  friendly_name       = "Desktop AppGroup"
  description         = "AVD application group"
  default_desktop_display_name = "${var.vdi-prefix}-desktop"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

DAG default desktop should be renamed to "${var.vdi-prefix}-desktop" 

### Actual Behaviour

remains as 'sessiondesktop' after apply
![image](https://user-images.githubusercontent.com/53939967/222172630-350b529f-265f-4ce4-ab3e-80c0619168db.png)

### Steps to Reproduce

deploy azure vdi and set a DAG

**Comment by sinbai** [comment]
@AdrianSaunders  thanks for opening this issue. Could you provide Terraform Log to help troubleshoot?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of the logs. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce and investigate the problem.
