### ISSUE TITLE
instant_restore_resource_group missing in tf docs

### ISSUE THREAD

**Issue by PeterLofaj** [hashicorp/terraform-provider-azurerm#20740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_backup_policy_vm

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Description of new property block instant_restore_resource_group is missing from azurerm_backup_policy_vm documentation.

https://registry.terraform.io/providers/hashicorp/azurerm/3.45.0/docs/resources/backup_policy_vm

### Actual Behaviour

missing

**Comment by mybayern1974** [comment]
I'm closing this issue by seeing the fix PR has been merged.
