### ISSUE TITLE
expected site_config.0.application_stack.0.dotnet_version to be one of [v2.0 v3.0 v4.0 v5.0 v6.0 v7.0]

### ISSUE THREAD

**Issue by sven5** [hashicorp/terraform-provider-azurerm#20743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app_slot

### Terraform Configuration Files

I have one App Service for Windows with `site_config` and `application_stack` setting
```hcl

resource "azurerm_windows_web_app" "app_service" {
  name                         = "app-${var.project}-${var.environment}-001"
  resource_group_name          = azurerm_resource_group.rg_app.name
  location                     = var.location
  tags                         = local.tags
  service_plan_id              = azurerm_service_plan.app_service_plan.id
  app_settings                 = local.app_env_variables
  client_affinity_enabled      = false
  virtual_network_subnet_id    = azurerm_subnet.app_service_subnet.id
  https_only                   = true
  
  site_config {
    scm_type           = null
    
    always_on          = true
    ftps_state         = "Disabled"
    websockets_enabled = true
    health_check_path  = "/api/healthcheck" # health check required in order that internal app service plan loadbalancer do not loadbalance on instance down
    use_32_bit_worker  = false
    remote_debugging_enabled = true
    #remote_debugging_version = "VS2022"
    
    application_stack {
      dotnet_version = "v6.0"
    }
  }
```

following one deployment slot which should inherit settings from app service.

```hcl
resource "azurerm_windows_web_app_slot" "app_service_test_slot_1" {
  count               = var.environment == "test" ? 1 : 0
  app_service_id      =  azurerm_windows_web_app.app_service.id
  name                = "test-1"
  tags                = local.tags
  app_settings        = azurerm_windows_web_app.app_service.app_settings
  virtual_network_subnet_id    = azurerm_windows_web_app.app_service.virtual_network_subnet_id
  https_only                   = azurerm_windows_web_app.app_service.https_only
  site_config {
    always_on          = azurerm_windows_web_app.app_service.site_config[0].always_on
    ftps_state         = azurerm_windows_web_app.app_service.site_config[0].ftps_state
    websockets_enabled = azurerm_windows_web_app.app_service.site_config[0].websockets_enabled
    health_check_path  = azurerm_windows_web_app.app_service.site_config[0].health_check_path
    use_32_bit_worker  = azurerm_windows_web_app.app_service.site_config[0].use_32_bit_worker
    application_stack {
      dotnet_version = azurerm_windows_web_app.app_service.site_config[0].application_stack[0].dotnet_version
    }
  }
```

### Debug Output/Panic Output

```shell
│ Error: expected site_config.0.application_stack.0.dotnet_version to be one of [v2.0 v3.0 v4.0 v5.0 v6.0 v7.0], got 
│
│   with azurerm_windows_web_app_slot.app_service_test_slot_1[0],
│   on test.tf line 20, in resource "azurerm_windows_web_app_slot" "app_service_test_slot_1":
│   20:       dotnet_version = azurerm_windows_web_app.app_service.site_config[0].application_stack[0].dotnet_version
```

### Expected Behaviour

I expect that all the settings from the app service's `site_config` can be applied to deployment slot.

### Actual Behaviour

the error message above is shown

**Comment by pkumar-yeti** [comment]
Hello @sven5  Any update on this issue ? I am facing the same issue when creating azure app service dotnet v8.0 version, I am getting this error "expected site_config.0.application_stack.0.dotnet_version to be one of [v2.0 v3.0 v4.0 v5.0 v6.0 v7.0], got v8.0"

**Comment by pkumar-yeti** [comment]
@sven5  thanks for the quick response. Unfortunately Mine is not working with 3.50.0 version. I am using versions like below. Any suggestions ?
```
terraform {
  required_version = "= 1.3.7"

  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.50.0"
    }
    random  = "= 3.4.3"
    # null    = "= 3.0.0"
  }
}

provider "azurerm" {
  features {}
}
```
And I am using variables block like this

```
variable "application_stack" {
  type        = any
  description = "(optional) Runtime information for the Application service"
  default = {
    current_stack = "dotnet"  # Possible values include dotnet, dotnetcore, node, python, php, and java.
    dotnet_version = "v8.0" # The version of .NET to use when current_stack is set to dotnet. Possible values include v2.0,v3.0, v4.0, v5.0, v6.0, v7.0 and v8.0.
  }
}

```

**Comment by oWretch** [comment]
@pkumar-yeti You will need to update your provider version to a newer version. v8.0 support was released after 3.50.0, which is why it doesn't work for you.

**Comment by pkumar-yeti** [comment]
@oWretch thanks for the info, If I update my provider other services in my terraform code might impact right ? how can I make sure my services in the tf code will not impact ? because I have 100s azure resources provisioned through this same version code. It would be great if you can answer this. thanks in advance.

**Comment by sven5** [comment]
An update can always impact your existing resources. However, you have to go through the `tf plan` output to see what's going on. No one can do this work for you 😄

**Comment by pkumar-yeti** [comment]
Thank you @sven5.
