### ISSUE TITLE
Support for CMK on Geo-backup enabled servers on Flexible Server for PostgreSQL

### ISSUE THREAD

**Issue by korsveien** [hashicorp/terraform-provider-azurerm#20750]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Creating a Flexible Server for PostgreSQL where both CMK and Geo-redundant backup is enabled will result in the following error:

```
Code="CMKNotSupportedForGeoRedundantBackupEnabledServer" Message="Customer Managed Key encryption is not supported for Geo redundant backup enabled server."
```

If this is to be supported there needs to be a way to define a secondary key id and identity that is used to encrypt the Geo-redundant backup in the paired region.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server" "postgres_server" {

...

customer_managed_key {

    // primary
    primary_key_vault_key_id          = azurerm_key_vault_key.primary.id
    primary_user_assigned_identity_id = azurerm_user_assigned_identity.primary.id

    // secondary (this or some version of this needs to be added)
    secondary_key_vault_key_id          = azurerm_key_vault_key.secondary.id
    secondary_user_assigned_identity_id = azurerm_user_assigned_identity.secondary.id
 }

 geo_redundant_backup_enabled = true

...

}
```

### References

Similar issue for mysql: #20408

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Service team confirmed this feature hasn't been supported by Azure Rest API. But it will be released to next API version. After that, we could take another look.

BTW, I filed an [issue](https://github.com/Azure/azure-rest-api-specs/issues/22890) on azure rest api spec for tracking.

**Comment by martinshkrelijerry** [comment]
@neil-yechenwei what about the MySQL issue https://github.com/hashicorp/terraform-provider-azurerm/issues/20408? Will this also be dealt with next API version?

**Comment by Danielchui** [comment]
@neil-yechenwei any update on this issues?  Any timeline for the fix?  Thanks.
