### ISSUE TITLE
terraform apply fails when trying to provision the api management service

### ISSUE THREAD

**Issue by carvarr** [hashicorp/terraform-provider-azurerm#20778]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "resource-group" {
  name = "myrgname"
}


resource "azurerm_api_management" "apim" {
  name                = "apim-dll-jhgtsk"
  location            = data.azurerm_resource_group.resource-group.location
  resource_group_name = data.azurerm_resource_group.resource-group.name
  publisher_name      = "user"
  publisher_email     = "user@mail.com"
  sku_name            = "Developer_1"

  tags = {
    iac-deployer = "terraform"
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.githubusercontent.com/carvarr/986b40548c22e5ce6de413d9b02acbe7/raw/f1f957980bbb1aa206bedd4ace9330e4cf304676/gistfile2.txt
```

### Expected Behaviour

apply should complete sucessfully

### Actual Behaviour

╷
│ Error: waiting for creation/update of Api Management: (Service Name "apim-dll-jhgtsk" / Resource Group "rg-gobrepo-ephemeral-dll-001"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=202
│ 
│   with azurerm_api_management.apim,
│   on main.tf line 102, in resource "azurerm_api_management" "apim":
│  102: resource "azurerm_api_management" "apim" {

### Steps to Reproduce

terraform apply

**Comment by xuzhang3** [comment]
@carvarr  The request was blocked by the backend, please check the throttle configuration of your sub.
```log
{"error":{"code":"SubscriptionRequestsThrottled","message":"Number of requests for subscription '6088a2cf-1d80-4dfa-817a-84fe6c7371d1' and operation 'GET/SUBSCRIPTIONS/RESOURCEGROUPS/PROVIDERS/MICROSOFT.APIMANAGEMENT/SERVICE/OPERATIONRESULTS/' exceeded the backend storage limit. Please try again after '6' seconds."}}: timestamp=2023-03-03T13:07:52.396Z
2023-03-03T13:08:54.406Z [DEBUG] provider.terraform-provider-azurerm_v3.45.0_x5: AzureRM Request: 
```

**Comment by carvarr** [comment]
@xuzhang3 thank you for your feedback, we are checking throttling restriction at sub level.. regards
