### ISSUE TITLE
azurerm_cdn_endpoint_custom_domain is not properly choosing Latest certificate

### ISSUE THREAD

**Issue by Kapsztajn** [hashicorp/terraform-provider-azurerm#20772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_endpoint_custom_domain

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_endpoint_custom_domain" "custom_domain" {
  for_each        = toset(var.static_domains)
  name            = join("-", [replace("${each.key}", ".", "-"), "cdn-profile"])
  cdn_endpoint_id = azurerm_cdn_endpoint.cdn_endpoint.id
  host_name       = "${each.key}"
  user_managed_https {
    key_vault_secret_id      = join("", [var.key_vault_certificate_url, "/secrets/", replace(each.key, ".", "-")])
    tls_version              = "TLS12"
  }
}
```

### Debug Output/Panic Output

```shell
# module.hidden.azurerm_cdn_endpoint_custom_domain.custom_domain["hidden"] will be updated in-place
  ~ resource "azurerm_cdn_endpoint_custom_domain" "custom_domain" ***
        id              = "/subscriptions/***/resourceGroups/hidden/providers/Microsoft.Cdn/profiles/nonprod-cdn-profile/endpoints/nonprod-cdn-endpoint/customDomains/hidden"
        name            = "hidden"
        # (2 unchanged attributes hidden)

      + user_managed_https ***
          + key_vault_secret_id = "***/secrets/hidden"
          + tls_version         = "TLS12"
        ***
    ***
```

### Expected Behaviour

Terraform should explicity choose Latest certificate when no version is provided.

```
        "secretVersion": null,
```
![image](https://user-images.githubusercontent.com/23492161/222699772-0e1c3bc9-5652-4793-a415-6b30cc397fb7.png)

### Actual Behaviour

Terraform is not choosing Latest version. On portal Certificate/Secret version is empty, even if it is required:
![image](https://user-images.githubusercontent.com/23492161/222698548-71c186a8-3043-4862-a113-851a4a702aae.png)

After checking from az cli I could see difference in secretVersion. When I manually set secretVersion to Latest it looks like this:
```
  {
    "customHttpsParameters": {
      "certificateSource": "AzureKeyVault",
      "certificateSourceParameters": {
        "deleteRule": "NoAction",
        "resourceGroupName": "hidden",
        "secretName": "hidden",
        "secretVersion": null,
        "subscriptionId": "hidden",
        "updateRule": "NoAction",
        "vaultName": "hidden"
}
```
**secretVersion is null** when after Terraform set certificate the version is:
```
  {
    "customHttpsParameters": {
      "certificateSource": "AzureKeyVault",
      "certificateSourceParameters": {
        "deleteRule": "NoAction",
        "resourceGroupName": "hidden",
        "secretName": "hidden",
        "secretVersion": "",
        "subscriptionId": "hidden",
        "updateRule": "NoAction",
        "vaultName": "hidden"
      }
```
**"secretVersion": ""**

### Steps to Reproduce

Run Terraform with azurerm_cdn_endpoint_custom_domain connected to KeyVault secret.

### References

Documentation could note how to provide specific version.

**Comment by WodansSon** [comment]
@Kapsztajn Thank you for reporting this issue. According to the [Azure Key Vault REST API reference documentation](https://learn.microsoft.com/rest/api/keyvault/keys/get-key/get-key?tabs=HTTP#uri-parameters), `...This URI fragment is optional. If not specified, the latest version of the key is returned`. The `Microsoft.Azure.KeyVault` library passes `String.Empty` as the `version` to the ARM call when there is no specific `version` requested. In the [.NET documentation](https://learn.microsoft.com/en-us/dotnet/api/system.string.empty?view=net-7.0) `String.Empty` is defined as a `...zero-length string, ""`. TBH, this feels more like a Portal UI/CLI bug rather than a Terraform issue. That said, I will see what I can do to work-around the Portal UI bug so it will display correctly, but we will still internally within Terraform track it as an empty string (e.g., "").
