### ISSUE TITLE
Application Gateway timeout

### ISSUE THREAD

**Issue by MilanHtec984** [hashicorp/terraform-provider-azurerm#20770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
terraform {
  required_version = "> 1.0.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "> 3.0.0"
    }
  }
  backend "azurerm" {
    resource_group_name  = "xxxx"
    storage_account_name = "infrahtecrndshared"
    container_name       = "xxxx"
    key                  = "xxxx"
  }
}

provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
Error: waiting for create of Application Gateway: (Name "dev-blueprints-agw" / Resource Group "dev-htecrnd-shared-rg-modular1-eastus2"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=401 -- Original Error: Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '3/3/2023 9:01:22 AM' is earlier than current UTC time '3/3/2023 9:05:00 AM'."
```

### Expected Behaviour

Resource to be created.

### Actual Behaviour

Times out after 15, 17, 20 minutes.

### References

Reference to previous issue
https://github.com/hashicorp/terraform-provider-azurerm/issues/20712

**Comment by reefwhooligan** [comment]
Was there something you did to resolve this that you could share?

**Comment by AndreiZhukouski** [comment]
@MilanHtec984 could you share your solution? Because I'm still experiencing this for both Application Gateway and API Management resources - https://github.com/hashicorp/terraform-provider-azurerm/issues/20834#issuecomment-1461585465.
