### ISSUE TITLE
Error: could not find DNS zone

### ISSUE THREAD

**Issue by alexs77** [hashicorp/terraform-provider-azurerm#20773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_dns_zone

### Terraform Configuration Files

```hcl
data "azurerm_dns_zone" "this" {
  name = var.domain.name
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: could not find DNS zone with name: "foo.com"
│ 
│   with module.cdn[0].data.azurerm_dns_zone.this[0],
│   on modules/cdn/cdn.tf line 44, in data "azurerm_dns_zone" "this":
│   44: data "azurerm_dns_zone" "this" {
│ 
╵
```

### Expected Behaviour

Work

### Actual Behaviour

Doesn't work.

### Important Factoids

It works with hashicorp/azurerm = 3.45.0 and earlier.

**Comment by evanrappe** [comment]
I can't say with certainty, but it _appears_ that we only see this in workspaces where we're not specifying `resource_group_name` for the data source (which is documented as optional). All workspaces were working on 3.45, whether or not the RG name was specified.

**Comment by alexs77** [comment]
Same for me, now that you mention it.

We've got some setups, where it's still working and some, where it stopped

We're running Terraform on Azure DeVops in a release pipeline. Where it's
still working, the DNS zone is in the same resource group as the Service
Principal connects to, so to say.

Evan Rappe ***@***.***> schrieb am Fr., 3. März 2023, 15:17:

**Comment by slzmruepp** [comment]
We have suddenly the same problem in our terraform pipeline. Worked fine but since yesterday the following errors:
│ Error: could not find DNS zone with name: "zone name"
│ 
│   with data.azurerm_dns_zone.aks_ingress_zone_app_int[0],
│   on dns.tf line 132, in data "azurerm_dns_zone" "aks_ingress_zone_app_int":
│  132: data "azurerm_dns_zone" "aks_ingress_zone_app_int" {

**Comment by slzmruepp** [comment]
I can concur that after adding the resource_group to the block, the read started to work again:
```
data "azurerm_dns_zone" "aks_ingress_zone_app_int" {
  name                = "test.example.com"
  resource_group_name = "rg-resourcegroupname"
  provider            = azurerm.dnszonesub
}
```
So this changed from an optional to a required parameter which should be respected by the documentation.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems DNSZones.List API doesn't return the value anymore. So filed an [issue](https://github.com/Azure/azure-rest-api-specs/issues/22921) on rest api spec for tracking.

**Comment by tombuildsstuff** [comment]
Linking to the correct issue: https://github.com/hashicorp/go-azure-sdk/issues/356 - this is an issue with polling in `hashicorp/go-azure-sdk` and will need to be fixed there

**Comment by neil-yechenwei** [comment]
Seems the issue has been fixed. Please take another look. Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of this [PR](https://github.com/hashicorp/go-azure-sdk/pull/388). As such, I am going to mark this issue as closed.
