### ISSUE TITLE
Support for specifying action groups for `azurerm_cost_anomaly_alert` resource.

### ISSUE THREAD

**Issue by sheeeng** [hashicorp/terraform-provider-azurerm#20777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would be nice if we are able to reuse existing action groups for `azurerm_cost_anomaly_alert` resource.

That's way we do not need to copy and paste the email addresses again.

### New or Affected Resource(s)/Data Source(s)

azurerm_cost_anomaly_alert

### Potential Terraform Configuration

```hcl
resource "azurerm_cost_anomaly_alert" "example" {
  name            = "alertname"
  display_name    = "Alert DisplayName"

  notification {
    contact_emails = [
      "foo@example.com",
      "bar@example.com",
    ]

    contact_groups = [
      azurerm_monitor_action_group.example.id,
    ]
  }
}
```

### References

- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cost_anomaly_alert
- https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/consumption_budget_subscription

**Comment by jameshowe** [comment]
Whilst I agree, I think the issue here is the lack of support from the Azure side rather than the provider not exposing the capability.

**Comment by aristosvo** [comment]
Hi  @sheeeng! Thanks for raising this issue.

As @jameshowe already stated, this is not something supported from the Azure side. Feel free to raise this towards Microsoft via their Sales representative or by filing a ticket at their side.

For now I'll mark it as an upstream issue.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
