### ISSUE TITLE
Error: Invalid Index after upgrading to 3.46.0 from 3.40.0

### ISSUE THREAD

**Issue by cshea15** [hashicorp/terraform-provider-azurerm#20785]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "aks_node_pool" {
  name                     = "aksnp${count.index + 1}"
  count                    = var.node_pool_count
  tags                     = azurerm_resource_group.rg_aks.tags
  os_sku                   = var.os_sku
  vnet_subnet_id           = var.aks_cluster_subnet_id
  enable_auto_scaling      = false
  scale_down_mode          = "Deallocate"
  node_count               = var.node_count
  zones                    = ["1", "2", "3"]
  kubernetes_cluster_id    = azurerm_kubernetes_cluster.aks_cluster[count.index].id
  vm_size                  = var.node_pool_vm_size
  priority                 = "Regular"
  enable_node_public_ip    = true
  node_public_ip_prefix_id = var.node_pip_prefix_id
}
```

### Debug Output/Panic Output

```shell
Didn't debug
```

### Expected Behaviour

I ran the code with the 3.40.0 version and was able to get the script to deploy. Now after upgrading it to 3.46.0, I get this Error: Invalid Index. I never changed this line of code since upgrading to 3.46.0

### Actual Behaviour

╷
│ Error: Invalid index
│
│   on aks\aks.tf line 53, in resource "azurerm_kubernetes_cluster_node_pool" "aks_node_pool":
│   53:   kubernetes_cluster_id    = azurerm_kubernetes_cluster.aks_cluster[count.index].id
│     ├────────────────
│     │ azurerm_kubernetes_cluster.aks_cluster is tuple with 2 elements
│     │ count.index is 2
│
│ The given key does not identify an element in this collection value: the given index is greater than or equal to the length of the collection.
╵

### Steps to Reproduce

terraform init
terraform plan --var-file local.tfvars --out plan.out

**Comment by ms-henglu** [comment]
Hi @cshea15 ,

Thank you for taking time to report this issue.

From the error message, it seems that `azurerm_kubernetes_cluster.aks_cluster` only contains 2 elements which causes the index 2 invalid. Would you please check it?

**Comment by cshea15** [comment]
@ms-henglu thank you for the comment Heng, looks like I had something I forgot to update in the changes i made. apologize for taking up your time. thank you again!
