### ISSUE TITLE
Subnet rename (destroy/recreate) fails if load balancer is attached

### ISSUE THREAD

**Issue by pessimism** [hashicorp/terraform-provider-azurerm#20783]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46

### Affected Resource(s)/Data Source(s)

azurerm_subnet, azurerm_lb

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "operational_subnet" {
  name                 = "${var.envname}-op-snet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = var.op_snet_prefix
}

resource "azurerm_lb" "cslb" {
  name                = "${var.envname}-lb"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "Standard"
  tags                = var.tags

  #Its IP
  frontend_ip_configuration {
    name                          = "${var.envname}-lb-ip"
    private_ip_address            = var.cs_lb_ip
    private_ip_address_allocation = "Static"
    private_ip_address_version    = "IPv4"
    subnet_id                     = azurerm_subnet.operational_subnet.id
  }
}
```

### Debug Output/Panic Output

```shell
~ name   = "REDACTED_op_snet" -> "REDACTED-op-snet" # forces replacement
# azurerm_subnet.operational_subnet must be replaced

Error: deleting Subnet: (Name "REDACTED_op_snet" / Virtual Network Name "REDACTED_vnet" / Resource Group "REDACTED"): network.SubnetsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeDeleted" Message="Subnet REDACTED_op_snet is in use by /subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/loadBalancers/REDACTED-lb/frontendIPConfigurations/REDACTED-lb-ip and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet." Details=[]
```

### Expected Behaviour

- gracefully destroy the downstream load balancer attached to the subnet
- destroy and recreate the subnet to complete the name change
- recreate the removed load balancer as it was before

### Actual Behaviour

-subnet removal blocked by downstream load balancer frontend ip configuration

### Steps to Reproduce

Create a subnet
Create a load balancer with a frontend ip configuration attached to the subnet
Attempt to rename the subnet using terraform

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/19781 seems to relate to other problems with proper detection and handling of dependencies downstream of a subnet

**Comment by sinbai** [comment]
@pessimism thanks for opening this issue. In your case, could you try adding [create_before_destroy  lifecycle ](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#create_before_destroy)as follows to see if that fixes the issue?

```
resource "azurerm_subnet" "operational_subnet" {
  name                 = "${var.envname}-op-snet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = var.op_snet_prefix

  lifecycle {
   create_before_destroy = true
  }
}

```

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved with the suggestion by @sinbai. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
