### ISSUE TITLE
azurerm_container_app - Does not allow multiple custom_domain blocks

### ISSUE THREAD

**Issue by srjobinar** [hashicorp/terraform-provider-azurerm#20784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.5

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
# Relevant section of terraform with dummy values

resource "azurerm_container_app" "container_app" {
  name                         = "container-app"
  container_app_environment_id = "<env_id>"
  resource_group_name          = "container-app-rg"
  revision_mode                = "Single"

  ingress {
    target_port = 80
    external_enabled = true
    traffic_weight {
      percentage = 100
    }
    custom_domain {
      certificate_id = "<certificate_id_from_container_apps_environment>"
      name          = "customDomain1"
    }
    custom_domain {
      certificate_id = "<certificate_id_from_container_apps_environment>"
      name          = "customDomain2"
    }
  }

  registry {
    server               = "containerappeun.azurecr.io"
    identity             = "<user_assigned_identity>"
  }

  identity {
    type = "UserAssigned"
    identity_ids = ["<user_assigned_identity>"]
  }

  template {
    container {
      name   = "container-app"
      image  = "<valid_image>"
      cpu    = var.container_cpu_request
      memory = var.container_mem_request
    }
    min_replicas = var.container_min_replicas
    max_replicas = var.container_max_replicas
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Too many custom_domain blocks
│ 
│   on main.tf line 127, in resource "azurerm_container_app" "container_app":
│  127:     custom_domain {
│ 
│ No more than 1 "custom_domain" blocks are allowed
```

### Expected Behaviour

According to the documentation:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_app#custom_domain

One or more custom_domain block should be allowed and hence when applying terraform,
Container App should be created with 2 custom domains configured.

### Actual Behaviour

terraform plan fails with the following validation error:
```
│ Error: Too many custom_domain blocks
│ 
│   on main.tf line 127, in resource "azurerm_container_app" "container_app":
│  127:     custom_domain {
│ 
│ No more than 1 "custom_domain" blocks are allowed
```

Looking at the code (With my very limited knowledge of Go)
In the customDomain schema `maxitems` seems to be set to one which could be the problem.

### Steps to Reproduce

`terraform plan`

**Comment by jackofallops** [comment]
I believe this needs to be implemented as an external resource in the same pattern as per `azurerm_static_site_custom_domain` which will update the existing resource.

**Comment by milesbarnard** [comment]
Any update on this? I'm also having this issue. The PR appears to be mostly done
