### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by sandole** [hashicorp/terraform-provider-azurerm#20795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Referring to https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#url:

(Optional) One url block as defined above - this line should say "below." instead of "above".

### Terraform Version

N/A

### AzureRM Provider Version

N/A

### Affected Resource(s)/Data Source(s)

N/A

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

**Comment by xyq175com** [comment]
Indeed it is, I can work on this  and drop a PR later

**Comment by sinbai** [comment]
@sandole, @xyq175 PR #20799  has been submitted to fix it. Thank you all.
