### ISSUE TITLE
Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer

### ISSUE THREAD

**Issue by tobiaswi** [hashicorp/terraform-provider-azurerm#20794]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

 v3.44 - v.3.46

### Affected Resource(s)/Data Source(s)

azurerm provider

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.46.0"
    }
  }

  required_version = ">= 1.3.9"
}

provider "azurerm" {
  use_oidc            = true
  storage_use_azuread = true
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-provider-issues"
  location = "westeurope"
}
```

### Debug Output/Panic Output

```shell
Initializing the backend...

Successfully configured the backend "http"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.44.0"...
- Installing hashicorp/azurerm v3.44.0...
- Installed hashicorp/azurerm v3.44.0 (signed by HashiCorp)

Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!
```
```shell
│ Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: could not parse Azure CLI version: launching Azure CLI: exec: "az": executable file not found in $PATH
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 12, in provider "azurerm":
│   12: provider "azurerm" {
│ 
```

### Expected Behaviour

Succeed without azure cli installed (CI environment).

### Actual Behaviour

Any plan fails with provider version >= 3.44 due to trying to build authorizer with az cli, even when not required (deploying resource group) and using OIDC auth.

### Steps to Reproduce
Able to reproduce issues with every provider version v3.44 and up.

The plan for v3.43 fails because I was trying to determine if the "use_cli = false" flag, which was introduced in v3.44, has any impact. It does not.
Using v3.43 and removing "use_cli" fixes the issue and plans are successful.

### Important Factoids

- CI environment with minimal terraform footprint (no az cli)

- Passing config through ENV
ARM_USE_OIDC
ARM_OIDC_TOKEN_FILE_PATH
ARM_CLIENT_ID
ARM_TENANT_ID
ARM_SUBSCRIPTION_ID

### References
possible issue introduced here? https://github.com/hashicorp/terraform-provider-azurerm/pull/20320

**Comment by manicminer** [comment]
@tobiaswi Thanks for reporting this issue. I have opened https://github.com/hashicorp/terraform-provider-azurerm/pull/20824 to fix this issue with handling of the `oidc_tokenfile_path` provider property, which will be included in this week's release.

**Comment by MicheleMinelli** [comment]
I am still seeing this problem with terraform 1.4.4 and azurerm 3.50.0

In my .tf I have

```
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.50.0"
    }
  }
```

And this is what I do and what I see

```
$ terraform version
Terraform v1.4.4
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.50.0

-------------------------------------------

$ terraform init -upgrade

Initializing Terraform Cloud...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.50.0"...
- Installing hashicorp/azurerm v3.50.0...
- Installed hashicorp/azurerm v3.50.0 (signed by HashiCorp)

Terraform has made some changes to the provider dependency selections recorded
in the .terraform.lock.hcl file. Review those changes and commit them to your
version control system if they represent changes you intended to make.

Terraform Cloud has been successfully initialized!

You may now begin working with Terraform Cloud. Try running "terraform plan" to
see any changes that are required for your infrastructure.

If you ever set or change modules or Terraform Settings, run "terraform init"
again to reinitialize your working directory.

------------------------------------------

$ terraform plan
Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.

Preparing the remote plan...

To view this run in a browser, visit:
<REDACTED>

Waiting for the plan to start...

Terraform v1.4.4
on linux_amd64
Initializing plugins and modules...
╷
│ Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: could not parse Azure CLI version: launching Azure CLI: exec: "az": executable file not found in $PATH
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 19, in provider "azurerm":
│   19: provider "azurerm" {
│
╵
Operation failed: failed running terraform plan (exit 1)
```

Am I doing something wrong?

**Comment by MicheleMinelli** [comment]
OK if I understand correctly, what I am doing can _only_ be used for running locally. For example https://stackoverflow.com/questions/72681536/azure-cli-path-error-running-in-terraform-cloud says so.

I will try a different method, but I have to say I find the output a bit confusing.
