### ISSUE TITLE
AKS cluster fails to provision where dns_prefix has leading digit

### ISSUE THREAD

**Issue by johnswarbrick-napier** [hashicorp/terraform-provider-azurerm#20806]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.6

### AzureRM Provider Version

3.39.1

### Affected Resource(s)/Data Source(s)

module.azure_kubernetes_cluster.module.k8s.azurerm_kubernetes_cluster.k8s

### Terraform Configuration Files

```hcl
Provision a new AKS cluster where `dns_prefix` includes a leading digit.

For example: `dns_prefix = "2ndcluster"`
```

### Debug Output/Panic Output

```shell
Error: dns_prefix must contain between 2 and 45 characters. The name can contain only letters, numbers, and hyphens. The name must start with a letter and must end with an alphanumeric character.. Got "2ndcluster".

  with module.azure_kubernetes_cluster.module.k8s.azurerm_kubernetes_cluster.k8s,
  on .terraform/modules/azure_kubernetes_cluster.k8s/k8s.tf line 6, in resource "azurerm_kubernetes_cluster" "k8s":
   6:   dns_prefix                   = var.dns_prefix

Error: Process completed with exit code 1.
```

### Expected Behaviour

According to the Azure documentation, a leading digit should be permitted:

> Azure Kubernetes Service (AKS) cluster DNS prefix should meet naming requirements.
> 
> Description
> The DNS prefix for AKS clusters has different requirements then the cluster name. The requirements for DNS prefixes are:
> 
> Between 1 and 54 characters long.
> Alphanumerics and hyphens.
> **Start and end with alphanumeric.**

Ref: https://azure.github.io/PSRule.Rules.Azure/en/rules/Azure.AKS.DNSPrefix/

### Actual Behaviour

Provisioning of AKS cluster fails with fatal error

### Steps to Reproduce

1. Provision a new AKS cluster where `dns_prefix` includes a leading digit. For example: `dns_prefix = "2ndcluster"`
2. Observe the fatal error on Terraform execution

### References

I think the issue has crept in with this commit, where the validation is overly restrictive:

https://github.com/hashicorp/terraform-provider-azurerm/commit/d16b53319f484a633504f86510ba37241fef44dc

**Comment by brianobr** [comment]
An important factoid is that the original commit that implemented the validation rule referenced the portal's validation. However, the portal now allows dnsPrefix to start with a digit.

**Comment by johnswarbrick-napier** [comment]
Thank you so much @WodansSon - very much appreciated :)
