### ISSUE TITLE
Sentinel Alerts mismatched errors 

### ISSUE THREAD

**Issue by cshea15** [hashicorp/terraform-provider-azurerm#20811]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule

### Terraform Configuration Files

```hcl
// Create Sentinel MS Security Incident Alert Rule for Office 365 Advanced Threat Protection
resource "azurerm_sentinel_alert_rule_ms_security_incident" "O365_ATP" {
  name                       = "ms_security_incident_alert_rule"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  product_filter             = "Office 365 Advanced Threat Protection"
  display_name               = "MS Security Incident Alert Rule"
  severity_filter            = ["High"]
}

// Create Sentinel MS Security Incident Alert Rule for Defender Advanced Threat Protection
resource "azurerm_sentinel_alert_rule_ms_security_incident" "DATP" {
  name                       = "ms_security_incident_alert_rule"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  product_filter             = "Microsoft Defender Advanced Threat Protection"
  display_name               = "MS Security Incident Alert Rule"
  severity_filter            = ["High"]

resource "azurerm_sentinel_alert_rule_scheduled" "scheduled_alert_rule" {
  name                       = "NOBELIUM_IOCs_related_to_FoggyWeb_backdoor"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  display_name               = "NOBELIUM IOCs related to FoggyWeb backdoor"
  severity                   = "High"

// Create a new Sentinel Alert Rule for ransomware
resource "azurerm_sentinel_alert_rule_scheduled" "DNS_Domains_linked_to_WannaCry_ransomware_campaign" {
  name                       = "DNS Domains linked to WannaCry ransomware campaign"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  display_name               = "DNS Domains linked to WannaCry ransomware campaign"
  severity                   = "High"
```

### Debug Output/Panic Output

```shell
didnt run debug
```

### Expected Behaviour

Alert Rules should have been created in Sentinel

### Actual Behaviour

received an error for mismatched kind. 
Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"ms_security_incident_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MicrosoftSecurityIncidentCreation", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.AAD_IP_alerts,
│   on modules\alerts.tf line 11, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "AAD_IP_alerts":
│   11: resource "azurerm_sentinel_alert_rule_ms_security_incident" "AAD_IP_alerts" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"ms_security_incident_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MicrosoftSecurityIncidentCreation", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.DFC_alerts,
│   on modules\alerts.tf line 20, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "DFC_alerts":
│   20: resource "azurerm_sentinel_alert_rule_ms_security_incident" "DFC_alerts" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"ms_security_incident_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MicrosoftSecurityIncidentCreation", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.AATP,
│   on modules\alerts.tf line 30, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "AATP":
│   30: resource "azurerm_sentinel_alert_rule_ms_security_incident" "AATP" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"ms_security_incident_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MicrosoftSecurityIncidentCreation", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.O365_ATP,
│   on modules\alerts.tf line 48, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "O365_ATP":
│   48: resource "azurerm_sentinel_alert_rule_ms_security_incident" "O365_ATP" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"ms_security_incident_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MicrosoftSecurityIncidentCreation", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.DATP,
│   on modules\alerts.tf line 57, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "DATP":
│   57: resource "azurerm_sentinel_alert_rule_ms_security_incident" "DATP" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"mlbeavior_analytics_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MLBehaviorAnalytics", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_machine_learning_behavior_analytics.mlba_alert_rule,
│   on modules\alerts.tf line 66, in resource "azurerm_sentinel_alert_rule_machine_learning_behavior_analytics" "mlba_alert_rule":
│   66: resource "azurerm_sentinel_alert_rule_machine_learning_behavior_analytics" "mlba_alert_rule" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"mlanomalous_ssh_login_detection_alert_rule\")": Sentinel Alert Rule has mismatched kind, expected: "MLBehaviorAnalytics", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_machine_learning_behavior_analytics.mlad_alert_rule,
│   on modules\alerts.tf line 74, in resource "azurerm_sentinel_alert_rule_machine_learning_behavior_analytics" "mlad_alert_rule":
│   74: resource "azurerm_sentinel_alert_rule_machine_learning_behavior_analytics" "mlad_alert_rule" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"NOBELIUM_IOCs_related_to_FoggyWeb_backdoor\")": Sentinel Alert Rule has mismatched kind, expected: "Scheduled", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_scheduled.scheduled_alert_rule,
│   on modules\alerts.tf line 82, in resource "azurerm_sentinel_alert_rule_scheduled" "scheduled_alert_rule":
│   82: resource "azurerm_sentinel_alert_rule_scheduled" "scheduled_alert_rule" {
│
╵
╷
│ Error: asserting alert rule of "Alert Rule (Subscription: \"9e087dff-9c5b-4650-96ee-19cfe5269c5d\"\nResource Group Name: \"rg-law-sentinel-eastus\"\nWorkspace Name: \"law-sentinel-eastus\"\nRule: \"DNS Domains linked to WannaCry ransomware campaign\")": Sentinel Alert Rule has mismatched kind, expected: "Scheduled", got ""
│
│   with module.modules.azurerm_sentinel_alert_rule_scheduled.DNS_Domains_linked_to_WannaCry_ransomware_campaign,
│   on modules\alerts.tf line 211, in resource "azurerm_sentinel_alert_rule_scheduled" "DNS_Domains_linked_to_WannaCry_ransomware_campaign":
│  211: resource "azurerm_sentinel_alert_rule_scheduled" "DNS_Domains_linked_to_WannaCry_ransomware_campaign" {
### Steps to Reproduce

terraform init
terraform apply

**Comment by cshea15** [comment]
@ziyeqf

**Comment by ziyeqf** [comment]
Hi @cshea15, thanks for reporting.

I have reproduced the same error, and opened an issue (https://github.com/hashicorp/go-azure-sdk/issues/354) on go-azure-sdk. I will keep looking into it.

Thanks!

**Comment by ziyeqf** [comment]
the PR (https://github.com/hashicorp/go-azure-sdk/issues/354) has been merged, after the new version released it should be fixed. :)

**Comment by tombuildsstuff** [comment]
@ziyeqf support for that shipped in [v0.20230309.1123256](https://github.com/hashicorp/go-azure-sdk/releases/tag/v0.20230309.1123256) which was vendored into the provider in #20810 and released in v3.47.0 FYI: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3470-march-09-2023

**Comment by cshea15** [comment]
@ziyeqf looks like the fix worked. No longer getting that error and able to deploy alerts. I did get an already exists error but bug seems to be fixed.

╷
│ Error: A resource with the ID "/subscriptions/9e087dff-9c5b-4650-96ee-19cfe5269c5d/resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus-1/providers/Microsoft.SecurityInsights/alertRules/ms_security_incident_alert_rule" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_alert_rule_ms_security_incident" for more information.
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.DFC_alerts,
│   on modules\alerts.tf line 20, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "DFC_alerts":
│   20: resource "azurerm_sentinel_alert_rule_ms_security_incident" "DFC_alerts" {
│
╵

**Comment by ziyeqf** [comment]
Hi @cshea15, glad to hear that. Do you mind closing this issue and we can track the "already exists" error in https://github.com/hashicorp/terraform-provider-azurerm/issues/20812. 

Thanks!
