### ISSUE TITLE
Sentinel Alerts and Data Connectors "already exists" error

### ISSUE THREAD

**Issue by cshea15** [hashicorp/terraform-provider-azurerm#20812]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel

### Terraform Configuration Files

```hcl
// Create Data Connector for Azure Active Directory
resource "azurerm_sentinel_data_connector_azure_active_directory" "aad" {
  name                       = "azure_active_directory"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
}

resource "azurerm_sentinel_data_connector_azure_security_center" "dfc" {
  name                       = "azure_security_center"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  subscription_id            = var.sub_id
}
resource "azurerm_sentinel_data_connector_microsoft_cloud_app_security" "microsoft_cloud_app_security" {
  name                       = "microsoft_cloud_app_security"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
}

resource "azurerm_sentinel_alert_rule_ms_security_incident" "CAS" {
  name                       = "ms_security_incident_alert_rule"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  product_filter             = "Microsoft Cloud App Security"
  display_name               = "MS Security Incident Alert Rule"
  severity_filter            = ["High"]
}

resource "azurerm_sentinel_alert_rule_fusion" "fusion_alert_rule" {
  name                       = "fusion_alert_rule"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
  alert_rule_template_guid   = "f71aba3d-28fb-450b-b192-4e76a83015c8"
  enabled                    = true
}
```

### Debug Output/Panic Output

```shell
didnt run debug
```

### Expected Behaviour

Connectors and Alerts should have been deployed. 

### Actual Behaviour

Get an error that these already exist but this is a fresh deployment, creating a new log analytics, rules, and connectors. 

│ Error: A resource with the ID "/subscriptions//resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus/providers/Microsoft.SecurityInsights/alertRules/fusion_alert_rule" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_alert_rule_fusion" for more information.
│
│   with module.modules.azurerm_sentinel_alert_rule_fusion.fusion_alert_rule,
│   on modules\alerts.tf line 3, in resource "azurerm_sentinel_alert_rule_fusion" "fusion_alert_rule":
│    3: resource "azurerm_sentinel_alert_rule_fusion" "fusion_alert_rule" {

│ Error: A resource with the ID "/subscriptions/resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus/providers/Microsoft.SecurityInsights/alertRules/ms_security_incident_alert_rule" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_alert_rule_ms_security_incident" for more information.
│
│   with module.modules.azurerm_sentinel_alert_rule_ms_security_incident.CAS,
│   on modules\alerts.tf line 39, in resource "azurerm_sentinel_alert_rule_ms_security_incident" "CAS":
│   39: resource "azurerm_sentinel_alert_rule_ms_security_incident" "CAS" {
│

│ Error: A resource with the ID "/subscriptions//resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus/providers/Microsoft.SecurityInsights/dataConnectors/azure_active_directory" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_data_connector_azure_active_directory" for more information.
│
│   with module.modules.azurerm_sentinel_data_connector_azure_active_directory.aad,
│   on modules\connectors.tf line 26, in resource "azurerm_sentinel_data_connector_azure_active_directory" "aad":
│   26: resource "azurerm_sentinel_data_connector_azure_active_directory" "aad" {

│ Error: A resource with the ID "/subscriptions//resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus/providers/Microsoft.SecurityInsights/dataConnectors/azure_security_center" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_data_connector_azure_security_center" for more information.
│
│   with module.modules.azurerm_sentinel_data_connector_azure_security_center.dfc,
│   on modules\connectors.tf line 19, in resource "azurerm_sentinel_data_connector_azure_security_center" "dfc":
│   19: resource "azurerm_sentinel_data_connector_azure_security_center" "dfc" {

 Error: A resource with the ID "/subscriptions//resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus/providers/Microsoft.SecurityInsights/dataConnectors/azure_active_directory" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_data_connector_azure_active_directory" for more information.
│
│   with module.modules.azurerm_sentinel_data_connector_azure_active_directory.aad,
│   on modules\connectors.tf line 26, in resource "azurerm_sentinel_data_connector_azure_active_directory" "aad":
│   26: resource "azurerm_sentinel_data_connector_azure_active_directory" "aad" {
│
╵
╷
│ Error: A resource with the ID "//resourceGroups/rg-law-sentinel-eastus/providers/Microsoft.OperationalInsights/workspaces/law-sentinel-eastus/providers/Microsoft.SecurityInsights/dataConnectors/microsoft_cloud_app_security" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sentinel_data_connector_microsoft_cloud_app_security" for more information.
│
│   with module.modules.azurerm_sentinel_data_connector_microsoft_cloud_app_security.microsoft_cloud_app_security,
│   on modules\connectors.tf line 33, in resource "azurerm_sentinel_data_connector_microsoft_cloud_app_security" "microsoft_cloud_app_security":
│   33: resource "azurerm_sentinel_data_connector_microsoft_cloud_app_security" "microsoft_cloud_app_security" {

### Steps to Reproduce

terraform init
terraform apply

**Comment by cshea15** [comment]
@ziyeqf

**Comment by ziyeqf** [comment]
Hi @cshea15, 

Could you please provide some more detail of the config and check if there is any mentioned resource exists in your Work Space on Portal?

I have tried `azurerm_sentinel_alert_rule_fusion` and `azurerm_sentinel_alert_rule_ms_security_incident`, they could be succesfully deployed.  I assume there is some conflicts with other resource.

Btw, it's suggested to remove the subscription id in log.

**Comment by cshea15** [comment]
Yes i added the solution and onboarding for the workspace. This is the only sentinel law being deployed. 


resource "azurerm_log_analytics_workspace" "law" {
  name                = "law-${var.prefix}-${var.resource_location}"
  location            = azurerm_resource_group.rg_law.location
  resource_group_name = azurerm_resource_group.rg_law.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "law_solution" {
  solution_name         = "SecurityInsights"
  location              = azurerm_resource_group.rg_law.location
  resource_group_name   = azurerm_resource_group.rg_law.name
  workspace_resource_id = azurerm_log_analytics_workspace.law.id
  workspace_name        = azurerm_log_analytics_workspace.law.name
  tags                  = azurerm_resource_group.rg_law.tags

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/SecurityInsights"
  }
}

// Create resource to onboard Sentinel to Log Analytics Workspace
resource "azurerm_sentinel_log_analytics_workspace_onboarding" "law_onboarding" {
  resource_group_name        = azurerm_resource_group.rg_law.name
  workspace_name             = azurerm_log_analytics_workspace.law.name
}

**Comment by cshea15** [comment]
Update!

I removed the terraform.lock.hcl, terraform.tfstate, and .terraform files. redeployed and still getting the already exists error but now getting this error as well.

│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.modules.azurerm_sentinel_data_connector_azure_advanced_threat_protection.aad_advanced_threat_protection, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵


│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.modules.azurerm_sentinel_data_connector_azure_active_directory.aad, provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

**Comment by ziyeqf** [comment]
Hi @cshea15 ,

as far as I know, there is no need to use both `azurerm_log_analytics_solution` and `azurerm_sentinel_log_analytics_workspace_onboarding` toghter, they are both onboard the workspace to Sentinel. And I may suggest to use `azurerm_sentinel_log_analytics_workspace_onboarding` and add `depend_on = [azurerm_sentinel_log_analytics_workspace_onboarding.law_onboarding]` for dataconnectors and alert rules.

And thanks for your update, will look into it.

**Comment by cshea15** [comment]
@ziyeqf I deployed just a resource group, law, and the law onboarding resources and it deployed out but weirdly it had connectors and alerts created even though I did not deploy those resources. Not sure if you seen that before.

**Comment by ziyeqf** [comment]
Hi @cshea15, as mentioned in https://github.com/hashicorp/terraform-provider-azurerm/issues/20811#issuecomment-1459280514, the error `Sentinel Alert Rule has mismatched kind` will be fixed with this [PR](https://github.com/hashicorp/pandora/pull/2200).  

For the `existing` error, could you please give it another try with setting the environmental variable `TF_LOG=DEBUG` and providing the log here? Also you can set `TF_LOG_PATH` toghter to save the logs to a file. [reference](https://developer.hashicorp.com/terraform/internals/debugging)

**Comment by cshea15** [comment]
[tfbug.log](https://github.com/hashicorp/terraform-provider-azurerm/files/10924420/tfbug.log)


Here is the log, hope i ran it correctly.

**Comment by ziyeqf** [comment]
Hi @cshea15, could you please run it again and provide the log file after the `mismatch` bug fixed?

**Comment by cshea15** [comment]
Will do, thank you

**Comment by cshea15** [comment]
[tfbug.log](https://github.com/hashicorp/terraform-provider-azurerm/files/10957463/tfbug.log)

**Comment by ziyeqf** [comment]
Hi @cshea15, per the log file. it seems there are 3 different alert rules sharing a same `name`

Every `alert rule` should have a different `name`.  Please rename them and it should work as expect.

For further questions please leave comments.
Thanks!

**Comment by cshea15** [comment]
@ziyeqf shouldn't Terraform see that it's creating multiple alerts with all different Product Filters, and the naming shouldn't matter?

**Comment by ziyeqf** [comment]
> @ziyeqf shouldn't Terraform see that it's creating multiple alerts with all different Product Filters, and the naming shouldn't matter?

@cshea15 Terraform was trying to create different alerts, while the name does matter because they are all sentinel alert rules. 

Technically, It's because of the id of Azure resources, `name` is a part of the resource id, and id of (almost) all sentinel alert rules are in same format:
```
/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/{resource_group_name}/providers/Microsoft.OperationalInsights/workspaces/{work_space_name}/providers/Microsoft.SecurityInsights/alertRules/{alert_rule_name}
```
so if two alert rules share a same name in a same log analytics workspace, they will get a same id, the first created alert rule will be created successfully then the second one will get `already exist` error comes out.
