### ISSUE TITLE
Support for `network_interface` on `azurerm_kubernetes_cluster_node_pool`

### ISSUE THREAD

**Issue by tkellen** [hashicorp/terraform-provider-azurerm#20814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to support the `network_interface` block used by `azurerm_linux_virtual_machine_scale_set` on the `azurerm_kubernetes_cluster_node_pool` resource which creates a virtual machine scale set under the hood? It would be nice to be able to associate the VMs in a node pool with a load balancer the same way you can with a scale set.

The use case for this is a desire to manually create a single load balancer that is backed by a NodePort service for a class of "routing" nodes running an ingress controller. At the moment the only workaround I can come up with is creating a routing subnet that is relatively small and associating every IP in it with the load balancer such that if VMs in the node group come and go they are recognized by the load balancer as a valid backend.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
...
  node_network_interface {
    ...
    ip_configuration {
      load_balancer_backend_address_pool_ids = [...]
    }
  }
}
```

**Comment by tkellen** [comment]
Thank you! I've raised that here:
https://github.com/Azure/AKS/issues/3512

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now. When it gets added, we can reopen this request or you can create a new one.
https://github.com/Azure/AKS/issues/3512
