### ISSUE TITLE
azurerm_monitor_diagnostic_setting for a VNet integrated storage account errors with "already created"

### ISSUE THREAD

**Issue by MarcBuch** [hashicorp/terraform-provider-azurerm#20828]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting tied to azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                = "mystorageaccount"
  resource_group_name = azurerm_resource_group.this.name
  location            = "westeurope"

  account_tier                  = "Standard"
  account_replication_type      = "LRS"
  public_network_access_enabled = false
}

resource "azurerm_private_endpoint" "this" {
  for_each            = toset(["blob", "file", "dfs"])
  name                = "pe-${each.key}-${azurerm_storage_account.this.name}"
  resource_group_name = azurerm_resource_group.this.name
  location            = "westeurope"

  subnet_id = var.subnet_id
  private_service_connection {
    name                           = "psc-${azurerm_storage_account.this.name}"
    private_connection_resource_id = azurerm_storage_account.this.id

    # Storage Account only supports one subresource name
    subresource_names    = [each.key]
    is_manual_connection = false
  }

  # Ignore changes to DNS settings for private Endpoint
  lifecycle {
    ignore_changes = [
      private_dns_zone_group
    ]
  }
}

resource "azurerm_monitor_diagnostic_setting" "this" {
  name                       = "mds-${azurerm_storage_account.this.name}"
  target_resource_id         = "${azurerm_storage_account.this.id}/blobServices/default"
  log_analytics_workspace_id = var.log_analytics_workspace_id

  enabled_log {
    category = "StorageRead"
    retention_policy {
      enabled = false

    }
  }
```

### Debug Output/Panic Output

```shell
Error: A resource with the ID "/subscriptions/xxxx-xxxx-xxxx-xxxx/resourceGroups/my-rg/providers/Microsoft.Storage/storageAccounts/mystorageaccount/blobServices/default|mds-mystorageaccount" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
```

### Expected Behaviour

Terraform creates the azurerm_monitor_diagnostic_setting resource and adds it to the state. Right now, after deleting it manually and running `terraform apply` again, it is created and added to the state.

### Actual Behaviour

azurerm_monitor_diagnostic_setting resource is created and visible in the Azure portal, but it is not in the state.

### Steps to Reproduce

The agent to be used for Terraform apply should be in the same VNet as the private Endpoint of the storage account.

**Comment by MarcBuch** [comment]
I have not yet run Terraform apply in verbose, to check if this is caused by the Azure API.

**Comment by teowa** [comment]
Hi @MarcBuch, this may related to https://github.com/hashicorp/terraform-provider-azurerm/issues/19706#issuecomment-1354466607 and https://github.com/hashicorp/terraform-provider-azurerm/issues/11076#issuecomment-963092635, please have a look if these can help. 
Thanks.
