### ISSUE TITLE
azurerm_cdn_endpoint_custom_domain cannot find endpoint id

### ISSUE THREAD

**Issue by pergeri** [hashicorp/terraform-provider-azurerm#20827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_endpoint_custom_domain azurerm_cdn_endpoint

### Terraform Configuration Files
So we've tried a few different configurations in order to get the custom domain to use the correct endpoint ID
```hcl
resource "azurerm_cdn_endpoint_custom_domain" "name-here" {
  name            = "another-name-here"
  cdn_endpoint_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Cdn/profiles/profile1/endpoints/endpoint1/"
  host_name       = "this.host.name"
}
``` 

```hcl
resource "azurerm_cdn_endpoint_custom_domain" "name-here" {
  name            = "another-name-here"
  cdn_endpoint_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Cdn/profiles/profile1/afdEndpoints/endpoint1/"
  host_name       = "this.host.name"
}
```

```hcl
resource "azurerm_cdn_endpoint_custom_domain" "name-here" {
  name            = "another-name-here"
  cdn_endpoint_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Cdn/profiles/profile1/afdendpoints/endpoint1/"
  host_name       = "this.host.name"
}
```

```hcl
data "azurerm_cdn_frontdoor_endpoint" "the-endpoint" {
  name                = "endpoint-name"
  profile_name        = "profile-name"
  resource_group_name = "resource-group"
}

resource "azurerm_cdn_endpoint_custom_domain" "name-here" {
  name            = "another-name-here"
  cdn_endpoint_id = data.azurerm_cdn_frontdoor_endpoint.the-endpoint.id
  host_name       = "this.host.name"
}

```

### Debug Output/Panic Output

```shell
---
```

### Expected Behaviour

Domain name should be associated with `the-endpoint` 

### Actual Behaviour

Different errors depending on configuration, errors in same order as configs: 
```
Error: creating "Custom Domain: (Name \"name-here\" / Endpoint Name \"endpoint-name\" / Profile Name \"profile-name\" / Resource Group \"resource-group\")": cdn.CustomDomainsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'profile-name/endpoint-name' not found."
```
```
Error: ID was missing the `endpoints` element
with azurerm_cdn_endpoint_custom_domain.name-here
on file.tf line xxx, in resource "azurerm_cdn_endpoint_custom_domain" "name-here":
```
```
Error: ID was missing the `endpoints` element
with azurerm_cdn_endpoint_custom_domain.name-here
on file.tf line xxx, in resource "azurerm_cdn_endpoint_custom_domain" "name-here":
```
```
Error: ID was missing the `endpoints` element
with azurerm_cdn_endpoint_custom_domain.name-here
on file.tf line xxx, in resource "azurerm_cdn_endpoint_custom_domain" "name-here":
```

### Steps to Reproduce

Try any of the above configurations.

**Comment by WodansSon** [comment]
@pergeri, it looks like you might be using the incorrect resource in your configuration file here? There are two resources in the `CDN` namespace/package for `endpoints`. The `CDN Front Door` endpoint (e.g. `azurerm_cdn_frontdoor_endpoint`) and the `CDN` endpoint (e.g. `azurerm_cdn_endpoint`), which I understand is incredibly confusing and out of my control. That said, if you look at the [resourceids.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/cdn/resourceids.go) file in source, you will see that the resource ids for each of these resources are defined correctly:  

```go
//go:generate go run ../../tools/generator-resource-id/main.go -path=./ -name=Endpoint -rewrite=true -id=/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Cdn/profiles/profile1/endpoints/endpoint1
//go:generate go run ../../tools/generator-resource-id/main.go -path=./ -name=FrontDoorEndpoint -id=/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Cdn/profiles/profile1/afdEndpoints/endpoint1 -rewrite=true
```

The `azurerm_cdn_endpoint_custom_domain` needs to reference an `azurerm_cdn_endpoint`, but the `azurerm_cdn_frontdoor_route` resource needs to reference an `azurerm_cdn_frontdoor_endpoint`. It is not clear to me from the description in the issue which one of these resources you are attempting to create. Base on your follow up comment:

>According to az afd endpoint list -g resource-group --profile-name profile-name
the id should be in this format:
>
>/subscriptions/{SUBSCRIPTION-ID}/resourcegroups/{RESOURCEGROUP}/providers/Microsoft.Cdn/profiles/{PROFILE-NAME}/afdendpoints/{ENDPOINT-NAME}
>
>Which we've tried.
>
>But it seems the resource expects the 'url' to be /endpoints/ and not /afdendpoints/

I think you are trying to create a `CDN Front Door` resouce?

**Comment by pergeri** [comment]
Well I'll be damned, thank you! I'll close this.
