### ISSUE TITLE
Expose customDomainVerificationId from azurerm_container_app_environment

### ISSUE THREAD

**Issue by WolfspiritM** [hashicorp/terraform-provider-azurerm#20829]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Even so not correctly documented the container app environment with latest version reports the "customDomainVerificationId".

The documentation issue is mentioned here:
https://github.com/microsoft/azure-container-apps/issues/648

This property is required to generate a custom domain for an app while creating the app. At the moment I have to use azapi for Microsoft.App/managedEnvironments to get that value cause otherwise I can't create an App.

It would be nice if this value could be exposed to azurerm so a domain validation dns record can be created

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app_environment" "example" {
  name                       = "my-environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}

resource "azurerm_dns_a_record" "test" {
  name                = "test"
  zone_name           = azurerm_dns_zone.test-zone.name
  resource_group_name = azurerm_resource_group.test.name
  ttl                 = 300
  records             = [azurerm_container_app_environment.example.custom_domain_verification_id]
}
```

### References

https://github.com/microsoft/azure-container-apps/issues/648

**Comment by xente** [comment]
Hi @WolfspiritM, I am using the workarround proposed by  @faheemgani.

You can check It here: https://link.medium.com/GKtORvcRWzb

**Comment by WolfspiritM** [comment]
> Hi @WolfspiritM, I am using the workarround proposed by @faheemgani.
> 
> You can check It here: https://link.medium.com/GKtORvcRWzb

Thanks. However I don't see a difference to what I've already proposed in my post?
`At the moment I have to use azapi for Microsoft.App/managedEnvironments to get that value cause otherwise I can't create an App`
