### ISSUE TITLE
env variable `ARM_SUBSCRIPTION_ID` not working as expected with provider

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-azurerm#20832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Based on the [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#subscription_id), the provider should recognize the subscription ID by either setting the `subscription_id` attribute as part of the provider block or exporting the id with `export ARM_SUBSCRIPTION_ID=""`

When using the export method the following error appears, at first I thought it was a subscription issue but when entering the same id into the `subscription_id` attribute it works as expected.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

provider "azurerm"

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}     
}

variable "location" {
  type = string
  default = "West US"
}

variable "node_count" {
  type = number
  default = 2
}

variable "vm_size" {
  type = string
  default = "Standard_A4_v2"
}

variable "kubernetes_version" {
  type = string
  default = "1.25.5"
}

resource "random_pet" "name" {}

resource "azurerm_resource_group" "test_group" {
  name     = "test-aks-${random_pet.name.id}"
  location = var.location
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "test-aks-${random_pet.name.id}"
  location            = azurerm_resource_group.test_group.location
  resource_group_name = azurerm_resource_group.test_group.name
  dns_prefix          = "test"
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    name       = "default"
    node_count = var.node_count
    vm_size    = var.vm_size
    //vm_size    = "Standard_A4_v2"
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "local_file" "kubeconfig" {
  content  = azurerm_kubernetes_cluster.test.kube_config_raw
  filename = "${path.module}/kubeconfig"
}

output "kubeconfig" {
  value = azurerm_kubernetes_cluster.test.kube_config_raw

  sensitive = true
}

output "cluster_name" {
  value = "test-aks-${random_pet.name.id}"
}
```

### Debug Output/Panic Output

```shell
➜  aks-new git:(aks-gha) ✗ tfp
random_pet.name: Refreshing state... [id=in-pangolin]
╷
│ Error: building account: unable to configure ResourceManagerAccount: subscription ID could not be determined and was not specified
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
│
╵
```

### Expected Behaviour

The export method for subscription ID should work the same as using the `subscription_id` attribute in the provider block

### Actual Behaviour

the following Error output appears

### Steps to Reproduce

`terraform plan`

**Comment by myc2h6o** [comment]
Hi @BBBmau thanks for opening the issue! I'm not able to conclude the root cause from the given information. Would you mind capturing the debug log with `export TF_LOG="DEBUG"`? It includes more details which may be helpful with troubleshooting.

**Comment by BBBmau** [comment]
The following is what's outputted after running `TF_LOG=debug terraform plan`

https://gist.github.com/BBBmau/5bb3fb36f418c0793795922c5e5bb7a4

**Comment by myc2h6o** [comment]
The debug log doesn't contain helpful info as well unfortunately, and I'm able to run it successfully with the given config. The one possible cause I could think of is an explicit `subscription_id = ""` in the provider block, would you mind double checking that's not the case?

Below is another test I made in my env, hope this help with the troubleshooting:
```
> cat main.tf
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "eastus"
}
```
```
> export ARM_CLIENT_ID="<client_id>"
> export ARM_CLIENT_SECRET="<client_secret>"
> export ARM_TENANT_ID="<tenant_id>"
> export ARM_SUBSCRIPTION_ID="<subscription_id>"
> terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_resource_group.test will be created
  + resource "azurerm_resource_group" "test" {
      + id       = (known after apply)
      + location = "eastus"
      + name     = "test"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

```
> terraform -version
Terraform v1.3.9
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.46.0
+ provider registry.terraform.io/hashicorp/local v2.4.0
+ provider registry.terraform.io/hashicorp/random v3.4.3

> lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.1 LTS
Release:        22.04
```

**Comment by BBBmau** [comment]
Hello! Just wanted to reply about how it wasn't in fact a provider issue but due to an authentication issue. Thank you again for the help!
