### ISSUE TITLE
expected os_disk.0.disk_size_gb to be in the range (0 - 4095)

### ISSUE THREAD

**Issue by lg-gulpdata** [hashicorp/terraform-provider-azurerm#20850]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "my_terraform_vm" {
  name                            = "gulp-summary-vm"
  location                        = azurerm_resource_group.rg.location
  resource_group_name             = azurerm_resource_group.rg.name
  network_interface_ids           = [azurerm_network_interface.my_terraform_nic.id]
  size                            = var.vm_size
  computer_name                   = "gulp-summary-vm"
  admin_username                  = "gulp-user"
  disable_password_authentication = true

  os_disk {
    name                 = "summary-disk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = "8192"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts"
    version   = "latest"
  }

  admin_ssh_key {
    username   = "gulp-user"
    public_key = tls_private_key.example_ssh.public_key_openssh
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: expected os_disk.0.disk_size_gb to be in the range (0 - 4095), got 8192
│ 
│   with azurerm_linux_virtual_machine.my_terraform_vm,
│   on main.tf line 90, in resource "azurerm_linux_virtual_machine" "my_terraform_vm":
│   90:     disk_size_gb         = var.vm_disk_size
```

### Expected Behaviour

create a vm with a disk of 8T

### Actual Behaviour

Error
expected os_disk.0.disk_size_gb to be in the range (0 - 4095), got 8192

### Steps to Reproduce

terraform apply

**Comment by myc2h6o** [comment]
Hi @lg-gulpdata this is a limitation from Azure https://learn.microsoft.com/en-us/azure/virtual-machines/managed-disks-overview#os-disk The maximum size of an OS Disk is 4 GB

**Comment by manicminer** [comment]
Thanks for opening this issue. Since this resource seems to be working as expected, within the limitations of the Azure service, I'm going to close this issue for now. If you believe there is something to be fixed in the provider here, please comment further and we'll be happy to take another look. Thanks!
