### ISSUE TITLE
Terraform removes origin_host_header in `azurerm_cdn_frontdoor_origin` and breaks origin

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#20866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

azurerm_cdn_frontdoor_origin

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_origin

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_origin" "globalstorage-primary" {
  name      = "primary"
  host_name = azurerm_storage_account.global.primary_web_host

  http_port  = 80
  https_port = 443
  weight     = 50
  priority   = 1

  enabled                        = true
  certificate_name_check_enabled = true

  origin_host_header = azurerm_storage_account.global.primary_web_host

  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.globalstorage.id
}
```

### Debug Output/Panic Output

```shell
# azurerm_cdn_frontdoor_origin.backendapi["mcintbb7b-cluster.australiaeast.cloudapp.azure.com"] will be updated in-place
  ~ resource "azurerm_cdn_frontdoor_origin" "backendapi" {
        id                             = "/subscriptions/c6f6607e-3975-44fc-b0c1-2dd79dd158b9/resourceGroups/mcint-global-rg/providers/Microsoft.Cdn/profiles/mcint-global-fd/originGroups/BackendApis/origins/mcintbb7b-cluster-australiaeast-cloudapp-azure-com"
        name                           = "mcintbb7b-cluster-australiaeast-cloudapp-azure-com"
      ~ weight                         = 51 -> 50
        # (9 unchanged attributes hidden)
    }
```

### Expected Behaviour

TF must not silently change attributes

### Actual Behaviour

**This is a very serious bug**

Terraform removes the `origin_host_header` on a `azurerm_cdn_frontdoor_origin` while doing some unrelated apply operation. See my example below. I had manually changed the weight to 51 (in the portal), so TF correctly wants to set this to 50. But in the process it silently removes the origin host header, and thereby breaking the origin in Front Door.

@WodansSon I believe you recently changed something around this, I assume this is a regression from that https://github.com/hashicorp/terraform-provider-azurerm/pull/20679

Before:
![image](https://user-images.githubusercontent.com/11445087/224023728-70fe59b2-4516-4de8-9db0-0d64745855fb.png)

After:
![image](https://user-images.githubusercontent.com/11445087/224023762-aadeabd2-385f-4575-933c-3f448a6a3fea.png)

### Steps to Reproduce

See above

**Comment by WodansSon** [comment]
@sebader, thank you for opening this issue. Yes this is a regression related to exposing the functionality to remove/unset the `origin_host_header` value. By enabling that functionality I inadvertently also caused this issue where if the `origin_host_header` value was not changed during an update operation it would be removed since the value would be `null`. 🚀
