### ISSUE TITLE
unable to create azurerm_bot_channel_directline 

### ISSUE THREAD

**Issue by guptaaayush8** [hashicorp/terraform-provider-azurerm#20892]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.1

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_bot_channel_directline

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-bot-test07"
  location = "eastus2"
}

resource "azurerm_user_assigned_identity" "example" {
  location            = azurerm_resource_group.test.location
  name                = "example"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_bot_channels_registration" "test" {
  name                = "acctestdftest07"
  location            = "global"
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "F0"
  microsoft_app_id    = resource.azurerm_user_assigned_identity.example.client_id
}

resource "azurerm_bot_channel_directline" "test" {
  bot_name            = azurerm_bot_channels_registration.test.name
  location            = azurerm_bot_channels_registration.test.location
  resource_group_name = azurerm_resource_group.test.name
  
  site {
    name    = "SomeSite"
    enabled = true
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Directline Channel for Bot "acctestdftest07" (Resource Group "acctestRG-bot-test07"): botservice.ChannelsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Site Name  Duplicate" Message="DirectLine Channel site name duplicate"
```

### Expected Behaviour

DirectLine channel site should get created.

### Steps to Reproduce

1. terraform init
2. terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. This PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/20890) is fixing this issue.
