### ISSUE TITLE
Key vault service doesn't have proper permissions to access the storage account for azurerm_key_vault_managed_storage_account

### ISSUE THREAD

**Issue by subhranil05** [hashicorp/terraform-provider-azurerm#20907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

v3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_client_config, azuread_service_principal

### Terraform Configuration Files

```hcl
data "azurerm_client_config" "current" {}


data "azuread_service_principal" "test" {
  # display_name = "Azure Key Vault"
  application_id = "id"
}

resource "azurerm_resource_group" "example" {
  name     = "key-vault-managed-sa1001"
  location = "East US"
}

resource "azurerm_storage_account" "example" {
  name                     = "keyvaultmanagedsa1001"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  is_hns_enabled           = true
}

resource "azurerm_key_vault" "example" {
  name                = "key-vaultmanaged-sa1001"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    secret_permissions = [
      "Get",
      "Delete"
    ]

    storage_permissions = [
      "Get",
      "List",
      "Set",
      "SetSAS",
      "GetSAS",
      "DeleteSAS",
      "Update",
      "RegenerateKey"
    ]
  }
}

resource "azurerm_role_assignment" "example" {
  scope                = azurerm_storage_account.example.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id         = data.azuread_service_principal.test.id
}

resource "azurerm_key_vault_managed_storage_account" "example" {
  name                         = "examplemanagedstorage"
  key_vault_id                 = azurerm_key_vault.example.id
  storage_account_id           = azurerm_storage_account.example.id
  storage_account_key          = "key1"
  regenerate_key_automatically = true
  regeneration_period          = "P1D"

  depends_on = [
    azurerm_role_assignment.example,
  ]
}
```

### Debug Output/Panic Output

```shell
Error: creating Managed Storage Account examplemanagedstorage: keyvault.BaseClient#SetStorageAccount: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Key vault service doesn't have proper permissions to access the storage account https://key-vaultmanaged-sa1001.vault.azure.net/storage/examplemanagedstorage"
│ 
│   with azurerm_key_vault_managed_storage_account.example,
│   on main.tf line 75, in resource "azurerm_key_vault_managed_storage_account" "example":
│   75: resource "azurerm_key_vault_managed_storage_account" "example" {
```

### Actual Behaviour

Azure key vault is not having proper access to storage account during the creation of key vault managed storage account.

Error: creating Managed Storage Account examplemanagedstorage: keyvault.BaseClient#SetStorageAccount: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Key vault service doesn't have proper permissions to access the storage account https://key-vaultmanaged-sa1001.vault.azure.net/storage/examplemanagedstorage"

### Steps to Reproduce

set the configuration as it is,
terraform apply

### References

the service principle I'm using having owner role to subscription scope.
Please guide me to fix the issue.

**Comment by aristosvo** [comment]
Hey @subhranil05 👋!

I believe this is the solution:
```hcl

provider "azuread" {}

data "azuread_service_principal" "test" {
  # https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys-powershell#service-principal-application-id
  # application_id = "cfa8b339-82a2-471a-a3c9-0fc0be7a4093"
  display_name = "Azure Key Vault"
}

resource "azurerm_role_assignment" "test" {
  scope                = azurerm_storage_account.test.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id         = data.azuread_service_principal.test.id
}
```

**Comment by subhranil05** [comment]
@aristosvo thanks for your reply.
I have tried it. But same issue with me

`data "azuread_service_principal" "test" {
  # https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys-powershell#service-principal-application-id
  # application_id = "5ce76c5a-6e82-4a02-8cfe-762c3483ae23"
  display_name = "subhterraform001"
}
resource "azurerm_role_assignment" "example" {
  scope                = azurerm_storage_account.example.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id         = data.azuread_service_principal.test.id
}`
Is it mandatory to keep display name as "Azure Key Vault" ? It is the only thing I have changed here

**Comment by subhranil05** [comment]
@aristosvo thanks for your reply.
I have tried it. But same issue with me

```
data "azuread_service_principal" "test" {

  # https://docs.microsoft.com/en-us/azure/key-vault/secrets/overview-storage-keys-powershell#service-principal-application-id
  # application_id = "5ce76c5a-6e82-4a02-8cfe-762c3483ae23"
  display_name = "subhterraform001"
}
resource "azurerm_role_assignment" "example" {
  scope = azurerm_storage_account.example.id
  role_definition_name = "Storage Account Key Operator Service Role"
  principal_id = data.azuread_service_principal.test.id
}
```
Is it mandatory to keep display name as "Azure Key Vault" ? It is the only thing I have changed here

**Comment by aristosvo** [comment]
That is the problem then. 

You don't need to create your own service principal. It is using a service principal for Azure Key Vault, and as such present in every tenant under the same name (and same id if you're using Azure public: `cfa8b339-82a2-471a-a3c9-0fc0be7a4093`)

**Comment by subhranil05** [comment]
@aristosvo yes you are right. Now it is created. We don't have to create any service principle ,it is already given on the docs 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_managed_storage_account
I have wasted time thinking it is only a data source example of service principle.
Have a request --  can this point about service principle be specified on the doc, (url given above)?

Thank you so much for your quick help.
