### ISSUE TITLE
Error parsing ace after data lake filesystem gets created.

### ISSUE THREAD

**Issue by giskou** [hashicorp/terraform-provider-azurerm#20914]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem

### Terraform Configuration Files

```hcl
resource "azurerm_storage_data_lake_gen2_filesystem" "main" {
  name               = "foo"
  storage_account_id = "bar"

  owner = "$superuser"
  group = "$superuser"

  dynamic "ace" {
    for_each = toset(["user", "group", "other"])
    content {
      scope       = "access"
      type        = ace.value
      permissions = "rwx"
    }
  }

  dynamic "ace" {
    for_each = toset(["user", "group", "other"])
    content {
      scope       = "default"
      type        = ace.value
      permissions = "rwx"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: parsing response ACL "user::rwx,group::rws,other::rwx,default:user::rwx,default:group::rwx,default:other::rwx": Permissions must be of the form [r-][w-][x-]
```

### Expected Behaviour

After creation, subsequent plan/apply should just work showing no changes to the actual infrastructure.

### Actual Behaviour

Creating works, but trying a plan afterwards shows the error above.

Note the `group::rws`. It looks like azure sets this somehow and the provider has issues parsing it while reading the resource.

### Steps to Reproduce

terraform apply
terraform plan/apply

**Comment by giskou** [comment]
I have more info on how this `s` ends up being there.
We are using this container as a PV in a kubernetes cluster with the blob csi driver.

The pod that mounts this is using fsGroup, so kubelet will do a chown and set the group ID to another user (1000 in our case) and the set_gid flag ends up there.

**Comment by myc2h6o** [comment]
Hi @giskou thanks for raising the issue! From the official document https://learn.microsoft.com/azure/storage/blobs/data-lake-storage-access-control#levels-of-permission only r,w,x, are possible values from the service thus the provider throws error when other values are found. I'd suggest opening a support ticket to Azure and see if there is any bug from the service side.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @myc2h6o‘s response as an answer based on the documentation. 
If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. If it gets added and support needs to be added on our side, we can reopen this request or you can create a new one.
