### ISSUE TITLE
azurerm_ssh_public_key name validation incorrectly rejects period

### ISSUE THREAD

**Issue by fuzzykiller** [hashicorp/terraform-provider-azurerm#20920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_ssh_public_key

### Terraform Configuration Files

```hcl
data "azurerm_ssh_public_key" "main" {
  name                = "my.existing-azure-ssh"
  resource_group_name = "my-stuff-rg"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: invalid value for name (Public SSH Key name must be 1 - 128 characters long, can contain letters, numbers, underscores, and hyphens (but the first and last character must be a letter or number).)
│
│   with data.azurerm_ssh_public_key.main,
│   on main.tf line 11, in data "azurerm_ssh_public_key" "main":
│   11:   name                = "my.existing-azure-ssh"
│
╵
```

### Expected Behaviour

I should be able to reference this existing resource, which I recently created using Azure Portal.

### Actual Behaviour

Validator for `name` property incorrectly rejects this valid Azure SSH key resource name.

### Steps to Reproduce

1. `terraform plan`

**Comment by sinbai** [comment]
@fuzzykiller thanks for opening this issue. PR #20955  has been submitted to fix this issue. Could you keep track of it for more updates?
