### ISSUE TITLE
Support for azurerm_servicebus_namespace_disaster_recovery_config

### ISSUE THREAD

**Issue by volturyon** [hashicorp/terraform-provider-azurerm#20933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello!

I have two services bus created by terraform, one is the main one and the other is the secondary one, the problem comes when I make changes and redeploy, because the disaster recovery is still attached I can't deploy and I have to delete the secondary one to recreate it or add a life cycle for it.

Is it possible to add an option to stop this from happening?

`We recreate secondary namespace in this step to avoid error: (Conflict) Unable to freeze secondary namespace`

### New or Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace_disaster_recovery_config

**Comment by xiaxyi** [comment]
Thanks @volturyon for raising this issue, the resource you mentioned is already supported by Terraform: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace_disaster_recovery_config

Can you try it and let me know if it works?

**Comment by mybayern1974** [comment]
Close this issue by assuming xiaxyi's suggestion could resolve it. Feel free to suggest re-activate this issue if what is being asked still has not been supported by this provided.
