### ISSUE TITLE
SPELLING MISTAKE || azurerm_automation_software_update_configuration || V3.33.0

### ISSUE THREAD

**Issue by Kushagra-Neu** [hashicorp/terraform-provider-azurerm#20931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_software_update_configuration

### Terraform Configuration Files

```hcl
output "automation_software_update_configuration_output" {
  description = "Automation Software Update Configuration output values"
  value = { for k, v in azurerm_automation_software_update_configuration.automation_software_update_configuration : k => {
    id = v.id
    error_code =v.error_code
    error_meesage = v.error_meesage
    }
  }
}
```

### Debug Output/Panic Output

```bash
#AUTOMATION SOFTWARE UPDATE CONFIGURATION OUTPUT
output "automation_software_update_configuration_output" {
  description = "Automation Software Update Configuration output values"
  value = { for k, v in azurerm_automation_software_update_configuration.automation_software_update_configuration : k => {
    id = v.id
    error_code =v.error_code
    error_message = v.error_message
    }
  }
}
```

### Expected Behaviour

```hcl
#AUTOMATION SOFTWARE UPDATE CONFIGURATION OUTPUT
output "automation_software_update_configuration_output" {
  description = "Automation Software Update Configuration output values"
  value = { for k, v in azurerm_automation_software_update_configuration.automation_software_update_configuration : k => {
    id = v.id
    error_code =v.error_code
    error_message = v.error_message
    }
  }
}
```

**Comment by sinbai** [comment]
@Kushagra-Neu thanks for opening this issue. It seems that this is a known issue. The typo property `error_meesage` would be removed in v4.0 and the doc would be updated. See [here ](https://github.com/hashicorp/terraform-provider-azurerm/blob/f25c80c637982953ba0534ab6db240e03b3df882/internal/services/automation/automation_software_update_configuration_resource.go#L948) for details.
