### ISSUE TITLE
Dynamic criteria in Azure Monitor for Service Bus Queues expected aggregation types not accepted

### ISSUE THREAD

**Issue by mccrackenyyc** [hashicorp/terraform-provider-azurerm#20944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "amb_alert_queue_topic_volume_irregular" {
  name                = "amb-alert-queue-topic-volume-irregular-${var.env_name}"
  resource_group_name = azurerm_resource_group.amb_monitor_rg.name
  scopes              = [azurerm_servicebus_namespace.amb_svcbus_ns.id]
  description         = "Monitors if queue or topic volumes become irregular"

  dynamic_criteria {
    metric_namespace  = "microsoft.servicebus/namespaces"
    metric_name       = "ActiveMessages"
    aggregation       = "Average"                <<<<<<<<<<<<<<<<<<<<<<<<<<
    operator          = "GreaterOrLessThan"
    alert_sensitivity = "High"

    dimension {
      name     = "EntityName"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.amb_monitor_group_main.id
  }
}
```
and
```hcl
resource "azurerm_monitor_metric_alert" "amb_alert_queue_topic_volume_irregular" {
  name                = "amb-alert-queue-topic-volume-irregular-${var.env_name}"
  resource_group_name = azurerm_resource_group.amb_monitor_rg.name
  scopes              = [azurerm_servicebus_namespace.amb_svcbus_ns.id]
  description         = "Monitors if queue or topic volumes become irregular"

  dynamic_criteria {
    metric_namespace  = "microsoft.servicebus/namespaces"
    metric_name       = "ActiveMessages"
    aggregation       = "Total"                <<<<<<<<<<<<<<<<<<<<<<<<<<
    operator          = "GreaterOrLessThan"
    alert_sensitivity = "High"

    dimension {
      name     = "EntityName"
      operator = "Include"
      values   = ["*"]
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.amb_monitor_group_main.id
  }
}
```

### Debug Output/Panic Output

Output when using aggregation = "Total"

```shell
azurerm_monitor_metric_alert.amb_alert_queue_topic_volume_irregular: Creating...
╷
│ Error: creating or updating Monitor Metric Alert: (Name "amb-alert-queue-topic-volume-irregular-dev" / Resource Group "amb-monitor-rg-dev"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Time aggregation must be one of [Average, Minimum, Maximum]. Activity ID: 9696fc7e-d249-4804-9c5a-a6765036ac37."     
│
│   with azurerm_monitor_metric_alert.amb_alert_queue_topic_volume_irregular,
│   on monitor.tf line 21, in resource "azurerm_monitor_metric_alert" "amb_alert_queue_topic_volume_irregular":
│   21: resource "azurerm_monitor_metric_alert" "amb_alert_queue_topic_volume_irregular" {
```

Output when using aggregation = "Average"
```sh
azurerm_monitor_metric_alert.amb_alert_queue_topic_volume_irregular: Creating...
╷
│ Error: creating or updating Monitor Metric Alert: (Name "amb-alert-queue-topic-volume-irregular-dev" / Resource Group "amb-monitor-rg-dev"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Dynamic alert currently only supports Total aggregation type for this metric. Activity ID: cd071bf3-7b9d-499a-a7d5-902bc7e8359e."
│
│   with azurerm_monitor_metric_alert.amb_alert_queue_topic_volume_irregular,
│   on monitor.tf line 21, in resource "azurerm_monitor_metric_alert" "amb_alert_queue_topic_volume_irregular":
│   21: resource "azurerm_monitor_metric_alert" "amb_alert_queue_topic_volume_irregular" {
```

### Expected Behaviour

Expected one of "Average" "Minimum" "Maximum" to be the accepted argument

As per: https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftservicebusnamespaces

### Actual Behaviour

Failed to create resource, stuck in a loop of alternating error messages when I used the suggested parameter.

### Steps to Reproduce

`terraform apply`

**Comment by teowa** [comment]
Hi @mccrackenyyc , thanks for submitting this!
by checking the code Terraform should have sent the correct value to service REST API, and from [Metrics not supported by dynamic thresholds](https://learn.microsoft.com/en-us/azure/azure-monitor/alerts/alerts-dynamic-thresholds#metrics-not-supported-by-dynamic-thresholds)

<html>
<body>


Microsoft.ServiceBus/namespaces | ActiveMessages
-- | --



</body>
</html>


The mentioned metric is currently not supported in dynamic threshold.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
