### ISSUE TITLE
Set share-level permissions for all authenticated identities on a storageaccount 

### ISSUE THREAD

**Issue by fmayerhof** [hashicorp/terraform-provider-azurerm#20957]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using a azure file share with Active Directory integrations it`s currently not possible to setup the default share-level permissions. 
You can setup the permissions via Azure CLI at the moment. see Microsoft docs.
https://learn.microsoft.com/en-us/azure/storage/files/storage-files-identity-ad-ds-assign-permissions?tabs=azure-cli

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "this" {
  name                      = "StorageName"
  resource_group_name       = var.rg_name
  location                  = var.location

  share_properties {
    retention_policy {
       days = 30
    }
    smb {
      versions                        = ["SMB3.1.1"]
      authentication_types            = ["Kerberos", "NTLMv2"]
      kerberos_ticket_encryption_type = ["RC4-HMAC", "AES-256"]
      channel_encryption_type         = ["AES-128-CCM", "AES-128-GCM", "AES-256-GCM"]
    }
    defaultSharePermission = "StorageFileDataSmbShareContributor"
  }
```

**Comment by rob31231232** [comment]
We also need this feature.

Best regards

**Comment by jaywithersbrewin** [comment]
You could use azapi if you want to do it with Terraform whilst you wait for the feature to be implemented.
