### ISSUE TITLE
azurerm_key_vault_certificate: "DigiCert doesn't support emails in subject alternate names with order for a Ssl certificate"

### ISSUE THREAD

**Issue by Vijayalakshmi-Yolbhavi** [hashicorp/terraform-provider-azurerm#20960]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificate

### Terraform Configuration Files

```hcl
subject_alternative_names {
        dns_names = ["internal.contoso.com", "domain.hello.world"]
        emails    = ["abc@xxxx.com"]
      }
```

### Debug Output/Panic Output

```shell
azurerm_key_vault_certificate.cert: Creating...
╷
│ Error: keyvault.BaseClient#CreateCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="DigiCert doesn't support emails in subject alternate names with order for a Ssl certificate"
```

### Expected Behaviour

As per the documentation,  subject_alternative_names block supports the following(below):
dns_names - (Optional) A list of alternative DNS names (FQDNs) identified by the Certificate. Changing this forces a new resource to be created.
emails - (Optional) A list of email addresses identified by this Certificate. Changing this forces a new resource to be created.
upns - (Optional) A list of User Principal Names identified by the Certificate. Changing this forces a new resource to be created.

So, ideally when we use the "emails" argument in  subject_alternative_names block it should not throw error.

### Actual Behaviour

When we are using the emails argument in subject_alternative_names block, terraform is throwing below error:

azurerm_key_vault_certificate.cert: Creating...
╷
│ Error: keyvault.BaseClient#CreateCertificate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadParameter" Message="DigiCert doesn't support emails in subject alternate names with order for a Ssl certificate"
│

**Comment by manicminer** [comment]
@Vijayalakshmi-Yolbhavi Thanks for opening this issue. As the API error states, your selected certificate vendor DigiCert doesn't support this field. You will need to omit the field or choose a different vendor. Please consult [Azure documentation](https://learn.microsoft.com/en-us/azure/key-vault/certificates/how-to-integrate-certificate-authority) for more details.

We use this issue tracker to manage bug reports and feature requests for the Terraform AzureRM provider. Accordingly, as this is a question about the corresponding Azure service, I'm going to close this issue and recommend contacting Azure support if you need clarification on this error message. Thanks!
