### ISSUE TITLE
`azurerm_private_dns_resolver_inbound_endpoint` doesn't allow to set `private_ip_allocation_method = Static`

### ISSUE THREAD

**Issue by kaplik** [hashicorp/terraform-provider-azurerm#20961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_resolver_inbound_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_resolver_inbound_endpoint" "this" {
  name                    = "${local.resolver_name}-in"
  location                = azurerm_private_dns_resolver.this.location
  private_dns_resolver_id = azurerm_private_dns_resolver.this.id

  ip_configurations {
    private_ip_allocation_method = "Static"
    subnet_id                    = azurerm_subnet.inbound.id
    private_ip_address           = "a.b.c.d"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Based on MS documentation, it should be possible to set the allocation method to "Static" and set the inbound endpoint ip address.
https://learn.microsoft.com/en-us/azure/templates/microsoft.network/dnsresolvers/inboundendpoints?pivots=deployment-language-bicep#ipconfiguration

Looks like this is not allowed/implemented on the tf provider resource level:
https://github.com/hashicorp/terraform-provider-azurerm/blob/f25c80c637982953ba0534ab6db240e03b3df882/internal/services/privatednsresolver/private_dns_resolver_inbound_endpoint_resource.go#L82-L88

### Actual Behaviour

```
│ Error: expected ip_configurations.0.private_ip_allocation_method to be one of [Dynamic], got Static
│ 
│   with module.x.azurerm_private_dns_resolver_inbound_endpoint.this,
│   on x/dns-resolver/main.tf line 196, in resource "azurerm_private_dns_resolver_inbound_endpoint" "this":
│  196:     private_ip_allocation_method = "Static"
```

```
│ Error: Value for unconfigurable attribute
│ 
│   with module.x.azurerm_private_dns_resolver_inbound_endpoint.this,
│   on x/dns-resolver/main.tf line 198, in resource "azurerm_private_dns_resolver_inbound_endpoint" "this":
│  198:     private_ip_address           = "a.b.c.d"
│ 
│ Can't configure a value for "ip_configurations.0.private_ip_address": its value will be decided automatically based on the result of applying this configuration.
╵
```

**Comment by myc2h6o** [comment]
@kaplik I've tested myself and found a document about this. Unfortunately, this is not supported by Azure yet.
Document: https://learn.microsoft.com/azure/dns/private-resolver-endpoints-rulesets#inbound-endpoints, under `Note`:
> The IP address assigned to an inbound endpoint is not a static IP address that you can choose. Typically, the fifth IP address in the subnet is assigned. However, if the inbound endpoint is reprovisioned, this IP address might change. The IP address does not change unless the inbound endpoint is reprovisioned.

Error when using static allocation method: `Code="BadRequest" Message="IP allocation mode must be set to dynamic.`

The [document mentioned in the issue description](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/dnsresolvers/inboundendpoints?pivots=deployment-language-bicep#ipconfiguration) is auto-generated based on the [API Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/dnsresolver/resource-manager/Microsoft.Network/stable/2022-07-01/dnsresolver.json#L1895) and it uses the common struct `IpConfiguration` as the input. This is why the option `Static` is showing up here.

**Comment by FreddyAyala** [comment]
What about this? Tip

Using PowerShell, you can specify the inbound endpoint IP address to be dynamic or static.
If the endpoint IP address is specified as dynamic, the address does not change unless the endpoint is deleted and reprovisioned. Typically the same IP address will be assigned again during reprovisioning.
If the endpoint IP address is static, it can be specified and reused if the endpoint is reprovisioned. The IP address that you choose can't be a [reserved IP address in the subnet](https://learn.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq#are-there-any-restrictions-on-using-ip-addresses-within-these-subnets).

https://learn.microsoft.com/en-us/azure/dns/dns-private-resolver-get-started-powershell#create-the-inbound-endpoint

`$ipconfig = New-AzDnsResolverIPConfigurationObject -PrivateIPAddress 10.0.0.4 -PrivateIPAllocationMethod Static -SubnetId /subscriptions/<your sub id>/resourceGroups/myresourcegroup/providers/Microsoft.Network/virtualNetworks/myvnet/subnets/snet-inbound
New-AzDnsResolverInboundEndpoint -DnsResolverName mydnsresolver -Name myinboundendpoint -ResourceGroupName myresourcegroup -Location westcentralus -IpConfiguration $ipconfig`

So it is indeed supported by powershell. For landing zones and client critical infrastructure where many spoke networks we will be configured pointing towatds this enpoint as dns server it is very important to be able to set an static IP address.

**Comment by dawsonar802** [comment]
The Rest API seems to support `Static` as well, so using AzAPI may be an option to provision in the interim. 
https://learn.microsoft.com/en-us/rest/api/dns/dnsresolver/inbound-endpoints/update?tabs=HTTP#ipallocationmethod

**Comment by yavuzakyuz** [comment]
any update on this?

**Comment by speak2beeb** [comment]
Ah yes, this would be very beneficial to our corporation!

**Comment by mcowart123** [comment]
Adding to the chorus saying this would be very nice to have.

**Comment by JordanSussman** [comment]
I was able to use [azapi_resource](https://registry.terraform.io/providers/Azure/azapi/latest/docs/resources/azapi_resource) to create a Private DNS Resolver Inbound Endpoint with the following config:

```hcl
resource "azapi_resource" "private_dns_resolver_inbound_endpoint" {
  name      = "drie"
  parent_id = azurerm_private_dns_resolver.dns.id
  location  = var.location
  type      = "Microsoft.Network/dnsResolvers/inboundEndpoints@2022-07-01"

  body = jsonencode({
    properties = {
      "ipConfigurations" : [
        {
          "subnet" : {
            "id" : var.subnet_id
          },
          "privateIpAllocationMethod" : "Static",
          "privateIpAddress" : var.prviate_ip_address
        }
      ]
    }
  })

  depends_on = [
    azurerm_private_dns_resolver.dns
  ]
}
```

**Comment by Alfonsoaz01** [comment]
hello, do you have any updates? When would this become available? thank you so much!

**Comment by BHellstream** [comment]
Seems like Micorsoft has updated the documentation @myc2h6o was referring to as well and now supports static, it would be a welcome feature to get.
