### ISSUE TITLE
InternalServerError on azurerm_postgresql_flexible_server

### ISSUE THREAD

**Issue by n1c0l4stournier** [hashicorp/terraform-provider-azurerm#20969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.38

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.3"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.38"
    }
  }
}

resource "azurerm_postgresql_flexible_server" "postgresql" {
  name                = "postgres-prp"
  resource_group_name = "pr-prp"
  location            = "WestEurope"
  version             = 14
  sku_name            = "GP_Standard_D2s_v3"
  zone                = 1
  storage_mb          = "32768"

  delegated_subnet_id = var.subnet_id
  private_dns_zone_id = var.private_dns_zone_id
  create_mode         = "Default"

  administrator_login    = "admin"
  administrator_password = "myStrongPassw0rd"

}
```

### Debug Output/Panic Output

```shell
Error: creating Flexible Server (Subscription: "<<Subscription_ID>>"
│ Resource Group Name: "rg-prp"
│ Server Name: "postgresql-prp"): polling after Create: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '<<Tracking_ID>>"
```

### Expected Behaviour

PostgreSQL Flexible Server created

### Actual Behaviour

An Internal Server Error is produced

### Steps to Reproduce

terraform apply

**Comment by n1c0l4stournier** [comment]
And I tried on different version of the provider : 3.37, 3.40, 3.41 with the same results

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Maybe zone you specified isn't available in the location you specified. Could you try other zones to see if the issue still exists? Thanks.

**Comment by adeshreddy** [comment]
Having similar issue. Tired with latest provider 3.47

**Comment by n1c0l4stournier** [comment]
> Thanks for raising this issue. Maybe zone you specified isn't available in the location you specified. Could you try other zones to see if the issue still exists? Thanks. BTW, service team will improve the error message.

Yes, Thanks a lot ! The issue was not the Location but the Zone.
