### ISSUE TITLE
Unable to deploy 2 azurerm_virtual_machine_extension at time 

### ISSUE THREAD

**Issue by san6789** [hashicorp/terraform-provider-azurerm#20998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

 As i am trying to deploy 2 different powershell scripts using azurerm_virtual_machine_extension with terraform into azure cloud where I am facing issue with the extensions.

### Terraform Version

2.89.0

### AzureRM Provider Version

2.89.0

### Affected Resource(s)/Data Source(s)

azure window vm 

### Terraform Configuration Files

```hcl
# Create windows vm
resource "azurerm_windows_virtual_machine" "windows-vm" {
  name                  = var.computer_name
  resource_group_name   = var.resource_group_name
  location              = var.resource_group_location
  size                  = var.size
  admin_username        = var.admin_username
  admin_password        = data.azurerm_key_vault_secret.admin_password.value
  network_interface_ids = [module.azure_nic.nic_id]

  os_disk {
    name                 = "${var.computer_name}_OsDisk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = var.disk_size_gb
  }

  source_image_reference {
    publisher = var.publisher
    offer     = var.offer
    sku       = var.sku
    version   = "latest"
  }
}

resource "azurerm_virtual_machine_extension" "winrm-config" {
  name                       = "GitOpsFramework.EnableWinRM"
  virtual_machine_id         = azurerm_windows_virtual_machine.windows-vm.id
  publisher                  = "Microsoft.Compute"
  type                       = "CustomScriptExtension"
  type_handler_version       = "1.10"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
    {
        "fileUris": [ "https://raw.githubusercontent.com/ansible/ansible/v2.13.3/examples/scripts/ConfigureRemotingForAnsible.ps1" ],
        "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"
    }
    SETTINGS
}

resource "azurerm_virtual_machine_extension" "this" {
  name                         = "testscript"
  virtual_machine_id = azurerm_windows_virtual_machine.windows-vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.10"
  settings = <<SETTINGS
   {

    "fileUris": ["ghs.ps1peelQmsyzwYj9d5XshsmsRTX9cKQ5ri81hZLXvA%3D"],

     "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ghs.ps1",

     "managedIdentity" : {}

  }
  SETTINGS
}
```

### Debug Output/Panic Output

```shell
Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ArtifactNotFound" Message="The VM extension with publisher 'Microsoft.Azure.Extensions' and type 'CustomScriptExtension' could not be found."
│ 
│   with azurerm_virtual_machine_extension.this,
│   on main.tf line 89, in resource "azurerm_virtual_machine_extension" "this":
│   89: resource "azurerm_virtual_machine_extension" "this" {
│ 
╵

[ERROR] The original error message:
Command '['terraform', 'apply', '.tfplan']' returned non-zero exit status 1.

[ERROR] The 'vm-windows' was not applied. See above error message.
```

### Expected Behaviour

both vm extensions going to deploy 

### Actual Behaviour

no

### Steps to Reproduce

Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ArtifactNotFound" Message="The VM extension with publisher 'Microsoft.Azure.Extensions' and type 'CustomScriptExtension' could not be found."
│ 
│   with azurerm_virtual_machine_extension.this,
│   on main.tf line 89, in resource "azurerm_virtual_machine_extension" "this":
│   89: resource "azurerm_virtual_machine_extension" "this" {
│ 
╵

[ERROR] The original error message:
Command '['terraform', 'apply', '.tfplan']' returned non-zero exit status 1.

[ERROR] The 'vm-windows' was not applied. See above error message.

### Important Factoids

no

### References

no

**Comment by manicminer** [comment]
@san6789 thanks for opening this issue. Unfortunately, this is not an issue with the provider but more of a usage question, since the error you are seeing comes from the API and not from the provider.

A [quick search](https://learn.microsoft.com/en-us/azure/virtual-machines/extensions/custom-script-windows#extension-schema) shows that this extension should have the publisher `Microsoft.Compute` and not `Microsoft.Azure.Extensions`. I recommend giving this a try and consult Azure documentation if you have further difficulties configuring the VM extension.

As this is not a provider issue, I'll go ahead and close this for now.
