### ISSUE TITLE
Azure Spring Apps support for application Service Registry binding

### ISSUE THREAD

**Issue by felipmiguel** [hashicorp/terraform-provider-azurerm#20990]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no clear way to bind applications to Service Registry. In `azurerm_spring_cloud_app` there is addon_json attribute that seems can be used for binding, but there is no documentation and even if service seems to be binded it doesn't work as expected.
Here an example:
```terraform
data "azurerm_spring_cloud_service" "spring_apps_service" {
  name                = var.spring_apps_service_name
  resource_group_name = var.resource_group
}
locals {
  addon_json = {
    applicationConfigurationService : var.configuration_service_bind ? {
      resourceId : "${data.azurerm_spring_cloud_service.spring_apps_service.id}/configurationServices/default"
    } : {},
    serviceRegistry : var.service_registry_bind ? {
      resourceId : "${data.azurerm_spring_cloud_service.spring_apps_service.id}/serviceRegistries/default"
    } : {}
  }
}

resource "azurerm_spring_cloud_app" "application" {
  name                = var.application_name
  resource_group_name = var.resource_group
  service_name        = var.spring_apps_service_name

  addon_json = jsonencode(local.addon_json)
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_spring_cloud_app

### Potential Terraform Configuration

```hcl
resource "azurerm_spring_cloud_app" "application" {
  name                = var.application_name
  resource_group_name = var.resource_group
  service_name        = var.spring_apps_service_name
  
  service_registry_enabled = true
}
```

**Comment by ms-henglu** [comment]
Hi @felipmiguel ,

Thank you for taking time to report this issue!

Would you please share us more about "service seems to be binded it doesn't work as expected", so I can help investigate.

**Comment by felipmiguel** [comment]
Hi @ms-henglu. What I mean is that the service appears in the binding list, however it doesn't seem to be registered. See the screenshots for applications `catalog-service-cosmos` and `catalog-service`. `catalog-service` was binded using azure cli. `catalog-service-cosmos` was binded using Terraform.

![image](https://user-images.githubusercontent.com/52053185/226589837-381fbe26-f066-43f5-94a8-68158750000a.png)

![image](https://user-images.githubusercontent.com/52053185/226590670-29c958ea-9e48-440f-9b54-20ade7edf68c.png)

**Comment by felipmiguel** [comment]
And looking at Tanzu Dev Tools I see the following:
`catalog-service` (the servide binded using azure cli) contains eurekaClient configuration
![image](https://user-images.githubusercontent.com/52053185/226592931-34418c02-741d-4936-b8d6-159133e42702.png)

While `catalog-service-cosmos` (the service binded using Terraform) doesn't contain eureka configuration
![image](https://user-images.githubusercontent.com/52053185/226593355-33678480-8472-4d19-8deb-ea994878701d.png)

**Comment by leonard520** [comment]
@felipmiguel The application itself should contain `spring-cloud-starter-netflix-eureka-client`. Check [doc ](https://learn.microsoft.com/en-us/azure/spring-apps/how-to-enterprise-service-registry?tabs=Portal#confirm-the-configuration-of-dependent-libraries-for-the-service-registry-client-eureka-client). Do you add it in your application `catalog-service-cosmos`?

**Comment by felipmiguel** [comment]
Hi @leonard520 , yes it contains Eureka client. 'catalog-service-cosmos` was created from `catalog-service`, just replacing postgresql by cosmos. All code can be found here https://github.com/felipmiguel/acme-fitness-store/tree/feature/tf-vnet-loadtest including the terraform configuration (under terraform-vnet).

Due to this issue I also prepared a repair script, that can be found here https://github.com/felipmiguel/acme-fitness-store/blob/feature/tf-vnet-loadtest/terraform-vnet/repair-routing.sh

**Comment by felipmiguel** [comment]
I can confirm that using this configuration script works:
```terraform
data "azurerm_spring_cloud_service" "spring_apps_service" {
  name                = var.spring_apps_service_name
  resource_group_name = var.resource_group
}
locals {
  addon_json = {
    applicationConfigurationService : var.configuration_service_bind ? {
      resourceId : "${data.azurerm_spring_cloud_service.spring_apps_service.id}/configurationServices/default"
    } : {},
    serviceRegistry : var.service_registry_bind ? {
      resourceId : "${data.azurerm_spring_cloud_service.spring_apps_service.id}/serviceRegistries/default"
    } : {}
  }
}

resource "azurerm_spring_cloud_app" "application" {
  name                = var.application_name
  resource_group_name = var.resource_group
  service_name        = var.spring_apps_service_name

  addon_json = jsonencode(local.addon_json)
}
```

The solution will be cleaner using an attribute like the proposed `service_registry_enabled` but it works.
I would appreciate if **documentation is updated accordinly**, as the attribute `addon_json` description is sparingly described.
