### ISSUE TITLE
Support for BYO user-managed identity for AKS AGIC ingress controller

### ISSUE THREAD

**Issue by orangesharing** [hashicorp/terraform-provider-azurerm#21008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi Team!

We are currently deploying AKS cluster with AGIC ingress controller using Terraform scripts. We need to tightly control the identities used in our ecosystem, therefore we usually refrain from allowing the Terraform provider create those User-Assigned Managed Identities automatically through defaults - instead we create them explicitly, assign proper permissions to them, and then assign them to appropriate Terraform resources. 

When we create AKS cluster with AGIC ingress controller, the following UAMIs come into play:
- Application Gateway identity
- AKS cluster (control plane) identity
- node pool (kubelet) identity
- AGIC identity

Of those four UAMIs we can explicitly create first three using standard Terraform approach, AGIC identity, however, is created automatically. Once the "ingress_application_gateway" block is used in "azurerm_kubernetes_cluster" resource, the deployment will result in an "ingressapplicationgateway-<cluster_name>" UAMI being created in the node pool resource group. 

Recently we have noticed, that ability to provide your own UAMI was made available for ARM-template deployments in June 2021 (https://github.com/Azure/AKS/issues/2374). Would it be possible to extend azurerm to support similar functionality (for example add an "identity" sub-block to "ingress_appolication_gateway" block)?

Thanks!

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "my_aks_cluster" {
  
  (...)

  ingress_application_gateway {
    gateway_id = azurerm_application_gateway.my_agw.id

    identity {
      client_id = "my_agic_uami_client_id"
      object_id = "my_agic_uami_principal_id"
    }

  }

}
```

### References

https://github.com/Azure/AKS/issues/2374

**Comment by aristosvo** [comment]
Hi @orangesharing! I see that the `ingress_application_gateway_identity` block is available, but not sure if you can use that for your use-case?

I'll try some things as well and file a PR if there is more needed.

**Comment by orangesharing** [comment]
Hi @aristosvo, that would be lovely, thank you!
Keep up the good work, Team!

**Comment by aristosvo** [comment]
Hi @orangesharing! The PR is not working out great at the moment. The question is if this functionality is properly supported at the moment, I've created an issue on the AKS repo to request a bit more information about the workings of the REST API.

If you have (more) solid proof that is should work (using portal, `az` or otherwise), please let me know. [Docs](https://learn.microsoft.com/en-us/azure/aks/use-managed-identity#summary-of-managed-identities) are at this moment in time telling a different story, as it states that BYO identity for AGIC is not supported.

**Comment by aristosvo** [comment]
Hi @orangesharing! Don't worry, this was kind of a moonshot to begin with, as the docs were unclear on this point. The ARM template was in that case indeed a bit misleading.

I'll close this issue for now and wait for the answer on the AKS issue for confirmation.
