### ISSUE TITLE
Terraform (through Jenkins) fails with error message "could not connect docker" While creating Azure Bastion

### ISSUE THREAD

**Issue by sandeepkumarvadde** [hashicorp/terraform-provider-azurerm#21019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.13

### AzureRM Provider Version

2.30.0

### Affected Resource(s)/Data Source(s)

azurerm_bastion_host.virtual_network_bastion

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "azurebastionsubnet" {
  name                 = "subnet-abc"
  resource_group_name       = "rg-abc"
  virtual_network_name      = "vnet-abc"
  address_prefixes     = ["x.x.x.x/25"]
  service_endpoints    = []
  enforce_private_link_endpoint_network_policies  = true
  enforce_private_link_service_network_policies   = true
}


resource "azurerm_public_ip" "virtual_network_public_ip" {
  name                = "pip-abc"
  resource_group_name = "rg-abc"
  location            = "Central US"
  sku                 = "Standard"
  allocation_method   = "Static"
}

#Bastion
resource "azurerm_bastion_host" "virtual_network_bastion" {
  name                = "bastion-abc"
  location            = "Central US"
  resource_group_name = "rg-abc"

  ip_configuration {
    name                 = "say abc-config"
    subnet_id            = "subnet-abc"
    public_ip_address_id = azurerm_public_ip.virtual_network_public_ip.id
  }
}
```

### Debug Output/Panic Output

```shell
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "examplevnet"
  address_space       = ["192.168.1.0/24"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "AzureBastionSubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["192.168.1.224/27"]
}

resource "azurerm_public_ip" "example" {
  name                = "examplepip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_bastion_host" "example" {
  name                = "examplebastion"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
  }
}
```

### Expected Behaviour

We trying to create a Azure Resource Group and resources on Azure through Terraform through Jenkins. We created Service Principal on Azure and Terraform (through Jenkins) authenticate by Service Principal.

Terraform should create a Azure Bastion Host without any errors

### Actual Behaviour

Terraform could create resources as expected, but fails with error message 

"Cannot contact docker-xyz: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@169c76e9:docker-xyz": Remote call on docker-xyz failed. The channel is closing down or has closed down
Agent docker-xyz was deleted; cancelling node body
Could not connect to docker-xyz to send interrupt signal to process
[Pipeline] echo"

But the surprising part here is, Terraform could create Azure Bastion, added Subnet & Public IP Address to Bastion, but fails with above error message. What could be root cause and resolution? Please suggest. Below is the source code. 

### Steps to Reproduce

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "examplevnet"
  address_space       = ["192.168.1.0/24"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "AzureBastionSubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["192.168.1.224/27"]
}

resource "azurerm_public_ip" "example" {
  name                = "examplepip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_bastion_host" "example" {
  name                = "examplebastion"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
  }
}

**Comment by sinbai** [comment]
@sandeepkumarvadde thanks for opening this issue. Could you please try creating just a `azurerm_resource_group` to see if that works? If having the same issue, I'm assuming it's not a Terraform issue since the above config works on my local machine(not via Jenkins).

**Comment by tombuildsstuff** [comment]
hi @sandeepkumarvadde 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
