### ISSUE TITLE
Support for Postgres flavor of `azurerm_cosmosdb_account`

### ISSUE THREAD

**Issue by mclacore** [hashicorp/terraform-provider-azurerm#21018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CosmosDB Postgres API now available: https://learn.microsoft.com/en-us/rest/api/postgresqlhsc/

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "postgres" {
  name                = var.name
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  offer_type          = "Standard"

  capabilities {
    name = "EnablePostgres"
  }
}
```

### References

https://learn.microsoft.com/en-us/rest/api/postgresqlhsc/

**Comment by MarioGruda** [comment]
It seems like support for the [azurerm_cosmosdb_account](https://github.com/hashicorp/terraform-provider-azurerm/issues/21018#top) would help to get the connection string to the coordinator node in terraform.

The connection string is structured according to the following scheme:

`Server=c-<CLUSTER NAME>.<RANDOM ID>.postgres.cosmos.azure.com;Database=citus;Port=5432;[...]`

We are able to get the cluster name from the azurerm_cosmosdb_postgresql_cluster ressource, but the random id is missing. A direct export  of the connection string is not available. For the other cosmos db flavors we can use the azurerm_cosmosdb_account to get the connection strings. But this is not supported for azurerm_cosmosdb_postgresql_cluster right now.

**Comment by mclacore** [comment]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_postgresql_cluster

**Comment by nastosk8** [comment]
Can someone please explain how this is solved, not by workaround or where to look for active request?
