### ISSUE TITLE
FHIR Service - PATCH method in CORS fails in terraform plan

### ISSUE THREAD

**Issue by perocha** [hashicorp/terraform-provider-azurerm#21045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.0

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_healthcare_fhir_service

### Terraform Configuration Files

```hcl
resource "azurerm_healthcare_fhir_service" "azure_health" {
  name                          = "ahfsmyname"
  location                      = var.location
  resource_group_name           = var.resource_group_name
  workspace_id                  = azurerm_healthcare_workspace.azure_health[0].id
  kind                          = var.fhir_kind

  # Define the authentication for the FHIR service
  authentication {
    authority = "https://login.microsoftonline.com/${data.azurerm_client_config.current.tenant_id}"
    audience  = "https://${azurerm_healthcare_workspace.azure_health[0].name}-ahfsmyname.fhir.azurehealthcareapis.com"
  }

  cors {
    allowed_origins     = ["*"]
    allowed_headers     = ["*"]
    allowed_methods     = ["DELETE", "GET", "OPTIONS", "PATCH"]
    max_age_in_seconds  = 600
    credentials_allowed = false
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected cors.0.allowed_methods.3 to be one of [DELETE GET HEAD MERGE POST OPTIONS PUT], got PATCH
│ 
│   with module.healthcare_workspace.azurerm_healthcare_fhir_service.azure_health,
│   on modules/healthcare-workspace/main.tf line 38, in resource "azurerm_healthcare_fhir_service" "azure_health":
│   38:     allowed_methods     = ["DELETE", "GET", "OPTIONS", "PATCH"]
│ 
╵
Error: Process completed with exit code 1.
```

### Expected Behaviour

<img width="950" alt="image" src="https://user-images.githubusercontent.com/47702045/226404987-5c68876f-a9fd-4c21-96b1-df80f3f82123.png">

PATCH is a valid method for CORS in FHIR Service

### Actual Behaviour

Terraform plan fails indicating PATCH is not a valid CORS method (when it is)

### Steps to Reproduce

Issue seems to be located in this validation of "allowed methods"

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/healthcare/healthcare_fhir_resource.go#L179

### Important Factoids

No

### References

N/A

**Comment by xiaxyi** [comment]
Thanks @perocha for raising this issue,  you can track the fix in the mentioned pr.
