### ISSUE TITLE
azurerm_sentinel_alert_rule_template ID is trimmed

### ISSUE THREAD

**Issue by bsuchorowski** [hashicorp/terraform-provider-azurerm#21040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.48

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_template

### Terraform Configuration Files

```hcl
data "azurerm_sentinel_alert_rule_template" "templates" {
  log_analytics_workspace_id = azurerm_log_analytics_workspace.la.id
  display_name               = "Known Barium IP"
}
```

### Debug Output/Panic Output

```shell
.
```

### Expected Behaviour

data.azurerm_sentinel_alert_rule_template.id should return full resource_id f.e 
"/subscriptions/xxxx/resourceGroups/rg-mnfro-hub-wus/providers/Microsoft.OperationalInsights/workspaces/la-mnfro-hub-wus/providers/Microsoft.SecurityInsights/AlertRuleTemplates/f68a5046-b7eb-4f69-9519-1e99708bb9e0"

### Actual Behaviour

data.azurerm_sentinel_alert_rule_template.id returns trimmed resource_id f.e:

"/subscriptions/xxxx/resourceGroups/rg-mnfro-hub-wus/providers/Microsoft.OperationalInsights/workspaces/la-mnfro-hub-wus/providers/Microsoft.SecurityInsights/alertRuleTemplates/"

### Steps to Reproduce

1. Add azurerm_sentinel_alert_rule_template data source to your Terraform Repository
2. Try to use azurerm_sentinel_alert_rule_template.id in for example azurerm_sentinel_alert_rule_scheduled (we used it to extract alert_rule_template_guid)

**Comment by ziyeqf** [comment]
Hi @bsuchorowski , thanks for reporting.

Have opened a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/21054) to fix this, once it merged & released it should be fixed.

Thanks!
