### ISSUE TITLE
azurerm_machine_learning_datastore_datalake_gen2 store the wrong storage_container_id causing resource to be replaced

### ISSUE THREAD

**Issue by gdippolito** [hashicorp/terraform-provider-azurerm#21049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_datastore_datalake_gen2

### Terraform Configuration Files

```hcl
resource "azurerm_machine_learning_datastore_datalake_gen2" "datastore" {
  name                 = "adls_datastore"
  workspace_id         = azurerm_machine_learning_workspace.workspaces.id
  storage_container_id = data.storage_external_to_resource_group.container_id
}
```

### Debug Output/Panic Output

```shell
# azurerm_machine_learning_datastore_datalake_gen2.dataset must be replaced
-/+ resource "azurerm_machine_learning_datastore_datalake_gen2" "dataset" {
      + authority_url         = (known after apply)
      ~ id                    = "/subscriptions/xxxxxxxx/resourceGroups/rg-dev-xxxxxxxx/providers/Microsoft.MachineLearningServices/workspaces/ws-dev-yyyyyyyyy/dataStores/dataset" -> (known after apply)
      ~ is_default            = false -> (known after apply)
        name                  = "dataset"
      ~ storage_container_id  = "/subscriptions/xxxxxxxxx/resourceGroups/rg-dev-xxxxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxxxxx/blobServices/default/containers/dataset" -> "/subscriptions/xxxxxxxx/resourceGroups/rg-dev-yyyyyyyy/providers/Microsoft.Storage/storageAccounts/yyyyyyyyy/blobServices/default/containers/dataset" # forces replacement
      - tags                  = {} -> null
        # (2 unchanged attributes hidden)
    }
```
```


### Expected Behaviour

the correct storage container id is saved in the state

### Actual Behaviour

The wrong storage container id (it contains the resource group identifier of the resoruce group where AzureML is deployed). 

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

**Comment by xuzhang3** [comment]
@gdippolito I cannot reproduce this error.   workspace and storage container can be in the same resource or not. The key info used in the storage container ID is the storage account name and the container name.
