### ISSUE TITLE
azurerm_api_management_backend error when setting resource_id - Value should represent absolute http URL

### ISSUE THREAD

**Issue by toothpasteBeforeOj** [hashicorp/terraform-provider-azurerm#21047]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_backend

### Terraform Configuration Files

```hcl
data "azurerm_windows_web_app" "api" {
  name                = var.app_service_name
  resource_group_name = var.app_service_rg_name
}

resource "azurerm_api_management_backend" "api_backend" {
  api_management_name = data.azurerm_api_management.apim.name
  name                = var.api_backend_name
  protocol            = var.api_backend_protocol
  resource_group_name = local.resource_group_name
  url                 = "https://${data.azurerm_windows_web_app.api.default_hostname}"
  resource_id         = data.azurerm_windows_web_app.api.id
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/toothpasteBeforeOj/afdf011e368d7ce485fff1a40ea32a14
```

### Expected Behaviour

When specifying the resource id of the Azure-hosted backend resource, the backend should be provisioned during terraform apply and the backend target should be linked as an Azure resource when viewing in the portal, not an HTTP(s) endpoint. 

### Actual Behaviour

After the plan is created and terraform apply is run, the following error is logged to the console.

> │ Error: creating/updating Backend: (Name "api-01" / Service Name "apim-01" / Resource Group "rg-01"): apimanagement.BackendClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"Value should represent absolute http URL","target":"resourceId"}]

If I remove the resource_id argument, the backend will be provisioned, however it will be linked as an HTTP(s) endpoint when viewing in the portal, not as an Azure resource.

### Steps to Reproduce

1. Configure scripts
2. Run terraform apply

**Comment by sinbai** [comment]
@toothpasteBeforeOj thanks for opening this issue. In fact, Terraform implements Azure resource management through Azure API. The above error is returned by Azure API, not Terraform. Per the [description of `resourceId` in Azure API](https://github.com/Azure/azure-rest-api-specs/blob/969fd0c2634fbcc1975d7abe3749330a5145a97c/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2022-08-01/definitions.json#L1908), the `resource_id` should be a URL. Could you please try using the URL (e.g. "https://management.azure.com/${data.azurerm_windows_web_app.api.id}")  rather than `data.azurerm_windows_web_app.api.id` to see if the error is resolved?
