### ISSUE TITLE
Support for azurerm_backup_policy_vm to include tiering

### ISSUE THREAD

**Issue by cliff-wakefield-acurus** [hashicorp/terraform-provider-azurerm#21051]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When defining an azure backup policy for a vm in the Azure Console you can enable tiering to move recovery points to an archive tier of the recovery services vault.

<img width="799" alt="CleanShot 2023-03-21 at 12 14 16@2x" src="https://user-images.githubusercontent.com/49538634/226497683-4659f7e9-71b3-4f34-baee-ac1d6ef1018d.png">

It would be great if this were exposed through the azurerm_backup_policy_vm resource.

The underlying API seems to support it.

### New or Affected Resource(s)/Data Source(s)

azurerm_backup_policy_vm

### Potential Terraform Configuration

```hcl
# no tiering is the default no extra variables
resource "azurerm_backup_policy_vm" "example" {
...
}

# enable recommended tiering
resource "azurerm_backup_policy_vm" "example" {
...
  tiering = "recommended"
}

# enable eligible tiering after 3 months
resource "azurerm_backup_policy_vm" "example" {
...
  tiering = "eligible"
  tiering_eligible_period = 3
}
```

### References

https://learn.microsoft.com/en-us/azure/backup/archive-tier-support
https://learn.microsoft.com/en-us/azure/backup/backup-azure-arm-userestapi-createorupdatepolicy

**Comment by craigmoyle** [comment]
Any update on this please? Has the potential to save customers quite a lot of money. Currently deploying via AzApi but it would be good to get native support.
