### ISSUE TITLE
azurerm_automation_hybrid_runbook_worker documentation

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/terraform-provider-azurerm#21075]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Struggling to follow the documentation for the affected resource; specifically the `worker_id` attribute.

Do we generate a the ID, why does the example not show us how we can generate an ID and why is it required/not generate for us?

Hoping to use this resource but hoping for some more clarification on this specific attribute please.

Appreciate it

### New or Affected Resource(s)/Data Source(s)

azurerm_automation_hybrid_runbook_worker

**Comment by wuxu92** [comment]
Hi @ASHR4 thanks for your feedback. actually the worker_id can be any valid UUID string, it works **as** a name of the worker. i will update the document for this property and if there are any other confusing parts to you?

**Comment by ASHR4** [comment]
Hi @wuxu92, appreciate the response, that clarifies that nicely.

The `worker_type` is exported, is there no way we can specify this when building this resource?
