### ISSUE TITLE
Support for assigning VM applications to virtual machine

### ISSUE THREAD

**Issue by rob31231232** [hashicorp/terraform-provider-azurerm#21094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It is possible to create an "Azure compute galleries" with azurerm_gallery_application and an application in it with azurerm_gallery_application_version.

But we missing the option to assign the application created with azurerm_gallery_application to an virtual machine. 

There is a workarround to assign the VM Application to a virtual machine with Azapi (https://github.com/L-u-k-e-GIT/azure_vm_applications/blob/main/vm_applications.tf)

### New or Affected Resource(s)/Data Source(s)

azurerm_gallery_application_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_gallery_application_assignment" "example" {
  gallery_application_id = azurerm_gallery_application_version.example.id
  location               = azurerm_gallery_application_version.example.location
  virtual_machine_id     = azurerm_windows_virtual_machine.example.id
}
```

### References

https://github.com/MicrosoftDocs/azure-docs/issues/93447 
https://github.com/L-u-k-e-GIT/azure_vm_applications/blob/main/vm_applications.tf
https://learn.microsoft.com/en-us/cli/azure/vm/application?view=azure-cli-latest#az-vm-application-set

**Comment by Kluud** [comment]
👍

**Comment by myc2h6o** [comment]
Hi @rob31231232 the gallery application could be assigned to the VM with `gallery_application` property with `azurerm_windows_virtual_machine` https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#gallery_application

**Comment by rob31231232** [comment]
> Hi @rob31231232 the gallery application could be assigned to the VM with `gallery_application` property with `azurerm_windows_virtual_machine` https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#gallery_application

I tested the `gallery_application` property and this will do the job, but not in our case. We need to install the gallery application after installing some VM Extensions (which we set with `azurerm_virtual_machine_extension`). In this specific case the VM must be AD domain joined before the application can be installed. 

When the `gallery_application` is installed with an separate terraform resource we're able to use `depends_on`, so we can force the installation of the VM Extension before the installation of the `gallery_application`

**Comment by myc2h6o** [comment]
@rob31231232 I got your point. It sounds like a reasonable feature request to support it as a separate resource as well. I'll be working on this.

**Comment by jkroepke** [comment]
@myc2h6o did you work on this?

**Comment by jkroepke** [comment]
FYI: There is a dedicated resource for an VMapplication. A separate resource must not modify the VM object, instead a resource `Microsoft.Compute/virtualMachines/VMapplications` could be used.

```json
{
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json",
    "contentVersion": "1.0.0.0",
    "resources": [
        {
            "apiVersion": "2021-07-01",
            "type": "Microsoft.Compute/virtualMachines/VMapplications",
            "name": "vm-demo-adc01/opsstack-agent-windows",
            "location": "westeurope",
            "properties": {
                "order": 1,
                "treatFailureAsDeploymentFailure": true,
                "packageReferenceId": "/subscriptions/xxx/resourceGroups/rg-opsstack-westeurope-001/providers/Microsoft.Compute/galleries/GAL_OPSSTACK_WESTEUROPE_001/applications/opsstack-agent-windows/versions/1.0.0"
            }
        }
    ]
}

```

Pretty sure, this can be archived with azapi provider.
