### ISSUE TITLE
Azure Virtual Desktop: load balancer type

### ISSUE THREAD

**Issue by marcvalk-git** [hashicorp/terraform-provider-azurerm#21102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Why does changing the load_balancer_type value from (i.e.) BreadthFirst to DepthFirst cause a creation of a new resource ?

Documentation states:
[load_balancer_type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_host_pool#load_balancer_type) - (Required) BreadthFirst load balancing distributes new user sessions across all available session hosts in the host pool. Possible values are BreadthFirst, DepthFirst and Persistent. Changing this forces a new resource to be created.

If you change this inside the portal, it just updates and does not create a new resource (as far as I can see)

### Terraform Version

1.4.2

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_host_pool

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_host_pool" "this" {
  name                     = "vdpool"
  resource_group_name      = "rg-001"
  location                 = "westeurope
  type                     = "Pooled"
  load_balancer_type       = "BreadthFirst"
  friendly_name            = "friendly name"
  description              = "description"
  validate_environment     = true
  maximum_sessions_allowed = 16
}
```

### Debug Output/Panic Output

```shell
# azurerm_virtual_desktop_host_pool.this must be replaced
-/+ resource "azurerm_virtual_desktop_host_pool" "this" {
      ~ id                       = "/subscriptions/***/resourceGroups/rg-001/providers/Microsoft.DesktopVirtualization/hostPools/vdpool" -> (known after apply)
      ~ **load_balancer_type       = "BreadthFirst" -> "DepthFirst" # forces replacement**
        name                     = "vdpool"
        # (10 unchanged attributes hidden)
    }
```

### Expected Behaviour

  # azurerm_virtual_desktop_host_pool.this must be replaced
-/+ resource "azurerm_virtual_desktop_host_pool" "this" {
      ~ id                       = "/subscriptions/***/resourceGroups/rg-001/providers/Microsoft.DesktopVirtualization/hostPools/vdpool" -> (known after apply)
      ~ **load_balancer_type       = "BreadthFirst" -> "DepthFirst" # forces replacement**
        name                     = "vdpool"

        # (10 unchanged attributes hidden)
    }

### Actual Behaviour

  # azurerm_virtual_desktop_host_pool.this must be replaced
-/+ resource "azurerm_virtual_desktop_host_pool" "this" {
      ~ id                       = "/subscriptions/***/resourceGroups/rg-001/providers/Microsoft.DesktopVirtualization/hostPools/vdpool" -> (known after apply)
      ~ **load_balancer_type       = "BreadthFirst" -> "DepthFirst" # forces replacement**
        name                     = "vdpool"
        # (10 unchanged attributes hidden)
    }

**Comment by sinbai** [comment]
@marcvalk-git thanks for opening this issue. This issue means that a change of  `load_balancer_type` should not force the creation of a new resource, correct? If yes, this issue has been fixed by PR #20947 and released in [v3.49.0 of the Terraform Provider](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.49.0/CHANGELOG.md). Could you upgrade the tf version to see if it has been resolved?
