### ISSUE TITLE
Support for PostgreSQL version 14

### ISSUE THREAD

**Issue by acano-arrive** [hashicorp/terraform-provider-azurerm#21103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.15

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.2.4"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.15.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 3.4.0"
    }
  }
}

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {}

data "azurerm_key_vault" "key_vault" {  # pulls in the specified keyVault
  name                = "mykv"
  resource_group_name = "myrg"
}

resource "random_password" "password" {
  length      = 20
  min_upper   = 2
  min_lower   = 2
  min_numeric = 2
  min_special = 2
}

resource "azurerm_key_vault_secret" "generated_pass" {
  name         = "admin-pwd"
  value        = random_password.password.result
  key_vault_id = data.azurerm_key_vault.key_vault.id
}

resource "azurerm_postgresql_server" "al-postgres-server" {
  name                          = "myserver"
  location                      = "centralus"
  resource_group_name           = "myrg"
  sku_name                      = "B_Gen4_1" 
  storage_mb                    = 5120
  backup_retention_days         = 7
  geo_redundant_backup_enabled  = false 
  auto_grow_enabled             = true 
  administrator_login           = "pg4dm1n_Us3r"
  administrator_login_password  = "${azurerm_key_vault_secret.generated_pass.value}"
  version                       = "14"
  ssl_enforcement_enabled       = true
}

resource "azurerm_postgresql_database" "al-postgres-db" {
  name                = "mydb"
  resource_group_name = "myrg"
  server_name         = azurerm_postgresql_server.al-postgres-server.pg-server-name
  charset             = "UTF8"
  collation           = "English_United States.1252" 
}
```

### Debug Output/Panic Output

```shell
INFO[0018] ╷
│ Error: expected version to be one of [9.5 9.6 11 10 10.2 10.0], got 14
│ 
│   with azurerm_postgresql_server.al-postgres-server,
│   on main.tf line 40, in resource "azurerm_postgresql_server" "al-postgres-server":
│   40:   version                       = "14"
│ 
╵ 
ERRO[0018] 1 error occurred:
        * exit status 1
```

### Expected Behaviour

PostgreSQL version 14 should be an expected version.

This was supported in Azure as of June 2022: https://docs.microsoft.com/en-us/azure/postgresql/flexible-server/release-notes#release-june-2022

Old issue: 
https://github.com/hashicorp/terraform-provider-azurerm/issues/17514

### Actual Behaviour

PostgreSQL version 14 was rejected and an error thrown.

### Steps to Reproduce

terraform init

terraform plan

**Comment by aristosvo** [comment]
Hi @acano-arrive!

In your example you are using single server instead of flexible server. Single server doesn't support later versions than 11, see also [this doc](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-compare-single-server-flexible-server).

As this is not supported by Azure, I'm not able to help you any further on adding this functionality to the single server resource.
