### ISSUE TITLE
azurerm_api_management zones must always be the same over all locations

### ISSUE THREAD

**Issue by feberl** [hashicorp/terraform-provider-azurerm#21101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.9

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurem_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "apim" {
  name                      = "myapim"
  location                  = "westeurope"
  resource_group_name       = "rg"
  publisher_name            = var.publisher_name
  publisher_email           = var.publisher_email
  sku_name                  = "Premium_2"
  virtual_network_type      = "Internal"
  zones                     = ["1", "2"]
  notification_sender_email = var.notification_sender_email
  public_ip_address_id      = var.public_ip_address_id


  virtual_network_configuration {
    subnet_id = var.network_subnet_ids_apim
  }


  additional_location" {
      location = "eastus"
      public_ip_address_id = var.public_ip_address_id_additional
      zones = ["1"]
      capacity = 1
      virtual_network_configuration {
        subnet_id = var.network_subnet_ids_apim_additional
     }
  }
}
```

### Debug Output/Panic Output

```shell
Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameters" 
Message="Invalid parameter: Specified sku capacity 1 is invalid for location 'East US'. 
Availability Zones (2,1), the sku capacity must be in multiples of number of Availability Zones = 2."
```

### Expected Behaviour

I can create a setup with a 2 zones for primary location (here westeurope) and capacity 2 and only one zone with one unit for additional location (here eastus)

### Actual Behaviour

Specified sku capacity 1 is invalid for location 'East US'. Availability Zones (2,1), the sku capacity must be in multiples of number of Availability Zones = 2

In the portal this setup is doable.
![image](https://user-images.githubusercontent.com/91525750/227477625-c346d48a-9a5b-4191-af2b-7b9ad6fc8b60.png)

**Comment by sinbai** [comment]
@feberl thanks for opening this issue. I have submitted [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/21128) to fix this issue. Could you track of it for more updates?
