### ISSUE TITLE
azurerm_container_registry virtual_network subnet_id not accepting multiple subnet IDs

### ISSUE THREAD

**Issue by dimitrigeo** [hashicorp/terraform-provider-azurerm#21116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.1

### AzureRM Provider Version

3.48

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
acr_subnets_allow = [
    "/subscriptions/XXXXXXXXXXXXXXXXX/resourceGroups/PROD/providers/Microsoft.Network/virtualNetworks/vnet-west-europe/subnets/aks-snet-west-europe",
    "/subscriptions/XXXXXXXXXXXXXXXXX/resourceGroups/STAGE/providers/Microsoft.Network/virtualNetworks/vnet-west-europe/subnets/aks-snet-west-europe"
  ]

variable "acr_subnets_allow" {
  description = "A list of subnet IDs to allow access to the container registry"
  type        = string
}

  network_rule_set {
    default_action = "Deny"
    ip_rule = [
      for ip_range in var.ip_range_team : {
        ip_range = ip_range
        action   = "Allow"
      }
    ]

    virtual_network {
      action    = "Allow"
      subnet_id = var.acr_subnets_allow

      #[
      #  for snet in var.acr_subnets_allow : {
      #    subnet_id = snet.value
      #  } 
      #]
    }
```

### Debug Output/Panic Output

```shell
│ Error: Incorrect attribute value type
│ 
│   on ../modules/acr/acr.tf line 27, in resource "azurerm_container_registry" "acr":
│   27:       subnet_id = [
│   28:         for snet in var.acr_subnets_allow : {
│   29:           subnet_id = snet
│   30:         } 
│   31:       ]
│     ├────────────────
│     │ var.acr_subnets_allow is list of string with 2 elements
│ 
│ Inappropriate value for attribute "subnet_id": string required.
```

### Expected Behaviour

I am trying to pass multiple subnet IDs to the subnet_id property in the virtual_network block, no matter what i try (dynamic for for loops) It will simple not accept a list of string or object. You can see one example in the commended out code.
I have also tried something like below:

      dynamic "virtual_network" {
        for_each = network_rule_set.value.virtual_network
        content {
          action    = "Allow"
          subnet_id = virtual_network.value.subnet_id
        }
      }

### Actual Behaviour

passes validation but fails plan stage

### Steps to Reproduce

terraform init, validate, plan

### Important Factoids

no

### References

nothing i can see

**Comment by magodo** [comment]
@dimitrigeo The `subnet_id` is of type string, while its containing property `virtual_network` is of type set. So you can do something like:

```hcl
resource "azurerm_container_registry" "example" {
#...
virtual_network {
  action = "Allow"
  subnet_id = ".../subnet1"
}

virtual_network {
  action = "Allow"
  subnet_id = ".../subnet2"
}
#...
}
```

**Comment by dimitrigeo** [comment]
Thanks @magodo! that worked!
