### ISSUE TITLE
azurerm_web_application_firewall_policy custom_rules match_conditions > operator "Any" cannot be used due to match_values being required while it should be optional

### ISSUE THREAD

**Issue by sanderrhorst** [hashicorp/terraform-provider-azurerm#21118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy 

### Terraform Configuration Files

```hcl
resource "azurerm_web_application_firewall_policy" "agw_aks" {
  provider            = azurerm.landingzone
  name                = "waf-${lower(var.CUSTOMER)}-${lower(var.ENVIRONMENT_SHORT)}-weu-001"
  resource_group_name = azurerm_resource_group.general.name
  location            = var.LOCATION
  tags                = local.global_tags

  lifecycle {
    ignore_changes = [
      custom_rules, # can be removed when issue below is resolved
    ]
  }

  // disabled because they cannot be created yet due to provider bug: 
  // https://github.com/hashicorp/terraform-provider-azurerm/issues/19013
   custom_rules {
     name      = "restRuleUploadExclusion"
     priority  = 40
    rule_type = "MatchRule"
     match_conditions {
       match_variables {
         variable_name = "PostArgs"
         selector      = "value"
       }
       operator           = "Any"
     }
     action = "Log"
   }
}
```

### Debug Output/Panic Output

```shell
When I use code above, Terraform gives me the following error during the plan: 

│ Error: Missing required argument
│ 
│   on application_gateway_waf_policy.tf line 19, in resource "azurerm_web_application_firewall_policy" "agw_aks":
│   19:     match_conditions {
│ 
│ The argument "match_values" is required, but no definition was found.

When I provide the value match_values = ["*"] the following error is provided during the apply (plan succeeds):
│ Error: creating Application Gateway Web Application Firewall Policy: (Name "waf-acc-weu-001" / Resource Group "rg-acc-weu-001"): network.WebApplicationFirewallPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ApplicationGatewayFirewallConditionNonEmptyMatchValues" Message="Custom Rule 'restRuleUploadExclusion' must not have any match value(s) in its condition in context 'System.Collections.Generic.List`1[System.String]'." Details=[]
```

### Expected Behaviour

The waf custom rules should be created. The operator "any" support was added in version 3.49.0, based on an issue I logged #19013. But this part of the code was forgotten. The field match_values should be optional when the operator = "any".

### Actual Behaviour

Either plan or apply fails.

### References

#19013

**Comment by sanderrhorst** [comment]
@wuxu92, can you fix this ASAP?

**Comment by wuxu92** [comment]
Hi @sanderrhorst thanks for you feedback and very sorry i haven't notice this issue in my last fix. Just created a PR to upate this reosurce ❤️
