### ISSUE TITLE
Logic App Workflow with API Connections Deploys but Connectors Aren't Found

### ISSUE THREAD

**Issue by johnsonr1994** [hashicorp/terraform-provider-azurerm#21120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.6

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_workflow

### Terraform Configuration Files

```hcl
data "local_file" "action-post-to-teams" {
  filename = "${path.module}/logic-app-step-templates/actions/1-post-to-teams.json"
}

data "local_file" "action-terminate" {
  filename = "${path.module}/logic-app-step-templates/actions/terminate.json"
}

data "local_file" "trigger-defender-security-alert" {
  filename = "${path.module}/logic-app-step-templates/triggers/defender-security-alert.json"
}

data "azurerm_managed_api" "defender-api" {
  name     = "ascalert"
  location = var.location
}

data "azurerm_managed_api" "teams-api" {
  name     = "teams"
  location = var.location
}

resource "azurerm_api_connection" "defender-api-connection" {
  name                = "ascalert"
  resource_group_name = var.alerting_rg_name
  managed_api_id      = data.azurerm_managed_api.defender-api.id
}

resource "azurerm_api_connection" "teams-api-connection" {
  name                = "teams"
  resource_group_name = var.alerting_rg_name
  managed_api_id      = data.azurerm_managed_api.teams-api.id
  display_name        = "PowerAutomate"
}

resource "azurerm_logic_app_workflow" "la-teams-alert" {
  name                = "la-teams-defender-alerts-aks"
  location            = var.location
  resource_group_name = var.alerting_rg_name

  workflow_parameters = {
    "$connections" = jsonencode(
      {
        defaultValue = {}
        type         = "Object"
      }
    )
  }

  parameters = {
    "$connections" = jsonencode({
      "ascalert": {
        "connectionId"   = azurerm_api_connection.defender-api-connection.id
        "connectionName" = azurerm_api_connection.defender-api-connection.name
        "id"             = azurerm_api_connection.defender-api-connection.managed_api_id
      } 
      "teams": {
        "connectionId"   = azurerm_api_connection.teams-api-connection.id
        "connectionName" = azurerm_api_connection.teams-api-connection.name
        "id"             = azurerm_api_connection.teams-api-connection.managed_api_id
      }
    })
  }
}

resource "azurerm_logic_app_trigger_custom" "trigger-defender-security-alert" {
  name         = "When_a_Microsoft_Defender_for_Cloud_Alert_is_Created_or_Triggered"
  logic_app_id = azurerm_logic_app_workflow.la-teams-alert.id

  body = data.local_file.trigger-defender-security-alert.content
}

resource "azurerm_logic_app_action_custom" "action-post-to-teams" {
  name         = "Post_to_Microsoft_Defender_Alerts_Channel"
  logic_app_id = azurerm_logic_app_workflow.la-teams-alert.id

  body = data.local_file.action-post-to-teams.content
}

resource "azurerm_logic_app_action_custom" "action-terminate" {
  name         = "Terminate"
  logic_app_id = azurerm_logic_app_workflow.la-teams-alert.id
  depends_on = [
    azurerm_logic_app_action_custom.action-post-to-teams
  ]

  body = data.local_file.action-terminate.content
}

### local files reference in the actions:
### 1-post-to-teams.json
{
    "inputs": {
        "body": {
            ***REDACTED***
        },
        "host": {
            "connection": {
                "name": "@parameters('$connections')['teams']['connectionId']"
            }
        },
        "method": "post",
        "path": "/beta/teams/conversation/message/poster/@{encodeURIComponent('User')}/location/@{encodeURIComponent('Channel')}"
    },
    "runAfter": {},
    "runtimeConfiguration": {
        "staticResult": {
            "name": "REDACTED",
            "staticResultOptions": "Disabled"
        }
    },
    "type": "ApiConnection"
}

### terminate.json
{
    "inputs": {
        "runStatus": "Succeeded"
    },
    "runAfter": {
        "Post_to_Microsoft_Defender_Alerts_Channel": [
            "Succeeded"
        ]
    },
    "type": "Terminate"
}

### defender-security-alerts.json
{
    "inputs": {
        "body": {
            "callback_url": "@{listCallbackUrl()}"
        },
        "host": {
            "connection": {
                "name": "@parameters('$connections')['ascalert']['connectionId']"
            }
        },
        "path": "/Microsoft.Security/Alert/subscribe"
    },
    "type": "ApiConnectionWebhook"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Logic App is stood up with API connectors wired up appropriately.

### Actual Behaviour

Logic app is stood up, but the API connectors referenced by respective actions aren't found.

**Comment by johnsonr1994** [comment]
This is the resulting designer view after deploying the logic app and connectors via terraform
![image](https://user-images.githubusercontent.com/75702341/227560738-600dbfbe-13bb-49dd-a95f-e7da29f95e85.png)

**Comment by sinbai** [comment]
@johnsonr1994 thanks for opening this issue. Could you please provide the complete terraform config to help reproduce and troubleshooting? It would be helpful if the terraform log could be provided as well.

**Comment by johnsonr1994** [comment]
@sinbai thank you for the response and I apologize for the delay on this. The above configuration is a submodule of a larger terraform config which contains data specific my team and isn't pertinent to this issue. The submodule that I have added above is the entire configuration that we are deploying to retrieve this issue. If you need me to formulate this into a different format, let me know.

I did run a terraform apply with the log level set to debug and that file can be found here: [terraform.log](https://github.com/hashicorp/terraform-provider-azurerm/files/11091306/terraform.log).
 Let me know if you have any other questions or need anything else from me. Thank you again.

**Comment by johnsonr1994** [comment]
@cjtous1 sorry for the late reply on this. I really appreciate the suggestion and I will give that a try as soon as possible. I will report back here whether that ends up working for us or not.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @cjtous1‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
