### ISSUE TITLE
Support for user-assigned identity for Azure Managed Grafana

### ISSUE THREAD

**Issue by hknutsen** [hashicorp/terraform-provider-azurerm#21126]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for assigning a user-assigned identity to Azure Managed Grafana.

Currently only system-assigned identity is supported through the Azure provider, however the ARM/Bicep reference mentions user-assigned identities.

### New or Affected Resource(s)/Data Source(s)

azurerm_dashboard_grafana

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_user_assigned_identity" "example" {
  location            = azurerm_resource_group.example.location
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_dashboard_grafana" "example" {
  name                              = "example-dg"
  resource_group_name               = azurerm_resource_group.example.name
  location                          = "West Europe"
  api_key_enabled                   = true
  deterministic_outbound_ip_enabled = true
  public_network_access_enabled     = false

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.example.id]
  }

  tags = {
    key = "value"
  }
}
```

### References

- [ARM/Bicep reference](https://learn.microsoft.com/en-us/azure/templates/microsoft.dashboard/2021-09-01-preview/grafana?pivots=deployment-language-bicep#managedidentity)

**Comment by jiaweitao001** [comment]
Fix PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/21394
