### ISSUE TITLE
Error: The terraform-provider-azurerm_v3.49.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by Drilli** [hashicorp/terraform-provider-azurerm#21137]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_virtual_machine

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm",
      version = "=3.0.1"
    }
  }
}

provider "azurerm" {
  subscription_id = "${var.azure_subscription_id}"
  client_id       = "${var.azure_client_id}"
  client_secret   = "${var.azure_client_secret}"
  tenant_id       = "${var.azure_tenant_id}"
  environment     = "china"
  features { }
}
resource "azurerm_resource_group" "rg" {
  name     = "${var.resource_group}"
  location = "${var.location}"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "${var.resource_group}-vnet"
  address_space       = ["10.1.0.0/16"]
  location            = "${var.location}"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "default"
  address_prefixes     = ["10.1.0.0/24"]
  virtual_network_name = azurerm_virtual_network.vnet.name
  resource_group_name  = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "bastion_subnet" {
  name                 = "AzureBastionSubnet"
  address_prefixes       = ["10.1.1.0/26"]
  resource_group_name  = "${azurerm_resource_group.rg.name}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"  
}

resource "azurerm_subnet_network_security_group_association" "nsgassocsub" {
  subnet_id                 = azurerm_subnet.subnet.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}

resource "azurerm_network_security_group" "nsg" {
  name                = "${var.prefix}-nsg"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_network_interface" "techdb-nic" {
  name                      = "${var.VMName}-nic"
  location                  = "${var.location}"
  resource_group_name       = azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "${var.VMName}-nic-config"
    subnet_id                     = azurerm_subnet.subnet.id
    private_ip_address_allocation = "Static"
    private_ip_address            = "10.1.0.4"
  }
}

resource "azurerm_windows_virtual_machine" "vm" {
  name                  = "${var.VMName}"
  location              = "${var.location}"
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [azurerm_network_interface.techdb-nic.id]
  size                  = "${var.VMSize}"
  computer_name         = "${var.VMName}"
  admin_username        = "${var.adminUser}"
  admin_password        = "${var.adminPassword}"

  source_image_reference {
    publisher = "${var.imageReferencePublisher}"
    offer     = "${var.imageReferenceOffer}"
    sku       = "${var.imageReferenceSKU}"
    version   = "${var.imageReferenceVersion}"
  }

  os_disk {
    name              = "${var.VMName}-osdisk"
    caching           = "ReadWrite"
    # create_option     = "FromImage"
    storage_account_type = "${var.osDiskType}"
  }

  tags = "${var.tags}"
}

resource "azurerm_mssql_virtual_machine" "sqlvm" {
  virtual_machine_id = azurerm_windows_virtual_machine.vm.id
  sql_license_type   = "PAYG"
}
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond
│
│   with azurerm_mssql_virtual_machine.sqlvm,
│   on teraformtechdb.tf line 205, in resource "azurerm_mssql_virtual_machine" "sqlvm":
│  205: resource "azurerm_mssql_virtual_machine" "sqlvm" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_v3.49.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x54529e6]

goroutine 67 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql.resourceMsSqlVirtualMachineRead(0x1df00410, {0x5e8e3a0, 0x1dd2e000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql/mssql_virtual_machine_resource.go:609 +0x4d6
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1d379ab0, {0x70836c0, 0x1dcf8360}, 0x1df00410, {0x5e8e3a0, 0x1dd2e000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1d379ab0, {0x70836c0, 0x1dcf8360}, 0x1df128c0, {0x5e8e3a0, 0x1dd2e000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x547
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1ce58730, {0x70836c0, 0x1dcf8300}, 0x1dcf61a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4f4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1ca40320, {0x70836c0, 0x1dcf8078}, 0x1dcf21b0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x646ee00, 0x1ca40320}, {0x70836c0, 0x1dcf8078}, 0x1c68e100, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1c7ae6c0, {0x708bfc4, 0x1c7ae7e0}, 0x1df020a0, 0x1d42ce28, 0xb2fb428, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x1c7ae6c0, {0x708bfc4, 0x1c7ae7e0}, 0x1df020a0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x25f

Error: The terraform-provider-azurerm_v3.49.0_x5.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Resources should have been created

### Actual Behaviour

This is happening when I specify the environment "china" in azurerm provider:

provider "azurerm" {
  subscription_id = "${var.azure_subscription_id}"
  client_id       = "${var.azure_client_id}"
  client_secret   = "${var.azure_client_secret}"
  tenant_id       = "${var.azure_tenant_id}"
  environment     = "china"
  features { }
}

### Steps to Reproduce

terraform plan

**Comment by aristosvo** [comment]
@Drilli Can you give me the stack trace if you remove `azurerm_mssql_virtual_machine` from your Terraform configuration as stated [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/21138#issuecomment-1486425176)?

**Comment by Drilli** [comment]
> @Drilli Can you give me the stack trace if you remove `azurerm_mssql_virtual_machine` from your Terraform configuration as stated [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/21138#issuecomment-1486425176)?
> 
> I can then take a look at it as well.

Yes, I think it gives the same Plugin Crashed error for many other resources.

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Plugin did not respond
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_network_interface.test-nic,
│   on teraformtechdb.tf line 80, in resource "azurerm_network_interface" "test-nic":
│   80: resource "azurerm_network_interface" "test-nic" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Plugin did not respond
│
│   with azurerm_storage_account.cstorage,
│   on teraformtechdb.tf line 217, in resource "azurerm_storage_account" "cstorage":
│  217: resource "azurerm_storage_account" "cstorage" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-azurerm_3.49.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x60c72a9]

goroutine 153 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/mssql.resourceMsSqlVirtualMachineRead(0xc002744c00, {0x6b290c0?, 0xc0005b1000?})
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/internal/services/mssql/mssql_virtual_machine_resource.go:604 +0x4c9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x7eb2100?, {0x7eb2100?, 0xc000640510?}, 0xd?, {0x6b290c0?, 0xc0005b1000?})
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000e2c1c0, {0x7eb2100, 0xc000640510}, 0xc0023b3520, {0x6b290c0, 0xc0005b1000})
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0019160d8, {0x7eb2100?, 0xc0006403f0?}, 0xc002600c80)
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0010a2960, {0x7eb2100?, 0xc000e59cb0?}, 0xc00142c600)
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x727ea00?, 0xc0010a2960}, {0x7eb2100, 0xc000e59cb0}, 0xc0018d4070, 0x0)
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001e41e0, {0x7ec22e0, 0xc00146c000}, 0xc0015b5c20, 0xc001942a80, 0xc500ed0, 0x0)
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1340 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001e41e0, {0x7ec22e0, 0xc00146c000}, 0xc0015b5c20, 0x0)
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1713 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        C:/Users/jahiridr/source/repos/terraform-provider-azurerm-3.0.49/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:963 +0x28a

Error: The terraform-provider-azurerm_3.49.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
