### ISSUE TITLE
azurerm_storage_account_local_user terraform import doesn't import ssh_authorized_key sections

### ISSUE THREAD

**Issue by siemin81** [hashicorp/terraform-provider-azurerm#21142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.0

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_local_user

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account_local_user" "example" {
  name                 = "user1"
  storage_account_id   = azurerm_storage_account.example.id
  ssh_key_enabled      = true
  ssh_password_enabled = true
  home_directory       = "example_path"
  ssh_authorized_key {
    description = "key1"
    key         = local.first_public_key
  }
  ssh_authorized_key {
    description = "key2"
    key         = local.second_public_key
  }
  permission_scope {
    permissions {
      read   = true
      create = true
    }
    service       = "blob"
    resource_name = azurerm_storage_container.example.name
  }
}
```

### Debug Output/Panic Output

```shell
terraform import terraform import azurerm_storage_account_local_user.example /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Storage/storageAccounts/storageAccount1/localUsers/user1
```

### Expected Behaviour

terraform state show:
resource "azurerm_storage_account_local_user" "user1" {
    home_directory       = "example_path"
    id                   = "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Storage/storageAccounts/storageAccount1/localUsers/user1"
    name                 = "user1"
    sid                  = (sensitive value)
    ssh_key_enabled      = true
    ssh_password_enabled = true
    storage_account_id   = "subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Storage/storageAccounts/storageAccount1"

    permission_scope {
        resource_name = "example"
        service       = "blob"

        permissions {
            create = true
            delete = false
            list   = false
            read   = true
            write  = false
        }
    }

    ssh_authorized_key {
        description = "key1"
        key         = "ssh-rsa AAAAB....."
    }

    ssh_authorized_key {
        description = "key2"
        key         = "ssh-rsa AAAAB....."
    }

    timeouts {}
}

### Actual Behaviour

terraform state show:
resource "azurerm_storage_account_local_user" "user1" {
    home_directory       = "example_path"
    id                   = "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Storage/storageAccounts/storageAccount1/localUsers/user1"
    name                 = "user1"
    sid                  = (sensitive value)
    ssh_key_enabled      = true
    ssh_password_enabled = true
    storage_account_id   = "subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/resGroup1/providers/Microsoft.Storage/storageAccounts/storageAccount1"

    permission_scope {
        resource_name = "example"
        service       = "blob"

        permissions {
            create = true
            delete = false
            list   = false
            read   = true
            write  = false
        }
    }

    timeouts {}
}

### Steps to Reproduce

1 create local users with SSH keys in portal
2 write terraform code
3 (optional) try to do terraform apply which will fail, because users are already present
4 terraform import the users
5 terraform plan/apply wants to recreate them becasue terraform is unaware of the ssh-key configuration and wants to add it forcing whole resource re-creation

### Important Factoids

no

**Comment by magodo** [comment]
@siemin81 That is because the Azure API won't return the `ssh_authorized_key`. You'd have to manually ignore them via `ignore_changes = [ssh_authorized_key]`.

**Comment by siemin81** [comment]
@magodo: Thank you for explanation, as usually its Azure fault :)
