### ISSUE TITLE
Support for `minimum_tls_cipher` - The feature was just enabled in preview and by default is set to least secure cipher provided. [Security concern]

### ISSUE THREAD

**Issue by jakubtrebacz-dev** [hashicorp/terraform-provider-azurerm#21141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The newly introduced preview feature on function apps and web apps is defaulting to least secure TLS they provide `TLS_RSA_WITH_AES_128_CBC_SHA`. There is a range of TLS ciphers you can choose from up to `TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384`.

It is some what a risk to have it as 128 I mentioned, still relatively small threat surface but it would be nice to have an option to change this to something more secure as soon as possible.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_web_app; azurerm_linux_web_app; azurerm_windows_function_app; azurerm_linux_function_app

### Potential Terraform Configuration

```hcl
We already have `minimum_tls_version` 
So lets add `minimum_tls_cipher = "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384"`
```

**Comment by tombuildsstuff** [comment]
hey @jakubtrebacz-dev 

Thanks for opening this issue.

Just so that we can understand the impact of this one, is this preview feature enabled by default - or this is something you need to opt-into to have this default set?

Thanks!

**Comment by jakubtrebacz-dev** [comment]
Hi @tombuildsstuff 

Thanks for the reply.
No I did not opt-into preview. By the looks of things the option has disappeared from the "Configuration -> General Settings" as quick as it showed up. My guess is that they accidentally made the preview option enabled to all users by default.
It might be a month or two before this feature is released then. 

Still, it's something that would be nice to have in terraform as soon as it's out of preview.
I will keep an eye and bump this post again when there is more information available on when this is coming out 👍🏻 

Cheers.

**Comment by jackofallops** [comment]
Thanks @jakubtrebacz-dev - given this looks to have been an unintended exposure of an upcoming feature, I'll close this out until we get official information on the feature or preview.

Thanks again for the diligence.
