### ISSUE TITLE
JsonADDomainExtension extension fails with error 1326 or 1909

### ISSUE THREAD

**Issue by op7ic** [hashicorp/terraform-provider-azurerm#21147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.49.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension

### Terraform Configuration Files

```hcl
[...]
resource "azuread_group" "dc_admins" {
  display_name     = "Administrators"
  description      = "AADDS Administrators"
  members          = [azuread_user.dc_admin.object_id]
  security_enabled = true
}

resource "azuread_user" "dc_admin" {
  user_principal_name         = "xxxx@xxxx.com"
  display_name                = "AADDS DC Administrator"
  password                    = "xxxxxxxx"
  force_password_change       = false
}

[...]
resource "azurerm_active_directory_domain_service" "aadds" {
  name                  = local.config_file.domain_server_name
  location              = azurerm_resource_group.aadds.location
  resource_group_name   = azurerm_resource_group.aadds.name
  filtered_sync_enabled = true
  domain_name           = "xxxx.com"
  sku                   = "Enterprise"
  
  initial_replica_set {
    subnet_id = azurerm_subnet.aadds.id
  }

  notifications {
    notify_dc_admins      = false
    notify_global_admins  = false
  }

  security {
    sync_kerberos_passwords = true
    sync_ntlm_passwords     = true
    sync_on_prem_passwords  = true
  }
  
  timeouts {
    create = "12h"
    update = "12h"
    read = "120m"
    delete = "12h"
  }

  tags = {
    environment = "prod"
  }
  
  lifecycle {
    ignore_changes = all
    create_before_destroy = true
  }
}
[...]
resource "azurerm_windows_virtual_machine" "avd" {
  count                 = length(random_id.avd)
  name                  = "avd-vm-${count.index}-${random_id.avd[count.index].hex}"
  location              = azurerm_resource_group.xxx.location
  resource_group_name   = azurerm_resource_group.xxx.name
  provision_vm_agent    = true
  size                  = var.win_server_size
  license_type          = "Windows_Client" 
  admin_username        = local.config_file.desktop.username
  admin_password        = local.config_file.desktop.password
  network_interface_ids = [azurerm_network_interface.avd[count.index].id]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
  
  
  identity {
    type  = "SystemAssigned"
  }

  source_image_reference {
   publisher = "MicrosoftWindowsDesktop"
   offer     = "office-365"
   sku       = "win11-21h2-avd-m365"
   version   = "latest"
  }
  
  timeouts {
    create = "12h"
    update = "12h"
    read = "120m"
    delete = "12h"
  }
  
}
[...]
resource "azurerm_virtual_machine_extension" "avd_aadds_join" {
  count                      = length(azurerm_windows_virtual_machine.avd)
  name                       = "aadds-join-vmext"
  virtual_machine_id         = azurerm_windows_virtual_machine.avd[count.index].id
  publisher                  = "Microsoft.Compute"
  type                       = "JsonADDomainExtension"
  type_handler_version       = "1.3"
  auto_upgrade_minor_version = true

  settings = <<-SETTINGS
    {
      "Name": "${azurerm_active_directory_domain_service.aadds.domain_name}",
      "OUPath": "",
      "User": "${azuread_user.dc_admin.user_principal_name}",
      "Restart": "true",
      "Options": "3"
    }
    SETTINGS

  protected_settings = <<-PROTECTED_SETTINGS
    {
      "Password": "${var.password}"
    }
    PROTECTED_SETTINGS

  lifecycle {
    ignore_changes = [settings, protected_settings]
  }
}
```
```


### Debug Output/Panic Output

```shell
Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'aadds-join-vmext'. Error message: \"Exception(s) occured while joining Domain 'xxx.com'\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot "
```

### Expected Behaviour

Host should join the domain using provisioning account.

### Actual Behaviour

During the build process, the above code will create an Azure AD, setup all the firewall, DNS, vpool, interfaces and such. The code runs successfully but once it gets to the extension provisioning, the error 1326 or 1909 gets raised by azure. The account for provisioning is freshly created in the same terraform file and not used anywhere other than to join the devices to the domain. Interestingly, when account password is reset then provisioning using above code will work successfully which lead me to conclude that somehow, account credentials are not synced with Azure AD after creation, and the password reset forces this synchronization to happen. 

The following error will appear in extension error log:
```
[
    {
        "code": "ComponentStatus/JoinDomainException for Option 3 meaning 'User Specified'/failed/1",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "ERROR - Failed to join domain='xxxxxxx.onmicrosoft.com', ou='', user='xxxxx@xxxx.onmicrosoft.com', option='NetSetupJoinDomain, NetSetupAcctCreate' (#3 meaning 'User Specified'). Error code 1326"
    },
    {
        "code": "ComponentStatus/JoinDomainException for Option 1 meaning 'User Specified without NetSetupAcctCreate'/failed/1",
        "level": "Error",
        "displayStatus": "Provisioning failed",
        "message": "ERROR - Failed to join domain='xxxxxxx.onmicrosoft.com', ou='', user=xxxxx@xxxx.onmicrosoft.com', option='NetSetupJoinDomain' (#1 meaning 'User Specified without NetSetupAcctCreate'). Error code 1909"
    }
]
```

**Comment by myc2h6o** [comment]
Hi @op7ic thanks for raising the issue! Unfortunately, according to the error message, this is more likely an issue with Azure extension itself instead of in the provider. I'd recommend you open a ticket towards Azure for help.

**Comment by op7ic** [comment]
hi @myc2h6o I did open ticket with azure as well to see what they can say. I suppose the follow up question is if there is any password reset mechanism that can be implemented in terraform to help with this issue?

**Comment by tombuildsstuff** [comment]
@op7ic as @myc2h6o has mentioned this is a configuration error related to the VM Extension itself, unfortunately we're unable to offer assistance with the configuration here, since VM Extensions are particularly finicky, as such I'm going to have to close this issue for the moment.

**Comment by op7ic** [comment]
hi @tombuildsstuff yep. I'm also working with azure to figure this one out. I suppose the follow up question is still valid - do you think its possible to have any password resest mechanism in terraform provider itself? I searched for it but can't find code which would reset the password for a user added by azurerm.

**Comment by op7ic** [comment]
Just a bit of an update. Here is Microsoft explanation about this process after chatting with Azure representative: 
"""
To authenticate users on the managed domain, Azure AD DS needs password hashes in a format that's suitable for NT LAN Manager (NTLM) and Kerberos authentication. Azure AD doesn't generate or store password hashes in the format that's required for NTLM or Kerberos authentication until you enable Azure AD DS for your tenant. For security reasons, Azure AD also doesn't store any password credentials in clear-text form. Therefore, Azure AD can't automatically generate these NTLM or Kerberos password hashes based on users' existing credentials.
"""
Effectively, this kills an ability to join the domain using created password as, without password reset, the account can't be used to join the AD. It also means that ADDS services in terraform might not be usable until password reset routine gets created.
