### ISSUE TITLE
azurerm_linux_function_app - WEBSITE_CONTENTAZUREFILECONNECTIONSTRING app setting does not get set by storage-related attributes

### ISSUE THREAD

**Issue by Dmitrii034** [hashicorp/terraform-provider-azurerm#21140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app, azurerm_windows_function_app

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~>1.3.9"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.48.0"
    }
  }
  backend "azurerm" {}
}

provider "azurerm" {
  use_msi         = false
  subscription_id = var.subscriptionId
  tenant_id       = var.tenantId
  features {}
}

resource "azurerm_virtual_network" "example" {
  name                = "virtnetname"
  address_space       = ["10.0.0.0/16"]
  resource_group_name = var.resourceGroup
  location            = var.location
}

resource "azurerm_subnet" "example" {
  name                 = "subnetname"
  resource_group_name  = var.resourceGroup
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Sql", "Microsoft.Storage"]

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.Web/serverFarms"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}

resource "azurerm_storage_account" "example" {
  name                     = "xxxxxxxxxxx"
  resource_group_name      = var.resourceGroup
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    ip_rules                   = [var.myIp]
    virtual_network_subnet_ids = [azurerm_subnet.example.id]
  }
}

resource "azurerm_storage_share" "share" {
  name                 = "exampleshare"
  storage_account_name = azurerm_storage_account.example.name
  quota                = 50
  access_tier          = "Hot"

  acl {
    id = "allpermissiom"

    access_policy {
      permissions = "rwdl"
      start       = "2021-01-01T00:00:00.0000000Z"
      expiry      = "2099-12-31T23:59:59.0000000Z"
    }
  }
}

resource "azurerm_service_plan" "example" {
  name                = "example-app-service-plan"
  resource_group_name = var.resourceGroup
  location            = var.location
  os_type             = "Linux"
  sku_name            = "EP1"
}

resource "azurerm_linux_function_app" "example" {
  name                = "xxxxx-xxxx-xxxxx"
  resource_group_name = var.resourceGroup
  location            = var.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  app_settings = {
    WEBSITE_CONTENTOVERVNET = 1
    WEBSITE_CONTENTSHARE    = azurerm_storage_share.share.name
  }

  site_config {}
}

resource "azurerm_app_service_virtual_network_swift_connection" "alfa_vnet_integration" {
  app_service_id = azurerm_linux_function_app.example.id
  subnet_id      = azurerm_subnet.example.id
}
```

### Debug Output/Panic Output

```shell
azurerm_linux_function_app.example: Creating...
╷
│ Error: WEBSITE_CONTENTAZUREFILECONNECTIONSTRING must be set when WEBSITE_CONTENTSHARE and WEBSITE_CONTENTOVERVNET are specified
│ 
│   with azurerm_linux_function_app.example,
│   on main.tf line 82, in resource "azurerm_linux_function_app" "example":
│   82: resource "azurerm_linux_function_app" "example" {
│ 
│ WEBSITE_CONTENTAZUREFILECONNECTIONSTRING must be set when WEBSITE_CONTENTSHARE and WEBSITE_CONTENTOVERVNET are specified
╵
```

### Expected Behaviour

Function app is created, app settings WEBSITE_CONTENTOVERVNET, WEBSITE_CONTENTSHARE are set by `app_settings` attribute, while app setting WEBSITE_CONTENTAZUREFILECONNECTIONSTRING is set by storage-related attributes (`storage_account_name` and `storage_account_access_key`).

From documentation: "Note: For storage related settings, please use related properties that are available such as storage_account_access_key, terraform will assign the value to keys such as WEBSITE_CONTENTAZUREFILECONNECTIONSTRING, AzureWebJobsStorage in app_setting."

The WEBSITE_CONTENTAZUREFILECONNECTIONSTRING app setting was being set correctly by storage attributes in previous provider version (tested on 3.46.0).

### Actual Behaviour

Apply failed with above error.

### Steps to Reproduce

`terraform apply`

### References

Might be related to this PR - https://github.com/hashicorp/terraform-provider-azurerm/pull/18258

**Comment by xiaxyi** [comment]
Thanks @Dmitrii034 for raising this issue, let me try reproducing this issue from my side and take the corresponding actions.

**Comment by xiaxyi** [comment]
@Dmitrii034 I raised a pr to set the connection string automatically for function apps that are using elastic app service plan, you can track the status in the mentioned pr.

**Comment by Dmitrii034** [comment]
Any updates on this @xiaxyi ? This issue is blocking us from updating to the newer azurerm versions. Unfortunately, we can't easily switch to setting the variable using `app_settings`.

**Comment by xiaxyi** [comment]
Hey @Dmitrii034 , the pr is still in review, I'll let you know once there is any progress.
