### ISSUE TITLE
Support for network dataplane field (AKS)

### ISSUE THREAD

**Issue by wedaly** [hashicorp/terraform-provider-azurerm#21167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

2023-02-01 and 2023-02-02preview APIs introduced [a new field to the AKS ManagedCluster resource called "networkDataplane"](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-02-01/managedClusters.json#L3143-L3164).

The networkDataplane field replaces the "ebpfDataplane" field added in the 2022-09-02preview API. This is a breaking change to the preview API.

When Terraform upgrades to Azure SDK with API verison 2023-02-02preview or later, it will need to replace references to "ebpfDataplane" with "networkDataplane".

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### References

* [networkDataplane field in Azure REST spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/stable/2023-02-01/managedClusters.json#L3143-L3164)
* [Configure Azure CNI Powered by Cilium in Azure Kubernetes Service (AKS)](https://learn.microsoft.com/en-us/azure/aks/azure-cni-powered-by-cilium)
* https://github.com/hashicorp/terraform-provider-azurerm/issues/19397
* https://github.com/hashicorp/terraform-provider-azurerm/pull/19527

**Comment by stephybun** [comment]
Thanks for the heads up and for raising this issue @wedaly.

I believe this was taken care of in the API upgrade for AKS in #21256 where we map the terraform resource's field `ebpf_data_plane` to the field `networkDataPlane` in the AKS API. Since this is already available I'm going to go ahead and close this issue.
