### ISSUE TITLE
Removing identity block from azurerm_mysql_flexible_server does not remove the respective managed identity

### ISSUE THREAD

**Issue by martinshkrelijerry** [hashicorp/terraform-provider-azurerm#21164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.49

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_flexible_server" "mysql_server" {
  name                         = "..."
  resource_group_name          = "..."
  location                     = "..."
  administrator_login          = "..."
  administrator_password       = "..."
  version                      = "8.0.21"
  backup_retention_days        = "..."
  zone                         = 1
  geo_redundant_backup_enabled = true
  storage {
    auto_grow_enabled = true
    size_gb           = 128
    iops              = 684
  }
  dynamic "identity" {
    for_each = var.PRIMARY_REGION_IDENTITY_ID != "" ? { identity_enab = true } : {}
    content {
      type         = "UserAssigned"
      identity_ids = compact([var.PRIMARY_REGION_IDENTITY_ID, var.SECONDARY_REGION_IDENTITY_ID])
    }
  }
  delegated_subnet_id               = "..."
  private_dns_zone_id               = "..."
  sku_name                          = "GP_Standard_D8ds_v4"
  create_mode                       = "Default"
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Removal of identity block should result in removal of any identities assigned to the instance.

### Actual Behaviour

The terraform apply succeeds, however the genuine result visible from portal is that no changes have been applied. Having tried again to issue terraform plan the output still depicts the identity to be deleted.
As one can see, there are two identity ids assigned to the instance. Adding the id comes without any problems, however the same scenario for deleting the entire block, applies to deleting single id from the identity block 

### Steps to Reproduce
1. terraform apply
2. Check terraform apply output - success
3. terraform apply/plan
4. The changes from first apply weren't actually applied

**Comment by tombuildsstuff** [comment]
hey @martinshkrelijerry 

Thanks for opening this issue.

Taking a look through this appears to be a bug here: https://github.com/hashicorp/terraform-provider-azurerm/blob/371a5f3774b539ab21feaafe82be55eeb308729b/internal/services/mysql/mysql_flexible_server_resource.go#L1002 - where rather than setting the identity type to `None`, we're setting this to `nil` which during an update will do nothing - as such this likely needs to become `if err != nil {` instead, so that we remove this identity during the update (which'll also want a test to confirm this works).

Thanks!
