### ISSUE TITLE
AzureRM Data Collection Rule - Syslog Facilities and Log Level wildcard does not set valid configuration.

### ISSUE THREAD

**Issue by azurehenry** [hashicorp/terraform-provider-azurerm#21185]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### Terraform Configuration Files

```hcl
data "azurerm_resource_group" "rg" {
  name = "lab-test-rg-01"
}

data "azurerm_log_analytics_workspace" "log_analytics_workspace" {
  name                = "lab-test-law-01"
  resource_group_name = data.azurerm_resource_group.rg.name
}

resource "azurerm_monitor_data_collection_rule" "azmondcr" {
    name                        = "lab-test-dcr-01"
    resource_group_name         = data.azurerm_resource_group.rg.name
    location                    = data.azurerm_resource_group.rg.location
    description                 = "data collection rule example"

    destinations {
        log_analytics {
            workspace_resource_id = data.azurerm_log_analytics_workspace.log_analytics_workspace.id
            name = "lab-test-azmon-las-01"
        }
        azure_monitor_metrics {
            name = "lab-test-azmon-metrics-01"
        }
    }
    data_sources {
        syslog {
            streams = ["Microsoft-Syslog"]
            facility_names = ["*"]
            log_levels = ["Info"]
            name = "lab-test-syslog-01"
        }
    }
    data_flow {
        streams      = ["Microsoft-Syslog"]
        destinations = ["lab-test-azmon-las-01"]
    }
}

Or
data "azurerm_resource_group" "rg" {
  name = "lab-test-rg-01"
}

data "azurerm_log_analytics_workspace" "log_analytics_workspace" {
  name                = "lab-test-law-01"
  resource_group_name = data.azurerm_resource_group.rg.name
}

resource "azurerm_monitor_data_collection_rule" "azmondcr" {
    name                        = "lab-test-dcr-01"
    resource_group_name         = data.azurerm_resource_group.rg.name
    location                    = data.azurerm_resource_group.rg.location
    description                 = "data collection rule example"

    destinations {
        log_analytics {
            workspace_resource_id = data.azurerm_log_analytics_workspace.log_analytics_workspace.id
            name = "lab-test-azmon-las-01"
        }
        azure_monitor_metrics {
            name = "lab-test-azmon-metrics-01"
        }
    }
    data_sources {
        syslog {
            streams = ["Microsoft-Syslog"]
            facility_names = ["*"]
            log_levels = ["*"]
            name = "lab-test-syslog-01"
        }
    }
    data_flow {
        streams      = ["Microsoft-Syslog"]
        destinations = ["lab-test-azmon-las-01"]
    }
}
```

### Debug Output/Panic Output

```shell
No debug output, will plan and apply successfully.
```

### Expected Behaviour

When using a wildcard value for Syslog Data Source Facilities in an Azure Monitor Data Collection Rule, the expected result is all Facilities would be set to minimum log level.  If you have facility_names = ["*"] and log_levels = ["*"] or ["Info"] you would expect each facility to be defined to either "none" or "Info" however the portal will indicate nothing has been configured.

### Actual Behaviour

The documentation indicates that using the wildcard value for the Facilities and/or Log Levels will apply for all, however the Azure Portal will display an error stating "Log levels' must not be empty. 'Log Levels' item count should be 1 or more.  Specified list has 0 items.  To properly set a minimum log level, a list of Facilities needs to be provided to get at least 1 set with a minimum log level.  
i.e. 
facility_names = ["auth"]
log_levels = ["Info"]

### Steps to Reproduce

- Create a Resource Group
- Create a Log Analytics Workspace
- Use basic Terraform code provided to attempt to create an Azure DCR with a Syslog data source.

**Comment by teowa** [comment]
Hi @azurehenry , thanks for submitting this issue!
From [REST API specification](https://github.com/Azure/azure-rest-api-specs/blob/ad580e5db33d432124c50b7ed1288b0847903104/specification/monitor/resource-manager/Microsoft.Insights/stable/2022-06-01/dataCollectionRules_API.json#L470-L518), the `facilityNames` and `logLevels` properties should support for using wildcard `*`. But the Azure Portal seems not support `*`, I am still confirming with the service team if this is display issue of Azure Portal. Thanks.

**Comment by teowa** [comment]
Confirmed that the service backend supports the wildcard `*` in facilityNames & logLevels, this is a Portal issue.

**Comment by teowa** [comment]
> Is this fixed and merged into the current azurerm provider? Do you have a specific version number with the commit?

Hi @esdccs1 , the issue is Azure Portal display issue, there is no fix in the provider for this.

**Comment by esdccs1** [comment]
@teowa whenever its a portal issue is there a specific github repo I can open an issue in to track it?

**Comment by teowa** [comment]
@esdccs1 @Milindkg97 This should be fixed now. If we set `*` for facilityNames & logLevels, the Portal now looks like:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/28a26ede-3b19-41e1-87e4-c84001d09edd)
