### ISSUE TITLE
share_properties smb object produces changes for premium storage account

### ISSUE THREAD

**Issue by elesandroo** [hashicorp/terraform-provider-azurerm#21182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_storage_account" "storage_account" {
  name                     = "teststorageaccount"
  resource_group_name      = "testRG"
  location                 = "northeurope"
  account_tier             = "Premium"
  account_replication_type = "LRS"
  account_kind             = "FileStorage"

  share_properties {
    retention_policy {
      days = 5
    }
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # module.sa.azurerm_storage_account.storage_account["xxxxxxx"] will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
      ~ share_properties {

          - smb {
              - authentication_types            = [] -> null
              - channel_encryption_type         = [] -> null
              - kerberos_ticket_encryption_type = [] -> null
              - multichannel_enabled            = false -> null
              - versions                        = [] -> null
            }

            # (1 unchanged block hidden)
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

No changes should be found when running `terraform plan`.

### Actual Behaviour

For Storage Account with `account_tier = "Premium"` and `account_kind = "FileStorage"`, Terraform is trying to make changes to the `smb` variable, whether it is configured or not.

### Steps to Reproduce

1. `terraform apply` on the file posted above
2. `terraform plan` or `terraform apply` on the exact same file without changing anything

**Comment by jptacnik** [comment]
I have the same issue. Any updates?

**Comment by magodo** [comment]
@elesandroo We are now deprecating the use of "Optional + Computed" for properties that have default value from API, even if users haven't specified them in the request. In this case, users are expected to explicitly ignore those properties. For your specific case, you can refer to this: https://github.com/hashicorp/terraform-provider-azurerm/pull/21226/files#diff-4f9906e7fa788bca7bf275f811f2bb83e477040899f0da7b51ee414c8175340dR4405-R4407
