### ISSUE TITLE
Support for Azure Cost Management saved views and subscriptions

### ISSUE THREAD

**Issue by dbsanfte** [hashicorp/terraform-provider-azurerm#21198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems the AzureRM provider does not yet support saved views and email subscriptions to those views as first-class resources. 

https://learn.microsoft.com/en-us/azure/templates/microsoft.costmanagement/views?pivots=deployment-language-terraform#resource-format-2

https://learn.microsoft.com/en-us/azure/templates/microsoft.costmanagement/scheduledactions?pivots=deployment-language-terraform#resource-format-2

While the existing support is 'adequate' it's not great and the provider would benefit from having these natively.

### New or Affected Resource(s)/Data Source(s)

azurerm_subscription_cost_management_view
azurerm_subscription_cost_management_view_scheduled_action

**Comment by aristosvo** [comment]
I'll take a look!
