### ISSUE TITLE
`azurerm_app_configuration_keys` datasource: regression

### ISSUE THREAD

**Issue by favoretti** [hashicorp/terraform-provider-azurerm#21206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

@teowa https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appconfiguration/app_configuration_keys_data_source.go#L138

This change broke it again. :)

```
│ Error: fetching keys for "AppConfiguration Nested Item Configuration Store Endpoint \"[https://terraform.azconfig.io\"] / Key \"terraform/atlas/data-cxxxx-config\" / Label \"\"": appconfiguration.BaseClient#getKeyValuesNextResults: Failure preparing next results request: StatusCode=0 -- Original Error: autorest: No scheme detected in URL /kv?api-version=1.0&key=terraform%2Fatlas%2Fdata-collection-config&after=dGVycmFmb3JtL2F0bGxxxxcKaW5kdXN0cnktdmVydGljYWw%3D
```

Pagination links don't include the endpoint, so somehow the change you made emptied it again. Want me to roll back or debug your change? 

### Terraform Version

1.4.2

### AzureRM Provider Version

3.49

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_keys

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

**Comment by teowa** [comment]
Hi @favoretti , apologize for introducing a regression.
I have sent PR to fix this.

**Comment by favoretti** [comment]
Awesome, thanks a lot!
