### ISSUE TITLE
Issue with validation of `firewall_policy_id` for `azurerm_application_gateway` added in `v3.50.0`

### ISSUE THREAD

**Issue by Laffs2k5** [hashicorp/terraform-provider-azurerm#21224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
# Note this is just the example usage code with 'firewall_policy_id' added to the 'http_listener' block

locals {
  # make sure this points to a WAF policy that exists  
  my_policy_id = "/subscriptions/<EXISTING SUB>/resourceGroups/<EXISTING RG>/providers/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/<NAME OF EXISTING WAF POLICY>"
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  address_space       = ["10.254.0.0/16"]
}

resource "azurerm_subnet" "frontend" {
  name                 = "frontend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.254.0.0/24"]
}

resource "azurerm_subnet" "backend" {
  name                 = "backend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.254.2.0/24"]
}

resource "azurerm_public_ip" "example" {
  name                = "example-pip"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Dynamic"
}

# since these variables are re-used - a locals block makes this more maintainable
locals {
  backend_address_pool_name      = "${azurerm_virtual_network.example.name}-beap"
  frontend_port_name             = "${azurerm_virtual_network.example.name}-feport"
  frontend_ip_configuration_name = "${azurerm_virtual_network.example.name}-feip"
  http_setting_name              = "${azurerm_virtual_network.example.name}-be-htst"
  listener_name                  = "${azurerm_virtual_network.example.name}-httplstn"
  request_routing_rule_name      = "${azurerm_virtual_network.example.name}-rqrt"
  redirect_configuration_name    = "${azurerm_virtual_network.example.name}-rdrcfg"
}

resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.frontend.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 80
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.example.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Http"
    firewall_policy_id             = local.my_policy_id
  }

  request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: ID was missing the `firewallPolicies` element
│ 
│   with module.main.module.network.azurerm_application_gateway.gateway,
│   on ../../modules/network/application_gateway.tf line 174, in resource "azurerm_application_gateway" "gateway":
│  174: resource "azurerm_application_gateway" "gateway" {
│ 
╵
```

### Expected Behaviour

Plan should pass.

### Actual Behaviour

Plan results in error.

### Steps to Reproduce

- Bump azurerm in your project using `azurerm_application_gateway` from earlier version to `3.50.0`
- Watch plan /apply fail

### References

This is a regression introduced with #21129 where the `firewall_policy_id` of `http_listener` blocks and `azurerm_application_gateway` itself is attempted to be validated as `Microsoft.Network/firewallPolicies` when it should be validated as `Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies`.

AFAIK the fix should be fairly simple:
Change [L20 of terraform-provider-azurerm/internal/services/network
/application_gateway_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.50.0/internal/services/network/application_gateway_resource.go#L20) from:
```golang
firewallValidate "github.com/hashicorp/terraform-provider-azurerm/internal/services/firewall/validate"
```

to
```golang
firewallValidate "github.com/hashicorp/terraform-provider-azurerm/internal/services/network/validate"
```

Then change `ValidateFunc` on [L543](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.50.0/internal/services/network/application_gateway_resource.go#L543) and [L1507](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.50.0/internal/services/network/application_gateway_resource.go#L1507) to use `firewallValidate.ApplicationGatewayWebApplicationFirewallPolicyID` instead of `firewallValidate.FirewallPolicyID`.

**Comment by marciobarbato** [comment]
Hi I have the same issue deploying application gateways with 3.50, 3.49 was working fine.

**Comment by tombuildsstuff** [comment]
hey @Laffs2k5 

Thanks for opening this issue / apologies for this regression.

I've opened #21238 which fixes this by updating the validation to check that a Application Gateway Web Application Firewall Policy ID is specified rather than a Firewall Policy ID - in the interim you should be able to temporarily pin your provider version to `= v3.49.0` to workaround this, but #21238 will go into the next release.

Thanks!

**Comment by marciobarbato** [comment]
@tombuildsstuff  Hi Tom, I just upgraded to latest provider (3.51) and I still see the error related to policy ids

Error: ID was missing the `ApplicationGatewayWebApplicationFirewallPolicies` element

@Laffs2k5  have you checked yours ?

**Comment by shlomimn** [comment]
@tombuildsstuff Hi Tom, still get the same problem with provider version 3.62

Planning failed. Terraform encountered an error while generating this plan.

```
Initializing modules...

Initializing provider plugins...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v3.62.1
...
...
╷
│ Error: ID was missing the `ApplicationGatewayWebApplicationFirewallPolicies` element
│ 
│   with module.appgw-hub.azurerm_application_gateway.this["applicationGateway"],
│   on .terraform/modules/appgw-hub/azure/application-gateway/main.tf line 20, in resource "azurerm_application_gateway" "this":
│   20:   firewall_policy_id                = var.firewall_policy_id

```

**Comment by danielfears** [comment]
> @tombuildsstuff Hi Tom, still get the same problem with provider version 3.62.1
> 
> Planning failed. Terraform encountered an error while generating this plan.
> 
> ```
> Initializing modules...
> 
> Initializing provider plugins...
> - Reusing previous version of hashicorp/azurerm from the dependency lock file
> - Using previously-installed hashicorp/azurerm v3.62.1
> ...
> ...
> ╷
> │ Error: ID was missing the `ApplicationGatewayWebApplicationFirewallPolicies` element
> │ 
> │   with module.appgw-hub.azurerm_application_gateway.this["applicationGateway"],
> │   on .terraform/modules/appgw-hub/azure/application-gateway/main.tf line 20, in resource "azurerm_application_gateway" "this":
> │   20:   firewall_policy_id                = var.firewall_policy_id
> ```

To add to this, currently have a requirement to pin the provider to 3.56 for deployment of AVNM resources, seeing the same error on 3.56. @tombuildsstuff

**Comment by marciobarbato** [comment]
Gents,  mine was still broken because validation is case sensitive, I added issue https://github.com/hashicorp/terraform-provider-azurerm/issues/22562 for that
