### ISSUE TITLE
azurerm_container_app - Support for using system assigned managed identity in registry block

### ISSUE THREAD

**Issue by DerekPaniagua** [hashicorp/terraform-provider-azurerm#21242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, container apps can be configured to use a "user assigned" managed identity to authenticate with a private Azure container registry. However, Azure also supports using a "system assigned" managed identity to authenticate with a ACR. The current documentation under the registry block states:

identity - (Optional) Resource ID for the **User Assigned** Managed identity to use when pulling from the Container Registry.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
Perhaps the following configuration could support this feature.

identity {
    type = "SystemAssigned"
}
registry {
    server   = "exampleregistry.azurecr.io"
    identity = "SystemAssigned"
}
```

### References

[Previous issue for supporting managed identities](https://github.com/hashicorp/terraform-provider-azurerm/issues/20412)

**Comment by DerekPaniagua** [comment]
This functionality is already supported by using the following:
```

identity {
    type = "SystemAssigned"
}
registry {
    server   = "exampleregistry.azurecr.io"
    identity = "system"
}
```
 However, it should still be documented in the Terraform Container App documentation.

**Comment by dhilgarth** [comment]
Except that this doesn't seem to work. My resource definition:

```
resource "azurerm_container_app" "app" {
  name                         = var.app_name
  resource_group_name          = var.resource_group_name
  container_app_environment_id = var.environment_id
  revision_mode                = "Multiple"
  identity {
    type = "SystemAssigned"
  }
  registry {
    server = "${var.container_registry_name}.azurecr.io"
    identity = "system"
  }
  template {
    container {
      name   = var.app_name
      image  = "vad1mo/hello-world-rest"
      cpu    = var.cpu
      memory = var.memory
      startup_probe {
        port      = 5050
        transport = "HTTP"
      }
      liveness_probe {
        port      = 5050
        transport = "HTTP"
      }
      readiness_probe {
        port      = 5050
        transport = "HTTP"
      }
    }
    min_replicas = 1
  }
  lifecycle {
    ignore_changes = [
      template[0].container[0].image
    ]
  }
}
```

This will fail with:

```
module.containerapp.azurerm_container_app.app: Still creating... [10m11s elapsed]
╷
│ Error: creating Container App (Subscription: "XXX"
│ Resource Group Name: "myapp-local-dev"
│ Container App Name: "myapp"): polling after CreateOrUpdate: Code="ContainerAppOperationError" Message="Failed to provision revision for container app 'myapp'. Error details: Operation expired."
│
│   with module.containerapp.azurerm_container_app.app,
│   on modules\containerapp\main.tf line 14, in resource "azurerm_container_app" "app":
│   14: resource "azurerm_container_app" "app" {
│
│ creating Container App (Subscription: "XXX"
│ Resource Group Name: "myapp-local-dev"
│ Container App Name: "myapp"): polling after CreateOrUpdate: Code="ContainerAppOperationError" Message="Failed to
│ provision revision for container app 'myapp'. Error details: Operation expired."
╵
```

Which is also visible in the portal:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1180105/b466b892-ce45-4a97-9376-934bc56d5e89)

When I remove the `registry` block, the container app is created after just 40 seconds.

**Comment by bvanskiver** [comment]
I was successfully able to use a system assigned identity, but it requires configuring the resources in multiple steps (which are far from ideal).

I get the same error as @dhilgarth if I try to create a container app initially with the system assigned identity, but if I instead set up the resource using the following steps it accomplishes the desired outcome:
1. Create the `azurerm_container_app` resource without `identity` and `registry` blocks
2. Add the `identity` and `registry` blocks and apply the update
3. Add `azurerm_role_assignment` resource and apply the update (example of this block is below)
4. Now can reference an image from the registry in the `container` block

```
resource "azurerm_role_assignment" "pull" {
  scope                = azurerm_container_registry.example.id
  role_definition_name = "AcrPull"
  principal_id         = azurerm_container_app.example.identity[0].principal_id
}
```

My version information:
```
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v3.57.0
```

**Comment by jtatum** [comment]
I think this is why we need to use user-managed identities - in order to support initial provisioning. Otherwise, you have a chicken and egg problem:

1. Container app needs to exist for identity to exist
2. Identity needs to exist to be added to ACR repo
3. Container app can't pull from ACR repo, so creation fails, blocking 1.

@bvanskiver mentions a workaround, by commenting out / temporarily creating without using this identity... But probably the best fix is just to use a user managed identity.

1. Create user managed identity
2. Grant it permissions to ACR
3. Create container app, specify ACR role grant as a `depends_on` resource.

I do think the docs should be updated to note that using a system assigned identity with the registry isn't a good idea. It might work if your container app needs other Azure permissions.

**Comment by jason-berk-k1x** [comment]
yeah, thats what I did and it _seems_ to work.....  my user assigned identiy grants AcrPull and access to a key vault used by everyone in the sub.  The system assigned identity grants access to a key vault specifically for the job

```
  identity {
    type = "SystemAssigned, UserAssigned"
    identity_ids = [
      data.azurerm_user_assigned_identity.aca_workload.id
    ]
  }

  registry {
    server   = data.azurerm_container_registry.acr.login_server
    identity = data.azurerm_user_assigned_identity.aca_workload.id
  }
```
