### ISSUE TITLE
azurerm_subscription expects two resource ID segments for subscription ID

### ISSUE THREAD

**Issue by larsakerlund** [hashicorp/terraform-provider-azurerm#21241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_subscription

### Terraform Configuration Files

```hcl
resource "azurerm_subscription" "main" {
  subscription_name = var.subscription_name
  subscription_id   = var.subscription_id
  workload          = var.subscription_type
}
```

### Debug Output/Panic Output

```shell
azurerm_subscription.main: Refreshing state... [id=/providers/Microsoft.Subscription/aliases/6aa52e66-fbc8-4a3e-87a1-9c5a9cbd5c63]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_subscription.main will be updated in-place
  ~ resource "azurerm_subscription" "main" {
        id                = "/providers/Microsoft.Subscription/aliases/6aa52e66-fbc8-4a3e-87a1-9c5a9cbd5c63"
      ~ subscription_name = "test" -> "test_new"
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_subscription.main: Modifying... [id=/providers/Microsoft.Subscription/aliases/6aa52e66-fbc8-4a3e-87a1-9c5a9cbd5c63]
╷
│ Error: could not parse Subscription ID from Alias: parsing "bd276562-439c-4de7-9f08-8d8e58c27c98": expected 2 segments within the Resource ID but got 1 for "bd276562-439c-4de7-9f08-8d8e58c27c98"
│
│   with azurerm_subscription.main,
│   on main.tf line 31, in resource "azurerm_subscription" "main":
│   31: resource "azurerm_subscription" "main" {
│
╵
```

### Expected Behaviour

Subscription name should have been updated.

### Actual Behaviour

Provider fails due to invalid number of segments in the subscription ID.

### Steps to Reproduce

1. Create alias for existing subscription using `terraform apply`.
2. Rename subscription and run `terraform apply` again.

### Important Factoids

Creating the alias works well. Updating it is what fails. Importing the alias makes no difference.

**Comment by ms-zhenhua** [comment]
Hi @larsakerlund, thank you for reporting this issue. I have created a PR to fix this issue.

**Comment by crower19** [comment]
I have the same error. Only happens on 3.50.0. I can confirm that on 3.49.0 version, works fine

**Comment by DevMan01** [comment]
I too can confirm 3.50 breaks our pipelines. We've rolled back to 3.49 with success. We're declining new versions of the provider until this bug is fixed as it is breaking.

**Comment by mph-adi-garg** [comment]
Having same issue in 3.44.0
