### ISSUE TITLE
Support for Caching feature in Azure Container Registry(ACR)

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#21258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Caching for ACR allows you to create a cache rule and cache container images from Docker Hub and Microsoft Artifact Registry. Caching images lets you pull images directly from your cache ensuring faster and more reliable pull operations.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Potential Terraform Configuration

```hcl
resource "azurerm_container_registry" "acr" {
  name                = "containerRegistry1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Premium"
  admin_enabled       = false
  georeplications {
    location                = "East US"
    zone_redundancy_enabled = true
    tags                    = {}
  }
  cache_rule {
    name                    = "name"
    registry                = "registry"
    source-repo             = "source-repo"
    target-repo             = "target-repo"
  }
  georeplications {
    location                = "North Europe"
    zone_redundancy_enabled = true
    tags                    = {}
  }
}
```

### References

https://aka.ms/acr/cache

**Comment by neko1101** [comment]
Hey guys,

any update on this, we hit the dockerhub rate limit lately..

**Comment by nclaeys** [comment]
Since yesterday the go-azure-sdk supports apiversion 2023-07-01 for the containerregistry, which has support for cacherules. Now the functionality can be implemented in the terraform provider. I am not sure when I will find time to start on it, so if someone else wants to give it a go, be my guest. More details can be found [here](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/containerregistry/2023-07-01/cacherules)

**Comment by bkarakashev** [comment]
@tombuildsstuff he ACR Cache rules are not our of preview and in production. Are you able to add support for it in terraform?
Many thanks

**Comment by kevinharing** [comment]
We're longing for this as well, by September 30 new dockerhub rate limiting will come into effect and this would make things easier to manage.

**Comment by kevinharing** [comment]
[It's now GA.](https://azure.microsoft.com/en-us/updates/generally-available-artifact-cache-for-azure-container-registry/)

**Comment by JoachimHansEDDI** [comment]
Hi there

Did you find some time to work on it? @nclaeys

**Comment by nclaeys** [comment]
@JoachimHansEDDI I did not get to it yet. Feel free to take it over, I am a bit swamped with other work in the coming weeks.

**Comment by JoachimHansEDDI** [comment]
> @JoachimHansEDDI I did not get to it yet. Feel free to take it over, I am a bit swamped with other work in the coming weeks.

I have no clue about development. ;-)

**Comment by bkarakashev** [comment]
Please, any update on this?

**Comment by webstean** [comment]
Any update, currently a BIG gap in azurerm support IMHO

**Comment by mhaligowski** [comment]
I'm an independent contributor, started working on it!

**Comment by JoachimHansEDDI** [comment]
> I'm an independent contributor, started working on it!

Thanks a lot @mhaligowski

**Comment by JoachimHansEDDI** [comment]
Morning @mhaligowski 

I see your PR https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fhashicorp%2Fterraform-provider-azurerm%2Fissues%2F21258

What/Who is the showstopper here or how is the process to get this merged?

**Comment by mhaligowski** [comment]
@JoachimHansEDDI evening, I'm still working on it! I think core of the development is done, I was able to run some base tests. The things left are:

* optional credentials,
* tests.

I've been busy with my professional project, which actually requires this change! I hope to get it finished within the next two weeks, with some more spotty people's availability over the holidays.

Sorry if this is putting you in an inconvenient position, I'm working on it in my spare time.

**Comment by janlauber-swissgrid** [comment]
any news on that?

**Comment by ashwajce** [comment]
Any latest news on this please?

**Comment by nguyenhung1121990** [comment]
There is currently looking that not supported by terraform yet. However I am using azapi terraform functions and it works.

MS Docs: https://learn.microsoft.com/en-us/azure/templates/microsoft.containerregistry/2023-01-01-preview/registries/cacherules?pivots=deployment-language-terraform

**Comment by danvy** [comment]
It's been a year since this feature was introduced 🎂

**Comment by npk-amperon** [comment]
Heads-up that I've springboarded off @mhaligowski's work and have a PR ready for review. I've run the acceptance tests locally (and built the provider and poked around manually).
