### ISSUE TITLE
Support for not changing license_type if nothing specified

### ISSUE THREAD

**Issue by mwsutherland** [hashicorp/terraform-provider-azurerm#21266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to leave the license_type of a azurerm_windows_virtual_machine alone if that option isn't specified? We have a process which dynamically allocates our hybrid Windows licenses to our largest VMs (to get most bang for the buck), so we don't want to specify whether a VM does or does not have a license in Terraform. Leaving out that option assumes that it should be set to 'none', unlicensing any TF-managed VMs every time we apply a change.

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

**Comment by StefanSchoof** [comment]
Did you try the ignore_changes argument?
 https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes

**Comment by mwsutherland** [comment]
Ooooo! I was unaware of that! I will check that out tomorrow and let you know if it solves our problem.
