### ISSUE TITLE
Support for exporting Azure resource identifier for `azurerm_key_vault_certificate`

### ISSUE THREAD

**Issue by andyadamides** [hashicorp/terraform-provider-azurerm#21261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `azurerm_key_vault_certificate` [resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/key_vault_certificate#attributes-reference), does not support exporting the Azure resource id for a certificate that is in an Azure Key Vault. It only exports the HTTPS link for that certificate, i.e. `https://<kv_name>.vault.azure.net/certificates/<cert_name>`.

The Azure KV Certificate id is of this form:
`/subscriptions/<sub_id>/resourceGroups/<rg_id>/providers/Microsoft.KeyVault/vaults/<kv_name>/certificates/<cert_name>`

Not having the Azure certificate id can cause downstream issues such as when trying to do fine-grained individual IAM role assignments to the certificate level, since the `scope` in `azurerm_role_assignment` does not support the `HTTPS` format.

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificate

### Potential Terraform Configuration

```hcl
output "kv_cert_raw_id" {
  value       = azurerm_key_vault_certificate.kv_certificate.raw_id
  description = "The Key Vault Certificate Azure Resource Raw ID."
}
```

**Comment by wuxu92** [comment]
hi @andyadamides is there any document or definition about the Azure resource manager ID for the KeyVault certificate? I find no such id from all APIs about certificates.

**Comment by andyadamides** [comment]
> hi @andyadamides is there any document or definition about the Azure resource manager ID for the KeyVault certificate? I find no such id from all APIs about certificates.

It was very hard for me to find one, but the way I did it was:
1. In the Azure Portal I went in the IAM part of a certificate I created
2. Added a role assignment for that certificate again manually from the portal
3. The, using the az cli: `az role assignment list --all` and this returned the role assignment for the certificate I had just added in the portal with this scope: `"scope": "/subscriptions/<sub_id>/resourceGroups/<rg_name>/providers/Microsoft.KeyVault/vaults/<kv_name>/certificates/<cert_name>"`

**Comment by wuxu92** [comment]
Hi @andyadamides could you use [data-sources/key_vault_secret#resource_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secret#resource_id) to get the resource id of secret?

**Comment by andyadamides** [comment]
> Hi @andyadamides could you use [data-sources/key_vault_secret#resource_id](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secret#resource_id) to get the resource id of secret?

But I cannot do this all in the same TF script: create a certificate using `azurerm_key_vault_certificate`, then use the above "data" block to get the secret(even if it is available, because this secret is not even shown in the azure portal in Secrets), and then in the same script use it in downstream resources(in my case `azurerm_role_assignment`)

**Comment by andyadamides** [comment]
@wuxu92 wdyt?

**Comment by wuxu92** [comment]
Hi @andyadamides could you please share an example configuration of your `azurerm_key_vaule_certificate`? i tried with my local env and did not get the secret field of the certificate resource.

**Comment by andyadamides** [comment]
> Hi @andyadamides could you please share an example configuration of your `azurerm_key_vaule_certificate`? i tried with my local env and did not get the secret field of the certificate resource.

```terraform
resource "azurerm_key_vault_certificate" "kv_certificate" {
  name         = module.naming_kv_certificate.result
  key_vault_id = var.key_vault_resource_id

  certificate_policy {
    issuer_parameters {
      name = var.issuer_parameters_issuer_name
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    lifetime_action {
      action {
        action_type = var.lifetime_action
      }

      trigger {
        days_before_expiry = var.lifetime_action_days_before_expiry
      }
    }

    secret_properties {
      content_type = var.secret_props_content_type
    }

    x509_certificate_properties {

      extended_key_usage = var.x509_cert_extended_key_usages
      key_usage          = var.x509_cert_key_usages

      subject_alternative_names {
        dns_names = var.san_dns_names
      }

      subject            = "CN=____"
      validity_in_months = var.x509_cert_key_validity_months
    }
  }


}
```

**Comment by wuxu92** [comment]
there is an empty secret field in the certificate by your configuration.. could you please create a new issue to describe your problem instead of continuning this thread?
