### ISSUE TITLE
Support for --custom-ca-trust-certificates for AKS clusters

### ISSUE THREAD

**Issue by jugash** [hashicorp/terraform-provider-azurerm#21284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Issue #18391 adds support for enabling custom CA trust store on AKS clusters but it doesn't allow specifying the path to the custom CA trust certificates. To configure a new AKS cluster to use custom CA with CAs installed before node boots up, this feature is needed.

`az aks create 
    --resource-group myResourceGroup 
    --name myAKSCluster 
    --node-count 2 
    --enable-custom-ca-trust 
    --custom-ca-trust-certificates pathToFileWithCAs`

More details : https://learn.microsoft.com/en-us/azure/aks/custom-certificate-authority

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
custom_ca_trust_certificates = {
  "key1" : {
     secretName : "secret1",
     vaultName  : "vault1"
  },
  "key2" : {
     secretName : "secret2",
     vaultName  : "vault2"
  },
  

}
```

**Comment by dkuzmenok** [comment]
Trust certificates are part of `2023-03-02-preview` Rest API:
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2023-03-02-preview/managedclusters?pivots=deployment-language-bicep#managedclustersecurityprofile
