### ISSUE TITLE
Support for azurerm_automation_hybrid_runbook_worker to install extension

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/terraform-provider-azurerm#21280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm not sure if this is a bug but after using azurerm_automation_hybrid_runbook_worker to manage some VMs as hybrid workers, the machines have no last seen time in the Azure portal and do not have the extension installed.

If this is the expected behaviour, can it install the extension as well?

### New or Affected Resource(s)/Data Source(s)

azurerm_automation_hybrid_runbook_worker

### Potential Terraform Configuration

```hcl
N/A
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_hybrid_runbook_worker

**Comment by wuxu92** [comment]
hi @ASHR4 thanks for your feedback. this behavior is expected and you can use the [virtual_machine_extension](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_extension) resource to managed the extension. `automation_hybrid_runbook_worker` will only manage the worker itself.

reference: https://learn.microsoft.com/en-us/azure/automation/extension-based-hybrid-runbook-worker-install?tabs=windows%2Crest-api#manage-hybrid-worker-extension-using-bicep--arm-templates-rest-api-azure-cli-and-powershell.

**Comment by mfuellbier** [comment]
Hi, I am struggling with this as well. What do you need to put into the `settings` section of the `azurevm_virtual_machine_extension` resource in terraform, to install the hybrid worker extension?

**Comment by ASHR4** [comment]
@mfuellbier the settings require the AutomationAccountURL it's connecting to:

`
{
      "AutomationAccountURL" : "${azurerm_automation_account.hybrid_service_url}"
}
`

The Hybrid Worker VMs, then require a system assigned identity.

Let me know if you need anything else :)
