### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert creation intermittently fails after creating the Log Analytics Workspace in the same TF apply

### ISSUE THREAD

**Issue by JoshStead** [hashicorp/terraform-provider-azurerm#21281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
// time_sleep resource to fix intermittent occurrences of "The workspace could not be found" errors
// from resource azurerm_monitor_scheduled_query_rules_alert.monitor_alert and azurerm_monitor_scheduled_query_rules_alert.network_resources
resource "time_sleep" "post_law_creation_wait_30s" {
  depends_on = [
    module.log_analytics_default
  ]

  create_duration = "30s"
}

resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert" {
  for_each = lower(var.ARM_LOCATION) == "uksouth" ? var.monitor_alerts.query_alerts : {}

  name                = each.key
  location            = var.ARM_LOCATION
  resource_group_name = module.bes_function_app.resource_group_name

  action {
    action_group = [azurerm_monitor_action_group.teams[0].id]
  }

  auto_mitigation_enabled = true
  data_source_id          = module.log_analytics_default.id
  description             = local.query_alerts_definitions[each.key].description
  enabled                 = each.value.enabled
  query                   = <<-QUERY
        ${local.query_alerts_definitions[each.key].query}
    QUERY

  severity    = each.value.severity
  frequency   = each.value.frequency
  time_window = each.value.time_window

  trigger {
    operator  = each.value.trigger.operator
    threshold = each.value.trigger.threshold
  }

  tags = var.global_settings.tags

  depends_on = [
    time_sleep.post_law_creation_wait_30s
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: creating or updating Monitor Scheduled Query Rules: (Scheduled Query Rule Name "monitor_vm_disk_space_5" / Resource Group "abc"): insights.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="{\r\n  \"error\": {\r\n    \"message\": \"The workspace could not be found\",\r\n    \"code\": \"WorkspaceNotFoundError\",\r\n    \"correlationId\": \"xyz\"\r\n  }\r\n}"
│ 
│   with azurerm_monitor_scheduled_query_rules_alert.monitor_alert["monitor_vm_disk_space_5"],
│   on scheduled_query_rules_alerts.tf line 209, in resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert":
│  209: resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert" {
│ 
╵

╷
│ Error: creating or updating Monitor Scheduled Query Rules: (Scheduled Query Rule Name "monitor_vm_memory" / Resource Group "abc"): insights.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="{\r\n  \"error\": {\r\n    \"message\": \"The workspace could not be found\",\r\n    \"code\": \"WorkspaceNotFoundError\",\r\n    \"correlationId\": \"xyz\"\r\n  }\r\n}"
│ 
│   with azurerm_monitor_scheduled_query_rules_alert.monitor_alert["monitor_vm_memory"],
│   on scheduled_query_rules_alerts.tf line 209, in resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert":
│  209: resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert" {
│ 
╵
╷
│ Error: creating or updating Monitor Scheduled Query Rules: (Scheduled Query Rule Name "monitor_vm_disk_space_10" / Resource Group "abc"): insights.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="NotFound" Message="{\r\n  \"error\": {\r\n    \"message\": \"The workspace could not be found\",\r\n    \"code\": \"WorkspaceNotFoundError\",\r\n    \"correlationId\": \"xyz\"\r\n  }\r\n}"
│ 
│   with azurerm_monitor_scheduled_query_rules_alert.monitor_alert["monitor_vm_disk_space_10"],
│   on scheduled_query_rules_alerts.tf line 209, in resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert":
│  209: resource "azurerm_monitor_scheduled_query_rules_alert" "monitor_alert" {
```

### Expected Behaviour

The Scheduled Query Rule Alert should create.

### Actual Behaviour

The Terraform apply will intermittently fail with the messages from the output. 

Currently there is a high chance that it will fail, e.g 2 out of 3 runs will fail. 

Rerunning the Terraform apply after a failure the Scheduled Query Rule Alert rules will create successfully. We have tried to use a time_sleep after the LAW creation but this has not fixed the issue. 

Looking at the other open issue here[https://github.com/hashicorp/terraform-provider-azurerm/issues/17145](url)

I can see the below for the LAW - I see the PUT, then a OK message. I dont see a **201 Created** message

2023-04-04T09:52:18.612Z [DEBUG] provider.terraform-provider-azurerm_v2.99.0_x5: AzureRM Request: 
PUT /subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/abc/providers/Microsoft.OperationalInsights/workspaces/xxx?api-version=2020-08-01 HTTP/1.1
Host: management.azure.com

2023-04-04T09:52:19.412Z [DEBUG] provider.terraform-provider-azurerm_v2.99.0_x5: AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/abc/providers/Microsoft.OperationalInsights/workspaces/xxx?api-version=2020-08-01: 
HTTP/2.0 200 OK

### Steps to Reproduce

Terraform init
Terraform validate
Terraform plan
Terraform apply

### References

There is already a open case but there has never been any troubleshooting after an initial repsonce by someone

https://github.com/hashicorp/terraform-provider-azurerm/issues/17145

**Comment by teowa** [comment]
Hi @JoshStead , thanks for submitting this issue.

This might happen due to SDK issue or service API issue. The legacy 2.99.0 version of the provider was released year ago. It is hard to make a fix release for the 2.x version now. Since both Azure and Terraform's Azure Provider move quickly, I really recommend you to try the new [3.x versions](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace) of the provider which should be capable for this scenario. I can successfully create the scheduled query rule with latest 3.50.0 version of the provider. A possible workaround if cannot upgrade to 3.x version is to prelong the sleep time, maybe try sleep for several minutes.

**Comment by manicminer** [comment]
Hi @JoshStead, thanks for reporting this. As @teowa mentioned, v2.x releases are fairly old at this point and we can no longer issue fixes for the v2 series. Accordingly, I'm going to close this issue for now, however if you still encounter problems after upgrading to the latest v3.x release, please feel free to comment further and we'll be happy to re-open and take another look at this. Thanks!
