### ISSUE TITLE
Support for documention in azurerm_application_gateway require_sni in http_listener

### ISSUE THREAD

**Issue by breys-eiffage** [hashicorp/terraform-provider-azurerm#21298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The documentation for azurerm_application_gateway is not complete. 

Please add the default value of the parameter require_sni in http_listener block. 

In Terraform, the default value is false but in Azure Portal, the default value is true. it can be confusing when you are using multiple ssl_certificate.

### New or Affected Resource(s)/Data Source(s)

azurerm_application_gateway

**Comment by sinbai** [comment]
@breys-eiffage thanks for your feedback. PR #21332 has been submitted to fix it.
