### ISSUE TITLE
Support for minimalTlsVersion in azurerm_cosmosdb_account

### ISSUE THREAD

**Issue by tobias-heller** [hashicorp/terraform-provider-azurerm#21294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to request a new feature for the azurerm_cosmosdb_account in the Azure Resource Manager API. With the release of the 2022-11-15 API version of the Azure Cosmos DB Resource Provider API, it is now possible to set the minimum TLS version for Cosmos DB accounts.

Currently, the only way to set the minimum TLS version is through the [Azure API](https://learn.microsoft.com/en-us/azure/cosmos-db/self-serve-minimum-tls-enforcement). However, it would be beneficial for users to have the ability to set the minimum TLS value to 1.2 through the [azurerm_cosmosdb_account ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account) resource. 

Although it is a standard for new Cosmos DB accounts to have a minimum TLS version of 1.2 since April 1, 2023, this feature would still be useful for users who have existing Cosmos DB accounts and need to update the minimum TLS version.
Possible values for `minimalTlsVersion` could be:

-  `Tls `for setting the minimum version to TLS 1.0.
- `Tls11` for setting the minimum version to TLS 1.1.
- `Tls12` for setting the minimum version to TLS 1.1.

I believe that adding this feature to azurerm_cosmosdb_account would greatly improve the user experience for managing Cosmos DB accounts through the Azure Resource Manager API.

Thank you for considering my feature request.

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  minimalTlsVersion   = "Tls12"

  geo_location {
    location          = "eastus"
    failover_priority = 1
  }
}
```

### References

Azure TLS version enforcement documentation: https://learn.microsoft.com/en-us/azure/cosmos-db/self-serve-minimum-tls-enforcement

**Comment by sehgalnamit** [comment]
The reason that the account didn't default to TLS1.2 is that the API version used to submit the request was not the minimum required 2022-11-15 (in this case, it had 2021-10-15). If Terraform doesn't use consistent API versions then it could result in such behavior.
