### ISSUE TITLE
azurerm_api_management refresh Azure Custom Domain Built in while it should not

### ISSUE THREAD

**Issue by raphaeldeletoille** [hashicorp/terraform-provider-azurerm#21299]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"

    proxy {
      host_name = "our custom domain"
      certificate = XXX
    }
}
```

### Debug Output/Panic Output

```shell
No need
```

### Expected Behaviour

This is supposed to deploy an APIM and a Custom Domain Gateway. 

### Actual Behaviour

It is working fine and deploy an APIM and a Custom Domain Gateway.

But on each apply after the first deployment terraform try to edit the Custom Domain Built in (deployed by Azure when Apim is deployed) and replace it with our Custom Domain Gateway declared in the TF Configuration file. This is because when terraform refresh the APIM, it detect two custom domain and will place in list 0 the custom domain built in created by Azure and in list 1 the custom domain gateway provided in tf file. It does not have a major impact but will slow the tf build on each apply and pollute the terraform plan. 

To fixe this "issue" i've had to explicitly declare the Custom Domain Built In from Azure in the Tf Configuration file, it is for sure not the best solution as it should not be present in the terraform configuration file because it is a custom domain managed by Azure  :

    proxy {
      host_name = "Azure Custom Domain Built in"
    }

    proxy {
      host_name = "our custom domain"
      certificate = XXX
    }

This fixe the issue but terraform should not refresh the Azure Custom Domain Built in and place it in list 0

**Comment by xuzhang3** [comment]
@raphaeldeletoille you are right you need to put the built-in domain first as it is auto-created by the service. In some scenario,  customer want to change the default built in domain configurations so the built-in domain cannot be ignored.

**Comment by raphaeldeletoille** [comment]
@xuzhang3  the built in domain can not be edited as it is auto managed by Azure --> Default is: <apim-service-name>.azure-api.net 
Then i can indeed change the apim name but why should we keep the Built In if it is not possible to directly manage it and might cause some issue like the one described ?

**Comment by xuzhang3** [comment]
@raphaeldeletoille built-in domain used to be ignored by AzureRM. But in some scenario, cx want want to change the configurations like `negotiate_client_certificate` so we add it back.
Ref: #16065

**Comment by raphaeldeletoille** [comment]
Ok i get it ! Didn't know it was possible to manage that setting for the Built In. Maybe it could be great to add that to the documentation as it can create some confusion. I didn't expect that the Built In Domain would be targeted if i not declare it explictly in the configuration file. You can close this issue then. Have a nice day :)
