### ISSUE TITLE
Can't create psql flexible server. Message="The value of the 'Version' should be in: []

### ISSUE THREAD

**Issue by samuelhornbyparallo** [hashicorp/terraform-provider-azurerm#21306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "psql" {
  for_each = azurerm_resource_group.stapp
  name                   = "psql-srv-${local.deployment_map[each.key].workload}-stapp-${var.env}-${local.deployment_map[each.key].locationCode}"
  location               = each.value.location
  resource_group_name    = each.value.name
  version                = "14"
  backup_retention_days = 7
  geo_redundant_backup_enabled = true
  create_mode = "Default"
  delegated_subnet_id    = var.env == "dev" ? azurerm_subnet.psql[each.key].id : null
  private_dns_zone_id    = var.env == "dev" ? data.azurerm_private_dns_zone.psql_dnszone_sa.id : null
  administrator_login    = "DbAdmin${local.deployment_map[each.key].workload}${var.env}"
  administrator_password = random_password.psqlPassword.result
  authentication {
    active_directory_auth_enabled = false
    password_auth_enabled         = true
  }
  zone                   = "1"
  storage_mb = 32768
  sku_name   = var.env == "prod"? "GP_Standard_D2s_v3" : "B_Standard_B2s"

}
```

### Debug Output/Panic Output

```shell
│ Error: creating Flexible Server (Subscription: "8d4f7793-1436-4651-a3d7-be5f0fde10a2"
│ Resource Group Name: "rg-regional-shd-stapp-dev-sa"
│ Flexible Server Name: "psql-srv-shd-stapp-dev-sa"): performing Create: servers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="ParameterOutOfRange" Message="The value of the 'Version' should be in: []. Verify that the specified parameter value is correct."
```

### Expected Behaviour

Not an version error.

### Actual Behaviour

Error message above

### Steps to Reproduce

terraform apply

### Important Factoids

-

### References

-

**Comment by samuelhornbyparallo** [comment]
This was due to an Azure resource limitation in my selected region.

**Comment by CiucurDaniel** [comment]
I had the same error yesterday therefore I will provide some extra context. The error itself is pretty confusing at first I thought that by `Version` it means the PostgresSQL version attribute. But is not, like @samuelhornbyparallo mentioned it has to do your Azure subscription and possible regional limitations.

A good way to check if that's the case if to try to create your Postgres flexible server from azure portal. Select your subscription then select the region. if you are not allowed to create the resource in that region you will get and error message saying: 

```
Subscription <your_subscription> is not allowed to provision in <region>
```

Another way is to query the skus with az cli:

```
az account set --subscription <your_subscription>

az postgres flexible-server list-skus --location <region>
[]
```
If you get an empty array `[]` that's also a good indicator. 


## How to fix? 

You need to request access to provision Azure PostgreSQL Flexible Server in the desired region. 
You can do that from Azure portal section called `Help + support`.


Hopefully this will help some people in the future. :dart:
