### ISSUE TITLE
Can't create azurerm_mysql_flexible_server version 8.0.31

### ISSUE THREAD

**Issue by tmurakam** [hashicorp/terraform-provider-azurerm#21301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_flexible_server" "mysql" {
  name                = "..."
  location            = "..."
  resource_group_name = "..."

  administrator_login    = "..."
  administrator_password = "..."

  sku_name   = "..."
  version    = "8.0.31"

  storage {
    size_gb           = 100
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/tmurakam/37dc11bf89bb633660bf79429ad73493
```

### Expected Behaviour

Should accept version = "8.0.31"

### Actual Behaviour

Error occured:

│ Error: expected version to be one of [5.7 8.0.21], got 8.0.31

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seem [service API](https://github.com/Azure/azure-rest-api-specs/blob/8a28143c7271d4496296ed47f70c3cb5a9981e57/specification/mysql/resource-manager/Microsoft.DBforMySQL/FlexibleServers/preview/2021-12-01-preview/FlexibleServers.json#L565) doesn't support "8.0.31" for now.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. If it gets added, we can reopen this request.
