### ISSUE TITLE
Long running process are failing with ExpiredAuthenticationToken

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#21361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.47.0 to latest 3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Terraform Configuration Files

```hcl
See public documentation for the example.
```

### Debug Output/Panic Output

```shell
[ERROR] provider.terraform-provider-azurerm_v3.47.0_x5: Response contains error diagnostic: diagnostic_detail="waiting for creation of Managed Instance: (Name "teno-sqlmi-srv2" / Resource Group "teno-rg-sqlmi-db-re2"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=401 -- Original Error: Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '4/11/2023 12:27:23 AM' is earlier than current UTC time '4/11/2023 12:30:55 AM'."" diagnostic_summary="waiting for creation of Managed Instance: (Name "teno-sqlmi-srv2" / Resource Group "teno-rg-sqlmi-db-re2"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=401 -- Original Error: Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '4/11/2023 12:27:23 AM' is earlier than current UTC time '4/11/2023 12:30:55 AM'."" tf_req_id=628e89d0-b178-52ff-35ca-2f1fff9b3863 @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 @module=sdk.proto diagnostic_severity=ERROR tf_proto_version=5.3 tf_provider_addr=provider tf_resource_type=azurerm_mssql_managed_instance tf_rpc=ApplyResourceChange timestamp=2023-04-11T00:30:54.871Z
╷
│ Error: waiting for creation of Managed Instance: (Name "teno-sqlmi-srv2" / Resource Group "teno-rg-sqlmi-db-re2"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=401 -- Original Error: Code="ExpiredAuthenticationToken" Message="The access token expiry UTC time '4/11/2023 12:27:23 AM' is earlier than current UTC time '4/11/2023 12:30:55 AM'."

(same with all intermediate versions above 3.47. Cannot use lower versions as some features are needed for backup and only been introduced in 3.47.0)
```

### Expected Behaviour

SQL Managed instance is taking 4 hours to deploy and it is expected the underlying SDK to deal to the refresh token accordingly. The current access token expires and break the deployment.

### Actual Behaviour

The recovery process is painful as we need to wait for the MI cluster to be provisioned and the MI instance running (after 3 hours..) before doing a terraform import and resume the deployment. This is something difficult to handle in a pipeline.

### Steps to Reproduce

Deploy a SQL MI instance as per the public example

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/20834#issuecomment-1462857739

**Comment by magodo** [comment]
@LaurentLesle Sorry that you run into this. This issue has been tracked by #20867, please follow that for any progress.
