### ISSUE TITLE
Support for new app service plan SKUs

### ISSUE THREAD

**Issue by JyrkiHei** [hashicorp/terraform-provider-azurerm#21365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New Azure App Service Plans have been published.

New SKU:s (hopefully all)
P0v3
P1mV3
P2mV3
P3mV3
P4mV3
P5mV3
I4v2
I5v2
I6v2

More info: https://azure.microsoft.com/en-us/blog/new-azure-app-service-plans-fuel-greater-choice-and-savings/

### New or Affected Resource(s)/Data Source(s)

azurerm_service_plan

**Comment by pbaumgartner-rdt** [comment]
P0v3 appears to have been missed from the change submitted to 3.52. Does this need re-opening or raising as a separate issue?
