### ISSUE TITLE
Support for not_before_date and expiration_date

### ISSUE THREAD

**Issue by herquan-docusign** [hashicorp/terraform-provider-azurerm#21380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Argument `not_before_date` and `expiration_date` are supported in resource `azurerm_key_vault_secret` but not in data source `azurerm_key_vault_secret`

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Potential Terraform Configuration

```hcl
data "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  key_vault_id = data.azurerm_key_vault.existing.id
}

output "expiration_date" {
  value     = data.azurerm_key_vault_secret.example.expiration_date
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/21359

**Comment by jaredbrogan** [comment]
A friendly reminder to close this out as completed, @herquan-docusign 🙂
