### ISSUE TITLE
404: Can not perform requested operation on nested resource. Parent resource 'contoso.com' not found.

### ISSUE THREAD

**Issue by thomaskennedy1066** [hashicorp/terraform-provider-azurerm#21399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_a_record

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_a_record" "webserverdns" {
  name = "mydnsrecord"
  zone_name = "contoso.com"
  resource_group_name = azurerm_resource_group.main.name
  ttl = 20
  records = [var.webserverip]
}
```

### Debug Output/Panic Output

```shell
│ Resource Group Name: "rg"
│ Private Dns Zone Name: "contoso.com"
│ Record Type: "A"
│ Relative Record Set Name: "mydnsrecord"): recordsets.RecordSetsClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'contoso.com' not found."
│
│   with module.redacted,
│   on ..\..\..\..\module\redacted.tf line 150, in resource "azurerm_private_dns_a_record" "webserver":
│  150: resource "azurerm_private_dns_a_record" "webserverdns" {
```

### Expected Behaviour

I expect this terraform code to produce an A record in the private DNS zone. It works fine in the portal and used to work fine last month.

### Actual Behaviour

Error occurs where the private dns zone is not found.

### References

I'm not sure but this may be related: https://github.com/hashicorp/terraform-provider-azurerm/issues/20773

**Comment by myc2h6o** [comment]
Hi @thomaskennedy1066 thanks for opening the issue. I've checked that #20773 is fixed in v3.51.0, below is a working example I tested in my environment. From the config you shared, I'm seeing you set `zone_name = "contoso.com"`. Are you creating `azurerm_private_dns_zone` in the same config? If so, you would need to make the dns record depends on the dns zone with `zone_name = azurerm_private_dns_zone.test.name` or using `depends_on` property,
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "testrg"
  location = "eastus"
}

resource "azurerm_private_dns_zone" "test" {
  name                = "contoso.com"
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_private_dns_a_record" "test" {
  name                = "mydnsrecord"
  zone_name           = azurerm_private_dns_zone.test.name
  resource_group_name = azurerm_resource_group.main.name
  ttl                 = 20
  records             = ["1.2.3.4", "1.2.4.5"]
}
```

**Comment by thomaskennedy1066** [comment]
Hey @myc2h6o , thanks for the reply. I'm deploying the zone in a separate terraform config and referencing the zone_name via a remote_state variable

**Comment by myc2h6o** [comment]
@thomaskennedy1066 if the dns zone is ready before creating the record, there may be some issue with the cache in Azure. I'd suggest:
 1. open a support to Azure to see if there is anything wrong on the server side.
 2. set environment variable `TF_LOG` to `DEBUG` according to https://developer.hashicorp.com/terraform/internals/debugging, which would output the API request details in the output, which shall contain the PUT url and body. You could also check if there is anything wrong with the request for creating the record.

**Comment by thomaskennedy1066** [comment]
The issue turned out to be that you have to provide the Resource Group which the DNS zone exists in to `azurerm_private_dns_a_record`. Changing the resource group fixed this issue
