### ISSUE TITLE
azurerm_linux_function_app has no possible values for default_provider in auth_settings_v2  

### ISSUE THREAD

**Issue by mgopez** [hashicorp/terraform-provider-azurerm#21398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the `azurerm_linux_function_app` documentation, the `auth_settings_v2` block has a `default_provider` parameter.

The current description is:
```
(Optional) The Default Authentication Provider to use when more than one Authentication Provider is configured and the unauthenticated_action is set to RedirectToLoginPage.
```

In the description there should be a list of possible values similar to how the `auth_settings` block's `default_provider` has:
```
Possible values include: AzureActiveDirectory, Facebook, Google, MicrosoftAccount, Twitter, Github
```

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_function_app, azurerm_windows_function_app

**Comment by aristosvo** [comment]
Hi @mgopez! Thanks for raising this issue. 

Do you know what the list is of possible values for v2? I cannot find these in any docs..

**Comment by mgopez** [comment]
Hey @aristosvo, I'm not sure what the complete list of acceptable values are.
On the portal an `active_directory_v2` provider shows up as `Microsoft` in the authentication blade.

I ended up manually setting the default provider on the portal to the `active_directory_v2` one I configured with Terraform.
Then used `resources.azure.com` to inspect the resource's auth configuration and the following was observed:
![image](https://user-images.githubusercontent.com/23063355/231541311-cf89799f-96a7-427e-9090-0014d751933a.png)

So I set the `auth_settings_v2`'s `default_provider` value to `azureactivedirectory` and it worked.
So perhaps it's the same as `auth_settings` v1?

**Comment by aristosvo** [comment]
Based on similar research as you did:

Possible values include the standard providers (`apple`, `azureactivedirectory`, `facebook`, `github`, `google`, `twitter`) or the `name` of your `custom_oidc_v2` provider. This doesn't mean the values are limited to that or that we are able to validate these.
