### ISSUE TITLE
Support for data collection parameters in AKS

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#21406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft started with some ways to cost optimize the AKS logs: https://learn.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-cost-config?tabs=create-arm#data-collection-parameters

This also includes values like an interval: "This value determines how often the agent collects data." - which is basically my feature request.

The data collection setting is found here in the AKS:
![image](https://user-images.githubusercontent.com/46575727/231669464-d2f1a44f-f2a9-4cdf-b1d0-39c4a64fba96.png)
![image](https://user-images.githubusercontent.com/46575727/231669721-a9842d47-c2be-449a-b8dd-cde1c1e6dac8.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
Pre-defined values:
monitor_settings {
   cost_presets = "Standard|Cost-optimized|Syslog"
}

definition with custom values:
monitor_settings {
   cost_presets = "Custom"
   interval = "x"
   namespace_excluded = "..."
   collect_syslog = true|false
}
```

**Comment by 0x4c6565** [comment]
@mkemmerz this is implemented with data collection rules. I've managed to enable this by adding a collection rule and association as below:

```hcl
resource "azurerm_monitor_data_collection_rule" "aks" {
  name                = azurerm_kubernetes_cluster.aks.name
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                  = var.tags

  destinations {
    log_analytics {
      name                  = "ciworkspace"
      workspace_resource_id = var.log_analytics_workspace_id
    }
  }

  data_flow {
    streams      = ["Microsoft-ContainerInsights-Group-Default"]
    destinations = ["ciworkspace"]
  }

  data_sources {
    extension {
      name           = "ContainerInsightsExtension"
      streams        = ["Microsoft-ContainerInsights-Group-Default"]
      extension_name = "ContainerInsights"
      extension_json = jsonencode({
        dataCollectionSettings = {
          interval               = "5m"
          namespaceFilteringMode = "Exclude"
          namespaces = [
            "kube-system",
            "gatekeeper-system",
            "azure-arc"
          ]
        }
      })
    }
  }
}

resource "azurerm_monitor_data_collection_rule_association" "aks" {
  name                    = azurerm_kubernetes_cluster.aks.name
  target_resource_id      = azurerm_kubernetes_cluster.aks.id
  data_collection_rule_id = azurerm_monitor_data_collection_rule.aks.id
}
```

The portal then shows the matching preset:

![image](https://user-images.githubusercontent.com/7476213/233969521-012d0448-0116-4aaa-bd70-e4ede7e2bf4f.png)

**Comment by mkemmerz** [comment]
@0x4c6565 Wow thanks! That looks great - I will give it a try!

**Comment by mkemmerz** [comment]
Closing this issue as the solution provided by @0x4c6565 worked perfectly. Thanks again!

**Comment by 0x4c6565** [comment]
> > I've managed to enable this by adding a collection rule and association as below:
> 
> Did you use this solution in conjuction with the oms_agent block? I'm trying the same thing but it's not changing the preset in the portal to match the updated config.

@SebSa do you have managed identity configured for AKS? This is required. You'll need to configure this if not, and set `msi_auth_for_monitoring_enabled` to `true` inside `oms_agent` block

**Comment by 0x4c6565** [comment]
I'd assume that was fine then - do you have `msi_auth_for_monitoring_enabled` set to `true` also?

I'm really not sure what the portal is looking for to denote which cost preset is configured - I'd assume it's based on the AKS data collection rule association and configured interval. Have you set the same LA workspace ID for both the rule and within the `oms_agent` block too? Presume you've also set `msi_auth_for_monitoring_enabled` to `true`?

**Comment by 0x4c6565** [comment]
@SebSa I think it may just be matching on configuration of the collection rule matching the below:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7476213/ff84585a-0eb1-408c-aa91-f2b41b649039)
