### ISSUE TITLE
unable to remove azurerm_ip_group

### ISSUE THREAD

**Issue by juicybaba** [hashicorp/terraform-provider-azurerm#21428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.3

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_ip_group

### Terraform Configuration Files

```hcl
resource "azurerm_ip_group" "default" {
...
 for_each = local.ip_groups
  lifecycle {
    create_before_destroy = true 
  }
}

resource "azurerm_firewall_policy_rule_collection_group" "default" {
# nothing special on code, but there is a rule uses above ip group
  for_each           = local.azurerm_firewall_policy_rule_collection_group
...
  dynamic "network_rule_collection" {
      for_each = each.value.network_rule_collections
  }
...
}
```

### Debug Output/Panic Output

```shell
Error: deleting IP Group "***" (Resource Group "***"): network.IPGroupsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="IpGroupsHasFirewallPolicyReferences" Message="IpGroups '***' cannot be deleted since there are firewall policies using this resource."
```

### Expected Behaviour

with `create_before_destroy = true` in place, `azurerm_ip_group` should be destroyed after `azurerm_firewall_policy_rule_collection_group` is updated.

### Actual Behaviour

I added `create_before_destroy = ture` to the code after seeing the error, however, the next apply still fail on the same error no matter `create_before_destroy = ture` is added under `azurerm_ip_group`(which i think is the correct place) or `azurerm_firewall_policy_rule_collection_group`.

**Comment by myc2h6o** [comment]
Hi @juicybaba the config and the expected behavior you described is correct to me. Just one thing that may be causing this unexpected behavior: could you check if the `azurerm_firewall_policy_rule_collection_group` still have a dependency on `azurerm_ip_group` in your state file when you prepare to removing the `azurerm_ip_group`? the `create_before_destroy` needs to work together with the dependency.

**Comment by juicybaba** [comment]
Hi @myc2h6o , i am not sure if I understand your ask, from the code perspective, there is no explicit `depends_on` but `azurerm_firewall_policy_rule_collection_group` is depending on `azurerm_ip_group` because there is a network rule using one of the `azurerm_ip_group`(I added a `for_each` to the code to match the logic that I have) and the rule needs to be updated before `azurerm_ip_group` to be deleted.

**Comment by juicybaba** [comment]
not sure what happened, the issue seems to be fixed.
