### ISSUE TITLE
azurerm_virtual_machine_extension

### ISSUE THREAD

**Issue by Cataluniat** [hashicorp/terraform-provider-azurerm#21431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I have noticed that in several forums there are many doubts with the azurerm_virtual_machine_extension resource and I have found that the error is within the terraform registry.
Specifically in:
### **virtual_machine_id = azurerm_virtual_machine.example.id**

Being a linux virtual machine, it is necessary to code like this: 

### **azurerm_linux_virtual_machine.example.id**

I consider it necessary to fix this problem. thank 

### Terraform Version

3.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.scfile))}"
    }
    PROT
}
```

### Debug Output/Panic Output

```shell
resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.scfile))}"
    }
    PROT
}
```

### Expected Behaviour

resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.scfile))}"
    }
    PROT
}

### Actual Behaviour

resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.scfile))}"
    }
    PROT
}

### Steps to Reproduce

resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.scfile))}"
    }
    PROT
}

### Important Factoids

 resource "azurerm_virtual_machine_extension" "example" {   name                 = "hostname"   virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id   publisher            = "Microsoft.Azure.Extensions"   type                 = "CustomScript"   type_handler_version = "2.0"      protected_settings = <<PROT     {         "script": "${base64encode(file(var.scfile))}"     }     PROT }

### References

resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   = azurerm_linux_virtual_machine.my_terraform_vm.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.scfile))}"
    }
    PROT
}

**Comment by myc2h6o** [comment]
Hi @Cataluniat thanks for raising the issue! The current design for linux|windows vm + vm extension may be not easy to change, however, as old `azurerm_virtual_machine` resource has been suppressed by the two new resources, I think it's a good idea to update the document of `azurerm_virtual_machine_extension` to use the new resources so that possibility of mis-writing `virtual_machine_id = azurerm_virtual_machine.example.id` could be reduced.
