### ISSUE TITLE
azurerm_key_vault creation takes too much time

### ISSUE THREAD

**Issue by ayelencasamassa** [hashicorp/terraform-provider-azurerm#21447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "my-key-vault" {
  name                        = var.my_key_vault_name
  location                    = data.azurerm_resource_group.my-rg.location
  resource_group_name         = data.azurerm_resource_group.my-rg.name
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days  = 7
  purge_protection_enabled    = false 
  sku_name                    = var.key_vault_sku_name
  enable_rbac_authorization   = false 

  network_acls {
    bypass                     = "AzureServices"
    default_action             = "Deny"
    virtual_network_subnet_ids = [data.azurerm_subnet.my-subnet.id]
    ip_rules                   = var.my_ips
  }

  timeouts {
    create = "70m"
  }
}
```

### Debug Output/Panic Output

```shell
Timeout
```

### Expected Behaviour

Just create the key vault

### Actual Behaviour

I am creating up to 20 key vaults. For some reason, it takes almost 60 minutes each!
Why is that?

### Steps to Reproduce

Using Azure DevOps

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
