### ISSUE TITLE
Could you please include Ip Restrictions in Ingress for azurerm_container_apps service?

### ISSUE THREAD

**Issue by harshanalavala** [hashicorp/terraform-provider-azurerm#21448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

sure

### Description

Could you please include Ip restrictions like inbound and outbound ip address restrictions . please check below image
![image](https://user-images.githubusercontent.com/117251076/232672217-8baf9fbe-15d7-48d5-a484-4e8e7ccaf50a.png)

### New or Affected Resource(s)/Data Source(s)

azurerm_container_apps

**Comment by vladkasianenko** [comment]
Otherwise, you have to call custom Azure CLI after terraform.
https://learn.microsoft.com/en-us/cli/azure/containerapp/ingress/access-restriction?view=azure-cli-latest#az-containerapp-ingress-access-restriction-set

**Comment by harshanalavala** [comment]
> Otherwise, you have to call custom Azure CLI after terraform. https://learn.microsoft.com/en-us/cli/azure/containerapp/ingress/access-restriction?view=azure-cli-latest#az-containerapp-ingress-access-restriction-set

yes we can do that. It would be nice to have that in Terraform configuration.

**Comment by davidkarlsen** [comment]
This issue should be closed - was fixed in https://github.com/hashicorp/terraform-provider-azurerm/pull/23870

**Comment by tombuildsstuff** [comment]
Fixed via https://github.com/hashicorp/terraform-provider-azurerm/pull/23870 - thanks for the heads up @davidkarlsen
