### ISSUE TITLE
DevTest Policies do not seem to apply

### ISSUE THREAD

**Issue by PatrickMcAfee-Eagle** [hashicorp/terraform-provider-azurerm#2145]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform -v
Terraform v0.11.9
+ provider.azurerm v1.17.0

### Affected Resource(s)

* azurerm_dev_test_policy

### Terraform Configuration Files

```hcl
resource "azurerm_dev_test_lab" "lab" {
  name                = "${lower(var.name)}"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
}

resource "azurerm_dev_test_policy" "lab_vm_cap" {
  name                = "LabVmCount"
  policy_set_name     = "default"
  lab_name            = "${azurerm_dev_test_lab.lab.name}"
  resource_group_name = "${azurerm_dev_test_lab.lab.resource_group_name}"
  threshold           = "50"
  evaluator_type      = "MaxValuePolicy"
}

resource "azurerm_dev_test_policy" "lab_user_vm_cap" {
  name                = "UserOwnedLabVmCount"
  policy_set_name     = "default"
  lab_name            = "${azurerm_dev_test_lab.lab.name}"
  resource_group_name = "${azurerm_dev_test_lab.lab.resource_group_name}"
  threshold           = "2"
  evaluator_type      = "MaxValuePolicy"
}

```

### Expected Behavior

Policies for user VM ownership should be visible in the Azure Portal

### Actual Behavior

Changes are reported as applied from CLI, but going in to the portal shows no policies applied to the DevTest Lab

```
module.devtest-lab.azurerm_dev_test_policy.lab_vm_cap: Creation complete after 1s (ID: /subscriptions/c1a2562a-38a4-4712-b919-...policysets/default/policies/labvmcount)
module.devtest-lab.azurerm_dev_test_policy.lab_user_vm_cap: Creation complete after 1s (ID: /subscriptions/c1a2562a-38a4-4712-b919-...s/default/policies/userownedlabvmcount)
```

### Steps to Reproduce

1. Run above configuration with a lab name, resource_group_name, and location
2. `terraform apply`

**Comment by slime-uk** [comment]
I tried to achieve these lab limits and I agree they do not apply.

What's more concerning is when I take the limits back out of my TF scripts and resort to apply limits manually for the lab in the Azure portal, they do not take - it simply says Saving and never saves the setting.
![LabVmLimitsFailingToSave](https://user-images.githubusercontent.com/15941907/76873415-a35d2e80-6865-11ea-8ac2-2bef8279cc2f.jpg)

However, another Dev Test lab in the same subscription but not under TF control, these settings save fine.

**Comment by slime-uk** [comment]
An update: Although they do not appear to apply in the Azure portal, it seems they do actually apply.  I set a lab user VM limit to 3 using Terraform and then the lab didn't allow me to create a 4th lab VM.

I then created another lab in the subscription and tried to set similar limits, it returned an error on the TF apply - complaining about duplicate policy.  I looked in Azure Activity monitor and the policy set names are different:

They seem to require the policy name as:
- labs/<lab-name>/policySets/default/policies/MaxVmsAllowedPerLab 
- labs/<lab-name>/policySets/default/policies/MaxPremiumVmsAllowedPerLab
- labs/<lab-name>/policySets/default/policies/MaxVmsAllowedPerUser
- labs/<lab-name>/policySets/default/policies/MaxPremiumVmsAllowedPerUser

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I can repro it. Seems it's an issue on rest api. So I filed an issue on Azure/azure-rest-api-specs#10298.

**Comment by katbyte** [comment]
I am going to close this as it was opened for `v1.x` of the provider (2 major versions ago) which is no longer actively maintained. 

If this is still an issue with `v3.x` of the provider please do let us know by opening a new issue, thanks!
