### ISSUE TITLE
Disconnected azurerm_linux_web_app private endpoint shows no changes

### ISSUE THREAD

**Issue by chrisbloe** [hashicorp/terraform-provider-azurerm#21461]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "_" {
  ...

  private_service_connection {
    name                           = "myname"
    is_manual_connection           = false
    private_connection_resource_id = azurerm_linux_web_app._.id
    subresource_names              = ["sites"]
  }
}
```

### Debug Output/Panic Output

```shell
Cannot obtain
```

### Expected Behaviour

The disconnection from the Web App should be noticed and recreated.

### Actual Behaviour

```hcl
No changes. Your infrastructure matches the configuration.
```

### Steps to Reproduce

1. Create the following linked components:

- `azurerm_linux_web_app`
- `azurerm_private_endpoint`

2. In the portal UI, visit the `Web App` -> `Networking` -> `Inbound Traffic`/`Features`/`Private endpoints`.
3. Delete the Private Endpoint entry.
4. Run `terraform plan`. This should show the private endpoint has been disconnected from the web app, but instead it shows no changes.

### References

Possibly related to #20776.

**Comment by xiaxyi** [comment]
Thanks @chrisbloe for raising this issue, the resource that you deleted from app service is private endpoint connection, not private endpoint. When you are creating the private endpoint, service will create the PE connection to the resource that you specified in the private endpoint.

we need to check if to add the connection status property in the private endpoint so Terraform can detect the connection status change.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @xiaxyi‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
