### ISSUE TITLE
Terraform - azurerm diagnostic setting not working as expected for azurerm_storage_account

### ISSUE THREAD

**Issue by madkimuz** [hashicorp/terraform-provider-azurerm#21476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.28

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "stgdiag" {
  name                     = var.STGACCOUNT_DIAG
  resource_group_name      = data.azurerm_resource_group.rg.name
  location                 = data.azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  tags                     = local.resource_tags
}

resource "azurerm_monitor_diagnostic_setting" "diagnostics" {
  name               = "testbatchdiag"
  target_resource_id = azurerm_batch_account.batchaccount.id
  storage_account_id = azurerm_storage_account.stgdiag.id

  enabled_log {
    category = "Audit"

    retention_policy {
      enabled = false
    } 
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }

  depends_on     = [
    azurerm_batch_account.batchaccount, azurerm_storage_account.stgdiag
 ]
}
```

### Debug Output/Panic Output

```shell
Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Category 'Audit' is not supported
with azurerm_monitor_diagnostic_setting.diagnostics,
on diag.tf line 10, in resource "azurerm_monitor_diagnostic_setting" "diagnostics":
resource "azurerm_monitor_diagnostic_setting" "diagnostics"
```

### Expected Behaviour

This should allow me to create the diagnostic settings with the following configurations:

Categories -- Service logs and Audit logs should be enabled

### Actual Behaviour

I get the following error message while validating it:

Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Category 'Audit' is not supported
with azurerm_monitor_diagnostic_setting.diagnostics,
on diag.tf line 10, in resource "azurerm_monitor_diagnostic_setting" "diagnostics":
resource "azurerm_monitor_diagnostic_setting" "diagnostics"

FYI - I also tried with enabled_log instead of log which is deprecated but the same error.

### Steps to Reproduce

terraform init
terraform validate

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.51.0/docs/resources/monitor_diagnostic_setting

**Comment by tombuildsstuff** [comment]
hi @madkimuz 

Taking a look through here, unfortunately it appears that the Azure API doesn't support defining the category `Audit` for a Storage Account, per the error message being returned from the Azure API:

> Category 'Audit' is not supported

As such you'll need to remove this category (and potentially use a different one) to implement this behaviour - you can see which categories are available [using the `azurerm_monitor_diagnostic_categories` Data Source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/monitor_diagnostic_categories).

Since this is a configuration question rather than a bug in the Azure Provider, whilst I'd like to thank you for opening this issue, I'm going to close this issue for the moment.

Thanks!
