### ISSUE TITLE
SQL MI gets denied by TDE policy

### ISSUE THREAD

**Issue by segraef** [hashicorp/terraform-provider-azurerm#21473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.4

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_instance

### Terraform Configuration Files

```hcl
# Module

resource "random_password" "administrator_login_password" {
  keepers = {
    salt = "pepper"
  }
  length           = 32
  min_upper        = 2
  min_lower        = 2
  min_special      = 2
  numeric          = true
  special          = true
  override_special = "!@#$%&"
  lower            = true
}

resource "random_password" "administrator_login" {
  keepers = {
    salt = "pepper"
  }
  length  = 12
  numeric = false
  special = false
  lower   = true
}

resource "azurerm_key_vault_secret" "administrator_login_password" {
  name            = format("%s-%s-%s", var.sql_managed_instance_name, "password", substr(random_password.administrator_login.result, 0, 5))
  value           = var.administrator_login_password == null ? random_password.administrator_login_password.result : var.administrator_login_password
  key_vault_id    = var.key_vault_id
  expiration_date = time_offset.password_expired.rfc3339
}

resource "time_offset" "password_expired" {
  offset_days = 90
}

resource "azurerm_mssql_managed_instance" "this" {
  name                           = var.sql_managed_instance_name
  resource_group_name            = var.resource_group_name
  location                       = var.location
  license_type                   = var.license_type
  sku_name                       = var.sku_name
  storage_size_in_gb             = var.storage_size_in_gb
  storage_account_type           = var.storage_account_type
  subnet_id                      = var.subnet_id
  vcores                         = var.vcores
  maintenance_configuration_name = var.maintenance_configuration_name
  dns_zone_partner_id            = var.dns_zone_partner_id == "" ? null : var.dns_zone_partner_id
  collation                      = var.collation
  minimum_tls_version            = "1.2"
  proxy_override                 = var.proxy_override
  public_data_endpoint_enabled   = false
  timezone_id                    = var.timezone_id
  administrator_login            = var.administrator_login == null ? random_password.administrator_login.result : var.administrator_login
  administrator_login_password   = var.administrator_login_password == null ? random_password.administrator_login_password.result : var.administrator_login_password
  tags                           = merge(local.tags, var.tags)

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "time_static" "current_time" {}

resource "time_offset" "two_years" {
  offset_years = 2
}

locals {
  sub_id                                    = split("/", var.key_vault_id)[2]
  kv_crypto_service_encryption_user_role_id = "e147488a-f6f5-4113-8e2d-b22465e65bf6" # "Key Vault Crypto Service Encryption User"
}

resource "azurerm_role_assignment" "this" {
  scope              = var.key_vault_id
  role_definition_id = format("/subscriptions/%s/providers/Microsoft.Authorization/roleDefinitions/%s", local.sub_id, local.kv_crypto_service_encryption_user_role_id) # "Key Vault Crypto Service Encryption User"
  principal_id       = azurerm_mssql_managed_instance.this.identity[0].principal_id
}

resource "azurerm_key_vault_key" "this" {
  name            = format("%s-%s-%s", var.sql_managed_instance_name, "tde", substr(random_password.administrator_login.result, 0, 5))
  key_vault_id    = var.key_vault_id
  key_type        = "RSA-HSM"
  key_size        = 2048
  not_before_date = time_offset.two_years.base_rfc3339 # time_static.current_time.rfc3339
  expiration_date = time_offset.two_years.rfc3339      #timeadd(time_static.current_time.rfc3339, "8760h")

  key_opts = [
    "unwrapKey",
    "wrapKey",
  ]

  rotation_policy {
    automatic {
      time_before_expiry = "P21M"
    }

    expire_after         = "P2Y"
    notify_before_expiry = "P30D"
  }

  depends_on = [
    azurerm_role_assignment.this
  ]
}

resource "azurerm_mssql_managed_instance_transparent_data_encryption" "this" {
  managed_instance_id   = azurerm_mssql_managed_instance.this.id
  key_vault_key_id      = azurerm_key_vault_key.this.id
  auto_rotation_enabled = true

  depends_on = [
    azurerm_role_assignment.this
  ]
}

# Configuration

module "sql_managed_instance_ae" {
  source                    = "git::https://aaa@dev.azure.com/aaa/Modules/_git/terraform-azurerm-sql-managed-instance?ref=1.0.2"
  sql_managed_instance_name = module.naming.generated_names.domain.sql_managed_instance[1]
  resource_group_name       = local.env_specific_config.resource_group_name_ae
  location                  = local.env_specific_config.location
  subnet_id                 = local.env_specific_config.subnet_003_ae
  key_vault_id              = module.key_vault_ae.id
  tags                      = local.env_specific_config.tags

  depends_on = [
    module.key_vault_ae
  ]
}
```

### Debug Output/Panic Output

```shell
The deployment of SQL MI via azurerm_mssql_managed_instance works fine but gets denied by SQL managed instances should use customer-managed keys to encrypt data at rest because it can't find "Microsoft.Sql/managedInstances/keyid" although TF applies it. Therefore we went ahaed and developed the module with AzApi to comply with the Azure policy.
```

### Expected Behaviour

The deployment of SQL MI via `azurerm_mssql_managed_instance` works fine but gets denied by [SQL managed instances should use customer-managed keys to encrypt data at rest](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fac01ad65-10e5-46df-bdd9-6b0cad13e1d2) because it can't find `Microsoft.Sql/managedInstances/keyid` although TF applies it.

Therefore we went ahaed and developed the module with AzApi to comply with the Azure policy. But SQL MI AzApi fails due to inexplicable reasons see https://github.com/hashicorp/terraform-provider-azurerm/issues/21472.

### Actual Behaviour

To have `Microsoft.Sql/managedInstances/keyid` applied.

### Steps to Reproduce

1. Assig policy [SQL managed instances should use customer-managed keys to encrypt data at rest](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fac01ad65-10e5-46df-bdd9-6b0cad13e1d2)
2. terraform apply

### References

[SQL managed instances should use customer-managed keys to encrypt data at rest](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fac01ad65-10e5-46df-bdd9-6b0cad13e1d2)

**Comment by tombuildsstuff** [comment]
hi @segraef 

Taking a look through here, unfortunately this appears to be a design choice within the Azure Policy in question - as such I'd recommend reaching out to the Azure Policy team about this in the short-term.

Since at this point in the time the `azurerm_mssql_managed_instance` resource doesn't support defining the TDE configuration within this resource (since this would mean this doesn't work when using a SystemAssigned Identity) - however this is something we could look to support both within the `azurerm_mssql_managed_instance` resource and in the separate `azurerm_mssql_managed_instance_transparent_data_encryption` resources.

If you'd like to see support for defining the TDE configuration inline within the `azurerm_mssql_managed_instance` resource, [please feel free to open a new Feature Request](https://github.com/hashicorp/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.yml&title=Support+for+%5Bthing%5D) to track that specifically - however since this issue is related to the design of the Azure Policy in question, whilst I'd like to thank you for opening this issue, I'm going to close this issue for the moment.

Thanks!
