### ISSUE TITLE
Support for Configure Playbook Permissions in Microsoft Sentinel

### ISSUE THREAD

**Issue by Akila-I** [hashicorp/terraform-provider-azurerm#21483]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the `azurerm_log_analytics_solution` resource creates a Microsoft Sentinel in Azure connected to the given log analytics workspace. It allows to create automation rules for the Sentinel Solution using `azurerm_sentinel_automation_rule` for Change Severity, Assign Owner,.. but not for Run Playbooks. To run a playbook through an automation rule, the Sentinel solution should have playbook permissions configured (refer to the screenshot). It would be great to have this playbook configuration feature to be done through Terraform if possible.

<img width="1186" alt="Screenshot 2023-04-19 at 14 44 32" src="https://user-images.githubusercontent.com/80597937/233074619-b8da2d2b-4dd8-41f9-9381-ff4dfa64fe1c.png">

### New or Affected Resource(s)/Data Source(s)

azurerm_log_analytics_solution

### Potential Terraform Configuration

```hcl
resource "azurerm_log_analytics_solution" "example" {
  solution_name         = "ContainerInsights"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  workspace_resource_id = azurerm_log_analytics_workspace.example.id
  workspace_name        = azurerm_log_analytics_workspace.example.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }

  playbook_permissions {
    resource_group_ids = [azurerm_resource_group.example.id]
  }
}
```

### References

https://learn.microsoft.com/en-us/azure/sentinel/automate-responses-with-playbooks

**Comment by ziyeqf** [comment]
Hi @Akila-I , thanks for opening this issue.

This function is actually deploying role assignment, it could be done by the following Terraform config:
```
data "azurerm_resource_group" "target" {
    name = "{your resource group name here}"
}

data "azuread_service_principal" "security_insight" {
  display_name = "Azure Security Insights"
}

resource "azurerm_role_assignment" "sentinel_automation_contributor" {
  scope                = data.azurerm_resource_group.target.id
  role_definition_name = "Microsoft Sentinel Automation Contributor"
  principal_id         = data.azuread_service_principal.security_insight.object_id
}
```

For any further questions please leave comments.
Thanks!

**Comment by Akila-I** [comment]
Thank you @ziyeqf for the explaining comment. Yes this works and that was what I wanted. Thank you for that.

However, I got another answer from the internet that we can use azuread_client_config instead of azuread_service_principal which also works. What do you think would be more suitable?

**Comment by ziyeqf** [comment]
> Thank you @ziyeqf for the explaining comment. Yes this works and that was what I wanted. Thank you for that.
> 
> However, I got another answer from the internet that we can use azuread_client_config instead of azuread_service_principal which also works. What do you think would be more suitable?

Could you please provide the part of config here? I'm not sure why `azuread_client_config` is working.

**Comment by Akila-I** [comment]
```
data "azuread_client_config" "current" {
}

resource "azurerm_role_assignment" "sentinel_automation_contributor" {
  scope                = data.azurerm_resource_group.target.id
  role_definition_name = "Microsoft Sentinel Automation Contributor"
  principal_id         = data. azuread_client_config.current.object_id
}
```

This also works by assigning the role to the current user/servicepincipal that runs the Terraform script.

**Comment by ziyeqf** [comment]
> > Could you please provide the part of config here? I'm not sure why `azuread_client_config` is working.
> 
> ```
> data "azuread_client_config" "current" {
> }
> 
> resource "azurerm_role_assignment" "sentinel_automation_contributor" {
>   scope                = data.azurerm_resource_group.target.id
>   role_definition_name = "Microsoft Sentinel Automation Contributor"
>   principal_id         = data. azuread_client_config.current.object_id
> }
> ```
> 
> This also works by assigning the role to the current user/servicepincipal that runs the Terraform script.

I suggest to use `azuread_service_principal` to assign the role to `Azure Security Insights`. Ii's as same as what Portal does. And, per my understanding Sentinel will use `Azure Security Insights` to access Playbook.

**Comment by Akila-I** [comment]
Thank you very much for the help @ziyeqf. Closing this issue as its answered.
