### ISSUE TITLE
azurerm_databricks_workspace no longer working. storage identity and managed disk identity output values are blank 

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#21487]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.7

### AzureRM Provider Version

3.45.0 and 3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
just a week ago, this code worked perfectly. i used arm template examples to help guide deployment in terraform: https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.databricks


resource "azurerm_databricks_workspace" "databricks_workspace" {
  count = var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count

  location            = local.region[var.location]
  name                = "${var.group_prefix}${format("%02d", count.index)}-dbrickws"
  resource_group_name = var.resource_group_name
  tags                = local.tags

  customer_managed_key_enabled                        = var.cmk_enabled
  infrastructure_encryption_enabled                   = var.infrastructure_encryption_enabled
  managed_resource_group_name                         = "MW_${var.group_prefix}${format("%02d", count.index)}-dbrickws"
  managed_services_cmk_key_vault_key_id               = var.cmk_enabled ? azurerm_key_vault_key.databricks_services_key[count.index].id : null
  managed_disk_cmk_key_vault_key_id                   = var.cmk_enabled ? azurerm_key_vault_key.databricks_disks_key[count.index].id : null
  managed_disk_cmk_rotation_to_latest_version_enabled = var.cmk_enabled ? true : null
  network_security_group_rules_required               = var.nsg_rules_required
  public_network_access_enabled                       = var.public_network_access_enabled
  sku                                                 = var.sku

  custom_parameters {
    no_public_ip                                         = var.no_public_ip
    private_subnet_name                                  = replace(var.private_subnet_id, "/.*//", "")
    private_subnet_network_security_group_association_id = var.private_nsg_assoc_id
    public_subnet_name                                   = replace(var.public_subnet_id, "/.*//", "")
    public_subnet_network_security_group_association_id  = var.public_nsg_assoc_id
    storage_account_name                                 = "${replace(var.group_prefix, "-", "")}${format("%02d", count.index)}dbrickwssa"
    storage_account_sku_name                             = var.storage_account_sku_name
    virtual_network_id                                   = replace(var.private_subnet_id, "//subnets/.*/", "")
  }

  depends_on = [azurerm_key_vault_access_policy.databricks_service_policy]
}

resource "azurerm_databricks_workspace_customer_managed_key" "databricks_workspace_key" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0

  key_vault_key_id = azurerm_key_vault_key.databricks_dbfs_key[count.index].id
  workspace_id     = azurerm_databricks_workspace.databricks_workspace[count.index].id

  depends_on = [azurerm_key_vault_access_policy.databricks_policy]
}

//KV stuff

data "azurerm_client_config" "current" {}
data "azuread_service_principal" "databricks_spn" {
  display_name = "AzureDatabricks"
}

resource "azurerm_key_vault_key" "databricks_dbfs_key" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0
  name  = "${var.group_prefix}${format("%02d", count.index)}-dbricks-dbfs-key"

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
  key_size     = 2048
  key_type     = "RSA"
  key_vault_id = var.keyvault_id
}

resource "azurerm_key_vault_key" "databricks_disks_key" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0
  name  = "${var.group_prefix}${format("%02d", count.index)}-dbricks-disks-key"

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
  key_size     = 2048
  key_type     = "RSA"
  key_vault_id = var.keyvault_id
}

resource "azurerm_key_vault_key" "databricks_services_key" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0
  name  = "${var.group_prefix}${format("%02d", count.index)}-dbricks-services-key"

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]
  key_size     = 2048
  key_type     = "RSA"
  key_vault_id = var.keyvault_id
}

resource "azurerm_key_vault_access_policy" "databricks_policy" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0

  key_vault_id = var.keyvault_id
  object_id    = azurerm_databricks_workspace.databricks_workspace[count.index].storage_account_identity[0].principal_id
  tenant_id    = data.azurerm_client_config.current.tenant_id

  key_permissions = [
    "Get",
    "UnwrapKey",
    "WrapKey"
  ]
}

resource "azurerm_key_vault_access_policy" "databricks_service_policy" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0

  key_vault_id = var.keyvault_id
  object_id    = data.azuread_service_principal.databricks_spn.object_id
  tenant_id    = data.azurerm_client_config.current.tenant_id

  key_permissions = [
    "Get",
    "UnwrapKey",
    "WrapKey"
  ]
}

resource "azurerm_key_vault_access_policy" "databricks_disk_policy" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0

  key_vault_id = var.keyvault_id
  object_id    = azurerm_databricks_workspace.databricks_workspace[count.index].managed_disk_identity[0].principal_id
  tenant_id    = data.azurerm_client_config.current.tenant_id

  key_permissions = [
    "Get",
    "UnwrapKey",
    "WrapKey"
  ]
}
```

### Debug Output/Panic Output

```shell
Error: Invalid index
on .terraform/modules/databricks/kv.tf line 61, in resource "azurerm_key_vault_access_policy" "databricks_policy":
  object_id    = azurerm_databricks_workspace.databricks_workspace[count.index].storage_account_identity[0].principal_id

Error: Missing required argument
with module.databricks.azurerm_key_vault_access_policy.databricks_disk_policy[0]
on .terraform/modules/databricks/kv.tf line 89, in resource "azurerm_key_vault_access_policy" "databricks_disk_policy":
  object_id    = azurerm_databricks_workspace.databricks_workspace[count.index].managed_disk_identity[0].principal_id
The argument "object_id" is required, but no definition was found.
```

### Expected Behaviour

everything build fine a week ago

### Actual Behaviour

the databricks resource no longer seems to be outputting storage and managed disk identities. i also see this error in the activity log:

\\\"code\\\": \\\"InvalidParameter\\\",\\r\\n    \\\"message\\\": \\\"https://KEYVAULT.vault.azure.net//keys/td04ybf51t300-dbricks-disks-key/d8d33b7dff184990923b3b7207ed5625 is not a valid versioned Key Vault Key URL. It should be in the format https://<vaultEndpoint>/keys/<keyName>/<keyVersion>.\\\",\\r\\n    \\\"target\\\": \\\"diskEncryptionSet.properties.activeKey.keyUrl\\\"\\r\\n  }\\r\\n}\"}]}]}}",

**Comment by fgarcia-cnb** [comment]
after much troubleshooting, i narrowed it down to the managed disk encryption parameters. As soon as i removed that, the workspace deployed fine with both dbfs and managed services encrypton enabled, and obviously managed disk encryption not enabled. Something definitely broke in the last week or so... i worked around the managed disk encryption error by using azapi:

```hcl
resource "azapi_update_resource" "dbricks_disk_encryption" {
  count = var.cmk_enabled ? (var.is_web_auth_workspace && var.resource_count > 0 ? 1 : var.resource_count) : 0

  type          = "Microsoft.Databricks/workspaces@2023-02-01"
  resource_id   = azurerm_databricks_workspace.databricks_workspace[count.index].id
  ignore_casing = true

  body = jsonencode({
    properties = {
      encryption = {
        entities = {
          managedDisk = {
            keySource = "Microsoft.Keyvault"
            keyVaultProperties = {
              keyVaultUri = replace(azurerm_key_vault_key.databricks_disks_key[count.index].versionless_id, "/\\.net/.*/", ".net")
              keyName     = azurerm_key_vault_key.databricks_disks_key[count.index].name
              keyVersion  = azurerm_key_vault_key.databricks_disks_key[count.index].version
            }
            rotationToLatestKeyVersionEnabled = true
          }
        }
      }
    }
  })

  response_export_values = ["properties.managedDiskIdentity.principalId"]
```

**Comment by osuleiman** [comment]
@fgarcia-cnb the error seems to be complaining about the key URI which is indeed incorrect (note the double "/"):

https://keyvault.vault.azure.net**//**keys/td04ybf51t300-dbricks-disks-key/d8d33b7dff184990923b3b7207ed5625

**Comment by fgarcia-cnb** [comment]
good eye. i didnt notice that extra slash. but in my code that value comes directly from the key resource:
```hcl
managed_disk_cmk_key_vault_key_id = var.cmk_enabled ? azurerm_key_vault_key.databricks_disks_key[count.index].id : null
```
i checked my state file and the key id doesnt have the extra slash. so where the heck is that extra slash coming from?

**Comment by fgarcia-cnb** [comment]
i checked out the JSON that was submitted by using the azurerm_databricks_workspace resource compared to the azapi_updte_resource. notice the trailing slash in the keyVaultUri for the bad request. somewhere the keyvault uri and key name are being concatenated with an extra slash

azurerm_databricks_workspace
---
```json
 "encryption": {
            "entities": {
                "managedDisk": {
                    "keySource": "Microsoft.Keyvault",
                    "keyVaultProperties": {
                        "keyName": "tp044nbm1fz00-dbricks-disks-key",
                        "keyVaultUri": "https://dc04-prd-nshrd-infra-kv.vault.azure.net/",
                        "keyVersion": "edb48c743e454a31a4a4f1b4f7839ff2"
                    },
                    "rotationToLatestKeyVersionEnabled": true
```

azapiupdae_resource
---
```json
"encryption": {
            "entities": {
                "managedDisk": {
                    "keySource": "Microsoft.Keyvault",
                    "keyVaultProperties": {
                        "keyName": "tp044nbm1fz00-dbricks-disks-key",
                        "keyVaultUri": "https://dc04-prd-nshrd-infra-kv.vault.azure.net",
                        "keyVersion": "edb48c743e454a31a4a4f1b4f7839ff2"
                    },
                    "rotationToLatestKeyVersionEnabled": true
                },
```

**Comment by fgarcia-cnb** [comment]
i checked the JSON in the azure activity log from last week, when the `azurerm_databricks_workspace` resource was working fine. it had the trailing slash as well. so i think something changed on the azure side when concatenating `keyVaultUri` with the `keyName' values

**Comment by fgarcia-cnb** [comment]
my azapi fix eseentially does the same thing... waiits for the workspace creation before enabling the key, but in the same run. is the bug in the terraform code or azure side? i cant imagine it being in the terraform code because it used to work 2 weeks ago.

**Comment by fgarcia-cnb** [comment]
yes, but the code parses it out like this:

```go
childId := NestedItemId{
		KeyVaultBaseUrl: fmt.Sprintf("%s://%s/", idURL.Scheme, idURL.Host),
		NestedItemType:  components[0],
		Name:            components[1],
		Version:         version,
	}
```

which parses out data like this:
`
{https://<KEYVAULT>.vault.azure.net/ keys td04ybf51t300-dbricks-disks-key d8d33b7dff184990923b3b7207ed5625}
`

which is fine. Notice the trailing slash in the keyvault URI. this worked fine 2 weeks ago. So i still think something changed on the azure side when they merge these 2 values back together... they're automatcailly appending a slash, even when not necessary, causing the double slash

**Comment by fgarcia-cnb** [comment]
MS support was able to replicate the issue. Deplying a new dataricks workspace with a keyvault URL value with ending slash fails with the double slash error. This worked fine 2 weeks ago and even their API documentation examples show a trailing slask.

**Comment by camilo-s** [comment]
I just had basically the same problem.

Does anyone know if the same error also occurs when deploying the Databricks workspace including managed Disk CMK setting via ARM Template?

**Comment by camilo-s** [comment]
> 



> So a workaround in terraform is to declare a variable and use conditionals.
> 
> 1. Build the workspace with disk_cmk as false - this allows creation
> 2. Flip disk_cmk = true then reapply.

@istairbn I tried exactly this option but the second Terraform run failed at the `terraform plan` step since the `azurerm_databricks_workspace.databricks_workspace.managed_disk_identity` block is still empty when policy `azurerm_key_vault_access_policy.databricks_disk_policy` gets planned (I even declared an explicit dependence of the key vault access policy on the databricks workspace). 

I tried to get around this by not reading the `azurerm_databricks_workspace.databricks_workspace.managed_disk_identity` directly but via a data resource to enforce lazy evaluation. Then my apply failed with the error that the access policy already exists. I looked in detail and it turns out `data.azurerm_databricks_workspace.databricks_workspace.managed_disk_identity[0].principal_id` is somehow outputting  the **dbfs storage account's system-assigned managed identity used for DBFS encryption**, rather than the one of the user-assigned managed identity dbdiskencryptionset####### in the Databricks' managed resource group.

**Comment by WodansSon** [comment]
@fgarcia-cnb, it looks like the code is missing a few `depends_on` args from what I can see, take a look at this [comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/22394#issuecomment-1639550787), if you expand the configuration code you should see the required `depends_on` args to order the creation of the various key vault policies. 🚀

**Comment by fgarcia-cnb** [comment]
not sure if you saw my previous comments but the code works fine. it was an issue on Microsofts side. they were able to replicate the issue and implement a fix

**Comment by WodansSon** [comment]
@fgarcia-cnb, DOH! Sorry, I must have missed that bit in reviewing this thread. In that case I am going to go ahead and close this issue as it seems to have been fixed my upstream Microsoft. Thanks! 🚀
