### ISSUE TITLE
`azurerm_app_configuration_key`: fails to retrieve keys if app config store resides in a different subscription

### ISSUE THREAD

**Issue by favoretti** [hashicorp/terraform-provider-azurerm#21486]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.49.0-3.51.0+

### Affected Resource(s)/Data Source(s)

azurerm_app_configiration_key

### Terraform Configuration Files

n/a

### Debug Output/Panic Output

After the ID changes in `app_configuration_key` (and `_feature`) made in #20082 a regression has been introduced. Pretty wicked corner case, but still.

`app_configuration_key` must be passed a `configuration_store_id`, which `Read()` now blissfully ignores, instead deducing it from the resource ID itself, fetching ID by endpoint. 

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appconfiguration/app_configuration_key_resource.go#L226

ResourceClient defaults to your current subscription, so when the app config in question resides in a different sub, the ResourceClient gets nothing in return, resulting in a cleanup of configuration key, since parent resource "doesn't exist", or at least provider thinks so.

While being a corner case, obviously we can't ignore the resource ID for the app config that's being passed to the resource, since it might be in a different sub (as happens to be in a few of our use-cases).

@teowa want me to address this one or will you fix it yourself? Happy to fix this myself too, just don't wanna step on your toes.

### Expected Behaviour

Resource should honor apconfig ID passed to it instead of trying to be smart.

### Actual Behaviour

Trying to be smart, but fails miserably.

**Comment by teowa** [comment]
Hi @favoretti, thanks for raising this. 

What mentioned above is also issue with other data plane resources in Key Vault, Storage Account and etc. From https://github.com/hashicorp/terraform-provider-azurerm/pull/20326#issuecomment-1419224641, now we cannot use`d.Get` to get the App Configuration resource ID in read function. And if we directly check if the data plane endpoint is available, we may meet the DNS dial failure and timeout related to https://github.com/hashicorp/terraform-provider-azurerm/pull/21464. 

As a workaround, maybe users can use [provider alias](https://developer.hashicorp.com/terraform/language/providers/configuration#alias-multiple-provider-configurations) with specific subscription ID to access App Configuration at another subscription. What do you think?

**Comment by favoretti** [comment]
@teowa So... I kinda understand where you're coming from, after reading all the comments. However, what's the point of having `app_configuration_id` property at all then if we use it while creating resources (hence, requiring not aliased providers?) and we're not using it while fetching that same resource. That's where I'm getting lost.

// cc: @tombuildsstuff

**Comment by favoretti** [comment]
As discussed before, won't be fixed. Multiple providers configured to the right sub should be used.
