### ISSUE TITLE
Support for Java 17 in azurerm_app_service

### ISSUE THREAD

**Issue by garoplin** [hashicorp/terraform-provider-azurerm#21492]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to import existing Azure App Service application that run Java17 into terraform, but it seems that Java17 is not supported. I get the error: 
`│ Error: expected site_config.0.java_version to be one of [1.7 1.8 11], got 17`
I'm using azurerm 3.36.0
When can we expected to have this supported?

### New or Affected Resource(s)/Data Source(s)

azurerm3.36.0

**Comment by StefanSchoof** [comment]
If you use a current provider version with the non deprecated resource it is Supported https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#java_version

**Comment by xiaxyi** [comment]
Thanks @garoplin , java 17 is supported by Terraform already if you use the latest app service provider:
1. linux function app:https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app#java_version
2. Linux web app:https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#java_version
3. windows function app:https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app#java_version
4. windows web app:https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app#java_version

**Comment by xiaxyi** [comment]
Hey @garoplin, Just would like to double confirm with you about the exact requirement that you have, referring to what you mentioned "When can we expected to have this supported?", does it mean:
1. You are aware of the new linux/ windows resource provider, still, you would like java 17 to be support in the resource [azurerm_app_service] (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service) which will be removed in 4.0 provider.
2. You can choose the latest linux/ windows resource provider, just not aware of it when you raised this issue.

If #1 is your requirement, unfortunately, we may not consider adding any new feature/ enhancement in that resource provider as it will be deprecating soon, may I know if there is any concern switching to the latest app service resource provider?

**Comment by garoplin** [comment]
@xiaxyi Yes, I'm aware of the existence of the new resource types that support java 17. The problem is, that in our organisation we use modules that underneath have app_service instead of linux/windows_web_apps. But i guess we'll just have to rewrite the modules. Thanks for the response
