### ISSUE TITLE
Provider version 3.53.0 is not compatible with AzureGov

### ISSUE THREAD

**Issue by msnook** [hashicorp/terraform-provider-azurerm#21508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.0

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

Any Terraform configuration in Azure Gov

### Terraform Configuration Files

See simple provider configuration below, where `ARM_ENVIRONMENT` is set to `usgovernment`.

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
  required_version = ">= 1.1.1"
}
```

### Debug Output/Panic Output

```shell
Unable to run Terraform Plan/Apply.
```

### Expected Behaviour

Terraform Plan/Apply runs without issue.

### Actual Behaviour

```
│ Error: unable to build authorizer for Attestation API: could not configure ClientSecret Authorizer: determining scope for "AttestationService": the endpoint "AttestationService" is not supported in this Azure Environment
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 1, in provider "azurerm":
│    1: provider "azurerm" {
│ 
╵
```

### Steps to Reproduce

Simply run `terraform plan` on any Terraform configuration using version 3.53.0 in Azure Gov.

### Important Factoids

It looks like [this](https://github.com/hashicorp/terraform-provider-azurerm/pull/20972) modification introduced Attestation.  And the Attestation endpoint is missing from [this configuration](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/hashicorp/go-azure-sdk/sdk/environments/azure_gov.go), likely because it is still in Preview according to [the documentation](https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/?products=azure-attestation&regions=usgov-non-regional,us-dod-central,us-dod-east,usgov-arizona,usgov-texas,usgov-virginia&rar=true).

**Comment by ChandlerSwift** [comment]
This also affects AzureChinaCloud for us, with the same symptoms. However, we're currently running v3.50. Moreover, the same command running on  worked fine for us yesterday 11:45AM CDT (!), which to me suggests this is an Azure issue, not a Terraform/provider issue.

cc: @wozneyr

**Comment by stonenw** [comment]
3.52.0 worked fine for me in Azure Gov and is what I reverted too to continue operating. I do think this is a Terraform AzureRM 3.53.0 issue.

**Comment by jhaxon** [comment]
Using 3.53.0 in Azure Gov we encountered this same error.

We engaged Azure Cloud support on this issue and they confirmed it was localized to hashicorp's provider.

Rolling back to v3.52.0 gets us past the issue.

**Comment by msnook** [comment]
@tombuildsstuff When can we expect `3.54.0`?  I'm trying to determine if I should pin a few dozen repos.
