### ISSUE TITLE
Terraform aks code is not updating nodecount in nodepools

### ISSUE THREAD

**Issue by selvanayaki678** [hashicorp/terraform-provider-azurerm#21518]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Trying to update the aks nodepool node count through terraform aks creation code. But it is not scaling down the node count in aks.

Aks version 1.24.10
azurerm provider version 3.47.0

### New or Affected Resource(s)/Data Source(s)

 azurerm_kubernetes_cluster

**Comment by selvanayaki678** [comment]
resource "azurerm_kubernetes_cluster" "aks" {
		name = "testaks"
		resource_group_name = testrg
		location = "East US"		
		kubernetes_version = 1.24.10
		role_based_access_control_enabled   = "true"
		azure_policy_enabled    = "true"

		network_profile {
			network_plugin = "azure"
			network_policy = "azure"
            load_balancer_sku = "standard"
			outbound_type = "userDefinedRouting"
		}	
		
		default_node_pool {
			name = "default"
			type = "VirtualMachineScaleSets"
			orchestrator_version = 1.24.6		
			
			node_count = 3
			vm_size = "Standard_D8s_v3"
			os_disk_size_gb = 100		
			
			enable_auto_scaling = false
			
		}		
        		
		identity {
			type = "SystemAssigned"
		}
		
		tags = {
			environment = "test"
		}
		
		
    }

**Comment by stephybun** [comment]
@selvanayaki678 I'm unable to reproduce the behaviour described with the configuration provided. 

Is Terraform showing a diff after applying a change to the `node_count` or are you receiving an error?

**Comment by stephybun** [comment]
Since we haven't heard back in a while I'm going to close this issue. Please let me know if this is still a problem and we'll be happy to reopen this. Thanks!
