### ISSUE TITLE
cost management export export_data_options time frame does not support a documented value

### ISSUE THREAD

**Issue by thaliegf** [hashicorp/terraform-provider-azurerm#21523]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_subscription_cost_management_export

### Terraform Configuration Files

```hcl
provider "azurerm" {
  alias           = "video_cloud"
  features {}
}

variable "cost_management" {
  type = object({
    storage_account_name = string
    export_name = string
    root_folder = string  
  })
}

cost_management = {
        storage_account_name = "costmgmt"
        export_name = "TestExport"
        root_folder = "devExport"
        }

data "azurerm_subscription" "current" {}

resource "azurerm_storage_container" "weekly_report" {
  name                  = "weeklycostreport"
  storage_account_name  = "costexport"
  container_access_type = "private"
  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_storage_container" "weekly_report" {
  provider = azurerm.video_cloud
  name                  = "test"
  storage_account_name  = "costexport"
  container_access_type = "private"
  lifecycle {
    prevent_destroy = true
  }
}

resource "azurerm_subscription_cost_management_export" "video_cloud_weekly" {
  provider = azurerm.video_cloud
  name                          = var.cost_management.export_name
  subscription_id               = data.azurerm_subscription.current.id
  recurrence_type               = "Weekly"
  recurrence_period_start_date  = "2023-04-24T00:00:00Z"
  recurrence_period_end_date    = "2050-02-01T00:00:00Z"

  export_data_storage_location {
    container_id        = azurerm_storage_container.weekly_report.resource_manager_id
    root_folder_path    = var.cost_management.root_folder
  }

  export_data_options {
    type        = "ActualCost"
    time_frame  = "TheLastWeek"
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected export_data_options.0.time_frame to be one of [Custom BillingMonthToDate TheLastBillingMonth TheLastMonth WeekToDate MonthToDate], got TheLastWeek
│
│   with module.logging_policies.azurerm_subscription_cost_management_export.video_cloud_weekly,
│   on ..\modules\logging-policies\main.tf line 150, in resource "azurerm_subscription_cost_management_export" "video_cloud_weekly":
│  150:     time_frame  = "TheLastWeek"
│
```

### Expected Behaviour

Expect to create a cost management export with export type "Weekly export of last 7 days"

### Actual Behaviour

Documentation mentions TheLastWeek should be a value for time_frame. However terraform plan fails when this value is provided.
![image](https://user-images.githubusercontent.com/98189369/234073023-d10673a5-7835-4209-80f8-70597f609ba8.png)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/billing_account_cost_management_export

### Steps to Reproduce

terraform plan

**Comment by myc2h6o** [comment]
Hi @thaliegf thanks for opening the issue! The value in the document is actually wrong and should be `TheLast7Days`. Plus, this value is not in the Azure API swagger definition which is being tracked by https://github.com/Azure/azure-rest-api-specs/issues/23707 thus it was not added to the provider code as well. I've opened #21528 to add the new option `TheLast7Days`
