### ISSUE TITLE
Support for [Email Communication Service]

### ISSUE THREAD

**Issue by iusergii** [hashicorp/terraform-provider-azurerm#21520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[Email Communications Service](https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/create-email-communication-resource)

### New or Affected Resource(s)/Data Source(s)

azurerm_email_communication_service

**Comment by aristosvo** [comment]
I'll take a look!

**Comment by aristosvo** [comment]
PR #21526 is filed.

@iusergii Do you have explicit wishes in domains, domain validation and coupling with the `azurerm_communication_service` you already know about? If that's the case, it makes sense to provide some details here to make sure we can realise this as well.

**Comment by GraemeMeyerGT** [comment]
@aristosvo / @iusergii do I correctly understand that the Azure APIs do not yet fully support this resource? It looks like there's no documented API/attribute (and thus no Terraform resource) to configure the actual domain that's being attached (e.g. example.com). Is that right?

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/107847353/7b2b0bff-48cb-40c4-8a01-b9f9fb9f9489)

**Comment by FinOCE** [comment]
Any chance there has been an update to this? I would like to be able to connect an Email Communications Service to the Communications Service, as well as provisioning a domain to the ECS (since this in my case would be setup through Azure DNS which is already available with terraform). In the meantime, I think I will have to just manually create the resources and put the connection string into my function app's app settings, since there aren't data sources for them to retrieve these programmatically either.

**Comment by aristosvo** [comment]
Hi @FinOCE and @GraemeMeyerGT ! At the time of contribution a lot of the workflow and APIs around these resources were unclear to me.

Please file separate feature requests for the other resources to create your whole Communication setup via Terraform, happy to help if I can find some time :)

**Comment by timja** [comment]
> Please file separate feature requests for the other resources to create your whole Communication setup via Terraform, happy to help if I can find some time :)

see https://github.com/hashicorp/terraform-provider-azurerm/issues/22549 and https://github.com/hashicorp/terraform-provider-azurerm/issues/22995
