### ISSUE TITLE
Support AppConfiguration in AzureChina/AzureGovernment

### ISSUE THREAD

**Issue by superkartoffel** [hashicorp/terraform-provider-azurerm#21550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "chinaeast2"
}

resource "azurerm_app_configuration" "appconf" {
  name                = "appConf1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}

data "azurerm_client_config" "current" {}

resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_app_configuration.appconf.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_app_configuration_key" "test" {
  configuration_store_id = azurerm_app_configuration.appconf.id
  key                    = "appConfKey1"
  label                  = "somelabel"
  value                  = "a test"

  depends_on = [
    azurerm_role_assignment.appconf_dataowner
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: while retrieving the Resource ID of Configuration Store at Endpoint: "https://appconf1.azconfig.azure.cn": expected a URI in the format `https://the-appconfiguration.azconfig.io` but got "appconf1.azconfig.azure.cn"
│ 
│   with azurerm_app_configuration_key.test,
│   on test.tf line 21, in resource "azurerm_app_configuration_key" "test":
│   25: resource "azurerm_app_configuration_key" "test" {
│ 
│ while retrieving the Resource ID of Configuration Store at Endpoint:
│ "https://appconf1.azconfig.azure.cn": expected a URI in the
│ format `https://the-appconfiguration.azconfig.io` but got
│ "appconf1.azconfig.azure.cn"
╵
```

### Expected Behaviour

It should create the azurerm_app_configuration_key

### Actual Behaviour

It does not create the azurerm_app_configuration_key because the URL returned from AzureChina does not conform to the rules defined in this terraform provider:

https://github.com/hashicorp/terraform-provider-azurerm/blob/faaea10d5c34c83fb2cd08a1f60b7335c96d7a32/internal/services/appconfiguration/client/helpers.go#L182

### Steps to Reproduce

set environment variable `ARM_ENVIRONMENT=china` to let the arm client know that you want to use AzureChina instead of the regular Azure Cloud.
Then run `terraform apply`

### Important Factoids

Running in Azure China!

**Comment by superkartoffel** [comment]
I would like to create a pull request for this. I'm unsure what the purpose of this explicit check of the URL is. Is it just a basic sanity check or is there more to it?

A simple fix would be to check if the URL is `*.azconfig.io` or `*.azconfig.azure.cn`
Would that be sufficient?

**Comment by TZdybel** [comment]
I experienced the same behaviour on Azure Government. My AzureRM Provider version is 3.49.0

```
│ Error: while retrieving the Resource ID of Configuration Store at Endpoint: "https://xxxxxx.azconfig.azure.us": expected a URI in the format `https://the-appconfiguration.azconfig.io` but got "xxxxxxxx.azconfig.azure.us" 
│
│   with module.app_configuration.azurerm_app_configuration_key.apc_application_connection_string,
│   on modules/app_configuration/main.tf line 76, in resource "azurerm_app_configuration_key" "apc_application_connection_string":
│   76: resource "azurerm_app_configuration_key" "apc_application_connection_string" {
│
│ while retrieving the Resource ID of Configuration Store at Endpoint:
│ "https://xxxxxx.azconfig.azure.us": expected a URI
│ in the format `https://the-appconfiguration.azconfig.io` but got
│ "xxxxxxx.azconfig.azure.us"
```

**Comment by bsuchorowski** [comment]
Any estimates on fixing this issue? This happens on our Azure Government instance as well.

**Comment by superkartoffel** [comment]
Thanks @TZdybel for the PR. Can we find someone to review and merge it? @tombuildsstuff maybe?

**Comment by tajatassi** [comment]
Hey is there any update on this issue so far?
