### ISSUE TITLE
Terraform State File not Updating after Removal of Azure Storage Account Path Mappings in App Service

### ISSUE THREAD

**Issue by no-hands-hand** [hashicorp/terraform-provider-azurerm#21556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.0

### AzureRM Provider Version

3.20.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service

### Terraform Configuration Files

```hcl
storage_account {
    name = "${var.name-prefix}-adlproc-files-${var.name-suffix}"
    type = "AzureFiles"
    account_name = var.adlproc-storageaccount-name
    share_name = var.adlproc-fileshare-name
    access_key = var.adlproc-storageaccount-access-key
    mount_path = "/home/data/adl_files_processed"
  }
  storage_account {
    name = "${var.name-prefix}-fsm-files-${var.name-suffix}"
    type = "AzureFiles"
    account_name = var.adlproc-storageaccount-name
    share_name = var.fsm-fileshare-name
    access_key = var.adlproc-storageaccount-access-key
    mount_path = "/home/data/adl_files"
  }
  storage_account {
    name = "${var.name-prefix}-adl-exception-files-${var.name-suffix}"
    type = "AzureFiles"
    account_name = var.adlproc-storageaccount-name
    share_name = var.adlproc-exception-fileshare-name
    access_key = var.adlproc-storageaccount-access-key
    mount_path = "/home/data/adl_exception_files"
  }
```

### Debug Output/Panic Output

```shell
https://gist.github.com/no-hands-hand/c2286baeb973011e2000dfa8880e4257
```

### Expected Behaviour

After removing these storage account mappings from the TF file, they should be removed from state file and by extension removed from app service.

### Actual Behaviour

After I removed these storage account mappings from TF file, the mappings were not removed from the Terraform state file (even after doing a terraform plan) and are still present in the app service.

### Steps to Reproduce

1. 'terraform init'
2. 'terraform plan'
3. 'terraform init'
4. 'terraform apply'

**Comment by xiaxyi** [comment]
Thanks @no-hands-hand for raising this issue, can I confirm with you about the detailed removal operation that you've took?

Did you remove all the storage accounts that are mapped to the app service, which means you are using an empty list to update the storage account or you have just removed some of the SAs and have at least one left? If the answer is empty list update, can you try using the rest api and see if the storage account list can be override by the empty list?

Besides, the resource provider `azurerm_app_service` is deprecating and will be removed in 4.0 provider, we suggest the user to use the latest app service provider `azurerm_windows_web_app` and `azurerm_linux_web_app`.

**Comment by no-hands-hand** [comment]
Hi @xiaxyi , we removed all the storage accounts that are mapped to the app service. There is not an actual empty list (like, say storage_account = {}), but all of those mappings were directly removed from the configuration files.

As to the use of azurerm_app_service, the usage of that is determined by my organization rather than me, but I will pass on the recommendation.

**Comment by xiaxyi** [comment]
@no-hands-hand Thanks, let me know if you have any issues using the lasted provider~

**Comment by rcskosir** [comment]
Thanks for opening this issue. As noted above the azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead. Since we won't be making updates to azurerm_app_service, I am going to mark this closed.
