### ISSUE TITLE
Cannot output azurerm_windows_function_app

### ISSUE THREAD

**Issue by JonathonAnderson** [hashicorp/terraform-provider-azurerm#21551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.27.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_function_app

### Terraform Configuration Files

```hcl
output test3 {
  value = azurerm_windows_function_app.dr
  sensitive = true
}

resource "azurerm_windows_function_app" "dr" {
  name                = "acp-dr-test-eastus-001"
  location            = azurerm_resource_group.dr.location
  resource_group_name = azurerm_resource_group.dr.name

  lifecycle { ignore_changes = [ app_settings, tags ]}

  service_plan_id            = azurerm_service_plan.dr.id
  storage_account_name       = azurerm_storage_account.app.name
  storage_account_access_key = azurerm_storage_account.app.primary_access_key

  functions_extension_version = "~4"

  site_config {
    application_stack {
      dotnet_version               = 6
      use_dotnet_isolated_runtime = false
    }
    application_insights_connection_string = azurerm_application_insights.dr.connection_string
    application_insights_key               = azurerm_application_insights.dr.instrumentation_key
  }

  tags = azurerm_resource_group.dr.tags
}
```

### Debug Output/Panic Output

```shell
Error: Output refers to sensitive values

  on az-sync-temp.tf line 52:
  52: output test3 {

To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your intent.

If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
    sensitive = true
```

### Expected Behaviour

Terraform should output the resource and only mark sensitive values as sensitive

### Actual Behaviour

Terraform marks the entire resource as sensitive, making it impossible to view resource details

**Comment by xiaxyi** [comment]
Thanks @JonathonAnderson for raising this issue, the windows function app object contains sensitive information so the whole object is treated as sensitive. 

you can try using terraform output test3  in the command line to see the result.

However, we don't recommend output the data of the whole object as there will be maintenance cost, also not secure. The best practice is to query specific property in the output.

**Comment by xiaxyi** [comment]
Hi @JonathonAnderson , may I know if you have any follow up questions?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @xiaxyi‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
