### ISSUE TITLE
Please provide example for usage of custom_data in azurerm_windows_virtual_machine documentation

### ISSUE THREAD

**Issue by AzySir** [hashicorp/terraform-provider-azurerm#21568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please provide example for custom_data in azurerm_windows_virtual_machine. This thing is impossible to use deeming it redundant. 

There is also user_data

The documentation also doesn't indicate how this is run - is this running powershell OR is this running cmd? 

Please advise.... 

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

**Comment by myc2h6o** [comment]
I've created #22951 to add the examples. And about retrieving the user data inside the VM, here is the Azure document for how to achieve that: https://learn.microsoft.com/azure/virtual-machines/instance-metadata-service?tabs=linux#get-user-data
