### ISSUE TITLE
Modify azurerm_monitor_metric_alert for Microsoft.Sql/servers/databases fail

### ISSUE THREAD

**Issue by Jerico815** [hashicorp/terraform-provider-azurerm#21589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_metric_alert" "alert_sql_database_freediskspacepercent" {
  provider                 = azurerm.sub01
  count                    = local.sql_database_sub01 == [] ? 0 : 1
  enabled                  = local.all_alerts_enabled
  name                     = "SQL_Database_FreeDiskSpacePercent"
  description              = "xxx"
  resource_group_name      = azurerm_resource_group.this.name
  auto_mitigate            = true
  scopes                   = local.sql_database_sub01
  severity                 = 2
  tags                     = local.tags
  target_resource_location = local.location
  target_resource_type     = "Microsoft.Sql/servers/databases"
  window_size              = "PT15M"
  frequency                = "PT15M"

  action {
    action_group_id = local.action_groups[0]
  }

  criteria {
    aggregation            = "Maximum"
    metric_name            = "storage_percent"
    metric_namespace       = "Microsoft.Sql/servers/databases"
    operator               = "GreaterThan"
    skip_metric_validation = false
    threshold              = 80
  }
}


locals {
     sql_database_sub01 = [
"/subscriptions/xxxx/resourceGroups/rg01/providers/Microsoft.Sql/servers/sqlserver01/databases/db01",
"/subscriptions/xxxx/resourceGroups/rg02/providers/Microsoft.Sql/servers/sqlserver02/databases/db02",
"/subscriptions/xxxx/resourceGroups/rg03/providers/Microsoft.Sql/servers/sqlserver03/databases/db03",
"/subscriptions/xxxx/resourceGroups/rg04/providers/Microsoft.Sql/servers/sqlserver04/databases/db04",
"/subscriptions/xxxx/resourceGroups/rg05/providers/Microsoft.Sql/servers/sqlserver05/databases/db05"
]
}
```

### Debug Output/Panic Output

```shell
Error: creating or updating Monitor Metric Alert (Subscription: "xxx"
│ Resource Group Name: "xxx"
│ Metric Alert Name: "SQL_Database_FreeDiskSpacePercent"): metricalerts.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Scopes property is invalid. Only single resource is allowed for criteria type SingleResourceMultipleMetricCriteria. If you want to create an alert on multiple resources, use MultipleResourceMultipleMetricCriteria odata.type."
```

### Expected Behaviour

Modify alert

### Actual Behaviour

Error see above

The strange thing is, if I create the alert from scratch as an example with 5 databases, everything is fine.
If I want to modify the existing alert (add or remove a single database), I get the error.
If I am using the Azure Portal, everything works fine.

Any ideas?

### Steps to Reproduce

1. terraform apply
2. Everything is working
3. Add or Remove ids from the local.sql_database_sub01 (local.sql_database_sub01 contains the database ids)
4. terraform apply
5. Error

**Comment by davejdeemer** [comment]
For what it's worth, I _just_ bumped in this today. I dropped down to 3.52.0, same error. On **3.50.0**, for my use case the apply is successful.
