### ISSUE TITLE
Support for zone-redundant site recovery replication recovery plans

### ISSUE THREAD

**Issue by viewegchris** [hashicorp/terraform-provider-azurerm#21584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current version of azurerm_site_recovery_replication_recovery_plan does not support the creation of recovery plans for VMs protected by Availability Zone to Availability Zone replication. 

The last versions of ARM Template provide therefore the property providerSpecificInput:
```
"providerSpecificInput" : [
    {
      "instanceType" : "A2A",
      "primaryZone" : "1",
      "recoveryZone" : "2"
    }
  ] 
```
https://learn.microsoft.com/en-us/azure/templates/microsoft.recoveryservices/2022-10-01/vaults/replicationrecoveryplans?pivots=deployment-language-arm-template#recoveryplana2ainput-1

Please add support for this property. Currently it's just possible to add recovery plans for zone zo zone replication via azurerm_template_deployment without the possibility to update the plan later, without destoning it first. 

### New or Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replication_recovery_plan 

### Potential Terraform Configuration

```hcl
resource "azurerm_site_recovery_replication_recovery_plan" "example" {
  name                      = "example-recover-plan"
  recovery_vault_id         = azurerm_recovery_services_vault.target.id
  source_recovery_fabric_id = azurerm_site_recovery_fabric.source.id
  target_recovery_fabric_id = azurerm_site_recovery_fabric.target.id

  instanceTyp" : "A2A"
  primaryZone :  1
  recoveryZone : 2
  
  recovery_group {
    type                       = "Boot"
    replicated_protected_items = [azurerm_site_recovery_replicated_vm.test.id]
  }
}
```

**Comment by ziyeqf** [comment]
Hi @viewegchris, thanks for opening this issue.

Have opened a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/21666) to support this, once it merged & released, the feature will be available.

For any further question please leave comments.
Thanks!
