### ISSUE TITLE
Support for multi azure accounts via AZURE_CONFIG_DIR

### ISSUE THREAD

**Issue by rmrf** [hashicorp/terraform-provider-azurerm#21593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Per this document [Terraform Registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli), azurerm directly use `az` command for plan/apply operation

We have mutlti azure accounts, which use different `AZURE_CONFIG_DIR` for switching the `az` command operation , wish this can works for Terraform azurerm. 

### New or Affected Resource(s)/Data Source(s)

azurerm

### Potential Terraform Configuration

```hcl
# Configure the Microsoft Azure Provider
provider "azurerm" {
  features {}
  azure_config_dir = "/home/terraform/azure-config1"
}
```
```


### References

https://learn.microsoft.com/en-us/cli/azure/azure-cli-configuration#cli-configuration-file

**Comment by magodo** [comment]
@rmrf Per the Azure CLI document, you can setup the `AZURE_CONFIG_DIR` env var prior to running `terraform` to point to the expected config.

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).

**Comment by rmrf** [comment]
@magodo I think this issue is asking for how to setup **multi** `AZURE_CONFIG_DIR` env var for terraform, right?

**Comment by magodo** [comment]
@rmrf Sorry I misunderstood your ask. So what you actually want here is to allow each terraform's provider (alias) to point to one CLI config dir?

**Comment by rmrf** [comment]
> @rmrf Sorry I misunderstood your ask. So what you actually want here is to allow each terraform's provider (alias) to point to one CLI config dir?

Yes, sorry I didn't state this more clearly at first. 

When we using only One Azure Account weeks ago, the terraform scenario is easy:  Our user just manager resource under one terraform's provider (alias) , this alias mapping to one subscription he wanted. that works perfect. 

Recently we have other Azure Accounts need to manager, this way not works, as our Terraform CI box can only manager one `az` account(I cant' provide env var to it). So I wish inside the `provider "azurerm"` we can also provide the `azure_config_dir` beside of `subscription_id`

**Comment by magodo** [comment]
@rmrf Is there any specific reason not to use service principal instead? Maintaining multiple Azure configuration directories and use them correctly in Terraform seems to easily go wrong.

**Comment by rmrf** [comment]
@magodo   I didn't notice the suggestion of using Service Principal  part on the document, I will give that a try, Thanks.  feel free to close this issue.

**Comment by rmrf** [comment]
@magodo  just provider one reason to use `az` command running on our Terraform CI Box, this box need a specific proxy to access the Internet, so our `az` command is alias `"HTTPS_PROXY=http://xxxx:3128 HTTP_PROXY=http://xxxxx:3128 az`, I'm not sure does this works or not on Service Principal Way, I will give a try.

**Comment by rcskosir** [comment]
Closing as noted by author above, thanks!
