### ISSUE TITLE
`Microsoft.App/environments` invalid delegation for a subnet

### ISSUE THREAD

**Issue by StiviiK** [hashicorp/terraform-provider-azurerm#21604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.54.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "core_containerappsenv" {
  name                 = "${local.prefixes.core_normal}-snet-cae"
  resource_group_name  = azurerm_resource_group.rg_core.name
  virtual_network_name = azurerm_virtual_network.core.name
  address_prefixes     = ["10.50.1.0/25"]
  delegation {
    name = "core-containerappsenv"
    service_delegation {
      name    = "Microsoft.App/environments"
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected delegation.0.service_delegation.0.name to be one of [Microsoft.ApiManagement/service Microsoft.AzureCosmosDB/clusters Microsoft.BareMetal/AzureVMware Microsoft.BareMetal/CrayServers Microsoft.Batch/batchAccounts Microsoft.ContainerInstance/containerGroups Microsoft.ContainerService/managedClusters Microsoft.Databricks/workspaces Microsoft.DBforMySQL/flexibleServers Microsoft.DBforMySQL/serversv2 Microsoft.DBforPostgreSQL/flexibleServers Microsoft.DBforPostgreSQL/serversv2 Microsoft.DBforPostgreSQL/singleServers Microsoft.HardwareSecurityModules/dedicatedHSMs Microsoft.Kusto/clusters Microsoft.Logic/integrationServiceEnvironments Microsoft.LabServices/labplans Microsoft.MachineLearningServices/workspaces Microsoft.Netapp/volumes Microsoft.Network/dnsResolvers Microsoft.Network/managedResolvers Microsoft.PowerPlatform/vnetaccesslinks Microsoft.ServiceFabricMesh/networks Microsoft.Sql/managedInstances Microsoft.Sql/servers Microsoft.StoragePool/diskPools Microsoft.StreamAnalytics/streamingJobs Microsoft.Synapse/workspaces Microsoft.Web/hostingEnvironments Microsoft.Web/serverFarms Microsoft.Orbital/orbitalGateways NGINX.NGINXPLUS/nginxDeployments PaloAltoNetworks.Cloudngfw/firewalls Qumulo.Storage/fileSystems], got Microsoft.App/environments
│ 
│   with azurerm_subnet.core_containerappsenv,
│   on network.tf line 33, in resource "azurerm_subnet" "core_containerappsenv":
│   33:       name    = "Microsoft.App/environments"
│ 
╵
```

### Expected Behaviour

The delegation `Microsoft.App/environments` should be accepted for subnets, as it is required for Azure Container Apps Environments using the workload profiles architecture. 
Microsoft Documentation: https://learn.microsoft.com/en-us/azure/container-apps/networking#subnet

**Comment by sanderrhorst** [comment]
Running into this as well. Service Delegation support is required for me to work with Container Apps Environment.
Please add this to the supported delegations.
