### ISSUE TITLE
Support for AKS trusted access

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#21629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AKS recently offers trusted access. Trusted Access is required for Azure Backup and AKS Private Clusters

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_trusted_access_role_binding

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_trusted_access_role_binding" "this" {
  name           = "bindingName"
  clustr_id     = azurerm_kubernetes_cluster.example.id
  source_resource_id = "/subscriptions/0000/resourceGroups/myResourceGroup/providers/Microsoft.Demo/samples"
  roles = ["Microsoft.Demo/samples/reader","Microsoft.Demo/samples/writer"]
}
```

### References

* https://learn.microsoft.com/en-us/azure/aks/trusted-access-feature

**Comment by stephybun** [comment]
Closed by #22647
