### ISSUE TITLE
Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: could not parse Azure CLI version: launching Azure CLI: exec: "az": executable file not found in $PATH

### ISSUE THREAD

**Issue by GavinDBL** [hashicorp/terraform-provider-azurerm#21633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.54.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
terraform {
  cloud {
    organization = "my-org"

    workspaces {
      name = "azure-terraform"
    }
  }

  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.54.0"
    }
  }
}

provider "azurerm" {
  features {}
  use_cli = false
}


resource "azurerm_resource_group" "rg" {
  name     = "myTFResourceGroup"
  location = "westus2"
}
```

### Debug Output/Panic Output

```shell
<script src="https://gist.github.com/GavinDBL/14b171c54f8eba472404a40fe0dc764d.js"></script>
```

### Expected Behaviour

Plan output

### Actual Behaviour

Error about az not in path

### Steps to Reproduce

terraform init
terraform plan

**Comment by eastlondoner** [comment]
Seeing this as well, to make things worse it also goes away if I switch back to AzureRM Provider Version `3.52.0`

**Comment by solidcloudio** [comment]
I was able to resolve this by changing the Workspace variables "ARM_CLIENT_ID", etc...  from "Terraform variables" to "Environment variables"

The error message was pretty misleading on the cause however..

Terraform variable
These variables should match the declarations in your configuration. Click the HCL box to use interpolation or set a non-string value.
Environment variable
These variables are available in the Terraform runtime environment.

**Comment by GavinDBL** [comment]
Resolved with solidcloudio's comment.
