### ISSUE TITLE
azurerm_search_service: Issue with "hosting_mode" in azurerm 3.54. Forces replacement of Resource due to the API returning 'Default' with a capital and azurerm trying change this to 'default' without a capital

### ISSUE THREAD

**Issue by a111792** [hashicorp/terraform-provider-azurerm#21630]
There seems to be an issue with the new argument: "hosting_mode" with azurerm 3.54. It is forcing a replacement of the search service due to the API returning 'Default' with a capital and azurerm trying change this to 'default' without a capital:

hosting_mode                             = "Default" -> "default" # forces replacement

I've checked the terraform state: `terraform state show "azurerm_search_service.example"`
And it returns:

resource "azurerm_search_service" "example" {
    ...
    hosting_mode          = "Default"
    ...
    
Removing the resource from state and re-importing does not help to resolve the issue. 

Setting the argument in the Terraform code to: `hosting_mode = "default"` also forces the replacement. 

Trying to use  `hosting_mode = "Default"` errors out too.

I've had to lock the azurerm provider to 3.53 to allow the run to complete without forcing the replacement.

Here is the original Terrafrom code:

resource "azurerm_search_service" "example" {
  name                                          = local.cognitive_search_name
  resource_group_name               = local.resource_group_name
  location                                      = local.location
  sku                                              = "standard"  
  public_network_access_enabled = false
  identity {
    type = "SystemAssigned"
  }
  tags = local.common_tags
}

_Originally posted by @njglenuk in https://github.com/hashicorp/terraform-provider-azurerm/issues/21323#issuecomment-1529376467_

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of hashicorp/pandora#2468. As such, I am going to mark this issue as closed.
