### ISSUE TITLE
Support for authenticate via Workload Identity

### ISSUE THREAD

**Issue by balazs92117** [hashicorp/terraform-provider-azurerm#21635]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Workload Identity is [finally GA](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/general-availability-for-azure-active-directory-ad-workload/ba-p/3798292)
It is  successor of [Azure AD Pod Identity](https://github.com/Azure/aad-pod-identity): https://azure.github.io/azure-workload-identity/docs/
I would like to use it to [Authenticating to Azure](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#authenticating-to-azure) of the AzureRM provider.
E.g.: We use Gitlab runner in an AKS cluster for running terraform. With this solution I don't need to pass Azure credentials to the provider, I could use the native Workload Identity.

### New or Affected Resource(s)/Data Source(s)

azurerm

**Comment by magodo** [comment]
@balazs92117 This seems has already been supported https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_oidc.

See an example usage here: https://github.com/hashicorp/terraform-provider-azurerm/issues/18612#issuecomment-1279912274

**Comment by manicminer** [comment]
That is correct, we already support workload identity for AKS (in addition to the now deprecated pod identity).

To configure Terraform you'll need to set the `ARM_OIDC_TOKEN_FILE_PATH` environment variable - I believe that the token path is contained in the `AZURE_FEDERATED_TOKEN_FILE` environment variable by default, so you'd need to grab this value and export it as the `ARM_OIDC_TOKEN_FILE_PATH`, or slurp up this file and export its contents as the `ARM_OIDC_TOKEN` environment variable. See this extract from the [provider documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs) for more details:

<img width="689" alt="Screenshot 2023-05-09 at 11 21 31" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/251987/bdaf0943-a03f-4824-a564-9f414ce6e40e">

As this authentication method is already supported by the provider, I'm going to close this issue for now, but if you believe you have found an issue with how the provider handles authentication in this scenario, please feel free to open a bug report using the template provided, and we'll be happy to look into it. Thanks!
