### ISSUE TITLE
Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ArtifactVersionNotFound" Message="No version found in the artifact repository that satisfies the requested version '2.1' for VM extension with publisher 'Microsoft.Azure.Extensions' and type 'CustomScript'."

### ISSUE THREAD

**Issue by AnushankarKonduri** [hashicorp/terraform-provider-azurerm#21646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.4

### AzureRM Provider Version

3.33.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_extension.

### Terraform Configuration Files

```hcl
I am trying to add new azurerm_virtual_machine_extension resource block. In one block I have already installed linux agent and in new extension resource block I am trying to install dotnet

esource "azurerm_virtual_machine_extension" "agent_pool_vm" {
name = "abc"
virtual_machine_id = azurerm_linux_virtual_machine.pipeline_agent.id
publisher = "Microsoft.Azure.Extensions"
type = "CustomScript"
type_handler_version = "2.1"

protected_settings = <<SETTINGS
{
"script" : "${base64encode(file(var.scfile))}"
}

SETTINGS

tags = var.listed_tag

depends_on = [
azurerm_linux_virtual_machine.pipeline_agent
]
}

DotNet custom script
resource "azurerm_virtual_machine_extension" "dotnet_core_vm" {
name = "xyz"
virtual_machine_id = azurerm_linux_virtual_machine.pipeline_agent.id
publisher = "Microsoft.Azure.Extensions"
type = "CustomScript"
type_handler_version = "2.1"

protected_settings = <<SETTINGS
{
"script" : "${base64encode(file(var.sc1file))}"
}

SETTINGS

tags = var.listed_tag

depends_on = [
azurerm_linux_virtual_machine.pipeline_agent
]
}
```

### Debug Output/Panic Output

```shell
but I am getting following error for second block (Note the first block in not included in plan as it alrady been applied by terraform):

azurerm_virtual_machine_extension.dotnet_core_vm: Creating...
╷
│ Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ArtifactVersionNotFound" Message="No version found in the artifact repository that satisfies the requested version '2.1' for VM extension with publisher 'Microsoft.Azure.Extensions' and type 'CustomScript'."
│
│ with azurerm_virtual_machine_extension.dotnet_core_vm,
│ on main.tf line 157, in resource "azurerm_virtual_machine_extension" "dotnet_core_vm":
│ 157: resource "azurerm_virtual_machine_extension" "dotnet_core_vm" {
```

**Comment by tombuildsstuff** [comment]
hi @AnushankarKonduri 

Thanks for opening this issue.

Unfortunately the Azure API only allows provisioning one of each Extension type, whilst this error message isn't great coming back from the API, this appears to be an API design limitation and you'd need to combine these into a single Custom Script Extension for this to run.

Since this is a configuration question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but should you have further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
