### ISSUE TITLE
Support for azurerm_sentinel_alert_rule_scheduled start time

### ISSUE THREAD

**Issue by chanster** [hashicorp/terraform-provider-azurerm#21653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The resource `azurerm_sentinel_alert_rule_scheduled` is missing one argument which allows control of when the schedule starts and is run.

This option is available in the web interface
<img width="602" alt="image" src="https://user-images.githubusercontent.com/232767/236236527-5443ca79-799b-4b34-946d-8aabbdf82678.png">

### New or Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_scheduled

### Potential Terraform Configuration

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "example" {
  ...
  start_time = "2023-05-05T11:00:00Z"
  ...
}
```

**Comment by ziyeqf** [comment]
Hi @chanster, thanks for opening this issue.

As the Portal shows, it's a preview feature, has not exposed API yet.  Have opened an issue (https://github.com/Azure/azure-rest-api-specs/issues/23830) requesting for this API.

For any further questions, please leave comments.
Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to close it for now.  When it gets added, we can reopen this request or you can create a new one.
https://github.com/Azure/azure-rest-api-specs/issues/23830
