### ISSUE TITLE
Azure Devops does not allow to use Terraform CLI to target a resource with double quotes 

### ISSUE THREAD

**Issue by intoinr** [hashicorp/terraform-provider-azurerm#21674]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

TerraformCLI@0

### Terraform Configuration Files

```hcl
- task: TerraformCLI@0
  displayName: terraform_plan
  inputs:
    command: plan
    workingDirectory: ${{ parameters.workingDirectory }}
    environmentServiceName: ${{ parameters.backendServiceArm }}
    commandOptions: '-out=/home/vsts/work/1/s/terraform.tfplan -detailed-exitcode -target=module.azure.azurerm_resource_group.azure["resource_group1_key"] -target=module.azure.azurerm_resource_group.azure["virtual_network1_key"] -target=module.azure.azurerm_virtual_network.azure["resource_group1_key"] -target=module.azure.azurerm_virtual_network.azure["virtual_network1_key"]'
```

### Debug Output/Panic Output

```shell
│ Error: Invalid target "module.azure.azurerm_virtual_network.azure[resource_group1_key]"
│ 
│ Index brackets must contain either a literal number or a literal string.
╵
╷
│ Error: Invalid target "module.azure.azurerm_virtual_network.azure[virtual_network1_key]"
│ 
│ Index brackets must contain either a literal number or a literal string.
╵

For more help on using this command, run:
  terraform plan -help
##[error]Terraform command 'plan' failed with exit code '1'.
##[error]╷
│ Error: Invalid target "module.azure.azurerm_resource_group.azure[resource_group1_key]"
│ 
│ Index brackets must contain either a literal number or a literal string.
╵
╷
│ Error: Invalid target "module.azure.azurerm_resource_group.azure[virtual_network1_key]"
│ 
│ Index brackets must contain either a literal number or a literal string.
╵
╷
│ Error: Invalid target "module.azure.azurerm_virtual_network.azure[resource_group1_key]"
│ 
│ Index brackets must contain either a literal number or a literal string.
╵
╷
│ Error: Invalid target "module.azure.azurerm_virtual_network.azure[virtual_network1_key]"
│ 
│ Index brackets must contain either a literal number or a literal string.
╵

For more help on using this command, run:
  terraform plan -help

Finishing: tf plan
```

### Expected Behaviour

The plan should have run correctly.

### Steps to Reproduce

I have used the vmImage 'ubuntu-latest'.

**Comment by tombuildsstuff** [comment]
hi @intoinr 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding usage of the provider when running in Azure DevOps rather than specific to Terraform - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
