### ISSUE TITLE
Support for PatchSettings automaticByPlatformSettings

### ISSUE THREAD

**Issue by larsmaes-sogeti** [hashicorp/terraform-provider-azurerm#21690]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please implement: 
- [Automatic by Platform Settings: Linux](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#linuxvmguestpatchautomaticbyplatformsettings)
- [Automatic by Platform Settings: Windows](https://learn.microsoft.com/en-us/rest/api/compute/virtual-machines/create-or-update?tabs=HTTP#windowsvmguestpatchautomaticbyplatformsettings)

This is to be able to configure custom update schedules and update reboot policy

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine, azurerm_windows_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "vm" {
...
patch_mode = "AutomaticByPlatform"
bypass_platform_safety_checks_on_user_schedule = true
reboot_settings = "IfRequired"
...
}
```

**Comment by myc2h6o** [comment]
Hi @oswdr you are right, VM has been using /kermit sdk currently and we need an update for the sdk version before onboarding this new feature, I've created https://github.com/tombuildsstuff/kermit/pull/207 to generate the new sdk version

**Comment by larsmaes-sogeti** [comment]
It seems that the required sdk updates have been merged. Can you take another look at it please?

**Comment by brakelee** [comment]
Is there any update on this issue? Is this now fixed?
