### ISSUE TITLE
Support for azurerm_virtual_hub routing policies

### ISSUE THREAD

**Issue by molson504x** [hashicorp/terraform-provider-azurerm#21701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it looks like Routing Intents and Policies are not able to be managed by the azurerm_virtual_hub resource.  This is pretty crucial to determining how traffic gets routed through a secure virtual hub, such as routing all traffic through an azure firewall or some other network appliance.  Note that this is different than a route table.

API Documentation: https://learn.microsoft.com/en-us/rest/api/virtualwan/routing-intent/create-or-update?tabs=HTTP

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_hub, azurerm_routing_intent

### Potential Terraform Configuration

```hcl
resource "azurerm_routing_intent" "routing_intent" {
  virtual_hub_id = var.virtual_hub_id
  routing_policy {
    name = "InternetRoutingPolicy"
    destinations = ["Internet"]  # Can be any of ["PrivateTraffic", "Internet"]
    nextHopResourceId = var.azure_firewall_id  # Can be the resource ID of a firewall, network appliance, etc...  or "None"
  }

  routing_policy {
    name = "PrivateTrafficRoutingPolicy"
    destinations = ["PrivateTraffic"]  # Can be any of ["PrivateTraffic", "Internet"]
    nextHopResourceId = "None"  # Can be the resource ID of a firewall, network appliance, etc...  or "none"
  }  
}
```

### References

https://learn.microsoft.com/en-us/rest/api/virtualwan/routing-intent/create-or-update

**Comment by molson504x** [comment]
> This also needs to be supported by azurerm_firewall?
> 
> > Customers using Azure Firewall in Virtual WAN secured hub can either set Azure Firewall Manager's 'Enable inter-hub' setting to 'Enabled' to use routing intent or use Virtual WAN portal to directly configure Azure Firewall as the next hop resource for routing intent and policies. Configurations in either portal experience are equivalent and changes in Azure Firewall Manager are automatically reflected in Virtual WAN portal and vice versa.
> 
> https://learn.microsoft.com/en-us/azure/virtual-wan/how-to-routing-policies#configuring-routing-intent-through-azure-portal

Yes.  I suspect that's why the Azure API has it as a separate thing, which was a part of why I proposed it as a separate resource provider.  Also looking at that article, you're still doing the configuration for a virtual hub (as part of the firewall policy).  I think that's why I proposed taking in the `virtual_hub_id` here.

**Comment by whizzer929** [comment]
Have you tried using azapi to set the routing intent?  azapi_update_resource.  I'm just starting to look into this as a workaround for now.

**Comment by dancarltonigt** [comment]
> Have you tried using azapi to set the routing intent? azapi_update_resource. I'm just starting to look into this as a workaround for now.

@whizzer929 I looked into this but could not find a way that worked using azapi_update_resource or azapi_resource.

If you do come up with a workaround using those resources, please respond back.

**Comment by whizzer929** [comment]
This appears to work.  I need to do more testing, but it did change the Routing Intent settings on the hub.  The trick was determining the correct type. 

`resource "azapi_resource" "hub_route_intent" {
  name      = "route_intent_name"
  parent_id = azurerm_virtual_hub.vwan_hub.id
  type      = "Microsoft.Network/virtualHubs/routingIntent@2022-09-01"

  body = jsonencode({
    properties = {
      "routingPolicies": [
      {
        "name": "InternetTraffic",
        "destinations": [
          "Internet"
        ],
        "nextHop": "${azurerm_firewall.hub_firewall.id}"
      },
      {
        "name": "PrivateTrafficPolicy",
        "destinations": [
          "PrivateTraffic"
        ],
        "nextHop": "${azurerm_firewall.hub_firewall.id}"
        }
      ]
    }
  })

  depends_on = [
    azurerm_virtual_hub.vwan_hub,
    azurerm_firewall.hub_firewall,
    azurerm_vpn_gateway.vpn_gateway,
    azurerm_express_route_gateway.er_gateway
  ]
}`

**Comment by dancarltonigt** [comment]
@whizzer929 Thanks for the update. Where are you defining/updating the destinations for Private Traffic and Internet?

**Comment by dancarltonigt** [comment]
@whizzer929 The private IP ranges can be set, but it appears it will pull them from the firewall, so no need to set in routing intent as well.

I asked because we have a couple of public /16s we have never advertised to the Internet, that we use internally.

**Comment by cveld** [comment]
What I find confusing is that there are two screens:
* Virtual hub routing intent
* Virtual hub integrated firewall vnet connection security
On the latter you can set the firewall for public traffic or private traffic per vnet connection.
I was expecting some properties on `azurerm_virtual_hub_connection`. Actually there is this `internet_security_enabled` property but this doesn't seem to do much. There doesn't seem to be a `private_network_security_enabled` property though.

**Comment by patpicos** [comment]
For anyone interested in a fully baked solution:
https://github.com/claranet/terraform-azurerm-virtual-wan/tree/main/modules/routing-intent
