### ISSUE TITLE
Network Security Rules not being updated

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/terraform-provider-azurerm#21711]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.5.5

### Affected Resource(s)/Data Source(s)

azurerm_network_security_group

### Terraform Configuration Files

```hcl
# MODULE
resource "azurerm_network_security_group" "main" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name 

  dynamic "security_rule" {
    for_each = merge(var.nsg_security_rules, (var.allow_local_rules_in ? local.rules : {}) )
    content {
      name                         = security_rule.value.name
      priority                     = security_rule.value.priority
      direction                    = security_rule.value.direction
      access                       = security_rule.value.access
      protocol                     = security_rule.value.protocol
      source_port_range            = security_rule.value.source_port_range
      source_port_ranges           = security_rule.value.source_port_ranges
      destination_port_range       = security_rule.value.destination_port_range
      destination_port_ranges      = security_rule.value.destination_port_ranges
      source_address_prefix        = security_rule.value.source_address_prefix
      source_address_prefixes      = security_rule.value.source_address_prefixes
      destination_address_prefixes = security_rule.value.destination_address_prefixes
      destination_address_prefix   = security_rule.value.destination_address_prefix
      description                  = security_rule.value.description
    }
  }
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

After creating the NSG, when calling the module and setting the `var.allow_local_routes_in = false`, the rules are removed from the NSG.n

### Actual Behaviour

After creating the NSG, these rules cannot be removed even after commenting out the security_rule block, it does not remove the routes.

Is this expected behaviour in that security rules within the azurerm_network_security_group resource are not removed after creation?

### Steps to Reproduce

terraform plan

**Comment by sinbai** [comment]
Hi  @ASHR4 thanks for opening this issue. Per the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group#security_rule), we have to explicitly set it to empty slice ([]) to remove it. Could you try removing it by setting `security_rule = []`?
