### ISSUE TITLE
Support for newly introduced planned maintenance configuration types for AKS cluster upgrades

### ISSUE THREAD

**Issue by BenjaminHerbert** [hashicorp/terraform-provider-azurerm#21722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The maintenance window that can be specified for an AKS cluster [has introduced _types_](https://learn.microsoft.com/en-us/azure/aks/planned-maintenance#creating-a-maintenance-window):

> There are currently three available configuration types: **default**, **aksManagedAutoUpgradeSchedule**, **aksManagedNodeOSUpgradeSchedule**:

> **default** corresponds to a basic configuration that will update your control plane and your kube-system pods on a Virtual Machine Scale Sets instance. It's a legacy configuration that is mostly suitable for basic scheduling of [weekly releases](https://learn.microsoft.com/en-us/azure/aks/release-tracker).
> 
> **aksManagedAutoUpgradeSchedule** controls when cluster upgrades scheduled by your designated auto-upgrade channel are performed. More finely controlled cadence and recurrence settings are possible than in a default configuration. For more information on cluster auto-upgrade, see [Automatically upgrade an Azure Kubernetes Service (AKS) cluster](https://learn.microsoft.com/en-us/azure/aks/upgrade-cluster).
> 
> **aksManagedNodeOSUpgradeSchedule** controls when node operating system upgrades scheduled by your node OS auto-upgrade channel are performed. More finely controlled cadence and recurrence settings are possible than in a `default configuration. For more information on node OS auto-upgrade, see [Automatically patch and update AKS cluster node images](https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-node-image)

Currently, the provider does only allow to specify the `default` type via [maintenance_window](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#maintenance_window) on the `azurerm_kubernetes_cluster` resource.

It would be nice, if all types could be specified.

They recommend different config types for different types of cluster upgrades. 

> We recommend using aksManagedAutoUpgradeSchedule for all cluster upgrade scenarios and aksManagedNodeOSUpgradeSchedule for all node image upgrade scenarios, while default is meant exclusively for weekly releases. You can port default configurations to aksManagedAutoUpgradeSchedule configurations via the az aks maintenanceconfiguration update command.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### References

- https://learn.microsoft.com/en-us/azure/aks/planned-maintenance#creating-a-maintenance-window

**Comment by aristosvo** [comment]
Thanks for this request!

@stephybun Do you prefer 2 new blocks or should we add a type to the block 'maintenance_window'?

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  ...
  // option 1:
  maintenance_window {
    type = "default"
    ...
  }
  
  // option 2:
  // default
  maintenance_window {
    ...
  }

  // autoUpgrade
  maintenance_window_auto_upgrade {
    ...
  }
  // default
  maintenance_window_node_os {
    ...
  }
  
}
```

**Comment by EppO** [comment]
I would go with option 1 because you still can have multiple "maintenance_window" with different configuration types

**Comment by aristosvo** [comment]
@EppO Thanks! I've started with the implementation because this usually helps a bit in these kind of decision processes.

The `default` maintenance window type (the "legacy" type, according to the docs) has a different model compared to the other two types. Supporting these 2 different models in one block type is a bit messy from a user perspective, as we cannot validate it as extensively as when we differentiate (option 2).

This means that I've chosen option 2 for now 🙈

**Comment by EppO** [comment]
If they are actually using different parameters, it makes sense indeed. Thanks for implementing this, really appreciated.

**Comment by aristosvo** [comment]
@EppO Do you have an opinion on this one: 

### Frequency schedules as separate blocks vs flat structure

```hcl
resource "azurerm_kubernetes_cluster" "test" {
  ...
  // option 1 (implemented)
  maintenance_window_node_os {
    frequency    = "AbsoluteMonthly" // multiple frequencies possible, the 4 shown in option 2 with their parameters
    day_of_month = 5
    interval     = 1
    

    duration   = 9
    start_time = "07:00"
    utc_offset = "+01:00"
    start_date = "2023-11-26T00:00:00Z"

    not_allowed {
      end   = "2023-11-30T00:00:00Z"
      start = "2023-11-26T00:00:00Z"
    }
  }

  // option 2  (more like `azurerm_monitor_alert_processing_rule_suppression`)
  maintenance_window_node_os {
    // frequency options, only 1 allowed at a time
    daily {
      interval = 1
    }
    weekly {
      interval    = 1
      day_of_week = "Monday"
    }
    relative_monthly {
      interval    = 1    
      day_of_week = "Monday"
      week_index  = "First"
    }
    absolute_monthly {
      interval     = 1
      day_of_month = 5
    }

    duration   = 9
    start_time = "07:00"
    utc_offset = "+01:00"
    start_date = "2023-11-26T00:00:00Z"

    not_allowed {
      end   = "2023-11-30T00:00:00Z"
      start = "2023-11-26T00:00:00Z"
    }
  }
}
```
I feel a bit more attracted to option 2, as this makes validation of the interval per frequency type better and gives more overview.

**Comment by EppO** [comment]
How would you set a schedule from Monday to Friday at nights (no weekends) using both options?

**Comment by aristosvo** [comment]
Don't know! I'll try multiple weekly blocks, but as far as I can interpret the docs it seems that it is not possible

**Comment by siegenthalerroger** [comment]
Thanks for the work on this. Might I suggest a different naming for the new blocks to better align with MS' naming. 

`maintenance_window_node_os` in MS jargon is `aksManagedNodeOSUpgradeSchedule`, and similar `...AutoUpgradeSchedule` for the k8s version upgrades. 

I've tried to align the naming with the existing parameters a bit, my suggestion would be
```
resource "azurerm_kubernetes_cluster" "test" {
  ...
  
  // default / AKS weekly releases
  maintenance_window {
    ...
  }

  // autoUpgrade
  auto_upgrade_schedule {
    ...
  }
  kubernetes_version = "1.24"
  automatic_channel_upgrade = "patch"

  // nodeOS patching
  node_os_upgrade_schedule {
    ...
  }
  default_node_pool {
    ...
    os_disk_size_gb = 30
    os_disk_type = "Managed"
    os_sku = "CBLMariner"
}
```

On a sidenote of the questions above, I prefer option 2 in both cases.

**Comment by siegenthalerroger** [comment]
@BenjaminHerbert That's the naming for the upgrade _channels_ not the respective _schedule_. I think that the upgrade channel types aren't implemented in the terraform provider yet either, so maybe it makes sense to consider them aswell when it comes to naming/layout.

**Comment by cailyoung** [comment]
👋 Azure will deprecate the default behaviour on 15 July, is the linked PR here going to be merged and released before then?

**Comment by aristosvo** [comment]
Hi @cailyoung! I added the docs to the PR, it now will depend on review.

Can you point me towards the announcement which backs up the deprecation claim?

**Comment by cmergenthaler** [comment]
> Hi @cailyoung! I added the docs to the PR, it now will depend on review.
> 
> Can you point me towards the announcement which backs up the deprecation claim?

There isn't an announcement somewhere available. We've got a notice because we are using the "default" maintenance configuration:

> Previously the maintenance [ configuration|https://learn.microsoft.com/azure/aks/planned-maintenance] ’default’ included both scheduling Auto upgrades and Node OS Patching. This will longer be the case starting as early as 15 July 2023. 
> 
> After 15 July 2023, the ‘default’ maintenance configuration will only work for controlling the AKS weekly releases. Any existing maintenance configurations set to ‘default’ will no longer work for controlling auto-upgrade or node OS patching.

**Comment by rouke-broersma** [comment]
> How would you set a schedule from Monday to Friday at nights (no weekends) using both options?

Simply no longer possible.. The closest is the 'pre-created' maintenance window weekday: https://learn.microsoft.com/en-us/azure/aks/aks-planned-maintenance-weekly-releases

**Comment by serbezki** [comment]
Is there some implicit initialization of start time for the maintenance? It seems like it, as I have not specified that, but at the same time I'm getting the following error when trying to apply:
Error: creating/updating Auto Upgrade Schedule Maintenance Configuration for Kubernetes Cluster
maintenanceconfigurations.MaintenanceConfigurationsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidParameter" Message="The input 'maintenanceWindow.startDate' 2023-07-06 00:00:00 +0000 cxTimeZone is before the current time 2023-07-10 06:50:45.111250283 +0000 UTC m=+233282.330901912."

**Comment by aristosvo** [comment]
> Is there some implicit initialization of start time for the maintenance?

No, not at the Terraform provider side. It is probably an error at Azure side of things!
