### ISSUE TITLE
Cannot create azurerm_storage_data_lake_gen2_filesystem in AzureChinaCloud

### ISSUE THREAD

**Issue by superkartoffel** [hashicorp/terraform-provider-azurerm#21741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem

### Terraform Configuration Files

```hcl
locals {
  service_location = "chinaeast2"
  service_storage_container_name_v1="testcontainer"
}

resource "azurerm_resource_group" "service-resourcegroup" {
  name = "TEST-RG"
  location = local.service_location
}

resource "azurerm_storage_account" "storage_account" {
  name = "storageaccounttest00001"
  resource_group_name = azurerm_resource_group.service-resourcegroup.name
  location = local.service_location
  account_kind = "StorageV2"
  account_tier = "Standard"
  access_tier = "Hot"
  allow_nested_items_to_be_public = false
  enable_https_traffic_only = true
  account_replication_type = "LRS"
  is_hns_enabled = "true"
}

resource "azurerm_storage_data_lake_gen2_filesystem" "data_lake_filesystem" {
  name = local.service_storage_container_name_v1
  storage_account_id = azurerm_storage_account.storage_account.id
}

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.55.0"
    }
  }
}

provider "azurerm" {
  features {}
}

terraform {
  required_version = "=1.4.4"
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/superkartoffel/26dd70f4fccb8728807ebdfbd033ff0f
```

### Expected Behaviour

It should create a resource-group, storage account and a container.

### Actual Behaviour

After 7m30s elapsed, the apply steps fails with an errors message:
```
╷
│ Error: checking for existence of existing File System "testcontainer" (Account "storageaccounttest00001"): autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: clientCredentialsToken: received HTTP status 400 with response: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://core.chinacloudapi.cn was not found in the tenant named 必达（天津）家畜饲养设备有限公司. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: d3d17978-a219-41af-a257-c46281a81f00\r\nCorrelation ID: 94deacab-32ae-4c87-9e43-fa9cd3351ecf\r\nTimestamp: 2023-05-10 11:40:31Z","error_codes":[500011],"timestamp":"2023-05-10 11:40:31Z","trace_id":"d3d17978-a219-41af-a257-c46281a81f00","correlation_id":"94deacab-32ae-4c87-9e43-fa9cd3351ecf","error_uri":"https://login.chinacloudapi.cn/error?code=500011"}
│ 
│   with azurerm_storage_data_lake_gen2_filesystem.data_lake_filesystem,
│   on blob.tf line 24, in resource "azurerm_storage_data_lake_gen2_filesystem" "data_lake_filesystem":
│   24: resource "azurerm_storage_data_lake_gen2_filesystem" "data_lake_filesystem" {
│ 
╵
```

It looks like the request to the token endpoint fails because the resource is not correct. It uses resource=https://core.chinacloudapi.cn/ instead of resource=https://storageaccounttest00001.dfs.core.chinacloudapi.cn/

I can reproduce the exact error message with a curl request like this:
`curl -X POST "https://login.chinacloudapi.cn/<tenant-id>/oauth2/token" -d "client_id=...&client_secret=...&resource=https://core.chinacloudapi.cn/&api-version=2018-02-01&grant_type=client_credentials" -H "content-type: application/x-www-form-urlencoded"`

### Steps to Reproduce

```
export ARM_CLIENT_ID="..."
export ARM_CLIENT_SECRET="..."
export ARM_TENANT_ID="..."
export ARM_SUBSCRIPTION_ID="..."
export ARM_ENVIRONMENT=china
terraform init
terraform validate
terraform plan -out=tfplan
terraform apply
```

### Important Factoids

Running in Azure China!

**Comment by superkartoffel** [comment]
By the way, I tried the same in AzurePublicCloud and it works as expected.

**Comment by czuser129** [comment]
@superkartoffel had the same issue with new terraform Provider today. Although it's working for old one i.e. 3.40.

**Comment by binpanoutlook** [comment]
Had the same issue. Also tried to create the filesystem via the az cli command, it works.

**Comment by binpanoutlook** [comment]
The issue has been resolved on the new version: https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.85.0

**Comment by superkartoffel** [comment]
Can confirm that it has been fixed.
