### ISSUE TITLE
azurerm_storage_account customer_managed_key returns NIL for KeyVault ID in another subscription

### ISSUE THREAD

**Issue by MattoHopkins** [hashicorp/terraform-provider-azurerm#21748]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.2

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_key" "data_key" {
  provider     = azurerm.other_sub
  name         = "data-key"
  key_vault_id = module.key_vault[0].key_vault.id
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = module.platform_resource_group.resource_group.name
  location                 = module.platform_resource_group.resource_group.location
  account_tier             = "Standard"
  account_replication_type = "GRS"
  identity {
    type = "UserAssigned"
  }

  customer_managed_key {
    key_vault_key_id = data.azurerm_key_vault_key.data_key.id #KV in another sub
    user_assigned_identity_id = azurerm_user_assigned_identity.user_identity.id #UAI in current sub where trying to create SA
  }
  tags = {
    environment = "staging"
  }
}
```

### Debug Output/Panic Output

```shell
2023-05-10T21:15:16.711Z [ERROR] provider.terraform-provider-azurerm_v3.55.0_x5: Response contains error diagnostic: @module=sdk.proto diagnostic_severity=ERROR tf_req_id=f1af0b44-1eee-ec04-861f-a2f8c65fb9f6 tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= diagnostic_summary="unexpected nil Key Vault ID retrieved at URL https://<keyvault_name>.vault.azure.net/" tf_proto_version=5.3 tf_provider_addr=provider tf_resource_type=azurerm_storage_account timestamp=2023-05-10T21:15:16.707Z
2023-05-10T21:15:16.712Z [ERROR] vertex "azurerm_storage_account.example" error: unexpected nil Key Vault ID retrieved at URL https://<keyvault_name>.vault.azure.net/
╷
│ Error: unexpected nil Key Vault ID retrieved at URL https://<keyvault_name>.vault.azure.net/
│ 
│   with azurerm_storage_account.example,
│   on uai-example-sa.tf line 19, in resource "azurerm_storage_account" "example":
│   19: resource "azurerm_storage_account" "example" {
│ 
╵
```

### Expected Behaviour

Storage Account is created with reference to KeyVault ID in another subscription

### Actual Behaviour

KeyVault ID from another subscription is returning NIL

### Steps to Reproduce

create storage account with customer_managed_key block referencing KeyVault in another subscription. This uses the User Assigned Identity with a Key in another subscription

and 

tf apply

**Comment by MattoHopkins** [comment]
Doing some more digging here as well - https://github.com/hashicorp/terraform-provider-azurerm/blob/94bbd836a9c931dfc6cd3285f51e8beb9e305058/internal/services/storage/storage_account_resource.go#L2350

Seems like I'm hitting this error around the parsing of the URL. Even after hardcoding the keyvault ID to mirror whats in portal, still no luck.

I have succesfully provisioned this via the azapi with the following code block:

```resource "azapi_resource" "example" {
  type      = "Microsoft.Storage/storageAccounts@2022-09-01"
  name      = "sauainame"
  parent_id = module.platform_resource_group.resource_group.id


  location = module.platform_resource_group.resource_group.location
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.user_identity[0].id]
  }
  body = jsonencode({
    properties = {
      encryption = {
        keySource = "Microsoft.KeyVault"
        keyvaultproperties = {
          keyname = "data-key"
          keyvaulturi = module.key_vault[0].key_vault.vault_uri
        }
        identity = {
          userAssignedIdentity = azurerm_user_assigned_identity.user_identity[0].id
        }
      }
    }
    sku = {
      name = "Standard_GRS"
    }
    kind = "StorageV2"
  })
}```

**Comment by MattoHopkins** [comment]
i can confirm the base vault_uris are the same between azapi resource creation and the terraform azurerm_storage_account data_key id. Parsing the URL seems to be fine as well... Seems like its breaking during this function call https://github.com/hashicorp/terraform-provider-azurerm/blob/94bbd836a9c931dfc6cd3285f51e8beb9e305058/internal/services/storage/storage_account_resource.go#LL2345C39-L2345C60

**Comment by MattoHopkins** [comment]
Digging a step further... 

https://github.com/hashicorp/terraform-provider-azurerm/blob/94bbd836a9c931dfc6cd3285f51e8beb9e305058/internal/services/keyvault/client/helpers.go#L111

I think this looks for resources within a specific sub based off the client subscription: https://github.com/hashicorp/terraform-provider-azurerm/blob/94bbd836a9c931dfc6cd3285f51e8beb9e305058/internal/services/resource/client/client.go#L46

**Comment by magodo** [comment]
@MattoHopkins Thanks for openning this and sorry for the limitation. This duplicates to #20199. Please subscribe that for any progress.
