### ISSUE TITLE
azurerm_vpn_gateway - Unsupported argument "bgp_settings"

### ISSUE THREAD

**Issue by ferserrano-contino** [hashicorp/terraform-provider-azurerm#21765]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_vpn_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_wan" "example" {
  name                = "example-vwan"
  resource_group_name = "testrg"
  location            = "westeurope"
}

resource "azurerm_virtual_hub" "example" {
  name                = "example-hub"
  resource_group_name = "testrg"
  location            = "westeurope"
  virtual_wan_id      = azurerm_virtual_wan.example.id
  address_prefix      = "10.0.1.0/24"
}

resource "azurerm_vpn_gateway" "vpn_gw" {
  name                                  = "example-vpn"
  resource_group_name                   = "testrg"
  location                              = "westeurope"
  virtual_hub_id                        = azurerm_virtual_hub.example.id
  bgp_route_translation_for_nat_enabled = true
  scale_unit                            = "2"

  bgp_settings = {
    asn         = "64512"
    peer_weight = "50"
    }
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported argument
│ 
│   on vpngateway.tf line 30, in resource "azurerm_vpn_gateway" "vpn_gw":
│   30:   bgp_settings = {
│ 
│ An argument named "bgp_settings" is not expected here. Did you mean to define a block of type "bgp_settings"?
```

### Expected Behaviour

Complete terraform plan successfully

### Actual Behaviour

terraform plan failed with the "Unsupported argument" error

### Steps to Reproduce

Just a simple terraform plan to validate the creation of the resources listed on configuration files section

### Important Factoids

No

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_gateway#bgp_settings

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems the tf config you provided is incorrect. Please try below tf config. Thanks.

```
resource "azurerm_vpn_gateway" "test" {
  ......

  bgp_settings {
    asn         = 65515
    peer_weight = 0
  }
}
```
