### ISSUE TITLE
Support for azurerm_container_app -- when trying to create it from an image in azure container registry using username, password_secret_name

### ISSUE THREAD

**Issue by asarma2307** [hashicorp/terraform-provider-azurerm#21766]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

variable "namespace" {
  default = "user1"
}

variable "cpu" {
  default = 0.25
}

variable "image" {
  default = "mycontainerregistry.azurecr.io/myrepo:latest"
}

variable "memory" {
  default = "0.5Gi"
}

variable "revision_mode" {
  default = "Single"
}

variable "location" {
  default = "eastus2"
}

variable "tags" {
  default = {
    "ASKID"            = "xxx"
    "AssignmentGroup"  = "xxx"
    "GLCode"           = "xxx"
    "Division"         = "xxx"
    "Portfolio"        = "xxx"
    "Product"          = "xxx"
    "Component"        = "xxx" 
    "ComponentVersion" = "xxx"
    "Environment"      = "xxx"
  }
}

data "azurerm_container_registry" "cr" {
  name = "mycontainerregistry"
  resource_group_name = "myacrrg"
}

locals {
  registry = {
    server   = "mycontainerregistry.azurecr.io"
    password_secret_name = data.azurerm_container_registry.cr.admin_password
    username = data.azurerm_container_registry.cr.admin_username
  }
}

resource "azurerm_resource_group" "my_rg" {
  name     = format("my-container-app-default-rg-%s", var.namespace)
  location = var.location
  tags     = var.tags
}

module "my_log" {
  source              = "git::https://xxx"
  name                = "my-log"
  namespace           = var.namespace
  resource_group_name = azurerm_resource_group.my_rg.name
  location            = azurerm_resource_group.my_rg.location
  tags                = var.tags

  retention_in_days = 30
  sku               = "PerGB2018"
}

module "my_cae" {
  source              = "../../../profiles/container-app-environment"
  name                = "my-default-cae"
  namespace           = var.namespace
  resource_group_name = azurerm_resource_group.my_rg.name
  location            = azurerm_resource_group.my_rg.location
  tags                = var.tags

  log_analytics_workspace_id = module.my_log.id
}

module "my_ca" {
  source              = "../../../profiles/container-app"
  name                = "my-default-ca"
  namespace           = var.namespace
  resource_group_name = azurerm_resource_group.my_rg.name
  tags                = var.tags

  container_app_environment_id = module.my_cae.id
  registry                     = local.registry
  revision_mode                = var.revision_mode

  template = {
    containers = [{
      name   = format("my-default-ca-%s", var.namespace)
      cpu    = var.cpu
      image  = var.image
      memory = var.memory
    }]
  }
}

```

### Debug Output/Panic Output

```shell
Error: creating Container App (Subscription: "xxx"
│ Resource Group Name: "xxxxx"
│ Container App Name: "xxxx"): performing CreateOrUpdate: containerapps.ContainerAppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="ContainerAppRegistriesPasswordSecretRefNotFound" Message="PasswordSecretRef 'xxx' defined for registry server 'xxxxxx.azurecr.io' not found."
│
│   with module.xxxx,
│   on ..\..\..\_modules\container-app\main.tf line 19, in resource "azurerm_container_app" "ca":
│   19: resource "azurerm_container_app" "ca" {
│
│ creating Container App (Subscription: "xxx"
│ Resource Group Name: "xxxx"
│ Container App Name: "xxxx"): performing CreateOrUpdate: containerapps.ContainerAppsClient#CreateOrUpdate: Failure     
│ sending request: StatusCode=0 -- Original Error: Code="ContainerAppRegistriesPasswordSecretRefNotFound" Message="PasswordSecretRef       
│ 'xxx' defined for registry server 'xxxxx.azurecr.io' not found."


```

### Expected Behaviour

Container app with given image should be created successfully. 

### Actual Behaviour

1. Creation of container app is failing when using an image from a registry with username, password_secret_name.
2. When identity = "system" in the registry block, the creation still fails. There is an open issue for this (https://github.com/hashicorp/terraform-provider-azurerm/issues/21242)
3. When creating the container app with the same image and registry from the portal, the creation is successfully completed. 
4. Public access to the container registry as well as admin username is enabled. 
5. The container app is not behind any vnet. 

### Steps to Reproduce

1. terraform apply

**Comment by vbakshi123** [comment]
Any updates on this ?

**Comment by sandeep-tembare-ceataec** [comment]
You need to create "secret" and use "secret name" as reference

```hcl
resource "azurerm_container_app" "application" {
  ...
  secret {
    name  = "registry-credentials"
    value = azurerm_container_registry.container-registry.admin_password
  }

  registry {
    server               = azurerm_container_registry.container-registry.login_server
    username             = azurerm_container_registry.container-registry.admin_username
    password_secret_name = "registry-credentials" # secret mentioned in above block
  }
  ...
}
```

Reference: [NubesGen-2](https://github.com/jdubois/NubesGen-2/tree/main)/[terraform](https://github.com/jdubois/NubesGen-2/tree/main/terraform)/[modules](https://github.com/jdubois/NubesGen-2/tree/main/terraform/modules)/[container-apps](https://github.com/jdubois/NubesGen-2/tree/main/terraform/modules/container-apps)/[main.tf](https://github.com/jdubois/NubesGen-2/blob/main/terraform/modules/container-apps/main.tf)

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @sandeep-tembare-ceataec‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
