### ISSUE TITLE
New resource/request: Set 'Automation Runbook' as action type for new 'azurerm_monitor_action_group'

### ISSUE THREAD

**Issue by danielfears** [hashicorp/terraform-provider-azurerm#2177]
When creating resource azurerm_monitor_action_group there is currently no argument for setting the action type to use a predefined Automation Runbook.

Requesting that functionality be added to allow the following arguments to be set for azurerm_monitor_action_group so that we can automate triggering runbooks from an alert action group:

- Action name: anything
- Action type: Automation Runbook
- Configure runbook:
  - Run runbook: enabled / disabled
  - Runbook source: User
    - Subscription
    - Automation account
    - Runbook
  - Runbook source: Built-in
    - Runbook

Thanks in advance.

**Comment by tombuildsstuff** [comment]
hi @danielfears 

Thanks for opening this issue :)

So that we could take a look into how we'd support this - is there a documentation link / ARM Template you're using for this at the moment?

Thanks!

**Comment by danielfears** [comment]
Hi @tombuildsstuff 

Unfortunately not, we've been implementing this manually. Ideally this is something we would need to be able to do via Terraform eventually :)

I assume Microsoft don't have an API for this, having looked at the documentation I cannot find anything (https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-create-action-group-with-resource-manager-template) but please correct me if I'm wrong!

If so, could it be fed back to Microsoft in the hopes they expose an API that Terraform could use? We have a Terraform Enterprise license and are looking to take full advantage of that :)

All the best!

**Comment by liemnotliam** [comment]
The SDK does support automation runbook receivers for action groups https://godoc.org/github.com/Azure/azure-sdk-for-go/services/preview/monitor/mgmt/2018-03-01/insights#ActionGroup

**Comment by catriona-m** [comment]
It looks like this question has been answered above so I'll close this now but please feel free to reopen if that is not the case. Thanks!
