### ISSUE TITLE
admin_password is not an optional attibute in property "windows_profile" of "kubernetes_cluster"

### ISSUE THREAD

**Issue by schmidt-i** [hashicorp/terraform-provider-azurerm#21773]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.56

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }

  windows_profile =  {
      admin_username = "admin"
      license        = "Windows_Server"
  }
}
```

### Debug Output/Panic Output

```shell
Managed Cluster Name: "example"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The value of parameter windowsProfile.adminPassword is invalid. Please see https://aka.ms/aks-naming-rules for more details." Target="windowsProfile.adminPassword"
```

### Expected Behaviour

A new Kubernetes cluster should be created with a random unknown admin password, since the property is not set and optional.

### Actual Behaviour

Cluster creation failed with an error message: 

Managed Cluster Name: "example"): managedclusters.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameter" Message="The value of parameter windowsProfile.adminPassword is invalid. Please see https://aka.ms/aks-naming-rules for more details." Target="windowsProfile.adminPassword"

### Steps to Reproduce

terraform apply

**Comment by stephybun** [comment]
Thanks for raising this issue @schmidt-i.

Whilst I can see that in the msft docs there is the option to omit the credentials on the azure CLI, it looks like the CLI is generating those credentials on behalf of the user and sending them to the API.

Based on the error message that's returned as well as after looking into the behaviour of this property it appears that this is a limitation in the AKS API so this property should actually become `Required` in the next major version of the provider.
