### ISSUE TITLE
terraform.tfstate file is destroying the existing resource when I deploy a new resource

### ISSUE THREAD

**Issue by rakesh-vishwabrahmana** [hashicorp/terraform-provider-azurerm#21772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.4

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
# main.tf

terraform {
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
}

resource "azurerm_container_registry" "azcr" {
  name                = var.acrname
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  sku                 = "Standard"

  identity {
    type = "SystemAssigned"
  }
}

# outputs.tf

output "login_server" {
  value = "${azurerm_container_registry.azcr.login_server}"
}

# variables.tf
variable "resource_group_name" {
  type = string
  description = "Resourcegroup name"
  default = "Dev"
}

variable "acrname" {
  type = string
  description = "Azure container registry name"
  default = "dev01"
}
```

### Debug Output/Panic Output

```shell
I can see In DevOps pipeline, 

azurerm_container_registry.azcr will be destroyed
   (because azurerm_container_registry.azcr is not in configuration)
```

### Expected Behaviour

It should create a new resource in azure and update the tfstate file. 

### Actual Behaviour

If Ideploy any resource in Azure using terraform from Azure DevOps pipeline, it's destroying the existing resource just because of adding the backup block in terraform code. It's working fine when I run from VS Code. 

Currently, commented out the terraform backup block and deploying the resources. So the terraform.tfstate file is not updating at the moment.

### Steps to Reproduce

`DevOpspipeline.yaml`

trigger:
`- none`

pool:
  vmImage: ubuntu-latest

steps:
`- task: TerraformInstaller@0`
  inputs:
    terraformVersion: 'latest'
`- task: TerraformTaskV3@3`
  displayName: Terraform Init
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/acr'
    backendServiceArm: 'Dev(Service Principal (automatic))'
    backendAzureRmResourceGroupName: 'Dev'
    backendAzureRmStorageAccountName: 'dev'
    backendAzureRmContainerName: 'terraform'
    backendAzureRmKey: 'tf/terraform.tfstate'

`- task: TerraformTaskV3@3`
  displayName: Terraform Plan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/acr'
    commandOptions: '-out=tfplan'
    environmentServiceNameAzureRM: 'Dev(Service Principal (automatic))'

`- task: TerraformTaskV3@3`
  displayName: Terraform Apply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/development/acr'
    environmentServiceNameAzureRM: 'Dev(Service Principal (automatic))'

**Comment by ziyeqf** [comment]
Hi @rakesh-vishwabrahmana, thanks for opening the issue.

I may did not understand about `backup block`, could you please provide some more details?

Thanks!

**Comment by ziyeqf** [comment]
Hi @rakesh-vishwabrahmana , thanks for the updating. 

To use multiple Terraform configs please use different `.tfsate` files. One config, one `.tfstate`. It saves the mapping between real world resources and your configs. More details could be found [here](https://developer.hashicorp.com/terraform/language/state)

For the question about "creating same resource", you will need compose two container registries in the same config, or it will destroy the old one because the old one does not exist in your config file.

For any further questions please leave comments.
Thanks.

**Comment by rakesh-vishwabrahmana** [comment]
Hi @ziyeqf, many thanks for the update. 

I will check and deploy as per your advise and let you know if that works for me. 

Thanks

**Comment by rakesh-vishwabrahmana** [comment]
Hi @ziyeqf, thanks for the information. 

Could you please share if you have any spec doc for composing two container registries in the same config. I just tried some example, but it didn't work. 

Thanks

**Comment by rakesh-vishwabrahmana** [comment]
Hi @ziyeqf, 

I have composed the existing container registry and created a new container registry in the same config as advised. It's working as expected. 

Thanks

Here is the code, please confirm once. 

`main.tf`

terraform {
  backend "azurerm" {}
}

provider "azurerm" {
  features {}
}

data "azurerm_resource_group" "rg" {
  name     = var.resource_group_name
}

resource "azurerm_container_registry" "azcrold" {
  name                = var.acrnameold
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  sku                 = "Standard"
 }

resource "azurerm_container_registry" "azcrnew" {
  name                = var.acrnamenew
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location
  sku                 = "Standard"
 }

`outputs.tf`

output "login_server" {
  value = "${azurerm_container_registry.azcrnew.login_server}"
}

`variables.tf`

variable "resource_group_name" {
  type = string
  description = "Resourcegroup name"
  default = "Dev"
}

variable "acrnameold" {
  type = string
  description = "Azure container registry name"
  default = "dev01"
}

variable "acrnamenew" {
  type = string
  description = "Azure container registry name"
  default = "dev02"
}
