### ISSUE TITLE
azurerm_container_app  Support for ingress IpSecurityRestrictionRule setting  

### ISSUE THREAD

**Issue by skykubashovo** [hashicorp/terraform-provider-azurerm#21774]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_container_app not support setting of IP Restrictions as per portal and Microsoft template documentation: https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-arm-template#ipsecurityrestrictionrule-1

Also and most important if IP Restrictions is configured from Azure portal, terraform remove already presented configuration.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

 ingress {
    external_enabled = true
    target_port      = 3978
    traffic_weight {
      latest_revision = true
      percentage      = 100
    }
    ip_security_restriction_rule {
      action = "Allow"
      ip_address_range = "1.1.1.1/32, 2.2.2.2/32"
    }
  }

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }
   
}

}
```

### References

Actually is not possible to set **IpSecurityRestrictionRule** with terraform provider. 

The option is documented here: 
https://learn.microsoft.com/en-us/azure/templates/microsoft.app/containerapps?pivots=deployment-language-arm-template#ipsecurityrestrictionrule-1

Also if you set ip restriction from portal and deploy new container app version, terraform delete the configuration setted from portal.

**Comment by JeremyKeusters** [comment]
Would indeed be very useful to have this in Terraform. To make it more clear, I've attached a screenshot of the functionality in the Azure portal:

![Screenshot 2023-07-12 at 15 48 59](https://github.com/hashicorp/terraform-provider-azurerm/assets/4648081/6e46e195-9e1e-49cd-bf47-acc394c8e45f)
