### ISSUE TITLE
Azure databricks provisioned in failed state using terraform azurerm provider. ["Provisioning State"= "Failed"]

### ISSUE THREAD

**Issue by hasanm64** [hashicorp/terraform-provider-azurerm#21797]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.0

### AzureRM Provider Version

2.70

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "databricks_PoC" {
  name                = var.DATABRICKS_PoC
  resource_group_name = var.MAIN_RESOURCE_GROUP_NAME_APP
  location            = var.LOCATION
  sku                 = "standard"
  tags = local.common_tags
}
```

### Debug Output/Panic Output

```shell
No error found in the logs.
Terraform apply completed successfully but databricks workspace got created in failed state.
```

### Expected Behaviour

It should create a azure databricks workspace with given configuration successfully in "Active" state.

### Actual Behaviour

The databricks workspace was created in failed state instead of active state after provisioning via terraform.
But when we include the optional property "managed_resource_group_name = "databricks-rg-xxxx-rg"" in the code block, that too with a unique name of the managed resource group which doesnot exist, it is creating the databricks workspace successfully in Active state.
In the activity logs of azure databricks workspace, I see there is change in property.
"Provisioning State" = "Accepted" to "Provisioning State" = "Failed"

How come adding a optional property is solving the issue??
Why is terraform creating workspace in failed state when "managed_resource_group_name" is not added??
Why is terraform changing the property "Provisioning State" post creation??

**Comment by rcskosir** [comment]
@hasanm64 Thank you for opening this issue. 
You have listed the AzureRM provider version that you are using as 2.70. 
We don't support older versions of the provider, like 2.70. 
Please update to the new provider version and update this issue with the new provider version if this issue is still occurring.
You can check the latest version at this link: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs
As of my comment, it is 3.57.0.

Thanks again,
Renae

**Comment by rcskosir** [comment]
Thanks again for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
