### ISSUE TITLE
azurerm_api_management_api validation restricts : character in path

### ISSUE THREAD

**Issue by madhoun** [hashicorp/terraform-provider-azurerm#21807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.19.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "test_api" {
  name                = "MyAPITest"
  resource_group_name = "MyRG"
  api_management_name = "MyAPIM"

  revision     = "1"
  display_name = "MyAPITest"
  path         = "services/ab:outbound-test"
  protocols    = ["https"]
  soap_pass_through = "true"
  subscription_required = "false"

  import {
    content_format = "wsdl"
    content_value  = file(local.api_outbound_wsdl)

    wsdl_selector {
        service_name = "OutboundService"
        endpoint_name = "outbound-test"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: "path" may only be up to 400 characters in length, not start or end with `/` and only contain valid url characters
```

### Expected Behaviour

Deploy API similar to what can be done from portal.  Example of template of api deployed from Azure Portal:

"type": "Microsoft.ApiManagement/service/apis",
            "apiVersion": "2022-09-01-preview",
            "name": "[concat(parameters('service_test'), '/outboundservice')]",
            "dependsOn": [
                "[resourceId('Microsoft.ApiManagement/service', parameters('service_test'))]"
           ],
            "properties": {
                "displayName": "MyAPITest",
                "apiRevision": "1",
                "subscriptionRequired": true,
                "serviceUrl": https://mytesturl.local.com/services/ab:outbound-test,
                **"path": "services/ab:outbound-test",**
                "protocols": [
                    "https"
                ],
                "authenticationSettings": {
                    "oAuth2AuthenticationSettings": [],
                    "openidAuthenticationSettings": []
                },
                "subscriptionKeyParameterNames": {
                    "header": "Ocp-Apim-Subscription-Key",
                    "query": "subscription-key"
                },
                "type": "soap",
                "isCurrent": true
            }

### Actual Behaviour

Error: "path" may only be up to 400 characters in length, not start or end with `/` and only contain valid url characters

### Steps to Reproduce

Error occurs on the terraform validate.   Seems the regex needs to be updated to be less restrictive and allow semicolon, issue similar to this: https://github.com/hashicorp/terraform-provider-azurerm/pull/7478

**Comment by madhoun** [comment]
I will submit a PR that fixes the APIM API path validation to allow colon character in the path.

**Comment by sinbai** [comment]
Hi @madhoun, After verifing the Azure API and Azure Portal, `services/ab:outbound-test` should indeed be allowed by Terraform. Thanks for opening this issue and submitting that PR to fix it.
