### ISSUE TITLE
web_app_* auto_heal_setting multiple triggers are modified every run

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#21823]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app, and likely other app service related resources

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "web_app" {
  <required minimum configuration>
  auto_heal_enabled = true
  auto_heal_setting {
    action {
      action_type = "Recycle"
    }
    trigger {
      status_code {
        count = 4
        interval = "00:10:00"
        status_code_range = "403"
      }
      status_code {
        count = 4
        interval = "00:20:00"
        status_code_range = "500-599"
      }
    }
  }
}
```

### Debug Output/Panic Output

```hcl
~ auto_heal_setting {

              ~ trigger {
                    # (1 unchanged attribute hidden)

                  ~ status_code {
                      ~ interval          = "00:20:00" -> "00:10:00"
                      ~ status_code_range = "403" -> "500-599"
                        # (3 unchanged attributes hidden)
                    }
                  ~ status_code {
                      ~ interval          = "00:10:00" -> "00:20:00"
                      ~ status_code_range = "500-599" -> "403"
                        # (3 unchanged attributes hidden)
                    }
                }
```

### Expected Behaviour

The configuration is unchanged, so the plan should have shown no changes.

### Actual Behaviour

Plan shows each status_code setting is updated with the settings of the other one on every run

**Comment by xiaxyi** [comment]
Thanks @calebak404 for raising this issue. Terraform defines the status code trigger as a list which means the order matters, however, seems API doesn't care about the order. 

Can I confirm with you to see if the status code trigger order matters (there will be priority when hitting the rule) in your actual practice?

thanks

**Comment by xiaxyi** [comment]
Thanks @calebak404 for raising this issue.

This is the order of the status code in flatten function, I will find a proper way to fix it.

**Comment by xiaxyi** [comment]
Hi @calebak404 , the fix to this issue is by spliting the auto_heal setting structure as mentioned in the linked PR. In 4.0 provider,  the auto heal status code trigger is defined as:
```
status_code {
          status_code = "503"
          interval          = "00:01:30"
          count             = 20
          path = "./terraformteststatusrange.aspx"
          win32_status = "30"
          sub_status = 202
        }

status_code_range {        
  status_code_range = "400-500"
 interval          = "00:01:30"
 count             = 20
}
```

**Comment by rcskosir** [comment]
@calebak404,
PR #21831 has been superseded by #22003, which has merged. Please upgrade to the latest provider (3.63) if you are able, to let us know if this has resolved your issue. 
Thank you

**Comment by calebak404** [comment]
This specific issue appears to be resolved
