### ISSUE TITLE
azurerm_consumption_budget_subscription deploys, but it does not trigger alerts

### ISSUE THREAD

**Issue by eric-mark** [hashicorp/terraform-provider-azurerm#21839]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_consumption_budget_subscription

### Terraform Configuration Files

```hcl
# manages our subscription consumption budget and alerting
# cost and usage data is typically available within 8-24 hours and budgets are evaluated against these costs every 24 hours
# when a budget threshold is met, email notifications are normally sent within an hour of the evaluation

resource "azurerm_consumption_budget_subscription" "monthly_budget_subscription" {
  name            = "${local.region_vars}-cost${var.env}-ntf"
  subscription_id = "/subscriptions/${var.az_subscription_id_map[var.env]}"
  amount          = var.subscription_budget[var.env]
  time_grain      = "Monthly"

  time_period {
    start_date = "2023-05-01T00:00:00Z" # Start date for monthly time grain should not be prior to current month.
    end_date   = "2030-01-01T00:00:00Z"
  }

  notification {
    enabled        = true
    threshold      = 50.0
    threshold_type = "Actual"
    operator       = "EqualTo"

    # contact_emails = [
    #   "eric-mark@xx-github-user-xx.com",
    # ]

    contact_groups = [
      "${local.contact_group_cyberengineering}",
    ]
  }

  notification {
    enabled        = true
    threshold      = 90.0
    threshold_type = "Actual"
    operator       = "EqualTo"

    # contact_emails = [
    #   "eric-mark@xx-github-user-xx.com",
    # ]

    contact_groups = [
      "${local.contact_group_cyberengineering}",
    ]
  }

  notification {
    enabled        = true
    threshold      = 95.0
    threshold_type = "Actual"
    operator       = "EqualTo"

    # contact_emails = [
    #   "eric-mark@xx-github-user-xx.com",
    # ]

    contact_groups = [
      "${local.contact_group_pagerduty}",
    ]
  }
}



locals {
  contact_group_cyberengineering = "/subscriptions/${var.az_subscription_id_map_uppercase[var.env]}/resourceGroups/${local.region_vars}-${var.prefix-actiongrp01}.rg/providers/microsoft.insights/actionGroups/${var.prefix-alertcyberengineering}"
}

locals {
  contact_group_pagerduty = "/subscriptions/${var.az_subscription_id_map_uppercase[var.env]}/resourceGroups/${local.region_vars}-${var.prefix-actiongrp01}.rg/providers/microsoft.insights/actionGroups/${var.prefix-alertpagerduty}"
}
```

### Debug Output/Panic Output

```shell
There is no issue with deployment.  We have deployed the same alert via terraform and manually.  If we deploy this manually, the alert will trigger.  If we deploy this via terraform, no alert will trigger.

We also have a msft support case open via TrackingID #2305160010002353
```

### Expected Behaviour

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/45639241/12d589b9-13ac-4b6f-85b7-a908deebfb5e)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/45639241/d56644a7-5aa0-4c2e-974d-566659ec7287)

Alerts should have triggered for the alerts deployed via Terraform.   The alerts trigger are the manual deployments, not the alerts deployed via Terraform.

### Actual Behaviour

Terraform deploys the alert with no issue.  However, no alerts are triggered.

### Steps to Reproduce

1. Create a budget alert via azurerm_consumption_budget_subscription
2. Configure action groups with or without emails
3. Trigger an alert

### Important Factoids

None

**Comment by eric-mark** [comment]
Update:  I recall why we deployed using a string variable:

contact_groups = [
      "${local.contact_group_cyberengineering}",
    ]

We ran into issue/bug where Azure was not accepting the subscription IDs in lower case.  We found a workaround using uppercase subscription IDs.  However, this might have been the issue.

I have deployed the code using

contact_groups = [
      azurerm_monitor_action_group.example.id,
    ]

And the deployment was successful.  We will report back within 48 hours with our results if this solution resolves our problem.

**Comment by eric-mark** [comment]
Re-test has been completed and no alerts have been triggered using action groups.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Could you compare the arm template of budget alert manually created with the arm template of budget alert created by Terraform via clicking "Export Template" on Azure Portal or invoking [rest api](https://learn.microsoft.com/en-us/rest/api/consumption/budgets/get?tabs=HTTP#code-try-0)?

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/1f28776e-6e89-4b2f-9570-efdbe5e67f57)

**Comment by eric-mark** [comment]
Hi @neil-yechenwei,

I don't see a method to export a budget from the portal.  However, i can use the data output feature within terraform to compare the differences for you later today.

**Comment by steph409** [comment]
Hi,
I just ran into a very similar issue. When creating a consumption budget using terraform, specifying an action group, the action group does not get assigned correctly (and I did not get alert notifications). When I specify the action group manually in the portal, and run `terraform plan` to see the diff, I remark the following:

in the terraform resource, the subscription_id in the contact groups is in all caps when created in the portal. When created using terraform, the subscription id is all small caps:

```hcl

      - notification { # forces replacement
          - contact_emails = [] -> null
          - contact_groups = [
              - "/subscriptions/8D75875A-331C-4AE2-8313-2E32507F60C1/resourceGroups/monitoring-resources/providers/microsoft.insights/actionGroups/subscription-owner-slcorp-management",
            ] -> ["/subscriptions/8d75875a-331c-4ae2-8313-2e32507f60c1/resourceGroups/monitoring-resources/providers/Microsoft.Insights/actionGroups/subscription-owner-slcorp-management"]
          - contact_roles  = [] -> null
          - enabled        = true -> null
          - operator       = "GreaterThan" -> null
          - threshold      = 80 -> null
          - threshold_type = "Actual" -> null
        }

```


not sure if this is related.

the terraform code is as follows:

```hcl



resource "azurerm_monitor_action_group" "notify_owner" {
  name                = "notify-me"
  resource_group_name = azurerm_resource_group.monitoring.name
  short_name = "sub-notify-me"
  email_receiver {
    name                    = "subscription-owner"
    email_address           = "foo@bar.com"
  }
}



resource "azurerm_consumption_budget_subscription" "budget" {
  name            = "subscription-budget-${data.azurerm_subscription.current.display_name}"
  subscription_id = data.azurerm_subscription.current.id
  amount     = 800
  time_grain = "Monthly"

  time_period {
    start_date = formatdate("2023-05-01'T'00:00:00Z", timestamp())
    end_date   = formatdate("2032-10-01'T'00:00:00Z", timestamp())
  }


  notification {
    enabled   = true
    threshold = 80.0
    operator  = "GreaterThan"
    contact_groups = [
      azurerm_monitor_action_group.notify_owner.id

    ]
  }
}

```

**Comment by eric-mark** [comment]
@steph409 and it triggered the alert and action group as well using all caps for the subscription?  I'll retest this again on my end with all caps, there must have been one character case off when i tried all caps.

**Comment by eric-mark** [comment]
@neil-yechenwei -- the only difference i am seeing with the tf output is the "end_date."  for the sake of testing, i'll edit the end_date to what the manual deployment auto configured.

Changes to Outputs:
  + manual = [
      + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/providers/Microsoft.Consumption/budgets/cdn-costnpd-ntf",
      + 300,
      + [],
      + [
          + {
              + contact_emails = []
              + contact_groups = [
                  + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/cdn-actiongrp01.rg/providers/Microsoft.Insights/actionGroups/AlertPagerDuty",
                ]
              + contact_roles  = []
              + enabled        = true
              + operator       = "EqualTo"
              + threshold      = 95
              + threshold_type = "Actual"
            },
          + {
              + contact_emails = []
              + contact_groups = [
                  + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/cdn-actiongrp01.rg/providers/Microsoft.Insights/actionGroups/AlertCyberEngineering",
                ]
              + contact_roles  = []
              + enabled        = true
              + operator       = "EqualTo"
              + threshold      = 50
              + threshold_type = "Actual"
            },
          + {
              + contact_emails = []
              + contact_groups = [
                  + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/cdn-actiongrp01.rg/providers/Microsoft.Insights/actionGroups/AlertCyberEngineering",
                ]
              + contact_roles  = []
              + enabled        = true
              + operator       = "EqualTo"
              + threshold      = 90
              + threshold_type = "Actual"
            },
        ],
      + "Monthly",
      + [
          + {
              + end_date   = "2030-01-01T00:00:00Z"
              + start_date = "2023-05-01T00:00:00Z"
            },
        ],
    ]
  + tf     = [
      + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/providers/Microsoft.Consumption/budgets/cdn-costnpd-ntf",
      + 300,
      + [],
      + [
          + {
              + contact_emails = []
              + contact_groups = [
                  + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/cdn-actiongrp01.rg/providers/Microsoft.Insights/actionGroups/AlertCyberEngineering",
                ]
              + contact_roles  = []
              + enabled        = true
              + operator       = "EqualTo"
              + threshold      = 50
              + threshold_type = "Actual"
            },
          + {
              + contact_emails = []
              + contact_groups = [
                  + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/cdn-actiongrp01.rg/providers/Microsoft.Insights/actionGroups/AlertCyberEngineering",
                ]
              + contact_roles  = []
              + enabled        = true
              + operator       = "EqualTo"
              + threshold      = 90
              + threshold_type = "Actual"
            },
          + {
              + contact_emails = []
              + contact_groups = [
                  + "/subscriptions/xxxx-xxxx-xxxx-xxxxx-xxxxx/resourceGroups/cdn-actiongrp01.rg/providers/Microsoft.Insights/actionGroups/AlertPagerDuty",
                ]
              + contact_roles  = []
              + enabled        = true
              + operator       = "EqualTo"
              + threshold      = 95
              + threshold_type = "Actual"
            },
        ],
      + "Monthly",
      + [
          + {
              + end_date   = "2030-01-01T00:00:00Z"
              + start_date = "2023-05-01T00:00:00Z"
            },
        ],
    ]

**Comment by eric-mark** [comment]
I've re-tested the alert deployed via terraform using the expiry date as the same as the manual alert.  The alert did not trigger.

**Comment by eric-mark** [comment]
After some further investigation with msft support team, we identified that this isn't a bug.  The "operator" had to be set to "GreaterThanOrEqualTo" rather than "EqualTo".  "EqualTo" will never trigger unless we hit the exact amount.
