### ISSUE TITLE
Support for allow_public_access_from_azure of azurerm_mysql_flexible_server

### ISSUE THREAD

**Issue by rsun-thoughtworks** [hashicorp/terraform-provider-azurerm#21832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We currently have seen a toggle in the Azure Portal that allows us to "Allow public access from any Azure service within Azure to this server" for a particular resource. However, when working with the azurerm_mysql_flexible_server, we couldn't find a corresponding option or configuration to enable this feature.

### New or Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Potential Terraform Configuration

```hcl
Option Name: azure_public_access_enabled

This option will enable "Allow public access from any Azure service within Azure to this server".
```

**Comment by garyburgmann** [comment]
```terraform
resource "azurerm_mysql_flexible_server_firewall_rule" "allow_access_to_azure_services" {
   name                               = "allow_access_to_azure_services"
   resource_group_name  = "foo"
   server_name                  = "bar"
   start_ip_address           = "0.0.0.0"
   end_ip_address             = "0.0.0.0"
   depends_on = [
     azurerm_mysql_flexible_server.foobar
   ]
 }
```

**Comment by rsun-thoughtworks** [comment]
> documented: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server_firewall_rule#example-usage-allow-access-to-azure-services
> 
> ```terraform
> resource "azurerm_mysql_flexible_server_firewall_rule" "allow_access_to_azure_services" {
>    name                 = "allow_access_to_azure_services"
>    resource_group_name  = "foo"
>    server_name          = "bar"
>    start_ip_address     = "0.0.0.0"
>    end_ip_address       = "0.0.0.0"
> }
> ```

No you got it all wrong.

When enable this option it will allow requests from within Azure, but not allow internet access.

Your example will grant access to all incoming request, regardless of source.

**Comment by steph409** [comment]
Hi!
I need this option as well. In the Microsoft Landing zone, there is a built-in policy which [denies public network ](https://www.azadvertizer.net/azpolicyadvertizer/c9299215-ae47-4f50-9c54-8a392f68a052.html) access for Mysql. 
When this policy is applied, it is not possible to deploy the mysql flexible server with terraform, as the option to disable the public access is missing.

**Comment by serbezki** [comment]
I'm not sure if this is related, but there also doesn't seem to be a way to disable public access from terraform? Or at least I'm having a hard time finding it documented anywhere.

**Comment by kingsleyadam** [comment]
> I'm not sure if this is related, but there also doesn't seem to be a way to disable public access from terraform? Or at least I'm having a hard time finding it documented anywhere.

Agreed, I'm not sure if there's a specific configuration that disables public access? One of the attributes to the MySQL resource is [public_network_access_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#public_network_access_enabled) so it's a bit odd it's not an argument.

**Comment by tombuildsstuff** [comment]
👋 

As mentioned above and similar to other Azure Services, Firewall Rules within Azure use the special value `0.0.0.0` to mean `Azure Services` rather than "open to the internet" (as in many other systems) - as such it's possible to configure access to Azure Services as in [this example in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server_firewall_rule#example-usage-allow-access-to-azure-services)). With regards to configuring whether Public Network Access is enabled on the MySql Flexible Server, this can be configured [using the `public_network_access_enabled` field on the `azurerm_mysql_flexible_server` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#public_network_access_enabled).

Since these questions have been resolved I'm going to go ahead and close this issue for the moment, but should you have any further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by kingsleyadam** [comment]
> 👋
> 
> As mentioned above and similar to other Azure Services, Firewall Rules within Azure use the special value `0.0.0.0` to mean `Azure Services` rather than "open to the internet" (as in many other systems) - as such it's possible to configure access to Azure Services as in [this example in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server_firewall_rule#example-usage-allow-access-to-azure-services)). With regards to configuring whether Public Network Access is enabled on the MySql Flexible Server, this can be configured [using the `public_network_access_enabled` field on the `azurerm_mysql_flexible_server` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#public_network_access_enabled).
> 
> Since these questions have been resolved I'm going to go ahead and close this issue for the moment, but should you have any further questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).
> 
> Thanks!

@tombuildsstuff 

A heads up, the [public_network_access_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server#public_network_access_enabled) is an attribute, not an argument.

I did find #24641 which is exactly what's required for public access enablement.

**Comment by clowa** [comment]
For everyone coming around looking for an option to disable the public network access - I found an workaround via the `Azure/azapi` provider, pleas see my [comment here](https://github.com/hashicorp/terraform-provider-azurerm/issues/24641#issuecomment-2076689855).
