### ISSUE TITLE
azurerm_cdn_frontdoor_rule does not allow only slash in match_values

### ISSUE THREAD

**Issue by dhilgarth** [hashicorp/terraform-provider-azurerm#21851]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule" "index" {
  name                      = "index"
  cdn_frontdoor_rule_set_id = azurerm_cdn_frontdoor_rule_set.index.id
  order                     = 1

  actions {
    url_rewrite_action {
      destination    = "/index.html"
      source_pattern = "/"
    }
  }

  conditions {
    url_path_condition {
      match_values = ["/"]
      operator     = "Equal"
    }
  }
  depends_on = [azurerm_cdn_frontdoor_origin.frontend, azurerm_cdn_frontdoor_origin_group.frontend]
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

It should be supported.

I found [this closed issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/20652), however:
1. This may be a special case, because when I create this via the UI, the leading slash is being persisted, as can be seen from retrieving the data via the CLI:
` az afd rule list -g XXX --profile-name frontdoor --rule-set-name index`
```
...
    "actions": [
      {
        "name": "UrlRewrite",
        "parameters": {
          "destination": "/index.html",
          "preserveUnmatchedPath": false,
          "sourcePattern": "/"
        }
      }
    ],
    "conditions": [
      {
        "name": "UrlPath",
        "parameters": {
          "matchValues": [
            "/"
          ],
          "negateCondition": false,
          "operator": "Equal",
          "transforms": []
        }
      }
    ],
...
```
2. Just not providing the slash, i.e. using `match_values = [""]` will lead to an error during apply: 
> Error: creating Front Door Rule: (Rule Name "index" / Rule Set Name "index" / Profile Name "frontdoor" / Resource Group "XXX"): cdn.RulesClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Rules validation failed. More information: Match value(s) must be provided."

I've filed an issue regarding the documentation: https://github.com/MicrosoftDocs/azure-docs/issues/109767

### Actual Behaviour

I get this error:

Error: "conditions.0.url_path_condition.0.match_values.0" must not begin with the URLs leading slash(e.g. /), got "/"
│
│   with module.frontend.azurerm_cdn_frontdoor_rule.index,
│   on modules\app\frontend\main.tf line 50, in resource "azurerm_cdn_frontdoor_rule" "index":
│   50:       match_values = ["/"]

### Steps to Reproduce

`terraform validate`

**Comment by indispeq** [comment]
Thank you for the work done on this @mbfrahry!

I am a little confused as to why this still does not work. I tried installing the 3.66 and 3.67 versions of the Azure provider, after seeing this problem solved, but I still get the error:

```
Planning failed. Terraform encountered an error while generating this plan.
                                                                                      
╷                                                                                     
│ Error: "conditions.0.url_path_condition.0.match_values.0" must not begin with the URLs leading slash(e.g. /), got "/health/"                                              
│                                                                                                                                                                           
│   with azurerm_cdn_frontdoor_rule.afd_rule["healthCheckNoRedirect"],
│   on main.tf line 59, in resource "azurerm_cdn_frontdoor_rule" "afd_rule":
│   59:       match_values     = each.value.match_values                                                                                                                    
│
```

**Comment by grasch** [comment]
Hey! The problem is still there, have it with azurerm v3.94.0 following the Microsoft documentation to set a no-cache-rule for authentication (https://learn.microsoft.com/en-us/azure/static-web-apps/front-door-manual?pivots=swa-afd-manual-afd&tabs=azure-portal#disable-cache-for-auth-workflow)

```
Planning failed. Terraform encountered an error while generating this plan.

│ Error: "conditions.0.url_path_condition.0.match_values.0" must not begin with the URLs leading slash(e.g. /), got "/.auth"
```
