### ISSUE TITLE
azurerm_cosmosdb_postgresql_coordinator_configuration can't find configuration

### ISSUE THREAD

**Issue by DIGIOFLV** [hashicorp/terraform-provider-azurerm#21857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_postgresql_coordinator_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_postgresql_cluster" "cosmosdb_postgresql_cluster" {
  name                                 = "coordinator-cosmosdbpostsqlclust-19987"
  resource_group_name                  = azurerm_resource_group.example.name
  location                             = azurerm_resource_group.example.location
  administrator_login_password         = random_password.password.result
  coordinator_public_ip_access_enabled = false
  node_public_ip_access_enabled        = false
  sql_version                          = 12
  coordinator_storage_quota_in_mb      = 32768
  coordinator_vcore_count              = 1
  node_count                           = 0
  coordinator_server_edition           = "BurstableGeneralPurpose"
  maintenance_window {
    day_of_week  = 0
    start_hour   = 0
    start_minute = 0
  }
  ha_enabled               = false
  node_server_edition      = "MemoryOptimized"
  node_storage_quota_in_mb = 131072
  node_vcores              = 2
  preferred_primary_zone   = 1
}

resource "azurerm_cosmosdb_postgresql_coordinator_configuration" "configurator_cosmosdb_postgresql_cluster" {
  name       = "coordinator-cosmosdbpostsqlclust-19987-config"
  cluster_id = azurerm_cosmosdb_postgresql_cluster.cosmosdb_postgresql_cluster.id
  value      = "on"
}
```

### Debug Output/Panic Output

```shell
Error: updating Coordinator Configuration
Coordinator Configuration Name: "coordinator-cosmosdbpostsqlclust-19987-config"): performing UpdateOnCoordinator: configurations.ConfigurationsClient#UpdateOnCoordinator: Failure sending request: StatusCode=0 -- Original Error: Code="not_found" Message="There is no configuration with name \"coordinator-cosmosdbpostsqlclust-19987-config\"."
```

### Expected Behaviour

Coordinator node configuration creation.

### Actual Behaviour

The cluster is created but the configuration for the coordinator node is not.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems the configuration name you specified is invalid. See more details from https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-server-parameters.

**Comment by DIGIOFLV** [comment]
Hi @neil-yechenwei , thanks for the quick reply. What do you mean for "invalid configuration name"? In registry the configuration name is a string: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_postgresql_node_configuration.
Your link refers to postgresql flexible while I'm having problems with Cosmos Db for Postgrsql.

**Comment by neil-yechenwei** [comment]
Sorry for late response. I mean seems the parameter name "coordinator-cosmosdbpostsqlclust-19987-config" of azurerm_cosmosdb_postgresql_coordinator_configuration you set is incorrect. I assume it should be predefined parameter name. Maybe this doc https://learn.microsoft.com/en-us/azure/cosmos-db/postgresql/reference-parameters is helpful.

**Comment by DIGIOFLV** [comment]
thanks @neil-yechenwei.
