### ISSUE TITLE
azurerm_service_plan doesn't implement P0V3 as a valid sku_name

### ISSUE THREAD

**Issue by troyha** [hashicorp/terraform-provider-azurerm#21879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement P0V3 as a valid App Service Plan [sku_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/service_plan#sku_name) . This sku is very economical in comparison to Standard and older Premium versions on Linux and I see no reason why anyone would choose Standard with this sku available.

There is an Azure bug which is apparently being fixed with an ETA rollout end of June which may affect this being implemented. I reported an issue (referenced below) so if it does affect the implementation, then once this is fixed it would be nice to have this sku added to TF. 

### New or Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Potential Terraform Configuration

```hcl
resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "P0v3"
}
```

### References

https://github.com/Azure/azure-cli/issues/26498

**Comment by aristosvo** [comment]
Hi @troyha! Thanks for raising this.

This should work AFAIK, but it is not documented properly when I added the SKUs (#21371).

**Comment by troyha** [comment]
I was about to update with the Actions error "Error: expected sku_name to be one of [B1 B2 B3 S1 S2 S3 P1v2 P2v2 P3v2 P1v3 P2v3 P3v3 Y1 EP1 EP2 EP3 F1 I1 I2 I3 I1v2 I2v2 I3v2 D1 SHARED WS1 WS2 WS3], got P0V3" that I'm getting and [found an existing issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/21554) when I searched this specific error
