### ISSUE TITLE
Terraform throws a Console Error: mysql.ServersClient#Update: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError"

### ISSUE THREAD

**Issue by stefanzahov-ops** [hashicorp/terraform-provider-azurerm#21878]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.14.11

### AzureRM Provider Version

2.65.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_server

### Terraform Configuration Files

```hcl
locals {
  common_tags = {
    Terraform = "true"
  }

  tags = merge(local.common_tags, var.tags)
  tags_with_resource_group = merge(
    local.tags,
    {
      "ResourceGroupName" = var.resource_group_name
    },
  )

resource "azurerm_mysql_server" "this" {
  count                        = var.create ? 1 : 0
  name                         = "${var.db_name}-mysqlsvr"
  location                     = var.location
  resource_group_name          = var.resource_group_name
  sku_name                     = var.sku_name
  administrator_login          = var.db_admin_username
  administrator_login_password = local.db_admin_password
  version                      = var.db_version
  storage_mb                   = var.storage_mb
  backup_retention_days        = var.backup_retention_days
  geo_redundant_backup_enabled = var.geo_redundant_backup_enabled
  ssl_enforcement_enabled      = var.ssl_enforcement_enabled
  auto_grow_enabled            = var.auto_grow_enabled
  tags                         = local.tags_with_resource_group
  create_mode                  = var.create_mode
  creation_source_server_id    = var.create_mode != "Default" ? var.primary_server_id : null
}
```

### Debug Output/Panic Output

```shell
After Terraform apply: 


Error: updating Server: (Name "<server_name>" / Resource Group "<rg_name>"): mysql.ServersClient#Update: Failure sending request: StatusCode=500 -- Original Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '2deb8587-40d7-41f2-96f6-34aedbb4fbf9'"
```

### Expected Behaviour

The In-place upgrade on the replica server should not raise an internal server error and to have a successful output after Terraform apply.

### Actual Behaviour

In our setup, we use 2 modules for the MySQL Managed servers - primary and secondary (replica). The replica server depends on the primary via the Remote state. 

We tried to update tags or retention days for the secondary (replica) module. 

The Terraform plan is as follows:

    `     # module.mysql-managed-replica.azurerm_mysql_server.this[0] will be updated in-place
  
      ~ resource "azurerm_mysql_server" "this" {
  
       id   =  <resource_id>

       name = <recource_name>
      ~ tags                              = {
   
       - "Environment"        = "dev" -> null
       
       # (7 unchanged elements hidden)
    }`

During the secondary apply over the already deployed replica module the Terraform updates successfully the changes inside the state and the changes are reflected in the Azure console inside the resource as well but the Terraform apply throws the following Error: 

 Error: updating Server: (Name "<server_name>" / Resource Group "<rg_name>"): mysql.ServersClient#Update: Failure sending request: StatusCode=500 -- Original Error: Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '2deb8587-40d7-41f2-96f6-34aedbb4fbf9'"

We tried it with the updated Azurerm provider (3.48.0) and it didn't solve the issue

**Comment by tombuildsstuff** [comment]
hi @stefanzahov-ops 

Thanks for opening this issue.

This 500 error is an internal error coming back from the Azure API (which is using an older version of the API) - since the provider version you're using (`v2.65.0`) is  [nearly 2 years old at this point](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v2.65.0) - we'd suggest trying this using the latest version of the Provider (which [at the time of writing is `v3.57.0`](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.57.0)).

Since this should be fixed by updating to the latest version of the Provider/a newer version of the API - I'm going to close this issue for the moment, but if this issue isn't fixed by updating to the latest version of the Provider then please let us know and we can take another look.

Thanks!

**Comment by stefanzahov-ops** [comment]
@tombuildsstuff 

Thanks for the suggestion, but I don't think this resolved my issue. 
After the upgrade to the latest provider version (3.57.0), there was a planned in-place update for "ssl_minimal_tls_version_enforced".

The Terraform plan is as follows: 

`(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: Initializing provider plugins...
 (out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - terraform.io/builtin/terraform is built in to Terraform
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - Finding hashicorp/azurerm versions matching "3.57.0"...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - Finding hashicorp/random versions matching "3.5.1"...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - Installing hashicorp/azurerm v3.57.0...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:39: - Installed hashicorp/azurerm v3.57.0 (signed by HashiCorp)
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:39: - Installing hashicorp/random v3.5.1...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:40: - Installed hashicorp/random v3.5.1 (signed by HashiCorp)
`


...

`(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:   # module.mysql-managed-replica.azurerm_mysql_server.this[0] will be updated in-place
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:   ~ resource "azurerm_mysql_server" "this" {`

...

`(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:       ~ ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled" -> "TLS1_2"`

...

`(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:         # (16 unchanged attributes hidden)
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:     }
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08: 
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08: Plan: 0 to add, 1 to change, 0 to destroy.`

...

The update happened inside the Azure console for the resource and inside the state but still Terraform threw the following Error again: 

`(err [mysql-azure] [example-mysql-managed-replica] [terraform apply]) 2023-05-23T08:46:47: Error: waiting for update of Server: (Name "bp-mysql-azure-db-read-mysqlsvr" / Resource Group "rg-bp-azure-tests"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '798b5155-a9bc-4a58-a65e-98cd9421fc2c'"
(err [mysql-azure] [example-mysql-managed-replica] [terraform apply]) 2023-05-23T08:46:47: `

**Comment by stefanzahov-ops** [comment]
@tombuildsstuff 

Thanks for the suggestion, but I don't think this resolved my issue. 
After the upgrade to the latest provider version (3.57.0), there was a planned in-place update for "ssl_minimal_tls_version_enforced".

The Terraform plan is as follows: 

`(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: Initializing provider plugins...
 (out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - terraform.io/builtin/terraform is built in to Terraform
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - Finding hashicorp/azurerm versions matching "3.57.0"...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - Finding hashicorp/random versions matching "3.5.1"...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:35: - Installing hashicorp/azurerm v3.57.0...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:39: - Installed hashicorp/azurerm v3.57.0 (signed by HashiCorp)
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:39: - Installing hashicorp/random v3.5.1...
(out [mysql-azure] [example-mysql-managed-replica] [terraform init]) 2023-05-23T08:42:40: - Installed hashicorp/random v3.5.1 (signed by HashiCorp)
`


...

`(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:   # module.mysql-managed-replica.azurerm_mysql_server.this[0] will be updated in-place
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:   ~ resource "azurerm_mysql_server" "this" {`

...

`(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:       ~ ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled" -> "TLS1_2"`

...

`(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:         # (16 unchanged attributes hidden)
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08:     }
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08: 
(out [mysql-azure] [example-mysql-managed-replica] [terraform plan]) 2023-05-23T08:43:08: Plan: 0 to add, 1 to change, 0 to destroy.`

...

The update happened inside the Azure console for the resource and inside the state but still Terraform threw the following Error again: 

`(err [mysql-azure] [example-mysql-managed-replica] [terraform apply]) 2023-05-23T08:46:47: Error: waiting for update of Server: (Name "<mysql_server_name>" / Resource Group "<rg_name>"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '798b5155-a9bc-4a58-a65e-98cd9421fc2c'"
(err [mysql-azure] [example-mysql-managed-replica] [terraform apply]) 2023-05-23T08:46:47: `
