### ISSUE TITLE
App Configuration LRO failed with internal error 

### ISSUE THREAD

**Issue by teowa** [hashicorp/terraform-provider-azurerm#21870]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.55.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "wt-testRG"
  location = "West Europe"
}

resource "azurerm_app_configuration" "appconf" {
  name                = "appConf1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}
```

### Debug Output/Panic Output

```shell
azurerm_app_configuration.appconf: Creating...
azurerm_app_configuration.appconf: Still creating... [10s elapsed]
╷
│ Error: creating Configuration Store (Subscription: "xxx"
│ Resource Group Name: "wt-testRG"
│ Configuration Store Name: "appConf1"): polling after Create: internal-error: a polling status of `Failed` should be surfaced as a PollingFailedError
│
│   with azurerm_app_configuration.appconf,
│   on main.tf line 6, in resource "azurerm_app_configuration" "appconf":
│    6: resource "azurerm_app_configuration" "appconf" {
│
╵
```

### Expected Behaviour

The error message should show error returned by API
with 3.54.0 of provider, the error message is like:
```
azurerm_app_configuration.appconf: Creating...
azurerm_app_configuration.appconf: Still creating... [10s elapsed]
╷
│ Error: creating Configuration Store (Subscription: "xxx"
│ Resource Group Name: "wt-testRG"
│ Configuration Store Name: "appConf1"): polling after Create: Code="NameUnavailable" Message="The specified name is already in use." AdditionalInfo=[{"info":{"activityId":"eb15c086-92d1-491f-a529-4d895e05bec8"},"type":"ActivityId"}]
│
│   with azurerm_app_configuration.appconf,
│   on main.tf line 6, in resource "azurerm_app_configuration" "appconf":
│    6: resource "azurerm_app_configuration" "appconf" {
│
╵
```

### Actual Behaviour

The apply fails with internal-error.

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/21637

**Comment by srikanthreddy005** [comment]
Facing same issue..
