### ISSUE TITLE
CMK resources for data and mssql detect CMK changes when there were none

### ISSUE THREAD

**Issue by taipignas** [hashicorp/terraform-provider-azurerm#21888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7

### AzureRM Provider Version

3.57.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_customer_managed_key azurerm_mssql_server_transparent_data_encryption

### Terraform Configuration Files

```hcl
configuration code can be taken from documentation
```

### Debug Output/Panic Output

```shell
customer_managed_key {
          - key_vault_key_id = "https://xx.vault.azure.net/keys/xxxxx" -> null
        }

 transparent_data_encryption_key_vault_key_id = "https://xx.vault.azure.net/keys/xxx" -> null
```

### Expected Behaviour

No changes were done so no changes should be detected by apply command

### Actual Behaviour

for both azurerm_storage_account_customer_managed_key and azurerm_mssql_server_transparent_data_encryption changes are detected on their attached resources azurerm_storage_account and azurerm_mssql_server

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/55182635/9e2b2b3a-e446-4834-ba81-02ca18a19417)
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/55182635/c2545bf9-cddf-44af-9ad6-6d5af654c836)

### Steps to Reproduce

1. create resources with CMK for storage or mssql
2. apply
3. apply again
4. changes are visible
5. apply again
6. samge changes are visible again

**Comment by taipignas** [comment]
this was some weird behavior i had when using a workaround with data resource

**Comment by myc2h6o** [comment]
Hi @taipignas thanks for reporting this! There is a missing `ignore_changes` within these documents. For `azurerm_storage_account`, the fix has been done recently, and now you can see the `ignore_changes` which tells the parent resource to ignore the change of the key which is managed by the child resource: https://github.com/hashicorp/terraform-provider-azurerm/blob/4729085ade44e177e839936784ed632dbeed5217/website/docs/r/storage_account_customer_managed_key.html.markdown?plain=1#L106-L110
For `azurerm_mssql_server`, we will be applying a similar fix soon.

**Comment by taipignas** [comment]
still doesnt work for me i still see changes on both azurerm_storage_account and azurerm_mssql_server for the CMK property, even though the attached CMK rsources didnt change.
