### ISSUE TITLE
Support for changing AKS default node pool params without recreating the cluster

### ISSUE THREAD

**Issue by adityasundaramurthy-maersk** [hashicorp/terraform-provider-azurerm#21881]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provider v3.47.0 added support for expanding the default nodepool by changing VM size via #20628. However, this does not support changing other typically optional parameters, such as `os_disk_size_gb`, which may differ for a specific VM SKU and might need to be changed for other SKUs (for instance, when changing `Standard_D8as_v4` to `Standard_D4as_v4`. 

As we now have the ability to swap the default pool through a temporary pool, can this mechanism be used to modify these parameters that typically require recreating the cluster, or managing the change externally via Azure CLI and then importing the new state?

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
Resource configuration remains unchanged
```

### References

#7093
#20628 
#21859 is related but applies to additional nodepools

**Comment by aristosvo** [comment]
Hi @adityasundaramurthy-maersk! Thanks for opening this issue.

As far as I know this should be covered by the open PR #21719.
