### ISSUE TITLE
Azure App Gw Request Routing Rule Prioririty is not Optional

### ISSUE THREAD

**Issue by truekonrads** [hashicorp/terraform-provider-azurerm#21891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.5.7

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "agw" {
#...
  request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Application Gateway: (Name "yyy" / Resource Group "xxxxx"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayRequestRoutingRulePriorityCannotBeEmpty" Message="Priority for the request routing rule /subscriptions/xxx/resourceGroups/yyyy/providers/Microsoft.Network/applicationGateways/yyyy_agw/requestRoutingRules/cyber-ti-portal-test_agw_req_routing_rule cannot be empty. All request routing rules should have a priority defined starting from api-version 2021-08-01" Details=[]
```

### Expected Behaviour

Documentation / Terraform must validate that priority is provided

### Actual Behaviour

If priority is not given, terraform goes ahead but Azure crashes

**Comment by ms-zhenhua** [comment]
Hi @truekonrads, thank you for reaching out. 
According to this [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#priority), `priority` is required when `sku.0.tier` is set to `*_v2`. When `sku.0.tier` is set to `*_v1`, the `priority` is still optional.
