### ISSUE TITLE
azurerm_eventgrid_event_subscription webhook with Blob Storage trigger is not accepting &

### ISSUE THREAD

**Issue by jaritimonen** [hashicorp/terraform-provider-azurerm#21904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.57

### Affected Resource(s)/Data Source(s)

azurerm_eventgrid_event_subscription

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_event_subscription" "example" {
  name                  = "evgs-example"
  scope                 = var.storage_account_id
  event_delivery_schema = "EventGridSchema"

  webhook_endpoint {
    url = "https://${azurerm_linux_function_app.example.default_hostname}/runtime/webhooks/blobs?functionName=example&code=${data.azurerm_function_app_host_keys.example.blobs_extension_key}"
  }
  included_event_types = [
    "Microsoft.Storage.BlobCreated",
  ]
}
```

### Debug Output/Panic Output

```shell
Code="Url validation" Message="Webhook validation handshake failed for..."
```

### Expected Behaviour

I'm trying to do this tutorial with Terraform: https://learn.microsoft.com/en-us/azure/azure-functions/functions-event-grid-blob-trigger?pivots=programming-language-csharp

It should have created an event subsription.

### Actual Behaviour

Webhook_endpoint parameter is sent API like this:
https://<FUNCTION_APP_NAME>.azurewebsites.net/runtime/webhooks/blobs?functionName=BlobTriggerEventGrid\u0026code=<BLOB_EXTENSION_KEY>

So & is encoded to \u0026 which is not something Azure is accepting and crashes the whole function in a state that is needs to be redeployed 

### Steps to Reproduce

Follow the tutorial, instead of using visual studio, use terraform.

### References

https://github.com/hashicorp/terraform/issues/31756

**Comment by myc2h6o** [comment]
Hi @jaritimonen thanks for opening the issue! The transformation from `&` to `\u0026` is done at Json marshal layer within the sdk. At service side, the escaped character shall be translated back at Json unmarshal layer and won't cause issue. I guess there might be some issue with the function? Below is a working example I tested in my environment, and I am able to see the `\u0026` in the request detail when setting `TF_LOG` to `DEBUG`, could you give it a try and see if it could work in your environment?


(I met the issue #16196 when using `azurerm_linux_function_app` so I switched to `azurerm_windows_function_app` instead)
```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "testrg"
  location = "eastus"
}

resource "azurerm_storage_account" "example" {
  name                     = "testsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_service_plan" "example" {
  name                = "testplan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  os_type             = "Windows"
  sku_name            = "S1"
}

resource "azurerm_windows_function_app" "example" {
  name                = "testapp"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  service_plan_id     = azurerm_service_plan.example.id

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key

  site_config {
    application_stack {
      dotnet_version = "v6.0"
    }
  }
}

resource "azurerm_function_app_function" "example" {
  name            = "example"
  function_app_id = azurerm_windows_function_app.example.id
  config_json     = jsonencode({
    "bindings" = [
      {
        "name" = "myBlob"
        "type" = "blobTrigger"
        "source" = "eventGrid"
      }
    ]
  })
}

// There may be some delay for `blobs_extension_key` to generate, may need to add a wait before reading the data source
data "azurerm_function_app_host_keys" "example" {
  name                = azurerm_windows_function_app.example.name
  resource_group_name = azurerm_resource_group.example.name

  depends_on = [ 
    azurerm_function_app_function.example
  ]
}

resource "azurerm_eventgrid_event_subscription" "example" {
  name                  = "test"
  scope                 = azurerm_storage_account.example.id
  event_delivery_schema = "EventGridSchema"

  webhook_endpoint {
    url = "https://${azurerm_windows_function_app.example.default_hostname}/runtime/webhooks/blobs?functionName=example&code=${data.azurerm_function_app_host_keys.example.blobs_extension_key}"
  }
  included_event_types = [
    "Microsoft.Storage.BlobCreated",
  ]
}

```

**Comment by jaritimonen** [comment]
Hello @myc2h6o. You just saved my day!
It workes, I added azurerm_function_app_function with bindings (instead of just adding functions from command line) and added depends_on = [ 
    azurerm_function_app_function.example
  ]
We can close this. Thanks a lot! :)
