### ISSUE TITLE
Unable to create azurerm_monitor_metric_alert on Azure App Service Plan

### ISSUE THREAD

**Issue by SImmy1710** [hashicorp/terraform-provider-azurerm#21902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0

### AzureRM Provider Version

2.99

### Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Terraform Configuration Files

```hcl
locals{
alert_signals =  {
    "warning_memoryPercentage" = {
      severity        = 2,
      threshold_alert = 80,
      aggregation     = "Average"
      metric_name     = "MemoryPercentage",
      frequency       = "PT1M",
      window_size     = "PT15M"
    },
    "critical_memoryPercentage" = {
      severity        = 1,
      threshold_alert = 95,
      aggregation     = "Average"
      metric_name     = "MemoryPercentage",
      frequency       = "PT1M",
      window_size     = "PT15M"
    },
    "warning_cpuPercentage" = {
      severity        = 2,
      threshold_alert = 80,
      aggregation     = "Average"
      metric_name     = "CpuPercentage",
      frequency       = "PT1M",
      window_size     = "PT30M"
    }


resource "azurerm_monitor_metric_alert" "alerts" {
  for_each = local.alert_signals

  name                = "${metric}-${each.key}"
  resource_group_name = "test-resourceGroup"
  scopes              = [azurerm_app_service_plan.app_service_plan.id]
  description         = "Tags\n============\n[Category = P${each.value.severity}]\n[Project = ${local.name}]"

  criteria {
    aggregation            = each.value.aggregation
    metric_name            = each.value.metric_name
    metric_namespace       = "Microsoft.Web/serverfarms"
    operator               = "GreaterThanOrEqual"
    threshold              = each.value.threshold_alert
    skip_metric_validation = true
  }

  severity      = each.value.severity
  auto_mitigate = true
  frequency     = each.value.frequency
  window_size   = each.value.window_size

  action {
    action_group_id = data.azurerm_monitor_action_group.integration-platform-action-group.id
    webhook_properties = {
      from = "terraform"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating or updating Monitor Metric Alert: (Name "metric_memoryPercentage" / Resource Group "test-resourceGroup"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Couldn't find a metric named MemoryPercentage.
```

### Actual Behaviour

terraform apply fails with the given error but retry fixes this

### Steps to Reproduce

terraform apply

### Important Factoids

NA

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert.html

**Comment by rcskosir** [comment]
@SImmy1710  Thank you for opening this issue.
Unfortunately we do not support older versions of the provider including 2.99.
The latest version as of this comment is 3.57.0 and is available on the same page as you linked in references: 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs

If you are able to update to the latest provider version and are still experiencing this issues, please update the issue with the latest version.

**Comment by rcskosir** [comment]
I am going to mark this issue as closed, due to the older version of the provider. If you are able to update to the latest provider version and are still experiencing this issues, we can reopen this issue.
