### ISSUE TITLE
azurerm_storage_account: randomly failed with ResourceNotFound or ContainerOperationFailure

### ISSUE THREAD

**Issue by hieunguyen-gkgab** [hashicorp/terraform-provider-azurerm#21903]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.46.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "resource_name" {

  name                = "st_name"
  resource_group_name = "rg_name"
  location            = var.location

  account_tier             = "Standard"
  account_kind             = "StorageV2"
  account_replication_type = "LRS"
  access_tier              = "Hot"

  enable_https_traffic_only       = true
  shared_access_key_enabled       = true
  allow_nested_items_to_be_public = false

  lifecycle {
    ignore_changes = [
      tags,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Error: reading share properties for AzureRM Storage Account "st_name": storage.FileServicesClient#GetServiceProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:70e82cce-b01a-004b-1551-8dbd4a000000\nTime:2023-05-23T08:37:43.3778079Z"

or 

Error: reading blob properties for AzureRM Storage Account "st_name": storage.BlobServicesClient#GetServiceProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ContainerOperationFailure" Message="The specified resource does not exist.\nRequestId:aa962bee-c01e-0034-8086-88aefe000000\nTime:2023-05-17T06:09:42.4267220Z"
```

### Expected Behaviour

Storage account should be created successfully. 

### Actual Behaviour

Most times the storage account is created successfully. The error occurred randomly. I did try to update provider verstion to 3.56.0 but the problem still exists.

**Comment by rcskosir** [comment]
@hieunguyen-gkgab Thank you for opening this issue.
Unfortunately we do not support older versions of the provider including 1.46.0. 
Our docs page is up to date with the latest version and can be found here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs

If you are able to update to the latest provider version and are still experiencing this issues, please update the issue with the latest version.

**Comment by hieunguyen-gkgab** [comment]
@rcskosir sorry it was my typo.
I updated the issue. The provider version is actually 3.46.0 and I also tested with 3.56.0

**Comment by magodo** [comment]
@hieunguyen-gkgab Assuming you were recreating the storage account with the same name caused this 404 error, then the issue shall duplicate to #13070.

**Comment by hieunguyen-gkgab** [comment]
@magodo Thank you for your help! The root issue is clear for me now.

**Comment by rcskosir** [comment]
Thank you @hieunguyen-gkgab for opening this issue and updating the provider versions.
Thank you @magodo for the help.
I am going to mark this issue as a duplicate to #13070 and close this issue.
