### ISSUE TITLE
Azure Private Endpoint for Key Vault is not accepting subresource_name in ip_configuration

### ISSUE THREAD

**Issue by erthalmvp** [hashicorp/terraform-provider-azurerm#21925]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I'm facing exactly what was reported in #18443. Is possible for the issue to be reopened?

Regards.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.54.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "kv_priv" {
  name                = "pep-test"
  location            = "brazilsouth"
  resource_group_name = "rg-test"
  subnet_id           = "<subnet-ID>"

  ip_configuration {
    name               = "ip-test"
    private_ip_address = "xxx.xxx.xxx.xxx"
    subresource_names  = "vault"
  }

  private_service_connection {
    name                           = pep-conn-test
    private_connection_resource_id = "<key-vault-resource-id>"
    subresource_names              = ["vault"]
    is_manual_connection           = false
  }
```

### Debug Output/Panic Output

```shell
Error: creating Private Endpoint "xxxxxx" (Resource Group "xxxxxx"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateEndpointIpConfigurationMissingMemberNamesRequiredByFps" Message="Private Endpoint /subscriptions/xxxxxx/resourceGroups/xxxxxx/providers/Microsoft.Network/privateEndpoints/xxxxxx contains static ipconfigurations: [PrivateIPAddress: xxxxxx, GroupId: vault, MemberName: vault] and its missing these membernames/groupids requested by Private Link service [GroupId: vault, MemberName: default]. Private Endpoint needs to be reconfigured with missing memberNames." Details=[]
```

**Comment by magodo** [comment]
@erthalmvp This is similar to https://github.com/hashicorp/terraform-provider-azurerm/issues/21781. From the error message, you probably need to explicitly set the [`member_name`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint#member_name) to be `default`?
