### ISSUE TITLE
Discrepancy in docs and execution for Azure Kubernetes Fleet Manager

### ISSUE THREAD

**Issue by tillig** [hashicorp/terraform-provider-azurerm#21936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.57.0

### Affected Resource(s)/Data Source(s)

azurerm_kuberentes_fleet_manager

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_fleet_manager" "fleet_manager" {
  location            = var.management_cluster_location
  name                = "fleet-manager"
  resource_group_name = azurerm_resource_group.resource_group.name
  tags                = local.all_tags

  lifecycle {
    ignore_changes = [
      tags["created_by"],
      tags["date_created"]
    ]
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Fleet (Subscription: "XXXXXXXXX"
│ Resource Group Name: "aks-fleet-manager-demo"
│ Fleet Name: "fleet-manager"): performing CreateOrUpdate: fleets.FleetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="RequestFieldInvalid" Message="Invalid request field: DNS prefix = . Expected: A valid DNS prefix must contain between 1 and 54 characters and can contain only letters, numbers, and hyphens. It must start and end with alphanumeric values.. Resource ID: \"/subscriptions/XXXXXXXXX/resourceGroups/aks-fleet-manager-demo/providers/Microsoft.ContainerService/fleets/fleet-manager\". Correlation ID: \"YYYYYYYYY\". Operation ID: \"ZZZZZZZZZ\""
```

### Expected Behaviour

The [documentation](https://github.com/hashicorp/terraform-provider-azurerm/blob/8b5cdc6a28816fb5fcb4bb9681b40d171023fcec/website/docs/r/kubernetes_fleet_manager.html.markdown?plain=1#L43) currently says that the `hub_profile` block is optional, but if you omit it, the deployment fails because there's no DNS prefix specified.

The docs should indicate that the block is required - even if the provider doesn't require it, if you don't specify it, deployment fails.

### Actual Behaviour

Deployment without the [currently marked optional] `hub_profile` block fails.

### Steps to Reproduce

Create an Azure Kubernetes Fleet Manager and omit the `hub_profile` block. The example from the docs - with the `hub_profile` removed - is good enough.

**Comment by penicaudm** [comment]
Since Fleet has 2 modes (no hub, and hub_enabled), the deployment of a fleet manager with no hub_profile block should deploy a fleet manager with no hub, and a deployment with the hub_profile data should deploy a hub. Right now it seems the only supported deployment is with a hub.
