### ISSUE TITLE
The azurerm_datadog_monitor resource does not register the required "Microsoft.Datadog" resource provider on the subscription.

### ISSUE THREAD

**Issue by devblackops** [hashicorp/terraform-provider-azurerm#21968]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.5

### AzureRM Provider Version

3.57.0

### Affected Resource(s)/Data Source(s)

azurerm_datadog_monitor

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "datadog" {
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

resource "azurerm_datadog_monitor" "datadog_monitor" {
  name                = var.name
  resource_group_name = azurerm_resource_group.datadog.name
  location            = var.location
  sku_name            = "Linked"
  tags                = var.tags

  datadog_organization {
    api_key         = var.datadog_api_key
    application_key = var.datadog_app_key
    redirect_uri    = "https://portal.azure.com/TokenAuthorize"
  }

  user {
    name  = var.user_name
    email = var.user_email
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Monitor (Subscription: "<SUBSCRIPTION-ID>"
Resource Group Name: "<RESOURCE-GROUP-NAME>"
Monitor Name: "<RESOURCE-NAME>"): performing MonitorsCreate: Put "https://management.azure.com/subscriptions/<SUBSCRIPTION-ID>/resourceGroups/<RESOURCE-GROUP-NAME>/providers/Microsoft.Datadog/monitors/<RESOURCE-NAME>?api-version=2021-03-01": The Resource Provider was not registered.

Resource Providers (APIs) in Azure need to be registered before they can be used - however the Resource
Provider was not registered, and calling the API returned the following error:

The subscription is not registered to use namespace 'Microsoft.Datadog'. See https://aka.ms/rps-not-found for how to register subscriptions. >
```
```


### Expected Behaviour

The `Microsoft.Datadog` resource provider is automatically registered on the subscription if it has not been previously registered.

### Actual Behaviour

Creating required resource provider `Microsoft.Datadog` is not automatically registered prior to creating the `azurerm_datadog_monitor` resource.

### Steps to Reproduce

1. Create a new subscription where the resource provider `Microsoft.Datadog` has **NOT** been registered
2. terraform init
3. terraform plan/apply

### Important Factoids

_No response_

### References

I noticed that `Microsoft.Datadog` is not listed in https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/resourceproviders/required.go. Is it just a matter of adding it there? Since https://github.com/hashicorp/terraform-provider-azurerm/pull/20311 was merged and this now uses https://github.com/hashicorp/go-azure-sdk, does something else need to be done?

**Comment by sinbai** [comment]
@devblackops thanks for opening this issue. Terraform auto-registers what we’re calling the “core RP’s”(listed in [required.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/resourceproviders/required.go)) , since those RP’s should be enabled by default. For `Microsoft.Datadog`, I assume that it is not most users going to need it, so it is considered not core RP, which is why it is not listed in required.go. Could you please refer to the documentation [here](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types#register-resource-provider) to manually register `Microsoft.Datadog` ?

**Comment by devblackops** [comment]
@sinbai I understood that the provider should auto-register providers as-needed, depending on what resources are used. That is explicitly stated in the comment in [required.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/resourceproviders/required.go#L3)

> // Required returns all of the Resource Providers used by the AzureRM Provider
// whilst all may not be used by every user - the intention is that we determine which should be
// registered such that we can avoid obscure errors where Resource Providers aren't registered.
// new Resource Providers should be added to this list as they're used in the Provider
// (this is the approach used by Microsoft in their tooling)

**Comment by sinbai** [comment]
@devblackops thanks for your feedback. I have submitted PR to update the comment.
