### ISSUE TITLE
Support for Microsoft.Cache for Redis API v2023-04-01

### ISSUE THREAD

**Issue by ajtiwari07** [hashicorp/terraform-provider-azurerm#21973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please update terraform with latest API v2023-04-01 of Microsoft Azure Cache for Redis. 
[Public Docs](https://learn.microsoft.com/en-us/rest/api/redis/redis/create?tabs=HTTP#redisconfiguration)

### New or Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### References

https://learn.microsoft.com/en-us/rest/api/redis/redis/create?tabs=HTTP#redisconfiguration

**Comment by aristosvo** [comment]
@ajtiwari07 Thanks for filing this issue.

Can you explain/specify which functionalities or features this would enable?

**Comment by ajtiwari07** [comment]
@aristosvo We have introduced a new storage-subscription-id parameter in redisConfiguration which allows to configure persistence and import/export on a storage account in different subscription but same region than the cache.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/116218102/e73a4030-d5f5-4864-8813-57ecc870d32f)
https://learn.microsoft.com/en-us/rest/api/redis/redis/import-data?tabs=HTTP
https://learn.microsoft.com/en-us/rest/api/redis/redis/export-data?tabs=HTTP
https://learn.microsoft.com/en-us/rest/api/redis/redis/create?tabs=HTTP

**Comment by aristosvo** [comment]
@ajtiwari07 Hi 👋 

I'm just a community maintainer, so I cannot give you any predictions on when this will go in. It doesn't seem the most pressing issue for the users of `azurerm`, as there are no 👍s on this issue. But that is just my impression, feel free to enlighten me on things like deprecations of the existing APIs.

As far as I know these requests are usually channeled via an internal channel and prioritized between the MS and HashiCorp people working on this for a living, but I don't have any insight on the matter more than what is publicly visible.

@rcskosir might know it a bit better indeed.

**Comment by catriona-m** [comment]
Hi @ajtiwari07. I am currently working on upgrading this. In order for us to generate the sdk it seems a workaround is required (see: https://github.com/hashicorp/pandora/pull/2686). It looks like a PR has been opened on the azure-rest-api-specs repo to resolve this (https://github.com/Azure/azure-rest-api-specs/pull/22407) - it would be good if that fix could be included in the next API version?

**Comment by ajtiwari07** [comment]
@catriona-m I am not familiar with this change. Is the sdk release with new api version blocked until this workaround is also applied to v2023-04-01 ?
