### ISSUE TITLE
Attestation provider policies are being set when not specified

### ISSUE THREAD

**Issue by msanft** [hashicorp/terraform-provider-azurerm#21998]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_attestation_provider

### Terraform Configuration Files

```hcl
resource "azurerm_attestation_provider" "attestation_provider" {
  name                = "testattprov"
  resource_group_name = "testrg"
  location            = "westus"
}
```

### Debug Output/Panic Output

```shell
not applicable
```

### Expected Behaviour

The attestation provider should leave the attestation policies unspecified, or incorporate the policies into the Terraform state.

### Actual Behaviour

The attestation provider gets created, and the attestation policies are (automatically?) set, but **not visible in the Terraform state**. When updating the resource, Terraform recognizes that the policies are set and suggests to set them to `null`, as they differ from the state, causing an error.

The diff:
```
~ resource "azurerm_attestation_provider" "attestation_provider" ***
    [...]
    - open_enclave_policy_base64 = "***" -> null
    - sgx_enclave_policy_base64  = "***" -> null
    - tpm_policy_base64          = "***" -> null
    # (4 unchanged attributes hidden)
***
```

The resulting error when updating the policies to `null`:
```
Error: updating value for `open_enclave_policy_base64`: attestation.PolicyClient#Set: Failure sending request: StatusCode=500 -- Original Error: context deadline exceeded
```

### Steps to Reproduce

1. Take a Terraform configuration with an `azurerm_attestation_provider` and do not set the attestation policies explicitly.
2. Run `terraform init && terraform apply`
3. Check that the attestation policies are set (e.g. through the Azure portal) while they are not present in the Terraform state.
4. _Optionally_ apply an update to the resource, notice that Terraform wants to update the resource because of the incorrect state (and therefore diff) and see the `500` status code on the update call.

**Comment by ziyeqf** [comment]
Hi @msanft, thanks for opening the issue.

This is by design because If these properties are not specified during creation, default values are generated by Azure backend service. To use the default values, please add the following `lifecycle.ignore_changes` to your config. 
```
  lifecycle {
   ignore_changes = [
     "open_enclave_policy_base64",
     "sgx_enclave_policy_base64",
     "tpm_policy_base64",
   ]
  }
``` 
Then when you want to specify these values or remove them, you can just remove them from `ignore_changes` block and specify your values.

For further questions please leave comments, thanks!

**Comment by msanft** [comment]
Hey @ziyeqf, thanks for getting back so fast! 

We ended up ignoring these attributes. But shouldn't the values be initially set to `null` when creating the attestation provider, overwriting the defaults set by the Azure backend service?

If we apply a configuration twice without specifying the `ignore_changes` meta-argument, the second run fails because it doesn't seem possible to set these values to `null`. 

If that is the desired behaviour, feel free to close this issue.
