### ISSUE TITLE
Data sources like azurerm_key_vault_secret spam the logs with "will be read during apply"

### ISSUE THREAD

**Issue by hterik** [hashicorp/terraform-provider-azurerm#22009]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.58.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "keyVault" {
  name                = "...."
  resource_group_name = "...."
}

data "azurerm_key_vault_secret" "foo" {
  name         = "bar"
  key_vault_id = data.azurerm_key_vault.keyVault.id
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Terraform apply should print empty plan if it has already been previously applied.

`data` resources are by definition always read during apply.
It does not make sense to print this to log every time and it makes it very difficult to compare the plan on actual resources that should modify the cloud.

### Actual Behaviour

`terraform apply` or `terraform plan` always prints following on every single invocation. Even after repeated applies.
```

  # module.mymodule.data.azurerm_key_vault_secret.foo will be read during apply
  # (config refers to values not yet known)
 <= data "azurerm_key_vault_secret" "foo" {
      + content_type            = (known after apply)
      + id                      = (known after apply)
      + key_vault_id            = (known after apply)
      + name                    = "bar"
      + resource_id             = (known after apply)
      + resource_versionless_id = (known after apply)
      + tags                    = (known after apply)
      + value                   = (sensitive value)
      + version                 = (known after apply)
      + versionless_id          = (known after apply)
    }
```

### Steps to Reproduce

terraform apply

### References

See https://github.com/hashicorp/terraform/issues/25805 where Terraform explains that responsibility of this lies on providers and not in Terraform.

**Comment by wuxu92** [comment]
thanks @hterik filing this issue. Is there only the `key_vault_secret` with a diff in the plan? what about the `key_vault` resource itself? because I didnot reproduce the issue locally. my `terraform apply` output with no diff/changes.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2633022/d9860ba8-5b12-431f-a754-273bb0aba951)
