### ISSUE TITLE
Terraform uses wrong scope when trying to destroy a role defined in resource group scope

### ISSUE THREAD

**Issue by felix-wolfheimer** [hashicorp/terraform-provider-azurerm#2203]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.10

### Affected Resource(s)

* azurerm_role_definition
* azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_definition" "vc-role-policy-instance-management" {

  name               = "role-policy-instance-management"
  scope              = "${azurerm_resource_group.vc-resource-group.id}"

  permissions {
    actions     = ["Microsoft.Storage/*/read",
                   "Microsoft.Network/*/read",
                   "Microsoft.Compute/*/read",
                   "Microsoft.Network/virtualNetworks/*",
                   "Microsoft.Network/networkInterfaces/*",
                   "Microsoft.Compute/virtualMachines/*",
                   "Microsoft.Compute/images/*",
                   "Microsoft.Authorization/*/read"
                  ]
    not_actions = []
  }

  assignable_scopes = [
    "${azurerm_resource_group.vc-resource-group.id}",
  ]
}

resource "azurerm_role_assignment" "vc-role-assignment-instance-management" {

  scope              = "${azurerm_resource_group.vc-resource-group.id}"
  role_definition_id = "${azurerm_role_definition.vc-role-policy-instance-management.id}"
  principal_id       = "${lookup(azurerm_virtual_machine.vc-instance-frontend.identity[0], "principal_id")}"

}

```

### Debug Output
Subscription ID is obfuscated. Note that terraform tries to destroy the role on the subscription scope, NOT on the resource group scope where it was defined. The client has owner permissions on the resource group, but no permissions for the subscription. 

* azurerm_role_definition.vc-role-policy-instance-management: Error deleting Role Definition "e72dd176-cd5f-c47b-7284-1ea84a451495" at Scope "subscriptions/XXXX": authorization.RoleDefinitionsClient#Delete: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '0a1d0717-7d17-426b-909b-0dba50310bb6' with object id '0a1d0717-7d17-426b-909b-0dba50310bb6' does not have authorization to perform action 'Microsoft.Authorization/roleDefinitions/delete' over scope '/subscriptions/XXXX'."

### Expected Behavior

The role should have been deleted.

### Actual Behavior

Error message (permission denied)

### Steps to Reproduce

1. `Create a role with a resource group scope using azurerm_role_definition`
2. Run `terraform apply` to create the role.
3. Run `terraform destroy` to destroy the role.  

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
