### ISSUE TITLE
How to retrieve / copy ssh password for storage local user (sftp)

### ISSUE THREAD

**Issue by onenessboy** [hashicorp/terraform-provider-azurerm#22039]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

..

### Terraform Version

1.0.0

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_local_user

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "WestEurope"
}

resource "azurerm_storage_account" "example" {
  name                     = "example-account"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  is_hns_enabled           = true
}

resource "azurerm_storage_container" "example" {
  name                 = "example-container"
  storage_account_name = azurerm_storage_account.example.name
}

resource "azurerm_storage_account_local_user" "example" {
  name                 = "user1"
  storage_account_id   = azurerm_storage_account.example.id
  ssh_key_enabled      = true
  ssh_password_enabled = true
  home_directory       = "example_path"
  ssh_authorized_key {
    description = "key1"
    key         = local.first_public_key
  }
  ssh_authorized_key {
    description = "key2"
    key         = local.second_public_key
  }
  permission_scope {
    permissions {
      read   = true
      create = true
    }
    service       = "blob"
    resource_name = azurerm_storage_container.example.name
  }
}
```

### Debug Output/Panic Output

```shell
Not able to see azure generated ssh password for this local user.
```

### Expected Behaviour

wanted to copy / save this ssh generated password generated azure/terraform to text file on azure blob

### Actual Behaviour

Was trying to create a storage account, and tried to enable sftp (succeeded), now I need to create a new local user with option of ssh password, (in portal it password will be visible so that I can copy incase of manual creation), but when I create via terraform, loca user being added, but not able to see ssh password any where..

### Steps to Reproduce

terraform apply

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
