### ISSUE TITLE
azurerm_storage_account should not require a versioned key id

### ISSUE THREAD

**Issue by jsathler** [hashicorp/terraform-provider-azurerm#22069]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "default" {
  name                     = "xxxxxxxxxxx"
  resource_group_name      = azurerm_resource_group.default.name
  location                 = azurerm_resource_group.default.location
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Hot"
  min_tls_version          = "TLS1_2"
  is_hns_enabled = true

  network_rules {
    bypass         = ["AzureServices"]
    default_action = "Deny"
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.default.id]
  }

  customer_managed_key {
    key_vault_key_id          = azurerm_key_vault_key.stgaccount.versionless_id
    user_assigned_identity_id = azurerm_user_assigned_identity.default.id
  }

}
```

### Debug Output/Panic Output

```shell
Error: parsing "https://my-vault.vault.azure.net/keys/adf-key": expected a versioned ID but no version in "https://my-vault.vault.azure.net/keys/adf-key"
```

### Expected Behaviour

key_vault_key_id should accept keys with no version to enable automatic key rotation

### Actual Behaviour

Apply ends in an error because validation requires a versioned key id

### Steps to Reproduce

terraform init
terraform apply

### Important Factoids

N/A

### References

I've found a similar issue in https://github.com/hashicorp/terraform-provider-azurerm/issues/14069

**Comment by magodo** [comment]
@rcskosir I've tried above config in the latest provider (v3.61.0), it works with no issue. I've checked that since https://github.com/hashicorp/terraform-provider-azurerm/commit/2e5d2e69ce381b868c7c2959fb64ce2d9f742d15 (since v2.97.0), which introduced the property `key_vault_key_id`, things should be working. So I'm wondering whether this error is raised from the `azurerm_storage_account` resource, or something else?

**Comment by jsathler** [comment]
I'm sorry about this, I can confirm it is working on both v3.59.0 and v3.61.0 for azurerm_storage_account resource. 

When opening this issue I mentioned the wrong resource (the issue is happening with azurerm_data_factory resource).

I'm closing this issue and opening a new one for azurerm_data_factory.
