### ISSUE TITLE
azurerm_app_configuration_feature and azurerm_app_configuration_key showing incorrect changes required

### ISSUE THREAD

**Issue by matt-funda** [hashicorp/terraform-provider-azurerm#22088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_feature / azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 3.59.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "main" {
  name = "rg-terraform-appconf-test"
  location = "West Europe"
}

resource "azurerm_app_configuration" "appconf_test_one" {
  name                = "appconf-terraform-bug-test-one"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "standard"
}

resource "azurerm_app_configuration" "appconf_test_two" {
  name                = "appconf-terraform-bug-test-two"
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku                 = "standard"
}

resource "azurerm_role_assignment" "role_assignment_one" {
  scope                = azurerm_app_configuration.appconf_test_one.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_role_assignment" "role_assignment_two" {
  scope                = azurerm_app_configuration.appconf_test_two.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}

resource "azurerm_app_configuration_key" "config" {
  configuration_store_id = azurerm_app_configuration.appconf_test_two.id
  key                    = "config"
  value                  = "config"
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/matt-funda/f32b53d14a2e0821c45d1a236c0a86df
```

### Expected Behaviour

After the second run terraform should report no changes required.

### Actual Behaviour

After the second run the `azurerm_app_configuration_key.config` resource reports as needing to be recreated something like:

```
-/+ resource "azurerm_app_configuration_key" "config" {
      ~ configuration_store_id = "/subscriptions/075254db-75bd-4d17-b2a8-9fa8cdff9f65/resourceGroups/rg-appconf-test/providers/Microsoft.AppConfiguration/configurationStores/appconf-before-terraform" -> "/subscriptions/075254db-75bd-4d17-b2a8-9fa8cdff9f65/resourceGroups/rg-terraform-appconf-test/providers/Microsoft.AppConfiguration/configurationStores/appconf-terraform-bug-test-two" # forces replacement
      + content_type           = (known after apply)
      ~ etag                   = "W3G8hFJ9DIDn04hCSS0d2QU929D8utjHLEfX4i6goCE" -> (known after apply)
      ~ id                     = "https://appconf-terraform-bug-test-two.azconfig.io/kv/config?label=" -> (known after apply)
      - tags                   = {} -> null
        # (4 unchanged attributes hidden)
    }
```

### Steps to Reproduce

1. run terraform apply
2. run either terraform apply or terraform plan again and see the error

### References

I think this bug may have been introduced in  https://github.com/hashicorp/terraform-provider-azurerm/pull/21750 but I am not sure exactly.

**Comment by teowa** [comment]
Hi @matt-funda , this is duplicate with https://github.com/hashicorp/terraform-provider-azurerm/issues/22061, and is resolved in PR https://github.com/hashicorp/terraform-provider-azurerm/pull/22072.
Thanks.

**Comment by matt-funda** [comment]
Thanks @teowa! I saw that issue but didn't realise it was the same.
