### ISSUE TITLE
Insufficient features blocks  on <empty> line 0: (source code not available)At least 1 "features" blocks are required.

### ISSUE THREAD

**Issue by ashishstationcasinos** [hashicorp/terraform-provider-azurerm#22133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.10

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group

### Terraform Configuration Files

```hcl
Main.tf
terraform {
  required_version = ">= 1.0.10"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.59.0"
    }
  }
}
provider "azurerm" {
  alias                      = "production"
  subscription_id            = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  skip_provider_registration = true

  features {}
}

Resource.tf
resource "azurerm_resource_group" "rg" {
   name     = "it-rg"
  location = "westus"
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Insufficient features blocks
│ 
│   on <empty> line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
```

### Expected Behaviour

It need to provide plan to create a resource group

### Actual Behaviour

It give an error of Insufficient feature Block

**Comment by rcskosir** [comment]
@ashishstationcasinos, thank you for opening this issue. I believe the error is caused because there is a named provider in use (you gave the provider an alias "production"), but you did not specify the name of the provider in your resource. Can you try something like this below and let me know if it works?

```terraform
resource "azurerm_resource_group" "rg" {
  provider = azurerm.production 
  name     = "it-rg"
  location = "westus"
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with my above response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Comment by JacobCrawfordKamstrup** [comment]
Though this might be true, the error message is horrible and there is no way to know that this is the error.
