### ISSUE TITLE
Disk encryption set is removed with attached disks

### ISSUE THREAD

**Issue by antoine-axa** [hashicorp/terraform-provider-azurerm#22130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.4

### AzureRM Provider Version

3.60.0

### Affected Resource(s)/Data Source(s)

azurerm_disk_encryption_set

### Terraform Configuration Files

```hcl
encryption.tf in root module:

resource "azurerm_disk_encryption_set" "encryption" {
  count                     = local.create_encryption ? 1 : 0
  name                      = "${local.virtual_machine_name}_Encryption"
  resource_group_name       = data.azurerm_resource_group.virtualmachine.name
  location                  = var.location
  key_vault_key_id          = azurerm_key_vault_key.encryption[0].id
  auto_key_rotation_enabled = true
}

disks.tf in root module :

module "vm_disks" {
  source                     = ".//disks"
  vm_name                    = local.virtual_machine_name
  vm_size                    = var.vm_size
  virtual_machine_id         = local.virtual_machine_id
  resource_group_name        = data.azurerm_resource_group.virtualmachine.name
  location                   = var.location
disk_name                  = "${local.virtual_machine_name}_${local.data_disks[count.index].disk_name}"
  disk_size_gb               = local.data_disks[count.index].disk_size
  storage_account_type       = local.data_disks[count.index].disk_storage_account_type
  caching                    = local.data_disks[count.index].disk_caching
  lun                        = local.data_disks[count.index].disk_lun != null ? local.data_disks[count.index].disk_lun : count.index
  on_demand_bursting_enabled = local.data_disks[count.index].disk_bursting
  source_resource_id         = local.data_disks[count.index].disk_source_resource_id
  disk_write_accelerator     = local.data_disks[count.index].disk_write_accelerator
  disk_encryption_set_id     = var.disk_profiles.disk_cmk_encryption ? azurerm_disk_encryption_set.encryption[0].id : null
  disk_zone                  = local.disk_zonal ? var.disk_profiles.disk_availability_zones.disk_primary_zone : null
  depends_on                 = [time_sleep.wait_10_seconds]
}

main.tf in child module

resource "azurerm_managed_disk" "disk" {
  count                         = var.disk_zone == 0 ? 0 : 1
  name                          = var.disk_name
  resource_group_name           = var.resource_group_name
  location                      = var.location
  storage_account_type          = var.storage_account_type
  public_network_access_enabled = false
  create_option                 = var.create_option
  source_resource_id            = var.source_resource_id
  disk_size_gb                  = var.tier != null ? null : var.disk_size_gb
  tier                          = var.tier
  on_demand_bursting_enabled    = var.on_demand_bursting_enabled
  zone                          = var.disk_zone
  disk_encryption_set_id        = var.disk_encryption_set_id
  network_access_policy         = "DenyAll"
}
```

### Debug Output/Panic Output

```shell
Error: deleting Disk Encryption Set "Disk_Encryption" (Resource Group "XYZ"): performing Delete: diskencryptionsets.DiskEncryptionSetsClient#Delete: Failure sending request: StatusCode=0 -- Original Error: Code="OperationNotAllowed" Message="DiskEncryptionSet 'Disk_Encryption' is being used by resource 'Disk_Data123' and cannot be deleted."
```

### Expected Behaviour

Terraform should first unattach disks from the disk encryption set and then remove it.

### Actual Behaviour

Terraform try to delete the disk encryption set

### Steps to Reproduce

Disabling CMK by setting the disk_profiles.disk_cmk_encryption variable to false.

**Comment by myc2h6o** [comment]
Hi @antoine-axa this is the default behavior in Terraform, that the create/update of a resource is done after the operation of its dependency is done, including delete. This behavior could be reversed with [`create_before_destroy`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#create_before_destroy) lifecycle meta-argument. The detailed explanation could be found at [here](https://github.com/hashicorp/terraform/blob/main/docs/destroying.md#create-before-destroy). Could you try this and see if it can resolve your case?

**Comment by antoine-axa** [comment]
Hi @myc2h6o thank you for your answer. I thought that the update of a resource was done before destroying the resource on which it depends on, like with a destroy operation, it always destroy first dependencies and then the dependant resource.

However, I still tried to add a `create_before_destroy` lifecycle meta-argument in both the `azurerm_disk_encryption_set` and `azurerm_managed_disk` resources but it's not resolving the problem.

**Comment by myc2h6o** [comment]
@antoine-axa `create_before_destroy` needs to be there before the actual run which destroys the resource, thus you may need an extra run to only add this flag, and double check if it's added in the state like https://github.com/hashicorp/terraform-provider-azurerm/issues/18915#issuecomment-1302271078.

another similar issue: #15483
