### ISSUE TITLE
Import of role results in invalid id format

### ISSUE THREAD

**Issue by mark-jordanovic-lewis** [hashicorp/terraform-provider-azurerm#22156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.7, 1.2.9, 1.3.9, 1.4.6 & 1.5.0

### AzureRM Provider Version

2.40.0, 2.46.0, 3.55.0, 3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_role_definition

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "sub" {}

resource "azurerm_role_definition" "actor_role" {

}
```

### Debug Output/Panic Output

```shell
$ tf import azurerm_role_definition.actor_role /subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED


azurerm_role_definition.actor_role: Importing from ID "/subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED"...
data.azurerm_subscription.sub: Reading...
data.azurerm_subscription.sub: Read complete after 0s [id=/subscriptions/REDACTED]
╷
│ Error: could not parse Role Definition ID, invalid format "/subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED"
│
│
╵
```

### Expected Behaviour

The resource should import.

### Actual Behaviour

There was an error.

### Steps to Reproduce

Define the resource, find an appropriate id, try to import it.

### References

[This issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/8426) is the exact same.

Reintroduction of already fixed behaviour.

**Comment by wuxu92** [comment]
@rcskosir the id of role_definition should be like `/subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED|{scope}` in the current azurerm version. that `/subscriptions/REDACTED/providers/Microsoft.Authorization/roleDefinitions/REDACTED` format is before #6107.  did you just update the azurerm from a very old version to 3.61.0?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @wuxu92‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
