### ISSUE TITLE
azurerm provider v3.61.0 breaks AKS deployment with new azure overlay CNI

### ISSUE THREAD

**Issue by sca-ai** [hashicorp/terraform-provider-azurerm#22151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.0

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "NA" {
  name                = "NA"
  location            = "NA"
  resource_group_name = "NA"

  node_resource_group        = "NA"
  private_cluster_enabled    = true
  private_dns_zone_id        = "NA"
  dns_prefix_private_cluster = "NA"
  key_vault_secrets_provider {
    secret_rotation_enabled  = false
    secret_rotation_interval = "3m"
  }

  kubelet_identity {
    client_id                 = azurerm_user_assigned_identity.NA.client_id
    object_id                 = azurerm_user_assigned_identity.NA.principal_id
    user_assigned_identity_id = azurerm_user_assigned_identity.NA.id
  }

  default_node_pool {
    name                = "default"
    node_count          = 2
    vm_size             = "Standard_DC2as_v5"
    max_pods            = 250
    vnet_subnet_id      = "NA"
    enable_auto_scaling = false
  }

  network_profile {
    load_balancer_sku   = "standard"
    network_plugin      = "azure"
    network_plugin_mode = "Overlay"
    pod_cidr            = "10.244.0.0/16"  // for further restrictions see https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.NA.id]
  }

  tags = NA
}
```

### Debug Output/Panic Output

```shell
module.NA.azurerm_kubernetes_cluster.NA: Creating...
╷
│ Error: `pod_cidr` and `azure` cannot be set together unless specifying `network_plugin_mode` to `overlay`
│
│   with module.NA.azurerm_kubernetes_cluster.NA,
│   on modules/NA/aks.tf line 5, in resource "azurerm_kubernetes_cluster" "NA":
│    5: resource "azurerm_kubernetes_cluster" "NA" {
│
╵
```

### Expected Behaviour

AKS cluster should be created with overlay network.

### Actual Behaviour

TF planning phase runs successfully, but TF apply dies with above error message.

### Steps to Reproduce

run TF client 1.5.0 and switch azurerm provider between 3.61.0 (fails) and 3.59.0 (works)

### Important Factoids

AKS cluster with overlay network work in new azure CNI works on azurerm provider 3.59.0.

**Comment by AntoineAtLeocare** [comment]
I just opened this issue: <https://github.com/hashicorp/go-azure-sdk/issues/507>. Is there a link with this one?
