### ISSUE TITLE
Typo in Docs for azurerm_mssql_database

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#22159]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

N/A

### Actual Behaviour

N/A

### Steps to Reproduce

N/A

### Important Factoids

 N/A

### References

In Datasource documentation there appears to be a cut and paste error.

Under Argument Reference, for the server_id, the docs say.

server_id  - The id of the MS SQL Server on which to create the database.

Because this is a datasource, I'm going to assume that this is incorrect and instead should read more like 

server_id  - The id of the MS SQL Server on which to read the database.

**Comment by sinbai** [comment]
@DevopsMercenary thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/22166)has been submitted to fix it.
