### ISSUE TITLE
kubernetes_cluster and azurerm_kubernetes_cluster_node_pool add possibility for imageMinimumGCAge kubelet_config

### ISSUE THREAD

**Issue by rgarcia89** [hashicorp/terraform-provider-azurerm#22180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it is only possible to define the following two image garbage collection tasks within the terraform provider.

[image_gc_high_threshold](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#image_gc_high_threshold) - (Optional) Specifies the percent of disk usage above which image garbage collection is always run. Must be between 0 and 100. Changing this forces a new resource to be created.

[image_gc_low_threshold](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#image_gc_low_threshold) - (Optional) Specifies the percent of disk usage lower than which image garbage collection is never run. Must be between 0 and 100. Changing this forces a new resource to be created.

However there is another very important definition that should be implemented.
imageMinimumGCAge - imageMinimumGCAge is the minimum age for an unused image before it is garbage collected. Default: "2m" (via https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/)

The definition of this value allows to define which images should be retained by the timing parameters defined with by `image_gc_high_threshold` and `image_gc_low_threshold`. 

### New or Affected Resource(s)/Data Source(s)

kubernetes_cluster, azurerm_kubernetes_cluster_node_pool

**Comment by stephybun** [comment]
Thanks for this feature request @rgarcia89.

It looks like the API doesn't expose/support this value - you'll need to raise this request over on the [AKS repo](https://github.com/Azure/AKS) before we can look into adding this.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on the [AKS repo](https://github.com/Azure/AKS), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
