### ISSUE TITLE
Warnings for azurerm_cognitive_deployment documentation

### ISSUE THREAD

**Issue by randompixel** [hashicorp/terraform-provider-azurerm#22198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was having issues with `azurerm_cognitive_deployment` which was giving me this error. 
```
CreateOrUpdate: unexpected status 400 with error: InvalidResourceProperties: The specified scale type 'Standard' of account deployment is not supported by the model 'text-davinci-003'.
```
This was causing me confusion as "scale type" can only be set to `Standard` in Terraform so I wasn't sure what to do.

What this actually turned out to be was I was trying to deploy `text-davinci-003` to `uksouth` which isn't supported (as per https://learn.microsoft.com/en-us/azure/cognitive-services/openai/concepts/models#gpt-3-models)

Is there anything that could be added to the documentation here to warn users that not all models can be deployed to all regions?

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

**Comment by lonegunmanb** [comment]
@randompixel Thanks for opening this pr, I've tried the following config and it worked for me:

```hcl

**Comment by jayendranarumugam** [comment]
Hi @lonegunmanb , First of thanks for your PR :) I have tried the new version `3.64.0` and noticed few points 

- When i used  newer version 0613 on `gpt-35-turbo` it looks like below (perfect) but when i checked in the portal the version is pointing as old (0301)
```
      + model {
          + format  = "OpenAI"
          + name    = "gpt-35-turbo"
          + version = "0613"
        }

      + scale {
          + capacity = 120
          + type     = "Standard"
        }
``` 

- I manually updated the version on the portal, and ran the terraform again now it shows like below
```
      ~ model {
            name    = "gpt-35-turbo"
          ~ version = "0301" -> "0613"
            # (1 unchanged attribute hidden)
        }
```
but I got the error like  **Error: doesn't support update**  (I can able to update the version from the portal successfully) 


Did this case work for you during the development ?

**Comment by kirk-marple** [comment]
@lonegunmanb I can concur there's something wrong still, and can't rerun a deployment or I get the same problem as @jayendranarumugam where it resets it back to 0301 and then won't allow update.

**Comment by lonegunmanb** [comment]
Thanks @jayendranarumugam and @kirk-marple for letting me know the issue, I'll try to reproduce it on my side.

**Comment by jayendranarumugam** [comment]
@lonegunmanb I have created https://github.com/hashicorp/terraform-provider-azurerm/issues/22501 if you like to work on it. Thanks !

**Comment by lonegunmanb** [comment]
Thanks @jayendranarumugam, I'll take a look!

**Comment by RyanRogersMicrosoft** [comment]
Has anyone seen this error: 
`Message: The specified scale type 'Standard' of account deployment is not supported by the model 'gpt-35-turbo'.`
from these configs:
```
openai.api_version = "2023-05-15"
model_name = "gpt-35-turbo"
deployment_name = "gpt-35-turbo"
model_version = "0613"
```


For ref:
`    deployment = client.deployments.begin_create_or_update(
        resource_group_name=cog_rg,
        account_name=openai_instance_name,
        deployment_name=deployment_name,
        content_type = 'application/json',
        deployment={
            "properties": {
            "model": {
                "format": "OpenAI",
                "name": model,
                "version": model_version
            },
            "scaleSettings": {
                "scaleType": "Standard"
            }
            },
            "sku": {
                "capacity": 1
            }
        }
    )`
And when I remove the scaleSettings section above I get:
Code: InvalidResourceProperties
Message: The scale settings of account deployment is invalid.
