### ISSUE TITLE
azurerm_site_recovery_replicated_vm failover_test network configuration failed 

### ISSUE THREAD

**Issue by Jeromeverb** [hashicorp/terraform-provider-azurerm#22193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.0

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version  = ">=3.50.0"
      configuration_aliases = [ azurerm.secondary, azurerm.hub, azurerm.prod ]
    }
  }
  required_version = ">= 1.0.5"
}


provider "azurerm" {
    features {}
    alias           = "secondary"
    subscription_id = var.subscription_secondary
}

provider "azurerm" {
    features {}
    alias           = "prod"
    subscription_id = var.subscription_prod
}

#################################SECONDARY#####################################
data "azurerm_resource_group" "primary" {
  provider = azurerm.prod
  name = var.resource_group_vm
}

data "azurerm_virtual_machine" "main" {
  provider = azurerm.prod
  name                = "${var.vm_fileserver_name}"
  resource_group_name = var.resource_group_vm
}

data "azurerm_network_interface" "main" {
  provider = azurerm.prod

  name                = "${var.vm_fileserver_name}-NIC"
  resource_group_name = var.resource_group_vm
}

data "azurerm_managed_disk" "OS" {
  provider = azurerm.prod
  name                = "${var.vm_fileserver_name}-OS"
  resource_group_name = var.resource_group_vm
}

data "azurerm_managed_disk" "data01" {
  provider = azurerm.prod
  name                = "${var.vm_fileserver_name}-DATA01"
  resource_group_name = var.resource_group_vm
}

data "azurerm_storage_account" "main" {
provider = azurerm.prod
name = var.storage_account_name
resource_group_name = var.storage_account_rg
}

#################################SECONDARY#####################################
data "azurerm_resource_group" "secondary" {
  provider = azurerm.secondary
  name =var.resource_group_secondary_name
}

data "azurerm_virtual_network" "secondary" {
  provider            = azurerm.secondary
  name                = var.virtual_network_secondary_name
  resource_group_name = data.azurerm_resource_group.secondary.name
}

data "azurerm_subnet" "secondary" {
  provider             = azurerm.secondary
  name                 = var.virtual_network_subnet_secondary_name
  resource_group_name  = data.azurerm_resource_group.secondary.name
  virtual_network_name = data.azurerm_virtual_network.secondary.name
}

########################TEST FAILOVER##############################################
data "azurerm_resource_group" "secondary_test" {
  provider = azurerm.secondary
  name =var.resource_group_secondary_name_test

}
data "azurerm_virtual_network" "secondary_test" {
  provider            = azurerm.secondary
  name                = var.virtual_network_secondary_name_test
  resource_group_name = data.azurerm_resource_group.secondary_test.name
}

data "azurerm_subnet" "secondary_test" {
  provider             = azurerm.secondary
  name                 = var.virtual_network_subnet_secondary_name_test
  resource_group_name  = data.azurerm_resource_group.secondary_test.name
  virtual_network_name = data.azurerm_virtual_network.secondary_test.name
}
######################################################################

data "azurerm_recovery_services_vault" "vault" {
  provider = azurerm.secondary
  name = var.recovery_services_vault_name
  resource_group_name = var.resource_group_infrabackup_secondary_name
}

data "azurerm_site_recovery_replication_policy" "policy" {
  provider = azurerm.secondary
  name                = "rrp_it_neu_prod_24_0_sql"
  recovery_vault_name = var.recovery_services_vault_name
  resource_group_name = var.resource_group_infrabackup_secondary_name
}

output "policyid" {
  value = data.azurerm_site_recovery_replication_policy.policy.id
}
######################################################################
######################################################################


resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
    provider = azurerm.secondary
  name                                      = "${var.vm_fileserver_name}"
  resource_group_name                       = var.resource_group_infrabackup_secondary_name
  recovery_vault_name                       = data.azurerm_recovery_services_vault.vault.name
  source_recovery_fabric_name               = var.azurerm_site_recovery_fabric_primary_name
  
  source_vm_id                              = data.azurerm_virtual_machine.main.id
  recovery_replication_policy_id            = var.azurerm_site_recovery_replication_policy_id
  source_recovery_protection_container_name = var.azurerm_site_recovery_protection_container_name

  target_resource_group_id                = data.azurerm_resource_group.secondary.id
  target_recovery_fabric_id               = var.azurerm_site_recovery_fabric_secondary_id
  target_recovery_protection_container_id = var.azurerm_site_recovery_protection_container_id
   
  managed_disk {
    disk_id                    = data.azurerm_managed_disk.OS.id
    staging_storage_account_id = data.azurerm_storage_account.main.id
    target_resource_group_id   = data.azurerm_resource_group.secondary.id
    target_disk_type           = var.disk_os_type
    target_replica_disk_type   = var.disk_os_replica_type
  }

  managed_disk {
    disk_id                    = data.azurerm_managed_disk.data01.id
    staging_storage_account_id = data.azurerm_storage_account.main.id
    target_resource_group_id   = data.azurerm_resource_group.secondary.id
    target_disk_type           = var.disk_data_type_01
    target_replica_disk_type   = var.disk_data_replica_type_01
  }
  

  target_network_id       = data.azurerm_virtual_network.secondary.id
  test_network_id         = data.azurerm_virtual_network.secondary_test.id

  network_interface {
    source_network_interface_id = data.azurerm_network_interface.main.id
    target_subnet_name            = var.virtual_network_subnet_secondary_name
    target_static_ip = var.target_static_ip
    failover_test_static_ip = var.target_static_ip_test
    failover_test_subnet_name = var.virtual_network_subnet_secondary_name_test

    
  }

     timeouts {
    create = "1440m"
    update = "1440m"
    read =  "60m"
    delete = "240m"
  }
  

}
```

### Debug Output/Panic Output

```shell
azurerm_site_recovery_replicated_vm.vm-replication: Still creating... [1h12m43s elapsed]
╷
│ Error: updating replicated vm VMTESTCSEB (vault VAULT-XXXX-BACKUP): polling after Update: Code="28020" Message="The requested operation failed."
│
│   with azurerm_site_recovery_replicated_vm.vm-replication,
│   on vm_replication.tf line 2, in resource "azurerm_site_recovery_replicated_vm" "vm-replication":
│    2: resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
│
```

### Expected Behaviour

what terraform planned to do:
Terraform will perform the following actions:

  # azurerm_site_recovery_replicated_vm.vm-replication will be created
  + resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
      + id                                        = (known after apply)
      + managed_disk                              = [
          + {
              + disk_id                       = "/subscriptions/ID_SUB_FR/resourceGroups/RG-PRIMARY/providers/Microsoft.Compute/disks/VMTESTCSEB-DATA01"
              + staging_storage_account_id    = "/subscriptions/ID_SUB_FR/resourceGroups/RGstorageaccountFR/providers/Microsoft.Storage/storageAccounts/storageaccountfortest"
              + target_disk_encryption        = []
              + target_disk_encryption_set_id = ""
              + target_disk_type              = "Premium_LRS"
              + target_replica_disk_type      = "Premium_LRS"
              + target_resource_group_id      = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-SECONDARY-NEU"
            },
          + {
              + disk_id                       = "/subscriptions/ID_SUB_FR/resourceGroups/RG-PRIMARY/providers/Microsoft.Compute/disks/VMTESTCSEB-OS"
              + staging_storage_account_id    = "/subscriptions/ID_SUB_FR/resourceGroups/RGstorageaccountFR/providers/Microsoft.Storage/storageAccounts/storageaccountfortest"
              + target_disk_encryption        = []
              + target_disk_encryption_set_id = ""
              + target_disk_type              = "Premium_LRS"
              + target_replica_disk_type      = "Premium_LRS"
              + target_resource_group_id      = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-SECONDARY-NEU"
            },
        ]
      + name                                      = "VMTESTCSEB"
      + network_interface                         = [
          + {
              + failover_test_public_ip_address_id = (known after apply)
              + failover_test_static_ip            = "aa.aaa.aaa.aaa"
              + failover_test_subnet_name          = "SUB-SECONDARY-TESTFAILOVER"
              + is_primary                         = false
              + recovery_public_ip_address_id      = ""
              + source_network_interface_id        = "/subscriptions/ID_SUB_FR/resourceGroups/RG-PRIMARY/providers/Microsoft.Network/networkInterfaces/VMTESTCSEB-NIC"
              + target_static_ip                   = "bb.bbb.bbb.bbb"
              + target_subnet_name                 = "SUB-SECONDARY-FAILOVER"
            },
        ]
      + recovery_replication_policy_id            = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-VAULTRECOVERY-NEU/providers/Microsoft.RecoveryServices/vaults/VAULTRECOVERY-NEU/replicationPolicies/rrp_it_neu_prod_24_0_sql"
      + recovery_vault_name                       = "VAULTRECOVERY-NEU"
      + resource_group_name                       = "RG-VAULTRECOVERY-NEU"
      + source_recovery_fabric_name               = "source_recovery_fabric_name-francecentral"
      + source_recovery_protection_container_name = "primary-protection-container"
      + source_vm_id                              = "/subscriptions/ID_SUB_FR/resourceGroups/RG-PRIMARY/providers/Microsoft.Compute/virtualMachines/VMTESTCSEB"
      + target_network_id                         = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-SECONDARY-NEU/providers/Microsoft.Network/virtualNetworks/VNET_SECONDARY_FAILOVER"
      + target_recovery_fabric_id                 = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-VAULTRECOVERY-NEU/providers/Microsoft.RecoveryServices/vaults/VAULTRECOVERY-NEU/replicationFabrics/source_recovery_fabric_name-northeurope"
      + target_recovery_protection_container_id   = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-VAULTRECOVERY-NEU/providers/Microsoft.RecoveryServices/vaults/VAULTRECOVERY-NEU/replicationFabrics/source_recovery_fabric_name-northeurope/replicationProtectionContainers/secondary-protection-container"
      + target_resource_group_id                  = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-SECONDARY-NEU"
      + test_network_id                           = "/subscriptions/ID_SUB_NEU/resourceGroups/RG-SECONDARY-NEU-TEST/providers/Microsoft.Network/virtualNetworks/VNET_SECONDARY_FAILOVER-TEST"
      + unmanaged_disk                            = []

      + timeouts {
          + create = "1440m"
          + delete = "240m"
          + read   = "60m"
          + update = "1440m"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

### Actual Behaviour

on error is raising:
│ Error: updating replicated vm VMTESTCSEB (vault VAULT-IT-NEU-PROD-INFRA-BACKUP): polling after Update: Code="28020" Message="The requested operation failed."
│
│   with azurerm_site_recovery_replicated_vm.vm-replication,
│   on vm_replication.tf line 2, in resource "azurerm_site_recovery_replicated_vm" "vm-replication":
│    2: resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
│

In Azure The replication is working and configured except for Subnet and testfailover IP. 
The VNET for testfailover is ok
Manualy it's possible to set the expected testfailover subnet and IP.

Another Terraform apply Plan: 1 to add, 0 to change, 1 to destroy. 

### Steps to Reproduce

terraform apply

### References

no

**Comment by ziyeqf** [comment]
Hi @Jeromeverb, thanks for opening this issue.

Per the config you provided, I can find the resource `azurerm_site_recovery_network_mapping`, could you please add it and give it another try? Details about it could be found [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/site_recovery_network_mapping)

For any further questions please leave comments.

**Comment by Jeromeverb** [comment]
Hi @ziyeqf thanks for your response.

I don't have issue with failover network configuration only in test failover.

For failover we use azurerm_route_table and subnet association:

resource "azurerm_route_table" "secondary" {
  provider = azurerm.secondary
  name                          = var.routetable_name
  location                      = var.location_secondary
  resource_group_name           = data.azurerm_resource_group.secondary.name
  disable_bgp_route_propagation = var.routetable_disable_bgp
    depends_on = [
      azurerm_virtual_network.secondary
  ]

  route {
      name                   = var.route_namea
      address_prefix         = var.route_adress_prefixa
      next_hop_type          = var.route_next_hop_typea
      next_hop_in_ip_address = data.azurerm_firewall.mainhub.ip_configuration.0.private_ip_address
  }

  route {
      name                   = var.route_nameb
      address_prefix         = var.route_adress_prefixb
      next_hop_type          = var.route_next_hop_typeb
      next_hop_in_ip_address = data.azurerm_firewall.mainhub.ip_configuration.0.private_ip_address
  }

  route {
      name           = var.route_namec
      address_prefix = var.route_adress_prefixc
      next_hop_type  = var.route_next_hop_typec
  }

  tags                = module.tags.datamap
}

resource "azurerm_subnet_route_table_association" "secondary" {
  provider = azurerm.secondary
  subnet_id      = azurerm_subnet.secondary.id
  route_table_id = azurerm_route_table.secondary.id
  depends_on = [
    azurerm_route_table.secondary, azurerm_subnet.secondary
  ]
}

And we have the same for TESTfailover (routable and association).

I don't see how to use azurerm_site_recovery_network_mapping for secondarynetwork **and** secondary testnetwork

**Comment by Jeromeverb** [comment]
Thanks a lot
