### ISSUE TITLE
azurerm_marketplace_agreement failing in v3.62.0

### ISSUE THREAD

**Issue by mykenoein** [hashicorp/terraform-provider-azurerm#22256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### AzureRM Provider Version

3.62.0

### Affected Resource(s)/Data Source(s)

azurerm_marketplace_agreement

### Terraform Configuration Files

```hcl
resource "azurerm_marketplace_agreement" "ciscosdwan" {
  publisher = "cisco"
  offer     = "cisco_cloud_vwan_app"
  plan      = "cisco_sdwan_vwan_nva_app"
}
```

### Debug Output/Panic Output

```shell
(I replaced our subscription ID with ########-####-####-####-############)

LOGS:

Error: parsing "/subscriptions/########-####-####-####-############/providers/Microsoft.MarketplaceOrdering/agreements/cisco/offers/cisco_cloud_vwan_app/plans/cisco_sdwan_vwan_nva_app": parsing the OfferPlan ID: the number of segments didn't match

Expected a OfferPlan ID that matched (containing 12 segments):
> /subscriptions/12345678-1234-9876-4563-123456789012/providers/Microsoft.MarketplaceOrdering/offerTypes/virtualMachine/publishers/publisherIdValue/offers/offerIdValue/plans/planIdValue

However this value was provided (which was parsed into 0 segments):

> /subscriptions/########-####-####-####-############/providers/Microsoft.MarketplaceOrdering/agreements/cisco/offers/cisco_cloud_vwan_app/plans/cisco_sdwan_vwan_nva_app

The following Segments are expected:

* Segment 0 - this should be the literal value "subscriptions"
* Segment 1 - this should be the UUID of the Azure Subscription
* Segment 2 - this should be the literal value "providers"
* Segment 3 - this should be the name of the Resource Provider [for example 'Microsoft.MarketplaceOrdering']
* Segment 4 - this should be the literal value "offerTypes"
* Segment 5 - this should be the literal value "virtualMachine"
* Segment 6 - this should be the literal value "publishers"
* Segment 7 - this should be the user specified value for this publisherId [for example "publisherIdValue"]
* Segment 8 - this should be the literal value "offers"
* Segment 9 - this should be the user specified value for this offerId [for example "offerIdValue"]
* Segment 10 - this should be the literal value "plans"
* Segment 11 - this should be the user specified value for this planId [for example "planIdValue"]

The following Segments were parsed:

* Segment 0 - not found
* Segment 1 - not found
* Segment 2 - not found
* Segment 3 - not found
* Segment 4 - not found
* Segment 5 - not found
* Segment 6 - not found
* Segment 7 - not found
* Segment 8 - not found
* Segment 9 - not found
* Segment 10 - not found
* Segment 11 - not found


  with azurerm_marketplace_agreement.ciscosdwan[0],
  on marketplace_agreement.tf line 1, in resource "azurerm_marketplace_agreement" "ciscosdwan":
   1: resource "azurerm_marketplace_agreement" "ciscosdwan" {
```

### Expected Behaviour

No error. No changes.

### Actual Behaviour

Terraform plan is failing even though no changes were made in our code. The only change is the azurerm provider version since we set it to use the latest. It's passing if I explicitly use v3.61.0.

### Steps to Reproduce

terraform plan

### Important Factoids

This seems to happen only when there is already an existing marketplace agreement created using previous version of azurerm provider. Error does not show when creating new marketplace agreement resource or when fetching as datasource

**Comment by calloes** [comment]
I have this issue also against the Cisco CSR 1000v marketplace agreeement.

**Comment by tombuildsstuff** [comment]
hey @calloes @mykenoein 

Thanks for reporting this / apologies for the regression here.

We've taken a look into this and have opened #22264 which both reverts to using the older Resource ID format and the older API version - since this resource is pretty wildly used we're going to be releasing a patch version of the Provider later today which includes this fix, but in the interim you should be able to pin to using the last release using:

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "=3.61.0"
    }
  }
}
```

Thanks!
