### ISSUE TITLE
Support for Certificate Transparency and Certificate Type in azurerm_key_vault_certificate

### ISSUE THREAD

**Issue by gittyNico** [hashicorp/terraform-provider-azurerm#22254]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

please add the possibility to set issuer settings for Certificate Transparency and Certificate Type. In my case GlobalSign does not support Certificate Transparency which defaults to true.

### New or Affected Resource(s)/Data Source(s)

azurerm_key_vault_certificate

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_certificate" "example" {
  name         = "issuer-cert"
  key_vault_id = azurerm_key_vault.example.id

  certificate_policy {    
    issuer_parameters {
      name = "Globalsign"
      certificate_transparency = false
      certificate_type = "OV-SSL"
    }
    ...
  }
}
```

### References

[MSGraph Reference](https://learn.microsoft.com/en-us/rest/api/keyvault/certificates/create-certificate/create-certificate?tabs=HTTP#issuerparameters)
[MS Docs](https://learn.microsoft.com/en-us/azure/key-vault/certificates/about-certificates#certificate-policy)

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this is a duplicate like you mentioned in your comment above. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of the existing open ones.
