### ISSUE TITLE
Disabling a MS Purview Account's Event Hub Namespace through the portal causes Managed Event Hub to drop and unable to reconcile against the TF state file.

### ISSUE THREAD

**Issue by alvincmah** [hashicorp/terraform-provider-azurerm#22269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.7

### AzureRM Provider Version

3.29.1

### Affected Resource(s)/Data Source(s)

azurerm_purview_account

### Terraform Configuration Files

```hcl
resource "azurerm_purview_account" "mypurview2-pview" {
 name                        = "${var.ENV}-mypurview2-pview"
 location                    = azurerm_resource_group.mypurview2-rg.location
 resource_group_name         = azurerm_resource_group.mypurview2-rg.name
 managed_resource_group_name = "${var.ENV}-mypurview2-rgmg"
 tags                        = {}
 identity {
   type = "SystemAssigned"
 }
 lifecycle {
   ignore_changes = [
		managed_resources
   ] 
 }
}
```

### Debug Output/Panic Output

```shell
please see actual behavior
```

### Expected Behaviour

with the lifecycle change it should ignore managed_resources section which ignores the change around the managed event hub.

### Actual Behaviour

xxxx = redacted

What ends up happening is that through the azure portal, if the event hubs namespace name is disabled then the event hub is dropped. 

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/60337260/3cc8ac23-c765-460c-b33f-0855309fa147)

Then when you rerun TF, it results in the message below because it doesn't understand that the event hub is dropped.  But you can't explicitly recreate this because the managed event hub is managed through the creation of the azurerm_purview_account.  

Account Name: "xxxx "): account.AccountClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="21000" Message="Managed Event Hub does not exist for account xxxx ." Details=[]

Once the event hub is dropped there is no way to recover that event hub.  And you cannot run a TF plan nor apply.

**Comment by myc2h6o** [comment]
Hi @alvincmah the managed event hub is unfortunately not able to be added back according to the document: https://learn.microsoft.com/azure/purview/configure-event-hubs-for-kafka#configure-event-hubs
>If you disable the managed Event Hubs resource you won't be able to re-enable a managed Event Hub resource. You will only be able to configure your own Event Hubs.

As for the customer-managed event hub, it is done with the "Kafka configuration" tab. The API is missing currently in the Azure Spec repo, I've opened https://github.com/Azure/azure-rest-api-specs/issues/24571 to request Azure team to add it. We'll be able to add the support after the API is ready.

**Comment by bensalem22** [comment]
The managed event hub should no longer created for Purview accounts provisioned after Dec. 15th 2022. Is there a way to disable the creation of the EH with Terraform?
