### ISSUE TITLE
Missing namespace_id in data source azurerm_servicebus_queue

### ISSUE THREAD

**Issue by krzysztof-madej** [hashicorp/terraform-provider-azurerm#22282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_queue

### Terraform Configuration Files

```hcl
data "azurerm_servicebus_queue" "servicebus_queues" {
  count               = length(local.servicebus_queues)
  name                = local.servicebus_queues[count.index].queue_name
  resource_group_name = local.servicebus_queues[count.index].resource_group_name
  namespace_name      = local.servicebus_queues[count.index].namespace
}
```

### Debug Output/Panic Output

```shell
╷
│ Warning: Argument is deprecated
│ 
│   with module.ave_module.module.validation.data.azurerm_servicebus_queue.servicebus_queues_validation,
│   on .terraform/modules/ave_module/validation/main.tf line 35, in data "azurerm_servicebus_queue" "servicebus_queues_validation":
│   35:   resource_group_name = local.servicebus_queues_validation[count.index].resource_group_name
│ 
│ `resource_group_name` will be removed in favour of the property
│ `namespace_id` in version 4.0 of the AzureRM Provider.
│ 
│ (and one more similar warning elsewhere)
╵
```

### Expected Behaviour

It should be possible to set `namespace_id` or azurerm should not display this warning.

### Actual Behaviour

There is no argument `namespace_id` in data source `azurerm_servicebus_queue`. It is available in resource but not in data source.

**Comment by xiaxyi** [comment]
Thanks @krzysztof-madej for raising this issue.

The situation is the 3.0 provider use `resource_group_name ` and `namespace_name ` to get the servicebus queue under the specified servicebus namespace and in 4.0 provider, user doesn't need to use the resoure group+namespace name to locate the servicebus namespace, instead, they can use the servicebus namespace id directly. 

Even though we are introducing the id in current and future provider, we can't just remove the two properties (`resource_group_name ` and `namespace_name `) from the 3.0 provider as it will cause breaking changes to users who are using them in their config. 

You can use the namespace id directly and the warning just to notify user about the property deprecation in 4.0 provider so they can take some actions.

sample code:
```
data "azurerm_servicebus_queue" "test" {
  name         = azurerm_servicebus_queue.test.name
  namespace_id = azurerm_servicebus_namespace.test.id
}
```

I will modify the documentation.

**Comment by xiaxyi** [comment]
@krzysztof-madej Good day, you can track the doc update via mention PR. Feel free to let me know if you have any questions.
