### ISSUE TITLE
azurerm_function_app_function does not allow underscore in name but Azure does

### ISSUE THREAD

**Issue by niven01** [hashicorp/terraform-provider-azurerm#22294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.0

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_function_app_function

### Terraform Configuration Files

```hcl
resource "azurerm_function_app_function" "my_function" {
  name            = "Funtion_name"
  config_json     = "{\"bindings\":[{\"authLevel\":\"function\",\"methods\":[\"get\"],\"name\":\"req\",\"type\":\"httpTrigger\"}],\"configurationSource\":\"attributes\",\"disabled\":false,\"entryPoint\":\"my.entrypoit.Function_name\",\"generatedBy\":\"Microsoft.NET.Sdk.Functions.Generator-4.1.1\",\"scriptFile\":\"../bin/ABC.APIs.PMIS.EMPX.dll\"}"
  function_app_id = "/subscriptions/xxxxxxx-xxxxxxx-xxxxxxxxx-xxxxxx/resourceGroups/my-resource-group/providers/Microsoft.Web/sites/myfunctionapp"

}
```

### Debug Output/Panic Output

```shell
Error: "name" must start with a letter, may only contain alphanumeric characters and dashes and up to 128 characters in length
```

### Expected Behaviour

I am importing an existing resource into Terraform. The name has been set in the portal with an underscore.

When running a Terraform Validate I'm expecting my code to pass with

Success! The configuration is valid.

### Actual Behaviour

 Error: "name" must start with a letter, may only contain alphanumeric characters and dashes and up to 128 characters in length
│
│   with azurerm_function_app_function.my_function,
│   on RG_abp-ais-pmis-empx-uks-rg01.tf line 73, in resource "azurerm_function_app_function" "my_function":
│   73:   name            = "Function_name"

### Steps to Reproduce

- Create code in Terraform for the existing resource
- run: `terraform validate`

**Comment by hasanciftci** [comment]
Same issue here!

**Comment by xiaxyi** [comment]
Thanks @niven01 for raising this issue, the fix is included in the mentioned pr and you can track it for a progress.
