### ISSUE TITLE
Support for ignore_tags for azurerm provider 

### ISSUE THREAD

**Issue by Sharono123** [hashicorp/terraform-provider-azurerm#22304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

My customer has a problem when he sets a new tag (for example:  “created-date”)  automatically via Azure Policy.
For example : [https://jrudlin.github.io/2019-07-18-azure-policy-createdon-date/](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjrudlin.github.io%2F2019-07-18-azure-policy-createdon-date%2F&data=05%7C01%7CSharon.Oliar%40microsoft.com%7C8a7df3ca87f942bc079e08db7723b75d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638234767997108427%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C7000%7C%7C%7C&sdata=Vi%2F7bC%2BmIPTvDUHix62ocqItGBpJBa1qrMsTzIMgU60%3D&reserved=0)
 
The problem is with IaC (Terraform) processes. 
When he runs “terraform plan“ after he creates a new resource via Terraform, he gets difference (because of the new tag), so we need to find a generic solution that won’t cause to a difference in terraform flows.
For example, in AWS he can define the following to solve this issue.
 
provider "aws" {
 
    ignore_tags {
      # Ignore tags added by the "Resource Auto Tagger" tool
      keys = ["Created By", "Creation Date", "IAM Role Name", "IAM User Name"]
    }
}
 
But in Azure he needs to do it per resource declaration.
 
Do you know if we have any plans to do the same in Azure like it is in AWS ?
Regards, 
Sharon 

### New or Affected Resource(s)/Data Source(s)

azurerm_provider

**Comment by humanascode** [comment]
This is a good suggestion. Today, the only way to achieve this in AzureRM is by using a lifecycle block with "Ignore Changes" for tags on each and every resource. Many customers manage their tags via Azure Policy and will find this usefull

**Comment by tombuildsstuff** [comment]
hey @Sharono123 

Thanks for opening this issue.

Taking a look through here, it appears that this feature request is captured within #13776, which is tracking adding support for default tags (and/or ignoring specific tag keys deployed across all resources) - as such rather than having multiple issues open tracking the same thing, I'm going to close this issue in favour of #13776, would you mind subscribing to that issue for updates?

Thanks!
