### ISSUE TITLE
Documentation bug - azurerm_postgresql_flexible_server: version 15 is not supported by azure

### ISSUE THREAD

**Issue by kantorv** [hashicorp/terraform-provider-azurerm#22302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "default" {
  name                   = "pgsrv-123"
  location            = "centralindia"
  resource_group_name = "mygroup"
  version                = 15
  administrator_login    = "pgadmin"
  administrator_password = "asdasd^123"
  zone                   = "1"
  storage_mb             = 32768
  sku_name               = "GP_Standard_D2s_v3"
  backup_retention_days  = 7
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating Flexible Server (Subscription: "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
│ Resource Group Name: "XXXXXXXXXXXXXXX"
│ Flexible Server Name: "pgsrv-k7tu1"): performing Create: servers.ServersClient#Create: Failure sending request: StatusCode=0 -- Original Error: Code="ParameterOutOfRange" Message="The value of the 'Version' should be in: [11,12,13,14]. Verify that the specified parameter value is correct."
```

### Expected Behaviour

unsupported  version shouldn't be documented

### Actual Behaviour

unsupported version is listed in documentation

> 
_[version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#version) - (Optional) The version of PostgreSQL Flexible Server to use. Possible values are 11,12, 13, 14` and 15`. Required when create_mode is Default. Changing this forces a new PostgreSQL Flexible Server to be created._

### Steps to Reproduce

terraform apply

### References

[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server#version)

**Comment by aristosvo** [comment]
@kantorv This is an Azure API error bouncing back, and because v15 is preview it is not available in the region you are using as stated in the [docs](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-supported-versions#postgresql-version-15-preview):

> PostgreSQL version 15 is now available in public preview in limited regions (West Europe, East US, West US2, South East Asia, UK South, North Europe, Japan east).The current minor release is 15.2. Refer to the [PostgreSQL documentation](https://www.postgresql.org/docs/release/15.2/) to learn more about improvements and fixes in this release. New servers will be created with this minor version.

**Comment by kantorv** [comment]
@aristosvo 
You're right, just tested in `westeurope` region, seems works well.

**Comment by kandakaj** [comment]
Our resource group is located in the eastus region, and I'm encountering an issue while attempting to create the azurerm_postgresql_flexible_server resource. I got the error message: Error: expected version to be one of [11 12 13], got 15
