### ISSUE TITLE
Unable to assign user-assigned managed identities to Kubernetes with `identity_ids` because `identity.type` value is set to `"SystemAssigned"`

### ISSUE THREAD

**Issue by tspearconquest** [hashicorp/terraform-provider-azurerm#22307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

I have a module like below:
```hcl
resource "azurerm_kubernetes_cluster" "default" {
  name                = coalesce(var.kubernetes_name_override, module.name_generator.value)
  location            = var.region
  resource_group_name = coalesce(azurerm_resource_group.default["cluster"].name, local.rg_name)

  dns_prefix         = local.dns_prefix
  kubernetes_version = var.kubernetes_control_plane_version

  default_node_pool {
    ...
  }

  identity {
    identity_ids = local.vmss_additional_user_assigned_identities
    type         = "SystemAssigned"
  }
}

locals {
  control_plane_managed_identity = [ for key, value in azurerm_kubernetes_cluster.default.identity : value.principal_id if value.type == "SystemAssigned" ][0]

  # Additional user-assigned managed identities to add to the VMSS for the cluster
  # Identities added here will be able to be used by pods in the cluster to authenticate against AzureAD
  vmss_additional_user_assigned_identities = var.vmss_additional_user_assigned_identities != null ? toset(var.vmss_additional_user_assigned_identities) : null
}
```

Then I have some terraform code using this module:

```
module "kubernetes" {
  source  = redacted
  version = redacted

  vmss_additional_user_assigned_identities = local.vmss_additional_user_assigned_identities
}
```

I have a service that will use a user-assigned managed identity in order to access Keyvault. I have granted the identity access to the keyvault via keyvault access policy, but I am getting an error from the service that the identity is not found when it queries the IMDS in the cluster.

I wanted to add the user-assigned managed identity to the VMSS so that it will be usable by services running in the cluster. I cannot shift the cluster control plane to `type = "UserAssigned"` managed identities -- they must remain on `type = "SystemAssigned"`, so that the nodes will be rotated by Azure when the 45 day rotation period expires.

I am able to add the identity via the azure portal as you can see in the attached screenshot

### Debug Output/Panic Output

```shell
│ Error: expanding `identity`: `identity_ids` can only be specified when `type` is set to "UserAssigned"
│
│   with module.kubernetes.azurerm_kubernetes_cluster.default,
│   on .terraform/modules/kubernetes/main.tf line 26, in resource "azurerm_kubernetes_cluster" "default":
│   26: resource "azurerm_kubernetes_cluster" "default" {
│
╵
```

### Expected Behaviour

I expected the identity to be assigned to the VMSS

### Actual Behaviour

The error shown above

### Steps to Reproduce

Create a cluster with a SystemAssigned managed identity
Add the `identity_ids` field inside the `identity` block where `type = "SystemAssigned"` is set
Run terraform plan, get successful plan

```
Terraform will perform the following actions:

  # module.kubernetes.azurerm_kubernetes_cluster.default will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "default" {
        id                                  = "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.ContainerService/managedClusters/<redacted>"
        name                                = "redacted"
        tags                                = {
            "aa_managed_by"      = "terraform"
            "cloud_subscription" = "DEV"
            "cloud_tenant"       = "dev"
            "network_label"      = "test"
            "product"            = "redacted"
            "region"             = "redacted"
            "resource_owner"     = "redacted"
            "zz_created_date"    = "2023-02-07T19:09:31Z"
        }
        # (27 unchanged attributes hidden)

      ~ identity {
          ~ identity_ids = [
              + "/subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<redacted>",
            ]
            # (3 unchanged attributes hidden)
        }

        # (8 unchanged blocks hidden)
    }
```

Run terraform apply, get error.

### References

I am able to add the identity via the azure portal as you can see in the attached screenshot

As mentioned above, I was able to add the identity via the portal. The azurerm provider documentation appears to be pretty clear that this usage is allowed:

> An identity block supports the following:
> 
> [type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#type) - (Required) Specifies the type of Managed Service Identity that should be configured on this Kubernetes Cluster. Possible values are SystemAssigned or UserAssigned.
> 
> [identity_ids](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#identity_ids) - (Optional) Specifies a list of User Assigned Managed Identity IDs to be assigned to this Kubernetes Cluster.
> 
> Note:
> This is required when type is set to UserAssigned.

identity_ids is optional when type is set to SystemAssigned, but there is nothing here indicating that we CANNOT specify identity_ids if type is SystemAssigned, and furthermore since the portal and azure CLI both supports this use-case, Terraform should as well.

The inability to specify user-assigned identities prevents configuring different identities for different apps, and forces us to configure all apps to leverage the control plane's SystemAssigned identity, which we specifically want to avoid to protect that identity from abuse.

<img width="1511" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/81998567/96e3322b-4ca5-4a9f-9780-51ec69d17b67">

**Comment by stephybun** [comment]
Thanks for raising this issue @tspearconquest. 

This looks to be requesting the same functionality outlined in #22106. So that we don't have multiple issues tracking the same thing I'm going to close this one in favour of #22106. Please subscribe to #22106 for updates.

Thanks!

**Comment by Speeddymon** [comment]
It's not requesting the same functionality. #22106 has to do with applying a user assigned identity to a cluster with SP for the control plane.

My control plane is using SystemAssigned Managed Identity, and I need to add additional UserAssigned manage
Managed Identities to it.

Please reopen this.

**Comment by tspearconquest** [comment]
Interesting! Thanks for the clarification!

I've not seen type `SystemAssignedUserAssigned` in the provider docs and I noticed that my supposedly SystemAssigned managed identity for the cluster and the cluster keyvault secrets CSI provider in the screenshot on my OP are actually both under the UserAssigned tab in the portal.

It seems as though type = `SystemAssigned` may be setting `SystemAssignedUserAssigned` when we have the keyvault secrets CSI provider enabled. Is it possible to set this value explicitly, in Terraform? I wouldn't have an issue with having that value set if it is possible, and if it makes this work for my use case.

**Comment by stephybun** [comment]
It currently isn't possible to set `SystemAssignedUserAssigned` in the provider for the kubernetes resource since it isn't supported in the AKS API (that's the link to the swagger spec in my previous comment). I also checked the latest version that's been published and it isn't supported in there either so upgrading the SDK version won't help. 

In order to support other identity types you would need to raise an issue over on the [AKS repo](https://github.com/Azure/AKS) requesting that they add it, but if I'm honest I'm not sure that will fulfill the functionality that we're after here. Some digging needs to be done in the portal/Azure CLI to see what it's doing or what steps are involved to achieve the desired state.

**Comment by Speeddymon** [comment]
Understood. I'll get a support case opened with Microsoft today and try to
dig in the Azure CLI to see if I can find anything relevant. Thank you
again!
