### ISSUE TITLE
azurerm_key_vault manages certificate contacts even if null specified; conflicts with azurerm_key_vault_certificate_contacts

### ISSUE THREAD

**Issue by camilosantana** [hashicorp/terraform-provider-azurerm#22301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.4.6

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

- `azurerm_key_vault`
- `azurerm_key_vault_certificate_contacts`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.62.1"
    }
  }
}
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy    = true
      recover_soft_deleted_key_vaults = true
    }
  }
}
data "azurerm_client_config" "current" {}
resource "azurerm_resource_group" "a" {
  location = "eastus"
  name     = "tf-azurerm-issue-22301"
}
resource "azurerm_key_vault" "a" {
  name                       = azurerm_resource_group.a.name
  location                   = azurerm_resource_group.a.location
  resource_group_name        = azurerm_resource_group.a.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  soft_delete_retention_days = 7
  purge_protection_enabled   = false
  sku_name                   = "standard"
  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id
    certificate_permissions = [
      "Backup",
      "Create",
      "Delete",
      "DeleteIssuers",
      "Get",
      "GetIssuers",
      "Import",
      "List",
      "ListIssuers",
      "ManageContacts",
      "ManageIssuers",
      "Purge",
      "Recover",
      "Restore",
      "SetIssuers",
      "Update"
    ]
  }
}
resource "azurerm_key_vault_certificate_contacts" "a" {
  key_vault_id = azurerm_key_vault.a.id
  contact {
    email = "user@domain.com"
  }
}
```

### Expected Behaviour

on first run

- key vault is created
- certificate contact is create

on every subsequent run

- terraform has nothing to do

### Actual Behaviour

on first run

- resources are created

alternating subsequent runs:

- `azurerm_key_vault.a` deletes the certificate contact even though it's not being managed here
- `azurerm_key_vault_certificate_contacts.a` sees that the contact is missing. adds it back

### Steps to Reproduce

1. `terraform apply -auto-approve`
2. run `#1` again

**Comment by wuxu92** [comment]
Hi @rcskosir thanks for filing this issue. This is a by-design for managing certificate contact in both `azurerm_key_vault` and `azurerm_key_vault_certificate_contacts`. To avoid this annoying issue, you can/need to add an `ignore_changes` meta argument to `azurerm_key_vault` like below:

```
resource "azurerm_key_vault" "a" {
  lifecycle {
    ignore_changes = [contact]
  }

...// other configurations
}
```

**Comment by wuxu92** [comment]
@camilosantana you are right. but currently, we have to set the `ignore_changes` argument when contacts were managed by `azurerm_key_vault_certificate_contacts` even if the contacts did not present in the `azurerm_key_vault`. azurerm will not add a computed+optional field anymore. so `ignore_changes` should be the solution now.
