### ISSUE TITLE
azurerm_storage_account should mention that allow_nested_items_to_be_public is the same thing as allow_blob_public_access

### ISSUE THREAD

**Issue by MohnJadden** [hashicorp/terraform-provider-azurerm#22305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.19.0

### AzureRM Provider Version

3.28.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "dbricks-storage" {
  name                              = "storageaccountnamefoo"
  resource_group_name               = "resourcegroupnamebar"
  location                          = "eastus"
  account_tier                      = "Standard"
  account_replication_type          = "ZRS"
  enable_https_traffic_only         = true
  min_tls_version                   = "TLS1_2"
  public_network_access_enabled     = false
  infrastructure_encryption_enabled = true
  is_hns_enabled                    = true
  cross_tenant_replication_enabled  = false
  default_to_oauth_authentication   = true
  network_rules {
    default_action             = "Deny"
    virtual_network_subnet_ids = ["Vnet Resource ID A", "Vnet Resource ID B"]
    bypass                     = ["Logging", "Metrics", "AzureServices"]
  }
```

### Debug Output/Panic Output

```shell
N/A - details below
```

### Expected Behaviour

There is no setting mentioned in the `azurerm_storage_account` documentation for disabling public access to blob storage, nor anything else that mentions blob storage public access control.  

### Actual Behaviour

Since our Azure Policy requires blob storage public access to be false, the resource as created above fails to pass policy and does not deploy.  

Some googling pointed at [a StackOverflow discussion](https://stackoverflow.com/questions/73741756/disabling-allow-public-blob-access-using-terraform) where from 3.0 onwards, the `allow_blob_public_access` argument was changed to `allow_nested_items_to_be_public`.  This does not make any sense from an Azure storage perspective - we refer to blobs as blobs or blob containers, not as nested items.  

### Steps to Reproduce

1. Assign Azure Policy using the built-in definition "[Preview]: Storage account public access should be disallowed" to a subscription or resource group scope
2. Wait about 30 minutes for the policy to take effect
3. Create a main.tf using the above storage account example in the resource group scope defined in step 1
4. Run `terraform apply` - it will be denied by the policy
5. Edit the main.tf from step 3 to include allow_nested_items_to_be_public = false
6. Save main.tf and run `terraform apply` - it will pass the policy validation

### Important Factoids

This is running in regular Azure public (non-gov)

**Comment by magodo** [comment]
@MohnJadden The sanity of the renaming is stated in the v3 upgrade guide:

> Storage: The field allow_blob_public_access will be renamed to allow_nested_items_to_be_public to resolve confusion about what this field does. This field specifies whether items within the Storage Account (such as Containers and Blobs) can opt-in to being made public (for example at the Container or Blob level) - and not that all resources within this Storage Account are public by default.

Meanwhile, the document of this property is well self-explained:

> `allow_nested_items_to_be_public` - (Optional) Allow or disallow nested items within this Account to opt into being public. Defaults to true

Note that in the context of AzureRM provider, the *nested items* is a ubiquitous term to describe child resources under a certain parent resource. E.g. key vault key/secret/certificate are nested items of key vault.

With above, I don't see a need to mention the v2 equivalent of this property in the v3 document. If you have troubles to discover the corresponding TF property of an Azure API property, there is some other tool I'm working on to fill the gap: https://github.com/magodo/azure-rest-api-bridge, which is trying to get a property mapping between the AzureRM provider and the Azure API, though it is still under development.

I'm gonna to close this issue for now, if you have any further concern, feel free to reopen it.
