### ISSUE TITLE
Terraform fails when rerunning code on a different environment using the same AAD login

### ISSUE THREAD

**Issue by istarbuxs** [hashicorp/terraform-provider-azurerm#22315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_workspace / azapi_resource

### Terraform Configuration Files

```hcl
upon creation of Synapse workspace via Terraform, we use this snippet to enable AAD

resource "azapi_resource" "AAD" {
  type      = "Microsoft.Synapse/workspaces/azureADOnlyAuthentications@2021-06-01"
  name      = "default"
  parent_id = azurerm_synapse_workspace.example.id
  body = jsonencode({
    properties = {
      azureADOnlyAuthentication = true
    }
  })
  depends_on = [azurerm_synapse_workspace.example]
}
```

### Debug Output/Panic Output

```shell
synapse.WorkspacesClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="ValidationFailed" Message="Workspace request validation failed, check error details for more information" Details=[{"code":"AadOnlyAuthenticationIsEnabled","message":"Azure Active Directory Only Authentication is enabled. Please contact workspace administrator."}]
```

### Expected Behaviour

When we run it on different environments, it should run successfully. Environments are dev, qa, production, etc.

### Actual Behaviour

When we run it on different environments, it runs successfully on 1 environment but fails on the other environments.

### Steps to Reproduce

Run the usual terraform steps and it fails.

1. init
2. plan
3. apply

**Comment by mybayern1974** [comment]
@istarbuxs thank you for opening this issue. May I suggest you file this issue to the [TF AzAPI provider repo](https://github.com/Azure/terraform-provider-azapi/issues) that could be more relevant to this ask?

**Comment by rcskosir** [comment]
@istarbuxs Thanks for taking the time to open this issue. Since this is an issue with TF AzAPI and not Azurerm, I am going to close this issue. I reccommned you open an issue with [TF AzAPI ](https://github.com/Azure/terraform-provider-azapi/issues)if you have not already. Thanks!
