### ISSUE TITLE
expected sku_tier to be one of [Premium Standard], got Basic

### ISSUE THREAD

**Issue by anouchka007** [hashicorp/terraform-provider-azurerm#22329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.1

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_firewall

### Terraform Configuration Files

```hcl
resource "azurerm_firewall" "AzureFirewall" {

    resource_group_name = var.resource_group_name
    location            = var.resource_group_location

    name                = var.azure_firewall_name
    sku_name            = var.azure_firewall_sku_name
    sku_tier            = var.azure_firewall_sku_tier

    ip_configuration {

        name                 = "configuration"
        subnet_id            = data.azurerm_subnet.AzureFirewallSubnet.id
        public_ip_address_id = azurerm_public_ip.AzureFirewallPublicIP.id

    }

    tags = {

        application       = var.tag_application
        cost_center       = var.tag_cost_center
        deployment_method = var.tag_deployment_method
        entity            = var.tag_entity
        environment       = var.tag_environment
        location          = var.tag_location
        owner             = var.tag_owner
    
    }

}
```

### Debug Output/Panic Output

```shell
Error: expected sku_tier to be one of [Premium Standard], got Basic
│
│   with module.AzureFirewall.azurerm_firewall.AzureFirewall,
│   on ..\..\..\modules\azure_firewall\main.tf line 46, in resource "azurerm_firewall" "AzureFirewall":
│   46:     sku_tier            = var.azure_firewall_sku_tier
```

### Expected Behaviour

Possibility to choose Basic for Azure Firewall SKU Tier instead of Premium or Standard 

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall

**Comment by wuxu92** [comment]
@anouchka007 which version of azurerm provider did you use? the `Basic` SKU tire was added from version v3.9.0 in #16989

**Comment by anouchka007** [comment]
> @anouchka007 which version of azurerm provider did you use? the `Basic` SKU tire was added from version v3.9.0 in #16989

Absolutely right!
I didn't pay attention to my provider version.
I just changed my code and now it works. Thank You!

**Comment by anouchka007** [comment]
terraform {

  required_version = ">= 1.0.0"

  required_providers {

    azurerm = {

      source = "hashicorp/azurerm"
      version = "=3.9.0"

    }

  }

}
