### ISSUE TITLE
No HTTP resource was found that matches the request URI for `azurerm_network_security_rule`

### ISSUE THREAD

**Issue by msl0** [hashicorp/terraform-provider-azurerm#22321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.2

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_network_security_group" "example" {
  name                = "acceptanceTestSecurityGroup1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_network_security_rule" "example" {
  name                        = "test/123"
  priority                    = 100
  direction                   = "Outbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "*"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.example.name
  network_security_group_name = azurerm_network_security_group.example.name
}
```

### Debug Output/Panic Output

```shell
Error: creating/updating Security Rule: (Name "test/123" / Network Security Group Name "acceptanceTestSecurityGroup1" / Resource Group "example-resources"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"No HTTP resource was found that matches the request URI 'https://westeurope.network.azure.com:30057/<some_ID1>/<some_ID2>/subscriptions/<subscription_ID>/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/acceptanceTestSecurityGroup1/securityRules/test/123?api-version=2022-07-01'."}]
```

### Expected Behaviour

Getting a name validation error

### Actual Behaviour

Getting an error not directly pointing to invalid input
`Error: creating/updating Security Rule: (Name "test/123" / Network Security Group Name "acceptanceTestSecurityGroup1" / Resource Group "example-resources"): network.SecurityRulesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="Failed" Message="The async operation failed." AdditionalInfo=[{"Message":"No HTTP resource was found that matches the request URI 'https://westeurope.network.azure.com:30057/<some_ID1>/<some_ID2>/subscriptions/<subscription_ID>/resourceGroups/example-resources/providers/Microsoft.Network/networkSecurityGroups/acceptanceTestSecurityGroup1/securityRules/test/123?api-version=2022-07-01'."}]`

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hey @msl0 

Thanks for opening this issue.

Taking a look through here this looks to be an issue within Azure itself, whilst Terraform is successfully making the API call to the Resource Manager API, the internal request that the Resource Manager API is making is failing, as such unfortunately this is a platform issue and not something that Terraform can workaround (or even retry).

At this point in time [the Azure status page is green](https://azure.status.microsoft/en-gb/status), however I'd recommend opening an issue with Azure Support, since they'd need to dig into this (as this is an issue with the API's themselves) - I've also raised this through our internal channels too.

Thanks!

**Comment by msl0** [comment]
Hi @tombuildsstuff 

I don't have Terraform development experience, so it's not clear to me. Does terraform use the `name` argument to build an API request path? I guess so because when I provided slash in rule name it then requests path is completely different.
Microsoft.Network/networkSecurityGroups/<nsg_name>/securityRules/**<rule_name>**?api-version=2022-07-01
Microsoft.Network/networkSecurityGroups/<nsg_name>/securityRules/**test/123**?api-version=2022-07-01

Is there any input validation for provider resources arguments? If adding a slash to the name may cause a request to be made to a different endpoint, it seems to me that input data validation should be used (if possible) to prevent such situations.

I would appreciate if you could explain.

**Comment by Threpio** [comment]
The `azurerm_network_security_rule` `name`attribute does not currently have a validation function assigned to it as seen 

https://github.com/hashicorp/terraform-provider-azurerm/blob/e90bbabde943d5869626d653ad07734bee85d3bf/internal/services/network/network_security_rule_resource.go#L47-L51

Unlike other attributes in the same resource: 

https://github.com/hashicorp/terraform-provider-azurerm/blob/e90bbabde943d5869626d653ad07734bee85d3bf/internal/services/network/network_security_rule_resource.go#L53-L57

**Comment by msl0** [comment]
@rcskosir thank you for very quick reaction! Exactly what I am reporting is a bug. I am an experienced Azure user. @tombuildsstuff suggested it might be a problem with Azure, but it's not.
There is nothing to do with Azure Support. In Azure, there is a strong association between the resource ID and the API endpoint URL. When you try to create NSG rule via Azure portal, names with slash are not allowed, but Terraform azurerm provider accepts this. Provider builds incorrect URL using `name` containing a slash and tries to make a request, but it's failing because endpoint is incorrect what I described above. I'm not a developer. I explained the problem and asked why he thought so. I suggested that the problem is the lack of validation of the 'name' attribute and asked if it is possible to introduce such a fix for this bug because I don't know Terraform provider from golang code perspective yet.
@Threpio provided an example attribute to show that adding an attribute validation is possible, but in the case of the 'name' attribute it is simply not there. There was no configuration questions at all. I hope I have clarified the situation.
I'm very pleased with the quick response, but I'm worried about closing issues so quickly without investigating the problem

**Comment by rcskosir** [comment]
@msl0 Thank you for the clarification. I will reopen this issue so that your request for validation to be added to the network_security_group_name can be tracked.

**Comment by wuxu92** [comment]
I think Terraform has no knowledge about the validation of the name field. even this API call response with such an error message. the swagger definition has no such validation information. Submitted a PR to add a simple validation though. #22336 

https://github.com/Azure/azure-rest-api-specs/blob/64efc48302878a07d1d1231eaed0ca9cadfaf037/specification/network/resource-manager/Microsoft.Network/stable/2022-07-01/networkSecurityGroup.json#L501-L506
