### ISSUE TITLE
404 error: reading static website for AzureRM Storage Account accounts.Client#GetServiceProperties

### ISSUE THREAD

**Issue by XiaoYue2-22** [hashicorp/terraform-provider-azurerm#22322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

n/a

### Terraform Version

1.5.0

### AzureRM Provider Version

3.61.0

### Affected Resource(s)/Data Source(s)

storage account

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
2023-06-28T16:29:00.173+1000 [ERROR] vertex "module.pf_storage_test.azurerm_storage_account.sa" error: reading static website for AzureRM Storage Account "tsttmppfstrg4": accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:49f821e6-b01e-0001-6c89-a9e049000000\nTime:2023-06-28T06:29:00.3520618Z"
2023-06-28T16:29:00.195+1000 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-06-28T16:29:00.202+1000 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/hashicorp/azurerm/3.62.1/darwin_amd64/terraform-provider-azurerm_v3.62.1_x5 pid=74668
2023-06-28T16:29:00.202+1000 [DEBUG] provider: plugin exited
```

### Expected Behaviour

recreate storage account without error

### Actual Behaviour

recreate storage account with 404 error

### Steps to Reproduce

1. run the command terraform apply to create new storage account
2. run command terraform destroy to delete the new created storage account
3. re-do step 1 to recreate the same storage account and see the 404 error.
4. This is happened intermittently when run terraform apply command to recreate storage account that has been deleted and it happened less time when trying to run command "terraform destroy."
5. this issue happens after introuduce network rule section in main.tf and local.tf. it works fine if not add network rule part
6. Also customer tried to updated to the latest version, same issue still happened. 
7. I tried same code with same steps as cx in my local computer but can't reproduce the issue

**Comment by XiaoYue2-22** [comment]
<main.tf>
module "pf_storage_test" {
  source = "../modules/storageaccount"
  resource_group_name  = local.resource_group_name
  storage_account_name = local.storage_account_name
  location             = local.location
  containers_list      = local.containers_list
  sa_replication_type             = local.sa_replication_type
  enable_versioning               = local.enable_versioning
  change_feed_enabled             = local.change_feed_enabled
  blob_change_feed_retention_days = try(local.blob_change_feed_retention_days, null)
  blob_restore_days               = local.blob_restore_days
  network_rules                   = local.network_rules
  scopes_allowed_to_copy          = try(local.scopes_allowed_to_copy, null)

  tags                 = local.tags
}

<local.tf>
# ----------------------------------------------------------------------
# Locals
# ----------------------------------------------------------------------
locals {
  ss_subscription_id   = "aaa9980d-036b-4721-a80b-661d624a7376"
  resource_group_name  = "APIMgroup"
  storage_account_name = "tsttmppfstrg0624"
  location             = "australiaeast"
  sa_replication_type = "LRS"
  enable_versioning    = true
  change_feed_enabled  = true
  blob_change_feed_retention_days = 1 # setting it to 0 is not possible. Set to 1day of retention. 
  blob_restore_days      = 6
  scopes_allowed_to_copy = "AAD"
  network_rules = { # [TO CHECK]default_action is hardcoded in module as "Deny"
                  default_action = "Deny"
                  bypass     = ["AzureServices"],
                  ip_rules   = [],
                  subnet_ids = []
                }
  containers_list = [
    { name = "testprivatecontainer", access_type = "private" },
    { name = "testopentoallcontainer", access_type = "container" }
  ]
  # Resource tags
  tags = {
    "appname"         = "shared services",
    "category"        = "shared_services",
    "domain"          = "group technology",
    
  }
}

**Comment by magodo** [comment]
This bug is being tracked in this [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/10872) which I'm going to close this in favour of - would you mind subscribing to that issue for updates?

Thanks!
