### ISSUE TITLE
unable to login in to azure by using Azue Login github action

### ISSUE THREAD

**Issue by AIopsGeek** [hashicorp/terraform-provider-azurerm#22327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

>1

### AzureRM Provider Version

>=3.0

### Affected Resource(s)/Data Source(s)

Azure Login Github Action

### Terraform Configuration Files

```hcl
on:
  workflow_call:
jobs:
  build-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.path }}
        
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        
      - name: Set up Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
```

### Debug Output/Panic Output

```shell
3s
##[debug]Evaluating condition for step: 'Set up Azure login'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Set up Azure login
##[debug]Loading inputs
##[debug]Evaluating: secrets.AZURE_CREDENTIALS
##[debug]Evaluating Index:
##[debug]..Evaluating secrets:
##[debug]..=> Object
##[debug]..Evaluating String:
##[debug]..=> 'AZURE_CREDENTIALS'
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run azure/login@v1
##[debug]=> null
##[debug]Result: null
##[debug]Loading env
Run azure/login@v1
##[debug]az cli version used: /usr/bin/az
##[debug]az cli version used:
##[debug]azure-cli                         2.49.0
##[debug]
##[debug]core                              2.49.0
##[debug]telemetry                          1.0.8
##[debug]
##[debug]Extensions:
##[debug]azure-devops                      0.26.0
##[debug]
##[debug]Dependencies:
##[debug]msal                              1.20.0
##[debug]azure-mgmt-resource               22.0.0
##[debug]
##[debug]Python location '/opt/az/bin/python3'
##[debug]Extensions directory '/opt/az/azcliextensions'
##[debug]
##[debug]Python (Linux) 3.10.10 (main, May 19 2023, 08:20:31) [GCC 11.3.0]
##[debug]
##[debug]Legal docs and information: aka.ms/AzureCliLegal
##[debug]
##[debug]
##[debug]Your CLI is up-to-date.
##[debug]
Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows
```

### Expected Behaviour

It should login in to Azure cloud from Github Actons CI. Tried by recreating the secrets manually and also through az cli but still getting the same error.

### Actual Behaviour

getting error

Error: Az CLI Login failed. Please check the credentials and make sure az is installed on the runner. For more information refer https://aka.ms/create-secrets-for-GitHub-workflows

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Terraform Azure Provider. The issue you are describing above is related to Az CLI / GitHub Actions which are not managed by the Terraform Azure Provider, therefore I am going to close this issue. You may want to open an issue or get support with GitHub or Azure to have your issue resolved.
