### ISSUE TITLE
cdn_frontdoor_rule_set_ids should be a ordered list

### ISSUE THREAD

**Issue by sammeidroid** [hashicorp/terraform-provider-azurerm#22364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.0

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_route

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule_set" "test_1" {
  name                     = "Test1"
  cdn_frontdoor_profile_id = data.azurerm_cdn_frontdoor_profile.frontdoor.id
}

resource "azurerm_cdn_frontdoor_rule_set" "test_2" {
  name                     = "Test2"
  cdn_frontdoor_profile_id = data.azurerm_cdn_frontdoor_profile.frontdoor.id
}

resource "azurerm_cdn_frontdoor_rule_set" "test_3" {
  name                     = "Test3"
  cdn_frontdoor_profile_id = data.azurerm_cdn_frontdoor_profile.frontdoor.id
}

resource "azurerm_cdn_frontdoor_route" "test" {
  name                          = "default"
  enabled                       = true
  cdn_frontdoor_endpoint_id     = data.azurerm_cdn_frontdoor_endpoint.test.id
  cdn_frontdoor_origin_group_id = azurerm_cdn_frontdoor_origin_group.test.id
  cdn_frontdoor_origin_ids      = [azurerm_cdn_frontdoor_origin.test.id]
  cdn_frontdoor_rule_set_ids = [
    azurerm_cdn_frontdoor_rule_set.test_3.id,
    azurerm_cdn_frontdoor_rule_set.test_1.id,
    azurerm_cdn_frontdoor_rule_set.test_2.id
  ]
  forwarding_protocol    = "HttpsOnly"
  https_redirect_enabled = true
  patterns_to_match      = ["/"]
  supported_protocols    = ["Http", "Https"]
  link_to_default_domain = true
}
```

### Debug Output/Panic Output

```shell
## current state
resource "azurerm_cdn_frontdoor_route" "test" {
    ....
    cdn_frontdoor_rule_set_ids    = [
        "/subscriptions/********/resourceGroups/rg-********-dev/providers/Microsoft.Cdn/profiles/afd-********-dev/ruleSets/Test1",
        "/subscriptions/********/resourceGroups/rg-********-dev/providers/Microsoft.Cdn/profiles/afd-********-dev/ruleSets/Test2",
        "/subscriptions/********/resourceGroups/rg-********-dev/providers/Microsoft.Cdn/profiles/afd-********-dev/ruleSets/Test3",
    ]
    ....
}
```

### Expected Behaviour

The specified order of the "cdn_frontdoor_rule_set_ids" is respected.

### Actual Behaviour

The order is arbitrary. You have to correct the order manually in the Azure resource afterwards.

**Comment by WodansSon** [comment]
@sammeidroid, Thank you for opening this issue. When I originally switched `cdn_frontdoor_rule_set_ids` to a `TypeSet` from a `TypeList` it was because the Azure RP was returning the `cdn_frontdoor_rule_set_ids` in the reverse order they were sent:

**Values Returned From Azure:**
```bash
"ruleSets":[{"id":".../ruleSets/acctestrulesetthree"},
            {"id":".../ruleSets/acctestrulesettwo"},
            {"id":".../ruleSets/acctestrulesetone"}],
```
But Terraform persists them to the state file the way they were defined in the configuration file:

**Values In Terraform State File:**
```bash
"cdn_frontdoor_rule_set_ids": [
              ".../ruleSets/acctestrulesetone",
              ".../ruleSets/acctestrulesettwo",
              ".../ruleSets/acctestrulesetthree"
            ],
```
Then on your next `plan`/`apply` you will see an unexpected diff because Terraform wants to put the `cdn_frontdoor_rule_set_ids` values back in the same order as they appear in the config file, resulting in a very confusing diff:

**Values In Terraform Diff on Plan/Apply:**
```bash
~ cdn_frontdoor_rule_set_ids = [
    - ".../ruleSets/acctestrulesetthree",
    - ".../ruleSets/acctestrulesettwo",
      ".../ruleSets/acctestrulesetone",
    + ".../ruleSets/acctestrulesettwo",
    + ".../ruleSets/acctestrulesetthree",
  ]
```

The RP may have changed and it now honors the order of the `cdn_frontdoor_rule_set_ids` were sent, I do not know. We also need to make sure that doing this will not adversely affect other resources as well, such as the `azurerm_cdn_frontdoor_rule_set_association` resource or any other resource that depends on this field.

**Comment by WodansSon** [comment]
Hi @sammeidroid, I am going to go ahead and close this as there hasn't been any activity on the issue for over a month now. 🚀

**Comment by darren-hexagon** [comment]
Hi @WodansSon, the ruleset ordering is definitely an issue for us as we have a lot of rulesets configured that we have to keep manually ordering which is pretty time consuming, and could potentially cause us real issues if the ordering is wrong.
Is there any plans to fix this issue?

Thanks

**Comment by thunderholt** [comment]
This has become a big problem for us. Is there any news on a fix?
