### ISSUE TITLE
azurerm_storage_blob having an issue to create JWKS document 

### ISSUE THREAD

**Issue by ashishstationcasinos** [hashicorp/terraform-provider-azurerm#22362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.10

### AzureRM Provider Version

3.59.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

```hcl
resource "tls_private_key" "private_pem" {
  algorithm = "RSA"
  rsa_bits  = 2048
}
resource "local_file" "content_private_pem" {
  filename = "${path.module}/tls-private.pem"
  content = tls_private_key.private_pem.private_key_pem
  depends_on = [ tls_private_key.private_pem ]
}
resource "local_file" "content_public_pem" {
  filename = "${path.module}/tls-public.pem"
  content = tls_private_key.private_pem.public_key_pem
  depends_on = [ 
    tls_private_key.private_pem, 
    local_file.content_private_pem
    ]
}

resource "null_resource" "azwi_jkws" {
    provisioner "local-exec" {
    interpreter = [ "/bin/bash", "-c" ]
    working_dir = "${path.module}"
    command = "azwi jwks --public-keys ${path.module}/tls-public.pem --output-file ${path.module}/jwks.json"
       
  } 
}
# resource "local_file" "content_jwks" {
#   filename = "${path.module}/jwks.json"
#   content = tls_private_key.private_pem.private_key_pem
#   depends_on = [ tls_private_key.private_pem ]
# }

resource "azurerm_storage_blob" "upload_jwks" {
  name                   = "openid/v1/jwks"
  storage_account_name   = azurerm_storage_account.karbon_storage_account.name
  storage_container_name = azurerm_storage_container.karbon_storage_container.name
  type                   = "Block"
  content_type           = "application/json"
  #content_md5            = "zWLl0lo15ms32axfqori5SOgAb"  
  source                 = "${path.module}/jwks.json"
  depends_on = [ 
    null_resource.azwi_jkws,
    local_file.content_public_pem
   ]
}
```

### Debug Output/Panic Output

```shell
local_file.content_private_pem: Creating...
local_file.content_private_pem: Creation complete after 0s [id=5af583de056d653badd0c6edfb51c98ce557ff2b]
local_file.content_public_pem: Creating...
local_file.content_public_pem: Creation complete after 0s [id=1d9e59c1549a6c94a18801aeb6b15819c4377d60]
azurerm_storage_blob.upload_jwks: Creating...
╷
│ Error: creating Blob "openid/v1/jwks" (Container "ittstwus2regulatedsc" / Account "ittstwus2regulatedsa"): opening: open ./jwks.json: no such file or directory
│ 
│   with azurerm_storage_blob.upload_jwks,
│   on resource.tf line 195, in resource "azurerm_storage_blob" "upload_jwks":
│  195: resource "azurerm_storage_blob" "upload_jwks" {
```

### Expected Behaviour

azurerm_storage_blob is able  to upload the jwks.json document to container.

### Actual Behaviour

It say it didnt find the file jwks.json 

### Steps to Reproduce

resource "tls_private_key" "private_pem" {
  algorithm = "RSA"
  rsa_bits  = 2048
}
resource "local_file" "content_private_pem" {
  filename = "${path.module}/tls-private.pem"
  content = tls_private_key.private_pem.private_key_pem
  depends_on = [ tls_private_key.private_pem ]
}
resource "local_file" "content_public_pem" {
  filename = "${path.module}/tls-public.pem"
  content = tls_private_key.private_pem.public_key_pem
  depends_on = [ 
    tls_private_key.private_pem, 
    local_file.content_private_pem
    ]
}

resource "null_resource" "azwi_jkws" {
    provisioner "local-exec" {
    interpreter = [ "/bin/bash", "-c" ]
    working_dir = "${path.module}"
    command = "azwi jwks --public-keys ${path.module}/tls-public.pem --output-file ${path.module}/jwks.json"
       
  } 
}
# resource "local_file" "content_jwks" {
#   filename = "${path.module}/jwks.json"
#   content = tls_private_key.private_pem.private_key_pem
#   depends_on = [ tls_private_key.private_pem ]
# }

resource "azurerm_storage_blob" "upload_jwks" {
  name                   = "openid/v1/jwks"
  storage_account_name   = azurerm_storage_account.karbon_storage_account.name
  storage_container_name = azurerm_storage_container.karbon_storage_container.name
  type                   = "Block"
  content_type           = "application/json"

  source                 = "${path.module}/jwks.json"
  depends_on = [ 
    null_resource.azwi_jkws,
    local_file.content_public_pem
   ]
}

### References

I am Runing the terraform in Azure Pipeline using devops agents. Please suggest how can I resolve this issue

**Comment by magodo** [comment]
@ashishstationcasinos Thank you for submitting this! From the error message:

> opening: open ./jwks.json: no such file or directory

The `${path.module}` equals to `.`. The question then becomes whether the working directory of `terraform` is the same as `${path.module}`. Alternatively, you can try to provide an absolute path instead.

**Comment by ashishstationcasinos** [comment]
Hello @magodo ,
 
I have Tried Something like this But Still gives me same error 

resource "null_resource" "azwi_jkws" {
    provisioner "local-exec" {
    interpreter = [ "/bin/bash", "-c" ]
    command = "azwi jwks --public-keys ${path.module}/tls-public.pem --output-file /home/devops/agents/agent1/jwks.json"
       
  } 
}
resource "azurerm_storage_blob" "upload_jwks" {
  name                   = "openid/v1/jwks"
  storage_account_name   = azurerm_storage_account.karbon_storage_account.name
  storage_container_name = azurerm_storage_container.karbon_storage_container.name
  type                   = "Block"
  content_type           = "application/json"
  #content_md5            = "zWLl0lo15ms32axfqori5SOgAb"  
  source                 = "/home/devops/agents/agent1/jwks.json"
  depends_on = [ 
    null_resource.azwi_jkws,
    local_file.content_public_pem
   ]
}

Output 

 opening: open /home/***/agents/agent1/jwks.json: no such file or directory 
 with azurerm_storage_blob.upload_jwks,
 on resource.tf line 194, in resource "azurerm_storage_blob" "upload_jwks":
  resource "azurerm_storage_blob" "upload_jwks" {

**Comment by ashishstationcasinos** [comment]
I misunderstood the "Absolute path". Then I tried as below which solved the issue.


resource "null_resource" "azwi_jkws1" {
    provisioner "local-exec" {
    interpreter = [ "/bin/bash", "-c" ]
    working_dir = abspath(path.cwd)
    command = "azwi jwks --public-keys tls-public.pem --output-file ${abspath(path.cwd)}/jwks.json"
  } 
}
resource "azurerm_storage_blob" "upload_jwks" {
  name                   = "openid/v1/jwks"
  storage_account_name   = azurerm_storage_account.karbon_storage_account.name
  storage_container_name = azurerm_storage_container.karbon_storage_container.name
  type                   = "Block"
  content_type           = "application/json"
  #content_md5            = "zWLl0lo15ms32axfqori5SOgAb"  
  source                 = "${abspath(path.cwd)}/jwks.json"
  depends_on = [ 
    null_resource.azwi_jkws1,
    local_file.content_public_pem
   ]
}

it is able to upload the file to azure container
