### ISSUE TITLE
Application Gateway PFX Password doesn't match

### ISSUE THREAD

**Issue by OffColour** [hashicorp/terraform-provider-azurerm#2237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.10

### Affected Resource(s)
azurerm_application_gateway

### Terraform Configuration Files

```hcl
ssl_certificate {
    name     = "wildcard.api.mydomain.co.uk"
    data     = "${base64encode(file(".\\Certificates\\api_mydomain_co_uk.pfx"))}"
    password = "ABCD$$EFGH"
  }
```
### Expected Behavior

Password matches PFX and is imported into the Application Gateway

### Actual Behavior

Password doesn't match due to the '$$' in the password.
Not sure if this is only true with a $$ or also fails with a single $

### Steps to Reproduce

Import PFX into Application Gateway with a password containing $$

### Important Factoids

Same issue when setting up a SQL Database

**Comment by phil-bevan** [comment]
This also occurs if your password contains an '@' character.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
