### ISSUE TITLE
Unable to build authorizer for Managed HSM API when deploying to Azure China

### ISSUE THREAD

**Issue by nickda** [hashicorp/terraform-provider-azurerm#22374]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.2

### AzureRM Provider Version

3.63

### Affected Resource(s)/Data Source(s)

All Resources / Data Sources

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  environment = "China"
}

resource "azurerm_resource_group" "test" {
  name     = "test"
  location = "China North 3"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: unable to build authorizer for Managed HSM API: could not configure ClientSecret Authorizer: determining scope for "ManagedHSM": the endpoint "ManagedHSM" is not supported in this Azure Environment
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 7, in provider "azurerm":
│    7: provider "azurerm" {
│ 
╵
Operation failed: failed running terraform plan (exit 1)
```

### Expected Behaviour

Successful initialization of provider.   

### Actual Behaviour

Failure to plan with the 3.63 version when deploying to Azure China.

### Steps to Reproduce

terraform plan

### Important Factoids

Running in Azure China

**Comment by ranjan-tim** [comment]
This worked till 3.62 azurerm version. i think this change broke this in 3.63 - 
[ : https://github.com/hashicorp/terraform-provider-azurerm/pull/22162/commits](https://github.com/hashicorp/terraform-provider-azurerm/pull/22162/files)
it's a change not tested in other Azure Provider (meaning AzureChina or AzureGov). KV hsm is not available in China
