### ISSUE TITLE
azurerm_monitor_diagnostic_setting continues to see drift on log_analytics_destination_type 

### ISSUE THREAD

**Issue by jaehnigen-kp** [hashicorp/terraform-provider-azurerm#22406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.3.9

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "example" {
  name                           = "example"
  target_resource_id             = azurerm_linux_web_app.example.id
  log_analytics_destination_type = "Dedicated"
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.example.id

  metric {
    category = "AllMetrics"
    enabled  = true
    retention_policy {
      enabled = true
      days    = 31
    }
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_monitor_diagnostic_setting.example will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "example" {
        id                             = "/subscriptions/<removed>/resourceGroups/<removed>/providers/Microsoft.Web/sites/<removed>"
      + log_analytics_destination_type = "Dedicated"
        name                           = "example"
        # (2 unchanged attributes hidden)

        # (11 unchanged blocks hidden)
    }
```

### Expected Behaviour

1. ❌ No drift being found and shown in TF plan.
2. ✅ The setting is correctly applied.

### Actual Behaviour

1. ❌ TF plan continously shows a drift for the `log_analytics_destination_type` when set to `Dedicated` for the `azurerm_linux_web_app` type.
2. ✅ The setting is correctly applied: log data can be found being collected into the appropriate dedicated tables.

The same behaviour was seen also for other monitored resource types, which are not explicitly mentioned to NOT support the `Dedicated` type at https://learn.microsoft.com/en-us/azure/azure-monitor/reference/tables/azurediagnostics#resource-types :

* `azurerm_databricks_workspace`
* `azurerm_postgresql_flexible_server`

### Steps to Reproduce

`terraform plan`

### References

May relate to #17172

**Comment by teowa** [comment]
Hi @jaehnigen-kp , thanks for submitting this issue!
This is related to https://github.com/hashicorp/terraform-provider-azurerm/pull/20203, this should be the service API issue, some resource does not support set `logAnalyticsDestinationType` property, see details in https://github.com/Azure/azure-rest-api-specs/issues/22400. Seems the `azurerm_linux_web_app` is one of these resources.

**Comment by teowa** [comment]
If go to Azure Portal, choose the resource and click diagnostic setting, there is no `Destination table` toggle for the Web App resource, below is the screenshot for the Data Factory resource:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/ee669b06-6679-493a-a78f-a93f9de99f8d)
