### ISSUE TITLE
Issue with WEBSITE_HEALTHCHECK_MAXPINGFAILURES in app_settings for azurerm_windows_web_app resource

### ISSUE THREAD

**Issue by vstepko** [hashicorp/terraform-provider-azurerm#22402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.52.0

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.63.0"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = <sub_ID>
  tenant_id       = <tenant_ID>
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku_name            = "P1v2"
  os_type             = "Windows"
}

resource "azurerm_windows_web_app" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  app_settings = {
    WEBSITE_HEALTHCHECK_MAXPINGFAILURES = "2"
  }

  site_config {}
}
```

### Debug Output/Panic Output

```shell
terraform plan
╷
│ Error: cannot set a value for WEBSITE_HEALTHCHECK_MAXPINGFAILURES in app_settings
│ 
│   with azurerm_windows_web_app.example,
│   on main.tf line 35, in resource "azurerm_windows_web_app" "example":
│   35:   app_settings = {
│   36:     WEBSITE_HEALTHCHECK_MAXPINGFAILURES = "2"
│   37:   }
```

### Expected Behaviour

All work fine in version 3.62.1 and below, and I can specify this parameter. 
I think this issue is not only with `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` but also with other parameters that could be specified under `app_settings`

### Actual Behaviour

Just specifying the WEBSITE_HEALTHCHECK_MAXPINGFAILURES parameter in app_settings - breaking a TF.

### Steps to Reproduce

1. terraform plan
2. terraform apply

any

**Comment by xiaxyi** [comment]
Thanks @vstepko for raising this issue, this property is exposed as [health_check_eviction_time_in_min](https://registry.terraform.io/providers/hashicorp/azurerm/3.64.0/docs/resources/windows_web_app#health_check_eviction_time_in_min) under `site_config` in Terraform provider. It would be handled if specified in `app_settings`. Can you try to set the property under `site_config`?

**Comment by SteveDevOps** [comment]
I am setting this problem starting in 3.63 as well for not just WEBSITE_HEALTHCHECK_MAXPINGFAILURES but also for:
SCM_DO_BUILD_DURING_DEPLOYMENT
WEBSITE_RUN_FROM_PACKAGE
WEBSITE_DNS_SERVER
WEBSITE_VNET_ROUTE_ALL

what are the new site_config equivalents for those?

**Comment by xiaxyi** [comment]
Thanks @vstepko for the feedback, let me check the use case of this two parameters.

**Comment by xiaxyi** [comment]
Thanks @vstepko for the feedbacks. I checked the provider code and would like to explain the situation:

The provider will refer to `health_check_eviction_time_in_min ` under `site_config` to set the `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` in `app_setting`, check below code:
```
appSettings := helpers.ExpandAppSettingsForUpdate(webApp.AppSettings)
			if metadata.ResourceData.HasChange("site_config.0.health_check_eviction_time_in_min") {
				appSettings.Properties["WEBSITE_HEALTHCHECK_MAXPINGFAILURES"] = pointer.To(strconv.Itoa(webApp.SiteConfig[0].HealthCheckEvictionTime))
			}
```
I understand that `health_check_eviction_time_in_min` and `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` may have different usages from the api level (which we need to take future investigations about it). Currently, the provider is having a 1:1 mapping relationship between them, can you try setting `health_check_eviction_time_in_min` and see if the `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` will be set to `app_setting`? 

let me know if you have more questions.

**Comment by sheeeng** [comment]
I have experienced the same issue.

```diff
--- a/versions.tf
+++ b/versions.tf
@@ -2,7 +2,7 @@ terraform {
   required_providers {
     azurerm = {
       source  = "hashicorp/azurerm"
-      version = ">= 3.41.0, <= 3.62.1"
+      version = ">= 3.41.0"
       # TODO: >= 3.62.2 (E.g. 3.66.0) has regression.
       # https://github.com/hashicorp/terraform-provider-azurerm/issues/22402
     }
```

If we apply this change, it will introduce this regression and faced with the error message.

```text
Error: cannot set a value for WEBSITE_HEALTHCHECK_MAXPINGFAILURES in app_settings
```

**Comment by simonlrostron** [comment]
I am making some changes to some longstanding TF configurations to enable App Service health checks, and can confirm that this behavior also occurs for **azurerm_linux_web_app** in **azurerm 3.90.0**.

The provider version was initially pinned to **3.21.1**. This version had a bug where the `health_check_eviction_time_in_min` argument did not function as expected (#16302).

I updated the provider version to **3.90.0**. While this solved the bug with the functionality of the argument, I am now seeing behavior that matches the issue described here.

It's unfortunate that defining the associated `WEBSITE_HEALTHCHECK_MAXPINGFAILURES` app setting is disallowed. I understand the desire to abstract settings as resource arguments, and I also realize that it might not be feasible to resolve configurations defined in different ways. A better compromise might be to only allow using one method or the other. (It's also worth considering that the other configurable setting for the health check feature, `WEBSITE_HEALTHCHECK_MAXUNHEALTHYWORKERPERCENT` is not abstracted.)

Thanks for your time.
