### ISSUE TITLE
Deploying kubernetes cluster in azure with kubelet_config sending unsupported properties with Linux NodePools

### ISSUE THREAD

**Issue by welersonlisboa1970** [hashicorp/terraform-provider-azurerm#22424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

Terraform version 1.5.0

### AzureRM Provider Version

azurerm v3.64.0

### Affected Resource(s)/Data Source(s)

azure/azapi v1.7.0 / azurerm v3.64.0

### Terraform Configuration Files

```hcl
# main.tf
### https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-terraform?tabs=azure-cli
###https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kubelet_config
### https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#cpu_cfs_quota_enabled
# Generate random resource group name

resource "random_pet" "rg_name" {
  prefix = var.resource_group_name_prefix
}


resource "azurerm_resource_group" "rg" {
  location = var.resource_group_location
  name     = random_pet.rg_name.id
}


resource "random_pet" "azurerm_kubernetes_cluster_name" {
  prefix = "clusteraks"
}


resource "random_pet" "azurerm_kubernetes_cluster_dns_prefix" {
  prefix = "dns"
}


resource "azurerm_kubernetes_cluster" "k8s" {
  location            = azurerm_resource_group.rg.location
  name                = random_pet.azurerm_kubernetes_cluster_name.id
  resource_group_name = azurerm_resource_group.rg.name
  dns_prefix          = random_pet.azurerm_kubernetes_cluster_dns_prefix.id


  identity {
    type = "SystemAssigned"
  }


  default_node_pool {
    name       = "agentpool"
    vm_size    = "Standard_E4s_v5"
    node_count = var.node_count
    kubelet_config {
          pod_max_pid = 1024
        }
  }


  linux_profile {
    admin_username = "ubuntu"
    ssh_key {
      key_data = jsondecode(azapi_resource_action.ssh_public_key_gen.output).publicKey
    }
  }

  network_profile {
    network_plugin    = "kubenet"
    load_balancer_sku = "standard"
  }
}
```

### Debug Output/Panic Output

```shell
-- When the main.tf statefile is generated to be applyed, output will be the following if cpuCFSquota is not declared:
       ~ kubelet_config {
              - allowed_unsafe_sysctls    = [] -> null
              - container_log_max_line    = 0 -> null
              - container_log_max_size_mb = 0 -> null
              - cpu_cfs_quota_enabled     = true -> null
              - image_gc_high_threshold   = 0 -> null
              - image_gc_low_threshold    = 0 -> null
              ~ pod_max_pid               = 4096 -> 1024
            }
        }

With NULL, azure will recognize as FALSE, and then the issue with CPU Limits for POD/Containers will be present on Kubernetes Cluster in Azure.
```

### Expected Behaviour

_Expected in Azure cpuCFSquota to be TRUE intead false._

   "agentPoolProfiles": [
            {
                "name": "agentpool",
                "count": 3,
                "vmSize": "Standard_E4s_v5",
                "osDiskSizeGB": 128,
                "osDiskType": "Managed",
                "kubeletDiskType": "OS",
                "maxPods": 110,
                "type": "VirtualMachineScaleSets",
                "enableAutoScaling": false,
                "scaleDownMode": "Delete",
                "provisioningState": "Succeeded",
                "powerState": {
                    "code": "Running"
                },
                "orchestratorVersion": "1.25.6",
                "currentOrchestratorVersion": "1.25.6",
                "enableNodePublicIP": false,
                "mode": "System",
                "kubeletConfig": {
                    **_"cpuCfsQuota": TRUE,
                    "failSwapOn": false,
                    "podMaxPids": 1024_**
                },
                "enableEncryptionAtHost": false,
                "enableUltraSSD": false,
                "osType": "Linux",
                "osSKU": "Ubuntu",
                "nodeImageVersion": "AKSUbuntu-2204gen2containerd-202306.26.0",
                "upgradeSettings": {},
                "enableFIPS": false
            }

### Actual Behaviour

agentpool create with Kubelet_config and cpuCFSquota = FALSE (issue is here)

      "agentPoolProfiles": [
            {
                "name": "agentpool",
                "count": 3,
                "vmSize": "Standard_E4s_v5",
                "osDiskSizeGB": 128,
                "osDiskType": "Managed",
                "kubeletDiskType": "OS",
                "maxPods": 110,
                "type": "VirtualMachineScaleSets",
                "enableAutoScaling": false,
                "scaleDownMode": "Delete",
                "provisioningState": "Succeeded",
                "powerState": {
                    "code": "Running"
                },
                "orchestratorVersion": "1.25.6",
                "currentOrchestratorVersion": "1.25.6",
                "enableNodePublicIP": false,
                "mode": "System",
                "kubeletConfig": {
                    "cpuCfsQuota": false,
                    "failSwapOn": false,
                    "podMaxPids": 1024
                },
                "enableEncryptionAtHost": false,
                "enableUltraSSD": false,
                "osType": "Linux",
                "osSKU": "Ubuntu",
                "nodeImageVersion": "AKSUbuntu-2204gen2containerd-202306.26.0",
                "upgradeSettings": {},
                "enableFIPS": false
            }

### Steps to Reproduce

-follow the steps of quick guide here:https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-terraform?tabs=azure-cli#implement-the-terraform-code

- Setup the statefile main.tf on Terraform.
- Set the variable.tf
+Perform the following:
++terraform init -upgrade
+++terraform plan -out main.tfplan
++++terraform apply main.tfplan
- generate the output file and apply the configuration.
- Wait for the AKS cluster creation and check the JSON file of cluster in azure portal.

### References

https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-terraform?tabs=azure-cli#implement-the-terraform-code
https://learn.microsoft.com/en-us/azure/aks/custom-node-configuration?tabs=linux-node-pools#kubelet-configurationhttps://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#kubelet_config
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#cpu_cfs_quota_enabled
https://github.com/hashicorp/terraform-provider-azurerm/issues/22194

https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/#:~:text=By%20default%2C%20the%20kubelet%20uses,are%20available%20at%20scheduling%20time.
https://en.wikipedia.org/wiki/Completely_Fair_Scheduler

**Comment by ms-henglu** [comment]
Hi @welersonlisboa1970 ,

Thank you for taking time to report this issue!

Would you please try to specify `cpu_cfs_quota_enabled=true` in the `kubelet_config` block to enable this feature?

**Comment by ms-henglu** [comment]
For the "FailSwapOn: false" field, it's set by default, the reason is that

> must be false, otherwise the backend will report error: CustomKubeletConfig.FailSwapOn must be set to false to enable swap file on nodes.

refs: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_nodepool.go#L1087

**Comment by welersonlisboa1970** [comment]
> Hi @welersonlisboa1970 ,
> 
> Thank you for taking time to report this issue!
> 
> Would you please try to specify `cpu_cfs_quota_enabled=true` in the `kubelet_config` block to enable this feature?
> 
> I'll raise a PR to make this field default to `true` in the next major version.

**Comment by welersonlisboa1970** [comment]
Thank you Heng, indeed using TRUE on cpuCFSquota to enforce the parameter CPU limits is working as expected. Thank you for submitting this issue to have a change on the next major version.

**Comment by welersonlisboa1970** [comment]
Thank you Heng, indeed using TRUE on cpuCFSquota to enforce the parameter CPU limits is working as expected. Thank you for submitting this issue to have a change on the next major version. Can I ask if we can have estimated ETA?

**Comment by ms-henglu** [comment]
Hi @welersonlisboa1970 , unfortunately there's no concrete timeline for the next major version.

**Comment by welersonlisboa1970** [comment]
thank you Heng

**Comment by welersonlisboa1970** [comment]
[like]  Welerson Lisboa reacted to your message:
________________________________
