### ISSUE TITLE
Refresh of "azurerm_key_vault" resources requires network connectivity to Keyvault data plane

### ISSUE THREAD

**Issue by joakimlemb** [hashicorp/terraform-provider-azurerm#22458]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.2

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "test_keyvault" {
  name                = "test-kv"
  location            = REDACTED
  resource_group_name = "testrg"
  tenant_id           = "REDACTED"
 
  enable_rbac_authorization = true
  soft_delete_retention_days = 90
  purge_protection_enabled   = true
 
  sku_name                      = "standard"
  public_network_access_enabled = false
 
  network_acls {
    bypass         = "AzureServices"
    default_action = "Deny"
  }
  
}
```

### Debug Output/Panic Output

```shell
Error: retrieving contact for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
```

### Expected Behaviour

Expect azurerm to only contact dataplane if needed, not always.

It is possible to workaround this issue with "-refresh=false" during plan/apply.

### Actual Behaviour

Terraform refresh fails on azurerm_key_vault if it is unable to contact the keyvault at TCP Port 443.

Current workarounds/solutions:
- Whitelist terraform clients public IP in Keyvault
- If Private Endpoint is used, connect to VPN so that the terraform client is able to reach the keyvault
- use "-refresh=false" in terraform

### Steps to Reproduce

Set up a keyvault and run terraform refresh after blocking the keyvault IP in the outgoing firewall where the terraform client is running.

(The read timeout parameter for azurerm_key_vault is not respected by "terraform refresh" so expect to wait 20+min before terraform gives up.)

If this is intended behavior, it should be documented and the error message "Original Error: context deadline exceeded" needs to be more informative.
Suggestion for error message: "Could not reach keyvault $FQDN ($IP) at $Protocol $Port"...

### References

relevant issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/17863
suspected code that creates the issue: https://github.com/hashicorp/terraform-provider-azurerm/blob/09bfe5bfb555c4ac4068348e56ba88655a1b07d6/internal/services/keyvault/key_vault_resource.go#L396

**Comment by tombuildsstuff** [comment]
hey @joakimlemb 

Thanks for opening this issue.

Taking a look through here unfortunately this is the same underlying issue as #9738 where the Resource Manager API doesn't contain all of the information necessary to detect changes to the state of the Key Vault, so we instead need to reach out to the Data Plane API.

Rather than having multiple issues open tracking the same thing, I'm going to close this issue for the moment - but would you mind subscribing to #9738 for updates?

Thanks!
