### ISSUE TITLE
azurerm_cosmosdb_account  switches the default_identity_type to FirstPartyIdentity whenever there is a change to the account

### ISSUE THREAD

**Issue by Divya1388** [hashicorp/terraform-provider-azurerm#22466]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.15.4

### AzureRM Provider Version

3.62.1

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "database" {
  name                            = var.name
  location                        = var.primary_location
  resource_group_name             = var.resource_group_name
  offer_type                      = "Standard"
  kind                            = "GlobalDocumentDB"
  enable_multiple_write_locations = var.enable_multiple_write_locations
  key_vault_key_id                = azurerm_key_vault_key.cmk.versionless_id

  consistency_policy {
    consistency_level       = var.consistency_level
    max_interval_in_seconds = var.max_interval_in_seconds
    max_staleness_prefix    = var.max_staleness_prefix
  }

  geo_location {
    location          = var.primary_location
    failover_priority = 0
    zone_redundant    = var.zone_redundant
  }

  dynamic "geo_location" {
    for_each = var.replication_locations
    content {
      location          = geo_location.value.location
      failover_priority = geo_location.value.failover_priority
      zone_redundant    = geo_location.value.zone_redundant
    }
  }

  backup {
    type                = var.backup_type
    interval_in_minutes = lower(var.backup_type) == "periodic" ? var.backup_interval_in_minutes : null
    retention_in_hours  = lower(var.backup_type) == "periodic" ? var.backup_retention_in_hours : null
  }

  # Adding the following to be able to access the account from the portal
  public_network_access_enabled = true
  ip_range_filter               = "104.42.195.92,40.76.54.131,52.176.6.30,52.169.50.45,52.187.184.26"

  tags = local.all_tags

  identity {
    type = "SystemAssigned, UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.cosmos_db_user_identity.id]
  }

  default_identity_type = "UserAssignedIdentity=${azurerm_user_assigned_identity.cosmos_db_user_identity.id}"

  lifecycle {
    ignore_changes = [
      tags["date_created"]
    ]
  }

  depends_on = [azurerm_key_vault_access_policy.uaid_kv_policy]
}
```

### Debug Output/Panic Output

```shell
The initial apply assigns the default identity to UserAssigned Identity and everything works fine. When we have some change on the account, for example tags, the resource silently switches to FirstPArtyIdentity and throw the following Error for CMK Encryption:

Error: updating Database Account: (Name "******" / Resource Group "r*******"): creating/updating CosmosDB Account "***********" (Resource Group "******************"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Updating default identity not allowed. Failed to validate key vault access permission 'Get' with KeyVaultErrorCode 'KeyVaultAuthenticationFailure'.\r\nActivityId: **********, Microsoft.Azure.Documents.Common/2.14.0"
```

### Expected Behaviour

There should not have been an error and  the tags should have been updated and not change the default_identity

### Actual Behaviour

Getting the following Error:

Error: updating Database Account: (Name "******" / Resource Group "r*******"): creating/updating CosmosDB Account "***********" (Resource Group "******************"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Updating default identity not allowed. Failed to validate key vault access permission 'Get' with KeyVaultErrorCode 'KeyVaultAuthenticationFailure'.\r\nActivityId: **********, Microsoft.Azure.Documents.Common/2.14.0"

And when i grant Azure Cosmos DB First Party Identity Get Wrap and UnWrap on the CMK Keys it goes with the change

But if there are no changes to cosmos account it keeps to userassigned identity

### Steps to Reproduce

terraform apply 

change a tag 

terraform apply

### Important Factoids

This has not happened in 3.55.0 and we see this https://github.com/hashicorp/terraform-provider-azurerm/pull/21780  that might be related

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/21780

**Comment by WodansSon** [comment]
@Divya1388, that you for opening this issue. I have looked into this and this issue is not caused by the PR you mentioned in your issue. I have debugged it and it is an issue with the API itself and we do not modify any settings except for that tags, but when the API sends the data back to use the `default identity` has been switched in the backend. I am reaching out to the service team to make them aware of this while I attempt to figure out a work-around for the API bug in the interim. 🚀

**Comment by Divya1388** [comment]
@WodansSon Thanks for looking into it and i am not sure if API version was changed in 3.58.0 but we don't see this bug in versions before 3.58.0

**Comment by WodansSon** [comment]
@Divya1388, I believe the reason you did not see the issue prior to `v3.58.0` is because you were hitting the service side issue where setting the `default identity` and `identity` at the same time would silently fail and automatically fallback to `First Party Identity`. That said, I missed this scenario when writing the test cases for the workaround I introduced for that issue. I will add a new acceptance test for this scenario specifically to make sure we don't get a regression in the future once I figure out a way to fix this. 🚀
