### ISSUE TITLE
Terraform resource for Azure AML workspace datastore- "azurerm_machine_learning_datastore_datalake_gen2" endpoint issue for Storage container ID deploying to US gov 

### ISSUE THREAD

**Issue by rej007** [hashicorp/terraform-provider-azurerm#22467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

should be an option provide endpoint if default endpoint is not "core.windows.net" for storage account 

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_datastore_datalake_gen2

### Potential Terraform Configuration

```hcl
I believe there should be an option to provide a different endpoint because the default endpoint is "core.windows.net", which might not be the case for all storage accounts
```

**Comment by rej007** [comment]
Resource Group Name: "test-rg”
│ Workspace Name: "exampleworkspace"
│ Data Store Name: "exampledatastore"): datastore.DatastoreClient#CreateOrUpdate: Failure responding to request: StatusCode=400 --
│ Original Error: autorest/azure: Service returned an error. Status=400 Code="Invalid" Message="Invalid endpoint. Provided:
│ [core.windows.net], Expected: [core.usgovcloudapi.net]" Details=[]

**Comment by stonenw-va** [comment]
Yes Same Error as rej007
creating Data Store (Subscription: 
│ Resource Group Name: "RG"
│ Workspace Name: "aml"
│ Data Store Name: "datastore"): unexpected status [40](https://github.com)0 with error: Invalid: Invalid
│ endpoint. Provided: [core.windows.net], Expected: [core.usgovcloudapi.net]

**Comment by rej007** [comment]
@manicminer
