### ISSUE TITLE
I want to create a Nutanix Kubernetes Cluster and to implement Workload Identity I need to create azure Federated Credentials 

### ISSUE THREAD

**Issue by ashishstationcasinos** [hashicorp/terraform-provider-azurerm#22471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Using terrafrom Creating a NKE(Nutanix Kubernetes Engine) Cluster and implement Workload Identity. For That I need to Create a Azure Federated Identity Credentials. As we are restricted to 20 federated credentials for Each managed identity I am Restricting the number of namespaces. When I Run terraform Plan(Running Terraform on Azure Pipelines) With Below Code I am facing issue of 
 Error: Invalid for_each argument
│ 
│   in resource "azurerm_federated_identity_credential" "afic":
│ :   for_each            =  toset(local.required_namespaces)
│     ├────────────────
│     │ local.required_namespaces is a set of string, known only after apply
│ 
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.

resource "nutanix_karbon_cluster" "karbon" {
  name    = var.karbonClusterName
  version = var.kubernetesVersion

  storage_class_config {
    name           = var.storageClassConfigName
    reclaim_policy = var.storageClassConfigReclaimPolicy

    volumes_config {
      file_system                = var.storageClassConfigVolumeConfigFileSystem
      password                   = var.storageClassConfigPassword
      username                   = var.storageClassConfigUsername
      prism_element_cluster_uuid = data.nutanix_cluster.cluster.metadata.uuid
      storage_container          = var.storageClassConfigStorageContainer
    }
.................................................
............................<>
  }

locals {
    required_namespaces  = setsubtract(data.kubernetes_all_namespaces.allns.namespaces, var.system_namespaces)
    depends_on = [data.kubernetes_all_namespaces.allns, nutanix_karbon_cluster.karbon]
}

data "kubernetes_all_namespaces" "allns" {
  depends_on = [ nutanix_karbon_cluster.karbon ]
 }
resource "azurerm_federated_identity_credential" "afic" {
  for_each            =  toset(local.required_namespaces)
  name                =  each.value
  resource_group_name =  azurerm_resource_group.rg.name
  audience            =  ["api://AzureADTokenExchange"]
  issuer              =  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  parent_id           =  azurerm_user_assigned_identity.uai.id
  subject             =  "system:serviceaccount:${each.key}:default"

  depends_on = [
    nutanix_karbon_cluster.karbon,
    local.required_namespaces,
    azurerm_storage_account.karbon_storage_account,
    azurerm_storage_container.karbon_storage_container,
    azurerm_user_assigned_identity.uai
  ]
 }

FYI:  As per Depends, First My cluster need to created and then It Need to Get the namespaces from the Cluster, But it is doing opposite.

Any Ideas How Can I fix it ? 

### New or Affected Resource(s)/Data Source(s)

azurerm_federated_identity_credential

### Potential Terraform Configuration

```hcl
resource "nutanix_karbon_cluster" "karbon" {
  name    = var.karbonClusterName
  version = var.kubernetesVersion

  storage_class_config {
    name           = var.storageClassConfigName
    reclaim_policy = var.storageClassConfigReclaimPolicy

    volumes_config {
      file_system                = var.storageClassConfigVolumeConfigFileSystem
      password                   = var.storageClassConfigPassword
      username                   = var.storageClassConfigUsername
      prism_element_cluster_uuid = data.nutanix_cluster.cluster.metadata.uuid
      storage_container          = var.storageClassConfigStorageContainer
    }
.................................................
............................<>
  }
variable "system_namespaces" {
    type   = list
    default = ["kube-system", "default","kube-release","devops"]
}

locals {
    required_namespaces  = setsubtract(data.kubernetes_all_namespaces.allns.namespaces, var.system_namespaces)
    depends_on = [data.kubernetes_all_namespaces.allns, nutanix_karbon_cluster.karbon]
}

data "kubernetes_all_namespaces" "allns" {
  depends_on = [ nutanix_karbon_cluster.karbon ]
 }
resource "azurerm_federated_identity_credential" "afic" {
  for_each            =  toset(local.required_namespaces)
  name                =  each.value
  resource_group_name =  azurerm_resource_group.rg.name
  audience            =  ["api://AzureADTokenExchange"]
  issuer              =  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
  parent_id           =  azurerm_user_assigned_identity.uai.id
  subject             =  "system:serviceaccount:${each.key}:default"

  depends_on = [
    nutanix_karbon_cluster.karbon,
    local.required_namespaces,
    azurerm_storage_account.karbon_storage_account,
    azurerm_storage_container.karbon_storage_container,
    azurerm_user_assigned_identity.uai
  ]
 }
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34), you're likely to get more support in answering your question there. With that in mind, I'm going to close this issue.
