### ISSUE TITLE
Support for bypassPlatformChecksOnUserSchedule set to true

### ISSUE THREAD

**Issue by Kockieee** [hashicorp/terraform-provider-azurerm#22487]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Since of recently our VM code fails with the following error regarding patch orchestration. After running our code we now get below error. We then have to go into the portal to turn on patch orchestration to 'Customer Managed Schedules (Preview)' 

This is the error shown in the pipeline:

│ Error: issuing creating request for Maintenance Assignment (virtual machine ID "/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxxxx"): configurationassignments.ConfigurationAssignmentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedResourceOperation" Message="The prerequisites to patch your machine were not met. Please set the patchMode to AutomaticByPlatform and bypassPlatformChecksOnUserSchedule as true. Resource: /subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.Compute/virtualMachines/xxxxxxxx""
│ 

Below chatGPT suggestion:

The error message suggests that there is an issue with the maintenance assignments for the virtual machines. Specifically, the prerequisites for patching the machines are not met. To resolve this issue, you need to set the patchMode to AutomaticByPlatform and bypassPlatformChecksOnUserSchedule to true in the maintenance assignment configuration.

-----

patchMode - AutomaticByPlatform is already present in terraform code
bypassPlatformChecksOnUserSchedule - true isn't available in terraform code.

We would like the latter to be added to the code. 

Thanks in advance! :)

### New or Affected Resource(s)/Data Source(s)

"hashicorp/azurerm"

**Comment by Annesars90** [comment]
Same issue here. This is now a mandatory setting so we can't redeploy unless we use the az api resource.
