### ISSUE TITLE
azurerm_storage_account.go non-compliant resource issue

### ISSUE THREAD

**Issue by MickyMcIntee** [hashicorp/terraform-provider-azurerm#22507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=0.12"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.0.0"
    }
  }
  backend "azurerm" {}
}
provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
Error: updating Azure Storage Account AllowSharedKeyAccess "***": storage.AccountsClient#Update: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="RequestDisallowedByPolicy" Message="Resource '***' was disallowed by policy.
```

### Expected Behaviour

- Create storage account with no tags
- Create subscription policy to require tags of a specific value
- Using azurerm_storage_account update the tag to the required specified value of the policy
- Tags should be updated and terraform should run alright

### Actual Behaviour

- Create storage account with no tags
- Create subscription policy to require tags of a specific value
- Using azurerm_storage_account update the tag to the required specified value of the policy
- Terraform fails with the policy being raised

Unfortunately can't share images of the code, but in azurerm_storage_account_resource.go on line 1502, I believe that because this client is called regardless to make updates to the storage account, before the client is called to update the tags, the policy is not met and so an error is raised - which essentially softlocks you from making any changes via terraform without manual intervention on the azure portal.

### Steps to Reproduce

1. Using terraform create a storage account with no tags
2. In azure subscription policies, create a policy that requires a particular resource tag
3. The storage account is now non-compliant
4. terraform import that resource into a new script
5. Adjust the resource block to include the tag that the policy requires
6. terraform plan to show clearly that the tag would be added on the run of the terraform
7. terraform apply

This will error because the tag isn't compliant, but I believe it's the blank tag that's not compliant being executed by the client in azurerm_storage_account_resource.go line 1502, and not the actual tags that are updated and should be executed by the client on line 1551

### Important Factoids

N/A

**Comment by magodo** [comment]
@MickyMcIntee Thank you for reporting this! Persumably, you can workaround this by `terraform apply -refresh=false`.
