### ISSUE TITLE
azurerm_cognitive_deployment not able to deploy latest version(0613) of gpt3.5

### ISSUE THREAD

**Issue by jayendranarumugam** [hashicorp/terraform-provider-azurerm#22501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.0

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "uksouth"
}

resource "azurerm_cognitive_account" "example" {
  name                = "example-ca"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "OpenAI"
  sku_name            = "S0"
}

resource "azurerm_cognitive_deployment" "example" {
  name                 = "example-cd"
  cognitive_account_id = azurerm_cognitive_account.example.id
  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0613"
  }

  scale {
    type = "Standard"
  }
}
```

### Debug Output/Panic Output

When i used newer version 0613 on gpt-35-turbo it looks like below (perfect) but when i checked in the portal the version is pointing as old (0301). I believe somehow while creating it took the default version and not the newer version

```
+ model {
          + format  = "OpenAI"
          + name    = "gpt-35-turbo"
          + version = "0613"
        }

      + scale {
          + capacity = 120
          + type     = "Standard"
        }
```

I manually updated the version on the portal, and ran the terraform again now it shows like below

```
      ~ model {
            name    = "gpt-35-turbo"
          ~ version = "0301" -> "0613"
            # (1 unchanged attribute hidden)
        }
```

but I got the error like Error: doesn't support update (I can able to update the version from the portal successfully)

#References

https://github.com/hashicorp/terraform-provider-azurerm/issues/22198#issuecomment-1625004948

**Comment by lonegunmanb** [comment]
Hi @jayendranarumugam, thanks for opening this issue, after some debugging I found that this issue was caused by the absent of `VersionUpgradeOption` argument. I'll open a pr to fix this issue.
