### ISSUE TITLE
`automatic_channel_upgrade` should accept "none" if it's the default

### ISSUE THREAD

**Issue by ianarsenault** [hashicorp/terraform-provider-azurerm#22510]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.58.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  automatic_channel_upgrade = "none"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none
│
│   with module.azure_aks_cluster.azurerm_kubernetes_cluster.aks,
│   on ../../../modules/azure_aks_cluster/0.1.0/cluster.tf line 18, in resource "azurerm_kubernetes_cluster" "aks":
│   18:   automatic_channel_upgrade = var.automatic_channel_upgrade
│
╵
Releasing state lock. This may take a few moments...
```

### Expected Behaviour

The [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade) states `the upgrade channel for this Kubernetes Cluster. Possible values are patch, rapid, node-image and stable. Omitting this field sets this value to none.` It's also documented as a default setting here https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster

If the value by default is set to `none` then this should be a configurable option, since an azurerm_kubernetes_cluster could be modularized and different values set for `automatic_channel_upgrade` based on the needs of each implementation.

Setting the value to `null` gets around this but may be better suited to expect one of the five values (patch, rapid, node-image, stable, none)?

### Actual Behaviour

`Error: expected automatic_channel_upgrade to be one of [patch rapid stable node-image], got none`

### Steps to Reproduce

Run a terraform apply on `azurerm_kubernetes_cluster` resource with `automatic_channel_upgrade = "none"`

### References

https://learn.microsoft.com/en-us/azure/aks/auto-upgrade-cluster
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_channel_upgrade

**Comment by stephybun** [comment]
Hi @ianarsenault,

This is a conscious design decision within the provider which we have explained over in the contributor docs [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md#the-none-value-or-similar) in case you haven't seen it. There are of course special cases where we do need to expose this because the default isn't `none` like for the `node_os_channel_upgrade` but since that isn't the case for this particular property we would not be looking to explicitly expose this value.

Thank you for taking the time to raise this issue but since this isn't something we would consider doing I'm going to close this issue.

**Comment by ianarsenault** [comment]
Thanks @stephybun, I missed the schema design consideration docs before opening this issue. That is very helpful and clears things up from my end. Much appreciated!

**Comment by jacobcrawford** [comment]
@stephybun i came across this issue when searching for "--node-os-upgrade-channel". Is `node_os_channel_upgrade` actually something that is supported somehow or did you just provide an example?
