### ISSUE TITLE
lifecycle ignore_changes in azurerm_container_registry not working with georeplications

### ISSUE THREAD

**Issue by mc-eddi** [hashicorp/terraform-provider-azurerm#22530]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "acrtest" {
  name                    = var.registry_name_new
  resource_group_name     = data.azurerm_resource_group.rg.name
  location                = var.location
  zone_redundancy_enabled = true
  sku                     = "Premium"
  admin_enabled           = true

  georeplications {
    location                = "westeurope"
    zone_redundancy_enabled = true
  }

  lifecycle {
    ignore_changes = [
      tags["project_product"],
      tags["project_resource_group"],
      tags["cost_unit"],
      tags["shared_unit"]
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_container_registry.acrnemo will be updated in-place
  ~ resource "azurerm_container_registry" "acrnemo" {
        id                            = "/subscriptions/12345678-1234-1234-1234-1234567890ab/resourceGroups/test-res-group/providers/Microsoft.ContainerRegistry/registries/acrtest"
        name                          = "acrtest"
        tags                          = {
            "cost_unit"              = "CU.123"
            "project_product"        = "testproj"
            "project_resource_group" = "test-res-group"
        }
        # (18 unchanged attributes hidden)

      ~ georeplications {
          ~ tags                      = {
              - "cost_unit"              = "CU.123" -> null
              - "project_product"        = "testproj" -> null
              - "project_resource_group" = "test-res-group" -> null
            }
            # (3 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

For the entire resource azurerm_container_registry lifecycle ignore_changes is set for three tags (e.g. cost_unit).
We would expect changes in the tags should be ignored by the terraform plan.

### Actual Behaviour

The terraform plan (see debug output) is recognizing this for the resource itself (container registry), but not for the georeplications setting (azure resource type container registry replication).

In Azure with the georeplication block another resource is created, but the lifecycle ignore_changes cannot be set for this resource in terraform.

### Steps to Reproduce

terraform plan

**Comment by magodo** [comment]
@mc-eddi Thank you for reporting this! As the `georeplications` is a list, you can specify it in the `ignore_changes` list as well, e.g.:

```hcl
  lifecycle {
    ignore_changes = [
      tags["foo"],
      georeplications.0.tags["foo"],
      georeplications.1.tags["foo"],
    ]
  }
```

**Comment by mc-eddi** [comment]
Thank you @magodo for the quick response.
Your answer solved the problem. This issue can be closed.
