### ISSUE TITLE
azurerm_kubernetes_cluster_node_pool not accepting argument custom_ca_trust_certificates_base64 

### ISSUE THREAD

**Issue by jocortems** [hashicorp/terraform-provider-azurerm#22539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster and azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "k8s_cluster" {
  name                = "${var.k8s_cluster_name}-aks"
  location            = azurerm_resource_group.rg_name.location
  resource_group_name = azurerm_resource_group.rg_name.name
  dns_prefix          = "${var.k8s_cluster_name}-k8s"

  default_node_pool {
    name           = "system"
    node_count     = 1
    vm_size        = var.aks_vm_sku
    vnet_subnet_id = azurerm_subnet.private_subnet_2.id

    custom_ca_trust_enabled = true    
    custom_ca_trust_certificates_base64 = [
      file("ca-chain.pem"),
    ]    
  }

  network_profile {
    network_plugin    = "azure"
    load_balancer_sku = "standard"
    service_cidr      = var.k8s_sevice_cidr
  }

  identity {
    type = "SystemAssigned"
  }

  linux_profile {
    admin_username = var.azure_vm_admin_username
    ssh_key {
      key_data = file(var.ssh_public_key)
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Unsupported argument
│ 
│   on aks.tf line 24, in resource "azurerm_kubernetes_cluster" "k8s_cluster":
│   24:     custom_ca_trust_certificates_base64 = [
│ 
│ An argument named "custom_ca_trust_certificates_base64" is not expected here.
```

### Expected Behaviour

Plan should have succeeded, the argument is provided in the documentation

### Actual Behaviour

Plan errored out

### Steps to Reproduce

Terraform plan

### Important Factoids

N/A

### References

Nothing else. I followed the documentation to register the preview feature in my subscription

**Comment by stephybun** [comment]
Thanks for raising this issue @jocortems. 

It looks like the property was documented under the wrong block - it's actually a top level property so moving it out of the `default_node_pool` block should fix the error you're seeing.
