### ISSUE TITLE
Support for managedNetwork in azurerm_machine_learning_workspace

### ISSUE THREAD

**Issue by AdamCoulterOz** [hashicorp/terraform-provider-azurerm#22546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In `2023-06-01-preview` of `Microsoft.MachineLearningServices/workspaces` there is a new feature [Workspace managed network isolation (preview)](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-managed-network?view=azureml-api-2&tabs=azure-cli#configure-for-serverless-spark-jobs). It manages the network isolation, virtual network and private linking under the ML Workspace resource. Can we add this property to the resource?

### New or Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_machine_learning_workspace" "example" {
  name                    = "example-workspace"
  location                = "azregion"
  resource_group_name     = "myrg"
  application_insights_id = "ai-id"
  key_vault_id            = "kv-id"
  storage_account_id      = "sa-id"

  managed_network {
    isolation_mode = "allow_only_approved_outbound" // or "allow_internet_outbound"
  }

  identity {
    type = "SystemAssigned"
  }
}
```

**Comment by cramseyio** [comment]
Hi, I am checking in on this. I noticed that this Managed Network Isolation feature was released as GA in October: https://azure.microsoft.com/en-us/updates/azure-machine-learning-general-availability-for-october/

It appears that it is available in this version of the API
Microsoft.MachineLearningServices/workspaces@2023-10-01

I can see it being used here in azapi_resource: https://learn.microsoft.com/en-us/azure/templates/microsoft.machinelearningservices/workspaces?pivots=deployment-language-terraform

Is this something that would be able to be implemented as part of **azurerm_machine_learning_workspace** now that it's out of preview?

Thanks!
