### ISSUE TITLE
HTTP method 'DELETE' is not supported. azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by Isaac-Irvine** [hashicorp/terraform-provider-azurerm#22551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.1

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_group_template_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "main" {
  name                = "sql-server"
  resource_group_name = var.resource_group_name
  location            = var.location

  version                       = "12.0"
}

resource "azurerm_resource_group_template_deployment" "vulnerability_assessment" {
  name = "vulnerability-assessment"
  resource_group_name = var.resource_group_name
  deployment_mode = "Incremental"

  parameters_content = jsonencode({
    sqlServerName = {
      value = azurerm_mssql_server.main.name
    }
    sqlServerAdmin = {
      value = azurerm_mssql_server.main.administrator_login
    }
  })
  template_content = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
      "sqlServerName": {
          "type": "String",
          "metadata": {
              "description": "Name of the SQL server"
          }
      },
      "sqlServerAdmin": {
          "type": "String",
          "metadata": {
              "description": "Name of the SQL server admin"
          }
      }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Sql/servers/sqlVulnerabilityAssessments",
      "apiVersion": "2022-02-01-preview",
      "name": "[concat(parameters('sqlServerName'), '/default')]",
      "properties": {
        "state": "Enabled"
      }
    },
    {
      "type": "Microsoft.Sql/servers/databases/sqlVulnerabilityAssessments/baselines",
      "apiVersion": "2022-02-01-preview",
      "name": "[concat(parameters('sqlServerName'),'/master/default/default')]",
      "properties": {
        "latestScan": false,
        "results": {
          "VA2130": [
            [
              "[parameters('sqlServerAdmin')]",
              "SID goes here"
            ]
          ]
        }
      }
    }
  ]
}
TEMPLATE
}
```

### Debug Output/Panic Output

```shell
Error: removing items provisioned by this Template Deployment: deleting Nested Resource "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-name/providers/Microsoft.Sql/servers/sql-server/databases/master/sqlVulnerabilityAssessments/default/baselines/default": resources.Client#DeleteByID: Failure sending request: StatusCode=405 -- Original Error: Code="MethodNotAllowed" Message="The HTTP method 'DELETE' is not supported on the resource 'subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rg-name/providers/Microsoft.Sql/servers/sql-server/databases/master/sqlVulnerabilityAssessments/default/baselines/default'."
```

### Expected Behaviour

azurerm_resource_group_template_deployment is deleted without incident

### Actual Behaviour

Gives the above error and fails to delete the resource

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Unfortunately, seems it's by service API design since the [rest API Spec](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2022-02-01-preview/DatabaseSqlVulnerabilityAssessmentBaselines.json) does not support `delete` action.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
