### ISSUE TITLE
New Resource: azurerm_servicebus_subscription_virtual_network_rule

### ISSUE THREAD

**Issue by steve-hawkins** [hashicorp/terraform-provider-azurerm#2255]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Much like the azurerm_sql_virtual_network_rule it would be great to have one for Service Bus Namespace

### New or Affected Resource(s)

* azurerm_servicebus_namespace_virtual_network_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_servicebus_namespace_virtual_network_rule" "example" {
  name                    = "servicebus_vnet_rule"
  resource_group_name     = "${azurerm_resource_group.example.name}"
  servicebus_namespace_id = "${azurerm_serverbus_namespace.example.id}"
  subnet_id               = "${azurerm_subnet.example.id}"
}
```

**Comment by tombuildsstuff** [comment]
hey @steve-hawkins 

Thanks for opening this issue :)

Taking a quick look into this it appears [this is supported by the Azure SDK](https://github.com/Azure/azure-sdk-for-go/blob/v21.3.0/services/servicebus/mgmt/2017-04-01/servicebus/rules.go#L43-L51) but is scoped at a Service Bus Subscription level, rather than the Namespace level (as such I've updated the issue title).

Thanks!

**Comment by aristosvo** [comment]
I want to give this one a try! 🚀

**Comment by jbinko** [comment]
@tombuildsstuff : As going through old items to investigate. This seems to be done and ready to be closed.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
