### ISSUE TITLE
Request for new resources and data sources for Azure Dev Center

### ISSUE THREAD

**Issue by bhupindersingh11** [hashicorp/terraform-provider-azurerm#22592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Request for new resources and data sources for Azure Dev Center

### New or Affected Resource(s)/Data Source(s)

azurerm_devcenter_XXXX

### References

https://learn.microsoft.com/en-us/rest/api/devcenter/
https://learn.microsoft.com/en-gb/azure/dev-box/overview-what-is-microsoft-dev-box

**Comment by damienaicheh** [comment]
@rcskosir Do you have any update on this enhancement please? 
It's also related to the issue https://github.com/hashicorp/terraform-provider-azurerm/issues/23367
Thanks!

**Comment by tombuildsstuff** [comment]
Fixed via #23538
