### ISSUE TITLE
Support for always serve option in Traffic Manager external endpoints

### ISSUE THREAD

**Issue by michal-malec** [hashicorp/terraform-provider-azurerm#22629]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Using Azure API or portal it's possible to set external endpoint of Traffic Manager into "Always serve traffic" mode. This setting disables health check and makes the endpoint available all the time. The feature seems to be not available in Terraform. It would be great to add it.

Reference to Azure API documentation:
https://learn.microsoft.com/en-us/rest/api/trafficmanager/endpoints/create-or-update?tabs=HTTP#alwaysserve

### New or Affected Resource(s)/Data Source(s)

azurerm_traffic_manager_external_endpoint

**Comment by guywood13** [comment]
+1 
This would be useful!

**Comment by sundarpn** [comment]
Yes, useful to add. Bump

**Comment by maksagit** [comment]
We also need this functionality
