### ISSUE TITLE
`azurerm_kubernetes_cluster`: provider wants to destroy/recreate cluster due to case mismatch in `network_plugin_mode`

### ISSUE THREAD

**Issue by jeffhuenemann** [hashicorp/terraform-provider-azurerm#22621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.65.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks1" {
# ...
  network_profile {
    network_plugin      = "azure"
    network_plugin_mode = "Overlay"
  }
}
```

### Debug Output/Panic Output

```shell
# module.kubernetes_cluster_standard.azurerm_kubernetes_cluster.aks1 must be replaced
-/+ resource "azurerm_kubernetes_cluster" "aks1" {
#[snip]
      ~ network_profile {
#[snip]
          + network_mode        = (known after apply)
          ~ network_plugin_mode = "overlay" -> "Overlay" # forces replacement
        }
    }
```

### Expected Behaviour

Per the [`azurerm_kubernetes_cluster` docs](https://registry.terraform.io/providers/hashicorp/azurerm/3.65.0/docs/resources/kubernetes_cluster), the acceptable value of `network_plugin_mode` is `Overlay` (uppercase `O`). With that value in play, subsequent plans/applies without any code change should not represent a mismatch of value, and should not suggest recreating the cluster.

### Actual Behaviour

In the state file, the state is represented with a lowercase `o`, creating a mismatch with uppercase `O` required in the configuration. `terraform plan` wants to replace the entire cluster due to `network_plugin_mode` changing (it thinks) from `overlay` in state to `Overlay` in configuration.

### Steps to Reproduce

1. Create an `azurerm_kubernetes_cluster` using `network_plugin` = `azure` and `network_plugin_mode` = `Overlay`
2. Subsequent `terraform plan` suggests to recreate the cluster on account of drift in`network_plugin_mode`

### Important Factoids

Did not observe this behavior until upgrading from 3.63 to 3.65

**Comment by jeffhuenemann** [comment]
Improved search on my part reveals #22151 -> #22153 for an update to the API version in use, so maybe this is really just a documentation change and `overlay` is the only appropriate input value? If the provider accepts both `overlay` and `Overlay` as inputs, then they both need to be non-impactful on subsequent plans/applies, to my thinking.

**Comment by stephybun** [comment]
Thanks for raising this issue @jeffhuenemann.

The resource will allow the value to be lowercased to `overlay` without replacing the cluster - this is unfortunately an update that needs to be done in the user's config since this change was shipped by the upstream API.

The latest release v3.66.0 shipped a documentation fix to the casing of the value in https://github.com/hashicorp/terraform-provider-azurerm/pull/22554.

Since this is working as expected and the documentation has been fixed I'm going to close this issue.
