### ISSUE TITLE
Error: expected import.0.authentication_type to be one of [ADPassword Sql], got SQL

### ISSUE THREAD

**Issue by Preet1202** [hashicorp/terraform-provider-azurerm#22634]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Error: expected import.0.authentication_type to be one of [ADPassword Sql], got SQL
with azurerm_mssql_database.mssql_database
on mssql_database.tf line 17, in resource "azurerm_mssql_database" "mssql_database":
    authentication_type = "SQL"

### Terraform Version

1.5.2

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "mssql_database" {
  name                        = "agent"
  server_id                   = azurerm_mssql_server.mssql_server.id
  collation                   = "SQL_Latin1_General_CP1_CI_AS"
  max_size_gb                 = 10
  min_capacity                = 0.75
  auto_pause_delay_in_minutes = -1
  sku_name                    = "GP_S_Gen5_6"
  tags                        = local.tags
  storage_account_type        = "Local"
  geo_backup_enabled          = true
  import {
    administrator_login = "cloudadmin"
    administrator_login_password = var.administrator_login_password
    storage_uri = ""
    authentication_type = "ADPassword"
    storage_key_type = "StorageAccessKey"
    storage_key = var.storage_key
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected import.0.authentication_type to be one of [ADPassword Sql], got SQL
with azurerm_mssql_database.mssql_database
on mssql_database.tf line 17, in resource "azurerm_mssql_database" "mssql_database":
    authentication_type = "SQL"
```

**Comment by Preet1202** [comment]
which changes are needed to solve this?

**Comment by sinbai** [comment]
@Preet1202 thanks for opening this issue. Could you please provide the complete tf configuration and reproduce steps to help reproduce/troubleshoot?
