### ISSUE TITLE
azurerm_app_service_plan: Changing per_site_scaling doesn't stick

### ISSUE THREAD

**Issue by elkrammer** [hashicorp/terraform-provider-azurerm#22653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I have an existing Azure App Service Plan with per_site_scaling enabled.
Trying to disable this setting currently has no effect. Terraform plan correctly shows that the setting is going to be disabled but after terraform apply the change is not sticking / being applied.

This seems to be an issue with Azure's API - currently the only way I've found to effectively disable this setting is using powershell:

`Set-AzAppServicePlan -ResourceGroupName rg-test -Name example-sp -PerSiteScaling $false`

### Terraform Version

1.5.3

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "rg-test"
  location = "East US"
}

resource "azurerm_app_service_plan" "example-sp" {
  name                = "api-appserviceplan-pro"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "Windows"
  per_site_scaling    = true

  sku {
    tier = "PremiumContainer"
    size = "PC2"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform reports no errors/failures
```

### Expected Behaviour

When setting `per_site_scaling = false` it should effectively disable it.

### Actual Behaviour

After disabling the setting Azure is still reporting it's enabled.
This can be verified using Azure CLI:

```
$ az appservice plan show -n example-sp -g rg-test | grep perSiteScaling
"perSiteScaling": true,


### Steps to Reproduce

Change `per_site_scaling    = true` to `per_site_scaling    = false` and run TF Apply
Then use ` az appservice plan show -n example-sp -g rg-test | grep perSiteScaling` to verify if the setting took effect


### Important Factoids

_No response_

### References

_No response_

**Comment by SudhirmkGit** [comment]
Do we have a solution for this ?
