### ISSUE TITLE
Application gateway fails to deploy with SSL policy set to AppGwSslPolicy20220101 or AppGwSslPolicy20220101S

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#22669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.9

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
provider "azurerm" {
  skip_provider_registration = true
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  address_space       = ["10.254.0.0/16"]
}

resource "azurerm_subnet" "frontend" {
  name                 = "frontend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.254.0.0/24"]
}

resource "azurerm_subnet" "backend" {
  name                 = "backend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.254.2.0/24"]
}

resource "azurerm_public_ip" "example" {
  name                = "example-pip"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

# since these variables are re-used - a locals block makes this more maintainable
locals {
  backend_address_pool_name      = "${azurerm_virtual_network.example.name}-beap"
  frontend_port_name             = "${azurerm_virtual_network.example.name}-feport"
  frontend_ip_configuration_name = "${azurerm_virtual_network.example.name}-feip"
  http_setting_name              = "${azurerm_virtual_network.example.name}-be-htst"
  listener_name                  = "${azurerm_virtual_network.example.name}-httplstn"
  request_routing_rule_name      = "${azurerm_virtual_network.example.name}-rqrt"
  redirect_configuration_name    = "${azurerm_virtual_network.example.name}-rdrcfg"
}

resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.frontend.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 80
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.example.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Http"
  }

  request_routing_rule {
    priority                   = 10
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }

  ssl_profile {
    name        = "default"
    ssl_policy {
        policy_type = "Predefined"
        # AppGwSslPolicy20220101 and AppGwSslPolicy20220101S NOT WORKING
        policy_name = "AppGwSslPolicy20220101S"

        # Working with:
        # AppGwSslPolicy20170401S, AppGwSslPolicy20170401

        # Deprecated: AppGwSslPolicy20150501
    }
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_application_gateway.network: Creating...
╷
│ Error: creating Application Gateway: (Name "example-appgateway" / Resource Group "example-resources"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewaySslPolicyMisMatch" Message="The newer and older SSL policies can't be used together for SSLPolicy and listener-specific SSLProfile. Your configuration's sslProfile default conflicts with the global sslPolicy AppGwSslPolicy20150501 set for this Application Gateway. Know more about the SSL policies. https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#usage-and-version-details" Details=[]
```

### Expected Behaviour

AGW should be created when using latest supported SSL policies

<img width="880" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/4702224/016164b5-7a50-49bf-bc2f-68bccc41b81b">

### Actual Behaviour

Failing as the golang network api version is not >= 2023-02-01

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#predefined-tls-policy

### Steps to Reproduce

terraform init and apply

### References

https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#predefined-tls-policy

Would be good to control the authorized value of the SSL

# Not supported yet:
AppGwSslPolicy20220101
AppGwSslPolicy20220101S

# working:
AppGwSslPolicy20170401S
AppGwSslPolicy20170401

# Deprecated
AppGwSslPolicy20150501

**Comment by skoop22** [comment]
Any progress on this ?

**Comment by drk1001** [comment]
Is this being worked on or do we need to implement a workaround for it?

**Comment by lazgeo** [comment]
Assigning the SSLProfile to the HttpListener solved the issue for me.

**Comment by teowa** [comment]
From the [doc](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#default-tls-policy), the `2023-02-01` or later version of the application gateway has defaultPredefinedSslPolicy:[AppGwSslPolicy20220101](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#predefined-tls-policy),  [current used](https://github.com/hashicorp/terraform-provider-azurerm/blob/3355bb9df2f7b12c3478311ca6d68a9252408599/internal/services/network/application_gateway_resource.go#L34) API version `2022-07-01` has the predefined policy [AppGwSslPolicy20150501](https://learn.microsoft.com/en-us/azure/application-gateway/application-gateway-ssl-policy-overview#predefined-tls-policy) as default. **If the default TLS doesn’t fit your requirement, choose a different Predefined policy or use a Custom one**. so in TF config if the `ssl_profile.ssl_policy.policy_name` wants to be configured as `AppGwSslPolicy20220101`, `ssl_policy` block is should to be specified to avoid conflict.

```hcl
  ssl_policy {
    policy_type = "Predefined"
    policy_name = "AppGwSslPolicy20220101"
  }

```
