### ISSUE TITLE
Importing azurerm_cdn_frontdoor_security_policy will force recreation due to casing changes in cdn_frontdoor_firewall_policy_id and cdn_frontdoor_domain_id

### ISSUE THREAD

**Issue by WojciechSadowski** [hashicorp/terraform-provider-azurerm#22666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_security_policy

### Terraform Configuration Files

```hcl
import {
  to = azurerm_cdn_frontdoor_firewall_policy.this
  id = ""
}
import {
  to = azurerm_cdn_frontdoor_security_policy.this
  id = ""
}
import {
  to = azurerm_cdn_frontdoor_profile.this
  id = ""
}
import {
  to = azurerm_cdn_frontdoor_endpoint.this
  id = ""
}
import {
  to = azurerm_cdn_frontdoor_custom_domain.this
  id = ""
}

resource "azurerm_cdn_frontdoor_security_policy" "this" {
  cdn_frontdoor_profile_id = azurerm_cdn_frontdoor_profile.this.id
  name                     = "${azurerm_cdn_frontdoor_firewall_policy.this.name}-securityPolicy"

  security_policies {
    firewall {
      cdn_frontdoor_firewall_policy_id = azurerm_cdn_frontdoor_firewall_policy.this.id

      association {
        patterns_to_match = ["/*"]

        domain {
          cdn_frontdoor_domain_id = azurerm_cdn_frontdoor_custom_domain.this.id
        }
        domain {
          cdn_frontdoor_domain_id = azurerm_cdn_frontdoor_endpoint.this.id
        }
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_cdn_frontdoor_security_policy.this must be replaced
# (imported from "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx/securityPolicies/xxxx")
# Warning: this will destroy the imported resource
-/+ resource "azurerm_cdn_frontdoor_security_policy" "this" {
        cdn_frontdoor_profile_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx"
      ~ id                       = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx/securityPolicies/xxxx" -> (known after apply)        
        name                     = "xxxx"

      ~ security_policies {
          ~ firewall {
              ~ cdn_frontdoor_firewall_policy_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/microsoft.network/frontdoorWebApplicationFirewallPolicies/xxxx" -> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Network/frontDoorWebApplicationFirewallPolicies/xxxx" # forces replacement

              ~ association {
                    patterns_to_match = [
                        "/*",
                    ]

                  ~ domain {
                      ~ active                  = true -> (known after apply)
                      ~ cdn_frontdoor_domain_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourcegroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx/customdomains/xxxx" -> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx/customDomains/xxxx" # forces replacement
                    }
                  ~ domain {
                      ~ active                  = true -> (known after apply)
                      ~ cdn_frontdoor_domain_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourcegroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx/afdendpoints/xxxx" -> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/xxxx/providers/Microsoft.Cdn/profiles/xxxx/afdEndpoints/xxxx" # forces replacement
                    }
                }
            }
        }
    }
```

### Expected Behaviour

The azurerm_cdn_frontdoor_security_policy resource should not need to be recreated after importing.

### Actual Behaviour

![terraform plan](https://user-images.githubusercontent.com/37096816/255791233-85c35861-6f5f-469a-a775-34f8ee3a5ad2.PNG)

When importing a azurerm_cdn_frontdoor_security_policy that was created outside of terraform the terraform plan will show that it will need to be recreated due to changes of the casing of cdn_frontdoor_firewall_policy_id and cdn_frontdoor_domain_id.

Since there is no update function in azurerm for azurerm_cdn_frontdoor_security_policy these changes will force a recreation. According to https://github.com/hashicorp/terraform-provider-azurerm/issues/19761#issuecomment-1381010226 the API doesn't support an Update operation. Is there a reason why a [patch update](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/services/cdn/mgmt/2021-06-01/cdn#SecurityPoliciesClient.Patch) can't be done (I am not familiar with go/Azure API).

### Steps to Reproduce

1. Create a CDN FrontDoor Profile, Custom Domain, Endpoint that is associated with one firewall policy in the Azure Portal or by using the Front Door (classic) to Standard/Premium tier migration tool.
2. terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/19761#issuecomment-1381010226

**Comment by WodansSon** [comment]
Hi @WojciechSadowski, thank you for opening this issue, unfortunately this behavior is by design in Terraform. Please see the explanation provided by @tombuildsstuff in [PR #22289](https://github.com/hashicorp/terraform-provider-azurerm/pull/22289) for more details. With that said I am going to go ahead and close this issue as by design, sorry.

**Comment by WojciechSadowski** [comment]
If it is possible to update azurerm_cdn_frontdoor_security_policy without forcing the resource to be replaced that would solve my issue. 
I did test implementing an update function in cdn_frontdoor_security_policy_resource.go https://github.com/hashicorp/terraform-provider-azurerm/commit/9ece5fdf19ea2106c2ab315f74a1a18e0c38bd4c and it is working correctly.
![changed](https://github.com/hashicorp/terraform-provider-azurerm/assets/37096816/9547e7b3-4e39-4b2a-8fd0-2ed98062e175)
Would there be any issues with creating a PR with these changes (after adding tests)?
