### ISSUE TITLE
storage_account_blob_container_sas changes with every apply

### ISSUE THREAD

**Issue by TobyPopeBG** [hashicorp/terraform-provider-azurerm#22670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.11

### AzureRM Provider Version

3.65.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_blob_container_sas azurerm_storage_account_sas

### Terraform Configuration Files

```hcl
data "azurerm_storage_account_blob_container_sas" "datalakeSASQueryString" {
  depends_on        = [module.mod_dataLake]
  https_only        = true
  count             = var.mod_dataLake_enabled ? 1 : 0
  connection_string = module.mod_dataLake.primaryConnectionString
  container_name    = "example"

  start  = "2013-07-09T00:00:00Z"
  expiry = "2099-12-31T00:00:00Z"

  permissions {
    read   = true
    write  = true
    delete = false
    list   = true
    add    = true
    create = true
  }

  timeouts {
    read = "5m"
  }
}

output "mod_dataLake_sasUrlQueryString" {
  value     = try(data.azurerm_storage_account_blob_container_sas.datalakeSASQueryString[0].sas, null)
  sensitive = true
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

SAS shouldn't be regenerated after each apply when using hardcoded dates/permissions.

### Actual Behaviour

SAS is regenerated and the output changed.

### Steps to Reproduce

1. Run a terraform plan/apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/15786

**Comment by magodo** [comment]
@TobyPopeBG I'm using the following version locally, and the 2nd plan won't show any diff:

```hcl
data "azurerm_storage_account_blob_container_sas" "test" {
  connection_string = azurerm_storage_account.test.primary_connection_string
  container_name    = azurerm_storage_container.test.name
  https_only        = true

  start  = "2022-08-22T00:00:00Z"
  expiry = "2023-08-22T00:00:00Z"

  permissions {
    add    = true
    create = true
    delete = true
    list   = true
    read   = true
    write  = true
  }
}
```

As is mentioned in the #15786, would you please double confirm whether the `module.mod_dataLake.primaryConnectionString` is computed in every apply, which transitively causes this data source be marked as known after apply.

**Comment by TobyPopeBG** [comment]
So it's only when we change something in the datalake that it will read from this data source again?

Seems like generating a SAS from a data source isn't the best method? Having it as a data source will mean the SAS is changing frequently every time a plan/apply is run.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
