### ISSUE TITLE
Support for overwriting an existing blob

### ISSUE THREAD

**Issue by KevinBrooke** [hashicorp/terraform-provider-azurerm#22696]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Add the ability to overwrite an existing blob with the azurerm_storage_blob resource. 
GCP functions this way, also the Azure CLI has the option when running `az storage blob upload`.

Reason, we init a file on first run and upload it via another process, TF then downloads it for processing and uploads again if it changed. ATM we use azure cli to upload it as it can overwrite the existing file, it would be nice to have the provider do this instead of a null resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "examplestoracc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "content"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "example" {
  name                   = "my-awesome-content.zip"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source                 = "some-local-file.zip"
  overwrite_existing     = true
}
```

**Comment by KevinBrooke** [comment]
We managed to work around this using the v1.5 import block.
e.g.
`import {
    to = azure_storage_account_blob.example
    id = "this-is-my-blob"
}

resource "azurerm_storage_blob" "example" {
  name                                  = "my-awesome-content.zip"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                                    = "Block"  
  source                                = "some-local-file.zip"
}`

**Comment by fardarter** [comment]
You should be able to do this by getting the md5 hash, but I'm here looking for issues because that's not currently working.

**Comment by manicminer** [comment]
@KevinBrooke Thanks for opening this issue. As you mentioned, importing the resource is the best way to implement this kind of workflow and the `import` block allows you to do this inline within your config during a standard apply operation.

Since this seems to work for your use case, I'm going to close out this issue for now. If I've misunderstood the underlying issue, please feel free to comment further and we'll take another look. Thanks!
