### ISSUE TITLE
Refresh is not done in parallel

### ISSUE THREAD

**Issue by orgads** [hashicorp/terraform-provider-azurerm#22693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

All

### Terraform Configuration Files

```hcl
Any
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

When terraform refreshes on plan/apply with `-parallelism` set, the refresh should be done in parallel.

### Actual Behaviour

The azurerm provider runs az commands one at a time.

### Steps to Reproduce

terraform apply

**Comment by magodo** [comment]
@orgads Could you please provide the debug log that implies the refresh is running in serialization?

**Comment by orgads** [comment]
Actually I was looking at Process Explorer and noticed sequential processes of az cli. Looks like they are used for show account and get access token. The real operations do seem to work in parallel.

Can you explain why the same commands are executed many times on each apply?

**Comment by magodo** [comment]
@orgads That is because `terraform apply` is composed of several RPC calls, where each call will start and stop the provider, where each start of the provider will in turn configure the provider, which invokes the azure cli to do authentication. These RPC calls are in serialized.

**Comment by orgads** [comment]
Ok, thank you.
