### ISSUE TITLE
"The storage account named XXX is already taken" but the Azure API claims it is available, issues with MySQL flexible server too

### ISSUE THREAD

**Issue by ayelencasamassa** [hashicorp/terraform-provider-azurerm#22691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I'm creating a storage account and getting "The storage account named XXX is already taken".
But if I run: Get-AzStorageAccountNameAvailability -Name 'XX'
The result is: 

NameAvailable Reason Message
------------- ------ -------
         True

Also, I'm creating a MySQL Flexible server and getting: "Flexible Server Name: "XX": polling after Create: Code="ProvisioningDisabled" Message="The region is restricted."
I created a ticket to enable the region, MS has enabled the region but still having the issue.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server and azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "xxx" {
  name                              = var.xxx
  location                          = azurerm_resource_group.xxx.location
  resource_group_name               = azurerm_resource_group.xxx.name
  account_tier                      = var.xxx
  account_replication_type          = var.xxx
  min_tls_version                   = var.xxx
  enable_https_traffic_only         = var.xxx
  public_network_access_enabled     = var.xxx
  shared_access_key_enabled         = var.xxx
  access_tier                       = var.xxx
  queue_encryption_key_type         = var.xxx
  table_encryption_key_type         = var.xxx
  cross_tenant_replication_enabled  = var.xxx
  infrastructure_encryption_enabled = var.xxx

  routing{
    choice = "MicrosoftRouting"
  }

  network_rules {
    default_action = "Deny"
    bypass         = ["AzureServices"]
  }

  tags = {
    environment = var.xxx
  }
}

resource "azurerm_mysql_flexible_server" "xxx" {
  name                   = var.xxx
  resource_group_name    = azurerm_resource_group.xxx.name
  location               = azurerm_resource_group.xxx.location
  administrator_login    = var.xxx
  administrator_password = var.xxx
  backup_retention_days  = var.xxx
  delegated_subnet_id    = azurerm_subnet.xxx.id
  private_dns_zone_id    = azurerm_private_dns_zone.xxx.id
  sku_name               = var.xxx
  version                = var.xxx
  zone                   = var.xxx
  storage {
    size_gb = var.xxx
  }

  depends_on = [azurerm_private_dns_zone_virtual_network_link.xxx]

  tags = {
    environment = var.xxx
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Azure Storage Account "XXX": storage.AccountsClient#Create: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="StorageAccountAlreadyTaken" Message="The storage account named XXX is already taken."

Error: creating Flexible Server (Subscription: "XXX"
Resource Group Name: "XXX"
Flexible Server Name: "XXX"): polling after Create: Code="ProvisioningDisabled" Message="The region is restricted."
```

**Comment by magodo** [comment]
@ayelencasamassa This is an Azure API inconsistency issue, which I'm not sure why. This issue is not related to the provider, as you'll hit the same API error no matter which client you're using the create the storage account. You might want to raise a ticket against Azure to figure out why.

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).
