### ISSUE TITLE
Migrating from Azure CNI V1 to CNI Overlay is now possible without replacement

### ISSUE THREAD

**Issue by damienpontifex** [hashicorp/terraform-provider-azurerm#22704]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Release [2023-06-11](https://github.com/Azure/AKS/releases/tag/2023-06-11) of AKS now notes "[Migrating a cluster from Azure CNI V1 to CNI Overlay](https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay) is GA now."

The `kubernetes_cluster_resource` explicitly marks this as `ForceNew` https://github.com/hashicorp/terraform-provider-azurerm/blob/c21a632fd560778f0ba3780c21dfa3fd20533761/internal/services/containers/kubernetes_cluster_resource.go#L1044

### New or Affected Resource(s)/Data Source(s)

kubernetes_cluster_resource

### Potential Terraform Configuration

```hcl
No change from user code, only change within provider
```

### References

- https://github.com/Azure/AKS/releases/tag/2023-06-11
- https://learn.microsoft.com/en-us/azure/aks/azure-cni-overlay#upgrade-an-existing-cluster-to-cni-overlay

**Comment by aristosvo** [comment]
I'll take a look!
