### ISSUE TITLE
AKS - Default Node Pool Taints can't be updated

### ISSUE THREAD

**Issue by etaham** [hashicorp/terraform-provider-azurerm#22719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.66.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "this" {
  name                      = local.cluster_name
  location                  = var.location
  tags                      = local.tags
  resource_group_name       = var.resource_group_name
  dns_prefix                = var.dns_prefix
  kubernetes_version        = var.kubernetes_version
  private_cluster_enabled   = true
  private_dns_zone_id       = var.common_core_private_dns_zone
  disk_encryption_set_id    = var.disk_encryption_set_id
  node_resource_group       = var.node_resource_group_name
  sku_tier                  = "Standard"

  identity {
      type         = "UserAssigned"
      identity_ids = [var.aks_managed_identity.id]
  }

  default_node_pool {
    name                   = var.default_node_pool.name
    temporary_name_for_rotation = "tmp${var.default_node_pool.name}"
    vm_size                = var.default_node_pool.vm_size
    os_disk_size_gb        = var.default_node_pool.os_disk_size_gb
    zones                  = var.availability_zones
    orchestrator_version   = var.kubernetes_version
    vnet_subnet_id         = var.subnet_id
    enable_host_encryption = true
    tags                   = local.tags

    node_count = var.default_node_pool.node_count

    #additional optional parameters
    node_labels = var.default_node_pool.node_labels
    node_taints = var.default_node_pool.node_taints

    only_critical_addons_enabled = var.default_node_pool.only_critical_addons_enabled
  }
  
  network_profile {
    ...
  }

}
```

### Debug Output/Panic Output

```shell
Acquiring state lock. This may take a few moments...
module.aks_cluster.azurerm_kubernetes_cluster.this: Modifying... [id=...]

╷
│ Error: expanding `default_node_pool`: The AKS API has removed support for tainting all nodes in the default node pool and it is no longer possible to configure this. To taint a node pool, create a separate one.
│ 
│   with module.aks_cluster.azurerm_kubernetes_cluster.this,
│   on ... line 57, in resource "azurerm_kubernetes_cluster" "this":
│   57: resource "azurerm_kubernetes_cluster" "this" {
│
```

### Expected Behaviour

Per the documentation, the default node pool should be recreated with the changed taints as temporary_name_for_rotation is specified.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#node_taints.

My uneducated guess as to the issue is here: https://github.com/hashicorp/terraform-provider-azurerm/blob/c9648f3c6c633ac74c0a686bef98012c35775b35/internal/services/containers/kubernetes_nodepool.go#L173C1-L180C8
This block should have `ForceNew:     true,`

### Actual Behaviour

The error above

### Steps to Reproduce

1. Create a cluster without taints or temporary_name_for_rotation
2. Add temporary_name_for_rotation
3. Add taint the default pool.

**Comment by etaham** [comment]
This is the error code: https://github.com/hashicorp/terraform-provider-azurerm/blob/c9648f3c6c633ac74c0a686bef98012c35775b35/internal/services/containers/kubernetes_nodepool.go#L913C1-L918C3 

I don't know the code to know if this also needs to change (or if the forceNew flag will just bypass it)

**Comment by raghav19** [comment]
+1 on this issue with the latest provider `3.75.0` as well.

**Comment by stephybun** [comment]
Thanks for raising this issue @etaham and for pointing out this conflicting information in the documentation!

It doesn't actually make sense for `temporary_name_for_rotation` to allow users to update the value for `node_taints` since it isn't possible to set arbitrary node taints on the default node pool of a cluster at all. This is a [limitation in the AKS API](https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli#system-and-user-node-pools). Acceptable taints are exposed via other properties in the schema e.g. `only_critical_addons_enabled` which I see you're already using.

In fact it doesn't make sense for this property to exist in the schema for the `default_node_pool` anymore because of this limitation. I'm going to raise a PR to correct the documentation and to remove the `node_taint` property in the next major release of the provider.
