### ISSUE TITLE
data "azurerm_images" setting `images`: Invalid address to set: []string{"images", "0", "os_disk", "0", "disk_encryption_set_id"}

### ISSUE THREAD

**Issue by shasondrasvral** [hashicorp/terraform-provider-azurerm#22732]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.6 1.4.6 1.5.4

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_images

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
}

terraform {
  required_providers {
    azurerm = {
      version = "~> 3.0"
      source  = "hashicorp/azurerm"
    }
  }
}

data "azurerm_images" "images" {
  resource_group_name = "myRG"
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/shasondrasvral/b185247cf3cd6fa1e2243192f745effd
```

### Expected Behaviour

terraform.exe plan
data.azurerm_images.images: Reading...
data.azurerm_images.images: Read complete after 1s [id=resourceGroups/myRG/tags/[]/images]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are
needed.

### Actual Behaviour

terraform.exe plan
data.azurerm_images.images: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: setting `images`: Invalid address to set: []string{"images", "0", "os_disk", "0", "disk_encryption_set_id"}
│
│   with data.azurerm_images.images,
│   on main.tf line 15, in data "azurerm_images" "images":
│   15: data "azurerm_images" "images" {
│
╵

### Steps to Reproduce

terraform init
terraform plan

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Can you provide us with a more complete TF configuration? It will help with reproducing this issue.
Thanks!
