### ISSUE TITLE
azurerm_pim_active_role_assignment failing when the azurerm_role_definition is provisioned at a different subscription

### ISSUE THREAD

**Issue by davidng1996** [hashicorp/terraform-provider-azurerm#22730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.67

### Affected Resource(s)/Data Source(s)

azurerm_pim_active_role_assignment, azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "primary" {
}
resource "azurerm_role_definition" "example" {
  name        = "my-custom-role"
  scope       = data.azurerm_subscription.primary.id
  description = "This is a custom role created via Terraform"

  permissions {
    actions     = ["*"]
    not_actions = []
    data_actions = ["*"]
    not_data_actions = []
  }

  assignable_scopes = [
    data.azurerm_subscription.primary.id,
    "/subscriptions/<subscriptionID2>"
  ]

}

resource "azurerm_pim_active_role_assignment" "always_active_azure_role_assignment1" {
  scope              = data.azurerm_subscription.primary.id
  role_definition_id = azurerm_role_definition.example.role_definition_resource_id
  principal_id       = "<principal_id>"
  justification      = "Test1"


  schedule {
    expiration {
      duration_hours = 10
    }
  }
  timeouts {
    read = "1h"
    create = "1h"
  }
}

resource "azurerm_pim_active_role_assignment" "always_active_azure_role_assignment2" {
  scope              = "/subscriptions/<subscriptionID2>"
  role_definition_id = azurerm_role_definition.example.role_definition_resource_id
  principal_id       = "<principal_id>"
  justification      = "Test2"


  schedule {
    expiration {
      duration_hours = 10
    }
  }
  timeouts {
    read = "1h"
    create = "1h"
  }

}

resource "azurerm_pim_eligible_role_assignment" "eligible_azure_role_assignment1" {
  scope              = data.azurerm_subscription.primary.id
  role_definition_id = azurerm_role_definition.example.role_definition_resource_id
  principal_id       = "<principal_id>"
  justification      = "Test3"


  schedule {
    expiration {
      duration_hours = 10
    }
  }
  timeouts {
    read = "1h"
    create = "1h"
  }
}

resource "azurerm_pim_eligible_role_assignment" "eligible_active_azure_role_assignment2" {
  scope              = "/subscriptions/<subscriptionID2>"
  role_definition_id = azurerm_role_definition.example.role_definition_resource_id
  principal_id       = "<principal_id>"
  justification      = "Test4"


  schedule {
    expiration {
      duration_hours = 10
    }
  }
  timeouts {
    read = "1h"
    create = "1h"
  }

}
```

### Debug Output/Panic Output

```shell
Error: waiting for Role Management Policy: (Principal Id "<principal_id>" / Scope "/subscriptions/<subscriptionID2>" / Role Definition Id "<data.azurerm_subscription.primary.id>/providers/Microsoft.Authorization/roleDefinitions/<role_definition_id>") to become found: timeout while waiting for state to become 'Found' (last state: 'Missing', timeout: 5m0s)

Error: waiting for Role Management Policy: (Principal Id "<principal_id>" / Scope "/subscriptions/<subscriptionID2>" / Role Definition Id "<data.azurerm_subscription.primary.id>/providers/Microsoft.Authorization/roleDefinitions/<role_definition_id>") to become ready: couldn't find resource (21 retries)
```

### Actual Behaviour

Terraform code is failing but role assignments are created in azure portal

### References

Bug is not fixed for [#22588](https://github.com/hashicorp/terraform-provider-azurerm/issues/22588).

- You did not fix the timeout issue for azurerm_pim_active_role_assignment
- Unable to find role management policy for azurerm_pim_active_role_assignment and azurerm_pim_eligible_role_assignment when the role definition is at a different subscription

Terraform code is failing but all 4 PIM assignments (2x active 2x eligible) are created and can be found in Azure Portal.

**Comment by bardholthe** [comment]
Check https://github.com/hashicorp/terraform-provider-azurerm/pull/22756

Context deadline check was checking the wrong status value for error. This caused the "Delete" operation to always fail with the error message internal error: context has no deadline.

Awaiting approval

**Comment by davidng1996** [comment]
@tombuildsstuff @rcskosir This is not fixed. v3.68 still throwing out the same error.
