### ISSUE TITLE
Support for mongo_server_version 5.0

### ISSUE THREAD

**Issue by qqap** [hashicorp/terraform-provider-azurerm#22734]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

`mongo_server_version` 5.0 is in preview and has been available for 7 months ([quickstart w/ screenshots using v5.0](https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/quickstart-portal)), and I was using it for my server. I wanted to use terraform, but there is a validation check 
```
		"mongo_server_version": {
				Type:     pluginsdk.TypeString,
				Optional: true,
				Computed: true,
				ValidateFunc: validation.StringInSlice([]string{
					string(documentdb.ServerVersionThreeFullStopTwo),
					string(documentdb.ServerVersionThreeFullStopSix),
					string(documentdb.ServerVersionFourFullStopZero),
					string(documentdb.ServerVersionFourFullStopTwo),
				}, false),
			},
```
that prevents me from using it. Could we add the ServerVersionFiveFullStopZero! Ty!!

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
`mongo_server_version` would accept 5.0
```

**Comment by EpicWink** [comment]
Superceded by #25889
