### ISSUE TITLE
data.azurerm_virtual_machine.power_state returns null

### ISSUE THREAD

**Issue by danbarr** [hashicorp/terraform-provider-azurerm#22737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

data.azurerm_virtual_machine

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.5"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.67"
    }
  }
}

provider "azurerm" {
  features {}
}

# Tested with generation 1 and 2 VMs, provisioned using the azurerm_linux_virtual_machine resource and manually via the portal

data "azurerm_virtual_machine" "example" {
  name                = "my-running-vm"
  resource_group_name = "my-resource-group"
}
```

### Debug Output/Panic Output

```shell
The GET request we're sending is not including the `$expand=instanceView` query parameter:

GET /subscriptions/REDACTED/resourceGroups/rg-example-check/providers/Microsoft.Compute/virtualMachines/example-vm?api-version=2023-03-01 HTTP/1.1
```

### Expected Behaviour

The `power_state` attribute should return `running`, per the continuous validation example [documented here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/tfc-check-blocks).

Azure CLI output:
```
❯ az vm show -g my-resource-group -n my-running-vm --show-details --query "powerState"
"VM running"
```

Note `--show-details` is required to get powerState; this adds `$expand=instanceView` to the API query, which the data source is not sending.

### Actual Behaviour

The `power_state` attribute is `null`:

Snippet from state file:
```json
{
  "version": 4,
  "terraform_version": "1.5.4",

  "resources": [
    {
      "mode": "data",
      "type": "azurerm_virtual_machine",
      "name": "example",
      "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "location": "centralus",
            "name": "my-running-vm",
            "power_state": null,
```

### Steps to Reproduce

1. Create a virtual machine via any method
2. Populate `resource_group_name` and `name` in the `azurerm_virtual_machine` data source block in the example code
3. Run `terraform init && terraform apply`

**Comment by ned1313** [comment]
Issue still exists on v3.68.0 of the provider.
