### ISSUE TITLE
azurerm_cosmosdb_sql_database - setup CosmosDb emulator using Terraform

### ISSUE THREAD

**Issue by Radamonas** [hashicorp/terraform-provider-azurerm#22746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Question: is there a way to configure Azure CosmosDb emulator using Terraform. This could be used as part of CI/CD testing and local development environment setup. As currently all our CosmosDb databases, containers (partition keys, indexes) are managed via Terraform it would be useful to have possibility to apply same configs to local emulated CosmosDb instance

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_sql_database

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Maybe [local-exec Provisioner](https://developer.hashicorp.com/terraform/language/resources/provisioners/local-exec) is helpful.

**Comment by Radamonas** [comment]
@neil-yechenwei local-exec is not the thing I am looking for, I would need something to be able to apply cosmos terraform setup on CosmosDb emulator. There is a way to use PowerShell to configure emulator, however I haven't found a way to transfer config from Terraform files to PowerShell to execute it on emulator. I could create a specific config for PowerShell step, but this would create additional maintenance as changes planned for CosmosDb will have to be applied to PowerShell and Terraform (two different places, two different approaches).

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
