### ISSUE TITLE
azurerm_orchestrated_virtual_machine_scale_set updates Terraform state even if operation fails with 409 conflict

### ISSUE THREAD

**Issue by ben-east** [hashicorp/terraform-provider-azurerm#22768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.1

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
I don't believe this is specific to a configuration, any azurerm_orchestrated_virtual_machine_scale_set resource should be able to reproduce.
```

### Debug Output/Panic Output

```shell
Error: updating Linux Virtual Machine Scale Set "az-cpu-large-prod-wus3-sub4" (Resource Group "rg-hydra-team-backstage-prod-usw3"): compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=409 -- Original Error: Code="Conflict" Message="The request failed due to conflict with a concurrent request. To resolve it, please refer to https://aka.ms/activitylog to get more details on the conflicting requests."
```

### Expected Behaviour

The update request for the VMSS failed with a 409 conflict due to another concurrent operation and the VMSS was not updated. In this case, the Terraform state should not have been updated and the operation should have failed -- OR the Terraform provider should have retried the operation.

### Actual Behaviour

The operation failed due to a 409 response and did not update the VMSS, but Terraform state was updated to show that the change was successful. Refreshing state and retrying the Terraform plan was also unable to detect this inconsistency, requiring another code change to trigger a successful plan and apply.

### Steps to Reproduce

Perform concurrent operation on the VMSS while the apply operation occurs

**Comment by WodansSon** [comment]
@ben-east, thank you for reporting this issue, however I believe this scenario is not supported currently via the Terraform Azure RM provider. Terraform should be the only tool modifying the Azure resource at the time of the `apply`. Can you please explain your scenario in more detail in regards as to what tool sets, actions and configuration that were being executed when you received this error? It also might be worth noting here that the error:
```bash
 Failure sending request: StatusCode=409 -- Original Error: Code="Conflict" Message="The request failed due to conflict with a concurrent request. To resolve it, please refer to https://aka.ms/activitylog to get more details on the conflicting requests."
```
Is an error being raised from the RP and not from Terraform directly, which means that the actual native Azure RP was not happy with the concurrent actions and not the Terraform provider.
