### ISSUE TITLE
Support for AKS vNet Integration (Preview) switching clusters Private <--> Public

### ISSUE THREAD

**Issue by Bailey-T** [hashicorp/terraform-provider-azurerm#22767]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

AKS vNet Integration has been around for a while now in preview: https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration

Configuring it is supported in the `azurerm_kubernetes_cluster` resource with the following block:

```
  api_server_access_profile {
    vnet_integration_enabled = true
    subnet_id                = var.api_server_subnet_id
  }
```

But what it doesn't currently support is the operation of switching a cluster to/from Public and Private.

If a cluster is toggled (via Azure CLI/API, as per the docs) away from how it was built, it tags the cluster for destroy and recreate.

We can use lifecycle ignore as a workaround:
```
  lifecycle {
    ignore_changes = [
      private_cluster_enabled,
      private_dns_zone_id,
    ]
  }
```
But this doesn't seem like the right solution.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Maybe something like this:
  api_server_access_profile {
    vnet_integration_enabled = true
    vnet_integration_access  = var.public_or_private
    subnet_id                = var.api_server_subnet_id
  }
# And prevent the use of private_cluster_enabled/private_cluster_public_fqdn_enabled when vnet integration is configured.
```

### References

https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
