### ISSUE TITLE
`azurerm_postgresql_flexible_server` storage size validation doesn't match Azure API

### ISSUE THREAD

**Issue by cailyoung** [hashicorp/terraform-provider-azurerm#22775]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "reportportal_server" {
  administrator_login               = var.postgres_admin_username
  administrator_password            = var.postgres_admin_password
  backup_retention_days             = var.postgres_backup_retention_days
  geo_redundant_backup_enabled      = false
  location                          = "australiaeast"
  name                              = local.database_name
  resource_group_name               = var.resourcegroup
  sku_name                          = var.postgres_sku
  storage_mb                        = var.postgres_storage_mb
  version = "13"

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected storage_mb to be one of [32768 65536 131072 262144 524288 1048576 2097152 4194304 8388608 16777216 33553408], got 4193280
│ 
│   with azurerm_postgresql_flexible_server.reportportal_server,
│   on database.tf line 21, in resource "azurerm_postgresql_flexible_server" "reportportal_server":
│   21:   storage_mb                        = var.postgres_storage_mb
│ 
╵
```

### Expected Behaviour

The value for 4TB of storage should be able to be used.

### Actual Behaviour

Error in planning as shown above. If I use `4194304` then there is a diff in the plan saying that storage_mb has to be changed from `4193280` to `4194304`.

### Steps to Reproduce

1. Create an instance using Terraform
2. Increase storage to 4TB in the Azure portal
3. Attempt to match the configured storage in your Terraform config by updating the variable value

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems TF is aligned with Azure Portal since Azure Portal also requires 4194304(4096*1024) for 4TB.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/4551f7e9-90d6-4ca7-992c-e78d11fc2b49)

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei ‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
