### ISSUE TITLE
Logic App parameters can't be non-string

### ISSUE THREAD

**Issue by EpicWink** [hashicorp/terraform-provider-azurerm#22770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.4

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_workflow

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "test" {
  name     = "spam"
  location = "australiaeast"
}

resource "azurerm_logic_app_workflow" "test" {
  lifecycle {
    ignore_changes = [workflow_parameters, workflow_schema, workflow_version]
  }

  name                = "spam"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  parameters = {
    foo = "bar"
    baz = ["foo", "bar"]
  }

  access_control {
    trigger {
      allowed_caller_ip_address_range = ["0.0.0.0-255.255.255.255"]
    }
  }
}
```

### Debug Output/Panic Output

```shell
2023-08-02T11:20:36.411+1000 [ERROR] vertex "azurerm_logic_app_workflow.test" error: Incorrect attribute value type
```

### Expected Behaviour

Successful plan

### Actual Behaviour

Error, output:

```text
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 30, in resource "azurerm_logic_app_workflow" "test":
│   30:   parameters = {
│   31:     foo = "bar"
│   32:     baz = ["foo", "bar"]
│   33:   }
│ 
│ Inappropriate value for attribute "parameters": element "baz": string required.
╵
```

### Steps to Reproduce

1. `terraform plan`

### References

* #12314
* #7241

**Comment by ziyeqf** [comment]
Hi @EpicWink, thanks fore opening the issue.

The resource is working as expected, to pass an array to a parameter and keep the config clear please use `jsonencode` function. Here is an example based on the config provided in the description.
```
resource "azurerm_logic_app_workflow" "test" {
  lifecycle {
    ignore_changes = [workflow_parameters, workflow_schema, workflow_version]
  }

  name                = "spam"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  parameters = {
    foo = "bar"
    baz = jsonencode(["foo", "bar"])
  }

  access_control {
    trigger {
      allowed_caller_ip_address_range = ["0.0.0.0-255.255.255.255"]
    }
  }
}
```

For any further questions please leave comments, thanks!
