### ISSUE TITLE
Azure : frontend_ip_configuration & gateway_ip_configuration forces a case sensitive resource group update 

### ISSUE THREAD

**Issue by Rohan-Teli** [hashicorp/terraform-provider-azurerm#22780]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.1.2

### AzureRM Provider Version

3.45.0

### Affected Resource(s)/Data Source(s)

Application Gateway in Azure

### Terraform Configuration Files

```hcl
NA
```

### Debug Output/Panic Output

```shell
NA
```

### Actual Behaviour

Azure : frontend_ip_configuration & gateway_ip_configuration forces a case-sensitive resource group update when we run TF plan even though the resource group name is correct.

This causes Application gateway modification every time we run Terraform

**Comment by wuxu92** [comment]
@Rohan-Teli thanks for filing this issue. I mention that you are using an old provider verison of `v3.45.0`, could you please have a try with the latest provider to see if it has been fixed. and could you please share an exmple terraform configuration to reproduce this?
