### ISSUE TITLE
azurerm_storage_account with azure files authentication AADKERB & active directory settings

### ISSUE THREAD

**Issue by kaplik** [hashicorp/terraform-provider-azurerm#22784]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.65.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "this" {
  name                = "storageacc"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  account_tier              = "Premium"
  account_kind              = "FileStorage"
  account_replication_type  = "ZRS"
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"

  azure_files_authentication {
    directory_type = "AADKERB"
    active_directory {
      domain_name = "xxxxxxx"
      domain_guid = "xxxxxxx"
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

the following properties should not be required when `azure_files_authentication.directory_type` is set to `AADKERB`:
- domain_sid
- forest_name
- netbios_domain_name
- storage_sid

only `domain_name` and `domain_guid` should be required, see ARM spec: https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-bicep#activedirectoryproperties

Relevant part of the code: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/storage/storage_account_resource.go#L191

### Actual Behaviour

```
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "domain_sid" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "forest_name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "netbios_domain_name" is required, but no definition was found.
╵
╷
│ Error: Missing required argument
│ 
│   on storage.tf line 27, in resource "azurerm_storage_account" "this":
│   27:     active_directory {
│ 
│ The argument "storage_sid" is required, but no definition was found.
╵
```

**Comment by magodo** [comment]
Hi @kaplik, thank you for submitting this! I've tried to send the request without specifying some of these properties, but I got either of below errors:

- Status=400 Code="RequiredPropertyMissing" Message="The required property domainSid is missing."
- Status=400 Code="RequiredPropertyMissing" Message="The required property forestName is missing."

This more looks like a document error of Azure to me.

**Comment by kaplik** [comment]
@magodo interesting, because i'm able to do a REST requests and set just these only 2 properties:

```
az rest -m PATCH -u "https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx?api-version=2021-06-01" --body '
{
    "properties": {
        "azureFilesIdentityBasedAuthentication": {
            "directoryServiceOptions": "AADKERB",
            "activeDirectoryProperties": {
                "domainName": "xxx",
                "domainGuid": "xxx"
            }
        }
    }
}
'
```


debug from az cli
```
cli.azure.cli.core.util: Request URL: 'https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx?api-version=2021-06-01'
cli.azure.cli.core.util: Request method: 'PATCH'
cli.azure.cli.core.util: Request headers:
cli.azure.cli.core.util:     'User-Agent': 'python/3.10.12 (macOS-13.4.1-arm64-arm-64bit) AZURECLI/2.50.0 (HOMEBREW)'
cli.azure.cli.core.util:     'Accept-Encoding': 'gzip, deflate'
cli.azure.cli.core.util:     'Accept': '*/*'
cli.azure.cli.core.util:     'Connection': 'keep-alive'
cli.azure.cli.core.util:     'x-ms-client-request-id': '0c98ade4-cb8a-4093-8e20-8601278c23db'
cli.azure.cli.core.util:     'Content-Type': 'application/json'
cli.azure.cli.core.util:     'CommandName': 'rest'
cli.azure.cli.core.util:     'ParameterSetName': '-m -u --body --debug'
cli.azure.cli.core.util:     'Authorization': 'Bearer ...'
cli.azure.cli.core.util:     'Content-Length': '217'
cli.azure.cli.core.util: Request body:
cli.azure.cli.core.util: {"properties": {"azureFilesIdentityBasedAuthentication": {"directoryServiceOptions": "AADKERB", "activeDirectoryProperties": {"domainName": "xxx", "domainGuid": "xxx"}}}}
```

and response
```
cli.azure.cli.core.util: Response status: 200
cli.azure.cli.core.util: Response headers:
cli.azure.cli.core.util:     'Cache-Control': 'no-cache'
cli.azure.cli.core.util:     'Pragma': 'no-cache'
cli.azure.cli.core.util:     'Transfer-Encoding': 'chunked'
cli.azure.cli.core.util:     'Content-Type': 'application/json'
cli.azure.cli.core.util:     'Content-Encoding': 'gzip'
cli.azure.cli.core.util:     'Expires': '-1'
cli.azure.cli.core.util:     'Vary': 'Accept-Encoding'
cli.azure.cli.core.util:     'x-ms-request-id': '7c3ad816-667f-4b52-8257-ee0705071961'
cli.azure.cli.core.util:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
cli.azure.cli.core.util:     'Server': 'Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0'
cli.azure.cli.core.util:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
cli.azure.cli.core.util:     'x-ms-correlation-request-id': '73c4e3ca-7580-495d-ab3e-a992e6ab95fa'
cli.azure.cli.core.util:     'x-ms-routing-request-id': 'GERMANYWESTCENTRAL:20230803T093534Z:73c4e3ca-7580-495d-ab3e-a992e6ab95fa'
cli.azure.cli.core.util:     'X-Content-Type-Options': 'nosniff'
cli.azure.cli.core.util:     'Date': 'Thu, 03 Aug 2023 09:35:34 GMT'
cli.azure.cli.core.util: Response content:
```

and it is also possible to do it in Azure portal, the request from Azure portal (in dev tools in the browser) looks pretty much the same

**Comment by kaplik** [comment]
and this is how it looks in Azure portal
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2400039/8c8753ba-c55f-4fff-8d79-669b43919ec3)

**Comment by magodo** [comment]
@kaplik Sorry, I mis-read your configuration, I thought the `directory_type` was `AD`. From the [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account.html#active_directory):

> If directory_type is set to AADKERB, active_directory is not supported. Use [icals](https://learn.microsoft.com/en-us/azure/storage/files/storage-files-identity-auth-azure-active-directory-enable?tabs=azure-portal#configure-directory-and-file-level-permissions) to configure directory and file level permissions.

I'm not sure about the context why it isn't supported, but you can just ignore the `active_directory` block at all.

@petr-stupka, do you know why `active_directory` is not supported in this case?

**Comment by kaplik** [comment]
@magodo i believe that the `active_directory` block (or some similar alternative) should be supported when `directory_type` is set to `AADKERB`, as per MS documentation you should set the domain name & guid for hybrid user accounts: 
https://learn.microsoft.com/en-us/azure/storage/files/storage-files-identity-auth-hybrid-identities-enable?tabs=azure-portal#enable-azure-ad-kerberos-authentication-for-hybrid-user-accounts

so we can have: 
1. `active_directory` block with the mandatory domain name and guid parameters with the rest parameters as optional
2. or a new block `azure_active_directory`  block with the mandatory domain name and guid parameters and no other parameters (and this block would be only used when the directory type is `AADKERB`)

**Comment by magodo** [comment]
@kaplik Yeah, that's should be something doable, whilst I'd like to get the reason why @petr-stupka intentionally not supporting it for `AADKERB` back in https://github.com/hashicorp/terraform-provider-azurerm/pull/20168.

**Comment by petr-stupka** [comment]
Hi, correct, it should be doable. If i remember it correctly it wasn't possible to set the `active_directory` block without additional manual step. I think there is still warning in MS Docs about the preview.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/18548253/bf011834-c60a-4439-9775-3bc1c4586e85)

Our use case in AVD was solved by just adding `directory_type` = `AADKERB` and then run the `icalc` in additional script resource as mentioned the in comment.

So as i said, it should be doable, it was just a limitation at the implementation time.
Still the `active_directory` block should be optional.

Thank you
