### ISSUE TITLE
The feature flag <Microsoft.Automanage/AutomanageAlertsEnabled> must enabled on subscription: <subscription>, in order to use properties: <Alerts/AutomanageStatusChanges/Enable> with azurerm_automanage_configuration

### ISSUE THREAD

**Issue by BrianRichardson** [hashicorp/terraform-provider-azurerm#22799]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_automanage_configuration

### Terraform Configuration Files

```hcl
resource "azurerm_automanage_configuration" "example" {
  name                        = "Example"
  automation_account_enabled  = true
  boot_diagnostics_enabled    = true
  defender_for_cloud_enabled  = true
  guest_configuration_enabled = true
  log_analytics_enabled       = true
  status_change_alert_enabled = true
  antimalware {
    real_time_protection_enabled   = true
    scheduled_scan_enabled         = true
    scheduled_scan_type            = "Full"
    scheduled_scan_day             = 1
    scheduled_scan_time_in_minutes = 660
  }
  location            = "WestEurope"
  resource_group_name = "Example"
}
```

### Debug Output/Panic Output

```shell
Error: creating Automanage Configuration: (Configuration Profile Name "Example" / Resource Group "Example"): automanage.ConfigurationProfilesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidConfigurationValue" Message="The feature flag <Microsoft.Automanage/AutomanageAlertsEnabled> must enabled on subscription: <subscription>, in order to use properties: <Alerts/AutomanageStatusChanges/Enable>"
│ 
│   with azurerm_automanage_configuration.deploy,
│   on automanage.tf line 1, in resource "azurerm_automanage_configuration" "deploy":
│  1: resource "azurerm_automanage_configuration" "deploy" {
│ 
│ creating Automanage Configuration: (Configuration Profile Name "Example" / Resource Group "Example"): automanage.ConfigurationProfilesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 --
│ Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidConfigurationValue" Message="The feature flag <Microsoft.Automanage/AutomanageAlertsEnabled> must enabled on subscription:
│ <subscription>, in order to use properties: <Alerts/AutomanageStatusChanges/Enable>"
```

### Expected Behaviour

AutoManage Configuration created or updated.

### Actual Behaviour

AutoManage Configuration neither created nor updated.
Previously succeeded some weeks, or a few months ago. Suspect no longer succeeding due to change with Preview Features on Azure.
Possibly caused by "status_change_alert_enabled" option set to true. Changing to false seems to resolve the issue.

### Steps to Reproduce

terraform apply

**Comment by liuwuliuyun** [comment]
Hi @BrianRichardson, thanks for raising this issue. Like the error message indicates, this is a requirement from subscription. Let me try to reach out to service team and see how to enable this feature.

**Comment by liuwuliuyun** [comment]
To enable a feature flag in a subscription, you can follow these steps:


- Sign in to the [Azure portal](https://portal.azure.com/).

- Search for and select Subscriptions.

- Click on the subscription you want to enable the feature flag for.

- In the left-hand menu, click on Preview features.

- Find the feature flag you want to enable and click on it.

- Click the Register button to enable the feature flag for your subscription

Please note that the availability of feature flags may vary depending on the subscription and the specific service you are using. If you cannot find the feature flag you are looking for, you may need to refer to the documentation or support for the specific Azure service you are using.

**Comment by liuwuliuyun** [comment]
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/17947406/7507e68b-5a5d-4524-b75b-0d6a57cb721b)

**Comment by 2good4hisowngood** [comment]
so so sorry, this is purely my own homelab nonsense, please ignore.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @liuwuliuyun‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
