### ISSUE TITLE
Microsoft.MachineLearningServices │ The parsed Resource ID was missing a value for the segment at position 5 | parsing segment "staticMicrosoftDatabricks": expected the segment "Microsoft.Databricks" 

### ISSUE THREAD

**Issue by mmohamednazeer** [hashicorp/terraform-provider-azurerm#22818]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

We are creating an databricks workspace through terraform, while creating databricks workspace we are adding aml workspace id as part custom parameters. 

But earlier it was worked as expected not from today its throwing the parse error. 

Its weird why they expecting  "Microsoft.Databricks" as a provider for aml workspace id.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.2

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "databricks_ws" {
  name                = "mydatabrics_ws_name"
  resource_group_name = var.resource_group_name
  location            = var.location
  sku                 = "premium"  

  custom_parameters {
    no_public_ip        = false
    public_subnet_name  = azurerm_subnet.databricks_public_subnet.name
    private_subnet_name = azurerm_subnet.databricks_private_subnet.name
    virtual_network_id  = var.virtual_network_id

    public_subnet_network_security_group_association_id  = azurerm_subnet_network_security_group_association.public.id
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id

    machine_learning_workspace_id = var.machine_learning_workspace_id
  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/<!-- my subscription>/resourceGroups/<!-- my resource group name>/providers/Microsoft.MachineLearningServices/workspaces/<!-- my aml workspace name>": parsing segment "staticMicrosoftDatabricks": parsing the Workspace ID: the segment at position 5 didn't match
│ 
│ Expected a Workspace ID that matched:
│ 
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Databricks/workspaces/workspaceValue
│ 

│ However this value was provided:
│ 
│ > /subscriptions/<!-- my subscription>/resourceGroups/<!-- my resource group name>/providers/Microsoft.MachineLearningServices/workspaces/<!-- my aml workspace name>
│ 
│ The parsed Resource ID was missing a value for the segment at position 5
│ (which should be the name of the Resource Provider [for example 'Microsoft.Databricks']).
│ 
│ 
│ 
│   with module.databricksws.azurerm_databricks_workspace.databricks_ws,
│   on ../../modules/databricks/databricks_ws.tf line 82, in resource "azurerm_databricks_workspace" "databricks_ws":
│   82:     machine_learning_workspace_id = var.machine_learning_workspace_id
│ 
╵
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: parsing "/subscriptions/<!-- my subscription>/resourceGroups/<!-- my resource group name>/providers/Microsoft.MachineLearningServices/workspaces/<!-- my aml workspace name>": parsing segment "staticMicrosoftDatabricks": parsing the Workspace ID: the segment at position 5 didn't match
│ 
│ Expected a Workspace ID that matched:
│ 
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Databricks/workspaces/workspaceValue
│ 
│ However this value was provided:
│ 
│ > /subscriptions/<!-- my subscription>/resourceGroups/<!-- my resource group name>/providers/Microsoft.MachineLearningServices/workspaces/<!-- my aml workspace name>
│ 
│ The parsed Resource ID was missing a value for the segment at position 5
│ (which should be the name of the Resource Provider [for example 'Microsoft.Databricks']).
│ 
│ 
│ 
│   with module.databricksws.azurerm_databricks_workspace.databricks_ws,
│   on ../../modules/databricks/databricks_ws.tf line 82, in resource "azurerm_databricks_workspace" "databricks_ws":
│   82:     machine_learning_workspace_id = var.machine_learning_workspace_id
│ 
╵
```

### Expected Behaviour

Data bricks workspace should be created with azure machine learning workspace as custom parameter. 

### Actual Behaviour

parsing "/subscriptions/bcb49ec5-052d-46ed-837d-a1e1959fe22a/resourceGroups/rg-mf-dev-it4it9/providers/Microsoft.MachineLearningServices/workspaces/amlws-mf-dev-it4it9": parsing segment "staticMicrosoftDatabricks": parsing the Workspace ID: the segment at position 5 didn't match

Expected a Workspace ID that matched:
> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Databricks/workspaces/workspaceValue

However this value was provided:

> /subscriptions/<!--mysubscriptionid>/resourceGroups/<!--myresourcegroup>/providers/Microsoft.MachineLearningServices/workspaces/<!--myamlworkspacename>

The parsed Resource ID was missing a value for the segment at position 5
(which should be the name of the Resource Provider [for example 'Microsoft.Databricks']).

### Steps to Reproduce

terraform apply

### Important Factoids

no

**Comment by WodansSon** [comment]
Hi @mmohamednazeer, thank you for opening this issue. I will look in to it and see if anything has changed recently. 🚀

**Comment by mmohamednazeer** [comment]
Thanks for fixing the issue! I will  check and update here as well.
