### ISSUE TITLE
ingress_application_gateway block does not enable AGIC add-on

### ISSUE THREAD

**Issue by thesse1** [hashicorp/terraform-provider-azurerm#22830]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster, azurerm_application_gateway

### Terraform Configuration Files

```hcl
https://gist.github.com/thesse1/64da3a85321684625273dba6454fd73e
```

### Debug Output/Panic Output

```shell
https://gist.github.com/thesse1/dbd8371f842caee63a5a7e9c07ec0cf7
```

### Expected Behaviour

Application Gateway Ingress Controller (AGIC) should have been configured and enabled. It should have injected the tags ingress-for-aks-cluster-id and managed-by-k8s-ingress into the AG instance. The AG activity log should show the action of the ingress controller updating AG. After deploying an ingress in the AKS cluster, it should create the corresponding backend and routing rule in AG, and the ingress should work.

### Actual Behaviour

The Azure Portals shows the AGIC as configured and enabled on the Network pane of the AKS cluster, but it has not really configured the AG for AGIC. For example, you do not see the tags ingress-for-aks-cluster-id and managed-by-k8s-ingress on the AG. Also, when you deploy an app with ingress to the AKS cluster, the ingress will not be reflected in AG (backend, routing rule), and it will not work, i.e., no loadbalancer IP will be assigned to the ingress. The AG activity log does not show any action of the ingress controller. Please note that this is working fine when you leave out the ingress_application_gateway block and configure AGIC manually in the Azure Portal or using az aks enable-addons -a ingress-appgw.

### Steps to Reproduce

2. az aks get-credentials --resource-group bug-report-rg --name bug-report-cluster
3. kubectl apply -f https://raw.githubusercontent.com/Azure/application-gateway-kubernetes-ingress/master/docs/examples/aspnetapp.yaml

### Important Factoids

No

**Comment by thesse1** [comment]
Just found out the root cause of the issue by inspecting the log of the ingress pod. It is missing the role assignments that are automatically created when you enable the add-on using the Azure Portal or az aks enable-addons -a ingress-appgw. Working fine again when I add the role assignments in Terraform. Just a hint: Maybe you could add this to the documentation for azurerm_kubernetes_cluster? Thanks!

**Comment by SaumyaBhushan** [comment]
Hey @thesse1 ! For me the issue is little bit different. When I am using this ingress_application_gateway block with gateway_name and subnet_id argument , aks is being creation just fine with the add on enabled and attached application gateway but when I am clicking on gateway link its is showing **resource not found** . The message that is being displayed near near ingress controller add on check box is **Ingress controller has not created the application gateway yet. It may take up to 15 mins before the application gateway gets created.** but i have waited for more than an hour and it has not been created yet .

What could e the reason for that ?

**Comment by SaumyaBhushan** [comment]
As you said it is working fine for me aswell when I configure AGIC manually in the Azure Portal or using az aks enable-addons -a ingress-appgw.
