### ISSUE TITLE
azurerm_key_vault_key resets expiration_date when autorotation is enabled

### ISSUE THREAD

**Issue by mruoss** [hashicorp/terraform-provider-azurerm#22838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.4.2

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_key

### Terraform Configuration Files

```hcl
# mostly copied from your docs

provider "azurerm" {
  features {
    key_vault {
      purge_soft_deleted_keys_on_destroy = true
      recover_soft_deleted_keys          = true
    }
  }
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_key_vault" "example" {
  name                       = "examplekeyvault"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  tenant_id                  = data.azurerm_client_config.current.tenant_id
  sku_name                   = "premium"
  soft_delete_retention_days = 7

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Create",
      "Delete",
      "Get",
      "Purge",
      "Recover",
      "Update",
      "GetRotationPolicy",
      "SetRotationPolicy"
    ]

    secret_permissions = [
      "Set",
    ]
  }
}

resource "azurerm_key_vault_key" "generated" {
  name         = "generated-certificate"
  key_vault_id = azurerm_key_vault.example.id
  key_type     = "RSA"
  key_size     = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]

  rotation_policy {
    automatic {
      time_before_expiry = "P30D"
    }

    expire_after         = "P90D"
    notify_before_expiry = "P29D"
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_key_vault_key.generated will be updated in-place
  ~ resource "azurerm_key_vault_key" "generated" {
      - expiration_date         = "2023-10-31T16:07:36Z" -> null
        id                      = "https://examplekeyvault.vault.azure.net/keys/generated-certificate/87f70e6ddfec458593933d48f8cd8afe"
        name                    = "generated-certificate"
        # (12 unchanged attributes hidden)
```

### Expected Behaviour

When the autorotation policy is enabled, the `expiration_date` is set by Azure each time the key is rotated. Terraform should not (try to) reset it.

### Actual Behaviour

Terraform tries to reset the `expiration_date` to `null` or to the value that is configured. That value should only be used for the first version of the key.

### Steps to Reproduce

1. `terraform apply`
2. rotate the key manually via the azure portal
3. `terraform init` => The plan shows the changes

**Comment by wuxu92** [comment]
Hi @mruoss thanks for raising this issue. because the `expiration_date` can be set by both user and Azure, if this field is set/updated by azure, then you should add add it to [`ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes). This is a bydesign of terraform schema.

```
resource "azurerm_key_vault_key" "generated" {

  lifecycle {
    ignore_changes = [expiration_date]
  }
}
```

**Comment by mruoss** [comment]
Oh I see! I did not know about this. Thanks for taking the time.

**Comment by mpjtaylor** [comment]
Still an issue in 3.71.0
Error: 'auto_key_rotation_enabled' field is set to 'true' expected a key vault key with a versionless ID but version information was found:
