### ISSUE TITLE
Doc: Emphasize that `azurerm_kubernetes_cluster.temporary_name_for_rotation` affects service availability

### ISSUE THREAD

**Issue by yoshigev** [hashicorp/terraform-provider-azurerm#22849]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.2

### AzureRM Provider Version

3.63.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  default_node_pool {
    name = "default"
    temporary_name_for_rotation = "defaulttemp"
  }
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

I initially expected that by setting `temporary_name_for_rotation`, when I'll make changes that requires re-creation of the node pool, it will be done gracefully.

### Actual Behaviour

I understand that AKS gives no API for doing it gracefully (e.g., by using Cordon and Drain).

So my request is that it will be noted clearly that setting `temporary_name_for_rotation` might be service-affective, as the node pool is deleted in a non-graceful manner.

**Comment by ms-henglu** [comment]
Hi @rcskosir ,

Thank you for taking time to report this issue!

> it will be noted clearly that setting temporary_name_for_rotation might be service-affective, as the node pool is deleted in a non-graceful manner.

Would you please share us more details about "as the node pool is deleted in a non-graceful manner"?

**Comment by yoshigev** [comment]
Hi @ms-henglu,

See [this Azure doc](https://learn.microsoft.com/en-us/azure/aks/resize-node-pool?tabs=azure-cli) for how to resize VMs in a node pool. It explains that the "recommended method" (i.e., that is graceful) is that prior to performing `delete` of a node pool, need to perform Cordon and Drain, so no pods will run on the pods when they'll get deleted.

As Cordon and Drain operations are not accessible via AKS API, Terraform Azurerm provider cannot perform them, so the deletion of the node pool is done brutally.

This is the relevant excerpt from the above doc (it was added following [this ticket](https://github.com/MicrosoftDocs/azure-docs/issues/90398)):
> When you delete a node pool, AKS doesn't perform cordon and drain. To minimize the disruption of rescheduling pods currently running on the node pool you are going to delete, perform a cordon and drain on all nodes in the node pool before deleting.

This is why I think that the documentation should mention that setting `temporary_name_for_rotation` might cause this non-graceful deletion of the node pool.

Thanks.
