### ISSUE TITLE
`azurerm_disk_encryption_set` - `azurerm_key_vault_key` stuck to specific version

### ISSUE THREAD

**Issue by mbassett** [hashicorp/terraform-provider-azurerm#22864]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.62.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_key

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault_key" "example-disk" {
  name            = "example-disk-key"
  key_vault_id    = azurerm_key_vault.example.id
  key_type        = "RSA"
  key_size        = 4096

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]

  rotation_policy {
    automatic {
      time_before_expiry = "P30D"
    }

    expire_after         = "P90D"
    notify_before_expiry = "P29D"
  }
}

resource "azurerm_disk_encryption_set" "example" {
  name                      = "example"
  resource_group_name       = azurerm_resource_group.example.name
  key_vault_key_id          = azurerm_key_vault_key.example-disk.id
  location                  = azurerm_resource_group.example.location
  auto_key_rotation_enabled = true
  identity {
    type = "SystemAssigned"
  }
  depends_on = [azurerm_key_vault_key.example-disk]
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Key should be rotated automatically and terraform should not try to keep setting the old expired keys active at the next run

### Actual Behaviour

terraform wants to set the original old key on next run

attempting to use versionless_id  or resource_versionless_id  results in errors about the number of elements or that the key needs to be versioned.

### Steps to Reproduce

create an azure key using terraform
add a newer key via automatic rotation, or manually
you will note the encryption set now shows the newer key (because we have   auto_key_rotation_enabled = true ), but running terraform plan it wants to replace the newer key with the older key.

**Comment by wuxu92** [comment]
hi @mbassett thanks for rasing this issue. this looks like the same issue as https://github.com/hashicorp/terraform-provider-azurerm/issues/22838. could you please have a look there? please feel free to append to this issue if #22838 does not resolve your problem.

**Comment by mbassett** [comment]
Doesn't resolve the issue.
I already have the life cycle ignore on the key.

The issue is when the key rotates terraform keeps using the original key
created.  The disk encryption set updates to the new key but every time
terraform runs it wants to change the target key Id back to the expired key.

**Comment by WodansSon** [comment]
@wuxu92 @mbassett, I looked at the code and to me it appears to be a bug in the way the `azurerm_disk_encryption_set` resources schema is defined for the `key_vault_key_id`:

```go
"key_vault_key_id": {
  Type:         pluginsdk.TypeString,
  Required:     true,
  ValidateFunc: keyVaultValidate.NestedItemId,
},
```

The `NestedItemId` validation function requires a key version and should prolly be calling the `NestedItemIdWithOptionalVersion` function instead for the `ValidateFunc` in the schema. That said, there should also prolly be a secondary check in the create/update functions to see if the `auto_key_rotation_enabled` field is set to `true` or not. If the `auto_key_rotation_enabled` is `true` and the `key_vault_key_id` points to or is defined with a version it should then raise an error stating that the `key_vault_key_id` must be versionless if `auto_key_rotation_enabled` is set to `true`.

**Comment by mbassett** [comment]
That explanation sounds correct and matches the symptoms I was seeing.

**Comment by riemers** [comment]
Seeing the same issue, funny to see only a 5 days old issue with an already open ready for review PR which resolves it. Very nice, can also be said sometimes. (Assuming it gets merged in the same speed)

**Comment by mpjtaylor** [comment]
I see this was fixed in v3.71.0 however I still get the error:

Error: 'auto_key_rotation_enabled' field is set to 'true' expected a key vault key with a versionless ID but version information was found:

**Comment by wuxu92** [comment]
@mpjtaylor as the error message says that you have to provide a versionless keyvault key id when `auto_key_rotation_enabled` is `true`. or could you please share your configuration?

**Comment by mpjtaylor** [comment]
@wuxu92  thanks understand now got it from the example here https://github.com/hashicorp/terraform-provider-azurerm/blob/main/website/docs/r/disk_encryption_set.html.markdown
