### ISSUE TITLE
Unable to enable ingress_application_gateway 

### ISSUE THREAD

**Issue by lambertpan** [hashicorp/terraform-provider-azurerm#22861]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurem_3.64.0

### Terraform Configuration Files

```hcl
dynamic "ingress_application_gateway" {
    for_each = var.ingress_application_gateway_enabled ? [1] : []
    content {

    }

  }
```

### Debug Output/Panic Output

```shell
“ingress_application_gateway.0.subnet_id”: one of
ingress_application_gateway.0.gateway_id,ingress_application_gateway.0.subnet_cidr,ingress_application_gateway.0.subnet_idmust be specified

The document says values under ingress_application_gateway are optional;  but the ingress gateway is not created\enabled if subnet_cidr is not specified
```

### Expected Behaviour

- The document says values under ingress_application_gateway are optional;  so ingress gateway needs to be enabled if subnet_cidr is not specified also
- Ingress gateway needs to work without specifying any optional field. 

<img width="713" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/10847950/68f8e81d-f049-44a6-b0a6-e84dec69e020">

### Actual Behaviour

- The document says values under ingress_application_gateway are optional;  but the ingress gateway is not created\enabled if subnet_cidr is not specified
- Terraform import is not importing subnet_cidr but it imports gateway_name which is not present in the document.

**Comment by teowa** [comment]
Hi @lambertpan , thanks for submitting this!
the related resource be [`azurerm_kubernetes_cluster`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#ingress_application_gateway). By checking the source code, the doc need to update to: 
> Exactly one of the `gateway_id`, `subnet_cidr`, `subnet_id` must be specified.

**Comment by lambertpan** [comment]
Thanks.

One more point, if I do import, I don't get the values you mentioned above. Please check the screenshot below;

This becomes difficult if I do an update from 2.x module to 3.x,  because these are not mandatory fields in 2.x azurerm providers. 

I have enabled ingress_application_gateway addon using 2.x, Now, if I try the same with 3.x, it is asking for subnet_cidr , so what is the guideline for migrating ingress_application_gateway from 2.x. to 3.x? Why it couldn't find pre-exiting addon from the backend state?

Screenshot of import
<img width="582" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/10847950/a0353fad-0fb9-4916-9e48-550120dd0c6c">

**Comment by teowa** [comment]
If we don't specify anything in `ingress_application_gateway`, the service API will return error: 
```
Kubernetes Cluster Name: "acctestaks230809142452168144"): managedclusters.ManagedClustersClient#CreateOrUpdate: 
Failure sending request: StatusCode=0 --
Original Error: Code="IngressAppGwAddonConfigProvideEitherApplicationGatewayIDOrSubnet" 
Message="Please either provide 'applicationGatewayId' to use an existing Application Gateway or provide 'subnetCIDR' or 'subnetId' which will be used to deploy a new Application Gateway for IngressApplicationGateway addon. Please refer to https://aka.ms/aks/agic." 
Target="AddonProfiles.IngressApplicationGateway"

```  

If the `gateway_id` is not set before,  we may just set it to `effective_gateway_id` when migrating from 2.x to 3.x

**Comment by lambertpan** [comment]
When migrating from 2.x to 3.x, if I set `effective_gateway_id`, I get an error `its value will be decided automatically based on the result of applying this. configuration.`. This comes along with missing required arguments.

So we can't use `effective_gateway_id`? This is also not mentioned in the document. 

Also, is `subnet_cidr` mandatory for migrating 2.x. to 3.x? This is also not mentioned in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/3.0-upgrade-guide


Error from terraform apply
`Error: Missing required argument
  on main.tf line 28, in resource "azurerm_kubernetes_cluster" "k8s":
  28: resource "azurerm_kubernetes_cluster" "k8s" {
"ingress_application_gateway.0.subnet_id": one of
ingress_application_gateway.0.gateway_id,ingress_application_gateway.0.subnet_cidr,ingress_application_gateway.0.subnet_id must be specified`

`Error: Value for unconfigurable attribute
  on main.tf line 28, in resource "azurerm_kubernetes_cluster" "k8s":
  28: resource "azurerm_kubernetes_cluster" "k8s" {
Can't configure a value for
"ingress_application_gateway.0.effective_gateway_id": its value will be
decided automatically based on the result of applying this configuration`

**Comment by lambertpan** [comment]
Can you please reopen the issue as there is no clear instruction for migrating  ingress_application_gateway controller from 2.x to 3.x ? The suggested `effective_gateway_id` is not working.

**Comment by teowa** [comment]
@lambertpan , from error message we cannot set `effective_gateway_id` but have to set config like: 
```hcl
  ingress_application_gateway {
    gateway_name = "ingress-appgateway"
    gateway_id = "/subscription/xxx..."
  }
```
