### ISSUE TITLE
azurerm_backup_policy_file_share: inquire all unprotected files shares under a storage account, item not found

### ISSUE THREAD

**Issue by CityHallin** [hashicorp/terraform-provider-azurerm#22882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5 windows_amd64

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_backup_policy_file_share

### Terraform Configuration Files

```hcl
terraform {
  backend "local" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.68.0"
    }
  }
}

provider "azurerm" {
  features {}
}

#Locals
locals {
  project  = "<ENTER_ALPHANUMERIC_STRING>"
  location = "<ENTER_AZURE_LOCATION>"
}

#Create Azure Resource Group
resource "azurerm_resource_group" "rg" {
  name     = "${local.project}-rg"
  location = local.location
}

#Create Azure Recovery Services Vault
resource "azurerm_recovery_services_vault" "rsv" {
  name                = "${local.project}-rsv"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  sku                 = "Standard"
}

#Create Azure Storage Account
resource "azurerm_storage_account" "sa" {
  name                     = "${local.project}sa"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

#Create Azure Storage Account Share
resource "azurerm_storage_share" "ss" {
  name                 = "${local.project}-share"
  storage_account_name = azurerm_storage_account.sa.name
  quota                = 50
}

#Register Storage Account with Recovery Services Vault
resource "azurerm_backup_container_storage_account" "rsv_reg" {
  resource_group_name = azurerm_resource_group.rg.name
  recovery_vault_name = azurerm_recovery_services_vault.rsv.name
  storage_account_id  = azurerm_storage_account.sa.id
}

#Create Recovery Services Vault backup policy
resource "azurerm_backup_policy_file_share" "rsv_policy" {
  name                = "${local.project}-rsv-policy"
  resource_group_name = azurerm_resource_group.rg.name
  recovery_vault_name = azurerm_recovery_services_vault.rsv.name

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 3
  }
}

# Add Storage Account share to Recovery Services Vault backup items
resource "azurerm_backup_protected_file_share" "rsv_share" {
  resource_group_name       = azurerm_resource_group.rg.name
  recovery_vault_name       = azurerm_recovery_services_vault.rsv.name
  source_storage_account_id = azurerm_storage_account.sa.id
  source_file_share_name    = azurerm_storage_share.ss.name
  backup_policy_id          = azurerm_backup_policy_file_share.rsv_policy.id
}
```

### Debug Output/Panic Output

```shell
Error: inquire all unprotected files shares under a storage account "<STORAGE_ACCOUNT_NAME>" (Resource Group "<RESOURCE_GROUP_NAME>"): protectioncontainers.ProtectionContainersClient#Inquire: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="BMSUserErrorContainerObjectNotFound" Message="Item not found. Item could have been deleted. Please check if item is present in Backup Items."
│
│   with azurerm_backup_protected_file_share.rsv_share,
│   on main.tf line 78, in resource "azurerm_backup_protected_file_share" "rsv_share":
│   78: resource "azurerm_backup_protected_file_share" "rsv_share"
```

### Expected Behaviour

The Azure Storage Account Share would show up as a Backup Item in the Recovery Services Vault

### Actual Behaviour

The error above would appear. The Storage Account is successfully registered as Backup Infrastructure in the Recovery Services Vault, but the share is not a Backup Item. I noticed if I waited 5 minutes after the failed Terraform Apply attempt and re-ran a Terraform Apply with the exact same code, the azurerm_backup_protected_file_share would show as the only creation and everything would run just fine with the share being added as a Backup Item in the Recovery Services Vault as expected.

### Steps to Reproduce

Saving the above code into a main.tf and running Terraform Init, Terraform Apply. 

### References

Initially thought this was related, but now I do not think so. https://github.com/hashicorp/terraform-provider-azurerm/pull/14238

**Comment by ziyeqf** [comment]
Hi @CityHallin, thanks for opening the issue.

Per the debug output, I assume it should be caused because `azurerm_backup_protected_file_share` was created before `azurerm_backup_container_storage_account` was created.
There are two ways to add the dependency:
1. use `azurerm_backup_container_storage_account.rsv_reg.storage_account_id` to reference the storage account. (Recommand)
```
resource "azurerm_backup_protected_file_share" "rsv_share" {
  resource_group_name       = azurerm_resource_group.rg.name
  recovery_vault_name       = azurerm_recovery_services_vault.rsv.name
  source_storage_account_id = azurerm_backup_container_storage_account.rsv_reg.storage_account_id
  source_file_share_name    = azurerm_storage_share.ss.name
  backup_policy_id          = azurerm_backup_policy_file_share.rsv_policy.id
}
```
2. add  `depends_on` manually
```
resource "azurerm_backup_protected_file_share" "rsv_share" {
  resource_group_name       = azurerm_resource_group.rg.name
  recovery_vault_name       = azurerm_recovery_services_vault.rsv.name
  source_storage_account_id = azurerm_storage_account.sa.id
  source_file_share_name    = azurerm_storage_share.ss.name
  backup_policy_id          = azurerm_backup_policy_file_share.rsv_policy.id

  depends_on = [azurerm_backup_container_storage_account.rsv_reg]
}
```

Please let me know if it works or not. For any further questions please leave comments.

Thanks!

**Comment by CityHallin** [comment]
@ziyeqf I appreciate the reply. Option #1 you mentioned worked like a champ. Thanks!
