### ISSUE TITLE
TF does not change disk caching before attaching to VM

### ISSUE THREAD

**Issue by MmAtBosch** [hashicorp/terraform-provider-azurerm#22896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.58.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "vm" {
  name                  = var.vm
  location              = azurerm_resource_group.vm.location
  resource_group_name   = azurerm_resource_group.vm.name
  network_interface_ids = [azurerm_network_interface.nic.id]
  vm_size               = var.vm_size
  zones                 = 1

  storage_data_disk {
    name = var.data_disk
    # Azure only supports disk caching with sizes smaller 4096 gb
    caching           = var.data_disk_size_gb < 4096 ? "ReadOnly" : "None"
    create_option     = "Attach"
    managed_disk_type = "Premium_LRS"
    disk_size_gb      = var.data_disk_size_gb
    lun               = 0
    managed_disk_id   = azurerm_managed_disk.vm.id
  }
}

resource "azurerm_managed_disk" "vm" {
  name                 = var.data_disk
  location             = azurerm_resource_group.vm.location
  resource_group_name  = azurerm_resource_group.vm.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = 4096
  tier                 = P50
  zone                 = 1

  lifecycle {
    ignore_changes = [
      create_option,
      source_resource_id,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Error: `disk_size_gb` can't be increased above 4095GB when `caching` is set to anything other than `None`
```

### Expected Behaviour

Set the disk caching to "None" before trying to detach/increase and attach the disk as shown in the TF plan.

      ~ storage_data_disk {
          ~ caching                   = "ReadOnly" -> "None"
          ~ disk_size_gb              = 4095 -> 4096
            name                      = "vm-02-disk"
            # (5 unchanged attributes hidden)
        }

### Actual Behaviour

Terraform plans the change properly

but then fails, because he tries to attach the disk with the old caching instead of taking the new caching value into account, before doing the attach.

azurerm_network_interface.nic: Modifying... 
azurerm_managed_disk.vm: Modifying... 
azurerm_network_interface.nic: Modifications complete after 0s
data.azurerm_monitor_diagnostic_categories.nic: Reading...
data.azurerm_monitor_diagnostic_categories.nic: Read complete after 1s
╷
│ Error: `disk_size_gb` can't be increased above 4095GB when `caching` is set to anything other than `None`
│ 
│   with azurerm_managed_disk.vm,
│   on main.tf line 75, in resource "azurerm_managed_disk" "vm":
│   75: resource "azurerm_managed_disk" "vm" {
│ 
╵

### Steps to Reproduce

Having a VM with a disk smaller than 4096 with host caching set to Read-Only.

Having following if else in the respective caching option:
caching           = var.data_disk_size_gb < 4096 ? "ReadOnly" : "None"

Chaning the disk size in the code higher than 4095.

Doing TF plan/apply

**Comment by MmAtBosch** [comment]
Also does not work when just configuring
caching           = "None"
and sik size 4096

without any if else

**Comment by myc2h6o** [comment]
@MmAtBosch thanks for opening the issue. When updating the Disk size in `azurerm_managed_disk`, Terraform has no information that the `caching` in Virtual Machine is going to be updated during the same apply, and the `caching` is not settable on the disk resource itself. And because the virtual machine depends on this data disk, the virtual machine will be updated after the data disk. so unfortunately, you would need to update the `cacing` to `None` on the first apply, then updating the disk size on the second apply.

**Comment by MmAtBosch** [comment]
thanks for your reply @myc2h6o 
But actually i just change two values in the same "azurerm_virtual_machine" resource 
```
storage_data_disk {
      ~ caching                   = "ReadOnly" -> "None"
      ~ disk_size_gb              = 4095 -> 4096
```

so in the first step it´s not about azurerm_managed_disk.

in my opinion it would just help, if the provider changes the sequence of both changes.

1. handling the caching
2. changing the disk size

**Comment by myc2h6o** [comment]
@MmAtBosch `azurerm_virtual_machine` is in a feature frozen state, and we are not able to touch it any more. You may wanna try `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine`.

For this issue, the Disk Size specified in the VM has to match the value in Managed Disk resource, the error you shared happens in the `azurerm_managed_disk` resource.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @myc2h6o‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
