### ISSUE TITLE
Support for enabling azure ad authentication on azurerm_mssql_virtual_machine without needing to run az cli

### ISSUE THREAD

**Issue by jwshive** [hashicorp/terraform-provider-azurerm#22904]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Add the ability to enable Azure Active Directory authentication for azurerm_mssql_virtual_machine resource.

The only way I can see right now to add azure active directory authentication to an Azure Sql Server virtual machine is to run an az cli command as a null resource. I'd like to have an azuread_administrator block for SQL Server virtual machines like we have for other resource types.

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_virtual_machine

**Comment by myc2h6o** [comment]
@jwshive thanks for opening the issue! `mssql_virutal_machine` does not have the property to configure the AD administrator block as what `azurerm_mssql_server` provided ([Swagger](https://github.com/Azure/azure-rest-api-specs/blob/0f8c649c09e568bf3c0d72a114ede33c418a2a49/specification/sql/resource-manager/Microsoft.Sql/stable/2021-11-01/Servers.json#L981-L982)). So unfortunately this may not be implemented currently in the provider. I suggest open a feature request to Azure to support this block in [SqlVM](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/stable/2022-02-01/sqlvm.json), and we could take another look into implement this in provider.

**Comment by jwshive** [comment]
@myc2h6o Thanks for replying. I did log this as a enhancement request. 
I'm not sure i follow what you're saying though. In azure, through the portal I can toggle Azure AD authentication support on the SQL Virtual Machine resource type that azurerm_mssql_virtual_machine tf resource creates. So my assumption is the functionality is there in azure, but is not represented in the TF provider. 

It's enabled in the portal by selecting the SQL Virtual Machine resource
Click Security Configuration
Azure AD Authentication

**Comment by myc2h6o** [comment]
@jwshive Yes from the detail you shared, I'm able to configure the AD Authentication as well from Azure Portal. It seems to be done by the SqlIaasExtension, and the details are stored in it. While the payload defined in the SqlIaasExtension is uncertain and may be changed, we may not be able to rely on it to retrieve the info. So probably this will still need the Azure SQL team to enhance the Swagger payload first.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
