### ISSUE TITLE
Add support for Azure Load Test CMK Encryption

### ISSUE THREAD

**Issue by jackwesleyroper** [hashicorp/terraform-provider-azurerm#22902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The azurerm_load_test resource does not currently support using CMK encryption type - can this be added?

### New or Affected Resource(s)/Data Source(s)

azurerm_load_test 

### Potential Terraform Configuration

```hcl
Add key_vault_key_id similar to the way encryption is handled in azure_windows_virtual_machine to add CMK encryption.

key_vault_key_id - (Optional) A versionless Key Vault Key ID for CMK encryption. Changing this forces a new resource to be created.
```

**Comment by tombuildsstuff** [comment]
Upstream issue tracking this: https://github.com/hashicorp/pandora/issues/2608
