### ISSUE TITLE
Documentation not specific enough for azurerm_cognitive_deployment

### ISSUE THREAD

**Issue by SebastianBalle** [hashicorp/terraform-provider-azurerm#22900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
Configuration taken from: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_deployment#example-usage

resource "azurerm_cognitive_deployment" "example" {
  name                 = "example-cd"
  cognitive_account_id = azurerm_cognitive_account.example.id
  model {
    format  = "OpenAI"
    name    = "text-curie-001"
    version = "1"
  }

  scale {
    type = "Standard"
    capacity = 50
  }
}
```

### Debug Output/Panic Output

```shell
No debug output
```

### Expected Behaviour

In the release of [3.64.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.64.0) the block property `capacity` in the `scale` block was introduced by https://github.com/hashicorp/terraform-provider-azurerm/pull/22223. The [docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cognitive_deployment#capacity) for the property is described as follow:

_(Optional) Tokens-per-Minute (TPM). If the SKU supports scale out/in then the capacity integer should be included. If scale out/in is not possible for the resource this may be omitted. Default value is 1. Changing this forces a new resource to be created._

The unit of Token-per-Minute (TPM) is missing a unit indicator. The unit is thousands of Token-per-Minute.

Additionally the https://github.com/hashicorp/terraform-provider-azurerm/pull/22223 indicates as breaking change in the statement _"This pr contains a breaking change to azurerm_cognitive_deployment and it should fix https://github.com/hashicorp/terraform-provider-azurerm/issues/22198."_
The property introduces a default value of 1 which might break existing values (it did for our infrastructure). It should be indicated in the [3.64.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.64.0)-changelog and any future releases that a breaking change exists in the PR. If no breaking changes is indicated in the changelog it is expected that I can upgrade the provider versions without changing the existing infrastructure.

**Comment by liuwuliuyun** [comment]
Hi @SebastianBalle , thanks for your advice. I will work on upgrading the document.
