### ISSUE TITLE
Invalid API Version for azurerm_sentinel_log_analytics_workspace_onboarding

### ISSUE THREAD

**Issue by LiamCloudGuard** [hashicorp/terraform-provider-azurerm#22905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.1.0

### AzureRM Provider Version

3.68.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_log_analytics_workspace_onboarding

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "sentinel" {
  name     = "rg-Sentinel-prd-${format("%.20s", terraform.workspace)}"
  location = var.location
  tags = {
    createdBy = "Terraform"
  }
}

resource "azurerm_log_analytics_workspace" "sentinel" {
  name                = "${terraform.workspace}-Sentinel-prd"
  location            = azurerm_resource_group.sentinel.location
  resource_group_name = azurerm_resource_group.sentinel.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_sentinel_log_analytics_workspace_onboarding" "sentinel" {
  depends_on = [ azurerm_log_analytics_workspace.sentinel ]
  workspace_name               = azurerm_log_analytics_workspace.sentinel.name
  customer_managed_key_enabled = false
}
```

### Debug Output/Panic Output

```shell
Onboarding State Name: "default"): sentinelonboardingstates.SentinelOnboardingStatesClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2022-11-01' is invalid. The supported versions are '2023-07-01,2023-07-01-preview,2023-03-01-preview,2022-12-01,2022-11-01-preview,2022-09-01,2022-06-01,2022-05-01,2022-03-01-preview,2022-01-01,2021-04-01,2021-01-01,2020-10-01,2020-09-01,2020-08-01,2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

### Expected Behaviour

Should not have returned API error and updated onboarding state for Sentinel on the workspace

### Actual Behaviour

Errors out due to invalid API

**Comment by ziyeqf** [comment]
Hi @LiamCloudGuard, thanks for reporting.

Have given it a try and it did not errored. Could you please give it another try and if the issue still exist, please provide the region you are using.

Thanks!

**Comment by ziyeqf** [comment]
> Hi @ziyeqf ,
> 
> I am still receiving this error, for both uksouth and westus. I havent had the chance to test more regions.
> 
> Which region/versions are you using in your terraform?
> 
> Thanks

My test was run on east us and it worked. Thanks for the update, I'm going to dig into it more.

**Comment by LiamCloudGuard** [comment]
Hey @ziyeqf ,

Yes you are right, feel like an idiot 😅. Thanks for the help!
