### ISSUE TITLE
servicebus topic - enable partitioning section - grammar

### ISSUE THREAD

**Issue by jaralonzo** [hashicorp/terraform-provider-azurerm#22950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

enable_partitioning is described as - "Boolean flag which controls whether to enable Changing this forces a new resource to be created. the topic to be partitioned across multiple message brokers. "

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/14593082/e5445442-4140-4b54-a93e-9fd598a78ff9)

Copy paste error?

### New or Affected Resource(s)/Data Source(s)

azurerm_servicebus_topic

### Potential Terraform Configuration

```hcl
change description to: "Boolean flag which controls whether to enable the topic to be partitioned across multiple message brokers.  Changing this forces a new resource to be created. "
```

### References

N/A

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. The typo appears to be fixed. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_topic.html
<img width="398" alt="enable_partitioning" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/132920294/0435c8f3-8edc-49d1-b225-635e07bcd491">
