### ISSUE TITLE
Support for filtering details of plan command output by add, change or destroy actions

### ISSUE THREAD

**Issue by Joseluismantilla** [hashicorp/terraform-provider-azurerm#22999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It would be super helpful some options in the plan command where we can filter only by changes, additions or deletions of resources, I mean, an option that allows filtering the terraform plan output with details according to our event or action we want to get more details.

Sometimes the amount of changes is big and the output only show changes according to your screen where the only option we have is to see the number next to the plan output with events like change, add or destroy but, it would be helpful to get a list of those 3 actions, not all in one or nothing.

E.g.:
**Plan:** 60 to add, 15 to change, 4 to destroy.

I'd like to know what we can do in these scenarios if we want to validate changes or resources to be deleted. I scroll up but I can't see enough details -- I think I can see the last 100 lines.

### New or Affected Resource(s)/Data Source(s)

terraform binary

**Comment by rcskosir** [comment]
Thanks for opening this issue. This forum is intended to be used for feature enhancements and bugs in the Azure Provider. Your support request would be something handled by [Terraform](https://github.com/hashicorp/terraform), so I encourage you to open a request in their repo for better visibility: https://github.com/hashicorp/terraform/issues. I'm going to mark this issue as closed, since it is not an enhancement on the Azure Provider.

**Comment by mybayern1974** [comment]
@Joseluismantilla FYI a [tooling ](https://driftctl.com/)and you can check whether it could (partially) serve your ask.
