### ISSUE TITLE
Support for `azurerm_communication_service_email_association`

### ISSUE THREAD

**Issue by timja** [hashicorp/terraform-provider-azurerm#22995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Linking of these two resources:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/communication_service
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/email_communication_service

In the portal from the communication services:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/21194782/2cac13a9-b01c-4c60-b77c-69b4eba7129b)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/21194782/03f68522-f078-4df3-be43-f77ab7dcde49)

Note it requires a verified domain already created in the `email_communication_service` which is covered in https://github.com/hashicorp/terraform-provider-azurerm/issues/22549

### New or Affected Resource(s)/Data Source(s)

azurerm_communication_service_email_association

### Potential Terraform Configuration

```hcl
resource "azurerm_communication_service_email_association"
   communication_service_id = "azurerm_communication_service.this.id"
   email_communication_service = "azurerm_email_communication_service.this.id"
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/22549
https://github.com/hashicorp/terraform-provider-azurerm/issues/21520#issuecomment-1590553733

**Comment by wgorczyca** [comment]
Just in case if someone needs a temporary workaround (with azapi provider)

```hcl
resource "azapi_update_resource" "this" {
  type      = "Microsoft.Communication/communicationServices@2022-07-01-preview"
  resource_id = azurerm_communication_service.this.id

  body = jsonencode({
    properties = {
      linkedDomains = [
        "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/example-rg/providers/Microsoft.Communication/emailServices/example-ecs/domains/customdomain.com"
      ]    
    }
  })
}
```
