### ISSUE TITLE
Support for `current_kubernetes_version` on `azurerm_kubernetes_cluster` resource

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform-provider-azurerm#22993]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I'd like to be able to get the current Kubernetes version from an `azurerm_kubernetes_cluster` resource. This information would be generally useful for reporting purposes and advanced automation use cases.

This change would also allow us to work around a current AKS bug with alias expansion for node pools (which we can't work around with the AKS suggested fix due to how the provider deals with setting the orchestrator version empty). We're currently having to use a shell script to get this value.

This data is already available in the provider and would only need to be exposed on the resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "default" {
  name               = "test"
  kubernetes_version = "1.27"
}

resource "azurerm_kubernetes_cluster_node_pool" "default" {
  name                  = "test"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.default.id
  orchestrator_version  = azurerm_kubernetes_cluster.default.current_kubernetes_version
}
```

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/22920
- https://github.com/hashicorp/terraform-provider-azurerm/pull/22986

**Comment by pszypowicz** [comment]
Hello,

Any updates, this is really missing at the moment in the provider.

**Comment by steph409** [comment]
Hi,
there is an attribute `kubernetes_version` instead of `current_kubernetes_version` on the azurerm_kubernetes_cluster resource. Why are you not using this one instead:

```hcl
resource "azurerm_kubernetes_cluster" "default" {
  name               = "test"
  kubernetes_version = "1.27"
}

resource "azurerm_kubernetes_cluster_node_pool" "default" {
  name                  = "test"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.default.id
  orchestrator_version  = azurerm_kubernetes_cluster.default.kubernetes_version
}
```

**Comment by stevehipwell** [comment]
@steph409 there are two versions associated with an AKS cluster. This is reflected in the data source but not the resource.
