### ISSUE TITLE
`azurerm_app_configuration_feature` creation times out if unauthorized to view soft-deleted `azurerm_app_configuration` resources

### ISSUE THREAD

**Issue by steven-hyland** [hashicorp/terraform-provider-azurerm#23001]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.0

### AzureRM Provider Version

3.67.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_feature

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.67.0"
    }
  }
}

provider "azurerm" {
  features {
    app_configuration {
      recover_soft_deleted = false
    }
  }
}

resource "azurerm_app_configuration" "app_configuration" {
  name                     = "unique-name-app-config-345825"
  resource_group_name      = "<any resource group>"
  location                 = "eastus2"
  sku                      = "standard"
  local_auth_enabled       = true
  public_network_access    = "Enabled"
  purge_protection_enabled = true
}

resource "azurerm_app_configuration_feature" "app_configuration_feature" {
  configuration_store_id = azurerm_app_configuration.app_configuration.id
  description            = "test"
  name                   = "test feature"
  key                    = ".appconfig.featureflag/test"
  enabled                = true
}
```

### Debug Output/Panic Output

Gist for both the debug log and the regular output are here: https://gist.github.com/steven-hyland/34c188a53ea2f1a65adf632c1fa94e93

### Expected Behaviour

The `azurerm_app_configuration_feature` resource should have been created in less than the time it took to timeout.

### Actual Behaviour

Resource creation timed out.

### Steps to Reproduce

`terraform apply -auto-approve`

### References

Please refer to this issue: https://github.com/hashicorp/terraform-provider-azurerm/issues/19605
And this PR: https://github.com/hashicorp/terraform-provider-azurerm/pull/19661

I believe this timeout issue is the same as or similar to the issue referenced and fixed in those two links. However, it seems the fix was not also applied to `azurerm_app_configuration_feature`. I believe the same or a similar fix would resolve this issue - reference the provider's `features.app_configuration.recover_soft_deleted` flag, and if it's `false`, don't check for the relevant soft-deleted resources, avoiding the Forbidden response.

I imagine the fix should be applied to `azurerm_app_configuration_key` to avoid a similar problem there as well.

**Comment by teowa** [comment]
Hi @steven-hyland , 

This should be permission issue, creating/reading App Configuration Feature resource need the `App Configuration Data Owner` role on either the App Configuration or a parent scope (such as the Resource Group/Subscription). Accoding to [doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/concept-enable-rbac#azure-built-in-roles-for-azure-app-configuration), we need to wait for 15 min for the permission to propagate, so the provider wait a long time to error out. We will fix the errorr message for this. 

To add the permission, we may need to add below config, e.g., 
```hcl
resource "azurerm_role_assignment" "appconf_dataowner" {
  scope                = azurerm_app_configuration.appconf.id
  role_definition_name = "App Configuration Data Owner"
  principal_id         = data.azurerm_client_config.current.object_id
}
```

Thanks.

**Comment by steven-hyland** [comment]
Hi @teowa - thanks for the context, but I am aware an additional permission is needed. Apologies if my troubleshooting revealed the wrong one.

I ran this test while having Owner on the relevant subscription, and still got the timeout error. I can create the relevant resources manually through the Azure Portal without issues. I believe `App Configuration Data Owner` is a subset of Owner, correct? If so, I don't think your suggested role assignment will resolve the problem.

I am requesting something similar to what was done for `azure_app_configuration` in the links that I provided. If someone has permissions to create resources but not check for soft-deleted resources on the parent type (which I am pretty sure is the case here, per the linked issues) then it should skip the soft-delete-check logic entirely if the `features.app_configuration.recover_soft_deleted` flag is `false`.

**Comment by teowa** [comment]
Hi @steven-hyland,  `App Configuration Data Owner` is NOT a subset of `Owner`, it can be proved by detail actions of these roles in Azure Portal or in this [doc](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#owner), the `Owner` role does not include any DataActions, e.g., `Microsoft.AppConfiguration/configurationStores/*/write`.
And this issue is not related with soft-delete function of `azurerm_app_configuration`.

Thanks.

**Comment by steven-hyland** [comment]
Hi @teowa, thank you for the clarification.

Does that explain why the same account (in the repro case, my account with `Owner`) is able to create the resources through the Azure Portal manually without issues, but not when running the example TF script above?

**Comment by teowa** [comment]
@steven-hyland , if you are using [Service Principal](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_certificate) to authenticate, then it should be different identity from the account used in Portal. That's why manually creation through Portal can succeed.

**Comment by steven-hyland** [comment]
@teowa I can double-check, but I am 99% sure I logged into the same account with `az login` so Terraform used those same credentials.

I will do another test soon when I get some time (hopefully today or tomorrow) to confirm and report back.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @teowa‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
