### ISSUE TITLE
azurerm_synapse_workspace crashes provider if storage_data_lake_gen2_filesystem_id is missing path

### ISSUE THREAD

**Issue by pacon-ar** [hashicorp/terraform-provider-azurerm#23004]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

9999

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_workspace

### Terraform Configuration Files

```hcl
See "References"
```

### Debug Output/Panic Output

```shell
panic, "slide bounds out of range"
```

### Expected Behaviour

Not crash

### Actual Behaviour

Crash

### Steps to Reproduce

1. supply a value to the `storage_data_lake_gen2_filesystem_id` attribute of the `azurerm_synapse_workspace` resource which is a URL but lacks a path element e.g. "https://foo.bar.example.net"
2. terraform apply

### References

`storage_data_lake_gen2_filesystem_id` is a URL including a single path element e.g. `https://foo.bar.example.net/pathelement1`

When parsing the attribute storage_data_lake_gen2_filesystem_id, the provider throws away any trailing path elements: https://github.com/hashicorp/terraform-provider-azurerm/blob/43f8ab0860fb588d95c34a1b109c09c41b9b3275/internal/services/synapse/synapse_workspace_resource.go#L798C13-L798C13

```golang
    Filesystem: utils.String(uri.Path[1:])
```

However does so in a way that assumes there is at least one path element. If there is no path element (e.g. user got mixed up and provided a DFS endpoint instead of a filesystem ID) then the provider will crash/panic.

Suggested fix is to add a check for the number of elements in the path, throw a specific error back to the user if the ID is malformed (e.g. lacking path element).

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Can you provide us with a more complete TF configuration as well as the panic output? It will help with reproducing this issue to confirm your findings and suggestions.
Thanks!

**Comment by pacon-ar** [comment]
Hi @rcskosir, the situation is that I wasn't the one who hit this bug and the affected terraform configuration no longer exists. I will put together an illustrative test case and a fix, but not sure "when". :-)

For now hopefully the report will show up in google searches for others hitting the same issue, so they know they are not going mad.

**Comment by pacon-ar** [comment]
Thankyou @wuxu92
