### ISSUE TITLE
azurerm_federated_identity_credential not loading "issuer" and failing to create

### ISSUE THREAD

**Issue by karloefd95** [hashicorp/terraform-provider-azurerm#23013]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.4.6

### AzureRM Provider Version

3.48.0

### Affected Resource(s)/Data Source(s)

azurerm_federated_identity_credential

### Terraform Configuration Files

```hcl
#main.tf
module "agic" {
  source = "../../modules/agic"
  ...
  cluster_oidc_url = module.cluster.aks_oidc_url
  depends_on = [module.cluster]
}

#cluster.tf
resource "azurerm_kubernetes_cluster" "aks" {
  ...
  workload_identity_enabled = true
  oidc_issuer_enabled = true
}

#cluster module output
output "aks_oidc_url" {
  value = azurerm_kubernetes_cluster.aks.oidc_issuer_url
}

#agic module
resource "azurerm_federated_identity_credential" "agic_credentials" {
  for_each = {
    for appgw in var.application_gateways : appgw.name => appgw
  }
  name                = "agic-${each.value.name}"
  resource_group_name = var.cluster_rg
  audience            = ["api://AzureADTokenExchange"]
  issuer              = var.cluster_oidc_url
  parent_id           = azurerm_user_assigned_identity.managed_indentity_agic.id
  subject             = "system:serviceaccount:agic:ingress-${each.value.name}-sa-ingress-azure"
}

#agic module variable defintion
variable "cluster_oidc_url" {
  type = string
  description = "The OIDC issuer URL that is associated with the cluster"
}
```

### Debug Output/Panic Output

```shell
# module.agic.azurerm_federated_identity_credential.agic_credentials["appgateway-devops-prd"] will be created
  + resource "azurerm_federated_identity_credential" "agic_credentials" {
      + audience            = [
          + "api://AzureADTokenExchange",
        ]
      + id                  = (known after apply)
      + name                = "agic-appgateway-devops-prd"
      + parent_id           = "/subscriptions/xxxxxxxxxx/resourceGroups/xxxx-xxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/agic-kubernetes-devops-prd"
      + resource_group_name = "xxxxx-xxx"
      + subject             = "system:serviceaccount:agic:ingress-appgateway-devops-prd-sa-ingress-azure"
    }


 Error: creating Federated Identity Credential (Subscription: "xxxxx"
│ Resource Group Name: "xxxx"
│ User Assigned Identity Name: "xxxx"
│ Federated Identity Credential Name: "agic-appgateway-devops-prd"): managedidentities.ManagedIdentitiesClient#FederatedIdentityCredentialsCreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The request format was unexpected. Federated Identity Credential must specify 'issuer', 'subject' and 'audience'."
```

### Expected Behaviour

AGIC module should receive not empty value from module.cluster.aks_oidc_url variable

### Actual Behaviour

azurerm_federated_identity_credential silently drops issuer argument and the API responds with an error.

Further explanation: 

- i have existing cluster and i want to enable workload identity on it by setting workload_identity_enabled and oidc_issuer_enabled to true in cluster module 
- in the same time i want to create federal identity credential in another module by using azurerm_federated_identity_credential resource
- agic module depends on cluster module so workload identity and oidc issuer should be created first and then passed to agic module via output value but when running terraform plan (or apply) "issuer" parameter gets droped
- if i first apply oidc_isssuer_enabled and enable it and after that in another apply i create federal identity credential everything works as expect with same code

### Steps to Reproduce

1. enable workload identity on existing cluster by setting
`workload_identity_enabled = true
  oidc_issuer_enabled = true`
2. create federal identity using azurerm_federated_identity_credential in another module using output variable from cluster module
3. run terraform plan

**Comment by magodo** [comment]
This duplicates to https://github.com/hashicorp/terraform-provider-azurerm/issues/21805, which has been fixed since v3.59.0.
