### ISSUE TITLE
storage_share quota issue greater than 5120 on standard SA

### ISSUE THREAD

**Issue by shanep2300** [hashicorp/terraform-provider-azurerm#23016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.10

### AzureRM Provider Version

Latest

### Affected Resource(s)/Data Source(s)

azurerm_storage_share

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage" {
  name = "${replace(replace(var.mandatory_prefix, "nrteu0", "ne0"),"-","")}${var.storage_account_name}"
  resource_group_name = "${var.resource_group_name}"
  location = "${var.resource_location}"
  
  account_kind = "${var.account_kind}"
  account_tier = "${var.storage_account_tier}"
  large_file_share_enabled = "${var.large_file_share_enabled}"
  account_replication_type = "${var.replication}"
  access_tier = "${var.storage_account_access_tier}"

  enable_https_traffic_only = true
  allow_nested_items_to_be_public = false

  network_rules {
    default_action = "${var.network_rules_default_action}"
    bypass = ["AzureServices"]
    virtual_network_subnet_ids = "${concat([data.azurerm_subnet.primary_subnet.id], length(var.additional_local_subnets) <= 0 ? [] : [for subnet_name in data.azurerm_subnet.additional_subnets: subnet_name.id])}"
    ip_rules = []
  }

  tags = "${var.mandatory_tags}"
}

resource "azurerm_storage_share" "file_shares" {
  count = "${length(var.fileshares)}"

  name = "${var.fileshares[count.index].name}"
  storage_account_name = "${azurerm_storage_account.storage.name}"
  access_tier = "${var.fileshares[count.index].file_share_access_tier}"
  quota = "${var.fileshares[count.index].quota}"
}
```

### Debug Output/Panic Output

```shell
shares.Client#SetProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidHeaderValue" Message="The value for one of the HTTP headers is not in the correct format.
```

### Actual Behaviour

Creating a `standard` storage account with `large_file_shared_enabled = true` allows the quota of the fileshare to be increased to the maximum of 100 TB in the azure portal. Doesn't work through terraform.

OR

The documentation needs to be updated as it states it only works for standard/premium accounts when it should also work for standard but with large file share enabled. I'm assuming the http error is do the azure api not being in synch?

### Steps to Reproduce

Create a `standard` storage account and add a fileshare with a quota > 5120 (This we know will fail)

Create a `standard` storage account WITH `large_file_shared_enabled = true` and add a fileshare with quota > 5120 (Error above)

**Comment by magodo** [comment]
Hi @shanep2300, I've tried the below config locally, which works fine for me:

```hcl
resource "azurerm_storage_account" "storage" {
  name                            = "magodotestaccntfs2"
  resource_group_name             = azurerm_resource_group.test.name
  location                        = azurerm_resource_group.test.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  large_file_share_enabled        = true
  enable_https_traffic_only       = true
  allow_nested_items_to_be_public = false
}

resource "azurerm_storage_share" "file_shares" {
  name                 = "test"
  storage_account_name = azurerm_storage_account.storage.name
  quota                = 6000
}
```

Would you mind to provide a minimal, valid (value filled) config here so that I can reproduce this issue on my side?

**Comment by shanep2300** [comment]
Did some further testing on my end and it worked. Looks like an error on my end...

Either way, the docs need to be changed to show that a greater quota works with `standard` sa  and `large_file_share_enabled` and not just premium.

Currently in docs:
`[quota](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_share#quota) - (Required) The maximum size of the share, in gigabytes. For Standard storage accounts, this must be 1GB (or higher) and at most 5120 GB (5 TB). For Premium FileStorage storage accounts, this must be greater than 100 GB and at most 102400 GB (100 TB).`

Ticket can be closed or change label for docs update if there is one.

**Comment by magodo** [comment]
@shanep2300 Just to be clear, for `premium`, the `large_file_share_enabled` is enabled by default by the service side. So do you want to mention that `quota` can be set to more than 5TB for standard SA when `large_file_share_enabled` is enabled?

**Comment by shanep2300** [comment]
That is correct. As right now it reads that a quota larger than 5 TB ONLY works for Premium storage accounts.
