### ISSUE TITLE
os_disk size modification giving error

### ISSUE THREAD

**Issue by tauqueer01** [hashicorp/terraform-provider-azurerm#23012]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

Terraform v1.5.0

### AzureRM Provider Version

 registry.terraform.io/hashicorp/azurerm v3.65.0

### Affected Resource(s)/Data Source(s)

 azurerm_virtual_machine , azurerm_managed_disk

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "os-diskfromsnap" {
  name                 = "os-disk"
  location             = "australiaeast"
  resource_group_name  = "rg-name"
  create_option        = "Copy"
  storage_account_type = "Standard_LRS"
   hyper_v_generation            = "V1"
  source_resource_id = azurerm_snapshot.os-disk-snap.id
   disk_size_gb         = 155  # change size here
}

resource "azurerm_virtual_machine" "vm-from-terraform" {
  location              = "australiaeast"
  name                  = "vm-from-terraform"
  network_interface_ids = [azurerm_network_interface.main.id]
  resource_group_name   = "rg_name"
  vm_size               = "Standard_D2s_v3"

  storage_os_disk {
    name              = "os-disk"
    os_type           = "Windows"
    caching           = "ReadWrite"
    create_option     = "Attach"  
    managed_disk_type = "Standard_LRS"
    managed_disk_id   = azurerm_managed_disk.os-diskfromsnap.id
  }
}
```

### Debug Output/Panic Output

```shell
Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResizeDiskError" Message="Managed disk resize via Virtual Machine 'vm-from-terraform' is not allowed. Please resize disk resource at /subscriptions/<subscription>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/os-disk." Target="disk.diskSizeGB"
│
│   with azurerm_virtual_machine.vm-from-terraform,
│   on windows.tf line 94, in resource "azurerm_virtual_machine" "vm-from-terraform":
│   94: resource "azurerm_virtual_machine" "vm-from-terraform" {
```

### Expected Behaviour

terraform script should not throw error while execution and disk size should be modified.

### Actual Behaviour

Terraform throws below error while execution and  actually disk is getting modified to desired size and tfstate file also gets updated with new size.

 Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResizeDiskError" Message="Managed disk resize via Virtual Machine 'vm-from-terraform' is not allowed. Please resize disk resource at /subscriptions/<subscription-is>/resourceGroups/<rg_name>/providers/Microsoft.Compute/disks/os-disk." Target="disk.diskSizeGB"
│
│   with azurerm_virtual_machine.vm-from-terraform,
│   on windows.tf line 94, in resource "azurerm_virtual_machine" "vm-from-terraform":
│   94: resource "azurerm_virtual_machine" "vm-from-terraform" {

### Steps to Reproduce

terraform init
terraform plan
terraform apply

**Comment by tauqueer01** [comment]
What is correct way to resize os_disk.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
