### ISSUE TITLE
AzureRM provider keeps requresting Microsoft.MixedReality

### ISSUE THREAD

**Issue by retpolanne** [hashicorp/terraform-provider-azurerm#23027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.70.0

### Affected Resource(s)/Data Source(s)

 provider.terraform-provider-azurerm_v3.70.0_x5

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "terratest_certmanager" {
  name     = "terratest-certmanager"
  location = "East US"
}
```

### Debug Output/Panic Output

```shell
st\"],\"apiVersions\":[\"2023-02-01-preview\",\"2022-10-01-preview\",\"2022-01-01-preview\"],\"capabilities\":\"CrossResourceGroupResourceMove, CrossSubscriptionResourceMove, SupportsTags, SupportsLocation\"}],\"registrationState\":\"NotRegistered\",\"registrationPolicy\":\"RegistrationRequired\"}]}","@timestamp":"2023-08-21T09:45:04.899545-03:00"}
2023-08-21T09:45:05.123-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: Determining which Resource Providers require Registration: timestamp=2023-08-21T09:45:05.123-0300
2023-08-21T09:45:05.123-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: Registering 1 Resource Providers: timestamp=2023-08-21T09:45:05.123-0300
2023-08-21T09:45:05.123-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: Registering Resource Provider "Microsoft.MixedReality" with namespace: timestamp=2023-08-21T09:45:05.123-0300
2023-08-21T09:45:05.123-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: Registering Subscription Provider (Subscription: "blaaaaa"
Provider Name: "Microsoft.MixedReality")..: timestamp=2023-08-21T09:45:05.123-0300
2023-08-21T09:45:05.123-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: AzureRM Request: 
POST /subscriptions/blaaaaa/providers/Microsoft.MixedReality/register?api-version=2022-09-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 providers/2022-09-01) HashiCorp Terraform/1.5.5 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.70.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 2
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: 21e952b0-df70-2268-868e-5293bb918903
Accept-Encoding: gzip

{}: timestamp=2023-08-21T09:45:05.123-0300
2023-08-21T09:45:05.123-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: POST https://management.azure.com/subscriptions/blaaaa/providers/Microsoft.MixedReality/register?api-version=2022-09-01: timestamp=2023-08-21T09:45:05.123-0300
2023-08-21T09:45:06.975-0300 [DEBUG] provider.terraform-provider-azurerm_v3.70.0_x5: AzureRM Response for https://management.azure.com/subscriptions/blaaa/providers/Microsoft.MixedReality/register?api-version=2022-09-01: 
HTTP/2.0 200 OK
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 21 Aug 2023 12:45:06 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 21e952b0-df70-2268-868e-5293bb918903
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1198
X-Ms-Request-Id: 9d840f55-85ff-40c8-9699-1a26e53d1b51
X-Ms-Routing-Request-Id: BRAZILSOUTH:20230821T124507Z:9d840f55-85ff-40c8-9699-1a26e53d1b51



Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Error ensuring Resource Providers are registered.
│ 
│ Terraform automatically attempts to register the Resource Providers it supports to
│ ensure it's able to provision resources.
│ 
│ If you don't have permission to register Resource Providers you may wish to use the
│ "skip_provider_registration" flag in the Provider block to disable this functionality.
│ 
│ Please note that if you opt out of Resource Provider Registration and Terraform tries
│ to provision a resource from a Resource Provider which is unregistered, then the errors
│ may appear misleading - for example:
│ 
│ > API version 2019-XX-XX was not found for Microsoft.Foo
│ 
│ Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
│ but this could also indicate that this Azure Region doesn't support this API version.
│ 
│ More information on the "skip_provider_registration" flag can be found here:
│ https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration
│ 
│ Original Error: Cannot register providers: Microsoft.MixedReality. Errors were: waiting for Subscription Provider (Subscription: "6376dd69-3ec8-470c-ad44-5470450e2444"
│ Provider Name: "Microsoft.MixedReality") to be registered: context canceled
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 11, in provider "azurerm":
│   11: provider "azurerm" {
```

### Expected Behaviour

Shouldn't loop this call to MixedReality. 

### Actual Behaviour

Keeps looping this call to MixedReality. Terraform apply hangs due to that. 

### Steps to Reproduce

Add the content above to providers.tf and main.tf. Run `terraform init` and `terraform plan`

### Important Factoids

I believe that something is unregistered in my account, but the error doesn't seem human readable.

**Comment by retpolanne** [comment]
I reported the issue too fast, but it can be fixed as easily as this:

```
provider "azurerm" {
  features {}
  skip_provider_registration = true
}
```

**Comment by schnabel45** [comment]
Is this actually a fix though? This looks more like a work-around. I'm seeing the same in version 3.68.0 after upgrading a project from 3.32.0.

**Comment by dghubble** [comment]
Yeah, this looks like a regression and should be re-opened.

**Comment by schnabel45** [comment]
Small context which I get the feeling that @retpolanne understood but I didn't until now. This is actually the Azure Subscription Resource Provider being registered and azurerm timing out. Specifically it looks like the Microsoft.MixedReality and Microsoft.ServiceFabricMesh providers are taking ages to register for newly created subscriptions. So this definitely isn't an azurerm bug. Definitely use the skip_provider_registration = true as a work around and check in the portal or via az cli to see when the providers have completely registered before removing.

**Comment by dghubble** [comment]
Thanks @schnabel45 It does seem to be Azure itself with `Microsoft.MixedReality` resource provider not registering, we've seen it since yesterday. Not a bug in this provider. Following up with Azure directly.

**Comment by PaulHallam101** [comment]
@dghubble have you had a response? We are still getting this error.

**Comment by dghubble** [comment]
I believe they've solved it now

**Comment by retpolanne** [comment]
Hey! Apologies for closing it too fast and I've just checked my email ;) 

I actually thought I just didn't read the docs properly and the fix was obvious for me later, so I thought it wasn't an actual issue. Glad it got solved!
