### ISSUE TITLE
Support for azurerm_storage_management_policy (cold storage policy)

### ISSUE THREAD

**Issue by w-kramer** [hashicorp/terraform-provider-azurerm#23020]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello there,

Microsoft has released "cold" storage tier (aditional to cool), as described in [Generally available: Azure Blob Storage Cold Tier](https://azure.microsoft.com/en-us/updates/generally-available-azure-cold-storage/.). Therefore a new "tierToCold" [rule action](https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview#rule-actions) was introduced.
In documentation version 3.70.0 of [azurerm_storage_management_policy](https://registry.terraform.io/providers/hashicorp/azurerm/3.70.0/docs/resources/storage_management_policy) I cannot find a representation of this.

Please add this to the provider.

Thank you very much.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_management_policy

### Potential Terraform Configuration

* tier_to_**cold**_after_days_since_modification_greater_than
* tier_to_**cold**_after_days_since_last_access_time_greater_than
* tier_to_**cold**_after_days_since_creation_greater_than

### References

* https://azure.microsoft.com/en-us/updates/generally-available-azure-cold-storage/
* https://learn.microsoft.com/en-us/azure/storage/blobs/lifecycle-management-overview#rule-actions
* https://registry.terraform.io/providers/hashicorp/azurerm/3.70.0/docs/resources/storage_management_policy

**Comment by magodo** [comment]
@w-kramer Are you referring to the following properties:

- tier_to_cool_after_days_since_modification_greater_than
- tier_to_cool_after_days_since_last_access_time_greater_than
- tier_to_cool_after_days_since_creation_greater_than
