### ISSUE TITLE
Retention policy days are ignored inside "enabled_log" for azurerm_monitor_diagnostic_setting" module

### ISSUE THREAD

**Issue by adrigomez85** [hashicorp/terraform-provider-azurerm#23025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

3.70.0

### AzureRM Provider Version

3.70.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "agw" {
  name               = "${var.deployment_def.code}-logaw-appgw-diag"
  target_resource_id = azurerm_application_gateway.local.id
  storage_account_id = data.azurerm_storage_account.agw.id
  enabled_log {

    category_group = "allLogs"

    retention_policy {
      enabled = true
      days    = 60
    }
  }

  metric {

    category = "Allmetrics"

    retention_policy {
      enabled = true
      days    = 50
    }
  }

}
```

### Debug Output/Panic Output

```shell
No changes. Your infrastructure matches the configuration.
```

### Expected Behaviour

When "days" value is being updated it has to be detected by Terraform and updated in Azure.

### Actual Behaviour

Change is not being detected by Terraform.

**Comment by HappyTobi** [comment]
Think this feature is deprecated:
https://learn.microsoft.com/en-us/azure/azure-monitor/essentials/migrate-to-azure-storage-lifecycle-policy
