### ISSUE TITLE
Support for Azure API Connection with V2 version

### ISSUE THREAD

**Issue by ParthibanSG** [hashicorp/terraform-provider-azurerm#23064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Current Terraform provider doesn't support creating api connections with V2 version. V1 version doesn't expose connectionruntime url whereas V2 does expose the URL which is required when coupling with logic app for automated deployments

Provider should provide the capability to end users to select the version (v1 or v2) to create resource accordingly

### New or Affected Resource(s)/Data Source(s)

azurerm_3.70.0

**Comment by aristosvo** [comment]
Hi @ParthibanSG! Do you know anything about documentation or the REST API docs to back this up?

I couldn't find anything to work with yet.

**Comment by sumeet-deloitte** [comment]
Hi everyone! Is there any update on this topic?
Currently I'm working on creation of logic apps through terraform but i can't create managed apis for logic apps workflow standard because it uses "**connectionRuntimeURL**" available in **V2** version of api connection.

**Comment by ParthibanSG** [comment]
@aristosvo I have also seen similar request in the past [https://github.com/hashicorp/terraform-provider-azurerm/issues/16818](url) but it was never addressed it seems.

Please check if below helps with the request

[https://medium.com/microsoftazure/provisioning-azure-logic-apps-api-connections-with-terraform-980179980b5b](url)

**Comment by ParthibanSG** [comment]
@aristosvo 

Thanks for the details and I will raise this issue with our Azure representative. Meanwhile, I found that we can create API connections via azapi. I did provide declaration like below

`
resource "azapi_resource" "connection" {
  type      = "Microsoft.Web/connections@2016-06-01"
  name      = "test-conn"
  parent_id = "/subscriptions/test/..."
  location  = "westeurope"

  body = jsonencode({
    properties = {
      api = {
        id = "/subscriptions/.../locations/westeurope/managedApis/azuresentinel"
      }
      displayName = "Test-Conn"
      parameterValueSet = {
        name   = "managedIdentityAuth"
        values = {}
      }
    }
  })
  schema_validation_enabled = false
}
`
I could see connection is created and is in Connected state however, connection is still showing "Authorize" option rather being managed by "ManagedIdentity". Do we have this support in current module (azurerm_api_connection) or should I also highlight this our Azure representative ?

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
