### ISSUE TITLE
azurerm_cosmosdb_postgresql_cluster - polling after Create: unmarshalling response body

### ISSUE THREAD

**Issue by selvaganesh-gopal** [hashicorp/terraform-provider-azurerm#23063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

polling after Create: unmarshalling response body: parsing time "2023-07-13 06:10:30 +0000" as "2006-01-02T15:04:05Z07:00": cannot parse " 06:10:30 +0000" as "T"

### Terraform Version

1.5.5

### AzureRM Provider Version

3.62

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_postgresql_cluster.cosmosdbPostgresqlCluster

### Terraform Configuration Files

```hcl
new CosmosdbPostgresqlCluster(this, 'cpsql', {
        name: "psql",
        location: "East US",
        resourceGroupName: "Vennila",
        administratorLoginPassword: "****",
        coordinatorStorageQuotaInMb: "873934",
        coordinatorVcoreCount: 4,
        nodeCount:0,
    });
```

### Debug Output/Panic Output

```shell
polling after Create: unmarshalling response body: parsing time "2023-07-13 06:10:30 +0000" as "2006-01-02T15:04:05Z07:00": cannot parse " 06:10:30 +0000" as "T"

 on cdk.tf.json line 801, in resource.azurerm_cosmosdb_postgresql_cluster.cosmosdbPostgresqlCluster (cosmosdbPostgresqlCluster):
 801:       }
```

### Expected Behaviour

polling after Create: unmarshalling response body: parsing time "2023-07-13 06:10:30 +0000" as "2006-01-02T15:04:05Z07:00": cannot parse " 06:10:30 +0000" as "T"

### Actual Behaviour

It needs to create the cosmos postgresSQL cluster in Azure

### Steps to Reproduce

terraform init
terraform apply

### Important Factoids

-

### References

-

**Comment by tombuildsstuff** [comment]
hey @selvaganesh-gopal 

Thanks for opening this issue.

Digging into this issue, the API result is returning a Date/Time value which differs from other APIs, as such I've opened https://github.com/hashicorp/go-azure-sdk/pull/632 to parse this value as a string rather a RFC3339 Date/Time value - which'll fix this issue once it's been merged and vendored into this repository.

Thanks!

**Comment by selvaganesh-gopal** [comment]
Thank you tombuildsstuff  for your support, now we are able to see the Cosmos PostgresSQL cluster in Azure using cdktf without any issue.

**Comment by dmahana** [comment]
hey @tombuildsstuff , v3.71.0 is already released but doesn't contain this fix. would this be added in the next release ?
