### ISSUE TITLE
azurerm_monitor_action_group

### ISSUE THREAD

**Issue by camilosantana** [hashicorp/terraform-provider-azurerm#23083]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.2

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_action_group

### Terraform Configuration Files

```hcl
terraform {
  required_providers { azurerm = { source = "hashicorp/azurerm", version = "3.71.0" } }
}
provider "azurerm" {
  features {}
}
locals {
  resource_group_name = "rg"
  monitor_action_groups = {
    monitor_action_group_team_name_01 = {
      sms_short_name = "display_name"
      app_push_receiver = {
        "john doe" = "bar@foo.baz"
      }
      sms_receiver = {
        "foo" = "5558675309"
        "bar" = "8675309555"
      }
    }
  }
}
resource "azurerm_monitor_action_group" "a" {
  for_each            = local.monitor_action_groups
  name                = each.key
  resource_group_name = local.resource_group_name
  short_name          = each.value.sms_short_name
  dynamic "azure_app_push_receiver" {
    for_each = each.value.app_push_receiver
    content {
      name          = app_push_receiver.key
      email_address = app_push_receiver.value
    }
  }
  # dynamic "sms_receiver" {
  #   for_each = each.value.sms_receiver
  #   content {
  #     country_code = "1"
  #     name         = sms_receiver.key
  #     phone_number = sms_receiver.value
  #   }
  # }
}
```

### Debug Output/Panic Output

```shell
Error:

`│ A managed resource "app_push_receiver" "key" has not been declared in the root module.`
```

### Expected Behaviour

It's expected that the dynamic block for `azure_app_push_receiver` can access the scoped variable map.

`azure_app_push_receiver.key` is expected to be `string` `"john doe"`

### Actual Behaviour

above error

### Steps to Reproduce

uncomment/comment the two dynamic blocks alternatively. `dynamic "sms_receiver"` parses as expected.  `dynamic "azure_app_push_receiver"` interprets the local as a terraform resource.

this happens with variables as well. i used locals here for more concise example.

### Important Factoids

nothing atypical. running in US East

**Comment by teowa** [comment]
Hi @camilosantana , from [doc](https://developer.hashicorp.com/terraform/language/expressions/dynamic-blocks#multi-level-nested-block-structures), `app_push_receiver.key` should be `azure_app_push_receiver.key` to refer to the current element of the inner block, below config can work:
```hcl
resource "azurerm_monitor_action_group" "a" {
  for_each            = local.monitor_action_groups
  name                = each.key
  resource_group_name = local.resource_group_name
  short_name          = each.value.sms_short_name
  dynamic "azure_app_push_receiver" {
    for_each = each.value.app_push_receiver
    content {
      name          = azure_app_push_receiver.key
      email_address = azure_app_push_receiver.value
    }
  }
  # dynamic "sms_receiver" {
  #   for_each = each.value.sms_receiver
  #   content {
  #     country_code = "1"
  #     name         = sms_receiver.key
  #     phone_number = sms_receiver.value
  #   }
  # }
}
```

**Comment by camilosantana** [comment]
confirmed. error was on my end.

from the documentation example @teowa linked to:

```hcl
  dynamic "origin_group" {
    for_each = var.load_balancer_origin_groups
    content {
      name = origin_group.key

      dynamic "origin" {
        for_each = origin_group.value.origins
        content {
          hostname = origin.value.hostname
        }
      }
    }
  }
```

> When using nested dynamic blocks it's particularly important to pay attention to the iterator symbol for each block. In the above example, origin_group.value refers to the current element of the outer block, while origin.value refers to the current element of the inner block.

I was referencing the element from `locals` instead of the dynamic resource the element was loaded into.

Thank you.
