### ISSUE TITLE
Microsoft.ApiManagement Error: unexpected segment "policies/policy" in 3.71.0 version

### ISSUE THREAD

**Issue by abbasbaman** [hashicorp/terraform-provider-azurerm#23095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.2

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api_policy

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_policy" "api_policies" {
  count               = length(var.apis_arguments)
  api_name            = var.apis_arguments[count.index].name
  resource_group_name = data.azurerm_api_management.apim.resource_group_name
  api_management_name = data.azurerm_api_management.apim.name

  xml_content = file(abspath(var.apis_arguments[count.index].policy_content))

 depends_on = [
    azurerm_api_management_api.apis,
    azurerm_api_management_named_value.named_values
  ]
}
```

### Debug Output/Panic Output

```shell
Initializing provider plugins...

Finding hashicorp/azurerm versions matching ">= 2.66.0"...
Installing hashicorp/azurerm v3.71.0...
Installed hashicorp/azurerm v3.71.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

╷
│ Error: parsing "/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.ApiManagement/service/xxxxxxxxx/apis/xxxxxx/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.ApiManagement/service/xxxxxxxx/apis/xxxxx/policies/policy")
│
│ with module.api.azurerm_api_management_api_policy.api_policies[0],
│ on .terraform/modules/api/api-template/api-resources.tf line 30, in resource "azurerm_api_management_api_policy" "api_policies":
│ 30: resource "azurerm_api_management_api_policy" "api_policies" {
│
╵
```

### Expected Behaviour

module.api-global-policy[0].azurerm_api_management_policy.this[0]: Refreshing state... [id=/subscriptions/<hidden>/resourceGroups/rg-ag-qa01-api-s-01/providers/Microsoft.ApiManagement/service/apim-ag-qa01-api-s-01/policies/policy]
No changes. Your infrastructure matches the configuration.
Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.

### Actual Behaviour

╷
│ Error: parsing "/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.ApiManagement/service/xxxxxxxxx/apis/xxxxxx/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/xxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.ApiManagement/service/xxxxxxxx/apis/xxxxx/policies/policy")
│
│ with module.api.azurerm_api_management_api_policy.api_policies[0],
│ on .terraform/modules/api/api-template/api-resources.tf line 30, in resource "azurerm_api_management_api_policy" "api_policies":
│ 30: resource "azurerm_api_management_api_policy" "api_policies" {
│
╵

### Steps to Reproduce

terraform init - which will use latest version 3.71.0

**Comment by o-otte** [comment]
Hello, I have encountered a similar issue but in another APIM Policy Resource:

```
│ Error: parsing "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xx/apis/fhapi-v1/operations/xxx/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/apis/xxx/operations/xxx/policies/policy")
│ 
│   with azurerm_api_management_api_operation_policy.xxxx,
│   on xxx.tf line 117, in resource "azurerm_api_management_api_operation_policy" "xxxx":
│  117: resource "azurerm_api_management_api_operation_policy" "xxxx" {
```

using:
* Terraform 1.5.6
* AzureRM Provider 3.71.0 trying to upgrade from 3.69.0

Affects: `azurerm_api_management_api_operation_policy`

**Comment by abbasbaman** [comment]
Hi @sinbai  I believe it's functioning correctly for certain APIs, but there are instances where it's failing. Could you please attempt it with different APIs?

**Comment by sinbai** [comment]
For `azurerm_api_management_api_operation_policy` , the result is the same as `azurerm_api_management_api_policy `. See below for details.  I assume where the ID "/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxx/providers/Microsoft.ApiManagement/service/xxxxxxxxx/apis/xxxxxx/policies/policy" is coming from is the crux of the issue. Because in v3.71.0, the ID no longer contains "policies/policy", and in v3.69.0 the ID ends with "policies/xml" in state file. So could anyone provide the complete reproduce steps to help reproduce/troubleshoot?

Step1: Create azurerm_api_management_api_operation_policy with the following tf config.（the version of Terraform Provider is 3.69.0）.

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
	  version = "3.69.0"
    }
  }
}

provider "azurerm" {
  features {} 
}
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-0830"
  location = "eastus"
}

resource "azurerm_api_management" "test" {
  name                = "acctestAM-0830"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  publisher_name      = "pub1"
  publisher_email     = "pub1@email.com"
  sku_name            = "Consumption_0"
}

resource "azurerm_api_management_api" "test" {
  name                = "acctestapi-0830"
  resource_group_name = azurerm_resource_group.test.name
  api_management_name = azurerm_api_management.test.name
  display_name        = "Butter Parser"
  path                = "butter-parser"
  protocols           = ["https", "http"]
  revision            = "3"
  description         = "What is my purpose? You parse butter."
  service_url         = "https://example.com/foo/bar"

  subscription_key_parameter_names {
    header = "X-Butter-Robot-API-Key"
    query  = "location"
  }
}

resource "azurerm_api_management_api_operation" "test" {
  operation_id        = "acctest-operation"
  api_name            = azurerm_api_management_api.test.name
  api_management_name = azurerm_api_management.test.name
  resource_group_name = azurerm_resource_group.test.name
  display_name        = "DELETE Resource"
  method              = "DELETE"
  url_template        = "/resource"
}

resource "azurerm_api_management_api_operation_policy" "test" {
  api_name            = azurerm_api_management_api.test.name
  api_management_name = azurerm_api_management.test.name
  resource_group_name = azurerm_resource_group.test.name
  operation_id        = azurerm_api_management_api_operation.test.operation_id
  xml_link            = "https://gist.githubusercontent.com/riordanp/ca22f8113afae0eb38cc12d718fd048d/raw/d6ac89a2f35a6881a7729f8cb4883179dc88eea1/example.xml"
}
```

Step2: Update the version of Terraform Provider to 3.71.0.

Step3: Run "terraform init -upgrade" => No error

Step4: Run "terraform plan" => No error.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/c9f18e3e-4a32-4afc-a1d4-8a3a63e666c5)

**Comment by furkankaracan** [comment]
This bug still appears with version 3.89.0

**Comment by ron-foreman** [comment]
Bug also present with version 3.92.0
