### ISSUE TITLE
Microsoft.ApiManagement Error: unexpected segment "policies/policy"

### ISSUE THREAD

**Issue by michelefa1988** [hashicorp/terraform-provider-azurerm#23112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.0

### AzureRM Provider Version

3.70.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_product

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_product" "api_management_product" {
  product_id            = var.product_id
  api_management_name   = var.api_management_name
  resource_group_name   = var.resource_group
  display_name          = var.display_name
  subscription_required = true
  approval_required     = false
  published             = true
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxxx/resourceGroups/rg/providers/Microsoft.ApiManagement/service/apim/products/xxx/policies/policy": unexpected segment "policies/policy" present at the end of the URI (input "/subscriptions/xxxx-xxxx-xxxx-xxxx-xxxx/resourceGroups/rg/providers/Microsoft.ApiManagement/service/apim/products/test-user/policies/policy")
│ 
│   with module.env-definition.module.test_user_wyzer_api_management_product_policy.azurerm_api_management_product_policy.api_management_product_policy,
│   on ../../../terraform-providers/azure/modules/api-management/azurerm_api_management_product_policy/azurerm_api_management_product_policy.tf line 19, in resource "azurerm_api_management_product_policy" "api_management_product_policy":
│   19: resource "azurerm_api_management_product_policy" "api_management_product_policy" {
│ 

```

### Expected Behaviour

Plan expected to finish cleanly

### Actual Behaviour

Planning failed. Terraform encountered an error while generating this plan.

**Comment by michelefa1988** [comment]
Relates to https://github.com/hashicorp/terraform-provider-azurerm/issues/23015

**Comment by sinbai** [comment]
Hi @michelefa1988, thanks for opening this issue. Per the provided terraform configuration, the affected terraform resource is `azurerm_api_management_product`. However, in `Debug Output/Panic Output`, the id  "/subscriptions/xxxx-xxxx-xxx-xxxxx-xxxx/resourceGroups/rg/providers/Microsoft.ApiManagement/service/apim-product-dev-gewc/apis/Health/policies/policy" appears to be the ID of terraform resource `azurerm_api_management_api_policy`. Could you please explain where this id is coming from? Is it possible to provide the complete repro steps to help reproduce/troubleshoot?

**Comment by michelefa1988** [comment]
@sinbai  can you please check again. I have various aim related products which are not working

**Comment by sinbai** [comment]
Hi @michelefa1988 I have submitted PR #23128 to try to resolve this error. Before the PR is released, could you please manually remove the suffix `/policies/policy` of the id (including the resources : azurerm_api_management_api_policy, azurerm_api_management_api_operation_policy, azurerm_api_management_product_policy ) in state file to see if it is resolved? (e.g. replace `"/subscriptions/xxxx-xxxx-xxx-xxxxx-xxxx/resourceGroups/rg/providers/Microsoft.ApiManagement/service/apim-product-dev-gewc/apis/Health/policies/policy"` with `/subscriptions/xxxx-xxxx-xxx-xxxxx-xxxx/resourceGroups/rg/providers/Microsoft.ApiManagement/service/apim-product-dev-gewc/apis/Health`)

**Comment by michelefa1988** [comment]
Yup, this seemed to have solved it and terraform plan works well.  :)
