### ISSUE TITLE
Enabled / Disabled State for custom_rules in azurerm_web_application_firewall_policy

### ISSUE THREAD

**Issue by UppyAU** [hashicorp/terraform-provider-azurerm#23123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The azurerm_web_application_firewall_policy resource does not support and is unaware of the State property on the CustomRule present from API Version (2022-09-01). 

- This is an issue as you can't add this property to an ignore_changes block on this resource
- It does not capture the current state of a custom rule 
- Could potentially result in it being re-enabled whilst not indicating so in the terraform plan

See:
https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.network.models.psapplicationgatewayfirewallcustomrule?view=az-ps-latest

https://learn.microsoft.com/en-us/rest/api/application-gateway/web-application-firewall-policies/list?tabs=HTTP
```
        "customRules": [
          {
            "name": "Rule1",
            "priority": 1,
            "state": "Enabled",
            "ruleType": "MatchRule",
            "matchConditions": [
              {
                "matchVariables": [
                  {
                    "variableName": "RemoteAddr",
                    "selector": null
                  }
                ],
                "operator": "IPMatch",
                "negationConditon": false,
                "matchValues": [
                  "192.168.1.0/24",
                  "10.0.0.0/24"
                ],
                "transforms": []
              }
            ],
            "action": "Block"
          },

```

Is it just a matter of adding the state as a item here? or are we limited by API version the provider is using?
terraform-provider-azurerm/internal/services/network/web_application_firewall_policy_resource.go

```
func expandWebApplicationFirewallPolicyWebApplicationFirewallCustomRule(input []interface{}) *[]webapplicationfirewallpolicies.WebApplicationFirewallCustomRule {
	results := make([]webapplicationfirewallpolicies.WebApplicationFirewallCustomRule, 0)
	for _, item := range input {
		v := item.(map[string]interface{})
		name := v["name"].(string)
		priority := v["priority"].(int)
		ruleType := v["rule_type"].(string)
		matchConditions := v["match_conditions"].([]interface{})
		action := v["action"].(string)

		result := webapplicationfirewallpolicies.WebApplicationFirewallCustomRule{
			Action:          webapplicationfirewallpolicies.WebApplicationFirewallAction(action),
			MatchConditions: expandWebApplicationFirewallPolicyMatchCondition(matchConditions),
			Name:            pointer.To(name),
			Priority:        int64(priority),
			RuleType:        webapplicationfirewallpolicies.WebApplicationFirewallRuleType(ruleType),
		}

		results = append(results, result)
	}
	return &results
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```hcl
custom_rules {
    name      = "Rule1"
    enabled = true | false
    priority  = 1
    rule_type = "MatchRule"

    match_conditions {
      match_variables {
        variable_name = "RemoteAddr"
      }

      operator           = "IPMatch"
      negation_condition = false
      match_values       = ["192.168.1.0/24", "10.0.0.0/24"]
    }

    action = "Block"
  }
```

**Comment by wuxu92** [comment]
hi @UppyAU thanks for raising this issue. while Azure Keyvault doesn't allow to read a disabled secret and there is a existing isssue  just like this: https://github.com/hashicorp/terraform-provider-azurerm/issues/15578, so azurerm cannot support this property for now.

and if you want to read the value of `enabled`, could you please have try with `https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault_secrets#enabled` to see if it meets your requirements.

**Comment by wuxu92** [comment]
hi @UppyAU thanks a lot for reporting this. But I think this should be a by-design as terraform provider guideline says here https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/topics/schema-design-considerations.md#features-that-are-toggled-by-the-property-enabled 

>that when the block is present the feature is enabled, and when it is absent it is disabled

**Comment by UppyAU** [comment]
Thanks @wuxu92 I think this might be one of those cases where it's an exception to this design choice. Primarily due to the fact that it introduces unexpected consequences with rules being re enabled but not explicitly called out in the terraform plan.

My use case is the existence of a couple of WAF Custom Rules that allows us to toggle the level of access available to the app services sitting behind the application gateway where we can block all traffic, block external only traffic but allow trusted IPs or allow all traffic by having the other two rules disabled.

This is then managed outside of terraform with AZ CLI calls enabling and disabling the rules as desired in an ADO pipeline but the rules configuration are stored in Infrastructure as Code.

The behaviour I'm experiencing is if I add new rule or make an adjustment it will recreate all the rules and reenable them. Which has an undesired outcome.

**Comment by wuxu92** [comment]
@UppyAU that sounds reasonable. could you please add a acceptance test with the `enabled` property in your PR with both `true` and `false` values.

**Comment by UppyAU** [comment]
I have added the field to the TestAccWebApplicationFirewallPolicy_complete test. 

Per :
- If the property is Optional then it can be added to the complete test.

Is that okay?

**Comment by UppyAU** [comment]
`make acctests SERVICE='network' TESTARGS='-run=TestAccWebApplicationFirewallPolicy_complete' TESTTIMEOUT='60m'
==> Checking that code complies with gofmt requirements...
FIND: Parameter format not correct
FIND: Parameter format not correct
==> Checking that Custom Timeouts are used...
FIND: Parameter format not correct
==> Checking that acceptance test packages are used...
TF_ACC=1 go test -v ./internal/services/network -run=TestAccWebApplicationFirewallPolicy_complete -timeout 60m -ldflags="-X=github.com/hashicorp/terraform-provider-azurerm/version.ProviderVersion=acc"
=== RUN   TestAccWebApplicationFirewallPolicy_complete
=== PAUSE TestAccWebApplicationFirewallPolicy_complete
=== CONT  TestAccWebApplicationFirewallPolicy_complete
--- PASS: TestAccWebApplicationFirewallPolicy_complete (180.61s)
PASS
ok      github.com/hashicorp/terraform-provider-azurerm/internal/services/network       180.683s`
