### ISSUE TITLE
azurerm_storage_account - Forced to add restore_policy although I only want to add cors_rule

### ISSUE THREAD

**Issue by th1nkgr33n** [hashicorp/terraform-provider-azurerm#23121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "stpim" {
  count                    = var.enable_pib_processing ? 1 : 0
  name                     = "stpim${var.environment}"
  location                 = azurerm_resource_group.backend_services.location
  resource_group_name      = azurerm_resource_group.backend_services.name
  account_tier             = "Standard"
  account_replication_type = "LRS"
  custom_domain {
    name          = "some_subdomain_${var.environment_domain_postfix}.xyz.com"
    use_subdomain = false
  }

  blob_properties {

    dynamic "cors_rule" {
      for_each = var.pim_blob_cors_rules
      content {
        allowed_origins    = cors_rule.value.allowed_origins
        allowed_methods    = cors_rule.value.allowed_methods
        allowed_headers    = cors_rule.value.allowed_headers
        exposed_headers    = cors_rule.value.exposed_headers
        max_age_in_seconds = cors_rule.value.max_age_in_seconds
      }
    }
  }
  tags = { "managedBy" : "terraform" }
}

and inside a tfvar file this var exist
pim_blob_cors_rules = [
  {
    allowed_origins    = ["https://localhost:3000"]
    allowed_methods    = ["GET", "HEAD", "OPTIONS"]
    allowed_headers    = [""]
    exposed_headers    = [""]
    max_age_in_seconds = 0
  },
  {
    allowed_origins    = ["https://*.xyz.com", "https://xyz.com"]
    allowed_methods    = ["GET", "HEAD", "OPTIONS"]
    allowed_headers    = [""]
    exposed_headers    = [""]
    max_age_in_seconds = 0
  }
]
```

### Debug Output/Panic Output

```shell
Error: updating Azure Storage Account `blob_properties` "stpimprod": storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestParameters" Message="Request parameters are invalid: properties.restorePolicy.days."
with azurerm_storage_account.stpim[0]
on pim_import.tf line 40, in resource "azurerm_storage_account" "stpim":
```

### Expected Behaviour

There  should only the cors_rules be added and the default values (which was never touched via azure portal) for restore_policy should notbe forced to change.

### Actual Behaviour

I'm forced to set restore_policy although this was nothing I want to set.
Unfortunately if I set this restory_policy -> days I'm again forced to set 
```
This must be used together with delete_retention_policy set, versioning_enabled and change_feed_enabled set to true.
```

And then next thing I'm getting to force to enable change_feed
```
Error: `change_feed_enabled` must be `true` when `restore_policy` is set
```

### Steps to Reproduce

We are running on Terraform Cloud for this. Could not provide appropriate command.

**Comment by th1nkgr33n** [comment]
A I have to add, that these errors only appear if I finally apply the planned run. After a plan, everything looks good.

**Comment by magodo** [comment]
@th1nkgr33n I used the following config, it works fine for me (apply+plan):

```
resource "azurerm_storage_account" "test" {
  name                = "acctestaccknknk"
  resource_group_name = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  blob_properties {
    cors_rule {
      allowed_origins    = ["http://www.example.com"]
      exposed_headers    = ["x-tempo-*", "x-method-*"]
      allowed_headers    = ["*"]
      allowed_methods    = ["GET"]
      max_age_in_seconds = "2000000000"
    }
  }
}
```

I also inspected the request actually being sent, it has the following content:

```json
{
  "properties": {
    "cors": {
      "corsRules": [
        {
          "allowedOrigins": [
            "http://www.example.com"
          ],
          "allowedMethods": [
            "GET"
          ],
          "maxAgeInSeconds": 2000000000,
          "exposedHeaders": [
            "x-tempo-*",
            "x-method-*"
          ],
          "allowedHeaders": [
            "*"
          ]
        }
      ]
    },
    "deleteRetentionPolicy": {
      "enabled": false
    },
    "isVersioningEnabled": false,
    "changeFeed": {
      "enabled": false
    },
    "restorePolicy": {
      "enabled": false
    },
    "containerDeleteRetentionPolicy": {
      "enabled": false
    },
    "lastAccessTimeTrackingPolicy": {
      "enable": false
    }
  }
}
```

Which also looks good to me.

**Comment by th1nkgr33n** [comment]
@magodo yeah the config on my side is the same, just wrapped inside a dynamic block because I have more than one cors_rule to add.

And the actual request which goes to Azure is also the same like yours
```
2023-08-30T12:11:08.575Z [DEBUG] provider.terraform-provider-azurerm_v3.69.0_x5: AzureRM Request: 
PUT /subscriptions/xxxxxx/resourceGroups/rg-xxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxx/blobServices/default?api-version=2021-09-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.20.5 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v66.0.0 storage/2021-09-01 HashiCorp Terraform/1.5.5 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.69.0 pid-222c6c49-1b0a-5959-xxxx-6608f9eb8820
Content-Length: 780
Content-Type: application/json; charset=utf-8
X-Ms-Correlation-Request-Id: 0a56abc3-c8c5-332d-xxxx-a754efc0dc35
Accept-Encoding: gzip

{
  "properties": {
    "cors": {
      "corsRules": [{
        "allowedOrigins": ["https://localhost:3000"],
        "allowedMethods": ["GET", "HEAD", "OPTIONS"],
        "maxAgeInSeconds": 0,
        "exposedHeaders": [""],
        "allowedHeaders": [""]
      }, {
        "allowedOrigins": ["https://*.xyz.com", "https://www.xyz.com", "https://xyz.com"],
        "allowedMethods": ["GET", "HEAD", "OPTIONS"],
        "maxAgeInSeconds": 0,
        "exposedHeaders": [""],
        "allowedHeaders": [""]
      }]
    },
    "deleteRetentionPolicy": {
      "enabled": false
    },
    "isVersioningEnabled": false,
    "changeFeed": {
      "enabled": false
    },
    "restorePolicy": {
      "enabled": false
    },
    "containerDeleteRetentionPolicy": {
      "enabled": false
    },
    "lastAccessTimeTrackingPolicy": {
      "enable": false
    }
  }
}
```

And it respons with a BadRequest
```
{"error":{"code":"InvalidRequestParameters","message":"Request parameters are invalid: properties.restorePolicy.days."}}: timestamp=2023-08-30T12:11:09.378Z
```

**Comment by th1nkgr33n** [comment]
Hmmm... I think its not a provider problem.
I can see that if I use the "template export" via portal, it looks like this
```
"properties": {
    "changeFeed": {
        "enabled": false
    },
    "restorePolicy": {
        "enabled": false,
        "days": 6
    },
    "containerDeleteRetentionPolicy": {
        "enabled": false
    },
}
```
I guess that in the past we had enabled the restorePolicy via portal and disabled it later. And the portal api left the "days" there as garbage. If I check other storage account with untouched "restorePolicy" there exist only property "enabled" and not "days"

I will investigate this and if I'm right, I will close this issue later.

**Comment by th1nkgr33n** [comment]
After some Microsoft Support Headache I got more insights about this problem.

So the support told me that if you enable and afterwards disable the "Enable point-in-time restore for containers" it is a expected behaviour that the property "days" is left there.
On my question "why?" they was not able to give me a proper answer. But they took a lot of notes and try to reproduce it. Future will tell what happens.

The API endpoint to update the "blob_properties" will throw errors due to the fact, that the "days" field is missing from Terraform request, although its not necessary to include because its "disabled" anyways.
As well that the Validation of the API Endpoint throws errors because of this unneeded property they couldn't really help more than taking notes and lead this issue to their technical advisor.

But nonetheless there might be a second option if MS insists on this strange behaviour. Maybe adapt the provider flexability. The Provider is not very flexible on configure these "properties". Only "days" could be set, which auto enable the prop on ResourceManager level to "enable = true"
```
A restore_policy block supports the following:
[days](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#days) - (Required) Specifies the number of days that the blob can be restored, between 1 and 365 days. This must be less than the days specified for delete_retention_policy.
```
The Provider produces this as a api request body per default, if I configure "no"-policy.
```
{
  "properties": {
    "deleteRetentionPolicy": {
      "enabled": false
    },
    "isVersioningEnabled": false,
    "changeFeed": {
      "enabled": false
    },
    "restorePolicy": {
      "enabled": false
    },
    "containerDeleteRetentionPolicy": {
      "enabled": false
    },
    "lastAccessTimeTrackingPolicy": {
      "enable": false
    }
  }
}
```
And If I set "days" like in the docs.. the provider produces something like this
```
{
    "deleteRetentionPolicy": {
      "enabled": true
      "days": 7
    },
    "isVersioningEnabled": true,
    "changeFeed": {
      "enabled": true
    },
    "restorePolicy": {
      "enabled": true
      "days": 6
    },
    "containerDeleteRetentionPolicy": {
      "enabled": false
    },
    "lastAccessTimeTrackingPolicy": {
      "enable": false
    }
  }
}
```
If the prop "enable" is also configurable via Terraform than I could adapt to the MS expected behaviour.
e.g.
```
resource "azurerm_storage_account" "stFooBar" {
  name                     = "stfoobar"
  location                 = "westeu"
  resource_group_name      = "rg_foobar"
  account_tier             = "Standard"
  account_replication_type = "LRS"

  blob_properties {
    restore_policy {
      enable = false   <<<<<------ currently not possible
      days = 6
    }
  }
  tags = { "managedBy" : "terraform" }
}
```

Kind regards

**Comment by th1nkgr33n** [comment]
Ok so MS will not likely change this.
What have to happen to create a Feature Request do adapt the Provider?

**Comment by th1nkgr33n** [comment]
Finally the azure support helped me in resetting the storage account.
Enabled via Portal the Point-In-Time and disabled via REST API Request removed the "days" field.

I will close this issue because it was more like a unexpected behaviour in azure than in the provider
