### ISSUE TITLE
Support for rate limiting in azurerm_web_application_firewall_policy

### ISSUE THREAD

**Issue by camilosantana** [hashicorp/terraform-provider-azurerm#23145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

support web application firewall custom rule for rate limiting.

ref: [rate-limiting-overview](https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/rate-limiting-overview)

Currently fails validation

`Error: expected custom_rules.0.rule_type to be one of [MatchRule Invalid], got RateLimitRule`

### New or Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_web_application_firewall_policy" "a" {
  name                = var.waf_policy_name
  resource_group_name = var.resource_group_name
  location            = var.location
  custom_rules {
    action    = "Block"
    name      = "ratelimit"
    priority  = 1
    rule_type = "RateLimitRule"
    match_conditions {
      match_values       = ["255.255.255.255/32", ]
      negation_condition = true
      operator           = "IPMatch"
      match_variables { variable_name = "RemoteAddr" }
    }
  }
...
...
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/23123 may be loosely related or wrapped up in the same work.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Please subscribe to the PR #23239 that has been created b @UppyAU to fix this issue.
