### ISSUE TITLE
Support for container apps jobs

### ISSUE THREAD

**Issue by fdebijl** [hashicorp/terraform-provider-azurerm#23165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello,

The recently GA'd [Azure Container Apps jobs](https://azure.microsoft.com/en-us/updates/generally-available-azure-container-apps-jobs/) are very interesting for our use case and would be really nice to have in this provider - the configuration could mostly inherit from `azurerm_container_app`, with the only addition being the trigger configuration. I've made a crude suggestion below, but the `trigger_config` block could also be unified into a single block, with a `trigger_type` key to differentiate the triggers - I don't know enough about developing terraform providers to say which one would be better.

Thank you in advance!

### New or Affected Resource(s)/Data Source(s)

`azurerm_container_app_job`

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app_job" "example" {
  name                         = "example-job"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  
  # One of event_, manual_ or scheduled_trigger_config must be present
  event_trigger_config {
    parallelism = 1
    replica_completion_count = 1
    scale {
      max_executions = 20
      min_executions = 2
      polling_interval = 60
      rules = [
        {
          auth = [
            {
              secret_ref= "secret"
              trigger_parameter = "trigger_param"
            }
          ]
          name = "string"
          type = "string"
        }
      ]
  }

  manual_trigger_config {
    parallelism = 1
    replica_completion_count = 1
  }

  scheduled_trigger_config {
    cron_expression = "0* /5 * * * *"
    parallelism = 4
    replica_completion_count = 1
  }

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }
}
```

### References

https://azure.microsoft.com/en-us/updates/generally-available-azure-container-apps-jobs/
https://learn.microsoft.com/en-us/azure/templates/microsoft.app/jobs?pivots=deployment-language-terraform

**Comment by dss010101** [comment]
There needs to be a way to mount a volume/fileshare for this.  Interestingly the portal does not offer one. but i understand it is available in ARM.  
most jobs typically do need a mount to write files or logs i would think - so odd that its not supported for jobs but is for container apps itself.    Unless im missing how to do this for containerapps jobs

**Comment by syepes** [comment]
+1

**Comment by dss010101** [comment]
curious if there is a way to do this as yet, including mounting a volume/fileshare using terraform?

**Comment by klemmchr** [comment]
> curious if there is a way to do this as yet, including mounting a volume/fileshare using terraform?

Since this issue is still open and the associated PR is still under review (and has been put on hold by the TF team), no.

**Comment by MichaelCastiau** [comment]
Is there an update as to when this possibly could be released in terraform. Our team would greatly benefit from terraform having support for container app jobs!
