### ISSUE TITLE
Error: expected a URI in the format `the-keyvault-name.vault.**` but got ""

### ISSUE THREAD

**Issue by OctavioCore** [hashicorp/terraform-provider-azurerm#23186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5, 1.5.6, 1.3.7

### AzureRM Provider Version

3.56.0 - 3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_linked_service_key_vault

### Terraform Configuration Files

```hcl
locals {
  tenant_name = "foobar-dev"
}

resource "azurerm_data_factory_linked_service_key_vault" "resource" {
  depends_on = [azurerm_key_vault.resource]

  name            = "LinkedKeyVault"
  data_factory_id = azurerm_data_factory.resource.id
  key_vault_id    = azurerm_key_vault.resource.id
  parameters = {
    "AzureKeyVaultName" = "foobar-dev-keyvault"
    "AzureKeyVaultURL"  = azurerm_key_vault.resource.vault_uri
  }
}

It would be quite hard to put the entire KeyVault resource in here; But it's a part of the same child module, has proper access policies configured for the Terraform service principal used for the rest of the deployment, and the network ACL is configured to allow traffic from the virtual network the machine that runs `apply` resides in. Nothing out of the ordinary.
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected a URI in the format `the-keyvault-name.vault.**` but got ""
(Pointing to the first line of the linked service resource)
```

### Expected Behaviour

The linked service should be created.

### Actual Behaviour

Terraform errored out, stating that the URI is in inproper format; The same code worked  fine a few weeks ago. I thought that it might be a race condition, the implicit dependency might have been missed - but adding an explicit one did not help.

The KeyVault that should become linked is properly outputting `keyvault_uri` - I've checked this value in the state, and it's "https://foobar-dev-keyvault.vault.azure.net/" which is correct, and the keyvault name matches `foobar-dev-keyvault`

Why does validation imply, that it's an empty string? Even when I've specified the key vault URI manually, it still did error with the same message, as if it was indeed an empty string.

### References

N/A

**Comment by rcskosir** [comment]
Thanks for opening this issue. Have you been able to try this on any of the more recent 3.x versions or on the new 4.x versions to see if this issue still persists?

**Comment by OctavioCore** [comment]
@rcskosir No, out of necessity we went with a manual approach. The infra stack I encountered this issue with is no longer in active operation, so I won't be able to verify this anytime soon.

**Comment by rcskosir** [comment]
@OctavioCore Thank you for the update! I am going to mark this as closed for now, but if you are able to verify that this is still an issue, reach out and we can either reopen this issue or open a new one.
