### ISSUE TITLE
Cannot register providers: Microsoft.Compute. Errors were: waiting for Subscription Provider

### ISSUE THREAD

**Issue by sreekanth3107** [hashicorp/terraform-provider-azurerm#23195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

v3.65.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
provider "azurerm" {
features{}
}
```

### Debug Output/Panic Output

```shell
Error: Error ensuring Resource Providers are registered.
Terraform automatically attempts to register the Resource Providers it supports to ensure it's able to provision resources.
If you don't have permission to register Resource Providers you may wish to use the "skip_provider_registration" flag in the Provider block to disable this functionality.
> API version 2019-XX-XX was not found for Microsoft.Foo
Could indicate either that the Resource Provider "Microsoft.Foo" requires registration,
but this could also indicate that this Azure Region doesn't support this API version.

Original Error: Cannot register providers: Microsoft.Compute. Errors were: waiting for Subscription Provider (Subscription: "XXX"
Provider Name: "Microsoft.Compute") to be registered: context deadline exceeded 	
with provider["registry.terraform.io/hashicorp/azurerm"],
```

### Expected Behaviour

successful apply

### Actual Behaviour

provider crashed

### References
I find a issue in Microsoft Q/A but this doesn't help because we didn't change any permissions expect the azurerm provider version. This is effected only newly created subs 
https://learn.microsoft.com/en-us/answers/questions/1354723/could-not-register-the-resource-provider-microsoft  
_No response_

**Comment by Mike-Nahmias** [comment]
I've been having this problem a lot lately. The azurerm provider seems to wait for all of the resource providers it registers to enter the "Registered" state, but I keep running into problems where some of these are stuck "Registering" for 12+ hours. This is against Microsoft's recommendation [in this article](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types):

> Your application code shouldn't block the creation of resources for a resource provider that is in the registering state. When you register the resource provider, the operation is done individually for each supported region. To create resources in a region, the registration only needs to be completed in that region. By not blocking a resource provider in the registering state, your application can continue much sooner than waiting for all regions to complete.


In the mean time, this is a simplified version of my workaround which seems ok so far:

1. In the provider, set skip_provider_registration = true
2. Use a local-exec provisioner to call the Azure CLI to register each provider you need (there is a resource to do this out there, but it also waits for the status to change to "Registered")
```
resource "null_resource" "provider_registration" {
  provisioner "local-exec" {
    command = "az provider register --namespace '${each.value}'"
  }
}
```
3. Add an explicit dependency on your resources/module calls that require a resource provider to ensure the provisioner runs first

**Comment by magodo** [comment]
I'm not sure why it takes so long time to register RP, but you can always skip the registration via:

```
export ARM_PROVIDER_ENHANCED_VALIDATION=1
export ARM_SKIP_PROVIDER_REGISTRATION=true
```

Meanwhile, if you still want to ensure some certain RPs are registered, you can use: `azurerm_resource_provider_registration`.

**Comment by amcsi** [comment]
I ran into this issue too. I'm not sure this is going to solve it for anyone else, but for some reason the problem was caused by the fact that I created an App Registration for TF to use with my Contributor user with which _I haven't created any TF resources yet_.

By - through the Azure Portal - manually creating a temporary Resource Group then promptly deleting it, suddenly TF plan/apply started working.
