### ISSUE TITLE
AssessmentsSnapshot and SubAssessmentsSnapshot not supported in azurerm_security_center_automation

### ISSUE THREAD

**Issue by dejiaja** [hashicorp/terraform-provider-azurerm#23198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.5

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_automation

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_automation" "continous_export" {
  name                = "ExportToEventHub"
  location            = var.location
  resource_group_name = var.resource_group_name

  action {
    type              = "eventhub"
    resource_id       = data.azurerm_eventhub.eventhub.id
    connection_string = azurerm_eventhub_authorization_rule.authrule.primary_connection_string
  }
  source {
    event_source = "Assessments"
    rule_set {
      rule {
          property_path  = "type"
          operator       = "Contains"
          expected_value = "Microsoft.Security/assessments"
          property_type  = "String" 
      }
/*       dynamic "rule" {
        for_each = toset(var.export_recommendations_severity)
        iterator = export
        content {
          property_path  = "severity"
          operator       = "Equals"
          expected_value = export.value
          property_type  = "String" 
        }
      } */
    }
  }
  

  source {
    event_source = "Alerts"
    rule_set {
      dynamic "rule" {
        for_each = var.export_securityalerts_severity
        iterator = export
        content {
                 property_path  = "severity"
        operator       = "Equals"
        expected_value = export.value
        property_type  = "String" 
        }
      }
    }
  }

  source {
   event_source = "RegulatoryComplianceAssessment"
  }

  source {
   event_source = "RegulatoryComplianceAssessmentSnapshot"
  }
  
  source {
   event_source = "SubAssessments"
  }

  source {
   event_source = "SubAssessmentsSnapshot"
  }

  source {
   event_source = "AssessmentsSnapshot"
  }

  scopes = var.export_subscription_scopes
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected source.5.event_source to be one of [Alerts Assessments RegulatoryComplianceAssessment RegulatoryComplianceAssessmentSnapshot SecureScoreControls SecureScoreControlsSnapshot SecureScores SecureScoresSnapshot SubAssessments], got SubAssessmentsSnapshot
│ 
│   with module.defender_continuous_export.azurerm_security_center_automation.continous_export,
│   on ../terraform-modules/defender-for-cloud/main.tf line 71, in resource "azurerm_security_center_automation" "continous_export":
│   71:    event_source = "SubAssessmentsSnapshot"
│ 
╵
╷
│ Error: expected source.6.event_source to be one of [Alerts Assessments RegulatoryComplianceAssessment RegulatoryComplianceAssessmentSnapshot SecureScoreControls SecureScoreControlsSnapshot SecureScores SecureScoresSnapshot SubAssessments], got AssessmentsSnapshot
│ 
│   with module.defender_continuous_export.azurerm_security_center_automation.continous_export,
│   on ../terraform-modules/defender-for-cloud/main.tf line 75, in resource "azurerm_security_center_automation" "continous_export":
│   75:    event_source = "AssessmentsSnapshot"
│
```

### Expected Behaviour

Terraform apply should succeed and continuous export should be visible on the Azure Portal post deployment.

### Actual Behaviour

Terraform apply fails when I try to set event_source as AssessmentsSnapshot or SubAssessmentsSnapshot

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/18919 similar issue created however using azapi is not a solution.

**Comment by rcskosir** [comment]
@dejiaja Thank you for taking the time to create this issue. 
Issue #18919 is still an open enhancement request for adding support for AssessmentsSnapshot and SubAssessmentsSnapshot. I understand using azapi may not work for you and is not a solution. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #18919 which is still open for contributions.
