### ISSUE TITLE
[BUG] Setting kubelet_config.image_gc_high_threshold on default_node_pool never finishes apply

### ISSUE THREAD

**Issue by panos-indev** [hashicorp/terraform-provider-azurerm#23210]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurem_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "main" {
    tags = local.common_tags
    location = var.location
    name = "${local.prefix}"
    resource_group_name = azurerm_resource_group.main.name
    dns_prefix = var.cluster_dns_prefix
    sku_tier = "Standard"
    azure_policy_enabled = true
    oidc_issuer_enabled = true

    identity {
        type = "UserAssigned"
        identity_ids = [azurerm_user_assigned_identity.cluster.id]
    }

    default_node_pool {
        name = var.nodepool_name
        vm_size = var.vm_size
        node_count = var.node_count
        os_disk_size_gb = var.vm_disk_size
        os_sku = "AzureLinux"
        kubelet_disk_type = "OS"
        max_pods = 200
        enable_node_public_ip = false
        zones = [1, 2, 3]
        kubelet_config {
            container_log_max_size_mb = 50
            container_log_max_line = 10
            image_gc_high_threshold = 80
        }
        temporary_name_for_rotation = "temprotation"
    }

    linux_profile {
        admin_username = "admin"

        ssh_key {
            key_data = tls_private_key.main.public_key_openssh
        }
    }

    azure_active_directory_role_based_access_control {
        managed = true
        admin_group_object_ids = data.azuread_groups.cluster_admins.object_ids
    }

    key_vault_secrets_provider {
        secret_rotation_enabled = false
    }

    network_profile {
        network_plugin = "azure"
        load_balancer_sku = "standard"
    }


    node_os_channel_upgrade = "SecurityPatch"
    automatic_channel_upgrade = "patch"
    maintenance_window_auto_upgrade {
        utc_offset = "+02:00"
        frequency = "Weekly"
        interval = 1
        duration = 4
        day_of_week = "Monday"
        start_time = "03:00"
    }
    maintenance_window_node_os {
        utc_offset = "+02:00"
        frequency   = "Weekly"
        interval    = 1
        duration    = 4
        day_of_week = "Monday"
        start_time  = "03:00"
    }
}
```

### Debug Output/Panic Output

```shell
The output is just a resource creation timeout after 1h30m...
```

### Expected Behaviour

Create or update the cluster with the required configuration.

### Actual Behaviour

The node pool of the cluster is left on a "Creating" state when trying to create. When trying to update, the temporary node pool is left on a "Ready" state but with 0/0 nodes ready, while the original default pool is left on "Deleting" state.

### Steps to Reproduce

Try to create a cluster with a value on kubelet_config.image_gc_high_threshold and the default_node_pool. I have tried with Ubuntu nodes as well and the behavior is the same. When i destroy, remove image_gc_high_threshold and create a new cluster,  everything works fine.

### References

It may as well be a problem with the API of azure or AKS itself, but I do not have the time to test further.

**Comment by stephybun** [comment]
Thanks for opening this issue @panos-indev.

The reason the cluster cannot provision is because [the default for the `image_gc_low_threshold` property is 80](https://learn.microsoft.com/en-us/rest/api/aks/agent-pools/create-or-update?view=rest-aks-2023-11-01&tabs=HTTP#kubeletconfig). So I suspect the value of the high and low threshold are conflicting, resulting in an invalid kubelet config.

You can set `image_gc_high_threshold` to 80 by lowering the `image_gc_low_threshold` as well e.g.

```
    kubelet_config {
      image_gc_high_threshold = 80
      image_gc_low_threshold = 70
    }
```

I'm going to close this issue since this isn't a problem with the provider. The configuration example above should help you provision your cluster.

**Comment by panos-indev** [comment]
So, it is a problem with azure? Something should throw an error that the specified kubelet config is incorrect instead of having terraform wait forever...

**Comment by stephybun** [comment]
I agree, the error message I received after the timeout also wasn't particularly helpful
```
│ Error: waiting for creation of Kubernetes Cluster (Subscription: ""
│ Resource Group Name: ""
│ Kubernetes Cluster Name: ""): Code="NodesNotReady" Message="Internal server error"
```
The AKS API is usually quite good at validating the cluster config and throwing an error immediately if there is something awry and while we do make a concerted effort to add validation into the provider to prevent users from ending up with broken clusters we can only work with the information that we get back from the API.

I'd suggest raising an issue on [Azure/AKS](https://github.com/Azure/AKS) to request better messaging around kubelet configuration errors.
