### ISSUE TITLE
Web app missing ARR infinity option

### ISSUE THREAD

**Issue by danpetitt** [hashicorp/terraform-provider-azurerm#23227]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Web apps have an optional ARR Infinity option which defaults to true, but is recommended to be false when your app is stateless  as it improves performance and removes an additional cookie.

Please add this option to the `site_config` block

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_webapp

### Potential Terraform Configuration

```hcl
site_config {
  arr_infinity = false
}
```

**Comment by UppyAU** [comment]
```
[client_affinity_enabled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_web_app#client_affinity_enabled) - (Optional) Should Client Affinity be enabled?
```

I think this might be the setting you are after @danpetitt ?

**Comment by danpetitt** [comment]
Yes, it is; how on earth did I miss that. I searched, I scrolled and didn't see it!

Apologies for wasting your time, and thanks for pointing it out.
