### ISSUE TITLE
Changing the capacity on azurerm_cognitive_deployment forces replacement

### ISSUE THREAD

**Issue by kliseb** [hashicorp/terraform-provider-azurerm#23226]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.2

### AzureRM Provider Version

v3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_account" "account" {
  location              = "eastus"
  resource_group_name   = var.rg_name
  name                  = "account-name"
  custom_subdomain_name = "subdomain-name"
  kind                  = "OpenAI"
  sku_name              = "S0"
}


resource "azurerm_cognitive_deployment" "deployment" {
  name                 = "name"
  cognitive_account_id = azurerm_cognitive_account.account.id
  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0301"
  }

  scale {
    type     = "Standard"
    capacity = 30
  }
}
```

### Debug Output/Panic Output

```shell
-/+ resource "azurerm_cognitive_deployment" "deployment" {
      ~ id                   = "<deployment-id>" -> (known after apply)
        name                 = "name"
        # (2 unchanged attributes hidden)

      ~ scale {
          ~ capacity = 30 -> 29 # forces replacement
            # (1 unchanged attribute hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

Changing the capacity (in this example, from 30 to 29) I would expect not to force replacement of the deployment.

### Actual Behaviour

If we want to change the capacity of our deployments, we must either change it through the azure portal or accept that our deployment won't exist for a short time. Perhaps azure also replaces the deployment silently in the background and there is no way to avoid replacing the deployment. If so, is there any azure documentation describing how they perform the capacity change?

**Comment by liuwuliuyun** [comment]
Hi @kliseb , thanks for raising this issue. I will try to test locally about this property and raise PR to fix it if possible.

**Comment by kliseb** [comment]
Hi @liuwuliuyun, we're running into the same problem with changing `rai_policy_name`. Should I open a new issue for this?

**Comment by kliseb** [comment]
I found a bug, so I'll open a new issue
