### ISSUE TITLE
Support for default encryption scope on ADLS gen2 filesystem

### ISSUE THREAD

**Issue by gdubya** [hashicorp/terraform-provider-azurerm#23232]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

We are using customer managed keys. We would like to be able to set a default encryption scope at the container / file system level for a storage account.

This is equivalent to the `default_encryption_scope` and `deny_encryption_scope_override` attributes on the BlobContainer object in Pulumi: 
* https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/blobcontainer/
* https://www.pulumi.com/registry/packages/azure-native/api-docs/storage/encryptionscope/

See also: https://learn.microsoft.com/en-us/azure/storage/blobs/encryption-scope-overview#encryption-scopes-for-containers-and-blobs

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem

### Potential Terraform Configuration

```
resource "azurerm_storage_data_lake_gen2_filesystem" "container1" {
    name               = "container1"
    storage_account_id = data.storageAccount1.id
    default_encryption_scope = data.encryptionscope185.id
    deny_encryption_scope_override = true
}
```

**Comment by rcskosir** [comment]
@gdubya Thank you for taking the time to open this feature request!
