### ISSUE TITLE
AzureBastionSubnet & AzureFirewallSubnet Subnet Name Requirements Do Not Match Azure Behavior

### ISSUE THREAD

**Issue by BrokeAssChewbacca** [hashicorp/terraform-provider-azurerm#23247]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_bastion_host, azurerm_firewall

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "examplevnet"
  address_space       = ["192.168.1.0/24"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "azurebastionsubnet"  # This is the cause of the issue
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["192.168.1.224/27"]
}

resource "azurerm_public_ip" "example" {
  name                = "examplepip"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  allocation_method   = "Static"
  sku                 = "Standard"
}

resource "azurerm_bastion_host" "example" {
  name                = "examplebastion"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.example.id
    public_ip_address_id = azurerm_public_ip.example.id
  }
}
```

### Debug Output/Panic Output

```shell
The name of the Subnet for "ip_configuration.0.subnet_id" must be exactly 'AzureBastionSubnet' to be used for the Azure Bastion Host resource.
```

### Expected Behaviour

I understand that Azure documentation says the subnets must be named "AzureBastionSubnet" and "AzureFirewallSubnet", however from the portal & API, the uppercase does not seem to matter. I've tested from the portal with "AzureBastionsubnet", "aZurEbasTionSubnet", ect.. and it allows it. 

We have inherited a Bastion host that was deployed into a subnet via the Azure portal named "AzureBastionsubnet". At this time, we are unable to import this resource to manage it with Terraform due to the subnet name check this provider performs.

Expected behavior due to behavior seen in the Azure portal * API: The `terraform plan` should not generate an error due to mismatch casing in the subnet name.

The same applies to `AzureFirewallSubnet` and `azurerm_firewall`.

### Actual Behaviour

A `terraform plan` generates the following error:

The name of the Subnet for "ip_configuration.0.subnet_id" must be exactly 'AzureBastionSubnet' to be used for the Azure Bastion Host resource.

### Steps to Reproduce

`terraform plan`

### References

https://learn.microsoft.com/en-us/azure/bastion/configuration-settings#subnet

https://learn.microsoft.com/en-us/azure/firewall/deploy-firewall-basic-portal-policy

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. The error message you mentioned is returned by service API, which means service API doesn't allow this format. Per my understanding, I assume Azure Portal misses the validation for the subnet name. Suggest to file an Azure Support ticket for this issue.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/19754191/63149c2d-8235-46bc-b30e-e658c73d9604)

**Comment by BrokeAssChewbacca** [comment]
> Thanks for raising this issue. The error message you mentioned is returned by service API, which means service API doesn't allow this format. Per my understanding, I assume Azure Portal misses the validation for the subnet name. Suggest to file an Azure Support ticket for this issue.
> 
> ![image](https://user-images.githubusercontent.com/19754191/267817159-63149c2d-8235-46bc-b30e-e658c73d9604.png)

Hey @neil-yechenwei, thank you for the response. I have verified that I am able to deploy a Bastion host in a subnet named `azurebastionsubnet` using Azure CLI:

```
# Created the resource group, vnet, subnet, and public IP from the portal prior to this
$ az network bastion create \
  --name bastion-test \
  --public-ip-address bastion-test \
  --resource-group bastion-test \
  --vnet-name bastion-test

# Validate creation
$ az network bastion show \
> --name bastion-test \
> --resource-group bastion-test

# Truncated output below
{
  ...
  "ipConfigurations": [
      "resourceGroup": "bastion-test",
      "subnet": {
        "id": "/subscriptions/<subscription-id>/resourceGroups/bastion-test/providers/Microsoft.Network/virtualNetworks/bastion-test/subnets/azurebastionsubnet",
        "resourceGroup": "bastion-test"
      },
    ]
      ...
}
```

So it seems that both the Azure Portal and Azure API do not require the PascalCase spelling. I also see the subnet name check and corresponding error I received in [terraform-provider-azurerm/internal/services/network/validate/bastion_subnet_name.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/021ceae91f4723aa1ca34204f876e8b765044334/internal/services/network/validate/bastion_subnet_name.go#L19). Am I misunderstanding your response?

I understand that Azure documentation says the subnet names **must** be `AzureBastionSubnet` and `AzureFirewallSubnet` respectively, but Azure does not seem to be enforcing the PascalCase, and until they do, I don't believe this provider should be enforcing it either. Thanks!

**Comment by BrokeAssChewbacca** [comment]
I reached out to Azure support to get some info around this on their end. They said that they temporarily removed the case checking for these two subnet names but plan to add it back in the near future.

Due to that, no change is needed here. Closing this issue, thanks!

**Comment by james-sawyer-boe** [comment]
I presume this has been reintroduced as I have the same issue
