### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert_v2 does not support adx as source

### ISSUE THREAD

**Issue by JuupHietbrink** [hashicorp/terraform-provider-azurerm#23248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "log_alert" {
  name                      = "Name"
  display_name              = "Name"
  resource_group_name       = var.resource_group_name
  location                  = var.location
  evaluation_frequency      = "P1D"
  window_duration           = "P1D"
  scopes                    = [data.azurerm_resource_group.rg.id]
  severity                  = 3
  skip_query_validation     = true
  criteria {
    query                   = <<-QUERY
    adx('https://help.kusto.windows.net/Samples').StormEvents
      QUERY
    time_aggregation_method = "Count"
    threshold               = 0
    operator                = "GreaterThan"
    failing_periods {
      minimum_failing_periods_to_trigger_alert = 1
      number_of_evaluation_periods             = 1
    }
  }
  enabled                   = var.action_groups_enabled
  action {
    action_groups           = [azurerm_monitor_action_group.email.id] #[azurerm_monitor_action_group.email.id]
  }
  tags                      = var.tags
}
```

### Debug Output/Panic Output

```shell
│ Scheduled Query Rule Name: "Name"): scheduledqueryrules.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure:
│ Service returned an error. Status=400 Code="BadRequest" Message="{\r\n  \"error\": {\r\n    \"message\": \"The request had some invalid properties\",\r\n    \"code\":
│ \"BadArgumentError\",\r\n    \"correlationId\": \"{my_correlation_id}\",\r\n    \"innererror\": {\r\n      \"code\": \"QueryValidationError\",\r\n      \"message\": \"The
│ 'adx' pattern cannot be used with the current authentication scheme\"\r\n    }\r\n  }\r\n}"
```

### Expected Behaviour

I have created the exact same alert in the azure portal with the same adx pattern and that works. I expected terraform to create the same alert rule with this same configuration.

https://learn.microsoft.com/en-us/azure/azure-monitor/logs/azure-monitor-data-explorer-proxy

**Comment by JuupHietbrink** [comment]
FYI: Also azurerm_monitor_scheduled_query_rules_alert does not support the adx as source.
Scheduled Query Rule Name: "Name"): scheduledqueryrules.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="{\r\n  \"error\": {\r\n    \"message\": \"The request had some invalid properties\",\r\n    \"code\": \"BadArgumentError\",\r\n    \"correlationId\": \"{my_reqeust_id}\",\r\n    \"innererror\": {\r\n      \"code\": \"QueryValidationError\",\r\n      \"message\": \"The 'adx' pattern cannot be used with the current authentication scheme\"\r\n    }\r\n  }\r\n}"

**Comment by crozzer** [comment]
I have also just hit this issue but using an ARM Template.  Adding `"skipQueryValidation": true, ` to the properties seemingly makes no difference either as it validates it anyway.

**Comment by crozzer** [comment]
@JuupHietbrink I have just got my ARM template to work just in case it helps you with you issue.  I just needed to add `"identity": {
    "type": "SystemAssigned"
 },`

**Comment by ASHR4** [comment]
This is affecting me as well. Raised #23437 in hopes of fixing this :)
