### ISSUE TITLE
azurerm_linux_function_app_slot shows changes in the indentity outside of TF which are not true

### ISSUE THREAD

**Issue by wojciech-czyz-asda** [hashicorp/terraform-provider-azurerm#23253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.4

### AzureRM Provider Version

3.56.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app_slot

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app_slot" "function_app_slot" {
  for_each = local.func_app_slots
  name     = each.value
  tags     = var.tags
  app_settings = var.app_settings

  function_app_id               = azurerm_linux_function_app.function_app.id
  https_only                    = true
  storage_account_name          = azurerm_storage_account.storage_account.name
  storage_uses_managed_identity = true
  functions_extension_version   = var.functions_extension_version
  virtual_network_subnet_id     = var.func_egress_subnet_id
  builtin_logging_enabled       = false
  
  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on                              = true
    application_insights_connection_string = data.azurerm_key_vault_secret.app_insights_secrets[local.app_insights_conn_str_kv_key].value
    application_insights_key               = data.azurerm_key_vault_secret.app_insights_secrets[local.app_insights_key_kv_key].value
    application_stack {
      node_version = var.func_node_version
    }
    ftps_state                        = "Disabled"
    http2_enabled                     = true
    minimum_tls_version               = "1.2"
    use_32_bit_worker                 = false
    vnet_route_all_enabled            = true
    websockets_enabled                = false
    health_check_path                 = "/api/v1/health"
    health_check_eviction_time_in_min = floor(var.func_healthcheck_max_ping_failures)
  }

  lifecycle {
    ignore_changes = [
      app_settings["MAINTENANCE_MODE_ENABLED"],
      site_config["health_check_eviction_time_in_min"]
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the
last "terraform apply" which may have affected this plan:

  # module.functionapp.azurerm_linux_function_app_slot.function_app_slot["s01"] has changed
  ~ resource "azurerm_linux_function_app_slot" "function_app_slot" {
      ~ app_settings                       = {
          ~ "DOMAIN_DEPLOYMENT_SLOT"                        = "s01" -> "prd"
            # (15 unchanged elements hidden)
        }
        id                                 = "/subscriptions/<subscription_id>/resourceGroups/<function_apps_resource_group>/providers/Microsoft.Web/sites/<function_app_name>/slots/s01"
        name                               = "s01"
        tags                               = {
            
        }
        # (26 unchanged attributes hidden)

      ~ identity {
          ~ principal_id = "*************4028d" -> "*************903"
            # (3 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

No changes should be detected as the values for the slot didn't change.

### Actual Behaviour

Changes detected and the changes detected are showing the values from the function app's production slot (not the deployment slot). Retry on the plan (sometimes it needs to be retried a couple of times) to not show the changes.

### Steps to Reproduce

1. Run terraform plan on existing infrastructure
2. See the "Object have changed outside of terraform"
3. Retry the terraform plan - see no changes in the infrastructure

This is non-deterministic - doesn't happen every time.

### Important Factoids

It works fine after upgrading terraform to 1.5.5 and azurerm 3.71.0 however both of the changelogs don't mention any fixes that could be related to this issue

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. Since this issue goes away after upgrading to terraform 1.5.5 and azurerm 3.71.0, there isn't anything to be fixed or resolved here. So that we can maintain focus on that, we instead ask that questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
