### ISSUE TITLE
azurerm_monitor_diagnostic_setting retention_policy deprecated without clear resolution

### ISSUE THREAD

**Issue by tlchaffi** [hashicorp/terraform-provider-azurerm#23250]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

>= 1.5.0, < 1.6.0

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_diagnostic_setting" "a_diagnostic_setting" {
  name               = "diagnostics-app"
  target_resource_id = azurerm_linux_web_app.app.id
  storage_account_id = azurerm_storage_account.stlogs01.id

  enabled_log {
    category = "AppServiceAppLogs"
    retention_policy {
      days    = 7
      enabled = true
    }
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Warning: Argument is deprecated
│ 
│   with module.myapp.azurerm_monitor_diagnostic_setting.a_diagnostic_setting,
│   on projects/myapp/app_api.tf line 64, in resource "azurerm_monitor_diagnostic_setting" "a_diagnostic_setting":
│   64: resource "azurerm_monitor_diagnostic_setting" "a_diagnostic_setting" {
│ 
│ `retention_policy` has been deprecated - to learn more
│ https://aka.ms/diagnostic_settings_log_retention
│ 
│ (and 23 more similar warnings elsewhere)
╵
```

### Expected Behaviour

1. The warning message should be more explicit and state that this needs to be removed, and replaced with a new resource block, azurerm_storage_management_policy.

2. The documentation [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting) mentions nothing about the attribute being deprecated. Furthermore it offers no guidance in an approach to resolve the deprecation. It should make some mention that the attribute is being removed from the resource type, and is being replaced with azurerm_storage_management_policy.

### Actual Behaviour

Warning message presented in plan and validate steps of Terraform.

### Steps to Reproduce

terraform plan
terraform validate

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23260 which has been opened by @teowa to fix this issue.

**Comment by nkol2307** [comment]
any update on this? 

which other resource to use instead of retention_policy
