### ISSUE TITLE
Incorrect type for percentage_filter_value in azurerm_app_configuration_feature

### ISSUE THREAD

**Issue by baximan** [hashicorp/terraform-provider-azurerm#23258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.70.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_feature

### Terraform Configuration Files

```hcl
There are 2 issues with percentage_filter_value:
1. Azurerm documentation mentions incorrect type. Should be `number` instead of `list of numbers`

2. Missing information on possible values for it. Tried using 0,1 and 2. No changes appear on Azure Portal. Please clarify what are the possible values and if it refers to the 'use feature filter' on the Portal.

resource "azurerm_app_configuration" "app_configuration" {
  name                = "app-config-1"
  resource_group_name = "rg-1"
  location            = "Canada Central"
  sku                 = "standard"
}

resource "azurerm_app_configuration_feature" "app_configuration_feature" {
  configuration_store_id  = azurerm_app_configuration.app_configuration.id
  description             = "mydescription"
  enabled                 = "true"
  label                   = "mylabel"
  name                    = "myname"
  percentage_filter_value = [1] // list of number like azurerm document mentions

  dynamic "targeting_filter" {
    default_rollout_percentage = "90"
  }
}
```

### Debug Output/Panic Output

```shell
ERROR when using list of numbers: 

│   on ..\main.tf line 14, in resource "azurerm_app_configuration_feature" "app_configuration_feature":
│   96:   percentage_filter_value = [1]
│     ├────────────────
│     │ percentage_filter_value is a list of number
│
│ Inappropriate value for attribute "percentage_filter_value": number required.
```

### Expected Behaviour

Expected behavior should be no error which is achieved by using attribute type as number.

### Steps to Reproduce

1. `terraform plan` the above config

**Comment by teowa** [comment]
Hi @baximan , the doc is wrong. From [Azure doc](https://learn.microsoft.com/en-us/azure/azure-app-configuration/howto-feature-filters-aspnet-core#configuring-a-feature-filter-in-azure-app-configuration), the `percentage_filter_value` should be a number, I have submit PR to fix the doc.

Thanks.

**Comment by baximan** [comment]
Thanks for confirming @teowa! Do you know what are the possible values and which field does it correspond to on Azure portal? It seems to be defaulting to zero and doesn't update anything on azure portal.

**Comment by teowa** [comment]
Hi @baximan , my config is:
```hcl
resource "azurerm_app_configuration_feature" "test" {
  configuration_store_id = azurerm_app_configuration.appconf.id
  description            = "test description"
  name                   = "test-ackey"
  label                  = "test-ackeylabel"
  enabled                = true
  percentage_filter_value= 1
}
```
 it corresponds to 
<img width="1458" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/493efd00-414d-49bb-8968-084604a52af7">

<img width="844" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/b2ce3d88-bea1-4689-a452-ef84a8d28b7f">

<img width="1319" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/1df459bd-3295-46f4-af13-d24a3203c8c7">

**Comment by baximan** [comment]
Hi @teowa , 

Okay! So, based on what you shared it's the % value for _Custom Filter_ . Are you able to provision Custom or Targeting or Time window filter through Terraform? I'm unable to as azurerm is missing an attribute to enable **Use filter feature**
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/77299022/fa1bb214-5d32-4dba-97a6-d7375128634d)

**Comment by teowa** [comment]
Hi @baximan , in azurerm, if either of `percentage_filter_value`, `targeting_filter` or `timewindow_filter` is specified, this means **Use filter feature** is enabled. Some examples on these fields can be found at https://github.com/hashicorp/terraform-provider-azurerm/blob/1014bf511188b572c0c619105551234be7fcbca3/internal/services/appconfiguration/app_configuration_feature_resource_test.go#L232-L250
