### ISSUE TITLE
`azurerm_security_center_setting` on resource creation with error target resource already exists.

### ISSUE THREAD

**Issue by haochen23** [hashicorp/terraform-provider-azurerm#23273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_setting

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.5"
}

resource "azurerm_security_center_setting" "this" {
  setting_name = "WDATP"
  enabled      = true
}
```

### Debug Output/Panic Output

```shell
│ Error: A resource with the ID "/subscriptions/xxxxxxxxxxxxxxxx/providers/Microsoft.Security/settings/WDATP" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_security_center_setting" for more information.
│ 
│   with azurerm_security_center_setting.this,
│   on main.tf line 104, in resource "azurerm_security_center_setting" "this":
│  104: resource "azurerm_security_center_setting" "this" {
```

### Expected Behaviour

Enable `WDATP` settings without the above error.

### Actual Behaviour

The `WDATP` settings is indeed enabled, however, together with the error message.

│ Error: A resource with the ID "/subscriptions/xxxxxxxxxxxxxxxx/providers/Microsoft.Security/settings/WDATP" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_security_center_setting" for more information.
│ 
│   with azurerm_security_center_setting.this,
│   on main.tf line 104, in resource "azurerm_security_center_setting" "this":
│  104: resource "azurerm_security_center_setting" "this" {

### Steps to Reproduce

just `terraform apply`

### Important Factoids

No

### References

#22702 

It seems the same error happens on disabling the settings.

I know in terraform doc it says "Deletion of this resource disables the setting." But it would be nice if we can simply set the argument `enabled      =  false`

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it's by design since there is an enabled existing WDATP in Azure. By default, it should be disabled. Maybe it's configured in another place or this resource is deleted from tf config because of carelessness. Suggest to import this existing resource first. BTW, it can be disabled via "enabled = false".

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
