### ISSUE TITLE
Support for more custom error page status code for application gateway

### ISSUE THREAD

**Issue by jazzywessy** [hashicorp/terraform-provider-azurerm#23280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently, azurerm_application_gateway http_listener custom_error_configurations status_code only allow 403 and 502.

However, on azure portal other status code is allowed which will defer from terraform state and cannot be track if it is manually added on azure portal.

### New or Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  sku {
    name     = "Standard_Small"
    tier     = "Standard"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = azurerm_subnet.frontend.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 80
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.example.id
  }

  backend_address_pool {
    name = local.backend_address_pool_name
  }

  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    path                  = "/path1/"
    port                  = 80
    protocol              = "Http"
    request_timeout       = 60
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Http"
    custom_error_configuration {
      status_code = “400”
      custom_error_page_url = “www.example.net/400.html”
    }
  }

  request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }
}
```

**Comment by rcskosir** [comment]
@jazzywessy Thank you for taking the time to open this feature request!

**Comment by psallis** [comment]
Support for the full list of status_codes at both Global and Listener level 
https://learn.microsoft.com/en-us/azure/application-gateway/custom-error

Adding an un-supported error page via CLI causes a terraform Apply error below, 

`Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayCustomErrorStatusCodeIsInvalid" Message="Custom error page has an invalid HTTP status code '500', for applicationGateways /subscriptions/[removed[/resourceGroups/[removed[/providers/Microsoft.Network/applicationGateways/[removed[. Valid status codes are: '[403, 502]'." Details=[]`

**Comment by kristeey** [comment]
Any updates on this?

**Comment by StefanSchoof** [comment]
I just noticed, that setting the error pages via powershell, will result into a error (Custom error pages has invalid HTTP status code '500' for <resource id>. Valid status codes are '[403, 502]') in the next apply.

**Comment by carnei-ro** [comment]
yeah, I tried to upgrade the API Version and still got the same error 🫠

**Comment by tgermain-impirica** [comment]
any update on this? I just received the same error
