### ISSUE TITLE
deploying container app: unautorized: authentication required

### ISSUE THREAD

**Issue by dss010101** [hashicorp/terraform-provider-azurerm#23285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

Terraform v1.5.7

### AzureRM Provider Version

3.53.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app, azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_app" "aca" {
  name = "aca-${var.name_prefix}"

  container_app_environment_id = azurerm_container_app_environment.app_env.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Single"

  secret {
    name  = "password"
    value = data.azurerm_container_registry.acr.admin_password
  }

  registry {
    server               = data.azurerm_container_registry.acr.login_server
    username             = data.azurerm_container_registry.acr.admin_username
    password_secret_name = "password"
  }


  ingress {
    allow_insecure_connections = false
    external_enabled           = true
    target_port                = 5050
    traffic_weight {
      percentage = 100
    }
  }

  template {
    container {
      name   = "test"
      image  = "hello_world:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }
```

### Debug Output/Panic Output

```shell
Error: creating Container App (Subscription: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Resource Group Name: "rg-myapp-datasvc-dev-eastus"
Container App Name: "aca-myapp-datasvc"): performing CreateOrUpdate: containerapps.ContainerAppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameterValueInContainerTemplate" Message="The following field(s) are either invalid or missing. Field 'template.containers.test.image' is invalid with details: 'Invalid value: \"hello_world:latest\": GET https:: UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/hello_world Type:repository]]';."

  with azurerm_container_app.aca,
  on main.tf line 58, in resource "azurerm_container_app" "aca":
  58: resource "azurerm_container_app" "aca" {

creating Container App (Subscription: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
Resource Group Name: "rg-myapp-datasvc-dev-eastus"
Container App Name: "aca-myapp-datasvc"): performing CreateOrUpdate: containerapps.ContainerAppsClient#CreateOrUpdate: Failure sending
request: StatusCode=0 -- Original Error: Code="InvalidParameterValueInContainerTemplate" Message="The following field(s) are either
invalid or missing. Field 'template.containers.test.image' is invalid with details: 'Invalid value: \"hello_world:latest\": GET https::
UNAUTHORIZED: authentication required; [map[Action:pull Class: Name:library/hello_world Type:repository]]';."
```

### Expected Behaviour

Im not sure why this is failing.  
The container registry is created fine and the image 'hello_world:latest' exists.
Admin user is enabled for the reigstry and i do see the 'password' and 'password2' available under Access key for that registry in azure portal.

Can anyone tell me what is wrong with this code? or why its failing?

**Comment by dss010101** [comment]
I was able to get past the above error after changing the template image property to
 ```image  = "${data.azurerm_container_registry.acr.login_server}/v8_pi_lab:latest"```
These things are so poorly documented.  it's not intuitive that I would need to do this given that I already have a registry entry embedded within the container app resource.  frustrating...

now after that I'm getting the following after about 8minutes...about to give up on this go with a vm instead.

```
│ creating Container App (Subscription: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
│ Resource Group Name: "rg-myapp-datasvc-dev-eastus"
│ Container App Name: "aca-myapp-datasvc"): polling after CreateOrUpdate: Code="ContainerAppOperationError" Message="Failed to provision revision for container app 'aca-myapp-datasvc'.
│ Error details: Operation expired."
```

**Comment by AndreasKratzig** [comment]
Hi @dss010101 ,

it looks like the ingress / traffic_weight block doesn't work correctly. Check out this issue [#20435](https://github.com/hashicorp/terraform-provider-azurerm/issues/20435).

Add the line `latest_revision = true` within the mentioned block to get this working as a workaround.

**Comment by dss010101** [comment]
> Hi @dss010101 ,
> 
> it looks like the ingress / traffic_weight block doesn't work correctly. Check out this issue [#20435](https://github.com/hashicorp/terraform-provider-azurerm/issues/20435).
> 
> Add the line `latest_revision = true` within the mentioned block to get this working as a workaround.

Thanks much! that did it

**Comment by rcskosir** [comment]
@dss01010 Thank you for taking the time to open this issue. Since you were able to get past the initial error of this issue, and the `Error details: Operation expired.` issue is tracked via issue #20435 I am going to mark this issue as closed to consolidate the duplicate discussion.
