### ISSUE TITLE
Azure Container Apps environment variables causes timeout

### ISSUE THREAD

**Issue by drmathias** [hashicorp/terraform-provider-azurerm#23289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  name     = myresourcegroup
  location = westeurope
}

resource "azurerm_log_analytics_workspace" "law" {
  name                = "law-myloganalyticsworkspace"
  location            = westeurope
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "cae" {
  name                       = cae-mycontainerappenv
  location                   = westeurope
  resource_group_name        = azurerm_resource_group.rg.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.log_analytics_workspace.id
}

resource "azurerm_container_app" "aca" {
  name                         = aca-mycontainerapp
  container_app_environment_id = azurerm_container_app_environment.cae.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Multiple"
  template {
    container {
      name   = "mycontainerapp"
      image  = "hello-world:latest"
      cpu    = 0.25
      memory = "0.5Gi"
      env {
        name  = "My__App_Config"
        value = "SomeValue"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Container App (Subscription: "..." Resource Group Name: "myresourcegroup" Container App Name: "mycontainerapp"): polling after CreateOrUpdate: Code="ContainerAppOperationError" Message="Failed to provision revision for container app 'mycontainerapp'. Error details: Operation expired."
```

### Expected Behaviour

Operation should not have timed out

### Actual Behaviour

Environment variables are created, by the operation will time out

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please take a look at this issue and the resulting discussion: #20435 

Adding `latest_revision = true` as suggested in the comments on issue #20435 will hopefully help as a work around. 

I am going to close this issue as a duplicate in favor of #20435 to consolidate the discussion.
