### ISSUE TITLE
Support for create_mode of "GeoRestore" in postgresql_flexible_server resource

### ISSUE THREAD

**Issue by prashantagavane** [hashicorp/terraform-provider-azurerm#23304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello Everyone,
The [postgresql_flexible_server resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server) does not support the create_mode of "GeoRestore".
it is possible to do it through azure portal, azi CLI as well as through azapi_resource. Since we have already configured flex servers through terraform and we need to implement DR solution, this feature becomes must to have. We have used similar configuration for single servers and to do the same for flex, we need to have option to select create mode as "GeoRestore"
is anyone found a workaround or are we expecting it to be available in upcoming releases? I have seen one issue raised couple of years back where I do not see any update since long long time. https://github.com/hashicorp/terraform-provider-azurerm/issues/16811

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of the existing issue #16811.
