### ISSUE TITLE
Support for azurerm_container_registry_token_password expiry = "Never"

### ISSUE THREAD

**Issue by Luskidoo** [hashicorp/terraform-provider-azurerm#23319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It is possible to create an ACR token password with an expiry of "Never" in the Azure portal but terraform requires a valid RFC3339 time.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_registry_token_password

### Potential Terraform Configuration

```hcl
resource "azurerm_container_registry_token" "example" {
  name                    = "example"
  container_registry_name = azurerm_container_registry.example.name
  resource_group_name     = azurerm_container_registry.example.resource_group_name
  scope_map_id            = azurerm_container_registry_scope_map.scope_map.id
}

resource "azurerm_container_registry_token_password" "example" {
  container_registry_token_id = azurerm_container_registry_token.example.id

  password1 {
    expiry = "Never"
  }
}
```

**Comment by magodo** [comment]
@Luskidoo You can simply omit the `expiry` attribute at all (since it is optional), which indicates no expiry (i.e. Never).

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If that is not the case, please provide additional information for a feature request, thanks!

**Comment by mloskot** [comment]
I wish the description of the `expiry` property included what @magodo explained in https://github.com/hashicorp/terraform-provider-azurerm/issues/23319#issuecomment-1727018757 as currently this is an implicit knowledge or wizardry :)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/80741/72e48be7-625d-4c81-a017-f3a3ea287130)
