### ISSUE TITLE
Support for description in network/nat rules in azurerm_firewall_policy_rule_collection_group

### ISSUE THREAD

**Issue by MaciejBrowarski** [hashicorp/terraform-provider-azurerm#23325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Please add --description argument for nat_rule_collection and network_rule in azurerm_firewall_policy_rule_collection_group.
This argument already exist for application_rule in Terraform module.
In SDK/AZ tools such limitation doesn't exists.

### New or Affected Resource(s)/Data Source(s)

azurerm_firewall_policy_rule_collection_group

### Potential Terraform Configuration

```hcl
Same as for application_rule in same module:
description - (Optional) The description which should be used for this rule.
```

### References

Terraform page:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_policy_rule_collection_group#description
AZ page:
https://learn.microsoft.com/en-us/cli/azure/network/firewall/policy/rule-collection-group/collection?view=azure-cli-latest
there is no limitation for --description option.

**Comment by rcskosir** [comment]
@MaciejBrowarski Thank you for taking the time to open this feature request!
