### ISSUE TITLE
can't read azure resources with manually added managedHSM encryption anymore

### ISSUE THREAD

**Issue by dano0b** [hashicorp/terraform-provider-azurerm#23321]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.65

### Affected Resource(s)/Data Source(s)

azurerm_storage_account
azurerm_mssql_server_transparent_data_encryption

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
  lifecycle {
    ignore_changes = [
      customer_managed_key
    ]
  }
}
# just used the doc example including ignore_changes
```

### Debug Output/Panic Output

```shell
╷
│ Error: internal-error: Managed HSM IDs are not supported as Key Vault Nested Items
│ 
│   with azurerm_storage_account.example,
│   on example.tf line 409, in resource "azurerm_storage_account" "example":
│  409: resource "azurerm_storage_account" "example" {
│ 
╵
while running terraform plan
```

### Expected Behaviour

Ignore customer managed key configuration outside of Terraform like in version 3.62.1 and before.

### Actual Behaviour

See error output above in Debug Output/Panic Output. Looks like a regression bug to me, since that behavior was working fine before.

Fails during plan to read Azure Resources. Also for other Azure Resources like azurerm_mssql_server_transparent_data_encryption 

### Steps to Reproduce

1. create storage via terraform
2. add manually managed HSM encrytion (since https://github.com/hashicorp/terraform-provider-azurerm/issues/14389 doesn't work)
3. run terraform plan with azurerm version 3.63+

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14389
https://github.com/hashicorp/terraform-provider-azurerm/issues/22977

**Comment by riemers** [comment]
This is not solved with the latest merger, verified this with version 3.102.0.  As stated by the author at https://github.com/hashicorp/terraform-provider-azurerm/pull/25088#issuecomment-1992534838
