### ISSUE TITLE
data source azurerm_network_service_tag produces incorrect results in AzureRM >= 3.69.0

### ISSUE THREAD

**Issue by vsabella** [hashicorp/terraform-provider-azurerm#23340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

data azurerm_network_service_tags

### Terraform Configuration Files

```hcl
# regional service
data "azurerm_network_service_tags" "storage" {
  location        = "westus2"
  service         = "Storage"
  location_filter = "westus2"
}
```

### Debug Output/Panic Output

```shell
see above
```

### Expected Behaviour

In 3.68.0 or earlier, the ID field is equal to the actual Service Tag from the api response. This is good because they are *case sensitive* if used in things like Firewall rules.
{
      + address_prefixes = [] # bunch of ips...
      **+ id               = "Storage.WestUS2"**
      + ipv4_cidrs       = [] # bunch of ips...
      + ipv6_cidrs       = [] # bunch of ips...
      + location         = "westus2"
      + location_filter  = "westus2"
      + service          = "Storage"
      + timeouts         = null

### Actual Behaviour

In 3.69.0 or later, the ID field was changed (see https://github.com/hashicorp/terraform-provider-azurerm/commit/05a8abd51c54a01cc370ec07114de5b4b6656b83#diff-ab68d1e4cc83749bc5f8f38b2fca60a4cb541c904f1275cf32eaf82dc8805d82R129)

This is bad because you cannot use "Storage.westus2" as a network storage tag safely, it will result in infinite drift between runs as the backend service corrects it to "Storage.WestUS2"

We expect the actual Azure API response to be returned, not a modified version of it, or at least the "Name" field returned from the Azure ID

  + b = {
      + address_prefixes = []
      **+ id               = "westus2-Storage"**
      + ipv4_cidrs       = []
      + ipv6_cidrs       = []
      + location         = "westus2"
      + location_filter  = "westus2"
      + service          = "Storage"
      + timeouts         = null
    }

### Steps to Reproduce

basica terraform plan/apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/commit/05a8abd51c54a01cc370ec07114de5b4b6656b83

**Comment by vsabella** [comment]
Tagging @tombuildsstuff

**Comment by wuxu92** [comment]
Hi @vsabella Thanks for raising this issue! The data source ID has been intentionally changed in the current provider version, as mentioned in the commit link provided. Would exposing the name of the service tag to the data source help to address this issue? @tombuildsstuff WDYT?

**Comment by vsabella** [comment]
@wuxu92  yes, exposing the name of the service tag would work :)
