### ISSUE TITLE
Support for higher CLI version in azurerm_resource_deployment_script_azure_cli

### ISSUE THREAD

**Issue by VincentVerweij** [hashicorp/terraform-provider-azurerm#23352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently it is possible with Bicep to deploy a ContainerApp Job. In order to achieve this, [the Microsoft Learn site](https://learn.microsoft.com/en-us/cli/azure/containerapp/job?view=azure-cli-latest) states the following:  
> This reference is part of the containerapp extension for the Azure CLI (version 2.45.0 or higher). The extension will automatically install the first time you run an az containerapp job command. [Learn more](https://learn.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview) about extensions.

I am using the following resource `azurerm_resource_deployment_script_azure_cli`. As can be seen [on the Hashicorp documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_deployment_script_azure_cli#version) and in [the code](https://github.com/hashicorp/terraform-provider-azurerm/blob/049a831cf08799ecfb3ecb4f475f99782182efa2/internal/services/resource/resource_deployment_script_common.go#L343) it only supports up till version `2.41.0`.  

As stated in the note we need at least version `2.45` or higher.

### New or Affected Resource(s)/Data Source(s)

azurerm_resource_deployment_script_azure_cli

### References

Here is the Bicep script that supports creating Azure ContainerApp Jobs since it can use CLI version `2.50.0`: https://gist.github.com/lukemurraynz/f2f2242ab8580a69db76f01b537d477c#file-main-bicep-L393

**Comment by rcskosir** [comment]
@VincentVerweij Thank you for taking the time to open this issue. Please subscribe to PR #23370  created by @teowa for this issue.
