### ISSUE TITLE
parsing the HostPool ID: the segment at position 6 didn't match

### ISSUE THREAD

**Issue by georgeollis** [hashicorp/terraform-provider-azurerm#23363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.74.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_application_group

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_application_group" "virtual_desktop_application_group" {
  name                         = var.name
  location                     = var.location
  resource_group_name          = var.resource_group_name
  default_desktop_display_name = var.default_desktop_display_name
  friendly_name                = var.friendly_name
  description                  = var.description
  host_pool_id                 = var.host_pool_id
  tags                         = var.tags
  type                         = var.type
}

Terraform TFVARS files with values

name = "test"
location = "uksouth"
type = "Desktop"
resource_group_name = "application_gateway_demo"
host_pool_id = "/subscriptions/xxxxxxx/resourceGroups/application_gateway_demo/providers/Microsoft.DesktopVirtualization/hostpools/test"
```

### Debug Output/Panic Output

```shell
│ Error: parsing "/subscriptions/baba41cf-c01d-4a55-b6c5-ca494b802be5/resourceGroups/application_gateway_demo/providers/Microsoft.DesktopVirtualization/hostpools/test": parsing segment "staticHostPools": parsing the HostPool ID: the segment at position 6 didn't match
│
│ Expected a HostPool ID that matched:
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.DesktopVirtualization/hostPools/hostPoolValue
│
│ However, this value was provided:
│
│ > /subscriptions/baba41cf-c01d-4a55-b6c5-ca494b802be5/resourceGroups/application_gateway_demo/providers/Microsoft.DesktopVirtualization/hostpools/test
│
│ The parsed Resource ID was missing a value for the segment at position 6
│ (which should be the literal value "hostPools").
│
│
│
│   with azurerm_virtual_desktop_application_group.virtual_desktop_application_group,
│   on azurerm_virtual_desktop_application_group.tf line 8, in resource "azurerm_virtual_desktop_application_group" "virtual_desktop_application_group":
│    8:   host_pool_id                 = var.host_pool_id
│
```

### Expected Behaviour

Should the host_pool_id value be using hostpools or hostPools? Currently, this is breaking deployments because getting the host pool resource ID via the Azure Portal using the following format:

/subscriptions/xxxxxx/resourceGroups/application_gateway_demo/providers/Microsoft.DesktopVirtualization/hostpools/test

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/76496924/934a27d9-5295-4b1e-98f5-158d06e4aa8f)

However, Terraform is expecting it to use hostPools instead of hostpools. 

### Actual Behaviour

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/76496924/d48937c0-7f03-4497-81f0-0e0c02eff12d)

**Comment by sinbai** [comment]
Hi @georgeollis  thanks for opening this issue. It is worth mentioning that Terraform provider replies on [Azure Rest API ](https://github.com/Azure/azure-rest-api-specs/blob/85d0d6c98a47a6b6c2c1684cf94cc8e089c3c4ab/specification/desktopvirtualization/resource-manager/Microsoft.DesktopVirtualization/stable/2023-09-05/desktopvirtualization.json#L2266C8-L2266C8)to manage Azure resources. Because the `host_pool_id` returned by API contains `hostPools` instead of `hostpool`,  it is by design that terraform provider requires the user to input the `hostPools`.

**Comment by georgeollis** [comment]
@sinbai If I create a Terraform host resource and output the host pool id. It is returned as _hostpools_ and not hostPools?

**Comment by georgeollis** [comment]
It appears to be working now... thanks.
