### ISSUE TITLE
Support for creating devbox resources

### ISSUE THREAD

**Issue by webstean** [hashicorp/terraform-provider-azurerm#23367]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Support for creating:-

devbox devcenteres
devbox projects
devbox definitions
devbox environment
devbox catalogs

### New or Affected Resource(s)/Data Source(s)

azurerm_devbox

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {

  name     = "devbox-example"
  location = "australiaeast"
  tags = { environment = "dev" }
}

resource "azurerm_devbox_devcenter" "example" {
  name                = "devcenter-example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  identity {
    type = "SystemAssigned"
  }
  tags = { environment = "dev" }
}

resource "azurerm_devbox_project" "example" {
  name                = "devproject-example"
  description         = "devproject example"   
  resource_group_name = azurerm_resource_group.example.name
  devcenter_id        = azurerm_devbox_devcenter.id
  dev_box_limits_enabled = true
  dev_box_per_developer = 2
  tags = { environment = "dev" }
}

resource "azurerm_devbox_definition" "example" {
  name                = "devproject-example"
  resource_group_name = azurerm_resource_group.example.name

  image {
    image               = "Windows 11 Enterprise + Developer Optimizations 22H2"
    version             = "latest"
    publisher           = "microsoft/visualstudio"
  }
  compute = "8 vCPU, 32GB RAM"
  storage = 256 GB SSD"
  hibernation_enable = true
}

resource "azurerm_devbox_environment" "example" {
  name                = "development-example"
  tags = { environment = "dev" }
}

resource "azurerm_devbox_catalog" "example" {
  name                = "catalog-example"

  repository_url = "https://github.com/example/example"
  source_control_type = "GitHub"
  branch              = "main"
  folder_path           = "devbox"
  secret_url            = "https://demp-devcenter--keyvault.vault.azure.net/secrets/secrets/pat"
}
```

**Comment by damienaicheh** [comment]
Hi @rcskosir I saw that the Dev Center was added to the provider with the #22592 issue which is really great, do you have an idea about when this related feature will be completed? Thanks!

**Comment by webstean** [comment]
Added with #22592 
devbox devcenteres
devbox projects

To be done:-
devbox definitions
devbox environment
devbox catalogs

would be a great start :-)

**Comment by damienaicheh** [comment]
Hi @rcskosir do you have an ETA for this issue please?

**Comment by dan-dimitrov** [comment]
Bump.
Our customer is on terraform and we need to deploy DevBox for their developer access. This includes devcentres, projects, definitions, environments and catalogs.

**Comment by dan-dimitrov** [comment]
@stephybun it appears that only environment type is supported.
We're still missing support for the following it appears...

- [ ] devbox devcenteres
- [ ] devbox projects
- [ ] devbox definitions
- [x] devbox environment
- [ ] devbox catalogs

**Comment by stephybun** [comment]
I believe these will all be available in the next release:

Available now:
dev center: https://github.com/hashicorp/terraform-provider-azurerm/pull/23538
projects: https://github.com/hashicorp/terraform-provider-azurerm/pull/23538
catalogs: https://github.com/hashicorp/terraform-provider-azurerm/pull/24833

Available in next minor release:
definitions: https://github.com/hashicorp/terraform-provider-azurerm/pull/26307
environment: https://github.com/hashicorp/terraform-provider-azurerm/pull/26291

**Comment by dan-dimitrov** [comment]
Thank you for confirming @stephybun :)
