### ISSUE TITLE
Logic App Action Body Not Does Accept Functions

### ISSUE THREAD

**Issue by nat-ray** [hashicorp/terraform-provider-azurerm#23365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I am facing an issue with Terraform 1.2.6 with provider azurerm 3.43.0 when trying to create an Azure logic app. I have it set up like this:

```
# Define the logic app

resource "azurerm_logic_app_workflow" "generic_app" {
  name                = "generic_app" 
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  identity {
    type = "SystemAssigned"
  }
}

# Run the logic app every 5 minutes

resource "azurerm_logic_app_trigger_custom" "generic_app_trigger" {
  name         = "generic_app_name"
  logic_app_id = azurerm_logic_app_workflow.generic_app.id

  body = <<BODY
{
  "recurrence": {
    "frequency": "Minute",
    "interval": 5
  },
  "type": "Recurrence"
}
BODY

}

# Perform the first action

resource "azurerm_logic_app_action_http" "generic_app_action_1" {
  name         = "HTTP"
  logic_app_id = azurerm_logic_app_workflow.generic_app.id
  method       = "POST"
  uri          = "https://some-endpoint.com"
  headers = {
    "authorization" = data.azurerm_key_vault_secret.authtoken_secret.value
    "content-type"  = "application/x-www-form-urlencoded"
  }
}

# Perform the second action if the first action completed

resource "azurerm_logic_app_action_http" "generic_app_action_2" {
  name          = "HTTP_1"
  logic_app_id  = azurerm_logic_app_workflow.generic_app.id
  depends_on    = [azurerm_logic_app_action_http.generic_app_action_1]
  method        = "POST"
  uri           = "https://some-endpoint.com"
  body          = "@decodeBase64(triggerBody()?['ContentData'])"
 
  headers = {
    "api-key"                = data.azurerm_key_vault_secret.api_key_secret.value
    "Authorization"            = "Bearer @{body('HTTP').access_token}"
    "Accept"                   = "application/json"
    "Content-Type"             = "application/json"
  }
  run_after {
    action_name   = "HTTP"
    action_result = "Succeeded"
  }
}
```

The terraform apply is successful, but in the Logic App Designer the `HTTP_1` action body (`@decodeBase64(triggerBody()?['ContentData'])`) does not appear correctly: 

![screenshot-1](https://github.com/hashicorp/terraform-provider-azurerm/assets/102099039/9ea618b5-46a3-415b-96c5-c7b8f4ed9345)

Instead it should be using the decodeBase64 function and appear like this:
![screenshot-2](https://github.com/hashicorp/terraform-provider-azurerm/assets/102099039/78e2287d-9266-4362-bc41-4b2be7908156)
![screenshot-3](https://github.com/hashicorp/terraform-provider-azurerm/assets/102099039/ceb89c65-7cdd-41ac-9eed-bc4fae59ea51)

I have also tried using a `azurerm_logic_app_action_custom` resource block instead:

```
resource "azurerm_logic_app_action_custom" "generic_app_action_2" {
  name         = "HTTP_1"
  logic_app_id = azurerm_logic_app_workflow.generic_app.id
  depends_on   = [azurerm_logic_app_action_http.generic_app_action_1]

  body = <<BODY
{
  "type": "Http",
  "inputs": {
    "method": "POST",
    "uri": "https://some-endpoint.com",
    "body": {
      "ContentData": "@{decodeBase64(triggerBody()?['ContentData'])}"
    },
    "headers": {      
      "Authorization": "Bearer @{body('HTTP').access_token}",
      "Accept": "application/json",
      "Content-Type": "application/json"
    }
  },
  "runAfter": {
    "HTTP": ["Succeeded"]
  }
}
BODY
}
```

But this is also not working.Is this a bug?

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.6

### AzureRM Provider Version

3.43.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_action_http

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1.2.5"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.43.0"
    }
  }
}
```

### Debug Output/Panic Output

```shell
n/a
```

**Comment by ziyeqf** [comment]
Hi @nat-ray, thanks for opening the issue.

I have give it a try and it shows as expected. 
<img width="866" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/51212351/6e0f9d47-c3b1-4426-bf0e-004b8daddf4c">

Do you mind updating your provider to the latest version and give it a try?

For any further questions please leave comments.

**Comment by ziyeqf** [comment]
Hi @nat-ray, thanks for reporting.

I tried to add that action on Portal, but after a fresh on that page, it shows as same as what Terraform created. While in the `Preview Designer`, both created by Terraform or Portal, it shows the function. So it might be a bug on the designer on Portal, rather than a bug of the provider.

I may suggest to open a support ticket on Azure for it.

For any further questions please leave comments, thanks!

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ziyeqf‘s response as an answer regarding the source of this behavior. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
