### ISSUE TITLE
`azurerm_cdn_frontdoor_rule` does not allow `cache_duration` of "00:00:00".

### ISSUE THREAD

**Issue by ingara** [hashicorp/terraform-provider-azurerm#23376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.7

### AzureRM Provider Version

3.40.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_rule

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_frontdoor_rule" "example" {
  cdn_frontdoor_rule_set_id = "/subscriptions/..."
  name                      = "disableDefaultCaching"
  order                     = 0

  actions {
    route_configuration_override_action {
      cdn_frontdoor_origin_group_id = "/subscriptions/..."
      cache_behavior                = "OverrideIfOriginMissing"
      cache_duration                = "00:00:00"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: "actions.0.route_configuration_override_action.0.cache_duration" must be longer than zero seconds, got "00:00:00"
```

### Expected Behaviour

It should successfully create the rule with duration set to 0 seconds.

This is possible in the Azure Portal, and is according to Microsoft the only way to "disable" the default caching behaviour for responses which do not have cache headers.

Relevant portion of the docs (https://learn.microsoft.com/en-us/azure/frontdoor/front-door-rules-engine-actions?tabs=portal&pivots=front-door-standard-premium#properties – under "Cache duration"):
> For a value of 0 seconds, the CDN caches the content, but must revalidate each request with the origin server.

The relevant code is at https://github.com/hashicorp/terraform-provider-azurerm/blob/48cd7502e9dc60011e8d6edaff26d5aee0ee2bc9/internal/services/cdn/validate/front_door_validation_helpers.go#L53-L55
As far as I can tell this explicit check should be removed.

### Actual Behaviour

Validation error.

### Steps to Reproduce

1. `terraform validate`

### References

- https://learn.microsoft.com/en-us/azure/frontdoor/front-door-rules-engine-actions?tabs=portal&pivots=front-door-standard-premium#properties

**Comment by rcskosir** [comment]
@ingara Thank you for taking the time to open this issue. Please subscribe to PR #23384 created by @WodansSon for this issue.
