### ISSUE TITLE
azurerm_recovery_services_vault user encryption cannot be set

### ISSUE THREAD

**Issue by BrunoPlancic** [hashicorp/terraform-provider-azurerm#23375]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.0

### AzureRM Provider Version

3.74.0

### Affected Resource(s)/Data Source(s)

azurerm_recovery_services_vault

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  location = var.rg_location
  name     = var.rg_name
  tags     = var.tags
}

resource "azurerm_recovery_services_vault" "vault" {
  name                = replace(var.rg_name,"rg-","rv-")
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"
  immutability        = "Unlocked"
  storage_mode_type   = "GeoRedundant"
  public_network_access_enabled = false
  cross_region_restore_enabled = true
  soft_delete_enabled = true
  encryption {
    infrastructure_encryption_enabled = false
    key_id = var.vault_encryption_key
    use_system_assigned_identity = true
  }
  identity {
    type = "SystemAssigned"
  }
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Error: updating Recovery Service Encryption Vault (Subscription: "<ID>"
│ Resource Group Name: "rg-azbackup-vm-test-2"
│ Vault Name: "rv-azbackup-vm-test-2"): polling after Update: polling failed: the Azure API returned the following error:
│
│ Status: "Failed"
│ Code: "UserErrorBMSCmkCannotBeEnabledVaultNotEmpty"
│ Message: "Encryption using customer managed keys cannot be enabled after registering items to the vault. Create a new vault and enable encryption using customer managed keys before adding any items for backup"
│ Activity Id: ""
│
│ ---
│
│ API Response:
│
│ ----[start]----
│ {
│   "id": "/subscriptions/<ID>/resourceGroups/rg-azbackup-vm-test-2/providers/Microsoft.RecoveryServices/vaults/rv-azbackup-vm-test-2/operationStatus/NDA5NTs3M2E4NmYxYi1kNjkzLTRiMjAtYmEwMy1hOGUxZDVjYTY5YjM=",
│   "name": "NDA5NTs3M2E4NmYxYi1kNjkzLTRiMjAtYmEwMy1hOGUxZDVjYTY5YjM=",
│   "status": "Failed",
│   "startTime": "9/25/2023 8:40:36 AM",
│   "endTime": "9/25/2023 8:44:38 AM",
│   "error": {
│     "code": "UserErrorBMSCmkCannotBeEnabledVaultNotEmpty",
│     "message": "Encryption using customer managed keys cannot be enabled after registering items to the vault. Create a new vault and enable encryption using customer managed keys before adding any items for backup"
│   }
│ }
│ -----[end]-----
│ , but recovery vault was created, a manually import might be required
│
│   with azurerm_recovery_services_vault.vault,
│   on main.tf line 10, in resource "azurerm_recovery_services_vault" "vault":
│   10: resource "azurerm_recovery_services_vault" "vault" {
```

### Expected Behaviour

It is expected for module to set up customer managed key for recovery services vault encryption.

### Actual Behaviour

Error was raised about items registered to the vault when there are none. If I comment out the encryption block vault is created normally. If I then uncomment encryption block and rerun terraform -apply encryption is enabled on vault.

**Comment by cleif** [comment]
### Successful Work around

@BrunoPlancic - unsure if you've found a work-around yet... I worked with MSFT Support on this exact issue.  This is a known behavior per their internal documentation.  There is no resolution, but there is a validated workaround.

Its def not a fix, but maybe helpful for anyone else running into this.

#### Workaround

The work around is a 2 step `terraform -apply` process.  The first apply needs to ensure your cross region restore is set to `false`

```
...
  cross_region_restore_enabled = false #HERE
  soft_delete_enabled = true
  encryption {
    infrastructure_encryption_enabled = false
    key_id = var.vault_encryption_key
    use_system_assigned_identity = true
  }
  identity {
    type = "SystemAssigned"
  }
....
```

Then after successful provisioning and state, update your code to reflect the `cross_region_restore_enabled = true`.

This resolved this issue and allowed complete provisioning.

> **Microsoft Internal Notes (from the Support Case)**
> Cause
> If CRR (Cross Region Restore) is enabled for the Vault, the storage state will be locked and it will interfere with further operations.
>
> So, as a summary, the problem seems to be related to the order selected to execute the operations.
> Please make sure to configure the script to enable CRR after enabling CMK encryption which is the process where the operation is currently failing.
> Check the order being used to create/modify the resources.

**Comment by ziyeqf** [comment]
Hi @BrunoPlancic and @cleif, thanks for reporting and the workaround.
 
Just submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/23618) for this, once it merged and released, it should be fixed. You can subscribe this PR to keep track on it.

For any other questions, please leave comments.Thanks!
