### ISSUE TITLE
azurerm_monitor_data_collection_rule does not seem to take the data_collection_endpoint_id into account

### ISSUE THREAD

**Issue by zadigus** [hashicorp/terraform-provider-azurerm#23386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.1

### AzureRM Provider Version

3.74.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_data_collection_endpoint" "dce" {
  name                = "MSProm-${var.location}-${var.cluster_name}"
  resource_group_name = var.resource_group_name
  location            = var.location
  kind                = "Linux"

  tags = var.tags
}

resource "azurerm_monitor_data_collection_rule" "dcr" {
  depends_on = [
    azurerm_monitor_data_collection_endpoint.dce,
  ]

  name                        = "MSProm-${var.location}-${var.cluster_name}"
  description                 = "DCR for Azure Monitor Metrics Profile (Managed Prometheus)"
  resource_group_name         = var.resource_group_name
  location                    = var.location
  data_collection_endpoint_id = azurerm_monitor_data_collection_endpoint.dce.id
  kind                        = "Linux"

  tags = var.tags

  destinations {
    monitor_account {
      monitor_account_id = var.monitor_workspace_id
      name               = "MonitoringAccount1"
    }
  }

  data_flow {
    streams      = ["Microsoft-PrometheusMetrics"]
    destinations = ["MonitoringAccount1"]
  }

  data_sources {
    prometheus_forwarder {
      streams = ["Microsoft-PrometheusMetrics"]
      name    = "PrometheusDataSource"
    }
  }
}
```

### Debug Output/Panic Output

```shell
all fine
```

### Expected Behaviour

I guess I should see the data collection endpoint set in the combobox on Azure:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8761254/c8fbeeb7-131d-4d3c-868a-a31b275a4357)

### Actual Behaviour

We see that the "Data collection endpoint" column is set to "No endpoint required".

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8761254/e0c88416-05e0-4060-905b-585e64e2fd06)

### Steps to Reproduce

```
terraform apply
```

**Comment by teowa** [comment]
Hi @zadigus , thanks for submitting this issue!
The combobox is related with the accociation resource. We should manually associate the resource to a Data Collection Endpoint, e.g., 
```hcl
# associate to a Data Collection Endpoint
resource "azurerm_monitor_data_collection_rule_association" "example2" {
  target_resource_id          = azurerm_kubernetes_cluster.example.id
  data_collection_endpoint_id = azurerm_monitor_data_collection_endpoint.example.id
  description                 = "example"
}
```

And the `azurerm_monitor_data_collection_rule.data_collection_endpoint_id` is used for [Logs Ingestion API](https://learn.microsoft.com/en-us/azure/azure-monitor/logs/logs-ingestion-api-overview)

**Comment by zadigus** [comment]
Hmmm I'll give it a go, I thought it was covered by the following association
```hcl
resource "azurerm_monitor_data_collection_rule_association" "dcra" {
  depends_on = [
    azurerm_monitor_data_collection_rule.dcr
  ]

  name                             = "MSProm-${var.location}-${var.cluster_name}"
  target_resource_id        = var.cluster_id
  data_collection_rule_id = azurerm_monitor_data_collection_rule.dcr.id
  description                    = "Association of data collection rule. Deleting this association will break the data collection for this AKS Cluster."
}
```

What is that association good for? I think I took it from some documentation on the topic, without really understanding what this is about.
