### ISSUE TITLE
Not able to upgrade default node pool of AKS cluster using Terraform

### ISSUE THREAD

**Issue by bhuvaneshkrs** [hashicorp/terraform-provider-azurerm#23395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.54.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
I am trying to upgrade the control plane (which includes upgrading Kubernetes version and default node pool orchestration version upgrade) of an existing AKS cluster which is already being managed by Terraform. In this process, only the Kubernetes vresion of the AKS cluster is getting upgraded but as soon as it picks up the default node pool for upgrade, I am getting the following error:
performing CreateOrUpdate: agentpools.AgentPoolsClient#CreateOrUpdate: Failure sending request: StatusCode=0 – Original Error: Code=“CustomKubeletConfigOrCustomLinuxOSConfigCanNotBeChanged” Message="CustomKubeletConfig or CustomLinuxOSConfig can not be changed for this operation.
```

### Debug Output/Panic Output

```shell
2023-09-26T16:38:28.289+0530 [DEBUG] provider.terraform-provider-azurerm_v3.54.0_x5.exe: AzureRM Response for https://management.azure.com/subscriptions/Subscription ID /resourceGroups/Resource group name/providers/Microsoft.ContainerService/managedClusters/AKS Cluster name /agentPools/nodepool?api-version=2023-02-02-preview:
HTTP/2.0 400 Bad Request
```

**Comment by lonegunmanb** [comment]
Hi @bhuvaneshkrs thanks for opening this issue. After our internal communication, I'm going to list the steps you've taken here, please correct me if I'm wrong, thanks in advance.

1. Create an Aks cluster by using ansible, omit `kubeletConfig.failSwapOn`.
2. Try to import this cluster into Terraform state by using `terraform import` command.
3. Change some configs under `kubelet_config` block, e.g.: tags
4. Execute `terraform apply`.

You cannot see the update for `failSwapOn` in the Terraform plan, but when you try to proceed, you saw the following error message:

`Failure sending request: StatusCode=0 – Original Error: Code=“CustomKubeletConfigOrCustomLinuxOSConfigCanNotBeChanged” Message="CustomKubeletConfig or CustomLinuxOSConfig can not be changed for this operation.`

According to https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_cluster_resource.go#L2368-L2369, the provider would call ` ExpandDefaultNodePool` function. Then in this `ExpandDefaultNodePool` function https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_nodepool.go#L1097, it would call ` expandClusterNodePoolKubeletConfig` function, in this function https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_nodepool.go#L1126 ` FailSwapOn` has been hard coded to `false`.

So, in a short conclusion, Terraform would try to update `FailSwapOn` to `false` even you only changed default node pool’s tags, and if the cluster’s FailSwapOn is not `false`, Terraform cannot detect such difference and wouldn’t show this change in the plan, but such change would trigger an error.

I would recommend reading the real kubelet config of this cluster, make sure that FailSwapOn is set to `false`, then try again.

**Comment by bhuvaneshkrs** [comment]
Hi @lonegunmanb , We could able to fix this by adding temporary_name_for_rotation property in default node pool and by changing one of kubelet config, by adding this it recreates the default node pool and while recreating the default node pool FailSwapOn gets injected since its getting provisioned from Terraform with azurerm as provider. This is also helpful to change the certain properties in default node pool without recreating the cluster.

**Comment by lonegunmanb** [comment]
Glad to hear that @bhuvaneshkrs ! I'm not an Aks expert so I just learnt this `temporary_name_for_rotation`, it seems like your cure. Thanks for sharing this knowledge to us so the community could learn how to solve the similar issues in the future!

Would you please close this issue since we have a solution now? Thanks!

**Comment by bhuvaneshkrs** [comment]
Issue resolved by adding temporary_name_for_rotation
