### ISSUE TITLE
Any change on `api_endpoint_authorized_ip_ranges` triggers replacement of AKS cluster resource

### ISSUE THREAD

**Issue by faganihajizada** [hashicorp/terraform-provider-azurerm#23397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.0

### AzureRM Provider Version

v3.74.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#api_server_access_profile


  api_endpoint_authorized_ip_ranges = [
    "10.0.0.0/8",
    ...
  ]
```

When we add a new IP or remove an IP from this list it trigger change in `nat_gateway_profile` and forces replacement on `azurerm_kubernetes_cluster`

```
+ nat_gateway_profile { # forces replacement
              + effective_outbound_ips    = (known after apply)
              + idle_timeout_in_minutes   = 4
              + managed_outbound_ip_count = (known after apply)
            }
```
```


### Debug Output/Panic Output

```shell
# azurerm_kubernetes_cluster.this must be replaced
-/+ resource "azurerm_kubernetes_cluster" "this" {
      ~ api_server_authorized_ip_ranges     = [
          - "10.0.0.0/8",
          - "other IPSs"
        ] -> (known after apply)
```
```


### Expected Behaviour

The list of `api_endpoint_authorized_ip_ranges` should be updated without cluster being re-created.

Azure doc: https://learn.microsoft.com/en-us/azure/aks/api-server-authorized-ip-ranges

### Actual Behaviour

Every time a change in `api_endpoint_authorized_ip_ranges` deletes the cluster and re-creates it

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

**Comment by faganihajizada** [comment]
Update: we removed the `nat_gateway_profile` from our module and now it updates-in-place as expected.

The removed code block:

```
    nat_gateway_profile {
      idle_timeout_in_minutes   = var.cluster_nat_gateway_idle_timeout_in_minutes
      managed_outbound_ip_count = var.cluster_nat_gateway_managed_outbound_ip_count
    }
 ``

Result:

```
  # azurerm_kubernetes_cluster.this will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "this" {
        id                                  = "/subscriptions/[PLACEHOLDER]/resourceGroups/[PLACEHOLDER]/providers/Microsoft.ContainerService/managedClusters/[PLACEHOLDER]"
        name                                = "[PLACEHOLDER]"
        tags                                = {}
        # (30 unchanged attributes hidden)

      ~ api_server_access_profile {
          ~ authorized_ip_ranges     = [
              - "[PLACEHOLDER]",
                # (10 unchanged elements hidden)
            ]
            # (1 unchanged attribute hidden)
        }
        
 ```

**Comment by stephybun** [comment]
Thanks for raising this issue and for providing an update @faganihajizada!

Since your modification to the config has resolved the problem I'm going to close this. If there are still issues please let us know and we can reopen this.
