### ISSUE TITLE
Missing support for disableLocalAuth in in Maps Account

### ISSUE THREAD

**Issue by baximan** [hashicorp/terraform-provider-azurerm#23400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The Maps Account resource (azurerm_maps_account) is missing support for disableLocalAuth. This can currently only be done via Bicep/ARM or AzAPI.

It would be great if the azurerm_maps_account also supported this.

### New or Affected Resource(s)/Data Source(s)

azurerm_maps_account

### Potential Terraform Configuration

```hcl
disableLocalAuth = bool
```

**Comment by rcskosir** [comment]
@baximan Thank you for taking the time to open this feature request!

**Comment by tombuildsstuff** [comment]
hey @baximan 

Support for this field [is available as `local_authentication_enabled`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maps_account#local_authentication_enabled) - would you be able to take a look and see if that works for you?

Thanks!

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @tombuildsstuff‘s response as an answer. If that is not the case, please provide additional information for this feature request, thanks!
