### ISSUE TITLE
MySQL Flexible SKU name validation is improper

### ISSUE THREAD

**Issue by kesavan-rangan** [hashicorp/terraform-provider-azurerm#23427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.13

### AzureRM Provider Version

3.15.1

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```json
{
  "azurerm_mysql_flexible_server": {
    "test-database-kesavanrangan-01": {
      "administrator_login": "sqluser",
      "administrator_password": "",
      "backup_retention_days": 35,
      "geo_redundant_backup_enabled": true,
      "high_availability": {
        "mode": "SameZone"
      },
      "lifecycle": {
        "ignore_changes": [
          "zone",
          "high_availability"
        ],
        "prevent_destroy": "true"
      },
      "location": "westeurope",
      "name": "test-database-kesavanrangan-01",
      "resource_group_name": "test-database",
      "sku_name": "Standard_E2ads_v5",
      "storage": {
        "auto_grow_enabled": true,
        "size_gb": 1000
      },
      "tags": {
        "Owner": "kesavan-rangan"
      },
      "version": "5.7"
    }
  }
}
```

### Debug Output/Panic Output

```shell
sample_test_terraform % terraform plan
╷
│ Error: "sku_name" is not a valid sku name, got Standard_E2ads_v5
│ 
│   with azurerm_mysql_flexible_server.test-database-kesavanrangan-01,
│   on main.tf.json line 22, in resource[0].azurerm_mysql_flexible_server.test-database-kesavanrangan-01:
│   22:                                 "sku_name": "Standard_E2ads_v5",
```

### Expected Behaviour

We should be able to create a MySQL resource without the above-mentioned validation error. 

### Actual Behaviour

The error that is mentioned above when the `terraform plan` is executed. I suspect that this is happening here - https://github.com/hashicorp/terraform-provider-azurerm/blob/aed9b2d3055fea7c6711c1988f6d8259a0b92861/internal/services/mysql/validate/flexible_server_sku_name.go#L15C77-L15C102 where the RegEx needs to be modified.

### Steps to Reproduce

1. Create a main.tf.json file in a directory and paste the above shared JSON file
2. `terraform init`
3. `terraform plan`

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/13678

**Comment by Siddarthyuvaraj** [comment]
@kesavan-rangan your SKU name should always start with the Tier. Eg: Consider you are using General purpose tier, it should start with GP. Since you are using Business Critical pricing tier it should be MO_Standard_E2ads_v5. Please refer the below doc for the same.
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_flexible_server

**Comment by kesavan-rangan** [comment]
@Siddarthyuvaraj It doesn't work with `MO_Standard_E2ads_v5` either. Here's the error:

sample_test_terraform % terraform plan
╷
│ Error: "sku_name" is not a valid sku name, got Standard_E2ads_v5
│ 
│   with azurerm_mysql_flexible_server.test-database-kesavanrangan-01,
│   on main.tf.json line 22, in resource[0].azurerm_mysql_flexible_server.test-database-kesavanrangan-01:
│   22:                                 "sku_name": "MO_Standard_E2ads_v5",

This validation is happening on the client side which needs to be fixed. I believe Azure has changed the way they name their SKUs.

**Comment by OriginalNexus** [comment]
@kesavan-rangan The AMD sku variants were later added to the provider: https://github.com/hashicorp/terraform-provider-azurerm/pull/18816. I think you need to update the provider, in the issue description you mentioned azurerm version 3.15.1, but AMD support was added in 3.28.0.

However an update to https://github.com/hashicorp/terraform-provider-azurerm/blob/7e6fdb49fd54c9c51a0b82c4cd722783c09f88d4/internal/services/mysql/validate/flexible_server_sku_name.go is still needed, as Azure added new server tiers with 20 cores (https://learn.microsoft.com/en-us/azure/mysql/flexible-server/concepts-service-tiers-storage).

The error I get now is `Error: "sku_name" is not a valid sku name, got MO_Standard_E20ds_v5`
Resource name: azurerm_mysql_flexible_server
Terraform version: 3.86.0

The regex should look something like this: 
```regex
^(B|GP|MO)_((Standard_E(2|4|8|16|20|32|48|64|80i)ds_v4)|(Standard_E(2|2a|4|4a|8|8a|16|16a|20|20a|32|32a|48|48a|64|64a|96)ds_v5)|(Standard_B(1|1m|2|2m|4m|8m|12m|16m|20m)s)|(Standard_D(2|4|8|16|32|48|64)ds_v4)|(Standard_D(2|4|8|16|32|48|64)ads_v5))$
```
Verified using online regex: https://regex101.com/r/VFpCTe/1

Can someone make this change? Thanks!
