### ISSUE TITLE
Tainted Storage Accounts Lead to Confusing Errors

### ISSUE THREAD

**Issue by rruenroeng** [hashicorp/terraform-provider-azurerm#23426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.4.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files
Redacted.

### Expected Behaviour

If Terraform thinks they are tainted, it should have the patience to wait until they are destroyed before trying to create them and moving on.

### Actual Behaviour

The resources exist and are unchanged from when Terraform first tried to stand them up, but Terraform has flagged them as tainted. It ends up in an endless cycle deleting and recreating these resources.

### Steps to Reproduce

1. terraform apply with the above setup. Need to have some tainted storage accounts.

### Important Factoids

None

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/10872

**Comment by fardarter** [comment]
I'm not sure it's related, but I'm having issues with Terraform tainting blobs and stating in plan they need replacing but then saying they already exist and need to be imported on apply.

**Comment by asadmahmood-res** [comment]
I am having the exact same issue with a tainted resource too

**Comment by rruenroeng** [comment]
Hi @tombuildsstuff and/or moderators. Could you please remove this post as soon as possible? I'm concerned about the sensitive nature of the history to the post and would like it removed.
