### ISSUE TITLE
Identity Block Support for azurerm_monitor_scheduled_query_rules_alert_v2 

### ISSUE THREAD

**Issue by ASHR4** [hashicorp/terraform-provider-azurerm#23437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Microsoft has added the ability to [Query Azure Resource Graph from Azure Monitor](https://techcommunity.microsoft.com/t5/azure-observability-blog/query-azure-resource-graph-from-azure-monitor/ba-p/3918298)

Utilising this within a azurerm_monitor_scheduled_query_rules_alert_v2 has caused the following error similar to #23248

`The 'adx' pattern cannot be used with the current
│ authentication scheme`

In #23248 they've mentioned a workaround using ARM and adding a system assigned identity resolved this. Can an identity block be added to this resource to support this new functionality required by MS:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/72310905/8013306d-d9ae-4627-93b8-276b77216108)

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2 

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "example" {
  name                = "example-msqrv2"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  + identity {
    + type = SystemAssigned, UserAssigned, SystemAssigned, UserAssigned
    + identity_ids = []
  + }
}
```

### References

https://techcommunity.microsoft.com/t5/azure-observability-blog/query-azure-resource-graph-from-azure-monitor/ba-p/3918298

https://github.com/hashicorp/terraform-provider-azurerm/issues/23248

**Comment by ASHR4** [comment]
Is there any advancements with this?

**Comment by VOVELEE** [comment]
This is also required for Quota alerts.
I have to use AzAPI atm to implement these and would be happy to migrate to azurerm :)

**Comment by ASHR4** [comment]
An update regarding this issue if people are waiting like myself

I attempted to resolve, however, the latest API version the HashiCorp Azure SDK uses was [2021-08-01](https://pkg.go.dev/github.com/hashicorp/go-azure-sdk@v0.20240124.1115501/resource-manager/insights/2021-08-01/scheduledqueryrules#section-readme) which doesn't support managed identities.

The earliest API version that supports managed identities for these alerts is [2022-08-01-preview](https://learn.microsoft.com/en-us/azure/templates/microsoft.insights/2022-08-01-preview/scheduledqueryrules?pivots=deployment-language-arm-template).

Some other [resources](github.com/hashicorp/go-azure-sdk/resource-manager/securityinsights/2022-10-01-preview/alertrules) use preview API versions so I've raised an issue to get this in so I can try and tackle this :)

**Comment by ASHR4** [comment]
I have written the code for this, however there is an issue with ARM when assigning a user assigned identity.

ARM claims the account running Terraform does not have sufficient permissions, this also occurs when building via the Azure portal

**Comment by altruistcoder** [comment]
I am also facing the same problem where I need to attach a system-assigned identity to my alert rule and also a few role assignments to that system-assigned identity but it seems that the resource doesn't provide a way yet to specify a block for defining identity that's going to be attached to the alert rule.

Can anyone please suggest a workaround for it? It would be really helpful.
