### ISSUE TITLE
terraform-provider-azurerm plugin crashes since last week

### ISSUE THREAD

**Issue by frugalpanda** [hashicorp/terraform-provider-azurerm#23447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.35.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
Unable to provide.
```

### Debug Output/Panic Output

```shell
Error: Plugin did not respond

The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4d5725f]

goroutine 211 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/containers.resourceKubernetesClusterRead(0x1bf7cc80, {0x5d6c480, 0x1b586f00})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/containers/kubernetes_cluster_resource.go:2018 +0x96f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1bd2caf0, {0x6d8eaa0, 0x1bb2aca8}, 0x1bf7cc80, {0x5d6c480, 0x1b586f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x166
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0x1bd2caf0, {0x6d8eaa0, 0x1bb2aca8}, 0x1ce83c70, {0x5d6c480, 0x1b586f00})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x547
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0x1b831820, {0x6d8eaa0, 0x1bb2ac48}, 0x1bf551a0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4f4
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0x1ba5d900, {0x6d8eaa0, 0x1bb2a978}, 0x1bf7a510)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/tf5server/server.go:748 +0x4c5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x62caf40, 0x1ba5d900}, {0x6d8eaa0, 0x1bb2a978}, 0x1ba68200, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.1/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x1b7c4120, {0x6d9826c, 0x1c1ab0e0}, 0x1ceac0a0, 0x1c37d2c0, 0xacb04e8, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x1b7c4120, {0x6d9826c, 0x1c1ab0e0}, 0x1ceac0a0, 0x0)
        google.golang.org/grpc@v1.50.1/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.50.1/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.50.1/server.go:963 +0x25f

Error: The terraform-provider-azurerm_v3.35.0_x5.exe plugin crashed!
```

### Expected Behaviour

Upgrade the final aks environment, with the same config as other successful upgrades just 2 weeks before.
System pool is upgraded 1.25.11
Node pools are upgraded to 1.25.11
Upgrade is complete. 
Repeats the process up to 1.27.1

### Actual Behaviour

Updated AKS in multiple environments with same configs over a few weeks.
This week the same was to be done in the final environment and then received the issue above.
Provider crashes with multiple azurerm errors during `terraform plan`.

Does a one time workaround, upgrades with `azure cli` without issues. AKS upgrade to 1.25.11 is complete. 
Upgrading the then done all the way to 1.27.1 (step by step) as that was the final upgrade we did from terraform in the other environments.
Goes back into terraform to fix the issues for future updates.

Runs `terraform plan` and the provider crashes.
Console suggests removing `azurerm_kubernetes_cluster` module from the state so it is done.
Runs `terraform rm {module state}` 
Runs `terraform import {module state} {resourceId}`
Provider crashes as the messages above (can't important external aks anymore).
Runs `terraform plan` again and it works but as expected the AKS is no longer in the state.

A colleague suggested that I should upgrade our provider, as it is quite old.
Upgraded a couple of versions 3.33.0 -> 3.35.0 with `terraform init -upgrade` but still getting the same issue.

Doubt upgrading the provider further will fix the issue as we it worked with the older version just a few weeks ago. Expecting that it is related to recent open source changes made last week. 

Sorry for the bad information, not used to interacting with open source communities.

### Steps to Reproduce

Try repeating the process of what happened under **Actual Behaviour** with the same provider versions.

**Comment by yildizbilal** [comment]
We have the same issue. I was able to upgrade kubernetes on our dev stage without problems. Now i wanted to upgrade the next stage but got the above crash. Any workaround?

**Comment by yildizbilal** [comment]
@frugalpanda try to upgrade the provider to the latest version (current v3.75.0). I've just upgraded it to try what will happen, it doesn't crashed. Related to the changes you have to update the terraform configuration files or migrate a resource again.

**Comment by stephybun** [comment]
@frugalpanda did the suggestion from @yildizbilal work for you?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @yildizbilal‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
