### ISSUE TITLE
Changing the rai_policy_name on azurerm_cognitive_deployment forces replacement, and allows changing to a policy that doesn't exist

### ISSUE THREAD

**Issue by kliseb** [hashicorp/terraform-provider-azurerm#23454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_account" "account" {
  location              = "eastus"
  resource_group_name   = var.rg_name
  name                  = "account-name"
  custom_subdomain_name = "subdomain-name"
  kind                  = "OpenAI"
  sku_name              = "S0"
}


resource "azurerm_cognitive_deployment" "deployment" {
  name                 = "name"
  cognitive_account_id = azurerm_cognitive_account.account.id
  rai_policy_name      = "ContentFilterPolicyThatDoesntExist"

  model {
    format  = "OpenAI"
    name    = "gpt-35-turbo"
    version = "0613"
  }

  scale {
    type     = "Standard"
    capacity = 30
  }
}
```

### Debug Output/Panic Output

```shell
-/+ resource "azurerm_cognitive_deployment" "deployment" {
      ~ id                   = "<deployment-id>" -> (known after apply)
        name                 = "gpt-35-turbo-0613"
      ~ rai_policy_name      = "Microsoft.Default" -> "ContentFilterPolicyThatDoesntExist" # forces replacement
        # (1 unchanged attribute hidden)

        # (2 unchanged blocks hidden)
    }
```

### Expected Behaviour

I would expect that changing the `rai_policy_name` would not force a replacement of the deployment. Also - I'll writeup a bug with azure - I would expect the deployment to fail since the policy does not actually exist.

### Actual Behaviour

The deployment is replaced, and successfully created with a policy that does not exist.

**Comment by kliseb** [comment]
I talked with azure support about the api allowing changing to a policy that doesn't exist, and they've opened an issue with their product team. There is still the issue that changing `rai_policy_name` on `azurerm_cognitive_deployment` resource is forcing replacement though.

**Comment by liuwuliuyun** [comment]
Hi @kliseb , thanks for raising this issue to us. I could help with removing the forceNew tag in `rai_policy_name`. And by my tests, it could be changed without redeployment.
