### ISSUE TITLE
Multi-Subscription support for azurerm_security_center_subscription_pricing

### ISSUE THREAD

**Issue by Joerg-L** [hashicorp/terraform-provider-azurerm#23464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The resource azurerm_security_center_subscription_pricing currently only supports to address a single subscription.

In https://github.com/hashicorp/terraform-provider-azurerm/issues/14755 a workaround was suggested to use multiple provider configurations, one for each subscription.

As the `provider = azurerm.<<Provider Alias>`  can't be passed to a module, this workaround isn't helping to avoid repeating code.
Currently, per subscription, ~100 LoC  are required to enable the Defender for Cloud for a single subscription.

In a Hub & Spoke scenario, following the Cloud Adaption Framework where multiple subscriptions are in place, it's really a mess that, even with terraform, a massiv code duplication has to be done to enable Defender for Cloud for all subscriptions.

The resource azurerm_security_center_automation has a "scope" argument of type list where, **hopefully**, multiple subscriptions are supported. Such an approach would be also good for the azurerm_security_center_subscription_pricing resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_security_center_subscription_pricing

**Comment by nickel-tyler** [comment]
you can pass aliased providers into modules. if you are creating azurerm_security_center_subscription_pricing's for multiple subscriptions in a single terraform root module, then you should use aliased providers.

https://developer.hashicorp.com/terraform/language/modules/develop/providers#provider-aliases-within-modules
https://developer.hashicorp.com/terraform/language/modules/develop/providers#implicit-provider-inheritance
https://developer.hashicorp.com/terraform/language/modules/develop/providers#passing-providers-explicitly

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @nickel-tyler‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
