### ISSUE TITLE
azurerm_api_management' subnet_id change produces changes if case differs

### ISSUE THREAD

**Issue by arkiaconsulting** [hashicorp/terraform-provider-azurerm#23465]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.0

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "main" {
  ............

  virtual_network_type = "Internal"
  virtual_network_configuration {
    subnet_id = azurerm_subnet.apim.id
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_api_management.main will be updated in-place
  ~ resource "azurerm_api_management" "main" {
        id                            = "......"
        name                          = "......"
        # (21 unchanged attributes hidden)

      ~ virtual_network_configuration {
          ~ subnet_id = "/subscriptions/xxx/resourceGroups/resource-group/providers/Microsoft.Network/virtualNetworks/myvnet/subnets/mysubnet" -> "/subscriptions/xxx/resourceGroups/RESOURCE-GROUP/providers/Microsoft.Network/virtualNetworks/MYVNET/subnets/mysubnet"
        }

        # (8 unchanged blocks hidden)
    }
```

### Expected Behaviour

`azurerm_api_management.virtual_network_configuration.subnet_id` should not appear in the changes

### Actual Behaviour

A change is detected because the casing of the resource group and/or the vnet are diferent

### Steps to Reproduce

Each time the terraform apply command is issued, a change is detected on the `subnet_id`

### References

#14831 #18988

**Comment by sinbai** [comment]
Hi @arkiaconsulting thanks for opening this issue. Per [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/18988), it seems that the casing issue has been fixed. Could you provide the actual resource group and the Vnet name(`RESOURCE-GROUP` or `resource-group` and `MYVNET` or `myvnet`)?

**Comment by arkiaconsulting** [comment]
Thank you @sinbai, but I don't see the point to giving the actual names.

 I managed to hardcode the value of the `subnet_id` property in the terraform configuration. Here is what happened:
- resource group lowercased, virtual network uppercased => change
- resource group uppercased, virtual network lowercased => change
- resource group lowercased, virtual network lowercased => no change

That means that the PR is not solving the casing issue, neither for the resource group name or the virtual network name. Which makes sense to me regarding the PR changes.

**Comment by sinbai** [comment]
Thanks for your explanation @arkiaconsulting. However, it is worth mentioning that terraform is case-sensitive for resource names. For [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/18988), it is actually to fix the wrong response of Azure API. However, user input is case-sensitive, and this is by design.

**Comment by mybayern1974** [comment]
@arkiaconsulting , to chime in based on sinbai's comments: 
1. For now terraform expects Azure backend honors users' input casing. Take the 1st of your listed 3 situations as example, >> "_resource group name lowercased, virtual network name uppercased => change detected_", I speculate the service backend changed your `virtual network name uppercased` to `virtual network name lowercased` so drift detected as you filed here. 
3. There could be a plan for this terraform provider to address this discrepancy while AFAIK there is no timeline to implement that yet. As workarounds to unblock, one option is by observing how Azure backend changed your casing first and then make your config value in terraform config align with that backend behavior as your input in your "3rd situation", or another option is to add [ignore_change](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to the target property to ignore those drifts.

**Comment by arkiaconsulting** [comment]
@sinbai @mybayern1974 Thanks for your explanations. What I understand is that this particular endpoint in the APIM Api does not behave as other resource type Api's endpoints.
Now my best bet is to reconstruct the subnet resourceId and lowercase the resource group name and the vnet name. Ignoring changes is not an option.

**Comment by arkiaconsulting** [comment]
For those of you who are interested, here is the workaround:
```hcl
resource "azurerm_api_management" "main" {
  ............

  virtual_network_type = "Internal"
  virtual_network_configuration {
    subnet_id = replace(replace(azurerm_subnet.apim.id, azurerm_subnet.apim.resource_group_name, lower(azurerm_subnet.apim.resource_group_name)), azurerm_subnet.apim.virtual_network_name, lower(azurerm_subnet.apim.virtual_network_name))
  }
}
```
