### ISSUE TITLE
The parameter dns_subscription can only be 'BestPractice' if the the anti_spyware_profile is set to 'BestPractice' as well. 

### ISSUE THREAD

**Issue by amado-pe** [hashicorp/terraform-provider-azurerm#23469]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.69.0

### Affected Resource(s)/Data Source(s)

azurerm_palo_alto_local_rulestack

### Terraform Configuration Files

```hcl
locals {
    # timestring = "${formatdate("YYYYMMDDhhmmss", timestamp())}"
    timestring = "123"
}
resource azurerm_resource_group "rg" {
    name = "${var.resource_prefix}-rg-${local.timestring}"
    location = var.location
    tags = {"userid" = "apena"}
} 

resource azurerm_palo_alto_local_rulestack "lrs" {
    name = "${var.resource_prefix}-lrs-${local.timestring}"
    resource_group_name = azurerm_resource_group.rg.name
    location = var.location
    # anti_spyware_profile = "None"
    dns_subscription = "BestPractice"
}
```

### Debug Output/Panic Output

```shell
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # azurerm_palo_alto_local_rulestack.lrs will be created
  + resource "azurerm_palo_alto_local_rulestack" "lrs" {
      + dns_subscription    = "BestPractice"
      + id                  = (known after apply)
      + location            = "northcentralus"
      + name                = "dummy-lrs-123"
      + resource_group_name = "dummy-rg-123"
    }

  # azurerm_resource_group.rg will be created
  + resource "azurerm_resource_group" "rg" {
      + id       = (known after apply)
      + location = "northcentralus"
      + name     = "dummy-rg-123"
      + tags     = {
          + "userid" = "apena"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
azurerm_resource_group.rg: Creating...
azurerm_resource_group.rg: Creation complete after 2s [id=/subscriptions/e5b40222-1b7a-4534-84fa-23ec5dd5c731/resourceGroups/dummy-rg-123]
azurerm_palo_alto_local_rulestack.lrs: Creating...
azurerm_palo_alto_local_rulestack.lrs: Still creating... [10s elapsed]
azurerm_palo_alto_local_rulestack.lrs: Still creating... [20s elapsed]
azurerm_palo_alto_local_rulestack.lrs: Still creating... [30s elapsed]
azurerm_palo_alto_local_rulestack.lrs: Creation complete after 34s [id=/subscriptions/e5b40222-1b7a-4534-84fa-23ec5dd5c731/resourceGroups/dummy-rg-123/providers/PaloAltoNetworks.Cloudngfw/localRulestacks/dummy-lrs-123]
```

### Expected Behaviour

This execution should failed because dns_subscription cannot be "BestPractice" if anti_spyware_profile is None

Following are the allowed and forbbiten combinations of these to fiels:

anti_spyware_profile:'BestPractice' & dns_subscription:'BestPractice'  --> OK
anti_spyware_profile:'BestPractice' & dns_subscription:'None'  --> OK
anti_spyware_profile:'None' & dns_subscription:'BestPractice'  --> NOK
anti_spyware_profile:'None' & dns_subscription:'None'  --> OK

Therefore, by default, if the customer creates a RS as follows:
        resource azurerm_palo_alto_local_rulestack "dummylrs" {
            name = "dummylrs"
            resource_group_name = azurerm_resource_group.rg.name
            location = var.location
            description = "Dummy lrs"
            anti_spyware_profile = "None"
        }
        The default value for dns_subscription should be 'None'. Otherwise, the it should be 'BestPractice'.

### Actual Behaviour

The actual behavior allows the following:
anti_spyware_profile:'BestPractice' & dns_subscription:'None'
This should fail

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it's by service API design since service API allows this combination. Could you share the document link that explicitly explains that API doesn't allow these combinations? Thanks.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If that is not the case, please provide the additional documentation asked for, thanks!
