### ISSUE TITLE
maximum_capture_duration is unexpected

### ISSUE THREAD

**Issue by op7ic** [hashicorp/terraform-provider-azurerm#23501]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Hi team, 

I noticed that when I use "azurerm_virtual_machine_packet_capture" and attempt to modify default "maximum_capture_duration" parameter I get an error. 

### Terraform Version

1.5.7

### AzureRM Provider Version

3.75

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_packet_capture

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_packet_capture" "xxxx" {
  count                      = length(azurerm_windows_virtual_machine.xxx)
  name                       = "packets-${count.index}-${random_id.xxx[count.index].hex}"
  network_watcher_id         = azurerm_network_watcher.xxxx.id
  virtual_machine_id         = azurerm_windows_virtual_machine.xxx[count.index].id
  maximum_bytes_per_session  = "85899345920"
  maximum_capture_duration   = "7890000"

  storage_location {
    storage_account_id = azurerm_storage_account.xxx.id
  }
}
```

### Debug Output/Panic Output

```shell
│   on main.tf line 1214, in resource "azurerm_virtual_machine_packet_capture" "xxxx":
│ 1214:   maximum_capture_duration   = 7890000
│
│ An argument named "maximum_capture_duration" is not expected here.
```

### Expected Behaviour

maximum_capture_duration should be expected in azurerm_virtual_machine_packet_capture function

**Comment by teowa** [comment]
Hi @op7ic , from [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine_packet_capture#maximum_capture_duration_in_seconds) it should be `maximum_capture_duration_in_seconds`.

Thanks.

**Comment by op7ic** [comment]
hi @teowa I think I missed that - maybe I was browsing different version or something like this. That said, when I changed it to match I also found different issue. Is there no method to capture more than 5h ? 

Error: expected maximum_capture_duration_in_seconds to be in the range (1 - 18000), got 7890000

**Comment by op7ic** [comment]
hi @teowa  thank you - not sure where did I missed that. Closing it now.
