### ISSUE TITLE
Error: Request cancelled The plugin.(*GRPCProvider).ReadResource request was cancelled.

### ISSUE THREAD

**Issue by thalesreisbr** [hashicorp/terraform-provider-azurerm#23512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.49.0 or 3.57.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
Default configuration from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.49.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5479d69]

goroutine 2801 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy.flattenAzureRmVirtualMachineOsProfile(...)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy/virtual_machine_resource.go:1281
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy.resourceVirtualMachineRead(0xc00250ca80, {0x617f780?, 0xc000101000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy/virtual_machine_resource.go:881 +0xd29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x75c41a0?, {0x75c41a0?, 0xc0020313e0?}, 0xd?, {0x617f780?, 0xc000101000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0010bb5e0, {0x75c41a0, 0xc0020313e0}, 0xc00174d5f0, {0x617f780, 0xc000101000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002980f0, {0x75c41a0?, 0xc0020312c0?}, 0xc002e16140)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0006ca780, {0x75c41a0?, 0xc002030cf0?}, 0xc00313bf80)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x68d1600?, 0xc0006ca780}, {0x75c41a0, 0xc002030cf0}, 0xc001cff2d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001de1e0, {0x75d43c0, 0xc001702340}, 0xc0020a2000, 0xc0014ce2d0, 0xbae4d70, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001de1e0, {0x75d43c0, 0xc001702340}, 0xc0020a2000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.49.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Run the terraform plan without any error

### Actual Behaviour

 Error: Request cancelled
│ 
│   with azurerm_virtual_machine.vm-customer["name3"],
│   on vm-customer.tf line 54, in resource "azurerm_virtual_machine" "vm-customer":
│   54: resource "azurerm_virtual_machine" "vm-customer" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with azurerm_virtual_machine.vm-customer["name2"],
│   on vm-customer.tf line 54, in resource "azurerm_virtual_machine" "vm-customer":
│   54: resource "azurerm_virtual_machine" "vm-customer" {
│ 
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
   with azurerm_virtual_machine.vm-customer["name1"],
   on vm-customer.tf line 54, in resource "azurerm_virtual_machine" "vm-customer":
   54: resource "azurerm_virtual_machine" "vm-customer" {
 
 The plugin.(*GRPCProvider).ReadResource request was cancelled.

### Steps to Reproduce

terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/21669

**Comment by wuxu92** [comment]
Hi @thalesreisbr Thanks for filing this issue. The provided link in `Default configuration from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app` does not contain any `azurerm_virtual_machine` resource. And the [panic code](htthttps://github.com/hashicorp/terraform-provider-azurerm/blob/2e393b5045c7e083462e32aa7285ed1aa104b37c/internal/services/legacy/virtual_machine_resource.go#L1283-L1284) of filed `computer_name` is an required field which should not possible to cause a nil value in the response. So could you please share the terraform configuration so I may identify the actual cause of the issue?

https://github.com/hashicorp/terraform-provider-azurerm/blob/2e393b5045c7e083462e32aa7285ed1aa104b37c/internal/services/legacy/virtual_machine_resource.go#L1283-L1284

**Comment by thalesreisbr** [comment]
@wuxu92 sorry I had put the wrong Terraform Configuration Files, but I fix it, 

The problem I think is because not calling flattenAzureRmVirtualMachineOsProfileWindowsConfiguration and I'm setting the os_profile_windows_config, This code were working, I don't know what's happen to it stop working.
