### ISSUE TITLE
Support for dotnet 8.0 and node 20 in linux_function_app and windows_function_app

### ISSUE THREAD

**Issue by Mvanchev** [hashicorp/terraform-provider-azurerm#23528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure has added support for node 20 and dotnet 8 for both linux and windows function apps.
Please add the same support in terraform as currently above values are not accepted by terraforms validation.

Azure Function App Windows supported_stack versions

[
  {
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "4.8"
  },
  {
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "8"
  },
  {
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "7"
  },
  {
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "6"
  },
  {
    "runtime": "dotnet",
    "supported_functions_versions": [
      "4"
    ],
    "version": "6"
  },
  {
    "runtime": "node",
    "supported_functions_versions": [
      "4"
    ],
    "version": "20"
  },
  {
    "runtime": "node",
    "supported_functions_versions": [
      "4"
    ],
    "version": "18"
  },
  {
    "runtime": "node",
    "supported_functions_versions": [
      "4"
    ],
    "version": "16"
  },
  {
    "runtime": "node",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "14"
  },
  {
    "runtime": "java",
    "supported_functions_versions": [
      "4"
    ],
    "version": "17.0"
  },
  {
    "runtime": "java",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "11.0"
  },
  {
    "runtime": "java",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "8.0"
  },
  {
    "runtime": "powershell",
    "supported_functions_versions": [
      "4"
    ],
    "version": "7.2"
  },
  {
    "runtime": "custom",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": ""
  }
]

Azure Function App Linux supported stack versions
[
  {
    "linux_fx_version": "DOTNET-ISOLATED|8.0",
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "8"
  },
  {
    "linux_fx_version": "DOTNET-ISOLATED|7.0",
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "7"
  },
  {
    "linux_fx_version": "DOTNET-ISOLATED|6.0",
    "runtime": "dotnet-isolated",
    "supported_functions_versions": [
      "4"
    ],
    "version": "6"
  },
  {
    "linux_fx_version": "DOTNET|6.0",
    "runtime": "dotnet",
    "supported_functions_versions": [
      "4"
    ],
    "version": "6"
  },
  {
    "linux_fx_version": "Node|20",
    "runtime": "node",
    "supported_functions_versions": [
      "4"
    ],
    "version": "20"
  },
  {
    "linux_fx_version": "Node|18",
    "runtime": "node",
    "supported_functions_versions": [
      "4"
    ],
    "version": "18"
  },
  {
    "linux_fx_version": "Node|16",
    "runtime": "node",
    "supported_functions_versions": [
      "4"
    ],
    "version": "16"
  },
  {
    "linux_fx_version": "Node|14",
    "runtime": "node",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "14"
  },
  {
    "linux_fx_version": "Python|3.11",
    "runtime": "python",
    "supported_functions_versions": [
      "4"
    ],
    "version": "3.11"
  },
  {
    "linux_fx_version": "Python|3.10",
    "runtime": "python",
    "supported_functions_versions": [
      "4"
    ],
    "version": "3.10"
  },
  {
    "linux_fx_version": "Python|3.9",
    "runtime": "python",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "3.9"
  },
  {
    "linux_fx_version": "Python|3.8",
    "runtime": "python",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "3.8"
  },
  {
    "linux_fx_version": "Python|3.7",
    "runtime": "python",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "3.7"
  },
  {
    "linux_fx_version": "Java|17",
    "runtime": "java",
    "supported_functions_versions": [
      "4"
    ],
    "version": "17.0"
  },
  {
    "linux_fx_version": "Java|11",
    "runtime": "java",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "11.0"
  },
  {
    "linux_fx_version": "Java|8",
    "runtime": "java",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": "8.0"
  },
  {
    "linux_fx_version": "PowerShell|7.2",
    "runtime": "powershell",
    "supported_functions_versions": [
      "4"
    ],
    "version": "7.2"
  },
  {
    "linux_fx_version": "",
    "runtime": "custom",
    "supported_functions_versions": [
      "4",
      "3"
    ],
    "version": ""
  }
]

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_function_app azurerm_linux_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app-node"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    node_version = "20"
  }
}

resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app-dotnet"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    dotnet_version = "8.0"
  }
}

resource "azurerm_windows_function_app" "example" {
  name                = "example-windows-function-app-node"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
    node_version = "~20"
   }
}

resource "azurerm_windows_function_app" "example" {
  name                = "example-windows-function-app-dotnet"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
      dotnet_version = "v8.0"
   }
}
```

**Comment by rcskosir** [comment]
@Mvanchev Thank you for taking the time to open this feature request!

**Comment by xiaxyi** [comment]
Thanks @Mvanchev for letting us know about this new feature, it's in our backlog now. I will update the progress here.

**Comment by CihatAcar** [comment]
As the LTS version of the node 20 released yesterday, should we expect the update here soon?

**Comment by heatonhampus** [comment]
What's the status on this?

**Comment by SamuelCox** [comment]
Dotnet 8 releases today, is there an ETA on this?

**Comment by gsmith077** [comment]
Currently unable to test upgrades to dotnet 8 because of this.

Web App Services support dotnet 8:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/33425559/128ba920-933a-49ff-a851-af46c6b7faa9)

👍on the original post

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #23638. As such, I am going to mark this issue as closed.

**Comment by CihatAcar** [comment]
Hi @rcskosir, I think the issue #23638 is only related to dotnet version but this issue is also concerns supporting node version 20. Could you confirm if the node 20 also supported now?

**Comment by rcskosir** [comment]
@CihatAcar Thank you for catching that, PR#23638 is only for dotnet 8.0, I have reopened this issue for the remaining request for supporting node version 20.

**Comment by joakimlemb** [comment]
Any chance to get this into v3.82? 

function apps got dotnet 8 in 3.82, this change should be very similar?

From https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md
azurerm_linux_function_app - add support for dotnet 8 [GH-23638]
azurerm_windows_function_app - add support for dotnet 8 [GH-23638]

**Comment by xiaxyi** [comment]
Hi guys, the node20 and dotnet8 is added in the mentioned PR, you can track the status there. Let me know if there is anything needed.
