### ISSUE TITLE
azurerm_mssql_elasticpool sku family always shown as changed on apply for Gen5

### ISSUE THREAD

**Issue by laurencee** [hashicorp/terraform-provider-azurerm#2353]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.10 
provider.azurerm v1.19.0

### Affected Resource(s)

* azurerm_mssql_elasticpool

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_elasticpool" "default" {
  name                = "myelasticpool"
  resource_group_name = "${azurerm_resource_group.default.name}"
  location            = "${azurerm_resource_group.default.location}"
  server_name         = "${azurerm_sql_server.default.name}"

  sku {
    name     = "BasicPool"
    capacity = 50
    tier     = "Basic"
    family   = "Gen5"
  }

  per_database_settings {
    min_capacity = 0
    max_capacity = 5
  }
}
```
### Expected Behavior

Terraform apply multiple times would not result in any changes appearing

### Actual Behavior

The sku family is always shown as changed because setting "Gen5" is the default and azure is automatically changing the family back to "".  

### Steps to Reproduce

1. `terraform apply`

**Comment by cadamantidis** [comment]
can confirm - to add a bit to this, if you attempt to update the resource via the azure cli to Gen4 or Gen 5 for standard/basic tiers you get:

`az sql elastic-pool update --ids <redacted> --family Gen5`
`Could not find sku in tier 'Standard' with family 'Gen5', capacity 400. Supported families & capacities for 'Standard' are: [(None, 50), (None, 100), (None, 200), (None, 300), (None, 400), (None, 800), (None, 1200), (None, 1600), (None, 2000), (None, 2500), (None, 3000)]. Please specify one of these supported combinations of family and capacity.`

When changing the value of family within the sku block to 'None' terraform plan spits out:
```Error: <redacted>.azurerm_mssql_elasticpool.elasticPool: expected sku.0.family to be one of [Gen4 Gen5], got None```

This implies to me that the value of None or null should be added as an acceptable value when the sku name is one that does not support Generations (I believe this refers specifically to anything that isn't v-core based)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
