### ISSUE TITLE
Support for ContentSafety in azurerm_cognitive_account

### ISSUE THREAD

**Issue by keithswright** [hashicorp/terraform-provider-azurerm#23531]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When creating a new azurerm_cognitive_account resource, we are not able to create "Content Safety" resources because it is not in the allowed values for "kind". 

Error: expected kind to be one of [Academic AnomalyDetector Bing.Autosuggest Bing.Autosuggest.v7 Bing.CustomSearch Bing.Search Bing.Search.v7 Bing.Speech Bing.SpellCheck Bing.SpellCheck.v7 CognitiveServices ComputerVision ContentModerator CustomSpeech CustomVision.Prediction CustomVision.Training Emotion Face FormRecognizer ImmersiveReader LUIS LUIS.Authoring MetricsAdvisor OpenAI Personalizer QnAMaker Recommendations SpeakerRecognition Speech SpeechServices SpeechTranslation TextAnalytics TextTranslation WebLM], got ContentSafety

The deployment template on azure uses a value of 

`"kind": "ContentSafety"`

So I assume it can jus be added to the "find" ValidateFunc in cognitive_account_resource.go

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_account

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_cognitive_account" "example" {
  name                = "example-account"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "ContentSafety"
  sku_name = "S0"
}
```

**Comment by dsczltch** [comment]
Hi, we are also looking for this feature. We are unable to use this service until it's supported by the terraform provider.

**Comment by vagmark30** [comment]
Hey, I am too looking for this feature! Any updates?
