### ISSUE TITLE
AKS api change: it supports now Update http proxy settings for existing clusters

### ISSUE THREAD

**Issue by zioproto** [hashicorp/terraform-provider-azurerm#23550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "cluster" {
  name                                = "test1"
  location                            = local.location
  resource_group_name                 = azurerm_resource_group.aks.name
  
....

  http_proxy_config {
    http_proxy = "http://some-proxy-server:3128/"
    https_proxy = "http://some-proxy-server:3128/"
    no_proxy = [".my-test.xyz"]
  }

}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

It is now possible to update the `http_proxy_config` without creating a new cluster.

### Actual Behaviour

Changing this forces a new resource to be created.

### References

https://github.com/Azure/AKS/issues/3524

https://github.com/MicrosoftDocs/azure-docs/commit/0bb10c7f3b608a541c48f2c1a9bf0574a22a8cd1

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request! Please subscribe to PR #23585 created by @stephybun for this issue.
