### ISSUE TITLE
azurerm_monitor_activity_log_alert has incorrect allowed values for recommendation_category

### ISSUE THREAD

**Issue by PlanetWilson** [hashicorp/terraform-provider-azurerm#23569]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.76

### Affected Resource(s)/Data Source(s)

azurerm_monitor_activity_log_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_activity_log_alert" "ar_sub_advisor_test" {
  description         = ""
  enabled             = true
  name                = "ar-secmon-sub-advisortest"
  resource_group_name = "rg-alerting"
  scopes              = ["/subscriptions/11111111-1111-1111-1111-111111111111"]

  action {
    action_group_id    = azurerm_monitor_action_group.ag_sub_email_1.id
    webhook_properties = {}
  }
  criteria {
    category                = "Recommendation"
    operation_name          = "Microsoft.Advisor/recommendations/available/action"
    recommendation_category = "HighAvailability"
    recommendation_impact   = "High"
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected criteria.0.recommendation_category to be one of ["Cost" "Reliability" "OperationalExcellence" "Performance"], got HighAvailability
│ 
│   with azurerm_monitor_activity_log_alert.ar_sub_advisor_3,
│   on secmon.alerting.tf line 214, in resource "azurerm_monitor_activity_log_alert" "ar_sub_advisor_3":
│  214:     recommendation_category = "HighAvailability"
```

### Expected Behaviour

The alert rule should have been created with a recommendation_category of HighAvailability

### Actual Behaviour

HighAvailability is a valid option for recommendation_category. Reliability is no longer an option if you look in the Azure Portal.

### Steps to Reproduce

terraform apply with a snippet like above

**Comment by teowa** [comment]
Hi @PlanetWilson , from Azure Portal it still looks like this for recommandation category, could you please share where the HighAvailbility comes from?
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/104055472/c19d0620-2dd8-47d6-b929-f5d20aa8b5cc)

**Comment by PlanetWilson** [comment]
Well that is bizarre, this is what I see:- 

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/283116/1c898d23-a821-4cb4-9fbd-8d6c4cb35a1f)
