### ISSUE TITLE
Plan fails for azurerm_dns_txt_record when no record blocks are specified

### ISSUE THREAD

**Issue by WibblyDibbler** [hashicorp/terraform-provider-azurerm#23561]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_dns_txt_record

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_dns_zone" "example" {
  name                = "mydomain.com"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_dns_txt_record" "example" {
  name                = "test"
  zone_name           = azurerm_dns_zone.example.name
  resource_group_name = azurerm_resource_group.example.name
  ttl                 = 300
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Insufficient record blocks
│ 
│   on dns.tf line 11, in resource "azurerm_dns_txt_record" "example":
│   11: resource "azurerm_dns_txt_record" "example" {
│ 
│ At least 1 "record" blocks are required.
╵
```

### Expected Behaviour

A DNS TXT record set should be planned with no records defined.  Creating this is possible through the Azure Portal.

### Actual Behaviour

The plan fails indicating a lack of record blocks.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it's by TF design since TF explicitly declares the record type.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
