### ISSUE TITLE
Error: Request cancelled The plugin.(*GRPCProvider).ReadResource request was cancelled.

### ISSUE THREAD

**Issue by thalesreisbr** [hashicorp/terraform-provider-azurerm#23573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.49.0 or 3.57.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "vm-customer" {
  for_each              = local.customers
  name                  = each.value-vm-name
  resource_group_name   = azurerm_resource_group.rg-spoke.name
  location              = azurerm_resource_group.rg-spoke.location
  network_interface_ids = [azurerm_network_interface.nic-customer[each.key].id]
  vm_size               = "Standard_B2ms"

  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_os_disk {
    name              = "${var.project_name}-osdisk-${each.key}-${var.azure_region_abbreviation}"
    os_type           = "Windows"
    caching           = "ReadWrite"
    create_option     = "Attach"
    managed_disk_type = "Standard_LRS"
    managed_disk_id   = azurerm_managed_disk-root-copy[each.key].id
  }

  os_profile_windows_config {
    enable_automatic_upgrades = false
    timezone                  = "UTC"
  }
  identity {
    type = "SystemAssigned"
  }
  tags = local.common_tags
  lifecycle {
    ignore_changes = [
      tags["CreatedOn"],
      tags["CreatedBy"]
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Stack trace from the terraform-provider-azurerm_v3.49.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5479d69]

goroutine 2801 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy.flattenAzureRmVirtualMachineOsProfile(...)
        github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy/virtual_machine_resource.go:1281
github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy.resourceVirtualMachineRead(0xc00250ca80, {0x617f780?, 0xc000101000})
        github.com/hashicorp/terraform-provider-azurerm/internal/services/legacy/virtual_machine_resource.go:881 +0xd29
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x75c41a0?, {0x75c41a0?, 0xc0020313e0?}, 0xd?, {0x617f780?, 0xc000101000?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc0010bb5e0, {0x75c41a0, 0xc0020313e0}, 0xc00174d5f0, {0x617f780, 0xc000101000})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0002980f0, {0x75c41a0?, 0xc0020312c0?}, 0xc002e16140)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.24.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0006ca780, {0x75c41a0?, 0xc002030cf0?}, 0xc00313bf80)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x68d1600?, 0xc0006ca780}, {0x75c41a0, 0xc002030cf0}, 0xc001cff2d0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001de1e0, {0x75d43c0, 0xc001702340}, 0xc0020a2000, 0xc0014ce2d0, 0xbae4d70, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0001de1e0, {0x75d43c0, 0xc001702340}, 0xc0020a2000, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-azurerm_v3.49.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Run the terraform plan without any error

### Actual Behaviour

Error: Request cancelled
│
│ with azurerm_virtual_machine.vm-customer["name3"],
│ on vm-customer.tf line 54, in resource "azurerm_virtual_machine" "vm-customer":
│ 54: resource "azurerm_virtual_machine" "vm-customer" {
│
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
╷
│ Error: Request cancelled
│
│ with azurerm_virtual_machine.vm-customer["name2"],
│ on vm-customer.tf line 54, in resource "azurerm_virtual_machine" "vm-customer":
│ 54: resource "azurerm_virtual_machine" "vm-customer" {
│
│ The plugin.(*GRPCProvider).ReadResource request was cancelled.
╵
╷
│ Error: Request cancelled
│
with azurerm_virtual_machine.vm-customer["name1"],
on vm-customer.tf line 54, in resource "azurerm_virtual_machine" "vm-customer":
54: resource "azurerm_virtual_machine" "vm-customer" {

The plugin.(*GRPCProvider).ReadResource request was cancelled.

### Steps to Reproduce

terraform plan

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/23512

**Comment by rcskosir** [comment]
@thalesreisbr Thank you for opening this issue. I see in issue #23512 which has a fix #23535 by @wuxu92. To clarify, even with the fix you are still seeing this bug?

**Comment by GAW99** [comment]
I have the same issue AzureRM 3.76.0 provider

**Comment by wuxu92** [comment]
@GAW99 Could you please share the error log of the issue in 3.76.0?

**Comment by thalesreisbr** [comment]
@rcskosir, The fix was about avoid the null pointer in the #23512  when @wuxu92  did #23535  I had put the wrong Terraform Configuration Files, a default and not the one in my code.

The problem is that it is not calling flattenAzureRmVirtualMachineOsProfileWindowsConfiguration because it is calling flattenAzureRmVirtualMachineOsProfile even though I put os_profile_windows_config.

**Comment by wuxu92** [comment]
@GAW99 Thanks for your logs. The error message shows that `strconv.ParseInt(107374182912, 0, 0)` causes an `out-of-range` error. Are you using a 32-bit Windows system?

The error comes from below: 
https://github.com/hashicorp/terraform-provider-azurerm/blob/b12ab79320f8343e7d8e158cfa77f9114a69aeae/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/field_reader.go#L325-L328

**Comment by GAW99** [comment]
Hi @wuxu92 ,

No I have Windows 10 Enterprise x64  
Version	22H2
OS build	19045.3448

I have been working with the terraform everyday, and only one piece of code caused such error. I am bit frustrated.

**Comment by wuxu92** [comment]
@GAW99 Did this error occur today? Have you upgraded Terraform or the provider recently? and could you please share the output of `terraform --version`

**Comment by wuxu92** [comment]
@thalesreisbr The error log provided just shows a null pointer panic. Are there any other error logs? could you please give more information about that `problem is that it is not calling flattenAzureRmVirtualMachineOsProfileWindowsConfiguration because it is calling flattenAzureRmVirtualMachineOsProfile`? As I could not find any connection between this and the problem at hand.

**Comment by thalesreisbr** [comment]
sorry @wuxu92, I tested again and it was solved, thank you.

**Comment by akshaygholap45** [comment]
in my case i was using older provider version. Upgrading it to new one solved the issue.
