### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by TChanel** [hashicorp/terraform-provider-azurerm#23584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure allows users to migrate from Classier Tier Front Door CDN Profile to a Premium Tier Front Door CDN Profile, and in the previous documentation for Classic Tier, you are able to see how to connect your Front Door to the Azure WAF Policy instance through the frontend endpoint with the web_application_firewall_policy_link_id attribute, but there are no similar attributes in the azurerm_cdn_frondoor_custom_domain front door, which is Azure Premium Tier equivalent. The document does not show any attributes to connect the two instances. This is more a documentation request maybe, if the feature is already there, but I haven't been able to see a clear answer on any forums. 

I see how to create both resources, just wasn't sure if I need to make sure we connect them, like previously, or if by creating it, it will automatically apply to the front door.

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_custom_domain, azurerm_cdn_frontdoor_firewall_policy, azurerm_cdn_frontdoor_endpoint

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_firewall_policy
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_endpoint
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_frontdoor_custom_domain

**Comment by WodansSon** [comment]
Hi @TChanel, yes you can still do that in the new CDN Frontdoor resources except it is a different resource. To do that now you must use the [azurerm_cdn_frontdoor_security_policy](https://registry.terraform.io/providers/hashicorp/azurerm/3.71.0/docs/resources/cdn_frontdoor_security_policy) to connect your WAF to the desired frontend endpoint.

**Comment by TChanel** [comment]
I see, an extra resource must now be used, this is what I was looking for, thank you!
