### ISSUE TITLE
Request representation changes detected, and reported applied, but added double quotes are stripped, so changes are not applied.

### ISSUE THREAD

**Issue by humbe76** [hashicorp/terraform-provider-azurerm#23591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api_operation

### Terraform Configuration Files

```hcl
# Setting up an entirely different APIM takes hours. The error looks generic, so just adding relevant parts.

resource "azurerm_api_management_api_operation" "op" {
  operation_id = "post-with-body"
  api_name = "internal-test-api"
  api_management_name = azurerm_api_management.apim.name
  resource_group_name = data.azurerm_resource_group.rg.name
  display_name        = "Post with body"
  method              = "POST"
  url_template        = "/post-with-body"

  request {
    description = each.value.body_description
    representation {
      content {
        content_type = "application/json"
        example {
          name = "example"
          value = "\"Banan\""
        }
      }
    }
  }
```

### Debug Output/Panic Output

```shell
$ terraform plan
...
Terraform will perform the following actions:

  # azurerm_api_management_api_operation.op["Post with body"] will be updated in-place
  ~ resource "azurerm_api_management_api_operation" "op" {
        id                  = "/subscriptions/***/resourceGroups/***/providers/Microsoft.ApiManagement/service/***/apis/internal-test-api/operations/post-with-body"
        # (8 unchanged attributes hidden)

      ~ request {
            # (1 unchanged attribute hidden)

          ~ representation {
                # (1 unchanged attribute hidden)

              ~ example {
                    name  = "example"
                  ~ value = "Banan" -> "\"Banan\""
                }
            }
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.

$ terraform apply "dev.tfplan"
azurerm_api_management_api_operation.op["Post with body"]: Modifying... [id=/subscriptions/***/resourceGroups/***/providers/Microsoft.ApiManagement/service/***/apis/internal-test-api/operations/post-with-body]
azurerm_api_management_api_operation.op["Post with body"]: Modifications complete after 0s [id=/subscriptions/***/resourceGroups/***/providers/Microsoft.ApiManagement/service/***/apis/internal-test-api/operations/post-with-body]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behaviour

I expected the sample body content in the example representation to be updated, as plan suggests it should.

### Actual Behaviour

terraform apply looks like it does the change and reports success, but old value is still active, verified in portal, and plan just suggests the same change over and over again, also detecting the actual value has not changed.

### Steps to Reproduce

terraform plan
terraform apply
terraform plan

**Comment by humbe76** [comment]
Hmm.. It seems to maybe be a more basic issue..

I originally made schema in portal and input'ed invalid json value. Trying to add double quotes in terraform, the double quotes seems to be stripped away at some point..

If I add curly brackets I get:

           ~ example {
                    name  = "example"
                  ~ value = "Banan" -> "{\"Banan\"}"
                }

and then it managed to apply the change..

But I'm unable to input a quoted string into the value as the quotes are stripped somewhere. Without the quotes it is not a legal JSON serialization of a string..

**Comment by humbe76** [comment]
Hmm.. This might be an Azure API management issue more than a terraform module issue.. Seems double quotes are stripped when trying to modify this in the portal too...

**Comment by humbe76** [comment]
If I manually add body sample by going into azure portal, and use form based editor to add sample, double quotes are also stripped there.. But if I manually edit with OpenApi editor, I can add escaped double quotes around the value, so the sample body actually becomes a valid one.. I guess the terraform module use the same functionality that the form based editor use and ends up getting double quotes stripped when applied..

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
