### ISSUE TITLE
Change detected (add slash in a role assignment scope) applied but still same change detected

### ISSUE THREAD

**Issue by llellouc** [hashicorp/terraform-provider-azurerm#23593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

azurerm v3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.76.0"
    }
  }
  required_version = ">= 1.4.0"
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

resource "azurerm_resource_group" "RG" {
  name      = var.RG_name
  location  = var.location
}

resource "azurerm_role_assignment" "ownerRoleForPipelineForRessourcesGroup" {
  principal_id                      = var.RG_Owner
  scope                             = azurerm_resource_group.RG.id
  role_definition_name              = "Owner"
}
```

### Debug Output/Panic Output

```shell
# azurerm_role_assignment.OwnerRole must be replaced
-/+ resource "azurerm_role_assignment" "ownerRoleForPipelineForRessourcesGroup" {
      ~ id                               = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MyRG/providers/Microsoft.Authorization/roleAssignments/yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy" -> (known after apply)
      ~ name                             = "zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz" -> (known after apply)
      ~ principal_type                   = "ServicePrincipal" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/providers/Microsoft.Authorization/roleDefinitions/8e3af657-a8ff-443c-a75c-2fe8c4bcb635" -> (known after apply)
      ~ scope                            = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MyRG" -> "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/MyRG/" # forces replacement
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    }




Full apply log (must search the ressource called "ownerRoleForPipelineForRessourcesGroup") :
https://raw.githubusercontent.com/llellouc/debugTerraform/master/terraform.log
```

### Expected Behaviour

Either the slash at the end of the scope is ignored because it serves no purpose.
Or, Terraform correctly adds the slash at the end.
Either way, since I'm not changing anything in my config file or directly on Azure, this should tell me there's no change.

Tried to modify manually the tfstate file but had the same issue

### Actual Behaviour

I can execute the same config file, 10 times in a row, Terraform will always add/destroy my resource because it detects that it must add a slash ("/") at the end of the scope.

When the issue happen one time, it always happen. But when I execute the same config file on an other environnement (different backend and different variables), the issue happen still happen but on other azurerm_role_assignment. So the issue is not consistant.

### Steps to Reproduce

terraform apply

**Comment by sinbai** [comment]
Hi @llellouc thanks for opening this issue. Unfortunately, I could not reproduce this issue with the following terraform configuration. Could you reproduce it with the configuration below?
```

provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.76.0"
    }
  }
}

resource "azurerm_resource_group" "RG" {
  name     = "example_test"
  location = "eastus"
}

data "azurerm_client_config" "current" {}

resource "azurerm_role_assignment" "ownerRoleForPipelineForRessourcesGroup" {
  principal_id                      = data.azurerm_client_config.current.object_id
  scope                             = azurerm_resource_group.RG.id
  role_definition_name              = "Owner"
}

output "rg_id" {
   value = azurerm_resource_group.RG.id
}

```

**Comment by ceciliasharp** [comment]
Had the same problem but we solved it by the following hack:
`
  scope   = trimsuffix(azurerm_resource_group.RG.id, "/")
`

**Comment by tombuildsstuff** [comment]
@ceciliasharp @llellouc 

In that instance it appears the Resource Group has been imported into Terraform using a slightly different Resource ID - where it has a trailing `/` but shouldn't do.

As such you should be able to fix this by removing and re-importing the Resource Group with the correct Resource ID (e.g. `terraform state rm azurerm_resource_group.RG && terraform import azurerm_resource_group.RG /subscriptions/0000/resourceGroups/abc123`) - can you take a look and see if that fixes this for you?

Thanks!

**Comment by llellouc** [comment]
@ceciliasharp 
Thanks for the tip, it didn't know the `trimsuffix()` method and it could be usefull to me in the futur.

@tombuildsstuff 
Sorry to take so much time to respond to you, I had too much work this week.
I tested your solution and effectively it works. So this issue can be closed.
I would just suggest to add an enhancement in your backlog to prevent this typo to cause an issue, for exemple by removing any trailing `/` during import.

Thanks for your help
