### ISSUE TITLE
Add scan_results_eventgrid_topic_id argument in azurerm_security_center_storage_defender resource

### ISSUE THREAD

**Issue by giacneri** [hashicorp/terraform-provider-azurerm#23607]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Malware scanning in Defender for Storage
Malware scanning, using Microsoft Defender for Storage, can be configured to send scanning results to Event Grid topic. In the current version of azurerm (v3.76.0) we only can enable malware scanning and set the cap gb per month.

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "westus2"
}

resource "azurerm_storage_account" "example" {
  name                     = "exampleacc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_security_center_storage_defender" "example" {
  storage_account_id                          = azurerm_storage_account.example.id
  malware_scanning_on_upload_enabled          = true
  malware_scanning_on_upload_cap_gb_per_month = 5000
  override_subscription_settings_enabled      = false
}
```
### Setting up Event Grid for malware scanning
 In this moment, to configure Event Grid for sending scan results you have to use the Azure Portal or REST API:
## Using Azure Portal
 - Select the storage account
 - Open the Microsoft Defender for Cloud tab and select settings
 - Set a event grid topic
 
[Azure Portal Screenshot](url)
## Using REST API
This configuration can be performed using REST API as well, using _scanResultsEventGridTopicResourceId_ field:

```http
PUT
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Storage/storageAccounts/{accountName}/providers/Microsoft.Security/DefenderForStorageSettings/current?api-version=2022-12-01-preview
```
```http
{ 
    "properties": { 
        "isEnabled": true, 
        "malwareScanning": { 
            "onUpload": { 
                "isEnabled": true, 
                "capGBPerMonth": 5000 
            }, 
            "scanResultsEventGridTopicResourceId": "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.EventGrid/topics/{EventGridTopicName}" 
        }, 
        "sensitiveDataDiscovery": { 
            "isEnabled": true 
        }, 
        "overrideSubscriptionLevelSettings": true 
    } 
}
```

### Feature Request

Add a new supported argument to the azurerm_security_center_storage_defender in order to send scanning results to Event Grid topic:

example:

- `scan_results_eventgrid_topic_id` - (Optional) The ID of the Event Grid topic used by Microsoft Defender for sending scanning results.

### New or Affected Resource(s)/Data Source(s)

azurerm_security_center_storage_defender

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-rg"
  location = "westus2"
}

resource "azurerm_storage_account" "example" {
  name                     = "exampleacc"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_eventgrid_topic" "example" {
  name                   = "exampletopic"
  location               = azurerm_resource_group.example.location
  resource_group_name    = azurerm_resource_group.example.name
}

resource "azurerm_security_center_storage_defender" "example" {
  storage_account_id                          = azurerm_storage_account.example.id
  malware_scanning_on_upload_enabled          = true
  malware_scanning_on_upload_cap_gb_per_month = 5000
  override_subscription_settings_enabled      = false
  scan_results_eventgrid_topic_id            = azurerm_eventgrid_topic.example.id
}
```

**Comment by rcskosir** [comment]
@giacneri Thank you for taking the time to open this feature request!

**Comment by SebastianBalle** [comment]
Would it be possible to extend this feature request with a `scan_results_log_analytics_workspace_id`?
