### ISSUE TITLE
Unable to Modify Invoice Section of Existing Subscription

### ISSUE THREAD

**Issue by jferry-pm** [hashicorp/terraform-provider-azurerm#23606]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_subscription

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_billing_mca_account_scope" "this" {
  billing_account_name = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
  billing_profile_name = "XXXX-XXXX-XXX-XXX"
  invoice_section_name = "KR6T-6SNC-XXX-XXX" # old
# invoice_section_name = "OIPS-MJLQ-XXX-XXX" # new
}

resource "azurerm_subscription" "subscriptions" {
  subscription_name = "TEST_SUBSCRIPTION"
  alias             = "test-sub"
  workload          = "DevTest"
  billing_scope_id  = data.azurerm_billing_mca_account_scope.this.id
}
```

### Debug Output/Panic Output

```shell
refresh produces a provider level WARNING

terraform refresh
2023-10-18T15:57:55.654+0100 [INFO]  Terraform version: 1.5.6
2023-10-18T15:57:55.655+0100 [INFO]  Go runtime version: go1.20.7
2023-10-18T15:57:55.655+0100 [INFO]  CLI args: []string{"C:\\proj\\utils\\terraform.exe", "refresh"}
2023-10-18T15:57:55.658+0100 [INFO]  CLI command args: []string{"refresh"}
2023-10-18T15:57:56.295+0100 [INFO]  provider: configuring client automatic mTLS
2023-10-18T15:57:56.387+0100 [INFO]  provider.terraform-provider-azurerm_v3.76.0_x5.exe: configuring server automatic mTLS: timestamp=2023-10-18T15:57:56.387+0100
2023-10-18T15:57:56.671+0100 [INFO]  provider: configuring client automatic mTLS
2023-10-18T15:57:56.715+0100 [INFO]  provider.terraform-provider-azurerm_v3.76.0_x5.exe: configuring server automatic mTLS: timestamp=2023-10-18T15:57:56.714+0100
2023-10-18T15:57:57.001+0100 [INFO]  provider: configuring client automatic mTLS
2023-10-18T15:57:57.046+0100 [INFO]  provider.terraform-provider-azurerm_v3.76.0_x5.exe: configuring server automatic mTLS: timestamp=2023-10-18T15:57:57.046+0100
2023-10-18T15:57:57.313+0100 [WARN]  ValidateProviderConfig from "provider[\"registry.terraform.io/hashicorp/azurerm\"]" changed the config value, but that value is unused
data.azurerm_billing_mca_account_scope.this: Reading...
data.azurerm_billing_mca_account_scope.this: Read complete after 0s [id=/providers/Microsoft.Billing/billingAccounts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/billingProfiles/XXXX-XXXX-XXX-XXX/invoiceSections/OIPS-MJLQ-XXX-XXX]
azurerm_subscription.subscriptions: Refreshing state... [id=/providers/Microsoft.Subscription/aliases/test-sub]
2023-10-18T15:58:09.684+0100 [WARN]  Provider "registry.terraform.io/hashicorp/azurerm" produced an invalid plan for azurerm_subscription.subscriptions, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .tags: planned value cty.MapValEmpty(cty.String) for a non-computed attribute
2023-10-18T15:58:09.701+0100 [INFO]  backend/local: refresh calling Refresh
```

### Expected Behaviour

After applying the modified invoice section ID, the underlying subscription is successfully updated in-place to reflect this change.

### Actual Behaviour

terraform plan detects an in-place update to the resources invoice sections ID

```
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_subscription.subscriptions will be updated in-place
  ~ resource "azurerm_subscription" "subscriptions" {
      ~ billing_scope_id  = "/providers/Microsoft.Billing/billingAccounts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/billingProfiles/XXXX-XXXX-XXX-XXX/invoiceSections/KR6T-6SNC-XXX-XXX" -> "/providers/Microsoft.Billing/billingAccounts/XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX/billingProfiles/XXXX-XXXX-XXX-XXX/invoiceSections/OIPS-MJLQ-XXX-XXX"
        id                = "/providers/Microsoft.Subscription/aliases/test-sub"
        tags              = {}
        # (5 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

apply shows successful update of resources

```
azurerm_subscription.subscriptions: Modifying... [id=/providers/Microsoft.Subscription/aliases/test-sub]
azurerm_subscription.subscriptions: Modifications complete after 0s [id=/providers/Microsoft.Subscription/aliases/test-sub]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

However the underlying invoice section ID on the referenced subscription is not updated

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/107566766/ae540404-85be-4e16-8361-f1a428399338)

A terraform refresh will show the state matches the remote resources, despite the remote resource not having the updated invoice section ID

### Steps to Reproduce

1. Populate `azurerm_billing_mca_account_scope` data with a valid `billing_account_name`, `billing_profile_name`, and `invoice_section_name`
2. `terraform apply` to build the subscription
3. Create a new `invoice_section_name` and modify the existing `invoice_section_name` that has been already applied
4. `terraform apply` to carry out an in-place update of the resource, confirming that terraform states the `billing_scope_id` will be modified to reflect the new `invoice_section_name`
5. Validate via Azure web console or CLI to confirm that the modifications to the `invoice_section_name` were not applied to the resource

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems you are referring data source azurerm_billing_mca_account_scope in tf config. As the data source is only for read, so it can't update invoice section. Seems TF doesn't support to update invoice section for now.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
