### ISSUE TITLE
The attribute for "Routing Configuration" is missing in the Front Door rule engine resource block

### ISSUE THREAD

**Issue by abbasbaman** [hashicorp/terraform-provider-azurerm#23609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I'm interested in implementing a rule that involves the action 'Routing Configuration.' This particular feature is found within the Front Door component and is part of the Rules Engine.

In the user interface for creating a Rules Engine, you'll notice an 'Add An Action' option, with the last option being 'Routing Configuration.'"

### Terraform Version

1.0.11

### AzureRM Provider Version

2.95.0

### Affected Resource(s)/Data Source(s)

azurerm_frontdoor_rules_engine

### Terraform Configuration Files

```hcl
resource "azurerm_frontdoor_rules_engine" "example_rules_engine" {
  name                = "IPWhiteListingForIAMAuth"
  frontdoor_name      = azurerm_frontdoor.frontdoor.name
  resource_group_name = var.ResourceGroupObject.name

  rule {
    name     = "IPWhiteListing"
    priority = 1
    
    match_condition {
    variable = "RequestURI"
    operator = "Equal"
    value    = ["https://xxxxxx/tech/fr-dev/v1.0/xxxx"]
    transform = "Trim"
  }
    action {
      request_header {
        header_action_type = "Append"
        header_name        = "X-IPWhiteList-Status"
        value              = "False"
      }
       response_header {
        header_action_type = "Append"
        header_name        = "X-IPWhiteLIsting-Version"
        value              = "v1"
      }
    }  

  }
```

### Debug Output/Panic Output

```shell
Error: Unsupported block type
│
│   on ..\..\..\modules\frontdoor\main.tf line 409, in resource "azurerm_frontdoor_rules_engine" "example_rules_engine":
│  409:       override_routing_configuration{
│
│ Blocks of type "override_routing_configuration" are not expected here.
```

### Expected Behaviour

rule {
    name     = "overrideRouteExample"
    priority = 1

    action {
      override_routing_configuration {
        route_type           = "Forward"         # Options "Forward" or "Redirect" -- Required
        backend_pool_name    = "my_backend_pool" # Required
        forwarding_protocol  = "HTTPS"           # Options "HTTPS", "HTTP", or "Match" --  Required
        rewrite_url          = true              # Boolean -- Default false
        caching              = true              # Boolean -- Default false
      }
    }
  }

### Steps to Reproduce

After adding the above resource block just run the "terraform apply"

**Comment by WodansSon** [comment]
Hi @abbasbaman, the Classic Frontdoor is no longer supported per the documentation and is currently in sustained engineering mode (e.g., `This deploys an Azure Front Door (classic) resource which has been deprecated and will receive security updates only.`) Please see [issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/14884) for more details about why this isn't currently supported and will not be supported moving forward.

**Comment by abbasbaman** [comment]
Hi @WodansSon "re there any alternative solutions besides upgrading the Azure Front Door from the classic tier to the standard tier?
