### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by raphaeldeletoille** [hashicorp/terraform-provider-azurerm#23620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

azurerm_monitor_workspace should be able to output the query endpoint url 

It would allow to connect easily on that ressource

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_workspace" "example" {
  name                = "example-mamw"
  resource_group_name = azurerm_resource_group.example.name
  location            = "West Europe"
}

What we would need is :

output "workspace_query_endpoint_url" {
  value = azurerm_monitor_workspace.example.queryendpoint
  description = "Endpoint Query URL of the Azure Monitor Workspace actual value)"
}
```

**Comment by rcskosir** [comment]
@raphaeldeletoille Thank you for taking the time to open this feature request!
