### ISSUE TITLE
Docker-related app_settings are removed when updating site_config or app_settings => unsettling application_stack

### ISSUE THREAD

**Issue by egorshulga** [hashicorp/terraform-provider-azurerm#23632]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_web_app" "app_service" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  service_plan_id     = var.service_plan_id

  app_settings = var.app_settings

  site_config {
    application_stack {
      docker_image_name   = "core/app:latest"
      docker_registry_url = "https://containerregistry.azurecr.io"
    }
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_linux_web_app.app_service will be updated in-place
~ resource "azurerm_linux_web_app" "app_service" {
    id                                = "..."
    name                              = "..."
    tags                              = {}
    # (20 unchanged attributes hidden)

  ~ site_config {
        # (22 unchanged attributes hidden)

      ~ application_stack {
          ~ docker_image_name   = "containerregistry.azurecr.io/core/app:latest" -> "core/app:latest"
          + docker_registry_url = "https://containerregistry.azurecr.io"
        }
    }

    # (2 unchanged blocks hidden)
}
```

### Expected Behaviour

1. `application_stack` settles and does not appear on subsequent runs of `terraform apply`.
2. App settings `DOCKER_REGISTRY_SERVER_URL`, `DOCKER_REGISTRY_SERVER_USERNAME`, `DOCKER_REGISTRY_SERVER_PASSWORD` are present in Azure Portal.

### Actual Behaviour

1. `application_stack` does not settle, it appears in every run of `terraform apply`. It takes time to update it on every run. Besides, it causes conflicts with updates that are implicitly triggered by other resources (e.g., Traffic Manager endpoints).
2. The aforementioned app settings are present and could be seen in Azure Portal.

### Steps to Reproduce

Option 1:
1. Define an `azurerm_linux_web_app` resource. Specify `site_config.application_stack` with `docker_image_name` and `docker_registry_url`. Apply it.
2. Change any property under `site_config` (e.g., `remote_debugging_enabled`). Apply it.
3. Run `terraform apply` once again.

Option 2:
1. Define an `azurerm_linux_web_app` resource. Specify `site_config.application_stack` with `docker_image_name` and `docker_registry_url`. Apply it.
2. Create any new app setting. Apply it.
3. Run `terraform apply` once again.

### References

This behavior was mentioned in comments in the (already closed) #22379.

My research in the code shows that docker-related app settings are wiped-out because of these lines:
1. [linux_web_app_resource.go:766](https://github.com/hashicorp/terraform-provider-azurerm/blob/415dbc0189a48ebecb3d9279fd1e2c554606e1a5/internal/services/appservice/linux_web_app_resource.go#L766C67-L766C67) - there it will call `ExpandForUpdate` when there are changes to `site_config`.
2. [linux_web_app_schema.go:896](https://github.com/hashicorp/terraform-provider-azurerm/blob/dbf1097f896342e4424953a892a96c24d23c4f9a/internal/services/appservice/helpers/linux_web_app_schema.go#L896) - under this condition it will create the docker-related settings, but only when there are changes to `site_config.application_stack`.
3. [linux_web_app_schema.go:951](https://github.com/hashicorp/terraform-provider-azurerm/blob/dbf1097f896342e4424953a892a96c24d23c4f9a/internal/services/appservice/helpers/linux_web_app_schema.go#L951) - there it will unconditionally expand app settings (once again, only when `site_config` is changed - see point 1), **but will not create docker-related settings**.
4. [linux_web_app_resource.go:807](https://github.com/hashicorp/terraform-provider-azurerm/blob/415dbc0189a48ebecb3d9279fd1e2c554606e1a5/internal/services/appservice/linux_web_app_resource.go#L807) - coming back in the stacktrace - there it will expand app settings if they are changed. Once again, docker-related settings will not be created.
5. And the last thing: [linux_web_app_resource.go:612](https://github.com/hashicorp/terraform-provider-azurerm/blob/415dbc0189a48ebecb3d9279fd1e2c554606e1a5/internal/services/appservice/linux_web_app_resource.go#L612) - during read it will try to take docker-related settings, but if it can't find it, then it will take the plain `LinuxFxVersion` and assign it to `docker_image_name`. That is not what we have in our terraform code, thus we see it as a diff.

So, the real problem is that changing `site_config` or `app_settings` deletes docker-related settings. It finally leads to the unsettling `docker_image_name` and `docker_registry_url` - and that's how the bug appears to us.

I am unsure how this issue should be fixed:
1. Either the docker-related settings should always be set when expanding app settings for update.
2. Or the docker-related settings should be completely ignored, instead relying on decoding of the `LinuxFxVersion`.

Let me mention the guys that I've seen in the discussion of the bug: @xiaxyi @jackofallops

**Comment by cleverer** [comment]
To also place this here, to verify there is this reproduction repository: https://github.com/Contactify-AG/terraform-bug-reproduction

@xiaxyi @jackofallops how can we help to get this sorted out quickly? It keeps breaking our infrastructure and is really annoying.
