### ISSUE TITLE
Azurerm_bot_service_azure_bot doesn't support cmk

### ISSUE THREAD

**Issue by rich2099** [hashicorp/terraform-provider-azurerm#23640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

The azure bot module does not support cmk. The original azure registration module does. From what I can tell under issue 12522 the original module is deprecated.

### Terraform Version

1.3.9

### AzureRM Provider Version

3.75.0

### Affected Resource(s)/Data Source(s)

Azurerm_bot_service_azure_bot

### Terraform Configuration Files

```hcl
Na
```

### Debug Output/Panic Output

```shell
Na
```

### Expected Behaviour

The resource should allow the ability to set cmk against the azure bot resource.

### Actual Behaviour

Does not appear to support cmk.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems it has been supported by TF. See more details from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_channels_registration.html#cmk_key_vault_url

**Comment by rich2099** [comment]
Thanks for the response Neil. 

Correct me if wrong, but the bot_channels_restriction module creates the older style resource, the "Bot Channel Registration" resource. According to MSFT, that has been depreciated in favour of the "Azure Bot" resource, although functionally they are the same.

My understanding from https://github.com/hashicorp/terraform-provider-azurerm/issues/12522 is that Azurerm_bot_service_azure_bot replaces azurerm_bot_channels_registration. So it would seem that Azurerm_bot_service_azure_bot should include the CMK functionality.

**Comment by AzySir** [comment]
> Thanks for the response Neil.
> 
> Correct me if wrong, but the bot_channels_restriction module creates the older style resource, the "Bot Channel Registration" resource. According to MSFT, that has been depreciated in favour of the "Azure Bot" resource, although functionally they are the same.
> 
> My understanding from #12522 is that Azurerm_bot_service_azure_bot replaces azurerm_bot_channels_registration. So it would seem that Azurerm_bot_service_azure_bot should include the CMK functionality.

Truly amazing how they release new versions of the resources but cannot seem to common sense migrating in all the existing values isn't it *facepalm*
