### ISSUE TITLE
azure_role_definition scope case insensitivity not caught in plan

### ISSUE THREAD

**Issue by daisy-timms-xlab** [hashicorp/terraform-provider-azurerm#23655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.2

### AzureRM Provider Version

3.73.0

### Affected Resource(s)/Data Source(s)

azurerm_role_definition

### Terraform Configuration Files

```hcl
resource "azurerm_role_definition" "custom_role" {
  name        = "custom_role"

  scope = "/providers/Microsoft.Management/managementgroups/<mg-id>>"
  permissions {
    actions = [
      "Microsoft.Authorization/*/Read"
    ]
    not_actions = []
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_role_definition.packet_capture: Creating...
╷
│ Error: failed to parse scope from Role Definition ID "/providers/Microsoft.Authorization/roleDefinitions/<rd-id>|/providers/Microsoft.Management/managementgroups/<mg-id>"
│ 
│   with azurerm_role_definition.packet_capture,
│   on roles.tf line 1, in resource "azurerm_role_definition" "custom_role":
│    1: resource "azurerm_role_definition" "custom_role" {
│ 
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.
```

### Expected Behaviour

Given a lot of azurerm resources are either case insensitive or raise when the scope is invalid, the terraform plan should have either caught that  `managementgroups` (rather than `managementGroups`) was not a valid scope segment or handled the casing.

### Actual Behaviour

The plan was successful and the custom role was created in azure on terraform apply, however the terraform apply failed on trying to read the resource back in. This meant that subsequent plans were also broken and the custom role definition had to be manually removed.

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23681 created by @wuxu92 for this issue.
