### ISSUE TITLE
Support for Key Vault integration with Container Apps Secrets

### ISSUE THREAD

**Issue by MrImpossibru** [hashicorp/terraform-provider-azurerm#23668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello,

Key Vault integration with Container Apps Secrets is missing. I'd like to see this feature in the upcoming releases. Thanks.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
secret {
  name = ***
  keyvault_url = ***
  identity = *** #"system" or id
}
```

### References

https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=arm-template#reference-secret-from-key-vault

**Comment by davidkarlsen** [comment]
This is a must-have for any enterprise adoption of container apps - any chance of the PR(s) getting merged?
