### ISSUE TITLE
Support for Grafana version as argument in azurerm_dashboard_grafana

### ISSUE THREAD

**Issue by pondichys** [hashicorp/terraform-provider-azurerm#23666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It is currently possible to choose the version of Grafana when deploying an Azure Managed Grafana workspace through the Azure Portal. Possible options are 9 or 10.
The current azurerm_dashboard_grafana resource exposes the grafana_version as an attribute only and not as an argument. This means that we currently cannot deploy version 10 with Terraform.

### New or Affected Resource(s)/Data Source(s)

azurerm_dashboard_grafana

### Potential Terraform Configuration

```hcl
resource "azurerm_dashboard_grafana" "this" {
  name                              = "myGrafana"
  resource_group_name               = "rg-mygrafana"
  location                          = "westeurope"
  grafana_version                   = "10"
}
```

**Comment by ppodevlabs** [comment]
while this get done you can use azapi provider to create and define the version

**Comment by djryanj** [comment]
@pondichys I've just submitted a PR that should add this, except the property is called `grafana_major_version` instead of `grafana_version` since that's what the underlying API wants (`grafana_version` is actually a read-only attribute, where `grafana_major_version` is the one you can set).
