### ISSUE TITLE
Support for [thing]

### ISSUE THREAD

**Issue by williamarobinson** [hashicorp/terraform-provider-azurerm#23673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

azurerm_cost_anomaly_alert needs the ability to be identified by subscription.  Without this, a multi-account strategy would require access and provider at each subscription

### New or Affected Resource(s)/Data Source(s)

azurerm_cost_anomaly_alert

### Potential Terraform Configuration

```hcl
subscription
```

**Comment by williamrobinsonlightstream** [comment]
resource "azurerm_cost_anomaly_alert" "example" {
  name            = "alertname"
  subscription = "subscription ID"
  display_name    = "Alert DisplayName"
  email_subject   = "My Test Anomaly Alert"
  email_addresses = ["example@test.net"]
}

**Comment by rcskosir** [comment]
@williamrobinsonlightstream Thank you for taking the time to open this feature request!
