### ISSUE TITLE
azurerm_eventhub_authorization_rule: Authorization Rule Name Not Found

### ISSUE THREAD

**Issue by tdevopsottawa** [hashicorp/terraform-provider-azurerm#23687]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.0

### AzureRM Provider Version

3.51.0

### Affected Resource(s)/Data Source(s)

data.azurerm_eventhub_authorization_rule

### Terraform Configuration Files

```hcl
data "azurerm_eventhub_authorization_rule" "this" {
  name                = var.eventhub_authorization_rule_name
  namespace_name      = var.eventhub_namespace_name
  eventhub_name       = var.eventhub_name
  resource_group_name = var.eventhub_resource_group
}
```

### Debug Output/Panic Output

```shell
(gist output is thousands of lines long, hundreds of which contain secrets, as this is a huge terraform state, so can't do this part)
```

### Expected Behaviour

Data source should have been created and usable

### Actual Behaviour

│ Error: Eventhub Authorization Rule (Subscription: "<redacted>"
│ Resource Group Name: "<redacted>"
│ Namespace Name: "<redacted>"
│ Eventhub Name: "<redacted>"
│ Authorization Rule Name: "<redacted>") was not found
│
│   with data.azurerm_eventhub_authorization_rule.this,
│   on default.tf line 1, in data "azurerm_eventhub_authorization_rule" "this":
│    1: data "azurerm_eventhub_authorization_rule" "this" {
│

I double and triple checked, the authorization rule I'm trying to reach does exist and the name is perfectly correct, and I'm logged in to an Owner account and everything.

### Steps to Reproduce

terraform apply

**Comment by xiaxyi** [comment]
Thanks @tdevopsottawa for raising this issue, are you able to get the auth rule using the same ID from another endpoint, such as azure cli ([guidance](https://learn.microsoft.com/en-us/cli/azure/eventhubs/eventhub/authorization-rule/keys?view=azure-cli-latest#az-eventhubs-eventhub-authorization-rule-keys-list))?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we’re unable to verify the reported behavior. The ticket will be closed for now, but please open a new one if it occurs again. Be sure to include if you able to get the auth rule using the same ID from another endpoint, such as azure cli ([guidance](https://learn.microsoft.com/en-us/cli/azure/eventhubs/eventhub/authorization-rule/keys?view=azure-cli-latest#az-eventhubs-eventhub-authorization-rule-keys-list)).
