### ISSUE TITLE
azurerm_storage_sync_cloud_endpoint / parsing the CloudEndpoint ID: the segment at position 5 didn't match

### ISSUE THREAD

**Issue by klausgh4836** [hashicorp/terraform-provider-azurerm#23683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_sync_cloud_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "storage" {
  account_replication_type = "LRS"
  account_tier             = "Standard"
  account_kind             = "StorageV2"
  location                 = each.value.region
  resource_group_name      = var.resource_group_name
  allow_nested_items_to_be_public = false
}

resource "azurerm_storage_share" "share" {
  name                 = each.value.file_share_name
  storage_account_name = azurerm_storage_account.storage.name
  quota = 5120
  acl {
    id = "GhostedRecall"
    access_policy {
      permissions = "r"
    }
  }
}

resource "azurerm_storage_sync" "filesync" {
  name                = "test-filesync"
  location            = var.region
  resource_group_name = var.resource_group_name
}

resource "azurerm_storage_sync_group" "group" {
  name            = "test-fsg"
  storage_sync_id = azurerm_storage_sync.filesync.id
}

resource "azurerm_storage_sync_cloud_endpoint" "cloudEndpoint" {
  name                  = "test-fscep"
  storage_sync_group_id = azurerm_storage_sync_group.group.id
  storage_account_id    = azurerm_storage_account.storage.name
  file_share_name       = azurerm_storage_share.share".name
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/12345678910/resourceGroups/yxcvbnm/providers/microsoft.storagesync/storageSyncServices/XXXXX/syncGroups/XXXXXX/cloudEndpoints/XXXXXX": parsing segment "staticMicrosoftStorageSync": parsing the CloudEndpoint ID: the segment at position 5 didn't match
│ 
│ Expected a CloudEndpoint ID that matched:
│ 
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.StorageSync/storageSyncServices/storageSyncServiceValue/syncGroups/syncGroupValue/cloudEndpoints/cloudEndpointValue
│ 
│ However this value was provided:
│ 
│ > /subscriptions/12345678910/resourceGroups/yxcvbnm/providers/microsoft.storagesync/storageSyncServices/XXXXXXX/syncGroups/XXXXXX/cloudEndpoints/XXXXXXXXX
│ 
│ The parsed Resource ID was missing a value for the segment at position 5
│ (which should be the name of the Resource Provider [for example 'Microsoft.StorageSync']).
│
```

### Expected Behaviour

The Resource ID should match lower case and a mix of upper and lower case. 

### Actual Behaviour

May be the Resource ID validating is matching only to 'Microsoft.StorageSync' and not to 'microsoft.storagesync'.

With azurerm version 3.65.0 the terraform apply is working. 
With azurerm version 3.66.0 the apply is not working any more.
May be this has to do with the PR https://github.com/hashicorp/terraform-provider-azurerm/pull/21928 .

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems I can't repro this issue on my local. If it's possible, could you share the repro steps? Thanks.

My steps:
1. Create azurerm_storage_sync_cloud_endpoint using v3.65.0
2. Upgrade version to v3.77.0
3. Run tf plan but I didn't encounter above issue

**Comment by klausgh4836** [comment]
The issue no longer occurs.
