### ISSUE TITLE
azurerm_kusto_cluster name check is not correct

### ISSUE THREAD

**Issue by Shadikho** [hashicorp/terraform-provider-azurerm#23686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_kusto_cluster

### Terraform Configuration Files

```hcl
import {
  id = "id of the existing resource with "-" inside its name"
  to = azurerm_kusto_cluster.kusto_cluster
}
```

### Debug Output/Panic Output

```shell
- Error: "name" must begin with a letter and may only contain alphanumeric characters: "project-nonprod-dx"
```

### Expected Behaviour

The resource code is generated without an error

### Actual Behaviour

The resource code is generated (when adding the -generate-config-out=file.tf in the plan command) but the command throws the following error:

Error: "name" must begin with a letter and may only contain alphanumeric characters: "project-nonprod-dx"

### Steps to Reproduce

1. Create an Azure data Explorer inside Azure Portal and use hyphen inside its name, like "test-kusto-2"
2. Try to import this already existing resource to terraform using import block and generating the code.
3. The error will happen

**Comment by Shadikho** [comment]
Hello all,

isn't there anyone who would like to comment on this issue or pay attention to it at all?! I would highly appreciate any information on whether there is a plan to fix this or not :)

**Comment by ezeeb** [comment]
I have the same problem. The fix should be quite simple: 
the regex in https://github.com/liuwuliuyun/terraform-provider-azurerm/blob/ca0d186d65af0de9291b161fb961854a038f3eb9/internal/services/kusto/validate/name.go#L50 simply needs an additional "-"

**Comment by tombuildsstuff** [comment]
Fixed via https://github.com/hashicorp/terraform-provider-azurerm/pull/23790 - thanks @Dirrbick :)

**Comment by Shadikho** [comment]
Thanks @Dirrbick.
