### ISSUE TITLE
Code snippet in documentation for azure application gateway contains a azurerm_subnet "backend" which is never used

### ISSUE THREAD

**Issue by Makki93** [hashicorp/terraform-provider-azurerm#23702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Code snippet in documentation for azure application gateway contains a azurerm_subnet "backend" which is never used
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_application_gateway

### Terraform Configuration Files

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

**Comment by sinbai** [comment]
Hi @Makki93 thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/23709)has been submitted to fix it.
