### ISSUE TITLE
azurerm_communication_service doesn't support US Gov

### ISSUE THREAD

**Issue by dptaf** [hashicorp/terraform-provider-azurerm#23719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.78.0

### Affected Resource(s)/Data Source(s)

azurerm_communication_service

### Terraform Configuration Files

```hcl
resource "azurerm_communication_service" "email" {
  name                = "email-${var.environment}"
  resource_group_name = "common"
  data_location       = "US Gov"
}
```

### Debug Output/Panic Output

```shell
Error: expected data_location to be one of ["Africa" "Asia Pacific" "Australia" "Brazil" "Canada" "Europe" "France" "Germany" "India" "Japan" "Korea" "Norway" "Switzerland" "UAE" "UK" "United States"], got US Gov
│ 
│   with azurerm_communication_service.email,
│   on email-manager.tf line 46, in resource "azurerm_communication_service" "email":
│   46:   data_location       = "US Gov"
```

### Expected Behaviour

I'd expect that we can pass in US Gov as a value to data_location.

### Actual Behaviour

I'm getting a validation failure on data_location.

**Comment by sinbai** [comment]
Hi @dptaf thanks for opening this issue. Per [Azure Communication Services for US Government](https://learn.microsoft.com/en-us/azure/communication-services/concepts/government) and [Data residency](https://learn.microsoft.com/en-us/azure/communication-services/concepts/privacy#data-residency) documentation, the feature of Azure Communication Services is currently in preview. Not recommended for production workloads. In additional, Terraform generally supports stable API versions, so I assume that `US Gov` could not be supported by Terraform currently.

**Comment by tombuildsstuff** [comment]
@sinbai it's worth noting the API Definitions don't contain the list of Data Locations (which is why this is hard-coded in the Provider, which is where this validation error is coming from) - it's possible that the Service itself is in Preview in the Azure Government environment, whilst using a Stable API version.

I'd suggest we reach out to the Service Team to confirm which API Version this is supported in, and to get [the list of possible values for `dataLocation` added to the API Definition](https://github.com/Azure/azure-rest-api-specs/blob/13ef12f5de907f32bb6cac13123824c48c911411/specification/communication/resource-manager/Microsoft.Communication/stable/2023-04-01/CommunicationServices.json#L756-L763) - since these should be being populated, which'll give us the information we need to support this.

**Comment by jjm123960** [comment]
Same issue here. Any updates on this?

Missed this on first search (closed dupe: https://github.com/hashicorp/terraform-provider-azurerm/issues/27689)

**Comment by MichaelChristopherson** [comment]
@sinbai - Any update on this issue.  Azure Communication Service is publicly available and is functional in us gov.  When I try to create these objects using the `United States` Data location I get the following error:
```
Error: creating Communication Service (Subscription: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
Resource Group Name: "<my-resource-group-name>"
Communication Service Name: "SharedServicesCommunicationService"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidDataLocation: Requested data location unitedstates is not supported. Supported locations: (usgov)

  with azurerm_communication_service.<resource-name>,
  on <my-file-name>.tf line 1, in resource "azurerm_communication_service" "<resource-name>":
   1: resource "azurerm_communication_service" "<resource-name>" {

creating Communication Service (Subscription:
"xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
Resource Group Name: "<my-resource-group-name>"
Communication Service Name: "SharedServicesCommunicationService"):
performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with
error: InvalidDataLocation: Requested data location unitedstates is not
supported. Supported locations: (usgov)
```

Once I update the terraform to use the `usgov` location like this:
```
resource "azurerm_communication_service" "example" {
  name                = "SharedServicesCommunicationService"
  resource_group_name = azurerm_resource_group.example.name
  data_location       = "usgov"
}

resource "azurerm_email_communication_service" "email_example" {
  name                = "SharedServicesEmailCommunicationService"
  resource_group_name = azurerm_resource_group.example.name
  data_location       = "usgov"

  depends_on = [ 
    azurerm_communication_service.example
  ]
}

resource "azurerm_email_communication_service_domain" "example" {
  name             = "example.us"
  email_service_id = azurerm_email_communication_service.email_example.id

  domain_management = "CustomerManaged"
}

resource "azurerm_communication_service_email_domain_association" "example" {
  communication_service_id = azurerm_communication_service.example.id
  email_service_domain_id  = azurerm_email_communication_service_domain.example.id
}
```

I get the following error:
```
Error: expected data_location to be one of ["Africa" "Asia Pacific" "Australia" "Brazil" "Canada" "Europe" "France" "Germany" "India" "Japan" "Korea" "Norway" "Switzerland" "UAE" "UK" "United States"], got usgov

  with azurerm_communication_service.example,
  on <my-file>.tf line 4, in resource "azurerm_communication_service" "example":
   4:   data_location       = "usgov"
```

Ill be adding a PR shortly.
