### ISSUE TITLE
ignore_missing_virtual_network_service_endpoint is listed as optional in documentation, but required by the provider

### ISSUE THREAD

**Issue by wikhede** [hashicorp/terraform-provider-azurerm#23714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

When trying to deploy a azurerm_eventhub_namespace with network_rulesets-object containing a virtual_network_rule the provider tells me that ignore_missing_virtual_network_service_endpoint is required, but the documentations lists it as optional.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.77.0

### Affected Resource(s)/Data Source(s)

azurerm_eventhub_namespace.network_rulesets.virtual_network_rule.ignore_missing_virtual_network_service_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
  capacity            = 2

  network_rulesets {
    default_action                 = "Deny"
    trusted_service_access_enabled = true
    virtual_network_rule = [{
      subnet_id                                       = azurerm_subnet.example.id
    }]
  }  
}
```

### Debug Output/Panic Output

```shell
│ Error: Incorrect attribute value type
│
│   on exempel.tf line 30, in resource "azurerm_eventhub_namespace" "example":
│   30:     virtual_network_rule = [{
│   31:       subnet_id = azurerm_subnet.example.id
│   32:     }]
│
│ Inappropriate value for attribute "virtual_network_rule": element 0: attribute "ignore_missing_virtual_network_service_endpoint" is
│ required.
```

### Expected Behaviour

No error.

### Actual Behaviour

An error.

### Steps to Reproduce

terraform plan

**Comment by jayendranarumugam** [comment]
hi @wikhede , I think you defined the `virtual_network_rule` as array list which gives you the error. Can you define it as a block like below ?

```
resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
  capacity            = 2

  network_rulesets {
    default_action                 = "Deny"
    trusted_service_access_enabled = true
    virtual_network_rule = {
      subnet_id                                       = azurerm_subnet.example.id
    }
  }  
}
```

Let me know if this works for you

**Comment by wuxu92** [comment]
This looks just the same as https://github.com/hashicorp/terraform/issues/28833 .

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is expected behavior, I am going to mark this issue closed.
