### ISSUE TITLE
[vmss] New type of VMSS instances

### ISSUE THREAD

**Issue by ozbillwang** [hashicorp/terraform-provider-azurerm#23723]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In Azure VMSS, it used to be list in its instances, and isolated. So the instances created by VMSS , are not list in Virtual machine. 

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8954908/0c8f7393-5f63-4e33-a2ad-dba3a79241cb)

When I use the resource `azurerm_linux_virtual_machine_scale_set` (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set)  to create the VMSS, the instances can be list in vmss, but can't be seen in Virtual Machine.

Recently, I found when I create VMSS via Azure Portal, the instances created by the new VMSS, type is `VM`, and can be list in Azure Virtual Machine now.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8954908/1b0f1c03-4db2-40c6-b233-6520e7fafd3e)

Could you support this feature?

### New or Affected Resource(s)/Data Source(s)

Resource: azurerm_linux_virtual_machine_scale_set 

### Potential Terraform Configuration

Add a new name, such as `instance_type` , and can be `VM`

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "example" {
  name                = "example-vmss"
  instance_type = "VM"
  ...
}

```

**Comment by ms-zhenhua** [comment]
Hi @ozbillwang, thank you for reaching out.
I do not quite understand your words of _"can be list in Azure Virtual Machine now"_. The second screenshot is still the page of **VMSS instances**, not the page of VM. And for the **Potential Terraform Configuration**, you want to add a new property `instance_type` to create a new VMSS, but VMSS will create VMs automatically, what scenario is this property used for? Could you please explain or elaborate more for this? Thanks.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/76987228/8c0bca64-a7a5-4f47-8a2f-e16b15c1ec8e)

**Comment by ozbillwang** [comment]
@ms-zhenhua 

Sure, let me explain.

I discovered the different setting recently, **not sure if I did something wrong or if a new feature released in Azure recently.** 

One month before, I created VMSS via Azure Portal, or by azure cli commands or Iac Codes, all scale out/in instances created in VMSS are only displayed in VMSS-> instances list

Similar as the first screen shot I posted above. **Please notes, there is no colume called `type`** 

But from last week, I found something different. When create a VMSS, from Azure Portal, the instances can still be displayed in VMSS -> Instances list, but there is a new colume called `type` and its value is `VM`

In the meantime, these instances can be listed in Azure Virtual Machine as well. 

That's in second screen shot I posted avove.

**Comment by ms-zhenhua** [comment]
Hi @ozbillwang, thank you for your clarification.
I found `these instances are also listed in Azure Virtual Machines` happens only when `Orchestration mode` is `Flexible`. You may have a try. However, [current Provider](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine_scale_set#disclaimers) supports `Uniform` only.

**Comment by tombuildsstuff** [comment]
@ms-zhenhua support for this is available in the `azurerm_orchestrated_virtual_machine_scale_set` resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set

**Comment by ms-zhenhua** [comment]
Thanks @tombuildsstuff for correcting me.
Hi @ozbillwang, you may use `azurerm_orchestrated_virtual_machine_scale_set` to create your VMSS and define your VMs explicitly with either `azurerm_linux_virtual_machine` or `azurerm_windows_virtual_machine`. Then the VMs can be seen in both `VMSS.instances` and `Azure VM list`

**Comment by ozbillwang** [comment]
Thanks so much @ms-zhenhua  @tombuildsstuff 

That's explain what I saw. Will have a try.

**Comment by ozbillwang** [comment]
I see . 

**Flexible orchestration mode** is the default mode now when you create VMSS on Azure Portal. Can't remember what's the setting before. 

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8954908/e620e4f7-0496-4656-88ca-0fe4d5eb6d1a)

**Comment by ozbillwang** [comment]
Related to this change, 11th Oct 2023, that matches the exact time I discovered.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/8954908/ae879c9b-cff9-4730-a99e-f373ee2360e6)

ref: https://azure.microsoft.com/en-us/updates/breaking-change-notice-vmss-create-default-orchestration-mode-changing-from-uniform-to-flexible-on-powershell-azure-cli/
