### ISSUE TITLE
Static is not supported by Cassandra tables in Cosmos

### ISSUE THREAD

**Issue by domjv** [hashicorp/terraform-provider-azurerm#23726]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.64.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_cassandra_table

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tflex-cosmosdb-account-rg"
  location = "West Europe"
}

resource "azurerm_cosmosdb_account" "example" {
  name                = "tfex-cosmosdb-account"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  offer_type          = "Standard"

  capabilities {
    name = "EnableCassandra"
  }

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    location          = azurerm_resource_group.example.location
    failover_priority = 0
  }
}

resource "azurerm_cosmosdb_cassandra_keyspace" "example" {
  name                = "tfex-cosmos-cassandra-keyspace"
  resource_group_name = azurerm_cosmosdb_account.example.resource_group_name
  account_name        = azurerm_cosmosdb_account.example.name
  throughput          = 400
}

resource "azurerm_cosmosdb_cassandra_table" "example" {
  name                  = "testtable"
  cassandra_keyspace_id = azurerm_cosmosdb_cassandra_keyspace.example.id

  schema {

    column {
      name = "id"
      type = "uuid"
    }
    column {
      name = "type"
      type = "text"
    }
    column {
      name = "source"
      type = "text"
    }
    column {
      name = "time"
      type = "timestamp"
    }
    column {
      name = "entity"
      type = "text"
    }
    column {
      name = "ownerid"
      type = "uuid"
    }
    column {
      name = "ownertype"
      type = "text"
    }
    column {
      name = "data"
      type = "blob"
    }
    column {
      name = "sequence"
      type = "int"
    }
    column {
      name = "cloudeventview"
      type = "blob static"
    }
    
    column {
      name = "lastupdated"
      type = "timestamp static"
    }
    partition_key {
      name = "ownertype"
    }
    partition_key {
      name = "ownerid"
    }
    cluster_key {
      name     = "sequence"
      order_by = "Desc"
    }
  }
}
```

### Debug Output/Panic Output

```shell
It does not error out. But when I inspect the table structure, it loses the static properties.
```

### Expected Behaviour

The table should be created with `cloudeventview` and `lastupdated` as static. Azure documentation says it is supported:
https://learn.microsoft.com/en-us/azure/cosmos-db/cassandra/support#cql-data-types

### Actual Behaviour

Creates the table without static properties on `cloudeventview` and `lastupdated` fields. 

### Steps to Reproduce

run `terraform apply`
check the table and create the DDL scripts.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. TF doesn't restrict the column data type. So maybe this feature is still in preview or the specified column data type is incorrect. Suggest to file an issue on https://github.com/Azure/azure-rest-api-specs for the usage.

**Comment by domjv** [comment]
> Thanks for raising this issue. TF doesn't restrict the column data type. So maybe this feature is still in preview or the specified column data type is incorrect. Suggest to file an issue on https://github.com/Azure/azure-rest-api-specs for the API usage.

Add the issues here:
https://github.com/Azure/azure-rest-api-specs/issues/26506

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. Thank you for creating the Azure ticket https://github.com/Azure/azure-rest-api-specs/issues/26506. When it gets added, we can reopen this request or you can create a new one.
