### ISSUE TITLE
Automation Account Schedule start time not being set as expected.

### ISSUE THREAD

**Issue by KezHalls** [hashicorp/terraform-provider-azurerm#23725]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.2

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azurerm_automation_schedule

### Terraform Configuration Files

```hcl
now 					= timestamp()
	aus_tz  				= timeadd(local.now, "11h")
	current_time           	= local.aus_tz
	#current_time			= local.now
	current_wallclock_time 	= formatdate("h.mm", local.current_time)
	today                  	= formatdate("YYYY-MM-DD", local.current_time)
	tomorrow               	= formatdate("YYYY-MM-DD", timeadd(local.current_time, "24h"))
	timezone				= "Australia/Sydney"  # Using this timezone to exclude daylight savings times

	start_backups           = "${(local.current_wallclock_time >= "18.30") ? local.tomorrow : local.today}T18:30:00Z"
	start_startaas          = "${(local.current_wallclock_time >= "7.00")  ? local.tomorrow : local.today}T07:00:00Z"
	start_stopaas           = "${(local.current_wallclock_time >= "19.00") ? local.tomorrow : local.today}T19:00:00Z"
 
automation_schedules = {
		"runbook_start_as"				= { schedule_name = "start-as-schedule", description =  "Start service Analysis Services", frequency = "Week", week_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], time_zone = local.timezone, start_time = local.start_startaas },
		"runbook_stop_as"				= { schedule_name = "stop-as-schedule", description =  "Stop service Analysis Services", frequency = "Week", week_days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"], time_zone = local.timezone, start_time = local.start_stopaas },
		"runbook_as_backup_all_databases"= { schedule_name = "as-backup-all-databases", description =  "Backups all Azure Analysis Services databases", frequency = "Day", time_zone = local.timezone, start_time = local.start_backups },
 	}



automation_runbook_schedules = {
		"runbook_as_start_service"		= { runbook_name = "as-start-stop-service", schedule_name =  "start-as-schedule" },
		"runbook_as_stop_service"		= { runbook_name = "as-start-stop-service", schedule_name =  "stop-as-schedule" },
		"runbook_as_backup_all"			= { runbook_name = "as-backup-all", schedule_name =  "as-backup-all-databases" },
	}

resource "azurerm_automation_schedule" "this" {
    for_each                    = local.automation_schedules

    name                        = each.value.schedule_name
    resource_group_name         = var.resource_group_name
    automation_account_name     = var.automation_account_name
    description                 = each.value.description
    frequency                   = each.value.frequency
    timezone                    = each.value.time_zone
    start_time                  = each.value.start_time

    depends_on                  = [azurerm_automation_account.this]
}
```

### Debug Output/Panic Output

```shell
output variables
times = {
  "aus_tz" = "2023-10-27T14:47:24Z"
  "current_time" = "2023-10-27T14:47:24Z"
  "current_wallclock_time" = "14.47"
  "now" = "2023-10-27T03:47:24Z"
  "start_backups" = "2023-10-27T18:30:00Z"
  "start_startaas" = "2023-10-28T07:00:00Z"
  "start_stopaas" = "2023-10-27T19:00:00Z"
  "today" = "2023-10-27"
  "tomorrow" = "2023-10-28"
}
```

### Expected Behaviour

Scheduled times to be allocated as per the output of variable values
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/29215309/4c2256c6-6152-4406-a1b3-cdb9c3c0f7d6)

### Actual Behaviour

See the times are not correct.  I also tried removing my local time zone setup but that did not get the desired result either.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/29215309/f50da8a1-73a2-4571-8883-518a348d03c7)

### Steps to Reproduce

plan and apply the code

### References

no

**Comment by wuxu92** [comment]
Hi @KezHalls Thanks for reporting this. As for `timestamp()` returns a time string with timezone `Z`  and `aus_tz` added 11h to `now` but it does not change the time zone, so `aus_tz` is actually 11 hours after now( not as present as +11 timezone). As the provider will [process the timezone internally](https://github.com/hashicorp/terraform-provider-azurerm/blob/afdbd918f780b54e839a57a80050b735354b9ca6/internal/services/automation/automation_schedule_resource.go#L260), we have to add the right timezone suffix to the `start_time` value. Could you please have a try with below values (change `Z` to the right timezone `+11:00`)

```
  start_backups           = "${(local.current_wallclock_time >= "18.30") ? local.tomorrow : local.today}T18:30:00+11:00"
  start_startaas          = "${(local.current_wallclock_time >= "7.00")  ? local.tomorrow : local.today}T07:00:00+11:00"
  start_stopaas           = "${(local.current_wallclock_time >= "19.00") ? local.tomorrow : local.today}T19:00:00+11:00"
```

It's should wok as your expectation now:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2633022/99ee1b3c-56bf-4392-99fa-781b2641468d)

**Comment by KezHalls** [comment]
thanks for feedback.  that works great.

**Comment by wuxu92** [comment]
@KezHalls Great! Could you please close this issue if it works?
