### ISSUE TITLE
Adjust azurerm_subnet documentation or resource_group_name to virtual_network_resource_group_name

### ISSUE THREAD

**Issue by williamrobinsonlightstream** [hashicorp/terraform-provider-azurerm#23720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In the azurerm_subnet resource, the documentation is incorrect.  The resource group name is meant for the virtual_network, not the subnet.  Documentation would need to be updated.

If possible, the resource value should be changed to virtual_network_resource_group_name so it is appropriately defined.

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
<DOCUMENTATION ONLY CHANGE>
resource_group_name - (Required) The name of the resource group in which the virtual network is located.

<RESOURCE CHANGE>

resource "azurerm_subnet" "example" {
  name                 = "example-subnet"
  virtual_network_resource_group_name  = azurerm_virtual_network.example.resource_group_name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]

  delegation {
    name = "delegation"

    service_delegation {
      name    = "Microsoft.ContainerInstance/containerGroups"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action"]
    }
  }
}
```

**Comment by jayendranarumugam** [comment]
Thank you @williamrobinsonlightstream for the findings I have raised a [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/23722) for this doc update
