### ISSUE TITLE
Support for AKS toggle/disable "run command" feature

### ISSUE THREAD

**Issue by mike-schaefer-dpdhl** [hashicorp/terraform-provider-azurerm#23731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

We're using AKS private clusters to enforce network isolation of the control plane towards the internet. This is our "second line of defense" to protect the cluster from malicious/unauthorized access and is an independent technical concept besides identities and RBAC.
Now, "Run command" allows to execute kubectl commands even if the cluster is a private cluster - it's enabled by default.

Microsoft has implemented a new property on AKS "**apiServerAccessProfile": { "disableRunCommand": true/false }**" to toggle cluster access via "run command".

ARM already has a new property field in the latest template. 
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-07-02-preview/examples/ManagedClustersCreate_DisableRunCommand.json

We'd like to get support from the terraform provider to set/toggle the corresponding property.

Remark: I could already find the new property in
terraform-provider-azurerm/internal/services/containers/kubernetes_cluster_resource.go     and
                                              internal/services/containers/kubernetes_cluster_resource_test.go

![grafik](https://github.com/hashicorp/terraform-provider-azurerm/assets/149396998/0efc54dd-be58-49cb-88f1-0a7aefbfe832)

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by stephybun** [comment]
Thanks for raising this issue @mike-schaefer-dpdhl.

This feature is already available in the AKS resource. The property you're looking for is `run_command_enabled` - this will toggle the run command in the API Server Access Profile.

Since this feature is already available I'm going to go ahead and close this issue.
