### ISSUE TITLE
Support for [Finish adding management group to azurerm_subscription]

### ISSUE THREAD

**Issue by woter1832** [hashicorp/terraform-provider-azurerm#23755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

From digging around in Microsoft's azure-sdk-for-go and your [fork][1], I can see that support for assigning a new subscription to a given management group appears to have been partially implemented.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/68354513/21c4f9b9-8062-4548-82c7-2bbdbfcce5eb)
[Source][2]

```
func resourceSubscriptionCreate(d *pluginsdk.ResourceData, meta interface{}) error {
	aliasClient := meta.(*clients.Client).Subscription.AliasClient
	subscriptionClient := meta.(*clients.Client).Subscription.SubscriptionClient
	client := meta.(*clients.Client).Subscription.Client
	ctx, cancel := timeouts.ForCreate(meta.(*clients.Client).StopContext, d)
	defer cancel()

	//snip

	} else {
		// If we're not assuming control of an existing Subscription, we need to know where to create it.
		req.Properties.DisplayName = utils.String(d.Get("subscription_name").(string))
		req.Properties.BillingScope = utils.String(d.Get("billing_scope_id").(string))
	}

//snip
```

[Source][3]

I'm rubbish at proper programming and know very little about Go and wouldn't know where to start. I'd love to learn it, but don't have the time, and at this point in my career, priorities lay elsewhere, therefore, if anyone with the required knowledge would be able to complete this, I'll be forever grateful.

Many thanks.

[1]: https://github.com/hashicorp/terraform-provider-azurerm/blob/fabb0139ae7a200efe07e1db18aaf4960f11d4d2/internal/services/subscription/subscription_resource.go#L17

[2]: https://pkg.go.dev/github.com/hashicorp/go-azure-sdk/resource-manager/subscription/2021-10-01/subscriptions#PutAliasRequestAdditionalProperties

[3]: https://github.com/hashicorp/terraform-provider-azurerm/blob/fabb0139ae7a200efe07e1db18aaf4960f11d4d2/internal/services/subscription/subscription_resource.go#L207

### New or Affected Resource(s)/Data Source(s)

azurerm_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_subscription" "this" {
  subscription_name   = "my-new-sub"
  alias               = "my-new-sub"
  billing_scope_id    = data.azurerm_billing_enrollment_account_scope.this.id
  management_group_id = "/providers/Microsoft.Management/managementGroups/Default-Sandbox/my-group"
  workload            = var.subscription_workload
  tags                = {purpose = test}
}

# Default-Sandbox is set in the Azure portal as the default location for any new subscription. OTB, this is the Tenant Root Group.
```

### References

Azure REST api: 
https://learn.microsoft.com/en-us/rest/api/subscription/alias/create?view=rest-subscription-2021-10-01&tabs=HTTP#putaliasrequestadditionalproperties

**Comment by ms-zhenhua** [comment]
Hi @woter1832, thank you for reaching out. 
Will you consider using [azurerm_management_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group) to add a subscription into a management group?

**Comment by woter1832** [comment]
Hi @ms-zhenhua ,
Thanks for replying. Unfortunately in this instance, we need this attribute exposed. Unless it doesn't work the way I expect/hope it to. I haven't tested it outside of Terraform. We already use `azurerm_management_group` to create parent and child MGPs.

**Reason:**
Deployment SPN (and my user) does not have write access to the default MGP, and is difficult to get even the `Management Group Contributor` role. We can't change the default MGP as company policy requires all new subscriptions to go into a restricted MGP. I have an exception.

I am sure you'll recognise this diagram:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/68354513/c052f9c9-8fc1-4c51-9c4f-e7258a5f7005)

For us, there are additional MGPs between Tenant Root Group and Contoso and it's one of these additional MGPs that new subscriptions go into. I have full control of Contoso.

I hope this clarifies the situation.

A possible workaround is to use the API directly via `terraform-azapi-resource` where I can specify the MGP ID in `additional properties`, but this means a lot of re-writing and I don't know if this resource maintains state.

**Comment by ms-zhenhua** [comment]
Hi @woter1832, thank you for your clarification. However, according to [this issue](https://github.com/Azure/azure-rest-api-specs/issues/24025#issuecomment-1551475127), seems you still need a `Management Group Contributor` role even if you decide to use `azurerm_subscription` to add a subscription into a management group.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API (https://github.com/Azure/azure-rest-api-specs/issues/24025#issuecomment-1551475127). I am going to label this issue as such and close it for now, if the Azure API changes their behavior, let us know and we can take another look.
