### ISSUE TITLE
Support for azurerm_storage_account shared_access_key_enabled rotation reminder

### ISSUE THREAD

**Issue by mpjtaylor** [hashicorp/terraform-provider-azurerm#23762]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The ability to set a rotation reminder for x days 

Set a reminder to manually rotate your access keys. This simply issues a notification banner indicating that key(s) need to be rotated based on the reminder set. This will not rotate your keys automatically. Your access key will be valid until you choose to manually rotate it.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account 

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "example" {
  name                       = "storageaccountname"
  resource_group_name        = azurerm_resource_group.example.name
  location                   = azurerm_resource_group.example.location
  account_tier               = "Standard"
  account_replication_type   = "GRS"
  shared_access_key_reminder = 12
  tags = {
    environment = "staging"
  }
}
```

**Comment by mpjtaylor** [comment]
checking Microsoft.Storage/storageAccounts@2022-09-01 seems this may not be available

**Comment by magodo** [comment]
@mpjtaylor Could you share the swagger definition of this feature? I've checked the latest version of storage account (i.e. 2023-01-01), and didn't see a potential relative property.

**Comment by rcskosir** [comment]
@mpjtaylor Thanks for taking the time to open this request. I am going to close this for now, based on the information above regarding its availability for us to add it. If it does become available in the future, feel free to ask to reopen, or open a new issue. Thanks!

**Comment by acastor01** [comment]
The rotation reminder is referred to in the MS docs as a “Key Expiration Policy” - [Create a key expiration policy](https://learn.microsoft.com/en-us/azure/storage/common/storage-account-keys-manage?tabs=azure-portal#create-a-key-expiration-policy)

Modifying key rotation policies is exposed in the API via a PATCH request with the properties.keyPolicy attribute - [Storage Accounts - Update - KeyPolicy](https://learn.microsoft.com/en-us/rest/api/storagerp/storage-accounts/update?view=rest-storagerp-2023-01-01&tabs=HTTP#keypolicy)

```
“properties”: {
  “keyPolicy”: {
    “keyExpirationPeriodInDays”: 30
  },
},
```
