### ISSUE TITLE
Support for Regional WAF Default Rule Set 2.1

### ISSUE THREAD

**Issue by gittyNico** [hashicorp/terraform-provider-azurerm#23802]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hi,

DRS 2.1 is now general available for Regional Web Application Firewall Policies.

Could you allow the corresponding configuration in the provider?

Thanks :)

### New or Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Potential Terraform Configuration

```hcl
managed_rule_set {
      type    = "DRS"
      version = "2.1"
}
```

### References

- [Azure GA Notification](https://azure.microsoft.com/en-us/updates/general-availability-default-rule-set-21-for-regional-waf-with-application-gateway/)

- [MS Docs](https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/application-gateway-crs-rulegroups-rules?tabs=drs21#drs-21)

- https://github.com/hashicorp/terraform-provider-azurerm/blob/22ba1063bb1d5a094e513ee3139dbcf5b0aa61d5/internal/services/network/validate/web_application_firewall_policy.go#L40-L52

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23818 created by @wuxu92 for this issue.
