### ISSUE TITLE
Missing attribute `name` in azurerm_automation_account documentation

### ISSUE THREAD

**Issue by gesnaud** [hashicorp/terraform-provider-azurerm#23804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.76

### Affected Resource(s)/Data Source(s)

azurerm_automation_account

### Terraform Configuration Files

```hcl
resource "azurerm_automation_account" "automation_account" {
  for_each             = { for subnet in local.subnets : subnet.subnet_key => subnet }
  name                = "aa-${replace(each.key, "_", "-")}-output-id"
  location            = var.location
  resource_group_name = var.rg_names["network"]
  sku_name            = "Basic"
}

resource "azurerm_automation_variable_string" "automation_account_output_value" {
  for_each             = { for subnet in local.subnets : subnet.subnet_key => subnet }
  name                    = "aa-variable-${replace(each.key,"_","-")}-output-id"
  resource_group_name     = var.rg_names["network"]
  automation_account_name = azurerm_automation_account.automation_account[each.key]
  value                   = var.snet_ids[each.key]
}
```

### Debug Output/Panic Output

```shell
Error: Incorrect attribute value type
│ 
│   on modules/output/main.tf line 24, in resource "azurerm_automation_variable_string" "automation_account_output_value":
│   24:   automation_account_name = azurerm_automation_account.automation_account[each.key]
│     ├────────────────
│     │ azurerm_automation_account.automation_account is object with 2 attributes
│     │ each.key is "aml_pe"
│ 
│ Inappropriate value for attribute "automation_account_name": string required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on modules/output/main.tf line 24, in resource "azurerm_automation_variable_string" "automation_account_output_value":
│   24:   automation_account_name = azurerm_automation_account.automation_account[each.key]
│     ├────────────────
│     │ azurerm_automation_account.automation_account is object with 2 attributes
│     │ each.key is "aml"
│ 
│ Inappropriate value for attribute "automation_account_name": string required.
```

### Expected Behaviour

As documented [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_variable_string), I should use `name` attribute on *azurerm_automation_account.automation_account[each.key]*:

```
resource "azurerm_automation_account" "example" {
  name                = "tfex-example-account"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_variable_string" "example" {
  name                    = "tfex-example-var"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name <==== Here is the good way
  value                   = "Hello, Terraform Basic Test."
}
```
So the documentation of `azurerm_automation_accoun` *MUST* talk about `name` attribute. That's the expected behavior according to me.

### Actual Behaviour

The [documentation ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account)of `azurerm_automation_account` is not refering `name` attribute:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/12083248/946d1a2b-f7c8-4dba-8ed8-c4ca8db08356)

### Steps to Reproduce

terraform plan

**Comment by wuxu92** [comment]
Hi @gesnaud Thanks for filing this issue. As for `name` is a required argument of automation account resource, so the `name` field is presented in the `Argumant Reference` block: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_account#name

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/2633022/bf580d99-d90e-4c40-90b9-3c8491c0b699)

**Comment by gesnaud** [comment]
Hi @wuxu92 !

Thanks for you answer! 
My bad! I always thought  that only the `Attributes reference` were only accessible properties from outside the resource!

I should have never paid enough attention to auto-completion in vscode indeed 😅

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/12083248/88dc9dbb-6a61-40fa-a3ac-21e3e47cddca)

Thanks and have anice day!
This (false) issue can be closed!
