### ISSUE TITLE
azurerm_linux_web_app unable to manage DOCKER_REGISTRY_SERVER_URL without a docker image defined as well

### ISSUE THREAD

**Issue by tullydwyer** [hashicorp/terraform-provider-azurerm#23814]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.75

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Linux"
  sku_name            = "P1v2"
}

resource "azurerm_linux_web_app" "example1" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  app_settings = {
    DOCKER_REGISTRY_SERVER_URL = "https://example.azurecr.io"
  }
}

resource "azurerm_linux_web_app" "example2" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  application_stack {
    docker_registry_url = "https://example.azurecr.io"
  }
}
```

### Debug Output/Panic Output

```shell
No Panic
```

### Expected Behaviour

A common practice is to separate the application deployment (docker image) from the infrastructure deployment (registry, authentication, etc), and we can do this in the portal.

The app setting DOCKER_REGISTRY_SERVER_URL should be able to be set without a docker image defined. As we deploy the docker image from a separate application release pipeline.

### Actual Behaviour

`example1` gives a perpetual diff for `DOCKER_REGISTRY_SERVER_URL`
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7508115/24c67529-17d8-477d-a056-77708a193ded)

`example2` gives `Error: Missing required argument`
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7508115/6ba0687b-79f1-4c2d-9e4b-ec5aa3ecaba5)

### Steps to Reproduce

Copy the example and try to run terraform apply.

**Comment by tullydwyer** [comment]
A workaround:

```terraform
lifecycle {
    ignore_changes = [
      # Managed by null_resource.docker_registry_server_url
      app_settings["DOCKER_REGISTRY_SERVER_URL"]
    ]
  }
```

```terraform
resource "null_resource" "docker_registry_server_url" {
  # If container registry and no container image set docker registry
  for_each = var.container_registry != null && var.container_image == null ? toset(["true"]) : toset([])

  # Changes to registry_fqdn requires re-provisioning
  triggers = {
    registry_fqdn = var.container_registry.registry_fqdn
  }

  provisioner "local-exec" {
    # Set DOCKER_REGISTRY_SERVER_URL using Azure CLI
    command = "az webapp config appsettings set --name ${azurerm_linux_web_app.this.name} --resource-group ${azurerm_linux_web_app.this.resource_group_name} --settings DOCKER_REGISTRY_SERVER_URL=https://${var.container_registry.registry_fqdn}"
  }
}
```

**Comment by xiaxyi** [comment]
Thanks @tullydwyer for raising this issue, the docker setting is supposed to be managed via `application_stack ` under `site_config` instead of `app_setting` directly. If you would like to deploy an "empty" web app the configure the docker related setting later, have you tried to leave the whole site_config as an empty block as:
```
resource "azurerm_linux_web_app" "example2" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {

  }
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @xiaxyi‘s response as an answer. We’re going to close this issue for now, but if you run into issues with the above suggestion, please reach out and we can reopen.
