### ISSUE TITLE
azi to create on-premise gateway connection

### ISSUE THREAD

**Issue by KezHalls** [hashicorp/terraform-provider-azurerm#23815]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.2

### AzureRM Provider Version

3.21.1

### Affected Resource(s)/Data Source(s)

azapi_resource

### Terraform Configuration Files

```hcl
resource "azapi_resource" "this" {
  type = "Microsoft.Web/connectionGateways@2016-06-01"
  name = var.connectionGateways_name
  location = "australiasoutheast"
  parent_id = "/subscriptions/xxxx/resourceGroups/rgtest"
  #tags      = merge(var.tags, tomap(var.tag_description))

  body = jsonencode({
    properties = {
      backendUri = "string"
      connectionGatewayInstallation = {
        #id = "string"
        location = "australiasoutheast"
        name = var.connectionGateways_name
        type = "Microsoft.Web/connectionGateways"
      }
      contactInformation = [
        var.contact_information
      ]
      description = "Data gateway"
      displayName = var.connectionGateways_name
      machineName = var.machineName
    }
    #etag = ""
  })
}
```

### Debug Output/Panic Output

```shell
│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidConnectionGateway
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidConnectionGateway",
│     "message": "The connection gateway installation reference for connection gateway 'cgw-test' is missing."
│   }
│ }
```

### Expected Behaviour

gateway connection was created

### Actual Behaviour

│ --------------------------------------------------------------------------------
│ RESPONSE 400: 400 Bad Request
│ ERROR CODE: InvalidConnectionGateway
│ --------------------------------------------------------------------------------
│ {
│   "error": {
│     "code": "InvalidConnectionGateway",
│     "message": "The connection gateway installation reference for connection gateway 'cgw-xxx' is missing."
│   }
│ }

### Steps to Reproduce

run resource code
plan --> apply

**Comment by mybayern1974** [comment]
@KezHalls Thank you for filing this issue. Given this repo is for Terraform AzureRM provider, please file this issue to the [Terraform AzAPI provider repo](https://github.com/Azure/terraform-provider-azapi/issues). With that I'm closing this issue.
