### ISSUE TITLE
Support for Init containers in Azure Container Apps

### ISSUE THREAD

**Issue by brecht-vermeersch** [hashicorp/terraform-provider-azurerm#23824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

[Init containers are general available. https://azure.microsoft.com/en-us/updates/generally-available-init-containers-in-azure-container-apps/](https://azure.microsoft.com/en-us/updates/generally-available-init-containers-in-azure-container-apps/)

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app" "example" {
  ...

  template {
    ...

    init_container {
      name    = ...
      image   = ...
      cpu     = ...
      memory  = ...
      command = ...
    }
  }
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23955 created by @sakazuki for this issue.

**Comment by sfragata** [comment]
There is another PR 😢 
https://github.com/hashicorp/terraform-provider-azurerm/pull/24132
