### ISSUE TITLE
Typo in example

### ISSUE THREAD

**Issue by ishanslab** [hashicorp/terraform-provider-azurerm#23827]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

example-usage-with-activities have a typo:  
```hcl
resource "azurerm_data_factory_pipeline" "test" {
  name            = "acctest%d"   <---------------- typo
  data_factory_id = azurerm_data_factory.test.id
```

### New or Affected Resource(s)/Data Source(s)

azurerm_data_factory_pipeline

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_pipeline" "test" {
  name            = "acctestId"  
  data_factory_id = azurerm_data_factory.test.id
```

**Comment by sinbai** [comment]
@ishanslab thanks for your feedback. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/23839)has been submitted to fix it.
