### ISSUE TITLE
Data Source: azurerm_subnet can't get id from subnet in different subscription

### ISSUE THREAD

**Issue by rmacian** [hashicorp/terraform-provider-azurerm#23826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.7

### AzureRM Provider Version

3.72.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
data "azurerm_subnet" "deployer" {
  name                = "{{ infra_collection_terraform.deployer.subnet }}"
  resource_group_name = "{{ infra_collection_terraform.deployer.resource_group }}"
  virtual_network_name = "{{ infra_collection_terraform.deployer.vnet }}"
}
```

### Debug Output/Panic Output

```shell
[31m│[0m [0m[1m[31mError: [0m[0m[1mSubnet (Subscription: "xxxxx-xxxx-xxxxx-xxxx"
    [31m│[0m [0mResource Group Name: "Ops_Bastion"
    [31m│[0m [0mVirtual Network Name: "Ops_Bastion-vnet"
    [31m│[0m [0mSubnet Name: "default") was not found[0m
    [31m│[0m [0m
    [31m│[0m [0m[0m  with module.databricks.data.azurerm_subnet.deployer,
    [31m│[0m [0m  on databricks/main.tf line 40, in data "azurerm_subnet" "deployer":
    [31m│[0m [0m  40: data "azurerm_subnet" "deployer" [4m{[0m[0m
    [31m│[0m [0m
    [31m╵[0m[0m
```

### Expected Behaviour

Data should admit to pass a subscription parameter to retrieve subnets like:
```
data "azurerm_subnet" "example" {
  name                 = "backend"
  virtual_network_name = "production"
  resource_group_name  = "networking"
  subscription_id = "xxxx-xxxxx-xxxxx-xxxx"
}
```

### Actual Behaviour

Data module has no subscription parameter and subnet is not found
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/subnet

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. Provider configuration is scoped to a subscription. In order for this datasource configuration to work - create an aliased provider scoped to the subscription in question and pass it using `providers` block.
