### ISSUE TITLE
Support for setting owner of database when using azurerm_postgresql_flexible_server_database

### ISSUE THREAD

**Issue by haveyoumetcp** [hashicorp/terraform-provider-azurerm#23835]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Would like to be able to set the owner of the database via azurerm_postgresql_flexible_server_database.

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_database

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems Azure rest api hasn't supported it yet. Once azure rest api supported it, we could take another look. Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
