### ISSUE TITLE
Support for enable automate DNS Configuration for the VM

### ISSUE THREAD

**Issue by karim20230** [hashicorp/terraform-provider-azurerm#23876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Terraform Version

```shell
Terraform v1.5.7
```

### Description

 There is a challenge in automatically configuring DNS names for virtual machines (VMs) within the Terraform setup.  This feature is crucial for accessibility of the VMs.

### New or Affected Resource(s)/Data Source(s)

azurerm_dns_a_record

### Current Behavior:

Currently, there is no automated way to configure DNS names for VMs, requiring manual intervention post-creation.

### Proposal

We expect a feature that allows for the automatic assignment and configuration of DNS names for VMs during their creation.

### Steps to Reproduce:

Provision a VM using Terraform.
Attempt to automatically configure a DNS name for the VM.

**Comment by ms-zhenhua** [comment]
Hi @karim20230 , thank you for reaching out.
Have you tried [domain_name_label](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/public_ip#domain_name_label) to configure the DNS name?

**Comment by karim20230** [comment]
Hi Thank you domain_name_label works!
