### ISSUE TITLE
Support multiple action groups for azurerm_monitor_metric_alert

### ISSUE THREAD

**Issue by Raymond-Ly** [hashicorp/terraform-provider-azurerm#23882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently `azurerm_monitor_metric_alert` only accepts a single action group. However, it would be great if we could allow more than 1 action group. So that we could alert via email + slack / other service.

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_metric_alert

### Potential Terraform Configuration

Current:

```hcl
  action {
    action_group_id = azurerm_monitor_action_group.emailacgroup.id
  }
```

Proposed:

```hcl
  action {
    action_groups = [
      azurerm_monitor_action_group.emailacgroup.id,
      azurerm_monitor_action_group.slackacgroup.id
    ]
  }
```

**Comment by teowa** [comment]
Hi @Raymond-Ly , thanks for submitting this!
We can set multiple action groups by specifing multiple [`action`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert#action) block, e.g.
```hcl
  action {
    action_group_id = azurerm_monitor_action_group.test1.id
    webhook_properties = {
      from = "terraform"
    }
  }

  action {
    action_group_id = azurerm_monitor_action_group.test2.id
  }
```

**Comment by Raymond-Ly** [comment]
Thanks @teowa
