### ISSUE TITLE
Support setting GPU MIG instance profiles on AKS node pools

### ISSUE THREAD

**Issue by somehowadev** [hashicorp/terraform-provider-azurerm#23880]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It is possible to create GPU node pools in AKS with MIG instance profiles.

It would be ideal if azurerm_kubernetes_cluster_node_pool supported this new property.

If the property is changed, the resource would need to be recreated.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_NC96ads_A100_v4"
  node_count            = 1

  mig_strategy          = "MIG7g"

  tags = {
    Environment = "Production"
  }
}
```

### References

* https://learn.microsoft.com/en-us/rest/api/aks/agent-pools/create-or-update?view=rest-aks-2023-08-01&tabs=HTTP#gpuinstanceprofile-

* https://learn.microsoft.com/en-us/azure/aks/gpu-multi-instance?tabs=azure-cli

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23887 created by @ms-henglu for this issue.
