### ISSUE TITLE
Support for workspace feature in Azure Container Registry(ACR)

### ISSUE THREAD

**Issue by haarchri** [hashicorp/terraform-provider-azurerm#23896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

we want to use workspace for ACR

--workspace
Name or ID of the Log Analytics workspace to send registry diagnostic logs to. All events will be enabled. You can use "az monitor log-analytics workspace create" to create one. Extra billing may apply.

https://learn.microsoft.com/en-us/cli/azure/acr?view=azure-cli-latest

### New or Affected Resource(s)/Data Source(s)

azurerm_container_registry

**Comment by magodo** [comment]
Hi @haarchri, this is actually a helper function provided in the Azure CLI, which after the ACR is created, it will create a diagnostics setting for in the workspace that targets to the ACR. You can do this via `azurerm_monitor_diagnostic_setting`.

Also see the CLI implementation here for the exact settings it used:

https://github.com/Azure/azure-cli/blob/7100fa116950da3c6aa4a8b0a5857ca7de4d820e/src/azure-cli/azure/cli/command_modules/acr/custom.py#L436-L452

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions about the CLI implementation, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
