### ISSUE TITLE
#20228 with redis configuration changes doesn't seem to be fixed

### ISSUE THREAD

**Issue by FireDrunk** [hashicorp/terraform-provider-azurerm#23906]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.80.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "redis" {
  name                = local.resource_name
  location            = var.redis_info.location
  resource_group_name = var.resource_group.name

  // SKU & Capacity
  capacity = var.redis_info.capacity
  family   = var.redis_info.family
  sku_name = var.redis_info.sku_name

  // Configuration
  enable_non_ssl_port = false
  minimum_tls_version = "1.2"
  redis_version       = 6

  // Networking
  public_network_access_enabled = false
  subnet_id                     = data.azurerm_subnet.redis_subnet.id

  tags = merge(var.tags, var.redis_info.tags)


  redis_configuration {
    aof_backup_enabled              = var.redis_info.configuration.aof_backup_enabled
    aof_storage_connection_string_0 = (var.redis_info.configuration.aof_backup_enabled ? var.linked_storage_account.primary_blob_connection_string : null)
    maxmemory_policy                = var.redis_info.configuration.maxmemory_policy
  }

  lifecycle {
    ignore_changes = [
      // This value gets obfuscated by Azure's API to prevent leaking the Storage Account keys.
      // This results in Terraform always detecting this as a change.
      redis_configuration["aof_storage_connection_string_0"]
    ]

    precondition {
      condition     = (var.redis_info.use_private_endpoint == false && var.redis_info.configuration.aof_backup_enabled == true) || (!var.redis_info.configuration.aof_backup_enabled)
      error_message = "When AOF Backup is enabled, using a Private Endpoint is not supported."
    }

    precondition {
      # When AOF Backup is enabled, SKU must be premium
      condition     = (var.redis_info.configuration.aof_backup_enabled && var.redis_info.sku_name == "Premium") || (!var.redis_info.configuration.aof_backup_enabled)
      error_message = "When AOF Backup is enabled, a Premium SKU is required."
    }
  }
}
```

### Debug Output/Panic Output

```shell
# module.router.module.redis["auto-0001"].azurerm_redis_cache.redis has changed
  ~ resource "azurerm_redis_cache" "redis" {
        id                            = "/subscriptions/<snip>/resourceGroups/rg-test-infra/providers/Microsoft.Cache/redis/redis-tst-infra-0001"
        name                          = "redis-tst-infra-0001"
        tags                          = {
            "created_by"    = "terraform"
            "environment"   = "test"
            "system"        = "infra"
            "team"          = "infra"
            "team_friendly" = "Infra"
        }
        # (23 unchanged attributes hidden)

      ~ redis_configuration {
          ~ aof_backup_enabled              = true -> false
            # (10 unchanged attributes hidden)
        }
    }
```

### Expected Behaviour

When enabling AOF backup, and disabling it afterwards, it doesn't get disabled by the Terraform code.
When disabling the AOF backup in the UI, the terraform provider also doesn't detect that it has been disabled, and does nothing. It does detect the above change in the resource, but it accepts it.

The code should disable the AOF backup when told to, and reapply the AOF backup settings when the settings have been changed in the UI.

### Actual Behaviour

Terraform doesn't correctly apply the changes.

### Steps to Reproduce

1:
- Create a redis instance
- enable AOF backup
- disable it in the UI
- run terraform
-> no changes

2:
- Create a redis instance
- enable aof backup
- run terraform
- disable aof backup
- run terraform
-> no changes

### Important Factoids

n/a

### References

n/a

**Comment by sinbai** [comment]
Hi @FireDrunk thanks for opening this issue. Could you please try using ` redis_configuration.0.aof_storage_connection_string_0` instead of in ` redis_configuration["aof_storage_connection_string_0"]` in `ignore_changes`?

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
