### ISSUE TITLE
azurerm_monitor_workspace data source

### ISSUE THREAD

**Issue by kristeey** [hashicorp/terraform-provider-azurerm#23905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Feature request for Azure monitor workspace data source. As far as I know, there is no data source reflecting the terraform resource `azurerm_monitor_workspace`.

### New or Affected Resource(s)/Data Source(s)

data source: azurerm_monitor_workspace

### Potential Terraform Configuration

```hcl
data "azurerm_monitor_workspace" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23928 created by @favoretti for this issue.
