### ISSUE TITLE
Role assignment for azure policy is getting created at each run in terraform

### ISSUE THREAD

**Issue by aravindraj111** [hashicorp/terraform-provider-azurerm#23913]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.7

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

resource "azurerm_role_assignment"

### Terraform Configuration Files

```hcl
resource "azurerm_subscription_policy_assignment" "storageac" { 
  name                 = "Storagepublic" 
  subscription_id      =  "/subscriptions/XXXXXXXXXXX"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/fa298e57-9444-42ba-bf04-86e8470e32c7"
  description          = "Anonymous public read access to containers and blobs in Azure Storage is a convenient way to share data but might present security risks. To prevent data breaches caused by undesired anonymous access, Microsoft recommends preventing public access to a storage account unless your scenario requires it."
  display_name         = "Configure your Storage account public access to be disallowed"
   identity {
    type = "SystemAssigned"
  }
  location = "East US"
}

resource "azurerm_subscription_policy_remediation" "testing" {
  name = "rest"
  subscription_id = "/subscriptions/XXXXXXXXXXXXXX"
  policy_assignment_id = azurerm_subscription_policy_assignment.storageac.id

}

resource "azurerm_role_assignment" "testuserid" {
  scope              = "/subscriptions/XXXXXXXXXXXXX"
  role_definition_id = "/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab"
  principal_id       = azurerm_subscription_policy_assignment.storageac.identity[0].principal_id

}
```

### Debug Output/Panic Output

```shell
Terraform will perform the following actions:

  # azurerm_role_assignment.testuserid must be replaced
+/- resource "azurerm_role_assignment" "testuserid" {
      ~ id                               = "/subscriptions/XXXXXXXXXXXXX/providers/Microsoft.Authorization/roleAssignments/f722d72e-438e-179e-cef0-5bfc1d358e3d" -> (known after apply)
      ~ name                             = "f722d72e-438e-179e-cef0-5bfc1d358e3d" -> (known after apply)
      ~ principal_type                   = "ServicePrincipal" -> (known after apply)
      ~ role_definition_id               = "/subscriptions/XXXXXXXXXXXXXXXXXXX/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab" -> "/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab"
 # forces replacement
      ~ role_definition_name             = "Storage Account Contributor" -> (known after apply)
      + skip_service_principal_aad_check = (known after apply)
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
```

### Expected Behaviour

Should report as no change found while running terraform plan since this policy was already ran via terraform and created the assignment and with the respective role for this subscription

### Actual Behaviour

It keeps replacing the role assignment id everytime it is run

### Steps to Reproduce

Try running terraform plan  twice for assigning the same policy with the role assignment 

### Important Factoids

no

### References

No

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. Are you sure you're using version `3.0.0` of the provider? If so, could you please retry this with a more recent version? (Latest is `3.81.0`)

**Comment by aravindraj111** [comment]
> Hi there and thank you for reporting this. Are you sure you're using version `3.0.0` of the provider? If so, could you please retry this with a more recent version? (Latest is `3.81.0`)

Hello,
         I checked with the updated version but still the result is the same, please find the attached image for reference.
![ver](https://github.com/hashicorp/terraform-provider-azurerm/assets/63192150/a07fde41-faef-46cf-a21d-e11531787911)

**Comment by aravindraj111** [comment]
Issue is fixed by changing the role assignment structure as "/subscriptions/XXXXXXXXXXXXXXXXXXX/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab" since this is being assigned to subscription level the default structure "/providers/Microsoft.Authorization/roleDefinitions/17d1049b-9a84-46fb-8f53-869881c3d3ab"  seems to works only when assigning it as management group level.
