### ISSUE TITLE
azurerm_virtual_hub_connection 404ing on the Hub's resource group if it's in a different subscription

### ISSUE THREAD

**Issue by padeshaies** [hashicorp/terraform-provider-azurerm#23919]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.7

### AzureRM Provider Version

3.80.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_hub_connection

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_hub_connection" "vhub_connection" {
  name                      = "connection1"
  virtual_hub_id            = "/subscriptions/<subscription A>/resourceGroups/<resource group A>/providers/Microsoft.Network/virtualHubs/<virtual hub>"
  remote_virtual_network_id = "/subscriptions/<subscription B>/resourceGroups/<resource group B>/providers/Microsoft.Network/virtualNetworks/<vnet>"
  internet_security_enabled = true
}
```

### Debug Output/Panic Output

```shell
{"@level":"error","@message":"Error: creating Hub Virtual Network Connection: (Name \"connection1\" / Virtual Hub Name \"<virtual hub>\" / Resource Group \"<resource group A>\"): network.HubVirtualNetworkConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code=\"ResourceGroupNotFound\" Message=\"Resource group '<resource group A>' could not be found.\"","@module":"terraform.ui","@timestamp":"2023-11-15T21:20:41.237656Z","diagnostic":{"severity":"error","summary":"creating Hub Virtual Network Connection: (Name \"connection1\" / Virtual Hub Name \"<virtual hub>\" / Resource Group \"<resource group A>\"): network.HubVirtualNetworkConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code=\"ResourceGroupNotFound\" Message=\"Resource group '<resource group A>' could not be found.\"","detail":"","address":"module.network.azurerm_virtual_hub_connection.wan_hub_connection_canadacentral","range":{"filename":"../../../modules/network/resources.tf","start":{"line":44,"column":78,"byte":1416},"end":{"line":44,"column":79,"byte":1417}},"snippet":{"context":"resource \"azurerm_virtual_hub_connection\" \"wan_hub_connection_canadacentral\"","code":"resource \"azurerm_virtual_hub_connection\" \"wan_hub_connection_canadacentral\" {","start_line":44,"highlight_start_offset":77,"highlight_end_offset":78,"values":[]}},"type":"diagnostic"}
Operation failed: failed running terraform apply (exit 1)
```

### Expected Behaviour

I feel like we should be able to link a WAN from another subscriptions in the same tenant as we are able to link other VNets from different subscriptions if the active session has the necessary RBAC access to it (which is has as a Contributor).

### Actual Behaviour

When the active session is set into the B subscription (the VNet's), it fails with the following message:

```
Error: creating Hub Virtual Network Connection: (Name "connection1" / Virtual Hub Name "<virtual hub>" / Resource Group "<resource group A>"): network.HubVirtualNetworkConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group '<resource group A>' could not be found."
``` 

The same behavior as #11497 can be observed. I think that it was supposed to be fixed in a PR, but is there a change we miss?

### References

#11497

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume TF doesn't restrict the subscription since the error is returned by API. Could you check if your service principal has the permission to access two subsscriptions?

**Comment by padeshaies** [comment]
Hi Neil,

We have given the Service Principal Contributor access to the Resource
Group that contains the Virtual WAN. From what I understand, the SP needs
Contributor on the Subscription?

Thanks.

**Comment by padeshaies** [comment]
Hi Neil,

I've tried with the SP as Contributor on the second subscription and it is
still not working.

[image: image.png][image: image.png]

**Comment by tiwood** [comment]
Do you use the correct provider context?

You need to apply this resource with an `azurem provider block` that has the subscription id of  `<subscription A>`

**Comment by padeshaies** [comment]
Switching around the subscriptions did the trick! 👍
