### ISSUE TITLE
Support for essential sku in managed grafana

### ISSUE THREAD

**Issue by warreee** [hashicorp/terraform-provider-azurerm#23920]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The current documentation https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dashboard_grafana states that the only grafana SKU supported with Terraform is `Standard`. Currently there is a new SKU named `essential`, can this be added? 

### New or Affected Resource(s)/Data Source(s)

azurerm_dashboard_grafana

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23934 created by @jiaweitao001 for this issue.
