### ISSUE TITLE
parsing "/subscriptions/***/resourcegroups/testrg/providers/microsoft.operationalinsights/workspaces/workspace": parsing segment "staticResourceGroups": parsing the Workspace ID: the segment at position 2 didn't match

### ISSUE THREAD

**Issue by kumar1708** [hashicorp/terraform-provider-azurerm#23937]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.73.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "law" {
  name                = "law"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.default_tags
}

import {
  to = azurerm_log_analytics_workspace.law
  id = "/subscriptions/****/resourcegroups/rg-01/providers/microsoft.operationalinsights/workspaces/law"
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/***/resourcegroups/rg-01/providers/microsoft.operationalinsights/workspaces/law": parsing segment "staticResourceGroups": parsing the Workspace ID: the segment at position 2 didn't match

> /subscriptions/***/resourceGroups/example-resource-group/providers/Microsoft.OperationalInsights/workspaces/workspaceValue
```

### Expected Behaviour

Import

### Actual Behaviour

Resource ID mismatch in terraform and Azure portal

**Comment by favoretti** [comment]
Hi there and thank you for reporting this. Capitalization of resource ID URLS matters in this case I think.

**Comment by kumar1708** [comment]
> It seems an issue displaying the ID in the Azure Portal. You should copy the ID in the JSON body for import instead of the Resource ID on the left side of the API Versions. You may report feedback to the Azure Portal.
> 
> ![image](https://user-images.githubusercontent.com/2633022/284143728-c785a0b6-3754-4cdc-8aae-405c4df4f684.png)

It worked this way.
Sure I will report it on Azure end

**Comment by favoretti** [comment]
Thank you both. I'm going to close this one then.
