### ISSUE TITLE
Create a Datasource for databricks_access_connector

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#23947]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Would like a Datasource for getting the ID of a databricks_access_connector

### New or Affected Resource(s)/Data Source(s)

azurerm_databricks_access_connector

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request!

**Comment by favoretti** [comment]
@DevopsMercenary I'll work on this one. You wanna fetch connectors created outside of terraform I assume? Cause resource does expose ID attribute.

**Comment by DevopsMercenary** [comment]
Yes, that's correct

**Comment by WilliamWsyHK** [comment]
Just want to check if there is any available date on having the data source for the `databricks_access_connector`?

**Comment by Valatka** [comment]
@favoretti what's the status on this? Can I take over this?

**Comment by favoretti** [comment]
@Valatka feel free to, please. I'm swamped at work atm, sorry about that.
