### ISSUE TITLE
Support for all available Data Collection Rule (DCR) data sources facility_names from Azure portal with terraform

### ISSUE THREAD

**Issue by kijunkang** [hashicorp/terraform-provider-azurerm#23951]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

There seems to be a difference between available facility names from portal and [terraform ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_data_collection_rule#facility_names)
 
|  Portal    | Terraform  |
| -------    | ---------- |
|LOG_ALERT   | ---------- | 
|LOG_AUDIT   | ---------- | 
|LOG_AUTH    |auth        |
|LOG_AUTHPRIV|authpriv    |
|LOG_CLOCK   | ---------- |
|LOG_CRON    |cron        |
|LOG_DAEMON  |daemon      |
|LOG_FTP     | ---------     |
|LOG_KERN    |kern        |
|LOG_LOCAL0  |local0      |
|LOG_LOCAL1  |local1      |
|LOG_LOCAL2  |local2      |
|LOG_LOCAL3  |local3      |
|LOG_LOCAL4  |local4      |
|LOG_LOCAL5  |local5      |
|LOG_LOCAL6  |local6      |
|LOG_LOCAL7  |local7      |
|LOG_LPR     |lpr         |
|LOG_MAIL    |mail        |
|LOG_NEWS    |news        |
|LOG_NOPRI   |LOG_NOPRI   |  
|LOG_NTP     |LOG_NTP     |
|LOG_SYSLOG  |syslog      |
|LOG_USER    |user        |
|LOG_UUCP    |uucp        |
| -----------|mark        |

Would it be possible to deploy facility that are missing from terraform without using [*]? so that way we can control which facility to be enabled. 

### New or Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request!

**Comment by kijunkang** [comment]
Thank you so much for taking time to look into this enhancement request. 
Do you have any time frame when this would get implemented? 

This is not a blocker for us, but we would like to deploy DCR with terraform as we only need to deploy specific facility names that is not being supported currently.

**Comment by teowa** [comment]
Hi @kijunkang , these facilityNames should be supported at `3.87.0` or later version after PR https://github.com/hashicorp/terraform-provider-azurerm/pull/24453 updating the `vendor/github.com/hashicorp/go-azure-sdk/resource-manager/insights/2022-06-01/datacollectionrules/constants.go` file

**Comment by kijunkang** [comment]
Thank you so much @teowa

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #24453. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
