### ISSUE TITLE
docs: missing default for `https_only` in azurerm_windows_function_app_slot and azurerm_linux_function_app_slot

### ISSUE THREAD

**Issue by tal66** [hashicorp/terraform-provider-azurerm#23953]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6

### AzureRM Provider Version

3.81.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app_slot, azurerm_windows_function_app_slot

### Terraform Configuration Files

```hcl
{}
```

### Debug Output/Panic Output

```shell
{}
```

### Expected Behaviour

docs should mention the default

### Actual Behaviour

The docs don't mention the default (false) for `https_only` in: azurerm_linux_function_app_slot, azurerm_windows_function_app_slot.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app_slot#https_only
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app_slot#https_only

[linux_function_app_slot](https://github.com/hashicorp/terraform-provider-azurerm/blob/ed9565a1ea594edac824b869c7bffff1e40a3a5e/internal/services/appservice/linux_function_app_slot_resource.go#L235-L240)
[windows_function_app_slot](https://github.com/hashicorp/terraform-provider-azurerm/blob/ed9565a1ea594edac824b869c7bffff1e40a3a5e/internal/services/appservice/windows_function_app_slot_resource.go#L236-L241)

Can I fix it in a PR [here ](https://github.com/hashicorp/terraform-provider-azurerm/blob/ed9565a1ea594edac824b869c7bffff1e40a3a5e/website/docs/r/linux_function_app_slot.html.markdown?plain=1#L101)and [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/ed9565a1ea594edac824b869c7bffff1e40a3a5e/website/docs/r/windows_function_app_slot.html.markdown?plain=1#L100)?

**Comment by xiaxyi** [comment]
Thanks @tal66 for raising this issue, the fix is in the mentioned PR.
