### ISSUE TITLE
Support for image resource id in the azurerm_image resource

### ISSUE THREAD

**Issue by mjneuharth** [hashicorp/terraform-provider-azurerm#23952]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

My use case:
1. Packer creates a Windows Virtual machine image (/subscriptions/<subscription>/resourceGroups/<resource group>/providers/Microsoft.Compute/images/<image name>)
2. Currently we reference that above image (azurerm_image data source) when creating a VM in a new resource group
3. We aim to move/copy the above image into the a resource group when deploying the resources that use the image

Attempts to use the `azurerm_image` resource currently have not worked as the resource can only reference:
1. source_virtual_machine_id
2. data_disk { blob_uri, managed_disk_id }
3. os_disk { blob_uri, managed_disk_id }

None of the above references work for our intended resource reference : /subscriptions/<subscription>/resourceGroups/<resource group>/providers/Microsoft.Compute/images/<image name> 

And the API tells us so when we try, e.g.

For the source_virtual_machine_disk_id,
> │ Error: ID was missing the `virtualMachines` element

Or for the *_disk blocks:
> Expected a Disk ID that matched:
> │ 
> │ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Compute/disks/diskValue

### New or Affected Resource(s)/Data Source(s)

azurerm_image

### Potential Terraform Configuration

```hcl
data "azurerm_image" "this" {
  name = "sourceImageName"
  resource_group_name = "imageGroup"
}

resource "azurerm_image" "this" {
  name = "imageName"
  location = "centralus"
  resource_group_name = "deploymentGroup"
  image_id = data.azurerm_image.this.id
}

resource "azurerm_windows_virtual_machine" "this" {
  source_image_id = azurerm_image.this.id
...
}
```

**Comment by ms-zhenhua** [comment]
Hi @mjneuharth, thank you for reaching out. 
`azurerm_image` is based on the [Azure Images REST API ](https://learn.microsoft.com/en-us/rest/api/compute/images/create-or-update?view=rest-compute-2023-07-01&tabs=HTTP)which does not support creating image from an existing image ID.
Will you consider using `azurerm_shared_image_version` which can be created from an existing `azurerm_image` and be used by an `azurerm_windows_virtual_machine`?
Here is an example:

```
provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-231120153155457682"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestnw-231120153155457682"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "test" {
  name                = "acctestnic-231120153155457682"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.test.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_shared_image_gallery" "test" {
  name                = "acctestsig231120153155457682"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"
}

resource "azurerm_shared_image" "test" {
  name                = "acctest-gallery-image"
  gallery_name        = azurerm_shared_image_gallery.test.name
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  os_type             = "Windows"

  identifier {
    publisher = "AcceptanceTest-Publisher"
    offer     = "AcceptanceTest-Offer"
    sku       = "AcceptanceTest-Sku"
  }
}

data "azurerm_image" "test" {
  name                      = "myPackerImage"
  resource_group_name       = "ademo-rg"  # resource group where the image resides
}

resource "azurerm_shared_image_version" "test" {
  name                = "0.0.1"
  gallery_name        = azurerm_shared_image.test.gallery_name
  image_name          = azurerm_shared_image.test.name
  resource_group_name = azurerm_shared_image.test.resource_group_name
  location            = azurerm_shared_image.test.location
  managed_image_id    = data.azurerm_image.test.id

  target_region {
    name                   = azurerm_shared_image.test.location
    regional_replica_count = "1"
    storage_account_type   = "Standard_LRS"
  }
}

resource "azurerm_windows_virtual_machine" "test" {
  name                = "example-vm"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  admin_password      = "xxxxxxxxxx"
  source_image_id     = azurerm_shared_image_version.test.id
  network_interface_ids = [
    azurerm_network_interface.test.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }
}
```

**Comment by ms-zhenhua** [comment]
Hi @mjneuharth, you may create a feature-request issue in [Azure/azure-rest-api-specs repo](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/compute/resource-manager/Microsoft.Compute/ComputeRP/stable/2022-03-01/image.json) to submit your request for Azure Image API.

**Comment by mjneuharth** [comment]
Thanks for the assistance here. Cheers!
