### ISSUE TITLE
Error importing azurerm_iothub element

### ISSUE THREAD

**Issue by patrickdassier** [hashicorp/terraform-provider-azurerm#23963]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.81.0

### Affected Resource(s)/Data Source(s)

azurerm_iothub

### Terraform Configuration Files

```hcl
import {
    id = "/subscriptions/xxx-xxx-xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx"
    to = azurerm_iothub.my_iothub
}
```

### Debug Output/Panic Output

```shell
Error: ID was missing the `iotHubs` element
```

### Expected Behaviour

When importing an iothub element, there is the following error:
`Error: ID was missing the `iotHubs` element`

Looking at the code, it seems that the azurerm provider looks for the name _iotHubs_ in the resource id, as Azure names it _iotHubs_, without a _i_ capitalized.

Could someone confirm this analysis ?

**Comment by ziyeqf** [comment]
Hi @patrickdassier, thanks for reporting.

Per the [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/iothub#import), the segment in the id should be `iotHubs`. For some resources the id have different casing in terraform and Azure portal.
Please modify the imported id to match the format in the above document.

For any further questions please leave comments, thanks!
