### ISSUE TITLE
Support for AKS Artifact Streaming

### ISSUE THREAD

**Issue by jrauschenbusch** [hashicorp/terraform-provider-azurerm#23961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Support for AKS Artifact Streaming would be really helpful for workloads which involve "large images, which can cause long image pull times and slow down your workload deployments."

- https://learn.microsoft.com/en-us/azure/aks/artifact-streaming
- https://learn.microsoft.com/en-us/azure/container-registry/tutorial-artifact-streaming

Support in REST API: https://github.com/Azure/azure-rest-api-specs/blob/bf204aab860f2eb58a9d346b00d44760f2a9b0a2/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-10-02-preview/managedClusters.json#L4096

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster, azurerm_kubernetes_cluster_node_pool

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request!

**Comment by jonathan-fileread** [comment]
+1, this service would be highly useful

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
