### ISSUE TITLE
maintenance_window_auto_upgrade/week_index does not link against the specified week but the occurrence of the day in the month

### ISSUE THREAD

**Issue by rgarcia89** [hashicorp/terraform-provider-azurerm#23979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.81.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
locals {
  current_time = timestamp()
  start_time   = timeadd(local.current_time, "1h")
}

resource "azurerm_kubernetes_cluster" "aks" {
  name                                = "some-name"
  resource_group_name                 = "some-rg"
  automatic_channel_upgrade           = "patch"
  node_os_channel_upgrade             = "NodeImage"

  api_server_access_profile {
    authorized_ip_ranges = []
  }

  maintenance_window {
    allowed {
      day   = var.auto_update_day != null ? var.auto_update_day : local.stage == "lab" ? "Tuesday" : local.stage == "prod" ? "Thursday" : null
      hours = [8, 9, 10, 11] # allow maintenace from 8:00am to 12:00pm
    }
  }

  maintenance_window_auto_upgrade { # kubernetes version upgrade
    frequency   = "RelativeMonthly" # same day of the month
    interval    = 1                 # once a month
    duration    = 4
    day_of_week = "Tuesday"
    week_index  = "First"
    start_time  = "08:00"
    utc_offset  = "+02:00"
    start_date  = local.start_time

  }

  maintenance_window_node_os {      # node-image version upgrade
    frequency   = "RelativeMonthly" # same day of the month
    interval    = 1                 # once a month
    duration    = 4
    day_of_week = "Tuesday"
    week_index  = "Third"
    start_time  = "08:00"
    utc_offset  = "+02:00"
    start_date  = local.start_time
  }

  default_node_pool {
    name                        = "nodepool1"
    temporary_name_for_rotation = "nodepoolx"
    node_count          = 3
    vm_size             = "Standard_D2ds_v5"
    os_disk_type        = "Ephemeral"
    os_disk_size_gb     = 80
    os_sku              = "AzureLinux"
    enable_auto_scaling = false
    zones               = [1, 2, 3]
  }
}
```

### Debug Output/Panic Output

```shell
not available
```

### Expected Behaviour

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/4134730/1d3fb8d3-1c99-4bcc-adc4-3f66e60b0282)

According to the definition of the maintenance my expectation is as followed.

On the Tuesday of the first week of the month run a kubernetes patch level update, if available.
On the Tuesday of the third week of the month run a node os update, if available.

### Actual Behaviour

Per days and weeks on the calendar above Tuesday of the third week should be the 14. November. However the maintenance is not happening on that date. Instead Tuesday the 21. November is being used.

### Steps to Reproduce

Implement the above shown maintenance section into your terraform definition and choose a day / week combination where you count the occurances of the date, instead of the week.

**Comment by ms-henglu** [comment]
Hi @rcskosir ,

Thank you for taking time to report this issue.

According to the doc, the `RelativeMonthly` schedule:
> For schedules like: 'recur every month on the first Monday' or 'recur every 3 months on last Friday

It seems that the current behavior follows its description.

refs: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/containerservice/resource-manager/Microsoft.ContainerService/aks/preview/2023-04-02-preview/managedClusters.json#L4225

**Comment by rgarcia89** [comment]
Hi @ms-henglu, 
understood. In that case the current description

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/4134730/315f952c-f23f-40f7-95d8-3ffa39fa9cb7)

is quite misleading. Since it lets assume one that you do set the week index here. So Tuesday of the First, Second, Third week. Which is not what is happening according to the official Microsoft description. Instead you are defining the occurrence of the specific day. So the first, second, third Tuesday of the month.

**Comment by ms-henglu** [comment]
Thanks @rgarcia89 , I opened a PR to improve the doc: https://github.com/hashicorp/terraform-provider-azurerm/pull/23996
