### ISSUE TITLE
Whether sku_tier of "azurerm_kubernets_cluster" supports "premium" functionality

### ISSUE THREAD

**Issue by sohwaje** [hashicorp/terraform-provider-azurerm#23972]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

The azcli command supports the following features when creating or updating an AKS.(Long Term Support (LTS))

1. sku_tier = premium
2. k8s-support-plan = AKSLongTermSupport

The example of the command is as follows. 

```
az aks create --resource-group myResourceGroup --name myAKSCluster --tier premium --k8s-support-plan AKSLongTermSupport --kubernetes-version 1.27

az aks update --resource-group myResourceGroup --name myAKSCluster --tier premium --k8s-support-plan AKSLongTermSupport
```

### Description

"sku_tier = premium", "k8s-support-plan = AKSLongTermSupport" is not currently supported for the "azurerm_kubernets_cluster" feature. Do you have any future support plans? I'm curious. In other words, I would like to know if you are planning to support the LTS feature or not.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #23970 created by @ms-henglu for this issue.
