### ISSUE TITLE
Support for Azure Kubernetes Service cost analysis

### ISSUE THREAD

**Issue by gravufo** [hashicorp/terraform-provider-azurerm#23982]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It would be very useful and convenient to add [AKS cost analysis](https://learn.microsoft.com/en-us/azure/aks/cost-analysis?wt.mc_id=searchAPI_azureportal_inproduct_rmskilling&sessionId=c9a872241c154e4a84ec273dfbc40cc0) support in the `azurerm_kubernetes_cluster` resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "this" {
  name          = "mycluster"
  location      = var.location
  [...]
  enable_cost_analysis = true
}
```

### References

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/aks-cost-analysis-an-azure-native-cost-visibility-experience/ba-p/3973401
https://learn.microsoft.com/en-us/azure/aks/cost-analysis?wt.mc_id=searchAPI_azureportal_inproduct_rmskilling&sessionId=c9a872241c154e4a84ec273dfbc40cc0

**Comment by ppa007asr** [comment]
Functionality has become GA today. Can this issue be picked up and the preview label removed?

**Comment by sydneydf** [comment]
Agreed! Would love this integration!

**Comment by mdaslamansari** [comment]
Any timeline?

**Comment by zioproto** [comment]
GA announcement:
https://azure.microsoft.com/en-gb/updates/generally-available-cost-analysis-addon-for-aks/

Cc: @ms-henglu @stephybun

**Comment by danielkwok72** [comment]
Hi

Would love to see this is supported in the next release of the azurerm provider and the aks resource. We are looking into enabling this feature in our cluster using terraform, but try to avoid azapi, so native support from azurerm will be fantastic.

**Comment by jblaaa-codes** [comment]
+ 1 on this.

**Comment by andriktr** [comment]
+1

**Comment by mdaslamansari** [comment]
+1 any plans for its TF integration...

**Comment by danielkwok72** [comment]
Any ETA on when the next provider release containing this feature will be great.

**Comment by jochenhebbrecht** [comment]
+1 👉  this would be really helpfu!
