### ISSUE TITLE
Cannot add a capability and upgrade the CosmosDB version at the same time.

### ISSUE THREAD

**Issue by moialbla** [hashicorp/terraform-provider-azurerm#23986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.81.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features = {}
}

resource "azurerm_resource_group" "cosmosdb_rg" {
  name     = "cosmosdb-rg"
  location = "East US"  # Change this to your desired region
}

resource "azurerm_cosmosdb_account" "cosmosdb" {
  name                = "cosmosdb-account"
  location            = azurerm_resource_group.cosmosdb_rg.location
  resource_group_name = azurerm_resource_group.cosmosdb_rg.name
  offer_type          = "Standard"
  kind                = "MongoDB"
  mongo_server_version            = 4.2 # this value was 3.6

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix   = 100
  }

  enable_multiple_write_locations = false

  geo_location {
    location          = azurerm_resource_group.cosmosdb_rg.location
    failover_priority = 0
    is_zone_redundant = false
  }

  capabilities {
    name = "EnableMongo"
  }

  capabilities {
    name = "EnableMongo16MBDocumentSupport"
  }
}
```

### Debug Output/Panic Output

```shell
documentdb.DatabaseAccountsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="\"EnableMongo16MBDocumentSupport capability is not compatible with mongo ServerVersion=3.6 accounts.\"\r\nActivityId: 00000, Microsoft.Azure.Documents.Common/2.14.0"
```

### Expected Behaviour

2023-11-22T09:54:30.7581303Z   ~ resource "azurerm_cosmosdb_account" "cosmos_db" {
2023-11-22T09:54:30.7582734Z         id                                           = "/subscriptions/0000000000000/resourceGroups/MY-RG/providers/Microsoft.DocumentDB/databaseAccounts/cosmosdb-account"
2023-11-22T09:54:30.7584118Z       ~ mongo_server_version                         = "3.6" -> "4.2"
2023-11-22T09:54:30.7584812Z         name                                         = "cosmosdb-account"
2023-11-22T09:54:30.7588038Z 
2023-11-22T09:54:30.7588290Z       + capabilities {
2023-11-22T09:54:30.7588656Z           + name = "EnableMongo16MBDocumentSupport"
2023-11-22T09:54:30.7589106Z         }
2023-11-22T09:54:30.7589268Z 
2023-11-22T09:54:30.7589538Z         # (6 unchanged blocks hidden)
2023-11-22T09:54:30.7589920Z     }****

### Steps to Reproduce

1 - Create a Cosmosdb -Mongo DB version 3.6
2 - Update the Cosmosdb.tf version from 3.6 to 4.2 and add the new capability EnableMongo16MBDocumentSupport
3 - Run the Terraform

**Comment by sinbai** [comment]
Hi @moialbla thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/24029)has been submitted to fix this issue. Could you please track it for more updates?

**Comment by moialbla** [comment]
Sure thing! 
Thanks!
