### ISSUE TITLE
Support for PostgreSQL Flexible Server: add Private Endpoint configuration

### ISSUE THREAD

**Issue by SmitsJoachim** [hashicorp/terraform-provider-azurerm#23992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

As of now, you can use Private Endpoints with PostgreSQL Flexible Server: please add this to azurerm_postgresql_flexible_server.
Reason: you cannot create a PostgreSQL Flexible Server resource by Terraform and afterwards adding Private Endpoint in Portal...

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it has been supported by [azurerm_private_endpoint](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint). Please check if it is what you expected.

**Comment by SmitsJoachim** [comment]
It works!

**Comment by DavidHe1127** [comment]
> It works!

hey I am struggling to get it to work. Would you mind sharing some code snippet on how you've done it? Thanks

**Comment by joachimsmits** [comment]
first: 
resource "azurerm_postgresql_flexible_server" "postgresql_flexible_server" {
  name                = "psql-${var.devprodall}-${var.location}-${var.acronym}"
  location            = var.location_full
  resource_group_name = var.resource_group
BLA BLA BLA BLA
}

and then:
module "private_endpoint" {
  source = "../private-endpoint"

  devprodall     = var.devprodall
  location       = var.location
  location_full  = var.location_full
  resource_group = var.resource_group
  acronym        = var.acronym

  resource_id = azurerm_postgresql_flexible_server.postgresql_flexible_server.id

  subnet_name      = "snet-${var.devprodall}-${var.location}-tribe-housing-databases"
  subnet_vnet_name = "vnet-${var.devprodall}-${var.location}-tribe-housing"
  subnet_rg_name   = "rg-${var.devprodall}-${var.location}-network"

  dns_zone_name     = "privatelink.postgres.database.azure.com"
  subresource_names = ["postgresqlServer"]

  tags = local.tags
}

Where the Private Endpoint Module is:
resource "azurerm_private_endpoint" "private_endpoint" {
  name                = "pe-${var.devprodall}-${var.location}-${var.acronym}"
  location            = var.location_full
  resource_group_name = var.resource_group
  subnet_id           = data.azurerm_subnet.subnet.id
  
  private_dns_zone_group { 
    name                 = "Entry-in-private-dns-zone-${var.devprodall}-${var.location}-${var.acronym}"
    private_dns_zone_ids = [data.azurerm_private_dns_zone.private_dns_zone.id]
  }

  private_service_connection {
    name                           = "pl-${var.devprodall}-${var.location}-${var.acronym}"
    is_manual_connection           = false
    private_connection_resource_id = var.resource_id
    subresource_names              = var.subresource_names
  }

  tags = local.tags
}

When more info is needed, plz ping me!

**Comment by DavidHe1127** [comment]
@joachimsmits Thanks for sharing. I've changed mine to be aligned with yours, however, I still see the same error I've mentioned in my earlier thread. Do you encounter this error?

**Comment by joachimsmits** [comment]
in our code, I cannot find parameter: PublicNetworkAccess

**Comment by joachimsmits** [comment]
but I can give you also the full Flex PQL Module:

odule "postgresql-flexible-server" {
  source = "git::https://dev.azure.com/raboweb/Tribe%20Housing/_git/it4it-tf-modules//azure/postgresql-flexible-server"

  count = local.databaseServerCount

  devprodall    = var.devprod
  location      = var.location
  location_full = var.location_full
  acronym       = var.acronym

  resource_group = module.resource-group.name

  sku_name           = var.postgresql_configurations.sku_name
  postgresql_version = var.postgresql_configurations.version

  backup_retention_days = var.postgresql_backup_retention_days
  server_parameters     = var.postgresql_server_parameters

  standby_zone = 2

  tags = local.tags
}

**Comment by joachimsmits** [comment]
Where the module contains: 

locals {
  tags = merge(
    var.tags,
    {
      "createdAt" = time_static.created_at.id
    }
  )
}

resource "time_static" "created_at" {}

data "azurerm_client_config" "current" {}
data "azuread_client_config" "current" {}
data "azuread_service_principal" "service_principal" {
  client_id = data.azuread_client_config.current.client_id
}

resource "azurerm_postgresql_flexible_server" "postgresql_flexible_server" {
  name                = "psql-${var.devprodall}-${var.location}-${var.acronym}"
  location            = var.location_full
  resource_group_name = var.resource_group

  sku_name = var.sku_name
  version  = var.postgresql_version

  auto_grow_enabled = true

  zone                  = var.zone
  backup_retention_days = var.backup_retention_days

  authentication {
    password_auth_enabled         = false
    active_directory_auth_enabled = true
    tenant_id                     = data.azurerm_client_config.current.tenant_id
  }

  dynamic "high_availability" {
    for_each = var.standby_zone != null ? toset([var.standby_zone]) : toset([])

    content {
      mode                      = "ZoneRedundant"
      standby_availability_zone = high_availability.value
    }
  }

  tags = merge(
    local.tags,
    {
      "UnassessedResource_generic-H-023" : "Testing Flexible Server for upcoming migration"
    }
  )
}

resource "azurerm_postgresql_flexible_server_active_directory_administrator" "postgresql_flexible_server_active_directory_administrator" {
  server_name         = azurerm_postgresql_flexible_server.postgresql_flexible_server.name
  resource_group_name = var.resource_group
  tenant_id           = data.azurerm_client_config.current.tenant_id
  object_id           = data.azuread_service_principal.service_principal.object_id
  principal_name      = data.azuread_service_principal.service_principal.display_name
  principal_type      = "ServicePrincipal"
}

resource "azurerm_postgresql_flexible_server_configuration" "postgresql_flexible_server_configuration" {
  for_each = var.server_parameters

  name      = each.key
  server_id = azurerm_postgresql_flexible_server.postgresql_flexible_server.id
  value     = each.value
}

module "private_endpoint" {
  source = "../private-endpoint"

  devprodall     = var.devprodall
  location       = var.location
  location_full  = var.location_full
  resource_group = var.resource_group
  acronym        = var.acronym

  resource_id = azurerm_postgresql_flexible_server.postgresql_flexible_server.id

  subnet_name      = "snet-${var.devprodall}-${var.location}-tribe-housing-databases"
  subnet_vnet_name = "vnet-${var.devprodall}-${var.location}-tribe-housing"
  subnet_rg_name   = "rg-${var.devprodall}-${var.location}-network"

  dns_zone_name     = "privatelink.postgres.database.azure.com"
  subresource_names = ["postgresqlServer"]

  tags = local.tags
}

**Comment by DavidHe1127** [comment]
@joachimsmits Thanks for sharing full content. Much appreciated. However, apart from auth params which I think it's unlikely to be relevant, all other params match mine. I will submit a support ticket for it.
