### ISSUE TITLE
Support for database shared throughput in CosmosDB

### ISSUE THREAD

**Issue by DeLeneMirouze** [hashicorp/terraform-provider-azurerm#24010]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Is it possible to set database shared throughput on cosmosdb ?

I found old 2019 issues about this, but can't find if it has been implemented.

****

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/3623

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems it has been supported by TF. See more details from https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_sql_database#example-usage.

**Comment by DeLeneMirouze** [comment]
ok thank you

**Comment by DeLeneMirouze** [comment]
I have the answer
