### ISSUE TITLE
Support for performance tier in postgresql_flexible_server_resource

### ISSUE THREAD

**Issue by pawelwalczak-tomtom** [hashicorp/terraform-provider-azurerm#24021]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure Portal allows for setting Performance Tier for disks managed by Flexible Server resource. 
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/76997551/7a406058-cf7e-417a-8cc0-a21f8cba4d20)
https://learn.microsoft.com/en-us/azure/virtual-machines/disks-change-performance

I couldn't find an existing way to set this parameter through this provider.

### New or Affected Resource(s)/Data Source(s)

postgresql_flexible_server_resource

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request!

**Comment by rbtcollins** [comment]
This seems to be implemented already?

**Comment by rcskosir** [comment]
I believe you are correct, looking at this PR https://github.com/hashicorp/terraform-provider-azurerm/pull/24892, I see the performance tiers. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are using, and more details about the enhancement, thanks!
