### ISSUE TITLE
Can't  associate NAT Rules with Connections in VPNGW (Azure)

### ISSUE THREAD

**Issue by jargoPL** [hashicorp/terraform-provider-azurerm#24037]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.0

### AzureRM Provider Version

2.46

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway

### Terraform Configuration Files

```hcl
Ok, so i have got Virtual network gateway, there are NAT Rules and Connections.
In Connections → NAT Rules there is:

Associate NAT rules that have been configured on the linked Virtual Network Gateway.

I have an ingress and egress NAT Rules there linked.

But how can i make it from Terraform? (associate NAT Rules with Connections)

Everytime when i want to run pipeline now, i have got error:

error: Creating/Updating Virtual Network Gateway: (Name "examplename-connectivity-euw-prod-01" / Resource Group "rg-example-euw-prod-01"): network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="GatewayNatRuleIsStillInUse" Message="The NAT rule /subscriptions/xxxxxxxxxxxx/resourceGroups/rg-example-euw-prod-01/providers/Microsoft.Network/virtualNetworkGateways/vpngw-example-euw-prod-01/natRules/nat-rule-01 is still in use and cannot be deleted. 


I dont want it to be deleted at all, i just want to make another, different connection without touching those linked NAT Rules.
```

### Debug Output/Panic Output

```shell
error: Creating/Updating Virtual Network Gateway: (Name "examplename-connectivity-euw-prod-01" / Resource Group "rg-example-euw-prod-01"): network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="GatewayNatRuleIsStillInUse" Message="The NAT rule /subscriptions/xxxxxxxxxxxx/resourceGroups/rg-example-euw-prod-01/providers/Microsoft.Network/virtualNetworkGateways/vpngw-example-euw-prod-01/natRules/nat-rule-01 is still in use and cannot be deleted.
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this. We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
