### ISSUE TITLE
Support for [primary_connection_string_alias] for azurerm_servicebus_namespace

### ISSUE THREAD

**Issue by MikayelyanVahe** [hashicorp/terraform-provider-azurerm#24048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Dear Support 

I have tried to search primary_connection_string_alias support for azurerm_servicebus_namespace resource in latest version of azurerm provider but in documnetation there is no any hint about support

The point is when Standard Service Bus is migrated to Premium Azure makes possible to use Alias Primary Connection String with old name (when Service Bus was in Standard SKU) without changing any connection string in services they are using

Could you please evaluate and give a feedback whether possible to have primary_connection_string_alias in output for azurerm_servicebus_namespace resource

### New or Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace.html

**Comment by MikayelyanVahe** [comment]
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/45225552/256a6e00-e757-4add-9a7d-ffad17f4b8a3)

**Comment by xiaxyi** [comment]
Thanks @MikayelyanVahe for raising this issue, I see https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace.html#default_primary_connection_string is exported, are you referring to export the alias connection string other than the default one?

**Comment by xiaxyi** [comment]
ah I see, let me check the api behavior first.

**Comment by MikayelyanVahe** [comment]
> azurerm_servicebus_namespace_authorization_rule 

Hi @xiaxyi 
Great I will use it to export primary_connection_string_alias 
BTW but is there any plan to have it in azurerm_servicebus_namespace resource?

**Comment by xiaxyi** [comment]
Thanks @MikayelyanVahe for the feedback, I'm afraid that we don't have any plan adding it the `azurerm_servicebus_namespace` for the following reasons:
1. It's a conditional property which isn't generated to every servicebus namespace by API, only those migrated/ DCRed has it.
2. The property is already supported by the `azurerm_servicebus_namespace_authorization_rule` resource provider.

Of course we can reconsider it, if you can provider a valid business justification. :) 

Let me know if you have any issue of accessing the property using the currently provided method.

**Comment by MikayelyanVahe** [comment]
Done
