### ISSUE TITLE
Support for getting a list of container names in a storage account

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#24057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

There is already an existing datasource `azurerm_storage_container` that requires a container name.  I would like a new datasource azurerm_storage_containerS ? that would give me a list of all of the containers in a named storage account.

It would be fine by me if datasource `azurerm_storage_account` was enhanced to include a list of the container names that it houses.

Bonus: would be to have a filter to only get the names of certain container names that match the filter or regex etc.

The issue we are trying to resolve is that there is an external entity creating containers and we need to be able to get a list of the existing containers and setup IAM and storage management policies.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_container azurerm_storage_account

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24061 created by @magodo for this issue.
