### ISSUE TITLE
Microsoft.Network/dnsForwardingRulesets/virtualNetworkLinks resource doesn't exist

### ISSUE THREAD

**Issue by tap1992** [hashicorp/terraform-provider-azurerm#24068]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.82.0

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_resolver_dns_forwarding_ruleset

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Should be able to link a azurerm_private_dns_resolver_dns_forwarding_ruleset to a virtual network to enable DNS forwarding rules for that specified Virtual Network.

### Actual Behaviour

The existing Terraform resource azurerm_private_dns_resolver_dns_forwarding_ruleset contains any VNet linking ability. When looking at the JSON template in Azure, it lists the virtual network link as a dedicated resource called 'Microsoft.Network/dnsForwardingRulesets/virtualNetworkLinks'

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @wuxu92‘s response as an answer. If that is not the case, please provide additional information for a feature request, thanks!
