### ISSUE TITLE
"Network Contributor" role not taking immediate effect during Terraform Apply for Kubernetes Cluster creation

### ISSUE THREAD

**Issue by vlad-333** [hashicorp/terraform-provider-azurerm#24064]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

latest

### AzureRM Provider Version

3.82.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
Pretended config:

resource "azurerm_resource_group" "example" {
  name     = "example"
  location = "West Europe"
}

resource "azurerm_user_assigned_identity" "example" {
  location            = azurerm_resource_group.example.location
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
}

# I also have a network_rg resource group where the azurerm_private_dns_zone is created and linked to the apropriate virtual network

resource "azurerm_role_assignment" "example" {
  scope                = module.resource_groups.rg["network_rg"].id
  role_definition_name = "Network Contributor"
  principal_id         = azurerm_user_assigned_identity.example.principal_id
}

resource "azurerm_kubernetes_cluster" "example" {
  name                    = "example-aks1"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  dns_prefix              = "exampleaks1"
  private_cluster_enabled = true
  private_dns_zone_id     = var.private_dns_zone_id

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.example.id]
  }

  tags = {
    Environment = "Production"
  }
}

output "client_certificate" {
  value     = azurerm_kubernetes_cluster.example.kube_config.0.client_certificate
  sensitive = true
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.example.kube_config_raw

  sensitive = true
}
```

### Debug Output/Panic Output

```shell
Failure sending request: StatusCode=0 -- Original Error: Code="CustomPrivateDNSZoneMissingPermissionError" Message="Service principal or user-assigned identity must be given permission to read and write to custom private dns zone /subscriptions/*****/resourceGroups/network-rg/providers/Microsoft.Network/privateDnsZones/privatelink.***.io. Check access result not allowed for action Microsoft.Network/privateDnsZones/read."
```

### Expected Behaviour

The "Network Contributor" role should take immediate effect during the first run of terraform apply, allowing the successful creation of the Kubernetes cluster without any permission issues.

### Actual Behaviour

The initial run of terraform apply fails with a permission error related to the private custom DNS zone, even though the role that permits the action is assigned. Subsequent run succeed without any changes done to the terraform or azure resources via Portal.

### Steps to Reproduce

1. Execute terraform apply to create the Kubernetes cluster.
2. Observe the failure during the apply job related to permission issues with the private custom DNS zone.
3. Check the Azure portal for the assigned "Network Contributor" role.
4. Execute terraform apply again without making any changes.
5. Observe that the second run succeeds.

**Comment by ms-henglu** [comment]
Hi @rcskosir ,

Thank you for taking time to report this issue!

Would you please check whether you have specified `depends_on = [azurerm_role_assignment.example]` in the Kubernetes resource block?

**Comment by vlad-333** [comment]
@rcskosir can you please set up apropriate tags as this is not only related to aks, thank you.

I face the same issue when creating a key vault certificate.
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/58341285/9068e4dd-2d70-4386-a01c-48062f680c8c)

Here is the full error:
Error: checking for presence of existing Certificate "example-cert" in https://example-kv.vault.azure.net/: keyvault.BaseClient#GetCertificate: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Caller is not authorized to perform action on resource.\r\nIf role assignments, deny assignments or role definitions were changed recently, please observe propagation time.\r\nCaller: appid=***;oid=***;iss=[https://sts.windows.net/***/\r\nAction](https://sts.windows.net/***//r/nAction): 'Microsoft.KeyVault/vaults/certificates/read'\r\nResource: '/subscriptions/***/resourcegroups/dev-compute-rg/providers/microsoft.keyvault/vaults/example-kv/certificates/example-cert'\r\nAssignment: (not found)\r\nDenyAssignmentId: null\r\nDecisionReason: 'DeniedWithNoValidRBAC' \r\nVault:example-kv;location=swedencentral\r\n" InnerError={"code":"ForbiddenByRbac"}

When I run the pipeline for the second time without making any changes to the code, the key vault certificate is beeing created successfully.

**Comment by MilesCameron-DMs** [comment]
From you error it looks like you need to add the Private DNS Zone Contributor role to your user assigned id and scope it to your private DNS zone.

**Comment by vlad-333** [comment]
> @vlad-333 From you error it looks like you need to add the Private DNS Zone Contributor role to your user assigned id and scope it to your private DNS zone.
> 
> That is a requirement for:
> 
> `private_cluster_enabled = true`

Hi @MilesCameron-DMs,

The Network Contributor role already [contains ](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#network-contributor) all the actions that a Private DNS Zone Contributor role [contains](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#private-dns-zone-contributor)

Also, if you'll read careful my comments, the issue is that the role don't take imediate effect, as when I run the pipeline second time (without making any changes to the roles or tf code) it works as expected.

**Comment by MilesCameron-DMs** [comment]
Fair point, i have written something very similar and am not seeing this issue, the only real difference is my code is modularised.

**Comment by vlad-333** [comment]
After some time I added in my locals a _depends_on_ variable with the value of the output of the role assignment from the module **role_assignments** and it worked out.
Example:
`depends_on = module.role_assignments.mi_rbac["network_contributor"]`
