### ISSUE TITLE
Support Event Grid Namespaces and MQTT broker

### ISSUE THREAD

**Issue by TheoMcCabe** [hashicorp/terraform-provider-azurerm#24079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I would like to create an event grid namespace mqtt broker using this terraform provider - it doesn't seem to be supported currently. 

Heres a link to the azure documentation: https://learn.microsoft.com/en-us/azure/event-grid/mqtt-overview

### New or Affected Resource(s)/Data Source(s)

azurerm_eventgrid

### Potential Terraform Configuration

```hcl
resource "azurerm_eventgrid_namespace" "my_namespace" {
  name                = "my_namespace"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  tags                = var.tags
  enable_mqtt_broker  = true

    mqtt_broker { 
      enable_alternative_client_authentication_name_sources= false
      maximum_session_expiry_interval_in_hours=1
      maximum_client_sessions_per_authentication_name=1
    }
}
```

### References

https://learn.microsoft.com/en-us/azure/event-grid/mqtt-overview

**Comment by jonas-weimar** [comment]
You can create a namespace and thus an mqtt event grid using the azapi provider (https://learn.microsoft.com/en-us/azure/templates/microsoft.eventgrid/namespaces?pivots=deployment-language-terraform)

**Comment by wyp84** [comment]
Same here, would be nice to have this in Terraform.
