### ISSUE TITLE
Unable to remove user assigned identity from azurerm_api_management

### ISSUE THREAD

**Issue by mg-8** [hashicorp/terraform-provider-azurerm#24084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.7

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
yaml config decalaration:-
apigw:
  shared:
    name: test-shdapi-gw-01
    sku_name: Developer_1
    publisher:
      name: test-shdapigw
      email: test-shdapigw@test.com    
    managed_identity:
      type: "UserAssigned"
      names:
        - id-test-shdapi-gw-01
        - id-test-shdapi-gw-02 

main.tf:-
resource "azurerm_user_assigned_identity" "this" {
  for_each = length(var.api_management.identity.names) != 0 ? toset(var.api_management.identity.names) : []

  name                = each.key
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location
}

resource "azurerm_api_management" "this" {
  name                = var.api_management.name
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location
  publisher_name      = var.api_management.publisher.name
  publisher_email     = var.api_management.publisher.email

  sku_name             = var.api_management.sku_name
  virtual_network_type = "Internal"
  public_ip_address_id = azurerm_public_ip.this.id

  identity {
    type         = var.api_management.identity.type
    identity_ids = length(var.api_management.identity.names) != 0 ? [for uai in azurerm_user_assigned_identity.this : uai.id] : []
  }

  virtual_network_configuration {
    subnet_id = var.virtual_network.subnet_id
  }
}

Plan:-
  # module.api_management["shared"].azurerm_api_management.this will be updated in-place
  ~ resource "azurerm_api_management" "this" {
        id                            = "/subscriptions/***/resourceGroups/test-shdapigw-rg/providers/Microsoft.ApiManagement/service/test-shdapi-gw-01"
        name                          = "test-shdapi-gw-01"
        tags                          = {}
        # (21 unchanged attributes hidden)

      ~ identity {
          ~ identity_ids = [
              - "/subscriptions/***/resourceGroups/test-shdapigw-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/id-test-shdapi-gw-02",
                # (1 unchanged element hidden)
            ]
            # (2 unchanged attributes hidden)
        }

        # (11 unchanged blocks hidden)
    }
```

### Debug Output/Panic Output

```shell
│ Error: creating/updating Service (Subscription: "***"
│ Resource Group Name: "test-shdapigw-rg"
│ Service Name: "test-shdapi-gw-01"): performing Update: unexpected status 409 with error: MsiServiceException: ClientId received from Managed Identity service of Type: UserAssigned was empty.
│ 
│   with module.api_management["shared"].azurerm_api_management.this,
│   on .terraform/modules/api_management/main.tf line 31, in resource "azurerm_api_management" "this":
│   31: resource "azurerm_api_management" "this" {
│ 
╵
##[error]PowerShell exited with code '1'.
```

### Expected Behaviour

Should be able to remove the user assigned identity marked for deletion from the config. I have created two user assigned identities for api management gateway and trying to remove one of them by removing the identity from config and getting above mentioned error. For some reason its not picking up the existing user assigned identity id while updating the resource config. 

This issue is not just with azurerm_api_management instead you can reproduce this issue with another other resource which supports user assigned identity. Basically identity_ids in below identity block accepts list of ids. Therefore, while removing one of them should work as technically the list is not empty. 

```
  identity {
    type         = "UserAssigned"
    identity_ids = [<list of ids>]
  }
```

### Actual Behaviour

│ Error: creating/updating Service (Subscription: "***"
│ Resource Group Name: "test-shdapigw-rg"
│ Service Name: "test-shdapi-gw-01"): performing Update: unexpected status 409 with error: MsiServiceException: ClientId received from Managed Identity service of Type: UserAssigned was empty.
│ 
│   with module.api_management["shared"].azurerm_api_management.this,
│   on .terraform/modules/api_management/main.tf line 31, in resource "azurerm_api_management" "this":
│   31: resource "azurerm_api_management" "this" {
│ 
╵
##[error]PowerShell exited with code '1'.

### Steps to Reproduce

Create two user assigned identity for api management gateway or any other azure resource support user assigned identity and then try removing one of them using terraform.

**Comment by sinbai** [comment]
Hi @mg-8 , thanks for opening this issue. Could you please add "create_before_destroy  = true" to resource `azurerm_user_assigned_identity` and try again,  like this:

```

lifecycle {
    create_before_destroy = true
  }
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. 
If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
