### ISSUE TITLE
Unable to get the latest key ID after rotating the key in Azure key valut - azurerm_key_vault_key

### ISSUE THREAD

**Issue by sainathyv** [hashicorp/terraform-provider-azurerm#24082]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.62.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_key

### Terraform Configuration Files

```hcl
locals {
    Current_date = timestamp()
    expiry_date = timeadd(local.current_date, "2160h")
}
resource "azurerm_key_vault_key" "encryption_key" {
  name            = "data-encryption_key"
  expiration_date = local.expiry_date
  key_vault_id    = data.azurerm_key_vault_key.keyvault.id
  key_type        = "RSA"
  key_size        = 2048

  key_opts = [
    "decrypt",
    "encrypt",
    "sign",
    "unwrapKey",
    "verify",
    "wrapKey",
  ]

  rotation_policy {
    automatic {
      time_before_expiry = "P80D"
    }

    expire_after         = "P90D"
    notify_before_expiry = "P79D"
  }
lifecycle {
ignore_changes = [
     expiration_date
    ]
   }
}

output "keyvault-id" {
value = azurerm_key_vault_key.encryption_key.id
}
output "version" {
value = azurerm_key_vault_key.encryption_key.version
}
output "versionless_id" {
value = azurerm_key_vault_key.encryption_key.versionless_id
}
output "resource_id" {
value = azurerm_key_vault_key.encryption_key.resource_id
}
output "resource_versionless_id" {
value = azurerm_key_vault_key.encryption_key.resource_versionless_id
}
```

### Debug Output/Panic Output

```shell
keyvault-id = XXX
version = XXX
versionless_id = XXX
resource_id = XXX
resource_versionless_id = XXX
```

### Expected Behaviour

As per the Azure rotation policies, Key has been rotated and when ever we run the Terraform it should fetch the new version of key.

Tried to run the Terraform Refresh commands to update the state file, but still no use.

### Actual Behaviour

When we run the terraform code it was trying to get the old version of the key, after rotation is completed in Azure key vault. 

Currently for our azure key vault auto rotation has been enabled and when ever keys rotate, we need to get the new key version from the terfform code. 
we tried to use versionless_id & Version but still seeing the old key value version itself.

I tried using the Terrform Refresh commands to update the state file, but still no luck. It was trying for the old version key. 

I read few articles in google and they suggested to destory & recreate the key vault, don't want to delete it. 

Looking fo your help & suggestion on this.

### Steps to Reproduce

Terraform apply
Terraform Refresh

### Important Factoids

N/A

### References

N/A

**Comment by sainathyv** [comment]
> @sainathyv Thanks for filing this issue. Out of curiosity, can you obtain the new/latest key ID from the Portal after performing the rotation action?

@wuxu92, Thanks for your response!
No, we are unable to get the new/latest key ID from terraform code.
I see new key in azure portal after key rotation.

**Comment by sainathyv** [comment]
> @sainathyv The ID of the `key_vault_key` resource won't change after apply, but you can obtain the current key version with `data.key_vault_key` [data source](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/key_vault).
> 
> ```terraform
> data "azurerm_key_vault_key" "enc_ds" {
>   key_vault_id = "data-encryption_key"
>   name           = data.azurerm_key_vault_key.keyvault.id
> }
> 
> output "key_id" {
>   value = data.azurerm_key_vault_key.enc_ds.resource_id
> }
> 
> output "key_id_versionless" {
>   value = data.azurerm_key_vault_key.enc_ds.resource_versionless_id
> }
> ```

Hi @wuxu92, Thanks for your response! 
We know about the data option to get the value, but it was not fetching the latest key version id from azure key vault whenever auto rotation is done as per the rotation policies

**Comment by sainathyv** [comment]
Our issue has been resolved !

**Comment by hrazaf6** [comment]
@sainathyv : How did you solve this..can you share the solution here as we are also facing the same issue. Thanks

**Comment by sainathyv** [comment]
> @sainathyv : How did you solve this..can you share the solution here as we are also facing the same issue. Thanks

Hi @hrazaf6 , I have added the Ignore changes in rotation ploicy code.

lifecycle {
ignore_changes = [
     expiration_date
    ]
   }
