### ISSUE TITLE
Support for azurerm_spring_cloud_service tier=StandardGen2

### ISSUE THREAD

**Issue by dgensert** [hashicorp/terraform-provider-azurerm#24103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Please allow resource to support new StandardGen2 tier = pay-as you go.
This will require either new SKUs or adding a new "tier" attribute, due to Azure using the same naming as the old Standard "S0":

`    "sku": {
      "capacity": null,
      "name": "S0",
      "tier": "StandardGen2"
    },`

Also, this will require a reference to container-environments by id. Therefore this change should be simple to integrate.

### New or Affected Resource(s)/Data Source(s)

azurerm_spring_cloud_service

### Potential Terraform Configuration

```hcl
resource "azurerm_spring_cloud_service" "service" {
  name                = var.service_name
  resource_group_name = var.resource_group_name
  location            = var.location
  sku_name            = var.sku
  tier                = "StandardGen2"
  container_environment_id = var.container_environment_id
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24107 created by @harshavmb for this issue.
