### ISSUE TITLE
Terraform apply appears to be in an infinite loop

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#24114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account 

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.3"

  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azuread" {
}

#Enforce that this should always use this subscription ID
provider "azurerm" {

  subscription_id = "0324c699-b0d4-4aa3-a321-571109a1c515"

  features {}
}

data "azurerm_virtual_network" "default" {
  name                = "devops-vnet"
  resource_group_name = "devops-vnet"
}

data "azurerm_subnet" "private-endpoint" {
  name                 = "private-endpoint"
  virtual_network_name = data.azurerm_virtual_network.default.name
  resource_group_name  = data.azurerm_virtual_network.default.resource_group_name
}

resource "azuread_group" "storage-account-blob-owner" {

  display_name = "sa-${azurerm_storage_account.terraform.name}-owner"

  description = "Enables All Blob Access in Storage Account '${azurerm_storage_account.terraform.name}'  for any group member"
  prevent_duplicate_names = true

  security_enabled = true
}

resource "azurerm_resource_group" "current" {
  name = "devops-tfstate-vasta"
  location = "eastus"
}

resource "azurerm_storage_account" "terraform" {
  name                = "tfstatepastacurimeat"
  resource_group_name = azurerm_resource_group.current.name
  location            = azurerm_resource_group.current.location
  account_kind                      = "StorageV2"
  account_replication_type          = "LRS"
  account_tier                      = "Standard"
}

```
```


### Debug Output/Panic Output

```shell
https://gist.github.com/DevopsMercenary/d3a93a0db3beebf0f13fb667941d1efd
```

### Expected Behaviour

create a resource group and storage account.

### Actual Behaviour

Never stops/completes 

trace log appears to show it is in a loop

### Steps to Reproduce

terraform init

terraform apply

**Comment by DevopsMercenary** [comment]
OK.  I went ahead and created the issue, but the issue has 'magically' fixed its self and just happened to start working w/o any additional interaction or changes.

**Comment by mybayern1974** [comment]
Thank you @DevopsMercenary for filing this issue and glad to see things are unblocked for you now, though we do not know why : ) With that, would you mind if we close this issue and of course you can ask for reactivate it once it happens again?
