### ISSUE TITLE
azurerm_cognitive_account virtual network rules only supports a single subnet when multiple subnets are allowed in Azure

### ISSUE THREAD

**Issue by MohnJadden** [hashicorp/terraform-provider-azurerm#24119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.78

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_account

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_account" "openai-cog" {
  for_each                  = var.variableName
  name     = "${each.value.teamName}-test-OpenAI"
    location = "eastus2"
  resource_group_name  = azurerm_resource_group.integration-test-rg[each.key].name
      kind = "OpenAI"
      sku_name = coalesce(each.value.pricingTier, each.key)
      identity {
        type = "SystemAssigned"
      }
      custom_subdomain_name = "${each.value.useCaseName}-oursubdomainname"
      network_acls {
        default_action = "Deny"
        ip_rules = each.value.homeIPs
        virtual_network_rules {
          ignore_missing_vnet_service_endpoint = false
            subnet_id = ["/subscriptions/ourGuid/resourceGroups/network-rg/providers/Microsoft.Network/virtualNetworks/east-vnet/subnets/ML","${azurerm_subnet.integration-test-subnet-funcapp[each.key].id}","${azurerm_subnet.integration-test-subnet-storage[each.key].id}"]
        }
      }
      outbound_network_access_restricted = "true"
      public_network_access_enabled = "true"
        lifecycle {
          ignore_changes = [tags,custom_subdomain_name]
        }
}
```

### Debug Output/Panic Output

```shell
Error: Incorrect attribute value type
│
│   on modules\openai-test\main.tf line 714, in resource "azurerm_cognitive_account" "openai-cog":
│  714:             subnet_id = ["/subscriptions/ourGuid/resourceGroups/network-rg/providers/Microsoft.Network/virtualNetworks/east-vnet/subnets/ML","${azurerm_subnet.integration-test-subnet-funcapp[each.key].id}","${azurerm_subnet.integration-test-subnet-storage[each.key].id}"]
│     ├────────────────
│     │ each.key is a string
│
│ Inappropriate value for attribute "subnet_id": string required.
```

### Expected Behaviour

Terraform should support the subnet_id as "subnet_ids" and allow a list of strings, which would then create the OpenAI service with selected networks allowed, and use the subnets provided in the config - this is supported via OpenAI as per the example below:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/26663320/a3cfe338-c0b7-475e-99c6-27a1e22f4ca5)

### Actual Behaviour

The debug error is produced.  If we only specify one subnet_id, it creates normally, but then we have to manually add the additional subnets.

### Steps to Reproduce

Run terraform apply with the example config and more than one subnet ID

**Comment by harshavmb** [comment]
Hi @MohnJadden ,

`azurerm_cognitive_account` indeed supports multiple subnets but not with `subnet_ids` argument. If you look at restapi specs [here](https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/accounts/create?view=rest-cognitiveservices-accountmanagement-2023-05-01&tabs=HTTP#virtualnetworkrule), only `id` has to be passed within `VirtualNetworkRule` block. 

In terraform configuration this will be translated as multiple blocks (dynamic blocks) as shown below::

```
   virtual_network_rules {
      ignore_missing_vnet_service_endpoint = false
      subnet_id                            = "/subscriptions/ourGuid/resourceGroups/network-rg/providers/Microsoft.Network/virtualNetworks/east-vnet/subnets/ML"
    }

   virtual_network_rules {
      ignore_missing_vnet_service_endpoint = false
      subnet_id                            = "/subscriptions/ourGuid/resourceGroups/network-rg/providers/Microsoft.Network/virtualNetworks/east-vnet/subnets/ML2"
    }
```

**Comment by mybayern1974** [comment]
@MohnJadden , thanks for opening this issue. By assuming harshavmb's (thank harshavmb for your reply!) response could address your questions, I'm closing this issue. Feel free to suggest to re-activate this issue if you believe your question is not fully addressed.
