### ISSUE TITLE
Documentation error -  VMSS can be deployed across multiple zones

### ISSUE THREAD

**Issue by terrymandin** [hashicorp/terraform-provider-azurerm#24120]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
The documentation in the registry says: "Due to a limitation of the Azure API at this time only one Availability Zone can be defined."  However, I set the zones parameter to 3 zones (e.g. ["1", "2", "3"]) and it deployed to all 3.  I think this restriction can be removed from the documentation.
```

### Debug Output/Panic Output

```shell
.
```

### Expected Behaviour

The "Due to a limitation of the Azure API at this time only one Availability Zone can be defined." warning should be removed

### Steps to Reproduce

Go here to see the warning: [Zones](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set.html#zones)
<img width="534" alt="zones_doc" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/833055/6cb9e168-bc2a-4721-8467-d99395835cc0">
<img width="588" alt="vmss_zones_deploy" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/833055/8c8a8989-a82d-4c35-bd54-c7b85ab313d6">

**Comment by ms-zhenhua** [comment]
@terrymandin, thank you for reporting this doc issue. I have created a PR to fix it.
