### ISSUE TITLE
DNS total string length needs to be updated from 1024 to 4096

### ISSUE THREAD

**Issue by abhinavkumar7** [hashicorp/terraform-provider-azurerm#24152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_dns_txt_record

### Terraform Configuration Files

```hcl
resource "azurerm_dns_txt_record" "spf_example_com" {
  name                = "spf"
  zone_name           = data.azurerm_dns_zone.my_zone.name
  resource_group_name = data.azurerm_dns_zone.my_zone.resource_group_name
  ttl                 = 3600
  record {
    value = "v=spf1..........." #More than 1024 characters here
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected length of record.0.value to be in the range (1 - 1024)
```

### Expected Behaviour

The Terraform configuration for Azure TXT record with more than 1024 characters in value should not have given error.

### Actual Behaviour

Following error is generated, when the string length for Azure DNS TXT record goes beyond 1024:

`Error: expected length of record.0.value to be in the range (1 - 1024)`

### Steps to Reproduce

1.) Add the config suggested in this Issue.
2.) Run Terraform Validate.
3.) Terraform throws error.

### References

[The multiple strings in a DNS record shouldn't be confused with the multiple TXT records in a TXT record set. A TXT record set can contain multiple records, each of which can contain multiple strings. Azure DNS supports a total string length of up to 4096 characters* in each TXT record set (across all records combined).](https://learn.microsoft.com/en-us/azure/dns/dns-zones-records#txt-records)

**Comment by mikemadeja** [comment]
Hello, I updated it to 4096. I think it should be ok even if National clouds are still set at 1024. I assume the response to going over that limit would respond with that but I can't test it.
