### ISSUE TITLE
GPT 4 is failing with "Account deployment is not supported"

### ISSUE THREAD

**Issue by dombajova** [hashicorp/terraform-provider-azurerm#24162]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_deployment" "****" {
  count                = 1
  name                 = local.model_name
  cognitive_account_id = one(****[*].id)
  rai_policy_name      = "Microsoft.Default"
  version_upgrade_option = "OnceNewDefaultVersionAvailable"
  
  model {
    format  = "OpenAI"
    name    = "gpt-4"
    version = "1106-preview"
  }

  scale {
    type     = var.open_ai_account_scale.type
    capacity = var.open_ai_account_scale.capacity
  }

  lifecycle {
    ignore_changes = [version_upgrade_option]
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Deployment (Subscription: "52da5607-435d-429b-9edb-4952ba048f87"
Resource Group Name: "****"
Account Name: "****"
Deployment Name: "gpt-4-turbo"): performing CreateOrUpdate: unexpected status 400 with error: DeploymentModelNotSupported: The model 'Format: OpenAI, Name: gpt-4, Version: 1106-preview' of account deployment is not supported.
```

### Expected Behaviour

Hi, I have tried to deploy GPT 4 with version 1106-preview through TA deployment (manually this is ok). But I am getting the following error: `Account deployment is not supported`

**Comment by jayendranarumugam** [comment]
The issue here is the case-sensitive the correct version is `1106-Preview` Capital **P** and not the small

**Comment by rcskosir** [comment]
@dombajova Thank you for opening this issue and @jayendranarumugam thank you for helping to find the problem with the configuration. As such, I am going to mark this issue as closed.
