### ISSUE TITLE
Support for CosmosDb for Mongodb vcore

### ISSUE THREAD

**Issue by nickwilliams-codynamic** [hashicorp/terraform-provider-azurerm#24161]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Add support for CosmosDb for MongoDb v5 (vcore) model.

https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/

Given the differences between the RU and vcore setup I'm not sure if this would be an extension to the existing resource, or a new resource entirely. 

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resource-group"
  location = "West Europe"
}

resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_cosmosdb_account" "db" {
  name                = "tfex-cosmos-db-${random_integer.ri.result}"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  enable_automatic_failover = true

  capabilities {
    name = "EnableAggregationPipeline"
  }

  capabilities {
    name = "mongoEnableDocLevelTTL"
  }

  capabilities {
    name = "MongoDBv5"
  }

  capabilities {
    name = "EnableMongo"
  }

  node_group_specs = [
        {
            kind: 'Shard'
            node_count: 1
            sku: 'M40'
            disk_size_gb: 128
            enable_ha: false
        }
    ]

  
}
```
```


### References

https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/

**Comment by harshavmb** [comment]
The closest I could relate is `cosmosdb_cassandra_datacenter` using `Microsoft.DocumentDB/cassandraClusters` API. Similarly Mongo cluster resource could have `cosmosdb_mongo_datacenter` name using `Microsoft.DocumentDB/mongoClusters` API. 
Lot of attributes are similar.

**Comment by nickwilliams-codynamic** [comment]
@mybayern1974 what is the 'preview' label? Does that related to Azure resources being in Preview? If so, CosmosDb for MongoDb vcore is GA now - announced at ignite.

**Comment by mybayern1974** [comment]
@nickwilliams-codynamic The reason I marked this as `preview` is, per what I've noticed, this feature only appears in the Azure service [preview API version](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2023-09-15-preview/mongoCluster.json#L4). To ensure it's technically safe to have Terraform AzureRM support this feature, I may suggest either wait for this feature appear in the Azure service stable API version or the Azure service team could confirm that preview API version could be regarded as same bar of stable APIs. I can help offline confirm with Azure teams on the latter and update here accordingly. 

As for explanation on why I mentioned "technically safe" above, please refer to [this comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/24036#issuecomment-1851296182) I commented in another issue.

**Comment by lsorber** [comment]
> To ensure it's technically safe to have Terraform AzureRM support this feature, I may suggest either wait for this feature appear in the Azure service stable API version or the Azure service team could confirm that preview API version could be regarded as same bar of stable APIs. I can help offline confirm with Azure teams on the latter and update here accordingly.

Any news on this @mybayern1974?

**Comment by mybayern1974** [comment]
@lsorber and all, we just got updates from the Azure Cosmos DB service team that this feature is still in preview and there is possibility there would be breaking changes related with this feature. When this feature could be stable is still under evaluation. The service team honors users' expectation to this feature in this provider, so evaluating the GA timeline of this feature is one of their priorities though there is not a timeline explicitly shared now. 
With all above, my previous [comment](https://github.com/hashicorp/terraform-provider-azurerm/issues/24161#issuecomment-1864389734) does not change. Furthermore, I've shared this GH issue with the service team so let's see whether contacts from the service team could share more details here if there are.

**Comment by em-le-ts** [comment]
+1

**Comment by philippencal** [comment]
+1

**Comment by j0eyWh** [comment]
+1

**Comment by j0eyWh** [comment]
+1

**Comment by maxe34** [comment]
+1

**Comment by jvalteren** [comment]
+1

**Comment by grisa2467** [comment]
+1

**Comment by IrfanSyed-PSC** [comment]
Any update on this feature ? vCore is not preview anymore in Cosmos.

**Comment by ivan-zaitsev** [comment]
Any update on this feature?

**Comment by igabi** [comment]
This [MR](https://github.com/Azure/azure-rest-api-specs/pull/27733) has been merged and "Azure Cosmos DB for MongoDB vCore" is no longer listed in the [latest preview ](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2024-05-15-preview/cosmos-db.json). [mybayern1974](https://github.com/mybayern1974)

**Comment by sinbai** [comment]
Hi @igabi, thanks for the updates. The `mongoCluster.json` has indeed been removed from the [latest preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/preview/2024-05-15-preview), however, I assume that the `mongoCluster.json` was just moved to [another folder](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/mongocluster/resource-manager/Microsoft.DocumentDB/preview/2024-03-01-preview/mongoCluster.json), which is still in preview. Also, I did not find `mongoCluster.json` available in any stable API version. Please feel free let us know if you find it in a stable API version, thanks.

**Comment by luansilvacit** [comment]
Hello, any update on this feature?

**Comment by budleigh** [comment]
bump for feature.

**Comment by saulfm08** [comment]
This makes me very upset. vcore not enabled and the RU latest supported is v6

**Comment by mybayern1974** [comment]
@saulfm08 , as well as to all here who expect this feature, with understanding your expectation, I however suggest or to say share transparency that the feature expectation is not at Terraform right now, instead, at the upstream service (API). Per commented above as [here ](https://github.com/hashicorp/terraform-provider-azurerm/issues/24161#issuecomment-1905211492)and [here ](https://github.com/hashicorp/terraform-provider-azurerm/issues/24161#issuecomment-2148765895)in this thread, this feature is not presented in a stable API version (per our latest observation, or anyone please correct me if you observe this feature appear in any stable service API version) but only a preview version, and there is a risk for Terraform to support preview features (reason has also been provided [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/24036#issuecomment-1851296182)). Furthermore, worth to mention, in one of my previous ticket filed to the target service team, they indicated it's possible the current preview API hosting this expected feature may introduce breaking change from their next stable API versions, if that happened, users who would have felt comfortable to get this feature in TF consuming the preview API version is possible to run into trouble when TF would have found TF cannot smoothly consume the next stable API version, which could include more wanted features by users, for that new API would be not backward compatible.

With above, I would suggest people who expect this feature in TF to file a ticket to target service team to consult their stable API release timeline (indeed, I did that recently with getting a response that it would come out soon though no concrete ETA provided)

**Comment by KOConchobhair** [comment]
I just came across this in case it helps anyone
>Full support for Terraform is targetted for the second half of 2024.
https://learn.microsoft.com/en-us/azure/cosmos-db/mongodb/vcore/quickstart-terraform

**Comment by nick4fake** [comment]
@stephybun  sorry, but how exactly that PR closes this issue? How can we manage vCore clusters?

**Comment by StefanSchoof** [comment]
I think there was an mixup. The PR closing this is https://github.com/hashicorp/terraform-provider-azurerm/pull/27636
