### ISSUE TITLE
[Docs Issue] Filtering for "sas" in Docs does not return storage_account_blob_container_sas

### ISSUE THREAD

**Issue by fishfacemcgee** [hashicorp/terraform-provider-azurerm#24189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

Irrelevant

### AzureRM Provider Version

Irrelevant (Latest version/3.84.0 on docs page)

### Affected Resource(s)/Data Source(s)

Irrelevant

### Terraform Configuration Files

```hcl
Irrelevant
```

### Debug Output/Panic Output

```shell
Irrelevant
```

### Expected Behaviour

Filtering for "sas" in the documentation filter should return **all** resources that, at the very least, contain "sas" in their resource name.

### Actual Behaviour

<img width="368" alt="Screen Shot 2023-12-11 at 3 16 05 PM" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1767723/c9e47e87-50b0-481d-9d1e-af86151a0954">

`storage_account_blob_container_sas` is not listed under Storage's Data Sources, despite it being visible when searching for "container".

<img width="359" alt="Screen Shot 2023-12-11 at 3 17 26 PM" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1767723/178e7f4c-5809-404f-a2ea-d031d0375b0d">

### Steps to Reproduce

1. Go to https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs
2. Click on the filter box
3. Type in `sas`

**Comment by rcskosir** [comment]
@fishfacemcgee Thank you for taking the time to report this issue. 
The filer functionality is not maintained by the AzureRM repo but is maintained by the registry team which does not have a public github. I have gone ahead and opened an internal report with the registry team for this issue. I am going to mark this issue as closed here, since there is nothing to be updated in this repo. 
Thanks again!
