### ISSUE TITLE
Support for KataCCIsolation as `workload_runtime` in `kubernetes_cluster_node_pool`

### ISSUE THREAD

**Issue by katexochen** [hashicorp/terraform-provider-azurerm#24196]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Confidential Containers on AKS can be currently used over the CLI via 

```
az aks nodepool add --workload-runtime KataCcIsolation ...
```

would be nice if we could use this via terraform

### New or Affected Resource(s)/Data Source(s)

kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "example" {
  workload_runtime = "KataCCIsolation"
  ...
}
```

### References

https://learn.microsoft.com/en-us/azure/aks/confidential-containers-overview

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
