### ISSUE TITLE
Adding one node and one zone to existing AKS nodepool will delete existing nodes?

### ISSUE THREAD

**Issue by mailbox171** [hashicorp/terraform-provider-azurerm#24215]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
OLD
---
node_count              = 1
zones                   = [1]

NEW
---
node_count              = 2
zones                   = [1,3]
```

### Debug Output/Panic Output

```shell
n/a

Not applied yet
```

### Expected Behaviour

I would expect a new node is created in zone 3

### Actual Behaviour

Documentation say the following. Is it accurate? Will existing node be deleted?
Thanks a lot.

[zones] (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster_node_pool#zones) - (Optional) Specifies a list of Availability Zones in which this Kubernetes Cluster Node Pool should be located. Changing this forces a new Kubernetes Cluster Node Pool to be created.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
