### ISSUE TITLE
Updating the hub_profile property dns_prefix does not re-create the azurerm_kubernetes_fleet_manager

### ISSUE THREAD

**Issue by penicaudm** [hashicorp/terraform-provider-azurerm#24212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_fleet_manager

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg" {
  location = var.location
  name     = "WE-EMEA-RG-AKS_Management"
  tags     = var.tags
}

resource "azurerm_kubernetes_fleet_manager" "fleet" {
  location            = azurerm_resource_group.rg.location
  name                = "fleet_management"
  resource_group_name = azurerm_resource_group.rg.name
  hub_profile {  
    dns_prefix = "dns_prefix"
  }
  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
Error: updating Fleet (Subscription: "sub_id"
│ Resource Group Name: "rg_name"
│ Fleet Name: "fleet_name"): performing CreateOrUpdate: fleets.FleetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing immutable/read-only properties is not allowed: HubProfile.DnsPrefix (old_dns_name-> new_dns_name). Resource ID: \"/subscriptions/subscription_id/resourceGroups/rg_name/providers/Microsoft.ContainerService/fleets/fleet_name\".│ 
│   with module.aks_fleet_manager.azurerm_kubernetes_fleet_manager.fleet,
│   on Modules/aks_fleet_manager/main.tf line 7, in resource "azurerm_kubernetes_fleet_manager" "fleet":
│    7: resource "azurerm_kubernetes_fleet_manager" "fleet" {
│ 
│ updating Fleet (Subscription: "sub_id"
│ Resource Group Name: "rg_name"
│ Fleet Name: "fleet_name"): performing CreateOrUpdate:
│ fleets.FleetsClient#CreateOrUpdate: Failure sending request: StatusCode=0
│ -- Original Error: Code="PropertyChangeNotAllowed" Message="Changing
│ immutable/read-only properties is not allowed: HubProfile.DnsPrefix
│ (old_dns_name -> new_prefix_name).
```

### Expected Behaviour

Updating the dns_prefix property should re-create the resource, since it's a property that cannot be changed, therefore it should prompt for recreation. 

### Actual Behaviour

The provider tries to do an in-place update of the resource

```hcl
  # module.aks_fleet_manager.azurerm_kubernetes_fleet_manager.fleet will be updated in-place
  ~ resource "azurerm_kubernetes_fleet_manager" "fleet" {
        id                  = resource.id
        name                = "fleet_name"
      ~ tags                = {} -> (known after apply)
        # (2 unchanged attributes hidden)

      ~ hub_profile {
          ~ dns_prefix         = "old_dns_prefix" -> "new_dns_prefix"
            # (2 unchanged attributes hidden)
        }
    }

```

### Steps to Reproduce

2. Update the DNS prefix property of the hub_profile block
3. terraform plan
4. Terraform Apply

**Comment by stephybun** [comment]
Thanks for taking the time to raise this issue @penicaudm.

At request of the MSFT service team that manages the fleet resources we will be deprecating and removing support for the `hub_profile` block in the resource, you can find more details on this over on #25010. The main reason given is that there is [no SLA for resources created with `hub_profile` settings since it is a preview feature](https://learn.microsoft.com/en-us/azure/kubernetes-fleet/architectural-overview).

I'm going to close this issue since the property will no longer be functional in the resource.
