### ISSUE TITLE
Changing AzureRM policy definition parameters fails.

### ISSUE THREAD

**Issue by KimShepherdVibrato** [hashicorp/terraform-provider-azurerm#2422]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.10
azurerm 1.19.0

### Affected Resource(s)

azurerm_policy_definition

### Terraform Configuration Files

```hcl
resource "azurerm_policy_definition" "tagging" {
  name         = "resource-tagging-policy"
  policy_type  = "Custom"
  mode         = "Indexed"
  display_name = "Resource Tagging Policy"
  policy_rule  = "${file("./policies/tagging.rules.json")}"
  parameters   = "${file("./policies/tagging.params.json")}"
}
```

### Debug Output

2018-11-30T02:15:19.6634162Z Error: Error applying plan:
2018-11-30T02:15:19.6634200Z 
2018-11-30T02:15:19.6634239Z 1 error(s) occurred:
2018-11-30T02:15:19.6634268Z 
2018-11-30T02:15:19.6634362Z * azurerm_policy_definition.tagging: 1 error(s) occurred:
2018-11-30T02:15:19.6634394Z 
2018-11-30T02:15:19.6635771Z * azurerm_policy_definition.tagging: policy.DefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidPolicyParameterUpdate" Message="The existing policy parameter(s) 'costCentreTagName' were not found in the policy being updated. The parameter names can not be changed."

### Expected Behavior

When changing the parameters for a azurerm_policy_definition, the resource should be destroyed and recreated.

### Actual Behavior

400 status code, applying the configuration failed since azurerm attempts to apply the new parameters to the existing policy, which is not allowed.

### Steps to Reproduce

1. Create an azurerm_policy_definition with parameters.
2. terraform apply
3. Change the parameter definition
4 . terraform apply

**Comment by KimShepherdVibrato** [comment]
As a workaround, I have created a random string with a keeper which will force destruction whenever I change policy parameters.

```HCL
resource "random_string" "tagging_policy" {
  length  = 4
  special = false

  keepers = {
    parameters = "${file("./policies/tagging.params.json")}"
  }
}

resource "azurerm_policy_definition" "tagging" {
  name         = "resource-tagging-policy-${random_string.tagging_policy.result}"
  policy_type  = "Custom"
  mode         = "Indexed"
  display_name = "Resource Tagging Restriction Policy"
  policy_rule  = "${file("./policies/tagging.rules.json")}"
  parameters   = "${random_string.tagging_policy.keepers.parameters}"
}
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
