### ISSUE TITLE
Error deploying `azurerm_storage_account` when specifying the `allow_nested_items_to_be_public` property

### ISSUE THREAD

**Issue by springcomp** [hashicorp/terraform-provider-azurerm#24220]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.84

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
[main.tf](https://gist.github.com/springcomp/4226d77975bedf0b57ac89ca0cc34021#file-main-tf])
```

### Debug Output/Panic Output

```shell
[tf.log](https://gist.github.com/springcomp/4226d77975bedf0b57ac89ca0cc34021#file-tf-log)

**Extract**

╷
│ Error: retrieving static website properties for Storage Account (Subscription: "subscription-identifier"
│ Resource Group Name: "resource-group-name"
│ Storage Account Name: "storage-account-name"): accounts.Client#GetServiceProperties: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: 
Service returned an error. Status=404 Code="ResourceNotFound" Message="The specified resource does not exist.\nRequestId:01fa7a5d-201e-0066-47cd-2d0e39000000\nTime:2023-12-13T14:08:12.4825519Z"
│
│   with azurerm_storage_account.storage,
│   on main.tf line 19, in resource "azurerm_storage_account" "storage":
│   19: resource "azurerm_storage_account" "storage" {
│
```

### Expected Behaviour

It should work 😏

### Actual Behaviour

It does not 😥

**Comment by magodo** [comment]
@springcomp Suspiciously this is because you are recreating a storage account with the same name, in which case the data plane endpoint that the SA TF resource will try to reach to is not ready due to DNS propagation (TTL).

**Comment by springcomp** [comment]
@magodo unfortunately no.

This issue happens every time, on the first try, for brand new named storage accounts.

**Comment by magodo** [comment]
Did you use private endpoint, or there are any network policy/rule to block data plane access? This probably duplicates to issue #2977.

**Comment by springcomp** [comment]
@magodo  thanks for your help.

You are right, there was a network rule.
Cheers.
