### ISSUE TITLE
azurerm_bot_service_azure_bot  public_network_access_enabled always refreshing as false and showing in plan.  Also missing from docs

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azurerm#24242]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.84.0

### Affected Resource(s)/Data Source(s)

azurerm_bot_service_azure_bot

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_application_insights" "example" {
  name                = "example-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

resource "azurerm_application_insights_api_key" "example" {
  name                    = "example-appinsightsapikey"
  application_insights_id = azurerm_application_insights.example.id
  read_permissions        = ["aggregate", "api", "draft", "extendqueries", "search"]
}

data "azurerm_client_config" "current" {}

resource "azurerm_bot_service_azure_bot" "example" {
  name                = "exampleazurebot"
  resource_group_name = azurerm_resource_group.example.name
  location            = "global"
  microsoft_app_id    = data.azurerm_client_config.current.client_id
  sku                 = "F0"

  endpoint                              = "https://example.com"
  developer_app_insights_api_key        = azurerm_application_insights_api_key.example.api_key
  developer_app_insights_application_id = azurerm_application_insights.example.app_id

  tags = {
    environment = "test"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

my bots have public network access enabled in the portal
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1514496/f230dd03-fa67-4108-97b0-4b2fa4713e38)

and it shows enabled in the resource explorer
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1514496/bd38da73-a088-40b4-807b-21ac0c603550)

and it shows as enabled in the response to the GET request during state refresh
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1514496/d3848cb6-42c8-4b3d-9a54-7deae81fe6c4)

so i expect it to show no changes in my plan

and if i apply, i expect no subsequent changes

also i expected this new prop to be documented at  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_service_azure_bot

### Actual Behaviour

it shows a change in my plan
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1514496/0bd92c83-a99e-45ff-b862-31972d4c795d)

applying this change has no effect, the next plan shows the same

also attribute was not documented at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/bot_service_azure_bot

### Important Factoids

maybe since the value in azure is "Enabled" and not more bool friendly provider is converting that to false always?

### References

feature requested with #23572 (note PR did not mention this ticket, and ticket was not closed)

introduced with #24125

**Comment by harshavmb** [comment]
Hi @drdamour ,

You could follow #24242 for more details.

**Comment by drdamour** [comment]
@catriona-m @harshavmb  this got closed, but changes don't appear to fix the missing docs part of this bug report
