### ISSUE TITLE
azurerm_windows_virtual_machine identity_ids should also work with SystemAssigned identities

### ISSUE THREAD

**Issue by theTPH** [hashicorp/terraform-provider-azurerm#24244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hi all, 
It is currently not possible to set the `identity_ids`  in an `identity` block of the `azurerm_windows_virtual_machine` when the identity `type` is set to "SystemAssigned".  It will throw the following error message:

> Error: expanding `identity`: `identity_ids` can only be specified when `type` is set to "SystemAssigned, UserAssigned" or "UserAssigned"

It would be great if we could set identity_ids also with the type "SystemAssigned" and then just be able to set its value to null. This would greatly improve the creation of modules that need to be able to create vms with "SystemAssigned" or "UserAssigned" managed identities. This would allow a module to look like this:

```
resource "azurerm_windows_virtual_machine" "vm" {
  count                 = var.vm_count
  name                  = "${local.vm_name}${count.index + 1}"
  {...}

  identity {
    type            = var.identity_type
    identity_ids = var.identity_ids
  }
}
```

### New or Affected Resource(s)/Data Source(s)

azurerm_windows_virtual_machine

**Comment by harshavmb** [comment]
Hi @theTPH ,

I've below configuration & it works fine with my `vm-module`.

```shell
variable "identity_ids" {
  description = "List of user identity_ids you would like to attach to the VM. Refer https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview for more details. By default, system managed identity is assigned to VM"
  type        = list(any)
  default     = []
}
```

TF code ::
```shell
## Create managed identity, you could even improvise for SystemAssignedUserAssigned too (not covered below)
  identity {
    type         = length(var.identity_ids) > 0 ? "UserAssigned" : "SystemAssigned"
    identity_ids = var.identity_ids
  }
```

The error you point is indeed a valid scenario, one must not pass non-empty list of `identity_ids` with `SystemAssigned`. It's not accepted by API hence `azurerm` provider has this validation. The snippet is [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/vendor/github.com/hashicorp/go-azure-helpers/resourcemanager/identity/system_and_user_assigned_map.go#L80-L82). 

If you are passing `SystemAssigned`, just pass an empty list of `identity_ids`. It should be okay.

**Comment by mybayern1974** [comment]
@theTPH thank you for opening this issue. With assuming harshavmb's response (thank harshavmb for your response!) could unblock this issue, I'm closing this issue. Feel free to suggest to re-activate if you have further questions.
