### ISSUE TITLE
azurerm_automation_module is not supporting Powershell 7.2 runtime

### ISSUE THREAD

**Issue by WiljanD** [hashicorp/terraform-provider-azurerm#24252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5.

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_module

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_automation_account" "example" {
  name                = "account1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_module" "example" {
  name                    = "PnP.PowerShell"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/PnP.PowerShell"
  }
}
```

### Debug Output/Panic Output

```shell
Module Name: "PnP.PowerShell") to finish provisioning: Orchestrator.Shared.AsyncModuleImport.ModuleImportException: An error occurred when trying to import the module to an internal PowerShell session. Either the module dependencies are not imported correctly or the module is unsupported. Internal Error Message: The version of Windows PowerShell on this computer is '5.1.15063.726'. The module 'C:\Users\Client\Temp\OCVWRXXUPN\PnP.PowerShell\PnP.PowerShell.psd1' requires a minimum Windows PowerShell version of '7.2' to run. Verify that you have the minimum required version of Windows PowerShell installed, and then try again.
```

### Expected Behaviour

resource "azurerm_automation_module" "example" {
  name                    = "PnP.PowerShell"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  runtime_version = "Powershell72"

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/PnP.PowerShell"
  }
}
<img width="540" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/109344602/5865b0dc-fc12-4576-93be-590d6666c8ce">

### Actual Behaviour

Module did not install because I couldn't change the runtime of the module.

### Steps to Reproduce

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_automation_account" "example" {
  name                = "account1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "Basic"
}

resource "azurerm_automation_module" "example" {
  name                    = "PnP.PowerShell"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/PnP.PowerShell"
  }
}

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14089
Issue is fixed on Automation Account Runbooks, not in Automation Account Modules

**Comment by varnav** [comment]
It is a separate resource:

https://learn.microsoft.com/en-us/rest/api/automation/powershell72module?view=rest-automation-2023-11-01

So theoretical code would look like this:

```
resource "azurerm_automation_powershell72module" "example" {
  name                    = "PnP.PowerShell"
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name

  module_link {
    uri = "https://www.powershellgallery.com/api/v2/package/PnP.PowerShell"
  }
}
```

**Comment by webstean** [comment]
You can use this in the interim:
resource "azapi_resource" "powercli" {
  for_each = azurerm_automation_account.automation

  type = "Microsoft.Automation/automationAccounts/modules@2022-08-08"

  name                    = "VMware.PowerCLI"
  location                = each.value.location
  parent_id               = each.value.id
  tags                    = each.value.tags   
  body = jsonencode({
    properties = {
      contentLink = {
        uri = "https://www.powershellgallery.com/api/v2/package/VMware.PowerCLI/"
        version = "7.2"
      }
    }
  })
}

**Comment by webstean** [comment]
Great stuff - Thank you - it works great.
