### ISSUE TITLE
mssql_database creation fails when there is a policy which checks transparent data encryption

### ISSUE THREAD

**Issue by strakh-alex** [hashicorp/terraform-provider-azurerm#24253]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.10

### AzureRM Provider Version

3.82.0+

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_database" "example" {
  name           = "example-db"
  server_id      = azurerm_mssql_server.example.id
  collation      = "SQL_Latin1_General_CP1_CI_AS"
  license_type   = "LicenseIncluded"
  max_size_gb    = 4
  read_scale     = true
  sku_name       = "S0"
  zone_redundant = true
  enclave_type   = "VBS"

  transparent_data_encryption_enabled = true
}
```

### Debug Output/Panic Output

```shell
"While enabling Transparent Data Encryption... Unexpected status 403: Request disallowed by policy..."
```

### Steps to Reproduce

We have an Azure Policy which prevents MSSQL databases from being created without TDE enabled.
As I noticed from the debug log, `azurerm` creates an MSSQL database sending 2 PUT requests:
- one for the database itself
- second for enabling TDE
The Azure policy blocks the database immediately preventing the 2nd request from finishing successfully.

Is it possible to change the behaviour and create a database with TDE in one request?

### Important Factoids

This issue is introduced from version 3.82.0 after https://github.com/hashicorp/terraform-provider-azurerm/pull/23721

### Workaround

User azurerm version =< 3.81.0

**Comment by WodansSon** [comment]
Hi @strakh-alex, I believe this issue was fixed in `v3.56.0` of the provider with [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/21704), is there something that I am missing here?

**Comment by strakh-alex** [comment]
> Hi @strakh-alex, I believe this issue was fixed in `v3.56.0` of the provider with [PR #21704](https://github.com/hashicorp/terraform-provider-azurerm/pull/21704), is there something that I am missing here? Based on your configuration it appears this is for the `azurerm_mssql_database` resource and not the `azurerm_mssql_server` resource which was fixed in the above mentioned PR? It was my understanding that only the server needed to be changed for this behavior, so does the same fix need to be introduced to the database as well? I am assuming so, but am asking the question anyways for clarification. 🙂

This issue returned from version 3.82.0 after [azurerm_mssql_server and azurerm_mssql_database - upgrade from v5.0/sql to 2023-02-01-preview](https://github.com/hashicorp/terraform-provider-azurerm/pull/23721)

**Comment by dkuzmenok** [comment]
@WodansSon I think latest API that we now use for mssql allows to set TDE properties for database creation, so there is no need to apply TDE afterwards.

Do you know if anyone is working on this issue? We can try to make it and contribute with a fix.

**Comment by WodansSon** [comment]
@dkuzmenok, I am not aware of anyone currently working on this issue (for the database creation), as most of the engineering staff are currently out for the holidays. IIRC I think that bit of information, was not clearly communicated or known when the original fix for TDE during create was introduced into the provider, the focus at that time was to allow the server specifically, to be able to be created with TDE enabled in one PUT instead of two. If you have time and bandwidth to add this functionality to the database, by all means feel free to open a PR referencing this issue, we love to see, and encourage, community contributions to the provider! 🙂
