### ISSUE TITLE
Container Apps Environment update causes AppLogsConfiguration to be set to null

### ISSUE THREAD

**Issue by EvaDonnermayer** [hashicorp/terraform-provider-azurerm#24283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.5

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
resource "azurerm_container_app_environment" "main" {
  name                           = format("ae-env%s-%s-%s", var.env, var.sub, var.location_short)
  location                       = var.location
  resource_group_name            = var.resource_group_name
  infrastructure_subnet_id       = var.infrastructure_subnet_id
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.main.id
  internal_load_balancer_enabled = var.internal_load_balancer_enabled
  tags                           = var.tags
}

resource "azurerm_log_analytics_workspace" "main" {
  name                = format("law-env%s-%s-%s", var.env, var.sub, var.location_short)
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags
}
```

### Debug Output/Panic Output

```shell
I deploy both resources and everything is fine, Log Analytics Workspace is set in the Container Apps Environment.
When I now change e.g. the tags of the Container Apps Environment and run tf apply again, not only the tags are updated, but also the Log Analytics Workspace is removed from the Container Apps Environment:

 "appLogsConfiguration": {
            "destination": null,
            "logAnalyticsConfiguration": null
        },

Terraform plan and apply do not show this change.

Supposition of the cause:
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containerapps/container_app_environment_resource.go Line 356:

existing.Model.Properties.AppLogsConfiguration = nil
```

### Expected Behaviour

- Update the tags
- Don't change anything else

### Actual Behaviour

- Updated tags
- Also updated: appLogsConfiguration.logAnalyticsConfiguration is set to null.

### Steps to Reproduce

- Terraform apply
- Change the tags
- Terraform apply again

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24303 created for this issue.

**Comment by tgolly** [comment]
Hi. Could this also be the reason `terraform import` doesn't seem to import the `log_analytics_workspace_id` configuration? 

I have an existing container apps environment I'm trying to import, it has log analytics set up, but performing and update after importing it says it's going to destroy my environment because it needs to "add" the `log_analytics_workspace_id` as a new attribute.  

~~~
        location                         = "australiaeast"
      + log_analytics_workspace_id       = "/subscriptions/xxx/xxx/xxx/xxx1" # forces replacement
        name                             = "xxxx"
~~~

But if it had correctly imported that config, it woudn't consider it an update.

Will PR #24303 also fix this issue?

**Comment by mbfrahry** [comment]
Hi @tgolly, unfortunately #24303 will not fix this issue when importing. The Azure API does not return something we can set into state. 

What we do, is take the log analytics id and do a Get call to figure out the customerId and sharedKey and pass that to the azure api like so

```
"logAnalyticsConfiguration": {
	"customerId": "XXXX-XXXX-XXXX",
	"sharedKey": "aSharedKey=="
}
```

And then Azure returns the following back.

```
"logAnalyticsConfiguration": {
	"customerId": "XXXX-XXXX-XXXX",
	"sharedKey": null
}
```

Unfortunately, there isn't enough information returned from the api to be able to set the `log_analytics_id` during an import.

**Comment by tgolly** [comment]
OK no worries @mbfrahry .  I do appreciate the detailed explanation, thanks!
