### ISSUE TITLE
azurerm_orchestrated_virtual_machine_scale_set support for additional_unattend_content

### ISSUE THREAD

**Issue by gibbcode** [hashicorp/terraform-provider-azurerm#24282]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Both `azurerm_windows_virtual_machine` and `azurerm_windows_virtual_machine_scale_set` offer the option to specify `additional_unattend_content`. 

This option is available in ARM for flexible VMSS `azurerm_orchestrated_virtual_machine_scale_set`, but is not available in Terraform.

This prevents consumers from executing custom_data after a VM build.

### New or Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_orchestrated_virtual_machine_scale_set" "vmss" {
  resource_group_name         = azurerm_resource_group.rg.name
  name                        = var.name
  location                    = var.location
  instances                   = var.vmss_instances
  tags                        = local.tags

  os_profile {
    custom_data = base64encode(module.rds-init.rendered)
    windows_configuration {
      admin_username           = "azureuser"
      admin_password           = sensitive(data.azurerm_key_vault_secret.admin-password.value)
      computer_name_prefix     = substr(var.name,0,9)
      additional_unattend_content {
         content = var.content
         setting = var.setting
      }
    }
  }
```

### References

Param available in [azurerm_windows_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#additional_unattend_content) and [azurerm_windows_virtual_machine_scale_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine_scale_set#additional_unattend_content)

But not in [azurerm_orchestrated_virtual_machine_scale_set](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/orchestrated_virtual_machine_scale_set)

**Comment by harshavmb** [comment]
Hi @gibbcode ,

Unfortunately, I couldn't get this working! I am having problems with `Autounattend.xml`. I tried with several contents, all I get is below error which doesn't tell much. I doubt it's even supported by azure API as I see several comments [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/9b5f37e56a061942d949eaf6f2ac6265afb02ce7/internal/services/compute/orchestrated_virtual_machine_scale_set.go#L68-L69). I have had similar experience with flex orchestration APIs not having all feature support like uniform mode.

In case if you have a working xml, please share with me. Have you tested with by other means like `az-cli`/`restapi`? I couldn't test this via portal as no option was offered. 

> Error: waiting for creation of Orchestrated Virtual Machine Scale Set (Subscription: "b500a058-6396-45db-a15d-3f31913e84a5"
> │ Resource Group Name: "factory-01"
> │ Virtual Machine Scale Set Name: "acctestOVMSS-01"): Code="OSProvisioningInternalError" Message="OS Provisioning failed for VM 'acctestOVMSS-01_9cec32de' due to an internal error." Target="acctestOVMSS-01_9cec32de"

**Comment by harshavmb** [comment]
No problem, I got it working with below configuration..

```
additional_unattend_content {        
        setting = "FirstLogonCommands"
        content = "<FirstLogonCommands><SynchronousCommand><CommandLine>shutdown /r /t 0 /c \"initial reboot\"</CommandLine><Description>reboot</Description><Order>1</Order></SynchronousCommand></FirstLogonCommands>"        
}
```
