### ISSUE TITLE
Support for exporting identity for a Data Kusto Cluster

### ISSUE THREAD

**Issue by weemel** [hashicorp/terraform-provider-azurerm#24293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

#6854 added the ability to assign a system identity, but the data azurerm_kusto_cluster does not export this information (principal id at the very least). It would be very useful for creating role assignments for an existing cluster.

### New or Affected Resource(s)/Data Source(s)

data azurerm_kusto_cluster

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request!
