### ISSUE TITLE
User Assigned Managed Identity fails with using Azure CLI authentication

### ISSUE THREAD

**Issue by DPatrickBoyd** [hashicorp/terraform-provider-azurerm#24295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  tags = {
    environment = "staging"
  }
}

provider "azurerm" {
  features {}
}

```

### Debug Output/Panic Output

```shell
2023-12-20T13:25:34.497Z [DEBUG] provider.terraform-provider-azurerm_v3.85.0_x5: az-cli invocation: az version -o=json: timestamp=2023-12-20T13:25:34.497Z
2023-12-20T13:25:34.777Z [DEBUG] provider.terraform-provider-azurerm_v3.85.0_x5: az-cli invocation: az account show -o=json: timestamp=2023-12-20T13:25:34.777Z
2023-12-20T13:25:35.162Z [DEBUG] provider.terraform-provider-azurerm_v3.85.0_x5: az-cli invocation: az account get-access-token --scope https://graph.microsoft.com/.default --tenant redactedId -o=json: timestamp=2023-12-20T13:25:35.162Z
Error: -20T13:25:35.608Z [ERROR] provider.terraform-provider-azurerm_v3.85.0_x5: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR tf_provider_addr=provider tf_rpc=Configure @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto tf_proto_version=5.4 tf_req_id=c01699c4-2936-0d46-95e3
diagnostic_summary="building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: Tenant shouldn't be specified for managed identity account" timestamp=2023-12-20T13:25:35.608Z
Error: -20T13:25:35.608Z [ERROR] vertex "provider[\"registry.terraform.io/hashicorp/azurerm\"]" error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: Tenant shouldn't be specified for managed identity account
```

### Expected Behaviour

it should be get the token from the command and then proceed with the terraform

### Actual Behaviour

the planning fails

### Steps to Reproduce

log into az cli using managed identity (in this case it's in a pod in a cluster)
`az login --identity`

terraform init
TF_LOG=DEBUG terraform plan

**Comment by DPatrickBoyd** [comment]
confirmed the same behavior on a vm. I know there are probably other ways of doing this, but according to the documentation
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli this should work

**Comment by magodo** [comment]
@DPatrickBoyd This looks like an error raised from Azure CLI, instead of this provider. Would you mind raise an issue towards https://github.com/Azure/azure-cli? Meanwhile, to auth via MSI, you can follow this guide: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity

**Comment by DPatrickBoyd** [comment]
Hi, this is terraforms provider that is making this request, which provides the incorrect parameter for the request. As it is your provider which is responsible for the incorrect parameter being supplied I feel it should be kept here and the fix would require a change on the provider side. Thank you

**Comment by harshavmb** [comment]
I think the problem is coming from [here](https://github.com/hashicorp/go-azure-sdk/blob/main/sdk/auth/azure_cli_authorizer.go#L71). The `--tenant` argument is skipped for `cloudshell` but not for managed identities. 

In the meantine, a crappy workaround I propose is to fake like a `cloudshell` environment by settting env var `AZUREPS_HOST_ENVIRONMENT=cloud-shell/1.0`.

**Comment by DPatrickBoyd** [comment]
let me try it and I will get back to you, thanks

**Comment by DPatrickBoyd** [comment]
> let me try it and I will get back to you, thanks

looks like that worked for me, but obviously not ideal. thanks for showing me that workaround. For now I think we may go with USE_MSI=TRUE and the client id to auth for now.

This is still an open problem

**Comment by harshavmb** [comment]
Hi @DPatrickBoyd ,

You could follow updates on this issue [here](https://github.com/hashicorp/go-azure-sdk/pull/793). If `hashicorp` merges the linked PR, we could simply bump the version of `go-azure-sdk` to build the `azurerm` provider to have it in usable shape.
