### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert: Scope can not be updated

### ISSUE THREAD

**Issue by alxy** [hashicorp/terraform-provider-azurerm#24304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.4

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    action_group           = []
    email_subject          = "Email Header"
    custom_webhook_payload = "{}"
  }
  data_source_id = azurerm_application_insights.example.id
  description    = "Alert when total results cross threshold"
  enabled        = true
  # Count all requests with server error result code grouped into 5-minute bins
  query       = <<-QUERY
  requests
    | where tolong(resultCode) >= 500
    | summarize count() by bin(timestamp, 5m)
  QUERY
  severity    = 1
  frequency   = 5
  time_window = 30
  trigger {
    operator  = "GreaterThan"
    threshold = 3
  }
  tags = {
    foo = "bar"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: creating or updating Monitor Scheduled Query Rules: (Scheduled Query Rule Name "example-metricalert" / Resource Group "rg-example"): insights.ScheduledQueryRulesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Scope can not be updated"
│ 
│   with azurerm_monitor_scheduled_query_rules_alert.example,
│   on alerts.tf line 21, in resource "azurerm_monitor_scheduled_query_rules_alert" "example":
│   21: resource "azurerm_monitor_scheduled_query_rules_alert" "example" {
```

### Expected Behaviour

Updating the `scopes` property should trigger a re-creation (delete & create) operation, not an update.

### Actual Behaviour

Terraform tries to call the api to modify the resource, however, that seems to be not supported.

### Steps to Reproduce

- Create alert rule with a certain scope
- Update the alert rule to have a different scope
- Notice the error above

**Comment by teowa** [comment]
Hi @alxy , thanks for submitting this!
It might be a mistake that the error message is not consistent with the given Terraform config. Should the [`azurerm_monitor_scheduled_query_rules_alert`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert) be [`azurerm_monitor_metric_alert`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert), for the formaer has no scope field?

**Comment by alxy** [comment]
Yeah sorry, i tried to anonymize this and copied an example from the terraform registry/docs. Looks like I copied from the wrong resource, let me fix it. It does happen for any `azurerm_monitor_scheduled_query_rules_alert` really, if you change the scope. The easy fix for this is btw to chose an entirely different resource name - this will force Terraform to destroy & re-create the alert rule. Which is normally not an issue, since this is not a data storage and its really quick to create/delete.
