### ISSUE TITLE
azurerm_linux_virtual_machine_scale_set does not propogate tags to network interface

### ISSUE THREAD

**Issue by c4milo** [hashicorp/terraform-provider-azurerm#24300]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.6.5

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "redpanda" {
  name                            = "vmss-${var.resource_name_prefix}-${var.redpanda_id}-agent"
  resource_group_name             = data.azurerm_resource_group.redpanda.name
  location                        = local.region
  sku                             = "Standard_B2als_v2"
  instances                       = 1
  admin_username                  = "redpanda"
  admin_password                  = ":)"
  disable_password_authentication = false
  zone_balance                    = true
  zones                           = var.zones

  tags = var.tags

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts"
    version   = "latest"
  }

  os_disk {
    storage_account_type = "Standard_LRS"
    caching              = "ReadWrite"
  }

  network_interface {
    name                          = "nic-${var.resource_name_prefix}-${var.redpanda_id}-agent-001"
    primary                       = true
    enable_accelerated_networking = true

    ip_configuration {
      name      = "private"
      primary   = true
      subnet_id = var.redpanda_agent_public_subnet_id

      public_ip_address {
        name                = "public"
        public_ip_prefix_id = azurerm_public_ip_prefix.redpanda.id
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
None
```

### Expected Behaviour

tags set for `azurerm_linux_virtual_machine_scale_set` propagate to children resources such as the default NIC. 

### Actual Behaviour

Tags are not added for the NIC

### Steps to Reproduce

terraform apply 

### Important Factoids

No

**Comment by pnduati** [comment]
@rcskosir Any update here?

**Comment by tombuildsstuff** [comment]
hey @c4milo 

Thanks for opening this issue.

Taking a look through here this behaviour is coming from the Azure API - as such this would be a feature request for the Service Team to implement [and as such I'd recommend opening an issue here](https://github.com/Azure/azure-rest-api-specs/issues) so that the Service Team can take a look into this. However unfortunately since the Azure API doesn't expose a means of propagating these tags in an automated fashion (e.g. when a new VM is created within the Scale Set), this isn't something we can fix in Terraform without support in the API and as such i'm going to close this issue for the moment.

Thanks!
