### ISSUE TITLE
geo_backup_enabled variable is trying to be set to false with each terraform plan and apply

### ISSUE THREAD

**Issue by ltutar** [hashicorp/terraform-provider-azurerm#24305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Terraform Configuration Files

```hcl
db3 = {
      name                 = "levent-geo-test"
      collation            = "SQL_LATIN1_GENERAL_CP1_CI_AS"
      sku_name             = "S0" //S0 (250gb), P2 (500gb), business critical: GP_S_Gen5_1 (512gb->)
      zone_redundant       = false
      geo_backup_enabled   = false
      storage_account_type = "Local"
    }
```

### Debug Output/Panic Output

```shell
From terraform apply:

2023-12-21T14:23:45.866+0100 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for module.azsql.azurerm_mssql_database.db["db3"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .geo_backup_enabled: was cty.False, but now cty.True
[0m[1mmodule.azsql.azurerm_mssql_database.db["db3"]: Modifications complete after 1m19s [id=/subscriptions/
```

### Expected Behaviour

Locally-redundant backup storage is already selected. Also created in this way as expected from the terraform code.
![Screenshot 2023-12-21 at 14 05 44](https://github.com/hashicorp/terraform-provider-azurerm/assets/7237078/e57384f1-ab9a-415f-a674-9032c79343a9)
I expect the terraform plan to  not see this as a change since the value is already correct.

### Actual Behaviour

But terraform state does not see this and wants to change it from true to false. Apply is also succeeded but the state is not changed. With every terraform plan and apply, we have this issue.

`[1m  # module.azsql.azurerm_mssql_database.db["db3"][0m will be updated in-place
[0m  [33m~[0m[0m resource "azurerm_mssql_database" "db" {
      [33m~[0m[0m geo_backup_enabled                  = true [33m->[0m[0m false
        id                                  = "/subscriptions/resourceGroups/providers/Microsoft.Sql/servers/x/databases/levent-geo-test"
        name                                = "levent-geo-test"
        tags                                = {
            "app"          = "x"
            "changenumber" = "x"
            "contact"      = "x"
            "costcenter"   = "x"
            "environment"  = "dev"
            "expirydate"   = "-"
            "owner"        = "x"
            "tier"         = "5"
        }
        [90m# (14 unchanged attributes hidden)[0m[0m

        [90m# (3 unchanged blocks hidden)[0m[0m
    }`

![Screenshot 2023-12-21 at 14 09 22](https://github.com/hashicorp/terraform-provider-azurerm/assets/7237078/965b8b26-9d01-46d9-a4db-73defe421e1d)

### Steps to Reproduce

terraform plan and apply

**Comment by ltutar** [comment]
I am also posting the trace lines where also the sdk version is printed.
`2023-12-21T16:41:02.824+0100 [TRACE] provider.terraform-provider-azurerm_v3.85.0_x5: Called downstream: @module=sdk.helper_schema tf_req_id=5 tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:920 tf_provider_addr=provider tf_resource_type=azurerm_mssql_database timestamp="2023-12-21T16:41:02.824+0100"
2023-12-21T16:41:02.825+0100 [TRACE] provider.terraform-provider-azurerm_v3.85.0_x5: Received downstream response: tf_resource_type=azurerm_mssql_database tf_rpc=ApplyResourceChange tf_proto_version=5.4 tf_provider_addr=provider @module=sdk.proto diagnostic_warning_count=0 tf_req_duration_ms=78565 tf_req_id=5 @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tf5serverlogging/downstream_request.go:40 diagnostic_error_count=0 timestamp="2023-12-21T16:41:02.824+0100"
2023-12-21T16:41:02.825+0100 [TRACE] provider.terraform-provider-azurerm_v3.85.0_x5: Served request: @module=sdk.proto tf_proto_version=5.4 tf_provider_addr=provider tf_req_id=5 tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:872 tf_resource_type=azurerm_mssql_database timestamp="2023-12-21T16:41:02.825+0100"
2023-12-21T16:41:02.825+0100 [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for module.azsql.azurerm_mssql_database.db["db1"], but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .geo_backup_enabled: was cty.False, but now cty.True`

**Comment by sinbai** [comment]
Hi @ltutar, thanks for opening this issue. Per the information provided, the reason for seeing this change is because `geo_backup_enabled = false` is set in the configuration file. If you do not expect to see this change and do not plan to delete `geo_backup_enabled = false`, it is recommended to use [ignore_change ](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) for `geo_backup_enabled` to ignore this change.

**Comment by sinbai** [comment]
Hi @ltutar Per the following screenshot from the [terraform documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database), "geo_backup_enabled is only applicable for DataWarehouse SKUs (DW*). This setting is ignored for all other SKUs. ". Because the provided tf config ` sku_name= "S0"`, it is recommend that you can delete the configuration or use `ignore_change` to achieve your expectations: expect the terraform plan to not see this as a change.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/f9844228-efac-458a-b563-3b02dfc69cd3)

**Comment by ltutar** [comment]
Thank you very much @sinbai 
I am closing my issue.
