### ISSUE TITLE
TDE with database level customer-managed keys - using TerraformSupport for [thing]

### ISSUE THREAD

**Issue by SnehaniranjanaSR** [hashicorp/terraform-provider-azurerm#24316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I am trying to create my database in azure with TDE with database level customer-managed keys - using Terraform. Need help in achieving that.

I see --encryption-protector $keyid can be used in creation of db using Azure CLI. Is there something similar to use in terraform?

We have azurerm_mssql_server_transparent_data_encryption" for TDE at server level. I am looking for something similar for database level.

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Potential Terraform Configuration

```hcl
resource "azurerm_mssql_database_transparent_data_encryption" "msql_db_tde"{
  server_id        = azurerm_mssql_server.sql_server.id
  database_name = azurerm_mssql_database.databases.name
  key_vault_key_id = data.azurerm_key_vault_key.mssql_db_key.id
}
```

### References

Reference:
https://learn.microsoft.com/en-us/azure/azure-sql/database/transparent-data-encryption-byok-database-level-basic-actions?view=azuresql&tabs=azure-portal%2Cazure-portal2#view-the-database-level-customer-managed-key-settings-on-an-azure-sql-database

**Comment by sinbai** [comment]
Hi @SnehaniranjanaSR thanks for opening this issue. After checking the code, I found the resource `azurerm_mssql_server_transparent_data_encryption` supports `key_vault_key_id ` which depends on [this](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/sql/resource-manager/Microsoft.Sql/preview/2023-02-01-preview/ServerKeys.json) Azure Rest API. However, it seems that the corresponding database level API is not yet visible. Given that Terraform implements the management of Azure resources through the Azure Rest API, so I'm currently assuming that Terraform has no way to support this request. Also, given that I'm not an expert on Azure Rest APIs. It is recommended to open an issue on [this ](https://github.com/Azure/azure-rest-api-specs/issues)repo to confirm whether there is an API that supports this request.

**Comment by SnehaniranjanaSR** [comment]
Thanks @sinbai , I have raised an issue as per your suggestion.

**Comment by SnehaniranjanaSR** [comment]
@sinbai , I am just curious, I just came across this while I was still searching, (https://github.com/Azure/azure-quickstart-templates/tree/master/quickstarts/microsoft.sql/sql-database-transparent-encryption-create) Can you please look into this and see if this might be related?

**Comment by harshavmb** [comment]
Hi @SnehaniranjanaSR,

I don't have any experience with sql server resources on Azure but having looked at the documentation & code I have gotten some understanding. 

`azurerm_mssql_server_transparent_data_encryption` indeed supports `tde` with cmk. If you would like to have the same TDE applied at the database level, it's done automatically you don't need to anything as it's enabled by default. You could see from the provider code [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/mssql/mssql_database_resource.go#L1604-L1607), it's enabled by default. Just that it's not documented. 

However, I do see another possibility of `Database level CMK` which I assume another layer of encryption at the database level in addition to sql server. Would you like to have this? Or you are okay with server level encryption? I do think it's possible to add a new resource similar to `azurerm_mssql_server_transparent_data_encryption`/`azurerm_mssql_managed_instance_transparent_data_encryption` but scoped at the database level.

**Comment by SnehaniranjanaSR** [comment]
@harshavmb , 

I already have done the TDE enabled and CMK at server level, I understand that the server level CMK is defaulted to the Database level. But, What I am trying to achieve is the Additional TDE with CMK at Database level. Where in I am not able to find relevant information online. @sinbai mentioned that the Azure REST API is not available for that feature, So I have crated a request in the specified link. Let me know if you have already explored on this. 

Regards,
Sneha

**Comment by dkuzmenok** [comment]
@harshavmb @SnehaniranjanaSR @sinbai 

With latest API (that we now use - `2023-02-01-preview`) we can now define encryption on database level. 
I am currently finishing the change to bring it into provider code.

I would submit a PR shortly.

**Comment by SnehaniranjanaSR** [comment]
@dkuzmenok, Thanks for the update, Will look forward for the changes.

**Comment by SnehaniranjanaSR** [comment]
@dkuzmenok, Thanks for the quick update. I will work on it to make changes. Will gat back to you if I have questions.

**Comment by SnehaniranjanaSR** [comment]
@dkuzmenok, I am having the version for the providers as below, Please confirm if this is the right version where the latest changes are available?
azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.86.0"
    }
    mssql = {
      source  = "betr-io/mssql"
      version = "0.3.0"
    }

**Comment by dkuzmenok** [comment]
@SnehaniranjanaSR It is not merged and released, so you cannot download it. You can only checkout the branch and compile `terraform-provider-azurerm` if you want to test it before release.

**Comment by SnehaniranjanaSR** [comment]
@dkuzmenok , Do you have an eta on when it will be released, so we can plan our work?

**Comment by dkuzmenok** [comment]
@SnehaniranjanaSR I am not linked to Hashicorp in any way, so I don't know when it would happen. You can subscribe to Merge Request updates to know when it is merged.
