### ISSUE TITLE
Azure Cognitive Deployment Resource Requires Version Field Incorrectly

### ISSUE THREAD

**Issue by tgoodsell-tempus** [hashicorp/terraform-provider-azurerm#24318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_deployment" "model" {

  name                 = "gpt-4-32k"
  cognitive_account_id = "my-azure-cognitive-account-id"
  model {
    format  = "OpenAI"
    name    = "gpt-4-32k"
    # version = "0613"
  }

  scale {
    type     = "Standard"
    capacity = 10
  }
}
```

### Debug Output/Panic Output

```shell
Required attribute "version" not specified: An attribute named "version" is required here
```

### Expected Behaviour

Per the API documentation, the `version` field should be optional: https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/deployments/create-or-update?view=rest-cognitiveservices-accountmanagement-2023-05-01&tabs=HTTP#deploymentmodel

When not passed, Azure automatically assigns the default version for the model at the time. So really this should be both `optional` and `computed`.

### Actual Behaviour

The `version` field is required.

### Steps to Reproduce

1. Create configuration similar to example.
2. Notice how `version` is required.

### References

https://learn.microsoft.com/en-us/rest/api/cognitiveservices/accountmanagement/deployments/create-or-update?view=rest-cognitiveservices-accountmanagement-2023-05-01&tabs=HTTP#deploymentmodel

**Comment by liuwuliuyun** [comment]
Hi @tgoodsell-tempus, thanks for raising this issue. I notice this issue a few days ago and raised PR to fix this. I will link the PR to this issue later. Currently provider design will no longer add new property that is `Optional` and `Computed`. But user could use [ignore_change](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to manually ignore changes in this field.

**Comment by tgoodsell-tempus** [comment]
> Hi @tgoodsell-tempus, thanks for raising this issue. I notice this issue a few days ago and raised PR to fix this. I will link the PR to this issue later. Currently provider design will no longer add new property that is `Optional` and `Computed`. But user could use [ignore_change](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to manually ignore changes in this field.

I'm curious, why is adding properties with both `optional` and `computed` stopped here? That's not something the SDKv2 docs explicitly recomend avoiding or anything (https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#computed).
