### ISSUE TITLE
SQL managed instance 12 core supported in azure but validation script failing the change 

### ISSUE THREAD

**Issue by ashish-antil-eroad** [hashicorp/terraform-provider-azurerm#24338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note
* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.0

### AzureRM Provider Version

3.72.0 

### Affected Resource(s)/Data Source(s)

azurerd_sqlManagedInstance

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_managed_instance" "sqlmi" {
  depends_on = [
    azurerm_subnet_network_security_group_association.sqlmi,
    azurerm_subnet_route_table_association.sqlmi,
  ]

  name                = local.sqlmi_name
  tags                = var.tags
  resource_group_name = var.resource_group_name
  location            = var.resource_group_location

  license_type       = var.sqlmi_license_type
  sku_name           = var.sqlmi_sku_name
  storage_size_in_gb = var.sqlmi_storage_size
  subnet_id          = var.subnet_id
  vcores             = var.sqlmi_vcores

  administrator_login          = local.sqlmi_admin
  administrator_login_password = azurerm_key_vault_secret.sqlmi-password-kv-secret.value

  collation   = "SQL_Latin1_General_CP1_CI_AS"
  timezone_id = "UTC"

  public_data_endpoint_enabled = var.sqlmi_public_data_endpoint_enabled

  dns_zone_partner_id = var.primary_sqlmi_id == "" ? null : var.primary_sqlmi_id

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    prevent_destroy = true
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: expected vcores to be one of [4 8 16 24 32 40 64 80], got 12
│ 
│   with module.sqlmi-main.azurerm_mssql_managed_instance.sqlmi,
│   on modules/sqlmi/main.tf line 50, in resource "azurerm_mssql_managed_instance" "sqlmi":
│   50:   vcores             = var.sqlmi_vcores
```

### Important Factoids

Hi 

We are upgrading SQL Managed instance from 
Service tier: 
**General Purpose (4-80 vCores, 32 GB-16 TB storage capacity, Fast storage) - for most production workloads**
Hardware generation
**Standard-series (Gen 5) - Intel Broadwell, 5,1 GB RAM/vCore**
8 Vcore 

TO 

Service tier   **"Business Critical (4-128 vCores, 32 GB-16 TB storage capacity, Super fast storage) - for IO-intensive and compute-intensive workloads"**
Hardware generation
**Premium-series - Intel Ice Lake, 7 GB RAM/vCore, up to 560 GB**
and 12 vcore 
 

on upgrading the script 
sqlmi_sku_name = "BC_Gen5" -> "BC_Gen8IM"
sqlmi_vcores  = 8 - > 12

I am getting the following error. 
**│ Error: expected vcores to be one of [4 8 16 24 32 40 64 80], got 12**

where on azure portal I am allowed to do so 
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/116608412/bb944505-a9af-4ba2-a083-75f97a35a06a)
on more digging in the provider code base, this code base doesn't have 12, which is supported by azure but missed out in Terraform provider code base. 

https://github.com/hashicorp/terraform-provider-azurerm/blob/ef3c1e68a2c25f2ce5950bb459ef248ed4699171/internal/services/sql/sql_managed_instance_resource.go#L90-L98

**Comment by sinbai** [comment]
Hi @ashish-antil-eroad per [the latest terraform documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_managed_instance#vcores), it seems that the `vcores` has been supported `12`. [Here ](https://github.com/hashicorp/terraform-provider-azurerm/blob/46a95c1b799aca661d980992e65779e8576178e7/internal/services/mssqlmanagedinstance/mssql_managed_instance_resource.go#L136)is the code of resource `azurerm_mssql_managed_instance`. Could you please use the latest Terraform version and try again?

**Comment by harshavmb** [comment]
Hi @sinbai / @mybayern1974 ,

I see similar issues being flagged by users who are not checking the documentation of latest provider versions. Can something be done by displaying error messages etc., to point them to use the newer provider versions rather flagging issues directly here?

**Comment by mybayern1974** [comment]
@harshavmb , re "_displaying error messages etc., to point them to use the newer provider versions..._", I intuitively assume it's hard to implement: it requires a specific old version knows its successor version would have made what is wanted, which however is infeasible unless backporting to that specific old version when a new version comes out. However, there is no backporting mechanism introduced in Terraform AzureRM yet.
With that, I feel that has to depend on users' sensitivity by always proactively subscribing new versions.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @sinbai‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
