### ISSUE TITLE
Support for Minimum Inbound TLS Cipher Suite on Linux WebApp

### ISSUE THREAD

**Issue by vamshisiram** [hashicorp/terraform-provider-azurerm#24337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Enable support for controlling Minimum Inbound TLS Cipher Suite on Linux WebApp via terraform

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

**Comment by xiaxyi** [comment]
Thanks @vamshisiram for raising this issue, the property is introduced in 2023-01-01 api version but Terraform azureRM is still using 2022-09-01. Given the fact that web is a big RP so we need to be careful about API upgrade, the task is already in our backlog now. BTW, there is another user request on this property https://github.com/hashicorp/terraform-provider-azurerm/issues/24223, I will link your issue there and would you mind tracking the status there as well?

**Comment by mybayern1974** [comment]
Per xiaxyi's suggestion, close this issue as dup. Please subscribe #24223 .
