### ISSUE TITLE
Support for NodeJs 20-LTS on Linux WebApp

### ISSUE THREAD

**Issue by vamshisiram** [hashicorp/terraform-provider-azurerm#24348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

MS supports Nodejs version 20-lts or 18-lts for linux webapp via Azure Portal. But, with terraform i am not able to set nodejs 20-lts, i get error as below.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/90816346/a67c824c-f17a-4305-99f7-cfdaa8db3899)

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

```hcl
deploy nodejs with version 20-lts
```

**Comment by xiaxyi** [comment]
@vamshisiram Thanks for raising this issue, the support for node 20 on Linux web app is added in pr https://github.com/hashicorp/terraform-provider-azurerm/pull/24073, you can subscribe it for progress.

**Comment by vamshisiram** [comment]
@xiaxyi Thanks. I have subscribed for the other one for updates.
