### ISSUE TITLE
Support for infrastructureResourceGroup in azurerm_container_app_environment

### ISSUE THREAD

**Issue by ezequielan** [hashicorp/terraform-provider-azurerm#24355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello,
please support infrastructureResourceGroup in azurerm_container_app_environment to specify a managed resource group name in order to comply with naming policies, thank you.

Regards.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app_environment" "example" {
  name                       = "my-environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  managed_resource_group_name = "managed-resource-group-name"
}
```

### References

https://learn.microsoft.com/es-es/azure/templates/microsoft.app/managedenvironments?pivots=deployment-language-terraform#managedenvironmentproperties-2

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24361 created by @aristosvo for this issue.
