### ISSUE TITLE
azurerm_postgresql_flexible_server does not support the SKU name : MO_Standard_E96ds_v5

### ISSUE THREAD

**Issue by Davidh-claranet** [hashicorp/terraform-provider-azurerm#24356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.79

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "example" {
  name                   = "example-psqlflexibleserver"
  resource_group_name    = azurerm_resource_group.example.name
  location               = azurerm_resource_group.example.location
  version                = "12"
  delegated_subnet_id    = azurerm_subnet.example.id
  private_dns_zone_id    = azurerm_private_dns_zone.example.id
  administrator_login    = "psqladmin"
  administrator_password = "H@Sh1CoR3!"
  zone                   = "1"

  storage_mb = 32768

  sku_name   = "MO_Standard_E96ds_v5"
  depends_on = [azurerm_private_dns_zone_virtual_network_link.example]

}
```

### Debug Output/Panic Output

```shell
Error: "sku_name" is not a valid sku name, got MO_Standard_E96ds_v5
```

### Expected Behaviour

The ressource should be created

### Actual Behaviour

Error: "sku_name" is not a valid sku name, got MO_Standard_E96ds_v5

### Steps to Reproduce

But it should work now.

### References

It was removed last year : 
https://github.com/hashicorp/terraform-provider-azurerm/commit/edaa524a8e76f6e451a2c8bb85fea023c6bf2a3d

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. As I mentioned in this [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/19246), service team just confirmed the Standard_E96ds_v5 and Standard_E104ids_v5 aren't ready for now.
