### ISSUE TITLE
Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: could not parse Azure CLI version

### ISSUE THREAD

**Issue by kunalraykar30** [hashicorp/terraform-provider-azurerm#24359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.52.0"
    }
  }
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "example-rg"
  location = "westeurope"
}
```

### Debug Output/Panic Output

```shell
$ gitlab-terraform plan
Initializing the backend...
Successfully configured the backend "http"! Terraform will automatically
use this backend unless the backend configuration changes.
Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "3.52.0"...
- Installing hashicorp/azurerm v3.52.0...
- Installed hashicorp/azurerm v3.52.0 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Terraform has been successfully initialized!
Planning failed. Terraform encountered an error while generating this plan.
╷
│ Error: unable to build authorizer for Resource Manager API: could not configure AzureCli Authorizer: could not parse Azure CLI version: launching Azure CLI: exec: "az": executable file not found in $PATH
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 11, in provider "azurerm":
│   11: provider "azurerm" {
│ 
╵
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: exit code 1
```

### Expected Behaviour

Should have gone through successfully from ```$ terraform plan```

### Actual Behaviour

Failing at the ```$ terraform plan```. Tried from the local desktop and it's working fine. 
I also tried with "use_cli = false" option but results are same. 

Little info about setup - 
Using gitlab-ci.yml to create resouces on Azure cloud while backend is stored in Gitlab itself. 

Below variables are already created in the CICD section of the gitlab - 

ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_TENANT_ID
ARM_SUBSCRIPTION_ID

### Steps to Reproduce

With version of azurerm - 3.51.0. Also, tried with lower version still error is same.

**Comment by harshavmb** [comment]
Hi @kunalraykar30 ,

This appears to be due to incorrect setup of `CI/CD`. Below is the authorizer preference..

> // Authorizers are selected for authentication methods in the following preferential order:
// - Client certificate authentication
// - Client secret authentication
// - OIDC authentication
// - GitHub OIDC authentication
// - MSI authentication
// - Azure CLI authentication

The fact of disabling `use_cli` is trivial here as the other authorizers were tried & failed. I assume `ARM_*` env vars doesn't seem to available during `terraform` execution. You could try printing `env` vars just before `gitlab-terraform plan`. 

If you see the `ARM_*` env vars available before `gitlab-terraform plan`, please share the debug logs by redacting sensitive info by applying `TF_LOG=debug` before terraform commands.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @harshavmb‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue and the debug logs by redacting sensitive info by applying TF_LOG=debug before terraform commands, thanks!
