### ISSUE TITLE
Support for `vmTemplate` in `azurerm_virtual_desktop_host_pool`

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#24358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

There doesn't appear to be support for `vmTemplate` property in a `azurerm_virtual_desktop_host_pool`

Allows the host pool to create VMs dynamically during ramp up.

Some Details...

https://learn.microsoft.com/en-us/rest/api/desktopvirtualization/host-pools/get?view=rest-desktopvirtualization-2022-02-10-preview&tabs=HTTP

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/112259176/d6ebad1a-ed69-4fd8-b80b-8ebd3de91eaa)

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_host_pool

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24358 for this issue.

**Comment by harshavmb** [comment]
Hi @DevopsMercenary ,

Do you have a sample `vmTemplate` you could share here? Apparently I couldn't find documentation. This is for adding a test case for this change.
