### ISSUE TITLE
azurerm_application_insights_*_test creates hidden tag that always reflects a "change" (when inside modules)

### ISSUE THREAD

**Issue by joaocc** [hashicorp/terraform-provider-azurerm#24371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

This is a reopen of several related issues, as I understand that the proposed workarounds do not work for more complex cases where the resources are created inside a module, and as such, prevents the use lifecycle.ignore_changes with dynamic tags.
* https://github.com/hashicorp/terraform-provider-azurerm/issues/16569
* https://github.com/hashicorp/terraform-provider-azurerm/issues/7026
* https://github.com/hashicorp/terraform-provider-azurerm/pull/7125

In these cases, the proposed workaround is to specify lifecycle.ignore_changes to something like 
```
    ignore_changes = [
      tags["hidden-link: /app-insights-instrumentation-key"],
      tags["hidden-link: /app-insights-resource-id"]
    ]
```

However, in `azurerm_application_insights_standard_web_test`, the tag in question is more complex:
`hidden-link:/subscriptions/0000-...-0000/resourceGroups/MySubName/providers/microsoft.insights/components/MyApInsightName`

If the `application_insights_standard_web_test` resource is created inside a module, and called from different contexts, it doesn't seem to be possible to use this approach, as the `lifecycle.ignore_changes` requires dynamically calculating the index to tags-to-ignore, which results in:
```
│ Error: Invalid expression
│ 
│   on ../../../azure/app_insights/main.tf line 77, in resource "azurerm_application_insights_standard_web_test" "this":
│   77:       tags[local._workaround_tags_hidden_link]
│ 
│ A single static variable reference is required: only attribute access and
│ indexing with constant keys. No calculations, function calls, template
│ expressions, etc are allowed here.
```
The example for this message was something like:
```
locals {
  _workaround_tags_hidden_link = format(
    "hidden-link:/subscriptions/%s/resourceGroups/%s/providers/Microsoft.Insights/components/%s",
    var.app_insights_sub_id,
    var.app_insights_rg,
    var.app_insights_name
  )
}
...
    ignore_changes = [
      tags[local._workaround_tags_hidden_link]
    ]
```

We would kindly ask for a workaround that could be used in this use case or, if confirmed that our understanding is correct, a revision of the decision to ignore the previous requests, in order to find a way to not have a resource always appearing as changed.

### Terraform Version

N/A

### AzureRM Provider Version

3.70.0+

### Affected Resource(s)/Data Source(s)

application_insights_standard_web_test

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
(see above)
```

### References

* https://github.com/hashicorp/terraform-provider-azurerm/issues/16569
* https://github.com/hashicorp/terraform-provider-azurerm/issues/7026
* https://github.com/hashicorp/terraform-provider-azurerm/pull/7125

**Comment by joaocc** [comment]
In addition, would it work (for the purpose of avoiding false positives) if we set tags["hidden-link:/..."] to the same value that appears in the plan? if so, would it be supported, or we would be risking some kind of corruption?
Thanks

**Comment by lonegunmanb** [comment]
Hi @joaocc we've carried a tested practice for this scenario, you can try the following config:

```hcl
terraform {
  required_providers {
    azapi = {
      source = "Azure/azapi"
      version = "1.11.0"
    }
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 3.50"
    }
  }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

resource "azurerm_resource_group" "example" {
  name     = "Rg-example"
  location = "West Europe"
}

resource "azurerm_application_insights" "example" {
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

locals {
  tags = {
    Environment = "test3"
  }
}

resource "azurerm_application_insights_web_test" "default" {
  name                    = "UpOrDown"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  application_insights_id = azurerm_application_insights.example.id
  kind                    = "ping"
  frequency               = 300
  timeout                 = 120
  enabled                 = true
  geo_locations           = ["emea-nl-ams-azr"]

  configuration = <<XML
<WebTest Name="WebTest1" Id="ABD48585-0831-40CB-9069-682EA6BB3583" Enabled="True" CssProjectStructure="" CssIteration="" Timeout="0" WorkItemIds="" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010" Description="" CredentialUserName="" CredentialPassword="" PreAuthenticate="True" Proxy="default" StopOnError="False" RecordedResultFile="" ResultsLocale="">
  <Items>
    <Request Method="GET" Guid="a5f10126-e4cd-570d-961c-cea43999a200" Version="1.1" Url="https://test/heartbeat" ThinkTime="0" Timeout="300" ParseDependentRequests="True" FollowRedirects="True" RecordResult="True" Cache="False" ResponseTimeGoal="0" Encoding="utf-8" ExpectedHttpStatusCode="200" ExpectedResponseUrl="" ReportingName="" IgnoreHttpStatusCode="False" />
  </Items>
</WebTest>
XML
  tags          = local.tags

  lifecycle {
    ignore_changes = [tags]
  }
}

resource "terraform_data" "tags_keeper" {
  triggers_replace = [
    local.tags
  ]
}

resource "azapi_update_resource" "application_insights_web_test_tags" {
  type        = "Microsoft.Insights/webtests@2015-05-01"
  resource_id = "${azurerm_resource_group.example.id}/providers/Microsoft.Insights/webtests/${lower(azurerm_application_insights_web_test.default.name)}"
  body        = jsonencode({
    tags = local.tags
  })

  lifecycle {
    replace_triggered_by = [
      terraform_data.tags_keeper.id
    ]
  }
}

data "azapi_resource" "example" {
  name      = azurerm_application_insights_web_test.default.name
  parent_id = azurerm_resource_group.example.id
  type      = azapi_update_resource.application_insights_web_test_tags.type
}

output test {
  value = data.azapi_resource.example
}
```

The key points:

1. Add `tags` into `ignore_changes` list
2. Add a `terraform_data` resource as `tags` keeper, once we've changed tags by our own data, this resource would be recreated with a new resource id.
3. Add an `azapi_update_resource` resource to update app insights web test resource's tags, and link it with `terraform_data` tags keeper, once tags have been changed, this update resource would be recreated.
4. Please notice the update resource's `resource_id`, I found that `webTests` and wet test resource's name would be converted to lowercase during `terraform refresh`, so I have to encode the id manually.

**Comment by joaocc** [comment]
Hi. Thanks @lonegunmanb for the workaround! Will be sure to try it. 
Even though it seems (and is) non-trivial, it would be localized in a specific module, so not really impacting overall maintenability.
I'm assuming that the naive-approach of simply setting `tags["hidden-link:..."] = "Resource"` would not work or would not as likely to be supported as using the other module.

**Comment by lonegunmanb** [comment]
Hi @joaocc ,

> is prevent_deletion_if_contains_resources = false really required?

No, we have some Azure Policies set in our testing environment which might create network security group for us, which might block the test stack being destroyed. You can just ignore this setting.

>Also, we were using `azurerm_application_insights_standard_web_test`. Are the API version and string the same?

Yes, I've used sniffer to inspect the API call, the version is `2015-05-01`.

Please feel free to ping me here if you have further questions.

**Comment by joaocc** [comment]
Thanks. I ended up using 2022-06-15 (as the previous one doesn't formally support standard tests), and everything seems to be working quite well. 
I think would still be preferable to intercept that specific field in this specific resources, but the workaround is working, so I think we can close the issue.
Once again, thanks for the help.
