### ISSUE TITLE
azurerm_storage_account_customer_managed_key: support for key vaults in other subscriptions

### ISSUE THREAD

**Issue by MattGarnerAWR** [hashicorp/terraform-provider-azurerm#24385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account_customer_managed_key

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "example" {
  name                     = "examplestor"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  identity {
    type = "SystemAssigned"
  }

  lifecycle {
    ignore_changes = [
      customer_managed_key
    ]
  }
}

resource "azurerm_storage_account_customer_managed_key" "example" {
  storage_account_id = azurerm_storage_account.example.id
  key_vault_id       = azurerm_key_vault.example.id
  key_name           = azurerm_key_vault_key.example.name
}
```

### Debug Output/Panic Output

```shell
# azurerm_storage_account_customer_managed_key.example will be updated in place
+ key_vault_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-name/providers/Microsoft.KeyVault/vaults/kv-name"
```

### Expected Behaviour

TF plan should find no changes, as CMK is already set up on the storage account

### Actual Behaviour

Every TF plan is wanting to apply the key vault ID to the storage account CMK.

### Steps to Reproduce

1. terraform apply
2. terraform plan

### Important Factoids

Key Vault is not on the same subscription, not sure if that is a problem?

**Comment by magodo** [comment]
@MattGarnerAWR Currently, the code assumes the subscription id of the keyvault is the same as the storage account id: https://github.com/hashicorp/terraform-provider-azurerm/blob/52734966f765c12a9537644f72d34cab1e1ab0cf/internal/services/storage/storage_account_customer_managed_key_resource.go#L274-L284

**Comment by MattGarnerAWR** [comment]
@magodo I disagree, this goes against provider design principles. This should be a bug.

https://developer.hashicorp.com/terraform/plugin/best-practices/hashicorp-provider-design-principles

**Comment by magodo** [comment]
@tombuildsstuff This issue seems to be a regression introduced by https://github.com/hashicorp/terraform-provider-azurerm/pull/24019, do you have a comment on this?

**Comment by btpemercier** [comment]
I'm agree with @MattGarnerAWR whenever you do a `terraform plan` you have this

```shell
# module.storage_account.azurerm_storage_account.storage_account will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
        id                                = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Storage/storageAccounts/mystorageaccount"
      - customer_managed_key {
          - key_vault_key_id          = "https://myvault.vault.azure.net/keys/my-key" -> null
          - user_assigned_identity_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/mystorageaccount-blob-id" -> null
        }

        # (5 unchanged blocks hidden)
    }
```

And the `terraform apply` does something but it shouldn't

```shell
Plan: 0 to add, 1 to change, 0 to destroy.
module.storage_account.azurerm_storage_account.storage_account: Modifying... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Storage/storageAccounts/mystorageaccount]
module.storage_account.azurerm_storage_account.storage_account: Modifications complete after 5s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-rg/providers/Microsoft.Storage/storageAccounts/mystorageaccount]
```

**Comment by tombuildsstuff** [comment]
As @magodo has mentioned above, this is an enhancement request rather than a bug - since we have a 1:1 relationship between a Provider instance and a Subscription at this point-in-time. Since there's already an issue open for this I'm going to consolidate this issue into #20199, as such would you mind subscribing to that issue for updates?

Thanks!
