### ISSUE TITLE
Support for Oracle Database@Azure

### ISSUE THREAD

**Issue by Bjego** [hashicorp/terraform-provider-azurerm#24387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hi Team,
we are relying on Oracle databases and we scaffold our cloud environment via the terraform provider. As Oracle Database@Azure is now officially launched (in the US). 
We would like to deploy Oracle Services via Terraform in Azure.
Please make this available.

[News Announcement](https://azure.microsoft.com/en-us/blog/microsoft-and-oracle-announce-that-oracle-databaseazure-is-now-generally-available/)

Thanks in advance!

### New or Affected Resource(s)/Data Source(s)

azurerm_3.9.0

### Potential Terraform Configuration

```hcl
Maybe close to a cosmos db config, a postgres config or a sql database config
```

### References

https://azure.microsoft.com/en-us/blog/microsoft-and-oracle-announce-that-oracle-databaseazure-is-now-generally-available/

**Comment by aristosvo** [comment]
Hi @Bjego 👋 

The Oracle@Azure is a Marketplace product, and it seems nothing regarding its infra is supported via the REST API.

Not sure what the future will offer here, but I would not expect it anytime soon.

**Comment by Bjego** [comment]
Hi @aristosvo ,
do you know, if it's possible to deploy it via arm/bicep/powershell then? Maybe we can inject bicep code into terraform and deploy it from there?
Or are there any plans to make this feature available for automation via rest?

Guess this is interesting for other companies as well 😄 , nor not? Guess this new feature is a game changer for cloud adoption of companies relying on Oracle databases.

Best regards

**Comment by aristosvo** [comment]
Hi @Bjego 👋 

The most important question on whether an Azure service can be used via IaC is whether there is an API for it. Specifications for the Azure REST APIs can be found [here](https://github.com/Azure/azure-rest-api-specs). At this moment in time there is nothing regarding `exadata` in there, the foundation of the OCI infrastructure that would be provided in Azure.

As that is not there, Terraform, Bicep, ARM, PowerShell and `az` have nothing to build upon. Unless I'm very mistaken and missed somehow the API definition and name, but until the API is available there is no way of doing IaC.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. There is a related PR open on Azure's side: https://github.com/Azure/azure-rest-api-specs/pull/26869. When it gets added, we can reopen this request or you can create a new one.
