### ISSUE TITLE
terraform azure stream analytics job output to kusto 

### ISSUE THREAD

**Issue by aasthabhalla** [hashicorp/terraform-provider-azurerm#24392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello Team,

Is terraform azure stream analytics job output to kusto supported? 
Also how can I create tables in kusto database using terraform?

### New or Affected Resource(s)/Data Source(s)

na

**Comment by jiaweitao001** [comment]
Hi @aasthabhalla , thanks for opening the issue. Currently, stream analytics job does not support output to kusto. You can find all the supported output [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs). To create tables in a kusto database, you can use `azurerm_kusto_script`.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @jiaweitao001‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Comment by aasthabhalla** [comment]
Hi @jiaweitao001 

I want to create multiple tables in azure database explorer database. I used the code here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_script but it only creates one table in the database. I pass the source_content like this 

Do you know what is the best way to pass the multiple create queries in this case?

source_content                      = <<-EOT
  .create table one (subject: string, system: string ),
  .create table two (subject: string, system: string),
  .create table three (subject: string, system: string),
  EOT
