### ISSUE TITLE
Can't create anything other than consumption tier API Manager

### ISSUE THREAD

**Issue by yooshyy** [hashicorp/terraform-provider-azurerm#24396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "api_manager_new" {
  name                = "apim-${local.appName}-${var.env}"
  location            = azurerm_resource_group.rg_client_portal_api.location
  resource_group_name = azurerm_resource_group.rg_client_portal_api.name
  publisher_name      = "xxx"
  publisher_email     = "xxx"
  sku_name            = "Basic_1"

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Service Name: "apim-client-portal-api-dev"): performing CreateOrUpdate: unexpected status 400 with error: NotSupported: 'Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_RSA_WITH_AES_128_CBC_SHA,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_RSA_WITH_AES_128_CBC_SHA256,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_RSA_WITH_AES_128_GCM_SHA256,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_RSA_WITH_AES_256_CBC_SHA,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_RSA_WITH_AES_256_CBC_SHA256,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TLS_RSA_WITH_AES_256_GCM_SHA384,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Ciphers.TripleDes168,Microsoft.WindowsAzure.ApiManagement.Gateway.Security.Protocols.Ssl30' customProperties are not supported in SkuType Consumption.
```

### Expected Behaviour

I expect an instance of API manager to be provisioned that is set at the basic tier

### Actual Behaviour

terraform apply fails. API manager is created in the consumption tier and is not added to my terraform state file.

### Steps to Reproduce

1. terraform apply

**Comment by sinbai** [comment]
Thanks for opening this issue. Unfortunately, I could not reproduce the issue with the following configuration.
```

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.85.0"
    }
  }
}

provider "azurerm" {
  features {}
}


resource "azurerm_resource_group" "test" {
  name     = "testRG-example"
  location = "eastus"
}

resource "azurerm_api_management" "api_manager_new" {
  name                = "apim-0105"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  publisher_name      = "pub1"
  publisher_email     = "pub1@email.com"
  sku_name            = "Basic_1"

  identity {
    type = "SystemAssigned"
  }
}
```

Based on the error message provided, it is recommended to use [TF Log](https://developer.hashicorp.com/terraform/internals/debugging) to see the exact value of the sku name in the request sent by Terraform. If the sku name sent by TF is `Basic`, I assume that it's an API issue. It is recommended to raise an issue in [this](https://github.com/Azure/azure-rest-api-specs/issues) repository for support.

**Comment by yooshyy** [comment]
Looking into the logs deeper I saw that instead of creating a new API manager, it was trying to update an existing API manager which was no longer visible in the Azure portal but I had deleted previously. I guess Azure must keep API managers around for a couple of days before doing a hard delete.

Changing the name of the resource properly spun of a new API manager and it works as expected.
