### ISSUE TITLE
Support for turning off request body inspection in CDN Frontdoor WAF

### ISSUE THREAD

**Issue by joschi27** [hashicorp/terraform-provider-azurerm#24401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure Frontdoor WAF policy has a policy setting for turning request body inspection on or off. When deploying a policy through terraform, the body inspection is automatically on, but we want to turn it off:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/16883655/23801d9f-00d8-4ca4-8135-4904eae93c38)

This issue was already raised on the legacy resource but was never completed for the new one. (see references)
You can even configure the custom message to return but not whether to turn it on or off.

The configuration option exists on the application gateway WAF already: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/application_gateway#request_body_check

### New or Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_firewall_policy

### Potential Terraform Configuration

```hcl
resource "azurerm_cdn_frontdoor_firewall_policy" "example" {
  name                              = "examplefdwafpolicy"
  resource_group_name               = azurerm_resource_group.example.name
  enabled                           = true
  mode                              = "Prevention"
  
  ### NEW ###
  request_body_check                = true # or false
}
```

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/17909

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24406 created by @harshavmb for this issue.
