### ISSUE TITLE
Policy exemptions will crash during apply if targeted resource doesn't exist 

### ISSUE THREAD

**Issue by marxhalvick** [hashicorp/terraform-provider-azurerm#24429]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_resource_policy_exemption

### Terraform Configuration Files

```hcl
Any config
```

### Debug Output/Panic Output

```shell
unexpected status 404 with error: ResourceNotFound: The Resource ...... was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
```

### Expected Behaviour

The plan should have failed before the apply tried to deploy the exemption.

### Actual Behaviour

The plan did work but the apply crashed because of the resource not found

### Steps to Reproduce

terraform apply

**Comment by jiaweitao001** [comment]
Hi @marxhalvick , as far as I tested, `azurerm_resource_policy_exemption` works well on my end. It would definitely make things easier for us to diagnose the problem if you could paste your TF config here. Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s). We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
