### ISSUE TITLE
Support for managed data disks in both azurerm_linux_virtual_machine and azurerm_windows_virtual_machine

### ISSUE THREAD

**Issue by benlavender** [hashicorp/terraform-provider-azurerm#24430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Like the now deprecated `azurerm_virtual_machine` had support for `storage_data_disk`, is it in the pipeline to apply this to the new modules?

I'm aware you can use `azurerm_managed_disk` and `azurerm_virtual_machine_data_disk_attachment` but would be easier in the noted modules.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine, azurerm_windows_virtual_machine

**Comment by mybayern1974** [comment]
Looks like the same issue with #6117

**Comment by benlavender** [comment]
Thanks yes I'd agree.

**Comment by benlavender** [comment]
Thanks yes I'd agree.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #6117.
