### ISSUE TITLE
`azurerm_security_center_setting` - SENTINEL is not valid anymore for `setting_name`

### ISSUE THREAD

**Issue by TimoW-Wago** [hashicorp/terraform-provider-azurerm#24438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_setting

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_setting" "main" {
  setting_name = "SENTINEL"
  enabled      = true
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/XXXXXX-XXXX-XXXX/providers/Microsoft.Security/settings/SENTINEL": parsing segment "settingName": expected the segment "settingName" to match one of the values "MCAS, Sentinel, WDATP, WDATP_EXCLUDE_LINUX_PUBLIC_PREVIEW, WDATP_UNIFIED_SOLUTION" but got "SENTINEL"
Operation failed: failed running terraform plan (exit 1)
```

### Expected Behaviour

Terraform plans should run without errors and update the value of `name_setting` to the new case.

### Actual Behaviour

We upgraded from provider version 3.83.0 to 3.86.0 and all Terraform plans fail. The casing of the option `setting_name` was changed in provider version 3.85.0 and does not accept the old value anymore. Therefore all Terraform runs fail during the plan stage making all changes to update to the new value `Sentinel` impossible.

### Steps to Reproduce

1. `terraform apply` using provider version 3.83.0
2. upgrade provider to 3.86.0
3. Optional: Change `setting_name` to new value `Sentinel`
4. `terraform apply` using new provider version

### References

- https://github.com/hashicorp/terraform-provider-azurerm/pull/24210

**Comment by ziyeqf** [comment]
Hi @TimoW-Wago , Thanks for reporting!

I have opened a PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/24497) for this, once it merged & released it should work. While as `SENTINEL` is a deprecated value, it's highly recommended to use `Sentinel` instead of `SENTINEL`.

For any further questions please leave comments.

Thanks!
