### ISSUE TITLE
The provider hashicorp/azurerm does not support resource type "azurerm_LogAnalytics_namespace".

### ISSUE THREAD

**Issue by balavennela** [hashicorp/terraform-provider-azurerm#24455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

I am trying to create secure score alert in loganalytics via terraform
I reffered https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace but Iam facing issue with The provider hashicorp/azurerm does not support resource type "azurerm_LogAnalytics_namespace"

<img width="890" alt="log analytics" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/103509121/0fb356cf-fd00-4b1a-b195-d5157de39f2a">
97a7379a340">

 below parameter I Configured via azure portal. How can i configure via terraform?

<img width="175" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/103509121/5310492e-4624-4027-8202-d5b2f915d4ad">

### Terraform Version

v1.5.2

### AzureRM Provider Version

v3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_LogAnalytics_namespace

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
on main.tf line 8, in resource "azurerm_LogAnalytics_namespace" "defender_namespace":
│    8:         resource "azurerm_LogAnalytics_namespace" "defender_namespace" {
│
│ The provider hashicorp/azurerm does not support resource type "azurerm_LogAnalytics_namespace".
```

### Expected Behaviour

fetch defender score automatically via terraform

### Actual Behaviour

Terraform plan was failed

### Steps to Reproduce

I did not apply

### Important Factoids

azure

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
