### ISSUE TITLE
azurerm_mssql_database  "Error: serverless databases do not support license type" with omitted license_type argument

### ISSUE THREAD

**Issue by kaganmersin** [hashicorp/terraform-provider-azurerm#24468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.5

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_database

### Terraform Configuration Files

```hcl
~ resource "azurerm_mssql_database" "single_database" {
      ~ auto_pause_delay_in_minutes         = 0 -> 60
      ~ min_capacity                        = 0 -> 0.5
        name                                = "example"
      ~ sku_name                            = "GP_Gen5_2" -> "GP_S_Gen5_2"
    }
```

### Debug Output/Panic Output

```shell
╷
│ Error: serverless databases do not support license type
│ 
│   with azurerm_mssql_database.single_database["dm"],
│   on main.tf line 16, in resource "azurerm_mssql_database" "single_database":
│   16: resource "azurerm_mssql_database" "single_database" {
│
```

**Comment by kaganmersin** [comment]
duplicated: https://github.com/hashicorp/terraform-provider-azurerm/issues/23103

**Comment by mchangchien** [comment]
Hello @kaganmersin sorry to jump in, but may I know the progress of this fix on this issue. Or if there's any workaround to fix this?
