### ISSUE TITLE
Container App custom scale rules not updating when multiple rules

### ISSUE THREAD

**Issue by ryanshirley-flipdish** [hashicorp/terraform-provider-azurerm#24467]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.2

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
module "customer_container_app_module" {
  servicebus_scaling_rules = [
    {
      queueName = "queue-a"
      messageCount = 5
    },
    {
      queueName = "queue-b"
      messageCount = 5
    },
  ]
}

resource "azurerm_container_app" "container_app_template" {
  template {
    dynamic "custom_scale_rule" {
      for_each = var.servicebus_scaling_rules

      content {
        name             = "sbus-${custom_scale_rule.value["queueName"]}"
        custom_rule_type = "azure-servicebus"
        metadata         = {
          queueName    = custom_scale_rule.value["queueName"]
          messageCount = custom_scale_rule.value["messageCount"]
          namespace    = "namespace"
        }
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
template {
            # (2 unchanged attributes hidden)

          ~ custom_scale_rule {
              ~ metadata         = {
                  ~ "queueName"    = "queue-b" -> "queue-a"
                    # (2 unchanged elements hidden)
                }
                name             = "queue-a"
                # (1 unchanged attribute hidden)

                # (1 unchanged block hidden)
            }

            # (2 unchanged blocks hidden)
        }
```

### Expected Behaviour

Two scaling rules created
1. `sbus-queue-a` with queue name `queue-a`
2. `sbus-queue-b` with queue name `queue-b`

### Actual Behaviour

Two scaling rules created
1. `sbus-queue-a` with queue name `queue-b`
2. `sbus-queue-b` with queue name `queue-b`

Terraform plan will always try change `sbus-queue-a` to use `queue-a` but on apply nothing changes and the plan stays the same on subsequent runs.

The same is true for if the `messageCount` property is different. `sbus-queue-a` with message count coming from` queue-b` value

**Comment by jiaweitao001** [comment]
Hi @ryanshirley-flipdish , thanks for reaching out. The TF config you provided above looks incomplete to me and hard to diagnose the problem. Seems you're trying to use a module to create resources, what is the name of the module? If you are just trying to create a container app with 2 sets of scale rules, maybe this is what you're looking for?

```HCL
locals {
  servicebus_scaling_rules = [
    {
      queueName = "queue-a"
      messageCount = 5
    },
    {
      queueName = "queue-b"
      messageCount = 5
    },
  ]
}

resource "azurerm_container_app" "container_app_template" {
  name = "testname"
  resource_group_name = azurerm_resource_group.dev.name
  container_app_environment_id = azurerm_container_app_environment.test.id
  revision_mode = "Single"

  template {
    container {
      name = "foo"
      image  = "barimage"
      cpu    = 0.25
      memory = "0.5Gi"
    }
    dynamic "custom_scale_rule" {
      for_each = local.servicebus_scaling_rules

      content {
        name             = "sbus-${custom_scale_rule.value["queueName"]}"
        custom_rule_type = "azure-servicebus"
        metadata         = {
          queueName    = custom_scale_rule.value["queueName"]
          messageCount = custom_scale_rule.value["messageCount"]
          namespace    = "namespace"
        }
      }
    }
  }
}

**Comment by ryanshirley-flipdish** [comment]
Hi @jiaweitao001, apologies I might have extracted too much to keep the context. You are correct I am using my own modules which in turn create a `azurerm_container_app` resource.

I am doing exactly like the example you have shared (I am passing servicebus_scaling_rules as a variable instead of locals but that will result in the same data).

The issue I face with the example you provided is that the scaling rules created in Azure results in the queueName for both rules to be `queue-b`. See in the example plan output `Debug Output/Panic Output` where the Terraform is thinking it needs to change the queue to `queue-a` but on apply nothing happens.

**Comment by jiaweitao001** [comment]
Hi @ryanshirley-flipdish , I've also observed this issue on my laptop. The root cause is still unknown. I'll keep investigating and keep you posted.

**Comment by ryanshirley-flipdish** [comment]
Thanks for the update, I appreciate it 🙏

**Comment by ryanshirley-flipdish** [comment]
@jiaweitao001 I see you opened a PR there with a fix for this. Any idea when that might be released?

I am in the middle of adding more scaling rules and the settings aren't being applied correctly because of this.

**Comment by jiaweitao001** [comment]
Hi @ryanshirley-flipdish , I'm not sure about HashiCorp's PR merging timeline. But it seems they will prioritize solving issues with more thumb ups.
