### ISSUE TITLE
Support for --node-provisioning-mode in AKS cluster

### ISSUE THREAD

**Issue by AlexandreODelisle** [hashicorp/terraform-provider-azurerm#24503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In the end of 2023, the Azure released provisionning options to support `karpenter` on an AKS cluster. 

The option is available once the feature is enable on a Azure subcription, please see [register-the-nodeautoprovisioningpreview-feature-flag]( https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli#register-the-nodeautoprovisioningpreview-feature-flag)

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  node_provisioning_mode  = "Auto"
  [...]
}
```

### References

Looking in the current Issues, I haven't seen any related to the new feature on AKS.

Azure References:
[node-autoprovision](https://learn.microsoft.com/en-us/azure/aks/node-autoprovision?tabs=azure-cli)
[Azure Karpenter](https://github.com/Azure/karpenter)

**Comment by AlexandreODelisle** [comment]
@stephybun, thanks for the labeling of the Issue and maintaining the provider. Do you happen to know, while talking with the Azure API Team, when they intend to make the feature in general availability?

**Comment by stephybun** [comment]
@AlexandreODelisle we unfortunately don't have a lot of insight into the AKS team's planning and delivery schedule. I think your best bet on finding out this information is to peruse the [AKS Public Roadmap project](https://github.com/Azure/AKS/projects/1) to see if there is an issue relating to the feature on there and at which stage it is, and if it's absent opening an issue on the [Azure/AKS](https://github.com/Azure/AKS) repo to get some visibility and input from their PMs on the feature.
