### ISSUE TITLE
parsing segment "staticResourceGroups": parsing the PrivateEndpoint ID: the segment at position 2 didn't match when upgrading azurerm from 3.21 to 3.86

### ISSUE THREAD

**Issue by Kkobakov** [hashicorp/terraform-provider-azurerm#24508]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

Terraform v1.1.3

### AzureRM Provider Version

registry.terraform.io/hashicorp/azurerm v3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "private_endpoint" {
  for_each            = var.acr_replica_endpoints == null ? {} : var.acr_replica_endpoints
  name                = each.value.pep_name
  location            = data.azurerm_resource_group.pep_res_group[each.key].location
  resource_group_name = data.azurerm_resource_group.pep_res_group[each.key].name
  subnet_id           = data.azurerm_subnet.private_link_endpoint_subnets[each.key].id

  private_service_connection {
    name                           = each.value.acr_name
    subresource_names              = ["registry"]
    private_connection_resource_id = each.value.acr_id
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "privatelink.azurecr.io"
    private_dns_zone_ids = ["${each.value.replica_dns_zone_id_prefix}privatelink.azurecr.io"]
  }

  tags = var.tags
  lifecycle {
    ignore_changes = [
      tags,
    ]
  }
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/xxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxx/providers/microsoft.network/privateEndpoints/xxxxxxxxxxxxx": parsing segment "staticResourceGroups": parsing the PrivateEndpoint ID: the segment at position 2 didn't match
│ 
│ Expected a PrivateEndpoint ID that matched:
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Network/privateEndpoints/privateEndpointValue
│
│ However this value was provided:
│
│ > /subscriptions/xxxxxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxx/providers/microsoft.network/privateEndpoints/xxxxxxxxxxxxxxxxxx
│
│ The parsed Resource ID was missing a value for the segment at position 2
│ (which should be the literal value "resourceGroups").
│
│
│
│   with azurerm_private_endpoint.private_endpoint["xxxxxxxxxxxx"],
│   on main.tf line 1, in resource "azurerm_private_endpoint" "private_endpoint":
│    1: resource "azurerm_private_endpoint" "private_endpoint" {
│
╵
time=2024-01-16T08:01:06Z level=error msg=1 error occurred:
        * exit status 1
```

### Expected Behaviour

when upgrading from 3.21 to 3.86 terraform plan succeeds 

### Actual Behaviour

when upgrading from 3.21 to 3.86 terraform plan fails with the error:
Error: parsing "/subscriptions/xxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxx/providers/microsoft.network/privateEndpoints/xxxxxxxxxxxxx": parsing segment "staticResourceGroups": parsing the PrivateEndpoint ID: the segment at position 2 didn't match
│ 
│ Expected a PrivateEndpoint ID that matched:
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Network/privateEndpoints/privateEndpointValue
│
│ However this value was provided:
│
│ > /subscriptions/xxxxxxxxxxxxxxxxxxxxxxx/resourcegroups/xxxxxxxxxxxxxxxxxxx/providers/microsoft.network/privateEndpoints/xxxxxxxxxxxxxxxxxx
│
│ The parsed Resource ID was missing a value for the segment at position 2
│ (which should be the literal value "resourceGroups").
│
│
│
│   with azurerm_private_endpoint.private_endpoint["xxxxxxxxxxxx"],
│   on main.tf line 1, in resource "azurerm_private_endpoint" "private_endpoint":
│    1: resource "azurerm_private_endpoint" "private_endpoint" {
│
╵
time=2024-01-16T08:01:06Z level=error msg=1 error occurred:
        * exit status 1

### Steps to Reproduce

1. create "azurerm_private_endpoint" for version 3.21
2. terraform init -upgrade (from 3.21 to 3.86)
3. terraform plan

**Comment by Kkobakov** [comment]
Hi @wuxu92,

The way to reproduce the problem as I described it is not correct. "azurerm_private_endpoint" was created in a previous version of azurerm, probably 2.x. We are now running 3.21 and trying to upgrade to 3.86. Terraform plan succeeds in 3.21 and fails in 3.86, but the resource was created in a much earlier version.

I found similar problem for another resource, if that helps:
https://github.com/hashicorp/terraform-provider-azurerm/issues/20240

**Comment by Kkobakov** [comment]
@wuxu92 what if I first "terraform state rm" the resource and then use the  "terraform import" to import it in the state?

**Comment by Kkobakov** [comment]
@wuxu92 it worked, thanks :)

**Comment by rcskosir** [comment]
@Kkobakov Thank you for taking the time to raise this! I am going to close this since @wuxu92‘s help was able to resolve this issue for you.
