### ISSUE TITLE
Support for the Pricing Model "StandardV2" needed for azurerm_stream_analytics_job

### ISSUE THREAD

**Issue by kzryzstof** [hashicorp/terraform-provider-azurerm#24505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The Azure Stream Analytics Job had a SKU update last year when it introduces the Pricing Plan `StandardV2`:

![Stream Analytics Job](https://github.com/hashicorp/terraform-provider-azurerm/assets/38137839/ffabbf7c-8c1f-489e-b3e1-4afbf416fdaf)

The resource `azurerm_stream_analytics_job` does not have the support for choosing the Pricing Plan. In fact, someone in our team changed it manually to `StandardV2` and now the `azurerm` provider wants to change it back to `Standard` but it is not accepted by Azure:

`Streaming Job Name: "saj-XXX-dev-01"): streamingjobs.StreamingJobsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Patching SKU from 'StandardV2' to 'Standard' is not supported" Details=[{"code":"400","correlationId":"57a7ddad-8b9c-e91b-8a0b-2a04043c35de","message":"Patching SKU from 'StandardV2' to 'Standard' is not supported","requestId":"246ee2a8-2aaf-4ce9-bf3d-f1230cfaacf7"}]`

Here is the link to the Azure Stream Analytics documentation detailing the change: 

https://learn.microsoft.com/en-ca/azure/stream-analytics/stream-analytics-streaming-unit-consumption#understand-streaming-unit-and-streaming-node

### New or Affected Resource(s)/Data Source(s)

azurerm_stream_analytics_job

### Potential Terraform Configuration

```hcl
resource "azurerm_stream_analytics_job" "default" {  
  pricing_plan = "Standard" or "StandardV2" (changing it requires the resource to be destroy)
}
```

**Comment by jiaweitao001** [comment]
Hi @kzryzstof , thanks for call this out. Currently, the API version TF is using does not support `StandardV2` as a valid input, it would error out if we forced so. This is supported in a preview API version `2021-10-01-preview`. You can leverage this by using Azapi to create your resource like this:

```HCL
resource "azapi_resource" "sajob" {
  type = "Microsoft.StreamAnalytics/streamingjobs@2021-10-01-preview"
  parent_id = azurerm_resource_group.dev.id
  name = <resource name>
  location = <resource location>
  
  body = jsonencode({
      properties = {
        sku = {
          name = "StandardV2"
        }
        transformation = {
          name = "main"
          properties = {
            query          = "   SELECT *\n   INTO [YourOutputAlias]\n   FROM [YourInputAlias]\n"
            streamingUnits = 3
          }
        }
      }
    })
  schema_validation_enabled = false
  response_export_values    = ["*"]
}
```

We will support the new API version in Azure RM once it's officially released. Thanks.

**Comment by rohith0020** [comment]
Hi @jiaweitao001, when can we expect this feature available in azurerm?

**Comment by jiaweitao001** [comment]
> Hi @jiaweitao001, when can we expect this feature available in azurerm?

Hi @rohith0020 , sorry we are not sure about the timeline of service team's new API version release. Once it's available, we will support it in azurerm.

**Comment by bergmeister** [comment]
This is now possible with `sku_name = "StandardV2"` so I think you can close this now
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/stream_analytics_job#sku_name
