### ISSUE TITLE
is it possible to specify the api version that used to create resource for azurerm_portal_dashboard?

### ISSUE THREAD

**Issue by jejass** [hashicorp/terraform-provider-azurerm#24525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

We want to create dashboard resource with Terraform. We have an Azure policy that require the creation should use api version greater than 2020-09-01-alpha that blocked the creation from Terraform. 
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/32087564/5ebe8d63-493e-4b56-a14a-2fd8a6d21c94)

So we want to know if there is anyway to specify the api version that used to create the dashboard resource.

if it is not possible to specify the api version that Terraform used, is there any way to execute ARM template deployment by Terraform? We can deploy an ARM template with api version.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.12.28

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_portal_dashboard

### Terraform Configuration Files

```hcl
NA
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

specify api version when creating Azure resource by Terraform

### Actual Behaviour

did not find property for api version

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
