### ISSUE TITLE
Cannot assign Management Group scope to Network Manager

### ISSUE THREAD

**Issue by xelossan** [hashicorp/terraform-provider-azurerm#24528]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.87.0

### Affected Resource(s)/Data Source(s)

azurerm_network_manager

### Terraform Configuration Files

```hcl
data "azurerm_management_group" "dev" {
  name = "dev"
}

resource "azurerm_network_manager" "default" {
  name                = "dev-vnm"
  resource_group_name = "dev"
  location            = "westeurope"

  scope_accesses = ["SecurityAdmin"]
  scope {
    management_group_ids = [
      data.azurerm_management_group.dev.id
    ]
  }
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.87.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
Error: creating Network Manager: unexpected status 400 with error: BadRequest: Resource [/providers/Microsoft.Management/managementGroups/dev] is not within tenant [...]
```

### Expected Behaviour

Network Manager should be created in selected scope, as Management Group exists in tenant, and Network Manager with the same configuration can be created from Azure Portal.

### Actual Behaviour

Trying to create Network Manager scoped to Management Group causes error incorrectly saying that the Management Group is not within tenant.

_No response_

**Comment by teowa** [comment]
Hi @xelossan, to create Network Manager in a Management Group, you need to first register the `Microsoft.Network` resource provider to the Management Group using [Azure CLI](https://learn.microsoft.com/en-us/cli/azure/provider?view=azure-cli-latest#az-provider-register) or [REST API](https://learn.microsoft.com/en-us/rest/api/resources/providers/register-at-management-group-scope?view=rest-resources-2021-04-01). You may also refer to the example TF config provided in the [Azure doc](https://learn.microsoft.com/en-us/azure/virtual-network-manager/create-virtual-network-manager-terraform?tabs=azure-cli&pivots=mgmt-grp)：
```hcl
resource "null_resource" "register_rp_to_mg" {
  provisioner "local-exec" {
    command = "az provider register --namespace Microsoft.Network -m ${azurerm_management_group.mg.name}"
  }
  depends_on = [azurerm_role_assignment.management_group_owner]
}

resource "time_sleep" "wait_5_seconds" {
  create_duration = "5s"
  depends_on      = [null_resource.register_rp_to_mg]
}

# Create a Virtual Network Manager instance

resource "azurerm_network_manager" "network_manager_instance" {
  name                = "network-manager"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  scope_accesses      = ["Connectivity"]
  description         = "example network manager"
  scope {
    management_group_ids = [azurerm_management_group.mg.id]
  }
  depends_on = [time_sleep.wait_5_seconds]
}

```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @teowa‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
