### ISSUE TITLE
azurerm_eventgrid_system_topic is unable to use a management group for the source_arm_resource_id paramater - Reopen 

### ISSUE THREAD

**Issue by kgopi1** [hashicorp/terraform-provider-azurerm#24548]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Hi, This issue # https://github.com/hashicorp/terraform-provider-azurerm/issues/18034 still not resolved with latest azurerm provider (3.87.0) also , still getting validation failed in event system topic when using management group. 

Error message:

 Error: Can not parse "source_arm_resource_id" as a resource id: No subscription ID found in: "tenants/***/providers/Microsoft.Management/managementGroups/******"
│ 
│   with azurerm_eventgrid_system_topic.topic,
│   on ev-policy-events.tf line 19, in resource "azurerm_eventgrid_system_topic" "topic":
│   19:   source_arm_resource_id = "/tenants/***/providers/Microsoft.Management/managementGroups/*****"

Refer the Microsoft link which states to use different syntax when referring the management group id. 

If your Event Grid system topic will be applied to the management group scope, then the Azure CLI --source parameter syntax is a bit different. Here's an example:

az eventgrid system-topic create --name PolicyStateChanges --location global --topic-type Microsoft.PolicyInsights.PolicyStates --source "/tenants/<tenantID>/providers/Microsoft.Management/managementGroups/<management_group_name>" --resource-group "<resource_group_name>"

https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/governance/policy/tutorials/route-state-change-events.md

### Terraform Version

1.5.7

### AzureRM Provider Version

3.87.0

### Affected Resource(s)/Data Source(s)

azurerm_eventgrid_system_topic

### Terraform Configuration Files

```hcl
resource "azurerm_eventgrid_system_topic" "topic" {
  name                   = "system-topic"
  location               = "Global"
  resource_group_name    = data.azurerm_resource_group.resource_group.name
  source_arm_resource_id = "/tenants/*****/providers/Microsoft.Management/managementGroups/****"
  topic_type             = "Microsoft.PolicyInsights.PolicyStates"
}
```

### Debug Output/Panic Output

```shell
Error: Can not parse "source_arm_resource_id" as a resource id: No subscription ID found in: "tenants/***/providers/Microsoft.Management/managementGroups/******"
```

### Expected Behaviour

Able to create azurerm_eventgrid_system_topic successfully. 

### Actual Behaviour

Error: Can not parse "source_arm_resource_id" as a resource id: No subscription ID found in: "tenants/***/providers/Microsoft.Management/managementGroups/******"

**Comment by tombuildsstuff** [comment]
hi @kgopi1

Taking a look through here, it appears that this is because the value being provided for the Management Group ID doesn't match the defined format for a Management Group ID. Management Group IDs should be in the format:

> /providers/Microsoft.Management/managementGroups/XXX

However the following value is being provided:

> /tenants/XXX/providers/Microsoft.Management/managementGroups/XXX

As such can you try removing the `/tenants/XXX` prefix from the Management Group ID?

Thanks!

**Comment by kgopi1** [comment]
Hi @tombuildsstuff , i tryied again by passing source_id as /providers/Microsoft.Management/managementGroups/*****. 

apply stage got failed with below error. 

performing CreateOrUpdate: unexpected status 400 with error: InvalidRequest: ResourceID is not in the expected format. 

So if you look Azure Documentation[ link](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/governance/policy/tutorials/route-state-change-events.md)  ,if we need to pass the management group as source_id it is looking in format as /tenants/*****/providers/Microsoft.Management/managementGroups/****


 # azurerm_eventgrid_system_topic.topic will be created
  + resource "azurerm_eventgrid_system_topic" "topic" {
      + id                     = (known after apply)
      + location               = "global"
      + metric_arm_resource_id = (known after apply)
      + name                   = "system-topic"
      + resource_group_name    = "myresourcegroup"
      + source_arm_resource_id = "/providers/Microsoft.Management/managementGroups/*****"
      + topic_type             = "Microsoft.PolicyInsights.PolicyStates"
    }

**Comment by dkaushik100** [comment]
Is this issue fixed? I am getting System Topic Name: "****"): performing CreateOrUpdate: unexpected status 400 with error: InvalidRequest: ResourceID is not in the expected f
ormat: /providers/Microsoft.Management/managementgroups/"****"
│ Parameter name: GetSourceScope

when creating a system topic resource via azurerm_eventgrid_system_topic

**Comment by sharccc** [comment]
reference IPL-6351
