### ISSUE TITLE
Cannot create a virtual network subnet with a network security group atomically

### ISSUE THREAD

**Issue by ghidalgo3** [hashicorp/terraform-provider-azurerm#24552]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0

### AzureRM Provider Version

3.0.2

### Affected Resource(s)/Data Source(s)

azurerm_subnet

### Terraform Configuration Files

```hcl
# Configure the Azure provider
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "resourceGroup"
  location = "eastus2"
}

resource "azurerm_virtual_network" "vnet" {
  address_space       = ["10.0.0.0/8"]
  name                = "vnet"
  location            = "eastus2"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_network_security_group" "nsg" {
  name                = "nsg"
  location            = "eastus2"
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefixes     = ["10.0.0.0/24"]
}

resource "azurerm_subnet_network_security_group_association" "assoc" {
  subnet_id                 = azurerm_subnet.subnet.id
  network_security_group_id = azurerm_network_security_group.nsg.id
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/ghidalgo3/5c98885d2ae0e4cbfbfec16664f070cc
```

### Expected Behaviour

I expect a single PUT call to create the subnet _and_ the NSG association with it.

### Actual Behaviour

There was a PUT call to create the subnet, followed by a second PUT call to associate the NSG with the subnet.

### Important Factoids

There are internal-to-Microsoft Azure security policies that do not allow subnets without NSGs.

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/5801

I believe the previous behavior was desirable, the current behavior opens up race conditions.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume it's by TF design and the race condition issue is considered. Suggest to use latest azurerm provider since all new changes/fixes would be involved in the latest version. Thanks.

**Comment by tombuildsstuff** [comment]
hi @ghidalgo3 

These fields have been intentionally removed from the `azurerm_subnet` resource to workaround issues within the Azure Platform during the deletion of resources, as this field has been intentionally removed unfortunately this isn't something we plan to reintroduce at this time. However as a part of #3917 we're planning to extend the `subnet` block within the `azurerm_virtual_network` resource to support more of the `subnet` related properties, but introducing that functionality will unfortunately be a breaking change and as such this must be done in a major version.

Instead #9022 is tracking adding an example of how to use Azure Policy with the separate resources, and #3917 is tracking adding additional fields within the `azurerm_virtual_network` resource - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by ghidalgo3** [comment]
Hi @tombuildsstuff, thank you for the related issues. Reading through #3917 showed me that if I want to add an NSG property to a subnet, that is achievable like this:

```terraform
resource "azurerm_virtual_network" "vnet" {
  address_space       = ["10.0.0.0/8"]
  name                = "vnet"
  location            = "eastus2"
  resource_group_name = azurerm_resource_group.rg.name
  subnet {
    name                 = "subnet"
    address_prefix     = "10.0.0.0/24"
    security_group = azurerm_network_security_group.nsg.id
  }
}
```

Which  shows up in the logs as a single PUT call:

```
PUT /subscriptions/394dccd4-6f06-4003-8c9a-671ba0d665c7/resourceGroups/resourceGroup/providers/Microsoft.Network/virtualNetworks/vnet?api-version=2021-05-01 HTTP/1.1
Host: management.azure.com
User-Agent: Go/go1.17.5 (amd64-linux) go-autorest/v14.2.1 Azure-SDK-For-Go/v62.3.0 network/2021-05-01 HashiCorp Terraform/1.7.0 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.0.2 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Content-Length: 371
Content-Type: application/json; charset=utf-8
X-Ms-Authorization-Auxiliary: 
X-Ms-Correlation-Request-Id: 10ddb6a3-1d71-aff3-daf7-6856a8afcf94
Accept-Encoding: gzip

{"location":"eastus2","properties":{"addressSpace":{"addressPrefixes":["10.0.0.0/8"]},"dhcpOptions":{"dnsServers":[]},"subnets":[{"name":"subnet","properties":{"addressPrefix":"10.0.0.0/24","networkSecurityGroup":{"id":"/subscriptions/394dccd4-6f06-4003-8c9a-671ba0d665c7/resourceGroups/resourceGroup/providers/Microsoft.Network/networkSecurityGroups/nsg"}}}]},"tags":{}}: timestamp=2024-01-18T17:59:07.389-0500
2024-01-18T17:59:08.338-0500 [DEBUG] provider.terraform-provider-azurerm_v3.0.2_x5: AzureRM Response for https://management.azure.com/subscriptions/394dccd4-6f06-4003-8c9a-671ba0d665c7/resourceGroups/resourceGroup/providers/Microsoft.Network/virtualNetworks/vnet?api-version=2021-05-01: 
HTTP/2.0 201 Created
```

It would be good to have the full list of subnet properties supported, but our immediate pain was specifically network security groups. I will thumbs-up #3917 as I'm sure it will become pertinent in the future. Thanks!
