### ISSUE TITLE
Terraform ignores changes to empty string value in azurerm_app_configuration_key

### ISSUE THREAD

**Issue by JiriKovar** [hashicorp/terraform-provider-azurerm#24565]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0

### AzureRM Provider Version

3.88.0

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration_key" "setting" {
  configuration_store_id = azurerm_app_configuration.appconf.id
  key                    = "testkey"
  label                  = "label"
  value                  = ""

  lifecycle {
    ignore_changes = [
      configuration_store_id // required due to https://github.com/hashicorp/terraform-provider-azurerm/issues/24109
    ]
  }
}
```

### Debug Output/Panic Output

```shell
No change in terraform plan detected & no change made by apply
```

### Expected Behaviour

~ resource "azurerm_app_configuration_key" "setting" {
      ~ etag                   = "<etag>" -> (known after apply)
      ~ value                  = "testvalue2" -> ""
        # (7 unchanged attributes hidden)
    }

### Actual Behaviour

The conjunction of changing the value to empty string with the workaround with `ignore_changes` mentioned in the linked bug causes the change to be ignored.

- If the new value is not empty, the change is detected and applied as expected
- If the key is completely new, it gets created and the value is set as expected
- If the `configuration_store_id` is not ignored, the change is detected and applied as expected

We did not yet observe similar issues in some other circumstances, but it has already caused us a production issue because this unexpected behavior can easily go unnoticed when running terraform apply and we have no guarantee that this is the only way the issue can manifest.

### Steps to Reproduce

* Apply the terraform configuration snippet given with nonempty value
* Change the value to empty string
* Run terraform plan and see that it does not reveal any changes

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/24109#issuecomment-1900300631

**Comment by tombuildsstuff** [comment]
Notes whilst passing through/reviewing this one: looks like this field is marked as `Computed` when it shouldn't be.
