### ISSUE TITLE
Azurerm_storage_account_network_rules fail apply, citing invalid request parameters (networkAcls.resourceAccessRules[*].resourceId)

### ISSUE THREAD

**Issue by OctavioCore** [hashicorp/terraform-provider-azurerm#24566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.88.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account, azurerm_storage_account_network_rules

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "resource" {
  name                              = "foobar"
  resource_group_name               = azurerm_resource_group.resource.name
  location                          = var.location
  account_tier                      = "Standard"
  account_replication_type          = "LRS"
  min_tls_version                   = "TLS1_2"
  infrastructure_encryption_enabled = true
  public_network_access_enabled     = true

  network_rules {
    default_action = "Deny"
    ip_rules       = []

    virtual_network_subnet_ids = [
      azurerm_subnet.main_subnet.id,
      azurerm_subnet.other_subnet.id,
      data.azurerm_subnet.another_subnet.id
    ]

    bypass = [
      "AzureServices",
      "Logging",
      "Metrics"
    ]

    dynamic "private_link_access" {
      for_each = toset([
        azurerm_private_endpoint.mssql_main_endpoint.id,
      ])

      content {
        endpoint_resource_id = private_link_access.value
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: updating `network_rules` for Storage Account (Subscription: "[MASKED]"
│ Resource Group Name: "MASKED"
│ Storage Account Name: "MASKED"): storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidValuesForRequestParameters" Message="Values for request parameters are invalid: networkAcls.resourceAccessRules[*].resourceId. For more information, see - https://aka.ms/storagenetworkruleset"
```

### Expected Behaviour

Private link block working - both for standalone rules declaration, and for the inline version in the storage account resource. If not - appropriate notification added to the documentation, with a suggestion for possible workaround. If the issue is that an incorrect output was passed to this block - the documentation should be clarified; The block demands `endpoint_resource_id` - and that's exactly what's been supplied.

### Actual Behaviour

The apply failed, despite valid code implementation, both when the inline rules were used, and when the separate rules block was used.

### Steps to Reproduce

1. Create a storage account
2. Create a private endpoint - in my case, it was for an Azure MSSQL Server.
3. Add the private endpoint to the private link block, in any shape or form
4. Run `apply`

### Important Factoids

When looking for a solution, I've found similar issues discussed on Bicep issue requests - so I do assume, this might have something to do with the SDK underneath, and not the provider itself.  The issue is quite difficult to ignore - compliance benchmarks for Azure demand private endpoints to be in use. 

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account_network_rules
https://registry.terraform.io/providers/hashicorp/azurerm/1.43.0/docs/resources/private_endpoint
https://github.com/Azure/azure-cli/issues/14404

**Comment by magodo** [comment]
@OctavioCore Instead of a `azurerm_private_endpoint`, this `endpoint_resource_id` expects the peering resource id, i.e. just the mssql resource id, per the document:

> * `endpoint_resource_id` - (Required) The resource id of the resource access rule to be granted access.

**Comment by OctavioCore** [comment]
> @OctavioCore Instead of a `azurerm_private_endpoint`, this `endpoint_resource_id` expects the peering resource id, i.e. just the mssql resource id, per the document:
> 
> > * `endpoint_resource_id` - (Required) The resource id of the resource access rule to be granted access.

I honestly thought, the endpoint resource ID is the ID of the private endpoint - the phrasing of the document is a bit confusing. I'd suggest a minor change for clarity, then:

> ` endpoint_resource_id ` -  (Required) The ID of the Azure resource that should be allowed access by the rule.`

or:

>`endpoint_resource_id` - (Required) The ID of the Azure resource that should be allowed access to the target storage account.`

**Comment by magodo** [comment]
Hi @OctavioCore, I just tried the below config, which works fine for me:

```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG-storage-kkk"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvirtnetkkk"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_subnet" "test" {
  name                 = "acctestsubnetkkk"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.2.0/24"]
  service_endpoints    = ["Microsoft.Storage"]
}

resource "azurerm_mssql_server" "test" {
  name                         = "acctestsqlserver321"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "missadministrator"
  administrator_login_password = "thisIsKat11"

  outbound_network_restriction_enabled = true
}

resource "azurerm_storage_account" "test" {
  name                     = "unlikely23exst2acctkkk"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["127.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.test.id]
    private_link_access {
      endpoint_resource_id = azurerm_mssql_server.test.id
    }
  }
}
```

Could you try above and review any diff with your config (note that the `service_endpoints    = ["Microsoft.Storage"]` is required for the vnet, otherwise you'll get error when configuring the subnet it contains in the storage's network ACL).

**Comment by OctavioCore** [comment]
> ```terraform
> azurerm_mssql_server
> ```

I've done some troubleshooting, and apparently this issue only occurs when the Key Vault is added as an endpoint. I've had its firewall configured to bypass for Azure services beforehand, but I suppose it might have something to do with the storage account being designated as managed by the keyvault - but, as apply passed, thus my current scope of requirements is fulfilled, I'll observe the situation and report if there's anything out of order/worthy of putting a note in the docs.

Thank you for the suggestion and help ;)
