### ISSUE TITLE
Support for multiple partitions in `azurerm_servicebus_namespace`

### ISSUE THREAD

**Issue by Simonzhaohui** [hashicorp/terraform-provider-azurerm#24597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When I would like to create azure service bus namespace with `Premium` sku, I can't set multiple partitions, like azure portal or CLI, example: parameter `--premium-partitions` with `az servicebus namespace create`.

The `Partition count` of Premium service bus namespace is 1, then I can't set `enable_partitioning` for `azurerm_servicebus_topic`

azurerm version: 3.86.0

### New or Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace

### Potential Terraform Configuration

```hcl
resource "azurerm_servicebus_namespace" "sb" {
  ...
  sku                           = "Premium"
  capacity                      = 2
  partitions                    = 2
  ... 

This partitions is only for Premium
```

### References

https://learn.microsoft.com/en-us/azure/service-bus-messaging/enable-partitions-premium

**Comment by xiaxyi** [comment]
Thanks @Simonzhaohui for raising this issue, let me check the feature and add it to the backlog once confirmed.

**Comment by xiaxyi** [comment]
Thanks @Simonzhaohui for raising this issue, the property is added in api version `2022-10-01-preview` while azurerm servicebus resource provider is currently using `2022-01-01-preview`. Let me raise a PR to upgrade the api version then add this property. Any update will be shared here. thanks for your understanding!

**Comment by Simonzhaohui** [comment]
@xiaxyi Appreciated for your support !

**Comment by xiaxyi** [comment]
Link API upgrade PR:https://github.com/hashicorp/terraform-provider-azurerm/pull/24650

**Comment by xiaxyi** [comment]
@Simonzhaohui Thanks for your patience, you can subscribe the linked PR for progress.

**Comment by chrispellett** [comment]
Does the linked PR (that was released in v3.90.0) have everything required to support multiple partitions on premium service bus namespaces?

The documentation doesn't mention what the property name to use is.

**Comment by xiaxyi** [comment]
@chrispellett If my understanding is correct, are you talking about the api property?  The property that this pr covered is 
 [premiumMessagingPartitions](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/servicebus/resource-manager/Microsoft.ServiceBus/preview/2022-10-01-preview/namespace-preview.json#L781)

**Comment by chrispellett** [comment]
Sure, sorry I wasn't clear before.

When I refer to the namespace resource documentation for v3.90.0, I don't see a property related to the partition count: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/servicebus_namespace

I'm not sure if the documentation aspect is part of the work to close this particular issue or not.
