### ISSUE TITLE
ACE showing changes on every plan when adding a new ACE block

### ISSUE THREAD

**Issue by RobDearling** [hashicorp/terraform-provider-azurerm#24604]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0

### AzureRM Provider Version

3.88.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem, azurerm_storage_data_lake_gen2_path

### Terraform Configuration Files

```hcl
resource "azurerm_storage_data_lake_gen2_filesystem" "test_container" {
  name               = "main"
  storage_account_id = azurerm_storage_account.dearlingr_acl_testing_storage.id
  ace {
    id = "<object-id-here>"
    permissions = "rwx"
    scope = "access"
    type = "group"
  }
}
```

### Debug Output/Panic Output

```shell
---
```

### Expected Behaviour

The terraform plan should only show the ace block specified in Terraform as a change.

### Actual Behaviour

Terraform plan will show 4 removals and the single addition.

### Steps to Reproduce

**Create initial container**
```
resource "azurerm_storage_data_lake_gen2_filesystem" "test_container" {
  name               = "main"
  storage_account_id = azurerm_storage_account.dearlingr_acl_testing_storage.id
}
```

- Run terraform apply 
- Run tf plan to confirm no changes

**Add an ACE**
```
resource "azurerm_storage_data_lake_gen2_filesystem" "test_container" {
  name               = "main"
  storage_account_id = azurerm_storage_account.dearlingr_acl_testing_storage.id
  ace {
    id = "<object-id-here>"
    permissions = "rwx"
    scope = "access"
    type = "group"
  }
}
```

- Run terraform plan 

Output will remove 4 ACE blocks in the plan and add the new ace block specified in terraform

```
  ~ resource "azurerm_storage_data_lake_gen2_filesystem" "test_container" {
        id                 = "https://dearlingrtestingstorage.dfs.core.windows.net/main"
        name               = "main"
        # (4 unchanged attributes hidden)

      - ace {
          - permissions = "---" -> null
          - scope       = "access" -> null
          - type        = "other" -> null
        }
      - ace {
          - permissions = "r-x" -> null
          - scope       = "access" -> null
          - type        = "group" -> null
        }
      - ace {
          - permissions = "rwx" -> null
          - scope       = "access" -> null
          - type        = "mask" -> null
        }
      - ace {
          - permissions = "rwx" -> null
          - scope       = "access" -> null
          - type        = "user" -> null
        }
      + ace {
          + id          = "2573b315-eb86-41a1-b57b-bb0ad94fa5e5"
          + permissions = "rwx"
          + scope       = "access"
          + type        = "group"
        }
    }
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I assume that it's by TF design. Service API would add the default ACEs when it isn't specified. So suggest to explicitly set them in the tf config if you want to retain the default ACEs.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei's response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
