### ISSUE TITLE
Azure Container App Environments - Add "consumption" option for workload profile

### ISSUE THREAD

**Issue by admsallai** [hashicorp/terraform-provider-azurerm#24608]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

By default when NOT providing "workload_profile" block, terraform is creating consumption only environment type.

When  "workload_profile" block is provided there is no option to only use default consumption profile since one of D4, D8, D16, D32, E4, E8, E16 and E32 is required. 

There is no option to create workload profiles environment type only with defaulty created consumption profile, so following manual in portal setup is not possible with terraform:
![Screenshot 2024-01-23 172936](https://github.com/hashicorp/terraform-provider-azurerm/assets/102801593/c48339ff-471f-424e-bd45-f04f92380b54)

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Potential Terraform Configuration

```hcl
resource "azurerm_container_app_environment" "agent_con_app_env" {
  name                           = "environment-name"
  location                       = "location"
  resource_group_name            = "rg-name"
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.log_analytics.id
  infrastructure_subnet_id       = azurerm_subnet.infra_subnet
  internal_load_balancer_enabled = true

   workload_profile {
    name                  = "workload-name"
    workload_profile_type = "Consumption" #or ability to skip this since consumption profile is default
    maximum_count         = 5
    minimum_count         = 1
  }
}
```

**Comment by jaromirmikulik** [comment]
The Example configuration for Consumption workload profile could look like this:

```

resource "azurerm_container_app_environment" "agent_con_app_env" {
  name                           = "environment-name"
  location                       = "location"
  resource_group_name            = "rg-name"
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.log_analytics.id
  infrastructure_subnet_id       = azurerm_subnet.infra_subnet
  internal_load_balancer_enabled = true

   workload_profile {
    workload_profile_type = "Consumption" #or ability to skip this since consumption profile is default
  }
}

```

"Consumption" workload profile type doesn't have any other values need to fill in.
