### ISSUE TITLE
azurerm_search_service create/update fails to update because on invalid properties

### ISSUE THREAD

**Issue by vamshisiram** [hashicorp/terraform-provider-azurerm#24623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.57.0

### Affected Resource(s)/Data Source(s)

azurerm_search_service

### Terraform Configuration Files

```hcl
resource "azurerm_search_service" "search_service" {
  name                          = "srch-test"
  resource_group_name           = "rg-test"
  location                      = "northcentralus"
  sku                           = var.sku
  replica_count                 = var.replica_count
  partition_count               = lower(var.sku) == "basic" ? 1 : var.partition_count
  public_network_access_enabled = false
  local_authentication_enabled  = true
}
```

### Debug Output/Panic Output

```shell
Error: updating Search Service (Subscription: "a3f35929-499d-49ee-a21d-0fbc494461b3" Resource Group Name: "rg-openai-001" Search Service Name: "srch-idpaidev-001"): performing CreateOrUpdate: unexpected status 400 with error: BadRequest: Request body cannot contain the following invalid Properties : privateEndpointConnections,provisioningState,sharedPrivateLinkResources,status,statusDetails. Please refer to https://learn.microsoft.com/en-us/rest/api/searchmanagement/management-api-versions for a list of allowed properties
```

### Expected Behaviour

expect the search service local auth to be enabled.

### Actual Behaviour

Error: updating Search Service (Subscription: "a3f35929-499d-49ee-a21d-0fbc494461b3" Resource Group Name: "rg-openai-001" Search Service Name: "srch-idpaidev-001"): performing CreateOrUpdate: unexpected status 400 with error: BadRequest: Request body cannot contain the following invalid Properties : privateEndpointConnections,provisioningState,sharedPrivateLinkResources,status,statusDetails. Please refer to https://learn.microsoft.com/en-us/rest/api/searchmanagement/management-api-versions for a list of allowed properties

### Steps to Reproduce

1. Create a search service first with local auth set to false.
2. then change the local auth to true. and apply.

**Comment by vamshisiram** [comment]
Hi Neil,

Yes, i tried with latest azurerm provider version and it still exists.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acranefei** [comment]
I'm having the same issue. I was able to deploy previously with no issue, but now it's throwing this error.

**Comment by math280h** [comment]
> I'm having the same issue. I was able to deploy previously with no issue, but now it's throwing this error.

Same here

**Comment by noiserockfiend** [comment]
Same issue.  Unable to make any changes to Search services.

**Comment by leiter-jakab** [comment]
I'm also encountering this issue. You can find my configuration below. I'm using a private endpoint and configure to use both API keys and RBAC for access.

```hcl
resource "azurerm_search_service" "ais-search" {
  name                = "ais-${local.workload}-search-${var.environment}"
  resource_group_name = data.azurerm_resource_group.rg-base.name
  location            = data.azurerm_resource_group.rg-base.location
  sku                 = "basic"

  public_network_access_enabled = false
  local_authentication_enabled  = false

  identity {
    type = "SystemAssigned"
  }
  
  tags = local.tags
}

resource "azurerm_private_dns_zone" "dns-search" {
  name                = "privatelink.${local.ai_search_domain}"
  resource_group_name = data.azurerm_resource_group.rg-base.name
  
  tags = local.tags
}

resource "azurerm_private_dns_zone_virtual_network_link" "dns-vnet-link-search-base" {
  name                  = "dns-vnet-link-${local.workload}-search-${var.environment}"
  resource_group_name   = data.azurerm_resource_group.rg-base.name
  private_dns_zone_name = azurerm_private_dns_zone.dns-search.name
  virtual_network_id    = data.azurerm_virtual_network.vnet-base.id

  tags = local.tags
}

resource "azurerm_private_endpoint" "pe-search" {
  name                = "pe-${local.workload}-search-${var.environment}"
  location            = data.azurerm_resource_group.rg-base.location
  resource_group_name = data.azurerm_resource_group.rg-base.name
  subnet_id           = azurerm_subnet.snet-private-endpoints.id

  custom_network_interface_name = "nic-${local.workload}-search-${var.environment}"

  private_service_connection {
    name                           = "psc-${local.workload}-search-${var.environment}"
    private_connection_resource_id = azurerm_search_service.ais-search.id
    subresource_names              = ["searchService"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "dns-zg-${local.workload}-search-${var.environment}"
    private_dns_zone_ids = [azurerm_private_dns_zone.dns-search.id]
  }

  tags = local.tags
}

resource "azurerm_monitor_diagnostic_setting" "ds_search" {
  name                       = "ds-${local.workload}-search-${var.environment}"
  target_resource_id         = azurerm_search_service.ais-search.id
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.law-base.id

  enabled_log {
    category = "OperationLogs"
  }

  metric {
    category = "AllMetrics"
    enabled  = false
  }
}
```

**Comment by fonts1215** [comment]
Same, just update authentication_failure_mode to "http403", also use private endpoint for connection

**Comment by user81017012** [comment]
it seems that updating anything in the resource causes this
the issue doesnt seem to be present in some older versions; like 3.53.0

**Comment by narisada014** [comment]
I've encountered the same issue with AzureRM version 3.90.0. The issue occurred just by adding the semantic_search_sku property.

**Comment by fonts1215** [comment]
Maybe Microsoft changed some API, and now for each change inside the Azuresearch (apply for terraform) we have this problem

**Comment by user81017012** [comment]
> it seems that updating anything in the resource causes this the issue doesnt seem to be present in some older versions; like 3.53.0

The issue seems to have started from version **3.54.0** and doesnt seem to be solved in recent provider versions

For the moment i just added an ignore changes on all for this resource :/ hopefully it gets fixed soon

**Comment by gjednaszewski** [comment]
I'm seeing this on 3.83.0 trying to update a tag value on the azure search resource

**Comment by WodansSon** [comment]
I suspect that something has changed on the service side. Our nightly acceptance tests had a 100% passing rate until January 31, 2024, where some of our test cases started failing with exact same error message as mentioned above. I will reach out to the service team to see if anything was pushed to production in that timeframe.

**Comment by ron-foreman** [comment]
Also getting this on 3.90.0 while updating tags. Upgrading to latest 3.92.0 has same result
