### ISSUE TITLE
azurerm_search_shared_private_link_service doesn't support SQL Managed Instance

### ISSUE THREAD

**Issue by christopher-pope** [hashicorp/terraform-provider-azurerm#24637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.88.0

### Affected Resource(s)/Data Source(s)

azurerm_search_shared_private_link_service

### Terraform Configuration Files

```hcl
esource "azurerm_search_shared_private_link_service" "private_link" {
      + id                 = (known after apply)
      + name               = "spl-managedInstance-sqlmi01"
      + request_message    = "Terrform Generated Private Link Service"
      + search_service_id  = "/subscriptions/[MASKED]/resourceGroups/RG/providers/Microsoft.Search/searchServices/azure-ai-search2"
      + status             = (known after apply)
      + subresource_name   = "managedInstance"
      + target_resource_id = "/subscriptions/[MASKED]/resourceGroups/RG/providers/Microsoft.Sql/managedInstances/sqlmi01"
    }
```

### Debug Output/Panic Output

```shell
Error: creating/ updating Shared Private Link Resource (Subscription: "[MASKED]"
Shared Private Link Resource Name: "spl-managedInstance-sqlmi01"):
performing CreateOrUpdate: unexpected status 400 with error: BadRequest:
Cannot create private endpoint for requested type 'managedInstance'.
Supported types are: 'blob,table,dfs,file,Sql,sqlServer,vault' RequestId:
```

### Expected Behaviour

I expect to be able to create a shared private link to a SQL Managed Instance. Based on Microsoft's documentation SQL Managed Instance support was first available in API Version 2020-08-01-Preview.

https://learn.microsoft.com/en-us/azure/search/troubleshoot-shared-private-link-resources#request-validation-failures

### Actual Behaviour

Cannot create private endpoint for requested type 'managedInstance'.
Supported types are: 'blob,table,dfs,file,Sql,sqlServer,vault'

### Steps to Reproduce

Create azurerm_search_shared_private_link_service  with subresource_name as "managedInstance"

**Comment by sinbai** [comment]
@christopher-pope thanks for opening this issue. It’s worth mentioning that Terraform uses the Azure Rest API to manage Azure resources. The above error is returned by the Azure Rest API and not Terraform. And, for Terraform resources `azurerm_search_shared_private_link_service` currently uses the latest stable version of the Rest API. So there is nothing that Terraform can do about this error. It is recommended to submit an issue [here ](https://github.com/Azure/azure-rest-api-specs/issues)to request help from the Rest API team.

Additionally, I assume that the following information might be useful to you.

-   `subresource_name` of Terraform corresponds to `Group ID` in the mentioned [documentation](https://learn.microsoft.com/en-us/azure/search/troubleshoot-shared-private-link-resources#request-validation-failures).
`search_service_id` of Terraform corresponds to `privateLinkResourceId` in mentioned documentation.
Per the documentation, I assume that the documentation for `Azure SQL Managed Instance (preview)` does not mention that the corresponding `Group ID` is `managedInstance`.

- Another point worth noting is "Resources marked with "(preview)" must be created using a preview version of the Management REST API versions." in the documentation.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
