### ISSUE TITLE
Release v3.89.0 introduces a breaking change for `azurerm_app_configuration_key` using key_vault_reference

### ISSUE THREAD

**Issue by gsmith077** [hashicorp/terraform-provider-azurerm#24639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

latest

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

azurerm_app_configuration_key

### Terraform Configuration Files

```hcl
resource "azurerm_app_configuration_key" "production" {
  configuration_store_id = var.app_config_id
  key                    = var.key_name
  type                   = "vault"
  label                  = "Production"
  vault_key_reference    = var.vault_key_versionless_id

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/gsmith077/e49067263334c773aa82fb4510cc0e6f
```

### Expected Behaviour

Considering no change to base terraform, an existing resource should be updated or identified as having no changes automatically.

### Actual Behaviour

See the debug output. A drift detection change threw errors on `terraform plan` when no changes had been performed in the modules.

I can't see anywhere else to put this: I'm not upset that a bugfix was created, and the PR author did nothing wrong.

I'm upset that it was released in a weekly cadence, broke my deployments and likely many others, and there was no indication in the release log that there were breaking changes.
The issue can be compensated for via the inclusion of a `lifecycle{ignore_changes=["value"]}` block on the impacted resource.

This information was inside the pull request, but things had to break through standard usage, and an investigation was required. Mitigation steps should have been listed as a breaking change on the release log directly, with either an explicit link to the expected steps for users or a reproduction of the required updates in the release log.

Text should be added to the documents (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration_key#vault_key_reference) that indicate the use of this argument requires the setting of the lifecycle. The example is updated, but no explanation of that example is provided.

### Steps to Reproduce

`terraform plan`

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/24565
https://github.com/hashicorp/terraform-provider-azurerm/pull/24582
https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.89.0

**Comment by hanjoe** [comment]
We're also facing issues using keyvault ref making 3.89.0 unusable for us. 
Error output is
`│ Error: while validating attribute 'value' (""): unexpected end of JSON input
│ 
│   with ******.azurerm_app_configuration_key.keyvault-ref,
│   on *****, in resource "azurerm_app_configuration_key" "keyvault-ref":
│    1: resource "azurerm_app_configuration_key" "keyvault-ref" {
│`

**Comment by elduddz** [comment]
#UsAsWell

**Comment by elduddz** [comment]
We have teams that pinned their provider to 3.84 and they are ok, but we cannot retroactively get backout these versions.

**Comment by SDanehy** [comment]
Having the same issue here

**Comment by gsmith077** [comment]
Just to reiterate and clarify for folks impacted by this:

A workaround/solution exists for restoring functionality. Inside your implementation of an `azurerm_app_configuration_key`, you can add the following block:

```hcl
resource "azurerm_app_configuration_key" "config-key" {
  name = "resource-name"
  [...]
  
  lifecycle {
      ignore_changes = [value]
  }
}
```

I don't fully know the impact of adding that, and it only seems to be required if `[vault_key_reference](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_configuration_key#vault_key_reference)` is set.

**Comment by teowa** [comment]
Hi, my apologies for introducing the bug in PR https://github.com/hashicorp/terraform-provider-azurerm/pull/24582. I have sent another PR #24702 to fix this. As a workaround, please pin the provider version to 3.88.0 or add a `ignore_changes` as suggested above. 
```hcl
  lifecycle {
      ignore_changes = [value]
  }
```

**Comment by rcskosir** [comment]
Thanks for the reporting on this @gsmith077 

Firstly, apologies for the inconvenience/impact here - until the fix goes out later this week if you're affected by this then we'd recommend pinning to the previous version of the Provider for the moment, which can be done using the required_providers block:

```tf
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.88.0"
    }
  }
}
```

Secondly, you are correct in that this breaking change should not have made it out in a minor release. We always strive to make these types of changes in major versions to avoid the impact you experienced here, or if it does go in a minor release a `BREAKING CHANGE` should have been added to the changelog both detailing why the change was being made in a minor version and how to work around it.

We greatly appreciate your feedback as it allows us to find areas of improvement in our processes and procedures. 

Thanks!

**Comment by danielnyari** [comment]
An acceptable workaround i found (without ignoring changes in the value) is to not specify type as `vault` but use the standard value with different content-type:


```HCL

resource "azurerm_app_configuration_key" "mykv_reference" {
    configuration_store_id = azurerm_app_configuration.this.id
    key = "some_secret"
    content_type = "application/vnd.microsoft.appconfig.keyvaultref+json;charset=utf-8"
    value = jsonencode({uri = "${azurerm_key_vault_secret.mysecret.id}"})

  
}
```
This way there is no JSON encoding error, and the App Config can recognize the KV reference.
