### ISSUE TITLE
terraform plan crashes on azurerm_storage_account_sas

### ISSUE THREAD

**Issue by suhancz** [hashicorp/terraform-provider-azurerm#2465]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.10
+ provider.azurerm v1.19.0

### Affected Resource(s)

* azurerm_storage_account_sas

### Terraform Configuration Files

```hcl
data "azurerm_storage_account_sas" "storage_storedvalue_1" {
  connection_string = "azurerm_storage_account.storage_storedvalue.primary_connection_string"
  https_only        = true

  resource_types {
    service   = true
    container = false
    object    = false
  }

  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }

  start  = "2018-12-04"
  expiry = "2099-12-31"

  permissions {
    read    = true
    write   = false
    delete  = false
    list    = true
    add     = false
    create  = false
    update  = false
    process = true
  }
}

output "sas_url_query_string_storedvalue_1" {
  value = "${data.azurerm_storage_account_sas.storage_storedvalue_1.sas}"
}

data "azurerm_storage_account_sas" "storage_storedvalue_2" {
  connection_string = "azurerm_storage_account.storage_storedvalue.primary_connection_string"
  https_only        = true

  resource_types {
    service   = true
    container = false
    object    = false
  }

  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }

  start  = "2018-12-04"
  expiry = "2099-12-31"

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
    update  = true
    process = true
  }
}

output "sas_url_query_string_storedvalue_2" {
  value = "${data.azurerm_storage_account_sas.storage_storedvalue_2.sas}"
}

data "azurerm_storage_account_sas" "storage_settlementbatch_1" {
  connection_string = "azurerm_storage_account.storage_settlementbatch.primary_connection_string"
  https_only        = true

  resource_types {
    service   = true
    container = false
    object    = false
  }

  services {
    blob  = true
    queue = false
    table = false
    file  = false
  }

  start  = "2018-12-04"
  expiry = "2099-12-31"

  permissions {
    read    = true
    write   = true
    delete  = true
    list    = true
    add     = true
    create  = true
    update  = true
    process = true
  }
}

output "sas_url_query_string_settlementbatch_1" {
  value = "${data.azurerm_storage_account_sas.storage_settlementbatch_1.sas}"
}
```

### Debug Output

See Panic Output.
### Panic Output

https://gist.github.com/suhancz/2a2404589c4b846499976f09ee63c6a0

### Expected Behavior

Terraform plan should have shown how the resources would be created.

### Actual Behavior

Terraform crashed on plan.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
N/A

### References
N/A

* #0000

**Comment by suhancz** [comment]
Also, please, take a look at the comment by @rnnr in the pull request https://github.com/hashicorp/go-azure-helpers/pull/16#discussion_r239785381 - I assume he found the main reason of the issue

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
