### ISSUE TITLE
Changing Storage Account immutability_policy forces resource replacement

### ISSUE THREAD

**Issue by itay-grudev** [hashicorp/terraform-provider-azurerm#24655]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0-rc2

### AzureRM Provider Version

3.85

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "protected-storage-account" {
  dynamic "immutability_policy" {
    for_each = var.protected_storage_retention_policy > 0 && ! var.initial_deployment ? [1] : []
    content {
      allow_protected_append_writes = true
      period_since_creation_in_days = var.protected_storage_retention_policy
      state = "Locked"
    }
  }
}
```

### Debug Output/Panic Output

```shell
# module.protected-storage.azurerm_storage_account.protected-storage-account must be replaced
...
      + immutability_policy { # forces replacement
          + allow_protected_append_writes = true
          + period_since_creation_in_days = 7
          + state                         = "Locked"
        }
```

### Expected Behaviour

Azure does not allow you to set an immutability policy of a storage account during its creation. Instead you should create it and then - enable it. For this reason we added an `initial_deployment` flag to have an intermediary state, where the storage account exists, but without the `immutability_policy`. After the first successful `terraform apply` we set the flag to `false`  to enable the `immutability_policy`.

At this point I expected that the `immutability_policy` gets added to the existing resource.

### Actual Behaviour

The resource is scheduled for replacement. This will definitely fail, as I mentioned earlier Azure does not allow you to set `immutability_policy` at storage account creation time.

### Steps to Reproduce

1. set `var.initial_deployment = true`
2. plan and apply
3. set `var.initial_deployment = false`
4. plan

**Comment by magodo** [comment]
@itay-grudev You shall be able to create the storage account with `immutability_policy`, while the state shall be in either "Disabled" or "Unlocked". Then for the follow up apply, you can change it back to "Locked".

**Comment by itay-grudev** [comment]
@magodo Worked like a charm. Thank you very much.
