### ISSUE TITLE
subnet changes with azurerm_private_dns_resolver_outbound_endpoint requires rebuild of endpoint

### ISSUE THREAD

**Issue by michaelkopf** [hashicorp/terraform-provider-azurerm#24660]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Hi everyone,

when updating a subnet with a private dns resolver outbound endpoint, the endpoint needs to be rebuilt. 
The subnet is locked by azure as long as there is an outbound dns resolver endpoint so no changes to the subnet are possible. 

As workaround I manually deleted the outbound endpoint. tf apply works afterwards.

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.86.0

### Affected Resource(s)/Data Source(s)

azurerm_subnet azurerm_private_dns_resolver_outbound_endpoint

### Terraform Configuration Files

```hcl
locals {
  location = "germanywestcentral"
}

resource "azurerm_resource_group" "rg" {
  location = local.location
  name     = "rg"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  address_space       = ["10.0.0.0/16"]
  location            = local.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "dns_resolver_outbound" {
  location            = local.location
  name                = "dns-resolver-outbound"
  resource_group_name = azurerm_resource_group.rg.name
  address_prefixes = ["10.0.1.0/28"]
  virtual_network_name = azurerm_virtual_network.vnet.name
  delegation {
    name = "Microsoft.Network.dnsResolvers"
    service_delegation {
      name    = "Microsoft.Network/dnsResolvers"
      actions = ["Microsoft.Network/virtualNetworks/subnets/join/action"]
    }
  }
}

resource "azurerm_private_dns_resolver" "test" {
  location            = local.location
  name                = "private-resolver"
  resource_group_name = azurerm_resource_group.rg.name
  virtual_network_id  = azurerm_virtual_network.vnet.id
}

resource "azurerm_private_dns_resolver_outbound_endpoint" "test" {
  location                = local.location
  name                    = "test"
  private_dns_resolver_id = azurerm_private_dns_resolver.test.id
  subnet_id               = azurerm_subnet.dns_resolver_outbound.id
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Subnet (Subscription: "XXXXXXXXXXXXXXXXXX"
│ Resource Group Name: "rg"
│ Virtual Network Name: "vnet"
│ Subnet Name: "dns-resolver-outbound"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InUseSubnetCannotBeUpdated" Message="Subnet DnsOutBoundSubnet is in use and cannot be updated." Details=[]
```

### Expected Behaviour

delete the private dns resolver outbound endpoint when changes are made to the subnet. Then apply changes and recreate the outbound endpoint.

### Actual Behaviour

the outbound endpoint remains untouched, changes to the subnet cannot be applied

### Steps to Reproduce

1. create all ressources (tf apply)
2. make changes to subnet in terraform (e.g. address prefixes)
3.  try to apply changes

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @michaelkopf‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
