### ISSUE TITLE
Azure SQL not associating user assigned identities

### ISSUE THREAD

**Issue by ETisREAL** [hashicorp/terraform-provider-azurerm#24673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.87.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "sql_server" {
  name                         = "${var.resources_prefix}-mssql-server"
  resource_group_name          = var.resource_group_name
  location                     = var.resource_group_location
  version                      = "12.0"
  administrator_login          = var.sql_server_admin_username
  administrator_login_password = var.sql_server_admin_password

  azuread_administrator {
    # Specifying an Azure Entra user
    #    login_username = azuread_user.mssql_admin_user.user_principal_name
    #    object_id      = azuread_user.mssql_admin_user.object_id
    # Using a User Assigned identity
    login_username = azurerm_user_assigned_identity.mssql_admin_managed_identity.name
    object_id      = azurerm_user_assigned_identity.mssql_admin_managed_identity.principal_id
    #    azuread_authentication_only = true # then administrator_login and administrator_login_password can be omitted
  }

  # Required if type is UserAssigned and should be combined with identity_ids
  primary_user_assigned_identity_id = azurerm_user_assigned_identity.mssql_admin_managed_identity.id
  identity {
    type         = "UserAssigned" # "SystemAssigned, UserAssigned"
    identity_ids = [
      azurerm_user_assigned_identity.mssql_admin_managed_identity.id,
      azurerm_user_assigned_identity.vm_iam_identity.id,
    ]
  }

  tags = {
    environment = "production"
  }

  depends_on = [azurerm_user_assigned_identity.mssql_admin_managed_identity]
}
```

### Debug Output/Panic Output

```shell
When creating a new resource, it literally never succeedes 

If updating the resource, the identities are not added. They can be seen from the console, but not associated
```

### Expected Behaviour

In the console I should see the association and it should allow using these resources for connecting

### Actual Behaviour

Resource creation fails with a timeout, even when extending the timeout to 45 minutes

**Comment by sinbai** [comment]
Hi @ETisREAL thanks for opening this issue. Could you please update the `Actual Behaviour` to let us know the details about `When creating a new resource, it literally never succeedes `?

**Comment by ETisREAL** [comment]
Hi @sinbai . Just updated the `Actual Behaviour` section

**Comment by sinbai** [comment]
Hi @ETisREAL thanks for the update. Unfortunately, I could not reproduce the issue. It works well with the following terraform configuration. It is recommended to confirm through the [TF_LOG](https://developer.hashicorp.com/terraform/internals/debugging) to see what happened when terraform apply.


![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/29bab5dd-8693-4b00-b32a-96eff36ef2df)

```

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.87.0"
    }
  }
}

provider "azurerm" {
  features {}
}


data "azurerm_client_config" "test" {}

resource "azurerm_resource_group" "test" {
  name     = "mssql-0131"
  location = "eastus"
}

resource "azurerm_user_assigned_identity" "test" {
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  name                = "test_identity_2112"
}
resource "azurerm_user_assigned_identity" "test2" {
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  name                = "test_identity_2112-2"
}

resource "azurerm_mssql_server" "test" {
  name                         = "acctestsqlserver0131"
  resource_group_name          = azurerm_resource_group.test.name
  location                     = azurerm_resource_group.test.location
  version                      = "12.0"
  administrator_login          = "DaveLister"
  administrator_login_password = "7h1515K4711"
  minimum_tls_version          = "1.2"

  azuread_administrator {
    login_username = azurerm_user_assigned_identity.test.name
    object_id      = azurerm_user_assigned_identity.test.principal_id
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.test.id,azurerm_user_assigned_identity.test2.id]
  }

  primary_user_assigned_identity_id            = azurerm_user_assigned_identity.test.id
}
```

**Comment by ETisREAL** [comment]
Maybe it was a temporary issue. Will give it a try again. Thank you for your time @sinbai :)
