### ISSUE TITLE
Errors adding AI instrumentation key to app settings

### ISSUE THREAD

**Issue by Leon99** [hashicorp/terraform-provider-azurerm#2469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.10
+ provider.azurerm v1.19.0
+ provider.null v1.0.0

### Affected Resource(s)

* azurerm_application_insights
* azurerm_app_service

### Terraform Configuration Files

```hcl
locals {
   ...
  ai_app_setting = "${map(
    "APPINSIGHTS_INSTRUMENTATIONKEY", "${azurerm_application_insights.ai.instrumentation_key}"
  )}"
}

resource "azurerm_application_insights" "ai" {
  name                = "${var.app_name}-${local.np_env}"
  location            = "${local.ai_location}"
  resource_group_name = "${module.common.monitoring_rg_prefix}-${local.np_env}-rg"
  application_type    = "Web"
}

resource "azurerm_app_service" "appservice" {
  count = "${var.create_as_slot ? 0 : var.count}"
...
  app_settings = "${merge(var.app_settings, local.ai_app_setting)}"
...
}
```

### Expected Behavior

AI resources are created and their instrumentation keys added to app services

### Actual Behavior
The first time the configuration was executed, TF showed that all the existing app settings are going to be removed, but instead of doing that it ended up with the following:
```
* module.staging-env.module.clientportal.azurerm_app_service_slot.appservice: azurerm_app_service_slot.appservice: diffs didn't match during apply. This is a bug with Terraform and
should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.10
    Resource ID: azurerm_app_service_slot.appservice
    Mismatch reason: extra attributes: app_settings.APPINSIGHTS_INSTRUMENTATIONKEY
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"app_settings.ASPNETCORE_ENVIRONMENT":*terraform.ResourceAttrDiff{Old:"Staging", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"app_settings.APPINSIGHTS_INSTRUMENTATIONKEY":*terraform.ResourceAttrDiff{Old:"", New:"(sensitive)", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```
The second time it ran successfully.
### Steps to Reproduce

1. `terraform apply`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
