### ISSUE TITLE
Support for Redis User

### ISSUE THREAD

**Issue by squeakymouse** [hashicorp/terraform-provider-azurerm#24692]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

On the `(PREVIEW) Data Access Configuration` tab of Azure Cache for Redis, there is the ability to add Redis users and assign them different access policies, e.g. Data Owner. Can this feature be added to Terraform?

### New or Affected Resource(s)/Data Source(s)

azurerm_redis_cache

**Comment by MichalSino** [comment]
Any new information about this?

For now I found workaround using AzApi provider:
resource "azapi_resource" "add-user" {
  type = "Microsoft.Cache/redis/accessPolicyAssignments@2023-08-01"
  name = "TestAPAssign"
  parent_id = azurerm_redis_cache.redis_cache.id
  body = jsonencode({
    properties = {
      accessPolicyName = "Data Owner"
      objectId         = ""
      objectIdAlias    = ""
    }
  })
}

@rcskosir / @mybayern1974  But It shows that could be resource something like that:

azurerm_redis_cache_accesspolicyassignment "apassign" {
   name = "TestAPAssign"
   redis_id =......
   role = "Data Owner"/"Data Contrubutor"/"Data Reader"
   principal_id = user_object_id
   principal_name = user_name
}

And another resource:
azurerm_redis_cache_accesspolicy {
   name = "TestAPAssign"
   redis_id =......
   permissions = "......"
}

**Comment by favoretti** [comment]
#25477 should fix this once I'm done with it
