### ISSUE TITLE
Support for adding tags to the oms_agent block on azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by Poltergeisen** [hashicorp/terraform-provider-azurerm#24712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I am blocked by Azure tagging policy when trying to deploy an AKS cluster. It complains when creating the OMS agent that it requires tags. 

According to the documentation, the oms_agent block does not support any tags. Is there a way to add them? If not -- can that be added to the module?

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "${var.prefix}-k8s"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "${var.prefix}-k8s"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_DS2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

  oms_agent {
    log_analytics_workspace_id      = azurerm_log_analytics_workspace.example.id
    msi_auth_for_monitoring_enabled = true
  }
}
```

**Comment by stephybun** [comment]
Thanks for raising this issue @Poltergeisen.

Looking at the documentation I don't believe that this is possible with the AKS API at the moment. You will have to raise an issue over on the [AKS repo](https://github.com/Azure/AKS) to have support for that added.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on the [AKS repo](https://github.com/Azure/AKS), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
