### ISSUE TITLE
azurerm_cdn_frontdoor_secret data source error: Invalid address to set

### ISSUE THREAD

**Issue by will-faro** [hashicorp/terraform-provider-azurerm#24731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.89.0

### Affected Resource(s)/Data Source(s)

azurerm_cdn_frontdoor_secret

### Terraform Configuration Files

```hcl
data "azurerm_cdn_frontdoor_secret" "tls_cert_secret" {
  name                = var.frontdoor_cert_secret_name
  profile_name        = var.frontdoor_name
  resource_group_name = var.frontdoor_resource_group
}
```
```


### Debug Output/Panic Output

```shell
│ Error: setting 'secret': Invalid address to set: []string{"secret", "0", "expiration_date"}
│ 
│   with data.azurerm_cdn_frontdoor_secret.tls_cert_secret,
│   on main.tf line 34, in data "azurerm_cdn_frontdoor_secret" "tls_cert_secret":
│   34: data "azurerm_cdn_frontdoor_secret" "tls_cert_secret" {
│ 
```
```


### Expected Behaviour

Data source should fetch data without error

### Actual Behaviour

Error thrown, data source unusable.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

_No response_

### References

_No response_

**Comment by antonina-uglianets** [comment]
Hi @will-faro 
I faced the same issue few days ago. Changing azurerm version to 3.57.0 helped me to fix it
azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.57.0"
    }

**Comment by OliDow** [comment]
Can confirm that downgrading from "3.103.1" to "3.57.0" removed the error but is hardly a fix :/

**Comment by qetza** [comment]
Any news on a fix in the newer version of the provider? It's getting difficult to stay on version "3.57.0" as we are missing new features.
