### ISSUE TITLE
Support outbound type migration for `azurerm_kubernetes_cluster`

### ISSUE THREAD

**Issue by stevehipwell** [hashicorp/terraform-provider-azurerm#24741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I'd like to be able to migrate the outbound type for an AKS cluster via the Terraform provider.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "default" {
  network_profile {
    outbound_type = "userAssignedNATGateway"
  }
}
```

### References

- https://azure.microsoft.com/en-us/updates/generally-available-outbound-type-migration-in-aks/

**Comment by qaiserali** [comment]
Hi,

This is still not working even using the latest version of azurerm.
I tried to migrate the outbound_type from loadBalancer to userDefinedRouting, but it still doesn't work, and the terraform is throwing the following error.

`Kubernetes Cluster Name: "xxx-xxx-xx"): performing CreateOrUpdate: unexpected status 400 with response: { │   "code": "InvalidUserDefinedRoutingWithLoadBalancerProfile", │   "details": null, │   "message": "UserDefinedRouting and load balancer profile are mutually exclusive. Please refer to http://aka.ms/aks/outboundtype for more details", │   "subcode": "", │   "target": "networkProfile.loadBalancerProfile" │  } `

Below is the code block of network_profile, and I don't have any settings related to load_balancer_profile in terraform

`network_profile { 
  dns_service_ip      = var.network_dns_service_ip 
  network_plugin      = var.network_plugin network_
  plugin_mode = var.network_plugin_mode 
  network_policy      = var.network_policy 
  outbound_type       = var.outbound_type 
  service_cidr        = var.network_service_cidr 
  pod_cidr            = var.network_pod_cidr 
}`
