### ISSUE TITLE
azurerm_monitor_diagnostic_setting - "log_analytics_destination_type" appears to be ignored

### ISSUE THREAD

**Issue by AlexcFrench** [hashicorp/terraform-provider-azurerm#24743]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.1

### AzureRM Provider Version

3.89.0_x5

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "RG1" {
  name     = "RG1"
  location = "UKSouth"
}

resource "azurerm_storage_account" "storageaccount" {
  name                     = "newstorageacct994"
  location                 = "UKSouth"
  account_replication_type = "LRS"
  resource_group_name      = azurerm_resource_group.RG1.name
  account_tier             = "Standard"

}

resource "azurerm_log_analytics_workspace" "LAW" {
  name                = "law1"
  location            = "UKSouth"
  resource_group_name = azurerm_resource_group.RG1.name
}

resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
  name                           = "diags"
  target_resource_id             = azurerm_storage_account.storageaccount.id
  log_analytics_workspace_id     = azurerm_log_analytics_workspace.LAW.id
  log_analytics_destination_type = "Dedicated"

  metric {
    category = "Transaction"
  }
  metric {
    category = "Capacity"
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/AlexcFrench/61cef311a22be04f8a28acb70335c3aa.js
```

### Expected Behaviour

Apply and then plan should not show any change required

### Actual Behaviour

Apply and then plan shows that the log type still needs to be set

### Steps to Reproduce

apply with the above code and then run another plan - it always shows it needs to add the setting :

  # azurerm_monitor_diagnostic_setting.diagnostic_settings will be updated in-place
  ~ resource "azurerm_monitor_diagnostic_setting" "diagnostic_settings" {
        id                             = "/subscriptions/_redacted_/resourceGroups/RG1/providers/Microsoft.Storage/storageAccounts/newstorageacct994|diags"
      + log_analytics_destination_type = "Dedicated"
        name                           = "diags"
        # (2 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }

### Important Factoids

standard Azure public cloud

**Comment by teowa** [comment]
Hi @AlexcFrench , thanks for submit this!

For some resource types (storageAccounts might be one of them), the `log_analytics_destination_type` is unconfigurable, but service API won't error out if the field is configured in request even it is unconfigurable. More details of the API behavior is posted in https://github.com/Azure/azure-rest-api-specs/issues/22400.

And some details of this field are posted at [the provider docs](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting#log_analytics_destination_type). To suppress the diff, would you try remove the `log_analytics_destination_type` field from diagnostic settings for storageAccount?

**Comment by MariusStorhaug** [comment]
I have no skills in Go, but it seems the property is implemented differently than the other properties on the resource:

From [internal/services/monitor/monitor_diagnostic_setting_resource.go:L555](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_diagnostic_setting_resource.go#L555):
```go
			logAnalyticsDestinationType := ""
			if resp.Model.Properties.LogAnalyticsDestinationType != nil && *resp.Model.Properties.LogAnalyticsDestinationType != "" {
				logAnalyticsDestinationType = *resp.Model.Properties.LogAnalyticsDestinationType
			}
			d.Set("log_analytics_destination_type", logAnalyticsDestinationType)
```

Other properties are implemented using `*props`.

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_diagnostic_setting_resource.go#L549C1-L553C5

From [internal/services/monitor/monitor_diagnostic_setting_resource.go:L549](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_diagnostic_setting_resource.go#L549):
```go
			partnerSolutionId := ""
			if props.MarketplacePartnerId != nil && *props.MarketplacePartnerId != "" {
				partnerSolutionId = *props.MarketplacePartnerId
				d.Set("partner_solution_id", partnerSolutionId)
			}
```
