### ISSUE TITLE
Java 21 support for azurerm_linux_function_app

### ISSUE THREAD

**Issue by antgustech** [hashicorp/terraform-provider-azurerm#24754]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Microsoft recently added support for Java 21 runtime in azure functions: https://azure.microsoft.com/en-us/updates/public-preview-azure-functions-support-for-java-21-on-linux/

When can we expect terraform resource to allow for Java 21 as only[ 8, 11 and 17 is currently supported](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app#java_version)?

### New or Affected Resource(s)/Data Source(s)

azurerm_3.90.0

### Potential Terraform Configuration

```hcl
application_stack {
      java_version = "21"
    }
```

**Comment by xiaxyi** [comment]
Thanks @antgustech for raising this issue,  added to my backlog. I'll share the progress here if there is any update.

**Comment by antgustech** [comment]
Is there any timeplan for when we might expect this to be implemented?

**Comment by terrafirmaownerdev** [comment]
I am requesting support for java_version = 21 for app services and functions, too.
