### ISSUE TITLE
Storage Account Static Website fails to create with BlockBlobPremiumStorage kind and Premium account tier

### ISSUE THREAD

**Issue by strakh-alex** [hashicorp/terraform-provider-azurerm#24782]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.10

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
account_kind = "BlockBlobStorage"
account_tier  = "Premium"
```

### Debug Output/Panic Output

```shell
* `access_tier` is only available for accounts of kind: [BlobStorage StorageV2 FileStorage]
```

### Expected Behaviour

BlockBlobStorage should be in the list of available kinds.

### Actual Behaviour

Creating a static website fails with the abovementioned error.

**Comment by dkuzmenok** [comment]
@stephybun 
That is probably introduced by this MR - https://github.com/hashicorp/terraform-provider-azurerm/pull/24496/files

**Comment by magodo** [comment]
Do you intended to use `account_tier = "Premium"` instead of `access_tier  = "Premium"`?

**Comment by strakh-alex** [comment]
> Did you intend to use `account_tier = "Premium"` instead of `access_tier = "Premium"`?

Correct, I use `account_tier = "Premium"`. 
The `access_tier` is set to `Hot`.

Update the description.

**Comment by dkuzmenok** [comment]
@magodo There is a check in storage resource that look strange:

```go

if d.Get("access_tier") != "" {
					if accountKind := d.Get("account_kind").(string); !slices.Contains(storageKindsSupportsSkuTier, storage.Kind(accountKind)) {
						return fmt.Errorf("`access_tier` is only available for accounts of kind: %v", storageKindsSupportsSkuTier)
					}
				}
```

Check is mixing `account_kind` and `access_tier` and error is pointing to `access_tier` while `account_kind` was verified.

**Comment by dkuzmenok** [comment]
https://learn.microsoft.com/en-us/azure/templates/microsoft.storage/storageaccounts?pivots=deployment-language-arm-template#storageaccounts-1

In general `kind` supported values are: 'BlobStorage', 'BlockBlobStorage', 'FileStorage', 'Storage', 'StorageV2'

And we have it splitted into HNS/non-HNS kinds:

```go
	storageKindsSupportsSkuTier = []storage.Kind{
		storage.KindBlobStorage,
		storage.KindStorageV2,
		storage.KindFileStorage,
	}
	storageKindsSupportHns = []storage.Kind{
		storage.KindBlobStorage,
		storage.KindStorageV2,
		storage.KindBlockBlobStorage,
	}
```

But only first one is used for validation (and so we get an error).
It probably check would either use mix of kinds to validation, or should take into account HNS value and compare different possible kinds.




</body>
</html>

**Comment by dkuzmenok** [comment]
@magodo Let me know, please, is anyone would work on the fix in the very near future, or we can contribute here.

**Comment by magodo** [comment]
@dkuzmenok `storageKindsSupportsSkuTier` is a list of `account_kind` that support `access_tier`, which means the `account_kind` not in this list can specify `access_tier`.

@strakh-alex In your case, for a `BlockBlobStorage`, if i specify the `accessTier` in the request, I'll get:

```json
{
    "error": {
        "code": "InvalidRequestPropertyValue",
        "message": "Account property Hot is invalid for the request."
    }
}
```

Also, if you have a storage account of `BlockBlobStorage` in the Portal, you'll see the setting as below:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7970698/fcf76428-c06f-43b4-bc54-98e7930294c8)

On the other hand, for a `StorageV2` account, you'll get:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7970698/04b60842-fe5c-4644-b790-864f3c06e9df)

So the above validation is to avoid user configuration error before apply time.

**Comment by gantvi01** [comment]
I am seeing similar issues in the 3.91 provider version. When I downgraded it to `version = "<3.80.0,"` it started working.

**Comment by magodo** [comment]
This issue duplicates to https://github.com/hashicorp/terraform-provider-azurerm/issues/24793, please find the detail and solution from that issue.
