### ISSUE TITLE
upgrade azure-sdk-for-go

### ISSUE THREAD

**Issue by sstarcher** [hashicorp/terraform-provider-azurerm#24795]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

authentication

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }
  backend "azurerm" {
    key = "xxxxxxxxxx.tfstate"
  }
}

provider "azurerm" {
  features {}

  subscription_id            = var.subscription_id
  tenant_id                  = var.tenant_id
  skip_provider_registration = true
}
```

### Debug Output/Panic Output

```shell
│ Error: building account: could not acquire access token to parse claims: running Azure CLI: exit status 1: ERROR: AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance. Trace ID: xxxxxxxxxxxxx Correlation ID: xxxxxxxxxx Timestamp: 2024-02-06 15:42:27Z
│ Interactive authentication is needed. Please run:
│ az login --scope https://graph.microsoft.com/.default
│
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on main.tf line 12, in provider "azurerm":
│   12: provider "azurerm" {
│
```

### Expected Behaviour

login works

### Actual Behaviour

login fails

### Steps to Reproduce

terraform plan

### References

Azure cli version 2.37 and above changed the way that the authentication is handled.  2.37 cli triggers a bug in our policies due to it trying to access resources that are not needed.  This is fixed in the latest azure cli 2.57.  My guess is that the version of the azure sdk that is being used due to being very old also has this same issue and that a newer version of the SDK would resolve this issue.

**Comment by magodo** [comment]
@sstarcher The underlying SDK that handles the authentication isn't bound to a specific version of Azure CLI. Instead, it delegates to an *executaion* of your locally installed Azure CLI to retrieve the token, similar as running `az account get-access-token`. This assumes you have already logged in. Look at [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli) for details.

So please check the CLI setup in your local environment.

**Comment by sstarcher** [comment]
Thank you
