### ISSUE TITLE
Azure Redis Cache active_directory_authentication_enabled Can Only Be True for Premium SKUs?

### ISSUE THREAD

**Issue by dpickeringjudge** [hashicorp/terraform-provider-azurerm#24796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.5

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache

### Terraform Configuration Files

```hcl
resource "azurerm_redis_cache" "cache" {
  name                          = "azure-cache"
  location                      = azurerm_resource_group.my_db[0].location
  resource_group_name           = azurerm_resource_group.my_db[0].name
  public_network_access_enabled = false
  family                        = "C"
  sku_name                      = "Basic"
  capacity                      = 0
  redis_configuration {
    active_directory_authentication_enabled = true
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: parsing Redis Configuration: The `active_directory_authentication_enabled` property requires a `Premium` sku to be set
│ 
│   with azurerm_redis_cache.cache[0],
│   on db.tf line 107, in resource "azurerm_redis_cache" "cache":
│  107: resource "azurerm_redis_cache" "cache" {
```

### Expected Behaviour

Expect Entra Auth to be enabled.

### Actual Behaviour

Validation error that suggests we need Premium SKU. 

Is there any documentation that supports this limitation? In the Portal we are able to configure Entra Auth on standard SKUs. Wondering why we've introduced this validation in the provider.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.

**Comment by dpickeringjudge** [comment]
Hello @rcskosir thanks for your response -- is it not a bug if their [documentation](https://learn.microsoft.com/en-us/azure/azure-cache-for-redis/cache-azure-active-directory-for-authentication) states that it's available in all SKUs yet the provider is requiring premium?

<img width="468" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/135984229/164bc432-40b1-4b4f-b4c5-08069daa6d02">

**Comment by rcskosir** [comment]
@dpickeringjudge Thanks for the additional information! I will go ahead and reopen this. I see in the screenshot you provided it says preview. I will do some digging around to see when the Premium SKU was added, this may be a bug, or it may be an enhancement thats needed, TBD.

**Comment by MichalSino** [comment]
@rcskosir Do we know when it will be fixed?

**Comment by pregress** [comment]
Please consider doing this together with: https://github.com/hashicorp/terraform-provider-azurerm/issues/24692 & also consider managing access policies.

So one can assign managed identites/ service principals to access the cache.
