### ISSUE TITLE
azurerm_container_group does not provision user assigned managed identity

### ISSUE THREAD

**Issue by cveld** [hashicorp/terraform-provider-azurerm#24809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.1

### AzureRM Provider Version

3.90

### Affected Resource(s)/Data Source(s)

azurerm_container_group

### Terraform Configuration Files

```hcl
resource "azurerm_container_group" "aci" {
...
identity {
    type         = "SystemAssigned, UserAssigned"
    identity_ids = ["someresourceid"]
  }
...
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The user assigned managed identity should be configured.

### Actual Behaviour

The user assigned managed identity is not added. Neither the type identity type is switched to "SystemAssigned, UserAssigned" and is stuck with "SystemAssigned":

 identity {
          ~ identity_ids = [
              + "someresourceid",
            ]
          ~ type         = "SystemAssigned" -> "SystemAssigned, UserAssigned"
            # (2 unchanged attributes hidden)
        }
}

After many applies, this is still reported by the plan.

### Steps to Reproduce

terraform apply

**Comment by tgolly** [comment]
I'm hitting this as well.

My terraform has this block:

~~~terraform
  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.xxx.id]
  }
~~~

But when running the apply with `TF_LOG=debug`, I can see the `PUT` request going to the Azure API and there is no "identity" block:

~~~json
{
    "location": "australiaeast",
    "name": "xxxxxxx",
    "properties": {
        "containers": [
            {
                "name": "xxxx",
                "properties": {
                    "command": [],
                    "image": "xxxxxxxx.azurecr.io/xxx/xxx:latest",
                    "ports": [
                        {
                            "port": 9999,
                            "protocol": "TCP"
                        }
                    ],
                    "resources": {
                        "requests": {
                            "cpu": 1,
                            "memoryInGB": 4
                        }
                    }
                }
            }
        ],
        "ipAddress": {
            "autoGeneratedDomainNameLabelScope": "xxx",
            "ports": [
                {
                    "port": 9999,
                    "protocol": "TCP"
                }
            ],
            "type": "Private"
        },
        "imageRegistryCredentials": [
            {
                "identity": "/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxxxxxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxx",
                "server": "xxxxxxxxxxx.azurecr.io"
            }
        ],
        "initContainers": [],
        "osType": "Windows",
        "restartPolicy": "Always",
        "sku": "Standard",
        "subnetIds": [
            {
                "id": "/subscriptions/xxxxxxxxxx/resourceGroups/xxxxxxxxxx/providers/Microsoft.Network/virtualNetworks/xxxxxxxxxx/subnets/xxxxx"
            }
        ],
        "volumes": []
    }
}
~~~

The payload should have an `identity` block [as documented here](https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi#deploy-using-an-azure-resource-manager-arm-template), like I specified in my resource.

**Comment by ning-kang** [comment]
Seems like the Update function for container group was not complete. Only tags are picked up for update. Raised a PR to allow updating managed identity.

**Comment by tgolly** [comment]
Can we please re-open this?

I'm not sure this bug is actually fixed.

I'm testing now with Terraform v.3.100.0 and I still don't see the identity block in the request in debug mode.



My terraform code contains this:

~~~terraform
  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.xxxxx.id]
  }
~~~

Again I'm trying to create the resource, and in the `PUT` request I don't see the `identity` block:

~~~json
{
    "location": "australiaeast",
    "name": "xxxxx",
    "properties": {
        "containers": [
            {
                "name": "xxxxx",
                "properties": {
                    "command": [],
                    "image": "xxxxxxxx.azurecr.io/xxxx/xxxx:latest",
                    "ports": [
                        {
                            "port": 80,
                            "protocol": "TCP"
                        }
                    ],
                    "resources": {
                        "requests": {
                            "cpu": 1,
                            "memoryInGB": 4
                        }
                    }
                }
            }
        ],
        "ipAddress": {
            "autoGeneratedDomainNameLabelScope": "Unsecure",
            "ports": [
                {
                    "port": 80,
                    "protocol": "TCP"
                }
            ],
            "type": "Private"
        },
        "imageRegistryCredentials": [
            {
                "identity": "/subscriptions/xxxxxxxxxxxxxxx/resourceGroups/xxxxxxxxxxx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/xxxxxxxxxxxxx",
                "server": "xxxxxxxxxxx.azurecr.io"
            }
        ],
        "initContainers": [],
        "osType": "Windows",
        "restartPolicy": "Always",
        "sku": "Standard",
        "subnetIds": [
            {
                "id": "xxxxxxxxxxxxxx"
            }
        ],
        "volumes": []
    },
    "tags": {
        "xxx": "xxxx"
    }
}
~~~
 
 So Im still getting this error, because the identity is not provided in the request [as per the doco](https://learn.microsoft.com/en-us/azure/container-instances/using-azure-container-registry-mi#deploy-using-an-azure-resource-manager-arm-template).
 
 > InvalidImageRegistryIdentity: The identity in the 'imageRegistryCredentials' of container group 'xxxx' not found in container group identity list.
