### ISSUE TITLE
Support for azurerm_sql_managed_database documentation

### ISSUE THREAD

**Issue by alselivonets** [hashicorp/terraform-provider-azurerm#24820]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In an argument reference block there's a wrong definition of the name. It says:
"name - (Required) The name of the SQL Managed _Instance_. Changing this forces a new resource to be created."
Instead of that it should say:
"(Required) The name of the SQL Managed _Database_. Changing this forces a new resource to be created."
The "name" argument refers to the name of a database, but not to the name of a SQL Managed Instance.

### New or Affected Resource(s)/Data Source(s)

azurerm_sql_managed_database

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_managed_database

**Comment by rithik56** [comment]
Hi @rcskosir , I have opened the PR for the above issue. Please check out.
