### ISSUE TITLE
deploying storage account with azurerm_storage_account always show '1 to change' in plan stage even there is no any changes for the storage account

### ISSUE THREAD

**Issue by jejass** [hashicorp/terraform-provider-azurerm#24834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

I tried to deploy a simple storage account by Terraform, I re-deployed same main.tf twice, it always told me 1 to change even there is no any changes for the proeprty.

resource "azurerm_storage_account" "storage_account" {
  resource_group_name = "arm-vscode"
  location            = "eastus"

  name = "junjiecaoterr4"

  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"

queue_properties{
  logging{
    read=true
    write=true
    delete=true
    **version = "1"**
  }
}

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">=1.0"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.9"
    }

    random = {
      source  = "hashicorp/random"
      version = "~>3.0"
    }
  }
}

provider "azurerm" {
  features {}
}
```

### Debug Output/Panic Output

```shell
azurerm_storage_account.storage_account: Refreshing state... [id=/subscriptions/a0956810-e74f-43f8-8d63-ef25dd1fbaeb/resourceGroups/arm-vscode/providers/Microsoft.Storage/storageAccounts/junjiecaoterr4]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # azurerm_storage_account.storage_account has been changed
  ~ resource "azurerm_storage_account" "storage_account" {
        id                                = "/subscriptions/a0956810-e74f-43f8-8d63-ef25dd1fbaeb/resourceGroups/arm-vscode/providers/Microsoft.Storage/storageAccounts/junjiecaoterr4"
        name                              = "junjiecaoterr4"
      + tags                              = {}
        # (38 unchanged attributes hidden)




        # (4 unchanged blocks hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the following plan may include actions to 
undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_storage_account.storage_account will be updated in-place
  ~ resource "azurerm_storage_account" "storage_account" {
        id                                = "/subscriptions/a0956810-e74f-43f8-8d63-ef25dd1fbaeb/resourceGroups/arm-vscode/providers/Microsoft.Storage/storageAccounts/junjiecaoterr4"
        name                              = "junjiecaoterr4"
        tags                              = {}
        # (38 unchanged attributes hidden)



      ~ queue_properties {


          ~ logging {
              ~ version               = "1.0" -> "1"
                # (4 unchanged attributes hidden)
            }

            # (2 unchanged blocks hidden)
        }

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 

Saved the plan to: main.tfplan

To perform exactly these actions, run the following command to apply:
    terraform apply "main.tfplan"
```

### Expected Behaviour

as there is no any changes for the storage account, 0 to change is expected.

### Actual Behaviour

no matter which value that I set for logging version, 1, 1.0, "1.0", always told me 1 to change.

### Steps to Reproduce

1.terraform apply
2. terraform plan

### References

no

**Comment by tombuildsstuff** [comment]
hey @jejass 

Taking a look through here this value is coming from the Azure API which is requiring/returning "1.0" here - as such you can resolve this diff by setting the value `1.0` rather than `1` in your Terraform configuration, so that this matches what Azure expects here.

Since this is a configuration question rather than a bug in the Azure Provider I"m going to close this issue for the moment, but should you have further configuration questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
