### ISSUE TITLE
Support for new SiteCredential policy on AzureRM for WebApps, Web Apps on Linux, Functions Apps on Windows and Linux

### ISSUE THREAD

**Issue by FinVamp1** [hashicorp/terraform-provider-azurerm#24866]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure App Service has introduced a new change that means the Site Credentials change depending on the date and time when the request has been made. ( I'm from Microsoft and the Azure App Service team)

az webapp deployment list-publishing-credentials command will retrieve this

E.G

  "publishingPassword": "AQKgAuFOXteWSpo82byZVaQOA1lPsgE.redacted",

If you request the same resource a few minutes later.

  "publishingPassword": "AQKgAuFOXteWSpo82byZVaQOA1pPsgE.redacted",

This setting is stored as part of the Terraform State and so this means that Terraform will detect a more frequent change to the plan than before and this is affecting a number of customers who have to reapply their plan state even though not much has changed. 

E.G.

azurerm_windows_web_app.example: Refreshing state... [id=subscriptions/{subid}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{sitename]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply" which may have affected this plan:

  # azurerm_windows_web_app.example has changed
  ~ resource "azurerm_windows_web_app" "example" {
        id                                            =subscriptions/{subid}/resourceGroups/{resourceGroupName}/providers/Microsoft.Web/sites/{sitename]"
        name                                           = "siteName"
      ~ site_credential                                = (sensitive value)
        tags                                           = {}

This change is rolling out at the moment and so this work item is to check if the AzureRM Provider could be adjusted to handle this change. As you can see above only part of the credentials change unless you reset the Publishing Profile credentials overall.
Perhaps the change could be based on the prefix that hasn't changed?

[Publish Profile Credentials](https://github.com/projectkudu/kudu/wiki/Deployment-credentials#site-credentials-aka-publish-profile-credentials)

### New or Affected Resource(s)/Data Source(s)

3.9.00

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  features {}
}
}


resource "azurerm_windows_web_app" "example" {
  # (other resource arguments...)
  name="TestFinbarSiteCerd"
  service_plan_id  = "/subscriptions/{subId}/resourceGroups/{rgName}/providers/Microsoft.Web/serverFarms/{serverFarmName"
  resource_group_name = "{rgName}"
  location = "{siteLocation}"
  webdeploy_publish_basic_authentication_enabled = false
  ftp_publish_basic_authentication_enabled  = false
  site_config{
    always_on = false #Testing on Free
    
  }


}
```

**Comment by tombuildsstuff** [comment]
hey @FinVamp1 

Thanks for opening this issue.

Just to double-check something:

> Azure App Service has introduced a new change that means the Site Credentials change depending on the date and time when the request has been made.
> This setting is stored as part of the Terraform State and so this means that Terraform will detect a more frequent change to the plan than before and this is affecting a number of customers who have to reapply their plan state even though not much has changed.

From this description it sounds like a breaking behavioural change has been made to an existing API version - per my understanding of the Azure Resource Manager specification those are supposed to be rolled out in a new API version (and/or go through the ARM Breaking Change review board).

Would you mind clarifying if this is being rolled out in an existing API version, or if this change is coming in a new API version?

Thanks!

**Comment by FinVamp1** [comment]
Thanks @tombuildsstuff  I'll check this and come back to you.

**Comment by drdamour** [comment]
@tombuildsstuff this isnt isolated to a new api…i get this “changes outside terraform” all the time starting a few months back..rather annoying

**Comment by cveld** [comment]
@FinVamp1 Why would you rotate this secret automatically? Most services if not all require an explicit rotation request.

**Comment by FinVamp1** [comment]
@tombuildsstuff  we are not using a new API Version for this and this was a resource provider management change. @cveld  I can't comment on our implementation for this change. The property is updated and this means that the plan needs to be updated. We are discussing what we can do on our side. Is there anything that Terraform can do?

**Comment by FinVamp1** [comment]
Hello there. for Azure App Services (including Azure Functions) this change has been rolled back and it should not affect Terraform state any longer. You should be able to verify this via  az webapp deployment list-publishing-profiles. Microsoft thanks you for the feedback and context to help reach this decision. I will close this issue.

**Comment by yirmio** [comment]
@FinVamp1 I'm still facing this issue (please ignore the app__plan_id, it is just uppercase letters change)
![Screenshot 2024-03-07 at 5 56 52](https://github.com/hashicorp/terraform-provider-azurerm/assets/4944071/74383fb7-7a10-4897-972e-e780e196697c)
Are you sure this issue is closed?

**Comment by FinVamp1** [comment]
@yirmio  can you let me know if you are still seeing this and if you're not comfortable sharing your app name then my email is finbar.ryan at microsoft.com
