### ISSUE TITLE
Add support for using a rolling upgrade policy on a scale set that has MaxSurge enabled

### ISSUE THREAD

**Issue by jmlaubach** [hashicorp/terraform-provider-azurerm#24898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently, when you create a Linux VMSS resource with the upgrade mode set to Rolling, and a rolling_upgrade_policy is set, you can only utilize the default behavior where VMs are brought down in patches to be updated. You are unable to use MaxSurge to change the behavior to where the rolling upgrade creates new VMs first before bringing old VMs down.

It would be helpful as the user to be able to enable the MaxSurge feature for Rolling Upgrade Policies on a scale set. This would allow for resource intensive applications running to not lose any resources by VMs in the scale set being brought down first rather than new VMs being created with updated settings.

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "example" {
  name                = "example-vmss"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Standard_F2"
  instances           = 1
  admin_username      = "adminuser"
  upgrade_mode        = "Rolling"

  rolling_upgrade_policy = {
    max_batch_instance_percent = 20
    max_unhealthy_instance_percent = 10
    max_unhealthy_upgraded_instance_percent = 10
    pause_time_between_batches = "PT10M"
    maxsurge = true
  }
```

**Comment by harshavmb** [comment]
Hi @jmlaubach ,

Thanks for opening this issue. At this point in time `MaxSurge` is still in preview mode. I have made changes & opened PR [here](https://github.com/hashicorp/terraform-provider-azurerm/pull/24914) but it is in draft mode. 

I ask for Hashicorp review when the stable version is released.

**Comment by jmlaubach** [comment]
@harshavmb 

Thanks for the update! Was wondering if this wasn't an option due to it still being in preview mode in Azure. Thank you!
