### ISSUE TITLE
azurerm_chaos_studio_experiment sets the incorrect selectors.target.type - should be ChaosTarget

### ISSUE THREAD

**Issue by luisfeliz79** [hashicorp/terraform-provider-azurerm#24899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_chaos_studio_experiment

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.91.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# Define some local variables
locals {
  prefix_name="chaos-CHANGE-ME"
  location="eastus"
}

# Create a resource group 
resource "azurerm_resource_group" "rg" {
  name     = "${local.prefix_name}-rg"
  location = local.location
}

# Create a user assigned managed identity (UAMI)
resource "azurerm_user_assigned_identity" "uami" {
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  name                = "${local.prefix_name}-testing-uami"
}

# Create a service bus namespace
resource "azurerm_servicebus_namespace" "servicebusns" {
  name                = "${local.prefix_name}-sbus"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"
}

# Create a queue in the service bus namespace
resource "azurerm_servicebus_queue" "sbqueue" {
  name         = "testqueue"
  namespace_id = azurerm_servicebus_namespace.servicebusns.id
  enable_partitioning = true
}

# Deploy permissions for the service bus namespace for the UAMI
resource "azurerm_role_assignment" "servicebus-rbac" {  
  scope                = azurerm_servicebus_namespace.servicebusns.id
  role_definition_name = "Azure Service Bus Data Owner"
  principal_id         = azurerm_user_assigned_identity.uami.principal_id
}

# Onboard the target service bus namespace to Chaos Studio
resource "azurerm_chaos_studio_target" "servicebus" {
  location           = azurerm_resource_group.rg.location
  target_resource_id = azurerm_servicebus_namespace.servicebusns.id
  target_type        = "Microsoft-ServiceBus"

}

# Add a capability for the Service Bus target
resource "azurerm_chaos_studio_capability" "servicebus-queue-disable" {
  chaos_studio_target_id = azurerm_chaos_studio_target.servicebus.id
  capability_type        = "ChangeQueueState-1.0"

}

# Create an experiment, leverage the User Assigned Managed Identity
resource "azurerm_chaos_studio_experiment" "example" {
  location            = azurerm_resource_group.rg.location
  name                = "${local.prefix_name}-TestServiceBusWithUAMI"
  resource_group_name = azurerm_resource_group.rg.name


  identity {
    type = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.uami.id]
  }

  selectors {
    name                    = "Selector1"    
    chaos_studio_target_ids = [azurerm_chaos_studio_target.servicebus.id]
  }

  steps {
    name = "Step 1"
    branch {
      name = "Branch 1"
      actions {
        urn           = azurerm_chaos_studio_capability.servicebus-queue-disable.urn
        selector_name = "Selector1"
        parameters = {
          queues = "[\"testqueue\"]"
          desiredState = "Disabled"
        }
        action_type = "discrete"

      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

The plan applies successfully as expected, but the configuration deployed is incorrect, leading to an error in error in the Portal editor for experiments.   The experiments do appear to work correctly regardless.
```

### Expected Behaviour

Expected behavior is for the the selectors[].targets[].type to be set to ChaosTarget
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/6314335/dccec50a-5810-451e-9cc1-cf1653003749)

### Actual Behaviour

The selectors[].targets[].type is set to the actual type of the target, which leads the error below in the portal
![7c9a7047-ec09-46b5-8e88-65db19091655](https://github.com/hashicorp/terraform-provider-azurerm/assets/6314335/ea37f475-6c43-4048-8d93-552883046fbb)

![5f3010bc-c5d8-4089-b018-dbea21597db1](https://github.com/hashicorp/terraform-provider-azurerm/assets/6314335/1789e203-f9f8-462d-b262-d9eef2ad5d58)

### Steps to Reproduce

terraform init
terraform plan -out my.plan
terraform apply my.plan

- Go to https://portal.azure.com
- Find the deployed resource group and view the experiment.
- click Edit while in the experiment overview screen
- Notice the error in the editor
- go back to the overview screen
- click on the JSON view to observe the selectors[].targets[].type, should be ChaosTarget

### References

Notice this REST API example, it uses "ChaosTarget"
 
https://learn.microsoft.com/en-us/rest/api/chaosstudio/experiments/create-or-update?view=rest-chaosstudio-2024-01-01&tabs=HTTP#:~:text=Create/update%20a%20Experiment%20in%20a%20resource%20group

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #24979 created by @neil-yechenwei for this issue.
