### ISSUE TITLE
Azure SQL Auditing with Log Analytics Workspace is not working

### ISSUE THREAD

**Issue by fjalcarazp** [hashicorp/terraform-provider-azurerm#24896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_mssql_server_extended_auditing_policy
azurerm_mssql_database_extended_auditing_policy

### Terraform Configuration Files

```hcl
# SOURCE: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/examples/sql-azure/sql_auditing_log_analytics/main.tf
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = var.location
}

resource "azurerm_mssql_server" "example" {
  name                         = "${var.prefix}-server-primary"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = var.location
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
}

resource "azurerm_mssql_database" "example" {
  name      = "${var.prefix}-db-primary"
  server_id = azurerm_mssql_server.example.id
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "${var.prefix}-LAW"
  location            = var.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_monitor_diagnostic_setting" "example" {
  name                       = "${var.prefix}-DS"
  target_resource_id         = "${azurerm_mssql_server.example.id}/databases/master"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id

  log {
    category = "SQLSecurityAuditEvents"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }

  lifecycle {
    ignore_changes = [log, metric]
  }
}

resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            = "${azurerm_mssql_server.example.id}/databases/master"
  log_monitoring_enabled = true
}

resource "azurerm_mssql_server_extended_auditing_policy" "example" {
  server_id              = azurerm_mssql_server.example.id
  log_monitoring_enabled = true
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

The azurerm resources «azurerm_mssql_database_extended_auditing_policy» and «azurerm_mssql_server_extended_auditing_policy» should link the Log Analytics Workspace in Azure Portal.

If you apply the azurerm example (https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/sql-azure/sql_auditing_log_analytics) the log analytics workspace is not linked in the Azure Portal.

According to the documentation, the azurerm provider offers the possibility of linking a Log analytics as a log destination, however, it does not seem that this is currently possible.

Additionally there seems to be a bug in this part of the code, as the database_id is incorrectly referenced:
```
resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            = "${azurerm_mssql_server.example.id}/databases/master"
  log_monitoring_enabled = true
}
```
I think the correction would be this:

```
resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            =  azurerm_mssql_database.example.id
  log_monitoring_enabled = true
}
```

### Actual Behaviour

Azure SQL Auditing is enabled without audit log destination.

### Steps to Reproduce

Apply the terraform provided and check the Azure SQL auditing and the destination of the logs.

**Comment by sinbai** [comment]
Hi @fjalcarazp thanks for opening this issue. I have fixed the wrong database id in [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/24920). Could you please make the following updates and try again?
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/b67c9172-f7dd-4874-b0af-95c27b412f1d)

**Comment by fjalcarazp** [comment]
I have just applied the code but the Azure SQL Auditing in the SQL Server is set to "enabled" but the log analytics is not set as Audit log destination.
The terraform code should set to "enabled" the Azure SQL Auditing in the SQL server and the database and set the Log analytics workspace as audit log destination.
![audit_sql_server](https://github.com/hashicorp/terraform-provider-azurerm/assets/73292476/6120ba62-6294-42c1-8e0e-f0e61d05bb0c)

**Comment by sinbai** [comment]
Thanks for the update @fjalcarazp. After testing, it was found that [this ](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/sql-azure/sql_auditing_log_analytics)example is actually just setting up sql server (excluding the database) auditing with log analytics workspace, which means that there are no errors in the example. It's really easy to misunderstand, but that's exactly why this example exists. If you would like to set up database at the same time, add the following configuration. Hope it's useful to you.
```

resource "azurerm_monitor_diagnostic_setting" "example-db" {
  name                       = "${var.prefix}-DS-db"
  target_resource_id         = azurerm_mssql_database.example.id
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id

  log {
    category = "SQLSecurityAuditEvents"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }

  lifecycle {
    ignore_changes = [log, metric]
  }
}

resource "azurerm_mssql_database_extended_auditing_policy" "example-db" {
  database_id            = azurerm_mssql_database.example.id
  log_monitoring_enabled = true
}
```

**Comment by fjalcarazp** [comment]
If [this](https://github.com/hashicorp/terraform-provider-azurerm/tree/main/examples/sql-azure/sql_auditing_log_analytics) example is just setting up the sql server auditing without the database: Why does it appear the azurerm_mssql_database_extended_auditing_policy?

```
resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            = "${azurerm_mssql_server.example.id}/databases/master"
  log_monitoring_enabled = true
}

resource "azurerm_mssql_server_extended_auditing_policy" "example" {
  server_id              = azurerm_mssql_server.example.id
  log_monitoring_enabled = true
}
```

So this resource is unnecessary in the example: 

```
resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            = "${azurerm_mssql_server.example.id}/databases/master"
  log_monitoring_enabled = true
}
```
On the other hand: do you know if it is necessary to create the database to set up the azure sql auditing in the sql server?

**Comment by sinbai** [comment]
After testing, `azurerm_mssql_database_extended_auditing_policy` is necessary, and `azurerm_mssql_database` is not necessary to set up the azure sql auditing in the sql server.

**Comment by fjalcarazp** [comment]
Ok, thank you very much for the clarification.
I suggest to delete the azurerm_mssql_database in the example to avoid confusion.

**Comment by bpelikan** [comment]
> After testing, `azurerm_mssql_database_extended_auditing_policy` is necessary, and `azurerm_mssql_database` is not necessary to set up the azure sql auditing in the sql server.

Do we really need  `azurerm_mssql_database_extended_auditing_policy` if we're talking about server auditing?
This is inherited from server, so I think it also not necessary here - I tested it and it works.
More in documentation (it's worth paying attention to the last sentence with a recommendation): [Auditing policy at the server and database level
](https://learn.microsoft.com/en-us/azure/azure-sql/database/auditing-server-level-database-level?view=azuresql)

I have similar issue as @fjalcarazp, in my case `terraform apply` ended up with selected `Event Hub` option and empty fields in Audit panel (I don't use Event Hub, only Log Analytics as destination), but despite of this I'm able to collect logs to Log Analytics.

I tried to recreate this issue on clean subscription (without Azure Policies etc.) with no success as it's works as it should, I see correct information in Audit panel. Maybe the cause was already existing diagnostic settings to another Log Analytics before enable auditing, but I'm not able to recrete this.

**Comment by fjalcarazp** [comment]
I think the ```azurerm_mssql_database_extended_auditing_policy``` is neccesary for audit logs in the SQL Server but you need to reference the SQL Server in  the resource like this:

```
resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            = "${azurerm_mssql_server.example.id}/databases/master"
  log_monitoring_enabled = true
}
```

If you deploy de SQL Server with the ```azurerm_monitor_diagnostic_setting``` resource with the ``` target_resource_id = "${azurerm_mssql_server.example.id}/databases/master" ``` you need to redeploy because it fails in the first attempt:

```
"The Resource 'Microsoft.Sql/servers/test-server-primary/databases/master' under resource group 'test-resources' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
```

If you want to enable the audit logs ONLY in the SQL Server the fixed final code it is (you don't need to create a sql database):

```
# SOURCE: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/examples/sql-azure/sql_auditing_log_analytics/main.tf
# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = var.location
}

resource "azurerm_mssql_server" "example" {
  name                         = "${var.prefix}-server-primary"
  resource_group_name          = azurerm_resource_group.example.name
  location                     = var.location
  version                      = "12.0"
  administrator_login          = "mradministrator"
  administrator_login_password = "thisIsDog11"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "${var.prefix}-LAW"
  location            = var.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_monitor_diagnostic_setting" "example" {
  # If it fails on the first attempt, apply again.
  name                       = "${var.prefix}-DS"
  target_resource_id         = "${azurerm_mssql_server.example.id}/databases/master"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id

  log {
    category = "SQLSecurityAuditEvents"
    enabled  = true

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = false
    }
  }

  lifecycle {
    ignore_changes = [log, metric]
  }
}

resource "azurerm_mssql_database_extended_auditing_policy" "example" {
  database_id            = "${azurerm_mssql_server.example.id}/databases/master"
  log_monitoring_enabled = true
}

resource "azurerm_mssql_server_extended_auditing_policy" "example" {
  server_id              = azurerm_mssql_server.example.id
  log_monitoring_enabled = true
}

```

The Azure SQL Auditing is enabled in the SQL Server rightly but the Azure Portal takes a few minutes to display the changes correctly.

I suggest at least removing the SQL database in the example to reduce confusion and maybe check the error given by the terraform apply in the first attempt.

**Comment by fjalcarazp** [comment]
Thank you very much.
I close the issue.
