### ISSUE TITLE
azurem_iothub endpoint connection string gets updated even when unchanged

### ISSUE THREAD

**Issue by pcharlan** [hashicorp/terraform-provider-azurerm#24907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_iothub

### Terraform Configuration Files

```hcl
resource "random_id" "random_suffix" {
  byte_length = 8 # Two hex chars per byte
}

locals {
  randsuffix = lower(random_id.random_suffix.hex)
}

resource "azurerm_resource_group" "rg" {
  name     = "rg-${local.randsuffix}"
  location = "eastus2"
}

resource "azurerm_storage_account" "iothub_storage_account" {
  name                     = "saiothub${local.randsuffix}"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  min_tls_version          = "TLS1_2"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  access_tier              = "Hot"
}

resource "azurerm_storage_container" "iothub_fallback" {
  name                  = "fallback"
  storage_account_name  = azurerm_storage_account.iothub_storage_account.name
  container_access_type = "private"
}

resource "azurerm_iothub" "iothub" {
  name                         = "iothub-${local.randsuffix}"
  resource_group_name          = azurerm_storage_account.iothub_storage_account.resource_group_name
  location                     = azurerm_storage_account.iothub_storage_account.location
  local_authentication_enabled = true

  sku {
    name     = "S1"
    capacity = 1
  }

  endpoint {
    type                       = "AzureIotHub.StorageContainer"
    connection_string          = nonsensitive(azurerm_storage_account.iothub_storage_account.primary_connection_string)
    name                       = "Fallback_IoT_Hub_Endpoint"
    batch_frequency_in_seconds = 60
    max_chunk_size_in_bytes    = 104857600 # 100MB
    container_name             = azurerm_storage_container.iothub_fallback.name
    encoding                   = "JSON"
    file_name_format           = "/year={YYYY}/month={MM}/day={DD}/hour={HH}/minute={mm}/{iothub}-{partition}"
  }

  cloud_to_device {
    max_delivery_count = 30
    default_ttl        = "PT1H"
    feedback {
      time_to_live       = "PT1H10M"
      max_delivery_count = 15
      lock_duration      = "PT30S"
    }
  }
}
```

### Debug Output/Panic Output

```shell
After initial plan and apply:
> terraform plan
[...]
  # azurerm_iothub.iothub will be updated in-place
  ~ resource "azurerm_iothub" "iothub" {
      ~ endpoint                     = [
          ~ {
              ~ connection_string          = "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=saiothub<redacted-account-suffix>;AccountKey=****" -> "DefaultEndpointsProtocol=https;AccountName=saiothub<redacted-account-suffix>;AccountKey=<redacted-key-value>==;EndpointSuffix=core.windows.net"
                name                       = "Fallback_IoT_Hub_Endpoint"
                # (11 unchanged attributes hidden)
```

### Expected Behaviour

The `plan` done immediately after the initial apply should have found nothing to do.

### Actual Behaviour

Terraform doesn't take into account the rearrangement of the components of the connection string so fails to see that nothing has changed.

### Steps to Reproduce

1. `terraform plan -out=tfplan.out`
2. `terraform apply tfplan.out`
3. `terraform plan`

**Comment by ziyeqf** [comment]
Hi @pcharlan, thanks for reporting.

The property `endpoint. connection_string` of `azurerm_iothub` is returned with `****` from the Azure backend Service, which might be due to safe concerns. So the provider can not dertermine if the `*` is as same as the value from `azurerm_storage_account`. So it will show the diff, and will update the value to the new one, even if they are the same.

A simple way to avoid the diff is adding it to `ignore_changes` parameter:
```terraform
resource "azurerm_iothub" "iothub" {
  name                         = "iothub-${local.randsuffix}"
  resource_group_name          = azurerm_storage_account.iothub_storage_account.resource_group_name
  location                     = azurerm_storage_account.iothub_storage_account.location
  local_authentication_enabled = true

  sku {
    name     = "S1"
    capacity = 1
  }

  endpoint {
    type                       = "AzureIotHub.StorageContainer"
    connection_string          = nonsensitive(azurerm_storage_account.iothub_storage_account.primary_connection_string)
    name                       = "Fallback_IoT_Hub_Endpoint"
    batch_frequency_in_seconds = 60
    max_chunk_size_in_bytes    = 104857600 # 100MB
    container_name             = azurerm_storage_container.iothub_fallback.name
    encoding                   = "JSON"
    file_name_format           = "/year={YYYY}/month={MM}/day={DD}/hour={HH}/minute={mm}/{iothub}-{partition}"
  }

  cloud_to_device {
    max_delivery_count = 30
    default_ttl        = "PT1H"
    feedback {
      time_to_live       = "PT1H10M"
      max_delivery_count = 15
      lock_duration      = "PT30S"
    }
  }

  lifecycle {
    ignore_changes = [ 
        endpoint.0.connection_string
     ]
  }
}
```

For any further questions please leave comments.

**Comment by ziyeqf** [comment]
> Hi @ziyeqf, thanks for your response!
> 
> What you say makes sense, but isn't this code designed specifically to ignore the difference between the stored representation of the AccountKey and the actual AccountKey?
> 
> https://github.com/hashicorp/terraform-provider-azurerm/blob/eaf257d5783b71c59e39ab0c239d65d8ec2f8a50/internal/services/iothub/iothub_endpoint_storage_container_resource.go#L130-L134
> 
> We can (and are) currently using lifecycle/ignore_changes to force TF to not care about changes in the connection string because that saves us almost two minutes per run, but this feels like a mildly dangerous hack. Isn't the code trying to ignore password changes itself, and merely failing to account for changes in the ordering of the string's individual sections?

This piece of code do intent to ignore the `accountKey` diff, while... The code seems to be wired and also not working.

Let's back to the design,  in my opnion, implicitly ignoring the diff might cause confusion. For example, if the `AccessKey` of `azurerm_storage_account` has been changed on Portal, apply the TF config will not update the correct value to `azurerm_iothub`.

**Comment by pcharlan** [comment]
If the hash of the access key could be stored and compared then that might be a good way to solve the problem without storing the key itself.

The issue of the components of the connection string being rearranged (while not otherwise changing) would still need to be worked out, as I think that's the main problem biting us here.

**Comment by ziyeqf** [comment]
> If the hash of the access key could be stored and compared then that might be a good way to solve the problem without storing the key itself.
> 
> The issue of the components of the connection string being rearranged (while not otherwise changing) would still need to be worked out, as I think that's the main problem biting us here.

Thanks for you component, you are correct. We should do something to avoid this kind diff. 

I have opened a PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/24956/files), once it merged & released, the issue should be fixed.

For any further questions please leave comments.
Thanks!

**Comment by pcharlan** [comment]
Thank you! ❤️ 

If there's an easy way for me to test this locally (such as if the PR creates a publicly-usable version I can test with) I'd be happy to test this out.

**Comment by ziyeqf** [comment]
> Thank you! ❤️
> 
> If there's an easy way for me to test this locally (such as if the PR creates a publicly-usable version I can test with) I'd be happy to test this out.

You can pull the provider repo and checkout the branch of the above PR:`ziyeqf:tengzh/issue/iothub_endpoint_connection_string` to build a provider binary locally and then follow [this document](https://developer.hashicorp.com/terraform/cli/config/config-file#development-overrides-for-provider-developers) to override the provider path to test.

While, I  do recommend to wait for the PR to be merged and released in new offical release. Because the code might change during review. And the provider built in this way is more "for developnment".
