### ISSUE TITLE
azurerm_linux_function_app_slot `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` are not created or maintained across applies correctly, causing slot swapping to eventually fail

### ISSUE THREAD

**Issue by SpektrixJb** [hashicorp/terraform-provider-azurerm#24901]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.91.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app_slot

### Terraform Configuration Files

```hcl
resource "random_integer" "random_identifier" {
  min = 10000
  max = 99999
}

resource "azurerm_resource_group" "function_rg" {
  name     = "func${random_integer.random_identifier.result}"
  location = "westeurope"
}

resource "azurerm_storage_account" "function_storage" {
  name                      = "func${random_integer.random_identifier.result}"
  resource_group_name       = azurerm_resource_group.function_rg.name
  location                  = azurerm_resource_group.function_rg.location
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  account_kind              = "StorageV2"
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
}

resource "azurerm_service_plan" "function_plan" {
  name                = "func-service-plan${random_integer.random_identifier.result}"
  location            = azurerm_resource_group.function_rg.location
  resource_group_name = azurerm_resource_group.function_rg.name
  os_type             = "Linux"
  sku_name            = "Y1"
}

resource "azurerm_linux_function_app" "function_app" {
  name                        = "func${random_integer.random_identifier.result}"
  location                    = azurerm_resource_group.function_rg.location
  resource_group_name         = azurerm_resource_group.function_rg.name
  service_plan_id             = azurerm_service_plan.function_plan.id
  storage_account_name        = azurerm_storage_account.function_storage.name
  storage_account_access_key  = azurerm_storage_account.function_storage.primary_access_key
  functions_extension_version = "~4"
  https_only                  = false
  builtin_logging_enabled     = false
  site_config {
    minimum_tls_version                    = 1.2
    http2_enabled                          = true
    ftps_state                             = "Disabled"
    application_stack {
      dotnet_version              = "8.0"
      use_dotnet_isolated_runtime = true
    }
  }
  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_linux_function_app_slot" "function_app_slot" {
  name                        = "staging"
  function_app_id             = azurerm_linux_function_app.function_app.id
  storage_account_name        = azurerm_storage_account.function_storage.name
  storage_account_access_key  = azurerm_storage_account.function_storage.primary_access_key
  functions_extension_version = "~4"
  https_only                  = false
  builtin_logging_enabled     = false
  site_config {
    minimum_tls_version                    = 1.2
    http2_enabled                          = true
    ftps_state                             = "Disabled"
    application_stack {
      dotnet_version              = "8.0"
      use_dotnet_isolated_runtime = true
    }
  }
  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
First Apply: https://gist.github.com/SpektrixJb/89e4a9e3d2634d690e0bc2fd7907cb80
Second Apply: https://gist.github.com/SpektrixJb/f95a475cf62d202c0b41a6d531aaf9dd
```

### Expected Behaviour

The linux app staging slot should have been created with the `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` settings set, like they are on the production slot. Swapping slots and re-deploying the function should work.****

### Actual Behaviour

The initial apply does not include the `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` settings on the deployment slot:
![1_MissingStagingSettings](https://github.com/hashicorp/terraform-provider-azurerm/assets/153078873/70711bbd-1676-4614-97ee-93600cb87f95)

If we then perform a slot swap, the settings get moved to the staging slot as expected
![2_AfterSlotSwap](https://github.com/hashicorp/terraform-provider-azurerm/assets/153078873/f5968fb0-0d8a-4c9c-813e-3e5b5eaef7d4)

However if we then apply a change to the Terraform which modifies the function app and staging slot, such as `https_only` then the settings appear to get moved to the production slot
![3_AfterApplyChangesTheFunction](https://github.com/hashicorp/terraform-provider-azurerm/assets/153078873/fce70479-0fda-4198-b3e9-09fa1fc2f316)

If we attempt another slot swap then we run into an error causing it to fail:
```
Failed to complete swap between slot 'staging' and slot 'production'. Error: {"_body":"{\"Code\":\"InternalServerError\",\"Message\":\"There was an unexpected error swapping slots 'staging' and 'production' for site 'func10455(staging)'. Please try to cancel your swap operation.\",\"Target\":null,\"Details\":[{\"Message\":\"There was an unexpected error swapping slots 'staging' and 'production' for site 'func10455(staging)'. Please try to cancel your swap operation.\"},{\"Code\":\"InternalServerError\"},{\"ErrorEntity\":{\"ExtendedCode\":\"04093\",\"MessageTemplate\":\"There was an unexpected error swapping slots '{0}' and '{1}' for site '{2}'. Please try to cancel your swap operation.\",\"Parameters\":[\"staging\",\"production\",\"func10455(staging)\"],\"Code\":\"InternalServerError\",\"Message\":\"There was an unexpected error swapping slots 'staging' and 'production' for site 'func10455(staging)'. Please try to cancel your swap operation.\"}}],\"Innererror\":null}","status":500,"ok":false,"statusText":"OK","headers":{"cache-control":["no-cache"],"content-length":["846"],"content-type":["application/json; charset=utf-8"],"date":["Thu"," 15 Feb 2024 15:06:54 GMT"],"etag":["\"1DA602094EA7E6B\""],"expires":["-1"],"pragma":["no-cache"],"server":["Microsoft-IIS/10.0"],"strict-transport-security":["max-age=31536000; includeSubDomains"],"x-aspnet-version":["4.0.30319"],"x-ms-correlation-request-id":["a9a70c7c-5214-43be-a025-38d5c75a231b"],"x-ms-failure-cause":["service"],"x-ms-ratelimit-remaining-subscription-writes":["1198"],"x-ms-request-id":["a9a70c7c-5214-43be-a025-38d5c75a231b"],"x-ms-routing-request-id":["UKSOUTH:20240215T150654Z:a9a70c7c-5214-43be-a025-38d5c75a231b"],"x-powered-by":["ASP.NET"]},"type":2,"url":"https://management.azure.com/subscriptions/f35423f1-0a9b-44d6-a4cb-452bc3c269c4/resourceGroups/func10455/providers/Microsoft.Web/sites/func10455/slots/staging/slotsswap?api-version=2018-11-01"}
```

I suspect the underlying cause is that the settings which should be required and managed by Azure are missing. Worse still, after the slot swap fails, the function slots seem to both end up with the same managed identity which is not a valid state - our only known way of getting out of this is to recreate the entire function app. We don't see the same issue on a windows function - both `WEBSITE_CONTENTSHARE` and `WEBSITE_CONTENTAZUREFILECONNECTIONSTRING` get set and maintained during slot swaps correctly.

### Steps to Reproduce

`terraform apply` to deploy the example
Swap the function app slots
Update a Terraform setting that will cause a change to the function app, such as `https_only`
`terraform apply` the change
Attempt to swap the slots again, this results in the failure

**Comment by tj-spyro** [comment]
A quick investigation into the differences between Linux/Windows and app/slot resources and when these 2 settings are set shows that the Linux slot resource is an outlier.

In the [Linux app resource](https://github.com/hashicorp/terraform-provider-azurerm/blob/7b39144c012f37267433ad98d797d01804f78d46/internal/services/appservice/linux_function_app_resource.go#L431) and both the [Windows app](https://github.com/hashicorp/terraform-provider-azurerm/blob/7b39144c012f37267433ad98d797d01804f78d46/internal/services/appservice/windows_function_app_resource.go#L436) and [slot resources](https://github.com/hashicorp/terraform-provider-azurerm/blob/7b39144c012f37267433ad98d797d01804f78d46/internal/services/appservice/windows_function_app_slot_resource.go#L451), the settings are set when the SKU is Elastic Premium or Consumption but in the Linux slot, we [only set for Elastic Premium](https://github.com/hashicorp/terraform-provider-azurerm/blob/7b39144c012f37267433ad98d797d01804f78d46/internal/services/appservice/linux_function_app_slot_resource.go#L434). The above is for a Consumption plan SKU.

**Comment by stephybun** [comment]
Thanks for opening this issue @SpektrixJb.

Is my understanding correct in that you are doing the slot swaps outside of Terraform? If so could you try using the resource `azurerm_function_app_active_slot` to do that swap instead and confirm whether you're still seeing the same behaviour?

**Comment by wyp84** [comment]
Same problem here, would be nice to have this fixed.

**Comment by SpektrixJb** [comment]
> Thanks for opening this issue @SpektrixJb.
> 
> Is my understanding correct in that you are doing the slot swaps outside of Terraform? If so could you try using the resource `azurerm_function_app_active_slot` to do that swap instead and confirm whether you're still seeing the same behaviour?

I'll make some time to try this soon. 

Ideally though I'd like to use slot swapping outside of Terraform. Managing the active slot through Terraform would require a Terraform change for each application deployment, a coupling which I don't think should be necessary.
