### ISSUE TITLE
azurerm_orchestrated_virtual_machine_scale_set: data_size -> disk_size_gb should not be mandatory when create_option=FromImage

### ISSUE THREAD

**Issue by mikeclayton** [hashicorp/terraform-provider-azurerm#24902]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.8

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

azurerm_orchestrated_virtual_machine_scale_set

### Terraform Configuration Files

```hcl
See "actual behaviour"
```

### Debug Output/Panic Output

```shell
See "actual behaviour"
```

### Expected Behaviour

See "actual behaviour"

### Summary

When creating an Azure Virtual Machine Scale Set using the ```azurerm_orchestrated_virtual_machine_scale_set``` resource, if the resource is based on an Azure Marketplace Image *and* if the Marketplace Image contains a data disk definition the resulting Azure scale set instance in the Azure Portal may end up having the ```"createOption": "FromImage"``` property set, and may not actually have a size specified for the data disk.

In this case, the size of the data disk when provisioning virtual machine instances in the scale set will ultimately be taken from the Marketplace Image definition.

Unfortunately, there's no way to represent this in an ```azurerm_orchestrated_virtual_machine_scale_set``` terraform resource because the ```data_disk -> disk_size_gb``` property is mandatory. This means  the ```terraform plan``` and ```terraform apply``` always detect drift in this resource once it's been created.

### Proposal

Make the appropriate ```data_disk``` properties (including ```disk_size_gb```, but *maybe* others as well ) *optional* when the ```create_option``` is set to ```FromImage``` so that virtual machines take the values from the Marketplace image when they're provisioned in the scale set.

### Workaround

One workaround is to:

* specify a ```data_disk``` block in the ```azurerm_orchestrated_virtual_machine_scale_set``` resource and match the size with the size of data disk in the Marketplace image - this effectively overrides the ```create_option = "FromImage"``` configuration
* apply the config, which eliminate the drift by setting set the ```data_size_gb``` on the live resource. Although this isn't *identical* to the original "missing" value it's functionally equivalent as it will create a data disk that matches the Marketplace Image definition (at least until the Marketplace Image definition changes).

The problem with this approach is that I think the Marketplace image can be redefined by the publisher and they could potentially change the size of the disk, in which case your ```azurerm_orchestrated_virtual_machine_scale_set``` resource locks the Virtual Machine Scale Set to old value.

### Additional Info

I found the issue while creating a scale set based on the USM Anywhere (a.k.a AlienVault) Marketplace Image but there's nothing particularly special about that image other than that it has a data disk specified in the Marketplace Image - you can see this with the following command:

```
C:\> az vm image show ^
    --urn "alienvault:unified-security-management-anywhere:unified-security-management-anywhere:8.0.49" ^
    --query "dataDiskImages"
[
  {
    "lun": 0,
    "sizeInBytes": 137438953984
  }
]
```

### Repro

1. Prepare an ```azurerm_orchestrated_virtual_machine_scale_set``` resource based on an Azure Marketplace image that has a data disk, but do not add a ```data_disk``` block - e.g. :

```
resource "azurerm_orchestrated_virtual_machine_scale_set" "alien-sensor-scaleset" {
  name                        = "myscaleset"
  location                    = "northerope"
  resource_group_name         = "myresourcegroup"
  ... snip ...

  # this particular marketplace image includes a 50gb os disk and a 128gb data disk
  source_image_reference {
    publisher = "alienvault"
    offer     = "unified-security-management-anywhere"
    sku       = "unified-security-management-anywhere"
    version   = "latest"
  }

  # specify the os disk details, but *not* the data disk
  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
    disk_size_gb         = 50
  }
  
   ... snip ...
}
```

2. Apply this resource, which will create a Virtual Machine Scale Set, and if you use the "Export Template" menu in the Azure Portal you'll see it contains this fragment, including ```"createOption": "FromImage"```:

```
... snip ...
"dataDisks": [
  {
    "lun": 0,
    "createOption": "FromImage",
    "caching": "None",
    "managedDisk": {
      "storageAccountType": "StandardSSD_LRS"
    },
    "deleteOption": "Delete"
  }
]
... snip ...
```

3. Running a ```terraform plan``` will show immediate drift because the plan detects the data disk on the Azure resource which was implicitly generated by the Azure API from the Marketplace Image, but isn't defined in the terraform source:

```
      - data_disk {
          - caching                        = "None" -> null
          - create_option                  = "FromImage" -> null
          - disk_size_gb                   = 0 -> null
          - lun                            = 0 -> null
          - storage_account_type           = "StandardSSD_LRS" -> null
          - ultra_ssd_disk_iops_read_write = 0 -> null
          - ultra_ssd_disk_mbps_read_write = 0 -> null
          - write_accelerator_enabled      = false -> null
        }
```

4. Trying to modify the terraform source to eliminate the drift is impossible because the ```data_disk -> disk_size_gb``` property is mandatory and cannot be set to match the live Azure scale set. If the ```data_disk``` is omitted then the ```tf plan``` wants to delete the one in the Azure Portal, and if a ```data_disk``` is added to the terraform source you have to specify a ```data_size_gb``` which means the ```tf plan``` wants to apply that to the live resource.

**Comment by harshavmb** [comment]
Hi @mikeclayton ,

Thanks for sharing detailed instructions on how to replicate the issue and I've managed to do that. 

I agree with you that `disk_size_gb` in `data_disk` should be an optional field like it's set part of `os_disk`. While replicating the issue I also found `lun` parameter too coming from `dataDiskImages` field. This means we have to apply similar changes to `lun` as well.

Now coming to the changes I intend to make on `azurerm` provider, I am facing below issues.

- Changing fields from `Required` to `Optional` could be considered as a breaking change. Nevertheless, in this case it's a bug rather enhancement. I assume it's okay. 
- I couldn't run test cases (already made necessary changes at my end) as Azure asks me to agree marketplace terms for `alienvault` publisher. I don't want to do that. Do you know any other image without the need of `plan` block and marketplace terms agreement & has data disk requirement? If yes, I could use the same for adding test case. 

Error I got ::

>  Error: creating Orchestrated Virtual Machine Scale Set (Subscription: "REDACTED"
│ Resource Group Name: "acctestRG-OVMSS-test"
│ Virtual Machine Scale Set Name: "acctestOVMSS-test"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" Message="User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: 'REDACTED' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='alienvault' offer = 'unified-security-management-anywhere', sku = 'unified-security-management-anywhere', Correlation Id: '71b235ea-8043-cce7-9bde-b45bf1d9f8be'.'"

Hope to from you!

**Comment by mikeclayton** [comment]
Hi @harshavmb 

Thanks for the quick reply. Hopefully changing from Required to Optional is less of a breaking change that going the other way - making it optional is a looser restriction so shouldn’t really stop any existing configurations from working :-).

I can’t search for any other images right now, but I can look later.

In the meantime you could look at the ```az vm image``` commands to list all Marketplace images and then iterate over them to look for one with a data disk in the json response…

Alternatively I assume it would be possible to make a custom image from an existing vm with a data disk and reference that rather than Marketplace image.

I can try to use ```as vm image``` later tonight and I’ll post some image ids you could try if you haven’t already found one yourself.

Cheers,

M

**Comment by mikeclayton** [comment]
@harshavmb - here's a random Marketplace image I found that has a data disk attached - it looks like a log aggregation app, but I've never used it before so I can't comment on what it actually does. Let me know if it's suitable, and I'll try to find a different one if not...

```
{
  "architecture": "x64",
  "automaticOsUpgradeProperties": {
    "automaticOsUpgradeSupported": false
  },
  "dataDiskImages": [
    {
      "lun": 0,
      "sizeInGb": 900
    }
  ],
  "disallowed": {
    "vmDiskType": "Unmanaged"
  },
  "extendedLocation": null,
  "features": [
    {
      "name": "IsAcceleratedNetworkSupported",
      "value": "False"
    }
  ],
  "hyperVGeneration": "V1",
  "id": "/Subscriptions/xxxxxxxxxxxxxxxx/Providers/Microsoft.Compute/Locations/westus/Publishers/micro-focus/ArtifactTypes/VMImage/Offers/arcsight-logger/Skus/arcsight_logger_72_byol/Versions/7.2.0",
  "imageDeprecationStatus": {
    "alternativeOption": null,
    "imageState": "Active",
    "scheduledDeprecationTime": null
  },
  "location": "westus",
  "name": "7.2.0",
  "osDiskImage": {
    "operatingSystem": "Linux",
    "sizeInGb": 100
  },
  "plan": {
    "name": "arcsight_logger_72_byol",
    "product": "arcsight-logger",
    "publisher": "micro-focus"
  },
  "tags": null
}
```

**Comment by harshavmb** [comment]
Hi @mikeclayton ,

Please subscribe to [#24944 ](https://github.com/hashicorp/terraform-provider-azurerm/pull/24944) for more details.
