### ISSUE TITLE
databricks storage account name and storage account tier not validated

### ISSUE THREAD

**Issue by mazzolia-prom** [hashicorp/terraform-provider-azurerm#24927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.9.2

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_databricks_workspace" "this" {
  name                = "prom-cust-${var.owner}-${local.environment}"
  resource_group_name = azurerm_resource_group.databricks.name
  location            = azurerm_resource_group.databricks.location
  sku                 = "premium"

  storage_account_name = "prom-cust-${var.owner}-${local.environment}"
  storage_account_sku_name = "Standard_LRS"

  custom_parameters {
    no_public_ip        = true
    public_subnet_name  = module.databrics_public_subnet_prod.name
    public_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.public.id
    private_subnet_name = module.databrics_private_subnet_prod.name
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id
    virtual_network_id  = module.vnet_fineco_prod.id
  }

  infrastructure_encryption_enabled = true

  network_security_group_rules_required = "AllRules"


  tags     = local.global_tags
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported argument
│ 
│   on fineco_databricks.tf line 13, in resource "azurerm_databricks_workspace" "this":
│   13:   storage_account_name = "prom-cust-${var.owner}-${local.environment}"
│ 
│ An argument named "storage_account_name" is not expected here.
╵
╷
│ Error: Unsupported argument
│ 
│   on fineco_databricks.tf line 14, in resource "azurerm_databricks_workspace" "this":
│   14:   storage_account_sku_name = "Standard_LRS"
│ 
│ An argument named "storage_account_sku_name" is not expected here.
```

### Expected Behaviour

to apply storage account name and tier to the databricks workspace

### Actual Behaviour

storage_account_sku_name
storage_account_name
are unexpected

### Steps to Reproduce

terraform apply

### Important Factoids

OSX 13.4 (22F66) ventura

### References

Terraform v1.7.3
on darwin_amd64
+ provider registry.terraform.io/databricks/databricks v1.36.3
+ provider registry.terraform.io/hashicorp/azuread v2.47.0
+ provider registry.terraform.io/hashicorp/azurerm v3.92.0

**Comment by WodansSon** [comment]
@mazzolia-prom, it appears that your parameters are in the incorrect location in the configuration that you supplied. The `storage_account_name` and `storage_account_sku_name` need to be in the `custom_parameters` code block of the configuration.

```HCL
  custom_parameters {
    no_public_ip        = true
    public_subnet_name  = module.databrics_public_subnet_prod.name
    public_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.public.id
    private_subnet_name = module.databrics_private_subnet_prod.name
    private_subnet_network_security_group_association_id = azurerm_subnet_network_security_group_association.private.id
    virtual_network_id  = module.vnet_fineco_prod.id
    storage_account_name = "prom-cust-${var.owner}-${local.environment}"
    storage_account_sku_name = "Standard_LRS"
  }
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @WodansSon‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
