### ISSUE TITLE
azurerm_federated_identity_credential requires audience attribute

### ISSUE THREAD

**Issue by rbtcollins** [hashicorp/terraform-provider-azurerm#24931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_federated_identity_credential

### Terraform Configuration Files

```hcl
resource "azurerm_federated_identity_credential" "api" {
  provider = azurerm.cdf_instance

  issuer              = var.cluster_oidc_issuer_url
  name                = "somename"
  parent_id           = azurerm_user_assigned_identity.api.id
  resource_group_name = azurerm_resource_group.api.name
  subject             = "system:serviceaccount:api:api"
}
```

is invalid because `audience` is required, but audience is not required for `az identity federated-credential create`, and is not used in the workload identity tutorial: https://learn.microsoft.com/en-us/azure/aks/learn/tutorial-kubernetes-workload-identity
```


### Debug Output/Panic Output

```shell
...
```

### Expected Behaviour

audience should not be required

**Comment by ziyeqf** [comment]
Hi @rbtcollins, thanks for opening the issue.

The CLI command has its default value for `audience`: `api://AzureADTokenExchange`. We did not add the default value to our provider becuase the rest api definition does not have the default value: https://github.com/Azure/azure-rest-api-specs/blob/a9fb3fa967eb2df4f4386358419a4f3f2f90a1ce/specification/msi/resource-manager/Microsoft.ManagedIdentity/stable/2023-01-31/ManagedIdentity.json#L720

Please leave comments for any further questions.
Thanks.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ziyeqf‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
