### ISSUE TITLE
Second terraform apply for PostgreSQL Flexible Server HA with a Read Replica

### ISSUE THREAD

**Issue by nickdala** [hashicorp/terraform-provider-azurerm#24949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
https://github.com/nickdala/azure-postgresql-terraform
```

### Debug Output/Panic Output

```shell
│ Error: updating Flexible Server (Subscription: ""
│ Resource Group Name: "rg-example"
│ Flexible Server Name: "psqlf-example2"): polling after Update: polling failed: the Azure API returned the following error:
│ 
│ Status: "InternalServerError"
│ Code: ""
│ Message: "An unexpected error occured while processing the request. Tracking ID: 'b0bd2e40-9c52-4b19-aa04-72045b13b622'"
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"name":"dc41259f-5d2d-4208-94fe-70282f7f0b23","status":"Failed","startTime":"2024-02-20T16:01:22.63Z","error":{"code":"InternalServerError","message":"An unexpected error occured while processing the request. Tracking ID: 'b0bd2e40-9c52-4b19-aa04-72045b13b622'"}}
│ -----[end]-----
│ 
│ 
│   with azurerm_postgresql_flexible_server.postgresql_database2,
│   on database.tf line 76, in resource "azurerm_postgresql_flexible_server" "postgresql_database2":
│   76: resource "azurerm_postgresql_flexible_server" "postgresql_database2" {
│
```

### Steps to Reproduce

The steps to reproduce the error can be found in the repo https://github.com/nickdala/azure-postgresql-terraform.  

A [Dev Container](https://code.visualstudio.com/docs/devcontainers/create-dev-container) is provided to help reproduce the issue.

Clone the repository.

```
git clone https://github.com/nickdala/azure-postgresql-terraform.git
cd azure-postgresql-terraform
```

You must first be authenticated to Azure and have the appropriate subscription selected.  To authenticate:

```shell
az login
```

Select the appropriate subscription:

```shell
az account set --subscription <subscription_id>
```

Then, to deploy the resources:

```shell
terraform init
terraform apply
```

At this point, we have two Postgres servers. A primary server and a read replica. 

To reproduce the bug, we will attempt to run `terraform apply` again.

```shell
terraform apply
```

**Comment by nickdala** [comment]
It looks like the issue is when the PostgreSQL server read replica is configured with high availability. I was not able to reproduce this bug once I removed HA from the [PostgreSQL Read Replica](https://github.com/nickdala/azure-postgresql-terraform/blob/main/database.tf#L92) 

```json
high_availability {
    mode = "ZoneRedundant"
    standby_availability_zone = 2
}
```

**Comment by mybayern1974** [comment]
@nickdala thank you for filing this issue. With noticing this issue may be duplicate with #20969 , I would suggest refer to that issue to see whether it could help. Though I'm closing this issue for being duplicate, feel free to suggest to reactivate this issue if you believe this issue is different from #20969.
