### ISSUE TITLE
Secrets cannot be removed from azurerm_container_app

### ISSUE THREAD

**Issue by GurliGebis** [hashicorp/terraform-provider-azurerm#24945]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
}
resource "azurerm_container_app" "example" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"

# Try and remove this after it has been applied.
  secret {
    name  = "dummy"
    value = "dummy"
  }

  template {
    container {
      name   = "examplecontainerapp"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: cannot remove secrets from Container Apps at this time due to a limitation in the Container Apps Service. Please see `https://github.com/microsoft/azure-container-apps/issues/395` for more details
│
│   with module.container-apps.azurerm_container_app.api,
│   on modules\container-apps\container-apps.tf line 46, in resource "azurerm_container_app" "api":
│   46: resource "azurerm_container_app" "api" {
```

### Expected Behaviour

Since the https://github.com/microsoft/azure-container-apps/issues/395 issue now has been fixed, this restriction should be removed.

### Actual Behaviour

The block is still in place, even though the upstream API has been fixed.

**Comment by DrizzlyOwl** [comment]
Still blocked by this in `3.99.0`

**Comment by mpigram1** [comment]
I'm also facing the same issue on `3.100.0`... This needs to be addressed as it's causing a lot of pain.
