### ISSUE TITLE
hashicorp/go-azure-sdk refactoring for azurerm_subscriptions - pagination and modelling issue

### ISSUE THREAD

**Issue by jschoombee** [hashicorp/terraform-provider-azurerm#24948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_subscriptions

### Terraform Configuration Files

```hcl
data "azurerm_subscriptions" "all" {
   //searching with a few thousand subscriptions in tenant 
}
```

### Debug Output/Panic Output

```shell
Less subscriptions in the tf state instances than expected.
```

### Steps to Reproduce

Use a version prior to 3.90.0 and all subscriptions (>1000) are returned. This [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/24663) seemed to have created the issue

I debugged the provider locally and managed to resolve the issue by dropping the `@odata` prefix for `nextLink` [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/416126a96abf4ee1500e5196b4e79b7aeffcd867/vendor/github.com/hashicorp/go-azure-sdk/sdk/odata/odata.go#L96)

Further `count` in the subscriptions response needed changing as it is not of type `int`. Below is what I ended up with which did the trick for me:

```golang
// OData is used to unmarshal OData metadata from an API response.
type OData struct {
	Context      *string `json:"@odata.context"`
	MetadataEtag *string `json:"@odata.metadataEtag"`
	Type         *Type   `json:"@odata.type"`
	Count        *Count  `json:"count"`
	NextLink     *Link   `json:"nextLink"`
	Delta        *Link   `json:"@odata.delta"`
	DeltaLink    *Link   `json:"@odata.deltaLink"`
	Id           *Id     `json:"@odata.id"`
	EditLink     *Link   `json:"@odata.editLink"`
	Etag         *string `json:"@odata.etag"`

	Error *Error `json:"-"`

	Value interface{} `json:"value"`
}

type Count struct {
	Type  *string `json:"type"`
	Value *int    `json:"value"`
}
```

### Important Factoids

Have a local branch to fix this issue and happy to submit but not sure if other resources/data sources depending on this package might be affected

### References

[PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/24663)

**Comment by jschoombee** [comment]
Sure,

I logged the raw responses when testing, below is a redacted snippet of the output. I haven't worked with the MS graph APIs much but it seems like OData was not implemented for subscriptions in azurerm - [api ref](https://learn.microsoft.com/en-us/rest/api/resources/subscriptions/list?view=rest-resources-2022-12-01&tabs=HTTP#subscriptionlistresult)

```json
{
    "value": [ 
        {
            "id": "/subscriptions/11111111-9f71-4226-ae1b-7995c4af4ccc",
            "authorizationSource": "RoleBased",
            "managedByTenants": [],
            "tags": {
                "redacted": 1
            },
            "subscriptionId": "11111111-9f71-4226-ae1b-7995c4af4ccc",
            "tenantId": "11111111-a3da-442a-1111-235cac24cd5c",
            "displayName": "redacted",
            "state": "Enabled",
            "subscriptionPolicies": {
                "locationPlacementId": "Public_2014-09-01",
                "quotaId": "EnterpriseAgreement_2014-09-01",
                "spendingLimit": "Off"
            }
        }
    ],
    "nextLink": "https://management.azure.com/subscriptions?$skipToken=redacted%3d&api-version=2022-12-01",
    "count": {
        "type": "Total",
        "value": 5297
    }
}
```

**Comment by BigFrog-coding** [comment]
Is there any progress on this? This is a blocking issue.

**Comment by jschoombee** [comment]
Confirm this bug still exists in `3.110.0`

**Comment by BigFrog-coding** [comment]
> Confirm this bug still exists in `3.110.0`

They dont seem to care or believe us

**Comment by jschoombee** [comment]
can we re-open?

**Comment by jschoombee** [comment]
Can this be re-opened?
