### ISSUE TITLE
##[error]provider "registry.terraform.io/hashicorp/vault" produced an unexpected new value: Root resource was present, but now absent.

### ISSUE THREAD

**Issue by tanglaojames** [hashicorp/terraform-provider-azurerm#24958]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

unknown

### Affected Resource(s)/Data Source(s)

unknown

### Terraform Configuration Files

```hcl
main.tf
=======
resource "vault_ldap_secret_backend_static_role" "role" {
  for_each        = var.Hashi_LDAPSSE_Roles
  mount           = each.value.ldap_secret_engine_path
  username        = each.value.appid
  dn              = each.value.dname
  role_name       = each.value.role_name #"${each.value.role_name}"
  rotation_period = var.token_ttl
}


providers.tf
============

terraform {
  backend "azurerm" {}
  required_providers {
    vault = {
      source = "hashicorp/vault"
      version = "3.25.0"
    }
  }
}

provider "vault" {
  # Configuration options
  address = var.vault_url
}


variables.tf
=============

variable "Hashi_LDAPSSE_Roles" {
  description = "Data From aggregated ldap static roles data, this schema should match the JSON hashi adse roles file."
  type = map(object(
    {
      appid_email: string,
      appid: string,
      role_name: string,
      environment: string,
      airid: string,
      dname: string,
      domain: string,
      ldap_secret_engine_path: string
    }
  ))
}

# variable "ldap_secret_engine_path" {
#   description = "(Required, Forces new resource) Path where the AD Secrets Engine is mounted"
#   type        = string
#   sensitive   = true
#   }


variable "token_ttl"{
  description = " (Optional) The incremental lifetime for generated tokens in number of seconds. Its current value will be referenced at renewal time."
  type        = string
  default     = 75*86400
}

variable "token_max_ttl"{
  description = "(Optional) The maximum lifetime for generated tokens in number of seconds. Its current value will be referenced at renewal time."
  type        = string
  default     = "8640000"
}

variable "vault_url" {
  description = "URL of vault server to use, this needs to match Azure Devops hashiVaultEnv in the pipelines.yaml file."
  type        = string
  default     = "https://xxxxxxxxxxx.com"
}
```

### Debug Output/Panic Output

```shell
##[error]provider "registry.terraform.io/hashicorp/vault" produced an unexpected new
value: Root resource was present, but now absent.
```

### Expected Behaviour

We are expecting to onboard and offboard without this error/info that causes the pipeline to fail

### Actual Behaviour

We can onboard but this error is showing and also when we try to deboard the static role using pipeline we can't offboard it after removing to our tfvars.json file.

we got 0 destroyed but the stage in pipeline succeeds.

When we try our personal token to add in providers.tf the error is removed but when using azurerm in providers.tf the error persists.
also even though we can remove the error by using our own token the pipeline can't deboard automatically the static role in vault.

**Comment by mybayern1974** [comment]
@tanglaojames thank you for filing this issue. While, I may suggest you file this issue to the Hashicorp Vault repository or Terraform Vault provider repository, because this repo is the project of `Terraform AzureRM provider`. Though the keyword `azurerm` appears in your TF config, it just means you are using Azure Storage to remotely store your TF state files, i.e. that `azurerm` has almost no relation with the project `Terraform AzureRM provider` this repo hosts.

**Comment by rcskosir** [comment]
@tanglaojames Thanks for taking the time to open this issue. Like @mybayern1974 says above, I suggest you open this issue in the [HashiCorp Vault Repo](https://github.com/hashicorp/vault) or the [Terraform Vault provider repo](https://github.com/hashicorp/terraform-provider-vault). Additionally you can try the [Community Resources](https://www.terraform.io/community). As such I am going to close this issue, if you have additional information on how this related to the Terraform AzureRM provider, leave us a comment and we can reopen.

**Comment by tanglaojames** [comment]
But when I try to Provision and Deprovision using same code but in local setup in Visual Code I can provision and deprovision without any error. the only changes I made in local setup is using a "token="hvs.xxxx" in a providers.tf file.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87511650/de03a649-d43f-4a72-80fc-6d58d409c3ac)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87511650/58557084-4cd8-461f-b381-1f9fbad1b197)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87511650/81907037-6c30-4c65-b983-b4aa53140a7b)
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87511650/89ed1769-1eb4-4dae-927e-ea69e128a33c)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87511650/a7bf6552-5474-4fed-b3dd-57113524255c)


So I tried to use the token in the Azure DevOps setup.
I got no error but when I try to deprovision I still fail to successfully delete the static role in Vault. But the TF Apply stage in our pipeline returns no error

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/87511650/07d6a8d6-b931-4b8b-bb35-8ce41e541036)
