### ISSUE TITLE
Support for defining target resource group for cluster_profile in azurerm_redhat_openshift_cluster

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/terraform-provider-azurerm#24959]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The ARM api has a property clusterProfile.resourceGroupId : https://learn.microsoft.com/en-us/azure/templates/microsoft.redhatopenshift/2023-07-01-preview/openshiftclusters?pivots=deployment-language-bicep#resource-format - but this property is not exposed in the azurerm equivalent.

This is handy in order to be able to define policies etc prior to provisioning the cluster. 

### New or Affected Resource(s)/Data Source(s)

redhat_openshift_cluster

### Potential Terraform Configuration

```hcl
cluster_profile {
  resource_group_id = <fullResourceIdOfTargetRg>
}
```

### References

https://learn.microsoft.com/en-us/azure/templates/microsoft.redhatopenshift/2023-07-01-preview/openshiftclusters?pivots=deployment-language-bicep#resource-format
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redhat_openshift_cluster

**Comment by martin-aders** [comment]
👍 This is also helpful if you want to create an identical cluster using the same domain name e.g. in a migration or recovery scenario. Currently, if you create a 2nd cluster using the same domain name you would end up having two clusters using the same resource group.
