### ISSUE TITLE
Support for Application Insights Standard Availability Tests

### ISSUE THREAD

**Issue by klemmchr** [hashicorp/terraform-provider-azurerm#24969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently only Classic Application Insights Availability Tests are supported using `azurerm_application_insights_web_test`. It would be great if Standard tests could be supported. Classic tests will be retired in 2026.

### New or Affected Resource(s)/Data Source(s)

azurerm_application_insights_web_test_standard

**Comment by teowa** [comment]
Hi @klemmchr , thanks for submitting this!
Application Insights Standard web tests should be supported in the [`azurerm_application_insights_standard_web_test`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_insights_standard_web_test) resource. Would you mind checking if this aligns with what you're looking for?

**Comment by klemmchr** [comment]
Sorry @teowa, I did not see this resource. It's quite weird that this resource does not pop up when searching for `test` in the documentation.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/6552521/88506de1-d8ca-4103-bfee-42d2b85ed142)
