### ISSUE TITLE
Support for azurerm_data_protection_backup_policy_flex_postgresql 

### ISSUE THREAD

**Issue by tonyign** [hashicorp/terraform-provider-azurerm#24970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure has rolled out this new feature in backup vault where we can choose a flex db and then enable backup for more than 35 days retention. Currently terraform only has resource for postgresql and not for flex_postgresql . It would really benefit a lot of people who have already migrated to flex since that is the long term db roadmap for pgsql in azure. 

### New or Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_policy_flex_postgresql 

### Potential Terraform Configuration

```hcl
resource "azurerm_data_protection_backup_policy_flex_postgresql" "pgsql_policy" {
  name                    = "pgsql-server-backup-policy"
  resource_group_name      = azurerm_data_protection_backup_vault.vault.resource_group_name
  vault_name               = azurerm_data_protection_backup_vault.vault.name

  # Database details
  server_name                  = "YOUR_PGSQL_FLEX_SERVER_ENDPOINT"
  database_name                = "*"        # Back up all databases

  # Daily backups
  backup_repeating_time_intervals = ["R/day"]
  default_retention_duration    = "P7D"     # Keep daily backups for 7 days

  # Weekly backups
  weekly_backup_retention_duration = "P84D"  # Keep weekly backups for 12 weeks (7 days * 12 weeks)

  # Monthly backups
  monthly_backup_retention_duration = "P1Y"   # Keep monthly backups for 12 months
}
```

**Comment by zameer712** [comment]
@mybayern1974 any progress on this module creation , it will benefit many of us .

can you please let us know the status on this
