### ISSUE TITLE
Typo in cosmosdb_account#identity

### ISSUE THREAD

**Issue by mrszop** [hashicorp/terraform-provider-azurerm#24986]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
No need to provide Terraform configuration files, since its only a small typo in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#identity block. The identity block says:

"type - (Required) The Type of Managed Identity assigned to this Cosmos account. Possible values are SystemAssigned, UserAssigned and SystemAssigned, UserAssigned."

SystemAssigned, UserAssigned is duplicated.
```

### Debug Output/Panic Output

```shell
---
```

**Comment by rcskosir** [comment]
@mrszop Thanks for taking the time to open this issue. This is not a typo in the documentation, I can see why it is confusing though. The options for type are 3 choices. Only `SystemAssigned`, only `UserAssigned` and both `SystemAssigned, UserAssigned`.
