### ISSUE TITLE
`azurerm_network_manager` tags always changed due to casing

### ISSUE THREAD

**Issue by ajaffie** [hashicorp/terraform-provider-azurerm#25018]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6

### AzureRM Provider Version

3.85

### Affected Resource(s)/Data Source(s)

azurerm_network_manager

### Terraform Configuration Files

```hcl
resource "azurerm_network_manager" "nm" {
  tags = {
    Tag1 = "tag 1",
    AnotherTag = "another tag",
  }
  // whatever required properties, only the tags are involved in the issue
}
```

### Debug Output/Panic Output

This is the plan output:
```
~ tags = {
  + "Environment" = "Production"
  + "ManagedBy"   = "Spacelift-TF"
  + "Stack"       = "core"
  - "environment" = "Production" -> null
  - "managedBy"   = "Spacelift-TF" -> null
    "purpose"     = "networking"
  - "stack"       = "core" -> null
}
```

### Expected Behaviour

No change.

### Actual Behaviour

The tags are detected as camel-case instead of pascal-case as they were created. The provider then tries to update the tags to match the configuration.

### Steps to Reproduce

1. Create an `azurerm_network_manager` resource and apply.
2. Run another plan. It will try to change the tags.

**Comment by AhalimZaki** [comment]
You can do something like the following 
resource "azurerm_network_manager" "nm" {
  tags = {
    Tag1 = "tag 1",
    AnotherTag = "another tag",
  }
  lifecycle {
    ignore_changes = [
      tags["Tag1 "],
      tags["AnotherTag "]
    ]
  }
}

Or 
resource "azurerm_network_manager" "nm" {
  tags = {
    Tag1 = "tag 1",
    AnotherTag = "another tag",
  }
  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

The 2nd one is not tested but it should work in theory.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @AhalimZaki‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
