### ISSUE TITLE
Support for delegation of subnet services in `azurerm_virtual_network` subnet blocks

### ISSUE THREAD

**Issue by rickardl** [hashicorp/terraform-provider-azurerm#25025]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

To align our organization with the Azure Cloud Adoption Framework (CAF) and adhere to Azure Policies, we've employed Terraform modules for streamlined network security and service deployments. A central aspect of this strategy is the deployment of vNet spokes connected to our central Hub. These spokes must support Microsoft Fabric and Container Apps, necessitating the ability to delegate subnets for seamless service integration.

Challenge with current separation between subnet and vNet resources

A key challenge stems from the Azure policy [Subnets should be associated with a Network Security Group](https://www.azadvertizer.net/azpolicyadvertizer/e71308d3-144b-4262-b144-efdc3cc90517.html). This mandates the attachment of Network Security Groups (NSGs) at the time of subnet creation. Due to this requirement, vNet creation becomes complex as it cannot proceed without pre-defined subnets and associated NSGs, demanding an integrated approach from the very beginning.

The current design of the azurerm_virtual_network resource presents a roadblock. It lacks support for configuring subnet delegation (recently implemented in this PR) and NSGs simultaneously. This limitation hinders many organizations' ability to comply with Azure's security best practices. The current design also prevents us from making this delegation a second day activity, because the subnet is now managed by an existing resource (as documented).

Potential Solution

A potential solution lies in extending the `azurerm_virtual_network` resource to enable delegation within subnet blocks. This enhancement would allow us to create vNets while simultaneously adhering to Azure's security policies.

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network" "test" {
  name                = "test-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  subnet {
    name           = "test-subnet"
    address_prefix = "10.0.1.0/24"
    security_group = azurerm_network_security_group.test_nsg.id

    delegation {
      name = "acitestdelegation"

      service_delegation {
        name    = "Microsoft.ContainerInstance/containerGroups"
        actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
      }
    }
  }

  tags = {
    environment = "Testing"
  }
}
```

### References

* https://learn.microsoft.com/en-us/azure/virtual-network/subnet-delegation-overview

**Comment by stephybun** [comment]
Thanks for opening this feature request @rickardl, we appreciate the comprehensive information on your use case.

Ultimately this appears to be asking for the same feature outlined in #3917. So that we can keep discussions on this issue consolidated and the tracking of it focused, I'm going to close this request in favour of #3917. Would you mind subscribing to #3917 for updates? Thanks!

**Comment by rickardl** [comment]
Absolutely 👍
