### ISSUE TITLE
Synapse workspace not setting AD Authentication to true

### ISSUE THREAD

**Issue by GurdipS5** [hashicorp/terraform-provider-azurerm#25023]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

3.4

### AzureRM Provider Version

3.9.3

### Affected Resource(s)/Data Source(s)

azurerm_synapse_workspace"

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_workspace" "main" {
  name                                 = "${var.business_unit}-${var.environment}-${lookup(local.short_locations, var.location)}-${local.identifier}-synws"
  resource_group_name                  = data.azurerm_resource_group.main.name
  location                             = var.location
  managed_resource_group_name          = "${var.business_unit}-${var.environment}-${lookup(local.short_locations, var.location)}-${local.identifier}-managedrg"
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = var.sql_admin_password
  public_network_access_enabled        = true
  managed_virtual_network_enabled      = true
  purview_id                           = var.purview_id
  storage_data_lake_gen2_filesystem_id = "https://${var.business_unit}0${var.environment}0${var.short_region}0xxx0sa.dfs.core.windows.net/landing"
  azuread_authentication_only          = true
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

AD Authentication should be enabled.

### Actual Behaviour

AD authentication is not enabled, as the portal reflects, and Azure Defender. Despite "azuread_authentication_only" set to true.

**Comment by ms-henglu** [comment]
Hi @GurdipS5 ,

Thank you for taking time to open this issue.

This feature is added in v3.78.0: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3780-october-26-2023, please update your azurerm version.
