### ISSUE TITLE
azurerm_private_dns_resolver_inbound_endpoint when method is set to static private_ip_address should provide static IP address

### ISSUE THREAD

**Issue by MaciejBrowarski** [hashicorp/terraform-provider-azurerm#25026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_private_dns_resolver_inbound_endpoint

### Terraform Configuration Files

```hcl
resource "azurerm_private_dns_resolver" "dns_resolver" { 
  name                = "dns"
  resource_group_name = "rg-resolver"
  location            = "westeurope"
  virtual_network_id  = data.azurerm_virtual_network.vnet.id
}

resource "azurerm_private_dns_resolver_inbound_endpoint" "inb_endp" {
  name                    = "input=1"
  private_dns_resolver_id = azurerm_private_dns_resolver.dns_resolver.id
  location                = "westeurope"

  ip_configurations {
    private_ip_allocation_method = "Static"
    private_ip_address = "10.0.0.4"
    subnet_id          = data.azurerm_subnet.sub.id
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Value for unconfigurable attribute
│
│   with azurerm_private_dns_resolver_inbound_endpoint.inb_endp["input-1"],
│   on privatednsresolver.tf line 23, in resource "azurerm_private_dns_resolver_inbound_endpoint" "inb_endp":
│   23:     private_ip_address = "10.0.0.4"
│
│ Can't configure a value for "ip_configurations.0.private_ip_address": its
│ value will be decided automatically based on the result of applying this
│ configuration.
```

### Expected Behaviour

Static allocatation method should set IP address from private_ip_address parameter.

### Actual Behaviour

private_ip_address parameter isn't acceptable by terraform provider an terraform not proceed with 'Static' ip allocation method.

### References

An ip_configurations block should accept the following:
private_ip_allocation_method - The private IP address allocation method.
subnet_id - The subnet ID of the IP configuration.
private_ip_address - The private IP address of the IP configuration. (use this address when method is Static)

Same as Data source for azurerm_private_dns_resolver_inbound_endpoint:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/private_dns_resolver_inbound_endpoint

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25035 created by @neil-yechenwei for this issue.
