### ISSUE TITLE
servicebus_namespace new premium_messaging_partitions support defaults to 0

### ISSUE THREAD

**Issue by benjaminwinokur** [hashicorp/terraform-provider-azurerm#25045]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.6.6

### AzureRM Provider Version

v3.93.0

### Affected Resource(s)/Data Source(s)

servicebus_namespace

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_namespace" "sb" {
  name                = module.naming.azure_service_bus_namespace
  resource_group_name = data.azurerm_resource_group.rg.name
  location            = data.azurerm_resource_group.rg.location

  sku                           = "Premium"
  capacity                      = 1
  zone_redundant                = true
  local_auth_enabled            = false
  minimum_tls_version           = 1.2
  public_network_access_enabled = false
  tags                          = merge(data.azurerm_resource_group.rg.tags, { creationTime = null }) // null to exclude tag with that key 
}
```

### Debug Output/Panic Output

```shell
# azurerm_servicebus_namespace.sb must be replaced
-/+ resource "azurerm_servicebus_namespace" "sb" {
      ~ default_primary_connection_string   = (sensitive value)
      ~ default_primary_key                 = (sensitive value)
      ~ default_secondary_connection_string = (sensitive value)
      ~ default_secondary_key               = (sensitive value)
      ~ endpoint                            = "https://private-internal-sb.servicebus.windows.net:443/" -> (known after apply)
      ~ id                                  = "/subscriptions/00000000-0000-0000-0000-00000000000/resourceGroups/resourcegroup-name/providers/Microsoft.ServiceBus/namespaces/private-namespace" -> (known after apply)
        name                                = "private-servicebusname"
      ~ premium_messaging_partitions        = 1 -> 0 # forces replacement
        tags                                = {
            "Owner"       = "Name"
            "ProjectCode" = "Code"
            "ProjectName" = "Name"
        }
        # (8 unchanged attributes hidden)

      - network_rule_set {
          - default_action                = "Allow" -> null
          - ip_rules                      = [] -> null
          - public_network_access_enabled = false -> null
          - trusted_services_allowed      = true -> null
        }
    }
```

### Expected Behaviour

There servicebus should not be recreated- it should default to 1 when the sku is set to "Premium"

### Actual Behaviour

Serviebus namespace is re-created

### Steps to Reproduce

terraform apply

**Comment by xiaxyi** [comment]
Thanks @benjaminwinokur for raising this issue, would you mind adding `ignore_changes` to the property `premium_messaging_partitions` or explicitly setting it to `1` in your config? I've shared some explanation about why we need to set the default value to `1` in issue #25007 . Thanks for your understanding!
