### ISSUE TITLE
Synapse workspace 'azuread_authentication_only' validation error

### ISSUE THREAD

**Issue by dumitrux** [hashicorp/terraform-provider-azurerm#25041]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.47.0

### Affected Resource(s)/Data Source(s)

azurerm_synapse_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_synapse_workspace" "example" {
  name                                 = "example"
  resource_group_name                  = azurerm_resource_group.example.name
  location                             = azurerm_resource_group.example.location

  storage_data_lake_gen2_filesystem_id = azurerm_storage_data_lake_gen2_filesystem.example.id
  sql_administrator_login              = "sqladminuser"
  sql_administrator_login_password     = "H@Sh1CoR3!"

  azuread_authentication_only = true

  aad_admin {
    login     = "AzureAD Admin"
    object_id = "00000000-0000-0000-0000-000000000000"
    tenant_id = "00000000-0000-0000-0000-000000000000"
  }

  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
Error: Terraform exited with code 1.
Error: Unsupported argument

  on synapse.tf line 10, in resource "azurerm_synapse_workspace" "synapse":
   8:   azuread_authentication_only          = var.enable_synapse_azuread_authentication_only

An argument named "azuread_authentication_only" is not expected here.
Error: Process completed with exit code 1.
```

### Expected Behaviour

The validation should have passed.

### Actual Behaviour

The validation of `azuread_authentication_only` throws an error.

### Steps to Reproduce

By running `terraform validate` with the default example and adding the `azuread_authentication_only` attribute.

### References

- [azurerm_synapse_workspace](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_workspace)

**Comment by ms-henglu** [comment]
Hi @dumitrux ,

Thank you for taking time to report this issue!

This feature is added in v3.7.8.0, please update the azurerm version.
https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3780-october-26-2023

**Comment by dumitrux** [comment]
Hi @ms-henglu,

It is working now, thanks!
I focused on using the most recent Terraform version, but overlooked the fact that I was not using the latest azurerm.
