### ISSUE TITLE
azurerm_key_vault_secret data source needs more privileges than should be required to read a secret

### ISSUE THREAD

**Issue by yhal-nesi** [hashicorp/terraform-provider-azurerm#25063]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.1.8

### AzureRM Provider Version

3.87.0_x5

### Affected Resource(s)/Data Source(s)

azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_secret" "example" {
  name         = "example"
  key_vault_id = "/subscriptions/xxx/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/vault"
}
```

### Debug Output/Panic Output

```shell
CLI works (az keyvault secret show ...). Terraform fails, relevant part of the log:

AzureRM Response for https://management.azure.com/subscriptions/xxxx/resourceGroups/rg/providers/Microsoft.KeyVault/vaults/vault?api-version=2023-02-01: 
HTTP/2.0 403 Forbidden

Looks like it tries to read properties of the vault, but I just want a secret value.
```

### Expected Behaviour

Data source contains secret properties.

### Actual Behaviour

403 error on "terraform plan"

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is as intended. As such I am going to mark this issue as closed. If you would like to provide more details about your specific case, we can consider a feature request as noted above.
