### ISSUE TITLE
servicebus premium partitioning unavailable

### ISSUE THREAD

**Issue by dave-irvine** [hashicorp/terraform-provider-azurerm#25073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace, azurerm_servicebus_queue

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_namespace" "namespace" {
  name                         = "test-servicebus-namespace"
  location                     = "eastus"
  resource_group_name          = "test-rg-name"
  sku                          = "Premium"
  zone_redundant               = true
  capacity                     = 2
  premium_messaging_partitions = 2
}

resource "azurerm_servicebus_queue" "queue" {
  name                = "test-servicebus-queue"
  namespace_id        = resource.azurerm_servicebus_namespace.namespace.id
  enable_partitioning = <true | false>
}
```

### Debug Output/Panic Output

```shell
> Non-partitioned entities are not allowed in partitioned namespace. The property EnablePartitioning must be set to true.

OR

> partitioning Entities is not supported in Premium SKU and must be disabled
```

### Expected Behaviour

A namespace and queue should be created.

Partitioning a premium namespace is available: https://learn.microsoft.com/en-us/azure/service-bus-messaging/enable-partitions-premium

### Actual Behaviour

Depending on whether partitioning on the queue is enabled or not, you either get a error saying partitioning must be enabled, or an error saying partitioning must be disabled.

### References

I can see in the past, partitioning in premium SKU was explicitly prevented in this module: https://github.com/hashicorp/terraform-provider-azurerm/pull/17599 but I believe partitioning in premium SKU is now available again: https://learn.microsoft.com/en-us/azure/service-bus-messaging/enable-partitions-premium

**Comment by xiaxyi** [comment]
Thanks @dave-irvine for raising this issue, let me check the feature and update the progress later.

**Comment by xiaxyi** [comment]
@dave-irvine I checked the doc and tested the feature, the result is as mentioned in the doc "All entities in this namespace will be partitioned.", so for premium namespace that have partition enabled, the partition will be enabled by default.  The feature is being updated, let me try removing the error message in terraform provider as well.
