### ISSUE TITLE
Update "AVS" to the correct name of "Azure VMware Solution" in public facing documentation

### ISSUE THREAD

**Issue by rvandenbedem** [hashicorp/terraform-provider-azurerm#25086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

azurerm_vmware_private_cloud, azurerm_vmware_cluster, azurerm_vmware_express_route_authorization, azurerm_vmware_netapp_volume_attachment

### Terraform Configuration Files

```hcl
N/A - requesting fixes to public facing documentation.
```

### Debug Output/Panic Output

```shell
N/A - requesting fixes to public facing documentation.
```

### Expected Behaviour

The correct name for "AVS"/"VMware (AVS)" is "Azure VMware Solution".

Requesting that this site is updated: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vmware_private_cloud

Issue 1: In AzureRM Table of Contents on LHS of browser - "VMware (AVS)" is updated to "Azure VMware Solution".

Issue 2: In each resource page "VMware Private Cloud" is updated to "Azure VMware Solution private cloud".

Issue 3: In each resource page "VMware Cluster" is updated to "Azure VMware Solution cluster".

Issue 4: In each resource page "The password of the vCenter admin" is updated to "The password of the vCenter Server admin".

Issue 5: In each resource page "Express Route" is updated to "Azure ExpressRoute".

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/102744761/3572d9f7-a925-4a6a-94d9-8efb07afa689)

### Actual Behaviour

N/A - requesting fixes to public facing documentation.

### Steps to Reproduce

Visit this site: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vmware_private_cloud

### Important Factoids

N/A - requesting fixes to public facing documentation.

### References

N/A - requesting fixes to public facing documentation.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #25191. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
