### ISSUE TITLE
azurerm_linux_function_app documentation has a typo for tenant_auth_endpoint parameter

### ISSUE THREAD

**Issue by besarbaugh** [hashicorp/terraform-provider-azurerm#25087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.x

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
tenant_auth_endpoint - (Required) The Azure Tenant Endpoint for the Authenticating Tenant. e.g. https://login.microsoftonline.com/v2.0/{tenant-guid}/

URL format should be https://login.microsoftonline.com/{tenant-guid}/v2.0/
```

### Debug Output/Panic Output

```shell
tenant_auth_endpoint - (Required) The Azure Tenant Endpoint for the Authenticating Tenant. e.g. https://login.microsoftonline.com/v2.0/{tenant-guid}/

URL format should be https://login.microsoftonline.com/{tenant-guid}/v2.0/
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app

**Comment by xiaxyi** [comment]
Thanks @besarbaugh for raising this issue, let me check the feature, will modify the doc once confirmed.

**Comment by Chambras** [comment]
Yeah, you are correct. I will submit a PR with the update and some links to the documentation as reference.
