### ISSUE TITLE
Support for `resourceSelector` in `azurerm_policy_definition`

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#25096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure Policy now support natively resource selectors. See reference for more info.

### New or Affected Resource(s)/Data Source(s)

azurerm_policy_definition

### Potential Terraform Configuration

```hcl
resource "azurerm_policy_definition" "this" {
resource_selectors = <<JSON
        [
            {
                "name": "SDPRegions",
                "selectors": [
                    {
                        "kind": "resourceLocation",
                        "in": [ "eastus", "westus" ]
                    }
                ]
            }
        ]
JSON
```

### References

* https://learn.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#resource-selectors-preview

**Comment by diecav** [comment]
Hello guys,

same for the Policy Exemptions. The resourceSelectors is currently missing.

https://learn.microsoft.com/en-us/azure/governance/policy/concepts/exemption-structure#resource-selectors

**Comment by jkroepke** [comment]
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment

`resource_selectors` are now present
