### ISSUE TITLE
Databricks managed resource group fails to autogenerate when using modules

### ISSUE THREAD

**Issue by TravBricks** [hashicorp/terraform-provider-azurerm#25090]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

2.99.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
## main.tf
data "azurerm_resource_group" "workspace_rg" {
  name = "your_existing_rg"
}

module "workspace_1" {
  source = "./modules/databricks_workspace"
  workspace_name = "terraform_ws_1_adb"
  resource_group_name = data.azurerm_resource_group.workspace_rg.name
  resource_group_location = data.azurerm_resource_group.workspace_rg.location
}

module "workspace_2" {
  source = "./modules/databricks_workspace"
  workspace_name = "terraform_ws_2_adb"
  resource_group_name = data.azurerm_resource_group.workspace_rg.name
  resource_group_location = data.azurerm_resource_group.workspace_rg.location
}

## Module relevant
resource "azurerm_databricks_workspace" "this" {
  name                        = var.workspace_name
  resource_group_name         = var.resource_group_name
  location                    = var.resource_group_location
  sku                         = var.workspace_sku
}
```

### Debug Output/Panic Output

```shell
Shows success, but 2nd workspace failed... subsequent terraform applies fail with this message:
Error: Invalid template interpolation value
│ 
│   on modules/databricks_workspace/output.tf line 10, in output "workspace_url":
│   10:   value       = "https://${azurerm_databricks_workspace.this.workspace_url}/"
│     ├────────────────
│     │ azurerm_databricks_workspace.this.workspace_url is null
│ 
│ The expression result is null. Cannot include a null value in a string template.

The workspaces in Azure Portal show the same MRG name for both workspaces.
```

### Expected Behaviour

When the optional `managed_resource_group_name` is not included a unique MRG name should be generated and used by the workspace.

### Actual Behaviour

There is a `managed_resource_group_name` reused for both workspaces resulting in a failed deployment for the second workspace.

### Steps to Reproduce

1. Build a simple terraform project with azurerm
2. Create a module for creating a workspace
3. Use the module twice creating uniquely named workspaces within the same parent resource group
4. Init = success
5. Plan = success
6. Apply = reported success
7. Azure portal shows otherwise
<img width="802" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/105364552/70349f4e-fedc-4c18-bd99-d8cf5719dd8a">

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace#managed_resource_group_name

**Comment by rcskosir** [comment]
Thanks for opening this issue. You've listed that this is an issue in the 2.x version of the provider which is no longer actively maintained.
If you are able to upgrade and this is still an issue with the 3.x version of the provider please do let us know and we can reopen this issue.

**Comment by TravBricks** [comment]
My bad, same thing happened with v3.93.0

Error:
```
Error: creating/updating Workspace (Subscription: "[redact]"
│ Resource Group Name: "terraform_travislongwell-rg"
│ Workspace Name: "[redact]"): polling after CreateOrUpdate: polling failed: the Azure API returned the following error:
│ 
│ Status: "ApplianceProvisioningFailed"
│ Code: ""
│ Message: "The managed resource group '/subscriptions/[redact]/resourceGroups/databricks-rg-terraform-rg' already exists. Please specify a new non-existent managed resource group"
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {
│   "status": "Failed",
│   "error": {
│     "code": "ApplianceProvisioningFailed",
│     "message": "The managed resource group '/subscriptions/[redact]/resourceGroups/databricks-rg-terraform-rg' already exists. Please specify a new non-existent managed resource group"
│   }
│ }
│ -----[end]-----
│ 
│ 
│   with module.workspace_2.azurerm_databricks_workspace.this,
│   on modules/databricks_workspace/workspace.tf line 1, in resource "azurerm_databricks_workspace" "this":
│    1: resource "azurerm_databricks_workspace" "this" {
│ 
```


TF version and azurerm provider version:
```
Terraform v1.5.7
on darwin_arm64
+ provider registry.terraform.io/hashicorp/azurerm v3.93.0
```

**Comment by TravBricks** [comment]
I updated to v3.9.3 and confirmed that it provides more feedback about the
error, but still behaves incorrectly.
