### ISSUE TITLE
temporary_name_for_rotation - not respecting PodDisruptionBudget

### ISSUE THREAD

**Issue by dkirrane** [hashicorp/terraform-provider-azurerm#25119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.6

### AzureRM Provider Version

3.73.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {

  # SNIP

  default_node_pool {
    name                        = local.default_node_pool_name
    temporary_name_for_rotation = local.default_node_pool_name_tmp
    os_disk_size_gb             = var.os_disk_size_gb
    # SNIP
  }

  # SNIP
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

I would expect the Deployment to drain 1 Pod at a time to respect the PodDisruptionBudget.

### Actual Behaviour

Deployment (3 replicas):
```
kubectl get deploy sample -n testing
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
sample   3/3     3            3           2m40s
```

PodDisruptionBudget:
```
kubectl describe pdb sample -n testing
Name:             sample
Namespace:        testing
Max unavailable:  1
Selector:         app.kubernetes.io/instance=sample,app.kubernetes.io/name=sample
Status:
    Allowed disruptions:  1
    Current:              3
    Desired:              2
    Total:                3
```

During Node pool rotation the Deployment goes to zero replicas:
```
kubectl get deploy sample -n testing -w
NAME     READY   UP-TO-DATE   AVAILABLE   AGE
sample   3/3     3            3           2m40s
sample   2/3     2            2           6m52s
sample   2/3     3            2           6m52s
sample   1/3     2            1           6m52s
sample   1/3     3            1           6m52s
sample   0/3     2            0           6m54s
sample   0/3     3            0           6m54s
sample   1/3     3            1           7m28s
sample   2/3     3            2           7m33s
sample   3/3     3            3           7m40s
``` 

### Steps to Reproduce

- Create a PDB with `maxUnavailable: 1`
- Enable temporary_name_for_rotation
- Change the default nodepool config e.g. change os_disk_size_gb
- terraform plan apply
- watch deployment go to zero replicas during rotation causing application outage.

### References

I can see it is set to ignoring PDBs here:

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/containers/kubernetes_cluster_resource.go#L2454

**Comment by TomBillietKlarrio** [comment]
If you turn on debug logging, you'll see that it indeed ignores the PDB:
```
2024-04-10T16:22:31.863+0200 [DEBUG] provider.terraform-provider-azurerm_v3.95.0_x5: DELETE https://management.azure.com/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ContainerService/managedClusters/xxx/agentPools/tom1c50?api-version=2023-06-02-preview&ignore-pod-disruption-budget=true: timestamp=2024-04-10T16:22:31.863+0200
```
While if you do the same from the Azure UI, it nicely works as expected.
This makes terraform very dangerous to use for an AKS cluster.

**Comment by rgarcia89** [comment]
I ran into this too. We had an outage because of that. It was working fine before. I was very surprised to see all nodes disappear at once even we had PDBs in place.

**Comment by urbantz-technical-support** [comment]
We also faced this issue and also caused minor downtime.

What was the reason behind enabling such a dangerous option like ignoring PDBs. They are meant to protect services in a ever changing environment.

**Comment by rgarcia89** [comment]
@dkirrane this counts for all nodes. Not only temporary once.

**Comment by rgarcia89** [comment]
@stephybun this does not only count for thee default node pool. It should also be respected for other node pools

**Comment by tombuildsstuff** [comment]
@rgarcia89 this issue is specifically requesting this for the Default Node Pool - if you'd like to see this for other node pools then please open a new feature request to track that.

Thanks!
