### ISSUE TITLE
retrieving Container "" (Account "XXXXX" / Resource Group "XXXXXXXX"): containers.Client#GetPropertiesWithLeaseID: Invalid input: `containerName` cannot be an empty string.

### ISSUE THREAD

**Issue by dioni-dev** [hashicorp/terraform-provider-azurerm#25113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.81.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_container

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "web_container" {
  name                  = "$web"
  storage_account_name  = azurerm_storage_account.cdn_storage.name
  container_access_type = "blob"
}
```

### Debug Output/Panic Output

```shell
When i try to import terraform state for the Azure $web container it appears the following error:

╷
│ Error: retrieving Container "" (Account "XXXXXX" / Resource Group "XXXXXXX"): containers.Client#GetPropertiesWithLeaseID: Invalid input: `containerName` cannot be an empty string.
│
│
╵
For the rest of imports everything is working fine, for sure it's something related with the naming ($web).

Could you fix it ?

Kind regards.
```

**Comment by magodo** [comment]
@dioni-dev Probably the `$web` is evaluated by your shell into an empty string as you didn't define the `web`. If you were using bash, you can use single quote to avoid shell evaluation, e.g.

> terraform import azurerm_storage_container.container1 'https://example.blob.core.windows.net/$web'

**Comment by manicminer** [comment]
hi @dioni-dev, thanks for opening this issue.

As @magodo said, this appears to be a syntax issue with your Terraform configuration.

We use GitHub issues for tracking feature requests and bugs in the Azure provider, and to maintain focus on that we instead ask that broader questions are raised using our [Community Resources](https://www.terraform.io/community.html). Accordingly I'm going to close this issue, but I believe you should be able to get an answer on the community discussion portal.
