### ISSUE TITLE
Error creating azurerm_hdinsight_kafka_cluster for HDInsight on Azure with Terraform

### ISSUE THREAD

**Issue by PavelGural** [hashicorp/terraform-provider-azurerm#25125]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.94.0

### Affected Resource(s)/Data Source(s)

azurerm_hdinsight_kafka_cluster

### Terraform Configuration Files

main.tf:
```hcl
resource "azurerm_hdinsight_kafka_cluster" "kafka" {
  ...
  cluster_version = "5.1"
  tier            = "Standard"

  component_version {
    kafka = "3.2"
  }

  storage_account_gen2 {
    storage_resource_id          = var.storage_account_id
    filesystem_id                = var.storage_container_name
    managed_identity_resource_id = var.managed_identity_resource_id
    is_default                   = true
  }
  ...
}
```

variables.tf:
```hcl
variable "storage_container_name" {
  description = "The name of the existing storage container in the Storage Account."
  type        = string
  default     = "<ContainerName>"
}

variable "storage_account_id" {
  description = "The resource ID of the existing Storage Account."
  type        = string
  default     = "/subscriptions/<SubscriptionID>/resourceGroups/<ResourceGroupName>/providers/Microsoft.Storage/storageAccounts/<StorageAccountName>"
}

variable "managed_identity_resource_id" {
  description = "Managed identity resource ID."
  type        = string
  default     = "/subscriptions/<SubscriptionID>/resourceGroups/<ResourceGroupName>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IdentityName>"
}
```

### Debug Output/Panic Output

terraform plan:
``` shell

Terraform will perform the following actions:

  # azurerm_hdinsight_kafka_cluster.kafka will be created
  + resource "azurerm_hdinsight_kafka_cluster" "kafka" {
      + cluster_version           = "5.1"
      ...
      + tier                      = "Standard"

      + component_version {
          + kafka = "3.2"
        }

      + storage_account_gen2 {
          + filesystem_id                = "<ContainerName>"
          + is_default                   = true
          + managed_identity_resource_id = "/subscriptions/<SubscriptionID>/resourceGroups/<ResourceGroupName>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IdentityName>"
          + storage_resource_id          = "/subscriptions/<SubscriptionID>/resourceGroups/<ResourceGroupName>/providers/Microsoft.Storage/storageAccounts/<StorageAccountName>"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

Here is the issue after `terraform apply` command:
```
Error: creating Kafka HDInsight Cluster (Subscription: "<SubscriptionID>"
│ Resource Group Name: "<ResourceGroupName>"
│ Cluster Name: "kafratrntest"): performing Create: unexpected status 400 with response: {"code":"BadRequest","message":"Storage account 'name' in storage profile cannot be null or empty"}
│
│   with azurerm_hdinsight_kafka_cluster.kafka,
│   on main.tf line 60, in resource "azurerm_hdinsight_kafka_cluster" "kafka":
│   60: resource "azurerm_hdinsight_kafka_cluster" "kafka" {
```

Here are additional details:
1. Storage Account and Storage Account Containers for the Kafka HDInsight exist.
2. Storage Account is eligible to have connections from a subnet of HDInsight.
3. ManagedIdentity has the following role assignment `Storage Blob Data Contributor`.

**Comment by ziyeqf** [comment]
Hi @PavelGural , thanks for opening the issue.

Per the [document](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/hdinsight_kafka_cluster.html#filesystem_id), the `filesystem_id` should be the id of `azurerm_storage_data_lake_gen2_filesystem`, using `container` here might not be correct.
A piece of code example is :
```terraform
resource "azurerm_storage_data_lake_gen2_filesystem" "example" {
  name               = "example"
  storage_account_id = azurerm_storage_account.example.id
}

resource "azurerm_hdinsight_kafka_cluster" "example" {
# other properties
 storage_account_gen2 {
    storage_resource_id          = azurerm_storage_account.example.id
    filesystem_id                = azurerm_storage_data_lake_gen2_filesystem.example.id
    managed_identity_resource_id = azurerm_user_assigned_identity.example.id
    is_default                   = true
  }
}
```

Do you mind giving it a try?  For any further questions please leave comments.

Thanks!

**Comment by PavelGural** [comment]
@ziyeqf thank you for your quick response! 

Could you please tell me if it's possible to use such construction to connect to a container somehow (I haven't used `azurerm_storage_data_lake_gen2_filesystem`)?:
```
storage_account_gen2 {
    storage_resource_id          = var.storage_account_id
    filesystem_id                = var.storage_container_name
    managed_identity_resource_id = var.managed_identity_resource_id
    is_default                   = true
  }
  ```
  
Unfortunately, in my case, it's not possible to use the following construction due to the authorization via shared key is denied:
 ```
 storage_account {
    storage_container_id = var.container_id
    storage_account_key  = data.azurerm_storage_account.example.primary_access_key
    is_default           = true
  }
  ```

**Comment by ziyeqf** [comment]
Hi @PavelGural, I don't think it would work, because I assume the value your `storage_container_name` is in different format with `azurerm_storage_data_lake_gen2_filesystem`:`https://account1.dfs.core.windows.net/fileSystem1` https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem#import

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ziyeqf‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
