### ISSUE TITLE
Azure IoT Hub Free sku support

### ISSUE THREAD

**Issue by grecosoft** [hashicorp/terraform-provider-azurerm#25149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The azure IoT Hub documentation states that there can only be one Free IoT Hub per azure subscription.  However, the sku property does not allow setting the value to free.

### New or Affected Resource(s)/Data Source(s)

azurerm_iothub

**Comment by ziyeqf** [comment]
Hi @grecosoft, thanks for opening the issue.
The `F1` sku is on `Free` tier. just opened a PR(#25170) to adding the statement to the document.
Thanks!
