### ISSUE TITLE
Error: retrieving static website properties for Storage Account

### ISSUE THREAD

**Issue by sameergk5** [hashicorp/terraform-provider-azurerm#25146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.9

### AzureRM Provider Version

 3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
we are trying to change backup settings for cosmos DB from periodic to continuous 7 days 
this option is only available in 3.93 and later , but when we execute terrafrom plan it throws below error
```

### Debug Output/Panic Output

```shell
Error: retrieving static website properties for Storage Account (Subscription: "d***********80"
│ Resource Group Name: "************"
│ Storage Account Name: "****************"): accounts.Client#GetServiceProperties: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with module.instaclustrstorageaccount.azurerm_storage_account.storage,
│   on ../../../../modules/azure/azure-storage/main.tf line 1, in resource "azurerm_storage_account" "storage":
│    1: resource "azurerm_storage_account" "storage" {
```

**Comment by magodo** [comment]
@sameergk5 This duplicates to #2977. Please see https://github.com/hashicorp/terraform-provider-azurerm/issues/24982#issuecomment-1972246655 for details.
