### ISSUE TITLE
Azure portal doesn't show the correct .NET version in a windows web app

### ISSUE THREAD

**Issue by wfe8006** [hashicorp/terraform-provider-azurerm#25153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

```
+ resource "azurerm_windows_web_app" "windows_app" {
--- snip snip ---
            + application_stack {
              + current_stack                = "dotnetcore"
              + docker_registry_password     = (sensitive value)
              + docker_registry_url          = (known after apply)
              + docker_registry_username     = (known after apply)
              + dotnet_core_version          = "v4.0"
              + dotnet_version               = (known after apply)
              + java_embedded_server_enabled = (known after apply)
              + php_version                  = (known after apply)
              + python                       = false
              + python_version               = (known after apply)
            }
        
    }
```

### Terraform Version

1.7.4

### AzureRM Provider Version

3.94.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_windows_web_app" "example" {
  name                = "app-service-p-windows-dotnetcore"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  service_plan_id     = azurerm_service_plan.example.id

  site_config {
    application_stack {
      current_stack  = "dotnetcore"
      dotnet_core_version = "v4.0"
    }
  }
}
```
```


### Debug Output/Panic Output

```shell
Terraform v1.7.4
on linux_amd64
Initializing plugins and modules...
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Creating...
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [10s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [20s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [30s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [40s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [50s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [1m0s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Still creating... [1m10s elapsed]
module.app-service-p-windows-dotnetcore.azurerm_windows_web_app.windows_app[0]: Creation complete after 1m12s [id=xxx/providers/Microsoft.Web/sites/app-service-p-windows-dotnetcore]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

### Expected Behaviour

The correct .NET version should be displayed as the default value in the azure portal.

### Actual Behaviour

The .NET version's default/selected value is empty in the azure portal

### Steps to Reproduce

`terraform apply`

**Comment by xiaxyi** [comment]
Thank @wfe8006 for raising this issue, dotnet_core is not supported by Azure portal anymore and you may refer to this article for more information:
https://github.com/Azure/app-service-linux-docs/blob/master/Runtime_Support/dot_net_core.md#end-of-life

The underly CLR of dotnet core is supported by the currently supported dotnet major version, would you mind setting your app to the current versions? Let me know if you have any concerns.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @xiaxyi‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
