### ISSUE TITLE
`azurerm_storage_account` should display correct error message if it creation fails due to different Region of VNET Subnet ID

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#25160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The creation of an Azure Storage Account can fail if it is created with a VNET Link to a resource in a different Azure region.

Example:
Storage Account creation in Germany West Central
VNet Link to resource in West Europe

The provider only prints a very generic:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/46575727/e8c306a6-7660-435c-a971-4c3f38c1bebb)

The Storage Account can then be found in the 'Deleted' section. Especially annoying if you have enabled Purge Protection.

Enabling TF_DEBUG shows the real reason then:

`
"status":"Failed","error":{"code":"NetworkAclsValidationFailure","message":"Validation of network acls failure: ResourceBeingAcledHasWrongLocation:Microsoft.Storage resources in germanywestcentral cannot be ACL-ed to virtual network /subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Network/virtualNetworks/zzz-virtual-network in westeurope. Only resources in westeurope, northeurope can be ACL-ed to virtual networks in westeurope.."}}: timestamp=xxxx
`

The real error message should be displayed by the provider in this case.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Potential Terraform Configuration

```hcl
Important is only to set the following (referencing resource in a different region):


  network_rules {
    ...
    virtual_network_subnet_ids = var.virtual_network_subnet_ids
```
```


### References

_No response_

**Comment by tombuildsstuff** [comment]
This is a limitation of the old base layer and will be fixed once this Resource is [migrated over to using the SDK client from `hashicorp/go-azure-sdk`](https://github.com/hashicorp/terraform-provider-azurerm/blob/ef1b64e15e9d0ae0f68ddc4b29257ffb09872f88/internal/services/storage/client/client.go#L47) rather than [the legacy client from `Azure/azure-sdk-for-go`](https://github.com/hashicorp/terraform-provider-azurerm/blob/ef1b64e15e9d0ae0f68ddc4b29257ffb09872f88/internal/services/storage/client/client.go#L34) - as such I'm going to tag this as `sdk/requires-upgrade` to account for that.
