### ISSUE TITLE
azurerm_virtual_machine_run_command protected_parameter change results in standard parameters being removed from state

### ISSUE THREAD

**Issue by tnavarra** [hashicorp/terraform-provider-azurerm#25177]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.94

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine_run_command

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_run_command" "example" {

  location           = var.location
  name               = "vmrc-example"
  virtual_machine_id = azurerm_windows_virtual_machine.main.id

  source {
    script = file("${path.module}/scripts/Add-ScriptExample.ps1")
  }

  parameter {
    name  = "StandardParamOne"
    value = "SampleOne"
  }

  parameter {
    name  = "StandardParamTwo"
    value = "SampleTwo"
  }

  parameter {
    name  = "StandardParamThree"
    value = "SampleThree"
  }

  protected_parameter {
    name  = "ProtectedParamOne"
    value = "ProtectedOne"
  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

When the value of a protected parameter is changed, an apply should update the protected parameter value and not change the value of the other parameters.

### Actual Behaviour

An apply shows only the protected parameter being changed. However, the other parameters are wiped from state. A subsequent plan shows a change adding the parameters back in.

### Steps to Reproduce

1) Deploy an azurerm_virtual_machine_run_command with protected and unprotected parameters.  
1) Update a protected parameter value and apply the change. 
1) Run a subsequent plan and notice that the unprotected parameters are being added again due to being previously being removed from state following the unrelated protected parameter update.

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25186 created by @teowa for this issue.
