### ISSUE TITLE
Unable to setup `azurerm_lighthouse_definition` with `eligible_authorization`: allowed with api-version greater and equal to '2020-02-01-preview'.

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#25183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.94.0

### Affected Resource(s)/Data Source(s)

azurerm_lighthouse_definition

### Terraform Configuration Files

```hcl
resource "azurerm_lighthouse_definition" "this" {
  name               = "Managed Services"
  description        = "Managed Services"
  managing_tenant_id = "00000000-0000-0000-0000-000000000000"
  scope              = data.azurerm_subscription.current.id

  authorization {
    principal_id           = "93e05589-7fd5-429f-9abf-b5e8c118fdf9"
    role_definition_id     = reverse(split("/", data.azurerm_role_definition.lighthouse["Reader"].role_definition_id))[0]
    principal_display_name = "Subscription_Reader"
  }
  authorization {
    principal_id           = "93e05589-7fd5-429f-9abf-b5e8c118fdf9"
    role_definition_id     = reverse(split("/", data.azurerm_role_definition.lighthouse["Managed Services Registration assignment Delete Role"].role_definition_id))[0]
    principal_display_name = "Lighthouse_Management"
  }
  authorization {
    principal_id           = "93e05589-7fd5-429f-9abf-b5e8c118fdf9"
    role_definition_id     = reverse(split("/", data.azurerm_role_definition.lighthouse["Monitoring Contributor"].role_definition_id))[0]
    principal_display_name = "Monitor_Contributor"
  }
  authorization {
    principal_id           = "93e05589-7fd5-429f-9abf-b5e8c118fdf9"
    role_definition_id     = reverse(split("/", data.azurerm_role_definition.lighthouse["Log Analytics Contributor"].role_definition_id))[0]
    principal_display_name = "LogAnalytics_Contributor"
  }
  authorization {
    principal_id           = "29a3288d-1e9f-4fac-9848-97cff0c0eef5"
    role_definition_id     = reverse(split("/", data.azurerm_role_definition.lighthouse["AcrPull"].role_definition_id))[0]
    principal_display_name = "Lighthouse_MPN_ID"
  }

  eligible_authorization {
    just_in_time_access_policy {
      multi_factor_auth_provider  = "Azure"
      maximum_activation_duration = "PT8H"
    }

    principal_id           = "93e05589-7fd5-429f-9abf-b5e8c118fdf9"
    role_definition_id     = reverse(split("/", data.azurerm_role_definition.lighthouse["Contributor"].role_definition_id))[0]
    principal_display_name = "Subscription_Contributor"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Works as documented

### Actual Behaviour

Registration Assignment: "b7513877-5971-3e8b-f26e-f2fb246dc324"): performing CreateOrUpdate: unexpected status 400 with error: InvalidRegistrationAssignmentCreateRequest: Managed services operations with eligible authorizations only allowed with api-version greater and equal to '2020-02-01-preview'.

### Steps to Reproduce

1. terraform apply

**Comment by ms-zhenhua** [comment]
Hi @jkroepke, thank you for reaching out. 
It seems that the error is caused by the Azure service, not the provider. Could you follow [this doc](https://developer.hashicorp.com/terraform/internals/debugging) to enable Terraform Log and repro this issue? Then you should be able to find the [PUT](https://github.com/Azure/azure-rest-api-specs/blob/41d1c179dc166b7f16b7e40ef4f2a1d9c85b10cc/specification/managedservices/resource-manager/Microsoft.ManagedServices/stable/2022-10-01/managedservices.json#L37) error response in your log. In the log, you should be able to find that the API version is 2022-10-01 which is greater that '2020-02-01-preview'. If so, you may create an API issue in the [swagger repo](https://github.com/Azure/azure-rest-api-specs) or report this issue to Azure support through [Azure Portal](https://portal.azure.com/).

**Comment by jkroepke** [comment]
Hi, thanks for you answer.

with TF_LOG, I was able to identity, that `azurerm_lighthouse_assignment` is the root cause. There are some logs:

```
2024-03-11T07:58:45.405Z [DEBUG] provider.terraform-provider-azurerm_v3.94.0_x5: AzureRM Response for https://management.azure.com/subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.ManagedServices/registrationAssignments/00000000-0000-0000-0000-000000000000?api-version=2019-06-01: 
HTTP/2.0 400 Bad Request
Content-Length: 205
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Mon, 11 Mar 2024 07:58:45 GMT
Expires: -1
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 97830a6f-1a04-3d4b-a43c-af1d88986f1a
X-Ms-Ratelimit-Remaining-Subscription-Writes: 1199
X-Ms-Request-Id: westcentralus:b537176e-67af-4ad1-88bd-74882378bfb5
X-Ms-Routing-Request-Id: WESTEUROPE:20240311T075845Z:9a44990c-80cf-4596-8ef2-0cd5fbb64605

{"error":{"code":"InvalidRegistrationAssignmentCreateRequest","message":"Managed services operations with eligible authorizations only allowed with api-version greater and equal to '2020-02-01-preview'."}}: timestamp=2024-03-11T07:58:45.402Z
```

The logs telling me, that `2019-06-01` is in use.

**Comment by BenHollamby** [comment]
So I've come across this same issue today, and hopefully the below helps someone get unstuck in the interim.

If you comment out the eligible_authorization block, run apply, once finished, uncomment the eligible_authorization block, and run again it works.... Not ideal, but it works.
