### ISSUE TITLE
Default azurerm_public_ip sku to Standard

### ISSUE THREAD

**Issue by nathanweeks** [hashicorp/terraform-provider-azurerm#25195]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_public_ip

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {} 
}

resource "azurerm_resource_group" "myrg" {
  name     = "myrg"
  location = "eastus"
}

resource "azurerm_public_ip" "my_public_ip" {
  name                = "my_public_ip"
  location            = azurerm_resource_group.myrg.location
  resource_group_name = azurerm_resource_group.myrg.name
  allocation_method   = "Dynamic"
}
```

### Debug Output/Panic Output

```shell
# azurerm_public_ip.my_public_ip will be created
  + resource "azurerm_public_ip" "my_public_ip" {
      + allocation_method       = "Dynamic"
      + ddos_protection_mode    = "VirtualNetworkInherited"
      + fqdn                    = (known after apply)
      + id                      = (known after apply)
      + idle_timeout_in_minutes = 4
      + ip_address              = (known after apply)
      + ip_version              = "IPv4"
      + location                = "eastus"
      + name                    = "my_public_ip"
      + resource_group_name     = "myrg"
      + sku                     = "Basic"
      + sku_tier                = "Regional"
    }

  # azurerm_resource_group.myrg will be created
  + resource "azurerm_resource_group" "myrg" {
      + id       = (known after apply)
      + location = "eastus"
      + name     = "myrg"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

### Expected Behaviour

Currently, an `azurerm_public_ip` defaults to `sku = "Basic"`:

https://github.com/hashicorp/terraform-provider-azurerm/blob/ae7b92b9c227e3938248c1edd94f9a28a754825e/website/docs/r/public_ip.html.markdown?plain=1#L79

At some point, the default should change to "Standard", as the "Basic" public sku is deprecated in Azure, cannot be created after 31 March 2025, and will be retired on 30 September 2025:

* https://azure.microsoft.com/en-us/updates/upgrade-to-standard-sku-public-ip-addresses-in-azure-by-30-september-2025-basic-sku-will-be-retired/
* https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25217 created by @wuxu92 for this issue.
