### ISSUE TITLE
azurerm_role_assignment - Error: loading Role Definition List: could not find role

### ISSUE THREAD

**Issue by mayk0gan** [hashicorp/terraform-provider-azurerm#25194]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.71.0

### Affected Resource(s)/Data Source(s)

azurerm_role_definition, azurerm_role_assignment

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "primary" {}

resource "azurerm_role_definition" "read_permissions" {
  description = "Read permissions test"
  name        = "role-name-example-1"
  scope       = data.azurerm_subscription.primary.id

  permissions {
    actions          = [
      "Microsoft.Resources/subscriptions/resourceGroups/read",
    ]
    not_actions      = []
    data_actions     = []
    not_data_actions = []
  }
}

resource "time_sleep" "wait_for_role_definition" {
  depends_on = [
    azurerm_role_definition.read_permissions,
  ]

  create_duration = "60s"
}

resource "azurerm_role_assignment" "role_assignment" {
  scope                = data.azurerm_subscription.primary.id
  principal_id         = local.application_id
  role_definition_name = azurerm_role_definition.read_permissions.name
}
```

### Debug Output/Panic Output

```shell
My module is extensive and contains numerous resources. I'm not convinced that including the entire log here would be beneficial.

However, I do observe the following line in the Terraform log:


{"@level":"error","@message":"vertex \"module.global.azurerm_role_assignment.subscription_read_data\" error: loading Role Definition List: could not find role '<ROLE_NAME>'","@timestamp":"2024-03-09T13:16:12.897462+02:00"}
```

Subsequently, it is printed as:

```
│ Error: loading Role Definition List: could not find role '<ROLE_NAME>'
│
│   with module.function.azurerm_role_assignment.role_name,
│   on modules/function/main.tf line 128, in resource "azurerm_role_assignment" "role_assignment":
│  128: resource "azurerm_role_assignment" "role_assignment" {
│
```
```


### Expected Behaviour

I create a role definition and then use it in a role assignment that I create. I would expect it to find the role definition and create the role assignment properly.

I've also tried adding a delay that depends on the role definition, but that didn't work either.

### Actual Behaviour

When Terraform attempts to create the role assignment, it does not find the role definition.

Instead, I receive the following error:

`Error: loading Role Definition List: could not find role <ROLE_NAME>`

It's important to note that I have multiple role definitions and role assignments. The failure occurs on random role assignments during every first installation and is not necessarily the same one each time.

In addition, I've tried several AzureRM versions + terraform versions, and it happens every time.

### Steps to Reproduce

_No response_

### Important Factoids

_No response_

### References

_No response_

**Comment by jkroepke** [comment]
You have to use this:

```
  role_definition_id = azurerm_role_definition.read_permissions.id
```

role_definition_name works only with bulit-in roles. The limitation is documented.

**Comment by mayk0gan** [comment]
@jkroepke 

> You have to use this:
> 
> ```
>   role_definition_id = azurerm_role_definition.read_permissions.id
> ```
> 
> role_definition_name works only with bulit-in roles. The limitation is documented.

It doesn't work.

```
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRoleDefinitionId" Message="The role definition ID '5ec5908e-7612-a0d9-e89e-43928080c50f|' is not valid."
```

Using `.role_definition_id` didn't work either:

```
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequestFormat" Message="The request was incorrectly formatted."
```

Also, can you share the link to the documentation that you're referring to? I can't find [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment) nor [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_definition)

**Comment by jkroepke** [comment]
> Also, can you share the link to the documentation that you're referring to?

Sure, it documented in the first link you provide by your-self.

> [role_definition_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#role_definition_name) - (Optional) The name of a built-in Role

And the first link, provided by you contains also a functional example.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#example-usage-custom-role--user

>   role_definition_id = azurerm_role_definition.read_permissions.role_definition_resource_id

So, please carefully read the documentation, not just scroll over.

**Comment by mayk0gan** [comment]
> > Also, can you share the link to the documentation that you're referring to?
> 
> Sure, it documented in the first link you provide by your-self: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment
> 
> > [role_definition_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#role_definition_name) - (Optional) The name of a built-in Role
> 
> And the first link again, provided by you contains also a functional example.
> 
> https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#example-usage-custom-role--user
> 
> > role_definition_id = azurerm_role_definition.read_permissions.role_definition_resource_id
> 
> So, please carefully read the documentation, not just scroll over.

I appreciate your comments @jkroepke.

The distinction between these attributes isn't clear, just look at this image: 
<img width="705" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/96263702/81a76e95-fdb9-437b-a331-45e8ce8d821a">

Explaining the difference between these attributes without relying on a single example would have made it much clearer. I firmly believe that effective documentation allows you to find answers to your questions without needing to read every word.

(See your first comment for reference https://github.com/hashicorp/terraform-provider-azurerm/issues/25194#issuecomment-1987157280)

Thanks, it's indeed fix the problem from what I see now.
