### ISSUE TITLE
azurerm_container_app_custom_domain import fails with "Error: retrieving Container App"

### ISSUE THREAD

**Issue by jonathan-vogel-siemens** [hashicorp/terraform-provider-azurerm#25216]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_custom_domain

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.95.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_container_app_custom_domain" "example" {
  container_app_id                         = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.App/containerApps/ca-example"
  name                                     = "somedomain.example.cloud"
  certificate_binding_type                 = "SniEnabled"
  container_app_environment_certificate_id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.App/managedEnvironments/exampleenv/certificates/examplecert"
}

import {  
  to = azurerm_container_app_custom_domain.example
  id = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.App/containerApps/ca-example/customDomainName/somedomain.example.cloud"
}
```

### Debug Output/Panic Output

```shell
azurerm_container_app_custom_domain.example: Preparing import... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.App/containerApps/ca-example/customDomainName/somedomain.example.cloud]
azurerm_container_app_custom_domain.example: Refreshing state... [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-example/providers/Microsoft.App/containerApps/ca-example/customDomainName/somedomain.example.cloud]
╷
│ Error: retrieving Container App (Subscription: ""
│ Resource Group Name: ""
│ Container App Name: "") to read Container App (Subscription: ""
│ Resource Group Name: ""
│ Container App Name: ""
│ Custom Domain Name: "")
│ 
│ retrieving Container App (Subscription: ""
│ Resource Group Name: ""
│ Container App Name: "") to read Container App (Subscription: ""
│ Resource Group Name: ""
│ Container App Name: ""
│ Custom Domain Name: "")
╵
```

### Expected Behaviour

the resource is imported

### Actual Behaviour

the error message is shown, resource is not imported

### Steps to Reproduce

1. `terraform apply`

**Comment by Kralizek** [comment]
I'm having the same error while executing `terraform plan` after the first execution that successfully created the domain.

**Comment by jonathan-vogel-siemens** [comment]
seems to be fixed in https://github.com/hashicorp/terraform-provider-azurerm/pull/25192

**Comment by rcskosir** [comment]
@jonathan-vogel-siemens Thanks for taking the time to open this issue! Since #25192 has been merged, I am going to mark this issue as closed. Once that PR is released, if you're still having this issue, feel free to reach out and we can reopen.

**Comment by Kralizek** [comment]
Is there an ETA for a new release?
