### ISSUE TITLE
Setting shared_access_key_enabled to false on azurerm_storage_account causes azurerm_storage_share to 403 on plan/apply

### ISSUE THREAD

**Issue by AndyLonghurstHESA** [hashicorp/terraform-provider-azurerm#25218]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.1

### AzureRM Provider Version

3.94.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
  storage_use_azuread = true
}

resource "azurerm_storage_account" "account" {
  name                              = lower("${var.project_name}${var.storage_use}${var.environment_name}${random_id.account.hex}")
  resource_group_name               = var.rg
  location                          = var.region
  account_tier                      = var.account_tier
  account_replication_type          = var.replication_type
  account_kind                      = var.account_kind
  public_network_access_enabled     = true
  infrastructure_encryption_enabled = true
  shared_access_key_enabled         = false
  network_rules {
    default_action                  = "Deny"
    virtual_network_subnet_ids      = [var.subnet_id]
    ip_rules                        = ["1.1.1.1"] 
  }

resource "azurerm_storage_share" "share" {
  count                 = length(var.share_names)
  name                  = var.share_names[count.index]
  quota                 = var.share_quota
  storage_account_name  = azurerm_storage_account.account.name
  access_tier           = var.share_access_tier
}
```

### Debug Output/Panic Output

```shell
Error: shares.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="KeyBasedAuthenticationNotPermitted" Message="Key based authentication is not permitted on this storage account.\nRequestId:ad19c854-a01a-0021-6d8a-743eb1000000\nTime:2024-03-12T14:38:19.7013825Z"
```

### Expected Behaviour

Terraform plan should run successfully with no changes to process

### Actual Behaviour

Terraform cannot read the azurerm_storage_share after shared_access_key_enabled is set to false on the azurerm_storage_account

### Steps to Reproduce

This happened after I disabled storage account key. I have set storage_use_azuread = true in my azurerm provider config. 

I am signed into the Az CLI with an account that has owner permission on the Azure subscription I am deployed to

**Comment by magodo** [comment]
@AndyLonghurstHESA Unfortunatly, the `storage_use_azuread` doesn't apply to table and share resources yet. This means you can only use the shared key to access those resources for now.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. We like to try to keep discussions consolidated, so we’re going to close this new issue in favor of #15083. Please subscribe to https://github.com/hashicorp/terraform-provider-azurerm/issues/15083 for further updates, thanks!
