### ISSUE TITLE
azurerm_windows_web_app_slot use_32_bit_worker default value does not match docs or default for azurerm_windows_web_app

### ISSUE THREAD

**Issue by Jolton** [hashicorp/terraform-provider-azurerm#25224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_windows_web_app_slot, azurerm_windows_web_app

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_plan" "example" {
  name                = "example-plan"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  os_type             = "Windows"
  sku_name            = "P1v2"
}

resource "azurerm_windows_web_app" "example" {
  name                = "example-windows-web-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_service_plan.example.location
  service_plan_id     = azurerm_service_plan.example.id

  site_config {}
}

resource "azurerm_windows_web_app_slot" "example" {
  name           = "example-slot"
  app_service_id = azurerm_windows_web_app.example.id

  site_config {}
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

A windows web app and slot are created and the use_32_bit_worker setting is set to true on both. This is what is documented on as the default for both resources, https://registry.terraform.io/providers/hashicorp/azurerm/3.95.0/docs/resources/windows_web_app_slot#use_32_bit_worker & https://registry.terraform.io/providers/hashicorp/azurerm/3.95.0/docs/resources/windows_web_app#use_32_bit_worker### 

### Actual Behaviour

The azurerm_windows_web_app is created correctly with use_32_bit_worker = true but the azurerm_windows_web_app_slot has use_32_bit_worker = false

**Comment by xiaxyi** [comment]
@Jolton Thanks for raising this issue, there isn't a default value defined for the property `use_32_bit_worker ` under `azurerm_windows_web_app_slot`. I modified the doc in the linked PR.

**Comment by Jolton** [comment]
In what way does this "value varies from different service plan"? I don't see anything in the [service-plan](https://registry.terraform.io/providers/hashicorp/azurerm/3.95.0/docs/resources/service_plan) resource related to 32 bit workers. Is it some hidden property on the service-plan sku?

Also is there a reason we can't just set the default to true on the azurerm_windows_web_app_slot resource? As it is right now it's just completely inconstant with the azurerm_windows_web_app resource
