### ISSUE TITLE
azurerm_network_security_rule prepends C:/Program Files/Git to SecurityRule ID. Tested in Git Bash, PowerShell and cmd for Windows

### ISSUE THREAD

**Issue by msharma111** [hashicorp/terraform-provider-azurerm#25237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.2

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_network_security_rule

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_rule" "srHttpAllowPort88" {
  name                        = "Port_88"
  priority                    = 112
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "88"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.rgAxis.name
  network_security_group_name = azurerm_network_security_group.nsgVMSS.name
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/msharma111/4dc0661d67e3cd03f3ae133403171328
```

### Expected Behaviour

/subscriptions/xxxxxxxxxxxxxxxxxxxxxx1/resourceGroups/rg-axis-stg-canadacentral-001/providers/Microsoft.Network/networkSecurityGroups/nsgVMSS-axis-stg-canadacentral-001/securityRules/Port_88

### Actual Behaviour

![Screenshot 2024-03-13 123459](https://github.com/hashicorp/terraform-provider-azurerm/assets/63875951/a6a78db8-1222-4332-acb7-285f9727472d)

### Steps to Reproduce

terraform plan

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seem I can't repro it on my local with below tf config and cmd/bash in Windows. Maybe running "terraform state rm azurerm_network_security_rule.test" to remove it from state first and then running "terraform import azurerm_network_security_rule.test /subscriptions/xx-xx-xx-xx-xx/resourceGroups/acctestRG-nsg-test04/providers/Microsoft.Network/networkSecurityGroups/acceptanceTestSecurityGroup1/securityRules/Port_88" would be helpful.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-nsg-test04"
  location = "WestEurope"
}

resource "azurerm_network_security_group" "test" {
  name                = "acceptanceTestSecurityGroup1"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
}

resource "azurerm_network_security_rule" "test" {
  name                        = "Port_88"
  priority                    = 112
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "88"
  source_address_prefix       = "*"
  destination_address_prefix  = "*"
  resource_group_name         = azurerm_resource_group.test.name
  network_security_group_name = azurerm_network_security_group.test.name
}
```

**Comment by msharma111** [comment]
This is happening with azurerm provider version >2.65. It works fine with previous version.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. @neil-yechenwei was unable to reproduce this behavior. We’re going to close this issue for now, but if you run into this again with the latest Terraform and Provider versions, please share some additional information that can help with reproduction.
