### ISSUE TITLE
Azure Functions Support for Node.js 20

### ISSUE THREAD

**Issue by garysassano** [hashicorp/terraform-provider-azurerm#25236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

When is [this](https://azure.microsoft.com/en-us/updates/generally-available-azure-functions-support-for-nodejs-20/) going to be available in the Azurerm Terraform provider?

### Description

Node.js 20 has been GA for a week, but it's still not present in the latest Azurerm Terraform provider.

### New or Affected Resource(s)/Data Source(s)

azurerm_3.95.0

**Comment by jackofallops** [comment]
Hi @garysassano - This was merged in PR #24073 earlier this week and will ship in the next release.

Thanks!
