### ISSUE TITLE
azurerm_pim_eligible_role_assignment throws an error Plugin did not respond and The terraform-provider-azurerm_v3.95.0_x5 plugin crashed

### ISSUE THREAD

**Issue by slam-wowx** [hashicorp/terraform-provider-azurerm#25241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
resource "time_static" "starttime"{}

resource "azurerm_pim_eligible_role_assignment" "pim_eligible_role_assignment" {
  scope              = "/subscriptions/<subid>/resourceGroups/<rgname>" 
  role_definition_id = "/subscriptions/<subid>/providers/Microsoft.Authorization/roleDefinitions/<roledefid>"
  principal_id       = "<adgroupid>"

  schedule {
    start_date_time = time_static.starttime.rfc3339
    expiration {
      duration_days = 365 # 1 year expiration while waiting for permanent assignment feature available
    }
  }

  justification = "Expiration Duration Set"

  ticket {
    number = "1"
    system = "example ticket system"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Request cancelled
│ 
│   with module.pim_contributor_role.azurerm_pim_eligible_role_assignment.pim_eligible_role_assignment,
│   on ../../../modules/pim_contributor_role/main.tf line 373, in resource "azurerm_pim_eligible_role_assignment" "pim_eligible_role_assignment":
│  373: resource "azurerm_pim_eligible_role_assignment" "pim_eligible_role_assignment" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-azurerm_v3.95.0_x5 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x50 pc=0x109171070]

goroutine 59 [running]:
github.com/hashicorp/terraform-provider-azurerm/internal/services/authorization.createEligibilityRoleAssignment.func1()
        github.com/hashicorp/terraform-provider-azurerm/internal/services/authorization/pim_eligible_role_assignment_resource.go:651 +0x70
github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext.func1()
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:113 +0x144
created by github.com/hashicorp/terraform-plugin-sdk/v2/helper/retry.(*StateChangeConf).WaitForStateContext in goroutine 99
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/retry/state.go:86 +0x1c4

Error: The terraform-provider-azurerm_v3.95.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

An Azure AD PIM eligible role assignment should be created at the resource group level.

### Actual Behaviour

I got the above error 

### Steps to Reproduce

1. Run terraform apply
2. Say yes and let the apply run
3. The error is thrown, all other resources apply successfully

**Comment by xuzhang3** [comment]
Not enough info to reproduce, since this is an `nil` exception and the code not checked that. Add a `nil` check should fix this issue but the error will still exist as the crash occurred during handing the error message returned from the service
