### ISSUE TITLE
Azure maps account resource does not support setting the location.

### ISSUE THREAD

**Issue by ozinus** [hashicorp/terraform-provider-azurerm#25248]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Latest version of this resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maps_account
does not let the user set the location of the resource. As a result it defaults the location to global and which in turn also not let the user set the storage resource or managed identity.   

### Service Used

azurerm_maps_account

### API Versions Used

3.95.0

### Description

Latest version of this resource: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maps_account
does not let the user set the location of the resource. As a result it defaults the location to global and which in turn also not let the user set the storage resource or managed identity.   

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/maps_account

**Comment by tjgitdh** [comment]
Is there an expected timeframe for when this problem will be resolved? The current issue is blocking the use of key features such as managed identity and data source, which in turn negates the benefits of automating Azure Maps using terraform

**Comment by markphillips100** [comment]
The provider will need the properties for Location, Managed Identity and Linked Resources for storage account linking, no later than 16th Sept 2024 as the [data upload api](https://learn.microsoft.com/en-au/rest/api/maps/data/upload?view=rest-maps-2023-06-01&tabs=HTTP) is deprecated and will be turned off on this date.  The expectation is for people to use the newer dataRegistry api and that depends on a mapsaccount resource be setup using the 3 missing properties.
