### ISSUE TITLE
Can't deploy a privatelink service with Terraform

### ISSUE THREAD

**Issue by DeLeneMirouze** [hashicorp/terraform-provider-azurerm#25258]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_private_link_service

### Terraform Configuration Files

```hcl
Hi

I try to deploy a Private Link Service.
I tested the sample provided in the doc:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_link_service

But get an error message.
I don't understand because :

private_endpoint_network_policies_enabled = false

This is asked by the doc:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_link_service
```

### Debug Output/Panic Output

```shell
│ Error: creating Private Link Service: (Name "example-privatelink" / Resource Group "RG6"): network.PrivateLinkServicesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateLinkServiceCannotBeCreatedInSubnetThatHasNetworkPoliciesEnabled" Message="Private link service /subscriptions/XXXXXXX/resourceGroups/RG6/providers/Microsoft.Network/privateLinkServices/example-privatelink cannot be created in a subnet /subscriptions/XXXXXXX/resourceGroups/RG6/providers/Microsoft.Network/virtualNetworks/example-vnet/subnets/example-subnet since it has private link service network policies enabled." Details=[] │ │ with azurerm_private_link_service.example, │ on config.tf line 83, in resource "azurerm_private_link_service" "example": │ 83: resource "azurerm_private_link_service" "example" {
```

### Expected Behaviour

The expected result should be the service is deployed.

### Actual Behaviour

│ Error: creating Private Link Service: (Name "example-privatelink" / Resource Group "RG6"): network.PrivateLinkServicesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateLinkServiceCannotBeCreatedInSubnetThatHasNetworkPoliciesEnabled" Message="Private link service /subscriptions/XXXXXXX/resourceGroups/RG6/providers/Microsoft.Network/privateLinkServices/example-privatelink cannot be created in a subnet /subscriptions/XXXXXXX/resourceGroups/RG6/providers/Microsoft.Network/virtualNetworks/example-vnet/subnets/example-subnet since it has private link service network policies enabled." Details=[] │ │ with azurerm_private_link_service.example, │ on config.tf line 83, in resource "azurerm_private_link_service" "example": │ 83: resource "azurerm_private_link_service" "example" {

### Steps to Reproduce

Run sample in the doc:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_link_service

**Comment by DeLeneMirouze** [comment]
What is lacking in the doc is:

private_link_service_network_policies_enabled = false

**Comment by magodo** [comment]
The `enforce_private_link_service_network_policies` in the document is the similar as `private_link_service_network_policies_enabled`, whilst they have the following differences:

- The former is deprecated and will be removed in the next major version. 
- They have opposite meanings, which means `enforce_private_link_service_network_policies = true` (as set in the example) effectively means `private_link_service_network_policies_enabled = false`.

See: https://github.com/hashicorp/terraform-provider-azurerm/blob/240126386f20c3b5a1713e1eb3a906e15ce8a43c/internal/services/network/subnet_resource.go#L772-L790

Regardlessly, I tried the example locally, which runs just fine:

```shell
azurerm_resource_group.example: Creating...
azurerm_resource_group.example: Creation complete after 6s [id=/subscriptions/0000/resourceGroups/mgd-test-private-link]
azurerm_virtual_network.example: Creating...
azurerm_public_ip.example: Creating...
azurerm_public_ip.example: Creation complete after 7s [id=/subscriptions/0000/resourceGroups/mgd-test-private-link/providers/Microsoft.Network/publicIPAddresses/example-api]
azurerm_lb.example: Creating...
azurerm_virtual_network.example: Still creating... [10s elapsed]
azurerm_virtual_network.example: Creation complete after 11s [id=/subscriptions/0000/resourceGroups/mgd-test-private-link/providers/Microsoft.Network/virtualNetworks/example-network]
azurerm_subnet.example: Creating...
azurerm_lb.example: Still creating... [10s elapsed]
azurerm_subnet.example: Still creating... [10s elapsed]
azurerm_subnet.example: Creation complete after 11s [id=/subscriptions/0000/resourceGroups/mgd-test-private-link/providers/Microsoft.Network/virtualNetworks/example-network/subnets/example-subnet]
azurerm_lb.example: Still creating... [20s elapsed]
azurerm_lb.example: Creation complete after 27s [id=/subscriptions/0000/resourceGroups/mgd-test-private-link/providers/Microsoft.Network/loadBalancers/example-lb]
azurerm_private_link_service.example: Creating...
azurerm_private_link_service.example: Still creating... [10s elapsed]
azurerm_private_link_service.example: Creation complete after 18s [id=/subscriptions/0000/resourceGroups/mgd-test-private-link/providers/Microsoft.Network/privateLinkServices/example-privatelink]
╷
│ Warning: Argument is deprecated
│
│   with azurerm_subnet.example,
│   on main.tf line 22, in resource "azurerm_subnet" "example":
│   22:   enforce_private_link_service_network_policies = true
│
│ `enforce_private_link_service_network_policies` will be removed in favour of the property `private_link_service_network_policies_enabled` in version 4.0 of the AzureRM Provider
╵

Apply complete! Resources: 6 added, 0 changed, 0 destroyed.
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
