### ISSUE TITLE
Unable to use the data source azurerm_storage_table_entity

### ISSUE THREAD

**Issue by NickG158** [hashicorp/terraform-provider-azurerm#25267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_table_entity

### Terraform Configuration Files

```hcl
data "azurerm_storage_table_entity" "example" {
  table_name           = "exampletablename"
  storage_account_name = "examplestorageaccountname"
  partition_key        = "1"
  row_key              = "2"
}
```

### Debug Output/Panic Output

```shell
data.azurerm_storage_table_entity.example: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: parsing Account ID: expected the account "" to use a domain suffix of "core.windows.net"
│
│   with data.azurerm_storage_table_entity.example,
│   on aa.tf line 1, in data "azurerm_storage_table_entity" "example":
│    1: data "azurerm_storage_table_entity" "example" {
│
╵
```

### Expected Behaviour

Return the storage table entity

### Actual Behaviour

Error above returned when using v3.96.0 of the azurerm provider. Working on 3.95.0 and below.

### Steps to Reproduce

terraform init, using the v3.96.0 provider
terraform plan / terraform apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/24798 

https://github.com/hashicorp/terraform-provider-azurerm/blob/ccdb7fa60f70f089514fdeaeb436863394ad9333/internal/services/storage/storage_table_entity_data_source.go#L86

**Comment by manicminer** [comment]
@NickG158 Thanks for reporting this and apologies for this regression. We'll work on a fix as soon as possible.
