### ISSUE TITLE
Version 3.96 azurerm_storage_share_file unexpected Error when checking file share 

### ISSUE THREAD

**Issue by mucke2701** [hashicorp/terraform-provider-azurerm#25269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.96

### Affected Resource(s)/Data Source(s)

azurerm_storage_file_share

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "azureteststorage"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "example" {
  name                 = "sharename"
  storage_account_name = azurerm_storage_account.example.name
  quota                = 50
}

resource "local_file" "test_file" {
  content  = <<EOT
[
  {"id": "1", "name": "test"}
]
EOT
  filename = "test.json"
}

resource "azurerm_storage_share_file" "example" {
  name             = "test1.json"
  storage_share_id = azurerm_storage_share.example.id
  source           = local_file.test_file.filename
}
```

### Debug Output/Panic Output

```shell
Error: checking for existing File "test.json" (Directory Path "" / Share Name "example" / Account "Account \"azureteststorage\" (IsEdgeZone false / ZoneName \"\" / Subdomain Type \"file\" / DomainSuffix \"core.windows.net\")"): executing request: unexpected status 403 received with no body
```

### Expected Behaviour

It should access the file share and fill it with the local file or overwrite if there is a existing file with the name "test.json"

### Actual Behaviour

I'm getting an Error message 403, same code still works in version 3.95 
The code breaks at checking the file share.

**Comment by BroderPeters** [comment]
Having a similar sudden error with this version for `azurerm_storage_blob`
```
Error: parsing [...]: expected the path to contain 2 segments but got 4
```

**Comment by manicminer** [comment]
@BroderPeters I suspect the storage blob error you're seeing is due to #25266

**Comment by manicminer** [comment]
@mucke2701 Thanks for reporting this issue. To help identify the root cause, could you let us know which authentication method you're using for the provider, and whether you have set the provider property `storage_use_azuread = true`?

**Comment by mucke2701** [comment]
yes, set to storage_use_azuread = true
But still not the expected behaviour

**Comment by manicminer** [comment]
@mucke2701 This resource was recently updated to support Azure AD authentication, whereas previously it always authenticated with a storage account key. Are you sure you have assigned an IAM role to your principal that includes the following permission?

```
Microsoft.Storage/storageAccounts/fileServices/fileShares/files/read and Microsoft.Storage/storageAccounts/fileServices/readFileBackupSemantics/action
```

The list of required permissions when using Azure AD authentication with the storage API is documented on [this Microsoft page](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory).

**Comment by ZuitAMB** [comment]
@manicminer Yes, the service principal got Contributor and Owner permissions on the subscription level, so the storage account is inheriting those permissions. Additionally, we assigned the Storage Account Contributor and Storage File Data SMB Share Contributor permissions on the storage account level - which should be sufficient.

**Comment by manicminer** [comment]
@ZuitAMB Unfortunately in that case those are not currently sufficient - you would also need to assign the [Storage File Data Privileged Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles/storage#storage-file-data-privileged-contributor) role, as the roles you have assigned do not include the `Microsoft.Storage/storageAccounts/fileServices/readFileBackupSemantics/action` / `Microsoft.Storage/storageAccounts/fileServices/writeFileBackupSemantics/action` permissions.

**Comment by ZuitAMB** [comment]
@manicminer Thanks a lot! After adding this additional role, the deployment was successful using 3.96.0. It seems like those missing permissions were indeed the root cause!

It seems a bit unexpected though, because our Owner role was granted a `Microsoft.Storage/*` permission at subscription level and the storage account was created by the same service principal.

Adding a note which permissions have to be granted for those resources to work sounds like a great idea. Additionally, wrapping the error message and adding a comment in case such an error occurs would be cool.

**Comment by manicminer** [comment]
No problem, that's also a good call to mention something more descriptive like "access denied" in the case that no contextual error message is provided in the 403 response.
