### ISSUE TITLE
Allow "SHA384" value for "integrity_algorithm" in resource azurerm_vpn_gateway_connection

### ISSUE THREAD

**Issue by tovstcn** [hashicorp/terraform-provider-azurerm#25265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.6.0

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_vpn_gateway_connection

### Terraform Configuration Files

```hcl
resource "azurerm_vpn_gateway_connection" "connection" {

### unrelated code

  vpn_link {
    name                 = "Link"
    egress_nat_rule_ids  = []
    ingress_nat_rule_ids = []
    vpn_site_link_id     = azurerm_vpn_site.site.link[0].id
    shared_key           = data.azurerm_key_vault_secret.presharedkey.value

    ipsec_policy {
      encryption_algorithm     = "AES256"
      integrity_algorithm      = "SHA384"
      dh_group                 = "ECP384"
      ike_encryption_algorithm = "GCMAES256"
      ike_integrity_algorithm  = "GCMAES256"
      pfs_group                = "ECP384"
      sa_data_size_kb          = "0"
      sa_lifetime_sec          = "45000"
    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: expected vpn_link.0.ipsec_policy.0.integrity_algorithm to be one of ["GCMAES192" "GCMAES128" "GCMAES256" "MD5" "SHA1" "SHA256"], got SHA384
```

### Expected Behaviour

succesful plan / apply with integrity_algorithm "SHA384" since Azure allows the value for this argument when configuring it through the portal.

<img width="791" alt="Untitled" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/124163017/88992458-f75a-487b-b8ae-062d0c84a350">

### Actual Behaviour

Failed plan with error: 

`expected vpn_link.0.ipsec_policy.0.integrity_algorithm to be one of ["GCMAES192" "GCMAES128" "GCMAES256" "MD5" "SHA1" "SHA256"], got SHA384`

### Steps to Reproduce

1. terraform apply with code: 

```
    ipsec_policy {
      dh_group                 = "ECP384"
      encryption_algorithm     = "AES256"
      integrity_algorithm      = "SHA384"
      ike_encryption_algorithm = "GCMAES256"
      ike_integrity_algorithm  = "GCMAES256"
      pfs_group                = "ECP384"
      sa_data_size_kb          = "0"
      sa_lifetime_sec          = "45000"
    }
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_gateway_connection

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems this feature has been supported by TF. Please use the property [`ike_integrity_algorithm`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/vpn_gateway_connection#ike_integrity_algorithm). See more details from https://learn.microsoft.com/en-us/azure/vpn-gateway/ipsec-ike-policy-howto#cryptographic-algorithms--key-strengths.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If that is not the case, please provide additional information about the feature request that differentiates it from what @neil-yechenwei shared, thanks!

**Comment by tovstcn** [comment]
Thanks for the replies. @rcskosir `ike_integrity_algorithm ` represents the algorithm in phase 2. What we require is the integrity algorithm for phase 1, which is represented by` integrity_algorithm `We add both phase 2 and phase 1 during the set-up, but for the phase 1 it is not allowed to add SHA384, so we have to override it by going to the portal and change it there.

**Comment by rcskosir** [comment]
@tovstcn for the additional information, I'll go ahead and reopen this feature request.

**Comment by neil-yechenwei** [comment]
integrity_algorithm in TF represents phase 1. See more details from https://github.com/Azure/azure-rest-api-specs/blob/6896b2280a63cb6f581a57964d275d8711852e9d/specification/network/resource-manager/Microsoft.Network/stable/2024-07-01/virtualNetworkGateway.json#L5250. Swagger indicates that it doesn't support SHA384. So it's service API limitation. Once service API supports it, we will take another look. Thanks.

ike_integrity_algorithm in TF represents phase 2. See more details from https://github.com/Azure/azure-rest-api-specs/blob/6896b2280a63cb6f581a57964d275d8711852e9d/specification/network/resource-manager/Microsoft.Network/stable/2024-07-01/virtualNetworkGateway.json#L5215. It supports SHA384 and it has been supported by TF.
