### ISSUE TITLE
Error creating storage blobs with `/` in the name

### ISSUE THREAD

**Issue by matt-funda** [hashicorp/terraform-provider-azurerm#25266]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "rg-storage-blob-bug"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "stfreblobbug"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "example" {
  name                  = "content"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource "azurerm_storage_blob" "example" {
  name                   = "directory/file.txt"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source                 = "file.txt"
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: parsing "https://stfreblobbug.blob.core.windows.net/content/directory/file.txt": expected the path to contain 2 segments but got 3
│
│   with azurerm_storage_blob.example,
│   on main.tf line 20, in resource "azurerm_storage_blob" "example":
│   20: resource "azurerm_storage_blob" "example" {
│
╵
```

### Expected Behaviour

All the resources are created

### Actual Behaviour

The resourcegroup, storage account and storage container are created, but when creating the blob terraform throws an error stating:

```
Error: parsing "https://stfreblobbug.blob.core.windows.net/content/directory/file.txt": expected the path to contain 2 segments but got 3
```

NOTE: It does appear to create the blob because I can see it in the azure portal. But on successive applies the same error appears while refreshing the state.

### Steps to Reproduce

1. `terraform init` and ensure you get 3.96.0
2. `terraform apply`

**Comment by mtrampont** [comment]
Hello,

I suspect this regression is coming from this commit https://github.com/hashicorp/terraform-provider-azurerm/commit/1fb9340b772b96988469a80e4ea71015365dc1c0#diff-04975b792c98f0dcce6c792195a0aef6b0c8d1827184b465900e359705fa3609R24

As I guess this is the line which is raising the error:
https://github.com/tombuildsstuff/giovanni/blob/main/storage/2023-11-03/blob/blobs/resource_id.go#L72

So I guess an issue should also be opened to tombuildsstuff/giovanni.

@manicminer what do you think ?

**Comment by lra** [comment]
Confirmed for us too, issue is not happening with Terraform v1.7.5 and azurerm 3.95.0. I happens with azurerm 3.96.0

**Comment by roycornelissen** [comment]
We see it too, for now we've pinned our `azurerm` provider to `3.95.0`

**Comment by manicminer** [comment]
@matt-funda Thanks for reporting, and thanks @mtrampont and @lra for digging into it. This is a regression due to the SDK migration, apologies for this. I'll issue a fix shortly and this will go out in next week's release. Until then, the best course of action is to pin to the previous version v3.95.0, until v3.97.0 is released.
