### ISSUE TITLE
Inconsistency in creating storage account and creating the subdomain as queue

### ISSUE THREAD

**Issue by raguldevops** [hashicorp/terraform-provider-azurerm#25261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.7.1

### AzureRM Provider Version

v3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_queue

### Terraform Configuration Files

```hcl
resource "azurerm_storage_queue" "storage_queue" {
  name                 = "queue-${var.project}-${var.environment}"
  storage_account_name = azurerm_storage_account.storage_account.name
}
```

### Debug Output/Panic Output

```shell
Error: expected the subdomain type to be "queue" but got "table"
│ 
│   with azurerm_storage_queue.storage_queue,
│   on storage_account.tf line 45, in resource "azurerm_storage_queue" "storage_queue":
│   45: resource "azurerm_storage_queue" "storage_queue" {
```

### Expected Behaviour

azurerm_storage_queue.storage_queue: Creating...
azurerm_storage_queue.storage_queue: Creation complete after 1s [id=https://sttestpocqatest.queue.core.windows.net/testpoc-qatest-queue]

### Actual Behaviour

 Error: expected the subdomain type to be "queue" but got "table"
│ 
│   with azurerm_storage_queue.storage_queue,
│   on storage_account.tf line 45, in resource "azurerm_storage_queue" "storage_queue":
│   45: resource "azurerm_storage_queue" "storage_queue" {

### Steps to Reproduce

use azurerm provider 3.96.0 
try to create a storage account and create a queue

**Comment by tombuildsstuff** [comment]
hey @raguldevops 

Thanks for opening this issue - apologies for this regression.

I've taken a look into this and have opened https://github.com/hashicorp/terraform-provider-azurerm/pull/25262 which fixes this issue, which'll ship as a part of the next release - but in the interim it should be possible to pin to an earlier version of the Provider to workaround this.

Thanks!
