### ISSUE TITLE
Support for endToEndEncryptionEnabled in azurerm_linux_web_app

### ISSUE THREAD

**Issue by davidkarlsen** [hashicorp/terraform-provider-azurerm#25277]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Support https://techcommunity.microsoft.com/t5/apps-on-azure-blog/end-to-end-e2e-tls-encryption-preview-on-linux-multi-tenant-app/ba-p/3976646 in azurerm_linux_web_app

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Potential Terraform Configuration

```hcl
end_to_end_encryption_enabled = true | false
```

**Comment by marcindulak** [comment]
Already requested in https://github.com/hashicorp/terraform-provider-azurerm/issues/25126

**Comment by davidkarlsen** [comment]
closing in favour of #25126
