### ISSUE TITLE
Cannot create a non-partitioned azurerm_servicebus_queue when premium partition  is set to 1

### ISSUE THREAD

**Issue by cloudnes** [hashicorp/terraform-provider-azurerm#25273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

=>3.93

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_queue

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "cc" {
  name     = "servicebus-test-cc"
  location = "canadacentral"
}

resource "azurerm_servicebus_namespace" "primary" {
  name                = "canadasb"
  location            = azurerm_resource_group.cc.location
  resource_group_name = azurerm_resource_group.cc.name
  sku                 = "Premium"
  capacity            = "1"
  premium_messaging_partitions = "1"
  zone_redundant                      = true
}

resource "azurerm_servicebus_queue" "example" {
  name         = "test"
  namespace_id = azurerm_servicebus_namespace.primary.id
  enable_partitioning = false
  enable_express      = false
  max_message_size_in_kilobytes = 1024
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: non-partitioned entities are not allowed in partitioned namespace
│
│   with azurerm_servicebus_queue.example,
│   on main.tf line 16, in resource "azurerm_servicebus_queue" "example":
│   16: resource "azurerm_servicebus_queue" "example" {
│
```

### Expected Behaviour

queue resource gets created.

### Actual Behaviour

queue resource is not created

### Steps to Reproduce

terraform apply

if enable_partitioning is set to true  you can see the queue created in the portal(with the partitioning set to false), however the terraform apply  "never" finalize, waiting for the queue to be "active" and times out after 30min  and does  not add  the resource to the state.

if importing a manually created queue through the azure portal  with the enable_partitioning set to false it does not show any issues with plan/apply

error:
│ Error: waiting for status of Queue (Subscription: "e1ee28e0-f2d1-4137-a99c-5b7cd55ddb78"
│ Resource Group Name: "servicebus-replication-cc"
│ Namespace Name: "servicebus-primary"
│ Queue Name: "tfex_servicebus_queue") to become ready: timeout while waiting for state to become 'Succeeded' (last state: 'Updating', timeout: 29m56.110709s)
│
│   with azurerm_servicebus_queue.example,
│   on main.tf line 15, in resource "azurerm_servicebus_queue" "example":
│   15: resource "azurerm_servicebus_queue" "example" { 

### Important Factoids

tested in eastus and canadacentral regions

**Comment by kerbou** [comment]
I experience the exact same issue, on 3.96.0

**Comment by xiaxyi** [comment]
Thanks @cloudnes for raising this issue, the provider does not regard premium namespace that have `premiumMessagingPartitions` set to `1` as non-partitioned namespace. The fix is included in the PR #25213  which checks the partition status of the parent namespace.

**Comment by ImIOImI** [comment]
This caught me today as well. Combined with the [issue I opened](https://github.com/hashicorp/terraform-provider-azurerm/issues/25007) its making working with premium message busses pretty tough. @xiaxyi do you know when #25213 will be released? I want to figure out if I need to drop back my provider version to `3.92.0` or not.

**Comment by xiaxyi** [comment]
Hi @ImIOImI @cloudnes @kerbou Could you let me know if you are having the expected queue creation now? Let me know if there is any issues. Thanks
