### ISSUE TITLE
Error while parsing account ID for data.azurerm_storage_blob

### ISSUE THREAD

**Issue by james-woodbridge** [hashicorp/terraform-provider-azurerm#25270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

```hcl
terraform {
  required_version = "~> 1.4"

  backend "azurerm" {}

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.0"
    }
    time = {
      source  = "hashicorp/time"
      version = "~> 0.10"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
}

data "azurerm_storage_container" "installer_container" {
  storage_account_name = "<storage-account-name>"
  name                 = "installers"
}

data "azurerm_storage_blob" "install_devops_script" {
  name                   = "<filename>"
  storage_account_name   = data.azurerm_storage_container.installer_container.storage_account_name
  storage_container_name = data.azurerm_storage_container.installer_container.name
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/james-woodbridge/812ea1347246d71082e3a821b3b3e046
```

### Expected Behaviour

Terraform should read the storage blob data source

### Actual Behaviour

terraform plan fails with the error:

```
│ Error: parsing Account ID: expected the account "" to use a domain suffix of "core.windows.net"
│ 
│   with data.azurerm_storage_blob.install_pwsh_script,
│   on data.tf line 28, in data "azurerm_storage_blob" "install_pwsh_script":
│   28: data "azurerm_storage_blob" "install_pwsh_script" {
│ 
```

### Steps to Reproduce

1. Implement a data block for azurem_storage_blob using provider v3.95.0
2. upgrade to 3.96.0
3. run `terraform plan`

**Comment by BHoggs** [comment]
Hi, this bug appears to also exist in the table storage data source, as per #25267 . Possible to fix both in this PR? They look to be related.
