### ISSUE TITLE
Removing azurerm_security_center_storage_defender does not disable Microsoft Defender for Cloud on storage account

### ISSUE THREAD

**Issue by VOVELEE** [hashicorp/terraform-provider-azurerm#25287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.9

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_storage_defender

### Terraform Configuration Files

```hcl
# Enable Defender for Storage
resource "azurerm_security_center_storage_defender" "this" {
  count = var.defender_for_cloud.enabled ? 1 : 0

  storage_account_id                     = azurerm_storage_account.this.id
  override_subscription_settings_enabled = true #Required because not enabled on subscription level

  malware_scanning_on_upload_enabled          = var.defender_for_cloud.malware_scanning_on_upload_enabled
  malware_scanning_on_upload_cap_gb_per_month = var.defender_for_cloud.malware_scanning_on_upload_cap_gb_per_month
  sensitive_data_discovery_enabled            = false
}
```

### Debug Output/Panic Output

```shell
Looks like the provider does not set 'isEnabled' property when deleting the resource.

See the request when you disable Defender for Cloud from the Azure portal

{"properties":{"isEnabled":false,"sensitiveDataDiscovery":{"isEnabled":false},"malwareScanning":{"onUpload":{"isEnabled":false,"capGBPerMonth":-1}},"overrideSubscriptionLevelSettings":false}}
```

### Expected Behaviour

- When resource is removed - the Defender for Cloud for Storage to be disabled

### Actual Behaviour

- When resource is removed - the Defender for Cloud for Storage remains enabled

### References

https://learn.microsoft.com/en-us/azure/templates/microsoft.security/defenderforstoragesettings?pivots=deployment-language-terraform

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I found this resource is disabled after this resource is removed from tf config and Azure Portal also indicates that it is disabled. And isEnabled property is also set to false when destroying this resource. Could you try below tf config with latest azurerm provider to see if the issue still exists? Thanks/

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-staorage-test123"
  location = "westeurope"
}

resource "azurerm_storage_account" "test" {
  name                = "acctestacctest12315"
  resource_group_name = azurerm_resource_group.test.name

  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_security_center_storage_defender" "test" {
  storage_account_id                          = azurerm_storage_account.test.id
  override_subscription_settings_enabled      = false
  malware_scanning_on_upload_enabled          = false
  malware_scanning_on_upload_cap_gb_per_month = 4
  sensitive_data_discovery_enabled            = false
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @neil-yechenwei‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
