### ISSUE TITLE
Not able to execute a Resource Graph Query for Azure Update Manager using "azurerm_monitor_scheduled_query_rules_alert_v2" resource

### ISSUE THREAD

**Issue by altruistcoder** [hashicorp/terraform-provider-azurerm#25311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "patch_assessment_failure" {
  name                 = "Patch-Assessment-Failure"
  description          = "Alert when the patch assessment operation for a specific VM is failed."
  resource_group_name  = "ospm-rg"
  location             = "northeurope"
  evaluation_frequency = "P1D"
  window_duration      = "P1D"
  scopes               = ["/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/ospm-rg/providers/microsoft.operationalinsights/workspaces/ospm-la"]
  severity             = 1

  criteria {
    query = <<-QUERY
      arg('').patchassessmentresources
      | where type in~ ("microsoft.compute/virtualmachines/patchassessmentresults", "microsoft.hybridcompute/machines/patchassessmentresults")
      | where properties.status =~ "Failed"
      | where properties.lastModifiedDateTime > ago(1d)
      | project vmResourceId
    QUERY

    time_aggregation_method = "Count"
    threshold               = 0
    operator                = "GreaterThan"

    dimension {
      name     = "vmResourceId"
      operator = "Include"
      values   = ["*"]
    }

    failing_periods {
      minimum_failing_periods_to_trigger_alert = 1
      number_of_evaluation_periods             = 1
    }
  }

  auto_mitigation_enabled = false
  enabled                 = true
  skip_query_validation   = true

  action {
    action_groups = ["/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/ospm-rg/providers/microsoft.insights/actiongroups/ospm-ag"]
  }
}
```

### Debug Output/Panic Output

```shell
Error: creating Scheduled Query Rule (Subscription: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
│ Resource Group Name: "ospm-rg"
│ Scheduled Query Rule Name: "Assessment-Failure"): unexpected status 400 with error: DraftClientException: The request had some invalid properties Activity ID: 174a8ae7-808c-4ceb-af13-fce8fdef28fe.
```

### Expected Behaviour

The alert rule should be created successfully.

### Actual Behaviour

The resource query block defined above is failing on terraform apply and giving the error specified above.

As per my observation, the resource query block `azurerm_monitor_scheduled_query_rules_alert_v2` is not able to execute the Azure Resource Graph Queries because if I remove the `arg('').` part from the query above, terraform apply works absolutely fine giving no errors but the query in the resulting alert rule becomes invalid because the table I am trying to put a query on is not available in the log analytics workspace directly and is coming up from the Azure Resource Graph.

**So, can you please provide some suggestions on how we can define an Azure Resource Graph query in the `azurerm_monitor_scheduled_query_rules_alert_v2` resource block or if there is some other resource which can be used to achieve this?**

**There is one more issue that I am facing with this resource:**

I need to attach a system-assigned identity to my alert rule and also a few role assignments to that system-assigned identity but it seems that the resource doesn't provide a way (_yet_) to specify a block for defining the identity that's going to be attached to the alert rule.
There's already an issue opened for this here: [github.com/hashicorp/terraform-provider-azurerm/issues/23437](https://github.com/hashicorp/terraform-provider-azurerm/issues/23437)

Any help for resolving the above issues or even a workaround would be highly appreciated.

### Steps to Reproduce

Anyone can reproduce this issue by trying to execute an Azure Resource Graph Query (**having `arg('')` in the query**) using the terraform resource `azurerm_monitor_scheduled_query_rules_alert_v2`

**Comment by teowa** [comment]
Hi @altruistcoder , thanks for submitting this.
Seems we may need to upgrade API version for the SDK to support the `identity` property and then the Resource Graph Query can be used. I will work on this.

**Comment by altruistcoder** [comment]
Hello @teowa, 

I am still facing the same issue using the azurerm provider's `3.97.1` version. The last update on the provider came around 4 days ago as on today and it also seems the documentation is also not updated yet as per what I can see here:

[https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert_v2](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert_v2)

Can you please suggest how can I test the latest changes that have been added by you?

**Comment by altruistcoder** [comment]
Alright! Thanks for the update @teowa . I hope it will fix the support of running Azure Resource Graph queries directly as well.
