### ISSUE TITLE
azurerm_network_manager_deployment only appears to deploy one thing despite TF saying it's done 'n'

### ISSUE THREAD

**Issue by stusklinar** [hashicorp/terraform-provider-azurerm#25334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.93.0

### Affected Resource(s)/Data Source(s)

azurerm_network_manager_deployment

### Terraform Configuration Files

```hcl
data "azurerm_subscription" "current" {

}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "uk south"
}



resource "azurerm_network_manager" "example" {
  name                = "example-network-manager"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  scope {
    subscription_ids = [data.azurerm_subscription.current.id]
  }
  scope_accesses = ["Connectivity"]
  description    = "example network manager"
}

resource "azurerm_network_manager_network_group" "example" {
  name               = "example-group"
  network_manager_id = azurerm_network_manager.example.id
}

resource "azurerm_virtual_network" "example" {
  name                    = "example-net"
  location                = azurerm_resource_group.example.location
  resource_group_name     = azurerm_resource_group.example.name
  address_space           = ["10.0.0.0/16"]
  flow_timeout_in_minutes = 10
}

resource "azurerm_network_manager_connectivity_configuration" "example" {
  count                 = 3
  name                  = "example-connectivity-conf-${count.index}"
  network_manager_id    = azurerm_network_manager.example.id
  connectivity_topology = "HubAndSpoke"
  applies_to_group {
    group_connectivity = "None"
    network_group_id   = azurerm_network_manager_network_group.example.id
  }
  hub {
    resource_id   = azurerm_virtual_network.example.id
    resource_type = "Microsoft.Network/virtualNetworks"
  }
}

resource "azurerm_network_manager_deployment" "example" {
  count = 3

  network_manager_id = azurerm_network_manager.example.id
  location           = "uksouth"
  scope_access       = "Connectivity"
  configuration_ids  = [azurerm_network_manager_connectivity_configuration.example[count.index].id]
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/stusklinar/bbbcaaae0da2b979e55eb99e46c0fa90

--

Running it again after a manual run, detects the deployments in Azure and removes the extra deployments.

Terraform says that its created 3 deployments - only 1 shows in portal.
You can deploy them all, and you get 1 `update`, 2 `adds` , and it runs as expected.
then if you rerun terraform, it detects they exist, and tries to remove them, as if they're not in state.


# azurerm_network_manager_deployment.example[1] will be updated in-place
  ~ resource "azurerm_network_manager_deployment" "example" {
      ~ configuration_ids  = [
            "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/connectivityConfigurations/example-connectivity-conf-1",
          - "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/connectivityConfigurations/example-connectivity-conf-0",
          - "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/connectivityConfigurations/example-connectivity-conf-2",
        ]
        id                 = "/subscriptions/000000-0000-0000-0000-0000000/resourceGroups/example-resources/providers/Microsoft.Network/networkManagers/example-network-manager/commit|uksouth|Connectivity"
        # (3 unchanged attributes hidden)
    }
```

### Expected Behaviour

Expected 3 deployments to have run, as the output says 3 have run/been deployed

### Actual Behaviour

Only one single deployment run
<img width="925" alt="Screenshot 2024-03-20 at 15 10 09" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1263488/6b5c3305-c1df-40af-b693-bedea9e8ab38">

Go into deployments and manually run - it runs the other 2 that never ran.
<img width="666" alt="Screenshot 2024-03-20 at 15 10 30" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1263488/80ad0045-ce05-47be-ac5f-978202287471">

<img width="1096" alt="Screenshot 2024-03-20 at 15 11 06" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/1263488/d977dacb-5065-4296-b6e1-26cf495c1bd3">

### Steps to Reproduce

terraform apply

**Comment by stusklinar** [comment]
Update:

I've found a workaround to this, which I'll do for the short term

```
resource "azurerm_network_manager_deployment" "deployment" {
  network_manager_id = module.azure_network_manager.network_manager_id
  location           = module.resource_group.resource_group_location
  scope_access       = "Connectivity"
  configuration_ids  = [for c in azurerm_network_manager_connectivity_configuration.config : c.id]
}
```

**Comment by teowa** [comment]
Hi @stusklinar , thanks for submitting this issue.
In azurerm implementation, we model Network Manager Deployment ID in the format `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourceGroup1/providers/Microsoft.Network/networkManagers/networkManager1/commit|eastus|Connectivity`, the location(`eastus`) and type(`Connectivity`) are added into ID, and each ID is supposed to be unique, that's because we actually don't allow for multiple deployments resource with same region and type. 

When `count = 3` is used, there are three deployment resources with same ID created in parallel, only one of them will be successfully created. This is unexpected and I will add a parallel lock to fire error earlier for the first method. The provided workaround is the right method if want to reference a list of configuration. 

Thanks.
