### ISSUE TITLE
azurerm_private_endpoint private_ip_address keeps changing after terraform apply

### ISSUE THREAD

**Issue by mgismaco** [hashicorp/terraform-provider-azurerm#25348]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.81

### Affected Resource(s)/Data Source(s)

azurerm_private_endpoint 

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "example" {
  name                = "${module.azurerm_naming.private_endpoint.name}-https-001"
  location            = data.azurerm_application_gateway.example.location
  resource_group_name = data.azurerm_application_gateway.example.resource_group_name
  subnet_id           = data.azurerm_subnet.example.id

  private_service_connection {
    name                           = "pep-connection-https"
    private_connection_resource_id = azurerm_private_link_service.example.id
    is_manual_connection           = false
  }

  tags = var.tags
}

resource "azurerm_private_dns_a_record" "example" {
  name                = "example"
  zone_name           = data.azurerm_private_dns_zone.example.name
  resource_group_name = data.azurerm_private_dns_zone.example.resource_group_name
  ttl                 = 300
  records             = [azurerm_private_endpoint.example.private_service_connection[0].private_ip_address]
}
```

### Debug Output/Panic Output

```shell
~ resource "azurerm_private_dns_a_record" "example" {
        id                  = "/subscriptions/xxx/resourceGroups/example/providers/Micros
oft.Network/privateDnsZones/example/A/example"
        name                = "example"
      ~ records             = [
          - "x.x.x.x",
          + "x.x.x.xx",
        ]
        tags                = {}
        # (4 unchanged attributes hidden)
    }
```

### Expected Behaviour

Terraform apply should set the A record correctly and not want to change it to the wrong IP on the next terraform apply.

### Actual Behaviour

First terraform apply sets the A record as the private link service private endpoint IP address, the following apply then it changes it to be the IP address of a virtual machine that is the backend of the private link service load balancer.

### Steps to Reproduce

terraform apply
terraform plan (shows IP change)

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems I can't repro this issue with latest azurerm provider and below tf config that is similar with yours. Could you try below tf config and latest azurerm provider to see if the issue still exists? Thanks.

tf config:
```
provider "azurerm" {
  features {}
}

data "azurerm_subscription" "current" {}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-test01"
  location = "westeurope"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvnet-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  address_space       = ["10.5.0.0/16"]
}

resource "azurerm_subnet" "service" {
  name                 = "acctestsnetservice-test01"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.5.1.0/24"]

  enforce_private_link_service_network_policies = true
}

resource "azurerm_subnet" "endpoint" {
  name                 = "acctestsnetendpoint-test01"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.5.2.0/24"]

  enforce_private_link_endpoint_network_policies = true
}

resource "azurerm_public_ip" "test" {
  name                = "acctestpip-test01"
  sku                 = "Standard"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Static"
}

resource "azurerm_lb" "test" {
  name                = "acctestlb-test01"
  sku                 = "Standard"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  frontend_ip_configuration {
    name                 = azurerm_public_ip.test.name
    public_ip_address_id = azurerm_public_ip.test.id
  }
}

resource "azurerm_private_link_service" "test" {
  name                           = "acctestPLS-test01"
  location                       = azurerm_resource_group.test.location
  resource_group_name            = azurerm_resource_group.test.name
  auto_approval_subscription_ids = [data.azurerm_subscription.current.subscription_id]
  visibility_subscription_ids    = [data.azurerm_subscription.current.subscription_id]

  nat_ip_configuration {
    name      = "primaryIpConfiguration-test01"
    primary   = true
    subnet_id = azurerm_subnet.service.id
  }

  load_balancer_frontend_ip_configuration_ids = [
    azurerm_lb.test.frontend_ip_configuration.0.id
  ]
}

resource "azurerm_private_endpoint" "test" {
  name                = "acctest-privatelink-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  subnet_id           = azurerm_subnet.endpoint.id

  private_service_connection {
    name                           = azurerm_private_link_service.test.name
    is_manual_connection           = false
    private_connection_resource_id = azurerm_private_link_service.test.id
  }
}

resource "azurerm_private_dns_zone" "test" {
  name                = "acctestzonetest01.com"
  resource_group_name = azurerm_resource_group.test.name

  depends_on = [azurerm_private_endpoint.test]
}

resource "azurerm_private_dns_a_record" "test" {
  name                = "myarecordtest01"
  resource_group_name = azurerm_resource_group.test.name
  zone_name           = azurerm_private_dns_zone.test.name
  ttl                 = 300
  records             = [azurerm_private_endpoint.test.private_service_connection[0].private_ip_address]
}
```

**Comment by mgismaco** [comment]
@neil-yechenwei still happening on the latest provider. Can you add a VM as the backend on the LB?

`
resource "azurerm_lb_backend_address_pool" "example" {
  loadbalancer_id = azurerm_lb.example.id
  name            = "https-vm"
}

resource "azurerm_network_interface_backend_address_pool_association" "example" {
  network_interface_id    = module.example_vm.network_interface_id
  ip_configuration_name   = module.example_vm.network_interface_ip_configuration_name
  backend_address_pool_id = azurerm_lb_backend_address_pool.example.id
}

resource "azurerm_lb_probe" "example" {
  loadbalancer_id = azurerm_lb.example.id
  name            = "443"
  port            = 443
}

resource "azurerm_lb_rule" "example" {
  loadbalancer_id                = azurerm_lb.example.id
  name                           = "443"
  protocol                       = "Tcp"
  frontend_port                  = 443
  backend_port                   = 443
  frontend_ip_configuration_name = azurerm_lb.example.frontend_ip_configuration[0].name
  backend_address_pool_ids       = [azurerm_lb_backend_address_pool.example.id]
  probe_id                       = azurerm_lb_probe.example.id
}
`

**Comment by mgismaco** [comment]
@neil-yechenwei was a problem in my code, apologies. I had another A record setting the same name to a different IP.
