### ISSUE TITLE
Support for versioning_enabled retention policy in azurerm_storage_account

### ISSUE THREAD

**Issue by anwarnk** [hashicorp/terraform-provider-azurerm#25349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Can't find an option for retention period for versioning when enabled.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/105373983/7bad1132-92da-4a72-8e5e-13f8ca7a8c99)

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Potential Terraform Configuration

```hcl
##redacted

  blob_properties {
    }
    versioning_enabled            = "true"
    versioning_delete_retention_policy {
      days = "xx"
    }
  }
```

**Comment by magodo** [comment]
@anwarnk This has already been supported by [azurerm_storage_management_policy](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_management_policy), namely the `rule.x.actions.0.version.delete_after_days_since_creation`.
