### ISSUE TITLE
azurerm_container_registry public_network_access_enabled does not fully allow public access

### ISSUE THREAD

**Issue by Vermyndax** [hashicorp/terraform-provider-azurerm#25359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "cr" {
  name                          = "xxx-${var.environment}"
  location                      = azurerm_resource_group.network_base.location
  resource_group_name           = azurerm_resource_group.network_base.name
  sku                           = "Premium"
  admin_enabled                 = false
  public_network_access_enabled = true
  anonymous_pull_enabled        = false
}
```

### Debug Output/Panic Output

```shell
Plan/apply succeeds, and Azure portal shows public access enabled, but not for all networks. Public access is enabled for "specific networks" only. Manual action must be taken in the portal to enable it for all networks.
```

### Expected Behaviour

The resource should provide a way to set public access for all. In our case, we're trying to use Github Actions to build/tag containers and save them into this repo.

### Actual Behaviour

Public access is enabled on the repo, but GitHub Actions is denied access to the repo unless we go to the portal and manually select "allow access for all networks."

### Steps to Reproduce

terraform apply

**Comment by magodo** [comment]
@Vermyndax I've tried your above config and created the ACR, whose portal shows the network setting as exepcted:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7970698/c3eea8b1-729e-4160-ad1e-493f3cc03b0e)

Could you elaborate more about:

> go to the portal and manually select "allow access for all networks."
