### ISSUE TITLE
Since: v3.96: azurerm_storage_share_file - status 400 received with no body

### ISSUE THREAD

**Issue by JasBonker** [hashicorp/terraform-provider-azurerm#25353]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.7.5

### AzureRM Provider Version

v3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share_file

### Terraform Configuration Files

```hcl
# --------------------------
# File share storage
# --------------------------
resource "azurerm_storage_share" "xxxxxxxxxxxx" {
  name                 = "xxxxxxxxxxxx"
  storage_account_name = data.terraform_remote_state.foundation.outputs.xxxxxxxxxxxx.name
  quota                = 50
}

resource "azurerm_backup_protected_file_share" "xxxxxxxxxxxx" {
  resource_group_name       = data.terraform_remote_state.foundation.outputs.azurerm_resource_group_backup.name
  source_storage_account_id = data.terraform_remote_state.backup.outputs.azurerm_backup_container_storage_account.storage_account_id
  recovery_vault_name       = data.terraform_remote_state.backup.outputs.azurerm_recovery_services_vault.name
  backup_policy_id          = data.terraform_remote_state.backup.outputs.azurerm_backup_policy_file_share.id
  source_file_share_name    = azurerm_storage_share.xxxxxxxxxxxxv.name
}

resource "local_file" "xxxxxxxxxxxx" {
  content = templatefile("${path.module}/../../../templates/xxxxxxxxxxxxxxxx.xml",
    {
      xxxxxx = var.xxxxxx
  })
  filename = "xxxxx.xml"
}

resource "azurerm_storage_share_directory" "xxxxxxxxxxxx" {
  name                 = "data"
  share_name           = azurerm_storage_share.xxxxxxxxxxxx.name
  storage_account_name = data.terraform_remote_state.foundation.outputs.azurerm_storage_account_mmc.name

}

resource "azurerm_storage_share_directory" "xxxxxxxxxxxx" {
  name                 = "data/xxxxxxxxxxxx"
  share_name           = azurerm_storage_share.xxxxxxxxxxxx.name
  storage_account_name = data.terraform_remote_state.foundation.outputs.azurerm_storage_account_mmc.name

  depends_on = [
    azurerm_storage_share_directory.data
  ]
}

resource "azurerm_storage_share_directory" "xxxxxxxxxxxx" {
  name                 = "data/xxxxxxxxxxxx/xxxxxxxxxxxx"
  share_name           = azurerm_storage_share.xxxxxxxxxxxx.name
  storage_account_name = data.terraform_remote_state.foundation.outputs.azurerm_storage_account_mmc.name

  depends_on = [
    azurerm_storage_share_directory.xxxxxxxxxxxx
  ]
}

resource "azurerm_storage_share_directory" "install" {
  name                 = "data/xxxxxxxxxxxx/xxxxxxxxxxxx/install"
  share_name           = azurerm_storage_share.xxxxxxxxxxxx.name
  storage_account_name = data.terraform_remote_state.foundation.outputs.azurerm_storage_account_mmc.name

  depends_on = [
    azurerm_storage_share_directory.mmc
  ]
}

resource "azurerm_storage_share_directory" "resources" {
  name                 = "data/xxxxxxxxxxxx/xxxxxxxxxxxx/install/resources"
  share_name           = azurerm_storage_share.xxxxxxxxxxxx.name
  storage_account_name = data.terraform_remote_state.foundation.outputs.azurerm_storage_account_mmc.name

  depends_on = [
    azurerm_storage_share_directory.install
  ]
}

resource "azurerm_storage_share_file" "xxxxxxxxxxxx" {
  name             = "xxxxxxxxxxxxs.xml"
  storage_share_id = azurerm_storage_share.xxxxxxxxxxxx.id
  path             = "data\\xxxxxxxxxxxx\\xxxxxxxxxxxx\\install\\resources"
  source           = "xxxxxxxxxxxx.xml"

  depends_on = [
    azurerm_storage_share_directory.resources
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: checking for existing File "xxxxxxxxxxxx.xml" (Directory Path "data\\xxxxxxxxxxxx\\xxxxxxxxxxxx\\install\\resources" / Share Name "xxxxxxxxxxxx" / Account "Account \"xxxxxxxxxxxx\" (IsEdgeZone false / ZoneName \"\" / Subdomain Type \"file\" / DomainSuffix \"core.windows.net\")"): executing request: unexpected status 400 received with no body
│
│   with azurerm_storage_share_file.xxxxxxxxxxxx,
│   on main.tf line 131, in resource "azurerm_storage_share_file" "xxxxxxxxxxxx":
│  131: resource "azurerm_storage_share_file" "xxxxxxxxxxxxv" {
```

### Expected Behaviour

Ideally:
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Or otherwise:
│ Error: A resource with the ID "https://xxxxxxxxxxxx.file.core.windows.net/xxxxxxxxxxxx/data\\xxxxxxxxxxxx\\xxxxxxxxxxxx\\install\\resources/xxxxxxxxxxxx.xml" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_storage_share_file" for more information.
│
│   with azurerm_storage_share_file.xxxxxxxxxxxx,
│   on main.tf line 131, in resource "azurerm_storage_share_file" "xxxxxxxxxxxx":
│  131: resource "azurerm_storage_share_file" "xxxxxxxxxxxx" {

### Actual Behaviour

│ Error: checking for existing File "xxxxxxxxxxxx.xml" (Directory Path "data\\xxxxxxxxxxxx\\xxxxxxxxxxxx\\install\\resources" / Share Name "xxxxxxxxxxxx" / Account "Account \"xxxxxxxxxxxx\" (IsEdgeZone false / ZoneName \"\" / Subdomain Type \"file\" / DomainSuffix \"core.windows.net\")"): executing request: unexpected status 400 received with no body
│
│   with azurerm_storage_share_file.xxxxxxxxxxxx,
│   on main.tf line 131, in resource "azurerm_storage_share_file" "xxxxxxxxxxxx":
│  131: resource "azurerm_storage_share_file" "xxxxxxxxxxxxv" {

### Steps to Reproduce

terraform apply

**Comment by JasBonker** [comment]
Additional info, I tested with v3.95 and TF 1.6.x and with TF 1.7.x and both works fine.
Once the Azure RM provider is set to v3.96 (and either TF 1.6.x or with TF 1.7.x) it breaks.

**Comment by manicminer** [comment]
@JasBonker Thanks for reporting this bug. I suspected a possible issue with handling backslash-delimited paths in the name, but in testing I was unable to reproduce this.

Would you be able to provide a debug log (i.e. by setting the `TF_LOG=DEBUG` environment variable) to assist with tracking down the issue? Thanks!

**Comment by tombuildsstuff** [comment]
@JasBonker would you be able to upgrade to `v3.97.1` and confirm if this is still happening for you?

**Comment by JasBonker** [comment]
Hi @tombuildsstuff and @manicminer,
Thanks for the quick replies! 
With 3.97.1 the issue sadly still persists. Here is the log file:
[issue25353.log](https://github.com/hashicorp/terraform-provider-azurerm/files/14722938/issue25353.log)

**Comment by manicminer** [comment]
Thanks for the additional info @JasBonker! I've identified some bugs in path handling, along with some gaps in our test coverage that allowed this to slip by unnoticed. I've opened https://github.com/tombuildsstuff/giovanni/pull/113 to address these bugs, and https://github.com/hashicorp/terraform-provider-azurerm/pull/25404 for the test coverage.
