### ISSUE TITLE
Role assignments can be created on Azure subscription aliases, but cannot imported to Terraform state

### ISSUE THREAD

**Issue by eehret** [hashicorp/terraform-provider-azurerm#25352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

Partial snippet illustrating what the corresponding Terraform looks like.  We have confirmed that this does work for creation when the role assignment does not already exist:

```hcl
resource "azurerm_role_assignment" "subscription-alias-owner-azops" {
  scope                = "/providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt"
  role_definition_name = "Owner"
  principal_id         = data.azuread_group.group_azops_team.id
}
```

### Debug Output/Panic Output

```shell
#The command being issued:
terraform import azurerm_role_assignment.subscription-alias-owner-azops "/providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt/providers/Microsoft.Authorization/roleAssignments/<redacted guid>"

#The result:

│ Error: could not parse Role Assignment ID "C:/Program Files/Git/providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt/providers/Microsoft.Authorization/roleAssignments/<redacted guid>"
```

It looks like something is going very wrong during parsing of the ID, as I'm not sure how the local file path is ending up in there.

### Expected Behaviour

Import the existing role assignment into Terraform state to the specified resource name.

Just to reiterate, this role assignment CAN be created using Terraform with config similar to what is shown above.
And when interrogating the role assignments using Azure PowerShell , we see that the ID we are trying to use for importing is in fact correct.  It also matches the format of the ID that we see in the Terraform state after we successfully create one of these using Terraform.

```
RoleAssignmentName : <redacted guid>
RoleAssignmentId   : /providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt/providers/Microsoft.Authorization/roleAssignments/<redacted guid>
Scope              : /providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt
DisplayName        : Azure - Cloud Admins
SignInName         : 
RoleDefinitionName : Owner
RoleDefinitionId   : 8e3af657-a8ff-443c-a75c-2fe8c4bcb635
ObjectId           : <redacted guid>
ObjectType         : Group
CanDelegate        : False
Description        : 
ConditionVersion   : 
Condition          : 
```

I would also like to request that, once importing this type of role assignment becomes possible, the page for `azurerm_role_assignment` be updated to show an example.  The current examples don't show importing a role assignment on a subscription alias.

### Actual Behaviour

The error above was returned and the state was not imported.

### Steps to Reproduce

`terraform import azurerm_role_assignment.subscription-alias-owner-azops "/providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt/providers/Microsoft.Authorization/roleAssignments/<redacted guid>"`

**Comment by magodo** [comment]
@eehret I've tried to import a role assignment that is scoped for a subscription alias (created also via terraform), which succeeds:

```shell
≡ƒÆñ  tf import azurerm_role_assignment.test /providers/Microsoft.Subscription/aliases/test/providers/Microsoft.Authorization/roleAssignments/cccc1aa1-99fd-5645-569c-d9c0b05ae655
data.azurerm_role_definition.test: Reading...
data.azurerm_client_config.test: Reading...
data.azurerm_client_config.test: Read complete after 0s [id=Y2xpZW50Q29uZmlncy9jbGllbnRJZD0wNGIwNzc5NS04ZGRiLTQ2MWEtYmJlZS0wMmY5ZTFiZjdiNDY7b2JqZWN0SWQ9Nzk0ZjhkNDUtNmViMy00ZTFlLWJjNjItYzAxMzE3ZWFlYWMxO3N1YnNjcmlwdGlvbklkPTBiMWY2NDcxLTFiZjAtNGRkYS1hZWMzLWNiOTI3MmYwOTU5MDt0ZW5hbnRJZD01NDgyNmIyMi0zOGQ2LTRmYjItYmFkOS1iN2I5M2EzZTljNWE=]
data.azurerm_role_definition.test: Read complete after 1s [id=/providers/Microsoft.Authorization/roleDefinitions/43d0d8ad-25c7-4714-9337-8ba259a9fe05]
azurerm_role_assignment.test: Importing from ID "/providers/Microsoft.Subscription/aliases/test/providers/Microsoft.Authorization/roleAssignments/cccc1aa1-99fd-5645-569c-d9c0b05ae655"...
azurerm_role_assignment.test: Import prepared!
  Prepared azurerm_role_assignment for import
azurerm_role_assignment.test: Refreshing state... [id=/providers/Microsoft.Subscription/aliases/test/providers/Microsoft.Authorization/roleAssignments/cccc1aa1-99fd-5645-569c-d9c0b05ae655]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

I'm on provider commit: 91352c2a9362d040f5153b42a790f5f3f853bd0e.

From your description above, looks like there is something wrong with the shell that inaccidently convert the last segment in `terraform import` from `"/providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt/providers/Microsoft.Authorization/roleAssignments/<redacted guid>"` to `"C:/Program Files/Git/providers/Microsoft.Subscription/aliases/dtb-adacs-dataanalytics-dt/providers/Microsoft.Authorization/roleAssignments/<redacted guid>"`. I'm not a powershell user, could you try the same thing via other shells like bash?

**Comment by eehret** [comment]
@rcskosir My attempt actually was made from Git bash (on Windows)

I can try again....

**Comment by eehret** [comment]
Ok, interesting ...

The exact same command actually worked from a regular PowerShell prompt but not from Git Bash

In both cases the command was executed on a Windows Server 2019 VM.  Nothing was different between attempts, no reboots or other manipulation of the environment was done.

**Comment by eehret** [comment]
Might be related to one of the known issues mentioned here related to "POSIX-to-Windows path conversion" mentioned here (https://github.com/git-for-windows/build-extra/blob/main/ReleaseNotes.md#known-issues ) and here (https://github.com/moby/moby/issues/24029#issuecomment-250412919)

So, not a Terraform bug I suppose.    Closing with a note to self to remember to prepend an extra / in front of the resource ID next time :)

**Comment by eehret** [comment]
Update for anyone who stumbles across my last comment above....  prepending with "//" does not work.  But fortunately the other workaround mentioned in the second link *does* work , i.e. setting MSYS_NO_PATHCONV=1 in Git Bash
