### ISSUE TITLE
`azurerm_graph_services_account` falsly marked as deprecated

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-azurerm#25387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_graph_services_account

### Terraform Configuration Files

```hcl
resource "azurerm_graph_services_account" "teams-meeting" {
  name                = "${var.environment}-teams-meeting"
  resource_group_name = azurerm_resource_group.this.name
  application_id      = module.app_teams_meeting.app_client_id
}
```

### Debug Output/Panic Output

```shell
│ Warning: Deprecated Resource
│ 
│   with module.seismic.azurerm_graph_services_account.teams-meeting,
│   on ../../modules/seismic-global-service/graph-services-account.tf line 4, in resource "azurerm_graph_services_account" "teams-meeting":
│    4: resource "azurerm_graph_services_account" "teams-meeting" {
│ 
│ The "azurerm_graph_services_account" resource has been deprecated and replaced by the "azurerm_graph_services_account" resource.
│ 
│ The existing "azurerm_graph_services_account" resource will remain available until the next
│ major version of the Azure Provider however the existing resource is feature-frozen
│ and we recommend using the "azurerm_graph_services_account" resource instead.
│ 
```

### Expected Behaviour

No warning

### Actual Behaviour

Showing a warning about `azurerm_graph_services_account` being deprecated and replaced by `azurerm_graph_services_account` (same resource).

### Steps to Reproduce

terraform plan

**Comment by teowa** [comment]
Hi @lra , thanks for reporting this bug. I have submit #25391 to remove the deprecation message.
