### ISSUE TITLE
Error: retrieving ACL's "WADMetricsPT1HP1xxxxxxx" in Storage Account "nxxcorpprodplanrgdiag": tables.Client#GetACL: Failure responding to request: StatusCode=200 -- Original Error: Error occurred reading http.Response#Body - Error = 'read tcp 10.132.12.5:56552->20.60.166.xxx:443: read: connection reset by peer'

### ISSUE THREAD

**Issue by lex885uk** [hashicorp/terraform-provider-azurerm#25382]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.6

### AzureRM Provider Version

3.76.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_table

### Terraform Configuration Files

```hcl
This is not caused by any configuration file issue. It just started to happen yesterday. We have our Terraform agent in a container instance in Azure and we use Terraform Cloud to run the pipelines with workspaces. The terraform agent has Contributor role on the subscription and so far it had no issues with reading the storage accounts and tables.

Anyone knows maybe if newer version of Terraform or Azurerm resolves this issue?
```

### Debug Output/Panic Output

```shell
Error: retrieving ACL's "WADMetricsPTxxxxxxxx" in Storage Account "nxxxcorpprodplanrgdiag": tables.Client#GetACL: Failure responding to request: StatusCode=200 -- Original Error: Error occurred reading http.Response#Body - Error = 'read tcp 10.132.12.5:54576->20.60.166.xxx:443: read: connection reset by peer'
```

### Expected Behaviour

This storage account belongs to a VM and it stores the azure vm diagnostics in tables. The terraform agent 10.132.12.5:54576 cannot read out the ACL list from the tables. All tables errors with this. But before yesterday the terraform agent had all the rights and everything to get these. We did not change anything on the storage account or on the access of the terraform agent. 

### Actual Behaviour

The terraform plan and apply both errors out with the above error, it cannot retrieve the ACL from the tables.

### Steps to Reproduce

terraform plan (intermittent)
terraform apply always - rerunning the pipeline not solving the issue

**Comment by manicminer** [comment]
Hi @lex885uk, thanks for reporting this issue. Are you experiencing this error consistently over time? I don't believe this is a permissions issue, as in v3.76.0 the storage account key is used to authenticate when retrieving ACLs for a table.

Without a debug log available, this does appear to be a network issue between your Terraform host and the storage account under management.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the debug log. We are going to close this issue. If you are able to provide the debug log, we can reopen this issue.
