### ISSUE TITLE
Support for associating a NSG at the subnet level

### ISSUE THREAD

**Issue by JihedTounsiTR** [hashicorp/terraform-provider-azurerm#25381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello team,

It seems that it is common for medium to large organizations to enable a policy that disallows the creation of a subnet if, at creation time, the subnet does not have a NSG associated to it.

This does not present a problem when using the `az cli`, please see below example:

```
# Create a Network Security Group
az network nsg create --name {nsg_name} --resource-group {resource_group_name} --location {location}

# Create a Subnet and associate it with the NSG
az network vnet subnet create --name {subnet_name} --resource-group {resource_group_name} --vnet-name {vnet_name} --address-prefixes {address_prefix} --network-security-group {nsg_name}
```

It is a problem when using terraform because the subnet and NSG association is its own resource that gets created after the subnet and the NSG, please see example from the [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet_network_security_group_association) below:

```
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "frontend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_security_group" "example" {
  name                = "example-nsg"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_subnet_network_security_group_association" "example" {
  subnet_id                 = azurerm_subnet.example.id
  network_security_group_id = azurerm_network_security_group.example.id
}
```

Allowing the subnet resource to accept a NSG id, will solve this problem and will also match the  portal and cli.
Many thanks,
Jihed

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
resource "azurerm_subnet" "example" {
  name                 = "frontend"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
  network_security_group_id = azurerm_network_security_group.example.id
}
```
```


### References

- https://registry.terraform.io/modules/haflidif/alz-subnet/azurerm/latest: suggests using the `azapi` provider to overcome the issue.
- https://serverfault.com/questions/1085382/subnet-is-not-creating-with-terraform-on-azure-how-to-fix-it: Suggests creating the subnets in line with the VNet where the subnet block accepts a NSG.

**Comment by tombuildsstuff** [comment]
hi @JihedTounsiTR 

This field has been intentionally removed from the `azurerm_subnet` resource to workaround issues within the Azure Platform during the deletion of resources, as this field has been intentionally removed unfortunately this isn't something we plan to reintroduce.

Instead #9022 is tracking adding an example of how to use Azure Policy with the separate resources, and #3917 is tracking adding additional fields within the `azurerm_virtual_network` resource - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by JihedTounsiTR** [comment]
Thank you for the prompt response.
