### ISSUE TITLE
Can't delete and immediately recreate a storage container

### ISSUE THREAD

**Issue by psdesse-vivlio** [hashicorp/terraform-provider-azurerm#25397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_container

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "container" {
    name                  = "container"
    storage_account_name  = "xxx"
    container_access_type = "blob"
}

```

### Debug Output/Panic Output

```shell
Error: creating Container "container" (Account "Account \"account\" (IsEdgeZone false / ZoneName \"\" / Subdomain Type \"blob\" / DomainSuffix \"core.windows.net\")"): creating container: executing request: unexpected status 409 with response: <?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerBeingDeleted</Code><Message>The specified container is being deleted. Try operation later.
```

### Expected Behaviour

Before version 3.96.0, this used to work properly. This should still be the case. This problem used to be fixed in the past (https://github.com/hashicorp/terraform-provider-azurerm/issues/6803) but it looks like this fix got lost during a dependency upgrade (https://github.com/hashicorp/terraform-provider-azurerm/pull/24798/files#diff-8db40417c7a77f3661557a5f4b11321c18561c1b773941430c0c7f1a9d4ebe34L35).

### Actual Behaviour

The recreate of the resource fails.

### Steps to Reproduce

To reproduce this issue you:

1. Apply it first to create the resources
2. Apply again adding the parameter `-replace azurerm_storage_container.container`

The problem is created by the quick delete and create right after the delete.

**Comment by manicminer** [comment]
Hi @psdesse-vivlio, thanks for reporting this. When we upgraded the SDK, some of the responsibility for request/response handling got moved around - specifically consistency-based retry logic is now [handled in the SDK](https://github.com/tombuildsstuff/giovanni/blob/main/storage/2023-11-03/blob/containers/create.go#L49-L70) rather than in the provider.

It looks like this handling might not be working entirely as expected, which I will look into further. If you can perhaps send a debug log (i.e. use `export TF_LOG=debug`) that would be hugely helpful. Thanks!

**Comment by manicminer** [comment]
@psdesse-vivlio No need to provide any additional info, I was able to identify the source of this issue.

The short version is that we aren't currently retrying enough, but this will soon be fixed :)

**Comment by manicminer** [comment]
Resolved by https://github.com/hashicorp/terraform-provider-azurerm/issues/24295, this will be vendored into the provider in due course.
