### ISSUE TITLE
When create a alert rule for prometheus with `severity = 0` for `CRITICAL`, it skips severity.

### ISSUE THREAD

**Issue by avinode-amagdy** [hashicorp/terraform-provider-azurerm#25399]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.6

### AzureRM Provider Version

~> 3.86

### Affected Resource(s)/Data Source(s)

azurerm_monitor_alert_prometheus_rule_group

### Terraform Configuration Files

```hcl
terraform {
  required_version = ">= 1"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.86"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.25"
    }
  }
}
```

### Debug Output/Panic Output

```shell
```

### Expected Behaviour

To create the alertmanager rule with `severity = 0`, for `CRITICAL` alerts.

### Actual Behaviour

It skips the `severity` and the portal falls back to the default value `severity = 3` for `INFORMATIONAL` 

### Steps to Reproduce

try to create aks cluster and configure a AMW-prometheus instance with it.
Then try to create new `azurerm_monitor_alert_prometheus_rule_group` with `severity = 0` .. check the created resource in the portal and verify the severity of the created resource.

### References

The code has the issue here:

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_alert_prometheus_rule_group_resource.go#L438

**Comment by sinbai** [comment]
Hi @avinode-amagdy thanks for opening this issue. I have submitted [PR #25408](https://github.com/hashicorp/terraform-provider-azurerm/pull/25408) to fix this issue. Could you please track it for more updates?
