### ISSUE TITLE
azurerm_sentinel_data_connector_threat_intelligence broken

### ISSUE THREAD

**Issue by jschwellnus92** [hashicorp/terraform-provider-azurerm#25409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_data_connector_threat_intelligence

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "acctest-01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "example" {
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  solution_name         = "SecurityInsights"
  workspace_name        = azurerm_log_analytics_workspace.example.name
  workspace_resource_id = azurerm_log_analytics_workspace.example.id

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/SecurityInsights"
  }
}

resource "azurerm_sentinel_data_connector_azure_advanced_threat_protection" "example" {
  name                       = "5cf9805d-1bda-401d-b898-0c985e31de31"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id

  depends_on = [
    azurerm_log_analytics_solution.example
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: retrieving Data Connector: (Name "Azure-Sentinel-TIP" / Workspace Name "platform-logs" / Resource Group "platform-logs"): securityinsight.DataConnectorsClient#Get: Failure responding to request: StatusCode=200 -- Original Error: Error occurred unmarshalling JSON - Error = 'parsing time "\"1970-01-01T00:00:00Z\"": month out of range' JSON = '{"id":"/subscriptions/18ebc478-c4af-4365-a746-9026391a40da/resourceGroups/platform-logs/providers/Microsoft.OperationalInsights/workspaces/platform-logs/providers/Microsoft.SecurityInsights/dataConnectors/Azure-Sentinel-TIP","name":"Azure-Sentinel-TIP","etag":"920021e4-0000-1a00-0000-641411860000","type":"Microsoft.SecurityInsights/dataConnectors","kind":"ThreatIntelligence","properties":{"tipLookbackPeriod":"1970-01-01T00:00:00Z","dataTypes":{"indicators":{"state":"enabled"}},"tenantId":"***"}}'
│
```

### Actual Behaviour

`azurerm_sentinel_data_connector_azure_advanced_threat_protection` is already defined in our repo. We are not attempting to make any changes to it however we are experiencing this error. The same error is present when we try to remove the resource. The only way for us to continue using our repo is to comment out this resource and manually remove it from the state file.

**Comment by ziyeqf** [comment]
Hi @jschwellnus92, thanks for reporting.

There is an on-going PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/25343) will fix this, you can subscribe that PR to keep track.

Thanks.

**Comment by jschwellnus92** [comment]
Thanks @ziyeqf, will keep an eye on the PR.
