### ISSUE TITLE
storage.BlobServicesClient#SetServiceProperties: "Required feature Global Dns is disabled."

### ISSUE THREAD

**Issue by fabio-s-franco** [hashicorp/terraform-provider-azurerm#25410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "spoke_std_storage_account" {
  provider = azurerm.cluster_subscription

  name                            = local.std_storage_account_name
  resource_group_name             = "rg"
  location                        = "North Europe"
  account_tier                    = "Standard"
  account_replication_type        = "ZRS"
  public_network_access_enabled   = false
  nfsv3_enabled                   = false
  account_kind                    = "StorageV2"
  is_hns_enabled                  = false
  allow_nested_items_to_be_public = false
  dns_endpoint_type               = "AzureDnsZone"
  shared_access_key_enabled       = false

  network_rules {
    default_action = "Deny"
    bypass         = ["AzureServices"]
  }

  blob_properties {
    versioning_enabled      = true
    change_feed_enabled     = true

    delete_retention_policy {
      days = 10
    }

    restore_policy {
      days = 9
    }
  }

  routing {
    publish_microsoft_endpoints = true
    publish_internet_endpoints  = false
    choice                      = "MicrosoftRouting"
  }

  lifecycle {
    ignore_changes  = [tags]
    prevent_destroy = false
  }
}
```

### Debug Output/Panic Output

```shell
Error: updating `blob_properties`: storage.BlobServicesClient#SetServiceProperties: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="RequiredFeatureDisabled" Message="Required feature Global Dns is disabled."

  with azurerm_storage_account.spoke_std_storage_account,
  on storage_account.tf line 1, in resource "azurerm_storage_account" "spoke_std_storage_account":
   1: resource "azurerm_storage_account" "spoke_std_storage_account" {
```

### Expected Behaviour

That the storage account is created with current settings. 

### Actual Behaviour

This is tricky one because I don't know if:

1 - The request made by the provider is wrong
2 - The combination of parameter I am using is not supported (and the provider lacks the specific validation)
3 - Something on my setup needs to change. I am creating a storage account within the context of hub & spoke architecture
4 - Is a problem with Azure API
5 - The error message is misleading and is throwing me off the real problem. I couldn't find any meaningful information about this error anywhere. There is no such feature, to enable in Azure registration procedure.

What I do know is that:

dns_endpoint_type               = "AzureDnsZone"

causes the error. The required feature Distributed Dns is already enabled for the subscription. Without this flag, the storage account becomes unreachable to the deployment agent. For some reason, the provider tries to access it via the domain name instead of resource id. I can access from the same machine via the portal, but the provider times out  when dns_endpoint_type parameter is not set, due to the fact that the private endpoint has not been created yet, so it fails to validate the resource creation.

Whic creates this kind of chicken and egg problem for storage accounts without public network access being deployed by the provider that runs in a jumpbox, peered to the Hub. The same jumpbox can access the resource via the portal, but not the provider. I already changed the provider to use "storage_use_azuread = true", but that didn't change anything.

Now this error message leads me to nowhere and I can only think that this is a bug, although not entirely sure from where. I exhausted everything I could think of that could cause a side effect like this.

### Steps to Reproduce

You will need a hub and spoke architecture setup and try to create a storage account with this code. 
Hub and spoke are in separate regions and that may play a role.

### Important Factoids

There may be a relation with the fact that the spoke in question is located in North Europe and the Hub is West Europe.
Jumpbox where it is being deployed from is a third spoke which is the same region of the Hub (West Europ)
But the vnets in question have Microsoft.Storage.Global service_endpoint enabled, which would be required for the complete setup which has a private endpoint.

**Comment by magodo** [comment]
@fabio-s-franco The API that failed is the `PUT` towards the `<storageaccount mgmt path>/blobServices/default`. So the network configuration doesn't come into play at this step yet.

The error message also confuse me, I'll try to reach to the storage team for a hint.
