### ISSUE TITLE
azurerm_container_app_custom_domain errors if container app has private registry (secret set)

### ISSUE THREAD

**Issue by fabrideci** [hashicorp/terraform-provider-azurerm#25433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_custom_domain

### Terraform Configuration Files

```hcl
resource "azurerm_container_app" "ingress" {
  name                         = "ingress"
  container_app_environment_id = azurerm_container_app_environment.container-app-environment.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Single"

  template {
    container {
      name   = "hub"
      image  = "ghcr.io/my-org/ingress:latest"
      cpu    = 0.25
      memory = "0.5Gi"
    }
  }

  registry {
    server               = "ghcr.io"
    username             = "my-user"
    password_secret_name = "registry-secret"
  }

  secret {
    name  = "registry-secret"
    value = "my-password"
  }

  ingress {
    target_port      = 80
    external_enabled = true
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}

resource "azurerm_container_app_custom_domain" "root" {
  name                                     = azurerm_dns_a_record.root.fqdn
  container_app_id                         = azurerm_container_app.ingress.id
  container_app_environment_certificate_id = azurerm_container_app_environment_certificate.container-app-certificate.id
  certificate_binding_type                 = "SniEnabled"
}
```

### Debug Output/Panic Output

```shell
Resource Group Name: "***"
Container App Name: "ingress"
Custom Domain Name: "***"): performing CreateOrUpdate: unexpected status 400 with error: ContainerAppSecretInvalid: Invalid Request: Container app secret(s) with name(s) 'registry-secret' are invalid: value or keyVaultUrl and identity should be provided.

  with azurerm_container_app_custom_domain.root,
  on 02-ingress.tf line 37, in resource "azurerm_container_app_custom_domain" "root":
  37: resource "azurerm_container_app_custom_domain" "root" {
```

### Expected Behaviour

The `azurerm_container_app_custom_domain` should correctly add the custom domain.

### Actual Behaviour

The `azurerm_container_app_custom_domain` fails to create. The logs seem to indicate it is because the registry secret is not resolved, presumably because the `azurerm_container_app_custom_domain` is getting the container app in order to update it with the custom domain, but isn't retrieving the secret and then when updating isn't sending the secret back.

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/25196

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. I have marked it as a duplicate and am going to close it since we are reopening the original issue. Thanks again!
