### ISSUE TITLE
Support for `enable_burst_capacity` in azurerm_cosmosdb_account

### ISSUE THREAD

**Issue by RockyMM** [hashicorp/terraform-provider-azurerm#25443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It would be nice that `azurerm_cosmosdb_account` support `enableBurstCapacity` as it does not seem that it is in preview anymore.

### New or Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
resource "azurerm_cosmosdb_account" "example" {
  enable_burst_capacity = true
}
```

### References

* https://learn.microsoft.com/en-us/azure/templates/microsoft.documentdb/databaseaccounts?pivots=deployment-language-terraform#databaseaccountcreateupdatepropertiesordatabaseaccou-2

**Comment by rcskosir** [comment]
Thank you for taking the time to open this feature request! On the documentation you linked, I see preview here:

> enableBurstCapacity	Flag to indicate enabling/disabling of Burst Capacity Preview feature on the account	bool

So for now I am going to label it preview. If you find additional documentation or announcements that it's GA, feel free to reach out and I can update the labels!

**Comment by RockyMM** [comment]
Hey @rcskosir,

This may be the case of conflicting documentation. I also reviewed https://learn.microsoft.com/en-us/azure/cosmos-db/burst-capacity when choosing burst capacity for my Cosmos NoSQL account, and I did not see that it is mentioned that it is in the preview, unlike Merge and some other capabilities. 

However, reading that

> The current implementation of burst capacity is subject to change in the future.

probably the Burst feature should be marked as still in Preview in Learn docs too.

**Comment by jvalteren** [comment]
Hello, I would like to see the `enableBurstCapacity` option exposed in the Terraform resource as well. IMO it is no longer part of the preview API, as you can see here: https://learn.microsoft.com/en-us/azure/templates/microsoft.documentdb/2024-05-15/databaseaccounts?pivots=deployment-language-terraform

The reference that the implementation is subject to change does not have anything to do with Preview status, it indicates that Microsoft might make internal changes in the future. That does not imply that the feature toggle itself will change along with it.

Would you please add the feature toggle to the `cosmosdb_account` resource?
