### ISSUE TITLE
Support for additional settings in liveness_probe, startup_probe and readiness_probe

### ISSUE THREAD

**Issue by pietersap** [hashicorp/terraform-provider-azurerm#25457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The available settings for the configuration of the liveness, readiness and startup probes in Azure Container Apps are lacking a few details.

- **initial_delay**: This setting is configurable in all three types of probes (liveness, readiness, startup) in Azure, but is only exposed in the liveness_probe block in the azurerm provider. It could be added to the readiness_probe and startup_probe blocks.
- **initial_delay**, by the way, currently has weird behaviour. It seems to default to 1, but I cannot set it to 0. So I am currently forced to set the value to 1, even if I want to set it to 0.
- **success_count_threshold**:  This setting is configurable in all three types of probes (liveness, readiness, startup) in Azure, but is only exposed in the readiness_probe block in the azurerm provider. It could be added to the liveness_probe and startup_probe blocks.
- **failure_count_threshold**: available in all three types of probes, in the azurerm provider the maximum value is 10 according to the documentation. I'm not sure if this is by design in the azurerm provider, but for sure Azure allows higher values. I'm currently at 15.

### New or Affected Resource(s)/Data Source(s)

azurerm_container_app

### Potential Terraform Configuration

```hcl
liveness_probe {
  transport               = "TCP"
  port                    = 5001
  interval_seconds        = 10
  timeout                 = 2
  success_count_threshold = 1 # missing
  failure_count_threshold = 6
  initial_delay           = 0
}
readiness_probe {
  transport               = "TCP"
  port                    = 5002
  interval_seconds        = 10
  timeout                 = 2
  success_count_threshold = 1
  failure_count_threshold = 3
  initial_delay           = 0 # missing
}
startup_probe {
  transport               = "TCP"
  port                    = 5002
  interval_seconds        = 2
  timeout                 = 2
  success_count_threshold = 1 # missing
  failure_count_threshold = 10 # current maximum in azurerm, although Azure allows higher
  initial_delay           = 0 # missing
}
```
```

**Comment by pietersap** [comment]
This issue slightly overlaps with this existing issue, but this issue is more complete https://github.com/hashicorp/terraform-provider-azurerm/issues/24845

**Comment by yavuzkaymak** [comment]
I think terminationGracePeriodSeconds is also missing in readiness probe.

https://github.com/Azure/azure-rest-api-specs/blob/main/specification/app/resource-manager/Microsoft.App/stable/2022-03-01/CommonDefinitions.json#L119-L236

**Comment by SpartakusMd** [comment]
Hey @yavuzkaymak, I didn't see this option in the Azure Portal. I also didn't find it in the GO SDK, while in the .NET I found it at the template level.  So in the end I didn't add it to my PR. Feel free to open a separate issue for it though.
