### ISSUE TITLE
Support for `--skip-gpu-driver-install`

### ISSUE THREAD

**Issue by charlienewey-odin** [hashicorp/terraform-provider-azurerm#25455]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Sometimes we want to use the NVIDIA GPU Operator instead for full lifecycle management of GPUs, and so it's occasionally beneficial to skip GPU driver installation.

This is the `--skip-gpu-driver-install` option in the CLI (see references)

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  name                  = "internal"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_NC4as_T4_v3"
  node_count            = 1
  
  skip_gpu_driver_install = true

  tags = {
    Environment = "Production"
  }
}
```

### References

https://learn.microsoft.com/en-us/azure/aks/gpu-cluster?tabs=add-ubuntu-gpu-node-pool#skip-gpu-driver-installation-preview

**Comment by skseth** [comment]
I am hitting the same issue. Though not clearly documented, it appears that the same effect as the CLI --skip-gpu-driver-install is achieved if the tag SkipGPUDriverInstall=True is attached to the node. Can someone confirm if this understanding is correct?

**Comment by charlienewey-odin** [comment]
I can confirm @skseth's suggestion appears to work - I have managed to add this tag & the NVIDIA GPU Operator installs perfectly fine afterwards.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to label this issue as such and close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
