### ISSUE TITLE
Changing `outboundType`  to `userDefinedRouting` leads malfunction error

### ISSUE THREAD

**Issue by HakjunMIN** [hashicorp/terraform-provider-azurerm#25499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

1. Deploy AKS cluster with outbound load balancer setting, without route table and firewall.

2. Change `outboundType` to `userDefinedRouting`
```tf
resource "azurerm_kubernetes_cluster" "k8s" {
  count               = var.resource_count
  name                = local.cluster_names[count.index]
  resource_group_name = azurerm_resource_group.k8s-rg[count.index].name
  location            = azurerm_resource_group.k8s-rg[count.index].location

  dns_prefix = var.dns_prefix
  kubernetes_version = "1.27.7"

  default_node_pool {
    name = "default"
    node_count = var.agent_count
    vm_size = "Standard_D2_v2"
    vnet_subnet_id = azurerm_subnet.node-subnet[count.index].id
    pod_subnet_id = azurerm_subnet.pod-subnet[count.index].id
  }

  identity {
    type = "SystemAssigned"
  }

  ingress_application_gateway {
    gateway_id = azurerm_application_gateway.network[count.index].id
  }

  network_profile {
    load_balancer_sku = "standard"
    network_plugin = "azure"
    outbound_type = "loadBalancer" => "userDefinedRouting"
  }
  tags = {
    Environment = "Development"
    delegation = "trial-01"
  }
}

```
3. Error happened even not specifying `loadBalacerProfile`
```bash
Error: updating Kubernetes Cluster (Subscription: "43fec997-2a49-4f32-8cec-81e390065f4f"

│ Resource Group Name: "aks-rg-0"
│ Kubernetes Cluster Name: "aks-0"): performing CreateOrUpdate: unexpected status 400 with response: {
│   "code": "InvalidUserDefinedRoutingWithLoadBalancerProfile",
│   "details": null,
│   "message": "UserDefinedRouting and load balancer profile are mutually exclusive. Please refer to [http://aka.ms/aks/outboundtype](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Faka.ms%2Faks%2Foutboundtype&data=05%7C02%7Candrewmin%40microsoft.com%7C89642caae95a4a25cad608dc53a3a333%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638477209564450897%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=1cV53KRYKBWkFelvZE%2Bv2vcgOq56qv4Z6vIbjCAsavs%3D&reserved=0) for more details",
│   "subcode": "",
│   "target": "networkProfile.loadBalancerProfile"
│  }
│
│   with azurerm_kubernetes_cluster.k8s[0],
│   on aks.tf line 1, in resource "azurerm_kubernetes_cluster" "k8s":
│    1: resource "azurerm_kubernetes_cluster" "k8s" {
│
```

cc: @lonegunmanb 

### Terraform Version

1.0

### AzureRM Provider Version

3.82

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
Refer to https://github.com/n-y-kim/AKS-tf-error-test/blob/main/aks.tf
```

### Debug Output/Panic Output

```shell
described above
```

### Expected Behaviour

working changing `outboundType` to `userDefinedRouting`

### Actual Behaviour

error populating

UserDefinedRouting and load balancer profile are mutually exclusive.

### Steps to Reproduce

Described above

### References

https://github.com/n-y-kim/AKS-tf-error-test/blob/main/aks.tf

**Comment by lonegunmanb** [comment]
Thanks @HakjunMIN for reporting this issue to us! I'll work for a pr to fix this.
