### ISSUE TITLE
azurerm_log_analytics_workspace issue

### ISSUE THREAD

**Issue by cuntoulishifu** [hashicorp/terraform-provider-azurerm#25497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.0

### AzureRM Provider Version

3.11.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "xxx-logaworkspace" {
  name                = "${var.prefix}-xxx-logaworkspace"
  location            = azurerm_resource_group.xxx.location
  resource_group_name = azurerm_resource_group.xxx.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}
```

### Debug Output/Panic Output

```shell
using Terraform Cloud, not sure how to debug this issue
```

### Expected Behaviour

work as before

### Actual Behaviour

Error: making Read request on AzureRM Log Analytics workspaces 'xxx-logaworkspace': unexpected status 500 (500 Internal Server Error) with response: {"Message":"An error has occurred."}

### Steps to Reproduce

terraform plan

**Comment by cuntoulishifu** [comment]
Actually this TF configuration had been working file before this morning, I checked our git commits and no one had made changes to this resource.

**Comment by Kralizek** [comment]
not sure if related, but for some reason my `azurerm_container_app_environment` needs to be recreated from scratch since this morning.

**Comment by ziyeqf** [comment]
Hi @colinbull, thanks for opening the issue.

However the error message shows it's an internal error on the service side, we are not sure what happens. I personally recommend you to open a support ticket to Azure, to get the service team invovled.

Thanks.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is on the service side and not from azurerm, as such I am going to mark this issue as closed. Feel free to leave any updates here from the service team or support ticket if you have opened one.
