### ISSUE TITLE
Enabling System Managed Identity for an Azure App Service Environment V3 resource using terraform

### ISSUE THREAD

**Issue by kote577422** [hashicorp/terraform-provider-azurerm#25495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

To enable Identity -> System Assigned Identity for an azure app service environment through the [terraform scripts](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/examples/app-service-environment-v3/main.tf). 
Please let us know the possibilities of enabling it through the same resource.

### New or Affected Resource(s)/Data Source(s)

azurerm_app_service_environment_v3

### Potential Terraform Configuration

```hcl
Not seeing identity block for azurerm_app_service_environment_v3 resource. Request to provide the alternate way of enabling the system assigned identity for an ASE V3.
```

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_environment_v3

**Comment by tombuildsstuff** [comment]
hey @kote577422

Checking [the `Azure/azure-rest-api-specs` repository](https://github.com/Azure/azure-rest-api-specs/tree/main/specification/web/resource-manager/Microsoft.Web/stable) the latest available API version for App Service is `2023-01-01` which [doesn't support configuring the identity](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/web/2023-01-01/appserviceenvironments); as such there doesn't appear to be an API for this yet. Would you be able to confirm if this functionality is available in the Azure Portal/CLI?

Thanks!

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
