### ISSUE TITLE
Changing `log_analytics_workspace_id` of `azurerm_container_app_environment` causes new resource to be created rather than in-place update.

### ISSUE THREAD

**Issue by Kralizek** [hashicorp/terraform-provider-azurerm#25511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

When changing the value of the `log_analytics_workspace_id` property of the `azurerm_container_app_environment` resource, Terraform wants to destroy and create the container app environment from scratch.

The same change can be done without such drastic action from Azure portal.

### Terraform Version

1.6.2

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "rg-test"
  location = var.default_location
}

resource "azurerm_log_analytics_workspace" "this" {
  name                = "law-test"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location
}

resource "azurerm_container_app_environment" "this" {
  name                = "env-test"
  resource_group_name = azurerm_resource_group.this.name
  location            = azurerm_resource_group.this.location

  log_analytics_workspace_id = null

  timeouts {
    create = "15m"
  }
}
```

### Debug Output/Panic Output

```shell
I am unable to recover the logs as I already worked around the issue.
```

### Expected Behaviour

Changing `log_analyics_workspace_id` from `null` to `azurerm_log_analytics_workspace.this.id` should not require the recreation of the resource.

### Actual Behaviour

The resource needs to be destroyed and recreated.

### Steps to Reproduce

2. change `log_analyics_workspace_id` from `null` to `azurerm_log_analytics_workspace.this.id`
3. `terraform apply`

**Comment by chlsmith** [comment]
I'm seeing similar behavior when I define log analytics in the same code repo as my container environment, even if I'm not changing anything on the log analytics workspace.   Regardless, the container environment is being recreated from scratch.
