### ISSUE TITLE
azurerm_application_insights app_id refreshing/pulling incorrect value with 3.98

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azurerm#25519]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.0

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights 

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "tf-test"
  location = "West Europe"
}

resource "azurerm_application_insights" "example" {
  name                = "tf-test-appinsights"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  application_type    = "web"
}

output "instrumentation_key" {
  value = azurerm_application_insights.example.instrumentation_key
}

output "app_id" {
  value = azurerm_application_insights.example.app_id
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

app_id should not be showing a change when moving to 3.98.0 from 3.97.0

### Actual Behaviour

when planning applying terraform spits out about values changing outside terraform...that haven't actually changed for the app_id of the app_insights resource.  it seems to now be pulling the resource name of the app insights instance as app_id instead of the guid value.

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1514496/42cce466-023d-4e53-98de-51fb93df35c6)

### Steps to Reproduce

run an apply in 3.98.0 for any app insights resource you had clean with 3.97.1

**Comment by stephybun** [comment]
Thanks for raising this @drdamour. It looks like I introduced this when updating the resource to use our SDK `hashicorp/go-azure-sdk`. I'll get a fix for this in to the next week's release.

**Comment by drdamour** [comment]
Is this hotfix worthy? It ended up breaking a bots logging because we ref this attribute for the botkits insights_app_id field
