### ISSUE TITLE
v3.98.0: azurerm_application_insights_api_key fails with error due to casing in `resourcegroup`

### ISSUE THREAD

**Issue by patst** [hashicorp/terraform-provider-azurerm#25522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights_api_key

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights_api_key" "a" {
  name                    = "appik-${local.resource_infix}-a"
  application_insights_id = var.datasources.application_insights.id
  read_permissions        = ["aggregate", "api", "draft", "extendqueries", "search"]
  write_permissions       = ["annotations"]
}
```

### Debug Output/Panic Output

```shell
Error: parsing "/subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match

Expected a ApiKey ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue/apiKeys/keyIdValue

However this value was provided:

> /subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349

The parsed Resource ID was missing a value for the segment at position 2
(which should be the literal value "resourceGroups").



  with module.chatbot.azurerm_application_insights_api_key.chatbot,
  on ../../../../../modules/gap-chatbot/main.tf line 31, in resource "azurerm_application_insights_api_key" "chatbot":
  31: resource "azurerm_application_insights_api_key" "chatbot" {

##[error]Terraform command 'plan' failed with exit code '1'.:  parsing "/subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match
##[error]
Error: parsing "/subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match

Expected a ApiKey ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue/apiKeys/keyIdValue

However this value was provided:

> /subscriptions/<subscriptionid>/resourcegroups/rg-my-resource/providers/microsoft.insights/components/appi-my-resource/apiKeys/f4ad4343-cf20-424e-b111-b86e5a83a349

The parsed Resource ID was missing a value for the segment at position 2
(which should be the literal value "resourceGroups").
```

### Expected Behaviour

resource is created

### Actual Behaviour

error occurs (see debug output)

### Steps to Reproduce

`terraform plan`

The issue occurs after updating the provider to v3.98.0 and running a plan.

The issue did not occur with provider version 3.97.1

I think it is probably an error in the Azure REST API,  which returns the value `resourcegroup` in lower casing. The validation expect its with an upper `g`(`resourceGroup`)

### References

Maybe it is related to this change: https://github.com/hashicorp/terraform-provider-azurerm/pull/25376

**Comment by Devvox93** [comment]
I have similar Output and indeed this did not happen with 3.97.1 and now occurs with 3.98.0.
My observation is that it is indeed casing, but not with "resourceGroups" but with "Microsoft.Insights" (expected) and "microsoft.insights" (provided).
I can see that that differs in the error message in my own pipeline as well as the output provided above.

**Comment by katbyte** [comment]
I believe this might have been caused by #25376

**Comment by celia-moreno** [comment]
I am facing also similar issue. Output: 

```
Error: parsing "/subscriptions/<mysubscriptionId>/resourcegroups/<myResourceGroup>/providers/microsoft.insights/components/<myComponentName>/apiKeys/<myApiKeyvalue>": parsing segment "staticResourceGroups": parsing the ApiKey ID: the segment at position 2 didn't match

Expected a ApiKey ID that matched:

> /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.Insights/components/componentValue/apiKeys/keyIdValue

However this value was provided:

> /subscriptions/<mysubscriptionId>/resourcegroups/<myResourceGroup>/providers/microsoft.insights/components/<myComponentName>/apiKeys/<myApiKeyvalue>

The parsed Resource ID was missing a value for the segment at position 2
(which should be the literal value "resourceGroups").
```

**Comment by tombuildsstuff** [comment]
@Devvox93 apologies for the inconvenience here, it appears that a second state migration is needed on that resource too - @stephybun can you take a look at that adding that one?

Alternatively/in the interim you should be able to workaround that by using `terraform state rm` to remove this resource from your state and then re-importing the `terraform import` the `azurerm_application_insights` resource with the fixed Resource ID, which'll fix this.

**Comment by Devvox93** [comment]
Thanks for confirming it's not on our side and not blaming anyone. We're all human!

Unfortunately, this runs in separated environments, each with isolated state backends with no direct way of accessing them.
To prevent manual changes, we've temporarily locked our provider version to 3.97.1 and will remove that lock once this issue is released. Will that be a 3.99.1 or should we wait for 3.100? Either way is fine by me/us :)
