### ISSUE TITLE
Version 3.98.0 azurerm_storage_account plan fails with Error: retrieving queue properties for Storage Account : unmarshalling response: could not parse response body

### ISSUE THREAD

**Issue by theTPH** [hashicorp/terraform-provider-azurerm#25521]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

2.237.1

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "strgacc" {
  name                              = var.cn_storage_acc_name
  resource_group_name               = var.strg_rg_name
  location                          = var.region
  account_tier                      = var.strg_tier
  account_replication_type          = var.strg_replication
  account_kind                      = var.strg_kind
  large_file_share_enabled          = var.strg_large_file_share_enabled
  min_tls_version                   = "TLS1_2"
  infrastructure_encryption_enabled = var.strg_inf_encryp_enabled
  dns_endpoint_type                 = var.strg_dns_endpoint_type

  network_rules {
    default_action             = "Allow"
    bypass                     = ["Logging", "Metrics", "AzureServices"]
    virtual_network_subnet_ids = var.strg_allowed_subnet_ids
    ip_rules                   = var.strg_public_ips
  }

  azure_files_authentication {
    directory_type = var.domain_directory_type
    active_directory {
      storage_sid         = var.strg_sid
      domain_name         = var.domain_name
      domain_sid          = var.domain_sid
      domain_guid         = var.domain_guid
      forest_name         = var.domain_forest
      netbios_domain_name = var.domain_netbios_name
    }
  }
  tags = var.resource_tags
}
```

### Debug Output/Panic Output

```shell
Plan: 2 to add, 16 to change, 8 to destroy.
╷
│ Error: retrieving queue properties for Storage Account (Subscription: "***"
│ Resource Group Name: "RGNAME"
│ Storage Account Name: "ACCOUNTNAME"): unmarshalling response: could not parse response body
│ 
│   with module.azadStorage.azurerm_storage_account.strgacc,
│   on .terraform/modules/azadStorage/terraform/modules/azad-storage-module/main.tf line 14, in resource "azurerm_storage_account" "strgacc":
│   14: resource "azurerm_storage_account" "strgacc" {
```

### Expected Behaviour

Finish planning

### Actual Behaviour

After the new provider release all my plans fail with the error above. 
I have tested in multiple customer environments. I made no changes to the storage accounts in the last days in any of these environments.The last change in all of them was switching to provider version 3.97.1 to accommodate the new  "dns_endpoint_type" property.
When I switch back to provider version 3.97.1 everything works.

**Comment by cveld** [comment]
Can you adjust the typo in the title of this issue. 3.89.0 -> 3.98.0

**Comment by theTPH** [comment]
fixed typo in title

**Comment by ciso-davidpham** [comment]
Not sure if this is related but when setting the property shared_access_key_enabled=true on the azurerm_storage_account resource it will output the same "unmarshalling response: could not parse response body" error, attempts to destroy will also fail the same way.

I needed to set it to false then it would build fine, after the build I could then update it to false however when attempting to destroy after it was set to shared_access_key_enabled=true , it would then fail with the same error.

**Comment by Joseluismantilla** [comment]
I can confirm this issue still happens with 3.97.1 and 3.98, when the Storage account has all private endpoints for its sub components like file, queue, table and blob, Terraform can't handle all of them, the quick workaround is to delete all private endpoints in the SA section to avoid this error.

**Comment by enorlando** [comment]
We have had the same issue when upgrading to 3.98.0 of the provider. Dropping back to 3.97.1 and no errors

**Comment by bandrews-ke** [comment]
We are having the same issue in 3.98.0, 3.97.1, and 3.96.0.  Do not have a workaround at the moment.

**Comment by PhilHamlin-MS** [comment]
Same issue in 3.98.0 and 3.97.1.

**Comment by rostrovsky** [comment]
This issue still occurs in 3.99.0 ...

**Comment by mason-mcglothlin** [comment]
Same issue still occurs in 3.99.0 for us too.

**Comment by tombuildsstuff** [comment]
@mason-mcglothlin @rostrovsky any chance you could providing the debug logs (using `TF_LOG=debug`) around this error message, so that we can dig into this one? Unfortunately the Terraform Configuration in the description is too generic enough for us to be able to reproduce this given the behaviour of Storage Accounts changes depending on the Account Type etc

**Comment by rostrovsky** [comment]
> @mason-mcglothlin @rostrovsky any chance you could providing the debug logs (using `TF_LOG=debug`) around this error message, so that we can dig into this one? Unfortunately the Terraform Configuration in the description is too generic enough for us to be able to reproduce this given the behaviour of Storage Accounts changes depending on the Account Type etc

unfortunately no, I work in regulated environment and can't access GH there to copy logs :(

**Comment by bandrews-ke** [comment]
@tombuildsstuff I've found that if the shared_access_key_enabled is set to false and the provider storage_use_azuread flag is also false that this is a decent way to replicate this issue.  When I set the storage_use_azuread flag to true, it does start to work sometimes, but othertimes it doesn't.

Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#shared_access_key_enabled

**Comment by mason-mcglothlin** [comment]
Okay, here's the full response for one of the storage accounts we're getting an error for, but I've replaced the potentially sensitive data with `--REDACTED--`

```
{
	"module": "module.appstorageaccount",
	"mode": "managed",
	"type": "azurerm_storage_account",
	"name": "storage",
	"provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
	"instances": [
	 {
	   "schema_version": 4,
	   "attributes": {
		 "access_tier": "Hot",
		 "account_kind": "StorageV2",
		 "account_replication_type": "ZRS",
		 "account_tier": "Standard",
		 "allow_nested_items_to_be_public": false,
		 "allowed_copy_scope": "",
		 "azure_files_authentication": [
		   {
			 "active_directory": [
			   {
				 "domain_guid": "--REDACTED--",
				 "domain_name": "--REDACTED--",
				 "domain_sid": "--REDACTED--",
				 "forest_name": "--REDACTED--",
				 "netbios_domain_name": "--REDACTED--",
				 "storage_sid": "--REDACTED--"
			   }
			 ],
			 "directory_type": "AD"
		   }
		 ],
		 "blob_properties": [
		   {
			 "change_feed_enabled": false,
			 "change_feed_retention_in_days": 0,
			 "container_delete_retention_policy": [],
			 "cors_rule": [],
			 "default_service_version": "",
			 "delete_retention_policy": [],
			 "last_access_time_enabled": false,
			 "restore_policy": [],
			 "versioning_enabled": false
		   }
		 ],
		 "cross_tenant_replication_enabled": true,
		 "custom_domain": [],
		 "customer_managed_key": [],
		 "default_to_oauth_authentication": false,
		 "edge_zone": "",
		 "enable_https_traffic_only": true,
		 "id": "/subscriptions/--REDACTED--/resourceGroups/nprod-gr-qae-rg/providers/Microsoft.Storage/storageAccounts/nprodgrqaeappst",
		 "identity": [],
		 "immutability_policy": [],
		 "infrastructure_encryption_enabled": false,
		 "is_hns_enabled": false,
		 "large_file_share_enabled": true,
		 "local_user_enabled": true,
		 "location": "southcentralus",
		 "min_tls_version": "TLS1_2",
		 "name": "nprodgrqaeappst",
		 "network_rules": [
		   {
			 "bypass": [
			   "AzureServices"
			 ],
			 "default_action": "Deny",
			 "ip_rules": [
			   "40.77.125.151"
			 ],
			 "private_link_access": [
			   {
				 "endpoint_resource_id": "/subscriptions/--REDACTED--/providers/Microsoft.Security/datascanners/storageDataScanner",
				 "endpoint_tenant_id": "--REDACTED--"
			   }
			 ],
			 "virtual_network_subnet_ids": []
		   }
		 ],
		 "nfsv3_enabled": false,
		 "primary_access_key": "--REDACTED--",
		 "primary_blob_connection_string": "--REDACTED--",
		 "primary_blob_endpoint": "https://nprodgrqaeappst.blob.core.windows.net/",
		 "primary_blob_host": "nprodgrqaeappst.blob.core.windows.net",
		 "primary_blob_internet_endpoint": "",
		 "primary_blob_internet_host": "",
		 "primary_blob_microsoft_endpoint": "",
		 "primary_blob_microsoft_host": "",
		 "primary_connection_string": "--REDACTED--",
		 "primary_dfs_endpoint": "https://nprodgrqaeappst.dfs.core.windows.net/",
		 "primary_dfs_host": "nprodgrqaeappst.dfs.core.windows.net",
		 "primary_dfs_internet_endpoint": "",
		 "primary_dfs_internet_host": "",
		 "primary_dfs_microsoft_endpoint": "",
		 "primary_dfs_microsoft_host": "",
		 "primary_file_endpoint": "https://nprodgrqaeappst.file.core.windows.net/",
		 "primary_file_host": "nprodgrqaeappst.file.core.windows.net",
		 "primary_file_internet_endpoint": "",
		 "primary_file_internet_host": "",
		 "primary_file_microsoft_endpoint": "",
		 "primary_file_microsoft_host": "",
		 "primary_location": "southcentralus",
		 "primary_queue_endpoint": "https://nprodgrqaeappst.queue.core.windows.net/",
		 "primary_queue_host": "nprodgrqaeappst.queue.core.windows.net",
		 "primary_queue_microsoft_endpoint": "",
		 "primary_queue_microsoft_host": "",
		 "primary_table_endpoint": "https://nprodgrqaeappst.table.core.windows.net/",
		 "primary_table_host": "nprodgrqaeappst.table.core.windows.net",
		 "primary_table_microsoft_endpoint": "",
		 "primary_table_microsoft_host": "",
		 "primary_web_endpoint": "https://nprodgrqaeappst.z21.web.core.windows.net/",
		 "primary_web_host": "nprodgrqaeappst.z21.web.core.windows.net",
		 "primary_web_internet_endpoint": "",
		 "primary_web_internet_host": "",
		 "primary_web_microsoft_endpoint": "",
		 "primary_web_microsoft_host": "",
		 "public_network_access_enabled": true,
		 "queue_encryption_key_type": "Service",
		 "queue_properties": [
		   {
			 "cors_rule": [],
			 "hour_metrics": [
			   {
				 "enabled": true,
				 "include_apis": true,
				 "retention_policy_days": 7,
				 "version": "1.0"
			   }
			 ],
			 "logging": [
			   {
				 "delete": false,
				 "read": false,
				 "retention_policy_days": 0,
				 "version": "1.0",
				 "write": false
			   }
			 ],
			 "minute_metrics": [
			   {
				 "enabled": false,
				 "include_apis": false,
				 "retention_policy_days": 0,
				 "version": "1.0"
			   }
			 ]
		   }
		 ],
		 "resource_group_name": "nprod-gr-qae-rg",
		 "routing": [],
		 "sas_policy": [],
		 "secondary_access_key": "--REDACTED--",
		 "secondary_blob_connection_string": "",
		 "secondary_blob_endpoint": null,
		 "secondary_blob_host": null,
		 "secondary_blob_internet_endpoint": null,
		 "secondary_blob_internet_host": null,
		 "secondary_blob_microsoft_endpoint": null,
		 "secondary_blob_microsoft_host": null,
		 "secondary_connection_string": "--REDACTED--",
		 "secondary_dfs_endpoint": null,
		 "secondary_dfs_host": null,
		 "secondary_dfs_internet_endpoint": null,
		 "secondary_dfs_internet_host": null,
		 "secondary_dfs_microsoft_endpoint": null,
		 "secondary_dfs_microsoft_host": null,
		 "secondary_file_endpoint": null,
		 "secondary_file_host": null,
		 "secondary_file_internet_endpoint": null,
		 "secondary_file_internet_host": null,
		 "secondary_file_microsoft_endpoint": null,
		 "secondary_file_microsoft_host": null,
		 "secondary_location": "",
		 "secondary_queue_endpoint": null,
		 "secondary_queue_host": null,
		 "secondary_queue_microsoft_endpoint": null,
		 "secondary_queue_microsoft_host": null,
		 "secondary_table_endpoint": null,
		 "secondary_table_host": null,
		 "secondary_table_microsoft_endpoint": null,
		 "secondary_table_microsoft_host": null,
		 "secondary_web_endpoint": null,
		 "secondary_web_host": null,
		 "secondary_web_internet_endpoint": null,
		 "secondary_web_internet_host": null,
		 "secondary_web_microsoft_endpoint": null,
		 "secondary_web_microsoft_host": null,
		 "sftp_enabled": false,
		 "share_properties": [
		   {
			 "cors_rule": [],
			 "retention_policy": [
			   {
				 "days": 7
			   }
			 ],
			 "smb": []
		   }
		 ],
		 "shared_access_key_enabled": true,
		 "static_website": [],
		 "table_encryption_key_type": "Service",
		 "tags": {},
		 "timeouts": null
	   },
	   "sensitive_attributes": [],
	   "private": "--REDACTED--",
	   "dependencies": [
		 "module.servicessubnet.azurerm_network_security_group.nsg",
		 "module.servicessubnet.azurerm_network_security_rule.nsg-rules",
		 "module.servicessubnet.azurerm_network_security_rule.nsg-rules-with-source-prefixes-list",
		 "module.servicessubnet.azurerm_subnet.subnet",
		 "module.servicessubnet.azurerm_subnet_network_security_group_association.nsga",
		 "module.servicessubnet.azurerm_subnet_route_table_association.routetable",
		 "module.servicessubnet.data.azurerm_resource_group.networkresourcegroup",
		 "module.servicessubnet.data.azurerm_resource_group.resourcegroup",
		 "module.servicessubnet.data.azurerm_route_table.routetable",
		 "module.servicessubnet.data.azurerm_virtual_network.vnet"
	   ]
	 }
	]
}
```

And here's the error that went along with it:
```
2024-04-12T15:13:06.843Z [DEBUG] provider.terraform-provider-azurerm_v3.99.0_x5.exe: POST https://management.azure.com/subscriptions/--REDACTED--/resourceGroups/nprod-gr-qae-rg/providers/Microsoft.Storage/storageAccounts/nprodgrqaecldwtnssst/listKeys?%24expand=kerb&api-version=2023-01-01: timestamp=2024-04-12T15:13:06.841Z
2024-04-12T15:13:06.844Z [ERROR] provider.terraform-provider-azurerm_v3.99.0_x5.exe: Response contains error diagnostic: diagnostic_severity=ERROR diagnostic_summary="retrieving queue properties for Storage Account (Subscription: "--REDACTED--"
Resource Group Name: "nprod-gr-qae-rg"
Storage Account Name: "nprodgrqaeappst"): unmarshalling response: could not parse response body" tf_proto_version=5.4 tf_resource_type=azurerm_storage_account diagnostic_detail= tf_provider_addr=provider tf_req_id=1755e503-e451-1504-a5c4-b6a5f1242832 @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto tf_rpc=ReadResource timestamp=2024-04-12T15:13:06.844Z
2024-04-12T15:13:06.845Z [ERROR] vertex "module.appstorageaccount.azurerm_storage_account.storage" error: retrieving queue properties for Storage Account (Subscription: "--REDACTED--"
Resource Group Name: "nprod-gr-qae-rg"
Storage Account Name: "nprodgrqaeappst"): unmarshalling response: could not parse response body
2024-04-12T15:13:06.845Z [ERROR] vertex "module.appstorageaccount.azurerm_storage_account.storage (expand)" error: retrieving queue properties for Storage Account (Subscription: "--REDACTED--"
Resource Group Name: "nprod-gr-qae-rg"
Storage Account Name: "nprodgrqaeappst"): unmarshalling response: could not parse response body
```

I hope that helps - please let me know if more info is needed.

**Comment by srivastavaprashant** [comment]
Downgrading to `3.97.1` didn't help.

**Comment by mason-mcglothlin** [comment]
> Downgrading to `3.97.1` didn't help.

@srivastavaprashant I downgraded to v3.95.0 and it did get me past the error.

**Comment by cerocool1203** [comment]
I have to downgrade to 3.97.1 for this error below to bypass it. I was running version 3.99 and when reaching the file share on Private endpoint I get this. Also, tried version 3.98 same problem. Since the changes made from 3.97 the provider has become quite instable as Storage Accounts are used almost on every single deployment

```
│ x-ms-date:Wed, 17 Apr 2024 06:08:40 GMT
│ x-ms-version:2023-11-03
│ /azstadev1/dev-files
│ restype:share'.</AuthenticationErrorDetail></Error>
│ 
│   with azurerm_storage_share.file_share_1,
│   on main.tf line 50, in resource "azurerm_storage_share" "file_share_1":
│   50: resource "azurerm_storage_share" "file_share_1" {
│ 
╵
╷
│ Error: executing request: unexpected status 403 (403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.) with response: ﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
│ RequestId:1de1725b-c01a-0009-0b8d-908f83000000
│ Time:2024-04-17T06:08:40.7833886Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'dsadaffsdgdfdf' is not the same as any computed signature. Server used following string to sign: 'GET
```

Additionally we were also getting randomly the error below on v3.99 so 1 out 3 runs it will work 

```
╷
│ Error: unable to locate "Storage Account (Subscription: \"mysub\"\nResource Group Name: \"myrg\"\nStorage Account Name: \"azstorage\")"
│ 
│   with module.key_vault.module.storage_account_for_operational_logs.azurerm_storage_account.storage_account,
│   on .terraform/modules/key_vault.storage_account_for_operational_logs/main.tf line 1, in resource "azurerm_storage_account" "storage_account":
│    1: resource "azurerm_storage_account" "storage_account" {
│ 
╵
Operation failed: failed running terraform plan (exit 1)
```

**Comment by tombuildsstuff** [comment]
@manicminer mind taking a look into this one?

**Comment by manicminer** [comment]
Thanks all for the additional information. I think there may be at least two issues occurring here - one of them may be related to https://github.com/hashicorp/terraform-provider-azurerm/issues/25527.

**Comment by manicminer** [comment]
@bandrews-ke When you don't set the `storage_use_azuread = true` provider property, and also specify `shared_key_access = false`, the storage account resource will not work correctly and the various resources that use the Storage API will not work at all. These setting combinations are mutually exclusive - however we can do a better job of reporting on this than the current "could not parse response body" error and I'll look at this.

To everyone experiencing this error message (and assuming you have set `storage_user_azuread = true`) - does this error surface only when you are using privatelink endpoints and/or have set `public_network_access_enabled = false` for the storage account, or does it happen even when you have not?

**Comment by ncole** [comment]
`storage_use_azuread = true`, `public_network_access_enabled = true`, `shared_access_key_enabled = false` for me. Downgrading doesn't work.

**Comment by manicminer** [comment]
@ncole We added support in v3.96.0 for AAD authentication for the following resources:

- azurerm_storage_share_file
- azurerm_storage_share_directory
- azurerm_storage_table
- azurerm_storage_table_entity

When specifying `storage_use_azuread = true`, you must ensure your Terraform principal has the relevant permissions for these services/resources. For storage file services, in addition to the permissions you mentioned, this also include:

- Microsoft.Storage/storageAccounts/fileServices/readFileBackupSemantics/action
- Microsoft.Storage/storageAccounts/fileServices/writeFileBackupSemantics/action

For reference when building custom roles, the list of required permissions when using Azure AD authentication with the storage API is documented on [this Microsoft page](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory#permissions-for-calling-data-operations).

Hope this helps!

**Comment by Bungee1797** [comment]
> @tombuildsstuff I've found that if the shared_access_key_enabled is set to false and the provider storage_use_azuread flag is also false that this is a decent way to replicate this issue. When I set the storage_use_azuread flag to true, it does start to work sometimes, but othertimes it doesn't.
> 
> Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#shared_access_key_enabled

Removing this also fixed the issue for me

**Comment by srivastavaprashant** [comment]
we can force terraform to use AD to access this bucket by setting:
```
provider "azurerm" {
  storage_use_azuread = true
  features {}
}
```
By doing this, terraform can access the bucket by AD, not using a shared_key. 
Unfortunately, there is no way to specify this in the resource definition. It could be a useful feature though.

**Comment by manicminer** [comment]
As `storage_use_azuread` is behavioral and isn't related to the state of individual resources, it was implemented as a provider property. We generally suggest using provider aliases if you'd like to selectively apply this behavior for different resources.

**Comment by RudyD** [comment]
I too am facing the problem. I upgrade to 3.100.0 azurerm version. I set my provider to use azurerm provider to use `storage_use_azuread = true` and set `shared_access_key_enabled = false` in my storage account. I'm using private endpoint and my storage account resource code is below:

```
resource "azurerm_storage_account" "storageforfuncapp" {
  name                            = "safunapp${local.suffix}"
  resource_group_name             = azurerm_resource_group.resource_group.name
  location                        = azurerm_resource_group.resource_group.location
  account_tier                    = "Standard"
  account_kind                    = "StorageV2"
  account_replication_type        = "GRS"
  enable_https_traffic_only       = true
  min_tls_version                 = "TLS1_2"
  shared_access_key_enabled       = false
  public_network_access_enabled   = false
  allow_nested_items_to_be_public = false

  network_rules {
    default_action             = "Deny"
    bypass                     = ["AzureServices"]
    virtual_network_subnet_ids = [azurerm_subnet.subnetpaas.id]
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.user_assigned_identity_for_blob.id]
  }

  blob_properties {
    last_access_time_enabled = true
    delete_retention_policy {
      days = 7
    }
  }

  queue_properties {
    logging {
      delete                = true
      read                  = true
      write                 = true
      version               = "1.0"
      retention_policy_days = 10
    }
    hour_metrics {
      enabled               = true
      include_apis          = true
      version               = "1.0"
      retention_policy_days = 10
    }
    minute_metrics {
      enabled               = true
      include_apis          = true
      version               = "1.0"
      retention_policy_days = 10
    }
  }
}
```

**Comment by RudyD** [comment]
I guess I should rip out my private endpoints until this issue is fixed?

**Comment by vmartinlantek** [comment]
> I guess I should rip out my private endpoints until this issue is fixed? I'd pitch in, but wouldn't know where to begin to assist in fixing.

Unless you need a specific feature of the latest providers (3.96 and higher), you can revert to version 3.95 where this bug is not present.

**Comment by manicminer** [comment]
I've marked this issue as resolved, as we've added better error response parsing which _should_ eliminate the "unmarshalling response" error and replace it with something more useful.
