### ISSUE TITLE
unable to deploy Azure Api management in the existing azure vnet subnet

### ISSUE THREAD

**Issue by sharatbhaskar1988** [hashicorp/terraform-provider-azurerm#25566]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

zurerm_api_management

### Terraform Configuration Files

```hcl
Data block section

data "azurerm_resource_group" "rg" {
  name = "azdlgleuw-rg-sharatapigw-001"
}
    
data "azurerm_virtual_network" "virtualnetwork" {
  name                = "azdlgleuw-vnet-sharatapigw-001"
  resource_group_name = data.azurerm_resource_group.rg.name
}


data "azurerm_subnet" "apisubnet" {
  name                 = "azdlgleuw-snet-sharatapigw-001"
  resource_group_name  = data.azurerm_resource_group.rg.name
  virtual_network_name = data.azurerm_virtual_network.virtualnetwork.name
}



Resource Block

resource "azurerm_public_ip" "api-pip" {
    allocation_method   = "Static"
    location            = data.azurerm_resource_group.rg.location
    name                = "azdlgleuw-pip-publicip-001"
    resource_group_name = data.azurerm_resource_group.rg.name
    sku                 = "Standard"
    zones = [1,2,3]
    sku_tier                = "Regional"
    idle_timeout_in_minutes = 4
    ip_version              = "IPv4"
    domain_name_label   = "azure-api-sharatapigw-001"

}


Creating the API management resources

resource "azurerm_api_management" "apim" {
  name                 = "azdlgleuw-apim-apimngname-001"
  resource_group_name  = data.azurerm_resource_group.rg.name
  location             = data.azurerm_resource_group.rg.location
  publisher_name       = "sharat"
  publisher_email      = "abcde@xyz.com"
  virtual_network_type = "Internal"
  sku_name             = "Developer_1"

  virtual_network_configuration {
    subnet_id = data.azurerm_subnet.apisubnet.id

  }

    public_ip_address_id = azurerm_public_ip.api-pip.id

}


resource "azurerm_api_management_api" "sharatapimgmntapi" {
  name                = "azdlgleuw-apim-apimgmntapi-001"
  resource_group_name = data.azurerm_resource_group.rg.name
  api_management_name = azurerm_api_management.apim.name
  revision            = "1"
  display_name        = "sharat-api"
  path                = "extranet/v1"
  protocols           = ["https"]

  import {
    content_format = "openapi"
    content_value  = file("${path.module}/openapi.yaml")
  }

}

resource "azurerm_api_management_api_policy" "example" {
  api_name            = azurerm_api_management_api.sharatapimgmntapi.name
  api_management_name = azurerm_api_management.apim.name
  resource_group_name = data.azurerm_resource_group.rg.name

  xml_content = <<XML
<policies>
  <inbound>
    <base />
    <set-backend-service base-url="https://azure-api-sharatapigw-001.azurewebsites.net/api" />
  </inbound>
</policies>
XML


}
```

### Debug Output/Panic Output

```shell
NA
```

### Expected Behaviour

Api management should get deployed with the public ip in the azure vnet subnet

### Actual Behaviour

Error message: Error: creating/updating Service (Subscription: "xxxxxxxxxxxxxx" │ Resource Group Name: "azdlgleuw-rg-sharatapigw-001" │ Service Name: "azure-api-sharatapigw-001"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidParameters: Invalid parameter: When updating subnetResourceId to /subscriptions/xxxxxxxx/resourceGroups/azdlgleuw-rg-sharatapigw-001/providers/Microsoft.Network/virtualNetworks/azdlgleuw-vnet-sharatapigw-001/subnets/azdlgleuw-snet-sharatapigw-001 in API Management service deployment with Virtual Network configured Internal, the Public IP Address property in location West Europe, must be a different from /subscriptions/xxxxxxxxxxxxx/resourceGroups/azdlgleuw-rg-sharatapigw-001/providers/Microsoft.Network/publicIPAddresses/azdlgleuw-pip-publicip-001 and should not match any of the existing location(s) (West Europe), as we need to create a new deployment to avoid downtime.

**Comment by sharatbhaskar1988** [comment]
@scott-doyland-burrows can you please suggest something in my issue?

**Comment by sinbai** [comment]
Hi @sharatbhaskar1988 thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).

**Comment by tombuildsstuff** [comment]
As per @sinbai's comment above, since this appears to be a configuration related question rather than a bug in the Provider I'm going to close this issue for the moment, but I'd instead direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).
