### ISSUE TITLE
azurerm_managed_disk will not work when disk attached to VM in scaleset

### ISSUE THREAD

**Issue by david-garcia-garcia** [hashicorp/terraform-provider-azurerm#25582]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.8.0

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

azurerm_managed_disk

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "example" {
  name                 = "${local.appname}_disk"
  location             = azurerm_resource_group.example.location
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = 110
}
```

### Debug Output/Panic Output

```shell
--
```

### Expected Behaviour

No error

### Actual Behaviour

The following error:

```
Expected a VirtualMachine ID that matched:
│
│ > /subscriptions/xxx/resourceGroups/example-resource-group/providers/Microsoft.Compute/virtualMachines/virtualMachineValue
│
│ However this value was provided:
│
│ > /subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Compute/virtualMachineScaleSets/akswinpl3/virtualMachines/akswinpl3_0  
```

### Steps to Reproduce

Modify properties of an Azure Virtual HD that is attached to a VM that is part of a ScaleSet.

**Comment by ms-zhenhua** [comment]
Hi @david-garcia-garcia, thank you for reaching out.
I do not quite understand the problem from your configuration snippet.  Could you please provide the whole executable Configuration so that we can do more investigations?

**Comment by david-garcia-garcia** [comment]
@ms-zhenhua yep that snippet is just for the disk.

The problem here is that - to reproduce - you would need to build a terraform with a VM scaleset and a disk attached to one VM inside that scaleset. There are many ways to achieve and reproduce that. I am using AKS which makes using my terraform setup as an example complex.

I have asked ChatGPT to build a simple sample for the described issue "please make me a terraform with an azure disk attached to a vm inside a scaleset":

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine_scale_set" "example" {
  name                = "example-scaleset"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard_DS1_v2"
  instances           = 2
  admin_username      = "adminuser"
  admin_password      = "Password1234!"

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "18.04-LTS"
    version   = "latest"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]
}

resource "azurerm_managed_disk" "example" {
  name                 = "example-disk"
  location             = azurerm_resource_group.example.location
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = 10
}

resource "azurerm_virtual_machine_data_disk_attachment" "example" {
  managed_disk_id    = azurerm_managed_disk.example.id
  virtual_machine_id = azurerm_linux_virtual_machine_scale_set.example.id
  lun                = 10
  caching            = "ReadWrite"
}
```

Yet, I believe that the error message is self-explanatory:

```
Expected a VirtualMachine ID that matched:
│
│ > /subscriptions/xxx/resourceGroups/example-resource-group/providers/Microsoft.Compute/virtualMachines/virtualMachineValue
│
│ However this value was provided:
│
│ > /subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Compute/virtualMachineScaleSets/akswinpl3/virtualMachines/akswinpl3_0 
```

I believe that it is clear from this message, that the implementation is looking for a specific pattern for the VM ID, but when a VM is in a scaleset, the pattern is different.

**Comment by ms-zhenhua** [comment]
Hi @david-garcia-garcia,
`azurerm_virtual_machine_data_disk_attachment.example.virtual_machine_id` should be assigned a VM ID, but now it's set with a VMSS ID. You may create a `azurerm_linux_virtual_machine` resource and assign its ID to the  `azurerm_virtual_machine_data_disk_attachment`. You may also need to replace `azurerm_linux_virtual_machine_scale_set` with `azurerm_orchestrated_virtual_machine_scale_set`, the ID of which then can be assigned to `azurerm_linux_virtual_machine.example.virtual_machine_scale_set_id`

**Comment by tombuildsstuff** [comment]
@david-garcia-garcia FWIW this resource currently doesn't support being used when attached to a Virtual Machine connected to a Virtual Machine Scale Set since (IIRC) there's some behavioural differences about how updates need to work - and as such as this time that's expected.

Since there's differences between a Virtual Machine (standalone) and a Virtual Machine that's connected to a Virtual Machine Scale Set, we'd instead look to add this as a new resource, [which this issue is tracking](https://github.com/hashicorp/terraform-provider-azurerm/issues/14617) and as such I'm going to close this issue in favour of that one - would you mind subscribing to that issue for updates?

Thanks!
