### ISSUE TITLE
Dynamic block condition affecting how instances of a list of objects are sorted

### ISSUE THREAD

**Issue by elesandroo** [hashicorp/terraform-provider-azurerm#25583]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.96.0

### Affected Resource(s)/Data Source(s)

azurerm_lb, azurerm_private_endpoint,...

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.96.0"
    }
  }
  backend "local" {}
}

provider "azurerm" {
  skip_provider_registration = false
  features {}
}

locals {
  frontend_ip_configuration = [
    {
      name               = "stest"
      subnet_id          = azurerm_subnet.example.id
      private_ip_address = "10.0.2.9"
    },
    {
      name               = "atest"
      subnet_id          = azurerm_subnet.example.id
      private_ip_address = "10.0.2.33"
    },
    {
      name               = "utest"
      subnet_id          = azurerm_subnet.example.id
      private_ip_address = "10.0.2.30"
    }
  ]
}

resource "azurerm_resource_group" "example" {
  name     = "LoadBalancerRG"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "subnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.2.0/24"]
}

resource "azurerm_lb" "example" {
  name                = "TestLoadBalancer"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  dynamic "frontend_ip_configuration" {
    for_each = local.frontend_ip_configuration

    content {
      name               = frontend_ip_configuration.value.name
      subnet_id          = azurerm_subnet.example.id
      private_ip_address = frontend_ip_configuration.value.private_ip_address
    }
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_lb.example will be updated in-place
  ~ resource "azurerm_lb" "example" {
        id                   = "/subscriptions/c813f663-9930-455f-9450-d0acf61942d9/resourceGroups/LoadBalancerRG/providers/Microsoft.Network/loadBalancers/TestLoadBalancer"
        name                 = "TestLoadBalancer"
        tags                 = {}
        # (6 unchanged attributes hidden)

      ~ frontend_ip_configuration {
            id                            = "/subscriptions/c813f663-9930-455f-9450-d0acf61942d9/resourceGroups/LoadBalancerRG/providers/Microsoft.Network/loadBalancers/TestLoadBalancer/frontendIPConfigurations/stest"
            name                          = "stest"
          ~ private_ip_address            = "10.0.2.4" -> "10.0.2.9"
            # (7 unchanged attributes hidden)
        }
      ~ frontend_ip_configuration {
            id                            = "/subscriptions/c813f663-9930-455f-9450-d0acf61942d9/resourceGroups/LoadBalancerRG/providers/Microsoft.Network/loadBalancers/TestLoadBalancer/frontendIPConfigurations/atest"
            name                          = "atest"
          ~ private_ip_address            = "10.0.2.5" -> "10.0.2.33"
            # (7 unchanged attributes hidden)
        }
      ~ frontend_ip_configuration {
            id                            = "/subscriptions/c813f663-9930-455f-9450-d0acf61942d9/resourceGroups/LoadBalancerRG/providers/Microsoft.Network/loadBalancers/TestLoadBalancer/frontendIPConfigurations/utest"
            name                          = "utest"
          ~ private_ip_address            = "10.0.2.6" -> "10.0.2.30"
            # (7 unchanged attributes hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behaviour

We expect there will be no changes when running terraform plan on a configuration that has been applied and no changes were made. We've tried changing the dynamic block condition using `toset(local.frontend_ip_configuration)`, `tolist(local.frontend_ip_configuration)`, `{for a in local.frontend_ip_configuration : a.name => a }`, and many more options and they all have a scenario where this happens (by running terraform plan; when adding new instance to the end of the list or the middle of the list). We know that some functions change the order of the instances but we are unsuccessful in finding a way that will prevent this altogether.

### Actual Behaviour

Instances of the list of objects keeps reordering even after applying the new order.

### Steps to Reproduce

First:
1. terraform init
2. terraform apply
3. terraform plan

Trying to apply the new order:
  5. terraform apply
  6. terraform plan

**Comment by lonegunmanb** [comment]
Hi @elesandroo , thanks for reporting this issue to us. Have you tried setting `private_ip_address_allocation` to `Static` yet?:

```hcl
content {
      name               = frontend_ip_configuration.value.name
      subnet_id          = azurerm_subnet.example.id
      private_ip_address = frontend_ip_configuration.value.private_ip_address
      private_ip_address_allocation = "Static"
    }
```

**Comment by lonegunmanb** [comment]
A kindly ping @elesandroo , any progress on this issue?

**Comment by elesandroo** [comment]
Hey @lonegunmanb, thanks for your reply. I've realised I captured the error wrongly. However, I may have found a solution to my problem so we can close this issue. Thank you for your effort though, I appreciate it.

**Comment by lonegunmanb** [comment]
@elesandroo Glad to hear that you've solved your issue! I don't have permission to close this issue, would you please be so kind to close it? Otherwise it would be pending for a while until HashiCorp's issue cleaner close it. Thanks for your help!
