### ISSUE TITLE
Windows node pool deleted and recreated when AKS is upgraded from k8s 1.28.x to 1.29.2

### ISSUE THREAD

**Issue by JiandongRuan** [hashicorp/terraform-provider-azurerm#25625]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.7

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "bot" {
  name                  = "win"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks.id
  os_type               = "Windows"
  os_sku                = "Windows2019"

  vnet_subnet_id = var.aks.cluster_subnet_id

  node_count = 1
  vm_size    = "Standard_F16s_v2"
  max_pods   = 40

  enable_auto_scaling = false
}
```

### Debug Output/Panic Output

```shell
# module.dev_westus2_aks_ea.azurerm_kubernetes_cluster_node_pool.bot[0] must be replaced
-/+ resource "azurerm_kubernetes_cluster_node_pool" "bot" {
-       custom_ca_trust_enabled = false -> null
-       enable_host_encryption  = false -> null
-       enable_node_public_ip   = false -> null
-       fips_enabled            = false -> null
        ...
!       kubelet_disk_type       = "OS" -> (known after apply)
-       max_count               = 0 -> null
-       min_count               = 0 -> null
        name                    = "bot"
-       node_taints             = [] -> null
!       orchestrator_version    = "1.29.2" -> (known after apply)
!       os_disk_size_gb         = 128 -> (known after apply)

-       windows_profile { # forces replacement
-           outbound_nat_enabled = true -> null
        }
    }
```

### Expected Behaviour

1. There must be no change in `windows_profile.outbound_nat_enabled`
2. node pool must be deleted and created again.

### Actual Behaviour

Terraform plan think `windows_profile.outbound_nat_enabled` has changed and wants to delete and recreate the node pool.

### Steps to Reproduce

1. Create a version 1.28.3 AKS cluster that has a Windows node pool
2. upgrade the AKS cluster to 1.29.2 via terraform
3. go to Azure portal and upgrade each node pool to 1.29.2
4. `terrafrom plan` again and you will see

**Comment by birenshah2** [comment]
We are noticing the same thing going from cluster version 1.28.3 to 1.28.5 using provider version 3.99.0 (yesterday). We upgraded some clusters _last_ week (same aks from/to versions) but using provider version 3.98.0, and did _not_ see this happen.

**Comment by JiandongRuan** [comment]
Here are more details for my issue:
1. I upgraded AKS cluster from 1.28.3 to 1.29.2 **yesterday** using provider version 3.73.0
2. After seeing the issue, I upgraded the provider version to 3.99.0. But this didn't help

Perhaps provider version is not the root cause here. Maybe some change at Azure side between last week and yesterday is causing the issue?
