### ISSUE TITLE
Logic App: Add callback url as attribute of custom trigger

### ISSUE THREAD

**Issue by nickel-tyler** [hashicorp/terraform-provider-azurerm#25623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Please add the ability to make use of the callback url from the ListCallbackURL azure sdk api for a given **custom** trigger so that the logic app can be hooked up to other infrastructure.

My particular use case is i'm trying to use terraform to manage the creation of a logic app and a security center automation that should be configured to trigger that logic app. azurerm_security_center_automation requires action.trigger_url, even if using built in connectors for the logic app triggers. azurerm_logic_app_trigger_http_request could be used instead according to https://learn.microsoft.com/en-us/azure/defender-for-cloud/workflow-automation#data-types-schemas, but I think the built-in connectors should be supported with TF too.

### New or Affected Resource(s)/Data Source(s)

azurerm_logic_app_trigger_custom and/or azurerm_security_center_automation

### References

https://github.com/Azure/azure-sdk-for-go/blob/a45cf26fd136c65f9ca4f00405c5ccce7b3941e3/sdk/resourcemanager/logic/armlogic/workflows_client.go
https://github.com/hashicorp/terraform-provider-azurerm/issues/3724
https://learn.microsoft.com/en-us/azure/defender-for-cloud/workflow-automation#data-types-schemas

**Comment by nickel-tyler** [comment]
i am working on the changes

**Comment by vil2be** [comment]
@nickel-tyler @mybayern1974 any update on this? much appreciated :)

**Comment by nickel-tyler** [comment]
@vil2be I'll make a pr tomorrow
