### ISSUE TITLE
Changing azurerm_machine_learning_workspace.image_build_compute_name forces replacement of the workspace

### ISSUE THREAD

**Issue by zhusulai** [hashicorp/terraform-provider-azurerm#25622]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.11

### AzureRM Provider Version

2.93.1

### Affected Resource(s)/Data Source(s)

azurerm_machine_learning_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_machine_learning_workspace" "azml_workspace" {
  name     = "myworkspace"
  location = "eastus2"
  resource_group_name      = "myRG"
  key_vault_id             = azurerm_key_vault.azml_kv.id
  storage_account_id       = azurerm_storage_account.azml_st.id
  container_registry_id    = azurerm_container_registry.azml_acr.id
  high_business_impact     = true
  image_build_compute_name = "ACR-TASKS-FALLBACK"
  identity {
    type = "SystemAssigned"
  }
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

`image_build_compute_name` can be set by using Azure CLI without having to destroy and recreate the workspace. Terraform should patch the workspace and set the property based on the config provided.

### Actual Behaviour

Terraform tries to destroy and recreate the workspace. If the workspace has soft-delete enabled, the recreation will fail, resulting in missing workspaces.

Official documentation also do not mention changing the property will force a replacement. https://registry.terraform.io/providers/hashicorp/azurerm/2.93.1/docs/resources/machine_learning_workspace.html#image_build_compute_name

### Steps to Reproduce

change the `image_build_compute_name` property
run `terraform apply`

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. You have written that this issue is in the 2.x version of the provider which is no longer actively maintained.
Are you able to upgrade and let us know if this is occurs on the latest provider (3.99 as of writing this)?

**Comment by xuzhang3** [comment]
@zhusulai   the `image_build_compute_name` will not trigger a recreate operation, can you check the `terraform plan` which property triggers the recreation, the output log should show the details.

**Comment by amoresi1-mc** [comment]
@xuzhang3 ` - image_build_compute_name      = "ACR-TASKS-FALLBACK" -> null # forces replacement`

**Comment by xuzhang3** [comment]
@amoresi1-mc  The `ForceNew` in `image_build_compute_name` has been removed in the latest release. Are you able to upgrade AzureRM version?

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. The `ForceNew` in `image_build_compute_name` was removed so I am going to mark this issue as closed. Please upgrade to the latest version of the provider and if you are still having this issue let us know and we can reopen it. Thanks!
