### ISSUE TITLE
Terragrunt with module and resource azurerm_key_vault_secret wants to recreate the secret again after creation

### ISSUE THREAD

**Issue by AlexanderBurdenko** [hashicorp/terraform-provider-azurerm#25637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.7

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

 azurerm_key_vault_secret

### Terraform Configuration Files

```hcl
generate "provider" {
    path = "provider.tf"
    if_exists = "overwrite_terragrunt"

    contents = <<EOF
    provider "azurerm" {
      features {
        app_configuration {
        recover_soft_deleted = false
      }
    }
    subscription_id            = "${get_env("ARM_SUBSCRIPTION_ID")}"
    skip_provider_registration = true
    use_oidc = true
    }
  EOF
}
```

### Debug Output/Panic Output

```shell
A resource with the ID "" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_key_vault_secret" for more information.
```

### Expected Behaviour

Stop recreate secret

### Actual Behaviour

Trying to recreate resource

**Comment by AlexanderBurdenko** [comment]
FYI: It's a Terragrunt
with a modules

**Comment by lonegunmanb** [comment]
Hi @AlexanderBurdenko thanks for opening this issue to us, would you please share us a minimum example code with corresponding descriptions step by step to show us how to reproduce this issue? If we can reproduce the issue, or analyze your code, it would be a great help, thanks!

**Comment by AlexanderBurdenko** [comment]
> Hi @AlexanderBurdenko thanks for opening this issue to us, would you please share us a minimum example code with corresponding descriptions step by step to show us how to reproduce this issue? If we can reproduce the issue, or analyze your code, it would be a great help, thanks!

resource "azurerm_key_vault_secret" "name_secret_resource" {
  name         = "name_secret"
  value        = "https://url"
  key_vault_id = var.azure_secrets_key_vault_resource_id
}
First time when you ran terraform apply everything fine, second time it's trying to recreate it

I have checked that in tfstate file this resource store

But error i have provided

**Comment by lonegunmanb** [comment]
@AlexanderBurdenko Could you please share the terraform plan output that showed the recreation plan with us? More details we know about your config, the better we could understand your issue.

**Comment by AlexanderBurdenko** [comment]
> @AlexanderBurdenko Could you please share the terraform plan output that showed the recreation plan with us? More details we know about your config, the better we could understand your issue.

the output the same as that provided in similar issues that provided previously
  + resource "azurerm_key_vault_secret" "secret" {
      + id                      = (known after apply)
      + key_vault_id            = ""
      + name                    = "ad-application-client-secret"
      + resource_id             = (known after apply)
      + resource_versionless_id = (known after apply)
      + value                   = (sensitive value)
      + version                 = (known after apply)
      + versionless_id          = (known after apply)
    }

The problem is:
That you are using Terraform "data resource http" to get API TOKEN for Function App even it doesn't change value at all, but terraform think this is new value, and want to create NEW Secret or New Version of Secret

**Comment by lonegunmanb** [comment]
@AlexanderBurdenko you can check this document: [Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior):

>Terraform reads data resources during the planning phase when possible, but announces in the plan when it must defer reading resources until the apply phase to preserve the order of operations. 

Once your `data http xxx` depends on another resource block, it's value would be `Known after apply` during plan phase, and causes the same behavior you've seen.

If you can share the raw Terraform config code with us then we can try to reproduce the issue, or pinpoint the root cause. If the original code is sensitive then would you please share a minimum desensitized example code with us? Thanks!

**Comment by AlexanderBurdenko** [comment]
> @AlexanderBurdenko you can check out this document: [Data Resource Behavior](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior):
> 
> > Terraform reads data resources during the planning phase when possible, but announces in the plan when it must defer reading resources until the apply phase to preserve the order of operations.
> 
> Once your `data http xxx` depends on another resource block, it's value would be `Known after apply` during plan phase, and causes the same behavior you've seen. We also have a vlog to describe this behavior: [Data sources are evil!](https://www.youtube.com/watch?v=l8k_cOHep28)
> 
> If you can share the raw Terraform config code with us then we can try to reproduce the issue, or pinpoint the root cause. If the original code is sensitive then would you please share a minimum desensitized example code with us? Thanks!

Well
data "http" "function_key" {
  url = "https://${azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname}/admin/functions/${local.function_name}/keys/${local.function_key_name}?code=${data.azurerm_function_app_host_keys.default.primary_key}"

  request_headers = {
    Content-Type = "application/json"
  }
}
resource "azurerm_key_vault_secret" "name_secret_resource" {
name = "name_secret"
value = "https://url+code=parsedfrom_data_http/"
key_vault_id = var.azure_secrets_key_vault_resource_id
}

**Comment by lonegunmanb** [comment]
```hcl
data "http" "function_key" {
  url = "https://${azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname}/admin/functions/${local.function_name}/keys/${local.function_key_name}?code=${data.azurerm_function_app_host_keys.default.primary_key}"
```

I think the problem is, we've used `azurerm_linux_function_app` in `data.http.function_key`, according to the [document](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior):

>The data resource depends directly on a managed resource that itself has planned changes in the current plan.

This data's read would be deferred to apply phase, which makes it's attribute `Known after apply`, and that caused the recreation.

**Comment by AlexanderBurdenko** [comment]
> @AlexanderBurdenko
> 
> ```terraform
> data "http" "function_key" {
>   url = "https://${azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname}/admin/functions/${local.function_name}/keys/${local.function_key_name}?code=${data.azurerm_function_app_host_keys.default.primary_key}"
> ```
> 
> I think the problem is, we've used `azurerm_linux_function_app` in `data.http.function_key`, according to the [document](https://developer.hashicorp.com/terraform/language/data-sources#data-resource-behavior):
> 
> > The data resource depends directly on a managed resource that itself has planned changes in the current plan.
> 
> This data's read would be deferred to apply phase, which makes it's attribute `Known after apply`, and that caused the recreation. Meanwhile we should verify whether `local.function_name`, `local.function_key_name` and `data.azurerm_function_app_host_keys.default` depends on a managed resource directly or indirectly.

Let me provide what i have
locals {
  parsed_response   = jsondecode(data.http.function_key.response_body)
}
data "http" "function_key" {
  url = "https://${azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname}/admin/functions/${local.function_name}/keys/${local.function_key_name}?code=${data.azurerm_function_app_host_keys.default.primary_key}"

  request_headers = {
    Content-Type = "application/json"
  }
}

resource "azurerm_key_vault_secret" "name_secret_resource" {
name = "name_secret"
value = "https://url+code=${parsed_response}"
key_vault_id = var.azure_secrets_key_vault_resource_id
}

But interesting thing, that the Value is the same and there is no changes

There is no options to get function_key which inside function, not HOST KEY of Function app

Only can be taken by API or AZ CLI

**Comment by lonegunmanb** [comment]
Hi @AlexanderBurdenko , thanks for providing us more details. I assume your config is:

```hcl
locals {
  parsed_response = jsondecode(data.http.function_key.response_body)
}
data "http" "function_key" {
  url = "https://${azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname}/admin/functions/${local.function_name}/keys/${local.function_key_name}?code=${data.azurerm_function_app_host_keys.default.primary_key}"

  request_headers = {
    Content-Type = "application/json"
  }
}

resource "azurerm_key_vault_secret" "name_secret_resource" {
  name = "name_secret"
  value = "https://url+code=${local.parsed_response}/"
  key_vault_id = var.azure_secrets_key_vault_resource_id
}
```

The dependency relation is: `azurerm_key_vault_secret.name_secret_resource` -> `local.parsed_response` -> `data.http.function_key` -> `azurerm_linux_function_app.gh_webhook_event_handler_app`, so the `data.http.function_key`'s output became `Known after apply`. Now we need to know how you define `azurerm_linux_function_app.gh_webhook_event_handler_app`? Is that possible to replace `azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname` with a value that could be known during the plan phase? And we also need to ensure that `local.function_name` and `local.function_key_name` wouldn't depend on any managed resource.

I would suggest sharing the whole config via a gist, if it doesn't contain any sensitive data, or you can try to erase these sensitive data then share the config with us.

**Comment by AlexanderBurdenko** [comment]
> Hi @AlexanderBurdenko , thanks for providing us more details. I assume your config is:
> 
> ```terraform
> locals {
>   parsed_response = jsondecode(data.http.function_key.response_body)
> }
> data "http" "function_key" {
>   url = "https://${azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname}/admin/functions/${local.function_name}/keys/${local.function_key_name}?code=${data.azurerm_function_app_host_keys.default.primary_key}"
> 
>   request_headers = {
>     Content-Type = "application/json"
>   }
> }
> 
> resource "azurerm_key_vault_secret" "name_secret_resource" {
>   name = "name_secret"
>   value = "https://url+code=${local.parsed_response}/"
>   key_vault_id = var.azure_secrets_key_vault_resource_id
> }
> ```
> 
> The dependency relation is: `azurerm_key_vault_secret.name_secret_resource` -> `local.parsed_response` -> `data.http.function_key` -> `azurerm_linux_function_app.gh_webhook_event_handler_app`, so the `data.http.function_key`'s output became `Known after apply`. Now we need to know how you define `azurerm_linux_function_app.gh_webhook_event_handler_app`? Is that possible to replace `azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname` with a value that could be known during the plan phase? And we also need to ensure that `local.function_name` and `local.function_key_name` wouldn't depend on any managed resource.
> 
> I would suggest sharing the whole config via a gist, if it doesn't contain any sensitive data, or you can try to erase these sensitive data then share the config with us.

This is azurerm_linux_function_app.gh_webhook_event_handler_app.default_hostname takes from creation resource azurerm_linux_function_app
You can use static or this one Reference

local.function_name and local.function_key_name you can provide any you want it's name of function and function key wich inside function

**Comment by lonegunmanb** [comment]
Hi @AlexanderBurdenko thanks for the reply, but I cannot find the definition of your `azurerm_linux_function_app.gh_webhook_event_handler_app`.

Without the complete config I can only provide limited suggestion for you. I would suggest you try to remove any reference to managed resource in your data source, and try again.

**Comment by AlexanderBurdenko** [comment]
azurerm_linux_function_app it's a resource of Terraform, gh_webhook_event_handler_app it's name of resource

**Comment by AlexanderBurdenko** [comment]
@lonegunmanb Hello
Thank you, but i guess in future if this possible can you add to your provider azurerm a possibility get default_function_key of function I'm talking not function app host default key.
Similar az cli command
az functionapp function keys list -g MyResourceGroup -n MyFunctionAppName --function-name MyFunctionName

**Comment by lonegunmanb** [comment]
@AlexanderBurdenko interesting proposal, would you please open a new issue for this feature request and ping me there? Since I think this issue could be considered as solved, isn't it?
