### ISSUE TITLE
 azurerm_storage_blob - Parallelism and size force replacement

### ISSUE THREAD

**Issue by roy-work** [hashicorp/terraform-provider-azurerm#25658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

There is an existing issue of this, and the bug report is fine: #8392

Unfortunately, the OP there closed the issue, and a bot then subsequently locked it, but it wasn't fixed AFAICT.

One note on the discussion that had occurred. The following comment was made:

> Seems API wouldn't return the properties Parallelism, size and source after checked by [api doc](https://docs.microsoft.com/en-us/rest/api/storageservices/get-blob-properties#response-headers).

(The link is to _Azure's_ documentation.) The API _cannot_ return those two properties, as they're not properties of Azure, but rather of _Terraform_ (or specifically, of this provider). E.g., `parallelism` is the number of threads to upload with; ofc. the API isn't going to return that. `size` is a bit more complicated, but for non-page blobs, it'd be nice if importing worked? (and in my case, "size of the page blob" isn't a property, not really, since I'm not dealing with a page blob; this is sort of a limitation of the data representation TF is using. It seems like this defaults to `0` (the only permissible value?) but gets imported as `null`.)

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

2.91.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

See linked bug, too.

```hcl
resource "azurerm_storage_blob" "example" {
  name                   = "blob.json"
  storage_account_name   = azurerm_storage_account.example.name
  storage_container_name = azurerm_storage_container.example.name
  type                   = "Block"
  source_content = jsonencode({
    thing: "https://example.com",
    thing2: "https://example.com/more-stuff",
  })
}
```

Create the corresponding blob manually, or do it with TF & remove the state for it.

Then do `terraform import 'azurerm_storage_blob.example' 'https://bucket.blob.core.windows.net/container/blob.json'`

### Debug Output/Panic Output

```shell
(see linked)
```

### Expected Behaviour

A (within reason) `terraform import` should result in no changes.

### Actual Behaviour

`parallelism` & `size` force replacement:

```
  # azurerm_storage_blob.resource must be replaced
-/+ resource "azurerm_storage_blob" "resource" {
      ~ access_tier            = "Hot" -> (known after apply)
      ~ id                     = "https://bucket.blob.core.windows.net/container/blob.json" -> (known after apply)
      ~ metadata               = {} -> (known after apply)
        name                   = "blob.json"
      + parallelism            = 8 # forces replacement
      + size                   = 0 # forces replacement
      + source_content         = jsonencode(
            {
              + thing   = "https://example.com"
              + thing2 = "https://example.com/more-stuff"
            } # forces replacement
        )
      ~ url                    = "https://bucket.blob.core.windows.net/container/blob.json" -> (known after apply)
        # (4 unchanged attributes hidden)

      - timeouts {}
    }
```

### Steps to Reproduce

1. `terraform import ${a blob} …`
2. `terraform plan`

### Important Factoids

You can, if you know what you are doing, do the following:
1. `terraform state pull`
2. Find the resource in the state file; `parallelism` & `size` will be present, and incorrect. Adjust their values to match what your `.tf` file has, to remove the difference.
3. Bump the state file serial.
4. `terraform state push` 

But for obvious reasons, you must know what you're doing here, and be careful! (Backup your state file first.)

This doesn't alleviate the `source_content` delta, which is also forcing replacement. You _can_ also eliminate that using the same method as above: manually modify the state file to set `source_content`, if that applies to your case. (Here, it did, as that is how I'm getting the blob's content.) TF stores the literal content in the state file — i.e., the exact value that `source_content` computes to. So, in this example, I adjust `source_content` to the _result_ of that `jsonencode` call, and then there's no delta. You must be _precise_: JSON has a lot of `"`s, which must be escaped (`source_content` in the state file is a string, which is the type of the result of `jsonencode`), and you must get the spacing right (there is none, i.e., the JSON is compact) and you must get the order right (the same order plan shows seems to work, and I presume TF must be generating a canonical JSON somehow).

### References

#8392

**Comment by magodo** [comment]
@roy-work As you've already pointed out, these properties reside in TF only to control the behavior of the upload process for the blob resource. When running `terraform import`, it do a API `GET` under the hood, which won't get these properties for sure. Instead, if you want a full state after import, there need to re-implement the format of the import, e.g. be something like `terraform import azurerm_storage_blob.example 'https://bucket.blob.core.windows.net/container/blob.json;<parallelism>;<size>'. Since these properties aren't critical to the resource itself, you shall be safe to do a follow up apply to just update their value in the state.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
