### ISSUE TITLE
"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace.","MessageTemplate":"An error occurred when picking stamp for Web space {0}.","Parameters":["XXXXX-NorthEuropewebspace"]}}]

### ISSUE THREAD

**Issue by rajece1989** [hashicorp/terraform-provider-azurerm#25669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.95.0

### Affected Resource(s)/Data Source(s)

azurerm_app_service_certificate

### Terraform Configuration Files

```hcl
Suddenly we started getting this below error when we try to replace the app service certificate

web.CertificatesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace." Details=[{"Message":"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"53004","Message":"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace.","MessageTemplate":"An error occurred when picking stamp for Web space {0}.","Parameters":["XXXXX-NorthEuropewebspace"]}}]
```

### Debug Output/Panic Output

```shell
web.CertificatesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace." Details=[{"Message":"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"53004","Message":"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace.","MessageTemplate":"An error occurred when picking stamp for Web space {0}.","Parameters":["XXXXX-NorthEuropewebspace"]}}]
```

### Expected Behaviour

Should be successful. 

Same azurerm version 3.88.0 , 3.95.0 it is working fine till yesterday

### Actual Behaviour

Should be successful. 

Same azurerm version 3.88.0 , 3.95.0 it is working fine till yesterday

### Steps to Reproduce

web.CertificatesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace." Details=[{"Message":"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"53004","Message":"An error occurred when picking stamp for Web space XXXXX-NorthEuropewebspace.","MessageTemplate":"An error occurred when picking stamp for Web space {0}.","Parameters":["XXXXX-NorthEuropewebspace"]}}]

**Comment by rajece1989** [comment]
<img width="218" alt="image (2)" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/46596339/30fb05ed-191b-42ca-b6c1-816fa52a152f">
<img width="504" alt="image (1)" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/46596339/387aad7b-48d5-488c-9750-6e3eb428da22">

Microsoft team mentioned that actual worspace should ha -Linux' which is missing when we try to deploy.

**Comment by rajece1989** [comment]
XXXXX-NorthEuropewebspace is the webspace that terraform is erroring to. When we discussed with Microsoft they let us know that the call was to XXXXX-NorthEuropewebspace webspace but the actual webspace was XXXXX-NorthEuropewebspace-XXXX. It seems terraform/AzureRM are somehow truncating or failing to pull the full webspace name and as a result the code fails when it attemtps to use the webspace to look for the stamp. 
 
This import and binding works both through Azure Portal and from Azure CLI.

**Comment by xiaxyi** [comment]
Thanks @rajece1989 for raising this issue, may i know which operation were you trying to do and can you share the full tf config with me?

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s) and the operation you were trying to do. We are going to close this issue - if you would like to [open a new issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/new/choose) please make sure that you fill out all the requested information so that we can try to reproduce the problem, or comment here and we can reopen this issue, thanks!
