### ISSUE TITLE
I am able to take RDP to azure vm without creating security group 

### ISSUE THREAD

**Issue by ajayrawat111** [hashicorp/terraform-provider-azurerm#25668]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.98.0

### Affected Resource(s)/Data Source(s)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine

### Terraform Configuration Files

```hcl
# 2 Resource create virtual network 
resource "azurerm_virtual_network" "tf-vnet" {
  name                = "Terraform-vnet"
  location            = azurerm_resource_group.tf-rg.location
  resource_group_name = azurerm_resource_group.tf-rg.name
  address_space       = ["10.0.0.0/16"]
}

# 3  resource create subnet

resource "azurerm_subnet" "tf-subnet" {
  name                 = "vmsubnet"
  virtual_network_name = azurerm_virtual_network.tf-vnet.name
  resource_group_name  = azurerm_resource_group.tf-rg.name
  address_prefixes     = ["10.0.0.0/24"]

}

# 4  resource create public ip

resource "azurerm_public_ip" "tf-pip" {
  name                = "vm-pip"
  allocation_method   = "Static"
  location            = azurerm_resource_group.tf-rg.location
  resource_group_name = azurerm_resource_group.tf-rg.name


}


# 5 resource create network interface

resource "azurerm_network_interface" "tf-nic" {
  name                = "Terraform-nic"
  location            = azurerm_resource_group.tf-rg.location
  resource_group_name = azurerm_resource_group.tf-rg.name

 

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.tf-subnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.tf-pip.id
  }


}

# 6 resource create vm

resource "azurerm_windows_virtual_machine" "tf-windows" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.tf-rg.name
  location            = azurerm_resource_group.tf-rg.location
  size                = "Standard_B2s"
  admin_username      = "ajay"
  admin_password      = "Azure@9716125339"
  network_interface_ids = [
    azurerm_network_interface.tf-nic.id,
  ]

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }
}
```

### Debug Output/Panic Output

```shell
na
```

### Expected Behaviour

it should not allow to login to vm using rdp 

### Actual Behaviour

i am able to login to machine with port enable

**Comment by tombuildsstuff** [comment]
hi @ajayrawat111 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
