### ISSUE TITLE
Error azurerm_monitor_diagnostic_setting produced an unexpected new value: Root resource was present, but now absent for trafficmanager and frontdoor

### ISSUE THREAD

**Issue by raghavendra3553** [hashicorp/terraform-provider-azurerm#25676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.85.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting

### Terraform Configuration Files

```hcl
#
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.85.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.46.0"
    }
  }

  required_version = ">=0.14.9"

  backend "azurerm" {
  }
}

resource "azurerm_monitor_diagnostic_setting" "fdazurediagnostics" {
  count                      = length(var.loganalyticsworkspaceid) > 0 ? 1 : 0

  name                       = format("%s-analytics", var.name)
  target_resource_id         = var.targetresourceid
  log_analytics_workspace_id = var.loganalyticsworkspaceid

  enabled_log {
    category_group = "AllLogs"
    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"
    enabled  = true
    retention_policy {
      enabled = false
    }
  }
  lifecycle {
    ignore_changes = [log, metric, log_analytics_destination_type]
  }
}

resource "azurerm_monitor_diagnostic_setting" "fdazurediagnosticssecurity" {
  count                          = length(var.securityeventhubauthorizationruleid) > 0 ? 1 : 0

  name                           = format("%s-securitylogs", var.name)
  target_resource_id             = var.targetresourceid
  eventhub_name                  = var.securityeventhubname
  eventhub_authorization_rule_id = var.securityeventhubauthorizationruleid

  enabled_log {
    category = "FrontDoorAccessLog"
    retention_policy {
      enabled = false
    }
  }

  lifecycle {
    ignore_changes = [log, metric, log_analytics_destination_type]
  }
}

variables.tf
============================

variable "loganalyticsworkspaceid" {
  type        = string
  description = "Name of Log Analytics workspace. Pass empty string to omit for development purposes"
}

variable "securityeventhubname" {
  type        = string
  description = "Name of Security Event Hub Name. Pass empty string to omit for development purposes"
}

variable "securityeventhubauthorizationruleid" {
  type        = string
  description = "ID of Security Event Hub Auth Rule.  Pass empty string to omit for development purposes"
}


variable "name" {
  type        = string
  description = "Front Door Name"
}

variable "targetresourceid" {
  type = string
}
```

### Debug Output/Panic Output

```shell
Error: Provider produced inconsistent result after apply
2024-04-18T09:16:18.5269378Z     stdout: 
2024-04-18T09:16:18.5269501Z     stdout: When applying changes to
2024-04-18T09:16:18.5269987Z     stdout: module.frontdoor["s00803NFD999991sltfm090728dev"].module.fdazurediagnostics[0].azurerm_monitor_diagnostic_setting.fdazurediagnostics[0],
2024-04-18T09:16:18.5270279Z     stdout: provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an
2024-04-18T09:16:18.5270491Z     stdout: unexpected new value: Root resource was present, but now absent.
2024-04-18T09:16:18.5270841Z     stdout: 
2024-04-18T09:16:18.5271133Z     stdout: This is a bug in the provider, which should be reported in the provider's own
2024-04-18T09:16:18.5816873Z     stdout: issue tracker.
2024-04-18T09:16:18.5817224Z     exit: 1
2024-04-18T09:16:18.5817296Z
```

### Expected Behaviour

Terraform should exit with code 0, the following resources should be created in Azure and placed inside the terraform state.

### Actual Behaviour

 Error: Provider produced inconsistent result after apply
2024-04-18T09:16:18.5269378Z     stdout: 
2024-04-18T09:16:18.5269501Z     stdout: When applying changes to
2024-04-18T09:16:18.5269987Z     stdout: module.frontdoor["s00803NFD999991sltfm090728dev"].module.fdazurediagnostics[0].azurerm_monitor_diagnostic_setting.fdazurediagnostics[0],
2024-04-18T09:16:18.5270279Z     stdout: provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an
2024-04-18T09:16:18.5270491Z     stdout: unexpected new value: Root resource was present, but now absent.
2024-04-18T09:16:18.5270841Z     stdout: 
2024-04-18T09:16:18.5271133Z     stdout: This is a bug in the provider, which should be reported in the provider's own
2024-04-18T09:16:18.5816873Z     stdout: issue tracker.
2024-04-18T09:16:18.5817224Z     exit: 1
2024-04-18T09:16:18.5817296Z 

### Steps to Reproduce

terraform plan and apply. We are seeing consistently this issue to trafficmanager and frontdoor, azure side it is created successfully

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25697 created by @teowa for this issue.

**Comment by raghavendra3553** [comment]
Thanks for quick fix and we need to know when this fix will be available because this fix is really important for our product. Is there any can we prioritize the fix to megre.

**Comment by teowa** [comment]
Hi @raghavendra3553 , I am not sure if it is unstable API or other factor, I cannot repro the `Root resource was present, but now absent.` error for diagnostic setting in my local now. Can you or anyone help provide Terraform [debug logs](https://developer.hashicorp.com/terraform/internals/debugging) with HTTP logs about PUT diagnostic setting and GET diagnostic setting (I guess it should be 404 returned for the GET after PUT), so I can submit the issue to REST API as suggested in https://github.com/hashicorp/terraform-provider-azurerm/pull/25697#pullrequestreview-2022324459 and push this forward.
