### ISSUE TITLE
"Diagnostic Settings Error:  Resource Already Exists..." for greenfield deployment.

### ISSUE THREAD

**Issue by sgmtg-jcustance** [hashicorp/terraform-provider-azurerm#25673]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.4

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_diagnostic_setting "storage_account"

### Terraform Configuration Files

```hcl
# Enable Diagnostic Settings for Storage account
resource "azurerm_monitor_diagnostic_setting" "storage_account" {
  for_each = var.diagnostic_settings_storage_account == null ? {} : var.diagnostic_settings_storage_account

  name                       = each.value.name
  target_resource_id         = azurerm_storage_account.this.id
  log_analytics_workspace_id = each.value.log_analytics_workspace_id

  dynamic "metric" {
    for_each = each.value.metric_categories
    content {
      category = metric.value
    }
  }
}
```

### Debug Output/Panic Output

```shell
'Diagnostic Settngs'
Error: A resource with the ID "/subscriptions/***/resourceGroups/xxxxxx-eu2-dev-rg-01/providers/Microsoft.Storage/storageAccounts/xxxxxxxxst01/blobServices/default/|diagnostics-blob" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
```

### Expected Behaviour

No error:  

### Actual Behaviour

Diagnostic setting is created by terraform but terraform doesn't 'remember' it already created it.

### Steps to Reproduce

GREENFIELD:  THIS DOES NOT HAPPEN 100% of the time

Using Azure Verified Module for Storage Account:
Create storage account with diagnostic settings enabled.
Storage Account Is Created (NEVER EXISTED)
Diagnostic Settings Created (NEVER EXISTED, since store account never existed)
Terraform throws error resource already exists.

Manually delete the diagnostic settings from the storage account using azure portal,
Rerun the terraform apply, and settings are created, no complaint of existing resources.  TF state updated as it should.

### Important Factoids

None

**Comment by teowa** [comment]
Hi @sgmtg-jcustance , could you please check if this is related to https://github.com/hashicorp/terraform-provider-azurerm/issues/19706#issuecomment-1354466607 and https://github.com/hashicorp/terraform-provider-azurerm/issues/11076#issuecomment-963092635. 

> when you delete an Azure resource in the Azure portal or through command, the associated diagnostic setting resource will not be deleted together with this Azure resource. Next time when you use terraform to re-create the same Azure resource, this diagnostic setting resource will still be associated with this Azure resource automatically.

Thanks.

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. I am going to close this with @teowa's response with linked comments above as an answer. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
