### ISSUE TITLE
Azure event grid subscription fails before manual validation

### ISSUE THREAD

**Issue by chatlabashev** [hashicorp/terraform-provider-azurerm#25689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.4

### AzureRM Provider Version

3.100.0

### Affected Resource(s)/Data Source(s)

azurerm_eventgrid_event_subscription

### Terraform Configuration Files

```hcl
resource "azurerm_maintenance_configuration" "maintenance_config" {
  name                     = "test-maintenance-config"
  resource_group_name      = "rg-patching-shared-eun"
  location                 = "northeurope"
  scope                    = "InGuestPatch"
  properties               = {}
  in_guest_user_patch_mode = "User"
  window {
    start_date_time = "2024-04-20 09:40"
    duration        = "02:00"
    time_zone       = "UTC"
    recur_every     = "Week Sunday"
  }
  install_patches {
    linux {
      classifications_to_include    = ["Critical", "Security"]
      package_names_mask_to_exclude = []
      package_names_mask_to_include = []
    }
    windows {
      classifications_to_include = ["Critical", "Security"]
      kb_numbers_to_exclude      = []
      kb_numbers_to_include      = []
    }
    reboot = "IfRequired"
  }
}

resource "azurerm_eventgrid_event_subscription" "eventgrid_event_pre_subscription" {
  scope                = azurerm_maintenance_configuration.maintenance_config.id
  name                 = "${azurerm_maintenance_configuration.maintenance_config.name}-pre"
  included_event_types = ["Microsoft.Maintenance.PreMaintenanceEvent"]
  webhook_endpoint {
    url                               = "https://eoacqvca9pmb9ks.m.pipedream.net"
    max_events_per_batch              = 1
    preferred_batch_size_in_kilobytes = 64
  }
  labels = []
  retry_policy {
    event_time_to_live    = 1440
    max_delivery_attempts = 3
  }
}
```

### Debug Output/Panic Output

```shell
Error:
2024-04-19T17:35:12.087+0300 [ERROR] provider.terraform-provider-azurerm_v3.100.0_x5.exe: Response contains error diagnostic: diagnostic_detail="" tf_req_id=ef5ed2a8-39b4-ce32-0fbe-85130f20442f @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto
  diagnostic_summary=
  | creating/updating Scoped Event Subscription (Scope: "/subscriptions/819b6709-3da5-457e-aa6d-e6cebf9e0f89/resourceGroups/rg-patching-shared-eun/providers/Microsoft.Maintenance/maintenanceConfigurations/test-maintenance-config"
  | Event Subscription Name: "test-maintenance-config-pre"): polling after CreateOrUpdate: `result.Status` was nil/empty - `op.Status` was "AwaitingManualAction" / `op.Properties.ProvisioningState` was ""
   tf_provider_addr=provider tf_resource_type=azurerm_eventgrid_event_subscription diagnostic_severity=ERROR tf_proto_version=5.4 tf_rpc=ApplyResourceChange timestamp="2024-04-19T17:35:12.087+0300"
2024-04-19T17:35:12.087+0300 [TRACE] provider.terraform-provider-azurerm_v3.100.0_x5.exe: Served request: tf_provider_addr=provider @module=sdk.proto tf_proto_version=5.4 tf_req_id=ef5ed2a8-39b4-ce32-0fbe-85130f20442f tf_resource_type=azurerm_eventgrid_event_subscription tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:872 timestamp="2024-04-19T17:35:12.087+0300"


Full debug output:
https://gist.github.com/chatlabashev/2875294c0836852939ec9b7ea37995a9
```

### Expected Behaviour

The default timeout for external event subscription Webhook validation is 10 minutes by default 
https://learn.microsoft.com/en-us/azure/event-grid/webhook-event-delivery#endpoint-validation-with-event-grid-events

The azurerm behavior until recently was that it will wait for 10 minutes for the webhook to be validated and only then fail

### Actual Behaviour

However Terraform apply is failing after 1 minute with:

 polling after CreateOrUpdate: `result.Status` was nil/empty - `op.Status` was "AwaitingManualAction" / `op.Properties.ProvisioningState` was ""

### Steps to Reproduce

1. terraform apply
2. Not validate webhook within 1 minute

**Comment by xiaxyi** [comment]
Thanks @chatlabashev for raising this issue, can you try adding the event grid subscription after the Maintenance Configuration
is fully provisioned?

**Comment by chatlabashev** [comment]
Hello @xiaxyi  Sorry for the delayed answer. Provisioning the Event Grid subscription fails with the same error even if the maintenance config was provisioned already. I also tried with the version  v3.107.0 of the provider. 
` Event Subscription Name: "test-maintenance-config-pre"): polling after CreateOrUpdate: `result.Status` was nil/empty - `op.Status` was "AwaitingManualAction" / `op.Properties.ProvisioningState` was ""`

**Comment by chatlabashev** [comment]
Actually when using version "3.50.0" of the provider the manual validation works as it is supposed to do and waits for 10 minutes for a manual validation. I was able to get the validation link from the request and validate manually after 8 minutes. It seems only the newer versions of the provider have the problem

> azurerm_maintenance_configuration.maintenance_config: Creating...
> azurerm_maintenance_configuration.maintenance_config: Still creating... [10s elapsed]
> azurerm_maintenance_configuration.maintenance_config: Creation complete after 13s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-patching-shared-eun/providers/Microsoft.Maintenance/maintenanceConfigurations/test-maintenance-config]
> azurerm_eventgrid_event_subscription.eventgrid_event_pre_subscription: Creating...
> azurerm_eventgrid_event_subscription.eventgrid_event_pre_subscription: Still creating... [10s elapsed]
> .
> .
> .
> azurerm_eventgrid_event_subscription.eventgrid_event_pre_subscription: Still creating... [8m40s elapsed]
> azurerm_eventgrid_event_subscription.eventgrid_event_pre_subscription: Still creating... [8m50s elapsed]
> azurerm_eventgrid_event_subscription.eventgrid_event_pre_subscription: Creation complete after 8m51s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/rg-patching-shared-eun/providers/Microsoft.Maintenance/maintenanceConfigurations/test-maintenance-config/providers/Microsoft.EventGrid/eventSubscriptions/test-maintenance-config-pre]

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue and the linked PR! Since the [PR](https://github.com/hashicorp/go-azure-sdk/pull/1051) has been merged, I am going to mark this issue as closed. If that's not the case, please reach out and we can reopen.
