### ISSUE TITLE
Terraform: Non-idempotent Behavior with SMTP Settings in Azure Managed Grafana

### ISSUE THREAD

**Issue by sureshkothapalli1982** [hashicorp/terraform-provider-azurerm#25721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

When attempting to update an existing managed Grafana resource that already contains SMTP changes using Terraform in Azure, I encountered the following error:

╷
│ Error: updating Grafana (Subscription: "******"
│ Resource Group Name: "******"
│ Grafana Name: "******"): performing GrafanaCreate: unexpected status 400 (400 Bad Request) with error: InvalidConfigurationForSMTP: SMTP configuration is incomplete with missing fields; Please refer to https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp
│ 
│   with module.grafana.azurerm_dashboard_grafana.grafana,
│   on ../managed-grafana/main.tf line 7, in resource "azurerm_dashboard_grafana" "grafana":
│    7: resource "azurerm_dashboard_grafana" "grafana" {
│ 
│ updating Grafana (Subscription: "b6689fdb-ac8c-4116-8136-c7a179cb5be6"
│ Resource Group Name: "******"
│ Grafana Name: "******"): performing GrafanaCreate:
│ unexpected status 400 (400 Bad Request) with error:
│ InvalidConfigurationForSMTP: SMTP configuration is incomplete with missing
│ fields; Please refer to
│ https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp
╵
time=2024-04-23T07:51:35Z level=error msg=terraform invocation failed in /vsts/agent/_work/_temp/gwj5LbmiAR8uR_2Jt4aS_DrT4BI/XGnQSqjdCiH80WepM5lWGD_VrRk/managed-grafana-stack prefix=[/vsts/agent/_work/1/s/src/stacks/managed-grafana/westeurope/prod-nlpapp0772] 
time=2024-04-23T07:51:35Z level=error msg=1 error occurred:
	* [/vsts/agent/_work/_temp/gwj5LbmiAR8uR_2Jt4aS_DrT4BI/XGnQSqjdCiH80WepM5lWGD_VrRk/managed-grafana-stack] exit status 1

Example terraform configuration:

## Terraform Configuration
Here is the relevant section of my Terraform configuration:

```hcl
resource "azurerm_dashboard_grafana" "grafana" {
  name                              = local.grafana_name
  resource_group_name               = local.resource_group_name
  location                          = var.location
  api_key_enabled                   = true
  deterministic_outbound_ip_enabled = false
  public_network_access_enabled     = true
  sku                               = var.grafana_sku
  grafana_major_version             = var.grafana_version

  azure_monitor_workspace_integrations {
    resource_id = var.prometheus_resource_id
  }

  smtp {
    enabled                   = var.grafana_smtp_enabled
    host                      = var.grafana_smtp_host
    user                      = var.grafana_smtp_user
    password                  = var.password
    start_tls_policy          = var.grafana_smtp_tls_policy
    from_address              = var.grafana_from_address
    from_name                 = var.grafana_from_name
    verification_skip_enabled = true
  }

  identity {
    type = "SystemAssigned"
  }

  tags = var.tags
}


Reproduction Steps:

1. Created an Azure managed instance using Terraform commands with the provided Terraform Azure managed Grafana configuration.
2. Attempted to run the same commands again for the second time, but failed with the error mentioned above.

Expected Behavior: It should not throw this error message.
Actual Behavior: It threw the error message as described.
Additional Context:

terraform {
  # Avoid major version updates
  required_version = ">= 1.3, < 2.0.0"

  required_providers {
    azurerm = {
      source  = "azurerm"
      version = "~> 3.97.1"
    }
  }
}


### Terraform Version

1.3

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azure managed grafana instance

### Terraform Configuration Files

```hcl
resource "azurerm_dashboard_grafana" "grafana" {
  name                              = local.grafana_name
  resource_group_name               = local.resource_group_name
  location                          = var.location
  api_key_enabled                   = true
  deterministic_outbound_ip_enabled = false
  public_network_access_enabled     = true
  sku                               = var.grafana_sku
  grafana_major_version             = var.grafana_version

  azure_monitor_workspace_integrations {
    resource_id = var.prometheus_resource_id
  }

  smtp {
    enabled                   = var.grafana_smtp_enabled
    host                      = var.grafana_smtp_host
    user                      = var.grafana_smtp_user
    password                  = var.password
    start_tls_policy          = var.grafana_smtp_tls_policy
    from_address              = var.grafana_from_address
    from_name                 = var.grafana_from_name
    verification_skip_enabled = true
  }

  identity {
    type = "SystemAssigned"
  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: updating Grafana (Subscription: "b6689fdb-ac8c-4116-8136-c7a179cb5be6"
│ Resource Group Name: "*****************"
│ Grafana Name: "*****************"): performing GrafanaCreate: unexpected status 400 (400 Bad Request) with error: InvalidConfigurationForSMTP: SMTP configuration is incomplete with missing fields; Please refer to https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp
│ 
│   with module.grafana.azurerm_dashboard_grafana.grafana,
│   on ../managed-grafana/main.tf line 7, in resource "azurerm_dashboard_grafana" "grafana":
│    7: resource "azurerm_dashboard_grafana" "grafana" {
│ 
│ updating Grafana (Subscription: "b6689fdb-ac8c-4116-8136-c7a179cb5be6"
│ Resource Group Name: "*****************"
│ Grafana Name: "*****************"): performing GrafanaCreate:
│ unexpected status 400 (400 Bad Request) with error:
│ InvalidConfigurationForSMTP: SMTP configuration is incomplete with missing
│ fields; Please refer to
│ https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp
╵
time=2024-04-23T07:51:35Z level=error msg=terraform invocation failed in /vsts/agent/_work/_temp/gwj5LbmiAR8uR_2Jt4aS_DrT4BI/XGnQSqjdCiH80WepM5lWGD_VrRk/managed-grafana-stack prefix=[/vsts/agent/_work/1/s/src/stacks/managed-grafana/westeurope/prod-nlpapp0772] 
time=2024-04-23T07:51:35Z level=error msg=1 error occurred:
	* [/vsts/agent/_work/_temp/gwj5LbmiAR8uR_2Jt4aS_DrT4BI/XGnQSqjdCiH80WepM5lWGD_VrRk/managed-grafana-stack] exit status 1
```

### Expected Behaviour

When attempting to update an existing managed Grafana resource that already contains SMTP changes using Terraform in Azure, I should not get the error

### Actual Behaviour

When attempting to update an existing managed Grafana resource that already contains SMTP changes using Terraform in Azure, I got below error

 Error: updating Grafana (Subscription: "b6689fdb-ac8c-4116-8136-c7a179cb5be6"
│ Resource Group Name: "*****************"
│ Grafana Name: "*****************"): performing GrafanaCreate: unexpected status 400 (400 Bad Request) with error: InvalidConfigurationForSMTP: SMTP configuration is incomplete with missing fields; Please refer to https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp
│ 
│   with module.grafana.azurerm_dashboard_grafana.grafana,
│   on ../managed-grafana/main.tf line 7, in resource "azurerm_dashboard_grafana" "grafana":
│    7: resource "azurerm_dashboard_grafana" "grafana" {
│ 
│ updating Grafana (Subscription: "b6689fdb-ac8c-4116-8136-c7a179cb5be6"
│ Resource Group Name: "*****************"
│ Grafana Name: "*****************"): performing GrafanaCreate:
│ unexpected status 400 (400 Bad Request) with error:
│ InvalidConfigurationForSMTP: SMTP configuration is incomplete with missing
│ fields; Please refer to
│ https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#smtp
╵
time=2024-04-23T07:51:35Z level=error msg=terraform invocation failed in /vsts/agent/_work/_temp/gwj5LbmiAR8uR_2Jt4aS_DrT4BI/XGnQSqjdCiH80WepM5lWGD_VrRk/managed-grafana-stack prefix=[/vsts/agent/_work/1/s/src/stacks/managed-grafana/westeurope/prod-nlpapp0772] 
time=2024-04-23T07:51:35Z level=error msg=1 error occurred:
	* [/vsts/agent/_work/_temp/gwj5LbmiAR8uR_2Jt4aS_DrT4BI/XGnQSqjdCiH80WepM5lWGD_VrRk/managed-grafana-stack] exit status 1

### Steps to Reproduce

1. Create an Azure managed instance using Terraform commands  with the provided Terraform Azure managed Grafana configuration.
2. Attempt to run the same commands again for the second time, but failed with the error.

**Comment by nestpana** [comment]
experiencing the same behavior

**Comment by mwiktorin-andrena** [comment]
We still have the same problem with version v3.111.0. Our workaround is currently to remove the smpt config, apply the change, and the add the smtp config again. @sureshkothapalli1982 did the change fix the issue for you?
