### ISSUE TITLE
Azure Keyvault (azurerm_key_vault) creation error context deadline exceeded

### ISSUE THREAD

**Issue by Mighty2Mike** [hashicorp/terraform-provider-azurerm#25722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.0

### AzureRM Provider Version

3.100.0

### Affected Resource(s)/Data Source(s)

azurerm_key_vault

### Terraform Configuration Files

```hcl
resource "azurerm_key_vault" "kv" {
  name                = var.kv_name
  location            = var.location
  resource_group_name = var.rg_name
  tenant_id           = data.azurerm_client_config.current.tenant_id
  sku_name            = "standard"
  tags = var.tags

  access_policy {
    tenant_id = data.azurerm_client_config.current.tenant_id
    object_id = data.azurerm_client_config.current.object_id

    key_permissions = [
      "Create",
      "Get",
      "List",
      "Update",
      "Import",
      "Delete",
      "Recover",
      "Backup",
      "Restore"
    ]

    secret_permissions = [
      "Set",
      "Get",
      "Delete",
      "Purge",
      "Recover",
      "List",
      "Backup",
      "Restore"
    ]

    certificate_permissions = [
      "Create",
      "Get",
      "Delete",
      "Purge",
      "Recover",
      "List",
      "Backup",
      "Restore",
      "Import",
      "Update",
      "GetIssuers",
      "SetIssuers"
    ]
  }

  network_acls{
    default_action = "Deny"
    bypass = "AzureServices"
  }  
}
```

### Debug Output/Panic Output

```shell
Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded
│ 
│   with azurerm_key_vault.kv,
│   on main.tf line 15, in resource "azurerm_key_vault" "kv":
│   15: resource "azurerm_key_vault" "kv" {
│
```

### Expected Behaviour

Terraform apply should successfully create Keyvault and continue with remaining steps of provisioning of other terraform resources

### Actual Behaviour

Key vault is provisioned and terraform apply command runs for more than 7 minutes then crashes with:
Error: retrieving `contact` for KeyVault: keyvault.BaseClient#GetCertificateContacts: Failure sending request: StatusCode=0 -- Original Error: context deadline exceeded

**Comment by magodo** [comment]
@Mighty2Mike This is a data plane endpoint, which timeout due to DNS resolve error (and it retries several times that exceeds the 5min timeout). The reason for the DNS resolve failure is probably because you are recreating this key vault with the same name.

Note that in the upcoming v4 of this provider, the contact property will be removed from the `azurerm_key_vault`, which makes this resource purely management plane only. Also in current version (with https://github.com/hashicorp/terraform-provider-azurerm/pull/25552), this contact property is only read when `public_network_access_enabled` is `true`.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
