### ISSUE TITLE
azurerm_network_connection_monitor is missing "AzureArcVM" type for destination target resource type

### ISSUE THREAD

**Issue by hewitt-brown** [hashicorp/terraform-provider-azurerm#25737]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.0

### AzureRM Provider Version

3.99.0

### Affected Resource(s)/Data Source(s)

azurerm_network_connection_monitor

### Terraform Configuration Files

```hcl
resource "azurerm_network_connection_monitor" "arcconnection" {
  name               = "azureTest_to_arcVm"
  network_watcher_id = data.azurerm_network_watcher.eastus2.id
  location           = data.azurerm_network_watcher.eastus2.location
  tags               = var.tags

  endpoint {
    name                 = "sourceName"
    target_resource_id   = data.azurerm_virtual_machine.testvm.id
    address              = data.azurerm_virtual_machine.testvm.private_ip_address
    target_resource_type = "AzureVM"
  }

  endpoint {
    name                 = "destinationName"
    address              = "private_ip_here"
    target_resource_type = "ExternalAddress" -> Would need "AzureArcVM"
  }

  test_configuration {
    name                      = "IcmpConnection"
    protocol                  = "Icmp"
    test_frequency_in_seconds = 60

    icmp_configuration {
      trace_route_enabled     = true
    }
  }

  test_group {
    name                     = "sourceName_to_destinationName"
    destination_endpoints    = ["destinationName"]
    source_endpoints         = ["sourceName"]
    test_configuration_names = ["IcmpConnection"]
  }

  notes = "Put notes here"

  output_workspace_resource_ids = [data.azurerm_log_analytics_workspace.workspace.id]
}
```

### Debug Output/Panic Output

```shell
│ Error: expected endpoint.0.target_resource_type to be one of ["AzureSubnet" "AzureVM" "AzureVNet" 
  "ExternalAddress" "MMAWorkspaceMachine" "MMAWorkspaceNetwork"], got AzureArcVM
│
│   with azurerm_network_connection_monitor.azurearcconnection,
│   on 03-azure.tf line 97, in resource "azurerm_network_connection_monitor" "azurearcconnection":
│   97: resource "azurerm_network_connection_monitor" "azurearcconnection" {
```

### Expected Behaviour

Connection Monitor should be deployed with the correct target resource type.

### Actual Behaviour

![arc-vm](https://github.com/hashicorp/terraform-provider-azurerm/assets/56040850/1a1bf869-fee2-4359-858f-b45262448aaa)

### Steps to Reproduce

1. Create a Connection Monitor in the GUI and have the target destination point to an Azure Arc enabled VM. 
2. Download the JSON export for the gui created resource.  I used aztfexport to see this but the json export also shows it. 
3. In the export we will see that the destination address is pointing to the Arc Enabled machine and has a resource_target_type of "AzureArcVM"
4. Attempt to add a network connection monitor of type "azureArcVM" with Terraform
5. Errors stating: "Error: expected endpoint.0.target_resource_type to be one of ["AzureSubnet" "AzureVM" "AzureVNet" "ExternalAddress" "MMAWorkspaceMachine" "MMAWorkspaceNetwork"], got AzureArcVM".  

### Important Factoids

n/a

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25745 created by @neil-yechenwei for this issue.
