### ISSUE TITLE
azurerm_redhat_openshift_cluster - when deleting a cluster, if its already in the state of `deleting` it should wait and watch the delete to finish.

### ISSUE THREAD

**Issue by paulczar** [hashicorp/terraform-provider-azurerm#25739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.4.6

### AzureRM Provider Version

3.92.0

### Affected Resource(s)/Data Source(s)

azurerm_redhat_openshift_cluster

### Terraform Configuration Files

```hcl
.
```

### Debug Output/Panic Output

```shell
.
```

### Expected Behaviour

when running an operation that would delete the cluster,  either deleting it or doing a version change,  if the cluster is already in a deleting state it should wait for the delete operation to finish and then update its state and move to the next resource.

### Actual Behaviour

```
To perform exactly these actions, run the following command to apply:
    terraform apply "aro.plan"
terraform apply aro.plan
azurerm_redhat_openshift_cluster.cluster: Destroying... [id=/subscriptions/c5545383-1a94-45fe-b501-7ebdf43e5d7a/resourceGroups/aro-xx-rg/providers/Microsoft.RedHatOpenShift/openShiftClusters/aro-pczarkow]
╷
│ Error: deleting Provider Open Shift Cluster (Subscription: "c5545383-1a94-45fe-b501-7ebdf43e5d7a"
│ Resource Group Name: "aro-xx-rg"
│ Open Shift Cluster Name: "aro-xx"): performing Delete: unexpected status 400 with error: RequestNotAllowed: Request is not allowed in provisioningState 'Deleting'.
│
│ deleting Provider Open Shift Cluster (Subscription: "c5545383-1a94-45fe-b501-7ebdf43e5d7a"
│ Resource Group Name: "aro-xx-rg"
│ Open Shift Cluster Name: "aro-xx"): performing Delete: unexpected status 400 with error: RequestNotAllowed:
│ Request is not allowed in provisioningState 'Deleting'.
╵
make: *** [Makefile:18: create] Error 1
```

**Comment by teowa** [comment]
@paulczar , thanks for submitting this.
From the source code, when we delete the `azurerm_redhat_openshift_cluster` resource, the provider is supposed wait until the response code changed from `200` to `404`. Is it possible the deletion is triggered outside of terraform or in previous Terraform apply? Could you please share the [debug log](https://developer.hashicorp.com/terraform/internals/debugging) containing API https flow with `TF_LOG=debug`, remember to hide sensitive info (e.g., subscription ID).

https://github.com/hashicorp/terraform-provider-azurerm/blob/2d02a315829ba7bfe871ebc6f8683caa24b77401/internal/services/redhatopenshift/redhat_openshift_cluster_resource.go#L517

https://github.com/hashicorp/terraform-provider-azurerm/blob/2d02a315829ba7bfe871ebc6f8683caa24b77401/vendor/github.com/hashicorp/go-azure-sdk/resource-manager/redhatopenshift/2023-09-04/openshiftclusters/method_delete.go#L65

https://github.com/hashicorp/terraform-provider-azurerm/blob/2d02a315829ba7bfe871ebc6f8683caa24b77401/vendor/github.com/hashicorp/go-azure-sdk/sdk/client/pollers/poller.go#L124

https://github.com/hashicorp/terraform-provider-azurerm/blob/2d02a315829ba7bfe871ebc6f8683caa24b77401/vendor/github.com/hashicorp/go-azure-sdk/sdk/client/resourcemanager/poller_delete.go#L88-L102

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @teowa's response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
