### ISSUE TITLE
Error: Invalid index

### ISSUE THREAD

**Issue by aravindmetla** [hashicorp/terraform-provider-azurerm#25736]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.5

### AzureRM Provider Version

3.52.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_table_entity

### Terraform Configuration Files

```hcl
locals {

  exception_handling = {
    1 = {
      partition_key        = "1",
      SystemName           = "ais",
      SystemErrorCode      = "401",
      ApplicationErrorCode = "",
      ExceptionType        = "application",
      Impact               = "1",
      Urgency              = "2"
    },

    2 = {
      partition_key        = "1",
      SystemName           = "ais",
      SystemErrorCode      = "400",
      ApplicationErrorCode = "",
      ExceptionType        = "business",
      Impact               = "1",
      Urgency              = "2"
    },

    3 = {
      partition_key        = "1",
      SystemName           = "ais",
      SystemErrorCode      = "403",
      ApplicationErrorCode = "",
      ExceptionType        = "application",
      Impact               = "1",
      Urgency              = "2"
    },

    4 = {
      partition_key        = "1",
      SystemName           = "ais",
      SystemErrorCode      = "",
      ApplicationErrorCode = "458",
      ExceptionType        = "technical",
      Impact               = "1",
      Urgency              = "2"
    }
  }
}
resource "azurerm_storage_table_entity" "exception_handling-shared" {
  for_each             = local.exception_handling
  storage_account_name = azurerm_storage_account.shared_storage_account.name
  table_name           = azurerm_storage_table.platform_logic_app_tables-shared["exceptionproperties"].name

  partition_key = each.value["partition_key"]
  row_key       = each.key

  entity = {
    SystemName           = each.value["SystemName"]
    SystemErrorCode      = each.value["SystemErrorCode"]
    ApplicationErrorCode = each.value["ApplicationErrorCode"]
    ExceptionType        = each.value["ExceptionType"]
    Impact               = each.value["Impact"]
    Urgency              = each.value["Urgency"]
  }
}
```

### Debug Output/Panic Output

```shell
on storage.tf line 3464, in resource "azurerm_storage_table_entity" "exception_handling-shared":
3464:     Impact               = each.value["Impact"]
    ├────────────────
    │ each.value is object with 6 attributes

The given key does not identify an element in this collection value.
```

**Comment by magodo** [comment]
@aravindmetla I guess the `local` here is simplified as I can validate above config with no error locally. Please check all the elements in the `local` to ensure they have the same fields. Alternatively, you can declare the  `exception_handling` as a variable with type constraint to enforce that, see https://discuss.hashicorp.com/t/each-value-is-object-with-5-attributes/59529/2

**Comment by Chambras** [comment]
@aravindmetla maybe you could also test with a more up to date terraform and azurerm versions? The most recent ones are terraform 1.8.2 and azurerm 3.100.0

**Comment by aravindmetla** [comment]
@Chambras figured there was a missing filed in locals and github actions was taking refs/remotes/pull/<req no>/merge branch while running the pipeline. fixed the issue now. thank you for support

**Comment by aravindmetla** [comment]
issue solved as a filed was missing in local variable
