### ISSUE TITLE
Support for all the license_type of linux vm on azure

### ISSUE THREAD

**Issue by arsenicks** [hashicorp/terraform-provider-azurerm#25741]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

With terraform right now, it's impossible to set the license_type of an azure vm at creation for anything other than RHEL_BYOS or SLES_BYOS.

From the terraform documentation: 
[license_type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#license_type) - (Optional) Specifies the BYOL Type for this Virtual Machine. Possible values are RHEL_BYOS and SLES_BYOS.

Here's the code that limit those value: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/linux_virtual_machine_resource.go#L234-L241 it was [added in 2021 via this commit](https://github.com/hashicorp/terraform-provider-azurerm/commit/afb08be8048fe9b5c2c542e698e428452c746f0a)

The [microsoft documentation](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-linux?tabs=ahbNewPortal%2CahbExistingPortal%2Clicenseazcli%2CrhelAzcliByosConv%2Crhelazclipaygconv%2Crhelpaygconversion%2Crhelcompliance#check-the-current-licensing-model-of-an-ahb-enabled-vm) confirm the list of possible license_type value for a linux vm.

The following license types correspond to PAYG model:
* For RHEL: RHEL_BASE, RHEL_EUS, RHEL_SAPAPPS, RHEL_SAPHA, RHEL_BASESAPAPPS, or RHEL_BASESAPHA.
* For SLES: SLES, SLES_SAP, or SLES_HPC

These ones correspond to BYOS:
* For RHEL: RHEL_BYOS
* For SLES: SLES_BYOS

Detailled license type description:
License type | Software updates | Allowed virtual machines
-- | -- | --
RHEL_BASE | Installs Red Hat regular/base repositories on your virtual machine. | RHEL BYOS virtual machines, RHEL custom image virtual machines
RHEL_EUS | Installs Red Hat Extended Update Support (EUS) repositories on your virtual machine. | RHEL BYOS virtual machines, RHEL custom image virtual machines
RHEL_SAPAPPS | Installs RHEL for SAP Business Apps repositories on your virtual machine. | RHEL BYOS virtual machines, RHEL custom image virtual machines
RHEL_SAPHA | Installs RHEL for SAP with High Availability (HA) repositories on your virtual machine. | RHEL BYOS virtual machines, RHEL custom image virtual machines
RHEL_BASESAPAPPS | Installs RHEL regular/base SAP Business Apps repositories on your virtual machine. | RHEL BYOS virtual machines, RHEL custom image virtual machines
RHEL_BASESAPHA | Installs regular/base RHEL for SAP with HA repositories on your virtual machine. | RHEL BYOS virtual machines, RHEL custom image virtual machines

It's already supported in [azure-cli since 2021](https://github.com/Azure/azure-cli/issues/20667) and using ARM templates too so I guess the API support it.

We use custom image created onprem using packer, those image are considered BYOS by default. We must set the license_type: RHEL_BASE on every vm so they will be billed as PAYG. This method has been confirmed by Microsoft support and Red Hat.

Would it be possible to simply add the supported license_type to the code ? If not all, at least RHEL_BASE because I'm pretty sure we will not be the only one using this in the future.

Red Hat will publish a knowledbase article to clarify this path is supported in the upcoming weeks.

### New or Affected Resource(s)/Data Source(s)

linux_virtual_machine_resource

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  license_type:       = "RHEL_BASE"
.....
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/compute/linux_virtual_machine_resource.go#L234-L241

https://github.com/hashicorp/terraform-provider-azurerm/commit/afb08be8048fe9b5c2c542e698e428452c746f0a

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine#license_type

https://learn.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-linux?tabs=ahbNewPortal%2CahbExistingPortal%2Clicenseazcli%2CrhelAzcliByosConv%2Crhelazclipaygconv%2Crhelpaygconversion%2Crhelcompliance#check-the-current-licensing-model-of-an-ahb-enabled-vm

**Comment by arsenicks** [comment]
@stephybun Hi, thanks for accepting the PR and merging it quick. 

I Just wanted to point out my PR only included RHEL_BASE because this is the one we need and I felt the other license_type might require more extended discussion. Shall we keep this issue open( as it was including all other license type) to discuss adding the other license type for the benefit of others ?

Otherwise it will fix our issue so that's good enough for me..

**Comment by stephybun** [comment]
@arsenicks sure it makes sense to keep the issue open. In future you can replace the word `Fixes #00000` with `Related #00000` in the PR to link the two but it won't close the issue when the PR is merged.

**Comment by arsenicks** [comment]
Thanks, I didn't know the difference! Does reopening the issue will block the inclusion of the fix in the release 3.102 or its already merged and will be included tomorrow?

**Comment by stephybun** [comment]
Nope! When it's merged it goes into the next AzureRM provider release 🙂

**Comment by Bjarki2330** [comment]
Any info on when the rest of the `license_type` attribute will support more strings? I can't update my code because one of our Linux machines has `RHEL_SAPAPPS` and requires `RHEL_BYOS` / `SLES_BYOS` or it just defaults to `none`.

**Comment by arsenicks** [comment]
> Any info on when the rest of the `license_type` attribute will support more strings? I can't update my code because one of our Linux machines has `RHEL_SAPAPPS` and trying to change it requires `RHEL_BYOS` / `SLES_BYOS` or `none`.

Hi @Bjarki2330 I didn't include them in my PR because I didn't want to be denied in case those license type shouldn't be added and I wanted the discussion to be held here.

I'll create a new PR on my lunch time to add all the other license_type supported on azure and submit it, we'll see how it goes I guess.

**Comment by arsenicks** [comment]
> Any info on when the rest of the `license_type` attribute will support more strings? I can't update my code because one of our Linux machines has `RHEL_SAPAPPS` and trying to change it requires `RHEL_BYOS` / `SLES_BYOS` or `none`.

Here you go, the PR is up for review. Once approved and merged, it will get shipped with next azurerm provider release which happen every Friday.

That being said, it's really simple to contribute, next time you face something like that I encourage you to fork the repo and submit a PR by yourself! :)
