### ISSUE TITLE
azurerm_monitor_workspace: Microsoft.Monitor and Microsoft.Dashboard provider not registered

### ISSUE THREAD

**Issue by cveld** [hashicorp/terraform-provider-azurerm#25769]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

3.101.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_workspace and azurerm_dashboard_grafana

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_workspace" "default" {
  name                = "mw-${local.resource_name_suffix}"
  resource_group_name = module.rg.groups.default.name
  location            = module.rg.groups.default.location
}

resource "azurerm_dashboard_grafana" "default" {
  name                              = "amg-${local.resource_name_suffix}"
  resource_group_name               = module.rg.groups.default.name
  location                          = module.rg.groups.default.location
  api_key_enabled                   = true
  deterministic_outbound_ip_enabled = false
  public_network_access_enabled     = true
  identity {
    type = "SystemAssigned"
  }
  azure_monitor_workspace_integrations {
    resource_id = azurerm_monitor_workspace.default.id
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The Microsoft.Monitor and Microsoft.Dashboard providers should be registered in the subscription by the azurerm provider.

### Actual Behaviour

``` Error: creating Account (Subscription: "suppressed"
│ Resource Group Name: "rg-monitoring-cve-jo8e"
│ Account Name: "mw-monitoring-cve-jo8e"): unexpected status 409 (409 Conflict) with error: MissingSubscriptionRegistration: The subscription is not registered to use namespace 'Microsoft.Monitor'. See https://aka.ms/rps-not-found for how to register subscriptions.

│ Error: creating Grafana (Subscription: "suppressed"
│ Resource Group Name: "rg-monitoring-cve-jo8e"
│ Grafana Name: "amg-monitoring-cve-jo8e"): performing GrafanaCreate: unexpected status 409 (409 Conflict) with error: MissingSubscriptionRegistration: The subscription is not registered to use namespace 'Microsoft.Dashboard'. See https://aka.ms/rps-not-found for how to register subscriptions.
│
```

### Steps to Reproduce

`terraform apply`

**Comment by brany09** [comment]
Same Issue here with latest versions

Terraform Version
1.9.2

AzureRM Provider Version
3.112.0


**Workaround**
manually register the provider using 
resource "azurerm_resource_provider_registration" "example" {
  name = "Microsoft.Monitor"
}
