### ISSUE TITLE
Support for daemonset-eviction-for-occupied-nodes

### ISSUE THREAD

**Issue by nemobis** [hashicorp/terraform-provider-azurerm#25764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The cluster autoscaler in AKS is nearly useless by default for the default pool, which always contains kube-system pods and usually some daemonset pods.

Currently the provider supports `skip-nodes-with-local-storage` and `skip-nodes-with-system-pods`, but additionally it would be good to have support for more [cluster-autoscaler-profile-settings](https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler?tabs=azure-cli#cluster-autoscaler-profile-settings)
* `daemonset-eviction-for-empty-nodes`: "Whether DaemonSet pods will be gracefully terminated from empty nodes."
* `daemonset-eviction-for-occupied-nodes`: "Whether DaemonSet pods will be gracefully terminated from non-empty nodes."

Both are currently marked as "in preview".

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster (auto_scaler_profile)

### References

https://learn.microsoft.com/en-us/azure/aks/cluster-autoscaler?tabs=azure-cli#cluster-autoscaler-profile-settings
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#skip_nodes_with_local_storage

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
