### ISSUE TITLE
Support for providing a Image reference while creating User and System node pools for AKS cluster

### ISSUE THREAD

**Issue by anilkumarpodugu** [hashicorp/terraform-provider-azurerm#25796]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

We would like to pass a custom image to the agent and user node pools while creating a AKS cluster using terraform.
As of now, we can only provide the VM_Size and the OS disk size. Once the AKS cluster is created using terraform, we see that AKSUbuntu has been used for linux based Agent Pools and the Storage type is set to Premium_SSD_LRS. When we try to a AKS cluster through Azure Portal, we can choose the VM SKU and Storage type of the Pool.
Having an option to provide the storage type for pools or provide an option to use a custom image of inhouse would really help.
Kindly look into this request.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool,azurerm_kubernetes_cluster

**Comment by anilkumarpodugu** [comment]
Attaching a screenshot for the issue reported
<img width="800" alt="github_new_feature" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/69627867/21baf2bc-74dc-4564-83df-05d40e674208">

**Comment by stephybun** [comment]
Thanks for raising this feature request @anilkumarpodugu.

Looking at the portal I don't see an option to select the underlying VM Sku and Storage type of a node pool, furthermore I don't see any option to supply this information to the AKS API so it looks like you will need to raise an issue over on [Azure/AKS](https://github.com/Azure/AKS) to have support for this added to the API.

**Comment by anilkumarpodugu** [comment]
Thanks for the reply. Will raise an issue in [Azure/AKS](https://github.com/Azure/AKS) as suggested.
