### ISSUE TITLE
Support for virtual endpoints for Postgres Flexible Servers

### ISSUE THREAD

**Issue by kingnathanal** [hashicorp/terraform-provider-azurerm#25803]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Azure has recently added support for promoting Postgres Flexible server read replica to primary, virtual endpoints are a way to create a single endpoint for referencing the primary server. 

[Learn docs](https://learn.microsoft.com/en-us/azure/postgresql/flexible-server/concepts-read-replicas-virtual-endpoints)

### New or Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server_virtual_endpoint" "this" {
  name = "virtual_endpoint_name"
  primary_server_id = azurerm_postgresql_flexible_server.primary_server.id
  read_server_id = azurerm_postgresql_flexible_server.replica_server.id
}
```

**Comment by fahimthanawala1** [comment]
I am also looking for this features, we have migration planned for the same.

**Comment by ramyeduri** [comment]
any update on this issue? we are also looking to adopt this new feature

**Comment by acoba33** [comment]
good day, I am also looking for this feature in terraform. Can an update please be provided so I can have a relative timeline for general availability? thank you.

**Comment by Pinaki-1** [comment]
+1

**Comment by ori-21** [comment]
Is it possible to create virtual endpoints for Postgres Flexible Servers using terraform module or it is not supported yet?

i tried the suggested terraform code above but the provider hashicorp/azurerm does not support resource type
 "azurerm_postgresql_flexible_server_virtual_endpoint"

Do anyone know any other solution?

Thank you in advance!

**Comment by ori-21** [comment]
So , finally can we use this resource now because i tried and got:
**Error: Invalid resource type
on virtual_endpoint.tf line 1, in resource "azurerm_postgresql_flexible_server_virtual_endpoint" "virtual-endpoint":
resource "azurerm_postgresql_flexible_server_virtual_endpoint" "virtual-endpoint" {
The provider hashicorp/azurerm does not support resource type "azurerm_postgresql_flexible_server_virtual_endpoint".**

**Comment by Krusty93** [comment]
> So , finally can we use this resource now? Because i tried and got: **Error: Invalid resource type on virtual_endpoint.tf line 1, in resource "azurerm_postgresql_flexible_server_virtual_endpoint" "virtual-endpoint": resource "azurerm_postgresql_flexible_server_virtual_endpoint" "virtual-endpoint" { The provider hashicorp/azurerm does not support resource type "azurerm_postgresql_flexible_server_virtual_endpoint".**

You need version `3.116`
