### ISSUE TITLE
Subnet Ids starting with '/' cause resources to always be updated

### ISSUE THREAD

**Issue by CampionFabio** [hashicorp/terraform-provider-azurerm#25832]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.2

### AzureRM Provider Version

3.101.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "theVnet" {
  name                = "theVnet"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  address_space       = "10.0.0.0/16"
  lifecycle {
    ignore_changes = [tags]
  }
}

resource "azurerm_subnet" "theSubNet" {
  name                 = "theSubNet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.theVnet.name
  address_prefixes     = "10.0.0.0/24"
  service_endpoints = [
    "Microsoft.Web",
    "Microsoft.Sql",
    "Microsoft.AzureCosmosDB"
  ]

  delegation {
    name = "Microsoft.Web.serverFarm"
    service_delegation {
      actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
      name    = "Microsoft.Web/serverFarms"
    }
  }
}


resource "azurerm_linux_web_app" "myWebApp" {
  name                = "myWebApp"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  service_plan_id     = azurerm_service_plan.aPlan.id
  https_only          = false

  client_affinity_enabled = true
    application_stack {
      dotnet_version = "6.0"
    }
    minimum_tls_version = "1.2"
  }

  virtual_network_subnet_id = azurerm_subnet.theSubNet.id
  lifecycle {
    ignore_changes = [
      tags,
      logs
    ]
  }
}
```

### Debug Output/Panic Output

```shell
# azurerm_linux_web_app.myWebApp will be updated in-place
  ~ resource "azurerm_linux_web_app" "myWebApp" {
        id                                             = "/subscriptions/<subsId>/resourceGroups/<rgName>/providers/Microsoft.Web/sites/myWebApp"
        name                                           = "myWebApp"
      ~ virtual_network_subnet_id                      = "/subscriptions/<subsId>/resourceGroups/<rgName>/providers/Microsoft.Network/virtualNetworks/<vnetNAme>/subnets/<subVnetName>" -> "subscriptions/<subsId>/resourceGroups/<rgName>/providers/Microsoft.Network/virtualNetworks/<vnetNAme>/subnets/<subVnetName>"
```

### Expected Behaviour

There should not be an update

### Actual Behaviour

it seems that because of the "/" in front of the subnet Id the resource "azurerm_linux_web_app.myWebApp" is always updated

### Steps to Reproduce

run `terraform apply`

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25885 created for this issue.
