### ISSUE TITLE
azurerm_api_management_api_operation representation/example/value does not get imported

### ISSUE THREAD

**Issue by lightpeak** [hashicorp/terraform-provider-azurerm#25843]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

3

### AzureRM Provider Version

3.102.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_api_operation

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api_operation" "delete_shipment" {
  operation_id        = "delete-shipment"
  api_name            = "Warehouse"
  api_management_name = var.apiMangementInstanceName
  resource_group_name = var.commonResourceGroupName
  display_name        = "Delete Shipment"
  method              = "POST"
  url_template        = "/shipment"
  description         = "Delete shipment(s) in Scale."

  request {
    header {
      name     = "warehouse"
      type     = "string"
      required = true
    }
    representation {
      content_type = "application/json"
      example {
        name  = "delete-shipment"
        value = <<JSON
          [{"InternalShipmentNum": 103}]
        JSON        
      }
    }
  }

  response {
    status_code = 200
    description = "Successful response"
    representation {
      content_type = "application/json"
    }
  }
}
```

### Debug Output/Panic Output

```shell
...
```

### Expected Behaviour

The pre-filled request body in the Azure API Management portal should have this value:
[{"InternalShipmentNum": 103}]

### Actual Behaviour

It's empty

### References

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/31926380/ce8529bd-a5c3-47ec-9926-66897b94b790)

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. Since it appears you have been able to solve your issue, I am going to mark this issue as resolved. Thanks!
