### ISSUE TITLE
Support for  DBFS firewall setting in `azurerm_databricks_workspace` resource

### ISSUE THREAD

**Issue by alexott** [hashicorp/terraform-provider-azurerm#25899]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Support for a firewall for the workspace's managed storage account (DBFS Root) was [recently released](https://learn.microsoft.com/en-us/azure/databricks/security/network/storage/firewall-support).  This functionality is typically requested by big enterprise customers who very often use Terraform for deployment of compliant workspaces.

It would be great to add support for this functionality to `azurerm` provider.

### New or Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25919 created by @favoretti for this issue.
