### ISSUE TITLE
Frontdoor persistent diff

### ISSUE THREAD

**Issue by VenelinMartinov** [hashicorp/terraform-provider-azurerm#25911]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.2

### AzureRM Provider Version

3.102.0

### Affected Resource(s)/Data Source(s)

azurerm_frontdoor

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.102.0"
    }
  }
}

# Configure the Microsoft Azure Provider
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "resourceGroup"
  location = "West Europe"
}

resource "azurerm_frontdoor" "example" {
  name                = "example476"
  resource_group_name = azurerm_resource_group.example.name

  routing_rule {
    name               = "rule1"
    accepted_protocols = ["Http", "Https"]
    patterns_to_match  = ["/*"]
    frontend_endpoints = ["frontEndEndpoint1"]

    forwarding_configuration {
      forwarding_protocol = "MatchRequest"
      backend_pool_name   = "exampleBackendBing"
    }
  }

  backend_pool_load_balancing {
    name = "exampleLoadBalancingSettings1"
  }

  backend_pool_health_probe {
    name         = "exampleHealthProbeSetting1"
    protocol     = "Https"
    probe_method = "HEAD"
  }

  backend_pool {
    name = "exampleBackendBing"
    backend {
      host_header = "www.bing.com"
      address     = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }

    load_balancing_name = "exampleLoadBalancingSettings1"
    health_probe_name   = "exampleHealthProbeSetting1"
  }

  frontend_endpoint {
    name      = "frontEndEndpoint1"
    host_name = "example476.azurefd.net"
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/VenelinMartinov/e93307a9682d266b5a5e5e6c6f630355
```

### Expected Behaviour

Upon running plan after apply, I expect there to be no diff in the resource.

### Actual Behaviour

A diff is produced on backend_pool_settings and cache_query_parameters every time.

Should the property be Computed given that the provider is setting it?

https://github.com/hashicorp/terraform-provider-azurerm/blob/0e9b08f5b552e58e396abd1c0dbec4505ae26869/internal/services/frontdoor/frontdoor_resource.go#L2072

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

**Comment by rcskosir** [comment]
Thanks for opening this issue. Azure Front Door Classic has been deprecated and is not actively maintained please see the note here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor. As such I am going to mark this issue closed. If this is still an issue with the 4.x version of the provider for the Azure Front Door Standard/Premium resource please do let us know by opening a new issue, thanks!
