### ISSUE TITLE
Automatically set the proper Cloud Environment

### ISSUE THREAD

**Issue by sigv** [hashicorp/terraform-provider-azurerm#2591]
When using a specific Azure Cloud Environment with Azure CLI authentication, not running `az cloud set --name x` results in _Error obtaining Authorization Token from the Azure CLI: Error waiting for the Azure CLI: exit status 1_.

This manual switch of Cloud Environments is a documented requirement, but when managing resources in multiple Clouds, such as for example the `public` and `german` ones, this prerequisite can be tedious and annoying.

Keeping in mind the `environment` field is set on the Provider block anyhow, it would be a great improvement if the switch were to be done automagically.

**Comment by tombuildsstuff** [comment]
hey @sigv 

Thanks for opening this issue - apologies for the delayed response here!

This sounds like a good addition to me - all of the authentication code is now in the [go-azure-helpers](https://github.com/hashicorp/go-azure-helpers) repository - as such I've opened an upstream issue to track this.

Thanks!

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
