### ISSUE TITLE
Documentation misleading for azurerm_container_app_job

### ISSUE THREAD

**Issue by kieranstockdale** [hashicorp/terraform-provider-azurerm#25927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_container_app_job

### Terraform Configuration Files

```hcl
https://github.com/hashicorp/terraform-provider-azurerm/blob/9c38efc5cbb701be6c142bd9423705e02e1fcc6a/website/docs/r/container_app_job.html.markdown?plain=1#L397

The documentation states only system assigned or none. However, this resource also supports user assigned managed identities.
```

### Debug Output/Panic Output

```shell
As above
```

**Comment by shaanrxx** [comment]
Hello, I can work on this!

**Comment by kurarrr** [comment]
Hello, I sent a small PR for this! https://github.com/hashicorp/terraform-provider-azurerm/pull/25989
