### ISSUE TITLE
Resource "azurerm_monitor_scheduled_query_rules_alert_v2" created but corrupted

### ISSUE THREAD

**Issue by admsallai** [hashicorp/terraform-provider-azurerm#25921]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

3.83.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "total_ingestion_alert" {  
  name = "ingestion-alert"
  location = data.azurerm_resource_group.infrastructure_rg.location
  resource_group_name  = data.azurerm_resource_group.infra_rg.name
  scopes = [data.azurerm_log_analytics_workspace.law.id]
  severity = 2
  evaluation_frequency = "PT6H"
  window_duration = "P1D"
  description = "n/A"
  action {
    action_groups = [azurerm_monitor_action_group.action_group["actiongroup"].id]
  }
  criteria {
    operator = "GreaterThan"
    query = "Usage | where TimeGenerated > ago(24h) | summarize TotalIngestionVolGB = sum(Quantity)/1024.0"
    metric_measure_column = "TotalIngestionVolGB"
    time_aggregation_method = "Total"
    threshold = 5
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Create an alert which is not corrupted.

### Actual Behaviour

Alert is successfully created and visible in Azure Portal. However it is not being fired when criteria are met, and when trying to edit it in the portal this happend:

![Screenshot 2024-04-19 141102](https://github.com/hashicorp/terraform-provider-azurerm/assets/102801593/673f2df1-a4c4-4faa-8ccf-5638f0b0e16e)

No summary is present. Unable to click Review+Save. Next step is Review+Save, even when Review+Save page is already open.

**After contacting Microsoft support, they could not fix the issue, and this is how they described this issue after investigating:**

"If an alert rule is created without managed identity from portal, we don't see that entry in the export template, whereas the terraform includes a Null value even though managed Identity is not enabled. Kindly ask you to reach out to terraform support and highlight this issue, they should probably fix it from their end."

This alert was working fine when creating 2 months ago, however when I need to recreate it again, with the same terraform code, this issue happened. **This issue is present for all the alerts of this kind, not only this one.**

### Steps to Reproduce

1. terraform plan
2. terraform apply

### Important Factoids

N/A

**Comment by Chambras** [comment]
@admsallai interesting, have you tried adding that `identity` block and set it to `SystemAssigned` ?
you might also upgrade the provider to the latest one 3.102.0
3.83.0 is kind of old...

**Comment by teowa** [comment]
Hi @admsallai , 
> This alert was working fine when creating 2 months ago, however when I need to recreate it again, with the same terraform code, this issue happened. This issue is present for all the alerts of this kind, not only this one.

Since you are using same terraform code and same Terraform provider version but it failed, it might be some changes happened at service backend.

From the support, seems you need to add `identity` to solve this,  the `identity` is introduced in version 3.98.0 from https://github.com/hashicorp/terraform-provider-azurerm/pull/25365, could you please try to use the latest version of the provider? Thanks.

**Comment by admsallai** [comment]
The updating of provider itself did not help, however then adding the identity block did! Thanks for your help!

**Comment by guidojw** [comment]
I'm also stuck on this issue with a log v2 alert that has an Application Insights instance as scope. Do you know what role is needed for the alert identity to be able to read metrics/logs on Application Insights?

**Comment by JoshWeepie** [comment]
@teowa Terraform is passing identity[type:None, userAssignedIdentities:null] in the requestbody, but creating an alert manually in the portal without identity doesn't pass any identity parameters in the requestbody, according the Portal Activity log JSON.

Essentially, anyone trying to create azurerm_monitor_scheduled_query_rules_alert_v2 without a managed identity can't until this is fixed, or they have to do it manually in the portal. If the portal/API supports creation without managed identity, shouldn't the azurerm provider behave the same for azurerm_monitor_scheduled_query_rules_alert_v2?

**Comment by JoshWeepie** [comment]
The API doc says identity is optional.

https://learn.microsoft.com/en-us/rest/api/monitor/scheduled-query-rules/create-or-update?view=rest-monitor-2023-03-15-preview&tabs=HTTP#request-body

The portal/API lets you create alerts without identity. The provider change https://github.com/hashicorp/terraform-provider-azurerm/pull/25365 is wrong for sending identity in the request parameters no matter what, is it not?

**Comment by JoshWeepie** [comment]
@admsallai @guidojw A workaround is to use the Azure CLI to update the --disabled or --severity properties on the log alert. Then you can edit the alert in the portal and save like normal as well. This will fix the alert triggering and my alert worked again after modifying. 👍 💯 

`az monitor scheduled-query update --disabled true --name 'Scheduled log alert name' --resource-group rgname`

or

`az monitor scheduled-query update --severity 3 --name 'Scheduled log alert name' --resource-group rgname`

**Comment by the-rule** [comment]
Having the same issue with hashicorp/azurerm v3.106.1

Would very much appreciate the fix for it since we manage a lot of monitoring alerts and manual involvement is not an option at all.

**Comment by admsallai** [comment]
I fixed the issue (or better to say created a workoround) by creating one user managed identity with necessary RBAC (Log Analytics Reader in my case) and assigned this identity to all alerts. Now it is all up and running without any issues.
