### ISSUE TITLE
Support for adding NSG argument in 'azurerm_subnet' block

### ISSUE THREAD

**Issue by APEX-DUSAN-ZAKIC** [hashicorp/terraform-provider-azurerm#25928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When deploying Network resources in Azure i used VNet block and defined subnet in that one. Since indexing of subnets can be quite "clonky" i decided to define Subnets as separate resource. The problem that i confronted was that i can't define the Network Security Group as an argument in that resource group. No problem, i created 'azurerm_subnet_network_security_group_association' but i now have a problem. Upon subnet creation NSG is not associated, only after creation and my security Policy is preventing creation of Subnets without NSG. I don't want to bypass the policy because it makes sense.

### New or Affected Resource(s)/Data Source(s)

azurerm_subnet

### Potential Terraform Configuration

```hcl
Add new argument to associate Network security group to the subnet similar to what you can do in a 'azurerm_virtual_network' block:

resource "azurerm_virtual_network" "example" {
  provider = azurerm.win365-nonprod
  name                = "example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["0.0.0.0/0"]
  dns_servers         = ["1.0.0.0]

  subnet {
    name           = "example"
    address_prefix = "0.0.0.0/0"
    security_group = azurerm_network_security_group.example.id
  }
```

**Comment by tombuildsstuff** [comment]
hi @APEX-DUSAN-ZAKIC 

This field has been intentionally removed from the `azurerm_subnet` resource to workaround issues within the Azure Platform during the deletion of resources, as this field has been intentionally removed unfortunately this isn't something we plan to reintroduce.

Instead #9022 is tracking adding an example of how to use Azure Policy with the separate resources, and #3917 is tracking adding additional fields within the `azurerm_virtual_network` resource - as such whilst I'd like to thank you for opening this issue I'm going to close this in favour of #9022 - would you mind subscribing to that issue for updates?

Thanks!
