### ISSUE TITLE
`azurerm_container_app_job` can't create secret that references KeyValt

### ISSUE THREAD

**Issue by kaedroho** [hashicorp/terraform-provider-azurerm#25934]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.3

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_container_app_job

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_secret" "api_key" {
  name         = "api-key"
  key_vault_id = azurerm_key_vault.default.id
  depends_on = [azurerm_role_assignment.key_vault_administrators_key_vault_secrets_officer]
}

resource "azurerm_container_app_job" "job" {
  name                         = "job"
  container_app_environment_id = azurerm_container_app_environment.default.id
  resource_group_name          = azurerm_resource_group.default.name
  location                     = azurerm_resource_group.default.location
  replica_timeout_in_seconds = 60
  replica_retry_limit        = 1

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.default.id]
  }

  secrets {
    name = "api-key"
    key_vault_secret_id = data.azurerm_key_vault_secret.api_key.id
    identity = azurerm_user_assigned_identity.default.id
  }

  template {
    container {
      name   = "worker"
      image  = ""
      cpu    = 0.5
      memory = "1Gi"

      env {
        name = "PLANG_API_KEY"
        secret_name = "plang-api-key"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Job (Subscription: "002c35be-da1d-4a33-a243-9c11b7aaf0cd"
│ Resource Group Name: "resource-group"
│ Job Name: "job"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ContainerAppSecretInvalid: Invalid Request: Container app secret(s) with name(s) 'api-key' are invalid: value or keyVaultUrl and identity should be provided.
│ 
│   with module.mymodule.azurerm_container_app_job.job,
│   on mymodule/container_app.tf line 8, in resource "azurerm_container_app_job" "job":
│    8: resource "azurerm_container_app_job" "job" {
│ 
│ updating Job (Subscription: ""
│ Resource Group Name: "resourcegroup"
│ Job Name: "job"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error:
│ ContainerAppSecretInvalid: Invalid Request: Container app secret(s) with name(s) 'api-key' are invalid: value or
│ keyVaultUrl and identity should be provided.
```

### Expected Behaviour

- This should be accepted as `key_vault_secret_id` and `identity` is provided
- This works for `azurerm_container_app`

### Actual Behaviour

A 400 bad request error is returned (see above)

### Steps to Reproduce

1) Add a `secrets` block that references a key vault secret to a `azurerm_container_app_job` resource

For example:
```hcl
resource "azurerm_container_app_job" "job" {
  ...

  secrets {
    name = "api-key"
    key_vault_secret_id = data.azurerm_key_vault_secret.api_key.id
    identity = azurerm_user_assigned_identity.default.id
  }

  ...
}
```

2) Run `terraform apply`

**Comment by guri-s** [comment]
Waiting for this to be merged so don't have to use azapi resource
