### ISSUE TITLE
[Postgres] Changing storage_mb from 524288 to 1048576 fails with storage_tier error

### ISSUE THREAD

**Issue by anoopjb** [hashicorp/terraform-provider-azurerm#25938]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.15.5

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
# terraform.tfstate
{
  "mode": "managed",
  "type": "azurerm_postgresql_flexible_server",
  "provider": "provider[\"registry.terraform.io/hashicorp/azurerm\"]",
  "instances": [
    {
      "sku_name": "GP_Standard_D2s_v3",
      "storage_mb": 524288,
      "storage_tier": "P20"
    }
  ]
}

# postgres.tf.json
{
  "resource": {
    "azurerm_postgresql_flexible_server": {
      "postgres_server": {
        "sku_name": "GP_Standard_D2s_v3",
        "storage_mb": 1048576,
        "version": "14"
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
[ERROR] provider.terraform-provider-azurerm_v3.103.1_x5: Response contains error diagnostic: @caller=github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/diag/diagnostics.go:58 @module=sdk.proto diagnostic_detail= tf_resource_type=azurerm_postgresql_flexible_server tf_rpc=PlanResourceChange diagnostic_severity=ERROR diagnostic_summary="1 error occurred:
        * invalid 'storage_tier' "P20" for defined 'storage_mb' size '1048576', expected one of ["P30", "P40" or "P50"]
```

### Expected Behaviour

The `storage_tier` is not explicitly mentioned in `postgres.tf.json`. The provider picks the default `storage_tier` (i.e `P30` as per the documentation [here](https://registry.terraform.io/providers/hashicorp/azurerm/3.96.0/docs/resources/postgresql_flexible_server#storage_tier-defaults-based-on-storage_mb)) for the storage_mb of `1048576`.

### Actual Behaviour

Changing `storage_mb` from `524288` to `1048576` fails due to invalid `storage_tier` "P20". 

### Steps to Reproduce

1. Setup a new Azure PostgreSQL Flexible Server with  `storage_mb` as `524288`. 
2. Change the  storage_mb to `1048576`.

**Comment by WodansSon** [comment]
Hi @anoopjb, thank you for opening this issue. Just so I understand the ask here, what you are saying is that you expect the `storage_tier`, if not defined in the configuration file, to follow the default `storage_tier` assignment semantics of the `create` function during an `update` operation? Basically, given your above example, if you change the configuration files `storage_mb` value from `524288` to `1048576` you expect the terraform provider to automatically update the `storage_tier` value to the API to be the default value for the newly defined `storage_mb` value (e.g., `P30') instead of passing/keeping the original `default` `sorage_tier` value of `P20`?

**Comment by anoopjb** [comment]
Yes, @WodansSon. Thanks.
