### ISSUE TITLE
azurerm_kubernetes_service_versions data source add default stable version support

### ISSUE THREAD

**Issue by ianarsenault** [hashicorp/terraform-provider-azurerm#25950]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

The `azurerm_kubernetes_service_versions` [data source ](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_service_versions) should have support for selecting stable version, not just latest version as these are different between terraform and the console

Right now if you want to use the data source the latest_version == `1.29.4` at time of creating this issue but the default version is `1.28.9`. There's no way to easily select default without knowing what the prefix should be every time you deploy a AKS cluster

```
data "azurerm_kubernetes_service_versions" "current" {
  location = var.location
  include_preview = false
}

output "azure_aks_versions" {
  value = data.azurerm_kubernetes_service_versions.current
}
```

```
  + aks_versions = {
      + id              = "/subscriptions/<SUBSCRIPTION>/providers/Microsoft.ContainerService/locations/<REGION>"
      + include_preview = false
      + latest_version  = "1.29.4"
      + location        = "<region>"
      + timeouts        = null
      + version_prefix  = null
      + versions        = [
          + "1.29.4",
          + "1.29.2",
          + "1.28.9",
          + "1.28.5",
          + "1.27.9",
          + "1.27.7",
        ]
    }
```

In the console `1.28.9` is the default and this should be an option within terraform instead of needing to pass in prefix which requires knowing Azures current stable/default. In GCP/GKE they have a similar option `data.google_container_engine_versions.gke_versions.release_channel_default_version["STABLE"]` which would be great to have in AKS as we always want to deploy stable/default that's available in console in terraform deployments.

<img width="706" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/12011826/33d937de-48eb-42f2-a2a2-d009c9ca71a0">

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_service_versions

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/kubernetes_service_versions

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

**Comment by aristosvo** [comment]
Hi @ianarsenault!

I filed a PR for it, will keep you updated.
