### ISSUE TITLE
Support for `azurerm_application_gateway` Basic SKU (Preview)

### ISSUE THREAD

**Issue by tedsmitt** [hashicorp/terraform-provider-azurerm#25973]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

As per the announcement for the [Application Gateway Basic SKU](https://azure.microsoft.com/en-us/updates/public-preview-azure-application-gateway-v2-basic-sku/#:~:text=The%20Application%20Gateway%20Basic%20SKU,require%20advanced%20traffic%20management%20features.) (Preview) - implement `Basic` as an option for the `azurerm_application_gateway` property `sku.name` and `sku.tier`

Following feature will be required to be registered in the subscription:
`az feature register --name AllowApplicationGatewayBasicSku --namespace Microsoft.Network`

Some changes to the `sku.capacity` and `autoscale_configuration` logic/defaults may need to be made as well, since the `Basic` SKU doesn't support this

I'm happy to look at implementing this, is the process to update to [go-azure-sdk](https://github.com/hashicorp/go-azure-sdk) first, and then implement this in the provider?

### New or Affected Resource(s)/Data Source(s)

`azurerm_application_gateway`

### Potential Terraform Configuration

```hcl
resource "azurerm_application_gateway" "this" {
  name                = "${var.prefix}-agw"
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location

  sku {
    name = "Basic"
    tier = "Basic"
  }
...
```

### References
https://azure.microsoft.com/en-us/updates/public-preview-azure-application-gateway-v2-basic-sku/#:~:text=The%20Application%20Gateway%20Basic%20SKU,require%20advanced%20traffic%20management%20features

**Comment by tedsmitt** [comment]
I am writing a PR for this feature, should have it ready for review either by the end of tomorrow.

**Comment by tedsmitt** [comment]
Upgrade of the `applicationgateways` API version is required

`
Application Gateway Name: "acctestag-240515175529330176"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: ApplicationGatewayPropertyNotSupportedApiVersionTooOld: Specified api-version '2022-07-01' does not support property 'Basic' in context '/subscriptions/21701392-9f9d-45f6-9283-8a4d90e5f9ef/resourceGroups/acctestRG-240515175529330176/providers/Microsoft.Network/applicationGateways/acctestag-240515175529330176'. Use at least api-version '2023-02-01' or remove property 'Basic' from the request body.
`

This might be more work than initially expected 😅

**Comment by tedsmitt** [comment]
Pending https://github.com/hashicorp/terraform-provider-azurerm/pull/26776 and release of 4.0

**Comment by Karl-jurvanen** [comment]
Any news on this, now that 4.0 is out?

**Comment by t-l-k** [comment]
@tedsmitt @rcskosir normally I'd consider an `azapi` resource when the required functionality isn't provided in `azurerm`, but for this resource, its so complicated! `Standard_v2` SKU brings a lot of excess features surplus to requirements and at a hefty price, in comparison to `Basic`. Can we remove the `blocked` label now given the following is merged?

- #26776

**Comment by tedsmitt** [comment]
https://github.com/hashicorp/terraform-provider-azurerm/pull/27440 Submitted
