### ISSUE TITLE
azurerm_container_app_job - 'cannot remove secrets from Container Apps at this time due to a limitation in the Container Apps Service'

### ISSUE THREAD

**Issue by charliesurman** [hashicorp/terraform-provider-azurerm#25994]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When deploying a container app job, you get the following error when trying to remove a secret:

`│ Error: cannot remove secrets from Container Apps at this time due to a limitation in the Container Apps Service. Please see https://github.com/microsoft/azure-container-apps/issues/395 for more details`

This was changed/resolved for the container app resource #24945 I am hoping the same can occur for container app jobs.

Thank you

### New or Affected Resource(s)/Data Source(s)

azurem_container_app_job

### References

**Related issue/PR**
https://github.com/hashicorp/terraform-provider-azurerm/issues/24945
https://github.com/hashicorp/terraform-provider-azurerm/pull/25743

**Comment by Botje** [comment]
The change for v3.107.0 includes a fix for this issue but it seems this not make the changelog.
