### ISSUE TITLE
`azurerm_data_protection_backup_instance_kubernetes_cluster` docs configuration doesn't work

### ISSUE THREAD

**Issue by peteroneilljr** [hashicorp/terraform-provider-azurerm#25999]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.0

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_data_protection_backup_instance_kubernetes_cluster

### Terraform Configuration Files

```txt
The configuration provided in the docs is fill with test resources that don't link to anything.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_instance_kubernetes_cluster
```

For example the following references.
```hcl
  depends_on = [
    azurerm_role_assignment.test_extension_and_storage_account_permission,
    azurerm_role_assignment.test_vault_msi_read_on_cluster,
    azurerm_role_assignment.test_vault_msi_read_on_snap_rg,
    azurerm_role_assignment.test_cluster_msi_contributor_on_snap_rg,
    azurerm_role_assignment.test_vault_msi_snapshot_contributor_on_snap_rg,
    azurerm_role_assignment.test_vault_data_operator_on_snap_rg,
    azurerm_role_assignment.test_vault_data_contributor_on_storage,
  ]
```

These are pointed at a `test` resource that doesn't exist.

```hcl
resource "azurerm_role_assignment" "test_vault_msi_snapshot_contributor_on_snap_rg" {
  scope                = azurerm_resource_group.snap.id
  role_definition_name = "Disk Snapshot Contributor"
  principal_id         = azurerm_data_protection_backup_vault.test.identity[0].principal_id
}

resource "azurerm_role_assignment" "test_vault_data_operator_on_snap_rg" {
  scope                = azurerm_resource_group.snap.id
  role_definition_name = "Data Operator for Managed Disks"
  principal_id         = azurerm_data_protection_backup_vault.test.identity[0].principal_id
}

resource "azurerm_role_assignment" "test_vault_data_contributor_on_storage" {
  scope                = azurerm_storage_account.test.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = azurerm_data_protection_backup_vault.test.identity[0].principal_id
}
```

### Debug Output/Panic Output

```shell
You can't reference resources that don't exist.
```

### Expected Behaviour

The example should show a minimal viable configuration to create the resource.

### Actual Behaviour

Resource does not create with provided configuration.

### Steps to Reproduce

terraform apply

### Important Factoids

n/a

### References

The following documentation is pretty new, and I believe someone may have uploaded their test configuration instead of a working example. There are many references to test resources that don't exist in this configuration that will cause the configuration to fail to deploy.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_protection_backup_instance_kubernetes_cluster

This reference should be cleaned up so that it is just the minimum resources needed to create the object.

**Comment by Chambras** [comment]
@peteroneilljr Nice catch! I will try to submit a PR soon to update the sample in the documentation.
