### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert fails with 400 Bad Request due to DraftClientException

### ISSUE THREAD

**Issue by joshvito** [hashicorp/terraform-provider-azurerm#26032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.104.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
// using example from docs @
// https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert
resource "azurerm_monitor_scheduled_query_rules_alert" "dependency" {
  name                = "RESOURCE_NAME"
  location            = "eastus2"
  resource_group_name = var.this_resource_group_name

  // actual value added, but comes from an output from module.app_insights_alerts
  action {
    action_group = ["/subscriptions/<sub_GUID>/resourceGroups/<this_resource_group_name>/providers/Microsoft.Insights/actionGroups/ag-RESOURCE_NAME"]
  }

  data_source_id = "/subscriptions/<sub_GUID>/resourceGroups/<this_resource_group_name>/providers/Microsoft.Insights/components/appi-RESOURCE_NAME"
  description    = "Alert when dependency failures rise, but filter out HEAD requests that fail. 404s to Blob HEAD requests are expected."
  enabled        = true
  query = format(<<-QUERY
  dependencies
  | where success == false AND name !startswith "HEAD"
  | count
  QUERY
  )
  severity    = 1
  frequency   = 10
  time_window = 15
  trigger {
    operator  = "GreaterThan"
    threshold = 90
  }
  depends_on = [module.app_insights_alerts]
}
```

### Debug Output/Panic Output

```shell
│ Scheduled Query Rule Name: "RESOURCE_NAME"): unexpected status 400 (400 Bad Request) with error: DraftClientException: The request had some invalid properties Activity ID: b1d537ed-6daf-4239-a59c-0cc6f741a779.
```

### Expected Behaviour

Expects the resource to be created

### Actual Behaviour

Fails on Apply

### Steps to Reproduce

terraform apply

**Comment by teowa** [comment]
Hi @joshvito, thanks for submitting this. The `azurerm_monitor_scheduled_query_rules_alert` [source code](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_scheduled_query_rules_alert_resource.go) has no change in last 4 months, this might due to service backend change.

**Comment by joshvito** [comment]
We've used it in the distant past successfully, but that was more than 4 month ago.

**Comment by GaryFail** [comment]
We also got this error but it turned out that our query wasn't valid for the scope, for example we were searching exceptions but the scope was the underlying log analytics workspace not application insights. We also used the v2 resource `azurerm_monitor_scheduled_query_rules_alert_v2`

**Comment by joshvito** [comment]
This turned out to be a bad query as @GaryFail mentioned.

Look at my original post closely...

This is the working query: ><

```
query = format(<<-QUERY
  dependencies
  | where success == false and name !startswith "HEAD"
  | count
  QUERY
```

**Comment by rcskosir** [comment]
@joshvito Thank you for taking the time to open this issue. Since the issue turned out to be a bad query are we able to close this issue? Thanks!

**Comment by joshvito** [comment]
Closing the issue is appropriate. Probably the error message returned from azure could be better, but that's outside scope of this project.
