### ISSUE TITLE
Support for flex consumption in azurerm_service_plan and related resources

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-azurerm#26043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Flex Consumption plans are now in public preview, would like support for these resources without using the azapi provider.

I believe the service_plan validation must allow the "FC1" sku_name, apart from that we need new optional attributes om the `azurerm_linux_function_app` and `azurerm_windows_function_app`

Attributes should be available in the following ARM template versions
Microsoft.Web/serverfarms@2023-12-01
Microsoft.Web/sites@2023-12-01

### New or Affected Resource(s)/Data Source(s)

azurerm_service_plan azurerm_linux_function_app azurerm_windows_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_service_plan" "example" {
  name                = "example"
(...)
  sku_name            = "FC1"
}

resource "azurerm_x_function_app" "example" {
  name                = "example-windows-function-app"
(..)
  scale_and_concurrency = { # optional
    maximum_instance_count = #1 to 1000?  # "Scale out further – The default scale limit set by client tools is 100, but this can be changed up to 1000 instances per app"
    instance_memory_mb = # 2048 or 4096 supported
  },
}
```

### References

https://techcommunity.microsoft.com/t5/apps-on-azure-blog/announcing-public-preview-of-azure-functions-flex-consumption/ba-p/4139028
https://github.com/Azure-Samples/azure-functions-flex-consumption-samples/blob/main/IaC/terraform/main.tf

**Comment by AayushbajajCAW** [comment]
Any Update regarding when this feautre might be added @xiaxyi

**Comment by s-nakagaki** [comment]
The premium sku is so expensive for micro-architecture. We really want Flex Consumption plan so much.

**Comment by oWretch** [comment]
Above PR adds support for the Flex Consumption plan. The Maximum Instance Count property on the function app is supported (`app_scale_limit`) but the Instance Memory property not exposed in the Azure API yet - we need a new preview API for this.
