### ISSUE TITLE
mysql flexible server replica fails to create

### ISSUE THREAD

**Issue by vakaobr** [hashicorp/terraform-provider-azurerm#26040]
The issue mentioned on https://github.com/hashicorp/terraform-provider-azurerm/issues/21763 continues to happen on the newer version of the provider.

Even including the `wait` block the replica fails to be created, it reports the server ID was being not specified (even if it got specified correctly, from a `data` or `resource` block) - I removed the `wait` on the second and subsequent runs since the main server was already created longer than 1 hour.

The code to create the replica came from a module on our side.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.104.2

### Affected Resource(s)/Data Source(s)

azurerm_mysql_flexible_server

### Terraform Configuration Files

```hcl
data "azurerm_mysql_flexible_server" "server" {
  name                = var.name
  resource_group_name = var.create_rg ? azurerm_resource_group.server[0].name : var.resource_group_name
  depends_on          = [azurerm_mysql_flexible_server.server]
}

resource "azurerm_mysql_flexible_server" "server_replica" {
  count                  = lower(var.environment) == "prod" && var.enable_replication ? 1 : 0
  name                   = format("%s-repl", var.name)
  location               = var.replica_location
  resource_group_name    = var.create_rg ? azurerm_resource_group.server_replica[0].name : var.resource_group_name_replica
  administrator_login    = var.admin_username
  administrator_password = var.create_password ? random_password.admin_password[0].result : var.admin_password
  sku_name               = var.sku_name
  create_mode            = "Replica"
  source_server_id       = data.azurerm_mysql_flexible_server.server.id
  version                = var.db_version
  backup_retention_days  = var.backup_retention_days
  # Right now, we need to choose if we use this (and allow the traffic only for VNET's) or we use the firewall rules
  delegated_subnet_id = var.use_peered_vnets_only ? azurerm_subnet.server_replica[0].id : null
  private_dns_zone_id = var.use_peered_vnets_only ? azurerm_private_dns_zone.server[0].id : null

  #ts:skip=AC_AZURE_0407
  geo_redundant_backup_enabled = false # To keep the costs down, we disable this by default
  tags                         = merge({ role = "replica" }, local.full_tags)

  storage {
    auto_grow_enabled = false
    size_gb           = var.storage_gb
  }

  # enable encryption out of the box are not possible since the AzureRM provider are broken in this part when comes to MySQL flexible servers
  dynamic "customer_managed_key" {
    for_each = var.enable_encryption ? [1] : []
    content {
      key_vault_key_id                  = azurerm_key_vault_key.server.id
      primary_user_assigned_identity_id = azurerm_user_assigned_identity.server.id
    }
  }

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.server_replica[0].id]
  }

  # prevent the possibility of accidental data loss
  lifecycle {
    prevent_destroy = true
    # We are not enabling HA, so lets ignore any changes azure shows for zones
    ignore_changes = [
      zone
    ]
  }

  depends_on = [
    module.peering_main_server_and_replica,
    azurerm_virtual_network.server_replica[0],
    azurerm_subnet.server_replica[0]
  ]
}
```

### Debug Output/Panic Output

```
Error: creating Flexible Server (Subscription: "<my subscription id>" Resource Group Name: "<rg name>" Flexible Server Name: "<server name>"): performing Create: unexpected status 400 (400 Bad Request) with error: InvalidParameterValue: Invalid value given for parameter SourceServerId. Specify a valid parameter value.
```

### Expected Behaviour

The replica server get created successfully. 

### Steps to Reproduce

terraform apply

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/21763

**Comment by carlossouzadev** [comment]
👏👏👏

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. It's by service API design. Suggest file issue on https://github.com/Azure/azure-rest-api-specs/issues or file Azure Support Ticket.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. On review, we’ve determined that the described behavior is as intended (see above comment), as such I am going to mark this issue as closed. If you file an issue upstream or am Azure Support Ticket, feel free to add that here.
