### ISSUE TITLE
not specifying ticket block in azurerm_pim_eligible_role_assignment resource forces recreation

### ISSUE THREAD

**Issue by mysteq** [hashicorp/terraform-provider-azurerm#26050]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.104.2

### Affected Resource(s)/Data Source(s)

azurerm_pim_eligible_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_pim_eligible_role_assignment" "ra_eligible" {
  scope              = data.azurerm_subscription.sub.id
  role_definition_id = "${data.azurerm_subscription.sub.id}${data.azurerm_role_definition.ra_contributor.id}"
  principal_id       = azuread_group.portal_operators.object_id

  schedule {
    start_date_time = time_static.time.rfc3339
    expiration {
      duration_days = 356
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

No changes

### Actual Behaviour

Not spesifying a ticket block with "ticket {}" forces recreation of the resource each run.

**Comment by manicminer** [comment]
Maintainer note: see also #26023 which includes a report of this bug
