### ISSUE TITLE
Support for azurerm_maintenance_assignment_dynamic_scope resource

### ISSUE THREAD

**Issue by kamstys** [hashicorp/terraform-provider-azurerm#26071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hi, is it possible to add subscription field on filter at scope configuration? For that moment is taking automatically machines from subscription where maintanance is deploy. Nice would have if will be possible to add machines from various subscription.

### New or Affected Resource(s)/Data Source(s)

azurerm_maintenance_assignment_dynamic_scope

### Potential Terraform Configuration

```hcl
resource "azurerm_maintenance_assignment_dynamic_scope" "example" {
name = "example"
maintenance_configuration_id = azurerm_maintenance_configuration.example.id

filter {
locations = ["West Europe"]
os_types = ["Windows"]
subscriptions = ["sub1", "sub2", "sub3"]
resource_groups = [azurerm_resource_group.example.name]
resource_types = ["Microsoft.Compute/virtualMachines"]
tag_filter = "Any"
tags {
tag = "foo"
values = ["barbar"]
}
}
}
```

**Comment by teowa** [comment]
Hi @kamstys , thanks for submitting this! Azurerm provider relys on Azure REST API to work, however I have checked Azure REST API does not support filter subscription now, so we should not able to support this here. 
https://github.com/Azure/azure-rest-api-specs/blob/162fb3af1af3a6e166ab16b8f2684c31a6e6bd0b/specification/maintenance/resource-manager/Microsoft.Maintenance/stable/2023-04-01/Maintenance.json#L2291-L2333

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
