### ISSUE TITLE
CosmosDB terraform provider, enable_automatic_failover doesn't exist in Argument references

### ISSUE THREAD

**Issue by sijjay** [hashicorp/terraform-provider-azurerm#26079]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

latest

### AzureRM Provider Version

latest

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

-

### Actual Behaviour

-

### Steps to Reproduce

search for enable_automatic_failover here https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account.html.
Youi will not find this parameter in the Argument references

### Important Factoids

-

### References

-

**Comment by stephybun** [comment]
Thanks for opening this issue @sijjay.

`enable_automatic_failover` is deprecated and has been superseded by `automatic_failover_enabled`. 

We always remove deprecated properties that are going to be removed in the next major version of the provider from the documentation to discourage users from setting them.

I'm going to close this issue since this is expected.
