### ISSUE TITLE
azurerm_application_insights_standard_web_test missing 

### ISSUE THREAD

**Issue by eltimmo** [hashicorp/terraform-provider-azurerm#26076]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The resource `azurerm_application_insights_standard_web_test` is missing the verbs `HEAD` and `OPTION`.
When I try and use HEAD I get the error below, though it is present and working in the portal.

__expected_ request.0.http_verb to be one of ["GET" "POST" "PUT" "PATCH" "DELETE"], got HEAD__

### New or Affected Resource(s)/Data Source(s)

azurerm_application_insights_standard_web_test

**Comment by tombuildsstuff** [comment]
Looks to be a validation issue, rather than coming from SDK constants: https://github.com/hashicorp/terraform-provider-azurerm/blob/03691480bbbe8c627e72270480df72131488a372/internal/services/applicationinsights/application_insights_standard_webtests_resource.go#L164

**Comment by tombuildsstuff** [comment]
Fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/26077
