### ISSUE TITLE
Row Delimiter does not have a default value for azurerm_data_factory_dataset_delimited_text

### ISSUE THREAD

**Issue by tpttomt** [hashicorp/terraform-provider-azurerm#26096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

3.5.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_dataset_delimited_text

### Terraform Configuration Files

```hcl
# This config hasn't been applied
provider azurerm {
  version = "3.5.0"
  features {}
}

resource azurerm_resource_group example {
  name     = "example"
  location = "uksouth"
}

resource azurerm_storage_account example {
  name                      = "example"
  resource_group_name       = azurerm_resource_group.example.name
  location                  = azurerm_resource_group.example.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "GRS"
  enable_https_traffic_only = true
}

resource azurerm_storage_container example {
  name                  = "example"
  storage_account_name  = azurerm_storage_account.example.name
  container_access_type = "private"
}

resource azurerm_data_factory example {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
}

resource azurerm_data_factory_linked_service_azure_blob_storage example {
  name                     = "example"
  resource_group_name      = azurerm_resource_group.example.name
  data_factory_name        = azurerm_data_factory.example.name
  integration_runtime_name = "AutoResolveIntegrationRuntime"
  connection_string        = azurerm_storage_account.example.primary_connection_string
}

resource azurerm_data_factory_dataset_delimited_text example {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  data_factory_name   = azurerm_data_factory.example.name
  linked_service_name = azurerm_data_factory_linked_service_azure_blob_storage.example.name
  parameters          = {
    "subfolder" = "" # Map value sets parameter default value
  }

  first_row_as_header = true

  schema_column {
    name = "example"
    type = "String"
  }

  azure_blob_storage_location {
    container            = azurerm_storage_container.example.name
    path                 = "@dataset().subfolder"
    dynamic_path_enabled = true
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The row delimiter value should be:

![Correct default value](https://github.com/hashicorp/terraform-provider-azurerm/assets/170732866/b6f6ff93-4843-4d22-b9c6-734d2a00b99c)

### Actual Behaviour

However it shows as:
![Incorrect default value](https://github.com/hashicorp/terraform-provider-azurerm/assets/170732866/d9c549ef-7480-4b0f-a565-42eed6db5c55)

### Steps to Reproduce

terraform apply

### Important Factoids

No

### References

https://github.com/lonegunmanb/terraform-provider-azurerm/blob/e72a140a83c7c13912ee964335e1dd2bad805e2f/internal/services/datafactory/data_factory_dataset_delimited_text_resource.go#L170C1-L174C6

https://github.com/hashicorp/terraform-provider-azurerm/issues/13545

**Comment by rcskosir** [comment]
@tpttomt Thanks for taking the time to open this issue. In your terraform config files the azure provider version is listed as 2.77.0. Have you tried a more recent version of the provider? The PR that closed the referenced issue was added to the 3.5.0 version of the provider and the current latest version of the provider is 3.105.0.

**Comment by tpttomt** [comment]
Hi there - I am actually using 3.5.0, sorry I have just taken the example from a previous github issue. 

Can you see in my references https://github.com/lonegunmanb/terraform-provider-azurerm/blob/e72a140a83c7c13912ee964335e1dd2bad805e2f/internal/services/datafactory/data_factory_dataset_delimited_text_resource.go#L170C1-L174C6 (here) that there is no default for row_delimiter.

**Comment by mybayern1974** [comment]
Thank @tpttomt for opening this issue. By regarding this issue might be duplicate with #22447, I'm closing this one in favor of the previously create one that people can subscribe. Or let me know if you assume these two issues are talking about different stories then I'm happy to re-evaluate and reactive this issue.
