### ISSUE TITLE
Setting TransactionOptimized on azurerm_storage_share.default returns Error

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#26095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_share

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "default" {

  name = local.trimmed-name

  resource_group_name = azurerm_resource_group.default.name
  location            = azurerm_resource_group.default.location

  account_kind             = "FileStorage"
  account_tier             = "Premium"
  account_replication_type = "LRS"

  public_network_access_enabled   = false
  allow_nested_items_to_be_public = false

  azure_files_authentication {
    directory_type = "AADDS"
  }

  network_rules {
    bypass = [
      "AzureServices",
    ]
    default_action = "Deny"
  }

  tags = local.tag-map
  lifecycle {
    ignore_changes = [
      tags,
    ]
  }
}

resource "azurerm_storage_share" "default" {

  name = "fslogix"

  access_tier = "TransactionOptimized"

  storage_account_name = azurerm_storage_account.default.name

  quota = 100 # Min 100GB for premium tier

  lifecycle {
    ignore_changes = [
      quota,
    ]
  }
}
```
```


### Debug Output/Panic Output

```shell
https://gist.github.com/DevopsMercenary/d0b436ad2f4d49cd225a82ad70e76930
```

### Expected Behaviour

Expected the storage account fileshare to be created and set to TransactionOptimized.

This happened on Create as well as update

### Actual Behaviour

Error returned was

```
│ Error: updating Access Tier for File Share "fslogix" (Account "Account \"cmdevuserprofilestoragec\" (IsEdgeZone false / ZoneName \"\" / Subdomain Type \"file\" / DomainSuffix \"core.windows.net\")"): executing request: unexpected status 400 (400 The value for one of the HTTP headers is not in the correct format.) with InvalidHeaderValue: The value for one of the HTTP headers is not in the correct format.
│ RequestId:e0ccd189-801a-0002-66d5-adf2c9000000
│ Time:2024-05-24T12:22:49.6611219Z
│
│   with azurerm_storage_share.default,
│   on file-share.tf line 4, in resource "azurerm_storage_share" "default":
│    4: resource "azurerm_storage_share" "default" {
│
╵
```

**Comment by Chambras** [comment]
@DevopsMercenary I think it is working the way it should be. If you are using General Purpose V2 (GpV2) account can choose between TransactionOptimized (default), Hot, and Cool. If you use FileStorage account, you can choose Premium.
In your case you are setting `account_kind` to `FileStorage` so that is why is failing.
You can find more information [here](https://learn.microsoft.com/en-us/cli/azure/storage/share-rm?view=azure-cli-latest#az-storage-share-rm-create-optional-parameters)

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/664891/87f1aba7-0d6a-4f2c-8ffd-048395530cde)

Maybe we can improve the documentation around this.

**Comment by magodo** [comment]
Thanks @Chambras! I can verify that the error is caused by the `access_tier` setting as mentioned above, with the following config:

```hcl
provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}

resource "azurerm_resource_group" "default" {
  name     = "mgd-test-storage"
  location = "westeurope"
}

resource "azurerm_storage_account" "default" {
  name                     = "mgdteststorageaccnt1"
  resource_group_name      = azurerm_resource_group.default.name
  location                 = azurerm_resource_group.default.location
  account_kind             = "FileStorage"
  account_tier             = "Premium"
  account_replication_type = "LRS"
}

resource "azurerm_storage_share" "default" {
  name                 = "fslogix"
  access_tier          = "Premium" # TransactionOptimized causes error
  storage_account_name = azurerm_storage_account.default.name
  quota                = 100
}
```
