### ISSUE TITLE
Max value of frequency of azurerm_monitor_scheduled_query_rules_alert should be 2880

### ISSUE THREAD

**Issue by xinfli** [hashicorp/terraform-provider-azurerm#26100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

Azure portal allow to execute query every 2 days (2880 minutes) for `Log search alert rule`:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1798198/7c9ffe52-0595-4f53-ab06-499cb5144640)

But when create a `Log search alert rule` with `azurerm_monitor_scheduled_query_rules_alert`, the allowed range for frequency is only `5-1440`:
```terraform
resource "azurerm_monitor_scheduled_query_rules_alert" "my_query_alert_rule" {
  # ...
  frequency      = 60 * 24 * 2 # Every 2 days
  time_window    = 60 * 24
  # ...
}
```

Got error below:
```
Error: expected frequency to be in the range (5 - 1440), got 2880
   ...
113:   frequency      = 60 * 24 * 2 # Every 2 days
```

Tried create with `azurerm_monitor_scheduled_query_rules_alert_v2`, but it allowed for max 1 day only:
```terraform
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "my_query_alert_rule_v2" {
  # ...
  evaluation_frequency = "P2D"
  window_duration      = "P1D"
  # ...
}
```

Got error below:
```
Error: expected evaluation_frequency to be one of ["PT1M" "PT5M" "PT10M" "PT15M" "PT30M" "PT45M" "PT1H" "PT2H" "PT3H" "PT4H" "PT5H" "PT6H" "P1D"], got P2D
  ...
131:   evaluation_frequency = "P2D"
```

### Terraform Version

1.8.4

### AzureRM Provider Version

3.104.2

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert, azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.104.2"
    }
  }
  backend "azurerm" {
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
}
```

### Debug Output/Panic Output

```shell
# For azurerm_monitor_scheduled_query_rules_alert
Error: expected frequency to be in the range (5 - 1440), got 2880
  ...
113:   frequency      = 60 * 24 * 2 # Every 2 days

# For azurerm_monitor_scheduled_query_rules_alert_v2
Error: expected evaluation_frequency to be one of ["PT1M" "PT5M" "PT10M" "PT15M" "PT30M" "PT45M" "PT1H" "PT2H" "PT3H" "PT4H" "PT5H" "PT6H" "P1D"], got P2D
  ...
131:   evaluation_frequency = "P2D"
```

### Expected Behaviour

Should allow max 2 days (2880 minutes) for frequency of azurerm_monitor_scheduled_query_rules_alert and azurerm_monitor_scheduled_query_rules_alert_v2 as same as Azure portal.

### Actual Behaviour

Only allow 1 day (1440 minutes) for frequency of azurerm_monitor_scheduled_query_rules_alert and azurerm_monitor_scheduled_query_rules_alert_v2

**Comment by Chambras** [comment]
@xinfli good catch! I will take a look!

**Comment by teowa** [comment]
Hi @xinfli , thanks for submitting this!
This is API limitation that frequency can only support up to `1440`, 
```
unexpected status 400 (400 Bad Request) with error: InvalidRequestContent: The request content was invalid and could not be deserialized: 'Frequency of 2880 minutes is not supported. Supported Frequencies are: 1, 5, 10, 15, 30, 45, 60, 120, 180, 240, 300, 360, 1440' 
```
 the Portal `peroid (in minutes)=2880` in the given screenshot is mapping to the `azurerm_monitor_scheduled_query_rules_alert_v2.window_duration` or `azurerm_monitor_scheduled_query_rules_alert.time_window`. So you may set
```
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "my_query_alert_rule_v2" {
  # ...
  evaluation_frequency = "P1D"
  window_duration      = "P2D"
  # ...
}
```

**Comment by Chambras** [comment]
Hi @xinfli I think there is also a confusion between, frequency/evaluation_frequency , and time_window/window_duration. time_window/window_duration is the period of time on which  the Alert query will be executed, this supports up to 2 days. frequency/evaluation_frequency is how often the scheduled query rule is evaluated; this supports up to 1 day.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @teowa‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
