### ISSUE TITLE
Support for AKS Web Application Routing - Private DNS zone and multiple zones

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#26110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

At the moment the web_app_routing block of aks only support a public DNS zone id. This feature request is to add the support for private DNS zone.

Note the current implementation only support 1 dns zone id when the azapi can support up to 5 dns zone ids.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster - web_app_routing

### Potential Terraform Configuration

```hcl
web_app_routing {
 dns_zone_ids = [
  "resource id of the private DNS zone",
  "resource id of the public dns zone"
 ]
}
```

### References

version 105 is using the version 2023-09-02-preview
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2023-09-02-preview/managedclusters?pivots=deployment-language-terraform#managedclusteringressprofilewebapprouting-2

version 2024-02-01 is supporting both public and private
https://learn.microsoft.com/en-us/azure/templates/microsoft.containerservice/2024-02-01/managedclusters?pivots=deployment-language-terraform#managedclusteringressprofilewebapprouting-2

**Comment by stephybun** [comment]
Just as a note @LaurentLesle. The AKS resource already supports private DNS zone IDs in case you're wanting to take advantage of that today. But we are missing support for supplying multiple DNS zone IDs.

https://github.com/hashicorp/terraform-provider-azurerm/blob/9206b818e64da211b844a8b17b260d795597f18a/internal/services/containers/kubernetes_cluster_resource.go#L422-L435

**Comment by LaurentLesle** [comment]
Yes correct. This issue is to request the multiple dns zone IDs and also
private dns zones which does not work with the current version of the sdk

**Comment by ms-henglu** [comment]
Thanks @LaurentLesle for taking time to report this issue. I'll work on this feature.
