### ISSUE TITLE
azurerm_storage_data_lake_gen2_filesystem - Apply fails after version upgrade

### ISSUE THREAD

**Issue by YukiNakamuraAbel** [hashicorp/terraform-provider-azurerm#26118]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.97

### Affected Resource(s)/Data Source(s)

azurerm_storage_data_lake_gen2_filesystem

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "dev" {
    name                     = "adls-dev"
    resource_group_name      = "rg-dev"
    location                 = japaneast
    account_tier             = "Standard"
    account_replication_type = "LRS"
    account_kind             = "StorageV2"
    access_tier              = "Hot"
    is_hns_enabled           = "true"
    allow_nested_items_to_be_public = "false"

    blob_properties {
      delete_retention_policy {
        days = 7
      }
      container_delete_retention_policy {
        days = 7
      }
    }
    tags = var.tags
}

resource "azurerm_storage_data_lake_gen2_filesystem" "mdm_delivery_container" {
    name               = "mdm-delivery-container"
    storage_account_id = azurerm_storage_account.dev.id
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: expected the subdomain type to be "dfs" but got "blob"
│ 
│   with azurerm_storage_data_lake_gen2_filesystem.mdm_delivery_container,
│   on main.tf line 1699, in resource "azurerm_storage_data_lake_gen2_filesystem" "mdm_delivery_container":
│ 1699: resource "azurerm_storage_data_lake_gen2_filesystem" "mdm_delivery_container" {
│ 
╵
```

### Expected Behaviour

Successful terraform provisioning and state file update

### Actual Behaviour

Terraform applied the changes, but showed as a failure and did not update the state file

### Steps to Reproduce

1.Create a resource with AzureRM Provider version 3.88
2.Change to AzureRM Provider Version 3.97
3.Terraform apply

### References

I found the comment below, but I want to raise it to version 3.97 or higher.
https://github.com/hashicorp/terraform-provider-azurerm/pull/25262#issuecomment-2049458653

**Comment by Chambras** [comment]
Hi @YukiNakamuraAbel Have you tried with the latest version 3.105.0?

**Comment by YukiNakamuraAbel** [comment]
Hi @Chambras I tried version 3.105.0 and got the same error.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. I tried to follow your steps but seems I can't repro this issue on my local. Could you try below tf config that is similar with yours to see if the issue still exists? Thanks.

```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-sa-test01"
  location = "eastus"
}

resource "azurerm_storage_account" "test" {
  name                            = "acctestadlsdev"
  resource_group_name             = azurerm_resource_group.test.name
  location                        = azurerm_resource_group.test.location
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  account_kind                    = "StorageV2"
  access_tier                     = "Hot"
  is_hns_enabled                  = "true"
  allow_nested_items_to_be_public = "false"

  blob_properties {
    delete_retention_policy {
      days = 7
    }

    container_delete_retention_policy {
      days = 7
    }
  }

  tags = {
    env = "test2"
  }
}

resource "azurerm_storage_data_lake_gen2_filesystem" "mdm_delivery_container" {
  name               = "mdm-delivery-container"
  storage_account_id = azurerm_storage_account.test.id
}
```

**Comment by YukiNakamuraAbel** [comment]
Hi, @neil-yechenwei .
I tried using the tf configuration you provided, but I got the same error.
The reason it doesn't reproduce locally may be because the resource was created before 3.88.
Please try updating in the following order: 3.58 → 3.69 → 3.88 → 3.97

**Comment by YukiNakamuraAbel** [comment]
The error was resolved by executing the following command.
This may be due to the fact that URL in blob format were registered as ID in previous versions.
`terraform state rm `
`terraform import`
