### ISSUE TITLE
azurerm_storage_account cross_tenant_replication_enabled should probably default to false

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#26127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently for the `azurerm_storage_account` resource the provider sets `cross_tenant_replication_enabled` to `true` by default.<sub>1</sub>

According to MS documentation<sub>2</sub>, as of Dec 15, 2023 the API creates storage accounts with that value as `false`

The provider should be updated to reflect the default behavior of the API and the portal.

### New or Affected Resource(s)/Data Source(s)

azurerm_storage_account

### References

1 . https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#cross_tenant_replication_enabled
2. https://learn.microsoft.com/en-us/azure/storage/blobs/object-replication-prevent-cross-tenant-policies?tabs=portal#remediate-cross-tenant-object-replication

**Comment by Wikiwix** [comment]
#26962 already implemented this, so I believe that this can be closed

**Comment by man0s** [comment]
yes, this can be closed. It's already implemented as @Wikiwix mentioned.

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved as of #26962. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
