### ISSUE TITLE
Error: Data collection rule is not valid for kind 'WorkspaceTransforms' The rule of kind 'WorkspaceTransforms' must have exactly one Log Analytics workspace destination (and no other).

### ISSUE THREAD

**Issue by Nazargora** [hashicorp/terraform-provider-azurerm#26138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

I created data collections rule and log analytics workspace via terraform 
and I have this error in photo how to fix?
<img width="1643" alt="AAAAAA" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/111236875/d492aad0-1a98-4b65-a950-38cf282e6493">

### Terraform Version

1.5.7

### AzureRM Provider Version

3.1

### Affected Resource(s)/Data Source(s)

azurerm

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "logworkspace" {
  name                = "${var.resource_group_prefix}-${var.application_environment_name}${var.instance_name}-logs"
  location            = var.location
  resource_group_name = data.azurerm_resource_group.apprg.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  #data_collection_rule_id  = 
  #kind = "WorkspaceTransforms"
}



# https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/monitor_data_collection_rule
# kept as a reminder, the az_api version, along ith the null_resource brought the best solution

resource "azurerm_monitor_data_collection_rule" "backendlogs-dcr" {
  name                = "${var.resource_group_prefix}-${var.application_environment_name}-backend-dcr"
  resource_group_name = data.azurerm_resource_group.apprg.name
  location            = var.location
  kind = "WorkspaceTransforms"
  #kind  = "Linux"
  
  destinations {
    log_analytics {
      name = azurerm_log_analytics_workspace.logworkspace.name
      workspace_resource_id = azurerm_log_analytics_workspace.logworkspace.id
    }
  }
  

  data_flow {
    streams       = ["Microsoft-Table-AppServiceConsoleLogs"]
    #destinations  = ["example-destination-log"]
    destinations = ["${azurerm_log_analytics_workspace.logworkspace.name}"]
    output_stream = "Microsoft-AppServiceConsoleLogs"
    transform_kql = "source\n| extend Context = parse_json(ResultDescription)\n| extend Thread_CF = tostring(Context.thread)\n| extend Level_CF = tostring(Context.level)\n| extend Logger_CF = tostring(Context.logger)\n| extend Message_CF = tostring(Context.message)\n| project-away Context,ResultDescription" 
    #"source\n| extend LL_CF = substring(ResultDescription, 12, 34)"
  }
```

### Debug Output/Panic Output

```shell
i try to create via terraform import the same error
```

### Expected Behaviour

I expected that editor transformation was been creating but I have strange error hat I have multiplying destination but I have only one in my code 

### Actual Behaviour

I do not understand why i have this weird error 

### Steps to Reproduce

all is easy  terraform init terraform plan terraform apply. my azure provider 
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3.103.1"
    }
  }
  backend "azurerm" {
    resource_group_name  = "00000"
    storage_account_name = "00000"
    container_name       = "00000"
    key                  = "00000.tfstate"
  }
}
provider "azurerm" {
  subscription_id = "0000000000000000000000000"
  features {}
}

### Important Factoids

Run in Germany West Central

**Comment by teowa** [comment]
Hi @Nazargora , thanks for submitting this!
I tried in my local and found that when updating the destination from one Log Analytic Workspace to another, the API returns the error, could you please share is you error also happen during a update like below? If so, you may need to force recreate the Data Collection Rule through `terraform apply -replace="azurerm_monitor_data_collection_rule.test"` as a workaround.
```

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_monitor_data_collection_rule.test will be updated in-place
  ~ resource "azurerm_monitor_data_collection_rule" "test" {
        id                  = "/subscriptions/xxx/resourceGroups/acctestRG-DataCollectionRule/providers/Microsoft.Insights/dataCollectionRules/acctestmdcr-d"
        name                = "acctestmdcr-d"
        tags                = {}
        # (4 unchanged attributes hidden)

      ~ destinations {
          ~ log_analytics {
              ~ name                  = "test-destination-log" -> "test-destination-log2"
              ~ workspace_resource_id = "/subscriptions/xxx/resourceGroups/acctestRG-DataCollectionRule/providers/Microsoft.OperationalInsights/workspaces/acctest-law-d" -> "/subscriptions/xxx/resourceGroups/acctestRG-DataCollectionRule/providers/Microsoft.OperationalInsights/workspaces/acctest-law-d2"
            }
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
azurerm_monitor_data_collection_rule.test: Modifying... [id=/subscriptions/0b1f6471-1bf0-4dda-aec3-cb9272f09590/resourceGroups/acctestRG-DataCollectionRule/providers/Microsoft.Insights/dataCollectionRules/acctestmdcr-d]
╷
│ Error: updating Data Collection Rule (Subscription: "0b1f6471-1bf0-4dda-aec3-cb9272f09590"
│ Resource Group Name: "acctestRG-DataCollectionRule"
│ Data Collection Rule Name: "acctestmdcr-d"): unexpected status 400 (400 Bad Request) with error: InvalidPayload: Data collection rule is invalid
│
│   with azurerm_monitor_data_collection_rule.test,
│   on main.tf line 25, in resource "azurerm_monitor_data_collection_rule" "test":
│   25: resource "azurerm_monitor_data_collection_rule" "test" {
│
│ updating Data Collection Rule (Subscription: "xxx"
│ Resource Group Name: "acctestRG-DataCollectionRule"
│ Data Collection Rule Name: "acctestmdcr-d"): unexpected status 400 (400 Bad Request) with error: InvalidPayload: Data collection rule is invalid
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @teowa‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
