### ISSUE TITLE
An argument named "by_custom_details" is not expected here.

### ISSUE THREAD

**Issue by mounikakandagadda29** [hashicorp/terraform-provider-azurerm#26133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

0.13.5

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_alert_rule_scheduled

### Terraform Configuration Files

```hcl
resource "azurerm_sentinel_alert_rule_scheduled" "tf-sl-audit-log-cleared-linux-test" {
  name                       = "TF-SL - Audit Log Cleared - Linux-TEST"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.law.id
  display_name               = "TF-SL - Audit Log Cleared - Linux-TEST"
  description                = "Attackers will attempt to erase their tracks and inhibit forensics by clearing logs that contains record of their malicious activity.  This alert detects when the security log is cleared on a Linux host."
  severity                   = "Low"
  tactics                    = ["Execution", "DefenseEvasion"]
  enabled                    = false
  query                      = <<QUERY

Test Query
QUERY

  entity_mapping {

    entity_type = "Host"
    field_mapping {
      identifier  = "HostName"
      column_name = "HostName"
    }
  }

  custom_details = {
    AlertGrouping = "AlertGrouping"
  }


  query_frequency = "PT1H"
  query_period    = "PT1H10M"

  event_grouping {

    aggregation_method = "AlertPerResult"
  }

  incident_configuration {
    create_incident = true
    grouping {
      lookback_duration      = "PT2H"
      entity_matching_method = "Selected"
      by_custom_details = ["AlertGrouping"]

    }
  }
}
```

### Debug Output/Panic Output

```shell
Error: Unsupported argument

  on sl-audit-log-cleared-linux.tf line 49, in resource "azurerm_sentinel_alert_rule_scheduled" "tf-sl-audit-log-cleared-linux-test":
  49:       by_alert_details = ["AlertGrouping"]

An argument named "by_alert_details" is not expected here.
```

### Expected Behaviour

Resource should be created

### Actual Behaviour

Terraform giving error.

### Steps to Reproduce

Just run the provided code and the error message should appear.

**Comment by ziyeqf** [comment]
Hi @mounikakandagadda29, thanks for opening the issue.

I tried the config, my error message is different with yours, could you please check if the error message is for `by_alert_details` instead of `by_custom_details`? 
My error message is :
```
│ Error: Unsupported argument
│ 
│   on main.tf line 61, in resource "azurerm_sentinel_alert_rule_scheduled" "tf-sl-audit-log-cleared-linux-test":
│   61:       by_custom_details      = ["AlertGrouping"]
│ 
│ An argument named "by_custom_details" is not expected here.
```
And per the [azurerm_sentinel_alert_rule_scheduled](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sentinel_alert_rule_scheduled#group_by_custom_details) document, the parameter name is `group_by_custom_details`.

For any further questions please leave comments.
Thanks

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @ziyeqf‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
