### ISSUE TITLE
Support for defining the cluster resource group when creating an ARO cluster

### ISSUE THREAD

**Issue by shane-snyder** [hashicorp/terraform-provider-azurerm#26147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently, there's no way to define the cluster resource group name for an ARO cluster.  This is available via az aro create using the --cluster-resource-group flag, but doesn't appear to be an option with the terraform provider.

### New or Affected Resource(s)/Data Source(s)

azurerm_azurerm_redhat_openshift_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_redhat_openshift_cluster" "example" {
  name                = "examplearo"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  cluster_resource_group_name =
```

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #25529 created by @teowa for this issue.
