### ISSUE TITLE
nested modules fail to preserve tags

### ISSUE THREAD

**Issue by 4c74356b41** [hashicorp/terraform-provider-azurerm#26151]
### Is there an existing issue for this?
- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version
1.5.7

### AzureRM Provider Version
3.76.0

### Affected Resource(s)/Data Source(s)
azurerm_container_registry

### Terraform Configuration Files
```hcl
# ./main.tf
local {
  tags = {
    a = "aa"
    b = "bb"
    c = "cc"
  }
}

module root ./root {
  tags = local.tags
}

# ./root/main.tf
module acr ../acr {
  tags = var.tags
}

# ./acr/main.tf
azurerm_container_registry {
  tags = var.tags
}
```

### Debug Output/Panic Output
```shell
.tags: planned value cty.UnknownVal(cty.Map(cty.String)) does not match config value cty.MapVal(map[string]cty.Value{"Application":cty.String XYZ
```

### Expected Behaviour
infrastructure is up to date

### Actual Behaviour
re-applies tags everytime

**Comment by magodo** [comment]
@4c74356b41 Would you please elaborate more about the reproduce step so that I can better understand what the exact error is?

**Comment by 4c74356b41** [comment]
there is no error, the plan results in unknown reason for the tag update:
<img width="332" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/16194643/7889edda-1651-463f-a897-5f2d2bedad5e">

I've narrowed it down to the specific tag:
```
"Updated" : formatdate("YYYY-MM-DD", timestamp()),
```

any specific reason why this would be unknown any why this would cause tag update when run on the same day?

**Comment by magodo** [comment]
Please checkout https://developer.hashicorp.com/terraform/language/functions/timestamp:

> The result of this function will change every second, so using this function directly with resource attributes will cause a diff to be detected on every Terraform run. We do not recommend using this function in resource attributes, but in rare cases it can be used in conjunction with [the ignore_changes lifecycle meta-argument](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) to take the timestamp only on initial creation of the resource. For more stable time handling, see the [Time Provider](https://registry.terraform.io/providers/hashicorp/time).

**Comment by 4c74356b41** [comment]
sorry, this doesnt make any sense. i'm not using this function directly, i'm wrapping it with format, so the result would always be the same during the same day

**Comment by 4c74356b41** [comment]
https://stackoverflow.com/a/78576127/6067741

```
formatdate("YYYY-MM", plantimestamp())
```
fixes the above
