### ISSUE TITLE
Synapse Administrator role Workspace

### ISSUE THREAD

**Issue by vsotog-Soluciones** [hashicorp/terraform-provider-azurerm#26154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.32.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "synapse_admin" {
  for_each             = data.azuread_user.synapse_admins
  scope                = azurerm_synapse_workspace.default.id
  role_definition_name = "Synapse Administrator"
  principal_id         = each.value.object_id
}
```

### Debug Output/Panic Output

```shell
Error: loading Role Definition List: could not find role 'Synapse Administrator'
```

### Actual Behaviour

╷
│ Error: loading Role Definition List: could not find role 'Synapse Administrator'
│
│   with azurerm_role_assignment.synapse_admin["vsotog@soluciones.cl"],
│   on synapse_workspace.tf line 137, in resource "azurerm_role_assignment" "synapse_admin":
│  137: resource "azurerm_role_assignment" "synapse_admin" {

### Steps to Reproduce

terraform plan
terraform apply

**Comment by Chambras** [comment]
Hi @vsotog-Soluciones I think there is a confusion here. `azurerm_role_assignment` is for built-in roles. If you execute ` Get-AzRoleDefinition | Format-Table -Property Name, IsCustom, Id` , you will see that `Synapse Administrator` is not here.  If you want to manage Synapse role assignments, you might want to take a look at [azurerm_synapse_role_assignment](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/synapse_role_assignment)

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @Chambras‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
