### ISSUE TITLE
Azure storage account blob container obsolete preview API version used

### ISSUE THREAD

**Issue by librucha** [hashicorp/terraform-provider-azurerm#26157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

azurerm_role_assignment

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "test" {
  principal_id         = "00000000-0000-0000-0000-000000000000"
  scope                = "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/xxxxx-rg/providers/Microsoft.Storage/storageAccounts/storage/blobServices/default/containers/container"
  role_definition_name = "Storage Blob Data Contributor"
}
```

### Debug Output/Panic Output

```shell
│ Error: loading Role Definition List: unexpected status 400 (400 Bad Request) with error: NoRegisteredProviderFound: No registered resource provider found for location 'westeurope' and API version '2022-05-01-preview' for type 'storageAccounts'. The supported api-versions are '2023-05-01, 2023-04-01, 2023-01-01, 2022-09-01, 2022-05-01, 2021-09-01, 2021-08-01, 2021-06-01, 2021-05-01, 2021-04-01, 2021-02-01, 2021-01-01, 2020-08-01-preview, 2019-06-01, 2019-04-01, 2018-11-01, 2018-07-01, 2018-03-01-preview, 2018-02-01, 2017-10-01, 2017-06-01, 2016-12-01, 2016-05-01, 2016-01-01, 2015-06-15, 2015-05-01-preview'. The supported locations are 'eastus, eastus2, westus, westeurope, eastasia, southeastasia, japaneast, japanwest, northcentralus, southcentralus, centralus, northeurope, brazilsouth, australiaeast, australiasoutheast, southindia, centralindia, westindia, canadaeast, canadacentral, westus2, westcentralus, uksouth, ukwest, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest, swedencentral, qatarcentral, polandcentral, italynorth, israelcentral, mexicocentral, spaincentral'.
```

### Expected Behaviour

Role assigment is created

### Actual Behaviour

fired error

**Comment by magodo** [comment]
@librucha The error is a bit confusing. The actual reason is that your subscription (that is running the `terraform`) hasn't registered the Microsoft.Storage RP. Please either ensure the [`skip_provider_registration`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#skip_provider_registration) is not enabled, or manually register it via any other means.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
