### ISSUE TITLE
azurerm_role_definition id is invalid

### ISSUE THREAD

**Issue by martin-hauge** [hashicorp/terraform-provider-azurerm#26171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.106.0

### Affected Resource(s)/Data Source(s)

azurerm_role_definition

### Terraform Configuration Files

```hcl
terraform {
  
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "= 2.50.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.106.0"
    }
  }
}

provider "azurerm" {
  features {
  }
  storage_use_azuread = true
}

data azurerm_subscription current {
}

data "azuread_client_config" "current" {}

resource "azuread_application" "app" {
  display_name = "test-bug"
  owners       = [data.azuread_client_config.current.object_id]
}

resource "azuread_service_principal" "sp" {
  client_id                    = azuread_application.app.client_id
  app_role_assignment_required = false
  owners                       = [data.azuread_client_config.current.object_id]
}

resource "azurerm_role_definition" "role_definition" {
    name        = "Role definition"
    scope       = data.azurerm_subscription.current.id
    description = "For bug reproduction"

    permissions {
        actions = [
            "Microsoft.Storage/storageAccounts/PrivateEndpointConnectionsApproval/action"
        ]
    }
}

resource "azurerm_role_assignment" "role_assignment" {
    scope              = data.azurerm_subscription.current.id
    role_definition_id = azurerm_role_definition.role_definition.id
    principal_id       = azuread_service_principal.sp.id
}
```

### Debug Output/Panic Output

```shell
azurerm_role_assignment.role_assignment: Creating...
╷
│ Error: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRoleDefinitionId" Message="The role definition ID '047fe50a-5aac-8259-f50b-2d04465518ce|' is not valid."
│ 
│   with azurerm_role_assignment.role_assignment,
│   on permissions.tf line 55, in resource "azurerm_role_assignment" "role_assignment":
│   55: resource "azurerm_role_assignment" "role_assignment" {
│ 
╵
```

### Expected Behaviour

A role definition should be created, followed by a role assignment referring to that definition.

### Actual Behaviour

The plan is successfully created. At the apply step, the role definition is successfully created, but when attempting to create a role assignment, referring to the `azurem_role_definition.name.id` field gives the above error. It appears there is an extra pipe character at the end of the otherwise correct id string.

### Steps to Reproduce

With the above configuration, `terraform init` followed by `terraform apply`.

### References

This issue was raised in an older, now closed issue #8426

**Comment by magodo** [comment]
@martin-hauge Per the [example](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#example-usage-custom-role--service-principal), you shall use `.role_definition_resource_id` instead of `.id`.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! I am going to close this with @magodo‘s response as an answer. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
