### ISSUE TITLE
Unable to created runner in Linux VM

### ISSUE THREAD

**Issue by SZGAN26** [hashicorp/terraform-provider-azurerm#26172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

login as: azureuser
azureuser@10.103.13.118's password:
Access denied
azureuser@10.103.13.118's password:
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last failed login: Fri May 31 10:56:03 UTC 2024 from 10.56.18.229 on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Fri May 31 10:51:43 2024 from 10.56.18.229
[azureuser@vmghactionppe01 ~]$ ls -ltr
total 4
drwxr-xr-x. 5 azureuser azureuser 4096 May 31 10:45 actions-runner
[azureuser@vmghactionppe01 ~]$ cd actions-runner
[azureuser@vmghactionppe01 actions-runner]$ ./config.sh --url https://github.com/Inter-IKEA-Digital/IIG-DataCatalog-BGAPI-Infra --token BEWDMCAN2YAFRNRINGGZFJ3GLGTKO

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 3F83:ACAFC:7CCEE2D:7D88F82:6659ACE4)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).

### Terraform Version

3.103.0.

### AzureRM Provider Version

3.103.0..

### Affected Resource(s)/Data Source(s)

azurerm v3.103.0..

### Terraform Configuration Files

```hcl
login as: azureuser
azureuser@10.103.13.118's password:
Access denied
azureuser@10.103.13.118's password:
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last failed login: Fri May 31 10:56:03 UTC 2024 from 10.56.18.229 on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Fri May 31 10:51:43 2024 from 10.56.18.229
[azureuser@vmghactionppe01 ~]$ ls -ltr
total 4
drwxr-xr-x. 5 azureuser azureuser 4096 May 31 10:45 actions-runner
[azureuser@vmghactionppe01 ~]$ cd actions-runner
[azureuser@vmghactionppe01 actions-runner]$ ./config.sh --url https://github.com/Inter-IKEA-Digital/IIG-DataCatalog-BGAPI-Infra --token BEWDMCAN2YAFRNRINGGZFJ3GLGTKO

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 3F83:ACAFC:7CCEE2D:7D88F82:6659ACE4)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).
```

### Debug Output/Panic Output

```shell
login as: azureuser
azureuser@10.103.13.118's password:
Access denied
azureuser@10.103.13.118's password:
Register this system with Red Hat Insights: insights-client --register
Create an account or view all your systems at https://red.ht/insights-dashboard
Last failed login: Fri May 31 10:56:03 UTC 2024 from 10.56.18.229 on ssh:notty
There was 1 failed login attempt since the last successful login.
Last login: Fri May 31 10:51:43 2024 from 10.56.18.229
[azureuser@vmghactionppe01 ~]$ ls -ltr
total 4
drwxr-xr-x. 5 azureuser azureuser 4096 May 31 10:45 actions-runner
[azureuser@vmghactionppe01 ~]$ cd actions-runner
[azureuser@vmghactionppe01 actions-runner]$ ./config.sh --url https://github.com/Inter-IKEA-Digital/IIG-DataCatalog-BGAPI-Infra --token BEWDMCAN2YAFRNRINGGZFJ3GLGTKO

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 3F83:ACAFC:7CCEE2D:7D88F82:6659ACE4)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).
```

### Expected Behaviour

Runners to be created

### Actual Behaviour

Getting error as 
[azureuser@vmghactionppe01 actions-runner]$ ./config.sh --url https://github.com/Inter-IKEA-Digital/IIG-DataCatalog-BGAPI-Infra --token BEWDMCAN2YAFRNRINGGZFJ3GLGTKO

--------------------------------------------------------------------------------
|        ____ _ _   _   _       _          _        _   _                      |
|       / ___(_) |_| | | |_   _| |__      / \   ___| |_(_) ___  _ __  ___      |
|      | |  _| | __| |_| | | | | '_ \    / _ \ / __| __| |/ _ \| '_ \/ __|     |
|      | |_| | | |_|  _  | |_| | |_) |  / ___ \ (__| |_| | (_) | | | \__ \     |
|       \____|_|\__|_| |_|\__,_|_.__/  /_/   \_\___|\__|_|\___/|_| |_|___/     |
|                                                                              |
|                       Self-hosted runner registration                        |
|                                                                              |
--------------------------------------------------------------------------------

# Authentication

Http response code: NotFound from 'POST https://api.github.com/actions/runner-registration' (Request Id: 3F83:ACAFC:7CCEE2D:7D88F82:6659ACE4)
{"message":"Not Found","documentation_url":"https://docs.github.com/rest"}
Response status code does not indicate success: 404 (Not Found).

**Comment by Chambras** [comment]
Hi @SZGAN26 I do not think this has to do with the azurerm provider. It looks you are trying to add a selfhosted runner to your private repo https://github.com/Inter-IKEA-Digital/IIG-DataCatalog-BGAPI-Infra
Did you follow this [guide](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners)?

**Comment by SZGAN26** [comment]
Thank you :)
I have added the data disks 250 GB. still getting error as No Space left on device.

Current runner version: '2.316.1'
Runner name: 'terraform'
Runner group name: 'Default'
Machine name: 'vmghactionstg01'
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'azure/login@v1' (SHA:cb79c773a3cfa[2](https://github.com/Inter-IKEA-Digital/IIG-DataCatalog-BGAPI-Infra/actions/runs/9319242419/job/25742140994#step:1:2)7f31f25eb3f677781210c9ce3d)
Error: No space left on device

Kindly help me on this

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
