### ISSUE TITLE
Small typo in example provided for container_registry_cache_rule, missing acr 

### ISSUE THREAD

**Issue by stephanerenou** [hashicorp/terraform-provider-azurerm#26170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.9

### AzureRM Provider Version

3.106.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry_cache_rule

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_container_registry" "acr" {
  name                = "containerRegistry1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  sku                 = "Basic"
}

resource "azurerm_container_registry_cache_rule" "cache_rule" {
  name                  = "cacherule"
  container_registry_id = azurerm_container_registry.acr.id
  target_repo           = "target"
  source_repo           = "docker.io/hello-world"
  credential_set_id     = "${azurerm_container_registry.id}/credentialSets/example"
}
```

### Debug Output/Panic Output

```shell
No panic
```

### Expected Behaviour

should create the rule
The fix is just to add acr to the credential id as:
credential_set_id     = "${azurerm_container_registry.acr.id}/credentialSets/example"

### Actual Behaviour

│ Error: Reference to undeclared resource
│ 
│   on ../sharedModules/sharedenv/registries.tf line 76, in resource "azurerm_container_registry_cache_rule" "cache_rule":
│   76:   credential_set_id     = "${azurerm_container_registry.id}/credentialSets/example"
│ 
│ A managed resource "azurerm_container_registry" "id" has not been declared in module.xxx.

### Steps to Reproduce

terraform apply

**Comment by Chambras** [comment]
Hi @stephanerenou good catch. A PR is coming soon :)
