### ISSUE TITLE
Support for ADX Provider

### ISSUE THREAD

**Issue by ascdi** [hashicorp/terraform-provider-azurerm#26187]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

We would need a provider to set up ADX.
Similar like the one by [favoretti](https://registry.terraform.io/providers/favoretti/adx/latest), but from an official source.

### New or Affected Resource(s)/Data Source(s)

none

### Potential Terraform Configuration

```hcl
provider "azurerm_adx" {
  tenant_id       = "***"
}

resource "azurerm_adx_table" "test" {
  name          = "Test1"
  database_name = "test-db"

  column {
    name = "id"
    type = "int"
  }
  column {
    name = "key"
    type = "string"
  }
  column {
    name = "value"
    type = "int"
  }
}

resource "azurerm_adx_table_mapping" "test" {
  name          = "TestMapping"
  database_name = "test-db"
  table_name    = azurerm_adx_table.test.name
  kind          = "Json"

  mapping {
    column   = "f1"
    path     = "$.f1"
    datatype = "string"
  }
  mapping {
    column   = "f2"
    path     = "$.f2"
    datatype = "string"
  }
}
```
```


### References

_No response_

**Comment by katbyte** [comment]
Hi @ascdi,

While i thank you for opening an issue this repo is only for the azurerm provider. At this time we have no intention of creating an official hashicorp ADX provider and i would recomend using the one @favoretti created.

As such i am going to close this.

**Comment by ascdi** [comment]
Actually it already exists but is named kusto_cluster.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kusto_cluster
