### ISSUE TITLE
Can't set `default_storage_firewall_enabled` to `false` in `azurerm_databricks_workspace` resource

### ISSUE THREAD

**Issue by alexott** [hashicorp/terraform-provider-azurerm#26213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
Just create a Databricks workspace with `default_storage_firewall_enabled` set to `true` and then try to set it to `false`.
```

### Debug Output/Panic Output

```shell
Debug logs are put into Gist at https://gist.github.com/alexott/b9b998531d382c6e7e5e4147f6700cd5
```

### Expected Behaviour

It's expected that the DBFS firewall will be disabled

### Actual Behaviour

it's not disabled

### Steps to Reproduce

Just create Databricks workspace with `default_storage_firewall_enabled` set to `true`, and then try to set it to `false`...

### Important Factoids

normal azure environment

### References

* #25919 - introduced this change.

* Documentation: https://learn.microsoft.com/en-us/azure/storage/common/storage-network-security?tabs=azure-portal#restrictions-and-considerations

**Comment by favoretti** [comment]
Hi and thank you for reporting this issue. 

I think I see why this is happening from the logs, will have a closer look and keep you posted.
