### ISSUE TITLE
APIM: behaviour of `zones` in `additional_location` differs from behaviour of `zones` in parent resource

### ISSUE THREAD

**Issue by CherylFlowers** [hashicorp/terraform-provider-azurerm#26244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.8

### AzureRM Provider Version

3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
resource "azurerm_api_management" "api_management" {
  name                = "test"
  resource_group_name = "test-rg"
  location            = "canada central"  
  sku_name            = "Premium"
  publisher_name      = "test"
  publisher_email     = "test@test.ca"
  zones               = ["1"]

  additional_location {
    location = "southeast asia"
    zones    = ["1", "2"]
  }
}
```

### Debug Output/Panic Output

```shell
+ additional_location {
+ capacity             = (known after apply)
+ gateway_disabled     = false
+ gateway_regional_url = (known after apply)
+ location             = "southeastasia"
+ private_ip_addresses = (known after apply)
+ public_ip_addresses  = (known after apply)
+ zones                = [
+ "1",
+ "2",
] # forces replacement
}
```

### Expected Behaviour

When adding a brand new `additional_location` to an existing APIM instance, the `zones` argument should not trigger a replacement, regardless of the value.

### Actual Behaviour

When adding a brand new `additional_location` to an existing APIM instance, if the `zones` field is configured, it triggers a replacement of the APIM instance. If the `zones` field is omitted, it does not trigger a replacement.

### Steps to Reproduce

1. Provision an APIM instance with no `additional_location`.
2. Add `additional_location` and omit the `zones` argument.
3. Run a `terraform plan` and note that the plan does not force a replacement of the APIM instance.
4. Add the `zones` field to `additional_location`.
5. Run a `terraform plan` and note that the plan now forces a replacement of the APIM instance.

### References

It appears [this pull request](https://github.com/hashicorp/terraform-provider-azurerm/pull/24431) may be related to this unexpected behaviour. It appears that the functionality of the `zones` argument was updated for the APIM instance itself, but the same changes were not made to the `additional_location` argument.

**Comment by sinbai** [comment]
Hi @CherylFlowers thanks for opening this issue. Per the Terraform [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management#additional_location) below, changing `zone` of `additional_location`forces a new resource to be created. I assume that the symptom is expected. Is it possible to explain why this case should not trigger a replacement?

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/39109137/2af28414-167b-4e3f-ad29-7ae5d1123bb7)

**Comment by klakshmikantha** [comment]
Hi @sinbai - Thank you for the response. Changing or setting the zones under 'additional_location' should re-create the data plane resource deployed in that region but not the entire control plane of APIM which is what is happening now. The zones at root level for control plane should drive recreation of the control plane but not the zones under each additional location block.
This is especially important as we add additional data planes in the future spanning geographies but can't afford to re-create control plane risking the configurations/APIs/products etc. already setup and also not impact other region data planes.
The zone setting under the additional_location block should only re-create the data plane in that location.

**Comment by sinbai** [comment]
Hi @klakshmikantha thanks for your reply. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/26384)has been submitted to remove the replacement when the `zone` in `additional_location` changes. Could you please track it for more updates?
