### ISSUE TITLE
Dotnet isolated options not working correctly

### ISSUE THREAD

**Issue by milesbarnard** [hashicorp/terraform-provider-azurerm#26252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### Terraform Configuration Files

```hcl
resource "azurerm_linux_function_app" "example" {
  name                = "example-linux-function-app"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  service_plan_id            = azurerm_service_plan.example.id

  site_config {
      always_on = true
      application_stack {
        dotnet_version                  = "8.0"
        use_dotnet_isolated_environment = true
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

It should produce a function app with the following settings:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/65308480/b2373c8c-2908-4f91-8fa9-a53ce7686866)

### Actual Behaviour

Instead it produces:
![dotnet](https://github.com/hashicorp/terraform-provider-azurerm/assets/65308480/77d1f950-d7bb-4be5-acb1-64f91ac2fe1a)

and you have to manually use the dropdown to set it

### Steps to Reproduce

terraform apply

**Comment by AlexPykavy** [comment]
According to the docs, you need to use [`use_dotnet_isolated_runtime`](https://registry.terraform.io/providers/hashicorp/azurerm/3.6.0/docs/resources/linux_function_app#use_dotnet_isolated_runtime) to specify the `dotnet-isolated` application stack.

**Comment by milesbarnard** [comment]
> According to the docs, you need to use [`use_dotnet_isolated_runtime`](https://registry.terraform.io/providers/hashicorp/azurerm/3.6.0/docs/resources/linux_function_app#use_dotnet_isolated_runtime) to specify the `dotnet-isolated` application stack.

Yes I have done - please see the Terraform configuration section under application_stack. Or do you mean there is somewhere else I am meant to specify it?

**Comment by milesbarnard** [comment]
@AlexPykavy Ah yes I think you're right - didn't spot that as it was going through a module. Thanks!
