### ISSUE TITLE
azurerm_resource_policy_assignment rejects resource_id value as invalid

### ISSUE THREAD

**Issue by rjhornsby** [hashicorp/terraform-provider-azurerm#26257]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_resource_policy_assignment

### Terraform Configuration Files

```hcl
data "azurerm_policy_definition" "vm-backups" {
  display_name = "Configure backup on virtual machines without a given tag to an existing recovery services vault in the same location"
}

resource "azurerm_resource_policy_assignment" "vm-backups" {
  name                 = "vm-backups"
  policy_definition_id = data.azurerm_policy_definition.vm-backups.id
  resource_id          = "/subscriptions/xxxxx-xxxx-421b-831f-xxxxx"
}
```

### Debug Output/Panic Output

```shell
│ Error: ID cannot be a Subscription ID
│
│   with azurerm_resource_policy_assignment.vm-backups,
│   on backup.tf line 21, in resource "azurerm_resource_policy_assignment" "vm-backups":
│   21:   resource_id          = "/subscriptions/xxxxx-xxxx-421b-831f-xxxxx"
```

### Expected Behaviour

In theory, it should have accepted the subscription ID as a valid value for the "resource_id" instead of the input validation error it throws.

If you `terraform import` this resource and look at the imported state, the resource_id is exactly the subscription id value that Terraform is now rejecting and saying you can't use.

```
$ terraform import azurerm_resource_policy_assignment.vm-backups /subscriptions/xxxxx-xxxx-421b-831f-xxxxx/providers/Microsoft.Authorization/policyAssignments/xxxxxxxx
...
Import successful!
$ terraform state show  azurerm_resource_policy_assignment.vm-backups
...
```

near the end of the output of `state show` it will say:

```
resource_id          = "/subscriptions/xxxxx-xxxx-421b-831f-xxxxx"
```

### Actual Behaviour

The azurerm provider rejects the `resource_id`, saying that it couldn't possibly accept a subscription id here.

I recognize that the example code is almost certainly incomplete. This is because I imported the resource with the minimum TF code, expecting to be able to `terraform plan` and fill in the missing values. I can't get past the invalid resource_id to do that.

### Steps to Reproduce

`terraform plan`

### Important Factoids

AZ government, but that shouldn't matter

**Comment by tombuildsstuff** [comment]
hey @rjhornsby 

The `azurerm_resource_policy_assignment` resource is intended for assigning a Policy to an ARM Resource (e.g. a Virtual Machine, Storage Account etc), there's other resources for assigning to a Subscription/Management Group/Resource Group - as such in this case you'll need to use [the `azurerm_subscription_policy_assignment` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subscription_policy_assignment) instead.

Since this should be fixed by using the `azurerm_subscription_policy_assignment` resource rather than the `azurerm_resource_policy_assignment` resource, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we can take another look.

Thanks!

**Comment by rjhornsby** [comment]
@tombuildsstuff ah, thanks for the hint. Seems like that was the issue.
