### ISSUE TITLE
Support for editing default_node_pool without downtime

### ISSUE THREAD

**Issue by Israphel** [hashicorp/terraform-provider-azurerm#26273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Currently, if you change (for example) vm_size, the instances rotation leads to downtime, because the whole node_pool is replaced.

Even though **ugprade_settings** is available, it's ignored when replacing the vm_size, so PDBs are not honored either.

Replacing **vm_size** is something common and expecting downtime to do that shouldn't be ok.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

**Comment by jkroepke** [comment]
Hey @Israphel 

Terraform is just following the Microsoft guide here. https://learn.microsoft.com/en-us/azure/aks/resize-node-pool?tabs=azure-cli

Replace a node pool is mandatory in context of changing properties.

**Comment by jkroepke** [comment]
Sure, but Terraform can't fix this limitation for you. You can raise an issue at Azure.

The general recommendation is an dedicated node pool for applications and leave the system node pool as-is.

**Comment by Israphel** [comment]
> The general recommendation is an dedicated node pool for applications and leave the system node pool as-is.

that's a compute waste, and also it won't fix the fact that the node pool for apps will also be nuked if you change vm size

**Comment by jkroepke** [comment]
There is no difference between doing an in-place upgrade or adding a new node pool and remove the old one. In both cases, old nodes goes down, new nodes come up.

**Comment by Israphel** [comment]
well, there is, you have to do all the draining and moving workloads by hand.

**Comment by jkroepke** [comment]
Buts something, you could automate as well.

**Comment by Israphel** [comment]
Well, I have elevated the issue to MS, since we're working with them anyway.

The future seems to be Karpenter as an addon, and with that we don't need to worry about node pools anymore.

**Comment by stephybun** [comment]
Thanks for opening this issue @Israphel.

We are in agreement that being able to update the default node pool without any downtime is preferable, but as @jkroepke pointed out the AKS API mandates the cycling of the system node pool if certain properties are changed.

We appreciate you raising this issue with Microsoft since they would ultimately need to expose this ability before we're able to support this in the provider, but since we're unable to satisfy this request until this becomes available in the upstream API I'm going to close this issue for the moment. Happy to revisit this at a later stage when and if the behaviour changes in the AKS API.
