### ISSUE TITLE
azurerm_virtual_network : Error: ID was missing the `networkSecurityGroups` element

### ISSUE THREAD

**Issue by totofff** [hashicorp/terraform-provider-azurerm#26276]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.2.3

### AzureRM Provider Version

3.107.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "some_network" {
  for_each            = local.data
  name                = format("vnet-%s-%s", var.env_id, each.key)
  location            = each.value.name
  resource_group_name = azurerm_resource_group.some_rg[each.key].name
  address_space       = local.list_address_spaces

  lifecycle {
    ignore_changes = [subnet]
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: ID was missing the `networkSecurityGroups` element
│ 
│   with azurerm_virtual_network.some_network["test"],
│   on main.tf line 132, in resource "azurerm_virtual_network" "some_network":
│  132: resource "azurerm_virtual_network" "some_network" {
│ 
╵
```

### Expected Behaviour

We add a new range in local.list_address_spaces list to add a new range in the vitrtual network

### Actual Behaviour

since 3.107.0 (working on 3.106.1) : when adding a range in a virtual network that have ignore change on subnet, it make an error editing the virtual network because on GO erreur on  networkSecurityGroups

### Steps to Reproduce

Deploy a virtual network with one range and ignore change on subnet, add a subnet and relaunch the pipeline adding a new range.

**Comment by pritiyadav537** [comment]
I am also facing the same issue while modifying tags for an existing vnet was deployed successfully earlier via terraform.

**Comment by pritiyadav537** [comment]
Any update please, its blocking our deployments ?

**Comment by Pidgegeddon** [comment]
We are facing the same issue when updating the `dns_servers` argument on a vnet resource. Setting provider version to `3.106.1` fixes this as a workaround for the time being

**Comment by Noel-Jones** [comment]
Should there not have been a 3.107.1 as this was a bug introduced in 3.107.0 ? I've had to go back to 3.106 as 3.108 isn't out yet.
