### ISSUE TITLE
azurerm_sentinel_data_connector_threat_intelligence_taxii input parsing

### ISSUE THREAD

**Issue by shaken1901** [hashicorp/terraform-provider-azurerm#26272]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.107.0

### Affected Resource(s)/Data Source(s)

azurerm_sentinel_data_connector_threat_intelligence_taxii

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resource-group"
  location = "East US"
  
}

resource "azurerm_log_analytics_workspace" "example" {
  name                = "example-workspace"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "example" {
  solution_name         = "SecurityInsights"
  location              = azurerm_resource_group.example.location
  resource_group_name   = azurerm_resource_group.example.name
  workspace_resource_id = azurerm_log_analytics_workspace.example.id
  workspace_name        = azurerm_log_analytics_workspace.example.name

  plan {
  publisher = "Microsoft"
  product   = "OMSGallery/SecurityInsights"
  }
}

resource "azurerm_sentinel_data_connector_threat_intelligence_taxii" "example" {
  name                       = "ti-taxii-data-connector-example"
  log_analytics_workspace_id = azurerm_log_analytics_workspace.example.id
  display_name               = "Mitre ATT&CK - Enterprise Attack Collection"
  api_root_url               = "https://cti-taxii.mitre.org/stix/"
  collection_id              = "95ecc380-afe9-11e4-9b6c-751b66dd541e"
  polling_frequency          = "OnceADay"
}
```

### Debug Output/Panic Output

```shell
Error: creating Data Connector: (Name "ti-taxii-data-connector-example" / Workspace Name "example-workspace" / Resource Group "example-resource-group"): securityinsight.DataConnectorsClient#CreateOrUpdate: Failure responding to request: StatusCode=201 -- Original Error: Error occurred unmarshalling JSON - Error = 'unknown enum for pollingFrequency "OnceADay"' JSON = '{"id":"/subscriptions/REDACTED/resourceGroups/example-resource-group/providers/Microsoft.OperationalInsights/workspaces/example-workspace/providers/Microsoft.SecurityInsights/dataConnectors/ti-taxii-data-connector-example","name":"ti-taxii-data-connector-example","etag":"REDACTED","type":"Microsoft.SecurityInsights/dataConnectors","kind":"ThreatIntelligenceTaxii","properties":{"taxiiServer":"https://cti-taxii.mitre.org/stix/","collectionId":"95ecc380-afe9-11e4-9b6c-751b66dd541e","workspaceId":"REDACTED","friendlyName":"Mitre ATT&CK - Enterprise Attack Collection","userName":null,"password":null,"taxiiLookbackPeriod":"1970-01-01T00:00:00Z","pollingFrequency":"OnceADay","dataTypes":{"taxiiClient":{"state":"enabled"}},"tenantId":"REDACTED"}}'
```

### Expected Behaviour

Resource should have deployed with the inputs provided

### Actual Behaviour

Terraform plan succeeds, but apply fails.
Error = 'unknown enum for pollingFrequency "OnceADay"' was observed

### Steps to Reproduce

terraform apply

### References

issue #25409, resolved by merge request #25343 - similar unmarshalling JSON parsing occurrence with another input in this module

**Comment by ziyeqf** [comment]
Hi @shaken1901, thanks for reporting. 
I have submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/26316) for this issue, once it merged it should be fixed. You can subscribe the PR to keep a track on it.
For any further questions please leave comments.

Thanks.

**Comment by geet-h17** [comment]
@ziyeqf till ur pr is merged is there any alternative way to get this running..?

**Comment by ziyeqf** [comment]
> @ziyeqf till ur pr is merged is there any alternative way to get this running..?

I'm afraid no..
