### ISSUE TITLE
Error in creating a logic app standard "There was a conflict. SiteConfig.PublicNetworkAccess cannot be set by itself. Please use the Site.PublicNetworkAccess property"

### ISSUE THREAD

**Issue by shobhit-jindal** [hashicorp/terraform-provider-azurerm#26288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.6

### AzureRM Provider Version

3.103.1

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_standard

### Terraform Configuration Files

```hcl
resource "azurerm_logic_app_standard" "logic_app_standard" {
  name                       = var.logic_app_name
  location                   = var.resource_group_location
  resource_group_name        = var.resource_group_name
  app_service_plan_id        = var.app_service_plan_id
  storage_account_name       = var.storage_account_name
  storage_account_access_key = var.storage_account_primary_access_key
  enabled                    = var.logic_app_enabled
  https_only                 = var.https_only
  version                    = var.logic_app_version
  tags                       = var.resource_tags

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on       = var.always_on
    ftps_state      = var.ftps_state
    min_tls_version = var.min_tls_version

    cors {
      allowed_origins = var.logic_app_allowed_origins
    }
  }

  lifecycle {
    ignore_changes = [
      site_config[0].public_network_access_enabled
    ]
  }
}
```

### Debug Output/Panic Output

```shell
StatusCode=400 -- Original Error: Code="BadRequest" Message="There was a conflict. SiteConfig.PublicNetworkAccess cannot be set by itself. Please use the Site.PublicNetworkAccess property." Details=[{"Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be set by itself. Please use the Site.PublicNetworkAccess property."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01020","Message":"There was a conflict. SiteConfig.PublicNetworkAccess cannot be set by itself. Please use the Site.PublicNetworkAccess property.","MessageTemplate":"There was a conflict. {0}","Parameters":["SiteConfig.PublicNetworkAccess cannot be set by itself. Please use the Site.PublicNetworkAccess property."]}}]
```

### Expected Behaviour

Logic_App_Standard resource should apply with any (valid) changes made to the resource block.

### Actual Behaviour

Not creating the resource throwing error

**Comment by ms-henglu** [comment]
Hi @shobhit-jindal ,

Thank you for taking time to report this issue!

Would you please provide a config with literal value to help reproduce the issue? Thanks!

**Comment by shobhit-jindal** [comment]
Hi,

Please find sample values below --

resource "azurerm_logic_app_standard" "logic_app_standard" {
  name                       = "test-la-001"
  location                   = "uksouth"
  resource_group_name        = <var.resource_group_name>
  app_service_plan_id        = <var.app_service_plan_id>
  storage_account_name       = <var.storage_account_name>
  storage_account_access_key = <var.storage_account_primary_access_key>
  enabled                    = true
  https_only                 = true
  version                    = "~4
  tags                       = null

  identity {
    type = "SystemAssigned"
  }

  site_config {
    always_on       = true
    ftps_state      = "AllAllowed"
    min_tls_version = "1.2"

    cors {
      allowed_origins = ["*"]
    }
  }

  lifecycle {
    ignore_changes = [
      site_config[0].public_network_access_enabled
    ]
  }
}

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
Hi @shobhit-jindal, I found this similar to https://github.com/hashicorp/terraform-provider-azurerm/issues/25891, and it seems that changes are already implemented. 
You may get the error because the changes have not yet been deployed to "uksouth", I tried with setting up using the same config, and it is working.

Can you try again, let me know if the problem still exists.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. Since the backend team with Microsoft rolled back the change some time ago I am going to mark this issue as closed. If this issue is still persisting, please reach out and I can reopen this issue.
