### ISSUE TITLE
upgrade_settings argument has become mandatory in azurerm_kubernetes_cluster_node_pool even though it is only an optional parameter after 3.106.1 update

### ISSUE THREAD

**Issue by raswinraaj** [hashicorp/terraform-provider-azurerm#26280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_node_pool

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_node_pool" "userpool" {
  for_each               = var.aks_user_nodepool
  name                   = each.value.nodepool-name
  kubernetes_cluster_id  = azurerm_kubernetes_cluster.instance.id
  vm_size                = each.value.vm-size
  zones                  = each.value.availability-zones
  max_pods               = each.value.max-pods
  enable_auto_scaling    = each.value.aks-usernp-autoscale
  max_count              = each.value.max-count
  min_count              = each.value.min-count
  orchestrator_version   = var.kubernetes_version
  mode                   = "User"
  enable_host_encryption = false
  enable_node_public_ip  = false
  node_labels            = each.value.node-labels
  tags                   = var.common_tags
  vnet_subnet_id         = var.aks_subnet_id
  lifecycle {
    ignore_changes = [
    tags["Creation Date"],
    max_count, 
    min_count
    ]
  }
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/raswinraaj/44850fd54d1035ac68a22ffa87ec3e10
```

### Expected Behaviour

upgrade_settings is an optional argument. It should not be shown as a removed property in tf plan

### Actual Behaviour

Now tf plan is showing as a removed argument

### Steps to Reproduce

terraform plan

### References

This commit seems to have broken - https://github.com/hashicorp/terraform-provider-azurerm/pull/26173#issuecomment-2148206867

**Comment by jaromirmikulik** [comment]
Is has the same behaviour also in resource azurerm_kubernetes_cluster --> section upgrade_settings should not be shown as a removed property in tf plan like bellow:

```
  ~ resource "azurerm_kubernetes_cluster" "aks" {
        id                                  = "/subscriptions/xxxxxx/resourceGroups/AKS-RG/providers/Microsoft.ContainerService/managedClusters/aks"
        name                                = "aks"
        tags                                = {
            "build"      = "20210323"
        }
        # (39 unchanged attributes hidden)

      ~ default_node_pool {
            name                          = "nodepool128"
            tags                          = {
                "build"      = "20210323"
            }
            # (33 unchanged attributes hidden)

          - upgrade_settings {}
        }

        # (7 unchanged blocks hidden)
    }

```

I have tested also in azurerm 1.107.0 and the behaviour is exactly same. I guess it started to shown from version 1.106.0.

If I revert to azurerm version 1.105.0, it works correctly.

**Comment by joshwright10** [comment]
@jaromirmikulik thanks! I think you made a typo though, it should be version `3.105.0`

**Comment by jaromirmikulik** [comment]
You are right. Sorry for that confusion.

**Comment by rgarcia89** [comment]
I have added 

```
  lifecycle {
    ignore_changes = [
      upgrade_settings,
    ]
  }
```

until it is fixed

**Comment by orgads** [comment]
Thanks. For inline configuration in `azurerm_kubernetes_cluster` it should be:
```tf
  lifecycle {
    ignore_changes = [
      # TODO: Remove once https://github.com/hashicorp/terraform-provider-azurerm/issues/26280 is fixed
      default_node_pool[0].upgrade_settings
    ]
  }
```

**Comment by rgarcia89** [comment]
@orgads you are right. I forgot to post both. Mine is for `azurerm_kubernetes_cluster_node_pool`.

**Comment by JCBSLMN** [comment]
I am having same issue with azurerm_kubernetes_cluster and azurerm_kubernetes_cluster_node_pool.

Terraform v1.5.7
azurerm v3.110.0
