### ISSUE TITLE
Azure Host Pool preferred_app_group_type  change forces replace

### ISSUE THREAD

**Issue by JulianReitzGIZ** [hashicorp/terraform-provider-azurerm#26324]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.107.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_host_pool

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_desktop_host_pool" "hostpool" {
    resource_group_name       = var.resource_group_name
    location                  = var.location
    name                      = var.avd_name
    friendly_name             = var.friendly_name
    description               = "Terraform managed HostPool"
    type                      = var.type
    preferred_app_group_type  = "RailApplications"

    tags                      = var.tags
}
```

### Debug Output/Panic Output

```shell
# module.avd["hp-avd-oneim-prod"].azurerm_virtual_desktop_host_pool.hostpool must be replaced
-/+ resource "azurerm_virtual_desktop_host_pool" "hostpool" {
        name                             = "hp-avd-prod"
      ~ preferred_app_group_type         = "Desktop" -> "RailApplications" # forces replacement
        # (12 unchanged attributes hidden)
        # (1 unchanged block hidden)
    }
```

### Expected Behaviour

While change the preferred_app_group_type  from "Desktop" to "RailApplications" should not trigger a replacement of the complete host pool resource.

### Actual Behaviour

Change of the attribute replace the host pool and alle related resources (application groups, hosts etc.). Hosts have to add manually after replacing of host pool!

**Comment by rcskosir** [comment]
Thanks for taking the time to raise this issue, as noted in the [terraform documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_host_pool#preferred_app_group_type):

> `preferred_app_group_type` - (Optional) Option to specify the preferred Application Group type for the Virtual Desktop Host Pool. Valid options are None, Desktop or RailApplications. Default is Desktop. Changing this forces a new resource to be created.

Changing the `preferred_app_group_type` forces a new resource to be created, this is expected behavior.

**Comment by JulianReitzGIZ** [comment]
@rcskosir thanks for the fast response! :D 

We are aware of the documentation, but we think that's unnecessary! Because it's possible to change this value through the azure portal without the need of replacement.

**Comment by sinbai** [comment]
Hi @JulianReitzGIZ thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/26333)has been submitted to fix this issue. Could you please track it for more updates?
