### ISSUE TITLE
Alert rules do not trigger and cannot be saved in the portal using the "azurerm_monitor_scheduled_query_rules_alert_v2" resource

### ISSUE THREAD

**Issue by MattNorman88** [hashicorp/terraform-provider-azurerm#26347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert_v2

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_scheduled_query_rules_alert_v2" "RoutesChangedTest" {
  for_each                         = { for rt in var.route_tables : rt.name => rt if rt.create_route_change_alert == true }
  name                             = "Alert-${var.alerts_data.alerts_subtitle}-RouteTable-RoutesChanged (${each.value.name}) TEST"
  resource_group_name              = var.alerts_data.resource_group_name
  scopes                           = [azurerm_route_table.RouteTable[each.value.name].id]
  description                      = "This alert will trigger when routes are amended in the route table"
  severity                         = 4
  auto_mitigation_enabled          = false
  enabled                          = true
  evaluation_frequency             = "PT5M"
  window_duration                  = "PT4H"
  location                         = var.location
  workspace_alerts_storage_enabled = false
  target_resource_types            = ["Microsoft.Network/routeTables"]
  tags                             = merge(var.resource_tags, { "DataClassification" = "N/A" })

  criteria {
    query = <<-QUERY
      AzureActivity 
        | where OperationNameValue == "MICROSOFT.NETWORK/ROUTETABLES/ROUTES/WRITE"
        | where ActivityStatusValue == "Success"
        | where Properties contains "${each.value.name}"
      QUERY

    resource_id_column      = null
    time_aggregation_method = "Count"
    threshold               = 0
    operator                = "GreaterThan"

    failing_periods {
      number_of_evaluation_periods             = 1
      minimum_failing_periods_to_trigger_alert = 1
    }
  }

  action {
    action_groups = [for grp in each.value.alert_action_groups : local.action_group_resource_map[grp]]
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

1. Alert rules gets created and triggers when a route change is made.
2. Alert can be edited and saved in the Azure portal after creation.

### Actual Behaviour

1. Alert rules gets created but never triggers when making a route change.
2. Alert cannot be saved in the Azure portal. It does not show the review summary and the save button is unresponsive.
3. The issue is not specific to this particular alert. It appears to affect all log query alerts.

### Steps to Reproduce

- Deploy alert with azurerm 3.98.0 onwards.
- The alert works fine with any version prior to 3.98.0.
- 3.98.0 introduced the ability to use the identity block which is documented as an optional parameter. It appears that an identity has to be provided as manually choosing the system managed identity option in the portal allows me to save the alert.

**Comment by teowa** [comment]
Hi @MattNorman88 , thanks for submitting this! #26364 is going to fix the issue.
