### ISSUE TITLE
Access policy is replaced when permissions are changed 

### ISSUE THREAD

**Issue by koderjoker** [hashicorp/terraform-provider-azurerm#26390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.108

### Affected Resource(s)/Data Source(s)

azurerm_redis_cache_access_policy

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=3.108.0"
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "East US"
}

resource "azurerm_redis_cache" "trf-example" {
  name                = "trf-example"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  capacity            = 1
  family              = "P"
  sku_name            = "Premium"
  enable_non_ssl_port = false

  redis_configuration {
    maxmemory_reserved = 2
    maxmemory_delta    = 2
    maxmemory_policy   = "allkeys-lru"
  }
}

resource "azurerm_redis_cache_access_policy" "example" {
  name           = "example"
  redis_cache_id = azurerm_redis_cache.trf-example.id
  permissions    = "+@read +@connection +cluster|info"
}

resource "azurerm_redis_cache_access_policy_assignment" "example" {
  name                = "00000000-0000-0000-0000-000000000000"
  redis_cache_id      = azurerm_redis_cache.trf-example.id
  access_policy_name  = azurerm_redis_cache_access_policy.example.name
  object_id           = "00000000-0000-0000-0000-000000000000"
  object_id_alias     = "ServicePrincipal"
}
```

### Debug Output/Panic Output

```shell
│ Error: deleting Redis Cache Access Policy example in Redis Cache trf-example in resource group example-resources: performing AccessPolicyDelete: unexpected status 400 (400 Bad Request) with error: AccessPolicyUpdateNotPermitted: Cannot delete access policy while it is linked to access policy assignment. For more information, see: https://aka.ms/redis/MicrosoftEntraAuthenticationPrerequisites.
│
│ deleting Redis Cache Access Policy example in Redis Cache trf-example in resource group example-resources: performing
│ AccessPolicyDelete: unexpected status 400 (400 Bad Request) with error: AccessPolicyUpdateNotPermitted: Cannot delete access policy
│ while it is linked to access policy assignment. For more information, see:
│ https://aka.ms/redis/MicrosoftEntraAuthenticationPrerequisites.
```

### Expected Behaviour

When the permissions of an access policy are changed, the access policy should update itself. It should not delete and recreate itself.

### Actual Behaviour

An access policy that has been assigned to an object id cannot be deleted. When the permissions of an access policy are updated, terraform tries to delete and recreate the access policy, which fails since the access policy is assigned to an object id.

### Steps to Reproduce

1. `terraform apply` the configuration above
2. Change resource azurerm_redis_cache_access_policy.example.name.permissions to `+@read +@write +@connection +cluster|info`
3. `terraform apply` again
4. This should fail with the error shared above

### References

Issue that was raised for introducing support for MS Entra Authentication https://github.com/hashicorp/terraform-provider-azurerm/issues/23371

**Comment by sinbai** [comment]
Hi @koderjoker thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/26440)has been submitted to fix this issue. Could you please track it for more updates?

**Comment by koderjoker** [comment]
@sinbai is there a way we could test this change before it's released?

**Comment by sinbai** [comment]
@koderjoker you could pull the [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/26440)and build the AzureRM Terraform Provider locally according to the [documentation](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/DEVELOPER.md) and then test it first.

**Comment by koderjoker** [comment]
Thanks for fix @sinbai @stephybun! Is there a release date for v3.110.0?
