### ISSUE TITLE
azurerm_container_registry expects "Premium" but state stores "Managed" 

### ISSUE THREAD

**Issue by spowser** [hashicorp/terraform-provider-azurerm#26414]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.102.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_container_registry" "acr" {
  name                = "TESTCR"
  resource_group_name = "TESTRG"
  sku                 = "Premium"

  admin_enabled = false
  location      = southcentralus

  georeplications {
    location                  = "canadacentral"
    regional_endpoint_enabled = true
    tags                      = {}
    zone_redundancy_enabled   = true
  }
  georeplications {
    location                  = "canadaeast"
    regional_endpoint_enabled = true
    tags                      = {}
    zone_redundancy_enabled   = false
  }
  georeplications {
    location                  = "germanywestcentral"
    regional_endpoint_enabled = true
    tags                      = {}
    zone_redundancy_enabled   = true
  }
  georeplications {
    location                  = "westus"
    regional_endpoint_enabled = true
    tags                      = {}
    zone_redundancy_enabled   = false
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The plan should come back with no changes.

### Actual Behaviour

Running a plan after the resource was imported results in:
~ sku                           = "Managed" -> "Premium"

### Steps to Reproduce

1.  Import an ACR from Azure with the following in the JSON found on the overview page
...
"sku": {
        "name": "Premium",
        "tier": "Managed"
},
...

3.  Run a plan with sku set to Premium

**Comment by magodo** [comment]
@spowser Currently, the provider assumes the `name` and `tier` are the same, as is defined in its [swagger](https://github.com/Azure/azure-rest-api-specs/blob/7753cb8917f0968713c013a1f25875e8bd8dc492/specification/containerregistry/resource-manager/Microsoft.ContainerRegistry/stable/2023-07-01/containerregistry.json#L3499), also there is no defined enum for `Managed`.

I'd like to know how is this ACR get created at the first place. If the `Premium` + `Managed` is a valid combination. Then we'll need to adapt the provider accordingly.

**Comment by tombuildsstuff** [comment]
@spowser whilst this might sound like an odd suggestion - from memory `Basic` (the old SKU) got replaced by `Managed` which then got renamed to `Basic` - so I suspect that's actually the new "Basic" but the resource representation looks to be using the outdated value - would you be able to add a tag to the Container Registry (via the CLI/Portal etc) and see if that updates `Sku` to `Basic`?

**Comment by spowser** [comment]
I checked one of our other ACRs that was created in June of 2023 with the Basic pricing plan and it shows 
```
"sku": {
        "name": "Basic",
        "tier": "Basic"
},
```

@tombuildsstuff Added a test tag to the resource in question but the resource json is still showing "Managed"

**Comment by tombuildsstuff** [comment]
Good to confirm that, thanks - in which case I guess we'll need to handle this new value within the Provider 👍

**Comment by loadaverage** [comment]
I have exactly the same issue, Registry was created with Terraform/azurerm on `8/4/2023` with:

```hcl
resource "azurerm_container_registry" "my_container_registry" {
  name                = "myregistry"
  resource_group_name = azurerm_resource_group.shared.name
  location            = azurerm_resource_group.shared.location
  sku                 = "Standard"
  admin_enabled       = true
  tags                = local.tags
}
```
Now, during apply I have:

```txt
 sku :
"Managed" change to "Standard"

```

**Comment by yyoda** [comment]
I encountered the same problem and did some testing.
- I can create a new resource (I tried with the Basic SKU).
- However, when I run `terraform plan`, it detects a difference.
- If I run `terraform apply` again, it succeeds, but the difference is not resolved.

My current conclusion is that the only workaround is:

```hcl
  lifecycle {
    ignore_changes = [sku]
  }
```

 azure provider version: 3.107.0

**Comment by yyoda** [comment]
Including `sku` in `ignore_changes` revealed another problem. This problem is exposed when `zone_redundancy_enabled` is true. There doesn't seem to be a smart workaround...

```
│ Error: ACR zone redundancy can only be applied when using the Premium Sku
│ 
│   with module.app.azurerm_container_registry.main,
│   on ../../../modules/app/main.tf line 4, in resource "azurerm_container_registry" "main":
│    4: resource "azurerm_container_registry" "main" {
│ 
╵
```

**Comment by morinow** [comment]
Can confirm this behavior even for older versions of the provider (3.72.0). The provider is getting the following response from Azure:
```json
"sku":  {
    "name": "Basic",
    "tier": "Managed"
}
```

... which triggers the pending change.

**Comment by akashsinghal** [comment]
Update on this issue: This issue should now be mitigated. The ACR team detected a regression in the most recent deployment. We've reverted the change and rolled it out globally. Any GET requests to the registry resource should now reflect the correct SKU information.

**Comment by spowser** [comment]
@akashsinghal @tombuildsstuff  
Can confirm I am no longer seeing the plan showing changes.

**Comment by magodo** [comment]
@spowser As this is an API regression, which is now resolved on Azure side, I'm gonna close this issue for now. Please feel free to reopen if it is not the case on your side.
