### ISSUE TITLE
azurerm_log_analytics_workspace "Free" SKU is no longer a valid choice

### ISSUE THREAD

**Issue by The-Real-Justin** [hashicorp/terraform-provider-azurerm#26410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.108.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_workspace" "example" {
  name                = "law-example-aks-test"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Free"
  retention_in_days   = 7
}
```

### Debug Output/Panic Output

```shell
Error: performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidParameter: Workspaces cannot be created or updated to free, standard or premium tiers. see 'https://docs.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#free-trial-pricing-tier'. Operation Id: 'c479d5008ead9743b2b368256f78740f'
```

### References

https://learn.microsoft.com/en-us/azure/azure-monitor/logs/cost-logs#free-trial-pricing-tier

**Comment by Chambras** [comment]
Hi @The-Real-Justin Based on the article `Access to the legacy Free Trial pricing tier was limited on July 1, 2022. Pricing information for the Standalone and Per Node pricing tiers is available` [here](https://aka.ms/OMSpricing).
So, I think this behavior is normal.

**Comment by The-Real-Justin** [comment]
correct. After July 1, 2022, the free tier is no longer available.
