### ISSUE TITLE
vm_template argument 

### ISSUE THREAD

**Issue by saroshanthamalaka** [hashicorp/terraform-provider-azurerm#26435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Could you please provide sample template which can be used to specify for the argument.  There is no documentation available, there is sample template available in this which is incomplete

https://github.com/hashicorp/terraform-provider-azurerm/pull/24369/commits/011433a50c6da04a1e1fc26dc7c8511c8ffb1f70 

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_host_pool

### References

None

**Comment by sinbai** [comment]
Hi @saroshanthamalaka thank you for taking the time to raise this! I would like to explain that this forum is intended to be used for feature enhancements and bugs in the Azure Provider . So that we can keep this forum focused on that we instead ask that questions are raised using one of the [Community Resources](https://www.terraform.io/community). Thanks!

**Comment by saroshanthamalaka** [comment]
Hi @sinbai  Thank you for the reply. I raised the community forum as well.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this over on the community forum. With that in mind, I'm going to close this issue here.
