### ISSUE TITLE
``azurerm_api_management`` Error while creating a new APIM service - can't delete "echo-api"

### ISSUE THREAD

**Issue by Apokalypt** [hashicorp/terraform-provider-azurerm#26438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.109.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_api_management" "apim" {
  location            = "westeurope"
  name                = "test-debug-apim"
  publisher_email     = "<valid email>"
  publisher_name      = "Test"
  resource_group_name = "<valid group>"
  sku_name            = "Developer_1"
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/Apokalypt/46f1e5b9d8380869dd79cb979d37f5b5
```

### Expected Behaviour

- APIM service should be created
- Echo API should be deleted

### Actual Behaviour

- APIM service is created
- Echo API can't be deleted (most of the time) => `unexpected status 400 (400 Bad Request) with error: ValidationError: Invalid payload format.  Contract should have 'properties' specified.`

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

-> *Sometimes the full creation (service creation + API deletion) works correctly so you may have to repeat these steps 2 or 3 times... If that's the case don't forget to remove APIM service before*

**Comment by Apokalypt** [comment]
Based on my tries, it seems that the problem comes from Azure API but maybe it's due to an invalid body sent from Terraform

**Comment by sinbai** [comment]
Hi @Apokalypt thanks for opening this issue. In order to find the root cause, a Terraform configuration (containing dependent resources and variable values) and detailed steps would be of great help in quickly reproducing/troubleshooting the issue. Could you please provide the complete Terraform configuration and detailed repro steps to help reproduce this issue? Thanks in advanced.

**Comment by stephybun** [comment]
Seems to be related to https://github.com/hashicorp/terraform-provider-azurerm/issues/26386

**Comment by Apokalypt** [comment]
> Seems to be related to #26386

Yeah, apparently it has been fix by Azure... I will make a few try later to make sure everything is ok

**Comment by Apokalypt** [comment]
> Hi @Apokalypt thanks for opening this issue. In order to find the root cause, a Terraform configuration (containing dependent resources and variable values) and detailed steps would be of great help in quickly reproducing/troubleshooting the issue. Could you please provide the complete Terraform configuration and detailed repro steps to help reproduce this issue? Thanks in advanced.

This is the exact file configuration and steps I've done 😅 So, I'm not sure to understand what's missing. However, I will take some time to verify it to make sure that everything is ok because maybe some values are set automatically due to our Azure environment

**Comment by rcskosir** [comment]
Thanks for taking the time to submit this issue. It looks like this has been resolved on the Azure side as noted above. As such, I am going to mark this issue as closed. If that is not the case, please provide additional information including the version in which you are still experiencing this issue, thanks!
