### ISSUE TITLE
azurerm_site_recovery_replication_recovery_plan and Microsoft Azure fabrics

### ISSUE THREAD

**Issue by rlodev67** [hashicorp/terraform-provider-azurerm#26457]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.107.0

### Affected Resource(s)/Data Source(s)

azurerm_site_recovery_replication_recovery_plan

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replication_recovery_plan" "recovery_plan" {
  name = "MY-DRP"
  recovery_vault_id = "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/myrg/providers/Microsoft.RecoveryServices/vaults/myvault"
  source_recovery_fabric_id = "/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/myrg/providers/Microsoft.RecoveryServices/vaults/myvault/replicationFabrics/myvault-vmwarefabric"
  target_recovery_fabric_id = "Micrcosoft Azure"
  boot_recovery_group   {
    replicated_protected_items = ["/subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/myrg/providers/Microsoft.RecoveryServices/vaults/myvault/replicationFabrics/myvault-vmwarefabric/replicationProtectionContainers/myvaultreplicationcontainer/replicationProtectedItems/myvmname"]
  }
}
```

### Debug Output/Panic Output

```shell
**Error: parsing "Microsoft Azure": parsing the ReplicationFabric ID: the number of segments didn't match
│ 
│ Expected a ReplicationFabric ID that matched (containing 10 segments):
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.RecoveryServices/vaults/vaultValue/replicationFabrics/replicationFabricValue
│
│ However this value was provided (which was parsed into 0 segments):
│
│ > Microsoft Azure
│
│ The following Segments are expected:
│
│ * Segment 0 - this should be the literal value "subscriptions"
│ * Segment 1 - this should be the UUID of the Azure Subscription
│ * Segment 2 - this should be the literal value "resourceGroups"
│ * Segment 3 - this should be the name of the Resource Group
│ * Segment 4 - this should be the literal value "providers"
│ * Segment 5 - this should be the name of the Resource Provider [for example 'Microsoft.RecoveryServices']
│ * Segment 6 - this should be the literal value "vaults"
│ * Segment 7 - this should be the user specified value for this vault [for example "vaultValue"]
│ * Segment 8 - this should be the literal value "replicationFabrics"
│ * Segment 9 - this should be the user specified value for this replicationFabric [for example "replicationFabricValue"]│
│ The following Segments were parsed:
│
│ * Segment 0 - not found
│ * Segment 1 - not found
│ * Segment 2 - not found
│ * Segment 3 - not found
│ * Segment 4 - not found
│ * Segment 5 - not found
│ * Segment 6 - not found
│ * Segment 7 - not found
│ * Segment 8 - not found
│ * Segment 9 - not found**
```

### Expected Behaviour

The recovery plan created

### Actual Behaviour

terraform stop and returning the error mentionned before

### Steps to Reproduce

terraform plan

**Comment by tombuildsstuff** [comment]
hi @rlodev67 

Taking a look through here it appears that a different value is being provided than we're expecting:

```
│ Expected a ReplicationFabric ID that matched (containing 10 segments):
│
│ > /subscriptions/12345678-1234-9876-4563-123456789012/resourceGroups/example-resource-group/providers/Microsoft.RecoveryServices/vaults/vaultValue/replicationFabrics/replicationFabricValue
│
│ However this value was provided (which was parsed into 0 segments):
│
│ > Microsoft Azure
```

As such you'll need to reference a the ID of a Replication Fabric Resource here - if you're looking for the Provider to support Azure Fabric within Recovery Services then I'd suggest opening a new feature request to track that, since this is a configuration question (as the wrong value is being provided) I'm going to close this issue for the moment - but you should be able to fix this by updating the value being specified here.

Thanks!

**Comment by rlodev67** [comment]
Hi @tombuildsstuff ,

I'm not really agree. When I manually create the ressource and check over powershell or terraform import, the target_recovery_fabric_id is equal to "Microsoft Azure". It looks like the value accepted by the azurerm provider should be :
- the 10 segments which represents an id
OR
- "Microsoft Azure"

Thanks
