### ISSUE TITLE
"does not have authorization" when updating just tags on resources like vnets and route tables

### ISSUE THREAD

**Issue by TeamDman** [hashicorp/terraform-provider-azurerm#26498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.0

### AzureRM Provider Version

3.109.0

### Affected Resource(s)/Data Source(s)

- azurerm_virtual_network
- azurerm_route_table

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  skip_provider_registration = true
}
data "azurerm_resource_group" "main" {
  name = "MyResourceGroup"
}
resource "azurerm_virtual_network" "main" {
  resource_group_name = data.azurerm_resource_group.main.name
  name                = "tagfail"
  tags = merge(data.azurerm_resource_group.main.tags, {
    "bruh" = "fish" # change this before applying with less privileged principal that has Tag Contributor but not Contributor
  })
  location      = "canadacentral"
  address_space = ["10.0.0.0/24"]
}
```

### Debug Output/Panic Output

https://gist.github.com/TeamDman/1c7acead87da937e8b479f7385668304

### Expected Behaviour

Tag should have been updated

### Actual Behaviour

```
❯ az role assignment list --resource-group "MyResourceGroup" --assignee "teamy@teamdman.ca" --query "[].roleDefinitionName" -o tsv
Reader
Tag Contributor
```
```

  # azurerm_virtual_network.main will be updated in-place
  ~ resource "azurerm_virtual_network" "main" {
        id                      = "/subscriptions/redactedsubscriptionid/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualNetworks/tagfail"
        name                    = "tagfail"
      ~ tags                    = {
          ~ "bruh"           = "sock" -> "fish"
        }
        # (9 unchanged attributes hidden)
    }

: 0 to add, 1 to change, 0 to destroy.
```
```
╷
│ Error: updating Virtual Network (Subscription: "redactedsubscriptionid"
│ Resource Group Name: "MyResourceGroup"
│ Virtual Network Name: "tagfail"): performing CreateOrUpdate: unexpected status 403 (403 Forbidden) with error: AuthorizationFailed: The client 'teamy@teamdman.ca' with object id 'redactedteamyobjid' does not have authorization to perform action 'Microsoft.Network/virtualNetworks/write' over scope '/subscriptions/redactedsubscriptionid/resourceGroups/MyResourceGroup/providers/Microsoft.Network/virtualNetworks/tagfail' or the scope is invalid. If access was recently granted, please refresh your credentials.
│ 
│   with azurerm_virtual_network.main,
│   on main.tf line 8, in resource "azurerm_virtual_network" "main":
│    8: resource "azurerm_virtual_network" "main" {
│ 
╵
```

### Steps to Reproduce

1. `az login` using account with Contributor or higher
2. `terraform apply`
3. change the tag to be different
4. `az logout`
5. `az login` using account that has Tag Contributor but not Contributor
6. `terraform apply`
7. 😭

**Comment by sinbai** [comment]
Hi @TeamDman thanks for opening this issue. I would like to explain that Terraform manages Azure resources by calling Azure Rest APIs, the `403` error is returned by Azure Rest API instead of Terraform. So I assume that Terraform could not do anything about the current usage.

**Comment by TeamDman** [comment]
There has to be an alternative endpoint that is used by the portal for updating the tags, since the portal works. Will investigate

**Comment by TeamDman** [comment]
https://learn.microsoft.com/en-us/rest/api/resources/tags/create-or-update-at-scope?view=rest-resources-2021-04-01&tabs=HTTP

https://learn.microsoft.com/en-us/rest/api/resources/tags/update-at-scope?view=rest-resources-2021-04-01

A call to this endpoint instead of the specific resource endpoint should be performed for tag modifications, since principals may only have permissions to update tags.
