### ISSUE TITLE
AKS Kubelet Config - Support for serializeImagePulls and maxParallelImagePulls

### ISSUE THREAD

**Issue by JonathanSiemering** [hashicorp/terraform-provider-azurerm#26505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Add support for AKS kubelet configuration of serializeImagePulls and maxParallelImagePulls, so AKS nodes can download images in parallel.

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name           = "default"
    node_count     = 1
    vm_size        = "Standard_D2_v2"

    kubelet_config {
      serialize_image_pulls    = false
      max_parallel_image_pulls = 10
    }
  }

  identity {
    type = "SystemAssigned"
  }

  tags = {
    Environment = "Production"
  }
}
```

### References

https://kubernetes.io/docs/concepts/containers/images/#serial-and-parallel-image-pulls
https://kubernetes.io/docs/concepts/containers/images/#maximum-parallel-image-pulls

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
Hi @JonathanSiemering, thanks for raising this. I have checked the Azure AKS service, and these configs are currently not supported.
Found this: https://github.com/Azure/AKS/issues/3879 which looks relevant.

**Comment by JonathanSiemering** [comment]
Hi @hqhqhqhqhqhqhqhqhqhqhq, that i have missed. Luckily it's planned for development on the aks side already.
Can the issue stay open for the period of time or should i reopen it?

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
> Hi @hqhqhqhqhqhqhqhqhqhqhq, that i have missed. Luckily it's planned for development on the aks side already. Can the issue stay open for the period of time or should i reopen it?

I would recommend closing it for now and reopen it in future, thanks!

**Comment by JonathanSiemering** [comment]
> Hi @JonathanSiemering, thanks for raising this. I have checked the Azure AKS service, and these configs are currently not supported. Found this: [Azure/AKS#3879](https://github.com/Azure/AKS/issues/3879) which looks relevant.

Wait for AKS feature to be implemented.
