### ISSUE TITLE
azurerm_kubernetes_cluster and azurerm_kubernetes_cluster_node_pool keeps detecting changes when upgrade_settings block is blank

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#26517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.110.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster, azurerm_kubernetes_cluster_node_pool 

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
...

     dynamic "upgrade_settings" {
        for_each = var.enable_upgrade_max_surge ? [1] : []
           content {
             max_surge = var.upgrade_max_surge
           }
       }
}

resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pool" {
...

      # no upgrade_settings block is set

}

variable "enable_upgrade_max_surge" {
  type        = bool
  default     = false
}
```

### Debug Output/Panic Output

```shell
none
```

### Expected Behaviour

Terraform should not detect changes. We only have an optional dynamic block that defaults to false for the aks resource, but we dont even set it for the node pool. However, terraform keeps planning to remove the block.

### Actual Behaviour
```hcl
  # module.aks.azurerm_kubernetes_cluster.aks[0] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster" "aks" {
        id                                  = "HIDDEN"
        name                                = "td06a-duc0md6-aks"
        
        # (40 unchanged attributes hidden)

      ~ default_node_pool {
            name                          = "default"
         
            # (33 unchanged attributes hidden)

          - upgrade_settings {}
        }

        # (8 unchanged blocks hidden)
    }

  # module.aks.azurerm_kubernetes_cluster_node_pool.additional_node_pool["cnrwm"] will be updated in-place
  ~ resource "azurerm_kubernetes_cluster_node_pool" "additional_node_pool" {
        id                            = "HIDDEN"
        name                          = "cnrwm"
        tags                          = {}
        # (33 unchanged attributes hidden)

      - upgrade_settings {}
    }
```

**Comment by fgarcia-cnb** [comment]
apologies, this issue seems to be the same as #26280

**Comment by mybayern1974** [comment]
Thank you @fgarcia-cnb for filing this issue and identifying a duplicate issue filed earlier. With that I'm closing this issue to have the previous one #26280 attract focus and you can subscribe that one.
