### ISSUE TITLE
azurerm_api_management_policy_fragment - not able to deploy policy fragment

### ISSUE THREAD

**Issue by nikhil0499** [hashicorp/terraform-provider-azurerm#26529]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.0

### AzureRM Provider Version

3.90.0

### Affected Resource(s)/Data Source(s)

azurerm_api_management_policy_fragment

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_policy_fragment" "policy_fragments" {
  api_management_id = var.apim_instance_ids[var.environment]
  name              = var.name
  format            = "xml"
  value             = var.xml_file_path
}
```

### Debug Output/Panic Output

```shell
Error: Invalid resource type
│ 
│   on ../../../../modules/api_policy_fragments/main.tf line 7, in resource "azurerm_api_management_policy_fragment" "policy_fragments":
│    7: resource "azurerm_api_management_policy_fragment" "policy_fragments" {
│ 
│ The provider hashicorp/azurerm does not support resource type
│ "azurerm_api_management_policy_fragment".
```

### Expected Behaviour

Should have created a Policy Fragment in Azure APIM Instance.

### Actual Behaviour

Error as mentioned above.

**Comment by stephybun** [comment]
Thanks for raising this issue @nikhil0499. The resource `azurerm_api_management_policy_fragment` was added in v3.105.0 of the provider.

Closing since this should be fixed by upgrading the version of the provider to v3.105.0 or higher.
