### ISSUE TITLE
is_hns_enabled is destructive

### ISSUE THREAD

**Issue by m1nkeh** [hashicorp/terraform-provider-azurerm#26522]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.0

### AzureRM Provider Version

3.110.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "rg1" {
  name     = "my_rg"
  location = "uksouth"
}

resource "azurerm_storage_account" "sa1" {
  name                     = "lkdgh8w4"
  resource_group_name      = azurerm_resource_group.rg1.name
  location                 = azurerm_resource_group.rg1.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  # is_hns_enabled           = true
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

WHen uncommenting the is_hns_enabled it should be switched on, or at least give an error as to why it cannot be. It is possible to enable this on the Azure portal, but not via Terraform.

### Actual Behaviour

Storage account is recreated

**Comment by magodo** [comment]
@m1nkeh This property is not a simple toggle like other updatable ones. If you do it from Portal, you'll see:

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/7970698/6497b393-4714-4d3f-97a0-6d758dd411fe)

As it has additional preconditions, which can conflict other properties, and also it takes hours to do the upgrade. We want to keep it a "force-new" property to avoid unnecessary confusions.

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).

**Comment by m1nkeh** [comment]
Hey @magodo, thanks for the response.

Yes, I'm aware of the reviewing and checking process.. hadn't fully appreciated that the upgrade may take hours.. which of course is completely correct if it's been there a while. I was checking and testing and even my empty storage account took at least 10 mins to do the whole process.

As a point of interest, a Storage Account created via Terraform will fail it seems as there are some implicit defaults around retention of data.

**Comment by magodo** [comment]
> As a point of interest, a Storage Account created via Terraform will fail it seems as there are some implicit defaults around retention of data. Not sure if that is a bug or a feature also?

Can you elaborate more about in which case the creation will fail?

**Comment by m1nkeh** [comment]
Not the creation, but the turning on of HNS via the portal will fail.

Create a ‘default’ storage account on the portal, NHS is ok
Create a ‘default’ storage account via terraform, HNS fails

**Comment by magodo** [comment]
@m1nkeh That is not a failure, but due to the `is_hns_enabled` property is intentionally marked as `ForceNew` in the provider, in which case a change of it will cause this resource delete then create.
