### ISSUE TITLE
Allow connection_string for linux_function_app that references its own identity

### ISSUE THREAD

**Issue by NathZ1** [hashicorp/terraform-provider-azurerm#26527]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Connecting Azure Function App to Azure SQL Database requires a connection string, which in terraform is configured using the connection_string block. MS preference is to use managed identity to remove the requirement for secrets in config, with connection string required to be in this format: 

`Server=demo.database.windows.net; Authentication=Active Directory Managed Identity; User Id=ClientIdOfManagedIdentity; Database=testdb`
https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity

The managed identity of the Function App is not known until after its own creation, so how can we create a connection string like this? This seems to be an issue with self-reference so I would guess the solution would be to create functionality internally that can achieve this. 

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_function_app

### References

https://learn.microsoft.com/en-us/azure/azure-functions/functions-identity-access-azure-sql-with-managed-identity

**Comment by xiaxyi** [comment]
@NathZ1 Thanks for raising this issue, the format of the connection string that you shared doesn't contains the function app's managed identity. 

The part `Authentication=Active Directory Managed Identity;` in the connection string (
`Server=demo.database.windows.net; Authentication=Active Directory Managed Identity; User Id=ClientIdOfManagedIdentity; Database=testdb`) is telling the driver about the identity type as mentioned in this [doc](https://learn.microsoft.com/en-us/azure/app-service/tutorial-connect-msi-sql-database?tabs=windowsclient%2Cefcore%2Cdotnet):
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/92154856/e7a257dd-73fd-4289-af7d-1b64282b1405)
The sample used the default type.

More reference:
![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/92154856/204df8b3-3faa-4314-b280-2f1befedfe79)

https://learn.microsoft.com/en-us/azure/azure-sql/database/authentication-azure-ad-user-assigned-managed-identity?view=azuresql

Let me know if I misunderstood your question.

**Comment by NathZ1** [comment]
Thanks for responding @xiaxyi!

Isn't the "ClientIdOfManagedIdentity" parameter within the connection string the function app's managed identity? Or is this only used for user assigned managed identity and not system assigned?

**Comment by NathZ1** [comment]
Yep, it's only required for user assigned managed identity. When I saw the name I assumed system assigned. Closing. Thanks for you help!

**Comment by xiaxyi** [comment]
@NathZ1 No problems, glad to see it worked!
