### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert: custom_webhook_payload values are not included in triggered alerts

### ISSUE THREAD

**Issue by nikolai-fra** [hashicorp/terraform-provider-azurerm#26532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.1.2

### AzureRM Provider Version

3.110.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_scheduled_query_rules_alert

### Terraform Configuration Files

```hcl
locals {
  custom_webhook_properties = {
    someproperty = "some-value"
}
resource "azurerm_monitor_action_group" "action_group_webhook" {
  name                = "name"
  resource_group_name = "rg-test"
  short_name          = "test"
  webhook_receiver {
    name        = "<my_name>"
    service_uri = "<my-uri>"
    use_common_alert_schema = true
  }
}
resource "azurerm_monitor_scheduled_query_rules_alert" "alert-node-ready-count" {
  name                = "alert-aks-node-ready-count-${azurerm_kubernetes_cluster.aks.name}"
  location            = "westeurope"
  resource_group_name = "rg-test"
  data_source_id      = <scope to your law>
  enabled             = true
  query               = <<-QUERY
    KubeNodeInventory
      | where Status != "Ready" and TimeGenerated > ago(10min)
      | summarize by Computer
QUERY
  severity            = 0
  frequency           = 5
  time_window         = 10

  trigger {
    operator  = "GreaterThan"
    threshold = 1
  }
  action {
    action_group           = [azurerm_monitor_action_group.action_group_webhook.id]
    custom_webhook_payload = jsonencode(local.custom_webhook_properties)
  }
}
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

Alerts generated by this scheduled query alert definition should contain the defined custom webhook properties in the body of the webhook.

### Actual Behaviour

The custom webhook properties are not send with the webhook by Azure, when triggerd..

It seems this is correlated with the Azure API version used by the azurerm provider to create the log search alert rule.

Using the v3.110 provider the json view of the log search alert rule in the azure portal shows per default the API Version "2021-08-01". Here the custom webhook properties are NOT listed:
```
"properties": {
        "createdWithApiVersion": "2018-04-16",
        ...
        "actions": {
            "actionGroups": [
                "/subscriptions/1BB4BDB5-CA1B-4B74-B45B-24FA098E629D/<action-group-id>"
            ]
        }
    }
```

When showing the same resource in an older api version like "2018-04-16" the customWebhookPayload is shown:
```
"properties": {
        "createdWithApiVersion": "2018-04-16",
        ...
        "action": {
            "severity": "0",
            "aznsAction": {
                "actionGroup": [
                    "/subscriptions/1BB4BDB5-CA1B-4B74-B45B-24FA098E629D/<action-group-id>"
                ],
                "customWebhookPayload": "{\"<mycustompayloadjson>\"}"
            },
    }
```

When creating a new alert via the azure portal with custom webhook properties, then these properties are shown in the json view for the new API Version (and the old ones too):
```
"properties": {
        "createdWithApiVersion": "2023-03-15-preview",
        ...
        "actions": {
            "actionGroups": [
                "/subscriptions/1bb4bdb5-ca1b-4b74-b45b-24fa098e629d/<my_action_group>"
            ],
            "customProperties": {
                "test": "123"
            }
        }
    }
```

It seems the component on azure side sending the concrete webhooks is probably using a newer api version and therefore not including the webhook properties of alerts of older api versions.
To fix this it is probably the best to upgrade the used api version in the azurerm provider?

**Comment by teowa** [comment]
Hi @nikolai-fra , thanks for the issue! 
The blog https://cloudadministrator.net/2021/11/04/azure-monitor-log-alert-v2/ may have help resolve your issue regards webhook of the scheduled query alert(also called log alert). We are unable to upgrade API version for `azurerm_monitor_scheduled_query_rules_alert` resource, because the API schema is not compatible between `2018-04-16` and later version. The `azurerm_monitor_scheduled_query_rules_alert_v2` is using the `2023-03-15-preview` version API, please change to use it.

**Comment by nikolai-fra** [comment]
Oh that's perfect. I wasn't able to find this during my research :/
May I suggest to add a warning on the docs page for the old v1 alert [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert)?
I opened the following PR to do so: https://github.com/hashicorp/terraform-provider-azurerm/pull/26553
