### ISSUE TITLE
I want to fetch the vm os and data disk and create the snapshot form them

### ISSUE THREAD

**Issue by pre-yugandhar** [hashicorp/terraform-provider-azurerm#26549]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.0.0

### AzureRM Provider Version

3.0.0

### Affected Resource(s)/Data Source(s)

data.azurerm_virtual_machine.main

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  required_version = ">= 1.0.0"
}

data "azurerm_virtual_machine" "main_vm" {
  name                = "abcd-rnd"
  resource_group_name = "abcd-rg"
}

output "vm_id" {
  value = data.azurerm_virtual_machine.main_vm.id
}

output "vm_location" {
  value = data.azurerm_virtual_machine.main_vm.location
}

output "vm_name" {
  value = data.azurerm_virtual_machine.main_vm.name
}
```

### Debug Output/Panic Output

```shell
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }

  required_version = ">= 1.0.0"
}

data "azurerm_virtual_machine" "main_vm" {
  name                = "terraform-rnd"
  resource_group_name = "Terraform-rg"
}

output "vm_id" {
  value = data.azurerm_virtual_machine.main_vm.id
}

output "vm_location" {
  value = data.azurerm_virtual_machine.main_vm.location
}

output "vm_name" {
  value = data.azurerm_virtual_machine.main_vm.name
}
```

**Comment by tombuildsstuff** [comment]
hi @pre-yugandhar 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
