### ISSUE TITLE
azurerm_recovery_services_protection_policy_vm missing day-based retention

### ISSUE THREAD

**Issue by ranokarno** [hashicorp/terraform-provider-azurerm#2656]
Terraform v0.11.10
### Affected Resource(s)
* `azurerm_recovery_services_protection_policy_vm`

### Terraform Configuration Files

Can anyone help to share if current Protection Policy VM able to support retention in daily based
[https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protection_policy_vm.html](url)

>   retention_monthly = {
>     count    = 7
>     weekdays = ["Sunday", "Wednesday"]
>     weeks    = ["First", "Last"]
>   }
> 
>   retention_yearly = {
>     count    = 77
>     weekdays = ["Sunday"]
>     weeks    = ["Last"]
>     months   = ["January"]
>   }

current retention only applicable for weekly based. It should also allow user to use daily based retention

> retention_yearly = {
>     count    = 5
>     days    = ["1", "2", ..., "Last"]
>     months   = ["December"]
>   }

when **days** in use, `**weekdays & weeks**` parameters are disabled/invalid

### References
ARM_template

>          "retentionPolicy": {
>             "dailySchedule": {
>               "retentionTimes": "[parameters('scheduleRunTimes')]",
>               "retentionDuration": {
>                   "count": "[parameters('dailyRetentionDurationCount')]",
>                   "durationType": "Days"
>               }
>             },
>             "monthlySchedule": {
>               "retentionScheduleFormatType": "Daily",
>               "retentionScheduleDaily": {
>                 "daysOfTheMonth": [
>                   {
>                     "date": 1,
>                     "isLast": true
>                   }
>                 ]
>               },
>               "retentionScheduleWeekly": null,
>               "retentionTimes": "[parameters('scheduleRunTimes')]",
>               "retentionDuration": {
>                 "count": "[parameters('monthlyRetentionDurationCount')]",
>                 "durationType": "Months"
>               }
>             },
>             "yearlySchedule": {
>               "retentionScheduleFormatType": "Daily",
>               "monthsOfYear": "[parameters('monthsOfYear')]",
>               "retentionScheduleDaily": {
>                 "daysOfTheMonth": [
>                   {
>                     "date": 1,
>                     "isLast": true
>                   }
>                 ]
>               },
>               "retentionScheduleWeekly": null,
>               "retentionTimes": "[parameters('scheduleRunTimes')]",
>               "retentionDuration": {
>                 "count": "[parameters('yearlyRetentionDurationCount')]",
>                 "durationType": "Years"
>               }
>             },

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
