### ISSUE TITLE
azurerm_search_service should support the "Allow Azure services on the trusted services list to access this search service"-flag

### ISSUE THREAD

**Issue by mkemmerz** [hashicorp/terraform-provider-azurerm#26575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The Azure Search Service should have an attribute to disable / enable the flag to "Allow Azure services on the trusted services list to access this search service".

This was recently introduced by Microsoft:
<img width="1091" alt="image" src="https://github.com/hashicorp/terraform-provider-azurerm/assets/46575727/3f1a6b4e-2a91-4c32-93e4-95f50b12c02b">

The flag is required if you disable the networking and use additional AI resources like Open AI that needs to reach the Search Service.

### New or Affected Resource(s)/Data Source(s)

azurerm_search_service

### Potential Terraform Configuration

```hcl
resource "azurerm_search_service" "example" {
  name                = "example-resource"
  ...
  network_bypass = "AzureServices"
}
```

### References

This issue requires the 1.4.0 of the search go sdk before it can be implemented: https://github.com/Azure/azure-sdk-for-go/releases/tag/sdk%2Fresourcemanager%2Fsearch%2Farmsearch%2Fv1.4.0-beta.1 because it adds support for:
`New field Bypass in struct NetworkRuleSet`

**Comment by vishbhalla** [comment]
Any work arounds for this in the mean time (apart from click ops of course)? I don't see anything in the CLI.

**Comment by henrydleao** [comment]
Hey guys, you can add the following snippet bellow the Terraform code that creates the AI Search:

`resource "azapi_update_resource" "ai_search_allow_azure_services" {
  type        = "Microsoft.Search/searchServices@2024-06-01-Preview"
  resource_id = azurerm_search_service.ai_search.id

  body = { 
    properties = {
      networkRuleSet = {
        bypass = "AzureServices"
      }
    }
  }
}`

It will call the API and update the resource with just what you want. Fix the resource_id to match your own AI Search resource in the Terraform code.

**Comment by aeimer** [comment]
@henrydleao many thanks for the tip!

If you were wondering what else can be set and where the docs are:

`None`, `AzurePortal`, `AzureServices`

https://learn.microsoft.com/en-us/rest/api/searchmanagement/services/update?view=rest-searchmanagement-2024-06-01-preview&preserve-view=true&tabs=HTTP#searchbypass
