### ISSUE TITLE
provider does not support ed25519 ssh keys while azure does.

### ISSUE THREAD

**Issue by jkroepke** [hashicorp/terraform-provider-azurerm#26587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.0

### AzureRM Provider Version

3.101.0

### Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Terraform Configuration Files

```hcl
-
```

### Debug Output/Panic Output

```shell
-
```

### Expected Behaviour

The Terraform provider should support ed25519 keys like the portal does

![image](https://github.com/hashicorp/terraform-provider-azurerm/assets/1560587/5c48e710-44cd-4ee0-b400-e7bcb796042e)

### Actual Behaviour

There is an local validation which is not in sync with the Azure capabilities

https://github.com/hashicorp/terraform-provider-azurerm/blob/e5efc92cda078405c8ea74ec5c00311f52278115/internal/services/compute/validate/ssh_key.go#L38-L39

### References

https://azure.microsoft.com/en-us/updates/v2/SSH-Key-Support-for-Linux-VMs

**Comment by ms-zhenhua** [comment]
@jkroepke, thank you reporting this issue. I have created a new PR to support this new type of SSH key.

**Comment by jkroepke** [comment]
@makkes If Azure says, the feature is released for VMs doesn't mean that the feature is availible for Kubernetes Worker Pools.

**Comment by makkes** [comment]
https://github.com/Azure/AKS/issues/4431

**Comment by magodo** [comment]
Fixed by #27202
