### ISSUE TITLE
Cannot downgrade Storage Account from v2 to v1 because of access_tier validation

### ISSUE THREAD

**Issue by kichel98** [hashicorp/terraform-provider-azurerm#26596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

~> 1.1

### AzureRM Provider Version

3.104.2

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
Current configuration (which storage account was installed with):
resource "azurerm_storage_account" "test-functions-sa" {
  name                            = "testfunctionstorage"
  location                        = var.location
  resource_group_name             = var.resource_group_name
  account_tier                    = "Standard"
  access_tier                     = "Hot"
  account_replication_type        = "GZRS"
  account_kind                    = "StorageV2"
  min_tls_version                 = "TLS1_2"
  is_hns_enabled                  = "true"
  allow_nested_items_to_be_public = "false"
  identity {
    type = "SystemAssigned"
  }

  network_rules {
    default_action             = "Deny"
    ip_rules                   = var.ips
    virtual_network_subnet_ids = [local.test-snet-func_id]
    bypass                     = [ "AzureServices" ]
  }

  blob_properties {
    delete_retention_policy {
      days = 7
    }
    container_delete_retention_policy {
      days = 7
    }
  }
}


Future configuration (which I want to install now with and it fails):
resource "azurerm_storage_account" "test-functions-sa" {
  name                            = "testfunctionstorage"
  location                        = var.location
  resource_group_name             = var.resource_group_name
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  account_kind                    = "Storage"
  min_tls_version                 = "TLS1_2"
  is_hns_enabled                  = "true"
  allow_nested_items_to_be_public = "false"
  identity {
    type = "SystemAssigned"
  }

  network_rules {
    default_action             = "Deny"
    ip_rules                   = var.ips
    virtual_network_subnet_ids = [local.test-snet-func_id]
    bypass                     = [ "AzureServices" ]
  }

  blob_properties {
    delete_retention_policy {
      days = 7
    }
    container_delete_retention_policy {
      days = 7
    }
  }
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

│ Error: 1 error occurred:
│ 	* `access_tier` is only available for accounts of kind: [BlobStorage StorageV2 FileStorage]
│ 
│ 
│ 
│   with azurerm_storage_account.test-functions-sa,
│   on test-functions.tf line 4, in resource "azurerm_storage_account" "test-functions-sa":
│    4: resource "azurerm_storage_account" "test-functions-sa" {
│ 
╵
```

### Expected Behaviour

Current v2 storage account (`account_kind=StorageV2`) should be removed and legacy v1 storage account (`account_kind=Storage`) should be installed.

### Actual Behaviour

Terraform plan failed on `access_tier` validation even though `access_tier` was removed from configuration (it cannot be set for `account_kind=Storage`),

**Comment by magodo** [comment]
@kichel98 I don't find a document from Azure says it supports the downgrade. There are several answers from StackOverflow saying this is not supported. So it seems meaningless to pass this validation.

**Comment by tombuildsstuff** [comment]
@kichel98 yeah, further to @magodo's comments AFAIK there isn't a downgrade path available (since it's a one-way upgrade process) - so I think the behaviour we have here is correct (in that you'd need to recreate this resource in order to make this change). Would you be able to provide a document showing that this is possible?

**Comment by kichel98** [comment]
@magodo @tombuildsstuff Yes, I know that downgrade from v2 to v1 with zero downtime and data migration is not possible, but I thought that in this case Terraform would simply delete v2 storage account and create new v1 storage account. Isn't it an expected behaviour in such cases? Similarly, like e.g. changing `content_md5` in `azurerm_storage_blob` forces a new resource to be created.

This validation error makes no sense for me, because I am trying to install a storage account, `access_tier` is not set in my configuration but I get an error that it must not be set.
