### ISSUE TITLE
Complete documentation for attribute ramp_down_force_logoff_users in azurerm_virtual_desktop_scaling_plan

### ISSUE THREAD

**Issue by fabrisodotps1** [hashicorp/terraform-provider-azurerm#26594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The text for the attribute ramp_down_force_logoff_users in https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_desktop_scaling_plan is not finished. The possible values are missing.

![Doc_azurerm_virtual_desktop_scaling_plan](https://github.com/hashicorp/terraform-provider-azurerm/assets/59888124/edad228f-5764-4551-b9de-8fd32ee7b2cc)

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_desktop_scaling_plan

**Comment by Chambras** [comment]
Nice catch @fabrisodotps1 
looking into what happened!
