### ISSUE TITLE
azurerm_automation_runbook - Inappropriate value for attribute "job_schedule": element 0: attributes "job_schedule_id", "parameters", and "run_on" are required.

### ISSUE THREAD

**Issue by joakimlemb** [hashicorp/terraform-provider-azurerm#26603]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

3.111.0

### Affected Resource(s)/Data Source(s)

azurerm_automation_runbook

### Terraform Configuration Files

```hcl
resource "azurerm_automation_runbook" "example" {
  location                = local.location
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  name                    = "example"
  log_verbose             = "true"
  log_progress            = "true"
  description             = "example"
  runbook_type            = "PowerShell72"
  
  job_schedule = [
    {
      schedule_name   = azurerm_automation_schedule.example.name
    }
  ]

  content = "example"

}

resource "azurerm_automation_schedule" "example" {
  resource_group_name     = azurerm_resource_group.example.name
  automation_account_name = azurerm_automation_account.example.name
  name                    = "example"
  frequency               = "Week"
  interval                = 1
  timezone                = "Etc/UTC"
  start_time              = "2024-11-12T05:00:00+01:00"
  week_days               = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
}
```

### Debug Output/Panic Output

```shell
Error: Incorrect attribute value type
│
│   on automation.tf line 26, in resource "azurerm_automation_runbook" "example":
│   26:   job_schedule = [
│   27:     {
│   28:       schedule_name   = azurerm_automation_schedule.example.name
│   29:     }
│   30:   ]
│
│ Inappropriate value for attribute "job_schedule": element 0: attributes "job_schedule_id", "parameters", and "run_on" are required.
```

### Expected Behaviour

Combine schedule to runbook

### Actual Behaviour

Error: Incorrect attribute value type
│
│   on automation.tf line 26, in resource "azurerm_automation_runbook" "example":
│   26:   job_schedule = [
│   27:     {
│   28:       schedule_name   = azurerm_automation_schedule.example.name
│   29:     }
│   30:   ]
│
│ Inappropriate value for attribute "job_schedule": element 0: attributes "job_schedule_id", "parameters", and "run_on" are required.

### Steps to Reproduce

terraform apply

### Important Factoids

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_runbook#job_schedule

### References

Terraform doc states that this should work:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_runbook#job_schedule

Currently implemented workaround using "azurerm_automation_job_schedule" resource rather than using the job_schedule block in azurerm_automation_runbook, which works fine.

**Comment by liuwuliuyun** [comment]
Hi @joakimlemb , thanks for bringing this to our attention. While attempting to replicate it, I noticed that the job_schedule block needs to be utilized as demonstrated in the following code snippet.
```
resource "azurerm_automation_runbook" "example" {
  location                = azurerm_resource_group.test.location
  resource_group_name     = azurerm_resource_group.test.name
  automation_account_name = azurerm_automation_account.test.name
  name                    = "example"
  log_verbose             = "true"
  log_progress            = "true"
  description             = "example"
  runbook_type            = "PowerShell72"

  job_schedule {
    schedule_name = azurerm_automation_schedule.example.name
  }


  content = "example"

}
```
Could you please try using it this way to see if it resolves your issue?
