### ISSUE TITLE
v3.112.0 breaks terraform plan with resource provider cache errors (403) 

### ISSUE THREAD

**Issue by circa10a** [hashicorp/terraform-provider-azurerm#26628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.4

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

Could be provider config.I don't think it's a particular resource

### Terraform Configuration Files

There's a lot and I can't pinpoint what exactly is causing this issue yet. I'm not sure that it matters since v3.111.0 seems to work fine

```hcl
provider "azurerm" {
  disable_correlation_request_id = false
  environment                    = "public"
  skip_provider_registration     = true
  storage_use_azuread            = true
  subscription_id                = <sub id>
  features {
    application_insights {
      disable_generated_rule = false
    }
    cognitive_account {
      purge_soft_delete_on_destroy = true
    }
    key_vault {
      purge_soft_delete_on_destroy               = false
      purge_soft_deleted_certificates_on_destroy = false
      purge_soft_deleted_keys_on_destroy         = false
      purge_soft_deleted_secrets_on_destroy      = false
      recover_soft_deleted_key_vaults            = true
      recover_soft_deleted_certificates          = true
      recover_soft_deleted_keys                  = true
      recover_soft_deleted_secrets               = true
    }
    log_analytics_workspace {
      permanently_delete_on_destroy = true
    }
    resource_group {
      prevent_deletion_if_contains_resources = true
    }
  }
}

```

### Debug Output/Panic Output

```shell
│ Error: populating Resource Provider cache: listing Resource Providers: loading results: unexpected status 403 (403 Forbidden) with error: AuthorizationFailed: The client '<principal id>' with object id '<principal id>' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/sub id>' or the scope is invalid. If access was recently granted, please refresh your credentials.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"],
│   on providers.tf line 48, in provider "azurerm":
│   48: provider "azurerm" {
│ 
╵
```

### Expected Behaviour

Terraform plan should succeed with v3.112.0

### Actual Behaviour

Terraform plan fails with 3.112.0, but succeeds with 3.111.0

### Steps to Reproduce

terraform plan with 3.111.0

### Important Factoids

Previous version works, latest version does not

**Comment by circa10a** [comment]
I'm struggling to find any major differences in the requests made with v3.111.0 and v3.112.0 when setting `TF_LOG=debug`

### v3.112.0 (403)

```log
============================ End AzureAD Request =============================: timestamp=2024-07-12T22:53:51.228Z
2024-07-12T22:53:51.238Z [DEBUG] provider.terraform-provider-azurerm_v3.112.0_x5: AzureRM Request: 
GET /subscriptions/<subscription id>/providers?api-version=2022-09-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 providers/2022-09-01) HashiCorp Terraform/1.5.4 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.112.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Accept: application/json; charset=utf-8; IEEE754Compatible=false
Content-Type: application/json; charset=utf-8
Odata-Maxversion: 4.0
Odata-Version: 4.0
X-Ms-Correlation-Request-Id: d5331fd4-1c50-0dfc-59ac-8c25ab340b52
Accept-Encoding: gzip: timestamp=2024-07-12T22:53:51.238Z
2024-07-12T22:53:51.238Z [DEBUG] provider.terraform-provider-azurerm_v3.112.0_x5: GET https://management.azure.com/subscriptions/<subscription id>/providers?api-version=2022-09-01: timestamp=2024-07-12T22:53:51.238Z
2024-07-12T22:53:51.251Z [DEBUG] provider.terraform-provider-azurerm_v3.112.0_x5: AzureRM Response for https://management.azure.com/subscriptions/7bcbf7c2-0e76-4f2d-ada2-d6d2540214cb/providers?api-version=2022-09-01: 
HTTP/2.0 403 Forbidden
```

### v3.111.0 (200)

```log
============================= End AzureAD Request =============================: timestamp=2024-07-12T23:05:45.028Z
2024-07-12T23:05:45.031Z [DEBUG] provider.terraform-provider-azurerm_v3.111.0_x5: AzureRM Request: 
GET /subscriptions/<subscription id>/providers?api-version=2022-09-01 HTTP/1.1
Host: management.azure.com
User-Agent: HashiCorp/go-azure-sdk (Go-http-Client/1.1 providers/2022-09-01) HashiCorp Terraform/1.5.4 (+https://www.terraform.io) Terraform Plugin SDK/2.10.1 terraform-provider-azurerm/3.111.0 pid-222c6c49-1b0a-5959-a213-6608f9eb8820
Accept: application/json; charset=utf-8; IEEE754Compatible=false
Content-Type: application/json; charset=utf-8
Odata-Maxversion: 4.0
Odata-Version: 4.0
X-Ms-Correlation-Request-Id: 46e8f0c4-9d5c-472b-6113-13ca4ebb21a8
Accept-Encoding: gzip: timestamp=2024-07-12T23:05:45.031Z
2024-07-12T23:05:45.031Z [DEBUG] provider.terraform-provider-azurerm_v3.111.0_x5: GET https://management.azure.com/subscriptions/<subscription id>/providers?api-version=2022-09-01: timestamp=2024-07-12T23:05:45.031Z
HTTP/2.0 200 OK
```

**Comment by dave-irvine** [comment]
The most recent commits to touch resource provider registration seem to be for PR https://github.com/hashicorp/terraform-provider-azurerm/pull/26574

I'm tagging @manicminer here to maybe look if that code (which should only affect 4.x) has somehow leaked back to the 3.x release?

**Comment by manicminer** [comment]
Thanks @circa10a, @dave-irvine for reporting this. You are correct that changes to resource provider registrations have been merged, that are due to go live in v4.0 of the provider but should not affect 3.x versions.

We have always attempted to read the registered resource providers for a subscription, and the logic here has not changed in #26574. I don't see any obvious cause for the error you're seeing, since the two API calls are exactly the same as far as I can tell? Have you perhaps recently provisioned this subscription? It can take some time for permissions to take effect, especially when using Azure CLI authentication.

That said, there is a related PR #26630 which may help resolve your issue. Once this is merged, specifying the environment variable `ARM_PROVIDER_ENHANCED_VALIDATION=false` in addition to the provider property `skip_provider_registration = true`, should allow you to skip reading the registered RPs in the event that you don't have permission to do so. We recommend running Terraform with this permission however, since generally we assume (and have done so for a long time) that this is the case.

**Comment by circa10a** [comment]
I can't explain it either, but I still able to reproduce as of today

**Comment by manicminer** [comment]
@circa10a Is that with a build from source? The PR mentioned above will be shipped in this week's release.

**Comment by circa10a** [comment]
@manicminer no I installed v3.112.0 via terraform init

**Comment by manicminer** [comment]
@circa10a OK thanks, can you try with v3.113.0 when it's released this week, setting [env var] `ARM_PROVIDER_ENHANCED_VALIDATION=false` and [provider config] `skip_provider_registration = true` and advise if this resolves it for you? Thanks :)

**Comment by circa10a** [comment]
> @circa10a OK thanks, can you try with v3.113.0 when it's released this week, setting [env var] `ARM_PROVIDER_ENHANCED_VALIDATION=false` and [provider config] `skip_provider_registration = true` and advise if this resolves it for you? Thanks :)

No changes unfortunately

**Comment by circa10a** [comment]
v3.113.0 has resolved the issue with no changes. I did not have to set ARM_PROVIDER_ENHANCED_VALIDATION=false

**Comment by manicminer** [comment]
@circa10a That's great, thanks for reporting back 👍

**Comment by Jordanbird96** [comment]
@manicminer This issue still persists. v3.111.0 works perfectly. Any newer versions produce the same error. I've tried 3.112.0, 113.0, 114.0 & 115.0.

Error: populating Resource Provider cache: listing Resource Providers: loading results: unexpected status 403 (403 Forbidden) with error: AuthorizationFailed: The client 'client-id' with object id 'object-id' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/sub-id'

The subscription and setup we are using has been in place for 3 years.

provider "azurerm" {
  alias                      = "alias-name"
  subscription_id            = "sub-id" 
  skip_provider_registration = true

  features {}
}

**Comment by gg3orgiev** [comment]
I am on v.3.115.0 and had the same issue. Adding ARM_PROVIDER_ENHANCED_VALIDATION=false, solves it for me.
