### ISSUE TITLE
Support for Dev Center Network Connections

### ISSUE THREAD

**Issue by damienaicheh** [hashicorp/terraform-provider-azurerm#26648]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Dev Centers needs to be connected to internal networks using Network Connections.

Those 2 elements are missing:

- https://learn.microsoft.com/en-us/azure/templates/microsoft.devcenter/2022-11-11-preview/devcenters/attachednetworks?pivots=deployment-language-bicep
- https://learn.microsoft.com/en-us/azure/templates/microsoft.devcenter/2023-04-01/networkconnections?pivots=deployment-language-bicep

### New or Affected Resource(s)/Data Source(s)

azurerm_dev_center

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/23367

**Comment by webstean** [comment]
Example azapi config, if that helps:
```
resource "azapi_resource" "devbox-networkconnections" {
  for_each = azurerm_dev_center.devbox
  ## one per region
  ## for_each = local.regions

  type = "Microsoft.DevCenter/networkConnections@2023-04-01"
  name = "${each.value.name}-network01"

  // resource group id for the parent id!!
  ## parent_id = azurerm_resource_group.devcenter[each.key].id
  parent_id = azurerm_resource_group.devcenter-connection[each.key].id
  location  = each.value.location
  body = jsonencode({
    properties = {
      domainJoinType = "AzureADJoin"
      ## HybridAzureADJoin needs the following:
      ##  domainName = "string"
      ##  domainPassword = "string"
      ##  domainUsername = "string"
      ##  organizationUnit = "string"

      ## needs to be new - so cannot already exist, so we let azure manage this itself 
      ## networkingResourceGroupName = "${var.prefix}-devcenter-network-rg"
      subnetId = data.azurerm_subnet.lab.id
    }
  })
  tags = each.value.tags
  lifecycle {
    create_before_destroy = true
  }
}
```

**Comment by damienaicheh** [comment]
Hi @webstean, thanks for the support.

I saw that we have the ability to create nework connections now with the ressources `azurerm_dev_center_network_connection` however we need the az api resource to attach it to the dev center:

```
resource "azapi_resource" "example" {
  type      = "Microsoft.DevCenter/devcenters/attachednetworks@2022-11-11-preview"
  name      = "ExampleNetworkConnection"
  parent_id = azurerm_dev_center.this.id
  body = jsonencode({
    properties = {
      networkConnectionId = azurerm_dev_center_network_connection.this.id
    }
  })
}
``` 

To be more precise, this resource is missing @rcskosir

**Comment by webstean** [comment]
You can now attach networks with:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dev_center_attached_network

**Comment by webstean** [comment]
So this can now be closed?

**Comment by damienaicheh** [comment]
Yes @webstean  @rcskosir
