### ISSUE TITLE
Provider azurerm needs Reader privileges on the azure subscription since 3.112.0

### ISSUE THREAD

**Issue by Darkfogel** [hashicorp/terraform-provider-azurerm#26667]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.2

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

provider issue

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.0.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">=2.0"
    }
  }
  backend "azurerm" {
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = "true"
}

provider "azuread" {
}
```

### Debug Output/Panic Output

```shell
The client '******' with object id '******' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/******'
```

### Expected Behaviour

Prior to the 3.112.0 version, a subscription id was provided using ARM_SUBSCRIPTION_ID environment variable. The service principal used had no permission on the subscription.

We are deploying role_assignment on managements groups and in most cases, there's no subscription related.

### Actual Behaviour

With the 3.112.0 version, the service principal now has to have reader access to the subscription provided.

### Steps to Reproduce

N/A

### Important Factoids

N/A

**Comment by circa10a** [comment]
I think this may be the same issue as https://github.com/hashicorp/terraform-provider-azurerm/issues/26628

**Comment by Darkfogel** [comment]
I think you might be right.

**Comment by mybayern1974** [comment]
Thank you Darkfogel for filing this issue. As suggested by circa10a, I'm closing this issue as duplicate, and please subscribe #26628 in which it mentioned the upcoming release in this week is likely to resolve the issue you are running into.
