### ISSUE TITLE
Saved Search Validation Incorrectly Flags Tabular Parameters

### ISSUE THREAD

**Issue by Folling** [hashicorp/terraform-provider-azurerm#26685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

https://github.com/hashicorp/terraform-provider-azurerm/blob/1aef7c1bc3e8afa3a15a1091ae2dd4c823e816ed/internal/services/loganalytics/log_analytics_saved_search_resource.go#L95

This regex is wrong and excludes tabular parameters in the form of `arg:(*)` or `arg:(sub_arg:type,sub_arg:type2)`. 

For more info, see here: https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/functions/user-defined-functions.

I also think the regex currently in use has some issues, such as the first segment being `*` instead of `+` or that `!` is allowed within argument names. There's more, but let's keep it brief.
Here's a regex I think is (more) correct:
```
^[a-zA-Z_][a-zA-Z0-9-_]*:([a-z]+(=[^,\n]+)?|\(\*\)|(\([a-zA-Z_][a-zA-Z0-9-_]*:[a-z]+(,[a-zA-Z_][a-zA-Z0-9-_]*:([a-z]+))*\)))(,\s*[a-zA-Z_][a-zA-Z0-9-_]*:([a-z]+(=[^,\n]+)?|\(\*\)|(\([a-zA-Z_][a-zA-Z0-9-_]*:[a-z]+(,\s*[a-zA-Z_][a-zA-Z0-9-_]*:([a-z]+))*\))))*$
```

I'm aware it's a bit of a mess, but it matches things pretty convincingly (note that tabular arguments do not support default values): https://regex101.com/r/n99EPo/1

### Terraform Version

v1.9.0

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_saved_search

### Terraform Configuration Files

```hcl
resource "azurerm_log_analytics_saved_search" "hello_world" {
  name                       = "hello_world"
  log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.id

  category     = "FooBar"
  display_name = "HelloWorld"
  query        = <<QUERY
    print("Hello World!")
  QUERY

  function_alias = "HelloWorld"
  function_parameters = [
    "foo:(*)"
  ]
}
```

### Debug Output/Panic Output

```shell
│ Error: invalid value for function_parameters.0 (Log Analytics Saved Search Function Parameters must be in the following format: param-name1:type1=default_value1 OR param-name1:type1 OR param-name1:string='string goes here')
│ 
│   with module.saved_searches.azurerm_log_analytics_saved_search.hello_world,
│   on modules/saved_searches/main.tf line 400, in resource "azurerm_log_analytics_saved_search" "hello_world":
│  400:     "foo:(*)"
│
```

### Expected Behaviour

Terraform should respect all valid function parameter definitions.

### Actual Behaviour

It doesn't.

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/11341
https://github.com/hashicorp/terraform-provider-azurerm/issues/10989

**Comment by ziyeqf** [comment]
Hi @Folling, thanks for reporting and providing the regexp.

The code was committed 3 years ago, might be out of date.  I opened a PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/26701) to update the validation.

For any further discussion please leave comments
