### ISSUE TITLE
new requirement for azure function apps

### ISSUE THREAD

**Issue by chlsmith** [hashicorp/terraform-provider-azurerm#2669]
It appears that there's a new required configuration for Function Apps called "FUNCTION_WORKER_RUNTIME" that is keeping things from deploying for me.  When I manually set it up in the portal, I get an option of "dotnet" for this flag.   Maybe an update is needed?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
