### ISSUE TITLE
`azurerm_kubernetes_cluster` - `web_app_routing.dns_zone_ids` has incorrect minimum item requirement

### ISSUE THREAD

**Issue by NickG158** [hashicorp/terraform-provider-azurerm#26717]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "default" {
  name     = "rgakstest"
  location = "westeurope"
}

resource "azurerm_kubernetes_cluster" "default" {
  name = "aks-test-cluster"
  dns_prefix = "testwebappissue"

  identity {
    type = "SystemAssigned"
  }

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_B2as_v2"
  }

  location            = "westeurope"
  resource_group_name = azurerm_resource_group.default.name

  web_app_routing {
    dns_zone_ids = []
  }
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: Not enough list items
│
│   with azurerm_kubernetes_cluster.default,
│   on resource_group.tf line 33, in resource "azurerm_kubernetes_cluster" "default":
│   33:     dns_zone_ids = []
│
│ Attribute web_app_routing.0.dns_zone_ids requires 1 item minimum, but config has only 0 declared.
```

### Expected Behaviour

Plan should have seen there was no changes and completed without error.

### Actual Behaviour

Since updating our terraform to use a list for `dns_zone_ids` in the `web_app_routing` block instead of the singular string `dns_zone_id` we have noticed the above error when passing an empty list ( [] ) to the `dns_zone_ids` property. 

The docs suggest we should be passing an empty list, "If not using Bring-Your-Own DNS zones this property should be set to an empty list." 

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#dns_zone_ids

I'd guess it's this line causing the error, as it sets a `MinItems` of 1:

https://github.com/hashicorp/terraform-provider-azurerm/pull/26117/files#diff-6a7f7d2789c7df9bc827ae00ddcf7d3fbf97b87d414313e0bf99fa55562b0090R440

### Steps to Reproduce

Try to create an AKS cluster using the web app routing addon with dns_zone_ids set to an empty list.

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/26117

**Comment by tgolly** [comment]
I'm stuck on this as well.

The docs say to pass and empty list, but if you do you so, you get an error.

**Comment by eissko** [comment]
yeap. same on my side. it's not implemented according the description which says to use empty list but when empty list is used, the plan fails.
