### ISSUE TITLE
azurerm_storage_account - cannot toggle enable_https_traffic_only to false which is required for azure share using nfs 

### ISSUE THREAD

**Issue by ashishsa1986** [hashicorp/terraform-provider-azurerm#26716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

3.74.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
Resource definition
resource "azurerm_storage_account" "storage_account_blob" {
  count                             = var.storage_account_kind != "FileStorage" ? 1 : 0
  name                              = "${var.environment}${var.applicationname}${var.region_abbreviation}${var.storage_account_name}"
  resource_group_name               = var.storage_account_resource_group_name
  location                          = var.storage_account_location
  account_kind                      = var.storage_account_kind
  account_tier                      = var.storage_account_tier
  account_replication_type          = var.storage_account_replication_type
  enable_https_traffic_only         = var.storage_account_enable_https_traffic_only


Called in root module
module "storage_share_01" {
  source                                    = "git::https://dev.azure.com/xxxx/xxxx/_git/azure_paas_storage_account?ref=xxxxx
  applicationname                           = var.applicationname
  region_abbreviation                       = var.region_abbreviation_01
  environment                               = terraform.workspace
  storage_account_name                      = "fs1"
  storage_account_resource_group_name       = module.resourcegroups_region_of_deployment_01.resourcegroup_names["${local.paas_rg_name}"]
  storage_account_location                  = var.region_of_deployment_01
  storage_account_kind                      = "FileStorage"
  storage_account_tier                      = "Premium"
  storage_account_replication_type          = "LRS"
  storage_account_enable_https_traffic_only = false
```

### Debug Output/Panic Output

```shell
# module.storage_share_01.azurerm_storage_account.storage_account_file[0] will be created
  + resource "azurerm_storage_account" "storage_account_file" {
      + access_tier                        = (known after apply)
      + account_kind                       = "FileStorage"
      + account_replication_type           = "LRS"
      + account_tier                       = "Premium"
      + allow_nested_items_to_be_public    = true
      + cross_tenant_replication_enabled   = true
      + default_to_oauth_authentication    = false
      + enable_https_traffic_only          = true
```

### Expected Behaviour

 # module.storage_share_01.azurerm_storage_account.storage_account_file[0] will be created
  + resource "azurerm_storage_account" "storage_account_file" {
      + access_tier                        = (known after apply)
      + account_kind                       = "FileStorage"
      + account_replication_type           = "LRS"
      + account_tier                       = "Premium"
      + allow_nested_items_to_be_public    = true
      + cross_tenant_replication_enabled   = true
      + default_to_oauth_authentication    = false
      + enable_https_traffic_only          = false

### Actual Behaviour

enable_https_traffic_only cannot be toggled to false

**Comment by magodo** [comment]
@ashishsa1986 Can you share the module definition of the resource `module.storage_share_01.azurerm_storage_account.storage_account_file`, rather than `module.storage_share_01.azurerm_storage_account.storage_account_blob`? I suspect the flag is not properly passed to the module..

**Comment by ashishsa1986** [comment]
@magodo You are right. I had not changed the pointer to variable in the _file module. Thanks for the help.
