### ISSUE TITLE
`azurerm_express_route_connection` updating Express Route Connection fails with `400 Bad Request`

### ISSUE THREAD

**Issue by tiwood** [hashicorp/terraform-provider-azurerm#26746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.6.3

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

azurerm_express_route_connection

### Terraform Configuration Files

```hcl
resource "azurerm_express_route_connection" "main" {
  for_each                         = local.express_route_connections
  name                             = each.value.name
  express_route_gateway_id         = azurerm_express_route_gateway.main[each.value.hub_key].id
  express_route_circuit_peering_id = each.value.peering_id
  routing_weight                   = each.value.weight
  enable_internet_security = false

  routing {
    associated_route_table_id = azurerm_virtual_hub_route_table.main[each.value.hub_key].id
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Express Route Connection (Subscription: "xxx"
│ Resource Group Name: "xxx"
│ Express Route Gateway Name: "xxx"
│ Express Route Connection Name: "xxx"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidRequestFormat: Cannot parse the request.
│ 
│   with azurerm_express_route_connection.main["xxx"],
│   on main.tf line 305, in resource "azurerm_express_route_connection" "main":
│  305: resource "azurerm_express_route_connection" "main" {
```

**Comment by tiwood** [comment]
I've captured the HTTP response, which shows us the actual error:

```
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "InvalidJson",
        "message": "Could not find member 'enablePrivateLinkFastPath' on object of type 'ExpressRouteConnectionProperties'. Path 'properties.enablePrivateLinkFastPath', line 1, position 116."
      }
    ]
  }
}
```

**Comment by xuzhang3** [comment]
Actually I don't think `private_link_fast_path_enabled` belong to this resource. It is a property belongs to  [azurerm_virtual_network_gateway_connection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_gateway_connection#private_link_fast_path_enabled). Service will simply return 400 bad request if `private_link_fast_path_enabled` was added to the request

**Comment by adammontlake** [comment]
Any update on this issue?
Experiencing the same thing

**Comment by erwinkramer** [comment]
> It seems the bug was introduced in version `3.100.0` via [56ac3fc](https://github.com/hashicorp/terraform-provider-azurerm/commit/56ac3fc1786dd8778b7860a3afdc94fc0601c975)

I can confirm this, still works on 1 version lower, so `3.99.0`.

**Comment by adammontlake** [comment]
This issue is still not solved.
While I can see that the latest provider v3.166.0 has now corrected the parameters, the Azure api version that is being used for sending the request is: api-version=2023-11-01
According to the [Azure docs](https://learn.microsoft.com/en-us/rest/api/virtualwan/express-route-connections/create-or-update?view=rest-virtualwan-2024-01-01&tabs=HTTP), it should be using 2024-01-01
The error I am still getting:
`{"error":{"code":"InvalidRequestFormat","message":"Cannot parse the request.","details":[{"code":"InvalidJson","message":"Could not find member 'enablePrivateLinkFastPath' on object of type 'ExpressRouteConnectionProperties'. Path 'properties.enablePrivateLinkFastPath', line 1, position 108."}]}}: timestamp="2024-08-29T11:11:24.779+0300"`
