### ISSUE TITLE
azurerm_container_app_environment -  infrastructure_resource_group_name property does not work as expected

### ISSUE THREAD

**Issue by AddEleven** [hashicorp/terraform-provider-azurerm#26777]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.9.3

### AzureRM Provider Version

v3.113.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app_environment 

### Terraform Configuration Files

```hcl
resource "azurerm_container_app_environment" "example" {
  name                           = "acaenv001"
  location                       = "eastus"
  resource_group_name            = "rg-aca-001"
  internal_load_balancer_enabled = true
  infrastructure_subnet_id       = "/subscriptions/<subscription_id/resourceGroups/<resource_group>/providers/Microsoft.Network/virtualNetworks/<my_vnet_001>/subnets/sn-aca"
  zone_redundancy_enabled        = false
  workload_profile {
    name                  = "Consumption"
    workload_profile_type = "Consumption"
  }
  infrastructure_resource_group_name = "rg-aca-001-infra"
}
```

### Debug Output/Panic Output

```shell
Status: "Failed"
│ Code: "RequestDisallowedByPolicy"
│ Message: "Resource 'ME_cae-np-ctragent-ciseus_rg-np-ctragent-ciseus_eastus' was disallowed by policy. Policy identifiers: '[{\"policyAssignment\":{\"name\":\"[OPERATIONAL][CUSTOM][DENY]Enforce consistent resource naming\",\"id\":\"/providers/Microsoft.Management/managementGroups/<mg>/providers/Microsoft.Authorization/policyAssignments/enforce_resource_naming\"},\"policyDefinition\":{\"name\":\"Enforce naming convention for Resource Groups\"
```

### Expected Behaviour

Terraform deploy should be successful. An ACA environment should be deployed in the resource group outlined, and the ACA env Load Balancer should be deployed into a resource group called "rg-aca-001-infra".

### Actual Behaviour

Fails because the infrastructure_resource_group_name property does not seem to be used and it tries to create a new resource group with the default ME_* name format. We have a policy at our management group level enforcing resource groups start with rg-*, so we cannot use this default name.

I have replicated this code in bicep with the following and this functionality works fine:

```
resource acaenv 'Microsoft.App/managedEnvironments@2023-11-02-preview' = {
  name: 'acaenv001'
  location: 'eastus'
  properties: {
    vnetConfiguration:{
      internal: true
      infrastructureSubnetId: '/subscriptions/<subscription_id/resourceGroups/<resource_group>/providers/Microsoft.Network/virtualNetworks/<my_vnet_001>/subnets/sn-aca'
    }
    zoneRedundant: false
    infrastructureResourceGroup: 'rg-aca-001-infra'
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
  }
}
```

### Steps to Reproduce

Run `terraform apply` on the above terraform module.

### Important Factoids

-

### References

-

**Comment by apsi15** [comment]
Same issue here. Can anyone give more insight and a solution for that?

**Comment by AddEleven** [comment]
@apsi15 - reverting to an older Terraform version (3.109.0) has resolved it for me. Seems to be an issue after this version.

**Comment by beparmentier** [comment]
same issue
@AddEleven thanks for the workaround

**Comment by NiklasA** [comment]
@jiaweitao001 can anyone of your team, please check this? Thank you 👍

**Comment by jiaweitao001** [comment]
Hi @AddEleven , thanks for opening the issue. I've reproduced the problem you are facing. I'll keep investigating and keep you posted here.

**Comment by jiaweitao001** [comment]
The issue is caused by this change: https://github.com/hashicorp/terraform-provider-azurerm/pull/26365 . The `DiffSuppressFunc` of `infrastructure_resource_group_name` is not working as expected, the input value will be omitted anyway. Is it possible that we revert this change? @jackofallops
