### ISSUE TITLE
azurerm_private_dns_zone_group under azurerm version 3.113.0 not found

### ISSUE THREAD

**Issue by NavichandanT** [hashicorp/terraform-provider-azurerm#26879]
### Community Note

I am using below version of terraform, and trying to use resource "azurerm_private_dns_zone_group".  But it fails that the module doesn't exists, is this deprecated? 

 azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.113.0"

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Which version did you use for azurerm_private_dns_zone_group?

**Comment by NavichandanT** [comment]
oh.. 

While converting my sql bicep file, I am taking copilot help and that suggested this resource. As getting an issue for it thought its not there in current version.  That's the reason have raised it. If doesn't exist at all, I can close this and will find another way.

resource "**azurerm_private_dns_zone_group**" "private_dns_zone_group" {
  for_each = { for ep in var.private_endpoints : ep.endpoint_name => ep }

  name                = "default"
  resource_group_name = local.resource_group_name
  private_endpoint_id = azurerm_private_endpoint.private_endpoint[each.key].id

  private_dns_zone_configs {
    name                  = "*#*#*#*#*"
    private_dns_zone_id   = each.value.private_dns_zone
  }
}

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. `azurerm_private_dns_zone_group` is not a resource that exists, as such I am going to mark this issue closed.
