### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by premishu** [hashicorp/terraform-provider-azurerm#26882]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.3

### AzureRM Provider Version

2.56.0

### Affected Resource(s)/Data Source(s)

registry.terraform.io/hashicorp/azurerm" produced an invalid new value for │ .protected_settings: inconsistent values for sensitive attribute

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "wvd" {
  count = var.number_of_hosts

  depends_on = [
    azurerm_virtual_machine_extension.LogAnalytics,
  ]

  name                 = "WVDSetup"
  virtual_machine_id   = azurerm_virtual_machine.wvdshvm.*.id[count.index]
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.10"

  protected_settings = <<PROTECTED_SETTINGS
    {
      "commandToExecute": "powershell -ExecutionPolicy Unrestricted -File Setup-FSLogix.ps1 -RegistrationToken ${var.wvd_registration_token}",
      "storageAccountName": "${data.azurerm_storage_account.wvd_setup.name}",
      "storageAccountKey": "${data.azurerm_storage_account.wvd_setup.primary_access_key}"
    }
  PROTECTED_SETTINGS

  settings = <<SETTINGS
    {
      "fileUris": [
        "${var.fslogixsetup_url}",
        "${var.fslogixsetupscript_url}",
        "${var.wvdagent_url}",
        "${var.wvdbootloader_url}"
      ]
    }
  SETTINGS

  lifecycle {
    ignore_changes = [
      settings,
      protected_settings,
    ]
  }

  tags = var.tags
}
```

### Debug Output/Panic Output

```shell
##[error]Terraform command 'apply' failed with exit code '1'.
##[error]╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.ptc.module.hosts[3].azurerm_virtual_machine_extension.wvd[0] to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
│ .protected_settings: inconsistent values for sensitive attribute.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know which latest version you are seeing the behavior on and we can reopen it, thanks!
