### ISSUE TITLE
Suggestion - Developer docs/changelog

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azurerm#2688]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As the number of contributors to the provider grows I think it would be useful to have some provider specific documentation for development.
This could cover things like Azure specific validators and helpers, registering clients and common patterns for working with the Azure API (such as locking subnets and vnets before updating).

It could also be handy to have a developer specific changelog covering internal changes (like the upcoming requiring imports thing) detailing what's changing and why.

I'd be happy to help out with writing down some of the things I've picked up so far.

Thoughts?

**Comment by metacpp** [comment]
@hbuckle Thanks for raising it here, and I'd like to add my 2 cents here:

>This could cover things like Azure specific validators and helpers, registering clients and common patterns for working with the Azure API (such as locking subnets and vnets before updating).

Maybe GitHub Wiki is a good place for it. A good examle: https://github.com/golang/go/wiki

>It could also be handy to have a developer specific changelog covering internal changes (like the upcoming requiring imports thing) detailing what's changing and why.

I would recommend that we provide clear information in `git commit message`, and use tool to generate dev-specific changelog.

Some useful links that you may be interested:
[How to write Git Commit Message](https://chris.beams.io/posts/git-commit/)
[Git Commit Message Tool]https://github.com/commitizen/cz-cli

**Comment by metacpp** [comment]
@tombuildsstuff 

Thanks for your thoughts.

>In my experience Wiki's almost always fall out of sync with reality - IMO this would be better as a file in the repo, this also has the additional benefit that it's on everybody's local machine when they clone the repo (among being able to PR changes etc), but should still be as visible

Any type of content can be out of sync if none maintains it.

[Golang Wiki](https://github.com/golang/go/wiki) is maintained by Go community, everyone can add/edit page with history tracking. Other than formal code review process, it's more lightweight way and adopted by many open source projects.

For online or offline, I don't have any specific preference.

>The "developer specific changelog" mentioned above is more for what's changing in development land (e.g. switching to Go modules)?

`Switching to Go modules` is a very good example here. This engineering work was done through several commits. If we put enough information in each commit message, we can just use some aggregation tool to generate the changelog with very minor tweaks, this is targeting to developer.

It's popular way in open source project, but it requires high quality commit message in day-to-day work.  This is something I am worried about.

Anyway, this is just my 2 cents for the brainstorming.

**Comment by tombuildsstuff** [comment]
Fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/16732 / these are now available in the `contributing` folder: https://github.com/hashicorp/terraform-provider-azurerm/tree/main/contributing
