### ISSUE TITLE
azurerm_container_app misleading error message when referencing a template container env with secret_name

### ISSUE THREAD

**Issue by bandwiches** [hashicorp/terraform-provider-azurerm#26893]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

azurerm_container_app

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_container_app_environment" "example" {
  name                       = "Example-Environment"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
}

resource "azurerm_container_app" "my_container_app" {
  name                         = "example-app"
  container_app_environment_id = azurerm_container_app_environment.example.id
  resource_group_name          = azurerm_resource_group.example.name
  revision_mode                = "Single"
  template {
    container {
      cpu    = 2.0
      memory = "4Gi"
      name   = "my_container"
      image  = "mcr.microsoft.com/azuredocs/containerapps-helloworld:latest"
      env {
        name = "MY_CLIENT_ID"
        secret_name = "my.client.id"
      }
    }
  }
  secret {
    name = "my.client.id"
    value = "some_value"
  }
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Expected to be able to use `.` in a secret name (my.secret.name)

### Actual Behaviour

```terraform
Error: "secret.0.name" must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

N/A

### References

This may be an issue with Azure Resource Manager rather than Terraform, this just happened to be the best spot I could find to address it.

**Comment by jiaweitao001** [comment]
Hi @bandwiches , thanks for asking. You are right about this, it is an ARM issue by design.

**Comment by bandwiches** [comment]
@jiaweitao001 I left feedback on their documentation page. Thanks!
