### ISSUE TITLE
`azurerm_monitor_data_collection_rule` - sampling_frequency_in_seconds incorrect range constraint

### ISSUE THREAD

**Issue by KiPIDesTAN** [hashicorp/terraform-provider-azurerm#26897]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

azurerm_monitor_data_collection_rule

### Terraform Configuration Files

```hcl
resource "random_string" "name" {
  length  = 8
  special = false
  upper   = false
}

locals {
  log_analytics_id = "resource.id.of.log.analytics.workspace"
  log_analytics_name = split(local.log_analytics_id, "/")[8]
}

resource "azurerm_monitor_data_collection_rule" "main" {
  name                = "dcr-testdcr"
  resource_group_name = var.resource_group_name
  location            = var.location

  data_sources {

    performance_counter {
      name                          = "PerfCounters"
      streams                       = [ "Microsoft-Perf" ]
      sampling_frequency_in_seconds = 1800
      counter_specifiers            = ["Processor(*)\\%% Processor Time"]
    }

  }

  destinations {
    log_analytics {
      name                  = local.log_analytics_name
      workspace_resource_id = local.log_analytics_id
    }
  }

  data_flow {
    streams      = [ "Microsoft-Perf" ]
    destinations = [ local.log_analytics_name ]
  }
}
```

### Debug Output/Panic Output

```shell
Terraform outputs an error that a sampling_frequency_in_seconds above 300 fails range validation.
 
sampling_frequency_in_seconds is an invalid range. sampling_frequency_in_seconds is documented in the  Terraform azurerm provider as 1 through 300, inclusive. However, the range is 1 through 1800. 

The 1 through 1800 range is viewable in the Portal.
```

### Expected Behaviour

sampling_frequencey_in_seconds should vary from 1 through 1800 (seconds) for Performance counters in a data collection rule (except VMInsights in Performance counters, which is always 60). 

This range is defined in the Portal and within the control plane. See image below.

![image 87](https://github.com/user-attachments/assets/2a641ca6-612d-4038-889e-52e85eb5af6b)

### Actual Behaviour

Terraform azurerm_monitor_data_collection_rule errors, stating that a value above 300 is out of range. The range code validation check from [monitor_data_collection_rule_resource.go](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/monitor/monitor_data_collection_rule_resource.go) is below.

```go
"sampling_frequency_in_seconds": {
	Type:         pluginsdk.TypeInt,
	Required:     true,
	ValidateFunc: validation.IntBetween(1, 300),
},
```

**Comment by pamelasalvatori** [comment]
any updates?
