### ISSUE TITLE
Error while updating the Azure recovery service vault weekly retention policy

### ISSUE THREAD

**Issue by suvarnanith** [hashicorp/terraform-provider-azurerm#26917]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.2

### AzureRM Provider Version

v3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_backup_policy_vm

### Terraform Configuration Files

```hcl
What happened?
I am trying to update a recovery service policy retention days via this new terraform resource. Creating the policy works just fine for all configurations, however updating from daily -> weekly, or changing the retention days for monthly or yearly gives a vague error:
"protectionpolicies.ProtectionPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorInvalidPolicyInput" Message="Input for create or update policy is not in proper format. Please check format of parameters like schedule time, schedule days, retention time and retention days."

I am trying to update the weekly policy for 10 RSV which are in different subscriptions. I am passing provider details to my modules to achieve this.

resource "azurerm_backup_policy_vm" "main" {
  provider = azurerm
  for_each = var.backup_policies_vm

  name                = each.key
  resource_group_name = var.resource_group_name
  recovery_vault_name = azurerm_recovery_services_vault.main.name

  timezone = each.value.timezone

  backup {
    frequency = each.value.backup_frequency
    time      = each.value.backup_time
  }

  retention_daily {
    count = each.value.retention_daily
  }

  retention_weekly {
    count    = 26
    weekdays = ["Sunday"]
  }
}
```

### Debug Output/Panic Output

```shell
protectionpolicies.ProtectionPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BMSUserErrorInvalidPolicyInput" Message="Input for create or update policy is not in proper format. Please check format of parameters like schedule time, schedule days, retention time and retention days "
e schedule time, schedule days, retention time and retention days "
```

### Expected Behaviour

Update the policy

### Actual Behaviour

Policy is not getting updated

**Comment by suvarnanith** [comment]
One more thing i want to add is that this error occurs only when i run terraform apply.

**Comment by sinbai** [comment]
Hi @suvarnanith thanks for opening this issue. Unfortunately, I could not reproduce the mentioned issue with the following tf config by changing `count` of `retention_weekly` from `26` to `28`. Could you try to reproduce with it? Could you please provide the minimal reproducible tf config (with dependencies and variable values) of this issue so that we could reproduce /troubleshoot?

```

terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "3.114.0"
    }
  }
}

provider "azurerm" {
  features {
  key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}



resource "azurerm_resource_group" "test" {
  name     = "testRG-backup-26917"
  location = "eastus"
  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}

resource "azurerm_recovery_services_vault" "test" {
  name                = "test-26917"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "Standard"

  soft_delete_enabled = false
}

resource "azurerm_backup_policy_vm" "test" {
  name                           = "test-BPVM-26917"
  resource_group_name            = azurerm_resource_group.test.name
  recovery_vault_name            = azurerm_recovery_services_vault.test.name

  timezone = "UTC"
  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }

   retention_weekly {
    count    = 28  #from 26 to 28
    weekdays = ["Sunday"]
  }
}
```

**Comment by suvarnanith** [comment]
Actually in my case before retention for week was not part of the code. When i updated i started getting this.
## Locals which pass the value to policy creation
locals {
  policies_vm = {
    default = {
      default_policy = true
      timezone = "UTC"
      backup_frequency = "Daily"
      backup_time = "23:00"
      retention_daily = 45
      retention_weekly = {
        count = 26
        weekdays = ["Sunday"]
      }
    }
  }
}

## main.tf
locals {
  sub = {
    app_id            = "##"
    tech_owner_dl     = "##"
    subscription_id   = "##"
    subscription_name = "##"
  }

  subsrsv = [
  {
      backup_policies_vm = local.policies_vm
      name = "test-vault-01"
      location = "chinanorth3"
      
    }
  ]
}
provider "azurerm" {
  alias = "abc"

  tenant_id                  = "##"
  subscription_id            = local.cbt_nonproduction.subscription_id
  skip_provider_registration = true
  environment                = "china"


  features {}
}

## Calling the module

module "backup" {
  source = "../module/backup"
  providers = {
    azurerm = azurerm.abc
  }
  for_each = {for k in local.subsrsv : "${k.name}@${k.location}" => k}
  vault_name          = each.value.name
  location            = each.value.location
  resource_group_name = "test-rg"
  backup_policies_vm  = {for k,v in each.value.backup_policies_vm: format("%s-%s", "testpolicy", k) => v}
  policy_name_prefix   = "test-policy"
  subscription_id      = local.sub.subscription_id
  subscription_name    = local.sub.subscription_name
}

## Version
terraform {
  required_version = ">= 1.1.9"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.67.0"
    }
  }
}

## Child Module

resource "azurerm_recovery_services_vault" "main" {
  provider = azurerm

  name                = var.vault_name
  location            = var.location
  resource_group_name = var.resource_group_name
  sku                 = var.vault_sku
  storage_mode_type   = var.vault_storage_mode_type

  public_network_access_enabled = false

  soft_delete_enabled = var.vault_soft_delete_enabled

  tags = var.tags

  lifecycle {
    ignore_changes = [tags]
  }
}

resource "azurerm_backup_policy_vm" "main" {
  provider = azurerm
  for_each = var.backup_policies_vm

  name                = each.key
  resource_group_name = var.resource_group_name
  recovery_vault_name = azurerm_recovery_services_vault.main.name

  timezone = each.value.timezone

  backup {
    frequency = each.value.backup_frequency
    time      = each.value.backup_time
  }

  retention_daily {
    count = each.value.retention_daily
  }

  dynamic "retention_weekly" {
    for_each = each.value.retention_weekly != null ? [each.value.retention_weekly] : []
    content {
      count    = lookup(retention_weekly.value, "count")
      weekdays = lookup(retention_weekly.value, "weekdays")
    }
  }

  dynamic "retention_monthly" {
    for_each = each.value.retention_monthly != null ? [each.value.retention_monthly] : []
    content {
      count    = lookup(retention_monthly.value, "count")
      weekdays = lookup(retention_monthly.value, "weekdays")
      weeks    = lookup(retention_monthly.value, "weeks")
    }
  }

  dynamic "retention_yearly" {
    for_each = each.value.retention_yearly != null ? [each.value.retention_yearly] : []
    content {
      count    = lookup(retention_yearly.value, "count")
      weekdays = lookup(retention_yearly.value, "weekdays")
      weeks    = lookup(retention_yearly.value, "weeks")
      months   = lookup(retention_yearly.value, "months")
    }
  }
}

## Variable

variable "vault_name" {
  type = string
}

variable "location" {
  type = string
}

variable "resource_group_name" {
  type = string
}

variable "vault_sku" {
  type    = string
  default = "Standard"
}

variable "vault_storage_mode_type" {
  type    = string
  default = "GeoRedundant"
}

variable "vault_soft_delete_enabled" {
  type    = bool
  default = true
}

variable "backup_policies_vm" {
  type = map(object({
    default_policy    = optional(bool, false)
    timezone          = string
    backup_frequency  = string
    backup_time       = string
    retention_daily   = number
    retention_weekly  = optional(object({
      count    = number
      weekdays = list(string)
    }), null)
    retention_monthly = optional(object({
      count    = number
      weekdays = list(string)
      weeks    = list(string)
    }), null)
    retention_yearly  = optional(object({
      count    = number
      weekdays = list(string)
      weeks    = list(string)
      months   = list(string)
    }), null)
  }))
}

variable "backup_vm_exclusion_tag" {
  type = string
  default = "SkipVMBackup"
}

variable "backup_vm_exclusion_value" {
  type = string
  default = "true"
}

variable "policy_name_prefix" {
  type = string
}

variable "subscription_id" {
  type = string
}

variable "subscription_name" {
  type = string
}
variable "tags" {
  type    = map(string)
  default = {}
}

**Comment by sinbai** [comment]
Thanks for providing the tf config. Could you please provide the detailed reproduction steps to help reproduce the issue?

**Comment by suvarnanith** [comment]
@sinbai Sure
## Create RSV ( without weekly retention block)
locals {
policies_vm = {
default = {
default_policy = true
timezone = "UTC"
backup_frequency = "Daily"
backup_time = "23:00"
retention_daily = 45
}
}
}
Steps: Terraform init, validate, plan and apply

RSV gets created.

## Update the RSV policy with weekly retention
locals {
policies_vm = {
default = {
default_policy = true
timezone = "UTC"
backup_frequency = "Daily"
backup_time = "23:00"
retention_daily = 45
retention_weekly = {
count = 26
weekdays = ["Sunday"]
}
}
}
}
Steps: Terraform init, Validate and plan works well
Terraform Apply gives me the error

**Comment by sinbai** [comment]
@suvarnanith thanks for the update. Unfortunately, it works fine on my side with the provided config and reproduce steps, details are as follows. Could you please double chick？ 
![image](https://github.com/user-attachments/assets/ce1f0d56-c33c-4e09-ba98-9f7949edb344)

**Comment by suvarnanith** [comment]
@sinbai  Now could u remove the Weekly policy and adding back again?
## Step 1
Remove weekly rotation
locals {
policies_vm = {
default = {
default_policy = true
timezone = "UTC"
backup_frequency = "Daily"
backup_time = "23:00"
retention_daily = 45
}
}
}

## Step 2
Add back the weekly rotation
locals {
policies_vm = {
default = {
default_policy = true
timezone = "UTC"
backup_frequency = "Daily"
backup_time = "23:00"
retention_daily = 45
retention_weekly = {
count = 26
weekdays = ["Sunday"]
}
}
}
}

**Comment by suvarnanith** [comment]
@sinbai It worked for me for new RSV and creating the weekly retention for first time. It did not work when i tried removing and adding back.

**Comment by suvarnanith** [comment]
Hi @sinbai Did you try the step that i mentioned.?

**Comment by sinbai** [comment]
Hi @suvarnanith it still works fine on my side with the following steps.
1. Create RSV ( without weekly retention block)
```
locals {
  policies_vm = {
    default = {
      default_policy   = true
      timezone         = "UTC"
      backup_frequency = "Daily"
      backup_time      = "23:00"
      retention_daily  = 45
    }
  }
}
```
Result:
![image](https://github.com/user-attachments/assets/ec399cf8-5f7a-40ca-ab76-d6a152eb7dca)


2. Update the RSV policy with weekly retention
```
locals {
  policies_vm = {
    default = {
      default_policy   = true
      timezone         = "UTC"
      backup_frequency = "Daily"
      backup_time      = "23:00"
      retention_daily  = 45
      retention_weekly = {
        count    = 26
        weekdays = ["Sunday"]
      }
    }
  }
}
```
Result:
![image](https://github.com/user-attachments/assets/d7c46d05-9618-4342-9b24-7712b781e7a0)

3. Remove weekly rotation
```
locals {
  policies_vm = {
    default = {
      default_policy   = true
      timezone         = "UTC"
      backup_frequency = "Daily"
      backup_time      = "23:00"
      retention_daily  = 45
    }
  }
}
```

Result:
![image](https://github.com/user-attachments/assets/79f0dc03-3fdd-4294-97ac-4bdd3ed916bf)

4. Add back the weekly rotation
```
locals {
  policies_vm = {
    default = {
      default_policy   = true
      timezone         = "UTC"
      backup_frequency = "Daily"
      backup_time      = "23:00"
      retention_daily  = 45
      retention_weekly = {
        count    = 26
        weekdays = ["Sunday"]
      }
    }
  }
}
```
Result:
![image](https://github.com/user-attachments/assets/46879b4d-23c3-4c22-b2f7-40e7638d9fef)

**Comment by suvarnanith** [comment]
@sinbai I deleted the RSV policy and recreated and then i added the weekly retention. Not sure what was wrong. Anyways thank you for the help

**Comment by suvarnanith** [comment]
Closing the issues
