### ISSUE TITLE
Fix default bug in preferred_data_persistence_auth_method and for azurerm_redis_cache resource  

### ISSUE THREAD

**Issue by RokDavid** [hashicorp/terraform-provider-azurerm#26948]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

From PR: 

Bug Description
The data_persistence_authentication_method field in the redis_configuration block of the azurerm_redis_cache resource is marked as optional. However, it is currently assigned a default value of "SAS". This results in Terraform always setting this field to "SAS" when it is not explicitly defined in the Terraform configuration. This behavior causes unnecessary updates to the Azure Redis Cache resource when the user has not specified a value for this field.
Worth to note that even not all of the SKUs support this option. Here's live example:

![Screenshot 2024-08-06 224212](https://github.com/user-attachments/assets/16737059-8a1f-4e9a-9ebf-38949c7cc9e1)

Expected Behavior
The data_persistence_authentication_method field should remain unset unless explicitly defined by the user in their Terraform configuration. If the user does not set this field, Terraform should not include it in the resource configuration, thereby preventing any unexpected updates.

Actual Behavior
When the data_persistence_authentication_method field is not defined in the Terraform configuration, Terraform defaults this field to "SAS" and attempts to update the resource configuration during terraform apply. This causes unintended changes to the Azure Redis Cache resource.

Steps to Reproduce
Define an Azure Redis Cache resource without specifying the data_persistence_authentication_method field in the Terraform configuration.
Run terraform plan and observe that Terraform plans to set the data_persistence_authentication_method field to "SAS".
Run terraform apply and apply the changes.
Run terraform plan again and observe that Terraform still includes data_persistence_authentication_method = "SAS" even though it was not explicitly defined.

![Screenshot 2024-08-06 224354](https://github.com/user-attachments/assets/a44cbeb8-c1d2-48cd-afe5-2114aabed807)

### New or Affected Resource(s)/Data Source(s)

azurerm_redis_cache 

### Potential Terraform Configuration

```hcl
From:

"data_persistence_authentication_method": {
    Type:     pluginsdk.TypeString,
    Optional: true,
    Default:  "SAS",
    ValidateFunc: validation.StringInSlice([]string{
        "SAS",
        "ManagedIdentity",
    }, false),
}


To:

"data_persistence_authentication_method": {
    Type:     pluginsdk.TypeString,
    Optional: true,
    ValidateFunc: validation.StringInSlice([]string{
        "SAS",
        "ManagedIdentity",
    }, false),
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/pull/24370

**Comment by RokDavid** [comment]
The same story is about _enable_authentication_ and _maxmemory_policy_ .
It makes the whole _redis_configuration{ }_ block append even though not specified.

**Comment by rcskosir** [comment]
@RokDavid Thank you for taking the time to open this issue! Can you provide the azurerm version in which you are experiencing this behavior?

**Comment by RokDavid** [comment]
@rcskosir we use the newest one (3.114 if I'm not wrong), however when I was researching this code was present on most versions available. I will confirm this asap

**Comment by RokDavid** [comment]
@rcskosir data_persistence_authentication_method change was introduced in v3.93, however maxmemory_policy  already existed.
