### ISSUE TITLE
azurerm_storage_account resource doesn't persist network_rules block configuration

### ISSUE THREAD

**Issue by jaromirmikulik** [hashicorp/terraform-provider-azurerm#26944]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.114.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

When I upgrade AzureRM to version **3.114.0**, the terraform plan starts to indicate changes in network_rules block (there was no changes performed in Azure and also in terraform code).

I tried previous versions of AzureRM and it seems that the last version, which not produce this type of error, is **3.112.0**.

```hcl

resource "azurerm_storage_account" "account" {
  name                = "storagetst"
  resource_group_name = "STORAGE-RG"

  location                 = "westeurope"
  account_tier             = "Standard"
  account_replication_type = "LRS"

  network_rules {
    default_action             = "Allow"
    bypass = [
      "AzureServices",
    ]
  }

  tags = {
    build = "20220606"
  }
}

```

### Debug Output/Panic Output

```shell
Terraform plan shows:



Terraform will perform the following actions:

  # module.storage_account_tst.azurerm_storage_account.account will be updated in-place
  ~ resource "azurerm_storage_account" "account" {
        id                                 = "/subscriptions/xxxx/resourceGroups/STORAGE-RG/providers/Microsoft.Storage/storageAccounts/storagetst"
        name                               = "storagetst"
        tags                               = {
            "build"      = "20220606"
        }
        # (97 unchanged attributes hidden)

      + network_rules {
          + bypass         = [
              + "AzureServices",
            ]
          + default_action = "Allow"
        }

        # (1 unchanged block hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.


```

### Expected Behaviour

No changes is indicated, because there doesn't have been changed (in Azure and also in TF code).

### Actual Behaviour

Terraform plan shows same changes each time you run `terraform plan`.

(I also tried to perform terraform apply to check, if this fix current case, but when I run terraform plan again, same changes are indicated. )

### Steps to Reproduce

`terraform init`
`terraform validate` (no problem is shown)
`terraform plan` (changes in network_rules are shown to be updated)
`terraform apply` (finished without problem)

When you again run `terraform plan`, same changes in network_rules block are shown.

### References

It could be caused by refactoring in: https://github.com/hashicorp/terraform-provider-azurerm/pull/26218 delivered in version 3.113.0 which is the first version, where this type of error is shown.

**Comment by magodo** [comment]
Hi @jaromirmikulik, this issue duplicates to https://github.com/hashicorp/terraform-provider-azurerm/issues/26854, please find the reason and solution from that. I'll close this issue for now, please feel free to reopen it if you have any other question.
