### ISSUE TITLE
Not able to pass list of string to the partition key path parameter in CosmosDB SQL Database containers deployment using Terraform

### ISSUE THREAD

**Issue by Rahul-Palande11** [hashicorp/terraform-provider-azurerm#26961]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.111.0

### Affected Resource(s)/Data Source(s)

CosmoDB sql database container

### Terraform Configuration Files

```hcl
Zip Folder Link - https://drive.google.com/drive/folders/1qCkVeH8wAc7E9pvt2WAQ7xJO5Mcuja_D?usp=sharing

This folder includes main.tf, variables.tf and main.tfvars
```

### Debug Output/Panic Output

```shell
Debug output file link - https://drive.google.com/file/d/1U9X-1r9THUfIDF-1esXgwf32JGPU_VPP/view?usp=sharing
```

### Expected Behaviour

When we run terraform plan and terraform apply command, so it should deploy CosmoDB sql database container with multiple partition key path (we have provided 2 partition key paths). There should be 2 partition key paths in the CosmoDB sql database container which we should be able to see on azure portal.

### Actual Behaviour

When we run terraform plan command, then we are facing error that partition_key_path expects a string value. But in the newer version of Azurem, it is accepting a list of strings but when I provide a list of string datatype for partition_key_path in terraform code, I get error. But when I try to create it using Azure portal, it gets created successfully.
The error which I get in Azure Devops pipeline is as below:-

│ Error: Incorrect attribute value type
│ 
│   on ../../../../../../../iac-modules/Infra-As-Code/Modules/terraform/documentDB/databaseAccounts/sqlDatabases/containers/v1.0/main.tf line 18, in resource "azurerm_cosmosdb_sql_container" "example":
│   18:   partition_key_path    =  ["/definition", "/id"] //var.partition_key_path //"/definition/id"
│ 
│ Inappropriate value for attribute "partition_key_path": string required.
╵
##[error]Terraform command 'plan' failed with exit code '1'.
__

### Steps to Reproduce

1. Have shared the main.tf, variables.tf and variables.tfvars file. You can check the code and trying recreating the issue.
2. You need to pass list of string in the parameter partition_key_path (i.e partition_key_path    =  ["/definition", "/id"]) and try deploying the resource "azurerm_cosmosdb_sql_container".
3. Run terraform plan and terraform apply for above code.

### Important Factoids

-

### References

Terraform Registry Link - https://registry.terraform.io/providers/hashicorp/azurerm/3.111.0/docs/resources/cosmosdb_sql_container

Want to achieve this using terraform - https://learn.microsoft.com/en-us/azure/cosmos-db/hierarchical-partition-keys?tabs=net-v3%2Carm-json#choosing-your-hierarchical-partition-keys

**Comment by stephybun** [comment]
Thanks for raising this issue @Rahul-Palande11. 

The property `partition_key_path` is deprecated and expects a string as an argument. In order to supply multiple paths you would need to use the property `partition_key_paths`.

I'm going to close this issue since this appears to be a configuration issue, using `partition_key_paths` should resolve the error message.

**Comment by Rahul-Palande11** [comment]
Thanks for responding but may I know this is for which azurerm version, because in the documentation for latest version I could see partition_key_path only?
