### ISSUE TITLE
Support for CIDR notation in postgresql_flexible_server_firewall_rule Resource

### ISSUE THREAD

**Issue by sonalpatel38-nhs** [hashicorp/terraform-provider-azurerm#26969]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Terraform does not currently support CIDR notation for the start_ip_address and end_ip_address attributes in the postgresql_flexible_server_firewall_rule resource.

Allowing the use of CIDR notation would help simplify firewall rule management, particularly for extensive IP ranges as this would allow definitions of broader range of IP addresses using more concise syntax. Additionally, to represent single IP addresses, a /32 mask could be used, making the end_ip_address attribute optional.

### New or Affected Resource(s)/Data Source(s)

postgresql_flexible_server_firewall_rule

### Potential Terraform Configuration

```hcl
resource "azurerm_postgresql_flexible_server_firewall_rule" "example" {
  name             = "example-fw"
  server_id        = azurerm_postgresql_flexible_server.example.id
  start_ip_address = "122.122.0.0/32"
}
```

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems Azure Rest API Spec hasn't supported this new feature for now since I don't find it from [Swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/postgresql/resource-manager/Microsoft.DBforPostgreSQL/stable/2022-12-01/FirewallRules.json). Once it's supported, we will take another look. Thanks. If it's possible, could you share the related MS official doc for this new feature? Thanks.

**Comment by harshavmb** [comment]
I too can't find the support for CIDR in REST-API specs [here](https://learn.microsoft.com/en-us/rest/api/postgresql/flexibleserver/firewall-rules/create-or-update?view=rest-postgresql-flexibleserver-2022-12-01&tabs=HTTP). 

I don't think this can be supported here as it's not supported in upstream APIs. Worth opening an issue with MS directly.

**Comment by harshavmb** [comment]
ignore the PR update here please, it's concerning [#26979](https://github.com/hashicorp/terraform-provider-azurerm/issues/26979)

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If you create a request on [Azure/azure-rest-api-specs](https://github.com/Azure/azure-rest-api-specs), feel free to add the link here. When it gets added, we can reopen this request or you can create a new one.
