### ISSUE TITLE
Error on data azurerm_storage_account following 3.115.0

### ISSUE THREAD

**Issue by Darkfogel** [hashicorp/terraform-provider-azurerm#26984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.115.0

### Affected Resource(s)/Data Source(s)

data.azurerm_storage_account

### Terraform Configuration Files

```hcl
data "azurerm_storage_account" "example" {
  name                = "example"
  resource_group_name = "resource-group"
}
```

### Debug Output/Panic Output

```shell
https://gist.github.com/Darkfogel/7c0c4b7bd6c6e9563c865d340a772d6c
```

### Expected Behaviour

No error on the data source, Working correctly on 3.114.0.

### Actual Behaviour

╷
│ Error: setting `azure_files_authentication`: Invalid address to set: []string{"azure_files_authentication", "0", "default_share_level_permission"}
│ 
│   with data.azurerm_storage_account.exstreamGenerateDocument_storage_account,
│   on main.tf line 661, in data "azurerm_storage_account" "exstreamGenerateDocument_storage_account":
│  661: data "azurerm_storage_account" "exstreamGenerateDocument_storage_account" {
│ 
╵

### Steps to Reproduce

terraform plan

**Comment by cerocool1203** [comment]
Error: setting `azure_files_authentication`: Invalid address to set: []string{"azure_files_authentication", "0", "default_share_level_permission"}
│ 
│   with data.azurerm_storage_account.airflow-share,
│   on adhoc.tf line 1, in data "azurerm_storage_account" "flow-share":
│    1: data "azurerm_storage_account" "flow-share" {
│ 
╵
Operation failed: failed running terraform plan (exit 1)

**Comment by jwalton3141** [comment]
Just to confirm, until v3.116.0 is released, you can avoid this bug by pinning the azurerm provider to v3.114.0, as eg.
```
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      # https://github.com/hashicorp/terraform-provider-azurerm/issues/26984
      version = "3.114.0"
    }
  }
}
```
