### ISSUE TITLE
azurerm_eventhub should accept namespace id as an input

### ISSUE THREAD

**Issue by calebak404** [hashicorp/terraform-provider-azurerm#27008]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

In order to be more consistent with other resources and allow for more flexibility, azurerm_eventhub should accept namespace id as an input instead of namespace name.

### New or Affected Resource(s)/Data Source(s)

azurerm_eventhub

### Potential Terraform Configuration

```hcl
resource "azurerm_eventhub" "example" {
  name                = "acceptanceTestEventHub"
  namespace_id        = azurerm_eventhub_namespace.example.id
  resource_group_name = azurerm_resource_group.example.name
  partition_count     = 2
  message_retention   = 1
}
```

**Comment by sinbai** [comment]
Hi @calebak404 thanks for opening this issue. Actually, Terraform resource `azurerm_eventhub` supports [namespace_name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub#namespace_name) as an input. Could you please use `namespace_name` instead of `namespace_id` as detailed below?

```
resource "azurerm_eventhub" "example" {
  name                = "acceptanceTestEventHub"
  namespace_name        = azurerm_eventhub_namespace.example.name
  resource_group_name = azurerm_resource_group.example.name
  partition_count     = 2
  message_retention   = 1
}
```

**Comment by calebak404** [comment]
I've conveyed this to our account team as well, but the goal with this request is to have namespace_id as an option in addition to namespace_name.

1. Providing the resource id of the namespace is more explicit and exact
2. This brings the event_hub resource in line with other resources that take ID as an argument.
3. This allows for more flexibility in module design enabling us to reference a namespace that is in a different subscription that the one the provider is configured for.
