### ISSUE TITLE
azurerm.storage_account network_rules block changed behavior after 3.112

### ISSUE THREAD

**Issue by tzoetemelk-dsc** [hashicorp/terraform-provider-azurerm#27000]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.115

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "GRS"

  network_rules {
    default_action = "Allow"
  }
}
```

### Debug Output/Panic Output

```shell
Terraform will show "changes" after 3.112, while at 3.112 no changes will be reported:
      + network_rules {
          + bypass                     = (known after apply)
          + default_action             = "Allow"
          + ip_rules                   = (known after apply)
          + virtual_network_subnet_ids = (known after apply)
```

### Expected Behaviour

No changes in state are expexted, nothing has changed for these resources.

### Actual Behaviour

If you add the following items with empty/default values:
`bypass
ip_rules
virtual_network_subnet_ids`
Terraform will still try to add default_action             = "Allow"

### Steps to Reproduce

Terraform plan will show changes after version 3.112
Terraform apply will apply, but next time terraform plan will still show the same changes on network_rules

**Comment by magodo** [comment]
Hi @tzoetemelk-dsc, this issue duplicates to https://github.com/hashicorp/terraform-provider-azurerm/issues/26854, please find the reason and solution from that. I'll close this issue for now, please feel free to reopen it if you have any other question.
