### ISSUE TITLE
azurerm_data_factory_linked_custom_service does not support "type" = "Lakehouse"

### ISSUE THREAD

**Issue by nise2** [hashicorp/terraform-provider-azurerm#27044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Version
```
terraform {
  backend "azurerm" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">=3.115.0" #(latest today)
    }
 // ...
}
```

### Description

**Missing "Lakehouse" Linked Service Type in AzureRM Provider** : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_custom_service

**Expected Behavior:**

I expect the provider to recognize the "Lakehouse" linked service type and create the resource accordingly, allowing me to configure specific properties and behaviors associated with Lakehouse environments.

Here is the documentation associated with this connector : https://learn.microsoft.com/en-gb/azure/data-factory/connector-microsoft-fabric-lakehouse?tabs=data-factory

**What I tried to bypass the issue:** 
I (recklessly) replaced "Lakehouse" by "MicrosoftFabricLakehouse" (base on the connector name), but same not working.
So I guess that "Lakehouse" is simply not supported yet.

**Actual Behavior:**
The actual terraform apply is overriding the specified "Lakehouse" (from the code and the plan as shown below) type with "LinkedService" leading to incorrect resource creation and potential configuration issues.

![Screenshot 2024-08-14 at 19 02 45](https://github.com/user-attachments/assets/619c020b-2ab0-489f-8eed-e6967f39acd4)

**Steps to Reproduce:**

**1. Create a Terraform configuration** 
```
resource "azurerm_data_factory_linked_service" "lakehouse_linked_service" {
  name                 = "my_lakehouse_linked_service"
  connection_string   = "my_connection_string"
  type                 = "Lakehouse"  # This type is being replaced
...
}
```

**2. Apply the configuration**
`terraform apply`

**3. Observe the created resource:**
`Verify in the Azure portal that the linked service type is "LinkedService" instead of "Lakehouse".`

![Screenshot 2024-08-14 at 16 17 22](https://github.com/user-attachments/assets/59ba35dc-bb39-4054-b62a-bc8d4179101f)

I believe adding support for the "Lakehouse" linked service type would greatly enhance the flexibility and capabilities of the AzureRM provider for working with Azure Data Factory / Azure Fabric and Lakehouse environments.

### Workaround
Do you have any ?

### Affected Resource(s)/Data Source(s)
- data_factory_linked_custom_service

### New Resource(s)/Data Source(s)
In the mean time, I suggest this : 
- azurerm_data_factory_dataset_lakehouse

### Potential Terraform Configuration

```
resource "azurerm_data_factory_linked_custom_service" "ls_lakehouse" {
  name            = <lakehouseName>
  data_factory_id = <dataFactoryId>
  type            = "Lakehouse"
...
}
```

### References
https://learn.microsoft.com/en-gb/azure/data-factory/connector-microsoft-fabric-lakehouse?tabs=data-factory
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_custom_service

**Comment by robertoNdams** [comment]
The solution is very simple: 

replace type       = "Lakehouse" with  **type       = "LakeHouse"**
 
 which comes from this [documentation](https://learn.microsoft.com/en-us/azure/templates/microsoft.datafactory/factories/linkedservices?pivots=deployment-language-bicep )

**Comment by nise2** [comment]
Thank you ! 😃
