### ISSUE TITLE
[DOCS] v4.0 upgrade guide indicates azurerm_kubernetes_cluster_node_pool property node_taints will be removed in v4.0?

### ISSUE THREAD

**Issue by tspearconquest** [hashicorp/terraform-provider-azurerm#27041]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform (and AzureRM Provider) Version
N/A - I am reading the docs

* Terraform Core version: N/A
* AzureRM Provider version: v4.0

### Affected Resource(s)/Data Source(s)

`azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files
N/A

### Description / Feedback

2 questions really.

1. Is this correct?
    I understand this property is deprecated in the `azurerm_kubernetes_cluster` resource itself because we can set the property to enable the critical addons only taint on the default system nodepool.
    However, the additional nodepools created by this resource have no such property and no other method to apply a taint to those nodes. Manually applying a taint to the nodes via kubectl will be overridden by Azure API as far as I am aware, and does not prevent workloads from being scheduled to the nodes between the time they join the cluster and the time an administrator applies the taint.
2. If this is correct, then how should we apply a taint to user node pools created by the `azurerm_kubernetes_cluster_node_pool` resource?

### References
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#azurerm_kubernetes_cluster_node_pool

**Comment by stephybun** [comment]
Hey @tspearconquest,

Thanks for pointing this out! It looks like this was an oversight, this property is not deprecated and will not be removed from the `azurerm_kubernetes_cluster_node_pool` resource in v4.0. I'll remove that line from the upgrade guide.

**Comment by stephybun** [comment]
Done by https://github.com/hashicorp/terraform-provider-azurerm/commit/a1189c6d6ad53360ffab8c9e811167b8e303a526
