### ISSUE TITLE
Failing - Azure storage account with disabling access key

### ISSUE THREAD

**Issue by psomasundaram70** [hashicorp/terraform-provider-azurerm#27043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.4

### AzureRM Provider Version

3.73.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
Please refer main.tf.txt attachment under reference.
```

### Debug Output/Panic Output

```shell
Please refer terraform-debug.txt attachment under reference.
```

### Expected Behaviour

Storage account should be created by disabling "access key" without any Terraform error.

### Actual Behaviour

Looks like, the "**Terraform or AzureRM**" provider is attempting to access the storage account with "**Access Key**" but the access key has been disabled for the newly created storage account hence it is failing. 

**Don't know why is making a call with access key, when that option is disabled for the storage account.**

### Steps to Reproduce

1. Rename attached main.tf.txt to main.tf
2. Update the values for **subscription_id, tenant_id , client_id and client_secret** under **backend "azurerm"** and **provider "azurerm"** blocks in **main.tf** file.
3. Run the following commands:

terraform init
terraform plan -out main.tfplan
terraform apply "main.tfplan" 

### Important Factoids

eastus2

### References

Attached main.tf.txt
[main.tf.txt](https://github.com/user-attachments/files/16615748/main.tf.txt)
[terraform-debug.log](https://github.com/user-attachments/files/16615766/terraform-debug.log)

**Comment by magodo** [comment]
The reason is that you have ` shared_access_key_enabled = false`, while currently the queue's data plane client in this provider only supports key based auth (instead of the AAD). This issue actually duplicates to https://github.com/hashicorp/terraform-provider-azurerm/issues/17341.

Since this is a configuration question I'm going to close this issue for the moment, but as mentioned above I'd recommend subscribing to https://github.com/hashicorp/terraform-provider-azurerm/issues/2977 here which should fix this longer-term.
