### ISSUE TITLE
"admin_enabled" does not work in "azurerm_container_registry"

### ISSUE THREAD

**Issue by jvictorcf** [hashicorp/terraform-provider-azurerm#27040]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.0

### AzureRM Provider Version

3.115.0

### Affected Resource(s)/Data Source(s)

azurerm_container_registry

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "test-rg"
  location = "North Europe"
}

resource "azurerm_container_registry" "acr" {
  name                          = "testacr"
  resource_group_name           = azurerm_resource_group.this.name
  location                      = "North Europe"
  sku                           = "Premium"
  admin_enabled                 = true
  public_network_access_enabled = true
  anonymous_pull_enabled        = false
  tags                          = local.tags
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The admin user should have been enabled in the ACR. You can find this configuration on Settings -> Access Keys -> Admin User.

### Actual Behaviour

Admin user option is disabled.

### References

[Documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_registry#admin_enabled)

**Comment by magodo** [comment]
@jvictorcf I've tried with the v3.115.0 provider locally, and the `admin_enabled` is correctly defined to be true in both API and from Portal. Presumably, your environment has some policy or other out-of-band process going on that made the change. You can check the Azure activity log to find out.

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment, but should you have further usage questions [I'd direct you towards the Community Discuss forum](https://discuss.hashicorp.com).

**Comment by jvictorcf** [comment]
Oh ok. Fair enough. It's probably something else causing this on my side, then.
Thank you.
