### ISSUE TITLE
Cannot enable Azure Container Storage using extension

### ISSUE THREAD

**Issue by ksharma-qc** [hashicorp/terraform-provider-azurerm#27064]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.4

### AzureRM Provider Version

3.115.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster_extension

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster_extension" "container_storage" {
  name           = "microsoft.azurecontainerstorage"
  cluster_id     = module.aks.cluster_id
  extension_type = "microsoft.azurecontainerstorage"

  configuration_settings = {
    "enable-azure-container-storage": "ephemeralDisk",
    "storage-pool-option": "NVMe",
    "azure-container-storage-nodepools": "storagepool",
    "performanceTier": "Standard"
  }
}
```

### Debug Output/Panic Output

```shell
│ Status: "Failed"
│ Code: "ExtensionOperationFailed"
│ Message: "The extension operation failed with the following error:  Error: [ InnerError: [Helm installation failed :  : InnerError [r
│ and has been uninstalled due to atomic being set: Service \"microsoft.azurecontainerst-coredns\" is invalid: metadata.name: Invalid v
│ DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanu
│ regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')]]] occurred while doing the operation : [Create] on the config, For genera
│ https://aka.ms/k8s-extensions-TSG."
│ Activity Id: ""
│
│ ---
```

### Expected Behaviour

Azure container storage should get enabled on the cluster. The operation works fine with Azure CLI `az aks update -n $CLUSTER_NAME -g $RG --enable-azure-container-storage ephemeralDisk --storage-pool-option NVMe --azure-container-storage-nodepools datapool`.

Tried with a newly provisioned cluster to no avail. The azurerm examples are missing an example for azure container storage on AKS.

The cluster has 3 nodes with NVMe storage.

### Actual Behaviour

Throws an invalid name error.

### Steps to Reproduce

Terraform apply with the above config.

### Important Factoids

Azure uksouth

**Comment by tgahlx** [comment]
@ksharma-qc 
i was able to deploy it using this settings:

```
      "global.cli.storagePool.install.name" = "ephemeraldisk-nvme",
      "global.cli.storagePool.install.size" = "512Gi"
      "global.cli.storagePool.install.type" = "ephemeralDisk",
      "global.cli.storagePool.install.diskType" = "nvme",
      "global.cli.activeControl" = "True",
      "global.cli.storagePool.install.create" = "True",
      "global.cli.storagePool.azureDisk.enabled" = "False",
      "global.cli.storagePool.elasticSan.enabled" = "False",
      "global.cli.storagePool.ephemeralDisk.nvme.enabled" = "True",
      "global.cli.storagePool.ephemeralDisk.temp.enabled" = "False",
      "global.cli.storagePool.ephemeralDisk.enableEphemeralBypassAnnotation" = "False",
      "global.cli.storagePool.ephemeralDisk.nvme.perfTier" = "Standard",
      "global.cli.storagePool.disable.validation" = "False",
      "global.cli.storagePool.disable.active" = "False",
      "global.cli.resources.num_hugepages" = "1024",
      "global.cli.resources.ioEngine.cpu" = "2.0",
      "global.cli.resources.ioEngine.memory" = "2Gi",
      "global.cli.resources.ioEngine.hugepages2Mi" = "2Gi",
  ```
  
  I've deployed it using the cli and checked the config in the portal.

**Comment by ksharma-qc** [comment]
> global.cli.storagePool.ephemeralDisk.nvme.enabled

Not sure I follow. Are you deploying using Azure CLI? Where do these settings go? This issue is for `azurerm_kubernetes_cluster_extension` resource in Terraform provider.

**Comment by tgahlx** [comment]
@ksharma-qc 
i've put this configuration into the `configuration_settings` block.

I've created it once via cli to have this config displayed in the azure portal.

**Comment by ksharma-qc** [comment]
> @ksharma-qc i've put this configuration into the `configuration_settings` block.
> 
> I've created it once via cli to have this config displayed in the azure portal.

Ah makes sense. I'll try that today and close the issue if it works.

**Comment by ksharma-qc** [comment]
> @ksharma-qc i've put this configuration into the `configuration_settings` block.
> 
> I've created it once via cli to have this config displayed in the azure portal.

Still the same error. 
```
│ ----[start]----
│ {"id":"/subscriptions/61563bab-9e7d-4714-9c33-61bc00b1f222/resourceGroups/rg-test-cluster-d8r/providers/Microsoft.ContainerService/ManagedClusters/aks-uksouth-acstortest-dev-d8r/providers/Microsoft.KubernetesConfiguration/extensions/microsoft.azurecontainerstorage/operations/d9e3114a-f83c-4170-bf0b-7f5ea4948620","name":"d9e3114a-f83c-4170-bf0b-7f5ea4948620","status":"Failed","error":{"code":"ExtensionOperationFailed","message":"The
│ extension operation failed with the following error:  Error: [ InnerError: [Helm installation failed :  :
│ InnerError [an error occurred while uninstalling the release. original install error: Service
│ \"microsoft.azurecontainerst-coredns\" is invalid: metadata.name: Invalid value:
│ \"microsoft.azurecontainerst-coredns\": a DNS-1035 label must consist of lower case alphanumeric characters or
│ '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123',
│ regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?'): warning: Hook pre-delete
│ acstor/templates/hooks/pre-delete-storagepool-delete.yaml failed: Job.batch
│ \"microsoft.azurecontainerstorage-pre-delete-storagepool-delete-job\" is invalid: spec.template.labels: Invalid
│ value: \"microsoft.azurecontainerstorage-pre-delete-storagepool-delete-job\": must be no more than 63
│ characters]]] occurred while doing the operation : [Create] on the config, For general troubleshooting visit:
│ https://aka.ms/k8s-extensions-TSG.","additionalInfo":[]}}
```

Here is the Terraform config used: 
```
resource "azurerm_kubernetes_cluster_extension" "container_storage" {
  name           = "microsoft.azurecontainerstorage"
  cluster_id     = module.aks.cluster_id
  extension_type = "microsoft.azurecontainerstorage"

  configuration_settings = {
    "global.cli.storagePool.install.name" = "ephemeraldisk-nvme",
    "global.cli.storagePool.install.size" = "512Gi"
    "global.cli.storagePool.install.type" = "ephemeralDisk",
    "global.cli.storagePool.install.diskType" = "nvme",
    "global.cli.activeControl" = "True",
    "global.cli.storagePool.install.create" = "True",
    "global.cli.storagePool.azureDisk.enabled" = "False",
    "global.cli.storagePool.elasticSan.enabled" = "False",
    "global.cli.storagePool.ephemeralDisk.nvme.enabled" = "True",
    "global.cli.storagePool.ephemeralDisk.temp.enabled" = "False",
    "global.cli.storagePool.ephemeralDisk.enableEphemeralBypassAnnotation" = "False",
    "global.cli.storagePool.ephemeralDisk.nvme.perfTier" = "Standard",
    "global.cli.storagePool.disable.validation" = "False",
    "global.cli.storagePool.disable.active" = "False",
    "global.cli.resources.num_hugepages" = "1024",
    "global.cli.resources.ioEngine.cpu" = "2.0",
    "global.cli.resources.ioEngine.memory" = "2Gi",
    "global.cli.resources.ioEngine.hugepages2Mi" = "2Gi",
  }
}
```

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
Hi @ksharma-qc , thanks for raising this.

I think the issue is that the `name` cannot accept `.`, only alphanumeric and `-`.

Below script worked for me:

```
resource "azurerm_kubernetes_cluster_extension" "container_storage" {
  name           = "microsoft-azurecontainerstorage"
  cluster_id     = azurerm_kubernetes_cluster.example.id
  extension_type = "microsoft.azurecontainerstorage"
  configuration_settings = {
    "enable-azure-container-storage" : "ephemeralDisk",
    "storage-pool-option" : "NVMe",
    "azure-container-storage-nodepools" : "storagepool",
    "performanceTier" : "Standard"
  }
}
```

**Comment by ksharma-qc** [comment]
> Hi @ksharma-qc , thanks for raising this.
> 
> I think the issue is that the `name` cannot accept `.`, only alphanumeric and `-`.
> 
> Below script worked for me:
> 
> ```hcl
> resource "azurerm_kubernetes_cluster_extension" "container_storage" {
>   name           = "microsoft-azurecontainerstorage"
>   cluster_id     = azurerm_kubernetes_cluster.example.id
>   extension_type = "microsoft.azurecontainerstorage"
>   configuration_settings = {
>     "enable-azure-container-storage" : "ephemeralDisk",
>     "storage-pool-option" : "NVMe",
>     "azure-container-storage-nodepools" : "storagepool",
>     "performanceTier" : "Standard"
>   }
> }
> ```

Yes that was indeed the problem. Closing this issue.
