### ISSUE TITLE
Virtual machine "license_type" isn't documented properly and doesn't allow all possible options

### ISSUE THREAD

**Issue by rgrace-puck** [hashicorp/terraform-provider-azurerm#27077]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.4

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "my_vm" {
  location              = "centralus"
  name                  = "vm-my-example"
  resource_group_name   = "rg-my-exmaple"

  license_type = "None" # this enables Azure Hybrid licensing
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

license_type should allow the "None" option as shown here:
https://learn.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing#powershell-1

Documentation should also make it more clear this pertains to Azure Hybrid licensing and involves additional compliance requirements.

### Actual Behaviour

Error: expected license_type to be one of ["Windows_Client" "Windows_Server"], got None

### References

https://learn.microsoft.com/en-us/azure/virtual-machines/windows/hybrid-use-benefit-licensing#powershell-1
https://learn.microsoft.com/en-us/windows-server/get-started/azure-hybrid-benefit?tabs=azure

**Comment by rcskosir** [comment]
@rgrace-puck Thanks for taking the time to open this issue. The azurerm_virtual_machine resource has been superseded by the [azurerm_linux_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_virtual_machine) and [azurerm_windows_virtual_machine](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine) resources. The existing azurerm_virtual_machine resource will continue to be available throughout the 3.x releases however is in a feature-frozen state to maintain compatibility - new functionality will instead be added to the azurerm_linux_virtual_machine and azurerm_windows_virtual_machine resources. 
I believe azurerm_windows_virtual_machine allows for a license type of None, have you been able to try that resource?

**Comment by rgrace-puck** [comment]
I didn't notice that, you are correct. 

The app service (azurerm_app_service) is similar but that deprecation notice is more apparent with the "danger" severity being used.
