### ISSUE TITLE
Support for defaultIngressControllerType in azurerm_kubernetes_cluster web_app_routing configuration block

### ISSUE THREAD

**Issue by underguiz** [hashicorp/terraform-provider-azurerm#27109]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

When you enable the application routing add-on with NGINX, it creates an ingress controller called default in the app-routing-namespace configured with a public facing Azure load balancer. That ingress controller uses an ingress class name of webapprouting.kubernetes.azure.com.

You can also control if the default gets a public or an internal IP, or if it gets created at all when enabling the add-on using **BICEP**. 

This configuration is crucial in regulated environments and the web_app_routing configuration block should support it.

Bicep example:

"ingressProfile": {
      "webAppRouting": {
        "nginx": {
            "defaultIngressControllerType": "None|Internal|External|AnnotationControlled"
        }
    }
    
Link to documentation: 

https://learn.microsoft.com/en-us/azure/aks/app-routing-nginx-configuration?tabs=bicep#control-the-default-nginx-ingress-controller-configuration

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  web_app_routing {
    dns_zone_ids = [ "/subscriptions/(...)/dnszone" ]
    default_type = none|internal|external
  }

}
```

**Comment by ms-henglu** [comment]
Hi @underguiz ,

Thank you for taking time to report this issue.

This feature is still in preview, we could support it in the azurerm provider. Here's config about how to use this feature with azapi provider, hope it could help you.

```hcl
resource "azapi_resource" "aksCluster" {
  type      = "Microsoft.ContainerService/managedClusters@2024-06-02-preview"
  parent_id = azapi_resource.resourceGroup.id
  name      = "hengluaks"
  location  = "westus"

  identity {
    type = "SystemAssigned"
  }

  body = {
    properties = {
      kubernetesVersion = "1.30.3"
      dnsPrefix         = "hengluaks"
      enableRBAC        = true
      agentPoolProfiles = [
        {
          name   = "agentpool"
          count  = 3
          vmSize = "Standard_DS2_v2"
          osType = "Linux"
          mode   = "System"
        }
      ]
      ingressProfile = {
        webAppRouting = {
          nginx = {
            defaultIngressControllerType = "AnnotationControlled"
          }
        }
      }
    }
  }
}
```

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to label this issue as such and close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
