### ISSUE TITLE
Support for `dynamicThrottlingEnabled` in `azurerm_cognitive_deployment`

### ISSUE THREAD

**Issue by Davasny** [hashicorp/terraform-provider-azurerm#27125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

New azure API (2024-06-01) supports field `dynamicThrottlingEnabled` in openai deployments which is missing in `azurerm_cognitive_deployment`

### New or Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Potential Terraform Configuration

```hcl
resource "azurerm_cognitive_deployment" "this" {
  dynamic_throttling_enabled = true
}
```

### References

https://learn.microsoft.com/en-us/rest/api/aiservices/accountmanagement/deployments/update?view=rest-aiservices-accountmanagement-2024-06-01-preview&tabs=HTTP

**Comment by mkemmerz** [comment]
I think this issue can be closed because it is a duplicate of https://github.com/hashicorp/terraform-provider-azurerm/pull/28100 ?

**Comment by Davasny** [comment]
Yes, thanks for that!
