### ISSUE TITLE
Failure to create "azurerm_cosmosdb_postgresql_cluster"

### ISSUE THREAD

**Issue by ThorstenKatz** [hashicorp/terraform-provider-azurerm#27138]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.4

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_postgresql_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_postgresql_cluster" "example" {
  name                            = "examplecluster"
  resource_group_name             = azurerm_resource_group.rg.name
  location                        = azurerm_resource_group.rg.location
  administrator_login_password    = "H@Sh1CoR3!"
  coordinator_server_edition      = "BurstableGeneralPurpose"
  coordinator_storage_quota_in_mb = 32768
  coordinator_vcore_count         = 1
  node_count                      = 0
}
```

### Debug Output/Panic Output

```shell
│ Server Groupsv 2 Name: "examplecluster"): performing Update: unexpected status 400 (400 Bad Request) with error: bad_request: There is no valid SKU with given coordinatorserver edition ("BurstableGeneralPurpose") and vCores (1).
│ 
│   with module.cosmosdb.azurerm_cosmosdb_postgresql_cluster.example,
│   on ../../modules/cosmosdb/main.tf line 21, in resource "azurerm_cosmosdb_postgresql_cluster" "example":
│   21: resource "azurerm_cosmosdb_postgresql_cluster" "example" {
│ 
│ Server Groupsv 2 Name: "examplecluster"): performing Update: unexpected
│ status 400 (400 Bad Request) with error: bad_request: There is no valid SKU
│ with given coordinatorserver edition ("BurstableGeneralPurpose") and vCores
│ (1).
```

### Expected Behaviour

The cluster is created as a single node with a "Burstable, 1vCore, 2GiB RAM and 32GB storage", as is also possible via the Azure portal.

### Actual Behaviour

The Terraform rollout aborts with the specified error message.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems your config is incorrect. "Burstable, 1 vCore(s) / 2 GiB RAM" only supports "BurstableMemoryOptimized" in Azure Portal/ Service API. Please update your config. THanks.

**Comment by ThorstenKatz** [comment]
Thanks for the info, creating the cluster worked with your parameter.

In my opinion, this parameter is not sufficiently documented. Because only “Bursted” is displayed in the portal, which I find a bit confusing.
