### ISSUE TITLE
data.azurerm_virtual_machine.power_state returns null 

### ISSUE THREAD

**Issue by na-init** [hashicorp/terraform-provider-azurerm#27147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.5

### AzureRM Provider Version

3.113.0

### Affected Resource(s)/Data Source(s)

Data Source: azurerm_virtual_machine

### Terraform Configuration Files

```hcl
terraform {
  required_version = "1.8.5"
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "2.48.0"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.113.0"
    }
  }
}


data "azurerm_virtual_machine" "virtual_machines" {
  name                = "xyz"
  resource_group_name = "xyz"
}
```

### Debug Output/Panic Output

```shell
https://registry.terraform.io/providers/hashicorp/azurerm/3.113.0/docs/data-sources/virtual_machine
```

### Expected Behaviour

VM output attribute power_state should not be null. 

### Actual Behaviour

VM output attribute power_state is null. 

### Steps to Reproduce

use terraform version 1.8.5
azure rm version 3.113.0
use a data block for vm 
VM output attribute power_state should not be null. 

### References

https://registry.terraform.io/providers/hashicorp/azurerm/3.113.0/docs/data-sources/virtual_machine

**Comment by stephybun** [comment]
Thanks for raising this issue @na-init. I believe this was fixed by #26991 and was released in v3.116.0.
