### ISSUE TITLE
azurerm_cognitive_deployment in latest version of the provider not working

### ISSUE THREAD

**Issue by JAGonzaleDiaz** [hashicorp/terraform-provider-azurerm#27179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.3

### AzureRM Provider Version

4.0.0

### Affected Resource(s)/Data Source(s)

azurerm_cognitive_deployment

### Terraform Configuration Files

```hcl
resource "azurerm_cognitive_deployment" "openai" {
  for_each = local.deployed_models

  name                 = each.value.deployment_name
  cognitive_account_id = azurerm_cognitive_account.openai[each.value.location].id

  model {
    format  = "OpenAI"
    name    = each.value.model_name
    version = each.value.model_version
  }

  scale {
    type     = each.value.scale.type
    tier     = each.value.scale.tier
    size     = each.value.scale.size
    family   = each.value.scale.family
    capacity = each.value.scale.type == "Standard" ? each.value.scale.capacity / 1000 : each.value.scale.capacity
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Insufficient sku blocks
│
│   on openai.tf line 35, in resource "azurerm_cognitive_deployment" "openai":
│   35: resource "azurerm_cognitive_deployment" "openai" {
│
│ At least 1 "sku" blocks are required.
╵
╷
│ Error: Unsupported block type
│
│   on openai.tf line 48, in resource "azurerm_cognitive_deployment" "openai":
│   48:   scale {
│
│ Blocks of type "scale" are not expected here.
```

### Expected Behaviour

deployment should be successful

### Actual Behaviour

At least 1 "sku" blocks are required.

### Steps to Reproduce

latest version of the azure provider and deploy a new cognitive deployment

### References

the latest provider documentation doesn't reflect this change

**Comment by stephybun** [comment]
Thanks for raising this issue @JAGonzaleDiaz.

This has been fixed by https://github.com/hashicorp/terraform-provider-azurerm/pull/27173 and released in v4.0.1.
