### ISSUE TITLE
auto_heal_enabled is not available in later azurerm version

### ISSUE THREAD

**Issue by praveenambati1233** [hashicorp/terraform-provider-azurerm#27186]
**AzureRM version** - 4.0.0
**terraform version** - 1.3.9

Error : An argument named "auto_heal_enabled" is not expected here. 
It seems it is removed after 3.116.0 version.

**Comment by mybayern1974** [comment]
Thank you for opening this issue. Given it looks like duplicate with #27185, please subscribe the opened one earlier.
