### ISSUE TITLE
no schema available for azurerm_dashboard. out of terraform plan for azurerm_portal_dashboard 

### ISSUE THREAD

**Issue by MarcusGasser** [hashicorp/terraform-provider-azurerm#27198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_portal_dashboard

### Terraform Configuration Files

```hcl
locals {   
  dashboards_base_path = "json-templates/dashboards/%s" 
} 

 resource "azurerm_portal_dashboard" "entrypoint_dashboard" {   
  name                = "entrypoint_dashboard"   
  resource_group_name = azurerm_resource_group.cos_workbooks_rg.name 
  location            = var.location   
  tags = {     
    "hidden-title" : "Entrypoint Dashboard"   
  }   
  dashboard_properties = file(format(local.dashboards_base_path, "entrypoint-dashboard.json")) 
}
```

### Debug Output/Panic Output

```shell
Terraform planned the following actions, but then encountered a problem:
  # azurerm_portal_dashboard.entrypoint_dashboard will be created
  + resource "azurerm_portal_dashboard" "entrypoint_dashboard" {
      + dashboard_properties = jsonencode(
            {
              + lenses   = {
                  + "0" = {
                      + order = 0
                      + parts = {
                          + "0" = {
                              + metadata = {
                                  + inputs   = []
                                  + settings = {
                                      + content = {
                                          + content        = <<-EOT
                                                # ... dashboard code
                                                </div>
                                            EOT
                                          + markdownSource = 1
                                          + markdownUri    = ""
                                          + subtitle       = ""
                                          + title          = ""
                                        }
                                    }
                                  + type     = "Extension/HubsExtension/PartType/MarkdownPart"
                                }
                              + position = {
                                  + colSpan = 10
                                  + rowSpan = 7
                                  + x       = 0
                                  + y       = 0
                                }
                            }
                        }
                    }
                }
              + metadata = {
                  + model = {
                      + timeRange = {
                          + type  = "MsPortalFx.Composition.Configuration.ValueTypes.TimeRange"
                          + value = {
                              + relative = {
                                  + duration = 24
                                  + timeUnit = 1
                                }
                            }
                        }
                    }
                }
            }
        )
      + id                   = (known after apply)
      + location             = "switzerlandnorth"
      + name                 = "entrypoint_dashboard"
      + resource_group_name  = "cos-workbooks-iac-preprod-rg"
      + tags                 = {
          + "hidden-title" = "Entrypoint Dashboard"
        }
    }
Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Error: no schema available for azurerm_dashboard.entrypoint_dashboard while reading state; this is a bug in Terraform and should be reported
│
```

### Expected Behaviour

should end with exit code 0

### Actual Behaviour

│ Error: no schema available for azurerm_dashboard.entrypoint_dashboard while reading state; this is a bug in Terraform and should be reported

### Steps to Reproduce

terraform plan

**Comment by hqhqhqhqhqhqhqhqhqhqhq** [comment]
Hi @MarcusGasser , thanks for raising this.

I believe the issue it that the resource was originally named as `azurerm_dashboard` and got renamed to `azurerm_portal_dashboard` in v4.0. The `azurerm_dashboard` exist in your state file, that is why terraform error during reading it from the state. 

To address this, you can:
1. Backup your state in case anything goes wrong
2. Remove `azurerm_dashboard` from the state file via `terraform state rm azurerm_dashboard.entrypoint_dashboard`
3. Make the changes in your config
4. Import those the resource back to state via `terraform import azurerm_portal_dashboard.entrypoint_dashboard <resource id>`

**Comment by MarcusGasser** [comment]
Thak you so much, worked for me!
