### ISSUE TITLE
azurerm_kubernetes_cluster default_node_pool certain values ignored

### ISSUE THREAD

**Issue by tjmullicani** [hashicorp/terraform-provider-azurerm#27201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.4

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  ...
  default_node_pool {
    ...
    name                    = "agentpool"
    host_encryption_enabled = true
    node_public_ip_enabled  = false
  }
}
```

### Expected Behaviour

AKS cluster is created with correct settings.

### Actual Behaviour

`azurerm_kubernetes_cluster` `default_node_pool` variables `host_encryption_enabled` and `node_public_ip_enabled` are not configured within AKS. Every time terraform is run, they have the incorrect value shown, and the change is not applied upstream to AKS.

```console
...
~ default_node_pool {
          ~ host_encryption_enabled       = false -> true
            name                          = "agentpool"
          ~ node_public_ip_enabled        = true -> false
            tags                          = {}
            # (28 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
```

```console
2024-08-26T22:17:04.794Z [WARN]  Provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced an unexpected new value for azurerm_kubernetes_cluster.aks, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .default_node_pool[0].node_public_ip_enabled: was cty.False, but now cty.True
      - .default_node_pool[0].host_encryption_enabled: was cty.True, but now cty.False
```

### Steps to Reproduce

1. terraform apply
2. terraform apply shows that host_encryption_enabled  and node_public_ip_enabled have not changed.

### Important Factoids

Azure Government

### References

https://github.com/hashicorp/terraform-provider-azurerm/blob/99b4df813da8023e69481bebc5bc84c2dc3e8dda/internal/services/containers/kubernetes_cluster_resource.go#L2663C3-L2668C4

https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/features/four_point_oh.go#L47

**Comment by slushysnowman** [comment]
Yeah we're having the exact same issue:
```
      ~ default_node_pool {
          ~ host_encryption_enabled       = false -> true
            name                          = "system"
          ~ node_public_ip_enabled        = true -> false
            tags                          = {}
            # (28 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
```
Happening every run and succeeds every time - so every time a temp system nodepool is being spun up...
