### ISSUE TITLE
Plan execution consumes a lot of memory

### ISSUE THREAD

**Issue by peeeeecho** [hashicorp/terraform-provider-azurerm#27204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.1

### AzureRM Provider Version

3.105.0

### Affected Resource(s)/Data Source(s)

Terraform execution client memory consumption.

### Terraform Configuration Files

```hcl
I have prepared the following syntax for each subscription.

*-----
## rpr
resource "null_resource" "rpr_SubscriptionID" {
  for_each     = toset([ for s in local.resource_provider : s])
  provisioner "local-exec" {
    command = "az provider register --wait --namespace ${each.value} --subscription SubscriptionID"
  }
}

## Resource Group for CoE
resource "azurerm_resource_group" "rg_SubscriptionID" {
  provider = azurerm.sub_SubscriptionID
  name     = local.name.rg01
  location = local.location.Japan-East
}

## activity log
resource "azurerm_monitor_diagnostic_setting" "mds_SubscriptionID" {
  provider                   = azurerm.sub_SubscriptionID
  log_analytics_workspace_id = local.coe_id.log01
  name                       = local.name.mds01
  storage_account_id         = local.coe_id.st01
  target_resource_id         = "/subscriptions/SubscriptionID"

  enabled_log {
    category = "Administrative"
  }
  enabled_log {
    category = "Alert"
  }
  enabled_log {
    category = "Autoscale"
  }
  enabled_log {
    category = "Policy"
  }
  enabled_log {
    category = "Recommendation"
  }
  enabled_log {
    category = "ResourceHealth"
  }
  enabled_log {
    category = "Security"
  }
  enabled_log {
    category = "ServiceHealth"
  }

  depends_on = [
    null_resource.rpr_SubscriptionID
  ]

  timeouts {}
}

## ag
resource "azurerm_monitor_action_group" "ag_SubscriptionID" {
  provider            = azurerm.sub_SubscriptionID
  enabled             = true
  name                = local.name.ag01
  resource_group_name = local.name.rg01
  short_name          = local.name.agshort01
  tags                = {}

  dynamic "email_receiver" {
    for_each = [for s in [
        "hoge@fuga.com",
      ] : s
    ]

    content {
      name          = email_receiver.value
      email_address = email_receiver.value
    }
  }

  depends_on = [
    null_resource.rpr_SubscriptionID,
    azurerm_resource_group.rg_SubscriptionID
  ]

  timeouts {}
}

## ServiceHealth
resource "azurerm_monitor_activity_log_alert" "ala_SubscriptionID" {
  provider            = azurerm.sub_SubscriptionID
  enabled             = true
  name                = local.name.ala01
  resource_group_name = local.name.rg01
  scopes              = ["/subscriptions/SubscriptionID"]
  tags                = {}

  action {
    action_group_id    = azurerm_monitor_action_group.ag_SubscriptionID.id
    webhook_properties = {}
  }

  criteria {
    category = "ServiceHealth"

    service_health {
      events    = []
      locations = []
      services  = []
    }
  }

  depends_on = [
    null_resource.rpr_SubscriptionID,
    azurerm_resource_group.rg_SubscriptionID
  ]

  timeouts {}
}
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Consumes about 3GB of memory.

### Actual Behaviour

【Issue】
I am trying to create the following resources for multiple subscriptions in one process.
The more subscriptions there are, the more memory is consumed when the plan is executed.

Is this normal ??
Even when deploying a large number of resources (over 100) in a single subscription, memory usage never exceeded 3GB.

Please let me know if there is a solution.

*—--
Memory usage
　70 Subscription: 8GB Mem
　90 Subscription: 9GB Mem
　110 Subscription: 10GB Mem
　
【What I have tried】
Specify the -out option when executing the plan.
Specify 1 for the parallelism option.
->Neither of these reduced memory consumption.

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
