### ISSUE TITLE
azurerm_service_plan doesn't implement P0V3 as a valid sku_name in uk south region

### ISSUE THREAD

**Issue by emoshaya** [hashicorp/terraform-provider-azurerm#27214]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

**Description:**

This was already manually updated from B1 to P0v3 in the Azure Portal and received the following Terraform drift:

```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.azure.azurerm_service_plan.this[0] will be updated in-place
  ~ resource "azurerm_service_plan" "this" {
        id                           = "/subscriptions/d1eb81d6-2585-4283-ac28-91d097732b55/resourceGroups/prod2/providers/Microsoft.Web/serverfarms/policyengine-prod2"
        name                         = "policyengine-prod2"
      ~ sku_name                     = "P0v3" -> "B1"
        tags                         = {
            "Name"              = "policyengine-prod2"
            "Project"           = "infra-policyengine-terraform-workspace"
            "dc"                = "prod2"
            "tenant"            = "tl"
            "terraform-managed" = "true"
            "terraform-project" = "infra-policyengine-terraform-workspace"
        }
      ~ worker_count                 = 2 -> 1
        # (8 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy

```

When I updated the Terraform configuration to fix this drift, I get the error that P0v3 is not a supported SKU.

### Terraform Version

1.9.5

### AzureRM Provider Version

3.44.1

### Affected Resource(s)/Data Source(s)

azurerm_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_service_plan" "asp" {
  name                = "name"
  location            = "UK South"
  resource_group_name = "test"
  tags                = []
  os_type             = "Linux"
  sku_name            = "P0v3"
  worker_count        = 2
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: expected sku_name to be one of [B1 B2 B3 S1 S2 S3 P1v2 P2v2 P3v2 P1v3 P2v3 P3v3 Y1 EP1 EP2 EP3 F1 I1 I2 I3 I1v2 I2v2 I3v2 D1 SHARED WS1 WS2 WS3], got P0v3
│
│   with module.azure.azurerm_service_plan.this[0],
│   on modules/azure/main.tf line 20, in resource "azurerm_service_plan" "this":
│   20:   sku_name = var.az_web_app_service_plan_sku
│
╵
```

### Expected Behaviour

to have an app service plan corresponding the new supported plan

### Actual Behaviour

error

### Steps to Reproduce

terraform plan failed

### Important Factoids

N/A

### References

- https://github.com/hashicorp/terraform-provider-azurerm/issues/21554
- https://github.com/hashicorp/terraform-provider-azurerm/issues/21879

**Comment by rcskosir** [comment]
@emoshaya Thank you for taking the time to open this issue. It looks like support was added in 3.52 per this [discussion](https://github.com/hashicorp/terraform-provider-azurerm/issues/21554#issuecomment-1568302431), and a document update followed in 3.59. Please upgrade to 3.52 or higher in order to use the supported P0V3. Thanks!
