### ISSUE TITLE
Version 4 - errors with docker registry settings in `app_settings`

### ISSUE THREAD

**Issue by somesylvie** [hashicorp/terraform-provider-azurerm#27219]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.94

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_linux_web_app

### Terraform Configuration Files

```hcl
https://github.com/CDCgov/reportstream-sftp-ingestion/blob/b0e739e7e1a1a2d8b4582f5e5fa6d9564d4fdff9/operations/template/app.tf#L82
https://github.com/CDCgov/reportstream-sftp-ingestion/pull/133/files
```

### Debug Output/Panic Output

```shell
Error: cannot set a value for DOCKER_REGISTRY_SERVER_PASSWORD in app_settings
Error: cannot set a value for DOCKER_REGISTRY_SERVER_URL in app_settings
Error: cannot set a value for DOCKER_REGISTRY_SERVER_USERNAME in app_settings

https://github.com/CDCgov/reportstream-sftp-ingestion/actions/runs/10534064189/job/29315667211
```

### Expected Behaviour

This should not be an error - these settings are still [in the Azure documentation](https://learn.microsoft.com/en-us/azure/app-service/reference-app-settings?tabs=kudu%2Cdotnet#custom-containers) and there's no mention in the release notes of moving or removing them

### Actual Behaviour

Terraform does not apply

### Steps to Reproduce

`terraform apply` (run via a Github Action)

**Comment by StijnT** [comment]
I am experiencing the same issue. As somesylvie states, these settings are not deprecated or superseded.

**Comment by tejalkalesains** [comment]
Hi 
I have pass docker_registry_url ,  docker_registry_username , docker_registry_password in **application_stack**. that work for me.

`site_config {
    application_stack {
        docker_image_name          = "somepath/myimage:latest"
        docker_registry_url            = "https://${azurerm_container_registry.app-container.login_server}"
        docker_registry_username = azurerm_container_registry.app-container.admin_username
        docker_registry_password = azurerm_container_registry.app-container.admin_password
   }
}`

Please note that the **docker_registry_url** must have the **https://** scheme prefix (http also works).

The settings should not appear in app_settings anymore.

**Comment by somesylvie** [comment]
The Terraform docs have since been updated to talk about the `application_stack` field. At the time I created this issue, the docs had not been updated.
