### ISSUE TITLE
Mandatory shared_key on azurerm_virtual_network_gateway_connection not supported for expressroute connections

### ISSUE THREAD

**Issue by keesmod** [hashicorp/terraform-provider-azurerm#27217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.2

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway_connection

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway_connection" "expressroute" {
  name                       = "expressroute"
  shared_key                 = random_password.shared_key.result
  location                   = var.location
  resource_group_name        = var.resource_group_network_name
  type                       = "ExpressRoute"
  virtual_network_gateway_id = azurerm_virtual_network_gateway.expressroute.id
  express_route_circuit_id   = data.azurerm_express_route_circuit.expressroute.id
  authorization_key          = azurerm_express_route_circuit_authorization.expressroute.authorization_key
  routing_weight             = 0
  connection_mode            = "Default"
  dpd_timeout_seconds        = 0
}
```

### Debug Output/Panic Output

```shell
╷
│ Error: creating Connection (Subscription: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx"
│ Resource Group Name: "rg-name"
│ Connection Name: "expressroute"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: CannotSetSharedKeyForExpressRouteConnectionType: Shared Key cannot be set for Connection /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxx/resourceGroups/rg-name/providers/Microsoft.Network/connections/expressroute of type ExpressRoute.
│ 
│   with module.expressroute_vng.azurerm_virtual_network_gateway_connection.expressroute[0],
│   on modules/expressroute_vng/vng.tf line 79, in resource "azurerm_virtual_network_gateway_connection" "expressroute":
│   79: resource "azurerm_virtual_network_gateway_connection" "expressroute" {
│ 
╵
```

### Expected Behaviour

shared_key should not be mandatory when resourcetype is "ExpressRoute"

### Actual Behaviour

fails with error

**Comment by randomnote1** [comment]
This issue seems to have been caused by #26217 in version `4.0`.

**Comment by mtraynham** [comment]
Setting the value to an empty string seems to be a work around.  Still a valid bug though.

```hcl
  shared_key = ""
```

**Comment by keesmod** [comment]
> Setting the value to an empty string seems to be a work around. Still a valid bug though.
> 
> ```hcl
>   shared_key = ""
> ```

Thanks. I tried that just now, but it doesn't work for my existing expressroute connection. Modifying the resource times out.

**Comment by mtraynham** [comment]
Interesting.  Guess it only works for new Express Route Connections ¯\_(ツ)_/¯?  

For what it's worth, I only took a stab in the dark with a falsy value, and it seemed to work.

**Comment by cohi** [comment]
Better workaround for an existing resource:

shared_key = “*”
lifecycle {
    ignore_changes = [ shared_key ]
}

I don’t know what the endpoint actually does with this dummy value.

**Comment by Tbohunek** [comment]
Maybe we're supposed to use [azurerm_express_route_connection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/express_route_connection) instead?

**Comment by aaronearles** [comment]
> Maybe we're supposed to use [azurerm_express_route_connection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/express_route_connection) instead?

Ran into this during a cutover today. I attempted to use `azurerm_express_route_connection` instead but it requires `express_route_gateway_id` and did NOT accept the Virtual Network Gateway ID. It passed terraform validate and plan, but the API rejected the request during the apply. I attempted to use `"*"`, which also failed, but ultimately `""` was succesful.

**Comment by mverlinden78** [comment]
We are running into another issue where we have to update our providers to the latest version. However, we also deploy our expressroute from the same code, which has the issue as described here.
This is really a blocking issue atm since we cannot upgrade the previous provider because it's introduced another issue.
Can someone please prioritize this.

**Comment by adammontlake** [comment]
> We are running into another issue where we have to update our providers to the latest version. However, we also deploy our expressroute from the same code, which has the issue as described here. This is really a blocking issue atm since we cannot upgrade the previous provider because it's introduced another issue. Can someone please prioritize this.

One possible workaround would be to separate the deployment of the ExpressRoute into a module and give it a different provider version. As long as you are not using FastPath you should be good with 3.99

**Comment by adammontlake** [comment]
> Maybe we're supposed to use [azurerm_express_route_connection](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/express_route_connection) instead?

There are two types of gateway connections in Azure:
1. azurerm_express_route_connection - this is for connecting to an ER gateway in a VWan
2. azurerm_virtual_network_gateway_connection - this is for connecting to a gateway in a VNet

They are not interchangeable
