### ISSUE TITLE
Unable to import the module with version after v1.44

### ISSUE THREAD

**Issue by gokulmaxi** [hashicorp/terraform-provider-azurerm#27234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.5.7

### AzureRM Provider Version

v2.0.0 and above

### Affected Resource(s)/Data Source(s)

all 

### Terraform Configuration Files

```hcl
package main

import (
	"encoding/json"
	"fmt"
	"github.com/hashicorp/terraform-plugin-sdk/terraform"
	tfschema "github.com/hashicorp/terraform-schema/schema"
	"github.com/hashicorp/terraform-provider-azurerm/"	
)

func main() {
	request := &terraform.ProviderSchemaRequest{
		ResourceTypes: []string{"azurerm_linux_virtual_machine"},
	}
	fmt.Print(request)
	fmt.Print(tfschema.LatestAvailableVersion)
	resources, _ := azurerm.Provider().GetSchema(request)
	j, err := json.Marshal(resources.Provider.BlockTypes)
	if err != nil {
		fmt.Printf("Error: %s", err.Error())
	} else {
		fmt.Println(string(j))
	}
}
```

### Debug Output/Panic Output

```shell
module declares its path as: github.com/terraform-providers/terraform-provider-azurerm
                but was required as: github.com/hashicorp/terraform-provider-azurerm
```

### Expected Behaviour

The gomodule should be imported properly

### Actual Behaviour

The latest version I am able to import is version 1.44

### Steps to Reproduce

require (
	github.com/hashicorp/terraform-plugin-sdk v1.17.2
	github.com/hashicorp/terraform-schema v0.0.0-20240828080221-d35f69426754
	github.com/hashicorp/terraform-provider-azurerm v3.166.0
)

### Important Factoids

Using go version 1.22

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
