### ISSUE TITLE
Error: locating Storage Account with data.azurerm_storage_containers

### ISSUE THREAD

**Issue by romankallen** [hashicorp/terraform-provider-azurerm#27247]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform (and AzureRM Provider) Version
1.9.5

### AzureRM Provider version
Problem see on 3.90.0 and 3.104.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_containers

### Terraform Configuration Files

```hcl
data "azurerm_storage_containers" "this" {
  storage_account_id = "/subscriptions/sub_id/resourceGroups/rg_id/providers/Microsoft.Storage/storageAccounts/storageaccountname"
}
```

### Debug Output/Panic Output

```hcl
Error: locating Storage Account "storageaccountname"

  with data.azurerm_storage_containers.storageaccountname_containers,
  on file.tf line 54, in data "azurerm_storage_containers" "storageaccountname_containers":
  54: data "azurerm_storage_containers" "storageaccountname_containers" {

locating Storage Account "storageaccountname"
##[warning]Can't find loc string for key: TerraformPlanFailed
##[error]Error: TerraformPlanFailed 1
Finishing: Terraform : plan

```

### Description / Feedback
Briefly explained:
v3.88.0 wants to recreate the PIM roles even though they have already been created, that is why we want a different version.

v3.104.0 solves the problem and the PIM roles are not recreated.

from v3.9x.0 there is an error with azurerm_storage_containers which we also need in the identity part (and thus the problem is also in v3.104.0)

**Comment by magodo** [comment]
@romankallen Sorry for running into this.. Is this systematically happening? Also I didn't see the exact error message in the issue description.

**Comment by romankallen** [comment]
Hi @magodo 
Today we found out that it has something to do with the subscription change. If we specify the subscription as the provider, it works. I will close the case. Thanks for the answer and help
