### ISSUE TITLE
AzureRM 4.0.1 Breaks All Terraform CLI after Upgrade

### ISSUE THREAD

**Issue by stevenliu-hso** [hashicorp/terraform-provider-azurerm#27262]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

All

### Terraform Configuration Files

```hcl
terraform state show 'azurerm_subnet.cdp_subnet["Melbourne"]'
```

### Debug Output/Panic Output

```shell
Failed to marshal state to json: unsupported attribute "enforce_private_link_endpoint_network_policies"The state file is empty. No resources are represented.
```

### Expected Behaviour

Display the attributes of a single resource in the Terraform state

### Actual Behaviour

Failed to marshal state to json: unsupported attribute "enforce_private_link_endpoint_network_policies"The state file is empty. No resources are represented.

### Steps to Reproduce

CLI
terraform state show 'azurerm_subnet.cdp_subnet["Melbourne"]'

**Comment by lonegunmanb** [comment]
Hi @stevenliu-hso thanks for reporting this issue! I can reproduce this issue on my side. The cause is, after upgrading to `v4`, we still have a state file created by `v3` provider, we need to migrate the state to `v4` first. Would you please try `terraform plan -refresh-only` then try `terraform state show` again? The refresh only plan would refresh and upgrade state's schema.

**Comment by stevenliu-hso** [comment]
Hello
Thanks for your help, I use Terraform Cloud, can I do this in Terraform Cloud, for example New Run -> Refresh State -> Start?

**Comment by lonegunmanb** [comment]
@stevenliu-hso I've checked the [document](https://developer.hashicorp.com/terraform/cloud-docs/run/modes-and-options#refresh-only-mode) and I think this is exactly method what could solve this issue.

**Comment by stevenliu-hso** [comment]
Cool, thanks, it seems to work. I was told previously the refresh is part of the terraform plan, but obviously it is not, I will have to run the refresh explicitly.

**Comment by lonegunmanb** [comment]
@stevenliu-hso Glad to hear that! If this issue has been solved, would you please kindly close this issue for us? Thanks!

**Comment by stevenliu-hso** [comment]
Cool, thanks

**Comment by lonegunmanb** [comment]
> Cool, thanks, it seems to work. I was told previously the refresh is part of the terraform plan, but obviously it is not, I will have to run the refresh explicitly.

@stevenliu-hso Another tip, in general speaking `refresh` is a part of terraform plan, but in your case you ran `terraform state show` command, which won't call refresh first. This is a special case.
