### ISSUE TITLE
Context deadline exceeded when provisioning application insights instance

### ISSUE THREAD

**Issue by JRobertEdwards** [hashicorp/terraform-provider-azurerm#27267]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.3.10

### AzureRM Provider Version

3.106.0

### Affected Resource(s)/Data Source(s)

azurerm_application_insights

### Terraform Configuration Files

```hcl
terraform {
  backend "azurerm" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.10"
    }
  }
}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name      = var.resource_group
  location  = var.location
  tags      = var.resource_tags
}

resource "azurerm_application_insights" "ai" {
  name                = var.application_insights_name
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  workspace_id        = var.log_analytics_funnel
  application_type    = "web"
  tags = var.resource_tags
}
```

### Debug Output/Panic Output

```shell
Error: retrieving Billing Features for Component (Subscription: "<subscription-id>"
    Resource Group Name: "<resource-group-name>"
    Component Name: "<component-name>"): Get "https://management.azure.com/subscriptions/<subscription-id>/resourceGroups/<resource-group-name>/providers/Microsoft.Insights/components/<component-name>/currentbillingfeatures?api-version=2015-05-01": context deadline exceeded

I have obscured the names of the resources FYI
```

### Expected Behaviour

Provisioning of app insights without issue

### Actual Behaviour

Intermittently since the 4.0 release this error has been popping up very frequently, despite no changes to our infrastructure or networking. I can only assume that there might have been a change to the api being used highlighted in the error itself.

### Steps to Reproduce

terraform apply

**Comment by ekowalsk** [comment]
it seems to be related to this ticket https://github.com/hashicorp/terraform-provider-azurerm/issues/27248

**Comment by mybayern1974** [comment]
Thank you @JRobertEdwards for filing this issue. With assuming it's duplicated with #27248 , I'm closing this one with having users subscribe the formerly filed #27248, or please suggest if you assume these two are not duplicated.
