### ISSUE TITLE
Unable to set `network_security_group_rules_required` to `AllRules` for `azurerm_databricks_workspace`

### ISSUE THREAD

**Issue by IEP-Brewin** [hashicorp/terraform-provider-azurerm#27274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_databricks_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "rg-example"
  location = "West Europe"
}

resource "azurerm_databricks_workspace" "example" {
  name                                                = "dbw-example"
  resource_group_name                                 = azurerm_resource_group.example.name
  location                                            = azurerm_resource_group.example.location
  network_security_group_rules_required               = "AllRules"
  public_network_access_enabled                       = false
  sku                                                 = "premium"
}

provider "azurerm" {
  resource_provider_registrations = "none"
  features {}
}
```

### Debug Output/Panic Output

```shell
│ Error: having 'network_security_group_rules_required' set to "AllRules" and 'public_network_access_enabled' set to 'false' is an invalid configuration
│
│   with azurerm_databricks_workspace.example,
│   on main.tf line 6, in resource "azurerm_databricks_workspace" "example":
│    6: resource "azurerm_databricks_workspace" "example" {
```

### Expected Behaviour

According to the azurerm_databricks_workspace" docs, `AllRules` should be allowed when `public_network_access_enabled` is set to `false`.

### Actual Behaviour

Unable to set `network_security_group_rules_required` to "`AllRules`

### Steps to Reproduce

terraform init
terraform plan

**Comment by Chambras** [comment]
Interesting find @IEP-Brewin I will take a look.

**Comment by gerrytan** [comment]
@IEP-Brewin NSG rules cannot be set to 'All Rules' if you disable public network access. Such NSG rule is only relevant if public network access enabled.

While I agree the terraform provider docs is insufficient, this behavior is consistent with workspace creation via portal:

![image](https://github.com/user-attachments/assets/9fbcb844-f249-47db-8b4b-7c9214049ea0)

**Comment by jaywithersbrewin** [comment]
Thanks for advising, @gerrytan. Please close this issue.
