### ISSUE TITLE
WAF Profile request_body_enforcement documentation is against wrong resource

### ISSUE THREAD

**Issue by rlaveycal** [hashicorp/terraform-provider-azurerm#27290]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9

### AzureRM Provider Version

4.0

### Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

The `azurerm_web_application_firewall_policy` resource's `request_body_enforcement` property should be documented.

### Actual Behaviour

The `request_body_enforcement` property documentation was added to the `application_gateway` resource (see PR link)

### References

#27094

**Comment by sinbai** [comment]
Hi @rlaveycal thanks for raising this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/27303)has been submitted to fix this doc issue.
