### ISSUE TITLE
Unable to create ARO cluster using terraform

### ISSUE THREAD

**Issue by priyas16** [hashicorp/terraform-provider-azurerm#27311]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

3.114

### Affected Resource(s)/Data Source(s)

azurerm_redhat_openshift_cluster

### Terraform Configuration Files

```hcl
main.tf:
## ARO Cluster

# See docs at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/redhat_openshift_cluster

resource "azurerm_redhat_openshift_cluster" "cluster" {
  name                        = var.cluster_name
  location                    = var.location
  resource_group_name         = var.resource_group_name
  tags                        = var.tags

  # NOTE: this input is missing to provide parity with the old provider at
  #       https://github.com/rh-mobb/terraform-provider-azureopenshift
  # cluster_resource_group = "${var.cluster_name}-cluster-rg"

  cluster_profile {
    domain      = var.domain
    pull_secret = var.pull_secret
    version     = var.aro_version
  }

  main_profile {
    vm_size   = var.master_vm_size
    subnet_id = var.master_subnet_id
  }

  worker_profile {
    subnet_id    = var.worker_subnet_id
    disk_size_gb = var.worker_disk_size_gb
    node_count   = var.worker_node_count
    vm_size      = var.worker_vm_size
  }

  network_profile {
    outbound_type = var.outbound_type
    pod_cidr      = var.aro_pod_cidr_block
    service_cidr  = var.aro_service_cidr_block
  }

  api_server_profile {
    visibility = var.api_server_profile
  }

  ingress_profile {
    visibility = var.ingress_profile
  }

  service_principal {
    client_id     = var.client_id
    client_secret = var.client_secret
  }

}

output "console_url" {
  value = azurerm_redhat_openshift_cluster.cluster.console_url
}

output "api_url" {
  value = azurerm_redhat_openshift_cluster.cluster.api_server_profile[0].url
}

output "api_server_ip" {
  value = azurerm_redhat_openshift_cluster.cluster.api_server_profile[0].ip_address
}

output "ingress_ip" {
  value = azurerm_redhat_openshift_cluster.cluster.ingress_profile[0].ip_address
}
-------------------
-------------------
provider.tf:
terraform {
    required_providers {
        azuread = {
            source  = "hashicorp/azuread"
            version = "~>2.53"
        }

        azurerm = {
            source  = "hashicorp/azurerm"
            version = "~>3.114"
        }
    }
}

provider "azurerm" {
  features {
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}
```

### Debug Output/Panic Output

```shell
azurerm_redhat_openshift_cluster.cluster: Creating...
╷
│ Error: creating Provider Open Shift Cluster (Subscription: "***"
│ Resource Group Name: "<RESOURCE-GROUP>"
│ Open Shift Cluster Name: "<CLUSTER-NAME>"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidParameter: The provided pull secret is invalid.
│ 
│   with azurerm_redhat_openshift_cluster.cluster,
│   on main.tf line 5, in resource "azurerm_redhat_openshift_cluster" "cluster":
│    5: resource "azurerm_redhat_openshift_cluster" "cluster" {
│ 
│ creating Provider Open Shift Cluster (Subscription:
│ "***"
│ Resource Group Name: "<RESOURCE-GROUP>"
│ Open Shift Cluster Name: "<CLUSTER-NAME>"): performing CreateOrUpdate:
│ unexpected status 400 (400 Bad Request) with error: InvalidParameter: The
│ provided pull secret is invalid.
╵
Error: Process completed with exit code 1.
```

### Expected Behaviour

ARO cluster should be created.

### Actual Behaviour

While trying to create ARO cluster using terraform its failing with invalid pull secret error mentioned above. But we are able to create the cluster manually with the same pull secret using Azure CLI and also tried to decode the pull secret provided in GitHub secret, that is also correct. Hence we would need your help in resolving this issue. Please let us know if you need any details. Thanks!

**Comment by teowa** [comment]
Hi @priyas16 , thanks for submitting this issue!
The error message `unexpected status 400 (400 Bad Request) with error: InvalidParameter: The provided pull secret is invalid.` Could you try to print the debug log to see if the pull secret sent to the API is correct? The [debug log](https://developer.hashicorp.com/terraform/internals/debugging) can be printed by adding environment variables, e.g., `TF_LOG=debug TF_LOG_PATH=aro.log`, and you can search the pull secret by `pullSecret` keyword.

**Comment by danieldbr** [comment]
Hi @priyas16 ,

Would you please try:

``` terraform
# variables.tf
variable "pull_secret" {
  description = "The pull secret for the ARO cluster"
  type        = string
  sensitive   = true
}
```

``` terraform
# terraform.tfvars
pull_secret = jsondecode(file("pull-secret.txt"))
```

### Explanation
Azure CLI opens the file at the parameter `--pull-secret` with [def validate_pull_secret(namespace):](https://github.com/Azure/azure-cli/blob/f5e95992fdce5e9b6ee6714f9f88ad60e44c9674/src/azure-cli/azure/cli/command_modules/aro/_validators.py#L100)

But Terraform takes the value of the argument `pull_secret` as a string and does not open the file at the path. Ref: https://github.com/hashicorp/terraform-provider-azurerm/blob/b0dd4f834a7cd8030acee5d2da774c53892f6905/internal/services/redhatopenshift/redhat_openshift_cluster_resource.go#L52

**Comment by priyas16** [comment]
Hi @teowa/@danieldbr,

Thanks for your response. The issue is resolved after passing the value in string format by escaping it with \ which is then stored in github repository secret. Thanks!
