### ISSUE TITLE
Error: reading static website for AzureRM Storage Account

### ISSUE THREAD

**Issue by Tbohunek** [hashicorp/terraform-provider-azurerm#27310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.2

### AzureRM Provider Version

3.116.0 / 4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "friday" {
  name                            = "friday25a"
  resource_group_name             = "friday"
  location                        = "westeurope"
  account_tier                    = "Standard"
  account_replication_type        = "LRS"
  allow_nested_items_to_be_public = false
}
```

### Debug Output/Panic Output

```shell
Error: retrieving static website properties for Storage Account (Subscription: "sss" Resource Group Name: "friday" Storage Account Name: "friday25a"): executing request: Get "https://friday25a.blob.core.windows.net/?comp=properties&restype=service": context deadline exceeded
```

### Expected Behaviour

I understand the challenge - I have seen the other closed issues.
What would help is a `bool` flag that will instruct the provider to **not** refresh the Static Website properties because I don't want it to. I can remove this flag after I deploy the PE, but I cannot deploy the PE if the prerequisite - SA creation - blocks its creation.

### Actual Behaviour

Terraform is properly trying to honor DSC in this case, but causes an impossible scenario in regulated environment. A deadlock.

### Important Factoids

The Storage Account doesn't have Private Endpoint yet.
It will work just fine after it has a Private Endpoint...
... but I cannot create the Private Endpoint, because the Storage Account itself will not finish creating.
![image](https://github.com/user-attachments/assets/d5838bdb-dbbe-4f34-88e2-ef410d531613)
My TFE doesn't and will not have connectivity to internet.

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/24982
https://github.com/hashicorp/terraform-provider-azurerm/issues/20257

**Comment by Tbohunek** [comment]
Alternatively the required PE deployment option could be embedded into the `azurerm_storage_account` resource for these scenarios? Then the provider would just be retrying to read the website until the PE kicks in, and suceed.

**Comment by Tbohunek** [comment]
Actually, why does terraform even check the website property on **create**? Assuming you didn't have it in the config, it's not there. The next time I care whether it's been added in other means is on next **refresh**, by when the PE would be in place, and all would be fine. :)

**Comment by magodo** [comment]
@Tbohunek Sorry for running into this. In fact, not only the website property will be accessed, the others will also be accessed during creation, e.g. queue, file, etc., as long as the current SA supports them.

The issue you saw here is due to your environment can resolve the blob endpoint domain name, see [this](https://github.com/hashicorp/go-azure-sdk/pull/1072) for an example. I'd like to understand more about the setup of your environment, especially about the DNS configuration and why it failed to resolve the blob domain name.

**Comment by Tbohunek** [comment]
Hey @magodo, happy to help! What do I need to do to reproduce?
My email is in my profile so you can hit me up (on Teams also).

The TFE runner can resolve the DNS name...to the public IP... But then can't connect to it (timeout).
