### ISSUE TITLE
Postgresql Flexible Server Configurations flaky behaviour

### ISSUE THREAD

**Issue by antogaro** [hashicorp/terraform-provider-azurerm#27332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.3

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server_configuration

### Terraform Configuration Files

```hcl
locals {
  server_parameters = {
    "require_secure_transport"            = "ON"
    "connection_throttle.enable"          = "ON"
    "row_security"                        = "ON"
    "pgaudit.log"                         = "ALL"
    "pgaudit.log_catalog"                 = "ON"
    "pgaudit.log_client"                  = "OFF"
    "pgaudit.log_level"                   = "LOG"
    "pgaudit.log_parameter"               = "ON"
    "pgaudit.log_relation"                = "ON"
    "log_autovacuum_min_duration"         = 250
    "metrics.autovacuum_diagnostics"      = "ON"
    "metrics.collector_database_activity" = "ON"
    "track_io_timing"                     = "ON"
    "pgbouncer.enabled"                   = "true"

  }
}

resource "azurerm_postgresql_flexible_server_configuration" "config" {
  for_each = local.server_parameters

  name      = each.key
  value     = each.value
  server_id = azurerm_postgresql_flexible_server.psql.id
}
```

### Debug Output/Panic Output

```shell
│ Error: updating Configuration (Subscription: "(subscription)"
│ Resource Group Name: "(resourcegroup)"
│ Flexible Server Name: "postgresql"
│ Configuration Name: "pgaudit.log_client"): polling after Update: polling failed: the Azure API returned the following error:
│ 
│ Status: "ServerBusy"
│ Code: ""
│ Message: "Server 'postgresql' is busy with another operation. Please try again later."
│ Activity Id: ""
│ 
│ ---
│ 
│ API Response:
│ 
│ ----[start]----
│ {"name":"f341eed8-2a81-4773-aa8a-d1355fe40369","status":"Failed","startTime":"2024-09-10T07:48:25.207Z","error":{"code":"ServerBusy","message":"Server 'postgresql' is busy with another operation. Please try again later."}}
│ -----[end]-----
│
```

### Expected Behaviour

Configurations are correctly added to the postgresql flexible server

### Actual Behaviour

After running terraform apply, sometimes the server returns the error "ServerBusy" this **does not happen everytime**, and the configuration name (in this case pgaudit.log_client) is different whenever the error is returned.

### Steps to Reproduce

1. Set some server configurations for the resource azurerm_postgresql_flexible_server_configuration and run terraform apply
2. If the error isn't returned run terraform destroy
3. repeat steps 1 and 2 until the error is returned

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #27355 created by @neil-yechenwei for this issue.

**Comment by kingnathanal** [comment]
Would this PR get added to the 3.116.x code base? or would we have to upgrade to 4.x to get it

**Comment by fheinonen** [comment]
This same error also happens when adding private endpoints with azurerm_private_endpoint to flexible server. Should I create a separate ticket for this?
