### ISSUE TITLE
azurerm_cosmosdb_account EnableNoSQLVectorSearch feature not available - requesting for it to be added

### ISSUE THREAD

**Issue by pumacln** [hashicorp/terraform-provider-azurerm#27343]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform version 1.9.5  AzureRM Provider Version 4.0.1

* Terraform Core version: [1.9.5]
* AzureRM Provider version: [4.0.1]

### Affected Resource(s)/Data Source(s)

azurerm_cosmosdb_account

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

resource "azurerm_cosmosdb_account" "example" {
  name                = "example"
  location            = "Central US"
  resource_group_name = var.app_resource_group.name # this value comes from the rg resource
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  automatic_failover_enabled = false

  public_network_access_enabled = true

  is_virtual_network_filter_enabled = true

  virtual_network_rule {
    id = azurerm_subnet.example1.id
  }

  virtual_network_rule {
    id = azurerm_subnet.example2.id
  }

  capabilities {
    name = "EnableServerless"
  }

  consistency_policy {
    consistency_level       = "Session"
    max_interval_in_seconds = 5
    max_staleness_prefix    = 100
  }

  geo_location {
    location          = "centralus"
    failover_priority = 0
  }
  
}
```

### Description / Feedback

Cosmos DB Account is created

Currently the possible values for the "capabilities" argument is limited to:
"A capabilities block Configures the capabilities to be enabled for this Cosmos DB account:

    [name](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#name) - (Required) The capability to enable - Possible values are AllowSelfServeUpgradeToMongo36, DisableRateLimitingResponses, EnableAggregationPipeline, EnableCassandra, EnableGremlin, EnableMongo, EnableMongo16MBDocumentSupport, EnableMongoRetryableWrites, EnableMongoRoleBasedAccessControl, EnablePartialUniqueIndex, EnableServerless, EnableTable, EnableTtlOnCustomPath, EnableUniqueCompoundNestedDocs, MongoDBv3.4 and mongoEnableDocLevelTTL."

The resource includes 3 Features that are managed by Azure as a value of "capabilities" like the ones above, yet cannot be implemented via Terraform yet and if any of this features is enabled via the Azure portal, the Terraform resource asks to be replaced when running an execution plan.

Example Error:
 Error: expected capabilities.0.name to be one of ["EnableAggregationPipeline" "EnableCassandra" "EnableGremlin" "EnableTable" "EnableServerless" "EnableMongo" "EnableMongo16MBDocumentSupport" "MongoDBv3.4" "mongoEnableDocLevelTTL" "DisableRateLimitingResponses" "AllowSelfServeUpgradeToMongo36" "EnableMongoRetryableWrites" "EnableMongoRoleBasedAccessControl" "EnableUniqueCompoundNestedDocs" "EnableTtlOnCustomPath" "EnablePartialUniqueIndex"], **got EnableNoSQLVectorSearch**

**Comment by sinbai** [comment]
Hi @pumacln thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/27357) has been submitted to support new capability `EnableNoSQLVectorSearch` for `azurerm_cosmosdb_account `. Could you please track it for more updates?

**Comment by pumacln** [comment]
Hi Elena,

Keeping a close eye on this for it to get approved and test the changes, this will allow me to implement consistent automation across multiple environments.

Thanks.
