### ISSUE TITLE
The total_retention_in_days value isn't being set when using basic tables in azurerm_log_analytics_workspace_table

### ISSUE THREAD

**Issue by richard-sistern** [hashicorp/terraform-provider-azurerm#27358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8.1

### AzureRM Provider Version

4.1.0

### Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace_table

### Terraform Configuration Files

```hcl
law_audit_basic_tables = [
    "AKSAuditAdmin",
    "ApiManagementGatewayLogs",
    "CDBControlPlaneRequests",
    "CDBDataPlaneRequests",
    "StorageBlobLogs",
  ]

resource "azurerm_log_analytics_workspace_table" "basic_table" {
  for_each = toset(local.law_audit_basic_tables)

  workspace_id = azurerm_log_analytics_workspace.loganalytics.id
  name         = each.key

  plan                    = "Basic"
  total_retention_in_days = 180
}
```

### Debug Output/Panic Output

```shell
No warnings/errors during plan/apply
```

### Expected Behaviour

The total retention in days set to 180 for tables in local.law_audit_basic_tables

### Actual Behaviour

A plan/apply completes fine, however the total retention remained at the default 30 days.  After manually updating the values to 180 days in portal, like this:

![image](https://github.com/user-attachments/assets/9c1d12be-3c55-46ef-9502-697ee8c436a0)

A subsequent plan gives the following change for each table:  ~ total_retention_in_days = 0 -> 180.  This happens on every plan.

### Steps to Reproduce

terraform plan/apply

**Comment by ziyeqf** [comment]
Hi @richard-sistern, thanks for reporting.

The current implementation ignored `total_retention_in_days` when `plan` is set to `Basic`. I just submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/27420) to fix it. Once it merged & released it should be fixed. You can subscribe the PR to keep a track.

For any further questions please leave comments.
Thanks!
