### ISSUE TITLE
AKS Node instances have Public IP address - node_public_ip_enabled ignored

### ISSUE THREAD

**Issue by jaydesai-automate** [hashicorp/terraform-provider-azurerm#27364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.1.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                                = "${local.environment}-aks-${local.purpose}-01"
  location                            = local.location
  resource_group_name                 = azurerm_resource_group.rg.name
  dns_prefix                          = "${local.environment}-aks-${local.purpose}-01"
  automatic_upgrade_channel           = "stable" 
  private_cluster_enabled             = true
  private_dns_zone_id                 = azurerm_private_dns_zone.aks_dns.id
  private_cluster_public_fqdn_enabled = false
  azure_policy_enabled                = true
  local_account_disabled              = true
  open_service_mesh_enabled           = false 
  http_application_routing_enabled    = false 


  web_app_routing {
    dns_zone_ids = []
  }
  default_node_pool {
    name                         = "system"
    node_count                   = 1
    vm_size                      = "Standard_D4ds_v5"
    vnet_subnet_id               = azurerm_subnet.snet_aks_nodes.id
    only_critical_addons_enabled = true
    temporary_name_for_rotation  = "temp"
    node_public_ip_enabled       = false

    upgrade_settings {
      max_surge = "10%"
    }
  }

  key_vault_secrets_provider {
    secret_rotation_enabled = true
  }
  storage_profile {
    blob_driver_enabled = true
  } 

  identity {
    type         = "UserAssigned"
    identity_ids = [azurerm_user_assigned_identity.aks_user.id]
  }
  network_profile {
    pod_cidr            = "10.244.0.0/16"
    service_cidr        = "10.0.0.0/16"
    dns_service_ip      = "10.0.0.10"
    network_plugin      = "azure"
    network_plugin_mode = "overlay"
    network_data_plane  = "cilium"
    network_policy      = "cilium" 
  }
}
```

### Debug Output/Panic Output

```shell
The Deployment finishes but it does not apply it to the AKS cluster. 
I did find this https://github.com/hashicorp/terraform-provider-azurerm/issues/27201
But the fix addresses the encryption and not the node_public_ip
```

### Expected Behaviour

With this setting, the expected result should be that the Nodes deployed in the Managed Resource Group, don't have Public IP Addresses attached to their instance node.

node_public_ip_enabled       = false

### Actual Behaviour

However, when you view the instance node running in the Virtual machine scale set, both the VMSS and the VM Instance have a public IP address associated with the resource. 

### Steps to Reproduce

Deploy resources and go to Managed Resource Group to view the setting. 

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/27201

**Comment by jaydesai23** [comment]
I noticed that this was not caused by the following, as it adds an external facing load balancer, which also assigns a public IP. It is not due to node_public_ip_enabled = false

web_app_routing {
    dns_zone_ids = []
  }

This can be mark as resolved.

**Comment by jaydesai-automate** [comment]
See above
