### ISSUE TITLE
azurerm_network_watcher_flow_log tags aren't updated

### ISSUE THREAD

**Issue by neonwhiskers** [hashicorp/terraform-provider-azurerm#27385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.0

### AzureRM Provider Version

4.0.1

### Affected Resource(s)/Data Source(s)

azurerm_network_watcher_flow_log

### Terraform Configuration Files

```hcl
resource "azurerm_network_watcher_flow_log" "this" {
  ...
  tags = {
    "cdt-service-level-class" = "missing"
  }
}
```

### Debug Output/Panic Output

```shell
# module.resource_group.module.network_spoke[0].azurerm_network_watcher_flow_log.this will be updated in-place
  ~ resource "azurerm_network_watcher_flow_log" "this" {
        id                        = "/subscriptions/f0...-...-...-...-.../resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_westeurope/flowLogs/nsg-prod"
        name                      = "nsg-prod"
      ~ tags                      = {
          ...
          ~ "cdt-service-level-class" = "undef" -> "missing"
        }
        # (7 unchanged attributes hidden)

        # (2 unchanged blocks hidden)
    }
```

### Expected Behaviour

When applying a Terraform plan to update the azurerm_network_watcher_flow_log resource, any changes to the tags block (such as modifying the value of an existing tag) should be applied in-place. 

### Actual Behaviour

The current behavior is that tag updates are not being applied during in-place updates, even though Terraform detects the changes and lists them in the plan. 

### Steps to Reproduce

1. create a configuration based on [this](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_watcher_flow_log) example 
2. add tags to the just created resource
3. terraform apply
4. change tag value
5. terraform apply
6. terraform plan again to see that this change is planned again

**Comment by originalag** [comment]
I ran into this exact issue on the latest version of 3.x (3.116.0) and tested several versions of azurerm to pinpoint when it was introduced, which I found to be 3.103.0:

3.116.0: Broken
3.103.0: Broken
3.102.0: Works

**Comment by fgarcia-cnb** [comment]
please fix in v3 for those who arent ready for v4
