### ISSUE TITLE
azurerm_virtual_network_gateway_connection expects a shared_key even when it is not needed

### ISSUE THREAD

**Issue by MasterBroda** [hashicorp/terraform-provider-azurerm#27400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

4.2.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway_connection

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway_connection" "connection" {
  name                       = "cxn-xyz"
  location                   = var.location
  resource_group_name        = var.resource_group_name
  type                       = "ExpressRoute"
  express_route_circuit_id   = express_route_circuit_id
  virtual_network_gateway_id = vng_id
  routing_weight             = 100
  shared_key                 = "SHARED_KEY"
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Connection (Subscription: "[MASKED]"
│ Resource Group Name: "RG-xyz"
│ Connection Name: "cxn-xyz"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: CannotSetSharedKeyForExpressRouteConnectionType: Shared Key cannot be set for Connection /subscriptions/[MASKED]/resourceGroups/RG-xyz/providers/Microsoft.Network/connections/cxn-xyz of type ExpressRoute.
```

### Expected Behaviour

The shared_key must be set as optional as it was in v3 of the provider so that the gateway connections for express routes can be successfully created. 

### Actual Behaviour

The provider sets the shared_key as required which completely blocks the creation of the gateway connection.

### Steps to Reproduce

1. create an express route.
2. create a virtual network gateway.
3. create a connection for the gateway using the tf snipped given above.

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems this property has been marked as required property. See more details from this [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/26251/files#diff-5fd83673add7a734c21116bb4de8a766a13b3cfce9556cd1262dc721fbc4ebdb).

**Comment by MasterBroda** [comment]
@stephybun's PR doesn't really explain the reasoning behind marking `shared_key` as required. The terraform plan will always succeed but the actual apply will fail as mentioned in the issue description.

**Comment by DesideriusE** [comment]
So, release 4.0.3 is out, but, reading the documentation this issue has not been addressed. Is it on the backlog for the next release?

**Comment by rcskosir** [comment]
:wave: Great catch! Thanks for reaching out and reporting this bug, unfortunately I do not have an ETA on when this will be reverted. However, any future work via the team or the community will end up linked here via a PR.

**Comment by cmgksims** [comment]
when do they plan on getting this fixed. Blocks existing deployments because it expects the key to be there even if its not needed.
