### ISSUE TITLE
Support for Azure Kubernetes Service (AKS) Automatic cluster

### ISSUE THREAD

**Issue by cpareek** [hashicorp/terraform-provider-azurerm#27446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Could we able to deploy Azure Kubernetes **Automatic** cluster using terraform?  its in preview at the moment on Azure but its already possible to deploy using AZ cli as well as Bicep.

Please see below bicep example..

```
@description('The name of the managed cluster resource.')
param clusterName string = 'myAKSAutomaticCluster'

@description('The location of the managed cluster resource.')
param location string = resourceGroup().location

resource aks 'Microsoft.ContainerService/managedClusters@2024-03-02-preview' = {
  name: clusterName
  location: location  
  sku: {
		name: 'Automatic'
  		tier: 'Standard'
  }
  properties: {
    agentPoolProfiles: [
      {
        name: 'systempool'
        count: 3
        vmSize: 'Standard_DS4_v2'
        osType: 'Linux'
        mode: 'System'
      }
    ]
  }
  identity: {
    type: 'SystemAssigned'
  }
}
```

**Link to documentation**
https://learn.microsoft.com/en-gb/azure/aks/intro-aks-automatic 

### New or Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

 sku_tier = 'Standard'
 automatic_cluster = true # (Optional) If true resource will use 'Microsoft.ContainerService/managedClusters@2024-03-02-preview' api and deploy AKS automatic cluster. Defaults to false.

}
```

### References

https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-automatic-deploy?pivots=bicep#review-the-bicep-file

**Comment by ms-henglu** [comment]
Hi @cpareek ,

Thank you for taking time to report this issue.

Unfortunately this feature is still in preview and it couldn't be supported by the azurerm provider. Please use the `azapi` provider for the preview features.

```hcl

resource "azapi_resource" "resourceGroup" {
  type     = "Microsoft.Resources/resourceGroups@2021-04-01"
  name     = "acctesthenglu923"
  location = "eastus"
  body     = {} # Resource group does not require additional properties in the body
}

resource "azapi_resource" "managedCluster" {
  type      = "Microsoft.ContainerService/managedClusters@2024-03-02-preview"
  parent_id = azapi_resource.resourceGroup.id
  name      = "acctesthenglu923"
  location  = "eastus"

  identity {
    type = "SystemAssigned"
  }

  body = {
    properties = {
      kubernetesVersion = "1.30.3"
      dnsPrefix         = "acctesthenglu923"
      agentPoolProfiles = [
        {
          name   = "agentpool"
          count  = 3
          vmSize = "Standard_DS4_v2"
          osType = "Linux"
          mode   = "System"
        }
      ]
    }
    sku = {
      name = "Automatic"
      tier = "Standard"
    }
  }
}

```

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to label this issue as such and close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.

**Comment by rcskosir** [comment]
Reopening, as it is GA.

**Comment by mstroob** [comment]
After a conversation with the azure AKS service team, we will be doing a minimal implementation of the resource, while the api for automatic cluster stabilizes.
