### ISSUE TITLE
azurerm_ai_services > The provider hashicorp/azurerm does not support resource type "azurerm_ai_services".

### ISSUE THREAD

**Issue by Petopp** [hashicorp/terraform-provider-azurerm#27488]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

Hi everyone,

I’m currently facing an issue with the hashicorp/azurerm Terraform provider. When trying to use the azurerm_ai_services resource, I get the following error:

`The provider hashicorp/azurerm does not support resource type "azurerm_ai_services".`

It seems like this resource is not supported in the current version of the provider. Has anyone else encountered this issue or knows of a workaround? Perhaps there’s an alternative resource or a different approach I could take?

Any help or suggestions would be greatly appreciated!
Thanks in advance!

Best regards,
Peter

### Terraform Version

1.9.6

### AzureRM Provider Version

3.112.0

### Affected Resource(s)/Data Source(s)

azurerm_ai_services

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "3.112.0" # https://learn.microsoft.com/en-us/azure/developer/terraform/provider-version-history-azurerm
    }
  }
}


resource "azurerm_resource_group" "example" {
  name     = "test2-example-resources"
  location = "eastus"
}


resource "azurerm_ai_services" "example" {
  name                = "example-account"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku_name            = "F0"

  tags = {
    Acceptance = "Test"
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Invalid resource type
│
│   on main.tf line 21, in resource "azurerm_ai_services" "example":
│   21: resource "azurerm_ai_services" "example" {
│
│ The provider hashicorp/azurerm does not support resource type "azurerm_ai_services".
```

### Expected Behaviour

Creating a azure AI Search in a resource group

### Actual Behaviour

Error message  

### Steps to Reproduce

1. terraform init
2. terraform paln -out tfout

### References

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/ai_services#argument-reference

**Comment by rcskosir** [comment]
@Petopp Thank you for taking the time to open this issue. `azurerm_ai_services `was added to the provider via #26008, which was released with version 3.116.0. In order to use this resource you will need to upgrade your version to 3.116 or 4.x. If you have future questions, I suggest using the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34).
