### ISSUE TITLE
Storage blob not uploaded on change

### ISSUE THREAD

**Issue by MateMalice** [hashicorp/terraform-provider-azurerm#27498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.6

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_blob

### Terraform Configuration Files

```hcl
# Configure provider
provider "azurerm" {
  features {}

  subscription_id = "xxxxxxxxxx"
}

terraform {
  required_providers {
    azurerm = {
      # User version 4.3.0
      version = "4.3.0"
    }
  }
}

# Create a storage account
resource "azurerm_storage_account" "test-storage" {
  name                     = "tfbugtest430"
  resource_group_name      = "rg-digid-authservice"
  account_replication_type = "LRS"
  account_tier             = "Standard"
  location                 = "australiaeast"
}

# Add a blob container
resource "azurerm_storage_container" "test-container" {
  name                  = "bugtest-container"
  storage_account_name  = azurerm_storage_account.test-storage.name
  container_access_type = "private"
}

# Add a blob
resource "azurerm_storage_blob" "deployed_files_branding_primary" {
  name                   = "bugtest-blob.html"
  storage_account_name   = azurerm_storage_account.test-storage.name
  storage_container_name = "bugtest-container"
  type                   = "Block"
  content_type           = "text/html"
  source_content         = file("./test-file.html")
}

# test-file.html contains the following on first run:
#<!DOCTYPE html>
#<html>
#
#<head>
#    <title>Test page</title>
#</head>
#
#<body>
#    <h1>This is a test</h1>
#</body>
#
#</html>

# test-file.html contains the following on second run: 
#<!DOCTYPE html>
#<html>
#
#<head>
#    <title>Test page</title>
#</head>
#
#<body>
#    <h1>This is a test</h1>
#    <h2>This has been added after the first run.</h2>
#</body>
#
#</html>
```

### Debug Output/Panic Output

```shell
See output here: https://raw.githubusercontent.com/MateMalice/tf-bug-reports/refs/heads/main/2024-09-25-storage-blob-upload-failed.txt
```

### Expected Behaviour

The blob should have been updated in the container on the second run - i.e. the new contents of the blob should match the second version of "test-file.html".

### Actual Behaviour

The blob is not being updated. Not only does the debug output not show a PUT or a POST call to update the blob, but the storage account shows no changes. The update timestamp of the blob is the same as the creation timestamp, so no update was made:
![image](https://github.com/user-attachments/assets/8e797ffb-9451-4374-9c5e-ecd0cf5b71d7)

As such, the second line is not showing in the uploaded file, even though the Terraform state contains the update.

### Steps to Reproduce

1. Create configuration as per above.
2. Run terraform apply a first time.
3. Modify the contents of test-file.html
4. Run terraform apply a second time

### References

This problem has surfaced after v4.3.0 - it did not exist in v4.2.0. In version 4.3.0, changes to storage blobs ceased triggering a destroy/recreate operation, but only trigger an update operation. The problem might be related to this change: https://github.com/hashicorp/terraform-provider-azurerm/commit/c197c2e40bf8b7be35616cb6de8b4871b0545b28

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. Please subscribe to PR #27508 for the fix.
