### ISSUE TITLE
azurerm_linux_virtual_machine - license_type support for UBUNTU_PRO

### ISSUE THREAD

**Issue by jasonrepos** [hashicorp/terraform-provider-azurerm#27520]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

It would be good to have support for the UBUNTU_PRO license within azurerm_linux_virtual_machine license_type
 
│ Error: expected license_type to be one of ["RHEL_BYOS" "SLES_BYOS"], got UBUNTU_PRO
│
│   with azurerm_linux_virtual_machine.<vm name>,
│   on terraform.tf line 3987, in resource "azurerm_linux_virtual_machine" "<vm name>":
│ 3987:   license_type = "UBUNTU_PRO"

### New or Affected Resource(s)/Data Source(s)

azurerm_linux_virtual_machine

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_virtual_machine" "xxx" {
  name                       = "xxx"
  location                   = azurerm_resource_group.yyy.location
  resource_group_name        = azurerm_resource_group.yyy.name
  license_type = "UBUNTU_PRO"
```

**Comment by harshavmb** [comment]
Hi @jasonrepos ,

Could you please share links to documentation where it says `UBUNTU_PRO` is supported? [Here](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/azure-hybrid-benefit-linux?tabs=ahbNewPortal%2CahbExistingPortal%2Clicenseazcli%2CrhelAzcliByosConv%2Crhelazclipaygconv%2Crhelpaygconversion%2Crhelcompliance) I see only `SLES` & `RHEL`  appear to be supported.

**Comment by jasonrepos** [comment]
Hi @harshavmb 

Here is the Azure doc on Ubuntu Pro - https://learn.microsoft.com/en-us/azure/virtual-machines/workloads/canonical/ubuntu-pro-in-place-upgrade

In my case I have manually upgraded our Ubuntu VMs using the following command

az vm update -g myResourceGroup -n myVmName --license-type UBUNTU_PRO

Following this, I am now having to set a lifecycle ignore so terraform does not revert the change.

lifecycle {
    ignore_changes = [
      license_type
    ]

**Comment by jasonrepos** [comment]
source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts-gen2"
    version   = "latest"
  }
