### ISSUE TITLE
api_server_access_profile vnet_integration_enabled and subnet_id fields disappeared in kubernetes_cluster 

### ISSUE THREAD

**Issue by Mikel-Landa** [hashicorp/terraform-provider-azurerm#27525]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.7

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Expected Behaviour

There is currently no way to enable API Server VNet Integration (https://learn.microsoft.com/en-us/azure/aks/api-server-vnet-integration) in terraform for AKS. Until 3.116.0, this was possible.

With the removal of vnet_integration_enabled and subnet_id field in the api_server_access_profile block, this seems no longer possible.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is in Preview by the underlying [AKS API](https://github.com/Azure/AKS) so I am going to label this issue as such and close it for now, please read [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#aks-migration-to-stable-api) about the AKS API change in 4.x. Once the feature has become generally available and is accessible in a Stable API version, we can reopen this request or you can create a new one.
