### ISSUE TITLE
MSAL token (timing?) issue in `azurerm_storage_account`

### ISSUE THREAD

**Issue by robbert-nlo** [hashicorp/terraform-provider-azurerm#27573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.7

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_storage_account

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "rg-test-asdf"
  location = "West Europe"
}

resource "azurerm_storage_account" "this" {
  for_each = toset([ for i in range(1,40): tostring(i) ])

  name                             = format("stasdgalsdjhca%s", each.key)
  resource_group_name              = azurerm_resource_group.this.name
  location                         = "West Europe"
  account_tier                     = "Standard"
  account_replication_type         = "GRS"
  allow_nested_items_to_be_public  = false

  lifecycle { ignore_changes = [tags] }
}
```

### Debug Output/Panic Output

```shell
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: retrieving static website properties for Storage Account (Subscription: "12345678-7bba-463c-8fce-8c89f0e3d394"
│ Resource Group Name: "rg-test-asdf"
│ Storage Account Name: "stasdgalsdjhca38"): executing request: authorizing request: running Azure CLI: exit status 1: ERROR: User 'REDACTED' does not exist in MSAL token cache. Run `az login`.
│ 
│   with azurerm_storage_account.this["38"],
│   on st.tf line 6, in resource "azurerm_storage_account" "this":
│    6: resource "azurerm_storage_account" "this" {
│ 
╵
╷
│ Error: retrieving static website properties for Storage Account (Subscription: "12345678-7bba-463c-8fce-8c89f0e3d394"
│ Resource Group Name: "rg-test-asdf"
│ Storage Account Name: "stasdgalsdjhca26"): executing request: authorizing request: running Azure CLI: exit status 1: ERROR: User 'REDACTED' does not exist in MSAL token cache. Run `az login`.
│ 
│   with azurerm_storage_account.this["26"],
│   on st.tf line 6, in resource "azurerm_storage_account" "this":
│    6: resource "azurerm_storage_account" "this" {
│ 
╵
╷
│ Error: retrieving queue properties for Storage Account (Subscription: "12345678-7bba-463c-8fce-8c89f0e3d394"
│ Resource Group Name: "rg-test-asdf"
│ Storage Account Name: "stasdgalsdjhca5"): executing request: authorizing request: running Azure CLI: exit status 1: ERROR: User 'REDACTED' does not exist in MSAL token cache. Run `az login`.
│ 
│   with azurerm_storage_account.this["5"],
│   on st.tf line 6, in resource "azurerm_storage_account" "this":
│    6: resource "azurerm_storage_account" "this" {
```

### Expected Behaviour

Terraform plan and apply should succeed in one shot.

### Actual Behaviour

Please note: This is a transient error which only surfaces on *part* of the resources, and it goes away after retrying.
It looks like a timing issue in getting the MSAL token for the storage account, storing it in the cache, and then using it. Possibly `az account get-access-token` (which the provider calls under the hood) i not reliable when it is called multiple times in parallel.

Part of the storage accounts are read correctly, without issue. But for another *part* of the storage accounts, `terraform plan` will fail to get the MSAL token from the cache, and it will throw the above error.

Note that the token for the storage accounts which errored, are actually present in the token cache file at this point!

When you run `terraform plan` again immediately after, there are less of these errors. If you repeat `terraform plan` long enough, the plan will succeed.

### Steps to Reproduce

(not sure if this matters) Run this locally on macOS Sonoma 14.7:

1. `terraform apply` the supplied example code (you may already find that the error will show in this fase, if not: continue)
2. clear MSAL token cache: `rm ~/.azure/msal_token_cache.*`
3. `az login`
4. `terraform plan`

### Important Factoids

- azure-cli version 2.64.0
- This issue is not present when running a plan with `-parallelism=1`

**Comment by magodo** [comment]
At the first glance, this is either an issue at the Azure CLI side, or an issue at the Terraform SDK side (it also caches the token):

https://github.com/hashicorp/go-azure-sdk/blob/4d383f2a389cf5073e8b5d0469f535e181b1a51c/sdk/auth/cached_authorizer.go#L29-L45

```
func (c *CachedAuthorizer) Token(ctx context.Context, req *http.Request) (*oauth2.Token, error) {
	c.mutex.RLock()
	dueForRenewal := tokenDueForRenewal(c.token)
	c.mutex.RUnlock()

	if dueForRenewal {
		c.mutex.Lock()
		defer c.mutex.Unlock()
		var err error
		c.token, err = c.Source.Token(ctx, req)
		if err != nil {
			return nil, err
		}
	}

	return c.token, nil
}
```

@robbert-nlo Is your MacOS an ARM machine?

**Comment by robbert-nlo** [comment]
@magodo Yes this is an ARM machine (M1 Max).

Some more info from a debug log. This stacktrace shows the issue:
```
  | DEBUG: cli.azure.cli.core.azclierror: Traceback (most recent call last):    
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
  |     cmd_result = self.invocation.execute(args)                              
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                              
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 666, in execute
  |     raise ex                                                                
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 733, in _run_jobs_serially
  |     results.append(self._run_job(expanded_arg, cmd_copy))                   
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                    
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 703, in _run_job
  |     result = cmd_copy(params)                                               
  |              ^^^^^^^^^^^^^^^^                                               
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 336, in __call__
  |     return self.handler(*args, **kwargs)                                    
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                    
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
  |     return op(**command_args)                                               
  |            ^^^^^^^^^^^^^^^^^^                                               
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/command_modules/profile/custom.py", line 83, in get_access_token
  |     creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, scopes=scopes,
  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/_profile.py", line 414, in get_raw_token
  |     credential = self._create_credential(account, tenant)                   
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                   
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/_profile.py", line 624, in _create_credential
  |     return identity.get_user_credential(username_or_sp_id)                  
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/auth/identity.py", line 245, in get_user_credential
  |     return UserCredential(self.client_id, username, **self._msal_public_app_kwargs)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/opt/homebrew/Cellar/azure-cli/2.64.0/libexec/lib/python3.11/site-packages/azure/cli/core/auth/msal_authentication.py", line 58, in __init__
  |     raise CLIError("User '{}' does not exist in MSAL token cache. Run `az login`.".format(username))
  | knack.util.CLIError: User 'REDACTED' does not exist in MSAL token cache. Run `az login`.
```

In `msal_authentication.py` line 58 it will call a function from the MSAL library for Python get_accounts ([microsoft-authentication-library-for-python/msal/application.py at 95a63a7fe97d91b99979e5bf78e03f6acf40a286 · AzureAD/microsoft-authentication-library-for-python](https://github.com/AzureAD/microsoft-authentication-library-for-python/blob/95a63a7fe97d91b99979e5bf78e03f6acf40a286/msal/application.py#L1194) ), which basically searches for the logged in account from the token cache (e.g. `msal_token_cache.json`). Then an error is triggered that no accounts were returned from the MSAL app. There are no file locks in the MSAL app (only thread locks), but just found that the MSAL extensions library does have a file lock mechanism: [microsoft-authentication-extensions-for-python/msal_extensions/token_cache.py at aa7ab6488b1599df207ff5c317672ca27f193a94 · AzureAD/microsoft-authentication-extensions-for-python](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/aa7ab6488b1599df207ff5c317672ca27f193a94/msal_extensions/token_cache.py#L40) .

However, there doesn’t seem to be a wait on lock when reading from the token_cache file ([microsoft-authentication-extensions-for-python/msal_extensions/token_cache.py at aa7ab6488b1599df207ff5c317672ca27f193a94 · AzureAD/microsoft-authentication-extensions-for-python](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/aa7ab6488b1599df207ff5c317672ca27f193a94/msal_extensions/token_cache.py#L72) ). Loading the file is just a simple read ([microsoft-authentication-extensions-for-python/msal_extensions/persistence.py at ba841e60dc2a8e23a1ce16bb87e8c3a75ee5b9a4 · AzureAD/microsoft-authentication-extensions-for-python](https://github.com/AzureAD/microsoft-authentication-extensions-for-python/blob/ba841e60dc2a8e23a1ce16bb87e8c3a75ee5b9a4/msal_extensions/persistence.py#L156) ).

The conclusion is the same though, it look like az-cli is not capable to run in parallel when the token cache is modified. Possibly process #1 fopen("w+")'s the file, and process #2 at the exact same moment reads from the empty file. And then the token cache file is written to by process #1. Modifications work across multiple processes, because of the locking mechanism, but that doesn’t seem to be the case for reading from the token cache file.

**Comment by magodo** [comment]
Hi @robbert-nlo, thank you for the additional information and analysis!

At the Terraform provider side, as I have demonstrated, it has a process lock, which restricts there is only one `az account get-access-token` being invoked at one time. Especially, the initial invocation is expected to return the token, which will be cached in memory at the provider side, until it expires.

Based on your analysis, are you running multiple terraform instances for the same scope (i.e. the same storage account endpoint) in your environment?

**Comment by robbert-nlo** [comment]
@magodo Hmm, no we're not doing that. This is reproducible with just one terraform instance.

**Comment by magodo** [comment]
@robbert-nlo OK, the storage data plane clients maintain their own authorizers, this means it is possible that multiple authorizers are using the Azure CLI in parallel (each has its own lock). This then leaves to the Azure CLI to support parallel access to the caches.

It now sounds like an issue to the Azure CLI, would you mind to open an issue at https://github.com/azure/azure-cli and back reference this one?

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue, thank you also for opening the upstream issue on the Azure CLI, since a fix will need to happen upstream and not in this repo, I am going to mark this issue as closed for now.
