### ISSUE TITLE
Service bus namespace zone redundant attribute - deprecated but not setting in Premium Sku

### ISSUE THREAD

**Issue by crisqouk** [hashicorp/terraform-provider-azurerm#27574]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.7

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_servicebus_namespace

### Terraform Configuration Files

```hcl
resource "azurerm_servicebus_namespace" "servicebusimstest01" {
  name                          = "servicebusimstest01"
  location                      = "uksouth"
  resource_group_name           = "RG1"
  sku                           = "Premium"
  capacity                      = 1
  premium_messaging_partitions  = 1
}
```

### Debug Output/Panic Output

```shell
azurerm_servicebus_namespace.servicebusimstest01: Creation complete after 1m25s
```

### Expected Behaviour

The 'zone_redundant' property for the sku = "Premium" to be created/shown as "zoneRedundant": true

### Actual Behaviour

The 'zone_redundant' property for the sku = "Premium" created/shows as "zoneRedundant": false. There is no way to set this and it is an immutable setting.

The 'zone_redundant' property was deprecated after v 3.116.0, expected any new azurerm_servicebus_namespace resources with sku = "Premium" to be created as zone redundant which is default now for this sku. The JSON properties of the resource show "zoneRedundant": false . If this is created in the portal then this shows as "zoneRedundant": true

### Steps to Reproduce

Create azurerm_servicebus_namespace in  v 4.1.0 or later

### Important Factoids

Any existing resources are unaffected when updating the the azurerm version and removing the 
**zone_redundant = true** parameter from the terraform as per the latest version requirements

**Comment by rcskosir** [comment]
Thank you for taking the time to open this issue. I am linking here 2 related issues also dealing with this `zone_redundant` change. #27510 and #27497

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Per the [description](https://github.com/hashicorp/terraform-provider-azurerm/pull/26611) for deprecating `zone_redundant`, it mentioned that `zone_redundant` field is now going to be 100% controlled by the API per the service team, which means that `zone_redundant` will be automatically set/controlled by service API or the availability of availability zone feature in each region. So it's service API limitation.

**Comment by dkuzmenok** [comment]
@neil-yechenwei @rcskosir Is that picked by anyone already?

**Comment by WodansSon** [comment]
Please see issue #27239 for more information, I will now close this issue as duplicate for 27239.
