### ISSUE TITLE
Support for Azure Redis Enterprise Api Version

### ISSUE THREAD

**Issue by ajtiwari07** [hashicorp/terraform-provider-azurerm#27592]
### Is there an existing issue for this?

- [X] I have searched the existing issues

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

Here's a link to the swagger spec: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/redisenterprise/resource-manager/Microsoft.Cache/stable/2023-11-01/redisenterprise.json

### Description

Azure Redis Enterprise api v2023-11-01 is generally available across all management clients such as Powershell, Az CLI, .Net etc. This issue is to support the same api version in terraform.

### New or Affected Resource(s)/Data Source(s)

Azure Cache for Redis Enterprise

### Potential Terraform Configuration

```hcl
Introduced new Scaling Statuses such as "Scaling" and "ScalingFailed" to represent scaling of redis enterprise cache.
```

**Comment by ajtiwari07** [comment]
[Onboard Terraform - all_passed_report.md](https://github.com/user-attachments/files/17297251/Onboard.Terraform.-.all_passed_report.md)

**Comment by xuzhang3** [comment]
The API will be upgrade to [2024-06-01-preview](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/redisenterprise/2024-06-01-preview) and I have a PR working on it.
