### ISSUE TITLE
Support for Microsoft_BotManagerRuleSet version 1.1 `in azurerm_web_application_firewall_policy`

### ISSUE THREAD

**Issue by akorp** [hashicorp/terraform-provider-azurerm#27643]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Please add support for `Microsoft_BotManagerRuleSet` version `1.1` for `azurerm_web_application_firewall_policy` which is in general availability now https://techcommunity.microsoft.com/t5/azure-network-security-blog/general-availability-of-azure-waf-bot-manager1-1-ruleset/ba-p/4165296

### New or Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

**Comment by akorp** [comment]
Too early :) Looks like the new `Microsoft_BotManagerRuleSet version 1.11` has been added only for _"Azure WAF integrated with Azure Front Door"_, and is not yet available for the `azurerm_web_application_firewall_policy`.

**Comment by audunsolemdal** [comment]
GA now for regional WAF https://azure.microsoft.com/en-us/updates/v2/General-availability-Bot-Manager-Ruleset-1-1-on-Azure-WAF-with-Azure-Application-Gateway
