### ISSUE TITLE
Documentation AzureRM function parse_resource_id appears to have wrong signature

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#27666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

4.9.7

### AzureRM Provider Version

4.5.0

### Affected Resource(s)/Data Source(s)

parse_resource_id

### Terraform Configuration Files

```hcl
n/a
```

### Debug Output/Panic Output

```shell
n/a
```

### References

<img width="1077" alt="image" src="https://github.com/user-attachments/assets/3bd3523b-0110-4320-a9ff-a66aea08dd0e">

**Comment by Chambras** [comment]
good catch @DevopsMercenary
