### ISSUE TITLE
falied to create azurerm_security_center_auto_provisioning 

### ISSUE THREAD

**Issue by christian1607** [hashicorp/terraform-provider-azurerm#27670]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

3.97.1

### Affected Resource(s)/Data Source(s)

azurerm_security_center_auto_provisioning

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_auto_provisioning" "example" {
  auto_provision = "On"
}
```

### Debug Output/Panic Output

```shell
│ Error: updating auto-provisioning setting for Auto Provisioning Setting: (Name "default"): security.AutoProvisioningSettingsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Deprecated" Message="Log Analytics auto provisioning is deprecated and can no longer be enabled."
2460│
2461│   with module.sece.azurerm_security_center_auto_provisioning.seccen,
2462│   on sece/main.tf line 10, in resource "azurerm_security_center_auto_provisioning" "seccen":
2463│   10: resource "azurerm_security_center_auto_provisioning" "seccen" {
2464│
2465╵
2466Error: Terraform exited with code 1.
2467Error: Process completed with exit code 1.
```

### Expected Behaviour

the resource should be created without any error

### Actual Behaviour

Can't create the resource because I think internally the provider tries to enable log analytics agent autoprovisioning which  will be deprecated by November 2024 [info](https://learn.microsoft.com/en-us/azure/defender-for-cloud/prepare-deprecation-log-analytics-mma-agent)

### Steps to Reproduce

1. user azurerm version 3.97.1
2. terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. TF doesn't enable Log Analytics auto provisioning in the request payload. Seems there is some issue on service API side. Suggest file Azure Support Ticket.

**Comment by irfanj01** [comment]
This is likely due to the retirement of LogAnalytics. More information can be found [here](https://learn.microsoft.com/en-us/azure/defender-for-cloud/prepare-deprecation-log-analytics-mma-agent#log-analytics-agent-autoprovisioning-experience---deprecation-plan).

Namely, this with regards to new subscriptions:

> On newly created subscriptions auto provisioning can no longer be enabled and is automatically turned off.

Best,

**Comment by ziyeqf** [comment]
Hi @christian1607, thanks for reporting.

I submitted a PR (https://github.com/hashicorp/terraform-provider-azurerm/pull/28030) to deprecate the resource and noticed this issue. The capability is being deprecated per [the document](https://learn.microsoft.com/en-us/azure/defender-for-iot/device-builders/quickstart-onboard-iot-hub#set-up-resource-providers-and-access-control).
