### ISSUE TITLE
Commenting private_dns_zone_id in azurerm_postgresql_flexible_server has not effect.

### ISSUE THREAD

**Issue by goors** [hashicorp/terraform-provider-azurerm#27671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

v1.8.2

### AzureRM Provider Version

3.106.1

### Affected Resource(s)/Data Source(s)

azurerm_postgresql_flexible_server

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_flexible_server" "default" {
  name                          = "${var.environment}-${var.name}-postgres-server"
  resource_group_name           = var.resource_group_name
  location                      = var.resource_group_location
  version                       = "16"
  delegated_subnet_id           = var.delegated_subnet_id
  #private_dns_zone_id           = var.private_dns_zone_id
  administrator_login           = var.admin_username
  administrator_password        = var.admin_password
  zone                          = "2"
  storage_mb                    = var.storage_mb
  sku_name                      = var.sku_name
  backup_retention_days         = 7
  public_network_access_enabled = false
  #depends_on                    = [var.private_dns_zone_id]
}
```

### Debug Output/Panic Output

```shell
No changes. Your infrastructure matches the configuration.
```

### Expected Behaviour

Somehow that private dns should be gone.

### Actual Behaviour

It is not gone. Thing is, we used that private dns resolver. But it is expensive as hell, so I decided just to jam in bind and tell azure network to use one more dns server and remove that private_dns_zone_id. It seams that can not be done, not only in terraform but in azure at all. I can not find any doc, saying it can or it can not.

So can someone answer? Deleting zone is out of the question of course since that will delete anything that is associated with postgres server.

### Steps to Reproduce

terraform plan

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. private_dns_zone_id needs to be set with delegated_subnet_id, which means that delegated_subnet_id also needs to be removed when private_dns_zone_id is removed. Additionally, re-creating this resource will be triggered when they're removed.

**Comment by goors** [comment]
Thank you for a clear answer.
