### ISSUE TITLE
Terraform Refresh State of Groups returns could not check for existing group(s)

### ISSUE THREAD

**Issue by DevopsMercenary** [hashicorp/terraform-provider-azurerm#27705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.6.0

### Affected Resource(s)/Data Source(s)

azuread_group

### Terraform Configuration Files

```hcl
resource "azuread_group" "aad-role" {

  for_each = toset( ["admin", "analyst", "delivery", "developer", "etl", "read-only", "solutions", "security-reader"] )

  display_name = format("%s-%s-%s", var.cm-region, "databricks", each.value)

  security_enabled        = "true"
  prevent_duplicate_names = true

}
```
```


### Debug Output/Panic Output

```shell
https://gist.github.com/DevopsMercenary/b93ff28402ea15ad1030ec59e0721e66
```

### Expected Behaviour

Updated the names of my groups

### Actual Behaviour

```
│ Error: could not check for existing group(s): unable to list Groups with filter "displayName eq 'read-only'": the context used must have a deadline attached for polling purposes, but got no deadline
│
│   with azuread_group.aad-role["read-only"],
│   on rbac.tf line 20, in resource "azuread_group" "aad-role":
│   20: resource "azuread_group" "aad-role" {
│
╵
╷
│ Error: could not check for existing group(s): unable to list Groups with filter "displayName eq 'delivery'": the context used must have a deadline attached for polling purposes, but got no deadline
│
│   with azuread_group.aad-role["delivery"],
│   on rbac.tf line 20, in resource "azuread_group" "aad-role":
│   20: resource "azuread_group" "aad-role" {
│
╵
╷
│ Error: could not check for existing group(s): unable to list Groups with filter "displayName eq 'developer'": the context used must have a deadline attached for polling purposes, but got no deadline
│
│   with azuread_group.aad-role["developer"],
│   on rbac.tf line 20, in resource "azuread_group" "aad-role":
│   20: resource "azuread_group" "aad-role" {
│
╵
```

**Comment by mybayern1974** [comment]
@DevopsMercenary , thank you for filing this issue. May I suggest this issue could be filed to the Terraform Azure AD Provider [repo](https://github.com/hashicorp/terraform-provider-azuread/issues) given the reported `azuread_group` resource belongs to that repo?

**Comment by DevopsMercenary** [comment]
Sorry, my mistake
