### ISSUE TITLE
Support for GraphQL in API Management

### ISSUE THREAD

**Issue by azarboon** [hashicorp/terraform-provider-azurerm#27708]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

API Management supports Graphql [since 2022](https://azure.microsoft.com/zh-tw/updates/general-availability-graphql-passthrough-support-in-azure-api-management/) but even after 2 years, azurerm_api_management_api still doesn't support it.

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management_api

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"
}

resource "azurerm_api_management_api" "example" {
  name                = "example-api"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  revision            = "1"
  display_name        = "Example API"
  path                = "example"
  protocols           = ["graphql"]

  import {
    content_format = "swagger-link-json"
    content_value  = "http://conferenceapi.azurewebsites.net/?format=json"
  }
}
```

### References

https://github.com/hashicorp/terraform-provider-azurerm/issues/14634

**Comment by sinbai** [comment]
Hi @azarboon, thanks for opening this issue. Since the latest version of Azure API's [protocol ](https://github.com/Azure/azure-rest-api-specs/blob/3a168488bc291f47ffa14d0fff10cabc2cf5ea37/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/definitions.json#L942)property does not support `GraphQL`, I assume you want `api_type` to support `GraphQL`, correct? If so, could you please try the following Terraform configuration?

```
resource "azurerm_api_management_api" "test" {
  name                = "acctestapi-%d"
  resource_group_name = azurerm_resource_group.test.name
  api_management_name = azurerm_api_management.test.name
  api_type            = "graphql"
  display_name        = "api1"
  path                = "api1"
  protocols           = ["https"]
  revision            = "1"
}
```

**Comment by azarboon** [comment]
> Hi @azarboon, thanks for opening this issue. Since the latest version of Azure API's [protocol ](https://github.com/Azure/azure-rest-api-specs/blob/3a168488bc291f47ffa14d0fff10cabc2cf5ea37/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2024-05-01/definitions.json#L942)property does not support `graphql`, I assume you want [api_type](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api#api_type) to support `graphql`, correct? If so, could you please try the following Terraform configuration?
> 
> ```
> resource "azurerm_api_management_api" "test" {
>   name                = "acctestapi-%d"
>   resource_group_name = azurerm_resource_group.test.name
>   api_management_name = azurerm_api_management.test.name
>   api_type            = "graphql"
>   display_name        = "api1"
>   path                = "api1"
>   protocols           = ["https"]
>   revision            = "1"
> }
> ```

Seems it's working. Thank you.

**Comment by mybayern1974** [comment]
Closing this issue by assuming the question has been addressed. Feel free to suggest to re-activate this issue if there are further questions.
