### ISSUE TITLE
Microsoft.Attestation resource provider not automatically registered

### ISSUE THREAD

**Issue by LiamLeane** [hashicorp/terraform-provider-azurerm#27727]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.8

### AzureRM Provider Version

4.6.0

### Affected Resource(s)/Data Source(s)

azurerm_attestation_provider

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {
    
  }
}

resource "random_string" "name" {
  length  = 10
  special = false
  numeric = true
  upper   = false
}

resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = random_string.name.result
}

resource "azurerm_attestation_provider" "attest" {
  name                = random_string.name.result
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
}
```

### Debug Output/Panic Output

```shell
│ Error: creating Attestation Providers (Subscription: ""
│ Resource Group Name: ""
│ Attestation Provider Name: ""): unexpected status 409 (409 Conflict) with error: MissingSubscriptionRegistration: The subscription is not registered to use namespace 'Microsoft.Attestation'. See https://aka.ms/rps-not-found for how to register subscriptions
```

### Expected Behaviour

RP should be automatically registered via provider block

### Actual Behaviour

Need one of these

resource "azurerm_resource_provider_registration" "attest" {
  name = "Microsoft.Attestation"
}

**Comment by ms-henglu** [comment]
Hi @LiamLeane ,

Thank you for taking time to report this issue.

The `Microsoft.Attestation` resource provider is not included in the list of auto registered providers, please use the `azurerm_resource_provider_registration` to register this provider.

More details, please see
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/4.0-upgrade-guide#improved-resource-provider-registration

**Comment by LiamLeane** [comment]
Sorry for wasting your time with an error between keyboard and chair issue 🥇
