### ISSUE TITLE
azurerm_public_ip - Support setting domain label scope

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-azurerm#27730]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Would like a new optional paramteer which can set the  "domain name label scope" on public IP address resources to avoid risk related to dangling DNS names.

Supported values are

```
"NoReuse"
"ResourceGroupReuse"
"SubscriptionReuse"
"TenantReuse"
```
This must be set upon creation of the resource

The API has supported setting this since provider version "Microsoft.Network/publicIPAddresses@2022-11-01", the feature is currently in public preview.

### New or Affected Resource(s)/Data Source(s)

azurerm_public_ip

### Potential Terraform Configuration

```hcl
resource "azurerm_public_ip" "example" {
  name                = "acceptanceTestPublicIp1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Static"
  domain_label_scope = "TenantReuse" # The domain name label scope can only be specified at the creation of a public IP address
}
```

### References

https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-addresses?branch=pr-en-us-268827#domain-name-label-scope-preview
https://learn.microsoft.com/en-us/azure/templates/microsoft.network/publicipaddresses?pivots=deployment-language-terraform

**Comment by sinbai** [comment]
Hi @audunsolemdal thanks for opening this issue. [PR ](https://github.com/hashicorp/terraform-provider-azurerm/pull/27748)has been submitted to support `domain_label_name_scope`. Could you please track it for more updates?
