### ISSUE TITLE
Support for `tags` attribute on `azurerm_mssql_managed_database`

### ISSUE THREAD

**Issue by iRoachie** [hashicorp/terraform-provider-azurerm#27809]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

The `azurerm_mssql_managed_database` resource does not support adding tags. 

It's supported via the rest API - https://learn.microsoft.com/en-us/rest/api/sql/managed-databases/create-or-update?view=rest-sql-2021-11-01&tabs=HTTP#request-body

Would like to have this attribute added to the resource to support compliance requirements.

### New or Affected Resource(s)/Data Source(s)

azurerm_mssql_managed_database

### Potential Terraform Configuration

```hcl
variable "tags" {
  type        = map(string)
  default     = {}
}
```

**Comment by Chambras** [comment]
@iRoachie  Thanks for submitting this one. I am surprised it does not support tags. I was looking at the source code and the current version uses API version 2023-08-01-preview. So in theory it shouldn't be a big problem. 
I will try to prepare something for next week.
