### ISSUE TITLE
Basic SKU invalid for azurerm_virtual_network_gateway 

### ISSUE THREAD

**Issue by philwelz** [hashicorp/terraform-provider-azurerm#27838]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.5

### AzureRM Provider Version

4.7.0

### Affected Resource(s)/Data Source(s)

azurerm_virtual_network_gateway

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway" "vng" {
  name                = azurecaf_name.vng.result
  location            = azurerm_resource_group.core.location
  resource_group_name = azurerm_resource_group.core.name
  tags                = local.common_tags

  type         = "Vpn"
  vpn_type = "RouteBased"
  sku           = "Basic"
  ...
}
```

### Debug Output/Panic Output

```shell
Virtual Network Gateway Name: "vgw-vng"): performing CreateOrUpdate: unexpected status 400 (400 Bad Request) with error: InvalidGatewaySkuSpecifiedForGatewayDeploymentType: Virtual network gateway Sku specified is not valid for gateway /subscriptions/8be8c704-a30b-4517-92b1-542991a4d11a/resourceGroups/rg-vng-core/providers/Microsoft.Network/virtualNetworkGateways/vgw-vng with DeploymentType VMScaleSet. The allowed Skus are VpnGw1AZ,VpnGw2AZ,VpnGw3AZ,VpnGw4AZ,VpnGw5AZ,VpnGw1,VpnGw2,VpnGw3,VpnGw4,VpnGw5.
```

### Expected Behaviour

 VPN Gateway with Basic SKU is created.

### Actual Behaviour

400 Bad request that the `Basic SKU` is not valid although the [Basic SKU is not retiring](https://learn.microsoft.com/en-us/azure/vpn-gateway/gateway-sku-consolidation#is-vpn-gateway-basic-sku-retiring) and i can deploy the Virtual Network Gateway with the AzApi Terraform Provider using [latest API ](https://learn.microsoft.com/en-us/azure/templates/microsoft.network/virtualnetworkgateways?pivots=deployment-language-terraform)`Microsoft.Network/virtualNetworkGateways@2024-03-01`.  So this seems to come from the AzureRM provider. 

### Steps to Reproduce

1. run `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. Seems I didn't reproduce this issue with below tf config. I suspect that the service principal you're using has no enough permission while tf apply.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-vnetgw-test01"
  location = "eastus"
}

resource "azurerm_virtual_network" "test" {
  name                = "acctestvn-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "test" {
  name                 = "GatewaySubnet"
  resource_group_name  = azurerm_resource_group.test.name
  virtual_network_name = azurerm_virtual_network.test.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_public_ip" "test" {
  name                = "acctestpip-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  allocation_method   = "Dynamic"
  sku                 = "Basic"
}

resource "azurerm_virtual_network_gateway" "test" {
  name                = "acctestvng-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  type     = "Vpn"
  vpn_type = "RouteBased"
  sku      = "Basic"

  ip_configuration {
    public_ip_address_id = azurerm_public_ip.test.id
    subnet_id            = azurerm_subnet.test.id
  }
}
```

![image](https://github.com/user-attachments/assets/dfa43977-fe37-4330-8142-0c0598c48999)

**Comment by philwelz** [comment]
mmh strange...its working with your code example. maybe it was one of my settings inside the resource but the error seemed bery confusing. thanks for helping here.
