### ISSUE TITLE
resources created using "azurerm_data_factory_linked_service_postgresql" report "The current legacy linked service is to be deprecated. Kindly upgrade this by creating a new PostgreSQL linked service"

### ISSUE THREAD

**Issue by mattduguid** [hashicorp/terraform-provider-azurerm#27869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.8.0

### Affected Resource(s)/Data Source(s)

azurerm_data_factory_linked_service_postgresql

### Terraform Configuration Files

```hcl
N/A - no issue with resource building at the moment, this is about the depreciated warning from the Azure Data Factory portal which has a date of 31/10/2024
```

### Debug Output/Panic Output

```shell
N/A
```

### Expected Behaviour

Expected it to create without deprecation warning in the Azure Data Factory

### Actual Behaviour

Azure portal message -> "The current legacy linked service is to be deprecated. Kindly upgrade this by creating a new PostgreSQL linked service - Learn more"

Clicking on "Learn more" takes us to -> https://learn.microsoft.com/en-gb/azure/data-factory/connector-postgresql?tabs=data-factory

On that page is has this message ->"The new PostgreSQL connector provides improved native PostgreSQL support. If you are using the legacy PostgreSQL connector in your solution, please upgrade your PostgreSQL connector **before October 31, 2024**. Refer to this section for details on the difference between the legacy and latest version."

This link also shows the key differences are mainly data types -> https://learn.microsoft.com/en-gb/azure/data-factory/connector-postgresql?tabs=data-factory#differences-between-postgresql-and-postgresql-legacy

When we visit terraform resource "azurerm_data_factory_linked_service_postgresql" we only see the single resource we dont see one for "legacy" and one for "new".

Given the deprecation date has now passed what is the way forward?

### Steps to Reproduce

N/A

### Important Factoids

We opened following ticket with Microsoft Premier "2411030030000930 - depreciated linked service created with azurerm_data_factory_linked_service_postgresql", they advise that they have removed ability to create legacy postgres linked services from the web UI and terraform can still via the API but now the depreciation date has passed this will be removed soon as well

Legacy =  "type": "PostgreSql",
New =  "type": "PostgreSqlV2",

### References

N/A

**Comment by ms-henglu** [comment]
Hi @mattduguid,

Thank you for taking time to report this issue.

I'd recommend to use [data_factory_linked_custom_service](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_custom_service) which is a generic resource to manage data factory linked service, and it could have better support for dynamic content.

Another solution is using the azapi provider, for example:

```hcl
resource "azapi_resource" "linkedService" {
  type = "Microsoft.DataFactory/factories/linkedservices@2018-06-01"
  parent_id = azurerm_data_factory.test.id
  name = "test1"
  body = {
     properties = {
      type = "PostgreSqlV2"
      typeProperties = {
        authenticationType = "Basic"
        database = "your-database"
        server = "your-server"
        sslMode = 2
        username = "your-username"
        password = {
          type = "SecureString"
          value = "your-password"
        }
      }
     }
  }
  schema_validation_enabled = false
}

```

**Comment by mattduguid** [comment]
@ms-henglu thanks very much for that information I have tested both here are the outcomes,

Tried your option 1 "azurerm_data_factory_linked_custom_service" but had 2 issues with this,
1. it still showed up as "Legacy" in the webUI
2. we tried changing its type = "PostgreSql" to type = "PostgreSqlV2" but this also failed as didn't like that type
```error
Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Failed to encrypt sub-resource payload { ***REMOVED***  } and error is: Invalid type 'LinkedService' is provided in 'linkedServices'. Please correct the type in payload and retry.."
```

Tried your option 2 and this works perfectly, should we be using this moving forward as the default or will the resource be updated to support the type = "PostgreSqlV2" ?

**Comment by ms-henglu** [comment]
Hi @mattduguid ,

For the option 1, I guess the payload might be incorrect, a way to fix it is importing the existing PostgreSqlV2 linked service with generating configuration, more details could be found [here](https://developer.hashicorp.com/terraform/language/import/generating-configuration).

> should we be using this moving forward as the default or will the resource be updated over time to support type = "PostgreSqlV2" ?

I think it's okay to move forward with the azapi_resource. For supporting the PostgreSqlV2 in the azurerm provider, I noticed there're some undocumented fields in the API spec/generated SDKs that will block the implementation.

**Comment by mattduguid** [comment]
awesome thanks for your help @ms-henglu
