### ISSUE TITLE
Support for .NET 9 in app service and functions

### ISSUE THREAD

**Issue by JoshWoodArup** [hashicorp/terraform-provider-azurerm#27879]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

.NET 9 is due to be GA on the 14th of November, and App Service and Functions already have preview support for it, however this is currently not configurable in terraform. In each of the resources, the `dotnet_version` field should support `9.0`

### New or Affected Resource(s)/Data Source(s)

- azurerm_linux_web_app
- azurerm_windows_web_app
- azurerm_linux_function_app
- azurerm_windows_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_linux_web_app" "web_app" {
  site_config {
    application_stack {
      dotnet_version = "9.0"
    }
  }
}
```

### References

[Azure Functions](https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=isolated-process%2Cv4&pivots=programming-language-csharp)
[App Service](https://azure.github.io/AppService/2024/08/19/net-9-preview-6-available-on-app-service.html)
Previous PRs:
#23893
#23638

**Comment by Patrik-Berglund** [comment]
Do you think it's possible to have this included in the next release?
