### ISSUE TITLE
Azurerm version is upgraded from v3.110.0 to latest version v4.8.0 which causing an issue

### ISSUE THREAD

**Issue by sathizhmail** [hashicorp/terraform-provider-azurerm#27907]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.8.0

### Affected Resource(s)/Data Source(s)

"azurerm" 

### Terraform Configuration Files

```hcl
provider "azurerm" {
  alias                      = "b2c_tenant"
  tenant_id                  = data.azurerm_aadb2c_directory.instance.tenant_id
  client_id                  = var.b2c_tenant_sp_client_id
  client_secret              = var.b2c_tenant_sp_secret
  subscription_id            = var.b2c_subscription_id
  skip_provider_registration = true
  features {
  }
}
```

### Debug Output/Panic Output

```shell
##[error]Terraform command 'plan' failed with exit code '1'.
##[error]╷
│ Error: populating Resource Provider cache: listing Resource Providers: loading results: unexpected status 401 (401 Unauthorized) with error: InvalidAuthenticationTokenTenant: The access token is from the wrong issuer 'https://sts.windows.net/aaaaaaa-7e74-4eff-b749-45b1c1862c57/'. It must match the tenant 'https://sts.windows.net/xxxxxxx-fd78-44b6-ad75-xxxxxxx/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/xxxxxxx-fd78-44b6-ad75-xxxxxxx' to get the token. Note, if the subscription is transferred to another tenant there is no impact to the services, but information about new tenant could take time to propagate (up to an hour). If you just transferred your subscription and see this error message, please try back later.
│ 
│   with provider["registry.terraform.io/hashicorp/azurerm"].b2c_tenant,
│   on main.tf line 53, in provider "azurerm":
│   53: provider "azurerm" {
```

### Expected Behaviour

Terraform should use the mentioned Subscription ID from an authenticated.

### Actual Behaviour

When using V3.110.0, I am able to successfully create/ update all the resource. I have upgraded to latest version 4.8.0 and started getting the authentication issue as mentioned. 

As part of upgrade activity, I added below line in azurerm as mentioned in https://registry.terraform.io/providers/hashicorp/azurerm/4.0.0/docs/guides/4.0-upgrade-guide#specifying-subscription-id-is-now-mandatory
subscription_id            = var.b2c_subscription_id

### Steps to Reproduce

Create a basic configuration that uses v4.2.0 of the azurerm provider:
example:
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = "4.8.0"
    }
  }
}

provider "azurerm" {
  alias                      = "extranet"
  tenant_id                  = var.tenant_id
  subscription_id            = var.extranet_subscription_id
  skip_provider_registration = true
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

provider "azurerm" {
  alias                      = "b2c"
  tenant_id                  = var.tenant_id
  subscription_id            = var.b2c_subscription_id
  skip_provider_registration = true
  features {
  }
}

provider "azurerm" {
  alias                      = "management"
  tenant_id                  = var.tenant_id
  subscription_id            = var.management_subscription_id
  skip_provider_registration = true
  features {
  }
}

provider "azurerm" {
  alias                      = "b2c_tenant"
  tenant_id                  = data.azurerm_aadb2c_directory.instance.tenant_id
  client_id                  = var.b2c_tenant_sp_client_id
  client_secret              = var.b2c_tenant_sp_secret
  subscription_id            = var.b2c_subscription_id
  skip_provider_registration = true
  features {
  }
}

Run terraform init
Run terraform plan

Note: getting this error on version upgrade activity

**Comment by teowa** [comment]
Hi @sathizhmail , thanks for raise this, please follow https://registry.terraform.io/providers/hashicorp/azurerm/4.0.0/docs/guides/4.0-upgrade-guide#specifying-subscription-id-is-now-mandatory to add a `subscription_id` field for the provider block to solve this.

**Comment by sathizhmail** [comment]
> Hi @sathizhmail , thanks for raise this, please follow https://registry.terraform.io/providers/hashicorp/azurerm/4.0.0/docs/guides/4.0-upgrade-guide#specifying-subscription-id-is-now-mandatory to add a `subscription_id` field for the provider block to solve this.

Hi @teowa , I did follow already. Still getting issue. Thanks

**Comment by teowa** [comment]
Hi @sathizhmail , Sorry for the incorrect tip above. Could you please try adding the `tenant_id` field to the provider block, following the example in the last section of this [documentation](https://registry.terraform.io/providers/hashicorp/azurerm/4.0.0/docs/guides/azure_cli)? It should look like this:

```hcl
provider "azurerm" {
  features {}

  subscription_id = "00000000-0000-0000-0000-000000000000"
  tenant_id       = "11111111-1111-1111-1111-111111111111"
}
```

**Comment by Chambras** [comment]
@lonegunmanb  Do you think your tool can help here?

**Comment by sathizhmail** [comment]
It is working fine after setting environment variables is azure pipeline and removed tenant_id, client_id and client_secret from tf file.

Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret#configuring-the-service-principal-in-terraform
