### ISSUE TITLE
Support for azure_purview_account event hub namespace configuration via terraform

### ISSUE THREAD

**Issue by aryah55** [hashicorp/terraform-provider-azurerm#27928]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

This resource provider takes a managed resource group parameter where it deploys the event hub namespace purview uses. In doing so it puts a deny on the IAM of the managed resource group for ALL PRINCIPLES with exemptions for purview managed identity.

I have a requirement to send the diagnostic logs for the event hub name space as part of the automation. The deny policy prevents me from doing this using my deployment service principal.

It would be beneficial if there was an additional parameter on the identity block to allow for a service principal (one that I am using for deployment) to be added to the exemption list on the deny policy.

Currently when I try to set the diagnostic settings on the event hub name space I am get an error that whilst the deployment service principal I am using has the permissions it is denied from doing so on this policy

### New or Affected Resource(s)/Data Source(s)

azurerm_purview_account

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_purview_account" "example" {
  name                = "example"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  identity {
    type = "SystemAssigned"
    exempt_deny_principal_ids = ["princiapl_id_1","princiapl_id_1"]
  }
}
```

**Comment by ms-henglu** [comment]
Hi @aryah55 ,

Thank you for taking time to report this issue.

Unfortunately this feature has not been supported in the upstream API.

**Comment by aryah55** [comment]
Further investigations with a Microsoft policy engineer have yielded an alternative method to set the diagnostic settings.

Whilst it would be ideal for the upstream API to allow diagnostic settings rather the exemption this feature seeks the policy on the managed resource group does now prevent you from setting diagnostics using **azurerm_monitor_diagnostic_setting**.

The reason it was not working forus is that we use a pattern module/template we have developed in house that sets critical action groups. Action groups are prevented from being created on the policy the purview account sets.

I am closing this.
