### ISSUE TITLE
Security Center Automation and Continuous Export is not working as expected

### ISSUE THREAD

**Issue by jasoncaltonkroger** [hashicorp/terraform-provider-azurerm#27970]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.7.5

### AzureRM Provider Version

4.3.0

### Affected Resource(s)/Data Source(s)

azurerm_security_center_automation

### Terraform Configuration Files

```hcl
provider "azurerm" {
    features {}
}

data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "eastus"
}

resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace123"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  sku                 = "Standard"
  capacity            = 2
}

resource "azurerm_security_center_automation" "example" {
  name                = "ExportToEventHub"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  action {
    type              = "EventHub"
    resource_id       = azurerm_eventhub_namespace.example.id
    connection_string = azurerm_eventhub_namespace.example.default_primary_connection_string
  }

  source {
    event_source = "Assessments"

    rule_set {
      rule {
        property_path  = "type"
        operator       = "Contains"
        expected_value = "Microsoft.Security/assessments"
        property_type  = "String"
      }
    }
  }

  source {
    event_source = "SubAssessments"
  }

  source {
    event_source = "Alerts"

    rule_set {
      rule {
        property_path  = "properties.metadata.severity"
        operator       = "Equals"
        expected_value = "low"
        property_type  = "String"
      }
    }
    rule_set {
      rule {
        property_path  = "properties.metadata.severity"
        operator       = "Equals"
        expected_value = "medium"
        property_type  = "String"
      }
    }
    rule_set {
      rule {
        property_path  = "properties.metadata.severity"
        operator       = "Equals"
        expected_value = "high"
        property_type  = "String"
      }
    }
    rule_set {
      rule {
        property_path  = "properties.metadata.severity"
        operator       = "Equals"
        expected_value = "informational"
        property_type  = "String"
      }
    }
  }

  scopes = ["/subscriptions/${data.azurerm_client_config.current.subscription_id}"]
}
```

### Debug Output/Panic Output

```shell
n/a
```

### Expected Behaviour

Continuous export should be visible on the Azure Portal post deployment. 

### Actual Behaviour

Azure portal shows "Custom export settings were applied programmatically for this subscription" and no settings are shown

![image](https://github.com/user-attachments/assets/8c88004b-83e8-4a56-90ae-832d4017aeb3)

### Steps to Reproduce

terraform apply

**Comment by neil-yechenwei** [comment]
Thanks for raising this issue. It looks like it's by service API design. Suggest file Azure Support Ticket to get more usage info.

**Comment by jasoncaltonkroger** [comment]
Per MS this is expected:


Thank you for your prompt reply. I appreciate your patience as we investigated your query.

 

After conducting an internal review, I can confirm that the configuration for Defender for Cloud’s continuous export, when set up via API or Terraform, is not displayed in the Azure Portal by design. Please be assured that the configuration is indeed functional, even though it does not appear under the continuous export settings in the portal.

 

Instead, you will notice a banner in the Azure Portal indicating the presence of a continuous export configuration. This is expected behavior and signifies that the setup is active and working as intended.

 

[https://learn.microsoft.com/en-us/azure/defender-for-cloud/continuous-export-rest-api#set-up-continuous-export-by-using-the-rest-api](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fazure%2Fdefender-for-cloud%2Fcontinuous-export-rest-api%23set-up-continuous-export-by-using-the-rest-api&data=05%7C02%7Csupportmail5%40microsoft.com%7C3d02c0b2234c4f4cdaf608dd041d9991%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638671247380138949%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=K%2FpRcHglN7OFkUyBknlZfh0Ru6AVOuf52tXP7LhyId0%3D&reserved=0)
