### ISSUE TITLE
Microsoft_BotManagerRuleSet version 1.1 not accepted

### ISSUE THREAD

**Issue by jasperpostcn** [hashicorp/terraform-provider-azurerm#28036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.9.8

### AzureRM Provider Version

4.10.0

### Affected Resource(s)/Data Source(s)

azurerm_web_application_firewall_policy

### Terraform Configuration Files

```hcl
...
...
    managed_rule_set {
      type    = "OWASP"
      version = "3.2"
    }

    managed_rule_set {
      type    = "Microsoft_BotManagerRuleSet"
      version = "1.1"
    }
...
...
...
```

### Debug Output/Panic Output

```shell
Error: expected managed_rules.0.managed_rule_set.0.version to be one of ["0.1" "1.0" "2.1" "2.2.9" "3.0" "3.1" "3.2"], got 1.1
```

### Expected Behaviour

1.1 Can be selected in the Azure portal so the version constraint should include 1.1

### Actual Behaviour

Not accepting 1.1 for the Microsoft_BotManagerRuleSet rule set

**Comment by CorrenSoft** [comment]
Hi @jasperpostcn,
I've published a PR implementing this request, you can subscribe to it to get notified when (if) gets approved.
