### ISSUE TITLE
Support for azurerm_api_management_certificate

### ISSUE THREAD

**Issue by ThibGregSBMB** [hashicorp/terraform-provider-azurerm#28049]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

Hello,

I have a question regarding the azurerm_api_management_certificate resource in Terraform.

I want to use a .cer certificate, but according to the documentation for the resource, it states the following:
_[data] - (Optional) The base-64 encoded certificate data, which must be a PFX file._

However, in the Azure Portal, it is clearly stated that a .cer file can be used. I tested this manually by adding my .cer certificate in the Azure Portal, and it worked correctly:
![PortalAzureExemple](https://github.com/user-attachments/assets/fc4615af-6d12-4a97-a7c7-42962434e100)

My questions are:

- What will happen if I use a .cer certificate with Terraform?
- Is the Terraform documentation outdated regarding this resource?
- Will the ability to use .cer certificates be officially supported in a future version of Terraform?
- Since Azure only asks for a Base64-encoded string, does Terraform simply pass the string to Azure without validating its contents (whether it's from a .cer or .pfx file)?

Thank you in advance for your help!

Have a great day,

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management_certificate

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku_name = "Developer_1"
}

resource "azurerm_api_management_certificate" "example" {
  name                = "example-cert"
  api_management_name = azurerm_api_management.example.name
  resource_group_name = azurerm_resource_group.example.name
  data                = filebase64("example.pfx") #or .cer file ?
}
```

**Comment by rcskosir** [comment]
Thank you for taking the time to raise this! We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. So that we can maintain focus on that, we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community), such as the [Azure Provider forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure/34). With that in mind, I'm going to close this issue.
