### ISSUE TITLE
The certificate_policy should be optional when importing a certificate with azurerm_key_vault_certificate

### ISSUE THREAD

**Issue by stijnherreman** [hashicorp/terraform-provider-azurerm#2804]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `certificate_policy` is a required block, while it should be optional, at least when importing a certificate. The information needed to fill in the block can be determined from the certificate itself or is otherwise automatically filled in by Azure.

### New or Affected Resource(s)

* azurerm_key_vault_certificate

### Potential Terraform Configuration

I've modified the existing example from the documentation to only include what is actually required:

```hcl
resource "azurerm_key_vault_certificate" "test" {
  name      = "imported-cert"
  vault_uri = "${azurerm_key_vault.test.vault_uri}"

  certificate {
    contents = "${base64encode(file("certificate-to-import.pfx"))}"
  }
}
```

### References

The [REST API documentation](https://docs.microsoft.com/en-us/rest/api/keyvault/importcertificate/importcertificate) shows that the `policy` block is not required.

When importing a certificate through the Azure Portal, the certificate name and certificate file are required, and the certificate password is optional. You can use your browser's developer tools to inspect the POST request, the only thing posted in addition to the user-provided information is an `enabled` attribute:

```
https://vault-name.vault.azure.net/certificates/certificate-name/import?api-version=2016-10-01
{"value":"...","pwd":"...","attributes":{"enabled":true}}
```

You can then retrieve the certificate using the Azure CLI and you'll see that a complete `policy` block has automatically been created:

```
$ az keyvault certificate show --id "https://vault-name.vault.azure.net/certificates/certificate-name"

{
  ...
  "policy": {
    ...
    "issuerParameters": {
      "certificateTransparency": null,
      "certificateType": null,
      "name": "Unknown"
    },
    "keyProperties": {
      "curve": null,
      "exportable": true,
      "keySize": 2048,
      "keyType": "RSA",
      "reuseKey": false
    },
    "lifetimeActions": [
      {
        "action": {
          "actionType": "EmailContacts"
        },
        "trigger": {
          "daysBeforeExpiry": null,
          "lifetimePercentage": 80
        }
      }
    ],
    "secretProperties": {
      "contentType": "application/x-pkcs12"
    },
    "x509CertificateProperties": {
      ...
    }
  }
  ...
}
```

**Comment by aristosvo** [comment]
Hi @stijnherreman! Thanks for this issue, I'll take a quick look if it is possible to implement this.

I will let you know the outcome!
