### ISSUE TITLE
`data.azurerm_logic_app_standard` fails with "Invalid address to set"

### ISSUE THREAD

**Issue by lra** [hashicorp/terraform-provider-azurerm#28156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.0

### AzureRM Provider Version

4.12.0

### Affected Resource(s)/Data Source(s)

azurerm_logic_app_standard

### Terraform Configuration Files

```hcl
data "azurerm_logic_app_standard" "pgalert_intake" {
  name                = "PGAlertIntake"
  resource_group_name = "prod-seismic"
}
```

### Debug Output/Panic Output

```shell
A simple terraform plan leads to:

data.azurerm_logic_app_standard.pgalert_intake: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: setting `identity`: Invalid address to set: []string{"identity", "0", "identity_ids"}
│
│   with data.azurerm_logic_app_standard.pgalert_intake,
│   on sql-monitoring.tf line 43, in data "azurerm_logic_app_standard" "pgalert_intake":
│   43: data "azurerm_logic_app_standard" "pgalert_intake" {
│
╵
```

### Expected Behaviour

Using azurerm v4.11.0 I get:
```
No changes. Your infrastructure matches the configuration.
```

### Actual Behaviour

Using azurerm v4.12.0 I get:
```
data.azurerm_logic_app_standard.pgalert_intake: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: setting `identity`: Invalid address to set: []string{"identity", "0", "identity_ids"}
│
│   with data.azurerm_logic_app_standard.pgalert_intake,
│   on sql-monitoring.tf line 43, in data "azurerm_logic_app_standard" "pgalert_intake":
│   43: data "azurerm_logic_app_standard" "pgalert_intake" {
│
╵
```

### Steps to Reproduce

1. terraform plan

### Important Factoids

This works fine with azurerm v4.11.0. The bug was introduced in v4.12.0.

**Comment by ziyeqf** [comment]
Hi @lra , thanks for reporting!

I submitted a PR(https://github.com/hashicorp/terraform-provider-azurerm/pull/28158) for it, once it merged & released, this should be fixed, before that please use v4.11.0 temporarily.
