### ISSUE TITLE
Adding example for app service + API management

### ISSUE THREAD

**Issue by azarboon** [hashicorp/terraform-provider-azurerm#28153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Description

I can't find any good example that connects App Service with Azure API Management. Existing tutorials are outdated. I've already created that (it was challenging a bit) and I was wondering if I can add it in example folder. This my first time adding example so I  was wondering if such a contribution is welcomed, and if so, which specification / requirements I need to keep in mind.

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management azurerm_linux_function_app

**Comment by azarboon** [comment]
@ssouthcity @jackofallops @gerrytan @paulomarquesc what's your advice?

**Comment by rcskosir** [comment]
Thank you for taking the time to open this. We use Issues in this repository to track feature enhancements and bugs in the Azure Provider. As such I am going to close this issue. For information about contributing please see our [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) that should help answer your questions regarding how to contribute.
