### ISSUE TITLE
automatic_channel_upgrade for resource azurerm_kubernetes_cluster does not display warning in v3

### ISSUE THREAD

**Issue by MichaelChristopherson** [hashicorp/terraform-provider-azurerm#28170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.5.6

### AzureRM Provider Version

3.116.0

### Affected Resource(s)/Data Source(s)

azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "default" {
  name = "test"

  automatic_channel_upgrade = "stable"
  node_os_channel_upgrade   = "NodeImage"

  default_node_pool {
    enable_auto_scaling    = true
    enable_host_encryption = true
    enable_node_public_ip  = false
  }
}
```

### Debug Output/Panic Output

```shell
│ Error: Unsupported argument
│ 
│   on my_tf_file.tf line xxx, in resource "azurerm_kubernetes_cluster" "my_resource_name":
│  xxx:   automatic_channel_upgrade = "stable"
│ 
│ An argument named "automatic_channel_upgrade" is not expected here.
```

### Expected Behaviour

When running a terraform plan or apply when using a v3 of the azurerm provider I would expect a WARNING to show up stating that the automatic_channel_upgrade has been depreciated and replaced by [automatic_upgrade_channel](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/kubernetes_cluster#automatic_upgrade_channel-1).

Currently no versions of the azurerm `3.x` provider support using `automatic_upgrade_channel` in place of `automatic_channel_upgrade` so users cannot even proactively use the new value before upgrading like you are able in many other resources.

### Actual Behaviour

When running a plan with version `3.116.0` no warning is displayed about `automatic_channel_upgrade` being replaced by `automatic_upgrade_channel` in 4.x versions of the provider.  So after upgrading the provider to version `4.10.0` we get an error right away when trying to run a plan or apply:

```
│ Error: Unsupported argument
│ 
│   on my_file.tf line  xxx, in resource "azurerm_kubernetes_cluster" "my_resource":
│  xxx:   automatic_channel_upgrade = "stable"
│ 
│ An argument named "automatic_channel_upgrade" is not expected here.
```

### Steps to Reproduce

Run a terraform plan or apply with version 3.116.0 of the provider.  No warning will be shown.
Upgrade terraform provider for azurerm from 3.x to 4.x
Run a terraform plan or apply and an error will be thrown.

### References

4.10.0 documentation: https://registry.terraform.io/providers/hashicorp/azurerm/4.10.0/docs/resources/kubernetes_cluster
3.117.0 documentation: https://registry.terraform.io/providers/hashicorp/azurerm/3.117.0/docs/resources/kubernetes_cluster

**Comment by MichaelChristopherson** [comment]
While I understand that there are breaking changes from one version to another that should be reviewed, most resources for the azurerm provider provide the ability to support both values in the latest 3.x version before upgrading to 4.x and provide a warning message that the value is changing, no longer supported in the next version, etc.

The fact that the behavior is not the same is what caused me to open this issue suggesting that when possible it should be accounted for.  The value of `enable_auto_scaling` was also updated from 3.x to `auto_scaling_enabled` in 4.x.  The values these properties accept has stayed the same they simply appear to be renamed before digging in more.

**Comment by stephybun** [comment]
Hey @MichaelChristopherson there is another issue open with the same query/concern. To consolidate discussion I'm going to close this in favour of https://github.com/hashicorp/terraform-provider-azurerm/issues/27209.
