### ISSUE TITLE
Always wants to replace resource and remove leading slash from subscription

### ISSUE THREAD

**Issue by black-snow** [hashicorp/terraform-provider-azurerm#28176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.0

### AzureRM Provider Version

3.116.0

same behaviour with 4.x

### Affected Resource(s)/Data Source(s)

azurerm_storage_management_policy

### Terraform Configuration Files

```hcl
resource "azurerm_storage_management_policy" "blob_auto_delete" {
  count = 1

  storage_account_id = azurerm_storage_account.this.id
  rule {
    name    = "autoDelete60"
    enabled = true
    filters {
      blob_types = ["blockBlob"]
    }
    actions {
      base_blob {
        delete_after_days_since_creation_greater_than = 60
      }
    }
  }
}
```

### Debug Output/Panic Output

```shell
# module.xxx.azurerm_storage_management_policy.blob_auto_delete[0] must be replaced
-/+ resource "azurerm_storage_management_policy" "blob_auto_delete" {

      ~ storage_account_id = "/subscriptions/xxx/resourceGroups/rg-test/providers/Microsoft.Storage/storageAccounts/xxx" -> "subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Storage/storageAccounts/xxx" # forces replacement
```

### Expected Behaviour

no replacement

### Actual Behaviour

replacement

Only happens with this one. I have other policies that work fine. Tried deleting and recreating it as well as "fixing" the state but it keeps coming back.

### Steps to Reproduce

Hard to say as it only happens with one of many policies.

### Important Factoids

nope

**Comment by magodo** [comment]
@black-snow I think the issue is more related to the `azurerm_storage_account.this.id`, where its current value is *without* the slash.

Could you kindly confirm this from the output of `terraform show`?

**Comment by black-snow** [comment]
You're correct - `terraform show | rg --pcre2 '"(?<!/)subscription'` yields `id = "subscriptions/99...` - I'll fix it in the state.

Thanks @magodo
