### ISSUE TITLE
Why does `import` on an `sql_database` require a firewall opening for Azure services?

### ISSUE THREAD

**Issue by tomasaschan** [hashicorp/terraform-provider-azurerm#2824]
Given an `sql_database` resource with the following import declaration
```
  import = {
    storage_uri                  = "${var.database_baseline_blob_url}"
    storage_key                  = "${var.deployment_storage_access_key}"
    storage_key_type             = "StorageAccessKey"
    administrator_login          = "${var.db_server_admin_username}"
    administrator_login_password = "${var.db_server_admin_password}"
    authentication_type          = "SQL"
  }
```
I can successfully import the database _if_ I also add a firewall opening for Azure services (i.e. IP range `0.0.0.0`-`0.0.0.0`). If I don't, the apply operation fails with an error message stating that the database server is not accessible from some IP (in my case it was an IP in Amsterdam, which I guess makes sense since the server is in the West Europe region).

I'm assuming this is not a limitation of Terraform, but of the underlying implementation of this functionality, but it would be nice if Terraform could make this _just work_, e.g. by detecting that no such firewall rule exists (and that it won't be created during the apply operation?) and, if needed, wrap the operation with creating the rule and cleaning up afterwards. Would that be feasible, or is it too complicated for the provider to handle?

**Comment by mehulr-cotiviti** [comment]
IP Address which i had to open is : 168.62.48.129  ("Microsoft Corporation", "Hampden Sydney", VA, USA)

Error which i got .. 
Error: sql.DatabasesClient#CreateImportOperation: Failure sending request: StatusCode=400 -- Original Error: Code="Failed" Message="The async operation failed." InnerError={"unmarshalError":"json: cannot unmarshal array into Go struct field serviceError2.details of type map[string]interface {}"} AdditionalInfo=[{"code":"0","details":[{"code":"0","message":"There was an error that occurred during this operation : '\u003cstring xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/\"\u003eError encountered during the service operation. ; Exception Microsoft.SqlServer.Management.Dac.Services.ServiceException:Unable to authenticate request; Inner exception System.Data.SqlClient.SqlException:Cannot open server \u0026amp;#39;my-dev-sqlsvr\u0026amp;#39; requested by the login. Client with IP address \u0026amp;#39;168.62.48.129\u0026amp;#39; is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.; \u003c/string\u003e'","severity":"16","target":null}],"innererror":[],"message":"There was an error that occurred during this operation : '\u003cstring xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/\"\u003eError encountered during the service operation. ; Exception Microsoft.SqlServer.Management.Dac.Services.ServiceException:Unable to authenticate request; Inner exception System.Data.SqlClient.SqlException:Cannot open server \u0026amp;#39;my-dev-sqlsvr\u0026amp;#39; requested by the login. Client with IP address \u0026amp;#39;168.62.48.129\u0026amp;#39; is not allowed to access the server.  To enable access, use the Windows Azure Management Portal or run sp_set_firewall_rule on the master database to create a firewall rule for this IP address or address range.  It may take up to five minutes for this change to take effect.; \u003c/string\u003e'","target":null}]

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
