### ISSUE TITLE
 dotnet_framework_version upto v6.0 is available and Need v7.0

### ISSUE THREAD

**Issue by rohitpatil2137** [hashicorp/terraform-provider-azurerm#28338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave comments along the lines of "+1", "me too" or "any updates", they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment and review the [contribution guide](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/contributing/README.md) to help.

### Terraform Version

1.10.3

### AzureRM Provider Version

4.14

### Affected Resource(s)/Data Source(s)

azurerm_app_service

### Terraform Configuration Files

```hcl
Currently we are using  dotnet_framework_version   = "v7.0" and terraform support upto v6.0
```

### Debug Output/Panic Output

```shell
dotnet_framework_version   = "v7.0"
value is not supported
```

### Expected Behaviour

dotnet_framework_version   = "v7.0"

**Comment by ned1313** [comment]
@rohitpatil2137 the resource `azurerm_web_service` was deprecated in v3 of the provider. According to the validation command:

```bash
The `azurerm_app_service` resource has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources. Whilst this resource will
│ continue to be available in the 2.x and 3.x releases it is feature-frozen for compatibility purposes, will no longer receive any updates and will be removed
│ in a future major release of the Azure Provider.
```

As such, I don't think any new versions of the .Net framework will be added to this resource type.

**Comment by rcskosir** [comment]
@rohitpatil2137 @ned1313 is correct here, `azurerm_app_service` is superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app`. `azurerm_app_service` will no longer receive any updates, as such I am going to close this request. Please use one of the new resources, I believe they support .Net v7.0 but if not, feel free to open a new feature request issue for that.
