### ISSUE TITLE
New Resource: azurerm_monitor_scheduled_query_rule

### ISSUE THREAD

**Issue by katbyte** [hashicorp/terraform-provider-azurerm#2854]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Implement Azure Monitor Scheduled Query Rule

### New or Affected Resource(s)

* azurerm_monitor_scheduled_query_rule

**Comment by tombuildsstuff** [comment]
Upstream API issue: https://github.com/Azure/azure-rest-api-specs/issues/5326

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
