### ISSUE TITLE
Policy Set Definition - Policy Definition ID Association Error

### ISSUE THREAD

**Issue by AErmie** [hashicorp/terraform-provider-azurerm#2858]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11

### Affected Resource(s)

* `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
resource "azurerm_policy_set_definition" "Initiative-Tags" {
  name         = "Initiative-AllResources-EnforceTags"
  policy_type  = "Custom"
  display_name = "Initiative-AllResources-EnforceTags"
  description  = "This initiative contains all of the Tagging Policies."
  management_group_id = "${var.PolicyDefinitionLocation}" 
  metadata = <<META
  {
    "category": "test"
  }
META
  parameters = <<PARAMETERS
    {
      "PolicyDefinitionID": "/providers/Microsoft.Authorization/policyDefinitions/Policy-AllResources-EnforceTags-Environment"
    }
    
PARAMETERS

  policy_definitions = <<POLICY_DEFINITIONS
    [
        {
          "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/Policy-AllResources-EnforceTags-Environment",
          "parameters": {
            "tagName": {
                "value": "Environment"
            },
            "tagValue": {
                "value": "BLANK",
                "allowedValues": [
                  "Core",
                  "Production",
                  "NonProduction"
                ]
            }
          }
        }
    ]
POLICY_DEFINITIONS
}
```

### Expected Behavior

Associate/link a Policy Definition with a Policy Initiative

### Actual Behavior

* azurerm_policy_set_definition.Initiative-Tags: Error creating/updating Policy Set Definition "Initiative-AllResources-EnforceTags": policy.SetDefinitionsClient#CreateOrUpdateAtManagementGroup: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidRequestContent" Message="The request content was invalid and could not be deserialized: 'Error converting value \"Policy-AllResources-EnforceTags-Environment\" to type 'Microsoft.WindowsAzure.ResourceStack.Providers.Authorization.Data.Entities.PolicyParameterDefinition'. Path 'properties.parameters.PolicyDefinitionID', line 1, position 327.'."

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by olohmann** [comment]
As far as I can see, the actual policy set definition code is not correct (i.e. it seems not to be a terraform resource bug). Especially the mix between params and policy definitions looks incorrect. 

Something like this is actually working:
```tf
resource "azurerm_policy_set_definition" "test" {
  name         = "testPolicySet"
  policy_type  = "Custom"
  display_name = "Test Policy Set"

  parameters = <<PARAMETERS
    {
        "tagName": {
            "type": "String",
            "metadata": {
                "description": "Tag Name",
                "displayName": "Tag Name"
            }
        },
 		"tagValue": {
            "type": "String",
            "metadata": {
                "description": "Tag Value",
                "displayName": "Tag Value"
            },
			"allowedValues": [
				"foo",
				"bar",
				"foobar"
			]
        }
    }
PARAMETERS

  policy_definitions = <<POLICY_DEFINITIONS
    [
        {
            "parameters": {
                "tagName": {
                    "value": "[parameters('tagName')]"
                },
				"tagValue": {
                    "value": "[parameters('tagValue')]"
                }
            },
            "policyDefinitionId": "/providers/Microsoft.Authorization/policyDefinitions/1e30110a-5ceb-460c-a204-c1c3969c6d62"
        }
    ]
POLICY_DEFINITIONS
}
```

**Comment by AErmie** [comment]
Thanks, I will try to modify my policy set to this format, however, the challenge I see is with the Policy Definition ID, which is generated at the time of creating the policy. So I was trying to pass it in as a variable. 

Also, does the Policy Def ID have to be a GUID? When I create a Policy in Terraform, the Name becomes the ID, which is not a GUID, so I wonder if that's causing an issue as well.

**Comment by olohmann** [comment]
Policy Sets are basically referring to Policy Definitions. I referred to the built-in Policy Definition for tag enforcement. This has a "well-known" (= static) ID. If you want to refer to a custom Policy Definition that you create dynamically with e.g. Terraform, you need to pass it as a dependency as with every other Terraform resource chaining. For example: `"policyDefinitionId": "${azurerm_policy_definition.test.id}"`

**Comment by mikelala** [comment]
@olohmann , Thank you for your comments. I am trying to create an initiative with several labels, but I do not know how to add several policies in the same initiative. Could you help me? Thank you!!!!!

**Comment by techadmin1982** [comment]
@olohmann @AErmie I am trying to create a new initiative with 2 "built-in" policies (allowedlocation and allowedSKU) using Terraform. There is not enough examples or clarity provided on below terraform KB on how multiple policies can be referenced inside a Terraform Initiative.  I can create the initiative with a single policy like the example given on the KB , no problem. Please can you help me as this is an interesting feature and i hope you know this answer already. 

[KB Link](https://www.terraform.io/docs/providers/azurerm/r/policy_set_definition.html)

**Comment by AErmie** [comment]
@techadmin1982, you're going to need to list/have multiple policy definition references, like this: 

policy_definition_reference {
    policy_definition_id = var.EnforceTags-CostCenter
    parameters = {
        tagName = "[parameters('CostCenter-tagName')]",
        tagValue = "[parameters('CostCenter-tagValue')]"
      }
  }

  policy_definition_reference {
    policy_definition_id = var.EnforceTags-DisasterRecoveryServiceTier
    parameters = {
        tagName = "[parameters('DisasterRecoveryServiceTier-tagName')]",
        tagValue = "[parameters('DisasterRecoveryServiceTier-tagValue')]"
      }
  }

**Comment by techadmin1982** [comment]
@AErmie Still getting error. I am using below code
`resource "azurerm_policy_set_definition" "polset1" {
name         = "pulu1"
policy_type  = "Custom"
display_name = "pulu1"

parameters = <<PARAMETERS
    {
        "sku-tagName": {
            "type": "String",
            "metadata": {
                "description": "The list of size SKUs that can be specified for virtual machines.",
                "displayName": "Allowed Size SKUs"
            }
        },
 		"tagValue": {
            "type": "Array",
            "metadata": {
                "description": "The list of size SKUs that can be specified for virtual machines.",
                "displayName": "Allowed Size SKUs"
            }
        }
    }
PARAMETERS

policy_definition_reference {
policy_definition_id = data.azurerm_policy_definition.pol1.id
parameters = {
tagName = "[parameters('sku-tagName')]",
tagValue = "[parameters('sku-tagValue')]"
}
}
}`


All look great till i run terraform apply. So, basically it's a runtime error i get 
Error: expanding `policy_definition_reference`: cannot set both `parameters` and `parameter_values`

  on initiative.tf line 1, in resource "azurerm_policy_set_definition" "polset1":
   1: resource "azurerm_policy_set_definition" "polset1" {

**Comment by techadmin1982** [comment]
@AErmie Nailed it finally !!. Thanks for your help.  
Let me explain what i did because I am sure many people would be facing this issue. I would also appreciate if you or someone from Hashicorp can review my example and modify their KB page. 
[Terraform KB](https://www.terraform.io/docs/providers/azurerm/r/policy_set_definition.html)

Ok, so I was struggling all morning to create a custom Azure initiative (azurerm_policy_set_definition in Terraform's). This initiative shall carry 2 "Built-In" Policies (Allowed Locations and Allowed Size SKUs). I am using:
Terraform version : v0.13.3
AzureRM Provider Plugin: version = "~>2.0"
Attached Zipped file containing terraform configuration file.

Let me know if there are any questions. 

[sm.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5293610/sm.zip)

**Comment by techadmin1982** [comment]
Update: I can see Terraform is allowing me to reference the built-in policies using "Data Sources" block in my code. 
So a good strategy could be create a separate tf file holding a list of built-in policies (see below)

``
data "azurerm_policy_definition" "pol1" {
display_name = "Allowed locations"
}
data "azurerm_policy_definition" "pol2" {
display_name = "Allowed virtual machine size SKUs"
}
``

**Comment by techadmin1982** [comment]
Update: I can see Terraform is allowing me to reference the built-in policies using "Data Sources" block in my code. 
So a good strategy could be create a separate tf file holding a list of built-in policies (see below)
```
data "azurerm_policy_definition" "pol1" {
display_name = "Allowed locations"
}
data "azurerm_policy_definition" "pol2" {
display_name = "Allowed virtual machine size SKUs"
}

```
I will put these codes in my personal GitHub repo today and post the link here.

**Comment by techadmin1982** [comment]
Please find the repo [here](https://github.com/techadmin1982/Azure_Policies_Using_Terraform.git)

**Comment by catriona-m** [comment]
It looks like this has been answered and can be closed now, however please feel free to reopen if this is not the case. Thanks!
