### ISSUE TITLE
Consider replacing satori/go.uuid

### ISSUE THREAD

**Issue by radeksimko** [hashicorp/terraform-provider-azurerm#2882]
This library does not seem to be maintained anymore per https://github.com/satori/go.uuid/issues/83 (and mentioned in a few other issues).

It seems that some other folks have switched over to https://github.com/gofrs/uuid

Alternatively HashiCorp maintains this library https://github.com/hashicorp/go-uuid

Would there be an interest in a PR which replaces the dependency? Is there any preference?

----

Admittedly this repo will have to keep vendoring `satori/go.uuid` due to https://github.com/Azure/azure-sdk-for-go/issues/3158 but that's a separate problem we can deal with later.

**Comment by katbyte** [comment]
I would support this PR! right now we either use `hashicorp/go-uuid` and `google/uuid` so either of those would get my vote unless there is a compelling reason to use `gofrs/uuid` over either of them.

**Comment by katbyte** [comment]
Opened an [issue ](https://github.com/Azure/azure-sdk-for-go/issues/4119) on the SDK.

Looking into it a bit more i think `gofrs/uuid` makes the most sense as it is a fork of `satori/go.uuid`

**Comment by radeksimko** [comment]
FYI: I agree the SDK should replace it too, but the aim of this issue was mainly replacing the library in the provider code. The provider itself uses this library, it's not just transitive dependency from the SDK.

See https://github.com/terraform-providers/terraform-provider-azurerm/search?q=github.com%2Fsatori%2Fgo.uuid&unscoped_q=github.com%2Fsatori%2Fgo.uuid

btw. there's already an issue in the upstream SDK:
https://github.com/Azure/azure-sdk-for-go/issues/3158

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
