### ISSUE TITLE
Azure Terraform plan shows modification on resources using "azurerm_app_service" and "azurerm_app-service_plan" after Terraform apply

### ISSUE THREAD

**Issue by vijayinaws** [hashicorp/terraform-provider-azurerm#2899]
### Terraform Version:
Terraform v0.11.11

### Azure Provider:
provider.azurerm v1.22.0

### Affected Resources:
azurerm_app_service
azurerm_app_service_plan

### Issue:
When I try terraform plan after terraform apply for the below attached terraform script using "azurerm_app_service" and "azurerm_app_service_plan", the plan output shows " ~ update in-place" for some of the resources created.
For "azurerm_app_service" resource issue occurs when I try to create more than 5 resources. 
For "azurerm_app_service_plan" issue occurs every time.

### main.tf
       resource "azurerm_app_service" "resouce_app_service" {
            count               = "${length(var.module_app_service_name)}"
            name                = "${element(var.module_app_service_name, count.index)}"
            location            = "East US"
            resource_group_name = "SBX_Azure_Images"
            app_service_plan_id = "${azurerm_app_service_plan.resource_app_service_plan.id}"

            site_config {
                dotnet_framework_version = "v4.0"
                remote_debugging_enabled = "true"
                remote_debugging_version = "VS2015"
            }

                app_settings {
                "WEBSITE_NODE_DEFAULT_VERSION" = "8.9.3"
        }
      }
        

        resource "azurerm_app_service_plan" "resource_app_service_plan" {
            name                = "demo-app-service-pan"
            location            = "East US"
            resource_group_name = "SBX_Azure_Images"

            sku {
                tier = "Shared"
                size = "S2"
            }
            
        }

        variable "module_app_service_name" {               
            type     = "list"
            default = [
                "app-test-demo-1",
                "app-test-demo-2",
                "app-test-demo-3",
                "app-test-demo-4",
                "app-test-demo-5",
                "app-test-demo-6",
                "app-test-demo-7",
                "app-test-demo-8",
                "app-test-demo-9",
                "app-test-demo-10",
                "app-test-demo-11",       
                ]
        }

### Debug output:

        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
        ~ update in-place

        Terraform will perform the following actions:

        ~ azurerm_app_service.resouce_app_service_2
            site_config.0.remote_debugging_enabled: "false" => "true"

        ~ azurerm_app_service.resouce_app_service_3
            site_config.0.remote_debugging_enabled: "false" => "true"

        ~ azurerm_app_service.resouce_app_service_4
            site_config.0.remote_debugging_enabled: "false" => "true"

        ~ azurerm_app_service.resouce_app_service_6
            site_config.0.remote_debugging_enabled: "false" => "true"

        ~ azurerm_app_service.resouce_app_service_7
            site_config.0.remote_debugging_enabled: "false" => "true"

        ~ azurerm_app_service.resouce_app_service_9
            site_config.0.remote_debugging_enabled: "false" => "true"

        ~ azurerm_app_service_plan.resource_app_service_plan
            sku.0.tier:                             "Standard" => "Shared"

        Plan: 0 to add, 7 to change, 0 to destroy.

        ------------------------------------------------------------------------

        Note: You didn't specify an "-out" parameter to save this plan, so Terraform
        can't guarantee that exactly these actions will be performed if
        "terraform apply" is subsequently run.

The above terraform creates 11 "azurerm_app_service" resource, but it is changing only 6 of them.
Compared terraform statefile and actual resource value and it is not set properly.

### Expected Behaviour:
Terrform plan should be "Insfrastructure is up to date"

### Actual Behaviour:
Terraform plan requires modification on resources

**Comment by neil-yechenwei** [comment]
Seems sku.tier in app service plan doesn't take effect. I filed an issue on Azure/azure-rest-api-specs#9726

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
