### ISSUE TITLE
New resource/request: Set 'Azure function' as action type for  'azurerm_monitor_action_group'

### ISSUE THREAD

**Issue by mrmojo666** [hashicorp/terraform-provider-azurerm#2982]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As title, is in roadmap to add "Azure Function" action type to "azurerm_monitor_action_group", seems that is supported by SDK https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/monitor/mgmt/2018-03-01/insights/models.go#L623

Thank you

**Comment by ddarwent** [comment]
Should a create a New Issue for the same thing but to support LogicApps?

**Comment by mchodson** [comment]
the push to app "AzureAppPushReceiver" should be added as well.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
