### ISSUE TITLE
Support managed disk from Packer image

### ISSUE THREAD

**Issue by gvilarino** [hashicorp/terraform-provider-azurerm#3014]
I'm being unable to make Linux VMs from packer images and managed disks play well with Terraform ([community thread here](https://stackoverflow.com/questions/55033018/terraform-azure-create-a-linux-vm-from-packer-image-and-external-data-disk), if you'd like to check out my approach, issues, and chip in with a thought on my solution).

If I understand #560 correctly, Packer-built images are not supported in the `azurerm_managed_disk`'s `create_option = FromImage` option.

My feature request would be for `azurerm_managed_disk` to support a way of using a data disk defined in a packer image when using `create_option = FromImage` (or a different option like `FromCustomImage`). I imagine something like this:

```HCL
data "azurerm_image" "custom" {
  name                = "some-custom-packer-image"
  resource_group_name = "custom-image-rg"
}

resource "azurerm_resource_group" "rg" {
  location = "eastus"
  name     = "terraform-rg"
}

resource "azurerm_managed_disk" "datadisk" {
  create_option        = "FromImage"
  image_reference_id   = "${data.azurerm_image.custom.data_disk.0.managed_disk_id}"
  location             = "${azurerm_resource_group.location}"
  name                 = "external-datadisk"
  resource_group_name  = "terraform-rg"
  storage_account_type = "Standard_LRS"
}
```

Note that `disk_size_gb` wouldn't be necessary as it's already defined during image creation.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
