### ISSUE TITLE
Application gateway - support for health probe return code range

### ISSUE THREAD

**Issue by bfleming-ciena** [hashicorp/terraform-provider-azurerm#3061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
For the health probe, you can supply a comma separated list OR you can give it a range and Azure will accept it. I would like to be able to support the range.  

Example:

200-999

In one case we needed to do this for a legacy app.

![image](https://user-images.githubusercontent.com/4722084/54463385-1baf8200-4730-11e9-8800-4c82a8dc211f.png)

### New or Affected Resource(s)

* azurerm_application_gateway

### Potential Terraform Configuration

```hcl
  #######################################################################
  # Health Probes
  #
  probe {
    name = "mysite.domain.com-probe"
    host = "mysite.domain.com"
    path = "/"
    interval = 30
    timeout = 30
    unhealthy_threshold = 3
    protocol = "Http"

    match {
      # define a local for this big list and put it here.
      status_code = "200-999" ### Doesn't work because it's a list.
    }
  }
```

### References

* #0000

**Comment by schuettecarsten** [comment]
This works here with 1.29.0 provider version.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
