### ISSUE TITLE
azurerm_role_assignment doesn't seem to work with registered apps

### ISSUE THREAD

**Issue by spacekitty76** [hashicorp/terraform-provider-azurerm#3179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azuread v0.2.0
+ provider.azurerm v1.24.0

### Affected Resource(s)

azuread_application
azurerm_role_assignment

### Terraform Configuration Files

```hcl
data "azuread_application" "test" {
  name = "my-sp-app"
}

resource "azurerm_role_assignment" "test" {
  scope                = "my-scope-here"
  role_definition_name = "Owner"
  principal_id         = "${data.azuread_application.test.application_id}"
}
```

### Debug Output
Using the app_id (which is required by azure for this case)
https://gist.github.com/spacekitty76/b2ed9356dd64c21d6918a94c13bbdc01

Using the apps object_id:
https://gist.github.com/spacekitty76/966ea89ddc9cc0dc08ab1faec3f0a247

### Expected Behavior

Create the role assignment using an application id.  The equivalent az ad command is (I have verified this command works as well):
az role assignment create --assignee <app_id> --role Owner --scope <my-scope>

### Actual Behavior
Terraform fails on assigning the role when an app_id is provided.  If you try to provide the
object id Azure rejects this.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by nomaster** [comment]
I've got it working!

We are missing an intermediate resource here: the **service principal**.

Consider the following code, which manages the creation of a service principal. It belongs to the app and gets the role assigned.

```hcl
data "azurerm_subscription" "current" {}

resource "azuread_application" "app" {
  name = "Your App"
}

resource "azuread_service_principal" "app" {
  application_id = azuread_application.app.application_id
}

resource "azurerm_role_assignment" "app_contributor" {
  role_definition_name = "Owner"
  principal_id         = azuread_service_principal.app.object_id
  scope                = azurerm_subscription.current.id
}
```
