### ISSUE TITLE
add Script actions to deployment to azurerm_hdinsight_spark_cluster

### ISSUE THREAD

**Issue by ofirshtrull** [hashicorp/terraform-provider-azurerm#3345]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

in Azure when creating an hdinsight cluster there is the ability to add Script actions,
it will be nice to have this option in the module

and in the the aws version emr there is an option to add spark cluster configuration i.e hive_site  is there an option to add this also to the deployment as a nice to have

### New or Affected Resource(s)

* azurerm_hdinsight_spark_cluster

* #0000

**Comment by ofirshtrull** [comment]
also, I noticed  that the Metastore Settings option is also missing

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Comment by FurcyPin** [comment]
Hi @favoretti ,

We came across this issue while using the latest version of this provider (2.74.0).
This feature request is still relevant. We created a new ticket: #13205

I'll add that Script Actions are crucial for provisioning HDInsight clusters correctly, 
they are scripts that are run on the nodes to configure them correctly, pre-install packages, etc.
