### ISSUE TITLE
Passing a blank administrator_login_password in azurerm_sql_server causes it not to attempt to update the password.

### ISSUE THREAD

**Issue by zippy1981** [hashicorp/terraform-provider-azurerm#3347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azuread v0.3.1
+ provider.azurerm v1.25.0

### Affected Resource(s)

* `azurerm_sql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_sql_server" "my_server" {
    name                          = "MyServer"
    resource_group_name           = "MyRG"
    location                      = "US Central"
    version                       = "12.0"
    administrator_login           = "${var.sql_settings["admin_login"]}"
    administrator_login_password  = ""
    /*
    lifecycle {
      ignore_changes = [
        "administrator_login",
        "administrator_login_password"
      ]
    }
    */
}
```

### Debug Output

Will provide secretly.

### Panic Output

None

### Expected Behavior

terraform should have attempted to  change the password to a blank string if updating an existing resource

### Actual Behavior

Terraform did not verify the password was the same at all. 

### Steps to Reproduce

1. Create a `azure_rm_sql_server` manually in the azure portal.
2. Add it to a tf file
3. Use `tf import` to add its state.
4. Set 'administrator_password' to "".
5. Perform a `tf plan` or `tf apply`

### Important Factoids

Extracted from a conversation from #3308. Expected behavior as per @katbyte.

### References

**Comment by zippy1981** [comment]
On the subject @katbyte also felt that the provider shouldn't even allow it to set a blank password because that would be forbidden. Since I assume its possible to configure a password policy to allow a blank password (despite how terrible an idea that would be) I don't think terraform should forbid that.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
