### ISSUE TITLE
Please add "ADVANCED DATA SECURITY" options to azurerm_sql_server

### ISSUE THREAD

**Issue by Sahasrara** [hashicorp/terraform-provider-azurerm#3366]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be nice to be able to toggle "ADVANCED DATA SECURITY" and enable "periodic reoccurring scans." 

### New or Affected Resource(s)

* azurerm_sql_server

### Potential Terraform Configuration

```
resource "azurerm_sql_server" "test" {
  advanced_data_security_enabled = true
  ...
}
```

### References

https://www.terraform.io/docs/providers/azurerm/r/sql_server.html

**Comment by ricohomewood** [comment]
This is a good one to enable as flags at high in Security Center for not being enabled. @tombuildsstuff what would the roadmap for this look like? Not sure if there is another ticket for enabling SQL server auditing?

**Comment by angusmack-altius** [comment]
I got this enabled and thus the warning in SC to go away using the threat_detection_policy setting

  threat_detection_policy {
    state                      = "Enabled"
    email_account_admins       = "Disabled"
    email_addresses            = ["xxxxx@yyy.com"]
    retention_days             = "30"
    storage_account_access_key = "${var.storage_logging_key}"
    storage_endpoint           = "https://${var.storage_logging_endpoint}/"
    use_server_default         = "Disabled"
  }

in the azurerm_sql_database resource.

Still working on how to enable the Auditing though...

**Comment by ricohomewood** [comment]
so it should be a case of implementing threat_detection_policy block at the logical SQL server level in `azurerm_sql_server` if this is already available at the database level.

**Comment by edisonmndza** [comment]
Any updates on this?

**Comment by rohrerb** [comment]
@katbyte  - Any chance we can get this planned?  Best to apply this at the SQL Server level so that all DB's under it will inherit the settings.  If possible it would nice if the policy was a separate resource instead of a field map.

**Comment by andymac4182** [comment]
It appears this isn't available at the SQL Server level in the API. This could be a MS feature required to be added to their API. I could only find the below linked API which is for a single database and seems to be related to the policy that you can set per database. 
https://docs.microsoft.com/en-us/rest/api/sql/databasethreatdetectionpolicies/createorupdate

**Comment by phatcher** [comment]
You can achieve this with https://www.terraform.io/docs/providers/azurerm/r/mssql_server_security_alert_policy.html

**Comment by ramioh** [comment]
As @phatcher mentioned, creating a vulnerability assessment resource `azurerm_mssql_server_vulnerability_assessment` implicitly enables Advanced Data Security. It is a workaround though.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
