### ISSUE TITLE
How can I achieve OMS log monitoring config through terraform?

### ISSUE THREAD

**Issue by mkg2** [hashicorp/terraform-provider-azurerm#3388]
How can I achieve below monitoring config through terraform?

* Resource: OMS Workspace

* Condition: Custom log Search
```
ContainerLog 
| where Name contains "test-conatiner"
| where LogEntrySource == "stderr"
| where LogEntry contains "lvl=error"
| project TimeGenerated, LogEntry 
```
* Actions
Send Custom mails to Action group
![image](https://user-images.githubusercontent.com/48181756/57268757-a28d3500-70b7-11e9-9878-3eb474252a33.png)

Thanks,
mkg2

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
