### ISSUE TITLE
MSI Environment variable branding rename

### ISSUE THREAD

**Issue by WodansSon** [hashicorp/terraform-provider-azurerm#3399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As part of the Microsoft rebranding of Managed Service Identity(MSI) to just Managed Identity(MI) we need to expose the new environment variable in terraform core runtime (e.g. ARM_USE_MI and ARM_MI_ENDPOINT) and update all documentation that refers to the technology as MSI and change it to MI. 

### New or Affected Resource(s)
* provider.go
* index.html.markdown
* managed_service_identity.html.markdown
* Other tooling that use this environment variable

**Comment by favoretti** [comment]
@WodansSon still relevant? If not, can we close it?

**Comment by rcskosir** [comment]
:wave: I am going to close this issue as significant time has passed and we have new processes in place for tracking this kind rebranding work, if you feel this issue is the best place to still track this work if it has not completed, we can reopen.
