### ISSUE TITLE
Azure Batch Pool Container Configuration

### ISSUE THREAD

**Issue by casparjespersen** [hashicorp/terraform-provider-azurerm#3411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Batch Pools can be Docker compatible if they have a container configuration supplied to them. Unfortunately, the current Terraform API version does not support this property. It would be a simple task to include this setup.

### New or Affected Resource(s)

* azurerm_batch_pool

### Potential Terraform Configuration

```hcl
resource "azurerm_batch_pool" "test" {
  name                = "testaccpool"
  resource_group_name = "${azurerm_resource_group.test.name}"
  account_name        = "${azurerm_batch_account.test.name}"
  display_name        = "Test Acc Pool Auto"
  vm_size             = "Standard_A1"
  node_agent_sku_id   = "batch.node.ubuntu 16.04"

  storage_image_reference {
    publisher = "microsoft-azure-batch"
    offer     = "ubuntu-server-container"
    sku       = "16-04-lts"
    version   = "latest"
  }

  container_configuration {
    container_image_names = ["ubuntu", "hello-world"]
    container_registries = [
      {
        registry_server = "registry-server-url"
        user_name = "registry-username"
        password = "registry-password"
      }
    ]
  }

}
```

### References

* https://docs.microsoft.com/en-gb/azure/batch/batch-docker-container-workloads
* https://docs.microsoft.com/en-us/python/api/azure-batch/azure.batch.models.containerconfiguration?view=azure-python

**Comment by tshauck** [comment]
There's still work to do on https://github.com/terraform-providers/terraform-provider-azurerm/pull/3311, but once it's merged it'll provide the basic functionality of saying a pool is configured for docker, otherwise the other attributes of the `container_configuration` are optional (e.g. `container_image_names`). Next step would be to add those optional keys.

**Comment by ennui93** [comment]
I took a first stab at adding the container_registries attribute. See [the add_batch_container_configs branch in my fork](https://github.com/terraform-providers/terraform-provider-azurerm/compare/master...ennui93:add_batch_container_configs). However, I'm unable to create a [schema with a list of dictionaries with specific keys](https://github.com/terraform-providers/terraform-provider-azurerm/compare/master...ennui93:add_batch_container_configs#diff-a2732a311d545c75b452cf3d14943880R125).

**Comment by ennui93** [comment]
OK, I did the thing. Please see PR #4072.

I was unable to create a proper block syntax for the elements in the `container_registries` block, even trying to use the `ConfigMode: schema.SchemaConfigModeAttr` workaround described in hashicorp/terraform#20626. Instead, I resorted to a set of maps to hold each of the container registry settings. This has some undesirable side effects such as allowing users to create spurious 'labels' for each of the container registry declarations, as well as overly-aggressive recreation of the pool on updates.

Comments/suggestions on the PR are welcome.

**Comment by ennui93** [comment]
I was able to get this working properly in the end with feedback from @katbyte in PR #4072, which is now merged as a9a98723a4692991604840fe91caf8bfef58c596.

This means that all that is left to complete this issue is adding support for `container_image_names` to `container_configuration`.

**Comment by dprateek1991** [comment]
@ennui93 Any idea by when this feature will be merged. I think we missed a very important feature in terraform by not adding container_image_names. 

I'm actually working on a use case where we need to use Azure Batch Service within ADF to do some data transfer between Azure and AWS and thus realise since now Pools can be docker compatible but no way to pass container_image_names in it. 

Without this feature, how currently its used ?

**Comment by ennui93** [comment]
PRs #3311 & #4702 are both merged and available [in version 1.33.0 of the provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.33.0/CHANGELOG.md) and later.

@tshauck, as I recall, this resource can provision working batch jobs without `container_image_names`. Is this correct? or do we need this key to use containers in Azure Batch service from Terraform?

**Comment by ennui93** [comment]
Initial iteration of the code to add `container_image_names` can be found at [the add_batch_container_image_names branch in my fork](https://github.com/terraform-providers/terraform-provider-azurerm/compare/master...ennui93:add_batch_container_image_names). However, it is failing unit tests with a runtime exception at present. I'll investigate further as I have time.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
