### ISSUE TITLE
azurerm_stream_analytics_function_javascript_udf not detecting multiple parameters

### ISSUE THREAD

**Issue by jungopro** [hashicorp/terraform-provider-azurerm#3412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```console
Terraform v0.11.13
+ provider.azuread v0.3.1
+ provider.azurerm v1.27.1
+ provider.random v2.1.2
+ provider.template v2.1.2
```

### Affected Resource(s)

* `azurerm_stream_analytics_function_javascript_udf`

### Terraform Configuration Files

```hcl
resource "azurerm_stream_analytics_function_javascript_udf" "function_2" {
  name                      = "${var.function_2_name}"
  stream_analytics_job_name = "${azurerm_stream_analytics_job.job.name}"
  resource_group_name       = "${azurerm_stream_analytics_job.job.resource_group_name}"

  script = <<SCRIPT
function main(header, deviceId) {
  if (deviceId) {
      deviceId = deviceId.replace('konnect-', '');
  }

  header.deviceId = deviceId;
  return header;
}
SCRIPT

  input {
    type = "any"
  }

  output {
    type = "record"
  }
}
```

### Expected Behavior

Function should get created with **2** parameters

### Actual Behavior

Function gets created with **1** parameter

### Steps to Reproduce

1. `terraform apply`

In addition to the above, if I simply edit the function post creation and add a blank line and saves, the parameters count automatically gets update to 2. when I re-run `terraform apply`, it reduces the count to 1 again...
Lastly, if I create the function via the portal and not via terraform, the parameters count is set to 2, as it should be

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
