### ISSUE TITLE
Failed to delete public ip address attached to application gateway (when changing from dynamic to static)

### ISSUE THREAD

**Issue by dazwin** [hashicorp/terraform-provider-azurerm#3419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
├── provider.azurerm 1.27.1

### Affected Resource(s)

* `azurerm_public_ip`
* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "gateway-ingress" {
  name                = "gateway-ingress"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.resource_group_location}"
  sku                 = "Standard"
  allocation_method   = "Static"
}

resource "azurerm_application_gateway" "network" {
  name                = "gateway"
  resource_group_name = "${var.resource_group_name}"
  location            = "${var.resource_group_location}"

  sku {
    name     = "WAF_v2"
    tier     = "WAF_v2"
    capacity = 2
  }

  frontend_ip_configuration {
    name                 = "gateway-frontend-ip"
    public_ip_address_id = "${azurerm_public_ip.gateway-ingress.id}"
  }
}
```

### Debug Output

Error: Error applying plan:

1 error(s) occurred:

* azurerm_public_ip.gateway-ingress (destroy): 1 error(s) occurred:

* azurerm_public_ip.gateway-ingress: Error deleting Public IP \"gateway-ingress\" (Resource Group \"#####\"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code=\"PublicIPAddressCannotBeDeleted\" Message=\"Public IP address /subscriptions/#####/resourceGroups/chs-cloud-develop/providers/Microsoft.Network/publicIPAddresses/gateway-ingress can not be deleted since it is still allocated to resource /subscriptions/#####/resourceGroups/chs-cloud-develop/providers/Microsoft.Network/applicationGateways/gateway/frontendIPConfigurations/gateway-frontend-ip.

### Expected Behavior

Successfully detach / reattach a new public IP address ...or... destroy/recreate the application gateway

### Actual Behavior

Failure per above output

### Steps to Reproduce

1. Create an azurerm_application_gateway with a azurerm_public_ip using the default allocation method (allocation_method   = "Dynamic")

2. `terraform apply`

3. Change the allocation method to Static (per above configuration). I also changed the public IP sku from basic to standard and application gateway sku to WAF_v2

4. `terraform apply`

### References

This is possibly a duplicate of...

* #2566

Creating a new issue here in case it's not and must be handled differently.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
