### ISSUE TITLE
AzureADExtension for terraform - Terraform destroy eventually fails

### ISSUE THREAD

**Issue by brijrajsingh** [hashicorp/terraform-provider-azurerm#3429]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_machine_extension.adextenstion`

### Terraform Configuration Files

```hcl

resource "azurerm_virtual_machine_extension" "adextenstion"
{
    name                       = "AADLoginForLinux"
    publisher                  = "Microsoft.Azure.ActiveDirectory.LinuxSSH"
    type                       = "AADLoginForLinux"
    type_handler_version       = "1.0"
    auto_upgrade_minor_version = true
    location                   = "${azurerm_resource_group.example.location}"
    resource_group_name        = "${azurerm_resource_group.example.name}"
    virtual_machine_name       = "${local.virtual_machine_name}"
}
```

### Debug Output
https://gist.github.com/brijrajsingh/aa506f33457dcc3df843ad56f580c232 

### Expected Behavior

Terraform destroy should have deleted all resources including the azure rm extension for Active directory Linux SSH 

### Actual Behavior

The destroy command was stuck at destroying the extension resources for about 10 minutes, eventually, the vm was deleted but not all resources. Destroy ended with the message

``` azurerm_virtual_machine_extension.adextenstion: Code="OperationPreempted" Message="The operation has been preempted by a more recent operation." ```

### Steps to Reproduce

1.  Create an Azure Linux VM with the Azure AD Extension.
2. Teardown using Azure Destroy

### References
1. https://docs.microsoft.com/en-us/azure/virtual-machines/linux/login-using-aad#log-in-to-the-linux-virtual-machine
2. https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
