### ISSUE TITLE
Azure Functions/Webapps User Assigned Identity Support

### ISSUE THREAD

**Issue by JustinGrote** [hashicorp/terraform-provider-azurerm#3495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
User Assigned Identities were implemented in: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1377

Now that preview support is available for Azure Functions and Webapps, the Identity field should allow for UserAssigned in the same way as VMs.

### New or Affected Resource(s)

* azurerm_function_app

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/issues/1377

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
