### ISSUE TITLE
Azure SQL Database Output for Azure Stream Analytics

### ISSUE THREAD

**Issue by OliverRC** [hashicorp/terraform-provider-azurerm#3531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We are terraform'ing our Stream Analytics jobs and one of the outputs is to an Azure SQL Database. Unfortunately right now it is not currently supported but would be a great addition.

### New or Affected Resource(s)

* azurerm_stream_analytics_output_sqldatabase

### References

* https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-sql-output-perf

**Comment by stephybun** [comment]
This was closed by #3567 and released in v1.31.0.
