### ISSUE TITLE
azurerm_monitor_metric_alertrule should support actiongroup

### ISSUE THREAD

**Issue by rhnewtron** [hashicorp/terraform-provider-azurerm#3557]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Monitor allows the usage of action groups to centralize incident forwarding and handling. With action groups, alarms trigger an action group, which then itself triggers e-Mails webhooks etc. 

### New or Affected Resource(s)

* azurerm_monitor_metric_alertrule

Action groups itself can already be used (data) https://www.terraform.io/docs/providers/azurerm/d/monitor_metric_alertrule.html and managed (resource) https://www.terraform.io/docs/providers/azurerm/r/monitor_metric_alertrule.html.

### Potential Terraform Configuration

See https://www.terraform.io/docs/providers/azurerm/r/monitor_metric_alertrule.html

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azurerm_monitor_action_group" "test" {
  name                = "CriticalAlertsAction"
  resource_group_name = "${azurerm_resource_group.test.name}"
  short_name          = "p0action"

  email_receiver {
    name          = "sendtoadmin"
    email_address = "admin@contoso.com"
  }

  email_receiver {
    name          = "sendtodevops"
    email_address = "devops@contoso.com"
  }

  sms_receiver {
    name         = "oncallmsg"
    country_code = "1"
    phone_number = "1231231234"
  }

  webhook_receiver {
    name        = "callmyapiaswell"
    service_uri = "http://example.com/alert"
  }
}

resource "azurerm_monitor_metric_alertrule" "test" {
  name                = "${azurerm_virtual_machine.test.name}-cpu"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  description = "An alert rule to watch the metric Percentage CPU"

  enabled = true

  resource_id = "${azurerm_virtual_machine.test.id}"
  metric_name = "Percentage CPU"
  operator    = "GreaterThan"
  threshold   = 75
  aggregation = "Average"
  period      = "PT5M"

  actiongroup_id = "${azurerm_monitor_action_group.test.id}"
}
```

### References

See https://www.terraform.io/docs/providers/azurerm/r/monitor_metric_alertrule.html
See https://www.terraform.io/docs/providers/azurerm/r/monitor_action_group.html

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
