### ISSUE TITLE
azurerm_client_config rolls state on every apply due to "ID" being a timestamp

### ISSUE THREAD

**Issue by JustinGrote** [hashicorp/terraform-provider-azurerm#3558]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
12.0

### Affected Resource(s)

* `azurerm_client_config`

### Debug Output

![image](https://user-images.githubusercontent.com/15258962/58662605-7728ef00-82df-11e9-9ba9-e11e9b5cb79c.png)

### Expected Behavior
ID should be something that only changes if the client config changes, such as a sha1 hash of the important attributes

### Actual Behavior

ID is a date, and rolls on every refresh/apply, requiring a state update, polluting the state history in systems like Terraform Enterprise, and generating unnecessary state change notifications

### Steps to Reproduce

1. Configure an azurerm_client_config
1. `terraform apply` multiple times. State updates every time. No other resource does this to my knowledge.

### Relevant Code
https://github.com/terraform-providers/terraform-provider-azurerm/blob/195a9c4c96b8498c9f8d15c8908cc5436c7f4988/azurerm/data_source_client_config.go#L63
Change to a sha hash of the clientID+tenantID or something.

**Comment by dcfsc** [comment]
As a workaround I hoped something like
```
data azurerm_client_config current {
  lifecycle {
    ignore_changes = [
      id
    ]
  }
}
```
works, but
```
Data resources do not have lifecycle settings, so a lifecycle block is not allowed.
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
