### ISSUE TITLE
AccRandTimeInt does not produce unique random numbers (on Windows Git Bash)

### ISSUE THREAD

**Issue by mattdot** [hashicorp/terraform-provider-azurerm#3573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_network_gateway_connection`
* testacc

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```
    t.Logf("rand=%d", tf.AccRandTimeInt())
    t.Logf("rand=%d", tf.AccRandTimeInt())
    
    ----- outputs ------- 
    
    data_source_virtual_network_gateway_connection_test.go:14: rand=190531090628781397
    data_source_virtual_network_gateway_connection_test.go:15: rand=190531090628781397
```

### Expected Behavior

Subsequent calls of tf.AccRandTimeInt() should produce different random numbers

### Actual Behavior

Calling `tf.AccRandTimeInt()` in rapid succession returns the same "random" number multiple times. 

### Steps to Reproduce

```
 make testacc TEST=./azurerm TEST=./azurerm/helpers/tf TESTARGS='-run=TestAccRandTimeInt'
```

```
	t.Run("Rand Date int unique", func(t *testing.T) {
		ri := AccRandTimeInt()
		ri2 := AccRandTimeInt()

		if ri == ri2 {
			t.Fatalf("AccRandTimeInt returned the same value on subsequent calls (%d, %d)", ri, ri2)
		}
	})
```

### Important Factoids

This only happens on Windows Git Bash (MINGW64).  It does not happen on Windows/WSL, Mac, Linux, etc.

### References

* #0000

**Comment by draggeta** [comment]
Oh, I thought I was the only one. I've had this exact same issue in one of my PR's. However, it happened for me in PowerShell and CMD. Decided then to test it out in a Linux VM and didn't have any issues there.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
