### ISSUE TITLE
Issue with subscription id format when setting security centre log analytics workspace.

### ISSUE THREAD

**Issue by odee30** [hashicorp/terraform-provider-azurerm#3604]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: v0.11.11
AzureRM Provider version: 1.29.0

### Affected Resource(s)

azurerm_security_center_workspace

### Terraform Configuration Files

```hcl
resource "azurerm_security_center_workspace" "sc_workspace" {
  scope             = "/subscriptions/00000000-0000-0000-0000-000000000000"
  workspace_id = "${data.terraform_remote_state.monitoring_state.workspace_id}"
}
```

### Debug Output

https://gist.github.com/odee30/574ac2413e94cdfabf4c263265ac10c2

### Expected Behavior

Security Centre should be linked to the specified Log Analytics Workspace.

### Actual Behavior

Apply fails to complete with the following error:

`azurerm_security_center_workspace.sc_workspace: Error creating Security Center Workspace: security.WorkspaceSettingsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidInput" Message="Invalid scope was provided - scope ''/subscriptions/00000000-0000-0000-0000-000000000000''. Please provide the following scope: '/subscriptions/{subscriptionId}'"`

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

- The pricing tier for the subscription is set to Standard as is required for setting the Log Analytics Workspace.
- The account running the deployment has owner role over the subscription.
- Copying the scope string and using with the PowerShell `Set-AzSecurityWorkspaceSetting` cmdlet works as expected.

### References

https://docs.microsoft.com/en-us/azure/security-center/security-center-powershell-onboarding
https://www.terraform.io/docs/providers/azurerm/r/security_center_workspace.html

* #0000

**Comment by DanGiffen** [comment]
Terraform v0.12.20
+ provider.azurerm v1.43.0

I found I had the same error using this syntax with a variable value `"scope = "subscriptions/${var.AzSharedSubID}"`. 
After adding a preceding "/" it worked as expected i.e
`scope = "/subscriptions/${var.AzSharedSubID}"`

**Comment by Kumoservices** [comment]
Hello

I have the same issue too with this code : 
Azurerm : 2.11.0
Terraform : 0.12.24

variable "security_center_subscription" {
  description = "List of subscriptions this log analytics should collect data for."
  type        = list(string)
  default     = [ "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx",
                  "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx",
                  "xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx"]
}

# Manages the subscription's Security Center Workspace.
resource "azurerm_security_center_workspace" "default" {
  count        = length(var.security_center_subscription)
  scope        = "/subscriptions/${element(var.security_center_subscription, count.index)}"
  workspace_id = azurerm_log_analytics_workspace.default.id
}

The error message is :
Error: Error creating Security Center Workspace: security.WorkspaceSettingsClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidInput" Message="Invalid scope was provided - scope '/subscriptions/xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxxx'. Please provide the following scope: '/subscriptions/{subscriptionId}'"

  on log_analytics.tf line 57, in resource "azurerm_security_center_workspace" "default":
  57: resource "azurerm_security_center_workspace" "default" {

Thanks

**Comment by petr-x** [comment]
Even hardcoded value throw the same error. Wondering if anyone found a solution.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
