### ISSUE TITLE
terraform import data is not liked by terraform plan

### ISSUE THREAD

**Issue by wardcomm** [hashicorp/terraform-provider-azurerm#3615]
terraform import data is not like by terraform plan
I did a terraform import of azurerm_route_table [it worked]
I did a terraform show and see import info
I then added ”next_hop_in_ip_address” to my terraform code and then did a terraform plan.
If I have data like:
hop_in_ip_address = "192.168.1.1" {real ip not used in this example}
[it fails]
If I remove hop_in_ip_address like comment out line
 `` # hop_in_ip_address or I use hop_in_ip_address = " " 
Terraform plan works
I think this is a bug in that terraform import has working data and terraform plan should except the data that terraform show is showing.

Expected outcome:
Adding IaC  hop_in_ip_address = "192.168.1.1" with real data, terraform plan should have no problem with data.

**Comment by draggeta** [comment]
@wardcomm I don't know if it is still an issue, but you can use the next hop IP address only when specifying `VirtualAppliance` as the `next_hop_type`. If you use it anywhere else, it fails as it's not allowed by Azure.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
