### ISSUE TITLE
Split out DNS configuration for vnet

### ISSUE THREAD

**Issue by davidobrien1985** [hashicorp/terraform-provider-azurerm#3643]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Vnet DNS configuration is currently part of the vnet resource which ends up causing weird scenarios where one needs to "go back" to the vnet resource after another resource was deployed and configure the vnet DNS entries. This is not possible today with all being part of `azurerm_virtual_network`

### New or Affected Resource(s)

* azurerm_virtual_network

**Comment by jarmbruster74** [comment]
I just ran into what I think was a version of this issue.  Trying to set up my own DNS resolver I build a VM with terraform, connect it to an interface (that is dependent on a subnet, dependent on a vnet).  Then I want to add the DNS setting to the VNET - I now have a cyclical dependency that I'm having trouble breaking out of with the current set up.

Comparing to how I solved this issue in AWS I see that the AWS provider has separate resources, for VPC, DHCP options and VPC/DHCP Options Association.  Something similar here - DNS options, DNS Options association could alleviate this cyclical resource dependency perhaps?

**Comment by jarmbruster74** [comment]
An example of the workaround I implemented using Azure CLI and Bash.  I imagine the provider could essentially implement a vnet_dns_options resource that would perform this same API call.

data "azurerm_subscription" "current" {
}

resource "null_resource" "set_dns" {
  triggers = {
    dns_servers = join(" ", local.dns_servers)
    vnet_name = module.vnet.vnet_name
  }

  provisioner "local-exec" {
    command = <<EOT
    az account set --subscription ${data.azurerm_subscription.current.subscription_id}
    tries=0
    while [ $tries -lt 100 ]
      do
      ((tries=tries+1))
      echo $tries ": Update DNS Settings with retries"
      out=$(az network vnet update --resource-group ${module.vnet.rg.name} --name ${module.vnet.vnet_name} --dns-servers ${join(" ", local.dns_servers)} 2>&1 >/dev/null)
      if [ $? -eq 0 ]
      then
        echo "DNS Set Successfully"
        break
      elif [[ $out == *retryable* ]]
      then
        echo "Retrying..."
        sleep 180
      else
        echo "Non Retryable Error: " $out
        break
      fi
    done
EOT
  }
}

**Comment by poddm** [comment]
Running into Terraform Cycle errors when trying to use this with `azure_firewall`.
https://docs.microsoft.com/en-us/azure/firewall/dns-settings#configure-virtual-network-dns-servers

```hcl
resource "azurerm_virtual_network" "example" {
  name                = "${var.name}-vnet"
  location            = var.location
  resource_group_name = var.resource_group_name
  tags                = var.tags

  address_space       = var.address_space
  dns_servers         = azurerm_firewall.example.ip_configuration[0].private_ip_address

}

resource "azurerm_firewall" "example" {
  name                = "example-fw"
  location            = var.location
  resource_group_name = var.resource_group_name

  dns_proxy = true
  
  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.this.id
    public_ip_address_id = azurerm_public_ip.this.id
  }
}
```

**Comment by Tailzip** [comment]
We're facing the same issue described by @poddm above when creating a VNET and a firewall. Having a dedicated resource to configure DHCP options for a VNET seems to be a good option.

**Comment by AurimasNav** [comment]
> ### Community Note
> * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
> * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
> * If you are interested in working on this issue or have submitted a pull request, please leave a comment
> 
> ### Description
> Vnet DNS configuration is currently part of the vnet resource which ends up causing weird scenarios where one needs to "go back" to the vnet resource after another resource was deployed and configure the vnet DNS entries. This is not possible today with all being part of `azurerm_virtual_network`
> 
> ### New or Affected Resource(s)
> * azurerm_virtual_network

Is this the solution?
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_dns_servers

**Comment by rcskosir** [comment]
@davidobrien1985 Thank you for opening this issue, I am going to mark it closed with: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_network_dns_servers
If that does not solve the weird scenarios you mentioned in your issue description, please let us know here, or by opening a new issue with additional details, thanks!
