### ISSUE TITLE
Provider produced inconsistent final plan on azurerm_firewall_network_rule_collection, after subsequent script run

### ISSUE THREAD

**Issue by urker** [hashicorp/terraform-provider-azurerm#3664]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.0 - 0.12.2

### Affected Resource(s)

* `azurerm_firewall_network_rule_collection`

### Terraform Configuration Files

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "${var.cluster_name}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.k8s_rg.name}"
  dns_prefix          = "${var.dns_prefix}"

  addon_profile {
    oms_agent {
      enabled = "true"
      log_analytics_workspace_id = "***"
    }
  }

  agent_pool_profile {
    name            = "default"
    count           = "${var.agent_count}"
    vm_size         = "${var.size}"
    os_type         = "${var.type}"
    os_disk_size_gb = 30
    vnet_subnet_id  = "${azurerm_subnet.subnet.id}"
  }

  network_profile {
    network_plugin       = "azure"
    service_cidr         = "${var.service_cidr}"
    docker_bridge_cidr   = "${var.docker_bridge_cidr}"
    dns_service_ip       = "${var.dns_service_ip}"
  }

  service_principal {
    client_id     = "${data.azurerm_key_vault_secret.client_id.value}"
    client_secret = "${data.azurerm_key_vault_secret.client_secret.value}"
  }

  provisioner "local-exec" {
    command = <<EOF
      rm endpoint
      az aks get-credentials --name "${var.cluster_name}" --resource-group "${azurerm_resource_group.k8s_rg.name}" --overwrite-existing
      kubectl describe service kubernetes | grep Endpoints | awk -F ":" '/1/ {gsub(/ /, "", $2); print $2}' >> endpoint
      kubectl apply -f yaml-files/storageClass.yaml
   EOF
  }
}

data "local_file" "endpoint" {
    filename = "./endpoint"
    depends_on = ["azurerm_kubernetes_cluster.k8s"]
}

resource "null_resource" "cluster" {
  triggers = {
    cluster_ip = "${trimspace(data.local_file.endpoint.content)}"
  }
  depends_on = ["azurerm_kubernetes_cluster.k8s"]
}

resource "azurerm_firewall_network_rule_collection" "az_firewall_network_rules" {
  name                = "az_firewall_network_rule_collection"
  azure_firewall_name = "${azurerm_firewall.firewall.name}"
  resource_group_name = "${azurerm_resource_group.vnet_rg.name}"
  priority            = 100
  action              = "Allow"

  rule {
    name = "k8stcp"

    source_addresses = "${var.sourceAddresses}"

    destination_ports = "${var.destinationTcpPorts}"

    destination_addresses = [
        "${null_resource.cluster.triggers.cluster_ip}",
    ]

    protocols = [
      "TCP",
    ]
  }

  rule {
    name = "k8sudp"

    source_addresses = "${var.sourceAddresses}"

    destination_ports = "${var.destinationUdpPorts}"

    destination_addresses = [
      "${null_resource.cluster.triggers.cluster_ip}",
    ]

    protocols = [
      "UDP",
    ]
  }

  rule {
    name = "cifsudp"

    source_addresses = "${var.sourceAddresses}"

    destination_ports = "${var.destinationCifsUdpPorts}"

    destination_addresses = [
      "Storage",
    ]

    protocols = [
      "UDP",
    ]
  }

  rule {
    name = "cifstcp"

    source_addresses = "${var.sourceAddresses}"

    destination_ports = "${var.destinationCifsTcpPorts}"

    destination_addresses = [
      "Storage",
    ]

    protocols = [
      "TCP",
    ]
  }
}

### Expected Behavior

When running apply for the first time script is running fine without any issues , all resources are created correctly , I would expect that script will run without issues in subsequent runs as well 

### Actual Behavior

If I run same script without any changes again I am getting this output 

Error: Provider produced inconsistent final plan

When expanding the plan for
azurerm_firewall_network_rule_collection.az_firewall_network_rules to include
new values learned so far during apply, provider "azurerm" produced an invalid
new value for .rule: planned set element
cty.ObjectVal(map[string]cty.Value{"description":cty.NullVal(cty.String),
"destination_addresses":cty.SetVal([]cty.Value{cty.StringVal("Storage")}),
"destination_ports":cty.SetVal([]cty.Value{cty.StringVal("***"),
cty.StringVal("***")}), "name":cty.StringVal("cifsudp"),
"protocols":cty.SetVal([]cty.Value{cty.StringVal("UDP")}),
"source_addresses":cty.SetVal([]cty.Value{cty.StringVal("*.*.*.*/*")})})
does not correlate with any element in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Error: Provider produced inconsistent final plan

When expanding the plan for
azurerm_firewall_network_rule_collection.az_firewall_network_rules to include
new values learned so far during apply, provider "azurerm" produced an invalid
new value for .rule: planned set element
cty.ObjectVal(map[string]cty.Value{"description":cty.NullVal(cty.String),
"destination_addresses":cty.SetVal([]cty.Value{cty.StringVal("Storage")}),
"destination_ports":cty.SetVal([]cty.Value{cty.StringVal("***"),
cty.StringVal("***")}), "name":cty.StringVal("cifstcp"),
"protocols":cty.SetVal([]cty.Value{cty.StringVal("TCP")}),
"source_addresses":cty.SetVal([]cty.Value{cty.StringVal("*.*.*.*/*")})})
does not correlate with any element in actual.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### Important Factoids

I have to get kubernetes api public  ip address to setup firewall rule , however kubernetes provider is not having this information , so I have to run provisioner on kuberneters resource to write this into a file and then read this information from the file in data block . This reading is done every time so it forcing update of network rules . I tried to use triggers with null resources but this is always being kicked off , so I can't run script after finishes successfully  
for the firs time .

**Comment by sraddhananda** [comment]
Interesting that it didn't get any traction even after close to a year.
I landed into the same situation and after some digging, I suspect this issue is to do with the rule schema "TypeSet" which is an unordered collection and all the major resource providers are implementing hash on these blocks. In Azure it is subnet block in Vnet resource & rules in firewall rule collection. In Aws it is Ingress/Egress for network ACL's
