### ISSUE TITLE
azurerm_virtual_machine data insufficient

### ISSUE THREAD

**Issue by bcline760** [hashicorp/terraform-provider-azurerm#3684]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

Is there any plans to flush out the virtual machine data resource? Right now it's, well, really useless. :/. According to the [documentation](https://www.terraform.io/docs/providers/azurerm/d/virtual_machine.html), it just returns the ID (and the name too, but that's not documented). I'd like it to see it return the IP addresses (public and private) at least.

### New or Affected Resource(s)

* Data Source: `azurerm_virtual_machine`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by n2qz** [comment]
I just hacked together some ugly and slow code to enumerate all possible NICs with azurerm_resources, and then search for NICs matching particular virtual_machine_id's.  Having the azurerm_virtual_machine data source directly return the ip_configurations would be a big win.

**Comment by nrbhutada** [comment]
High time terraform need an update to provide few important VM attributes and list of NICs should be on top.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
