### ISSUE TITLE
Change Azure Application Gateway SKU Conversion from v1 to v2 to Destroy and Recreate

### ISSUE THREAD

**Issue by jstewart612** [hashicorp/terraform-provider-azurerm#3713]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.11.14 and 1.30.1

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Destroy and recreate without me manually having to do so.

### Actual Behavior

```azurerm_application_gateway.ag-envoy-aag: Error Creating/Updating Application Gateway "dve2-aag-ci-ag-envoy" (Resource Group "Linux"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayCannotChangeSkuToAndFromV2Sku" Message="Application Gateway /subscriptions/xxx/resourceGroups/Linux/providers/Microsoft.Network/applicationGateways/dve2-aag-ci-ag-envoy with SKU tier Standard_v2 cannot be changed to SKU tier Standard. Please create a new gateway with the required SKU tier." Details=[]```

### Steps to Reproduce

1. Change your azurerm_application_gateway from any non-v2 SKU to a V2 SKU
2. Apply your new tf and watch it break.

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
