### ISSUE TITLE
Improve azurerm_network_interface data source

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#3736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi, thanks for all your hard work. I'd like to issue this request - I got caught somewhat by surprise this doesn't exist since the AWS provider has it...

An existing internal Network Interface without public IP can only be found when the name and the resource group are available:

```tf
data "azurerm_network_interface" "test" {
  name                = "acctest-nic"
  resource_group_name = "networking"
}
```
However, this is too restricitive. To manage Network interfaces independently from virtual machines, I would like to create them in a separate TF script, and query for them in another one.

### New or Affected Resource(s)

I could envision that you build another Data Source ```azurerm_network_interfaces``` and add filter capabilites e.g. something like

```tf
data "azurerm_network_interfaces"  "nics" {
  filter {
      name = "tag:Function"
      values = ["webserver-nic"]    
  }
  resource_group_name = "networking"
}
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
