### ISSUE TITLE
Make DNS Records properties of DNS Zones

### ISSUE THREAD

**Issue by sylr** [hashicorp/terraform-provider-azurerm#3759]
### Description

It would be nice if Azure DNS records would be properties of Azure DNS zone terraform objects.

I.E. 

```
resource "azurerm_dns_zone" "dev-xxxx-com" {
  name                = "dev.xxxx.com"
  resource_group_name = "dns-euw-dev-rg"
  zone_type           = "Public"

  ns_record {
    name      = "@"
    ttl       = "172800"
    records   = ["ns1-03.azure-dns.com.","ns2-03.azure-dns.net.","ns3-03.azure-dns.org.","ns4-03.azure-dns.info."]
  }

  ns_record {
    name      = "xxxx"
    ttl       = "172800"
    records   = ["ns1-04.azure-dns.com.","ns2-04.azure-dns.net.","ns3-04.azure-dns.org.","ns4-04.azure-dns.info."]
  }

  a_record {
    ...
  }

  cname_record {
    ...
  }  
}
```

Using this would remove any records on Azure side that is not registered in terraform.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
