### ISSUE TITLE
azurerm_sql_virtual_network_rule multiple rules

### ISSUE THREAD

**Issue by hakeem86** [hashicorp/terraform-provider-azurerm#3790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I think it would be useful if it was possible to add multiple rules to azurerm_sql_virtual_network_rule

### New or Affected Resource(s)

* azurerm_sql_virtual_network_rule

### Potential Terraform Configuration

```hcl

resource "azurerm_resource_group" "test" {
  name     = "acceptanceTestResourceGroup1"
  location = "West US"
}

resource "azurerm_sql_server" "test" {
  name                         = "mysqlserver"
  resource_group_name          = "${azurerm_resource_group.test.name}"
  location                     = "West US"
  version                      = "12.0"
  administrator_login          = "4dm1n157r470r"
  administrator_login_password = "4-v3ry-53cr37-p455w0rd"
}

resource "azurerm_sql_firewall_rule" "test" {
  resource_group_name = "${azurerm_resource_group.test.name}"
  rules = {
    "Allow access to Azure services" = ["0.0.0.0", "0.0.0.0"]
    "Rule name 01"                   = ["10.0.17.62", "10.0.17.62"]
    "Rule name 02"                   = ["10.0.18.62", "10.0.18.62"]
  }
}


```

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
