### ISSUE TITLE
Referencing nonexisting resource in app settings causes all app settings to be reset

### ISSUE THREAD

**Issue by tomasaschan** [hashicorp/terraform-provider-azurerm#3861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that `app_settings` are being reset if there is one app setting that refers to a resource that doesn't yet exist (but will after the deploy). This makes it difficult to apply incremental changes to an existing infrastructure - we have to take care to create all new resources (using `terraform apply -target ...`) before we do the general `terraform apply` to set new app settings. Doing this manually is cumbersome and error-prone; doing it automatically seems daunting...

Here's an example configuration that exhibits the behavior. First, create the following resources:

```hcl
provider "azurerm" {}

resource "azurerm_resource_group" "rg" {
  name     = "terraform-repro"
  location = "westeurope"
}

resource "azurerm_app_service_plan" "svcplan" {
  name                = "svcplan"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "${azurerm_resource_group.rg.location}"

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "app" {
  name                = "tf-azurerm-appsettings-repro"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "${azurerm_resource_group.rg.location}"
  app_service_plan_id = "${azurerm_app_service_plan.svcplan.id}"

  app_settings = {
    "foo"         = "bar"
    "svc_plan_id" = "${azurerm_app_service_plan.svcplan.id}"
  }
}
```
When those have been created successfully, add the following resource
```hcl

resource "azurerm_application_insights" "insights" {
  name                = "appinsights-repro"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "${azurerm_resource_group.rg.location}"
  application_type    = "Web"
}
```
and update the `app_settings` node on the app service with a new setting:
```hcl
  app_settings = {
    "foo"             = "bar"
    "svc_plan_id"     = "${azurerm_app_service_plan.svcplan.id}"
    "appinsights_key" = "${azurerm_application_insights.insights.instrumentation_key}"
  }
```

I expect `terraform plan` to show the following actions:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_app_service.app
      app_settings.%:               "" => <computed>
      app_settings.appinsights_key: "" => <computed>

  + azurerm_application_insights.insights
      id:                       <computed>
      app_id:                   <computed>
      application_type:         "Web"
      instrumentation_key:      <computed>
      location:                 "westeurope"
      name:                     "appinsights-repro"
      resource_group_name:      "terraform-repro"
      tags.%:                   <computed>
```
but in fact it shows these:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_app_service.app
      app_settings.%:           "" => <computed>
      app_settings.foo:         "bar" => ""
      app_settings.svc_plan_id: "/subscriptions/f8a3118e-27fc-45a8-8e34-19ce4ccb18b9/resourceGroups/terraform-repro/providers/Microsoft.Web/serverfarms/svcplan" => ""

  + azurerm_application_insights.insights
      id:                       <computed>
      app_id:                   <computed>
      application_type:         "Web"
      instrumentation_key:      <computed>
      location:                 "westeurope"
      name:                     "appinsights-repro"
      resource_group_name:      "terraform-repro"
      tags.%:                   <computed>
``` 
Notice that not only is the new setting `appinsights_key` not initialized; but _all the other settings are reset_! If you run `terraform apply` (and confirm the application), and then run `terraform plan` again, you'll get a plan suggesting to set _all_ app settings, including `appinsights_key`.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
