### ISSUE TITLE
azurerm_storage_queue.id returns queue URL instead of resource ID

### ISSUE THREAD

**Issue by jjgrayston** [hashicorp/terraform-provider-azurerm#3866]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_queue`

### Terraform Configuration Files

```hcl
resource "azurerm_role_assignment" "role_assignment_storage_queue" {
  scope                = "${azurerm_storage_queue.storage_queue.id}" 
  role_definition_name = "Storage Queue Data Message Sender"
  principal_id         = "${azuread_service_principal.service_principal.id}"
}
```

### Output

`terraform apply` outputs following:
```
+ azurerm_role_assignment.role_assignment_storage_queue
      id:                                                      <computed>
      name:                                                    <computed>
      principal_id:                                            "xxxxxxxx"
      role_definition_name:                                    "Storage Queue Data Message Sender"
      scope:                                                   "https://xxx.queue.core.windows.net/xxxxx"
```
result is the following error:
```Error: Error applying plan:

1 error(s) occurred:

* azurerm_role_assignment.role_assignment_storage_queue: 1 error(s) occurred:

* azurerm_role_assignment.role_assignment_storage_queue: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="MissingSubscription" Message="The request did not have a subscription or a valid tenant level resource provider."```

**Comment by jjgrayston** [comment]
Provider details:

Terraform v0.11.13
+ provider.azuread v0.3.1

**Comment by chpspiir** [comment]
I have a concrete use case for this:

Say I want to create a `azure_monitor_metric_alert` for a queue. I would have to construct the resource ID manually like this:

```
resource "azurerm_monitor_metric_alert" "x" {
  name                = "x"
  resource_group_name = "x"
  scopes              = ["${azurerm_storage_account.my_storage.id}/queueServices/${azurerm_storage_queue.my_queue.name}"] # <---- This is tedious
  description         = "No messages queued  for the past hour. Has scheduler stopped working?"
  window_size         = "PT1H" # 1H is minimum for queues

  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts/queueServices"
    metric_name      = "QueueMessageCount"
    aggregation      = "Average"
    operator         = "Equals"
    threshold        = 0
  }

  action {
    action_group_id = x
  }
}
```

**Comment by chpspiir** [comment]
Judging by https://github.com/terraform-providers/terraform-provider-azurerm/blob/8d3416a921d4ae769bf38bf8a159001869785d6c/vendor/github.com/tombuildsstuff/giovanni/storage/2018-11-09/queue/queues/resource_id.go#L25, and the API docs for the queue, its doesn't seem like this data is easily available.

If anyone has a suggested solution, i'll gladly volunteer to do the implementation

**Comment by tombuildsstuff** [comment]
@chpspiir unfortunately this information isn't easily available via the Data Plane API. Whilst it is available via the Resource Manager API unfortunately this only supports AzureAD authentication, which requires an additional Authorization which hasn't been retroactively added to existing roles by Microsoft (e.g. `Storage Data Reader`) - when new `Contributor` roles get this by default.

For the moment it's probably safe to build this up within the resource however - since we have to know the Storage Account ID/URI to be able to access the key; which should also work regardless of the users permissions, since we don't need to interact with this URI. From Terraform's side we could look to expose these as an additional property (e.g. `arm_resource_id`) rather than updating the `id` field; since the ARM ID isn't the primary identifier here.

Hope that helps :)

**Comment by chpspiir** [comment]
@tombuildsstuff Just to double check: What you're saying is that it is should be alright to construct the ID statically and expose it as `arm_resource_id` right?

I think that must be the next best solution if the data is not readily available via the API.

I'll try and take a stab at it in the coming days. Probably won't get it right the first time, but then I'll learn something :)

**Comment by chpspiir** [comment]
Or are you saying that it should be fine to construct the ID in my own terraform code?

**Comment by tombuildsstuff** [comment]
@chpspiir it should be fine to infer it in this instance, since we're templating:

```
{storageAccountId}/queueServices/{queueName}
```

(since we're obtaining `storageAccountId` anyway 👍

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
