### ISSUE TITLE
Changing application gateway frontend IP is not supported

### ISSUE THREAD

**Issue by ByteCommander** [hashicorp/terraform-provider-azurerm#3883]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.3
+ provider.azurerm v1.30.1
+ provider.null v2.1.2

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
# data source about manually created static public IP
data "azurerm_public_ip" "agw" {
  name                = "${var.agw-public-ip-name}"
  resource_group_name = "${var.agw-public-ip-rg}"
}

resource "azurerm_application_gateway" "agw" {
  # ...
  name = "test-monitoring-agw"
  resource_group_name = "test-infra-rg"

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 2
  }

  frontend_ip_configuration {
    name                 = "test-monitoring-agw-frontend-ip"
    public_ip_address_id = "${data.azurerm_public_ip.agw.id}"
  }
```
### Expected Behavior

When we change `var.agw-public-ip-name` to the name of a different, manually created public IP, we'd expect Terraform to update the application gateway accordingly and assign it the new public IP, replacing its current one.

### Actual Behavior

In `terraform apply`:
```
Error: Error Creating/Updating Application Gateway "test-monitoring-agw" (Resource Group "test-infra-rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewayFrontendIpPublicIpAddressCannotBeChanged" Message="PublicIPAddress property of FrontendIpConfiguration /subscriptions/xxxxxf/resourceGroups/test-infra-rg/providers/Microsoft.Network/applicationGateways/test-monitoring-agw/frontendIPConfigurations/test-monitoring-agw-frontend-ip cannot be changed." Details=[]

  on ....../agw.tf line 13, in resource "azurerm_application_gateway" "agw":
  13: resource "azurerm_application_gateway" "agw" {
```
The application gateway frontend IP configuration seemingly can not be changed through the Azure API, but destroying and recreating the app gateway is required. Terraform doesn't do that though but instead throws this error message.

Tainting the app gateway resource to force-recreate it solves the problem.

### Steps to Reproduce

1. Create an app gateway in Azure with a public frontend ip using terraform.
2. Try to change the frontend ip to a different one and `terraform apply`.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
