### ISSUE TITLE
Ignore changes for Application gateway not work

### ISSUE THREAD

**Issue by MelleD** [hashicorp/terraform-provider-azurerm#3903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform: 0.12.4
provider: 1.31.0

### Affected Resource(s)

```
resource "azurerm_application_gateway" "AppGateway"
```

### Terraform Configuration Files

```
resource "azurerm_application_gateway" "AppGateway" {
  name                = var.name
  resource_group_name = data.azurerm_resource_group.ResourceGroup.name
  location            = data.azurerm_resource_group.ResourceGroup.location

  ssl_certificate {
    name     = var.ssl_certificate_name
    data     = var.ssl_certificate_file
    password = var.ssl_certificate_password
  }

  lifecycle {
    ignore_changes = [
      ssl_certificate
    ]
  }
}

```

### Debug Output

```
Error Creating/Updating Application Gateway "gw" (Resource Group "rg"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ApplicationGatewaySslCertificatePasswordIncorrect" Message="Password specified for certificate /subscriptions/111/resourceGroups/rg/providers/Microsoft.Network/applicationGateways/gw/sslCertificates/certifact is incorrect." Details=[][0m
```

### Expected Behavior

The ssl certificate from the gateway should not be changed

### Actual Behavior

The ssl certificate is trying to change

### Steps to Reproduce

1. Upload a new ssl certfiact e.g. with the azure portal for a gateway
2. terraform apply

**Comment by Dmitry1987** [comment]
well it never knows if the data in your cert file is the same like last time or not, maybe this is the problem? 
I am trying to figure out what kind of password this setting needs, my cert has no password but it is a required field in Azure

**Comment by devopsewb** [comment]
Im stuck here too. Any updates to this request would be appreciated greatly!

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
