### ISSUE TITLE
Support for additional fields in azurerm_traffic_manager_profile monitor_config

### ISSUE THREAD

**Issue by Leon99** [hashicorp/terraform-provider-azurerm#3905]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There are a few fields that can be configured through the portal but not via Terraform:

![image](https://user-images.githubusercontent.com/6840381/61675729-deda4400-ad3c-11e9-8d18-741558f5aa90.png)

**Expected Status Code Ranges** is especially important since redirect codes are not respected by the monitor and require explicit configuration to be supported.
### New or Affected Resource(s)

* azurerm_traffic_manager_profile

**Comment by ukphillips** [comment]
Really looking for the feature - without it the only option is to ensure all endpoints support a probe endpoint with a 200 response code.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
