### ISSUE TITLE
Feature Request: Subnets defined in-line within the Virtual Network resource doesn't support all parameters

### ISSUE THREAD

**Issue by JamesDLD** [hashicorp/terraform-provider-azurerm#3917]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Subnets defined in-line within the Virtual Network resource doesn't support all parameters that are available in the standalone Subnet resource.

Subnets defined in-line within the Virtual Network resource support -->

- name
- address_prefix 
- **security_group** 

Subnet defined in the standalone Subnet resource support -->

- name 
- resource_group_name 
- virtual_network_name 
- address_prefix
- network_security_group_id 
- **route_table_id**
- **service_endpoints**
- **delegation**
- **service_delegation**

### New or Affected Resource(s)

* azurerm_virtual_network

### Potential Terraform Configuration

```hcl

resource "azurerm_resource_group" "test" {
  name     = "acceptanceTestResourceGroup1"
  location = "West US"
}

resource "azurerm_network_security_group" "test" {
  name                = "acceptanceTestSecurityGroup1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_route_table" "test" {
  name                          = "acceptanceTestRouteTable"
  location                      = "${azurerm_resource_group.test.location}"
  resource_group_name           = "${azurerm_resource_group.test.name}"
  disable_bgp_route_propagation = false

  route {
    name           = "route1"
    address_prefix = "10.1.0.0/16"
    next_hop_type  = "vnetlocal"
  }

  tags = {
    environment = "Production"
  }
}

resource "azurerm_ddos_protection_plan" "test" {
  name                = "ddospplan1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_virtual_network" "test" {
  name                = "virtualNetwork1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  address_space       = ["10.0.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]

  ddos_protection_plan {
    id     = "${azurerm_ddos_protection_plan.test.id}"
    enable = true
  }

  subnet {
    name              = "subnet1"
    address_prefix    = "10.0.1.0/24"
    route_table_id    = azurerm_route_table.test.id
    service_endpoints = ["Microsoft.Sql", "Microsoft.Storage"]
    delegation {
      name = "acctestdelegation"

      service_delegation {
        name    = "Microsoft.ContainerInstance/containerGroups"
        actions = ["Microsoft.Network/virtualNetworks/subnets/action"]
      }
    }
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.2.0/24"
    security_group = azurerm_network_security_group.test.id
  }

  tags = {
    environment = "Production"
  }
}

```

### References

azurerm_subnet : https://www.terraform.io/docs/providers/azurerm/r/subnet.html
azurerm_virtual_network : https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html

**Comment by tradosh** [comment]
the subnet for address_prefix should accept IPv4 and IPv6 values instead of just one value in here

**Comment by jtracey93** [comment]
I can see in the azurerm_subnet resource source code that support for "address_prefix" will be removed in the next major release and therefore a push towards "address_prefixes" (what we need for the above issue that @tradosh mentioned/created above) will be required in the subnet & VNET resources for Terraform. 

Is there an ETA on this being completed? As this also could help with #9022 in some scenarios, especially @tradosh's above 😃

**Comment by wwasher3** [comment]
Sorry to ask for an ETA but looks as through there is nothing new on this issue for quite a while and was interested in getting an update/ETA.
Thanks.

**Comment by gettek** [comment]
Hi @tombuildsstuff 

Can't remember if these are automatically set during association but is there also scope for including the below **Private Link Endpoints** or **Private Link Services** flags as available in the standalone subnet resource? Thanks!

- `enforce_private_link_endpoint_network_policies`
- `azurerm_subnet_network_security_group_association`

**Comment by robertbrandso** [comment]
I did a workaround using `azapi_resource`. In my case I had an Azure Policy denying any subnet creation without a NSG attached, and I needed to create a subnet with delegation. The below solution is working great.

You can get the subnet ID from `azapi_resource.subnet.id`.

```hcl
# Create virtual network
resource "azurerm_virtual_network" "example" {
  name                = "vnet-example-lab"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  address_space = ["10.0.0.0/24"]
}

# Create NSG
resource "azurerm_network_security_group" "example" {
  name                = "nsg-example-lab"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

# Create subnet
resource "azapi_resource" "subnet" {
  type      = "Microsoft.Network/virtualNetworks/subnets@2022-07-01"
  name      = "snet-example-lab"
  parent_id = azurerm_virtual_network.example.id

  body = jsonencode({
    properties = {

      # List of address prefixes in subnet
      addressPrefixes = ["10.0.0.0/28"]

      # Service delegations
      delegations = [
        {
          name = "delegation"
          properties = {
            serviceName = "Microsoft.ContainerInstance/containerGroups"
          }
        }
      ]

      # Attach to NSG
      networkSecurityGroup = {
        id = azurerm_network_security_group.example.id
      }
    }
  })
}
```

**Comment by haflidif** [comment]
As I also reference here in this comment: https://github.com/hashicorp/terraform-provider-azurerm/issues/9022#issuecomment-1760322330

Here is another great workaround to mitigate the policy issue, I created a terraform module that uses the [`Azure/azapi`](https://registry.terraform.io/providers/Azure/azapi/latest/docs) resource to be able to create subnets that support delegation, service endpoints, as well as use both existing NSG and Route Tables, + is also able to create NSG and Route Table in one go,

It should help until an official resolution within `azurerm` is in place.

Terraform Registry: [haflidif/alz-subnet/azurerm](https://registry.terraform.io/modules/haflidif/alz-subnet/azurerm/latest)
Github Repo: [terraform-azurerm-alz-subnet](https://github.com/haflidif/terraform-azurerm-alz-subnet)

**Comment by fabianjucker-swissgrid** [comment]
This would be very helpful since currently Azure Container Apps only support subnets with `addressPrefix` instead of `addressPrefixes` (and only the in-line subnet has `addressPrefix`), see https://github.com/microsoft/azure-container-apps/issues/786

**Comment by haflidif** [comment]
I see this is missing from release [v3.112.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.112.0) will this maybe not be released until [v4.0.0](https://github.com/hashicorp/terraform-provider-azurerm/milestone/172) ?

**Comment by stephybun** [comment]
@haflidif the functionality is there but it will only become available when v4.0.0 goes out.

**Comment by haflidif** [comment]
> @haflidif the functionality is there but it will only become available when v4.0.0 goes out.

Ahh, thank you for confirming @stephybun 👍

**Comment by joshuafernandes** [comment]
@tradosh had opened https://github.com/hashicorp/terraform-provider-azurerm/issues/10596 for the vnet to support multiple CIDRs (ipv4 and ipv6) which has been closed in favour of this issue, but this issue also doesn't resolve that @stephybun ?

**Comment by stephybun** [comment]
Thanks for pointing that out @joshuafernandes, we'll work on getting that in.

**Comment by joshuafernandes** [comment]
Thankyou @stephybun , appreciate it !
