### ISSUE TITLE
Adding ip_restriction for App Service results in "IpSecurityRestriction.IpAddress is invalid.  It must be in CIDR format." error

### ISSUE THREAD

**Issue by tvanfosson** [hashicorp/terraform-provider-azurerm#3963]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.4 (via Azure Shell)
+ provider.azurerm v1.32.0

### Affected Resource(s)

`azurerm_app_service`

### Terraform Configuration Files

variables.tf
```variables.tf
variable "prefix" {
  type        = string
  description = "The prefix used for all resources"
}

variable "location" {
  type        = string
  description = "The Azure region for all resources"
  default     = "West US"
}

variable "environment" {
  type        = string
  description = "The value for the environment tag"
}
```
development.tfvars
```development.tfvars
prefix                 = "bug-repro"
location               = "West US"
environment            = "bugrepro"
```

main.tf
```main.tf
provider "azurerm" {
  version = "~> 1.28"
}

data "azurerm_subscription" "current" {
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "main" {
  name     = "${var.prefix}-resources"
  location = var.location

  tags = {
    environment = var.environment
  }
}

### App Services ###

resource "azurerm_app_service_plan" "main" {
  name                = "${var.prefix}-appserviceplan"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  sku {
    tier = "Standard"
    size = "S1"
  }

  tags = {
    environment = var.environment
  }
}

resource "azurerm_app_service" "api" {
  name                = "${var.prefix}-appservice"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  app_service_plan_id = azurerm_app_service_plan.main.id

  identity {
    type = "SystemAssigned"

  site_config {
    always_on                = true
    http2_enabled            = true
    remote_debugging_enabled = true
    remote_debugging_version = "VS2017"
    scm_type                 = "VSTSRM"

    ip_restriction {
      ip_address = "192.168.0.0/24"  # replace with a real network
    }
  }

  tags = {
    environment = var.environment
  }
}
```

### Debug Output

https://gist.github.com/tvanfosson/1e5a5f29cb44637cf9256d9a0fd51356

### Expected Behavior

The App Service should be configured with the given IP address restriction.

### Actual Behavior

It appears that Terraform encodes the IP address specified as `<nil>` when it is sent to the API. This results in an error indicating that an address in CIDR format is required and the configuration fails.

### Steps to Reproduce

1. `terraform apply -var-file="development.tfvars`

**Comment by tvanfosson** [comment]
I've also tried this with version 1.12.5 of Terraform, same version of the Azure provider locally with the same results.

**Comment by paul-vu** [comment]
The Terraform documents specify the IP Address must be in CIDR notation, but this does not work for me. I had to use ip_address and subnet_mask to get this to work. (using azurerm version = 1.41.0) 

To define a single restriction: (Note: virtual_network_subnet_id is a required field for some reason when defining it this way)
```
site_config {
  {
    ip_address                = "192.168.0.0"
    subnet_mask               = "255.255.255.0"
    virtual_network_subnet_id = null
  }
}
```

To use a list of CIDRs (my preferred way):
```
dynamic "ip_restriction" {
  for_each = [
    "192.168.0.0/24"
  ] # or you can use a var.ip_restrictions list here if you don't want to hard code this
  content {
    ip_address  = split("/", ip_restriction.value)[0]
    subnet_mask = cidrnetmask(ip_restriction.value)
  }
}
```

**Comment by baoduy** [comment]
I got the same issue even set `virtual_network_subnet_id = null`
```
{
      ip_address                = "30.168.10.5"
      subnet_mask               = "255.255.255.0"
      virtual_network_subnet_id = null
    }
```

**Comment by paul-vu** [comment]
30.168.10.5/24 is not a valid cidr block. The 255.255.255.0 mask I used was just an example, and will  only work with /24. You'll need to do the conversion yourself when using custom ranges to calculate the correct subnet mask, or use the dynamic ip_restriction in my example above. If you want to add a single IP like the one you mentioned, it would need a different mask:

```
{
      ip_address                = "30.168.10.5"
      subnet_mask               = "255.255.255.255"
      virtual_network_subnet_id = null
}
```

**Comment by adubnik** [comment]
This is still seem to be an issue with 2.7 provider, probably related to the API version used in provider e.g. https://github.com/microsoft/azure-pipelines-tasks/issues/11578

**Comment by martinjt** [comment]
I'm pretty sure this works with the latest version.

```
    ip_restriction {
      ip_address                = 10.0.0.0/8
      priority                  = 1000
      name                      = "InternalAppSubnet"
      action                    = "Allow"
    }
```

Note that the syntax no longer has a separate `subnet_mask` variable.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
