### ISSUE TITLE
Can't refresh api management admin user data using azurerm_api_management_user

### ISSUE THREAD

**Issue by Sasa33** [hashicorp/terraform-provider-azurerm#3967]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.14
provider.azurerm v1.32.0

### Affected Resource(s)

* `azurerm_api_management_user`

### Terraform Configuration Files

```hcl
data "azurerm_api_management_user" "admin" {
  user_id             = "1"
  api_management_name = "${azurerm_api_management.api_management.name}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
}
```
I'd like to get the default admin user account  (/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/users/1) of api management
### Expected Behavior
I get the admin user's data

### Actual Behavior
I got the following error:
Error: data.azurerm_api_management_user.admin: "user_id" may only contain alphanumeric characters and dashes up to 80 characters in length (this error comes from the ApiManagementUserName function in api_management validator)

I noticed that other users's id is 24 length digits, if I tried another user, it works as expected.
But I can't get the admin user's data by using "1" as user_id

**Comment by jhattarki** [comment]
I am having the same issue. Is there a solution/workaround.
Thanks.

**Comment by identifysun** [comment]
@jhattarki 

You can try to create a new user(no admin).

**Comment by EtienneDeneuve** [comment]
@Sasa33 do you still have the issue after the @rikribbers modification ?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
