### ISSUE TITLE
identity_id list of string required - using both types

### ISSUE THREAD

**Issue by cookiecurse** [hashicorp/terraform-provider-azurerm#3993]
In my Azure provider [according to the documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html) (see paragraph "A identity block supports...") I should be able to use identity to set both types `SystemAssigned, UserAssigned` . However, for the UserAssigned I **have to** specify the identity_ids.

From my understanding the identity_ids should look something like this: 
`/subscriptions/<SubscriptionID>/resourcegroups/<RG>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<IdentityName>`
However, since I am throwing both into the type it may be different but I am not 100% sure what that should look like since I couldn't find any examples that use both types.

The issue [#1377](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1377) could have been related but it has been closed, so I am not sure that it is related.

Any help would be much appreciated!

-Cookie

**Comment by ArcturusZhang** [comment]
Hi @cookiecurse thanks for this issue. This reply may be a bit late, but when using `UserAssigned` identity, you should first create some user-assigned identity using the `azurerm_user_assigned_identity` resource, like this:
```
resource "azurerm_user_assigned_identity" "example" {
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  name = "test-identity"
}
```
then reference this in the vm, like this:
```
resource "azurerm_windows_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  
  # other useful attributes

  identity {
    type = "UserAssigned"  # `SystemAssigned, UserAssigned` works the same
    identity_ids = [azurerm_user_assigned_identity.example.id]
  }
}
```

**Comment by ArcturusZhang** [comment]
And regarding `since I am throwing both into the type`, you could take it like this way:
With a `SystemAssigned` identity, Azure will create a SP for you and fill the `principal_id` and `tenant_id` after the creation.
With a `UserAssgined` identity, you have to create your own identity, and during the creation of the identity, Azure will give you the `principal_id` and `tenant_id`, then reference it in the `identity_ids`.
These two methods have no conflict with each other, you can fill free to use them together.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
