### ISSUE TITLE
Feature request: support AzureVmWorkloadProtectionPolicy in RecoveryServicesVault

### ISSUE THREAD

**Issue by AndresPineros** [hashicorp/terraform-provider-azurerm#4047]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Right now the Recovery Services resources only allow creating ProtectionPolicies and ProtectedItems for AzureVMs, but not for the other types of resources.

It would be nice to have the option for AzureVmWorkloadProtectionPolicy and AzureVmWorkloadProtectedItem in order to backup SQL VMs with the managed service.

### New or Affected Resource(s)
* azurerm_recovery_services_protection_policy_sql_vm
* azurerm_recovery_services_protected_sql_vm

### Potential Terraform Configuration

I think defining the resource abstractions requires a little more experience than what I have, but here's the Python definition I used for the Policy's model, which could help a little to move it to Go. The SDK model names are the same so it should be easy to map them.
```
protection_policy = AzureVmWorkloadProtectionPolicy(
        backup_management_type='AzureWorkload',
        work_load_type="SQLDataBase",
        settings=Settings(
            issqlcompression=False,
            is_compression=False
        ),
        sub_protection_policy=[
            SubProtectionPolicy(
                policy_type="Full",  # PolicyType.full
                retention_policy=LongTermRetentionPolicy(
                    retention_policy_type="LongTermRetentionPolicy",
                    daily_schedule=DailyRetentionSchedule(
                        retention_times=[
                            datetime(2019, 8, 9, 5, 0, 0)],
                        retention_duration=RetentionDuration(
                            count=180,
                            duration_type=RetentionDurationType.days
                        )
                    )
                ),
                schedule_policy=SimpleSchedulePolicy(
                    schedule_policy_type="SimpleSchedulePolicy",
                    schedule_run_days=None,
                    schedule_run_frequency=ScheduleRunType.daily,
                    schedule_run_times=[
                        datetime(2019, 8, 9, 5, 0, 0)],
                    schedule_weekly_frequency=0
                )
            ),
            SubProtectionPolicy(
                policy_type="Log",
                retention_policy=SimpleRetentionPolicy(
                    retention_policy_type="SimpleRetentionPolicy",
                    retention_duration=RetentionDuration(
                        count=15,
                        duration_type=RetentionDurationType.days
                    )
                ),
                schedule_policy=LogSchedulePolicy(
                    schedule_policy_type="LogSchedulePolicy",
                    schedule_frequency_in_mins=15
                )
            )
        ]
    )

### References
https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protection_policy_vm.html
https://www.terraform.io/docs/providers/azurerm/r/recovery_services_protected_vm.html
```

**Comment by nikoremi97** [comment]
+1

**Comment by abc1196** [comment]
Having the same issue.

**Comment by yosoyafa** [comment]
having the same issue

**Comment by rubendcm9708** [comment]
Having the same issue

**Comment by juanswan13** [comment]
I'm having the same issue. Currently i'm making this manually but this action mess up the terraform state.

**Comment by nexxai** [comment]
Hi @AndresPineros can you please update your submission to use the template found here please: https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md

**Comment by djsunn** [comment]
Implementation of the Workload Types SAPHANA and SapHanaDatabase would be very much appreciated.

**Comment by Rod-Sychev** [comment]
+1

Looking forward to this one too.

**Comment by NQFDevOps** [comment]
+1
We need this as well.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
