### ISSUE TITLE
azurerm_application_gateway - Ignore changes for ssl certificate does not work

### ISSUE THREAD

**Issue by MelleD** [hashicorp/terraform-provider-azurerm#4084]
After the upgrade from terraform 0.11.x to 0.12.6 and the azure provider from 1.28.0 to 1.32.1 the ignore changes is not working anymore.
Before the upgrade it works fine. Currently we have a default ssl certifacte for the deployment. After the deployment we change the certifacte manually. After the next deployment the ssl certifacte is changed to the default one.

I raise up a bug to terraform https://github.com/hashicorp/terraform/issues/22412. But it seems that is no bug for terraform, because `terraform plan` show no actions and diff in the output.

### Terraform Version
0.12.6

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "AppGateway" {
  ssl_certificate {
    name     = var.ssl_certificate_name
    data     = var.ssl_certificate_file
    password = var.ssl_certificate_password
  }

  lifecycle {
    ignore_changes = [
      ssl_certificate
    ]
  }
}
```

### Expected Behavior
Certifacte should not changed

### Actual Behavior
Certifacte is changed

**Comment by nexxai** [comment]
You'll need to wrap the `ssl_certificate` in the `ignore_changes []` in double-quotes.

Example:
```hcl
  lifecycle {
    ignore_changes = [
      "ssl_certificate"
    ]
  }
```

**Comment by SirWayne** [comment]
@nexxai 
thanks for your response. Try the syntax, but same issue. The certifacte is changed after applying terraform

```
resource "azurerm_application_gateway" "AppGateway" {
  ssl_certificate {
    name     = var.ssl_certificate_name
    data     = var.ssl_certificate_file
    password = var.ssl_certificate_password
  }

  lifecycle {
    ignore_changes = [
      "ssl_certificate"
    ]
  }
}```

**Comment by SirWayne** [comment]
And in the terraform docu, the syntax is without quotes
https://www.terraform.io/docs/configuration/resources.html

**Comment by SirWayne** [comment]
Is there no news here?

**Comment by jonasbark** [comment]
We noticed the same - this ultimately means that all of our web apps will break each time we make a change to the gateway.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
