### ISSUE TITLE
azurerm_function_app: AppSettings Not Saved to tfstate file

### ISSUE THREAD

**Issue by midacts** [hashicorp/terraform-provider-azurerm#4116]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```text
#> terraform -v
Terraform v0.12.0
+ provider.azuread v0.5.1
+ provider.azurerm v1.31.0
```

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "funcapp" {
  name                      = var.function_app_name
  location                  = data.azurerm_resource_group.rg.location
  resource_group_name       = data.azurerm_resource_group.rg.name
  app_service_plan_id       = data.azurerm_app_service_plan.asp.id
  storage_connection_string = data.azurerm_storage_account.sa.primary_connection_string
  client_affinity_enabled   = var.client_affinity_enabled
  https_only                = var.https_only
  version                   = var.runtime_version
  app_settings              = local.appsettings
  dynamic "connection_string" {
    for_each = var.connection_string
    content {
      name  = connection_string.value.name
      type  = connection_string.value.type
      value = connection_string.value.value
    }
  }
  depends_on = [azurerm_application_insights.ai]
  tags       = var.tags

  site_config {
    use_32_bit_worker_process = var.worker_32bit
    websockets_enabled        = var.websockets_enabled
  }
}
```

### Expected Behavior

To create the resource and not show any changes.
(to not have `terraform plan` think app_settings are not set when they have been)

### Actual Behavior

`terraform apply` runs successfully and applies all the correct appsettings.
The issue is, not all of the app settings are stored in the tfstate file so when you run `terraform plan` again, it shows that there are changes, when there really are not.

From my experience, these app settings are not getting stored:
- AzureWebJobsDashboard
- AzureWebJobsStorage
- FUNCTIONS_EXTENSION_VERSION

[These lines](https://github.com/terraform-providers/terraform-provider-azurerm/blob/746689a54f46b69b6055fdcf06cffbe974a64376/azurerm/resource_arm_function_app.go#L534-538) in the `resource_arm_function_app.go` file seem to be the issue?

**Comment by Bessonov** [comment]
Still valid for:
```
Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v1.41.0
+ provider.kubernetes v1.10.0
+ provider.null v2.1.2
```

**Comment by matthorgan** [comment]
Can confirm this is still valid for `terraform v0.12.21` and `azuread v.0.8.0`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
