### ISSUE TITLE
Don't Create Default API and Products When Creating API Management

### ISSUE THREAD

**Issue by opticyclic** [hashicorp/terraform-provider-azurerm#4121]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an API Management instance it adds the default "Echo API" API and the default "Starter" and "Unlimited" products.

There needs to be a flag to either not create these or have them deleted after the API Management is created.

### New or Affected Resource(s)

* azurerm_api_management
* azurerm_api_management_api

### References

* #3649 
* https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-01-01/apis/delete

**Comment by jeanpaulsmit** [comment]
Is this really a bug? The example API and products are created by the Azure Resource Manager by default, the only thing you currently can do is remove them afterwards. I'd say at this point in time it behaviour by design?
https://feedback.azure.com/forums/248703-api-management/suggestions/31826548-do-not-deploy-echo-api-when-deploying-via-the-sdk

**Comment by opticyclic** [comment]
Maybe.
However, I would _think_ that the majority of people don't want those in a production system.

The issue you have linked is over two years old which doesn't look good for an SDK fix.

Maybe a workaround is for terraform to provide an option that specifies that you want these items deleted after the APIM is created.

**Comment by jeanpaulsmit** [comment]
I totally agree with you that this Echo API and products shouldn't be there. The thing I'm trying to  point out is that when you create an APIM resource, Microsoft decides to add them by default.
So this is not a Terraform bug.
Easiest solution would be when Microsoft would listen to the community by picking up this rather old feedback issue.

**Comment by molinch** [comment]
@opticyclic @jeanpaulsmit In the meantime do you have any workaround?

**Comment by jeanpaulsmit** [comment]
Actually I haven't spent time on it, but you could use Powershell to remove it.
I use Powershell to set a custom the subscription key, so this should be rather easy.
https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/Remove-AzApiManagementApi?view=azps-2.8.0

**Comment by molinch** [comment]
Thanks @jeanpaulsmit

**Comment by molinch** [comment]
By any chance @jeanpaulsmit would you have an example on how you would proceed?

**Comment by molinch** [comment]
That's really awesome, thanks for the help it really helps new joiners like me

**Comment by opticyclic** [comment]
I delete them using the az cli wrapped in a null resource:

```
#The following 3 resources are required to delete demo products from the APIM using the AZ CLI
resource "null_resource" "clean-apim-api" {
  provisioner "local-exec" {
    command = "az rest -m delete -u \"https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/${var.resource_group_name}/providers/Microsoft.ApiManagement/service/${azurerm_api_management.apim.name}/apis/echo-api?api-version=2019-01-01\""
  }
  depends_on = ["azurerm_api_management.apim"]
}

resource "null_resource" "clean-apim-product-starter" {
  provisioner "local-exec" {
    command = "az rest -m delete -u \"https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/${var.resource_group_name}/providers/Microsoft.ApiManagement/service/${azurerm_api_management.apim.name}/products/Starter?deleteSubscriptions=true&api-version=2019-01-01\""
  }
  depends_on = ["azurerm_api_management.apim"]
}

resource "null_resource" "clean-apim-product-unlimited" {
  provisioner "local-exec" {
    command = "az rest -m delete -u \"https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/${var.resource_group_name}/providers/Microsoft.ApiManagement/service/${azurerm_api_management.apim.name}/products/Unlimited?deleteSubscriptions=true&api-version=2019-01-01\""
  }
  depends_on = ["azurerm_api_management.apim"]
}
```

**Comment by sebader** [comment]
thanks a lot @opticyclic ! that works great for me. Unfortunately only under Linux. In Terraform for Windows I get:

````
null_resource.clean-apim-product-unlimited (local-exec): Executing: ["cmd" "/C" "az rest -m delete -u \"https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/apim-shared/providers/Microsoft.ApiManagement/service/genericapi/products/Unlimited?deleteSubscriptions=true&api-version=2019-01-01\""]
null_resource.clean-apim-product-unlimited (local-exec): ERROR: No connection adapters were found for '"https://management.azure.com/subscriptions/*****/resourceGroups/apim-shared/providers/Microsoft.ApiManagement/service/genericapi/products/Unlimited?deleteSubscriptions=true&api-version=2019-01-01"'
````

**Comment by Radamonas** [comment]
We created PowerShell function for this and added it to our infrastructure pipeline.

```
param (
    [Parameter(Mandatory = $true)]
    [string]
    $ResourceGroup,

    [Parameter(Mandatory = $true)]
    [string]
    $ProductName,

    [Parameter(Mandatory = $true)]
    [string]
    $Environment
)

Write-Host "Starting clean-up of predefined API and products..."

$context = New-AzApiManagementContext -ResourceGroupName $ResourceGroup -ServiceName "$ProductName-$Environment"

Write-Host "Starting deletion of [Echo API]..."
Remove-AzApiManagementApi -Context $context -ApiId "echo-api" 

Write-Host "Starting deletion of product [Starter]..."
Remove-AzApiManagementProduct -Context $context -ProductId "starter" -DeleteSubscriptions

Write-Host "Starting deletion of product [Unlimited]..."
Remove-AzApiManagementProduct -Context $context -ProductId "unlimited" -DeleteSubscriptions

Write-Host "Clean-up finished."
```

**Comment by guyknur** [comment]
This works for me (using Azure CLI features currently in preview):

```
resource "null_resource" "clean-apim-product-starter" {
  provisioner "local-exec" {
    command = "az apim product delete --product-id starter -g ${azurerm_resource_group.rg_general.name} -n ${azurerm_api_management.apim.name} --delete-subscriptions true -y"
  }
  depends_on = [ azurerm_api_management.apim_jv ]
}

resource "null_resource" "clean-apim-product-unlimited" {
  provisioner "local-exec" {
    command = "az apim product delete --product-id unlimited -g ${azurerm_resource_group.rg_general.name} -n ${azurerm_api_management.apim.name} --delete-subscriptions true -y"
  }
  depends_on = [ azurerm_api_management.apim_jv ]
}
```
