### ISSUE TITLE
azurerm_route_table - Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by JayDoubleu** [hashicorp/terraform-provider-azurerm#4136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.6
+ provider.azurerm v1.32.1

### Affected Resource(s)
azurerm_route_table

### Terraform Configuration Files
```hcl
resource "azurerm_route_table" "test" {
  name                          = "acceptanceTestSecurityGroup1"
  location                      = "northeurope"
  resource_group_name           = "rg-test-test"
  disable_bgp_route_propagation = false

  dynamic "route" {
    for_each = local.routes
    content {
      name                   = route.value.name
      address_prefix         = route.value.addressPrefix
      next_hop_in_ip_address = route.value.nextHopIpAddress
      next_hop_type          = "VirtualAppliance"
    }
  }

  tags = {
    environment = "Production"
  }
}
```

### Expected Behavior
Terraform should produce dynamic routes

### Actual Behavior

> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for azurerm_route_table.test to include new values
> learned so far during apply, provider "azurerm" produced an invalid new value
> for .route: new element 1 has appeared.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.
> 
> 
> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for azurerm_route_table.test to include new values
> learned so far during apply, provider "azurerm" produced an invalid new value
> for .route: new element 2 has appeared.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.

local.routes is a dynamically created map. If I change this to static data then it works as expected.

**Comment by cakriwut** [comment]
Does this bug has any fixes? I experience the problem if I create 4 x dynamic rule block. No issue if I commented  the last dynamic rule, apply, un comment, and apply

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
