### ISSUE TITLE
'Error: Provider produced invalid plan' when using 'ignore_changes' for 'ip_configuration' on 'azurerm_network_interface' resource

### ISSUE THREAD

**Issue by gitet** [hashicorp/terraform-provider-azurerm#4150]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.7
+ provider.azurerm v1.29.0

### Affected Resource(s)

* `azurerm_network_interface`

### Terraform Configuration Files

```hcl
# I have a set of Palo Alto VMs in a HA-setup, called PA-0 and PA-1.
# Each VM has a NIC - PA-0_VNIC1 and PA-1_VNIC1. 
# 
# The VNICs are setup with individual (different) primary IP addresses.
# In addition, PA-0_VNIC1 also has a secondary IP that is "floating" between
# the two VNICs (the Palo Alto VMs will call the Azure API to move the 
# secondary IP around between them if a failure occurs on the "active" VM).
#
# I want to ignore the state of the 'ip_configuration' blocks on the VNICs 
# using lifecycle 'ignore_changes':

resource "azurerm_network_interface" "PA-0_VNIC1" {
    # [...] name, location, resource_group_name etc.
    
    lifecycle {
        ignore_changes = [
            "ip_configuration"
        ]
    }

    # * primary
    ip_configuration {  
        primary = true
        name = "conf-0"
        subnet_id = "${azurerm_subnet.PA_SNET_2.id}"
        private_ip_address_allocation = "static"
        private_ip_address = "10.68.244.45"
    }
    # * initial secondary
    ip_configuration {  
        name = "conf-1"
        subnet_id = "${azurerm_subnet.PA_SNET_2.id}"
        private_ip_address_allocation = "static"
        private_ip_address = "10.68.244.44"
    }
}

resource "azurerm_network_interface" "PA-1_VNIC1" {
    # [...] name, location, resource_group_name etc.

    lifecycle {
        ignore_changes = [
            "ip_configuration"
        ]
    }

    # * primary
    ip_configuration {
        primary = true
        name = "conf-0"
        subnet_id = "${azurerm_subnet.PA_SNET_2.id}"
        private_ip_address_allocation = "static"
        private_ip_address = "10.68.244.46"
    }
}

```

### Debug Output
None provided.

### Panic Output
N/A

### Expected Behavior
I expect terraform to return "No changes. Infrastructure is up-to-date."

### Actual Behavior
Error: Provider produced invalid plan

Provider "azurerm" has indicated "requires replacement" on
azurerm_network_interface.PA-1_VNIC1 for a non-existent attribute path
cty.Path{cty.GetAttrStep{Name:"ip_configuration"},
cty.IndexStep{Key:cty.NumberIntVal(1)},
cty.GetAttrStep{Name:"private_ip_address_version"}}.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

### Steps to Reproduce

1. `terraform apply`
2. Using Azure Portal: move secondary IP configuration from PA-0_VNIC1 to PA-1_VNIC1
3. `terraform plan`

### Important Factoids
None.

### References
None.

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
