### ISSUE TITLE
No Field For Issuer Url In App Service Authorization

### ISSUE THREAD

**Issue by opticyclic** [hashicorp/terraform-provider-azurerm#4176]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> A (sic) active_directory block supports the following:
> 
>     client_id - (Required) The Client ID of this relying party application. Enables OpenIDConnection authentication with Azure Active Directory.
> 
>     client_secret - (Optional) The Client Secret of this relying party application. If no secret is provided, implicit flow will be used.
> 
>     allowed_audiences (Optional) Allowed audience values to consider when validating JWTs issued by Azure Active Directory.

However, when setting up Active Directory Authorization in the portal you need to enter the Issuer Url (which is the WS-FEDERATION SIGN-ON ENDPOINT from Active Directory).

### New or Affected Resource(s)

* azurerm_app_service

**Comment by katbyte** [comment]
Properties exist in the SDK:
```
	// Issuer - The OpenID Connect Issuer URI that represents the entity which issues access tokens for this application.
	// When using Azure Active Directory, this value is the URI of the directory tenant, e.g. https://sts.windows.net/{tenant-guid}/.
	// This URI is a case-sensitive identifier for the token issuer.
	// More information on OpenID Connect Discovery: http://openid.net/specs/openid-connect-discovery-1_0.html
	Issuer *string `json:"issuer,omitempty"`
	// ValidateIssuer - Gets a value indicating whether the issuer should be a valid HTTPS url and be validated as such.
	ValidateIssuer *bool `json:"validateIssuer,omitempty"`
```

We should probably add both

**Comment by katbyte** [comment]
It appears this is not in the docs, but supported by the resource. Could you try and set `auth_settings.issuer` property?

**Comment by opticyclic** [comment]
> issuer - (Optional) Issuer URI. When using Azure Active Directory, this value is the URI of the directory tenant, e.g. https://sts.windows.net/{tenant-guid}/.

So just so I understand, 

- the issuer is specific to Azure Active Directory
- there is an Active Directory block
- but the issuer isn't in the Active Directory block

Should this issue be changed to ask for it to be moved to the block?
Or is there a reason why it is written in the unintuitive way?

**Comment by sebader** [comment]
sorry to resurrect this, but I just stumbled upon the same. I totally agree with @opticyclic that it does not feel right that the issuer field is outside the active_directory block. Is there any reason for this?

**Comment by opticyclic** [comment]
Just for reference, the current method to do it looks like this:

    resource "azurerm_app_service" "app-service" {
      name                = "${var.prefix}-app-service"
      resource_group_name = var.resource_group_name
      location            = var.resource_group_location
      app_service_plan_id = azurerm_app_service_plan.app-plan.id
        
      auth_settings {
        enabled = true
    
        active_directory {
          client_id = var.client_id
        }
        issuer = var.issuer_url
    
        tags = var.tags
      }
    }

With the `issuer` suspiciously outside the `active_directory` block, even though the documentation says it is specific to Active Directory.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
