### ISSUE TITLE
Detect static IP/subnet mismatches AND reserved IP rangeconflict during terraform plan

### ISSUE THREAD

**Issue by degerrit** [hashicorp/terraform-provider-azurerm#4225]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We use static IP addresses on Private Peering, with fixed subnets, and run terraform from within a CI pipeline. 

On a few occasions now, I've noticed terraform fails in the _terraform apply_ stage; whereas IMHO the errors should have been caught during the _plan_ stage.

* Subnet mismatches (i.e. address outside of subnet) are probably the easiest, assuming terraform's state caches that information (?)
* There are currently 5 (!) reserved IP addresses in each subnet - see References

Example:

> azurerm_network_interface.network_interface_card.1: network.InterfacesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="PrivateIPAddressInReservedRange" Message="Private static IP address 10.10.100.31 falls within reserved IP range of subnet prefix 10.10.100.0/27." Details=[]

### New or Affected Resource(s)

* azurerm_network_interface

### Potential Terraform Configuration

No change to config needed, example:

```
resource "azurerm_network_interface" "network_interface_card" {
    ip_configuration {
        private_ip_address_allocation = "static"
        subnet_id                     = "${var.subnet_id}"
        private_ip_address            = "${element(var.private_ip_addresses, count.index)}"
```

### References

* https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-faq

> Are there any restrictions on using IP addresses within these subnets?
> Yes. Azure reserves 5 IP addresses within each subnet. These are x.x.x.0-x.x.x.3 and the last address of the subnet. x.x.x.1-x.x.x.3 is reserved in each subnet for Azure services.
> 
> x.x.x.0: Network address
> x.x.x.1: Reserved by Azure for the default gateway
> x.x.x.2, x.x.x.3: Reserved by Azure to map the Azure DNS IPs to the VNet space
> x.x.x.255: Network broadcast address

NOTE: this Microsoft documentation is not entirely correct, since the first (network) address and broadcast address differ for smaller subnets than a common /24. I.e., the "first 4" and the "last" IP address of every subnet are reserved.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
