### ISSUE TITLE
New Resource: Service Fabric Applications & Services

### ISSUE THREAD

**Issue by JamieMagee** [hashicorp/terraform-provider-azurerm#4317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Service Fabric Azure Resource Manager (ARM) application and service deployment is now generally available. [See here](https://azure.microsoft.com/en-us/updates/azure-resource-manager-arm-application-and-service-deployment-is-now-ga/). The new resources are supported in azure-sdk-for-go as of 30th August. [See here](https://github.com/Azure/azure-sdk-for-go/tree/master/services/servicefabric/mgmt/2019-03-01/servicefabric)

### New or Affected Resource(s)

I can see several new resources

- `azurerm_service_fabric_application`
- `azurerm_service_fabric_application_service`
- `azurerm_service_fabric_application_type`
- `azurerm_service_fabric_application_type_version`

### Potential Terraform Configuration

TBD

### References

- [Service Fabric Azure Resource Manager (ARM) application and service deployment is now generally available](https://azure.microsoft.com/en-us/updates/azure-resource-manager-arm-application-and-service-deployment-is-now-ga/)
- [What is the Service Fabric application resource model?](https://docs.microsoft.com/en-gb/azure/service-fabric/service-fabric-concept-resource-model#service-fabric-application-life-cycle-with-azure-resource-manager)
- [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go/tree/master/services/servicefabric/mgmt/2019-03-01/servicefabric)

**Comment by tombuildsstuff** [comment]
hey @JamieMagee 

Thanks for opening this issue.

Taking a quick look into this I just wanted to clarify that this is for Service Fabric Mesh (which is being tracked in #2486) - and not the (older) Service Fabric offering? Whilst the branding unfortunately is the same, looking at the API Version being used (`2019-03-01`) I believe this is Service Fabric Mesh as opposed to the older offering?

Thanks!

**Comment by JamieMagee** [comment]
@tombuildsstuff I believe this is for Service Fabric clusters. The ARM template types are different. This issue is about `Microsoft.ServiceFabric/clusters/applications`, while the (newer) Service Fabric Mesh hosts `Microsoft.ServiceFabricMesh/applications`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
