### ISSUE TITLE
azurerm_monitor_log_profile is not configuring Azure Blob backend for Eventhub for insights-operational-logs

### ISSUE THREAD

**Issue by Sas002** [hashicorp/terraform-provider-azurerm#4336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000
Version Terraform v0.11.11 

https://terraform.io/docs/providers/azurerm/r/monitor_log_profile.html

We are trying to setup Azure monitor_log_profile for sending Azure Activity logs to Eventhub and and Azure Blob both and From event hub to send to backend Azure Blob storage account as captured.

Issue : There is no way to configure eventhub , which is automatically created by terraform with name "insights-operational-logs" to configure backend Azure storage for capture , which send event hub events to Azure blob storage. Also there is no way we can customize the eventhub name from "insights-operational-logs"  to something else. 

terraform code used 

# Create Event hub for syslog under Event hub Namespace for tenant
resource "azurerm_eventhub" "tenantlog" {
  name                = "tenantactivitylog"
  namespace_name      = "${azurerm_eventhub_namespace.securityloggingns.name}"
  resource_group_name = "${azurerm_resource_group.security_logging.name}"
  partition_count     = 2
  message_retention   = 1
  capture_description {
    enabled  = true
    encoding = "Avro"
    interval_in_seconds = 60
    destination {
      name = "EventHubArchive.AzureBlockBlob"
      archive_name_format = "{Namespace}/{EventHub}/{PartitionId}/{Year}-{Month}-{Day}T{Hour}:{Minute}:{Second}"
      blob_container_name = "${azurerm_storage_container.security_logging_container.name}"
      storage_account_id  = "${azurerm_storage_account.security_logging_blob.id}"
    }
  }
  depends_on = ["azurerm_eventhub_namespace.securityloggingns"] 
}      
# Create Azure monitor log profile to send Azure activity logs to Event hub and Blob storage parallel 
resource "azurerm_monitor_log_profile" "tenantactivitylog" {
  name = "default"
  categories = [
    "Action",
    "Delete",
    "Write",
  ]
  locations = [
    "global",
  ]
  # RootManageSharedAccessKey is created by default with listen, send, manage permissions
  servicebus_rule_id = "${azurerm_eventhub_namespace.securityloggingns.id}/authorizationrules/RootManageSharedAccessKey"
  storage_account_id = "${azurerm_storage_account.security_logging_blob.id}"
  retention_policy {
    enabled = true
    days    = 1
  }
}

**Comment by Sas002** [comment]
This is bug from terraform Azure Blob and Azure extension

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
