### ISSUE TITLE
multi-tenant deployment using Azure shared image gallery via terraform

### ISSUE THREAD

**Issue by nicethomaslearngit** [hashicorp/terraform-provider-azurerm#4378]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have created shared image gallery in tenant1 and I am able to create VMs using this image across all subscriptions in this tenant. Used CLI, powershell and Terraform and it worked fine

When I try to create a VM in Tenant-2 with Shared Image Galley available in Tenant-1, it is failing with below error.

Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/subscription-ID-of-tenant-2/resourceGroups/mygroup/providers/Microsoft.Compute/virtualMachines/sigvm-01', however the current tenant '<Tenant-2 ID>' is not authorized to access linked subscription '<subscription-ID-of-tenant-1>'." 

I am using the version 1.34.0

### New or Affected Resource(s)

* azurerm_1.34.0

### Potential Terraform Configuration

```hcl
####  connecting to tenant -2 ########
provider "azurerm" {
  subscription_id = "${var.subscription_id}"
  client_id       = "${var.client_id}"
  client_secret   = "${var.client_secret}"
  tenant_id       = "${var.tenant_id}"
}

#####  connecting to tenant -1 ######## Provider for fetching the SIG resource
provider "azurerm" {
  alias           = "sig-resources-id"
  subscription_id = "${var.sig_subscription_id}"
  client_id       = "${var.sig_client_id}"
  client_secret   = "${var.sig_client_secret}"
  tenant_id       = "${var.sig_tenant_id}"

```

### References

* #4290

**Comment by nicethomaslearngit** [comment]
Hi @tombuildsstuff 

Could you kindly assist me what changes are needed here for using shared Image galleries as above.

**Comment by nicethomaslearngit** [comment]
Hi @tombuildsstuff 

Have you got a chance to look into this.. thank you

**Comment by katbyte** [comment]
Hi @nicethomaslearngit,

We have actually quietly adding support for multi tenant situations like this with service principal authentication. the CLI version is in the works but no timeframe yet. It's not been documented as it remains untested/unofficial but if you'd like to give it a try using a SP for auth and adding  the additional tenants in the provider block:
```hcl
provider "azurerm" {
  auxiliary_tenant_ids = ["00000000-0000-0000-0000-000000000000", "00000000-0000-0000-0000-000000000000", "00000000-0000-0000-0000-000000000000"]
}
```

or in an environment variable: `ARM_AUXILIARY_TENANT_IDS="00000000-0000-0000-0000-000000000000;00000000-0000-0000-0000-000000000000;00000000-0000-0000-0000-000000000000"

Up to 3 can be specified.

If this does work for you please let us know! as we have no tested or verified that it works.

**Comment by nicethomaslearngit** [comment]
Hi @katbyte 

 Thanks a lot for the update.

I tried using auxiliary tenant ids and unfortunately its not working, I will await for the official documentation for using this.

Thank You

**Comment by darryncurranHP** [comment]
@nicethomaslearngit I was having the same issue as you and seem to have figured it out.

I was attempting to peer vnets across ad tenants but the idea is the same.

I followed the steps here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/share-images-across-tenants and ended up with a service principal that had contributor access to both subscriptions (haven't tested it yet with less access or scoped to just the vnet).

My provider setup that finally worked for me was as follows (Notice I'm using the same client_id and client_secret across both providers):
```
provider "azurerm" {
  version = "=1.34"
  alias = "hub"
  client_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  client_secret = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  subscription_id = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
  tenant_id = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"
  auxiliary_tenant_ids = ["bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"]
}

provider "azurerm" {
  version = "=1.34"
  alias = "spoke"
  client_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  client_secret = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  subscription_id = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
  tenant_id = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"
  auxiliary_tenant_ids = ["aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"]
}
```

**Comment by nicethomaslearngit** [comment]
@darryncurranHP 

Awesome awesome.. It worked like a charm, I was on it for couple of weeks and finally the above worked !! 

@katbyte  @tombuildsstuff  FYI

Thanks again.

**Comment by nicethomaslearngit** [comment]
Hi @darryncurranHP  @katbyte @tombuildsstuff 

I ran into another issue, when I am trying to deploy to same tenant it failing with error tenant_id and auxilliary tenant_id are same.

I did a workaround as below

auxiliary_tenant_ids = "${(var.sig_tenant_id == var.tenant_id ? [] : ["var.tenant_id"])}" 

If both tenant IDs are same , I am assigning a null value and is working fine in terraform 12. But failing in terraform 11 and I am terraform version 11

Error reading config for provider config azurerm: parse error at 1:45: expected expression but found "["

Above is the error when used in 11 version. Any suggestions?

**Comment by siobam** [comment]
Hi, 
I use the following workaround.
Works fine for me in any cases.
https://github.com/siobam/Terraform/tree/master/cross_tenant_peeting

**Comment by nicethomaslearngit** [comment]
Hi @siobam 

Can you please help me with the code again.

**Comment by siobam** [comment]
Hi,

Sure, how can i help you?

Thanks,
Viktor

ср, 6 нояб. 2019 г. в 10:06, nicethomaslearngit <notifications@github.com>:

**Comment by nicethomaslearngit** [comment]
Thanks @siobam 

The link above was giving 404, I got the git url. Thanks again

**Comment by siobam** [comment]
try this:
https://github.com/siobam/Terraform/tree/master/azure_cross_tenant_peeting


ср, 6 нояб. 2019 г. в 10:25, nicethomaslearngit <notifications@github.com>:

**Comment by christiansetzer** [comment]
This issue is still open and I wonder what the actual workaround for using image versions in a shared gallery in a tenant in another tenant is? Can someone describe what needs to be done here?
I followed [https://docs.microsoft.com/en-us/azure/virtual-machines/linux/share-images-across-tenants](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/share-images-across-tenants ) and I tried using the described setup in [https://github.com/terraform-providers/terraform-provider-azurerm/issues/4378#issuecomment-537948435](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4378#issuecomment-537948435) but this is not working. I haven't tried it with the same service principal though.

> Error: Error creating Linux Virtual Machine "testvm" (Resource Group "testvm-rg"): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="LinkedAuthorizationFailed" Message="The client has permission to perform action 'Microsoft.Compute/galleries/images/versions/read' on scope '/subscriptions/subscription-id-fdsfsfsd/resourceGroups/imgbos-rg/providers/Microsoft.Compute/virtualMachines/testvm', however the current tenant 'tenant-id-fdfdfsdf' is not authorized to access linked subscription 'subscription-id-fdsfsfsd'."

Do I really need the same service principal and how do I give him access to tenant 2?

Any help would be appreciated.

**Comment by darryncurranHP** [comment]
@christiansetzer Yes it needs to be the same service principal, and it details how to give access in the link you included.

**Comment by christiansetzer** [comment]
@darryncurranHP So the service principal has to be authenticated with the same procedure is what I understand. TGhe service principal also needs the setting for

> Accounts in any organizational directory (Any Azure AD directory - Multitenant)

I will try that and give feedback

**Comment by christiansetzer** [comment]
@darryncurranHP Thanks that really works now. But I still have to wonder why there are contributor rights in tenant1 where the shared image gallery resides necessary.

**Comment by yuri-tieto** [comment]
Any idea if this can work with Managed Identities? We are using Managed Identities for authenticating Terraform. Can Managed Identity be shared between tenants?

**Comment by eodonoghue** [comment]
I have tried the workaround outlined here to deploy images from a shared image gallery in tenant_1 into tenant_2 and it works,, thank you. 
I want to use the same code base to deploy images into a few environments, some will be in the same tenant as the image gallery, some will be in other tenants. Is there a way to use the auxiliary_tenant_ids to do this?

There is a workaround for this listed on this page also:
auxiliary_tenant_ids = "${(var.sig_tenant_id == var.tenant_id ? [] : ["var.tenant_id"])}"
but I found that this only works when the tenant id's are the same. If the tenants are different, this does not work for me. I get this error:
Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*errors.errorString)(0xc000ed8050), PackageType:"azure.multiTenantSPTAuthorizer", Method:"WithAuthorization", StatusCode:0, Message:"Failed to refresh one or more Tokens for request to https://graph.windows.net/xxxxxxxxxxxxxxxx/servicePrincipals?%24filter=appId+eq+%yyyyyyyyyyyyyyyyy%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(nil)}

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
