### ISSUE TITLE
API Management Delegation is not able to be configured

### ISSUE THREAD

**Issue by ptzbguenter** [hashicorp/terraform-provider-azurerm#4423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would be useful to be able to configure Delegation on an API Management resource. I'm thinking this best lives on the `azurerm_api_management` resource.

### New or Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management" "test" {
  name                = "example-apim"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  sku {
    name     = "Developer"
    capacity = 1
  }

  delegation {
    url                      = "https://my.fancy.api.portal.auth/delegation"
    validationKey            = "<very.secret.key>"
    enable_subscriptions     = true
    enable_signin_and_signup = true
  }
}
```

### References

* https://github.com/solankisamir/azure-rest-api-specs/blob/4d76d19845c0c731f32ca830f3ae85d19aa9b90d/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2018-01-01/apimportalsettings.json#L673
* https://github.com/solankisamir/azure-rest-api-specs/blob/4d76d19845c0c731f32ca830f3ae85d19aa9b90d/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2018-01-01/examples/ApiManagementPortalSettingsPutDelegation.json

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
