### ISSUE TITLE
azurerm_storage_account not waiting until fully ready before creating tables

### ISSUE THREAD

**Issue by AHelper** [hashicorp/terraform-provider-azurerm#4445]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.9
+ provider.azurerm v1.34.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.random v2.2.0
```

### Affected Resource(s)

* `azurerm_storage_account` with `azurerm_storage_table`

### Terraform Configuration Files

[test.tf](https://gist.github.com/AHelper/94effd4d5651e18bb135b1d0dcfc8cb3#file-test-tf)

### Debug Output

[terraform_failure.log](https://gist.github.com/AHelper/94effd4d5651e18bb135b1d0dcfc8cb3#file-terraform_failure-log)

### Expected Behavior

All resources should be deployed successfully every time.

### Actual Behavior

There is a chance (25%-50%) of the following failures:
```
azurerm_resource_group.default: Creating...
azurerm_resource_group.default: Creation complete after 6s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tftestrg]
azurerm_storage_account.default: Creating...
azurerm_storage_account.default: Still creating... [10s elapsed]
azurerm_storage_account.default: Still creating... [20s elapsed]
azurerm_storage_account.default: Still creating... [30s elapsed]
azurerm_storage_account.default: Still creating... [40s elapsed]
azurerm_storage_account.default: Still creating... [50s elapsed]
azurerm_storage_account.default: Creation complete after 50s [id=/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/tftestrg/providers/Microsoft.Storage/storageAccounts/tftestrgsa]
azurerm_storage_table.table[0]: Creating...
azurerm_storage_table.table[1]: Creating...
azurerm_storage_table.table[3]: Creating...
azurerm_storage_table.table[4]: Creating...
azurerm_storage_table.table[2]: Creating...
azurerm_storage_table.table[1]: Creation complete after 6s [id=https://tftestrgsa.table.core.windows.net/Tables('Table1')]
azurerm_storage_table.table[3]: Creation complete after 6s [id=https://tftestrgsa.table.core.windows.net/Tables('Table3')]
azurerm_storage_table.table[0]: Still creating... [10s elapsed]
azurerm_storage_table.table[2]: Still creating... [10s elapsed]
azurerm_storage_table.table[0]: Creation complete after 10s [id=https://tftestrgsa.table.core.windows.net/Tables('Table0')]
azurerm_storage_table.table[2]: Creation complete after 11s [id=https://tftestrgsa.table.core.windows.net/Tables('Table2')]

Error: Error creating Table "Table4" within Storage Account "tftestrgsa": tables.Client#Create: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="Unknown" Message="Unknown service error" Details=[{"odata.error":{"code":"ResourceNotFound","message":{"lang":"en-US","value":"The specified resource does not exist.\nRequestId:8ad12b6b-0002-010c-047c-7459b2000000\nTime:2019-09-26T15:11:37.2043785Z"}}}]

  on Test\test.tf line 33, in resource "azurerm_storage_table" "table":
  33: resource "azurerm_storage_table" "table" {

```

### Steps to Reproduce

`terraform apply -var 'azure_resource_group_name=<your RG name here>' -var 'azure_subscription=<your sub ID here>'`

This issue does not happen every time, the example above may need to be redeployed multiple times for the fault to appear.

**Comment by AHelper** [comment]
We've tried a few workarounds to have a local-exec hold the resource from completing until we know the SA is actually ready:
- A local-exec that just sleeps for a minute didn't help, it would still get a table to fail with a 404 (which is interesting...).
- A local-exec that repeatedly tries to create a dummy table and queue (and removes once complete) using the Azure CLI (az storage table create --subscription $Subscription --account-name $Name --name $queueName, etc.). _This does seem to work so far._

This sounds like an issue on Azure's side as we're also seeing this same race condition exist with the resource group.  This may be a problem with Azure's Go library or REST API that doesn't actually wait until the resource is generally available.

And if a 404 is expected behavior, should the AzureRM provider handle that and retry on a 404?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
