### ISSUE TITLE
Recovery service vault backups not enabled for some VMs

### ISSUE THREAD

**Issue by ymash13** [hashicorp/terraform-provider-azurerm#4566]
Hello,
I am creating 16 VMs with backup config using Terraform, Only 8 out of the 16 are getting deployed with backup, the rest do not show backups enabled.

In Terraform, I get this error:
Error: Error waiting for the Recovery Service Protected VM "VM;iaasvmcontainerv2;AZ-GWC3-RG;AZ-GWC3-Util02" to be true (Resource Group "AZ-GWC3-RG") to provision: timeout while waiting for state to become 'Found' (last state: 'NotFound', timeout: 30m0s)

### Affected Resource(s)

Azure Recovery Services Vault

### Terraform Configuration Files
```
resource "azurerm_recovery_services_protected_vm" "Util02" {
    backup_policy_id    = "${azurerm_recovery_services_protection_policy_vm.GFS.id}"
    recovery_vault_name = "${azurerm_recovery_services_vault.RecoveryVault.name}"
    resource_group_name = "${azurerm_resource_group.RG.name}"
    source_vm_id        = "${azurerm_virtual_machine.Util02.id}"
    }
```
### Expected Behavior

All 16 servers should have backups enabled

### Actual Behavior

Only 8 getting backups enabled.

### Steps to Reproduce

1. `terraform apply`

**Comment by dherrma** [comment]
I run into the same issue, however some vm`s don`t get a backup. Some news over here?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
