### ISSUE TITLE
Changing address space for vnet/subnets doesn't trigger correct update of the vnet and blocks the update

### ISSUE THREAD

**Issue by erplsf** [hashicorp/terraform-provider-azurerm#4577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

+ Terraform v0.12.10
+ provider.azurerm v1.35.0

### Affected Resource(s)

`azurerm_virtual_network`
`azurerm_subnet`

### Terraform Configuration Files

```hcl
#Azure Generic vNet Module
resource "azurerm_virtual_network" "vnet" {
  name                = "${var.vnet_name}"
  location            = "${var.location}"
  address_space       = ["${var.address_space}"]
  resource_group_name = "${var.resource_group_name}"
  tags                = "${var.tags}"
}

resource "azurerm_subnet" "subnet" {
  name                 = "${var.subnet_names[count.index]}"
  virtual_network_name = "${azurerm_virtual_network.vnet.name}"
  resource_group_name  = "${var.resource_group_name}"
  address_prefix       = "${var.subnet_prefixes[count.index]}"
  service_endpoints    = "${var.service_endpoints}"
  count                = "${length(var.subnet_names)}"
}
```

### Debug Output

https://gist.github.com/erplsf/a371b970b15247931ee66b424d609cf7

### Expected Behavior

When i change the address space of the vnet and associated subnets, it should update it in place, as shown in plan.

### Actual Behavior

Terraform/Azure complains that subnet becomes invalid with the new address space. This is probably because even though I create the subnet separately, the subnet block is still added automatically to the vnet state. You can easily see it/reproduce with the multiple subnets.

### Steps to Reproduce

Use the supplied terraform code. (It was a part of a module, and is supplied as-is, should be easily modifiable to be used directly.

1. Allocate some address space for vnet and valid address prefix from that range for subnets
2. Change the address space and address prefixes to the new ones.
1. `terraform apply`

### Important Factoids

North Germany Azure

**Comment by neil-yechenwei** [comment]
Thanks for your comments. 
The resource vnet cannot know address prefix of subnet also need to be updated while updating the address space of vnet with separated resources “azurerm_virtual_network” and “azurerm_subnet” in a time as these two resources are using different apis to update the properties of vnet and subnet. So I think you should use the subnet properties in resource “azurerm_virtual_network” to update address space and address prefix in a time. Below is the sample code of tf config.
`
resource "azurerm_resource_group" "example" {
  name     = "testrg1"
  location = "eastus"
}

resource "azurerm_virtual_network" "example" {
  name                = "testvnet1"
  location            = "${azurerm_resource_group.example.location}"
  address_space       = ["10.1.0.0/16"]
  resource_group_name = "${azurerm_resource_group.example.name}"
  
  subnet {
    name           = "testsubnet1"
    address_prefix = "10.1.1.0/24"
  }
}
`

And there is a hint dependency between resource vnet and resource subnet. Subnet is dependent on vnet. So vnet is always updated first before subnet is updated while using separated resources in a time by terraform. So another solution is that you should remove all subnets under the vnet first and update the address space of vnet, then add subnet with new address prefix.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
