### ISSUE TITLE
Can not create Standard_v2 application gateway with private ip

### ISSUE THREAD

**Issue by d4md1n** [hashicorp/terraform-provider-azurerm#4578]
I am trying to create an application gateway version 2 using terraform. After a successful `terraform plan ` I get the following error when using `terraform apply`

 /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxx-rg/providers/Microsoft.Network/applicationGateways/application_gateway_v2 does not support Application Gateway without Public IP for the selected SKU tier Standard_v2. Supported SKU tiers are Standard,WAF." Details=[]

Please note that the above configuration is available through the azure portal

**Comment by katbyte** [comment]
Hi @d4md1n,

Could you supply the terraform configuration that produced this error? It looks like you are using the wrong SKU to not use a public IP.

**Comment by junglekid** [comment]
Application Gateway v2 only supports public IP address.

This is from FAQ for Application Gateways. https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-faq#does-application-gateway-support-static-ip
Does Application Gateway support static IP?
"Yes, the Application Gateway v2 SKU supports static public IP addresses. The v1 SKU supports static internal IPs."

Please look at the differences between V1 and V2. https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-autoscaling-zone-redundant#differences-with-v1-sku
States ILB Mode only is not supported on V2.

The Frontend IP Address has to be a public. This is what I get when I try to create the Application Gateway v2 with a private ip address.
"Application Gateways with a tier of Standard_v2 don’t support only private IP addresses as the frontend. Supported SKU tiers are standard and WAF."

**Comment by d4md1n** [comment]
I see I had created an application gateway v2 using both public and private IP and supposed that it would work using only private

Thank you for pointing it out

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
