### ISSUE TITLE
Support for storage mounts on App Service slots 

### ISSUE THREAD

**Issue by BzSpi** [hashicorp/terraform-provider-azurerm#4588]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Storage mounts have been implemented on App Service through the PR #3792.
This should also be available for the `azurerm_app_service_slot` resources.

### New or Affected Resource(s)

* azurerm_app_service_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service_slot" "staging" {
  # ...

  storage_account {
    name = "my-mount-point"
    type = "AzureFiles"
    # ..
  }
}
```

### References

* #2247 Support Bring Your Own Storage for Web Apps

**Comment by alex-3sr** [comment]
Hi all,

It could be nice to have this feature, mount storage are need especially on both for validate stagging slot before swap to prod.
I checked, and I can see that API is available : https://docs.microsoft.com/en-us/rest/api/appservice/webapps/updateazurestorageaccountsslot

Really impatient to see next PR for this feature ;)
Thanks and have a nice day
Regards,
Alexandre

**Comment by vanProoijenBoyd** [comment]
Would be very helpful. Currently have to do a workaround for a customer, because we can't add a storage account to the slots.

**Comment by evilpilaf** [comment]
Indeed, getting this feature would be extremely helpful, specially for containerized web apps, where warmup can take quite a bit, being able to use slots would make it much better

**Comment by rossifumax** [comment]
Hello everyone,

After more than 2 years, could you please add this feature ? 
It's a real problem when in production we need a mount point, and when we swap the slots, the mount point doesn't exists.

I don't think there's a lot of work to retrieve this feature from the resource `azurerm_app_service` to `azurerm_app_service_slot`.

Regards,
Rémi

**Comment by rossifumax** [comment]
Hello everyone,

I've pushed a PR to fix this issue.
https://github.com/hashicorp/terraform-provider-azurerm/pull/15084

Regards,
Rémi
