### ISSUE TITLE
Azure backend state file naming

### ISSUE THREAD

**Issue by reddare** [hashicorp/terraform-provider-azurerm#4589]
Hi.

When using azure backend, state file can be named something like this: '**name.of.state.file**'.

But [Naming and Referencing Guide](https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata) told that:

> Container names must start with a letter or number, and can contain only letters, numbers, and the dash (-) character.

Thats why its impossible to use any other azure tools (like CLI or PowerShell) for managing terraform state files.

So, when I use terraform with azure backend with workspaces I have got something like that:
**name.of.state.file:workspace** and trying to manage this file with Azure CLI, I have got an error:
`azure.common.AzureHttpError: The specifed resource name contains invalid characters. ErrorCode: InvalidResourceName`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
