### ISSUE TITLE
Import of azurerm_app_service_certificate incomplete

### ISSUE THREAD

**Issue by andydkelly-ig** [hashicorp/terraform-provider-azurerm#4591]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.14
+ provider.azurerm v1.34.0

### Affected Resource(s)

`azurerm_app_service_certificate`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault" "test-kv" {
  name                = "test-kv"
  resource_group_name = "terraform"
}

data "azurerm_key_vault_secret" "test-cert" {
  name                         = "eng-test-com"
  vault_uri                    = "${data.azurerm_key_vault.test-kv.vault_uri}"
}

resource "azurerm_app_service_certificate" "test" {
  name                = "eng-test-com"
  resource_group_name = "test"
  location            = "centralus"
  key_vault_secret_id = "${data.azurerm_key_vault_secret.test-cert.id}"
}
```

### Expected Behavior

The certificate should be imported into the state file. Running a terraform plan should suggest no changes.

### Actual Behavior

The cert gets imported but without the `key_vault_secret_id` value. Running a subsequent terraform plan wants to recreate the resource.

### Steps to Reproduce

1. `terraform import azurerm_app_service_certificate.test`
2. `terraform plan`

### Important Factoids

Manually editing the terraform state to add the entry ` "key_vault_secret_id": "https://test-kv.vault.azure.net/secrets/eng-test-com-com/89d193447afb5c32a87b14f1fd71be37" ` resolves the issue.

![import](https://user-images.githubusercontent.com/42772281/66587044-95520600-eb81-11e9-841e-f8a0bc0be415.png)

![recreate](https://user-images.githubusercontent.com/42772281/66587248-f5e14300-eb81-11e9-8c18-c7c340196f1f.png)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
