### ISSUE TITLE
CosmosDB import failure after apply error that it already exists (and it does, but not according to plan)

### ISSUE THREAD

**Issue by KajB** [hashicorp/terraform-provider-azurerm#4619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.12.10
AzureRM version: 1.34.0

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
resource "azurerm_cosmosdb_account" "main" {
  name                = "${local.common_identifier}${var.environment_name}cdb"
  location            = "${azurerm_resource_group.main.location}"
  resource_group_name = "${azurerm_resource_group.main.name}"
  offer_type          = "${local.cosmosdb_settings.default_offer}"
  kind                = "${local.cosmosdb_settings.default_kind}"

  consistency_policy {
    consistency_level = "${local.cosmosdb_settings.default_consistency_level}"
  }

  geo_location {
    prefix            = "${local.common_identifier}${var.environment_name}cdb"
    location          = "${azurerm_resource_group.main.location}"
    failover_priority = 0
  }
}

locals {
  cosmosdb_settings = {
      default_offer             = "Standard"
      default_kind              = "MongoDB"
      default_consistency_level = "Strong"
  }
}
```

### Panic Output

[Part of crash.log](https://gist.github.com/KajB/5c9eef6a5a2b9c6da2e6e937ff659504)
### Expected Behavior
After terraform telling me to import the existing resource, the resource should have been updated in the state file.
### Actual Behavior
The state file did not get updated and an error occured.
### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform apply`
4. `terraform import azurerm_cosmosdb_account.main /subscriptions/**/resourceGroups/**/providers/Microsoft.DocumentDB/databaseAccounts/**`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems I cannot repro it anymore with below tfconfig which is similar with yours in latest version. Maybe I missed somehting. If you want, you can have a try below tfconfig to check whether the issue still exists? Thanks.
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-cosmos-test"
  location = "eastus2"
}

resource "azurerm_cosmosdb_account" "test" {
  name                = "acctest-ca-test"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  consistency_policy {
    consistency_level = "Strong"
  }

  geo_location {
    prefix            = "catestcdb"
    location          = azurerm_resource_group.test.location
    failover_priority = 0
  }
}
```

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
