### ISSUE TITLE
Error deleting non-last load balancer frontend IP config

### ISSUE THREAD

**Issue by nitzanm** [hashicorp/terraform-provider-azurerm#4648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.9
+ provider.aws v2.29.0
+ provider.azurerm v1.34.0
+ provider.null v2.1.2
```

### Affected Resource(s)

* `azurerm_lb`

### Terraform Configuration Files

At first, we create a load balancer with three frontend IP configs.  Note that the third one has a public IP *prefix*, but the first two have public IP *addresses*.

```json
    "azurerm_lb": {
      "my-lb1": {
        "frontend_ip_configuration": [
          {
            "name": "my-lb1-ms4-frontend",
            "public_ip_address_id": "${azurerm_public_ip.my-ip-ms4.id}"
          },
          {
            "name": "my-lb1-ms5-frontend",
            "public_ip_address_id": "${azurerm_public_ip.my-ip-ms5.id}"
          },
          {
            "name": "my-snat",
            "public_ip_prefix_id": "${azurerm_public_ip_prefix.my.id}"
          }
        ],
        "location": "centraluseuap",
        "name": "my-lb1",
        "resource_group_name": "${azurerm_resource_group.my.name}",
        "sku": "Standard"
      }
    },
```

Then, we modify the config, removing the first frontend IP config, leaving only one *prefix* and one *address*:

```json
    "azurerm_lb": {
      "my-lb1": {
        "frontend_ip_configuration": [
          {
            "name": "my-lb1-ms5-frontend",
            "public_ip_address_id": "${azurerm_public_ip.my-ip-ms5.id}"
          },
          {
            "name": "my-snat",
            "public_ip_prefix_id": "${azurerm_public_ip_prefix.my.id}"
          }
        ],
        "location": "centraluseuap",
        "name": "my-lb1",
        "resource_group_name": "${azurerm_resource_group.my.name}",
        "sku": "Standard"
      }
    },
```

### Debug Output

```
Terraform will perform the following actions:

  # azurerm_lb.my-lb1 will be updated in-place
  ~ resource "azurerm_lb" "my-lb1" {
        id                   = "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1"
        location             = "centraluseuap"
        name                 = "my-lb1"
        private_ip_addresses = []
        resource_group_name  = "my"
        sku                  = "Standard"
        tags                 = {}

      ~ frontend_ip_configuration {
            inbound_nat_rules             = []
            load_balancer_rules           = [
                "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1/loadBalancingRules/my-lb1-ms4-ws7",
                "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1/loadBalancingRules/my-lb1-ms4-ws8",
            ]
          ~ name                          = "my-lb1-ms4-frontend" -> "my-lb1-ms5-frontend"
            outbound_rules                = []
            private_ip_address_allocation = "Dynamic"
          ~ public_ip_address_id          = "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPAddresses/my-ip-ms4" -> "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPAddresses/my-ip-ms5"
            zones                         = []
        }
      ~ frontend_ip_configuration {
            inbound_nat_rules             = []
            load_balancer_rules           = [
                "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1/loadBalancingRules/my-lb1-ms5-ws10",
                "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1/loadBalancingRules/my-lb1-ms5-ws9",
            ]
          ~ name                          = "my-lb1-ms5-frontend" -> "my-snat"
            outbound_rules                = []
            private_ip_address_allocation = "Dynamic"
            public_ip_address_id          = "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPAddresses/my-ip-ms5"
          + public_ip_prefix_id           = "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPPrefixes/my"
            zones                         = []
        }
      - frontend_ip_configuration {
          - inbound_nat_rules             = [] -> null
          - load_balancer_rules           = [] -> null
          - name                          = "my-snat" -> null
          - outbound_rules                = [
              - "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1/outboundRules/my-lb1",
            ] -> null
          - private_ip_address_allocation = "Dynamic" -> null
          - public_ip_prefix_id           = "/subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPPrefixes/my" -> null
          - zones                         = [] -> null
        }
    }
```
...
```
Error: Error Creating/Updating Load Balancer "my-lb1" (Resource Group "my"): network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LoadBalancerFrontendIPConfigurationCannotReferencePublicIPAddressAndPublicIPPrefix" Message="Load Balancer Frontend IP Configuration /subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/loadBalancers/my-lb1/frontendIPConfigurations/my-snat cannot reference Public IP Address /subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPAddresses/my-ip-ms4 and Public IP Prefix /subscriptions/subid-xxxx/resourceGroups/my/providers/Microsoft.Network/publicIPPrefixes/my" Details=[]
```

### Expected Behavior

Preferred behavior: Terraform realizes that I deleted one of the three frontend IP configurations, and deletes that one, without touching the other two.

Acceptable behavior: Terraform doesn't realize I deleted one of the configs; it just does a straight diff and ends up deleting the last/third config, and "shifting" the settings of the first two configs one down.  So 3 becomes 2, 2 becomes 1, and 1 is gone.

### Actual Behavior

Terraform doesn't realize I deleted a config, so it tries to do what I said above in "acceptable behavior."  However, it appears to miss the `public_ip_prefix`.  That causes it to try and add a `public_ip_prefix` to a config that already has a `public_ip_address`. Azure, rightfully, refuses to do so.

### Steps to Reproduce

1. Use the first config above
1. `terraform apply`
1. Use the second config above
1. `terraform apply`

### References

* May be related to #1622

**Comment by nitzanm** [comment]
My initial hypothesis is that this is because both the `public_ip_prefix_id` and `public_ip_address_id` have `Computed: true` in their schema (under the `lb` resource).  If I understand the docs correctly, that means that if they are not specified (or are empty), Terraform will use the current value in the resource and not try to update/overwrite it.  I can't find a way to tell Terraform "I want this to exist in the config, and I want it to be *blank*".

Maybe the answer is to remove `Computed: true` from both of them? I don't immediately see a reason why they're computed, but far be it from me to claim I understand fully.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Yes. I assume you're right. Hopes this fix would be helpful.

**Comment by magodo** [comment]
@nitzanm Thank you for submitting this!

Per @tombuildsstuff has [told](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8182#issuecomment-682498708), removing the `Computed: true` would be a breaking change, we'd better seek some other way to address the issue, rather than breaking other users.

Prior to Terrafrom 0.11, for those `Optional` + `Computed` properties, it is possible to force zero it to `""` for string type. However, this behavior changes since 0.12 (and the corresponding plugin SDK under used by this provider). There is an issue hashicorp/terraform-plugin-sdk#282 tracking that issue. Once it is resolved, your issue can be addressed by explicitly setting the unset `Optional` + `Computed` properties to `""` *to tell Terraform "I want this to exist in the config, and I want it to be blank".*

For now, the workaround is to do a two stage applies: one to cleanup the ip config block and the other to add back the expected ip configs.

Hope this makes sense.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
