### ISSUE TITLE
azurerm notification hub apns certificate credentials

### ISSUE THREAD

**Issue by smushtaq** [hashicorp/terraform-provider-azurerm#4694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi,

For iOS VoIP notifications we cant use azurerm notification hub APNS token based authentication and have to use certificate based authentication. Terraform doesnt provide a mechanism to specify certificate based APNS credentials.

[https://github.com/terraform-providers/terraform-provider-azurerm/issues/2316](url)
link describes the same issue but says it will be deprecated. I dont see any official note which says this will be deprecated.

Can you please add this as a feature request to add support for certificate based APNS credentials.

### New or Affected Resource(s)

* azurerm_notification_hub

### Potential Terraform Configuration

```hcl
resource "azurerm_notification_hub" "example" {
  name                             = "name"
  namespace_name         = azurerm_notification_hub_namespace.test.name
  resource_group_name  = data.azurerm_resource_group.resource_group.name
  location                         = data.azurerm_resource_group.resource_group.location

apns_credential {
    application_mode  = "Sandbox"
    authentication_mode = "Certificate"
    certificate_thumbprint   = ""
    certificate_password      = ""
  }
```

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
