### ISSUE TITLE
Update documentation to show HCL 2 syntax

### ISSUE THREAD

**Issue by scott1138** [hashicorp/terraform-provider-azurerm#4815]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Update the Azure provider docs for HCL 2.  I am happy to work on it, but I am not sure if someone is already doing it or if you'd prefer they be left with the HCL 1 syntax.  I also don't know if it would be acceptable to do them in part or if we need to do all of them in one commit for consistency.  And now that I type that it makes sense that we would do it all at once.

### New or Affected Resource(s)

Pretty much all of them :)

* azurerm_*

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
