### ISSUE TITLE
Adding and Removing Route Table from AzureFirewallSubnet fails when using azurerm_subnet_route_table_association

### ISSUE THREAD

**Issue by keiransteele** [hashicorp/terraform-provider-azurerm#4834]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.13
+ provider.azurerm v1.36.0

### Affected Resource(s)

azurerm_route
azurerm_route_table
azurerm_firewall
azurerm_subnet_route_table_association

### Terraform Configuration Files

Not working:

```hcl
resource "azurerm_subnet" "snet-network-syd-firewall" {
  name = "${var.snet-network-syd-firewall}"
  resource_group_name = "${azurerm_resource_group.rg-network-syd.name}"
  virtual_network_name = "${azurerm_virtual_network.myryman-network-syd.name}"
  address_prefix = "${var.snet-addrsp-network-syd-firewall}"

  route_table_id = "${azurerm_route_table.rt-network-syd-firewall.id}"
}

resource "azurerm_public_ip" "ip-network-syd-firewall" {
  name = "ip-network-syd-firewall"
  resource_group_name = "${azurerm_resource_group.rg-network-syd.name}"
  location = "${var.location}"
  allocation_method = "Static"
  sku = "Standard"
}

resource "azurerm_firewall" "fw-network-syd-firewall" {
  name = "${var.fw-network-syd-firewall-001}"
  resource_group_name = "${azurerm_resource_group.rg-network-syd.name}"
  location = "${var.location}"
  ip_configuration {
    name = "ipconfig"
    subnet_id = "${azurerm_subnet.snet-network-syd-firewall.id}"
    public_ip_address_id = "${azurerm_public_ip.ip-network-syd-firewall.id}"
  }
}

# Configure Route Table

resource "azurerm_route_table" "rt-network-syd-firewall" {
  name = "rt-network-syd-firewall"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.rg-network-syd-firewall.name}"
  disable_bgp_route_propagation = false
}

resource "azurerm_route" "route-network-syd-firewall" {
  name = "Internet"
  resource_group_name = "${azurerm_resource_group.rg-network-syd-firewall.name}"
  route_table_name = "${azurerm_route_table.rt-network-syd-firewall.name}"
  address_prefix = "0.0.0.0/0"
  next_hop_type = "Internet"
}

resource "azurerm_subnet_route_table_association" "rta-network-syd-firewall" {
  subnet_id = "${azurerm_subnet.snet-network-syd-firewall.id}"
  route_table_id = "${azurerm_route_table.rt-network-syd-gatewaysubnet.id}"
}
```

Working:

```hcl
resource "azurerm_subnet" "snet-network-syd-firewall" {
  name = "${var.snet-network-syd-firewall}"
  resource_group_name = "${azurerm_resource_group.rg-network-syd.name}"
  virtual_network_name = "${azurerm_virtual_network.myryman-network-syd.name}"
  address_prefix = "${var.snet-addrsp-network-syd-firewall}"

  route_table_id = "${azurerm_route_table.rt-network-syd-firewall.id}"
}

resource "azurerm_route_table" "rt-network-syd-firewall" {
  name = "rt-network-syd-firewall"
  location = "${var.location}"
  resource_group_name = "${azurerm_resource_group.rg-network-syd-firewall.name}"
  disable_bgp_route_propagation = false

  route {
    name = "Internet"
    address_prefix = "0.0.0.0/0"
    next_hop_type = "Internet"
  }
}
```
### Debug Output

https://gist.github.com/keiransteele/c4511267db4ca5f072801bf9b4d7dde0

### Expected Behavior

When adding a route table to the AzureFirewallSubnet using azurerm_subnet_route_table_association, which is the required subnet name for an Azure Firewall, I expect that the route table should be associated without error so long as a 0.0.0.0/0 route is specified with the next hop of Internet.

When removing a route table from the AzureFirewallSubnet, I expect that the route table should be removed without error

### Actual Behavior

When using azurerm_subnet_route_table_association to associate an azurerm_route resource with an AzureFirewallSubnet. I get the error:
```
{
  "error": {
    "code": "AzureFirewallSubnetRouteTableMustHaveDefaultRouteToInternet",
    "message": "Route Table rt-myryman-network-syd-gatewaysubnet on firewall subnet AzureFirewallSubnet must have 0.0.0.0/0 route with next hop Internet.",
    "details": []
  }
}
```
The route resource includes the route as specified in the error and the route table is successfully associated despite the error message. Running terraform apply again with no changes results in the same error message. I assume this is due to the tainted state the previous failure left the resource in?

When removing the route table, route, route association and route id from the subnet, the removal fails with the same error that the route table must have a 0.0.0.0/0 route. Presumably this is because the resources are now separate and are removed in the reverse of being provisioned but Azure doesn't allow the removal of the required route from the route table (including in the portal). Using the now deprecated way of putting the route block in the route table resource gets around this due to it being a single resource.

Additionally, while provisioning works when putting a route block inside the route table resource, removal still fails because the route table isn't disassociated from the subnet fully before the attempted removal of the  route table and results in the error:

```
Error: Error deleting Route Table "rt-myryman-network-syd-firewall" (Resource Group "rg-myryman-network-syd-firewall"): network.RouteTablesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseRouteTableCannotBeDeleted" Message="Route table rt-myryman-network-syd-firewall is in use and cannot be deleted." Details=[]
```

### Steps to Reproduce

1. `terraform apply` - Apply the non-working config

* #0000

**Comment by michaelschmit** [comment]
I'm running into this same issue as well. I would perhaps rename the title of this issue to be more generic. For instance, "Destroying Route Table Fails when Using azurerm_subnet_route_table_association" because it is not related to AzureFirewallSubnet specifically and it doesn't fail on add.

It is also worth noting to anyone else looking at this issue that terraform warns that using the old route_table_id attribute method is deprecated and that using azurerm_subnet_route_table_association is preferred.

**Comment by keiransteele** [comment]
I haven't encountered issues with destroying route tables when using azurerm_subnet_route_table_association. I have been doing a number of destroys lately for testing too. 

It is possibly more to do with the separate route resource but I haven't done any more testing to confirm. Do you have failing examples?

Although apparently deprecated, using route_table_id on the subnet is still pretty much a requirement otherwise the route table is re-associated with every apply.

**Comment by michaelschmit** [comment]
I always get an error saying that the route is in use.  I'm using a default route (0.0.0.0/0), so azure monitor etc. is likely using the route. However, from the portal I can always delete the route without an issue and then destroy the rest of the resources.

> Although apparently deprecated, using route_table_id on the subnet is still pretty much a requirement otherwise the route table is re-associated with every apply.

It is worse than that. If you do a re-apply, it deletes the association altogether which is another bug.

**Comment by michaelschmit** [comment]
Also, your error above indicates you have ran into the same thing I commented on above: 

`Error: Error deleting Route Table "rt-myryman-network-syd-firewall" (Resource Group "rg-myryman-network-syd-firewall"): network.RouteTablesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="InUseRouteTableCannotBeDeleted" Message="Route table rt-myryman-network-syd-firewall is in use and cannot be deleted." Details=[]`

**Comment by Yakuza-UA** [comment]
I've hit a similar error today. Terraform was failing to associate route table with AzureFirewallSubnet on the first run, but worked on a second attempt of plan/apply. I had to introduce 10s delay dependency resource to resolve it. Apparently Azure is too slow to actually detect that Internet route was added to RT.

**Comment by Phydeauxman** [comment]
I am running into this issue on applys and destroys

**Comment by rezarms** [comment]
I had the same issue today but during adding not destroying.
I attached a default route to Firewall subnet and got the error code AzureFirewallSubnetRouteTableMustHaveDefaultRouteToInternet
In second try it worked.

**Comment by Yakuza-UA** [comment]
@rezarms as I've stated above I had exactly same symptoms as yourself. I think this is Azure being slow... my workaround to this was to delay association of the route table to FirewallSubnet by 10s. I no longer get this errors by doing the following

```terraform
# Create Route Table for Workload subnets (or Azure FW)
resource "azurerm_route_table" "onprem-via-sdwan" {
  name                          = "rt-${local.scope_name}-onprem-via-sdwan"
  location                      = azurerm_resource_group.sdwan.location
  resource_group_name           = azurerm_resource_group.sdwan.name
  disable_bgp_route_propagation = false

  tags = local.sdwan_tags
}

# Add Default Route (in AFW deployments)
resource "azurerm_route" "onprem-via-sdwan-default" {
  name                = "Internet"
  route_table_name    = azurerm_route_table.onprem-via-sdwan.name
  resource_group_name = azurerm_route_table.onprem-via-sdwan.resource_group_name
  address_prefix      = "0.0.0.0/0"
  next_hop_type       = "Internet"
}

# Introduce 10s delay after Default Route creation, or deployment may fail
resource "time_sleep" "sdwan_delay_10s" {
  depends_on = [azurerm_route.onprem-via-sdwan-default]

  create_duration = "10s"
}

# Create Workload (Azure FW) Route Table association
resource "azurerm_subnet_route_table_association" "onprem-via-sdwan" {
  subnet_id      = local.sdwan_afw_subnet.id
  route_table_id = azurerm_route_table.onprem-via-sdwan.id

  depends_on = [time_sleep.sdwan_delay_10s]
}
```

As you can see, I create Route Table, then UDR (0.0.0.0), but I my assignment resource depends on delay timer, which in turn depends on Default UDR creation. This has worked really well.

**Comment by rezarms** [comment]
@Yakuza-UA thanks.
I will try with a delay

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
