### ISSUE TITLE
Please add "availability alert rule" for endpoint monitoring

### ISSUE THREAD

**Issue by dxc-maneesh** [hashicorp/terraform-provider-azurerm#4837]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add "availability alert rule" for endpoint monitoring
![image](https://user-images.githubusercontent.com/40375655/68452618-0a226980-022e-11ea-998b-df8b3b25c1cc.png)
![image](https://user-images.githubusercontent.com/40375655/68452699-45249d00-022e-11ea-8061-1637ae4edfaa.png)
![image](https://user-images.githubusercontent.com/40375655/68452857-b6fce680-022e-11ea-9540-3f493fa92520.png)

Thanks

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
