### ISSUE TITLE
azurerm_hdinsight_spark_cluster gateway is always enabled no matter what, causes cluster to be recreated constantly

### ISSUE THREAD

**Issue by guitmz** [hashicorp/terraform-provider-azurerm#4877]
### Terraform (and AzureRM Provider) Version

* terraform `0.12.10`
* azurerm `1.36.0`

### Affected Resource(s)

* `azurerm_hdinsight_spark_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_hdinsight_spark_cluster" "spark" {
...
  gateway {
    enabled  = false
    username = "my-user"
    password = "my-password"
 ...
}
```

### Expected Behavior

Spark cluster is created with Ambari disabled (as indicated in the documentation: https://www.terraform.io/docs/providers/azurerm/r/hdinsight_spark_cluster.html#enabled) 

### Actual Behavior

Spark cluster is created with Ambari enabled. Upon next terraform run, since it has `enabled = false`, terraform tries to recreate Spark Cluster without Ambari, but since Azure for some reason forces it to be enabled, it will end in an endless recreation loop.

Note that setting `enabled = true` "solves" this, terraform won't try to recreate the cluster anymore and Ambari will be kept running.

### Steps to Reproduce

1. Define the `gateway` as `enabled = false` in `azurerm_hdinsight_spark_cluster`
2. Create cluster, it will be enabled anyway
3. Run terraform again, it will try to disable the `gateway`, causing the cluster to be recreated
4. It will be recreated with the `gateway` enabled again even tough you keep `enabled = false` in its definition
5. Repeat to infinity

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems the enabled property of gateway in hdinsight spark cluster doesn't take effect from service api side. So I raised an issue on Azure/azure-rest-api-specs#9926

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
