### ISSUE TITLE
Terraform plan visual bug for azurerm_virtual network shows incorrect performable actions?

### ISSUE THREAD

**Issue by crawfs** [hashicorp/terraform-provider-azurerm#4903]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.12.15

AzureRM provider version: 1.36.1

### Affected Resource(s)

* azurerm_virtual_network

* `azurerm_XXXXX`

### Terraform Configuration Files

**Template File:**

```hcl
provider "azurerm" {
  version = "=1.36.1"
  subscription_id = var.subscription_id
}

resource "azurerm_resource_group" "vnet_rg_deploy" {
  name     = var.network_rg
  location = var.network_rg_location
}
resource "azurerm_virtual_network" "vnet_deploy" {
  name                = var.vnet_name
  resource_group_name = var.network_rg
  address_space       = var.vnet_address_space
  location            = var.location
  dns_servers         = var.vnet_dns_servers

  dynamic "subnet" {
    for_each             = var.subnet
    content {
      name                 = subnet.key
      address_prefix       = subnet.value
    }
  }
}

```
**Variables**:
```hcl
subscription_id = "000000"
vnet_name = "dev-test-vnet"
subnet = {
    "subnet1" = "10.0.0.0/24"
    "subnet2" = "10.0.1.0/24"
    "subnet3" = "10.0.3.0/24"
    }
network_rg  = "test-network-rg-dev"
location = "australiasoutheast"
vnet_address_space = ["10.0.0.0/16"]
network_rg_location = "australiasoutheast"
```

### Debug Output

https://gist.github.com/crawfs/71c21637dad0cf02eb6e44e578e0bde8

I've scrubbed some sensitive info out of the gist and variables file but it should really be relevant to this case.

### Expected Behavior

I would expect that the plan would on show a change (+ or -) if the subnet doesn't exist yet or is different from what is defined in the template.

In the above example I have an Azure virtual network (that has been imported into terraform) with the subnets subnet1 and subnet3 already deployed and subnet2 has not been, I would expect that running

```hcl
terraform plan
```
would result in only showing a change (+ or -) for subnet2 which is missing from the azure resource. However the output of terraform plan shows what appears to be terraform deleting the existing subnets and recreating them as they are. What makes this behavior somewhat stranger is that if your subnet configuration exactly matches the configuration of the Azure virtual network terraform works exactly as intended and tells you that no infrastructure changes will be made. 

### Actual Behavior

As explained above the terraform plan output (as far as I can tell) suggests that it will delete the existing subnets and recreate them with the exact same configuration, however upon terraform apply the existing subnets are untouched and terraform only adds the new subnet and does not impact the existing ones.

Does this issue report make sense or am I fundamentally misunderstanding how terraform works?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
