### ISSUE TITLE
Incomplete state when importing AzureRM App Service

### ISSUE THREAD

**Issue by oleksiypavlenko** [hashicorp/terraform-provider-azurerm#4922]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.16
+ provider.azurerm v1.36.1

### Affected Resource(s)

* azurerm_app_service_plan

### Terraform Configuration Files

```
resource "azurerm_app_service_plan" "appservicename" {
  name                = "appservicename"
  location            = azurerm_resource_group.resource-group.location
  resource_group_name = azurerm_resource_group.resource-group.name
  kind                = "Windows"

  sku {
    tier     = "Standard"
    size     = "S1"
    capacity = 1
  }

  tags = {
    environment = azurerm_resource_group.resource-group.tags.environment
  }
}
```
### Expected Behavior

Terraform state should have all the properties set correctly.

### Actual Behavior
The state in Terraform Cloud. 

Note, the properties **kind, location, name** are set to null which forces resource being replaced on **apply** command.

```
{
  "version": 4,
  "terraform_version": "0.12.16",
  "serial": 7,
  "lineage": "f21e4bc1-ed56-b68b-16b4-6b1fdc804d14",
  "outputs": {},
  "resources": [
    {
      "mode": "managed",
      "type": "azurerm_app_service_plan",
      "name": "appservicename",
      "provider": "provider.azurerm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "app_service_environment_id": null,
            "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ResourceGroupName/providers/Microsoft.Web/serverFarms/appservicename",
            "is_xenon": null,
            "kind": "",
            "location": null,
            "maximum_elastic_worker_count": null,
            "maximum_number_of_workers": null,
            "name": "",
            "per_site_scaling": null,
            "properties": [],
            "reserved": null,
            "resource_group_name": "ResourceGroupName",
            "sku": [],
            "tags": {}
          },
          "private": "some value=="
        }
      ]
    },
    {
      "mode": "managed",
      "type": "azurerm_resource_group",
      "name": "resource-group",
      "provider": "provider.azurerm",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ResourceGroupName",
            "location": "eastus2",
            "name": "ResourceGroupName",
            "tags": {
              "environment": "prvw"
            }
          },
          "private": "some value=="
        }
      ]
    }
  ]
}
```

### Steps to Reproduce

1. terraform import azurerm_app_service_plan.appservicename /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/ResourceGroupName/providers/Microsoft.Web/serverFarms/appservicename

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
