### ISSUE TITLE
azurerm_function_app missing remote Git source control options

### ISSUE THREAD

**Issue by djsly** [hashicorp/terraform-provider-azurerm#4952]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am using the *azurerm_function_app* resource and I want to deploy my code to it from GitHub using an external Git source repo URL. This is a standard feature of all Azure App Services including Function Apps.

You already support this in the *azurerm_app_service* but for some reason have removed/omitted it from the azurerm_function_app despite from an Azure ARM perspective they are the same thing.

This was requested here: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1801 and closed as duplicate of https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104

But https://github.com/terraform-providers/terraform-provider-azurerm/issues/1104 only added the source_control support for * azurerm_app_service*

### New or Affected Resource(s)

* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "foo" {
  name = "bar"
  location = "northeurope"
  app_service_plan_id = "${azurerm_app_service_plan.blahblah.id}"
  source_control {
    repo_url = "https://github.com/benc-uk/serverless-cognitive.git"
    branch = "master"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/azure-functions/functions-infrastructure-as-code
* Here is a working ARM template with this feature https://github.com/benc-uk/azure-arm/blob/master/old/paas-other/function-app-withcode/azuredeploy.json

**Comment by djsly** [comment]
@benc-uk were you able to use azurerm_app_function with source_control settings in the end ?

**Comment by benc-uk** [comment]
@djsly I gave up and went back to ARM where it's trivial to do this, but I've not been keeping up with TF support in this area

**Comment by djsly** [comment]
Thanks. I will try using azurerm-template I think. The number of open issues in the app function resource is quite high with some major ones too

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
