### ISSUE TITLE
azurerm_virtual_machine_extension type-handler change not working

### ISSUE THREAD

**Issue by OffColour** [hashicorp/terraform-provider-azurerm#4962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
0.12.7 and 1.34.0

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```
resource "azurerm_virtual_machine_extension" "datadog_app01" {
  name                 = "Datadog"
  location             = local.location
  resource_group_name  = azurerm_resource_group.environment-rg.name
  virtual_machine_name = azurerm_virtual_machine.app-01.name
  publisher            = "Datadog.Agent"
  type_handler_version = "0.7"
  type                 = "DatadogWindowsAgent"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
        {
          "api_key": "${local.datadog_registration_key}"
        }
    
SETTINGS

}
```

### Expected Behavior

Changing the type_handler_version should force a rerun of the extension.

The powershell equivalent of what it should do is

`$rerun = [System.GUID]::NewGuid().ToString(); Set-AzVMExtension -ResourceGroupName "<resource group>" -VMName "<vm name>" -location "<location>" -Name "DatadogAgent" -Publisher "Datadog.Agent" -Type "DatadogWindowsAgent" -TypeHandlerVersion "0.7" -Settings @{"api_key" = "<datadog API Key>"} -forceRerun $rerun`

### Actual Behavior

Terraform notices the change in type_handler and gives the impression it's updating, but the actually installed version doesn't change.

### Steps to Reproduce

Install Datadog extension with type-handler_version 0.6
Change type handler to 0.7 in terraform
Apply
Extension remains at 0.6

### Additional Information

Azure Portal shows 0.6 installed
Azure VM has 0.6 installed.
Azure Resource Explorer shows 0.7 installed.

**Comment by OffColour** [comment]
Update: I've found that this is working inconsistently.
I've got some VMs where everything has worked fine and others where the version remains at the old one but resource explorer has the new one.
I've tried manually changing the version in resource explorer back to the old one, running terrafom again (which notices the change), it attempts to update it again but the version on the VM remains the same and only the resource explorer version gets updated again.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
