### ISSUE TITLE
azure function app support for remote builds and customer supplied identity

### ISSUE THREAD

**Issue by kapilt** [hashicorp/terraform-provider-azurerm#4975]
remote building is the default now for func tools. it would be nice to see terraform support this. also support of the customer supplied identity (beta).

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
