### ISSUE TITLE
Container Instance Identity principalId

### ISSUE THREAD

**Issue by skanojia1983** [hashicorp/terraform-provider-azurerm#4996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Export principleID attribute for container instance.  Currently when systemAssigned identity is creating principleID is not being exported. PrincipleID is key for role assignment. Currently, this is something that has to be done outside of terraform using cli. 

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by anufryieu-transcribeme** [comment]
tenant_id is also needed to be exported like for https://www.terraform.io/docs/providers/azurerm/r/function_app.html.

For instance, it's very useful for if you need to add key vault policy for the container group.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
