### ISSUE TITLE
Support for API Management Global Policy seperately from the API Management azurerm_api_management resource

### ISSUE THREAD

**Issue by alastairtree** [hashicorp/terraform-provider-azurerm#5015]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the global API Policy for API management is configured with the `policy` block of the  `azurerm_api_management` resource. However this makes it impossible to apply any policy that includes references to the same API management instance or things contained within it, because you create a circular dependency. 

I propose a new resource for the global policy, much like the seperate resources for the policy at API, Product and Operation levels.

For example, I want to deploy API management, a logger config using `azurerm_api_management_logger` (which depends on api managment being deployed already) and thren global policy to log all requests to that logger - I can't because the policy is part of the `azurerm_api_management` resource which has to deploy before `azurerm_api_management_logger` can, and I need the logger deployed before I can apply the global policy containing `<log-to-eventhub logger-id="${eventhub_logger_id}">` otherwise it is rejected by API Management.

Another example - in the global policy I want to IP whitelist requests into API Management from itself. I cannot because the IP address I need to put as an input in the policy is an output of itself.

### New or Affected Resource(s)

* Deprecate policy block on `azurerm_api_management`
* Add new resource `azurerm_api_management_policy`

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management_policy" "my_global_policy" {
  api_management_name = "abc"
  resource_group_name = "abc"
  xml_content   = "....policy xml goes here ... "
}
```

**Comment by robinkb** [comment]
@tombuildsstuff @katbyte This ticket can be closed since the implementation of `azurerm_api_management_policy`, correct?

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
