### ISSUE TITLE
Enterprise Security Package Support for HDInsight

### ISSUE THREAD

**Issue by njuCZ** [hashicorp/terraform-provider-azurerm#5023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Azure HDInsight offers a number of methods to address enterprise security needs. 

What's more, the standard Azure HDInsight cluster is a single-user cluster, Azure HDInsight with Enterprise Security Package support can provide Active Directory-based authentication, multi-user support, and role-based access control for HDInsight clusters

### New or Affected Resource(s)
Affected Resource:
`azurerm_hdinsight_hadoop_cluster`
`azurerm_hdinsight_hbase_cluster`
`azurerm_hdinsight_spark_cluster`

Affected Data Source:
`azurerm_hdinsight_cluster`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by m4r74** [comment]
Are there any plans on progressing with this? Any blockers?

**Comment by mybayern1974** [comment]
I'm closing this issue by noticing [PR 12866 ](https://github.com/hashicorp/terraform-provider-azurerm/pull/12866)trying to resolve this issue has been merged and released. Please suggest to reopen this issue if there are different opinions.
