### ISSUE TITLE
azurerm_api_management_product approval_required error

### ISSUE THREAD

**Issue by tradosh** [hashicorp/terraform-provider-azurerm#5035]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Terraform v0.12.16
+ provider.azuread v0.7.0
+ provider.azurerm v1.37.0
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_api_management_product`

### Terraform Configuration Files

resource "azurerm_api_management_product" "name" {
  product_id            = "internal"
  api_management_name   = var.api_management_name
  resource_group_name   = var.rg_name
  display_name          = "Internal"
  subscription_required = true
  approval_required     = true
  published             = false}

### Debug Output

run terraform apply

### Panic Output

Error: `subscription_required` must be true and `subscriptions_limit` must be greater than 0 to use `approval_required`

### Expected Behavior

The system should create API Management with the approval_required = true

### Actual Behavior

Doesn't create the API Management product. If you set that to false, you can create the product, and in the GUI set the Require Approval to true, and without a need to provide subscription limits. Creating it using the az commands works fine as well.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
