### ISSUE TITLE
Support for [Postgresql Hyperscale(Citus)]

### ISSUE THREAD

**Issue by yingkunhu** [hashicorp/terraform-provider-azurerm#5040]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

`azurerm_postgresql_server` seems only support single server, but in our production environment, we decided to choose Azure postgresql Hyperscale cluster, and it seems not supported yet. 

Based on the existing documentation, seems that only sql server support hyperscale option. 

* azurerm_postgresql_hyperscale_server

**Comment by dduleep** [comment]
Is there is any road map for adding azurerm_postgresql_hyperscale_server resource?

**Comment by tombuildsstuff** [comment]
@dduleep this issue is tracking support for it

**Comment by katbyte** [comment]
@yingkunhu - looking at the [docs](https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-hyperscale-portal) it doesn't seem like you can configure this outside the portal?

**Comment by ddigioia2** [comment]
Within the next 6-12 months, this may become critical to our moving our development and infrastructure into Azure. It would be great if we could get this onto a roadmap with some kind of time frame. 

Thanks!

**Comment by magodo** [comment]
As @katbyte mentioned, there is no API support for Citus currently. Whilst the service team is working on that, hopefully the API/SDK will be available in several months (maybe longer than half a year). Until then, we will move on to supporting it in terraform.

**Comment by scottwiseProagrica** [comment]
We are also working on a transition that requires Citus in production and would like to create it via Terraform. I know this is now available from the Azure cli and ARM templates. API release target for Feb 2021.

**Comment by xp-vit** [comment]
> We are also working on a transition that requires Citus in production and would like to create it via Terraform. I know this is now available from the Azure cli and ARM templates. API release target for Feb 2021.

Does this mean that in March/April we can expect Citus support in terraform?

**Comment by gowdra01** [comment]
has anybody written it using arm templates ?

**Comment by scottwiseProagrica** [comment]
Any update on when support might arrive?

**Comment by yingkunhu** [comment]
As a workaround, you could use `azurerm_template_deployment` to do the deployment, but I'm not quite sure whether update/delete will be working.

**Comment by magodo** [comment]
@scottwiseProagrica Just checked the latest azure-rest-api-specs, there is still no Swagger defined for this.

**Comment by guitmz** [comment]
@yingkunhu we are doing that and it works for cluster creation but terraform can't keep the state of changes (not to mention is hacky as hell)

**Comment by robertlagrant** [comment]
> As @katbyte mentioned, there is no API support for Citus currently. Whilst the service team is working on that, hopefully the API/SDK will be available in several months (maybe longer than half a year). Until then, we will move on to supporting it in terraform.

How's this going, @magodo? It's been a full year!

**Comment by cmahlert** [comment]
Isn't that the needed REST API?: https://github.com/Azure/azure-rest-api-specs/tree/master/specification/postgresqlhsc/resource-manager

Would be great to have this in Terraform.

**Comment by magodo** [comment]
Hi @robertlagrant and @cmahlert, sorry for the slow response.

The PG Citus swagger is currently in private preview status, which means there is likely to be changes in breaking way as it evolves. That is not ideal to implement in this provider, as the provider expects to be stable in each major version (v2 for now), which means we should avoid breaking changes.

Anyway, I've asked for a Go SDK release to involve this service. Meanwhile, I'd like to confirm whether there is any planned breaking change for it, we should be able to implement it in the provider if they commit no breaking changes will be involved.

**Comment by robertlagrant** [comment]
@magodo thank you for this. We're just revisiting this - any progress?

**Comment by mybayern1974** [comment]
@robertlagrant , there is another [thread ](https://github.com/Azure/azure-sdk-for-go/issues/14875)talking about this issue, in which there is business context, potential feature contributor as well as Microsoft service team folks. I just got a chance to reach out to Microsoft service team contacts for this feature while the latest info has no big updates from the above thread: Despite of whether this feature is ready on portal, its API has not reached readiness yet so Terraform for now is unable to support that. All things are actively on going at Microsoft though there is not a timeline yet.

**Comment by tombuildsstuff** [comment]
@mybayern1974 there's a PR inflight for this, see https://github.com/hashicorp/terraform-provider-azurerm/pull/15208

**Comment by mybayern1974** [comment]
> @mybayern1974 there's a PR inflight for this, see #15208

Thank you for sharing this info. Indeed the service contact also let me know they are keeping in touch with @favoretti with providing possible updates in feature API readiness.

**Comment by favoretti** [comment]
Yeah, sorry all, almost done there, just got super sidetracked with other work. Will try to finish ASAP.

**Comment by Hyper200** [comment]
Hey @favoretti 

Not trying to rush you, is it coming soon?

I'm working on somthing which needs me to deploy these groups reoccouringly, if its going to be a while yet i'll look at the arm template deployment instead. If its likey going to be soon i'll hold off.

@yingkunhu Where did you find an arm template example, there no export button in the portal so was just wondering before i go to the effort of creating one myself

Thanks all!

**Comment by favoretti** [comment]
@Hyper200 hey man. Sorry for the delay here, can't say for sure. For one that API is somewhat.. interesting. 

And most importantly - I'm a Ukrainian abroad with whole family middle of the war zone - head is really elsewhere these days. 

If anyone wants to pick up on this - feel free. 

Apologies again.

**Comment by Hyper200** [comment]
Hey @favoretti 

First of all, I am truly sorry to here about your family. I hope they remain safe

I think I'll speak for everyone when I say fuck what russia is doing.

You owe no one any apologies.

If there is anything I can do to help just ask.

Joe.

**Comment by zhangtiedong0912** [comment]
@favoretti @Hyper200  hi do we finish support Citus by terraform?

**Comment by thebuck25** [comment]
Postgres Hyperscale no longer exists - all users have been migrated to CosmosDB for Postgres API.  DocumentDB API support for the Postgres engine on CosmosDB was finally released two weeks ago.  Please see #19375
