### ISSUE TITLE
Support for targeting a subscription in azurerm_policy_set_definition

### ISSUE THREAD

**Issue by gjtaylor** [hashicorp/terraform-provider-azurerm#5042]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support arguments ```subscription_id``` and ```scope``` on ```azurerm_policy_set_definition``` to allow a policy set/initiative to be defined at a subscription. See REST reference https://docs.microsoft.com/en-us/rest/api/resources/policysetdefinitions/createorupdate

Currently there is support for ```management_group_id``` - adding analogous support for ```subscription_id``` would go some way to helping, but having a single attribute ```scope``` which can be assigned either a management group or subscription id would allow for more reuse of policy initiatives across complex environments.

### New or Affected Resource(s)

* azurerm_policy_set_definition

### Potential Terraform Configuration

```hcl
data "azurerm_subscription" "mysub" {
  subscription_id = "xxx"
}

data "azurerm_policy_definition" "asc_policy_definition_monitor_system_updates" {
  display_name = "System updates should be installed on your machines"
}


resource "azurerm_policy_set_definition" "asc_policy_initiative_baseline" {
  name         = "Baseline ASC Policy"
  display_name = "test policy set definition"
  policy_type  = "Custom"
  scope        = data.azurerm_subscription.mysub.subscription_id


  metadata = <<METADATA
    {
        "category": "Security Center"
    }
  METADATA

  policy_definitions = <<POLICY_DEFINITIONS
    [
      {
        "parameters": {
          "effect": {
            "value": "AuditIfNotExists"
          }
        },
        "policyDefinitionId": "${data.azurerm_policy_definition.asc_policy_definition_monitor_system_updates.id}"
        }
   ]
  POLICY_DEFINITIONS

}
```

### References

*

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
