### ISSUE TITLE
VGW does not force recreate on authorization key change

### ISSUE THREAD

**Issue by tcanelas** [hashicorp/terraform-provider-azurerm#5050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.14
+ provider.azurerm v1.35.0
+ provider.netbox (unversioned)
```

### Affected Resource(s)

* `azurerm_virtual_network_gateway_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway_connection" "connection" {
  count               = "${var.build_vnet * (var.express_route_circuit_id == "" ? 0 : 1)}"
  name                = "ExpressRoute${var.region}"
  location            = "${var.region}"
  resource_group_name = "core-network"

  type                               = "ExpressRoute"
  virtual_network_gateway_id         = "${azurerm_virtual_network_gateway.expressroute.id}"
  express_route_circuit_id           = "${var.express_route_circuit_id}"
  authorization_key                  = "${azurerm_express_route_circuit_authorization.key.authorization_key}"
  routing_weight                     = 1
  enable_bgp                         = false
  use_policy_based_traffic_selectors = false
  express_route_gateway_bypass       = false
}
```

### Expected Behavior

Resource azurerm_virtual_network_gateway_connection should be recreated after authorization_key change, else the key is in status "available" and the connection is broken

### Actual Behavior

```
-/+ module.network_northeurope.azurerm_express_route_circuit_authorization.key (new resource required)
 ~ module.network_northeurope.azurerm_virtual_network_gateway_connection.connection
      authorization_key:            <sensitive> => <sensitive> (attribute changed)
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tcanelas** [comment]
Any information on this ?

**Comment by tcanelas** [comment]
Hi, do we have any information if this is coming someday ?
For the moment we must parse the plan result and taint the resource to force the recreation which is not ideal

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
