### ISSUE TITLE
azurerm_api_management_api_operation_policy fails with non-encoded policy

### ISSUE THREAD

**Issue by jeanpaulsmit** [hashicorp/terraform-provider-azurerm#5066]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

azurerm 1.37
terraform 0.12.17

### Affected Resource(s)

azurerm_api_management_api_operation_policy

### Expected Behavior

Based on this issue [#4140 ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/4140) I expected the policy on operation level (azurerm_api_management_api_operation_policy ) also to be fixed for encoding. 
However I get the same error I ran into as described in 4140:
Error creating or updating API Operation Policy: apimanagement.APIOperationPolicyClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"'My-Custom-HTTP-Header' is an unexpected token. Expecting white space. Line 17, position 75.","target":"representation"}]

I can understand however 4140 fixed this only for azurerm_api_management_api_policy 

### Actual Behavior

Issue as described in 4140 but for azurerm_api_management_api_operation_policy 

### Steps to Reproduce

Try to apply an operation level policy to an API using azurerm_api_management_api_operation_policy

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
