### ISSUE TITLE
azurerm_app_service_plan showing change on every plan or apply

### ISSUE THREAD

**Issue by priguha93** [hashicorp/terraform-provider-azurerm#5095]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.13

+ provider.azurerm v1.36.1

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_app_service_plan" "example" {
  name                = "api-appserviceplan-pro"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  kind = "Linux"
  sku {
    tier = "Standard"
    size = "S1"
    capacity = 1
  }
  maximum_elastic_worker_count = 2
  reserved = true
  per_site_scaling = true
}
```

### Expected Behavior

Post resource creation, on doing a second plan or apply, it should show no change as the config isn't modified.

### Actual Behavior

Post resource creation, on doing a second plan or apply, it showing 1 change but the config wasn't changed and also am not able to see any change in the state file.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` or `terraform apply`

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems maximumElasticWorkerCount property doesn't take effect from api side while creating app service plan. I've filed an issue on Azure/azure-rest-api-specs#10184

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
