### ISSUE TITLE
azurerm_network_security_rule.source_application_security_group_ids only accepts an array of length 1

### ISSUE THREAD

**Issue by nccurry** [hashicorp/terraform-provider-azurerm#5126]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_network_security_rule`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
resource "azurerm_network_security_rule" "master-api" {
  name = "openshift-${var.ocp_cluster_name}-master-api"
  resource_group_name = data.azurerm_resource_group.main.name
  network_security_group_name = azurerm_network_security_group.master.name
  description = "Api traffic from cluster hosts and load balancer"
  protocol = "Tcp"
  source_port_range = "6443"
  destination_port_range = "6443"
  source_application_security_group_ids = [
    azurerm_network_security_group.bootstrap.id,
    azurerm_network_security_group.master.id,
    azurerm_network_security_group.worker.id,
    azurerm_network_security_group.api-lb.id
  ]
  access = "Allow"
  priority = "102"
  direction = "Inbound"
}
```

### Debug Output

```
Error: source_application_security_group_ids: attribute supports 1 item maximum, config has 4 declared

  on main.tf line 525, in resource "azurerm_network_security_rule" "master-api":
 525: resource "azurerm_network_security_rule" "master-api" {
```

### Expected Behavior

To be able to deploy multiple source_application_security_group_ids in an array inside a single azurerm_network_security_rule.

### Actual Behavior

You can only deploy a single source_application_security_group_ids as an array of a single string in a azurerm_network_security_rule.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The code for this is here:
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_network_security_rule.go#L126

```
			"source_application_security_group_ids": {
				Type:     schema.TypeSet,
				MaxItems: 1,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Set:      schema.HashString,
			},

			//lintignore:S018
			"destination_application_security_group_ids": {
				Type:     schema.TypeSet,
				MaxItems: 1,
				Optional: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Set:      schema.HashString,
			},
```

### References

* #0000

**Comment by yupwei68** [comment]
@nccurry ,Thanks for opening this issue, It's only related to resource "`azurerm_network_security_rule`". Now the API network-security-rule only support up to 1 Application Security Group in the source or destination fields.

**Comment by feeyu7** [comment]
Is there a timeline for this issue?

**Comment by JohnDelisle** [comment]
Any updates on this issue?

**Comment by xlammertink** [comment]
I'd like to know more about the current status too. Is this a limitation of the AzureRM API or bug in Terraform? The plural in the name suggests that multiple IDs can be provided, but apparently that's not possible. The documentation of the security rule resource also doesn't state a warning about this limitation. https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_rule#source_application_security_group_ids

**Comment by TimHarmon** [comment]
like to know the status on this issue as it pertains to adding more than 10 elements.

**Comment by jppitout** [comment]
Hi @yupwei68 could you confirm if this is a problem with terraform, azurerm or Azure API?

**Comment by xlammertink** [comment]
I believe this is an issue in the AzureRM provider. Where the arguments “source_application_security_group_ids” and “destination_application_security_group_ids” imply that they allow for multiple ASGs to be provided, it only allows for 1 to be provided. The logic should be updated to allow multiple ASGs to be set as source or destination ASGs. In case the latter is not possible the arguments should be renamed (“_ids” should be replaced with “_id”).

**Comment by favoretti** [comment]
@xlammertink  When I look at current code, that's not an issue, both parameters are lists with no limits. Are you sure this is still an issue on the latest provider version?

**Comment by tombuildsstuff** [comment]
👋 

Checking the code this is set to `MaxItems: 10` so closing as this is no longer an issue - if you're still seeing this issue on the latest version of the Provider then please feel free to let us know and we can take another look.

Thanks!
