### ISSUE TITLE
Support for "Healthcheck" in Azure Web Apps

### ISSUE THREAD

**Issue by sorenhansendk** [hashicorp/terraform-provider-azurerm#5147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure have released an healthcheck feature to Azure Web Apps. I think we should implement that, so its possible to configure from the Terraform configuration easy. Read more about it here: https://github.com/projectkudu/kudu/wiki/Health-Check-(Preview)

### New or Affected Resource(s)

* azurerm_app_service

**Comment by martinjt** [comment]
I think this can be closed @tombuildsstuff, the property is now available in the `azurerm_app_service` resource

**Comment by scottctr** [comment]
Although the health_check_path is there to set the URL, it doesn't seem to control enabling the health check.

**Comment by xortim** [comment]
The property is there, and the plan shows that this is to be set, but the healthcheck isn't enabled. It would also be nice to support the load balancer values as well.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
