### ISSUE TITLE
Wrong API version when creating azurerm_cdn_profile

### ISSUE THREAD

**Issue by pjeannet-dior** [hashicorp/terraform-provider-azurerm#5192]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

*`Terraform v0.12.18`
*`provider.azurerm v1.38.0`, also tried the `v1.39.0`

### Affected Resource(s)

* `azurerm_cdn_profile`

### Terraform Configuration Files

```hcl
resource "azurerm_cdn_profile" "sample" {
  provider            = azurerm.china
  name                = "name-cdn"
  location            = "China East"
  resource_group_name = "rg_name"
  sku                 = "Standard_ChinaCdn"
}
```

### Debug Output

Error: cdn.ProfilesClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'chinaeast' and API version '2017-10-12' for type 'profiles'. The supported api-versions are '2015-06-01, 2016-04-02, 2016-10-02, 2017-04-02, 2018-04-02, 2015-04-02'. The supported locations are 'chinanorth, chinanorth2, chinaeast, chinaeast2'."

### Expected Behavior

Resource is created.

### Actual Behavior

Apply hangs out with previous error.

### Steps to Reproduce

1. `terraform apply` with provider being china region
2. approve apply change

### Important Factoids

This error appeared in an Azure China subscription.
I deployed manualy the resource and tried to import it later in terraform and got the same error.

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
