### ISSUE TITLE
Validation Helper: CIDR network

### ISSUE THREAD

**Issue by phires** [hashicorp/terraform-provider-azurerm#5227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Potentially all that are using the validators

### Expected Behavior

* A CIDR value of 123.456.789.999/10 should be invalid
* A CIDR value of 0.0.0.0 should be invalid, as it is not a valid CIDR notation without the network part

### Actual Behavior

Above examples are valid

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by phires** [comment]
There is a validator in go (net.ParseCIDR).
I would refactor these validation methods, although I'm not too sure of the implications of making an IP without network suffix (e.g. 0.0.0.0) failing the check.

**Comment by katbyte** [comment]
@phires, that would be a great addition. You could make it an additional parameter or have multiple such as `validate.CIDR` and `validate.CIDRAllowNoSuffix` or `validate.CIDRorIP`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
