### ISSUE TITLE
Support for data migration service

### ISSUE THREAD

**Issue by magodo** [hashicorp/terraform-provider-azurerm#5257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support data migration service and its related resources. It is a fully managed service designed to enable seamless migrations from multiple database sources to Azure data platforms with minimal downtime (online migrations). More info [here](https://docs.microsoft.com/en-us/azure/dms/dms-overview).

The resource in terraform is meant to support resource provision/destroy. Not going to handle any procedure task (e.g. only support create/destroy a migration task but not start/stop a migration task).

### New or Affected Resource(s)

* azurerm_data_migration_service
* azurerm_data_migration_project
* azurerm_data_migration_task

### Potential Terraform Configuration

```hcl
resource "azurerm_data_migration_service" "example" {
	name                = "example-dms"
	location            = azurerm_resource_group.example.location
	resource_group_name = azurerm_resource_group.example.name
	virtual_subnet_id   = azurerm_subnet.example.id
	sku_name            = "Standard_1vCores"
}

resource "azurerm_data_migration_service_project" "example" {
	name                = "example-dms-project"
	location            = azurerm_resource_group.example.location
	resource_group_name = azurerm_resource_group.example.name
        service_name = azurerm_data_migration_service.example.name
	source_platform = "SQL"
        target_platform = "SQLDB"
}

resource "azurerm_data_migration_service_task_sql_server" "test" {
  name                       = "example-dms-task"
  service_name               = azurerm_data_migration_service.example.name
  project_name               = azurerm_data_migration_service_project.example.name
  resource_group_name        = azurerm_resource_group.example.name
  databases {
    source_database_name = "FooDB"
    target_database_name = "SomeAzureSqlDB"
    source_tables        = ["dbo.SomeTable"]
    target_tables        = ["dbo.SomeTable"]
  }
  source_connection_info {
    server_address           = "1.2.3.4"
    server_port              = 1433
    user_name                = "SA"
    password                 = "secret"
    encrypt_connection       = true
    trust_server_certificate = true
  }
  target_connection_info {
    server_address           = "some-sql-server.database.windows.net"
    server_port              = 1433
    user_name                = "example-root"
    password                 = "secret"
    encrypt_connection       = true
    trust_server_certificate = true
  }
}

```

**Comment by tombuildsstuff** [comment]
Fixed via #5993 and #5258
