### ISSUE TITLE
Support for Parquet serialization for azurerm_stream_analytics_output_blob 

### ISSUE THREAD

**Issue by tkasu** [hashicorp/terraform-provider-azurerm#5320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of 17.7.2019, Stream Analytics blob output now supports Parquet in addition of Avro, json and csv. 

However, azurerm_stream_analytics_output_blob only supports  Avro, Json and Csv. 

### New or Affected Resource(s)

* azurerm_stream_analytics_output_blob

### References

* [Microsoft announcement of native Parquet support](https://azure.microsoft.com/en-us/updates/stream-analytics-offers-native-support-for-parquet-format/)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
