### ISSUE TITLE
Unable to update Azure FrontDoor configuration if the linked firewall policy has updates

### ISSUE THREAD

**Issue by naikajah** [hashicorp/terraform-provider-azurerm#5340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.18

### Affected Resource(s)

* `azurerm_frontdoor`
* `azurerm_frontdoor_firewall_policy`

### Terraform Configuration Files

Sample code for **azurerm_frontdoor_firewall_policy** ==> https://www.terraform.io/docs/providers/azurerm/r/front_door_firewall_policy.html#example-usage

Sample code for **azurerm_frontdoor** ==>> https://www.terraform.io/docs/providers/azurerm/r/front_door.html#example-usage

```hcl

resource "azurerm_frontdoor_firewall_policy" "example" {
// rest of the code from https://www.terraform.io/docs/providers/azurerm/r/front_door.html#example-usage
  
frontend_endpoint {
    name                              = "exampleFrontendEndpoint1"
    host_name                         = "example-FrontDoor.azurefd.net"
    custom_https_provisioning_enabled = false
  web_application_firewall_policy_link_id = "/subscriptions/${var.subscription_id}/resourcegroups/${var.resource_group}/providers/Microsoft.Network/frontdoorwebapplicationfirewallpolicies/example-fdwafpolicy"
  }

}

resource "azurerm_frontdoor" "example" {
  // Sample code from https://www.terraform.io/docs/providers/azurerm/r/front_door_firewall_policy.html#example-usage
}

```

### Expected Behavior

If there is a change in the `azurerm_frontdoor_firewall_policy` resource it destroys and re-creates the resource. During this time terraform is expected to perform the following operations:
1. Unlink the WAF policies from the front door
2. Delete the WAF policy
3. Re-Create the WAF policy with updated config
4. Link the WAF policy with the front door

### Actual Behavior

Terraform apply fails with the below error:

`FrontDoorWebApplicationPolicy could not be deleted because there are active resources linked to it. Please delete the linked resources and try again.`

This may be because WAF policy is attached to the front door as **web_application_firewall_policy_link_id**   and the association is not known to terraform. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

1. Run terraform apply the first time on the above example resources will create front door and WAF policy and links them together.
2. Update the WAF policy config e.g. **Name** of the WAF policy
3. Terraform Plan shows that the WAF policy will be replaced

```
  # module.landing_zone.azurerm_frontdoor_firewall_policy.custom[0] must be replaced
-/+ resource "azurerm_frontdoor_firewall_policy" "custom" {

```

4. Terraform apply fails with the error as WAF policy is linked to the front door.

### References

* #0000

**Comment by naikajah** [comment]
### Posible solution:
Perhaps once of the possible solution, I can think of is to create a new resource 

*  `azurerm_frontdoor_firewall_policy_attachment`

and use this resource to attach the firewall policy to the front door, this, in turn, can then follow the proper pattern of unlinking and linking the resource before re-creating the WAF policy

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Comment by timja** [comment]
@favoretti this is still relevant please re-open, nothing to do with provider versions

**Comment by favoretti** [comment]
Re-opened as requested.

**Comment by WodansSon** [comment]
The legacy Frontdoor resources have been retired and are no longer being developed.
