### ISSUE TITLE
Support for Compression option GZIP on Stream Analytics job input for Event Hub

### ISSUE THREAD

**Issue by mcalnd70** [hashicorp/terraform-provider-azurerm#5348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Stream Analytics Job Input for Event Hubs has a "Event compression type" option with has 3 possible values - GZip, Deflate or None. Please add support for this in the Terraform provider

### New or Affected Resource(s)

* azurerm_stream_analytics_stream_input_eventhub

### Potential Terraform Configuration

```hcl
resource "azurerm_stream_analytics_stream_input_eventhub" "example" {
  name                         = "eventhub-stream-input"
  stream_analytics_job_name    = "${data.azurerm_stream_analytics_job.example.name}"
  resource_group_name          = "${data.azurerm_stream_analytics_job.example.resource_group_name}"
  eventhub_consumer_group_name = "${azurerm_eventhub_consumer_group.example.name}"
  eventhub_name                = "${azurerm_eventhub.example.name}"
  servicebus_namespace         = "${azurerm_eventhub_namespace.example.name}"
  shared_access_policy_key     = "${azurerm_eventhub_namespace.example.default_primary_key}"
  shared_access_policy_name    = "RootManageSharedAccessKey"

  serialization {
    type     = "Json"
    encoding = "UTF8"
  }

  compression {    
    type = "GZip"
  }
}
```

### References

* #0000

**Comment by tschager** [comment]
Setting the Event Compression Type seems to be supported now: 

[Azure Resource Manager API Doc](https://docs.microsoft.com/en-us/rest/api/streamanalytics/stream-analytics-input#create)

**Comment by mcalnd70** [comment]
Of note, I found Stream Analytics Jobs in Terraform largely unworkable, and bit the bullet and went back to ARM templating for these

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
