### ISSUE TITLE
Geo redundancy not working in Azure Gov environment

### ISSUE THREAD

**Issue by gongjunhuang** [hashicorp/terraform-provider-azurerm#5351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.8
+ provider.azurerm v1.36.1
+ provider.random v2.2.1
```

### Affected Resource(s)
**azurerm_postgresql_server**

### Terraform Configuration Files

```hcl
resource "azurerm_postgresql_server" "postgre_server" {
    name                = "dbserver"
    location            = "usgovvirginia"
    resource_group_name = "${azurerm_resource_group.jira_rg.name}"

    sku {
        name     = "${var.jira_postgre_sku_name}"
        capacity = "${var.jira_postgre_sku_capacity}"
        tier     = "${var.jira_postgre_sku_tier}"
        family   = "${var.jira_postgre_sku_family}"
    }

    storage_profile {
        storage_mb            = "${var.jira_postgre_storage}"
        backup_retention_days = "${var.jira_postgre_data_retention}"
        geo_redundant_backup  = "Enabled"
        auto_grow             = "Enabled"
    }

    administrator_login          = "${var.mp_db_username}"
    administrator_login_password = "${azurerm_key_vault_secret.db_pswd.value}"
    version                      = "9.5"
    ssl_enforcement              = "Enabled"

    tags                         = "${local.postgresqlserver_tags}"
}
```

### Panic Output

```
Error: Error waiting for update of PostgreSQL Server "frmp-jira-production-dbserver" (Resource Group "frmp-production-jira-rg"): Code="GeoRedundantBackupNotSupported" Message="Geo-Redundant Backup is not supported"

  on postgreSQL.tf line 1, in resource "azurerm_postgresql_server" "postgre_server":
   1: resource "azurerm_postgresql_server" "postgre_server" {
```

### Expected Behavior

postgre sql server enable geo redundancy

### Actual Behavior

Not support Geo Redundancy

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
