### ISSUE TITLE
folder type for azurerm_application_insights_analytics_item returns BadRequest

### ISSUE THREAD

**Issue by erwinkramer** [hashicorp/terraform-provider-azurerm#5396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.18
+ provider.azurerm v1.38.0
```

### Affected Resource(s)

* `azurerm_application_insights_analytics_item`

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights_analytics_item" "folderexample" {
  name                    = "folderexample"
  application_insights_id = "${azurerm_application_insights.example.id}"
  content                 = "folderexample"
  scope                   = "shared"
  type                    = "folder"
}
```

### Debug Output

```
 Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Unsupported type parameter" InnerError={"diagnosticcontext":"8cca2215-b743-4b2d-aa6f-23e690a6d2d5","time":"2020-01-14T12:52:27.8366730Z"}
```

### Expected Behavior
Should create a folder in App Insights 

### Actual Behavior
None created

### Steps to Reproduce
1. Follow the configuration [here ](https://www.terraform.io/docs/providers/azurerm/r/application_insights_analytics_item.html).
2. Alter the Item `type` parameter value to `folder`.

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems API doesn't support folder type. I assume it's an API issue. So I filed an issue on Azure/azure-rest-api-specs#10165

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
