### ISSUE TITLE
Cannot specify the subnet name in the "azurerm_dev_test_virtual_network". 

### ISSUE THREAD

**Issue by Tenseiga** [hashicorp/terraform-provider-azurerm#5421]
Currently we cannot specify the subnet name for the vnet "azurerm_dev_test_virtual_network".
My Scenario is that my company has naming convention for all resources.. subnetCurrently it is hardcoded as "vnetnamesubnet"
![image](https://user-images.githubusercontent.com/5677236/72518325-0b0bf300-3890-11ea-949b-c8dbf67f2fd2.png)

file name is https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/devtestlabs/resource_arm_dev_test_virtual_network.go

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After investigated, I found the [subnet name](https://github.com/terraform-providers/terraform-provider-azurerm/blob/34b981a972f57be588dee1738db5a9f7467811ad/azurerm/internal/services/devtestlabs/dev_test_virtual_network_resource.go#L301) in dev code is used for SubnetOverride, which means here subnet name only can be handled by service api. So if you want to specify the subnet name, the new property [ExternalProviderResourceID](https://github.com/Azure/azure-sdk-for-go/blob/db81c34dd5dede3283d34f9225ba99e60a3a8b2f/services/devtestlabs/mgmt/2018-09-15/dtl/models.go#L9293) needs to be introduced. So I assume you're requesting this new property.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
