### ISSUE TITLE
Changing resource's resource_group_name shouldn't require replacement

### ISSUE THREAD

**Issue by Bouke** [hashicorp/terraform-provider-azurerm#5432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Whenever I change a resource group's name, all it's resources will be recreated. In the Azure Portal, I can just move resources to a different resource group (non-destructive operation).

```
  # azurerm_resource_group.acc must be replaced
-/+ resource "azurerm_resource_group" "acc" {
      ~ id       = "/subscriptions/.../resourceGroups/acc" -> (known after apply)
        location = "westeurope"
      ~ name     = "acc" -> "cb-acc" # forces replacement
      ~ tags     = {} -> (known after apply)
    }

  # azurerm_storage_account.acc__cbacc must be replaced
-/+ resource "azurerm_storage_account" "acc__cbacc" {
...
     ~ resource_group_name               = "acc" -> "cb-acc" # forces replacement
...
}
```

### New or Affected Resource(s)

* azurerm_resource_group
* on a generic level, all resources that support moving

### References

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription
https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-support-resources

**Comment by DenWin** [comment]
@Bouke You are not able to rename a resource group in the Azure Portal.

The process of moving all resources from one resource group into another is a different one to renaming a resource group.

**Comment by Bouke** [comment]
Well sure. The problem I have with the rename is the destructive operation on the group's content (recreating resources).

**Comment by DenWin** [comment]
These are 2 separate processes:
Renaming a resource group)
* This is not possible in Azure
* Terraform has the same limitation and the only Option for Terraform to ensure this within its configuration is to drop & recreate - including all child objects

Moving a resource group)
* This is a separate method within Azure
* while it certain would be an option to incorporate this process in Terraform I would not do this if I had the power to say either way
* I would rather declare this a limitation and demand one needs to fix this outside of Terraform - which is exactly the case at the moment

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
