### ISSUE TITLE
azurerm giving the wrong IP in variable referance.

### ISSUE THREAD

**Issue by E-N-G-XOR** [hashicorp/terraform-provider-azurerm#5442]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.19
+ provider.azurerm v1.38.0
+ provider.random v2.2.1

### Affected Resource(s)

"${azurerm_public_ip.vpn_pub_ip.ip_address}"
* `azurerm_XXXXX`

### Terraform Configuration Files

https://drive.google.com/open?id=1OHd7NAZ4lSOhR3KthbJ146iBvWxr12xj

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Terraform doesn't not crash, just tries to connect to the wrong IP. Or no, ip at all....
### Expected Behavior

I should have gotten the correct IP. "52.228.16.67"
### Actual Behavior

I got the IP of "13.88.254.145" and on a re-apply the value was empty

the local provisioner and remote-exec provisioner will not connect to the host that was just created....

### Steps to Reproduce

A simple terraform apply with the code will work.... Takes 3 mins... 

1. `terraform apply`

### Important Factoids

Running the the canada central region.
### References

None that I can see...
* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
