### ISSUE TITLE
azurerm_subnet service_endpoints empty set creates infinite change loop

### ISSUE THREAD

**Issue by robgil-dds** [hashicorp/terraform-provider-azurerm#5486]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
- terraform 0.12.19
- azurerm v1.40.0

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
variable "service_endpoints" {
  type = map
  default = {
    public = ""
    private = "Microsoft.Storage,Microsoft.KeyVault"
  }
}

resource "azurerm_subnet" "subnet" {
  for_each             = var.networks
  name                 = "${var.name}-${var.environment}-${each.key}"
  resource_group_name  = azurerm_resource_group.vpc.name
  virtual_network_name = azurerm_virtual_network.vpc.name
  address_prefix       = element(split(",", each.value), 0)

  # See https://github.com/terraform-providers/terraform-provider-azurerm/issues/3471
  lifecycle {
    ignore_changes = [route_table_id]
  }

  service_endpoints = split(",", var.service_endpoints[each.key])
}
```

### Debug Output

```
  # module.vpc.azurerm_subnet.subnet["public"] will be updated in-place
  ~ resource "azurerm_subnet" "subnet" {
        address_prefix                                 = "10.1.1.0/24"
        enforce_private_link_endpoint_network_policies = false
        enforce_private_link_service_network_policies  = false
        id                                             = "***"
        ip_configurations                              = []
        name                                           = "***"
        resource_group_name                            = "***"
        route_table_id                                 = "***"
      ~ service_endpoints                              = [
          + "",
        ]
        virtual_network_name                           = "***"
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Expected Behavior
It should do nothing with an empty list

### Actual Behavior
It tries to apply an empty list every plan/apply

### Steps to Reproduce
- Pass in an empty list to `service_endpoints`. This will infinitely loop.

### Important Factoids

It's handy to pass in an empty list when using this resource in a module and optionally turning off service endpoints by passing an empty list.

### References

* #0000

**Comment by jackofallops** [comment]
Hi @robgil-dds 

`split` doesn't return an empty list if your `var.service_endpoints` is empty, it returns a list with a single empty string element.  You could do something like this to remove this in cases where the list would return empty:
`service_endpoints = compact(split(",", var.service_endpoints[each.key]))`


-Ste

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
