### ISSUE TITLE
Application Gateway V2 - InvalidResourceReference when using authentication_certificate with in backend_http_settings block

### ISSUE THREAD

**Issue by ankurkapoor** [hashicorp/terraform-provider-azurerm#5497]
Hi,

I raised below issue few weeks back on Tarraform discussion forum but haven't to any solution yet so posting same as a bug here. You can see the reference here: https://discuss.hashicorp.com/t/using-trusted-root-certificate-for-application-gateway-v2/4883

**Problem**
I have been trying to automate creation of Application Gateway V2 (with WAF_v2) by following the documentation https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html

Surely there are few references to V2 so i am assuming that the documentation has been updated after the new App gateway V2 release.

My problem is with regards to the “Backend_http_Settings” which i am trying to configure to use the “trusted root certificate” using below syntax:

```
  backend_http_settings {
    name                  = "${local.http_setting_name}"
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 30
    host_name = "testname.testhost.com"
    authentication_certificate {
        name = "${local.trusted_root_certificate_name}"
    }
  }
```
In the above code block i have defined the authentication_certificate sub section so that i can link the backend_http_settings with a trusted_root_certificate that is being created in the same application gateway resource code block. This successfully passes the “terraform plan” however when i try to “apply” the change, it fails with below error:

Error: Code=“InvalidResourceReference” Message=“Resource XXXX/providers/Microsoft.Network/applicationGateways/XXXX/authenticationCertificates/XXXX-test-vnet-trc referenced by resource XXXX/providers/Microsoft.Network/applicationGateways/XXXX-test-agwv1/backendHttpSettingsCollection/XXXX-test-vnet-be-htst was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.” Details=

If I remove the “authentication_certificate” sub section from the above code, it works fine however it creates the Http Listner but with “Use Well Known CA Certificate” option selected.

![image](https://user-images.githubusercontent.com/9979266/72990468-1b6c2280-3de8-11ea-8bc7-a713971a2046.png)

Is there any configuration that i am missing to set correctly so that i can link the certificate for the trusted root?

Thanks!

**Terraform Version**
```
Terraform v0.12.20
+ provider.azurerm v1.40.0
```

**Comment by n-shine** [comment]
https://docs.microsoft.com/en-us/azure/application-gateway/certificates-for-backend-authentication
> For the v1 SKU, authentication certificates are required, but for the v2 SKU trusted root certificates are required to allow the certificates.

Since you are using a v2 SKU, you will need to set `trusted_root_certificate` inside of your `backend_http_settings` block.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
