### ISSUE TITLE
Unable to create `azurerm_monitor_metric_alert` on QueueMessageCount for a storage queue

### ISSUE THREAD

**Issue by chpspiir** [hashicorp/terraform-provider-azurerm#5511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`v0.12.20`

### Affected Resource(s)

* `azurerm_1.41.0`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "resource_group" {
  name = "resource_group"
  location = "North Europe"
}

resource "azurerm_storage_account" "storage_account" {
  name = "asjdlk8918y3bbhjasd"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  location = "North Europe"
}

resource "azurerm_storage_queue" "queue" {
  name = "queue"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  storage_account_name = azurerm_storage_account.storage_account.name
}

resource "azurerm_monitor_metric_alert" "alert" {
  name                = "test-alert"
  resource_group_name = azurerm_resource_group.resource_group.name
  scopes              = ["${azurerm_storage_account.storage_account.id}/queueServices/${azurerm_storage_queue.queue.name}"]
  description         = "Messages are accumulating in queue ${azurerm_storage_account.storage_account.id}. Has executor stopped consuming items?"
  window_size         = "PT1H"
  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts/queueServices"
    metric_name      = "QueueMessageCount"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 25
  }
}
```

### Expected Behavior

I expected an Azure Monitor alert rule to be created that fires when the number of messages goes over the threshold. 

### Actual Behavior

When we experienced the queue backing up, we did not get the expected alert.

When I inspect the alert in the portal, I see something that doesn't match what I see when I manually create the alert:

![image](https://user-images.githubusercontent.com/50174491/73068704-26888680-3eac-11ea-9a9a-17b134d84297.png)

The above screenshot shows that no data is actually available. 

When I manually create the alert, the queue name is NOT shown in the resource block. It simply says <storage account name>/queue. I am also not able to select a single queue, I can only see metrics for all queues in the storage account (which is good enough for my use case).

Also, when I hover over the graph, I see numbers in the handmade alert, where I see `--` in the terraformed alert.

I tried fiddling with the metric name spaces and the scope, but I a lot of validation errors. If i eg. change the scope to be `"${azurerm_storage_account.storage_account.id}/queue/${azurerm_storage_queue.queue.name}"` instead of `"${azurerm_storage_account.storage_account.id}/queueServices/${azurerm_storage_queue.queue.name}"`, I get a validation error from the API telling me that the metric namespace should be `Microsoft.Storage/storageAccounts/queue` instead of `Microsoft.Storage/storageAccounts/queueServices`. Since `Microsoft.Storage/storageAccounts/queueServices` is what is show here:  https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccountsqueueservices, I am not sure what is the right thing to do.
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

Thanks for the help!

**Comment by maciejgwizdala** [comment]
I have exactly the same issue with table storage.
When I try to use `"${azurerm_storage_account.storage_account.id}/table` (like it's in Azure Portal), I'm getting error:
> Can not parse "scopes.0" as a resource id: The number of path segments is not divisible by 2 in subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourcegroup01/providers/Microsoft.Storage/storageAccounts/storageaccount01/table"

It's related to [resourceid](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/helpers/azure/resourceid.go#L38-L40) helper, which is used for parsing resources paths.

**Comment by maciejgwizdala** [comment]
From Azure Portal I was able to fetch JSON representation of Azure Metric Alert resource:
`{
	"id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resourcegroup01/providers/microsoft.insights/metricalerts/nosql-alert",
	"name": "nosql-alert",
	"type": "microsoft.insights/metricalerts",
	"location": "global",
	"tags": {},
	"kind": "",
	"sku": "",
	"plan": "",
	"managedBy": "",
	"properties": {
		"actions": [
			{
				"actionGroupId": "/subscriptions/00000000-0000-0000-0000-000000000000/resourcegroups/resourcegroup01/providers/microsoft.insights/actiongroups/ops-group-01",
				"webHookProperties": {}
			}
		],
		"autoMitigate": true,
		"criteria": {
			"allOf": [
				{
					"criterionType": "StaticThresholdCriterion",
					"dimensions": [],
					"metricName": "TableCapacity",
					"metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
					"name": "Metric1",
					"operator": "GreaterThan",
					"threshold": 21474836480,
					"timeAggregation": "Average"
				},
				{
					"criterionType": "StaticThresholdCriterion",
					"dimensions": [],
					"metricName": "Transactions",
					"metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
					"name": "Metric2",
					"operator": "LessThan",
					"threshold": 10,
					"timeAggregation": "Total"
				}
			],
			"odata.type": "Microsoft.Azure.Monitor.SingleResourceMultipleMetricCriteria"
		},
		"description": "NoSQL table storage account alerts",
		"enabled": true,
		"evaluationFrequency": "PT5M",
		"scopes": [
			"/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/resourcegroup01/providers/Microsoft.Storage/storageAccounts/storageaccount01/tableServices/default"
		],
		"severity": 3,
		"targetResourceRegion": "westeurope",
		"targetResourceType": "Microsoft.Storage/storageAccounts/tableServices",
		"templateType": 8,
		"windowSize": "PT6H"
	}
}`
The most interesting part is scope - for table storage it's `${azurerm_storage_account.storage_account.id}/tableServices/default`, so for the queue it should be '${azurerm_storage_account.storage_account.id}/queueServices/default'

**Comment by kensykora** [comment]
We were able to workaround this... it's confusing but it works.

The key is the scopes and the window_size must be PT1H

```hcl
resource "azurerm_monitor_metric_alert" "datapipeline_retry_queues" {
  name                = "${azurerm_storage_account.storage.name}-errors"
  resource_group_name = azurerm_resource_group.rg.name
  scopes              = ["${azurerm_storage_account.storage.id}/queueServices/default"]
  description         = "Messages have exceeded their default retry count and require republishing. Please investigate."
  window_size         = "PT1H"
  action {
    action_group_id = data.azurerm_monitor_action_group.med.id
  }
  criteria {
    metric_namespace = "Microsoft.Storage/storageAccounts/queueServices"
    metric_name      = "QueueMessageCount"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 0
  }
}
```

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
