### ISSUE TITLE
Code="CrossSeriesOrCrossGatewayGenenrationResizeNotSupported" Message="Resize from ASeries to DSeries or vice versa and Resize across VirtualNetworkVpnGatewayGenerations are not supported."

### ISSUE THREAD

**Issue by pearcec** [hashicorp/terraform-provider-azurerm#5535]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_network_gateway`

### Expected Behavior

The service should remove the old one including the connection then add it back.

### Actual Behavior

random_id.vnet: Refreshing state... (ID: IImOIA)
data.azurerm_subscription.current: Refreshing state...
azurerm_resource_group.resource-group: Refreshing state... (ID: /subscriptions/redacted)
azurerm_express_route_circuit.private: Refreshing state... (ID: /subscriptions/redactedt)
azurerm_virtual_network.vnet: Refreshing state... (ID: /subscriptions/bredacted)
azurerm_public_ip.gw-public-ip: Refreshing state... (ID: /subscriptions/redacted-gateway-public-ip)
azurerm_subnet.gateway: Refreshing state... (ID: /subscriptions/redacted0/subnets/GatewaySubnet)
azurerm_virtual_network_gateway.gateway: Refreshing state... (ID: /subscriptions/redacted8-...work/virtualNetworkGateways/tf-gateway)
azurerm_express_route_circuit_peering.private: Refreshing state... (ID: /subscriptions/redacted8-...adataEast/peerings/AzurePrivatePeering)
azurerm_virtual_network_gateway_connection.connection: Refreshing state... (ID: /subscriptions/redacted-...onnections/redacted)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_virtual_network_gateway.gateway
      sku: "Standard" => "UltraPerformance"

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions in workspace "teradata"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_virtual_network_gateway.gateway: Modifying... (ID: /subscriptions/redacted-...work/virtualNetworkGateways/tf-gateway)
  sku: "Standard" => "UltraPerformance"
azurerm_virtual_network_gateway.gateway: Still modifying... (ID: /subscriptions/redacted-...work/virtualNetworkGateways/tf-gateway, 10s elapsed)

Error: Error applying plan:

1 error occurred:
        * azurerm_virtual_network_gateway.gateway: 1 error occurred:
        * azurerm_virtual_network_gateway.gateway: Error waiting for completion of AzureRM Virtual Network Gateway "tf-gateway" (Resource Group "tf-sharedservic-bare-network-eastus-rg"): Code="CrossSeriesOrCrossGatewayGenenrationResizeNotSupported" Message="Resize from ASeries to DSeries or vice versa and Resize across VirtualNetworkVpnGatewayGenerations are not supported." Details=[]

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Steps to Reproduce

1. `terraform apply`

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/network/resource_arm_virtual_network_gateway.go#L93

All that needs to be added is ForceNew: ture, to the sku

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
