### ISSUE TITLE
Support for kusto EventGrid

### ISSUE THREAD

**Issue by noam-shapira** [hashicorp/terraform-provider-azurerm#5553]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for kusto EventGrid 

### New or Affected Resource(s)

* azurerm_kusto

### References
https://docs.microsoft.com/bs-latn-ba/azure/data-explorer/ingest-data-event-grid

* #0000

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
