### ISSUE TITLE
App Service Plan hosting platform can't be changed in-place; TF tries to

### ISSUE THREAD

**Issue by brandonh-msft** [hashicorp/terraform-provider-azurerm#5555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.20
+ provider.azurerm v1.42.0

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "fxnapp" {
  name                = format("%s-%s-fxns-%s", var.appname, var.domainprefix, var.environment)
  location            = var.location
  resource_group_name = var.resource_group_name
  kind                = "functionapp"
  reserved            = true
  is_xenon            = false
  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}
```

updated to

```hcl
resource "azurerm_app_service_plan" "fxnapp" {
  name                = format("%s-%s-fxns-%s", var.appname, var.domainprefix, var.environment)
  location            = var.location
  resource_group_name = var.resource_group_name
  kind                = "functionapp"
  is_xenon            = true
  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}
```

### Expected Behavior

Because this is a hosting platform change (Linux -> Windows), it can't be done in place. Therefore the ASP (and dependent objects) need to be deleted & re-created

### Actual Behavior

TF tried to do an in-place change, resulting in 
~~~
web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS." Details=[{"Message":"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS."},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"11022","Message":"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.","MessageTemplate":"You cannot change the OS hosting your app at this time. Please recreate your app with the desired OS.","Parameters":[]}}]
~~~

**Comment by ricohomewood** [comment]
Any update to this bug ... causes real issues to Azure Functions?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
