### ISSUE TITLE
App Service Linux container does not start until first http request

### ISSUE THREAD

**Issue by haodeon** [hashicorp/terraform-provider-azurerm#5559]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.20
AzureRM provider 1.42.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/app-service/docker-basic

### Expected Behavior

After deploying an app service running Linux containers. The app service should automatically pull the container image and begin running it.

### Actual Behavior

The app service does not start the container until after the service receives a http request

### Steps to Reproduce

Run the docker-basic example from above

### References

* #0000

I understand in the example above it even warns you about the fact the container is launched on the first http request.

Why I am raising this as a bug report is because I do not understand why an App Service created by Terraform behaves this way. In my own testing with ARM templates and az CLI, these alternate methods of creating the same resources does not seem to have this limitation.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
