### ISSUE TITLE
Scaling azurerm_sql_elasticpool does not scale the pool size

### ISSUE THREAD

**Issue by phekmat** [hashicorp/terraform-provider-azurerm#5566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform v0.11.14
azurerm v1.42

### Affected Resource(s)

* `azurerm_sql_elasticpool`

### Terraform Configuration Files

```hcl
resource "azurerm_sql_elasticpool" "pool" {
  name                = "pool"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  location            = "${var.location}"
  server_name         = "${azurerm_sql_server.sql_server.name}"
  edition             = "${var.elastic_pool_edition}"
  dtu                 = "${var.elastic_pool_dtu}"
  db_dtu_max          = "${var.elastic_pool_dtu}"
}
```

### Expected Behavior

Changing the DTU should appropriately scale the `pool_size` if it's not specified (or at least document that the `pool_size` only defaults on creation

### Actual Behavior

Scaling the DTUs up does not increase the pool size to the default, nor does scaling it down decrease the pool size to the default. 

### Steps to Reproduce

1. `terraform apply`
1. Modify the number of DTUs 
1. `terraform apply`

### Important Factoids

There's a capabilities API that provides the default that the provider could query (https://docs.microsoft.com/en-us/rest/api/sql/capabilities/listbylocation#elasticpoolperformancelevelcapability)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
