### ISSUE TITLE
Support for Azure Container Group SKU

### ISSUE THREAD

**Issue by jamesbannan** [hashicorp/terraform-provider-azurerm#5592]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The latest version of the Microsoft.ContainerInstance/containerGroups API (2019-12-01) introduces support for [dedicated hosts](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-dedicated-hosts). This is important for some enterprise implementations of ACI where full host isolation is required to satisfy security controls.

When deploying an ACI using the latest API, you select either `"sku": "Standard"` or `"sku": "Dedicated"` depending on what you want to deploy. At the moment, this can only be done in Terraform by using an ARM template within an `azurerm_template_deployment` resource rather than using the native `azurerm_container_group` resource.

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
  sku      = "Standard"
}
```
```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
  sku      = "Dedicated"
}
```

### References

* https://docs.microsoft.com/en-us/azure/container-instances/container-instances-dedicated-hosts

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
