### ISSUE TITLE
Support for linking an IoT Hub to an existing DPS

### ISSUE THREAD

**Issue by mark-greene** [hashicorp/terraform-provider-azurerm#5632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for linking an IoT Hub to an existing DPS.  Currently you can only link a hub during DPS resource creation (or updating your DPS resource creation code).  I am currently having to shell out to the cli to do this (https://docs.microsoft.com/en-us/cli/azure/iot/dps/linked-hub?view=azure-cli-latest).

### New or Affected Resource(s)

* azurerm_iothub_dps_linked_hub

### Potential Terraform Configuration

```hcl
data "azurerm_iothub_dps" "example" {
  name                = "iot_hub_dps_test"
  resource_group_name = "iothub_dps_rg"
}

resource "azurerm_iothub_dps_linked_hub" "example"
{
  id = data.azurerm_iothub_dps.example.id

  linked_hub {
    connection_string = azurerm_iothub.example.primary_connection_string
    location          = azurerm_iothub.example.location
  }
}

```

### References

* #0000

**Comment by omeryesil** [comment]
Any update about this ticket. I think this is an important feature to have. In our case, we ave separate deployments, like common service (VNETs, Storage Accounts, etc.) deployments, then application specific deployments (multiple applications). We are planning to put the DPS deployment in the common services, and IoT Hub deployments under each applications. As the common needs to run first, DPS will be created before the IoT hubs, so that can't really link IoT hub to the DPS.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.

**Comment by favoretti** [comment]
@mark-greene I apologize, I might have been a bit too trigger-happy here. Is this still something you are missing? If so, I'll be happy to re-open this.

**Comment by mark-greene** [comment]
I am still having to use a non-terraform workaround for this issue.  We are currently using the latest Terraform and provider.
