### ISSUE TITLE
Support for data sources to get resources by ID

### ISSUE THREAD

**Issue by BHoggs** [hashicorp/terraform-provider-azurerm#5691]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I think it would be a useful if all data sources were capable of getting their respective data based on a known resource ID.
An example of where this might be useful is when dynamically getting resources by chaining the `azurerm_resources` data source to another. As `azurerm_resources` does not return any useful information other than the resource ID, it could be passed on to the respective data source to query more resource-specific data.

This is not currently possible as all data sources currently require `name` + `resource_group_name`. `resource_group_name` is not currently returned by `azurerm_resources`, so it's not possible to get more information about a resource.

### New or Affected Resource(s)

Data Sources:
* azurerm_resources
* azurerm_*

### Potential Terraform Configuration

```hcl
# Get vNet resource by type & tags
data "azurerm_resources" "network" {
  type = "Microsoft.Network/virtualNetworks"

  required_tags = {
    environment = "production"
    app         = "example-app"
  }
}

# Get vNet detailed information, using ID
data "azurerm_virtual_network" "example" {
  id = data.azurerm_resources.network.resources[0].id
}

# Output address_space
output "virtual_network_address_space" {
  value = data.azurerm_virtual_network.example.address_space
}

```

**Comment by LaurentLesle** [comment]
I have reviewed this request and found it would be helpful if this variation got implemented. 

Getting azure resources by id would allow us to re-use existing resources provided by the customer without managing them with Terraform
Name and Resource_group_name would have to be exported

```hcl
data "azurerm_resources" "network" {
  id = var.resource_id
}

data "azurerm_virtual_network" "example" {
  name = data.azurerm_resources.network.name
  resource_group_name = data.azurerm_resources.network.resource_group_name 
}

# Output address_space
output "virtual_network_address_space" {
  value = data.azurerm_virtual_network.example.address_space
}
```

**Comment by schwarzzz** [comment]
I find especially the first variation "Get vNet resource by type & tags" really useful.
```
data "azurerm_resources" "network" {
  type = "Microsoft.Network/virtualNetworks"

  required_tags = {
    environment = "production"
    app         = "example-app"
  }
}
```

This would allow us to implement a "convention based" data source without knowing the exact name of a resource.

I also see the need for some various for various use cases:

A data source `azurerm_resources` (plural) should return 0..n resources in a list.
A data source `azurerm_resource` (singular) should return 0..1 resources (`null` or the resource itself)
- It should fail, if more than one resource matches the tagging criteria
- It maybe even could fail for zero resources, if a flag was set in the data source definition (e.g. `must_match = true`)

I got inspired by C#'s Enumerable methods (`Enumerable.Select`, `Enumerable.First`, `Enumerable.FirstOrDefault`) with select working on Azure Resource Tags...

**Comment by AdamCoulterOz** [comment]
@LaurentLesle & @BHoggs - the reason that `resource_group_name` isn't currently exported by `azurerm_resources` is because the underlying azure-sdk-for-go api being used doesn't provide that value, most likely because not all resources have either a `subscription_id` or a `resource_group_name`:

https://github.com/Azure/azure-sdk-for-go/blob/f531174e50dc985270a91713d205c6ddc449e378/services/resources/mgmt/2020-06-01/resources/models.go#L1750-L1779

I was considering if it would be work creating a new data resource for parsing a resourceId to extract the component parts (i.e. `subscription_id`, `resource_group_name` and `name`)

**Comment by BHoggs** [comment]
@AdamCoulterOz I actually came up with a regex expression that does exactly that. It's an option, but I wouldn't recommend it as it's bit of a hack!

```hcl
locals {
    resource_map = regex(
        "(?i)^/Subscriptions/(?P<subscription_id>[^/]+)/resourceGroups/(?P<resource_group>[^/]+)/providers/(?P<provider>[^/]+)/.+/(?P<resource_name>.+)$",
        var.resource_id
    )
}
```

This will return the following parameters:
* `local.resource_map.subscription_id`
* `local.resource_map.resource_group`
* `local.resource_map.provider`
* `local.resource_map.resource_name`

**Comment by tombuildsstuff** [comment]
@AdamCoulterOz that's tracked in #1466 fwiw

**Comment by favoretti** [comment]
Closing this in favor of #1466
