### ISSUE TITLE
Support for login without an assigned subscription

### ISSUE THREAD

**Issue by SimonTheLeg** [hashicorp/terraform-provider-azurerm#5731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Functionality is exactly the same as described in #2025, however for a different reason: By having the possibility to assign roles on a management group instead of a subscription level, there is no need for the user/SPP that runs terraform to have a subscription assigned.

To give a more real world example: We have build a terraform module that uses both azuread and azurerm providers to create an Azure Application (azuread) and then assign it a role on a Management Group level (azurerm); Here's a short excerpt:

```hcl
resource azurerm_role_definition meshcloud_replicator {
  name        = "meshcloud-replicator"
  scope       = var.scope
  description = "..."

  permissions {
    actions = [
       "*",
    ]
  }

  assignable_scopes = [
    var.scope
  ]
}

resource azuread_application meshcloud_replicator {
  name = var.spp_name 
}

resource azuread_service_principal meshcloud_replicator {
  application_id = azuread_application.meshcloud_replicator.application_id
}

resource azurerm_role_assignment meshcloud_replicator {
  scope              = var.scope
  role_definition_id = azurerm_role_definition.meshcloud_replicator.id
  principal_id       = azuread_service_principal.meshcloud_replicator.id
}
```
The user/SPP running `terraform apply` would not need to be assigned to any subscription to sucessfully create the resources, but currently has to so or the apply fails (see #2025)

If you are planning to add Management Groups to the AzureAD provider, that of course could also solve this issue.

### References

* #2025

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
