### ISSUE TITLE
Support for Custom Routes on an Azure Virtual Network Gateway Point to Site VPN

### ISSUE THREAD

**Issue by jaredtrog** [hashicorp/terraform-provider-azurerm#5809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support defining custom routes for point to site VPN users allows additional routes to be specified beyond what is included in BGP or the VNET. This can be done easily enough in PowerShell post deployment but why not use the power of Terraform? :)

I looked through open/closed issues and current PRs and didn't find this request so my apologies if I missed something that already exists.

### New or Affected Resource(s)

* azurerm_virtual_network_gateway

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_network_gateway" "example" {
  name                = "test"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false
  sku           = "Basic"

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = azurerm_public_ip.example.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.example.id
  }

  vpn_client_configuration {
    address_space = ["10.2.0.0/24"]

    custom_routes = ["10.10.0.0/24",
                    "10.20.0.0/24",
                    "172.16.0.0/16"]

    root_certificate {
      name = "DigiCert-Federated-ID-Root-CA"

      public_cert_data = <<EOF
CERTDATA
EOF

    }

    revoked_certificate {
      name       = "Verizon-Global-Root-CA"
      thumbprint = "912198EEF23DCAC40939312FEE97DD560BAE49B1"
    }
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-p2s-advertise-custom-routes

**Comment by AndresFPineros** [comment]
Is the current work-around a local-exec?

**Comment by chriskinsman** [comment]
This looks like it has landed however changing the custom_route recreates the gateway.

This means adding a simple route takes ~20 minutes.  Is there a way to add routes without recreation?

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
