### ISSUE TITLE
OnlyOneGroupIdPermitted Private link service connection

### ISSUE THREAD

**Issue by dwizzle204** [hashicorp/terraform-provider-azurerm#5820]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azurerm v1.44.0

### Affected Resource(s)

* `azurerm_private_endpoint`

### Terraform Configuration Files

```hcl
resource "azurerm_private_endpoint" "main" {
  for_each            = var.storage_account
  name                = azurerm_storage_account.main[each.key].name
  location            = data.azurerm_resource_group.main[each.key].location
  resource_group_name = data.azurerm_resource_group.main[each.key].name
  subnet_id           = data.azurerm_subnet.main[each.key].id

  private_service_connection {

    name                           = format("%s-pl", azurerm_storage_account.main[each.key].name)
    is_manual_connection           = "false"
    private_connection_resource_id = azurerm_storage_account.main[each.key].id
    subresource_names              = ["blob", "file", "queues"]
  }
  depends_on = [azurerm_storage_account.main]
}

```

### Expected Behavior

Terraform to create the link for all the subresources listed

### Actual Behavior

Error: Error creating Private Endpoint "test" (Resource Group "test-rg"): network.PrivateEndpointsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="OnlyOneGroupIdPermitted" Message="Private link service connection /subscriptions/test/resourceGroups/test-rg/providers/Microsoft.Network/privateEndpoints/test/privateLinkServiceConnections/test-pl has the following group Ids: blob, file, queues. Only one group Id is permitted when connecting to a first-party resource (/subscriptions/test/resourceGroups/test-rg/providers/Microsoft.Storage/storageAccounts/test)." Details=[]

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sunnynazar** [comment]
I am also facing the same issue , i am using az tf provider 2.7.0 and tf version 0.12.26.

But when i check azure portal , i see that there is possibility to attach only one sub-resource of storage account not multiple. So, that might explain the issue .

**Comment by rstarov** [comment]
It stated in https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview [https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-overview ](url)
Maybe it makes sense to update https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/private_endpoint

When using private endpoints for Azure services, traffic is secured to a specific private link resource. The platform performs an access control to validate network connections reaching only the specified private link resource. **To access additional resources within the same Azure service, additional private endpoints are required.**

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
