### ISSUE TITLE
Support for setting API Management capacity per region

### ISSUE THREAD

**Issue by jnancel** [hashicorp/terraform-provider-azurerm#5857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For Azure API Management, when activating geo-replication in the portal, it's possible to set the Capacity per region, having different values on each region.

But in the provider, `additional_location` only takes `location` as an argument. I suppose the provider is currently using the `sku` value to set the same number of units per region.

It'd be great if a `capacity` parameter could be added to the `additional_location` block to be able to set units per region.

### New or Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management" "example" {
  ...
  additional_location {
    location = "eastus2"
    capacity = 3
  }
  ...
}
```

**Comment by andrediasbr** [comment]
When the API Management deployment includes a virtual private network and you try to add a new location, you have to specify the vnet / subnet for new location.

This request could add a new parameter called subnet_id in order to support this scenario.  

```
resource "azurerm_api_management" "example" {
  ...
  additional_location {
    location = "eastus2"
    capacity = 3
    subnet_id = "...."
  }
  ...
}
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
