### ISSUE TITLE
azurerm_virtual_machine_scale_set_extension not running

### ISSUE THREAD

**Issue by hbuckle** [hashicorp/terraform-provider-azurerm#5860]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

Terraform v0.12.21
+ provider.azurerm v1.44.0

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_scale_set_extension" "test" {
  name                         = "init-script"
  virtual_machine_scale_set_id = azurerm_windows_virtual_machine_scale_set.test.id
  publisher                    = "Microsoft.CPlat.Core"
  type                         = "RunCommandWindows"
  type_handler_version         = "1.1"
  auto_upgrade_minor_version   = true
  settings = jsonencode({
    script = split("\n", file("${path.module}/init.ps1"))
  })
  protected_settings = jsonencode({
    parameters = [
      {
        Name  = "input"
        Value = data.external.ip_address.result.privateIpAddress
      },
    ]
  })
}
```

### Description / Feedback

I'm trying out the new `azurerm_virtual_machine_scale_set_extension` resource, and I may be missing something, but although the extensions are created they don't seem to actually run. I've used the above example on the old VM scale set resource and it runs the script fine, but with the new resource nothing is run. Querying with the Azure CLI shows

```json
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": null,
  "name": "init-script",
  "protectedSettings": null,
  "provisionAfterExtensions": [],
  "provisioningState": null,
  "publisher": "Microsoft.CPlat.Core",
  "settings": {
    "script": [
      "param (",
      "  [string]$input",
      ")",
      "$ErrorActionPreference = \"Stop\"",
      "$ProgressPreference = \"SilentlyContinue\"",
      "Write-Host test"
    ]
  },
  "type": "RunCommandWindows",
  "typeHandlerVersion": "1.1"
}
```

**Comment by hbuckle** [comment]
I think I figured this out - because the extension is added to the scale set after it is created Azure does not run the extension on existing instances. If you add a new instance to the scale set then the extension is run, or Upgrade the existing instances to the latest model.
I believe setting upgrade_mode to Automatic would achieve this, but that requires a health probe to be configured as well.

Anyway, this behaviour should probably be documented as it's pretty confusing when migrating from the old all in one resource

**Comment by arestarh** [comment]
Hi,

Next issue reported on **Terraform Providers Azure** Hashicorp forum probably not directly related to this specific Github issue, but it is related to the fact that 
 azurerm_virtual_machine_scale_set_extension **_applies VMSS extension to the scale set after it is created_**:
https://discuss.hashicorp.com/t/azurerm-windows-virtual-machine-scale-set-extensions/6388

**Comment by hbuckle** [comment]
I ended up adding a provisioner to the extension resource to update the existing instances after adding the extension

```hcl
  provisioner "local-exec" {
    interpreter = ["cmd", "/c"]
    command     = "az vmss wait --created -n ${azurerm_windows_virtual_machine_scale_set.elastic_data.name} -g ${azurerm_resource_group.elastic.name}"
  }

  provisioner "local-exec" {
    interpreter = ["cmd", "/c"]
    command     = "az vmss update-instances --instance-ids * -n ${azurerm_windows_virtual_machine_scale_set.elastic_data.name} -g ${azurerm_resource_group.elastic.name}"
  }
```

No idea what to do about (idiotic) extensions like service fabric that insist on being added at creation though

**Comment by anhowe** [comment]
This is related to #5976.   The fix here is to inline the extension similar to 1.X `azurerm_virtual_machine_scale_set_extension`.  As you mention by not in lining extension with the VMSS object, the extension installs and is stuck in "Creating" state until you run a rolling upgrade on the VMSS, and requires a health probe to set to automatic.

Another workaround is to use cloud-init, but cloud-init doesn't cause the VM to fail on the failure of the script. Also, cloud-init doesn't have the ability to take secrets like custom script's "protectedSettings" field.

Additionally this results in a performance penalty, since applying extensions in two steps causes the whole deployment to take much longer as it has to wait until all nodes are up before applying the extension, and the additional slowness of the rolling upgrade.

**Comment by neil-yechenwei** [comment]
@hbuckle , may I ask which property value in azure cli result you mentioned indicates the extension is not running?

```
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": null,
  "name": "init-script",
  "protectedSettings": null,
  "provisionAfterExtensions": [],
  "provisioningState": null,
  "publisher": "Microsoft.CPlat.Core",
  "settings": {
    "script": [
      "param (",
      "  [string]$input",
      ")",
      "$ErrorActionPreference = \"Stop\"",
      "$ProgressPreference = \"SilentlyContinue\"",
      "Write-Host test"
    ]
  },
  "type": "RunCommandWindows",
  "typeHandlerVersion": "1.1"
}
```

**Comment by elias-p** [comment]
I have similar issue the monitoring extension is not working after provision the vmss on this module and previous module is working without issue.

**Comment by denis-vogrincic** [comment]
Any update on progress?

**Comment by jackofallops** [comment]
Inline extensions for VMSS was released as a Beta feature in v2.26.0, please see the docs for the `azurerm_windows_virtual_machine_scale_set` and `azurerm_linux_virtual_machine_scale_set` for use.

I'm going to close this for now, we can re-open if this does not resolve this issue.

**Comment by jackofallops** [comment]
Re-opening - there is an associated issue in the `azurerm_virtual_machine_scale_set_extension` that needs to be addressed.

**Comment by ShreyasNBS** [comment]
@jackofallops I tried using the extension block, and now get an error stating 

> Automatic repairs not supported for this Virtual Machine Scale Set because a health probe or health extension was not provided.

Below is my code

```
resource "azurerm_linux_virtual_machine_scale_set" "artifactory_primary_scaleset" {
  name                            = "${module.names.standard["virtual-machine-scaleset"]}-artifactory-primary"
  location                        = data.azurerm_resource_group.artifactory_rg.location
  resource_group_name             = data.azurerm_resource_group.artifactory_rg.name
  upgrade_mode                    = "Manual"
  zones                           = ["1", "2", "3"]
  zone_balance                    = true
  sku                             = var.azure_vm_sku
  instances                       = 1
  admin_username                  = var.vm_admin_username
  admin_password                  = random_password.artifactory_vm_password.result
  computer_name_prefix            = "${module.names.standard["virtual-machine-scaleset"]}-artifactory-primary"
  disable_password_authentication = false

  boot_diagnostics {
    storage_account_uri = azurerm_storage_account.artifactory_storage_account_boot_diagnostics.primary_blob_endpoint
  }

  automatic_instance_repair {
    enabled = true
  }

  network_interface {
    name                          = "${module.names.standard["virtual-machine-scaleset"]}-${var.artifactory_primary_nic}"
    primary                       = true
    enable_accelerated_networking = true
    ip_configuration {
      primary                                = true
      name                                   = "${module.names.standard["ip-config"]}-${var.artifactory_primary_ipconfig_name}"
      subnet_id                              = data.azurerm_subnet.artifactory_private_subnet.id
      load_balancer_backend_address_pool_ids = [azurerm_lb_backend_address_pool.artifactory_bep.id]
    }
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
    disk_size_gb         = 250
  }

  data_disk {
    lun                  = 0
    caching              = "ReadWrite"
    disk_size_gb         = var.disk_size_gb
    storage_account_type = "Premium_LRS"
  }

  extension {
    name                       = "agent_script_artifactory_primary"
    publisher                  = "Microsoft.Azure.Extensions"
    type                       = "CustomScript"
    type_handler_version       = "2.1"
    auto_upgrade_minor_version = true
    settings                   = <<SETTINGS
    {
    }
    SETTINGS
    protected_settings         = <<PROTECTED_SETTINGS
    {
        "script": "${base64encode("${data.template_file.init.rendered}")}"
    }
    PROTECTED_SETTINGS
    provision_after_extensions = ["agent_script_artifactory_apphealth_primary"]
  }

  extension {
    name                       = "agent_script_artifactory_apphealth_primary"
    publisher                  = "Microsoft.ManagedServices"
    type                       = "ApplicationHealthLinux"
    type_handler_version       = "1.0"
    auto_upgrade_minor_version = true
    settings = jsonencode(
      {
        "protocol"    = "http"
        "port"        = "8081"
        "requestPath" = "/artifactory/webapp/#/login"
      }
    )
    protected_settings = <<PROTECTED_SETTINGS
    {
    }
    PROTECTED_SETTINGS
  }

  source_image_id = var.rhel_hardened_image

  depends_on = [azurerm_lb.artifactory_lb, azurerm_lb_rule.artifactory_lb_https_rule, azurerm_lb_backend_address_pool.artifactory_bep, azurerm_storage_account.artifactory_storage_account_boot_diagnostics, azurerm_postgresql_database.artifactory_postgresqlsrv_artifactorydb]
  tags       = merge(var.global_settings.tags, local.twistlock_tags)
}
```


What am I missing?

Edit: I had a look at the official example, but they are using load balancer probe. In our case, LB probe does not work over https because we are using a self signed cert form Hashicorp Vault.

https://github.com/Azure/azure-quickstart-templates/blob/master/201-vmss-automatic-repairs-slb-health-probe/azuredeploy.json

**Comment by patademahesh** [comment]
@ShreyasNBS We are also getting the same error at the time of VMSS creation. Please suggest any quick fix.

`Error: Error creating Linux Virtual Machine Scale Set "production-cms-vmss" (Resource Group "production-centralindia-resource-group"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Automatic repairs not supported for this Virtual Machine Scale Set because a health probe or health extension was not provided."`

**Comment by tombuildsstuff** [comment]
@ShreyasNBS support for Application Health Extensions is being tracked in #8120

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
