### ISSUE TITLE
Add container_access_type as Optional Parameter to Storage Account static_website Block

### ISSUE THREAD

**Issue by MattMencel** [hashicorp/terraform-provider-azurerm#5921]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to be able to set the `container_access_type` to the $web container that gets created when you enable the static_website feature on a storage account.

It should default to "private", duplicating what happens with the setting on `azurerm_storage_container`.

> container_access_type - (Optional) The Access Level configured for this Container. Possible values are blob, container or private. Defaults to private.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

``` hcl
resource "azurerm_storage_account" "website" {
  name                     = "website"
  location                 = "centralus"
  resource_group_name      = "my_rg
  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "GRS"

  static_website {
    container_access_type = "blob"
  }
}
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
