### ISSUE TITLE
Api gateway new operations not being added

### ISSUE THREAD

**Issue by woeterman94** [hashicorp/terraform-provider-azurerm#5955]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform 0.12.21

The API gateway is not properly updating. New operations are not being added. And thus the web app cannot reach the new endpoints.
![image](https://user-images.githubusercontent.com/5755057/75688897-8db20b80-5ca0-11ea-8e7f-92836a0840cf.png)

My terraform config file

```
resource "azurerm_api_management_api" "api" {
  resource_group_name   =   var.Apim-ResourceGroupName
  api_management_name   =   var.Apim-Name
  name                  =   "${var.Apim-ApiName}"
  revision              =   var.Apim-ApiRevision
  display_name          =   var.Apim-ApiDisplayName
  path                  =   var.Apim-ApiPath
  protocols             =   ["https"]
  service_url           =   var.Apim-ApiServiceUrl
 import {
    content_format      =   "swagger-link-json"
    content_value       =   var.Apim-ApiContentValue
  }
  subscription_key_parameter_names{
    header              =   var.Apim-ApiSubscriptionHeader
    query               =   "subscription-key"
  }
}

resource "azurerm_api_management_product" "product" {
  resource_group_name   =   var.Apim-ResourceGroupName
  api_management_name   =   var.Apim-Name
  product_id            =   var.Apim-ProductId
  display_name          =   var.Apim-ProductDisplayName
  description           =   var.Apim-ProductDescription
  subscription_required =   true
  subscriptions_limit   =   100
  approval_required     =   true
  published             =   true


}

resource "azurerm_api_management_product_api" "productapi" {
  api_name              =  "${var.Apim-ApiName}"
  product_id            =   var.Apim-ProductId
  resource_group_name   =   var.Apim-ResourceGroupName
  api_management_name   =   var.Apim-Name
  depends_on = [azurerm_api_management_product.product,azurerm_api_management_api.api]

} 
```

The gateway is configured to import a swagger file, but when deploying the new operations are not being added.

 Am I missing something? 

Edit: it works when I delete the API gateway API in azure and redeploy, but this is not ideal.

**Comment by woeterman94** [comment]
14 days and counting!

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
