### ISSUE TITLE
Spurious changes on function app settings

### ISSUE THREAD

**Issue by jjgriff93** [hashicorp/terraform-provider-azurerm#5972]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: `v0.12.18`
AzureRM provider version: `1.40.0`

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "trafficdata" {
  name                      = "func-${var.appname}-traffic-${var.environment}"
  resource_group_name       = azurerm_resource_group.trafficdata.name
  location                  = var.location
  app_service_plan_id       = azurerm_app_service_plan.trafficdata.id
  storage_connection_string = azurerm_storage_account.trafficdatafunctions.primary_connection_string
  version                   = "~2"
  app_settings              = {
      "CITIES_CONFIG_URL"               = var.config_cities_url
      "TRAFFICTILES_OUTPUT_URL"         = azurerm_storage_container.traffictiles.id
      "TRAFFICROUTES_OUTPUT_URL"        = azurerm_storage_container.trafficroutes.id
      "AZURE_MAPS_ENDPOINT"             = "https://atlas.microsoft.com/"
      "KEY_VAULT"                       = azurerm_key_vault.traffic_collection.vault_uri
      "NUM_OF_ROUTES_PER_CITY"          = var.nb_of_routes
      "FUNCTIONS_WORKER_RUNTIME"        = "python"
      "WEBSITE_NODE_DEFAULT_VERSION"    = "~10"
      "APPINSIGHTS_INSTRUMENTATIONKEY"  = var.appinsights_instrumentation_key
  }
```

### Debug Output

https://gist.github.com/jjgriff93/94b0b6c652682a8adc4527c590c95f34

### Expected Behavior

No changes should be detected for App Settings as the configuration was not modified.

### Actual Behavior

On every run Terraform tries to update app settings when they should be ignored. There are no changes between runs on our App Settings but the system/provider seems to apply its own which vary each time.

### Steps to Reproduce

1. Create a standard tf script for deploying a Function App with Appllication settings as above.
2. `terraform apply`
3. `terraform apply` again

* #0000

**Comment by ajklotz** [comment]
Just recently complained about this on SO

https://stackoverflow.com/questions/67740193/terraform-reports-a-change-to-application-insights-key-on-every-plan-that-is-run?noredirect=1#comment119768066_67740193

**Comment by tim-krehan** [comment]
Same Issue here.

Is there any workarround or plans to update this?

**Comment by tombuildsstuff** [comment]
hi @jjgriff93 

Apologies for the delayed reply here.

Taking a look through here the `azurerm_function_app` resource has since been superseded by the [`azurerm_linux_function_app`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app) and [`azurerm_windows_function_app`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app) resources. Whilst the existing `azurerm_function_app` resource continues to be available in 3.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_function_app`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_function_app) and [`azurerm_windows_function_app`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_function_app) resources going forward.

Thanks!

**Comment by ncmuthu** [comment]
I am using azurerm_linux_function_app, I still have the issue.

```
# Enabling App Insights
resource "azurerm_application_insights" "function-app-test" {
  name                = "${var.function_app_name}-appinsights"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  application_type    = "web"
  depends_on = [
    azurerm_resource_group.function-app-test,
  ]
}
# Creating Function app
resource "azurerm_linux_function_app" "function-app-test" {
  name                       = "${var.function_app_name}"
  location                   = "${var.location}"
  resource_group_name        = "${var.resource_group_name}"
  service_plan_id            = azurerm_service_plan.function-app-test.id
  storage_account_name       = "${var.storage_account_name}"
  storage_account_access_key = azurerm_storage_account.function-app-test.primary_access_key
  app_settings = {
    "FUNCTIONS_WORKER_RUNTIME"            = "python",
    "AzureWebJobsDisableHomepage"         = "true",
    "APPINSIGHTS_INSTRUMENTATIONKEY"      = "${azurerm_application_insights.function-app-test.instrumentation_key}",
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"
    "AzureWebJobsDashboard"               = ""
  }
  site_config {
    ftps_state               = "FtpsOnly" # To disable plain ftp
    always_on                = true       # Enable this to avoid the cold start time of compute
    health_check_path        = "/"        # Enable FunctionApp health check
    application_stack {
      docker {
        registry_url     = "docker.io"
        image_name       = "ncmuthu2015/azurefunctionsimage"
        image_tag        = "latest"
        }
    }
    app_service_logs {
      retention_period_days = "365"
    }
  }
  https_only           = "true"           # Disable http access for function URL 
  /*
  identity {
    type         = "UserAssigned"
    identity_ids = [ azurerm_user_assigned_identity.managed_identity.id ]
  }
  */
}
```
``` 
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the     
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.functionapp.azurerm_linux_function_app.function-app-test will be updated in-place
  ~ resource "azurerm_linux_function_app" "function-app-test" {
      ~ app_settings                      = {
          + "APPINSIGHTS_INSTRUMENTATIONKEY"      = (sensitive)
```
