### ISSUE TITLE
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Did not find functions with language [python].

### ISSUE THREAD

**Issue by erwinsalubre** [hashicorp/terraform-provider-azurerm#5977]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "function" {
  depends_on                = [data.azurerm_storage_account_sas.storage_sas]
  app_service_plan_id       = azurerm_app_service_plan.plan.id
  location                  = azurerm_resource_group.eventgridrg.location
  name                      = "func-apps"
  resource_group_name       = azurerm_resource_group.eventgridrg.name
  storage_connection_string = azurerm_storage_account.storage_account.primary_connection_string
  version                   = "~2"

    app_settings = {
      https_only                            = true
      FUNCTIONS_WORKER_RUNTIME              = "python"
      AzureWebJobsStorage                   = azurerm_storage_account.storage_account.primary_connection_string
      CleanupPackerImagesConnection         = var.function_storage_connection_string
      FUNCTIONS_EXTENSION_VERSION           = "~2"
      FUNCTION_APP_EDIT_MODE                = "readonly"
      HASH                                  = base64encode(filesha256("${var.function_name}.zip"))
      WEBSITE_RUN_FROM_PACKAGE              = "${azurerm_storage_blob.storage_blob.url}${data.azurerm_storage_account_sas.storage_sas.sas}"
    }
}
```

### Debug Output

```
The function runtime is unable to start. Microsoft.Azure.WebJobs.Script: Did not find functions with language [python].
Session Id: 0ebad842dbfc426e8ac26ba7a1219f11

Timestamp: 2020-03-02T03:46:59.477Z
```

### Expected Behavior

Function Apps and Functions should be deployed and running.

### Actual Behavior

Function Apps and Functions is deployed but Function App is not running with the error above.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by 6403wency413** [comment]
Any update on this? It's quite critical in our operation to get this resolved.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
