### ISSUE TITLE
Object output schema in documentation

### ISSUE THREAD

**Issue by bhummerstone** [hashicorp/terraform-provider-azurerm#6054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be really helpful to document the object schema for a resource so that we can plan outputs/lookups more easily

### New or Affected Resource(s)

* azurerm_*

### Potential Terraform Configuration

Not TF code, more documentation suggestion :-)

### References

* #0000

**Comment by tracypholmes** [comment]
Hi @bhummerstone! Could you provide us with a bit more information and/or an example of what you're looking for? This way we can make sure any moves we make are in the right direction. Thank you for submitting this issue 😃

**Comment by bhummerstone** [comment]
Sure! When you run terraform output (https://www.terraform.io/docs/commands/output.html) against a deployed resource, you get a load of useful information. When writing a custom module, you can output this object and re-use it in other resources/modules

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
