### ISSUE TITLE
RetryableError destroying VM Extension while also destroying NSG on the subnet

### ISSUE THREAD

**Issue by ssemyan** [hashicorp/terraform-provider-azurerm#6080]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.23
+ provider.azurerm v2.1.0

### Affected Resource(s)

* `azurerm_network_security_group`
* `azurerm_subnet_network_security_group_association`
* `azurerm_linux_virtual_machine`
* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.1.0"
  features {}
}

data "azurerm_subnet" "master_etc_subnet" {
  name                 = "subnet-1"
  virtual_network_name = "mybug-network"
  resource_group_name  = "mybug-rg"
}

# Create SG
resource "azurerm_network_security_group" "etcd" {
  name                = "dev-k8s-etcd"
  location            = "westus2"
  resource_group_name = "mybug-rg"
}

# Attach the NSG to the subnet 
resource "azurerm_subnet_network_security_group_association" "etcd_nsg_subnet_associate" {
  subnet_id                 = data.azurerm_subnet.master_etc_subnet.id
  network_security_group_id = azurerm_network_security_group.etcd.id
}

# Create the nic
resource "azurerm_network_interface" "etcd-nic" {
  name                = "etcdhost1-nic"
  location            = "westus2"
  resource_group_name = "mybug-rg"
  
  ip_configuration {
    name                          = "internal"
    subnet_id                     = data.azurerm_subnet.master_etc_subnet.id
    private_ip_address_allocation = "Dynamic"
  }
}

# Create the VM 
resource "azurerm_linux_virtual_machine" "etcd-vm" {
  name                            = "etcdhost1"
  location                        = "westus2"
  resource_group_name             = "mybug-rg"
  size                            = "Standard_F2"
  admin_username                  = "etcadmin"
  admin_password                  = "MyPassFoo123!"
  disable_password_authentication = false
  zone                            = 1

  network_interface_ids = [
    azurerm_network_interface.etcd-nic.id,
  ]

  os_disk {
    name                 = "etcdhost1-os-disk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  # Just use Ubuntu for now, can use a custom image later
  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}

# Use the custom script extension to run the init.sh script
resource "azurerm_virtual_machine_extension" "etcd-ext" {
    name                       = "etcdhost1-ext"
    virtual_machine_id         = azurerm_linux_virtual_machine.etcd-vm.id
    publisher                  = "Microsoft.Azure.Extensions"
    type                       = "CustomScript"
    type_handler_version       = "2.1"
    auto_upgrade_minor_version = "false"

    settings = <<SETTINGS
    {
        "commandToExecute": "hostname && uptime"
    }
    SETTINGS
}
```

### Debug Output

https://gist.github.com/ssemyan/7f307f4e1207c513e57b7c1ce7d649e5

### Expected Behavior

Destroy should work as expected. 

### Actual Behavior

ata.azurerm_subnet.master_etc_subnet: Refreshing state...
azurerm_network_security_group.etcd: Refreshing state... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Network/networkSecurityGroups/dev-k8s-etcd]
azurerm_subnet_network_security_group_association.etcd_nsg_subnet_associate: Refreshing state... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Network/virtualNetworks/mybug-network/subnets/subnet-1]
azurerm_network_interface.etcd-nic: Refreshing state... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Network/networkInterfaces/etcdhost1-nic]
azurerm_linux_virtual_machine.etcd-vm: Refreshing state... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Compute/virtualMachines/etcdhost1]
azurerm_virtual_machine_extension.etcd-ext: Refreshing state... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Compute/virtualMachines/etcdhost1/extensions/etcdhost1-ext]
azurerm_subnet_network_security_group_association.etcd_nsg_subnet_associate: Destroying... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Network/virtualNetworks/mybug-network/subnets/subnet-1]
azurerm_virtual_machine_extension.etcd-ext: Destroying... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Compute/virtualMachines/etcdhost1/extensions/etcdhost1-ext]
azurerm_subnet_network_security_group_association.etcd_nsg_subnet_associate: Still destroying... [id=/subscriptions/SUBGUID...ks/mybug-network/subnets/subnet-1, 10s elapsed]
azurerm_virtual_machine_extension.etcd-ext: Still destroying... [id=/subscriptions/SUBGUID...nes/etcdhost1/extensions/etcdhost1-ext, 10s elapsed]
azurerm_subnet_network_security_group_association.etcd_nsg_subnet_associate: Destruction complete after 10s
azurerm_network_security_group.etcd: Destroying... [id=/subscriptions/SUBGUIDresourceGroups/mybug-rg/providers/Microsoft.Network/networkSecurityGroups/dev-k8s-etcd]
azurerm_network_security_group.etcd: Destruction complete after 1s
azurerm_virtual_machine_extension.etcd-ext: Still destroying... [id=/subscriptions/SUBGUID...nes/etcdhost1/extensions/etcdhost1-ext, 20s elapsed]
azurerm_virtual_machine_extension.etcd-ext: Still destroying... [id=/subscriptions/SUBGUID...nes/etcdhost1/extensions/etcdhost1-ext, 30s elapsed]
azurerm_virtual_machine_extension.etcd-ext: Still destroying... [id=/subscriptions/SUBGUID...nes/etcdhost1/extensions/etcdhost1-ext, 40s elapsed]
azurerm_virtual_machine_extension.etcd-ext: Still destroying... [id=/subscriptions/SUBGUID...nes/etcdhost1/extensions/etcdhost1-ext, 50s elapsed]
azurerm_virtual_machine_extension.etcd-ext: Still destroying... [id=/subscriptions/SUBGUID...nes/etcdhost1/extensions/etcdhost1-ext, 1m0s elapsed]

Error: Code="RetryableError" Message="A retryable error occurred."

*Note: only the NSG is deleted, everything else remains because it got stuck deleting the vm extension and everything else depends on it*

### Steps to Reproduce

1. `terraform apply` (should be no errors)
1. `terraform destroy` (will end with error)

### Important Factoids

This error does not occur if you remove the custom script extension - thus it may be a race condition.

**Comment by fcatacut** [comment]
Try adding `depends_on = [azurerm_network_security_group.etcd, azurerm_subnet_network_security_group_association. etcd_nsg_subnet_associate]` to your `azurerm_virtual_machine_extension` as a workaround.

We ran into this issue and were able to get `destroy` to successfully complete using this approach.  We ended up adding `depends_on` to all of the VM-related resources in our module: `azurerm_linux_virtual_machine`, `azurerm_virtual_machine_extension`, `azurerm_managed_disk`, and `azurerm_virtual_machine_data_disk_attachment`.  This might be a little overkill, but we were running into similar "RetryableError" errors.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
