### ISSUE TITLE
Support for new RP DataBoxJob

### ISSUE THREAD

**Issue by neil-yechenwei** [hashicorp/terraform-provider-azurerm#6101]
Description
There is a request here to support data box job, which lets you send terabytes of local data into Azure in a quick, inexpensive, and reliable way. After discussion between our PM and hashicorp owners, we will continue to work on the implementation.
Overview: https://docs.microsoft.com/en-us/azure/databox/data-box-overview
Rest api spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databox/resource-manager/Microsoft.DataBox/stable/2019-09-01/databox.json
PS: https://docs.microsoft.com/en-us/powershell/module/az.databox/new-azdataboxjob?view=azps-3.4.0

Affected resource provider
Microsoft.DataBox

Potential Terraform Configuration
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = var.location
}

resource "azurerm_storage_account" "example" {
  name                     = "${var.prefix}storageaccount"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location

  account_kind             = "StorageV2"
  account_tier             = "Standard"
  account_replication_type = "RAGRS"
}

resource "azurerm_databox_job" "example" {
  name                = "${var.prefix}-databoxjob"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  contact_details {
    name         = "DataBoxJobTester"
    emails       = ["some.user@example.com"]
    phone_number = "+112345678912"
  }

  destination_account {
    type               = "StorageAccount"
    storage_account_id = azurerm_storage_account.example.id
  }

  preferred_shipment_type = "MicrosoftManaged"

  shipping_address {
    city              = "San Francisco"
    country           = "US"
    postal_code       = "94107"
    state_or_province = "CA"
    street_address_1  = "16 TOWNSEND ST"
  }

  sku_name = "DataBox"
}
```

**Comment by tombuildsstuff** [comment]
Since this one isn't possible at this time [due to the Service shipping real hardware to folks](https://github.com/hashicorp/terraform-provider-azurerm/pull/6103#issuecomment-760502502) - I'm going to suggest that we close this issue for the moment - but should there be customer demand for this issue (and a means of testing it becomes available) then we can look to reopen this/add support in the future
