### ISSUE TITLE
New resource `azurerm_advisor`

### ISSUE THREAD

**Issue by yupwei68** [hashicorp/terraform-provider-azurerm#6119]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---
Hi @tombuildsstuff  @katbyte ,I'm currently working on a new resource `azurerm_advisor_suppresion`. 
Please refer [Advisor Doc](https://docs.microsoft.com/en-us/azure/advisor/advisor-overview).  

On portal:
![image](https://user-images.githubusercontent.com/56525716/76734699-709c3300-679e-11ea-8097-17b4f5e6d7bc.png)

`azurerm_advisor_suppresion` enables a particular recommendation got from `Advisor` to be postponed for a specific duration or infinitely. Refer to [powershell](https://docs.microsoft.com/en-us/powershell/module/az.advisor/disable-azadvisorrecommendation?view=azps-3.6.1).

Do you think it make sense to create this resource in Terraform? 

---
If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by favoretti** [comment]
@yupwei68 looks like this is already in, so can be closed? Or am I missing something here?

**Comment by tombuildsstuff** [comment]
Fixed via #6867 - thanks @favoretti
