### ISSUE TITLE
Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by SadokLadhari** [hashicorp/terraform-provider-azurerm#6151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.23
azurerm provider : 2.1.0

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "main" {
...
  dynamic "probe" {
    for_each = local.backends
     content {
     ...
     }
   }
...

}
```

### Expected Behavior
Should iterates through each key-value-pair of the local.backends and creates probes (7 elements in my case)  without errors.

When I repeat Terraform apply the ERROR disappear ! 

### Actual Behavior

> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for
> module.application-gateway.azurerm_application_gateway.main to include
> new values learned so far during apply, provider
> "registry.terraform.io/-/azurerm" produced an invalid new value for .probe:
> block count changed from 1 to 7.
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
