### ISSUE TITLE
Support for automatically tainting resources in tfstate when they fail creating

### ISSUE THREAD

**Issue by Wiston999** [hashicorp/terraform-provider-azurerm#6156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Taint resources in tfstate when they are not properly created while `terraform apply`ing. It would be helpful that the provider stores the resources as tainted when they fail so the next time `terraform apply` they are automatically removed and recreated instead of be left in an unconsistent state (they doesn't exist in tfstate but they exist in a failed state in Azure Portal).

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
