### ISSUE TITLE
azurerm_storage_management_policy doesn't allow `zero` values for base_blob actions.

### ISSUE THREAD

**Issue by jackofallops** [hashicorp/terraform-provider-azurerm#6158]
A recent bug fix to this resource surfaced a secondary issue whereby a user configured `0` value for any of `tier_to_cool_after_days_since_modification_greater_than`, `delete_after_days_since_modification_greater_than`, or `tier_to_archive_after_days_since_modification_greater_than` treated as the parameter is not set.

This means that currently a minimum value of `1` is available for these parameters.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_storage_management_policy`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_management_policy" "test" {
  storage_account_id = azurerm_storage_account.test.id

  rule {
    name    = "singleActionRule"
    enabled = true
    filters {
      prefix_match = ["container1/prefix1"]
      blob_types   = ["blockBlob"]
    }
    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than = 0
        delete_after_days_since_modification_greater_than = 30
      }
      snapshot {
        delete_after_days_since_creation_greater_than = 30
      }
    }
  }
}```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The target rule should have the named action enabled with a value set of `0`

### Actual Behavior

The target rule is not active and has no value set.

### Steps to Reproduce

Set any of the named properties to `0` in a valid resource config as above.

### Important Factoids

N/A

### References

#5803 - Bug surfaced by changes to enable users to set single properties as per #4580 

* #0000

**Comment by dpiche174** [comment]
I also noticed this surprising behavior.  If an action is not specified in `base_blob`, Terraform enables the action and set it to 0 days:
![image](https://user-images.githubusercontent.com/835846/78815132-c75feb80-799d-11ea-9f20-bcb8acae3f3c.png)

**Comment by jackofallops** [comment]
> I also noticed this surprising behavior. If an action is not specified in `base_blob`, Terraform enables the action and set it to 0 days:

Hi @dpiche174 
Can you let me know which versions of Terraform and Provider you're seeing this behaviour in?
Thanks!

**Comment by dpiche174** [comment]
Sure! Here is this.

Terraform v0.12.19
azurerm provider v2.1.0

**Comment by jackofallops** [comment]
Thanks @dpiche174 
The bug fix that this issue references is the one that resolves the issue you observed above, and was released in v2.3.0 of the provider.  Not specifying a given action now disables that action.  It had the unfortunate side effect of making it not possible to set a `0` value for those fields, however.  We'll look to address that in a future release.

**Comment by dpiche174** [comment]
Just tried azurem v2.5.0 and it works.  Thank you!

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

**Comment by admsteck** [comment]
@favoretti Which issue was addressed?  The issue of unspecified actions being enabled mentioned by @dpiche174, or the original issue?  I'm using provider version 2.64.0 and still cannot set the delete_after_days_since_modification_greater_than to 0.  I get the following error:

`
Error: creating Azure Storage Management Policy "...redacted...": storage.ManagementPoliciesClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned 
an error. Status=400 Code="InvalidManagementPolicyRule" Message="ManagementPolicy rule deletetempfiles is invalid. Invalid value for parameter : baseBlob For more information, see - 
https://aka.ms/managementpolicyexamples"
`

The only workaround I can see is to set the value to 1, which isn't really a valid workaround since it changes how the rule would work.
