### ISSUE TITLE
Support for filtering by tags for azurerm_key_vault

### ISSUE THREAD

**Issue by jaredledvina** [hashicorp/terraform-provider-azurerm#6160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It'd be helpful to have the Data Source `azurerm_key_vault` support finding KeyVaults by tags instead of only by their name. This will help us work with KeyVaults where the name is uniquely generated to avoid collisions when purge_protection is enabled and we're rebuilding environments. 

### New or Affected Resource(s)

* azurerm_key_vault

### Potential Terraform Configuration

```hcl
data "azurerm_key_vault" "example" {
  resource_group_name = "some-resource-group"
  filter {
    name   = "environment"
    values = ["staging"]
  }
}
```

### References

https://docs.microsoft.com/en-us/rest/api/keyvault/vaults/listbyresourcegroup

Note: It doesn't seem like the API actually allows filtering via the request but, it seems to be something possible via https://docs.microsoft.com/en-us/rest/api/resources/resources/list. Unsure what makes sense when it comes to implementing this.

**Comment by jpreese** [comment]
Great timing! I agree that this should be applied to key_vault, but most other resources as well. I have a more generic "able to filter all the things" in #6154

**Comment by tombuildsstuff** [comment]
hey @jaredledvina 

Thanks for opening this issue.

Due to the way the singular data sources are defined (e.g. `azurerm_key_vault`) it'd likely make more sense to introduce a new `azurerm_key_vaults` data source here which supports these filters (which returns 1 or more key vaults) - as such I've tagged this as a new data source, but this sounds good to me 👍 

Thanks!

**Comment by favoretti** [comment]
Closing this one in favor of #6154 to keep discussion consolidated
