### ISSUE TITLE
Documentation for Service Principal with Client Certificate Creates an invalid format for Azure

### ISSUE THREAD

**Issue by pbstrein** [hashicorp/terraform-provider-azurerm#6187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
Authenticating as a Service Principal using a Client Certificate

### Expected Behavior

Following the steps provided in the documentation should create a cert that can be used by Microsoft to authenticate as a Service Principal. 

### Actual Behavior
The Azure CLI runs into errors as it tries to authenticate using a cert created from the documentation. 

### Steps to Reproduce
Follow steps as listed in the documentation. 
1. `openssl req -newkey rsa:4096 -nodes -keyout "service-principal.key" -out "service-principal.csr"`
2. `openssl x509 -signkey "service-principal.key" -in "service-principal.csr" -req -days 365 -out "service-principal.crt"`
3. `openssl pkcs12 -export -out "service-principal.pfx" -inkey "service-principal.key" -in "service-principal.crt"`
4. Create service principal by following steps in documentation
- use `https://terra.form`
- upload `service-principal.crt`
- give `Contributor` role
5. If logged in the Azure CLI, logout by running `az logout`
6. Login as the Service Principal using `az login --service-principal --username APP_ID --tenant TENANT_ID --password /path/to/cert`

An error similar to the following should appear. 
```
Error:Invalid Certificate: Expected Start of Certificate to be '-----BEGIN RSA PRIVATE KEY-----'
```

*Note:* I could not test this by setting env variables and running `terraform init` as said in the documentation due to #6181, but logging in should be enough to demonstrate documentation issues. 

I also get similar error when I try running in Azure-Powershell using `Connect-AzAccount -ServicePrincipal -ApplicationID <app ID> -Tenant <tenant ID> -CertificateThumbprint <thumbprint>`
```
PS C:\EpicSource\Cloud\terraform\Stamps\Azure\HSWeb Pair> Connect-AzAccount -ServicePrincipal -ApplicationId $appId -Ten
ant $tenantId -CertificateThumbprint $thumbPrint
Connect-AzAccount : The private key is not present in the X.509 certificate.
At line:1 char:1
+ Connect-AzAccount -ServicePrincipal -ApplicationId $appId -Tenant $te ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Connect-AzAccount], NotSupportedException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Profile.ConnectAzureRmAccountCommand
```
### Important Factoids

I believe this issue comes b/c the documentation does not attach a private key to the certificate. If you run `az ad sp create-for-rbac --create-cert`, a cert that has a private and public key gets created, and those certs do work in Azure CLI and Azure Powershell.  

I am using Azure CLI in a Powershell window, but I don't think that should make a difference. 

### References
#6181 
https://github.com/Azure/azure-cli/issues/9970

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
