### ISSUE TITLE
Support for Retention by data type on azurerm_log_analytics_workspace

### ISSUE THREAD

**Issue by ricohomewood** [hashicorp/terraform-provider-azurerm#6199]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow to set retention by data type on log analytics workspace.

### New or Affected Resource(s)

* azurerm_log_analytics_workspace

### Potential Terraform Configuration

```hcl
resource "azurerm_log_analytics_workspace" "test" {
  name                = "workspacetest-01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "PerGB2018"
  retention_in_days   = 30
  data_type_retention = {
    name = "ContainerLog"
    retention_in_days = 60
  }
}
```

### References

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/manage-cost-storage#change-the-data-retention-period

Example API call ...
```
PUT /subscriptions/00000000-0000-0000-0000-00000000000/resourceGroups/MyResourceGroupName/providers/Microsoft.OperationalInsights/workspaces/MyWorkspaceName/Tables/SecurityEvent?api-version=2017-04-26-preview
    {
        "properties": 
        {
            "retentionInDays": 730
        }
    }
```

**Comment by C123R** [comment]
Hi there, Can I give it a shot?

**Comment by favoretti** [comment]
@C123R by all means, thank you!

**Comment by christianrondeau** [comment]
@C123R did you begin an implementation? I didn't find a branch in your GitHub profile.

**Comment by C123R** [comment]
Hi @christianrondeau, Not yet - I'm still waiting for the go from contributors. Just wanted to make sure it wasn't already in the works?

**Comment by favoretti** [comment]
Not that I'm aware of. Feel free to submit a PR!

**Comment by markrzasa** [comment]
Is anyone working on this? If not, I have some code that I could contribute to hopefully close this issue. I'd just need a week or two to get the code ready for a PR.
Thanks.

**Comment by christianrondeau** [comment]
@stephybun I saw on the related PR that this was on hold until the new Azure SDK was available, and the PR itself was abandoned; I guess this also means this resource will be revisited? I'm not sure I can contribute but more information on this issue's dependencies status would be nice :) Thanks!

**Comment by markrzasa** [comment]
@stephybun  If the SDK is ready, I can rework and recommit my PR.
