### ISSUE TITLE
azurerm_log_analytics_solution produces inconsistent final plan when using Resource Group with upper case letters

### ISSUE THREAD

**Issue by jaygridley** [hashicorp/terraform-provider-azurerm#6202]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform `1.12.23`
* azurerm `2.2.0`

### Affected Resource(s)

* `azurerm_log_analytics_solution`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "logs" {
  name     = "UKS-PROD-LOGS-RG-001"
  location = "uksouth"
}

resource "azurerm_log_analytics_workspace" "spoke" {
  name                = "UKS-PROD-LAW-001"
  resource_group_name = azurerm_resource_group.logs.name
  location            = azurerm_resource_group.logs.location

  sku               = "PerGB2018"
  retention_in_days = var.logs_retention_in_days
}

resource "azurerm_log_analytics_solution" "security" {
  solution_name         = "Security"
  location              = azurerm_log_analytics_workspace.spoke.location
  resource_group_name   = azurerm_log_analytics_workspace.spoke.resource_group_name
  workspace_resource_id = azurerm_log_analytics_workspace.spoke.id
  workspace_name        = azurerm_log_analytics_workspace.spoke.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/Security"
  }
}
```

### Debug Output

```
Error: Provider produced inconsistent final plan

When expanding the plan for
module.common.azurerm_log_analytics_solution.security to include new
values learned so far during apply, provider "registry.terraform.io/-/azurerm"
produced an invalid new value for .resource_group_name: was
cty.StringVal("UKS-PROD-LOGS-RG-001"), but now
cty.StringVal("uks-prod-logs-rg-001").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.

Releasing state lock. This may take a few moments...
```

### Expected Behavior

Apply finished without error.

### Actual Behavior

Apply failed with error. It is due to inconsistency in the returned Resource Group name where the Solution is deployed to. When Resource Group container uppercase letters, the returned value is with lowercase instead.

### Steps to Reproduce

1. have clean account
1. `terraform plan`
1. `terraform apply`

### Important Factoids

* re-plan and apply works without issue

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems there is a problem in terraform while referencing resource group by indirect approach. I suggest to reference resource group directly in `azurerm_log_analytics_solution`.

Sample code:
```
resource "azurerm_log_analytics_solution" "security" {
  ......
  location              = azurerm_resource_group.logs.location
  resource_group_name   = azurerm_resource_group.logs.name
  ......
}
```

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
