### ISSUE TITLE
azurerm terraform storage backed is broken for usung SAS

### ISSUE THREAD

**Issue by tezzigator** [hashicorp/terraform-provider-azurerm#6213]
### Terraform (and AzureRM Provider) Version
terraform 0.12.23
azure 2.2.0

### Affected Resource(s)
Azurerm storage backend

```
terraform {
  required_version = "= 0.12.23"
  backend "azurerm" {
    resource_group_name  = "REDACTED"
    storage_account_name = "REDACTED"
    container_name       = "REDACTED"
    key                  = "REDACTED" 
    sas_token = "se=2021-03-31&sp=racwdl&spr=https&sv=2018-11-09&sr=c&sig=REDACTED
    }
```

### Debug Output
Error: Error inspecting states in the "azurerm" backend:
    storage: service returned error: StatusCode=404, ErrorCode=ResourceNotFound, ErrorMessage=The specified resource does
not exist.
RequestId:27c1a34d-f01e-0007-26ba-ffce6c000000
Time:2020-03-21T19:51:01.4711570Z, RequestInitiated=Sat, 21 Mar 2020 19:51:01 GMT, RequestId=27c1a34d-f01e-0007-26ba-ffce6c000000, API Version=2014-02-14, QueryParameterName=, QueryParameterValue=

### Steps to Reproduce
terraform init

### Important Factoids
SAS was created via:
`az storage container generate-sas --account-name REDACTED--account-key REDACTED --name REDACTED--permissions acdlrw --https-only --expiry 2021-03-31`

### References
https://www.terraform.io/docs/backends/types/azurerm.html
https://docs.microsoft.com/en-us/azure/storage/blobs/storage-blob-user-delegation-sas-create-cli

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
