### ISSUE TITLE
r/function_app: support for enabling Incoming client certificates and Certificate exclusion paths

### ISSUE THREAD

**Issue by jungopro** [hashicorp/terraform-provider-azurerm#6243]
Hello

According to [this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2004) there is an option to enable `Incoming client certificates` on `azurerm_function_app`. However:

- There is no documentation on how to implement it
- There is no mention of whether or not one can add `Certificate exclusion paths` once `Incoming client certificates` is enabled

I was able to accomplish it via the az cli:

```console
az functionapp update --set clientCertEnabled=true --set clientCertExclusionPaths="/foo;/bar;/hello;/world" --name jungoafadsgasdge-functio --resource-group azure-functions-test-rg
```

Is it supported in Terraform out-of-the-box and if so can you please share an example code on how to accomplish that?

Thanks 
Omer

**Comment by mattduguid** [comment]
Similar issue on azurerm_app_service, can toggle client_cert_enabled, but cant specify client_cert_exclusion_paths. Will likely look to use null_resource/provisioner/local-exec to sort for now.

**Comment by howlowck** [comment]
implementation for `client_cert_mode` = "Required", "Optional", or "Ignore" is in PR #11161

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
