### ISSUE TITLE
Support for azurerm_function_app_custom_hostname_binding

### ISSUE THREAD

**Issue by collinstevens** [hashicorp/terraform-provider-azurerm#6248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

- Support for custom hostname bindings currently exists for App Services, but does not exist for Function Apps, see https://www.terraform.io/docs/providers/azurerm/r/app_service_custom_hostname_binding.html.
- Support for a new resource type, azurerm_function_app_custom_hostname_binding, would replace the current manual process of creating the custom hostname binding through the Azure Portal.

### New or Affected Resource(s)

* azurerm_function_app_custom_hostname_binding

**Comment by oleksiypavlenko** [comment]
It would be great to see this feature.
The proposed configuration:

```
resource "azurerm_function_app_custom_hostname_binding" "example" {
  hostname              = "www.mywebsite.com"
  function_app_name     = azurerm_function_app.example.name
  resource_group_name   = azurerm_resource_group.example.name
}
```

**Comment by drdamour** [comment]
do we need this?  `azurerm_app_service_custom_hostname_binding` works with functions apps as is

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
