### ISSUE TITLE
Support for function_app vnet integration

### ISSUE THREAD

**Issue by buissjer** [hashicorp/terraform-provider-azurerm#6267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The field `virtual_network_name` was removed from the `site_config` block since azurerm provider version 2.0.
I'm currently working in a previous version which allow me to use this field in an `ignore_changes` block like following (for both app_service and app_function):
```
  lifecycle {
    ignore_changes = [
      site_config[0].vnetName,
      app_settings
    ]
```

I need this to avoid breaking the vnet integration did by ARM templates.

How can I do the same in 2.0 version?

**New or Affected Resource(s)**

- azurerm_app_service
- azurerm_function_app

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
