### ISSUE TITLE
Passwords with $ character are stripped without warning/error

### ISSUE THREAD

**Issue by chrissewell1234** [hashicorp/terraform-provider-azurerm#6268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_sql_server`

### Terraform Configuration Files

```hcl
variable sql-sa-password {
  type   = string
  value = "Pa$$word"
}

...

resource "azurerm_sql_server" "rtgs-sql-server" {
  administrator_login          = "sql-admin"
  administrator_login_password = var.sql-sa-password

}
```
### Expected Behavior

Either 'Pa$$word' should have been set as the password or some kind of warning/error should be given

### Actual Behavior

The $ are stripped from the string leaving 'Paword' as the admin password

### Steps to Reproduce

1. Create a SQL Server instance with an admin password containing $ and no string interprolation syntax.

2. Attempt to login to SQL server

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
