### ISSUE TITLE
Zone-redundant option not available in Public LB via Terrafrom

### ISSUE THREAD

**Issue by Sagar2133** [hashicorp/terraform-provider-azurerm#6296]
Description :- 

We have configured nodes under different Availability Zone and when we are trying to configure those nodes under Public load balancer with  "Zone-redundant" option we are getting below error, It seems it's out of support.

* azurerm_public_ip.XXXX-pip01: Error Creating/Updating Public IP "XXXX-pip01" (Resource Group "XX-rgXX"): network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidAvailabilityZone" Message="**The zone(s) 'Zone-redundant' for resource 'Microsoft.Network/publicIPAddresses/XXXX-pip01' is not supported****. The supported zones for location 'westeurope' are '1,2,3'"

Could you please check this and provide me the the suitable tf setting/module.

**Comment by rajatrawat99** [comment]
I am facing the same issue while trying to create **azurerm_public_ip** by giving zones option as zone-reduntant. I get the same error:

> Error: Error Creating/Updating Public IP "iiq-perf-lab-nat-ip" (Resource Group "iiq-perf-lab-group"): network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidAvailabilityZone" Message="The zone(s) 'zone-reduntant' for resource 'Microsoft.Network/publicIPAddresses/iiq-perf-lab-nat-ip' is not supported. The supported zones for location 'westus2' are '1,2,3'"

error says we can choose zones as 1, 2 or 3 but azure does give us  'zone-reduntant' option atleast in azure portal.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
