### ISSUE TITLE
Changing tags in azurerm_network_interface resets enable_ip_forwarding, then flip-flops

### ISSUE THREAD

**Issue by pedrohdz** [hashicorp/terraform-provider-azurerm#6326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azurerm v2.3.0
```

### Affected Resource(s)

* `azurerm_network_interface`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

locals {
  location = "West Europe"
  base_name = "testing"
}

resource "azurerm_resource_group" "example" {
  name     = local.base_name
  location = local.location
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  enable_ip_forwarding = true
  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
  tags = {
    foo = "value_foo"
    bar = "value_bar"
    haa = "value_haa"
    goo = "value_goo"
    boo = "value_boo"
    #hoo = "value_hoo"  # Uncomment on the second apply.
  }
}
```

### Panic Output

N/A

### Expected Behavior

1. Changes to `tags` should have no impact on `enable_ip_forwarding` and vice versa.
2. The state of the deployment should not be flip-flopping `enable_ip_forwarding` and `tags`.

### Actual Behavior

Once deployed, an addition to the `tags` will set `enable_ip_forwarding` to false.  After that, subsequent applies will switch between:

- Setting `enable_ip_forwarding` to `true`, silently deleting `tags`.
- Adding `tags` and silently setting `enable_ip_forwarding` to `false`.

### Steps to Reproduce

1. `terraform apply`, you can run this multiple times and the state of the deployment is stable.
2. Un-comment the `hoo = "value_hoo"` line.
3. `terraform apply`
4. `terraform apply` - It will want to set `enable_ip_forwarding` to `true`
5. `terraform apply` - It will want to add the `tags` back.
6. GOTO `4`

The plan never hits a stable state.

### Important Factoids

None.

### References

- None

**Comment by noderat** [comment]
I am encountering this issue but with `enable_accelerated_networking` instead of `enable_ip_forwarding`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
