### ISSUE TITLE
Unable to provision Azure Monitor Logging with 

### ISSUE THREAD

**Issue by markti** [hashicorp/terraform-provider-azurerm#6332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.3.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl

/* in a different module */
/* https://dev.azure.com/persistent-cloud-northamerica/_git/terraform-azure?path=%2Fmonitoring%2Flog_analytics%2Fmain.tf */

resource "azurerm_log_analytics_workspace" "workspace" {
  name                = var.name
  location            = var.location
  resource_group_name = var.resource_group_name
  sku                 = "PerGB2018"
  retention_in_days   = 30
}

resource "azurerm_log_analytics_solution" "solution_vminsights" {
  solution_name         = "VMInsights"
  location              = var.location
  resource_group_name   = var.resource_group_name
  workspace_resource_id = azurerm_log_analytics_workspace.workspace.id
  workspace_name        = azurerm_log_analytics_workspace.workspace.name

  plan {
    publisher       = "Microsoft"
    product         = "OMSGallery/VMInsights"
    promotion_code  = ""
  }
}

/* in a different module */
/* https://dev.azure.com/persistent-cloud-northamerica/_git/terraform-azure?path=%2Fvm%2Flinux%2Flinux_monitor */


resource "azurerm_virtual_machine_extension" "vm_ext_linuxagent" {

  name                          = "DependencyAgentLinux"
  virtual_machine_id            = module.vm_baseline.id
  publisher                     = "Microsoft.Azure.Monitoring.DependencyAgent"
  type                          = "DependencyAgentLinux"
  type_handler_version          = "9.10"
  auto_upgrade_minor_version    = true
  depends_on                    = [module.vm_baseline]

  settings = <<SETTINGS
    {
    }
SETTINGS

  tags = {
    app = var.app_name
    env = var.env_name
  }
}

resource "azurerm_virtual_machine_extension" "vm_ext_omsagent" {
  name                          = "OMSExtension"
  
  virtual_machine_id            = module.vm_baseline.id
  
  publisher                     = "Microsoft.EnterpriseCloud.Monitoring"
  type                          = "OmsAgentForLinux"
  type_handler_version          = "1.7"
  auto_upgrade_minor_version    = true

  depends_on                    = [module.vm_baseline]

  settings = <<SETTINGS
    {
      "workspaceId": "${var.log_analytics_workspace_id}",
      "azureResourceId": "${module.vm_baseline.id}",
      "stopOnMultipleConnections": "true"
    }
  SETTINGS

  protected_settings = <<SETTINGS
    {
      "workspaceKey": "${var.log_analytics_workspace_key}"
    }
  SETTINGS

  tags = {
    app = var.app_name
    env = var.env_name
  }
}

```

### Panic Output

> Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
> 
>   on vm/linux/linux_monitor/main.tf line 18, in resource "azurerm_virtual_machine_extension" "vm_ext_linuxagent":
>   18: resource "azurerm_virtual_machine_extension" "vm_ext_linuxagent" {
> 
> 
> 
> Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded
> 
>   on vm/linux/linux_monitor/main.tf line 39, in resource "azurerm_virtual_machine_extension" "vm_ext_omsagent":
>   39: resource "azurerm_virtual_machine_extension" "vm_ext_omsagent" {

### Expected Behavior

- DependencyAgentLinux should provision and display a status of "Provisioning Succeded"
- OMSExtension should provision and display a status of "Provisioning Succeded"

Virtual Machine should start pushing logs to Log Analytics workspace that was supplied.

### Actual Behavior

- DependencyAgentLinux provisioned and displayed a status of "Provisioning Succeded"
- OMSExtension failed to provision and display a status of "(unavailable)"

Virtual Machine is not pushing logs to the log analytics workspace.

### Steps to Reproduce

1. clone this repo "https://dev.azure.com/persistent-cloud-northamerica/_git/terraform-azure"
2. supply your own Azure Account
3. 'terraform init'
4. `terraform apply`

### Important Factoids

Public Azure

**Please Note**

- I am able to manually add a VM provisioned with the "linux_baseline" module to the same Log Analytics / VMInsights solution (see LABVM002)
- I reproduced the inputs into the 'azurerm_virtual_machine_extension' from the deployment templates I used when doing the same manually from the portal to LABVM002

**Comment by Satyricon** [comment]
Adding `workspaceId` under `settings` for `DependencyAgentLinux` helps. At least works for me.

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
