### ISSUE TITLE
Not able to create application gateway v2 with the SSL certificate for backend http setting

### ISSUE THREAD

**Issue by vivek99singh** [hashicorp/terraform-provider-azurerm#6340]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---
Not able to create Azure application gateway and getting the below error:
Error: Error Creating/Updating Application Gateway "example-appgateway" (Resource Group "HWE-IAM-DMZ-WEST-EUROPE-RG"): network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceReference" Message="Resource /subscriptions/4cbcff46-75ea-420f-bef3-bdea0e39fe9d/resourceGroups/HWE-IAM-DMZ-WEST-EUROPE-RG/providers/Microsoft.Network/applicationGateways/example-appgateway/sslCertificates/Internal-RootCA referenced by resource /subscriptions/4cbcff46-75ea-420f-bef3-bdea0e39fe9d/resourceGroups/HWE-IAM-DMZ-WEST-EUROPE-RG/providers/Microsoft.Network/applicationGateways/example-appgateway/httpListeners/HWE-IAM-DMZ-WEST-EUROPE-httplstn was not found. Please make sure that the referenced resource exists, and that both resources are in the same region." Details=[]

I am using root certificate for trusted root for backend https setting

data "azurerm_resource_group" "example" {
  name     = "HWE-IAM-DMZ-WEST-EUROPE-RG"
}

data "azurerm_virtual_network" "example" {
  name                = "HWE-IAM-DMZ-WEST-EUROPE"
  resource_group_name = data.azurerm_resource_group.example.name
}

data "azurerm_subnet" "frontend" {
  name                 = "LIAM03-APPGW-SUB"
  resource_group_name  = data.azurerm_resource_group.example.name
  virtual_network_name = data.azurerm_virtual_network.example.name
}

resource "azurerm_public_ip" "example" {
  name                = "example-pip"
  resource_group_name = data.azurerm_resource_group.example.name
  location            = data.azurerm_resource_group.example.location
  allocation_method   = "Dynamic"
}

# since these variables are re-used - a locals block makes this more maintainable
locals {
  backend_address_pool_name      = "${data.azurerm_virtual_network.example.name}-beap"
  frontend_port_name             = "${data.azurerm_virtual_network.example.name}-feport"
  frontend_ip_configuration_name = "${data.azurerm_virtual_network.example.name}-feip"
  http_setting_name              = "${data.azurerm_virtual_network.example.name}-be-htst"
  listener_name                  = "${data.azurerm_virtual_network.example.name}-httplstn"
  request_routing_rule_name      = "${data.azurerm_virtual_network.example.name}-rqrt"
  redirect_configuration_name    = "${data.azurerm_virtual_network.example.name}-rdrcfg"
}
data "azurerm_network_interface" "target" {
 name                = "hwe-dev-liam03242"
 resource_group_name = "HWE-IAM-DMZ-WEST-EUROPE-RG"
}

data "azurerm_key_vault" "example" {
  name                = "liamkeyvault"
  resource_group_name = "HWE-IAM-DMZ-WEST-EUROPE-RG"
}

data "azurerm_key_vault_secret" "example" {
  name         = "dev-test"
  key_vault_id = data.azurerm_key_vault.example.id
}

resource "azurerm_application_gateway" "network" {
  name                = "example-appgateway"
  resource_group_name = data.azurerm_resource_group.example.name
  location            = data.azurerm_resource_group.example.location

  sku {
    name     = "Standard_v2"
    tier     = "Standard_v2"
    capacity = 2
  }

  gateway_ip_configuration {
    name      = "my-gateway-ip-configuration"
    subnet_id = data.azurerm_subnet.frontend.id
  }

  frontend_port {
    name = local.frontend_port_name
    port = 443
  }

  frontend_ip_configuration {
    name                 = local.frontend_ip_configuration_name
    public_ip_address_id = azurerm_public_ip.example.id
  }

  ssl_certificate {
        name     = "dev-test"
        data     = filebase64("dev-test.pfx")
        password = ""
  }

  backend_address_pool {
    name = local.backend_address_pool_name
    ip_addresses = ["10.2.0.9"]
  }

  http_listener {
    name                           = local.listener_name
    frontend_ip_configuration_name = local.frontend_ip_configuration_name
    frontend_port_name             = local.frontend_port_name
    protocol                       = "Https"
    ssl_certificate_name           = "Internal-RootCA"
  }
 
  backend_http_settings {
    name                  = local.http_setting_name
    cookie_based_affinity = "Disabled"
    port                  = 443
    protocol              = "Https"
    request_timeout       = 1
  }

  trusted_root_certificate {
        name = "Internal-RootCA"
        data = filebase64("rootCA.cer")
  }

  probe {
    name                = "default"
    protocol            = "Https"
    path                = "/"
    interval            = 5
    host                = "localhost"
    timeout             = 4
    unhealthy_threshold = 3
  }

 request_routing_rule {
    name                       = local.request_routing_rule_name
    rule_type                  = "Basic"
    http_listener_name         = local.listener_name
    backend_address_pool_name  = local.backend_address_pool_name
    backend_http_settings_name = local.http_setting_name
  }

}

The code is as mentioned below: 
If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
