### ISSUE TITLE
azurerm_nat_gateway and azurerm_virtual_machine_extension destroy causes "retryable error"

### ISSUE THREAD

**Issue by sdcscripts** [hashicorp/terraform-provider-azurerm#6361]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
+ provider.azurerm v2.0.0
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_nat_gateway`
* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
git clone https://github.com/sdcscripts/issue_with_nat
cd issue_with_nat
mv terraform.tfvars.example terraform.tfvars
terraform init
terraform apply 
terraform destroy
```
During the destroy always get the following 

Error: Code="RetryableError" Message="A retryable error occurred."

### Expected Behavior

Should have created all resources and then the destroy should have destroyed all resources

### Actual Behavior

Create happens fine but the destroy fails every time. 

### Steps to Reproduce

git clone https://github.com/sdcscripts/issue_with_nat
cd issue_with_nat
mv terraform.tfvars.example terraform.tfvars
terraform init
terraform apply 
terraform destroy

### Important Factoids

I have managed to resolve the problem by using a depends_on with the natgw module , in effect stopping the NAT G/W resources being created before the VMextensions are created and enforcing that the NAT G/W is deleted before the VMextension resources. This resolves the problem so it's basically some kind of race condition / deadlock with NAT G/W and VM extension on destroy operation that causes the "retryable error".

The retryable error sometimes does not allow a repeat terraform destroy because the state file becomes corrupted.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
