### ISSUE TITLE
Support Azure DevOps Service Connections in Terraform

### ISSUE THREAD

**Issue by Hjortsberg** [hashicorp/terraform-provider-azurerm#6387]
### Community Note
- Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
**Note**: This scenario is when running Terraform in automation in Azure DevOps Pipelines.
The subscription that holds the ACR is _not_ the same used in the TF script to create the resources.

When deploying E.G an App Service that pulls a docker image from an Azurer Container Registry or simmilar container registry, it would be nice to be able to utilize the Azure DevOps Service Connections already defined. This would reduce the amount of credentials that needs to be supplied by Pipelines secret variables or KeyVault. This is a problem since our Operations team would like to avoid having service principals credentials defined as secret vars or in KeyVault.

I would like to be able to replace the following `DOCKER_REGISTRY_SERVER`-fields in app settings 
with a single ACR Service Connection.
### Terraform example config from Sam Merrell
``` 
resource "azurerm_app_service" "containertest" {
name                = "someuniquename01"
location            = "eastus2"
resource_group_name = "test-resource-group"
app_service_plan_id = "${azurerm_app_service_plan.containertest.id}"

site_config {
always_on        = true
linux_fx_version = "DOCKER|${data.azurerm_container_registry.containertest.login_server}/testdocker-alpine:v1"
 }

app_settings {
 "WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"
"DOCKER_REGISTRY_SERVER_URL"          = "https://${data.azurerm_container_registry.containertest.login_server}"
"DOCKER_REGISTRY_SERVER_USERNAME"     = "${data.azurerm_container_registry.containertest.admin_username}"
"DOCKER_REGISTRY_SERVER_PASSWORD"     = "${data.azurerm_container_registry.containertest.admin_password}"
  }
}
```

### Affected Resource
- azurerm_app_service

**Comment by favoretti** [comment]
This can be achieved by using terraform-provider-azuredevops to either fetch or create service connections and then use them via a remote state for instance.

Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
