### ISSUE TITLE
azurerm_template_deployment with file: "Error parsing JSON: invalid character 'ï' looking for beginning of value"

### ISSUE THREAD

**Issue by ericregnier** [hashicorp/terraform-provider-azurerm#6395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.23
- azurerm v2.1.0 (haven't tried previous versions)

### Affected Resource(s)

azurerm_template_deployment

### Terraform Configuration Files

Here's an example of my config file which reads the ARM template body from a json file:

```hcl
resource "azurerm_template_deployment" "item" {
  name                    = local.parameters.ResourceName
  resource_group_name     = module.lookup.azurerm_resource_group.name
  template_body           = file("${path.module}/hello.json")
  parameters              = local.parameters
  deployment_mode         = "Incremental"
}
```

### Steps to Reproduce

1. Prepare your ARM template json file (default UTF-8 encoding) in Visual Studio. I used Azure Resource Group VS project type

1. Prepare the terraform scripts as per above 

1. init and execute ```terraform apply```

### Actual Behavior

Failed. ```template_body```  outputted with error message: "Error parsing JSON: invalid character 'ï' looking for beginning of value".

Terminal output:
```
Terraform will perform the following actions:

  # module.logic_app.azurerm_template_deployment.item will be created
  + resource "azurerm_template_deployment" "item" {
      + deployment_mode     = "Incremental"
      + id                  = (known after apply)
      + name                = "ice-RiskGradeModelSynchronization-ibdev"
      + outputs             = (known after apply)
      + parameters          = {
          + "CDSEnvironment" = "orga8b76b7f.crm6"
        }
      + resource_group_name = "ice-ibdev-rg"
      + template_body       = "Error parsing JSON: invalid character 'ï' looking for beginning of value"
    }
```
For it to work, I had to change the encoding of the files to ANSI.

### Expected Behavior

```template_body``` loaded and outputted successfully with UTF-8 encoding for the ARM templates as per the documentation and VS defaults (i.e. https://www.terraform.io/docs/configuration/functions/file.html)

Terminal output:
```
# module.logic_app.azurerm_template_deployment.item will be created
  + resource "azurerm_template_deployment" "item" {
      + deployment_mode     = "Incremental"
      + id                  = (known after apply)
      + name                = "ResourceName"
      + outputs             = (known after apply)
      + parameters          = {
          + "Param1" = "value"
        }
      + resource_group_name = "RGName"
      + template_body       = jsonencode(blahblahblah)
      blahblahblah
```

### Important Factoids/Environment

- Using Azure Resource Group VS project to manage the ARM templates
- Using VS Code to manage and execute Terraform
- Running on Windows 10

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
