### ISSUE TITLE
Logic App Action URL Authentication missing

### ISSUE THREAD

**Issue by GregoryFrance** [hashicorp/terraform-provider-azurerm#6401]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

My goal is to create a Logic app Http Action.

This HTTP action required an Authentication (Basic). 

I can' find any parameters with Terraform to set Atuthentication fields.

Is it missing in "azurerm_logic_app_action_http" ?

Than you,

**Comment by dcfsc** [comment]
We are unable to use this resource due to the missing authentication setting. I suppose I could wedge some ARM in, but that seems tacky.

**Comment by darren-johnson** [comment]
Hey, I just tried using azurerm_logic_app_action_custom instead and so far so good.

`resource "azurerm_logic_app_action_custom" "stuff" {
    body         = jsonencode(
        {
            inputs   = {
                authentication = {
                    audience = "https://vault.azure.net"
                    type     = "ManagedServiceIdentity"
                }
                method         = "GET"
                uri            = "https://keyvaultname.vault.azure.net/secrets/secretname?api-version=7.0"
            }
            runAfter = {}
            type     = "Http"
        }
    )
    logic_app_id = "/subscriptions/subscriptionid/resourceGroups/resourcegroup/providers/Microsoft.Logic/workflows/logicappname"
    name         = "actionname"
}`

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
