### ISSUE TITLE
Support for Data resource Metric Alert within Azure Monitor

### ISSUE THREAD

**Issue by abilous-ti** [hashicorp/terraform-provider-azurerm#6421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide Data resource for Metric Alert within Azure Monitor (such as azurerm_monitor_metric_alert).

### New or Affected Resource(s)

azurerm_monitor_metric_alert

**Comment by abilous-ti** [comment]
@katbyte Will it be implemented in nearest future?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
