### ISSUE TITLE
App GW HTTP Listener with SSL Cert

### ISSUE THREAD

**Issue by nycjay01** [hashicorp/terraform-provider-azurerm#6468]
We use the following as an undocumented workaround:

```
Upload SSL certificate to Azure Vault as a secret
```
```
az keyvault secret set --name "certificate" --vault-name "vault_name" --file "certificate.pfx" --encoding base64
```
```
Read the secret using Terraform data resource
```
```
data "azurerm_key_vault_secret" "certificate" {
    name         = "certificate"
    key_vault_id = var.key_vault_id
}
```

```
resource "azurerm_application_gateway" "example" {
    ssl_certificate {
        name     = certificate
        data       = data.azurerm_key_vault_secret.certificate.value
        password = var.password
    }
...
}
```

Hi there,

I tried this out and I am able to upload the cert as above. But I keep getting the error message below. Any pointers would be greatly appreciated.

```
Message="Password` specified for certificate /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/shared-rg/providers/Microsoft.Network/applicationGateways/aks01-appgw/sslCertificates/coreapicert is incorrect." Details=[]
```

Facts:
Cert is a 3rd part generated cert
I am on TF Enterprise
I have the password from the 3rd Party
Key Vault is in a separate resource group
I have full admin on subscription

**Comment by nycjay01** [comment]
Anyone? :-)

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
