### ISSUE TITLE
Azure IotHub set Default TTL, Retention Time and Delivery count

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-provider-azurerm#6499]
_This issue was originally opened by @srinivasansharath as hashicorp/terraform#24681. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
Hi,,

Wanted to check if there is a plan to add support for C2D parameters for Azure IotHub..

- Default TTL
- Feedback retention time
- Maximum delivery count

thanks..

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
