### ISSUE TITLE
Trouble peering vnets across subscriptions. 

### ISSUE THREAD

**Issue by jlombardo29** [hashicorp/terraform-provider-azurerm#6518]
Hi,  I saw a similar issue for this so I did double check that my service principal has access to both subs.   My error is 

> azurerm_virtual_network_peering.hub-to-wvd-peer: Creating...
> 
> Error: network.VirtualNetworkPeeringsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'CORE_RG' could not be found."
> 

I've confirmed the RG is in place and permissions are not an issue.  

Thanks for any direction on this.   The `hub-to-peer` vnet end is not managed by terraform which is why the values are hard coded for now. 

```
resource "azurerm_virtual_network_peering" "wvd-to-hub-peer" {
  name                      = "wvd-to-hub-peer"
  resource_group_name       = azurerm_resource_group.wvd-vnet-rg.name
  virtual_network_name      = azurerm_virtual_network.wvd-vnet-rg.name
  remote_virtual_network_id = "/subscriptions/012d1dc7-1220-347a-b6c7-daaaaaaaaaac/resourceGroups/CORE_RG/providers/Microsoft.Network/virtualNetworks/testvnet"

  allow_virtual_network_access = true
  allow_forwarded_traffic = true
  allow_gateway_transit   = false
  use_remote_gateways     = false
 # depends_on = [""]
}


```

```
resource "azurerm_virtual_network_peering" "hub-to-wvd-peer" {
  name                      = "hub-to-wvd-peer"
  resource_group_name       = "CORE_RG"
  virtual_network_name      = "testvnet"
  #remote_virtual_network_id = "azurerm_virtual_network.wvd-vnet-rg.name"
   remote_virtual_network_id = "/subscriptions/a21c4994-1662-4621-a881-2349841e9c3/resourceGroups/wvd-vnet-rg/providers/Microsoft.Network/virtualNetworks/wvd-vnet"
  allow_virtual_network_access = true
  allow_forwarded_traffic   = true
  allow_gateway_transit     = true
  use_remote_gateways       = false
 # depends_on = ["azurerm_virtual_network.spoke1-vnet", "azurerm_virtual_network.hub-vnet", "azurerm_virtual_network_gateway.hub-vnet-gateway"]
}


```

**Comment by misastovicek** [comment]
I would use another Azurerm provider for the subscription where Hub network resides.
This would be the provider code:
```hcl
provider "azurerm" {
  version = "~>2.0"

  features {}
}

provider "azurerm" {
  version         = "~>2.0"
  subscription_id = "a21c4994-1662-4621-a881-2349841e9c3"
  alias           = "hub"

  features {}
}
```
And this would be in the resource:
```hcl
resource "azurerm_virtual_network_peering" "hub-to-wvd-peer" {
  provider = azurerm.hub

  name                      = "hub-to-wvd-peer"
  resource_group_name       = "CORE_RG"
  virtual_network_name      = "testvnet"
  #remote_virtual_network_id = "azurerm_virtual_network.wvd-vnet-rg.name"
   remote_virtual_network_id = "/subscriptions/a21c4994-1662-4621-a881-2349841e9c3/resourceGroups/wvd-vnet-rg/providers/Microsoft.Network/virtualNetworks/wvd-vnet"
  allow_virtual_network_access = true
  allow_forwarded_traffic   = true
  allow_gateway_transit     = true
  use_remote_gateways       = false
 # depends_on = ["azurerm_virtual_network.spoke1-vnet", "azurerm_virtual_network.hub-vnet", "azurerm_virtual_network_gateway.hub-vnet-gateway"]
}
```

**Comment by heoelri** [comment]
@jlombardo29 not sure if you got this working in the meantime, i case not, i wrote a blog post on how to configure cross-subscription / cross-tenant virtual network peerings with terraform in azure including the required permissions, multiple provider definitions etc. https://medium.com/microsoftazure/configure-azure-virtual-network-peerings-with-terraform-762b708a28d4?source=friends_link&sk=5e49f7c3aa80480e90a15aba99c769b6

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
