### ISSUE TITLE
Imported storage account private endpoint and subsequent apply results in destroy/recreate

### ISSUE THREAD

**Issue by eehret** [hashicorp/terraform-provider-azurerm#6524]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.6.0

### Affected Resource(s)

* `azurerm_private_endpoint`
* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
# Configure where the project's back end is, i.e. where will the state be stored
terraform {
  backend "azurerm" {
    storage_account_name = "<redacted back end name>"
    container_name       = "tfstate"
    key                  = "rasa-appian.tfstate"
  }
}

# Configure the Azure Provider
provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=2.6.0"
  features {}
  subscription_id = "<redacted>"
}

resource "azurerm_storage_account" "stor_bugtest" {
  name                      = "<redacted storage account name>"
  resource_group_name       = "rg_RASA_APPIAN_STG"
  location                  = "canadacentral"
  account_kind              = "StorageV2"
  access_tier               = "Hot"
  account_replication_type  = "GRS"
  account_tier              = "Standard"
  enable_https_traffic_only = true
  network_rules {
    default_action = "Deny"
    bypass = [
      "AzureServices"
    ]
    ip_rules                   = []
    virtual_network_subnet_ids = []
  }
}

resource "azurerm_private_endpoint" "pe_stor_bugtest" {
  name                = "pe-<redacted storage account name>"
  resource_group_name = "rg_RASA_APPIAN_STG"
  location            = "canadacentral"
  subnet_id           = "<redacted subnet id>"

  private_service_connection {
    name                           = "pe-<redacted storage account name>"
    is_manual_connection           = false
    private_connection_resource_id = azurerm_storage_account.stor_bugtest.id
    subresource_names = [
      "file"
    ]
  }
}
```

### Expected Behavior

If possible, Terraform provider should have preserved the original case of the ID that was stored in the private_connection_resource_id attribute of the azurerm_private_endpoint.pe_stor_bugtest object. 

### Actual Behavior

The original case of the resource ID linked to the zurerm_private_endpoint.pe_stor_bugtest via the private_connection_resource_id attribute was not preserved.  On subsequent `terraform apply` commands, the resource is marked to be destroyed and recreated.
The desired result is that a `terraform apply` after the import will not result in any change to this attribute.

### Steps to Reproduce
1. In Azure, create a storage account.
2. In Azure, create a private endpoint for the storage account created in step 1.
3. Import the existing azurerm_storage_account, naming it `stor_bugtest`, i.e.:
`terraform import azurerm_storage_account <insert Azure Resource ID here>`
4. Import the existing azurerm_private_endpoint, naming it `pe_stor_bugtest`, i.e.:
`terraform import azurerm_private_endpoint <insert Azure Resource ID here>`
5. `terraform apply`, using the provided configuration file

### References

* #0000

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
