### ISSUE TITLE
Update of account_replication_type in azurerm_storage_account ends with the error StorageAccountTypeConversionNotAllowed

### ISSUE THREAD

**Issue by PeterUherek** [hashicorp/terraform-provider-azurerm#6526]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* `terraform - v0.12.24`
* `azurerm -  2.3.0`

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_storage_account" "example" {
  name                     = "storageaccountname"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "ZRS"

  tags = {
    environment = "staging"
  }
}
```

### Expected Behavior

I expected terraform will replace resource azurerm_storage_account if It is not possible to change it

### Actual Behavior
It fails with error: 
```
Error: Error updating Azure Storage Account type "configserviceebdxg7": storage.AccountsClient#Update: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="StorageAccountTypeConversionNotAllowed" Message="Storage account type Standard_ZRS cannot be changed to Standard_GRS."

  on ../../../modules/replication/main.tf line 495, in resource "azurerm_storage_account" "config_service_storage_account":
 495: resource "azurerm_storage_account" "config_service_storage_account" {
```

### Steps to Reproduce

1. `terraform apply`
2. Update account_replication_type  from ZRS to GRS
3. `terraform apply`

**Comment by PeterUherek** [comment]
There is was similiar bug https://github.com/terraform-providers/terraform-provider-azurerm/issues/110

**Comment by blame19** [comment]
Any update on this?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
