### ISSUE TITLE
Support for App Services Docker Container Logging 

### ISSUE THREAD

**Issue by ablyler** [hashicorp/terraform-provider-azurerm#6531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the ability to set the docker container logging property of app services via terraform.

`az webapp log config --name <app-name> --resource-group myResourceGroup --docker-container-logging filesystem`

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```
resource "azurerm_app_service" "example" {
  name                = "example-app-service"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  logs {
    docker_container = "filesystem"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/app-service/containers/configure-custom-container#access-diagnostic-logs

**Comment by jlienSage** [comment]
Actually, there is no missing setting in `azurerm_app_service` for this. The structure and naming in a web app logging configuration is a bit peculiar, and neither the Portal nor the existence of the `--docker-container-logging` option reflect what is going on underneath.

Inspect the output of `az webapp log config --name app-myapp --resource-group rg-myrg --docker-container-logging filesystem`:

```json
{
  "applicationLogs": {
    "azureBlobStorage": {
      "level": "Off",
      "retentionInDays": null,
      "sasUrl": null
    },
    "azureTableStorage": {
      "level": "Off",
      "sasUrl": null
    },
    "fileSystem": {
      "level": "Off"
    }
  },
  "detailedErrorMessages": {
    "enabled": false
  },
  "failedRequestsTracing": {
    "enabled": false
  },
  "httpLogs": {
    "azureBlobStorage": {
      "enabled": false,
      "retentionInDays": 3,
      "sasUrl": null
    },
    "fileSystem": {
      "enabled": true,
      "retentionInDays": 3,
      "retentionInMb": 100
    }
  },
  "id": "/subscriptions/<uuid>/resourceGroups/rg-myrg/providers/Microsoft.Web/sites/app-myapp/config/logs",
  "kind": null,
  "location": "Region",
  "name": "logs",
  "resourceGroup": "rg-myrg",
  "tags": {},
  "type": "Microsoft.Web/sites/config"
}
```

This is the change:

```json
"httpLogs": {
  "fileSystem": {
    "enabled": true,
    "retentionInDays": 3,
    "retentionInMb": 100
  }
}
```

There is no docker logging setting, and in the portal, this setting is in the App Service Logs blade, and is the only setting there when the source is Linux/Container. Per [the documentation](https://docs.microsoft.com/en-us/azure/app-service/troubleshoot-diagnostic-logs#enable-application-logging-linuxcontainer), you change this setting to capture container logs.

So, **to turn on container logging in your `azurerm_app_service` Terraform configuration, add the following:**

```tf
logs {
  http_logs {
    file_system {
      retention_in_days = <days>
      retention_in_mb   = <mb>
    }
  }
}
```

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
