### ISSUE TITLE
Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details

### ISSUE THREAD

**Issue by nickmhankins** [hashicorp/terraform-provider-azurerm#6555]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.12.19 
azurerm 1.44
### Affected Resource(s)

* `azurerm_key_vault_secret`
* `azurerm_key_vault_key`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  auxiliary_tenant_ids = var.current_deployment.tenant_id == var.image_gallery.authentication.tenant_id ? [] : [var.image_gallery.authentication.tenant_id]
}

provider "azurerm" {
  alias           = "image_gallery"
  subscription_id = var.image_gallery.authentication.subscription_id
  client_id       = var.image_gallery.authentication.client_id
  client_secret   = var.image_gallery.authentication.client_secret
  tenant_id       = var.image_gallery.authentication.tenant_id
}

data "azurerm_shared_image_version" "image" {
  for_each            = var.image_versions.gallery
  name                = each.value.version
  image_name          = each.value.definition
  gallery_name        = var.image_gallery.config.name
  resource_group_name = var.image_gallery.config.resource_group
  provider            = azurerm.image_gallery
}

resource "azurerm_key_vault" "keyvault" {
  name                            = "some-kv-name"
  location                        = azurerm_resource_group.testing_rg.location
  resource_group_name             = azurerm_resource_group.testing_rg.name
  tenant_id                       = data.azurerm_client_config.current.tenant_id
  sku_name                        = "standard"
  enabled_for_deployment          = true
  enabled_for_template_deployment = true
}


resource azurerm_key_vault_secret tenant_credential_secrets {
  for_each     = var.credentials
  name         = each.value.username
  value        = each.value.pass
  key_vault_id = azurerm_key_vault.keyvault.id
}
```

### Debug Output

2020/04/20 18:48:24 [DEBUG] azurerm_key_vault_secret.tenant_credential_secrets["win_admin"]: apply errored, but we're indicating that via the Error pointer rather than returning it: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/04/20 18:48:24 [TRACE] EvalMaybeTainted: azurerm_key_vault_secret.tenant_credential_secrets["win_admin"] encountered an error during creation, so it is now marked as tainted
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/04/20 18:48:24 [TRACE] EvalWriteState: removing state object for azurerm_key_vault_secret.tenant_credential_secrets["win_admin"]
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalApplyProvisioners
2020/04/20 18:48:24 [TRACE] EvalApplyProvisioners: azurerm_key_vault_secret.tenant_credential_secrets["win_admin"] has no state, so skipping provisioners
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalMaybeTainted
2020/04/20 18:48:24 [TRACE] EvalMaybeTainted: azurerm_key_vault_secret.tenant_credential_secrets["win_admin"] encountered an error during creation, so it is now marked as tainted
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalWriteState
2020/04/20 18:48:24 [TRACE] EvalWriteState: removing state object for azurerm_key_vault_secret.tenant_credential_secrets["win_admin"]
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalIf
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalIf
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalWriteDiff
2020/04/20 18:48:24 [TRACE] <root>: eval: *terraform.EvalApplyPost
2020/04/20 18:48:24 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details
2020/04/20 18:48:24 [ERROR] <root>: eval: *terraform.EvalSequence, err: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details
2020/04/20 18:48:24 [TRACE] [walkApply] Exiting eval tree: azurerm_key_vault_secret.tenant_credential_secrets["win_admin"]

**stdout errors**
```hcl
2020-04-20T20:19:14.1239202Z ##[error]Error: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details

  on keyvault.tf line 218, in resource "azurerm_key_vault_secret" "tenant_credential_secrets":

 218: resource azurerm_key_vault_secret tenant_credential_secrets {

Error: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details

  on keyvault.tf line 218, in resource "azurerm_key_vault_secret" "tenant_credential_secrets":

 218: resource azurerm_key_vault_secret tenant_credential_secrets {

Error: autorest/Client#Do: Preparing request failed: StatusCode=0 -- Original Error: Error getting Authorization Token for client cert: an MultiTenantOauth token wasn't configured correctly; please file a bug with more details

  on keyvault.tf line 218, in resource "azurerm_key_vault_secret" "tenant_credential_secrets":

 218: resource azurerm_key_vault_secret tenant_credential_secrets {

```
### Expected Behavior

We are deploying to one tenant using a Shared Image Gallery in another (just to give context for multi-tenant oauth token error), and it should be able to provision resources in the current tenant successfully.

### Actual Behavior

It seems to read the image gallery from the other tenant and deploy the VMs just fine, but for some reason the Key Vault secrets creation steps are returning errors, which is strange because they are not using the image gallery provider, they're just being created in the current deployment tenant.  I can see the Key Vault secrets and Key Vault Keys creation being attempted for 7-10 minutes, then the attempts disappear and it errors out a few minutes later

### Important Factoids
If I remove all references to resources in the other tenant (image gallery, all data sources, image_gallery provider) and only deploy the key vault and secrets, it will still fail.  **Once I remove the auxiliary_tenant_ids from the azurerm provider, the deployment will succeed.**

### Steps to Reproduce

Create an azurerm provider with a `auxiliary_tenant_ids` containing the tenant id a second tenant that your multi-tenant service principal has access to.  Deploy a Key Vault and Key Vault secrets and Key Vault Keys.  

* #0000

**Comment by solinov** [comment]
👍

**Comment by devblackops** [comment]
Any updates on this issue? I am seeing it as well. We are using multiple providers because we're setting up VNET peering to another tenant. Even if I create and use a provider that doesn't have `auxiliary_tenant_ids`, as long as there exists one in the config we're seeing this error. Removing the provider with `auxiliary_tenant_ids` seems to fix this issue, but the whole terraform config can't complete because of the VNET peering requirement.

**Comment by aakashmathai** [comment]
One workaround to fix this creating a new provider without any auxiliary tenants and using that provider for reading the secret:
```
provider "azurerm" {
  version                    = "~> 1.44.0"
  alias                      = "vault_read"
  skip_provider_registration = true
}
```

```
data "azurerm_key_vault_secret" "adc-password" {
  provider = vault_read
  depends_on = [something]
  name         = "secret_name"
  key_vault_id = azurerm_key_vault.kv.id
}
```

This worked for me and  @subrat96

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
