### ISSUE TITLE
Support for seperate `frontend_ip_conifguration` resources for `azurerm_lb`

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/terraform-provider-azurerm#6568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the `azurerm_lb` resource allows multiple front_ip_configuration blocks to be defined within it.  However, as they are "embeded" in the resource, you are unable to use a count to control how many addresses get created. 

### Affected Resource(s)

Key scenario this becomes an issue is in supporting multiple zones.  Take the following configuration:

```
resource "azurerm_lb" "mylb" {
  name                = "my-lb"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  frontend_ip_configuration {
    name                          = "${azurerm_resource_group.main.name}-lb-ip"
    subnet_id                     = data.azurerm_subnet.subnet.id
    private_ip_address_allocation = "dynamic"
  }
```

The above scenario is simple enough: a LB with a single internal IP.  If I want to support something across multiple zones, however, I have to now duplicate the `frontend_ip_configuration` for every zone.  This becomes really troublesome if I setup a list or map of the zones so the admin can select which zones/how many he actually wants to use (maybe the service is fine in only 2 zones .... maybe the region selected only has 1).

This becomes really complicated really fast.

### Potential Terraform Configuration

**azurerm_lb_frontend_ip_configuration**
This mimics what's done in a lot of other scenarios (including backend ip association). A seperate resource black that can be associated and thus, allows us to use counts to control quantity.

```
resource "azurerm_lb" "managerlb" {
  name                = "${azurerm_resource_group.main.name}-lb"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

}

resource "azurerm_lb_frontend_ip_configuration" "ips" {
  count =  3
  loadbalancer_id = azurerm_lb.managerlb.id
  name = "lb-ip-zone-${count.index +1}"
  subnet_id  = data.azurerm_subnet.subnet.id
  private_ip_address_allocation = "dynamic"
  zones   = [count.index + 1]
}
```

This is obviously over simplified, but it now gives me the ability to set a scalable count that spans zones easily.

### References

* #0000

**Comment by fabiendelpierre** [comment]
I don't think it's a bad idea, but couldn't you accomplish the same thing (i.e. a scalable count that spans zone easily) with dynamic blocks? For example:

```
variable "zones" {
  type = list(string)
  default = ["1", "2", "3"]
}

resource "azurerm_lb" "managerlb" {
  name = "${azurerm_resource_group.main.name}-lb"
  location = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  dynamic "frontend_ip_configuration" {
    for_each = var.zones

    content {
      name = "lb-ip-zone-${frontend_ip_configuration.value}"
      subnet_id = data.azurerm_subnet.subnet.id
      private_ip_address_allocation = "dynamic"
      zones = [frontend_ip_configuration.value]
    }
  }
}
```

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
