### ISSUE TITLE
function app setting optional facebook/microsoft/google/twitter/active_directory fields

### ISSUE THREAD

**Issue by ctooley21** [hashicorp/terraform-provider-azurerm#6572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "fap_req_sch" {
  name                = "GAV-ARV-${var.env}-WAP-REQ-SCH-01"
  location            = azurerm_resource_group.rg_ilb_ase.location
  resource_group_name = azurerm_resource_group.rg_ilb_ase.name
  app_service_plan_id = azurerm_app_service_plan.asp_req_sch.id
  storage_connection_string = azurerm_storage_account.str_req_sch.primary_connection_string

  version = "~2"

  identity {
    type = "SystemAssigned"
  }   

  app_settings = {
  "APPINSIGHTS_INSTRUMENTATIONKEY" = "${var.instrumentation_key}"
  }
}
```

### Expected Behavior

These fields should not be generated when not set

### Actual Behavior

These fields were generated even with no mention in our resource definition, and the documentation saying that it was optional.

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by aristosvo** [comment]
@ctooley21 Can you elaborate a bit more what you see and would like to see?

Which fields are generated and why is it a problem these are generated?

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
