### ISSUE TITLE
Support for adding rules/backends etc to an existing application gateway

### ISSUE THREAD

**Issue by listentorick** [hashicorp/terraform-provider-azurerm#6605]
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I have an application gateway which servers multiple SaaS customers. As I add new customers I need to add rules and backends. Currently Im using dynamic blocks, however this requires me to maintain and pass in a list of all tenants to the tf config which builds the AGW to ensure existing tenants arent lost.

### New or Affected Resource(s)

It woud be great to be able to add a set of rules and backends  when adding a tenant without the need to "know" about all of the existing tenants and their meta data.

* azurerm_application_gateway

### Potential Terraform Configuration

resource "azurerm_application_gateway_rule" "myrule" {
	name                = "example-appgateway_rule"
	application_gateway_name = azurerm_application_gateway.example.name 
	rule_type                  = "Basic"
	http_listener_name         = "listener_name"
	backend_address_pool_name  = "backend_address_pool_name"
	backend_http_settings_name = "http_setting_name"
}

### References

* #0000

**Comment by listentorick** [comment]
I am interested in contributing to this myself, before I do is this inline with your roadmap?

**Comment by RavulaChetan** [comment]
Whats the roadmap for support to add rules/backend to existing application gateway

**Comment by devblackops** [comment]
I'd like to extend this request to include other resource blocks. Notably, it would be great if there were discrete resources for:

- ssl_certificate
- probe
- backend_address_pool
- http_listener
- redirect_configuration
- request_routing_rule

I image this would look similar to how `azurerm_lb` has separate `azurerm_lb_backend_address_pool`, `azurerm_lb_rule`, and `azurerm_lb_probe` resources.

A more composable configuration would make provisioning the AppGW a lot easier when there are many modules that create resources to need to be exposed through it.

**Comment by ceciliasharp** [comment]
Is this on the roadmap soon?

**Comment by tombuildsstuff** [comment]
Consolidating this into #9615 which is tracking this issue more generally - please subscribe to that issue for updates.
