### ISSUE TITLE
"ValidationError" when destroying API Management Authorization Server

### ISSUE THREAD

**Issue by markti** [hashicorp/terraform-provider-azurerm#6637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.18
+ provider.azuread v0.6.0
+ provider.azurerm v2.7.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azurerm_api_management_authorization_server`

### Terraform Configuration Files

```hcl

resource "azurerm_api_management_authorization_server" "apim_auth" {

  name                         = var.name
  api_management_name          = var.apim_name
  resource_group_name          = var.resource_group_name
  display_name                 = var.name
  authorization_endpoint       = "https://login.microsoftonline.com/${var.tenant_id}/oauth2/v2.0/authorize"
  client_id                    = var.client_id
  client_secret                = var.client_secret
  client_registration_endpoint = "http://localhost"
  token_endpoint               = "https://login.microsoftonline.com/${var.tenant_id}/oauth2/v2.0/token"

  default_scope                = var.default_scope

  client_authentication_method = [
    "Body"
  ]

  authorization_methods = [
    "GET"
  ]

  bearer_token_sending_methods = [
    "authorizationHeader"
  ]

  grant_types = [
    "authorizationCode",
    "implicit",
  ]
}
```

### Panic Output

Error: deleting Authorization Server "Admin-Auth" (API Management Service "foo-test-apim" / Resource Group "foo-test-global"): apimanagement.AuthorizationServerClient#Delete: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="ValidationError" Message="One or more fields contain incorrect values:" Details=[{"code":"ValidationError","message":"The authorization server cannot be deleted because it assigned to at least one API.","target":"ApiAuthenticationSettings"}]

### Expected Behavior

Doing an apply that should delete an entire API Management instance, all its APIs and authorization servers, everything and should perform a cascading delete to destroy all the resources according to their dependency graph.

### Actual Behavior

you get this error. Probably because its trying to delete authorization servers that are linked to APIs.

### Steps to Reproduce

1. `terraform apply`
2. manually link an API to an authorization server in the azure portal
3. comment out entire API management and all resources
4. `terraform apply`

### Important Factoids

Azure Public

### References

This would probably be mitigated by adding this feature so that you didnt have to manually link an API to an authorization server.

* #6614

**Comment by yupwei68** [comment]
Hi @markti , thanks for opening this issue. You could try deleting `azurerm_api_management_api` before deleting the `azurerm_api_management_authorization_server` and  `azurerm_api_management`, which in this case could work for you. On the other hand, this issue requests an enhancement for `azurerm_api_management_api`  adding blocks   `authenticationSettingsContract`

**Comment by swapnilbjadhav** [comment]
Hi @yupwei68, @markti  is the authenticationSettingsContract block added? i want to provide the Oauth2.0 security to my api

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
