### ISSUE TITLE
Support for Stream Analytics Compatibility Level 1.2

### ISSUE THREAD

**Issue by tschager** [hashicorp/terraform-provider-azurerm#6660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add compatibility level 1.2 as a possible argument value for azurerm_stream_analytics_job.

Documentation: [Compatibility level for Azure Stream Analytics jobs](https://docs.microsoft.com/en-us/azure/stream-analytics/stream-analytics-compatibility-level)

### New or Affected Resource(s)

* azurerm_stream_analytics_job

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_stream_analytics_job" "example" {
  name                                     = "example-job"
  resource_group_name                      = azurerm_resource_group.example.name
  location                                 = azurerm_resource_group.example.location
  compatibility_level                      = "1.2"
  data_locale                              = "en-GB"
  events_late_arrival_max_delay_in_seconds = 60
  events_out_of_order_max_delay_in_seconds = 50
  events_out_of_order_policy               = "Adjust"
  output_error_policy                      = "Drop"
  streaming_units                          = 3

  tags = {
    environment = "Example"
  }

  transformation_query = <<QUERY
    SELECT *
    INTO [YourOutputAlias]
    FROM [YourInputAlias]
QUERY

}
```

### References

* https://www.terraform.io/docs/providers/azurerm/r/stream_analytics_job.html#compatibility_level
* https://github.com/Azure/azure-rest-api-specs/issues/5604

**Comment by neil-yechenwei** [comment]
@tschager , thanks for opening this issue. Seems GA API version hasn't supported Compatibility Level 1.2 yet. I've reopened this issue for tracking.

**Comment by chriswue** [comment]
Looks like an updated GA version is now available: https://github.com/Azure/azure-rest-api-specs/issues/5604#issuecomment-907458115
