### ISSUE TITLE
azurerm_virtual_hub_connection misspelled arguments

### ISSUE THREAD

**Issue by doherty100** [hashicorp/terraform-provider-azurerm#6663]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.7.0

### Affected Resource(s)

* `azurerm_virtual_hub_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_hub_connection" "vwanhubconnect1" {
  name  = var.vwan_hub_connection_name_1
  virtual_hub_id = azurerm_virtual_hub.vwanhub1.id
  remote_virtual_network_id = var.remote_virtual_network_id
  hub_to_vitual_network_traffic_allowed = true
  vitual_network_to_hub_gateways_traffic_allowed = true
  internet_security_enabled = true
}
```

### Debug Output

N/A
### Panic Output

N/A
### Expected Behavior

* "hub_to_vitual_network_traffic_allowed"  argument should be spelled "hub_to_virtual_network_traffic_allowed". 
* "vitual_network_to_hub_gateways_traffic_allowed" should be spelled "virtual_network_to_hub_gateways_traffic_allowed"
### Actual Behavior

Had to use misspelled argument names in my configuration.

### Steps to Reproduce

N/A
### Important Factoids

Azure Public

### References

N/A

**Comment by magodo** [comment]
Thank you for letting us know this issue :+1:
I have submitted a PR to fix it!

**Comment by katbyte** [comment]
Closing as these properties were removed in v3.0 of the provider (as they stopped functioning in the API)
