### ISSUE TITLE
After Updating to 2.x plans show a ton of tag removals

### ISSUE THREAD

**Issue by drdamour** [hashicorp/terraform-provider-azurerm#6674]
Per MS recommendations we have a policy in place that copies all tags on the resource group down to any resources in the group on creation.  as such we don't define tag block hcl in any resources beyond resource groups.

 This didn't cause issues in azurerm 1.x, but when moving to 2.x our plans show all our resources losing all their tags because tags is now null by default it seems.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.7.0
+ provider.null v2.1.2

### Affected Resource(s)

* `azurerm_app_service`
* `azurerm_storage_account`

### Expected Behavior

we expected terraform to not remove any tags since the tag block was not defined for the resources...or at least have a mention of this behaviour change in the upgrade guide https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html

### Actual Behavior

provider is determining all our resources tags should be removed.

### Steps to Reproduce

put some tags on a resource outside of TF
1. `terraform apply`
see the tags are trying to be removed

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
