### ISSUE TITLE
Java settings missing when provisioning azurerm_app_service

### ISSUE THREAD

**Issue by hashitop** [hashicorp/terraform-provider-azurerm#6709]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Tested with:

* `azurerm_2.6.0`
* `azurerm_1.36.0`

NOTES:
* `Possibly any version`

### Terraform Configuration Files

https://github.com/Azure/terraform/tree/master/quickstart/101-web-app-linux-java

```hcl

resource "azurerm_app_service_plan" "default" {
  name                = "${var.name}-plan"
  location            = "${azurerm_resource_group.default.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  kind                = "Linux"

  # Reserved must be set to true for Linux App Service Plans
  reserved = true

  sku {
    tier = "${var.plan_tier}"
    size = "${var.plan_sku}"
  }
}

resource "azurerm_app_service" "default" {
  name                = "${var.dns_prefix}-${var.name}-${var.environment}-app"
  location            = "${azurerm_resource_group.default.location}"
  resource_group_name = "${azurerm_resource_group.default.name}"
  app_service_plan_id = "${azurerm_app_service_plan.default.id}"

  site_config {
    always_on        = false
    java_version           = "1.8"
    java_container         = "tomcat"
    java_container_version = "9.0"
  }
}

```

### Debug Output

**Payload from apply operation**

https://gist.github.com/hashitop/75c1b2f11204e0aadda9751d007492af

**Trace log from plan operation**

https://gist.github.com/hashitop/5d74e865b8cea0fc0bab50db96681e8b

### Expected Behavior

No change with terraform plan/apply

### Actual Behavior

Always shows the change underneath `site_config` block with plan/apply operation

    java_version           = "1.8"
    java_container         = "tomcat"
    java_container_version = "9.0"

And `always_on` is always `true`

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### Important Factoids

The response payload from Azure API during **terraform refresh** always contains these values

- alwaysOn: true
- javaVersion:null
- javaContainer:null
- javaContainerVersion:null

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
