### ISSUE TITLE
azurerm_iothub_dps always forced to be recreated

### ISSUE THREAD

**Issue by emileturcotte** [hashicorp/terraform-provider-azurerm#6720]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Using Terraform v0.12.24
Using provider v2.7.0

### Affected Resource(s)

* `azurerm_iothub_dps`
* `azurerm_iothub_dps_shared_access_policy`

### Terraform Configuration Files

Here is the content of my module :
```hcl
resource "azurerm_iothub_dps" "dps" {
  name                = var.name
  resource_group_name = var.resource_group.name
  location            = var.resource_group.location

  sku {
    name     = "S1"
    capacity = "1"
  }

  linked_hub {
    connection_string = var.iothub_connection_string
    location          = var.resource_group.location
  }
}
# We need to create this because the DPS resource does not expose the default Shared Access Policy, so we can't output it.
resource "azurerm_iothub_dps_shared_access_policy" "dps" {
  name                = "dpsowner"
  resource_group_name = var.resource_group.name
  iothub_dps_name     = azurerm_iothub_dps.dps.name

  service_config     = true
  enrollment_read    = true
  enrollment_write   = true
  registration_read  = true
  registration_write = true
}

resource "azurerm_management_lock" "dps" {
  name       = "delete-lock"
  scope      = azurerm_iothub_dps.dps.id
  lock_level = "CanNotDelete"
  notes      = "Locked because it is a shared resources which contains data. It can still be read and updated."
}
```

Here is the declaration of my module :

```hcl
resource "azurerm_resource_group" "terraform" {
  name     = "${var.environment}-IoTHubCore"
  location = "East US"
}

module "dps" {
  source                   = "./modules/dps"
  
  name                     = "IoTHub-${var.environment}-DPS"
  iothub_connection_string = module.iot-hub.iothubowner_connection_string
  resource_group           = {
    name = azurerm_resource_group.terraform.name
    location = azurerm_resource_group.terraform.location
  }
}
```
### Debug Output

Link to Debug output Gist : https://gist.github.com/emileturcotte/cc3eda3fe9d02ae9254cdcf9b1f0efeb

### Expected Behavior

- If no changes are made to the azurerm_iothub_dps resource, Terraform should not detect changes between two ```terraform apply```.
- When the ```azurerm_iothub_dps``` resource is deleted, its associated ```azurerm_iothub_dps_shared_access_policy``` resources should be also deleted.

### Actual Behavior

- After the first provisionning, Terraform detects changes to the ```azurerm_iothub_dps``` resource even though there has been no configuration changes. Some of them are update in-place, but it always tries to set its ```tags : {}``` to ```null```. This triggers a replacement of the resource, which I do not want happening. If I allow the recreation, its associated ```azurerm_iothub_dps_shared_access_policy``` is not recreated as well, so it causes a deployment crash (I assume because it is left in the state although it is effectively deleted). The ```azurerm_management_lock``` is recreated and is not a problem.
- Also, some of the ```azurerm_iothub_dps_shared_access_policy``` permissions are detected as false, which causes an update. See Issue #5630 

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan` you should see the detection of unnecessary update in-place, tags being set to null and Shared Access Key policies changing from false to true.

### References

* #5630

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I summarized your questions.
Questions:
1. azurerm_iothub_dps would recreate even if there is no change on it.
2. terraform always tries to set tags : {} to null
3. “enrollment_read/registration_write/registration_read” always tries to set the value
4. Once removed azurerm_iothub_dps block from tfconfig, azurerm_iothub_dps_shared_access_policy wouldn't be deleted.

For above question 1 and 2, seems I cannot repro this issue with latest azurerm and below tfconfig. Could you have a try below tfconfig to check whether this issue still exists?

For above question 3, seems api doesn't return the values "enrollmentRead/registrationWrite/registrationRead" after created successfully. I assume it's an api issue. So I filed an issue on Azure/azure-rest-api-specs#10356.

For above question 4, azurerm_iothub_dps cannot be removed from tfconfig independently. Because iothub_dps_name property of azurerm_iothub_dps_shared_access_policy would reference it and this property is required, which means azurerm_iothub_dps and azurerm_iothub_dps_shared_access_policy have to be removed together. So I think now the problem has gone.

tf config:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-iotdps-test01"
  location = "eastus2"
}

resource "azurerm_iothub_dps" "test" {
  name                = "acctestIoTDPS-test01"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location

  sku {
    name     = "S1"
    capacity = "1"
  }
  
  linked_hub {
    connection_string = "xxxxxxx"
    location          = azurerm_resource_group.test.location
  }
}

resource "azurerm_iothub_dps_shared_access_policy" "test" {
  name                = "acctest01"
  resource_group_name = azurerm_resource_group.test.name
  iothub_dps_name     = azurerm_iothub_dps.test.name

  service_config      = true
  enrollment_write    = true  
  enrollment_read     = true
  registration_write  = true
  registration_read   = true
}
```

**Comment by chatelain-io** [comment]
I have the same issue, each time I run terraform dps get replaced.

`resource "azurerm_iothub_dps" "main" {
  name                          = local.iothub_name
  resource_group_name           = data.azurerm_resource_group.main.name
  location                      = "East US"
  
  sku {
    name     = "S1"
    capacity = "1"
  }

  linked_hub {
    allocation_weight       = 0
    apply_allocation_policy = true
    connection_string       = format("HostName=%s;SharedAccessKeyName=%s;SharedAccessKey=%s", azurerm_iothub.main.hostname, "iothubowner", data.azurerm_key_vault_secret.iothub_main_iothubowner_primary_key.value) 
    location                = data.azurerm_resource_group.main.location
  }

  tags = {
    environment = var.environment
  }
}`

result:
`# azurerm_iothub_dps.main must be replaced
-/+ resource "azurerm_iothub_dps" "main" {
    ~ allocation_policy             = "Hashed" -> (known after apply)
    ~ device_provisioning_host_name = "global.azure-devices-provisioning.net" -> (known after apply)
    ~ id                            = "xxx" -> (known after apply)
    ~ id_scope                      = "xxx" -> (known after apply)
    location                      = "eastus"
    name                          = "xxx"
    resource_group_name           = "xxx"
    ~ service_operations_host_name  = "xxx.azure-devices-provisioning.net" -> (known after apply)
    tags                          = {
        "environment" = "prod"
    }

    ~ linked_hub {
        allocation_weight       = 0
        apply_allocation_policy = true
        ~ connection_string       = (sensitive value)
        ~ hostname                = "xxx.azure-devices.net" -> (known after apply)
        location                = "canadaeast"
    }

    sku {
        capacity = 1
        name     = "S1"
    }
}`

**Comment by chatelain-io** [comment]
The issue is when I set the linked_hub.connection_string 

`connection_string = format("HostName=%s;SharedAccessKeyName=%s;SharedAccessKey=%s", azurerm_iothub.main.hostname, "iothubowner", data.azurerm_key_vault_secret.iothub_main_iothubowner_primary_key.value)`

Don't know why yet, but terraform try to replace it even if the value do not change.

Adding the connection_string to ignore_changes fix the issue for now

**Comment by NZetterval** [comment]
I go force replacement in linked hub due to location which is not changed.
~ linked_hub {
          ~ connection_string       = (sensitive value)
          ~ hostname                = "iot-SwegonCloud-dev-we.azure-devices.net" -> (known after apply)
          ~ location                = "West Europe" -> "westeurope" # forces replacement

**Comment by DaveOHenry** [comment]
Had the same issue when trying to build the connection string myself. Solved it with a native Terraform data source like this:
```
data "azurerm_iothub_shared_access_policy" "iothubowner" {
  name                = "iothubowner"
  resource_group_name = azurerm_resource_group.rg.name
  iothub_name         = azurerm_iothub.iothub.name
}

resource "azurerm_iothub_dps" "iothub_dps" {
  name                = "iothub-dps"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  sku {
    name     = "S1"
    capacity = "1"
  }

  linked_hub {
    location          = azurerm_resource_group.rg.location
    connection_string = data.azurerm_iothub_shared_access_policy.iothubowner.primary_connection_string
  }
}
```

**Comment by esierrapena** [comment]
hi! even with native Terraform data source is added to linked_hub block, terraform plan suggest to destroy and recreate the resource in my case.. dps resource has been previously imported with terraform import.

```resource "azurerm_iothub_dps" "dpshgu" {
  name                = "{{ az_config.dps.name }}"
  resource_group_name = "{{ infra_collection_resource_group }}"
  location            = "{{ location }}"

  sku {
    name     = "{{ az_config.dps.sku_name }}"
    capacity = "{{ az_config.dps.sku_capacity }}"
  }

  linked_hub {
    connection_string = data.azurerm_iothub_shared_access_policy.sp_iothubowner.primary_connection_string
    location          = "{{ location }}"
  }

  tags = local.tags
}

**Comment by svenna** [comment]
I looked into the go code and it clearly states that changes in connection string and location will force recreate.
https://github.com/hashicorp/terraform-provider-azurerm/blob/b44ea51c13981790f575c04d0d79eff94639f71f/internal/services/iothub/iothub_dps_resource.go#L82

i think this is a missunderstanding of what you are declaring here... i assume that a change of location (and conn_str) of a resource normally forces a replacement. but we are in linked_hubs only referencing values from somewhere else.
