### ISSUE TITLE
Migrating from azurerm_azuread_* resoruces to azuread_* commands still fails.

### ISSUE THREAD

**Issue by DamaniN** [hashicorp/terraform-provider-azurerm#6726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```text
terraform -v
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.8.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.vault v2.10.0
```

### Affected Resource(s)

* `azurerm_azuread_*` migration to `azuread_*`

### Terraform Configuration Files

```hcl
resource "azurerm_azuread_application" "example" {
  name            = "myimportantname"
  homepage        = "https://myimportanthomepage.com"
  identifier_uris = ["https://myimportanturi.com"]
}
```

### Debug Output

Provided upon request.

### Panic Output

None

### Expected Behavior

Terraform should have provided the ID of the resource being migrated. 

### Actual Behavior

Terraform gave the error: 

`A managed resource type "azurerm_azuread_application" is not supported by
provider "azurerm".`

### Steps to Reproduce

1. `terraform state list | grep azuread`
1. `echo <resource_name>.id | terraform console`

Example:

```text
echo azurerm_azuread_application.example.id | terraform console
Acquiring state lock. This may take a few moments...

Error: Invalid resource type

  on <console-input> line 1:
  (source code not available)

A managed resource type "azurerm_azuread_application" is not supported by
provider "azurerm".
```

### Important Factoids

There are a couple of issues here:

1. The updated migration instructions in #3542 do not list azurerm_azuread_* resources. The same issue applies to them. 

1. The instructions in #3542 only work with `v1.44.0` of the provider (as far as I have tested). To work around this I had to force my `azurerm` provider back to `v1.4.4.0` from `v2.8.0`
### References

I followed the updated instructions from #3542 but these don't work with version `v2.8.0` of the azurerm provider.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
