### ISSUE TITLE
Databricks workspace not ready after creation

### ISSUE THREAD

**Issue by sdebruyn** [hashicorp/terraform-provider-azurerm#6753]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
➜ terraform -v
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.6.0
+ provider.databricks v0.1.0
+ provider.http v1.2.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_databricks_workspace`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~> 2.6.0"
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "rg"
  location = "eastus2"
}

resource "azurerm_databricks_workspace" "dbks" {
  name                        = "dbks"
  resource_group_name         = azurerm_resource_group.rg.name
  managed_resource_group_name = "rgdbks"
  location                    = "eastus2"
  sku                         = "standard"
}
```

### Debug Output
https://gist.github.com/sdebruyn/c181f6939f0628db5cd888302eba00de

### Behavior
The workspace is created and terraform continues to the next resource in the dependency chain. We noticed a few issues in databricks providers:
- https://github.com/innovationnorway/terraform-provider-databricks/issues/49
- https://github.com/databrickslabs/databricks-terraform/issues/33

So it looks like the workspace is not yet ready to use right after creation.
I hoped that the field `provisioningState` could indicate when the workspace is really ready, but it goes to `succeeded` right away and has the same state after a refresh.

It's probably an issue in the Azure API itself, but I'm still creating it here for future reference as well...

### Steps to Reproduce
1. `terraform apply`

**Comment by njuCZ** [comment]
@sdebruyn  thanks for pointing this problem. I have asked the databricks servie team. I will share here if there is any updates.

**Comment by WodansSon** [comment]
This appears to have been fixed by the service team. If you are no longer feel free to close this issue.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
