### ISSUE TITLE
Support for customizing HDInsight kafka brokers with correct kafka server.properties for TLS configuration

### ISSUE THREAD

**Issue by jaapterwoerds** [hashicorp/terraform-provider-azurerm#6788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a developer, I want to be able to provide the Kafka brokers in my HDInsight cluster with the correct properties to enable SASL_SSL between clients and brokers and at least SSL between brokers.

The mechanism to achieve this is described in the Azure documentation. In this feature request I want to restrict the scope to the properties I need for configuring TLS for Kafka brokers. The mechanism seem generic, so it could eventually be applied for other Kafka broker properties and other configuration files for other HDInsight cluster types. 

Since the cluster types are split in separate Terraform entities, I will restrict  myself to the Kafka cluster type here and specifically the properties which are needed to secure the cluster in the aforementioned way. Later, extending the support to other properties of the Kafka brokers and other configuraiton of other cluster types can be provided in a similar way.

### New or Affected Resource(s)

* azurerm_hdinsight_kafka_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azurerm_hdinsight_kafka_cluster" "test" {
  name                = "acctesthdi-%d"
  resource_group_name = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  cluster_version     = "3.6"
  tier                = "Standard"

  component_version {
    kafka = "1.1"
  }

  gateway {
    enabled  = true
    username = "acctestusrgw"
    password = "TerrAform123!"
  }

  server_properties {
    "listeners" = "PLAINTEXT://localhost:9092,SSL://localhost:9093,SASL_SSL://localhost:9093"
    "ssl_key_password" = "secretkeypassword"
    "ssl_keystore_location" = "/etc/ssl/certs/java/keystore.jks"
    "ssl_keystore_password" = "secretpassword"
    "ssl_truststore_location" = "/usr/lib/openjdk11/jre/lib/security/cacerts"
    "ssl_truststore_password" = "changeit"
    "security_inter_broker_protocol" = "SSL"
  }

  storage_account {
    storage_container_id = azurerm_storage_container.test.id
    storage_account_key  = azurerm_storage_account.test.primary_access_key
    is_default           = true
  }

  roles {
    head_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }

    worker_node {
      vm_size                  = "Standard_D3_V2"
      username                 = "acctestusrvm"
      password                 = "AccTestvdSC4daf986!"
      target_instance_count    = 3
      number_of_disks_per_node = 2
    }

    zookeeper_node {
      vm_size  = "Standard_D3_V2"
      username = "acctestusrvm"
      password = "AccTestvdSC4daf986!"
    }
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-customize-cluster-bootstrap

**Comment by jaapterwoerds** [comment]
I'm working on a PR to implement just this.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
