### ISSUE TITLE
Please support custom headers

### ISSUE THREAD

**Issue by dhirschfeld** [hashicorp/terraform-provider-azurerm#6793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Custom headers were added in azure cli in https://github.com/Azure/azure-cli-extensions/pull/1104.

It would be great if terraform allowed passing through custom headers.

My particular usecase is selecting Ubuntu 18.04 for AKS:
https://docs.microsoft.com/en-au/azure/aks/cluster-configuration#os-configuration-preview

**Comment by tbertenshaw** [comment]
is there some way of passing this through before its fully supported?

**Comment by dhirschfeld** [comment]
As well as Ubuntu 18.04 I'd also like to test all of the below which require the ability to pass custom headers:
* [Gen2 VMs](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#generation-2-virtual-machines-preview)
* [Ephemeral OS disks](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-ephemeral-os-on-existing-clusters-preview)
* [`containerd` runtime](https://docs.microsoft.com/en-us/azure/aks/cluster-configuration#use-containerd-as-your-container-runtime-preview)

***xref:*** #7947

**Comment by dhirschfeld** [comment]
Interesting/relevant? [comment](https://github.com/Azure/AKS/issues/1370#issuecomment-671522778) in the AKS repo:
> *We'll be making a few additional options so you're able to try these previews that don't land on the API via ARM too. Stay tuned on the next few weeks.*

**Comment by ubsujit** [comment]
Hi.. do we have any updates for adding custom header?

**Comment by carmilea** [comment]
Do we have an update aks-custom-headers support?   We have a use-case for enabling UltraSSD's as part of our provisioning:

```
--aks-custom-headers EnableUltraSSD=true 
```

**Comment by annaeseo** [comment]
I'm also looking for an update on this issue.   Deploying AKS version 1.18.8 using Terraform still deploys Ubuntu 16.04.  Looking for an option to deploy AKS version 1.18.8 with Ubuntu 18.04.

**Comment by dhirschfeld** [comment]
At least for the OS disk type, it has been implemented in #9166.

**Comment by vidyasagarreddyc** [comment]
https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver, storage CSI drivers are GAed but not availbe in terraform to enable it

**Comment by DrewRomanyk** [comment]
@tombuildsstuff Hey Tom, after checking this [comment ](https://github.com/Azure/azure-sdk-for-go/issues/11692#issuecomment-793601076) and checking the source code, it seems like the solution for this is to include these properties into the actual request headers for the create cluster operations. Would the solution be similar to what you did for appconfiguration [here](https://github.com/hashicorp/terraform-provider-azurerm/blob/main/internal/services/appconfiguration/sdk/1.0/appconfiguration/client.go#L48)?

I ask as I would love to get this working for the storage CSI drivers that went GA but require a special request header to enable the feature that can only be enabled on the cluster creation request.

Im happy to try to get it working, but I don't have any experience with working directly on terraform source code so if some one more experienced wants to work on the solution happy to let them do so.

**Comment by aristosvo** [comment]
PR trying to solve this problem: #14178

**Comment by sossickd** [comment]
For the benefit of anyone tracking this issue @aristosvo [PR](https://github.com/hashicorp/terraform-provider-azurerm/pull/14178) was `Closed` with status `wontfix`. There was a valid reason for this and the suggestion was too request these Headers to be added to the Swagger for the AKS API. I have subsequently created an [issue](https://github.com/Azure/AKS/issues/2757) on the AKS project.

**Comment by tombuildsstuff** [comment]
Opened a PR on the Swagger repository to add support for this, FWIW: https://github.com/Azure/azure-rest-api-specs/pull/18232

**Comment by mathieu-benoit** [comment]
Any update on this? Trying to set `--aks-custom-headers UseGPUDedicatedVHD=true` is a blocker to properly implement this: https://learn.microsoft.com/en-us/azure/aks/gpu-cluster if we don't want to manually deploy the `Daemonset`.

**Comment by dhirschfeld** [comment]
Tom's PR was closed as AKS are moving away from using custom headers. Given that, I'll close the issue for support here.

**Comment by Sturgelose** [comment]
@dhirschfeld is there any place where this deprecation of using custom headers is notified/written? At least to find which is the alternative Azure is suggesting instead of the headers and get an idea when will we be able to  use GPU machines in AKS from terraform without hacks...

**Comment by dhirschfeld** [comment]
The linked issue has the current status. I'm not fully clear how/if preview features will be supported by terraform in future :/

* https://github.com/Azure/azure-rest-api-specs/pull/18232#issuecomment-1068300285
* https://github.com/Azure/azure-rest-api-specs/pull/18232#issuecomment-1190886706
