### ISSUE TITLE
Support for custom Azure environments

### ISSUE THREAD

**Issue by igal-s** [hashicorp/terraform-provider-azurerm#6816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want the ability to use this provider with other Azure cloud instances beside the four (Public, USGovernment, German, and China) which are mentioned in the [provider documentation](https://www.terraform.io/docs/providers/azurerm/index.html#environment) and the [Azure go-autorest library](https://github.com/Azure/go-autorest/blob/9132adfc9db3007653dccb091b6a6c8e09b74ef5/autorest/azure/environments.go#L34).

While implementig this feature, looking at the [azure.EnvironmentFromName function implementation](https://github.com/Azure/go-autorest/blob/9132adfc9db3007653dccb091b6a6c8e09b74ef5/autorest/azure/environments.go#L219), I found an undocumented way of achieving this by setting `environment="STACK"` in  the provider configuration and setting the `AZURE_ENVIRONMENT_FILEPATH` environment variable to the path of a json file containing the environment endpoints.

#### Current workaround:
```bash
#/bin/bash
export AZURE_ENVIRONMENT_FILEPATH="MyAzureEnvEndpointFile.json"
#...
terraform apply
```
```hcl
#main.tf
provider "azurerm" {
  environment = "STACK"
  features {}
}
```

The above method works, but it's cumbersome and there is a comment in the `EnvironmentFromName` function indicates that this behavior potentioaly can change. So perhaps there's room for a more elegant method.

### Potential Terraform Configuration

I think that there are two possible options to configure it:

#### Option 1:
Add a special behaviro to the `environment` field i.e if the value ends with ".json" treat the field as a path to a config file. The upside of this is that it will require very minimal code changes to the code in `go-azure-helpers`

```hcl
#main.tf
provider "azurerm" {
  environment = "MyAzureEnvEndpointFile.json"
  features {}
}
```

#### Option 2:
Use a new field for the new behavior
```hcl
#main.tf
provider "azurerm" {
  environment_file_path = "MyAzureEnvEndpointFile.json"
  features {}
}
```
Sample MyAzureEnvEndpointFile.json file:
```json
{
    "Name":                         "AzurePublicCloud",
    "ManagementPortalURL":          "https://manage.windowsazure.com/",
    "PublishSettingsURL":           "https://manage.windowsazure.com/publishsettings/index",
    "ServiceManagementEndpoint":    "https://management.core.windows.net/",
    "ResourceManagerEndpoint":      "https://management.azure.com/",
    "ActiveDirectoryEndpoint":      "https://login.microsoftonline.com/",
    "GalleryEndpoint":              "https://gallery.azure.com/",
    "KeyVaultEndpoint":             "https://vault.azure.net/",
    "GraphEndpoint":                "https://graph.windows.net/",
    "ServiceBusEndpoint":           "https://servicebus.windows.net/",
    "BatchManagementEndpoint":      "https://batch.core.windows.net/",
    "StorageEndpointSuffix":        "core.windows.net",
    "SQLDatabaseDNSSuffix":         "database.windows.net",
    "TrafficManagerDNSSuffix":      "trafficmanager.net",
    "KeyVaultDNSSuffix":            "vault.azure.net",
    "ServiceBusEndpointSuffix":     "servicebus.windows.net",
    "ServiceManagementVMDNSSuffix": "cloudapp.net",
    "ResourceManagerVMDNSSuffix":   "cloudapp.azure.com",
    "ContainerRegistryDNSSuffix":   "azurecr.io",
    "CosmosDBDNSSuffix":            "documents.azure.com",
    "TokenAudience":                "https://management.azure.com/",
    "ResourceIdentifiers": {
        "Graph":               "https://graph.windows.net/",
        "KeyVault":            "https://vault.azure.net",
        "Datalake":            "https://datalake.azure.net/",
        "Batch":               "https://batch.core.windows.net/",
        "OperationalInsights": "https://api.loganalytics.io",
        "Storage":             "https://storage.azure.com/"
    }
}
```
### References

* go-azure-helpers upstreasm PR for Option 1:  https://github.com/hashicorp/go-azure-helpers/pull/53

**Comment by tombuildsstuff** [comment]
hey @igal-s 

Thanks for opening this issue.

Taking a look into this, rather than sourcing this from a file on disk (which could break) - it'd probably be better to look these up on demand, using the metadata service at `/metadata/endpoints?api-version=1.0` ([example](https://management.azure.com/metadata/endpoints?api-version=1.0)).

Out of interest - when you say you're looking to make use of this in a custom environment, is this for general usage or for running the tests? I'm asking mostly so we understand how we'd test/support this environment if it's for general usage

Thanks for raising the separate bug around the `AZURESTACKCLOUD` - whilst that's been beneficial in this scenario, that behaviour isn't intentional and we should probably raise an error there instead - so I'll send a PR to fix that shortly.

Thanks!

**Comment by igal-s** [comment]
Hi @tombuildsstuff

Thanks for the quick response.

While I agree that using a single endpoint per cloud instance to define the reset of the endpoints would be ideal, the metadata endpoint output does not contain all of the endpoints you'd get if you initialize with `azure.EnvironmentFromName`. For example: the `ResourceIdentifiers.Storage` field which is being used [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/9e920ab31fa0524e05191ce6babe5e94a94db33b/azurerm/internal/clients/builder.go#L82) is missing in output of your [example](https://management.azure.com/metadata/endpoints?api-version=1.0).

Playing around with different values for the `api-version` produces odd results:
* [2018-01-01](https://management.azure.com/metadata/endpoints?api-version=2018-01-01) - this one has locations from the 4 cloud instates from `go-autorest`.
* [2020-01-01](https://management.azure.com/metadata/endpoints?api-version=2018-01-01) - this one has a list of the endpoints from those 4 could instances.

In addition to that, this endpoints output is inconsistent across cloud instances.

Loading the endpoints from a file (or perhaps providing each as a septate parameter to the provider definition) is consistent with other Azure tools. The functionality that enables the definition of custom cloud environments using user provided endpoints is implemented in both [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/cloud?view=azure-cli-latest#az-cloud-register) and [Azure PowerShell](https://docs.microsoft.com/en-us/powershell/module/az.accounts/add-azenvironment). So similarly to these two cases, if there is a schema change (which is rare), then it would be up to the user to update his custom endpoint definition.

The environments in which we want to use this are internal and are not meant to be used by the general public.

**Comment by jbpaux** [comment]
Azure Stack has its own provider but is quite outdated. Would be great if azurerm provider can target both azure public (or china/sovereign/gov/dod) and azure stack hub envs

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
