### ISSUE TITLE
Support for azureml compute 

### ISSUE THREAD

**Issue by epa095** [hashicorp/terraform-provider-azurerm#6827]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To use azure machine learning one [wants](https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-train-models-with-aml#create-or-attach-an-existing-compute-target) to create [compute](https://docs.microsoft.com/en-us/python/api/azureml-core/azureml.core.compute.compute.computetarget?view=azure-ml-py) instances. It would be nice if it was possible to create these using terraform. 

### References
https://docs.microsoft.com/en-us/python/api/azureml-core/?view=azure-ml-py
https://docs.microsoft.com/en-us/azure/machine-learning/

**Comment by lachie-white** [comment]
The ability to "attach" compute as well, so attach external AKS or Databricks instances would be extremely useful
