### ISSUE TITLE
Feature request for Suppressing the alerts after certain time in azurerm_monitor_scheduled_query_rules_alert

### ISSUE THREAD

**Issue by udaypachika** [hashicorp/terraform-provider-azurerm#6842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_monitor_scheduled_query_rules_alert

### Potential Terraform Configuration

*azurerm_monitor_scheduled_query_rules_alert

### References
https://www.terraform.io/docs/providers/azurerm/r/monitor_scheduled_query_rules_alert.html

* #0000

**Comment by mcdafydd** [comment]
Hello,

I think this particular form of suppression is already supported in the resource.  In the Microsoft [example](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-log), they refer to suppression within a scheduled query rule like this:

`"throttlingInMin": "[variables('alertActions').SuppressTimeinMin]",`

This should be supported by the existing resource:

`throttling - (Optional) Time (in minutes) for which Alerts should be throttled or suppressed. Values must be between 0 and 10000 (inclusive).`

Additional suppression support will come from [Action Rules](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-action-rules#suppression-of-alerts), and it looks like a PR (#6563) has already been submitted for that (yay!).

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
