### ISSUE TITLE
Support for LargeFileSharesState argument in azurerm_storage_account

### ISSUE THREAD

**Issue by doherty100** [hashicorp/terraform-provider-azurerm#6857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for the [LargeFileSharesState](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/create#largefilesharesstate) property by adding a corresponding argument to azurerm_storage_account.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "storage_account_01" {
  name                     = random_id.random_id_storage_account_01_name.hex
  resource_group_name      = azurerm_resource_group.resource_group_01.name
  location                 = azurerm_resource_group.resource_group_01.location
  account_kind             = "StorageV2"
  account_tier             = var.storage_account_tier
  access_tier              = var.storage_access_tier
  account_replication_type = var.storage_replication_type
  large_file_shares_enabled = TRUE
  tags                     = var.tags
}
```

### References

* [Azure Rest API Documentation](https://docs.microsoft.com/en-us/rest/api/storagerp/storageaccounts/create#largefilesharesstate)

**Comment by favoretti** [comment]
Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
