### ISSUE TITLE
mongoDB expireAfterSeconds option is currently not supported

### ISSUE THREAD

**Issue by landintrees** [hashicorp/terraform-provider-azurerm#6894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.16
+ provider.azuread v0.6.0
+ provider.azurerm v1.44.0
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

* `azurerm_cosmosdb_mongo_collection`

### Terraform Configuration Files

```hcl
data "azurerm_cosmosdb_account" "example" {
  name                = "tfex-cosmosdb-account"
  resource_group_name = "tfex-cosmosdb-account-rg"
}

resource "azurerm_cosmosdb_mongo_database" "example" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = data.azurerm_cosmosdb_account.example.resource_group_name
  account_name        = data.azurerm_cosmosdb_account.example.name
}

resource "azurerm_cosmosdb_mongo_collection" "example" {
  name                = "tfex-cosmos-mongo-db"
  resource_group_name = data.azurerm_cosmosdb_account.example.resource_group_name
  account_name        = data.azurerm_cosmosdb_account.example.name
  database_name       = azurerm_cosmosdb_mongo_database.example.name

  default_ttl_seconds = "0"
  shard_key           = "uniqueKey"
  throughput          = 400
}

```

### Expected Behavior

Mongo DB Collection is created (or skipped if already existing)

### Actual Behavior

Error: Error waiting on create/update future for Cosmos Mongo Collection tfex-cosmos-mongo-db (Account tfex-cosmosdb-account, Database tfex-cosmos-mongo-db): Code="BadRequest" Message="The 'expireAfterSeconds' option is currently not supported.\r\nActivityId: xxxxx-xxxxx-xxxxx-xxxxx, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0"

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This has been working fine for ~4 months until this morning during a terraform apply on an existing deployment (so no changes were necessary) so we suspect this is an issue on the Azure end.

It is somewhat interesting as well that terraform was attempting to remove indexes that it had never needed to before:

```hcl
      - indexes {
          - key    = "$_ts" -> null
          - unique = false -> null
        }
      - indexes {
          - key    = "CosmosDefaultIndex" -> null
          - unique = false -> null
        }
```

### References

* #0000

**Comment by yupwei68** [comment]
Hi @landintrees , thanks for opening this issue. We need to upgrade the service version of the resources in `cosmos`. Our current service version `azurerm_cosmosdb_mongo_database` has expired.

**Comment by landintrees** [comment]
Thanks @yupwei68, as a workaround we commented out the TTL setting and added a lifecycle ignore to the indexes which fixed the issue for us:

```
  #default_ttl_seconds = "0"
  lifecycle {
    ignore_changes = [
      indexes
    ]
  }
```

**Comment by yupwei68** [comment]
Hi @landintrees The `ttl` field has been fixed and released last week from service team. I have tested that it works in Terraform currently. Please retry on your side.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
