### ISSUE TITLE
Use of azurerm_mssql_server_vulnerability_assessment causes InternalServerError

### ISSUE THREAD

**Issue by philspokas** [hashicorp/terraform-provider-azurerm#6961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform -v
Terraform v0.12.25
+ provider.azurerm v2.9.0
+ provider.random v2.2.1

### Affected Resource(s)
azurerm_mssql_server_security_alert_policy

### Terraform Configuration Files

```
resource "azurerm_mssql_server_security_alert_policy" "sqlserver-policy" {
  resource_group_name        = var.resource_group_name
  server_name                = azurerm_sql_server.sqlserver.name
  state                      = "Enabled"
  storage_endpoint           = data.azurerm_storage_account.storageaccount_prod.primary_blob_endpoint
  storage_account_access_key = data.azurerm_storage_account.storageaccount_prod.primary_access_key
  #disabled_alerts = [
   # "Sql_Injection",
    #"Data_Exfiltration"
  #]
  retention_days = 20
}
```
### Debug Output

https://gist.github.com/philspokas/4d563bbcd53d3c77516602a74303c8d0

### Expected Behavior

Resource is provisioned

### Actual Behavior

Error: error waiting for creation/update of mssql server security alert policy (server "<i>server</i>", resource group "<i>group</i>"): Code="InternalServerError" Message="An unexpected error occured while processing the request. Tracking ID: '8ce8527a-06b4-4778-a0cd-6895bcd4a441'"2020-05-15T10:37:06.741-0700 [DEBUG] plugin: plugin process exited: path=C:\Users\pspokas\dev\terraform-templates\resources\sqlserver\.terraform\plugins\windows_amd64\terraform-provider-azurerm_v2.9.0_x5.exe pid=41960

### Steps to Reproduce
1. Add azurerm_mssql_server_vulnerability_assessment to terraform script
2. 'terraform init'
3. 'terraform plan'
4. 'terraform apply'

**Comment by yupwei68** [comment]
Hi @philspokas , thanks for opening this issue. Sorry that I can't reproduce this error. Does this error run out only once or does it run out every time you apply the code?

**Comment by philspokas** [comment]
Hi,

Happens every time.  Another user in the same org is having the same issue.

Thanks.


Phil Spokas | VP Professional Services | 509-492-2214
IntelliTect.com<http://intellitect.com/> | Twitter<https://twitter.com/IntelliTect> | LinkedIn<https://www.linkedin.com/company/intellitect> | Facebook<https://www.facebook.com/Intellitect>

IntelliTect<http://www.intellitect.com/>
Passionate Hard Work, Courageous Honesty, Innovative Excellence<http://intellitect.com/about/>

**Comment by yupwei68** [comment]
hi @philspokas ,Could you provide more detail configurations for `azurerm_sql_server` and `azurerm_storage_account` (behind firewall or not) to help to reproduce this error?

**Comment by yupwei68** [comment]
hi @philspokas Could you please provide more details of the code, like the configurations of the "azurerm_sql_server" and "azurerm_storage_account", behind firewall or not to help to reproduce it?

**Comment by philspokas** [comment]
> hi @philspokas ,Could you provide more detail configurations for `azurerm_sql_server` and `azurerm_storage_account` (behind firewall or not) to help to reproduce this error?

Hi, I add a link to a gist with terraform log output. Is that helpful? The storage account *does* have firewall rules setup, but, the script is being executed from a valid IP. 

Having error details beyond "InternalServerError" in the log would be helpful but I didn't see any.

**Comment by philspokas** [comment]
Update on this: the issue is that the application exits without any proper error message. The root cause is the storage account used by Azure SQL Vulnerability Assessment was not allowing access to Azure Services. 

The fix, in my opinion, is to return a proper error message to the user

**Comment by yupwei68** [comment]
@philspokas Thanks for your suggestion. Since it's an error message returned from service, I'd like to suggest to raise an issue to the service team in https://github.com/Azure/azure-rest-api-specs/issues.

**Comment by favoretti** [comment]
Since this issue has been reported a long time ago and relates to the version of provider we no longer support - I'm going to close it. Please open a new updated bug report on current versions of terraform and provider if this is still relevant. Thank you.
