### ISSUE TITLE
Monitor Metrics alert will fail directly after AKS deployment

### ISSUE THREAD

**Issue by AndreasMWalter** [hashicorp/terraform-provider-azurerm#6996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform: 0.12.24
AzureRM: 2.8.0 (according to the change log it should apply to all the others as well)

### Affected Resource(s)

* `azurerm_monitor_metric_alert`

### Terraform Configuration Files

```hcl

data "azuread_service_principal" "aks_omsprincipal" {
  display_name = "omsagent-${azurerm_kubernetes_cluster.aks.name}"
  depends_on = [azurerm_kubernetes_cluster.aks]
}

resource "azurerm_role_assignment" "monpublisher" {
  scope                = azurerm_kubernetes_cluster.aks.id
  role_definition_name = "Monitoring Metrics Publisher"
  principal_id = data.azuread_service_principal.aks_omsprincipal.id
}

resource "azurerm_monitor_metric_alert" "nodeCPUmonitor" {
  name                = "CPU-above-threshold-alert"
  resource_group_name = azurerm_resource_group.rg.name
  scopes              = [azurerm_kubernetes_cluster.aks.id] 
  description         = "Action will be triggered when CPU Usage is greater than 80 for 30 minutes."

  criteria {
    metric_namespace = "Insights.Container/nodes"
    metric_name      = "cpuUsagePercentage"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 80

    dimension {
      name     = "Host"
      operator = "Include"
      values   = ["*"]
    }
  }
  frequency = "PT30M" 
  window_size = "PT30M"
  action {
    action_group_id = azurerm_monitor_action_group.ag.id
  }
  depends_on = [azurerm_role_assignment.monpublisher]
}
```

### Debug Output

Not needed (timing issue)

### Panic Output
-

### Expected Behavior

The monitor metric alert gets created.

### Actual Behavior

Due to the implementation of AKS metrics the affected namespace and metrics get created once the AKS cluster starts publishing its information into it ("Insights.Container/nodes"). However this means that the AzureRM provider will not be able to resolve the metric name until it is created and subsequently fail with the following error.

```bash
 Error: Error creating or updating metric alert "CPU-above-threshold-alert" (resource group "RGNAME"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="The following metric name(s) were not found: cpuUsagePercentage. Please note that for custom metrics, the relevant metric namespace must be specified."
   on mon.tf line 57, in resource "azurerm_monitor_metric_alert" "nodeCPUmonitor":
```
I would assume that this will also be an issue for Custom Metrics

For the time being I have created a null wait resource to resolve the issue (with bash obviously sleep must be used):

```hcl
resource "null_resource" "waitaks0" {
  provisioner "local-exec" {
    command = "powershell.exe Start-Sleep -Seconds 600"
  }
  depends_on = [azurerm_role_assignment.monpublisher]
}
```
However waiting for the object 600 seconds is not efficient and I have seen the metrics take up to twenty minutes to be published.

Some sort of custom retry interval might be more helpful.

### Steps to Reproduce

* Create an AKS Cluster
* Give the Service Principal/OMS Agent Identity (if using MSI) "Monitoring Metrics Publisher" Permissions
* create the metric alert
* Terraform apply the config

Note: The OMS Agent Identity is not exported by the azurerm_kubernetes_cluster you will need to provide a data source.

```hcl
data "azuread_service_principal" "aks_omsprincipal" {
  display_name = "omsagent-${azurerm_kubernetes_cluster.aks.name}"
  depends_on = [azurerm_kubernetes_cluster.aks]
}
```

I will open a separate feature request for this.

### Important Factoids

Azure Public Cloud (westeurope)

### References

https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-custom-overview
* #0000

**Comment by aristosvo** [comment]
@AndreasMWalter What is the AKS configuration you use? Do you use `addon_profile` or `log_analytics_solution`? I'm trying to understand the usecase and context better to reproduce the problem.

## Addon Profile
```hcl
resource "azurerm_kubernetes_cluster" "aks" {
...
  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = azurerm_log_analytics_workspace.law.id
    }
  }
...
}
```
## Log Analytics Solution
```hcl
resource "azurerm_log_analytics_solution" "la-container-solution" {
  # For first party solution, the solution name has to be convention of solutionType(workspaceName), and the product has to be OMSGallery/solutionType.
  # For example, product OMSGallery/ChangeTracking, solution name ChangeTracking(myworkspace)
  solution_name         = "ContainerInsights"
  location              = var.context.location
  resource_group_name   = var.context.resource_group_name
  workspace_resource_id = azurerm_log_analytics_workspace.law.id
  workspace_name        = azurerm_log_analytics_workspace.law.name

  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}```

**Comment by AndreasMWalter** [comment]
Hiya, we are using the addon_profile configuration

**Comment by degaravikumaryadav** [comment]
In order to create an alert on metric namespace "Insights.Container/nodes", they should be enabled first. Here is the link to enable these metric namespaces.
https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-update-metrics

**Comment by d-tris** [comment]
I've just encountered this as well. It seems that the issue is indeed caused by the fact that the metrics need to be emitted before alerts are created for them.

However, there must be a way to create alerts for such metrics - in fact, enabling the recommended alerts in the Azure Portal does create alerts for not-yet-emitted metrics.

Maybe the [`SkipMetricValidation`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.monitor.models.multimetriccriteria.skipmetricvalidation?view=azure-dotnet) property could help with this? Though it does mention only custom metrics, so I'm not sure.

**Comment by degaravikumaryadav** [comment]
> BTW @degaravikumaryadav as far as I can tell, "enabling them" in this case means giving AKS's OMS Agent the "Monitoring Metrics Publisher" role, right?

Yes, it is.

**Comment by hetii** [comment]
@AndreasMWalter Hi.

I try your code but, as I notice I my cluster don't expose any omsagent-* for .data.azuread_service_principal resource.

I just have service principal that I use to provision cluster itself, and it has owner role, so not sure if this is the one where I need to assing "Monitoring Metrics Publisher"?

**Comment by torbendury** [comment]
Hi, sorry for interrupting you two, but I just ran into a similar problem. I want to use Log Analytics (activated via `addon_profile`) and read through [this link to Azure Docs](https://docs.microsoft.com/en-us/azure/azure-monitor/containers/container-insights-update-metrics) which describe that I have to click certain stuff in the Azure Portal. As you described, this basically gives the `omsagent` SP a certain role - are we able to do this via Terraform, or do we **really** need to click this stuff?

**Comment by AndreasMWalter** [comment]
> 

If you look into my code above you will find a role assignment, however, since I originally created the issue a lot of time has passed so I am unsure if it still works :)

The original issue was resolved by the addition of this parameter: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert#skip_metric_validation
