### ISSUE TITLE
app_service: deprecate the built-in `python_version` field since its deprecated

### ISSUE THREAD

**Issue by cdeil** [hashicorp/terraform-provider-azurerm#7010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

What is the meaning of this setting?

https://www.terraform.io/docs/providers/azurerm/r/app_service.html#python_version

Terraform currently only allows values "2.7" or "3.4".

I think the currently supported versions on Azure are "3.6" and "3.7"
https://docs.microsoft.com/en-us/azure/app-service/containers/quickstart-python?tabs=bash

Currently I get this:
```
% az webapp list-runtimes | grep python
  "python|2.7",
  "python|3.6",
```

But I have a web app running that I configured to 3.7 via:
```
az webapp create --runtime "PYTHON|3.7"
```
that's running and I see that version in the portal.

Can you please update the allowed versions here to add "3.7" in Terraform?
Or alternatively explain in the docs why only 3.4 is allowed?

### New or Affected Resource(s)

- `azurerm_app_service`

**Comment by cdeil** [comment]
```
% az webapp list-runtimes --linux | grep PYTHON
  "PYTHON|3.8",
  "PYTHON|3.7",
  "PYTHON|3.6",
  "PYTHON|2.7"
```

**Comment by lrxtom2** [comment]
@cdeil Hi, Thanks for opening the issue!
I will work on to fix this.

**Comment by mloar** [comment]
I've opened a PR that changes the validation list for the `python_version` argument. However, I now think this is not the right solution.

I have an App Service that I created through the Azure Portal with the Python Version set to 3.7. Running `terraform plan` shows that `python_version` is not set at all. Instead, the appropriate argument appears to be `linux_fx_version`, which is set to `PYTHON|3.7`. I can't find any Azure documentation on the purpose of `SiteConfig.PythonVersion`, but it does not appear to be the correct way to set the Python version that is used to run the application.

I suggest that perhaps the proper fix is simply to document that setting `python_version` is probably not what users want to do, and they should use `linux_fx_version` or `windows_fx_version` instead.

**Comment by tombuildsstuff** [comment]
👋 

After reviewing #7213 (thanks @mloar) - it appears this field is being deprecated in favour of the `linux_fx_version` field - as such I'm going to "re-target" this issue towards deprecating that field & highlighting the replacement path instead

Thanks!

**Comment by rcskosir** [comment]
Thanks for opening this issue. The `azurerm_app_service` resource itself is now deprecated and will be removed in a future versions of the provider. As such, I am going to close this issue.
