### ISSUE TITLE
Support for Put Empty or 0 bytes Storage Blobs

### ISSUE THREAD

**Issue by Vimary94** [hashicorp/terraform-provider-azurerm#7046]
Hello,
There are some 0 bytes file that are required to be stored in Storage as block blobs, these files can be created successfully through the Portal or Azure Storage Manager.However, I have the following issue:

> Error PutBlockBlobFromFile: Error putting bytes: blobs.Client#PutBlockBlob: Invalid input: `input.Content` must either be nil or not empty.

The terraform version is : v0.12.24
Azure Provider: 2.0.0

Thank you, 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by lrxtom2** [comment]
@Vimary94 Thanks for opening the issue! Could you please provide more context about that? Like TF Code, Repro steps or something others. I will help you to resolve the question.

**Comment by bchess** [comment]
This happens when you `source` a file that is size 0.

E.g.

**Comment by bchess** [comment]
This happens when you source a file that is size 0. E.g.

**Comment by heoelri** [comment]
Another option to create an empty blob is to use `source_content`:

```hcl
# Empty Storage Blob for Azure Front Door health checks 
resource "azurerm_storage_blob" "healthcheck" {
  name                   = "health.check"
  storage_account_name   = azurerm_storage_account.deployment.name
  storage_container_name = azurerm_storage_container.sys.name
  type                   = "Block"
  source_content         = "" # empty file
}
```

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
