### ISSUE TITLE
Support for access policies and EventSources for Time Series Insights

### ISSUE THREAD

**Issue by alex-3sr** [hashicorp/terraform-provider-azurerm#7053]
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi All,

First, thank to add recently support for TSI environnements, with azurerm_time_series_insights_standard_environment ;)
For complete a full TSI deployment, we need at least 2 others parts of ressources ->
* Events Sources : "Microsoft.TimeSeriesInsights/environments/eventsources"
* Access Policies : "Microsoft.TimeSeriesInsights/environments/accesspolicies"

It could be nice to have theses 2 new ressources with the new one, for complete now a full TSI deployment without requiring to use ARM template.

Thanks ;)

### New or Affected Resource(s)

The 2 new TF resources could be like this ->
* azurerm_time_series_insights_eventsources
* azurerm_time_series_insights_access_policy

### Potential Terraform Configuration

* azurerm_time_series_insights_eventsources
```hcl
resource "azurerm_time_series_insights_eventsources" "example" {
  name = "example"
  location = resource.rg.location
  tsi_environnement = resource.azurerm_time_series_insights_standard_environment.id
  kind = "Microsoft.EventHub"
  properties {
    servicebusnamespaceId = "/subscriptions/xxxx/xxxx"
	eventhubname = "eventhubexample"
	keyname = "mykey"
	consumergroupname = "$Default"
	sharedAccessKey = "xxxxxxxxxxxxxxxxxxx"
  }
}
```

* azurerm_time_series_insights_access_policy
```hcl
resource "azurerm_time_series_insights_access_policy" "example" {
  name = "example"
  tsi_environnement = resource.azurerm_time_series_insights_standard_environment.id
  object_id = "11111111-1111-1111-1111-111111111111"
  roles = ["Reader","Contributor"]
}
```

### References

TSI Access Policies : https://docs.microsoft.com/en-us/azure/templates/microsoft.timeseriesinsights/2017-11-15/environments/accesspolicies
TSI Event sources : https://docs.microsoft.com/en-us/azure/templates/microsoft.timeseriesinsights/2017-11-15/environments/eventsources

**Comment by alex-3sr** [comment]
Hi,

I see that now is available https://www.terraform.io/docs/providers/azurerm/r/iot_time_series_insights_access_policy.html ;) thank you. Although, I noticed an error in documentation ->
_resource_group_name - (Required) The name of the resource group in which to create the Azure IoT Time Series Insights Access Policy._

_resource_group_name_ is not required and more, it's not an accepted argument ;) Please, can you remove it from the doc.

Thanks
Regards

**Comment by Lachlan-White** [comment]
Very keen to see Event Sources as a resource for TSI. The TSI Resource isn't able to do a lot without having this available for configuration, and it's a bit clunky doing half with Terraform and half with ARM at the moment

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
