### ISSUE TITLE
Support for "Allow trusted Microsoft Services" in Event Hub Namespace networking restrictions

### ISSUE THREAD

**Issue by sebader** [hashicorp/terraform-provider-azurerm#7104]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Event Hub Namespace supports to open the firewall for trusted Microsoft Services. This should be possible to set through Terraform as well
![image](https://user-images.githubusercontent.com/11445087/82991262-b0cd2c80-9ffd-11ea-975f-5e8eeb17580e.png)

### New or Affected Resource(s)

* azurerm_eventhub_namespace

### Potential Terraform Configuration

```hcl
resource "azurerm_eventhub_namespace" "example" {
  name                = "example-namespace"
  
  network_rulesets {
    allow_trusted_microsoft_services_bypass_firewall = true
  }
}
```

**Comment by kvendingoldo** [comment]
I started to work on this in my MR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/9038

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (#10169) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
