### ISSUE TITLE
Shared access signature for Azure Eventhub

### ISSUE THREAD

**Issue by MourIdri** [hashicorp/terraform-provider-azurerm#7160]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi there. 

It is possible to implement shared access signature for azure event hub ? 
like it is possible to communicate with the service Azure blob in a programmatic way. 

SAS token capability is implemented for Storage here : 
https://www.terraform.io/docs/providers/azurerm/d/storage_account_sas.html

while the possibility to do it for Azure Hub is documented here : 
https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token#bash
but not yet possible on Terraform.

In any case, Eventhub is the best approach to expose events from Azure to outer world ( like SIEMs : Qradar, splunk etc... )

Thanks

**Comment by Suseelraj** [comment]
Any Updates on this feature yet?

**Comment by jrblanno** [comment]
it would be amazing to have this feature, is it being developed ?
