### ISSUE TITLE
Support for encrypted disks with azurerm_site_recovery_replicated_vm

### ISSUE THREAD

**Issue by ubenmackin** [hashicorp/terraform-provider-azurerm#7239]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently I am able to use azurerm_site_recovery_replicated_vm as long as I do not have the VM Disk Encryption extension enabled (AzureDiskEncryption).

```hcl
resource "azurerm_key_vault" "shared" {
  name                = "${var.prefix}-kv-pri-shared"
  resource_group_name = azurerm_resource_group.kv.name
  location            = azurerm_resource_group.kv.location

  enabled_for_disk_encryption = true
  tenant_id                   = data.azurerm_client_config.current.tenant_id
  sku_name                    = var.key_vault_sku

  network_acls {
    default_action = "Deny"
    ip_rules       = var.key_vault_ip_cidr
    bypass         = "AzureServices"
  }
}

resource "azurerm_virtual_machine_extension" "mgmt-encrypt" {
  name  = "AzureDiskEncryption"

  virtual_machine_id         = azurerm_windows_virtual_machine.mgmt.id
  publisher                  = "Microsoft.Azure.Security"
  type                       = "AzureDiskEncryption"
  type_handler_version       = "2.2"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
{
    "EncryptionOperation": "EnableEncryption",
    "KeyVaultURL": "${azurerm_key_vault.shared.vault_uri}",
    "KeyVaultResourceId": "${azurerm_key_vault.shared.id}",
    "VolumeType": "OS"
}
             SETTINGS
}
```

If I enable disk encryption, the the terraform apply fails:

```
Error: Error creating replicated vm mgmt-vm-replication (vault nardl-recovery-vault-shared): Code="150175" Message="Virtual machine's OS disk is encrypted and there is no disk information found."
2020-06-06T03:39:17.2678042Z 
2020-06-06T03:39:17.2678389Z   on 06-recoveryvault.tf line 105, in resource "azurerm_site_recovery_replicated_vm" "mgmt-vm-replication":
2020-06-06T03:39:17.2678899Z  105: resource "azurerm_site_recovery_replicated_vm" "mgmt-vm-replication" {
2020-06-06T03:39:17.2679119Z 
```

If I apply the replication for the VM from the Azure Portal, it asks for the Disk encryption key vault source and target, which doesn't appear to be an option on the current azurerm_site_recovery_replicated_vm resource interraform.

Digging in further, if I export an ARM template before enabling the site replication, I see the following in the replicationProtectedItems section.

```json
"type": "microsoft.recoveryservices/vaults/replicationFabrics/replicationProtectionContainers/replicationProtectedItems",
            "apiVersion": "2018-07-10",
            "name": "",
            "properties": {
                "policyId": "",
                "protectableItemId": "",
                "providerSpecificDetails": {
                    "instanceType": "A2A",
                    "fabricObjectId": "",
                    "recoveryResourceGroupId": "",
                    "recoveryContainerId": "",
                    "vmDisks": [],
                    "vmManagedDisks": [
                        {
                            "diskId": "",
                            "primaryStagingAzureStorageAccountId": "",
                            "recoveryResourceGroupId": "",
                            "recoveryReplicaDiskAccountType": "",
                            "recoveryTargetDiskAccountType": "",
                            "diskEncryptionInfo": {
                                "diskEncryptionKeyInfo": {
                                    "secretIdentifier": "",
                                    "keyVaultResourceArmId": ""
                                },
                                "keyEncryptionKeyInfo": {
                                    "keyIdentifier": "",
                                    "keyVaultResourceArmId": ""
                                }
                            }
                        }
                    ],
                    "multiVmGroupName": "",
                    "recoveryAzureNetworkId": ""
                }
            }
```

Namely the section for diskEncryptionInfo under vmManagedDisks. It takes the target key vault and target encryption secret as arguments (I believe in a previous step it copies the secret from the source key vault to the target).

### New or Affected Resource(s)

* azurerm_site_recovery_replicated_vm

### Potential Terraform Configuration

Suggest adding a target_key_vault_id to the managed_disk block:

```hcl
resource "azurerm_site_recovery_replicated_vm" "vm-replication" {
  name                = "mgmt-vm-replication"
  resource_group_name = azurerm_resource_group.shared.name

  recovery_vault_name                       = azurerm_recovery_services_vault.vault.name
  source_recovery_fabric_name               = azurerm_site_recovery_fabric.primary.name
  source_vm_id                              = azurerm_windows_virtual_machine.mgmt.id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  source_recovery_protection_container_name = azurerm_site_recovery_protection_container.primary.name

  target_resource_group_id                = azurerm_resource_group.shared.id
  target_recovery_fabric_id               = azurerm_site_recovery_fabric.secondary.id
  target_recovery_protection_container_id = azurerm_site_recovery_protection_container.secondary.id

  managed_disk {
    disk_id                    = "/subscriptions/${var.subscription_id}/resourcegroups/${azurerm_resource_group.shared.name}/providers/microsoft.compute/disks/${azurerm_windows_virtual_machine.mgmt.os_disk.0.name}"
    staging_storage_account_id = azurerm_storage_account.recoverycache-pri.id
    target_resource_group_id   = azurerm_resource_group.shared.id
    target_disk_type           = "Premium_LRS"
    target_replica_disk_type   = "Premium_LRS"
    target_key_vault_id       = azurerm_key_vault.shared.id
  }
}
```

On a side note, there doesn't seem to be a way to access the managed_disk on the azurerm_windows_virtual_machine like we could previously on azurerm_virtual_machine. On azurerm_virtual_machine the following worked:

azurerm_virtual_machine.mgmt.storage_os_disk.0.managed_disk_id

However, on the new azurerm_windows_virtual_machine I don't see a way to get the disk ID, only the name. That is why in the configuration snippet above, I have a long ID parsed together from pieces.

**Comment by balyssruoga** [comment]
do you have any updates on resolution

**Comment by neilamoran** [comment]
Is this still an outstanding problem?

**Comment by myc2h6o** [comment]
I'm able to repro the issue. Currently [this feature](https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-how-to-enable-replication-ade-vms) is not supported. I'm considering adding the support for it, will update if I have any progress

**Comment by piyaldas** [comment]
> I'm able to repro the issue. Currently [this feature](https://docs.microsoft.com/en-us/azure/site-recovery/azure-to-azure-how-to-enable-replication-ade-vms) is not supported. I'm considering adding the support for it, will update if I have any progress

Hey @myc2h6o 
We are developing our entire architecture with ASR & ADE enabled for one of our client via Terraform.
Any updates on this, by when we can get the feature/attribute ready in the terraform module.

**Comment by devsheoran** [comment]
Hi @myc2h6o We are also looking to implement RSA replication (Azure to Azure) for ADE encrypted VMs using Terraform; waiting to hear any update on this.

**Comment by myc2h6o** [comment]
I've done adding the properties and is struggling with the test case, will send a pr probably by the end of this week

**Comment by myc2h6o** [comment]
Hi all, I've raised a pr to add the support for this feature.

And for below restriction of not able to get ID of a linux/windows virtual machine's OS Disk,
> On a side note, there doesn't seem to be a way to access the managed_disk on the azurerm_windows_virtual_machine like we could previously on azurerm_virtual_machine. On azurerm_virtual_machine the following worked:

Using the `azurerm_managed_disk` data source can workaround it.
```hcl
data "azurerm_managed_disk" "test" {
  name                = azurerm_linux_virtual_machine.test.os_disk[0].name
  resource_group_name = azurerm_linux_virtual_machine.test.resource_group_name
}

//The OS Disk id can then be retrieved from data.azurerm_managed_disk.test.id
```

**Comment by devsheoran** [comment]
@myc2h6o Not sure if you tested [this ](https://discuss.hashicorp.com/t/challenges-azure-site-recovery-implementation-for-ade-encrypted-vms/37619)scenario during your testing. If yes, I think you can provide some helpful suggestion on the issue.

**Comment by myc2h6o** [comment]
Hi @devsheoran I haven't tried doing the actual backup yet, but from the link you shared seems like `create_option` of the restored disk changes to `restore`. I assume this is by design as the disk is not the original one but a restored disk. To avoid the force replacement, you can add `create_option` to `ignore_changes` described [here](https://www.terraform.io/language/meta-arguments/lifecycle). I'll try this scenario by myself and see if there is a better way to manage the disk which is to be resotred.

**Comment by devsheoran** [comment]
> 

It did the trick. Thanks @myc2h6o
