### ISSUE TITLE
azurerm_linux_virtual_machine_scale_set output private ip 

### ISSUE THREAD

**Issue by jamiephillips0000** [hashicorp/terraform-provider-azurerm#7333]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to generate an ssh config from terraform inventory using a template. We use a scale set but it is pretty static and we only ever expand for big events. The azurerm_linux_virtual_machine_scale_set is a welcome improvement over the azurerm_virtual_machine_scale_set but it still does not export the private IPs of the VM's it creates.

```hcl
resource "azurerm_linux_virtual_machine_scale_set" "java" {
  instances           = var.java_count
  .....
}
output "java-main" {
    value=azurerm_linux_virtual_machine_scale_set.java
}
```

### New or Affected Resource(s)

- azurerm_linux_virtual_machine_scale_set

### Potential Terraform Configuration

```hcl
output "java-main" {
    value=azurerm_linux_virtual_machine_scale_set.java.private_ip_adresses # a map of instance id to ip address
}

```

**Comment by hbuckle** [comment]
#6752 should help with this?

**Comment by ArcturusZhang** [comment]
Hi @jamiephillips0000 thanks for this issue! And thanks @hbuckle this PR should exactly be the one this issue is asking for.

**Comment by wandrew26** [comment]
Would love to see this in the next release! Any hope for that?
