### ISSUE TITLE
Enhancement to azurerm_mssql_virtual_machine Resource

### ISSUE THREAD

**Issue by knighteagle789** [hashicorp/terraform-provider-azurerm#7341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am working on creating a terraform plan to create custom database servers.  In the ARM template, I see options to configure the storage settings (StorageConfigurationSettings).  I would love to see these same options available in the Terraform Resource as well.

Here is the example in the ARM template for reference:
.....
                "StorageConfigurationSettings": {
                    "DiskConfigurationType": "[parameters('sqlStorageDisksConfigurationType')]",
                    "StorageWorkloadType": "[parameters('sqlStorageWorkloadType')]",
                    "SQLDataSettings": {
                        "LUNs": "[parameters('dataDisksLUNs')]",
                        "DefaultFilePath": "[parameters('dataPath')]"
                    },
                    "SQLLogSettings": {
                        "LUNs": "[parameters('logDisksLUNs')]",
                        "DefaultFilePath": "[parameters('logPath')]"
                    },
                    "SQLTempDbSettings": {
                        "DefaultFilePath": "[parameters('tempDbPath')]"
                    }
                },
.....

**Comment by yupwei68** [comment]
Hi @knighteagle789 , thanks for opening this issue. We might need to wait till the service team return the block `StorageConfigurationSettings` back when we get the sql vm throught its service api before our Terraform implementation. I'll keep this issue open to track this issue.

**Comment by valentin-stefan-popa** [comment]
Any news?

**Comment by tnerguiTT** [comment]
Hi,

Found this on the repo:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_virtual_machine#data_settings

Please advise if there is there any sample of this block where I can reference to?

Thanks much.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
