### ISSUE TITLE
Support for "None" ip_address_type in azurerm_container_group

### ISSUE THREAD

**Issue by briangardner** [hashicorp/terraform-provider-azurerm#7416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure allows for container groups to be created with "None" as the IP Address Type.  When trying to create an instance of `azurerm_container_group` with `ip_address_type` set to "None", the following error is thrown:

Error: expected ip_address_type to be one of [Public Private], got None

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_container_group" "example" {
  name                = "example-continst"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  ip_address_type     = "None"
  os_type             = "Linux"

  container {
    name   = "hello-world"
    image  = "microsoft/aci-helloworld:latest"
    cpu    = "0.5"
    memory = "1.5"

    ports {
      port     = 443
      protocol = "TCP"
    }
  }

  container {
    name   = "sidecar"
    image  = "microsoft/aci-tutorial-sidecar"
    cpu    = "0.5"
    memory = "1.5"
  }

  tags = {
    environment = "testing"
  }
}

```

### References

* #0000

**Comment by SebRosander** [comment]
Hi @briangardner , can you please elaborate a bit on this? I've looked into the following parts and can't find any support fort "None" for ip_address_type:

-  SDK (https://godoc.org/github.com/Azure/azure-sdk-for-go/services/containerinstance/mgmt/2018-10-01/containerinstance#ContainerGroupIPAddressType) 

- REST  (https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/get#containergroupipaddresstype)

- Microsoft.ContainerInstance containerGroups template reference (https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups#ipaddress-object)

**Comment by briangardner** [comment]
According to [this](https://docs.microsoft.com/en-us/azure/templates/microsoft.containerinstance/containergroups), the `ipAddress` object is not required.  And in the Azure Portal, you can create a container "None" selected for networking.

![Capture](https://user-images.githubusercontent.com/1761566/85601017-fb9d8c80-b61b-11ea-9510-e0dca40ca280.PNG)

**Comment by booyaa** [comment]
Also in the REST API, this is not a required option in the request body: [docs](https://docs.microsoft.com/en-us/rest/api/container-instances/containergroups/createorupdate#request-body)

**Comment by afdezl** [comment]
`None` seems to also be the default when deploying with docker-compose. This addition would be quite useful.

**Comment by booyaa** [comment]
I've been doing some digging around what the Azure CLI when you omit the IP Address Type (`--ip-address`), I'm wondering if the upstream SDK used by the provider could be modified to behave like this?

The output below has been edited for brevity

```sh
az container create --debug --resource-group rg-lab-hello --name hello --image microsoft/aci-helloworld:latest 
msrest.http_logger: Request URL: 'https://management.azure.com/subscriptions/cd54c26a-69eb-42de-b7d5-4aab87f2d6ca/resourceGroups/rg-lab-hello/providers/Microsoft.ContainerInstance/containerGroups/hello?api-version=2018-10-01'
msrest.http_logger: Request method: 'PUT'
msrest.http_logger: Request body:
msrest.http_logger: {"location": "centralus", "tags": {}, "properties": {"containers": [{"name": "hello", "properties": {"image": "microsoft/aci-helloworld:latest", "resources": {"requests": {"memoryInGB": 1.5, "cpu": 1.0}}}}], "restartPolicy": "Always", "osType": "Linux"}}
```

We can see Azure CLI v2.24.0 talks to the Azure management REST API via Python SDK (azsdk-python-azure-mgmt-resource/18.0.0) and presumably the SDK provides defaults for missing parameters:

- Memory
- CPU
- Restart policy
- OS Type 

The response from the REST API is fine, there's no mention of IP Address Type

```sh
msrest.http_logger: Response content:
msrest.http_logger: {"properties":{"provisioningState":"Succeeded","containers":[{"name":"hello","properties":{"image":"microsoft/aci-helloworld:latest","ports":[],"environmentVariables":[],"instanceView":{"restartCount":0,"currentState":{"state":"Running","startTime":"2021-06-04T14:57:58.032Z","detailStatus":""}},"resources":{"requests":{"memoryInGB":1.5,"cpu":1.0}}}}],"restartPolicy":"Always","osType":"Linux","instanceView":{"events":[],"state":"Running"}},"id":"/subscriptions/cd54c26a-69eb-42de-b7d5-4aab87f2d6ca/resourceGroups/rg-lab-hello/providers/Microsoft.ContainerInstance/containerGroups/hello","name":"hello","type":"Microsoft.ContainerInstance/containerGroups","location":"centralus","tags":{}}
```

Finally the JSON output (happens on a lot of Azure CLI commands), you can see the value is "null", I'm assuming the Azure CLI is interpreting any missing values as "null".

```json
{
  "containers": [
    {
      "command": null,
      "environmentVariables": [],
      "image": "microsoft/aci-helloworld:latest",
      "instanceView": {
        "currentState": {
          "detailStatus": "",
          "exitCode": null,
          "finishTime": null,
          "startTime": "2021-06-04T15:03:49.867000+00:00",
          "state": "Running"
        },
        "events": null,
        "previousState": null,
        "restartCount": 0
      },
      "livenessProbe": null,
      "name": "hello",
      "ports": [],
      "readinessProbe": null,
      "resources": {
        "limits": null,
        "requests": {
          "cpu": 1.0,
          "gpu": null,
          "memoryInGb": 1.5
        }
      },
      "volumeMounts": null
    }
  ],
  "diagnostics": null,
  "dnsConfig": null,
  "id": "/subscriptions/xxx/resourceGroups/rg-lab-hello/providers/Microsoft.ContainerInstance/containerGroups/hello",
  "identity": null,
  "imageRegistryCredentials": null,
  "instanceView": {
    "events": [],
    "state": "Running"
  },
  "ipAddress": null,
  "location": "centralus",
  "name": "hello",
  "networkProfile": null,
  "osType": "Linux",
  "provisioningState": "Succeeded",
  "resourceGroup": "rg-lab-hello",
  "restartPolicy": "Always",
  "tags": {},
  "type": "Microsoft.ContainerInstance/containerGroups",
  "volumes": null
}
```

**Comment by lonegunmanb** [comment]
Hello @briangardner , since the `azurerm_container_group` has supported `None` as `ip_address_type` now ([doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/container_group#ip_address_type)), would you please close this issue? Many thanks!
