### ISSUE TITLE
Support for azurerm_subnets

### ISSUE THREAD

**Issue by jpreese** [hashicorp/terraform-provider-azurerm#7418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Create a new data source `azurerm_subnets` that takes a list of subnets by name and returns the details of those subnets.

### New or Affected Resource(s)

* azurerm_subnets

### Potential Terraform Configuration

```hcl
data "azurerm_subnets" "subnets" {
  subnets = var.subnets
}
```

Where `var.subnets` could be:

```hcl
type = set(object({
  name = string
  virtual_network_name = string
  resource_group_name = string
)
```

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. May I know what you want to get for details of subnet?

**Comment by jpreese** [comment]
@neil-yechenwei minimally the subnet ids, though one could make the argument to keep it the same as azurerm_subnet.

The exact use case for this request is to be used with the azurem_key_vault resource. We'd like to be able to have a module that creates a key vault and allows the subnets to access it based on input values. Right now we have to have a data provider per subnet.

**Comment by tombuildsstuff** [comment]
hey @jpreese 

Thanks for opening this issue :)

I believe this should already be achievable using Terraform's `count` parameter on the Data Source to achieve this, for example:

```hcl
provider "azurerm" {
  version = "=2.15.0"
  features {}
}

resource "azurerm_resource_group" "test" {
  count    = "3"
  name     = "tom-dev${count.index}"
  location = "West Europe"
}

data "azurerm_resource_group" "test" {
  count      = 3
  name       = "tom-dev${count.index}"
  depends_on = [azurerm_resource_group.test]
}

output "names" {
  value = data.azurerm_resource_group.test.*.name
}
```

Would you be able to take a look and see if that works for you? Whilst we could look to introduce a new data source specifically for this, I believe this should already be possible using the `count` parameter here (which in your case can be achieved using the size/value of the list for the count/name respectively)

Thanks!

**Comment by jpreese** [comment]
Yep! That should definitely work, we've taken a similar approach in a few of our other modules. It's just a little nicer to be able to use for_each and rather than calling the data provider once per item in the collection, batch it into one. 

Minor quality of life additions, but I saw other data sources that did this so I wasn't sure if the plan was to provide a plural alternative for all of them or not.

**Comment by neil-yechenwei** [comment]
Yes. I assume it also works fine on `tf plan`.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
