### ISSUE TITLE
Imported Device Provisioning Service (DPS) has a diff between Azure Portal and Terraform Configuration

### ISSUE THREAD

**Issue by v1r7u** [hashicorp/terraform-provider-azurerm#7443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In our product we had an existing DPS, which we started managing by terraform. The component at Azure Portal is shown with `apply_allocation_policy = true` and `allocation_weight = 1`. When we described the resource with the same properties as we see at portal and import it to the configuration, the next terraform apply command says it's going to change DPS resource:
![image](https://user-images.githubusercontent.com/1583399/85382956-bf94f980-b53f-11ea-8abb-f0b54200ab32.png)

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.26
+ provider.azurerm v2.15.0
```

### Affected Resource(s)

* `azurerm_iothub_dps`

### Terraform Configuration Files

```hcl
resource "azurerm_iothub_dps" "dps" {
  name                = "dps-v1r7u-issue"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location

  sku {
    name     = "S1"
    capacity = "1"
  }

  linked_hub {
    connection_string = azurerm_iothub_shared_access_policy.dps.primary_connection_string
    location = azurerm_resource_group.rg.location
    apply_allocation_policy = true
    allocation_weight = 1
  }
}

```

### Expected Behavior

After DPS is imported, the following `terraform plan/apply` shows empty changeset.

### Actual Behavior

`terraform plan/apply` shows changes in `linked_hub` configuration.

### Steps to Reproduce

Detailed steps to reproduce and terraform configuration sample I've committed to the repo https://github.com/v1r7u/azurerm_issues/tree/master/src/dps_import

**Comment by xuzhang3** [comment]
Hi @v1r7u, Thanks your feedback. It is not recommend to manager the Azure resource though the portal and Terraform at the same time. Although the resource has not changed, but this will may cause unexpected  behavior.

**Comment by v1r7u** [comment]
@xuzhang3 I know, and we are not going to do that. In our product, we had a kind of _starting point_, when some resources were created a while ago and now we're managing them by terraform. One of these resources is DPS.

When DPS is created with default values at Azure Portal, Azure Portal shows it as `apply_allocation_policy = true` and `allocation_weight = 1`. But if I import it to terraform, TF sees the same resource as `apply_allocation_policy = false` and `allocation_weight = 0` (btw, these are defaults at azurerm provider, so that might contribute to the issue). Thus, any TF plan/apply says they are going to change DPS resource in-place.

It's not critical issue, as proposed by TF changeset will do no harm to real DPS.

**Comment by xuzhang3** [comment]
@v1r7u I did some test and use POSTMAN to handle the HTTP request. This is API's behavior.
1. First, I create DPS with terraform, Terraform will set `apply_allocation_policy` and `allocation_weight` values and add these two variables to the request body. After DPS created, I can get these variables.
![image](https://user-images.githubusercontent.com/57888764/85970141-1a28cc80-b9fc-11ea-832a-0fb0cd8700c2.png)

2. Second, I delete the linked hubs through portal and recreate the linked hubs with the same policy. When I call the API, `apply_allocation_policy` and `allocation_weight` won't be returned. After I did some update through portal and call the API again, these two variables will be returned now. 
 -  after delete 
![image](https://user-images.githubusercontent.com/57888764/85970189-3d537c00-b9fc-11ea-904f-7703350280a8.png)
 - create through portal (`apply_allocation_policy` and `allocation_weight` won't return)
![image](https://user-images.githubusercontent.com/57888764/85970316-b9e65a80-b9fc-11ea-9744-0b2a339ae9f0.png)
 - update configure
![image](https://user-images.githubusercontent.com/57888764/85970364-dda9a080-b9fc-11ea-99e5-d2024e520916.png)

Based on my test: 
1. If we create the linked hubs with specified `apply_allocation_policy` and `allocation_weight` values, API will return these two variables.
2. If we create the linked hubs without  `apply_allocation_policy` and `allocation_weight`, API won't return these two variables. But  after we update the linked hub configures, the `apply_allocation_policy` and `allocation_weight` will be returned. 

[IOT DPS REST spec update example](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/deviceprovisioningservices/resource-manager/Microsoft.Devices/stable/2018-01-22/examples/DPSUpdate.json)

**Comment by v1r7u** [comment]
@xuzhang3 that's great investigation! Thank you!

Based on your data, I have a theory that Azure itself and `azurerm` provider treat the absence of `apply_allocation_policy` and `allocation_weight` values in different ways: 
- Terraforms considers no-data as `false` and `0`
- Azure - as `true` and `1`

Unfortunately, trying to prove it would take some time. And as far as I can not do it in working time due to other tasks, I can not give you a proper ETA. I'll do my best to update the thread by the end of the week.

**Comment by v1r7u** [comment]
I did a few more tests and my conclusion is the following:
1. Azure, by default, use `null` for `allocation_weight` and `apply_allocation_policy `. I receive this result from `az cli` (see screenshot at the end of the post). I think, go-sdk also [uses nullable types](https://github.com/Azure/azure-sdk-for-go/blob/37f3f4162dfce955ef5225ead57216cf8c1b2c70/services/provisioningservices/mgmt/2018-01-22/iothub/models.go#L207-L210) for these properties
2. But, Azure internally treats empty values for these properties as `true` and `1`. It's shown this way at portal, and DPS itself behaves as they are set to `apply_allocation_policy = true` and `allocation_weight = 1`.
3. terraform `azurerm` provider has default values `0` and `false`.

Thus, if azure responds with `null`s, terraform _thinks_ it's `0` and `false`, which in fact is not right...

I think, there are two problems:
- Azure behaves contradictory: API response differs from component behavior (and Azure Portal UI)
- `azurerm` provider uses defaults, that do not correspond to the real component behavior.

I think the right way to fix it: Azure internally sets default values to `1` and `true` instead of `null`; after that `azurerm` provider can use the same defaults. 

On the other hand, we could change `azurerm` defaults to  `1` and `true`  without requesting Azure team to make a change on their side. This still leaves the root cause of the issue, but aligns TF with azure behavior.

Frankly, I'm puzzled about what to do. The issue is not that critical, but we already spend so many hours on it, that it itches to solve it somehow. 

<details>
<summary>Proof with screenshots</summary>

1. Created by TF linked_hub returns non `null` properties:
![01_created_by_tf](https://user-images.githubusercontent.com/1583399/86400347-bbd44600-bca8-11ea-8d6f-71f63b616e92.png)

2. Manually created from portal `linked_hub` returns `null` properties:
![02_created_through_portal](https://user-images.githubusercontent.com/1583399/86400267-9a735a00-bca8-11ea-871a-f608fe97f49b.png)

In both cases, Azure portal displays the same.

</details>

**Comment by chdalski** [comment]
I can confirm the described behavior with Terraform v0.12.28.
And it's a major issue because as a result terraform will recreate the dps whenever an apply command is run.
