### ISSUE TITLE
azurerm_function_app_slot: clone function_app settings 

### ISSUE THREAD

**Issue by MaxiPalle** [hashicorp/terraform-provider-azurerm#7466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With azurerm_function_app_slot a function app slot will be created.
What this resource does not offer, is to clone the settings of the function_app itself, like app_settigs etc. which is not congruent with the Azure portal functionality.

Would be helpful to have a switch (boolean) whether to clone the corresponding function_app.

### New or Affected Resource(s)

* azurerm_function_app_slot

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
}

resource "azurerm_function_app_slot" "example" {
  name                       = "test-azure-functions_slot"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  function_app_name          = azurerm_function_app.example.name
  clone_function_app_settings   = true
}
```

**Comment by aristosvo** [comment]
@MaxiPalle Do you want to clone the `app_settings` only on creation or every sync? It makes sense to by default clone the `app_settings` on setup by default unless specified.

To be honest, I think most users probably won't use this functionality, because `app_settings` can also be set on the resource itself. I'd prefer to have it explicit instead of copying it, what do you think?

**Comment by MaxiPalle** [comment]
@aristosvo Yes, absolutely. It would make sense to set those explicitely. If you need to just copy them, it would always be possible to do this with the TF code.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
