### ISSUE TITLE
Route Table routes should be Set instead of List

### ISSUE THREAD

**Issue by r0bnet** [hashicorp/terraform-provider-azurerm#7489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform -v
Terraform v0.12.26
+ provider.azurerm v2.12.0
```

### Affected Resource(s)

* `azurerm_route_table`

### Terraform Configuration Files

```hcl
resource "azurerm_route_table" "fw" {
  name                          = "fw-routetable"
  location                      = "northeurope"
  resource_group_name           = "myroutetablerg"

  route {
    name                   = "firewall"
    address_prefix         = "0.0.0.0/0"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = "10.0.0.1"
  }
}
```

Apply the example above. Add a route in the portal. Add the route in the code but switch order. Do `terraform plan`.

### Expected Behavior

Terraform output:
`No changes detected.`

### Actual Behavior

Terraform wants to change the routes (change order) because Azure returns them in order. So code and reality don't fit. Problem is that if you apply Azure won't change anything since it doesn't see any difference (in contrast to Terraform).

### Steps to Reproduce

See above.

**Comment by vzabawski** [comment]
I'm getting same behavior with azurerm 2.90.0 provider:

```
       ~ route                         = [
          - {
              - address_prefix         = "10.0.0.0/8"
              - name                   = "corporate"
              - next_hop_in_ip_address = "10.0.0.1"
              - next_hop_type          = "VirtualAppliance"
            },
            {
                address_prefix         = "0.0.0.0/0"
                name                   = "route_to_fw"
                next_hop_in_ip_address = "192.168.1.1"
                next_hop_type          = "VirtualAppliance"
            },
          + {
              + address_prefix         = "10.0.0.0/8"
              + name                   = "corporate"
              + next_hop_in_ip_address = "10.0.0.1"
              + next_hop_type          = "VirtualAppliance"
            },
```

Entry "corporate" is the same, but Terraform suggests replacing it.
