### ISSUE TITLE
Unsetting outbound_ip_address_ids in azurerm_kubernetes_cluster.loadbalancer_profile does not work

### ISSUE THREAD

**Issue by davelosert** [hashicorp/terraform-provider-azurerm#7615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.12.20
- provider.azuread v0.7.0
- provider.azurerm v2.17.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "aks_egress" {
	name                = "aks_egress"
	location            = "northeurope"
	resource_group_name = "build_aks"
	allocation_method   = "Static"
	sku                 = "Standard"
}

resource "azurerm_kubernetes_cluster" "aks" {
	name                = "build_cluster"
	location            = "northeurope"
	resource_group_name = "build_aks"
	node_resource_group = "build_aks_node"
	kubernetes_version  = "1.17.3"
	dns_prefix          = local.var.aks.dns_prefix


	default_node_pool {
		name               = "default"
		node_count         = 1
		vm_size            = "Standard_D1_v2"
		availability_zones = ["1", "2", "3"]
		vnet_subnet_id     = azurerm_subnet.aks.id
	}

	network_profile {
		network_plugin = "azure"
		network_policy = "azure"

		load_balancer_sku   = "Standard"
		load_balancer_profile {
			# was previously set to:
			# outbound_ip_address_ids = [azurerm_public_ip.aks_egress.id]
			outbound_ip_address_ids = []
		}
	}
        ...
}
```

### Debug Output

```
Error: updating Managed Kubernetes Cluster "build_cluster" (Resource Group "build_aks"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidLoadBalancerProfileOutboundIPs" Message="Load balancer profile outbound IPs is not a valid value(must contain at least one public IP resource ID)." Target="networkProfile.loadBalancerProfile.outboundIPs"
```

### Expected Behavior

I am trying to unlink a previously set egress-ip-address from the cluster.

I expected the `loadbalancer_profile` to return to it's "default" status (meaning: if there is no `load_balancer_profile` specified) - being an aks-managed outbound ip.

### Actual Behavior

Setting it to an empty array to remove the previously set public_ip as stated [in the docs](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#outbound_ip_address_ids) produces the error above.
So once set, there seems to be no way to return to the default.

### Steps to Reproduce

1. Create an AKS Cluster config with an explicitly set value for `outbound_ip_address_ids`
2. `terraform apply`
3. Set the `outbound_ip_address_id` to an empty value (`[]`)
 4. `terraform apply`

**Comment by dkirrane** [comment]
I've hit this same issue with `azurerm = 2.18.0`.  Same issue happens for `outbound_ip_prefix_ids`

I also tried to switch from `outbound_ip_address_ids` to `managed_outbound_ip_count`:

```
  load_balancer_profile = {
    managed_outbound_ip_count = 1
    outbound_ip_address_ids   = []
  }
```

`Error: "network_profile.0.load_balancer_profile.0.outbound_ip_address_ids": conflicts with network_profile.0.load_balancer_profile.0.managed_outbound_ip_count`

This should probably be https://github.com/terraform-providers/terraform-provider-azurerm/issues/5846 reopened?

**Comment by sivamca127** [comment]
Even i'm also struggling a lot with couple of issues with respect to UserDefinedRouting (Custom subnet and Routetable). 

Here is error info:

> Error: creating Managed Kubernetes Cluster "aks-tf" (Resource Group "aks-tf"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 --
> Original Error: Code="InvalidUserDefinedRoutingWithLoadBalancerProfile" Message="UserDefinedRouting and load balancer profile are mutually exclusive. Please refer to http://aka.ms/aks/outboundtype for more details" Target="networkProfile.loadBalancerProfile"

I've tried  with&without managed_outbound_Ip_count and outbound_address_ids=[] & [azurerm_public_ip.aks.id]

Here is my code snippet:
        	
                  network_profile {
		         network_plugin     = "kubenet"
		          network_policy     = "calico"
		         dns_service_ip     = "172.16.1.10"
		         service_cidr       = "172.16.0.0/16"
		         docker_bridge_cidr = "172.17.0.1/16"
		        pod_cidr           = "172.40.0.0/16"
		       outbound_type      = "userDefinedRouting"
	load_balancer_sku  = "Standard"

	load_balancer_profile {
		outbound_ip_address_ids = [ "${azurerm_public_ip.aks.id}" ]

	}
	# load_balancer_profile {
	#     managed_outbound_ip_count = 5
	#     #effective_outbound_ips    = [ azurerm_public_ip.aks.id ]
	#     outbound_ip_address_ids   = []
	#     outbound_ip_prefix_ids    = []
	#     outbound_ports_allocated  = 0
		
	# }
	}


I don't find much examples on UDR with detailed information. 

much appreciated for any help.

**Comment by sivamca127** [comment]
kindly some please look into this issue. as it is road blocker for me to move further

**Comment by rmorilha** [comment]
Same here:
terraform version: 0.14.6
azurerm provider version: 2.45.1

Terraform Plan Output:
```
Error: Incorrect attribute value type

  on Modules/Kubernetes/main.tf line 84, in resource "azurerm_kubernetes_cluster" "kubernetes":
  84:       managed_outbound_ip_count = []

Inappropriate value for attribute "managed_outbound_ip_count": number
required.
```

**Comment by akostic-kostile** [comment]
I'm trying to write configuration that would allow me to use 1 static IP and migrate it between different clusters. Considering that most of the changes in AKS configuration require recreating the cluster this seems like a sensible requirement.
It seems that this load_balancer_profile block has several major issues, or the issues are on Azure API side.

**Comment by akostic-kostile** [comment]
I did some tests with this `load_balancer_profile` block and I think I can shed some light on how things actually work.
When you provision AKS cluster an L4 LB gets provisioned automatically and one (AKS managed) IP gets created and attached to it, this IP lives in the same RG as nodes. From the Terraform standpoint omitting `load_balancer_profile` is the same as writing something like this:

```
load_balancer_profile {
  managed_outbound_ip_count = 1
}
```

The other two configuration options you can use are `outbound_ip_address_ids` and `outbound_ip_prefix_ids`. Key information here is that **these 3 options are mutually exclusive**, so if you wanted to switch from default (managed_outbound_ip_count = 1) to supplying your own, static IP you would have to do something like this:

```
load_balancer_profile {
  # managed_outbound_ip_count = 1
  outbound_ip_address_ids = [
    /subscriptions/$SUBSCRIPTION_ID/resourceGroups/example/providers/Microsoft.Network/publicIPAddresses/example-ip1
  ]
}
```

This will detach AKS managed IP and attach your static IP to the LB, leaving you with just one IP again. **There needs to be at least 1 IP attached to LB at all times**, which means that these parts of the documentation are complete nonsense:

```
User has to explicitly set managed_outbound_ip_count to empty slice ([]) to remove it.
User has to explicitly set outbound_ip_prefix_ids to empty slice ([]) to remove it.
User has to explicitly set outbound_ip_address_ids to empty slice ([]) to remove it.
```

The Azure API does not allow you to set any of these properties to an empty list, it's a bad request.

This static IP you've bound to the LB can live in any resource group, however if you try to make an Ingress controller use this IP (for it's service of LoadBalancer type) you'll get an error that says that this IP must be present in **nodes** RG. This makes 0 sense, a static IP must live in a resource group that gets created and destroyed together with the cluster?! What is the point of even provisioning a static IP if you're not going to reuse it between different clusters? Might as well use AKS managed IPs in that case.

Luckily there is a way to get over this, but requires some "creative" thinking. This is a very useful page:
https://docs.microsoft.com/en-us/azure/aks/static-ip#create-a-service-using-the-static-ip-address

It comes down to having to put an annotation on the k8s service of LoadBalancer type that points Ingress controller to where the IP is located:

`service.beta.kubernetes.io/azure-load-balancer-resource-group: example` 

My problem with this annotation is that it's incorrectly named, LB does not exist in the `example` RB, only the IPs are there, LB is actually provisioned in the **nodes** group.

Also you must attach a role that allows AKS identity to read and write in this RG, specifically `Network Contributor` role.

```
resource "azurerm_role_assignment" "aks-network-contributor-example-rg" {
  scope                = azurerm_resource_group.example.id
  role_definition_name = "Network Contributor"
  principal_id         = azurerm_kubernetes_cluster.aks.identity[0].principal_id
}
```

Hopefully this comment with help someone out, I've wasted way too much time trying to get this to work.
