### ISSUE TITLE
Prepare for HDInsight 3.6 end of life

### ISSUE THREAD

**Issue by kosinsky** [hashicorp/terraform-provider-azurerm#7670]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider includes 8 resources to support different HDInisght cluster configuration:
* azurerm_hdinsight_hadoop_cluster
* azurerm_hdinsight_kafka_cluster
* azurerm_hdinsight_hbase_cluster
* azurerm_hdinsight_spark_cluster
* azurerm_hdinsight_interactive_query_cluster
* azurerm_hdinsight_rserver_cluster
* azurerm_hdinsight_ml_services_cluster
* azurerm_hdinsight_storm_cluster
 
HDInsight has two active versions 4.0 and 3.6. 3.6 will be retired on December 30, 2020. https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-component-versioning#available-versions

HDInsight 4.0 doesn't support Storm (see component versions table https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-component-versioning#apache-components-available-with-different-hdinsight-versions) and ML Services (https://docs.microsoft.com/en-us/azure/hdinsight/r-server/r-server-overview#simple-secure-and-high-scale-operationalization-and-administration)

As a result following resources will stop work after December 30:
* azurerm_hdinsight_rserver_cluster
* azurerm_hdinsight_ml_services_cluster
* azurerm_hdinsight_storm_cluster

and all acceptance tests for other 5 will fail.

We should:
- [ ] Mark rserver, strom and ml_services are deprecated with message about Dec 30
- [ ] Update acceptance tests for hadoop|hbase|spark|kafka|interactive_query to use 4.0 and proper component versions

### References

* https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-component-versioning

**Comment by kosinsky** [comment]
@tombuildsstuff Does `v3.0.0` label mean that resources can be deleted in v3, but test updates and deprecation messages can be added in v2 or all changes should be part of v3?

**Comment by tombuildsstuff** [comment]
@kosinsky based on previous deprecations of this type in HDInsight, existing clusters should keep running - however provisioning new instances will fail from that date, so we'll (presumably) deprecate these resources in a 2.x release (as you've mentioned) and then remove them in 3.0, which is why I've put this in the 3.0 milestone (since this is where this'll ultimately be "fixed" by removing these resources which are becoming unsupported)

**Comment by kosinsky** [comment]
Got it. I'll work on 2.x parts
