### ISSUE TITLE
Support for azurerm_monitor_autoscale_setting "metric divide by instance count"

### ISSUE THREAD

**Issue by Dmitry1987** [hashicorp/terraform-provider-azurerm#7696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New feature exists in Azure but is not available in "azurerm_monitor_autoscale_setting" in Terraform. 
It is called "Enable metric divide by instance count", and allows to measure average CPU for example across all VMs in a scale-set, and scale based on the average of all pool of machines. Azure support confirmed that this is the only way to properly calculate percentage "average across many VMs", if not checked, the scaling policy won't work as expected.

![image](https://user-images.githubusercontent.com/9369080/87201337-36a5ee00-c2b3-11ea-82b7-43b3cb0b76b9.png)

### New or Affected Resource(s)

azurerm_monitor_autoscale_setting

**Comment by Dmitry1987** [comment]
Oops the mac screenshot resolution 😅

**Comment by magodo** [comment]
Hi @Dmitry1987 Thank you for submitting this :+1: 
Currently, the Azure API Spec doesn't define that property, hence I submit an issue for this: Azure/azure-rest-api-specs#10159. Once it's been addressed, we can go on implementing that in terraform.

**Comment by Dmitry1987** [comment]
thank you @magodo 👍

**Comment by andycoderapptio** [comment]
Is there any work around for this? It is set to true by default, if you un-check it after one deployment will setting remain unchecked?

**Comment by magodo** [comment]
@andycoderapptio This depends on the service behavior when it receives a request whose payload didn't specify that property.
