### ISSUE TITLE
Support for App Service Public Certificates

### ISSUE THREAD

**Issue by timlharrison** [hashicorp/terraform-provider-azurerm#7697]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I do not see any way to add a public certificate to an Azure App Service today.  I would like to request this feature to be added.  The Azure API reference is Microsoft.Web/sites/publicCertificates

### New or Affected Resource(s)

azurerm_app_service_public_certificate (?)
azurerm_app_service_public_certificate_binding (?)

### Potential Terraform Configuration

```hcl
resource "azurerm_app_service" "example" {
  name                = "app01"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id
}

resource "azurerm_app_service_public_certificate" "example" {
  name                = "example-root-cert"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  cer_blob            = filebase64("rootca.cer")
}

resource "azurerm_app_service_public_certificate_binding" "example" {
  app_service_name    = azurerm_app_service.example.name
  public_certificate_name = azurerm_app_service_public_certificate.example.name
  resource_group_name = azurerm_resource_group.example.name
}
```

### References

https://docs.microsoft.com/en-us/azure/app-service/configure-ssl-certificate#upload-a-public-certificate

**Comment by tombuildsstuff** [comment]
hey @timlharrison 

Thanks for opening this issue.

Taking a look through it appears this is available via [the `azurerm_app_service_certificate ` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service_certificate.html) by specifying the certificate contents using the `pfx_blob` parameter - would you be able to take a look and see if that works for you?

Thanks!

**Comment by timlharrison** [comment]
I believe that is used to upload an App Service server certificate & private key.  I'm looking to upload a custom, internal trusted root certificate.

**Comment by tombuildsstuff** [comment]
@timlharrison thanks for clarifying 👍

**Comment by dagus** [comment]
Please prioritize this feature if possible. It is very common that a client certificate is required and it is not great to have a arm template for this instead of a Terraform resrouce.

**Comment by TheRealWaldo** [comment]
To clarify what @timlharrison said a bit further, the `azurerm_app_service_certificate` resource actually fails if you try to pass a `pfx_blob` to it that only contains a public key with:

`Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="At least one certificate is not valid (Certificate does not contain a private key.)."`

There is currently no workaround except for ARM templates or hacky powershell that I am aware of.

NOTE: This is also apparently not supported in azure-cli: https://github.com/Azure/azure-cli/issues/12391

**Comment by hydros** [comment]
> To clarify what @timlharrison said a bit further, the `azurerm_app_service_certificate` resource actually fails if you try to pass a `pfx_blob` to it that only contains a public key with:
> 
> `Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="At least one certificate is not valid (Certificate does not contain a private key.)."`
> 
> There is currently no workaround except for ARM templates or hacky powershell that I am aware of.
> 
> NOTE: This is also apparently not supported in azure-cli: [Azure/azure-cli#12391](https://github.com/Azure/azure-cli/issues/12391)

Hi guys,

I want automatise this part too.

I see here : https://docs.microsoft.com/en-us/azure/templates/microsoft.web/2018-11-01/sites/publiccertificates this and with https://resources.azure.com/ we can see "publicCertificates".

When i checked this params it's important : 

```
"type": "Microsoft.Web/sites/publicCertificates",
  "properties": {
      "blob":""
      "publicCertificateLocation":"",
      "thumbprint":""
  }
```


I think it's not a huge effort to implement it on the Azure Provider.

**Comment by tombuildsstuff** [comment]
Looks like the SDK client for this is available in [`apps.go -> CreateOrUpdatePublicCertificate` (line ~3001)](https://raw.githubusercontent.com/Azure/azure-sdk-for-go/v49.2.0/services/web/mgmt/2020-06-01/web/apps.go)

**Comment by hydros** [comment]
> Looks like the SDK client for this is available in [`apps.go -> CreateOrUpdatePublicCertificate` (line ~3001)](https://raw.githubusercontent.com/Azure/azure-sdk-for-go/v49.2.0/services/web/mgmt/2020-06-01/web/apps.go)
> 
> Also looks like there's a separate version for Slot, so presumably there'd be two resources here, `azurerm_app_service_public_certificate` and `azurerm_app_service_slot_public_certificate`

Hello, I think you are right about the availability of the resource in the sdk client. (~ 3001) 

What next? Who can integrate this feature ? :)

Thank you! :)

**Comment by SecDWizar** [comment]
Is there any progress ?
