### ISSUE TITLE
Support for compound indexes in azurerm_cosmosdb_sql_container

### ISSUE THREAD

**Issue by bouff** [hashicorp/terraform-provider-azurerm#7723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for compound indexes was added to azurerm_cosmosdb_mongo_collection in [this enhancement](https://github.com/terraform-providers/terraform-provider-azurerm/issues/4460)

Can this be added for DocumentDb as well?

### New or Affected Resource(s)

* azurerm_cosmosdb_sql_container

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.


#8461
