### ISSUE TITLE
Terraform trying to update the old nsg rules, when trying to add new nsg rules 

### ISSUE THREAD

**Issue by Vignesh-Rao** [hashicorp/terraform-provider-azurerm#7803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

 terraform -v
Terraform v0.12.28
+ provider.azurerm v2.17.0

### Affected Resource(s)

* ```azurerm_network_security_group```

### Terraform Configuration Files

```
var file: var.auto.tfvars
nsg-to-rule-map = {
    "test-nsg1" = ["rule1"]
    "test-nsg2" = ["rule2","rule3"]
    "test-nsg3" = ["rule3"]
}

nsgs = {
  test-nsg1 = {
      loc = "westeurope"
      rg = "TestRG"
   }
   test-nsg3 = {
      loc = "eastus2"
      rg = "TestRG"
    }
    test-nsg2 = {
       loc = "centralindia"
       rg = "TestRG"
    }
}

rules = {
    rule1 = {
      priority                   = 2000
      direction                 = "Inbound"
      access                     = "Allow"
      protocol                   = "*"
      source_port_range          = "8080"
      source_port_ranges         = []
      destination_port_range     = "*"
      destination_port_ranges    = []
      source_address_prefix      = "VirtualNetwork"
      source_address_prefixes    = []
      destination_address_prefix = "*"
      destination_address_prefixes = []
    }
    rule2 = {
      priority                   = 1000
      direction                  = "Inbound"
      access                     = "Allow"
      protocol                   = "Tcp"
      source_port_range          = "*"
      source_port_ranges         = []
      destination_port_range     = "22"
      destination_port_ranges    = []
      source_address_prefix      = "0.0.0.0/0"
      source_address_prefixes    = []
      destination_address_prefix = "*"
      destination_address_prefixes = []
    }
    rule3 = {
      priority                                = 1001
      direction                              = "Inbound"
      access                                  = "Allow"
      protocol                              = "Tcp"
      source_port_range              = "*"
      source_port_ranges             = []
      destination_port_range       = "3389"
      destination_port_ranges      = []
      source_address_prefix          = "*"
      source_address_prefixes       = []
      destination_address_prefix   = "*"
      destination_address_prefixes = []
    }
}

main.tf:

resource "azurerm_network_security_group" "example" {
  for_each                      = var.nsgs
  name                           = each.key
  location                       = each.value.loc
  resource_group_name = each.value.rg


  dynamic "security_rule" {
    for_each                   = lookup(var.nsg-to-rule-map,each.key)
    content {
       name                       = "${security_rule.value}-${each.key}"
       priority                   = lookup(var.rules, security_rule.value)["priority"]
       direction                  = lookup(var.rules, security_rule.value)["direction"]
       access                     = lookup(var.rules, security_rule.value)["access"]
       protocol                   = lookup(var.rules, security_rule.value)["protocol"]
       source_port_range          = lookup(var.rules, security_rule.value)["source_port_range"]
       source_port_ranges         = lookup(var.rules, security_rule.value)["source_port_ranges"]
       destination_port_range     = lookup(var.rules, security_rule.value)["destination_port_range"]
       destination_port_ranges    = lookup(var.rules, security_rule.value)["destination_port_ranges"]
       source_address_prefix      = lookup(var.rules, security_rule.value)["source_address_prefix"]
       source_address_prefixes    = lookup(var.rules, security_rule.value)["source_address_prefixes"]
       destination_address_prefix      = lookup(var.rules, security_rule.value)["destination_address_prefix"]
       destination_address_prefixes    = lookup(var.rules, security_rule.value)["destination_address_prefixes"]
        }
    }
}
```

### Debug Output

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

   azurerm_network_security_group.nsgtest["test-nsg2"] will be updated in-place
  ~ resource "azurerm_network_security_group" "nsgtest" {
        id                  = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        location            = "centralindia"
        name                = "test-nsg2"
        resource_group_name = "TestRG"
      ~ security_rule       = [
          + {
              + access                                     = "Allow"
              + description                                = ""
              + destination_address_prefix                 = "*"
              + destination_address_prefixes               = []
              + destination_application_security_group_ids = []
              + destination_port_range                     = "*"
              + destination_port_ranges                    = []
              + direction                                  = "Inbound"
              + name                                       = "rule1-test-nsg2"
              + priority                                   = 2000
              + protocol                                   = "*"
              + source_address_prefix                      = "VirtualNetwork"
              + source_address_prefixes                    = []
              + source_application_security_group_ids      = []
              + source_port_range                          = "8080"
              + source_port_ranges                         = []
            },
          - {
              - access                                     = "Allow"
              - description                                = ""
              - destination_address_prefix                 = "*"
              - destination_address_prefixes               = []
              - destination_application_security_group_ids = []
              - destination_port_range                     = "22"
              - destination_port_ranges                    = []
              - direction                                  = "Inbound"
              - name                                       = "rule2-test-nsg2"
              - priority                                   = 1000
              - protocol                                   = "Tcp"
              - source_address_prefix                      = "0.0.0.0/0"
              - source_address_prefixes                    = []
              - source_application_security_group_ids      = []
              - source_port_range                          = "*"
              - source_port_ranges                         = []
            },
          - {
              - access                                     = "Allow"
              - description                                = ""
              - destination_address_prefix                 = "*"
              - destination_address_prefixes               = []
              - destination_application_security_group_ids = []
              - destination_port_range                     = "3389"
              - destination_port_ranges                    = []
              - direction                                  = "Inbound"
              - name                                       = "rule3-test-nsg2"
              - priority                                   = 1001
              - protocol                                   = "Tcp"
              - source_address_prefix                      = "*"
              - source_address_prefixes                    = []
              - source_application_security_group_ids      = []
              - source_port_range                          = "*"
              - source_port_ranges                         = []
            },
          + {
              + access                                     = "Allow"
              + description                                = null
              + destination_address_prefix                 = "*"
              + destination_address_prefixes               = []
              + destination_application_security_group_ids = []
              + destination_port_range                     = "22"
              + destination_port_ranges                    = []
              + direction                                  = "Inbound"
              + name                                       = "rule2-test-nsg2"
              + priority                                   = 1000
              + protocol                                   = "Tcp"
              + source_address_prefix                      = "0.0.0.0/0"
              + source_address_prefixes                    = []
              + source_application_security_group_ids      = []
              + source_port_range                          = "*"
              + source_port_ranges                         = []
            },
          + {
              + access                                     = "Allow"
              + description                                = null
              + destination_address_prefix                 = "*"
              + destination_address_prefixes               = []
              + destination_application_security_group_ids = []
              + destination_port_range                     = "3389"
              + destination_port_ranges                    = []
              + direction                                  = "Inbound"
              + name                                       = "rule3-test-nsg2"
              + priority                                   = 1001
              + protocol                                   = "Tcp"
              + source_address_prefix                      = "*"
              + source_address_prefixes                    = []
              + source_application_security_group_ids      = []
              + source_port_range                          = "*"
              + source_port_ranges                         = []
            },
        ]
        tags                = {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

### Panic Output

When   "test-nsg2" = ["rule2","rule3"] line in var.auto.tfvars file is changed to   "test-nsg2" = ["rule2","rule3","rule1"] and terraform plan is run it shows above logs
### Expected Behavior

It should add only rule1 to test-nsg2
### Actual Behavior

 The logs shows that its deleting & re-applying the existing rules as well 

### Steps to Reproduce
```
Change the   "test-nsg2" = ["rule2","rule3"]  to "test-nsg2" = ["rule2","rule3","rule1"] and run terraform plan & apply
```

**Comment by njuCZ** [comment]
@Vignesh-Rao thanks for pointing this issue, it seems it's an `terraform-plugin-sdk` issue casued by `ConfigMode: schema.SchemaConfigModeAttr`. there is no good way for now to fix it but only a workaround: use resource "azurerm_network_security_rule" with "count" or "for_each".

**Comment by magodo** [comment]
Hi @Vignesh-Rao Thank you for submitting this!

This issue is a terraform core issue appear for v1 plugin SDK (used by azurerm provider). There is a related issue in core: hashicorp/terraform#21901, which you might be interested to.

**Comment by magodo** [comment]
It just creates the new rule. This is an UX issue IMO.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
