### ISSUE TITLE
Error creating App Service (windows Container) with private docker hub

### ISSUE THREAD

**Issue by charlesdee** [hashicorp/terraform-provider-azurerm#7833]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.28
+ provider.azurerm v2.18.0
+ provider.null v2.1.2
### Affected Resource(s)

azurerm_app_service

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "test" {
  name                = azurerm_resource_group.test.name
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  app_service_plan_id = azurerm_app_service_plan.test.id


  app_settings = {
    DOCKER_REGISTRY_SERVER_URL      = "https://index.docker.io",
    DOCKER_REGISTRY_SERVER_USERNAME = var.dockeruser,
    DOCKER_REGISTRY_SERVER_PASSWORD = var.docker_pass
  }

    site_config {
    windows_fx_version = "DOCKER|${var.docker_image}"
  }
}
```

### Debug Output

Error: Error creating App Service "testresgrp" (Resource Group "testresgrp"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="The parameter WindowsFxVersion has an invalid value. Could not find the specified image name and tag combination. latest" Details=[{"Message":"The parameter WindowsFxVersion has an invalid value. Could not find the specified image name and tag combination. latest"},{"Code":"BadRequest"},{"ErrorEntity":{"Code":"BadRequest","ExtendedCode":"01007","Message":"The parameter WindowsFxVersion has an invalid value. Could not find the specified image name and tag combination. latest","MessageTemplate":"The parameter {0} has an invalid value.","Parameters":["WindowsFxVersion"]}}]

### Expected Behavior

Should have created an app service. 
works fine for the public repo images

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

NO

### References

* #0000

**Comment by pragadeeshraju** [comment]
similar issue, I'm using a private image from the docker hub. but it works if we use a public image.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
