### ISSUE TITLE
[azurerm_mssql_server] Cannot create a private endpoint on first run

### ISSUE THREAD

**Issue by mikemowgli** [hashicorp/terraform-provider-azurerm#7848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform version
Terraform v0.12.28
+ provider.azuread v0.11.0
+ provider.azurerm v2.18.0
+ provider.databricks v0.2.1
+ provider.random v2.3.0
```

### Affected Resource(s)

* `azurerm_mssql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_server" "tamers-synapse-server" {
  name                          = "example"
  resource_group_name           = "example"
  location                      = "westeurope"
  version                       = "12.0"
  administrator_login           = var.synapse_admin_user
  administrator_login_password  = var.synapse_admin_password
  public_network_access_enabled = false

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_subnet" "tamers-subnet-synapse" {
  name                    = var.synapse_subnet_name
  resource_group_name     = "example"
  virtual_network_name    = "example"
  address_prefixes        = [var.synapse_subnet_range]
  enforce_private_link_endpoint_network_policies = true
  enforce_private_link_service_network_policies  = true
}

resource "azurerm_private_endpoint" "tamers-synapse-private-endpoint" {
  name                    = "datatamers-synapse-pep"
  location                = "westeurope"
  resource_group_name     = "example"
  subnet_id               = azurerm_subnet.tamers-subnet-synapse.id

  private_service_connection {
    name                           = "tamers_synapse_psc"
    is_manual_connection           = false
    private_connection_resource_id = azurerm_mssql_server.tamers-synapse-server.id
    subresource_names              = ["sqlServer"]
  }
}
```

### Debug Output

```
Error: Error waiting on create/update future for SQL Server "datatamerssynapsep" (Resource Group "datatamersp"): Code="PECsNotExistingToDenyPublicNetworkAccess" Message="Unable to set Deny Public Network Access to Yes since there is no private endpoint enabled to access the server. Please set up private endpoints and retry the operation (https://docs.microsoft.com/azure/sql-database/sql-database-private-endpoint-overview#how-to-set-up-private-link-for-azure-sql-database)."

  on synapse.tf line 5, in resource "azurerm_mssql_server" "tamers-synapse-server":
   5: resource "azurerm_mssql_server" "tamers-synapse-server" {
```

### Behavior

A private endpoint is expected when creating the SQL server with `public_network_access_enabled = false`, but the `azurerm_private_endpoint`  resource depends on the server. There is a cyclic dependency between the server and the private endpoint.

### Workaround

* Creating the server first with `public_network_access_enabled = true`
* Creating the private endpoint
* turning off public access

But this is a lame workaround because
* it requires updating the code
* the server is publicly exposed for a limited time

What is the recommendation?

### Steps to Reproduce

1. `terraform apply`

**Comment by dawes206** [comment]
I am facing this same issue. Has a solution been figured out yet?

**Comment by vladdoster** [comment]
Isn't this due to conflicting attributes?

> Network policies, like network security groups (NSG), are not supported for Private Link Endpoints or Private Link Services. In order to deploy a Private Link Endpoint on a given subnet, you must set the enforce_private_link_endpoint_network_policies attribute to true. This setting is only applicable for the Private Link Endpoint, for all other resources in the subnet access is controlled based via the Network Security Group which can be configured using the azurerm_subnet_network_security_group_association resource.

**Comment by jvanenckevort** [comment]
Any workaround for this issue except the manual approach?

**Comment by brownz11** [comment]
It appears at some point Azure Fixed the underlying API and this now works on create (but not on subsequent attempts without a private endpoint)

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
