### ISSUE TITLE
TF rebuild of AKS cluster does not taint and rebuild helm_release

### ISSUE THREAD

**Issue by Marcus-James-Adams** [hashicorp/terraform-provider-azurerm#7900]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azuread v0.11.0
+ provider.azurerm v2.19.0
+ provider.cloudflare v2.8.0
+ provider.helm v1.2.4
+ provider.kubernetes v1.11.4
+ provider.random v2.3.0
+ provider.tls v2.1.1

### Affected Resource(s)

azurerm_kubernetes_cluster
helm_release

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

When an azurerm_kubernetes_cluster is recreated for any reason, additional tasks that have been run against it such as helm_release should be marked as tainted so that they are re-imported after the cluster is rebuilt

### Actual Behavior

the helm_releases think they are imported and do not reapply

* #0000

**Comment by jmcshane** [comment]
The helm release resource doesn't have an explicit dependency on your provider configuration. You can add an explicit depends on to the helm_release resource, something like:

```
resource "helm_release" "my_release" {
  ...

  depends_on = [azurerm_kubernetes_cluster.aks]
}
```

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
