### ISSUE TITLE
Failure during local vnet integration of app service

### ISSUE THREAD

**Issue by arshad2117** [hashicorp/terraform-provider-azurerm#7929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.28
provider.azurerm v2.20.0

### Affected Resource(s)

azurerm_subnet
azurerm_virtual_network
azurerm_app_service

### Terraform Configuration Files
```
provider "azurerm" {
  version = "=2.20.0"
  subscription_id = "INSERT_SUBSCRIPTION_ID"
  features {}
}

resource "azurerm_resource_group" "vnettest" {
  name     = "vnetTFTestGroup"
  location = "North Central US"
}

resource "azurerm_virtual_network" "vnettest" {
  name                = "virtualNetwork-1"
  location            = azurerm_resource_group.vnettest.location
  resource_group_name = azurerm_resource_group.vnettest.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_subnet" "vnettest" {
  name                 = "subnet-test-1"
  resource_group_name  = azurerm_resource_group.vnettest.name
  virtual_network_name = azurerm_virtual_network.vnettest.name
  address_prefix       = "10.0.1.0/24"
  service_endpoints    = ["Microsoft.AzureCosmosDB", "Microsoft.EventHub"]
}


resource "azurerm_app_service_plan" "vnettest" {
  name                = "vnet-test-app-service-plan"
  location            = azurerm_resource_group.vnettest.location
  resource_group_name = azurerm_resource_group.vnettest.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "vnettest" {
  name                = "vnet-test-app-service"
  location            = azurerm_resource_group.vnettest.location
  resource_group_name = azurerm_resource_group.vnettest.name
  app_service_plan_id = azurerm_app_service_plan.vnettest.id

}


resource "azurerm_app_service_virtual_network_swift_connection" "vnettest" {
  app_service_id = azurerm_app_service.vnettest.id
  subnet_id      = azurerm_subnet.vnettest.id
}

```

### Debug Output

Debug output gist - https://gist.github.com/arshad2117/35ed187046af6dfb062a4b8d3237f469

### Expected Behavior

Should have integrated vnet with the given app service

### Actual Behavior

Throws a 500 status code after trying to integrate for 5-10 mins

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by njuCZ** [comment]
@arshad2117 according to https://docs.microsoft.com/en-us/rest/API/appservice/webapps/createorupdateswiftvirtualnetworkconnection, when creating a azurerm_app_service_virtual_network_swift_connection, we need to make sure the target Subnet has already been delegated.
you could follow this example to create vnet integration app service: https://www.terraform.io/docs/providers/azurerm/r/app_service_virtual_network_swift_connection.html#example-usage

**Comment by arshad-motorq** [comment]
@njuCZ Thanks. Seems like subnet delegation was the issue

**Comment by njuCZ** [comment]
@arshad-motorq thanks for your quick try. Since you could create it successfully, I am going to close this issue.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
