### ISSUE TITLE
Supplied IpAddressOrRange is not publicly routable

### ISSUE THREAD

**Issue by fanaticit** [hashicorp/terraform-provider-azurerm#7946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.28
+ provider.azuread v0.11.0
+ provider.azurerm v2.20.0

### Affected Resource(s)

* `azurerm_cosmosdb_account`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  version = "=2.20"
}

resource "azurerm_cosmosdb_account" "account" {
  name                = format("%sserver-%s", local.prefix, random_id.suffix.hex)
  resource_group_name = azurerm_resource_group.cosmos-rg.name
  location            = azurerm_resource_group.cosmos-rg.location
  offer_type          = "Standard"
  consistency_policy {
    consistency_level = "Session"
  }
  geo_location {
    location          = azurerm_resource_group.cosmos-rg.location
    failover_priority = 0
  }
  ip_range_filter = "${data.terraform_remote_state.mgt-net.outputs.vpn_address_space},${data.terraform_remote_state.config.outputs.network.subnets.service_fabric}" 

  tags = merge(local.tags, local.cosmos_account_tags)

  # If you really, REALLY, need to delete the SQL Server Instance, uncomment this...
  lifecycle {
    prevent_destroy = true
  }
}
```

### Expected Behavior

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior

Error: Error updating CosmosDB Account "fan-inf-cosmos-server-079d" properties (Resource Group "fan-inf-cosmos-rg"): Error creating/updating CosmosDB Account "fan-inf-cosmos-server-079d" (Resource Group "om-inf-cosmos-rg"): documentdb.DatabaseAccountsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Supplied IpAddressOrRange is not publicly routable: '172.31.0.0/16'. Only publicly routable ranges are enforceable through IpRules. Please provide IPv4 addresses or ranges not contained in [10.0.0.0/8,100.64.0.0/10,172.16.0.0/12,192.168.0.0/16].\r\nActivityId: 44ff6a45-648f-4d20-909e-4dda8cfbc13b, Microsoft.Azure.Documents.Common/2.11.0"

### Steps to Reproduce

1. set provider version for azurerm to 2.20
2. try to apply new cosmos db account
3. `terraform apply`

### Important Factoids

'172.31.0.0/16' is one of our internal ranges and is in the ip_range_filter set ranges. This is the IP address it's complaining about.
Running this with azurerm provider version 2.19 or 2.18 works as normal.

### References

* #0000

**Comment by yupwei68** [comment]
Hi @Fanaticit , thanks for opening this issue. On fact, we have upgraded the service api version in release 2.20. I assume it's a reasonable error message since the ip range is reserved for their usage.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
