### ISSUE TITLE
Support for Azure Netapp Files Snapshot Policy

### ISSUE THREAD

**Issue by tbugfinder** [hashicorp/terraform-provider-azurerm#7965]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure & Netapp are rolling out new feature - Snapshot Policies (currently whitelisting required).
Those can be defined within an Netapp Account definition and assigned to volumes.

### New or Affected Resource(s)

* azurerm_netapp_account
* azurerm_netapp_volume

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
Dont' know exactly, tbd based on API.

**Comment by tbugfinder** [comment]
Rest API PR pending...
https://github.com/Azure/azure-rest-api-specs/pull/10425

**Comment by tbugfinder** [comment]
so the rest-api pre requisite was merged end of August :-)
https://github.com/Azure/azure-rest-api-specs/pull/10425

**Comment by tbugfinder** [comment]
specification/netapp/resource-manager/Microsoft.NetApp/stable/2020-06-01/examples/BackupPolicies_Create.json

**Comment by BartoszDopke** [comment]
Is anything done in this topic?

**Comment by BartoszDopke** [comment]
Workaround I found useful is to define NetApp Snapshot Policy using Azure Powershell and Azure CLI.
You can try like this:

```
resource "null_resource" "snapshot_policy" {
    provisioner "local-exec" {
        command = <<EOT
          $snapshotPolicy = Get-AzNetAppFilesSnapshotPolicy -ResourceGroupName "${var.resource_group_name}" -AccountName "${var.netapp_account_name}" -Name "${local.snapshot_policy_name}" -ErrorAction SilentlyContinue
          
          if($snapshotPolicy -eq $null) {
            Write-Host "${local.snapshot_policy_name} will be created!"
            az netappfiles snapshot policy create -g "${var.resource_group_name}" --account-name "${var.netapp_account_name}" --snapshot-policy-name "${local.snapshot_policy_name}" -l "${var.environment.location.name}" --enabled true ${local.snapshot_policy_type}
          }
           else  {
            Write-Host "${local.snapshot_policy_name}-01 will be updated!"
            az netappfiles snapshot policy update -g "${var.resource_group_name}" --account-name "${var.netapp_account_name}" --snapshot-policy-name "${local.snapshot_policy_name}" -l "${var.environment.location.name}" --enabled true ${local.snapshot_policy_type}
          }

          if ("${var.snapshot_policy_type}" -eq "null") {
            if($snapshotPolicy -eq $null) {
            Write-Host "${local.snapshot_policy_name} does not exist!"
          }
           else  {
            Write-Host "${local.snapshot_policy_name} will be deleted!"
            az netappfiles snapshot policy delete -g "${var.resource_group_name}" --account-name "${var.netapp_account_name}" --snapshot-policy-name "${local.snapshot_policy_name}"
          }
        }
        EOT
        interpreter = ["pwsh", "-Command"]
    }
}
```

**Comment by paulomarquesc** [comment]
Hi @BartoszDopke and @tbugfinder, this will start to be addressed in the coming weeks.

**Comment by schlbra** [comment]
Any updates on this feature?

**Comment by schlbra** [comment]
Snapshot policy is now officially a GA feature as of this month. Hopefully we can get this terraform added soon so folks can start backing up their production data. :)
