### ISSUE TITLE
"azurerm_app_service_plan" dose not allow to create service plan ElasticPremium|EP1|1

### ISSUE THREAD

**Issue by sgabenov** [hashicorp/terraform-provider-azurerm#7973]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "app_service_plan" {
    name = "${var.prefix}-plan-${var.environment}"
    location = var.location
    resource_group_name = var.resource_group_name
    kind = "elastic"
    reserved = true

    sku {
        tier = "ElasticPremium"
        size = "EP1"
        capacity = 1
    }
}
```

### Expected Behavior

Service plan ElasticPremium|EP1|1 should be created. This plan is able to create through Azure WebUI to host linux/python function app with premium plan and show such configuration if import resource to TF

### Actual Behavior

Terraform shows error `'reserved' has to be set to true when kind is set to 'Linux'`. Does not allow to create such plan.

### Steps to Reproduce

1. `terraform apply` with code block above

### Important Factoids
I believe this should be an Azure API bug or limitation as well as you can not select such plan in api
```
az appservice plan create --name
                          --resource-group
                          [--app-service-environment]
                          [--hyper-v]
                          [--is-linux]
                          [--location]
                          [--no-wait]
                          [--number-of-workers]
                          [--per-site-scaling]
                          [--sku {B1, B2, B3, D1, F1, FREE, I1, I2, I3, P1V2, P2V2, P3V2, PC2, PC3, PC4, S1, S2, S3, SHARED}]
                          [--subscription]
                          [--tags]
```

**Comment by njuCZ** [comment]
@sgabenov in latest azurerm version 2.21, we have fixed this bug. And I have tested it in my local, this is no such problem now, Could you have a try again?

**Comment by LaurentLesle** [comment]
yes I confirm it is now working. I am using 2.23

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
