### ISSUE TITLE
`azurerm_kubernetes_cluster` addon Profile OMSConfig refresh plan is not empty

### ISSUE THREAD

**Issue by yupwei68** [hashicorp/terraform-provider-azurerm#7984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
0.12.26
 provider.azurerm v2.21.0

### Affected Resource(s)
azurerm_kubernetes_cluster

* `azurerm_XXXXX`

### Terraform Configuration Files

https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/containers/tests/kubernetes_cluster_addons_resource_test.go#L156

### Expected Behavior

refresh plan is not empty

### Actual Behavior
~ addon_profile {

          - kube_dashboard {
              - enabled = true -> null
            }

            oms_agent {
                enabled                    = true
                log_analytics_workspace_id = "/subscriptions/.../resourcegroups/ask-resource-group-yup/providers/microsoft.operationalinsights/workspaces/preyup-workspace"
                oms_agent_identity         = []
            }
        }

### Steps to Reproduce

1. Terraform apply
2. Terraform plan

### References

* #0000

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
