### ISSUE TITLE
Default for allowExtensionOperations set wrong

### ISSUE THREAD

**Issue by NilsBusche** [hashicorp/terraform-provider-azurerm#7986]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.28
terraform-provider-azurerm_v2.21.0_x5

### Affected Resource(s)

* `azurerm_linux_virtual_machine`
* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "instance" {
  name                  = var.hostname
  location              = data.azurerm_resource_group.rg_vm.location
  resource_group_name   = data.azurerm_resource_group.rg_vm.name
  network_interface_ids = [azurerm_network_interface.nic_0.id]
  size                  = var.flavor
  availability_set_id   = var.availabilityset
  computer_name         = var.hostname
  admin_username        = var.os_username

  source_image_reference {
    publisher = var.image_publisher
    offer     = var.image_offer
    sku       = var.image_sku
    version   = var.image_version
  }

  os_disk {
    name                 = "${var.hostname}_volume_0"
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
  }

  admin_ssh_key {
    public_key = file(var.ssh_key_path)
    username   = var.os_username
  }

  boot_diagnostics {
    storage_account_uri = var.storage_uri
  }
}
```

### Expected Behavior

We are importing a VM using Terraform import functionality. This VM has following set in its properties:

`    "allowExtensionOperations": null,`

This we looked up using command `az vm show`

The Terraform import now should import the attribute `allowExtensionOperations` into Terraform's state with value `null` or with the default value `true`.

### Actual Behavior

If you look into the statefile after importing the value of `allowExtensionOperations` is set to `false`, which is wrong. Now Terraform wants to change the attribute (which forced a recreation in provider versions before).

### Steps to Reproduce

Import VM into Terraform.

1. Take a VM which has set `    "allowExtensionOperations": null,`
2. `terraform import`

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
