### ISSUE TITLE
azurerm_postgresql_server doesn't apply auto_grow_enabled change 

### ISSUE THREAD

**Issue by michal-stasiak-gft** [hashicorp/terraform-provider-azurerm#8084]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform: 0.12.24
* azurerm: 2.22.0

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

Former configuration:
```hcl
resource "azurerm_postgresql_server" "this" {
  name                         = local.solution_name_prefix
  location                     = data.azurerm_resource_group.solution.location
  resource_group_name          = data.azurerm_resource_group.solution.name
  sku_name                     = var.db_sku_name
  version                      = "10"
  ssl_enforcement_enabled      = true
  storage_mb                   = var.db_storage_mb
  backup_retention_days        = var.db_backup_retention_days
  geo_redundant_backup_enabled = var.db_geo_redundant_backup_enabled
  auto_grow_enabled            = true

  ...
}
```
Change in configuration to be applied:

`  auto_grow_enabled            = true` ->   `auto_grow_enabled            = false`

### Debug Output

https://gist.github.com/michal-stasiak-gft/2da3d861aa739bbd43e2b219509639fd#file-azurerm_postgresql_server__auto_grow_enabled__apply-log

### Expected Behavior

The PostgreSQL server was created with `auto_grow_enabled` set to `true`. I'd like to disable the feature.
On `terraform plan` the planned change of property is shown. 

### Actual Behavior
`terraform apply` indicates a change to be applied:
```
  # module.main.azurerm_postgresql_server.this will be updated in-place
  ~ resource "azurerm_postgresql_server" "this" {
      ~ auto_grow_enabled                 = true -> false
 ...
```
The change is not applied (as is seen on Azure Portal).
Each subsequent terraform plan or terraform apply shows the same change to be applied. 
Each `terraform apply` ends with misleading success: `Apply complete! Resources: 0 added, 1 changed, 0 destroyed.`

### Steps to Reproduce
1. Create PostgreSQL DB using `azurerm_postgresql_server` with `auto_grow_enabled = true`.
2. Change the property to `false` and run `terraform apply`.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
