### ISSUE TITLE
Support for init container in azurerm_container_group 

### ISSUE THREAD

**Issue by johnksv** [hashicorp/terraform-provider-azurerm#8085]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The provider should support init containers in Container Instances, as available through the CLI and as described here:

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-init-container

### New or Affected Resource(s)

* azurerm_container_group

### Potential Terraform Configuration

```hcl
resource "azurerm_container_group" "group" {
  …
  init_container {
    cpu = 0
    image = ""
    memory = 0
    name = ""
  }
  …
}
```

### References

* https://docs.microsoft.com/en-us/azure/container-instances/container-instances-init-container

**Comment by allantargino** [comment]
Hi @ArcturusZhang,
Did you start working on this feature? If not I am happy to help.

**Comment by allantargino** [comment]
Inspecting the current interface, I suppose we will have some problems with Volumes when introducing Init Containers, giving that both Containers and Init Container should have the ability to share volumes.

That's the current `[*].container.volume`:

```
volume {
    name = ""

    mount_path = ""
    read_only = false

    share_name = ""
    storage_account_name = ""
    storage_account_key = ""

    empty_dir = false

    secret = {
        "a" : "b"
    }

    git_repo {
        url = ""
        directory = ""
        revision = ""
    }
}
```
It merges both concepts of `Volume Mounts` and `Volumes` into one abstraction.

I would propose deprecating `[*].container.volume`, in favor of both `[*].container.volume_mount` and `[*].volumes`.

This is a proposal for `[*].container.volume_mount`:
```hcl
volume_mount {
    volume_name = ""
    mount_path = ""
    read_only = false
}
```

Where `volume_name` must reference a `volume.name`.

This is a proposal for `[*].volume`:
```hcl
volume {
    name = ""

    file_share {
        share_name = ""
        storage_account_name = ""
        storage_account_key = ""
    }

    empty_dir = false

    secret = {
        "a" : "b"
    }

    git_repo {
        url = ""
        directory = ""
        revision = ""
    }
}
```

> I am also proposing grouping all file share properties under the new `file_share` property.

After these changes, we shouldn't have problems introducing volumes to Init Container using the same abstractions.

Thoughts?
cc/ @ArcturusZhang

**Comment by ArcturusZhang** [comment]
Hey @allantargino appreciate if you could start - I only have a very simple start and then occupied by something else. 
The design is very reasonable, thanks for the contribution!

**Comment by bdhar1** [comment]
Hi @ArcturusZhang / @allantargino , 

Any update on this issue? This can really help with the ACI usage.

Thanks in advance.

**Comment by allantargino** [comment]
Hi @bdhar1, I end up not implementing on this feature.

**Comment by hterik** [comment]
Sharing volumes between containers is now supported using emptyDir, since https://github.com/hashicorp/terraform-provider-azurerm/pull/13374 
When adding initContainers i believe it should be possible to use same mechanism.
Sharing other type of volume mounts makes less sense, so new mode of defining volumes shouldn't block this feature.

**Comment by lonegunmanb** [comment]
Hello @johnksv and everyone, the `init_container` has been introduced into the container group resource from v3.2.0. Would you please close this issue? Many thanks!
