### ISSUE TITLE
azurerm_data_factory_linked_service_azure_blob_storage connection string is stored differently

### ISSUE THREAD

**Issue by MrSimonEmms** [hashicorp/terraform-provider-azurerm#8099]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_data_factory_linked_service_azure_blob_storage`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "data-factory" {
  location = var.LOCATION
  name = "rg"
}

resource "azurerm_data_factory" "ingester" {
  name = "data-factory"
  location = azurerm_resource_group.data-factory.location
  resource_group_name = azurerm_resource_group.data-factory.name
}

resource "azurerm_data_factory_linked_service_azure_blob_storage" "ingester" {
  name = "blob-storage"
  resource_group_name = azurerm_resource_group.data-factory.name
  data_factory_name = azurerm_data_factory.ingester.name
  connection_string = azurerm_storage_account.ingestion.primary_connection_string
}
```

### Expected Behavior

Create a linked service and store the `typeProperties` in the format (`<value>` represents the value, which has not been added as sensitive).

```json
{
  "connectionString": "<value>",
  "encryptedCredential": "<value>"
}
```

### Actual Behavior

It set the `connectionString` as a secure string. This means that although the connections work for anything created by Terraform, if a developer wishes to add something into Azure manually (I know, but it's what we have to do) then it's not able to get the data.

```json
{
  "connectionString": {
    "type": "SecureString",
    "value": "**********"
  },
   "encryptedCredential": "<value>"
}

For example, when creating a Wrangling Data Flow, we get the error:

```
DataFormat.Error: The supplied URL must be a valid 'http:' or 'https:' URL.Detailshttps://**********.blob.core.windows.net/raw/filename.csv
```

When I manually edit the linked data set in Azure (which changes the underlying JSON), it works fine. Specifically, note how the URL is `*****` - I suspect this is because the SecureString isn't able to be decrypted by Azure

```
**NB** There is also a documentation error in the [docs](https://www.terraform.io/docs/providers/azurerm/r/data_factory_linked_service_azure_blob_storage.html#connection_string) - the connection string param makes references to 
`account_endpoint`, `account_key` and `database`, which appear to have been copied and pasted from the CosmoDB page. If this is correct, these need further elucidation.

### Steps to Reproduce

1. `terraform apply`
2. Go to data factory
3. Go to author and monitor
4. Go to manage
5. Go to `blob-storage` linked service
6. View the JSON

### References

* #0000

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
