### ISSUE TITLE
Add Attributes InternalIpAddress, outboundIpAddresses, serviceIpAddress to an app_service_environment

### ISSUE THREAD

**Issue by LaurentLesle** [hashicorp/terraform-provider-azurerm#8179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

App service environment only return the id and location attributes. This feature request is to add

- InternalIpAddress
- outboundIpAddresses
- serviceIpAddress 

This is required when deploying an isolated ASE with ILB.

https://github.com/Azure/azure-rest-api-specs/blob/master/specification/web/resource-manager/Microsoft.Web/stable/2020-06-01/AppServiceEnvironments.json - from line 1814

Current workaround. Get those properties through the az resources:
```hcl
data "external" "ase_ilb_ip" {
  program = ["bash", "-c", "az resource show --ids ${lookup(azurerm_template_deployment.ase.outputs, "id")}/capacities/virtualip --query '{internalIpAddress: properties.internalIpAddress}' | jq -c"]

  depends_on = [azurerm_template_deployment.ase]
}
```

### New or Affected Resource(s)

* azurerm_app_service_environment

**Comment by CaptainStealthy** [comment]
@katbyte The PR linked to this issue was merged and released with 2.62, it looks like? I just tested the `internal_ip_address` attribute, and it works on 2.63.

**Comment by adamyager** [comment]
> @katbyte The PR linked to this issue was merged and released with 2.62, it looks like? I just tested the `internal_ip_address` attribute, and it works on 2.63.

I am also confused on this one. Is it duplicate? Is something new delivered here?

**Comment by bduzik** [comment]
My PR should have closed this issue. It returns information on creation per the issue request.

**Comment by adamyager** [comment]
> My PR should have closed this issue. It returns information on creation per the issue request.
I think we need this for app service enviroment v3. but I dont know if that is what this Issue is for

**Comment by adamyager** [comment]
@katbyte I think if we move this to the App service enviroment V3 resource, it is certanly neeed, we can keep it open.
I believe the work is exactly the same just for ASE v3

**Comment by haraldatbmw** [comment]
ASEv3 is now GA - see https://azure.microsoft.com/en-us/updates/app-service-environment-v3-now-generally-available/

Maybe its a better approach to update the resource `azurerm_app_service_environment` to be able to create ASEv2 and ASEv3 instead of having two different resources.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
