### ISSUE TITLE
Support for azurerm_data_factory_integration_runtime_managed AAD authentication

### ISSUE THREAD

**Issue by jonathaneckman** [hashicorp/terraform-provider-azurerm#8305]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using a `catalog_info` block with `azurerm_data_factory_integration_runtime_managed`, the `administrator_login` and `administrator_password` are required. To configure IR AAD authentication with an ARM template, you simply configure a managed identity on the data factory and do not send and admin username and password with the IR deployment. 

### New or Affected Resource(s)

* azurerm_data_factory_integration_runtime_managed

### Potential Terraform Configuration

```hcl
resource "azurerm_data_factory_integration_runtime_managed" "example" {
  name                = "example"
  data_factory_name   = azurerm_data_factory.example.name
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  node_size = "Standard_D8_v3"
  
  catalog_info {
    server_endpoint = 'connectionString...'
    pricing_tier = "Standard"
  }
}
```

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

#10649
