### ISSUE TITLE
How to inline yaml for the "content_value" field of azurerm_api_management_api

### ISSUE THREAD

**Issue by tezzigator** [hashicorp/terraform-provider-azurerm#8306]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
0.13 & 2.24

### Affected Resource(s)
azurerm_api_management_api

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_api" "get" {
  name                = "apimpetstoreget"
  resource_group_name = data.azurerm_resource_group.rg.name
  api_management_name = azurerm_api_management.apim.name
  revision            = "1"
  display_name        = "'PetstoreGet"
  path                = "apimpetstore"
  protocols           = ["https"]

  import {
    content_format = "openapi"
    content_value  = <<-EOT
    openapi: 3.0.1
    info:
      title: Get Store
      version: '1.0'
    servers:
      - url: 'http://${azurerm_container_group.container.ip_address}:8080/v2'
    paths:
      /store/inventory:
        get:
          summary: Retrieve resource
          description: >-
            A demonstration of a GET call on a sample resource. It is handled by an
          responses:
            '200':
              description: Returned in all cases.
    components:
      securitySchemes:
        apiKeyHeader:
          type: apiKey
          name: Ocp-Apim-Subscription-Key
          in: header
        apiKeyQuery:
          type: apiKey
          name: subscription-key
          in: query
    security:
      - apiKeyHeader: []
      - apiKeyQuery: []
    EOT
  }
}
```
The apply completes fine, and for the most part my config is deployed, except 1 field- the interpolation of `      - url: 'http://${azurerm_container_group.container.ip_address}:8080/v2'` as the "HTTP(s) endpoint" never makes it into the API portal.   When terraform spits out its plan, it interpolated correctly, to "- url: 'http://10.0.2.4:8080/v2'" but that just never gets set to the HTTP(s) endpoint.  If I then manually go to the portal to put it in, then it just starts working though.

**Comment by yupwei68** [comment]
hi @tezzigator 

Thanks for opening this issue. This seems a question for hcl. Would you like to find the answer in https://github.com/hashicorp/hcl/issues?

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the Community Resources. I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html). 

Thanks!

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
