### ISSUE TITLE
azurerm_postgres_server: ssl_minimal_tls_version_enforced cannot be updated 

### ISSUE THREAD

**Issue by romain-zert** [hashicorp/terraform-provider-azurerm#8314]
Not sure how to re open the following issue so writing a new one :
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7228

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.24

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files

```hcl
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
```

### Expected Behavior

I can update from TLS1_1 to TLS1_2 configuration 

### Actual Behavior

Update is ignored, event if properly detected by terraform plan.
No error is displayed in the terraform apply neither the terraform state is updated

### Steps to Reproduce

Try to update the TLS configuration for an **already **deployed postgres** server

### Important Factoids

* #0000

**Comment by yupwei68** [comment]
Hi @lakichemole , thanks for opening this issue. Would you mind checking your Azurerm version again? There is an [acctest](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/mysql/tests/mysql_server_resource_test.go#L201) for updating `ssl_minimal_tls_version_enforced` from `TLS1_1` to `TLS1_2`, which I have tested it with success currently. The PR to fix this issue has been released in v2.19.0. If there are still problems, please provide a more specific terraform configuration for `azurerm_mysql_server` and reproducing steps if it's convenient?

**Comment by lakichemole** [comment]
Hi @yupwei68 here the configuration script 
### PaaS Azure PostGreSQL Server
resource "azurerm_postgresql_server" "assie_paas_postgresql_server" {
  count                            = 1
  name                             = "azpsypsql58"
  location                         = "westeurope"
  resource_group_name              = "rzt-test"
  sku_name                         = "B_Gen5_2"
  storage_mb                       = 5120
  backup_retention_days            = 7
  geo_redundant_backup_enabled     = false
  administrator_login              = "postgresadmin"
  administrator_login_password     = "SecretPassword10928*)]@"
  version                          = "9.5"
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"
}

If I change TLS1_2 to TLS_1 --> nothing happen on Azure side even if every thing is ok on terraform side

here my terraform version info

Terraform v0.12.28
+ provider.azurerm v2.25.0

**Comment by yupwei68** [comment]
Hi @lakichemole Would you mind updating the title to be `azurerm_postgresql_server` instead of `azurerm_mysql_server`

**Comment by lakichemole** [comment]
Hi @yupwei68  thank yo for sharing the PR, I'm not aware about release flow, any ETA for the PR to be integrated?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
