### ISSUE TITLE
Hosting_mode to High Density in Cognitive Search

### ISSUE THREAD

**Issue by kartikcr** [hashicorp/terraform-provider-azurerm#8332]
#7878 # Terraform (and AzureRM Provider) Version
Terraform: v0.13.0
Azure rm version 1.41.0

### Affected Resource(s)

1. azurerm_search_service

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_search_service" "acc" {
name = "${var.cognsearch_account_name}"
resource_group_name = "${azurerm_resource_group.rg.name}"
location = "${azurerm_resource_group.rg.location}"
sku = "standard3"
hosting_mode = "highDensity"
}
```

### Debug Output

An argument named "hosting_mode" is not expected here.

### Expected Behavior

Hosting_mode should be defined for standard3 azurerm.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by blueelvis** [comment]
@mybayern1974 @ArcturusZhang @favoretti - This is already fixed and working in the latest release. Could you please close this?

**Comment by favoretti** [comment]
Yes sir. Thank you.
