### ISSUE TITLE
Support for Tags in Data Source of azurerm_app_service

### ISSUE THREAD

**Issue by Abhishekqwerty** [hashicorp/terraform-provider-azurerm#8414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, we can only specify the Azure App Service name and Resource Group name in **Data Source: azurerm_app_service**.
It would be great if we get the list for App Services in the Resource Group based on tags.
This feature would help in getting a list of App Services and adding App Services as the backend in FrontDoor or the API Management.

### New or Affected Resource(s)

* data "azurerm_app_service"

### Potential Terraform Configuration

```hcl
data "azurerm_app_service" "example" {
  resource_group_name = "search-service"
  tags = { Type = backend }

output "app_service" {
  value = ["${data.azurerm_app_service.example.*.default_site_hostname}"]
  }
}
```

**Comment by Abhishekqwerty** [comment]
Any luck with this feature?

**Comment by Kavinraja-G** [comment]
I would like to work on this issue.

**Comment by tombuildsstuff** [comment]
This is available in [the `azurerm_linux_app_service`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/linux_web_app#tags) and [`azurerm_windows_app_service`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/windows_web_app#tags) Data Sources
