### ISSUE TITLE
kubernetes_cluster is forcing resetAADProfile on any AKS configuration change

### ISSUE THREAD

**Issue by djsly** [hashicorp/terraform-provider-azurerm#8433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

the azureADDResetProfile logic is always triggered on AKS resource update, we did both SKU change from Free to Paid and it triggered the resetADDProfile Logic and now we did the 1.15.12 to 1.16.13 version upgrade and it started with the resetADDProfile

<img width="400" alt="Screen Shot 2020-09-10 at 11 30 44 PM" src="https://user-images.githubusercontent.com/4981802/92853701-1f23d800-f3be-11ea-9b09-ff9c3c30b606.png">

This causes majors issues since the resetAAD profile will force an update of all the kubernetes_agent_pool resources. forcing them to be upgraded before the control plane is updated 

### Expected Behavior

Only update the AKS resource with the default node pool , don't touch the resetADDProfile if it's not change. 
tf plan output shows no change to the profile block

### Actual Behavior
it's messing up all the agent_pool by forcing them to upgrade 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by djsly** [comment]
@katbyte  / @tombuildsstuff  this is breaking any Kubernetes updates,  on big cluster it's very obvious. 

we looked at it and the DIFF doesn't show anything that would trigger the resetAAD 

This statement is already different 
https://github.com/terraform-providers/terraform-provider-azurerm/blob/479c070970dcbb79721c81d889a309502f26b92e/azurerm/internal/services/containers/kubernetes_cluster_resource.go#L879

I'm not sure what is causing it since we are not getting the DIFF printed in the logs. 
our assumption is that we have a null != [] or something along those lines. 

Caused by an API version bump on the container client maybe ? or Azure decided to return default Values compared to nothing before ?

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
