### ISSUE TITLE
Optionally prevent deletion of predefined application settings on App Services

### ISSUE THREAD

**Issue by KSiig** [hashicorp/terraform-provider-azurerm#8435]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

One of the big problems I have when using this provider to deploy Web Apps or Function Apps, is that I forget about something like `WEBSITE_RUN_PACKAGE` or other predefined variables.

My suggestion is to add an argument called `keep_predefined_settings` which can then either be `true` or `false`. If it is set to true, then do not delete the settings that are set by Azure.

The problem with something like this, is that the list of variables that Azure uses has to be manually maintained in an array in the code. At least that's the only solution I can come up with. I would love suggestions on how this can be better implemented. I hoped there was a REST endpoint somewhere to get all the variables, but I can't find such thing.

### New or Affected Resource(s)

* azurerm_app_service
* azurerm_function_app

### Potential Terraform Configuration

```hcl
resource "azurerm_function_app" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
  keep_predefined_settings = true
}
```

**Comment by ljluestc** [comment]
```

resource "azurerm_function_app" "example" {
  name                       = "test-azure-functions"
  location                   = azurerm_resource_group.example.location
  resource_group_name        = azurerm_resource_group.example.name
  app_service_plan_id        = azurerm_app_service_plan.example.id
  storage_account_name       = azurerm_storage_account.example.name
  storage_account_access_key = azurerm_storage_account.example.primary_access_key
}

# Define the settings you want to keep and set them explicitly
resource "azurerm_function_app_config" "example" {
  name                = azurerm_function_app.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  app_settings = {
    "MY_CUSTOM_SETTING" = "my_custom_value"
    "ANOTHER_SETTING"   = "another_value"
    # Add more custom settings as needed
  }
}

# You can use count or conditional expressions to manage settings conditionally
resource "azurerm_function_app_config" "example_predefined" {
  count               = var.keep_predefined_settings ? 1 : 0
  name                = azurerm_function_app.example.name
  app_service_plan_id = azurerm_app_service_plan.example.id

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = "https://example.com/package.zip"
    # Add other predefined settings as needed
  }
}
```

**Comment by rcskosir** [comment]
Thanks for opening this issue. The azurerm_app_service resource is deprecated, feature frozen and will be removed in a future version of the provider - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead. The azurerm_function_app resource is deprecated, feature frozen and will be removed in a future version of the provider - so I'd suggest moving to the azurerm_linux_function_app and azurerm_windows_function_app resources instead. Since these are feature frozen, I am going to close this issue.
