### ISSUE TITLE
Azure Firewall Network Rule - Support for service tags

### ISSUE THREAD

**Issue by roshanp85** [hashicorp/terraform-provider-azurerm#8439]
Hi Team,

Do we have support for terraform, to implement the service tags in Azure firewall: azurerm_firewall_network_rule_collection.

We see them in our portal, but in the documentation we are not able to see anything that will implement the service tags, with source addresses. Please advise thanks.

**Comment by capdragon** [comment]
100%, We need to be able to add something like:
```
    rule {
      name                  = "gw-az-infa"
      protocols             = ["TCP"]
      source_addresses      = ["GatewayManager"] 
      destination_addresses = ["*"] 
      destination_ports     = ["65200-65535"]
    }
```

**Comment by masonhuemmer** [comment]
Agreed, we need support to set service tags at the "source_addresses" parameter.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here it appears that support for `source_addresses` is [available in the `azurerm_firewall_network_rule_collection` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/firewall_network_rule_collection#source_addresses) and as such I'm going to close this issue for the moment.

Thanks!
