### ISSUE TITLE
Terraform not allowing max_age_in_seconds to be 0 for existing azure storage account imported

### ISSUE THREAD

**Issue by SunnyOswal** [hashicorp/terraform-provider-azurerm#8446]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM Provider: 2.23.0
Terraform: 0.13.2

### Affected Resource(s)
* `azurerm_storage_account`

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "st" {
  name                     = "abc"
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  min_tls_version          = "TLS1_0"
  account_kind             = "Storage"
  account_tier             = "Standard"
  account_replication_type = "LRS"

  blob_properties {
          cors_rule {
                allowed_headers    = [
                    "*",
                ]
                allowed_methods    = [
                    "PUT",
                    "OPTIONS",
                ]
                allowed_origins    = [
                    "xyz",
                ]
                exposed_headers    = [
                    "*",
                ]
              max_age_in_seconds = 0
            }
        }
        network_rules {
          bypass                     = [
              "AzureServices",
          ]
          default_action             = "Allow"
        }
    timeouts {}
}
```
### Expected Behavior

No Error.

### Actual Behavior

```
expected blob_properties.0.cors_rule.0.max_age_in_seconds to be in the range (1 - 2000000000)
```

### Steps to Reproduce
Azure storage Account with CORS config as :
![image](https://user-images.githubusercontent.com/19683199/93013525-e2352c80-f5db-11ea-9e01-a2d4ce752c1b.png)

1. Import existing azure storage account to terraform.
2. Use above terraform config with max_age_in_seconds (which is mandatory in cors_rule block)
3. `terraform plan`

**Comment by atrauzzi** [comment]
Experiencing this issue as well.
