### ISSUE TITLE
Support for WCF Relays and Authorization rules for it

### ISSUE THREAD

**Issue by dbychkouski** [hashicorp/terraform-provider-azurerm#8463]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would like to have opportunity to add WCF Relay and Shared Access policy for it into Azure Relay Namespace. Thank you in advance

### New or Affected Resource(s)

New:
azurerm_wcf_relay
azurerm_relay_namespace_authorization_rule

### Potential Terraform Configuration

     resource "azurerm_resource_group" "example" {
        name     = "example-resources"
        location = "West Europe"
     }

     resource "azurerm_relay_namespace" "example" {
        name                = "example-relay-namespace"
        location            = azurerm_resource_group.example.location
        resource_group_name = azurerm_resource_group.example.name

        sku_name = "Standard"

        tags = {
      source = "terraform"
        }
     }

     resource "azurerm_wcf_relay" "example" {
        name                  = "example-wcf-relay"
        resource_group_name   = azurerm_resource_group.example.name
        azure_relay_namespace_name = azurerm_relay_namespace.name
        relay_type = "http"
        requires_client_authorization = true
     }
 
     resource "azurerm_wcf_relay_authorization_rule" "example" {
        name                = "example-wcf-rule"
        wcf_relay_name      = azurerm_wcf_relay.example.name
        resource_group_name = azurerm_resource_group.example.name

        listen = true
        send   = true
        manage = false
     }

### References

* #0000

**Comment by rcskosir** [comment]
@dbychkouski Thank you for taking the time to open this issue and apologies for the delay. I stumbled on this issue and I see that there is a duplicate feature request with a little more interaction on it. We like to try to keep discussions consolidated, so we’re going to close this issue in favor of #8776.
