### ISSUE TITLE
azurerm_function_app doesn't start deployed function

### ISSUE THREAD

**Issue by pmelkowski** [hashicorp/terraform-provider-azurerm#8546]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

https://raw.githubusercontent.com/logicmonitor/lm-logs-azure/master/deploy.tf

### Debug Output

No errors in the log.

### Expected Behavior

The Azure Function is deployed and running.

### Actual Behavior

The Azure Function is deployed but not running.

### Steps to Reproduce

1. `terraform apply --var 'lm_company_name=company' --var 'lm_access_id=access_id' --var 'lm_access_key=access_key' --var 'azure_region=northcentralus'` (or any other region)
2. `az webapp log tail --name lm-logs-company-northcentralus --resource-group lm-logs-company-northcentralus-group` - only SSH service is started:
```
/appsvctmp/volatile/logs/runtime/040c652a6ce16a5c9a01cc1f5378e45ce5f695dbf4471de9bfebfd52410c2ff9.log
2020-09-21T08:48:37.437939799Z: [INFO]  Starting OpenBSD Secure Shell server: sshd.
2020-09-21T08:48:54.159125242Z: [INFO]  Hosting environment: Production
2020-09-21T08:48:54.160116148Z: [INFO]  Content root path: /
2020-09-21T08:48:54.161348855Z: [INFO]  Now listening on: http://[::]:80
2020-09-21T08:48:54.171694615Z: [INFO]  Application started. Press Ctrl+C to shut down.
```
3. Go to Azure Portal, and restart the Function App - the function starts.

### Important Factoids

* The script uses GitHub as the package source (`WEBSITE_RUN_FROM_PACKAGE  = "https://github.com/logicmonitor/lm-logs-azure/raw/master/package/lm-logs-azure.zip"`) but using Azure Blob Storage doesn't help, in the both cases the package is properly installed.
* Using `az functionapp restart` or `az functionapp stop` and `az functionapp start` usually doesn't help (~99% cases), doesn't matter when done - tried it a few hours after the deployment as well.
* Restarting from the portal always helps.

**Comment by adamrushuk** [comment]
I've got exactly the same issue. Are there any workarounds yet?

**Comment by adamrushuk** [comment]
Here's my Function App config: https://github.com/adamrushuk/aks-nexus-velero/blob/develop/terraform/function_app.tf

**Comment by adamrushuk** [comment]
Thanks for marking previous comments as off-topic. I'll raise a separate issue.
