### ISSUE TITLE
azurerm_kubernetes_cluster fails to update if a node pool is being reprovisioned

### ISSUE THREAD

**Issue by janlunddk** [hashicorp/terraform-provider-azurerm#8565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version: 0.12.26
AzureRM Provider version: 2.28.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files
Not much to show here. The config files from #8562 cause this issue along with a change of `orchestrator_version` on both the cluster and the pools.

The basic issue is that when a cluster Kubernetes version update is requested (in this case from 1.15.12 to 1.16.13), **and** a node pool is reprovisioned (#8562), there seems to be either a timing issue or maybe more likely a plan dependency issue.

The node pool is correctly deleted, but the AKS upgrade fails due to the fact that it does not wait for the deletion and re-provisioning of the node pool to finalize. (Ref. the error message `Message="Cannot update AAD profile because agent pool mypool is under provisioning state Deleting."` (Full apply-log is shown below in _Actual Behavior_)

A workaround is to run `terraform plan` and `terraform apply` again.

### Expected Behavior

The cluster should have reprovisioned the node pool and updated all pools to the new Kubernetes version.

### Actual Behavior

```
azurerm_kubernetes_cluster_node_pool.mypool[0]: Destroying... [id=/subscriptions/...---/resourcegroups/myrg/providers/Microsoft.ContainerService/managedClusters/mycluster/agentPools/mypool]
azurerm_kubernetes_cluster.akscluster: Modifying... [id=/subscriptions/...-.../resourcegroups/myrg/providers/Microsoft.ContainerService/managedClusters/mycluster]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 10s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 20s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 30s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 40s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 50s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 1m0s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 1m10s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 1m20s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 1m30s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 1m40s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 1m50s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Still destroying... [id=/subscriptions/...-...mycluster/agentPools/mypool, 2m0s elapsed]
azurerm_kubernetes_cluster_node_pool.mypool[0]: Destruction complete after 2m2s

Error: updating Managed Kubernetes Cluster AAD Profile in cluster "mycluster" (Resource Group "myrg"): containerservice.ManagedClustersClient#ResetAADProfile: Failure sending request: StatusCode=400 -- Original Error: Code="AadProfileUpdateError" Message="Cannot update AAD profile because agent pool mypool is under provisioning state Deleting."

  on platform.aks.tf line 25, in resource "azurerm_kubernetes_cluster" "akscluster":
  25: resource "azurerm_kubernetes_cluster" "akscluster" {

```
### Steps to Reproduce

1. Make a change that will require a node pool reprovisioning (e.g. a node size change or the unwanted taint re-creation #8562)
2. Change the `orchestrator_version` to a new version for all pools (including the cluster default pool).
3. `terraform plan`
4. `terraform apply`

### References

* #8562

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems I cannot repro it with below tfconfig. Could you have a try below tfconfig to check whether the issue still exists?
1. Create resources:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-aks-test01"
  location = "eastus2"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestakstest01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestakstest01"
  kubernetes_version  = "1.16.13"

  default_node_pool {
    name                 = "default"
    node_count           = 1
    vm_size              = "Standard_DS2_v2"
	orchestrator_version = "1.16.13"
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "aksnodepool1"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count             = 1
  max_count             = 2
  node_count            = 1
  orchestrator_version  = "1.16.13"
}
```

2. Update resource:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-aks-test01"
  location = "eastus2"
}

resource "azurerm_kubernetes_cluster" "test" {
  name                = "acctestakstest01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name
  dns_prefix          = "acctestakstest01"
  kubernetes_version  = "1.17.9"

  default_node_pool {
    name                 = "default"
    node_count           = 1
    vm_size              = "Standard_DS2_v2"
	orchestrator_version = "1.16.13"
  }

  identity {
    type = "SystemAssigned"
  }
}

resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "aksnodepool1"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count             = 1
  max_count             = 2
  node_count            = 1
  orchestrator_version  = "1.17.9"
}
```

**Comment by janlunddk** [comment]
@neil-yechenwei, thanks for your fast response.

The scenario you created above will work perfectly fine.
But if you change your update resource for the pool look like this, adding a taint (or alternatively change vm_size to another VM series) :

```
resource "azurerm_kubernetes_cluster_node_pool" "test" {
  name                  = "aksnodepool1"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.test.id
  vm_size               = "Standard_DS2_v2"
  enable_auto_scaling   = true
  min_count             = 1
  max_count             = 2
  node_count            = 1
  orchestrator_version  = "1.17.9"
  node_taints                = ["mytaint=true:NoSchedule"]    <-- Add this to the update
}
```
So now you have updated both the orchestrator version and added a taint.
This will cause a reprovisioning of the `test` node pool, and the update for the `default` pool will fail.

**Comment by neil-yechenwei** [comment]
Thanks for your information. Seems I can repro it now. After checked, seems there is conflicting issue while updating azurerm_kubernetes_cluster and destroying azurerm_kubernetes_cluster_node_pool at the same time. I assume it's hard to resolve this issue from terraform. So suggest to update azurerm_kubernetes_cluster first, then recreate azurerm_kubernetes_cluster_node_pool as workaround.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
