### ISSUE TITLE
azurerm_app_service keeps displaying site_credential block

### ISSUE THREAD

**Issue by audunsolemdal** [hashicorp/terraform-provider-azurerm#8567]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0

### Affected Resource(s)

* `azurerm_app_service`

### Expected Behavior

No site_credential output during terraform plan

Not sure how to interpretate this
![image](https://user-images.githubusercontent.com/21334768/93869007-88afba80-fccb-11ea-90ae-9b116d9eff9a.png)

### Actual Behavior

site_credential output is shown during `terraform plan`

### Steps to Reproduce

Deploy with Azure devops to app service.

Even set "scm_type" to "None" gives the same result

### References

* #0000

**Comment by mrparkers** [comment]
Most likely related to https://github.com/hashicorp/terraform-plugin-sdk/issues/201

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
