### ISSUE TITLE
Cannot prevent passing subscription key to API Management by "query" 

### ISSUE THREAD

**Issue by prabhakarreddy1234** [hashicorp/terraform-provider-azurerm#8693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Azure API Management allows us to pass subscription-key by query and/or header. But Terraform is forcing us to enable both query and header options. Passing subscription-key by query is considered insecure. So it would be useful if one option is made required.

### Terraform (and AzureRM Provider) Version 
Terraform : 0.12.29
AzureRM: 2.29.0 (all versions)

### Affected Resource(s)

* `subscription_key_parameter_names`
* `azurerm_api_management`

### Terraform Configuration Files
```
resource "azurerm_api_management_api" "abc-public-search-api" {
  name                = "abc-public-search-api-${var.environment_name}"
  resource_group_name = "${var.resource_prefix}-${local.environment_common}-${var.environment_geography}-network-persistent"
  api_management_name = data.azurerm_api_management.platform.name
  revision            = replace(var.release_name, ".", "")
  display_name        = "Search abc Api - ${local.environment_long_name}"
  description         = "Contains all of the endpoints to make aggregated data queries on base."
  path                = "${var.environment_name}/api/abc/v1/search"
  protocols           = [var.protocol]
  service_url         = "${var.api_backend_url}/api/abc/v1/search"

  subscription_key_parameter_names {
    header = "Subscription-Key"
    ###query  = "Subscription-Key"   commented out
  }

  import {
    content_format = "openapi-link"
    content_value  = var.abc_public_search_api_link
  }
}
```
### Expected Behavior

It shouldn't error. It shouldn't allow passing subscription-key by query.

### Actual Behavior

The argument "query" is required, but no definition was found.

### References

https://www.terraform.io/docs/providers/azurerm/r/api_management_api.html#subscription_key_parameter_names

**Comment by nexxai** [comment]
@prabhakarreddy1234 If I'm reading the documentation of this resource right, the `query` parameter is not the actual key itself but the name of the query string parameter (the `name` portion of `scheme://hostname.tld/path/endpoint?name=value`) and so there isn't (or at least, shouldn't be) any sensitive information being passed there.

If you don't think this is the case, can you show evidence?

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
