### ISSUE TITLE
azurerm_app_service_plan creates Xenon plan when is_xenon = false

### ISSUE THREAD

**Issue by larsmars** [hashicorp/terraform-provider-azurerm#8694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.3
provider registry.terraform.io/hashicorp/azurerm v2.29.0

### Affected Resource(s)
azurerm_app_service_plan

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "eo-plan" {
  name                                   = local.plan_name
  resource_group_name        = azurerm_resource_group.eo-rg.name
  location                               = azurerm_resource_group.eo-rg.location
  kind                                     = "Windows"
  is_xenon                              = false

  sku {
    tier = "Standard"
    size = "S1"
  }

  tags = {
    App_name                    = var.app_name
    App_short_name          = var.app_short_name
    Env                               = terraform.workspace
  }
}
```

### Expected Behavior

Non xenon Windows **App service plan** created

### Actual Behavior
![image](https://user-images.githubusercontent.com/5154589/94675123-87107300-0319-11eb-9925-fe5554f0648a.png)

No errors, all fine in console. (Apply complete!)

App service **Xenon plan** is created 
![image](https://user-images.githubusercontent.com/5154589/94674671-d5714200-0318-11eb-9508-8ca6b9d43cd6.png)

### Steps to Reproduce
`terraform apply`

**Comment by mleziva** [comment]
I think _kind_ needs to be set to "App" instead of "Windows", but this is still not documented anywhere and not expected

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
