### ISSUE TITLE
target_network_id not applying on initial run of azurerm_site_recovery_replicated_vm resource

### ISSUE THREAD

**Issue by cr0schma** [hashicorp/terraform-provider-azurerm#8696]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.29.0

### Affected Resource(s)

azurerm_site_recovery_replicated_vm

### Terraform Configuration Files

```hcl
resource "azurerm_site_recovery_replicated_vm" "web_vm_replication" {
  #TODO:
  count                                     = var.number_of_web
  name                                      = data.azurerm_virtual_machine.Web[count.index].name
  resource_group_name                       = azurerm_resource_group.rgDR.name
  recovery_vault_name                       = azurerm_recovery_services_vault.rsvDR.name
  source_recovery_fabric_name               = azurerm_site_recovery_fabric.fabric.name
  #source_vm_id                              = azurerm_virtual_machine.vm.id
  source_vm_id                              = data.azurerm_virtual_machine.Web[count.index].id
  recovery_replication_policy_id            = azurerm_site_recovery_replication_policy.policy.id
  source_recovery_protection_container_name = azurerm_site_recovery_protection_container.protection_container.name
  target_network_id                         = azurerm_virtual_network.vnetDR.id

  target_resource_group_id                = azurerm_resource_group.rgDR.id
  target_recovery_fabric_id               = azurerm_site_recovery_fabric.fabricDR.id
  target_recovery_protection_container_id = azurerm_site_recovery_protection_container.protection_containerDR.id
  target_availability_set_id              = azurerm_availability_set.webDR.id

  managed_disk {
    #disk_id                    = azurerm_virtual_machine.vm.storage_os_disk[0].managed_disk_id
    disk_id                    = data.azurerm_managed_disk.Web[count.index].id
    staging_storage_account_id = data.azurerm_storage_account.primary.id
    target_resource_group_id   = azurerm_resource_group.rgDR.id
    target_disk_type           = "Standard_LRS"
    target_replica_disk_type   = "Standard_LRS"
  }
}
```

### Expected Behavior

![image](https://user-images.githubusercontent.com/72145440/94696423-06477c00-0305-11eb-9444-8028f7be7ebc.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/72145440/94696976-a3a2b000-0305-11eb-86c6-b308f36b88ca.png)

### Steps to Reproduce

1. `terraform apply`
2. If target_network_id is added to the code after you have already created the azurerm_site_recovery_replicated_vm resource it will connect the target network

**Comment by cr0schma** [comment]
FYI: The target network does apply on the initial run if you add the network_interface block with the required argument of source_network_interface_id

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
