### ISSUE TITLE
Support for shared disks

### ISSUE THREAD

**Issue by zumic96** [hashicorp/terraform-provider-azurerm#8708]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft announced GA of shared disks on it's Premium tier for all regions. Previously it was available only for Ultra disks which weren't available in many regions so this feature didn't make much sense.
Now that changed and with this new feature creation of SQL server Failover Cluster Instances is much easier than before.

### New or Affected Resource(s)

* azurerm_managed_disk

### Potential Terraform Configuration

```hcl
resource "azurerm_managed_disk" "example" {
  name                 = "acctestmd"
  location             = "West US 2"
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Premium_LRS"
  create_option        = "Empty"
  disk_size_gb         = "1"

  shared               = true

  tags = {
    environment = "staging"
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "example" {
  managed_disk_id    = azurerm_managed_disk.example.id
  virtual_machine_id = azurerm_virtual_machine.example[0].id
  lun                = "10"
  caching            = "ReadOnly"
}

resource "azurerm_virtual_machine_data_disk_attachment" "example" {
  managed_disk_id    = azurerm_managed_disk.example.id
  virtual_machine_id = azurerm_virtual_machine.example[1].id
  lun                = "10"
  caching            = "ReadOnly"
}
```

### References

* https://azure.microsoft.com/en-us/updates/shared-disks-on-azure-disk-storage-is-now-available-in-broader-set-of-regions/

**Comment by Lachlan-White** [comment]
@tombuildsstuff @jackofallops I see that the PR was closed due to preview status of the featured.

I believe this is now in GA, would there be a way to review the change to see if it's now valid?

**Comment by svenschiller** [comment]
We are interested in using the shared disk, as well. Please reopen #8790 now that this is GA.

**Comment by kahoffman** [comment]
Is there any progress on this feature? This has been GA for a while.

**Comment by KiranChilledOut** [comment]
still waiting

**Comment by PylsaPylsa** [comment]
Is this really the kind of support we can expect when new features go to GA? Almost a year and still no progress?

**Comment by fabricesemti80** [comment]
Good Morning,

I would need similar in my environment too...I suppose it is still not possible?
Is there an ETA please?

Thanks,
F.

**Comment by steve727** [comment]
Following to see when we could expect this feature to be available, we have a similar need for our Production environments as well. Thanks, Steve

**Comment by RobertFloor** [comment]
We would need this feature to

**Comment by tombuildsstuff** [comment]
Support for this is available [via the `max_shares` property within the `azurerm_managed_disk` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#max_shares).
