### ISSUE TITLE
Support for using latest azure-sdk-for-go library for timeseriesinsights

### ISSUE THREAD

**Issue by akirakakar** [hashicorp/terraform-provider-azurerm#8726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, iottimeseriesinsights is using preview version of sdk(github.com/Azure/azure-sdk-for-go/services/preview/timeseriesinsights/mgmt/2018-08-15-preview/timeseriesinsights). We want to start using the lastest sdk(github.com/Azure/azure-sdk-for-go/tree/master/services/timeseriesinsights/mgmt/2020-05-15/timeseriesinsights)

### New or Affected Resource(s)

* azurerm_iot_time_series_insights_standard_environment
* azurerm_iot_time_series_insights_access_policy
* azurerm_iot_time_series_insights_reference_data_set

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

#9b01074387689b1a009640499f8f9788ee5d045c
