### ISSUE TITLE
docs: ARM_METADATA_HOST should be ARM_METADATA_HOSTNAME

### ISSUE THREAD

**Issue by ngtuna** [hashicorp/terraform-provider-azurerm#8728]
I encountered this issue with:

Authentication method: MSI (tried with Service Principal with no luck as well)
terraform version: 0.13.3
azurerm version: >= 2.28.0

**Comment by tombuildsstuff** [comment]
hi @ngtuna 

Thanks for opening this issue.

Unfortunately there's not enough information in this for us to be able to debug this - but it appears that the provider field `metadata_host` (sourced from `ARM_METADATA_HOST`) is being set to an empty string, rather than being omitted which would cause this; would you be able to confirm if that environment variable/provider field is being set?

Thanks!

**Comment by ngtuna** [comment]
Hi I tried to set it to `ARM_METADATA_HOST=169.254.169.254` but no luck again.

Here is my providers.tf 

```terraform {
  required_version = ">= 0.13"

  backend "azurerm" {}

  required_providers {
    azuread = {
      version = ">= 1.0.0"
      source  = "hashicorp/azuread"
    }

    azurerm = {
      version = ">= 2.28.0"
      source  = "hashicorp/azurerm"
    }
  }
}
```

**Comment by tombuildsstuff** [comment]
@ngtuna in this instance the `ARM_METADATA_HOST` field needs to be unset, not an empty string - it's not necessary for Azure Public (only some other regions)

**Comment by ngtuna** [comment]
oh btw, some more info. Those envvar are set:

ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_ENVIRONMENT=usgovernment 
ARM_TENANT_ID
ARM_SUBSCRIPTION_ID

Which ARM_METADATA_HOST should I set to ?

**Comment by ngtuna** [comment]
Ah you meant unset it. I just did it. Remove TF cache. Still same error :(

**Comment by vsabella** [comment]
We also ahve been seeing this - with Terraform 0.13 and latest AzureRM provider (2.24 and above) on US Gov environment

**Comment by vsabella** [comment]
@tombuildsstuff  and @ngtuna  this is doc bug - the code says:

ARM_METADATA_HOSTNAME
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.30.0/azurerm/internal/provider/provider.go

but the docs say ARM_METADATA_HOST
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.30.0/website/docs/index.html.markdown

and the tests use ARM_METADATA_HOST
https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.30.0/azurerm/internal/acceptance/data.go

**Comment by vsabella** [comment]
You can find the APIs here:
https://github.com/Azure/azure-cli/blob/azure-cli-2.12.1/src/azure-cli-core/azure/cli/core/cloud.py

**Comment by tombuildsstuff** [comment]
@vsabella this field does not need to be configured in Azure Public or US Government - so it can omitted.

However ultimately this is a documentation bug where `ARM_METADATA_HOST` should be `ARM_METADATA_HOSTNAME` in the documentation
