### ISSUE TITLE
API Management Service Data Source does not expose identity data

### ISSUE THREAD

**Issue by sjentzsch** [hashicorp/terraform-provider-azurerm#8736]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$terraform -v
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
+ provider registry.terraform.io/hashicorp/azurerm v2.30.0
```

### Affected Resource(s)

* `azurerm_api_management`

### Expected Behavior

I expect the datasource for the `azurerm_api_management` to contain information on the `identity`, as specified here:

* https://www.terraform.io/docs/providers/azurerm/d/api_management.html
* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/apimanagement/api_management_data_source.go#L63

### Actual Behavior

The block `identity` is not contained, verified via `terraform state show` on the datasource, and also I get the error:

```
Error: Unsupported attribute

  on main.tf line 123, in resource "azurerm_key_vault_access_policy" "test":
 298:   tenant_id = data.azurerm_api_management.test.identity.tenant_id

This value does not have any attributes.
```

**Comment by TheMacStack** [comment]
Shouldn't this be labeled as a `Bug` rather than `Enhancement`? The documentation clearly states the `Identity` data should be returned when using Data Source: azurerm_api_management but it is not.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

#10429
