### ISSUE TITLE
New Data Source: `azurerm_eventhub_cluster`

### ISSUE THREAD

**Issue by blame19** [hashicorp/terraform-provider-azurerm#8742]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful to have a data source for eventhub_clusters, in order to retrieve their id at runtime.

### New or Affected Resource(s)

* data azurerm_azurerm_eventhub_cluster

### Potential Terraform Configuration

Ideally it could be useful to have something like this:
```hcl

`data "azurerm_eventhub_cluster" "example" {
  cluster_name               = "search-eventhub-cluster-name"
  resource_group_name = "search-service"
}

output "eventhub_cluster_id" {
  value = data.azurerm_eventhub_cluster.example.id
}`

```

### References

//

**Comment by stephybun** [comment]
Hello @blame19, thank you for this request. 

This was fixed by #11763 which was released in `v2.60.0`.
