### ISSUE TITLE
azurerm_template_deployment error parsing JSON using file function

### ISSUE THREAD

**Issue by PhilBroderick** [hashicorp/terraform-provider-azurerm#8775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.13.4
* provider.azurerm v2.30.0

### Affected Resource(s)

* `azurerm_template_deployment`

### Terraform Configuration Files

Inline ARM
```hcl
resource "azurerm_template_deployment" "functionkey" {
  deployment_mode = "Incremental"
  name = "functionkeys01"
  resource_group_name = azurerm_resource_group.rg.name
  
  template_body = <<DEPLOY
  {
    "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
      "contentVersion": "1.0.0.0",
      "parameters": {
        "functionApp": {
          "type": "string"
        }
      },
      "variables": {
        "functionAppId": "[resourceId('Microsoft.Web/sites', parameters('functionApp'))]"
      },
      "resources": [],
      "outputs": {
        "functionKey": {
          "type": "string",
          "value": "[listkeys(concat(variables('functionAppId'), '/host/default'), '2018-11-01').functionKeys.default]"
        }
      }
  }
  DEPLOY
  
  parameters = {
    "functionApp" = azurerm_function_app.functionapp.name
  }
  
  depends_on = [ azurerm_function_app.functionapp ]
}
```

Using file function
```hcl
resource "azurerm_template_deployment" "functionkey" {
  deployment_mode = "Incremental"
  name = "functionkeys01"
  resource_group_name = azurerm_resource_group.rg.name
  
  template_body = file("../arm/list-function-key.json")
  
  parameters = {
    "functionApp" = azurerm_function_app.functionapp.name
  }
  
  depends_on = [ azurerm_function_app.functionapp ]
}
```

### Expected Behavior

Expected TF to parse the JSON correctly using the file function.

### Actual Behavior

Received the following error when using the file function:
![image](https://user-images.githubusercontent.com/33251762/95320033-c77b6e00-0890-11eb-9c15-64b67de64305.png)

It works when using the inline ARM template, but not when reading from file.

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### Important Factoids

Ran the ARM file using the Azure CLI to ensure it was valid, which it was. Running `terraform apply` with the inline ARM script produces the expected output.

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
