### ISSUE TITLE
Support for Infrastructure Encryption on azurerm_storage_account

### ISSUE THREAD

**Issue by chrisp787** [hashicorp/terraform-provider-azurerm#8816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RequireInfrastructureEncryption option for azurerm_storage_account resource creation. We have enabled this feature on several of our Azure subscriptions https://docs.microsoft.com/en-us/azure/storage/common/infrastructure-encryption-enable?tabs=powershell#register-to-use-infrastructure-encryption. However when provisioning new storage accounts using Terraform there does not appear to be an argument for this, and it can not be enabled following storage account creation. Please could this be added as an argument to this resource? 

### New or Affected Resource(s)

azurerm_storage_account. 

* azurerm_v2.31.1

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by yupwei68** [comment]
Support for Infrastructure Encryption on `azurerm_storage_account_customer_managed_key`

**Comment by chrisp787** [comment]
Thanks for the reply @yupwei68 however i think that this resource is for customer management for their own keys for encryption at rest (Service level) https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption#about-encryption-key-management

However wheat we are after is the following.

We have enabled the feature on our subscription (the option only becomes available once it has been enabled ) and can only be then enabled on storage accounts during creation.

https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption#doubly-encrypt-data-with-infrastructure-encryption

**Comment by saurabh2004** [comment]
Any news around this topic please? Was a workaround or a fixed solution found? 
Terraform website does not have reference to this 

Support for Infrastructure Encryption on azurerm_storage_account #8816

**Comment by trooper5232** [comment]
> Any news around this topic please? Was a workaround or a fixed solution found?
> Terraform website does not have reference to this
> 
> Support for Infrastructure Encryption on azurerm_storage_account #8816

This comment was marked off topic however it is very much on topic. Azure added infrastructure encryption in September of 2020 [link.](https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption#doubly-encrypt-data-with-infrastructure-encryption)

**Comment by chrisp787** [comment]
Hi @trooper5232 No unfortunately we did not manage to implement a solution using Terraform.

**Comment by tarique-s** [comment]
Any ETA on when this feature will be added? It's one of the security configuration for storage account required at my client organization and we are not able to use Terraform configuration to create storage account because of this.

**Comment by DevKiranOps** [comment]
I have almost convinced my Architect to move away from ARM templates to Terraform. And here we are! No option to chhose Infrastructure encryption. I am sure this feature is quite important for many Azure users.

**Comment by AliMBajwa** [comment]
I'm aware it's possible to achieve this via azurerm_storage_encryption_scope - but this is a preview feature and it not yet supported by storage accounts which have hierarchical namespace enabled.

Therefore there isn't a reliable way to create storage accounts (with data lakes) than can be double encrypted via Terraform?

If I'm misinformed please do correct me.

**Comment by chrisp787** [comment]
> I'm aware it's possible to achieve this via azurerm_storage_encryption_scope - but this is a preview feature and it not yet supported by storage accounts which have hierarchical namespace enabled.
> 
> Therefore there isn't a reliable way to create storage accounts (with data lakes) than can be double encrypted via Terraform?
> 
> If I'm misinformed please do correct me.

Yes currently it does not seem possible to enable double encrytion with terraform. However i would believe that this could be implemented as it is possible to enable it when using other tools such as ARM templets, Powershell and Azure CLI. It would be good if the argument was added to azurerm_storage_account resource.

**Comment by AliMBajwa** [comment]
Suggestion as a temp workaround for anyone who needs a workaround right now: terraform import a CLI created storage account. I have an azure pipelines yaml template to do this for me - while not ideal, does work.

**Comment by Kumar1325** [comment]
+1

Hi @terraform Team,

I've the same requirement, and it was blocked by the policy that each storage account should be enabled the `infrastructure encryption`. While I'm deploying with terraform, I was getting the validation error that I can't create a Storage account without infrastructure encryption.

do you have any plans to have this as an attribute in storage account resource?

**Comment by Ileriayo** [comment]
An alternative (for blob storage accounts) may be to use encryption scopes.
You can create an encryption scope with the infrastructure encryption feature enabled and then bind the encryption scope to containers in the storage account.

Caveat (Automatic update of key version): A storage account may have up to 10,000 encryption scopes that are protected with customer-managed keys for which the key version is automatically updated. If your storage account already has 10,000 encryption scopes that are protected with customer-managed keys that are being automatically updated, then the key version must be updated manually for any additional encryption scopes that are protected with customer-managed keys. https://docs.microsoft.com/en-us/azure/storage/blobs/encryption-scope-overview#key-management

**Comment by ryan-peterson3** [comment]
Thanks.  Our Storage Accounts will be used for file shares only.

Ryan Peterson
Infrastructure & Operations
Data Center Services
Federal Aviation Administration

***@***.******@***.***>
2200 S. 216th Street
Des Moines, WA  98198
(206) 231-3296 Office<https://email.dot.gov/owa/>
