### ISSUE TITLE
Support for Tags as Subscription Data Source Attribute

### ISSUE THREAD

**Issue by markhoiland** [hashicorp/terraform-provider-azurerm#8857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For the azurerm_subscription data source it would be helpful to have the tags as a output, just like other resources.  

### New or Affected Resource(s)

* azurerm_subscription

### Potential Terraform Configuration

```hcl
data "azurerm_subscription" "current" {
}

output "current_subscription_tags" {
  value = data.azurerm_subscription.current.tags
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/list

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.

#9456
