### ISSUE TITLE
Support for Stream Analytics storage account settings

### ISSUE THREAD

**Issue by ggmahyar** [hashicorp/terraform-provider-azurerm#8886]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A Storage Account is needed for an Stream Analytic Job to run, if the output is set to Synapse. In contact with Mircosoft we found out that it is already implemented in ARM and .net SDK but the setting is not yet possible via Azure CLI. We want to continue using azurerm_stream_analytics_job and refrain deploying with ARM template.

### New or Affected Resource(s)

* azurerm_stream_analytics_job

And in this point of the ARM Template
```json
    {
      "type": "Microsoft.StreamAnalytics/StreamingJobs",
      "apiVersion": "2017-04-01-preview",
      "name": "${job_name}",
      "location": "${location}",
      "properties": {
        "sku": {
          "name": "${sku}"
        },
...
        "jobStorageAccount": {
          "accountName": "${job_storage_account_name}",
          "accountKey": "${job_storage_account_key}"
        }
...
      }
    }
```
### Potential Terraform Configuration

```hcl
resource "azurerm_stream_analytics_job" "example" {
  name                                     = "example-job"
  resource_group_name                      = var.name
  location                                 = var.location
...
  storage_account = {
     name = var.storage_account_name
     key    = var.storage_account_key
   }
}
```

### References

* #0000

**Comment by ZAHEERPASHA** [comment]
we want to configure storage account settings with Azure stream analytics job using Terraform.  Can someone help us with the code snippet.

**Comment by Avalaxy** [comment]
Huh, is this still open? TF Azurerm has so many possible inputs/outputs for asa now, but can't use them because it's impossible to configure a storage account? Or is there a workaround?

**Comment by Avalaxy** [comment]
@katbyte do you know if this issue is on the radar? It's what is still preventing us for using Terraform for Azure Stream Analytics.

**Comment by Auxority** [comment]
Any updates on this?

**Comment by katbyte** [comment]
This appears to now be supported https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/stream_analytics_job#job_storage_account-1 - as such i am going to close it out
