### ISSUE TITLE
azurerm_mssql_virtual_machine doesn't converge

### ISSUE THREAD

**Issue by t3mi** [hashicorp/terraform-provider-azurerm#8902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azurerm v2.31.1

### Affected Resource(s)

* `azurerm_mssql_virtual_machine`

### Terraform Configuration Files

Code to reproduce could be fetched from [example](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/mssql/mssqlvm) folder
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
Subsequent plan/apply should not show any diffs.

### Actual Behavior
Subsequent plan/apply shows the diff:
```hcl
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # azurerm_mssql_virtual_machine.example will be updated in-place
  ~ resource "azurerm_mssql_virtual_machine" "example" {
        id                    = "/subscriptions/<subscriptionID>/resourceGroups/uniq-resources/providers/Microsoft.SqlVirtualMachine/sqlVirtualMachines/uniq-VM"
        r_services_enabled    = false
        sql_connectivity_port = 1433
        sql_connectivity_type = "PRIVATE"
        sql_license_type      = "PAYG"
        tags                  = {}
        virtual_machine_id    = "/subscriptions/<subscriptionID>/resourceGroups/uniq-resources/providers/Microsoft.Compute/virtualMachines/uniq-VM"

      - storage_configuration {
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #0000

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
