### ISSUE TITLE
Support for additional revision in azurerm_api_management_api

### ISSUE THREAD

**Issue by wongny** [hashicorp/terraform-provider-azurerm#8911]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We would like to create additional revision in api management api, the azurerm_api_management_api can only create api with a revision number. Requesting for feature to manage the api revision, details on additional revisions are described [here](https://docs.microsoft.com/en-us/azure/api-management/api-management-get-started-revise-api#add-a-new-revision).

### New or Affected Resource(s)

* azurerm_api_management_api
* azurerm_api_management_api_revision

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

**Comment by yupwei68** [comment]
Hi @wongny , thanks for opening this issue.
I think additional revision is supported in azurerm_api_management_api here by assigning the `source_api_id` https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management_api#source_api_id

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue seems to have been addressed in the latest versions of the provider (or a valid workaround was provided) - I'm going to close it. Please open a new updated bug report if this is still relevant. Thank you.
