### ISSUE TITLE
azurerm_bot_web_app enpoint value toggles between null and actual value

### ISSUE THREAD

**Issue by orecht** [hashicorp/terraform-provider-azurerm#8971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Tested with terraform 0.12.9 and 0.13.4 (latest stable)
azurerm provider 2.30.0

### Affected Resource(s)
* azurerm_bot_web_app 
* azurerm_bot_channels_registration.

### Terraform Configuration Files

```hcl
locals {
  app_name = "ops-borge"
  microsoft_app_id = ""MY_APPLICATION_REGISTRATION_ID_REDACTED""
}

resource "azurerm_bot_web_app" "borge_bot" {
  name                = local.app_name
  location            = "global"
  resource_group_name = azurerm_resource_group.borge_rg.name
  sku                 = "F0"
  microsoft_app_id     = local.microsoft_app_id

  endpoint            = "https://${local.app_name}.azurewebsites.net/api/messages"
}

resource "azurerm_bot_channels_registration" "borge_webchat" {
  name                = local.app_name
  location            = "global"
  resource_group_name = azurerm_resource_group.borge_rg.name
  sku                 = "F0"
  microsoft_app_id     = local.microsoft_app_id
}
```

### Debug Output

https://gist.github.com/orecht/5e42b3c5dbf3d7ecd3d973083dfa3deb

### Panic Output
No pancic output

### Expected Behavior

First run: endpoint is set to `https://ops-borge.azurewebsites.net/api/messages`
Second and subsequent runs detects not changes and applies not modification. 

Web Chat in Azure portal works after each run 

### Actual Behavior
First run: endpoint is set to `https://ops-borge.azurewebsites.net/api/messages`
Second run endpoint is set to null. Web Chat in Azure portal is not working. 
Third run: endpoint is set to `https://ops-borge.azurewebsites.net/api/messages`. Web Chat in Azure portal is working again.
etc...

### Steps to Reproduce

1. `terraform apply` 3 time on the same code

### Important Factoids
None

**Comment by favoretti** [comment]
Thanks for opening this issue! Since this issue has been reported a long time ago and relates to an older version of provider - I'm going to close it. If this is still relevant and occurring on the latest version of terraform and provider please do open a new issue!
