### ISSUE TITLE
azurerm_application_security_group change-in-place fails when an NSG dependency exists

### ISSUE THREAD

**Issue by dwrolvink** [hashicorp/terraform-provider-azurerm#8989]
Terraform change in place fails on Azure ASG when that ASG is referenced by an NSG rule.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.32.0
```

### Affected Resource(s)
* `azurerm_application_security_group`
* `azurerm_network_security_rule`

### Expected Behavior
When renaming an existing ASG
That is being used in an NSG rule
The NSG rule should be replaced

**or**

When renaming an existing ASG
That is being used in an NSG rule
The new ASG should be created
Then the NSG rule should be updated-in-place
Then the old ASG should be deleted

### Actual Behavior
The NSG rule is being updated-in-place. The order makes that terraform deletes the (old) ASG before the NSG rule is updated. This results in the following error:

```
Error: Error issuing delete request for Application Security Group "ASG-db1" (Resource Group "Test-rg"): 
network.ApplicationSecurityGroupsClient#Delete: Failure sending request: StatusCode=400 -- Original Error: 
Code="ApplicationSecurityGroupCannotBeDeletedIfReferencedBySecurityRule" Message="Application Security Group (ASG) 
/subscriptions/{}/resourceGroups/Test-rg/providers/Microsoft.Network/applicationSecurityGroups/ASG-db1 cannot be deleted 
because it is referenced by SecurityRule(s) /subscriptions{}/resourceGroups/spoke-vnet-rg/providers/Microsoft.Network
/networkSecurityGroups/np-sv-nsg/securityRules/test2, /subscriptions/{}/resourceGroups/spoke-vnet-rg/providers
/Microsoft.Network/networkSecurityGroups/np-sv-nsg/securityRules/test1." Details=[]
```

### Steps to Reproduce

Main.tf
```
/* [whatever backend code to get the below working in your subscription] */

# Create ASG's
resource "azurerm_resource_group" main-rg {
  name     = "test-rg"
  location = "West Europe"
}
resource "azurerm_application_security_group" "asg1" {
  name                = "asg1"
  resource_group_name = azurerm_resource_group.main-rg.name
  location            = azurerm_resource_group.main-rg.location
}
resource "azurerm_application_security_group" "asg2" {
  name                = "asg2"
  resource_group_name = azurerm_resource_group.main-rg.name
  location            = azurerm_resource_group.main-rg.location
}

# Create NSG rules
data "azurerm_resource_group" "nsg-rg" {
  name     = "your nsg rg"
}
data "azurerm_network_security_group" "nsg1" {
  name                = "your nsg"
  resource_group_name = data.azurerm_resource_group.nsg-rg.name
}
resource "azurerm_network_security_rule" "testrule" {
  name                        = "test1"
  priority                    = 1300
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "Tcp"
  source_port_range           = "*"
  destination_port_range      = "*"
  #source_address_prefix       = "*"
  #destination_address_prefix  = "*"
  source_application_security_group_ids = [azurerm_application_security_group.asg1.id]
  destination_application_security_group_ids = [azurerm_application_security_group.asg2.id]
  resource_group_name         = data.azurerm_resource_group.nsg-rg.name
  network_security_group_name = data.azurerm_network_security_group.nsg1.name
}
```
- Then run `terraform apply` this should work.
- Then change one of the ASG names above, and run `terraform apply` again.
- Then the error will be reported

# Current workaround
- Remove the NSG rules from main.tf and run terraform apply
- Place the NSG rules back in main.tf, change the ASG name, then run terraform apply

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
