### ISSUE TITLE
[Hdinsight] Support for encryption at host using platform-managed keys

### ISSUE THREAD

**Issue by serafeimgr** [hashicorp/terraform-provider-azurerm#9009]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

-

### Description
Currently we have the option to create a HDinsight cluster using platform-managed keys but the terraform provider does not give this option.

According to the docs is doable using az cli

example below

```
az hdinsight create -t spark -g MyResourceGroup -n MyCluster \\
-p "yourpass" \\
--storage-account MyStorageAccount --encryption-at-host true


```

### References

https://docs.microsoft.com/en-us/azure/hdinsight/disk-encryption#encryption-at-host-using-platform-managed-keys

**Comment by tfproviders** [comment]
I have given it a spin and was able to implement the same. Here are the details:

- Terraform Provider - [tfproviders/terraform-provider-azurerm](https://registry.terraform.io/providers/tfproviders/azurerm/latest?pollNotifications=true)
- GitHub Repo - [tfproviders/terraform-provider-azurerm](https://github.com/tfproviders/terraform-provider-azurerm)

```
resource "azurerm_hdinsight_hbase_cluster" "example" {
  name                      = "example-hdicluster"
  resource_group_name       = azurerm_resource_group.example.name
  location                  = azurerm_resource_group.example.location
  cluster_version           = "3.6"
  enable_accelerated_writes = true                      # Added in this Fork
  tier                      = "Standard"

  component_version {}
  gateway {}
  storage_account {}
  roles {
    head_node {}
    worker_node {}
    zookeeper_node {}
  }
  enable_disk_encryption {                               # Added in this fork
    using_pmk    = false
    using_cmk_key_url = "https://example.vault.azure.net/keys/xxxxx/xxxxxx"
    msi_resource_id   = "/subscriptions/xxxxxx-xxxxxxx-xxxx-xxxxxxx-xxxxxx/resourcegroups/example/providers/microsoft.managedidentity/userassignedidentities/example-assigned-managed-identity"
  }
}
```
- `enable_accelerated_writes` added to enable accelerated writes for **HBase** clusters, documented [here](https://registry.terraform.io/providers/tfproviders/azurerm/latest/docs/resources/hdinsight_hbase_cluster?pollNotifications=true#enable_accelerated_writes)
- `enable_disk_encryption {}` added to enable encryption at rest for **HBase** clusters. documented [here](https://registry.terraform.io/providers/tfproviders/azurerm/latest/docs/resources/hdinsight_hbase_cluster?pollNotifications=true)

**Comment by tombuildsstuff** [comment]
hey @serafeimgr 

As [mentioned in this issue](https://github.com/hashicorp/terraform-provider-azurerm/issues/8988#issuecomment-2025179295) I believe that support for this is now available and as such I'm going to close this issue for the moment; but if there's more needed on this front then please let us know and we can take another look.

Thanks!
