### ISSUE TITLE
Terraform destroys the wrong resources when subscription_id is changed

### ISSUE THREAD

**Issue by connorbrown-8451** [hashicorp/terraform-provider-azurerm#9012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.33.0
```

### Affected Resource(s)

* `azurerm_resource_group`
* Potentially others, only tested with resource group

### Terraform Configuration Files

```hcl
variable "subscription_id" {}
variable "tenant_id" {}
variable "client_id" {}
variable "client_secret" {}

provider "azurerm" {
  version = "=2.33.0"
  features {}
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  client_id       = var.client_id
  client_secret   = var.client_secret
}

resource "azurerm_resource_group" "test_rg" {
  name     = "rg-destroy-testing"
  location = "eastus2"
}
```

### Debug Output

https://gist.github.com/connorbrown-8451/25104052d328d5ed64dee7d7f14e40ad

### Panic Output

N/A
### Expected Behavior

Terraform should not have destroyed a resource group in a subscription that is different from the subscription it created the resource group in.

### Actual Behavior

When using a Service Principal to authenticate to Azure, Terraform can potentially destroy resources that it did not create. In our scenario, Terraform destroyed a resource group in a different subscription but with the same name as a resource group that it created. Furthermore, Terraform logs to the console that it is destroying the resource group in the correct subscription (the subscription the resource group was created in), but destroyed a resource group in a different subscription. Below is the output of the same terraform destroy command that is logged in the attached gist:

```
azurerm_resource_group.test_rg: Refreshing state... [id=/subscriptions/9bde41cb-d848-4a01-b48a-38c7d2c564d4/resourceGroups/rg-destroy-testing]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # azurerm_resource_group.test_rg will be destroyed
  - resource "azurerm_resource_group" "test_rg" {
      - id       = "/subscriptions/9bde41cb-d848-4a01-b48a-38c7d2c564d4/resourceGroups/rg-destroy-testing" -> null
      - location = "eastus2" -> null
      - name     = "rg-destroy-testing" -> null
      - tags     = {} -> null
    }

Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

azurerm_resource_group.test_rg: Destroying... [id=/subscriptions/9bde41cb-d848-4a01-b48a-38c7d2c564d4/resourceGroups/rg-destroy-testing]
azurerm_resource_group.test_rg: Still destroying... [id=/subscriptions/9bde41cb-d848-4a01-b48a-...64d4/resourceGroups/rg-destroy-testing, 10s elapsed]
azurerm_resource_group.test_rg: Still destroying... [id=/subscriptions/9bde41cb-d848-4a01-b48a-...64d4/resourceGroups/rg-destroy-testing, 20s elapsed]
azurerm_resource_group.test_rg: Still destroying... [id=/subscriptions/9bde41cb-d848-4a01-b48a-...64d4/resourceGroups/rg-destroy-testing, 30s elapsed]
azurerm_resource_group.test_rg: Still destroying... [id=/subscriptions/9bde41cb-d848-4a01-b48a-...64d4/resourceGroups/rg-destroy-testing, 40s elapsed]
azurerm_resource_group.test_rg: Destruction complete after 47s
```

Note that the subscription ID logged above is not the same as what is logged in the debug logs.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `Create resource group in a new subscription with the same name`
4. `export TF_VAR_subscription_id=<new_subscription_id>`
5. `terraform destroy`

### Important Factoids

* Note that a terraform init is not required after the new subscription_id is provided. Running a terraform init, then a terraform apply/destroy yields the same result however.
* The same behavior can be observed by removing the resource group from the Terraform configuration, then running a terraform apply.
* The resource group that was actually created by Terraform is not destroyed during this process.
* Some things have been redacted or otherwise replaced in the debug logs, such as client_secrets and IDs.
* This does not occur when using the [Azure CLI](https://www.terraform.io/docs/providers/azurerm/guides/azure_cli.html) authentication method.
* The backend configuration does not seem to change this behavior.

### References

N/A

**Comment by neunkasulle** [comment]
@connorbrown-8451 Are the subscriptions in the same tenant? (I observed similar behaviour across tenants)

**Comment by connorbrown-8451** [comment]
@neunkasulle - For my testing, I was using the same tenant. I have not tried cross-tenant, but I am not surprised to hear that you're observing the same behavior.

**Comment by tombuildsstuff** [comment]
Consolidating this into #11662
