### ISSUE TITLE
azurerm_monitor_scheduled_query_rules_alert incorrectly requires metric_column when it is an optional property

### ISSUE THREAD

**Issue by kensykora** [hashicorp/terraform-provider-azurerm#9026]
The `azurerm_monitor_scheduled_query_rules_alert` resource type, when using a `metric_trigger`, currently requires the resource to declare a `metric_column` property, but this is an optional field in Azure, and setting this field changes the behavior of the alert. It causes the alert to trigger split out by a column, when I don't want it to do that at all.

Here's an example -- alert without a `metric_column` -- in the gif I switch between without, and then TO a metric column

![metric](https://user-images.githubusercontent.com/64756/97208502-2f82ed00-1789-11eb-9f19-e2fa480f4eb3.gif)

Here is the sample terraform:

```hcl

resource "azurerm_monitor_scheduled_query_rules_alert" "high_error_rate" {
  count = var.enable_alerts ? 1 : 0

  name                = "${local.prefix}-alert-high-error-rate"
  resource_group_name = azurerm_resource_group.gateway_rg.name
  location            = azurerm_resource_group.gateway_rg.location

  action {
    action_group = [
      data.azurerm_monitor_action_group.med.id
    ]
    email_subject = "Gateway - ${title(var.env)} - High Error Rate"
  }

  data_source_id = azurerm_application_insights.gw_app_insights.id
  description    = "Alert when high error rate in the gateway"
  enabled        = true

  query = <<-QUERY
    let start=floor(ago(30m), 1m);
    let end=floor(now(), 1m);
    let interval=5m;
    requests
    | where name == "Device Connection"
    | join kind=leftouter 
    (
      exceptions
      | summarize num_exceptions=count() by operation_Id
    )
    on $left.operation_Id == $right.operation_Id
    // | where timestamp > start and timestamp < end
    // | summarize AggregatedValue=toint((todecimal(count()) - todecimal(countif(num_exceptions > 0))) / todecimal(count()) * 100) by bin(timestamp, interval)
    | make-series kind=nonempty AggregatedValue=toint((todecimal(count()) - todecimal(countif(num_exceptions > 0))) / todecimal(count()) * 100) default=100
                  on timestamp in range(start, end, interval)
    | mv-expand timestamp, AggregatedValue
    | summarize AggregatedValue=max(toint(AggregatedValue)) by bin(todatetime(timestamp), interval)
  QUERY

  severity    = 1  # Error
  frequency   = 5  # Minutes
  time_window = 30 # Minutes
  trigger {
    operator  = "LessThan"
    threshold = 100 - local.error_rate_percent

    metric_trigger {
      metric_trigger_type = "Consecutive"
      operator = "GreaterThan"
      threshold = 1
      metric_column = "timestamp" # THIS SHOULD NOT BE REQUIRED
    }
  }
}
```

The ARM Template, without the `metric_column`, for reference:

```json
 {
            "type": "microsoft.insights/scheduledqueryrules",
            "apiVersion": "2018-04-16",
            "name": "[parameters('scheduledqueryrules_paas_dev_gw_alert_high_error_rate_name')]",
            "location": "westeurope",
            "dependsOn": [
                "[resourceId('microsoft.insights/components', parameters('components_paas_dev_gw_ai_name'))]"
            ],
            "properties": {
                "description": "Alert when high error rate in the gateway",
                "enabled": "true",
                "source": {
                    "query": "let start=floor(ago(30m), 1m);\nlet end=floor(now(), 1m);\nlet interval=5m;\nrequests\n| where name == \"Device Connection\"\n| join kind=leftouter \n(\n  exceptions\n  | summarize num_exceptions=count() by operation_Id\n)\non $left.operation_Id == $right.operation_Id\n// | where timestamp > start and timestamp < end\n// | summarize AggregatedValue=toint((todecimal(count()) - todecimal(countif(num_exceptions > 0))) / todecimal(count()) * 100) by bin(timestamp, interval)\n| make-series kind=nonempty AggregatedValue=toint((todecimal(count()) - todecimal(countif(num_exceptions > 0))) / todecimal(count()) * 100) default=100\n              on timestamp in range(start, end, interval)\n| mv-expand timestamp, AggregatedValue\n| summarize AggregatedValue=max(toint(AggregatedValue)) by bin(todatetime(timestamp), interval)\n",
                    "authorizedResources": [],
                    "dataSourceId": "[resourceId('microsoft.insights/components', parameters('components_paas_dev_gw_ai_name'))]",
                    "queryType": "ResultCount"
                },
                "schedule": {
                    "frequencyInMinutes": 5,
                    "timeWindowInMinutes": 30
                },
                "action": {
                    "severity": "1",
                    "aznsAction": {
                        "actionGroup": [
                            "[parameters('actionGroups_medium_priority_externalid')]"
                        ],
                        "emailSubject": "Gateway - Dev - High Error Rate"
                    },
                    "trigger": {
                        "thresholdOperator": "LessThan",
                        "threshold": 90,
                        "metricTrigger": {
                            "thresholdOperator": "GreaterThan",
                            "threshold": 1,
                            "metricTriggerType": "Consecutive"
                        }
                    },
                    "odata.type": "Microsoft.WindowsAzure.Management.Monitoring.Alerts.Models.Microsoft.AppInsights.Nexus.DataContracts.Resources.ScheduledQueryRules.AlertingAction"
                }
            }
        },
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_monitor_scheduled_query_rules_alert`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

```
❯ terraform plan
Acquiring state lock. This may take a few moments...
Releasing state lock. This may take a few moments...

Error: Missing required argument

  on ..\..\infrastructure\monitoring.tf line 80, in resource "azurerm_monitor_scheduled_query_rules_alert" "high_error_rate":
  80:     metric_trigger {

The argument "metric_column" is required, but no definition was found.
```
### Expected Behavior

`metric_column` should not be a required field. It should be optional.

### Actual Behavior

`metric_column` is required.

### Steps to Reproduce

See above

1. `terraform apply`

### References

* #3951
* #5053

**Comment by fgarcia-cnb** [comment]
On a related note, I have a manually built alert in the portal that has the metric trigger operator set to "GreaterThanOrEqual", but terraform provider only supports "[GreaterThan LessThan Equal]"

**Comment by sandeepsingh0321** [comment]
I ran into the same issue today. While terraform alert pipeline I got the same error
`The given value is not valid for variable "query_rules_alerts": element
"qra3": attribute "trigger": attribute "metric_trigger" is required.
`

**Comment by gondar** [comment]
We hit this one too just now.

**Comment by cjrpriest** [comment]
My investigation revealed that `metric_column` in terraform maps to `metricMeasureColumn` in the ARM Condition object (see https://docs.microsoft.com/en-us/azure/templates/microsoft.insights/scheduledqueryrules?tabs=json), and not the `dimensions` property in the ARM Condition object, which is what the OP implied by associating it with the "Aggregate on" and "Pivoted on" UI elements in the GIF.

The only value for `metric_column` that I've managed to make work is `AggregatedValue`, which is the column name that the UI in the Azure portal insists that you use.

When you use something else (in the query _and_ the `metric_column` property), I'm not sure if the alert will actually work or not, but the UI doesn't like it when you open up the alert in the Azure portal.

**Comment by truptisatardekar** [comment]
I'm having similar issue. When creating the log search alert from the portal, I see different configuration options
![image](https://user-images.githubusercontent.com/28647908/155552487-9a047f99-0b7a-47a0-80ab-8516f0e630f7.png)

When I try to create the same resource using terraform (azurerm_monitor_scheduled_query_rules_alert), terraform has different configuration. I adjusted the configuration, did terraform apply. Now the resource created in portal has different configuration options
![image](https://user-images.githubusercontent.com/28647908/155553112-d033cbbb-1ca4-447e-888b-49ec7cc91c04.png)

Why do I see the difference? Also, the log query works perfectly fine when I create the log alert directly in portal. When I add the same query by terraform, in the portal later it throws an error: 

> Search Query should contain 'AggregatedValue' and 'bin(timestamp, [roundTo])' for Metric alert type

Does anyone else has similar issue?

**Comment by wpassarella** [comment]
Hi @truptisatardekar 

I have the same problem as you. There is no part of measurements in the Terraform documentation, there is no way to implement this via terraform, it is outdated in relation to the Portal.

![image](https://user-images.githubusercontent.com/21314058/158359458-f603e34a-296d-4e07-afb5-e28d8bd0ce69.png)

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_scheduled_query_rules_alert

**Comment by kutsav** [comment]
Was anyone able to solve this?

**Comment by nc-winish** [comment]
Having the same problem as shown by [truptisatardekar](https://github.com/truptisatardekar)

Creating an Azure Alert with a custom log search on a VM manually from the Azure Portal i get these options:
![image](https://user-images.githubusercontent.com/80685510/169006897-a38d317b-61d5-4f7e-b2f4-88f3d337c166.png)

In the Alert rules i see the condition as expected: 
![image](https://user-images.githubusercontent.com/80685510/169008295-f9df0f58-0e82-4013-b731-8dfcff828194.png)

When creating the same one with Terraform ( Tried 1.1.0 and up ) and AzureRM ( tried 2.87.0 and up )

I get this underneath the kusto query:
![image](https://user-images.githubusercontent.com/80685510/169008671-b56bc40d-07d5-4eff-b0ee-fcb859f302d9.png)

Changing the kusto wont work anymore, it will keep trowing this error.

The options will have changed.
![image](https://user-images.githubusercontent.com/80685510/169008765-657bcec2-54bb-47e7-9f5b-abfa505709ed.png)

When comparing the Alerts, i notice that in the JSON there is also a difference in query Type.
The one i made manually uses:
"queryType": "Number"

The one i created with TF uses:
"queryType": "ResultCount"

Is this causing the problem?

**Comment by nc-winish** [comment]
Thanks to [sam-merrell-sp](https://github.com/sam-merrell-sp) comment, it got me thinking.

i found a work-around by using AzApi https://docs.microsoft.com/en-us/azure/developer/terraform/overview-azapi-provider
With this provider you will be able to still use terraform, but code while using ARM (not templates!) and being able to select which API you want to use.
Got it working by using the 2021-08-01  API

**Comment by pplavetzki** [comment]
@nc-winish Any chance you have an example of the code you used?  Would be extremely helpful!  Thank you.
