### ISSUE TITLE
dns server list order issue in vnet

### ISSUE THREAD

**Issue by fgarcia-cnb** [hashicorp/terraform-provider-azurerm#9063]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v2.33.0
### Affected Resource(s)

* `azurerm_virtual_network`

### Terraform Configuration Files

```hcl
#changing dns servers order as follows
~ dns_servers = [
          - "10.70.2.30",
            "10.94.2.84",
            "10.90.2.84",
          + "10.70.2.30",
        ]
```

### Expected Behavior
we are changing the order of the DNS servers on the VNET:

Expect order to apply. subsequent runs should not see changes

### Actual Behavior

Azure Portal shows list order changes, but subsequent terraform plans/applies still detect changes, and tries to apply same change over and over. not idempotent

### Steps to Reproduce

1. `terraform apply`

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After tested, seems Service API doesn't support to change the order of the DNS servers. So I submit a PR to update the attribute of dns_servers from TypeList to TypeSet since API doesn't care the order of the DNS Servers.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. When it gets added, we can reopen this request or you can create a new one.
