### ISSUE TITLE
Support looking up list of private DNS zones linked to a given VNET

### ISSUE THREAD

**Issue by eehret** [hashicorp/terraform-provider-azurerm#9096]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've run into a use case where I need to be able to look up the private dns zone(s) that are linked to a given VNET.  I don't see any way to do that currently using any azurerm data provider (please correct me if I'm missing something).

More context for the scenario:  I provisioned a private AKS cluster.  When you do that, the `azurerm_kubernetes_cluster` creates a private DNS zone for itself.
In a later step of my build process, I have a need to link that private DNS zone to another existing subnet in my network.  
Unfortunately the name of the DNS zone does not seem to be exposed by the azurerm_kubernetes_cluster data provider, nor does it seem that I can look up a private DNS zone without knowing its name.  But `azurerm_kubernetes_cluster` chooses the name for me randomly, so I can't know the name.

It would be great to have a property exposed on `azurerm_kubernetes_cluster` that tells me the name of the private dns zone, OR, have a data provider for looking up azurerm_private_dns_zone without fully specifying a name. 
I *do* know what resource group it was created in, so I could provide that....but not the name.

### New or Affected Resource(s)
`azurerm_kubernetes_cluster`
`azurerm_private_dns_zone`

### References

* #0000

**Comment by pierreyvesv** [comment]
hello @eehret ,

you can use the following code to get the dns zone from azurerm_kubernetes_cluster:

```
locals {
  aks_private_dns_zone = join(".", slice(split(".", azurerm_kubernetes_cluster.kube_infra.private_fqdn), 1, 6))
}

data "azurerm_private_dns_zone" "private_aks_zone" {
  name                = local.aks_private_dns_zone
  resource_group_name = azurerm_kubernetes_cluster.kube_infra.node_resource_group
}

```
