### ISSUE TITLE
Cannot import aks cluster - flattening `default_node_pool`: The Default Agent Pool "" was not found

### ISSUE THREAD

**Issue by ludydoo** [hashicorp/terraform-provider-azurerm#9122]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.34.0
```

### Affected Resource(s)

```
azurerm_kubernetes_cluster
azurerm_kubernetes_cluster_node_pool
```

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.34.0"
  skip_provider_registration = true
  features {}
}

terraform {
  backend "local" {
    path = "terraform.tfstate"
  }
}

resource "azurerm_resource_group" "staging" {
  name     = "staging"
  location = "West Europe"
}

resource "azurerm_public_ip" "staging" {
  name                = "staging"
  resource_group_name = azurerm_resource_group.staging.name
  location            = azurerm_resource_group.staging.location
  allocation_method   = "Static"
}

resource "azurerm_kubernetes_cluster" "staging" {
    name                = "staging"
    location            = azurerm_resource_group.staging.location
    resource_group_name = azurerm_resource_group.staging.name
    dns_prefix          = "staging"

    linux_profile {
        admin_username = "azureuser"
        ssh_key {
            key_data = "REDACTED"
        }
    }

    default_node_pool {
        type            = "VirtualMachineScaleSets"
        name            = "nodepool1"
        node_count      = 1
        vm_size         = "Standard_B4ms"
        vnet_subnet_id = "REDACTED"
    }

    service_principal {
        client_id     = "REDACTED"
    }

    role_based_access_control {
      enabled = "true"
    }

    network_profile {
      load_balancer_sku = "Standard"
      network_plugin = "azure"
      network_policy = "azure"
      dns_service_ip = "REDACTED"
      docker_bridge_cidr = "172.17.0.1/16"
      outbound_type = "loadBalancer"
      service_cidr = "REDACTED"
      load_balancer_profile {
        managed_outbound_ip_count = 1
        outbound_ip_address_ids = [azurerm_public_ip.staging.id]
      }
    }
}

```

### Debug Output

```
2020/11/02 11:59:04 [ERROR] eval: *terraform.EvalRefresh, err: flattening `default_node_pool`: The Default Agent Pool "" was not found
2020/11/02 11:59:04 [ERROR] eval: *terraform.EvalSequence, err: flattening `default_node_pool`: The Default Agent Pool "" was not found

Error: flattening `default_node_pool`: The Default Agent Pool "" was not found
```

### Expected Behavior

It should understand that I'm trying to import an existing NodePool, and that it has a name that was provided in the default_node_pool block

### Actual Behavior

It thinks that the default_node_pool has no name at all

### Steps to Reproduce

1. `terraform import azurerm_kubernetes_cluster.staging /subscriptions/REDACTED/resourcegroups/staging/providers/Microsoft.ContainerService/managedClusters/staging`

### Important Factoids

This is not a greenfield project

I need to import an existing kubernetes AKS cluster

**Comment by stephybun** [comment]
Hi @ludydoo,

I realise this issue is several years old now but wondering if this is still a problem with the latest version of the provider?

**Comment by stephybun** [comment]
Closing since we haven't heard back. If this is still an issue with the latest version of the provider feel free to reach out and we can reopen this. Thanks!
