### ISSUE TITLE
Virtual Network Gateway Connection provisioned in a failed state is not recognized as a new created resource in Terraform

### ISSUE THREAD

**Issue by skinamdar** [hashicorp/terraform-provider-azurerm#9130]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_network_gateway_connection`

### Terraform Configuration Files

```hcl
resource azurerm_virtual_network_gateway_connection "ercconection_con-test123-vng-vnet1-expressroute-123" {
   name                = "con-test123-vng-vnet-expressroute-123"
   location            = data.azurerm_virtual_network.vnet1.location
   resource_group_name = data.azurerm_virtual_network.vnet1.resource_group_name
   type                = "ExpressRoute"
   virtual_network_gateway_id = azurerm_virtual_network_gateway.vng_vng-vnet1-expressroute-123.id
   express_route_gateway_bypass = true

   authorization_key = "123"
   express_route_circuit_id = "/subscriptions/###/resourceGroups/abc/providers/Microsoft.Network/expressRouteCircuits/test123"

   routing_weight      = 0
   depends_on = [azurerm_virtual_network_gateway.vng_vng-vnet1-expressroute-123]
}
```

### Expected Behavior

When we run terraform apply against that resource, even if it was initially provisioned in a failed state, that state should have been reflected back to Terraform. So when we run `terraform apply` it will recognize the Virtual Network Gateway connection was created and we don't need to import the state. 

### Actual Behavior

Even though the Virtual Network Gateway connection was created, it was created in a failed state. Terraform should have picked up that state that the resource was created so when we run `terraform apply` again, we don't need to import the state. What actually happened is that Terraform's state didn't get the signal that the resource was created and complained stating the resource is already in azure and the state needs to be imported. 

### Steps to Reproduce

1. `terraform apply` of a Virtual Network Gateway connection which connects to an NON-provisioned Express Route Circuit
2. Get the output 
```
Error: Error waiting for completion of Virtual Network Gateway Connection "con-test123-vng-vnet1-expressroute-123" (Resource Group "abc"): Code="ServiceProviderNotProvisioned" Message="The current cross connection provisioning state 'NotProvisioned' of this service key '123' prevents this operation." Details=[]
```
3. Run `terraform apply` again gives us the following error
```
Error: A resource with the ID "/subscriptions/###/resourceGroups/abc/providers/Microsoft.Network/connections/con-test123-vng-vnet1-expressroute-123" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_network_gateway_connection" for more information.
```

### Important Factoids

This only happens when a Virtual Network Gateway Connection is initially provisioned in a Failed state, explicitly when trying to connect to an Express Route Circuit that isn't provisioned yet. 

### References

* #0000

**Comment by rossdotpink** [comment]
Noticing the same behavior with provisioning AKS Clusters; `terraform apply` can fail due to a provisioning error where there are insufficient IPs available in the requested subnet, but the cluster is still provisioned (just into a 'Failed' state).

Terraform does not adopt the resource into its state, which seems similar to the issue above.

**Comment by xortim** [comment]
I'm encountering this exact issue. The resource gets provisioned and I would expect this to be recorded by terraform.

**Comment by favoretti** [comment]
Hi there and thank you for opening this issue. While the resources are getting provisioned by RM API on Azure side, terraform provider relies on successful return codes from the API to be able to completely "adopt" the resource and provision it into state. Judging from the output of your error, terraform wasn't able to provision the resource successfully and therefore considered it a failed attempt. 

I'm going to close this issue, since there's little we can do here unfortunately, but feel free to re-open if you feel we've closed this erroneously.
