### ISSUE TITLE
Support for IoTHub Managed Service Identity for Endpoints

### ISSUE THREAD

**Issue by MPapst** [hashicorp/terraform-provider-azurerm#9139]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The IoTHub supports the Managed Service Identity Feature to use the MSI for Authorization against endpoints.
* Currently it is not possible to create an IoT Hub with identity block.
* Currently it is not possible to use the Identity for Authorization when creating IoT Hub Endpoints

### New or Affected Resource(s)

* azurerm_iothub

### Potential Terraform Configuration

```hcl
resource "azurerm_iothub" "test" {
# [...]
  identity {
     type = "SystemAssigned"
  }
  
  endpoint {
    type = "AzureIoTHub.ServiceBusTopic"
    # [...]
    use_managed_identity = true
  }
```
This should create a new Role Assignment for the MSI. Alternative it could be possible to create an azurerm_iothub_endpoint resource.

### References

No References found

**Comment by davidlane-iteratec** [comment]
This is a quite painful omission. Using IoTHub Manage Identities is the only way to allow messages from an IoTHub to be routed to services connected to Vnets:
https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support#egress-connectivity-from-iot-hub-to-other-azure-resources

**Comment by davidlane-iteratec** [comment]
Also 2 out of 3 points of on the above page (https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support#egress-connectivity-to-event-hubs-endpoints-for-routing) are currently not possible:
1. azurerm_role_assignment of "Azure Event Hubs Data Sender" -> Cannot retrieve the id of the system assigned managed identity of the iothub. I guess this will become a output attribute when this bug is implemented.
2. Custom endpoint with Identity-based as the Authentication type. Here is how this looks:

    "routing": {
      "endpoints": {
        "eventHubs": [
          {
            "authenticationType": "identityBased",
            "connectionString": null,
            "endpointUri": "sb://<eventhubnamespace>.servicebus.windows.net",
            "entityPath": "<eventhub>",
            "id": "<eventhub-id>",
            "name": "testtesttest",
            "resourceGroup": "<resourcecroup>",
            "subscriptionId": "<subscriptionid>"
          }
        ],

3. Also now that I see it there is also no output attribute of a evenhub namespace corresponding to "sb://<eventhubnamespace>.servicebus.windows.net": but that can be bolted together using string ops.

I have been able to work around it using a combination of null_resource with local_exec provisioner and external data source with call to az cli but it's not pretty.

**Comment by eranjbarSuncor** [comment]
@davidlane-iteratec do you think you could share a sanitized version of your workaround? I am interested in implementing something similar

**Comment by davidlane-iteratec** [comment]
@eranjbarSuncor : sure, it was something along these lines
```
resource "null_resource" "iothub-sami-on-creation" {
  triggers = {
    iothub-id = azurerm_iothub.<iothub>.id
  }

  provisioner "local-exec" {
    command = "az iot hub update --name ${azurerm_iothub.<iothub>.name} --set identity.type=\"SystemAssigned\""
  }
}

resource "null_resource" "iothub-routing-on-creation" {
  triggers = {
    iothub-id = azurerm_iothub.<iothub>.id
  }
 
  provisioner "local-exec" {
    command = "az iot hub routing-endpoint create -r ${azurerm_resource_group.<iothubrg>.name} -n iotep-eh -s ${data.azurerm_subscription.current.subscription_id} -t eventhub --hub-name ${azurerm_iothub.<iothub>.name} --auth-type identitybased --endpoint-uri sb://${azurerm_eventhub_namespace.<eventhubns>.name}.servicebus.windows.net --entity-path ${azurerm_eventhub.<eventhub>.name}"
  }
}

data "external" "identity-evhns" {
  program    = ["az", "iot", "hub", "show", "-n", azurerm_iothub.<iothub>.name, "--query", "identity"]
}

resource "azurerm_role_assignment" "ra-evhns-iot" {
  scope                = azurerm_eventhub_namespace.<eventhubns>.id
  role_definition_name = "Azure Event Hubs Data Sender"
  principal_id         = data.external.identity-evhns.result.principalId
}
```

**Comment by MPapst** [comment]
Will that create a endpoint every time you call the script, even when the endpoint is already there?

**Comment by davidlane-iteratec** [comment]
See https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource 
Triggers ensures that the block is only called when the value (in this case iothub id) changes

**Comment by MPapst** [comment]
Very good workaround... unfortunately it seems unusable for me.
As soon as I figured out that there are additional features (like private endpoint) that are not supported...
I am thinking of going to bicep for the hub and have an call that one from terraform.

**Comment by derSchtefan** [comment]
We would need this, since our IoT hubs, like every other resource we create in Terraform, uses system managed identities, and authentication between services is done with that.

It is kinda strange that azurerm supports 
```hcl
 identity {
     type = "SystemAssigned"
  }
```
everywhere except for IoT hub.

**Comment by benjamin-goldman** [comment]
hey!  any chance this just works in Pulumi?

also - is this getting addressed?

**Comment by luckeyca** [comment]
this seems to be the same as this: https://github.com/hashicorp/terraform-provider-azurerm/issues/12170

**Comment by myc2h6o** [comment]
Previous change #14354 adds the `identity` to the `iothub`, this new change #14705 allows the endpoints to use the identity.
