### ISSUE TITLE
Issue updating IotHub having identity managed storage container endpoints

### ISSUE THREAD

**Issue by aha0926** [hashicorp/terraform-provider-azurerm#9155]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.34.0

### Affected Resource(s)

* `azurerm_iothub`

### Terraform Configuration Files

```
resource "azurerm_iothub" "iothub" {
  name                = local.iothub_name
  resource_group_name = data.azurerm_resource_group.vmrg.name
  location            = data.azurerm_resource_group.vmrg.location

  sku {
    name     = "S1"
    capacity = "2"
  }
}
```

### Debug Output
![image](https://user-images.githubusercontent.com/55856699/98121405-8a19f880-1eaf-11eb-8847-7cf930287be4.png)

GET /subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/MyRg/providers/Microsoft.Devices/IotHubs/my-iothub-name?api-version=2020-03-01 HTTP/1.1

Response 200:
{
	"id": "/subscriptions/xxxxxxxxxxxxxxxxxxx/resourceGroups/MyRg/providers/Microsoft.Devices/IotHubs/my-iouthub-name",
	"name": "my-iothub-name",
	"type": "Microsoft.Devices/IotHubs",
	"location": "westeurope",
	"tags": {},
	"subscriptionid": "xxxxxxxxxxxxxxxxxx",
	"resourcegroup": "MyRg",
	"etag": "AAAABDqSdHw=",
	"properties": {
		"locations": [
			{
				"location": "West Europe",
				"role": "primary"
			},
			{
				"location": "North Europe",
				"role": "secondary"
			}
		],
		"state": "Active",
		"provisioningState": "Succeeded",
		"ipFilterRules": [],
		"hostName": "my-iothub-name.azure-devices.net",
		"eventHubEndpoints": {
			"events": {
				"retentionTimeInDays": 1,
				"partitionCount": 4,
				"partitionIds": [
					"0",
					"1",
					"2",
					"3"
				],
				"path": "my-iothub-name",
				"endpoint": "xxxxxxxxxxxxxx"
			}
		},
		"routing": {
			"endpoints": {
				"serviceBusQueues": [],
				"serviceBusTopics": [],
				"eventHubs": [],
				"storageContainers": [
					{
						"containerName": "iothub",
						"fileNameFormat": "{iothub}/{partition}/{YYYY}/{MM}/{DD}/{HH}/{mm}.avro",
						"batchFrequencyInSeconds": 100,
						"maxChunkSizeInBytes": 104857600,
						"encoding": "avro",
						"endpointUri": "https://datalakegen2.blob.core.windows.net/",
						"authenticationType": "identityBased",
						"name": "datalakegen2",
						"id": "xxxxxxxxxxxxxxxxxxxxxxxx",
						"subscriptionId": "xxxxxxxxxxxxx",
						"resourceGroup": "MyRg"
					}
				]
			},
			"routes": [
				{
					"name": "datalakegen2",
					"source": "DeviceMessages",
					"condition": "true",
					"endpointNames": [
						"datalakegen2"
					],
					"isEnabled": true
				}
			],
			"fallbackRoute": {
				"name": "$fallback",
				"source": "DeviceMessages",
				"condition": "true",
				"endpointNames": [
					"events"
				],
				"isEnabled": false
			}
		},
		...
	},
	"sku": {
		"name": "S1",
		"tier": "Standard",
		"capacity": 1
	},
	"identity": {
...
	}
}

PUT /subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/MyRg/providers/Microsoft.Devices/IotHubs/my-iothub-name?api-version=2020-03-01 HTTP/1.1
{
	"location": "westeurope",
	"properties": {
		"enableFileUploadNotifications": false,
		"eventHubEndpoints": {
			"events": {
				"partitionCount": 4,
				"retentionTimeInDays": 1
			}
		},
		"messagingEndpoints": {},
		"routing": {
			"endpoints": {
				"serviceBusQueues": [],
				"serviceBusTopics": [],
				"eventHubs": [],
				"storageContainers": [
					{
						**"connectionString": "",**
						"name": "datalakegen2atlasdev",
						"subscriptionId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
						"resourceGroup": "MyRg",
						"containerName": "iothub",
						"fileNameFormat": "{iothub}/{partition}/{YYYY}/{MM}/{DD}/{HH}/{mm}.avro",
						"batchFrequencyInSeconds": 100,
						"maxChunkSizeInBytes": 104857600,
						"encoding": "avro"
					}
				]
			},
			"routes": [
				{
					"name": "datalakegen2",
					"source": "DeviceMessages",
					"condition": "true",
					"endpointNames": [
						"datalakegen2"
					],
					"isEnabled": true
				}
			],
			"fallbackRoute": {
				"source": "DeviceMessages",
				"condition": "true",
				"endpointNames": [
					"events"
				],
				"isEnabled": false
			}
		},
		"storageEndpoints": {}
	},
	"sku": {
		**"capacity": 2,**
		"name": "S1"
	},
	"tags": {}
}

Response 500:
{
	"code": 500018,
	"httpStatusCode": "InternalServerError",
	"message": "Malformed Token. If you contact a support representative please include this correlation identifier: xxxxxxxxxxxxxxx, timestamp: 2020-11-04 13:23:16Z, errorcode: IH500018."
}
### Expected Behavior

IotHub has custom endpoints that are not controlled by the code.
When updating IotHub (resizing, for example) with terraform apply the operation is successful.

### Actual Behavior

When updating IotHub with terraform apply the operation fails with message "The async operation failed." InnerError={"unmarshalError":"json: cannot unmarshal number into Go struct field serviceError2.code of type string"} AdditionalInfo=[{"code":500018,"httpStatusCode":"InternalServerError","message":"Malformed Token. "

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by luckeyca** [comment]
as currently the azurerm_iothub does not support managed identity which is required to create custom endpoints using other azure services as documented here: https://docs.microsoft.com/en-us/azure/iot-hub/virtual-network-support#egress-connectivity-from-iot-hub-to-other-azure-resources
This is related to this feature request: https://github.com/hashicorp/terraform-provider-azurerm/issues/12170

**Comment by myc2h6o** [comment]
Hi @aha0926 identity-based endpoints are being added in #9139, it shall be able to resolve this issue. Rather than having multiple issues open to track the same thing, would you mind subscribing to it for update? Feel free to reopen this issue if it cannot be fully resolved.

**Comment by mybayern1974** [comment]
Hi @aha0926 , I'm closing this issue for it being dup with #9139 that has been resolved now. Please suggest to reopen it you feel it's not the case.
