### ISSUE TITLE
Support for 2020-03-30 version of HealthcareApis

### ISSUE THREAD

**Issue by ricec** [hashicorp/terraform-provider-azurerm#9179]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the [2020-03-30 version of HealthcareApis](https://github.com/Azure/azure-sdk-for-go/tree/master/services/healthcareapis/mgmt/2020-03-30/healthcareapis) to add new properties such as exportConfiguration, publicNetworkAccess, and identity.

### New or Affected Resource(s)

* azurerm_healthcare_service

**Comment by tombuildsstuff** [comment]
Thanks @r-t-m 👍
