### ISSUE TITLE
azurerm_firewall: Enable DNS Proxy + Azure provided DNS

### ISSUE THREAD

**Issue by poddm** [hashicorp/terraform-provider-azurerm#9184]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Current implementation will only `Enable` DNS Proxy when providing custom DNS servers.  However, it seems azure allows you to Enable DNS proxy settings and still use the `Azure provided DNS`.

Example Screenshot:
![Screen Shot 2020-11-05 at 4 26 19 PM](https://user-images.githubusercontent.com/8801231/98311200-a7b89200-1f83-11eb-8041-8a61ef3c28f9.png)

### New or Affected Resource(s)

* azurerm_firewall

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "azurerm_firewall" "example" {
  name                = "example-fw"
  location            = var.location
  resource_group_name = var.resource_group_name

  dns_proxy = true
  
  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.this.id
    public_ip_address_id = azurerm_public_ip.this.id
  }
}

```

### Example from Azure docs
* https://docs.microsoft.com/en-us/azure/firewall/dns-settings#enable-dns-proxy-preview-1
```bash
az network firewall update \
    --name fwName \ 
    --resource-group fwRG \
    --enable-dns-proxy true
```

### References

* #8878

**Comment by poddm** [comment]
Believe I can work around this with the following

```hcl
resource "azurerm_firewall" "example" {
  name                = "example-fw"
  location            = var.location
  resource_group_name = var.resource_group_name
  
  # https://docs.microsoft.com/en-us/azure/virtual-network/what-is-ip-address-168-63-129-16
  dns_servers = ["168.63.129.16"]
  
  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.this.id
    public_ip_address_id = azurerm_public_ip.this.id
  }
}
```

**Comment by fcommand-all** [comment]
Do we plan to add "dns proxy" ? There is use case to have this settings only (without DNS server) :  use FQDN in Azure Firewall network rules.

**Comment by niswitze** [comment]
Are there any updates on this feature?
