### ISSUE TITLE
azurerm_app_service_hybrid_connection - Fail to request send_key_name

### ISSUE THREAD

**Issue by cacizi41** [hashicorp/terraform-provider-azurerm#9185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
### Affected Resource(s)

* `azurerm_app_service_hybrid_connection`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_plan" "asp" {
  name                = var.app_service_plan_name
  location            = var.location
  resource_group_name = var.resource_group_name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "appservice" {
  name                = var.app_service_name
  location            = var.location
  resource_group_name = var.resource_group_name
  app_service_plan_id = azurerm_app_service_plan.asp.id
}

resource "azurerm_relay_namespace" "relay" {
  name                = var.relay_name
  location            = var.location
  resource_group_name = var.resource_group_name

  sku_name = "Standard"
}

resource "azurerm_relay_hybrid_connection" "relay_hc" {
  name                 = var.hybrid_connection_name
  resource_group_name  = var.resource_group_name
  relay_namespace_name = azurerm_relay_namespace.relay.name
  user_metadata        = "user_metadata"
}

resource "azurerm_app_service_hybrid_connection" "appservice_hc" {
  app_service_name    = var.app_service_name
  resource_group_name = var.resource_group_name
  relay_id            = azurerm_relay_hybrid_connection.relay_hc.id
  hostname            = "testhostname"
  port                = 8080
  send_key_name       = "RootManageSharedAccessKey" (Also tried removing this attribute since it is optional)
}
```

### Debug Output

No
### Panic Output

No
### Expected Behavior
Plan OK

### Actual Behavior

The app service, the relay namespace & relay_hybrid_connection  are created ok but app_service_hybrid_connection creation failed.

Error: unable to List Access Keys for Namespace "XXX" (Resource Group "XXX"): relay.NamespacesClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "\"The requested resource exampleSharedAccessKey does not exist.\"" error: json: cannot unmarshal string into Go value of type azure.RequestError

Also tried importing app service, relay and hc that are created manually to verify the format. Got the same error as above.
### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by cacizi41** [comment]
I think it is a bug. So I created a key named "exampleSharedAccessKey" in the relay. It planned ok. And If I changed the send_key_name value to a non empty random string. It still plans ok. So terraform is looking only for "exampleSharedAccessKey" no matter what user input.

**Comment by GelbB** [comment]
Looking in to the source code, seems like the error is that the SendKeyName is collected from the hybridConnection object, regardless what the user had entered. as a result, the App-Service tries using the HyCo send key instead of the NAmespace send key (which is in default `RootManageSharedAccessKey`). 

in this file https://github.com/terraform-providers/terraform-provider-azurerm/blob/1ed305d60383e9cc299dcf12685606978994f19d/azurerm/internal/services/web/app_service_hybrid_connection_resource.go check lines 176 -197

**Comment by cacizi41** [comment]
A follow up update on this issue. We are now getting new `Error: unable to List Access Keys for Namespace "XXX" (Resource Group "XXX"): relay.NamespacesClient#ListKeys: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: ""The requested resource **defaultSender** does not exist.""`  We did a walkaround by setting up 'defaultSender' key in relay.

**Comment by tgolly** [comment]
Also having this issue.  

Documentation says the default key is "RootManageSharedAccessKey".

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service_hybrid_connection#send_key_name

**Comment by rcskosir** [comment]
Thanks for opening this issue. The azurerm_app_service_hybrid_connection resource is deprecated in version 3.0 and will be removed in version 4.0 - so I'd suggest moving to the azurerm_web_app_hybrid_connection resource instead.
If this is still an issue with the 3.x version of the provider for azurerm_web_app_hybrid_connection resource please do let us know by opening a new issue, thanks!
