### ISSUE TITLE
Support for Storage Table Service

### ISSUE THREAD

**Issue by yupwei68** [hashicorp/terraform-provider-azurerm#9208]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CORS is an HTTP feature that enables a web application running under one domain to access resources in another domain. 
Azure storage services support Cross-Origin Resource Sharing (CORS) for the Blob, Table, and Queue services.

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://docs.microsoft.com/en-us/rest/api/storageservices/set-table-service-properties
* https://docs.microsoft.com/en-us/rest/api/storageservices/cross-origin-resource-sharing--cors--support-for-the-azure-storage-services

**Comment by tombuildsstuff** [comment]
@yupwei68 when opening issues, can you describe the use-case/user problem being solved rather than just a link to an API Endpoint?

**Comment by tombuildsstuff** [comment]
Consolidating into https://github.com/hashicorp/terraform-provider-azurerm/issues/18714 since there's more information in that issue and this _appears_ to be a duplicate
