### ISSUE TITLE
Destroy azurerm_network_watcher_flow_log fails if storage account resource group lock is enabled

### ISSUE THREAD

**Issue by dduleep** [hashicorp/terraform-provider-azurerm#9226]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_2.35.0`
* `terraform.exe_0.13.5`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
  version = "=2.35.0"
}

Resource actions are indicated with the following symbols:
  - destroy

Terraform will perform the following actions:

  # azurerm_network_watcher_flow_log.nsg-flow-log[0] will be destroyed
  - resource "azurerm_network_watcher_flow_log" "nsg-flow-log" {
      - enabled                   = true -> null
      - id                        = "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/NetworkWatcherRG/providers/Microsoft.Network/networkWatchers/NetworkWatcher_westeurope/networkSecurityGroupId/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/network-rg/providers/Microsoft.Network/networkSecurityGroups/DemoSubnet-nsg" -> null
      - network_security_group_id = "/subscriptions/xxxxxxxxxxxxxxxxx/resourceGroups/network-rg/providers/Microsoft.Network/networkSecurityGroups/DemoSubnet-nsg" -> null
      - network_watcher_name      = "NetworkWatcher_westeurope" -> null
      - resource_group_name       = "NetworkWatcherRG" -> null
      - storage_account_id        = "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx/resourceGroups/storage-rg/providers/Microsoft.Storage/storageAccounts/mystorageaccount" -> null
      - version                   = 1 -> null

      - retention_policy {
          - days    = 7 -> null
          - enabled = true -> null
        }

      - traffic_analytics {
          - enabled               = false -> null
          - interval_in_minutes   = 60 -> null
          - workspace_id          = "cxxxxxxxxxxxxxxx" -> null
          - workspace_region      = "westeurope" -> null
          - workspace_resource_id = "/subscriptions/xxxxxxxxxxxxxxxxxxxxxx/resourcegroups/cloudopslab-rg/providers/microsoft.operationalinsights/workspaces/law" -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

### Panic Output
```Error: waiting for completion of disabling Flow Log Configuration for target "/subscriptions/xxxxxxxxxxxxxxxx/resourceGroups/xxxxxxxx-rg/providers/Microsoft.Network/networkSecurityGroups/DemoSubnet-nsg" (Network Watcher "NetworkWatcher_westeurope" / Resource Group "NetworkWatcherRG"): Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=409 -- Original Error: Code="ScopeLocked" Message="The scope '/subscriptions/xxxxxxxxxxxxxxxxxxxx/resourceGroups/storage-rg/providers/Microsoft.Storage/storageAccounts/mystorageaccount/managementPolicies/default' cannot perform delete operation because following scope(s) are locked: '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/storage-rg'. Please remove the lock and try again." Details=[]```

### Expected Behavior

Since there is no deletion happen on the storage account, destroy of azurerm_network_watcher_flow_log need to be successes 

### Actual Behavior
azurerm_network_watcher_flow_log  resources does not delete

### Steps to Reproduce
1. create storage-rg and enable the resource prevention lock-in resource group
2. create storage account as abcxxx01 inside storage-rg resource group.
3. link abcxxx01 with azurerm_network_watcher_flow_log and create the azurerm_network_watcher_flow_log resource
3. delete the azurerm_network_watcher_flow_log

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems you added a lock on the resource group level at step 1. I assume you have to remove the lock first before destroying the resources in this resource group.

**Comment by dduleep** [comment]
@neil-yechenwei Thank you for your reply on the issue
1. I'm going to delete `azurerm_network_watcher_flow_log` in `NetworkWatcherRG` resource group, not the storage account. The storage account refer as data
`cannot perform delete operation because following scope(s) are locked: '/subscriptions/xxxxxxxxxxxxxxxxxx/resourceGroups/storage-rg'. Please remove the lock and try again."`
