### ISSUE TITLE
azurerm_app_service resource does not behave as expected on some outputs

### ISSUE THREAD

**Issue by Justin-DynamicD** [hashicorp/terraform-provider-azurerm#9255]
First off, I appologize if this is a Terraform error and not a error with the resource in question, this resource just happens to be the only place Ive seen it happen.

**TLDR: when referencing the principal_id after a change, dependant resources may fail.**

Terraform 0.13.4 & 0.13.5 tested.

I am demoing this with the for_each flag as I used this when discovering the issue, and do not know if it is related.

```
provider azurerm {
  features{}
}

resource "azurerm_resource_group" "main" {
  name     = "example"
  location = "West US 2"
}

locals {
  services = ["app", "svc", "auth-svc"]
}

resource "azurerm_app_service_plan" "app" {
  name                = "example-app"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  kind                = "App"
  sku  {
    tier              = "Basic"
    size              = "B1"
    capacity          = 1
  }
}

resource "azurerm_app_service" "main" {
  for_each            = toset(local.services)
  name                = "example-${each.value}"
  location            = azurerm_app_service_plan.app.location
  resource_group_name = azurerm_app_service_plan.app.resource_group_name
  app_service_plan_id = azurerm_app_service_plan.app.id
  https_only          = true
  site_config {
    always_on                = false
    dotnet_framework_version = "v4.0"
    ftps_state               = "AllAllowed"
    scm_type                 = "VSTSRM"
  }
  identity {
    type = "SystemAssigned"
  }
}

output "test-identity" {
  value = azurerm_app_service.main["app"].identity[0].principal_id
}
```

1. run `terraform apply`
2. someone manually toggles the identity to off in the example-app service (controlled by identity {})
3. re-run `terraform plan`

**What I would expect**:
Terraform to identify that the "identity" needs to be enabled and that the output is set to "known after update"

**What occurs**:
Terraform returns an error:

```
Error: Invalid index
  azurerm_app_service.main["app"].identity is empty list of object
```

Essentially as the existing object doesnt have this entry yet, the plan fails instead of simply stating it will eventually know the values.

**Comment by rcskosir** [comment]
Thanks for opening this issue. azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
