### ISSUE TITLE
azurerm_app_service_certificate not setting hosting_environment_profile_id

### ISSUE THREAD

**Issue by tgwallenborg** [hashicorp/terraform-provider-azurerm#9268]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.32.0

### Affected Resource(s)

* `azurerm_app_service_certificate`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate" "app_cert" {
  name                           = "our-domain"
  resource_group_name            = "rg-test1-euw"
  location                       = "westeurope"
  hosting_environment_profile_id = azurerm_app_service_environment.ase.id
  key_vault_secret_id            = azurerm_key_vault_certificate.tls.secret_id
}
```

### Expected Behaviour

A certificate is created that is possible to use in my App Service hosted in App Service Environment

### Actual Behaviour

The certificate is created but is not accessible from the App Service.
Its not showing in the Private Certificate list and I get:
`"Code":"NotFound","ExtendedCode":"04031","Message":"Certificate CORRECT-THUMBPRINT was not found."` 
When trying to add a `custom_hostname_binding`.
Running `terraform state show azurerm_app_service_certificate.app_cert` shows a correct `hosting_environment_profile_id`

I _think_ the error is here
When checking the change history for the certificate both `hostingEnvironment` and `hostingEnvironmentProfile` is null:
```json
{
	"id": "/subscriptions/XXXX/resourcegroups/rg-test1-euw/providers/microsoft.web/certificates/our-domain-net",
	"name": "our-domain-net",
	"type": "microsoft.web/certificates",
	"location": "westeurope",
	"tags": {},
	"kind": "",
	"sku": "",
	"plan": "",
	"managedBy": "",
	"properties": {
		"cerBlob": null,
		"expirationDate": "2022-11-11T07:21:23.0000000Z",
		"friendlyName": "",
		"hostingEnvironment": null,
		"hostingEnvironmentProfile": null,
		"hostNames": [
			"our.domain.net"
		],
		"issueDate": "2020-11-11T07:21:23.0000000Z",
		"issuer": "Issuing CA Device V3",
		"keyVaultId": "/subscriptions/XXXX/resourcegroups/rg-test1-euw/providers/microsoft.keyvault/vaults/XXXX",
		"keyVaultSecretName": "our-domain-secret",
		"keyVaultSecretStatus": "Initialized",
		"password": null,
		"pfxBlob": null,
		"publicKeyHash": null,
		"selfLink": null,
		"serverFarmId": null,
		"siteName": null,
		"subjectName": "our.domain.net",
		"tags": {},
		"thumbprint": "CORRECT-THUMBPRINT",
		"toDelete": null,
		"valid": null,
		"webSpace": "rg-test1-euw-WestEuropewebspace"
	}
}
```

### Steps to Reproduce
1. Create Internal App Service Environment
2. Create App Service inside the App Service Environment
3. Create Key Vault with a certification
4. Create azurerm_app_service_certificate
5. Try use the certificate in the App Service

### Important Factoids

The App Service Environment is an internal one with a "Isolated" App Service.
The certificate is an internally signed one.

**Comment by JBlandHV** [comment]
I also have hit this issue, I can see the certificate is created in the Azure Resource Explorer but the hostingEnvironmentProfile is not set even though I am setting it in the Terraform.

**Comment by jonathaneckman** [comment]
This issue also occurs in an App Service (not ASE) where hosting_environment_profile_id is not used.

**Comment by JBlandHV** [comment]
> This issue also occurs in an App Service (not ASE) where hosting_environment_profile_id is not used.

Do not think you can apply a self signed certificate when using a normal App Service and not an ASE as MS do not allow that on shared infrastructure. It is allowed on an ASE as it's not shared so they allow you to modify the root certificates.

Of course this isn't working in Terraform, I've had to drop to a null resource for this one step which is working fine but would be good if this was fixed at some point.

**Comment by DanielBMann9000** [comment]
I am seeing the same behavior. Terraform state contains the `hosting_environment_profile_id` field, but the certificate within the Azure resource explorer shows a `hostingEnvironmentProfile` block that's null. A certificate imported manually through the portal shows a block with several properties:

```
    "hostingEnvironment": null,
    "hostingEnvironmentProfile": {
      "id": "/subscriptions/xxx/resourceGroups/yyy/providers/Microsoft.Web/hostingEnvironments/my-ase-name",
      "name": "my-ase-name",
      "type": "Microsoft.Web/hostingEnvironments"
    },
```

**Comment by jarekmisz** [comment]
This issue still persists. I'm using provider version 2.47.0. 
Symptoms are the same as in the previous posts. The certificate gets created but certificate binding fails.

**Comment by JBlandHV** [comment]
Any chance of some progress on this? It's been broken for a long time.

**Comment by adamyager** [comment]
yes. Agreed here, would love to see some assistance here. Breaks a key automaton for many customers.

**Comment by katbyte** [comment]
I am going to close this because the `azurerm_app_service ` has been superseded by the `azurerm_linux_web_app` and `azurerm_windows_web_app` resources.

If this is still an issue with `v3.x` of the provider and the new resources do let us know by opening a new issue, thanks!
