### ISSUE TITLE
Support for disabling basic auth access to the SCM site

### ISSUE THREAD

**Issue by jmcshane** [hashicorp/terraform-provider-azurerm#9290]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some organizations require that access to the app service via a generated username/password be disabled and all access go through Azure AD RBAC. Allow app services to disable webdeploy and scm for app services: https://docs.microsoft.com/en-us/azure/app-service/deploy-configure-credentials#webdeploy-and-scm

This should operate in the same way that ftp is disabled in #2651.

### New or Affected Resource(s)

* azurerm_app_service

### Potential Terraform Configuration

```hcl
azurerm_app_service {
  site_config {
    web_deploy = "Disabled"
  }
}
```

### References

* https://docs.microsoft.com/en-us/azure/app-service/deploy-configure-credentials#webdeploy-and-scm

**Comment by byteknacker** [comment]
Hello, I definitely need this feature for my work. Is there an update on it?

**Comment by yesoos** [comment]
Same here - for the new modules especially:

azurerm_linux_web_app and azurerm_windows_web_app
