### ISSUE TITLE
Import Image ignores OS Disk and Zone Resilient properties

### ISSUE THREAD

**Issue by inoreip** [hashicorp/terraform-provider-azurerm#9306]
Hi

When importing an existing Azure Image in to the Terraform state ([as documented here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/image#import)) the following properties are ignored and therefore the state does not match what is deployed. This of course results in the next plan/apply wanting to redeploy the image.

Missing properties:

- os_disk
- zone_resilient

Versions:
Terraform: v0.13.5
Provider: azurerm 2.36.0 (also verified in as not working in 2.23.0)
Command: azurerm_image

EDIT
-----

I have tracked it down to this line [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/7da0a5a60168e56e388d799dca807fcf07f700af/azurerm/internal/services/compute/image_resource.go#L304). Basically there is a check with a comment:

"either source VM or storage profile can be specified, but not both"

However the image in Azure has both. The image was created from an existing VM using the capture method, which is pretty standard. The original VM no longer exists, however the image still has a resource reference to it.

Thank you very much.

Regards.

**Comment by jessecureton** [comment]
Hi! Chiming in to add another voice here. This is reproducible by creating an image with Packer (for instance following any of the basic [examples](https://www.packer.io/docs/builders/azure/arm)), then attempting to `terraform import` the created image. The `zone_resilient` property post-import is set to `null` in the state, which means on the next plan it proposes to tear down and recreate the resource.

You can work around this by doing a few manual `terraform state {pull/push}` operations, but that's riskier than I'd like to push users to do. You could also just use a terraform data source to reference the packer image, but that means the image's lifecycle can't be managed by Terraform and it then can get lost in large cloud accounts that are driven primarily by Terrafrom automation.

It'd be nice to get a fix such that the `zone_resilient` property is set appropriately on import!

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
