### ISSUE TITLE
plan fail after massive dns import

### ISSUE THREAD

**Issue by fumaluca** [hashicorp/terraform-provider-azurerm#9339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.36.0
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.3
+ provider registry.terraform.io/mongodb/mongodbatlas v0.7.0

### Affected Resource(s)

* terraform state
* terraform import
* azurerm_dns_cname_record

### Terraform Configuration Files

```hcl
resource "azurerm_dns_cname_record" "cname" {
  name                = var.cname_name
  zone_name           = var.dns_zone_name
  resource_group_name = var.dns_zone_rg
  ttl                 = var.cname_ttl 
  record              = var.cname_record
}
```
1000x
```
module "cname" {
  source                  = "../modules/dns/cname"
  dns_zone_rg             = module.agyo_dns_rg.dns_zone_rg
  dns_zone_name           = module.agyo_dns_zone.dns_zone_name
  cname_ttl               = var.cname_ttl
  cname_record            = "cname_record"
  cname_name              = "name"
}
```
### Debug Output

```
Error: Error retrieving CNAME Record connection-updater-dev (DNS Zone "customdns.io" / Resource Group "operation"): dns.RecordSetsClient#Get: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded
```

### Expected Behaviour

I've added a module dedicated to dns zone and cname to my terraform.
After that i've imported ~1000 existing cname.
The import of existing resources was made step by step and every time i've checked that terraform plan doesn't have any changes to do.

I would like to import all the dns zone, cname, A record, ....(step by step all azure resources) and start managing it with terraform.
Terraform/AzureRM be able to create a plan.

### Actual Behaviour

I run `terraform plan -out=$PLAN` from different machines, changed parallelism (1,2,10) also set TF_LOG=DEBUG
Everytime i try to run `terraform plan -out=$PLAN` it doesn't be able to create a plan and exit with this error.
```
Error: Error retrieving CNAME Record connection-updater-dev (DNS Zone "customdns.io" / Resource Group "operation"): dns.RecordSetsClient#Get: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

*`terraform state list` return 987 element (not only cname, also aks, network, sql, storage ...)
* all cname is pre-existing resources in azure, other resources was created with terraform and work fine
* some cname was imported and the plan returned a successful  plan
* tried with different parallelism parameter but no changes
* tried to plan from Azure VM, gitlab hosted on AWS and my laptop.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
