### ISSUE TITLE
Support for additional client_cert_enabled values in app_service

### ISSUE THREAD

**Issue by JamesCarscadden** [hashicorp/terraform-provider-azurerm#9343]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

azurerm_app_service argument client_cert_enabled is currently a boolean value, however in the azure app service this configuration has three possible values -> require, allow and ignore. The current boolean values maps only to "require" (for true) or "ignore" (for false).

Propose updating this argument to accept the string values for "Require", "Allow" or "Ignore" so that each possibility can be properly set.

In addition, while this is a valid configuration item for an Azure function app, this setting does not exist in the azurerm_function_app provider. Propose adding this configuration item.

### New or Affected Resource(s)

* azurerm_app_service
* azurerm_function_app

### Potential Terraform Configuration

resource "azurerm_app_service" "myapp" {
    ....
    client_cert_enabled = "Allow"
}

similarly for azurerm_function_app.

Possibly should be renamed from "client_cert_enabled" (implying a boolean value), to "client_cert_mode" as presented in the azure portal.

**Comment by CaptainStealthy** [comment]
Partially covered by #7849 - I found a temporary workaround for this by using the Azure CLI, and posted a snippet in that thread.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/7849#issuecomment-827745718

**Comment by favoretti** [comment]
Thank you for opening this issue. Closing in favor of #7849 to keep the discussion concise.
