### ISSUE TITLE
Support for granular alert conditon when setting resource health alert with terraform

### ISSUE THREAD

**Issue by theasphaltworld** [hashicorp/terraform-provider-azurerm#9391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Terraform lacks of ability to further set alert conditions for resource health alert

### New or Affected Resource(s)

azurerm_monitor_activity_log_alert

### Potential Terraform Configuration

```hcl
resource "azurerm_monitor_activity_log_alert" "resourcehealth" {
  name                = " Resource Health Alert"
  description         = "Resource Health Alerts"
  resource_group_name = var.resource_group_name
  scopes              = [var.scopes]
  criteria {
    category = "ResourceHealth"
  }
 alert_condition{
   Event_status =["active", "in progress", "resolved","updated" ]
    current_resource_status=["available","degraded","unavailable","unknown"]
    previous_resource_status=["available","degraded","unavailable","unknown"]
    reason_type=["platform initiated", "user initiated"]
}

  action {
    action_group_id = var.action_group_id
  }
  tags = var.tags
}
```

### References

* #0000

**Comment by theasphaltworld** [comment]
i found it's lack of ability to further set granual alert condition, like we only want alerted on when current resource status is degraded or unavailable, and reson type is platform initiated. Terraform seems to be giving all to all the conditions.
without this alert can be very noisy

**Comment by jdheyburn** [comment]
Looks like this ticket is asking for the equivalent for what #10978 does for `ServiceHealth`.

**Comment by michaelelleby** [comment]
Any status on this issue, since #10978 has implemented now?

**Comment by JamesDLD** [comment]
Just faced the same issue when I tried to configure my alerts on a VPN Connection (Azure resource type 'Microsoft.Network/Connections'). Thanks.
