### ISSUE TITLE
Failed enabling NSG flow log due to "Invalid provisioning state" on NSG "Updating"

### ISSUE THREAD

**Issue by zumic96** [hashicorp/terraform-provider-azurerm#9395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.3
Provider: latest

### Affected Resource(s)

* `azurerm_network_watcher_flow_log`

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "nsg" {
  name = var.nsg_name

  location            = var.region
  resource_group_name = var.resource_group_name
  tags                = var.tags
}

data "azurerm_storage_account" "storage_account" {
  name                 = var.flow_storage_acc_name
  resource_group_name  = var.resource_group_name
}

resource "azurerm_network_watcher_flow_log" "nsg_flow_log" {
  network_watcher_name = var.network_watcher_name
  resource_group_name  = var.resource_group_name

  network_security_group_id = azurerm_network_security_group.nsg.id
  storage_account_id        = data.azurerm_storage_account.storage_account.id
  enabled                   = true

  retention_policy {
    enabled = false
    days = 0
  }
}
```

### Debug Output

Error: Error setting Flow Log Configuration for target "..../providers/Microsoft.Network/networkSecurityGroups/example-nsg" (Network Watcher "example_network_watcher" / Resource Group "rg-example-1"): network.WatchersClient#SetFlowLogConfiguration: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidProvisioningStateForTargetResource" Message="Invalid provisioning state for target resource ..../providers/Microsoft.Network/networkSecurityGroups/example-nsg. The provisioning state is Updating." Details=[]

  on .terraform/modules/vm.security_group/10-main.tf line 25, in resource "azurerm_network_watcher_flow_log" "nsg_flow_log":
  25: resource "azurerm_network_watcher_flow_log" "nsg_flow_log" {

### Expected Behaviour

Terraform should have waited for NSG to be in ready state and then update flow_log settings or do a retry if state is updating.

### Actual Behaviour

Terraform thrown error that state is Updating and I had to run plan/apply again to finish provisioning.

### Steps to Reproduce

Create NSG and enable flow logs.

### Important Factoids

It is not consistent behavior, when it happens it breaks automated provisioning of VMs since apply isn't successfull.

**Comment by dtoes** [comment]
Same issue here. 

depends_on = azurerm_network_security_group.nsg also not working. Still get the same error message that the provisioning state is updating.

**Comment by jackofallops** [comment]
Hi @zumic96 
Do you have any Azure side configuration that might be making change to your deployed NSG's (via policies etc) at creation time?  The provider waits for a completion message from Azure before marking the resource created, and there's locking around it internally to prevent the provider trying to make more than one change at once.

**Comment by zumic96** [comment]
Hi,
No config from Azure side, like policies or simmilar. Things that could influence this is that in same step when creating NSG Flow I am also adding bunch of rules to NSG is created but seems like adding rules leaves it in Updating state for some time and then I get this error message. If I run apply again after 1-2 min it goes ok.

Since I have specific needs for NSG rules I can't put time_sleep resource since depending on config not all rules from module are added. I tried adding it to ASG because it was usually created between NSG rules and Flow Logs but it's janky solution.

Alsto noticed same problem when doing destroy action, seems like NSG is updating since all rules are being removed and then it fails to disable Flow Logs, there I didn't try to find correct place for time_sleep resource as I think it's not good solution using it for this.

**Comment by Tenseiga** [comment]
+ 1 I am also getting the error. :(

**Comment by nishantsondhi16** [comment]
Facing the similar issue.
Wondering if someone in the community has tried adding a sleep in the resource, and around how much time of sleep is best as a workaround for this.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem pre-3.x version of the provider which are no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
