### ISSUE TITLE
azurerm_monitor_action_group.itsm_receiver type or validation type issue

### ISSUE THREAD

**Issue by defadmindef** [hashicorp/terraform-provider-azurerm#9405]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5

### Affected Resource(s)

source  = "hashicorp/azurerm"
version = "~> 2.35"

### Terraform Configuration Files
resource "azurerm_monitor_action_group" "default_action_group" {
    name                = "default_action_group"
    short_name          = "default"
    resource_group_name = data.azurerm_resource_group.rg.name

    itsm_receiver {
        name = "itsm_create_event"
        connection_id = "12345678-fedc-fedc-fdec-123456789012"
        region = data.azurerm_resource_group.rg.location

        workspace_id = data.azurerm_log_analytics_workspace.workspace.workspace_id
        //workspace_id = "12345678-abcd-abcd-abcd-123456789012|12345678-dcba-dcba-dcba-098765432109"

	ticket_configuration = "{\"PayloadRevision\":2,\"WorkItemType\":\"Event\",\"UseTemplate\":false,\"WorkItemData\":\"{\\\"severity\\\":\\\"1\\\",\\\"event_class\\\":\\\"Azure\\\"}\",\"CreateOneWIPerCI\":true,\"CreateOneWIPerLog\":false}"
    }
}

### Expected Behaviour

When I run terraform with the example code, it creates the action group, but the ITSM Ticket in the portal is empty.  Through testing and with Microsofts help we have found that the difference between a portal created action group and a terraform created action group is the lack of a subscription id in the itsm_receiver.workspace_id section.

In the resource explorer it shows the "workspace_id" with a UUID (subscription_id) then a PIPE then another UUID (workspace_id).  It strongly appears that the workspace_id should be the "subscription_id|workspace_id".  However if I enter that, terraform complains that the workspace_id needs to be a valid UUID.

**Error: expected "itsm_receiver.0.workspace_id" to be a valid UUID, got 12345678-abcd-abcd-abcd-123456789012|12345678-dcba-dcba-dcba-098765432109**

In the monitor_action_group_resource.go lines 93-97 it says the workspace_id is a string, but the validatefunc is expecting UUID.  It either needs a multiple UUID separated by a PIPE or needs to validate as a string so the two uuid's separated by a | is allowed.
						**"workspace_id": {
							Type:         schema.TypeString,
							Required:     true,
							ValidateFunc: validation.IsUUID,
						},**

### Actual Behaviour
**Error: expected "itsm_receiver.0.workspace_id" to be a valid UUID, got 12345678-abcd-abcd-abcd-123456789012|12345678-dcba-dcba-dcba-098765432109**

### Steps to Reproduce
in the terraform example above use this
workspace_id = "12345678-abcd-abcd-abcd-123456789012|12345678-dcba-dcba-dcba-098765432109"

If I knew the Go language I might offer a pull request, but I don't - sorry.

**Comment by sinbai** [comment]
@defadmindef thanks for opening this issue. Re "_When I run terraform with the example code, it creates the action group, but the ITSM Ticket in the portal is empty_." I would like to confirm that the "ITSM Ticket " means "createorupdateticket" in the screenshot below in Azure portal? If yes, I could not reproduce this issue. Also, I would like to confirm that the azurerm_monitor_action_group and azurerm_log_analytics_workspace resources are created in different subscriptions in your use-case?

> ![image](https://user-images.githubusercontent.com/39109137/153841578-3173bed5-29ed-4f45-87bf-ff03e47db059.png)

**Comment by defadmindef** [comment]
I cannot see your comment in github, so I'm replying to this email.  It has
been a year and a half since I submitted this, and so the details are not
as clear as they were.

Re-reading over my original post I don't believe the "name" is what I was
referring to.  Terraform was complaining that it was expecting a UUID type,
but Azure is expecting a string with one or more UUID's separated by a pipe
sign.
*Error: expected "itsm_receiver.0.workspace_id" to be a valid UUID, got
12345678-abcd-abcd-abcd-123456789012|12345678-dcba-dcba-dcba-098765432109*
