### ISSUE TITLE
Azure Function App Missing Startup Command

### ISSUE THREAD

**Issue by Japeth** [hashicorp/terraform-provider-azurerm#9427]
So I'm trying to deploy an Azure Function app that runs off of a customized container stored in an Azure Container Registry.

I can successfully set the app settings linux_fx_version to pull the docker image, as well as using DOCKER_ENABLE_CI, DOCKER_REGISTRY_SERVER_URL, DOCKER_REGISTRY_SERVER_USERNAME, and DOCKER_REGISTRY_SERVER_PASSWORD.

However, I've noticed that in azurerm_function_app, there is _no_ setting for app_command_line under site_config.  The resource azurerm_app_service _does_ contain this setting however.  Unfortunately, without this startup command, the function app doesn't know how to start.  Could we get this added to the azurerm_function_app so users can specify a startup command/file ?

**Comment by rcskosir** [comment]
Thanks for opening this issue. The azurerm_function_app resource is deprecated in version 3. 0 and will be removed in version 4.0 - so I'd suggest moving to the azurerm_linux_function_app and azurerm_windows_function_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_function_app and azurerm_windows_function_app resources please do let us know by opening a new issue, thanks!
