### ISSUE TITLE
Support for System Managed Identity in Event Grid Domain and Event Grid Topic 

### ISSUE THREAD

**Issue by piotrgwiazda** [hashicorp/terraform-provider-azurerm#9525]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please enable support for Managed Identity for Event Grid Domain and Event Grid Topic for event delivery as described in https://docs.microsoft.com/en-us/azure/event-grid/managed-service-identity

### New or Affected Resource(s)

* azurerm_eventgrid_topic
* azurerm_eventgrid_domain

### Potential Terraform Configuration

Just follow the standard pattern to enable system identity and read from output properties.

```hcl
  identity {
    type = "SystemAssigned"
  }
```

### References

* #0000

**Comment by marcin-dudek** [comment]
I will be happy to contribute this one. Seems this has not been released in 2.55.0.

**Comment by javier-moreno-h** [comment]
I think it would be a good idea to add identities support for **_azurerm_eventgrid_system_topic_** too. Thanks.

**Comment by wbreza** [comment]
Any update for when this feature will be available?
