### ISSUE TITLE
Support for system assigned identity for dead-lettering in Event Grid Subscription

### ISSUE THREAD

**Issue by piotrgwiazda** [hashicorp/terraform-provider-azurerm#9526]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for system assigned identity for dead-lettering in Event Grid Subscription

### New or Affected Resource(s)

* azurerm_eventgrid_event_subscription

### Potential Terraform Configuration

```hcl
resource "azurerm_eventgrid_event_subscription" "sample_topic_subscription" {
  name  = "example"
  scope = azurerm_eventgrid_domain_topic.sample.id

  # ...removed...

  storage_blob_dead_letter_destination {
    storage_account_id = azurerm_storage_account.example.id
    storage_blob_container_name = azurerm_storage_container.example.name

    # A new flag needed here, example:
    use_system_assigned_identity = true
  }
  
}
```

### References

* #0000

**Comment by jrauschenbusch** [comment]
@piotrgwiazda I've started with an implementation for it. But as there could be more dead letter destinations within the future, i decided to hoist the identity configuration:

```tf
resource "azurerm_eventgrid_event_subscription" "example" {
  
  name  = "example"
  scope = azurerm_eventgrid_domain_topic.example.id

  # ...removed...

  delivery_identity {
     type = "SystemAssigned" # Allowed values are: "SystemAssigned" or "UserAssigned" 
     user_assigned_identity_id = "<object_id>" # Required when type is "UserAssigned", else obsolete
  }

  dead_letter_identity {
     type = "SystemAssigned" # Allowed values are: "SystemAssigned" or "UserAssigned" 
     user_assigned_identity_id = "<object_id>"  # Required when type is "UserAssigned", else obsolete
  }
  
}
```

As you can see i'll also include support for delivery identity.

**Comment by tohov** [comment]
Any estimated schedule for this feature?

**Comment by jrauschenbusch** [comment]
Hi @tohov . As you can see, the PR was opened last year. It's up to the Terraform AzureRM provider team to review it. Unfortunately it seems, that one can actively ask for a review, but nothing happens.

**Comment by tohov** [comment]
Hi! I'm quite new to GitHub issues so not aware of all the standard procedures. Thanks for understanding. And also thank you for trying to get this one resolved. 

I noticed that running the tf config that does not have the identity declared will of course remove the selection of using the system assigned identity made by hand to the resource. So if the resource is deployed by tf you cannot use resource identity unless you taint the resource or do some other temporary hacks to not touch the resource while still adding/running other configs.
