### ISSUE TITLE
azurerm_function_app WEBSITE_CONTENTSHARE app_settings always shown as changed

### ISSUE THREAD

**Issue by peteneville** [hashicorp/terraform-provider-azurerm#9536]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/-/azuread v1.1.1
+ provider registry.terraform.io/-/azurerm v2.38.0
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource "azurerm_function_app" "analytics_app" {
  name                       = "${local.shared.environment}-${local.shared.location_short}-analytics-app"
  location                   = local.shared.location 
  resource_group_name        = local.shared.resource_group_name_windows
  app_service_plan_id        = azurerm_app_service_plan.plan_analytics.id
  storage_account_name       = azurerm_storage_account.analytics_app.name
  storage_account_access_key = azurerm_storage_account.analytics_app.primary_access_key
  https_only                 = true
  client_affinity_enabled    = false
  enabled                    = true 
  version                    = var.functions_extension_version
  tags = local.tags
  
  site_config {
    always_on                  = "true"
    websockets_enabled         = false
    ftps_state                 = "AllAllowed"
    use_32_bit_worker_process  = true
  }
  identity {
     type = "SystemAssigned"
  }  
  app_settings = merge(
    local.shared.app_settings_windows,
    {
      WEBSITE_CONTENTAZUREFILECONNECTIONSTRING = azurerm_storage_account.analytics_app.primary_connection_string
      WEBSITE_CONTENTSHARE                     = azurerm_storage_share.analytics_app_file_share.name
  })

}




locals {
  ...
    app_settings_windows = {
      APPINSIGHTS_INSTRUMENTATIONKEY  = data.azurerm_application_insights.main.instrumentation_key
      WEBSITE_TIME_ZONE               = "GMT Standard Time"
      WEBSITE_ENABLE_SYNC_UPDATE_SITE = "true"
      WEBSITE_RUN_FROM_PACKAGE        = "1"
    }
   
  } 
}
```

### Debug Output
None available

### Panic Output

None available
### Expected Behaviour

Running plan with azurerm_function_app and app_settings  that include WEBSITE_CONTENTSHARE, we expect state to be maintained and change detection only if changed when we run a plan. 

### Actual Behaviour

We always get WEBSITE_CONTENTSHARE detected as a change even though the value is already present and the same.
This setting is never added to the state file, whilst other app settings are.

Is this a bug please?

### Steps to Reproduce

1. `terraform plan`

**Comment by peteneville** [comment]
Also worth noting that adding a lifecyle to ignore these isn't working for me:
`  lifecycle {
      ignore_changes = [
          app_settings["WEBSITE_CONTENTSHARE"],
          app_settings["WEBSITE_CONTENTAZUREFILECONNECTIONSTRING"]
    ]
  }`

**Comment by Fnatte** [comment]
I don't know the inner workings of this, but it seems like https://github.com/terraform-providers/terraform-provider-azurerm/commit/f9659d61ad826a133095e8cc38a3195c29ee555e might be related?

**Comment by peteneville** [comment]
Thank you - definitely looks similar, but I do not understand yet why this fix doesn't help.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
