### ISSUE TITLE
Can't add certificate to App Service with multiple WebSpaces

### ISSUE THREAD

**Issue by andydkelly-ig** [hashicorp/terraform-provider-azurerm#9556]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform - latest
AzureRM Provider - latest

### Affected Resource(s)

* `azurerm_app_service_certificate`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service_certificate" "test" {
  name                = "test"
  resource_group_name = "rgTest"
  location            = "North Central US"
  key_vault_secret_id = "var.certId"
  hosting_environment_profile_id = "/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Web/hostingEnvironments/<ase-name>"
}
```

### Expected Behaviour

I opened issue 7756 as i have App Services that had moved resource groups in their life and therefore have multiple webspaces. When creating a certificate, it puts it into the original webspace which makes it inaccessible by the App Service. Adding the cert through the UI doesn't do this and puts it in the correct webspace. Issue #7756 was closed as it was stated this functionality was available as part of the `hosting_environment_profile_id` field, but this doesn't seem to be the case unless I am missing something. This field is only for App Service environments - if I am using this wrong for this purpose please let me know, but i cannot see how to secet an App Service Webspace using this field. As a consequence i am having to add my certificate to my app service through the GUI which is breaking our process. 

### Actual Behaviour

The field doesn't accept a mapping to the webspace and is designed for App Service environments.

### Steps to Reproduce

1. `terraform apply`

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/7756
https://github.com/terraform-providers/terraform-provider-azurerm/issues/5115

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. azurerm_app_service resource is deprecated and will be removed in v4.0 - so I'd suggest moving to the azurerm_linux_web_app and azurerm_windows_web_app resources instead.
If this is still an issue with the 3.x version of the provider for azurerm_linux_web_app and azurerm_windows_web_app resources please do let us know by opening a new issue, thanks!
