### ISSUE TITLE
Storage directory creation error for ".ssh" subdirectory

### ISSUE THREAD

**Issue by tomatwoodliquidx** [hashicorp/terraform-provider-azurerm#9608]
Using:
- Terraform v0.13.5
- Azurerm provider v2.38.0

When attempting to create file share directory "sftp/client1/.ssh/keys", the azurerm_storage_directory resource incorrectly states "Error: name must contain only uppercase and lowercase alphanumeric characters, numbers and hyphens, and can be nested multiple levels".  Please note the Azure portal allows for the creation of the ".ssh" subdirectory without issues.

Example code screenshots included.

Error:
![image](https://user-images.githubusercontent.com/60616518/100786778-9d51b280-33e0-11eb-9b11-b07137a3585e.png)

Example code:
![image](https://user-images.githubusercontent.com/60616518/100786856-be1a0800-33e0-11eb-82f2-54aed30d109b.png)

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
