### ISSUE TITLE
azurerm_monitor_action_group can't use dynamic array of email receivers

### ISSUE THREAD

**Issue by markti** [hashicorp/terraform-provider-azurerm#9614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.37.0

### Affected Resource(s)

* `azurerm_monitor_action_group`

### Terraform Configuration Files

```hcl
resource "azurerm_monitor_action_group" "action_group" {

  resource_group_name = var.context.resource_group_name
  
  name                = var.service_settings.name
  short_name          = var.service_settings.short_name


  dynamic "email_receiver" {
    for_each = var.service_settings.subscribers
      content {
        
        name                    = name
        email_address           = email
        use_common_alert_schema = true

      }
  }

}
```

variables file:
```hcl
variable "service_settings" {
  type = object({

    name       = string
    short_name = string
    
    subscriber_name = string
    subscriber_email = string

    subscribers = list(object({
      name  = string
      email = string
    }))

  })
}
```

### Panic Output

"Error: Invalid reference: A reference to a resource type must be followed by at least one attribute access, specifying the resource name."

### Expected Behaviour

It should provision multiple "email_receiver" blocks.

### Actual Behaviour

It fails throwing a strange error.

### Steps to Reproduce

1. try and provision an action group with a list of objects
2. `terraform apply`

**Comment by Dice-Jad** [comment]
Hi @markti, I have managed to get this to work using the terraform lookup function within the dynamic block, try the following:

```terraform
resource "azurerm_monitor_action_group" "action_group" {

  resource_group_name = var.context.resource_group_name
  
  name                = var.service_settings.name
  short_name          = var.service_settings.short_name


  dynamic "email_receiver" {
    for_each = var.service_settings.subscribers
      content {
        
        name                    = lookup(email_receiver.value, "name", null)
        email_address           = lookup(email_receiver.value, "email", null)
        use_common_alert_schema = true

      }
  }

}
```

**Comment by katbyte** [comment]
@markti - can you try @Dice-Jad's suggestion and let us know if this is still an issue?

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
