### ISSUE TITLE
unmarshal error when destroying resource from azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by giraudeo** [hashicorp/terraform-provider-azurerm#9629]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

tried with Terraform v0.13.4 and v0.13.5
AzureRM version 2.38.0

### Affected Resource(s)

* `azurerm_resource_group_template_deployment`
* `Azure Action Rule`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_subscription" "current" {}

locals {

  region = "westeurope"

  tags = {
    owner = "owner"
  }

  resource_group_name = "rsg-haint-weu1-d-001"

  subscription_id = data.azurerm_subscription.current.subscription_id
  subscription_name = data.azurerm_subscription.current.display_name

  actiongroups_list = {
      acg-hatest1 = {
          short_name = "acg-hatest1",
          email_addresses = {
            "email1"= {
              email_name = "email name",
              email_address = "my.email@xxx.xx"
            }
          }
      }
  }

  actiongroup_name = "acg-hatest1"

  alert_region = [
      "East US",
      "Central US",
      "Global"
  ]

  alert_severity_acr_notify = [
      "Sev0",
      "Sev1"
  ]

  rha_suffix_acr_notify = "sev01"

}


resource "azurerm_resource_group" "rsg" {
  name     = local.resource_group_name
  location = local.region

  tags = local.tags
}

resource "azurerm_monitor_action_group" "acg" {

    name = local.actiongroup_name
    resource_group_name = azurerm_resource_group.rsg.name
    short_name = local.actiongroup_name

    dynamic "email_receiver" {
        for_each = local.actiongroups_list["acg-hatest1"].email_addresses
        content {
            name = email_receiver.value.email_name
            email_address = email_receiver.value.email_address
            use_common_alert_schema = false
        }
    }

    tags = local.tags
}


resource "azurerm_resource_group_template_deployment" "terraform-arm-acr-notify" {
  depends_on = [azurerm_monitor_action_group.acg]
  name                = "terraform-arm-acr-notify"
  resource_group_name = azurerm_resource_group.rsg.name
  deployment_mode = "Incremental"
  template_content = file("arm/acr.json")

  parameters_content =  jsonencode({
        acr_name = {value = "rha_${local.subscription_name}_all_${local.rha_suffix_acr_notify}"},
        acg_uri = {value = "/subscriptions/${local.subscription_id}/resourcegroups/${local.resource_group_name}/providers/microsoft.insights/actiongroups/${local.actiongroup_name}"},
        alert_severity = {value = local.alert_severity_acr_notify}
  })
}
```

ARM available at:
https://gist.github.com/giraudeo/0a7e57eb24708a2ab0e2a08cf406a79d#file-acr-json

### Debug Output

https://gist.github.com/giraudeo/7f0f961e274aaf8229243fefe9acd080#file-terraform_log-txt

### Panic Output

no panic

### Expected Behaviour

Action Rule resource destroyed without error

### Actual Behaviour

Action Rule resource destroyed WITH error

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Important Factoids

The Action Rule is a Preview resource.
From the JSON file: 
            "type": "Microsoft.AlertsManagement/actionRules",
            "apiVersion": "2019-05-05-preview",

### References

I mention them, because the action is the same (destroy of a previsouly deployed ARM resource), but the error is different than mine:
* #9458 Resources created by azurerm_resource_group_template_deployment fail to be destroyed
* #9003 terraform destroy for resource azurerm_resource_group_template_deployment fails bug service/template

**Comment by giraudeo** [comment]
Hello,

Just to say I tried with Terraform 0.14.0 and AzureRM 2.39.0, I am getting the same error too.

Regards,

**Comment by julioas09** [comment]
Yeah, somethng is not working with action rules in ARM. I can create them without a problem but it fails with `failed to unmarshal response body: StatusCode=0 -- Original Error: json: cannot unmarshal bool into Go value of type map[string]interface {}
` on destroy.

**Comment by MarkKharitonov** [comment]
We have faced the same issue. Is there any update here?

**Comment by giraudeo** [comment]
Hello,

I tried today with Terraform 14.4, and AzureRM 2.43.0, still the same.
Is anything missing to consider it as a bug?

Regards,

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
