### ISSUE TITLE
Support for azurerm_key_vault_certificate 509v3 Basic Constraints CA and pathlen

### ISSUE THREAD

**Issue by mhennecke** [hashicorp/terraform-provider-azurerm#9634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The azurerm_key_vault_certificate resource lacks the option to create self-signed CA certificates. Please add the possibility to define the x509v3 basic constraint ca:true and/or pathlen:<some integer>

The Azure Portal UI, as well as az-cli, lacks this feature. However, the Key Vault REST API supports it. Please see the reference to the existing documentation bug.

### New or Affected Resource(s)

* azurerm_key_vault_certificate

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_certificate" "example" {
  name         = "generated-cert"
  key_vault_id = azurerm_key_vault.example.id

  certificate_policy {
    issuer_parameters {
      name = "Self"
    }

    key_properties {
      exportable = true
      key_size   = 2048
      key_type   = "RSA"
      reuse_key  = true
    }

    lifetime_action {
      action {
        action_type = "AutoRenew"
      }

      trigger {
        days_before_expiry = 30
      }
    }

    secret_properties {
      content_type = "application/x-pkcs12"
    }

    x509_certificate_properties {
      key_usage = [
        "cRLSign",
        "digitalSignature",
        "keyCertSign",
        "keyEncipherment",
      ]

      basic_constraints {
        ca = true
        path_len_constraint = 2
      }

      subject            = "CN=hello-world"
      validity_in_months = 12
    }
  }
}
```

### References

The key vault rest api for creating certificates supports basic constraints. However, this is undocumented and addressed: [azure-rest-api-specs #8295](https://github.com/Azure/azure-rest-api-specs/issues/8295)

I verified, that the following REST call, will generate a certificate with the requested basic_constraints:
```
POST https://<vault-name>.vault.azure.net/certificates/<cert-name>/create?api-version=7.1
Authorization: Bearer <token>
content-type: application/json

{
  "policy": {
    "key_props": {
      "exportable": true,
      "kty": "RSA",
      "key_size": 2048,
      "reuse_key": false
    },
    "secret_props": {
      "contentType": "application/x-pkcs12"
    },
    "x509_props": {
      "subject": "CN=somesubject.com",
      "sans": {
        "dns_names": [
          "somesubject.com"
        ]
      },
      "key_usage": [
        "cRLSign",
        "digitalSignature",
        "keyCertSign",
        "keyEncipherment"
      ],
      "basic_constraints": {
        "ca": true,
        "path_len_constraint": 3
      }
    },
    "issuer": {
      "name": "Self"
    }
  }
}
```

**Comment by jlichwa** [comment]
Duplicate - https://github.com/Azure/azure-rest-api-specs/issues/11962#issuecomment-827181465
#please-close

**Comment by etiennejournet** [comment]
> Not supported by service, feature request here- [Azure/azure-rest-api-specs#11962 (comment)](https://github.com/Azure/azure-rest-api-specs/issues/11962#issuecomment-827181465)
> #please-close

Not open to external contribution for the terraform provider then ?

**Comment by jlichwa** [comment]
> > Not supported by service, feature request here- [Azure/azure-rest-api-specs#11962 (comment)](https://github.com/Azure/azure-rest-api-specs/issues/11962#issuecomment-827181465)
> > #please-close
> 
> Not open to external contribution for the terraform provider then ?

Correct. At this moment it is for internal use only. We have it in our backlog and it will evaluate it on our next planning.

**Comment by Blankf** [comment]
Any update on this, we are about a year further now then the last comment on internal use.
would be nice to have this!

**Comment by nikdosev** [comment]
Hi, also looking for an update :)
I guess one workaround is to use an `azapi_resource` with the `azapi` provider.

**Comment by jlichwa** [comment]
Basic Constraints is not supported option by Key Vault service. That field can be changed or removed at any time.

**Comment by jkroepke** [comment]
> Hi, also looking for an update :) I guess one workaround is to use an `azapi_resource` with the `azapi` provider.

Sadly, Azure Keyvault Certificates are not supported by azapi

**Comment by philipstreet** [comment]
The lack of support for these attributes is rather disappointing given they are required when you want to use a self-signed certificate for TLS Inspection on an Azure Firewall (https://learn.microsoft.com/en-us/azure/firewall/premium-certificates#intermediate-ca-certificate-requirements).

I wanted to create this certificate in KV from Terraform because you don't need to generate a private key, but now it looks I'm going to have to create a CA certificate outside of Terraform and put up with the hassle this entails, i.e. creating a private key without storing it in the Terraform state.

**Comment by rcskosir** [comment]
Thanks for taking the time to open this issue. It looks like the behavior you requested is not supported by the underlying Azure API so I am going to label this issue as such and close it for now. If it gets added, we can reopen this request or you can create a new one.
