### ISSUE TITLE
Unable to increase minimum node count while autoscaling is enabled

### ISSUE THREAD

**Issue by pdefreitas** [hashicorp/terraform-provider-azurerm#9660]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

According to Microsoft, a fix has been rolled out to allow to enable increase of node count of a AKS cluster, when auto scaling is enabled [1].

#8007 perfectly describes the situation but it was closed by hashibot. Will this ever be implemented?

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### References

[1] https://github.com/Azure/AKS/issues/1758#issuecomment-689970088

**Comment by timja** [comment]
We just tested this out and I wasn't able to reproduce this anymore.

(We hit this back in February and raised a ticket on our backlog to fix it)

**Comment by katbyte** [comment]
@pdefreitas - can you confirm this is still an issue in the latest version of the provider? thanks

**Comment by tombuildsstuff** [comment]
Closing this out since we've not heard back here.
