### ISSUE TITLE
MySQL Server being created with public network access when created with GeoRestore

### ISSUE THREAD

**Issue by jjoynsonerwin** [hashicorp/terraform-provider-azurerm#9684]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version 0.13.5
AzureRM version 2.36.0

### Affected Resource(s)

* `azurerm_mysql_server`

### Terraform Configuration Files

```hcl
resource "azurerm_mysql_server" "core" {
  name                         = etc
  resource_group_name          = etc
  location                     = etc
  sku_name                     = "GP_Gen5_4"
  version                      = "8.0"
  administrator_login          = etc
  administrator_login_password = etc
  auto_grow_enabled            = true
  backup_retention_days        = 35
  create_mode                  = "GeoRestore"
  creation_source_server_id    = etc
  geo_redundant_backup_enabled = true
  infrastructure_encryption_enabled = false
  public_network_access_enabled     = false
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
  storage_mb                        = 102400
  tags                              = etc
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behaviour

MySQL server is created with Deny public network access set to "Yes" in the portal.

### Actual Behaviour

MySQL server is created with Deny public network access set to "No" in the portal.

### Steps to Reproduce

See deployment code above. If created using "Default" create_mode then the Deny public network access option is set correctly. Seems to be an issue using GeoRestore vs Default as this has been working correctly with Default for a while.

### Important Factoids

N/A

### References

N/A

**Comment by kingsleyadam** [comment]
I'm also running into this, if I run apply again it correctly sets the public access flag.

This means I always have to apply twice before the resource is correctly deployed.

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
