### ISSUE TITLE
new azurerm_function_app fails with "Cannot modify this site because another operation is in progress"

### ISSUE THREAD

**Issue by mattduguid** [hashicorp/terraform-provider-azurerm#9703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform = 0.13.4
azurerm = 2.31.0

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
  resource "azurerm_function_app" "azure" {
  name = var.function_app_name
  location = azurerm_resource_group.azure.location
  resource_group_name = azurerm_resource_group.azure.name
  app_service_plan_id = var.app_services_plan_id
  storage_account_name = azurerm_storage_account.azure.name
  storage_account_access_key = azurerm_storage_account.azure.primary_access_key
  version = "~3"
  site_config {
    always_on = true
    ftps_state = "FtpsOnly"
    linux_fx_version = "DOTNET|3.0" 
    min_tls_version = "1.2"
    use_32_bit_worker_process = false
  }
  identity {
    type = "SystemAssigned"
  }
  app_settings = var.function_app_settings
}
```
### Debug Output

Terraform output short error = "Service returned an error. Status='<'nil'>' '<'nil'>'"
Terraform output full error = https://gist.github.com/mattduguid/b50e73ffcda8b669fffba956742a6693

Terraform debug short error = "Message":"Cannot modify this site because another operation is in progress."
Terraform debug full error = https://gist.github.com/mattduguid/4d201d3eb1b221842238292d294fa3f3

### Expected Behaviour

A new function app would create first time.

### Actual Behaviour

Need to rerun until it succeeds. Most times this is once only but can take multiple runs.

### Steps to Reproduce

1. `terraform apply`

**Comment by mattduguid** [comment]
I hadn't used the optional attribute "os_type",

- os_type - (Optional) A string indicating the Operating System type for this function app.

Not specifying it results in "forces replacement",

- - os_type = "linux" -> null # forces replacement

When that ran it failed with the http 409 shown in terraform debug which looks like the gap between the delete and create operations wasn't long enough, this will also be why on retry it succeeds later,

module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Destroying... [id=/subscriptions/***MY_SUBSCRIPTION***/resourceGroups/***MY_RESOURCE_GROUP***/providers/Microsoft.Web/sites/***MY_FUNCTIONAPP***]
module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Destruction complete after 3s
module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Creating...
module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Still creating... [10s elapsed]
module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Still creating... [20s elapsed]
module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Still creating... [30s elapsed]
module.terraform-azure-***MY_MODULE***.azurerm_function_app.azure: Still creating... [40s elapsed]
Error: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

Workaround for me was to specify "os_type" as mandatory rather optional attribute.

Long term may need to make that attribute mandatory but if it needs to remains optional maybe a further check is required to wait until delete operation is fully complete?

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
