### ISSUE TITLE
azurerm_api_management_policy key  error

### ISSUE THREAD

**Issue by prateikjaiswal** [hashicorp/terraform-provider-azurerm#9708]
In documentation, `azurerm_api_management_policy` key `apim_management_id` should be `api_management_id` instead of `apim_management_id`

**Comment by woozar** [comment]
+1

**Comment by sherzberg** [comment]
This looks like it was fixed here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/10497

**Comment by tombuildsstuff** [comment]
fixed via #10497, thanks for the heads up #10497
