### ISSUE TITLE
azurerm_dev_test_schedule - webhook_url not set // mail address

### ISSUE THREAD

**Issue by MaxiPalle** [hashicorp/terraform-provider-azurerm#9758]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform 0.13.5
AzureRM 2.39

### Affected Resource(s)

* `azurerm_dev_test_schedule`

### Terraform Configuration Files

```hcl
resource "azurerm_dev_test_schedule" "schedule-lab1" {
  name                = "LabVmsShutdown"
  location            = azurerm_resource_group.dtl-lab1.location
  resource_group_name = azurerm_resource_group.dtl-lab1.name
  lab_name            = azurerm_dev_test_lab.lab1.name
  status              = "Enabled"

  daily_recurrence {  
    time      = "1900"
  }

  time_zone_id = "Central European Standard Time"
  task_type    = "LabVmsShutdownTask"

  notification_settings {
    status          = "Enabled"
    time_in_minutes = "30"
    webhook_url     = "someone@domain.tld"
  }
}
```

### Debug Output

```bash
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

azurerm_dev_test_schedule.schedule-lab1: Modifying... [id=/subscriptions/<subscription-id>/resourcegroups/rg-dtl-lab1/providers/microsoft.devtestlab/labs/devtestlab1/schedules/labvmsshutdown]
azurerm_dev_test_schedule.schedule-lab1: Modifications complete after 3s [id=/subscriptions/<subscription-id>/resourcegroups/rg-dtl-lab1/providers/microsoft.devtestlab/labs/devtestlab1/schedules/labvmsshutdown]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Expected Behaviour

Setting mail address to webhook_url.

### Actual Behaviour

Nothing set in Azure portal; neither in 'Webhhok url' nor in 'Email address'.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
