### ISSUE TITLE
Getting "Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded" when running over 2000 DNS Records

### ISSUE THREAD

**Issue by IQ-OO** [hashicorp/terraform-provider-azurerm#9816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5 (also tried Terraform v0.14, same error)
+ provider registry.terraform.io/hashicorp/azurerm v2.39.0

### Affected Resource(s)

azurerm_dns_a_record
azurerm_dns_cname_record

### Terraform Configuration Files

The A and CNAME records are very similar to what is below except that are over 1000 records for each
```hcl
provider "azurerm" {
#    version="2.39"
    features {}
}

resource "azurerm_resource_group" "example" {
  name     = "large-rg"
  location = "West US"
}

resource "azurerm_dns_zone" "example" {
  name                = "dnsrecords.com"
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_dns_a_record" "arecord" {
        name                = " arecord "
        zone_name           = " dnsrecords.com"
        resource_group_name = "large-rg"
        ttl                 = 300
        records             = ["1.1.1.1"]
}

resource "azurerm_dns_cname_record" "cname" {
        name                = "cname"
        zone_name           = " dnsrecords.com"
        resource_group_name = "large-rg"
        ttl                 = 300
        record              = "testing.trafficmanager.net."
}

```

### Debug Output

`2020/12/09 17:11:22 [TRACE] eval: *terraform.EvalWriteState
2020/12/09 17:11:22 [TRACE] EvalWriteState: recording 1 dependencies for azurerm_dns_zone.example
2020/12/09 17:11:22 [TRACE] EvalWriteState: writing current state object for azurerm_dns_zone.example
2020/12/09 17:11:22 [TRACE] [walkRefresh] Exiting eval tree: azurerm_dns_zone.example
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example": visit complete
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example": dynamic subgraph completed successfully
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example": visit complete
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example (expand)": dynamic subgraph completed successfully
2020/12/09 17:11:22 [TRACE] vertex "azurerm_dns_zone.example (expand)": visit complete
2020/12/09 17:11:22 [TRACE] dag/walk: upstream of "provider[\"registry.terraform.io/hashicorp/azurerm\"] (close)" errored, so skipping
2020/12/09 17:11:22 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020/12/09 17:11:22 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/12/09 17:11:22 [TRACE] statemgr.Filesystem: unlocked by closing terraform.tfstate
2020-12-09T17:11:22.725-0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/hashicorp/azurerm/2.39.0/windows_amd64/terraform-provider-azurerm_v2.39.0_x5.exe pid=18812
2020-12-09T17:11:22.725-0800 [DEBUG] plugin: plugin exited`

### Expected Behaviour

Should be able to generate the 2000+ A and CNAME records

### Actual Behaviour

Getting  “dns.RecordSetsClient#Get: Failure sending request: StatusCode=429 -- Original Error: context deadline exceeded” when running terraform apply

### Steps to Reproduce

`terraform apply`

**Comment by thatshumbug** [comment]
Any news or insight on this one?

**Comment by dan-leanix** [comment]
Whatever it is it was introduced with the Terraform Azure provider 2.x versions from the very beginning. We could reproduce it with version 2.1.0. So, I assume that this exists since version 2.0.0.

Terraform Azure provider version 1.44.0 just works.

**Comment by krowlandson** [comment]
Interesting observation @dan-leanix... I've not had a chance to pinpoint the exact point where it became the primary method of controlling requests to the AzureRM API, but the autorest client was introduced from v2.3.0 so I suspect there was a general effort from v2.0.0 to change the way the provider interacts with the API.

In our particular case, there has clearly been a change on the platform side which is resulting in a provider throttling requests when it didn't previously. However 429 responses are common across most others, including the DNS service as mentioned in [Creating Over 2000 DNS Records Gives me StatusCode=429 hashicorp/terraform#27266](https://github.com/hashicorp/terraform/issues/27266).

Unfortunately it seems that when running high numbers of parallel tasks against the same API (on an individual Resource Provider / Service), Terraform isn't correlating related HTTP/429 responses, so the backoff isn't aggressive enough to let the API rate limiting to be lifted.

**Comment by magodo** [comment]
@IQ-OO This seems to be the same issue as #14213? You might check the solution [here](https://github.com/hashicorp/terraform-provider-azurerm/issues/14213#issuecomment-970549257), where you might want to increase the read timeout a bit. Currently, the provider will infinitely retry on 429, until timeout.

On the other hand, you might want to decrease the `-parallelism` to avoid the probability of a resource starving on 429 until timeout (imagine it is set as `1` as an extream example).

**Comment by magodo** [comment]
@IQ-OO Increasing the timeout without an apply will cause the plan continue using the old timeout, see https://github.com/hashicorp/terraform/issues/31023 for workarounds...

**Comment by md2k** [comment]
Hi all, have the same issue, but i did patch for state file to trick timeouts for read for all target resources and it is still the same... after 5 min tf gives up and i have `context deadline exceeded`.  I have strong feelings that on state refresh `azurerm` doesn't respect custom timeouts.

**Comment by md2k** [comment]
also for me default timeout for read operations in provider looks weird, default read timeout 5min, while azure API on `ResourceRequestsThrottled` asking to wait for 307 seconds. For me default timeout should cover at least first threshold.

```
HTTP/2.0 429 Too Many Requests
Content-Length: 245
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Expires: -1
Pragma: no-cache
Retry-After: 307 <----
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Ms-Correlation-Request-Id: 66787420-22fb-8723-b962-1b7ec88b426d
X-Ms-Failure-Cause: gateway
X-Ms-Request-Id: xxxxxxxx
X-Ms-Routing-Request-Id: xxxxxxxxx
```
```json
{
  "error": {
    "code": "ResourceRequestsThrottled",
    "message": "Number of requests for action Microsoft.Network/privateDnsZones/virtualNetworkLinks/read exceeded the limit of 500 for time interval 00:05:00. Please try again after 307 seconds."
  }
}
```

**Comment by magodo** [comment]
@md2k The command you used to change above only changed the timeout value in the config. While Terraform is using the timeout value stored in the `private` attribute. Please:

- Either make a dummy change for all these resources to trigger an apply (with -fresh=false to avoid refreshing)
- Or recreate all these resources with timeout set before apply

**Comment by md2k** [comment]
Ok i found myself, only not sure what UID means there. why all those complications... rhetorical question

**Comment by magodo** [comment]
@md2k There is an issue opened in the SDK repo for this: https://github.com/hashicorp/terraform-plugin-sdk/issues/963.

**Comment by md2k** [comment]
@magodo  i still think this is partly azurerm provider issue, because Azurre API asking to wait for 307 seconds, so default timeout for read should at least cover 1 retry. so default to 6 min will solve lot of problems. Want me to repost my solution to ticket in sdk ticket ?

**Comment by magodo** [comment]
@md2k You can definitely add the manual modification as a 3rd workaround (while it might be difficult to follow for users who use remote backend). Regarding the timeout value, yes, I can make that change.
