### ISSUE TITLE
container_image_names not expected

### ISSUE THREAD

**Issue by tonytilbo** [hashicorp/terraform-provider-azurerm#9868]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.4.0

### Affected Resource(s)

azurerm_batch_pool

### Terraform Configuration Files
```hcl
resource "azurerm_batch_pool" "batchpool" {
  container_configuration {
    type = "DockerCompatible"
    container_registries {
      registry_server = var.container_registry.location
      user_name       = var.container_registry.username
      password        =  var.container_registry.password
    }
    container_image_names = ["image1", "image2"]
  }
}

```

### Expected Behaviour

When using 2.12 we was able to set the container_image_names when updating to 2.4 it fails with the error below.

### Actual Behaviour

An argument named "container_image_names" is not expected here.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
