### ISSUE TITLE
Unable to deploy VpnGw2AZ or others with resource azurerm_virtual_networkg_gateway

### ISSUE THREAD

**Issue by XavierGeerinck** [hashicorp/terraform-provider-azurerm#9892]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
AzureRM Provider > 2.38 (tested on 2.40 as well)

### Affected Resource(s)

* `azurerm_virtual_network_gateway`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network_gateway" "vg_hub" {
  name                = "vgw-${var.name}-hub-glb-${var.location_shortcode}-vpn"
  location            = var.location
  resource_group_name = var.rg_hub_network_name

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false

  # https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways
  # We utilize this SKU since it supports 30 tunnels and has 1.25 Gbps throughput support + Zone-redundancy
  # Note: pricing is $0.564/hr
  sku           = "VpnGw2" 
  generation     = "Generation2" # required for Gw2AZ

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = azurerm_public_ip.pip_hub_vpn_gateway1.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = [for x in tolist(azurerm_virtual_network.vnet_hub.subnet): x.id if x.name == "GatewaySubnet"][0]
  }

  depends_on = [azurerm_virtual_network.vnet_hub, azurerm_public_ip.pip_hub_vpn_gateway1]
}
```

### Expected Behaviour

Should work and create a VNET Gateway with the SKU "VpnGw1AZ"

### Actual Behaviour

![image](https://user-images.githubusercontent.com/591282/102367038-9b2f4c80-3fb9-11eb-993b-e5b17864f062.png)

### Important Factoids

#3314 had the same issue and was closed in #3362, but this seems to be unrelated? When trying to deploy through the AzurePortal, everything goes well

**Comment by ruandersMSFT** [comment]
@XavierGeerinck  Do you already have a Generation1 Gateway deployed and you are now trying to deploy a Generation2 Gateway?  The output in the error message is limited to the Generation1 SKUs, leading me to think a Generation1 gateway is already deployed and now you are trying to upgrade to a Generation2 gateway?

[Gateway SKUs](https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpn-gateway-settings#gwsku)

Your code sample above clearly shows Generation2; however, given the error list is limited to Generation1 SKUs, it leads me to believe the Gateway is already deployed of the older Generation.

**Comment by XavierGeerinck** [comment]
Hi @ruandersMSFT, so I have tried removing all the resources again right now and no gateways exist on the Tenant now. Generation = `Generation2` and sku = `VpnGw2AZ` 

Some observations:
* When I made a "typo" and wrote `VpnGWAZ2` it complained before already, not passing the validation step of Terraform
* When I then fixed the typo, the plan got updated and looked promising: `~ sku                        = "VpnGw2" -> "VpnGw2AZ"`

When this plan was executing, I got the same issue: 

```
Error: Error Creating/Updating AzureRM Virtual Network Gateway "vgw-primary-hub-glb-we-vpn" (Resource Group "hub-glb-network"): network.VirtualNetworkGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidGatewaySkuSpecifiedForGatewayDeploymentType" Message="Virtual network gateway Sku specified is not valid for gateway /subscriptions/00170083-ede8-45bd-b70b-b881a5bb648a/resourceGroups/hub-glb-network/providers/Microsoft.Network/virtualNetworkGateways/vgw-primary-hub-glb-we-vpn with DeploymentType CloudService. The allowed Skus are Basic,Standard,HighPerformance,VpnGw1,VpnGw2,VpnGw3,UltraPerformance,VpnGw4,VpnGw5." Details=[]
```

So could I be correct to assume that this is an Azure API issue? Seeing that it happens during deployment itself?

**Comment by ruandersMSFT** [comment]
Looks like a Terraform bug.  I was able to reproduce the issue, and get the same error message ("The allowed Skus are Basic,Standard,HighPerformance,VpnGw1,VpnGw2,VpnGw3,UltraPerformance,VpnGw4,VpnGw5.").  

The Terraform sample code used was:

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 2.41"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "resourceGroup1"
  location = "West US"
}

resource "azurerm_virtual_network" "example" {
  name                = "virtualNetwork1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]

  subnet {
    name           = "GatewaySubnet"
    address_prefix = "10.0.1.0/24"
  }

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.2.0/24"
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.3.0/24"
  }
}

resource "azurerm_public_ip" "example" {
  name                = "PublicIp1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Dynamic"
}

data "azurerm_subnet" "GatewaySubnet" {
  name                 = "GatewaySubnet"
  virtual_network_name = "virtualNetwork1"
  resource_group_name  = "resourceGroup1"
  depends_on = [azurerm_virtual_network.example]
}

resource "azurerm_virtual_network_gateway" "vg_hub" {
  name                = "Gateway1"
  location            = azurerm_resource_group.example.location
  resource_group_name = "resourceGroup1"

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false

  # https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways
  # We utilize this SKU since it supports 30 tunnels and has 1.25 Gbps throughput support + Zone-redundancy
  # Note: pricing is $0.564/hr
  sku           = "VpnGw2AZ" 
  generation     = "Generation2" # required for VpnGw2AZ

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = azurerm_public_ip.example.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = data.azurerm_subnet.GatewaySubnet.id
  }

  depends_on = [azurerm_virtual_network.example, azurerm_public_ip.example]
}
```

**Comment by ruandersMSFT** [comment]
Hi @XavierGeerinck,

What location are you deploying to via _var.location_?

I was able to reproduce your exact error message ("... with DeploymentType CloudService. The allowed Skus are Basic,Standard,HighPerformance,VpnGw1,VpnGw2,VpnGw3,UltraPerformance,VpnGw4,VpnGw5.").

My primary recommendation is to review what region your are deploying in, as VpnGw2AZ may not be available in your target region.  I was able to successfully deploy a VpnGw2AZ gateway with Terraform 2.41.0 using the sample below.  Also, consider your Public IP configuration (in my example below Static allocation_method and Standard sku for [Zone Redundant](https://docs.microsoft.com/en-us/azure/vpn-gateway/about-zone-redundant-vnet-gateways#pipskus) deployment).

The following sample worked my EastUS test; however, it did not for WestUS.  I believe you may be deploying to a region where VpnGw2AZ is not yet available.

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 2.41"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "resourceGroup1"
  location = "EastUS"
}

resource "azurerm_virtual_network" "example" {
  name                = "virtualNetwork1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  address_space       = ["10.0.0.0/16"]
  dns_servers         = ["10.0.0.4", "10.0.0.5"]

  subnet {
    name           = "GatewaySubnet"
    address_prefix = "10.0.1.0/24"
  }

  subnet {
    name           = "subnet1"
    address_prefix = "10.0.2.0/24"
  }

  subnet {
    name           = "subnet2"
    address_prefix = "10.0.3.0/24"
  }
}

resource "azurerm_public_ip" "example" {
  name                = "PublicIp1"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Static"
  sku                 = "Standard"
}

data "azurerm_subnet" "GatewaySubnet" {
  name                 = "GatewaySubnet"
  virtual_network_name = "virtualNetwork1"
  resource_group_name  = "resourceGroup1"
  depends_on = [azurerm_virtual_network.example]
}

resource "azurerm_virtual_network_gateway" "vg_hub" {
  name                = "Gateway1"
  location            = azurerm_resource_group.example.location
  resource_group_name = "resourceGroup1"

  type     = "Vpn"
  vpn_type = "RouteBased"

  active_active = false
  enable_bgp    = false

  # https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-about-vpngateways
  # We utilize this SKU since it supports 30 tunnels and has 1.25 Gbps throughput support + Zone-redundancy
  # Note: pricing is $0.564/hr
  sku           = "VpnGw2AZ" 
  generation     = "Generation1"

  ip_configuration {
    name                          = "vnetGatewayConfig"
    public_ip_address_id          = azurerm_public_ip.example.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = data.azurerm_subnet.GatewaySubnet.id
  }

  depends_on = [azurerm_virtual_network.example, azurerm_public_ip.example]
}```

**Comment by ruandersMSFT** [comment]
As an additional example, VpnGwAZ is available in West US 2, but not West US.

**Comment by XavierGeerinck** [comment]
Hi @ruandersMSFT!

Thank you so much for checking this in so much detail!!! This helped me a lot. 

I have reviewed the configuration and it indeed seems that my PIP was Dynamically allocated instead of Static. I have changed it now to the following:

```hcl
resource "azurerm_public_ip" "pip_hub_fw" {
  name                = "pip-${var.name}-hub-${var.location_shortcode}-fw"
  location            = var.location
  resource_group_name = var.rg_hub_network_name

  allocation_method = "Static" # should be static for firewall
  sku               = "Standard" # The Public IP must have a Static allocation and Standard sku.
}
```

I am currently waiting for a review internally and will come back on this as soon as I was able to test this (we are working on a more complex setup with UDR, IPG, ... and changing the VpnGw will require some recreation at the moment with some manual changes we still have to port over).

I'll keep you updated from as soon as I know more (most likely after the holidays) 😊 but I am confident this will be able to solve it for us!!! thanks again!!

**Comment by mattshort77** [comment]
@XavierGeerinck did you ever solve this? I've got a very similar issue.

**Comment by mattshort77** [comment]
`My primary recommendation is to review what region your are deploying in, as VpnGw2AZ may not be available in your target region.`

Great suggestion, but i can't find this listed in the documentation. Also, the AZ CLI commands for virtual network gateways dont list the sku compatability, in the same way that it does for VMs.

**Comment by ruandersMSFT** [comment]
@mattshort77 Keep in mind that the "AZ" version of the Gateway is the Zone Redundant (use of Availability Zones) version of the Azure Gateway.  The Azure region you are using will have to support Availability Zones.  Refer to (Azure Regions with Availability Zones)[https://docs.microsoft.com/en-us/azure/availability-zones/az-region#azure-regions-with-availability-zones]

**Comment by picardsrcd** [comment]
I'd love a command to see what is available in a region. In CanadaCentral, a region with AZ's, this combo is not allowed:
```
  generation = "Generation2"
  sku        = "VpnGw2AZ"
```

Falling back to 
```
  generation = "Generation2"
  sku        = "VpnGw2"
```

**Comment by picardsrcd** [comment]
nvm i had to change the public ip to standard / static, then the SKU became available :)

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
