### ISSUE TITLE
Inconsistent final plan (app service, system managed identity + role assignment)

### ISSUE THREAD

**Issue by flobeier** [hashicorp/terraform-provider-azurerm#9893]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform: `0.14.0`
AzureRM Provider: `v2.39.0`

### Affected Resource(s)

* `azurerm_app_service`
* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "app_service_api" {
  resource_group_name = data.azurerm_resource_group.resource_group.name
  location            = data.azurerm_resource_group.resource_group.location
  app_service_plan_id = azurerm_app_service_plan.app_service_plan.id
  name                = local.api_app_name

  identity {
    type         = "SystemAssigned, UserAssigned"
    identity_ids = [
      azurerm_user_assigned_identity.api_identity.id]
  }
}

resource "azurerm_role_assignment" "api_app_storage_contributor" {
  scope = azurerm_storage_account.blob_storage.id
  role_definition_name = "Storage Account Contributor"
  principal_id = azurerm_app_service.app_service_api.identity.0.principal_id
}
```

### Expected Behaviour

Create system assigned managed identity and apply the role assignment.

### Actual Behaviour

System managed identity has been created but the role assignment failed with the following error:
```
Error: Provider produced inconsistent final plan

When expanding the plan for
azurerm_role_assignment.api_app_storage_contributor to include new values
learned so far during apply, provider
"registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
.principal_id: was cty.StringVal(""), but now
cty.StringVal("89b35uy7-21o1-1n8l-ho3i-8bxa6n2v6s19"). # (Values not real, changed for privacy reasons)

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```
Running `terraform apply` again after the error occured was successful.

### Steps to Reproduce

1. Create `azurerm_app_service` resource with user assigned managed identity and run `terraform apply`
2. Add system assigned managed identity to `azurerm_app_service` resource together with a role assignment for it
3. Run `terraform apply`

### References

* #0000

**Comment by Tailzip** [comment]
Hi, I can confirm this is happening for us as well, not with `azurerm_role_assignment` resource but with `azurerm_key_vault_access_policy`.

```hcl
resource "azurerm_key_vault_access_policy" "bug" {
  key_vault_id = azurerm_key_vault.self.id
  tenant_id    = data.azurerm_client_config.current.tenant_id
  object_id    = azurerm_app_service.self.identity.0.principal_id

  secret_permissions = [
    "get",
    "list"
  ]
}
```

```shell
Error: expected "object_id" to be a valid UUID, got 

  on main.tf line 113, in resource "azurerm_key_vault_access_policy" "bug":
 113: resource "azurerm_key_vault_access_policy" "bug" {
```

We noticed that if `azurerm_app_service` resource is created **from scratch** with both `"SystemAssigned, UserAssigned"` identities, it works just fine. Only updating the `identity` block in place produces that error.

As a workaround, we had to taint the `azurerm_app_service` to force its re-creation with both identities.

**Comment by flobeier** [comment]
@Tailzip just today I ran into this error again, this time with `azurerm_key_vault_access_policy` too. I wanted to update an existing policy but got the now familiar error again:

> Error: Provider produced inconsistent final plan
> 
> When expanding the plan for
> module.sql_admin_automation_key_vault[0].azurerm_key_vault.key_vault to
> include new values learned so far during apply, provider
> "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for
> .access_policy[4].object_id: was
> cty.StringVal("xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"), but now
> cty.StringVal("xxxxx-xxxxx-xxxxx-xxxxx-xxxxx").
> 
> This is a bug in the provider, which should be reported in the provider's own
> issue tracker.

**Comment by xaviergxf** [comment]
I'm having the same problem 

```
expected "principal_id" to be a valid UUID, got 
```

when assigning the role with:
```
resource "azurerm_cosmosdb_sql_role_assignment" "cosmosDbApiRoleAssignment" {
  name                = "D7FD79BF-F929-4B72-BC5D-E6BC0E3A3FE9"
  resource_group_name = var.resourceGroupName
  account_name        = azurerm_cosmosdb_account.customerDbAccount.name
  role_definition_id  = azurerm_cosmosdb_sql_role_definition.cosmosDbReadWriteRole.id
  principal_id        = azurerm_function_app.customerApiApp.identity.0.principal_id
  scope               = azurerm_cosmosdb_sql_database.customerDbSqlDb.id

  depends_on = [
    azurerm_function_app.customerApiApp,
    azurerm_cosmosdb_account.customerDbAccount,
    azurerm_cosmosdb_sql_role_definition.cosmosDbReadWriteRole,
    azurerm_cosmosdb_sql_role_assignment.cosmosDbDevRoleAssignment
  ]
}
```

**Comment by abuarbaz** [comment]
Is there any plan to fix this issue? As we are facing problem with our eventgrid_topic where we are trying to update userassigned identity to systemassigned identity?

Error: Provider produced inconsistent final plan

│

│ When expanding the plan for

│ module.basic-infrastructure.azurerm_role_assignment.system_identity to

│ include new values learned so far during apply, provider

│ "registry.terraform.io/hashicorp/azurerm" produced an invalid new value for

│ .principal_id: was cty.StringVal(""), but now

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
