### ISSUE TITLE
Import of azurerm_mssql_database does not detect existing geo-replication settings

### ISSUE THREAD

**Issue by phatcher** [hashicorp/terraform-provider-azurerm#9894]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
+ provider registry.terraform.io/hashicorp/azurerm v2.40.0

### Affected Resource(s)

* `azurerm_mssql_server`

### Expected Behaviour

I should be able to import databases that are already geo-replicating

### Actual Behaviour

The [sample code](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/sql-azure/failover_group) works fine for creating geo replication and failover group. However, if I import databases that are already a geo-replication setup, the CreateMode and primary database ids are not present, so it wants to destroy and re-create my replica.

### Steps to Reproduce

1. Create databases in two regions and setup geo-replication
2. Import into the state file
3. `terraform apply`

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
