### ISSUE TITLE
Support for client certificate on app_service etc

### ISSUE THREAD

**Issue by phatcher** [hashicorp/terraform-provider-azurerm#9956]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current value is a bool, whereas from the portal this is a bit more complex...

![image](https://user-images.githubusercontent.com/192778/102726598-fc3b8500-4317-11eb-8002-6e48de1339dc.png)

### New or Affected Resource(s)

* azurerm_app_service
* azurerm_app_service_slot
* azurerm_function_app
* azurerm_function_app_slot

**Comment by phatcher** [comment]
Also I noticed that azurerm_app_service_slot currently does not even have the bool property `client_cert_enabled`

**Comment by CaptainStealthy** [comment]
This is partially covered by #7849. I posted a workaround in that thread for `azurerm_app_service`.

https://github.com/terraform-providers/terraform-provider-azurerm/issues/7849#issuecomment-827745718

**Comment by favoretti** [comment]
Thank you for opening this issue. Closing in favor of #7849 to keep the discussion concise.
