### ISSUE TITLE
Empty start_time in azurerm_data_factory_trigger_schedule leads to invalid trigger state

### ISSUE THREAD

**Issue by markusgulden** [hashicorp/terraform-provider-azurerm#9983]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/azurerm v2.41.0
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* `azurerm_data_factory_trigger_schedule`

### Terraform Configuration Files

Example is taken from the official documentation at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_trigger_schedule#example-usage
```hcl
resource "azurerm_data_factory_trigger_schedule" "test" {
  name                = "example"
  data_factory_name   = azurerm_data_factory.test.name
  resource_group_name = azurerm_resource_group.test.name
  pipeline_name       = azurerm_data_factory_pipeline.test.name

  interval  = 5
  frequency = "Day"
}
```

### Expected Behaviour

The start_time attribute is described as follows:  _(Optional) The time the Schedule Trigger will start. This defaults to the current time. The time will be represented in UTC._
So I would expect a trigger with the current time as start_time, if using the example from the documentation.

### Actual Behaviour

When leaving start_time empty, a trigger with an invalid start_time is created:
![image](https://user-images.githubusercontent.com/24793790/102910368-71a67300-4448-11eb-8a5f-4697fb9883a2.png)

### References

* #0000

**Comment by rcskosir** [comment]
Thanks for opening this issue. This was a problem in the 2.x version of the provider which is no longer actively maintained.
If this is still an issue with the 3.x version of the provider please do let us know by opening a new issue, thanks!
